### ISSUE TITLE
Is Magisk caused the problem with system boot?

### ISSUE THREAD

**Issue by x86-app** [topjohnwu/Magisk#1002]
I'm using **RR-OS 6.x.x (Android 8) running on Redmi Note 3 (kenzo)**. Today I tried to install zip pack of RR-OS 7.0.0 (Android 9). The installer looks installed Magisk 18 the last, but **after reboot Magisk Manager says there's no Magisk installed.** 
**I entered to TWRP and flashed Magisk's package, and... It can't boot up.** The phone stucked at booting. 
Only RR-OS logo on the screen and when long-pressed the power key the phone vibrates for little time. **But it turns fine after system partition cleared and OS package re-flashed.**
Is the problem caused by Magisk? 
Thanks.

**Comment by x86-app** [comment]
I just tried Magisk 17.2 the version I used before the update, it works perfectly with RR-OS 7.0.0.

**Comment by topjohnwu** [comment]
Github issues is not a support platform
