### ISSUE TITLE
Installation fail when I try a direct update

### ISSUE THREAD

**Issue by mikhoul** [topjohnwu/Magisk#1006]
Why Installation fail when I try a direct update ? 

![image](https://user-images.githubusercontent.com/5678673/52132006-3b6d6980-260c-11e9-923b-383f0162edaa.png)

![image](https://user-images.githubusercontent.com/5678673/52131944-21338b80-260c-11e9-8aea-e67aad69dcba.png)

It's on with MECOOL M8S Pro+ TV Box Amlogic S905X Android 7.1.

Regards :octocat:

**Comment by topjohnwu** [comment]
Please test on canary channel, this is already fixed
