### ISSUE TITLE
Modules won't mount

### ISSUE THREAD

**Issue by JERW86** [topjohnwu/Magisk#1010]
When I tried to update a module through twrp or MM, the module installed as expected but will not mount. I appriciate your hard work. Thank you

[magisk.log](https://github.com/topjohnwu/Magisk/files/2823217/magisk.log)
Phone Moto G4 xt1625
Android 9.0
Custom rom: ArrowOS
Magisk 18.1 (18008) debug

**Comment by topjohnwu** [comment]
It is 99.999% F2FS driver issue. A completely new implementation will come eventually, but before that there is nothing I can do on my side. You can either format your data to EXT4, or update your custom kernel to include proper F2FS drivers.

**Comment by JERW86** [comment]
I double checked and my /data partition is formated to ext4. I hope you will fix the issue.
