### ISSUE TITLE
Magisk Manager v6.1 crash with network on

### ISSUE THREAD

**Issue by davidngrc** [topjohnwu/Magisk#1013]
I uncheck the “check update” option in setting
but when I launch Magisk Manager v6.1, the update icon is looping, and then crash.
if I put the phone into airplane mode, then it will launch normally, no more crash.

below is the cat log

build.board: unknown
build.bootloader: unknown
build.brand: unknown
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: unknown
build.display: unknown
build.fingerprint: google/shamu/shamu:7.1.1/N6F27M/4299435:user/release-keys
build.hardware: unknown
build.host: unknown
build.id: unknown
build.manufacturer: unknown
build.model: unknown
build.product: unknown
build.radio: unknown
build.serial: xxxxxxx
build.tags: unknown
build.time: 0
build.type: unknown
build.user: unknown
version.codename: REL
version.incremental: a7b325f540
version.release: 8.1.0
version.sdk_int: 27

02-02 09:17:20.411 I/ActivityManager(845): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/a.c (has extras)} from uid 10116
02-02 09:17:20.723 I/ActivityManager(845): START u0 {cmp=com.topjohnwu.magisk/a.b (has extras)} from uid 10143
02-02 09:17:21.199 W/opjohnwu.magisk(16100): type=1400 audit(0.0:4338): avc: denied { read } for name="event-log-tags" dev="tmpfs" ino=11458 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:runtime_event_log_tags_file:s0 tclass=file permissive=0
02-02 09:17:21.463 I/ActivityManager(845): Displayed com.topjohnwu.magisk/a.b: +590ms (total +1s9ms)
02-02 09:17:22.829 E/AndroidRuntime(16100): Process: com.topjohnwu.magisk, PID: 16100
02-02 09:17:22.844 W/ActivityManager(845): Process com.topjohnwu.magisk has crashed too many times: killing!
02-02 09:17:22.844 W/ActivityManager(845):   Force finishing activity com.topjohnwu.magisk/a.b
02-02 09:17:22.855 I/WindowManager(845): Failed to capture screenshot of Token{bfb36f2 ActivityRecord{2e679fd u0 com.topjohnwu.magisk/a.b t286 f}} appWin=Window{42cbe9f u0 com.topjohnwu.magisk/a.b} drawState=4
02-02 09:17:22.865 E/BufferQueueProducer(266): [com.topjohnwu.magisk/a.b#0] queueBuffer: BufferQueue has been abandoned
02-02 09:17:22.875 E/ActivityManager(845): Found activity ActivityRecord{2e679fd u0 com.topjohnwu.magisk/a.b t-1 f} in proc activity list using null instead of expected ProcessRecord{f9883c6 16100:com.topjohnwu.magisk/u0a143}
02-02 09:17:22.890 I/ActivityManager(845): Killing 16100:com.topjohnwu.magisk/u0a143 (adj 199): crash
02-02 09:17:42.053 I/ActivityManager(845): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/a.c bnds=[251,1641][444,1862] (has extras)} from uid 10116
02-02 09:17:42.140 I/ActivityManager(845): Start proc 16627:com.topjohnwu.magisk/u0a143 for activity com.topjohnwu.magisk/a.c
02-02 09:17:42.225 I/XLua.Xposed(16627): Loaded com.topjohnwu.magisk:10143
02-02 09:17:43.429 I/ActivityManager(845): START u0 {cmp=com.topjohnwu.magisk/a.b (has extras)} from uid 10143
02-02 09:17:43.902 W/opjohnwu.magisk(16627): type=1400 audit(0.0:4402): avc: denied { read } for name="event-log-tags" dev="tmpfs" ino=11458 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:runtime_event_log_tags_file:s0 tclass=file permissive=0
02-02 09:17:44.254 I/ActivityManager(845): Displayed com.topjohnwu.magisk/a.b: +677ms (total +2s151ms)
02-02 09:18:08.244 I/Magisk  (316): proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[16820] ns=[4026545252]
02-02 09:18:11.341 I/ActivityManager(845): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/a.c (has extras)} from uid 10116
02-02 09:18:11.583 I/ActivityManager(845): START u0 {cmp=com.topjohnwu.magisk/a.b (has extras)} from uid 10143
02-02 09:18:12.031 I/ActivityManager(845): Displayed com.topjohnwu.magisk/a.b: +406ms (total +660ms)
02-02 09:18:13.729 E/AndroidRuntime(16627): Process: com.topjohnwu.magisk, PID: 16627
02-02 09:18:13.741 W/ActivityManager(845):   Force finishing activity com.topjohnwu.magisk/a.b
02-02 09:18:13.787 I/ActivityManager(845): Showing crash dialog for package com.topjohnwu.magisk u0
02-02 09:18:15.090 I/ActivityManager(845): Killing 16627:com.topjohnwu.magisk/u0a143 (adj 900): crash

**Comment by topjohnwu** [comment]
I need a logcat, not Magisk logs. Please read instruction before opening a new issue

**Comment by davidngrc** [comment]
this is from logcat

**Comment by Jackktheslayer95** [comment]
Hohoh

**Comment by topjohnwu** [comment]
It does not happen on the lastest Magisk Manager, it is probably caused by the "Xposed" you are using
