### ISSUE TITLE
Show system app(s)

### ISSUE THREAD

**Issue by DevDef** [topjohnwu/Magisk#1019]
https://github.com/topjohnwu/Magisk/blob/56d2fb9a3b06d136d1586556b676a26c7d27eedc/app/src/full/res/values/strings.xml#L222

Hi,
Is there really several apps or are you talking about Magisk Manager app?
In the second case, “Show system apps” should be singular : “Show system app”.

Regards,

Davy

**Comment by topjohnwu** [comment]
System apps are apps installed in the factory image, so yes it is plural

**Comment by DevDef** [comment]
OK, I see. But in that case the name of the string should be show_system_apps, accordingly.
