### ISSUE TITLE
Device Support: Google Pixel

### ISSUE THREAD

**Issue by crivchri** [topjohnwu/Magisk#102]
Hi, just wanting to ask for support of Google Pixel.

Link to current factory image: https://dl.google.com/dl/android/aosp/sailfish-nof26v-factory-65092b38.zip

Hope to hear about this soon. Thank you!

**Comment by Didgeridoohan** [comment]
https://forum.xda-developers.com/showpost.php?p=71133174&postcount=16

**Comment by Whoopie** [comment]
duplicate #47
