### ISSUE TITLE
F-Droid and bootctl 

### ISSUE THREAD

**Issue by licaon-kter** [topjohnwu/Magisk#1023]
I'd like to add MagiskManager to F-Droid, and it builds fine and dandy.

The F-Droid policy is to have everything FOSS and built from source, but I see that `bootctl` is a binary. 

Is this binary build from https://android.googlesource.com/platform/system/extras/+/master/bootctl or taken from somewhere else?

While being licensed under Apache 2.0 (if the repo above is the source) makes it compatible with a GPL3 app ( I'm no lawyer, I just read https://www.apache.org/licenses/GPL-compatibility.html ), we kinda need to build it from sources to be able to include it.

So two questions:
* could this be build standalone without the need to build the whole AOSP?
* if not, could this be separated like `SafetyNet` part was?

Thanks

Ref: https://gitlab.com/fdroid/fdroiddata/merge_requests/4401/diffs

**Comment by topjohnwu** [comment]
@licaon-kter it doesn't seem easy or even possible to separate it from AOSP tree since it is deep into the whole HIDL stuff. Can I host it somewhere on a server, and download when I need it?

**Comment by licaon-kter** [comment]
How much is that needed? From what I parsed it's used in Pie for the A/B stuff or maybe I've misread...

Is it easy to move it (the coding part) to download as needed?

**Comment by topjohnwu** [comment]
Yes it is, I think I'll just go that route :)

**Comment by DenyDarko** [comment]
Just a personal opinion here.

Can't see why a magisk core function (most modern devices are A/B, thus the "core" term)  controlling boot should be separated from main code for it to be included in f-droid. It's not an optional check like safetynet.

Magisk has it's own update process and everything.

Does it even worth it?

IMHO if F-Droid wants Magisk, they should consider a reasonable exception, not the other way around.

Again that's just a free time personal comment.

**Comment by licaon-kter** [comment]
@DenyDarko F-Droid can't guarantee _"we build this from source"_ if they keep adding exceptions, everyone feels special and want some sort of exception for their own app.

You can keep using the internal updater while I'll choose the F-Droid build.

**Comment by DenyDarko** [comment]
@licaon-kter it's just my personal opinion, how I feel about it, I don't have decision power here.  Don't take me wrong xD

BTW, Magisk IS special, very very special. As special as it can get.

It's the only Superuser method in active development.

**Comment by Iey4iej3** [comment]
Add a reference: https://gitlab.com/fdroid/rfp/issues/283
