### ISSUE TITLE
[Help] Magisk 18.0 is not working. No Root prompts from rooted apps.

### ISSUE THREAD

**Issue by yathomasi1** [topjohnwu/Magisk#1031]
Complete Log:

02-03 23:08:23.891  2032  2032 I Magisk  : * Creating /sbin overlay
02-03 23:08:23.957  2034  2034 I Magisk  : Magisk v18.0(18000) daemon started
02-03 23:08:23.968  2034  2035 I Magisk  : ** post-fs-data mode running
02-03 23:08:23.968  2034  2035 I Magisk  : * Initializing Magisk environment
02-03 23:08:24.018  2034  2035 I Magisk  : * Mounting mirrors
02-03 23:08:24.020  2034  2035 I Magisk  : mount: /sbin/.magisk/mirror/system
02-03 23:08:24.020  2034  2035 I Magisk  : link: /sbin/.magisk/mirror/vendor
02-03 23:08:24.020  2034  2035 I Magisk  : bind_mount: /sbin/.magisk/mirror/bin
02-03 23:08:24.021  2034  2035 I Magisk  : * Setting up internal busybox
02-03 23:08:24.265  2040  2040 I Magisk  : Magisk v18.0(18000) logger started
02-03 23:08:24.416  2034  2035 I Magisk  : * Mounting /data/adb/magisk.img
02-03 23:08:24.469  2034  2035 I Magisk  : * Running post-fs-data.d scripts
02-03 23:08:24.469  2034  2035 I Magisk  : * Running module post-fs-data scripts
02-03 23:08:24.469  2034  2035 I Magisk  : * Loading modules
02-03 23:08:24.547  2034  2055 I Magisk  : * Starting MagiskHide
02-03 23:08:24.547  2034  2055 I Magisk  : hide_utils: Hiding sensitive props
02-03 23:08:24.547  2034  2055 I Magisk  : hide_list add: [com.google.android.gms.unstable]
02-03 23:08:24.644  2034  2055 I Magisk  : hide_list rm: [com.google.android.gms.unstable]
02-03 23:08:24.700  2034  2055 I Magisk  : hide_list add: [com.google.android.gms/.droidguard.DroidGuardService]
02-03 23:08:25.421  2034  2222 I Magisk  : ** late_start service mode running
02-03 23:08:25.422  2034  2222 I Magisk  : * Running service.d scripts
02-03 23:08:25.426  2034  2222 I Magisk  : * Running module service scripts
02-03 23:09:13.944  2034  2055 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[5087] ns=[4026533771]
02-03 23:09:45.854  2034  2055 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[6240] ns=[4026533760]
02-03 23:10:09.865  2034  2055 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[8455] ns=[4026533737]
02-03 23:12:59.931  2034  2055 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[12427] ns=[4026533693]
02-03 23:13:10.484 12566 12566 E Magisk  : write failed with 32: Broken pipe
02-03 23:13:34.599 12704 12704 E Magisk  : write failed with 32: Broken pipe
02-03 23:13:47.188 13294 13294 W Magisk  : su: request rejected (10160->0)

**Comment by khalisz** [comment]
I have the same issue. 
There is now the 18.1, let's try to see if the problem still or not.

**Comment by yathomasi** [comment]
updated magisk manager to 7.0 and magisk to 18.1. Same issue 
Also app is put in  not optimized list in battery optimization
and in performance optimization app is allowed to run in backgroud, allow the system to wake up and allowed to be awakened by other application.

**Comment by khalisz** [comment]
Damn it ! :/

When I downgrade to 17.1, it works, 17.3 or newer No Root prompts from rooted apps.
Dunno if it's because of Android Pie.

**Comment by yathomasi** [comment]
I am using Android Nougat and I don't know the reason behind error message 
`E Magisk : write failed with 32: Broken pipe`
I think i will also try 17.1. Hope that works and I will stick with that version. Thanks @khalisz

**Comment by khalisz** [comment]
Hi Yathomasi, have you tried Magisk 17.1 ?

**Comment by yathomasi1** [comment]
@khalisz Yeah I installed magisk 17.1 and upgraded magiak manager to 6.1.0.
Magisk manager 5.9.1 was default on flashing 17.1 but it crashed on searching module. The latest 7.0.0 doesn't have support for 17.1 so I am using 6.1.0 and magisk 17.1 is working well for me.
Thanks

**Comment by khalisz** [comment]
It works now, I found the solution on XDA

Look here : https://forum.xda-developers.com/showpost.php?p=78835695&postcount=7
