### ISSUE TITLE
Magisk Manager 7.0.0 won't run

### ISSUE THREAD

**Issue by Nakadroid** [topjohnwu/Magisk#1035]
After I updated the manager it says it doesn't support Magisk Versions below 18.0 and closes but I have 18.1 installed, at least that's what the older version of the manager tells me. So there's no update for Magisk itself to install.

**Comment by nihalanand697** [comment]
Tried uninstalling manager , and flashing 18.1 zip from recovery?
It might not install manager so just install it from the zip.

**Comment by Nakadroid** [comment]
I didn't do it after I installed the 7.0.0 apk but I did that back then when I installed 18.1, since I had issues updating using the app.

**Comment by NaderKabir** [comment]
Hi 

Error for OnePlus 6 Android 9 ver 18.1

Very weak for OnePlus 6

**Comment by NaderKabir** [comment]
Hi

Error insatall magisk 18.1 for OnePlus 6

 after flash zip don't booting phone

**Comment by nihalanand697** [comment]
Flash magisk uninstaller zip. Download from github.

**Comment by Nakadroid** [comment]
> Tried uninstalling manager , and flashing 18.1 zip from recovery?
> It might not install manager so just install it from the zip.

so do I just uninstall the manager and flash 18.1 
or do I also flash the uninstall first, then flash 18.1?
