### ISSUE TITLE
Magisk Doesn't Install on Moto X 2014 (Victara) Running LineageOS

### ISSUE THREAD

**Issue by LunarEclipse120** [topjohnwu/Magisk#104]
Device: Moto X 2014
Codename: victara
Model Number: XT1096
Running: LineageOS 14.1 with Stock Gapps
Recovery Log: http://pastebin.com/Yu7tf26D
Boot Image: [boot.zip](https://github.com/topjohnwu/Magisk/files/818357/boot.zip)

Basically, I go flash the latest Magisk zip and it fails with the error in the log.

**Comment by topjohnwu** [comment]
Moto issues should be fixed
