### ISSUE TITLE
bootlop after flash

### ISSUE THREAD

**Issue by Reflyansyah** [topjohnwu/Magisk#1043]
I did all the instructions and bootlop!
yes all my data is missing :p
because of this so please fix Magisk :<

VIVO Y21

**Comment by Reflyansyah** [comment]
https://ufile.io/a5fzc

**Comment by Reflyansyah** [comment]
'''
- Copying image to cache
- Device platform: armeabi-v7a
- Downloading zip
... 0%
1038+1 records in
1038+1 records out
1063528 bytes transferred in 0.024 secs (44313666 bytes/sec)
- Unpacking boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/data/data/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [5927771]
RAMDISK_SZ      [2218447]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
PAGESIZE        [2048]
NAME            [1465282049]
CMDLINE         [bootopt=64S3,32S1,32S1 product.version=PD1309CW_EX_A_1.10.12]
CHECKSUM        [becd97e841a1378b359cefa6ca559052d2e233a7]
DTB             [22915]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
- Checking ramdisk status
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Backing up stock boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Compressing to [stock_boot_00cb1e04dfe9ae29dc4ac08e69b0c9ccf545ed04.img.gz]
- Patching ramdisk
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Patch with flag KEEPVERITY=[false] KEEPFORCEENCRYPT=[false]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Loading dtbs from [dtb]
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
- Repacking boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/data/data/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [5927771]
RAMDISK_SZ      [2218447]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
PAGESIZE        [2048]
NAME            [1465282049]
CMDLINE         [bootopt=64S3,32S1,32S1 product.version=PD1309CW_EX_A_1.10.12]
CHECKSUM        [becd97e841a1378b359cefa6ca559052d2e233a7]
DTB             [22915]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [5927771]
RAMDISK_SZ      [2456612]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
PAGESIZE        [2048]
NAME            [1465282049]
CMDLINE         [bootopt=64S3,32S1,32S1 product.version=PD1309CW_EX_A_1.10.12]
CHECKSUM        [5ee6f0d1625e46f309d65c8f5ef75daae2ca20f0]
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Cleaning up...

****************************
 Patched image is placed in 
 /storage/emulated/0/Download/patched_boot.img 
****************************
- All done!
'''

**Comment by topjohnwu** [comment]
@Reflyansyah have you tried the latest canary builds?

**Comment by Reflyansyah** [comment]
I try soon

**Comment by Reflyansyah** [comment]
I at least use the latest builds of Magisk

**Comment by kimonoki** [comment]
I tried the Canary build still got bootloop.
