### ISSUE TITLE
Flashing issues in KitKat

### ISSUE THREAD

**Issue by HemanthJabalpuri** [topjohnwu/Magisk#1049]
Sir topjohnwu ...
My device is running on KitKat StockROM Samsung
Many seg faults and ERROR:1 in TWRP
I posted the logs in xda thread at https://forum.xda-developers.com/apps/magisk/mod-magisk-v1-universal-systemless-t3432382/post78837438....

also 272 line of util_functions need to be changed to
elif [ -e app_process32 ]; then
instead of
else
because app_process is hardlinked independent binary in KitKat... no app_process32/64 is there..
so force symlinking will cause bootloop...

Feature Request: We can only patch a boot.img without root.. Can you please add an option to patch boot.img option even after rooting....! This will help to patch others boot.img in a single device

**Comment by topjohnwu** [comment]
Thanks for the report!

You can still patch boot images after rooted though :)

**Comment by HemanthJabalpuri** [comment]
> Thanks for the report!
> 
> You can still patch boot images after rooted though :)

Sir some another things i noticed in kitkat with MagiskManager are
-Unable to download Magisk.zip or MagiskManager
-Unable to load Online modules list in Downloads section

Executing magiskboot and magiskinit binaries in TWRP gives segmentation fault...

**Comment by bgamez23** [comment]
i got the same issue with Android 4.4.4

**Comment by HemanthJabalpuri** [comment]
@topjohnwu Sir along with above issues ...
With Canary builds my device struck at bootlogo...
One canary build booted once and second time no booting....
Magisk log for last boot is attached
[magisk.log](https://github.com/topjohnwu/Magisk/files/2882821/magisk.log)

**Comment by bgamez23** [comment]
installation works fine now without any problem. but if you gonna Hide Magisk Manager in the settings it wont download the files. just like the same before.

**Comment by HemanthJabalpuri** [comment]
> installation works fine now without any problem. but if you gonna Hide Magisk Manager in the settings it wont download the files. just like the same before.
> 
> SafetyNet Check Success
> x ctsProfile: false
> 
> android kitkat 4.4.4

Hi...
In my device Magisk 18.2 66* I can't able to flash and manually patched boot.img gives struck at bootlogo..

**Comment by bgamez23** [comment]
its seems lots of bugs for the lower version of android. renaming magisk disk is also bug which failed you to download and install it. and also failed to detect root permission even you installed the magisk successfully without any problem.

**Comment by HemanthJabalpuri** [comment]
> its seems lots of bugs for the lower version of android. renaming magisk disk is also bug which failed you to download and install it. and also failed to detect root permission even you installed the magisk successfully without any problem.

Are you using Magisk now?

**Comment by bgamez23** [comment]
Yup i still use it but for L and M version.not for Kitkat its totally unstable for that version.
