### ISSUE TITLE
Feature Request - do not reset root access permissions after an app update

### ISSUE THREAD

**Issue by sjanello** [topjohnwu/Magisk#105]
Hello,

I've noticed that when an app is updated, it resets or loses it's setting for whether or not to allow or disallow root access. This can be problematic if an app auto updates and is not visited to re-allow root access; or if the user is not watching their phone to re-allow root access when it is requested. I believe SuperSu has a similar option.

**Comment by Zulgrib** [comment]
SuperSU by default kept the permission and had an option to revoke when updated.

**Comment by topjohnwu** [comment]
Fixed
