### ISSUE TITLE
Magisk Manager V.7.0 stuck at app launch screen

### ISSUE THREAD

**Issue by egurudev** [topjohnwu/Magisk#1051]
I am using OnePlus 5t with stock oxygen os Android version 8.1 . I upgraded Magisk to V18.1 and then installed v.7.0 but since then Manager is stuck at app launch screen and all I can see is Magisk logo nothing else. I tried doing the fresh installation but it's same. Any idea?

**Comment by egurudev** [comment]
May I ask why this is closed without a response. I understand you don't owe me an answer per se but I will be grateful if someone can address this issue and let me know how to get out of this jam

**Comment by fessmm** [comment]
@egurudev no logs.
