### ISSUE TITLE
Unable to Update Magisk 18.0 to 18.1  Moto G6

### ISSUE THREAD

**Issue by JakeFrom98** [topjohnwu/Magisk#1053]
Hello, this is my first issue report I've ever done but I'll try to display as much info and be as informal as possible ;)

So I can use version 18.0 pretty flawlessly but I cannot update to version 18.1 using Magisks update system or TWRP. I noticed when I install Magisk 18.0 I believe it says Device platform: arm but when I install 18.1 it says Device platform: armeabi-v7a and I cannot install it. If anyone has any tips on how to resolve this issue I would appreciate it thank you. :)

My Device Info

Android Version: 8.0.0
Model: Moto G6 ali
Machine: armv7I
ABI: areabi-v7a

Magisk 18.1 Install Log 

- Copying image to cache
- Device platform: armeabi-v7a
- Downloading zip
... 0%
1038+1 records in
1038+1 records out
1063528 bytes (1.0MB) copied, 0.029840 seconds, 34.0MB/s
- Unpacking boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/mnt/expand/0dcbe6f2-8077-48e0-afb4-64368c1f2ede/user_de/0/com.topjohnwu.magisk/install/boot.img]
No boot image magic found!
! Unable to unpack boot image
! Installation failed

**Comment by topjohnwu** [comment]
You are passing an incorrect image to the manager

**Comment by JakeFrom98** [comment]
I used the built-in update system of Magisk.
