### ISSUE TITLE
Pixel 3 Soft Brick

### ISSUE THREAD

**Issue by eluke97** [topjohnwu/Magisk#1056]
Both version 18.0 and 18.1 soft brick my pixel 3, necessitating a reflash of the factory image every time I attempt. I've seen on several forums that others have the same problem, but it seems to be hit or miss among the community.

**Comment by eluke97** [comment]
The following fix worked for me, although I don't understand why.   https://www.reddit.com/r/GooglePixel/comments/9dm42e/flashing_magisk_puts_me_in_a_boot_loop/

**Comment by vvb2060** [comment]
https://mobile.twitter.com/topjohnwu/status/1070029212428439553

**Comment by topjohnwu** [comment]
I'm am using Pixel 3 XL daily, there is **0** possibility Magisk will brick Pixels.

**Comment by eluke97** [comment]
I see you already addressed this; sorry for bringing up a nonissue
