### ISSUE TITLE
Failed to install latest magisk for android 4.4.4

### ISSUE THREAD

**Issue by bgamez23** [topjohnwu/Magisk#1057]
Here is what i get after flashing in twrp.

https://i.postimg.cc/wTRFs1WD/IMG-20190210-195005.jpg

And also failed to manual download the Magisk-v18.1(18100).zip from latest magisk manager.

https://i.postimg.cc/q718Htwb/IMG-20190210-195643.jpg

Magisk Update Available notification wont remove.

**Comment by topjohnwu** [comment]
Screenshots is not a valid bug report, please know how to report issues
