### ISSUE TITLE
Magisk boot loop with latest canary release 

### ISSUE THREAD

**Issue by Fox2Code** [topjohnwu/Magisk#1058]
I have a bootloop with on my phone and with my investigation, I have found the boot process blocked before adb and magisk daemon start (Made logs impossible to provide) this may mean it's a magiskinit or magiskboot issue

However, I have successfully extracted the patched boot image from my phone

This is a new bug with the latest canary release so it's must be a recent commit that causes this bug

[Patched image.zip](https://github.com/topjohnwu/Magisk/files/2848887/Patched.image.zip)
[Original image.zip](https://github.com/topjohnwu/Magisk/files/2848888/Original.image.zip)

**Comment by Ante0** [comment]
It might be this commit that causes it:
https://github.com/topjohnwu/Magisk/commit/c8491d008f3e6a5799c0d757378f2ba6b4d951fc
Someone else, including me is having problems with this canary build. 
I use a Huawei on Pie though.
The boot images are not really needed, Magisk only replaces 'init'.

And I can't get any logs either as phone won't get past "Your phone is unlocked" screen :/

**Comment by mscalindt** [comment]
I have a problem too with this canary build.

**Comment by Ante0** [comment]
Still the same for me. It fixed the bootloop on Oreo (EMUI8), but bootloop
on EMUI9 (uses system-as-root) is still there. Eventually it goes to
eRecovery now so I should be able to get something out of logs, but no time
to check today :/
