### ISSUE TITLE
小米mix3安装失败

### ISSUE THREAD

**Issue by luo1227135067** [topjohnwu/Magisk#1059]
- Copying zip to temp directory
- Installing Magisk-v18.1.zip
************************
* Magisk v18.1 Installer
************************
- Mounting /system, /vendor
- Using system_root_image, keep dm/avb-verity
- Encrypted data detected, keep forceencrypt
- Target image: /dev/block/sde45
- DTBO image: /dev/block/sde37
- Device platform: arm64
- Constructing environment
- Boot image is signed with AVB 1.0
- Unpacking boot image
- Checking ramdisk status
- Magisk patched boot image detected
- Patching ramdisk
- Repacking boot image
- Flashing new boot image
- Sign image with test keys
! Insufficient partition size
! Installation failed

**Comment by vvb2060** [comment]
busybox出问题了，导致检查空间的命令失败。 #1060

**Comment by luo1227135067** [comment]
我用面具刷了busybox模块没用。然后软件安装busybox成功了，可以刷入了。但是重启手机又不见了，又用rec刷入，也成功，重启手机又不见了。刷别人修改过的又可以。官方的只能刷17.1
18.1要刷别人改过的

**Comment by topjohnwu** [comment]
已 merger @vvb2060 的 PR

**Comment by luo1227135067** [comment]
没看懂
