### ISSUE TITLE
请教：安卓p系统system_root，boot（仅有kernel）和recovery，好像不支持root？

### ISSUE THREAD

**Issue by wzsx150** [topjohnwu/Magisk#1064]
作者你好，首先感谢你做出来magisk，非常厉害的root工具。我一直都在使用。你很厉害！

以前只有AB系统才有system_root的模式，这是boot分区就是存放以前的recovery文件，然后正常启动系统时boot只是将系统引导至system分区，由system_root的文件完成进入系统。那时好像通过patch boot分区就可以root系统。

但是安卓p时代有了全新的一种模式，system分区是system_root模式，此时还有boot分区和recovery分区，和AB系统完全不同。
此时boot分区只有kernel内核文件，并没有ramdisk，所以如果直接patch boot分区，实际上没什么意义，因为没有ramdisk。实际上因为system_root的存在，所以以前ramdisk的文件都放在了system分区中。所以理论上此时应该patch system分区就可以了。

不知道作者你有没有测试过在这种类型的手机上进行卡刷？
我没有研究你卡刷的脚本在这种模式上的patch过程，但是我想，18.0和18.1不能安装在这个类型的手机上的原因是不是就是我说的这样？？

但是比较奇怪的是，为什么卡刷17.1版本，就可以root这种类型的手机？很奇怪。。。。难道你已经在17.X的版本上做了对这种新类型手机的patch策略？能介绍一下你对这种类型的手机的patch思路吗？

希望作者你能抽出时间看一下我说的这个问题，因为安卓p的新机子基本大部分都是这样类型的（除去AB系统的），这将是最近新发布的机型都要面对的问题。

**Comment by topjohnwu** [comment]
@wzsx150 就我自己所知，華為 EMUI 9.0 就是用類似你所說得設計(我剛有有一台華為送給我的 Honor View 10)。因此你要 patch 在 recovery_ramdisk 上面，並且每次開機都要以 recovery 形式開啟。這個在 Magisk v18.0 已經開始正式支援並且在官方的說明文件裡面已經詳加說明 (我沒有時間維護兩語言的文檔因此只有英文的，不過我想在中國應該有很多人會幫忙翻譯吧)

在偵測到 EMUI 9 設備得時候，Magisk Manager 將會 patch 在 recovery_ramdisk 上。如果還有其他設備用類似的形式，可以讓我知道下。

**Comment by scarlet-glass** [comment]
你好，大神，努比亚红魔mars也是system_root，目前我只能手动解包boot和system.img进行拼包才能实现

**Comment by wzsx150** [comment]
> @wzsx150 就我自己所知，華為 EMUI 9.0 就是用類似你所說得設計(我剛好有一台華為送給我的 Honor View 10)。因此你要 patch 在 recovery_ramdisk 上面，並且每次開機都要以 recovery 形式開啟。這個在 Magisk v18.0 已經開始正式支援並且在官方的說明文件裡面已經詳加說明 (我沒有時間維護兩語言的文檔因此只有英文的，不過我想在中國應該有很多人會幫忙翻譯吧)
> 
> 在偵測到 EMUI 9 設備得時候，Magisk Manager 將會 patch 在 recovery_ramdisk 上。如果還有其他設備用類似的形式，可以讓我知道下。



@topjohnwu 大佬，你好，更新日志，我之前就看过了，知道你支持华为emui9了，但是就是因为不清楚你为什么没有写支持安卓p的system_root类型的设备，才来到这里发问的。

你没有完全看懂我说的意思，华为的emui9和我说的这种类型的手机还不一样的，可能是因为你手上安卓p的设备比较少，所以你没接触过。
就我现在接触到的设备里，例如联想z5s，联想z5pro GT，小米mix3，红米note7等等，对于出厂安卓p的设备，很多都是这样的类型。你可以仔细读一下我说的这种类型的设备的特点。
他有boot，但是boot分区没有ramdisk，ramdisk的init等文件都在system分区，因为是system_root。

正如楼上 @scarlet-glass 所说，我认为对于system_root的设备最直接的解决方案，应该是直接patch system分区，因为init等文件都在system分区，挂载后，直接patch就行了。而不像传统的原始的boot分区（你需要解压boot和patch ramdisk，然后再打包刷入），没这么麻烦了。



我说一下华为emui9的特点，华为emui9与之前的emui8相比，有所不同，emui8有ramdisk分区，所以magisk可以直接解压ramdisk，然后patch，然后打包刷入ramdisk分区就行了，所以也不用说patch recovery_ramdisk这种做法。
emui9把ramdisk分区去除了，然后把system分区从system模式改成了system_root模式，可以理解为将原来的ramdisk分区的文件放到了system分区，此时如果我们还有旧的magisk去root，他会找不到ramdisk分区、boot分区而无法进行下一步操作。

另外针对emui9，你说你的解决方案是patch recovery_ramdisk，我认为这不是一个很完美的方案。

最后，我强烈建议，对于system_root模式的手机（除了AB系统的），一律改为直接patch system分区。这样的方案既可以解决我说的那种类型的手机的root问题，同样也能解决华为emui9的root问题。而且是基本完美的。只是需要更麻烦的判定逻辑而已。

（其实对于我说的这种类型的设备，就如楼上所说，我可以把system_root中的init等之类的文件，打包到boot里，然后卡刷magisk，然后再把boot里ramdisk的文件复制出来，覆盖到system，其实是很麻烦的，所以这里想让你能直接修改支持这种设备）

除了推特，大佬你那还有什么联系方式和大陆通用的？如果在这里反馈交流不方便，我们可以考虑其他联系方式进行沟通。

**Comment by wzsx150** [comment]
@topjohnwu 因为我是twrp的开发者，经常会研究各种机型的root问题，所以可能在有些方面可以给你提供更多的思路，我自己有时候也会简单的修改你的卡刷包，以适用某些机型的root。

再次感谢你，做出来这么好用的root工具。

**Comment by wzsx150** [comment]
@topjohnwu hello？

**Comment by vvb2060** [comment]
你知道magisk是什么吗？
A Magic Mask to Alter Android System Systemless-ly

**Comment by vvb2060** [comment]
可以预见，出于成本考虑，加上Google对P的强制要求，使用Aonly & system-as-root 的设备应该会增加。如果按照[AOSP的标准结构](https://source.android.com/devices/bootloader/system-as-root#about-system-as-root) ，应该会是patch recovery镜像后刷进boot分区。
@wzsx150 不用从system里复制，一堆本来就会清空的东西…要的是被执行，magiskinit做完准备工作后就会把控制权移交给/system_root/init。
为什么不要修改system？先不说systemless这个概念，我们来说说system-as-root，它为什么会出现？因为Project Treble只更新system分区，init这些东西得丢进system里一起更新。好，更新system分区，但由于是块级更新，要求完全不能动system分区，这就是理由。boot分区可以非常方便地还原以支持OTA。

**Comment by wzsx150** [comment]
@vvb2060 没必要争辩这个，我只是想让作者至少提供patch system_root的功能，卡刷脚本里放一个参数来控制也行，类似于保持dm校验和保持强制加密的那个参数。

本来就没想发这条的，就是不想惹来各种争执，作者如果愿意，那当然我很高兴，可以省很多麻烦，如果作者不愿意，那也没事，只不过我自己麻烦点而已，再不行，那就尝试自己修改patch system_root吧。

希望 @topjohnwu 能够回复一下，至少心里有个底。

**Comment by vvb2060** [comment]
联想z5s，联想z5pro GT，小米mix3，红米note7…它们的分区结构都是标准模型吗？即两个内核。
EMUI9，问题就出在共用一个内核，没有源码，不知道怎么才能让它在正常启动时使用recovery_ramdisk。
如果是标准模型，可以非常简单地patch recovery镜像后刷进boot分区(当然magisk得更新一下)。

**Comment by vvb2060** [comment]
@wzsx150 根据反馈，在小米mix3和红米note7上测试通过。
17.1可用的原因是，magiskboot 会在最后一步生成出ramdisk，但在后续版本无ramdisk的情况下会出错。

**Comment by TheNewlt** [comment]
> 你好，大神，努比亚红魔mars也是system_root，现在我手动解包boot和system.img进行拼包才能实现

What do you do for the package? Can you tell me more about it?
