### ISSUE TITLE
F2FS filesystem installation module

### ISSUE THREAD

**Issue by scarlet-glass** [topjohnwu/Magisk#1065]
The machine is Nubia X (NX616J), and it cannot install any files through magisk. The big god said before that it was f2fs driver problem, could the big god guide where is the problem specifically?
I tried to format the data partition as ext4, but the boot prompt failed to encrypt

**Comment by scarlet-glass** [comment]
- Copying zip to temp directory
- Installing magisk-EdXposed-v0.2.9.7_beta-release.zip
*******************************
 Please install Magisk v17.0+! 
*******************************
! Installation failed

**Comment by topjohnwu** [comment]
Fixed: 1321f097b823729ba0b2dd99e611098538cb8a73
