### ISSUE TITLE
Feature suggestion: Disable MagiskRoot when there is already root installed.

### ISSUE THREAD

**Issue by pthfdr-42** [topjohnwu/Magisk#1066]
LineageOS have a built-in root plugin that you can flash and enable in Developer Settings.
So, when starting Magisk Manager, you should ask the system for root access first (if exist), and if root is granted, disable Magisk root/Magisk hide/etc completely and only use Magisk as a framework for modules (like xposed).

**Comment by topjohnwu** [comment]
Well, you should not install Lineage root if you want to use Magisk....
