### ISSUE TITLE
late_start mode never run on S7 edge

### ISSUE THREAD

**Issue by JohnChu101** [topjohnwu/Magisk#1069]
My phone model is Samsung Galaxy S7 edge (SM-G9350) with Qualcomm 820.

And the late_start mode of magisk never run on my device. I even did a fresh installation of magisk and it still doesn't work.

Log:
02-21 16:27:30.284   622   622 I Magisk  : * Creating /sbin overlay
02-21 16:27:30.342   624   624 I Magisk  : * Device API level: 24
02-21 16:27:30.342   624   624 I Magisk  : Magisk v18.1(18100) daemon started
02-21 16:27:30.345   624   625 I Magisk  : ** post-fs-data mode running
02-21 16:27:30.345   624   625 I Magisk  : * Initializing Magisk environment
02-21 16:27:30.346   624   625 I Magisk  : * Mounting mirrors
02-21 16:27:30.348   624   625 I Magisk  : mount: /sbin/.magisk/mirror/system
02-21 16:27:30.348   624   625 I Magisk  : link: /sbin/.magisk/mirror/vendor
02-21 16:27:30.348   624   625 I Magisk  : bind_mount: /sbin/.magisk/mirror/bin
02-21 16:27:30.349   624   625 I Magisk  : * Setting up internal busybox
02-21 16:27:30.392   630   630 I Magisk  : Magisk v18.1(18100) logger started
02-21 16:27:30.424   624   625 I Magisk  : * Running post-fs-data.d scripts
02-21 16:27:30.426   624   625 I Magisk  : Create /data/adb/magisk.img with size 64M
02-21 16:27:30.458   624   625 I Magisk  : * Mounting /data/adb/magisk.img
02-21 16:27:30.526   624   625 I Magisk  : * Running module post-fs-data scripts
02-21 16:27:30.526   624   625 I Magisk  : * Loading modules
02-21 16:27:30.557   624   647 I Magisk  : * Starting MagiskHide
02-21 16:27:30.557   624   647 I Magisk  : hide_utils: Hiding sensitive props
02-21 16:27:30.567   624   647 I Magisk  : hide_list add: [com.google.android.gms/.droidguard.DroidGuardService]
02-11 23:33:58.715   624  5065 E Magisk  : su: cannot find manager
02-11 23:34:25.957   624  7708 E Magisk  : su: cannot find manager
02-11 23:35:09.432   624   647 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[9922] ns=[4026534326]

**Comment by topjohnwu** [comment]
Please report issues with the latest canary debug builds
