### ISSUE TITLE
SELinux policy patch not work（HUAWEI Mate20 Pro)

### ISSUE THREAD

**Issue by yishisanren** [topjohnwu/Magisk#1078]
My phone is HUAWEI Mate20 Pro. EMUI9.
I can not edit setenforce.

https://drive.google.com/file/d/1s4Radxcvk98Mms05efCG13picInrU7LV/view?usp=drivesdk
https://drive.google.com/file/d/1-yNYDbqGtMFYG4fb2iAYeedzjnvgL7Ia/view?usp=drivesdk

**Comment by topjohnwu** [comment]
https://twitter.com/topjohnwu/status/1095919293114601472
