### ISSUE TITLE
Magisk uninstalling itself?

### ISSUE THREAD

**Issue by EvoWizz** [topjohnwu/Magisk#108]
So that the second time I have the same problem with Magisk :/ It just uninstall itself :/ So I don't know what to do when it happens :/ I'm on 7.1.1 (Resurrection Remix) on my Moto X Play.
![magisk](http://i.imgur.com/8MFgrG0.png)

**Comment by Darkness4** [comment]
I can confirm too. It's apparently because of magiskhide. It is not uninstalling itself, but it looks like it stays disabled. So the solution may be to reboot and/or disable magiskhide.

Also i cannot access to the logs when it happens.

**Comment by EvoWizz** [comment]
@Darkness4 Hi, thanks for answering :) 
-----
So I had that bug again, and I tried to reboot, but Magisk is still "disabled". I don't know what to do now since I can't disable Magisk Hide since the app think I'm not rooted :/

**Comment by topjohnwu** [comment]
Disable busybox to fix it

**Comment by skygate2012** [comment]
I encountered the same issue. It's not actually uninstalling itself but rather changing its name due to Magisk Hide I enabled earlier. I found it under the fake name (default is Settings).
