### ISSUE TITLE
Imageless Magisk causes SElinux type transition failure

### ISSUE THREAD

**Issue by ianmacd** [topjohnwu/Magisk#1080]
The changes that remove Magisk's reliance on _magisk.img_ cause the [Xposed Framework (SDK 26)](https://github.com/Magisk-Modules-Repo/xposed_26) module to trigger a loop during boot on my Samsung S9+.

Builds containing commits up to and including those from 11th February are fine. Builds containing commits from the 12th onwards fail if the Xposed SDK 26 module is enabled.

Disabling the module or running Magisk in core-only mode are functional work-arounds.

**Comment by topjohnwu** [comment]
@ianmacd may you grab  the full logcat when stuck in bootloop? I suspect there is something to do with SELinux

**Comment by ianmacd** [comment]
As requested, here is a logcat from the very start of the boot process, including several loops of the problematic section.

[logcat.gz](https://github.com/topjohnwu/Magisk/files/2867194/logcat.gz)

**Comment by topjohnwu** [comment]
Hmm... the context itself seems correct, I suspect it has some weird stuff to do with Samsung's knox nonsense. Because when you check the context of the original `/system/bin/app_process64`, you should see that its context should also be `u:object_r:zygote_exec:s0`.

**Comment by ianmacd** [comment]
But then I wonder why it would work up until 2019-02-11?

I've been running your Xposed module ever since I purchased the device in early 2018 and put Magisk on it. It's only after the radical changes to Magisk this week that Xposed has stopped working.

**Comment by teddy0209** [comment]
Glad I found this... Xposed is also causing my M9 to not boot on 18105 and 106... sdk24

**Comment by Didgeridoohan** [comment]
> But then I wonder why it would work up until 2019-02-11?

Some pretty major changes where done on 2019-02-12, i.e. the commit to remove the Magisk image in favour of the new method to store modules in /data/adb/modules...

**Comment by ianmacd** [comment]
> > But then I wonder why it would work up until 2019-02-11?
> 
> Some pretty major changes where done on 2019-02-12, i.e. the commit to remove the Magisk image in favour of the new method to store modules in /data/adb/modules... Could be a possible cause.

I'm aware of the invasive changes made that day, but the Xposed module was created by John himself and, AFAIK, it doesn't do anything unusual at installation time that would make it vulnerable to implementation changes.

John himself suspects KNOX, but KNOX isn't new and hasn't changed on Samsung devices, which is why I was curious why the changes on the 12th would've had this effect on the module.

**Comment by topjohnwu** [comment]
@ianmacd I finally understood the issue, a workaround will be added very soon, please stay tuned :)

**Comment by ianmacd** [comment]
> @ianmacd I finally understood the issue, a workaround will be added very soon, please stay tuned :)

Fabulous! Thank you for getting to the bottom of it!

I very much look forward to the fix.

**Comment by ianmacd** [comment]
Verified working. Thank you very much!

**Comment by teddy0209** [comment]
Awesome, thanks for the fix!!!
