### ISSUE TITLE
[Cute feature request]: Uninstall button swipe

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#1082]
I was reading the article below and I thought to suggest it, why not?

Not only it will prevent any accident taps, it's also really cute visually, it gives a modern taste:

https://android.jlelse.eu/make-a-great-android-ux-how-to-make-a-swipe-button-eefbf060326d

**Comment by topjohnwu** [comment]
Thanks for the suggestion, but I really don't have that many time to create fancy UIs. Tons of other issues still need to be handled and I'm only a single man :)
