### ISSUE TITLE
SAMSUNG S9 SM-G9650 Chinese version SNAPDRAGON

### ISSUE THREAD

**Issue by tomatolei** [topjohnwu/Magisk#1085]
SAMSUNG S9 SM-G9650 Chinese version SNAPDRAGON ,install magisk 18.1 and magisk 18.2 can not boot,
I think maybe ramdisk/init problem，Because the original init can be turned on。On behalf of Qualcomm Samsung users, I pay tribute to the developers, thank you！
this is original boot.img of SM-G9650 android pie
https://drive.google.com/file/d/1qnUNufa2VcRqhfTcIPUqaOPjlZidanH6/view?usp=sharing

**Comment by topjohnwu** [comment]
The new A only system-as-root patch might fix this issue, closed for now
