### ISSUE TITLE
"Magisk is not installed" after installing Magisk Canary build 18103 or later

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#1086]
The last fully functional Magisk Canary build on my device is the 18101. 18102 causes stuck in the boot logo and 18103 and later cause "Magisk is not installed." My device is a Zenfone 4 (ZE554KL) with Android 8.0. It does not have a vendor partition and uses the old partition layout (boot, recovery, system, cache, userdata...). Thank you so much for your time and great work!

[stockboot.img.zip](https://github.com/topjohnwu/Magisk/files/2871289/stockboot.img.zip)
[magisk18101patchedboot.img.zip](https://github.com/topjohnwu/Magisk/files/2871290/magisk18101patchedboot.img.zip)
[magisk18105patchedboot.img.zip](https://github.com/topjohnwu/Magisk/files/2871291/magisk18105patchedboot.img.zip)

**Comment by shakalaca** [comment]
I'm looking into it, stay tuned :)

**Comment by KaMyKaSii** [comment]
@shakalaca what a surprise to see you here, I used your unofficial unlocker to unlock the bootloader of my Zenfone 4. I believe you are with Zenfone 5, is it suffering the same problem? Do you think that can be a specific problem in ZenUI roms? Although another user on the Magisk Canary thread on xda reported having the same problem with Moto Z running Lineage 16

**Comment by kjp4756** [comment]
I'm the one with the Moto Z.  It's actually a treble converted Moto Z which uses squashfs for vendor.  I need commit 6698c189fc9fba638bb4873522e5cfc81d964be1 for magisk to work for me so there isn't a previous canary build that worked for me.  I was running a private build of magisk with just that one commit (based on ~ feb 6 magisk source) and it worked so there has to be something that was merged afterwards that's causing issues.

I can post my boot images if needed.  There are no log files to be found.

**Comment by kjp4756** [comment]
It looks like 18106 works for me.  I should've tried that before posting earlier.

**Comment by KaMyKaSii** [comment]
Many thanks, @shakalaca and @topjohnwu, the 18107 build is working perfectly. But one thing worth mentioning is that after doing a clean install with TWRP and rebooting, my device got stuck at the boot logo for about thirty seconds and then went into fastboot mode. But a second reboot was enough to make Android boot and Magisk work properly
