### ISSUE TITLE
Systemless hosts file should have more space

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [topjohnwu/Magisk#1087]
I use AdAway with Steven Blacks & hpHosts hosts file. Also I have IPv6 support enabled in AdAway. This gives me a hosts file with ~40MB! And this file seems to be to big for the systemless support of Magisk... I also filled a issue on the AdAway project to trim the file (https://github.com/AdAway/AdAway/issues/1107), but giving in general the file more space in Magisk would be IMHO also a good idea.

**Comment by topjohnwu** [comment]
Please check the canary builds before reporting! I bet you have no idea what I'm talking about

**Comment by Tobias-B-Besemer** [comment]
Works after switch to canary!

**Comment by PerfectSlayer** [comment]
Hi @topjohnwu !
It is not related to your app. I must resize img on user device in order to copy large file into 😉

**Comment by Tobias-B-Besemer** [comment]
Guess it was a bug in Magisk 18.1. I also had write problems with different Magisk Modules. Now, after switch to Magisk 18.2 Nightly, the Modules and the Systemless Hosts File work!

**Comment by KaMyKaSii** [comment]
@Tobias-B-Besemer this is not a bug. Magisk 18.1 and earlier used a 64MB ext4 image to store all the modules, so if you try to save large files inside without increasing the image before, you will have problems. Magisk 18.2 (the Canary builds) no longer uses ext4 images, it stores the modules in normal folders, so now the size limit for modules is how much free space you have on the internal storage
