### ISSUE TITLE
Show module information when click on a module

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [topjohnwu/Magisk#1089]
When I click in the Download View on a module, I get some interesting information like the command I have to run in command line to configure this module. In the Module View I miss this feature -> I always have to go to the Download View to look for the commands to run. I think Magisk should also show the module information when click on a module in Module View.

**Comment by topjohnwu** [comment]
@diareuse you might want to check this out for your redesign too. If there is a corresponding repo that has the same ID as a module, you might be able to show some info regarding that. I'm not so sure about how it can be implemented, but it is up to you.

If you already have something implemented similar to this, then feel free to close this issue

**Comment by diareuse** [comment]
I find unnecessary to add issues to legacy at this point, so I'd like to refrain from doing so. 🤪Nonetheless I will add this to the redesign.

**Comment by topjohnwu** [comment]
@diareuse Ah yeah, the current Magisk Manager is feature freeze, all changes I'm will be mentioning is meant to be in the redesign
