### ISSUE TITLE
N910C running DittoNote 7 Rom with Permissive kernel Incompatibilities

### ISSUE THREAD

**Issue by zixith** [topjohnwu/Magisk#109]
Please see attached kernel zip (which contains the kernel's boot.img). I am using the DittoNote 7 rom with this kernel, and I could swear that I was awake for the whole night trying to figure out why Safety Net wasn't passing. It seems that the kernel is Permissive and no matter what I try (terminal commands etc.) I just couldn't get the Rom to be Enforcing, this preventing me from running Android Pay and Pokemon Go. Please could you advise on how I could pass Safety Net successfully, would it be possible to change the SELinux of that kernel to Enforcing to it plays nicely with SELinux? Or is there a way to get fake enforcing to work with this rom? Thank you.

[DittoNote7_N910C_Kernel.zip](https://github.com/topjohnwu/Magisk/files/836949/DittoNote7_N910C_Kernel.zip)

**Comment by zixith** [comment]
EDIT: I realised I was actually using the stock kernel (not Suemax which is what I originally put) and getting those SafetyNet failure issues.

**Comment by topjohnwu** [comment]
Samsung issues are all fixed
