### ISSUE TITLE
Reset prop not work on EMUI 4.0

### ISSUE THREAD

**Issue by MlgmXyysd** [topjohnwu/Magisk#1097]
module.zip/common/system.prop
```
ro.config.ksm=true
ro.config.low_ram=true
persist.sys.force_highendgfx=true
ro.huawei.multiwindow=true
ro.config.hw_support_clone_app=true
ro.config.hw_eyes_protection=7
qemu.hw.mainkeys=0
ro.config.hw_navigationbar=true
ro.config.fp_navigation=true
ro.config.vc_call_vol_steps=20
ro.config.vc_call_vol_default=18
fw.show_multiuserui=1
fw.max_users=8
ro.config.hw_glovemode_enabled=1
```

Device: Huawei Honor 4X
System: EMUI 4.0 Android 6.0.1

Other app in module is working.
Full boot log here:
[boot-2019-02-18-11-32-48.log](https://github.com/topjohnwu/Magisk/files/2873957/boot-2019-02-18-11-32-48.log)

**Comment by topjohnwu** [comment]
You did not set up your modules properly, please read the instructions within `config.sh`
