### ISSUE TITLE
resetprop make settings stop work in Nexus 6P

### ISSUE THREAD

**Issue by ikey4u** [topjohnwu/Magisk#1098]
My Nexus 6P is enabled with developer options, and I use `resetprop` command to do the following in adb shell

```
resetprop ro.secure 0
resetprop ro.debuggable 1
```

and then when I reopen developer options, it makes Nexus 6P's settings application stop.

Revert `ro.secure` and `ro.debuggable` make settings work again.

**Comment by topjohnwu** [comment]
This has nothing to do with resetprop
