### ISSUE TITLE
convert magisk module version

### ISSUE THREAD

**Issue by jvaz87** [topjohnwu/Magisk#1099]
how do I install a module in magisk v16 being the module created for v17? How to convert? because my mi8se does not install magisk v17 nor v18 only v16 @topjohnwu 
![screenshot_2019-02-18-21-56-30](https://user-images.githubusercontent.com/47756896/52972282-25480300-3399-11e9-86f3-b65a032785ae.png) 
[SmaliPatcherModule-0.0.4.0-fOmey@XDA.zip](https://github.com/topjohnwu/Magisk/files/2877118/SmaliPatcherModule-0.0.4.0-fOmey%40XDA.zip)

**Comment by topjohnwu** [comment]
There is no way to convert, and sorry, no support will be provided for old versions
