### ISSUE TITLE
No support for KitKat

### ISSUE THREAD

**Issue by TheComputerGuy96** [topjohnwu/Magisk#11]
@topjohnwu, can you add KitKat support for Magisk because KitKat is quite popular Android version?

**Comment by topjohnwu** [comment]
I don't have a device, and KK to LP is quite a lot difference, it will make it super difficult to maintain.
Once the project is super stable, I'll consider adding KK support.

**Comment by drinkmystery** [comment]
@topjohnwu, now the Magisk is V12, and still not support KK.
In my understanding, the Magisk core boot img patcher patches
the stock boot.img to implement systemless root.
I disable the api check in update-binary, and run it on my KK device.
The stock boot.img was successfully patched.

I just wonder if systemless root can support KK in theory.
If the answer is yes, I'll try to port Magisk for my KK device.

就我的理解,magick是通过对官方的boot.img打patch来实现systemless root.
我注释了安装脚本里的api检测,强制在KK上运行,结果成功对官方boot.img进行了patch.
我想知道在理论上是否可以在KK上实现 systemless root.
如果可以的话, 我想自己尝试移植Magisk 到我的KK 设备上,

**Comment by TheComputerGuy96** [comment]
@drinkmystery Magisk Hide can't work on KitKat (and below) because of lack of setns support
