### ISSUE TITLE
Error 1 on installing (mt657

### ISSUE THREAD

**Issue by k0niii** [topjohnwu/Magisk#1103]
Error 1 on intalling mt6572 chipset
Both on android 4.4, 5.x, 6,0 roms
Both stable or canary build
https://dropmb.com/download/4ba8c35fc2943fce5c1f96634e96b132.html

**Comment by DenyDarko** [comment]
[recovery.log](https://github.com/topjohnwu/Magisk/files/2881103/recovery.log)

Log attached for convenience.

Dropmb is full of ads.

**Comment by k0niii** [comment]
> [recovery.log](https://github.com/topjohnwu/Magisk/files/2881103/recovery.log)
> 
> Log attached for convenience.
> 
> Dropmb is full of ads.

Sorry for inconvenience Im new on GitHub

**Comment by k0niii** [comment]
[recovery.log](https://github.com/topjohnwu/Magisk/files/2903607/recovery.log)
Unsupported/Unknown image format
On latest canary 18109
Chipset:mt6572 kitkat
Twrp 3.1.1

**Comment by topjohnwu** [comment]
I cannot magically know how your device's boot image format to support it. If you can point to me any existing tools that can unpack your boot image, feel free to let me know

**Comment by k0niii** [comment]
> I cannot magically know how your device's boot image format to support it. If you can point to me any existing tools that can unpack your boot image, feel free to let me know

[magisk_install_log_20190226_213938.log](https://github.com/topjohnwu/Magisk/files/2905757/magisk_install_log_20190226_213938.log)
But it can be patch on magisk manager and i install successfully
[Boot.img.zip](https://github.com/topjohnwu/Magisk/files/2905775/Boot.img.zip)

**Comment by iyx** [comment]
I encountered this "Unsupported/Unknown image format" problem also, but manual patching with manager also worked for me.

**Comment by elig0n** [comment]
> I encountered this "Unsupported/Unknown image format" problem too, but manual patching with manager also worked for me.
Which manager? I try with the program itself (Magisk Manager) and it shows me this. Zip is its own. Weird.

**Comment by chulluter** [comment]
Guys 
I flashed a rom with SuperSU already in it.
I wanted magisk so 
I flashed unSU.zip with TWRP
But when I flashed 
Magisk 19.3.zip 
It said 
Unknown/Unsupported IMG format 
Please helpp

**Comment by kuttekalund** [comment]
okay I faced same error unknown/unsupported file format when installing magisk
i have my boot.img
i used magisk manager to create a patched file
what do i do then ?
