### ISSUE TITLE
Grant Helium superuser

### ISSUE THREAD

**Issue by Cyberavater** [topjohnwu/Magisk#1105]
Magisk seems doesn't grant Helium Superuser while SuperSU does.

App link: <a href="https://www.apkmirror.com/apk/clockworkmod/helium/helium-1-1-4-6-release/helium-app-sync-backup-1-1-4-6-android-apk-download/">Helium</a>

**Comment by DenyDarko** [comment]
This is not a bug.

Both apps are fossils and they are compatible.

It's not a magisk bug, but an extremely outdated (technically EOL) app.

**Comment by topjohnwu** [comment]
It is very likely that Helium assumes the `su` path.
