### ISSUE TITLE
Can't install Magisk on Samsung S4 (i9506) with Stock 5.0.1 LP

### ISSUE THREAD

**Issue by Rosxo** [topjohnwu/Magisk#1106]
I have intermediate experience with flashing, "twrping", rooting and installing modules with magisk. And I know it works with many custom roms on xda. But for some reason stock 5.0.1 fails. Can someone investigate?

**Comment by DenyDarko** [comment]
https://www.didgeridoohan.com/magisk/MagiskHelp

Logs.
