### ISSUE TITLE
[Maybe Detection Issue] Not Installed at MManager 7.0

### ISSUE THREAD

**Issue by prenfic** [topjohnwu/Magisk#1107]
PLATFORM:
System: 5.1.1 (Build No. A5FMB19)
Device: Nokia N1 (tablet)
CPU: Z3580 (x86_64bit CPU with 64bit Linux)
APP: M.Manager v7.0 (185)
Magisk Version: v18.2 (nightly by ianmacd)

Before Anything Else:
1. To be clear, magisk is detected in v6.1 (165) M.Manager (stock and ianmacd as well)
2. N1 is intel CPU based, so I patch boot.img thru M.M v7.0 and then flash it under twrp

Issue:
Both version of M.Manager, in which 6.1 and 7.0 are installed, but magisk is detected in v6.1 but "not installed" in v7.0.

Log (pull from /cache/magisk.log):
```
--------- beginning of main
I/Magisk  (  226): Magisk v18.2-2019022001-ianmacd(2019022001) daemon started
I/Magisk  (  226): * Device API level: 22
I/Magisk  (  226): ** post-fs-data mode running
I/Magisk  (  226): * Initializing Magisk environment
I/Magisk  (  226): * Mounting mirrors
I/Magisk  (  226): mount: /sbin/.magisk/mirror/system
I/Magisk  (  226): link: /sbin/.magisk/mirror/vendor
I/Magisk  (  226): bind_mount: /sbin/.magisk/mirror/bin
I/Magisk  (  226): * Setting up internal busybox
I/Magisk  (  226): * Running post-fs-data.d scripts
I/Magisk  (  226): bind_mount: /sbin/.magisk/img
I/Magisk  (  226): * Running module post-fs-data scripts
I/Magisk  (  226): * Loading modules
I/Magisk  (  226): * Starting MagiskHide
I/Magisk  (  226): hide_utils: Hiding sensitive props
I/Magisk  (  226): hide_list init: [com.google.android.gms]
--------- beginning of system
I/Magisk  (  226): ** late_start service mode running
I/Magisk  (  226): * Running service.d scripts
I/Magisk  (  226): * Running module service scripts
I/Magisk  (  226): proc_monitor: UID=[10007] PID=[1945] ns=[4026532740]
E/Magisk  ( 2821): write failed with 32: Broken pipe
E/Magisk  ( 2822): write failed with 32: Broken pipe
I/Magisk  (  226): * Stopping MagiskHide
E/Magisk  ( 4189): write failed with 32: Broken pipe
E/Magisk  ( 4190): write failed with 32: Broken pipe
--------- beginning of crash
```

**Comment by prenfic** [comment]
Screenshots:
(v6.1)
![01](https://user-images.githubusercontent.com/13857562/53085955-04211700-353f-11e9-86c1-3e1ab73c8d2d.png)
(7.0)
![Uploading 02.png…]()

**Comment by Didgeridoohan** [comment]
Don't report about issues with unofficial builds. I know you state that there's an issue with "stock" as well, but all your provided info is related to an unofficial build that may or may not be in a usable state. Besides, those builds are built with the release flag and won't have as verbose logs as the Canary debug build (which is required to use when reporting about issues)
