### ISSUE TITLE
Fidelity App Detects Root

### ISSUE THREAD

**Issue by zimmerma379** [topjohnwu/Magisk#1108]
Fidelity app v3.30 [com.fidelity.android] is able to detect rooted device even when it is HIDDEN in Magisk Manager.  Also set "Superuser Access=Disabled" but root still detected.  The Fidelity app opens fine and does not detect root for most operations.  But if you have the Fidelity Visa Card as one of your accounts, tapping on it to view gives a "root detected" dialog and you cannot view the account.  ;-(

I sure hope other apps do not adopt this type of root detection.

[Running Magisk v18.0 + Magisk Manager v7.0.0]

**Comment by zimmerma379** [comment]
UPDATE:  Must be issue reported in [#907](https://github.com/topjohnwu/Magisk/issues/907).  After toggling "Magisk Hide" OFF/ON, root is now NOT detected as described above.  I understand this "fix" only last temporarily?  Perhaps I should revert to Magisk v17.3?

**Comment by topjohnwu** [comment]
Use the latest canary, MagiskHide is greatly improved
