### ISSUE TITLE
Magisk v6 was able to hide SU in my phone, but v11.1 is not.

### ISSUE THREAD

**Issue by matiffeder** [topjohnwu/Magisk#111]
I tried many times, but Magisk Hide still invalid.

I flashed rom (ARHD) again, booted to syetem install manager, confirmed it pass SafetyNet, flashed Magisk v11.1, enabled Magisk Hide, and checked Root Checker and SafetyNet attest box in Magisk Hide menu.

But,

Root Checker still ask if I give it access or not.
SafetyNet attest still shows fales.
SafetyNet check in Magisk Manager also shows failed.

Then I disabled Magisk Hide and reboot to system, then enabled Magisk Hide, SafetyNet and Root Checker still recognize my system is rooted.

My phone info: HTC M7, ROM: ARHD 93.0, Android 5.0.2, HTC Sense 6.0, Firmware 7.19.401.30.

Original post: 
https://forum.xda-developers.com/apps/magisk/mod-magisk-v1-universal-systemless-t3432382/post71411261#post71411261

Magisk Log
[log.txt](https://github.com/topjohnwu/Magisk/files/838835/log.txt)

Rom ARHD 93.0 original boot.img (Change the name of boot.img.txt to boot.img)
[boot.img.txt](https://github.com/topjohnwu/Magisk/files/838809/boot.img.txt)

Hope it will be fixed, but I think there are not many people use M7 and Magisk, anyway, it's up to you if you want to fix. Thank you!!!

PS. 如果看不懂我的英文，我可以寫中文

**Comment by JonnyTech** [comment]
I had exactly the same problem with my HTC One M7 and Android Revolution HD 93.0 with Magisk.

Last week I gave up, flashed [TWRP v2.6.3.3](https://dl.twrp.me/m7/twrp-2.6.3.3-m7.img.html) and [LineageOS 14.1](https://mirrorbits.lineageos.org/full/m7/20170302/lineage-14.1-20170302-nightly-m7-signed.zip) and now it works perfectly.

**Comment by M4rt1n17** [comment]
> I had exactly the same problem with my HTC One M7 and Android Revolution HD 93.0 with Magisk.
> 
> Last week I gave up, flashed TWRP v2.6.3.3 and LineageOS 14.1 and now it works perfectly.

Pls install a newer Version of TWRP because of important fixed for Android 7.0+
---> _https://dl.twrp.me/m7/ (TWRP twrp-3.0.0-2)_
---> **https://forum.xda-developers.com/showthread.php?t=2236620 (TWRP twrp-3.1.0)**

**Comment by JonnyTech** [comment]
I cannot. Any newer version is bigger than the recovery partition. Flashing them results in corruption, losing all of my data and preventing the phone from booting. I tried every other version available. Hoping that someone produces a working build soon..

**Comment by matiffeder** [comment]
I'm using the latest version of TWRP

**Comment by JonnyTech** [comment]
Your M7 must not be the same as mine. Different firmware? Cannot S-OFF my one.

**Comment by matiffeder** [comment]
> Your M7 must not be the same as mine. Different firmware? Cannot S-OFF my one.
It's normal M7, not other special versions, firmware is 7.19.401.30 and S-ON.
I think TWRP is off-topic, maybe we call talk that in XDA. This is me: https://forum.xda-developers.com/apps/magisk/mod-magisk-v1-universal-systemless-t3432382/post71411261#post71411261

**Comment by matiffeder** [comment]
Other log.
[magisk_error_20170314_015501.log.txt](https://github.com/topjohnwu/Magisk/files/868164/magisk_error_20170314_015501.log.txt)
