### ISSUE TITLE
only xiaomi8SE cannot use versions higher than 16.6     
只有小米8SE无法使用高于16.6的版本

### ISSUE THREAD

**Issue by kissunyeason** [topjohnwu/Magisk#1110]
8SE的avb验证在boot里
dtbo里反而没有avb验证
而且难以置信的是boot里居然没有dm验证。
希望对您有所帮助
不是MIUI无法使用高于16.6，是只有小米8SE这部手机比较特殊

8SE AVB verification in boot。
There is no AVB validation in dtbo。
And incredibly, there's no DM validation in boot.
I hope it will help you.
It's not that MIUI can't use more than 16.6, it's just xiaomi 8SE, which is a special phone.

**Comment by vvb2060** [comment]
#980

**Comment by kissunyeason** [comment]
just xiaomi 8se not all xiaomi device，i guess xiaomi 9 se will have same issue
