### ISSUE TITLE
Firefly Rockchip RK3399 Unable to repack Boot Image Android 8.1

### ISSUE THREAD

**Issue by Fai29** [topjohnwu/Magisk#1111]
Hi All, I have a FireFly RK3399 board, this board unable to repack Boot Image if I choose recommend install.
If I use "patch boot image" by using official image, it unable to unpack the img.

The log is attached. What can I do?

[magisk_install_log_20190221_164647.log (1).txt](https://github.com/topjohnwu/Magisk/files/2888432/magisk_install_log_20190221_164647.log.1.txt)

**Comment by topjohnwu** [comment]
#755
