### ISSUE TITLE
锤子 坚果Pro 2S Smastisan  Pro 2S 不能安装高于16.6 版本

### ISSUE THREAD

**Issue by MelanPrince** [topjohnwu/Magisk#1112]
只有16.6 版本的 在 recovery 下刷入 开机可以正常使用 magisk 但是 magisk  app 安装插件闪退。

安装18.1 版本的 在 recovery 刷入 zip 文件 开机后 magisk 检测是未安装 magisk

magisk 修改boot 文件 通过fastboot 刷入 patched_boot 开机还是是未安装magisk。

**Comment by kissunyeason** [comment]
https://www.coolapk.com/feed/10427539?shareKey=Y2JlOGExMTZlZTkwNWM2ZmI0NjM~&shareUid=2013801&shareFrom=com.coolapk.market_9.0.2

**Comment by vvb2060** [comment]
根据报告，坚果Pro 2S 也适用于此修复：# 1115
所以可能是高通的问题……
[Magisk-v18.2-69d10b747.zip](https://github.com/topjohnwu/Magisk/files/2893105/Magisk-v18.2-69d10b747.zip)

**Comment by MelanPrince** [comment]
> https://www.coolapk.com/feed/10427539?shareKey=Y2JlOGExMTZlZTkwNWM2ZmI0NjM~&shareUid=2013801&shareFrom=com.coolapk.market_9.0.2

亲测支持  坚果Pro 2S 看来是 高通710 的 bug。

**Comment by xiaowyyyyya** [comment]
#980

**Comment by tanghengvip** [comment]
@MelanPrince 你现在搞定了对吗？
坚果Pro 2S v6.6.5.5.4_TNT  +  magisk-taichi-v4.7.4.zip 吗？
请问面具是用哪个版本呢？

**Comment by MelanPrince** [comment]
@tanghengvip 18.2 18111
https://cdn.jsdelivr.net/gh/yzkpqv68745/magisk/alpha.json

这里下载。

**Comment by tanghengvip** [comment]
> @tanghengvip 18.2 18111
> https://cdn.jsdelivr.net/gh/yzkpqv68745/magisk/alpha.json
> 
> 这里下载。

感谢！已完美刷入使用中。

**Comment by courage2018** [comment]
怎么刷入，需要先解BL，刷REC，再刷入吗？
