### ISSUE TITLE
coolpad great god f1 not supported

### ISSUE THREAD

**Issue by calidion** [topjohnwu/Magisk#1116]
Coolpad 8297-c00

**Comment by Didgeridoohan** [comment]
And unless you provide every possible detail as to why it isn't supported, and what can be done to change that, things will likely stay that way.

**Comment by calidion** [comment]
what input should i provide?

**Comment by Didgeridoohan** [comment]
Whatever is necessary to show why Magisk doesn't work on the device in question.

**Comment by martyfender** [comment]
Logs would be a good start.

[https://www.didgeridoohan.com/magisk/MagiskHelp](url)
