### ISSUE TITLE
升級18.1過程遇阻，hide unhide問題？無法升級問題

### ISSUE THREAD

**Issue by Justsoos** [topjohnwu/Magisk#1117]
相信很多人都遇到這個問題，但沒有搜索到官方解決方案，或者重要提示。
MIUI 9，Android 6，原裝18.0，Manager版本是6.1.0使用正常。幾星期前有Manager 7.0提示升級，在Manager內選擇升級後，原6.1.0Manager 圖標，apk安裝都在，新產生一個7.0的圖標和安裝，而且新app顯示magisk沒有安裝！
第一重誤解：
提示需要新裝magisk… 感覺不對勁，就沒有繼續。
最終在
https://www.reddit.com/r/Android/comments/an02pu/magisk_v181_and_magisk_manager_v700_is_released/
有網友提示是之前使用了hide功能，導致Manager找不到magisk，然後取消6.1.0的hide，重啟手機，再次點擊6.1.0的升級…
第二重誤解：
這次從6.1.0的Manager升級，還是出現新圖標，不是覆蓋升級，新app打開後，兩個更新一直在轉圈… 等了十分鐘還在轉
![screenshot_20190223094258](https://user-images.githubusercontent.com/3480043/53279935-cfd07500-374f-11e9-8af2-de183d3dcb5b.png)

第三重結果：
很偶然下，用手指從上往下拉了一下，窗口這才有了反應，提示變成Manager已經更新，magisk需要額外下載，點擊下載後，瞬間顯示toast更新失敗
![screenshot_20190223094404](https://user-images.githubusercontent.com/3480043/53279941-dd85fa80-374f-11e9-8f6c-bd9cd6e4c52a.png)

目前就只好停止在這裡，繼續用舊版了。
另外還有個bug，18.0 + 6.1.0 在沒有網絡接入情況下，會閃退。

**Comment by vvb2060** [comment]
都是不会解决，或已经修复的问题。
另外，显示额外安装并不是真的需要，你这个只是在没有root权限情况下的误判。

**Comment by Justsoos** [comment]
目前7.0 Manager 卡在這裡，選擇Boot修補，失敗。
是不是意味著要
1，卸載6.10 Manager
2，重啟到recovery刷18.1 ？？
那麼之前安裝的模塊是否要重新安裝，還是會被覆蓋？

![screenshot_20190223162009](https://user-images.githubusercontent.com/3480043/53283935-15109900-3788-11e9-9738-f031804c1f1d.png)
![screenshot_20190223162306](https://user-images.githubusercontent.com/3480043/53283936-15a92f80-3788-11e9-96d8-c8f0c5f9e5ff.png)

**Comment by Justsoos** [comment]
继续解决此问题，选择了recovery先刷uninstall magisk，再重新刷18.1
多次启动后可以正常使用了。
但还是存在一个老bug，root 权限弹出窗口，必须要两次以上运行root需求程序才能正确弹出。
而且，这次刷18.1之后，多次运行绿色守护，都再无法获取root权限
也许是绿色守护通过xposed框架获取了权限，可以忽略magisk？？
如何手动获取root权限？？
我不是记得很清楚，之前xposed应该是有root申请权限的，这次升级后，怎么运行都不给提示了… …
用myandroidtools打开发现magisk manager 一个服务没有开。
也许并不是这个问题？？
![img_20190223_180032](https://user-images.githubusercontent.com/3480043/53284975-0af59700-3796-11e9-9f3c-076bee9ced43.png)
