### ISSUE TITLE
华为P9 EVA B377 完全安装Magisk 导致不能正常开机

### ISSUE THREAD

**Issue by MelanPrince** [topjohnwu/Magisk#1119]
fastboot 刷入patched boot  开机 安装 magisk 主程序 可以 正常唤醒 root 正常使用。

联网 安装magisk 额外组件 重启 就会不开机。

EVA B399SP17 同样操作 正常启动 使用

android 7.0 EMUI  5.0

**Comment by topjohnwu** [comment]
那是魔劍的問題，根 Magisk 本身無關。
