### ISSUE TITLE
Root not detected for Kitkat 4.4.4

### ISSUE THREAD

**Issue by bgamez23** [topjohnwu/Magisk#1121]
Failed to detect root for Android Kitkat 4.4.4. the installation works fine without any problem but apps that needs root permission doesn't detected.

![screenshot_2019-02-24-19-58-08](https://user-images.githubusercontent.com/1854368/53298890-c853bd80-386e-11e9-8db2-2ef49561c065.png)
![screenshot_2019-02-24-19-58-22](https://user-images.githubusercontent.com/1854368/53298892-c8ec5400-386e-11e9-9dd4-b477c0920206.png)
![screenshot_2019-02-24-19-58-35](https://user-images.githubusercontent.com/1854368/53298893-c8ec5400-386e-11e9-8a33-f0b41590aa90.png)
![screenshot_2019-02-24-19-58-01](https://user-images.githubusercontent.com/1854368/53298894-c8ec5400-386e-11e9-8d8d-edb117d83946.png)

**Comment by bgamez23** [comment]
here is the magisk log
[magisk_log_20190224_200159.log](https://github.com/topjohnwu/Magisk/files/2897854/magisk_log_20190224_200159.log)

**Comment by bgamez23** [comment]
Hide Magisk Manager in the settings it wont download the files. just like the same before.

SafetyNet Check Success
x ctsProfile: false

**Comment by bgamez23** [comment]
![screenshot_2019-02-24-20-14-45](https://user-images.githubusercontent.com/1854368/53299098-313c3500-3871-11e9-9c93-76741348357e.png)
![screenshot_2019-02-24-20-15-26](https://user-images.githubusercontent.com/1854368/53299099-313c3500-3871-11e9-8177-c3d38541e625.png)
[magisk_log_20190224_201534.log](https://github.com/topjohnwu/Magisk/files/2897871/magisk_log_20190224_201534.log)

**Comment by topjohnwu** [comment]
Please check the logs yourself. Your kernel does not support mount namespace, thus cannot use MagiskHide.
Also, please read the instructions to report bugs. You are using release builds, which does not provide any useful information.

**Comment by bgamez23** [comment]
i use both and both magisk_log is provided. as you can see the version the 1st one is 
Magisk V18.1 (18100)
Magisk Manager v7.0.0 (185)

Canary Build
Magisk v18.2-660e0dc0 (18108)
Magisk Manager v7.0.0-3ebc886f (188)
(com.YHqVb1qj.wtHxv.d)

**Comment by bgamez23** [comment]
root permission works fine if i use kingroot. but only magisk does not work with this version of kitkat.
