### ISSUE TITLE
Magisk Manager 7 not patching boot.img

### ISSUE THREAD

**Issue by kftX** [topjohnwu/Magisk#1123]
I'm currently testing a in-development version of PA (Pie) for the Mi A2 (I'm not the dev) Lite but I've hit a stumbling block with applying magisk to the rom. As in, I can't get it to work in any way. Flashing via TWRP isn't working but that's an issue with the TWRP on our device specifically, that will hopefully be fixed.

However, I can't even patch the _boot.img_ file to work in any way. I've tried patching it on my device, didn't work. I tried patching it on my GF's phone which is running LOS/Magisk 18.1/Magisk Manager 7 and it doesn't do anything either. The patched boot is a few bytes smaller (20,634KB vs 20,640KB) but it seems to do nothing at all. And if I pass that patched boot through Magisk Manager to patch, it says it's stock still.

Any ideas? Or is this a known but with Magisk Manager? Is there any sort of log I can provide that could help?

Edit: Ran out of ideas and decided to flash Magisk 17.3 and using Manager 6.1.0 and everything is working. I don't even.

Edit 2: Updating to 18.0 over 17.3 didn't work. Uninstalled 17.3, installed 18.0. 18.0 doesn't work either. So anything beyond 17.3 is a dud.

**Comment by Didgeridoohan** [comment]
Installation log would be a good start... There's a button for it, right there when you patch the image.

**Comment by kftX** [comment]
I apologize! here it is:

```
- Copying image to cache
- Device platform: arm64-v8a
- Downloading zip
... 0%
1038+1 records in
1038+1 records out
1063528 bytes transferred in 0.017 secs (62560470 bytes/sec)
- Unpacking boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [21126177]
RAMDISK_SZ      [0]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
PATCH_LEVEL     [2018-10]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 firmware_class.path=/vendor/firmware_mnt/image loop.max_part=7 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992 androidboot.selinux=permissive buildvariant=userdebug]
CHECKSUM        [fa9e299e0ce01c3b1e07319678677e0e398289fc]
DTB             [11554741]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [raw]
- Checking ramdisk status
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
- Stock boot image detected
- Backing up stock boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Compressing to [stock_boot_420f4e0517dfb5e42d824e0ac8bd1900e1569ae3.img.gz]
cp: can't stat 'ramdisk.cpio': No such file or directory
- Patching ramdisk
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Add entry [init] (0750)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[false]
Segmentation fault 
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Patch @ 01540610 [736B69705F696E697472616D667300]->[77616E745F696E697472616D667300]
- Repacking boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [21126177]
RAMDISK_SZ      [0]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
PATCH_LEVEL     [2018-10]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 firmware_class.path=/vendor/firmware_mnt/image loop.max_part=7 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992 androidboot.selinux=permissive buildvariant=userdebug]
CHECKSUM        [fa9e299e0ce01c3b1e07319678677e0e398289fc]
DTB             [11554741]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [raw]
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [21132058]
RAMDISK_SZ      [0]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
PATCH_LEVEL     [2018-10]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 firmware_class.path=/vendor/firmware_mnt/image loop.max_part=7 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992 androidboot.selinux=permissive buildvariant=userdebug]
CHECKSUM        [dec418c6b247ffb4efe34e927e15bf750984c0f5]
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Cleaning up...

****************************
 Patched image is placed in 
 /storage/emulated/0/Download/patched_boot.img 
****************************
- All done!
```

**Comment by topjohnwu** [comment]
#980

**Comment by tymofiishpundra78-a11y** [comment]
- Copying image to cache
- Device platform: arm64-v8a
- Downloading zip
... 0%
1038+1 records in
1038+1 records out
1063528 bytes transferred in 0.017 secs (62560470 bytes/sec)
- Unpacking boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [21126177]
RAMDISK_SZ      [0]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
PATCH_LEVEL     [2018-10]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 firmware_class.path=/vendor/firmware_mnt/image loop.max_part=7 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992 androidboot.selinux=permissive buildvariant=userdebug]
CHECKSUM        [fa9e299e0ce01c3b1e07319678677e0e398289fc]
DTB             [11554741]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [raw]
- Checking ramdisk status
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
- Stock boot image detected
- Backing up stock boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Compressing to [stock_boot_420f4e0517dfb5e42d824e0ac8bd1900e1569ae3.img.gz]
cp: can't stat 'ramdisk.cpio': No such file or directory
- Patching ramdisk
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Add entry [init] (0750)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[false]
Segmentation fault 
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Patch @ 01540610 [736B69705F696E697472616D667300]->[77616E745F696E697472616D667300]
- Repacking boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [21126177]
RAMDISK_SZ      [0]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
PATCH_LEVEL     [2018-10]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 firmware_class.path=/vendor/firmware_mnt/image loop.max_part=7 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992 androidboot.selinux=permissive buildvariant=userdebug]
CHECKSUM        [fa9e299e0ce01c3b1e07319678677e0e398289fc]
DTB             [11554741]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [raw]
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [21132058]
RAMDISK_SZ      [0]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
PATCH_LEVEL     [2018-10]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 firmware_class.path=/vendor/firmware_mnt/image loop.max_part=7 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992 androidboot.selinux=permissive buildvariant=userdebug]
CHECKSUM        [dec418c6b247ffb4efe34e927e15bf750984c0f5]
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Cleaning up...

****************************
 Patched image is placed in 
 /storage/emulated/0/Download/patched_boot.img 
****************************
- All done!
-
