### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by timikesmarky** [topjohnwu/Magisk#1124]
Hello,

I just migrated from supersu to magisk as my main root app. All is great except one big thing I miss. SuperSU allowed me to see logs of apps, the commands apps used as root in the logs tab. I could see what the apps did as root. Magisk just shows a list but no detailed logging. Can you please add this feature? 

Thank you!

https://lh3.googleusercontent.com/vZI-YSr5F5pPmw6t9iCAMfQoLyThgjtNhILNC-AXlYw8JzEU3XgJ5_av_Ta_SCmRDXA=w1920-h937-rw

**Comment by DenyDarko** [comment]
#610
