### ISSUE TITLE
Magisk v18.1 not working on Nexus5x 8.1.0

### ISSUE THREAD

**Issue by vanshu** [topjohnwu/Magisk#1126]
Here's what I'm trying....

Phone: Google Nexus5x

Bootloader: Unlocked

Os Version : 8.1.0 (OPM7.181205.001, Dec 2018)

From fasboot, I load TWRP

fastboot boot twrp-3.2.3-0-bullhead.img

Run

adb sideload Magisk-v18.1.zip

Seems to load fine. but Zip signature verification failed,

Wipe Dalvik cache Reboot phone

Phone reboots fine, but Magisk isn't installed?

Please help.

**Comment by Didgeridoohan** [comment]
How about using the TWRP install button?

**Comment by vanshu** [comment]
> How about using the TWRP install button?

It doesn't work too.

**Comment by Didgeridoohan** [comment]
Unless you can provide logs there's nothing anyone can do to help...

**Comment by topjohnwu** [comment]
I have a Nexus 5X and I'm using it on my device.

**Comment by vanshu** [comment]
> I have a Nexus 5X and I'm using it on my device.

are you sure your  nexus5x os Version : 8.1.0 (OPM7.181205.001, Dec 2018) or not ?
