### ISSUE TITLE
Relock bootloader

### ISSUE THREAD

**Issue by GabrielTK** [topjohnwu/Magisk#113]
Hey Guys!
I'm planning to relock the bootloader after magisk install. I'll keep (almost) everything stock by just booting to TWRP instead of flashing it. Is there any problem on it??

**Comment by Didgeridoohan** [comment]
This is not a question for an issue on GitHub. Better suited for the support thread on xda.
https://forum.xda-developers.com/apps/magisk

**Comment by GabrielTK** [comment]
Ok, thx :D

On Mar 14, 2017 8:59 AM, "Didgeridoohan" <notifications@github.com<mailto:notifications@github.com>> wrote:

This is not a question for an issue on GitHub. Better suited for the support thread on xda.
https://forum.xda-developers.com/apps/magisk
