### ISSUE TITLE
Frequent zygote64 crash & random phone freeze since 18.1

### ISSUE THREAD

**Issue by CrescendoFang** [topjohnwu/Magisk#1130]
I got so many tombstones like this since 18.1.
Also my phone seems to randomly freezing (changed nothing) since this 18.1 build, even when left alone charging.

FULL LOGS: https://pastebin.com/bPk2BMT9

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/natrium/natrium:8.0.0/OPR1.170623.032/V10.2.1.0.OBGCNXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 969, tid: 969, name: main  >>> zygote64 <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference

**Comment by topjohnwu** [comment]
Nothing to do with Magisk

**Comment by CrescendoFang** [comment]
eh? I'll factory reset my phone then....
FYI, it stopped since canary build GitHub commit 8032bd0b.
