### ISSUE TITLE
transplant magiskboot use cygwin error occurred。 

### ISSUE THREAD

**Issue by 7763sea** [topjohnwu/Magisk#1131]
when i compile magiskboot lib, **native/jni/utils/**  this error occurred.

home/Administrator/utils/file.cpp:10:10: 致命错误：sys/sendfile.h：No such file or directory
 #include <sys/sendfile.h>

/home/Administrator/utils/file.cpp:12:10: 致命错误：linux/fs.h：No such file or directory
 #include <linux/fs.h>

how to resolve?

**Comment by topjohnwu** [comment]
Both headers are Linux only. I currently have no plans to port `magiskboot` to other platforms. You can replace the function `sendfile` to your own implementation
