### ISSUE TITLE
F2FS drivers 模块安装问题

### ISSUE THREAD

**Issue by youyim123** [topjohnwu/Magisk#1132]
努比亚X（F2FS drivers）安装模块时提示：“! /magisk_merge.img mount failed...”，但是我在/data/adb/modules下创建一个文件夹，重启手机后安装模块就可以成功安装，模块存在于/data/adb/modules目录下。
另外7.0.0-8032bd0b和7.0.0-5764f0c8版本的magisk.apk会重复提示安装运行环境，即使之前已经安装成功了。

**Comment by topjohnwu** [comment]
已經在 canary 裡面解決了，請不要一直重複回報.....

**Comment by youyim123** [comment]
@topjohnwu 安装的就是你今天更新的canary版本https://github.com/topjohnwu/magisk_files

**Comment by topjohnwu** [comment]
那是就是你安裝的模組沒有使用表準 template API，所有標準 template 都已經內建支援 imageless modules 了。
最新版本的 Magisk 已經完全不使用任何 image ，在你的錯誤訊息中 magisk_merge.img 的出現代表了安裝仍然在使用舊版的安裝邏輯，並不是我能控制的。
