### ISSUE TITLE
[Idea] Improve strings updates

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#1133]
Hello @topjohnwu 

Idk if this would be possible, but given the sometimes long delays in getting translation updates, is it possible to set up a faster delivery system for language file updates?

For example, if the Spanish translations are updated just after a major update of Magisk, then the Spanish users of Magisk must wait a while before the next translation update arrives.

I don't know if a system like this is possible to implement in JAVA or other.

**Comment by DenyDarko** [comment]
There are free 3rd party platforms that makes this a lot easier.

https://www.transifex.com/ for example is used by AdAway @perfectslayer

**Comment by xerta555** [comment]
@DenyDarko I was not talking about the type of tool to use to complete translations, but about the implementation of a system that would make each new update of online translations available.

I don't know if services like Transifex allow this, for me they provide another type of tool that simplifies the incorporation of translations into language files.

**Comment by PerfectSlayer** [comment]
There is some tool to sync translation from github to transifex then from transifex to github once a localization is complete.

The main issue is you will need a server to setup this tool (I am not aware of a free hosted solution) and Magisk seems to heavily rely on GitHub infra instead of having its own server. (which I understand perfectly :wink:)

Check txgh for more details: https://docs.transifex.com/integrations/github-txgh

**Comment by xerta555** [comment]
@PerfectSlayer 
I think I have not been understood, my question is not about a tool to facilitate the translation itself, my question is about whether or not it is possible to have the language file automatically downloaded for the one used by the user, for example...

Example:
- the Spanish translation file is updated one Thursday morning after deployment of a major update of Magisk and the Manager
- Spanish Magisk users open their phones to check the day's news
- while these users are checking the news or simply deactivating their aircraft mode, a wake-lock call from the Manageur will automatically check the Github URL address if there has been an update since the last check
- the manager automatically downloads and installs the file from Github and installs it to immediately schedule a relaunch of the Manageur app

I guess my process can be simplified, but the basic idea is there.

**Comment by PerfectSlayer** [comment]
Okay, so you want to update app locales at runtime.

Even if it is possible, you can programmatically load bytecode and strings, I don't think it is a good idea on Android.

The usual way to do this is to shop translations as resources, bundled in the app, and update/publish the app the more often you could. That's way your have CI/CD, Play Store auto-update and app bundle.

I won't answer for @topjohnwu but I don't think runtime update is the android way to do locale update.

**Comment by topjohnwu** [comment]
Dynamic updates doesn't seem to be possible. Although indeed I can push more updates for Magisk Manager (I just never track translations). I will close this issue, but thanks for all the suggestions above!

**Comment by xerta555** [comment]
> Dynamic updates doesn't seem to be possible. Although indeed I can push more updates for Magisk Manager (I just never track translations). I will close this issue, but thanks for all the suggestions above!

If I interpret correctly what you say, a self-update system could be implemented directly by the Manager if you wanted it (if we didn't have better ideas)?
