### ISSUE TITLE
PowerOff Charging Issue

### ISSUE THREAD

**Issue by Link-Zhang** [topjohnwu/Magisk#1137]
Device: OnePlus 6T 
OS: H2OS 9.0.4

After using Magisk to root my device(OP6T), some version of Magisk(16.7-18.1) comes a little issue. But Magisk 16.4 seems OK! Could you fix it in the next coming version ?
 Issue Description: 
1.Totally Powerof my device
2. Charge it.
3. Issue:
    (1) 16.7-18.1: stop at google warning, without charging animation
   (2)16.4: show some google warning, but later comes with charging animation.

**Comment by DenyDarko** [comment]
#906
