### ISSUE TITLE
MagiskHide stops working with an extensive list of Apps to hide root from

### ISSUE THREAD

**Issue by NoobAndProud** [topjohnwu/Magisk#1138]
It needs more testing but I noticed that MagiskHide is fine after a reboot but stops working after an inconsistent (1-5 hours) amount of time.
Talking about above 50+ apps (games, Google apps, "apps who doesn't use root as such don't need to see root").
Getting an even bigger list (100+) does force MagiskHide to completely fail (even after reboot).
If logs are necessary to define further work I'm happy to oblige but need instructions to do so.
I'm sorry for any confusion in my error report as English isn't my native language.
I don't expect that MagiskHide can work with an infinite amount of apps and failing directly is (in my opinion) a better way to handle it but this error report is more about that it's failing after a inconsistent time period (thinking you are safe and then apps fail and block your device).

**Comment by DenyDarko** [comment]
John already said that this is expected when you spam the hide list the way Magisk functions.you only add the absolutely required stuff .

**Comment by Didgeridoohan** [comment]
Apart from what's already been said, what Magisk version are you testing this on? Besides the fact that you should always report bugs based on the current code (so only in the latest Canary release), if you happen to be using Magisk v18.0 or v18.1, MagiskHide intermittingly failing is a known bug on those releases that has been fixed upstream.

**Comment by NoobAndProud** [comment]
I was not aware but I thank you for the feature request on #1139.
I had noticed that MagiskHide completely stops working at reboot with a to big list, but with a "moderately" long list it stopped working after running for a longer period that was what threw me off.

**Comment by NoobAndProud** [comment]
@digeridoohan
Newest OOS update 9.0.12, 7.0.0 Manager, 18.1 Magisk Stable.

**Comment by Didgeridoohan** [comment]
So, in other words: you can close this issue, since it's already been fixed. But that doesn't mean that you should keep a Hide list that large on future releases...
