### ISSUE TITLE
[Feature Request]: Implement a warning when Magisk hide list is abused.

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#1139]
As Magisk misbehaving and can cause serious issues when users are spamming the hide list, it might be a good idea to show a warning after X amount of apps additions.

That came to me by reading #1138

**Comment by NoobAndProud** [comment]
+1 interest.

**Comment by topjohnwu** [comment]
The new MagiskHide system should be much more stable, adding too many targets to the list shall only drain battery.
