### ISSUE TITLE
Magisk Hide should have a explanation line on top

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [topjohnwu/Magisk#1141]
IMHO "Magisk Hide" should have a explanation line on top that explain in maybe one sentence a new user what kind of apps can/should be hidden. Because at first I thought this is to hide apps from others, like Lucky Patcher from Google Store and only later I read that this is (AFAIK, now) for apps like from banks, to hide Magisk from them.

**Comment by topjohnwu** [comment]
You should do some research before messing with your phone with Magisk though, I personally don't think writing every single detail in the app is a good idea :)
