### ISSUE TITLE
HDFC bank app v10.0.1 detected root

### ISSUE THREAD

**Issue by SasikumarN** [topjohnwu/Magisk#1144]
HDFC app v10.0.1  detects root on startup.

Package/activity name: com.snapwork.hdfc/com.hdfc.retail.netbanking.HDFCBank

Magisk version: 18.2-5764f0c8(18110)
Magisk App: v7.0.0-5764f0c8(190)

Tested on Magisk canary debug build.

**Comment by DenyDarko** [comment]
No it doesn't.

![screenshot_20190228-090012](https://user-images.githubusercontent.com/3320229/53547300-54980600-3b37-11e9-9c28-21761a5bacb4.jpg)

**Comment by SasikumarN** [comment]
You are using old version (v7). That was working fine with magisk hide.
New version v10.0.1 version which is always finding the root.

![image3489075734488190981](https://user-images.githubusercontent.com/7869868/53559446-1c60e980-3b70-11e9-9899-3e9ead73e005.jpg)
-

**Comment by SasikumarN** [comment]
@topjohnwu 

I mentioned clearly in the first post as HDFC Bank app v10 has this issue. But @DenyDarko shared HDFC Bank app v7 screenshot.
This issue has to be reopened  since I shared the enough detail in above post.

**Comment by DenyDarko** [comment]
I've managed to find the new v10.
So.. Opened it, and as expected detected root:
![screenshot_20190228-154252](https://user-images.githubusercontent.com/3320229/53570664-b70cf880-3b6f-11e9-94ff-02f0d4dfa937.jpg)

Then, I've went into MagiskManager and enabled hiding for the app. It launched just fine:
![screenshot_20190228-154321](https://user-images.githubusercontent.com/3320229/53570710-d2780380-3b6f-11e9-88ea-bd6a791003ea.jpg)

This is not a Magisk issue.

**Comment by SasikumarN** [comment]
could you please link me the steps that I need to do for debugging this?

I have tried the following,
1. Uninstalled root required app such as titanium backup.
2. Enable /disable magisk hide after adding hdfc to hide list
3. Every time rebooted for each and every settings change
4. Magisk canary release build
5. Magisk debug build 

None of these works for me. FYI, I haven't installed any modules in magisk.

Here attached debug logs
`
02-28 07:22:37.847   461  7629 I Magisk  : * Stopping MagiskHide
02-28 07:22:37.858   461  1945 D Magisk  : proc_monitor: running cleanup
02-28 07:22:37.859   461  1945 D Magisk  : proc_monitor: terminating
02-28 07:22:38.861   461  7631 I Magisk  : * Starting MagiskHide
02-28 07:22:38.861   461  7631 I Magisk  : hide_utils: Hiding sensitive props
02-28 07:22:38.862   461  7631 D Magisk  : resetprop: getprop [ro.boot.verifiedbootstate]: [green]
02-28 07:22:38.862   461  7631 D Magisk  : resetprop: getprop [ro.boot.veritymode]: [enforcing]
02-28 07:22:38.862   461  7631 D Magisk  : resetprop: getprop [ro.debuggable]: [0]
02-28 07:22:38.862   461  7631 D Magisk  : resetprop: getprop [ro.secure]: [1]
02-28 07:22:38.862   461  7631 D Magisk  : resetprop: getprop [ro.build.type]: [user]
02-28 07:22:38.862   461  7631 D Magisk  : resetprop: getprop [ro.build.tags]: [release-keys]
02-28 07:22:38.862   461  7631 D Magisk  : resetprop: getprop [ro.build.selinux]: [0]
02-28 07:22:38.862   461  7631 D Magisk  : hide_list: initialize
02-28 07:22:38.862   461  7631 I Magisk  : hide_list init: [com.snapwork.hdfc]
02-28 07:22:38.872   461  7631 I Magisk  : hide_list init: [com.google.android.gms]
02-28 07:22:38.901   461  7631 D Magisk  : proc_monitor: Updating inotify list
02-28 07:22:39.087   461  7631 D Magisk  : proc_monitor: Monitoring /data/app/com.snapwork.hdfc-YVWmXHA8qG_OX3-_-0DOHQ==/base.apk
02-28 07:22:39.087   461  7631 D Magisk  : proc_monitor: Monitoring /data/app/com.google.android.gms-2-boxixm4G-5qq9dhgKn1w==/base.apk
02-28 07:22:39.087   461  7631 D Magisk  : proc_monitor: Monitoring /data/system
02-28 07:23:05.555   461  7631 D Magisk  : proc_monitor: /data/system/packages.xml updated
02-28 07:23:05.555   461  7631 D Magisk  : proc_monitor: Updating inotify list
02-28 07:23:05.742   461  7631 D Magisk  : proc_monitor: Monitoring /data/app/com.snapwork.hdfc-YVWmXHA8qG_OX3-_-0DOHQ==/base.apk
02-28 07:23:05.742   461  7631 D Magisk  : proc_monitor: Monitoring /data/app/com.google.android.gms-2-boxixm4G-5qq9dhgKn1w==/base.apk
02-28 07:23:05.742   461  7631 D Magisk  : proc_monitor: Monitoring /data/system
02-28 07:23:09.790   461  7631 D Magisk  : proc_monitor: /data/system/packages.xml updated
02-28 07:23:09.790   461  7631 D Magisk  : proc_monitor: Updating inotify list
02-28 07:23:09.975   461  7631 D Magisk  : proc_monitor: Monitoring /data/app/com.snapwork.hdfc-YVWmXHA8qG_OX3-_-0DOHQ==/base.apk
02-28 07:23:09.975   461  7631 D Magisk  : proc_monitor: Monitoring /data/app/com.google.android.gms-2-boxixm4G-5qq9dhgKn1w==/base.apk
02-28 07:23:09.975   461  7631 D Magisk  : proc_monitor: Monitoring /data/system
02-28 07:23:13.471   461  7512 D Magisk  : su: return code=[0]
02-28 07:23:16.965   461  7631 D Magisk  : proc_monitor: /data/system/packages.xml updated
02-28 07:23:16.965   461  7631 D Magisk  : proc_monitor: Updating inotify list
02-28 07:23:17.149   461  7631 D Magisk  : proc_monitor: Monitoring /data/app/com.snapwork.hdfc-YVWmXHA8qG_OX3-_-0DOHQ==/base.apk
02-28 07:23:17.149   461  7631 D Magisk  : proc_monitor: Monitoring /data/app/com.google.android.gms-2-boxixm4G-5qq9dhgKn1w==/base.apk
02-28 07:23:17.149   461  7631 D Magisk  : proc_monitor: Monitoring /data/system
02-28 07:23:23.260   461  7946 D Magisk  : su: request from pid=[7942], client=[10]
02-28 07:23:23.260   461  7946 D Magisk  : su: request from uid=[10243] (#1)
02-28 07:23:23.260   461  7946 D Magisk  : magiskdb: query magiskhide=[1]
02-28 07:23:23.260   461  7946 D Magisk  : magiskdb: query requester=[com.uou9z9JVSoyp.OBA]
`

**Comment by DenyDarko** [comment]
Is Magisk hidden? 

(4th option in settings)

**Comment by SasikumarN** [comment]
@DenyDarko 
1. Manager package name randomized
2. Safetynet passed

**Comment by Didgeridoohan** [comment]
> I can see the below error in 18.1 but not on canary debug build.

Bug reports concerning the stable release are not interesting if they cannot also be reproduced with the current Canary build. Especially if we're talking about MagiskHide, since it has been rewritten from scratch.

Only work with the Canary builds when debugging...

**Comment by SasikumarN** [comment]
Okay, I found my problem statement.

Uninstalling HDFC bank and reinstalling it worked. But force stop & clearing the app data not helped here.

@DenyDarko  Thanks for your input :)

**Comment by aadithyarulez** [comment]
I have the same issue, tried magisk core only modules, reinstalling the app, turn ff phone permission for google play services. But it still detects roots.

**Comment by binoysankar** [comment]
For me the above is not solved with the above solution. Seems hdfc have updated the app and its still finding the root.

**Comment by tousief** [comment]
I have tried all the possible provided methods but hdfc v10 app detects root.

I have the latest magisk installed

I have passed net safety test.

Device is certified in playstore.

Hidden all the banking apps in magisk hide

Repacked the magisk with different name.

Result all banking apps work but HDFC net banking app is not working.

I even tried reinstalling the apk

Also tried restarting the device but nothing works for HDFC netbanking app. Can you please check and help me out.

I'm using Asus Zenfone 5z.

Rooted using patched boot.img

Thanks in advance.
