### ISSUE TITLE
[Feature Request] Magisk promt: setting for pre-selected time period.

### ISSUE THREAD

**Issue by streawrov** [topjohnwu/Magisk#1146]
I think it would be good for the comfortability if you can choose a default preselected time period for the Magisk prompt. Most of the time i want to be prompted for any root request and sometimes it is inconvenient to change the time period everytime from permanently to one-time or 10 minutes. 
I think it would enhance the user experience.

**Comment by topjohnwu** [comment]
Magisk Manager already remembers the last used option for an app. So basically if you chose "once" for a certain app, it will always default to "once" for that particular app.
I am not interested in making yet another option to change the default of all apps :)

**Comment by streawrov** [comment]
Thanks for the quick answer. I didn't notice this feature at all. That's exactly what I was looking for. Sorry for wasting your time. Best regards.
