### ISSUE TITLE
There are a lot of problems with A/B rooting

### ISSUE THREAD

**Issue by PrakarshRocks** [topjohnwu/Magisk#1147]
@topjohnwu @phhusson 

Please add a way for magisk to detect when it is removed like when I did ota update it removed root for second slot and every time I have to go into magisk and reflash to second slot. It would be beautiful if this could be done automatically. Can it?

BTW I don't know if I'll get your reply so please telegram me your reply @prakyy

**Comment by DenyDarko** [comment]
So let me understand your logic.

You ask and mention the developer to invest time and write plenty of code so you won't have to tap 3 buttons once per around two months.

Correct?

**Comment by PrakarshRocks** [comment]
> So let me understand your logic.
> 
> You ask and mention the developer to invest time and write plenty of code so you won't have to tap 3 buttons once every one-two months.
> 
> Correct?

You don't understand first off I get updates every 15 days, second if I ever forget to talk those 3 buttons,I loose my root and since I don't own a computer it becomes VERY difficult for me to regain root if it is too hard to add this feature then please close my request but I hoped this would make it.

**Comment by NoobAndProud** [comment]
Can't you change back to boot in the other slot (which had root) and repatch the previous unrooted slot? Which makes it possible to reapply root without a computer. (doesn't have TWRP the option to choose next bootslot?)

**Comment by topjohnwu** [comment]
No, it is not possible
