### ISSUE TITLE
UNBLOCKFILE doesn't get deleted

### ISSUE THREAD

**Issue by Fox2Code** [topjohnwu/Magisk#1149]
The magisk UNBLOCKFILE (**/dev/.magisk_unblock**) doesn't get deleted

I provide the **logs.zip** witch contain three file
magisk.log > The logs of magisk
logcat.log > the boot logcat of my phone
cmdresult.txt > the result of the command **ls -la** on **/dev** folder

[logs.zip](https://github.com/topjohnwu/Magisk/files/2919526/logs.zip)

This is a big hiding issue because magisk can be detected just by listing the content of the **/dev** folder

**Comment by topjohnwu** [comment]
What version are you using? It is not present on any of my devices.

**Comment by Fox2Code** [comment]
@topjohnwu I found why this happen it due to the post-fs-data duration is more than 10 second
I have enable the core only mode and the file was gone
