### ISSUE TITLE
Hide does not work for some applications Such as IRIAM

### ISSUE THREAD

**Issue by Minato-Aqua** [topjohnwu/Magisk#1151]
For example: IRIAM, this application can detect the existence of Magisk anyway.
I have passed the S66afetyNet test
I used a random package name to hide Magisk Manager
I have not installed Xposed, Lucky Patcher, no other root management application.
Developer option has been turned off
Also tried uninstalling Magisk Manager
However, IRIAM will detect Magisk anyway.**
![screenshot_20190302-083346](https://user-images.githubusercontent.com/42766704/53675186-f69e2680-3cce-11e9-9efb-a9ec44e6d646.jpg)
**

**Comment by topjohnwu** [comment]
#1152

**Comment by DenyDarko** [comment]
No it doesn't.
Again, this is not a support thread, you should go to XDA thread and ask for help there :)

![screenshot_20190302-071913](https://user-images.githubusercontent.com/3320229/53677625-b6817880-3cbb-11e9-83b8-30bf8f346ea2.jpg)

**Comment by mutza974** [comment]
> For example: IRIAM, this application can detect the existence of Magisk anyway.
> I have passed the S66afetyNet test
> I used a random package name to hide Magisk Manager
> I have not installed Xposed, Lucky Patcher, no other root management application.
> Developer option has been turned off
> Also tried uninstalling Magisk Manager
> However, IRIAM will detect Magisk anyway.**
> ![screenshot_20190302-083346](https://user-images.githubusercontent.com/42766704/53675186-f69e2680-3cce-11e9-9efb-a9ec44e6d646.jpg)
> **

**Comment by mutza974** [comment]
> For example: IRIAM, this application can detect the existence of Magisk anyway.
> I have passed the S66afetyNet test
> I used a random package name to hide Magisk Manager
> I have not installed Xposed, Lucky Patcher, no other root management application.
> Developer option has been turned off
> Also tried uninstalling Magisk Manager
> However, IRIAM will detect Magisk anyway.**
> ![screenshot_20190302-083346](https://user-images.githubusercontent.com/42766704/53675186-f69e2680-3cce-11e9-9efb-a9ec44e6d646.jpg)
> **

https://github.com/topjohnwu/Magisk/issues/1151#issuecomment-468886893

**Comment by mutza974** [comment]
![Uploading 117337177_3320335461390663_1175453008344512549_o.jpg…]()
