### ISSUE TITLE
Need a 'no wait' option for post-fs-data script of module

### ISSUE THREAD

**Issue by RikkaW** [topjohnwu/Magisk#1153]
For some specific purposes, like run a daemon program or wait for something such as zygote process, the post-fs-data script must not run synchronously.

In order to achieve this goal with pure sh, the script has to write like this:
```
if [[ $1 != "background" ]]; then
    sh $0 background &
    exit 0
fi

# do the real things
```
But this is not good and more importantly sh from users can never be though reliable, so a native program is required to do this.

So if Magisk can provider a 'no wait' option or simply post-fs-data-no-wait.sh to let post-fs-data scripts run like service scripts, things could be much easiser.

**Comment by topjohnwu** [comment]
Just simply write your script like this:
```
main_function() {
  # Do the real things
}

# Run the function in background shell
(main_function "$@")&
```
