### ISSUE TITLE
TWRP install of Magisk-v18.1(18100).zip breaks boot

### ISSUE THREAD

**Issue by nitramwin** [topjohnwu/Magisk#1156]
Following a failed boot after the install of 18000 and also 18100, I am providing the following details and files.

Device: OnePlus One (bacon) 
Android: Pie (9) security patch level 05 Feb 19 
ROM: [Potato Open Sauce Project](https://sourceforge.net/projects/posp/files/bacon/weeklies/potato_bacon-9-20190212.Baked-v2.1.WEEKLY.zip/download)
Recovery: TWRP 3.2.3-0

1. BEFORE TWRP MAGISK 18100 INSTALL >> Phone booting
[boot.emmc.win.zip](https://github.com/topjohnwu/Magisk/files/2922153/boot.emmc.win.zip)
[recovery.log](https://github.com/topjohnwu/Magisk/files/2922152/recovery.log)

2. AFTER TWRP MAGISK 18100 INSTALL >> Phone not booting
[boot.emmc.win.zip](https://github.com/topjohnwu/Magisk/files/2922155/boot.emmc.win.zip)
[recovery.log](https://github.com/topjohnwu/Magisk/files/2922154/recovery.log)

3. AFTER TWRP MAGISK 18100 REMOVED WITH UNINSTALLER >> Phone booting
[boot.emmc.win.zip](https://github.com/topjohnwu/Magisk/files/2922158/boot.emmc.win.zip)
[recovery.log](https://github.com/topjohnwu/Magisk/files/2922157/recovery.log)

**Comment by Didgeridoohan** [comment]
https://github.com/topjohnwu/Magisk/blob/master/README.MD#bug-reports
