### ISSUE TITLE
magisk_simple seems not to be working

### ISSUE THREAD

**Issue by eMPee584** [topjohnwu/Magisk#1158]
Things I see in `/data/adb/magisk_simple/system/` are not being shown overlaid in filesystem, f.e. replacing  bootanimation.zip seems not to work. Known condition? error on my part?

**Comment by Didgeridoohan** [comment]
Often, the boot animation starts to early even for magisk_simple. Nothing to do about it...

**Comment by eMPee584** [comment]
ok i understand that, but that's just one symptom.. also the files don't show up with app nor with ssh...
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Didgeridoohan** [comment]
What files are you trying to replace that requires Simple Mount?

**Comment by eMPee584** [comment]
wanted to place some custom binaries into xbin..


On March 2, 2019 7:50:17 PM GMT+01:00, Didgeridoohan <notifications@github.com> wrote:
>What files are you trying to replace that requires Simple Mount?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/topjohnwu/Magisk/issues/1158#issuecomment-468948807

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Didgeridoohan** [comment]
Simple Mount can only replace files that are already present, not mount new ones.

You need a proper module for that.

**Comment by eMPee584** [comment]
oh. is that documented somewhere? or rather, can it be changed?
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
