### ISSUE TITLE
Device support: Xiaomi Redmi Note 2

### ISSUE THREAD

**Issue by cheongzewei** [topjohnwu/Magisk#116]
Hi... Basic check integrity works, but cts profile match doesn't in safetynet check.

I'll be very thankful if you could help fix it.
[Boot.img](https://mega.nz/#!ph5VBC4Z!uJKd-nvSUruBMB3yMYRMrMu0xhMADWeswRobqCtrz5Q)

**Comment by DeicPro** [comment]
I have got that device and is problem a problem with Xiaomi... They don't follow Google rules and break CTS... Magisk can't do nothing with this...
