### ISSUE TITLE
No adjustment to the font

### ISSUE THREAD

**Issue by linar10** [topjohnwu/Magisk#1160]
There is no possibility to fit the right number of words. The strap is rolled up, it does not adjust to the number of words

![screenshot_20190302-203427__01](https://user-images.githubusercontent.com/829604/53686727-2c70f880-3d2b-11e9-8e70-18bd4a7e51c9.jpg)

**Comment by zertyuiop** [comment]
On the flash dialog, the buttons must be higher or the font must be smaller to accommodate two lines of text.
![screenshot_20190304-124802_magisk_manager](https://user-images.githubusercontent.com/4997630/53725290-c300ff00-3e7c-11e9-87d3-7551347a1cc7.png)

**Comment by topjohnwu** [comment]
Magisk Manager will go through major rewrite soon
