### ISSUE TITLE
Modules doesn't show in Core mode.

### ISSUE THREAD

**Issue by Senliast** [topjohnwu/Magisk#1161]
If I am getting a bootloop, I can enable core mode to uninstall problematic module. Earlier, the modules were shown in core mode, but since an magisk update not anymore. Is it only my problem or is it normal now? If yes, why? It doesn't make a sense, how should I then uninstall problematic module?

**Comment by bggold** [comment]
Boot with twrp and in the data/adb/modules folder delete the folder of that module.  Reboot and you should be good.

**Comment by Senliast** [comment]
Yes, but what if i have no access to /data from recovery? For example, on my old Galaxy S7, TWRP cannot decrypt /data because it doesnt support Samsung encryption.

**Comment by bggold** [comment]
Not sure what you can do.  So you cant even flash the magisk uninstaller?

**Comment by Senliast** [comment]
This is single way how I recovered my phone without to wipe data 😅 but then I must reinstall all my modules again and give all apps root again. Of course, it's a possibility but to uninstall the module per UI would be much comfortable and quickly. It's only my suggestion.

**Comment by bggold** [comment]
Try going back to a previous version of Magisk and see if it occurs still.  That way at least you have narrowed down the version it started with and report your findings with logs.

**Comment by vvb2060** [comment]
Make sure to install the latest Canary Build before reporting any bugs! DO NOT report bugs that is already fixed upstream.
