### ISSUE TITLE
Magisk Manager still crashes when accessing the hide list, even with the supposedly fixed version.

### ISSUE THREAD

**Issue by martyfender** [topjohnwu/Magisk#1162]
Even with the updated version, MM still crashes for many of us when trying to access the hide list. I posted logs in the Canary thread. The latest unofficial build also crashes, on 3 devices and the 2 devices I have Canary on.

Sorry, if you already have a fix in the works, you can close this issue.

They are all, Nextbook Ares 8A's, x86, Android 6.0.1 tablets.

Thanks

**Comment by topjohnwu** [comment]
@martyfender does it also happen on debug builds too?

**Comment by martyfender** [comment]
Yes, the two devices I have Canary on have the debug build.
