### ISSUE TITLE
Magisk v18.2-e8f35b02 - adb shell > su - No Grant Superuser Access Popup

### ISSUE THREAD

**Issue by 0pLuS0** [topjohnwu/Magisk#1163]
Hello,

I'm running a microG version of OxygenOS  5.1.7 Oreo 8.1.0 for OnePlus 5T and at first 18.1 would not appear in the App Drawer, as well as the Superuser Grant Access popup not appearing.

So I flashed Magisk v18.2-e8f35b02 and this one now appears in the App Drawer.

But when I run adb shell then su, there is no popup to grant superuser access, so this issue has been happening since either 18.0 or 18.1

I hope this can be fixed soon...

I've attached a log from inside the Log section of Magisk.

Thanks

[magisk_log_20190302_202439.log](https://github.com/topjohnwu/Magisk/files/2922832/magisk_log_20190302_202439.log)

**Comment by topjohnwu** [comment]
You might have to open Magisk Manager for once, and you have to add it to NOT be optimized for battery

**Comment by 0pLuS0** [comment]
@topjohnwu hi

I've always ran the Magisk Manager but for every version I've used Magisk, I've never had to not optimize it.

I'll give the Battery Optimization a shot and report back on this...

Thanks
