### ISSUE TITLE
Google Pay and MagiskHide - does not work

### ISSUE THREAD

**Issue by Lukaszek22** [topjohnwu/Magisk#1164]
GooglePay: latest version (2.82.231680166)
Magisk: v18.1
MagiskManager: v7.0.0

There is a problem with MagiskHide. GooglePay rejects credit card cause it says that I'm rooted.
On other apps, MagiskHide works great!
Of course, I rebooted and tried to reinstall GooglePay and MagiskManager. And I also "hide" my MagiskManager in the settings section.

**Comment by Didgeridoohan** [comment]
https://github.com/topjohnwu/Magisk/issues/1152

**Comment by Lukaszek22** [comment]
Of course, I fully understand but I was using Magisk Manager some time ago and it works perfectly with Google Pay(17.2) version of Magisk. And come on its not a “no name“ app but Google Pay, which I presume people use a lot.

**Comment by MichaelRolltideroll** [comment]
I have been trying to get the mask to work or update. No code
