### ISSUE TITLE
Magisk-debug.zip (e8f35b02) breaks boot

### ISSUE THREAD

**Issue by nitramwin** [topjohnwu/Magisk#1166]
Failed boot after flash of the latest Canary.

CONTEXT

OnePlus One bacon
Pie with security patch level 05 Feb 19
Potato Open Sauce Project 
TWRP 3.2.3-0

AFTER TWRP FLASH OF CANARY MAGISK >> Phone not booting past splash screen

- [recovery.log](https://github.com/topjohnwu/Magisk/files/2925797/recovery.log)
- [boot.emmc.win.zip](https://github.com/topjohnwu/Magisk/files/2925798/boot.emmc.win.zip)

**Comment by topjohnwu** [comment]
It is very likely an issue of your custom ROM, not Magisk
