### ISSUE TITLE
Magisk(18.1)/FrankeNDK (r3) build issue sqlite

### ISSUE THREAD

**Issue by almostssh** [topjohnwu/Magisk#1167]
I'm having issues building with FrankeNDK (latest release)

From a fresh Docker Ubuntu instance:
- Install Python3.7.2
- Download/extract FrankeNDK
- Download Android SDK tools (download platform-tools, build tools, etc)
- git clone Magisk per instructions
- set ANDROID_HOME to sdk path, ANDROID_NDK_HOME to FrankeNDK path
- python build.py -v -c config.prop binary

> [x86] Compile        : busybox <= volume_id.c
[x86] Compile        : busybox <= xfs.c
[armeabi-v7a] Executable     : busybox
[armeabi-v7a] SharedLibrary  : libsqlite.so
/root/dev/android/FrankeNDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ./obj/local/armeabi-v7a/objs/sqlite/stubs/sqlite3_stub.o:1:3: invalid character
/root/dev/android/FrankeNDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ./obj/local/armeabi-v7a/objs/sqlite/stubs/sqlite3_stub.o:1:3: syntax error, unexpected $end
/root/dev/android/FrankeNDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ./obj/local/armeabi-v7a/objs/sqlite/stubs/sqlite3_stub.o: not an object or archive
collect2: error: ld returned 1 exit status
make: *** [obj/local/armeabi-v7a/libsqlite.so] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/root/dev/android/Magisk/native'

**Comment by topjohnwu** [comment]
Are you messing with linker flags? The issue is that the linker is not running with `-flto`
