### ISSUE TITLE
Magisk Module Suggestion

### ISSUE THREAD

**Issue by Prakyy** [topjohnwu/Magisk#1168]
I seldom see modules that don't concern my phone for example if I have a OnePlus 6, why would I want to see mi a1 modules?

BTW I love your work with magisk. <3

**Comment by Jeepeo** [comment]
> I seldom see modules that don't concern my phone for example if I have a OnePlus 6, why would I want to see mi a1 modules?
> 
> BTW I love your work with magisk. <3

Why should you look it , just ignore it , such a human being

**Comment by topjohnwu** [comment]
@Prakyy doing a device filter is impractical, we don't have infinite resources to list all possible Android devices out there (we are not iPhone :) )
