### ISSUE TITLE
Icon on AndroidTV Oreo for Magisk Manager

### ISSUE THREAD

**Issue by bubuleur** [topjohnwu/Magisk#1169]
Hello,
I use your application on my nvidia shield tv with AndroidTv Oreo
but when I install your application I do not have a logo to access it
it is possible to put a logo for easy access?
I made a logo
![magisk_manager_logo](https://user-images.githubusercontent.com/21688137/53789293-635e2e80-3f24-11e9-8858-22d579c47a2c.png)
and I know who there are 2 applications that allow to put a logo on Androidtv
there is apk2tv and APK Icon Editor
Thanking you

**Comment by bubuleur** [comment]
Thank you the logo suits you?

**Comment by bubuleur** [comment]
Up please

**Comment by bubuleur** [comment]
Hello,
I would like to test to see if the logo is fine but I can not recompile with your apk
Thanking you

**Comment by bubuleur** [comment]
Hello topjohnwu I just saw that you have updated but I just saw that my icon for androidtv was not put
Waiting for a response
Thanking you

**Comment by topjohnwu** [comment]
Sorry, but I don't have an Android TV device to test, so I won't focus my time on the icon for now

**Comment by bubuleur** [comment]
Ah thin is annoying I would like so much to have an icon that my nvidia shield tv tell me how to do I can help you
While waiting for your reply

**Comment by bubuleur** [comment]
Up please
it's just to put a shortcut on androidtv how I'm told you're helping
Thank you

**Comment by bubuleur** [comment]
Please I made the logo
I can do it with apk2tv and APK Icon Editor but it does not work

**Comment by NeonUniverse** [comment]
Stop spamming, John has other plans other than Android TV. Kthx

**Comment by bubuleur** [comment]
but I would like to help that
