### ISSUE TITLE
小米9安装Magisk高版本，apk读取不到

### ISSUE THREAD

**Issue by Coinswang** [topjohnwu/Magisk#1172]
安装Magiskv17.3+低版本apk可以正常读取到和获取root权限，如果安装18.0或者18.1，在低版本apk能检测到已安装18.1，但是提示升级高版本apk，安装最新版apk之后又提示未安装Magisk。

**Comment by topjohnwu** [comment]
請測試最新的 canary build，已經修復好一陣子了

**Comment by kana112233** [comment]
> 請測試最新的 canary build，已經修復好一陣子了

这个是什么意思？
