### ISSUE TITLE
為什麼我的18.1掛載不了system分區的讀寫權限？

### ISSUE THREAD

**Issue by Aditems** [topjohnwu/Magisk#1173]
rt

**Comment by Aditems** [comment]
現在每次嘗試獲取system的讀寫權限都會大量佔用內存導致卡死重啟，希望能解決一下

**Comment by topjohnwu** [comment]
這個怎麼想都跟 Magisk 毫無關聯，Magisk 僅提供 root，並不會影響 Linux kernel 運作的方式
