### ISSUE TITLE
Magisk 17.3 and up don't work with Lucky Patcher

### ISSUE THREAD

**Issue by leopard20** [topjohnwu/Magisk#1178]
The root access dialog doesn't appear at all. Magisk v17.1 was the last one I tested that works fine with Lucky Patcher. Didn't test 17.2.

**Comment by Didgeridoohan** [comment]
Good.

**Comment by topjohnwu** [comment]
It should not be an issue on my side, if all root apps except Lucky Patcher doesn't, it is obvious which one is to blame here

**Comment by leopard20** [comment]
Not that I care about this. Just wanted to report it, see if you cared. I use v17.1 anyway.

**Comment by jonniex7** [comment]
Same issue on latest

**Comment by Didgeridoohan** [comment]
That is excellent news. Thank you for reporting.

**Comment by leopard20** [comment]
@Didgeridoohan Do you think you're a fucking smart ass?
