### ISSUE TITLE
PS4 Remote Play 2.8.0 can detect root with magisk hide

### ISSUE THREAD

**Issue by RYU81** [topjohnwu/Magisk#1180]
I have Magisk version 18.1 even with hide PS4 Remote Play 2.8.0 get error 88001003.

**Comment by eXhumer** [comment]
#1152

**Comment by dongzhaosheng73** [comment]
> 我有Magisk版本18.1甚至隐藏PS4 Remote Play 2.8.0得到错误88001003。

最后如何解决呢？我也遇到同样的问题
