### ISSUE TITLE
"Magisk is not installed" error but root access works

### ISSUE THREAD

**Issue by eXhumer** [topjohnwu/Magisk#1181]
Device: OnePlus 6T
Magisk Version: 18112 (and below)
Magisk Manager Version: 193
OS: Android 9 (OOS 9.0.12)
LOG: https://drive.google.com/open?id=1gGw3Fiw_8DAjU9SR_hkjBWm5FZgtMB33

**Comment by eXhumer** [comment]
LOG: https://drive.google.com/file/d/1IbnPAifEyqd2fkhg6qgZwY4bIikgjOcq/view?usp=sharing

**Comment by Djtrip83** [comment]
I experienced this as well today. Did you install Magisk Manager first and then Magisk? I did that, got the same error message, and then I ran a clean uninstall and installed Magisk via temporary TWRP. Then I installed Magisk Manager and everything showed as installed.

**Comment by eXhumer** [comment]
No. It started happening after v18 update AFAIK. I fully wiped my phone, clean installed OS using MSMDownloadTool, flashed TWRP and then flashed Magisk Zip. It still shows this error. Root access works, but I don't think the Magisk modules work.

**Comment by Xalaxis** [comment]
Same problem.  Oneplus 6.  Magisk 18118.  MM ecf3d303

**Comment by Xalaxis** [comment]
@eXhumer 

topjohnwu has now [released a new build](https://forum.xda-developers.com/showpost.php?p=79145041&postcount=1083) which fixes all the problems I've been having.

The exact release is https://github.com/topjohnwu/magisk_files/blob/a5296f5a4becc4d753328c248c45c13879a45b13/canary_builds/magisk-release.zip

**Comment by eXhumer** [comment]
> 
> 
> @eXhumer
> 
> topjohnwu has now [released a new build](https://forum.xda-developers.com/showpost.php?p=79145041&postcount=1083) which fixes all the problems I've been having.
> 
> The exact release is https://github.com/topjohnwu/magisk_files/blob/a5296f5a4becc4d753328c248c45c13879a45b13/canary_builds/magisk-release.zip

That fixed the issue. Thanks.
