### ISSUE TITLE
redmagic Mars for system_root

### ISSUE THREAD

**Issue by scarlet-glass** [topjohnwu/Magisk#1184]
I released a submission that addresses the root of the system_root partition. After testing, redmagic Mars Android 9.0 implements root.
https://github.com/topjohnwu/Magisk/pull/1183/commits/a796533b7bc18db2d9dd1ead2da2d44352659337

**Comment by scarlet-glass** [comment]
https://github.com/topjohnwu/Magisk/pull/1183/commits/a796533b7bc18db2d9dd1ead2da2d44352659337

**Comment by scarlet-glass** [comment]
I released a submission that addresses the root of the system_root partition. After testing, redmagic Mars Android 9.0 implements root.
https://github.com/topjohnwu/Magisk/commit/a796533b7bc18db2d9dd1ead2da2d44352659337

**Comment by topjohnwu** [comment]
This is already done ages ago...
e72c6685edf81706617a3444575c4500b9b8fe6c

**Comment by scarlet-glass** [comment]
I brushed your build version and it didn't work in redmagic. After the changes I submitted are brushed in, root can be achieved.

**Comment by topjohnwu** [comment]
可以用中文沒關係。
你所做得事情跟我所做的事情是一模一樣的。
你可以把使用 canary build 的 recovery log 還有 patch 完的 boot image 傳給我嗎？

**Comment by scarlet-glass** [comment]
链接：https://pan.baidu.com/s/1Yyu0o4XOlAFRBtVZiY86aA 
提取码：vfhv

**Comment by scarlet-glass** [comment]
我使用我刚刚修改的就可以实现root，用你 canary build里面的刷进去就无法root

**Comment by scarlet-glass** [comment]
我的设备一台是解锁bootloader的，一台是未解锁bootloader的。
解锁的设备用canary build里面的刷进去可以root，未解锁bootloader无法root，但是使用我修改的方法可以实现不解锁bootloader就可以root

**Comment by scarlet-glass** [comment]
@topjohnwu

**Comment by vvb2060** [comment]
第一，这不是你修改的，而是我修改的。
第二，你提交的pr还是我第一版的内容，它必须配合magiskboot的修改一起，否则根本走不到分支3和4。用我的第二版pr才能仅修改脚本。
第三，不要用百度云，下载文件必须用手机号注册百度账号并且安装百度云客户端。应该打包后直接上传GitHub。
第四，我从努比亚官网下载了[红魔Mars系统包](http://ui.nubia.cn/rom/detail/61)，这是提取的原始boot镜像： [boot.zip](https://github.com/topjohnwu/Magisk/files/2948188/boot.zip) 。应该没什么问题。
第五，不解锁bootloader是什么奇怪的操作
第六，我看了你上传的boot镜像，用的版本是18112，可能是ramdisk被压缩的关系，用最新的18114再试。

**Comment by scarlet-glass** [comment]
第一，我没有说这个代码就是我的，我只是拿这个给作者做个解释，如果有侵权，抱歉哈
第五，不解锁bootloader，使用拼包并签名就可以完成root。用大佬的最新构建，在没有解锁BL的情况下是无法识别system_root的，如果解锁了，就会自动识别system_root，我已经测试过了。
