### ISSUE TITLE
Why are "Install" buttons shown in Magisk Manager home screen always?

### ISSUE THREAD

**Issue by cyfrost** [topjohnwu/Magisk#1186]
This is more of a UX issue than anything else.

When Magisk root processes and everything else are up and running, opening up the Magisk Manager app will show huge "Install" buttons on it's home screen. What purpose do they serve there? Magisk is already installed, root is detected fine, Magisk Manager is installed, so why are they shown?

![image](https://user-images.githubusercontent.com/12471103/54023262-886bcf00-41ba-11e9-82d6-b9ac6dab4e4e.png)

If those buttons appear when something is wrong (Magisk root processes are not detected etc), I'd gladly appreciate it's presence indicating something's wrong.
 
As such, Magisk Manager notifies of any new updates available, So I can't think of anything else why they're there. Heck, I've had my younger brother ask me this today and I totally gave into the bewilderment.

If you'd like, I can send a PR with changes that make those Install buttons become visible ONLY IF root is either not detected/installed.

I do not mean to come across as rude, and sorry if it sounded like it, but I just want to make your app better (for me and anyone else).

**Comment by Didgeridoohan** [comment]
UX is currently a work in progress. It will be improved, question is just when.

Take a look here for an idea on what might be in the works:
https://twitter.com/_knightrise/status/1094807861840904192?s=09

**Comment by topjohnwu** [comment]
The install button is there so people can easily reinstall/downgrade/switch channels, I just simply didn't bother to change the text from "install" to "reinstall" (as it will involve tons of people for translations)
