### ISSUE TITLE
Magisk Hide 白屏

### ISSUE THREAD

**Issue by Etsuya233** [topjohnwu/Magisk#1188]
设备：Redmi Note 5 Pro
系统：Pixel Experience Pie
Magisk版本：18.1

对任何一个使用Magisk Hide，打开会白屏，多任务没有该程序。
挺久前就这样的了emm
[magisk_log_20190308_213921.log](https://github.com/topjohnwu/Magisk/files/2946013/magisk_log_20190308_213921.log)

**Comment by Etsuya233** [comment]
这些是我安装的模块
![screenshot_20190308-214746](https://user-images.githubusercontent.com/42312804/54032202-ebc22500-41eb-11e9-9a98-99d411c88c18.png)
![screenshot_20190308-214755](https://user-images.githubusercontent.com/42312804/54032229-fb416e00-41eb-11e9-843f-0e842d267f7e.png)
![screenshot_20190308-214758](https://user-images.githubusercontent.com/42312804/54032243-04cad600-41ec-11e9-9a25-f21b5d9e93b3.png)

**Comment by topjohnwu** [comment]
回報問題請用 canary build，已經修復了
