### ISSUE TITLE
Not All System Apps Shown - Version 18.1 Magisk Hide - Nougat 7.1.2 Not Compatible?

### ISSUE THREAD

**Issue by bugnot** [topjohnwu/Magisk#1189]
Testing on 7.1.2 Nougat by Lineage OS.
New version 18.1 surprisingly shows a handful of system apps.
While the previous version 18.0 does not have such flaw and showed all system apps.

Are we not supposed to not use 18.1 on older system such as Nougat?

**Comment by topjohnwu** [comment]
Fixed in latest canary
