### ISSUE TITLE
Copying symlinks still fails in v11.5

### ISSUE THREAD

**Issue by laggardkernel** [topjohnwu/Magisk#119]
There is a syntax error in the travel function of magic_mask.sh. [Line 131](https://github.com/topjohnwu/Magisk/blob/master/scripts/magic_mask.sh#L131)
``` shell
          cp -afc "$ITEM" $"DUMMDIR/$1/$ITEM"
```
I pulled a commit some time ago for v11.1. Maybe you don't see it. Pull request #97 .

**Comment by tonymanou** [comment]
There is a conflict in your pull request due to changes in recent commits, you should update it ASAP!
(Either rebase your work on master and force-push the result to your ```patch-1``` branch in order to update your PR, or add a new commit that fixes the conflict)

**Comment by laggardkernel** [comment]
Fixed by [commit 624b764](https://github.com/topjohnwu/Magisk/commit/624b7616d082feced71bff0474c64c1b4afd5cc0)
