### ISSUE TITLE
OTA Installation doesn't work

### ISSUE THREAD

**Issue by RYU81** [topjohnwu/Magisk#1194]
I don't modified system and vendor so after this step 
"restore Magisk Manager → Uninstall → Restore Images"
still show me message when doing OTA about my system is modified.

OS: 9.0
Phone:Note 9
model: SM-N960F
Magisk 18.1
Magisk Manager 7

**Comment by KaMyKaSii** [comment]
Did you make the first installation of Magisk through TWRP or Odin? I believe that the "Restore images" function only works as expected when installed through TWRP (because the installer first creates the necessary backup)

**Comment by RYU81** [comment]
btw i don't remember it  😂 but is there way to fix it?

**Comment by KaMyKaSii** [comment]
@RYU81 If you are sure you have not done anything that has modified /system, I believe you only need to install the stock boot.img through Odin

**Comment by RYU81** [comment]
now i remember it I'm sure i install magisk through TWRP

**Comment by topjohnwu** [comment]
This has nothing to do with Magisk. Magisk will restore whatever it overwrites, it cannot promise any other stuff.
