### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by keyute** [topjohnwu/Magisk#1195]
Running latest canary 18115 on pixel 3 xl march security patch. Performance has slowed down dramatically after installing it. Didn't happen at last canary version

**Comment by AuroraWright** [comment]
https://forum.xda-developers.com/showpost.php?p=79074070&postcount=930 more details

**Comment by topjohnwu** [comment]
I'm working on it, please stay tuned

**Comment by keyute** [comment]
> I'm working on it, please stay tuned

my phone keeps crashing and boots into recovery mode "android system not loaded"

here is the log (magisk core only enabled)
[magisk_log_20190310_113344.log](https://github.com/topjohnwu/Magisk/files/2949046/magisk_log_20190310_113344.log)
