### ISSUE TITLE
Struck at bootlogo in KitKat

### ISSUE THREAD

**Issue by HemanthJabalpuri** [topjohnwu/Magisk#1196]
After flashing Magisk v18115 and older canary results struck at boot logo....
Magisk Manager is unable to download zip or apk
Logs are attached
[Magisk_logs.zip](https://github.com/topjohnwu/Magisk/files/2949059/Magisk_logs.zip)
Older version logs are attached at https://forum.xda-developers.com/showpost.php?p=78989988&postcount=828 and https://github.com/topjohnwu/Magisk/issues/1049

**Comment by HTAEDFOLEGNA** [comment]
UPGRADE!!!

**Comment by HemanthJabalpuri** [comment]
> UPGRADE!!!

Same result after upgrade too...

**Comment by kill0rz** [comment]
Same problem here:

OnePlus 3
Android 8.1 (RR)
Trying to flash 18122 -> stuck at boot screen
APK 200 works fine, 18100 is installed an works fine

**Comment by HemanthJabalpuri** [comment]
> Same problem here:
> 
> OnePlus 3
> Android 8.1 (RR)
> Trying to flash 18122 -> stuck at boot screen
> APK 200 works fine, 18100 is installed an works fine

Any boot struck is because of magiskinit that is placed in ramdisk of boot.img.....
All versions of apps should work as usual....
(In my thinking)

**Comment by kill0rz** [comment]
Thanks for your reply! 
Is there any fix for the Boot struckle?

**Comment by HemanthJabalpuri** [comment]
> Thanks for your reply!
> Is there any fix for the Boot struckle?

We have to wait for topjohnwu's reply for fix

**Comment by HemanthJabalpuri** [comment]
closing because 1256 is active
