### ISSUE TITLE
Magisk Downloads need adjustment

### ISSUE THREAD

**Issue by Prakyy** [topjohnwu/Magisk#1197]
So you guys switched to saving files in the Downloads folder, can we get an option to save the Downloads to wherever we want? My movie files are in Downloads but the modules are also in Downloads and I have to scroll a while. Pls don't reject this really need this. Unless it's too difficult to code in that option. I will understand.

Thx.

**Comment by Prakyy** [comment]
If you didn't understand, I meant I should be able to change default download location to a folder called 'obesity' in my phone storage if I want to.

**Comment by DenyDarko** [comment]
Oh Cmon, magisk modules are on a strict diet before getting accepted.

**Comment by Prakyy** [comment]
Lol but you do understand what I mean right?

**Comment by topjohnwu** [comment]
To implement this, I have to create a file explorer UI to let you choose where to put your files, which is not trivial and not on my list of interest any time soon.

**Comment by Prakyy** [comment]
Sir you don't need to create UI, just ask for location during magisk install

**Comment by Prakyy** [comment]
Or we could just type in terminal something like 'magisk_def_loc emulated/0/downloads/obesity'

**Comment by Prakyy** [comment]
Sir I have OCD please I don't want to give crazy.

**Comment by neekless** [comment]
Just move the damn file yourself
