### ISSUE TITLE
MagiskHide and Google Pay

### ISSUE THREAD

**Issue by Slats2** [topjohnwu/Magisk#1202]
Hi, Google Pay isn't working again after updating to 18116 using MagiskHide. Really annoying, no offense. Is there anyway to fix this as I use this everyday.

**Comment by eXhumer** [comment]
#1152

**Comment by martyfender** [comment]
There is now an xda thread dedicated to this problem:

[https://forum.xda-developers.com/apps/magisk/discussion-google-pay-magisk-discussion-t3906703](url)
