### ISSUE TITLE
Humble "advanced feature" request: allow configuring and injecting simple binary-based "android-style" init daemons/services 

### ISSUE THREAD

**Issue by tonsimple** [topjohnwu/Magisk#1204]
As per https://github.com/topjohnwu/Magisk/blob/master/docs/details.md magisk already injects a lot of custom init.rc stuff into android boot process.

So, in principle, it should be possible to inject inconspicuously named custom service starting some kind of not-too-intricate binary daemon

something like 
c_samserv_init.rc

containing stuff like 

on property:cmserv.enable=1
 start cmserv12

service cmserv12 /path/to/binary -some -command -line params 
user inet_raw
group inet_raw
disabled  

This would allow one to 

1) configure simple (and not-so-simple) android init daemons that can restart automatically without any additional housekeeping shenanigans 

2) start them as normal android init services or using special prop triggers (as in example above) that can be initiated, for example, using Magisk's own script-running infrastructure (if the daemon is not particularly needed early on)

P.S.: I realize that I can already, say, edit Magisk's init.magisk.rc but I really don't feel like tampering with that of all things, and it would be nice to have a facility to inject simple custom android service daemons in an organized and "official" manner

**Comment by topjohnwu** [comment]
For starting init.rc services, you always have to patch the boot image. It is not possible to do it with modules.
If you are going to patch ramdisk anyways, there is no point in adding new "Magisk" support for it

**Comment by tonsimple** [comment]
Please pardon the perhaps foolish question, but if current customized init process can inject init.magisk.rc, what prevents it from, say, checking if a particular path like say "/sbin/.core/img/custominit/ " exists and injecting   *.rc files located there if it does?
