### ISSUE TITLE
Safetynet...

### ISSUE THREAD

**Issue by HTAEDFOLEGNA** [topjohnwu/Magisk#1205]
Safetynet still says not valid response

**Comment by Didgeridoohan** [comment]
That's pretty much certain to be an issue on your side. And without any other info than "it doesn't work", there's absolutely nothing that can be done.

Suggestion: close this issue (so @topjohnwu doesn't have to), take a look [here](https://www.didgeridoohan.com/magisk/MagiskHide#hn_The_response_is_invalid), and if you still can't figure things out go to xda and post in the general support thread (with plenty of [details and preferably logs](https://www.didgeridoohan.com/magisk/MagiskHelp)).

**Comment by HTAEDFOLEGNA** [comment]
@Didgeridoohan sorry man it was on my end. I don't know what I did to maor my phone do what it did. But I did a clean flash of soldier9312 after formatting my s9 with twrp and magisk is fully functional again
