### ISSUE TITLE
Security Error: Unauthorised Software From Magisk Manager

### ISSUE THREAD

**Issue by BinariGuy** [topjohnwu/Magisk#1207]
My device doesn't have a Custom Recovery, so I opted to install magisk via Magisk Manager using Kingroot.
It was going very well but this appeared:
**- Detecting target image**
**- Device platform: armeabi-v7a**
**- Downloading zip**
**... 0%
! Unable to check signature
! Installation failed**

My device is this:
+ M4 SS4452
+ 5.1.1 Lollipop
+ armv7
+ Kernel ver 3.10.49
+ 1GB RAM

Pls help! Thanks!

**Comment by HemanthJabalpuri** [comment]
@BinariGuy can you please help me messaging me at https://forum.xda-developers.com/member.php?u=8953766

**Comment by topjohnwu** [comment]
@BinariGuy please provide Magisk Manager logcat while installing, using the debug canary build

**Comment by BinariGuy** [comment]
This one?
https://github.com/topjohnwu/magisk_files/blob/master/canary_builds/app-debug.apk

**Comment by topjohnwu** [comment]
Yes, please reply with logcat reports

**Comment by BinariGuy** [comment]
@topjohnwu I had a problem while installing:
_Security Error: This phobnes has been flashed  with unauthorised software & is locked._

**Comment by topjohnwu** [comment]
Just install the APK and report logcat! This has nothing to do with Magisk, just plain old app logcats. I will close the issue for now, I cannot help you without even the simplest logcat report.
