### ISSUE TITLE
Excessive magiskhide proc monitor before crashing 

### ISSUE THREAD

**Issue by keyute** [topjohnwu/Magisk#1210]
Does not happen when during first install of app. Happens AFTER restart phone . App then becomes unusable with random vibrations time to time 

[magisk_log_20190312_204511.log](https://github.com/topjohnwu/Magisk/files/2956932/magisk_log_20190312_204511.log)

**Comment by topjohnwu** [comment]
Sorry, but I cannot understand what you want to report.
