### ISSUE TITLE
Magisk not able to be applied in Android Q

### ISSUE THREAD

**Issue by Ralozey** [topjohnwu/Magisk#1211]
I just upgraded to Android Q DevPrev 1
and noticed that neither patched_boot (I tried patching the stock Android Q image for my Pixel 2 XL and when booting after applying via fastboot it doesn't boot anymore)
nor my ususal method of patching via twrp work.
I suppose this is related to Android Q having a completely different boot partition system but I thought I'd give you a heads up (Also this is probably a story/epic rather than an issue but 🤷‍♂️)

**Comment by plavirudar** [comment]
Can also confirm that patching by TWRP zip installing `Magisk-v18.1.zip` fails with Error 1 on Pixel XL.

**Comment by JRoy** [comment]
Associated Twitter Threads from John:

[Android Q Issues](https://mobile.twitter.com/topjohnwu/status/1105947979679191041)

[Magisk works on Pixel 1&2](https://mobile.twitter.com/topjohnwu/status/1106069688121847809)

**Comment by topjohnwu** [comment]
Check the latest canay, non logical partition devices should work just fine now

**Comment by AndroidDeveloperLB** [comment]
@topjohnwu It worked fine for me on Q beta 1, but for some reason not on beta 2.
Can you please help?
