### ISSUE TITLE
Google Pay Issues as of Recent Google Pay / Google Play Services Updates

### ISSUE THREAD

**Issue by ChristopherHammond13** [topjohnwu/Magisk#1213]
Symptoms:
- SafetyNet passes
- Google Pay allows setup / adding of cards
- Google Play shows the device as certified
- When paying, the error "You can no longer pay in shops with Google Pay" appears on the screen and the transaction doesn't go through
- Actual cards work (so it's not a bank issue)
- Issues faced with multiple cards from different companies

There is an XDA thread about this: https://forum.xda-developers.com/apps/magisk/discussion-google-pay-magisk-discussion-t3906703

Device: OnePlus 6, latest OxygenOS, a couple of Magisk modules installed but otherwise vanilla (no Xposed, etc.)
Versions:
- Google Pay 2.84.237487748
- Google Play Services 15.0.90 (100400-231259764)

My Google account shows the following notice in Chrome when I look for Google Pay help online:
![image](https://user-images.githubusercontent.com/295396/54364735-64e6cf80-4665-11e9-9f77-69ac6ec5989e.png)

Thanks for any help you can provide! If I can gather any information to help please do let me know :)

**Comment by microtechton** [comment]
#1152

**Comment by microtechton** [comment]
#1152
