### ISSUE TITLE
Unable to get root access despite installation of magisk manager

### ISSUE THREAD

**Issue by bheeshmpita** [topjohnwu/Magisk#1214]
The magisk manager despite being successfully installed through zip file flashing in recovery mode, my device doesn't get rooted, even though the magisk manager app gets installed on my device. I am using a custom ROM on my device 
I'm sharing the related info below
![photo6](https://user-images.githubusercontent.com/48560944/54371166-f292e100-469e-11e9-939f-bd561929cdc0.jpg)
![photo (3)](https://user-images.githubusercontent.com/48560944/54371263-19511780-469f-11e9-93d7-2c288179e6d2.jpg)
[magisk_log_20190314_213934.log](https://github.com/topjohnwu/Magisk/files/2967379/magisk_log_20190314_213934.log)
please note that I am an amateur in the rooting process, so while providing help please use easy to understand terminology 
Any kind of help would be appreciated

**Comment by topjohnwu** [comment]
Any report should be using canary builds, please read the README before reporting
