### ISSUE TITLE
Unable to get root access despite installation of magisk manager

### ISSUE THREAD

**Issue by bheeshmpita** [topjohnwu/Magisk#1215]
The magisk manager despite being successfully installed through zip file flashing in recovery mode, my device doesn't get rooted, even though the magisk manager app gets installed on my device. I am using a custom ROM on my device
I'm sharing the related info below
![photo607](https://user-images.githubusercontent.com/48560944/54408625-877df480-4708-11e9-85bd-a23dc2f4bf9e.jpg)
![photo (3)](https://user-images.githubusercontent.com/48560944/54408634-8d73d580-4708-11e9-8653-8bc6d74279c1.jpg)
[magisk_log_20190315_090837.log](https://github.com/topjohnwu/Magisk/files/2969435/magisk_log_20190315_090837.log)

please note that I am an amateur in the rooting process, so while providing help please use easy to understand terminology
Any kind of help would be appreciated
**for @topjohnwu , john this isn't any bug report, I just want to successfully root my device with magisk**

**Comment by Didgeridoohan** [comment]
If it's not a big report it does not belong here. There's a whole forum for getting help over at XDA. Close this issue and go there instead.

**Comment by bheeshmpita** [comment]
oh thanks, **Didgeridoohan** for guiding me, can you please link me where exactly should I post on xda, as I above said that I am an amateur in all these stuff. Afterwards I would close this issue

**Comment by Didgeridoohan** [comment]
Well, I noticed that you've already done it, even before creating this issue... So, now you can close.

**Comment by bheeshmpita** [comment]
so you mean to say I did that at right place? Please can you help me more on this issue (at xda). Anyway thanks to you.

**Comment by Didgeridoohan** [comment]
Yes, that we the right place. Close this now so topjohnwu doesn't have to.
