### ISSUE TITLE
No "Install" button - Samsung Galaxy S8

### ISSUE THREAD

**Issue by kfiz** [topjohnwu/Magisk#1216]
Hi,

I would like to patch the boot.img of my device, but I can't seem to find the install button.
I've attached a screenshot. Weirdly enough sometimes when I'm offline an uninstall button appears, that consistently disappears when I get back online.
Any suggestions?

Best

D

![Screenshot_20190315-204514_Magisk Manager](https://user-images.githubusercontent.com/5100646/54416888-f8b9a980-4700-11e9-901e-0cff81a82994.jpg)

**Comment by Didgeridoohan** [comment]
Why do people think that the GitHub issue tracker is a support forum? Unless you have a bug to report, take it to xda instead.

**Comment by kfiz** [comment]
Thanks for the quick and friendly reply.

**Comment by Didgeridoohan** [comment]
It wasn't meant to be either friendly or hostile, merely informative.

The issue tracker is meant for the developer to keep track of issues and bugs with the software. If it gets swamped with stuff that is nothing but support requests the workload for the developer increases quite a lot and actual bugs risk disappearing in the clutter.

So, again, please close this issue (to keep some of that workload I mentioned away from topjohnwu) and post on xda instead.

**Comment by kfiz** [comment]
Will do. But don't forget that a bug in the gui is still considered a bug in a Lot of code repositories. + I've read the developers hints wrt. missing Buttons and how they relate to a working internet connection. Since my issues occur despite having an inet connection I thought this was the right place.

**Comment by Didgeridoohan** [comment]
I don't see any bug in your description. You say that there's no install button, but in your screenshot I see a big button with the word "Installier" (which I'm going to assume means "Install" in your language). Have you tried clicking it?

**Comment by kfiz** [comment]
I will stop discussing here with you, since I think you're attitude is, contrary to what you sugessted earlier, hostile and arrogant. I closed the issue, so I'd say there is nothing for you to do here.

**Comment by Didgeridoohan** [comment]
I have a tendency to be a bit too ironic/sarcastic than what is good for the written media. Sorry about that.

Good luck.
