### ISSUE TITLE
rootfs file selabels commit breaks S9+.

### ISSUE THREAD

**Issue by ianmacd** [topjohnwu/Magisk#1218]
My Samsung s9+ doesn't get past the bootloader screen after applying and building with a1b5185ecbc41a0a87b7c62df623809b5510ba84.

**Comment by AuroraWright** [comment]
Also breaks Pixel 2 XL on Sultan kernel. Stock kernel works.

**Comment by topjohnwu** [comment]
Can anyone provide last dmesg for me to know what causes things to break down? (Bootloop, boot into recovery and dump logs)
@AuroraWright for Pixels I think it is in `/sys/fs/pstore/console-ramoops`, @ianmacd I'm not sure about Samsung devices

**Comment by AuroraWright** [comment]
Tried doing that (made it crash, immediately held volume down and went to recovery) but /sys/fs/pstore/ is empty

**Comment by AuroraWright** [comment]
For what it's worth it seems it's the same thing which causes Huawei devices to crash, aka https://github.com/topjohnwu/Magisk/blob/8893cbd64afe6df17a29a08d480b93f49ad9c30f/native/jni/core/init.cpp#L448

**Comment by martyfender** [comment]
On my 2 Nextbook Ares 8A, x86, Android 6.0.1 tablets, build 18119 installs fine. on one device it booted right up, on the second I had a first boot only, on boot animation bootloop. As usual, a forced shutdown, followed by a cold boot and it booted fine and appears to work fine after that.

**Comment by topjohnwu** [comment]
Fixed in 957feca626e670710eb598742d385a95d0d303cd
