### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by iVirusPro** [topjohnwu/Magisk#1220]
Samsung Galaxy Trend GT-S7392
From android system recovery (not TWRP)

```
E:failed to verify whole-file signature
E:failed to verify whole-file signature
E:signature verification failed
```

**Comment by Displax** [comment]
You can't flash Magisk via stock recovery. It accept only images signed by Samsung.

**Comment by iVirusPro** [comment]
I see. Thanks.
