### ISSUE TITLE
Always in Magisk core mode. MagiskHide is not active.

### ISSUE THREAD

**Issue by VasyaHH** [topjohnwu/Magisk#1221]
Magisk core mode always active. 
If I turn off magisk core in settings and reboot device, it turns on again. It happens on all latest build.
With magisk hide option the same thing. It always turned off. If I activate magisk hide and restart magisk manager app it reverts back to off state.
Samsung galaxy J7.
Same issues on the latest build 18121
```
--------- beginning of main
--------- beginning of system
03-18 17:17:48.613  2587  2587 I Magisk  : Magisk v18.2-945f8810(18121) daemon started
03-18 17:17:48.613  2587  2587 I Magisk  : * Device API level: 26
03-18 17:17:48.630  2587  2588 D Magisk  : resetprop: getprop [ro.crypto.state]: [unencrypted]
03-18 17:17:48.665  2587  2588 I Magisk  : ** post-fs-data mode running
03-18 17:17:48.668  2587  2588 I Magisk  : * Initializing Magisk environment
03-18 17:17:48.672  2587  2588 I Magisk  : * Mounting mirrors
03-18 17:17:48.673  2587  2588 I Magisk  : mount: /sbin/.magisk/mirror/system <- /dev/block/platform/13540000.dwmmc0/by-name/SYSTEM
03-18 17:17:48.673  2587  2588 I Magisk  : mount: /sbin/.magisk/mirror/data <- /dev/block/platform/13540000.dwmmc0/by-name/USERDATA
03-18 17:17:48.674  2587  2588 I Magisk  : link: /sbin/.magisk/mirror/vendor <- /sbin/.magisk/mirror/system/vendor
03-18 17:17:48.674  2587  2588 I Magisk  : * Setting up internal busybox
03-18 17:17:48.689  2587  2588 I Magisk  : * Running post-fs-data.d scripts
03-18 17:17:49.562  2587  2741 I Magisk  : ** late_start service mode running
03-18 17:17:49.563  2587  2741 I Magisk  : * Running service.d scripts
03-18 17:18:24.127  2587  5708 D Magisk  : su: request from pid=[5703], client=[8]
03-18 17:18:24.127  2587  5708 D Magisk  : su: request from uid=[10239] (#1)
03-18 17:18:24.128  2587  5708 D Magisk  : magiskdb: query su_fingerprint=[0]
03-18 17:18:24.131  2587  5708 D Magisk  : su: waiting child pid=[5709]
03-18 17:18:24.131  5709  5709 D Magisk  : su: fork handler
03-18 17:18:24.132  5709  5709 D Magisk  : su: use global namespace
03-18 17:18:31.954  2587  5939 D Magisk  : su: request from pid=[5937], client=[9]
03-18 17:18:31.955  2587  5939 D Magisk  : su: request from uid=[10242] (#1)
03-18 17:18:31.956  2587  5939 D Magisk  : magiskdb: query su_fingerprint=[0]
03-18 17:18:31.958  2587  5939 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
03-18 17:18:31.959  2587  5939 D Magisk  : su: waiting child pid=[5940]
03-18 17:18:31.959  5940  5940 D Magisk  : su: fork handler
03-18 17:18:31.961  5940  5940 D Magisk  : su: use namespace of pid=[5937]
03-18 17:18:31.989  2587  5939 D Magisk  : su: return code=[0]
03-18 17:18:32.096  2587  5969 D Magisk  : su: request from pid=[5961], client=[7]
03-18 17:18:32.096  2587  5969 D Magisk  : su: request from uid=[10242] (#2)
03-18 17:18:32.097  2587  5969 D Magisk  : su: waiting child pid=[5971]
03-18 17:18:32.097  5971  5971 D Magisk  : su: fork handler
03-18 17:18:32.103  5971  5971 D Magisk  : su: use namespace of pid=[5961]
03-18 17:18:32.373  2587  6027 D Magisk  : su: request from pid=[6022], client=[9]
03-18 17:18:32.373  2587  6027 D Magisk  : su: request from uid=[10227] (#1)
03-18 17:18:32.373  2587  6027 D Magisk  : magiskdb: query su_fingerprint=[0]
03-18 17:18:32.374  2587  6027 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
03-18 17:18:32.375  2587  6027 D Magisk  : su: waiting child pid=[6028]
03-18 17:18:32.375  6028  6028 D Magisk  : su: fork handler
03-18 17:18:32.376  6028  6028 D Magisk  : su: use namespace of pid=[6022]
03-18 17:18:32.403  2587  6027 D Magisk  : su: return code=[0]
03-18 17:18:39.513  2587  5969 D Magisk  : su: return code=[0]
```

**Comment by Didgeridoohan** [comment]
You forgot to include [logs](https://www.didgeridoohan.com/magisk/MagiskHelp).

**Comment by VasyaHH** [comment]
> You forgot to include [logs](https://www.didgeridoohan.com/magisk/MagiskHelp).

Attached logs after reboot device. When switch on/off settings logs are empty.

**Comment by topjohnwu** [comment]
Try using an uninstaller to cleanup and reinstall again. There is no similar reports elsewhere, and from the logs the only reason why you are booting in core-only mode is because the file `/cache/.disable_magisk` exists

**Comment by Laiyox** [comment]
Got the same problem that Magisk always get in Core only Mode which can't be deactivated

**Comment by hamaminatu** [comment]
> 
> 
> Try using an uninstaller to cleanup and reinstall again. There is no similar reports elsewhere, and from the logs the only reason why you are booting in core-only mode is because the file `/cache/.disable_magisk` exists

Can we force disable the core-only mode?

**Comment by giftometre** [comment]
I also similar issue. I'm using stock ROM (Nougat 7.1) on Infinix zero 4 plus. It keeps booting with Core mode enabled. Each time I put it off and reboot, it does same. 
Kindly help. 
Thank you.

**Comment by giftometre** [comment]
This is my log after disabling core mode and rebooting.. 

--------- beginning of main
--------- beginning of system
07-18 00:38:33.426   304   304 I Magisk  : Magisk v19.3(19300) daemon started
07-18 00:38:33.427   304   304 I Magisk  : * Device API level: 25
07-18 00:38:41.844   304   429 I Magisk  : ** post-fs-data mode running
07-18 00:38:41.858   304   429 I Magisk  : * Initializing Magisk environment
07-18 00:38:41.873   304   429 I Magisk  : * Mounting mirrors
07-18 00:38:41.874   304   429 I Magisk  : mount: /sbin/.magisk/mirror/system
07-18 00:38:41.875   304   429 I Magisk  : mount: /sbin/.magisk/mirror/data
07-18 00:38:41.876   304   429 I Magisk  : link: /sbin/.magisk/mirror/vendor
07-18 00:38:41.877   304   429 I Magisk  : * Setting up internal busybox
07-18 00:38:41.908   304   429 I Magisk  : * Running post-fs-data.d scripts
07-18 00:38:42.225   304   490 I Magisk  : ** late_start service mode running
07-18 00:38:42.226   304   490 I Magisk  : * Running service.d scripts
07-18 00:38:42.304   304   490 I Magisk  : service.d: exec [v4afx.sh]
--------- beginning of crash
07-18 00:39:22.382   304  2004 I Magisk  : ** boot_complete triggered

**Comment by Michal-Mikolas** [comment]
I have the same problem after updating Magisk & Magisk Manager. 
Xiaomi Redmi 4A, MIUI9. 

I am stupid I updated Magisk. I will never update anything which currently works again!
