### ISSUE TITLE
[feature suggestion] Delete files

### ISSUE THREAD

**Issue by AuroraWright** [topjohnwu/Magisk#1223]
Using the same approach used to add files (unless I misread the source) it'd be possible to also delete a file (mount a tmpfs on its parent folder, create dummy files for all the files *except the ones that have to be deleted*, bind mount the real files on the dummy files). As to how this should be indicated by modules, maybe a DELETE variable could be added to config.sh with a list of files to be removed.

**Comment by topjohnwu** [comment]
A section in documentations since the first days have info regarding deleting files. Usually replacing the original file with a dummy file is good enough. What are the cases that actually deleting a file matter though?

**Comment by topjohnwu** [comment]
@AuroraWright may you elaborate?

**Comment by AuroraWright** [comment]
My bad, I missed the previous reply. I didn't experience a case where file removal is absolutely necessary but someone asked me if it'd be possible to remove "bloat" system apps using Magisk, and I thought that for such a task it'd be way easier to have something like this rather than using dummy files.

**Comment by topjohnwu** [comment]
Removing bloat apps is simple: replacing with a dummy folder :)
All of these techniques are available in the official docs
