### ISSUE TITLE
Google Pay doesn't set up, SafetyNet passes

### ISSUE THREAD

**Issue by Senliast** [topjohnwu/Magisk#1224]
Since a few days, I cannot set up G Pay, it's saying rooted device etc, all through both cts profile and basicintegrity are green. As I read, this happens because of recent Google Play Services update.
I installed old Play Services, like in this thread, and Google Pay now working!

https://forum.xda-developers.com/apps/magisk/discussion-google-pay-magisk-discussion-t3906703

Using latest Canary build.
I only would like to let you know about it.

**Comment by topjohnwu** [comment]
#1152
