### ISSUE TITLE
Weird Lockscreen Issue on Magisk 17+

### ISSUE THREAD

**Issue by user-ilang** [topjohnwu/Magisk#1225]
Hello, me and some kenzo users have a problem. Lockscreen issue, after entering pin, password or pattern, its gonna blackscreen (like systemui restart) and then we can't unlock the device. Its a random bug, not necessarily when it happens, this happens after booting which requires entering a password (except you activate the bypass password on rom features). This bug is very very random, whether it's the first, third, or fourth reboot, it's hard to guess. we are required to remove lockscreen.db to temporarily overcome this bug. We use magisk 17.3 - latest
That's the chronology. 

And yesterday, i gonna some research. I flashed magisk 16.7, and 17, i haven't find lockscreen issue anymore. But, me and other kenzo user want the latest magisk :(

• Bug: Weird Lockscreen Issue (Blackscreen like systemui restart)
• Magisk ver. : 17.3 - Latest
• OS ver. : Oreo, Pie (There no issue on Nougat below)
Need some log? How to take it? I will give the log

Thanks

*Sorry for my bad english, :(

**Comment by Didgeridoohan** [comment]
A logcat grabbed as the bug manifests would be useful. Use a logcat bootscript as described [here]() and reboot until the issue occurs. There'll be a bootlog.log in /cache which you then can pull from recovery. Or, you can simply reboot again and if the device boots up you can save the bootlog_last.log file (also in /cache), which will then be the file showing the bug.

Alwasy use the latest Canary debug build (currently 18121) when reporting about bugs and issues (so unless you have it installed, do that first). It might also be good to include the Magisk log from the same boot as the logcat.

**Comment by user-ilang** [comment]
Okay i will try @Didgeridoohan

**Comment by pranavks** [comment]
I do have the same problem.
On my Asus Zenfone Max Pro M1, ROM: Havoc OS.
