### ISSUE TITLE
Update on the MagiskHide and Google Pay Issue!

### ISSUE THREAD

**Issue by Slats2** [topjohnwu/Magisk#1228]
Hi,

I've been looking into this, here's what I did and found out:

A few days after updating to 18.2 Canary I tried enabling in-store payments and Google Pay said the phone was rooted or altered. I then wiped **/data/data/com.google.android.gms** in recovery, and it worked again for approximately 12 hours (with default MagiskHide settings, only "unstable" enabled in the list). I then wiped data again and enabled MagiskHide on all the Play Services + Google Pay, and it worked for several days, so I considered it to be a pass. 

I then disabled MagiskHide on Google Pay and it still worked for several days. 

Thus:

- the result of the google pay root check is stored in the **/data/data/com.google.android.gms** folder (Google Play Services data folder), for all other apps Android just wipes the **/data/data** folder but that's not the case for Play Services as there's a custom UI for deleting data which doesn't seem to remove everything, and obviously, this data isn't removed. You can wipe **/data/data/com.google.android.gms** in recovery to remove the result of the check.

- the check is done apparently randomly in the span of a day or two. That's probably to achieve what happened in this thread, conflicting reports and people having no idea what triggers the check and how to deal with it.

- the check is done by Google Play Services, but by something other than the "unstable" (SafetyNet) process.

- not sure about this one, but given that Magisk 18.1 and older have imperfect MagiskHide functionality (the hiding can be "raced" and thus defeated with some tricks, according to John himself), it's possible Google is also doing that. Using 18.2 is your best bet as it enables hiding on a process as soon as possible.

I'm now trying to pinpoint which component of play services is doing the check, so the default MagiskHide list can be updated (I'll report on GitHub once I'm sure).

Reporting that renaming com.google.android.gms to com.google.android.gms.bak worked for me. I was able to successfully add a card where before it was detecting root.

Magisk Canary **18.2-945f8810**
Magisk Manager **7.0.0-8893cbd6**
Magisk Hide on all Google Pay and Google Play Services
Google Pay **2.84.237487748**
Google Play Services **15.0.90**

**Nokia 6.1 (2018)**
**February 2019** Security Update
Stock Rooted

**Comment by topjohnwu** [comment]
Thx for the update

**Comment by ihatemicrosoft-was-already-taken** [comment]
Unfortunately, this didn't work for me.

Magisk Manager 7.2.0 (213)
Magisk 19.2 (19200)
Magisk Hide on all Google Pay and Google Play Services
Google Pay 2.88.248767160
Google Play Services 17.1.22

Pixel 3 (blueline)
May 2019 security update

Google Pay had been working before. I set up the phone as new after the May 2019 update. Since then I also can't decrypt the data partition in twrp any longer.

Don't know if and how this all is related to me setting up the phone as new. FYI, Just wanted to share my experiences.

**Comment by Mi2Sir** [comment]
google pay not work any more after May 2019
I have magisk 19.3

**Comment by taylorjdawson** [comment]
If anyone is still having issues [try this](https://forum.xda-developers.com/apps/magisk/magisk-google-pay-gms-17-1-22-pie-t3929950). Confirmed working for me. 

Device: Google Pixel 3XL (crosshatch)
Android Version: 9
Magisk Version: 19.3
Magisk Manager Version: 7.3.2
Google Pay Version: 2.95
Google Play Services Version: 18.3.85

**Comment by testingforbugs** [comment]
> 
> 
> If anyone is still having issues [try this](https://forum.xda-developers.com/apps/magisk/magisk-google-pay-gms-17-1-22-pie-t3929950). Confirmed working for me.
> 
> Device: Google Pixel 3XL (crosshatch)
> Android Version: 9
> Magisk Version: 19.3
> Magisk Manager Version: 7.3.2
> Google Pay Version: 2.95
> Google Play Services Version: 18.3.85

This worked for me as well,

Device: Google Pixel 4 (flame)
Android Version: 10 (QD1A.190821.007)
Magisk Version: 20.0
Magisk Manager Version: 7.3.5
Google Pay Version: 2.10.275591585
Google Play Services Version: 19.4.20 (120400-271418971)

Still have not tested paying, will update when I do

**Comment by moposx** [comment]
> If anyone is still having issues [try this](https://forum.xda-developers.com/apps/magisk/magisk-google-pay-gms-17-1-22-pie-t3929950). Confirmed working for me.
> 
> Device: Google Pixel 3XL (crosshatch)
> Android Version: 9
> Magisk Version: 19.3
> Magisk Manager Version: 7.3.2
> Google Pay Version: 2.95
> Google Play Services Version: 18.3.85

This worked for me, Google Pay no longer detects the root access on my phone.

Device: Google Pixel 2 XL (taimen)
Android Version: 10 (QQ1A.191205.008)
Magisk Version: 20.1
Magisk Manager Version: 7.4.0
Google Pay Version: 2.104.286073543
Google Play Services Version: 19.8.31 (120400-284611645)
  
I will update if this doesn't work after some time.
