### ISSUE TITLE
Samsung on5 Android 6.0.1 after Magisk Root , imei Status goes NG and Network Emergncy mode only 

### ISSUE THREAD

**Issue by A2HI2H** [topjohnwu/Magisk#1229]
Samsung on5 Android 6.0.1 after Magisk Root , imei Status goes NG and Network Emergncy mode only , again after repair imei it works , but again same problem after restart it goes ng , but working fine with super su , please help me to fix it

**Comment by DenyDarko** [comment]
You only report bugs for Canary **debug** builds:
https://github.com/topjohnwu/magisk_files/tree/master/canary_builds

And ONLY with logs:

https://www.didgeridoohan.com/magisk/MagiskHelp
