### ISSUE TITLE
Magisk 18.1Boot Loop in xperia performace

### ISSUE THREAD

**Issue by liCN** [topjohnwu/Magisk#1230]
device: sony xperia performance,F8131
Android 8.0.0, 41.3.A.2.149
V17.1 work but V18.1 loop

**Comment by DenyDarko** [comment]
You only report bugs for Canary debug builds:
https://github.com/topjohnwu/magisk_files/tree/master/canary_builds

And ONLY with logs:

https://www.didgeridoohan.com/magisk/MagiskHelp
