### ISSUE TITLE
Set MagiskManager to EXEMPT in Android PIE as shown under Developer Options > Standby Apps

### ISSUE THREAD

**Issue by Djtrip83** [topjohnwu/Magisk#1233]
Magisk Manager does not appear automatically as EXEMPT under Standby Apps compared to other apps like Tasker or AutoInput.

![image](https://user-images.githubusercontent.com/48355907/54823111-bc58f100-4c9e-11e9-9904-92d9bb6690e4.png)

Can an intent be setup so the app automatically set itself to EXEMPT? Currently, I have to set it to Active manually to avoid Android killing Magisk Manager but it may change between reboots.

Apologies for the non-dev description of the request

**Comment by topjohnwu** [comment]
Sorry, but the standby buckets are determined by your own usage, nothing I can fix
https://developer.android.com/topic/performance/appstandby
