### ISSUE TITLE
about Installation failed

### ISSUE THREAD

**Issue by huitc** [topjohnwu/Magisk#1234]
[magisk_install_log_20181228_221429.log](https://github.com/topjohnwu/Magisk/files/2997097/magisk_install_log_20181228_221429.log)
`Boot image patched by unsupported programs` what's that mean.... t.t
I'm using mi6 android 8.0.0 rooted

**Comment by DenyDarko** [comment]
That means that you need to restore your original boot image and then reinstall magisk.

But that's for XDA not here. 

You may close this :)
