### ISSUE TITLE
com.android.google gms should be added to default Magisk Hide list

### ISSUE THREAD

**Issue by AuroraWright** [topjohnwu/Magisk#1235]
After lots of testing (see here https://forum.xda-developers.com/showpost.php?p=79171459&postcount=469 ) I determined Google now uses the main Play Services component (com.google.android.gms) to randomly check for modifications to use Google Pay rather than (just?) Safetynet/com.google.android.gms.unstable, so I think the default list should be updated to include it. (Sadly that probably won't fix the problem for people who already tripped the check as the result is cached and they still probably need to wipe the Play Services data folder, but not Magisk's issue I guess).

**Comment by Slats2** [comment]
> After lots of testing (see here https://forum.xda-developers.com/showpost.php?p=79171459&postcount=469 ) I determined Google now uses the main Play Services component (com.google.android.gms) to randomly check for modifications to use Google Pay rather than (just?) Safetynet/com.google.android.gms.unstable, so I think the default list should be updated to include it. (Sadly that probably won't fix the problem for people who already tripped the check as the result is cached and they still probably need to wipe the Play Services data folder, but not Magisk's issue I guess).

Same research/testing here.

**Comment by AuroraWright** [comment]
(I don't know if you're trolling me at this point, but tbh it's not funny if you are).

**Comment by topjohnwu** [comment]
@AuroraWright you mean the main process itself and the unstable process is good enough? So only one additional process will make it work?

**Comment by AuroraWright** [comment]
Yeah exactly: https://m.imgur.com/a/j6v0Rnh

**Comment by topjohnwu** [comment]
OK, thanks for the investigation, will add it to the default list 👍

**Comment by UnicornsOnLSD** [comment]
3DS Custom Firmware developer by day, Android researcher by night :)

**Comment by Retro-Dev** [comment]
c
