### ISSUE TITLE
MagiskSU异常

### ISSUE THREAD

**Issue by huangsijun17** [topjohnwu/Magisk#1236]
Los16每日版用户，1-3天更新一次系统，一周多前MSU正常提权使用。
22日注意到MSU异常，症状为原先已经授权的App可以正常提权到ROOT，但其它App请求ROOT权限时，Magisk Manager不响应，无弹窗提示，无日志记录。
但Magisk中的模块工作正常。

＝＝＝＝＝＝＝＝＝＝
LineageOS 16 每日版3月21日版本
小米 MIX 2S 8G+256G
Magisk Manager v7.0.0 (185)
Magisk v18.1 (18100)

**Comment by huangsijun17** [comment]
试过在Recovery中刷卸载包后重装，结果之前所有允许root的记录全没了。。。

**Comment by topjohnwu** [comment]
回報問題請用最新 canary 版。Magisk Manager 有許多改動，可能會修復你的問題。
即使沒有修復你得問題，這也跟 Magisk 無關。請將 Magisk Manager 加入 doze mode / battery save / memory save 的白名單中。
