### ISSUE TITLE
Google Pay still not working

### ISSUE THREAD

**Issue by keyute** [topjohnwu/Magisk#1240]
Yes, I know magiskhide requests will not be entertained. I'm just here to say that adding Google play services process does not work - even after clearing data and reboot

**Comment by tcmaps** [comment]
the battle is lost

**Comment by topjohnwu** [comment]
@keyute I'm aware of this issue, I get 123843023940237403728374923 reports about GPay everyday. Thanks for contributing to development

**Comment by tHBp** [comment]
@keyute Google Pay is working on Magisk Canary though. No need to hide Play Services, just the app itself.

**Comment by keyute** [comment]
@tHBp I'm on Canary

**Comment by yuukieve** [comment]
@keyute This is user error, not the fault of Magisk or @topjohnwu, once you have encountered this error clearing the data of Google Pay/Play Services isn't enough, you need to go into recovery and use ADB or the terminal to delete the entire contents of `/data/data/com.google.android.gms`
