### ISSUE TITLE
[feature request] Have a way to recover from a bad module for devices on which twrp can't mount data

### ISSUE THREAD

**Issue by fishsoupisgood** [topjohnwu/Magisk#1241]
Would it be possible for magisk to abort loading all modules if it detect the presence of a particularly named file on the cache partition?

I have a number of devices which encrypted data partitions that twrp can't mount, so recovering from a bad module is a full system wipe. It would be nice if there were a way to make magisk temporarily disable all but the core functionality. Prehaps by holding a button, perhaps by detecting a file on the cache partition, perhaps after noticing 3 boots in a row failed.

**Comment by Zackptg5** [comment]
TWRP should be able to mount encrypted data so you might want to talk to your device's twrp maintainer. How would magisk be able to distinguish that the cause of the bootloop is it? Newer devices don't even have a cache partition anymore.
You could just flash magisk uninstaller zip in twrp or restore stock boot img with fastboot if that happens
Also note that future magisk versions don't have an img anymore - it's just a normal folder now: /data/adb/modules

**Comment by topjohnwu** [comment]
You should use Magisk Manager to install modules if custom recovery cannot decrypt data

**Comment by fishsoupisgood** [comment]
Using magisk manager the flow I've experienced is the following:

1) I boot the device with magisk running
2) I use magisk manager to install a new module, with a problem that prevents the system booting
3) I reboot
4) the system now won't boot, and I can't disable the module because I can't mount data in TWRP (special vendor method of calculating key using trustzone).

What I was asking for was some way of preventing magisk from loading any modules, be it a file on cache or a button held down or something similar, so that recovering from this situation doesn't require a full wipe.
