### ISSUE TITLE
单刷处理过的boot.img无法安装模块

### ISSUE THREAD

**Issue by scarlet-glass** [topjohnwu/Magisk#1244]
大神你好，我刷了你最新的构建版本magisk，刷完以后将boot.img提取出来，给别的机器刷进去，虽然可以实现root，但是安装模块会失败，请问这个是什么问题？是不是有部分文件写入了data分区啊？

**Comment by topjohnwu** [comment]
新版的 Magisk Manager 已修復 additional setup。

**Comment by scarlet-glass** [comment]
是不是还没有编译？我用你3天前的构建版本还是不行

**Comment by scarlet-glass** [comment]
@topjohnwu
