### ISSUE TITLE
Running apps who require root access without rooting the device 

### ISSUE THREAD

**Issue by ShalokShalom** [topjohnwu/Magisk#1245]
This page here claims that you can install Apps who would normally require root access without such one: https://www.magiskroots.com/

Is this true? 

I am asking because Blackberry devices provide a special security mechanism which prevents rooting.

**Comment by DenyDarko** [comment]
Another scam?

Internet is full of those and they're (obviously) unrelated to magisk or its developer.

**Comment by topjohnwu** [comment]
Why the god do people believe these stupid scams and now spamming my Github issue

**Comment by ShalokShalom** [comment]
Honestly, reporting obscure webpages about your project is something you could be grateful for. 
And besides that did you miss the meaning of the word spam.
