### ISSUE TITLE
Google Play & Gmail App just close it self

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [topjohnwu/Magisk#1247]
Since last version my Google Play App close it self when I try to update a app. Also: My Gmail App just close it self when I open a mail.
[magisk_log_20190326_173511.log](https://github.com/topjohnwu/Magisk/files/3009228/magisk_log_20190326_173511.log)

**Comment by topjohnwu** [comment]
This will revert the change that break things: d08b1a6639d3569eb1533e85cbe958743eedef97
