### ISSUE TITLE
About Magisk Module in Nubia X

### ISSUE THREAD

**Issue by MasterOfStar** [topjohnwu/Magisk#1250]
After Nubia X Android magisk couldn't install most of the modules,  But the group also has other mobile phone F2FS system can brush module. Hereby, what is the specific reason for this. （Translation, Chinese → English ）

Nubia X安卓magisk后无法安装大部分模块
根据为该机型适配的大佬称是F2FS的缘故。但是群里也有其他手机F2FS系统能够通刷模块的。
特此求证具体是什么原因。

**Comment by MasterOfStar** [comment]
log：
- Copying zip to temp directory
- Installing magisk-riru-core-v17.1(1).zip
- Mounting /system, /vendor
Archive:  /data/user/0/com.nP.SW.Sp.OPp1uLT/cache/install.zip
   creating: common/
  inflating: common/post-fs-data.sh
  inflating: config.sh
  inflating: module.prop
- Device platform: arm64
***********
Riru - Core
***********
******************************
Powered by Magisk (@topjohnwu)
******************************
- Creating /data/adb/magisk_merge.img with size 64M
Creating filesystem with parameters:
    Size: 67108864
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4096
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16384
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4096 inodes and 1294/16384 blocks
Create /data/adb/magisk_merge.img with size 64M
e2fsck 1.43.3 (04-Sep-2016)
open: /dev/block/loop7 failed with 2: No such file or directory
! /data/adb/magisk_merge.img mount failed...
! Installation failed

**Comment by scarlet-glass** [comment]
使用我的新版本就可以实现安装模块了啊。努比亚论坛搜索  绯色玻璃   看我的最新发帖

**Comment by skittles9823** [comment]
@MasterOfStar The Magisk image will be gone as of 18.2 so this bug won't really matter by then.

As for the current situation, you can try rebooting and if that doesn't fix the issue, reinstalling Magisk will.

**Comment by scarlet-glass** [comment]
@MasterOfStar 楼主可以前往https://bbs.nubia.cn/thread-1452565-1-1.html
使用我的方法进行root安装模块，根据你的日志查看，还是作者之前很早的版本，使用打包magisk_merge.img的方法来实现的。作者在几个月前就已经修复了该问题，采用别的办法来实现了模块安装的问题

**Comment by MasterOfStar** [comment]
@scarlet-glass 好的👌 我是刷的youyim2的那个“全功能版”。好久没上论坛了，不知道😂

**Comment by MasterOfStar** [comment]
@scarlet-glass TWRP的话youyim2的和你的有什么差别吗？

**Comment by scarlet-glass** [comment]
@MasterOfStar 没有。
