### ISSUE TITLE
Magisk manager giving an update notification when no update is available.

### ISSUE THREAD

**Issue by OutrageOrange** [topjohnwu/Magisk#1252]
On 7.0.0 using stable release channel and it is stuck in a never ending "please update" notification loop. If i update like it asks, it still continuously notifies about the same update, even though the app itself says it is up to date.
- Android 8.0.0 (Oreo)
- Moto e5 cruise (James) 
- Not rooted (_yet_) 
- Cricket wireless

**Comment by topjohnwu** [comment]
1. No full description
2. Not using canary channel for reports
3. Closed
