### ISSUE TITLE
Magisk19.0 can't boot

### ISSUE THREAD

**Issue by Roiyaru** [topjohnwu/Magisk#1256]
Equipment: ZUK Z2 (z2_plus), ROM: AEX6.4 (pie, /factory), TWRP-factory-3.2.3-1. In the process of installing Magisk19, everything is normal (Twrp does not show a red error message), but it can't be stuck, and the card is on the first screen. Use 18.1 and everything works fine.
This is the Google Cloud Drive link, which has the logcat I crawled.
https://drive.google.com/file/d/1pNjqLaO5PlUAbGbAqMvb7F27uLrHKkpH/view?usp=drivesdk

**Comment by kill0rz** [comment]
Seems to be the same problem as #1196 .
Can reproduce on my OnePlus3 A3003.

No logcat output at boot logo :/

```
- Detecting target image
- Device platform: arm64-v8a
- Existing zip found
1014+1 records in
1014+1 records out
1039176 bytes (1014.8KB) copied, 0.019707 seconds, 50.3MB/s
- Unpacking boot image
Parsing boot image: [/dev/block/sde18]
HEADER_VER      [0]
KERNEL_SZ       [10217010]
RAMDISK_SZ      [1746013]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
DTB             [0]
OS_VERSION      [8.1.0]
OS_PATCH_LEVEL  [2018-12]
PAGESIZE        [4096]
NAME            []
CMDLINE         [androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 cma=32M@0-0xffffffff buildvariant=userdebug]
CHECKSUM        [e7dfd7335c8e9e5b2a7ebe57f0632c33ca13c4b2]
KERNEL_DTB      [700287]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Magisk patched boot image detected
Loading cpio: [ramdisk.cpio]
Remove [.backup]
Remove [.backup/.magisk]
Move [.backup/init] -> [init]
Dump cpio: [ramdisk.cpio]
Loading cpio: [ramdisk.cpio]
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Patch with flag KEEPVERITY=[false] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [kernel_dtb]
Found fstab in dtb.0000
Found block [system] in fstab
Found fstab in dtb.0001
Found block [system] in fstab
- Repacking boot image
Parsing boot image: [/dev/block/sde18]
HEADER_VER      [0]
KERNEL_SZ       [10217010]
RAMDISK_SZ      [1746013]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
DTB             [0]
OS_VERSION      [8.1.0]
OS_PATCH_LEVEL  [2018-12]
PAGESIZE        [4096]
NAME            []
CMDLINE         [androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 cma=32M@0-0xffffffff buildvariant=userdebug]
CHECKSUM        [e7dfd7335c8e9e5b2a7ebe57f0632c33ca13c4b2]
KERNEL_DTB      [700287]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [10217010]
RAMDISK_SZ      [1716137]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
DTB             [0]
OS_VERSION      [8.1.0]
OS_PATCH_LEVEL  [2018-12]
PAGESIZE        [4096]
NAME            []
CMDLINE         [androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 cma=32M@0-0xffffffff buildvariant=userdebug]
CHECKSUM        [746fec7f9899a2703596e73bd8a33bd414c95e39]
- Flashing new boot image
- All done!
```

**Comment by xerta555** [comment]
Hello.

I get the exactly same issue.
This following mounting error from the vendor partition repeats itself indefinitely, blocking everything else, resulting in a bootloop.


Recording loggcat, i get this following error:
`adsprpc : vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:43:adsp daemon restarting...
adsprpc : vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:39:adsp daemon error dlopen failed: library "libadsp_default_listener.so" not found
adsprpc : vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:41:adsp daemon sleeping for 25ms
debuggerd: resuming target 8347
ServiceManager: service 'media.audio_flinger' died
ServiceManager: service 'media.player' died
ServiceManager: service 'media.resource_manager' died
ServiceManager: service 'media.camera' died
adsprpc : vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:43:adsp daemon restarting...
adsprpc : vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:39:adsp daemon error dlopen failed: library "libadsp_default_listener.so" not found
adsprpc : vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:41:adsp daemon sleeping for 25ms
adsprpc : vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:43:adsp daemon restarting...
adsprpc : vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:39:adsp daemon error dlopen failed: library "libadsp_default_listener.so" not found
adsprpc : vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:41:adsp daemon sleeping for 25ms
adsprpc : vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:43:adsp daemon restarting...`

Complete logcat file:
[logcat.txt](https://github.com/topjohnwu/Magisk/files/3020236/logcat.txt)

I had to:
- reboot manually (with physical hardware keys) in my custom recovery
- flash Magisk v18.1 ZIP file
- rebooting in system (classic mode) to finaly boot normaly again but i can't get Magisk working again bcz the Manager say that Magisk isn't installed.

My device:
LG H870 (G6)
arm64
Android 7.1.2
Resurection Remix (custom ROM)

**Comment by HafizZiq** [comment]
I get same issue like @xerta555 
But after flash magisk 18.1 everything works lile usual
Magisk 19.0 stuck at splahloop screen

**Comment by Roiyaru** [comment]
@HafizZiq Me too, can only use 18.1.

**Comment by bzntm** [comment]
Normal on rolex (Redmi 4A)

HavocOS 2.3
Android Pie
NGNTD Kernel

**Comment by Roiyaru** [comment]
Oddly, I first installed the 7.1.0 manager, and it was successful to choose to install 19.0 directly in the manager. But why can't I install it in twrp?

**Comment by Roiyaru** [comment]
Okay I'm sorry. Even if you can successfully install 19.0 in the manager, an unknown error will occur. For me, 18.1 is the best, 19.0 I can't use it at all (successfully installed but can't boot). The following link contains the logcat I crawled (including magisk) https://drive.google.com/folderview?id=1H3WKVQzVKX4Te35TYeLnbdgG3j4Suiw4

**Comment by Kugumin** [comment]
Same issue. I can install Magisk 19, but whenever I want install any module or just simply reboot it won't boot in system. Somehow cleaning Dalvik Cache helps to boot system, but to be honest it takes much time!

**Comment by Roiyaru** [comment]
I urgently need a solution. Who can help me?

**Comment by xerta555** [comment]
> I urgently need a solution. Who can help me?

Have u tested to uninstall Magisk completly ?
[Magisk-uninstaller-20181208.zip](https://github.com/topjohnwu/Magisk/files/3024771/Magisk-uninstaller-20181208.zip)

After having uninstall Magisk, install again the v18.1 ZIP 
[Magisk-v18.1.zip](https://github.com/topjohnwu/Magisk/files/3024773/Magisk-v18.1.zip)

**Comment by Roiyaru** [comment]
@xerta555 Well, I am using 18.1 now, but I want to use 19.0. I have not found a solution right now.

**Comment by Kugumin** [comment]
@Roiyaru, looks like we have to wait for @topjohnwu to fix this issue, because it happens for many people

**Comment by HafizZiq** [comment]
@Roiyaru 
Also,after switch back to magisk 18.1 from magisk 19,my phone takes little bitut time to booting
The solution are only clean flash..
Ive doing anything inclu5 uninstaller magisk 18.q and 19
Full uninstalled,but yea..tajes time to boot into system rather than before..
Clean flash solve every magisk problem for me..but yea,its take time!

**Comment by BintangRN** [comment]
> Equipment: ZUK Z2 (z2_plus), ROM: AEX6.4 (pie, /factory), TWRP-factory-3.2.3-1. In the process of installing Magisk19, everything is normal (Twrp does not show a red error message), but it can't be stuck, and the card is on the first screen. Use 18.1 and everything works fine.
> This is the Google Cloud Drive link, which has the logcat I crawled.
> https://drive.google.com/file/d/1pNjqLaO5PlUAbGbAqMvb7F27uLrHKkpH/view?usp=drivesdk

same problem for me

**Comment by Roiyaru** [comment]
This problem is common in z2_plus's treble rom, which may have changed in order to adapt to pixel3.

**Comment by xerta555** [comment]
@Roiyaru @kill0rz @HafizZiq @Kugumin @BintangRN 
This problem don't happen anymore on my phone after applying the last update:
https://github.com/topjohnwu/Magisk/blob/91da1cf817528d7adea331204c93aa0554fdc7c2/scripts/module_installer.sh

on my modules, my device is booted propeply :+1:

**Comment by Roiyaru** [comment]
@xerta555 Received, I will try

**Comment by Roiyaru** [comment]
I updated the latest Canary version, which is still a normal installation but not bootable.

**Comment by xerta555** [comment]
> I updated the latest Canary version, which is still a normal installation but not bootable.

Personaly the last BETA (v19) works fine for me
https://github.com/topjohnwu/Magisk/releases/tag/v19.0

**Comment by Roiyaru** [comment]
@xerta555 No, the version after 18.1 on my device will not boot.

**Comment by Kugumin** [comment]
> my device is booted propeply

My phone doesn't boot even without modules, so I don't think the problem is exactly in the modules

**Comment by Roiyaru** [comment]
@Kugumin I have the same opinion as you.

**Comment by kill0rz** [comment]
Latest Canary update 19002 did not fix the non-booting error on my One Plus 3 A3003 :(

**Comment by kill0rz** [comment]
19003 with clean install has same problem

**Comment by SunatP** [comment]
@topjohnwu good evening mr.Topjohnwu, i update Magisk to 19 in Magisk Manager and got successfully but after press reboot and then my phone doesn't boot normally it's looklike a bootloop maybe and i can't get logcat from TWRP, so i decide to flash uninstall magisk and flash 18.1 again after that it's boot normally, what's wrong in ver 19?

**Comment by topjohnwu** [comment]
People should try the latest canary for reporting, not official v19!

**Comment by kill0rz** [comment]
> People should try the latest canary for reporting, not official v19!

I tried 19003 from Canary Channel but got the same behavior.

**Comment by shakalaca** [comment]
@kill0rz what's your OS version ? I have no problem with 19003 on my A3003 (in stock ROM 5.0.8)

**Comment by shakalaca** [comment]
@Roiyaru I see 'init.magisk.rc' in your log but as far as I know it's been removed someday in February. Can you upload the 'stock boot.img' and 'patched boot.img' for further analysis ? :)

**Comment by Roiyaru** [comment]
@shakalaca What do you need is the original boot and the boot after installing magisk?

**Comment by shakalaca** [comment]
@Roiyaru I need both of them :)

**Comment by Roiyaru** [comment]
@shakalaca The files you need are in the link below https://drive.google.com/folderview?id=1H3WKVQzVKX4Te35TYeLnbdgG3j4Suiw4

**Comment by shakalaca** [comment]
@Roiyaru the files you uploaded are identical, can you dump or backup boot partition in TWRP after flash the Magisk ?

**Comment by Roiyaru** [comment]
@shakalaca You need me to boot in twrp backup or boot partition that can't boot

**Comment by shakalaca** [comment]
@Roiyaru I need the boot image that cannot boot up your phone, either you patch throught MagisManager or backup (or dd) from TWRP

**Comment by Roiyaru** [comment]
@shakalaca The new file has been uploaded https://drive.google.com/folderview?id=1H3WKVQzVKX4Te35TYeLnbdgG3j4Suiw4

**Comment by shakalaca** [comment]
@Roiyaru so can your phone boot up or not after installing Magisk ? The log tells me your phone boot up successfully, but root app isn't working right ?

**Comment by Roiyaru** [comment]
@shakalaca I did not perform any cleanup after installing magisk, no boot, so I don't know if magicsk is working properly.

**Comment by Roiyaru** [comment]
@shakalaca I did not perform any cleanup after installing magisk, no boot (the card is on the first screen after booting, did not enter the boot animation), so I don't know if the magic is working properly.

**Comment by shakalaca** [comment]
@Roiyaru then how do you get the logcat ?

**Comment by Roiyaru** [comment]
@shakalaca Do not clear any, install magisk18.1 directly

**Comment by Roiyaru** [comment]
@shakalaca Do not clear anything, install magisk18.1 directly. I now feel that I may have caught the wrong logcat.

**Comment by HemanthJabalpuri** [comment]
@shakalaca
I have similar issue at https://github.com/topjohnwu/Magisk/issues/1196 and log is taken with logcatbootscript placed in postfsdata.d folder....
May that will give some info

**Comment by ARTI1208** [comment]
Zenfone 2 (x86), Android 7, built magisk with recent commits. Sometimes boots, but mostly not. I can't find out what makes it boot, but it seems that flashing on fresh (after uninstaller) always breaks boot process while flashing on top of 18.0 or 18.1 sometimes passes

**Comment by shakalaca** [comment]
@Roiyaru Can you boot into twrp and show me the output of *"adb shell ls -lZ /data/adb"* ?
@HemanthJabalpuri From your log I see Xposed installed, did you try to boot without Xposed ?
@ARTI1208 when failed to boot then go twrp and show me the output of *"adb shell ls -lZ /data/adb"*

**Comment by ARTI1208** [comment]
@shakalaca 
```
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
drwxr-xr-x    3      4096 Apr 12 10:27 u:object_r:magisk_file:s0        magisk
-rw-------    1     11264 Apr 11 17:36 u:object_r:adb_data_file:s0      magisk.db
-rw-r--r--    1  67108864 Apr 12 10:27 u:object_r:adb_data_file:s0      magisk.img
drwxr-xr-x    2      4096 Apr 11 17:04 u:object_r:adb_data_file:s0      post-fs-data.d
drwxr-xr-x    2      4096 Apr 11 17:04 u:object_r:adb_data_file:s0      service.d
```

**Comment by shakalaca** [comment]
@ARTI1208 Is this 18.x or Canary build ? If you're on Canary build then try this and see if it boots up:
```
adb shell mkdir /data/adb/modules
adb shell chmod 755 /data/adb/modules 
adb shell chcon u:object_r:system_file:s0 /data/adb/modules
adb reboot

```
And if possible, try clean install (remove everything under /data/adb/) and give me the output with above command if failed to boot.

**Comment by ARTI1208** [comment]
@shakalaca built by myself yesterday. Creating modules dir has no effect. Removing contents of /data/adb/ helps if 18.x (18.1 in my case) was installed (installed 18.1 -> booted -> cleaned adb folder in twrp -> flashed my build -> booted), however it not works when I tried to reinstall my build

**Comment by Haitham025** [comment]
I have 
Nexus 6P
Pixel experience ( 2019/04/04 )
My camera don't work , when i try to uninstall magisk my device CANNOT BOOT UP , do you have any solution ? 
Sorry for my English

**Comment by Roiyaru** [comment]
@shakalaca I tried the input instruction in TWRP and it didn't output anything

**Comment by Darkcast** [comment]
Did you do a backup before flashing? Have you tried flashing the magisk Uninstaller?

**Comment by Haitham025** [comment]
I didn't do backup because after flashing the rom and starting the device,
i flash magisk .
Yes i flash magisk uninstall and show some errors . Sorry for my English

في الثلاثاء، 16 أبريل 2019 9:52 م Darkcast <notifications@github.com> كتب:

**Comment by Darkcast** [comment]
I mean did you  backup before flashing so you can restore.

**Comment by Haitham025** [comment]
No i didn't . Just downloaded substratum and restart the device and the
camera finally worked. I don't know what that issue but THANKS TO CONTACT
WITH ME


في الأربعاء، 17 أبريل 2019 1:32 ص Darkcast <notifications@github.com> كتب:

**Comment by topjohnwu** [comment]
The issue is slowly deteriorating into user support thread. Closed
