### ISSUE TITLE
Support Wear OS Devices

### ISSUE THREAD

**Issue by simonsmh** [topjohnwu/Magisk#1257]
Since Wear OS doesn't have document application, it could never install the module from Magisk Manager and this problem is more urgent since v7.1.
Also we need a Wear OS Layout for the tiny screen. Design similar to the play store is just OK.

**Comment by topjohnwu** [comment]
Sorry, but I don't have a wear OS device, and currently don't have time for more UI related work on this project

**Comment by simonsmh** [comment]
What about running on the emulator?
At least leave this issue open and wait community to implement it. It is an issue.

**Comment by fox8091** [comment]
Since the UI is going through a pretty heavy refactor, is there any chance this can be revisited? Not only is the UI hard to use on a Wear device, but Magisk Manager can't be hidden nor updated due to the fact that PackageManager denies app installs on Wear. However, Play Store and ADB can install packages without problems.

**Comment by fox8091** [comment]
Do note, in the two watches I have access to, you can tell that they're a WearOS device by parsing ro.build.characteristics. WearOS devices have "watch" as one of their characteristics.

**Comment by lss4** [comment]
I currently have a Huawei Wear 2 Pro. With [janjan's custom ROM and recovery](https://forum.xda-developers.com/smartwatch/watch-2/rom-t3705589), the result is mostly positive.

Magisk 19.3 can be installed and used without issues. While Magisk Manager's layout might not be the best on the watch, it's still usable.

I've only encountered the following caveats so far. Apart from those, everything's working fine.
1. It's not possible to answer Superuser prompts on the watch (the prompt simply does not show up). You need to use either Deny or Grant for automatic responses.
2. (same as fox8091's comments) Wear OS (used to be Android Wear) does not support sideloading APKs, it's not possible to hide or upgrade Magisk Manager. The watch does contain a Package Installer app but what it does is to tell you that "Install/Uninstall actions not supported on wear". As far as I remember it's still possible to install apps via `adb install`.

**Comment by simonsmh** [comment]
@lss4 It's far from usable. There is no working download and install manager makes it unable to install magisk itself and modules. This is still a serious problem.

**Comment by lss4** [comment]
> @lss4 It's far from usable. There is no working download and install manager makes it unable to install magisk itself and modules. This is still a serious problem.

Yeah... personally I never tested those as I hardly thought of any modules useful on a watch.
Considering that it's also not possible to install modules or Magisk itself as you mentioned, guess the flashing capability is also not available on the watch, either.

At least it does its intended basic purpose as a systemless root as far as I can tell.

**Comment by fox8091** [comment]
I personally am able to install modules (requires clicking the far upper left), but installing Manager doesn't work due to PackageManager. I believe pm install through a shell still works though, so I can test.

**Comment by FloopDaPig** [comment]
I am also very interested in this as i have a custom rom on my huawei watch 2, and would love to get google pay working.

**Comment by lss4** [comment]
A late post regarding the situation with most recent Magisk versions (and Manager).

It seems with latest (redesigned) Magisk Manager, I couldn't even change Automatic Responses to Grant on my Huawei Watch 2 Pro, because with the new UI, the title part is so big that it leaves virtually no room to show the options (made several attempts to choose the option but no avail, changing Display->Font size to Small doesn't help, either). As Prompt doesn't work on Wear OS (not sure how it is now), this makes newer Magisk versions (that come with the redesigned Manager) mostly unusable (one can still use early versions, though).

And as for PackageManager... `pm install` from a shell (as well as `adb install`, which was how I sideloaded Kernel Adiutor 4 Wear) does work. It's just that the Package Installer on Wear OS is merely a stub telling you that sideloading is not supported (which is not true).

**Comment by DestroyerXyz** [comment]
Can the package installer be tweaked?

**Comment by darkdex52** [comment]
I'm also having the same issue on my Asus Zenwatch 2. The new redesign makes the prompt option title too big, so you can't select automatic deny or grant in the options menu, thus you can't grant any apps root permissions.

**Comment by browntownington** [comment]
I used to flash Magisk.zip in TWRP on my custom ROM Huawei Watch 2. This process was seamless.

As of Magisk v22 only an apk is provided. I read that you can rename the apk to zip and flash in TWRP but i also read it could cause a boot loop and now the patched boot is now recommended.

I decided to to try 'adb install -r Magisk.apk' which looked to install the manager app. I then on my watch opened Magisk and did an 'update' with direct install method. The screen UI is had to navigate but you can YOLO through. Or you can change the DPI via ADB if you are not sure.

**Comment by mgood7123** [comment]
> Since Wear OS doesn't have document application, it could never install the module from Magisk Manager and this problem is more urgent since v7.1.
> Also we need a Wear OS Layout for the tiny screen. Design similar to the play store is just OK.

Wtf WearOS can be rooted? How? There is no recovery mode nor download/fastboot mode

**Comment by browntownington** [comment]
> Wtf WearOS can be rooted? How? There is no recovery mode nor download/fastboot mode

Android Watch is the same as an Android phone. It does have  recovery and download/fastboot mode. You simply boot fastboot and boot twrp and flash Magisk to boot as usual. Boom profit.

**Comment by mgood7123** [comment]
But ONLY if your wear os device supports usb :(

Wifi adb to reboot and flash is impossible :(

**Comment by Tiebe** [comment]
There's work being done at https://github.com/Dionicio3/Magisk

**Comment by fillwithjoy1** [comment]
Surely UI work on Wear OS should now be considered since we have the Pixel Watches that make it easy to root the device
