### ISSUE TITLE
Can't unselect Google GMS in Magisk Hide v19

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [topjohnwu/Magisk#1259]
As far as I understand it, the patch for #1247 landed, but I can't unselect GMS.unstable in Magisk Hide v19. I even tried to re-install Google Play with OpenGApps.

![Screenshot_20190329-001509_Magisk_Manager](https://user-images.githubusercontent.com/11881073/55199992-79c27780-51bc-11e9-8868-d284f899e72b.png)

[magisk_log_20190329_004937.log](https://github.com/topjohnwu/Magisk/files/3020535/magisk_log_20190329_004937.log)

**Comment by Displax** [comment]
This is not a bug, "unstable" is hardcored.

**Comment by Didgeridoohan** [comment]
And, to clarify further, the commit you mentioned removed com.google.android.gms from being hardcoded.

**Comment by Tobias-B-Besemer** [comment]
Shouldn't then com.google.android.gms.unstable not be removed, too?

**Comment by Didgeridoohan** [comment]
No, because that's what makes it possible to pass SafetyNet. It has always been on the Hide list.

**Comment by Tobias-B-Besemer** [comment]
But the PR to #1247 don't fix the issue for me... I guess because I have the beta of gms...

**Comment by Didgeridoohan** [comment]
Then you have a different issue that is unrelated. Close the issue please.

**Comment by Tobias-B-Besemer** [comment]
Can you re-open #1247, because it's not fixed for me?

**Comment by Didgeridoohan** [comment]
Better to open a new issue in that case, including new logs that show the actual crashes (logcat).
