### ISSUE TITLE
Magisk Root Android O Developer Preview

### ISSUE THREAD

**Issue by KristianFJones** [topjohnwu/Magisk#126]
Install appears fine but upon booting Magisk Manager reports not rooted functionality greatly limited

Nexus 6P
Stock Android O Preview 1

**Comment by TheComputerGuy96** [comment]
@KristianFJones This problem will be fixed on Magisk v13.0

**Comment by KristianFJones** [comment]
Yeah, I've been running magisk V13 on the dev preview for a few weeks
