### ISSUE TITLE
Magiskhide doesn't hide busybox

### ISSUE THREAD

**Issue by Kieaer** [topjohnwu/Magisk#1260]
Device: S7 Edge Exynos (Android 8.0)
Magisk v19.0

The busybox in the sbin folder is exposed and the magiskhide does not function properly.
![Screenshot_20190329-094741_RootbeerFresh](https://user-images.githubusercontent.com/44261958/55201734-b9fb1780-5207-11e9-9134-f6c456bfe7b9.jpg)

**Comment by Zackptg5** [comment]
Busybox is in a hidden folder in sbin and isn't even mounted for use, it's just a symlink. If any app actually tries to detect in the real world that'd be an issue but this is just a root checker app that's going out of it's way to look for it so I doubt that this would be an issue

**Comment by Kieaer** [comment]
@Zackptg5 Some apps are detecting Busybox.
It usually checks Busybox and blocks it from running in chat apps (Kakaotalk) and games (Dolls Order, FGO and etc...)

**Comment by Ingan121** [comment]
Uninstall that BusyBox in the same way that you installed it, and then install BusyBox from Magisk modules repo.
