### ISSUE TITLE
Hello topjohnwu I just saw that you have updated but I just saw that my icon for androidtv was not put

### ISSUE THREAD

**Issue by bubuleur** [topjohnwu/Magisk#1262]
Hello topjohnwu I just saw that you have updated but I just saw that my icon for androidtv was not put
Waiting for a response
Thanking you

_Originally posted by @bubuleur in https://github.com/topjohnwu/Magisk/issues/1169#issuecomment-477900490_

**Comment by Didgeridoohan** [comment]
Was there really a need to open a new issue about this? Since the "Enhancement" label was added to the original issue, you can be pretty sure that it's on the to-do list. The thing is that the to-do list is pretty long and priority choices have to be made. UX enhancements will come at some point.

**Comment by bubuleur** [comment]
Okay, sorry, but how long will it be? 
Thank you

**Comment by Didgeridoohan** [comment]
ETA=When it's ready.

(There's an unwritten rule in the enthusiast development world - never ask for an ETA.)
