### ISSUE TITLE
Restoring stock boot image caused phone to not boot any more - Wrong image restored? Multiple stock image backups found!

### ISSUE THREAD

**Issue by TomasRiker** [topjohnwu/Magisk#1263]
### System
My device: **Xiaomi Mi A1**
Android version: **Pie, February 2019 update, 10.0.5.0**

### What happened
- I wanted to do an OTA update to the March 2019 version of Pie (10.0.6.0).
- As always, I let the download start and, before it would actually install the update, I used Magisk Manager to restore the stock boot image. It said it was successful.
- The OTA update failed. I had seen this before, so I didn't worry much.
- I decided to install Magisk back (using the Manager's "Direct install" method since no OTA update was done). This led to an error message: _"No boot image magic found!"_ / _"Unable to unpack boot image"_ / _"Installation failed"_.
- I rebooted, but the system wouldn't boot any more (stuck in white screen with the Mi logo and the color bars not moving).
- Fortunately, Fastboot was still working, so I booted TWRP.
- I looked for the stock image backed up by Magisk and found **two of them** in `/data`.
- One file was a month old (when I did the last OTA update, which worked), the other one was two months old.
- I flashed the newer one to `boot`.
- The system booted fine again, and later on I was able to install Magisk back.

### Questions
- Is it normal that there is more than one stock image backup in `/data`?
- What does Magisk do when, during restoring the stock boot image, it encounters multiple backups? Does it simply flash the first one it finds, or does it select the one with the newest file modification date? (I think it should, or at least it should ask the user.)
- If this is already done as I proposed, why did it work after I manually flashed the same file that Magisk should have flashed when I told it to restore the backup?

**Comment by topjohnwu** [comment]
Magisk will save the hash of the stock boot image it patched, and will only use a matching boot image to restore. There must be something wrong with your setup
