### ISSUE TITLE
Magisk Repo Not Working

### ISSUE THREAD

**Issue by Slats2** [topjohnwu/Magisk#1264]
Hi @topjohnwu 

The Magisk Repo is not showing all the latest modules that have been released or updated in the past few days.

The download speeds are also getting slow as well.

Please reply.

@Slats2

**Comment by KieronQuinn** [comment]
Module listing working absolutely fine for me, and the speed is dependent on GitHub, I suggest you read #1249

**Comment by Slats2** [comment]
Was not related

**Comment by KieronQuinn** [comment]
Ah, so an issue about a module being slow to download isn't related to modules being slow to download from the repo. Sure.

**Comment by topjohnwu** [comment]
d22c7de79a4280097cae4093ad5fe80debf1b592
