### ISSUE TITLE
Magisk is not working after MagiskManager update

### ISSUE THREAD

**Issue by PSSGCSim** [topjohnwu/Magisk#1265]
Hello,
yesterday I have updated MagiskManager to version 7.1.0. Since then I was not able to make Magisk work again. I have even tried going up a version (19) to the beta channel. But I had no luck.
Today I decided to gather some logs and see if there is anything relevant. I have found that in beginning of logcat is crash report of the magisk.bin. I could not find anything of this sort in already posted issues so I am posting it now myself. I am running latest version of the OnePlus's OxygenOS on the 5T model. The system boots normally but the Magisk shows as "not installed". I have used the method of patching the boot.img packed with the OS and then flashing the patched_boot.img thru the fastboot mode.
I am attaching the installation log and the logcat log.

Thank you for looking into this.

[magisk-logcat.log](https://github.com/topjohnwu/Magisk/files/3022569/magisk-logcat.log)
[magisk_install_log_20190329_125341.log](https://github.com/topjohnwu/Magisk/files/3022570/magisk_install_log_20190329_125341.log)

**Comment by PSSGCSim** [comment]
The update must have corrupted some of Magisk's files in `/data/adb/*`. After purging all Magisk related files everything started to work again.
Files I have removed:
```
/data/adb/magisk.img
/data/adb/magisk.db
D /data/adb/magisk
```
For me it is solved by this workaround but if you want to look into it further feel free to reopen this.

**Comment by keeferrourke** [comment]
Hey @PSSGCSim I had the same issue, and this solved it! Thanks :)
