### ISSUE TITLE
Device Support: Huawei Honor V8

### ISSUE THREAD

**Issue by dadaist** [topjohnwu/Magisk#127]
Twrp install Magisk-v11.2.zip and Magisk-v11.6.zip failed. screen freezes at "patching boot img" then device reboot.

rooted phone with SuperSu, then attempted install using Magisk Manager. Error message "Magist installation error".

Here is the boot image extracted with TWRP.
[boot.emmc.zip](https://github.com/topjohnwu/Magisk/files/860457/boot.emmc.zip)

**Comment by Gondost** [comment]
If this is anything like the Honor 8, Huawei inexplicably left out loop mount support from the Nougat kernel. On the Honor 8 we're stuck on Marshmallow for now.

**Comment by Ante0** [comment]
It's the same with Mate 9.
SuperSU is flashable though, but only with the phh/su hybrid install zip. I guess the same could be done with Magisk.
