### ISSUE TITLE
Magisk Canary not getting the beta MM Update

### ISSUE THREAD

**Issue by Slats2** [topjohnwu/Magisk#1270]
Hi @topjohnwu 

The Canary release channel has not been given the beta MM update!

**Comment by topjohnwu** [comment]
Are you asking for a ban? Really?

**Comment by Slats2** [comment]
No, I am not!

Kind Regards,

Braeden Slatyer

**Comment by Slats2** [comment]
> Are you asking for a ban? Really?

Why?

**Comment by Didgeridoohan** [comment]
Most likely because you're spamming the issue tracker.

**Comment by Slats2** [comment]
No, I am not!
