### ISSUE TITLE
[Magisk v19] New module format => bootloop

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#1273]
Hello @topjohnwu 

Regarding the last rules about module installer:
https://github.com/topjohnwu/Magisk/blob/master/docs/guides.md

Regarding your last module template, there are few issues:
- if the user install a simple module (replace a file in /sdcard for exemple) with the new default update-binary file:

`#!/sbin/sh
# This is a dummy file that should be replaced with a proper installer script

# If you are creating a module locally for personal usage or testing,
# download the script in the following URL:
# https://github.com/topjohnwu/Magisk/blob/master/scripts/module_installer.sh
# And replace this script with the downloaded script

# Error, this script should always be replaced
exit 1`

The flash falls into error (either via the Manager or via twrp).

If we use the previous module_installer.sh file: https://github.com/topjohnwu/Magisk/blob/master/scripts/module_installer.sh

The flash install successfull (by the manager or by twrp), but it's impossible to boot.

Logcat link: https://github.com/topjohnwu/Magisk/issues/1256#issuecomment-477786334

I updated my modules on the Github repository (almost in blind mode) because I can't test the installations of my modules without having to reinstall everything every time.

I wait your next Magisk version.

**Comment by topjohnwu** [comment]
Apparently you do not know how to use the new format. Unfortunately this repo's issue is not a place for support.
