### ISSUE TITLE
Unable to download any files (except modules) from magisk app

### ISSUE THREAD

**Issue by Prakyy** [topjohnwu/Magisk#1274]
I get around 5kbps speeds when downloading magisk zip or manager apk update from manager app, lol no my data plan is not for 5kbps. I get a solid 5-6 MBps when downloading files through chrome, only slows down to this level when downloading from manager app also never finishes the download always times out.

**Comment by topjohnwu** [comment]
This is an issue with your internet and Github, nothing I can control
