### ISSUE TITLE
[Enhancements] module_installer.sh

### ISSUE THREAD

**Issue by VR-25** [topjohnwu/Magisk#1275]
`$MODPATH/system/placeholder` is NOT removed automatically by the installer. I found this to cause bootloop.

It's best to call `on_install()` right after `mkdir -p $MODPATH` (line 94).

Reasonings
1. This solves the "placeholder" issue.
2. It gives developers more flexibility with installation flags. I personally need to manipulate/process these in `on_install()`.

Lastly, could you please add a variable that stores the primary (live, BOOTMODE) path of the module being installed/updated (e.g., MODPATH_LIVE)? I like the idea of enforced API. This would take it to the next level.

Reasoning
- I want to read information from the installed module (e.g., installed version) for more advanced installation logic (e.g., cleanup, config patching). Sure I can use /sbin/.magisk/img/$MODID or /data/adb/modules/$MODID - but why not have a dedicated variable for such an important path?

**Comment by topjohnwu** [comment]
Regarding the `on_install` location, I agree, so changes done (91da1cf817528d7adea331204c93aa0554fdc7c2)

Regarding the second point: you shouldn't be cleaning up any old modules, because no matter what you do the old module will be completely erased when upgraded. Could you elaborate more about config patching?

**Comment by VR-25** [comment]
By "cleanup", I mean removing obsolete/incompatible module config/data (not stored in /data/adb/modules/). I often need to do that, especially on module downgrades and major upgrades.

Regarding "config patching" - whenever I add/remove stuff to/from a default module configuration file - or update its syntax, the custom (user) config file must be patched to comply with the changes.

For these, I often need to check which version is installed...

`instVer=$(sed -n s/versionCode=//p /sbin/.magisk/$MODID/module.prop)`

`[[ ${instVer:-0} \> $newVer ]] && fart`

**Comment by topjohnwu** [comment]
@VR-25 after a lot of consideration, I figured out that it will be too complicated to provide an "old path". For example when the module is flashed in recovery, the old module will be removed before even running any callback.

It would be easier for me to add support for old module path if all I have to support is imageless modules (a.k.a v19.0+), but unfortunately at this time around I still have to support image based Magisk.

**Comment by VR-25** [comment]
[Alternative] @topjohnwu, I figured instead of checking the installed module version, I'll be checking its config file `versionCode` (contained in the file itself).
With this, I no longer see the need to access the live module path anytime soon.
Thank you.
