### ISSUE TITLE
Magisk Manager App stuck at "mask" loading/launch image from version 7.0

### ISSUE THREAD

**Issue by gu5t3r** [topjohnwu/Magisk#1276]
[logcat_MM.txt](https://github.com/topjohnwu/Magisk/files/3027210/logcat_MM.txt)
Cannot open any Magisk Manager App version starting from 7.0.
Magisk Manager App version 6.1.0 opens and works with magisk 18.1 or 19.0, versions 7.0 or 7.1 stucks at magisk "mask" loading image.

I'm using Xiaomi Redmi Note 4 with latest MIUI10.

**Comment by martyfender** [comment]
Try deleting the apps data in Android settings, apps. While I am at that screen, I also turn on storage permissions. When you do this you will have to go into Magisk Manager settings and redo some of the setting. I have had to do this frequently on recent Canary and Unofficial builds, for some reason. I had to do it today on today's unoffical build.

**Comment by topjohnwu** [comment]
Not using debug build, ignored
