### ISSUE TITLE
Possible future bug for Magisk Manager: background launched activity for Android Q

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/Magisk#1277]
When an app requests root, I see this on Android Q:

![image](https://user-images.githubusercontent.com/5357526/55296058-3450b500-541d-11e9-8f37-1d1fdeca1832.png)

**Comment by topjohnwu** [comment]
Thanks, I'm aware of it....

**Comment by AndroidDeveloperLB** [comment]
@topjohnwu Sorry, I didn't find this being reported here.
