### ISSUE TITLE
Request: for Magisk Manager, add Intent to reach various screens

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/Magisk#1278]
Especially the list of rules for apps to block/grant super-user privilege .

**Comment by topjohnwu** [comment]
What do you want it for? Starting Magisk Manager with an intent with extra
`key="section", value="<the section you want>"` will launch the section

**Comment by topjohnwu** [comment]
The relevant code is here: https://github.com/topjohnwu/Magisk/blob/master/app/src/main/java/com/topjohnwu/magisk/MainActivity.java#L123

**Comment by AndroidDeveloperLB** [comment]
Oh thank you.
As for the question, if the user tells the app to request root, but it was accidentally chosen not to grant it before, I can't request again, so I open the app instead.
