### ISSUE TITLE
Magiskd high CPU usage.

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [topjohnwu/Magisk#1279]
Magiskd is keeping the CPU running high all the time till I disable the magiskhide & re-enable it.
Lineage OS 16.0 here, using Magisk canary 19.0.

Its observed since 18.0 till latest build.
Log here: https://pastebin.com/aL7M8gpK

**Comment by topjohnwu** [comment]
Nothing related to Magisk in logs

**Comment by Olit2000** [comment]
I am facing the same issue. 
It appears right with boot.
I found this line appear in the logs a couple of times:
`--------- beginning of crash`
Rebooting or disable the magiskhide & re-enable it solves it as @Crescendo-BLYAT mentioned

**Comment by yaochx** [comment]
it works, what's happening about this
