### ISSUE TITLE
Magisk Hide breaks app storage

### ISSUE THREAD

**Issue by Unspec7** [topjohnwu/Magisk#1287]
Device: Pixel 3 XL, March Security Update

Magisk version: 19.0
Manager version: 7.1.1

Ever since v19, I have been having continuous issues with system stability. When I first boot up, I am able to clear app storage and cache like normal from the app info page. After a minute or so, it becomes this: [screenshot](https://photos.app.goo.gl/36jxJKXBWBiAANkJ7)

Disabling magisk hide and rebooting fixes the issue, and the screen shows the correct storage space usage even after an hour. [This is what it's supposed to look like](https://photos.app.goo.gl/w2KW1xXzSbvNYXmu9)

When magisk hide is enabled, com.google.android.gms.unstable is perpetually selected in the magisk hide menu. I can deselect it, but as soon as I collapse the tree and expand it again, it is selected. I am also having issues with Google Maps causes System UI crashes, but I am unsure if it is related. When System UI crashes and restarts again, which seems to soft boot the device since it asks for passcode when first unlocking, the storage screen shows the proper values again as well.

**Comment by Didgeridoohan** [comment]
Duplicate: https://github.com/topjohnwu/Magisk/issues/1109
