### ISSUE TITLE
google nexus 5 not support since 19.0

### ISSUE THREAD

**Issue by xuebiao** [topjohnwu/Magisk#1288]
google nexus 5 not support since 19.0 on android 7.1.2

**Comment by Didgeridoohan** [comment]
I find that hard to believe... The  Nexus and Pixel line are the devices that have the least risk of encountering device specific issues.

And, without any kind of details, logs or anything else that show that this actually has anything to do with Magisk and not something you've done with your setup, this issue report will be closed without further comment.

**Comment by VR-25** [comment]
@xuebiao, what exactly are you reporting?
What's the actual issue?
How/why do you think your device isn't supported?

**Comment by topjohnwu** [comment]
I'm personally testing all releases with my Nexus 5X running 6.0.1. I don't think there will be any issues on Nexus/Pixel. And also, no info provided means there is no way I can help you
