### ISSUE TITLE
Possible bug for Magisk Manager pinned shortcut: not updating its icon

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/Magisk#1290]
I had a pinned shortcut to Magisk Manager, and I've noticed today that if I create a new one, the icon seems different.

I think it's a bug, as the icon should change automatically.

**Comment by topjohnwu** [comment]
Sorry, I can't understand your issue

**Comment by AndroidDeveloperLB** [comment]
@topjohnwu 
In the past, I created a pinned shortcut to the "SuperSu" screen on Magisk Manager. It got me a rather blurry icon, which stayed this way till recently.
The bug here is that on some newer version of Magisk Manager, the icon has changed to be have a much high-quality, yet the pinned shortcut hasn't updated itself.
If you wish, I can show you how to solve it.
