### ISSUE TITLE
Request: add option to create pinned shortcut (or normal one for old Android versions) from the settings screen

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/Magisk#1291]
As the title says...
Also, app shortcuts (those that can appear on the launcher's "widgets" list screen) could be nice.

**Comment by topjohnwu** [comment]
If you are on Android 7.1+, you can already access shortcuts when long pressing Magisk Manager's icon. I am not willing to spend any time on creating widget for no practical use

**Comment by AndroidDeveloperLB** [comment]
@topjohnwu I mean here 2 things:
1. Be able to create the pinned shortcuts from within the app.
2. Be able to create normal shortcuts from the launcher's widgets screen, which should work on old Android versions too.

**Comment by AndroidDeveloperLB** [comment]
@topjohnwu I mean here 2 things:
1. Be able to create the pinned shortcuts from within the app.
2. Be able to create normal shortcuts from the launcher's widgets screen, which should work on old Android versions too.

Why do you close it? I think it could be nice to have multiple ways to reach those, and it's not hard at all (especially the pinned shortcut creation)....
I can help you if you wish...

**Comment by Didgeridoohan** [comment]
@AndroidDeveloperLB If you have something to contribute, create a pull request with your proposed improvements instead of opening an issue.

**Comment by AndroidDeveloperLB** [comment]
@Didgeridoohan Good idea. I tried now, but it fails to be built:

![image](https://user-images.githubusercontent.com/5357526/55433871-f8ddf400-559e-11e9-9e71-ef4c9a590338.png)

Any idea why this occurs ?
