### ISSUE TITLE
A320F mount data

### ISSUE THREAD

**Issue by AK2H** [topjohnwu/Magisk#1293]
Samsung Galaxy A3 2017 Stock Oreo
data partition can not be mounted after flashing patched-boot.img even if I do a factory reset it will be encrypted again after booting into OS
this problem occur only with Magisk,
with SuperSU data can be mounted.
Stock Boot.img attached:
[boot.zip](https://github.com/topjohnwu/Magisk/files/3040326/boot.zip)

**Comment by topjohnwu** [comment]
Flash Magisk with force data encryption disabled

**Comment by AK2H** [comment]
previous forced data encryption disable did not work,
however this morning I found this: [https://zackptg5.com/android.php#disverfe](url)
I flashed this after flashing patched-boot.img (Magisk.zip resulted with error) and it worked!
