### ISSUE TITLE
Magisk Manager 7.1.1 does not see Magisk installed

### ISSUE THREAD

**Issue by madduck** [topjohnwu/Magisk#1298]
I have magisk 18.1 running, and the previous manager version 6.1 shows that. However, the 7.1.1 manager claims that magisk is not installed.

![Screenshot_20190404-192810_Magisk Manager](https://user-images.githubusercontent.com/195073/55576667-1d0e1200-5712-11e9-8177-651682968b03.jpg)

![Screenshot_20190404-193648_Magisk Manager](https://user-images.githubusercontent.com/195073/55576690-27301080-5712-11e9-838a-cc5f3d78b6e7.jpg)

**Comment by madduck** [comment]
Why are you closing this issue without any comment, @topjohnwu?

**Comment by keeferrourke** [comment]
Hey @madduck I had a similar issue. Perhaps https://github.com/topjohnwu/Magisk/issues/1265 is related?

Also confused why this (and so many other issues) was closed without comment. Really makes troubleshooting a pain when you have to dig through random closed issues :/
