### ISSUE TITLE
flash v9 got bootloop (v8 work fine)

### ISSUE THREAD

**Issue by twu2** [topjohnwu/Magisk#13]
If upgrade from Magisk Manager, it will boot without issue. But need to re-install phh's superuser again (some program can't detect root, but some can).

If flash v9 zip in recovery (with or without uninstall first), the patched boot.img can't boot, will get bootloop. Also can't boot into recovery, need to flash the normal boot.img to bring the system back.

Device is Xiaomi Redmi Note2.

**Comment by Rahh1112** [comment]
I can confirm this issue on my ghost (motorola moto x 2013). The only diff from the issue described by twu2 is that support for motorola devices was added in v9.. so magisk doesn't work with versions < v9

**Comment by twu2** [comment]
I found  the reason why it's not work for me.
My device is arm64, but the TWRP is built for arm32.  '/tmp/magisk/arm64/bootimgtools' execute failed. 
So the boot partition will be filled by 0 after flash the patched boot.img.

`Installing zip file '/external_sd/Magisk-v9.zip'
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
I:Zip does not contain SELinux file_contexts file in its root.
I:Legacy property environment initialized.
Archive:  /external_sd/Magisk-v9.zip
  inflating: META-INF/MANIFEST.MF
  inflating: META-INF/CERT.SF
  inflating: META-INF/CERT.RSA
  inflating: META-INF/com/google/android/update-binary
  inflating: META-INF/com/google/android/updater-script
  inflating: arm/bootimgtools
  inflating: arm/busybox
  inflating: arm/magiskhide
  inflating: arm/resetprop
  inflating: arm/sepolicy-inject
  inflating: arm64/bootimgtools
  inflating: arm64/busybox
  inflating: arm64/magiskhide
  inflating: arm64/resetprop
  inflating: arm64/sepolicy-inject
  inflating: chromeos/futility
  inflating: chromeos/kernel.keyblock
  inflating: chromeos/kernel_data_key.vbprivk
  inflating: common/custom_ramdisk_patch.sh
  inflating: common/file_contexts_image
  inflating: common/init.magisk.rc
  inflating: common/magic_mask.sh
  inflating: common/magiskhide/add
  inflating: common/magiskhide/list
  inflating: common/magiskhide/rm
  inflating: x64/bootimgtools
  inflating: x64/busybox
  inflating: x64/magiskhide
  inflating: x64/resetprop
  inflating: x64/sepolicy-inject
  inflating: x86/bootimgtools
  inflating: x86/busybox
  inflating: x86/magiskhide
  inflating: x86/resetprop
  inflating: x86/sepolicy-inject
*****************************
Magisk v9 Boot Image Patcher
*****************************
- Mounting /system(ro), /cache, /data
- Device platform: arm64
chmod: /futility: No such file or directory
- Constructing environment
- /data/magisk.img detected!
mknod: /dev/block/loop0: File exists
- Mounting /data/magisk.img to /magisk
- Found Boot Image: /dev/block/mmcblk0p7
- Unpacking boot image
CANNOT LINK EXECUTABLE: could not load library "libc.so" needed by "/tmp/magisk/arm64/bootimgtools"; caused by "libc.so" is 32-bit instead of 64-bit
/tmp/updater: line 333: can't open /tmp/boottmp/bootunpack/ramdisk.gz: no such file
- Creating backups
32768+0 records in
32768+0 records out
16777216 bytes (16.0MB) copied, 0.266820 seconds, 60.0MB/s
- Patching ramdisk
grep: init*.rc: No such file or directory
sh: 0: unknown operand
sed: init.rc: No such file or directory
CANNOT LINK EXECUTABLE: could not load library "libc.so" needed by "/tmp/magisk/arm64/sepolicy-inject"; caused by "libc.so" is 32-bit instead of 64-bit
cp: can't create 'sbin/magic_mask.sh': No such file or directory
chmod: sbin/magic_mask.sh: No such file or directory
- Repacking boot image
CANNOT LINK EXECUTABLE: could not load library "libc.so" needed by "/tmp/magisk/arm64/bootimgtools"; caused by "libc.so" is 32-bit instead of 64-bit
mv: can't rename 'new-boot.img': No such file or directory
CANNOT LINK EXECUTABLE: could not load library "libc.so" needed by "/tmp/magisk/arm64/bootimgtools"; caused by "libc.so" is 32-bit instead of 64-bit
ls: /tmp/boottmp/new-boot.img: No such file or directory
sh: bad number
chmod: /tmp/boottmp/new-boot.img: No such file or directory
- Flashing new boot image
dd: can't open '/tmp/boottmp/new-boot.img': No such file or directory
- Unmounting partitions
losetup: /dev/block/loop0: No such device or address
- Done
I:Updater process ended with RC=0
I:Legacy property environment disabled.
Updating partition details...
I:Data backup size is 7626MB, free: 1851MB.
I:Unable to mount '/usbotg'
I:Actual block device: '', current file system: 'auto'
...done
I:Set page: 'flash_done'
I:operation_end - status=0
`

**Comment by topjohnwu** [comment]
Yes, I changed to dynamic linking.
Will force link to /system/lib64 in the next release, thanks for reporting!
