### ISSUE TITLE
Samsung SM-N9005, Rooted but no root permission

### ISSUE THREAD

**Issue by RomikB** [topjohnwu/Magisk#130]
Samsung Galaxy Note 3 (SM-N9005) Stock Android 5.0
Magisk v11.6
Rooted but no root permission
[install_log.txt](https://github.com/topjohnwu/Magisk/files/862045/install_log.txt)
[magisk.log.txt](https://github.com/topjohnwu/Magisk/files/862046/magisk.log.txt)

**Comment by thassan** [comment]
just the obvious, have you enabled Superuser access for "Apps and ADB" in MagiskManager -> Settings?

**Comment by RomikB** [comment]
This setting not available Magisk Settings in this state.

**Comment by Tr4il** [comment]
I'm experiencing the exact same issue as RomikB on my OnePlus One. Running Sultan 6.0.1, with systemless xposed. MagiskSU is enabled according to the Magisk Manager, but apps like AdAway and Titanium Backup cannot gain root access. 
Attached is a boot partition backup where this is the case.
[botchedboot2017-03-23--11-36-50.zip](https://github.com/topjohnwu/Magisk/files/864844/botchedboot2017-03-23--11-36-50.zip)

**Comment by topjohnwu** [comment]
Samsung issues are all fixed
