### ISSUE TITLE
SafetyNet and Google Pay are working fine with 19.0

### ISSUE THREAD

**Issue by Cubox-** [topjohnwu/Magisk#1301]
Since you are getting so many reports about things being broken, here is my experience:

After installing the Canary version and making everything break, with Google Play Services crashing when any app was trying to use SafetyNet, I decided to factory reset and start again.

Without any issue, SafetyNet is working perfectly, no need to change anything in MagiskHide.
Google Pay is also working well, with nothing required to do so.

Thanks for your work. For anyone having an issue, try doing a factory reset, it really helps.

This is using MagiskManager 7.1.1 and Magisk 19.0 (not Canary) on a Razer phone, running OEM system image.

**Comment by topjohnwu** [comment]
Thx
