### ISSUE TITLE
Bug: confirmation dialog disappears upon configuration change (like orientation change)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/Magisk#1302]
Try any app that requests root permission. Example this simple repo:

https://github.com/AndroidDeveloperLB/RootHelper

Then try to change orientation, and the confirmation dialog of Magisk is closed, thinking as if I chose not to grant the permission.

Please fix this issue.

**Comment by AndroidDeveloperLB** [comment]
@topjohnwu Why close it? You fixed it? Is it now fixed on the official app ? You couldn't reproduce it?
Please explain what is going on.

**Comment by Displax** [comment]
[This](https://github.com/topjohnwu/Magisk/commit/96127f8bd19294dca9082952a9c93a4d77fddfe6) commit is your fix.

**Comment by AndroidDeveloperLB** [comment]
@Displax Not mine. 
Screen orientation locking isn't a good solution. It was just an example of how it gets dismissed as if I chose an option. It's more of a workaround. Instead of supporting configuration change (which includes orientation change, for example) , you lock the orientation ...

Also, I think screen locking (using `setRequestedOrientation`) is problematic on a very specific version of Android (8.0, as I remember), as it might cause crashes. I remember it was reported to Google, after they themselves got this issue on Admob SDK. Maybe this could show it (I remember it somewhere else though) :
https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/xQ4rql_jexc
I think it was also asked about on StackOverflow.

So, this is not a good fix. Please don't close the issue.
