### ISSUE TITLE
Bug: Installing Magisk v19.0 on Samsung Galaxy S5 with LineageOS 16 cause boot in Download mode

### ISSUE THREAD

**Issue by kambei** [topjohnwu/Magisk#1303]
I have a Samsung Galaxy S5 with Lineage OS 16 installed.
If i install, via TWRP, Magisk v19.0 it cause a boot in Download Mode.

Uninstalling it, make my S5 boot again!

**Comment by kambei** [comment]
Version v18.1 working fine!!!

**Comment by kill0rz** [comment]
#1256

**Comment by aliabdoh1** [comment]
مشكورين
