### ISSUE TITLE
Shells forked by Magisk drain my cpu/battery

### ISSUE THREAD

**Issue by ElCoyote27** [topjohnwu/Magisk#1306]
Hi,
First of all, thanks for Magisk. Without its 'Hide' mode, I wouldn't be able to use -one- app from which I need to hide that my phone is running LIneageOS.
Here's my setup:
- Xiaomi Mi Mix (256gb/6gb/4 cores)
- TWRP 3.2.1
- LineageOS 15.1 (20190406)
- Magisk 7.1.1 / 19.0

Everytime the phone reboots, I have to go kill the /system/bin/sh processes that Magisk spawns if I want to keep my phone responsive and its battery undrained.

Is this because I'm using 'Hide' (for one app)?
Does Magisk close the Shell.Su it invokes when the process terminates? (this is well known to cause rogue processes).

**Comment by topjohnwu** [comment]
Yes in normal conditions, but there are ways to create a process that is unkillable easily with root, and there is no way around it

**Comment by ElCoyote27** [comment]
@topjohnwu Would you mind providing further details? What do you mean that there is no way around it? Is it a limitation of Magisk Shell.Su routines?
Can you confirm if this is because I'm using Magisk Hide or unrelated to this?
