### ISSUE TITLE
Samsung S10 (Chinese version) cannot root with  Canary magisk

### ISSUE THREAD

**Issue by shuajinanhai** [topjohnwu/Magisk#1307]
hello，topjohnwu，i try  root my S10 (Chinese version)  with  Canary magisk , But it failed.  Why did S10（Exynos ）succeed? Samsung S10 (Chinese version) cannot

**Comment by shuajinanhai** [comment]
英语不好，直接用中文了哈，你好，topjohnwu，看了你对韩版S10 root的处理教程，非常独特，我也按照你的教程尝试对中国版本的S10进行root,但是进不去系统，也进不去recovery，还会无限重启，能否分析下中国版本的S10还有什么验证吗

**Comment by shuajinanhai** [comment]
我已经成功root了，现在开始做TWRP

**Comment by topjohnwu** [comment]
Nice

**Comment by rp4k** [comment]
@shuajinanhai 你可以给我你的微信。我想root。 HK S10+ 但是应用修补后的.tar文件后，无法使电话进入系统恢复。

**Comment by rp4k** [comment]
> 英语不好，直接用中文了哈，你好，topjohnwu，看了你对韩版S10 root的处理教程，非常独特，我也按照你的教程尝试对中国版本的S10进行root,但是进不去系统，也进不去recovery，还会无限重启，能否分析下中国版本的S10还有什么验证吗

我们已经尝试了很多次，但无法让手机启动到系统“recovery”中。您是怎么做到的？

we have tried several times and we can not get the phone to boot into system recovery after applying the patched  .tar file    HK  s10+  SM-G9750 .  what are we doing wrong?

**Comment by WestlifeBG** [comment]
@shuajinanhai你可以给我你的微信。我想根。香港S10 +但是应用修补后的. tar文件后,无法使电话进入系统恢复。我也想给我的港版s10+root

**Comment by rp4k** [comment]
Westlifebg  if you use wechat let's start a group add me rp4000

**Comment by rp4k** [comment]
I worked together with @westlifebg  and the button combination to get into stock recovery does not work. Any other suggestions @topjohnwu

**Comment by esinker** [comment]
记录下这个问题，我解决它了，需要清除下cache 按住 音量下键，关机键，还用Bixby 键 进入简单的recovery 清除缓存
