### ISSUE TITLE
19004 stuck at booting logo

### ISSUE THREAD

**Issue by 805447391** [topjohnwu/Magisk#1310]
19000,19001,19002 work fine for my decice， but when i upgrade to 19003，it stucks at boot logo page again and again，i have to reflash 19002 for booting.

**Comment by Jonikx** [comment]
...

**Comment by 805447391** [comment]
solved，reflashed 19003

**Comment by 805447391** [comment]
reopened, it seems like this problems remains.
Device: chiron
ROM: LineageOS 15.1
Magisk: 19004
Problem: power on ---> show Mi logo ----> stuck.....about 1 min   -----> auto reboot to fastboot  -----> force reboot by long press power key ------> show Mi logo  -------> boot normally (required 2~3 times rebooting)
