### ISSUE TITLE
實現刪除文件的方法

### ISSUE THREAD

**Issue by fsxitutu** [topjohnwu/Magisk#1313]
通過觀察可知magisk(version:18.1)對被替換文件所在的目錄掛載到tmpfs，並在其中創建空文件，最後把文件（來自系統或模塊）綁定掛載到這些空文件上。從而實現修改/system目錄。
未來能否添加功能在引導時不掛載相關文件，是否就可以相當於實現“刪除”呢？
此方法我已經進行測試是可行的。我製作了一個模塊，往/system中一個子目錄放置一個文件，然後通過service.sh腳本umount這個文件和我需要“刪除”的文件，最後rm這兩個文件。設備啟動後這兩個文件在/system中已無法找到了。
刪除目錄同理。

**Comment by topjohnwu** [comment]
文檔中已經提及，實際刪除文件是不必要的，只需要把原文件替換成空白檔案即可達成一樣的效果。
