### ISSUE TITLE
Enhancement of .disable_magisk

### ISSUE THREAD

**Issue by michal-mike** [topjohnwu/Magisk#1315]
User has root access gained via Magisk patched recovery boot image (example new Huawei Mate 20 Pro, P30...).  User installs offending module which causes bootfreeze or bootloop.  Device has no custom recovery (and there is no such recovery available for given device). E.g. Mate 20 Pro has a bootlegged TWRP available which cannot handle encrypted filesystem. So effectively no TWRP for users who went with encrypted filesystem.  User is doomed in such situation. Cannot gain root, so not even write .disable_magisk file into /cache.

What if the file .disable_magisk could be placed for instance in root of internal storage or sdcard?
I can hear the argument that this feature could be misused by any user app having storage permission. But an attacker would not gain anything interesting. Assume we want it more under control, so maybe this is a good scenario?
- Magisk Manager allows a recovery keyword to be set under Settings; hash will be saved in Magisk directory
- In case of need for recovery the device owner could place a plain-text file .disable_magisk containing that keyword (or in case of a paranoid owner just the hash of that keyword generated externally on a trusted device)
- Magisk looks for that file during boot, if found, hashes are compared, if match => Magisk skips loading of custom modules

**Comment by topjohnwu** [comment]
#1286
