### ISSUE TITLE
Bug: Magisk causes bootloop on Mi 8 (MIUI 10) upon completing "Additional setup"/installing through TWRP

### ISSUE THREAD

**Issue by JarlPenguin** [topjohnwu/Magisk#1316]
Magisk installs successfully through patched boot image, but upon completing "Additional setup" in Magisk Manager and rebooting, device bootloops. Uninstalling Magisk through TWRP and reinstalling while not completing "Additional setup" fixes this issue. 

When installing Magisk through TWRP and rebooting, the device also bootloops. This can be fixed by installing Magisk normally, then running the uninstaller, which strangely does not uninstall Magisk.

Xiaomi Mi 8 (dipper)
MIUI 10.2.3.0 Global Stable
Magisk 19.0-82ea9db9
Magisk Manger 7.1.1-da3937ff

**Comment by topjohnwu** [comment]
You do not provide any logs regarding the bootloop, how would I help?

**Comment by JarlPenguin** [comment]
Going to the Magisk tab in the Logs section of Magisk manager yields no logs to save.
