### ISSUE TITLE
Why does it contact github very regularly?

### ISSUE THREAD

**Issue by OhSoGood** [topjohnwu/Magisk#1320]
On both Lineageos 16.0 and 15.1 for S7 (from https://forum.xda-developers.com/galaxy-s7/development/beta-lineageos-16-0-s7-herolte-t3842465), I've only installed twrp + the rom (after a full wipe) + Magisk 18.1 (from this site) + afwall. And I'm very surprised to see that afwall is very regularly blocking connections from the kernel to github (likely to raw.githubusercontent.com), something like 70 blocked connections in one hour to a single IP address, plus 4-5 other IP addresses. 

So, it's either the rom or Magisk who is contacting github. But for what? And is it well-known and documented? 

If I missed that info, that's all my fault. But if that's a 'secret' feature', I don't really like it...

**Comment by Didgeridoohan** [comment]
The Magisk files are stored on GitHub, so whenever the Manager checks for an update, it'll have to make a connection to the GitHub servers...

**Comment by topjohnwu** [comment]
@OhSoGood everytime you open Magisk Manager, it will access `raw.githubusercontent.com` once for checking Magisk updates, once to the Github APIs for checking module updates, and if there is a module upgrade on the repo, and an additional N times to `raw.githubusercontent.com` where N is the number of modules available.

**Comment by topjohnwu** [comment]
All requests are `GET` requests. If you know any networking, you will know `GET` does not send any information, it only request data from servers, like downloading files or browsing a web page

**Comment by OhSoGood** [comment]
@topjohnwu : Thank you very much for the clarification, that sounds all legit and normal indeed. I had not read it in XDA or on this github repo, hence my worry. Actually (maybe an issue with afwall), these connections appears in afwall as issued by kernel and not magisk manager, which was a little weird.
