### ISSUE TITLE
Magisk Manager  shows old version as newest

### ISSUE THREAD

**Issue by ovz93br43v7** [topjohnwu/Magisk#1328]
Hello,
nothing really important, but probably interesting: 

I have installed the newest versions from github (Magisk v19 and Magisk Manager v7.1.1).
When I open Magisk Manager it shows me as newest version of Magisk v18.1 and as installed version Magsik v19.0)

Regards

**Comment by Didgeridoohan** [comment]
Take a look at the update channel in the Manager settings (stable is still at v18.1, beta is v19.0), and then you can close this.

**Comment by ovz93br43v7** [comment]
Ok sorry.
