### ISSUE TITLE
Error avb1.0 Sign     Error code Signature is INVALID

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#1332]
Hello, I found a big bug. Recovery flash magisk.zip
There is something wrong with this code.
Incorrect detection boot.img AVB 1.0 sign
`eval $BOOTSIGNER -verify < $BOOTIMAGE && BOOTSIGNED=true`

recovery.log :

- Current boot slot: _b
- Mounting /system, /vendor
- Device is system-as-root
- System-as-root, keep dm/avb-verity
- Encrypted data, keep forceencrypt
- Target image: /dev/block/mmcblk0p13
- Device platform: arm64
- Constructing environment
Signature is INVALID
- Unpacking boot image
Parsing boot image: [/dev/block/mmcblk0p13]
HEADER_VER      [0]
KERNEL_SZ       [45179111]
RAMDISK_SZ      [10498379]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
DTB             [0]
OS_VERSION      [8.1.0]
OS_PATCH_LEVEL  [2018-12]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200,n8 androidboot.console=ttyMSM0 earlycon=msm_serial_dm,0xc170000 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 sched_enable_hmp=1 sched_enable_power_aware=1 service_locator.enable=1 swiotlb=1 androidboot.configfs=true androidboot.usbcontroller=a800000.dwc3 androidboot.selinux=permissive veritykeyid=id:78df5491771b144d524ffb34bc9a6cf321c15adf buildvariant=eng veritykeyid=id:7e4333f9bba00adfe0ede979e28ed1920492b40f]
CHECKSUM        [83cd03ea0492d990ed6aa7fc2a624b758d81239e]
KERNEL_DTB      [34243618]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [lzma]
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Backing up stock boot image
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Patch @ 017F71B0 [736B69705F696E697472616D667300]->[77616E745F696E697472616D667300]
- Repacking boot image
Parsing boot image: [/dev/block/mmcblk0p13]
HEADER_VER      [0]
KERNEL_SZ       [45179111]
RAMDISK_SZ      [10498379]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
DTB             [0]
OS_VERSION      [8.1.0]
OS_PATCH_LEVEL  [2018-12]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200,n8 androidboot.console=ttyMSM0 earlycon=msm_serial_dm,0xc170000 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 sched_enable_hmp=1 sched_enable_power_aware=1 service_locator.enable=1 swiotlb=1 androidboot.configfs=true androidboot.usbcontroller=a800000.dwc3 androidboot.selinux=permissive veritykeyid=id:78df5491771b144d524ffb34bc9a6cf321c15adf buildvariant=eng veritykeyid=id:7e4333f9bba00adfe0ede979e28ed1920492b40f]
CHECKSUM        [83cd03ea0492d990ed6aa7fc2a624b758d81239e]
KERNEL_DTB      [34243618]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [lzma]
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [45183719]
RAMDISK_SZ      [10286557]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
DTB             [0]
OS_VERSION      [8.1.0]
OS_PATCH_LEVEL  [2018-12]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200,n8 androidboot.console=ttyMSM0 earlycon=msm_serial_dm,0xc170000 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 sched_enable_hmp=1 sched_enable_power_aware=1 service_locator.enable=1 swiotlb=1 androidboot.configfs=true androidboot.usbcontroller=a800000.dwc3 androidboot.selinux=permissive veritykeyid=id:78df5491771b144d524ffb34bc9a6cf321c15adf buildvariant=eng veritykeyid=id:7e4333f9bba00adfe0ede979e28ed1920492b40f]
CHECKSUM        [385eaee755c86efd2a6cb57ad8daba388fda0edf]
- Flashing new boot image
Cleaning up...
- Unmounting partitions
- Done
I:Updater process ended with RC=0`

According to my many tests. Many Android phones can't stay AVB 1.0 Sign
Use AIK unpackimg.bat magiskv19.0.zip out boot.img  Non-existent  split_img/boot.img-sigtype and split_img/boot.img-avbtype
I'm very sorry about my English.Thank you for your efforts.

**Comment by androiddisk** [comment]
Error code Signature is INVALID

**Comment by topjohnwu** [comment]
That error message is NOT an error, it is simply reporting that the image is not signed. And also, not all images needed to be signed.

**Comment by jgratero** [comment]
Is there an archive available for the previous versions (apk and zip) for Magisk?
