### ISSUE TITLE
EMUI 9 booting into recovery with latest canary

### ISSUE THREAD

**Issue by GtrCraft** [topjohnwu/Magisk#1335]
I can't seem to boot in twrp with a magisk patch twrp image in the latest canary (holding volume up) on Berkeley EMUI 9.
I thought it was implemented recently, or am I doing something wrong?

**Comment by topjohnwu** [comment]
I tried and found out that Huawei's kernel does not receive events on boot. Unfortunately this can't be fixed on Magisk's side
