### ISSUE TITLE
麻煩再看一下我的問題。avb1.0檢測簽名可能真的有問題

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#1336]
我昨天迴響的問題其實我沒有表達清楚，同一個boot.img通過Magisk Manager修補的boot.img會保留avb 1.0簽名。但是recovery刷出來卻不會保留avb1.0簽名。

所以我覺得是recovery判斷是否需要avb1.0的命令需要陞級。我的設備是紅米3s雖然不會囙此開機卡屏。但是在Nubia z17上會出現開機卡屏。需要單獨刷一個簽名才能開機

**Comment by androiddisk** [comment]
很抱歉麻煩到你了。但是我遇到的問題可能只有你懂。如果你能回答一下我，我會非常感謝。

為什麼存在/system_root/ini.rc的強制KEEPVERITY=true。是這種檔案格式不能完美去除KEEPVERITY麼？

更奇怪的是我居然還是能够修改system分區正常使用。不應該卡屏才對嘛

**Comment by topjohnwu** [comment]
Recovery 執行 `dalvikvm` 有很高的機率會失敗 (custom recovery 很蛋疼的....)，所有簽名/認證都是跑 Magisk Manager 裡面的 java code，因此環境要能夠啟動 Android runtime 才有辦法。

如果你的裝置是使用 system-as-root (看起來就是)，那用 Magisk 啟動之後系統自動就不會跑 AVB ，但是其他得分區仍然會進行認證。若要完全去掉 AVB，最簡單的方式就是把 vbmeta 替換成無認證的 image (此方法我尚未推送到非 Galaxy S10 手機上，不過未來將會正式支援)

**Comment by androiddisk** [comment]
感谢解答
