### ISSUE TITLE
P10 android Pie touch issues

### ISSUE THREAD

**Issue by neoxxx85** [topjohnwu/Magisk#1337]
If i boot my vtr-l09c432 in normal way [power] , i have android 9 without root and touch work fine. 
If i boot with [vol+] + [power] from recovery workaround android start with right privileges and magisk work fine but from now the touchscreen no work at extreme left and right borders for all height display, boring problem in keyboard and navigation top bar.
ps: i have manual patched my original extract recovery_ramdisk.img from update.app with magisk 18 and beta19, some result.

**Comment by neoxxx85** [comment]
Find solution to fix bug:

from root shell: stop aptouch

**Comment by bernie99899** [comment]
I have the same issue with Magisk 20.
Every time I reboot I had to stopaptouch by root shell.

Have you solve it in another way??
