### ISSUE TITLE
MagiskHide does not hide /sbin/su binary

### ISSUE THREAD

**Issue by cobbr** [topjohnwu/Magisk#134]
Hi, thanks for the great project!

I'm currently testing an Android app that attempts to detect root by calling the system command `which su`. Even with MagiskHide enabled for the application itself and for the shell, the command is successful and returns `/sbin/su`. The app additionally checks for the existence of a file called `/sbin/su`.

I considered a trivial bypass by temporarily renaming the `su` binary, but as soon as I do that, Magisk fails to detect that the phone is rooted and appears to disable MagiskHide all-together.

Would it be possible to have MagiskHide hide the `/sbin/su` binary?

Would also appreciate any work-around suggestions.

**Comment by thassan** [comment]
First make sure your ROM does not already come with root installed.. for magiskhide to work, magisk must be installed on a clean , unrooted system, to install its own MagiskSU, which is magiskhide'able 8-)
post magisk.log , and tell whether you're passing safetynet checks otherwise.
Android version and kernel version would be useful too

**Comment by cobbr** [comment]
So I think I was making a dumb mistake here. It appears the app was using an Android permission to control the phone app, and was having the phone make shell calls on its behalf. Adding the phone applications to the MagiskHide list successfully hid root from the application.

This seems like a very strange root detection method to me, and it seems odd that a permission to control the phone allows an app to make shell calls as the phone app. Does anyone with more Android background than me know how this is possible from a security perspective?

In any case, that question is not Magisk related. Feel free to close this issue.
