### ISSUE TITLE
Installing Magisk after unrooting SuperSU

### ISSUE THREAD

**Issue by danjde** [topjohnwu/Magisk#1340]
Hi Devs!
I've installed [LineageOS 15.1](https://forum.xda-developers.com/galaxy-s3-neo/orig-development/dev-lineageos-15-1-galaxy-s3-neo-t3795428) on Samsuns S3 Neo I9301I  and then SuperSU. Then I've encrypted the phone (data)
I've removed manually via adb root every SuperSU pieces, but now trying to install from TWRP Magisk, obtain the error:

> Boot image patched by unsupported programs, please restore stock boot image.

Is it LineageOS 15.1 (Oreo 10.1) supported by Magisk stable version?
How could I solve this issue and install latest stable Magisk? :-)

[Here](https://www.cosmogonia.org/owncloud/index.php/s/EjpbAToagkNNnBS) my boot.img

Many thanks!

Davide

**Comment by DenyDarko** [comment]
Well it's obvious isn't it?

You need to restore an original boot.img for your device by using your favorite method.

Then magisk will work. 

This is XDA material though, not for the bug tracker as it's not a bug.
