### ISSUE TITLE
avb1.0签名的识别问题已经得到解决 请加入代码

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#1341]
代码来自supersu
BOOTSIGNER="/system/bin/dalvikvm -Xbootclasspath:/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/bouncycastle.jar -Xnodex2oat -Xnoimage-dex2oat -cp \$APK \$BOOTSIGNERCLASS"

`-Xbootclasspath:/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/bouncycastle.jar`
主要是加了这一段 本来不能检测到avb1.0的机器 现在能够检测了。 

另外请教一下 vbmeta 中的avb2.0校验 听朋友说在解锁BL的时候就已经关闭了。不需要管avb2.0校验了。同时另一位朋友发了一份avbtool生成的vbmeta.img 据说通用屏蔽avb2.0. 那我是应该解锁后就不用管avb2.0还是刷入通用屏蔽vbmeta.img。 又来麻烦你了 谢谢

[vbmeta.zip](https://github.com/topjohnwu/Magisk/files/3081375/vbmeta.zip)

**Comment by topjohnwu** [comment]
感謝回報

另外，vbmeta 生成已經在 code 中
https://github.com/topjohnwu/Magisk/blob/master/app/src/main/java/com/topjohnwu/magisk/tasks/MagiskInstaller.java#L202

**Comment by androiddisk** [comment]
厉害 感谢你的付出
