### ISSUE TITLE
Pixel xl - marlin bootloop

### ISSUE THREAD

**Issue by Darkcast** [topjohnwu/Magisk#1343]
Hi

I have a pixel xl running android 9.0.0 (PQ2A.190405.003, Apr 2019) and twrp 3.3.0.0.
When installed magisk beta 19.0  my phone got boot looped and it returns to the twrp recovery screen. 

I fixed it by running the magisk Uninstaller and just to make sure it wasn't an issue I tried installing the 18.0 version and it soft bricked my phone I had to do a dirty flash of the stock rom to get it to work.

I was wondering if you this has been reported yet and if there is a fix for it.

Thanks 

Thanks

**Comment by Darkcast** [comment]
why did you close my issue ? I was doing more testing and getting logs ?

**Comment by topjohnwu** [comment]
Because I have a Pixel XL, and it has no issues

**Comment by Darkcast** [comment]
that is strange, what do you suggest I do then ?
