### ISSUE TITLE
Defex Security  problems with Sm-J415F  

### ISSUE THREAD

**Issue by Kopra159** [topjohnwu/Magisk#1345]
I tried  many but deffex  security  still enable ,
1-Many apps run as root doesn't  work .
2-I made my own kernel   and I need to test it but deffex  security  .

**Comment by Kopra159** [comment]
@topjohnwu

**Comment by topjohnwu** [comment]
This is weird, the Defex hex patch works on the latest S10+. I don't think there are new forms of Defex introduced

**Comment by Kopra159** [comment]
I tested magisk  19 .
Defex security  stil as it many apps can't  run .

**Comment by Kopra159** [comment]
Also i Tested  Canary

**Comment by Kopra159** [comment]
@topjohnwu 
Ok, Any help I can upload any files  u need ,please  this is big issue  many apps doesn't  work also phone  slow with root and  I am used  to use firewall .

**Comment by Kopra159** [comment]
@topjohnwu 
Sorry  for  disturb  U but I don't  lie see 
![Screenshot_20190418-014817_Magisk Manager](https://user-images.githubusercontent.com/48631763/56327908-cde9c780-617c-11e9-882e-3c0eba420080.jpg)
![Screenshot_20190418-014831_Magisk Manager](https://user-images.githubusercontent.com/48631763/56327909-ce825e00-617c-11e9-9664-0d4dd47bd20e.jpg)
![Screenshot_20190418-014824_Linux Deploy](https://user-images.githubusercontent.com/48631763/56327910-ce825e00-617c-11e9-995a-cfbae57ed122.jpg)
