### ISSUE TITLE
Magisk Canary Samsung Galaxy S10 - SM-G97x0 HK/Chinese Versions

### ISSUE THREAD

**Issue by Fzndox** [topjohnwu/Magisk#1346]
This is on behalf of XDA-developers forums and the following 2 threads regarding Majisk root on the SM-G97x0 versions:

Background:
https://forum.xda-developers.com/galaxy-s10/how-to/snapdragon-root-waiting-discussion-t3919024
and
https://forum.xda-developers.com/galaxy-s10/development/magisk-root-galaxy-s10-series-t3918699

Specifics:
The issue appears when following the original S10 guide here: https://topjohnwu.github.io/Magisk/samsung
Users are having issues and are getting stuck with step 9, reported starting on pages 6-9 here:
https://forum.xda-developers.com/galaxy-s10/how-to/snapdragon-root-waiting-discussion-t3919024/page6

Theory:
We suspect the magisk_patched.tar is breaking the ability to boot to stock recovery or recovery partition and only minor modifications may be required for a successful root. We are asking SM-G97x0 users to produce a log file to provide further supporting documentation. Restoring to stock firmware restores the ability to boot to stock recovery.

Inputs:
If we are able to obtain a log file, it will be attached to this document.

**Comment by Fzndox** [comment]
Just to add, not sure what this guy did to get his root working correctly:
我已经成功root了，现在开始做TWRP

_Originally posted by @shuajinanhai in https://github.com/topjohnwu/Magisk/issues/1307#issuecomment-480554664_

**Comment by rp4k** [comment]
After applying the patched .tar for step 9 we need to go into stock recovery to preform a factory reset. But the phone refuses to listen to the button combination.
To confirm this is only after the patch is applied. I is flashed stock firmware in Odin and the button combination works fine to get into stock recovery.

Nobody on the XDA forums i can confirm can get it into  Stock Recovery    everyone is using the HK S10 Series  i have tried personally on the SM-G9750 S10+  and can confirm the phone will not boot into stock recovery after the patch has been applied.

**Comment by dannya726** [comment]
No one who has said they got root working on the HK has ever provided any proof, so it's safe to say it hasn't happened.

**Comment by chrisjoinme42** [comment]
I confirm the same problem with the samsung series s10 s10e sm-g9700 hk snapdragon I tried all the variants of buttons in step 9 we were blocking :(

**Comment by rp4k** [comment]
@chrisjoinme42  how about downloading the Chinese firmware  .  CSC  :  chc 

Flash the stock firmware first in Odin then  patch it with magisk.  Since the guy before said he had used the Chinese firmware.

**Comment by chrisjoinme42** [comment]
I do not understand sorry :(

**Comment by rp4k** [comment]
The button combination for stock recovery doesn't work @topjohnwu

**Comment by Arkhypov** [comment]
@rp4k @topjohnwu any updates on this issue? I am getting same problem with SM-G9750.
I could not get into stock recovery after patch..

**Comment by Arkhypov** [comment]
> @rp4k @topjohnwu any updates on this issue? I am getting same problem with SM-G9750.
> I could not get into stock recovery after patch..

Fixed my problem by using this magisk manager:
https://github.com/ianmacd/MagiskBuilds/blob/master/MagiskManager-v7.3.3-2019081202-ianmacd.apk
