### ISSUE TITLE
Hong Kong s10+  SM-G9750   stock recovery issue

### ISSUE THREAD

**Issue by rp4k** [topjohnwu/Magisk#1347]
After applying the patched .tar  for step 9 we need to go into stock recovery to preform a factory reset.  But the phone refuses to listen to the button combination.  
To confirm this is only after the patch is applied.  I is flashed stock firmware in Odin and the button combination works fine to get into stock recovery.

**Comment by Didgeridoohan** [comment]
Was it really necessary to open a second issue on this?

I'd suggest you close this and continue any more troubleshooting in https://github.com/topjohnwu/Magisk/issues/1346.
