### ISSUE TITLE
Latest canary version Magisk Manager does not download Magisk

### ISSUE THREAD

**Issue by jparnell8839** [topjohnwu/Magisk#1349]
Canary version v7.1.1-8d4c4072 (206) of Magisk Manager states that it is downloading v19.0-8d4c4072 (19004), but evidence indicates otherwise. I have provided a workaround in case any Googlers get her.

When using the "Select and patch a file" method of installing, and flashing in fastboot, Magisk Manager states that it must install additional utilities, which fails. When downloading the zip, it states that the dowload is complete, and that it is located in /sdcard/Download, but the zip is not present.

All permissions are granted to Magisk Manager.
![magisk](https://user-images.githubusercontent.com/5015689/56369042-956edb80-61c6-11e9-838f-54087421c6ed.jpg)

I am running Android Q Beta 2 on Pixel 2 XL. I realize that this may be a very unique HW/SW combo scenario, but it seems like Magisk Manager does not have storage permissions necessary.

The workaround is to download the magisk-release.zip from your Canary builds and boot into TWRP to flash the zip. Unfortunately, I have to get rid of all screen security (swipe, fingerprints, pin, etc) because TWRP cannot, for whatever reason, decrypt storage with protection.

If there are any logs you require, I do have root back, so I can provide with whatever you need. I understand you're busy working on Android's newest wrench in your gears with the Q Beta.

**Comment by topjohnwu** [comment]
Q is using scoped storage (more info here: https://developer.android.com/preview/privacy/scoped-storage). Will use storage access framework in the future
