### ISSUE TITLE
"Latest: v18.1"

### ISSUE THREAD

**Issue by GamingWessel** [topjohnwu/Magisk#1350]
![Screenshot_20190418-182349_Magisk_Manager](https://user-images.githubusercontent.com/39128502/56376359-e6eb8a80-6207-11e9-9dca-8cedeaa4e71a.png)
Image speaks for itself

**Comment by Didgeridoohan** [comment]
The image only tells us that you have the update channel set to stable, which currently is at v18.1. For anything else you need to change to beta or canary channels...

**Comment by Didgeridoohan** [comment]
Please close this issue now...

**Comment by GamingWessel** [comment]
Ok, I wasn't aware of that :)
