### ISSUE TITLE
Magisk compatibility issues

### ISSUE THREAD

**Issue by xiaokanghub** [topjohnwu/Magisk#1352]
Magisk Manager v7.1.1
Magisk v18.1
MI8 Android 8.1  
 I install the  framework through the REC, but when I use JDB to attach some software, a connection reset error will occur with JDB,I already set debuggable value is 1, and forward the port.but if I uninstall the Magisk, JDB will work. did you have any way to solve this problem? Thank you for  developer

**Comment by topjohnwu** [comment]
Disable MagiskHide to prevent modifying userdebug flags

**Comment by xiaokanghub** [comment]
> Disable MagiskHide to prevent modifying userdebug flags

I never enable the MagiskHide mode, the problem when I install the  framework ,JDB can't work well. error example: “java.net.SocketException:connection reset”

**Comment by Didgeridoohan** [comment]
MagiskHide is enabled by default. If things start working after disabling Hide, you could keep it off, or use MagiskHide Props Config to reset the necessary props that it Hide changes.

**Comment by xiaokanghub** [comment]
> MagiskHide is enabled by default. If things start working after disabling Hide, you could keep it off, or use MagiskHide Props Config to reset the necessary props that it Hide changes.

ah, unfortunately, JDB can not working after disabling Hide, same error, what can I do for it? uninstall....
