### ISSUE TITLE
lost root after OTA update despite following what the tutorial says

### ISSUE THREAD

**Issue by Frefreak** [topjohnwu/Magisk#1354]
Hello, this is the first time I use magisk and yesterday I received an OTA update on my oneplus 6T about the 2019.3 security fix, etc. As the tutorial here is what I did:

- restore boot image (without reboot, magisk did says success)
- install OTA: this is where thing seems to go wrong, it prompt that root detected and root will be lost after this update, since I wasn't sure if this is the expected behavior I continued. ~1.7GB downloaded
- after the update, click the first row(selecting magisk), install to inactive slot, reporting success.

But after I reboot, system is fine but magisk isn't installed as reported in magisk manager. What did I do wrong or is the [tutorial](https://topjohnwu.github.io/Magisk/tutorials.html) still valid?

magisk version before update:
- installed: v19.0
- latest: v18.1

yes, installed is newer than latest as reported

UPDATE: after reinstall Magisk everything seems to work fine, previous installed module is still there. (`/sbin/.magisk/modules`). Just want to make sure what went wrong.

**Comment by Frefreak** [comment]
Could you please explain why this is closed directly?

**Comment by Didgeridoohan** [comment]
Since OOS downloads the full OTA when detecting root, it's likely gonna be different... You would have to trick it into downloading the regular OTA, possibly by adding the system updater to the Hide list, before starting the procedure.

**Comment by Frefreak** [comment]
Thanks, I will try this way next OTA...
