### ISSUE TITLE
No internet connection after rooting S10+

### ISSUE THREAD

**Issue by optimistichopeless** [topjohnwu/Magisk#1357]
Hi guys,
Strange behavior of Galaxy S10+ after root : I followed instructions from https://topjohnwu.github.io/Magisk/samsung, got root, but after reboot, wifi and mobile data are available only in no magisk mode (normal restart). When booting in magisk mode (power+bixby+volume up), no internet connection : no wifi, no mobile data, no internet (wifi on, network available, nothing happens when connecting, no status bar icon for mobile data).
Does anyone have any solution ?

**Comment by topjohnwu** [comment]
Remove WiFi and reconnect. It has something to do with Samsung's smart storage
