### ISSUE TITLE
Magisk prevents Shield K1 tablet from booting

### ISSUE THREAD

**Issue by popinloopy** [topjohnwu/Magisk#136]
Shield K1 tablet.
TWRP 3.0.2-2 (the newer versions do not exist for this tablet)
Attached is the last stock boot image updated for Marshmallow.
[boot.zip](https://github.com/topjohnwu/Magisk/files/867089/boot.zip)
The full stock recovery image can be found [here.](http://developer.download.nvidia.com/mobile/shield/ROM/ST8K1/1_5_0/nv-recovery-sb-na-wf-1.5.0.zip)
 I stick with M for compatibility reasons.
After flashing Magisk, it is stuck in the booting animation. Have let it sit for a few hours, to see if it was just slow. After flashing the magisk uninstaller zip, it boots right up with no problems.

**Comment by popinloopy** [comment]
I should mention I've been trying this using the Magisk 11.6 zip. Have also tried redownloading magisk and TWRP and the recovery image multiple times just in case it was a failed download and I had a corrupted file.

**Comment by TheComputerGuy96** [comment]
http://s2.quickmeme.com/img/94/94eb289f247f6e711a9975bed6783d1db4a15af4a9f2b7cd8f1a560a3bfb540a.jpg

**Comment by popinloopy** [comment]
Alright, the update to Magisk 12.0 seemed to have fixed the issue. Sorry I never got the logcat to you, have been a tad busy recently. Thanks for the help!
