### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by heppth** [topjohnwu/Magisk#1361]
Hi,

I'm running LINEAGE OS and installed magisk. Now want to have a unrooted device. After click on complete uninstall in magisk manager my device did not boot anymore. It starts in fast boot. I recovered boot and tryed the official Uninstaller zip. Same here. When I uninstall magisk manager and reboot, magisk manager comes back. What can I do?

**Comment by topjohnwu** [comment]
reflash your rom
