### ISSUE TITLE
unzip failure while installing module

### ISSUE THREAD

**Issue by jancm** [topjohnwu/Magisk#1370]
Trying to install local module via Manager. Get unzip failure. Install same module via Franco Kernel Manager flasher and it works with no issues. Only module this has happened with (so far). Zip has tested as fine. Unzip via command line also works when I tested.
Attached files:
logs.zip - contains Magisk log, Magisk install log, Franco Manager install log. (Logcat not included, no relevant info beyond that in Magisk log)
misc-files.zip - module being installed.
(There's another issue as well, but I'll file a separate report for that. Uses the same module though).
Anything else you need just ask.
[logs.zip](https://github.com/topjohnwu/Magisk/files/3122818/logs.zip)
[misc-files.zip](https://github.com/topjohnwu/Magisk/files/3122821/misc-files.zip)

**Comment by topjohnwu** [comment]
Magisk Manager is using java's native `ZipInputStream` for extraction. Use a sane `zip` command for packing, and don't allow it to use `zip64` format

**Comment by 0x1af2aec8f957** [comment]
@jancm I have the same problem.

**Comment by jancm** [comment]
@0x1af2aec8f957  in my case the problem was the way Mixplorer was zipping up the file. The -developer was notified and fixed the problem.

**Comment by Koladweep** [comment]
> Magisk Manager is using java's native `ZipInputStream` for extraction. Use a sane `zip` command for packing, and don't allow it to use `zip64` format

Wow! This is still an issue. Please include this in main docs. https://github.com/topjohnwu/Magisk/blob/master/docs/guides.md

**Comment by axet** [comment]
@topjohnwu it is saying "!Unzip error" when here is `META-INF/com/google/android/update-binary` file is missing. It should report correct error, not zip/compression related issue.
