### ISSUE TITLE
Trying to install files to /system/product/ fails

### ISSUE THREAD

**Issue by jancm** [topjohnwu/Magisk#1372]
As part of install.sh I have the following:
REPLACE="
/system/app/Tycho
/system/product/priv-app/MyVerizonServices
/system/product/priv-app/VzwOmaTrigger
/system/product/app/MobileFeliCaClient
/system/product/app/MobileFeliCaMenuApp
/system/product/app/MobileFeliCaMenuMainApp
/system/product/app/MobileFeliCaSettingApp
/system/product/app/MobileFeliCaWebPlugin
/system/product/app/MobileFeliCaWebPluginBoot
/system/product/app/VZWAPNLib
"
The first line (Tycho) works fine. The rest fail to appear in the installed module, although they do appear in /data/adb/module_update/
Furthermore if I manually copy the product subdirectory to it's proper location in the installed module it's no longer there after a reboot.

Attached files:
system-installed.zip - the system subdirectory from the installed module.
system-update.zip - the system subdirectory from module_update
(Note that bin in the installed /system/ is created by post-fs-data.sh)
misc-files.zip - the module (same as https://github.com/topjohnwu/Magisk/issues/1370 install logs are available there)

Pixel 3 XL, stock + Kirisakura kernel
April patches
Canary Magisk

Need anything else just ask.
[system-installed.zip](https://github.com/topjohnwu/Magisk/files/3122939/system-installed.zip)
[system-update.zip](https://github.com/topjohnwu/Magisk/files/3122942/system-update.zip)
[misc-files.zip](https://github.com/topjohnwu/Magisk/files/3122944/misc-files.zip)

**Comment by topjohnwu** [comment]
Product is not yet supported now, please stay tuned for future updates
