### ISSUE TITLE
magisk defex

### ISSUE THREAD

**Issue by akano12** [topjohnwu/Magisk#1373]
i have a galaxy j6+ running android 9.0 and one ui version 1.0 ,and April 2019 security patch
been facing this problem since i had android 8.1.0 , magisk didnt patch defex,thus not all root apps were working,but luckily on 8.1.0 a developer removed defex from the kernel and posted it on xda (it fixed the problems with magisk and root apps),
now my device received androird 9.0, magisk isn't working at all,tried patching boot.img ,installing through twrp but always not working. manager says Magisk not installed
could you please fix it?
boot.img of android 9:
http://s000.tinyupload.com/index.php?file_id=00047268707154637493

**Comment by akano12** [comment]
@topjohnwu 

androdef posted this about j6+ on xda,thought it might help

"As always from Samsung, the most recent protected device against Root is J6+ (SM-J610F) & J4+ (SM-J415F)
In these devices Samsung provides an compressed kernel image into the boot image with gzip compressing method
preventing any patches that the Root needs to do to be able to get full permissions on the device.

The currently security exists in that kernel is defex protection that prevent a lot of applications to get Root access like [Titanium backup, ES File Explorer, FRep.....etc] and all other process that needs to run as Root in a custom paths.

In other devices we can bypass that security by just hexpatch directly to the kernel image but in this device the kernel image is compressed with gzip and has some restrictions prevent us from normal decompressing-recompressing."

is there anything u can do to fix this? Thanks in advance

**Comment by topjohnwu** [comment]
If that's the case, there is nothing I can do here. Use a custom kernel for the matter
