### ISSUE TITLE
SU request rejected enhancement

### ISSUE THREAD

**Issue by Jasi2169** [topjohnwu/Magisk#1374]
Well for me no resolution works for root access prompt i made small tool which edit magiskdb for third party apps manually.

What i am thinking if you add feature like "MANUAL SU" in superuser fragment where user clicks the option it opens up all user installed apps and user select the app and click SAVE/OK and it adds the policy to magiskdb then that app can work.

i made this tool Magisk Root granter it does the same :- https://www11.zippyshare.com/v/uUugY8pA/file.html

here youtube what i am talking about : https://youtu.be/SodoF5Vii_4

the issue is that it need root access before magisk issue persists,but in case if this feature is added to magisk it can write magiskdb without any root prompt required in case of issues like su request rejected,in that case if people use some apps or advanced battery optimization it will fix that issue because any app can be granted su manually

**Comment by topjohnwu** [comment]
Can you just try the latest canary? I believe 99.99999% it will fix the issue.....

**Comment by Jasi2169** [comment]
Sorry to sag but same result with canary builds v19 and manager 207 build

https://i.postimg.cc/c1gS7jzS/Screenshot-20190427-231818-Magisk-Manager.jpg

https://i.postimg.cc/fW0GSd3W/Screenshot-20190427-232303-App-Ops.jpg
