### ISSUE TITLE
Samsung Tab S5e Button Combination Not Leading to Recovery-Magisk Boot

### ISSUE THREAD

**Issue by TJWeiten** [topjohnwu/Magisk#1375]
In a very similar vein to two likely semi-related issues (#1360 & #1346), I am having slight issues following the new Samsung Pie-oriented Magisk installation tutorial.

Specifically, I am using the recently released Samsung Tab S5e. It _appears_ the functional installation of Magisk is working (using the @ianmacd Canary build of Magisk), but Step 11 is effectively impossible and I'm not quite sure why/where the fault lies.

On my device, I have successfully flashed the generated magisk_patched.tar, rebooted into standard recovery, and performed a factory reset. However, it appears impossible to boot to Magisk-in-Recovery through any combination of keys on the Tab S5e. If I hold Power & Vol Up until the bootloader splash, I will _always_ end up in standard recovery, regardless of how long I hold the Vol Up button.

I am not sure precisely how the key combination for boot Magisk-in-Recovery functions, so is it possible that because the device lacks a Bixby button (and has a different combination for Recovery access), that this is impeding my ability to boot Magisk? Because as far as I can tell, magisk_patched.tar was flashed successfully into the AP slot. Though I am not sure if there is any log I can check to determine if root was actually applied correctly in that step.

**Comment by topjohnwu** [comment]
You just need to boot into recovery normally. The button combo to boot into recovery changes from device to device, I can't help you with that
