### ISSUE TITLE
Can Magisk Manager add in-screen fingerprint sensor support?

### ISSUE THREAD

**Issue by HikariCalyx** [topjohnwu/Magisk#1378]
The device in following GIF is Nokia 9 PureView.
![N9PV_GIF](https://user-images.githubusercontent.com/29157608/56850200-cae79780-6931-11e9-9c00-5240a6a61541.gif)
Soon more Android vendors may build the fingerprint sensor into the screen like this. 

Here's the position of in-screen fingerprint sensor on Nokia 9 PureView:
![Screenshot_2019-04-27-21-15-26](https://user-images.githubusercontent.com/29157608/56850217-2023a900-6932-11e9-819a-660dc53a9a83.png)

**Comment by topjohnwu** [comment]
What a freaking stupid OEM.... on screen fingerprint sensor should block all contents and show the confirmation screen in front of all UI elements. Samsung is one of the OEMs I know that does this thing correctly. I'll see what I can do

**Comment by osm0sis** [comment]
Works fine on OnePlus 6T also.

**Comment by rp4k** [comment]
He already added this.   This issue should be closed.  Just update to the latest manager.
