### ISSUE TITLE
Magisk 11.6 not installing magisksu

### ISSUE THREAD

**Issue by trijethero** [topjohnwu/Magisk#138]
Samsung A5 SM-A520FD 2017 stock ROM

Updating or fresh ROM flash magisk not installing magisksu

**Comment by StormPooper** [comment]
Same on a OnePlus One running Resurrection Remix 5.8. Running the uninstaller and reinstalling 11.1 works, but 11.6 doesn't install MagiskSU.

**Comment by topjohnwu** [comment]
Samsung issues are all fixed
