### ISSUE TITLE
Request for U-Boot format

### ISSUE THREAD

**Issue by HemanthJabalpuri** [topjohnwu/Magisk#1382]
[boot.zip](https://github.com/topjohnwu/Magisk/files/3125915/boot.zip)

Attached boot.zip containing ramdisk.img and kernel.img
Meizu Mx4 pro has two partitions ramdisk and kernel
ramdisk can be unpacked with AIK with commit https://forum.xda-developers.com/showthread.php?t=2073775&p=79427551

Thanks

**Comment by topjohnwu** [comment]
Sorry, I have no interest in non standard images that is not trivial to support
