### ISSUE TITLE
Magisk 19 Beta Offline Charging not working with Mi 9 EEA ROM (v10.2.22.0.PFAEUXM)

### ISSUE THREAD

**Issue by Manu270891** [topjohnwu/Magisk#1386]
Offline charging doesn't work on the Xiaomi Mi 9 EEA ROM (v10.2.22.0.PFAEUXM) using the patched boot image created by Magisk 19 Beta, everything else is apparently working fine. The patched boot image created by the stable release (18.1) does't install Magisk.

**Comment by Displax** [comment]
https://github.com/topjohnwu/Magisk/issues/906
