### ISSUE TITLE
Magisk Manager - Update not up to date

### ISSUE THREAD

**Issue by francwalter** [topjohnwu/Magisk#1389]
Hello
I have on my Xiaomi Mi A1 (Android 9.0, arm64) Magisk Manager v7.1.2 (208) and Magisk v19.0 (19000) and in the main screen of Magisk Manager it shows:

Magisk is up to date
Installed: v19.0 (19000)
Newest: v18.1 (18100)

Magisk Manager is up to date
Installed: v17.1.2 (208)
Newest: v7.1.1 (203)

Pull down to update don't change it. I had before Magisk Manager v7.1.1 which showed the same. I updated Magisk Manager here from Github release, but shouldn't it be possible in Magisk Manager itself?
I remember that this worked always before, but since 19.0 I have not had any update proposal higher than v18.1
I can update modules in the Download section without problems.

What is wrong?

Thanks.

**Comment by JonnyTech** [comment]
In settings, change stable update channel to beta.

**Comment by francwalter** [comment]
Thank!
