### ISSUE TITLE
After magisk update, data loss

### ISSUE THREAD

**Issue by Yoanndp** [topjohnwu/Magisk#1390]
I just udpated Magisk and after reboot, android asked me to decrypt my phone so I entered my password and now it says "your data is unfortunately altered". I checked on the TWRP's File Manager and I still can see my data, any fix?

**Comment by Yoanndp** [comment]
Actually with Magisk Uninstaller my phone booted up but when re-rooting it still locked. I forgot to precise, I own a Honor 8 - FRD-L09C432B4xx

**Comment by gchatthes** [comment]
Same for me with Huawei P9 Plus - EMUI version 5.0.3 - VIE-L09C432B385.

After installing 19.1 either directly or with patched boot and flashed through fastboot (tried both methods), after rebooting into system I'm required to enter a password to decrypt storage. After trying to enter the "default_password" password, it says decryption failed and asks to wipe the partition but after rebooting I am able to enter a password again. I also tried my google password and pin but both weren't able to decrypt the phone. After rolling back to Magisk version 18.1, everything worked normal again.

Please let me know if you need any logs. Issue seems to affect EMUI 5 devices.

**Comment by topjohnwu** [comment]
Can you try to disable MagiskHide to see if it is the issue? Downgrade to v18.1, disable MagiskHide in Magisk Manager, then upgrade to v19.1

**Comment by ThePROgrammer1** [comment]
The same issue P9 EVA-L09 (Nougat).
Even after enabling core only mode and disabling Magisk Hide.

**Comment by gchatthes** [comment]
I don't know if it helps, but I'm also attaching you the original pre-patched boot.img (fastboot flashable) of my firmware. Seems all three cases so far are EMUI 5 related.
Many thanks topjohn for your support.
boot.zip md5:6b1e558bf7dd8fe77313405d35eefc39
[boot.zip](https://github.com/topjohnwu/Magisk/files/3137294/boot.zip)

**Comment by Yoanndp** [comment]
Yeah, still have to restore nand backup, actually, I'll keep the previous stable version

**Comment by lorvi** [comment]
same here. huawei p9. after update 19.1 it asking password, but i have not any password protected storage 🤔

**Comment by topjohnwu** [comment]
Nobody provides any kind of logs. Great! Time to close issue

**Comment by Yoanndp** [comment]
How could we get logs in 19.1 since our phone is unusable?

**Comment by Didgeridoohan** [comment]
Installation logs? Copy of unpatched and patched boot image? Etc... If nothing substantial is provided there's very little chance of anything being fixed.

**Comment by gchatthes** [comment]
Ok I'll install TWRP and try to get any logs I can by following the guide:
https://www.didgeridoohan.com/magisk/MagiskHelp
Afterwards I'll reopen a new case with all relevant logs attached and we'll see if that helps.
