### ISSUE TITLE
Magisk 19.1 in protected apps needs unlocking for granting root

### ISSUE THREAD

**Issue by ant9000** [topjohnwu/Magisk#1391]
I use the Protected apps feature of LineageOS (14.1 on my phone), and have always kept Magisk among those apps so it can't be opened without a pin or fingerprint.  Up to version 18.1 included, this setup worked smoothly.

In version 19.1 things have changed: now whenever an app needs root, the system asks me to unlock Magisk. This is pretty annoying for apps that require unlocking often, and is a more concrete problem for apps that release permissions as soon as they are not foreground - since by the time you get back they would require root again.

The only way I have found to avoid this behaviour is to keep Magisk outside of protected apps: which means available to anyone handling my phone.

Am I missing some setting that could resolve this situation, or can you confirm this is indeed a bug?

Thank you for your great job,

Antonio

**Comment by topjohnwu** [comment]
In v19.1, the native daemon will directly launch the activity for root request. In before it first sends a broadcast, and then in the broadcast it then launch the activity. This is required to support Android Q and some Chinese ROM's broadcast blacklisting.

I believe the fact that the old method works on LineageOS protected apps is a bug on their side. The new behavior should be the "correct" behavior.
