### ISSUE TITLE
[bug] There are conflicts between the three modules EDxposed, Pix3lify, and MagiskHidePropsConf in Magisk V19.1+.

### ISSUE THREAD

**Issue by 2220209876** [topjohnwu/Magisk#1395]
![photo_2019-05-02_14-57-56](https://user-images.githubusercontent.com/7346652/57060158-f92af580-6cea-11e9-842d-ef63b829d188.jpg)

https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/releases
MagiskHidePropsConf-v4.0.1b52
https://github.com/ElderDrivers/EdXposed/releases
EdXposed v0.4.1.2_beta（SandHook&YAHFA）
https://github.com/Magisk-Modules-Repo/Pix3lify
Pix3lify 2.99
[bug] The three modules of EDxposed, Pix3lify, and MagiskHidePropsConf (with fingerprint function set) in Magisk V19001+ (excluding V19000) will conflict.
Sometimes it will cause all modules to fail. Only the root function can be used (if the function of other modules is disabled, it will be effective), sometimes EDxposed will not find the apk file (pictured).
![photo_2019-05-02_14-57-55](https://user-images.githubusercontent.com/7346652/57060221-398a7380-6ceb-11e9-9907-22bb1893a891.jpg)

This problem can also occur after using the uninstall card to swipe the package and then reinstalling the magisk

If you use https://github.com/topjohnwu/Magisk/releases/tag/v19.0 this version will not cause problems

**Comment by 2220209876** [comment]
【bug】Magisk V19001+（不包括V19000）版本中EDxposed、Pix3lify、MagiskHidePropsConf（已設置指紋功能）這三個模塊一起使用會有衝突，
有時候會導致全部的模塊失效只能使用root功能（如果禁用其中一個模塊其它模塊的功能會有效果），有時候EDxposed會找不到apk文件（如圖）

使用卸載卡刷包然後重新安裝magisk後也會出現這種問題

如果使用 https://github.com/topjohnwu/Magisk/releases/tag/v19.0 這個版本則不會出現問題

**Comment by MlgmXyysd** [comment]
提供一下完整的开机日志。

**Comment by 2220209876** [comment]
> 提供一下完整的开机日志。
已经刷机。。。如果是edxp不能用 和下面这种情况一样
https://github.com/ElderDrivers/EdXposed/issues/207

**Comment by MlgmXyysd** [comment]
我想看的是Magisk挂载模块时的日志。

> > 提供一下完整的开机日志。
> > 已经刷机。。。如果是edxp不能用 和下面这种情况一样
> > [ElderDrivers/EdXposed#207](https://github.com/ElderDrivers/EdXposed/issues/207)

**Comment by Didgeridoohan** [comment]
Isn't this just the same as reported here: https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/18

Likely caused by EdXposed... Or do you have new information now?

**Comment by 2220209876** [comment]
The situation is different, https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/18 Here is the effect of MagiskHidePropsConf v3.5+ and EDxposed, but MagiskHidePropsConf can't modify the settings in the command terminal but its Fingerprints are effective and EDxposed can also be used.

Now the problem is MagiskHidePropsConf (the configuration can not be modified in the effect terminal), EDxposed can not be used normally (but the interface display module has been activated)
> 这不是这里报道的相同：[Magisk-Modules-Repo / MagiskHidePropsConf＃18](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/18)
> 
> 可能由EdXposed引起......或者您现在有新信息吗？



情況不一樣了，https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/18 這裡的是MagiskHidePropsConf v3.5+ 和EDxposed都有效果，只是MagiskHidePropsConf 在命令終端裡不能修改設置但是它的指紋是有效果的，EDxposed也能使用。

現在這個問題是MagiskHidePropsConf（有效果終端裡不能修改配置）、EDxposed不能正常使用（但是软件界面顯示模塊已經激活）

**Comment by Didgeridoohan** [comment]
Even though you say the symptoms are different it's quite likely that the cause is related. But, I don't see any Magisk logs, so it's kind of hard to say...

**Comment by 2220209876** [comment]
> 提供一下完整的开机日志。
![QQ图片20190502221906](https://user-images.githubusercontent.com/7346652/57081962-5f823900-6d28-11e9-85bc-8b7c29111a18.jpg)

[magisk19.1riru18edxp412 2019-05-02 22-15-34.zip](https://github.com/topjohnwu/Magisk/files/3138402/magisk19.1riru18edxp412.2019-05-02.22-15-34.zip)
完全卸载重装magiskv19.1的开机日志等（其他模块生效 edxp找不到apk文件）
——————————————————————————————————————————

Completely uninstall the boot log of reloading magiskv19.1 (other modules take effect edxp can not find apk file)

**Comment by 2220209876** [comment]
> Isn't this just the same as reported here: [Magisk-Modules-Repo/MagiskHidePropsConf#18](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/18)
> 
> Likely caused by EdXposed... Or do you have new information now?

Interestingly, after using magisk v19.1, MagiskHidePropsConf 4.0.1 can modify props in the terminal, and EDxposed can also be used normally. The module switch state is as shown in the figure.
This seems to be a conflict between magisk, Pix3lify, EDxposed.
![YuanEn_2019-05-02_22-31-53](https://user-images.githubusercontent.com/7346652/57085258-68760900-6d2e-11e9-8481-5b0a9b3f6de1.png)
[bootlogmagisk19.1riru18edxp412  02disable pix3 2019-05-02 22-33-34.zip](https://github.com/topjohnwu/Magisk/files/3138636/bootlogmagisk19.1riru18edxp412.02disable.pix3.2019-05-02.22-33-34.zip)

**Comment by 2220209876** [comment]
[magisk19.1  03   disableProps 2019-05-02 22-37-42.zip](https://github.com/topjohnwu/Magisk/files/3138650/magisk19.1.03.disableProps.2019-05-02.22-37-42.zip)
![03333](https://user-images.githubusercontent.com/7346652/57085627-2ac5b000-6d2f-11e9-9496-60bc5ed39cae.png)

EDxposed will fail to find the file for the first time after activating Pix3lify and EDxposed to close MagiskHidePropsConf

**Comment by Didgeridoohan** [comment]
Looking at the Magisk logs provided, this is exactly the same issue as reported earlier (https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/18). The late_start service boot stage is executed too early with EdXposed active.

**Comment by 2220209876** [comment]
> Looking at the Magisk logs provided, this is exactly the same issue as reported earlier ([Magisk-Modules-Repo/MagiskHidePropsConf#18](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/18)). The late_start service boot stage is executed too early with EdXposed active.

Interestingly, in the magisk v19.1 version, MagiskHidePropsConf and EDxposed can be used together, both sides can be used normally, and props can be set in the terminal;

If you activate Pix3lify, EDxposed will lose its effect.
This does not happen in magisk19.0

**Comment by rushiranpise** [comment]
I face same error.
If i install edxposed + pix3lify = no edxposed works

Edxposed + viper4fx = no edxposed works

(shows activated in edxposed installer/manager app but modules says it isn't activated)

Aslo trio of three of them gives same error .

But pix3lify+viper4fx = both works!

**Comment by topjohnwu** [comment]
This doesn't seem to have anything to do with Magisk itself. Closed

**Comment by 2220209876** [comment]
> 这似乎与Magisk本身没有任何关系。关闭

更新到magisk 19.2或者magisk（EDXposed）版本后没有冲突
