### ISSUE TITLE
Bug]18.1版本的没有问题，19版本的magisk和天下任我行APP冲突

### ISSUE THREAD

**Issue by demo40** [topjohnwu/Magisk#1398]
非常抱歉，打扰您了，麻烦解决一下，谢谢！从19版本以上开始的magisk，会让天下任我行APP一键新机功能失效，手机序列号和手机型号无法改变。18.1版本的magisk没有出现这个问题，附上天下任我行APP下载链接
https://www.lanzous.com/i400s9g

**Comment by topjohnwu** [comment]
你要去告知 app 得 dev，不是我 :)
