### ISSUE TITLE
Request: use root to update itself

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/Magisk#1402]
Instead of the normal APK installing, seeing that it is a root-based-app, you can use root to update it.
This can reduce the time and steps to update the app.
The user could just choose "update", and it will be taken care of in the background.
We could even have a setting for auto-updating of the app.

**Comment by topjohnwu** [comment]
Although it is possible, I will want the app be as close to following normal Android rules as possible.

**Comment by AndroidDeveloperLB** [comment]
Well, the Play Store updates itself, and of other apps.
It's quite annoying to always manually update the app.
It's a rooted app. We already have trust in it...

**Comment by AndroidDeveloperLB** [comment]
Can't you at least make it optional? Please?
