### ISSUE TITLE
Problem with Magisk-v19.1 (19100)

### ISSUE THREAD

**Issue by zen-U** [topjohnwu/Magisk#1405]
Updated to Magisk-v19.1 (19100). However, Osaifu-Keitai of Japanese specification does not function. The reason may be "init.svc.secure_element_hal_service" is not running.
Are there any fixes for these?
![Screenshot_Magisk_Manager_20190503-125518](https://user-images.githubusercontent.com/19715114/57119256-a9f4cb80-6da3-11e9-84b3-2b4714029dba.png)
![Screenshot_おサイフケータイ_アプリ_20190503-125436](https://user-images.githubusercontent.com/19715114/57119263-b711ba80-6da3-11e9-86fd-6e040c4a4782.png)

**Comment by topjohnwu** [comment]
Have you tried disabling modules? Maybe some modules are breaking the system

**Comment by zen-U** [comment]
Yes.  I get an error even if I uninstall magisk and install it.

**Comment by zen-U** [comment]
There is no error until Magisk-v19.0-3eae9494 (19001).  All subsequent canary builds will generate an error.

**Comment by sfai05** [comment]
Same here. After upgrade to 19.1 my nfc sim card is not working.

**Comment by ITJesse** [comment]
I have the same problem. Felica works well on v19.0

**Comment by nakashy** [comment]
I have same problem after V19.1

[magisk_log_V19000.log](https://github.com/topjohnwu/Magisk/files/3151106/magisk_log_V19000.log)
[logcat_V19000.log](https://github.com/topjohnwu/Magisk/files/3151108/logcat_V19000.log)
[magisk_log_V19100.log](https://github.com/topjohnwu/Magisk/files/3151109/magisk_log_V19100.log)
[logcat_V19100.log](https://github.com/topjohnwu/Magisk/files/3151111/logcat_V19100.log)

**Comment by edroebersen** [comment]
I experience a problem with Magisk-v19.1(19100).zip too. I can flash this zip together with some other zips to fix DRM, SafetyNet and hide props. When I flash the zip the kernel is patched succesfully. Yet afterward Magisk Manager v7.1.2 doesn't confirm that the zip was flashed. When I try to flag again TWRP does recognize that the kernel was rooted and the boot image was repacked. I forgot the exact message, but it doesn't do this job another time. Hence it definitely was done successfully.

This is puzzling me way too much.

**Comment by topjohnwu** [comment]
I'm 99% sure disabling MagiskHide will fix the issue. Can anyone confirm?

**Comment by nakashy** [comment]
sorry, my english is no good.

about Osaifu-Keitai, works fine with magisk-v19.0

not works with magisk-v19.1 in below case.
  enable MagiskHide > not works
  disable MagiskHide > not works
  Magisk CoreMode > not works

**Comment by TheShadowRunner** [comment]
Not sure if somewhat related but after updating to 19.1, I notice a strange behavior: some apps are just failing to launch.
I'll see the launch screen (exemple Youtube) and it hangs there for 20+ seconds.
It's random, happens once in a while. All apps are affected (not only root apps).
Sometimes it'll eventually load, sometimes I have to terminate the app manually.
Restarting the same app right after always works normally.
Sadly it doesn't generate anything in Magisk log..
Never had such issue on 18.1 with same settings and modules.
On Xperia Z5C / stock 7.1.1 / kernel patched with rootkernel prior to magisk install.
At your disposal for any further info you may need.
Thank you so much for developing Magisk !

**Comment by zen-U** [comment]
I have disabled magisk hide but the same error occurs.
The screen shot time does not matter.

![Screenshot_Magisk_Manager_20190511-111953](https://user-images.githubusercontent.com/19715114/57563964-a1257a80-73df-11e9-9ab2-55c9836abc1a.png)
![Screenshot_Magisk_Manager_20190511-112011](https://user-images.githubusercontent.com/19715114/57563965-a5ea2e80-73df-11e9-8a8a-e41a530f6c8b.png)
![Screenshot_おサイフケータイ_アプリ_20190511-111936](https://user-images.githubusercontent.com/19715114/57563968-abe00f80-73df-11e9-95bf-af6d9d776ace.png)

**Comment by ITJesse** [comment]
@edroebersen 
You need to flash v18.1 first and then v19.x, otherwise it will not work properly.
It's probably a bug.

**Comment by edroebersen** [comment]
> @edroebersen
> You need to flash v18.1 first and then v19.x, otherwise it will not work properly.
> It's probably a bug.

@ITJesse Zhu  Okay, that might work. I think it is surprising that flashing v19.0 first and then v19.1 to  is not enough. If all versions have this since v18.1, then it is also an old bug that should have been solved. This should be easy because it is just a check and nothing fancy.

Thank you for your solution. I will try this.

**Comment by li-yifei** [comment]
Same here. The felica client works fine on magisk 19.0 but failed after upgrading.

**Comment by edroebersen** [comment]
> @edroebersen
> You need to flash v18.1 first and then v19.x, otherwise it will not work properly.
> It's probably a bug.

@ITJesse Zhu  I tried your solution and found my own mistake. I was installing two files from TWRP that should be installed from Magisk:
- MagiskHide_Props_Config-v3.0.3-v48.zip,
- SafetyPatch-v2.zip

One of the two files probably corrupted the signature of Magisk-v19.1(19100).zip  Hence I can not conclude that there is a bug or that one generally needs to flash v18.1 first and then v19.x  I can only conclude that this helps when you install files from TWRP that should be installed from Magisk by mistake. Hence your solution worked, but not necessarily because of a workaround for some bug.

Why did it help me to find my mistake? This had to do with the fact that v18.1 and v19.0 get in a bootloop when you install these two files from TWRP. This is no longer the case in v19.1  Hence one can conclude that v19.1 is more stable because it can endure more. Yet it is also more confusing because it leaves more room for undetected human error.

**Comment by nakashy** [comment]
To edroebersen, what about do you talk ?

please see the zen-U's original post.

**Comment by edroebersen** [comment]
Flashing v18.1 before v19.1 didn't change much technically for the problem I experience. As a consequence I flash carefully from TWRP now.

First I restore a neat configuration from a Nandroid back-up. The back-up contains ordinary european firmware 41.3.A.2.184 for the Sony Xperia XZ, a big collection of installed apps and some configuration of these apps.

Starting with this very basical non-rooted configuration I try to install v19.1 like this:

On my laptop I issue:

Step 1: rootkernel kernel.elf boot.img
Step 2: fastboot flash boot boot_F8331_41.3.A.2.184_DRMfix_unprotectedpartitions.img
Step 3: fastboot boot twrp-3.3.0-0-kagura.img

Then from the userinterface of TWRP I issue:

Step 4: install DRMfix-System-Mode.zip
Step 5: install SafetyNet_Cleaning_Tools.zip
Step 6: install Magisk-v19.1.zip
Step 7: install Universal-safetynet-fix-v3.zip
Step 8: install MagiskHidePropsConf-master.zip

Then I restart Android and activate Magisk Manager v7.1.2 to see if Magisk v19.1 (19100) is installed. After these neat steps Magisk isn't installed. Only Magisk Manager is up to date: v7.1.2 (208)

Does anybody know why this doesn't install Magisk v19.1?
Can the installation of the zips in Step 4, 5, 7 and 8 damage the installation of the zip with Magisk v19.1?

![Screenshot_20190513-012056](https://user-images.githubusercontent.com/23479097/57590057-50219d80-7529-11e9-906f-4334c50692a9.png)

**Comment by zen-U** [comment]
@edroebersen 
We have proposed a felica client issue after updating to Magisk-v 19.1 (19100).  Please propose an install issue separately.

**Comment by kojiking76** [comment]
I lost root after updating. Magisk manager is fine though. Can anyone help? 
![Screenshot_20190520-075556](https://user-images.githubusercontent.com/50811844/57989998-c21f5700-7ad4-11e9-89a8-59d4d0c49e59.png)

**Comment by nakashy** [comment]
I want to help solve this issue.
What should I put out?

**Comment by zen-U** [comment]
Even in 19.2, felica client still does not work due to an error.
We would like to solve this problem

**Comment by audy3571138** [comment]
Ok

**Comment by kojiking76** [comment]
I solved the root issue by using magisk uninstaller. Then run magisk 18.1 in TWRP and got my root back. After that I did not do any more update. Because it's the update that unroot my phone in the first place.

**Comment by sfai05** [comment]
@zen-U @nakashy I think the title of this issue is bit confusing and descriptive enough. I suggest we close this issue and re-open one.

**Comment by zen-U** [comment]
understood.  This issue closes and creates a new issue about Felica Client

**Comment by Didgeridoohan** [comment]
@edroebersen Your issue has nothing to do with the rest of the problems described here, but just for the record: yes, one of the modules you're installing is likely causing your problem. Universal SafetyNet Fix is a badly made module that breaks Magisk functionality. It keeps being updated for newer versions of Magisk, but nobody fixes the badly made code...
