### ISSUE TITLE
AFTER update magisk . I cant update / install any app

### ISSUE THREAD

**Issue by rp4k** [topjohnwu/Magisk#1406]
I cant install any .apk or app from Google play or galaxy store.  
Installed module is edxposed and YouTube and riru
.  
[magisk_log_20190503_123143.log](https://github.com/topjohnwu/Magisk/files/3140655/magisk_log_20190503_123143.log)

**Comment by topjohnwu** [comment]
It seems to be an issue with Edxposed

**Comment by rp4k** [comment]
Actually it wasn't edxposed .  It was lucky patcher.   After fixing the settings I was able to install stuff again.

**Comment by rp4k** [comment]
[xposed_all_20190503_153422.log](https://github.com/topjohnwu/Magisk/files/3140979/xposed_all_20190503_153422.log)
[xposed_error_20190503_153416.log](https://github.com/topjohnwu/Magisk/files/3140983/xposed_error_20190503_153416.log)
Check my logs but I have no issues with exposed

**Comment by rp4k** [comment]
![Screenshot_20190503-171243_Magisk Manager](https://user-images.githubusercontent.com/18055235/57128742-ef76c000-6dc6-11e9-9d0a-9d1293e9e11a.jpg)
![Screenshot_20190503-171249_Magisk Manager](https://user-images.githubusercontent.com/18055235/57128747-f4d40a80-6dc6-11e9-8309-4ca768f50af5.jpg)


I only use these modules

**Comment by PRinceBhai** [comment]
It's still the same for me, after upgrading i can't seem to install any app from a .apk or Play Store. I had to format and reflash my Rom and then tried again. Before Flashing Magisk zip i was able to install Apps from both .apks abd play store. But after flashing Magisk it just won't work i had to re flash, before the recent update everything was fine. Guess i need to downgrade?

**Comment by rp4k** [comment]
@princebhai my issue was because of lucky patch .  Not magisk . After I fixed the settings I was able to install just fine.  But I am also on android 9.0   and using s10+

**Comment by PRinceBhai** [comment]
@r4pk I am using AOSP Extended Oreo 8.1 on my Moto E, after updating Magisk the applications stopped updating as well as installing. So i thought i might've done something with some settings so i thought a Reset would be fine which i did and solved my problem but right after i flashed Magisk [19.1] my apps again stopped updating and installing and then i reflashed the whole ROM by wiping data before but again it was the same After flashing Magisk. So i'm pretty sure that it's magisk what was causing issue. As of now i haven't flashed magisk and apps can be updated as well as Installed from apks. I flashed about 4 times to be able to understand what was causing this issue. Right after flashing magisk i couldn't even install the magisk manager. So i'll just try the older versions.

**Comment by rp4k** [comment]
my issue came back. and i even updated edxposed to there latest 4.1.2 beta  and still the same issue. and now lucky patcher is not installed @topjohnwu  the issue is still there.. why did you close this when this issue has not been fixed.

**Comment by rp4k** [comment]
the only way to fix this on my s10+ is to re-flash the patched AP file that i made as a backup from the previous version.

**Comment by PRinceBhai** [comment]
Told ya, It's something in Magisk and it probably is affecting certain devices/roms at the moment that is why nobody else have reported this yet. But let's see. I'll just use the 18.1 [last version which ran fine for me].

**Comment by rp4k** [comment]
this is how i temp fixed the issue. 
i removed both my google account and my samsung account.  i also removed  Titanium backup because it seems be broken with 9.0 on the samsung s10 series because of the very unique root method/system.  also remove lucky patcher.   i can now install and update from play store and galaxy store. but i am using  magisk manager 7.1.2(208)  and i am using  magisk v19.0-54d1207f (19005)  because like i said the s10 is a special root method.

**Comment by PRinceBhai** [comment]
Hmm.. I'll test this out too but you flashed Magisk over the newer one or did you uninstall the previous one? Also did you do that while you didn't have a Google Or Samsung Account? I'll try to replicate it the same way you did.

**Comment by rp4k** [comment]
i had  magisk 19.1 (19100) installed first and yes my google / samsung accounts were both activated.   then i re-flashed the patch.tar in ODIN and it overwrote my magisk and made it now the older build magisk 19     
 (19005) .  after that i removed my google account and samsung account completely then i did a wipe of all Dalvik/ART Cache and /data/dalvik-cache  from the app "easy cache wiper"  or you can do it from stock recovery also just wipe cache.   after the phone rebooted into rooted mode.  i then re-added my google account and samsung account and then everything worked fine.   

i am using Edxposed ( EdXposedInstaller_v2.2.4-release.apk)
Modules ------
Ruru V18 
magisk-EdXposed-v0.3.1.7
libsecure storage 1.7  for samsung 
systemless hosts  v1.0

but i wont be updating  my magisk to 19100 until  i see a reason to.  
and i am still able to get my vanilla OTA updates from samsung with just updating and patching the FW and then patching in via ODIN.  .

**Comment by PRinceBhai** [comment]
That's great that you found a way, but it's something in your patch.tar which ultimaltey fixed the issue for you as you've said it overwrote Magisk . I can't seem to find any other way on how to fix this problem besides having to reflash the rom and lose all my data and restart again, Which i can do but it will be time consuming. if only i could know what magisk creates or modifies or even the contents of your patch.tar then i could get something to start with.

**Comment by rp4k** [comment]
You can flash the uninstaller from twrp.  I don't have twrp  so it was different

**Comment by PRinceBhai** [comment]
I did, it did not resolve i said that earlier too.

**Comment by rp4k** [comment]
I really want to reinstall lucky patch 8.3.3 but I am afraid it might break it again and I might not be able to install items.  Though I don't know if it was lucky patcher or titanium backup that is causing the issue.  Do you use any of these apps.

**Comment by rp4k** [comment]
@topjohnwu   Google play store works fine..  but samsung Galaxy store and SIDELOAD APK files.  are the issue.  i think it has to do with being able to hide them properly.   is there a way to figure out what we need to hide so that it works.  because on a fresh install  of everything with everything updated. it works for about a few hours then it stops working.   so it has to do with hiding function.

**Comment by rp4k** [comment]
@topjohnwu  my syslog   you can see that there is a NULL effect.  and i dont know if it is magisk related or edxposed.   but it is there in the samsungapp when trying to install an apk. 
[2019-05-10_15.42.zip](https://github.com/topjohnwu/Magisk/files/3165884/2019-05-10_15.42.zip)

**Comment by PRinceBhai** [comment]
No i don't use Lucky Patcher and TB doesn't work on my Rom.

**Comment by PRinceBhai** [comment]
I just downgraded to 5.1 and it worked, first i tried 19.0 then 19.1 both worked. Now i think there's something with the android version.

**Comment by rp4k** [comment]
I cant downgrade I am stuck on 9.0
