### ISSUE TITLE
[ASUS Zenfone 5Z] Magisk 19.1 update broke modules 

### ISSUE THREAD

**Issue by kailashrs** [topjohnwu/Magisk#1407]
I have been using Magisk for a while, all was good until 19.1 completely broke modules... Root, Magisk hide seem to be working fine but modules are done for... Attached Magisk logs: 

https://pastebin.com/SEiz2tqs

**Comment by Didgeridoohan** [comment]
Could be because of the move to image-less Magisk... As stated in the release notes, the transition might cause issues.

Possible solution: remove and reinstall modules.

**Comment by kailashrs** [comment]
I've tried reinstalling twice, doesn't help :(

**Comment by rp4k** [comment]
i haven't had any issues with the modules that i use.  my issue was different i wasn't able to install applications but that was because of a different app i thought it was magisk but it wasn't.   but i am having no issues with edxposed, and my other modules.

**Comment by Didgeridoohan** [comment]
@kailashrs What about reinstalling Magisk? Might work by just doing a direct install over your current installation through the Manager, if not you'll have to do a full uninstall and reinstall.

**Comment by kailashrs** [comment]
I did try everything before opening this issue :(

**Comment by kailashrs** [comment]
I guess I'll just use an older 18.1 Magisk patched boot img for now, hopefully until someone here comes up with something :)

**Comment by kailashrs** [comment]
@topjohnwu @Didgeridoohan i just tried magisk 19.0 and it works perfect, so i guess some commit after it broke modules for me...

**Comment by sl1k** [comment]
@kailashrs do you have a patched.zip of 19.0? I´m having the same issues and can´t seem to be able to locate my patched.zip... I don´t have mine and can´t seem to be able to create one anymore...

**Comment by sl1k** [comment]
Actually, found 18.1v and still I cannot get modules to become installed anymore...

**Comment by sl1k** [comment]
[magisk_log_20190507_131145.log](https://github.com/topjohnwu/Magisk/files/3152039/magisk_log_20190507_131145.log)
orage/Download/magisk_log_20190507_131145.log

**Comment by sl1k** [comment]
[2019-05-07-13-29-35.txt](https://github.com/topjohnwu/Magisk/files/3152133/2019-05-07-13-29-35.txt)
[magisk.log](https://github.com/topjohnwu/Magisk/files/3152135/magisk.log)

**Comment by sl1k** [comment]
Probably best logs are these. Tried to include everything. Modules don´t appear in module list and apps don´t install....
[2019-05-07-13-36-35.txt](https://github.com/topjohnwu/Magisk/files/3152166/2019-05-07-13-36-35.txt)
[magisk_log_20190507_133607.log](https://github.com/topjohnwu/Magisk/files/3152170/magisk_log_20190507_133607.log)

**Comment by kailashrs** [comment]
@sl1k I installed 19.0 using twrp

**Comment by sl1k** [comment]
@kailashrs no use for me.. Doesn´t install it. script does go through though. Maybe I will try uninstalling canary first, if that helps. But I somehow doubt it.

**Comment by RikkaW** [comment]
A possible reason: SELinux context of module files
Use `ls -laZ /data/adb/modules` to check. For most modules, the context should be `u:object_r:system_file:s0` rather than `u:object_r:adb_data_file:s0`.
If it is the problem, reinstall modules should fix.Also, I find that install modules in TWRP can cause the problem.

**Comment by sl1k** [comment]
@topjohnwu Can confirm newest build fixed issue! Great work! Cheers!
