### ISSUE TITLE
After 19.1 install, device asks for decryption password

### ISSUE THREAD

**Issue by gchatthes** [topjohnwu/Magisk#1409]
**Symptom:**
After upgrading to Magisk v19.1 from 18.1 (by patching boot.img), when the device boots up it asks for decryption password. I tried putting my PIN, google password and the password "default_password" in the respective field, but it fails to decrypt the device. Only thing I'm able to do in that state is to wipe the device (which I didn't). ADB is also unavailable in this state, even though USB debugging was enabled before Magisk upgrade. After downgrading to 18.1 everything works well again and SafetyNet passes:
**Device details:**
Huawei P9 Plus (VIE-L09)
Firmware: VIE-L09C432B385 (Stock EMUI 5.0.3 Based on Nougat 7.0)
Security patch level: May/2018
**Methods tried to mitigate the problem**
Booted with core-only mode and MagiskHide-disabled --> same symptom
**Attached Logs:**
Boot.zip: Original pre-patched boot image
magisk_patched19100.zip: Patched boot image with Magisk-v19.1 (device not booting properly)
magisk_patched18100.zip: Patched boot image with Magisk-v18.1 (device working properly)
magisk_install_log_20190503_133217.log: install log for patching original boot.img with Magisk-v19.1
fastboot.log: Fastboot flash boot log (installing Magisk-v19.1-patched boot with fastboot)
logcat18100.zip: Logcat while booting device with Magisk-v18.1 installed
magisk.log: File from /cache/magisk.log from TWRP, while Magisk-v19.1 was installed and device was unbootable
recovery.zip: All files under "/cache/recovery" from TWRP, while Magisk-v19.1 was installed
**Notes on logs:**
Followed instructions under "https://www.didgeridoohan.com/magisk/MagiskHelp" to collect logs, but there are not many logs with Magisk-v19.1 installed since Android logging switches to disabled (adb not connecting) and magisk.log doesn't seem to record anything. I followed also instruction by placing executable file under "/data/adb/post-fs-data.d" but no bootlog.log file gets created under "/cache"

[boot.zip](https://github.com/topjohnwu/Magisk/files/3141653/boot.zip)
[magisk_patched18100.zip](https://github.com/topjohnwu/Magisk/files/3141655/magisk_patched18100.zip)
[magisk_patched19100.zip](https://github.com/topjohnwu/Magisk/files/3141659/magisk_patched19100.zip)
[fastboot.log](https://github.com/topjohnwu/Magisk/files/3141664/fastboot.log)
[logcat18100.zip](https://github.com/topjohnwu/Magisk/files/3141666/logcat18100.zip)
[magisk_install_log_20190503_133217.log](https://github.com/topjohnwu/Magisk/files/3141667/magisk_install_log_20190503_133217.log)
[magisk.log](https://github.com/topjohnwu/Magisk/files/3141668/magisk.log)
[recovery.zip](https://github.com/topjohnwu/Magisk/files/3141669/recovery.zip)

**EDIT:**
Magisk Manager which was used: v7.1.2 (208)
Advanced Settings in Magisk manager:
Enabled - Preserve force encryption
Disabled - Preserve AVB 2.0/dm-verity

**EDIT2:**
Completely uninstalled magisk and reinstalled 19.1 from scratch didn't mitigate the issue. Seems like /data doesn't get mounted at all during boot process, while other partitions are mounted properly. Would also explain why "/data/adb/post-fs-data.d" script gets ignored. Unfortunately can't check since adb isn't working during boot process with 19.1 and I'm unable to get a logcat.

**Comment by Didgeridoohan** [comment]
Why updating through patching the boot image manually? Is direct install through the Manager not possible?

**Comment by gchatthes** [comment]
I also installed it directly but had the same results. I used fastboot method in this example because its easier for me to switch Magisk versions with this method.

**Comment by heldchen** [comment]
same here on a Mi A1: after in-app patching the boot image to 19.1 and rebooting, the device reported "System destroyed." upon boot. only a factory reset helped. installing 19.1 on the factory resetted device afterwards worked tho...

**Comment by lysiong** [comment]
> 
> 
> **Symptom:**
> After upgrading to Magisk v19.1 from 18.1 (by patching boot.img), when the device boots up it asks for decryption password. I tried putting my PIN, google password and the password "default_password" in the respective field, but it fails to decrypt the device. Only thing I'm able to do in that state is to wipe the device (which I didn't). ADB is also unavailable in this state, even though USB debugging was enabled before Magisk upgrade. After downgrading to 18.1 everything works well again and SafetyNet passes:
> **Device details:**
> Huawei P9 Plus (VIE-L09)
> Firmware: VIE-L09C432B385 (Stock EMUI 5.0.3 Based on Nougat 7.0)
> Security patch level: May/2018
> **Methods tried to mitigate the problem**
> Booted with core-only mode and MagiskHide-disabled --> same symptom
> **Attached Logs:**
> Boot.zip: Original pre-patched boot image
> magisk_patched19100.zip: Patched boot image with Magisk-v19.1 (device not booting properly)
> magisk_patched18100.zip: Patched boot image with Magisk-v18.1 (device working properly)
> magisk_install_log_20190503_133217.log: install log for patching original boot.img with Magisk-v19.1
> fastboot.log: Fastboot flash boot log (installing Magisk-v19.1-patched boot with fastboot)
> logcat18100.zip: Logcat while booting device with Magisk-v18.1 installed
> magisk.log: File from /cache/magisk.log from TWRP, while Magisk-v19.1 was installed and device was unbootable
> recovery.zip: All files under "/cache/recovery" from TWRP, while Magisk-v19.1 was installed
> **Notes on logs:**
> Followed instructions under "https://www.didgeridoohan.com/magisk/MagiskHelp" to collect logs, but there are not many logs with Magisk-v19.1 installed since Android logging switches to disabled (adb not connecting) and magisk.log doesn't seem to record anything. I followed also instruction by placing executable file under "/data/adb/post-fs-data.d" but no bootlog.log file gets created under "/cache"
> 
> [boot.zip](https://github.com/topjohnwu/Magisk/files/3141653/boot.zip)
> [magisk_patched18100.zip](https://github.com/topjohnwu/Magisk/files/3141655/magisk_patched18100.zip)
> [magisk_patched19100.zip](https://github.com/topjohnwu/Magisk/files/3141659/magisk_patched19100.zip)
> [fastboot.log](https://github.com/topjohnwu/Magisk/files/3141664/fastboot.log)
> [logcat18100.zip](https://github.com/topjohnwu/Magisk/files/3141666/logcat18100.zip)
> [magisk_install_log_20190503_133217.log](https://github.com/topjohnwu/Magisk/files/3141667/magisk_install_log_20190503_133217.log)
> [magisk.log](https://github.com/topjohnwu/Magisk/files/3141668/magisk.log)
> [recovery.zip](https://github.com/topjohnwu/Magisk/files/3141669/recovery.zip)
> 
> **EDIT:**
> Magisk Manager which was used: v7.1.2 (208)
> Advanced Settings in Magisk manager:
> Enabled - Preserve force encryption
> Disabled - Preserve AVB 2.0/dm-verity
> 
> **EDIT2:**
> Completely uninstalled magisk and reinstalled 19.1 from scratch didn't mitigate the issue. Seems like /data doesn't get mounted at all during boot process, while other partitions are mounted properly. Would also explain why "/data/adb/post-fs-data.d" script gets ignored. Unfortunately can't check since adb isn't working during boot process with 19.1 and I'm unable to get a logcat.

me have the exactly same problem with you but mines is 
Huawei Mate8
EMUI 5.0.1 
Android version 7.0
Build number NXT-L29C636B594 
Android security patch level 1Dec2017. 

same error on Magisk v19.0 but when revert back Magisk v18.1, problem solved.

**Comment by Shad0wSmurf** [comment]
Also had decrypting storage issue,

Emui 5.0.4
Honor 6x
18.1 works, but after reinstall of 18.1 no ability to install modules

**Comment by strelokhalfer** [comment]
Huawei P9 lite. Have same problems as @Shad0wSmurf, only busybox instaled succesfuly.

**Comment by Holzknoten** [comment]
Same Problem like gchatthes and lysiong.

Magisk v19.1
HUAWEI Mate 8
EMUI 5.0.4
NXT-L29C432B584
Sicherheitspatch 01.09.2018

**Comment by psolyca** [comment]
I had the same trouble of decryption password but I have managed to go back to v18.1 without loosing my partition.

I have followed this guide https://www.didgeridoohan.com/magisk/MagiskInstallationIssues# ("Keeping dm-verity and forced encryption")
So, on a terminal (custom recovery)
`echo KEEPVERITY=true>>/cache/.magisk
echo KEEPFORCEENCRYPT=true>>/cache/.magisk`
Reflash v18.1, boot process is longer but that works (tried 2 times)

I have tested the same with v19.1 and that did not work !

**Comment by Montblanc0** [comment]
Has anyone tried removing all PINs/passwords/gestures/fingerprints/face unlocks prior updating to 19?

**Comment by meszb** [comment]
I have the same problem with my device, but I don't know how to get relevant helpful information.And my device has removed all passwords.
Huawei P9 EVA-AL10
Build EVA-AL10C00B399SP17
EMUI 5.0.3
Android 7.0

**Comment by nooz** [comment]
anyone here tried v19.2 yet?

**Comment by alexa-v2** [comment]
Just to note that Huawei uses it's own decryption binaries different from AOSP or Google which may/not be contributing to this issue

EMUI also is known to have issues with many things, maybe magisk is one of them. Though to be fair reported issues are second hand because I've never owned a Huawei device

**Comment by meszb** [comment]
> anyone here tried v19.2 yet?

it can't work

**Comment by nooz** [comment]
so we're just "stuck" on v18??

**Comment by nooz** [comment]
anyone here tried v19.3 ?

**Comment by nooz** [comment]
tried v19.3, same issues :/

**Comment by Kopra159** [comment]
it is different issue ,

**Comment by grantiago** [comment]
Same issue:
huawei m3 8 inch
BTV-DL09 (BEETHOVEN)
emui 5.0.4
product id 46326519
country eu
no passwords or lockscreens of any sort
"decryption unsuccessful" no option to enter pin, pw
v19.3
v18.1 working fine

**Comment by topjohnwu** [comment]
Please try the latest canary. Report again if it doesn't fix the issue.

**Comment by grantiago** [comment]
v19.4-1058aebo (19302) working as expected. 
huawei m3 8 inch
BTV-DL09 (BEETHOVEN)
emui 5.0.4
product id 46326519
country eu
LTE

**Comment by gchatthes** [comment]
Can also confirm that the issue has been fixed. Tried latest canary (19.4-dd6e55ac 19303) and app version 7.3.3-dd6e55ac - 227. Also passes Safetynet.
Thank you very much @topjohnwu for keeping those devices alive.
Wish you all the best.

**Comment by Yoanndp** [comment]
19302 is also working as expected on Honor 8 (FRD-L09C432Bxx) EU version.

Safetynet still works!
Thanks a lot @topjohnwu

**Comment by meszb** [comment]
确认问题已得到修复

**Comment by Kopra159** [comment]
> Please try the latest canary. Report again if it doesn't fix the issue.

bootloop 🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️
