### ISSUE TITLE
magisk 19.1 on reboot remove saved bluetooth paired and wifi samsung stock rom pie

### ISSUE THREAD

**Issue by Jasi2169** [topjohnwu/Magisk#1415]
I am on s9+ android pie rom wirh april 1 security patch

Magisk 19.1 update after reboot removed my saved wifi and paired bluetooth devices but i was abale to pair new bluetooth devices after reboot and forget wifi and again add same wifi but after every reboot wifi paired is saved but bluetooth is reset and no devices appear in bluetooth paired devices after every reboot.

I am back to 18.1

**Comment by rp4k** [comment]
You need to download the libsecure module in magisk

**Comment by Jasi2169** [comment]
> 
> 
> You need to download the libsecure module in magisk

that libsecure_storage module has no effect for me, bluetooth devices needs repairing after reboot everytime
