### ISSUE TITLE
When my Xiaomi 9 uses it, it will be stuck in the startup interface can not proceed to the next step, this is why?

### ISSUE THREAD

**Issue by WangSiwang** [topjohnwu/Magisk#1417]
Before this release on May 1, I can use the XiaoMi9 development version ROM root request this link (https://raw.githubusercontent.com/topjohnwu/magisk_files/master/canary_builds/release.json) to install the 7.1.2 version of the Magisk directly. And in this release, you can unzip and install Magisk directly. However, now I find that this link points to the iteration version of May 1, when my Xiaomi 9 uses it will be stuck in the startup interface can not proceed to the next step, this is why?

**Comment by Zen-Z** [comment]
Me too, my device is Mi8, ROM is MIUI development version 9.4.26.

**Comment by crok** [comment]
Same happens to a lots of us having a Mido: update from 18.1 to 19.1 and phone cannot boot (not really bootloop, it stucks in the Mi logo). Xiaomi Redmi Note 4X (Mido) with almost all MIUI ROMs (official or custom, MIUI10)

**Comment by WangSiwang** [comment]
My situation is not stuck in the mi logo, but the logo that is activated in magisk. Why is there [Direct Installation (Recommended)], I really need it? ? ?

**Comment by topjohnwu** [comment]
No logs, can't fix

**Comment by WangSiwang** [comment]
How can I get Application log logs and ask me

**Comment by crok** [comment]
> How can I get Application log logs and ask me
@WangSiwang, may you please check out the following link:
[https://www.didgeridoohan.com/magisk/MagiskHelp](https://www.didgeridoohan.com/magisk/MagiskHelp)
..and do the steps described in the "_Logcat boot script_" section?
