### ISSUE TITLE
Can't turn on Wi-Fi

### ISSUE THREAD

**Issue by XperioR** [topjohnwu/Magisk#1420]
Before updating Magisk Manager to v19.1 I was using 19.0 version - then it did work normally, but right after updating the WiFi is just turning on and half a second later immediately disabling...

EDIT: phone: Galaxy A3 2017; using LineageOS 16

**Comment by XperioR** [comment]
downgraded to 19.0 via TWRP and it works

anyways - I hope that you will consider this problem

**Comment by jgierer12** [comment]
I had the same issue with Magisk v19.2. Also on Galaxy A3 2017 and LineageOS 16. Downgrading to v19.0 did the trick too for me.

@topjohnwu Are you aware of this problem?

**Comment by XperioR** [comment]
> I had the same issue with Magisk v19.2. Also on Galaxy A3 2017 and LineageOS 16. Downgrading to v19.0 did the trick too for me.
> 
> @topjohnwu Are you aware of this problem?

Yeah, I am working now on downgraded v19.0 - this is the most recent version where wifi works, newer versions are just broken

**Comment by jgierer12** [comment]
@topjohnwu sorry to bother you but is this the same issue as #552 and/or #844? It would be cool if you could point us somewhere to keep an eye on this, instead of closing the issue without any comment at all.

**Comment by glcb1** [comment]
Had same issue on Samsung Galaxy 2017 using [ resurrection remix 7 ](http://get.mcfy.fr/Samsung%20Galaxy%20A3%202017/ResurrectionRemix%207/), with magisk v.20.2.7.
I solved my problem by adding the script file /data/local/userinit.sh containing this line :

insmod /modules/qca_cld/qca_cld_wlan.ko

and by making this file executable (chmod +x)
I found this solution on [https://github.com/topjohnwu/Magisk/issues/552](https://github.com/topjohnwu/Magisk/issues/552) and [https://forum.xda-developers.com/showthread.php?t=1704347](https://forum.xda-developers.com/showthread.php?t=1704347l)
