### ISSUE TITLE
v19.1 causes bootloop for Xperia 10 Plus, v18.1 was working fine

### ISSUE THREAD

**Issue by RebelliousX** [topjohnwu/Magisk#1421]
[boot_magisk_xperia_10_plus_53.0.A.4.79_R4A.zip](https://github.com/topjohnwu/Magisk/files/3145078/boot_magisk_xperia_10_plus_53.0.A.4.79_R4A.zip)

After installing v19.1 on my Xperia 10 Plus, system was stuck in bootloop.

Magisk Manager fails to patch SIN file in 7.1.2 (can't find BOOT!) while previously was able to do so (unpack, patch and repack with signing using AVB keys) in v7.1.1 and v18.1 which works fine.

Flashing stock ROM again and flashing magisk patched boot image with v18.1, I get root access but no modules will get installed, such as YT Vanced. Before v19.1 was released, all modules can be installed.

Edit: the attached patched boot image is the working one for magisk v18.1, below is the original stuck image. As I said, v19.1 fails to patch the image.

**Comment by RebelliousX** [comment]
[boot_X-FLASH-ALL-8F02_Xperia10plus.zip](https://github.com/topjohnwu/Magisk/files/3145080/boot_X-FLASH-ALL-8F02_Xperia10plus.zip)

**Comment by MartinX3** [comment]
Same on Galaxy note 2 with android 9 (linesge os), xperia xz2, xperia xz3.
Sony Open Devices Project.

**Comment by topjohnwu** [comment]
Please check the proper instruction to report bugs, a boot image won't help
