### ISSUE TITLE
Modules not loading

### ISSUE THREAD

**Issue by Bberx** [topjohnwu/Magisk#1422]
![6E4765F1-589F-47A5-B4B8-51A2AB6234C0](https://user-images.githubusercontent.com/35908542/57191741-5e851d80-6f5b-11e9-864b-cb14587b48f4.png)
Attached files is my modules list.

My device is Mi A2 lite. Modules are not loading. Xposed seems to work but after I install quickswitch. It does not load modules even the youtube vanced. But when I uninstall quickstep I all other modules will mount/load.

Ps. I have no idea if I can get logs via adb logcat regarding with this.

**Comment by Didgeridoohan** [comment]
Sounds like it could be related to this: https://github.com/topjohnwu/Magisk/issues/1395

EdXposed could be messing up the boot stages, but the only way to know is if you provide the Magisk log (from the Canary debug build).

**Comment by Bberx** [comment]
> Sounds like it could be related to this: #1395
> 
> EdXposed could be messing up the boot stages, but the only way to know is if you provide the Magisk log (from the Canary debug build).

how do I do that?

**Comment by Didgeridoohan** [comment]
https://www.didgeridoohan.com/magisk/MagiskHelp
