### ISSUE TITLE
Magisk spontaneously stops working (19.1)

### ISSUE THREAD

**Issue by MrSenshi** [topjohnwu/Magisk#1423]
On Magisk 19.1, Android Pie (Resurrection Remix), OnePlus 3, Magisk seems to work for a few minutes after boot and Magisk manager displays just fine. Then, spontaneously, root and Magisk will stop working. Magisk manager says "Magisk not installed" although it was working and fully functioning 2 minutes prior. On reboot, Magisk appears installed and working again before then disappearing a few minutes later. Persists between ROM updates. This issue did not exist prior to 19.x. Please fix!

**Comment by Didgeridoohan** [comment]
You haven't provided any useful information for a proper bug report. Please fix!

**Comment by MrSenshi** [comment]
Hi, sorry about that, what information would you like me to provide? I can't seem to access any useful log file.

**Comment by MrSenshi** [comment]
I got logs!

**Comment by TheGreySquare** [comment]
Same here.
Only I have this issue on all versions (Including 19.1) of Magisk available on Android Pie.

Redmi 4x, 3/32.
Pixel Experience ROM (AOSP based) Android Pie.

**Comment by rushiranpise** [comment]
disable hide option from magisk serttings and reboot

**Comment by devopsdeluxe** [comment]
Experiencing the same issue.

Phone: Oneplus 3T
ROM: LineageOS 16.0 (Builds 20190601 and 20190602)
Modem + Firmware: 9.0.2
Recovery: TWRP 3.3.1-0

> disable hide option from Magisk settings and reboot

I'll test this and report back on whether or not it resolves the issue.

**Comment by acidicX** [comment]
I am having the same Issues on a OnePlus 5 with Linage 16 (latest build today), since Magisk 19
OP Firmware: 9.0.5.

> disable hide option from Magisk settings and reboot

Testing now...

**Comment by acidicX** [comment]
Ok it seems to work without the hide option... @topjohnwu should we open a new issue because of it? Hide is one of the main features of magisk...
