### ISSUE TITLE
19.1 App will ask for Password after Lock

### ISSUE THREAD

**Issue by Hexxonite** [topjohnwu/Magisk#1424]
I have activated app lock for Magisk in order to avoid abuse if my phone gets found.

After I lock my phone and unlock it using the code, Magisk now Pop's up and wants me to enter the code again for some action.
However before the 19.1 update this would not happen, as I have granted permanent root to the apps in need. 
I would call this a bug and as it is pretty annoying, is there an easy way to go back to version 18?

**Comment by Ingan121** [comment]
May related to #1412, is there any app that using root in background?

**Comment by Hexxonite** [comment]
Yes there is. But I still dont get why I have to "confirm" this action even though the app is set to "granted"

**Comment by Senliast** [comment]
Yeah, but once the "invisible Magisk dialog" appears, your password locking app detects it and continues showing the password request even after the dialog is away.
BTW, why are you thinking that you can protect your phone by locking the Magisk app ? 😂 If the person wants to  steal your data - he will reboot the device to recovery and pull the data out. Therefore, just encrypt you phone, set lock password and that's good, you don't need to lock Magisk.)

**Comment by topjohnwu** [comment]
#1412
