### ISSUE TITLE
Documentation should warn users about Magisk Hide's incompatibility with ADB root.

### ISSUE THREAD

**Issue by nlburgin** [topjohnwu/Magisk#1425]
Users having issues with `adb root` has been reported in #590, #688, #425, etc, and have always been met with the response that this is expected behavior.

If this is intended behavior, then it needs to be documented better, somewhere besides the comments of "wontfix" bugs in the issue tracker.

Like in the README.md and/or in [here](https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445)

It may be intended behavior, but unless Magisk warns that this is going to happen, then it is very counter-intuitive for the user. The user doesn't understand why they get a `adbd cannot run as root in production builds` message, and when they search the internet for answers, usually they find instructions on how to patch the boot img to set the security settings in `default.prop` (except they may well be already set, and Magisk is just hiding them).

I spent the whole day assuming it was my ROM that had failed to set up its `adbd` as root-capable, but it turned out that Magisk Hide was hiding the relevant properties, not just from apps that were specifically enabled for Magisk Hide, but from the whole system (including from `adbd` which is something that one would intuitively expect to have access to root).

And simply running `adb shell` and then `su` is only a partial workaround because it still doesn't give root access to `adb push`, `adb pull`, etc. Unless I'm mistaken, running `su` from `adb shell` doesn't really give you any more access than you'd have by running `su` from the terminal app inside the phone; it doesn't give you the full functionality of a rooted Debug Bridge.

If the design of Magisk Hide is inherently incompatible with rooted debug bridge, that's fine, but users should at least be **warned** of this incompatibility, preventing it from appearing as unexpected and confusing behavior.

I also think it should be documented that disabling Hide to get a plain umasked rooted system, doesn't take full effect until after a reboot. That was the only way I could get rooted adb working, was to reboot the phone *after* disabling Hide. "Requires reboot" is a simple enough description that it could probably be mentioned inside the Magisk Manager app next to the appropriate setting.

**Comment by topjohnwu** [comment]
MagiskHide does not require a reboot to be disabled. The property hiding is what that requires a reboot to be reset. I will consider adding this to docs, but I doubt anyone will read the docs anyways and just complain to me at the end of the day

**Comment by devzsolt** [comment]
I lost 4 hours of my life before I have finally found this issue. After disabling MagiskHide **and** rebooting adb root magically works as it is intended. Otherwise it silently fails (on Magisk's side, while seeing `adbd cannot run as root in production builds` on my laptop).

So @topjohnwu please believe us, it's worth mentioning this incompatibility. Even better to warn inside the app, not just in the docs. Eg. when enabling MagiskHide and when enabling root for ADB or Apps & ADB.

Btw. my experience was on Android 9.0 with Magisk 19.3 and Manager 7.3.2 (latest now)

ps.: Kudos for creating Magisk, it's all good beyond this problem.

**Comment by hrehfeld** [comment]
I second adding this to the docs.
