### ISSUE TITLE
Oppo Realme 3 bootloop with Magisk 19.1

### ISSUE THREAD

**Issue by fawazahmed0** [topjohnwu/Magisk#1426]
After flashing the patched boot image, the device goes into bootloop
I have used Magisk Manager v7.1.2 to patch the boot image. I have also tried v19 and v19.2 (canary debug), even that did not work.
I was not able to get any logs.
Here is the link to stock boot image (A only system as root, no ramdisk in boot.img):

https://drive.google.com/open?id=17kuagLCpxKDtasfw4C0rS2o67mq-j_wg

System Ramdisk(Extracted from system.img):

https://drive.google.com/file/d/1zyvpnLDDTuWMvV8DYXjQylwQqWOpbyVq/view?usp=sharing

Device: Realme 3 RMX1825 (Android 9) ( A only system as root)

**Comment by MartinX3** [comment]
Same on Galaxy note 2 with android 9 (linesge os), xperia xz2, xperia xz3.

**Comment by madranet** [comment]
Ditto on Nexus 7" 2013. Rooted stock Marshmallow

* Upgraded the Magisk Manager application which then informed me on relaunching it that it wasn't backwards compatible with the version of Magisk I hd installed [17,1 –I think!] and that I'd have to either downgrade the Manager app or flash Magisk manually.

* Flashed Magisk 19,1 manually and now stuck in a bootloop.

**Comment by hellobbn** [comment]
I am having the same problem on my Xperia XZ2. I entered recovery and got the log in `/sys/fs/pstore`.
Here is the kernel log:
[console-ramoops-0.txt](https://github.com/topjohnwu/Magisk/files/3220077/console-ramoops-0.txt)

**Comment by topjohnwu** [comment]
@fawazahmed0 there are some changes in `magiskinit` in the latest canary, please check it out.
Open a new issue if problem persists.
