### ISSUE TITLE
Temp Fix / Workaround for 19.1

### ISSUE THREAD

**Issue by phr34k0** [topjohnwu/Magisk#1428]
Just did a test on my phone after which all my modules goes kapoot and disappears from Magisk. Any installation of new modules will just disappear after a reboot of phone hence after. Luckily I had my previous patched_a.img file I have kept and did a 'fastboot boot patched_a.img' in the bootloader. All modules seems to appear and Magisk boots up to the previous 19.0 version. Tried uninstalling Magisk to "downgrade" to a previous version but failed.

Uninstall all of your modules if you kept your patched boot img until the devs fixes the broken 19.1 Magisk update if any of your apps goes crazy.

P.S: My phone is Xiaomi Blackshark 8gb ram 128gb storage that came with JoyUI and there is no firmware out there to restore if Magisk were to brick the phone.

**Comment by rp4k** [comment]
so whats the fix. just reapply the patch image

**Comment by rikuddo** [comment]
For me, it didn't fix the bootloop even after doing that. What DID work is installing the latest canary build and then everything worked fine. Here's the link where I got the build from,

https://github.com/topjohnwu/magisk_files/tree/master/canary_builds

**Comment by phr34k0** [comment]
Glad that works for you. Just tested the canary myself, it appears the disappearing of installed modules still exists on 19.2 canary build as to current 19.1
