### ISSUE TITLE
Device Support: Huawei Mate 8 (Nougat)

### ISSUE THREAD

**Issue by Boosik** [topjohnwu/Magisk#143]
While flashing on Huawei Mate 8 (Nougat, build NXT-L29C432B560) the phone reboots. Magisk worked fine on Marshmalow. Last thing I saw in the TWRP log was something like:

Backing up boot image
Patching ram disk

Right after the "Patching ram disk" message appears, the phone reboots and magisk is not installed.

[bootimg.zip](https://github.com/topjohnwu/Magisk/files/870181/bootimg.zip)

**Comment by Kara-ism** [comment]
@Boosik 
Hi , I'm a newbie here.
Could you give me some simple instructions how to make this work on Marshmalow?I would appreciate it. :smiley:
