### ISSUE TITLE
Unable to boot with 19.1 on Pixel 2XL

### ISSUE THREAD

**Issue by guidezpl** [topjohnwu/Magisk#1432]
### Specs
Pixel 2XL on April 2019 security patch (previous)
Magisk Manager v7.1.2 (latest)
Using Magisk v19.0 normally

- extracted boot.img from the May 2019 full factory image, patched it with Magisk
- adb sideloaded May 2019 security patch OTA
- fastboot flash boot the patched image

From this point, would boot back to fastboot screen, couldn't get past the white Google screen with the loading bar at the bottom

Flashing the original boot.img (to both slots a and b) allowed me to boot.

Thinking maybe I had done something wrong, I went through all the steps again, this time patching on the latest Android version, but got the same bootloop. Installed TWRP and flashed Magisk directly, still got a bootloop. Between every step I restored the original boot.img

Finally, flashed v19.0, booted without problem.

**Comment by StunnerDude** [comment]
Can you specifically describe how you got Magisk working on the May security patch? I had to revert to April because flashing Magisk 19.0 still caused a bootloop.

**Comment by rikuddo** [comment]
I couldn't work it out either but then I tried the canary build and it worked flawlessly for me.  Here's the link to that build

https://github.com/topjohnwu/magisk_files/tree/master/canary_builds

**Comment by StunnerDude** [comment]
I started with the canary build originally but it didn't work, then I tried 19.1 beta, 19.1 stable, and as well as 19.0 stable, all while fresh installing the OTA each time. All have resulted in a bootloop. Honestly regretting updating.

**Comment by topjohnwu** [comment]
I think it should be an issue with the modules you've installed....
