### ISSUE TITLE
[红魔Mars]最新canary_builds版本上无法正常使用模块

### ISSUE THREAD

**Issue by youyim** [topjohnwu/Magisk#1435]
手机信息
红魔Mars SDM845 Android9.0.0

问题：
1.在最新的canary_builds上安装模块后（提示安装成功），重启手机，模块里不会显示且所安装模块不生效
2.安装edxposed也会导致手机卡在开机logo界面

然而在两个问题基础上再刷入低版本的[canary_builds](https://github.com/topjohnwu/magisk_files/tree/65e7a66e56019e30d22bd0addf21f5c7d4e40276)后，模块正常加载且可以使用，edxposed也不会导致卡开机logo且正常使用

经过测试在红魔Mars上这个[canary_builds](https://github.com/topjohnwu/magisk_files/tree/65e7a66e56019e30d22bd0addf21f5c7d4e40276)版本后的magisk都存在这个问题，而这个版本之前的都可以正常使用

如果你需要更多相关信息或log，随时联系我。

![Screenshot_2019-05-07-23-14-57-678](https://user-images.githubusercontent.com/19865880/57312405-0e0aed00-7120-11e9-9088-2e9edfb8c23f.png)

[模块加载问题.zip](https://github.com/topjohnwu/Magisk/files/3153380/default.zip)
[edxposed冲突.zip](https://github.com/topjohnwu/Magisk/files/3153381/edxposed.zip)

**Comment by Didgeridoohan** [comment]
Duplicate of https://github.com/topjohnwu/Magisk/issues/1407

**Comment by RikkaW** [comment]
可能的原因: 模块文件的 SELinux context 炸裂
用 `ls -laZ /data/adb/modules` 看一下，context 应该是 `u:object_r:system_file:s0` 而不是 `u:object_r:adb_data_file:s0`。是这样的话，试一下重装模块，要在 manager 里面装（

**Comment by youyim** [comment]
@RikkaW 无论重装多少次模块，它都不会出现在Magisk Manager模块管理里，也不会生效。这是ls -laZ /data/adb/modules结果
![Screenshot_2019-05-10-10-46-03-791](https://user-images.githubusercontent.com/19865880/57499160-34dc4580-7311-11e9-9867-be1c62bf3bb9.png)
