### ISSUE TITLE
Add support in Magisk Manager to patch boot.img using other versions

### ISSUE THREAD

**Issue by fawazahmed0** [topjohnwu/Magisk#1436]
Why this is required?
1. Sometimes new version of magisk causes bootloops or breaks some functionality and the user might not have the old patched boot as backup.
2. Not every phone has custom recovery build, so they can't just flash old version.

The only way to patch boot.img is using magisk manager, but it does not provide any option to choose the version, it always uses latest version, which may not work for some devices. but the old version may work

**Comment by Ricky-Hao** [comment]
Install `MagiskManager 7.1.1` and set custom update channel to `https://github.com/Ricky-Hao/magisk_files/raw/master/beta.json`  to install `Magisk 19.0`.

**Comment by topjohnwu** [comment]
No planning to add more complication to the already complicated installation setup
