### ISSUE TITLE
Modules that use post-fs-data are not running

### ISSUE THREAD

**Issue by alexa-v2** [topjohnwu/Magisk#1437]
I am running Descendant sGSI on a moto g6, Android 9.

Unlike a lot of other complaints I am seeing, Magisk works (mostly) wonderfully on my device/ROM. I get root, some modules (hello, substratum!), and MagiskHide works great (works on all my tests, though I do not use things like SnapChat and I have no NFC, so no Google Pay)

However, I noticed that recently Quickswitch and EdXposed, along with MagiskHide Props config all do not work. The similarity? They all rely on post-fs-data scripts to function. And for whatever reason, those are not running

This seems to hold true for both beta (v19.1) and canary (v19.2-4040a024) debug builds of magisk

Logs: https://pastebin.com/wEXLsGB9

**Comment by Didgeridoohan** [comment]
https://github.com/topjohnwu/Magisk/issues/1395

https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/18

**Comment by alexa-v2** [comment]
OK

It is definitely an official magisk issue. I installed the ianmacd version, and those modules that depend on that work

**Comment by alexa-v2** [comment]
> #1395
> 
> [Magisk-Modules-Repo/MagiskHidePropsConf#18](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/18)

Thanks for that,  but disabling one of the combination of the three modules did not help, as stated in the thread

**Comment by Didgeridoohan** [comment]
> > #1395
> > [Magisk-Modules-Repo/MagiskHidePropsConf#18](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/18)
> 
> Thanks for that, but disabling one of the combination of the three modules did not help, as stated in the thread

To know for sure what's going on you'd have to compare the Magisk log with all the different permutations of having the different modules installed. I still suspect that it's EdXposed causing issues, but can't say either or without comparing logs...

**Comment by DanGLES3** [comment]
I've had something similar,I couldn't get viper and Edxposed at the same time (it was one or the other),I've noticed the issue was caused by magisk only running one post-fs-data script and ignoring the other,I've managed to workaround it by putting Edxposed script into viper's and it worked

**Comment by topjohnwu** [comment]
It seems to me that the problem is caused by modules, not inherently an issue with Magisk itself

**Comment by rushiranpise** [comment]
I face same error.
If i install edxposed + pix3lify = no edxposed works

Edxposed + viper4fx = no edxposed works

(shows activated in edxposed installer/manager app but modules says it isn't activated)

Aslo trio of three of them gives same error .

But pix3lify+viper4fx = both works!
