### ISSUE TITLE
Magisk Can not auto detect bot Image

### ISSUE THREAD

**Issue by pekira001** [topjohnwu/Magisk#144]
Hello i am trying to install for the first time Magisk on my phone (LG-H420 Android 5.1), my phones have KingRoot Installed and Magisk Manager have permission to use root, I know that Kingroot is full working because LuckyPatcher and GameKiller are perfectly working, I have tried all available options and only one reacted but it simply restarted the phone, all that didn't work just give a message saying where the .zip was save, Kingroot is fully updated. Please help

![screenshot_2017-03-25-16-56-09](https://cloud.githubusercontent.com/assets/24511224/24324380/61cfac28-117d-11e7-90eb-9b3a9e3a5671.png)
![screenshot_2017-03-25-17-01-01](https://cloud.githubusercontent.com/assets/24511224/24324378/61ca8040-117d-11e7-9959-233c004206a9.png)
![screenshot_2017-03-25-16-56-04](https://cloud.githubusercontent.com/assets/24511224/24324379/61ce4a5e-117d-11e7-9405-a7f294ec39b1.png)

**Comment by adekmaulana** [comment]
Do manual Choose boot.img
Open your file manager, go to /dev/block/platform/'your directory'/by-name

The your directory is different from others phone remember that directory named
Now
Open
Terminal Emulator
Command
adb shell
ls -al /dev/block/platform/yourdirectorynamed/by-name

You should find your information where the boot.img is
And select on drop down menu match on magisk  with on the Terminal Emulator gave the info
