### ISSUE TITLE
Execute arm64 executable with exec() family of functions in su always get permission denied on Samsung devices

### ISSUE THREAD

**Issue by RikkaW** [topjohnwu/Magisk#1441]
The situation is, compile the same code using `exec()` family of functions to arm and arm64, run in `su`, works for arm but permission denied for arm64. (arm64 version also work in adb shell)
I don't own a Samsung device, the above situation was investigated with the help of the device owners.
Learned from others that it may be a problem with Samsung defex or RKP, so I submit an issue here.

**Comment by rp4k** [comment]
i am having a serious issue with not being able to install applications from Sideload  or  Galaxy Store on my samsung s10+   using  Rikka Riru v10  and Edexpose 4.1.2 scripthook.   running  magisk 19.1(19100)  Playstore works fine.
