### ISSUE TITLE
installation Failed on pixel2xl  AndroidQ Beta3  

### ISSUE THREAD

**Issue by WardZhouA** [topjohnwu/Magisk#1443]
When flashing Magisk 19.1/19.2 zip through twrp, it  failed to mount vender and system(invalid argument)
 After rebooting device, magisk manager said it is installed but the model does not work

**Comment by hkyq** [comment]
I was just going to make an issue asking if the beta preview 3 worked. Update us please.

**Comment by WardZhouA** [comment]
> I was just going to make an issue asking if the beta preview 3 worked. Update us please.

Still not working, I am rolling back to Android 9.

**Comment by RikkaW** [comment]
https://github.com/topjohnwu/Magisk/issues/1407#issuecomment-491133372

**Comment by puppywang** [comment]
Same to me, patch boot image failed

The log is as follows

**Comment by hkyq** [comment]
@puppywang I don't think the log was uploaded correctly

**Comment by topjohnwu** [comment]
@shakalaca has confirmed working on his Pixel 2, so issue closed

**Comment by hkyq** [comment]
So, Magisk should work on Pixel's with Android Q Beta 3?

**Comment by shakalaca** [comment]
@hkyq Root is working, but there's problem installing new modules and @topjohnwu is looking into it.

**Comment by hkyq** [comment]
Ah, ok thanks for the explanation.
