### ISSUE TITLE
S8+ magisk auto uninstalled and can't reinstalled v19.1

### ISSUE THREAD

**Issue by Jirubizu** [topjohnwu/Magisk#1446]
So I had magisk v18.1 and it worked perfectly, however a few days ago I realised that inside the manager it said magisk is not installed and I need to install v19.1. I did this however, even after using twrp and it saying done. It still wasn't installed :/. Any tips on how to get magisk working again?

**Comment by Jirubizu** [comment]
Why closed?

**Comment by topjohnwu** [comment]
Why no additional info? Do you think I am a god that can magically fix your issues without you providing any details?
