### ISSUE TITLE
"Magisk is not installed" – after flashing Magisk.zip (Both on Stable (v19.1)/Last Canary (Debug) build)

### ISSUE THREAD

**Issue by TheGreySquare** [topjohnwu/Magisk#1448]
I'm sorry, I know that it's already was opened several times, but it looks like that issue still presented.

Info:
1. Magisk Canary (Debug) – v19.2-4040a024 (19101);
2. Magisk Manager Canary (Debug) – v7.1.2-a9350f50 (210);
3. Recovery – Official TWRP (Treble) v3.3.0-0;
4. Device – Redmi 4X (Santoni), 3/32;
5. OS – Android Pie;
6. ROM – Custom AOSP Based ROM – Pixel Experience, 08.05.19, Official;
7. Kernel – 3.18.139-DarkPhoenix-1.3.1;

Logs:
[dmesg.log](https://github.com/topjohnwu/Magisk/files/3169121/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/3169122/recovery.log)

Unfortunately, I can't get Magisk.log. There's no such log in /cache. I'll try again.

Several screenshots showing my steps:
[Screenshots.zip](https://github.com/topjohnwu/Magisk/files/3169129/Screenshots.zip)

Thank you

**Comment by shakalaca** [comment]
Would you please attach the result of 'dmesg' and 'logcat' after boot up ?

**Comment by TheGreySquare** [comment]
@shakalaca 
Sorry for the logs, that's really dumb of me.
I'll try to attach needed logs later today.

**Comment by Montblanc0** [comment]
Same issue on Redmi Note 7, latest MIUI stable based on Pie. After some hours, Magisk Manager reports Magisk not installed and root is no longer working. A reboot fixes the problem until the issue eventually reappears.

**Comment by rushiranpise** [comment]
Do this,
Reflash latest magisk beta via magisk manager app, reboot , after reboot disable magisk hide from magisk manager setting. Reboot

**Comment by Montblanc0** [comment]
Thanks but I would be defeating the purpose if I disabled Magisk Hide. The idea would be to have it enabled without Magisk having a self-destroy timer, as it was intended.

**Comment by Montblanc0** [comment]
I was wondering if this issue is only related to Xiaomi/Redmi devices as I see that @TheGraySquare also has a Xiaomi device.

**Comment by alexa-v2** [comment]
Have you tried flashing a patched boot I'm instead of the zip? On stock pie on the Moto g6 it solved the issue

**Comment by Montblanc0** [comment]
@alexa-v2 I don't know about the op, but I installed Magisk via zip file. Afaik there are 2 ways of achieving the same thing, since I recall the zip file patching the boot img as well. Are you sure we are talking about the same bug?

**Comment by topjohnwu** [comment]
#1423
