### ISSUE TITLE
sm-g9750 reboots, attached kmsg

### ISSUE THREAD

**Issue by tulth** [topjohnwu/Magisk#1450]
sm-g9750 experiences 1-3 random reboots/day for me post magisk patch, with both canary and ianmacd version.

I captured a /proc/last_kmsg file right after a crash/reboot.  Se attachment that has the last part.  Hope this helps!!

[last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/3169640/last_kmsg.txt)

**Comment by tulth** [comment]
Attached is another panic capture.
[last_last_kernel.txt](https://github.com/topjohnwu/Magisk/files/3169703/last_last_kernel.txt)

**Comment by tulth** [comment]
I have a suspicion it is related to this:
https://android.googlesource.com/kernel/common/+/ASB-2019-01-05_4.9

but why would rooting make this bug pop up?

**Comment by topjohnwu** [comment]
Are you using custom kernel? Are you using 100% stock ROM + stock kernel with the official Samsung S10 installation instructions?

**Comment by tulth** [comment]
I followed your instructions exactly, and had reboots like others reported.  I am now trying the ianmacd magisk fork and the logs above are from that fork.  In both cases I believe that the kernel is basically unmodified.  I am not running a custom kernel.  When I first got the phone I think it was on a different build version but I did not record which.

**Comment by znbaboy** [comment]
Also having this issue

**Comment by topjohnwu** [comment]
I does seem like something to do with the kernel. Unfortunately this isn't something I can help

**Comment by znbaboy** [comment]
@tulth have you found a solution? The reboots dont seem to occur until you first reboot your phone manually. I flashed my phone with the latest FW and magisk_patched and didnt have the reboot issue for nearly two days. Then my battery died and ever since then the issue came back.

**Comment by tulth** [comment]
The problem has vanished for me.  i think I have only had 1 unexplained reboot in the last month.

The reboots seemed to stop after I installed the libsecure  storage companion magisk module.  

I am loving this phone!

**Comment by znbaboy** [comment]
@tulth are you on the latest update? I've used libsecure but it doesn't seem to solve the issue for me :(

**Comment by tulth** [comment]
i am on ianmacd 2019051001

**Comment by znbaboy** [comment]
I meant phone firmware. Im on ASF1 on my s10e

**Comment by tulth** [comment]
build number suffix is asd4

**Comment by znbaboy** [comment]
I just installed the latest inamcd Magisk and flahsed and i just got another reboot. UGH.
