### ISSUE TITLE
[Bug] Latest Canary Manager breaks "Hide Magisk Manager" option

### ISSUE THREAD

**Issue by yuukieve** [topjohnwu/Magisk#1455]
The latest version of Magisk Manager on the Canary channel, Magisk Manager v7.1.2-80cd85b0 (211) cannot use the "Hide Magisk Manager" option in Settings. Attempting to do so will show a toast saying "Hide Magisk Manager failed". 

This effected the previous commit (210) as well, and this is how it was discovered that it also effects updates from already-hidden Magisk Managers: updates become impossible ("There was a problem parsing the package") until you unhide Magisk Manager, at which point you can no longer re-hide it. 

**Reproduction steps:**
1. Update to the latest Canary build of Magisk Manager, v7.1.2-80cd85b0 (211) or the previous commit (210).
2. Navigate to Magisk Manager>Settings.
3. Select "Hide Magisk Manager".
4. Observe the appearance of a "Hide Magisk Manager failed" toast.
5. Observe that Magisk Manager was not hidden, as the toast said.

**System Info:**
* **Device:** Pixel 3 XL 
* **Build:** Stock (PQ3A.190505.002 - May 5, 2019) 
* **Magisk version:** Magisk v19.2-80cd85b0 (19102)
* **Magisk Manager version:** Magisk Manager v7.1.2-80cd85b0 (211)
* **Logcat:** [logcat.log](https://github.com/topjohnwu/Magisk/files/3175411/logcat.log)

**Comment by DenyDarko** [comment]
https://github.com/topjohnwu/Magisk/issues/1453

**Comment by diareuse** [comment]
Fixed in latest canary.
