### ISSUE TITLE
magisk Manager7.1.2 can't run on MIUI 10 Android P Xiaomi9

### ISSUE THREAD

**Issue by theside9** [topjohnwu/Magisk#1456]
Open magisk7.1.2 with the system-provided root (unlocked system partition) and stop at the startup interface.

Strangely, in previous versions of magisk manager, it worked perfectly.

But in previous versions of magisk manager, when installing magisk, it will be forced to update to the latest magisk manager. Is there any way not to update it to the latest version and install the latest v19.1?

**Comment by theside9** [comment]
And it just stop at the startip interface, I don't know how to find it's log.

**Comment by Katherine1** [comment]
This happened to me on my Pixel. The only workaround I found was to reboot into twrp and manually install Magisk. The manager does at least run fine once Magisk is installed.

**Comment by DenyDarko** [comment]
https://www.didgeridoohan.com/magisk/MagiskHelp

Bug reports without logs are completely useless.

You need to upload at least a logcat when the issue occurs. 

Check the link above

**Comment by Ricky-Hao** [comment]
Use this to install old version Masigk https://github.com/topjohnwu/Magisk/issues/1436#issuecomment-490422116

**Comment by theside9** [comment]
Finally, I reboot into twrp and install magisk.Now, it looks like so good.
