### ISSUE TITLE
what the "beginning of crash" in log ?

### ISSUE THREAD

**Issue by nobichal** [topjohnwu/Magisk#1461]
I want to ask, the intent of this log what? Because there is a word "beginning of crash", whether it happens there is an error magisk me?
(sorry my english is bad)
device : asus zenfone max pro m1
rom : Pixel Expirence (Pie)

09-30 03:11:01.390   598   881 I Magisk  : hide_list init: [com.google.android.gms/com.google.android.gms.unstable]
09-30 03:11:01.396   598   881 I Magisk  : hide_list init: [org.microg.gms.droidguard/com.google.android.gms.unstable]
--------- beginning of crash
05-15 17:14:24.428   598  1142 I Magisk  : ** late_start service mode running
05-15 17:14:24.429   598  1142 I Magisk  : * Running service.d scripts
05-15 17:14:24.445   598  1142 I Magisk  : service.d: exec [11link2sd]
05-15 17:14:24.483   598  1142 I Magisk  : * Running module service scripts
05-15 17:14:24.483   598  1142 I Magisk  : nfsinjector: exec [service.sh]
05-15 17:14:24.492   598  1142 I Magisk  : MagiskHidePropsConf: exec [service.sh]
05-15 17:14:33.194   598  2841 I Magisk  : ** boot_complete triggered
05-15 17:14:52.975   598   881 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[5040] UID=[10007]

**Comment by martyfender** [comment]
I had that error on the latest Canary on 2 devices. Rebooting to TWRP and deleting the cache and dalvik cache got rid of that error for me on next boot.

**Comment by DenyDarko** [comment]
I have the same log entry.

I don't say error as there is no actual crash. 

Kinda weird xD

**Comment by Olit2000** [comment]
#1279 might be related

**Comment by topjohnwu** [comment]
That is how `logcat` works on Android.... I don't filter the output of the tool.
Whenever there is **ANY** crash on your device for the first time, it will show that message
