### ISSUE TITLE
Magisk v19.1 broken on Oxygen OS Open Beta 10

### ISSUE THREAD

**Issue by Odder1** [topjohnwu/Magisk#1462]
Device instantly shuts down and boots into recovery mode when installed. Magisk version 18.0 does install and let the system boot, but no modules can be installed. Installing 19.1 through the Magisk Manager, or through TWRP recovery results in this same issue

**Comment by Shenron0** [comment]
I had the same problem as well and to fix it you have to start from scratch all over again to get magisk installed. You have to roll back to the stable Oreo and then update to the beta again and follow the same instructions to root and install magisk. Just make sure you backup EVERYTHING before you do the roll back by using twrp

**Comment by ChristopherHammond13** [comment]
OxygenOS often has this issue. Whenever I update my phone I have to run the Magisk uninstaller, flash the ROM then run the latest Magisk installer again all from TWRP. Just updating and flashing Magisk without the uninstaller first causes the immediate shut down -> recovery issue.

**Comment by alexa-v2** [comment]
Have you confirmed this on the current magisk Canary (19.3 at the time of this post)?
