### ISSUE TITLE
`echo id | su` doesn't work as expected

### ISSUE THREAD

**Issue by brbsix** [topjohnwu/Magisk#1463]
To illustrate the issue:

    $ echo id | su

Expected output:

    uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0

Actual output:

    id

---
With SuperSU, I found `su -c COMMAND` to be very unreliable as it would frequently truncate the command's output or incorrectly report it's exit status. [It was instead recommended to create an interactive shell and pipe commands to it.][0]

As such, I have a large number of scripts that utilize the following technique:

    $ su <<<id
    uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0

    $ su <<EOF
    echo 'This is the beginning of a long series of commands.'
    id
    EOF
    This is the beginning of a long series of commands.
    uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0

Curiously, this doesn't work with MagiskSU. Rather than execute the commands that it receives via stdin, it prints them to stdout.

---

I've encountered quite a few inconsistencies however the issue generally seems to arise when either stdout or stderr are connected to a terminal.

    $ su <<<'touch the_command_was_clearly_run' &>/dev/null
    $ ls
    the_command_was_clearly_run

    $ out=$(su <<<id 2>/dev/null)
    $ echo "$out"
    uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0

    $ out=$(su <<<cmd_does_not_exist 2>&1)
    $ echo "$?"
    127
    $ echo "$out"
    /system/bin/sh: <stdin>[1]: cmd_does_not_exist: not found

I'm not sure why, but the following typically (but not always) seems to work:

    $ (sleep 0.1; echo id) | su
    uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0
    $ echo "$?"
    129

This also seems to work:

    $ socat - EXEC:su <<<id
    uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0

[0]: https://su.chainfire.eu/#how-call

**Comment by topjohnwu** [comment]
@brbsix Magisk's `su -c` simply passes everything after the `-c` to `sh -c` with root permissions, there is no difference in how it is handled, so at least in Magisk's case the output will not be truncated.

What are you using this for? For an app? If that's the case,  would suggest you check out https://github.com/topjohnwu/libsu for that matter

**Comment by mirfatif** [comment]
This and other similar problems are with Android's limited `mksh` (/sytem/bin/sh).

**Comment by brbsix** [comment]
@mirfatif I've encountered the same issue using different shells. E.g. with Bash in Termux `echo id | su -s /data/data/com.termux/files/usr/bin/bash` it has the same behaviour.

**Comment by mirfatif** [comment]
In Linux world, **_Use pipe to write to su(1) and assume non-interactive (tee-like) behavior is NOT well supported_**. So STDIN from pipe or here-strings (<<<) to `su` should be avoided if possible, though the behavior isn't consistent; see [this](https://github.com/shadow-maint/shadow/blob/4.7/src/su.c#L721) and [this](https://github.com/karelzak/util-linux/blob/v2.34-rc2/login-utils/su-common.c#L341).
Android's `su` binary is not actually the `switch user`, it just connects you to a privileged daemon through UNIX socket. So don't expect a mature behavior when it comes to pseudo-terminal related issues. Also see [this issue](https://github.com/topjohnwu/Magisk/issues/1544#issuecomment-504843590).

`mksh` is bad at handling heredocs (<<), or lacks features. E.g. you can't export function to be used in heredoc. `set -x` always writes to terminal if set before `exec >/file/name 2>&1`. Other problems I can recall are no persistent history, no process substitution, no signal blocking etc.

To have a more Linux-like feel of CLI, I login to `bash` over `tmux` over `busybox su` over `/sbin/su` from Termux's `.profile`.

**Comment by topjohnwu** [comment]
Thanks for all the replies, I'll close this since I don't plan to fix it
