### ISSUE TITLE
The fact of not accepting Magisk Hide request...

### ISSUE THREAD

**Issue by Senliast** [topjohnwu/Magisk#1464]
@topjohnwu , before you close this issue please read these few strings.
I highly appreciate and respect your work on Magisk, it's titanic work to support so much devices and features , but I don't understand why you don't even want to accept Magisk hide request. Earlier , no app could detect Magisk, but now almost every app can it, and Magisk hide works only some times. For me personally, it worked for no single app, wrom which I tried to hide root.
I understand that you are working for Magisk in your free time, but I personally am ready to donate to you if you would upgrade Magisk hide at least for G Pay. I hope, you will review your opinion about Magisk Hide requests.
Thank you.

**Comment by topjohnwu** [comment]
Please check the XDA forums for instructions on how to use GPay with MagiskHide

**Comment by Senliast** [comment]
Yeah that's the whole point , that none of they are all not working 😂 I tried them all, and also from Russian forum 4pda, and no one working, g pay always says that device is altered or rooted.
And I am speaking not only from g pay, but generally about apps that doesn't work with root. You could at least review requests for some apps and try to upgrade Magisk hide for them.

**Comment by Didgeridoohan** [comment]
If there are methods to detect root that Magisk can't circumvent, it's generally up to the community to find what can be done about it. You can't expect @topjohnwu to do everything all the time... He's a buddy guy.
