### ISSUE TITLE
 Requires additional setup?

### ISSUE THREAD

**Issue by cutesniper22** [topjohnwu/Magisk#1465]
Hi @topjohnwu 
I'm facing an issue which is quite similar to the following case
https://github.com/topjohnwu/Magisk/issues/1316

I installed magisk using method of patching boot.img. After installed successfully & reboot, magisk manager ask for "requires additional setup". I pressed "Yes" to proceed and it automatically reboot to recovery permanently unless I perform full wipe. 

It seem like magisk try to look for/install something into data partition where my data partition currently encrypted (FBE). That why it failed to boot? Correct me if I'm wrong.. 

Relevant Info
-Xiaomi Mi 9 
-MIUI rom global EEA/Global Stable 10.2.24/10.2.9 (Android -9.0)
-Magisk version 19.1 installed

Attached with the magisk log.
[magisk_log_20190517_112445.log](https://github.com/topjohnwu/Magisk/files/3189795/magisk_log_20190517_112445.log)
Screenshot: 
![Screenshot_2019-05-17-11-22-50-961_com topjohnwu magisk](https://user-images.githubusercontent.com/26847827/57902235-e8f24900-789a-11e9-9572-babd10decfdf.png)

**Comment by Senliast** [comment]
Why are you installing with boot image patching? Flash uninstaller in recovery, reboot, then flash Magisk normal in recovery.

**Comment by cutesniper22** [comment]
> Why are you installing with boot image patching? Flash uninstaller in recovery, reboot, then flash Magisk normal in recovery.

I did that before, the issue still happened, keep asking for "requires additional setup" after flashed.
Another reason why I don want to do this is because of official firmware update need official recovery. I don think custom recovery able to perform update.

**Comment by foxmajik** [comment]
Also some devices like Google Pixel 3 currently cannot flash zips in recovery, so those devices require flashing the patched bootloader.

**Comment by mhamzas** [comment]
Facing the same issue with Canary Build !
