### ISSUE TITLE
Conflict between various Modules

### ISSUE THREAD

**Issue by rushiranpise** [topjohnwu/Magisk#1468]
Device Moto G2
Rr 7.0.2 pie
Magisk 19.1 beta/canary

If i install Viper4fx/Pix3lify + Edxposed/Quick Step it creates conflict

With edxposed, when viper4fx/pix3lify module is enabled, it shows framework is installed in xposed installer,but the modules still says it hasn't been enabled even when it has enabled

And with quick step, it says failed to run boot script

Aslo it's the same in canary build

**Comment by KieronQuinn** [comment]
#1395

**Comment by Didgeridoohan** [comment]
Yeah... You yourself commented on the above referenced issue. Was it really necessary to open another? And noone's still managed to show that this is actually a Magisk issue (I still suspect it's EdXposed causing it)...
