### ISSUE TITLE
Flashfire doesn't work

### ISSUE THREAD

**Issue by ubrderechte** [topjohnwu/Magisk#1469]
On my device (Sony Xperia Z2/sirius) I flashed right now Resurrection Remix v5.8.5 and flashed also the latest version of Magisk and I wanted to start Flashfire but then I got the message:

`Root was found, but access could not be acquired! Supported roots:`
`SuperSU`
`Magisk`
`CM SU (SELinux/Permissive)`
`Found root:`
`19.1:MAGISKSU`

What should I do right now? Any fixing methods??

**Comment by Didgeridoohan** [comment]
That's something for Chainfire to fix, but since Flashfire is abandoned that's very unlikely to happen. Not an issue with Magisk, please close the issue (so that @topjohnwu doesn't have to).

**Comment by ubrderechte** [comment]
So what can I do? I want to use Flashfire.

**Comment by Didgeridoohan** [comment]
If the last release of Flashfire doesn't work with current Magisk, the only option is to switch to a root solution that does work (old Magisk release, SuperSU, etc).

And like I said, please close the issue. It's got nothing to do with Magisk.

**Comment by OferYuval** [comment]
Same issue here with xiaomi mi a2 lite / Android One (Pie) rom.

**Comment by Navneet-Kumar-Singh** [comment]
Same issue here on sm a920f

**Comment by Navneet-Kumar-Singh** [comment]
I guess if just topjohnwu changes the name of 23.0:Magical to just Magisk then it should work
