### ISSUE TITLE
[11.6] SafetyNet Basic Integrity not valid after install

### ISSUE THREAD

**Issue by s0r00t** [topjohnwu/Magisk#147]
Phone : Xiaomi Redmi Note 4
ROM : MIUI 8.3 by xiaomi.eu 7.3.23 | Beta
Magisk version : 11.6

Before installing Magisk, CTS does fail but basic integrity passes.
After installing Magisk, basic integrity no longer passes the test, whether Magisk Hide is enabled or not.

Magisk Hide do work, I've tried hiding root from settings + a random root check app from the Play Store, and it could not find root.

**Comment by topjohnwu** [comment]
Then something else if preventing it from passing if root is actually hidden

**Comment by s0r00t** [comment]
There is no additional action taken besides installing Magisk 11.6 from TWRP.  
I'm gonna investigate this, if you say so.

**Comment by s0r00t** [comment]
So, I've completely formatted my phone. Nothing custom, besides the test & Magisk. Ran the test before & after installing Magisk with Magisk Hide.
Same results as before. 

I don't know if I need to toggle Hide on specific apps for it to pass.

Can you re-open the issue, please?
