### ISSUE TITLE
edroebersen

### ISSUE THREAD

**Issue by edroebersen** [topjohnwu/Magisk#1476]
I experience a problem with Magisk-v19.1(19100).zip. I can flash this zip together with some other zips to fix DRM and SafetyNet. When I flash Magisk-v19.1(19100).zip the kernel is patched succesfully. Yet afterward Magisk Manager v7.1.2 doesn't confirm that the zip was flashed. When I try to flash again TWRP does recognize that the kernel was rooted and the boot image was repacked. I forgot the exact message, but it doesn't do this job another time. Hence it definitely was done successfully.

This is puzzling me way too much.

When I start I first restore a neat configuration from a Nandroid back-up. The back-up contains ordinary european firmware 41.3.A.2.184 for the Sony Xperia XZ, a big collection of installed apps and some configuration of these apps.

Starting with this very basical non-rooted configuration I try to install v19.1 like this:

On my laptop I issue:

Step 1: rootkernel kernel.elf boot.img
Step 2: fastboot flash boot boot_F8331_41.3.A.2.184_DRMfix_unprotectedpartitions.img
Step 3: fastboot boot twrp-3.3.0-0-kagura.img

Then from the userinterface of TWRP I issue:

Step 4: install DRMfix-System-Mode.zip
Step 5: install SafetyNet_Cleaning_Tools.zip
Step 6: install Magisk-v19.1.zip

Then I restart Android and activate Magisk Manager v7.1.2 to see if Magisk v19.1 (19100) is installed. After these neat steps Magisk isn't installed. Only Magisk Manager is up to date: v7.1.2 (208)

Does anybody know why this doesn't install Magisk v19.1?
Can the installation of the zips in Step 4 and 5 damage the installation of the zip with Magisk v19.1?

![Screenshot_20190520-030500](https://user-images.githubusercontent.com/23479097/57991243-dac84680-7aad-11e9-9424-635ac04b1e51.png)

**Comment by topjohnwu** [comment]
Sorry, but github is not a place for support. Issues are only for development purpose
