### ISSUE TITLE
Magisk 19.x does not work well on Oreo Samsung device

### ISSUE THREAD

**Issue by senayuki** [topjohnwu/Magisk#1479]
Im using S7 edge with Android 8.0
Magisk 18.1 do work well on my device, but after I UPDATE to 19.2 ,Magisk Manager tell me "Magisk is not installed".
The same problem on Magisk 19.1
Strangely, Xposed and Riru etc. ,all installed mods still working. 
How can I solve it? Where can I find some logs?
Thanks

**Comment by callihn** [comment]
I'm getting the same problem after updating ftom 19.1 to 19.2. Sometimes after I reboot it's there and other times it's not and when it's not Magisk Manager is not available either says app not installed.

**Comment by senayuki** [comment]
> I'm getting the same problem after updating from 19.1 to 19.2. Sometimes after I reboot it's there and other times it's not and when it's not Magisk Manager is not available either says app not installed.

Unfortunately, reboot is useless for me... I cant manage my mods anymore

**Comment by callihn** [comment]
I'm on 5.1 too and using a different phone so obviously this is not an isolated issue. I think the issue is with Magisk Manager though, anyone want to try the previous version and test that? I don't get the issue every reboot but it's easy to notice when I do because I use Link2SD so all those apps are missing when it happens.

**Comment by senayuki** [comment]
> I'm on 5.1 too and using a different phone so obviously this is not an isolated issue. I think the issue is with Magisk Manager though, anyone want to try the previous version and test that? I don't get the issue every reboot but it's easy to notice when I do because I use Link2SD so all those apps are missing when it happens.

A good news, I flash latest kernel, and reflash Magisk 19.2, it worked.
