### ISSUE TITLE
Can't install Magisk Redmi 4x

### ISSUE THREAD

**Issue by RAVINTER** [topjohnwu/Magisk#1480]

**Comment by RAVINTER** [comment]
Like in title, Redmi 4x (Santoni) When im install Magisk via Twrp no errors but Magisk Manager say "Install"  and no have root, trying many times and not work. Im reading many solutions but still nothing works, im patching boot image with magisk from latest my instaled rom and install via adb, here no errors to all fine but again still no root and Magisk Manager call for "install"  Anyone can help? Sorry for my english.  Twrp version 3.3.0  Magisk tried to install versions 19.0, 19.1,19.2

**Comment by WaterFlai** [comment]
i had the same problem too, redmi 4x. magisk manager show that magisk is not installed, but actually its installed and your previous module and root privilege is still there. adaway,, youtube vanced,camera 2 api miui10 is working, but magisk manager telling me its not installed.  i tried for root checker and the manager not giving any prompt. thanks for

**Comment by RAVINTER** [comment]
For me not works anything, im not have root.

**Comment by WaterFlai** [comment]
Downgrade, give a try

**Comment by RAVINTER** [comment]
Nobody help so im install SuperSu and now have root, Magisk is useless. Creator never help like i see.

**Comment by WaterFlai** [comment]
Dude, just downgrade to 19.1 it's working

**Comment by WaterFlai** [comment]
All you need is flash magisk uninstaller 19.2 and flash your 19.1 again
