### ISSUE TITLE
Magisk Manager 7.2.0 crashes when I try to open.

### ISSUE THREAD

**Issue by nerdjp** [topjohnwu/Magisk#1484]
I got a notification that magisk had an update, but when trying to install MM 7.2.0, the app won't open anymore, showing "Magisk Manager has stopped" on screen... I tried updating to Magisk 19.2 via Recovery and then update the manager to 7.2.0, still no luck... Now I'm with Magisk 19.2 and Manager 7.1.2, Phone: Moto E5 (Nora), Android 8.0.0 (Oreo).

What should I do? 

Ps: it's my first time posting an issue in Github, so let me know if I do something wrong, please.

**Comment by Jacksparrow75** [comment]
Same problem here...

**Comment by Jacksparrow75** [comment]
Same problem here... I've updated to 7.2 when I got notification. I forced stopped the app, cleared cache and data and no luck. I uninstalled and then reinstalled, no way. I reflashed os, magisk 19.2 but still the same. It seems everything works, but I can't open magisk manager anymore...

**Comment by theobch** [comment]
You don't provide a log, both of you.
I suggest you do, if you want the community / @topjohnwu to helps you.
[Here a little tutorial](https://forum.xda-developers.com/showthread.php?t=1726238) if you don't know how to.

**Comment by topjohnwu** [comment]
Just as @theobch said, giving logs for Magisk Manager is the simplest of all reports...

**Comment by Jacksparrow75** [comment]
How can I provide you logs if I can't open magisk manager?

**Comment by salevdns** [comment]
>E/AndroidRuntime(13978): Caused by: android.content.res.Resources$NotFoundException: Drawable com.topjohnwu.magisk.swiftinstaller.overlay drawable/ic_splash_activity with resource ID #0x7f080096 D/AbnormalMonitor( 862) appCrash com.topjohnwu.magisk W/ActivityManager( 862) Force finishing activity com.topjohnwu.magisk/a.c I/ActivityManager( 862): Showing crash dialog for package com.topjohnwu.magisk u0

Make sure you disable any theme for MM i.e. substratum.

Also please make sure log comments are collapsible or link to a service like pastebin next time.

**Comment by Jacksparrow75** [comment]
> > E/AndroidRuntime(13978): Caused by: android.content.res.Resources$NotFoundException: Drawable com.topjohnwu.magisk.swiftinstaller.overlay drawable/ic_splash_activity with resource ID #0x7f080096 D/AbnormalMonitor( 862) appCrash com.topjohnwu.magisk W/ActivityManager( 862) Force finishing activity com.topjohnwu.magisk/a.c I/ActivityManager( 862): Showing crash dialog for package com.topjohnwu.magisk u0
> 
> Make sure you disable any theme for MM i.e. substratum.
> 
> Also please make sure log comments are collapsible or link to a service like pastebin next time.

Thanks alot, it now works!!!
