### ISSUE TITLE
Magisk for Chrome OS?

### ISSUE THREAD

**Issue by jbardi** [topjohnwu/Magisk#1485]
Is there any movement on getting Magisk to work on Chrome OS?

I am currently rooting the Android system on my Chromebooks via SuperSU, but that requires 2 copies of the Android system image to remain present on the Chromebook, one patched, and one unpatched, and takes up extra space and has to be redone from scratch with every Chrome OS upgrade.  Would LOVE to see Magisk on Chrome OS!

**Comment by topjohnwu** [comment]
Magisk will also need 2 copies of the system due to the fact that Android in ChromeOS is stored in `squashfs` images

**Comment by KB5201314** [comment]
@topjohnwu Sorry, how can I get Magisk run on Android in ChromeOS, is there any guides?
