### ISSUE TITLE
shell asks for root permissions?

### ISSUE THREAD

**Issue by cc-rock** [topjohnwu/Magisk#1491]
Since updating to Magisk 19.2 / Manager 7.2.0, when I connect my phone to the computer for debugging, a pop up appears telling me that "shell" is requesting root privileges.
Is that supposed to happen? I'm not doing anything that requires root, just USB debugging..

**Comment by cc-rock** [comment]
Sorry for writing here, might not be the right place, but the XDA forum seems empty apart from the release notes.. and I couldn't find any link to any discussion forum

**Comment by alexa-v2** [comment]
Is ro.secure=0 and/or ro.adb.secure=0 in your ROM?

**Comment by AngelFalse** [comment]
> Is ro.secure=0 and/or ro.adb.secure=0 in your ROM?

Does the adb session obtained root privilege by the usual "su" ways? I used to think it obtained root privilege by forking a sub-process with root privilege that came with itself...

**Comment by alexa-v2** [comment]
If the aforementioned flags in your build.prop are set it's automatically root

It really depends on your ROM and if you've tweaked build.prop

However any commands that invoke su will, of course, ask for root as well

**Comment by AngelFalse** [comment]
> If the aforementioned flags in your build.prop are set it's automatically root
> 
> It really depends on your ROM and if you've tweaked build.prop
> 
> However any commands that invoke su will, of course, ask for root as well

Yes... But, I mean, adbd process checks for the build.prop, then decide what permission the adb session shall get. Does this progress involve invoking su? Or does this progress only involve forking a new process with shell/root permission?

**Comment by topjohnwu** [comment]
Something is seriously wrong with the ROM you are using. Nothing to do with Magisk

**Comment by cc-rock** [comment]
Well, the rom is stock oxygen os, with no modifications apart from magisk and the quickswitch module for changing recents.. the above mentioned flags (ro.secure and ro.adb.secure) are both set to 1.. but I'll investigate further if it can be caused by something else. Thank you.

**Comment by cc-rock** [comment]
Ok, found the culprit.. my bad.. I was connecting the phone while Android Studio's "Device file explorer" was open, and that is requesting root permissions (by design). Sorry for the inconvenience
