### ISSUE TITLE
'Magisk not installed' on Rockchip Oreo firmwares

### ISSUE THREAD

**Issue by mo123** [topjohnwu/Magisk#1493]
Tested with Canary build and also with latest Magisk 7.2 on Rockchip RK3328 Oreo firmware.
After power on/off or reboots Magisk Manager can't pick up that Magisk is installed.
After some reboots or power off's then Magisk Manager says that Magisk is installed again.
About 2 out of every 5 power on's, reboots have working Magisk.

This is on Rockchip RK3328, RK3399 ARM64 devices running Android Oreo firmware.

I patched the boot.img manually and repacked with KRNL support since Magisk Manager can't repack boot.img's with KRNL support correctly.

Trying the exact same Magisk builds on Rockchip Nougat firmwares ARM & ARM64 then Magisk works correctly after every reboot or power on. Nougat doesn't use vendor, oem or security partitions that are in Oreo and perhaps this is why it works on it?

I see people with Samsung and other devices running Oreo firmwares also have problems with Magisk just disappearing and saying 'Magisk is not installed' after a certain time or reboot.
Can the issues be related, is there a problem with ARM64 or new pattitions support on Oreo? 
Does Magisk mount too early in the boot process perhaps, similar problem than Leagoo devices https://github.com/topjohnwu/Magisk/pull/1459?

Here are some logs.
Will post more later.

[    2.858120] magiskinit: Early mount system
[    2.861894] magiskinit: mount ->/system failed with 22: Invalid argument
[    2.864127] magiskinit: Early mount vendor
[    2.864184] magiskinit: mount ->/vendor failed with 22: Invalid argument
[    2.864248] magiskinit: open: /proc/device-tree/firmware/android/fstab/product/dev failed with 2: No such file or directory
[    2.864306] magiskinit: open: /proc/device-tree/firmware/android/fstab/odm/dev failed with 2: No such file or directory

[    4.337269] type=1400 audit(1557978781.996:3): avc: denied { getattr } for pid=1 comm="init" path="/sbin/magisk" dev="tmpfs" ino=12541 scontext=u:r:init:s0 tcontext=u:object_r:tmpfs:s0 tclass=file permissive=1
[    4.341131] init: cannot setexeccon('u:r:magisk:s0') for aO8SZcq: Invalid argument
[   14.347098] init: Command 'wait /dev/.magisk_unblock 10' action=post-fs-data (/init.rc:746) returned -1 took 10008ms.
[   14.347277] init: Service 'aO8SZcq' (pid 229) killed by signal 6

[   30.573969] type=1400 audit(1557978808.233:35): avc: denied { getattr } for pid=1 comm="init" path="/sbin/magisk" dev="tmpfs" ino=12541 scontext=u:r:init:s0 tcontext=u:object_r:tmpfs:s0 tclass=file permissive=1
[   30.574683] init: cannot setexeccon('u:r:magisk:s0') for AveucLR: Invalid argument

[logcat.log](https://github.com/topjohnwu/Magisk/files/3205844/logcat.log)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/3205847/dmesg.log)
Patched boot.img, rename to .img to unpack
[ramdisk.gz](https://github.com/topjohnwu/Magisk/files/3205848/ramdisk.gz)

**Comment by topjohnwu** [comment]
It seems to me the same issue of #1459. Will investigate further
