### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by FoOlKeN** [topjohnwu/Magisk#1495]
Im a on Samsung A600fn (android 9)and i face 2 problems.
-Can't sign in Samsung acount (process failed)
-Can't set up password or Pin code when i try to comfirm it say pin code incorrect even for a password, and i cant use Faceunlock or Fingerprint
Flashed with latest TWRP for a6 and try with magisk 18.1/19.2

**Comment by alexa-v2** [comment]
Have you tried using magiskhide on any apps involved in this process? You may have to clean data of them and reboot after adding them to magiskhide

**Comment by FoOlKeN** [comment]
Yes already but the most important fr me is to set up a security like Password or Pin code but i cant confirm it

**Comment by alexa-v2** [comment]
How exactly are you sure it's magisk related?

**Comment by FoOlKeN** [comment]
I dont know exactly and that why im asking...on android oreo everything was working perfectly and it cant be my firmware i get it from Sammobile.
Can it be Twrp nothing is encrypted

**Comment by alexa-v2** [comment]
I don't see any way magisk will interfere with locksreen setting

Are you using anything to mod it such as a magisk or Xposed module?

**Comment by FoOlKeN** [comment]
No because at the first i was rootedt on oreo and wanted to pass on One Ui(android9) so i flash a firmware from Sammobile and now i have the security setting

**Comment by FoOlKeN** [comment]
And if i downgrade to Android oreo and root all works perfectly i was wonder if is the firmware so o try with the software Samfirm and i have the same security problem

**Comment by Tommasoleone** [comment]
I have same issue with samsung A6, A6+ and A7 2018. This issue only with Android Pie, with oreo dont have unlock screen issue. I have read xda forum many user have same issue with Samsugn J4 and J4+. I have try: Magisk 18, 18.1, 19, 19.1 and 19.2, Noverity 6.0, 1.0 and Universal no verity, i have try many firmware of Pie and have try Magisk core only mode. Dont have others ideas. Only samsung S9 working without unlock screen issue if rooting with dr.ketan fix.

**Comment by topjohnwu** [comment]
@Tommasoleone may you point to me the so-called "dr.ketan" fix?

**Comment by topjohnwu** [comment]
Continue discussion is #1409

**Comment by Tommasoleone** [comment]
Sorry if I didn't answer first..I have rooted s9 with this: 
https://forum.xda-developers.com/galaxy-s9-plus/how-to/guide-root-s9-oem-fix-t3763974   and dont have lock screen issue.

Other device have lock screen issue..Discussione 1409 its another issue..For more info of lockscreen issue see this:
https://forum.xda-developers.com/galaxy-j4+/how-to/root-j4-plus-pie-u2-2019-t3929112/page5


Thanks!
