### ISSUE TITLE
Magidk Canary version 

### ISSUE THREAD

**Issue by alexa-v2** [topjohnwu/Magisk#1496]
Hello
I recently noticed that the beta and stable version is newer than Canary
Manager Canary is 7.1.2, stable/beta 7.2.0
Magisk Canary is 19.2-[string] (19102) and stable/beta is 19.2 (19200)

**Comment by alexa-v2** [comment]
Just noticed I misspelled magisk in the title :-)

**Comment by topjohnwu** [comment]
Pushed
