### ISSUE TITLE
What does the "Superuser Access" settings do? It does not seems to function correctly.

### ISSUE THREAD

**Issue by AngelFalse** [topjohnwu/Magisk#1498]
When connecting adb via LAN, my adb session does not gain root privilege automatically.

Raw output:

```
D:\adb>adb push xxx /data/media/xxx
failed to copy '' to '/data/media/10/': couldn't create file: Permission denied
D:\adb>adb pull /xposed.prop x
remote object '/xposed.prop' not a file or directory
D:\adb>adb shell whoami
shell
```

I **didn't test connecting adb via. usb** (the computer I use for now does not have a proper adb 
usb driver configured), but I expect it's the same thing.

And when I tried to execute su in the adb shell, magisk manager popped out a "Superuser Request" window.

Is this problem coming from the reformation of the security model android system? I once connected a android 4.2 device using adb, and gained "adb" when executing whoami in the shell, now I what I can get is "shell" by default.

I don't believe it a design failure in magisk, but it is a real problem, please consider.

> Device Information (adbd / phone side):
> Device model: Mi-4c
> Codename: Libra / Xiaomi 4C
> Android Version:7.1.2
> ROM: LineageOS 14.1-20181207-NIGHTLY-libra
> Kernel: 3.10.107-perf-g6e4151
> SELinux status: Enforcing

> Device Information (adb / computer side, though I don't think there's anything important here...):
> Windows 10 Enterprise 2016 LTSB
> 10.0.14393
> Android Debug Bridge version 1.0.32

**Comment by topjohnwu** [comment]
`adb root` and allow `adb` to use root is 2 different things
