### ISSUE TITLE
Magisk 19.2 bootlooping on Google Pixel XL

### ISSUE THREAD

**Issue by P0werGirl** [topjohnwu/Magisk#1502]
Conditions:

- OEM unlocked Google Pixel XL. It was Verizon locked, [but I unlocked it following this thread's guidance from XDA.](https://forum.xda-developers.com/pixel-xl/how-to/how-to-unlock-bootloader-verizon-pixel-t3796030)
- Android 9, May security update on Google Pixel XL. Phone fully updated.
- Dev options enabled, USB debugging on.
- Flashed TWRP 3.3.0-0 (Marlin ver.) onto the phone. Installed TWRP .zip from TWRP recovery.
- Attempted to flash Magisk 19.2 .zip from TWRP recovery.
- Entered bootloop. Reflashed stock factory image. Reflashed TWRP. Reinstalled TWRP .zip from TWRP recovery. Flashed Magisk 17.2, no problems so far.

Not sure what the issue is, 19.2 seems unstable on the Pixel XL.

**Comment by topjohnwu** [comment]
Check if there are incompatible modules installed. Pixel devices are always first party supported
