### ISSUE TITLE
[Manager] Prompting to update to old module versions when updated outside of the repo

### ISSUE THREAD

**Issue by yuukieve** [topjohnwu/Magisk#1507]
Magisk Manager seems to ignore or misinterpret the module.prop versioning info if a downloaded-from-repo module is updated to a version newer of the module than is available on the repo. For example, I updated to Riru-Core v19.1 from the GitHub release, which has a module.prop consisting of:

```
id=riru-core
name=Riru - Core
version=v19.1
versionCode=22
author=Rikka
description=Inject zygote process by replace libmemtrack.so, provide interface to other Riru modules.
``` 

Magisk Manager now prompts me to "update" Riru-Core to v19, despite the v19 ZIP downloaded from Magisk Manager having a module.prop consisting of lower versioning: 

```
id=riru-core
name=Riru - Core
version=v19
versionCode=21
author=Rikka
description=Inject zygote process by replace libmemtrack.so, provide interface to other Riru modules.
``` 

----

**System info:**
**Device:** Pixel 3 XL
**Android version:** 9.0 (stock, 2019-05-09 security patch)
**Magisk version:** v19.3-8c40db57 (19201) [Latest Canary at time of writing]
**Magisk Manager version:** v7.2.0-8c40db57  (214) [Latest Canary at time of writing]

**Comment by diareuse** [comment]
This has been already fixed. Next release 🤞
