### ISSUE TITLE
Device Support: Acer Liquid Z630 (T03) - MagiskHide

### ISSUE THREAD

**Issue by nicegamer7** [topjohnwu/Magisk#151]
Acer Liquid Z630 (T03) - Mediatek MT6735
Hey, Magisk is great and it works great. Good job on it.
But one thing that has never worked for me is MagiskHide.
Before installing Magisk, I am able to pass SafetyNet tests and root checking apps (of course). After installing Magisk, it doesn't work on root checking apps, or SafetyNet testers.
I've attached the boot.img, please tell me if there are any logs I can provide to help out.

**Comment by Didgeridoohan** [comment]
Attaching the boot image didn't work, try again.

**Comment by nicegamer7** [comment]
Sorry, I didn't notice.
[boot.zip](https://github.com/topjohnwu/Magisk/files/886481/boot.zip)

**Comment by nicegamer7** [comment]
This one is updated, it might be better to look at this one.
[boot.zip](https://github.com/topjohnwu/Magisk/files/886578/boot.zip)
