### ISSUE TITLE
Cerberus + google maps constant root permission request with 19.2

### ISSUE THREAD

**Issue by Sada-Mio** [topjohnwu/Magisk#1510]
Pixel 3XL, no modules, Cerberus,  start google maps directions.

- 18.2 works fine,
- 19.1 google maps would go in & out of PIP mode rapidly. 
- 19.2 google maps direction is able to function, but Cerberus would display permanent toast message being granted root permission. Magisk logs filled with requests attempts.

**Comment by topjohnwu** [comment]
Tell the Cerberus dev to fix his app. Maybe point him to `libsu`
