### ISSUE TITLE
Error problem with Felica Client after Magisk-v19.0-3eae9494 (19001)

### ISSUE THREAD

**Issue by zen-U** [topjohnwu/Magisk#1511]
FeliCa Client does not emit an error in Magisk-v19.0-3eae9494 (19001). Perfect operation. However, all subsequent Magisk will generate an error.
Even in Magisk-v19.3-6a54672b (19202), FeliCa Client emits an error.  
What should we do?

**Comment by nakashy** [comment]
I have same problem on Pixel3(blueline PQ3A.190505.002) with docomo(japanese career)SIM.

**Comment by nakashy** [comment]
[logcat_V19000.log.gz](https://github.com/topjohnwu/Magisk/files/3247054/logcat_V19000.log.gz)
[logcat_V19203.log.gz](https://github.com/topjohnwu/Magisk/files/3247055/logcat_V19203.log.gz)

FelicaClient(com.felicanetworks.mfc) needs SecureElement, and work with eSE1(on Pixel3).

Bellow lines are in logcat_V19000.log(Magisk19000)
  06-03 13:03:09.971  2041  2041 I android_os_HwBinder: HwBinder: Starting thread pool for eSE1::android.hardware.secure_element@1.0::ISecureElement
  06-03 13:03:10.041  2041  2041 I SecureElement-Terminal-eSE1: eSE1 was initialized
  06-03 13:03:10.042  2041  2094 I SecureElement-Terminal-eSE1: OnStateChange:true
  06-03 13:44:53.772  2041  2041 I SecureElementService: main onBind
  06-03 13:44:53.775  2041  2056 D SecureElementService: getReader() eSE1
  06-03 13:44:53.778  2041  2056 W SecureElement-Terminal-eSE1: Enable access control on logical channel for com.felicanetworks.mfc

But with Magisk19203(logcat_V19203.log)
  06-03 15:57:09.662   610   610 W hwservicemanager: getTransport: Cannot find entry android.hardware.secure_element@1.0::ISecureElement/eSE1 in either framework or device manifest.

**Comment by patrickschneider23** [comment]
@nakashy

**Comment by alvinhochun** [comment]
Very likely related: I have a SIM card with a Secure Element for nfc payment (*not* Osaifu-Keitai and *no* eSE) which *just works* through the NFC chip (i.e. other NFC readers are able to detect the payment "card"), but the App by the service provider is unable to communicate with the SIM card via SEService
to read the remaining balance.

I had the latest Magisk (19.3) installed. So I tried downgrading to [19.0] and to my surprise said App is now able to communicate with the SIM card. I then tested [19.1] in which said app appears to *not* work.

[19.0]: https://raw.githubusercontent.com/topjohnwu/magisk_files/307ea862ab66203602c5c1e2eb20180196472ca6/beta.json

[19.1]: https://raw.githubusercontent.com/topjohnwu/magisk_files/d7184d2142e2e6b022972b4508bd6a6224d1c214/stable.json

So I also checked the other canary versions. Here are the results:

| Magisk Version        | App Working? |
|-----------------------|--------------|
| 19.0                  | Yes          |
| 19.0-3eae9494 (19001) | Yes          |
| 19.0-da3937ff (19002) | No           |
| 19.0-82ea9db9 (19003) | No           |
| 19.1                  | No           |
| 19.3                  | No           |

Skimming through the [changes between 19001 and 19002][changes], I don't really see anything suspicious yet... I hope this can help hunting down the issue.

[changes]: https://github.com/topjohnwu/Magisk/compare/3eae9494...da3937ff

Device: Pixel 3a US version (no eSE)
Android version: 9 (sargo-pq3b.190605.006)

---

I don't get the log messages similar to what @nakashy got unless I manually kill the process `com.android.se`, but here's what I get when I do so:

**Magisk 19.0**:

```
06-11 xx:34:35.467 12440 12440 I SecureElementService: main onCreate
06-11 xx:34:35.470   542   542 W hwservicemanager: getTransport: Cannot find entry android.hardware.secure_element@1.0::ISecureElement/eSE1 in either framework or device manifest.
06-11 xx:34:35.471 12440 12440 I SecureElementService: No HAL implementation for eSE1
06-11 xx:34:35.473 12440 12440 I android_os_HwBinder: HwBinder: Starting thread pool for SIM1::android.hardware.secure_element@1.0::ISecureElement
06-11 xx:34:35.478 12440 12440 I SecureElement-Terminal-SIM1: OnStateChange:true
06-11 xx:34:35.479 12440 12440 I SecureElement-AccessControlEnforcer: Allowed ACE mode: ara=true arf=true fullaccess=false
06-11 xx:34:35.508 12440 12440 I SecureElement-AraController: Refresh tag has changed.
06-11 xx:34:35.508 12440 12440 I SecureElement-AraController: Read ARs from ARA
06-11 xx:34:36.001 12440 12440 I SecureElement-AccessControlEnforcer: ARA applet is used for:SIM1
06-11 xx:34:36.003 12440 12440 I SecureElement-Terminal-SIM1: SIM1 was initialized
06-11 xx:34:36.004   542   542 W hwservicemanager: getTransport: Cannot find entry android.hardware.secure_element@1.0::ISecureElement/SIM2 in either framework or device manifest.
06-11 xx:34:36.005 12440 12440 I SecureElementService: No HAL implementation for SIM2
```

**Magisk 19.3**:

```
06-11 xx:57:26.490 11242 11242 I SecureElementService: main onCreate
06-11 xx:57:26.492   552   552 W hwservicemanager: getTransport: Cannot find entry android.hardware.secure_element@1.0::ISecureElement/eSE1 in either framework or device manifest.
06-11 xx:57:26.493 11242 11242 I SecureElementService: No HAL implementation for eSE1
06-11 xx:57:26.493   552   552 W hwservicemanager: getTransport: Cannot find entry android.hardware.secure_element@1.0::ISecureElement/SIM1 in either framework or device manifest.
06-11 xx:57:26.493 11242 11242 I SecureElementService: No HAL implementation for SIM1
```

**Comment by alvinhochun** [comment]
Just did a git bisect and it points to the commit 0149b1368d7f508e0c1bde47ba217ac9ae81976a.

@topjohnwu Any ideas?

**Comment by alvinhochun** [comment]
Update: I'm happy to say that the payment app for my SIM is **now working** (as in successfully reading the remaining balance and transaction history) on the latest canary **19.4-dd6e55ac (19303)**, likely due to the MagiskInit rewrite for system-as-root devices. Though I did not test build 19302 so I could be wrong.

**Comment by nakashy** [comment]
I confirmed !!!
FelicaClient works fine with 19.4-dd6e55ac (19303).

**Comment by sfai05** [comment]
Hi @alvinhochun , are you using the CSL Octopus NFC SIM card ?

**Comment by zen-U** [comment]
FeliCa Client worked properly with Magisk-v19.4-dd6e55ac (19303).  topjohnwu Thank you for correspondence.

**Comment by alvinhochun** [comment]
> Hi @alvinhochun , are you using the CSL Octopus NFC SIM card ?

Yes, but it should be the same for any SIM cards that utilizes similar technologies.

**Comment by topjohnwu** [comment]
Thanks for the confirmation, @zen-U !
