### ISSUE TITLE
Screen sleep timeout interrupted if root request accepted in background

### ISSUE THREAD

**Issue by Senliast** [topjohnwu/Magisk#1512]
If root request accepted in background too often, screen doesn't sleep. As I understand, the screen timeout will be reset. For example if screen sleep time set to 2 minutes, and background root requests accepted often, than every 2 minutes, and screen never sleep.

Latest Magisk Canary, Pixel 2 Pie ROM.

**Comment by topjohnwu** [comment]
That is none of my business, don't use that crappy app that isn't written correctly

**Comment by Senliast** [comment]
I am sorry, but it is script, that continuously runs in background and fixes Google Pay. Every certain amount of time, it resets G Pay databases, so that the attestation success. At this time, it cannot be made on an another way.
If it's complicated for you to fix it right now - no problem.
