### ISSUE TITLE
Latest canary build broke many things

### ISSUE THREAD

**Issue by AaronKeener** [topjohnwu/Magisk#1515]
Hello @topjohnwu

On the latest Magisk canary build (19203), can't open a number of apps like Terminal emulator, Spotify, online games (ex : PUBG, boom Beach, etc...)

Spotify also closes itself in the recents menu

ROM : OxygenOS Open Beta 10 (Android Pie)
Device : OnePlus 6T

Can't take logcat since Terminal emulator crashes at launch.
Also, Magisk logs are empty

**Comment by topjohnwu** [comment]
Try uninstall and resinstall, there is nothing big changed between 19202 to 19203
