### ISSUE TITLE
Magisk Modules not working - SGP771 Sony Xperia Z4 Tab

### ISSUE THREAD

**Issue by elimn8r** [topjohnwu/Magisk#1516]
[magisk_log_20190528_214147.log](https://github.com/topjohnwu/Magisk/files/3227528/magisk_log_20190528_214147.log)

SU working but I can't get any modules to work.

**Comment by topjohnwu** [comment]
`10-15 09:57:17.469   576   577 E Magisk  : mount /sbin/.magisk/block/system->/sbin/.magisk/mirror/system failed with 1: Operation not permitted`

Your kernel does not allow mounting mirrors, nothing I can do about
