### ISSUE TITLE
Magisk - Core Only Mode even after disable

### ISSUE THREAD

**Issue by ariel-** [topjohnwu/Magisk#1519]
Hi! I installed magisk through TWRP on a galaxy tab 3. I can't get Magisk to work (using su in adb stops for a few secs then returns with 'permission denied', there is no prompt to grant su to shell process)

Also it's always in Core only mode. Even after disabling it and then rebooting, it is enabled again.

Furthermore when I save logs they come as empty:
![](https://i.imgur.com/veU03yD.png)

I saved them as a screenshot then transferred to my computer:
![](https://i.imgur.com/miKz1li.png)

Any ideas? I already visited #1221 and #1494. The former did not help (ie uninstalling then flashing again), while the later was closed without response.

**Comment by topjohnwu** [comment]
API 17 is barely tested at all, a lot of things are bound to be broken.
If you can, please try to upgrade your device to a newer Android version....
