### ISSUE TITLE
Is there a safe way to manually put a stock img for magisk to restore?

### ISSUE THREAD

**Issue by zzj0311** [topjohnwu/Magisk#1521]
Hi, I'm using magisk 19.2 on my oneplus 7 pro are since there's not a fully functional custom recovery till now so I just follow  [this](https://forum.xda-developers.com/oneplus-7-pro/how-to/guide-root-oneplus-7-pro-patched-boot-t3931205) to get magisk work. And here comes the problem, I do not have a stock image backup thus an OTA update won't happen. Since there's tool to extract stock img from the factory image under the same sys version so may I just zip the img ,rename it and place to the exact location and it would just work or it just break everything, thanks!

**Comment by Didgeridoohan** [comment]
This is a bug/issue tracker, not a support forum.
