### ISSUE TITLE
Busybox selinux support

### ISSUE THREAD

**Issue by Tungstwenty** [topjohnwu/Magisk#1523]
If possible, please activate the selinux build option so that applets such as "ps", "ls", etc. support the -Z flag and are able to show the selinux context.
I find myself needing to use the toolbox utilities in such cases instead of always relying on busybox.

**Comment by mirfatif** [comment]
An alternate busybox with SELinux enabled: https://github.com/yashdsaraf/bb-bot/releases

**Comment by alexa-v2** [comment]
I think the busybox included is kinda lacking in general though, not just this
