### ISSUE TITLE
Can not get kernel com port after root.

### ISSUE THREAD

**Issue by rosir-zhong** [topjohnwu/Magisk#1527]
We use Magisk Manager to fix boot.img, and download the magisk_patched. The android 7.1 system root successfully. Then we use the  SN_Writer Tool to Write IMEI, and it can not get the kernel com port for writing IMEI. The hardware platform is MT6739 of MediaTek Inc. Waiting for help, thanks.

**Comment by topjohnwu** [comment]
You did not provide any info, am I a god?
