### ISSUE TITLE
CTS mismatch + High CPU usage on Xperia C3 running V12

### ISSUE THREAD

**Issue by ghost** [topjohnwu/Magisk#153]
I'm running the Xperia C3 on stock 5.1.1 rom. I keep getting CTS mismatch on all Magisk versions, and it doesn't seem to be hiding root as well. 

Also, I get high CPU usage from magiskhide process, and it won't go away after an hour. This happens only on v12, the earlier version works fine.

Stock boot image: https://www.dropbox.com/s/l2zm4v5pfodhcz5/boot.img?dl=0
Modified kernel boot.img: https://www.dropbox.com/s/l2zm4v5pfodhcz5/boot.img?dl=0

[magisk_error_20170331_172810.txt](https://github.com/topjohnwu/Magisk/files/885155/magisk_error_20170331_172810.txt)

**Comment by TheComputerGuy96** [comment]
@topjohnwu @AngryManjuu I also have high CPU usage problem

**Comment by farovitus** [comment]
With V13.3, using Samsung G955F, we are also having this kind of issue, 
- Android Os drains as much as the screen does.
- Other interesting issue, all cpu cores locked at max freq. How to solve ? Flash supersu than fully uninstall supersu and flash magisk :) 

let me know if you need some logs or ...
