### ISSUE TITLE
preserve options in 7.2.0 not visible on Shield

### ISSUE THREAD

**Issue by theVanZan** [topjohnwu/Magisk#1535]
I can see the "preserve avb2.0" and "force encryption" options in 7.1.2 but they're missing in 7.2.0. This is on a Shield TV 2017. The options show up in 7.2.0 on other devices i.e my GPD XD Plus.

**Comment by topjohnwu** [comment]
@diareuse any idea?

**Comment by diareuse** [comment]
It was only hidden when no root is detected. From 7.2+ these options are not hidden anymore and are permanently visible regardless of root state. https://github.com/topjohnwu/Magisk/commit/fc26de48b283ec2d96e9580fc1384fad757421b6

**Comment by theVanZan** [comment]
Is there any way to use the patch boot.img option in 7.1.2 without being forced to update? Cos the preserve option is visible in that version. When I click "install" for Magisk it basically gives me no other option but to update Magisk Manager.

**Comment by topjohnwu** [comment]
Unfortunately, Magisk Manager is required to be updated in order for things to work properly.
A new release should be out soon, scheduled to be this weekend, so please stay tuned for the update
