### ISSUE TITLE
Magisk 19.2 error

### ISSUE THREAD

**Issue by scarzx** [topjohnwu/Magisk#1538]
the password was correct but the data  is corrupted error after installing v19.2 And restarting, reverting back to 18.1 fixed it.... (Huawei p9 lite)

**Comment by DenyDarko** [comment]
No logs, no device info.

What an awesome bug report for a psychic.

For the rest of the mortals logs are needed:

https://www.didgeridoohan.com/magisk/MagiskHelp

**Comment by scarzx** [comment]
https://pastebin.com/J2hDiFC6

**Comment by topjohnwu** [comment]
#1409
