### ISSUE TITLE
Mechanism for updating Magisk Manager modules by the repo

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#1539]
Hello John,

From last news, when a module is updated on the Magisk Modules repo, it's the `versionCode` that is compared with the one locally present on the device?

I ask the question because I have one of my modules that has a defect, I can put a higher number for `versionCode` than the one on repo, and the module remains waiting for update on my Magisk Manager and that of my testers.

For the moment, whatever version number I assign to the online module, it appears as not updated on the devices on which it is installed.

**Comment by topjohnwu** [comment]
If thats the case, its an issue with the UI in Magisk Manager, nothing to do with the repos
