### ISSUE TITLE
Bug when showing the modules description

### ISSUE THREAD

**Issue by mythio** [topjohnwu/Magisk#1541]
Magisk version: 19.2
OS: Android Pie 9.0

When in Downloads section, and click on any module. If your network is slow, or if you quickly press the back button, the app goes to magisk home, and then over it the description dialog is displayed. It is not that much of a problem, but after you've left that section, it makes no sense to display the dialog.

**Comment by topjohnwu** [comment]
This is not a bug. The description is downloaded asynchronously and shown once the download it completed. I don't think it is worth the effort to "fix" this issue by requiring to change fundamentally how it works
