### ISSUE TITLE
Hidden Magisk Manager cannot detect Magisk.

### ISSUE THREAD

**Issue by Tornado15550** [topjohnwu/Magisk#1542]
On a fresh Magisk installation, hiding Magisk Manager repackages Magisk Manager and scrambles the package name as expected, but the new re-packaged Manager app can no longer detect Magisk.

Steps to reproduce:
1) Completely uninstall magisk along with any/all modules. 
2) Install the latest Magisk built from source through TWRP. The regular Magisk Manager appears and Magisk works as intended. 
3) Re-package Magisk Manager
4) Manager re-packages successfully
5) Open the re-packaged Manager. 

Expected Behavior: Magisk should be detected by the re-packaged Manager and function normally. 

Actual Behavior: Re-packaged Manager states Magisk is no longer installed. 

Re-installing the non-repackaged Manager (via APK) detects Magisk once again and works normally.

OS: Android Q Beta 3
Device: Pixel 2 XL
Architecture: arm64

Two screenshots have also been included which showcase:
1) Magisk working normally when not re-packaged:- 
![Screenshot_20190531-024959](https://user-images.githubusercontent.com/5608158/58747098-95980300-8423-11e9-892e-0ba3066fed7f.png)

2) Magisk no longer being detected by the re-packaged Manager:- 
![Screenshot_20190531-025109](https://user-images.githubusercontent.com/5608158/58747105-9e88d480-8423-11e9-8757-208a01bc566d.png)

Logs: attached below:-
[magisk_log_20190531_024222.log](https://github.com/topjohnwu/Magisk/files/3244806/magisk_log_20190531_024222.log)

More detailed logs and context can be found here: https://github.com/diareuse/Magisk/issues/8

**Comment by martyfender** [comment]
I have the same issue on my Nextbook Ares 8A, Intel x86, Android 6.0.1 tablets on the latest Canary build. In addition, I usually have global namespace set in MM and it is showing in in MM as inherit thd requestors namespace. In the magisk.log attached it is showing global. 
[magisk.log](https://github.com/topjohnwu/Magisk/files/3245096/magisk.log)

**Comment by AaronKeener** [comment]
Issue confirmed on OnePlus 6T Open Beta 11 (Android Pie)

**Comment by Tornado15550** [comment]
This issue has now been fixed and Manager can successfully detect Magisk when hidden. I will proceed to close it now. Thanks for the quick fix! :)

**Comment by AaronKeener** [comment]
It isn't fixed for me
