### ISSUE TITLE
cannot exit from su after started a shell daemon

### ISSUE THREAD

**Issue by eebssk1** [topjohnwu/Magisk#1544]
Hi.
I rencently found that my shell daemon no longer shows up in htop after boot.So i try to run it in juicessh with magisksu.The shell daemon successfully gone into background and ran properly.But when i invoke exit on the shell,the shell just stuck at there.
Without the shell daemon,i can exit from su normally.I don't know what causes this(seems only happen after [include]19.2).
note that i start the shell daemon in service.sh in a module.
The cmd that i run the shell daemon:setsid nohup nice -n 5 ionice -c 3 -t /system/bin/cpsc > /dev/null &

update1:After i killed the shell daemon,the stucked su successfully exited.But shoudn't setsid nohup detach proccess from su shell?

**Comment by mirfatif** [comment]
This problem is from days of SuperSU. Any process started from `su`'s shell can't detach from terminal. May be some issue with pseudo-terminal implementation. A workaround is to use `screen`/`tmux` above `su`.

**Comment by topjohnwu** [comment]
@eebssk1 the root shell is not the same thing as a local shell; it is a remote shell.
Think of it more like an SSH connection :)

**Comment by mirfatif** [comment]
@topjohnwu I have added some relevant details to above comment. This behavior sometimes gets irritating, though not a big hurdle. In my situation I run a Linux environment on Termux which does have background processes running. And if I forget to run `tmux` above `su` and accidentally do `exit`, the shell hangs. Consider fixing if possible.
