### ISSUE TITLE
Magisk Manager FR translation issue

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#1546]
Hello 
I get French font issue with last Magisk Manager:

![Screenshot_20190603-175108](https://user-images.githubusercontent.com/20888017/58815675-54247500-8628-11e9-80e9-4e011bfd47a9.png)

Normaly, the `_` carachter between the word `Voulez` and the `vous` should be `-`, and the same strange issue happen for the `?` carachter at the end of the text string.

I don't know if this issue happen also for other French users, i haven't see an similar issue on the repo.
Apart this issue, everything related Magisk works fine.
I already have try to change it to Spanish language, the issue don't happen.

Concerning the file translation, the [corresponding line](https://github.com/topjohnwu/Magisk/blob/80d834fb5587906d77dbb0dc83d056da23ffe0bb/app/src/main/res/values-fr/strings.xml#L92) is writed normaly.

Curiously, it also happen for the `SUPER-USER` (SUPER-UTILISATEUR in French) title in the log tab, and the [corresponding line](https://github.com/topjohnwu/Magisk/blob/80d834fb5587906d77dbb0dc83d056da23ffe0bb/app/src/main/res/values-fr/strings.xml#L6) looks like good.
![Screenshot_20190603-180019](https://user-images.githubusercontent.com/20888017/58816479-e7aa7580-8629-11e9-9633-17296ea9d772.png)

Can some French users can check that ?

**Comment by AaronKeener** [comment]
It looks like it's an issue w/ your system font, Don't have that problem w/ OnePlus Slate font

Ça doit être un problème avec la police que tu utilise sur ton portable, je n'ai pas ce problème avec la police OnePlus slate

**Comment by xerta555** [comment]
> I see that you have caprica font module installed, please consider disabling it and check if the problem still occurs

Effectivly, my issue was due to my Caprica font, i'm going to see why it happen.
Ty again.
