### ISSUE TITLE
Patched image not compatible with Moto G7 Play (channel)

### ISSUE THREAD

**Issue by ctonton** [topjohnwu/Magisk#1547]
Magisk Manager does not recognize that it has been installed after patching and flashing the boot.img. Patched image is a considerably smaller file size than the OEM boot.img. Fastboot log shows a wrong filesize error upon flashing the patched image. I have attached the OEM boot.img for this device. Thanks in advance for any help with rooting this phone.
Model: Moto G7 Play (channel)
Software version: CHANNEL_PPY29.105_57_cid50_subsidy_DEFAULT_regulatory_XT1952_2_MEXICO_CFC
[boot.img.zip](https://github.com/topjohnwu/Magisk/files/3250340/boot.img.zip)

**Comment by topjohnwu** [comment]
Please try the latest canary. Report again if it doesn't fix the issue.
