### ISSUE TITLE
[Feature Request]: Keep dm-verity disabled for Force encryption disabled devices.

### ISSUE THREAD

**Issue by SrikanthSd** [topjohnwu/Magisk#1549]
On stock miui devices after flashing twrp for the first time, we have to flash separate patch to disable Force encryption then Later magisk to disable dm-verity and gain root.

But when running magisk uninstaller, It will flash untouched stock boot.img then dm-verity comes back. dm-verity detecting changes in the system(i..e Force encryption disabled) causing bootloop. 
To avoid this, magisk should keep dm-verity disabled in the boot.img even after running uninstaller.

Sorry if im unclear!

**Comment by indianets** [comment]
Isn't this achieved by making /data/.magisk file in TWRP before flashing magisk with

KEEPVERITY=false

I have not tried this recently in the exact situation as you, but previously I have used .magisk.

**Comment by SrikanthSd** [comment]
To prevent bootloop, Everytime i had to remove stock boot.img which is backed-up by magisk and run uninstaller.
It will remove remove magisk in the current boot keeping the dm-verity disabled. 
It is the only solution to remove root.

**Comment by topjohnwu** [comment]
There is an option for you to disable dm-verity in Magisk Manager
