### ISSUE TITLE
Some apps not Shown For Hide

### ISSUE THREAD

**Issue by jahmadiiiii** [topjohnwu/Magisk#1551]
Hi 
I tested magisk 19.3 and some apps not shown in Magisk Hidr part to use hide to avoid know about root status!

This apps Include "Chrome latest version" and some times "YOUTUBE"

App version: 19.3 For service & 7.2.0 for app side

I test on 2 phone, J5 2016 stock 7.1.1 and a8 2018 stock 7.1.1.

Please Test and Fix this problem also check other google apps.

Best Regard

**Comment by AaronKeener** [comment]
Did you tried checking "show system apps" in the 3 dot menu in Magisk Hide ?

**Comment by topjohnwu** [comment]
^ this

**Comment by jahmadiiiii** [comment]
Why Close ths Issue, i forgot to say i also Checked  "Show System Apps" and found no this apps.

**Comment by jahmadiiiii** [comment]
@topjohnwu Plz take a look again
