### ISSUE TITLE
Inapp uninstaller removed gapps

### ISSUE THREAD

**Issue by MartinX3** [topjohnwu/Magisk#1552]
I used the magisk manager v7.2.0 to uninstall magisk 19.2.
After a reboot not only the app and magisk are away, it removed my google play services, the playstore, etc...

And a reinstallation of the pico gapps.zip on my omnirom 9.0 don't bring them back.
Installation of magisk 19.3 doesn't bring them back.
Just flashing the vanilla boot.img doesn't bring them back.

[bugreport.zip](https://github.com/topjohnwu/Magisk/files/3256886/bugreport.zip)

Flashing the vanilla boot.img, then the pico gapps and then magisk 19.3 helped.
It must be in this order to restore the gapps.

But it wants now to set up the device again for gapps.

A restart takes me into a unlimited "Device gets started..." dialogue with black background.
Forced a restart, now the device booted, but the playstore is still not working.

Reflashed vanilla system.img and reapplied pico gapps.
Now my google account got removed from the system and it wants to reapply the google set up assistant like on a full wiped phone.
Restarted the phone again.

Seems to work now.

**Comment by topjohnwu** [comment]
Uninstaller does not touch any of the things you just mentioned

**Comment by AaronKeener** [comment]
@MartinX3 If you lose root access, apps that need root/Magisk modules to be installed just diseappear, not an issue, and... If you want to update to 19.3,why uninstall 19.2 ? Just make an update

**Comment by MartinX3** [comment]
@aaronkeener
"You're Holding it wrong" is not usefull.
Update, uninstall and clean installation need to work.

And did you read carefully what I wrote?
Gapps (playstore and play services, etc.) need root? Are you sure?

And apps which need root doesn't disappear from the launcher and the app list.
They just may become unusable if the developer didn't catch the exception of a root deny.
