### ISSUE TITLE
Boot image patch: options no longer visible

### ISSUE THREAD

**Issue by smx-smx** [topjohnwu/Magisk#1554]
Commit b2fa5b551ece08936e4f6411079b9b826f957394 hides advanced install options (e.g keep dm-verify) when the device is not rooted.

I've been using a script that automatically
- boots TWRP
- pulls boot image from /dev (dm-verify is enabled)
- reboots to Android and launches the Magisk app
- [user patches the boot image, keeping dm-verify on]
- the patched boot image is pulled and flashed through fastboot

Since the new Magisk Manager release, this use case is no longer possible.
Is it possible to bring the old behaviour back?

Thanks

**Comment by Didgeridoohan** [comment]
https://github.com/topjohnwu/Magisk/commit/fc26de48b283ec2d96e9580fc1384fad757421b6
