### ISSUE TITLE
Android P is stopping my module from running in the background

### ISSUE THREAD

**Issue by AeonLucid** [topjohnwu/Magisk#1555]
I made an executable that starts a daemon like [this](https://stackoverflow.com/questions/17954432/creating-a-daemon-in-linux/17955149#17955149) using Android NDK.

In the Magisk module I have this in `set_permissions` (next to the default one):
```
set_perm "$MODPATH/system/bin/myexecutable" 0 2000 0755 u:object_r:system_file:s0
```

`LATESTARTSERVICE` is also enabled and service.sh contains:
```
myexecutable
```

It works but after a bit I see the following message in logcat:
```
E/OHPD: [BgDetect] AppForkedProc myexecutable pid 1121 uid 0 can't find pkgName
```

How can I prevent this from happening?

**Comment by topjohnwu** [comment]
This has nothing to do with Magisk itself, and also this Github issues is not a support platform

**Comment by AeonLucid** [comment]
Sorry for that.
