### ISSUE TITLE
Package names in Magisk Hide

### ISSUE THREAD

**Issue by localacct** [topjohnwu/Magisk#1556]
Hi

My apologies because I do not think this is Magisk related but I have no idea where to start searching, so I am posting it here.

In Magisk Hide, I can choose the applications that Magisk should hide from. Normally, I will see a package name such as "ru.xxxx.zzzz" under a particular application. However, sometimes, I also see a name such as  "ru.xxxx.zzzz:transferservices" under the application name as well.

Does anyone has any idea how that came about? Using other tools such as Frida and ps to list the processes in the Android device does not show a process with the name "ru.xxxx.zzzz:transferservices".

Searching online does not yield much details either.

My apologies again for asking a somewhat not so related question.

**Comment by topjohnwu** [comment]
Magisk Manager scans through all your apps and show you a list of all possible process an app can create in the menu. That is what you are seeing here. ru.xxx.zzzz:transferservice is mostly a daemon service of the app that spawns it own process, working independently outside of the application.
