### ISSUE TITLE
Can I root Vivo V15 Pro with latest Magisk?

### ISSUE THREAD

**Issue by topaloglu321** [topjohnwu/Magisk#1557]
I need to root my Vivo V15 Pro. Is it possible to do it with latest Magisk?

**Comment by AaronKeener** [comment]
Magisk github is not the place to ask this, it's not a support.

**Comment by topaloglu321** [comment]
Sorry for that but how can I learn?

**Comment by AaronKeener** [comment]
Well, I think searching on xda developers would be a good start.

**Comment by topjohnwu** [comment]
Prey and ask God :)
