### ISSUE TITLE
Magisk 19.3 - Core Only Mode Enabled ALWAYS

### ISSUE THREAD

**Issue by carlos6034** [topjohnwu/Magisk#1558]
Hi there, so to be as brief as possible.

I just installed a ROM on my J7 Pro to upgrade from android 8.1 to 9.0 (if it helps at all the variant is J730G/DS).

When installing magisk I noticed my modules were not enabled, and then I saw that Core Only Mode was enabled. Tried disabling it and rebooting no luck, still comes on after booting up.

Tried different methods like using older version of the magisk apk and not using version 19.x.
Even tried completely uninstalling and installing again but no luck at all. 

There are no anomalies on logs so I won't post them for now, but if requested I will try to do it. 

PD: Yes, I've read previous threads on this issue but I think the problem is not API or Android version, so please just don't close it.

**Comment by AaronKeener** [comment]
I suggest you flashing the "Magisk manager in  TWRP , and then disable core only mode Into TWRP"

**Comment by carlos6034** [comment]
I do always flash magisk through TWRP, currently running 19.4 Canary. What I do not know is how to disable core only mode in TWRP.

Mind a quick explanation?

**Comment by AaronKeener** [comment]
I'm not talking about magisk, I'm taking about a module named :"Magisk Manager in recovery mode" that you can flash through TWRP and use to disable core only mode through TWRP's terminal

**Comment by carlos6034** [comment]
Now I get it, I'll try that right now

**Comment by carlos6034** [comment]
UPDATE: Disabling through TWRP didn't work

**Comment by AaronKeener** [comment]
Well...I don't have any other idea to fix your problem :/

**Comment by carlos6034** [comment]
Thanks for the help though Aaron, I will keep that in mind.

I would suggest the mods to keep this thread opened until this is solved. We don't know who else might be experiencing this issue.

**Comment by topjohnwu** [comment]
You want to keep this open, but yet does not provide any info regarding the issue....

**Comment by carlos6034** [comment]
Well after being closed, I can just say it was a ROM problem

**Comment by Untzo** [comment]
I have the same problem on my lg g5

**Comment by rCan9** [comment]
same problem here. dont know how to fix
