### ISSUE TITLE
Hidden Manager can't detect that Magisk is installed

### ISSUE THREAD

**Issue by AaronKeener** [topjohnwu/Magisk#1559]
I open this issue because I have the exact same problem as mentionned in
https://github.com/topjohnwu/Magisk/issues/1542
But since I don't use ianmacd unofficial Magisk build the problem isn't fixed for me 

I'm on OxygenOS Open Beta 11 (Android Pie) on OnePlus 6T

**Comment by Didgeridoohan** [comment]
Well... Then you wait for an official release, right?

**Comment by AaronKeener** [comment]
No, just waiting for a bugfix, I'm on canary build

**Comment by Didgeridoohan** [comment]
I'm curious... What's the point of this GitHub issue? The problem has been resolved, just not yet released officially. It will be, so what you can do is to build yourself, use an unofficial build, or wait.

**Comment by AaronKeener** [comment]
The point is to make John, or diareuse (idk who's on manager issues) add the fix to the actual canary build, like on any other issue, but I'll just wait I guess.

**Comment by Didgeridoohan** [comment]
That's what I'm saying... It will be released officially when it's ready to release. Time to close this.

**Comment by AaronKeener** [comment]
Isn't the point of closing issues telling everyone that's fixed ?
