### ISSUE TITLE
Magisk doesn't patch ro.build.fingerprint and ro.build.description props

### ISSUE THREAD

**Issue by TheComputerGuy96** [topjohnwu/Magisk#156]
Some source-built ROMs for some devices don't use stock ROM ro.build.fingerprint and ro.build.description  props, so they use ROM-generated ones, which aren't CTS certified and that issue causes CTS profile mismatch (An example of device tree which doesn't have them: https://github.com/Samsung-KYLEPROXX/android_device_samsung_kylepro)

So patch them with some CTS-certified ro.build.fingerprint and ro.build.description props, @topjohnwu

**Comment by Didgeridoohan** [comment]
That's something you easily can do yourself with a Magisk module or script.

Topjohnwu has already stated he won't touch build props since it has to much potential to cause issues. Better to leave it to the user.

**Comment by TheComputerGuy96** [comment]
OK
