### ISSUE TITLE
Magisk version checking mechanism.

### ISSUE THREAD

**Issue by AreYouLoco** [topjohnwu/Magisk#1564]
I do get notifications about magisk update available but its even higher than recent one. I am using canary.

I suspect that the version detecting works just by comparing if its equal to the one available not checking if its higher. But I didnt go into code so I might be wrong.

Is it the case?

![Screenshot_20190607-212237](https://user-images.githubusercontent.com/6299176/59128465-67a64780-896a-11e9-9422-f05b1e67e2d1.png)

**Comment by alexa-v2** [comment]
You're not on canary

Canary is currently 19.4-somerandomletters

But I do also get random update notification when one isn't available

**Comment by topjohnwu** [comment]
It's a bug in the current version of Magisk Manager on the canary channel, nothing to worry about
