### ISSUE TITLE
Is my phone rooted?

### ISSUE THREAD

**Issue by YuGiOhJCJ** [topjohnwu/Magisk#1566]
Hello,

I installed [Magisk-19.3](https://github.com/topjohnwu/Magisk/releases/download/v19.3/Magisk-v19.3.zip) on my Xiaomi Redmi 6A using the [Custom Recovery method](https://topjohnwu.github.io/Magisk/install.html#custom-recovery) with [TWRP-3.3.1 (cactus)](https://eu.dl.twrp.me/cactus/twrp-3.3.1-0-cactus.img) and [no-verity-opt-encrypt-6.0](https://build.nethunter.com/android-tools/no-verity-opt-encrypt/no-verity-opt-encrypt-6.0.zip).

I expected to have a rooted phone after that.
However, it seems that my phone is not rooted at all:
```
$ ./adb shell
cactus:/ $ su
Permission denied
```
Is my phone rooted?

By the way, I can see the Magisk Manager app on my Home screen but I cannot run it because it requires Internet access: "Magisk Manager - Please connect to the Internet! Upgrading to full Magisk Manager is required. - OK".
I am sure that I miss some useful features included in this app but I don't want to connect my smartphone to the Internet (too many automatic bad things happen when I do that).
Can I disable this Internet access requirement for this app?

Also, since I have installed Magisk I have an error "Android system - There's an internal problem with your device. Contact your manufacturer for details. - OK" each time that I start the system.
I read in the Internet that I can fix that by using the Magisk Manager app and tweaking the settings.
However, as I said, I can't run the app.
Is there an alternative way to fix that like editing the zip file?

Thank you.
Best regards.

**Comment by callihn** [comment]
Use a wifi hotspot maybe?

**Comment by YuGiOhJCJ** [comment]
No, I just don't want to have Internet access on my phone because a lot of bad things happen when my device is able to access to the Internet. I always disable Data and Wi-Fi to avoid that.
Can you give an answer to my 3 questions please?
1) Is my phone rooted?
2) Can I disable this Internet access requirement for this app?
3) Is there an alternative way to fix that like editing the zip file?

**Comment by callihn** [comment]
How did you get the file without Internet?

1. Probably but without an su manager you can't give root permissions to an
app.

2. You can't install an app or parts of an app that you haven't downloaded
without internet access unless you have someone else download it and send
it to you using bluetooth which generally requires you to be in the same
room with that person.

3. Most likely not.

**Comment by YuGiOhJCJ** [comment]
I don't understand why Magisk Manager requires Internet access. I mean, this is version 7.2.0 that is already the last stable version. Internet access should be optional isn't it? If I really want to upgrade I could manually install a newer APK transferring it from my PC to my smartphone using USB and MTP.

**Comment by callihn** [comment]
Honestly I don't know why it does that. I've had it do that to me too at
times but it doesn't always do it so I'm not sure what's going on with it.
Though you might try iptables to firewall your phone. Many however already
have a quite robust set of iptables rules but you can check yours and set
it up to your liking then "bad things" shouldn't happen when you connect it
to the Internet and that would make life easier.

**Comment by alexa-v2** [comment]
The installed manager is only a stub; it's onyx purpose is to downloaded the full manager

It may also need to download a setup zip once installed too

Why are you so afraid of the internet but not of being rooted?

**Comment by callihn** [comment]
On that note, how does one download the full manager app? As there are
times that Internet may not be available or very slow during install.

**Comment by YuGiOhJCJ** [comment]
> Why are you so afraid of the internet but not of being rooted?
I am afraid of the Internet on my smartphone because as soon as I enable it my device is sending or receiving data and I don't know exactly what kind of data, maybe some private ones.
Also, my system shows notifications about updates that I can't remove if I don't install them.
Maybe it is just a behavior of MIUI 10, the stock Android I am using on my smartphone, but I really don't like that.
I don't see a reason to be afraid of being rooted.

> The installed manager is only a stub; it's onyx purpose is to downloaded the full manager
Oh, so please tell me how I can download the full manager app manually (using my PC) then installing it on my phone.

**Comment by callihn** [comment]
Your PC does the exact same thing in every way. It's checking for email,
backing up your app list and settings, checking for updates, etc. Just
general trivial stuff to give you a better experience, nothing personal
unless you set something up to do that. You can deny and or uninstall any
and all updates.

**Comment by YuGiOhJCJ** [comment]
> Your PC does the exact same thing in every way. It's checking for email, backing up your app list and settings, checking for updates, etc. Just general trivial stuff to give you a better experience, nothing personal unless you set something up to do that.

Indeed, my PC is sending and receiving data over the Internet but I trust my PC not my phone. On my PC, I built from source code each program that I am using, I reviewed their source code and I have tools to check what is sent or received over the Internet. On my phone, I have not built each program that I am using because it is a new device that I bought recently and I am not confident using it.
Moreover, I configured my PC to disable everything that is done automatically over the Internet.
So, my PC is checking for emails only when I ask him manually to do it, it is backing up things only when I ask him, ...

> You can deny and or uninstall any and all updates.

Maybe one day I will know how to do that.
I disabled a lot of settings to avoid this default behavior that I don't like.
However, currently it is doing things automatically over the Internet even if I configure my phone to not doing it.
That's why I don't want to connect it to the Interenet.
Anyway, I am new on Android/MIUI so I will learn to use it better.

**Comment by callihn** [comment]
Google it. Even at user level you can disable background data. As for
uninstalling just use the Playstore. All easier than a PC and Google has
the answers, just ask it.

**Comment by YuGiOhJCJ** [comment]
OK I fixed the problem!

Here are the steps:
1) Uninstall Magisk Manager (the one that was automatically installed after installing the zip file)
2) Build the Magisk Manager APK from source code (I guess that we can also use the one provided on GitHub)
3) Install this APK on the smartphone

Now, my phone is rooted:
```
$ ./adb shell
cactus:/ $ su
cactus:/ #
```

I will now try the Advanced Settings of Magisk Manager to fix the "Android system - There's an internal problem with your device. Contact your manufacturer for details. - OK" message appearing each time that I start the system...

**Comment by topjohnwu** [comment]
@YuGiOhJCJ please keep these kind of discussion (technical support) out of this development repo
