### ISSUE TITLE
Magisk Manager truncating version info in lite theme

### ISSUE THREAD

**Issue by callihn** [topjohnwu/Magisk#1568]
When using the lite theme in Magisk Manager on the latest Canary version the version information for Magisk Manager is truncated. Issue does not exist in the dark theme and just started with this version.

Can't seem to attach screenshots...
content://media/external/file/5065
content://media/external/file/5066
content://media/external/file/5067

**Comment by topjohnwu** [comment]
Doesn't seem to be the case on my device

**Comment by callihn** [comment]
Ohh I didn't know this was being made for one device only.

**Comment by callihn** [comment]
Which device do you have? I'll save up and get me one of those.

**Comment by Didgeridoohan** [comment]
If you want to report an issue you have to do it properly... There's no info here that anyone can do anything with, so the issue got closed.

**Comment by callihn** [comment]
What can I include that will make any difference? I want to include
screenshots including my device information but I couldn't seem ti do that
though I don't know how that would really help. In my mind there where
changes involving the light theme only since it doesn't exist in the dark
theme and it was in a recent commit as it did not exist in the last canary
version. There is no error to catch as it's only cosmetic and if not
running canary one would never notice it because the vesion lines and
install lines are much shorter.

I think overall many developers are a bit harsh when someone is just trying
to do the right thing, once you get to a certain level of involvement ti
report you're at a point where you can just fix it on your version and move
on. The benefit of reporting it is so that everyone can benefit and if I
where intimately familiar with the source I'd already know right where to
look and run a diff on the files involved.
