### ISSUE TITLE
Magisk 19.1: unable to boot after updating OnePlus 3T to LineageOS 16.0-2019607

### ISSUE THREAD

**Issue by chaoscommander** [topjohnwu/Magisk#1569]
Title says it all: I previously updated to the current version of Magisk successfully (should have been 19.1 from last week or so, can't check now since I had to delete it), but after installing the latest LineageOS update for OP3, the phone wouldn't boot anymore (screen went black after boot splash screen or never stopped showing it). After sideloading the Magisk Uninstaller via recovery, the phone boots again. Will provide additional details if you tell me what you need.

**Comment by topjohnwu** [comment]
If it used to work, but an LineageOS update breaks it, you know who to blame here
