### ISSUE TITLE
Device Support: ZTE Axon 7

### ISSUE THREAD

**Issue by Duir-XDA** [topjohnwu/Magisk#157]
This is further expanding on a previous issue [#59](https://github.com/topjohnwu/Magisk/issues/59) and possibly [#43](https://github.com/topjohnwu/Magisk/issues/43). As mentioned in issue #59, Magisk 10.3 beta 2 installs fine and grants root and can pass SafetyNet but any later version is not working properly. The last tickets were referencing older versions, but I have tried Magisk V12 and root with MagiskSU is not working.

I've uploaded the stock boot image for B19 (Android 7.1.1) of the device as well as the resulting boot.img after flashing Magisk V12 (the Magisk Patched boot is a TWRP backup). I've also included the Magisk.log (didn't show any errors) and the recovery.log from the install (also didn't notice any errors). I'll add more to what I've got including the 10.3 beta 2 patched boot (in case it will help) and a logcat in bit.

If you need any other information let me know as myself and others would love to see this device supported.

All files/logs can be found [here](https://www.androidfilehost.com/?w=files&flid=168400)

EDIT: No luck with logcat, some displayed nothing others wanted root which I didn't have. I did, however, upload the Magisk 10.3-beta2 Patched Boot.

**Comment by Duir-XDA** [comment]
![Uploading Magisk12_Screen1.jpg…]()
![Uploading Magisk12_Screen2.jpg…]()
![Uploading Magisk10.3-beta2.jpg…]()

**Comment by Duir-XDA** [comment]
Hit wrong button while trying to upload screenshots, sorry.

**Comment by topjohnwu** [comment]
Can you upload the zip that worked for you?
Thanks

**Comment by Duir-XDA** [comment]
Sorry for the delay.
You can find it [here](https://www.androidfilehost.com/?w=files&flid=169822)
It's part of a ROM install so the APKs for Magisk Manager and Superuser are separate from the Magisk installer ZIP. I uploaded all 3 to the linked folder.

**Comment by MaxRink** [comment]
yes, ur MagiskSu doesnt seem to work on the Axon 7. 
Stumbled across the same issue

**Comment by MaxRink** [comment]
@topjohnwu 
is there any log u would need to diagnose this?

**Comment by MaxRink** [comment]
ive just build myself magisk form ur upcoming v 13 tree.
The funny thing:
su works now, but magisk is broken.

**Comment by topjohnwu** [comment]
Magisk is not broken, what is broken is Magisk Manager  
The new version requires a new update to the manager, but I'd like to first stabilize the core part before start working on the application
