### ISSUE TITLE
Bootloop Xperia 10 Plus I4293 (Magisk Version 19.3)

### ISSUE THREAD

**Issue by samualdee** [topjohnwu/Magisk#1571]
Bootloop once it get to 'Powered by Android' Screen. Magisk 19.3.

**Comment by RebelliousX** [comment]
Same with I3223. In Magisk v18.1 it was working fine. The developer closed my issue #1421 saying I didn't provide logs.

I provided him a patched boot image with Magisk v18.1 that works. And the original boot that Magisk v19.X can't unpack / repack at all. I mean you do not need a log if the Magisk Manager can't even unpack boot image in v19.X. Something happened after v18.1 caused the issue.

**Comment by 8lexliu** [comment]
Have you tried to unzip the boot.sin to get the boot.000 then using magisk to patch it?

**Comment by samualdee** [comment]
Yes. 18.1 also worked for me.

**Comment by topjohnwu** [comment]
#1537
