### ISSUE TITLE
Magisk 19.3 Manager 7.2 - unable to install modules: unzip: invalid option -- j

### ISSUE THREAD

**Issue by malotur** [topjohnwu/Magisk#1572]
Hi, every time i try to install any module, either directly with the download or manually from filesystem, the installation fails (for example) with this log:

- Copying zip to temp directory
- Installing Show_Hide_Navigation_Bar-v1.0.zip
unzip: invalid option -- j
usage: unzip [-d DIR] [-lnopqv] ZIP [FILE...] [-x FILE...]
! Unable to extract zip file!
! Installation failed

The device is an android 8.1 headunit SC9853i based.

**Comment by M4XX1MUS** [comment]
I'm with same problem, my log:

- Device platform: arm64-v8a
- Existing zip found
- Copying image to cache
1022+1 records in
1022+1 records out
1047368 bytes transferred in 0.004 secs (261842000 bytes/sec)
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
! Unsupported/Unknown image format
! Installation failed

**Comment by topjohnwu** [comment]
@malotur it means your Magisk installation is not properly setup
@M4XX1MUS your issue has nothing to do with this issue

**Comment by M4XX1MUS** [comment]
@topjohnwu How can I solve this problem?
