### ISSUE TITLE
compiled error

### ISSUE THREAD

**Issue by cofface** [topjohnwu/Magisk#1573]
* Building binaries: magisk magiskinit magiskboot busybox

jni/utils/logging.cpp:32:12: warning: unused function 'log_d' [-Wunused-function]
static int log_d(const char *fmt, va_list ap) {
           ^
1 warning generated.
jni/utils/cpio.cpp:166:20: error: no member named 'extract' in
      'std::__ndk1::map<std::__ndk1::basic_string_view<char,
      std::__ndk1::char_traits<char> >, std::__ndk1::unique_ptr<cpio_entry_base,
      std::__ndk1::default_delete<cpio_entry_base> >,
      std::__ndk1::less<std::__ndk1::basic_string_view<char,
      std::__ndk1::char_traits<char> > >,
      std::__ndk1::allocator<std::__ndk1::pair<const
      std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char> >,
      std::__ndk1::unique_ptr<cpio_entry_base,
      std::__ndk1::default_delete<cpio_entry_base> > > > >'
        auto ex = entries.extract(e->filename);
                  ~~~~~~~ ^
jni/utils/cpio.cpp:204:20: error: no member named 'extract' in
      'std::__ndk1::map<std::__ndk1::basic_string_view<char,
      std::__ndk1::char_traits<char> >, std::__ndk1::unique_ptr<cpio_entry_base,
      std::__ndk1::default_delete<cpio_entry_base> >,
      std::__ndk1::less<std::__ndk1::basic_string_view<char,
      std::__ndk1::char_traits<char> > >,
      std::__ndk1::allocator<std::__ndk1::pair<const
      std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char> >,
      std::__ndk1::unique_ptr<cpio_entry_base,
      std::__ndk1::default_delete<cpio_entry_base> > > > >'
        auto ex = entries.extract(it);
                  ~~~~~~~ ^
2 errors generated.
make: *** [obj/local/armeabi-v7a/objs/utils/cpio.o] Error 1
make: *** Waiting for unfinished jobs....

Build binary failed!

**Comment by cofface** [comment]
build in windows.

**Comment by topjohnwu** [comment]
Build with FrankeNDK

**Comment by cofface** [comment]
I had build with FrankeNDK in windows same error.
