### ISSUE TITLE
Bootloop Sony Xperia 1  with Magisk 19.4 （16b232d2a)

### ISSUE THREAD

**Issue by yishisanren** [topjohnwu/Magisk#1574]
My phone is Sony Xperia 1, the mode is J9910.

Bootloop once it get to 'Sony' Screen. Magisk 19.4(16b232d2a)

I have tried to unzip the boot.sin to get the boot.000 , then use Magisk19.4 and 19.3 to patch it.
Bootloop every time, like Xperia 10 Plus or Xperia 10.

Use Magisk to patch the boot.sin, it says can not found the boot.img

**Comment by 8lexliu** [comment]
Works fine on https://github.com/topjohnwu/Magisk/commit/3eae9494cee56552702ba4104bc203d5ce4136ef

**Comment by yishisanren** [comment]
works fine on 19.0（19000），others are not good.

**Comment by MartinX3** [comment]
18.1 works too?
Then You suffer from the same bug I see on the XZ2, XZ3, XZ2P and XZ2C. (Tama plattform, directly predecessor of the Xperia 1).
I'll open now a bugtracker for my device (XZ2) and maybe it gets fixed.

**Comment by 8lexliu** [comment]
It seems like this issue affecting all Sony devices(running 9.0)?

**Comment by 8lexliu** [comment]
Seems like this issue affects all Xperia devices(running 9.0)? at least Xperia 1/10/10Plus/XZ3/XZ2

**Comment by MartinX3** [comment]
Xperia 10, too?
Gives me hopes that a single fix will repair it for every xperia device since 2018. :)

**Comment by topjohnwu** [comment]
#1537

**Comment by LucasZhaoting** [comment]
I have a xperia 10 too, also with magisk 18 can get root, after update cant. but i cant install modules, yes i can install, but after reboot dont appear i installed modules.
