### ISSUE TITLE
pixel xl无限重启，无法进入系统

### ISSUE THREAD

**Issue by dasdroid** [topjohnwu/Magisk#1579]
求助：刷了android9.0官方镜像，magisk18.1，正常使用了3个月，最近突然crash并无限重启，进bootloader重刷官方镜像还是无限重启，进fastboot boot进twrp后刷twrp进度条卡住退出recovery重启，刷Magisk-uninstaller提示“Cannot access /data,please uninstall with Magisk Manager”。

**Comment by topjohnwu** [comment]
I use Pixel XL daily, there should be no issues for that
