### ISSUE TITLE
Xperia XZ2 stock firmware bootloop since 19.1

### ISSUE THREAD

**Issue by MartinX3** [topjohnwu/Magisk#1580]
Until 18.1 / 19.0 the installation of the magisk on a clean stock rom was fine.
Since then it results into a bootloop.

The XZ2, XZ2C, XZ2P and XZ3 having this problem, seems that the [Xperia 1](https://github.com/topjohnwu/Magisk/issues/1574) (Our direct hardware successor) has the same problem.
So I assume a sony stock firmware compatibility problem.

Luckily I was able to extract the `/sys/fs/pstore` in TWRP.
I attached it:

Default stock setting in fstab for userdata -> crashing at Sony Logo
`encryptable=ice`
[console-ramoops-0.log](https://github.com/topjohnwu/Magisk/files/3276795/console-ramoops-0.log)

Modified stock setting in fstab for userdata -> crashing at Powered by Android logo
`encryptable=footer`
[console-ramoops-0.log](https://github.com/topjohnwu/Magisk/files/3276877/console-ramoops-0.log)
[dmesg-ramoops-0.log](https://github.com/topjohnwu/Magisk/files/3276878/dmesg-ramoops-0.log)

**Comment by topjohnwu** [comment]
#1537
