### ISSUE TITLE
Bootloader unlocked state not masked in magisk 19.3

### ISSUE THREAD

**Issue by HpNoTiQ56** [topjohnwu/Magisk#1586]
Hi,
Since version 19.3 and using every canary build since, I can't view Netflix in Playstore or running it on N5X and Pixel 3a but can do it with same magisks build on Samsung Galaxy A5 2017 running Pixel Experience.
I think that bootloader state is not well hidden with magisk 19.3. 
I can submit log if needed.

**Comment by topjohnwu** [comment]
Nothing is changed regarding that part
