### ISSUE TITLE
UI Uninstall option modification

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#1587]
This is a request for @diareuse I guess xD

I was wondering if you might find it interesting making the Uninstall option not a tap but a slide or a tap-and-hold or something like that which will make accidents a bit more difficult. 

It's not necessary, and it's minor. 

But I thought to propose it 😊

**Comment by diareuse** [comment]
Hey,
the app already shows a dialog asking whether you're certain about that action 😄
Hence I wouldn't call this an accident, specifically when you have to consecutively click two distinct buttons 😃
I guess you're proposing a design element rather than prefix then

**Comment by diareuse** [comment]
In that case I'll take that into consideration when redesigning the app. Thanks for your input
