### ISSUE TITLE
Magisk causes LOS Updater to crash

### ISSUE THREAD

**Issue by nate2014jatc** [topjohnwu/Magisk#1590]
Given, the circumstances are specific, but quite easy to replicate.
https://gitlab.com/LineageOS/issues/android/issues/503

The LOS people closed the issue, quite sure that it was due to Magisk.

**Comment by alexa-v2** [comment]
How can you confirm its magisk? Do you have logs? What's your device and ROM/version?

**Comment by topjohnwu** [comment]
Sorry, but I'm not willing to fix bugs for custom ROMs (don't have the time to do so).
If someone can point out to me what I can adjust to fix this, I will happily merge/do the fix.
