### ISSUE TITLE
Download section not loading (or loading an incomplete list) 

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#1591]
What is mentioned on the title.

At some point with the code overhaul the modules on the download section stopped loading at all or an incomplete list is loaded randomly. Pretty weird. 

I'm attaching a small screen recording (zipped, github doesn't allow mp4 uploads) and a logcat from the recent (today) debug build. 

OnePlus 6 on last Open Beta OOS 20

Hopefully it'll help. 

[19-06-15-09-39-58.mp4.zip](https://github.com/topjohnwu/Magisk/files/3292808/19-06-15-09-39-58.mp4.zip)

[logcat_06-15-2019_09-46-36.txt](https://github.com/topjohnwu/Magisk/files/3292806/logcat_06-15-2019_09-46-36.txt)

**Comment by lucenera** [comment]
![Screenshot_20190615-100655_Manager](https://user-images.githubusercontent.com/35407790/59549277-80f75700-8f5b-11e9-9bac-4ee819d4878f.jpg)
I have several installed modules. But I see an empty list or a list of few elements that change randomly by every opening.

**Comment by DenyDarko** [comment]
> ![Screenshot_20190615-100655_Manager](https://user-images.githubusercontent.com/35407790/59549277-80f75700-8f5b-11e9-9bac-4ee819d4878f.jpg)
> I have several installed modules. But I see an empty list or a list of few elements that change randomly by every opening.

Same here. When randomly some modules appear, this happens.

In case that some of my installed modules are lucky to be included to those random ones, they're shown up there.

**Comment by hemlok89** [comment]
Same thing happening to me after upgrading to Magisk Manager 7.3.0
![Screenshot_20190615-184851](https://user-images.githubusercontent.com/39864104/59551923-80cc7b00-8f9e-11e9-9425-4d99e558c78c.png)

**Comment by martyfender** [comment]
This bug has been occurring on all Magisk Manager builds since v215. Reverting to v214 solves it for me.

**Comment by lucenera** [comment]
![Screenshot_20190615-162918_Manager](https://user-images.githubusercontent.com/35407790/59552733-e44cad80-8f8a-11e9-93a1-a4e37206a234.jpg)

**Comment by hemlok89** [comment]
I have currently reverted back to 7.2.0, which solves the problem.

**Comment by diareuse** [comment]
There's an attempted fix for this here the suspicion is that the date-parsing was the culprit https://github.com/topjohnwu/Magisk/commit/3e08d0b646d579fb72bb15ea81cfe20e532af894

In case that this doesn't fix the issue please reopen this and post a logcat with your reply. Thank you!
