### ISSUE TITLE
Superuser, gone after add app to magiskhide

### ISSUE THREAD

**Issue by VerZnox** [topjohnwu/Magisk#1593]
Good Night for members or Admin
I got some problem on the superuser on the magisk manager after i add on the magiskhide 
After i try to hide it,
I try to open the app 
Accidentally superuser for the app not working
I hope this can fixed
Im useing
Oppo  A39 (CPH1605)
Android 5.1
Magisk/Magisk Manager (Latest)

**Comment by Didgeridoohan** [comment]
Are you saying that an app that's added to the Hide list no longer recognises that your device is rooted?

That's how MagiskHide works... It hides root from apps on the Hide list. Do not put an app you want to give superuser access to on the Hide list.

**Comment by VerZnox** [comment]
The app already added but the superuser not working

**Comment by Didgeridoohan** [comment]
Again: Apps on the Hide list will NOT have Superuser access. That is by design and how it should be.
