### ISSUE TITLE
App crash when using new floating button 

### ISSUE THREAD

**Issue by RaR1991** [topjohnwu/Magisk#1594]
The app is forcing closing when you touch the floating button with an empty logfile

**Comment by diareuse** [comment]
Crash was fixed https://github.com/topjohnwu/Magisk/commit/15dd2fcff9d3629e1048658d7859ec55e92fd9b5 and the button should no longer appear when the log is empty https://github.com/topjohnwu/Magisk/commit/63d21d71db484092dd5fb4af26c231e6edb4e1fa
