### ISSUE TITLE
Locating boot image for some devices has different /dev/block structure

### ISSUE THREAD

**Issue by CatMe0w** [topjohnwu/Magisk#1595]
There is a special Android (5.1 Lollipop) device, which does not have a `/dev/block/bootdevice/by-name/boot`.
It becomes `/dev/block/platform/ff0f0000.rksdmmc/by-name/boot` instead.
Detailed `mount` log: https://pastebin.com/pLZAg5iC

Current Magisk Manager cannot find boot image for this device and throws a `Unable to check signature` while trying installing Magisk via Manager.
It may requires a special mechanism for this kind of devices to locate their boot image.

**Comment by topjohnwu** [comment]
Unable to check signature has nothing to do with boot image location detection.

**Comment by CatMe0w** [comment]
Yes, it has.

Check the installer log: 
```
- Target image: /dev/block/
- Device platform:armeabi-v7a
- Downloading zip
... 100%
! Unable to check signature
! Installation failed
```

It detects a wrong image path. The image should never be a `/dev/block/`.

**Comment by CatMe0w** [comment]
I took out the boot image manually but Magisk Manager cannot patch it. 
This is a RockChip device. It is a known issue, see #755

**Comment by ghjjkbbh** [comment]
#775


 
---Original---
