### ISSUE TITLE
Oneplus 3 OxygenOS 9.0.3 with Magisk 19.3 reboots to Recovery

### ISSUE THREAD

**Issue by SubZero5** [topjohnwu/Magisk#1596]
Oneplus 3 (A3000) with OxygenOS 9.0.3 (Android 9) with Magisk 19.3 (19300) reboots to Recovery after first launch...

**Comment by topjohnwu** [comment]
I think 99% is user error

**Comment by SubZero5** [comment]
How do I fit in the 1% then @topjohnwu ? :)

I flash the Full OTA for `OOS 9.0.3` with `fastboot boot _` and then flash `Magisk 19.3 (19300)` over it.
I have been flashing like this since I first got my phone...

When I flash the Full OTA for `OOS 9.0.2` with `fastboot boot _` and then flash `Magisk 19.3 (19300)` over it, it runs great. I have been flashing like this since I first got my phone...

I think that there is something going on with `OOS 9.0.3`...
