### ISSUE TITLE
Supolicy problem in magisk or in module?

### ISSUE THREAD

**Issue by dp-alvarez** [topjohnwu/Magisk#1598]
I'm having a strange problem with EdXposed, it causes some system apps to lose their configuration on reboots.

Looking around, it seems like the problem is related to [this post-fs-data script](https://github.com/ElderDrivers/EdXposed/blob/master/edxp-core/template_override/common/post-fs-data.sh).

Some more details on [this bug report](https://github.com/ElderDrivers/EdXposed/issues/287).

Does this look like an issue on the EdXposed script or in Magisk itself?

**Comment by topjohnwu** [comment]
EdXposed

**Comment by dp-alvarez** [comment]
I see, thanks and apologies for the noise!
