### ISSUE TITLE
Magisk Manager 7.3 : Superuser app listing empty

### ISSUE THREAD

**Issue by adrenochrome25** [topjohnwu/Magisk#1599]
I received a notification to install the MagiskManager 7.3 (220) update a few minutes ago, but with this new version the Superuser app listing is totally empty (it only display the green "Superuser" banner).
No error in the logs. Reboot dont change anything. MagiskHide app listing is displaying ok.
The superuser functions are working as expected : apps that were promoted with previous versions are still getting root access

**Comment by DenyDarko** [comment]
#1592 ...

**Comment by diareuse** [comment]
I'm gonna close this one. 
@adrenochrome25 follow my instructions and post a reply to https://github.com/topjohnwu/Magisk/issues/1592
Thank you
