### ISSUE TITLE
not export PATH in V9's magic_mash.sh

### ISSUE THREAD

**Issue by twu2** [topjohnwu/Magisk#16]
This is done in V8, but is not done in V9.
so modules' script might not work like before.

**Comment by topjohnwu** [comment]
I meant to do that, as I don't want to pollute the PATH value.
Any issues have you faced so far?

**Comment by aviraxp** [comment]
@topjohnwu You can see the issue here http://forum.xda-developers.com/xposed/unofficial-systemless-xposed-framework-t3485293/post69628959#poststop

If you are not going to export PATH, then I think the post-fa-data.sh of your Systemless Xposed need to be updated.
