### ISSUE TITLE
"Live patch policy in service mode" breaks MagiskSU when encrypted

### ISSUE THREAD

**Issue by zhaofengli** [topjohnwu/Magisk#160]
Device: Nextbit Robin (ether)
ROM: LineageOS 14.1 20170328

## Investigation
1. Start with an unencrypted system
2. Download and install `Magisk-v12.0.zip` in recovery
3. :+1: **(`Magisk-v12.0.zip`, unencrypted)** Reboot, and verify that MagiskSU and Magisk Hide **both work**
4. Encrypt the system, requiring a pattern to be drawn on boot
5. In recovery, uninstall Magisk, then reinstall the same version (`Magisk-v12.0.zip`)
6. :-1: **(`Magisk-v12.0.zip`, encrypted)** Reboot, and see that MagiskSU and Magisk Hide **both fail**
    * "Rooted but no root permission, not allowed?"
    * `su` in adb shell does nothing (return value 255)
    * [Log file here](https://gist.github.com/zhaofengli/cb90983ef4f592469a4e660ea447f2b0#file-magisk-v12-0-encrypted-log)
    * It appears that Magisk Hide isn't enabled at all. But let's focus on MagiskSU for now.
7. In recovery, uninstall Magisk, then install `Magisk-v11.6.zip`
8. :+1: **(`Magisk-v11.6.zip`, encrypted)** Reboot, and see that **MagiskSU works** immediately, but Magisk Hide only works after toggling the switch
    * [Log file here](https://gist.github.com/zhaofengli/cb90983ef4f592469a4e660ea447f2b0#file-magisk-v11-6-encrypted-log) (after toggling the switch)
    * Let's not care about Magisk Hide not working immediately for now
9. `git bisect` between d53f33bed8cf0ee900803200f2422433edb91c9a and 40766b337577eca43f2c956910e41b6e0e8e8090
    * Note that I didn't care about Magisk Hide during the bisect (i.e. a commit is "good" when MagiskSU works)
10. After testing, find that the first bad commit is 67f347f88099ce1235a234aad6ee048d31b99e08
11. Revert 67f347f88099ce1235a234aad6ee048d31b99e08 (resulting in [this patch](https://gist.github.com/zhaofengli/cb90983ef4f592469a4e660ea447f2b0#file-revert-ee05476-patch)), build, uninstall Magisk in recovery and then installing this version
12. :+1: **(40766b337577eca43f2c956910e41b6e0e8e8090 with 67f347f88099ce1235a234aad6ee048d31b99e08 reverted, encrypted)** Reboot, and see that **MagiskSU works** immediately, but Magisk Hide only works after toggling the switch

Any input would be appreciated. My guess for Magisk Hide not working immediately is that `persist.magisk.hide` isn't available before userdata is decrypted.

**Comment by Didgeridoohan** [comment]
Interesting. I'll add that this isn't true for all devices. Both my Nexus 6 and OnePlus 3T are encrypted and have no issues with Magisk v12.

**Comment by TomParis01** [comment]
I can confirm that Magisk 11.6 works with my LG G6 with encrypted /data/ partition while 12.0 gives the "Rooted but no root permission, not allowed?" error

**Comment by topjohnwu** [comment]
These issues should be fixed in v13+
If any more issues, open new issue and provide logs with the new versions
