### ISSUE TITLE
Wrong busybox binary on x86

### ISSUE THREAD

**Issue by xymopen** [topjohnwu/Magisk#1600]
Hi,

I have a Xiaomi Mi Pad 2 which runs on Intel Atom X5-Z8500 and Magisk installs busybox for ARM architect.
I find out that [update_binary.sh](https://github.com/topjohnwu/Magisk/blob/defbbdfe21214fa88dc4220373469c72bee84156/scripts/update_binary.sh) uses `/dev/null` to decide architect is arbitrary, because the tablet has such device.
I also notice that during patching boot.img the console said the platform is `arm64-v8a`, although it installed the right binary. The misleading message is from [MagiskInstaller.java#L122](https://github.com/topjohnwu/Magisk/blob/7756e107799cc9a18735c0f9e98684f3d6141ffc/app/src/main/java/com/topjohnwu/magisk/tasks/MagiskInstaller.java#L122).

**Comment by osm0sis** [comment]
No, it just attempts to run busybox and if it fails to run, it then uses x86. It's likely getting confused by Intel's libhoudini arm emulation.

**Comment by xymopen** [comment]
Yes, the binary can run after system started. However it fails during boot and modules cannot be loaded. `/cache/magisk.log` says:

```
--------- beginning of main
I/Magisk  ( 2291): Magisk v19.3(19300) daemon started
I/Magisk  ( 2291): * Device API level: 22
I/Magisk  ( 2291): ** post-fs-data mode running
I/Magisk  ( 2291): * Initializing Magisk environment
I/Magisk  ( 2291): * Mounting mirrors
I/Magisk  ( 2291): mount: /sbin/.magisk/mirror/system
I/Magisk  ( 2291): mount: /sbin/.magisk/mirror/data
I/Magisk  ( 2291): link: /sbin/.magisk/mirror/vendor
I/Magisk  ( 2291): * Setting up internal busybox
E/Magisk  ( 2311): execve /sbin/.magisk/busybox/busybox failed with 8: Exec format error
I/Magisk  ( 2291): * Running post-fs-data.d scripts
I/Magisk  ( 2291): * Running module post-fs-data scripts
I/Magisk  ( 2291): * Loading modules
I/Magisk  ( 2291): * Starting MagiskHide
I/Magisk  ( 2291): hide_policy: Hiding sensitive props
I/Magisk  ( 2291): hide_list init: [com.google.android.gms/com.google.android.gms.unstable]
I/Magisk  ( 2291): hide_list init: [org.microg.gms.droidguard/com.google.android.gms.unstable]
--------- beginning of system
I/Magisk  ( 2291): ** late_start service mode running
I/Magisk  ( 2291): * Running service.d scripts
I/Magisk  ( 2291): * Running module service scripts
I/Magisk  ( 2291): ** boot_complete triggered
```

**Comment by osm0sis** [comment]
Sounds like maybe it would be better to try to run the x86 first, then do arm as the fallback, @topjohnwu.

**Comment by xymopen** [comment]
May be we can use `api_level_arch_detect` in [util_functions.sh#L325](https://github.com/topjohnwu/Magisk/blob/defbbdfe21214fa88dc4220373469c72bee84156/scripts/util_functions.sh#L325)?

**Comment by osm0sis** [comment]
The goal is to have a zip that automatically creates its own flashing environment, so no. I think my idea of reversing the order would work well though.

**Comment by xymopen** [comment]
I tried replace busybox binary at `/sbin/.magisk/busybox` but after reboot it reverted to ARM version(makes no sense to me). I don't understand how this happened. I made a flashable zip without architect detection and used fiddler to inject it.

**Comment by xymopen** [comment]
I pull the binary from `/sbin/.magisk/busybox/busybox` to PC and probe it with `file` in `wsl` .

**Comment by osm0sis** [comment]
I told you where to replace busybox and it wasn't in sbin. Please read more carefully.

**Comment by xymopen** [comment]
I just try to get the same result in a different approach. I install Magisk several times and check which binary it installed. When x86 binary get the right place the issue did resolve.

**Comment by xymopen** [comment]
Maybe I didn't express myself clearly. I made a `magisk.zip` that would always emit x86 busybox, hijack Magisk Manager with fiddler so it would always get my altered zip, follow the normal patch boot procedure, and now I have a working Magisk.

**Comment by xymopen** [comment]
The working Magisk's log is a copy of the non-working ones, just without the only error line.

**Comment by osm0sis** [comment]
Okay good, thanks, my idea should fix it then, it'll just need changes to the update-binary.sh and the build system to try x86 first as a more definitive detection, then maybe another fix to the arch detection in the installer if that doesn't fix it on its own.
