### ISSUE TITLE
magiskinit: doing load_persist_props on post-fs-data causes persist.* props to revert to default

### ISSUE THREAD

**Issue by GMMan** [topjohnwu/Magisk#1607]
I've got a phone that has a default time zone set in `build.props` (among other things, mostly for faking specs). Magisk is causing the time zone to be reset every time the phone is rebooted. This phone does not have data encryption enabled. I did some digging, and it looks like running `load_persist_props` before the system property service has started is causing issues.

A simplified init trigger flow looks like this:
```
early-init -> init -> early-fs -> fs -> post-fs -> post-fs-data -> property_service_init -> early-boot -> boot
```
Notice how `post-fs-data` precedes `property_service_init`.

Next, let's look at what gets called for `load_persist_props`:
```c
/* When booting an encrypted system, /data is not mounted when the
 * property service is started, so any properties stored there are
 * not loaded.  Vold triggers init to load these properties once it
 * has mounted /data.
 */
void load_persist_props(void)
{
    load_override_properties();
    /* Read persistent properties after all default values have been loaded. */
    load_persistent_properties();
}
```
Note the comment on that function.

Inside `load_persistent_properties`, it will `persistent_properties_loaded = 1;` on success. And searching for that, we find this:
```c
    else if (persistent_properties_loaded &&
            strncmp("persist.", name, strlen("persist.")) == 0) {
        /*
         * Don't write properties to disk until after we have read all default properties
         * to prevent them from being overwritten by default values.
         */
        write_persistent_property(name, value);
    }
```
So if you load persistent properties before default properties, and `persist.*` are present in `build.prop`, those default values will overwrite the saved values.

The easy way to fix this is to just remove `load_persist_props` from `on post-fs-data`, though I don't know how much impact this would have. For Magisk itself, it seems to only read whether user data is currently encrypted, which are not persistent properties. Only thing I think making this change would affect is modules trying to read persistent properties during init, which will not be available (but probably wouldn't be available anyway if the storage was encrypted).

**Comment by topjohnwu** [comment]
`property_service_init` shouldn't be later than `post-fs-data`, you can already call `getprop` in post-fs-data

**Comment by GMMan** [comment]
Sure, properties may be available, but that doesn't mean the property service has been initted, and hence `build.prop` has not been read at that point. See order in [init code](https://android.googlesource.com/platform/system/core/+/refs/heads/kitkat-release/init/init.c#962). (I'm currently dealing with a KitKat device, in case you're wondering.)

**Comment by the-brad** [comment]
Not as technically helpful as OP, but I have the same issue on my Razer Phone 2 running 9.0 stock. I set some props via system.prop inside of a module bute the props don't get changes when I check with getprop in terminal.

**Comment by alexa-v2** [comment]
I have issues with time being known on boot (bootscript output), I'm wondering if magisk is the cause now

**Comment by GMMan** [comment]
Currently debugging a problem with entering MediaTek factory mode on a Marshmallow device, and looking at init, initting the properties service is before `init.rc` is parsed, but it doesn't include loading properties. That has been split out to a keyword `load_all_props_action`, which still runs after `post-fs-data`. `load_persist_props` is triggered when data partition is decrypted, as before.
