### ISSUE TITLE
Blank MagiskSU list

### ISSUE THREAD

**Issue by penuser** [topjohnwu/Magisk#1608]
Device: Redmi4, MIUI10 Stable, Android 6
Magisk: Magisk 19.3 Manager 7.30

Problem: Magisk can SU apps correctly and function well. However, the SuperUser page is a white screen without anything showing up, which means I cannot see and edit the SUapp list.

Tried a core-only mode and this won't fix it.

Thanks.

**Comment by DenyDarko** [comment]
#1592

It's fixed for the next release. 

You can close this one
