### ISSUE TITLE
Feature request: Don't check for Updates when there is no internet connection

### ISSUE THREAD

**Issue by CreepyCrafter24** [topjohnwu/Magisk#1609]
Checking for Updates when there is no internet connection seems pointless to me.

**Comment by topjohnwu** [comment]
It won't

**Comment by CreepyCrafter24** [comment]
![Screenshot_20190617-083356_Manager](https://user-images.githubusercontent.com/33260128/59583219-ed4c9480-90da-11e9-821c-0897fd9a3672.jpg)
It appears to try to check for updates. Sorry if I am overlooking something
