### ISSUE TITLE
Are we sure clear repo cache still works?

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#1611]
Hey @diareuse 

In the today's build, the missing download modules seems to be fixed.

I've noticed something else though. 

By going into magisk settings, clearing repo cache won't result in an empty download section as usual. 

So, I'm wondering if something is broken with that or it's just how it works now. 

Small video and logcat attached. 

[19-06-18-09-29-24.mp4.zip](https://github.com/topjohnwu/Magisk/files/3300053/19-06-18-09-29-24.mp4.zip)

[logcat_06-18-2019_09-30-07.txt](https://github.com/topjohnwu/Magisk/files/3300056/logcat_06-18-2019_09-30-07.txt)

**Comment by diareuse** [comment]
Hey,

this is correct behavior. The fragments are no longer reloaded every time they're opened. Long story short, its state is _completely_ detached from the activity/fragment and so it is capable of keeping everything loaded when the view goes away.

The backing data (database) is cleared so next time you're gonna swipe to refresh or start the app again, everything is forcefully downloaded from github's servers.

**Comment by DenyDarko** [comment]
Thank you for the awesomely detailed answer.

Case closed xD

**Comment by bmazak** [comment]
Just started to see a message with the Magisk Icon at bottom of screen that says Re-pro Cache cleared. It's transparent so it does not interfere with Icons under it.  Can not clear this message.
