### ISSUE TITLE
Reboot to Recovery gives loading dialog Factory data reset

### ISSUE THREAD

**Issue by cmstew** [topjohnwu/Magisk#1614]
Magisk Manager: 7.3.1

In Magisk Manager if you go to Modules, click the boot menu options in the top right, and click "Reboot to Recovery" it pops up with a loading dialog that says "Factory data reset...". It still ends up taking you to the recovery, but it's a pretty misleading dialog. lol

**Comment by DenyDarko** [comment]
This has nothing to do with Magisk.

Magisk just calls the reboot to recovery command, how the reboot is handled has to do with your recovery. 

Check the behavior with another app:

https://play.google.com/store/apps/details?id=com.awiserk.kundalias.rootboot

**Comment by DenyDarko** [comment]
@cmstew

https://github.com/topjohnwu/Magisk/commit/b1e63f0f140e9ef88e7bf19bfb266c95e4ae335d
