### ISSUE TITLE
LOCK SCREEN ISSUE WITH SAMSUNG PIE (J4 - J6 - J4 + - J6 + - A6 - A6 + - A7 2018 -AND MAYBE MORE  ) AFTER FLASH MAGISK 

### ISSUE THREAD

**Issue by Kopra159** [topjohnwu/Magisk#1617]
**ALL AT XDA THREAD :** 
https://forum.xda-developers.com/showpost.php?p=79747083&postcount=628

AND THE CAUSE AND PICTURE ARE THERE  .

BESIDE THAT THEIR IS FIX BY  PRO  ananjaser1211 : 

https://forum.xda-developers.com/showpost.php?p=79749109&postcount=635

BUT WE NEED SOLUTION FOR ALL DEVICES  .

WE ALL WAIT THE BEST SOLUTION BY U . 

AND VERY THANKS .

**Comment by Didgeridoohan** [comment]
Do you have to shout?

**Comment by topjohnwu** [comment]
#1409

**Comment by Kopra159** [comment]
> Do you have to shout?

???
behave rude .

**Comment by Kopra159** [comment]
> #1409

mr @topjohnwu  , No u understand the matter wrong  all magisk version make lockscreen issue with pie .

but with oreo 19.3 works with lockscreen well .

**Comment by Kopra159** [comment]
@topjohnwu    THE same with canary

**Comment by Kopra159** [comment]
@topjohnwu 
Excuse me , try to take look in logs and tell me where is the problem or  what should I do .
I run commands to grep logs then set lockscreen then lockscreen then reboot  , this in 3 minutes .
Here u are
-  logcat : 
[logcat.txt](https://github.com/topjohnwu/Magisk/files/3747652/logcat.txt)
- dmesg :
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/3747653/dmesg.txt)
- dumpsys :
[dumpsys.txt](https://github.com/topjohnwu/Magisk/files/3747654/dumpsys.txt)
