### ISSUE TITLE
Search Is Broken

### ISSUE THREAD

**Issue by maruashok** [topjohnwu/Magisk#1618]
Device : Redmi Notre 4(Mido)
Os : AEX 5.8 Oreo (Latest)
Magisk Manager V 7.3.1
Magisk Search Is Brokern Please Check,

Regenerate (Manager 7.3.1)
1 - Search anything in Magisk Manager Downloads or Hide,
2 - Go Back
3 - Come back to downloads,
4 - It will display previously searched result and you can't clear search list(Search Textbox is already empty)

Tried Pull down to refresh list on magisk hide/downlods but failed,it will only display previously searched result.

**Comment by DenyDarko** [comment]
You're right.

A temporary solution when you return to the Download section is to write something else (anything) on the search bar and delete it.

**Comment by diareuse** [comment]
This commit fixes that issue.
https://github.com/topjohnwu/Magisk/commit/ab57415f97c9f9e6af9e0dde5976ac109b748eee

Problem was that viewModel was _correctly_ retaining its state however the state of widget (searchView) was not linked with the viewModel resulting in data being seemingly corrupted and the screen "broken".

The same this appears to (not) work on the Magisk Hide screen, which has been fixed as well.

Thank you for reporting this inconsistence.
