### ISSUE TITLE
Magisk (any version) flash zip crashes Honor 8 Nougat

### ISSUE THREAD

**Issue by Gondost** [topjohnwu/Magisk#162]
[dmesg-ramoops-0.txt](https://github.com/topjohnwu/Magisk/files/896065/dmesg-ramoops-0.txt)
The device crashes and instantly reboots itself, whether installing from recovery or booted system. Log attached.

[last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/894287/last_kmsg.txt)

**Comment by fredfred41** [comment]
same, here. do you have adopted storage sd?

**Comment by OldDroid** [comment]
@topjohnwu the issue can be closed as its related to twrp itself due to an old recovery kernel version (with broken loop support)

**Comment by fredfred41** [comment]
I have the latest twrp 3.1.0-0, and I still have this crash and reboot to system when triying to install magisk v12 on my honor8 FRD-L09 android v7.0

**Comment by OldDroid** [comment]
you should check over at xda for my last twrp update on honor 8 @fredfred41

**Comment by fredfred41** [comment]
Here? :
https://forum.xda-developers.com/honor-8/how-to/twrp-nougat-edition-t3504140

I will try it, thanks

**Comment by fredfred41** [comment]
I managed to update to 3.1.0-3, and now I can complete magisk v12  installation thanks OldDroid. but now I have bootloop an e-recovery screen. I tried magisk uninstaller, and can have my phone to boot. But I lost root, and cant install magisk with twrp, without having the same bootloop.

**Comment by Gondost** [comment]
Kernel issue, not Magisk issue -- Huawei is finally getting around to fixing their kernel in the B38* updates.
