### ISSUE TITLE
Phone Power off/Reboot - Magisk on Hong Kong Snapdragon S10e G9700

### ISSUE THREAD

**Issue by znbaboy** [topjohnwu/Magisk#1620]
When magisk is installed and enabled on snapdragon s10s with unlockable bootloaders (aka hong kong models) the phone frequently powers off during use.

Mainly happens when locking/waking device, but also occurs during random phone use.

I cannot find any fixes anywhere and have had other users report this same issue. 

A thread created on XDA regarding this issue:
https://forum.xda-developers.com/galaxy-s10e/help/g9700-occasional-crash-log-included-t3932845

Ive tried multiple builds of magisk including: Stable, Canary, Ianmacd's

**Comment by topjohnwu** [comment]
#1450
