### ISSUE TITLE
Magisk Doesn't Properly Patch AP File for Latest S10e Update

### ISSUE THREAD

**Issue by znbaboy** [topjohnwu/Magisk#1623]
The G9700 ASF1 AP file doesn't get patched correctly with the Magisk Manager app. Odin fails to flash at Recovery.img and WinRAR has an error when viewing the magisk_patched.tar file

![magisk error](https://user-images.githubusercontent.com/52028136/59961055-b7732b80-949f-11e9-84c5-0aacbff17787.png)

**Comment by DrRambone** [comment]
Confirmed, no boot on 9700 on ASF1

**Comment by topjohnwu** [comment]
@znbaboy copy the AP tar file with ADB as mentioned in the instructions. MTP tends to corrupt data in large files

**Comment by znbaboy** [comment]
@topjohnwu that was never an issue for previous versions. Just copying and AP file to phone, patching with Magisk, & putting it back on my computer worked fine for the last update. Although I'll try it. What instructions are you referring to? The Exynos guide seems to be deleted

**Comment by znbaboy** [comment]
@topjohnwu ADB pull seems to have resolved the issue. Thanks! I hope you can fix the kernel bug on the snapdragon models of s10s one day.

**Comment by wonderlandpoet1** [comment]
My issue is there is absolutely no file with that file code name
