### ISSUE TITLE
PS Vue Still Detects Root Using Hide on Canary 

### ISSUE THREAD

**Issue by moore-bryan** [topjohnwu/Magisk#1625]
Completely fresh install of Lineage 15.1 Unofficial and Magisk Canary on Nexus 10.

PS Vue still detects root despite using Magisk Hide.

**Comment by topjohnwu** [comment]
#1152

**Comment by moore-bryan** [comment]
No offense, but this is a lazy response. I'm not suggesting Magisk has never worked; rather, just the LATEST version no longer works.
