### ISSUE TITLE
Canary 1058aeb0 bootloops Q Beta 4 .019 Pixel 2 XL 128 GB

### ISSUE THREAD

**Issue by JohnLGalt** [topjohnwu/Magisk#1626]
Hi,

I have a Taimen that keeps bootlooping upon install of Canary (debug) build 7.3.1-1058aeb0.  
It's reproducible 100% of the time, and at least one other user over at XDA has confirmed it as well:  https://forum.xda-developers.com/apps/magisk/dev-magisk-canary-channel-bleeding-edge-t3839337/post79774538#post79774538

I'm attaching both the kernel and recovery logs.

Also, FWIW, I clean installed Android Q Beta 4 build .019 just after it was released to test Magisk canary build that is causing an inordinate amount of lagginess throughout the system, in a wide variety of issues.  I've detailed the experiences in this post at XDA as well:

https://forum.xda-developers.com/showpost.php?p=79767555&postcount=581

(Sorry about it not being in the Magisk Canary thread, but it was in reply to a post from Unholy in the Q discussion thread).

Device:  **Google Pixel 2 XL 128 GB** (aka _Taimen_)
OS:  **Android Q Beta 4 build .019** (clean installed earlier this week, restored through Google account except for 1 app, Blokada, restored via TiBu)
Reproducibility:  **100%**
Steps:

1)  Install through Magisk Mgr, reboot, **phone goes directly to bootloader on reboot**.
2)  Boot TWRP, Flash uninstaller, reboot to system, verify Magisk is uninstalled (I have logs for this step as well if needed)
3)  Reboot to bootloader, boot TWRP, flash latest Magisk Canary (debug), wipe Dalvik, reboot - **phone goes directly to bootloader** 

Please let me know if anything else is needed.

[magisk_canary_install_dmesg.log](https://github.com/topjohnwu/Magisk/files/3317170/magisk_canary_install_dmesg.log)
[magisk_canary_install_recovery.log](https://github.com/topjohnwu/Magisk/files/3317171/magisk_canary_install_recovery.log)

**Comment by Darian71** [comment]
Exactly the same issue and fix with my Pixel XL (Marlin) on 019 Q beta release.

**Comment by JohnLGalt** [comment]
Magisk Stable does not cause this bootloop, FWIW.

**Comment by JohnLGalt** [comment]
Welp - TopJohnWu already had a reply ready.  

https://twitter.com/topjohnwu/status/1142503019822510080

Based upon that, I'm closing this report.
