### ISSUE TITLE
Bootloop Xiaomi Mi 9

### ISSUE THREAD

**Issue by ivdeveloper86** [topjohnwu/Magisk#1627]
Good afternoon friends

I want to ask for help to understand the problem, I can not install Magisk on my Xiaomi Mi 9 phone
After flashing from TWRP, the phone does not boot (it starts TWRP back), tried the same way through MagiskManager-v7.3.2 to flash the boot boot.img and was already flashing through TWRP, the result is the same, the phone is not loaded. I will not format the data, because I will lose a lot of information.
Installed official firmware 10.2.26.0.PFAEUXM (https://en.miui.com/download-361.html#588)

[magisk_patched.zip](https://github.com/topjohnwu/Magisk/files/3317667/magisk_patched.zip)
[magisk_install_log_2019-06-23T11_48_48Z.log](https://github.com/topjohnwu/Magisk/files/3317668/magisk_install_log_2019-06-23T11_48_48Z.log)
![Screenshot_2019-06-23-12-02-42-163_com android settings](https://user-images.githubusercontent.com/26603326/59974018-add8e900-95af-11e9-88b0-a385eecd4d4e.png)

**Comment by topjohnwu** [comment]
Try the latest canary build

**Comment by ivdeveloper86** [comment]
I checked on the last canary build 19.4 (19302), still Bootloop :(

**Comment by ivdeveloper86** [comment]
> Try the latest canary build

I checked on the last canary build 19.4 (19302), still Bootloop :(

**Comment by ganeshkrishnan1** [comment]
same problem with my mi 9. Flashed magisk and now its stuck in bootloop.

**Comment by Vanman989** [comment]
same with MI9T MIUI 11.0.1.0

**Comment by ganeshkrishnan1** [comment]
I could solve this by flashing dmverity before flashing magisk. The issue is for encrypted partitions and magisk is unable to flash to correct partition when the table is encrypted.

make sure to flash dmverity then magisk. order matters
