### ISSUE TITLE
Device Support: Samsung Galaxy S7 Edge (Sprint)

### ISSUE THREAD

**Issue by d0ggo** [topjohnwu/Magisk#163]
This might be somewhat difficult since Qualcomm has Secure Boot enabled (which is what got me) but I'm able to help somewhat.

I've tried installing the Magisk Manager, and it was granted root permissions alright with my systemless(?) root from the guide seen [here](https://forum.xda-developers.com/sprint-s7-edge/how-to/sm-g935p-spr-root-nougat-7-0-data-t3568780) on XDA. After downloading and installing Magisk, the Manager gives me a popup that asks me if I want to reboot. I click yes, it reboots, then gives me a blue screen saying something along the lines of secure boot failing to start up (boot.img) in small red text at the top right and in the center saying that my software has been basically demolished and I may incur charges having to send my phone into my carrier. Sorry I don't know the exact text. A flash to stock in Odin works fine, thank god.

I don't know where I can get ahold of a boot image for this device unless you'd want a bootloader .tar.md5. Thank you so much for Magisk, and feel free to contact me further about this!

Edit: Forgot to say Magisk Manager, after testing SafetyNet, throws me an error about CTS profile mismatch, if I remember right

Edit 2: Error code fixed in first edit

Edit 3: Oh my gosh I'm forgetting everything today. Android version 7.0, Sprint S7 Edge, latest Magisk and Magisk Manager.

**Comment by LoungeKatt** [comment]
You can't modify the boot image with a locked bootloader. The reason the phone can be rooted is that someone obtained an engineering boot image, which has accepted keys. Samsung uses a special signing hash (or at least they did before they began actually enforcing it) to verify the integrity of an image. This means installing an unofficial image will always cause an error.
