### ISSUE TITLE
Doesn't install on roms that are prepatched

### ISSUE THREAD

**Issue by Cyberavater** [topjohnwu/Magisk#1633]
I know it doesn't install on already rooted/supersu rom but my rom is patched for other reasons (i.e Debloated, Deodexed, tweaked, etc) so can there be any way to install it on such roms?

**Comment by Cyberavater** [comment]
I'd really appreciate if you could help on this matter.

**Comment by Didgeridoohan** [comment]
This is not a support forum. Best place to ask for assistance is in your ROM forum/thread.
