### ISSUE TITLE
Unsupported/Unknown image format

### ISSUE THREAD

**Issue by elig0n** [topjohnwu/Magisk#1634]
- Device platform: arm64-v8a
    - Existing zip found
    - Copying image to cache
    1022+1 records in
    1022+1 records out
    1047368 bytes transferred in 0.013 secs (80566769 bytes/sec)
    - Unpacking boot image
    Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
    ! Unsupported/Unknown image format
    ! Installation failed

App Info shows it's Magisk Manager 7.3.2
The program itself shows Magisk Manager 7.3.3 (224)
Zip name: Magisk-v19.3(19300).zip

**Comment by melblanc** [comment]
On S10 here it is showing: Installed 7.3.2(224)
                                           Latest    7.3.2(224) 

Another S10 on which Magisk is working displays:
                                          Installed 7.3.1-1058aeb0 (225)
                                          Latest     7.3.1-1058aeb0 (225) 

Usually have option of 'Direct install of Magisk with Magisk Manager but 
with this version have to download ZIP file and then select it for installation.
Displays the following when attempting to install via Manager:

Failed
Device platform:arm64-v8a
Existing zip found
Copying image to cache
Unpacking boot image
Unsupported/Unkown image format
Installation Failed

**Comment by JoanVC100** [comment]
a

**Comment by topjohnwu** [comment]
Not enough info

**Comment by elig0n** [comment]
Please explain what info you need ? 
This is not a good reason to close an issue and no way of handling an issue.

**Comment by robocoder** [comment]
I got the same error but managed to install the zip via TWRP.

You might try installing the canary builds with debug.

https://github.com/topjohnwu/magisk_files/tree/master/canary_builds

**Comment by Canhobix** [comment]
Does anyone got any updates on this ? I also used this release and got the same error.
https://github.com/topjohnwu/magisk_files/blob/master/canary_builds/release.json

Thank you

**Comment by DarrenMack-OD** [comment]
I am having the same issue, I thought it was me, but not matter how I download and install Magisk, it gives me this error

**Comment by satisfy123** [comment]
Having the same issue!

**Comment by NathanielRMoss** [comment]
same issue on 4 S4galaxy phones. Continually asks me to update Magisk Manager, even though the manager is up to date. Then No Direct install option anymore.

**Comment by h6w** [comment]
Same on OnePlus 6 without TWRP.

**Comment by takuhii** [comment]
I manually installed Magisk 19.4, and it now tells me the latest version is Magisk 19.3 :/

**Comment by yusea431** [comment]
Got the same issue to elig0n, and my device platform is armeabi v7a . Many times i installed/reinstalled but still...

**Comment by Eisenherz254** [comment]
I am also getting the same error on Magisk v7.3.5(243). My device is Ulefone Note 7 running on Android 8.1 Go Edition. Any advise please?

**Comment by h6w** [comment]
Ok, I think there's a misunderstanding of the process here.  For my reference, and others, the "Download Patch File" is NOT the file you then "Install".  You must:
1) Download the patch file
2) Patch your boot.img with the patch file on another machine
3) Patch the boot with `fastboot boot patch_boot.img`
4) Without rebooting, run Magisk Manager and select "install into slot".
The, and only then, will the system be patched and stay patched!

You only get into this problem situation if you do an OTA update and then reboot.  If you do an OTA update in future, go to Magisk Manager **before rebooting**!

**Comment by Marco-Sulla** [comment]
@h6w 
> Patch your boot.img with the patch file on another machine

How?

**Comment by Canhobix** [comment]
Enter on fastboot mode

# fastboot flash boot.img

Please note that you should flash the boot.img of your phone model and baseband switch.


> @h6w
> 
> > Patch your boot.img with the patch file on another machine
> 
> How?

**Comment by KestrelSoftworks** [comment]
@h6w Just tried patching a LineageOS boot.img the way you say since I'm facing the same issue. It keeps saying "Unsupported/Unknown image format"
The img file is attached.
[boot_img.zip](https://github.com/topjohnwu/Magisk/files/3854169/boot_img.zip)
Is there anything I can try to make this work? Or any pipeline you can suggest me to tweak the img file or needed thing? 
Thank you in advance.

**Comment by h6w** [comment]
@Marco-Sulla @KestrelSoftworks That depends on your phone.

e.g. For OnePlus6,

> **How to extract from OTA and manually patch stock OOS boot.img using Magisk Manager:**
>
> 1. Install python3 and PIP manager on your system .
> 2. Use pip to install "protobuf" module:
>
>    `pip3 install protobuf`
>
> 3. Download payload_dumper.py and update_metadata_pb2.py from this gist https://gist.github.com/ius/42bd02a5...342ab7a9c60f15 and save them in one directory.
> 4. Download full update zip with OOS (containing payload.bin). It can be downloaded from [this great thread](https://forum.xda-developers.com/oneplus-6/how-to/oneplus-6-mirrors-official-oxygen-os-t3792244) by @[Titokhan](https://forum.xda-developers.com/member.php?u=5301049)
> 5. Extract payload.bin from update zip to same directory where payload_dumper.py is located.
> 6. Use payload_dumper.py to extract original boot.img
>
>    `python payload_dumper.py payload.bin`
>
> After a while you should have all img's included in payload.bin dumped in your working directory.
> 7. Install Magisk Manager app on your OP6.
> 8. Place that dumped boot.img on your phone storage.
> 9. In Magisk Manager app tap install, and select "Patching boot image file". Select boot.img that you've just uploaded to your phone.
> 10. Magisk Manager will patch boot.img and save it on Phone's internal storage in "MagiskManager" directory (file called "patched_boot.img").
> 11. Download this patched file to your computer and just use it to boot using fastboot

--- copied from a post on [xda-developers](https://forum.xda-developers.com/oneplus-6/how-to/oneplus-6-magisk-root-oos-5-1-5-t3794440)

Downloading the gists was a bit tricky, but this process worked for me. :-)

You can also download pre-patched boot images [from here](https://forum.xda-developers.com/oneplus-6/how-to/patched-boot-image-magisk-16-7-beta-t3818853).

**Comment by Marco-Sulla** [comment]
Well, I'll find a way for my phone, a Xiaomi Redmi Note 6 pro with Andorid 9 and MIUI 10.3.6.

PS: a question: flashing the boot image via Magisk, not via fastboot, requires an unlocked phone?

**Comment by h6w** [comment]
Unlocked, yes.  And the caveat is that some brands (e.g. Samsung) now have eFuses, which means once you unlock them, it voids your warranty. OnePlus is one of the few brands that encourage people to use alternative ROMs so they don't have an eFuse. :-)On 19 Nov. 2019 00:51, Marco Sulla <notifications@github.com> wrote:Well, I'll find a way for my phone, a Xiaomi Redmi Note 6 pro with Andorid 9 and MIUI 10.3.6.
PS: a question: flashing the boot image via Magisk, not via fastboot, requires an unlocked phone?

**Comment by miigotu** [comment]
If this helps anyone, my factory image had a bootloader image in the zip, and another zip. Inside the second zip is a boot.img. The boot.img works.

```
dusted@ROG:~/Downloads/coral: ls coral-qq2a.200305.004.a1/
bootloader-coral-c2f2-0.2-6118748.img
flash-all.bat
flash-all.sh
flash-base.sh
image-coral-qq2a.200305.004.a1.zip
radio-coral-g8150-00055-200110-b-6126839.img
dusted@ROG:~/Downloads/coral: unzip coral-qq2a.200305.004.a1/image-coral-qq2a.200305.004.a1.zip
Archive:  coral-qq2a.200305.004.a1/image-coral-qq2a.200305.004.a1.zip
  inflating: android-info.txt        
  inflating: boot.img                
  inflating: dtbo.img                
  inflating: product.img             
  inflating: super_empty.img         
  inflating: system.img              
  inflating: system_other.img        
  inflating: vbmeta.img              
  inflating: vbmeta_system.img       
  inflating: vendor.img              
dusted@ROG:~/Downloads/coral: adb push boot.img /sdcard/Download
```

**Comment by gnorbsl** [comment]
If anyone stumbles over this issue like me:

The issue was that magisk is not recognizing the firmware archive that is loaded from sammobile etc. You have to unpack the firmware and you will see 5 files, one of them is AP_ something tar.md5

Upload the file to your phone, patch it with magisk, download to PC and flash it with odin, but also flash all the other files in the archive.

Read and follow this guide:

https://topjohnwu.github.io/Magisk/install.html#samsung-system-as-root

**Comment by ric-hard-dick** [comment]
When i patch the boot.img via magisk on phone (sgs5spr stock marshmallow w/twrp) im not seeing this this new patched boot img in the cache (where magisk says its at) or the /storage/download area.

**Comment by CrayzyOne** [comment]
Just got the same problem. I solved it by patching the img file on a different device.
I don't know why this is not working on the same device.

**Comment by miigotu** [comment]
> Just got the same problem. I solved it by patching the img file on a different device.
> I don't know why this is not working on the same device.

I believe it happens on a device with slot_a and slot_b bootloader, so a different device with a single slot might make it work.

**Comment by iamDaretech** [comment]
> On S10 here it is showing: Installed 7.3.2(224)
> Latest 7.3.2(224)
> 
> Another S10 on which Magisk is working displays:
> Installed 7.3.1-1058aeb0 (225)
> Latest 7.3.1-1058aeb0 (225)
> 
> Usually have option of 'Direct install of Magisk with Magisk Manager but
> with this version have to download ZIP file and then select it for installation.
> Displays the following when attempting to install via Manager:
> 
> Failed
> Device platform:arm64-v8a
> Existing zip found
> Copying image to cache
> Unpacking boot image
> Unsupported/Unkown image format
> Installation Failed

yes same problem with me any solutions i use oppo a7

**Comment by ric-hard-dick** [comment]
I believe you may have contacted the wrong individual. But what file format is the boot.img your trying to use? 

It needs to bee the one that comes with the files that come with whatever device you haves stock image zip download. Find your devices stock image flashable, open it up and copy just the boot.img file to your mobile and when magisk prompts you to select a file to patch you select that one. It will then patch it and tell you where it saved the patched .img too. Then I believe the magisk installer won't give you anymore issues when updating/installing. My memory is rusty and my phone is different so I could be missing a step or two. You might need to flash or install that patched img via twrp or fastboot and then the msgisk installer should work. For my moto x pure I had to use a PC to fastboot install my patched .img.. Anyways good luck.
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


Jul 4, 2021, 03:12 by ***@***.***:

**Comment by tonmoy998** [comment]
I have the same issue.Ramdisk :yes 
unknown or unformated image file
