### ISSUE TITLE
No modules visibles

### ISSUE THREAD

**Issue by N1coc4colA** [topjohnwu/Magisk#1640]
Hello, I'm on... Phoenix OS based on Android-x86 Project which is based on AOSP 7.1.1. I want test to run Fortnite (works right but not the right sys. ver. and not recognized by the Installer). I installed Magisk cause it's more fast and Fortnite look for root files and there is a hide mode. So, I wanted to use GLTools 4.0.1, in it, there is the option Install using magisk and you get a .Zip file to install GLTools. I tryed a lot, cause nothing is show in the module page. At a moment, I saw the module and there was write "It will be updated after reboot" (some thing like that). After rebooting, there was nothing, so, i went to the downloads page (was nothing but now fix by using clear cache) and I installed some modules. After the reboot, there is nothing. But now... I have... 2 "Magisk Manager" it's WTF!!! But in the two, there is nothing. Can someone help me?

**Comment by Didgeridoohan** [comment]
This is not a support forum. Close this issue and move over to xda instead.
