### ISSUE TITLE
Idea about fixing the .magisk_unblock staying after boot 

### ISSUE THREAD

**Issue by Fox2Code** [topjohnwu/Magisk#1641]
References #1149 / #1154 
I make this post to show and discuss ideas to fix this bug
In the first part, I will show how to reproduce the bugs and how it can happen and in a second part I will explain my possibles idea to fix the bug

## 1. How to reproduce the bug
To reproduce the bug the magisk post-fs-data ne too be longer than 10 second it can be achieve by installing too many module or by installing this test module that just wait 11 second on boot 
[Sleep11sec.zip](https://github.com/topjohnwu/Magisk/files/3333783/Sleep11sec.zip)
This bug happen because magisk-deamon create the file .magisk_unblock after it was "deleted"
Normal Magisk boot (post-fs-data only)
* init.rc => start magisk-deamon 
* init.rc => **wait 10 .magisk_unblock**
* magisk-deamon => Init modules / other stuff
* magisk-deamon => **create .magisk_unblock**
* (init.rc continue because .magisk_unblock created)
* init.rc => **rm .magisk_unblock**
* init.rc => normal booting

Slow Magisk boot (post-fs-data only)
* init.rc => start magisk-deamon 
* init.rc => **wait 10 .magisk_unblock**
* magisk-deamon => Init modules / other stuff
* (init.rc continue because he has waited too long)
* init.rc => **rm .magisk_unblock**
* init.rc => normal booting
* (magisk-deamon just finished initialization)
* magisk-deamon => **create .magisk_unblock**

## 2. My idea to fix the bug

My first idea was to create a temporary file that exists only before `rm .magisk_unblock` was executed but in fact, it was not fully resolving the full problem of magisk booting because it does not resolve the problem if something needs to be done on post-fs-data before the system server start

My new idea has potentially a good idea to not only resolve this issue but can also improve Magisk hiding
Magisk patch the init.rc file on boot and add services that allow running the magisk-daemon without blocking the process.
but the problems with these services is that it creates a prop every time a new service is created.
my idea is instead to use a service to launch magisk-daemon from a service is to use an intermediate script that launch magisk daemon and kill itself to unblock the boot process when a problem is detected or the boot is finished to unblock the boot process and since the magisk-daemon is a direct child of the intermediate the process can communicate without requiring creating file and it will also make magisk much difficult to detect

I want advice from the magisk community to know if it's a good idea or not.
And I know topjohnwu is actually doing many changes to magisk but I just wanted to share my idea to see if it is good or not 

Bug tested a present on latest magisk canary build at the time of the post 
(19.4-dd6e55ac)

**Comment by topjohnwu** [comment]
I understand the issue, that is why I didn't closed your original PR (for my own reminder). This is not on my priority list to fix. The solution I might do eventually is simply kill executing scripts after a certain amount of time so no malicious modules can break magic mount.

**Comment by Fox2Code** [comment]
Ok Thanks for the response

**Comment by osm0sis** [comment]
Chainfire went with 60s for su.d: https://su.chainfire.eu/#updates-sud
