### ISSUE TITLE
Latest Canary causing boot issues

### ISSUE THREAD

**Issue by alexa-v2** [topjohnwu/Magisk#1643]
After updating to the latest 19.4 Canary, I have to reboot three times each boot to get a successful boot

Device: Moto Z3 play

ROM: Resurrection Remix 7.0.2 

Misc: Selinux permissive by ROM maintainer, unencrypted storage

Logs:  https://drive.google.com/file/d/1--V0qGROfvM_AAC-LLJtfch0fn1qv2_t/view?usp=drivesdk

Magisk: version code 19303

_Sent from my moto z3 play using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alexa-v2** [comment]
Ok

After a bit of troubleshooting here's what I've gotten:

1) It only happens on _reboot_. If I shut down and then cold boot, it works fine

2) The magic number seems to be 3. First two boots hang on the boot animation, third boots fine

3) I've tried core only mode to no avail so it's not a module doing it 

_Sent from my moto z3 play using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alexa-v2** [comment]
Well if I cold boot it doesn't always require 3 reboots but still require 1 or 2 sometimes

_Sent from my moto z3 play using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by topjohnwu** [comment]
Are you using any modules? Remove all modules before reporting issues

**Comment by alexa-v2** [comment]
@topjohnwu I believe core only mode will achieve what you requested, and I already said I tried that

**Comment by topjohnwu** [comment]
This can potentially fix your issue: 05658cafc740fbb5a121aaed3546c23634767717

**Comment by alexa-v2** [comment]
@topjohnwu the issue seems resolved
