### ISSUE TITLE
Stuck in Core Only Mode

### ISSUE THREAD

**Issue by farukr1** [topjohnwu/Magisk#1645]
Device: H8266 Xperia XZ2, Android 9, stock firmware

Latest canary build which is 19.4-dd6e55ac, magisk manager version is 7.7.3-dd6e55ac, thankfully the device boots however it's stuck in core only mode forever, behavior doesn't change with a restart or with the other installation methods.
[magisk.log](https://github.com/topjohnwu/Magisk/files/3337640/magisk.log)
[magiskcatlog.txt](https://github.com/topjohnwu/Magisk/files/3337643/magiskcatlog.txt)

(logcat recorded while turning the switch for Core Only Mode on and off, after a restart switch turns back to on again)

**Comment by topjohnwu** [comment]
#1537

**Comment by mirfatif** [comment]
Same with me on v19.3 stable. Previously on v19.2 I had to enable Core only mode because of [this issue](https://github.com/RikkaApps/Riru/issues/46#issue-455448192) (@topjohnwu please look into this too if it needs to be addressed at your end). Now I can't disable core-only mode whatever I do. I also tried manually deleting `/cache/.disable_magisk` and `/data/adb/modules` and then reinstalling modules. In app it looks disabled (in settings and on main activity) but modules aren't loaded, neither appear under Modules menu.
```
06-29 16:33:22.710   752  2072 I Magisk  : ** boot_complete triggered
06-29 16:33:22.715   752  2072 E Magisk  : su: cannot find manager
06-29 16:33:22.743  2075  2075 I Magisk  : apk_install: /data/magisk.apk
06-29 16:33:23.796  2219  2219 I Magisk  : apk_install: Success
06-29 16:33:50.445  2453  2453 I Magisk  : Magisk v19.3(19300) daemon started
06-29 16:33:50.445  2453  2453 I Magisk  : * Device API level: 28
06-29 16:33:50.549  2453  2454 I Magisk  : ** post-fs-data mode running
06-29 16:33:50.551  2453  2454 I Magisk  : * Initializing Magisk environment
06-29 16:33:50.555  2453  2454 I Magisk  : * Mounting mirrors
06-29 16:33:50.555  2453  2454 I Magisk  : mount: /sbin/.magisk/mirror/system
06-29 16:33:50.555  2453  2454 I Magisk  : mount: /sbin/.magisk/mirror/vendor
06-29 16:33:50.556  2453  2454 I Magisk  : mount: /sbin/.magisk/mirror/data
06-29 16:33:50.557  2453  2454 I Magisk  : * Setting up internal busybox
06-29 16:33:50.573  2453  2454 I Magisk  : * Running post-fs-data.d scripts
06-29 16:33:50.574  2453  2454 I Magisk  : post-fs-data.d: exec [start_linux]
06-29 16:34:01.286  2453  9150 I Magisk  : ** late_start service mode running
06-29 16:34:01.294  2453  9150 I Magisk  : * Running service.d scripts
06-29 16:34:01.297  2453  9150 I Magisk  : service.d: exec [test]
06-29 16:34:01.311  2453  9150 I Magisk  : * Running module service scripts
06-29 16:34:37.137  2453 13047 I Magisk  : ** boot_complete triggered
```

**Comment by RDRXS** [comment]
Same issue, Sir

(ResurrectionRemix-Oreo)
