### ISSUE TITLE
Feature Request: Add "Select/Deselect all" modules toggle feature in Magisk Manager

### ISSUE THREAD

**Issue by Y-T-G** [topjohnwu/Magisk#1648]
Sometimes the modules do not load at boot even though the modules are enabled. Toggling each of the modules off and on (without requiring any reboot in between) fixes the issue. It would be nice if there was a Toggle all feature to remove the extra work.

Yes, I know it's a bug and should have a separate issue but my Magisk log is not working for some reason, so I am unable to create a proper issue for the bug report.

**Comment by topjohnwu** [comment]
If you know how the enabling/disabling works, toggling the module won't do anything useful.
Also, if you want to disable all modules at a time, turn on core only mode in settings
