### ISSUE TITLE
The latest canary versions make Dash charge by OnePlus not working.

### ISSUE THREAD

**Issue by fantee** [topjohnwu/Magisk#1649]
The latest canary versions make Dash charge by OnePlus not working.

**Comment by lirannl** [comment]
This also applies to warp charge on the OP7P Pro.

Downgrading to 19.3 fixed the issue.

**Comment by AnnieTheEagle** [comment]
Yes. This is occuring for me on a EU (Model Number: GM1913) OnePlus 7 Pro for me with Canary. Rolling back to Stable solves the issue completely.

Would this issue show in Magisk logs or would a Logcat be better?

**Comment by alexa-v2** [comment]
Just to cover the bases, I'd advise getting the magisk log, a boot log, and a logcat of you trying to charge

**Comment by osm0sis** [comment]
We've found in internal testing that it seems to be the new SAR boot mode causing the issues, where the old mode, now known as SARCompat, still allows it to work fine.

To trigger SARCompat as a workaround you can flash a custom kernel that adds something to the ramdisk in the /overlay directory.

**Comment by AnnieTheEagle** [comment]
Is this something that can be fixed in SAR? Or will we need to remain in SARCompat ? Is there an easy way to make a module that adds a file to /overlay directory of the RAM disk?

**Comment by osm0sis** [comment]
/overlay needs to be in the ramdisk. Modules don't make sense for that at all.

Hopefully @topjohnwu can figure it out and it can be fixed; we don't know why it's broken yet.

**Comment by osm0sis** [comment]
Nevermind, I figured it out just now poking around on my 6T while in SAR mode. In SAR it is missing `/sbin/charger`, `/sbin/charger_log`, and `/sbin/dashd`. Off mode charging is also definitely broken again due to this.

I think @topjohnwu will just need to fix up the file linking logic from /system_root/sbin to his custom /sbin and it'll work great again. :+1:

**Comment by topjohnwu** [comment]
This should fix your issue: 05658cafc740fbb5a121aaed3546c23634767717
