### ISSUE TITLE
Magisk v12.0 didnt install MagiskSU?

### ISSUE THREAD

**Issue by wzhy90** [topjohnwu/Magisk#165]
I have compare with v11.6 and v11.1. Only v11.1 has a script install MagiskSU?
But I flash v11.1 it didnt install Magisk itself. v11.6 and v12 only install Magisk but without MagiskSU

**Comment by wzhy90** [comment]
Using Sony stock 7.0 and official TWRP

**Comment by TheComputerGuy96** [comment]
@wzhy90 Can you post TWRP recovery.log?

**Comment by 3xpent** [comment]
The cause is Sony RIC service, see this thread at xda: https://forum.xda-developers.com/crossdevice-dev/sony/patched-magisk-v12-sony-devices-t3582331

**Comment by wzhy90** [comment]
Yes, cause by Sony RIC. I have confirmed.
