### ISSUE TITLE
Magisk v19.3 regression over Magisk v18.1

### ISSUE THREAD

**Issue by kmdm** [topjohnwu/Magisk#1651]
I've been using this ROM on my Nexus 7 (2013) (deb): https://forum.xda-developers.com/nexus-7-2013/development/rom-lineageos-16-0-t3903286

Works absolutely fine with Magisk v18.1 and I can pass both basic and cts profiles. 

After upgrading to Magisk v19.3 both basic and cts profiles return false and fail. 

The only other notable thing with v19.3 installed (or no Magisk installed) is that Android reports a trust violation due to the ROM/build being signed by "public keys".

**Comment by topjohnwu** [comment]
Report with canary builds, not public builds
