### ISSUE TITLE
hide magisk doesn't work for HSBC HK banking app on Android Pie

### ISSUE THREAD

**Issue by moralrebuild** [topjohnwu/Magisk#1652]
What have been done
step 1. Android 9.0 (lineage OS 16) phone (Nexus 6) installs the latest Magisk v19.3 and Magisk Manager v7.3.2
step 2. install [HSBC HK Mobile Banking](https://play.google.com/store/apps/details?id=hk.com.hsbc.hsbchkmobilebanking&hl=en_US)
step 3. go to the hide magisk settings of Magisk Manager and then tick the app of HSBC HK Mobile Banking
step 4. start the banking app

What is the result:
The banking app detected that the phone was rooted and quit immediately

**Comment by DenyDarko** [comment]
It works fine:
![Screenshot_20190630-163726](https://user-images.githubusercontent.com/3320229/60397393-6f19d480-9b55-11e9-99ef-94b7db6dd5c9.jpg)

Furthermore:
#1152

**Comment by moralrebuild** [comment]
@DenyDarko  Can you tell me what's your Android version and any tricks have you applied?  I went over you mentioned threa and found no help.

**Comment by DenyDarko** [comment]
No tricks. Just the usual Hide. 

Plain stock OOS Open Beta 21 (Android 9, June Security Patch) on OnePlus 6.

**Comment by topjohnwu** [comment]
#1152

**Comment by moralrebuild** [comment]
@topjohnwu zero helpful info. If Magisk claims providing hide feature, prove itself on the main stream OS (for e.g. lineage OS 16) with main stream banking app, like HSBC.

**Comment by moralrebuild** [comment]
@DenyDarko  I suppose you are lucky one but nothing else, so don't say it work just with your niche configuration.

**Comment by Didgeridoohan** [comment]
@moralrebuild That link was just to tell you that requests for specific app's root detection will be ignored here on Github...

@DenyDarko have showed you that Magisk can hide itself perfectly fine from that app (and I can confirm that's the case on my devices as well). If hide isn't working for you, you either have something on your device that the app is detecting and that Magisk can't hide, or (and this is my main guess) you haven't hidden the Manager itself (take a look in the Manager settings).

**Comment by moralrebuild** [comment]
@Didgeridoohan Thanks for your reminder. It finally works and the key was 'Hide Magisk Manager'.  But somehow the feature is not very stable, I recalled that I had tried it at the very beginning and it messed itself by reporting no magisk installed. Anyway after a few times unstallation and reinstallation, the magisk manager hide itself peacefully.

**Comment by devsk** [comment]
Sorry for waking the sleeping giant but its relevant. It looks like HSBC app runs fine until I have a terminal app running with 'su' and the HSBC seems to detect it and claim that its a rooted device.

Is there a way hide one app from another app? Or stop an app from listing running processes? Or would the app consider that as evasion and think that its rooted?

**Comment by jamesWalker55** [comment]
Had an issue with HSBC HK detecting root as well.

I had already hidden the magisk app and called it "Magical Settings", but apparently HSBC still managed to detect the magisk app.

I finally got it working by renaming the magisk app to just "Apples" and HSBC no longer detects root.

**Comment by wezfaas** [comment]
> Had an issue with HSBC HK detecting root as well.
> 
> I had already hidden the magisk app and called it "Magical Settings", but apparently HSBC still managed to detect the magisk app.
> 
> I finally got it working by renaming the magisk app to just "Apples" and HSBC no longer detects root.

Well, I guess I'm too desperate to try the name "Apples", but as expected, it doesn't work for me.  Can you provide infos on your other settings like Systemless hosts, Enforce DenyList etc.

**Comment by Malvineous** [comment]
I had the same problem with HSBC AU.  [This page](https://droidwin.com/how-to-hide-root-from-apps-via-magisk-denylist/) says to install the Zygisk Assistant and to disable "Enforce DenyList" (which apparently makes Zygisk do the hiding instead of Magisk) however this just made the HSBC app freeze and not respond instead, with an Android popup coming up after a while saying the app keeps crashing.

I think I'm just going to close my HSBC account, their apps and website are the most cumbersome and onerous I've ever used.  It's not worth my time to battle with them every time I want to do something, and there are plenty of other banks out there who have software developers who actually know what they're doing.
