### ISSUE TITLE
Can't run Magisk Manager without an internet connection (or in Airplane Mode) - stuck on "Checking for updates..."

### ISSUE THREAD

**Issue by diamondavocado** [topjohnwu/Magisk#1658]
As per the title. 

If you don't have an internet connection or you're using airplane mode, you cannot install and launch Magisk Manager because it gets stuck on "Checking for updates..." infinitely. 

I guess there is no timeout on the update check? If the server ever goes down I guess this also means the app will be unusable unless there is a timeout.

**Comment by alexa-v2** [comment]
It'll still work but internet things like update check won't work correctly or at all (eg, downloads section disappeared). I think though most apps expect an "always on_ internet connection and in cases like this, get buggy

**Comment by topjohnwu** [comment]
Fixed in upstream
