### ISSUE TITLE
Tapping the 'Download Complete' notification immediately begins module flashing

### ISSUE THREAD

**Issue by seffparker** [topjohnwu/Magisk#1659]
When we chose to Download a module via Magisk Manger without flashing, and hit the 'Download complete ' notification, the Magisk Manager immediately begins the flashing without any further confirmation.

Then we need to reboot two times to get rid of that module.

It would be better if it wait for user's confirmation before flashing automatically.

**Comment by alexa-v2** [comment]
Just so you know you can delete the module folder in /data/adb/modules and /data/adb/modules_update and it'll never activate the modules

**Comment by topjohnwu** [comment]
In the new implementation, the tapping the notification will only flash if only you selected "Install" when you download the module.
