### ISSUE TITLE
Grab Driver app still detects root after hiding Manager.

### ISSUE THREAD

**Issue by MikuDroid** [topjohnwu/Magisk#1661]
Even AFTER and BEFORE hiding magisk manager, grab driver still detects root. I also attached logcat, and magisk logs. Hope this issue will be fixed soon cause i reached dead end on what should i do next.
[2019-07-02-23-14-15.txt](https://github.com/topjohnwu/Magisk/files/3357835/2019-07-02-23-14-15.txt)
[magisk.txt](https://github.com/topjohnwu/Magisk/files/3357836/magisk.txt)

**Comment by gloeyisk** [comment]
> Even AFTER and BEFORE hiding magisk manager, grab driver still detects root. I also attached logcat, and magisk logs. Hope this issue will be fixed soon cause i reached dead end on what should i do next.
> [2019-07-02-23-14-15.txt](https://github.com/topjohnwu/Magisk/files/3357835/2019-07-02-23-14-15.txt)
> [magisk.txt](https://github.com/topjohnwu/Magisk/files/3357836/magisk.txt)

Does both SafetyNet passed?

**Comment by rama982** [comment]
#1152

**Comment by hoost-pt** [comment]
Same problem here with this app https://play.google.com/store/apps/details?id=pt.viaverde.clientes&hl=pt_PT
All Ok with Magisk 19.2

Oneplus One with Tugapower ROM (Lineage base)
Magisk 19.3 (19300)
Magisk Manager 7.3.2 (224)
SafetyNet OK

**Comment by MikuDroid** [comment]
> > Even AFTER and BEFORE hiding magisk manager, grab driver still detects root. I also attached logcat, and magisk logs. Hope this issue will be fixed soon cause i reached dead end on what should i do next.
> > [2019-07-02-23-14-15.txt](https://github.com/topjohnwu/Magisk/files/3357835/2019-07-02-23-14-15.txt)
> > [magisk.txt](https://github.com/topjohnwu/Magisk/files/3357836/magisk.txt)
> 
> Does both SafetyNet passed?

it's passed, i'm confused so i ask here.

**Comment by MikuDroid** [comment]
> #1152

ah, sad to hear that. i'll close the issue then.

**Comment by MikuDroid** [comment]
actually, I'll reopen the issue now as i found this app using UDS detection to detect magisk/root. Because when i check my device using rootbeer fresh, only uds detection that triggered after hiding the app using magisk hide. Can developers do something about this UDS detection stuff?

**Comment by gloeyisk** [comment]
> 
> 
> actually, I'll reopen the issue now as i found this app using UDS detection to detect magisk/root. Because when i check my device using rootbeer fresh, only uds detection that triggered after hiding the app using magisk hide. Can developers do something about this UDS detection stuff?

Decompile the APK and remove the root detection? Just my opinions, might it help.

**Comment by MikuDroid** [comment]
> > actually, I'll reopen the issue now as i found this app using UDS detection to detect magisk/root. Because when i check my device using rootbeer fresh, only uds detection that triggered after hiding the app using magisk hide. Can developers do something about this UDS detection stuff?
> 
> Decompile the APK and remove the root detection? Just my opinions, might it help.

The thing is, i don't know how.

**Comment by obengsakti** [comment]
not magisk bro! tapi xposed yang detects  . i have solution for you . wani pirooo??

**Comment by MikuDroid** [comment]
> not magisk bro! tapi xposed yang detects . i have solution for you . wani pirooo??
Implying I'm using xposed lmao. Also, stop putting comment on closed issue.

**Comment by MikuDroid** [comment]
sorry for bringing up old issue, but i just want to confirm that **this issue is gone with the latest magisk version!** huge thanks for the newest hiding method! @topjohnwu

**Comment by MikuDroid** [comment]
I'm sorry i bumped the old and closed issue. I just wanna say thanks for the latest update (20.4), this app is not bugging about root detection anymore. Huge thanks once again!

**Comment by MikuDroid** [comment]
Latest Grab Driver update (5.119.0) trips root detection again in magisk 20.4. This cat and mouse game isn't going to end i suppose :(

**Comment by amk316** [comment]
the latest update for "stc pay" can deduct rooting using UDS!!!
i though magisk has solve UDS deduction for ever.

**Comment by phr34k0** [comment]
Latest Magisk and Latest grab driver. Root detected even if hide 

![Screenshot_2020-09-08-00-44-26-060_com yB5P joEThL0a nJ](https://user-images.githubusercontent.com/13272249/92407322-cc9fad00-f16c-11ea-94b2-c518925a6c8c.png)
![Screenshot_2020-09-08-00-44-12-000_com grabtaxi driver2](https://user-images.githubusercontent.com/13272249/92407323-ce697080-f16c-11ea-8e08-170ef03a0103.png)

**Comment by phr34k0** [comment]
Latest Magisk and Latest grab driver. Root detected even if hide 

![Screenshot_2020-09-08-00-44-26-060_com yB5P joEThL0a nJ](https://user-images.githubusercontent.com/13272249/92407322-cc9fad00-f16c-11ea-94b2-c518925a6c8c.png)
![Screenshot_2020-09-08-00-44-12-000_com grabtaxi driver2](https://user-images.githubusercontent.com/13272249/92407323-ce697080-f16c-11ea-8e08-170ef03a0103.png)
![Screenshot_2020-09-08-00-47-47-095_com android settings](https://user-images.githubusercontent.com/13272249/92407377-0670b380-f16d-11ea-84a4-52c4ef326b59.png)
