### ISSUE TITLE
Stuck on Bootlogo Samsung Galaxy S10 Plus SM-G975F DBT @ G975FXXU2ASF3

### ISSUE THREAD

**Issue by Psmk182** [topjohnwu/Magisk#1663]
I installed Magisk on my S10 Plus today.
Everthing worked fine.
After a few app installs, magisk was showing me that a update is avaiable.

After i installed the update i pressed on reboot.
After this i stucked at SAMSUNG bootlogo.
Im using latest firmeware G975FXXU2ASF3.

**Comment by ianmacd** [comment]
Two questions:

Are you on stock ROM or something else?

Which update channel provided the update?

**Comment by Knusteple** [comment]
Same happened to me when I update to the newest version.  I tried on the two s10+ custom roms in xda developer section.

**Comment by Knusteple** [comment]
The top update channel in Magisk Manager named: 
19305😊

**Comment by topjohnwu** [comment]
@Knusteple it works on stock ROM, so it is not an issue on Magisk's side
