### ISSUE TITLE
No app installed after flashing Magisk zip

### ISSUE THREAD

**Issue by SmartManoj** [topjohnwu/Magisk#1667]
Moto E condor
Lineage 15.1 Oreo
Tried also using adb
`adb: failed to install MagiskManager-v7.3.2.apk: Error: failed to write; readlink failed: EACCES (Permission denied)`

**Comment by topjohnwu** [comment]
Github issues are not for support

**Comment by SmartManoj** [comment]
https://forum.xda-developers.com/moto-e/development/rom-lineageos-15-0-unofficial-t3678226/post75758264#post75758264
