### ISSUE TITLE
Superuser request dialogue does not trigger in Swift Backup

### ISSUE THREAD

**Issue by jslawler** [topjohnwu/Magisk#1668]
### Description
When Swift Backup requests superuser rights, Magisk does not prompt the user.
This issue does not appear to affect all devices as this was tested on 2 devices prior to raising this issue.

### Steps to reproduce

1. Start Swift Backup
2. Complete initial app prompts
3. Superuser access should be requested here, but times out instead of showing the dialogue.

### Screen Records
<details><summary>Video 1 - OnePlus 6/OxygenOS 9.0.7</summary>

![OnePlus 6](https://user-images.githubusercontent.com/6005161/60727933-a65dfc00-9f2e-11e9-8282-f17b6c45ba5a.gif)

</details>

<details><summary>Video 2 - Pixel 2 XL</summary>

Video removed to scrub personal information. Will be re-uploaded.

</details>

### Notes from the Swift Backup developer
When analysing the logs, he thought this may be of some interest.
`D/ActivityTrigger(886): activityStartTrigger: Activity is not Triggerred in full screen ApplicationInfo{9ce8dcc com.topjohnwu.magisk}`

### Logs
[logs-2019-07-05-22-54-23.zip](https://github.com/topjohnwu/Magisk/files/3363030/logs-2019-07-05-22-54-23.zip)

### Versioning
**Magisk**: 19305(Also tested on 19300)
**Magisk Manager**: 224
**Swift Backup**: 3.0.3

**Comment by topjohnwu** [comment]
It works fine on my device.
