### ISSUE TITLE
Nice to have: Make magisk-module-installer a template repository

### ISSUE THREAD

**Issue by crass** [topjohnwu/Magisk#1669]
I hope this would be the right place for this issue, didn't see a better place.

It would be nice to have the magisk-module-installer be a template repository on github.  It should be as simple as checking the template repository checkbox from the repo options page on github.

https://help.github.com/en/articles/creating-a-repository-from-a-template

**Comment by topjohnwu** [comment]
It used to be, but morons keep creating PRs to the repo, so I archived it to make it read-only
