### ISSUE TITLE
Magisk 12.0 doesn't work well with MIUI

### ISSUE THREAD

**Issue by MurdererFight** [topjohnwu/Magisk#167]
Initially, SafetyNet will fail in any case and to make it working you need to input in a terminal:

sh magisk/.core/magiskhide/disable
sh magisk/.core/magiskhide/enable

multiple times then SafetyNet start to work but Magisk will lose root, only Terminal can get su permission and other apps can't detect root. I dont' encounter those issues on Nougat custom roms.
Already disable busybox on MagiskManager and Systemless ADs supports, only MagiskHide is enabled and still doesn't work.

MIUI 8 Global Developer 7.4.6 with Stock Kernel / Xiaomi Redmi Note 3 Pro

**Comment by Redsandro** [comment]
I cannot get past _"CTS profile mismatch"_ either, on MIUI 8 EU Developer 7.4.6 / Xiaomi Mi 5

**Comment by MurdererFight** [comment]
You need to use MIUI Stable fingerprint, so install/ask someone to get "ro.build.fingerprint" and "ro.build.description" and replace those values with your

**Comment by MurdererFight** [comment]
But even with thise values MagiskHide will still not work. But I get both BasicIntergrity and CATS Profile to green when I run the commands

**Comment by purval6300** [comment]
do one thing use any root explorer and go to /magisk/.core/magiskhide and open enable file using any text editor and replace last line with 
(su -c $BINPATH/magiskhide --daemon)
this one..and toogle magisk hide

**Comment by Redsandro** [comment]
@MurdererFight said:
> You need to use MIUI Stable fingerprint, so install/ask someone to get "ro.build.fingerprint" and "ro.build.description" and replace those values

@purval6300 said:
> go to `/magisk/.core/magiskhide` and (...) replace last line with `(su -c $BINPATH/magiskhide --daemon)`

I've seen a lot of different instructions scattered across XDA topics and Github issues that I haven't seen in the documentation. And users commenting that it still doesn't work.

I wonder if there's a step by step guide somewhere.

**Comment by moep1234** [comment]
i have also an mi5 with the newest xiaomi.eu rom 7.4.6 and testing a long time now magisk versions... no verision is working :/    "(su -c $BINPATH/magiskhide --daemon)" does not work too
