### ISSUE TITLE
MagiskManager crash when installing local module with bad update-binary

### ISSUE THREAD

**Issue by crass** [topjohnwu/Magisk#1670]
MagiskManager 7.3.2, Magisk 19.3

While testing a module I'm creating starting from the module template repo, I forgot to overwrite the update-binary from the non-working default version in the template repo with module_installer.sh.  When installing the module, MagiskManager log of the installation doesn't finish and goes to a white screen and is unresponsive until I kill it.

It would be nice if this edge case printed a failure log message and rolled back the install.

**Comment by DenyDarko** [comment]
A logcat would be nice

**Comment by alexa-v2** [comment]
Magisk should replace that file forcefully anyway, so there's a bug elsewhere here

Need Magisk logs and a logcat

**Comment by Didgeridoohan** [comment]
@alexa-v2 Only when downloading from the Magisk repo. Installing a module manually will not replace the file.

**Comment by alexa-v2** [comment]
@didgeridoohan documentation says "on install" didn't realize that means "on _download_ and install"

**Comment by Didgeridoohan** [comment]
@crass Is this still a thing? I've tested but can't reproduce the issue (I just get the expected "Installation failed")...

If it is, you need to provide the proper [logs](https://www.didgeridoohan.com/magisk/MagiskHide#hn_Hiding_root_from_apps) to show what's happening on your device.
