### ISSUE TITLE
Bootloop oneplus 6 after upgrade to 9.0.7

### ISSUE THREAD

**Issue by MarianKot** [topjohnwu/Magisk#1671]
TWRP bootloop on OnePlus 6 after OS upgrade

**Comment by Shenron0** [comment]
The guide to prevent that is on XDA if you've never read it

**Comment by MarianKot** [comment]
Mea culpa, I've missed the thread. Closed issue for me now...

**Comment by yondaime1992** [comment]
Hi, I have the same problem.
I've already read a lot of guides on XDA.
I tried to patch stock boot.img through magisk and through fastboot boot the device for install magisk with magisk manager but the device restarts continuously.
If I reinstall the full rom and bluespark twrp the phone works correctly (obviously without root), but when i try to install magisk both through patched boot.img and through flashing zip of magisk 19.3 it restarts continuously.

**Comment by yondaime1992** [comment]
Solved, I first of all flashed magisk_unistaller and now all works
