### ISSUE TITLE
Auto Reboot after successful boot

### ISSUE THREAD

**Issue by Mohsyn** [topjohnwu/Magisk#1673]
Magisk 19305
Phone: Honor View 10

Phone boots successfully but restarts as soon as boot is complete in some seconds.
It has root access at that time, but before I can check anything phone restarts.

I've full logcat - please let me know if a part of it is required or full ?

**Comment by topjohnwu** [comment]
I'm pretty sure this only happens when you flashed the erecovery ramdisk, not recovery ramdisk

**Comment by Mohsyn** [comment]
I have flashed recovery_ramdisk - my devices does not allow flashing of erecovery
I get this in logcat
Command=/system/bin/app_process /system/bin com.android.commands.am.Am broadcast -n com.topjohnwu.magisk/a.h --user 0 -f 0x00000020 -a android.intent.action.REBOOT --es action test
