### ISSUE TITLE
Magisk won't add files from a module with /system/product/*

### ISSUE THREAD

**Issue by MrBaNkS** [topjohnwu/Magisk#1676]
Magisk is running great and stable on Canary, but me and many other people on Mata (Essential PH-1) can't add files to /system/product after this commit: https://github.com/topjohnwu/Magisk/commit/e8b73ba6d1d142b623b7d4da0c2acb8be674407b
We don't have a /product partition so when the symlink to /system/product to /product is made nothing shows up there when files in a module with /system/product/* are added. On top of that we already had that symlink from /system/product to /product. If logs are needed I can provide.

**Comment by MrBaNkS** [comment]
Magisk Log: 

[magisk_log_20190707_120703.log](https://github.com/topjohnwu/Magisk/files/3365909/magisk_log_20190707_120703.log)

**Comment by MrBaNkS** [comment]
Lol yeah my fault I should have done that ☺️

**Comment by Uzver123** [comment]
I have same exact problem on Android 13 Placing files in system/product/ with magisk does not work however placing in system/product/media/ works.
