### ISSUE TITLE
Magisk breaks lockscreen on android pie

### ISSUE THREAD

**Issue by akano12** [topjohnwu/Magisk#1682]
hey,i have a samsung j6+ (j610f) that had 8.1.0 oreo preinstalled, rooted it with magisk. but this device had security in its kernel that limited the work of magisk and most of root apps failed to obtain su permission, a recognized developer from xda rebuilt the stock kernel and removed the security and magisk worked fine.

now my device received 9.0 ( one ui version 1), tried flashing magisk from twrp,always got magisk not installed from the manager + flashing magisk broke the lockscreen. a senior member from xda rebuilt the stock kernel and removed the security, magisk worked and all root apps work,but still locksreen is broken.

if i put password/pin or whatever and lock the phone,i can't unlock it ,always get wrong pin/password error (ofc im typing the password correctly),if i restart my phone,it will get stuck in bootloop,deleting the locksetting.db from twrp file manager fixes the bootloop but not the lockscreen

is there a fix for the locksreen?are there any logs that help detect whats causing the problem?

**Comment by topjohnwu** [comment]
Report with canary builds

**Comment by akano12** [comment]
@topjohnwu tried flashing latest canary,phone didn't boot at all,it just hangs at J6+logo screen then turn on and off continuously :(

**Comment by akano12** [comment]
@topjohnwu canary never worked on my j610f, always end up with bootloop
stable/beta works just fine
