### ISSUE TITLE
Patch boot.img failed on Pixel 3 running Android Q Beta 5

### ISSUE THREAD

**Issue by MichaelPan1026** [topjohnwu/Magisk#1687]
I just upgraded to Android Q Beta 5 on Pixel 3. When I tried to patch boot.img with latest canary Magisk manager, it notified me failed. I searched a lot about this and found somebody managed to do that just with a lot of tries. But I cannot do that still until now.

**Comment by MichaelPan1026** [comment]
Oh I found the solution, it's not caused by Magisk but Android Q itself. Just check Installing Unknown Apps in App's setting then retry.

**Comment by martyfender** [comment]
Yes, that has alway been true, as far as I know, one must go to settings, security and allow apps from unknown sources.

**Comment by Octal450** [comment]
I've never had to do that? Is that Pixel 3 only?

**Comment by Didgeridoohan** [comment]
@Octal450 Android Q

**Comment by Octal450** [comment]
Gotcha
