### ISSUE TITLE
Failed to patch boot.img on Pixel 3 XL Android 10 Beta 5

### ISSUE THREAD

**Issue by fr34kyn01535** [topjohnwu/Magisk#1689]
I've tried patching the boot image for my Pixel 3XL with MagiskManager-v7.3.2 and MagiskManager-v7.3.3 and received an error in the last step when copying the patched boot image to storage. 

![Screenshot_20190712-131451](https://user-images.githubusercontent.com/898145/61124648-ae2a1d00-a4a7-11e9-835e-06d3c9607cbb.png)

File Storage Permission has been granted and was successfully requested.

`07-12 13:08:19.444 25242 25893 W System.err: java.io.FileNotFoundException: /storage/emulated/0/Download/magisk_patched.img: open failed: EACCES (Permission denied)
07-12 13:08:19.444 25242 25893 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:496)
07-12 13:08:19.444 25242 25893 W System.err:    at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
07-12 13:08:19.444 25242 25893 W System.err:    at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
07-12 13:08:19.444 25242 25893 W System.err:    at a.xp0.e(SourceFile:3)
07-12 13:08:19.444 25242 25893 W System.err:    at a.cr0.d(Unknown Source:0)
07-12 13:08:19.444 25242 25893 W System.err:    at a.uq0.run(Unknown Source:2)
07-12 13:08:19.444 25242 25893 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-12 13:08:19.444 25242 25893 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-12 13:08:19.444 25242 25893 W System.err:    at java.lang.Thread.run(Thread.java:919)
07-12 13:08:19.444 25242 25893 W System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
07-12 13:08:19.444 25242 25893 W System.err:    at libcore.io.Linux.open(Native Method)
07-12 13:08:19.444 25242 25893 W System.err:    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
07-12 13:08:19.444 25242 25893 W System.err:    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
07-12 13:08:19.444 25242 25893 W System.err:    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
07-12 13:08:19.444 25242 25893 W System.err:    at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7242)
07-12 13:08:19.444 25242 25893 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:482)
07-12 13:08:19.444 25242 25893 W System.err:    ... 8 more`

https://github.com/topjohnwu/Magisk/blob/188ea2644a846f0b5f78648a901020cb69c4eb19/app/src/main/java/com/topjohnwu/magisk/tasks/MagiskInstaller.java#L339

**Comment by fr34kyn01535** [comment]
https://github.com/topjohnwu/Magisk/issues/1687 fixed it. Weird error.

**Comment by anvypuppy** [comment]
Hello. I faced the same problem like yours. How could you fix it? Thx

**Comment by fr34kyn01535** [comment]
Manually grant the permission to install unknown apps to the MagiskManager.

**Comment by anvypuppy** [comment]
It got fix, thx. It seems like some apps requires storage permission had the same problem, such as pandownload. I have to switch it so that it can modify the storage.
