### ISSUE TITLE
Magisk Manager doesn't start the patching process.

### ISSUE THREAD

**Issue by EtherealCod3** [topjohnwu/Magisk#1690]
Device: Mediacom Smartpad 10HX (SP10HX - Based on Mediatek 6580/8321)
Magisk Manager Version: 7.3.2
Android Version: 6.0
Bootloader: Unlocked
Recovery: Stock
Steps: Extracted stock boot.img from stock rom provided by the vendor.
Placed into Download folder.
Installed Magisk Manager APK latest 7.3.2 build, selected "Select and update a file".
Selected boot.img file to patch.
Issue: Nothing happens after selection.
Patching process doesn't even start.
Magisk Manager simply goes back to its home window (display status of magisk manager and magisk).
Tried to patch boot.img from my phone (different arm arch and android version). Patching process completes , however when flashing boot.img back to the tablet, flashing is done but magisk is not installed.

**Comment by topjohnwu** [comment]
Please test with canary channel and provide full logcats
