### ISSUE TITLE
Please adapt MIUI SU

### ISSUE THREAD

**Issue by liyuxi** [topjohnwu/Magisk#1691]
The first time MIUI su（In MIUI Development Edition of China ROM）will defaulted reject any root permission request，user need to manually enable. But Magisk Manager will never to recheck the root permission. Please provide a method to recheck the root permission or check the root permission when Magisk Manager launch and Magisk Module is not installed

**Comment by DenyDarko** [comment]
https://github.com/topjohnwu/Magisk/commit/7bad6ec1fb399c5ca60c873b6a0b6e5f0cd4fd95

Related?

**Comment by liyuxi** [comment]
> [7bad6ec](https://github.com/topjohnwu/Magisk/commit/7bad6ec1fb399c5ca60c873b6a0b6e5f0cd4fd95)
> 
> 有关？

No，my mean is MIUI su permit Magisk Manager root，which don’t find. Because the first time MIUI su rejected Magisk Manager whose request.

**Comment by topjohnwu** [comment]
Forget about it, I will not support MIUI su as it is impossible
