### ISSUE TITLE
Can't install apps after rooting device with Magisk

### ISSUE THREAD

**Issue by VladimirMikulic** [topjohnwu/Magisk#1693]
Hi, as the title says after I've rooted my device with Magisk I can't install apps on my device anymore. On Google Play Store I get "Can't install app 963" and if I try to install a file.apk I get "App not installed".

> What's funny about this is that when I unroot device with Magisk uninstaller everything works fine again. SuperSU also works.

I want Magisk, it has many features and SuperSU is abandoned and deprecated.

### ADDITIONAL INFO:
**Device**: sm-g531h
**ROM**: DotOS 2.4 Oreo (I've tried switching ROMs, but the problem is in Magisk)
**ADB apk installation error message**: 
"adb: failed to install Downloads/MagiskManager-v7.3.2.apk: Error: failed to write; readlink failed: EACCES (Permission denied)"

**Comment by topjohnwu** [comment]
Please provide full logcat. And also, test with using the latest canary builds

**Comment by VladimirMikulic** [comment]
I tested Magisk with stock ROM of my phone(sm-g531h) and it works fine.
It doesn't work with custom ROM(yes, not even canary builds).

Why?

**Comment by VladimirMikulic** [comment]
@topjohnwu LOG: 
[log.txt](https://github.com/topjohnwu/Magisk/files/3403499/log.txt)

**Comment by xawlw** [comment]
Try this https://forum.xda-developers.com/showpost.php?p=76108327&postcount=47

**Comment by VladimirMikulic** [comment]
@xawlw WOW, this fixed the problem. Thank you very much. I really appreciate your help.

**Comment by xawlw** [comment]
@VladimirMikulic No problem, Also I think this is a kernel side issue
Try to build a kernel with this commit as it might help https://github.com/Albe96XDA/Aspiration_Kernel_J2LTE-MM/commit/b506dad4cf1b5ca0c89f315696ca1d9d74b80eaf

**Comment by VladimirMikulic** [comment]
@xawlw The link that you provided doesn't work.

**Comment by xawlw** [comment]
@VladimirMikulic I'm having the same issue but I still can't figure why it happens

But I'm sure it's kernel specific as it working on other kernels for my device
