### ISSUE TITLE
lockscreen bug (keystore write) &  samsung account doesn't work after flash magisk and magisk canary(19.4)

### ISSUE THREAD

**Issue by Kopra159** [topjohnwu/Magisk#1696]
@topjohnwu    
**AFTER FLASH ALL MAGISK VERSION 2 BUGS appears  :**
_1- ALL lockscreen  types won't work ._ 
_2- Samsung account won't work ._

**https://github.com/topjohnwu/Magisk/issues/1617**

**I tried also magisk canary(19.4) but it failed .**

the problem noone can fix it and it relate to magisk , I am sure .                                                           Excuse me , CAN u try to see it and any logs or logcat or files u need I will send it to U .
AND I am sure u will solve it .
and very thanks for reading this issue .

**Comment by akano12** [comment]
same on note 9 https://github.com/topjohnwu/Magisk/issues/1344
and j6+
if u have u2 on your j4+ u can downgrade to u2 oreo
on j6+ i can't downgrade, because there isn't u2 for oreo,only u1 :(
