### ISSUE TITLE
Devices won't boot with patched boot.img in pixel 3 running Q beta 5.

### ISSUE THREAD

**Issue by OzzyThorne** [topjohnwu/Magisk#1698]
Apparently, I can't provide a log.

**Comment by topjohnwu** [comment]
You have incompatible module enabled......
I am using Pixel 3 XL on Q B5

**Comment by OzzyThorne** [comment]
OK, I found it boot into system factually, cause the adb works. It's the system UI or other something doesn't work. So I can provide a bugreport using the adb.
[bugreport-blueline-QPP5.190530.014-2019-08-20-19-03-34.zip](https://github.com/topjohnwu/Magisk/files/3523639/bugreport-blueline-QPP5.190530.014-2019-08-20-19-03-34.zip)

**Comment by OzzyThorne** [comment]
> You have incompatible module enabled......
> I am using Pixel 3 XL on Q B5

No, no problem with moudules. Cause I switched to the special version  (https://raw.githubusercontent.com/yzkpqv68745/magisk/master/core.json) and this problem doesn't disappear.
