### ISSUE TITLE
Incomplete bind_mount under /system/vendor and /system/lib64

### ISSUE THREAD

**Issue by laggardkernel** [topjohnwu/Magisk#17]
There are still some problems concerning mounting files under /system/vendor and /system/lib64. bind_mount under these places are incomplete, some files are left out unmounted.

Tested on OnePlus3, OxygenOS 3.2.7, Marshmallow 6.0.1. Magisk v9 + phh's superuser.
1. The first case is related to overlay folder under /system/vendor. 
**NOTE**: /system/vendor/overlay does **NOT** exist in the OxygenOS ROM originally.
Modified audio confs, the two confs below,
```
/magisk/v4a/system/vendor/etc/audio_output_policy.conf
/magisk/v4a/system/vendor/etc/audio_effects.conf
```
were ignored to be mounted when overlay theme apks were mounted under /system/vendor/overlay. See the Magisk log below,
```
** Magisk post-fs mode running...
** Magisk post-fs-data mode running...
Preparing modules
Bind mount dummy system
Mount: /dev/magisk/dummy/system/lib/soundfx
Mount: /dev/magisk/dummy/system/fonts
Mount: /dev/magisk/dummy/system/vendor
Mount: /dev/magisk/dummy/system/app
Mount: /dev/magisk/dummy/system/priv-app
Bind mount module items
Mount: /magisk/v4a/system/lib/soundfx/libv4a_fx_ics.so
Mount: /magisk/overlay/system/vendor/overlay
Mount: /magisk/ubuntu_font/system/fonts/Ubuntu-RI.ttf
Mount: /magisk/ubuntu_font/system/fonts/Ubuntu-R.ttf
```
While after I created a empty overlay folder under /system/vendor, the modified audio confs are mounted correctly. 
```
** Magisk post-fs mode running...
** Magisk post-fs-data mode running...
Preparing modules
Bind mount dummy system
Mount: /dev/magisk/dummy/system/lib/soundfx
Mount: /dev/magisk/dummy/system/fonts
Mount: /dev/magisk/dummy/system/app
Mount: /dev/magisk/dummy/system/priv-app
Bind mount module items
Mount: /magisk/v4a/system/lib/soundfx/libv4a_fx_ics.so
Mount: /magisk/v4a/system/vendor/etc/audio_output_policy.conf
Mount: /magisk/v4a/system/vendor/etc/audio_effects.conf
Mount: /magisk/overlay/system/vendor/overlay
Mount: /magisk/ubuntu_font/system/fonts/Ubuntu-RI.ttf
Mount: /magisk/ubuntu_font/system/fonts/Ubuntu-R.ttf
```

2. The 2nd case happened when I combined ViPER4Android and Dolby Atmos together, with additional libs, as a Magisk module. Using the two files below could reproduce the problem,
```
/magisk/v4a/system/lib64/soundfx/libeffectproxy.so
/magisk/v4a/system/lib64/libhwdaphal.so
```
**NOTE**: libeffectproxy.so is an existing lib on my ROM, but **NOT** libhwdaphal.so.
Similar result, libeffectproxy.so was omitted to be mounted, but libhwdaphal.so was mounted successfully.
```
** Magisk post-fs mode running...
** Magisk post-fs-data mode running...
Shrinking /data/magisk.img to 224M...
Preparing modules
Bind mount dummy system
Mount: /dev/magisk/dummy/system/lib64
Mount: /dev/magisk/dummy/system/fonts
Mount: /dev/magisk/dummy/system/app
Mount: /dev/magisk/dummy/system/priv-app
Bind mount module items
Mount: /magisk/v4a/system/lib64/libhwdaphal.so
Mount: /magisk/overlay/system/vendor/overlay
Mount: /magisk/ubuntu_font/system/etc/fonts.xml
Mount: /magisk/ubuntu_font/system/etc/fallback_fonts.xml
```

It seems **adding new items and replacing existing items at the same time** under /system/vendor and /system/lib64, maybe /systen/bin as well, could **NOT** be done correctly yet. Is it a logical oversight in the mount mechanism?

**Comment by topjohnwu** [comment]
Nice finding, I'll try and see 👍

**Comment by laggardkernel** [comment]
@topjohnwu Stuck at boot animation when mounting binaries. According to the magisk.log, everything worked okay and ended with late_start service mode running. I couldn't use mods with binaries mount since v7. But it did work on v6. Any ideas? Do you need any logs other that magisk.log for analysis?
