### ISSUE TITLE
Install support for Huawei Mate 9

### ISSUE THREAD

**Issue by wrecklesswun** [topjohnwu/Magisk#170]
[boot.emmc.zip](https://github.com/topjohnwu/Magisk/files/915461/boot.emmc.zip)

Included boot file backup from twrp

**Comment by Ante0** [comment]
There is no 'loop' support in pre-april 2017 builds of Mate 9 firmware. It does work in, for example, L29C432B182.
Any B180+ build should work. You should check the Mate 9 Guides over at XDA on how to update to the latest version of your model.
