### ISSUE TITLE
Can't root - unable to mount /system

### ISSUE THREAD

**Issue by alfredoivan** [topjohnwu/Magisk#1700]
Device: Alcatel Pixi 3 10 (8080)
Using: Carliv Touch Recovery v5.7.3 (twrp won't work)

I pushed the zip using:
adb push Magisk-v19.3.zip /internal_sd/clockworkmod/magisk.zip

And this is the output:
***********
*Magisk v19.3 Installer
***************
- Mounting system
! cannot mount /system
- Unmounting partitions
E: Installation error in
/data/media/0/clockworkmod/magisk.zip
(Status 1)

Install from sdcard complete.

Some other zip, like UPDATE-supersu, installed (albeit it doesn't work for other reasons).
I tried mounting /system before the magisk install procedure, from "Mounts/storage" - "Mount /system" but it doesn't work. Same output.

**Comment by topjohnwu** [comment]
Root your device with the patch boot image method. I do not want to waste any time on broken recoveries.
