### ISSUE TITLE
Magisk can't update over ethernet

### ISSUE THREAD

**Issue by mo123** [topjohnwu/Magisk#1701]
Please add ethernet update support too.
I just get connecting in Magisk Manager v7.3.2 if using ethernet, wifi turned off.
It can be useful for users using Android development boards that only have ethernet.

**Comment by ZVNexus** [comment]
What device are you using out of curiosity?

**Comment by mo123** [comment]
Using a Khadas Edge Android 9 development board.

Seems similar to this problem if using ethernet and wifi is switched off.
Magisk Manager infinitely checks for updates.
https://github.com/topjohnwu/Magisk/issues/1658

**Comment by topjohnwu** [comment]
Are you sure it has actual internet access? Magisk Manager uses the system APIs to detect whether internet access is available.

**Comment by topjohnwu** [comment]
Still no response... I'll close this issue
