### ISSUE TITLE
mount --bind problem (strange)

### ISSUE THREAD

**Issue by jancm** [topjohnwu/Magisk#1706]
Currently running v19.4-736729f5(19307)
Pixel 3 XL, Pie - July security patches (stock + Kirisakura kernel)
This used to work (for a long time) but since I don't trigger this very often I can't be 100% when this problem first occurred. I do think it was with 19307 though (or the one before that that was only up a few hours).

So I have a script, currently triggered via Edge Sense, which toggles the hosts file. Unmounts the current hosts file and then mounts either a copy of the default hosts, or the hosts file from the built-in hosts module, depending on which version was currently mounted. I'm attaching a copy of that script.
What's currently happening is, when I issue the bind mount, I get "permission denied".

However the really strange part is if I cd (using a terminal app) to the same directory the script is stored in and then manually enter the exact same command it works successfully. Try to execute the script from the terminal, it errors.

So the problem only occurs from within a script file. Here's a trace
+ MODDIR=. 
+ Loc=/data/media/0/ 
+ Hostfile=/system/etc/hosts 
+ Defhosts=./../misc-files/misc/default_hosts/hosts 
+ Suhosts=./../hosts/system/etc/hosts 
+ Adaway_hosts='mount --bind ./../hosts/system/etc/hosts /system/etc/hosts' 
+ Default_hosts='mount --bind ./../misc-files/misc/default_hosts/hosts /system/etc/hosts' 
+ rm -f /data/media/0/System_hosts.flg
+ '[' -e ./../hosts/system/etc/hosts ']'
+ grep -qi adaway /system/etc/hosts
+ su -mm -c umount -l /system/etc/hosts
+ su -mm -c mount --bind ./../misc-files/misc/default_hosts/hosts /system/etc/hosts
Permission denied

Need anything else, or have any questions, let me know.
[toggle_hosts.sh.txt](https://github.com/topjohnwu/Magisk/files/3409074/toggle_hosts.sh.txt)

**Comment by topjohnwu** [comment]
Host files can not be cleanly toggled when modules are used. You should be using the official host module, which can be enabled in Magisk Manager's settings

**Comment by jancm** [comment]
Just FYI, I figured out what was causing this. There's some sort of problem with su -c. Here's a test script:
set -x
su -c exit
su -c exit
su -c exit
su -c exit
su -c exit
su -c exit
su -c exit
su -c exit
sleep 3
su -c exit
sleep 3
su -c exit
sleep 3
su -c exit
sleep 3
su -c exit
sleep 3
su -c exit
sleep 3
su -c exit
exit

Here's the trace output:
+ su -c exit
+ su -c exit
Permission denied
+ su -c exit
+ su -c exit
Permission denied
+ su -c exit
+ su -c exit
Permission denied
+ su -c exit
+ su -c exit
Permission denied
+ sleep 3
+ su -c exit
+ sleep 3
+ su -c exit
+ sleep 3
+ su -c exit
+ sleep 3
+ su -c exit
+ sleep 3
+ su -c exit
+ sleep 3
+ su -c exit
+ exit

Note that 'sleep 2' still gives "Permission denied". And that after a "Permission denied" the next "su -c" works. After that failure, after that success, etc.
