### ISSUE TITLE
su -p does not preserve environment

### ISSUE THREAD

**Issue by crass** [topjohnwu/Magisk#1707]
Here's and excerpt from `su --help`:
```
Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                make the shell a login shell
  -m, -p,
  --preserve-environment        do not reset environment variables, and
                                keep the same shell
  -s, --shell SHELL             use SHELL instead of the default in passwd
...
```

However, when I do `su -p` or `su --preserve-environment` the environment is not preserved.  Specifically, I'm wanting `PATH` and `LD_LIBRARY_PATH` to be preserved (but maybe others as well).  In the case of `PATH`, it might be desirable to prepend some su binaries directories to the original path.

If we don't want to allow this functionality, perhaps just remove the option and help from `su`?

**Comment by topjohnwu** [comment]
Check the source code, the preserve environment option only affects `HOME`, `USER`, `LOGNAME`, and `SHELL`
