### ISSUE TITLE
superuser access request loop

### ISSUE THREAD

**Issue by nahdoubtit** [topjohnwu/Magisk#1709]
if you have fingerprint authentication enabled, failed and tried too many times, it tells you to try again later, during this if you go into the Magisk Manager app, go to super user, and try to enable it manually, the fingerprint prompt comes up, but since you were revoked and can't try, the popup keeps coming up and you can't authenticate or hit close, and you get stuck, forcing you to close the app to get out of the loop. 

video to understand better: https://u.teknik.io/r1Asg.mp4

**Comment by topjohnwu** [comment]
It is an issue with the fingerprint authentication process, which is controlled by the system, not Magisk Manager. Disable fingerprint in settings temporarily to workaround this issue.

**Comment by nahdoubtit** [comment]
Wasn't sure, figured I'd let you know, thanks for the response.

**Comment by alexa-v2** [comment]
Have a similar issue before

Found out it was resurrection remix "allow fingerprint authentication on boot" setting
