### ISSUE TITLE
Update Magisk without updating Manager

### ISSUE THREAD

**Issue by Sorontik** [topjohnwu/Magisk#1720]
Currently, MagiskManager forces the user to
first update the MagiskManager
and then (maybe) update Magisk.

So, with an outdated Manager, the only thing one can do, is to update the Manager

In Situations, where the new Manager-Version is no longer compatible with the old Magisk-Version, this leads to an incompatible System.

It would be useful to 
a) give user the option (maybe 'hidden' in Settings or sth like that) to update Magisk (or install a custom version) without forcing the user to first update MagiskManager.

b) limit the updating capabilities, so that both, Manager and Magisk stay compatible.
So the Manager must not offer Versions that are incompatible to the currently installed Magisk Version. When all newer Versions of the Manager would be incompatible with the current Magisk-Version, these Versions should not be offered as updates (or at least not without a proper, BIG warning that this will break the setup). 
Additionally, in those cases, the Manager could offer to update Magisk despite being not totally up to date (it should update to the newest Magisk-Version that is still compatible with the running Manager)
The idea is to update Magisk and the manager alternately, so that the respective versions always remain compatible.

**Comment by topjohnwu** [comment]
Magisk Manager *ALWAYS* has to be upgraded first because new version of Magisk might require special support to upgrade existing devices, and that is only possible by upgrading the app

**Comment by Sorontik** [comment]
I understand the problem, but there has to be a possibility to limit the update to compatible versions!

I does not make sense to offer (and, in a way, advertise) updates on a running system, that knowingly render the system useless.

The workflow should be:
Update Manager to newest Version that is STILL COMPATIBLE with current Magisk Version
then update Magisk to the newest Version that ist compatible with current Manager

Then (again) update Manager to newest compatible Version
Then update Magisk

and repeating the process until both are up to date

**Comment by Sorontik** [comment]
So, what i'm suggesting is to offer a way for users to choose to which newer Version they want to update (especially if some of them are not compatible with the current Magisk or Manager)
