### ISSUE TITLE
su fails in terminal emulators using Magisk 19307

### ISSUE THREAD

**Issue by callihn** [topjohnwu/Magisk#1721]
Device: LG K7 LGMS330 5.1.1
Magisk v19.4-736729f5(19307) 
Device API level: 22

I have tested this with several terminal emulator apps and get the same result, I have also flashed Magisk back and forth from the last canary build 19306 to the current 19307, this issue only exists in the 19307 build.

```
u0_a61@m1:/ $ su
WARNING: linker: su: unused DT entry: type 0x6ffffef5 arg 0x1358
WARNING: linker: su: unused DT entry: type 0x6ffffffe arg 0x19cc
WARNING: linker: su: unused DT entry: type 0x6fffffff arg 0x2
u0_a61@m1:/ #
```
The only thing I could see that looked abnormal in the magisk log was a line that said write failed 32 broken pipe, I don't believe I'd seen that line before and after clearing the log it has not reappeared.

**Comment by topjohnwu** [comment]
Thanks for the report, fixed in the toolchain here: topjohnwu/FrankeNDK@c265e2860686213bc7bc26349bc8b249f55ffc8c
