### ISSUE TITLE
Unable to mount /system RW in Android Q

### ISSUE THREAD

**Issue by 1dopewrx** [topjohnwu/Magisk#1729]
I am unable to mount /system in Android Q on my Pixel 2 XL either in TWRP or through terminal/ADB. I've tried rooting through patching boot.img as well as traditional through TWRP and same result. A thread on XDA has people pointing towards it being a magisk problem. Could this be possible?

**Comment by topjohnwu** [comment]
If you are unable to mount system as rw in TWRP, then it is not a Magisk problem, but the new way Google is dealing with their system partitions

**Comment by Octal450** [comment]
Will this be fixed at some point? I'd like to be able to debloat my device.

I though the partition scheme was only modified on the Pixel 3 and not the older Pixels?

Kind Regards,
Josh

**Comment by 3c71** [comment]
From what I read, it appears that since Android 9, /system partition is actually in / partition.
Have you tried mount -o rw,remount / instead?

I tried on a Pie and a Q device, no luck on either of them. Tried on Android 6 with Magisk, same result whether I use / or /system !? Then went on a SuperSU device, all ok.

Any news on this?

**Comment by topjohnwu** [comment]
Android Q uses EXT4 dedup filesystem, which is not writable.
More info here: https://twitter.com/topjohnwu/status/1170404631865778177

**Comment by Jaapp-** [comment]
Just to add a datapoint, after disabling MagiskHide I could remount through adb with more progress, but it still didn't work:
```[libfs_mgr]dt_fstab: Using a specified mount point /system_root for system
[libfs_mgr]dt_fstab: Using a specified mount point /system_root for system
[libfs_mgr]dt_fstab: Using a specified mount point /system_root for system
[libfs_mgr]dt_fstab: Using a specified mount point /system_root for system
E failed to remount partition dev:/dev/block/platform/soc/c0c4000.sdhci/by-name/system mnt:/system_root: No such file or directory
/system/bin/remount exited with status 10
remount failed
```

Afterwards (previous step might or might not be necessary), running `adb remount -o rw,remount /` in a shell did work for me while `adb remount -o rw,remount /system` didn't.

**Comment by st4ycool** [comment]
Why you never mention that problems in faq? It takes so much time to discover by yourself

**Comment by plakat3** [comment]
Well then I don't see a point of rooting the phone. Wanted to change hosts file and this is one of the main reason for me to root it.

**Comment by fusionneur** [comment]
you can change hosts file systemlessly with adaway after you enable systemless hosts in magisk
