### ISSUE TITLE
Cannot change boot img to have custom kernel S10

### ISSUE THREAD

**Issue by msftsecurityteam** [topjohnwu/Magisk#1731]
This probably isn't the place for this question, but I am trying to build a custom kernel and boot it on an S10 (SM-G973F). I have already rooted my phone with Magisk, and just recently built the kernel. When I pulled the boot image off of the phone, I used the magiskboot utility to unpack the image and then used it again to perform the same hex patches as boot_patch.sh. I then repack'ed it into a boot.img and flashed to the BOOT partition. After the flash it booted fine, but I didn't notice any changes to my kernel uname. 

I know the boot.img doesn't have the ramdisk anymore, and those other changes, so does that mean I need to actually flash to the recovery partition instead?

**Comment by topjohnwu** [comment]
Yes, the kernel you're booting with Magisk is the one in recovery
