### ISSUE TITLE
Question about magisk ota tricks when in major Android version update

### ISSUE THREAD

**Issue by wrlssqi** [topjohnwu/Magisk#1736]
My question is that whether the ota tricks that magisk plays works correctly when in major Android version update (such as from pie to q). Recently I update from pie to q beta 5 through ota on pixel 2. After installed, I flash magisk 19.4 to second slot, then reboot. Then phone stuck at G loading screen. I have to flash factory image to boot normally.
您好，我想问一下magisk的ota功能在大版本升级时候是否还能正常工作。我把我的pixel2手机从pie通过ota的方式升级到了q beta 5，然后再ota安装完毕后，把magisk 19.4安装到了second slot，然后重启。结果手机卡在G界面无法进入系统。fastboot里刷入原版boot镜像后，直接变成无法启动的状态，报data corrupt错误。factory reset清除数据后才恢复正常。
非常感谢各位的解答！

**Comment by topjohnwu** [comment]
It should. The reason for data corruption have many different possibilities, most likely it is caused by non compatible Magisk modules
