### ISSUE TITLE
"Can't find target image" on WikoPulp

### ISSUE THREAD

**Issue by Sorontik** [topjohnwu/Magisk#1739]
Directly Installing Magisk fails with Message "! Unable to detect target Image"
On a Wiko Pulp running Android 5.1 (Kernel 3.10.72)
With Magisk 19.3 and Manager 7.3.2(224)

I'd rather not change to canary build as this would mean to fastboot-flash a new boot.img and thus wipe all data.
I can confirm though, that the problems still occur with the up-to-date scripts from this repo.
(I ran `find_boot_image` and its parts from /scripts/util_functions.sh manually in a root shell via adb, copied right out of this repo)

It would be nice to add this and I'd happily help and provide additional information that helps.

Here's what i found by now:
(guided by my understanding of your scripts)

All fstabs on the system:
```
/ #> find -iname '*fstab*' 
/system/etc/recovery.fstab
/sbin/.magisk/mirror/system/etc/recovery.fstab 
/fstab.mt6592
```

The first two are identical (surprise^^) and contain this:
```
# mount point	fstype		device			[device2]

/boot		emmc		boot
/cache		ext4		/dev/block/mmcblk0p4
/data		ext4		/dev/block/mmcblk0p5
/misc		emmc		misc
/recovery	emmc		recovery
/sdcard		vfat		/dev/block/mmcblk0p6
/system		ext4		/dev/block/mmcblk0p3
```

The latter one contains this:
```
# Android fstab file.
#<src>           <mnt_point>         <type>    <mnt_flags and options>                 <fs_mgr_flags>
# The filesystem that contains the filesystem checker binary (typically /system) cannot
# specify MF_CHECK, and must come before any filesystems that do specify MF_CHECK

/emmc@android     /system      ext4   ro						                wait
/emmc@usrdata   /data        ext4   noatime,nosuid,nodev,noauto_da_alloc,discard               wait,check,resize,encryptable=footer
/emmc@cache      /cache       ext4   noatime,nosuid,nodev,noauto_da_alloc,discard               wait,check
/emmc@protect_f   /protect_f   ext4   noatime,nosuid,nodev,noauto_da_alloc,commit=1,nodelalloc   wait,check,autoformat
/emmc@protect_s   /protect_s   ext4   noatime,nosuid,nodev,noauto_da_alloc,commit=1,nodelalloc   wait,check,autoformat
/devices/platform/mtk-msdc.0/mmc_host   auto      vfat      defaults        voldmanaged=sdcard0:emmc@fat,noemulatedsd
/devices/platform/mtk-msdc.1/mmc_host   auto      vfat      defaults        voldmanaged=sdcard1:auto
/devices/platform/mt_usb                auto      vfat      defaults        voldmanaged=usbotg:auto
```

Also, i found the following 'files', that might be interesting
`/dev/BOOT`  (character device)
`/dev/bootimg` (character device)
`/dev/block/mmcblk0boot0` (block device)
`/dev/block/mmcblk0boot1` (block device)
along with nine other block devices 
`/dev/block/mmcblk0p1` through `mmcblk0p9`

Please tell me, if you need additional information or 'guide' me to find the correct location so i can find it manually and create a patch for the script.

**Comment by topjohnwu** [comment]
Your fstab does not contain the info where the boot block device is.
And also, your device's `/dev` does not create symlinks with the proper names. It is impossible for any script possible to detect where your boot image partition is.

Also, fastboot flash boot images does NOT wipe your data. You can upgrade your device using the boot image patch method all the time

**Comment by Sorontik** [comment]
unfortunately i can't since the system locks the bootloader after one reboot - so each time i want to flash a new boot image, i need to unlock the booloader first, wich in turn does wipe all data
