### ISSUE TITLE
Modules lost after reboot [Galaxy Tab 3 10.1][LineageOS 14.1]

### ISSUE THREAD

**Issue by Crashdummyy** [topjohnwu/Magisk#174]
I did a fresh install of LineageOS 14.1 ( tried Cyanogenmod 13 as well ) and installed magisk afterwards.
Whenever I try to install a Module I can see it in the Magisk Manager but it disappears after reboot.

`** Magisk post-fs mode running...
** Magisk post-fs-data mode running...
/data/magisk_merge.img found
/data/magisk.img found, attempt to merge
Expanding /data/magisk.img to 32M...
/dev/block/loop0 /data/magisk.img
/dev/block/loop1 /data/magisk_merge.img
Merging: SonyFramework
Merge complete
* Running post-fs-data.d
* Loading core props
* Preparing modules
* Stage 1: Mount system and vendor mirrors
* Stage 2: Mount dummy skeletons
* Stage 3: Mount module items
* Stage 4: Execute module scripts
* Stage 5: Mount mirrored items back to dummy
** Magisk late_start service mode running...
* Enabling systemless hosts file support
* Enabling BusyBox
* Linking binaries to /sbin
* Starting MagiskSU
* Running service.d
* Starting MagiskHide
MagiskHide: Moving and re-linking /sbin binaries
MagiskHide: Removing dangerous read-only system props
MagiskHide: resetprop by nkk71 & topjohnwu
Initializing...
Modify data structure: 'ro.debuggable'='0'
Existing property: 'ro.debuggable'='1'
Recheck property: 'ro.debuggable'='0'
Done!
MagiskHide: Killing com.google.android.gms.unstable
MagiskHide: Starting MagiskHide daemon
MagiskHide: Update process/package list:
MagiskHide: [com.google.android.gms.unstable]
Zygote(0) ns=mnt:[4026532703] 
MagiskHide: com.google.android.gms.unstable(PID=4361 ns=mnt:[4026532764])
MagiskHide: Permissive detected
MagiskHide: Calling magiskpolicy for pseudo enforce mode
MagiskHide: Unmounted (/sbin)
MagiskHide: Unmounted (/system/xbin)
MagiskHide: Unmounted (/magisk)
MagiskHide: Unmounted (/system/etc/hosts)`

**Comment by Didgeridoohan** [comment]
Try installing through recovery instead.

**Comment by Crashdummyy** [comment]
I did install it through recovery (twrp ) i'm updating twrp to 3.0.2 right now and then i will try it again

**Comment by Didgeridoohan** [comment]
Your log shows an installation of Sony Framework through the Manager.

**Comment by Crashdummyy** [comment]
Yeah thats the Module I want to install.
Magisk itself appears to work :/

**Comment by Didgeridoohan** [comment]
I meant: install the module through recovery... Have you tried that?

**Comment by Crashdummyy** [comment]
I tried to install it through recovery right now, here it results in a bootloop :/

**Comment by Crashdummyy** [comment]
Any news on this ? Still can't get any module to work

**Comment by topjohnwu** [comment]
That's most likely a module issue IMO.

**Comment by Crashdummyy** [comment]
Fixed with v13.1
