### ISSUE TITLE
Make magisk patch both slots

### ISSUE THREAD

**Issue by mauronofrio** [topjohnwu/Magisk#1740]
Actually i'm maintaining a bit of TWRPs for some A/B devices (OnePlus 7, OnePlus 7 Pro, OnePlus 6, OnePlus 6T and Zenfone 6) and on all these devices when you flash a ROM update using the TWRP you need to flash again the TWRP installer and you have to reboot in TWRP before flash Magisk again, this because Magisk is flashed in the active slot. This normally shouldn't be a big problem but sometimes (usually when the security patch changes) after flashed the new update and TWRP installer, when you reboot again in TWRP, this is not able to decrypt /data so users can't flash the magisk zip and they need of a Pc. Can be possible make Magisk patches both slots? In this way there would be fewer problems for users and especially fewer requests for help in the various threads.

**Comment by topjohnwu** [comment]
I personally do not agree with the way current custom ROM is flashing to the other slot, but I digress. I will never install Magisk to the both slot since it is a violation of the very design of A/B slots

**Comment by mauronofrio** [comment]
We don't decide where to flash it, update_engine automatically flash payload roms on the inactive slot because it's how update works on the A/B devices. A solution can be also a magisk version that patch the inactive slot. Or better an addon zip that place a file in the tmp folder, so magisk check if that file is there it patches the inactive slot, if it is not there magisk will patch the active slot. This should be an easy way to bypass the problem, letting the user choose where to install the zip.

**Comment by mauronofrio** [comment]
@topjohnwu
I want to explain better the second option that i think it's the better solution (because over time it would need less maintenance):
You should create a new zip that creates a file called (for example) activeslot or inactiveslot in /tmp; if in /tmp there are not a activeslot or inactiveslot automatically the zip will create a file called inactiveslot. If a file of these 2 is already there it will be deleted and the opposite file will be created. Now in the magisk zip you should add an check of these files: if there are not activeslot or inactiveslot file magisk will patch the active slot; if /tmp/activeslot file exist magisk will patch the active slot; if /tmp/inactiveslot magisk will patch the inactive slot. Teoriacally the activeslot file can also be excluded from all the processes, if /tmp/inactiveslot file exist magisk will patch the inactive slot otherwise magisk will patch the active slot.
I know it is an annoying and apparently useless thing, but the problem is there and by doing so it would be solved.

If you want i can do all and then make a pull request.
