### ISSUE TITLE
HOW TO MAGISK Q BETA 5 PIXEL 3

### ISSUE THREAD

**Issue by ETJAKEOC** [topjohnwu/Magisk#1741]
So I was hoping to make this post to help others with my experience with my struggle of rooting the Android Q 5 beta on the Pixel 3.

I had tried every option available from topjohnwu's versions of Magisk, but unfortunately none of the methods worked for me; (stable, canary). I didn't want to risk trying to factory wipe and test with a fresh install to see if it fixed the issue, and if you don't want to take that route then I suggest you use IanMacD's latest canary version of Magisk, as this application has worked right off the bat.

Not sure what changes he made to allow this to happen where the regular Magisk failed, but I wanted to point out that this method works to all of you who are also struggling with rooting the Android Q beta 5 on your Pixel 3's.

The IanMacD canary Magisk can be found at: https://github.com/ianmacd/MagiskBuilds/tree/testing

I'm not trying to make anyone think that one developer's version of Magisk is better than the other, I'm just hoping that this information may help other users, and possibly Mr. Wu if he can see what differences make this utilizable on certain devices when the original version won't work, but that's why we make forks right? 😆 

I hope this post helps other users out, enjoy!

**Comment by topjohnwu** [comment]
@ETJAKEOC @ianmacd's version is just building the upstream of Magisk, where I am still not comfortable of releasing it to the public
