### ISSUE TITLE
假如要修改magisk模块的文件夹路径是不是修改zip里面的addon.d.sh就可以了？

### ISSUE THREAD

**Issue by seraph758** [topjohnwu/Magisk#1742]
我不知道中文能不能看懂，我就说下我的问题。因为我的手机目前测试版android q没有合适的twrp,所以我就用修改boot的办法刷入面具。但是因为我不小心安装了一个不兼容的模块，导致现在卡在开机的界面。恢复原版boot 就可以开机，但是这样就没有root，没办法删掉模块文件，用修改的boot就卡开机。我的思路是重新制作一个boot，把里面的路径从data/adb修改成别的，这样开机就不加载之前的模块，就没问题了。不知道我这个思路可行吗，我在两个zip文件夹里发现两个脚本里面涉及到data/adb目录，不知道是不是都要修改

**Comment by topjohnwu** [comment]
開機得時候，連進 ADB 然後手動把 module 刪掉
```
adb shell
su

cd /sbin/.magisk/modules
rm -rf <module_id>
reboot
```

**Comment by seraph758** [comment]
su的時候不是也需要在手機上給他權限嗎，現在卡在開機畫面，都進不去電腦，也能用這個辦法嗎

**Comment by seraph758** [comment]
> 開機得時候，連進 ADB 然後手動把 module 刪掉
> 
> ```
> adb shell
> su
> 
> cd /sbin/.magisk/modules
> rm -rf <module_id>
> reboot
> ```
su的時候不是也需要在手機上給他權限嗎，現在卡在開機畫面，都進不去電腦，也能用這個辦法嗎
