### ISSUE TITLE
Disable check update & causing device freeze on opening app(s)

### ISSUE THREAD

**Issue by zputnyq** [topjohnwu/Magisk#1746]
Hi @topjohnwu 
I have used magisk since v16, it's great. However there are 2 problems which I face.

Disable check update is sometimes failed, it sometimes keeps checking when there is a network connection. While without network connection (data / wifi), its checking never ends.

About the freeze, this problem is hard to be reproduced, but it seems when device has been used for longer time, it appears.
I don't mean to compare but with SuperSu there is no freeze problem. My guess it is magisk memory usage, probably u can do something for this.

Thank you
I really appreciate it

Xperia M4 stock 6.0.1 & stock kernel
Magisk stable v19.3 with magisk manager 7.3.2

**Comment by topjohnwu** [comment]
First issue: #1658 
Second issue: can't fix without details

**Comment by zputnyq** [comment]
@topjohnwu 
My apology.
I'm confused about the details should I post , since it seems randomly happen.
However, so far I only have one sure detail.
The freeze happens after I clear my device using SD maid.
With other root (SuperSU) it's fine.
