### ISSUE TITLE
EMUI9.1电话短信闪退

### ISSUE THREAD

**Issue by 0x10000** [topjohnwu/Magisk#1747]
Mate 10 9.1.0.321 （加入了EROFS,方舟编译器的版本）

进入系统后电话短信闪退，卸载Magisk后打开正常

**Comment by piggy0915** [comment]
试试
adb shell
su
rm /data/user/0/com.android.providers.telephony/databases/*
rm /data/user/0/com.android.providers.contacts/databases/*

**Comment by cliffmanw** [comment]
> 试试 adb shell su rm /data/user/0/com.android.providers.telephony/databases/* rm /data/user/0/com.android.providers.contacts/databases/*

yes, it works!
