### ISSUE TITLE
Keep rooted after Lineage upgrade

### ISSUE THREAD

**Issue by matlink** [topjohnwu/Magisk#175]
Is it possible with magisk, like SuperSU, to patch the system not to be forced to flash the magisk zip again after upgrading Lineage?

**Comment by TheComputerGuy96** [comment]
@matlink Maybe

**Comment by DavidGitta** [comment]
Yes it is.

**Comment by matlink** [comment]
'Yes it is' and 'Kinda'. Can't be more precise :D

**Comment by salevdns** [comment]
Yes sorry I wanted to test it before going more into detail. I made a addon.d script inspired by osm0sis flashafterupdate script that flashes the newest Magisk installer zip located in /sdcard/MagiskManager whenever an system update gets installed.
Here I made a zip to flash in recovery:
[Magisk OTA persistence-v1.zip](https://github.com/topjohnwu/Magisk/files/1048290/Magisk.OTA.persistence-v1.zip)
Actually I think it would be great if a similar functionally would be implemented in Magisk by default.

**Comment by osm0sis** [comment]
You could also just direct Magisk Manager to download the zip to /sdcard/FlashAfterUpdate and cut out the middle man. :)

**Comment by LinkofHyrule89** [comment]
I would really love for this to be a feature natively added to magisk!

**Comment by salevdns** [comment]
Good news:
An excellent addon.d solution has been implemented in the latest [Magisk [BETA]](https://forum.xda-developers.com/apps/magisk/beta-magisk-v13-0-0980cb6-t3618589) v13.0(54e6a79). So from here on Magisk will survive updates by default (as long as the rom supports addon.d scripts of course).
@matlink issue can be closed.
@topjohnwu thanks for your amazing work!

**Comment by LinkofHyrule89** [comment]
Thanks a lot!

**Comment by matlink** [comment]
I'll try that !
