### ISSUE TITLE
[Question?] Will This Work On...

### ISSUE THREAD

**Issue by gatekeeper1122** [topjohnwu/Magisk#1751]
Will magisk work on the "Samsung Tab E 8.0 T377WVLU3ARG1" i dont know if i should try it or not but its like the only thing i would run with a rooted device i own them other applications that dont do what magisk does to hide my device from saftey net are not worth my time to have my device rooted if it does work with my device then it would be really big upgrade from my motorla G4 Plus thats rooted with magisk if it doesnt then i guess ill stick with the official release until i can find another tablet that can be rooted with magisk - if there someone out there that does any development with android & getting magisk to work on anything im willing to help get it working with my device

**Comment by topjohnwu** [comment]
Github issues is not the place to ask for support.
