### ISSUE TITLE
GitHub API limitation

### ISSUE THREAD

**Issue by RikkaW** [topjohnwu/Magisk#1753]
Magisk Manager uses GitHub API without authentication. Unauthorized calls are limited to 60 requests per hour per IP (https://developer.github.com/v3/#rate-limiting). The limitation would be triggered easily.

The simplest solution is to use Basic authentication.

Also, it needs to add somethings to inform users if the request is unsuccessful.

**Comment by DenyDarko** [comment]
" Authenticated requests are associated with the authenticated user, regardless of whether Basic Authentication or an OAuth token was used. "

I don't see how this won't hit the limit within seconds.

Unless everyone gets his own credentials

**Comment by topjohnwu** [comment]
@RikkaW the old implementation accidentally deletes the etag key, which is a bug I recently fixed.

In the latest canary builds, the app will properly cache the etag key and send it along with the request so if nothing is changed on the server side, the API will not response anything and the rate limit will not be counted.

For more info check the Github docs: https://developer.github.com/v3/#conditional-requests
