### ISSUE TITLE
Magisk Manager Uninstall does not work

### ISSUE THREAD

**Issue by sovanyio** [topjohnwu/Magisk#1754]
Magisk 19.3
Manager: 7.3.2
Phone: Pixel 2 XL, August 2019

I haven't been able to apply magisk through the OTA flow ever. When trying to uninstall pre-OTA, I get the toast message that the stock backup is not found.
Upon `adb shell` into my device, I see several older backups under `/data` that are out of date. I ultimately found the correct stock backup at the manager's hidden obfuscated path under `install/`.

When I poke around the source here, and follow the code flow through the error message, starting here: https://github.com/topjohnwu/Magisk/blob/0c17ea5755171f951c545cb3605919e574110182/app/src/main/java/com/topjohnwu/magisk/view/dialogs/UninstallDialog.kt I see that it calls `restore_imgs` 
 here: https://github.com/topjohnwu/Magisk/blob/415ff23be5872f537d9ad59b4055abe3ddf3e280/app/src/main/res/raw/utils.sh

```
local SHA1=`grep_prop SHA1 /sbin/.magisk/config`
  [ -z $SHA1 ] && local SHA1=`cat /.backup/.sha1`
```
Running the first line fails for me, and the file referred in the second line does not exist.

I'm not seeing any relevant output in the logs either.

**Comment by topjohnwu** [comment]
If there is anything missing for uninstallation, it is caused by an incorrect configuration somewhere in the process. Backing up is extremely tricky, and there are 398209 possible ways to mess up the uninstallation process. Unfortunately the easiest way to uninstall Magisk in your case is to just restore the boot image via fastboot.

**Comment by sovanyio** [comment]
So there is no way to support the OTA compatible installation if the fastboot method was used to install originally?
