### ISSUE TITLE
Pixel 3a flags Magisk as 'uninstalled' after update (to MagiskManager 7.3.2) + boot loop on all subsequent Magisk patched boot imgs (sargo-pq3b.190801.002 and sargo-pd2a.190115.032)

### ISSUE THREAD

**Issue by andrewtheiss** [topjohnwu/Magisk#1762]
Cause:  Pixel 3a has been rooted since May 14 using current Magisk and MagiskManager available at that time (19.1, and 7.1.2 (208)).  On Aug 2 I opted to 'Hide Magisk' which worked without issue. Today I updated MagiskManager and after update Magisk went from 'Installed' to 'Not Installed'.  

Attempted Solution #1: Most probable fix was to flash the boot.img which I still have on my laptop from the original root.  After patching sargo-pd2a.190115.032 boot.img succeeded with MagiskManger.  fastboot flash command ran without error.  On boot, bootloop occurred. 

Attempted Solution #2: Download latest factory image (sargo-pg3b.190801.002), flash-all.bat for entire phone (windows, i know..) install latest MagiskManager, patch latest boot.img, fastboot flash image, bootloop again.  

Attempted Sol #3: Switch active partition and try same steps (with sargo-pg3b.190801.002), bootloop was once again the end result.

Other Deets: Tried install through TWRP.  TWRP throws error on install of MagiskManager 'sig verification failed' (possibly unrelated but I figured more detailed account is better).  Also I've installed Magisk + MagiskManager on Pixels 1, XL, 2, 3, and 3a for many a friend so I'm hopefully not too ignorant on what I'm doing and can provide additional details should you need!

**Comment by topjohnwu** [comment]
Pixel devices are definitely always fully supported as it is always the first device I use to test things on. Github issues are not for user support.
