### ISSUE TITLE
Can you provide a development tutorial for the magics module?

### ISSUE THREAD

**Issue by TealerLinkGuo** [topjohnwu/Magisk#1763]
Magisk is an excellent software, I hope you can provide module development tutorials or samples for novice developers.

**Comment by Didgeridoohan** [comment]
Making modules is dead easy, especially with the documentation that's already available:
https://topjohnwu.github.io/Magisk/

And the module installer template is very detailed on what's needed and possible.

Did you even look for any instructions or documentation before opening this?

You can close this issue now, to save John the effort of having to do it himself.
