### ISSUE TITLE
Car2go app (com.car2go) app detects root

### ISSUE THREAD

**Issue by Gro-Tsen** [topjohnwu/Magisk#1768]
The Car2go car rental app (com.car2go, available from Google Play) refuses to perform some tasks (validating user's driver license) on a rooted device. (The error message is obscure, "we're unable to validate your driver's license on this phone for technical reasons", but the app writes to a log file a line saying "NETVERIFY Error: Device is rooted", so this is certainly the problem.)

I've tried doing the following:

* remove all superuser permissions and disable root access before even installing the app,

* use Magisk hide on the app as soon as it is installed (before running it),

* hide Magisk manager under random name,

* disable USB debugging, disable developer options, chmod 440 /proc/net/unix (someone suggested this).

Despite all this, the app still refuses to work and the line "NETVERIFY Error: Device is rooted" is still being recorded.

This is on a Google (LGE) Nexus 5 (“hammerhead”) running LineageOS 14.1 (Android 7.1.2 Nougat) with the latest build (20190126) before LineageOS discontinued its support for this device. The com.car2go app version is 3.48.0.

I have no idea how to debug any further.

**Comment by Gro-Tsen** [comment]
Forgot to add: this was with versions 19.3 (19300) of Magisk and 7.3.2 (224) of the Magisk manager, which are the latest as of now. Also, the SafetyNet check in Magisk manager passed (ctsProfile: true, basicIntegrity: true).

**Comment by KieronQuinn** [comment]
#1152

**Comment by malbo192** [comment]
having same problem, got any further with this?

**Comment by KieronQuinn** [comment]
@malbo192 I suggest you read the previously linked #1152

**Comment by Gro-Tsen** [comment]
> having same problem, got any further with this?

I did not manage to get Car2go to work on my rooted phone (using Magisk or anything else), I resorted to buying the cheapest Android phone I could and left it unrooted. However, there are two things which might be worth mentioning to others in my situation:

* Car2go cares about the phone being rooted only for the purpose of driver license validation: once this step is passed, it will happily run on a rooted phone. (So if you can borrow someone else's phone for this, you can use the app on your own phone later.)

* The underlying culprit is a framework known as “Jumio”: see [here](https://github.com/Jumio/mobile-sdk-android). This may be worth mentioning because it means it probably affects more than just Car2go. Alas, I have no idea how Jumio works or how it detects root, so I can't say any more.

**Comment by Gro-Tsen** [comment]
@KieronQuinn I don't know what you're trying to achieve by (repeatedly) linking to issue #1152 which says similar issues will be ignored.

I can quite well understand, and respect, the devs' reasons for not wanting to look into a zillion different apps and trying to work around the idiosyncrasies of each of them.

But submitting an issue saying that “application foobar does not work” serves another useful function, namely, to make that fact discoverable using search engines. Specifically, the point of *this* bug report is not to get the issue fixed (I understand nobody has the time or the will to work upon it) but to make sure that googling “Car2go Magisk” leads here and avoids any one losing their time by trying to use Magisk to get Car2go to work on a rooted Android phone (or at least one with LineageOS).  Maybe eventually someone with the time and the will to understand what is going on will do so, and maybe the information contained in the thread will be useful.  Or maybe not.  But in the mean time, the mere existence of the bug report is useful for discoverability, and this was my purpose in creating it.

What you're trying to do by linking to an issue which provides no help of any sort except saying “won't fix”, however, I fail to discern.  I think everyone here completely understands that the issue will likely never be fixed and I don't see the point of hammering the fact.

**Comment by KieronQuinn** [comment]
@Gro-Tsen

Linking to #1152 provides the main thread for talking about what is causing these issues, it is not just a "won't fix". You've clearly not read the thread there either if you think it is. 

By talking about the issues there rather than here, you can help with the possibility of fixing the issue, here nobody will see it.
