### ISSUE TITLE
Magisk Manager periodically crashing on LG G3

### ISSUE THREAD

**Issue by Senliast** [topjohnwu/Magisk#1771]
Magisk Manager is periodically force closes (even if not open) on my device,
i am not doing something specific, it just happens random. Also tried reinstalling
the OS, installing latest stable and canary version, doesnt help.
Here is log: https://justpaste.it/5hnbz
Crash happens at 01:41:37
Repackaged Magisk Manager name: com.B.zEPc.QV.MWFI4f

Device: LG G3 D855
ROM: LineageOS 15.1
No Magisk modules, no Xposed / any system mods installed.

**Comment by topjohnwu** [comment]
Unfortunately, your logs does not contain any relevant info.
Please check the canary branch and see if that fixes your issue. If issue still persist, please use the debug version of the canary build and upload full logs.
