### ISSUE TITLE
Cannot complete flashing in Odin for SM-A505F

### ISSUE THREAD

**Issue by bilogic** [topjohnwu/Magisk#1772]
Hi,

I have tried several versions of Magisk to patch my AP file. However, these ```magisk_patched.tar``` either 

1. are not able to complete patching (yes my Odin v3.13's progress bar stops growing and there are no errors on the phone)
2. in other cases, Odin closes, no errors, nothing, with a half complete progress bar on the phone
3. there is only 1 instance of successful Odin flashing, but after I ```recover``` to factory reset, it shows the ```SAMSUNG``` outline, goes into ```Starting Android...``` and then goes into a reboot loop

My A50 version is ```A505FDDU2ASF2_A505FOLM2ASF2_XSP```, any idea how can I track down what the issue might be? Thank you.

**Comment by topjohnwu** [comment]
Use ADB to do file transfers. It is known that MTP can corrupt large files like AP firmwares

**Comment by bilogic** [comment]
It worked! I wished I did not missed that note in your ```install.md```, perhaps warn others to use ```ADB``` and avoid ```MTP``` unless they know what they are doing? Thank you!

**Comment by bilogic** [comment]
Not sure if this is the most appropriate place to ask, but any known methods on how to have TWRP and Magisk co-exists on the A50?

I was able to flash a stand alone AP file via ODIN to get TWRP, but doing the ```(OEM Recovery Key Combo) → (Splash screen) → (Release all buttons)``` could not get me into Magisk, it always got me into TWRP (I'm just trying to save some time here, if it is a no, I will stop exploring).

Thank you.

**Comment by vimikr** [comment]
Hi! 
Cannot Load My Samsung Galaxy A50 after TWRP-3.3.1-2_zvox.tar 
It Always working only on this screen. No way to reboot it. 
<a href="https://fastpic.ru/view/90/2019/0907/_a0892e62ccc6c24055e6c2e35215741b.jpg.html" target="_blank"><img src="https://i90.fastpic.ru/thumb/2019/0907/1b/_a0892e62ccc6c24055e6c2e35215741b.jpeg" border="0"></a>

Can You help me?

**Comment by bilogic** [comment]
@vimikr
1. Do the ODIN flash again
2. You must do wipe/factory reset before attempting to boot into TWRP
3. Boot into TWRP

You probably did not do step 2 and went from step 1 to 3

**Comment by vimikr** [comment]
Thank You! 
But How I can do this?

[https://youtu.be/01qBd0dMnwE](url)

[https://youtu.be/m2NWlGUD4Lc](url)


Can You help me with any recomendations/apps?

**Comment by bilogic** [comment]
@vimikr which step are you stuck, 1, 2 or 3?

**Comment by bilogic** [comment]
1. Do the ODIN flash again https://www.hardreset.info/devices/samsung/samsung-galaxy-a50/download-mode/

**Comment by vimikr** [comment]
> 
> 
> @vimikr which step are you stuck, 1, 2 or 3?

It was the 2nd step, but after Odin flash I cannot open Bootloader

**Comment by bilogic** [comment]
2. You must do wipe/factory reset before attempting to boot into TWRP for the 1st time
https://www.naldotech.com/galaxy-a50-recovery

**Comment by vimikr** [comment]
> 
> 
>     1. Do the ODIN flash again https://www.hardreset.info/devices/samsung/samsung-galaxy-a50/download-mode/

I know this way, but if you will see this video, I cannot open DownloadMode, Odin can't see the Phone

**Comment by bilogic** [comment]
Please plug in the USB cable and press the buttons *exactly*. If your TWRP is stuck, you must start from step 1 again.

**Comment by vimikr** [comment]
> 
> 
> Please plug in the USB cable and press the buttons _exactly_. If your TWRP is stuck, you must start from step 1 again.

I Did it all _Exactly_... A lot of times... But cannot enter Download Mode

https://youtu.be/cp9ruh_qGv8

What are the ways to Download or Wipe Phone? Probably with SDCard?

Its totally new one. Yesterday I got it. Without any additional or personal information.

**Comment by bilogic** [comment]
Press ```+``` and ```power``` until you enter Android Recovery, select ```Reboot to bootloader```
I don't think the instructions mentioned to unplug and replug the cable... :)

**Comment by vimikr** [comment]
> 
> 
> Press `+` and `power` until you enter Android Recovery, select `Reboot to bootloader`
> I don't think the instructions mentioned to unplug and replug the cable... :)

Doesn't work (((
+ and Power --- No changes - no reboot, only screen with Teamwin (((
It reboot only with - and Power. Its only "working" combination.

**Comment by bilogic** [comment]
Press all 3 buttons until it reboots, then + and power
