### ISSUE TITLE
reopen: Bootloop to Recovery - Incompatible With System-As-Root Without Ramdisk

### ISSUE THREAD

**Issue by RedCriterion** [topjohnwu/Magisk#1773]
This is a request to reopen: 
#729 
#980
#1439 

The Issues (which are the same and got prematurely closed) did not get fixed!
I tried the newest 19.3 today and it still is the same. 

Please, please, look into it.
I'm thanking you in advance.

**Comment by topjohnwu** [comment]
#1674
