### ISSUE TITLE
Doesn't work with A only system-as-root on Nokia 1 Plus

### ISSUE THREAD

**Issue by S190762** [topjohnwu/Magisk#1775]
Unable to get this to work at all on a Nokia 1 Plus. There is no TWRP recovery for this device, I have tried compiling my own but only the stock recovery boots, so my only option is to patch the boot.img. 

The default boot.img contains only the kernel and no ramdisk. The device is running Android 9.0 Pie GO Edition. There is no treble support or A/B partitions, just A partition. The device flashes the stock recovery on every boot. 

I have tired patching the boot.img with the canary build, the debug build, 17.3 and other versions. I have also tried the system-as-root without ramdisk version.

Magisk correctly produces a boot.img with a small ramdisk. Magisk Manager however cannot detect magisk at all, I have browsed the file system with mtk-su root, and there is no signs of magisk after flashing the boot.img. I have also tried patching the recovery.img, still no sign of magisk. Using fastboot boot magisk_patched.img, the same thing happens. Magisk cannot be detected.

I have tried flashing the boot.img with SP Flash Tool and Fastboot.

**Comment by topjohnwu** [comment]
#1674

**Comment by S190762** [comment]
Used the latest Magisk from https://github.com/ianmacd/MagiskBuilds 

Used Magisk to patch recovery.img, flashed magisk_patched.img to recovery then held down Volume Up + Power until the phone booted. Loading magisk manager then said Magisk Installed and used Direct Install.

Magisk is now installed and works perfectly. Version installed is "19.4-736729f5" SafetyNet also passes.

**Comment by greenmns** [comment]
i have you issue 
i want root nokia 1 plus android pie but i did several method but none of them dont work
do you can root nokia 1 plus?

**Comment by bell18-web** [comment]
Nokia 1? 
    On Sunday, February 23, 2020, 7:24:52 PM GMT+8, greenmns <notifications@github.com> wrote:  
 
 
i have you issue
i want root nokia 1 plus android pie but i did several method but none of them dont work
do you can root nokia 1 plus?

**Comment by greenmns** [comment]
nokia 1 plus
