### ISSUE TITLE
Unable to repack boot image!

### ISSUE THREAD

**Issue by dubcusb** [topjohnwu/Magisk#1778]
Hi, I'm trying to install Magisk by patching a boot.img I got from a zipped OTA. I'm getting the following error:
![screenshot](https://user-images.githubusercontent.com/21978144/63065885-d2797f00-bed5-11e9-9679-b703728bfdf9.png)
Log: [log.txt](https://github.com/topjohnwu/Magisk/files/3503896/log.txt)
What is the cause of this error?

**Comment by alexa-v2** [comment]
Wow

Error #1: it's using 32bit busybox and failing. Guessing you're one of the few devices that's armeabi-v7a running 64bit OS

Error #2: Segmentation fault, possibly caused by error #1

**Comment by topjohnwu** [comment]
@dubcusb please upload your boot image as @osm0sis said

**Comment by osm0sis** [comment]
It's because Huawei has added some data in the header at decimal offset 1632 (where recovery_dtbo info is stored on newer devices): `Cairo-L23C469B125_65583_181210_SIGN`

We'll have to add some protections against such nonsense to magiskboot and unpackbootimg. :+1:

**Comment by osm0sis** [comment]
#1848 should fix this.
