### ISSUE TITLE
With repacked manager, the regular named manager appears after each boot

### ISSUE THREAD

**Issue by micw** [topjohnwu/Magisk#1779]
Hello,
I have repacked magisk manager to workaround a stupid check in my banking app. That works fine - it seems that the app looks for the original APK name.
The problem I have is that after each reboot, a original named manager appears in addition to the repackaged one. I have to remove this one manually after each reboot, otherwise the banking software detects magisk.

**Comment by topjohnwu** [comment]
This should be resolved in the latest canary Magisk Manager

**Comment by micw** [comment]
Does this mean, the next stable update will fix it?
