### ISSUE TITLE
Possible incomplete SELinux integration.

### ISSUE THREAD

**Issue by screwer** [topjohnwu/Magisk#1780]
Phone: Samsung Galaxy S7
Original firmware: G930FXXU3ERJE (Oreo Nov-2018)
Installed firmware: G930FXXU1DQG1 (Nougat, Jul-2017).
OEM unlocked.
Magisk installed via TWRP.

Shell output:
> herolte:/ $ su
> /system/bin/sh: su: can't execute: Permission denied

Logcat output:
> 04-25 13:20:38.670  3093  3093 E audit   : type=1400 audit(1556187638.659:256): avc:  denied  { execute } for  pid=5119 comm="sh" name="magisk" dev="tmpfs" ino=4275 scontext=u:r:shell:s0 tcontext=u:object_r:tmpfs:s0 tclass=file permissive=0 SEPF_SECMOBILE_7.0_0009
> 04-25 13:20:38.671  3093  3093 E audit   : type=1300 audit(1556187638.659:256): arch=c00000b7 syscall=48 success=no exit=-13 a0=ffffff9c a1=7d39a301e8 a2=1 a3=0 items=0 ppid=3303 pid=5119 auid=4294967295 uid=2000 gid=2000 euid=2000 suid=2000 fsuid=2000 egid=2000 sgid=2000 fsgid=2000 tty=pts0 ses=4294967295 comm="sh" exe="/system/bin/sh" subj=u:r:shell:s0 key=(null)
> 04-25 13:20:38.671  3657  3770 D SecurityLogAgent:SEDenialService: Got Modify Event and sending Denial Intent for audit.log / /system/bin/sh -
> 04-25 13:20:38.671  3657  3770 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:906 com.android.server.SEDenialService$AuditFileObserver.onEvent:84 android.os.FileObserver$ObserverThread.onEvent:122 android.os.FileObserver$ObserverThread.observe:-2 android.os.FileObserver$ObserverThread.run:85
> 04-25 13:20:38.671  3093  3093 E audit   : type=1327 audit(1556187638.659:256): proctitle=2F73797374656D2F62696E2F7368002D
> 04-25 13:20:38.671  3093  3093 E audit   : type=1320 audit(1556187638.659:256):
> 04-25 13:20:38.672  3657  3770 D SecurityLogAgent:SEDenialService: audit.ondenial set to 0 after sending samsung.intent.action.knox.DENIAL_NOTIFICATION intent
> 04-25 13:20:38.676  8105  8105 D SecurityLogAgent:  SeDenialReceiver : Intent received : samsung.intent.action.knox.DENIAL_NOTIFICATION

**Comment by topjohnwu** [comment]
The daemon was not properly start up, since it will fix all secontext when startup. In your case, the secontext is still `tmpfs`, not `rootfs`.
