### ISSUE TITLE
After several hours of standby Magisk loses root installation

### ISSUE THREAD

**Issue by NoobAndProud** [topjohnwu/Magisk#1782]
Maybe wrong forum but I'm unable to identify the right one.

I've noticed after several hours that Magisk Manager gives out a notification (I will provide the notification text if I am able to) pressing this notification reveals that Magisk "is not installed" I was panicked at first as I thought maybe the phone made an Upgrade/Update and restarted on its own. I reinstalled Magisk via TWRP (which stated it was a Magisk-patched system) and everything worked fine. I noticed it the second time and just restarted the phone (Op7Pro) and Magisk gets shown correctly and works till the next time it loses it.

Reproducing is difficult and I am willing to provide any necessary documentation and/or files needed to identify the cause.

Thanks in advance for the awesome work done on Magisk/Manager.

**Comment by topjohnwu** [comment]
This issue should be resolved in the latest canary
