### ISSUE TITLE
Line processing problem for module

### ISSUE THREAD

**Issue by grislux55** [topjohnwu/Magisk#1783]
I found that when the files in the magisk module use Windows line breaks, it will cause some intractable errors. For example, if the module.prop file newline is in Windows format, then this module can not be deleted correctly. I suggest that the module's newline characters be in Linux format before installing the module.

**Comment by grislux55** [comment]
I'm using magisk 19.3, magisk manager 7.3.2.

**Comment by Didgeridoohan** [comment]
Of course... That's even in the docs: https://topjohnwu.github.io/Magisk/guides.html#magisk-module-installer

What's the point of this issue? It's up to whomever makes the module to use the proper tools...
