### ISSUE TITLE
Cpu Overloaded

### ISSUE THREAD

**Issue by ShaAmin-cpu** [topjohnwu/Magisk#1784]
![Screenshot_2019-08-18-09-25-45-62_354d8a2f68bc9775ed3c9363dac7e362](https://user-images.githubusercontent.com/53892191/63459798-d592e300-c472-11e9-8764-21f909a0427e.png)
Magisk Consuming 93% of my Cpu
Device: Realme 1
Mediatek Helio P60
Ram 3Gb

**Comment by KieronQuinn** [comment]
Your screenshot doesn't actually show Magisk as running at 92% CPU, it shows init. I'm not sure what could be causing that, but it may not be Magisk. 

If it does turn out to be, one of the suggestions in the issue you commented on but don't seem to have tried is to disable Magisk Hide from Magisk Manager. See if that helps.

**Comment by ShaAmin-cpu** [comment]
@KieronQuinn I have Disabled Magisk Hide......Also No Module Installed....Same Problem

**Comment by topjohnwu** [comment]
Just as @KieronQuinn said, the one using CPU is `init`, not Magisk
