### ISSUE TITLE
Magisk leaks daemon socket into hide-space

### ISSUE THREAD

**Issue by meme** [topjohnwu/Magisk#1786]
```
sailfish:/ $ su
sailfish:/ # magiskhide exec /bin/sh
sailfish:/ # cat /proc/net/unix | awk '{ if (length($8) == 33) print $8 }'| awk -F@ '{ if (length($2)) print $2 }' | sort -u | head -n 1
d30138f2310a9fb9c54a3e0c21f58591
```

(used the replacement socket name in the example)

Although the socket _can_ be connected to, it cannot be fingerprinted as commands cannot be dispatched by binaries other than `magisk` (though this may be [ab]used by aggressive Magisk detection systems as it is unlikely to get false-positives)

**Comment by topjohnwu** [comment]
The latest Magisk canary already has variable length socket names.
