### ISSUE TITLE
Latest Manager canary version causing.... Interesting issues 

### ISSUE THREAD

**Issue by alexa-v2** [topjohnwu/Magisk#1788]
Alright

With the latest update to magisk manager play Store is crashing a few seconds after opening

"Well how tf is that magisk fault?" 

Good question, glad you aasked

Logs: https://del.dog/tafoborama

Of course when this started happening I went to the trusted logcat 

I found no logs directly from com.android.vending, instead every crash had something from magisk 
What interests me is the line starting
```
08-23 22:38:16.636 W/System.err(27761): android.content.pm.PackageManager$NameNotFoundException
```
This spams logcat every crash

Removed manager and poof, store stops crashing

So somehow latest canary manager is causing issues with play Store, as I can confirm before the update all was fine

**Comment by alexa-v2** [comment]
Caused similar issues with SwiftKey

Logs https://del.dog/inabovoyoy

**Comment by alexa-v2** [comment]
In fact, even trying stable still produces the same crashing

Never happened before today when I updated manager.....

**Comment by alexa-v2** [comment]
Hmm
Repackage the app include in the zip, and issue is back. It's something to do with the repackage process

I'm sorry if I misspelled anything Gboard is crashing every 2-3 sec right now, with same occurrence in logcat as before

Now officially confirmed on 3 ROMs (including stock OOS). Tried core only mode to no avail. Every single time it starts occuring right after I repackage Magisk Manager

**Comment by topjohnwu** [comment]
Sorry, but this does not make any sense at all.

**Comment by alexa-v2** [comment]
Oh wow thanks @topjohnwu

Every time I repackage manager, several apps start crashing in a loop, and pacakageManager can't find a component of magsik manager, according to logs. Said component not found exception spams the log on every crash with manager installed. Uninstall manager, the apps stop crashing and the exception isn't thrown. Reinstall after repackage and it starts getting thrown. Repackage in the first place and it gets thrown

I can't even install manager right now because Gboard will start crashing in a loop, along with play store

What more explanation is there to give?

**Comment by endolith** [comment]
I just updated Magisk and now Gboard is crashing every 2-3 seconds.  Ever find out the cause?  I wiped its data but it's still doing it.
