### ISSUE TITLE
Moto Z2 Play: Cannot boot after flashing Magisk

### ISSUE THREAD

**Issue by AnClark** [topjohnwu/Magisk#1789]
A total update from Lenovo updated the bootloader on my Moto Z2 Play. After this, any boot images must be signed and verified, or it will refuse to boot. 
So Magisk-patched boot image cannot boot, only stucking on bootloader screen.

**Comment by AnClark** [comment]
[UPDATE]
This device cannot directly flash Magisk zip. Must use Magisk Manager, switching on "Keep AVB 2.0/dm-verity", then patch boot image with it.

**Comment by AnClark** [comment]
No need to get logs.
This issue is easy to solve: add AVB checker & patcher into the `Magisk-v19.3.zip`.  Just like what Magisk Manager does.

**Comment by topjohnwu** [comment]
You found your own solution. Just patch your images with Magisk Manager

**Comment by AnClark** [comment]
Look at this. I also have a **suggestion**:

> This issue is easy to solve: add AVB checker & patcher into the Magisk-v19.3.zip. Just like what Magisk Manager does.
