### ISSUE TITLE
AdAway doesn't work with latest version

### ISSUE THREAD

**Issue by polsvoice** [topjohnwu/Magisk#1790]
I'm on a rooted OnePlus 6T, and I can't get AdAway to work. I've gone into Magisk and enabled "Systemless hosts" under Settings. It says "Added systemless hosts module", and I see it enabled when I look under "Modules".

I've tried rebooting. I've tried disabling and re-enabling ad-blocking. I've tried uninstalling and re-installing AdAway. Nothing works. I still see ads. I know I'm not supposed to be seeing ads, because I have another phone with AdAway installed on it, and the ads don't show up there.

The target hosts file is `/system/etc/hosts`. When I select "Open hosts file", I get 

`Error: Failed to load hosts file content.`

Then, I tap on "Open the hosts file", and try to open it with OI Notepad. I get an error "File not found", and the screen shows a document with only one word in it: error.

 - AdAway version: 4.2.8
 - Device: OnePlus 6T
 - Android version: OxygenOS 9.0.16
 - Root version: Magisk 19.3

However, [this bug report](https://github.com/AdAway/AdAway/issues/1140) mentions that downgrading Magisk to 17.3 allows AdAway to work again. I uninstalled 19.3 and installed 17.3 (and downgraded Magisk Manager to 6.1.0), and it works now.

So, it seems like something in more recent versions of Magisk has broken AdAway.

**Comment by AaronKeener** [comment]
It does, just go into preferences > target host file and set it to /system/etc/hosts

Works for my OnePlus 6T with Magisk Canary and AdAway

**Comment by topjohnwu** [comment]
This just doesn't make sense, closed

**Comment by AaronKeener** [comment]
Yeah, do you have activated systemless mode through AdAway before activating it through Magisk Manager?

**Comment by phoz0n** [comment]
Had the same behavior in adaway because I didnt have the systemless module in magisk. Fixed it by reflashing magisk.
