### ISSUE TITLE
SE Linux state changes after Magisk installation

### ISSUE THREAD

**Issue by baltbreeze** [topjohnwu/Magisk#1791]
I have the Galaxy S10 with G973FXXU3ASG8 firmware on it.
It's a developer phone and it has the SE Linux state "PERMISSIVE" out of the box.
However, after I have successfully installed Magisk using system-as-root guide, the SE Linux state changed to Enforcing. So a magisk installation procedure is causing the enforcing of the SE Linux context and that is not suitable in my case.
Is there any workaround to avoid that moment (any clues to edit in sources maybe)?

**Comment by baltbreeze** [comment]
Not this time.
I have a lot of audit logs about denied activities.
When I boot normally, without Magisk - I have no permission errors but I have no root.
When I boot to Magisk mode I have root but it's complete hell with SE Linux.
I've found one piece of code when the init is patched for SE Linux at 
MagiskInit::setup_rootfs() from /native/jni/init/rootfs.cpp.
The Topjohnwu's comment is appreciated..

**Comment by topjohnwu** [comment]
I don't know how Samsung developer phone works. Magisk assumes all devices are retail software running with full Android security.
If you want to enforce SELinux permissive on Samsung, in normal circumstances you have to modify the kernel (modify source code and compile your own custom kernel). You can try that route, that is the only suggestion I could give you.
