### ISSUE TITLE
i come back(About samsung new devices A60)

### ISSUE THREAD

**Issue by w2016561536** [topjohnwu/Magisk#1795]
I have tried to patch the boot image which get from odin package , but it seems magisk will put some new files in the ramdisk of boot image .But if you put there some files , it cannot boot. And Samsung a60 des not have third party twrp or cwm. How to install magisk?

PS: When I patch the boot image , I have decompress the lz4 file

**Comment by topjohnwu** [comment]
Patch the AP file, not the boot image. Please read the documentation for instructions.
