### ISSUE TITLE
Import properties from file using resetprop

### ISSUE THREAD

**Issue by localacct** [topjohnwu/Magisk#1796]
Hi

I understand that resetprop allows the import of properties using a file that contains the values. May I know what should the syntax of the properties and values be? I have tried the following but the properties do not seem to take the new values. I have tried colons, spaces, etc.

properties.txt (various combinations)

- gsm.version.baseband:xxxx
- gsm.version.baseband: xxxx
- gsm.version.baseband xxxx
- \[gsm.version.baseband]:xxxx
- \[gsm.version.baseband]:xxxx

I ran the commands in this manner (tried different combinations)
````
resetprop -v -n --file properties.txt
````

````
resetprop -v --file properties.txt
````

May I know what should be the proper way to write the properties.txt file?

**Comment by topjohnwu** [comment]
The syntax is the same as `build.prop`.
