### ISSUE TITLE
v19.4: su: cannot find manager when using hide / repack

### ISSUE THREAD

**Issue by micw** [topjohnwu/Magisk#1797]
Hello,

on 19.4 with hide enabled and repacked manager, I cannot get root via ADB shell. Su gives always "permission denied". Here's the log:

```
08-27 22:07:14.363   472 16181 D Magisk  : su: request from pid=[16170], client=[11]
08-27 22:07:14.363   472 16181 D Magisk  : su: request from uid=[2000]
08-27 22:07:14.363   472 16181 D Magisk  : magiskdb: query magiskhide=[1]
08-27 22:07:14.363   472 16181 D Magisk  : magiskdb: query root_access=[3]
08-27 22:07:14.364   472 16181 E Magisk  : su: cannot find manager
08-27 22:07:14.364   472 16181 W Magisk  : su: request rejected (2000)
```

Looks different than #882.

**Comment by micw** [comment]
It's also broken for all other apps that have not yet requested root.

**Comment by micw** [comment]
When I install a non-repackaged manager, su works and finds the manager. When I remove it, the issue reappears.

**Comment by topjohnwu** [comment]
Use the latest canary build. The database is not properly setup in your case.

**Comment by micw** [comment]
@topjohnwu I'm on latest, there is no update. Can you point out how to fix this?
Should a reinstall + a new repack do the job?
