### ISSUE TITLE
Snapchat detects root even with Magisk Hide & MagiskHide props

### ISSUE THREAD

**Issue by kurtextrem** [topjohnwu/Magisk#1798]
...and Snapchat bans for it, since a week.

Why this issue might be different than "Hide doesn't work" (#1152): It detect roots even inside the app Island (outside of Island too), which creates and manages a work profile. As I did not install Magisk in Island, it should not be able to detect root, as there is no root available inside Island. So somehow Snapchat is either escaping Island, or is detecting root inside a work profile, where it should not be possible (?).

I'm using the latest canary build.

**Comment by kurtextrem** [comment]
@alexa-v2 Thank you! Do you know any other app or something else to "hide" the SU binary?

**Comment by kurtextrem** [comment]
Can you remember the name of the xposed module?

**Comment by topjohnwu** [comment]
#1152
