### ISSUE TITLE
i also have some questions(it seems that magisk really doesn't fit A60)

### ISSUE THREAD

**Issue by w2016561536** [topjohnwu/Magisk#1799]
I have read all markdown files in docs.Follow the instructions in "install.md".I flashed the magisk_patched.img with 4 others official firmwares by odin .After that, I rebooted the phone manually with "power" and "volume down" . As soon as the screen turned black ,I held the "power" and "volume up"(Samsung A60 doesn't have bixby button) to boot to real recovery.When I saw the waring of the bootloader had been unlocked , I released the power button , but I still held the volume button for more then 1 minutes . I could only see this .
![IMG_0777](https://user-images.githubusercontent.com/40821031/63843837-a3750a00-c9b9-11e9-99c7-e3215f290bd2.JPG)

**Comment by w2016561536** [comment]
sorry it should be "magisk_patched.tar"

**Comment by w2016561536** [comment]
sorry , I typed the wrong words, it should be "magisk_patched.tar"

**Comment by w2016561536** [comment]
The text on screen:The phone does not run Samsung's official software. Mobile phone functionality and security may be problematic, and you can't install software updates

I have read install.md for many times . I also tried to flash it more than 2 times too.

**Comment by w2016561536** [comment]
> Could you translate the on-screen text?
> And did you retry, double checking your steps?

The text on screen:The phone does not run Samsung's official software. Mobile phone functionality and security may be problematic, and you can't install software updates
I have read install.md for many times . I also tried to flash it more than 2 times too.

**Comment by topjohnwu** [comment]
The instructions are complete. Multiple users already confirmed that those instructions work on all latest Samsung devices. You have to figure out the key combo to boot into download mode / recovery mode for your specific device, I can't help you with that.
