### ISSUE TITLE
No signal on A-only SAR with recovery mode Magisk

### ISSUE THREAD

**Issue by S190762** [topjohnwu/Magisk#1801]
Magisk installed to recovery partition on a A-Only system as root mediatek device. The device has no signal, and no IMEI number. Wifi works.

Tried all versions including stable/beta/canary/canary debug/ianmacd latest. No modules are installed. Attempting to dial a number says "Mobile network not available"

Dmesg is full of the following error:
[33.239513] [1:init] Could not find service hosting interface vendor.mediatek.hardware.radio@3.0::IRadio/imsrild1
[33.240113] [1:init] Received control message from 'interface'start' for 'vendor.mediatek.hardware.radio@3.0::IRadio/imsrild1'  from pid: 337 (/system/bin/hwservicemanager)

**Comment by S190762** [comment]
[last_kmsg.log](https://github.com/topjohnwu/Magisk/files/3553485/last_kmsg.log)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/3553486/dmesg.log)
[logcat.log](https://github.com/topjohnwu/Magisk/files/3553487/logcat.log)
[logcat_radio.log](https://github.com/topjohnwu/Magisk/files/3553488/logcat_radio.log)

**Comment by S190762** [comment]
[magisk_log_20190829_023008.log](https://github.com/topjohnwu/Magisk/files/3553492/magisk_log_20190829_023008.log)
[magisk_install_log_2019-08-29T012514Z.log](https://github.com/topjohnwu/Magisk/files/3553493/magisk_install_log_2019-08-29T012514Z.log)

**Comment by alexa-v2** [comment]
This seems an awful lot like a ROM issue

Are you on stock? Did you only flash magisk, did you modify ANYTHING else?

Because I've never seen magisk cause this....

And BTW what device?

**Comment by S190762** [comment]
The rom is completely stock, there are no custom roms for my device or TWRP. 

It is a Nokia 1 Plus running Android 9 Go Edition. It came with Android 9 so has A only system-as-root. The boot.img doesn't contain a ramdisk and magisk doesn't work if i try to patch the boot.img

**Comment by JarlPenguin** [comment]
If the device is running a 32 bit operating system: #1674

**Comment by nebulakl** [comment]
Same phone, (possibly) same rom and same issue on magisk 16b40096. 

All logs gathered with SysLog app and magisk logs:
https://gist.github.com/nebulakl/fe94a607a5188feeae942c384234ae9f

stock firmware package that *may* help analyze the issue
https://drive.google.com/open?id=1ZNEgRw33-4DlLkY6S_DbytOaZpaBprsh

**Comment by hasnainbhai77** [comment]
Having same issue on infinix smart 3 plus x627 on pie please solve this issue

**Comment by bauner** [comment]
I have the same issue on Redmi Note 8 pro

**Comment by unresolvedsymbol** [comment]
Can confirm Magisk v20.1 completely breaks the radio on Essential phone with stock Android 9, strangely it fixed it on some Android Q custom ROMs and stock betas but all of this is paranormal 😂

**Comment by osm0sis** [comment]
Out of curiosity, while unrooted with radio working can you adb shell into the ROM that Magisk was breaking radio for and give the output of `mount` ?

**Comment by nebulakl** [comment]
`mount` output while radio is working:

```
adb on /dev/usb-ffs/adb type functionfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,seclabel,relatime)
/dev/block/dm-0 on /vendor type ext4 (ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr)
/dev/block/dm-1 on /data type f2fs (rw,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,extent_cache,mode=adaptive,active_logs=6,alloc_mode=reuse,fsync_mode=posix)
/dev/block/dm-2 on /mnt/expand/bc9c63a3-cc24-4226-a75c-d9a939d341aa type f2fs (rw,dirsync,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,alloc_mode=default,fsync_mode=posix)
/dev/block/mmcblk0p10 on /mnt/vendor/protect_s type ext4 (rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered)
/dev/block/mmcblk0p12 on /mnt/vendor/persist type ext4 (rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered)
/dev/block/mmcblk0p14 on /vendor/BBSYS type ext4 (rw,context=u:object_r:bbs_file:s0,nosuid,nodev,noatime,data=ordered)
/dev/block/mmcblk0p19 on /vendor/elabel type ext4 (rw,context=u:object_r:fih_elabel_data_file:s0,nosuid,nodev,noatime,block_validity,delalloc,barrier,user_xattr)
/dev/block/mmcblk0p39 on /cache type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered)
/dev/block/mmcblk0p6 on /mnt/vendor/nvcfg type ext4 (rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered)
/dev/block/mmcblk0p7 on /mnt/vendor/nvdata type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered)
/dev/block/mmcblk0p9 on /mnt/vendor/protect_f type ext4 (rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered)
devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600)
/dev/root on / type ext4 (ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr)
/mnt/expand/bc9c63a3-cc24-4226-a75c-d9a939d341aa/media on /mnt/runtime/default/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal)
/mnt/expand/bc9c63a3-cc24-4226-a75c-d9a939d341aa/media on /mnt/runtime/read/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal)
/mnt/expand/bc9c63a3-cc24-4226-a75c-d9a939d341aa/media on /mnt/runtime/write/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal)
/mnt/expand/bc9c63a3-cc24-4226-a75c-d9a939d341aa/media on /storage/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal)
none on /acct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct)
none on /config type configfs (rw,nosuid,nodev,noexec,relatime)
none on /dev/cpuctl type cgroup (rw,nosuid,nodev,noexec,relatime,cpu)
none on /dev/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent)
none on /dev/memcg type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
none on /dev/stune type cgroup (rw,nosuid,nodev,noexec,relatime,schedtune)
proc on /proc type proc (rw,relatime,gid=3009,hidepid=2)
pstore on /sys/fs/pstore type pstore (rw,seclabel,nosuid,nodev,noexec,relatime)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
sysfs on /sys type sysfs (rw,seclabel,relatime)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,size=462448k,nr_inodes=115612,mode=755)
tmpfs on /mnt type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=462448k,nr_inodes=115612,mode=755,gid=1000)
tmpfs on /storage type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=462448k,nr_inodes=115612,mode=755,gid=1000)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,seclabel,relatime)
```

**Comment by osm0sis** [comment]
Thank you, and now for comparison, the same command with latest Magisk Canary flashed and mobile data broken?

**Comment by nebulakl** [comment]
`mount` output with magisk and broken radio:
```
adb on /dev/usb-ffs/adb type functionfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,seclabel,relatime)
/dev/block/dm-0 on /vendor type ext4 (ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr)
/dev/block/dm-1 on /data type f2fs (rw,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,extent_cache,mode=adaptive,active_logs=6,alloc_mode=reuse,fsync_mode=posix)
/dev/block/dm-2 on /mnt/expand/bc9c63a3-cc24-4226-a75c-d9a939d341aa type f2fs (rw,dirsync,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,alloc_mode=default,fsync_mode=posix)
/dev/block/mmcblk0p10 on /mnt/vendor/protect_s type ext4 (rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered)
/dev/block/mmcblk0p12 on /mnt/vendor/persist type ext4 (rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered)
/dev/block/mmcblk0p14 on /vendor/BBSYS type ext4 (rw,context=u:object_r:bbs_file:s0,nosuid,nodev,noatime,data=ordered)
/dev/block/mmcblk0p19 on /vendor/elabel type ext4 (rw,context=u:object_r:fih_elabel_data_file:s0,nosuid,nodev,noatime,block_validity,delalloc,barrier,user_xattr)
/dev/block/mmcblk0p39 on /cache type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered)
/dev/block/mmcblk0p6 on /mnt/vendor/nvcfg type ext4 (rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered)
/dev/block/mmcblk0p7 on /mnt/vendor/nvdata type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered)
/dev/block/mmcblk0p9 on /mnt/vendor/protect_f type ext4 (rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered)
devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600)
/dev/root on / type ext4 (ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr)
/mnt/expand/bc9c63a3-cc24-4226-a75c-d9a939d341aa/media on /mnt/runtime/default/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal)
/mnt/expand/bc9c63a3-cc24-4226-a75c-d9a939d341aa/media on /mnt/runtime/read/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal)
/mnt/expand/bc9c63a3-cc24-4226-a75c-d9a939d341aa/media on /mnt/runtime/write/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal)
/mnt/expand/bc9c63a3-cc24-4226-a75c-d9a939d341aa/media on /storage/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal)
none on /acct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct)
none on /config type configfs (rw,nosuid,nodev,noexec,relatime)
none on /dev/cpuctl type cgroup (rw,nosuid,nodev,noexec,relatime,cpu)
none on /dev/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent)
none on /dev/memcg type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
none on /dev/stune type cgroup (rw,nosuid,nodev,noexec,relatime,schedtune)
proc on /proc type proc (rw,relatime,gid=3009,hidepid=2)
pstore on /sys/fs/pstore type pstore (rw,seclabel,nosuid,nodev,noexec,relatime)
/sbin/.magisk/block/data on /sbin/.magisk/mirror/data type f2fs (rw,lazytime,seclabel,relatime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,extent_cache,mode=adaptive,active_logs=6,alloc_mode=reuse,fsync_mode=posix)
/sbin/.magisk/block/system_root on /sbin/charger type ext4 (ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr)
/sbin/.magisk/block/system_root on /sbin/.magisk/mirror/system_root type ext4 (ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr)
/sbin/.magisk/block/vendor on /sbin/.magisk/mirror/vendor type ext4 (ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
sysfs on /sys type sysfs (rw,seclabel,relatime)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,mode=755)
tmpfs on /mnt type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000)
tmpfs on /sbin type tmpfs (rw,seclabel,relatime,mode=755)
tmpfs on /storage type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,seclabel,relatime)
```

**Comment by nebulakl** [comment]
Interestingly, despite Magisk Manager shows Magisk is up to date, I was not able to gain root access.
Magisk Manager also shows my device requires additional setup but whenever I tap ok I only get setup failed message.
![image](https://user-images.githubusercontent.com/12024936/68905973-f89aff00-0710-11ea-865c-d5b1133dbf2b.png)
![image](https://user-images.githubusercontent.com/12024936/68905983-fe90e000-0710-11ea-8950-d1d31481c132.png)

**Comment by osm0sis** [comment]
Probably nothing of relevance but here's the diff of the working and broken mount outputs:
```
$ diff working.txt broken.txt
27a28,31
> /sbin/.magisk/block/data on /sbin/.magisk/mirror/data type f2fs (rw,lazytime,seclabel,relatime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,extent_cache,mode=adaptive,active_logs=6,alloc_mode=reuse,fsync_mode=posix)
> /sbin/.magisk/block/system_root on /sbin/charger type ext4 (ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr)
> /sbin/.magisk/block/system_root on /sbin/.magisk/mirror/system_root type ext4 (ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr)
> /sbin/.magisk/block/vendor on /sbin/.magisk/mirror/vendor type ext4 (ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr)
30,32c34,37
< tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,size=462448k,nr_inodes=115612,mode=755)
< tmpfs on /mnt type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=462448k,nr_inodes=115612,mode=755,gid=1000)
< tmpfs on /storage type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=462448k,nr_inodes=115612,mode=755,gid=1000)
---
> tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,mode=755)
> tmpfs on /mnt type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000)
> tmpfs on /sbin type tmpfs (rw,seclabel,relatime,mode=755)
> tmpfs on /storage type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000)
```

**Comment by alexa-v2** [comment]
> Interestingly, despite Magisk Manager shows Magisk is up to date, I was not able to gain root access.
> Magisk Manager also shows my device requires additional setup but whenever I tap ok I only get setup failed message.
> ![image](https://user-images.githubusercontent.com/12024936/68905973-f89aff00-0710-11ea-865c-d5b1133dbf2b.png)
> ![image](https://user-images.githubusercontent.com/12024936/68905983-fe90e000-0710-11ea-8950-d1d31481c132.png)

Just keep trying setup, sometimes takes a couple tries. But anyhow that's outside the scope of this issue, open another one if you continue to have issues @nebulakl

**Comment by fawazahmed0** [comment]
Have you flashed dm-verity disabler anytime? last time I had problem with that.
Just incase you flashed dm-verity disabler, I have the fix for it.

**Comment by Iscle** [comment]
Why was this issue closed? I have the same problem on a clean, source-built MediaTek MT6739 system running SAR Android 9!

**Comment by Iscle** [comment]
> Why was this issue closed? I have the same problem on a clean, source-built MediaTek MT6739 system running SAR Android 9!

It might be because the proper init files are not being called when booting from the recovery partition instead of the normal boot partition using system-as-root? Looking into it now.

I've taken a radio logcat with and without magisk, and noticed that NVRAM and RILMUXD, services that are started by the init files, are not logged when running Magisk from the recovery partition.

**Comment by ShaDisNX255** [comment]
I guess it must be a Mediatek problem
Samsung A10s, A-Only and System As Root also experiences this

When you reboot normally, signal returns but you lose Magisk of course
When you reboot + Magisk by using recovery hot keys, Magisk works but signal is gone

**Comment by buffer1900** [comment]
infinix  smart 4 x653   same problem.Any fix  for this  ?

**Comment by Axeltherabbit** [comment]
Same issue on blackview a60, mediatek chip, the IMEI is null in the recovery and fine with a normal boot

**Comment by arklese1zure** [comment]
Hi guys, I think me and some oher people are finding this problem on Galaxy A32 phones (Mediatek MT6769V).
What's strange is that the problem persists even after reflashing with stock ROM.

Has anyone found any possible solution?

**Comment by FlexaLOL** [comment]
> Hi guys, I think me and some oher people are finding this problem on Galaxy A32 phones (Mediatek MT6769V). What's strange is that the problem persists even after reflashing with stock ROM.
> 
> Has anyone found any possible solution?

yeah, my A32 4G with the same MTK Helio G80 (MT6769V) chipset has the same problem, and also, people with a22s and a32 5g are mass reporting this issue

**Comment by dronkit** [comment]
+1 Same problem with the samsung A325M (a32 4g), no IMEI or baseband a few days after rooting, flashing stock rom doesn't fix it. Updated Magisk up to canary 7cfce9ff, no fix.
My dmesg has lots of:
`Control message: Could not find 'vendor.samsung.hardware.radio.bridge@2.0::ISehBridge/slot1' for ctl.interface_start from pid: 440 (/system/bin/hwservicemanager)`,
`Control message: Could not find 'android.hardware.radio@1.5::IRadio/slot1' for ctl.interface_start from pid: 440 (/system/bin/hwservicemanager)`,
`Could not find 'vendor.samsung.hardware.radio.channel@2.0::ISehChannel/imsd' for ctl.interface_start from pid: 440 (/system/bin/hwservicemanager)`
IDK if related but my magisk log has lots of
`626   628 E : unlock mmcblk0p42 failed with 13: Permission denied`
for several devices.

Please ask me for any files/logs that can be helpful!

**Comment by dronkit** [comment]
I was able to fix it on the a32, working so far
https://forum.xda-developers.com/t/rooted-a325m-suddenly-no-imei-no-sim.4386753/post-86588571

IDK what is the cause, but mayb this will help the "victims" or the fixing of the issue

**Comment by osm0sis** [comment]
Could be worth trying with 24304, original init handles a lot more now.

**Comment by AHL8192** [comment]
I have the same problem. Any solutions?

**Comment by AHL8192** [comment]
Interesting that this issue is closed 4 years ago and no solution has been found  ::(

My MTK phone also doesn't have a ramdisk file. I have to boot into recovery in order for magisk to work. But when I boot into recovery, I lose cellular network access.
Any solutions?

**Comment by AHL8192** [comment]
interestingly I've just patched the boot image and now everything works.
I have no ramdisk though!!!!
