### ISSUE TITLE
Magisk Not Creating boot.img stock backup

### ISSUE THREAD

**Issue by Godlikehobbit** [topjohnwu/Magisk#1806]
Currently running magisk canary (19307) on a OnePlus 7 Pro with LineageOS 16 (26/08/19).|

I have tried installing Magisk through the built in lineage recovery, TWRP (3.3.1-4), and by patching the stock boot.img myself, but none of the methods create a backup that persists through a reboot. Magisk itself runs fine but without the stock image backup I am unable to follow the guide for OTA updates with magisk as there is no stock image to restore to. Not sure if I'm missing something obvious or Lineage is doing something strange

**Comment by topjohnwu** [comment]
The backup should exist unless your image is pre-patched.

**Comment by Godlikehobbit** [comment]
image isn't pre patch, log shows that it recognizes it as a stock image and backs it up but the backup is nowhere to be found

**Comment by Godlikehobbit** [comment]
In case anyone else is having this issue and made the same mistakes as me. The solution is (assuming you start with a working LineageOS 16 install):
1. extract the stock boot.img from your current update (I used [this script](https://gist.github.com/stainslav/5b88649f2554de47978a3f754dfcce2b) on the zip for my current version)
2. flash the stock boot image with fastboot from the bootloader
3. reboot into recovery and sideload magisk

The issue appears to be caused by the LineageOS boot.img not having implemented the fastboot boot command so the only way to install LineageOS from stock is by overwriting the stock boot.img with TWRP (or some other recovery) which means the Magisk boot.img backup gets overwritten when LineageOS finishes it's install.

Sorry for the issue topjohnwu, I must have not had enough sleep while trying to fix it myself.
