### ISSUE TITLE
Unsupported/Unknown image format

### ISSUE THREAD

**Issue by Intichar** [topjohnwu/Magisk#1809]
Hi,

I´m trying to install Magisk on a HTC U12+ Firmware version 2.55.401.1 (Android 9, August 2019) via "Select and Patch a File" Method.

Magisk Manager says:
-unpacking boot image
!Unsupported/Unknown image format
!Installation failed

Example Download location for boot.img file (boot_signed_2_55.401.1.img): https://androidfilehost.com/?fid=6006931924117931767
(just to make sure the file was OK: unpacked OTA bin with python payload_dumper, results in same file, naturally same issue.)

Please advise.
KR, Lorenz

**Comment by osm0sis** [comment]
That's not a boot.img, that's a boot.img.p, a bsdiff patch file from an incremental OTA to be applied to the existing boot partition.

**Comment by Intichar** [comment]
Ah, I see. Thanks for pointing out!
