### ISSUE TITLE
Some app can detect magisk

### ISSUE THREAD

**Issue by d3m3vilurr** [topjohnwu/Magisk#181]
Some app try existing check `/magisk/.core/bin/su` and `/dev/magisk/mirror/system`.
This method looks efficiently block the magisk hide.

Can you check this?

Detail information:

app - https://play.google.com/store/apps/details?id=com.hyundaicard.appcard
this app looks download rooting suspicion dictionary from the internet to `/data/data/com.../aria`
current dictionary updated at 4/19, and added information to `area/system.png`
```
<f>/magisk/.core/bin/su
<d>/dev/magisk/mirror/system
```
and leave detection to log before kill application.
```
04-26 01:12:16.202 11882 11882 D DXLog   : [ BEngineHelper ] checkRooting : File,/dev/magisk/mirror/system,Directory,[Suspicious-directory]
```

**Comment by JonnyTech** [comment]
Is this the case even when you hide the app in Magisk manager? Which version are you using?

**Comment by d3m3vilurr** [comment]
I was hiding before launch app. magisk v12.0 & android 7.1.2
