### ISSUE TITLE
Unable to boot phone while charging

### ISSUE THREAD

**Issue by Loakii** [topjohnwu/Magisk#1810]
While my phone is charging it stays on an unlocked bootloader warning. Which makes it impossible to boot the phone unless unplugged and forced to reboot with power and volume buttons. I've seen another issues regarding something to the oneplus 6, but that issue is mostly because of the charge animation.

This doesn't happen without Magisks being installed. Is there any chance this can be fixed?

**Device: OnePlus 6**

**Comment by osm0sis** [comment]
Have you tried on the latest Canary?

**Comment by topjohnwu** [comment]
#906
