### ISSUE TITLE
Unsupported/Unknown image format

### ISSUE THREAD

**Issue by rezeropoint** [topjohnwu/Magisk#1811]
**magisk_install_log_2019-09-01T19_26_51Z.log**

- Device platform: arm64-v8a
- Downloading zip
... 0%
- Copying image to cache
1022+1 records in
1022+1 records out
1047368 bytes transferred in 0.012 secs (87280666 bytes/sec)
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
! Unsupported/Unknown image format
! Installation failed

Device：MI 9se

**Comment by osm0sis** [comment]
Upload the boot.img

**Comment by dipakCrayon** [comment]
Where uploade boot.img ?

**Comment by osm0sis** [comment]
Here. GitHub allows uploads. @rezeropoint, please upload the boot.img you were having trouble patching.

**Comment by topjohnwu** [comment]
If @osm0sis have already confirmed that Mi 9 SE works just fine, I will say 99.999% the user is providing the incorrect file to Magisk Manager
