### ISSUE TITLE
Magisk hide does hide root on IRCTC imudra application

### ISSUE THREAD

**Issue by bukyapavankumar** [topjohnwu/Magisk#1812]
https://play.google.com/store/apps/details?id=com.matchmovepay.irctc

Here are logs  error
09-01 19:32:17.030 E/RootBeer(18243): b: a() [239] - com.topjohnwu.magisk ROOT management app detected!

**Comment by Ingan121** [comment]
#1152
(Do Manager>Settings>Repackage)

**Comment by bukyapavankumar** [comment]
What ? N How?
