### ISSUE TITLE
Google Pixel XL / Android 9 / Magisk 19.3 won't boot

### ISSUE THREAD

**Issue by coogle** [topjohnwu/Magisk#1814]
Device: Google Pixel XL w/TWRP 3.2.3-1-marlin installed, running stock Android 9 firmware (brand new install)

TWRP installed fine, Magisk seemed to install fine (no errors), but upon reboot it gets to the "G" screen (with a scrolling progress bar) that never goes away. Eventually, the device restarts and returns to Recovery Mode.

Note: I also tried 19.4 Canary latest, with the same effect (after uninstalling 19.3)

**Comment by topjohnwu** [comment]
Do you realize that I use Pixel devices as daily driver?
This is most likely an incompatible module issue

**Comment by coogle** [comment]
Nope I don't know anything about you :)

If you mean an Magisk module, I never got it working at all and it's the very first time I've ever used this code in fact... so if it's not stock I wasn't doing it!

I was able to resolve the issue myself by downgrading to Android 8 instead using TWRP 3.2.3-1. Used the exact same process otherwise so it's def. an issue on your end.
