### ISSUE TITLE
boot.img didn't work

### ISSUE THREAD

**Issue by 2019karl** [topjohnwu/Magisk#1816]
hi,i try to use magiskmanager to modify boot.img ,but somthing occured 
i used "fastboot flash boot magisk_patched.img" command ,it successful .but when i reboot ,it still unstalled magisk.
my phone pixel 3xl ,image version crosshatch-qp1a.190711.020

**Comment by topjohnwu** [comment]
Please use the latest canary

**Comment by 2019karl** [comment]
tks
