### ISSUE TITLE
[Feature Request] Option to create Magisk Core-Only boot images in Magisk Manager

### ISSUE THREAD

**Issue by suppai** [topjohnwu/Magisk#1817]
Would it be possible to add an option enabling Magisk Manager to create patched `boot.img`s that force Magisk Core-Only mode? This would allow users who don't have access to TWRP to recover from a bootloop caused by a broken Magisk Module, and is especially prominent now because Android 10 devices with the new partitioning scheme like the Pixel 3 and Pixel 3a don't work with TWRP (nothing can be mounted) and thus Magisk cannot be modified from there. Currently the only solution for these users is to either flash a stock `boot.img` and go rootless or wipe userdata, as deleting `/data/adb/modules` without TWRP or root is not possible.

**Comment by suppai** [comment]
Another potential solution I can think of would be MagiskInit checking for some keycombo at boot and forcing Core-Only if it's pressed, but not sure if this is feasible or not.

**Comment by reyqn** [comment]
As mentioned in #1286 it could be enough to just check more places for a .disable_magisk, (/persist/cache/) for example.

I had the issue you are talking about and I managed recovering from it without wiping userdata by editing [magisk.h](https://github.com/topjohnwu/Magisk/blob/master/native/jni/include/magisk.h) and recompiling magisk from scratch.

While waiting for a patch to the official magisk you rebuild magisk yourself with the modifications that suits you in [magisk.h](https://github.com/topjohnwu/Magisk/blob/master/native/jni/include/magisk.h) (or if you are using a pixel 3a I left a comment in [this](https://forum.xda-developers.com/showpost.php?p=80190577&postcount=554) thread on xda with a pre-patched boot.img)

**Comment by topjohnwu** [comment]
#1286
