### ISSUE TITLE
Can't launch MagiskHide

### ISSUE THREAD

**Issue by geek85** [topjohnwu/Magisk#1818]
When I toggle MagiskHide in manager, it became instable
If I close and launch manager again it will not detect magisk.
If I test in terminal:
```
magiskhide --enable
read (4 != 0) failed with 0: Success"
```
[magisk_log_20190905_163809.log](https://github.com/topjohnwu/Magisk/files/3579814/magisk_log_20190905_163809.log)
[logcat.log](https://github.com/topjohnwu/Magisk/files/3579817/logcat.log)

Honor 9 (STF-L09) on Android 7.0 with Magisk  Canary 19.4-736729f5

**Comment by osm0sis** [comment]
Sounds related to the major su shell regression I reported to @topjohnwu awhile back. Basically every second `su -c` command would show "Permission denied" and the logs would show "4 != 0".

I think https://github.com/topjohnwu/Magisk/commit/cdb53ca0490c03f8307e53baf0f648baa7af3511 is supposed to fix it, so we'll have to see in the next Canary and make sure. :+1:

**Comment by osm0sis** [comment]
@geek85 Try with 19308 and report back!

**Comment by geek85** [comment]
same here with canary  19308

**Comment by topjohnwu** [comment]
Cannot reproduce as of the latest canary release

**Comment by osm0sis** [comment]
@CaptainThrowback reproduced it today. Check #general on Slack.

**Comment by geek85** [comment]
Still present with 19406.
Could a factory reset resolve the problem ?

**Comment by geek85** [comment]
The problem was inside magisk.db
I recreated the database from SQL instructions I found here and replaced the DB with the new one. After a reboot, no more problem.

**Comment by osm0sis** [comment]
So uninstalling and reinstalling Magisk probably also would have worked. :+1:
