### ISSUE TITLE
Bank application Credit Mutuel detects phone is rooted

### ISSUE THREAD

**Issue by 1knod** [topjohnwu/Magisk#1819]
The latest version of the bank application "Credit Mutuel" detects that the phone is rooted. So I can't use the application.
App link : https://play.google.com/store/apps/details?id=com.cm_prod.bad
Version: 7.0.5

I'm using Magisk for week and everything works until the last update of the app. The version of Magisk has not been updated during this time.
* Magisk v19.3 (19000)
* Magisk Manager : v7.3.2 (224)
* Advanced Settings : preserve force encryption and preserve avb 2.0/dm-verity are unchecked
* SafetyNet Check Success : : ttsProfile and basicIntegrity are true

Installed Addons : 
* Youtube vanced - Magisk Repo v14.21.54 (b01.40.20)
* xmlpak  - a road to vendor apps v3.5
* Samsung 4k60 Camera Mod v7.6.86-3.0.3
* Google Dialer Framework v5
* Energized Protection: 
* Debloater v17.2.1

Phone : Samsung S7 Edge (SM-G935FD)
Android : 8.00 with security path from June 1, 2019

**Comment by Didgeridoohan** [comment]
https://github.com/topjohnwu/Magisk/issues/1152

And

https://www.didgeridoohan.com/magisk/MagiskHide#hn_Hiding_root_from_apps

**Comment by Hunsu** [comment]
I'm using CIC and I think it has the same detection mechanism as the one from Credit Mutuel (same bank). I found out that if you replace the webview the app will think you have root.

So I deleted bromite webview and the app is working again. I found out this by looking at the logcat logs.

**Comment by breversa** [comment]
Shelter (https://f-droid.org/en/packages/net.typeblog.shelter/) did the trick for me for this application.

**Comment by breversa** [comment]
> Shelter (https://f-droid.org/en/packages/net.typeblog.shelter/) did the trick for me for this application.

… or so I thought.
It worked once, then failed again. Can't remember what I changed inbetween…
