### ISSUE TITLE
Can't install Magisk modules

### ISSUE THREAD

**Issue by rnhmjoj** [topjohnwu/Magisk#1822]
### Issue description
I can't seem to install Magisk modules from any of the repos [here](https://github.com/Magisk-Modules-Repo). The installation fails with this error:
```
- Copying zip to temp directory
! This zip is not a Magisk module!
! Installation failed
```

### Steps to reproduce
Try for instance [dnscrypt-proxy.zip](https://github.com/Magisk-Modules-Repo/dnscrypt-proxy/archive/master.zip) or [mm.zip](https://github.com/Magisk-Modules-Repo/mm/archive/master.zip)

### Info
Magisk: v19.3
Android: LineageOS 15.1

**Comment by Didgeridoohan** [comment]
The zip won't be packaged properly if you download the repository directly from Github like that. Download from the Magisk Manager instead.

And please close this issue so that John doesn't have to.

**Comment by rnhmjoj** [comment]
I'm just following the [instructions](https://github.com/Magisk-Modules-Repo/dnscrypt-proxy#installation). So they are either wrong or misleading, at least.

What is needed to "properly" package a module anyway?

**Comment by Didgeridoohan** [comment]
Those instructions are wrong, yes, but that's not John's fault... Take that up with the module creator, download/install your modules from the Magisk Manager (or, just take the repository zip and repack it with the module files in the root of the zip rather then the <name-of-module> directory).

And of course, close the issue...

**Comment by rnhmjoj** [comment]
> just take the repository zip and repack it with the module files in the root of the zip rather then the directory

Ah, I see. Thank you.

> And of course, close the issue...

If it's so important to close issues as soon as possible... ok.

**Comment by Didgeridoohan** [comment]
Thank you. To clarify, it's not important to close issues as soon as possible... I'm just trying to keep John's workload slightly smaller by asking the people that opened issues, that shouldn't have been opened in the first place, to close them themselves.

**Comment by Feda777Feda** [comment]
> ### Issue description
> I can't seem to install Magisk modules from any of the repos [here](https://github.com/Magisk-Modules-Repo). The installation fails with this error:
> 
> ```
> - Copying zip to temp directory
> ! This zip is not a Magisk module!
> ! Installation failed
> ```
> 
> ### Steps to reproduce
> Try for instance [dnscrypt-proxy.zip](https://github.com/Magisk-Modules-Repo/dnscrypt-proxy/archive/master.zip) or [mm.zip](https://github.com/Magisk-Modules-Repo/mm/archive/master.zip)
> 
> ### Info
> Magisk: v19.3 Android: LineageOS 15.1
