### ISSUE TITLE
In-Built BusyBox remains active after disabling in Manager settings

### ISSUE THREAD

**Issue by Amber26Theta** [topjohnwu/Magisk#183]
I have the in-built busybox disabled to stop a loss of root on my Moto G4 Plus (XT1644), however I still see "Enabling Busybox" in the magisk log, implying that it is still active.

**Comment by Amber26Theta** [comment]
Here is an image of the issue https://imgur.com/a/EHMbE

**Comment by Didgeridoohan** [comment]
Have you checked in /system/xbin if busybox if there with all it's applets (a whole lot of symlinked files)? To verify? Or you could use an app that checks if busybox is properly installed (there's a bunch of them in the Play store).

The "Enabling Busybox" line stays in the log even after disabling built-in busybox.

**Comment by Amber26Theta** [comment]
It's less of me wanting to use BusyBox and more just wanting to actually keep my root for a sizeable amount of time. However, I will take a ss of the folder and post it here

**Comment by Didgeridoohan** [comment]
So, that means: yes you can confirm that Magisk busybox is still there? 

Check if the files are symlinks pointing to /data/magisk/busybox.

**Comment by Amber26Theta** [comment]
The issue seems to be a ROM issue: Opening the Manager from my home screen causes me to lose my root, while opening the Manager directly from the Settings app fixes root. Strange.
