### ISSUE TITLE
Reopen: Package parse error when trying to update a hidden Magisk Manager.

### ISSUE THREAD

**Issue by martyfender** [topjohnwu/Magisk#1834]
On a hidden Magisk Manager only, there is a parse error when trying to update the manager to the latest build. Unhiding MM in settings and it is successfully updated. Then it must be rehid. If the user had the update channel set to anything other than the Canary debug, then it must be changed back twice, also.
Attached are filtered logcats using LogcatX's per app logcat.
[Log_2019-9-08_13-15-01.txt](https://github.com/topjohnwu/Magisk/files/3587828/Log_2019-9-08_13-15-01.txt)
[Log_2019-9-08_13-13-49.txt](https://github.com/topjohnwu/Magisk/files/3587829/Log_2019-9-08_13-13-49.txt)

On @ianmacd, latest, 2019091001 build, with all of your latest commits, including the "fix",
d73f39c706e54256440c09fb22b1cdc4e2a586c6
 the problem still happens.
This is on all three of my Nextbook tablets with @ianmacd builds and of course, the 2 that I have yesterday's Canary debug builds. @ianmacd builds have his own update channel that is reset each time to the default, Canary debug channel.

 Is there anything else I can provide to help solve this issue?

Thanks John, I appreciate your effort, considering you are, (I assume), back at UM to continue your  Masters studies. I wish you the best in your studies.

**Comment by topjohnwu** [comment]
The old build was already broken, I cannot fix it.
Try to redownload the manager once you've upgraded, it'll work just fine.

**Comment by martyfender** [comment]
Thanks @topjohnwu I should have realized that I was going from a version with a bug to a version with it fixed. That is wy I still had the error.
