### ISSUE TITLE
Patch vbmeta.img in BL tar file

### ISSUE THREAD

**Issue by mohammad92** [topjohnwu/Magisk#1835]
A105F BL tar file contain vbmeta.img and it replace the on in AP patched tar.
When you select the BL tar file to patch in magisk manager it fail due to no boot.img there. If you can make it to patch the vbmeta.img only we can pass this issue.

**Comment by axifive** [comment]
You don't need patch vbmeta. It just flashed in fastboot mode with 'disable-verity' and 'disable-verification' flags:
`fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img`

**Comment by topjohnwu** [comment]
Then manually remove the `vbmeta.img` within BL.
