### ISSUE TITLE
[Android10] A-only two stage system-as-root

### ISSUE THREAD

**Issue by argraur** [topjohnwu/Magisk#1838]
https://source.android.com/devices/bootloader/system-as-root

Android 10 forces system-as-root for all devices now, on non-A/B devices, both recovery and boot partitions exist, but boot partition **contains** ramdisk with init and base mount points

System boots in two stages. Kernel starts with boot-ramdisk as ramdisk and executes first stage init (/init) that mounts system, chroots into it and executes /system/bin/init (second stage init) that starts Android system.

**A-only boot-ramdisk layout**:
/apex (folder)
/avb (folder)
/debug_ramdisk (folder)
/dev (folder, mount point)
/init (static executable)
/mnt (folder, mount point)
/proc (folder, mount point)
/sys (folder, mount point)

_Magisk currently can't handle these boot-ramdisks_.

**Comment by argraur** [comment]
By the way, system can be mounted as r/w on A-only devices.

**Comment by topjohnwu** [comment]
@argraur I think you are currently using custom ROM. On stock ROMs, the system image is formatted as "ext4 dedup", which is not possible to mount r/w. Check my tweets to see more info about this.

**Comment by xyyx** [comment]
> https://source.android.com/devices/bootloader/system-as-root
> 
> Android 10 forces system-as-root for all devices now, on non-A/B devices, both recovery and boot partitions exist, but boot partition **contains** ramdisk with init and base mount points
> 
> System boots in two stages. Kernel starts with boot-ramdisk as ramdisk and executes first stage init (/init) that mounts system, chroots into it and executes /system/bin/init (second stage init) that starts Android system.
> 
> **A-only boot-ramdisk layout**:
> /apex (folder)
> /avb (folder)
> /debug_ramdisk (folder)
> /dev (folder, mount point)
> /init (static executable)
> /mnt (folder, mount point)
> /proc (folder, mount point)
> /sys (folder, mount point)
> 
> _Magisk currently can't handle these boot-ramdisks_.

Superuser is alive) Still alive) But I am waiting for Magisk)
![photo_2019-09-14_09-24-23](https://user-images.githubusercontent.com/7220590/64901921-74f17180-d6d1-11e9-8e02-379d1666ee8f.jpg)

**Comment by Howard-00** [comment]
> > https://source.android.com/devices/bootloader/system-as-root
> > Android 10 forces system-as-root for all devices now, on non-A/B devices, both recovery and boot partitions exist, but boot partition **contains** ramdisk with init and base mount points
> > System boots in two stages. Kernel starts with boot-ramdisk as ramdisk and executes first stage init (/init) that mounts system, chroots into it and executes /system/bin/init (second stage init) that starts Android system.
> > **A-only boot-ramdisk layout**:
> > /apex (folder)
> > /avb (folder)
> > /debug_ramdisk (folder)
> > /dev (folder, mount point)
> > /init (static executable)
> > /mnt (folder, mount point)
> > /proc (folder, mount point)
> > /sys (folder, mount point)
> > _Magisk currently can't handle these boot-ramdisks_.
> 
> Superuser is alive) Still alive) But I am waiting for Magisk)
> ![photo_2019-09-14_09-24-23](https://user-images.githubusercontent.com/7220590/64901921-74f17180-d6d1-11e9-8e02-379d1666ee8f.jpg)

How to use it? I tried to copy file from phh's superuser but it doesn't work.

**Comment by argraur** [comment]
@topjohnwu I just tried to mount K20 Pro Android 10 system image as r/w and it worked! http://bigota.d.miui.com/9.05.24/raphael_android_images_9.05.24.1.native.google.user_20190524.0000.00_10.0_ab58fbe3cb.tgz

**Comment by half-cambodian-hacker-man** [comment]
@topjohnwu Since this is becoming a blocker as more devices adopt Android 10, would it be worth funding an A-only Q-capable device for your testing?

**Comment by jmac052002** [comment]
I would definitely throw in to fund an A-only device for testing!

**Comment by argraur** [comment]
There are no A-only devices launched with Q. There are Mi 9 and K20 Pro that got official Q but both of them have Pie system-as-root implementation.

**Comment by skittles9823** [comment]
John has a Nexus 5X which just got Pixel Experience 10 so now that he's released the new Magisk 19.4 beta he will probably start on seeing what's up with A only SAR on Q.

**Comment by YoDevil** [comment]
To elaborate on some comments above:
A-only 2 stage init SAR can work both by including an fstab in the first stage ramdisk where the fstab contains `/system` with the flag `first_stage_mount`( reference article https://source.android.com/devices/architecture/kernel/mounting-partitions-early#fstab-ramdisk ), OR by early-mounting the `/system` block in dts fstab (note that the article does NOT say this is a possible solution!)
The second approach is the trend custom roms are going to follow for supporting legacy devices (before the legacy-SAR era), while the first one is most likely going to be used by vendors who are willing to release devices on Q with A-only SAR.
Idealy you'd want to support both, thus the detection logic may get a little more complex.

**Comment by topjohnwu** [comment]
These series of commits add support for A-only 2SI devices: 4d91e50d6dec76a4bdcec737f11d7547b0da34cb...cf2d02c0dddbaaaa2b50b71369f8c8e5aa143b55

**Comment by AlexZorzi** [comment]
I'm still facing bootloops after installing latest magisk canary on s8 lineage 17.0 exynos 8990. uploading pstore logs can be useful?
