### ISSUE TITLE
你好，麻烦看下。申请ROOT权限无响应

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#1844]
你好， 发现一个很多网友反馈过的问题。 最开始我以为只是个别机型的个例。后面经常有网友反馈这个问题。

已经在magisk manager 超级用户列表中的app 可以使用root权限。但是新的app申请root权限无响应。尝试删除了/data/adb文件夹以及/cache下的文件和卸载重装magisk manager都不行。

最新的稳定版和canary版都不行。我分别上传了附件。

唯一的解决方法是恢复出厂设置。 但是，我很奇怪。为什么恢复出厂设置能解决。 难道，magisk除了/data/adb /cache /data/data/com.topjohnwu.magisk 之外还有其他用到的文件夹？ 

[v19.4-f383d11d_magisk.log](https://github.com/topjohnwu/Magisk/files/3613923/v19.4-f383d11d_magisk.log)
[v19.3_magisk.log](https://github.com/topjohnwu/Magisk/files/3613926/v19.3_magisk.log)

**Comment by androiddisk** [comment]
另外 尝试在 设置的 自动响应 从 提示改为允许也无效

**Comment by topjohnwu** [comment]
那個是許多 ROM 有做過度電力優化，導致 root request 無法出現。
非常多針對中國優化得系統都會有這種情形，請手動將 Magisk Manager 加入白名單
