### ISSUE TITLE
无响应ROOT 应该与设置无关

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#1846]
你好 麻烦耽搁你一点时间，请再看一遍我的问题。
#1844 
根据上个提问大神的回复。 是系统禁止了Magisk的弹窗的意思是把。 
我真的可以肯定不是这个原因。比如我在自动响应设置允许后。 就无需弹悬浮窗获取ROOT权限。

但是遇到BUG时，就是没法弹出悬浮窗。即使设置自动响应为允许后

![QQ图片20190916211410](https://user-images.githubusercontent.com/11062371/64960948-fd853300-d8c6-11e9-9488-09712925a15f.jpg)

最最奇怪的是，每次恢复出厂设置后。就能正常获取ROOT权限。隔两天就不能了。而且是概率性出现。 想找LOG也很无奈

**Comment by androiddisk** [comment]
即使正处于Magisk Manager主界面。 依然无法得到软件申请ROOT的弹窗

**Comment by topjohnwu** [comment]
這個跟彈窗與否無關，而是系統禁止 Magisk Manager 在背景中被喚醒。
設置成自動允許，Magisk 仍要啟動 Magisk Manager，差別只是 Magisk Manager 會自動幫你允許，而不會開啟新的視窗。
你可以把 Magisk Manager 手動打開，然後不關閉試試看。
若這樣也不行的話，那我也無解了.....
