### ISSUE TITLE
Android X86 7.1 "No such file or directory" in magisk log

### ISSUE THREAD

**Issue by railty** [topjohnwu/Magisk#1847]
I have install Magisk successfully on a VM running Android X86 Nougat 7.1 r2, by following the tutorial (https://asdasd.page/2018/02/18/Install-Magisk-on-Android-x86/). There is no error message during the installation, after reboot, magisk manager (7.3.2) shows the magisk 19.3 is installed and is up to date. but there are 2 errors in the masgisk log.

09-16 14:24:34.378  2020  2021 E Magisk  : mount /sbin/.magisk/block/system->/sbin/.magisk/mirror/system failed with 16: Device or resource busy
09-16 14:24:34.378  2020  2021 I Magisk  : mount: /sbin/.magisk/mirror/system
09-16 14:24:34.379  2020  2021 I Magisk  : mount: /sbin/.magisk/mirror/data
09-16 14:24:34.379  2020  2021 I Magisk  : link: /sbin/.magisk/mirror/vendor
09-16 14:24:34.379  2020  2021 I Magisk  : * Setting up internal busybox
09-16 14:24:34.383  2020  2021 I Magisk  : * Running post-fs-data.d scripts
09-16 14:24:34.383  2020  2021 E Magisk  : mount /sbin/.magisk/mirror/data/adb/modules->/sbin/.magisk/modules failed with 2: No such file or directory

Does this matter? Am I running magisk or not, I cannot install Riru-Core (install failed) or Xposed Framework (Installed succeffully, but not active), is this related?

some more error message in the log

09-16 14:37:14.178  2020  2021 I Magisk  : * Running module post-fs-data scripts
09-16 14:37:14.178  2020  2021 I Magisk  : xposed: exec [post-fs-data.sh]
09-16 14:37:14.183  2020  2021 I Magisk  : * Loading modules
09-16 14:37:14.183  2020  2021 I Magisk  : xposed: constructing magic mount structure
09-16 14:37:14.183  2020  2021 E Magisk  : opendir: /sbin/.magisk/mirror/system/framework failed with 2: No such file or directory
09-16 14:37:14.183  2020  2021 E Magisk  : opendir: /sbin/.magisk/mirror/system/lib failed with 2: No such file or directory
09-16 14:37:14.183  2020  2021 E Magisk  : mount /sbin/.magisk/modules/xposed/system/bin/patchoat->/system/bin/patchoat failed with 2: No such file or directory
09-16 14:37:14.183  2020  2021 I Magisk  : bind_mount: /system/bin/patchoat
09-16 14:37:14.183  2020  2021 E Magisk  : mount /sbin/.magisk/modules/xposed/system/bin/oatdump->/system/bin/oatdump failed with 2: No such file or directory
09-16 14:37:14.183  2020  2021 I Magisk  : bind_mount: /system/bin/oatdump
09-16 14:37:14.183  2020  2021 E Magisk  : mount /sbin/.magisk/modules/xposed/system/bin/dex2oat->/system/bin/dex2oat failed with 2: No such file or directory
09-16 14:37:14.183  2020  2021 I Magisk  : bind_mount: /system/bin/dex2oat
09-16 14:37:14.183  2020  2021 E Magisk  : mount /sbin/.magisk/modules/xposed/system/bin/app_process32->/system/bin/app_process32 failed with 2: No such file or directory

**Comment by topjohnwu** [comment]
The error is this line:
`E Magisk : mount /sbin/.magisk/block/system->/sbin/.magisk/mirror/system failed with 16: Device or resource busy`

The system is not in an environment Magisk is expecting, thus causing these bugs.
