### ISSUE TITLE
Chcon 指令未找到

### ISSUE THREAD

**Issue by tony8077616** [topjohnwu/Magisk#1849]
大哥你好
本人採用你的腳本進行GApps的安裝
但是在SaR與Non-SaR雙架構的TWRP情況下，卻發生 chcon大哥你好，我是孟武
本人採用你的腳本進行GApps的安裝
但是在SaR與Non-SaR雙架構的TWRP情況下，卻發生 chcon指令找不到的問題
(Busybox採用您Magisk自身的那個)
![image](https://user-images.githubusercontent.com/9822340/65149474-be84e800-da54-11e9-89e5-a45fbefc0152.png)

**Comment by topjohnwu** [comment]
那個是你的 TWRP 的問題，chcon 在 Android 4.3 以上應該都要存在
