### ISSUE TITLE
Cannot boot if magisk.img is resized

### ISSUE THREAD

**Issue by Zulgrib** [topjohnwu/Magisk#185]
When flashing from TWRP a magisk module from the magisk module repo downloaded from magisk manager and a magisk.img resize happens, the device will be stuck on the boot screen forever, until magisk.img is deleted, stock boot.img flashed and kernel+supersu+magisk are reflashed.

I don't understand why a resize is required for a 20Kb module in the first place...
The script should check if the img is corrupted and restore a backup it had done before resizing if something goes wrong...

ZE551ML
Stock 6.0.1 (UL-Z00A-WW-4.21.40.223-user)
Magisk v12

I don't have log, ADB doesn't work in this situation

**Comment by xenithorb** [comment]
I think I'm being hit by this - and I believe it specifically occurs after the *second* resize.

LineageOS 14.1  on OnePlus One bacon. I'm not sure what else it could be.

**Comment by Zulgrib** [comment]
This problem is restricting Magisk's potential as it is impossible to install more than one module without triggering resize.

**Comment by thermatk** [comment]
Same on latest LineageOS on Nexus 5X

**Comment by vemacs** [comment]
Assuming this is related to https://github.com/topjohnwu/Magisk/issues/234. This is a serious issue - a total data partition restore/reset is necessary to fix it, and it shouldn't be happening in the first place.

**Comment by Zulgrib** [comment]
Don't know if same root cause as flashing stock boot image, delete magisk.img and start over works here.
There is no need to format data.

**Comment by vemacs** [comment]
Deleting magisk.img/reflashing boot only works if your device is unencrypted. If it's encrypted, you have to reset/restore.

**Comment by xenithorb** [comment]
My device is encrypted and I've never needed to reset/restore

**Comment by vemacs** [comment]
A bunch of OnePlus 3/T users have: https://forum.xda-developers.com/oneplus-3t/help/blackscreen-magisk-update-t3576571?nocache=1

**Comment by topjohnwu** [comment]
Should be fixed by now
