### ISSUE TITLE
May Magisk can install for ARM64 CPU?

### ISSUE THREAD

**Issue by ythsu0305** [topjohnwu/Magisk#1852]
I have one HTC X9U DUAL. This is a ARM64 CPU DEVICE.
Would you please could provide ARM64 compiled version or How could I find the ARM64 Version at github? thanks all

**Comment by martyfender** [comment]
I believe the current Magisk should install on ARM64 devices. Have you actually tried to install it?
If  you have problems installing, the Canary build will provide much better logging.

[https://www.didgeridoohan.com/magisk/MagiskHelp](url)

**Comment by topjohnwu** [comment]
It does
