### ISSUE TITLE
On the latest magisk Canary and unofficial builds, in a root terminal, has anyone else seen this strange behavior: (unreachable)?

### ISSUE THREAD

**Issue by martyfender** [topjohnwu/Magisk#1853]
On the latest magisk Canary and unofficial builds, in a root terminal, has anyone else seen this strange behavior: (unreachable)? Root in the terminal appears to be working normally. Is it just a cosmetic error? Disclaimer, I have not used the terminal recently, so I'm not sure when this started.

 Screenshots and the magisk.log are attached to this post in the general forum:

https://forum.xda-developers.com/showpost.php?p=80266583&postcount=35733]

Nextbook Ares 8A, Intel x86, Android 6.0.1. the latest Canary 19309, Magisk Manager, 234. This also happens on @ianmacd latest unofficial build.

Thanks

**Comment by topjohnwu** [comment]
Sorry, but I cannot reproduce this issue.

**Comment by jpzex** [comment]
I just updated to Magisk 20.0 and it happened. I always use terminal and this appeared to me right now. in fact I found this GitHub issue searching for answers.

Here is my terminal: https://play.google.com/store/apps/details?id=jackpal.androidterm

And here my "env" and "set" output before and after I type "su":

Before:

cedric:/ $ env
_=/system/bin/env
ANDROID_DATA=/data
TMPDIR=/data/local/tmp
HOME=/data/user/0/jackpal.androidterm/app_HOME
ANDROID_SOCKET_zygote=9
EXTERNAL_STORAGE=/sdcard
ANDROID_ROOT=/system
ANDROID_BOOTLOGO=1
ANDROID_ASSETS=/system/app
BOOTCLASSPATH=/system/framework/QPerformance.jar:/system/framework/qcom.fmradio.jar:/system/framework/oem-services.jar:/system/framework/tcmiface.jar:/system/framework/telephony-ext.jar:/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/bouncycastle.jar:/system/framework/apache-xml.jar:/system/framework/legacy-test.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/android.hidl.base-V1.0-java.jar:/system/framework/android.hidl.manager-V1.0-java.jar
ASEC_MOUNTPOINT=/mnt/asec
HOSTNAME=cedric
DOWNLOAD_CACHE=/data/cache
ANDROID_STORAGE=/storage
PATH=/sbin:/system/bin:/vendor/bin
SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/com.android.location.provider.jar
TERM=screen
cedric:/ $ set
ANDROID_ASSETS=/system/app
ANDROID_BOOTLOGO=1
ANDROID_DATA=/data
ANDROID_ROOT=/system
ANDROID_SOCKET_zygote=9
ANDROID_STORAGE=/storage
ASEC_MOUNTPOINT=/mnt/asec
BASHPID=22628
BOOTCLASSPATH=/system/framework/QPerformance.jar:/system/framework/qcom.fmradio.jar:/system/framework/oem-services.jar:/system/framework/tcmiface.jar:/system/framework/telephony-ext.jar:/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/bouncycastle.jar:/system/framework/apache-xml.jar:/system/framework/legacy-test.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/android.hidl.base-V1.0-java.jar:/system/framework/android.hidl.manager-V1.0-java.jar
COLUMNS
DOWNLOAD_CACHE=/data/cache
EPOCHREALTIME=1571223266.310831
EXTERNAL_STORAGE=/sdcard
HOME=/data/user/0/jackpal.androidterm/app_HOME
HOSTNAME=cedric
IFS=$' \t\n'
KSHEGID=10114
KSHGID=10114
KSHUID=10114
KSH_VERSION='@(#)MIRBSD KSH R55 2017/04/12'
LINES
OPTIND=1
PATH=/sbin:/system/bin:/vendor/bin
PATHSEP=:
PGRP=22628
PIPESTATUS[0]=1
PPID=19872
PS1=$'${|\n\tlocal e=$?\n\n\t(( e )) && REPLY+="$e|"\n\n\treturn $e\n}$HOSTNAME:${PWD:-?} $ '
PS2='> '
PS3='#? '
PS4='[$EPOCHREALTIME] '
PWD=/
RANDOM=1756
SECONDS=6
SHELL
SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/com.android.location.provider.jar
TERM=screen
TMOUT=0
TMPDIR=/data/local/tmp
USER_ID=10114
_=set
cedric:/ $



After:

cedric:/ $ su
cedric:(unreachable) # env
_=/system/bin/env
ANDROID_DATA=/data
DOWNLOAD_CACHE=/data/cache
LOGNAME=root
HOME=/
ANDROID_SOCKET_zygote=9
TERM=screen
SHELL=/system/bin/sh
ANDROID_BOOTLOGO=1
ANDROID_ASSETS=/system/app
BOOTCLASSPATH=/system/framework/QPerformance.jar:/system/framework/qcom.fmradio.jar:/system/framework/oem-services.jar:/system/framework/tcmiface.jar:/system/framework/telephony-ext.jar:/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/bouncycastle.jar:/system/framework/apache-xml.jar:/system/framework/legacy-test.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/android.hidl.base-V1.0-java.jar:/system/framework/android.hidl.manager-V1.0-java.jar
ASEC_MOUNTPOINT=/mnt/asec
HOSTNAME=cedric
ANDROID_STORAGE=/storage
USER=root
TMPDIR=/data/local/tmp
PATH=/sbin:/system/bin:/vendor/bin
SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/com.android.location.provider.jar
ANDROID_ROOT=/system
EXTERNAL_STORAGE=/sdcard
cedric:(unreachable) # set
ANDROID_ASSETS=/system/app
ANDROID_BOOTLOGO=1
ANDROID_DATA=/data
ANDROID_ROOT=/system
ANDROID_SOCKET_zygote=9
ANDROID_STORAGE=/storage
ASEC_MOUNTPOINT=/mnt/asec
BASHPID=22968
BOOTCLASSPATH=/system/framework/QPerformance.jar:/system/framework/qcom.fmradio.jar:/system/framework/oem-services.jar:/system/framework/tcmiface.jar:/system/framework/telephony-ext.jar:/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/bouncycastle.jar:/system/framework/apache-xml.jar:/system/framework/legacy-test.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/android.hidl.base-V1.0-java.jar:/system/framework/android.hidl.manager-V1.0-java.jar
COLUMNS
DOWNLOAD_CACHE=/data/cache
EPOCHREALTIME=1571223316.091583
EXTERNAL_STORAGE=/sdcard
HOME=/
HOSTNAME=cedric
IFS=$' \t\n'
KSHEGID=0
KSHGID=0
KSHUID=0
KSH_VERSION='@(#)MIRBSD KSH R55 2017/04/12'
LINES
LOGNAME=root
OPTIND=1
PATH=/sbin:/system/bin:/vendor/bin
PATHSEP=:
PGRP=22968
PIPESTATUS[0]=1
PPID=673
PS1=$'${|\n\tlocal e=$?\n\n\t(( e )) && REPLY+="$e|"\n\n\treturn $e\n}$HOSTNAME:${PWD:-?} # '
PS2='> '
PS3='#? '
PS4='[$EPOCHREALTIME] '
PWD='(unreachable)'
RANDOM=27490
SECONDS=6
SHELL=/system/bin/sh
SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/com.android.location.provider.jar
TERM=screen
TMOUT=0
TMPDIR=/data/local/tmp
USER=root
USER_ID=0
_=set
cedric:(unreachable) #

My Magisk config is:

Core Only Mode Off
Magisk Hide On
Systemless Hosts added
Superuser for Apps and ADB
Multiuser User-independent
Global Mount Namespace

My ROM has forceencrypt enabled by default (kept) and dm-verity was patched on Magisk recovery install.

I have some modules installed, I'll disable all of them and see if they influence this behaviour. (On previous Magisk versions it did not happen)

**Comment by ianmacd** [comment]
> This also happens on @ianmacd latest unofficial build.

At John's request, my unofficial build has no longer been distributed since 2019-09-22. Please switch to Canary.

**Comment by vindicatorr** [comment]
I know this issue is old, but I just encountered it myself and also found it odd.

But my findings on the topic resulted in the "Mount Namespace Mode" being set to "Isolated Namespace". When I change it back to the default of "Global", it no longer shows as "unreachable" (as does "inherit").

As isolated, going to any directory (eg. $ cd /) makes the "unreachable" go away (and as expected, pwd shows the path).

Question would be what "isolated" does to make the path something other than "/" when you enter into "su".

**Comment by jpzex** [comment]
Since the beginning, I use global mount to ensure compatibility among
applications which involve mounting partitions system-wide. I always had
this (unreachable) appearing on terminal. The solution is to run "cd /"
then do whatever I need.
