### ISSUE TITLE
Flashing Magisk on Global MIUI ROM for Mi9t Pro results in a bootloop

### ISSUE THREAD

**Issue by ixanza** [topjohnwu/Magisk#1854]
This here is a strange behaviour for me as we have multiple versions of the MIUI ROM, flashing Magisk on the Chinese or Indian version of the ROM works fine however flashing Magisk on the global version of the ROM will result in a bootloop. 

There is a way to get around it by formatting the data partition but then magisk will ask to install the full version which will result in a bootloop again. The ROM works fine without the full version and root is present however I am unable to use any modules from it.

**Comment by ixanza** [comment]
Why was this closed without any explanation?

**Comment by martyfender** [comment]
The most likely reason is that you didn't provide logs. He also ask users posting here be on the Canary build.

https://www.didgeridoohan.com/magisk/MagiskHelp

**Comment by ixanza** [comment]
Alright I'm heading to work now I'll try the new 19.4 beta or canary and provide logs when I'm back in like 12 hours. Had no idea that there's logs during bootloops.
