### ISSUE TITLE
Magisk Manager Patch-Error and Corrupted 'magisk_patched.tar'

### ISSUE THREAD

**Issue by eladkarako** [topjohnwu/Magisk#1855]
@topjohnwu 

Unzipped the original firmware with https://github.com/mcmilk/7-Zip-zstd/releases/tag/19.00-v1.4.2-R1 and feed the AP_.. file to MagiskManager.

https://github.com/topjohnwu/Magisk/releases/tag/manager-v7.3.4 (MagiskManager-v7.3.4.apk)
The latest manager is giving me an error and result with a corrupted `AP_....` file that can't be extracted fully with 7zip (test) and makes odin hang when flashing 'system' up until Windows-explorer closes it down.

<img src="https://i.imgur.com/CWxz4CB.jpg"/>
<br/>
<img src="https://i.imgur.com/NVH6UEC.png"/>

<pre>
- Device platform: armeabi-v7a
- Processing tar file
-- Extracting: boot.img.lz4
-- Decompressing: boot.img.lz4
Detected format: [lz4]
Decompressing to [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
-- Extracting: recovery.img.lz4
-- Decompressing: recovery.img.lz4
Detected format: [lz4]
Decompressing to [/data/user_de/0/com.topjohnwu.magisk/install/recovery.img]
-- Writing: system.img.lz4
! Process error
! Installation failed
</pre>

<hr/>

I'm trying to rebuilt the `tar` file with plain `img` files to see it it will work, instead of feeding it the original AP_... 'tar' .

**Comment by eladkarako** [comment]
I have extracted the `boot.img`, tar-compressed it in a unix compatible way with msys2:
`tar --format=ustar --create boot.img >boot.tar` moved it to my phone and patched it with the manager.

**Comment by eladkarako** [comment]
I think that patching the entire `AP_..` file, 
failed due to an insignificant disk-space for the entire file (its over 4 GB), 
I might have should have used my external-SD-card for that, 
that might be the reason the file got broken.....

I nice feature to add might be to pre-check for free disk-space for the entire operation...
or notify that the writing was failed due to low disk-space, 
--- and not to complete the packing to tar, as if everything was OK...
... that is very confusing.

BTW.
The extraction of just the `boot.img`, packing it to tar, patching it with the manager, 
moving it to the PC, and flashing it with ODIN (along of all the other files), 
then long 'recovery combination' to boot to samsung-recovery, clearing cache and factory reset, 
following by battery out, battery in, short 'recovery combination', (one by design extra reboot) and the system is UP as expected.

Since patching the `AP_...` file is causing so much problems, 
it might be nice to provide 'minimal patch' of just the `boot.img` (or tar), for an already installed phones whom just need root.

**Comment by topjohnwu** [comment]
Magisk will do all RMM/FileVault patches if your device is using the new system-as-root setup of Samsung (e.g. S10/Note 10).
If your device has insufficient free space, this is completely not an issue of Magisk.
