### ISSUE TITLE
Magisk 'installation' is missing after flash (shows installation -1)

### ISSUE THREAD

**Issue by eladkarako** [topjohnwu/Magisk#1857]
I had Magisk working for one boot, 
and then it bootloop for some reason so I've flashed back the original firmware.
I did wiped the cache and did a factory reset through the original recovery menu.

I now have plenty of disk-space to patch the complete `AP_...` from the firmware 
(see https://github.com/topjohnwu/Magisk/issues/1855)

But the manager does not the Install ("patch") menu item:
<img src="https://i.imgur.com/vKKmIex.jpg" />

how to get rid of this, 
bringing back the clean state again, allowing me to patch files once again?

**Comment by eladkarako** [comment]
factory reset (again) doesn't seems to fix the problem.
when I've flashed I even used `CSC_OMC_....` so the phone should have been wiped clean as well.

I don't have custom recovery to flash `Magisk-uninstaller`, 
and I don't understand why there isn't an independent 'patch' button, 
regardless of installation status in the first place, 
how may I patch the files manually? ("outside of the manager"?)

**Comment by topjohnwu** [comment]
Please follow proper bug report instructions

**Comment by Didgeridoohan** [comment]
@eladkarako From that screenshot it looks like you simply don't have an internet connection.

**Comment by eladkarako** [comment]
@Didgeridoohan You might be right, 

But I can 100% tell if that's true, since I've happen to flashed the `CSC_OMC` again (and did a cache/data wipe) during another testing (of another failed root method) and it happen to solved it, 
it now says again "not installed", 

I must say, having a more verbosed message such as "no internet connection", 
or at least mentioning in the wiki that <strong>green status with <code>-1</code></strong> in it really means "red status" (gray status?) with no internet connection. That's not intuitive.

maybe just setting the UI section to initially be grayed out, 
and only later setting it to be green/red depending on an actual check can be more informative.

Plus, nothing in the mechanisem of the program mentions that it requires internet-connection, 
to provide status of the locally-installed program, that not making much sense.

<hr/>

I'll put Magisk down for now, 
On my J400F/PIE - I can't seems to successfully patch and install anything but the official firmware again, anything else (putting a previously successfully-patched boot.img in ODIN `AP`) fails immediately. 

And although I've unlocked the OEM previously and never locked it again, 
the OEM (bootloader) entry won't show in the developer menu anymore, 
which makes me think the RMM/vault unlocking of Magisk did not fully succeed, 
and it got (timed-) locked again (several web-sources says it locks for 7 days).

I'll probably try again in 6 months, once more PIE rooting-related solutions will get more mature, 
currently non-works for me and my poor over-flashed J400F :]

I should have never upgraded from Oreo :|

**Comment by Didgeridoohan** [comment]
@eladkarako Just for clarification. The "-1" most likely just means you had messed up the installation, nothing else...

All that happens when the Manager doesn't have an internet connection is that the install buttons and the SafetyNet test doesn't show. Both of which needs a working internet connection. That's why I made my guess above.
