### ISSUE TITLE
[Pixel XL][Android 10]Can't Flash Modules

### ISSUE THREAD

**Issue by gudenau** [topjohnwu/Magisk#1858]
When attempting to install any module from the repo or internal storage the same error occurs `unable to extract zip file`. I've tried several different modules.

It seems that it's caused by `unzip` not liking the `j` flag.

Example log:
```
- Copying zip to temp directory
- Installing Busybox_for_Android_NDK-1.30.1(13020).zip
- Current boot slot: _a
- Device is system-as-root
unzip: invalid option -- j
usage: unzip [-d DIR] [-lnopqv] ZIP [FILE...] [-x FILE...]
! Unable to extract zip file!
! Installation failed
```

**Comment by topjohnwu** [comment]
There are something wrong with the busybox installation. Re-install Magisk to make sure the environment is properly setup

**Comment by gudenau** [comment]
Thank you for the prompt response, this has resolved my issue.

**Comment by gudenau** [comment]
@topjohnwu It seems like the BusyBox install regularly breaks itself. Can't figure out what the trigger is.

**Comment by Feda777Feda** [comment]
#

> When attempting to install any module from the repo or internal storage the same error occurs `unable to extract zip file`. I've tried several different modules.
> 
> It seems that it's caused by `unzip` not liking the `j` flag.
> 
> Example log:
> 
> ```
> - Copying zip to temp directory
> - Installing Busybox_for_Android_NDK-1.30.1(13020).zip
> - Current boot slot: _a
> - Device is system-as-root
> unzip: invalid option -- j
> usage: unzip [-d DIR] [-lnopqv] ZIP [FILE...] [-x FILE...]
> ! Unable to extract zip file!
> ! Installation failed
> ```https://github.com/topjohnwu/Magisk/issues/1858#issue-496572710
