### ISSUE TITLE
Magisk is unable to replace files in /product/fonts

### ISSUE THREAD

**Issue by danielhuang** [topjohnwu/Magisk#1860]
I created a module to replace certain system fonts with modified versions. However, they are not applied correctly. Files present in other directories are working correctly. 

The files are present in `/data/adb/modules/<module name>`.

I am using Magisk 19.4.

**Comment by skittles9823** [comment]
The best way to debug this would be to use the debug canary builds to get a log from magisk manager > logs > magisk tab so we can see if the files are bind mounting or not.

**Comment by topjohnwu** [comment]
Did you put your files in `<module_name>/system/product/fonts`?

**Comment by danielhuang** [comment]
Yes. I placed the files in both `/system/fonts` and `/system/product/fonts`.

**Comment by danielhuang** [comment]
I uploaded logs here: https://ipfs.yellowiki.xyz/ipfs/QmRE1hKgD1DSgowV59ni8T1VWkV3FLDLSoTNbv6TTbrpEg

I notice a line saying `opendir: /sbin/.magisk/mirror/product/fonts failed with 2: No such file or directory`. Could this be related to the issue I am facing?

`magisk-replace-product-sans` is the module I am testing.

**Comment by skittles9823** [comment]
I've gotten reports from about 3-4 more a only users on Q, testing QuickSwitch having issues with /product not getting mirrored. As in magisk not trying to mirror it to begin with.

**Comment by topjohnwu** [comment]
Fixed in 695e7e6da057bed18777220cf3b917b5563f8beb
