### ISSUE TITLE
Magisk Manager doesn't support android lollipop?

### ISSUE THREAD

**Issue by Emulatorer** [topjohnwu/Magisk#1861]
I always get bootloop when I'm using magisk manager as an alternative root account to supersu (sorry for my english)

I already did all the possible method but end up bootloop please can anyone answer my question 😅

**Comment by gloeyisk** [comment]
> I always get bootloop when I'm using magisk manager as an alternative root account to supersu (sorry for my english)
> 
> I already did all the possible method but end up bootloop please can anyone answer my question

Which phone? I tried in MIUI 9 that runs Android Lollipop both installer and boot just working fine. Could you provide the log while bootloop?

**Comment by topjohnwu** [comment]
It does. GitHub issues is not a place to ask for support

**Comment by Emulatorer** [comment]
It's ok now ^^
![Screenshot_20190923-211859](https://user-images.githubusercontent.com/37603562/65429028-06867f00-de48-11e9-9525-fbf9df8b7bfb.png)
