### ISSUE TITLE
No Root Request

### ISSUE THREAD

**Issue by DATL4G** [topjohnwu/Magisk#1862]
When I open an app that needs root privileges there is no query if I allow it or not.
I tried it in several root-checkers, a file explorer and in a terminal.
My installed modules work without problems.
When I go to superuser it just says: No apps found.
Battery optimization is turned off for the app.

**Device:** UMIDIGI One Max (European Version)
**Android Version:** 9 (Pie)
I'm using the [Phh AOSP 9.0 v119](https://github.com/phhusson/treble_experimentations/releases/tag/v119) (Vanilla arm64 A-only) 
And I'm not sure if this issue should be at #844 
(I had the same issue with another device on Stock ROM)
**Vendor:** Oreo
**Magisk Version:** Tried 19.3 and 19.4
**Magisk Manager Version:** 7.3.4
**SafetyNet Status:** 
- ctsProfile: false
- basicIntegrity: true

**Superuser Access:** Apps and ADB
**Multiuser Mode:** Independent

**Comment by Displax** [comment]
@DATL4G 
https://github.com/topjohnwu/Magisk/issues/844#issuecomment-503339709

**Comment by DATL4G** [comment]
Yeah that worked for my device with GSI but my device wich still has Stock ROM is still having this issue

**Comment by topjohnwu** [comment]
#844
