### ISSUE TITLE
Latest Canary still not working on S8(dreamlte) on LineageOS17

### ISSUE THREAD

**Issue by Aniums** [topjohnwu/Magisk#1865]
Based on what i read on twitter and stuff around here, Latest canary v19.5 should have added support for A-only devices on Android 10.0.
In my case, it's a LineageOS 17 build on my S8 with Exynos8895.

It bootlooped before on 19.4(which of course wasn't supported), but now it's a different type of loop.
Before(19.4) it would just show Samsung splash screen and stay on it, but now(19.5) it constantly turns on and off.
I tried some other stuff like boot image patching and using Magisk Uninstaller.

Anyway, there is no Log file in /Cache/

And yes, i used Debug build.

**Comment by topjohnwu** [comment]
This should fix your bug 3d4081d0af15af37a79a74151f9f7ffb0c8d8b6b

**Comment by Aniums** [comment]
It's still not working though :(
Tell me if you need me to upload something.
