### ISSUE TITLE
Latest canary (19403) not working on bullhead LineageOS 15.1

### ISSUE THREAD

**Issue by alvinhochun** [topjohnwu/Magisk#1866]
After installation of build 19403 and reboot it says "Magisk not installed" or something like that. Tried both direct install from app and zip install from TWRP.

It didn't seem to have created any `magisk.log` (all I could find were logs for working versions).

Build 19309 still works, and probably a canary version after that worked (can't verify). Stable build 19400 works.

(I can't find the other canary versions to test since @topjohnwu seemed to have nuked them from the magisk_files repo.)

**Comment by alvinhochun** [comment]
Actually, installing another version after installing 19403 it would state "stock boot image detected".

**Comment by topjohnwu** [comment]
Fixed in 3d4081d0af15af37a79a74151f9f7ffb0c8d8b6b
