### ISSUE TITLE
bootloop

### ISSUE THREAD

**Issue by ryty1** [topjohnwu/Magisk#1869]
System: emui9

Magisk version: 19403（canary）

Edxposed version: magisk-EdXposed-YAHFA-v0.4.6.0_beta(4469)-release

Ruri version:19.5

**Question** : phone **bootloop**  。

**PS** : brush in magisk will not bootloop. Only brush in  edxposed will bootloop. 

[logcat](https://pan.baidu.com/s/1WhEmUf_KhlY7Ux8Tca62OA)

**Comment by ryty1** [comment]
Plus: Only brush magisk will not bootloop. Only brush edxposed is bootloop.

**Comment by topjohnwu** [comment]
That is an module issue, not a Magisk issue

**Comment by martyfender** [comment]
It is an on going, EdXposed issue, I believe.
