### ISSUE TITLE
Error "Unable to repack boot image"

### ISSUE THREAD

**Issue by clayissimo** [topjohnwu/Magisk#1872]
Trying to manually install Magisk on Android 10 on a Pixel XL device, since TWRP seems to be broken for Android 10+Pixel XL (see https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1513 ).

Using MagiskManager-v7.3.4.apk, stock Pixel XL bootloader from Android 10, patch September 2019 (bootloader-marlin-8996-012001-1907011432.img), 

When trying to manually patch the error message "unable to repack boot image! Installation failed" is shown.

Also tried it with patch October 2018 (!) (bootloader-marlin-8996-012001-1808030001.img), same issue.

Is this a broken feature in 7.3.4 / 19400?

![Magisk Screenshot](https://user-images.githubusercontent.com/11587972/65579233-a7278c80-df77-11e9-8c03-945ff7d3dba0.jpeg)

Error log:

- Device platform: arm64-v8a
- Copying image to cache
1022+1 records in
1022+1 records out
1047368 bytes (0.9 M) copied, 0.018839 s, 53 M/s
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
PXA_BOOT_HDR
HEADER_VER      [0]
KERNEL_SZ       [0]
RAMDISK_SZ      [543450473]
SECOND_SZ       [1952804128]
EXTRA_SZ        [10]
RECOV_DTBO_SZ   [0]
DTB             [0]
PAGESIZE        [1852399476]
NAME            [to_recovery = %u && boot_into_hosd = %u
]
CMDLINE         [_into_hosd = %u
e version = %d 
]
CHECKSUM        [20696d616765207369676e6174757265203d20256420636865636b20696d6167652076657273696f6e203d202564200a]
Segmentation fault 
- Checking ramdisk status
- Stock boot image detected
- Backing up stock boot image
- Patching ramdisk
Add entry [init] (0750)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
PXA_BOOT_HDR
HEADER_VER      [0]
KERNEL_SZ       [0]
RAMDISK_SZ      [543450473]
SECOND_SZ       [1952804128]
EXTRA_SZ        [10]
RECOV_DTBO_SZ   [0]
DTB             [0]
PAGESIZE        [1852399476]
NAME            [to_recovery = %u && boot_into_hosd = %u
]
CMDLINE         [_into_hosd = %u
e version = %d 
]
CHECKSUM        [20696d616765207369676e6174757265203d20256420636865636b20696d6167652076657273696f6e203d202564200a]
Segmentation fault 
! Unable to repack boot image!
! Installation failed

**Comment by martyfender** [comment]
You should be patching the stock boot.img and not the bootloader, or are you using the wrong name when you actually are using the boot.img?

**Comment by skittles9823** [comment]
Nope. Pixels use boot.img the bootloader is in the factory image and the boot.img is inside the zip in the archived image.

**Comment by clayissimo** [comment]
@martyfender @skittles9823 , thanks for the hints. Could you also elaborate how to flash the boot.img using fastboot?

**Comment by clayissimo** [comment]
Okay, the answer is...

fastboot flash boot boot.img

Great, everything worked fine :)

Now if Magisk's patcher could give out a warning, that this is not a boot.img but the bootloader, that would be great (instead of indicating that everything is ok when saying "Stock boot image detected" etc.). Shall I start a feature suggestion?

**Comment by skittles9823** [comment]
The `stock boot image detected` prompt is for the current boot image already on the device, not the one that's being flashed. But yea, some more descriptive error messages would be useful to users.

**Comment by martyfender** [comment]
This should work on your device if you patch the boot.img instead of the bootloader image. I am almost certain that other Pixel XL users have been successful in doing this.

**Comment by repsorp** [comment]
Same error message when trying to update to last canary version

```
Repack to boot image: [new-boot.img]
Segmentation fault
! Unable to repack boot image!
! Installation failed
```

[magisk_install_log_2021-03-07T13_35_46Z.log](https://github.com/topjohnwu/Magisk/files/6097107/magisk_install_log_2021-03-07T13_35_46Z.log)
