### ISSUE TITLE
Error while installing Magisk through Magisk manager

### ISSUE THREAD

**Issue by Taz2303** [topjohnwu/Magisk#1873]
Hi, 
I'm trying to instal Magisk 19.3 through Magisk Manager Version: v7.3.4
and getting this error 
- Device platform: arm64-v8a
- Coping image to cache
- unpacking boot image
!unsupported/unknown image format
!installation failed

Any ideas how to solve it?

I have used

Stable Magisk Version: v19.3 (also tried Beta Magisk Version: v19.4)

**- Device platform: arm64-v8a
- Copying image to cache
1618+0 records in
1618+0 records out
1656832 bytes transferred in 0.004 secs (414208000 bytes/sec)
1085+1 records in
1085+1 records out
1111628 bytes transferred in 0.003 secs (370542666 bytes/sec)
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
! Unsupported/Unknown image format
! Installation failed**

I have also tried to instal it through TWRP which causing the phone to get stuck in bootloop to TWRP mode (the only way to get out of it is to flash the uninstall file Magisk-uninstaller-20190919.zip)

Phone is K20 Pro 

If there is any other details/info needed I'll be happy to provide

**Comment by topjohnwu** [comment]
Please upload you boot image

**Comment by osm0sis** [comment]
@Taz2303 try latest stable, also upload the boot.img

**Comment by osm0sis** [comment]
I just used latest Magisk Canary to patch miui_RAPHAELININGlobal_V10.4.8.0.QFKINXM_ae28a80a5c_10.0.zip boot.img without issue.

**Comment by Taz2303** [comment]
Hi @osm0sis  Much appreciation for your help and details.
I'll give it a try and hopefully it will work for me too.

**Comment by froilanmangeles570-lgtm** [comment]
Installation

Failed!

- Device platform: arm64-v8a

- Installing: R6687BB53suu-kitsune (27001)

- Processing zip file

! No boot image found

! Process error

! Installation failed
