### ISSUE TITLE
Unable to repack boot image from EMUI 10

### ISSUE THREAD

**Issue by twy2004** [topjohnwu/Magisk#1875]
I tried to root my mate 20 at EMUI 10.
but magisk report it could not repatch the recovery ramdisk.

recovery ramdisk img
https://drive.google.com/open?id=1wiI0MRbSjUx0C85Z27a66N_y36yA-7Wg

**Comment by twy2004** [comment]
BTW, I used lasted canary magisk.

**Comment by ashish1607** [comment]
Why was this issue closed? did magisk started rootin emui 10?

**Comment by randiean** [comment]
Why was this issue closed? did magisk started rootin emui 10?
