### ISSUE TITLE
Magisk hide apps disabled on rebooted for anything under android 8

### ISSUE THREAD

**Issue by 0xC1A551C** [topjohnwu/Magisk#1877]
I have installed the latest magisk 19.4 and the latest magisk manager that goes along with it on 3 of my android 7.1.2 devices. Every time I hide an app it unhides on reboot!

However, my android 9 devices work fine no problem.  Any idea?

Previous version of magisk work fine on 7.1.2

**Comment by martyfender** [comment]
logs?
https://www.didgeridoohan.com/magisk/MagiskHelp
