### ISSUE TITLE
Closed issue #1865 is still a problem

### ISSUE THREAD

**Issue by Aniums** [topjohnwu/Magisk#1878]
I already commented there that it's not fixed, but  the issue is still closed so iwanted to make sure that you see it.

In case you already saw it, sorry for opening another issue :/ .

Nothing really changed in the way it bootloops.

**Comment by Aniums** [comment]
Someone told me that
"The current SaR setup is too mount system early on dts".

**Comment by topjohnwu** [comment]
The latest canary build could solve your issue as proper QCDT patching support is added
