### ISSUE TITLE
Magisk Hide: broken fingerpint on Huawei P9/P9 Lite/P9 Plus/P10/Mate 9/Honor 8/6X

### ISSUE THREAD

**Issue by OldDroid** [topjohnwu/Magisk#188]
Everything seems to be fine after installation finished, device reboots, safetynet works - only fingerprint is now broken somehow. I'd tried to reproduce the issue by restoring everything back to latest stock (fingerprint working like it should) and flashing magisk 12 afterwards (Result: fingerprint broken)
EDIT: problem is solved after turning off Magisk Hide.
Since this is still considered as an issue it will remain open.

Logcat:
[https://pastebin.com/Wm7QtesH](https://pastebin.com/Wm7QtesH)

Stock boot.img from latest Nougat rom:
[https://drive.google.com/open?id=0BxWP2gF_0Bd_Z18wLVZnRHJLTXc](https://drive.google.com/open?id=0BxWP2gF_0Bd_Z18wLVZnRHJLTXc)

**Comment by Ante0** [comment]
Same thing happens on Mate9, but only if you enable Magisk Hide.

**Comment by Gondost** [comment]
See also: https://github.com/topjohnwu/Magisk/issues/120

I tried a build of V13 and the fingerprint issue persists on that version as well. Disabling Magisk Hide also works to restore functionality.

**Comment by ericmota** [comment]
hey guys, I have a p9 and I can´t get safetynet works, also I have the problem with the fingerprint.
what are the steps to install magisk to works fine?
I uninstalled magisk, tried to pass safetynet and stills I got fail on safetymismatch
L09 c438b386 thanks in advance and sorry for my english

**Comment by Ante0** [comment]
@Gondost my PR does nothing to fix fingerprint. It just adds fileencryptioninline to be looked for when decrypting.

**Comment by Gondost** [comment]
@Ante0 right, that I know, I was just asking whether you had some feedback on what we could provide to topjohnwu to get the fingerprint problem fixed.

**Comment by Gondost** [comment]
More info for @olddroid & @topjohnwu

Tested on V12: When you turn MagiskHide off and reboot, the FPS works. Once booted, if you turn MagiskHide on, it works and succeeds at passing SafetyNet, and FPS works. If you reboot, it breaks FPS again.

**Comment by fabianw931** [comment]
@Gondost any possibility to enable/disable magiskhide automatically with something like tasker?

**Comment by MLGHamsterFIN** [comment]
@fabianw 931 If the scripts for enabling magisk hide are avaivable and you can run scripts as root on tasker, that should work. You could propably also use automate wich is free.

**Comment by Ante0** [comment]
Fingerprint works again on Mate 9 with Magisk v13.1, with Hide enabled and after rebooting

**Comment by wwarne** [comment]
I have P10 plus and with Magisk v14 SafetyNet check fails after enabling fingerprint. 
I tried turn MagiskHide off, reboot, and turn it on, but SafetyNet check fails again. (Beside that everything works great).
I also tried to disable fingerprints (delete all prints and switch screen lock from PIN to Pattern). It didn't help.
