### ISSUE TITLE
pixel XL Android 10 magisk root is incomplete

### ISSUE THREAD

**Issue by vbmnvbn** [topjohnwu/Magisk#1881]
pixel XL Android 10 magisk root is incomplete

Show already ROOT
but Unable to delete system app

**Comment by topjohnwu** [comment]
The system partition is formatted as read-only, nothing I can do.
https://twitter.com/topjohnwu/status/1170404631865778177

**Comment by vbmnvbn** [comment]
OK thanks 
I expect  you can solve it.

**Comment by skittles9823** [comment]
It's not something that needs to be solved. You can use the terminal debloater if you wish to remove system apps.

**Comment by vbmnvbn** [comment]
Magisk

> It's not something that needs to be solved. You can use the terminal debloater module if you wish to remove system apps.

I just want to see if it is completely root

**Comment by vbmnvbn** [comment]
how to get Magisk v19.5 ...  :(

**Comment by martyfender** [comment]
https://github.com/topjohnwu/magisk_files/tree/canary
