### ISSUE TITLE
Modification: Check if module is already downloaded

### ISSUE THREAD

**Issue by b3nnee** [topjohnwu/Magisk#1882]
#Hello, 
Great job with Magisk. 
I have a small request that had nothing to do with Magisk hide. 

Sometimes one needs to run the installation of an already downloaded module to make changes perhaps. Currently Magisk redownloads the entire module again even though it already exists in the download folder. In a future update, kindly, check if a file exists before redownloading it if it doesn't exist. If it exists, run the install directly.

Thanks. I hope I was clear with the above request.

**Comment by topjohnwu** [comment]
It is intentionally removed as a feature because the installer scripts could be updated.
If you want to reuse an existing zip, in the modules section, press the "+" floating action button to manually select a zip to install.

**Comment by b3nnee** [comment]
Great thanks a lot for pointing that out.

Cheers
