### ISSUE TITLE
Magisk 19.4 thinks it's installed, but it's not

### ISSUE THREAD

**Issue by theslats2** [topjohnwu/Magisk#1883]
Hey topjohnwu,

I'm having an issue on a Samsung Galaxy Tab A 10.1 (2016) (SM-T580) where I've installed Magisk 19.4 on LineageOS 17 Beta and it's saying Magisk Installed (-1), but it's not installed.

I used the LineageOS 17 Beta from XDA and clean flashed with OpenGapps.

![Screenshot_20191001-001646_Magisk_Manager](https://user-images.githubusercontent.com/50344900/65887333-1a4e5a00-e3e1-11e9-986e-47dd9fefeb05.png)

**Comment by topjohnwu** [comment]
Connect to internet. It is a bug in the UI
