### ISSUE TITLE
Banner AndroidTV

### ISSUE THREAD

**Issue by bubuleur** [topjohnwu/Magisk#1886]
[TV-Banner AndroidTV.zip](https://github.com/topjohnwu/Magisk/files/3685483/TV-Banner.AndroidTV.zip)

Files to replace your base to have a shortcut on Android TV
Thank you

**Comment by xerta555** [comment]
> Files to replace your base to have a shortcut on Android TV

If i translate, u want the support of Android TV?

**Comment by bubuleur** [comment]
Hello,
Yes I am not English I am using a translator can you help me I would like a shortcut on androidtv that I created for the next magisk updates
Thank you very much

**Comment by xerta555** [comment]
> Yes I am not English I am using a translator can you help me I would like a shortcut on androidtv that I created for the next magisk updates

As i have never used Android TV, i don't know if John have add the support (at least the homescreen icon) for Android TV.
I am not sure, but it seems to me that Magisk need an addition or modification in the AndroidManifest.xml file of Magisk Manager.

**Comment by bubuleur** [comment]
Okay it's not possible to do so? because I do not know
Thanking you

**Comment by topjohnwu** [comment]
Sorry, but currently there is no plans to support Android TV yet

**Comment by sorryusernameisalreadytaken** [comment]
> Sorry, but currently there is no plans to support Android TV yet

@topjohnwu what is 868 days later :D
Is there a chance to show androidTV some love? I use Magisk now since the first time I root my foster nvidia shield TV.

DPAD-Support is quite okay but the missing launcher-icon is in AndroidTV always a problem. It is always time consuming to find and start magisk via app's menu.
