### ISSUE TITLE
Installation steps - Entire package error

### ISSUE THREAD

**Issue by ArmynC** [topjohnwu/Magisk#1887]
**Hey**, if I try to install _magisk_patched.tar_ alongside _BL_, _CP_ and _HOME_CSC_, after the reboot, in the recovery menu it shows an error. But if I try just with the _AP_, it works fine.

**Comment by HafizZiq** [comment]
> **Hey**, if I try to install _magisk_patched.tar_ alongside _BL_, _CP_ and _HOME_CSC_, after the reboot, in the recovery menu it shows an error. But if I try just with the _AP_, it works fine.

Its because they are different
BL - bootloader
CP - baseband
And
CSC - Country Sales Code

So, just AP works as universal flasher, other than that, not, because they have their part for flashing

**Comment by ArmynC** [comment]
Yeah, I know. But this is written in the guide and isn't working. A modification is needed?

**Comment by topjohnwu** [comment]
Follow the instruction properly. Everyone is able to root their devices properly, include myself.

**Comment by ArmynC** [comment]
I did root my phone. But I meant the fact that the instructions make the users to install the patched magisk AP alongisde the BL, CP and CSC from the original firmware, but isn't working, resulting in a bootloader error. If this is the case on Galaxy S10, every user that do the instruction as noted will see an error. Even the other tutorials make show us to install just the patched AP.
