### ISSUE TITLE
MagiskHide and Work profile (Shelter/Island)

### ISSUE THREAD

**Issue by corna** [topjohnwu/Magisk#1888]
Hi,

I'm trying to enable MagiskHide for an app installed in the "Work" profile, however the app itself is not listed in Magisk unless it is also installed in the "Personal" profile. If it is installed in both profiles and MagiskHide is enabled for it, then the app works correctly (i.e., can not detect root) on both profiles.

Is it possible to list the apps from all the profiles in the MagiskHide section?

Thanks

**Comment by impulsiva** [comment]
Magisk comes with "Only owner has root access" option selected, and work profile is being considered as a real profile, so in work profile apps won't be able to get root access and Magisk's goodies, also they can't detect root. This is not an issue, just a misunderstanding.

**Comment by topjohnwu** [comment]
@corna install Magisk Manager in the work profile, and allow it to gain root access in the device owner profile.

**Comment by corna** [comment]
I have already tried it, still the app refuses to run unless it is also hidden in the main profile.

**Comment by chilliger** [comment]
I can confirm. There is no way to hide an app in work profile other than installing it also in the personal one.

**Comment by corna** [comment]
@topjohnwu Your suggestion does not work unfortunately, any other suggestion?

**Comment by ChrisMiller94** [comment]
I found a solution, which may work for who's have problem with MagiskHide when workprofile is in use.

1.) Hide Magisk Manager and turn on MagiskHide
2.) Be sure, Magisk is hided correctly in personal profile and not detected by Google Play
3.) Hide Magisk for all work profile app, ie. Outlook, Microsoft Intune, Authenticator etc.
4.) Open Microsoft Intune, select your device and tap on "Check device settings"
5.) After check completed you need to see "In Compliance" at the Device Setting Status section

After all point is done, you can use your work profile apps, without detecting root and failed to start

Tested on Xiaomi Mi 10T Pro, need to work on all Xiaomi maybe on other OEM's devices.

**Comment by dzver123** [comment]
Tried magisk hide - did not help, neither enforce deny list. 

Installed Shamiko module to hide root: https://github.com/LSPosed/LSPosed.github.io/releases
Added app in magisk > settings > deny list (have not enabled DENY LIST ENFORCEMENT) 
Hid magisk app from settings as well
Installed https://github.com/kdrag0n/safetynet-fix 

None of this helped. Once I launch Shelter/Island, I get the message "cannot create work profile"

Any advice?
