### ISSUE TITLE
Magisk - Google services crash

### ISSUE THREAD

**Issue by ArmynC** [topjohnwu/Magisk#1889]
*Hey*, I saw that the Google services didn't work (ex. Google Play, G-Mail, YouTube, Google Maps ...) and some apps (ex. MEGA, Action Widget...)

I did wipe the system, install a new firmware and re-rooted and all was good. After making some settings and installing some modules I got again a Google Service crashed box. I have uninstalled all modules and reboot the phone but to no avail.

![IMG-20191004-WA0008](https://user-images.githubusercontent.com/16375271/66188524-201d9700-e690-11e9-9d62-b27ab981ef5a.jpg)
![IMG-20191004-WA0009](https://user-images.githubusercontent.com/16375271/66188526-201d9700-e690-11e9-998a-1f11094491be.jpg)

And the "Google Account" menu isn't working alongside the SafetyNet check (scan loop)

![IMG]( https://i.imgur.com/UCkuxVZ_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by martyfender** [comment]
https://www.didgeridoohan.com/magisk/MagiskHelp

**Comment by ArmynC** [comment]
[Log_2019-10-04_20-34-44.txt](https://github.com/topjohnwu/Magisk/files/3691715/Log_2019-10-04_20-34-44.txt)

**Comment by ArmynC** [comment]
Maybe because of [microG](https://github.com/Magisk-Modules-Repo/microg_installer) !?

**Comment by martyfender** [comment]
> Maybe because of [microG](https://github.com/Magisk-Modules-Repo/microg_installer) !?

My best guess would be that your problem would be caused by microG.

**Comment by topjohnwu** [comment]
From your report, the issue is either in MicroG, or some of your modules
