### ISSUE TITLE
Magisk not hiding specific app

### ISSUE THREAD

**Issue by JaFranchise** [topjohnwu/Magisk#189]
Magisk was passing safetynet but would not hide root from the AFL Live app. This was using xiaomi redmi note 3. The hide had worked on other roms for the same device.

The app would always say root was detected. I stumbled across some instructions specific to this app, and the way for root to be hidden was to change the build.prop:

I had to change: ro.build.tags=test-keys
to: ro.build.tags=release-keys

I'm not sure if this is a problem with Magisk, it's probably more of a problem because of the ROM. Nonetheless I thought I'd pass it on if it was useful information.

**Comment by Didgeridoohan** [comment]
It's not a problem with Magisk... And it's also known that some apps do not like "test-keys". Thank you for reporting though, but it's not really something to open a GitHub issue about.

In future versions of Magisk Manager you'll be able to change props like that in a GUI.
