### ISSUE TITLE
Material Theming for Magisk Manager

### ISSUE THREAD

**Issue by Rakleed** [topjohnwu/Magisk#1892]
Please make the design of the application in the style of Material Theming (this is an extension of Material Design, which was introduced at Google I/O 2018). Material Theming lets you fine tune Material Design, and I like Material Theming more than the older version of Material Design. Useful links: https://material.io/design/material-theming/overview.html, https://material.io/develop/android/docs/theming-guide/.

**Comment by MrBaNkS** [comment]
Lol how is this an issue? 😅😆🤔

**Comment by xerta555** [comment]
> Lol how is this an issue? 😅😆🤔

Effectivly, it would have more room in the requests section...

**Comment by topjohnwu** [comment]
@diareuse is already working on a redesign.
GitHub issues are used for me to track issues, so I'll close this.

**Comment by diareuse** [comment]
@Rakleed the redesign as already taking place, as John pointed out.

---

I'm making sure that the themes are extendable and can be super-fine-tuned so everybody can play around with Substratum, yet provide great experience out of the box. Please be patient as designing system like this takes enormous amounts of time. 🙏
