### ISSUE TITLE
Magisk Manager: Fingerprint UI infinite loop

### ISSUE THREAD

**Issue by aowenson** [topjohnwu/Magisk#1894]
Magisk Manager version 7.3.4

Steps to reproduce:
1 Enable fingerprint authentication
2 Toggle SU status of an app from 'off' to 'on'
3 Dialog appears asking for fingerprint authentication to enable SU. Click 'close' on dialog to deny the request.

Current outcome:
4 Another dialog appears asking for fingerprint authentication for toggling SU status to 'off', when it was off to begin with!
5 Click close, taken back to step 3, infinite loop, only way out is to authenticate.

Expected outcome:
4 Dialog actually closes when I click close, app SU status is unchanged.

Why is this important? Maybe it is possible for malware to request SU access, generating the fingerprint authentication dialog. If I am not expecting this, and click close several times in an infinite loop, then it becomes impossible for me to guarantee that I deny SU access. I will have to guess which dialog corresponds to 'off' and authenticate that, so I could end up granting root access to malware against my consent.

**Comment by RonanTetsu** [comment]
Important indeed, and quite a find.. I want to ask, why is fingerprint authentication used anyway? Jw..

**Comment by aowenson** [comment]
If malware can access the Superuser page and attempt to give itself root, then having fingerprint authentication enabled prevents this from being silently successful.

**Comment by diareuse** [comment]
Fixed via https://github.com/topjohnwu/Magisk/commit/d8d72f92b3fd5c48cdff4b4c16db405c41a065f8
