### ISSUE TITLE
the new magisk 19.4+will make system locked

### ISSUE THREAD

**Issue by a2212997715** [topjohnwu/Magisk#1895]
android ：10 miui11
phone：redmik20pro
Version 19.2magisk
Modified system can be mounted，
but 19.4 or19.5 can't

**Comment by martyfender** [comment]
The way I understand it, the system can no longer be modified in Android 10, except by doing it systemlessly with, for example, a Magisk module.

**Comment by topjohnwu** [comment]
Please read release notes.
If your device is system-as-root, you need to remount `/` instead of `/system`
