### ISSUE TITLE
Unable to patch my boot image

### ISSUE THREAD

**Issue by ockysaurus** [topjohnwu/Magisk#1898]
Hi I'm unable to patch my boot image (on Android 9) with today's canary update. Sorry I can't provide logs because top bar of patch tool is broken somehow.
Video showing my issue: https://youtu.be/GlRQ3YKCk18

**Comment by martyfender** [comment]
https://www.didgeridoohan.com/magisk/MagiskHelp

**Comment by ockysaurus** [comment]
I already tried only logs are from booting magisk up

**Comment by ockysaurus** [comment]
Issue with topbar is fixed so i can provide logs
[magisk_install_log_2019-10-08T055508Z.log](https://github.com/topjohnwu/Magisk/files/3700644/magisk_install_log_2019-10-08T055508Z.log)

**Comment by martyfender** [comment]
There is a new, just released, Canary build, which may fix your issue.

**Comment by ockysaurus** [comment]
The log is from 19406 canary update

**Comment by topjohnwu** [comment]
@ockysaurus are you using a Huawei device?

**Comment by ockysaurus** [comment]
Yes

**Comment by topjohnwu** [comment]
@ockysaurus may you upload a dump of the partition `/dev/block/mmcblk0p33`?

**Comment by ockysaurus** [comment]
GitHub has 10 mb limit so I uploaded to another site 
https://ufile.io/2kqenzy5
