### ISSUE TITLE
Finger print stopped working after v16

### ISSUE THREAD

**Issue by masterlemmi** [topjohnwu/Magisk#1901]
I have a Huawei trt-l21a.
With magisk v.16  i can see the Finger Print Management on my settings.
With higher versions, I don't see it anymore and I can't use the finger print scanner to unlock my phone.

Huawei y7prime (TRT-L21A)
EMUI Version 5.1
Android Version 7.0

LOGCAT : 
[lgocat.txt](https://github.com/topjohnwu/Magisk/files/3700763/lgocat.txt)

[magisk.log](https://github.com/topjohnwu/Magisk/files/3700757/magisk.log)

**Comment by topjohnwu** [comment]
Please try the latest canary and see if that fix your issue (most likely it will).
If not, then I do not have the interest nor ability to fix this issue, as you are running a super old EMUI build that I have no idea how things work back then.
