### ISSUE TITLE
Unable to patch Exynos DTBH device trees

### ISSUE THREAD

**Issue by Aniums** [topjohnwu/Magisk#1902]
I did all the usual procedures by flashing it normally, using debug and release and uninstaller, and it's still the same, but using the manual image patching now makes the phone stay on the bootloader logo.
Of course, my dumbass decided to leave it on for a few minutes and now i have a (probably) permanent mark that is hard to notice but still there. Lmao.

Anyway, please let me close this issue myself in case of  another attempt to fix it that doesn't work, so to not open one every time.(if it's a problem).

AgaIn, a comment from one of my devs was:
 "The current SaR setup is to mount system early on dts".

I don't know if that helps you with any though xD

Anyway, thanks fir actually helping out in the first place.

**Comment by topjohnwu** [comment]
If installing Magisk bootloops your device, then I'm pretty sure the issue does not lie in Magisk.
Is the ROM you are using a GSI ROM? Magisk does not support GSIs as they do not follow normal Android systems, in order for it to have maximum compatibility, tons of non standard hacks are added and no consideration was added to make it not conflict with Magisk's assumption.

If you are using an GSI, please close this issue as I will not attempt to fix non standard setups (#844)

**Comment by Aniums** [comment]
I not using a GSI :/

**Comment by topjohnwu** [comment]
@Aniums please upload your boot image

**Comment by Aniums** [comment]
Here you go:

https://drive.google.com/open?id=17zquR2ADT5MwdpmQV1pRGCZUVftxK0qC

**Comment by topjohnwu** [comment]
Thanks for the image man, the next canary will definitely fix your issue :)

**Comment by topjohnwu** [comment]
@Aniums new canary is released, please check it out!

**Comment by Aniums** [comment]
@topjohnwu i am faster than lightspeed so i already installed it.
It works AWOOOOOOOO.
THANK YOU VERY MUCH!
