### ISSUE TITLE
Magisk won't add overlay dir to /vendor

### ISSUE THREAD

**Issue by tsynik** [topjohnwu/Magisk#1903]
Since probably 18.x release, I have issues with Magisk modules which contains /system/vendor/overlay/... data. On current device, /vendor is separate partition, and module have /system/vendor/**app**/xxx, /system/vendor/**overlay**/yyy files. There is no overlay dir in /vendor partition on device. After installing module with Magisk 19.3 I have both **app** and **overlay** dirs in /data/adb/modules/module/system/vendor, but only contents under **app** applied to /vendor (this dir exists in /vendor partition). With Magisk 19.4 I only have **app** dir under data/adb/modules/module/system/vendor after module install. Probably there is some bug in current logic.

**Comment by topjohnwu** [comment]
Because there is no `overlay` folder in your `/vendor`, due to bootloop protection, any module adding files/directories in mount point roots (e.g. `/system`, `/vendor`, `/product`) will be ignored.

This is not a bug, but expected behavior.

**Comment by tsynik** [comment]
So, there is no way to add any folder to /vendor root?

**Comment by skittles9823** [comment]
Generally devices without /vendor/overlay will use another dir like /product/overlay or /system/overlay. It's up to the module developer to add checks to change which directory they go into.

**Comment by tsynik** [comment]
There is no any overlay dir in ROM by default. If we talk about Runtime Resource Overlays, the must reside in /system/vendor/overlay directory: https://github.com/pratik98/Runtime-Resource-overlay-Target-Package
