### ISSUE TITLE
Failed to install Magisk on Pixel 1 QP1A.191005.007.A1

### ISSUE THREAD

**Issue by Icenowy** [topjohnwu/Magisk#1904]
Magisk version: v19.3
Magisk Manager version: 7.3.4

When trying to use "Install to the other slot" method on QP1A.190711.020 to install on OTAed QP1A.191005.007.A1,  I get `Unable to download bootctl` error. Re-trying shows `Magisk patched boot image detected`. Trying to force reboot just drops back the the original slot with QP1A.190711.020.

Trying to patch manually and flash via fastboot leads to bootloop without adbd active.

**Comment by Icenowy** [comment]
Patching QP1A.190711.020 boot with the same Magisk and MM version works.

**Comment by topjohnwu** [comment]
Without any logs, I can't know the issue you experienced.
Anyways, I updated the commit hash within the app so in case it was failing using the old links.
