### ISSUE TITLE
Support Q recovery

### ISSUE THREAD

**Issue by YoDevil** [topjohnwu/Magisk#1905]
In Q aosp recovery uses /system to store recovery binaries and configs (/system/bin, /system/etc).
It expects system to be mounted to /mnt/system instead, and likewise vendor to /mnt/vendor.

Magisk install script is incompatible since it tries mounting to /system

**Comment by topjohnwu** [comment]
What is incompatible about that though? Magisk will directly mount the raw device block to where it should be (`/system`, `/vendor`), and it does not need anything from the recovery as all tools required is all bundled with the installer.

**Comment by YoDevil** [comment]
Well you can't mount on /system when /system contains recovery itself

**Comment by topjohnwu** [comment]
Why? It's just a folder, and any folder can be used as a mountpoint.

**Comment by YoDevil** [comment]
I believe it is caused by the mounting, but i don't know the reason:
```
[   46.924898] Archive:  /sideload/package.zip
[   46.924943]   inflating: META-INF/com/google/android/update-binary
[   46.924958]   inflating: META-INF/com/google/android/updater-script
[   46.924973]   inflating: arm/magiskinit
[   46.924988]   inflating: arm/magiskinit64
[   46.925002]   inflating: arm/magiskboot
[   46.925016]   inflating: x86/magiskinit
[   46.925030]   inflating: x86/magiskinit64
[   46.925044]   inflating: x86/magiskboot
[   46.925058]   inflating: common/magisk.apk
[   46.925072]   inflating: common/boot_patch.sh
[   46.925086]   inflating: common/util_functions.sh
[   46.925100]   inflating: common/addon.d.sh
[   46.925114]   inflating: chromeos/futility
[   46.925139]   inflating: chromeos/kernel_data_key.vbprivk
[   46.925153]   inflating: chromeos/kernel.keyblock
[   47.079760] Segmentation fault
[   47.232974] mount: mounting /system on /system_root failed: Invalid argument
[   47.236984] mount: mounting /system_root/system on /system failed: No such file or directory
[   50.386796] mount: can't read '/etc/fstab': Too many symbolic links encountered
[   50.691702] E:Error in /sideload/package.zip (status 1)
```
Notice the Segmentation fault.

I can try providing a snapshot of the Lineage 17.0 recovery (based on aosp Q recovery) for HTC M8 if you're willing to look into it.

**Comment by CaptainThrowback** [comment]
@YoDevil

If this is on an M8, have you tried using my unofficial TWRP with SAR support? I don't have any issue flashing Magisk in that TWRP at all.
