### ISSUE TITLE
Possible issue with Motorola G7

### ISSUE THREAD

**Issue by groston** [topjohnwu/Magisk#1906]
As previously reported on xda-developers:

We got a new Moto G7 for my wife and following the instructions here https://www.thecustomdroid.com/install-twrp-root-moto-g7-plus-guide/, I successfully rooted the phone. However, there was a security update that needed to be installed, so with some great advice from ptn107, see https://forum.xda-developers.com/moto-g7/help/invalid-zip-file-format-trying-to-t3977463, I flashed the updated ROM onto the phone. (Note that I omitted 'fastboot erase userdata'. Also note that the warning message 'is-logical:<partition>: not found' was seen for all flash commands.)

The phone booted properly after the update, so I then went through the exact same rooting steps that had worked previously. However, this time, the phone gets stuck in a boot loop. I reflashed the ROM and can boot successfully, but the phone is no longer rooted. (I have tried this twice, with Magisk 19.3 and 19.4 - same result.)

Any ideas as to what I may be doing incorrectly? More importantly, what is the best way forward?

**Comment by topjohnwu** [comment]
You might have some incompatible modules installed. The easiest way is to use a custom recovery to remove all modules (`/data/adb/modules`)
