### ISSUE TITLE
Magisk Hide may should hide root for Download Manager and Downloads by default

### ISSUE THREAD

**Issue by yangzhaofeng** [topjohnwu/Magisk#1910]
I met a problem of Download Manager on my pixel after it upgraded to Android 10 and this leads to the unavailability of Google play and some apps. Here is my solution including Magisk Hide.

* Walk a far way and drop empty milk box into recyclable garbage bin.
* Hide root for Download Manager and Downloads in Magisk Hide.
* Disable both system apps in settings and clear their data.
* Reboot my phone and then enable them.

I am not sure which step works. But if it is the step of hiding root for both apps that works, Magisk Hide should hide root for them by default.

**Comment by topjohnwu** [comment]
No, they shouldn't, and you should not do that.
I'm also running a Pixel device with Android 10, and I experienced no issues whatsoever.
