### ISSUE TITLE
Phone soft reboots after a module or magisk update.

### ISSUE THREAD

**Issue by thanuj10** [topjohnwu/Magisk#1911]
Im using the latest Magisk Canary and I've noticed that whenever I update magisk or one of my installed modules, The phone boots and after 5 seconds it immediately does a soft-reboot.
After the soft re-boot though, The phone runs fine and there are no reboots unless I ask it to.

Device: Nokia 6.1 Plus
Android: 9.0/Pie, Running on the September patch
Magisk Version: 19.5-c42a51dc
Magisk Manager Version: 7.3.4-c42a51dc

[magisk_log_20191009_082055.log](https://github.com/topjohnwu/Magisk/files/3705382/magisk_log_20191009_082055.log)

**Comment by osm0sis** [comment]
Still an issue with v20 stable or latest Canary?

**Comment by thanuj10** [comment]
Not so far. So I'm assuming its fixed.

**Comment by osm0sis** [comment]
Go ahead and close the issue then. :+1:

**Comment by thanuj10** [comment]
Im sorry to bring this up again but the phone rebooted this morning again after I installed a module.
This is on V20 stable. I did a clean installation of Magisk on a fresh installation of the Stock ROM too.

**Comment by osm0sis** [comment]
Fresh log?

**Comment by thanuj10** [comment]
@osm0sis Here you go, This happened after I updated the Debloat module. (The crashes don't seem to be related to any soecific module)
[magisk_log_20191019_134715.log](https://github.com/topjohnwu/Magisk/files/3746404/magisk_log_20191019_134715.log)

**Comment by osm0sis** [comment]
You should also reopen this issue if it's ongoing for you.
