### ISSUE TITLE
Newest version of Magisk (19.4) causes bootloop with EdXposed

### ISSUE THREAD

**Issue by jakob1379** [topjohnwu/Magisk#1913]
Hello there! After removing all modules and installing separately and it seems consistent I have found that when I install Riru-core and Riru-EdXposed through Magisk, my samsung s9+ it sent into an infinite boot (not a direct boot-loop).

**Comment by martyfender** [comment]
From everything I have read, that is an EdXposed issue and not a Magisk issue.

**Comment by jakob1379** [comment]
Great. I will post it in there instead!
