### ISSUE TITLE
Magisk Manager v7.3.5 (243) crash on Settings section

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#1915]
Hi,

After having updating Magisk Manager from 7.3.4 to v7.3.5 version and Magisk from the 19.4 last Canary build to Magisk v20 (new version of today), Magisk Manager crash when i go in the Settings section.

Basicaly, Magisk Manager display it Settings window during arround 1 seconds and crash immediatly.

This issue happen even after having wype data for the Manager.

Apparently, from the logcat:
`10-11 22:55:21.469  5892  9469 W PackageManager: Unknown permission android.permission.FOREGROUND_SERVICE in package com.topjohnwu.magisk`

[logcat.txt](https://github.com/topjohnwu/Magisk/files/3719660/logcat.txt)

The `FOREGROUND_SERVICE` is an unknow permission..

My device:
- LG H870 (G6 Internal variant)
- Resurection Remix v5.8.5 (7.1.2)

The strange thing is that it seems to me that this service is already being used by other applications that I use on a daily basis without any problems.

If another logfile is needed, tell me i will send it here.

Tx in advance.

**Comment by topjohnwu** [comment]
The bug lies in Google's AndroidX support library, I dunno how I can fix that...

**Comment by topjohnwu** [comment]
And also, the bug is not the unknown permission

**Comment by xerta555** [comment]
> The bug lies in Google's AndroidX support library, I dunno how I can fix that...

Ah...it's a nuisance for all devices that will have an Android version lower than X

> And also, the bug is not the unknown permission

From wich line in the logfile do u have see that?

**Comment by topjohnwu** [comment]
@xerta555 
AndroidX is the name of Google's official support library, it is not a specific Android version.
May you try this APK out?
https://www.dropbox.com/s/levdw5l0u0lfu1u/app-release.apk?dl=0

**Comment by xerta555** [comment]
> AndroidX is the name of Google's official support library, it is not a specific Android version.
May you try this APK out?
https://www.dropbox.com/s/levdw5l0u0lfu1u/app-release.apk?dl=0

Ah ok, about your apk it works again without crashing, i guess a second logcat file wouldn't be too much for you?

Just installed the last 20.1-59fd38bb (20001) Canary version from the Manager and rebooted my device, it continue to works like a charm.

**Comment by topjohnwu** [comment]
Hm? So the latest canary works, but not the release one? That's odd

**Comment by xerta555** [comment]
> Hm? So the latest canary works, but not the release one? That's odd

The bug started to appear after I updated Magisk Manager to the latest version you released today (not Magisk itself).

**Comment by topjohnwu** [comment]
So please tell me what is working, you are confusing me.
1. v7.3.5 from the stable/beta channel
2. The one on the canary channel
3. The APK I just gave you the link to

**Comment by xerta555** [comment]
> So please tell me what is working, you are confusing me.

Today i do theses steps:
- I check your Twitter and see your Update post concerning your v20
- I open Magisk Manager v7.3.4 (i was on the Canary channel)
- I didn't see the v20 Canary update available (for the Manager and for Magisk, nothing)
- I had to switch manually from the Canary channel to the Beta channel to see the 2 updates (for the Manager and for Magisk)
- I have updated Magisk Manager from the v7.3.4 to v7.3.5
- I have opened Magisk Manager v7.3.5
- I tried to go to the Settings section and Magisk Manager and it started crashing

**Comment by topjohnwu** [comment]
You don't need to tell me what you've done, please just test the 3 APKs and report which is working, which is not.

**Comment by xerta555** [comment]
> The APK I just gave you the link to

This one works fine for me.

**Comment by xerta555** [comment]
I just have test the last apk from stable/beta channel, it crash on Settings section.

And the one on the Canary channel crash on Settings section too.

> May you try this APK out?
https://www.dropbox.com/s/levdw5l0u0lfu1u/app-release.apk?dl=0

=> Only the one you have uploaded to Dropbox works fine on my device.

**Comment by topjohnwu** [comment]
Cool, thanks

**Comment by xerta555** [comment]
If you want i test another apk or another logfile, tell me 👍

**Comment by martyfender** [comment]
> @xerta555
> AndroidX is the name of Google's official support library, it is not a specific Android version.
> May you try this APK out?
> https://www.dropbox.com/s/levdw5l0u0lfu1u/app-release.apk?dl=0

Just out of curiosity, what is changed in this that got rid of the crash? I did not have any problems with the current Canary on my Android 6.0.1 Nextbook Ares 8A tablet with the settings crashing the app.

**Comment by topjohnwu** [comment]
@martyfender I downgraded the recyclerview library

**Comment by torjohron** [comment]
It's not only on this device, same thing happened to me (s9). The Dropbox file solved the problem for me to :)

**Comment by topjohnwu** [comment]
@torjohron @xerta555 please re-download the official v7.3.5, I uploaded a new binary which fixes the issue

**Comment by torjohron** [comment]
Working now, tx!

**Comment by xerta555** [comment]
@topjohnwu The new official version of the Manager fix the issue for me too 🤗

Thanks

**Comment by zemix** [comment]
redownload manager by official link again, install, and no Settings crash now, thanks
hope manager's apk fix in flashable zip Magisk-v20.0.zip too
worked well now (LGD802 Andr 7.1.2 AospExtended-v4.6-d802-20180618-0929-OFFICIAL)
