### ISSUE TITLE
Error verifying vbmeta image

### ISSUE THREAD

**Issue by soratobukuroneko** [topjohnwu/Magisk#1919]
Hello,

I wanted to upgrade magisk to 2.0.0 but now I get an error at boot:

partition vbmeta
Reason vbmeta: Error verifying vbmeta image:
0_0_INDIVLDVMT_EDRHS_IMTHSGAUEMSAC

My phone is a Samsung A70 SM-A705FN. Magisk 19.4 was running fine.
Is there a way to downgrade or fix that?

**Comment by w2016561536** [comment]
I have the same issue ,On my sm-a6060 , if I update to magisk 20.0 ,I get the same error while booting. According to the log of update.The magisk manager installed the magisk into the ramdisk of boot image.In fact, magisk should be installed into recovery.You can try boot to system without magisk and then patch the ap file

**Comment by w2016561536** [comment]
However , Magisk seems that it only can install magisk into boot image even if I choose "Install to recovery"(not only upgrade , but also patching the ap file).I will submit a new issue to topjohnwu

**Comment by topjohnwu** [comment]
Fixed in this commit: 9867a3bd600c5d1f599bee6e2d8e5b87bcd01a86

**Comment by kraxarn** [comment]
As a new update with the fix hasn't been released yet, what is the best way to recover from this? I can't seem to boot my device at all.
