### ISSUE TITLE
[LineageOS] Flashing Magisk causes Android to boot directly to recovery

### ISSUE THREAD

**Issue by zacchi4k** [topjohnwu/Magisk#192]
I'm running LineageOS 20170428 on my Asus Zenfone 2 (ZE551ML). When I try to flash Magisk from the TWRP recovery (3.1.0) and restart the phone, Android doesn't boot anymore and the phone boots directly to the recovery.
Apparently, it's not a problem affecting just me, other people complained about this issue too (all running LOS)

**Comment by Didgeridoohan** [comment]
Are you sure it's not a matter of some Asus devices requiring boot image signing? 

There are many users of Magisk on LineageOS...

**Comment by zacchi4k** [comment]
Could you give me some other info?

**Comment by Didgeridoohan** [comment]
The Magisk release thread (https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445), last point of the FAQ in the troubleshooting section. That's all I know... You'll have to do some research yourself.

**Comment by suyonk** [comment]
So the problem is in the asus device itself,so how i can fix it ? can someone help me ? Thankyou :)

**Comment by zacchi4k** [comment]
But I unlocked the bootloader and even enabled the "unlock bootloader" option under LineageOS' developer settings, shouldn't boot image signing be unnecessary at this point?

**Comment by Didgeridoohan** [comment]
No idea... I have no knowledge of Asus devices.

I was merely asking if you had ruled out boot image signing as a cause of there issue.

Bootloader and boot image are not the same thing.

**Comment by zacchi4k** [comment]
According to [this post](https://forum.xda-developers.com/showpost.php?p=68542370&postcount=8551), signed boot images are required with the new bootloader (and the new bootloader is required for LineageOS). What do I do now?

**Comment by Didgeridoohan** [comment]
Now you Google... Or wait for someone who knows more.

**Comment by zacchi4k** [comment]
I found a zip of Magisk 8 on Xda patched for the Zenfone 2 (all it does is cat a file containing the needed  signature to the boot partition).
I ported the patch to the Magisk 12 installer and it worked, but it would be nice to see it implemented officially.

**Comment by Magissia** [comment]
This is device specific, too much time consuming for low result, while it would be awesome there are more important things to do.
(Please don't be offended, I'm using a ZenFone too, just being realistic)

**Comment by zacchi4k** [comment]
We already have all the code needed, just a line for device model detection is required

**Comment by antchris** [comment]
@zacchi4k Hi, could you please explain how exactly you did it ? I'have a zenfone 2 and bootloop too :/

**Comment by ziovec** [comment]
@zacchi4k I'm interested too!
I'm running ze551ml and stucked in bootloop...I've looked for a Magisk zip patched and I wasn't able to find it...but even if I'll found it, I'm not sure I'll be able to port the patch in Magisk 12...please help :D

**Comment by kaitozaki** [comment]
installed this and it work!!!!
**https://forum.xda-developers.com/attachment.php?attachmentid=4164411&d=1496000476**

Main forum page
https://forum.xda-developers.com/android/software-hacking/signing-boot-images-android-verified-t3600606

leave a like!

**Comment by fernandoglatz** [comment]
@kaitozaki thanks for sharing! The boot loop stopped and my root started up again

**Comment by zacchi4k** [comment]
If someone still needs this: https://forum.xda-developers.com/zenfone2/general/magisk-patched-zenfone-2-t3670476/post73729108#post73729108
