### ISSUE TITLE
Creating ANR after flashing Magisk 20.0

### ISSUE THREAD

**Issue by gangd42** [topjohnwu/Magisk#1921]
**Magisk Manager** producing **ANR** and the device freeze and reboot again after upgrading/flashing **Magisk 20.0** from custom recovery **TWRP** and updating **Magisk Manager 7.3.5(243)**.
But everything is fine after reverting it back to the previous version, i.e., **Magisk 19.3** and **Magisk Manager 7.3.4(235)**.

I have **whyred**(Redmi Note 5 Pro) with running custom ROM **Ressurection Remix Oreo 8.1.0**.

![Screenshot_Magisk_Manager_20191012-160504](https://user-images.githubusercontent.com/16123051/66700072-41265d80-ed0a-11e9-95ed-ea259c69b968.png)

**Comment by topjohnwu** [comment]
No logs, closed

**Comment by gangd42** [comment]
It's working fine after flashing **Magisk 20.0** again from **TWRP**.
Thanks.
