### ISSUE TITLE
CaixaBank Bank Apps detecting root

### ISSUE THREAD

**Issue by mikelgmh** [topjohnwu/Magisk#1922]
All of the Caixabank bank apps are detecting root access, so I can't login to my bank account. Safety Net is passing. ![](https://i.imgur.com/T3bwjx9.jpg)

Tested on Redmi Note 4 using Pixel Experience ROM. It worked at Magisk <19.x

**Comment by Emulatorer** [comment]
Related to  #1152

**Comment by Emulatorer** [comment]
Try this Xposed Module
![Screenshot_20191012-193533](https://user-images.githubusercontent.com/37603562/66700791-958c0600-ed27-11e9-9239-50b7fa195b86.png)

**Comment by topjohnwu** [comment]
#1152

**Comment by deivids84** [comment]
CaixaBank's banking applications detect root again even if they are in Deny List
