### ISSUE TITLE
Magisk 20.0 (20000): /sbin/.core is linked to magisk instead of .magisk

### ISSUE THREAD

**Issue by F-i-f** [topjohnwu/Magisk#1927]
After installing the latest Magisk 20.0 (20000) downloaded at around October 12 @ 23:00 UTC, the compatibility link in `/sbin/.core` points to `./magisk` instead of `./.magisk`.
``` shell
# ls -la /sbin/.core 
lrwxrwxrwx    1 root         root                 8 Oct 12 16:08 /sbin/.core -> ./magisk
```

**Comment by fox8091** [comment]
Fixed in #1917
