### ISSUE TITLE
[Leeco Le Pro 3] [X720] Safetynet error

### ISSUE THREAD

**Issue by mauronofrio** [topjohnwu/Magisk#193]
Magisk dont pass Safetynet and it report an error: Case -1 , safetyNet_error
The boot.img is here: https://mega.nz/#!Z9cHlJ6K!V1dVAUlWdzDYXb9-i9IfdHFslOivrgauhzhAiX6US-8

**Comment by Didgeridoohan** [comment]
What have you tried in your efforts to make SafetyNet pass? 

A few things to try here:
https://forum.xda-developers.com/apps/magisk/magisk-magisk-hide-troubleshooting-tips-t3561828

**Comment by ChrisCheney** [comment]
This will make it pass but probably should be made more generic for all android devices:

https://gitlab.com/alelec/magisk-gemini-safetynet-props/builds/14015433/artifacts/download

**Comment by mauronofrio** [comment]
Thanks it seems to work
