### ISSUE TITLE
custom android 10 boot.img fail

### ISSUE THREAD

**Issue by 99degree** [topjohnwu/Magisk#1931]
Hi,

Doing a porting of android pixel factory boot image to a meizu m3note, I manually patch the image with custom build magiskinit as /init (not the magiskinit64) and fail after selinux with permission denied. Can anybody offer some hints?

short extract:
[    4.947179]  (5)[1:init]init: restorecon failed of /system/bin/init failed: Permission denied

the log is as below:
[magisk_latest_git_with_dbg_log.TXT](https://github.com/topjohnwu/Magisk/files/3721856/magisk_latest_git_with_dbg_log.TXT)

Thanks.

**Comment by topjohnwu** [comment]
Patch the boot image with Magisk Manager, or properly follow the installation scripts.

**Comment by 99degree** [comment]
redo the test with latest magisk v20 and patch img with magisk manager. boot still fail with the extracted ramdisk.img.gz.

boot cmd:
`fastboot.exe boot wt6755-kernel-q ramdisk.pixel3xl.q.img --cmdline "bootopt=64S3,32N2,64N2 enforcing=0 androidboot.selinux=permissive root=/dev/ram androidboot.board.platform=mt6755 androidboot.hardware=mt6755 androidboot.debuggable=1 androidboot.force_normal_boot=1 _androidboot.android_dt_dir=/dt-overlay rootdelay=5 android_custom_fdt=1 want_initramfs " --base 0 --kernel-offset    0x40080000 --ramdisk-offset  0x45000000  --tags-offset    0x44000000   --page-size 2048 --header-version 0 --os-version 7.0.0 --os-patch-level 2018-02-02  --dtb-offset 0x44000000
`

analysis log:
results is similar outcome to previously reported. 


>  log:
[    1.376846]  (5)[1:init]init: init first stage started!
[    1.377107]  (5)[1:init]init: Switching root to '/first_stage_ramdisk'
[    1.377468]  (5)[1:init]init: [libfs_mgr]ReadFstabFromDt(): failed to read fstab from dt
[    1.377779]  (5)[1:init]init: [libfs_mgr]Warning: unknown flag: resize
[    1.377802]  (5)[1:init]init: [libfs_mgr]Warning: unknown flag: =/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/metadata
[    1.378196]  (5)[1:init]init: Using Android DT directory /proc/device-tree/firmware/android/
[    1.378607]  (5)[1:init]init: [libfs_mgr]Warning: unknown flag: resize
[    1.378630]  (5)[1:init]init: [libfs_mgr]Warning: unknown flag: =/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/metadata
...
[    1.469681]  (5)[1:init]init: [libfs_mgr]superblock s_max_mnt_count:65535,/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/userdata
[    1.474662]  (5)[1:init]EXT4-fs (mmcblk0p31): mounted filesystem with ordered data mode. Opts: barrier=1
[    1.474775]  (5)[1:init]init: [libfs_mgr]__mount(source=/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/userdata,target=/system_root,type=ext4)=0: Success
[    1.475237]  (5)[1:init]init: [libfs_mgr]superblock s_max_mnt_count:65535,/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/vendor
[    1.477842]  (5)[1:init]EXT4-fs (mmcblk0p33): mounted filesystem without journal. Opts: barrier=1
[    1.477920]  (5)[1:init]init: [libfs_mgr]__mount(source=/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/vendor,target=/vendor,type=ext4)=0: Success
[    1.478259]  (5)[1:init]init: Could not get mount point for '/' in /proc/mounts, /system will not be available for overlayfs
...
[    1.521581]  (6)[1:init]init: Skipped setting INIT_AVB_VERSION (not in recovery mode)
[    1.523623]  (5)[1:init]random: init urandom read with 13 bits of entropy available
...
[    4.686477]  (5)[1:init]init: Loading SELinux policy
...
[    7.369950]  (5)[1:init]audit: type=1403 audit(1453619628.120:2): policy loaded auid=4294967295 ses=4294967295
[    7.371591]  (5)[1:init]selinux: SELinux: Loaded policy from /sbin/.se
[    7.371591]
[    7.372655]  (5)[1:init]audit: type=1404 audit(1453619628.130:3): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295
[    7.418871]  (5)[1:init]audit: type=1400 audit(1453619628.170:4): avc:  denied  { getattr } for  pid=1 comm="init" path="/system/etc/selinux/plat_file_contexts" dev="mmcblk0p31" ino=180011 scontext=u:r:kernel:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
[    7.419511]  (5)[1:init]selinux: selinux_android_file_context: Error getting file context handle (No such file or directory)
[    7.419511]
[    7.421960]  (4)[1:init]audit: type=1400 audit(1453619628.180:5): avc:  denied  { execute } for  pid=1 comm="init" name="linker64" dev="mmcblk0p31" ino=155560 scontext=u:r:kernel:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
**[    7.422494]  (4)[1:init]init: execv("/system/bin/init") failed: Permission denied**
[    7.442386]  (5)[1:init]audit: type=1400 audit(1453619628.200:6): avc:  denied  { open } for  pid=1 comm="init" path="/system/lib64/libbacktrace.so" dev="mmcblk0p31" ino=156389 scontext=u:r:kernel:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
[    7.455367]  (5)[1:init]audit: type=1400 audit(1453619628.210:7): avc:  denied  { open } for  pid=1 comm="init" path="/system/lib64/libbase.so" dev="mmcblk0p31" ino=156390 scontext=u:r:kernel:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
[    7.455701]  (5)[1:init]audit: type=1400 audit(1453619628.210:8): avc:  denied  { open } for  pid=1 comm="init" path="/system/lib64/bootstrap/libc.so" dev="mmcblk0p31" ino=171365 scontext=u:r:kernel:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
[    7.456064]  (5)[1:init]init: #00 pc 0000000000066d20  /system/bin/init (android::init::InitFatalReboot()+80)
[    7.456095]  (5)[1:init]init: #01 pc 00000000000926f4  /system/bin/init (android::init::InitAborter(char const*)+44)
[    7.456119]  (5)[1:init]init: #02 pc 000000000000c5b4  /system/lib64/libbase.so
[    7.456141]  (5)[1:init]init: #03 pc 000000000006a1a0  /system/bin/init (android::init::SetupSelinux(char**)+760)
[    7.456163]  (5)[1:init]init: #04 pc 0000000000023170  /system/bin/init (main+276)
[    7.456184]  (5)[1:init]init: #05 pc 000000000007d798  /system/lib64/bootstrap/libc.so
[    7.456203]  (5)[1:init]init: Reboot ending, jumping to kernel
[    7.456807]  (5)[1:init]mmcblk mmc1:59b4: shutdown
[    7.457892]  (5)[1:init][msdc]msdc power off
[    7.457914]  (5)[1:init][msdc]msdc power off
[    7.478949]  (5)[1:init]battery battery: shutdown
[    7.479000]  (5)[1:init]mmcblk mmc0:0001: shutdown

regards.
[magisk_v20_official_patched_boolog.txt](https://github.com/topjohnwu/Magisk/files/3723690/magisk_v20_official_patched_boolog.txt)
