### ISSUE TITLE
Busybox wget don't resolve IP addresses

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#1932]
Hi,

For one of my Magisk module, i have to automaticly download file from intrnet.

The problem is that your Busybox don't resolve domains names to IP addresses.
Also, i can't enforce my install.sh file to use the Busybox binary file from osm0sis for wich it's works fine.

Apparently it's a problem that's already been reported to you, so do I have to add the osm0sis Busybox binaries in my module zip to make it works fine or do you plan to fix it?

Tx in advance.

**Comment by skittles9823** [comment]
Here is a quote from osm0sis. John hasn't commented on it I don't believe.

![](https://i.imgur.com/2TpkAd5.png)

**Comment by xerta555** [comment]
> Here is a quote from osm0sis. John hasn't commented on it I don't believe.

I initiated the user's message on John's Slack, where indeed osm0sis answered as you mentioned.

I was able to manage without in the design of an update of one of my Magisk modules.

As the tester in question pointed out in my Telegram test discussion group, we very much hope that John will fix this issue.

Since osm0sis has already figured out how to fix this issue for some time now, I think it won't be insurmountable to fix for John.

**Comment by osm0sis** [comment]
John used to use my patches for networking but stopped doing so and has mentioned a few times he has no plans on going back.

Modules that require a full wget should either include their own busybox or require mine to be installed.

**Comment by xerta555** [comment]
> to minimize

Your patch increases the size of the binaries that much?
However, between your two binaries the difference is not great...

So I have to include an if statement to use your working binaries automatically.

Amazing this kind of free carrot....

**Comment by osm0sis** [comment]
It wasn't about binary size, it was about John wanting as few patches as possible.

**Comment by xerta555** [comment]
> It wasn't about binary size, it was about John wanting as few patches as possible.

Did it cause other problems?
Or just to have the most clean setup as possible?

**Comment by xerta555** [comment]
@osm0sis Let's be crazy, I'm asking one last question:
would it be possible to have a patch in the form of a file (binary or other) that would fix this?

In such a way that wget can work with a CLI argument that we would point to this patch file?

**Comment by osm0sis** [comment]
Not entirely sure I get what you mean.. Patching Magisk's busybox on-device? No, not possible.

**Comment by xerta555** [comment]
> Not entirely sure I get what you mean.. Patching Magisk's busybox on-device? No, not possible. My networking patches add a libres minimal resolver and patches references in several utilities to use it instead.

Thanks anyway for your answer, at least I tried...

I guess I'll have to close this subject now bcz John willn't change this judgment?

**Comment by osm0sis** [comment]
Correct. At most John should revise his busybox config to properly remove the effected utilities so people don't have this question again in the future.

**Comment by xerta555** [comment]
> Correct. At most John should revise his busybox config in keeping with his decision to exclude my networking patches to properly remove the effected utilities so people don't have this question again in the future.

Do you know if he intends to purely and simply remove applets that may require an IP resolution tool like wget and ping for example, or does he plan to fix this sort of issue as you?

Sorry, I didn't quite understand the meaning of your sentence.

**Comment by osm0sis** [comment]
I don't know of his intentions, merely saying what the best course of action would be for him.

**Comment by osm0sis** [comment]
This will remove the broken applets for the next build once John merges it all: https://github.com/topjohnwu/ndk-box-kitchen/pull/1

**Comment by xerta555** [comment]
@osm0sis I think that this situation will be better than now..

Anycase ty very much for all your infos.
