### ISSUE TITLE
Can't mount /system rw on magisk 19.4+

### ISSUE THREAD

**Issue by betaxab** [topjohnwu/Magisk#1936]
I can't mount /system on 19.4+, but 19.3 works well. I tried 19.4, 19.5 20.0, these does not work.

My device: Moto Z2 Force, Stock Android 9.0, PPX29.159-23, I have already removed dm-verity by reinstall magisk zip on magisk manager.

it will show:
`# mount -o rw,remount /system
mount: '/system' not in /proc/mounts
`
cat /proc/mounts

> /dev/root / ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
tmpfs /sbin tmpfs rw,seclabel,relatime,size=1891948k,nr_inodes=472987,mode=755 0 0
/sbin/.magisk/block/system_root /sbin/.magisk/mirror/system_root ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
/sbin/.magisk/block/system_root /sbin/charger ext4 rw,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,size=1891948k,nr_inodes=472987,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,mode=600 0 0
proc /proc proc rw,relatime,gid=3009,hidepid=2 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
tmpfs /mnt tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1891948k,nr_inodes=472987,mode=755,gid=1000 0 0
none /acct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
none /dev/stune cgroup rw,nosuid,nodev,noexec,relatime,schedtune 0 0
none /config configfs rw,nosuid,nodev,noexec,relatime 0 0
none /dev/cpuctl cgroup rw,nosuid,nodev,noexec,relatime,cpu 0 0
none /dev/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent 0 0
cg2_bpf /dev/cg2_bpf cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
adb /dev/usb-ffs/adb functionfs rw,relatime 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,seclabel,relatime 0 0
/dev/block/bootdevice/by-name/userdata /data ext4 rw,seclabel,nosuid,nodev,noatime,discard,nobarrier,noauto_da_alloc,data=ordered 0 0
/dev/block/bootdevice/by-name/modem_a /system/vendor/firmware_mnt ext4 ro,context=u:object_r:firmware_file:s0,nosuid,nodev,relatime,data=ordered 0 0
/dev/block/bootdevice/by-name/bluetooth_a /system/vendor/bt_firmware ext4 ro,context=u:object_r:bt_firmware_file:s0,nosuid,nodev,relatime,data=ordered 0 0
/dev/block/bootdevice/by-name/dsp_a /system/vendor/dsp ext4 ro,seclabel,nosuid,nodev,relatime,data=ordered 0 0
/dev/block/bootdevice/by-name/persist /persist ext4 rw,seclabel,nosuid,nodev,noatime,data=ordered 0 0
/dev/block/bootdevice/by-name/persist /mnt/vendor/persist ext4 rw,seclabel,nosuid,nodev,noatime,data=ordered 0 0
/dev/block/bootdevice/by-name/fsg_a /system/vendor/fsg ext4 ro,context=u:object_r:fsg_file:s0,nosuid,nodev,relatime,block_validity,delalloc,barrier,user_xattr 0 0
/dev/block/dm-0 /oem ext4 ro,context=u:object_r:oemfs:s0,nosuid,nodev,relatime,block_validity,delalloc,barrier,user_xattr 0 0
/dev/block/bootdevice/by-name/carrier /carrier ext4 rw,seclabel,nosuid,nodev,noatime,data=ordered 0 0
tmpfs /storage tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1891948k,nr_inodes=472987,mode=755,gid=1000 0 0
/sbin/.magisk/block/data /sbin/.magisk/mirror/data ext4 rw,seclabel,relatime,discard,nobarrier,noauto_da_alloc,data=ordered 0 0
/sbin/.magisk/block/data /sbin/.magisk/modules ext4 rw,seclabel,relatime,discard,nobarrier,noauto_da_alloc,data=ordered 0 0
/data/media /mnt/runtime/default/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal 0 0
/data/media /storage/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal 0 0
/data/media /mnt/runtime/read/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal 0 0
/data/media /mnt/runtime/write/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal 0 0

Magisk log:

cat magisk.log
> --------- beginning of main
--------- beginning of system
01-02 14:41:01.935   997   997 I Magisk  : Magisk v20.0(20000) daemon started
01-02 14:41:01.935   997   997 I Magisk  : * Device API level: 28
01-02 14:41:01.955   997   998 I Magisk  : ** post-fs-data mode running
01-02 14:41:01.957   997   998 I Magisk  : * Initializing Magisk environment
01-02 14:41:01.958   997   998 I Magisk  : * Mounting mirrors
01-02 14:41:01.959   997   998 I Magisk  : mount: /sbin/.magisk/mirror/data
01-02 14:41:01.959   997   998 I Magisk  : link: /sbin/.magisk/mirror/system
01-02 14:41:01.959   997   998 I Magisk  : link: /sbin/.magisk/mirror/vendor
01-02 14:41:01.959   997   998 I Magisk  : link: /sbin/.magisk/mirror/product
01-02 14:41:01.959   997   998 I Magisk  : * Setting up internal busybox
01-02 14:41:01.971   997   998 I Magisk  : * Running post-fs-data.d scripts
01-02 14:41:01.975   997   998 I Magisk  : * Running module post-fs-data scripts
01-02 14:41:01.975   997   998 I Magisk  : * Loading modules
01-02 14:41:02.029   997  1005 I Magisk  : * Starting MagiskHide
01-02 14:41:02.029   997  1005 I Magisk  : hide_policy: Hiding sensitive props
01-02 14:41:02.029   997  1005 I Magisk  : hide_list init: [com.google.android.gms/com.google.android.gms.unstable]
01-02 14:41:02.036   997  1005 I Magisk  : hide_list init: [org.microg.gms.droidguard/com.google.android.gms.unstable]
10-09 09:58:22.093   997  1445 I Magisk  : ** late_start service mode running
10-09 09:58:22.093   997  1445 I Magisk  : * Running service.d scripts
10-09 09:58:22.093   997  1445 I Magisk  : * Running module service scripts
10-09 09:58:31.563   997  3064 I Magisk  : ** boot_complete triggered
10-09 09:58:31.594  3068  3068 I Magisk  : apk_install: /data/magisk.apk
10-09 09:58:37.688  4729  4729 I Magisk  : apk_install: Success
10-09 09:58:41.649   997  1005 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[5110] UID=[10017]

If you need more info, pelse let me know.

**Comment by topjohnwu** [comment]
Please read the release notes....
https://github.com/topjohnwu/magisk_files/blob/2d7ddefbe4946806de1875a18247b724f5e7d4a0/notes.md

**Comment by 0x454447415244** [comment]
System file should be accessed via:
```
/sbin/.magisk/mirror/system_root/system
```
Enable write access like this:
```
mount -o rw,remount /sbin/.magisk/mirror/system_root
```

**Comment by Paschalis** [comment]
This on a Google Pixel Android 10 gives me:
` '/sbin/.magisk/block/system_root' is read-only`

Any solutions to that?

**Comment by fusionneur** [comment]
same on oneplus, android 10, magisk 20.4:

OnePlus7TPro:/ # mount -o rw,remount /sbin/.magisk/mirror/system_root
'/sbin/.magisk/block/system_root' is read-only
