### ISSUE TITLE
Not Booting in Asus Zenfone 2 Laser

### ISSUE THREAD

**Issue by suyonk** [topjohnwu/Magisk#194]
I tried to flash Magisk v12.0 but my phone is soft brick. I have supersu,busybox adn twrp latest version. My phone running in 5.0.2 version (Lollipop). Can you figure it out why my phone can't booting ?? Thank You very Much :)

**Comment by Didgeridoohan** [comment]
See my answers here: https://github.com/topjohnwu/Magisk/issues/192
