### ISSUE TITLE
Bootloop from latest Magisk

### ISSUE THREAD

**Issue by mikejm123** [topjohnwu/Magisk#1941]
I've got a Galaxy Tab A 2019 T510. I've been using the prior Magisk, the Manager and the Magisk installed busybox for about 2 Months without a problem. I updated to Magisk 20 and the new Manager a few days ago. Everything continued to work until I shut off the tablet. When I tried to start it back up I got a continuous bootloop. I tried going into recovery and clearing cache but nogo. I had to reload to recover.

**Comment by topjohnwu** [comment]
I was fixed, please wait for the next release
