### ISSUE TITLE
Magisk 20 Phone gets unresponsive

### ISSUE THREAD

**Issue by michaelarlt** [topjohnwu/Magisk#1943]
Phone: OnePlus 6T
TWRP: 3.3.1.1
Magisk Manager: 7.3.5 (243)
Magisk: 19.3

When i update to the latest version 20 of magisk, the mobile is becoming unresponsive after few minutes once the reboot is done. There is even an error in the magisk log, which states that the setup is incomplete. You can see in the attached picture. Luckily i managed to get it before it got unresponsive.
![Screenshot_20191016-130558](https://user-images.githubusercontent.com/18514062/66925447-ab9e0d00-f02c-11e9-88d4-55de01b603cc.jpg)

**Comment by topjohnwu** [comment]
Please use debug builds to report issues
