### ISSUE TITLE
Don't get any notification from Magisk Manager

### ISSUE THREAD

**Issue by onesolo** [topjohnwu/Magisk#1946]
I've been using the canary Magisk Manager, and also magisk canary itself, since using it on Android 10 betas. I don't get any notification when magisk and magisk manager have an update. Pixel 3 user.

**Comment by topjohnwu** [comment]
I used the official WorkManager library from Google, if it is not working on a Pixel, I don't know what to say....
I get notifications without any problems on all of my devices, including Samsung. You might be putting Magisk Manager on battery optimized mode.
