### ISSUE TITLE
Module zip need to be verified before installation

### ISSUE THREAD

**Issue by RikkaW** [topjohnwu/Magisk#1947]
Today I received a "can't boot" report from my user. After some investigation, I found the problem is caused by corrupted so file (the front part is correct and the behind part is gone, causing linker error).

So I asked for the zip file. The image shows the diff of the correct zip from my device and the bad zip.
![2019-10-17_23-38-17](https://user-images.githubusercontent.com/12999176/67024602-47b43b00-f137-11e9-8080-7c0d4bc80a4c.png)
It not looks like caused by a network error.

We may conclude that GitHub may provide corrupted zip. So Magisk Manager needs some kind of verification mechanism such as let the module author add files to the zip and verify them on installation.

**Comment by topjohnwu** [comment]
Unfortunately, GitHub does not provide any verification method to verify downloads. It is possible GitHub is packaging old version of code when its backend is syncing, I really don't know as I do not host the files on my server.
Also, even if we have checksum support from the backend, the zip file is processed on-the-fly when downloading from GitHub, so there could also be issues happening on device.

**Comment by RikkaW** [comment]
Finally get a feasible and easy plan.
Provide an executable with generating & verifying file hash function. The executable can be bundled with Magisk or included in the module zip.
The module developer can use the executable to generate the hash for important files and sort the hash in other files (i.e., `xxx.so.hash` for `xxx.so`), making them verifiable in `install.sh`.
