### ISSUE TITLE
[UI][Feature Request] UI theme improvements 

### ISSUE THREAD

**Issue by alexa-v2** [topjohnwu/Magisk#1951]
Unfortunately as of now no substratum theme I own supports the latest canary manager so here goes:

The new UI of Manager is good. However, there remains in my opinion some work to be done.

Right now in dark theme, there's a green bar (that's in my opinion kinda ugly), and some weird (also in my opinion) gray lines here and there. Not great UI to be honest

So here's what I suggest:
Option 1:
Remove the green bar at the top in dark theme, make it black. Keep it in light theme though. Although it's been in manager for forever, maybe it's time for it to go
Option 2:
A Black (AMOLED) theme. My preference. As with option 1, it has no green bar but also none of this gray lines - a true black theme. New options would be Light, Dark, Black.

Obviously not a very high priority but more an improvement

**Comment by topjohnwu** [comment]
The app is already undergoing a new UI redesign by @diareuse, please be patient :)
There is no need to keep coming up with UI improvement requests as I keep track of GitHub issues for actual bugs.
