### ISSUE TITLE
Can i patch samsung firmware with Magisk19.3

### ISSUE THREAD

**Issue by brsteej** [topjohnwu/Magisk#1953]
Hello
I have problem with magisk 20 when i patch samsung tab s6 or s5e and flash it there is an issue with vbmeta partition and wont boot
So is there any way to patch with magisk 19.3 ? it was fine for me

**Comment by bsecur** [comment]
https://raw.githubusercontent.com/bsecur/Magisk-json/master/19.4.json

**Comment by topjohnwu** [comment]
It is already fixed, please be patient.
