### ISSUE TITLE
Installation partial failure.

### ISSUE THREAD

**Issue by Exist2Resist** [topjohnwu/Magisk#1954]
Pixel 2 XL on Android 10 October update.

After flashing latest v20 Magisk Zip updating partitions fails with the following errors....

> Failed to mount '/system' (Invalid arguments)
> Failed to mount '/vendor' (Invalid arguments)

Then once I boot into the OS Magisk says it's up to date, however enabling add blocking in AdAway, it fails to remount the partition as read/write to make changes to the host file.

Does SU no longer have access to mount r/w partitions in Android 10?

**Comment by martyfender** [comment]
For Adaway, go to Magisk Manager, settings, click on systemless hosts, you should see a toast:  added systemless hosts module. Now, just like and module installed, you must reboot for it to be enabled. in addition, in Adaway, settings, enable systemless mode must be checked. It should be checked by default on a new install. John should know about your other errors.

**Comment by topjohnwu** [comment]
Please read release notes regarding the changes in system-as-root, your root app needs to be updated. Also, use systemless hosts for hiding ads

**Comment by Exist2Resist** [comment]
Nothing happens on latest version when I click systemless hosts. 

7.3.5 (243)
