### ISSUE TITLE
PLZ help can't root Galaxy J6 🥺

### ISSUE THREAD

**Issue by ChemsoDev** [topjohnwu/Magisk#1956]
I have a galaxy j6
sm-j600f binary 5 (aka u5)
android pie (oneui1.0)
![Screenshot_20191019-233752_Settings](https://user-images.githubusercontent.com/41765106/67152292-d6a58c80-f2ca-11e9-8888-7548f1f5695f.jpg)
![Screenshot_20191019-233817_Settings](https://user-images.githubusercontent.com/41765106/67152297-e329e500-f2ca-11e9-8598-70cda03dddfd.jpg)

what is the best method to install magisk
twrp or flashig patched rom or patched recovery and send me links if there is
plz i need help cz the last time i broke my device with a bootloop (i accidentally deleted the /system /vendor /data /... in fact all the partitions 😉 ah u know twrp 🙄)

**Comment by martyfender** [comment]
This is not the place to ask for help rooting your device. It is for bug reporting only. If there is an xda forum about your device that is the best way to find out. Some in the Magisk General Support / Discussion thread may be able to help. Also, see here:
https://topjohnwu.github.io/Magisk/install.html

**Comment by ChemsoDev** [comment]
thanx 
and sorry for the interruption
i will flash it using twrp 
u know the classic method
