### ISSUE TITLE
Mounting /product doesn't work on Huawei device

### ISSUE THREAD

**Issue by Dr-TSNG** [topjohnwu/Magisk#1957]
I want to replace files in /product/etc/media and I placed my files in [module.zip]/system/product/etc/media . Then,I installed it but when rebooted I found it doesn't work and /sbin/.magisk/modules/mymodule/product is empty.

**Comment by topjohnwu** [comment]
It means that folder does not exist for some reason, Magisk wll remove files that is not safe to mount
