### ISSUE TITLE
Recovery gone after patching OxygenOS 10 OnePlus 6T (Magisk 20)

### ISSUE THREAD

**Issue by MrHappy** [topjohnwu/Magisk#1958]
After updating to the Beta release of Android Q (OxygenOS) on 6T and patching boot.img with Magisk20 the recovery is gone.
After flashing the unpatched boot.img it is back.
Could you please fix this?

Don't know if it is related, but opening settings in Magisk Manager crashes the app...

If you need any help/additional information, let me know ;)

**Comment by topjohnwu** [comment]
#1920

**Comment by MrHappy** [comment]
You linked this to a similar issue, but that issue is on Pie not Q....  😕

**Comment by MrHappy** [comment]
@topjohnwu
You related this issue to #1920, but that is a different phone with different os version.
This issue is not resolved.
