### ISSUE TITLE
Screen flashing on root access

### ISSUE THREAD

**Issue by Mohsyn** [topjohnwu/Magisk#1959]
Everytime any app requires root access, the screen moves back and forth to right before the toast comes up.
It doesn't do anything but very annoying

**Comment by martyfender** [comment]
I have a similar issue on the latest Canary but for me the Magisk Manager black window will flash on the screen for a moment, right before the root granted toast appears. This is both on my new Onn 8 Android 9 and all of my Nextbook Ares 8A tablets.
