### ISSUE TITLE
[Systemless Xposed Framework]No support for Moto G gen 2 2014

### ISSUE THREAD

**Issue by TotalLegitREMIX** [topjohnwu/Magisk#196]
So first off I want to say that I am not extraordinarily experienced with the android OS and such, therefore there is a possibility that I am just making a mistake (but I don't believe that is true)

I am trying to install systemless Xposed framework (SDK 23) through your app and it just isn't working. I have even tried flashing the ZIP that the app downloads and nothing is working to get Xposed installed. I download it, and then it goes to "processing zip file". After sitting there an incredibly long time finishes. Then I select install and I go though that same processes again. When it is done it gives me a toast notification (that is what they are called right?) saying "Installation error!"
When I try to flash it in TWRP I get en error in short stating that it could not extract the zip file.

Also when you say these posts require me to include my boot image, I would be lying if I said I knew exactly what you meant by that.
The MEGA file "XT1064_TITAN_RETUAWS_6.0_MPB24.65-34_cid9_CFC.xml.zip" Is my phone's base OS. If you are wanting to know what version of Xposed I use when I install it manually, that would be "xposed-v87-sdk23-arm.zip" from the download website. The google drive file "Xposed_Framework_SDK_23-87.1_Systemless_by_topjohnwu.zip" is the one that Magisk Manager downloaded, reuploaded by me. The only "img" file I am messing with is TWRP but I doubt you care about that. If you need something I didn't provide, let me know. 

Thank you :)

(Stock Base ROM is the Mega link. The XDA link is where I found my stock ROM. The Google drive link is what Magisk Manager downloads when I select for it to install the Xposed framework)
https://mega.nz/#F!00ZlRb4Q!l27FlJ7q-IbI8L95uYqneA
https://forum.xda-developers.com/moto-g-2014/development/original-motorola-firmware-collection-t3153533
https://drive.google.com/open?id=0B7zDiumep19lbVVwUEtoMzVzUWM

**Comment by topjohnwu** [comment]
No Xposed support here
