### ISSUE TITLE
samsung-system-as-root installation update

### ISSUE THREAD

**Issue by casperdcl** [topjohnwu/Magisk#1961]
I followed [topjohnwu/Magisk/docs/install.md#samsung-system-as-root](https://github.com/topjohnwu/Magisk/blob/f8b4190a11fc5dd3a5c7162d72a27b5bf174ef4a/docs/install.md#samsung-system-as-root) for the Galaxy A40 and had to use a slightly different method.

In particular, for step 9 (trying to full data wipe) it insteads boots straight into recovery with this error:

```
Error verifying vbmeta image: OK_NOT_SIGNED (3)
verification disabled bit is set
CUSTOM VBMETA
VBMETA: No sign info
VBMETA .
```

I fixed this by instead in step 7 (flash `magisk_patched.tar` as `AP`) also flashing `HOME_CSC.tar` as `CSC` but no other files (no flashing `BL` and `CP`). I noticed in particular that the `BL.tar` contains a `vbmeta.img.lz4` which is perhaps confusing Odin?

**Comment by topjohnwu** [comment]
It is already fixed, please wait for update

**Comment by dex513** [comment]
MODE (AVB Fail)
vbmeta: Error verifying vbmeta  HASH_MISMATCH (3)
vbmeta: VERIFICATION_DISABLED bit is set
VBMETA M215FXXU3CVH1, 54722419R
