### ISSUE TITLE
要启动Android，请输入您的密码

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#1962]
这个BUG不是来自系统设置的某个密码。在联想Z5设备上安装magisk就会出现。并且在已经安装Magisk的情况 。（测试了多个版本很老和最新的）不同的版本也可能触发开机密码。解决方法似乎只有格式化DATA？
![125436stp3i8h98prir5r9](https://user-images.githubusercontent.com/11062371/67164549-607a5600-f3ae-11e9-9461-482ee412a577.jpg)

实在没办法。 特来求助。 主要上传了放在post-fs-data 和 service.d 文件夹的logcat日志

[post-fs-data_[正常].log](https://github.com/topjohnwu/Magisk/files/3748213/post-fs-data_.log)
[post-fs-data_[要启动Android，请输入您的密码].log](https://github.com/topjohnwu/Magisk/files/3748214/post-fs-data_.Android.log)
[service.d_[正常].log](https://github.com/topjohnwu/Magisk/files/3748215/service.d_.log)
[service.d_[要启动Android，请输入您的密码].log](https://github.com/topjohnwu/Magisk/files/3748216/service.d_.Android.log)
[magisk.log](https://github.com/topjohnwu/Magisk/files/3748217/magisk.log)

**Comment by topjohnwu** [comment]
有些手機在改過 boot image 過後 data 加密金鑰就會失效 (例如 Samsung)。你的手機很有可能就是這一類。

**Comment by androiddisk** [comment]
感谢回复
