### ISSUE TITLE
MagiskManager 7.3.5 (243) from 20.0 crashed after opening Settings tab on FireTV (Android 7.1.2)

### ISSUE THREAD

**Issue by tsynik** [topjohnwu/Magisk#1963]
Here is the log:
10-20 22:01:59.574  5302  5302 D Error   : ERR: exClass=java.lang.StackOverflowError
10-20 22:01:59.574  5302  5302 D Error   : ERR: exMsg=stack size 8MB
10-20 22:01:59.574  5302  5302 D Error   : ERR: file=AccessibilityNodeInfo.java
10-20 22:01:59.574  5302  5302 D Error   : ERR: class=android.view.accessibility.AccessibilityNodeInfo$CollectionItemInfo
10-20 22:01:59.574  5302  5302 D Error   : ERR: method=obtain line=4138
10-20 22:01:59.575  5302  5302 D Error   : ERR: stack=java.lang.StackOverflowError: stack size 8MB
10-20 22:01:59.575  5302  5302 D Error   : 	at android.view.accessibility.AccessibilityNodeInfo$CollectionItemInfo.obtain(AccessibilityNodeInfo.java:4138)
10-20 22:01:59.575  5302  5302 D Error   : 	at a.zh$b.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at androidx.recyclerview.widget.RecyclerView$o.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at androidx.recyclerview.widget.RecyclerView$o.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.jt.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at a.yq.a()
10-20 22:01:59.575  5302  5302 D Error   : 	at
10-20 22:01:59.575  5302  5302 D Error   : ERR: TOTAL BYTES WRITTEN: 41344
10-20 22:01:59.604  5302  5313 I art     : Background partial concurrent mark sweep GC freed 219793(7MB) AllocSpace objects, 5(4MB) LOS objects, 13% free, 25MB/29MB, paused 4.282ms total 125.999ms
10-20 22:01:59.641   618   629 W ActivityManager:   Force finishing activity com.topjohnwu.magisk/a.b
10-20 22:01:59.644   257  1438 I chatty  : uid=1000(system) Binder:257_5 expire 19 lines
10-20 22:01:59.654  5302  5302 I Process : Sending signal. PID: 5302 SIG: 9

**Comment by topjohnwu** [comment]
Redownload Magisk Manager, it was fixed
