### ISSUE TITLE
Magisk 20 breaks sensors on OxygenOS 10 on OP6T

### ISSUE THREAD

**Issue by MrHappy** [topjohnwu/Magisk#1965]
Sensors (rotating etc) work fine before flashing Magisk 20.
After flashing screen doesn't rotate anymore.
Anyway to flash older Magisk (19.4 i.e.) with the app?
(As twrp doesn't work yet on OP6T/OxygenOS 10...)

**Comment by DenyDarko** [comment]
Now you're mentioning it, I've tried it and auto rotation doesn't work with my OnePlus 6 either.

Haven't noticed till now as I rarely use landscape.

I wonder if that's why I don't have ear detection too (my screen stays active while I'm talking to the phone).

**Comment by MrHappy** [comment]
It appears to be riru - edxposed related...
When I disable this in Magisk screen rotating works again....

**Comment by martyfender** [comment]
Yes, I have seen many reports of riru - edxposed conflicting with Magisk, both here and the Magisk xda threads.

**Comment by topjohnwu** [comment]
Closed as it is an issue with modules.
