### ISSUE TITLE
能否提供禁用“分离挂载命名空间”的root权限。

### ISSUE THREAD

**Issue by daiaji** [topjohnwu/Magisk#1966]
实际上钛备份(TitaniumBackup)，和幸运破解器(LuckyPatcher)这两个APP的一部分功能（主要是“将更新整合进ROM”和“整合更新至 /system”），都无法在Magisk提供的ROOT权限下工作（挂载命名空间 模式 三种设置都无效），但在SuperSU中是可以通过关闭“分离挂载命名空间”，使这两个APP的功能正常使用。
希望Magisk提供类似的功能😋

**Comment by martyfender** [comment]
You might try use global namespace in mm settings. That is the recommended setting for Apps2SD.

**Comment by daiaji** [comment]
I actually tried this setup with LuckyPatcher, but it didn't help me.

**Comment by topjohnwu** [comment]
Global mount namespace 就是用全域的掛載命名空間。如果還有問題，那便不是 Magisk 的問題。
