### ISSUE TITLE
Unable to Root NUBIA RED MAGIC (NX609J)

### ISSUE THREAD

**Issue by methuselahin** [topjohnwu/Magisk#1967]
I am unable to root Nubia Red Magic NX609j. This Phone had got OMNI rom too. But root was never achievable. When i flashed magisk stable latest, the phone shows system got corrupted and never boots. The OMNO rom version is 9.0. The official stock ROM has got same issues. I am attaching recovery logs after flashing and before booting(flashed over OMNI ROM)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/3754102/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/3754103/recovery.log)

**Comment by martyfender** [comment]
I believe topjohnwu only allows reports here from the Canary builds.
topjohnwu, please clarify this for me and others, if this is true>

Thanks

**Comment by methuselahin** [comment]
@martyfender i will be delighted to report in xda too. The thing is, here it stays clean and tidy. XDA is kinda off chat lately.

**Comment by CaptainThrowback** [comment]
This is due to the garbage that Nubia adds to commandline. The only way around this in the past was patching them out in the kernel directly. I'm not sure there's anything that Magisk can do here. I believe @eng.stk is the one that fixed it before in the kernel.

**Comment by methuselahin** [comment]
@CaptainThrowback  flashed Magisk Canary from https://github.com/topjohnwu/magisk_files/tree/canary . here are the logs on omni without gapps. 
[dmesg.log](https://github.com/topjohnwu/Magisk/files/3760383/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/3760384/recovery.log)

right before booting to the rom

**Comment by CaptainThrowback** [comment]
Recovery logs aren't helpful here - we need Magisk log/logcat from Android to find out what's going on.

**Comment by engstk** [comment]
> This is due to the garbage that Nubia adds to commandline. The only way around this in the past was patching them out in the kernel directly. I'm not sure there's anything that Magisk can do here. I believe @engstk is the one that fixed it before in the kernel.
> 
> This is the case with any Magisk version, including the Canary builds. But if @methuselahin could flash the latest Canary debug and grab logs, that might be helpful.

Yep, indeed.

**Comment by methuselahin** [comment]
@ CaptainThrowback   
_Magisk logs are placed in /cache/magisk.log (For A/B devices, they are actually in /data/cache/magisk.log)
If you cannot boot or stuck in bootloops, grab logcats (and kernel dmesg if possible) on boot_
The recovery.log in the zip was copied from the system cache. I mentioned it over there brah

**Comment by topjohnwu** [comment]
As pointed out by @engstk and @CaptainThrowback, this is nothing Magisk can fix, so this issue will be closed

**Comment by methuselahin** [comment]
You can now root the device by patching the boot.img by first downloading the magisk and then flashing the patched boot.img on Chinese version i.e 9.0 checked by me and another user.

**Comment by DonZenith** [comment]
> @topjohnwu  You can now root the device by patching the boot.img by first downloading the magisk and then flashing the patched boot.img on Chinese version i.e 9.0 checked by me and another user. 

Hello sir, I'm on the global rom stuck in android 8.0. Is there any custom development support for this device ? Like roms and kernels of sorts ? Also, I would like to know how do I install gcam coz stock cam is shit af 😞
