### ISSUE TITLE
Issues after updating to 20 with Magisk Manager (Nexus 5X)

### ISSUE THREAD

**Issue by bandithedoge** [topjohnwu/Magisk#1968]
It's either broken or I'm doing something stupid. Probably the latter. Also possible cringe alert.

I updated Magisk to version 20 through the latest Magisk Manager (7.3.5). Everything seemed to go fine, except after rebooting when I unlock the device, it shows a black screen and locks again every time. I then tried to use uninmod and remove possible faulty modules but it didn't work because magisk.img isn't mounted. I uninstalled Magisk and reinstalled the latest version. Device is booting for an eternity and when it finally boots it says something about failed encryption and forces me to factory reset.

Some info:
Nexus 5X (bullhead) on stock 8.1.0, stock kernel, no Xposed. Updated from 19.4. TWRP 3.3.1 from twrp.me.

**Comment by topjohnwu** [comment]
I have owned a Nexus 5X myself, and it works just fine. Please seek other places for support :)

**Comment by bandithedoge** [comment]
Okay, but have you tried this specific update? I've used many versions of Magisk on my 5X and this is the only one that has problems like this.
