### ISSUE TITLE
Read only System (/System could not be mounted) 

### ISSUE THREAD

**Issue by engrahmadosama** [topjohnwu/Magisk#1969]
I have updated to magisk v20.0 and now my root applications ate not working.
ES files manager says read only filesystem
Link2sd says mount can't find /system in /proc/mounts

When i try to reinstall magisk usimg direct install method, it says unable to detect target image installation failed.

I reinstalled using patched_magisk. Img
But issues remains the same. 

As you have changed to /root instead of /system. 
What is the solution my problem,

**Comment by topjohnwu** [comment]
https://twitter.com/topjohnwu/status/1186808994133790720
