### ISSUE TITLE
Core Only Mode Enabled ALWAYS

### ISSUE THREAD

**Issue by sjc74364** [topjohnwu/Magisk#1970]
device: realme Q
rom: coloros 6

Unable to open migiskHide
Unable to turn off core mode

--------- beginning of main
--------- beginning of system
02-05 05:13:14.473   618   618 I Magisk  : Magisk v20.1-59fd38bb(20001) daemon started
02-05 05:13:14.485   618   619 D Magisk  : resetprop: getprop [ro.crypto.state]: [encrypted]
02-05 05:13:14.485   618   619 D Magisk  : resetprop: getprop [init.svc.vold]: [running]
02-05 05:13:14.499   618   619 I Magisk  : ** post-fs-data mode running
02-05 05:13:14.503   618   619 I Magisk  : * Initializing Magisk environment
02-05 05:13:14.506   618   619 I Magisk  : * Mounting mirrors
02-05 05:13:14.506   618   619 I Magisk  : mount: /sbin/.magisk/mirror/vendor <- /sbin/.magisk/block/vendor
02-05 05:13:14.506   618   619 I Magisk  : mount: /sbin/.magisk/mirror/data <- /sbin/.magisk/block/data
02-05 05:13:14.507   618   619 I Magisk  : link: /sbin/.magisk/mirror/system <- /sbin/.magisk/mirror/system_root/system
02-05 05:13:14.507   618   619 I Magisk  : link: /sbin/.magisk/mirror/product <- /sbin/.magisk/mirror/system/product
02-05 05:13:14.507   618   619 I Magisk  : * Setting up internal busybox
02-05 05:13:14.521   618   619 I Magisk  : * Running post-fs-data.d scripts
02-05 05:13:14.525   618   619 I Magisk  : Upgrade / New module: ViPER4AndroidFX-Legacy
10-23 09:08:56.811   618  1256 I Magisk  : ** late_start service mode running
10-23 09:08:56.812   618  1256 I Magisk  : * Running service.d scripts
10-23 09:09:11.425   618  3527 I Magisk  : ** boot_complete triggered
10-23 09:09:11.432   618  3527 E Magisk  : su: cannot find manager
10-23 09:09:11.528  3549  3549 I Magisk  : apk_install: /data/magisk.apk
10-23 09:09:13.077  3851  3851 I Magisk  : apk_install: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
10-23 09:09:13.086   618  3527 E Magisk  : su: cannot find manager
10-23 09:09:21.928   618  5680 D Magisk  : su: request from pid=[5616], client=[6]
10-23 09:09:21.928   618  5680 D Magisk  : su: request from uid=[10132]
10-23 09:09:21.940   618  5680 D Magisk  : su: waiting child pid=[5683]
10-23 09:09:21.940  5683  5683 D Magisk  : su: fork handler
10-23 09:09:21.945  5683  5683 D Magisk  : su: use global namespace
10-23 09:10:43.621   618  9308 D Magisk  : su: request from pid=[9307], client=[7]
10-23 09:10:43.621   618  9308 D Magisk  : su: request from uid=[10146]
10-23 09:10:43.622   618  9308 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
10-23 09:10:43.627   618  9308 D Magisk  : su: waiting child pid=[9311]
10-23 09:10:43.628  9311  9311 D Magisk  : su: fork handler
10-23 09:10:43.628  9311  9311 D Magisk  : su: use namespace of pid=[9307]
10-23 09:10:43.656   618  9308 D Magisk  : su: return code=[0]
10-23 09:10:43.683   618  9314 D Magisk  : su: request from pid=[9313], client=[8]
10-23 09:10:43.683   618  9314 D Magisk  : su: request from uid=[10146]
10-23 09:10:43.697   618  9314 D Magisk  : su: waiting child pid=[9326]
10-23 09:10:43.697  9326  9326 D Magisk  : su: fork handler
10-23 09:10:43.701  9326  9326 D Magisk  : su: use namespace of pid=[9313]
10-23 09:10:43.822   618  9314 D Magisk  : su: return code=[123]
10-23 09:18:26.181   618 14873 D Magisk  : su: request from pid=[14868], client=[7]
10-23 09:18:26.181   618 14873 D Magisk  : su: request from uid=[10133]
10-23 09:18:26.182   618 14873 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
10-23 09:18:26.187   618 14873 D Magisk  : su: waiting child pid=[14876]
10-23 09:18:26.187 14876 14876 D Magisk  : su: fork handler
10-23 09:18:26.188 14876 14876 D Magisk  : su: use namespace of pid=[14868]

**Comment by topjohnwu** [comment]
According to the logs, core only mode is not enabled
