### ISSUE TITLE
Latest canary (23/10/2019) is failing to hide, creating a launch loop

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#1971]
Hey @topjohnwu 

As the title says, hide function is broken with the recent release.

I'm attaching a logcat and a screen record demonstrating the issue.

[b.log](https://github.com/topjohnwu/Magisk/files/3762184/b.log)

[Demonstrating Video](https://send.firefox.com/download/04d9cee3cc25190c/#wsN2ZHH-oVy4uplLG1jRWw)

I'm on OnePlus6 with the recent Android 10 Beta release.

**Comment by DenyDarko** [comment]
To update the issue, after I put down the device to open this issue, I launched MagiskManager once more and then after I tapped "Yes" it didn't loop and worked.

There is a glitch somewhere though.

**Comment by topjohnwu** [comment]
Yes, there are some issues with R8, and it was fixed
