### ISSUE TITLE
[Mi A1] Different OTA procedure with latest monthly update?

### ISSUE THREAD

**Issue by teohhanhui** [topjohnwu/Magisk#1976]
I've always followed the OTA installation procedure here: https://topjohnwu.github.io/Magisk/tutorials.html#ota-installation

However, with the latest monthly update (October 2019) for Mi A1 (tissot), it seems like there's a conflict(?) in switching the active slot, i.e.

Active slot before OTA: `b` (presumably)
Active slot after OTA + "Install to Inactive Slot (After OTA)" + reboot: `a` (confirmed with `fastboot getvar ...`)

Which seems correct. However, the system refused to boot, with the error message "The system has been destroyed".

I thought something went wrong with the OTA / Magisk install, so I did `fastboot set_active b` hoping to just boot back into the previous slot. However, to my surprise, the system was updated (and root was not lost), and I've confirmed that the current active slot has actually been automatically switched to `a`! (By the post-OTA script at first boot?)

So, does this mean there's been a change in how OTA updates are applied on this device? Or is it just a bug in Magisk Manager?

**Comment by topjohnwu** [comment]
There are many possible reasons why an OTA will fail, Magisk Manager simply just installs Magisk on the second slot. I cannot help you with all possibility of failures, unfortunately.

**Comment by teohhanhui** [comment]
Hi, as I've explained in the OP, the OTA did not fail. It seems like I had to switch the active slot back to the previous one for the OTA to complete successfully.
