### ISSUE TITLE
Magisk manager changes back to system language after opening settings

### ISSUE THREAD

**Issue by towlie** [topjohnwu/Magisk#1977]
(Using latest canary Debug)
 Steps to reproduce:
- use a device with non english default language
- set language to english 
- restart app (clear cache) 
- return to main screen of magisk manager

Now you will see non english translations for example the "update check" on the main page.

For better understanding I made a video of this issue:
https://drive.google.com/file/d/10xCooM95DSIApZskql9Bdv-QDYvhW698/view?usp=sharing

**Comment by RikkaW** [comment]
The manager app uses [applyOverrideConfiguration](https://github.com/topjohnwu/Magisk/blob/78daa2eb62fefde8ad7049d3224572b2819b7bbc/app/src/main/java/com/topjohnwu/magisk/base/BaseActivity.kt#L49) to implement custom locale. But the `applyOverrideConfiguration` is called only from the DayNight implementation of appcompat. According to my experience, DayNight from appcompat is not reliable from the first day.

So I choose to update configuration in `attachBaseContext` and it has never been reported to have problems from years ago.

```
override fun attachBaseContext(newBase: Context) {
    val configuration = newBase.resources.configuration
    // change configuration
    super.attachBaseContext(newBase.createConfigurationContext(configuration))
}
```
