### ISSUE TITLE
Magisk crash / FATAL exception (Could not read database)

### ISSUE THREAD

**Issue by towlie** [topjohnwu/Magisk#1978]
Log: https://gist.github.com/towlie/90d548d2e12da9d25e795512259081f1
 
Quote from log:
> 10-24 14:18:46.159   634  2802 D Magisk  : magiskdb: query magiskhide=[1]
>--------- beginning of crash
>10-24 14:18:48.691   634  3096 D Magisk  : su: request from pid=[3091], client=[7]

I guess this isn't helpful and I can't see any downsides by this crash. I looked through logcat and didn't find anything magisk related.
Is there anything I can do to find the cause of this crash?

----

# Update
Let's have a look at this: https://gist.github.com/towlie/809af865ad8ee843e7dc8b6dcd2d16a1
com.A6jnho.yXyp.Jr7P is hidden magisk manager.

**Comment by towlie** [comment]
Core only mode log: https://gist.github.com/towlie/e7d180802c4f36502daa469d25a3b44a

Also it does only happen on my android 9 device. I also have an android 7 device which doesn't have this crash notice.

**Comment by Didgeridoohan** [comment]
https://didgeridoohan.com/magisk/Magisk#hn_Beginning_of_crash

**Comment by towlie** [comment]
Interesting. I wonder what causes this. I thought this was related to magisk because this didn't happen with the canary version I used before.

**Comment by towlie** [comment]
Let's have a look at this: https://gist.github.com/towlie/809af865ad8ee843e7dc8b6dcd2d16a1
com.A6jnho.yXyp.Jr7P is hidden magisk manager.

**Comment by topjohnwu** [comment]
Delete the repackaged APK and start from scratch with the original Magisk Manager

**Comment by towlie** [comment]
I did a clean install and it still happens.

**Comment by towlie** [comment]
Here is a proof that this error was introduced with the latest changes.
https://gist.github.com/towlie/af9e4897578ac683a2ac700b295693d4

I was running the builds from 13 days ago.
https://github.com/topjohnwu/magisk_files/blob/5ca00f6806cec673ca02f21c10451ec63b3eed20/magisk-release.zip
