### ISSUE TITLE
Install fail，not support my ramdisk（file type gunzip）

### ISSUE THREAD

**Issue by qiurigao** [topjohnwu/Magisk#198]
*****************************
Magisk v12.0 Boot Image Patcher
*****************************
- Mounting /system(ro), /cache, /data
- Device platform: arm
- Constructing environment
- /data/magisk.img detected!
mount: permission denied (are you root?)
- Mounting /data/magisk.img to /magisk
- Found Boot Image: /dev/block/mmcblk0p21
- Unpacking boot image
Cannot open /dev/block/mmcblk0p21

MagiskBoot (by topjohnwu) - Boot Image Modification Tool

! Unable to unpack boot image
Updater 过程结束，错误：1
I:Legacy property environment disabled.
I:Install took 2 second(s).

boot.img: [https://github.com/qiurigao/vivo_y55/raw/master/Boot/vivo_y55_boot_no_verity_crypt-1.16.6.img](url)

**Comment by topjohnwu** [comment]
Your recovery is not working properly, its not running in root.  
Recovery有問題，跟boot種類無關
