### ISSUE TITLE
app detects /sbin/su binary

### ISSUE THREAD

**Issue by EvoxOG** [topjohnwu/Magisk#1981]
With the latest canary build I have repackaged magisk to a different name and used magisk hide to hide the app but it still detects root if I uninstall Magisk the app works fine So I installed an app that detects where root is been found and it says "/sbin/su" and i also tried to hide that app but it does nothing. How do I go about hiding /sbin/su?

**Comment by topjohnwu** [comment]
Add the app to the hide list

**Comment by akbar091202** [comment]
> Add the app to the hide list

doesn't work, is there another way?
