### ISSUE TITLE
[HELP] Installing on Pixel 3a XL on Android 10

### ISSUE THREAD

**Issue by scottismyname** [topjohnwu/Magisk#1983]
I don't think there is an issue with Magisk, however I am having trouble. 

I just got my P3aXL brand new from Google.  Here are the steps I took once I got my phone:

-  I updated to the latest October security patches using stock Android. 
- Once it was on the latest, enabled OEM unlocking inside android.
- Rebooted to bootloader and unlocked.
- Booted back into Android, setup my account.  
- Installed latest magisk manager (7.3.5)
- Downloaded October system image (bonito-qp1a.191005.007).
- Extracted boot.img from the large zip file
- Copied boot.img to phone.
- Inside magisk manager, clicked install, selected boot.img from phone.
- Copied magisk_patched.img from download directory on phone back to my PC.
- Rebooted to bootloader and ran `fastboot flash boot magisk_patched.img`.
- From fastboot, ran `fastboot reboot`

At this point the system bootloops like 3 or 4 times, then stays in bootloader mode saying no valid boot slot.  I can fix it by reflashing the factory image (removing the -w from flash-all.bat).  

Not sure where to go from here.

I am on the latest version of the sdk tools (v29).

Any help debugging this issue would be great!

I am not new to rooting at all, so I'm comfortable with almost any tool/command line things I can try.

**Comment by skittles9823** [comment]
Try using `fastboot boot magisk_patched.img` first to see if it'll boot the image.

If that works then do `fastboot flash boot_<slot letter> magisk_patched.img` so boot_a or boot_b depending on what it shows you in fastboot.

I've got a 3a xl as well and I'm rooted just fine on the latest security patch.

**Comment by topjohnwu** [comment]
No help is provided on Github issues
