### ISSUE TITLE
Magisk hide not working?

### ISSUE THREAD

**Issue by TICG** [topjohnwu/Magisk#199]
I have built magisk newest commits. 0 errors, however magisk hide is unavailable.

**Comment by TICG** [comment]
However in magisk, I have this.
"--------- beginning of main
05-13 00:08:10.735 I/Magisk  ( 3068): ** post-fs mode running
--------- beginning of system
05-13 00:08:11.423 I/Magisk  ( 3068): ** post-fs-data mode running
05-13 00:08:11.423 I/Magisk  ( 3068): * Mounting /data/magisk.img
05-13 00:08:11.433 I/Magisk  ( 3068): * Running post-fs-data.d scripts
05-13 00:08:11.434 I/Magisk  ( 3068): * Loading modules
--------- beginning of crash
05-13 00:09:12.778 I/Magisk  ( 3255): Magisk v14.0 daemon started
05-13 00:09:12.779 E/Magisk  ( 3255): mkdir /magisk 493 failed with 17: File exists
05-13 00:09:12.786 I/Magisk  ( 3255): ** late_start service mode running
05-13 00:09:13.618 I/Magisk  ( 3255): * Running service.d scripts
05-13 00:09:13.618 I/Magisk  ( 3255): * Running module service scripts
05-13 00:10:00.093 E/Magisk  ( 9279): fopen: /magisk/.core/magiskhide/hidelist failed with 2: No such file or directory
05-13 00:13:02.244 E/Magisk  (17646): fopen: /magisk/.core/magiskhide/hidelist failed with 2: No such file or directory
05-13 00:16:44.306 E/Magisk  (19551): fopen: /magisk/.core/magiskhide/hidelist failed with 2: No such file or directory
05-13 00:16:56.572 E/Magisk  (19667): fopen: /magisk/.core/magiskhide/hidelist failed with 2: No such file or directory"

**Comment by topjohnwu** [comment]
This should be fixed a long time ago

**Comment by JackTheDipper** [comment]
Great thanks for Magisk, @topjohnwu.

Just one question to get the point. When I'm searching the issues for "hidelist" or similar things, I end up in this thread and cannot find a properly closed issue with a description, commit reference, whatsoever. 

So, when was this fixed? I have exactly the same error running Magisk v13.2 with MagiskManager 5.0.6. Apparently, Magisk doesn't save any preferences, but I have to reconfigure after every boot.

Has it been fixed later ("long time ago"?!") or should it be fixed in v13.2 already? In the latter case, it isn't fixed, obviously ;-)

**Comment by saltyzip** [comment]
I have exact same issue, driving me nuts. Running v13.3 and v5.1.1.

**Comment by saltyzip** [comment]
--------- beginning of main
I(  273:  273) Magisk v13.3(1330) daemon started
I(  273:  275) ** post-fs mode running
--------- beginning of system
I(  273:  288) ** post-fs-data mode running
I(  273:  436) ** late_start service mode running
I(  273:  436) * Running service.d scripts
--------- beginning of crash
I(  273:11716) * Starting MagiskHide
I(  273:11716) hide_utils: Hiding sensitive props
I(  273:11716) hide_list add: [com.google.android.gms.unstable]
E(  273:11716) fopen: /magisk/.core/hidelist failed with 2: No such file or directory
I(  273:11716) proc_monitor: init ns=mnt:[4026531840]
I(  273:11716) proc_monitor: zygote ns=mnt:[4026545107]
I(  273:11716) proc_monitor: com.google.android.gms.unstable (PID=11748 ns=mnt:[4026545332])
I(11761:11761) hide_utils: Re-linking /sbin

**Comment by pluim007** [comment]
I have the exact same problem: Fresh install, but no succes!

--------- beginning of main
03-19 16:12:34.630  1173  1173 I Magisk  : Magisk v13.3(1330) daemon started
03-19 16:12:34.632  1173  1175 I Magisk  : ** post-fs mode running
--------- beginning of system
03-19 17:12:35.030  1173  1187 I Magisk  : ** post-fs-data mode running
03-19 17:12:35.051  1173  1187 I Magisk  : * Mounting /data/magisk.img
03-19 17:12:35.081  1173  1187 E Magisk  : mount /dev/block/loop1->/magisk failed with 22: Invalid argument
03-19 17:12:35.986  1173  1358 I Magisk  : ** late_start service mode running
08-03 15:20:21.296  1173  1358 I Magisk  : * Running service.d scripts
08-03 15:20:21.296  1173  1358 I Magisk  : * Running module service scripts
08-03 15:22:13.286  1173  8687 I Magisk  : * Starting MagiskHide
08-03 15:22:13.287  1173  8687 I Magisk  : hide_utils: Hiding sensitive props
08-03 15:22:13.287  1173  8687 I Magisk  : hide_list add: [com.google.android.gms.unstable]
08-03 15:22:13.318  1173  8687 E Magisk  : fopen: /magisk/.core/hidelist failed with 2: No such file or directory
08-03 15:22:13.319  1173  8687 I Magisk  : proc_monitor: init ns=mnt:[4026531840]
08-03 15:22:15.384  1173  8687 I Magisk  : proc_monitor: zygote ns=mnt:[4026535384] zygote64 ns=mnt:[4026535375]
08-03 15:22:29.702  1173  8687 I Magisk  : proc_monitor: com.google.android.gms.unstable (PID=9444 ns=mnt:[4026535422])
08-03 15:22:29.704  9449  9449 I Magisk  : hide_utils: Re-linking /sbin

**Comment by saltyzip** [comment]
I managed to fix mine, working beautiful now.

After install of magisk I didn't wait long enough on first reboot of phone. You must wait for it to complete, do not be impatient and think it's stuck and force a reboot.
