### ISSUE TITLE
Oneplus 7 pro not working

### ISSUE THREAD

**Issue by Mister-Hope** [topjohnwu/Magisk#1990]
![Screenshot_20191026-183857](https://user-images.githubusercontent.com/33315834/67618286-e7508800-f81f-11e9-9703-4c2267ac0b66.jpg)
I am an experienced user, but I got problems now. The magisk think it is working, and I can install amd uninstall modules with no errors, but none of the module works. Is it my phone's problem or magiskV20? I tried to reboot and reinstall magisk in twrp, but nothing works.
![Screenshot_20191026-184215](https://user-images.githubusercontent.com/33315834/67618316-5c23c200-f820-11e9-9e52-557440fb0413.jpg)
![Screenshot_20191026-184211](https://user-images.githubusercontent.com/33315834/67618317-5ded8580-f820-11e9-839e-2ab13589ec74.jpg)

**Comment by Mister-Hope** [comment]
Besides, root are working well

**Comment by RikkaW** [comment]
Again, enable core only mode and start to complain.

"I am an experienced user".

**Comment by Mister-Hope** [comment]
So this feature is disabled by default in magiskV20?

**Comment by Mister-Hope** [comment]
I did not open it after install and I didn' see, Mr.Nobody @RikkaW . Besides I didn't see this breaking changes on the xda thread.

Also, when do you plan to respown your storage rediect bot? Some requested has opened half a year
