### ISSUE TITLE
I can't mount anything in /product

### ISSUE THREAD

**Issue by Dr-TSNG** [topjohnwu/Magisk#1992]
My device is Huawei. I asked this question before and you said "It means that folder does not exist for some reason , Magisk wll remove files that is not safe to mount." But I find that actually I can't mount not only that folder I mentioned before but anything in /product,so is this a bug of magisk or Huawei system?
Additionally, I find that Huawei devices have both /product and /system/product , and I want to mount something in /product , maybe this is the problem.

**Comment by topjohnwu** [comment]
If `/system/product` is not a symlink to `/product`, then Huawei is doing some stupid crap, and I do not plan to support it. There will be no way for me to make things consistent over the board.
