### ISSUE TITLE
Redmi Note 8 Pro Magisk support

### ISSUE THREAD

**Issue by damianlavalle** [topjohnwu/Magisk#1993]
Not sure if this is the right place for this kind of request, if not, I do apologize. But I'm kinda stuck looking for options for this particular case. It's not for lack of trying, but quite simply every version and every installation method results in the same, bootloops. I've got a Global (EU) Redmi Note 8 Pro and I've ken the extra steps to ensure it has a fully unlocked bootloader and I have attempted to install magisk through twrp, fastboot (sdk), "odin mode" fastboot on the device, be it a patched bin or a zip versions 17 to 20. There's alot of "how to" but I haven't actually seen any actual successes, everyone is just copying the same thing from each other and most of them haven't verified a thing, after all, the phone was just bearly released about 10 days ago. In any case, I'm happy to provied any logs or testing, I haven't even bothered to put any data back on the phone cuz I'm just expecting to have to wipe it again trying to get Magisk working on it.

**Comment by topjohnwu** [comment]
Read the official instructions, it covers all sorts of scenarios.
