### ISSUE TITLE
三星c7pro无法正常开机

### ISSUE THREAD

**Issue by suiyunye** [topjohnwu/Magisk#1994]
三星c7010，官方系统，安卓8.0，稳定版Magisk版本：v20.0在刷入后开机卡在第一屏这里（显示我修改了内核）无法进入系统，我是通过修改boot.img刷入的，附boot.img
以前修补的19.0，19.2都可以顺利的刷入

[boot.zip](https://github.com/topjohnwu/Magisk/files/3775480/boot.zip)

**Comment by w2016561536** [comment]
我a60也这毛病，等下一个magisk更新

**Comment by w2016561536** [comment]
作者推送了20.1更新，a60实测可以刷入并正常启动（我点直接更新的）
