### ISSUE TITLE
After update to Android 10, error code in /sdcard

### ISSUE THREAD

**Issue by Crabor** [topjohnwu/Magisk#1997]
I can`t find the magisk....
![Snipaste_2019-10-27_20-54-14.png](https://i.loli.net/2019/10/27/NGQsrUZ4MOEztpf.png)

**Comment by osm0sis** [comment]
TWRP just can't decrypt /data anymore. This has nothing at all to do with Magisk. Please close the issue.

https://twrp.me/site/update/2019/10/23/twrp-and-android-10.html
