### ISSUE TITLE
Unable to read sensors

### ISSUE THREAD

**Issue by danielcr12** [topjohnwu/Magisk#2]
after flashing magisk on my moto x (2013) the moto doze app is not able to read/change/update the status of the sensors of the device. therefore light sensor, gyro, touchscreen, motion sensor, nothing works, the good part is that magisk itself seems to work. (i was able to test this by using vysor to remote controll my phone. here i add some logs, hope this helps to norrow the issue.

i first installed supersu in systemless mode
then installed the magisk manager app and proceed to install magisk
rebooted.

Device: Moto X 2013
Android Version: CM13 (Marmsmallow 6.0.1)
Kernel: CM built in kernel

im adding all logs and info i could get.

[Stcock_cm_boot.img.gz](https://github.com/topjohnwu/Magisk/files/507466/Stcock_cm_boot.img.gz)
[magisk.txt](https://github.com/topjohnwu/Magisk/files/507471/magisk.txt)
[liveboot.txt](https://github.com/topjohnwu/Magisk/files/507473/liveboot.txt)
[moto_boot_stockt](https://app.box.com/s/ux9mjzh6jn5c2cc737hv5bwgk0f5jbor)
[magisk_log.txt](https://github.com/topjohnwu/Magisk/files/507477/magisk_log.txt)
![screenshot_20161003-205727](https://cloud.githubusercontent.com/assets/12722871/19059412/3302cf78-89b6-11e6-8698-cf588d47e355.png)
![screenshot_20161003-205203](https://cloud.githubusercontent.com/assets/12722871/19059413/330f8d6c-89b6-11e6-9f60-088b110aa2e9.png)

**Comment by topjohnwu** [comment]
I assume the sensors are linked to dtb image. Thanks for providing the info!

**Comment by Rahh1112** [comment]
I'm having similar issue too.. after flashing magisk (v7), the sensors don't respond.. and i'm unable to touch the screen

**Comment by topjohnwu** [comment]
Finally fixed in 1f3b81338cdcc010facb479a1e05534f355b4368
I'm just too lazy to check the code... sorry for the delay

**Comment by die-microsoft** [comment]
Screen rotate, gyro, magnetic, and other sensors not working on LineageOS 17.1 on a LG G5 H850.

**Comment by channel0** [comment]
Is there a way other than initialization in this case?  Or do I have to wait for the next version?
