### ISSUE TITLE
 Magisk is not installed after update MIUI 7.5.11

### ISSUE THREAD

**Issue by szamuka** [topjohnwu/Magisk#200]
I updated MIUI 7.5.11 via TWRP, when phone was turn on then shows magisk is not installed.

![magis](https://cloud.githubusercontent.com/assets/21019458/26024677/a1955158-37d6-11e7-8887-fe5218992307.png)

**Comment by JonnyTech** [comment]
After an update, you need to flash Magisk from recovery. The ROM replaces boot.img on your device. It must be modified by the Magisk installer for it to work. This is common with all systems, not just yours.
