### ISSUE TITLE
Magisk19.4及以上版本严重bug,导致boot stuck on splash screen

### ISSUE THREAD

**Issue by z826540272** [topjohnwu/Magisk#2004]
自从magisk19.4更改了挂载点之后,发现使用一些软件修改/system分区会导致重启后无法开机,更甚至使用resetprop方式的module修改prop也有几率导致无法开机.

经过多次测试验证,发现使用这一款app https://play.google.com/store/apps/details?id=com.jumobile.manager.systemapp 系统程序安全卸载器 可以 100%触发无法开机的故障.
测试步骤是先使用 root explorer 挂载根目录为 rw, 然后使用 系统程序安全卸载器 卸载任意系统软件,并重启,一定会无法开机.

然后我将 手机上更改过的 system img 与刷机包原始image档案进行对比, 发现 系统程序安全卸载器 确实只是删除了其中一个apk文件,但是就会造成开机卡第一屏,这时候,把这个文件放回去,也无法将手机重新开机,解决办法唯有重新刷system档或者切换slot.
      通过 Root Explorer 删除同样的文件,重启开机却无任何问题.重刷system档后可以开机,怀疑system档案被破坏,但是在ubuntu上mount后和原始image 使用bcompare软件进行对比,发现更改的只是少了一个文件.至此我就无法再继续排查原因了.

事件2
修改系统build.prop后卡在开机动画,随进入第二系统挂载上一个slot修改回去,仍然无法开机.
事件3
后来我只通过module方式修改prop参数,但是今天这次修改过后又发生了卡在开机动画的问题,同样,删除module或更改回去并不能解决问题,但是切换到另一个slot系统却可以正常启动.
查看adb logcat,大概只记得停留在这段
servicemanager: waiting for service 'media.audio_policy' on '/dev/binder'
个人无法判断出问题根源

现在切换回19.3版本,使用 系统程序卸载器 更改系统分区发现并无异常,可以正常重启.
机型 黑鲨Helo AWM-A0
安卓版本 9.0
启用加密,关闭DM校验,测试版本 magisk 20.0 & 19.3

随机性无法开机让人恐惧.

**Comment by topjohnwu** [comment]
從 19.4 開始，system as root 得 mount point 將改為 `/`，這個我無法變更，起要求 system app manager 更新。

**Comment by topjohnwu** [comment]
另外一種可能，就是你得 AVB 沒有被完全關閉，請在安裝時進入進階選項，確認 AVB 將會被關閉
