### ISSUE TITLE
Pad Images to Original Size With Zeros

### ISSUE THREAD

**Issue by Sudrien** [topjohnwu/Magisk#2005]
Running a Moto g7 power & magisk manager 7.3.5 (243) - no TWRP - so I use boot.img patching

I upload my boot.img, patch with manager, download the new image do the usual 

> fastboot flash boot magisk_patched.img

...and it fails. However, if I pad the file to the same size as boot.image - in my case, using

> dd if=/dev/zero of=magisk_patched.img bs=1 count=1 seek=33554431

It succeeds.

Could this file padding be added to the usual process?

**Comment by osm0sis** [comment]
Simpler would be to zero the target partition before flashing the new image.

**Comment by Sudrien** [comment]
Doesn't that script require elevated permissions? I don't have those yet.

As far as I'm aware I can only run patching while unrooted
https://github.com/topjohnwu/Magisk/blob/master/scripts/boot_patch.sh#L186

Once rooted I can do the direct install.

**Comment by osm0sis** [comment]
Fair point then.

**Comment by astafyev** [comment]
I might have the same issue. My Redmi K20 is flashed with http://bigota.d.miui.com/V11.0.2.0.PFJEUXM/miui_DAVINCIEEAGlobal_V11.0.2.0.PFJEUXM_e32b086df3_9.0.zip firmware and original boot.img has 128MB size. It is zero-padded, but I see 'AVBf' AVBv2 signing footer at the end.
Patched image has 16MB size and I haven't found any signature.
As a result I have bootloop, phone tries to boot, fails and automatically goes to recovery.

**Comment by dkgitdev** [comment]
Maybe these issues is connected as well?

https://github.com/topjohnwu/Magisk/issues/1998
https://github.com/topjohnwu/Magisk/issues/2008

**Comment by astafyev** [comment]
Looks absolutely similar to me.

**Comment by osm0sis** [comment]
Actually a not zeroed partition would leave trailing avb2 footer and such from the previous signed image. :+1:

**Comment by osm0sis** [comment]
So, ignoring all the unconnected Redmi issues people started hijacking this issue thread with...

@Sudrien, does `fastboot erase boot` before you flash magisk_patched.img have any effect?

**Comment by Sudrien** [comment]
> fastboot erase boot
> Erasing 'boot_a'                                   (bootloader) Permission denied
> FAILED (remote: '')
> fastboot: error: Command failed

...so that would be a no.

**Comment by osm0sis** [comment]
Interesting, that would have fixed the issue for you. How nice of Motorola to disable that command. 🙄

So yeah, on your device I guess the only option is to zero pad to the length of the boot partition.

**Comment by Sudrien** [comment]
Interestingly, it does seem the zero padding is necessary only after I flash the unpatched boot.img to allow security updates to be install (with magisk_patched.img flashed, and I get a continuous stream of failure notifications). I think it must be the security update writing the signature, not boot.img itself.

**Comment by osm0sis** [comment]
Well you can't take am OTA over a patched boot.img, so...

**Comment by osm0sis** [comment]
Best idea I can think of is @topjohnwu could provide a checkbox option in Magisk Manager to zeropad magisk_patched.img to the length of the original dumped boot.img when it's set to Patch Image mode for weird devices such as yours, since it would be a waste of space and bandwidth to force the larger files on everyone (some boot partitions are up to 128mb nowadays).

**Comment by osm0sis** [comment]
@diareuse, when you guys add "output image creation options" for Safe Mode please also see about adding a feature to pad the magisk_patched.img as I described in my last comment. :+1:

**Comment by zgfg** [comment]
> I might have the same issue. My Redmi K20 is flashed with http://bigota.d.miui.com/V11.0.2.0.PFJEUXM/miui_DAVINCIEEAGlobal_V11.0.2.0.PFJEUXM_e32b086df3_9.0.zip firmware and original boot.img has 128MB size. It is zero-padded, but I see 'AVBf' AVBv2 signing footer at the end.
> Patched image has 16MB size and I haven't found any signature.
> As a result I have bootloop, phone tries to boot, fails and automatically goes to recovery.

Btw, I have also K20, and I was patching and flashing MIUI 10, 11 and 12 (ibcl. that same PFJEUXM 11.0.2) with no problems whatsoever - however it was import to disable Recovery mode (and to keep enabled Encryption and AVB - two options removed now in the latest Cabary)

**Comment by osm0sis** [comment]
@topjohnwu I believe the logic in your solution is still flawed.. magiskboot shouldn't pad it during repack.

It should be a separate command perhaps, so external signing can occur first. I see you excluded ChromeOS already, but AVBv1 would also be a problem since it would shrink again from signing but then wouldn't be padded anymore.

**Comment by zgfg** [comment]
By comparing the padding between my original stock boot img:
https://mega.nz/file/wo1BgIoL#RWXjmk8AOV6MxtstgYFMDtyUjjqQJLtCTpoYRd38z68

and the magisk_patched.img patched  by Canary 301/20407:
https://mega.nz/file/ExEGxBAY#VqABVkVdkJOnNvi0mNgfS3tTvy_orlMKMv7IZZRgx6E

I see a difference in the last 64 bytes.
Patched iimage contains only zeroes while the stock image contains some signature:
![Screenshot_2020-10-02-22-25-14-495_com offsec nhterm](https://user-images.githubusercontent.com/51943147/94966923-61908e80-04fe-11eb-94ef-74078f79a7aa.jpg)
![Screenshot_2020-10-02-22-11-26-765_com offsec nhterm](https://user-images.githubusercontent.com/51943147/94967000-8a188880-04fe-11eb-9dda-3e5ca0b7045f.jpg)

However, for my Xiaomi Mi 9T (MIUI 12/Android 10) it doesn't matter, that full-size magisk_patched.img padded with all zeroes can be successfuly flashed and used for booting to Magisk

**Comment by osm0sis** [comment]
Yeah that's just the AVBv2 footer, that's unrelated.

**Comment by topjohnwu** [comment]
@osm0sis if AVBv1 signing shrinks the image, it should be fixed on that side.
Padding is not necessary in 99% of the time, so this is not considered a bug.

**Comment by osm0sis** [comment]
@topjohnwu, if you could remove the padding from magiskboot or make it a separate argument/feature within magiskboot it would be relatively simple to implement it for all using script.
