### ISSUE TITLE
Why i build magiskinit is ELF executable for Android 16, non-PIE executables

### ISSUE THREAD

**Issue by youling257** [topjohnwu/Magisk#2007]
./build.py stub
./build.py binary magisk magiskinit

Magisk/native/out/arm64-v8a/magisk:              ELF shared object, 64-bit LSB arm64, dynamic (/system/bin/linker64), for Android 21, BuildID=d87ef49a98b51f5df5f7917570c40be7900315d0, stripped

Magisk/native/out/armeabi-v7a/magisk:            ELF shared object, 32-bit LSB arm, dynamic (/system/bin/linker), for Android 16, BuildID=aec942fa58b2b51fdcebf6f7a9388a136ba419bc, stripped
Magisk/native/out/armeabi-v7a/magiskinit:        ELF executable, 32-bit LSB arm, for Android 16, BuildID=ceebc76d126e15f1937fb61569cbd7e3c22563e5, static, stripped
Magisk/native/out/armeabi-v7a/magiskinit64:      ELF executable, 32-bit LSB arm, for Android 16, BuildID=54d25c0f0c89b5d3c700ad2e519ffb86695b08fe, static, stripped

Magisk/native/out/x86/magisk:                    ELF shared object, 32-bit LSB 386, dynamic (/system/bin/linker), for Android 16, BuildID=84bc789716dcdb1e13e54ae8493910594772fc65, stripped
Magisk/native/out/x86/magiskinit:                ELF executable, 32-bit LSB 386, for Android 16, BuildID=720d892ee3bca8766f551e422912b964e7d81664, static, stripped
Magisk/native/out/x86/magiskinit64:              ELF executable, 32-bit LSB 386, for Android 16, BuildID=16ecc842e0a2792d922f382b37db0e8e1177f6e4, static, stripped

Magisk/native/out/x86_64/magisk:                 ELF shared object, 64-bit LSB x86-64, dynamic (/system/bin/linker64), for Android 21, stripped

**Comment by youling257** [comment]
I follow the instructions, Building Environment Requirements, Building Notes and Instructions
final build succeed, but used magiskinit on Android 9 not work, the binary non-PIE executables.

**Comment by topjohnwu** [comment]
Use FrankeNDK to build binaries.
