### ISSUE TITLE
Redmi Note 8 Pro 6/128 CN version

### ISSUE THREAD

**Issue by ZheniOK** [topjohnwu/Magisk#2008]
Hi, tried patching boot.img with latest Magisk Canary as it was recommended in the [previous issue](https://github.com/topjohnwu/Magisk/issues/1998) and still getting a bootloop .
What details would help you to find the issue ?
Please find the patched boot img and the original one attached
Thanks

[RN8ProBootPatched.zip](https://github.com/topjohnwu/Magisk/files/3787826/RN8ProBootPatched.zip)

**Comment by astafyev** [comment]
I have the same issue with Redmi K20 CN 8/256.

**Comment by osm0sis** [comment]
Let's continue here. Has Magisk ever worked on this device?

**Comment by astafyev** [comment]
For my case it's brand new phone and Magisk has never worked here, I mean nobody tried.

**Comment by pasha-zzz** [comment]
Magisk works fine on any Global versions of same device. But on CN we have bootloop

**Comment by astafyev** [comment]
Interesting. My CN phone Redmi K20 is flashed with EEA firmware for Mi 9T, so it's not a native firmware for it. While for Global version phone (Mi 9T) it's native. My FW version can be found at http://bigota.d.miui.com/V11.0.2.0.PFJEUXM/miui_DAVINCIEEAGlobal_V11.0.2.0.PFJEUXM_e32b086df3_9.0.zip. So one can download and look into original boot.img.

**Comment by dkgitdev** [comment]
There's a rumor that if you wipe the phone before / after boot flashing, everything goes into normal -- maybe someone can try it?

**Comment by dkgitdev** [comment]
Wipe of the Data Partition just made it boot...

**Comment by dkgitdev** [comment]
The latest Canary version and Latest Stable both said that I should reinstall magisk -- it get's to safety net checks, though no module can install onto it. testing with 19.4.

**Comment by dkgitdev** [comment]
This seems like a partial solution (to make GPay work, although I did NOT tested GPay exactly), but we still lack the modules support

**Comment by dkgitdev** [comment]
Well, I've tested on GPay and it doesn't work.

**Comment by dkgitdev** [comment]
But the root access DOES work. So, can anyone answer some of the following questions:

1. Why the system boots after I format data partition, although the only affected partition is boot?
2. Why does the root access work?
3. Why don't the magisk modules work?
4. Why does magisk say something like "you need to install magisk again" and won't boot after installation?

**Comment by towlie** [comment]
> 1. Why the system boots after I format data partition, although the only affected partition is boot?

I can confirm this one for my MI 9T PRO EEA Version. (But I cannot confirm point 2. 3. and 4. for my device.)
After flashing magisk it will bootloop until you wipe data / factory reset. If you flash magisk again then everything will work.
To make it bootloop again by installing magisk, I would have to reflash the whole rom again.

Maybe the data encryption or some integrity check is depending on the boot image?

**Comment by dkgitdev** [comment]
Mate!!! It DID work! Thank you so much.

Final flashing instructions:

1. Flash magisk
2. Wipe `data`
3. Flash magisk again

**Comment by ZheniOK** [comment]
@dkgitdev so is it possible to use GPay after that ? All I need is to get root for installing patch for GPay and Adblock

**Comment by topjohnwu** [comment]
Well, you all got your answer here

**Comment by towlie** [comment]
I am glad to hear that this helped you.
But I wouldn't say that the issue is solved because:
1. I fear there will be more issue reports like this
2. And there might be a chance that an OTA update forces you to wipe data again (Just an assumption but I hope that this will not be the case)

I think this issue needs to be recreated with a different title because it must be something related to the boot image and data encryption.
All I can tell is that my device is recognized as SaR and AVB2

**Comment by osm0sis** [comment]
Sounds kinda like the Samsung nonsense where you need a wipe first due to the decryption keys getting tripped up by Magisk: https://topjohnwu.github.io/Magisk/install.html#before-installing-magisk

My hunch is that will just have to be the installation procedure you guys use on these variants of these devices because there's no other way to get around it.
