### ISSUE TITLE
能否增加備份所有模塊，生成一個可刷入包的功能

### ISSUE THREAD

**Issue by Howard-00** [topjohnwu/Magisk#2009]
如題，參考應用Migrate

**Comment by RikkaW** [comment]
如 #1282 所述，一个模块安装后所得文件可能是设备相关的（如 Android 版本，ABI）。因此，不可能在不改变现有模块结构的情况下实现可靠的备份。

**Comment by topjohnwu** [comment]
感謝 @RikkaW 解答 ^_^
