### ISSUE TITLE
Pokemon Go doesn't work with Magisk and Xposed

### ISSUE THREAD

**Issue by szamuka** [topjohnwu/Magisk#201]
Pokemon Go doesn't work when Xposed is active. How to fix it?
Xiaomi Redmi Note 3
Android 6.0.1
MIUI 7.5.4 xiaomi.eu

**Comment by Didgeridoohan** [comment]
Disable or uninstall Xposed.

**Comment by szamuka** [comment]
I wanted to check xposed module for pokemon go and I would like to play with active xposed

**Comment by Didgeridoohan** [comment]
Magisk Hide can't hide Xposed. There have been some ways to trick some Pokemon Xposed modules to function even with Xposed disabled (no idea if it still works). Check the Pokemon Magisk thread in the Magisk forum over on XDA.

It's not a problem with Magisk... I'd suggest closing this issue.
