### ISSUE TITLE
image signed with testkeys cause bootloop

### ISSUE THREAD

**Issue by defi231** [topjohnwu/Magisk#2013]
have to resign the image to boot
op3t lineage os 16
https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/rom-nlos-16-0-t3879405/post78433989#post78433989

**Comment by topjohnwu** [comment]
Using Magisk with stocked bootloader is not officially supported. Users should be expected to sign with their own keys.

**Comment by osm0sis** [comment]
This is also incorrect. We use the verity key for awhile now, since https://github.com/topjohnwu/Magisk/commit/085ea6d0a1ba295fa26fd6d06d5b9eac69cf5c47 partly because the experiments from nvertigo67 made me realize Magisk wasn't already.

See here: https://forum.xda-developers.com/android/software-hacking/signing-boot-images-android-verified-t3600606/post79838315#post79838315

**Comment by nvertigo** [comment]
@osm0sis: after your commit (https://github.com/topjohnwu/Magisk/pull/1662/commits/67f383a5714c0175680ed6ff5c7fefb3717b5c97 ), I've assumed it's fixed. Sadly, according to https://forum.xda-developers.com/showpost.php?p=80737127&postcount=3436 this doesn't work.

Appart from the expirience of @defi231, after https://github.com/topjohnwu/Magisk/pull/1662/commits/67f383a5714c0175680ed6ff5c7fefb3717b5c97 the console message here https://github.com/topjohnwu/Magisk/blob/04920883ea431d71a6206a4321208aad3648ca0e/app/src/main/java/com/topjohnwu/magisk/tasks/MagiskInstaller.kt#L269 should be adjusted.

**Comment by nvertigo** [comment]
I've checked the keys @osm0sis has added. Thes are the very same I've added to @chainfire's bootsigner. Perhaps something gets messed up while signing? 
BTW: I don't use a locked bootloader myself, so I need to rely on @defi231's findings.

**Comment by osm0sis** [comment]
I think def's quote "if i do a clean install with magisk it is working but after i update the OS i have to sign it again with the AOSP Key or i get bootloops" is the main clue here.

Clean install with Magisk means Magisk's boot signing with verity key does in fact work. The real question is what's happening "after I update the OS"

**Comment by nvertigo** [comment]
Is there a way to check which key the boot partition is curtently signed with?

**Comment by defi231** [comment]
> @defi231, how are you updating the OS, step by step?

downloading *.zip file via OS update, exporte file to internal, boot into recovery and install

**Comment by osm0sis** [comment]
> Is there a way to check which key the boot partition is currently signed with?

Looks like the latest BootSignature.jar can do that: https://android.googlesource.com/platform/system/extras/+/master/verity/BootSignature.java#300

> downloading *.zip file via OS update, exporte file to internal, boot into recovery and install

And are you then flashing Magisk again? You might need to since the OTA would replace the boot.img with its own.

**Comment by nvertigo** [comment]
> > Is there a way to check which key the boot partition is currently signed with?
> 
> Looks like the latest BootSignature.jar can do that: https://android.googlesource.com/platform/system/extras/+/master/verity/BootSignature.java#300
> 
> So can Magisk's SignBoot: https://github.com/topjohnwu/Magisk/blob/master/signing/src/main/java/com/topjohnwu/signing/SignBoot.java#L135

Thanx. Will try to make a flashable zip, that checks for aosp verity key.
 
> > downloading *.zip file via OS update, exporte file to internal, boot into recovery and install
> 
> And are you then flashing Magisk again? You might need to since the OTA would replace the boot.img with its own.

Auto-install from addon.d.

**Comment by osm0sis** [comment]
> > And are you then flashing Magisk again? You might need to since the OTA would replace the boot.img with its own.
> 
> Auto-install from addon.d.

Right, is that happening though? Does @defi231 see the output from it in recovery or in recovery.log? I'd also like him to try to reflash Magisk directly after the OTA instead of your zip, since if the Magisk zip worked initially it should work again.

**Comment by nvertigo** [comment]
I've got a dd of the boot partition from

1. a blank los boot image without magisk
2. a boot image with magisk freshly flashed magisk-20.0
3. a boot image from dirty flashed rom (aka magisk flashed from addon.d

Then I've checked the images checked with:
`
ingo@adler /usr/local/src/los16 $ java -Xmx2048m -Djava.library.path=/mnt/export/data/src/los16/out/host/linux-x86/lib64 -jar /mnt/export/data/src/los16/out/host/linux-x86/framework/BootSignature.jar -verify /mnt/export/data/Downloads/incoming/boot-magisk.img -certificate build/make/target/product/security/verity.x509.pem
`
For 1 & 2 I get:
`
NOTE: verifying using public key from build/make/target/product/security/verity.x509.pem
Signature is VALID
`
For 3 I get:
`
Exception in thread "main" java.io.IOException: unexpected end-of-contents marker
        at org.bouncycastle.asn1.ASN1InputStream.readObject(ASN1InputStream.java:221)
        at com.android.verity.BootSignature.<init>(BootSignature.java:99)
        at com.android.verity.BootSignature.verifySignature(BootSignature.java:287)
        at com.android.verity.BootSignature.main(BootSignature.java:329)
`

I'm pretty sure that means: no signature at all. 

If I look at the recovery log, the fresh magisk flash ,entions signing, but the addon.d flash is NOT mentioning signing. @osm0sis is right (again ;) )

@defi231 can you edit the original issue report, to something saying it's only on addon.d magisk flashes, that the boot image isn't signed. Hopefully @topjohnwu will reopen the issue again.

**Comment by osm0sis** [comment]
@defi231 can reopen it as well. I'll take a look at the addon.d script to see what I can do.

**Comment by nvertigo** [comment]
BOOTSIGNED is initialozed to false here https://github.com/topjohnwu/Magisk/blob/master/scripts/util_functions.sh#L27 , there's no further check; so the if clause you mentioned is alway false. Maybe just the check is missing?

**Comment by osm0sis** [comment]
> BOOTSIGNED is initialized to false here https://github.com/topjohnwu/Magisk/blob/master/scripts/util_functions.sh#L27 , there's no further check; so the if clause you mentioned is alway false. Maybe just the check is missing?

Initialized to false, yes, but it shouldn't stay that way: https://github.com/topjohnwu/Magisk/blob/master/scripts/addon.d.sh#L63

@nvertigo, can you or @defi231 add this line:
`echo "$APK $BOOTSIGNER $BOOTIMAGE $BOOTSIGNED"` before line 63 and after remove_system_su, then flash Magisk, then dirty flash the ROM and provide the recovery.log ?

**Comment by osm0sis** [comment]
@nvertigo, also worth noting that your VerifiedBootSigner's included custom.der which is presumably derived from verity.x509.pem (since I notice custom.pk8 IS verity.pk8) also shows a correctly signed image as INVALID when checked against the correct verity.x509.pem. So you might want to include the actual verity.x509.pem in your zip, and not the .der just to be on the safe side.

**Comment by nvertigo** [comment]
I've added the echo line twice, in line 62 and 65. In between there's:
`
libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 5484 (main), pid 5484 (main)
`
[recovery.log](https://github.com/topjohnwu/Magisk/files/3799176/recovery.log)

**Comment by osm0sis** [comment]
There we go. So it attempts to verify but segfaults so $BOOTSIGNED remains false. So the next question is why.

**Comment by nvertigo** [comment]
> @nvertigo, also worth noting that your VerifiedBootSigner zip's included custom.x509.der which is presumably derived from verity.x509.pem (since I notice custom.pk8 IS verity.pk8) also shows a correctly signed image as INVALID at times when checked against the actual verity.x509.pem. So you might want to include the actual verity.x509.pem in your zip, and not the .der just to be on the safe side.

Ähh, no. Used VerifiedBootSigner-v8.01-aosp-key.zip and got:
`
ingo@adler /usr/local/src/los16 $ java -Xmx2048m -Djava.library.path=/mnt/export/data/src/los16/out/host/linux-x86/lib64 -jar /mnt/export/data/src/los16/out/host/linux-x86/framework/BootSignature.jar -verify /mnt/export/data/Downloads/incoming/boot-magisk-bsig.img -certificate build/make/target/product/security/verity.x509.pem
NOTE: verifying using public key from build/make/target/product/security/verity.x509.pem
Signature is VALID
ingo@adler /usr/local/src/los16 $

`

> Edit: The correctly signed image I'm referring to is the boot.img from your latest OP3T ROM zip.

I don't get this.

For the segfault: I've no clue at all - maybe twrp?

**Comment by osm0sis** [comment]
Ehh check my edits above. False alarm about your zip.

**Comment by nvertigo** [comment]
> Ehh check my edits above. False alarm about your zip.

Seen to late; disregarded. *lol*

**Comment by osm0sis** [comment]
Is Magisk Manager hidden on your setups? No APK = no verifier, so could be an issue with find_manager_apk.

**Comment by nvertigo** [comment]
> Is Magisk Manager hidden on your setups? No APK = no verifier, so could be an issue with find_manager_apk.

No. 

Have to leave now for an appointment. Continuing tomorrow.

**Comment by osm0sis** [comment]
Alright thanks, I'll see what I can figure out between now and then. :+1:

**Comment by osm0sis** [comment]
Found and working on fixing a few issues with the scripts, looks like BootSigner/SignBoot will also need some touch-ups though:
```
/system/bin/dalvikvm -Xnodex2oat -Xnoimage-dex2oat -cp $AIKBIN/BootSignature_Android.jar com.android.verity.BootSignature -verify  /sdcard/boot-nlos-16.0-20191024_084809-beta-oneplus3t.img
Signature is VALID

/system/bin/dalvikvm -Xnodex2oat -Xnoimage-dex2oat -cp $AIKBIN/BootSignature_Android.jar com.android.verity.BootSignature -verify  /sdcard/image-new.img
Signature is VALID

/system/bin/dalvikvm -Xnodex2oat -Xnoimage-dex2oat -cp $APK a.a -verify < /sdcard/boot-nlos-16.0-20191024_084809-beta-oneplus3t.img
Signature is VALID

/system/bin/dalvikvm -Xnodex2oat -Xnoimage-dex2oat -cp $APK a.a -verify < /sdcard/image-new.img
Invalid image: not signed
```

**Comment by osm0sis** [comment]
Hopefully my above PR will fix the issue you guys were seeing. If not, my changes should at least help narrow it down further. :+1:

**Comment by nvertigo** [comment]
My today's journey:
From yesterday the boot image was left unsigned. When ditectly updating (to stable channel 20101). No sig found, so no sig made.
[magisk_install_log_2019-11-02T13_16_51Z.log](https://github.com/topjohnwu/Magisk/files/3800468/magisk_install_log_2019-11-02T13_16_51Z.log)

Then I've booted to recovery, and (in one session):
1. flashed 20101
2. flashed verifiedbootsigner
3. flashed 20101 (correctly signed)
4. flashed the rom (incl. 20101 from addon.d)
[recovery.log](https://github.com/topjohnwu/Magisk/files/3800472/recovery.log)

Before rebooting to system, I've flashed the bootsigner again - not comtained in the log. In system I've installed 20101 from the Manager once again - it has signed the boot image cotrectly now.

[magisk_install_log_2019-11-02T13_44_37Z.log](https://github.com/topjohnwu/Magisk/files/3800476/magisk_install_log_2019-11-02T13_44_37Z.log)

**Comment by defi231** [comment]
> Edit: @defi231 please reopen this issue so it doesn't get lost. 

cannot reopen, or i dont see how to do

**Comment by osm0sis** [comment]
@defi231 hmm, maybe John changed the repo rules?

@nvertigo as I worried, still that error
```libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 5762 (main), pid 5762 (main)
Segmentation fault
```
Does flashing Magisk zip on its own from recovery still work over a signed image?

Off the top of my head, obvious problem with signing during addon.d is /system is being mounted, unmounted and formatted at different times, so maybe it's attempting to run dalvikvm at a bad time.

**Comment by nvertigo** [comment]
> @defi231 hmm, it's usually in the options at the top or bottom, maybe in a menu, or maybe John changed the repo rules?
> 
> @nvertigo as I worried, still that error
> 
> ```
> libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 5762 (main), pid 5762 (main)
> Segmentation fault
> ```
> 
> Does flashing Magisk zip on its own from recovery still work over a signed image?

As long as the curtently installed image is signed, flashing magisk in recovery and updating from Manager works perfectly.

> Off the top of my head, obvious problem with signing during addon.d is /system is being mounted, formatted, overwritten, and unmounted at different times, so maybe it's attempting to run dalvikvm at a bad time.
> 
> Good news is I verified I did fix the other signing issues I found. 👍

I'm still thinking of the unexpanded wildcards (btw: data is definetly mounted, when the addon.d script is run). The really ugly point: they are not expanded two times: the first time when APK is set, and the second time when $APK is used. From what I understand of sh's wildcard expansion, they should be expanded both times... Really ugly and really strange.

**Comment by osm0sis** [comment]
/data is mounted, yes, or the script couldn't run, I'm talking about /system because we need /system/bin/dalvikvm to run the signer; the inability to access dalvikvm is the likely culprit.

The wildcards are expanded when used because it's run with `eval`, so that part should be fine.

**Comment by nvertigo** [comment]
> The wildcards aren't expanded when set, but are expanded when used because it's run with `eval`, so that part should be fine. If you want to test that to see if it makes a difference, add `APK=$(echo $APK)`

We'be proofed yesterday, that echo $APK doesn't expands the wildcard. That's what confuses my.

**Comment by osm0sis** [comment]
> We'be proofed yesterday, that echo $APK doesn't expands the wildcard. That's what confuses my.

Hmm fair point, but try it anyway, since that's not my previous experience with echoing wildcard paths, and it's a little different the way I did it.

**Comment by nvertigo** [comment]
...yeah, and I hear some ls, mount and find calls for debugging calling... 😉 I'll check tommorow.

**Comment by osm0sis** [comment]
> ...yeah, and I hear some ls, mount and find calls for debugging calling... 😉 I'll check tommorow.

_After_ you try out the above, try adding the below after get_flags in addon.d.sh:
```
  # Keep system mounted since we need dalvikvm for signing AVBv1 images
  /system/bin/sleep 20 &
  /system_root/system/bin/sleep 20 &
```

**Comment by osm0sis** [comment]
Managed to trigger it by setting up my OP5 with an AVBv1 signed image. :+1:
```libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 1078 (main), pid 1078 (main)
Segmentation fault```

I'll see what I can work out. 😉

**Comment by osm0sis** [comment]
Oh my god. Crazy. So I figured it out. And it's really really stupid.

The issue is - get this - that running addon.d-v1 backup then restore leaves you in /tmp/addon.d after it's been deleted. 😑

I'll make a PR to workaround this bullshit and it should be in the next build. 🙄😉

**Comment by nvertigo** [comment]
> Oh my god. Crazy. So I figured it out. And it's really really stupid.
> 
> The issue is - get this - that running addon.d-v1 backup then restore leaves you in /tmp/addon.d after it's been deleted. 😑
> 
> I'll make a PR to workaround this bullshit and it should be in the next build. 🙄😉

Wow! That hasn't come to my mind. Great finding!

**Comment by nvertigo** [comment]
For completeness:

I've patched 20101 with https://github.com/topjohnwu/Magisk/pull/2020/commits/a52e130f53867c11fb7664752b66c7dbaed8fb0e 

`wget https://github.com/topjohnwu/Magisk/commit/a52e130f53867c11fb7664752b66c7dbaed8fb0e.patch -O -|sed -e 's#/scripts#/common#g' -e 's#common/flash_script.sh#META-INF/com/google/android/updater-script#g' |patch -p1 --no-backup-if-mismatch`

Repacked and flashed.

Updating the rom and reflashing magisk from addon.d correctly signs the boot image, now! Congrats!

[recovery.log](https://github.com/topjohnwu/Magisk/files/3801716/recovery.log)
