### ISSUE TITLE
Magisk app says "Magisk is not installed"

### ISSUE THREAD

**Issue by sai4041412** [topjohnwu/Magisk#2014]
_Hello_
the thing is when ever i flash latest(or any version) Magisk zip in TWRP all goes well but Magisk app says _Magisk is not installed_   flashed more than 5+ times still same result.
_Non-SAR build/TWRP_
logs here as well !! recovery and dmesg logs 
[recovery.log](https://github.com/topjohnwu/Magisk/files/3799123/recovery.log)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/3799124/dmesg.log)

in-case needed device trees

 device tree : https://github.com/ArrowOS-Devices/android_device_motorola_sanders
kernel tree : https://github.com/ArrowOS-Devices/android_kernel_motorola_sanders
branch arrow-10.0

**Comment by shakalaca** [comment]
Is it possible to grab /data/cache/magisk.log ?

**Comment by sai4041412** [comment]
> Is it possible to grab /data/cache/magisk.log ?

no i don't have any file like _magisk.log_ in storage

**Comment by Dybios** [comment]
> 
> 
> Is it possible to grab /data/cache/magisk.log ?

Just for a little more clarification for the issue, flashing the magisk zip does patch the bootimage. Extracting the ramdisk shows that a .backup folder is created with the magiskinit as well as the system init. A magisk folder is also created in the /data/adb path and a .magisk file is also present in the /data path.
However, there are no magisk.log, su, or any magisk related stuff in either /sbin or /data that is installed in the device itself.

Although, side note (not sure if it is relevant or not), the fstab in our /vendor/etc doesnt seem to be affected at all after flashing the zip but I'm not sure if it would be visible after boot so I might be a little off here. Thanks.

**Comment by topjohnwu** [comment]
May you use the boot image patching method and see if it works?

**Comment by Dybios** [comment]
> May you use the boot image patching method and see if it works?

I just tried it and it seems there's a little progress there. Patching the boot image manually and flashing it causes panic and reboot to bootloader. The first stage init seems to be trying to find system/lib64/libselinux.so while that file is in /sbin instead. The log is as attached below.

[    7.669484,4] init: init first stage started!
[    7.670957,4] init: Using Android DT directory /proc/device-tree/firmware/android/
[    7.671795,4] init: [libfs_mgr]ReadDefaultFstab(): failed to find device default fstab
[    7.684271,4] init: [libfs_mgr]superblock s_max_mnt_count:65535,/dev/block/platform/soc/7824900.sdhci/by-name/system
[    7.684392,4] init: [libfs_mgr]__mount(source=/dev/block/platform/soc/7824900.sdhci/by-name/system,target=/system,type=ext4)=0: Success
[    7.684601,4] init: Switching root to '/system'
[    7.684677,4] init: Unable to move mount at '/system/lib64/libselinux.so': No such file or directory

Would symlinking help? Thanks.

**Comment by Dybios** [comment]
Also (probably unrelated but worth a mention), our prop _getprop ro.build.system_root_image_ is set as false and if set to true gives an obvious bootloop because we are not using the legacy system-as-root implementation. Sanders is an A-only device following 2SI SAR Impl.

**Comment by mirsella** [comment]
it don't really resolve the issue but a workaround I found : with a custom kernel it work, I'm using sphynx kernel but it should work with any other

**Comment by osm0sis** [comment]
Do you have Magisk Manager hidden but then opened the unhidden version installed by the TWRP flash instead? It can show as "not installed".

**Comment by mirsella** [comment]
> Do you have Magisk Manager hidden but then opened the unhidden version installed by the TWRP flash instead? It can show as "not installed".

hello, my issue was resolved with a clean flash of my rom, by wiping /data. the rom (xiaomi eu) was on beta so it surely break something when updating to Android Q.

**Comment by Dybios** [comment]
Hi, this issue has now been solved. The problem was in our custom motorola dtbtool that wasn't properly oriented towards creating the proper boot image of Android 10 for the Magisk zip to be able to patch the fstab. Switching to the source dtbtool and reverting a few old commits helped to do the trick.
Thanks all.

**Comment by sai4041412** [comment]
Hi, this issue has now been solved. The problem was in our custom motorola dtbtool that wasn't properly oriented towards creating the proper boot image of Android 10 for the Magisk zip to be able to patch the fstab. Switching to the source dtbtool and reverting a few old commits helped to do the trick.
Thanks all.
