### ISSUE TITLE
Cannot install after uninstall

### ISSUE THREAD

**Issue by LM1LC3N7** [topjohnwu/Magisk#2017]
Hello,

I don't know why, but since I have flashed the uninstall zip, I cannot flash magisk anymore.
If I do so, my OP6T is stuck at bootloader. After flashing again the uninstaller, it can boot again.

I tried also to flash again the last system full OTA, but magisk did not work..
I have TWRP installed but not rooted anymore 😕

Any ideas about that?

Thanks a lot!

* Magisk version: v20.0
* Uninstaller version: Magisk-uninstaller-20191011
* OS version: OxygenOS 9.0.17
* Device: OnePlus 6T

**Comment by topjohnwu** [comment]
Reflash your ROM and start clean. Or maybe you have incompatible modules installed.
