### ISSUE TITLE
Magisk Manager Filters Modules with names started with lowercase letters in to the bottom in the Modules list [ After X]]

### ISSUE THREAD

**Issue by mikesew1320** [topjohnwu/Magisk#2024]
Latest Magisk Manager even the canary and debug versions Filters Modules that their name started with Smallcase letters in to the bottom in the Modules list

I think its contributers should take proper modification on the sorting logic within the app source!

As I noticed thus issue started to appear after you fixed the module sorting issue last time

If this issue is known issue please try to fix it quickly as a hotfix. Too much boring 😴 thing

![Screenshot_20191103-155153](https://user-images.githubusercontent.com/43565227/68085414-e805a180-fe51-11e9-97c7-43208f2a1620.jpg)

**Comment by osm0sis** [comment]
Sounds like the best thing to do would be to have it still sort alphabetically, but regardless of case.

@diareuse

**Comment by diareuse** [comment]
I wondered what I forgot 😅 The modules are not rewritten in the redesign, so this completely slipped my mind.

This is not top priority for me, and I'd prefer this being fixed by the redesign. I don't see rereleasing stable because of non fatal issue.

**Comment by topjohnwu** [comment]
@diareuse there is already some bugs I have found out, will have to release a fix soon anyways LOL. I'll do a fix for this

**Comment by diareuse** [comment]
Awesome

**Comment by mikesew1320** [comment]
> @diareuse there is already some bugs I have found out, will have to release a fix soon anyways LOL. I'll do a fix for this

Thanks my master! I am happy to hear you this!
