### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by YouROK** [topjohnwu/Magisk#2027]
I cannot select modules from the repository using the remote control. Also this problem is in the exposed

**Comment by YouROK** [comment]
Add to item layout:
 android:focusable="true"
 android:clickable="true"

**Comment by topjohnwu** [comment]
@diareuse I have no plans to work on this, but you might want to check if this is feasible in your redesign

**Comment by topjohnwu** [comment]
Use this issue to track Android TV support

**Comment by topjohnwu** [comment]
#2175
