### ISSUE TITLE
Installing magisk from twrp result in softbrick fastboot

### ISSUE THREAD

**Issue by patrickhgb** [topjohnwu/Magisk#2028]
Hi,

I have OnePlus 7 Pro, wiped device and update to OxygenOS android 10.

I have magisk manager APK installed, saying magisk is not installed.

Then I downloaded magisk version 21 .zip from the app, it's placed under "downloads."

I boot into TWRP recovery, then select the magisk.zip to be installed. However this results in the phone only being able to boot into fastboot and not the actual OS. I have also tried to install magisk using adb sideload and it faces the same issue.

The softbrick can be resolved by flashing TWRP (.zip) again.

Flashing magisk.zip and twrp.zip result in successful boot into OS but magisk is still shown as not installed.

Any ideas on what might be happening here?

Thanks in advance.

**Comment by nopyhe** [comment]
Same with Xiaomi MI 8, MIUI 10, Android 10 
I tried the boot image patching method but reboot to fastboot.
I tried both magisk version 20 and 20.1.

**Comment by topjohnwu** [comment]
Use boot image patching method to root your device.
