### ISSUE TITLE
Envirinment Setup Failed

### ISSUE THREAD

**Issue by Moonwalker8689** [topjohnwu/Magisk#2029]
Samsung Galaxy Tab-E 9.6, SM-T560NU Android version 6.0.1, running Stock ROM rooted with magisk updated to latest Magisk with flashable zip afterwards Magisk is denied superuser rights when setting up environment and therefore is no longer working. Flashed with TWRP. Magisk zip file used was, Magisk-v20.1(20100). Thanks hope it gets fixed.

**Comment by topjohnwu** [comment]
You did not provide any relevant info to fix your issue.
Your best bet would be full uninstall and reinstall Magisk
