### ISSUE TITLE
Magisk install fail using TWRP or boot.img patch (safeboot loop)

### ISSUE THREAD

**Issue by patrickhgb** [topjohnwu/Magisk#2030]
Hi,

I have OnePlus 7 Pro, wiped device and update to OxygenOS android 10.

I have magisk manager APK installed, saying magisk is not installed.

Then I downloaded magisk version 20.1 .zip from the app, it's placed under "downloads."

I boot into TWRP recovery (TWRP have been installed using .img fastboot then .zip for persistent installation), then select the magisk.zip to be installed. However this results in the phone only being able to boot into fastboot and not the actual OS. 

I have also tried to install magisk using adb sideload and it faces the same issue.

The softbrick can be resolved by flashing TWRP (.zip) again.

Flashing magisk.zip and twrp.zip result in successful boot into OS but magisk is still shown as not installed.

_**I also tried a prepatched stock boot img (https://forum.xda-developers.com/oneplus-7-pro/how-to/magisk-patched-boot-image-oneplus-7-pro-t3964345) and patching my own stock boot img extracted from OnePlus official update website as suggested in the aforementioned XDA thread and previously closed issue, but I wasn't able to get past fastboot loop.**_

Update package: https://support.oneplus.com/app/answers/detail/a_id/4312
OnePlus7Pro Oxygen OS  10.0.1.GM21AA

If I restore by reinstalling TWRP, phone boots fine.

This is using the B partition. If manually selecting the A partition, for some reason cannot be booted into and will result in fastboot loop regardless of what's being done there.

Any ideas on what might be happening here?

Thanks in advance.

**Comment by topjohnwu** [comment]
Apparently, someone on XDA already have their OnePlus 7 Pro rooted, GitHub issues is not a place to ask for support...
Messing TWRP and Magisk on A/B devices is never a good idea, please refer to corresponding threads for help
