### ISSUE TITLE
su randomly dissapears

### ISSUE THREAD

**Issue by w1d3m0d3** [topjohnwu/Magisk#2031]
Hello,
I'm running Magisk and Manager versions 20.2-7da97489 and 7.4.1-7da97489 (Canary Debug channel, although this I can reproduce on the release channel) on LineageOS 16.0 dipper 20191103 nightly, and occasionally, some time after boot, the su binary disappears from `/sbin`:
```
1|dipper:/ $ ls /sbin
chargeonlymode charger magisk magiskhide magiskinit magiskpolicy resetprop supolicy ueventd watchdogd
dipper:/ $ # ran in an ADB shell, but reproducible through termux
```
Invoking `/sbin/magisk su` still causes the superuser request prompt to appear and, upon granting permission, the root shell to work. There's nothing interesting in the Magisk log, attached below, and so far the only thing I noticed that was off about Magisk is that single executable going missing.

Logs and `ls /sbin` [here](https://github.com/topjohnwu/Magisk/files/3803176/magisk_log_and_shell.txt)

I've done more elaborate testing beforehand but, sadly, I had to reflash Lineage, and with it Magisk, so I discarded the results as out of date.

Another possibly useful detail is that I had formatted data at one point before this started happening, but clean reinstalling Magisk (and now reflashing + reinstalling Magisk, without wiping data) didn't help.

I've noticed that Magisk Manager works until it's unloaded by removing it from recent apps, presumably because it already has a shell open with libsu or something. I can even enable/disable/install/update modules!

EDIT: When it comes to Magisk Hide configuration, almost nothing is hidden, just the default parts of Google Play Services.

**Comment by topjohnwu** [comment]
That is 100% just some random fluke, as it seems the daemon started up just fine, and other applets also exists

**Comment by w1d3m0d3** [comment]
I'd not be so sure, since I've been getting this for quite a while now consistently. Yes, the daemon runs fine, but after ~20min the `su` binary alone dissapears
