### ISSUE TITLE
Redmi Note 7 xiaomi.eu MIUI11 Weekly ROM - deny all su request

### ISSUE THREAD

**Issue by oldman63** [topjohnwu/Magisk#2033]
Redmi Note 7 (codename lavender)
xiaomi.eu MIUI11 Weekly ROM 9.10.31_v11-9 version
OrangeFox 10.0_2 Stable recovery

Magisk 20.1
After installed Safetynet Fix module, SafetyNet Check is success.

The problem: the root request is totally denied. no any Prompt, in the Magisk Log is included all deny events.

Magisk 20.0 is working perfectly!

![Screenshot_2019-11-04-18-58-35-892_com topjohnwu magisk](https://user-images.githubusercontent.com/3171626/68156155-8e819d80-ff4b-11e9-920d-1dc1cb3b3ca9.jpg)
![Screenshot_2019-11-04-18-59-10-197_com topjohnwu magisk](https://user-images.githubusercontent.com/3171626/68156159-8e819d80-ff4b-11e9-9507-ad08ee2dc4f3.jpg)
![Screenshot_2019-11-04-18-59-21-162_com topjohnwu magisk](https://user-images.githubusercontent.com/3171626/68156160-8e819d80-ff4b-11e9-877a-5f52cee8e42e.png)
![Screenshot_2019-11-04-20-05-22-895_org adaway](https://user-images.githubusercontent.com/3171626/68156161-8f1a3400-ff4b-11e9-9d50-be0eb5fcc8ea.jpg)

**Comment by topjohnwu** [comment]
It is already fixed 25c557248cab19f9761bbeb5a8ba110318d79d85

**Comment by oldman63** [comment]
Thank you!

**Comment by cizaquita** [comment]
How to install the fix? What's the update version?

Thanks
