### ISSUE TITLE
Bad Module Prevents Boot

### ISSUE THREAD

**Issue by gudenau** [topjohnwu/Magisk#2034]
I installed Edexposed and Riru on my Pixel 4 XL.

This has caused the device to fail to boot, I have tried the following to fix it:

- `su -c rm -vfr /data/adb/module/[edexposed]`
- `su -c rm -vfr` everything that shows up from `find 2>/dev/null | grep -i magisk`
- `su -c touch /data/.disable_magisk`
- `su -c touch /data/.disable_magisk`
- `su -c magisk --remove-modules`
- `adb sideload MultiFunctions4Magisk-v1.0.3.4.1.5A0(Unity4.2)(3MF).zip`
- Creating a custom boot.img with a patched Magisk init
- Spamming power button on boot

These have all failed.

Dmesg is spamming things like this:
```
[   15.184852] init: Could not find 'android.frameworks.cameraservice.service@2.0::ICameraService/default' for ctl.interface_start
[   15.211922] init: Received control message 'interface_start' for 'android.frameworks.sensorservice@1.0::ISensorManager/default' from pid: 546 (/system/bin/hwservicemanager)
[   15.211947] init: Could not find 'android.frameworks.sensorservice@1.0::ISensorManager/default' for ctl.interface_start
```

**Comment by topjohnwu** [comment]
Before a proper solution is created, please use this command when your device is booting up:
`adb wait-for-device shell magisk --remove-modules`
The device will reboot, and all modules will be removed

**Comment by gudenau** [comment]
No change.

After the second try one it said that there was not a valid slot to boot however.

**Comment by gudenau** [comment]
![Screenshot_20191107-081529](https://user-images.githubusercontent.com/5642329/68396378-17106180-0137-11ea-8cc9-ae31d608c077.png)

Don't appreciate being called an idiot for your problem......

**Comment by gudenau** [comment]
@topjohnwu Please fix your project. I want to have root again.

**Comment by ArdenSinclair** [comment]
There is nothing wrong with Magisk itself here

**Comment by gudenau** [comment]
Yeah there is, the thing to remove modules doesn't function.
