### ISSUE TITLE
No superuser toasts on v20102, v255. 

### ISSUE THREAD

**Issue by martyfender** [topjohnwu/Magisk#2035]
On both my new Onn 8, Android 9.tablet and also my Nextbook Ares 8A, Android 6.0.1 tablets, when I launch root apps that had previously been granted root, there are no longer any toasts, whatsoever. I double checked settings, also.
Attached is a logcat filtered in LogcatX for Manager, in addition the magisk.log. Hiding the Manger makes no difference.
[Log_2019-11-04_19-17-52.txt](https://github.com/topjohnwu/Magisk/files/3806661/Log_2019-11-04_19-17-52.txt)
[magisk_log_20191104_191833.log](https://github.com/topjohnwu/Magisk/files/3806664/magisk_log_20191104_191833.log)

Thanks, John.

**Comment by topjohnwu** [comment]
Fixed here 46447f7cfd966da458e83f33b6205a89196fe598
