### ISSUE TITLE
Manger app cannot find stock image backup after I installed by patched boot.img

### ISSUE THREAD

**Issue by li-yifei** [topjohnwu/Magisk#2037]
Magisk ver: 20.1
Magisk manager ver: 7.4.0(253)(3)
Env: Pixel 4 XL w/ November Update
I had read the [tutorial](https://github.com/topjohnwu/Magisk/blob/master/docs/tutorials.md#ota-installation)
Actually I had flashed magisk patched img before I tried workflow below again, but nothing happened.
Magisk manager exists and has been renamed.
**My workflow:**
1. patch the boot.img extracted from the factory image.
2. flash it by fastboot.
3. tried to restore the stock image by magisk manager, but it said that the stock image was not found.

[Video clip](https://streamable.com/cv1va)

**Comment by topjohnwu** [comment]
You have to patch your boot image with the device you want to root in order to preserve the stock boot image. Also, if you wiped data afterwards, the backup will also be removed

**Comment by li-yifei** [comment]
Sorry but I did patch the image on the same phone I flashed ** AFTER ** unlocking the bootloader.
