### ISSUE TITLE
Installation Magisk

### ISSUE THREAD

**Issue by szamuka** [topjohnwu/Magisk#204]
My phone hasnt root yet then
I installed earlier Super SU in systemless mode reboot and next magisk v12 Hide fixed.zip

And now I think the Hide isn't working good

If I havent rooted yet then I must install only Magisk v12? Or SuperSU must be earlier

http://i.imgur.com/AxRLgRO.png

Xiaomi

**Comment by Didgeridoohan** [comment]
Magisk can't hide SuperSU. If you need SafetyNet to pass, remove SuperSU completely and flash Magisk in recovery. That way you'll get MagiskSU installed and SafetyNet should pass, hopefully.

**Comment by szamuka** [comment]
http://i.imgur.com/dYdfe4I.jpg

my telephone wasn't rooted yet then I installed SuperSu i systemless mode

**Comment by Didgeridoohan** [comment]
Yes, those are the installation instructions. But if you wan't to use Magisk Hide to pass SafetyNet, skip the part about flashing systemless SuperSU.
