### ISSUE TITLE
Magisk v20.1 Random Rebooting Problem

### ISSUE THREAD

**Issue by redymedan** [topjohnwu/Magisk#2041]
I have used Magisk v20.0 / v20.1, on these versions I faced random rebooting problem, how to fix it? Thanks

**Comment by unresolvedsymbol** [comment]
Android 9 or 10?

**Comment by unresolvedsymbol** [comment]
Yeah it seems v20.1 doesn't work on Android 9. It was probably only tested on 10. I downgraded to v20 on my phone with Android 9 and everything's working alright again.

**Comment by redymedan** [comment]
> 
> 
> Yeah it seems v20.1 doesn't work on Android 9. It was probably only tested on 10. I downgraded to v20 on my phone with Android 9 and everything's working alright again.

It also happened on Magisk v20.0, I install it by patching AP file and flash it via ODIN.  I can not downgrade it I have no choice because I am not use TWRP. do you know other way to downgrade it to Magisk v19.3?  Magisk v19.3 worked stable.

**Comment by Didgeridoohan** [comment]
> Yeah it seems v20.1 doesn't work on Android 9. It was probably only tested on 10. I downgraded to v20 on my phone with Android 9 and everything's working alright again.

Nope. Plenty of testing on Pie as well.

**Comment by unresolvedsymbol** [comment]
> > Yeah it seems v20.1 doesn't work on Android 9. It was probably only tested on 10. I downgraded to v20 on my phone with Android 9 and everything's working alright again.
> 
> Nope. Plenty of testing on Pie as well.

**Comment by topjohnwu** [comment]
No logs no fix

**Comment by VarunSaiTeja** [comment]
I am using Samsung M30s
Mobile rebooting automatically after few seconds
