### ISSUE TITLE
Slight correction on Magisk Tools Doc

### ISSUE THREAD

**Issue by gabefair** [topjohnwu/Magisk#2043]
On the [Magisk Tools Doc page](https://github.com/topjohnwu/Magisk/blob/master/docs/tools.md) it says:
> run `./magiskinit(64) -x magisk <path>` to extract magisk out of the binary.

Running `./magiskinit(64) -x magisk .` doesn't work as the app requires you to not only specify a path but also the name of the binary. 

So `./magiskinit(64) -x magisk <path>/magisk` is more correct

**Comment by topjohnwu** [comment]
The path is the desired path to store magisk binary, not the path to the folder where you want to store magisk. Path does not mean directory
