### ISSUE TITLE
Wifi mac address lost after rooting on xiaomi mi 6 used miui 11 android 9 Pie

### ISSUE THREAD

**Issue by apri294** [topjohnwu/Magisk#2044]
hi, i lost my wifi mac address after rooting this device, use magisk 20.1 xiaomi mi 6 miui 11 android 9 pie, thanks

**Comment by martyfender** [comment]
I would suggest providing logs so topjohnwu doesn't close this issue right away.

**Comment by topjohnwu** [comment]
No logs no fix
