### ISSUE TITLE
Prompt to grant superuser access is not appearing in magisk 20.1 in miui 11

### ISSUE THREAD

**Issue by arjuntsgowda** [topjohnwu/Magisk#2045]
Hello
In miui 11,magisk prompt to grant root is not appearing ,because of this apps are not granted
[magisk_log_20191106_080831.log](https://github.com/topjohnwu/Magisk/files/3812254/magisk_log_20191106_080831.log)
 root access.
This problem wasn't there in magisk 20
If we just set magisk option to grant instead of prompt even then apps are not granted root access
If there is a need for any other logs,kindly ask
Thank you

**Comment by TomHorvath1607** [comment]
Hi, I have same problem

**Comment by dknchris** [comment]
I've received some reports about the same with Swift Backup users. The root request popup doesn't show up.

**Information sent by one of the usesr**
Device: Redmi Note 7
ROM: MIUI Global Stable v11.0.3.0 (PFGMIXM)
Android version: 9.0 (Pie)
Magisk version: v20.1

**Logs**
[magisk_log_20191112_005607.log](https://github.com/topjohnwu/Magisk/files/3834920/magisk_log_20191112_005607.log)
[device.txt](https://github.com/topjohnwu/Magisk/files/3834921/device.txt)

**Comment by topjohnwu** [comment]
Fixed in d952cc2327839855002951d5ee7c6586698fe119

**Comment by mentengjaya** [comment]
> Hello
> In miui 11,magisk prompt to grant root is not appearing ,because of this apps are not granted
> [magisk_log_20191106_080831.log](https://github.com/topjohnwu/Magisk/files/3812254/magisk_log_20191106_080831.log)
> root access.
> This problem wasn't there in magisk 20
> If we just set magisk option to grant instead of prompt even then apps are not granted root access
> If there is a need for any other logs,kindly ask
> Thank you

Hello, excuse me, is the problem solved or not? Because I got same issues here.
Thank you.

**Comment by ranjithran** [comment]
Not working in this version 
![Screenshot_2019-12-12-17-58-08-277_com topjohnwu magisk](https://user-images.githubusercontent.com/36547960/70712094-055b4480-1d09-11ea-9a07-483bc5229af4.jpg)

**Comment by velox11** [comment]
any updates ? I really need adaway...

**Comment by SirCoolMind** [comment]
me too. MIUI 11, device Redmi 5 Rosy. log is similar to one above.

**Comment by DavidNingthoujam** [comment]
For everyone heaving this issue just goto app info for magisk than turn on auto start and goto other permissions than turn on display pop up message while running in background.. i hope this helps

**Comment by SirCoolMind** [comment]
> For everyone heaving this issue just goto app info for magisk than turn on auto start and goto other permissions than turn on display pop up message while running in background.. i hope this helps

Thank you so much. My phone now working fine asking for root. Never thought that would be a problem huhuh

**Comment by POBrien333** [comment]
> 
> 
> For everyone heaving this issue just goto app info for magisk than turn on auto start and goto other permissions than turn on display pop up message while running in background.. i hope this helps

Can you, @DavidNingthoujam, specify what you mean here? Are you talking about a setting in Magisk or in the Android Settings under "Apps"?

**Comment by Didgeridoohan** [comment]
@POBrien333 It's an Android setting found on some OEM versions of Android. MIUI is the one mentioned here, so I believe it pertains to that particular flavour of Android.
