### ISSUE TITLE
Unable to repack boot image on Realme 5

### ISSUE THREAD

**Issue by ayatkyo** [topjohnwu/Magisk#2046]
Using Magisk Manager 7.4.1 from [here](https://github.com/topjohnwu/magisk_files/tree/canary) and boot.img from [here](https://download.c.realme.com/osupdate/RMX1911EX_11_OTA_0150_all_jzKjYWTb3tvE.ozip) then decrypt it using [this](https://github.com/bkerler/oppo_ozip_decrypt), got "Unable to repack boot image".

Here is the log and boot.img :
[magisk_install_log_2019-11-06T114828Z.log](https://github.com/topjohnwu/Magisk/files/3812412/magisk_install_log_2019-11-06T114828Z.log)
[boot.zip](https://github.com/topjohnwu/Magisk/files/3812424/boot.zip)

Thanks

**Comment by osm0sis** [comment]
There's something very weird with that boot.img: the header magic is there but then it looks like something completely different.

**Comment by ayatkyo** [comment]
Could it be because decryption tool ? i will try other device boot.img to make sure it decrypt correctly

**Comment by osm0sis** [comment]
Most likely. The custom ROM boot.img from https://forum.xda-developers.com/realme-5/development/9-x-realme-5-t3993021 is normal format and works without issue.

Please close the issue since there's nothing wrong with Magisk here. :+1:

**Comment by ayatkyo** [comment]
Thanks for answer
