### ISSUE TITLE
magisk19.4+ 使用部分需要ROOT权限的软件会导致系统无法开机

### ISSUE THREAD

**Issue by z826540272** [topjohnwu/Magisk#2047]
使用这个 https://play.google.com/store/apps/details?id=com.jumobile.manager.systemapp
系统程序卸载器 卸载任意系统软件一定会触发无法开机的故障,但是文件内容却是正确的
还有别的root权限软件没做兼容性适配的也可能导致系统无法开机.
经过检查,文件系统区域 部分信息产生了奇怪的更改.
 tune2fs -l /dev/block/by-name/system_a
Last mounted on:          /
变更为
Last mounted on:          /system_root
操作前:

~ # tune2fs -l /dev/block/by-name/system_a
tune2fs 1.43.3 (04-Sep-2016)
Filesystem volume name:   /
Last mounted on:          /
Filesystem UUID:          c13fd2a9-5571-5c92-98f4-d26bf9cb66c6
Filesystem magic number:  0xEF53
Filesystem revision #:    1 (dynamic)
Filesystem features:      ext_attr resize_inode dir_index filetype extent flex_bg sparse_super large_file huge_file uninit_bg dir_nlink extra_isize
Filesystem flags:         signed_directory_hash
Default mount options:    user_xattr acl
Filesystem state:         not clean
Errors behavior:          Continue
Filesystem OS type:       Linux
Inode count:              193536
Block count:              774003
Reserved block count:     0
Free blocks:              101921
Free inodes:              187662
First block:              0
Block size:               4096
Fragment size:            4096
Reserved GDT blocks:      188
Blocks per group:         32768
Fragments per group:      32768
Inodes per group:         8064
Inode blocks per group:   504
Flex block group size:    16
Filesystem created:       Mon Jan  1 00:00:00 2018
Last mount time:          Wed Nov  6 15:06:25 2019
Last write time:          Wed Nov  6 14:51:11 2019
Mount count:              7
Maximum mount count:      -1
Last checked:             Mon Jan  1 00:00:00 2018
Check interval:           0 (<none>)
Lifetime writes:          125 kB
Reserved blocks uid:      0 (user root)
Reserved blocks gid:      0 (group root)
First inode:              11
Inode size:               256
Required extra isize:     32
Desired extra isize:      32
Default directory hash:   half_md4
Directory Hash Seed:      e90c259e-f9ca-5b19-ac4a-539592f2d9b8

**Comment by topjohnwu** [comment]
System mount point 由 `/system` 改為 `/`，這件事情 v19.4 就開始了，大概講了一億遍，也有一億個人不斷的開 issue。請你要求你下載的 app 的開發者修好他的 app，不要怪在 Magisk 頭上
