### ISSUE TITLE
Magisk Manager on TV or Android STB without mouse

### ISSUE THREAD

**Issue by tsynik** [topjohnwu/Magisk#2048]
In general it works. Only issue on devices controlled by CEC or with Remote (D-PAD) it's not possible to switch to few main Manager elements: it's apps blocks on Magisk Hide list and elements of Modules (mainly + button required) / Repo.
Is it possible to add focus on them or some kind of context menus on [long] SELECT click, so Manager will be fully useful without mouse on such devices?

**Comment by tsynik** [comment]
For (+) on Modules, probably enough to add this action as last item in Reboot options text menu.

**Comment by meiser79** [comment]
duplicate of #2027
