### ISSUE TITLE
Magisk busybox grep not finding boot image

### ISSUE THREAD

**Issue by Decatf** [topjohnwu/Magisk#205]
The busybox grep bundled with Magisk (un)installer has problems finding the boot image location. 

My device (Galaxy Tab 10.1 / GT-P7500) has an irregular boot partition path. Right now the only reason Magisk installer is working on this device is because the `find_boot_image` call during install is using the TWRP busybox.

In `flash_script.sh` the `find_boot_image` function is called before constructing environment. So when `grep`-ing `recovery.fstab` it is using the recovery busybox instead of the Magisk busybox. The uninstall script does use the Magisk busybox grep since `find_boot_image` is called after environment construction.

recovery busybox grep:
```
~ # /sbin/grep -E '\b/boot\b' "/etc/recovery.fstab"
/boot                   emmc            /dev/block/mmcblk0p3
~ # 
```
Magisk bundled busybox grep:
```
~ # /dev/tmp/busybox/grep -E '\b/boot\b' "/etc/recovery.fstab"
~ # 
```
It works if the regex is changed:
```
~ # /dev/tmp/busybox/grep -E '/boot\b' "/etc/recovery.fstab"
/boot                   emmc            /dev/block/mmcblk0p3
~ # 
```

This run on an unofficial TWRP 3.0.0. [Here is the recovery.fstab for this device.](https://github.com/Decatf/android_device_samsung_p4-common/blob/android-7.1-twrp/twrp.fstab)

**Comment by topjohnwu** [comment]
The scripts has changed a lot, obsolete issue
