### ISSUE TITLE
magisk manager is autostarting on boot "in fullscreen"

### ISSUE THREAD

**Issue by lemmy04** [topjohnwu/Magisk#2051]
Every time I boot my device the first i have to do after unlocking it is to back out of magsk manager now, y pressing "back" *twice*.

Device: Samsung S8+
OS: Latest Android Pie image for S8+ downloaded with frija, flashed with odin
Magisk 20.1
Magisk Manager 7.4.0

XDA forum thread: https://forum.xda-developers.com/apps/magisk/magisk-manager-autostarting-boot-t3998455

https://forum.xda-developers.com/showpost.php?p=80806441&postcount=36879 seems to be related as well.

**Comment by osm0sis** [comment]
Maybe part of the broadcast tests? I think there are fixes in for the upcoming Canary that should fix it.

**Comment by topjohnwu** [comment]
Fixed in d952cc2327839855002951d5ee7c6586698fe119
