### ISSUE TITLE
Latest Canary Build Magisk / Manager Galaxy S4

### ISSUE THREAD

**Issue by helmchenlord** [topjohnwu/Magisk#2054]
Galaxy S4
lineage-14.1-20191031-UNOFFICIAL-jfltexx.zip
https://los-legacy.de/jfltexx/lineage-14.1-20191031-UNOFFICIAL-jfltexx.zip
Latest Canary Build Magisk / Manager
S-pushTAN
https://play.google.com/store/apps/details?id=com.starfinanz.mobile.android.pushtan&hl=de

Because the latest release didn't work for me didn't work for me. S-pushTAN crashed.
I tried latest canary build.
Set the hook in Manager to hide the app and gave the name "Manager" to MagisterManager.
Rebooted the phone and tried to start S-pushTAN but it crashed again.
Opened the Manager app again, but it flashed on and off the screen and I was not able to use the app.
Uninstalled both and re-installed with the same result.
Magisk Manager is still inusable for me. (flashing)

**Comment by Didgeridoohan** [comment]
First of all: https://github.com/topjohnwu/Magisk/issues/1152

Second: Magisk can hide from that app just fine (I just tested). Either your system is too outdated to fully be able to hide the Manager (Android 9+ is required for complete obfuscation), or there's something else being detected that Magisk can't hide (like another app, your ROM, etc).

Please close this issue (so John doesn't have to), take a look here: https://didgeridoohan.com/magisk/MagiskHide#hn_Hiding_root_from_apps
If you still can't get things working, seek assistance over at XDA.
