### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by xdMatthewbx** [topjohnwu/Magisk#2055]
When trying to install just about any module It shows:

- Copying zip to temp directory
- Installing MODULENAME.zip
! installation failed

Tried with Netflix Enabled, SSH for Magisk, and others. Phone is Galaxy A520W.
Yes, I'm running the latest version.

**Comment by xdMatthewbx** [comment]
For what reason was this closed? There has been no fix given.

**Comment by topjohnwu** [comment]
For what reason should I accept issues without any details or logs? Please read before opening issues on Github

**Comment by xdMatthewbx** [comment]
[magisk_install_log_2019-11-08T08:57:50Z.log](https://github.com/topjohnwu/Magisk/files/3824844/magisk_install_log_2019-11-08T08.57.50Z.log)
My apologies, I thought the logs I had ready provided we're satisfactory. Please tell me if you need any other logs and reopen this issue.
