### ISSUE TITLE
RootBeerFresh failing UDS check even when Magisk-Hidden

### ISSUE THREAD

**Issue by Djtrip83** [topjohnwu/Magisk#2056]
I use RootBeerFresh hidden via Magisk to check from time to time that all is ok. Since one my banking apps threw an error (likely due to rooting), I went to check and found that Magical UDS and Stat failed the test in RootBeerFresh. Has this been reported? Is it normal?

Magical versione 20.1 stable
Magisk manager repackaged 7.4.0 (253)

**Comment by topjohnwu** [comment]
#1152

**Comment by Djtrip83** [comment]
Thanks for the link to your best practices!
