### ISSUE TITLE
Bootloop issues - V20

### ISSUE THREAD

**Issue by expphoto** [topjohnwu/Magisk#206]
So this is an odd one. I initially instaled Magisk with SuperSU via the manager and it worked flawlessly minus the ability to hide and get SafetyNet to pass. I removed SuperSU (via switch the SU app), uninstalled Magisk and reinstalled Magisk (via TWRP). The phone then became unstable and rebooted every 2-5 mins. 

Boot Image https://drive.google.com/file/d/0B5Uw7OXrBAaZWkVZbUY5ak1VMjA/view?usp=sharing

**Comment by Argeovus** [comment]
Same issue, except mine does this every 30 seconds. Stock room on US996 factory unlocked

**Comment by KiRanF500** [comment]
Hey I'm using Motorola onepower phone and while I flashed the magisk zip file my phone went bootloop. And then after some time I flashed another zip file kali-nethunter . The thing is nethunter didn't installed and I got my bootlooping solved I got my Moto ROM back.

But I really wish to root my phone. And I can't take another chance. So please confirm that magisk support Moto onepower.
