### ISSUE TITLE
Simpler would be to zero the target partition before flashing the new image.

### ISSUE THREAD

**Issue by saicheung128** [topjohnwu/Magisk#2065]
Simpler would be to zero the target partition before flashing the new image.

Edit: Which Magisk already goes: https://github.com/topjohnwu/Magisk/blob/master/scripts/util_functions.sh#L267

_Originally posted by @osm0sis in https://github.com/topjohnwu/Magisk/issues/2005#issuecomment-547578854_

**Comment by osm0sis** [comment]
Garbage issue. Stop.
