### ISSUE TITLE
Magisk Manager is constantly looking for updates

### ISSUE THREAD

**Issue by pheraspu** [topjohnwu/Magisk#2067]
For two days Magisk is constantly looking for updates and I can't download any module; The download page says: "No modules found."
It only allows me to do manual module downloads.
I have the latest Canary channel release installed, but the problem also occurs with the beta channel.
Thank you

**Comment by pheraspu** [comment]
![Screenshot_20191111-165048-01](https://user-images.githubusercontent.com/57631490/68601054-dfd9e180-04a3-11ea-8baa-92c27c12217e.jpeg)
![Screenshot_20191111-165218-01](https://user-images.githubusercontent.com/57631490/68601064-e5cfc280-04a3-11ea-9243-741e7be99dcf.jpeg)

**Comment by osm0sis** [comment]
Force close advd reopen?

**Comment by pheraspu** [comment]
Yes, but the problem is the same. Thank you anyway

**Comment by osm0sis** [comment]
Uninstall and reinstall the latest app-debug (canary) APK from https://github.com/topjohnwu/magisk_files/tree/canary?files=1 ?

**Comment by pheraspu** [comment]
Hi. I can't download the apk. There is a server error
![Screenshot_20191112-072201_Chrome-01](https://user-images.githubusercontent.com/57631490/68647181-86ae9400-051d-11ea-8e73-1d5a3fc71e05.jpeg)

**Comment by Didgeridoohan** [comment]
Seems like the Spanish authorities are involved:
https://forum.xda-developers.com/showpost.php?p=80864777&postcount=36981
https://forum.xda-developers.com/apps/magisk/stuck-searching-updates-t4001437/post80868593#post80868593

Use a VPN.

**Comment by pheraspu** [comment]
Yes, it is true... With VPN works right...
Thank you

**Comment by Didgeridoohan** [comment]
Changing DNS should also work (OpenDNS, for example).

You can close the issue now...
