### ISSUE TITLE
Batch installing modules without using manager

### ISSUE THREAD

**Issue by nemanjan00** [topjohnwu/Magisk#2070]
Hello, 
Is there any way to batch install modules without any user interaction? 

I need to mass provision devices with some magisk modules and am looking for ideas

**Comment by xerta555** [comment]
Hi,
You can "reproduice" the official module setup procedure, i let u read the guide on the git for that.
I can also say that it's not recommended, because yould purely breaking a Magisk setup

**Comment by topjohnwu** [comment]
#2036

**Comment by topjohnwu** [comment]
This does seem to be easy to do, and currently have no plans to support this
