### ISSUE TITLE
magiskboot 20+ is mangling the DTB when it patches it.

### ISSUE THREAD

**Issue by ianmacd** [topjohnwu/Magisk#2073]
Versions of `magiskboot` since early October have a fatal flaw affecting some devices:

```
[ianmacd@lagom ~]$ ls -l device/samsung/winnerx/prebuilt/recovery_dtbo
-rw-rw-r--. 1 ianmacd ianmacd 8388608 Nov  4 13:29 device/samsung/winnerx/prebuilt/recovery_dtbo
[ianmacd@lagom ~]$ ./magiskboot dtb device/samsung/winnerx/prebuilt/recovery_dtbo patch recovery_dtbo.new 2>/dev/null 
[ianmacd@lagom ~]$ ls -l recovery_dtbo.new                            
-rw-r--r--. 1 ianmacd ianmacd 2895216 Nov 13 11:44 recovery_dtbo.new
```

As you can see, two thirds of the file is being eaten.

One immediate effect of this is that Samsung Qualcomm devices will not boot after their stock recovery image is patched by Magisk. This probably applies to devices from other manufacturers, too.

One workaround is to unpack the bad image and replace the mangled `recovery_dtbo` with a copy previously patched by Magisk 19.4. When the image is repacked and subsequently flashed, it will boot as expected. That's what I'm doing until the bug in `magiskboot` is fixed.

Cheers,

Ian

**Comment by cawilliamson** [comment]
I opened a bug about this a while ago but had nowhere near this level of detail.

Basically this is the exact issue I've been facing.

I found a similar workaround:

- Patch with 19.3
- Upgrade in-situ to 20.1

It would be greatly appreciated if this could be resolved though because it's a real pain in the arse for everyone on Sammy QC devices.

**Comment by osm0sis** [comment]
Image for @topjohnwu to reproduce the issue with:
https://gitlab.com/osm0sis/boot-img-collection/blob/master/aosp-hdr1-avb2-recoverydtbo-seandroid-512sig-samsung_gfold-smf907b-recovery.img :+1:

**Comment by ianmacd** [comment]
After further investigation, I found the bad commit to be 4d91e50d6dec76a4bdcec737f11d7547b0da34cb: `Update dtb patch to not use in-place modification`.

This adds the ability to the `magiskboot dtb patch` command to write to a new output file, rather than edit the existing file in-place.

If the file is edited in-place, there is in fact still no error. The file is correctly rewritten. It's only when the new option to write the output to a new file is used that the resulting file is invalid.

**Comment by osm0sis** [comment]
The installer patches it in place, so it must be an issue in place as well?

**Comment by ianmacd** [comment]
Yeah, you're right.

I had hard reset to the commit where the problem was introduced, and at that point in time, what I wrote above was correct. Fast-forwarding to the head of the branch, however, it's no longer true. Now, even the in-place patching doesn't work. Ugh.

The only thing I can say for sure, then, is that the commit I cited is the one where the problem was first introduced.

**Comment by ianmacd** [comment]
Just in case referencing this issue from a pull request doesn't notify followers, I'll mention it here, too.

In an effort to encourage and expedite a fix for this issue, I have submitted the following pull request:

https://github.com/topjohnwu/Magisk/pull/2096

It works for Qualcomm-based Samsung devices, but may cause chaos on other makes and models. I bow to John's superior knowledge in this regard to know whether to commit or discard this simple fix.

**Comment by osm0sis** [comment]
Through test images it seems like the issue may indeed be directly with the recovery_dtbo magiskboot is creating.

**Comment by osm0sis** [comment]
Fixed by https://github.com/topjohnwu/Magisk/commit/8d2198865697b3fe55474e523c473297df5bbd72

:tada:

**Comment by ianmacd** [comment]
Yes, indeed. Many thanks.
