### ISSUE TITLE
why Magisk did not enable adbd root permission

### ISSUE THREAD

**Issue by fr0zenrain** [topjohnwu/Magisk#2074]
I want to sanitize app check in my phone. so i have patched boot.img and flash it by manual not use Magisk, and it's not ok. does Magisk can patch  boot.img enable adb root permission. it is possible? why Magisk did not enable adbd root permission. thanks.

**Comment by topjohnwu** [comment]
https://twitter.com/topjohnwu/status/1192853698390585346

**Comment by Didgeridoohan** [comment]
@fr0zenrain Just as a FYI, there's an easy solution:
https://didgeridoohan.com/magisk/Magisk#hn_ADB_cannot_run_as_root_in_production_builds

**Comment by fr0zenrain** [comment]
> @fr0zenrain Just as a FYI, there's an easy solution:
> https://didgeridoohan.com/magisk/Magisk#hn_ADB_cannot_run_as_root_in_production_builds

Thanks for you solution.
