### ISSUE TITLE
Patched boot.img non-functional on Moto E6 (surfna)

### ISSUE THREAD

**Issue by suppai** [topjohnwu/Magisk#2077]
Hello. With the latest Magisk Canary and stable, Magisk Manager can successfully patch boot.img and recovery.img for the Moto E6 (codename surfna), but when booting it via the boot.img method, Magisk Manager will report that Magisk is not installed; the "Recovery Mode" method works. This is a A-only device with an unlockable bootloader and stock-ish Android, as well as separate boot.img and recovery.imgs; recovery is not part of the standard boot.img like you'd see on i.e. Pixel devices. Here is the build info from the ROM on the device we tested:

```
BUILD REQUEST INFO:
SW Version: surfna-user 9 PPB29.73-81 fd167 release-keysM8940_32.127.01.130R
MBM Version: MBM-2.1-surfna_retail-461a42d-190818
Modem Version: M8940_32.127.01.130R
FSG Version: FSG-8953-26.76
Build Fingerprint: motorola/surfna/surfna:9/PPB29.73-81/fd167:user/release-keys
CQATest App Version: 6.0.4

VERSION INFO FOUND UNDER 'ABOUT PHONE' SCREEN:
System Version: 29.31.86.surfna.retail.en.US
Model Number: moto e6
Android Version: 9
Baseband Version: M8940_32.127.01.130R
Build Id: PPB29.73-81
SW Display Build ID: PPB29.73-81
Build Date: Sun Aug 18 02:00:00 CDT 2019

OTHER MISC VERSION INFO:
Subsidy Lock Config: slcf_rev_d_default_v1.0.nvm
Regulatory Info (eLabel): regulatory_info_xt2005_5_sku6.png
Blur Version: Blur_Version.29.31.86.surfna.retail.en.US
Version when read from CPV: surfna-user 9 PPB29.73-81 fd167 release-keys

AB Update Enabled: False
Full Treble Enabled: True
```

Please let me know if any other information is needed and I will provide it.

**Comment by suppai** [comment]
**Files:**

* [boot.img.zip](https://github.com/topjohnwu/Magisk/files/3848729/boot.img.zip)
* [recovery.img.zip](https://github.com/topjohnwu/Magisk/files/3848730/recovery.img.zip)
* [dtbo.img.zip](https://github.com/topjohnwu/Magisk/files/3848731/dtbo.img.zip)

**Comment by topjohnwu** [comment]
You already answered your own question: A only system-as-root devices are stuck with recovery mode, there is no way around it
