### ISSUE TITLE
Magisk 257 & 20105: su log refresh button not working

### ISSUE THREAD

**Issue by Jon8RFC** [topjohnwu/Magisk#2079]
This likely existed well before this version and was why I often had "missing logs", but didn't think to really test it until the log storage system changed, as notated in the changelog.

The refresh button only works if it's the first new entry in the list.  Successive entries can only be shown if a different window is opened, such as settings, and then the log window is opened again.  This is reproducible and I've rebooted.

Pixel 4 Google Edition
Build QD1A.190821.007.A3

Video of usage:
https://youtu.be/Ur0vfaUCr7A

**Comment by Jon8RFC** [comment]
I'm unsure if the magisk application logs have the same issue, because I'm not sure how to test it and know if/when new entries should appear.

**Comment by diareuse** [comment]
Yeah, will do :) The redesign generally doesn't reuse existing logic and I coincidentally didn't start redesigning the logs screen yet haha, but no worries

**Comment by topjohnwu** [comment]
I think the issue lies in how diff is calculated, you should be more familiar with the code :)
