### ISSUE TITLE
URGENT: disabling magisk made OP6 stuck on bootloader, How to recover from it?

### ISSUE THREAD

**Issue by JerryGoyal** [topjohnwu/Magisk#2081]
I had latest magisk (stable version) installed and tried to disable it from magisk manager->uninstall->restore images.
when i restarted the phone it stuck on bootloader screen.
I tried to got to twrp recovery mode and it's stuck on the flash screen.
Why would magisk manager put a button which is not working at all and bricks the phone? Please guide me what to do.

**Comment by topjohnwu** [comment]
Restore stock boot image
