### ISSUE TITLE
[KMSG Logs] Magisk higher than 19.3 doesnt work.

### ISSUE THREAD

**Issue by myst33d** [topjohnwu/Magisk#2082]
Magisk higher than 19.3 doesnt work on Redmi 6A custom ROMs.
`[   91.431204]  (2)[1:init]init: File /vendor/bin/aee_aedv(labeled "u:object_r:unlabeled:s0") has incorrect label or no domain transition from u:r:init:s0 to another SELinux domain defined. Have you configured your service correctly? https://source.android.com/security/selinux/device-policy#label_new_services_and_address_denials
[   91.431236]  (2)[1:init]init: starting service 'aee_aedv'...
[   91.432786]  (1)[541:init]init: cannot execve('/vendor/bin/aee_aedv'): Permission denied
[   91.432943]  (0)[341:logd.auditd]type=1400 audit(1574244199.070:164): avc: denied { execute } for pid=540 comm="init" name="aee_aedv" dev="mmcblk0p35" ino=618 scontext=u:r:init:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=0
[   91.432980]  (0)[341:logd.auditd]type=1400 audit(1574244204.080:165): avc: denied { execute } for pid=541 comm="init" name="aee_aedv" dev="mmcblk0p35" ino=618 scontext=u:r:init:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=0
[   91.433781]  (2)[1:init]init: Service 'aee_aedv' (pid 541) exited with status 127
[   91.433813]  (2)[1:init]init: Sending signal 9 to service 'aee_aedv' (pid 541) process group...
[   91.433917]  (2)[1:init]libprocessgroup: Successfully killed process cgroup uid 0 pid 541 in 0ms`
[kmsg.log](https://github.com/topjohnwu/Magisk/files/3868894/kmsg.log)

**Comment by journeym** [comment]
Why is the issue closed? I have the same problem

**Comment by myst33d** [comment]
> Why is the issue closed? I have the same problem

Well, its not a problem with Magisk, blame Mediatek for making our life harder.
