### ISSUE TITLE
A small suggestion about magisk manager

### ISSUE THREAD

**Issue by w2016561536** [topjohnwu/Magisk#2087]
In magisk manager 7.4.0. If I want to disable magisk modules by terminals. I need to create a file in /cache. So could you make a function that if this file doesn't exist , the magisk will disable moudles and    only use magisk su.In this way ,I can use recovery to wipe cache and i do not need pc to disable it when some moudles cause some bugs(many phones does have third party rec till now)

**Comment by topjohnwu** [comment]
This will be addressed by introducing safe mode boot image patches
