### ISSUE TITLE
wifi mac address lost in magisk 20.1

### ISSUE THREAD

**Issue by apri294** [topjohnwu/Magisk#2089]
hay, my wifi mac address lost on magisk 20.1, my phone xiaomi mi6, miui 11.0.3 
[magisk_log_20191117_090642.log](https://github.com/topjohnwu/Magisk/files/3855155/magisk_log_20191117_090642.log)

**Comment by osm0sis** [comment]
What version of Magisk last worked? Have you tried with the latest Canary?

**Comment by apri294** [comment]
i think version 19.4, and before i update miui to 11.0.3

> What version of Magisk last worked? Have you tried with the latest Canary?
