### ISSUE TITLE
A/B OTA update - install to inactive slot - not switching partitions

### ISSUE THREAD

**Issue by mysiak** [topjohnwu/Magisk#2091]
I'm experiencing issue with Mi A3, stock ROM (happened second month in a row). I am using the usual A/B OTA update procedure with Magisk v20.1 - restore images, apply OTA, install Magisk to inactive slot, reboot. To this point everything goes smoothly, but phone reboots to the same, old (and unrooted) system. When I switch active boot partitions in fastboot manually, phone boots into updated and rooted system correctly.

I either captured Magisk logs too late or they simply do not show anything relevant, so unfortunately I probably can't provide more detailed information. 

I understand that it's hard to guess what could have gone wrong, but as a workaround - is there a way how could I trigger active slot change via terminal emulator directly from a running Android manually? Currently I must be at a PC with working fastboot to be able to install OTA and keep root. Not a huge problem, but I miss my "quick & easy OTA installation" days :)

Thanks!

Edit: this issue sounds a little bit similar: https://github.com/topjohnwu/Magisk/issues/1976

**Comment by shakalaca** [comment]
1. Download bootctl here: https://github.com/topjohnwu/magisk_files/raw/master/bootctl
2. move bootctl to /data/adb/ and chmod 755 bootctl
3. /data/adb/bootctl get-current-slot
3a. if 0, then: bootctl set-active-boot-slot 1
3b. if 1, then: bootctl set-active-boot-slot 0
4. see if there's any error message on console or dmesg
5. reboot bootloader and check the active slot

**Comment by mysiak** [comment]
Thank you @shakalaca, I'm gonna try it with next OTA update.

**Comment by topjohnwu** [comment]
No reply from user, issue closed

**Comment by mysiak** [comment]
I was waiting for next OTA..which I got only today. :)

Issue is still present with Canary Magisk and Mi A3.

Quick fix:
1. restore images
2. install OTA update
3. install Magisk to both current and inactive slots
4. reboot (reboots to old system, but with root)
5. install Magisk to inactive slot
5. reboot (system takes longer to boot due to apps optimization which is otherwise done during OTA installation, but boots into new system with root)
