### ISSUE TITLE
[Magisk Manager] - Show Magisk log in Magisk Manager crashes MM/superuser

### ISSUE THREAD

**Issue by mysiak** [topjohnwu/Magisk#2092]
Magisk Manager (v7.4.0 - 253) crashes when trying to view Magisk (v20.1 -201000) logs from within the MM app. App stays active, but superuser doesn't work anymore - all apps get denied root access automatically and list with approved apps is empty. Reboot fixes it until next attempt to view logs in MM. Reproducible every time - if there is a need for extra logs, just let me know.

Stock Android 9 on Xiaomi Mi A3 phone.

[logcat_MM_crash.txt](https://github.com/topjohnwu/Magisk/files/3862832/logcat_MM_crash.txt)
[magisk_crash.log](https://github.com/topjohnwu/Magisk/files/3862833/magisk_crash.log)

Edit: actually it crashes with superuser logs as well

Thanks!

**Comment by diareuse** [comment]
![image](https://user-images.githubusercontent.com/5982859/69225731-31a6f980-0b7f-11ea-8b2f-56c2c79c8f3c.png)

Note:
Latest canary is 257.

**Comment by mysiak** [comment]
Oups, my bad. Going to check with canary build.

**Comment by mysiak** [comment]
Working fine in Canary 257, sorry :)
