### ISSUE TITLE
Lock screen problem and Samsung account issue

### ISSUE THREAD

**Issue by mrsamkhar** [topjohnwu/Magisk#2094]
I can't sign in samsung account and add any lock screen methods if I add pattern/pin/password  after reentering it says wrong pattern/pin/password, also i cant add any fingerprints 
device: sm-j600f
android: 9  one ui 1.0
magisk 20.1

**Comment by pheraspu** [comment]
It is not a Magisk's problem. This issue happens because the Samsung security policy with root on Pie Devices, at least with A600 and A605. I know that there is a solution in XDA, I will look for the link.

**Comment by mrsamkhar** [comment]
please give me the link if you find. thanks in advance.

**Comment by diareuse** [comment]
Sort this out in DMs

**Comment by pheraspu** [comment]
> I can't sign in samsung account and add any lock screen methods if I add pattern/pin/password after reentering it says wrong pattern/pin/password, also i cant add any fingerprints
> device: sm-j600f
> android: 9 one ui 1.0
> magisk 20.1

I am using this zip (flash with TWRP) in A6+ and it works perfectly; I can use Samsung account and lock screen:
https://forum.xda-developers.com/galaxy-a6/how-to/galaxy-a6-lockscreen-samsung-account-t4010211

**Comment by pheraspu** [comment]
> please give me the link if you find. thanks in advance.

I am using this zip (flash with TWRP) in A6+ and it works perfectly; I can use Samsung account and lock screen:
https://forum.xda-developers.com/galaxy-a6/how-to/galaxy-a6-lockscreen-samsung-account-t4010211
