### ISSUE TITLE
Can Magisk root VOS?

### ISSUE THREAD

**Issue by The-SamminAter** [topjohnwu/Magisk#2095]
There are currently no tools that can root VOS (Vsmart OS), so I was wondering if Magisk would be able to root VOS 8.1. Is the only current limitation Magisk not recognizing VOS to be  rootable with Magisk?

Unfortunately, I can't find a VOS Joy 1 ROM, which is preventing me from doing something like [installing Aquaris C and then rooting using Magisk](https://translate.googleusercontent.com/translate_c?depth=1&rurl=translate.google.com&sl=auto&sp=nmt4&tl=en&u=https://tinhte.vn/threads/v-smart-joy-1-unlock-bootloader-chuyen-doi-vos-joy1-sang-rom-bq-aquaris-c-root.2982775/&xid=17259,1500000,15700002,15700019,15700186,15700190,15700256,15700259,15700262,15700265,15700271,15700283&usg=ALkJrhg9MmyZd1NCZuwB9Dq6UjE1LsjP-A), because I'd like to be able to flash the original OS in case something goes wrong.

**Comment by MichaelRolltideroll** [comment]
I don't think I won't my phone to be rooted . That would voided my warranty
. And I have rooted several phones and had nothing but problems with it.
No thank you have a great day 😊😊😊😊

Michael S Rodgers

**Comment by The-SamminAter** [comment]
> I don't think I won't my phone to be rooted . That would voided my warranty . And I have rooted several phones and had nothing but problems with it. No thank you have a great day 😊😊😊😊 Michael S Rodgers

I understand that you have several reasons for not rooting a phone running VOS, such as bad experiences with rooted phones and the warranty on the device becoming void, but (1) this is for if anyone, for example myself or the people who wrote the article mentioned in my first post, want to root their Vsmart devices, as there are no current ways to root VOS (ignoring KingoRoot, and I don't know if that could do it either), and (2) owning a Vsmart phone while not inside of Vietnam (which I do) makes it most likely impossible to use the warranty or get VOS installed in case something goes wrong while flashing a different Android OS onto your phone to gain the ability to root it, not to mention the fact that [Vsmart's ROM download page](https://support.vsmart.net/vn-en/download) is completely blank, and the only ROM for VOS that's available online (as far as I could find, though I did possibly find one for a Vsmart Joy 1 behind a shady paywall) is for a Vsmart Joy 1+, meaning that if something goes wrong you're completely screwed unless you have a Vsmart Joy 1+ or live in Vietnam.

**Comment by topjohnwu** [comment]
As long as the device is using standard Android boot images, you can root the device with Magisk using the boot image patching method.
There is currently no plans to support non standard devices.
