### ISSUE TITLE
Magisk lagging issue (init using 95% cpu)

### ISSUE THREAD

**Issue by fawazahmed0** [topjohnwu/Magisk#2099]
Init using high amount of cpu resource:
![Top init](https://user-images.githubusercontent.com/20347013/69272604-e03d4f80-0bfc-11ea-89ea-1f3a36f6d665.jpg)
**Logs:**
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/3871098/dmesg.txt)
[logcatlog.txt](https://github.com/topjohnwu/Magisk/files/3871099/logcatlog.txt)
[magisklog.txt](https://github.com/topjohnwu/Magisk/files/3871101/magisklog.txt)
[stracelog.txt](https://github.com/topjohnwu/Magisk/files/3871103/stracelog.txt) (strace of init process)
[bugreport-RMX1825-PPR1.180610.011-2019-11-21-00-47-23.zip](https://github.com/topjohnwu/Magisk/files/3871097/bugreport-RMX1825-PPR1.180610.011-2019-11-21-00-47-23.zip) (Not really required)

Just in case, you need partition dump of my [phone](https://forum.xda-developers.com/realme-3/how-to/files-partition-dump-realme-3-t3931069 "phone")

This issue was always there from beginning i.e 19.3 or 19.4 (when magisk started supporting SAR ), but I thought the problem was with my slow stock rom.
I just got to know about this from [here](https://zukfans.eu/community/threads/important-if-you-are-using-magisk-performance-issue.7969/ "here"). and also many phone users were complaining of lag due to magisk.

The lagging problem starts 1-2 hours after reboot i.e when init uses more cpu trying to fork.

**Comment by fawazahmed0** [comment]
@topjohnwu So I started saving all the kernel logs after reboot, to see what was happening before the lagging issue.

I got this message in log before lagging starts to begin:
`[18232.200138] (7)[101:kswapd0]lowmemorykiller: kill orphan foreground task init, pid 318, adj 0, min_score_adj 900
[18232.200168] (7)[101:kswapd0]lowmemorykiller: kill orphan foreground task init, pid 319, adj 0, min_score_adj 900`

I assume lmkd is killing the init process, and thats what causing this issue
https://source.android.com/devices/tech/perf/lmkd


Here is the log, just search for first occurrence of the below string in the log (this is the time when lagging issue starts):
`Forked subcontext for`
Then start examining logs above the string to get the real cause of this issue
[smalldmesg.log](https://github.com/topjohnwu/Magisk/files/3902922/smalldmesg.log)

**Comment by fawazahmed0** [comment]
So I killed pid 318 and 319 (i.e init) manually and that is what triggering the lagging issue.
So lmkd is causing this issue, because that is the thing killing these processes.

**Comment by fawazahmed0** [comment]
So I set the oom_adj and oom_score_adj values of init pids to -17 and -1000 respectively, i.e making them unkillable, let's see if that works
.
Note: init of pid 1 already have above values to make it unkillable

Refer:
https://unix.stackexchange.com/questions/153585/how-does-the-oom-killer-decide-which-process-to-kill-first
https://lwn.net/Articles/317814/

**Comment by fawazahmed0** [comment]
@topjohnwu No lagging till now

**Comment by fawazahmed0** [comment]
Just a temporary fix , for anyone having this lagging issue:

`su
for i in $(pgrep -x init); do echo -1000 > /proc/$i/oom_score_adj && echo -17 > /proc/$i/oom_adj; done`

**Comment by topjohnwu** [comment]
I do not see anything related to Magisk here, closed

**Comment by fawazahmed0** [comment]
@topjohnwu , this lagging problem happens only when magisk is installed

**Comment by fawazahmed0** [comment]
Just for others, who are facing lagging issue in magisk, I have made a service script (init) script for this issue( May work , may not work, my fix is working in Realme 1 and Realme 3):
https://forum.xda-developers.com/android/general/magisk-lagging-issue-fix-t4012863
