### ISSUE TITLE
adb shell does not work when magisk hide is disabled

### ISSUE THREAD

**Issue by fawazahmed0** [topjohnwu/Magisk#2100]
**Steps to Reproduce this bug:**
1. Go to Magisk Manager settings and disable magisk hide.
2. Reboot the phone.
3. Connect the phone to pc and try 'adb shell' command. The command doesn't work
4. Now enable magisk hide and try 'adb shell' command. Now the command works.

**Logs:**
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/3873674/dmesg.txt)
[logcatlog.txt](https://github.com/topjohnwu/Magisk/files/3873675/logcatlog.txt)
[magisklog.txt](https://github.com/topjohnwu/Magisk/files/3873676/magisklog.txt)

**Comment by fawazahmed0** [comment]
Actually, the props were causing the issue in my stock rom.

For example: ro.debuggable is set to 1 and ro.secure is to set 0 by default (well actually, I changed those values manually by editing the prop file before to support adb root command) and the ro.build.type is set to user by default. (changing this manually is not possible)
So, ro.build.type should have been set to 'userdebug' and not 'user' and I guess that was breaking the adbd in magisk, 

Anyways the adbd works  without any issue with the above prop configuration(ie ro.debuggable=1, ro.secure=0,ro.build.type=user), when magisk is not installed.
The adbd only breaks when magisk is installed with above prop configuration and magisk hide being disabled.

Please feel free to close this issue, if you feel the above prop configuration (ie ro.debuggable=1, ro.secure=0,ro.build.type=user) is very rare and doesn't need to be supported in magisk.

**Comment by Didgeridoohan** [comment]
MagiskHide changes those props, since apps that detect a rooted device are known to look for them as a sign of tampering. That won't change, but you can of course change the props back yourself with a boot script or [module](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#setreset-magiskhide-sensitive-props) and still keep MagiskHide active.

It's not an issue, but a feature. You can close this.

**Comment by fawazahmed0** [comment]
@Didgeridoohan @topjohnwu Yes I am aware of that, just the question was, why adbd doesn't work when ro.secure=0 (default value taken from prop file) and magiskhide is disabled.
But adbd works perfectly well with ro.secure =0 value and no magisk being installed.

**Comment by Didgeridoohan** [comment]
Rebooted after disabling Hide? The altered props will stay with their current value until a reboot.

**Comment by fawazahmed0** [comment]
@Didgeridoohan yes I rebooted after disabling hide.
Now one of my default prop values is ro.secure=0 (the unaltered value written in .prop file) and this value causes adbd to break when magisk is installed.
ro.secure=0 works without any problem when magisk is not installed.

Anyways, I guess ro.secure cannot be 0 when ro.build.type is user , and that is what causing the adbd to break I assume.
