### ISSUE TITLE
KEEPVERITY & KEEPFORCEENCRYPT ... what is their use ?

### ISSUE THREAD

**Issue by aiamuzz** [topjohnwu/Magisk#2103]
At first i thought it was a much needed way to enable disable dm-verity and force-encryption on stock ROM's ... but it doesn't seem to do anything besides show up in Magisk-Manager ... what is the purpose of putting up that setting in the Magisk-Manager ?

echo KEEPVERITY=true
echo KEEPFORCEENCRYPT=true

It would've been really great if it was actually a switch to enable disable these annoying features for some !!!

**Comment by aiamuzz** [comment]
I would like to turn forced encryption off(disable encryption) ... is there any flashable file that will ease the whole process ?

I have almost tried all the tutorials and videos on how to do that ... but failed each time ...

primarily those tutorials speak of using fastboot commands

`fastboot erase userdata`
and
`fastboot format userdata`

I tried both approaches and failed ... i run either of the above commands the `/data` partition cannot be mounted in TWRP ... i try to restore a a previous `/data` partition backup ... i get the error that the backup was created on F2FS partition ... and only when i reformat the erased/formated userdata to this file-system it lets me restore the `/data` backup ... but on boot the encryption continues to be in force !!!

an easy magisk flashable file that disables dm-verity and force-encryption options and help restore the backed up `/data` partition will make life so much easier !!!

**Comment by topjohnwu** [comment]
You can toggle these features via Magisk Manager in advanced settings

**Comment by Didgeridoohan** [comment]
And to clarify, the mentioned settings only have any kind of effect when patching a boot image. So in other words, when installing. Just toggling the settings does nothing by themselves.

**Comment by aiamuzz** [comment]
> You can toggle these features via Magisk Manager in advanced settings

hmmmm ... I know i can toggle(check & uncheck) these options in Magisk Manager ... but its just that i didn't really find them consequential to anything ...

Eg. I my new OnePlus 3T device which runs Stock Pie and force encryption is enabled by default ... when i first flashed Magisk and opened the Magisk Manager I could see these 2/3 options ... for my device the option 'KEEPFORCEENCRYPT' was enabled(checked) the other 2 options were unchecked ... i assumed that as my device currently was encrypted it may have been checked giving the current status of my device ... i then unchecked and tried booting with the hope **that Magisk would have some magic up its sleeve** that will disable the default forced encryption which was proving quite the task for me to disable in spite of attempting a few tutorials on the forums ... 

But on reboot after unchecking the 'KEEPFORCEENCRYPT' option in Magisk Manager ... i discovered that the devices encryption was still as it was ... encrypted !

Then i unchecked again and closed the MManager and reopened it then i found that it wasn't unchecked ... it was checked back up.

Then i came across a forum which spoke of dropping a .magisk file in /cache or /data ... with the above 2 options set to either true or false ... i thought i'd experiment and i created this file and flagged both to 'false' ... i rebooted and hoped the encryption would be disabled this time bcos i noticed after dropping this file with a 'false' flag the closing and reopening of MManager would now let the uncheck status be registered ... but after reboot the default checked state was un checked(probably bcos MManager read it from the .magisk file ... but the encryption was untouched.

@topjohnwu ... wouldn't toggling mean to enable disable this feature ... but its not working as expected(or at least a lay user would assume it would/should given that these options were coded into the Magisk Manager !!!)

> And to clarify, the mentioned settings only have any kind of effect when patching a boot image. So in other words, when installing. Just toggling the settings does nothing by themselves.

Hmmmmm ... exactly, just like i have described above ... just toggling the setting did absolutely nothing !!!

@topjohnwu ... after some more researching and reading more material on disabling the forced encryption i came across an thread which finally let me achieve it ... it had only 2 aspects to it ...

1. flash a patched boot image
2. flash a zip file with what seems an fstab file

I am no coder but of what i have understood of Magisk ... flashing the Magisk zip file also entails flashing a patched boot image ... cant Magisk incorporate this patch(seems a minor flag change) which allows disabling of the default forced encryption into its own patched boot image ?

and the 'Force_Encryption_Disabler_For_OOS_Pie_v1.zip' fstab file could be served in some other way ... may be as Magisk module ?

would make lay users like myself ... and our lives way easier ... I have almost toiled endlessly with having to re-flash the stock rom 5-6 times in the hope to disable this forced encryption !!!

**Comment by Didgeridoohan** [comment]
You've misunderstood the setting and my message. Enable or disable the setting in the Manager, then install Magisk (or patch the boot image you're going to use). That will patch the image and remove the forced encryption flag from your device.

You can simply disable the setting and then reinstall Magisk over your current installation and that will remove forced encryption. After that you can format data and encryption will be removed.

**Comment by aiamuzz** [comment]
> You've misunderstood the setting and my message. Enable or disable the setting in the Manager, then install Magisk (or patch the boot image you're going to use). That will patch the image and remove the forced encryption flag from your device.
> 
> You can simply disable the setting and then reinstall Magisk over your current installation and that will remove forced encryption. After that you can format data and encryption will be removed.

oh ... ok ... you mean these 2 options on the magisk manager itself are those flags that i have requested in the last post ... disabling these 2 (unchecking) will add these flags to the magisk's patched boot image ? If that is what its intention has been to code into the MManager ... ignore my request in the last post @topjohnwu ...

I have a few clarifications ...

1. Flashing the Magisk zip in TWRP will enable root on the device.
2. I had flashed Magisk zip long ago ... disabling forced encryption was proving to be challenge.
3. So if my above understanding is right ... I just uncheck those 2 options to disable DM-verity and ForcedEncryption ... then how do i go about re flashing Magisk(remember Magisk is already flashed onto my device) ... do i have to install the same Magisk zip file i flashed previously ... if so how will that file grab the unchecking that i have done on the MManager ? ... or ... is there a way to flash a newly patched boot image triggering the flash from inside the MManager ?

As i am not a coder ... certain concepts are hard to wrap my head around ... and the lack(not able to find if there already is) of literature for 'NOOBS' has complicated things ... at least for me ... :open_mouth:  :rofl:

**Comment by Didgeridoohan** [comment]
If you're already rooted with Magisk, press Install -> Direct install in the Manager (after having disabled the options you don't want active). Done.

**Comment by aiamuzz** [comment]
> If you're already rooted with Magisk, press Install -> Direct install in the Manager (after having disabled the options you don't want active). Done.

oh wow ... :face_with_head_bandage: ... all along i had been sitting right on it ?

so let me get this a little more clearly ... 

1. I come from a fresh stock ROM flash ... 
2. Unlock bootloader
3. flash TWRP
4. flash Magisk zip
5. boot into the device
6. uncheck the verity and encryption flags and hit install on the Magisk Manager
7. Done

So the encryption is disabled on next reboot ?
or
we need to boot into twrp and do a factory reset ?

Will booting after the factory reset result in my device with force encryption turned off ?

**Comment by Didgeridoohan** [comment]
You can do it on a fresh install as well:
https://didgeridoohan.com/magisk/Magisk#hn_Disabling_dm-verity_and_forced_encryption

And Magisk only disabled the enforced encryption flag, the device will still be encrypted and a wipe of data will be necessary to remove the encryption.

**Comment by aiamuzz** [comment]
> And Magisk only disabled the enforced encryption flag, the device will still be encrypted and a wipe of data will be necessary to remove the encryption.

I am clear on that concept ... i believe earlier when encryption wasn't forced and if someone opted for it ... and when the disabled it ... If i am not wrong the OS would prompt them a warning that disabling encryption will reset the system to factory ... and when the user consents the process would proceed with a boot and reset wipe.

@topjohnwu ... @Didgeridoohan ... wouldn't it be good to provide the same warning prompt on Magisk as well when the user unchecks the setting preserve @Didgeridoohan ... wouldn't it be good to provide the same warning prompt on Magisk Manager when the user unchecks KEEPFORCEENCRYPT toggle ?

Seriously it would have saved me tons of mental agony and more importantly time in the form of late nights !!!

**@topjohnwu ... please consider adding that warning prompt ( you could even add a suggestion to make a nandroid backup on TWRP before you uncheck(disable) the KEEPFORCEENCRYPT toggle !!!**

**Comment by topjohnwu** [comment]
@aiamuzz the KEEPFORCEENCRYPT flag will be automatically enabled when your data is already encrypted. No need to shout out loud. This thing has been like this since the SuperSU days, I dunno why are you making a fuzz out of this...

**Comment by shailangsa** [comment]
how is it possible to get the disable verity option on newer versions of magisk?

**Comment by Werve** [comment]
I am also looking for a way to remove forceencrypt with the latest versions of Magisk.
Unfortunately, there is no Custom recovery on my device yet so the method with the .magisk file suggested here https://www.didgeridoohan.com/magisk/MagiskInstallationIssues# does not apply and neither do any similar methods that involve a .zip to flash.
I noticed that there is a config file in the directory that generates Magisk after installation in /dev/<random chrs>/.magisk/config where there is indicated the flags applied.
How can I modify them?
