### ISSUE TITLE
documentation issue: instructions on how to update a "magisk in recovery" system are missing

### ISSUE THREAD

**Issue by lemmy04** [topjohnwu/Magisk#2105]
Maybe I'm just blind, but I can't find instructions on how to update Magisk on a "magisk in recovery", *non* a/b system, i.e. Samsung Galaxy S10 or Tab S5e.

**Comment by topjohnwu** [comment]
It is written in the beginning: upgrade with Magisk Manager

**Comment by lemmy04** [comment]
"direct install", even on a system-as-root, non a/b device? that should be right there in writing...
