### ISSUE TITLE
Magisk Support for Beelink GT-King Android Box 9.0

### ISSUE THREAD

**Issue by denzele** [topjohnwu/Magisk#2113]
Hi there ,

just wondering if there's any way of getting Magisk successfully working on this Android TV Box that runs Android 9.0 . I got Magisk  installed with TWRP but once rebbot happens there's no magisk installed and also root is gone . Thanks

**Comment by osm0sis** [comment]
I explained this in the Magisk thread: https://forum.xda-developers.com/apps/magisk/mod-magisk-v1-universal-systemless-t3432382/post81048673#post81048673

**Comment by osm0sis** [comment]
Hmm, can you guys give me output from `ls -alR /dev/block` for this device?

**Comment by Syked69** [comment]
[Ls output - GT King.txt](https://github.com/topjohnwu/Magisk/files/3909576/Ls.output.-.GT.King.txt)
hi osm0sis,
the output is attached in the txt file

**Comment by Syked69** [comment]
Brand: Beelink
Model: GT-KING
Type: TV Box
System: Android 9.0 (non ATV)
CPU: Amlogic S922X

**Comment by osm0sis** [comment]
Thanks. All is named as it should be, so this might actually be a different issue than the Nvidia Shield TV.

**Comment by osm0sis** [comment]
What I said in the Nvidia Shield TV Issue before we knew a bit more still stands here though.

> For A-only SAR devices that don't accept the cpio ramdisk magiskboot creates, the only option is to patch the recovery partition instead.
> 
> You need to dump the stock recovery partition to recovery.img, then use the latest Magisk Manager Canary to patch it, with likely all 3 Advanced Settings checked for stock ROM.
> 
> Then you need to flash that recovery.img back to the recovery partition and then always only reboot the device to recovery.

I believe @Syked69 already reported this works in the Magisk thread, so you guys may be in the and boat as Samsung devices that just do not accept the cpio ramdisk magiskboot creates.

**Comment by topjohnwu** [comment]
Try installing Magisk to the recovery image

**Comment by Genxster1998** [comment]
But I don't have a way to boot directly in recovery mode through hardware buttons.so I have to first boot in system then use adb to reboot in recovery.
Amlogic T962x A only sar device.

**Comment by Matrix40au** [comment]
I have a HK1 Box (S905x3) and I was able to get Magisk installed!


Once you have your OS setup. Install TWRP, then nstall Magisk.

Create a Backup of Boot.img/Recovery.img in TWRP.
Then patch the boot image in Magisk..
Tick "Recovery Mode" and Patch Boot.img
Copy > magisk_patched_img > to internal SDcard/USB

Restart and go into TWRP Recovery and install the magiskPatched.IMG to the recover partition..

Reboot System once or twice, and hold the Reset in the AV switch and it shouldn't boot to Recovery, but instead it will load the the PatchedBootIMG saved in Recovery slot.

I was able to install Magisk.

** INSTALLED 22.1
RAMDISK NO
ZYGIST NO
SAR: YES

It takes over from SuperSU etc and you will have to grant SU rights etc, load addons!!..

I was so thrilled to work it out!!!!

**Comment by Phreakerthy** [comment]
Do you have the rom already with magisk installed? Do you have her backup already with magisk? I'm trying to install on a vontar x3 but without success the magisk does not recognize the root of the rom, can you post the backup of your rom already with magisk installed?
