### ISSUE TITLE
No root prompt

### ISSUE THREAD

**Issue by jgwallace3** [topjohnwu/Magisk#2122]
I have recently changed phones to a Oneplus 7 Pro, unlocked the bootloader and installed LineageOS 16 along with TWRP, GAPPS and Magisk on it. No errors were seen at install time.

When an app requests root, I am seeing no prompt and eventually the app reports root wasn't granted.

I am running canary build v20.2-72edbfc4(20108) in core-only mode. I'm attaching screenshots and logs. I see no obvious errors in the logs. Please help!

Magisk screen shot showing version:
![Screenshot_20191202-112501_Magisk_Manager](https://user-images.githubusercontent.com/10977044/69981106-9eb37b00-14ff-11ea-8b64-7632c85f0560.png)

App I used to check root with:
![Screenshot_20191202-112623_Root_Checker](https://user-images.githubusercontent.com/10977044/69981146-bb4fb300-14ff-11ea-8d4d-ee442e237cdf.png)

Magisk log: [magisk_log_20191202_112643.log](https://github.com/topjohnwu/Magisk/files/3912445/magisk_log_20191202_112643.log)

Logcat from ADB: [logcat.txt](https://github.com/topjohnwu/Magisk/files/3912450/logcat.txt)

TWRP log from install of magisk: [recovery.log](https://github.com/topjohnwu/Magisk/files/3912452/recovery.log)

**Comment by jgwallace3** [comment]
Oh, and just to add. I initially started with magisk 20.1 stable, encountered the 'no prompt' issue, then uninstalled (via twrp) and installed the canary build.

**Comment by topjohnwu** [comment]
Use the latest canary build, it is fixed

**Comment by jgwallace3** [comment]
Is there a more recent build than 20.2-72edbfc4(20108) ?
I'm looking here, per the xda thread: https://github.com/topjohnwu/magisk_files/tree/canary

**Comment by martyfender** [comment]
According to what I am reading, he did ude the latest Canary build.

**Comment by jgwallace3** [comment]
@topjohnwu Can you please clarify? I am using (and failing on) what I thought was the latest canary build - 20.2-72edbfc4(20108). Is there a more recent one? I'd love to give it a try.

**Comment by sireebob** [comment]
this github issue was the top search result for me so i wanted to add: wipe cache & dalvik.
i had this issue and spent a lot of unnecessary time troubleshooting it - my own fault - because i skip that step out of bad habit (i've never found it necessary until now).
i was able to go back to the stable version of magisk, too. canary not needed. just wipe cache & dalvik whenever you flash magisk.
this may not resolve all cases but i hope it helps someone.
