### ISSUE TITLE
Magisk support for Ulefone Armor 3wt - Android 9

### ISSUE THREAD

**Issue by danucu** [topjohnwu/Magisk#2123]
Hi there ,

just wondering if there's any way of getting Magisk successfully working on Ulefone Armor 3wt that runs Android 9. I tried with and without TWRP. With TWRP ended up in boot loop. Without TWRP cannot install magisk. This device uses dm-verity.

[ls_output.txt](https://github.com/topjohnwu/Magisk/files/3913685/ls_output.txt)

[ulefone armor 3wt.zip](https://github.com/topjohnwu/Magisk/files/3913651/ulefone.armor.3wt.zip)

**Comment by topjohnwu** [comment]
Use boot image patching method. Your device might also require patching recovery instead of boot image
