### ISSUE TITLE
Magisk 19.4+ Detected by Fate Grand Order

### ISSUE THREAD

**Issue by realmain** [topjohnwu/Magisk#2124]
I noticed that the game has been detecting Magisk on any version of Magisk 19.4+. I am staying with Magisk 19.3 currently because that is the only one working. Checked the game in Magisk Hide.

I also used [ProcGate](https://github.com/topjohnwu/ProcGate) to check for vulnerabilities, and there were no leaks.

I don't know what other info I can pull for you to assist.

Samsung Note 9
Magisk 19.4 - 20.1
Magisk Manager 7.4.0

**Comment by mbjurstrom** [comment]
I think this falls under 
https://github.com/topjohnwu/Magisk/issues/1152

**Comment by realmain** [comment]
I did see that post. I do not know if it does fall under that or not 100%. I feel like that is more for if all versions of Magisk doesn't work for an app, like even if an app updated and now Magisk stopped working.

The issue here is Magisk was internally changed in some way during 19.4 onwards which caused it to now be detected.

**Comment by fr0zenrain** [comment]
> I think this falls under
> #1152

procgate can't detect v18.4, i tested.

**Comment by ShidoDAL** [comment]
Finally it worked, i wait very long already.... Cant play 2 month of it already. Thanks for the tutorial
