### ISSUE TITLE
Oukitel k12 and Magisk

### ISSUE THREAD

**Issue by dimv36** [topjohnwu/Magisk#2126]
Hi all,

Bootloader is unlocked.
I try to install Magisk on my smartphone via flashing boot image.
First reboot is ok, MagiskManager marks that root is intalled. But when I restart my smartphone I see logo, stack, and smartphone moves to Fastboot mode ...

To unbrick it I flash boot via original boot.img. So, no root at all. Can you help me?

**Comment by xerta555** [comment]
> To unbrick it I flash boot via original boot.img. So, no root at all. Can you help me?

Hi, i think you should send here your boot.img stock file and the modded one (by rebooting directly in custom recovery just after the install).

**Comment by dimv36** [comment]
Hi, boot and patched boot are hire: [https://yadi.sk/d/iWfdLP43JUyq6A](url).

My problem is solved. Boot stuck will be caused, I think, that I remove system applications like Google Music etc via [https://system-app-rem…u.uptodown.com/android](url), not Magisk module.
