### ISSUE TITLE
Kernel zip installtion

### ISSUE THREAD

**Issue by asprakash** [topjohnwu/Magisk#2130]
Hi. I am trying to install custom kernel without TWRP. Then I found this great Magisk tool. I followed the instruction and installed Magisk on my samsung A505. I also noted this from the Magisk installation document, "If you plan to install custom kernels, flash the zip AFTER installing Magisk". Can you give some guidance on how to prepare a zip file for custom kernel and install it from Magisk?. Here I assumed, installing kernel zip dont required TWRP.   

TIA.

**Comment by topjohnwu** [comment]
Please ask your custom kernel developer for instructions
