### ISSUE TITLE
小米8 AndroidQ /sbin/magiskinit -x manager /data/magisk.apk ——》“System error”

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#2134]
use magisk20.1
/sbin/magiskinit 并不是magisk的。 而是厂家自带的。 magiskinit size is error
/sbin/magiskinit -x manager /data/magisk.apk 报错 严重错误 手机卡死 
请大神务必重视这个重大错误

![错误](https://user-images.githubusercontent.com/11062371/70376908-227ac680-1949-11ea-8ce0-f60dddc362e5.png)
![错误2](https://user-images.githubusercontent.com/11062371/70377019-3ffc6000-194a-11ea-94dd-17d374c24551.png)

**Comment by androiddisk** [comment]
![错误](https://user-images.githubusercontent.com/11062371/70377001-0af00d80-194a-11ea-9258-7d4f8c6b226d.png)

**Comment by topjohnwu** [comment]
請告訴你的 custom ROM 作者不要做把 `magiskinit` 放在 ROM 裡面這種低能事情.....

**Comment by topjohnwu** [comment]
Same as #2133

**Comment by vvb2060** [comment]
你能提供使用的系统版本在MIUI官方的下载地址吗？

**Comment by androiddisk** [comment]
> 你能提供使用的系统版本在MIUI官方的下载地址吗？

https://bigota.d.miui.com/9.12.5/miui_MI8_9.12.5_6e60503465_10.0.zip

附件是开机后提取的/sbin/magiskinit 由于无法直接上传我修改了后缀
[magiskinit.ZIP](https://github.com/topjohnwu/Magisk/files/3939493/magiskinit.ZIP)
