### ISSUE TITLE
Using supolicy in post-fs-data.sh cause any service.sh won't be executed.

### ISSUE THREAD

**Issue by i1itione** [topjohnwu/Magisk#2137]
This Magisk module, EdXposed (older version before v0.4.6.0) uses supolicy command for live patch in its post-fs-data.sh, and then will cause any other service.sh won't be executed.

11-09 17:32:33.341   476   477 I Magisk  : riru_edxposed_sandhook: exec [post-fs-data.sh]
12-09 06:52:18.644   476   910 I Magisk  : ** late_start service mode running
12-09 06:52:21.491   476   477 I Magisk  : * Loading modules

**Comment by martyfender** [comment]
Did you see what John stated on Twitter:

John Wu
‏ @topjohnwu
1h1 hour ago

Proper pre-init sepolicy patch for modules is currently in the works and progress is looking good. This shall provide the proper foundation for custom sepolicy patches as live patching is either buggy or outright impossible. Edxposed users rejoice!
