### ISSUE TITLE
OTA update detects that S9+ is rooted

### ISSUE THREAD

**Issue by nemui3353** [topjohnwu/Magisk#2138]
I followed the tutorial on Magisk OTA Update Tutorial page 
No Custom Recovery installed, 
Install Magisk patched stock boot image through Odin, 
Insert gzipped Stock boot image to /data partition,
restore boot image to stock But OTA updates detected that it's modified device..

so I completely remove Magisk trhough Magisk Manager, and reboot to check the status on Download mode. The status is still custom..
Is this Magisk's problem or Samsung is too strict to root users?

**Comment by topjohnwu** [comment]
It's a problem of Samsung, not Magisk
