### ISSUE TITLE
華為EMUI9，模組無法釋放文檔到product分區

### ISSUE THREAD

**Issue by maimaiguanfan** [topjohnwu/Magisk#2139]
存在/sbin/.magisk/mirror/product，但是安裝修改product分區的模組後，應被釋放到/product的文檔未被釋放，magisk canary19.4至最新版均存在該問題

**Comment by topjohnwu** [comment]
請查閱 module 製作相關文檔，`/product` bind mounting 確認是正常運作的

**Comment by maimaiguanfan** [comment]
使用的是Quickswitch最新版，基本上確認正常

John Wu <notifications@github.com> 于 2019年12月11日周三 下午5:52写道：

**Comment by maimaiguanfan** [comment]
再次確認，本人製作的模組。同一設備，在AOSP10，product文檔釋放正常。回到EMUI9，重啟後product文檔未被釋放，/data/adb/modules中模組/product軟連接已創建，但是裡面的文檔消失
