### ISSUE TITLE
HTC One x+ support

### ISSUE THREAD

**Issue by AnotherPony** [topjohnwu/Magisk#214]
**Recovery logs:**
`- Flashing new boot image
1130+0 records in
1130+0 records out
4628480 bytes (4.4MB) copied, 0.174501 seconds, 25.3MB/s
- Unmounting partitions
losetup: /dev/block/loop0: No such device or address
- Done
I:Legacy property environment disabled.
Updating partition details...
I:Data backup size is 6154MB, free: 22883MB.
I:Can't probe device /dev/block/mmcblk0p5
E:Unable to mount '/recovery'
I:Actual block device: '/dev/block/mmcblk0p5', current file system: 'ext4'
...done
I:Set page: 'flash_done'
I:operation_end - status=0`

**[boot.zip](https://github.com/topjohnwu/Magisk/files/1021882/boot.zip)**

**Comment by topjohnwu** [comment]
Your logs does not mean it's broken
