### ISSUE TITLE
Enabling MagiskHide crashes WebView Zygote (Android 9 AOSP)

### ISSUE THREAD

**Issue by cdebavel** [topjohnwu/Magisk#2141]
Enabling MagiskHide (not enabling hiding any apps) results in the webview zygote getting a 'Permission Denied' when trying to access trace_marker, crashing it:

webview_zygote: jni_internal.cc:616] JNI FatalError called: (com.android.webview:sandboxed_process0) Failed open(/sys/kernel/debug/tracing/trace_marker, 1): Permission denied

Doesn't matter what WebView implementation is used.

Also posted here: https://gitlab.com/LineageOS/issues/android/issues/1470

**Comment by topjohnwu** [comment]
Your ROM might assume it will always run in `userdebug` mode, which will not be the case when MagiskHide is enabled.

**Comment by cdebavel** [comment]
Should changing the ro property to 'user' affect that? I tried doing that
with the Props Config module and the behavior was the same.

**Comment by Didgeridoohan** [comment]
@cdebavel Just to be clear: If that is your issue, changing the prop to `userdebug` would be the solution (or disabling MagiskHide and rebooting).

**Comment by cdebavel** [comment]
Changing the prop to 'userdebug' and rebooting doesn't prevent the crash,
but disabling MagiskHide and rebooting does.

**Comment by Didgeridoohan** [comment]
In that case it could be one or more of the other MagiskHide props as well that needs to be changed. You could try disabling then one by one until you find the culprit or culprits.

**Comment by tytydraco** [comment]
I had this exact crash on the latest stable. It turns out it was caused by a bad module that didn't sleep long enough after boot. Hope this can help someone who comes across this.

**Comment by matejdro** [comment]
@tytydraco Have you managed to find a solution or a workaround for this? It seems this breaks the chroot completely. Or is it fine not having access to /sys?

**Comment by matejdro** [comment]
If anyone else attempting to set up chroot stumbles upon this thread, the trick is that you have to mount `/sys` with `--rbind` flag:

`mount --rbind /sys $chroot_folder/sys`

That way all child mounts inside `/sys` will also be mounted, which seems to fix the issue for some reason.
