### ISSUE TITLE
Uninstall magisk cause bootloop

### ISSUE THREAD

**Issue by divadres** [topjohnwu/Magisk#2142]
Hi,
I use magisk 20.1 on Xiamoi mi6 with MIUI 11, when I uninstall magisk either from recovery or from magisk manager I get a bootloop that I can only fix by flashing the partition system with stock image or reinstalling magisk.
In magisk theory you should not modify the system partition, right? and if magisk modifies it, it would restore it when it is uninstalled, right?

**Comment by topjohnwu** [comment]
Magisk itself will not change anything other than the boot image. However, since it provides root access, there are many ways you can mess up your device, which I will not be able to solve.
