### ISSUE TITLE
AOSP Build requirements?

### ISSUE THREAD

**Issue by dasJ** [topjohnwu/Magisk#2144]
Don't get me wrong, I'm not asking for "Hey, how can I integrate Magisk into my ROM?"
Instead, the question is more basic: Is it enough to rename init (as in #509) and place magiskinit as /init?
Ofc, the APK must also be built, but does a fully working Magisk (with the ability to install modules later) require more than magiskinit as /init?

**Comment by topjohnwu** [comment]
The build process of `magiskinit` isn't trivial as it embeds multiple binaries into itself (thar might change in the future). The bigger problem is that `magiskinit` expect to run on `rootfs`, which is not the case when you build it in AOSP in system-as-root setup. Currently there is no plan to support that setup as it requires significant changes to Magisk's design
