### ISSUE TITLE
Recovery Bootloop

### ISSUE THREAD

**Issue by Vanman989** [topjohnwu/Magisk#2145]
Recovery Bootloop after installing magisk 19.3 and 20.1 on MI9T MIUI 11.0.1.0 Global official. Flashing and through TWRP

**Comment by Vanman989** [comment]
Hi, sorry it took me while to realise magisk was making my phone constantly boot into recovery. When uninstalled it would stop. Is there a fix to this? Or will it be fixed in the next release?

**Comment by towlie** [comment]
Might be related to this:
https://github.com/topjohnwu/Magisk/issues/2008#issuecomment-548365369
