### ISSUE TITLE
Segmentation fault on stock boot 9.0

### ISSUE THREAD

**Issue by systemizer99** [topjohnwu/Magisk#2146]
Hello, topjohnwu.
I have a problem when patching stock boot image. Here is the log. Please, help me.
`- Device platform: arm64-v8a
- Copying image to cache
1566+0 records in
1566+0 records out
1603584 bytes transferred in 0.024 secs (66816000 bytes/sec)
1045+1 records in
1045+1 records out
1070668 bytes transferred in 0.016 secs (66916750 bytes/sec)
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [1]
KERNEL_SZ       [15220198]
RAMDISK_SZ      [6466936]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2019-11]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyMSM0,115200,n8 androidboot.console=ttyMSM0 androidboot.hardware=qcom androidboot.memcg=true msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_serial_dm,0x78B0000 firmware_class.path=/vendor/firmware_mnt/image androidboot.usbconfigfs=true loop.max_part=7 buildvariant=user]
CHECKSUM        [55b009f09897522f9ef5d7ec3f101e7fd76e90ed000000000000000000000000]
Segmentation fault 
- Checking ramdisk status
- Stock boot image detected
- Backing up stock boot image
- Patching ramdisk
Add entry [init] (0750)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [1]
KERNEL_SZ       [15220198]
RAMDISK_SZ      [6466936]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2019-11]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyMSM0,115200,n8 androidboot.console=ttyMSM0 androidboot.hardware=qcom androidboot.memcg=true msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_serial_dm,0x78B0000 firmware_class.path=/vendor/firmware_mnt/image androidboot.usbconfigfs=true loop.max_part=7 buildvariant=user]
CHECKSUM        [55b009f09897522f9ef5d7ec3f101e7fd76e90ed000000000000000000000000]
Segmentation fault 
! Unable to repack boot image!
! Installation failed
`
Magisk 20.1 / 7.4.0

**Comment by topjohnwu** [comment]
Please try using the canary channel, and also, please upload your boot image

**Comment by systemizer99** [comment]
Here is the image
[boot.zip](https://github.com/topjohnwu/Magisk/files/3961080/boot.zip)

**Comment by osm0sis** [comment]
Uhhh

```
Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers

Supplied image: boot.img

Setting up work folders...

Image type: AOSP

Splitting image to "split_img/"...
BOARD_KERNEL_CMDLINE console=ttyMSM0,115200,n8 androidboot.console=ttyMSM0 androidboot.hardware=qcom androidboot.memcg=true msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_serial_dm,0x78B0000 firmware_class.path=/vendor/firmware_mnt/image androidboot.usbconfigfs=true loop.max_part=7 buildvariant=user
BOARD_KERNEL_BASE 80000000
BOARD_NAME 
BOARD_PAGE_SIZE 2048
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 00008000
BOARD_RAMDISK_OFFSET 01000000
BOARD_SECOND_OFFSET 00f00000
BOARD_TAGS_OFFSET 00000100
BOARD_OS_VERSION 9.0.0
BOARD_OS_PATCH_LEVEL 2019-11
BOARD_HEADER_VERSION 1
BOARD_HEADER_SIZE 1648

Unpacking ramdisk to "ramdisk/"...

Compression used: tar
Unsupported format.
Error!
```

**Comment by osm0sis** [comment]
On even closer inspection somehow the split Image.gz is 15mb where the boot.img is only 7.3mb, so either this is a boot.img with a bad header or it's truncated from an incomplete dump/bad download.

**Comment by topjohnwu** [comment]
Thanks for the investigation @osm0sis, will close this issue
