### ISSUE TITLE
華為EMUI9，模組無法釋放文檔到product分區

### ISSUE THREAD

**Issue by maimaiguanfan** [topjohnwu/Magisk#2148]
請注意，並非模組問題，已確認。本人製作的模組，同一設備，在AOSP10，product文檔釋放正常。回到EMUI9，重啟後product文檔未被釋放，/data/adb/modules中模組/product軟鏈已創建，但是裡面的文檔消失
本人製作的模組https://mega.nz/#!UnZkzKhK!YbpqIqZAcuKvzl2z2Zuo0pNpA46JHKKt2_EaBAdwCC0

**Comment by topjohnwu** [comment]
#2359

**Comment by maimaiguanfan** [comment]
多謝。已安裝模組，但問題仍然存在

John Wu <notifications@github.com> 于 2020年2月1日周六 上午1:45写道：

**Comment by Didgeridoohan** [comment]
You'd have to provide more info than that... For starters, what's the output of `cat /proc/mounts`?

**Comment by maimaiguanfan** [comment]
Thanks. It's nice that you can help me.
I got it.
https://mega.nz/#!Zu5WSa6S!mjLPPDQm2ULySfVm_sL0x1DI4FSsBO7otdhwQYbZk8c

/product (real product partition) is mounted. I flashed a mod,and I can see
the file was released into /data/adb/modules. However, after reboot, all
the files of the mods in /system/product disappeared (the files in /system
and /system/vendor didn't).

Didgeridoohan <notifications@github.com> 于 2020年2月8日周六 上午1:08写道：

**Comment by maimaiguanfan** [comment]
> You'd have to provide more info than that... For starters, what's the output of `cat /proc/mounts`?

![1581162154743_Screenshot_20200208_193645_bin mt plus](https://user-images.githubusercontent.com/55618987/74084550-365aba00-4aab-11ea-89a5-f1974bcf2885.jpg)
