### ISSUE TITLE
magisk hide not working good - best practices read 

### ISSUE THREAD

**Issue by Clod-7** [topjohnwu/Magisk#2149]
First of all, I want you to know that I've read all the best practices in the tutorial, tried them and the problem can't be solved.

I have a galaxy a3 (SM-a320FL) with android 7 and magisk 20.1 - magisk manager 7.4
It has been working fine until some days ago, now the banking app (UBS Access app) find root and doesn't work. Safetynet check is green, everything works and other apps can't find root.
I think the problem has started with the latest update of the banking app UBS Access.
Magisk is renamed with random name.

Other root apps installed are: 
Adaway (installed after option Host systemless activated)
All in one toolbox
SD Maid
Root uninstaller
App Ops

I tried to uninstall/reinstall the banking app, same thing with magisk, but nothing changes. I also tried to swith off debug and developer options, but nothing changes.

I wonder if you are able to solve my problem.
thank you

**Comment by MikuDroid** [comment]
Same thing here with [Grab Driver App](https://play.google.com/store/apps/details?id=com.grabtaxi.driver2), using magisk 20.2 canary. The app finally catching up with magisk manager hiding binary method. Despite having all checks green using RootBeer Fresh, safetynet also green, Grab Driver still detects my device as rooted.

**Comment by MikuDroid** [comment]
Ah, my bad. I think this issue should also fall into #1152 right? :(

**Comment by topjohnwu** [comment]
@MikuDroid yes :)
