### ISSUE TITLE
MagiskHide failed to proc on apps installed on adopted storage (SD card)

### ISSUE THREAD

**Issue by NoblePink** [topjohnwu/Magisk#2150]
Before anyone cite 1152 here, please understand that the Best Practices guide does not mention anything about MagiskHide itself not proccing at all when it should (it'll show up in the logs when it does but it didn't). I've made a video demonstrating the problem:

https://twitter.com/NoblePink/status/1205959114393735168

It's done on a fresh reboot with Magisk on core only mode. First I opened the Magisk log which shows the apps on the hide list, then I proceed to open the apps on it (all are installed on SD card). One game detected root and after I opened the other 2 non-root related apps, I went back to Magisk log and hit refresh several times but nothing shows up (indicating that MagiskHide didn't proc). After that I moved all 3 apps to internal storage and open them again, the game works fine and MagiskHide did indeed procced as shown in the log.

I would like to note that if the apps in my test case above are moved to the SD card again, MagiskHide will still proc but will fail again after a couple of hours and it doesn't survive reboot. The same happens if an app is added to the hide list first before being moved to SD card.

**Comment by Didgeridoohan** [comment]
Yes, it's known that [apps installed to adoptable/external storage](https://didgeridoohan.com/magisk/MagiskHide) can't be detected by MagiskHide.

Can't remember right know if there is anything that @topjohnwu can do about it...

**Comment by NoblePink** [comment]
Well this is unfortunate. If this bug has been around for a long time without solution perhaps the official documentations should be updated to inform users?

**Comment by topjohnwu** [comment]
Docs are updated
