### ISSUE TITLE
After hiding Magisk Manager, boot image is not backed up in some circumstances

### ISSUE THREAD

**Issue by nooriro** [topjohnwu/Magisk#2152]
## Environment
- Google Pixel 3 XL ( QP1A.191105.003 and QQ1A.191205.008 ) with BL unlocked
- Magisk Manager 7.4.0 (253)
- Magisk 20.1 (20100)

## Steps to Reproduce
1. Flash-all QP1A.191105.003 factory image via fastboot mode
2. Install Magisk Manager 7.4.0
3. Run Magisk Manager and install Magisk 20.1 (by patching `boot.img` and flashing `magisk_patched.img` via fastboot mode)
4. **Hide Magisk Manager with changing the app name to 😎🌰😁**
5. Run 😎🌰😁 and click [UNINSTALL] > [RESTORE IMAGES]
6. Do OTA ( Settings > System > System update )
7. **After OTA, click [Restart now] WITHOUT INSTALLING MAGISK TO INACTIVE SLOT**
8. **After reboot, run 😎🌰😁 and install Magisk 20.1 again** (by patching `boot.img` and flashing `magisk_patched.img` via fastboot mode)

## Expected Results
- There should be two boot image backups in `/data` directory.
  <img src="https://user-images.githubusercontent.com/16160401/70858296-d8927180-1f42-11ea-9fa2-f8fcc42296d8.png" alt="Screenshot_20191213-172516" width="360">
  - One is from QP1A.191105.003 (step 3) : `stock_boot_907ffbe20d180b90d033a313f5d2fd0b8ed862dd.img.gz`
  - The other is from QQ1A.191205.008 (step 8) : `stock_boot_f4f604ae3a93e5595907269215aeb46dd019db3b.img.gz`

## Actual Results
- **There's only one boot image backup** in `/data` directory.
  <img src="https://user-images.githubusercontent.com/16160401/70858327-6e2e0100-1f43-11ea-9dfb-8576eca5c1ab.png" alt="Screenshot_20191214-144323" width="360">
  - It is from QP1A.191105.003 (step 3) : `stock_boot_907ffbe20d180b90d033a313f5d2fd0b8ed862dd.img.gz`
  - **QQ1A.191205.008's boot image (step 8) has never been backed up.**

## More Infos
- Installation log of step 3 : [magisk_install_log_2019-12-14T142436Z.log](https://github.com/topjohnwu/Magisk/files/3964616/magisk_install_log_2019-12-14T142436Z.log)
- **Installation log of step 8 : [magisk_install_log_2019-12-14T144127Z.log](https://github.com/topjohnwu/Magisk/files/3964617/magisk_install_log_2019-12-14T144127Z.log)**
- Instead of steps 5 to 7, each of the following produces the same result
  - **adb sideload the full ota image** of QQ1A.191205.008
  - **flash-all** (with `-w` removed) **the factory image** of QQ1A.191205.008
- Even though QQ1A.191205.008's boot image has not been backed up, `/sbin/.magisk/config` **has the correct SHA1 hash value** of QQ1A.191205.008's boot image : `f4f604ae3a93e5595907269215aeb46dd019db3b`
  <img src="https://user-images.githubusercontent.com/16160401/70858596-1219ab80-1f48-11ea-9139-e25586493d55.png" alt="Screenshot_20191214-144405" width="360">

**Comment by topjohnwu** [comment]
The package name is renamed, so the daemon cannot find the location where to find the manager. It is in theory possible to find, but it is currently a very low priority

**Comment by osm0sis** [comment]
Shouldn't it just be copied as part of the patching/flashing script/activity?

**Comment by topjohnwu** [comment]
@osm0sis I assume in his case he is patching without root. The magisk daemon normally searches for the folder `/data/user_de/0/com.topjohnwu.magisk/install` and copy it as `/data/adb/magisk`, however if the app is repackaged that path obviously does not exist
