### ISSUE TITLE
OnePlus 7T CPU stuck on maximum frequency

### ISSUE THREAD

**Issue by BRUHItsABunny** [topjohnwu/Magisk#2154]
Hi, after the new update OnePlus has released for the 7T (OxygenOS 10.0.7) I noticed that the prime cluster is locked to it's highest frequency. It causes the phone to heat up while browsing the web and also drains the battery almost 90% during night time when it's supposed to go into "deep sleep".

I have no idea what causes this and how to debug it.

I tried to:
let the battery drain all the way
reboot
wipe dalvik cache
factory reset
local update after factory reset (this one fixed it!)

However after fixing it, booting ANY root patched boot.img causes the same issue and the issue stays after installing magisk (v20.1). This is BEFORE I even flashed my custom kernel, ElementalX kernel that is.

The rooting guide I followed:
https://forum.xda-developers.com/oneplus-7t/how-to/guide-how-to-root-oneplus-7t-twrp-t3979307/amp/
Also tried a variation of that guide in which I pulled the boot.img from my own phone rather than downloading one that has been patched already.

How can I figure out what's going on here?

This screenshot shows the CPU being stuck in highest frequency while watching YouTube
![1199306-f2e8744a10ca20a607cb19d1ead15378](https://user-images.githubusercontent.com/53124399/70859982-4312c580-1ee1-11ea-801b-96281a589017.jpg)

This screenshot shows the CPU being stuck in said frequency for the past 6 or so hours without a single dip below it.
![1199308-e955e95988caefeaab5c2c6d09d11fee](https://user-images.githubusercontent.com/53124399/70859983-43ab5c00-1ee1-11ea-98c9-2ed4666411fb.jpg)

**Comment by topjohnwu** [comment]
There are many people using Magisk on OnePlus 7T without issues. You might have some something weird causing this issue, not inherently caused by Magisk
