### ISSUE TITLE
no modules list after install some modules [MAGISK STABLE V20.1][PRIME OS]

### ISSUE THREAD

**Issue by Draconixss** [topjohnwu/Magisk#2155]
i want to install NFS injector and succes
this is the log:
- Copying zip to temp directory
- Installing NFS_INJECTOR_nfsinjector-v8.8(971).zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh
  inflating: sepolicy.sh
  inflating: service.sh
  inflating: system.prop
  inflating: unity_upgrade.sh
  inflating: addon.sh
  inflating: busybox
  inflating: busybox
  inflating: util_functions.sh
  inflating: install.sh
  inflating: module.prop
  inflating: uninstall.sh
 
Unzipping files...
___  | / /__  ____/_  ___/
__   |/ /__  /_   _____ 
_  /|  / _  __/   ____/ /
/_/ |_/  /_/      /____/
 
* ϟ NFS-INJECTOR ϟ *
 
* KING OF MODS *
 
* Module For Forcefulness & Energy Aware *
 
* Flash , Reboot And Forget *
 
* Official Telegram Group @nfsinjector *
 
* By K1KS & Team *
- MagiskSU detected
 
- Installing
   Installing scripts and files for x86 SDK 25 device...
 
- Setting Permissions
 
    *******************************************
    *      Powered by Magisk (@topjohnwu)     *
    *******************************************
 
    *******************************************
    *    Unity by ahrion & zackptg5 @ XDA     *
    *******************************************
 
after i reboot and open the modules menu
its empty :(

**Comment by topjohnwu** [comment]
Please report to the module developer
