### ISSUE TITLE
[12.0] Generic Hide from SafetyNet

### ISSUE THREAD

**Issue by ChrisCheney** [topjohnwu/Magisk#216]
As I noted in issue #193 there is a module that allows SafetyNet (Android Pay, etc) to pass for gemini phones. If possible it would be nice to integrate the changes they make directly into Magisk so it will work properly for all Android devices.

https://gitlab.com/alelec/magisk-gemini-safetynet-props/builds/14015433/artifacts/download

**Comment by TheComputerGuy96** [comment]
@ChrisCheney Maybe

**Comment by topjohnwu** [comment]
Please don't report SafetyNet related issues unless you provide an improvement to the hide mechanism, thanks
