### ISSUE TITLE
MagiskPolicy causing boot freeze on Android 10

### ISSUE THREAD

**Issue by Pittvandewitt** [topjohnwu/Magisk#2160]
When using a module with a post-fs-data.sh file that contains magiskpolicy rules, the device will get stuck booting. This happens on devices running Android 10, but not all. To workaround this issue commenting out these magiskpolicy rules and running setenforce 0 allows the device to boot, but this is very undesirable as it's much more of a security issue.

There's a log in the attachment

[console-ramoops-0.txt](https://github.com/topjohnwu/Magisk/files/3968356/console-ramoops-0.txt)

**Comment by Didgeridoohan** [comment]
Already being worked on...
https://twitter.com/topjohnwu/status/1203808733953966080?s=20

And there are a couple of commits on this already.

**Comment by topjohnwu** [comment]
Live patching is never officially supported, but new methods to patch sepolicy is added (12fda2928051601ebc7fac980fae29a80e7979cc). Please wait for the next version

**Comment by Pittvandewitt** [comment]
I must have missed that. Thank you very much for the update
