### ISSUE TITLE
No superuser popup

### ISSUE THREAD

**Issue by jabba80** [topjohnwu/Magisk#2161]
Environment:
----------------
- Honor 7x (BND-L21C432) running Openkirin build of Ressurection Remix 7.0.1
- Magisk 20.1
   - installed via patched revovery_ramdis.img
   - partition extracted from BND-L21 9.1.0.141(C432E2R1P1)
- Magisk Manger 7.4.0

Description:
--------------
If I boot the device holding up and pwr & release just after the honor-splash-screen, the Magisk Manager App tells me everything is fine.
But no app (even root-checker) is able to gain root-previleges, as the popup does not appear.
I already disabled all battery-optimization for the Magisk Manager App.
Also a su on an adb-shell does not work and is logged with "request rejected".
An automatic "allow" in the superuser settings of magisk results in the same error-msg.

**Comment by jabba80** [comment]
Meanwhile updated Magisk to v20.2-11b7076a(20109), but behaviour is still the same.

Attached a magisk-log.
[magisk_log_20191216_154843.log](https://github.com/topjohnwu/Magisk/files/3968585/magisk_log_20191216_154843.log)

**Comment by topjohnwu** [comment]
Please use the debug version for bug reporting. Also, this does not make sense because activity launching method is proven to be working, make sure you are also on the latest Magisk Manager

**Comment by jabba80** [comment]
Just to confirm there's no problem at all with magisk. Seems to be @Ressurection Remix. Tried with OmniRom and everything worked as expected.

**Comment by sireebob** [comment]
try to wipe cache & dalvik if you ever run into this again

**Comment by whyorean** [comment]
> try to wipe cache & dalvik if you ever run into this again

Thanks buddy !
