### ISSUE TITLE
Fortnite v11.30+ detects magisk

### ISSUE THREAD

**Issue by sashankvisweshwaran** [topjohnwu/Magisk#2162]
Fortnite v11.30+ detects magisk even with magisk hide enabled, and magisk manager package name randomized (even without magisk manager app) oem unlock disabled, usb debugging disabled. OnePlus 6 OOS 10.0.1, Magisk v20.1, even v20.2 is being detected....idk how to attach log here

**Comment by topjohnwu** [comment]
#1152

**Comment by Didgeridoohan** [comment]
Tip: I've seen reports that the app is looking for folders and files on your device that can be a sign of a rooted device. The TWRP folder has been mentioned (try renaming it to something else).
