### ISSUE TITLE
Select all option in Magisk Hide

### ISSUE THREAD

**Issue by CaptainRedHat** [topjohnwu/Magisk#2165]
As a user, I want the ability to "select all" applications on the Magisk Hide screen.Personally, I like to hide Magisk from all applications and then unhide only the apps that need root.

Another way to implement this would be to have magisk hidden from all apps by default and then a user can unhide it from the apps that need root. If you really think about it, most users have more non-root apps than root apps, so I believe that this should be the default behavior.

**Comment by topjohnwu** [comment]
If you read the docs, you will understand that doing so will crash your device.
DO NOT ADD ALL APPS TO THE HIDE LIST OR YOUR DEVICE WILL VERY LIKELY BREAK.
