### ISSUE TITLE
Replace early mounts (system, vendor, etc)

### ISSUE THREAD

**Issue by mittorn** [topjohnwu/Magisk#2166]
Is it possible to replace vendor partition by system subdirectory?
My device fails to start rild if vendor modified (radio seems to have on dm-verify implementation), but i need change fstab to disable FDE.
I tried to place vendor copy in /system/vendor1 and mount with bind (in device tree), but it failed to start anyway, is there any solution to change early mounts in magisk?
Also i tried to replace it by symlink, but it seems to be removed during boot
I do not have free different partition to use it instead of vendor

**Comment by topjohnwu** [comment]
I do not plan support any non standard modifications.
