### ISSUE TITLE
Magisk seems to be crashing My LG v20

### ISSUE THREAD

**Issue by Nitrucks** [topjohnwu/Magisk#217]
Firstly, I apologize if this is not the right place for this.

In summary, it seems that every time, with what I've tested (v 12 and v11.6), crashes my LG v20 T-Mobile.

On the stock stock rom installed by Mega Rom for LG v20 with magisk, and magisk manager pre-installed with it. It would often bring up System Process isn't responding, and would prompt me to either wait, or close the app. If i close the app it doesn't bring it up again, but still crashes. If i press "wait", it prompts me again after a couple of seconds, then crashes.

Both cause the crashes do not fully restart the phone. From the looks of how long it takes, it may be a soft restart.

I appreciate any help ahead of time!

**Comment by Argeovus** [comment]
Having same issue, my phone will reboot about 30 seconds after it starts. Only way to stop the reboots is to uninstall magisk completely.
