### ISSUE TITLE
Android fails to boot on restore using Magisk 19.4+

### ISSUE THREAD

**Issue by IgorGolyanov** [topjohnwu/Magisk#2171]
If I create a backup with TWRP and restore from it, Android hangs on boot (see attachment). Confirmed working with Magisk 19.3, fails with any higher version.
Logcat + ls/mount command outputs attached.
Android 8.1.0, Pixel 2, TWRP 3.3.0-0

[logcat.txt](https://github.com/topjohnwu/Magisk/files/3991693/logcat.txt)
[ls_mount.txt](https://github.com/topjohnwu/Magisk/files/3991694/ls_mount.txt)
![photo_2019-12-21_14-57-42](https://user-images.githubusercontent.com/1529164/71312226-6ab1e280-2439-11ea-8c6f-ea52ff91ca68.jpg)

**Comment by topjohnwu** [comment]
This has nothing to do with Magisk. Full data backups never really works as it used to be, I have no idea what caused this issue. Try to restore to stock boot image and see if it boots for you

**Comment by IgorGolyanov** [comment]
The backup was created from a clean factory image provided by Google. I tried restoring it about 10 times: always works without Magisk or with Magisk up to 19.3. Never works with 19.4+. Could you maybe try to replicate the issue?
