### ISSUE TITLE
Missing .disable_magisk

### ISSUE THREAD

**Issue by ShalokShalom** [topjohnwu/Magisk#2172]
Hi there :hugs: 

My S5 installation has no such file installed. That is, the file itself is there, while without any content. Simply empty. 

Do you have this file for download?

I found nothing in the repo search. 

Greetz

**Comment by topjohnwu** [comment]
It's just a file to notify Magisk to run in core only mode, users don't need to mess with it, change the settings in Magisk Manager

**Comment by ShalokShalom** [comment]
Yeah, its just not working 

When I touch it, its not doing anything. 

MM is working.
