### ISSUE TITLE
Hide Magisk Manager: main UI activated on first root request after reboot

### ISSUE THREAD

**Issue by dantmnf** [topjohnwu/Magisk#2173]
I'm using https://github.com/RikkaApps/Shizuku , which launches a server program with root on LOCKED_BOOT_COMPLETED or BOOT_COMPLETED.

However:
1. It won't start until device unlocked. (the app is direct boot aware, not sure if related to the next issue)
2. when using Hide Magisk Manager, it will bring up the main activity of Magisk Manager.

Device: OnePlus 7 Pro
System version: HydrogenOS (Android 10) various revision

**Comment by Didgeridoohan** [comment]
I'm assuming that you're testing this in the stable release? All bug reports should be made after testing on the Canary Debug release (on which at least #2 should already be fixed, IIRC).

**Comment by dantmnf** [comment]
I can confirm issue 2 is fixed in canary builds.

Now I will take a look on issue 1...
