### ISSUE TITLE
Magisk Manager 7.4 keeps crashing

### ISSUE THREAD

**Issue by m1cm1c** [topjohnwu/Magisk#2174]
I used to use an old version of Magisk Manager. However, when I opened it today, it wanted to update itself. The updated version (7.4) did not work. Every time I opened it, Android said "Magisk Manager keeps crashing". Magisk Manager 7.3.5 works. (The version I used to use was older but I don't know which version it was exactly.)

Phone: OnePlus 6
OxygenOS version: 9.0.9
Android version: 9

**Comment by martyfender** [comment]
Have you tried to go to Android settings, app and delete Magisk Manager data and cache, then relaunch the app?

**Comment by m1cm1c** [comment]
@martyfender Yes. At first I rebooted, checked, deleted the app's cache, checked, deleted the app's cache and data, and checked.

**Comment by topjohnwu** [comment]
I can't help you without logs from debug builds
