### ISSUE TITLE
cant root vivo v3. error 1 twrp

### ISSUE THREAD

**Issue by fiqhqy** [topjohnwu/Magisk#2177]
Sir,  i using vivo v3. I cant root my devices.  In twrp still error 1. I try to patch boot.img but my devices bootloop.  So,  can u check my boot.img ? Then i can root my devices.  Thanks

**Comment by fiqhqy** [comment]
This my boot cant patched

https://www.dropbox.com/s/i83o9ooclkxifoe/boot.img?dl=0

**Comment by fiqhqy** [comment]
Android version : 5
Soc : snap 616
Name : vivo v3

![Screenshot_20191225_165929](https://user-images.githubusercontent.com/59210930/71442321-fbd5d180-2737-11ea-9242-7813ff880682.jpg)

**Comment by Bruhmantheboy** [comment]
@topjohnwu How did you root your phone please tell me I have somehow got TWRP 3.1.1 but I can't  root my phone please tell me sir how to root it my specifications are just like yours.
