### ISSUE TITLE
Bootloop after OTA on OP6 w/o TWRP and with TWRP

### ISSUE THREAD

**Issue by stilltldr** [topjohnwu/Magisk#2178]
Hi,

after applying the OTA-Update my device got into a bootloop.

- OP6
- OTA to version 10.3.0
- previous version unknown, but latest updates were applied
- Magisk was installed but without TWRP

After applying the OTA update and installing Magisk in the inactive slot via Magisk Manager, I got stuck in a bootloop. 

After that, I followed [these instructions](https://forum.xda-developers.com/oneplus-6/how-to/how-to-flash-twrp-magisk-android-10-t3988213). Flashing TWRP works, but after installing Magisk v20.1, the bootloop happens again.

So the last attempt was to flash the latest full OOS from [here](https://www.oneplus.com/de/support/softwareupgrade/details?code=PM1574156173727) to get out of the bootloop. That worked. Then, I flashed TWRP again and the device booted. Then, I tried to install Magisk v20.1 with the same result (boot loop). I even repeated the above steps and tried to install Magisk-v20.2-11b - no difference.

So currently, I can use my device but I don't have root anymore.

Any ideas would be appreciated!

KR
stilltldr

**Comment by topjohnwu** [comment]
OnePlus devices are always supported, please ask for help elsewhere
