### ISSUE TITLE
[Device Unsupported] Evervolv 7.1.2 on HP TouchPad

### ISSUE THREAD

**Issue by jkmartindale** [topjohnwu/Magisk#218]
Magisk will detect the boot image on mmcblk0p13 when flashed (not from within Magisk Manager), but will have an error while attempting to unpack it. I really don't know anything about this stuff so maybe I'm just doing something wrong. The log detects system root, which is weird because Evervolv doesn't ship with root. Evervolv recommends rooting with SuperSU 2.46, since I guess the later versions won't install because they're also systemless.
[Boot Image (boot.zip)](https://github.com/topjohnwu/Magisk/files/1030764/boot.zip)
```
- Mounting /system(ro), /cache, /data
! System installed root detected, mount rw :(
- Device platform: arm
- Constructing environment
- Creating /data/magisk.img
- Mounting /data/magisk.img to /magisk
- Found Boot Image: /dev/block/mmcblk0p13
- Unpacking boot image
! Unable to unpack boot image
Updater process ended with ERROR: 1
```

**Comment by TheComputerGuy96** [comment]
@jkmartindale Can you also post your recovery.log?

**Comment by jkmartindale** [comment]
Where do I find that?

**Comment by TheComputerGuy96** [comment]
@jkmartindale If you're using TWRP, then do this: http://rootzwiki.com/topic/24120-how-to-get-a-log-from-twrp/

**Comment by jkmartindale** [comment]
Alright, here we go.
[recovery.log.txt](https://github.com/topjohnwu/Magisk/files/1043013/recovery.log.txt)

**Comment by TheComputerGuy96** [comment]
@jkmartindale Can you try to flash Magisk v13.0 snapshot build?: https://forum.xda-developers.com/apps/magisk/unofficial-magisk-v10-beta-built-t3521901

**Comment by migube** [comment]
tried 13.0 with an older evervolv on TPad got Sony Elf32 formate detected, use Bootbridge from @AdrianDC

**Comment by jkmartindale** [comment]
@TheComputerGuy96 I flashed Magisk build 170612 on the 2017-06-20 Evervolv nightly. It asked me to use Bootbridge, so I swapped out the install.zip file inside Bootbridge using 7-Zip, flashed that, and received error 7.
[recovery.log.txt](https://github.com/topjohnwu/Magisk/files/1117425/recovery.log.txt)

**Comment by TheComputerGuy96** [comment]
@topjohnwu Some info: https://github.com/Evervolv/android_device_hp_tenderloin/blob/ng-7.0/makemulti.sh
