### ISSUE TITLE
Magisk Hide doesn't apply to packages not installed for user 0

### ISSUE THREAD

**Issue by dantmnf** [topjohnwu/Magisk#2181]
Think of package `com.example.package` only installed for user 10 (work profile), the following code can't detect them as `/data/user_de/0/com.example.package` doesn't exist.

https://github.com/topjohnwu/Magisk/blob/3beffd84d654342b5a68900d2677972f539ddfb0/native/jni/magiskhide/proc_monitor.cpp#L82

**Comment by dantmnf** [comment]
Possible solution at https://github.com/dantmnf/Magisk/commit/1f52a369e142b99c2de47e67bc025f54388709cf. Not tested yet.

**Comment by misterpyrrhuloxia** [comment]
@topjohnwu, does your having closed #2340 above mean that this is going to be fixed in the next Magisk release? If so, will it go to Magisk Beta first? If so, when might that be?

**Comment by osm0sis** [comment]
Looks like #1840 is still waiting to be merged to potentially fix this.

**Comment by MikeBishop** [comment]
Can I suggest putting "Enterprise" or "work" in the title of this issue so that people can find it using search?  That might reduce the frequency of duplicate issues being opened.

**Comment by adi90x** [comment]
Hey @topjohnwu , thanks for solving this issue, what is the recommended way to hide application in Work Profile now ?
Regards

**Comment by alexdoub** [comment]
@topjohnwu I would love an answer for this. I'm trying to keep root but my work profile is strictly blocking it. Basically what happens is...

Attempting to install work profile while rooted
1) Using magisk hide, I hide almost every app I can see, including the below management profile
2) I run workspace one intelligent hub (management software) on my user profile
3) It installs the work profile and many apps
4) It immediately detects root, deletes the work profile and all associated apps

I also tried de-rooting, installing the work profile then rerooting, but it results in me being locked out of my work profile. When I try to access any app in the work profile it prompts me for my password then crashes when I input it. It shows a dialog like 'settings keeps crashing'.

Any suggestions would be welcome...

**Comment by undertow25** [comment]
> @topjohnwu I would love an answer for this. I'm trying to keep root but my work profile is strictly blocking it. Basically what happens is...
> 
> Attempting to install work profile while rooted (note, safetynet passes & Im using the magisk manager hide option & magisk hide option on all the apps I can think of, especially the management profile)
> 
> 1. I run workspace one intelligent hub (management software) on my user profile
> 2. It installs the work profile and many apps
> 3. It immediately detects root, deletes the work profile and all associated apps
> 
> I also tried de-rooting, installing the work profile then rerooting, but it results in me being locked out of my work profile. When I try to access any app in the work profile it prompts me for my password then crashes when I input it. It shows a dialog like 'settings keeps crashing'.
> 
> Any suggestions would be welcome...

Did you find a solution for this? Having the same issue when trying set up Airwatch.

**Comment by alexdoub** [comment]
@undertow25 Afraid not. I think all it would take is somehow being able to pre-configure magisk for new user profiles before they are created. If we could have a script that does both 1) Enables magisk hide 2) Hides X app by package, then configure that script to immediately run on any new android user profile made, then that would solve this. Unfortunately I don't know enough about magisk dev to know if thats possible, but it seems doable.

**Comment by undertow25** [comment]
> @undertow25 Afraid not. I think all it would take is somehow being able to pre-configure magisk for new user profiles before they are created. If we could have a script that does both 1) Enables magisk hide 2) Hides X app by package, then configure that script to immediately run on any new android user profile made, then that would solve this. Unfortunately I don't know enough about magisk dev to know if thats possible, but it seems doable.
> 
> EDIT: Or a simplified solution -- Make it so magisk automatically copies the current MagiskHide settings for new users created on the same device.

That would be welcome. I definitely don't want to carry a second phone just to access the work emails.
I found a dirty workaround though. Start with magisk manager unhidden and when airwatch starts to create the work profile hide it. The repackaged app will be added to both the personal and work profiles. It works perfectly but you have to get the timing right.

**Comment by TheSunilVarma** [comment]
Any Solution yet ?.. @undertow25  can you explain bit more, if it still working for you. Steps ?

**Comment by adi90x** [comment]
Did you find any solution ? I was successful with Old magisk version but unable to install my work profil with latest magisk version

**Comment by undertow25** [comment]
Sorry can't really give more details, I've no idea what VMware hub is doing
in the background. But for sure, if you hide magisk manager just after it
starts to create the work profile, the renamed app will install under both
profiles with the existing magisk hide settings, masking root for VMware
hub. I managed it twice now, though the second time it took at least 20-30
attempts. Multiuser mode is user independent, not sure if that's important.

**Comment by adi90x** [comment]
Hello @topjohnwu ,
Any chance for you to have a look into this issue ? Still not possible to install a new profile without root being detected.
Regards,

**Comment by osm0sis** [comment]
Not something he'll be looking at: https://topjohnwu.medium.com/state-of-magisk-2021-fe29fdaee458
