### ISSUE TITLE
No modules load on Android 6.

### ISSUE THREAD

**Issue by martyfender** [topjohnwu/Magisk#2182]
No modules will load on the latest Canary on Android 6. It works fine on my Anxroid 9 device. Nextbook Ares 8A Android 6.0.1 x86.
Onn 8 Android 9.
[magisk_log_20191227_082308.log](https://github.com/topjohnwu/Magisk/files/4005422/magisk_log_20191227_082308.log)

Dec 12 or 13th commits appear to have caused this.
Thanks

**Comment by topjohnwu** [comment]
@martyfender your log shows that the daemon only starts with late start service, which should not happen. Please create a full boot logcat dump so I can see which step causes the crash

**Comment by martyfender** [comment]
Do you mean a logcat boot script, (if it will even run in these circumstances). 
I am at work  ut wkll when I have some time and at home, where that device is.

**Comment by martyfender** [comment]
I always have trouble running logcat at boot on this device. I tried: adb logcat -v long > name of problem.txt and got nothing. A bootscript.sh from didgeridoohan's help site in service.d did not run, as I expected it would not. 
I do know that the commits I mentioned caused the problem initially, because I used unofficial builds last week or when ever, when those were first committed. I, of course, do not report to you on those unofficial builds and wait for you to release a new Canary. 
how can I do a proper boot logcat since it appears to have problems doing that on my Nextbook Ares 8A's, Android 6 devices? I got waiting for device on Linux Mint Mate, just released, 19.3, after a full boot, even though If I entered the command: adb devices, it showed the device?
I always have issues with this on these 4 devices.
By the way, congratulations on completing your Masters degree in computer science. That is a great accomplishment! If computers had been more than punch card and COBOL and FORTRAN in the 1970's, I might have studied computer science, myself, at Indiana University.

**Comment by martyfender** [comment]
[logcat.txt](https://github.com/topjohnwu/Magisk/files/4006658/logcat.txt)

**Comment by martyfender** [comment]
topjohnwu, I want to point out that this is on a device where I use both selinux switch and a hacked version of Chanfires adb insecure, but this happens on all of my Nextbook Android 6 devices without these extras.
My new, Onn 8, Android 9 tablet, does not have this issue with the latest Canary.

Thank You for all of your work on this.

**Comment by topjohnwu** [comment]
@martyfender your logcat happens too late. To grab a boot logcat, run `adb logcat > log.txt` on your device before your device boots up

**Comment by martyfender** [comment]
[new file.txt](https://github.com/topjohnwu/Magisk/files/4006690/new.file.txt) 
I am not sure if this is any better, my devices, A 6, don't seem to start logcat, until they are almost booted to the login screen.

**Comment by martyfender** [comment]
The previous Canary worked fine on all of these 4 Android 6.0.1 Nextbooks.
https://github.com/topjohnwu/Magisk/commit/8c500709e492b9133e64bb5bed0f81b4d40a8622
https://github.com/topjohnwu/Magisk/commit/af060b313295ab7b0d23e9e816b97ed37ef03411
https://github.com/topjohnwu/Magisk/commit/12fda2928051601ebc7fac980fae29a80e7979cc
One of these commits caused the issue, because they all started when during when these were added to to the unofficial build. And I do not report on them, as  I don't want them taken down, like you did the others.

**Comment by topjohnwu** [comment]
@martyfender may you please upload both `magisk.log` and `magisk.log.bak`?

**Comment by topjohnwu** [comment]
I tried running Android 6.0 on my own Nexus 9, and I found nothing wrong

**Comment by martyfender** [comment]
I uploaded magisk.log already from todays build. unfortunately, magisk.log.bak is also from todays build. I do not remember how to revert to the previous build in the repository, I have read how to before, don't remember where.
Would it be here:
https://github.com/topjohnwu/magisk_files/tree/da34d45b111af268bc493a73d628e8510f74c258

**Comment by topjohnwu** [comment]
@martyfender use the latest build, your daemon crashed and relaunches, so `magisk.log.bak` actually happens before the crash happens. Just upload both files while running the build you have issues with

**Comment by martyfender** [comment]
[magisk.log](https://github.com/topjohnwu/Magisk/files/4006750/magisk.log)

**Comment by martyfender** [comment]
[magisk.log.bak.log](https://github.com/topjohnwu/Magisk/files/4006752/magisk.log.bak.log)

**Comment by martyfender** [comment]
Github doesn't support. Bak so I added. Log to it.

**Comment by martyfender** [comment]
It is almost the same?

**Comment by martyfender** [comment]
Ian didn't have issues on his devices as well.
It happened on 3 of my Android 6 devices, but not my Android 9 devices. 
I thought about running the magisk uninstaller on one of the devices and starting from scratch, but reflashing the older build always solves the issues, so I have not done it.

**Comment by martyfender** [comment]
Attached is the magisk.log after I flashed the previous Canary debug build.
thanks
[magisk_log_20191228_085823.log](https://github.com/topjohnwu/Magisk/files/4007079/magisk_log_20191228_085823.log)

**Comment by martyfender** [comment]
Here is a new logcat from the current Canary release. I there anything else I can do like complete uninstall flash, factory reset, flash stock boot.img to help with troubleshoot this?
[log.txt](https://github.com/topjohnwu/Magisk/files/4008388/log.txt)


Thanks

**Comment by martyfender** [comment]
Attached is the magisk.log after I flashed the previous Canary debug build.
thanks
[Uploading magisk_log_20191228_085823.log…]()
[magisk_log_20191229_130259.log](https://github.com/topjohnwu/Magisk/files/4008393/magisk_log_20191229_130259.log)
[bootlog.log](https://github.com/topjohnwu/Magisk/files/4008394/bootlog.log)
[magisk.log.bak.log](https://github.com/topjohnwu/Magisk/files/4008397/magisk.log.bak.log)

**Comment by topjohnwu** [comment]
I know it is not your fault, but without logs when the crash happens, I can never know what causes it. I will close this issue since there is no way I can fix it.

**Comment by topjohnwu** [comment]
@martyfender I'll triage this issue later in the future

**Comment by martyfender** [comment]
Thanks

**Comment by martyfender** [comment]
I installed the latest Canary debug on one of my other Nextbook Ares 8A, Android 6.0.1 tablets. attached is a logcat from it. I don't know if is is of any use, or not.
[log.txt](https://github.com/topjohnwu/Magisk/files/4017357/log.txt)

**Comment by youling257** [comment]
same problem, not mount mirror system and data, not load modules.
01-03 19:04:42.413     0     0 W magiskinit: Mount /sbin tmpfs overlay

01-03 19:04:53.051  1416  1416 I Magisk  : Magisk v20.2(20200) daemon started
01-03 19:04:53.051  1416  1416 I Magisk  : * Device API level: 25
01-03 19:04:53.059  1416  1418 I Magisk  : ** late_start service mode running

**Comment by youling257** [comment]
I git reset --hard many commit, build and test boot.
final, reset --hard 4bb8ad19cf0890238ecf3e8ffa244da3a5230776, build magiskinit and test boot no problem, modules loaded.
reset --hard d22b9c26b66c0ecea53abdc4729f1014982427b3, modules not loaded.

https://github.com/topjohnwu/Magisk/commit/d22b9c26b66c0ecea53abdc4729f1014982427b3 is bad!

**Comment by youling257** [comment]
@martyfender please you test my build.
https://drive.google.com/open?id=1vl9tM-MaVgzdhAmZW6L08VXRVpYnT21T

**Comment by martyfender** [comment]
I will tonight.

**Comment by youling257** [comment]
my build is master branch revert d22b9c2.

**Comment by martyfender** [comment]
Will you be doing a pull request?

Thanks

**Comment by youling257** [comment]
topjohnwu can do it.

**Comment by martyfender** [comment]
I now have your build on 3 devices and it is working well on all of them.

**Comment by topjohnwu** [comment]
@martyfender if that is the culprit, it means that your kernel does not support `MS_MOVE` option to move mount points. I'll see what I can do

**Comment by youling257** [comment]
@topjohnwu  what it do mount --move ?
may be mount move failed on my userspace.

**Comment by martyfender** [comment]
I have 3.14.64-x86_64 (warroir@warroir-11)(gcc version 4.9.2(GCC)) #1 SMP PREMPT Yhu Feb 16 21:25:00 EST 2017 release keys. All I know is that Magisk has never had this problem since I have been using it since 15.0.
By the way, I saw your twitter feed and burnout on such a project as this is enviable. 
Sometime one needs to do other things for a while to refresh. 
I will miss it if there are no commits for a while, but I you do have to evaluate what is important to you at this point in your life, considering you have Graduated and, I assume are looking at your possible careers for the future.
Thanks

**Comment by martyfender** [comment]
Why would a company developing not put this in the kernel? This is a cheap, Chinese tablet, made by yfang. I am sorry, I know you are from Taiwan, but I am suspcious when I see info such as this. 
Are they just stupid in not including this in the kernel?

**Comment by topjohnwu** [comment]
I have seen some very old devices that mount move won't work in some situations. All modern devices supports it fine (and in fact, it is critical for booting Android 10). I was just being a bit less careful and forgot about this when refactoring code to support persist mounting pre-init

**Comment by youling257** [comment]
My Androidx86 7.1.2 run on Linux mainline kernel.
5.5.0-rc4-android-x86_64+ (gcc version 9.2.1 20191130 (Ubuntu 9.2.1-22ubuntu1))root@localhost #1Mon Dec 30 11:31:09 CST 2019
cm_android_x86-userdebug 7.1.2 NJH47F 939dd5481a test-keys, security patch 2019-09-05
mount move no problem.
what do you want to say commit d22b9c2.

**Comment by youling257** [comment]
test magisk release 20.2 on my kernel 5.5 Androidx86 9.0
magisk release 20.2 not work!
01-06 03:58:39.353     0     0 W init    : wait for '/dev/.magisk_unblock' timed out and took 10009ms
01-06 03:58:39.370     0     0 I init    : Command 'wait /dev/.magisk_unblock 10' action=post-fs-data (/init.rc:782) took 10026ms and failed: wait_for_file() failed
01-06 03:58:40.255  1436  1436 I Magisk  : Magisk v20.2(20200) daemon started
01-06 03:58:40.256  1436  1436 I Magisk  : * Device API level: 28
01-06 03:58:40.264  1436  1438 I Magisk  : ** late_start service mode running

my build revert d22b9c2 magiskinit worked on my Androidx86 9.0.
01-06 04:22:08.681     0     0 W magiskinit: Mount /sbin tmpfs overlay
01-06 04:22:08.987  1347  1347 I Magisk  : Magisk v20.2(20200) daemon started
01-06 04:22:08.988  1347  1347 I Magisk  : * Device API level: 28
01-06 04:22:08.999  1347  1348 D Magisk  : resetprop: getprop [ro.crypto.state]: [unsupported]
01-06 04:22:08.999  1347  1348 D Magisk  : resetprop: getprop [init.svc.vold]: [running]
01-06 04:22:09.051  1347  1348 I Magisk  : ** post-fs-data mode running
01-06 04:22:09.052  1347  1348 I Magisk  : * Initializing Magisk environment
01-06 04:22:09.081  1347  1348 I Magisk  : * Mounting mirrors
01-06 04:22:09.081  1347  1348 I Magisk  : mount: /sbin/.magisk/mirror/system <- /sbin/.magisk/block/system

**Comment by topjohnwu** [comment]
@martyfender may you please test out this Magisk build whether it fixes your issue?
[magisk-debug.zip](https://github.com/topjohnwu/Magisk/files/4027513/magisk-debug.zip)

**Comment by youling257** [comment]
01-07 04:06:41.496 0 0 W magiskinit: Mount /sbin tmpfs overlay
01-07 04:06:41.685 0 0 I magisk[1337]: segfault at ffdb20d8 ip
000000000807f868 sp 00000000ffda7f40 error 6 in magisk
(deleted)[8048000+92000]
01-07 04:06:52.363 1446 1446 I Magisk : Magisk v20.3-242e64d7(20202) daemon
started
01-07 04:06:52.363 1446 1446 I Magisk : * Device API level: 25
01-07 04:06:52.370 1446 1447 I Magisk : ** late_start service mode running

**Comment by topjohnwu** [comment]
@youling257 do you have the full logs? I would love to know where the segfault happens to narrow down the specific portion of code that causes the crash.

**Comment by martyfender** [comment]
It will be many hours before I am off work. I only have my new, Onn, Android 9 tablet with me at work.
What was changed in this build?

**Comment by youling257** [comment]
01-07 04:17:43.464     0     0 I magisk[1336]: segfault at ffb714f8 ip 000000000807f868 sp 00000000ffb67360 error 6 in magisk (deleted)[8048000+92000]
01-07 04:17:43.471     0     0 I Code    : 5d c3 55 89 e5 57 56 83 e4 f0 89 d6 8b 7d 08 83 ec 0c ff 75 0c 57 52 51 68 31 01 00 00 e8 28 0b 00 00 83 c4 20 83 f8 ff 74 06 <c6> 04 07 00 eb 23 e8 3d 61 01 00 8b 38 83 ec 0c 57 e8 a2 51 01 00
[log.txt](https://github.com/topjohnwu/Magisk/files/4028323/log.txt)

**Comment by martyfender** [comment]
I just tested your latest build youling257 on one of my Nextbook Ares 8A, Android 6 devices and it has the same issue with modules not loading and mirrors not mounting, just the same as before.
I installed it on my Onn 8, Android 9 tablet and it appears to be fine.

**Comment by topjohnwu** [comment]
@youling257 your ROM has supersu, please stop reporting issues if you have conflicting software....

**Comment by youling257** [comment]
@topjohnwu 
new log.txt，17:41 boot with your build no the supersu, remove supersu no the magisk segfault at, but not lunch magisk daemon.17:44 boot with my build has the supersu.
supersu not problem, I had been used supersu and magisk two years, on init launch supersu, on post-fs-data launch magisk, nougat-x86 oreo-x86 pie-x86 no problem.
on q-x86, have to on init or post-fs launch magisk, on post-fs-data launch supersu.

@martyfender what is mean of you " tested your latest build youling257" ? 
the two days build magisk-debug.zip by topjohnwu, did you test it ?
[log.txt](https://github.com/topjohnwu/Magisk/files/4034673/log.txt)

**Comment by martyfender** [comment]
Yes, it was topjohnwu build I tested. I thought it was your new build until I just looked back at the post again. that build had the same issues topjohnwu.

**Comment by topjohnwu** [comment]
@martyfender please try this build, thx
[magisk-debug.zip](https://github.com/topjohnwu/Magisk/files/4036002/magisk-debug.zip)

**Comment by martyfender** [comment]
In a few hours I will. Do you wa t magisk.logs?

**Comment by martyfender** [comment]
I just installed the latest build above and it has the same problem of no modules installed, etc.
Nextbook Ares 8A, Intel x86, Android 6.0.1 tablet.

Thanks

**Comment by martyfender** [comment]
Yes, I tried it, as I stated previously, on 3 of my Nextbook Ares 8A tablets, with Android 6.

**Comment by topjohnwu** [comment]
@martyfender 3rd take, please try it out, thx :)
[magisk-debug.zip](https://github.com/topjohnwu/Magisk/files/4039203/magisk-debug.zip)

**Comment by youling257** [comment]
test it daemon can launch, modules can load.
wait for you push the patch commit.

**Comment by martyfender** [comment]
No, that build has the same issue.

**Comment by martyfender** [comment]
Retested this to confirm that is still works:

https://drive.google.com/open?id=1vl9tM-MaVgzdhAmZW6L08VXRVpYnT21T

**Comment by topjohnwu** [comment]
@martyfender so it means your issue is not the same as @youling257.
I can only fix an issue with corresponding logs, and @youling257 provide enough info for me to fix it.

**Comment by martyfender** [comment]
But I did provide logs?

**Comment by youling257** [comment]
@martyfender i have two build let you test, need you report.
https://drive.google.com/drive/folders/1aZ_bBUCZnISutUSIPB0dsDIOi4wsJBIL?usp=sharing

**Comment by martyfender** [comment]
The master does not load modules or mount mirrors, but the revert does. Do you need magisk.log and adb logcat -v long > log.txt?

**Comment by youling257** [comment]
two different log, master version log and revert version log.

martyfender <notifications@github.com> 于 2020年1月10日周五 上午2:21写道：

**Comment by martyfender** [comment]
[revertlog.txt](https://github.com/topjohnwu/Magisk/files/4041918/revertlog.txt)

**Comment by martyfender** [comment]
These are from the master:


[MASTERLOG.LOG](https://github.com/topjohnwu/Magisk/files/4041980/MASTERLOG.LOG)

**Comment by BilliTheKid** [comment]
Latest Canary Build 20.4 is showing a black screen in modules. Unable to see them. Pixel 2 XL running Android 10 January security update. All was fine until this update.

**Comment by youling257** [comment]
magisk daemon can launch on my userspace with the master build, but sbin some file link error.
my rever build sbin some file link not error.
https://github.com/topjohnwu/Magisk/issues/2247

@martyfender 
may be your sbin some file link error with master build.
can you provide your ls -al /sbin result?

**Comment by martyfender** [comment]
u0_a116@NX16A8116K:/ $ su
root@NX16A8116K:(unreachable) # ls -al /sbin
drwxr-xr-x root     root              2020-01-11 20:53 .magisk
lrwxrwxrwx root     root              2020-01-11 20:53 adbd -> /root/adbd
lrwxrwxrwx root     root              2020-01-11 20:53 healthd -> /root/healthd
-rwxr-xr-x root     root       300940 2020-01-11 20:53 magisk
lrwxrwxrwx root     root              2020-01-11 20:53 magiskhide -> ./magisk
-rwxr-xr-x root     root       601248 2020-01-11 20:53 magiskinit
lrwxrwxrwx root     root              2020-01-11 20:53 magiskpolicy -> ./magiskinit
lrwxrwxrwx root     root              2020-01-11 20:53 resetprop -> ./magisk
lrwxrwxrwx root     root              2020-01-11 20:53 slideshow -> /root/slideshow
lrwxrwxrwx root     root              2020-01-11 20:53 su -> ./magisk
lrwxrwxrwx root     root              2020-01-11 20:53 supolicy -> ./magiskinit
root@NX16A8116K:(unreachable) #

**Comment by youling257** [comment]
is it my revert build result?
what about the master build?


martyfender <notifications@github.com> 于 2020年1月12日周日 上午10:09写道：

**Comment by martyfender** [comment]
That is from the master because that is what you asked for.

**Comment by youling257** [comment]
compare master build and revert build /sbin file.

**Comment by martyfender** [comment]
From the revert:

/ $ su
 # ls -al /sbin
lrwxrwxrwx root     root              2020-01-12 10:17 .core -> ./.magisk
drwxr-xr-x root     root              2020-01-12 10:17 .magisk
lrwxrwxrwx root     root              2020-01-12 10:17 adbd -> /root/adbd
lrwxrwxrwx root     root              2020-01-12 10:17 healthd -> /root/healthd
-rwxr-xr-x root     root       300940 2020-01-12 10:17 magisk
lrwxrwxrwx root     root              2020-01-12 10:17 magiskhide -> ./magisk
-rwxr-xr-x root     root       601248 2020-01-12 10:17 magiskinit
lrwxrwxrwx root     root              2020-01-12 10:17 magiskpolicy -> ./magiskinit
lrwxrwxrwx root     root              2020-01-12 10:17 resetprop -> ./magisk
lrwxrwxrwx root     root              2020-01-12 10:17 slideshow -> /root/slideshow
lrwxrwxrwx root     root              2020-01-12 10:17 su -> ./magisk
lrwxrwxrwx root     root              2020-01-12 10:17 supolicy -> ./magiskinit
lrwxrwxrwx root     root              2020-01-12 10:17 ueventd -> /root/ueventd
lrwxrwxrwx root     root              2020-01-12 10:17 watchdogd -> /root/watchdogd
 #

**Comment by youling257** [comment]
@martyfender my shared folder update, a new build need you help to test, and ls -al sbin file list.
https://drive.google.com/drive/folders/1aZ_bBUCZnISutUSIPB0dsDIOi4wsJBIL?usp=sharing

**Comment by martyfender** [comment]
Yes, I will test, but I would appreciate if you give me some feedback about my output this time, instead of leaving me blind, hanging. I do not understand this.

Thanks

**Comment by martyfender** [comment]
He is your latest builds output. Modules and mirrors do not mount, same as others. Please give some feedback as to what you are trying.
u0_a116@NX16A8116K:/ $ su
root@NX16A8116K:(unreachable) # ls -al sbin
drwxr-xr-x root     root              2020-01-15 21:31 .magisk
lrwxrwxrwx root     root              2020-01-15 21:31 adbd -> /root/adbd
lrwxrwxrwx root     root              2020-01-15 21:31 healthd -> /root/healthd
-rwxr-xr-x root     root       300940 2020-01-15 21:31 magisk
lrwxrwxrwx root     root              2020-01-15 21:31 magiskhide -> ./magisk
-rwxr-xr-x root     root       601248 2020-01-15 21:31 magiskinit
lrwxrwxrwx root     root              2020-01-15 21:31 magiskpolicy -> ./magiskinit
lrwxrwxrwx root     root              2020-01-15 21:31 resetprop -> ./magisk
lrwxrwxrwx root     root              2020-01-15 21:31 slideshow -> /root/slideshow
lrwxrwxrwx root     root              2020-01-15 21:31 su -> ./magisk
lrwxrwxrwx root     root              2020-01-15 21:31 supolicy -> ./magiskinit
root@NX16A8116K:(unreachable) #

**Comment by martyfender** [comment]
?

**Comment by martyfender** [comment]
Solve with #2386 
Thanks
