### ISSUE TITLE
an help

### ISSUE THREAD

**Issue by DoctorSubtilis** [topjohnwu/Magisk#2188]
This is the first time I try to root my android smartphone (I have already "rooted", so to say, my tablet with kingroot, but I'm not suer of the result...), an Asus Zenfone 2 (Z00ED) with Android 6.
I have downloaded from [this site](https://github.com/sabpprook/android_device_asus_ze500kl/releases) two img, whose name are:  

* stock_recovery_Z00ED_WW_Phone_13.10.7.1.img (32 mb)
* twrp-3.0.2-0-ze500kl.img (15 mb) 

Installed Magisk Maneger and patched two img:  

* the first (frm stock_recovery_Z00ED_WW_Phone_13.10.7.1.img) is now about 11mb  
* the second twrp-3.0.2-0-ze500kl.img is still about 15 mb.

Which of them I should flash?  
And how? I have Linux (KDE Neon) and adb working. 
Mainly: There is a risk to make the smartphone unusable?  

Thank you

**Comment by Didgeridoohan** [comment]
Neither... The Github issues are not for general support, but got bug reporting.

Please close this issue and ask for help on XDA instead.
https://forum.xda-developers.com/apps/magisk

You might want to take a closer look at the installation instructions first though:
https://topjohnwu.github.io/Magisk/install.html

**Comment by DoctorSubtilis** [comment]
OK. Thanks.
