### ISSUE TITLE
[UI] Displays 'Install' even if the Magisk & Magisk manager are latest & already installed. 

### ISSUE THREAD

**Issue by whyorean** [topjohnwu/Magisk#2193]
Hey @topjohnwu , thanks for Magisk & your contributions to the community.

I noticed this weird behaviour where the app displays to install magisk and manager even if its latest & installed, pardon me if its intentionally done this way.

In case its not intentional, I think showing something as `Check` instead of `Install` would be more appropriate.

Magisk : 20.2-7fa2625a
Manager : 7.4.1-7fa2625a

Pattern is similar for stable & beta channel too, currently I'm on Canary.

![IMG_20191231_110553](https://user-images.githubusercontent.com/21051221/71611265-8ba6d000-2bbd-11ea-8fd4-217aaace0be1.jpg)

**Comment by topjohnwu** [comment]
It is intentional, it is made to re-install Magisk in case something is wrong with your setup

**Comment by yakov116** [comment]
@topjohnwu so may it should say Re-Install
