### ISSUE TITLE
How to hide the Magisk by Frida

### ISSUE THREAD

**Issue by williamleecn** [topjohnwu/Magisk#2194]
I modify the Frida that run on root user can unmount all Magisk created mounts ,but all of application can't access Magisk created mounts ,that can't use the cmd "su". How to unmount some app's mounts olny?

照着Magisk Hide的代码,已经修改Frida可以umount所有Magisk加载的分区,但现在全部软件都无法再访问Magisk加载的分区及相关的程序,请问如何实现umount后,其他软件不受影响?

**Comment by topjohnwu** [comment]
Check out mount namespace documentations. Hiding stuff is complicated, I would suggest you directly check the source code.

**Comment by williamleecn** [comment]
i open remote process mnt :  `open /proc/%d/ns/mnt => fd` , then   `setns (fd,0)` , then unmount
