### ISSUE TITLE
Magisk not granting root to some apps

### ISSUE THREAD

**Issue by Paget96** [topjohnwu/Magisk#2196]
Sometimes root cannot be granted to some apps, also one more thing I saw, when I go to the the superuser section and remove the app, I cannot grant root again, i have to reboot the device and do it again.

All i have in the log is this:
12-20 08:40:44.547   638   638 I Magisk  : Magisk v20.1(20100) daemon started
.
.
.
01-02 05:41:44.943   638  8960 W Magisk  : su: request rejected (10233)

Tried performing a logcat doesn't help.
Since it also happens in my application, I have tried running full debug version, app asks for root and after a while it get denied.

Tried to patch boot image again and to re-do the all possible cases to spot something, every time is the same.

**Comment by topjohnwu** [comment]
Please use canary debug builds before reporting

**Comment by martyfender** [comment]
More specifically, the Canary debug build.

**Comment by Paget96** [comment]
> More specifically, the Canary debug build.

I'm on the latest canary build at the moment, no issues for now. Tried the same process above to reproduce it, works fine for now.
