### ISSUE TITLE
no img in magisk.zip

### ISSUE THREAD

**Issue by cxbignekoc** [topjohnwu/Magisk#2197]
nexus 7 2013 wifi
win 7 professional
- twrp
- TWRP for Asus Nexus 7 2013 Wi-Fi (code:flo)

installing magisk 20.2 (20200) via magisk manager 7.5.0 (265) .
Manager ask me for installing magisk 20.2.

When choosing install i can choose for a File or download the zip.

Zip is already downloaded, so i choose the file.

I choose magisk20.2.zip and later try to rename it into *.img because zip not work

Error:
- Device Platform armeabi-v7a
- copying image to cache
- unpacking boot image
! unsupported/unknown image format
! installation fail

*security option installing from unknow source is deactivated

**Comment by Didgeridoohan** [comment]
This is not the place for this... There's nothing wrong, you just haven't figured out how things work.

To make things easy, just flash the downloaded Magisk zip (don't rename it) in TWRP. Done.

Please close this issue, so John don't have to.
