### ISSUE TITLE
Magisk not installed

### ISSUE THREAD

**Issue by HafizZiq** [topjohnwu/Magisk#2198]
Got magisk not installed after clean flash from 20.1
20.1 uninstaller>20.2>kernel>reboot
Android 7.1
Note 8
![IMG_20200102_215339_346](https://user-images.githubusercontent.com/46204743/71670571-3cbe8d80-2dab-11ea-932c-012a3be5eb70.jpg)

**Comment by nutpantz** [comment]
Same issue Canadian Galaxy s7 edge on Oreo the Galaxy project rom with superkernel.
Tired direct install, from recovery, clean flash of kernel then magisk again. Went back to 20.1. no errors were visible at any time during flash.

**Comment by MadDucks** [comment]
I'm seeing the same issue on my Pixel XL.   If I adb into the device, and issue a su -, I get the SU manager, but in the magisk manager, it says it's not installed.

**Comment by Freeglobe** [comment]
for me the same, 
galaxy S7 Galaxy Project with Superkernel: magisk 20.2 will not installed, i have try direct install from 20.1 and uninstall and clean install from TWRP, but 20.2 will not work, flash back in TWRP with 20.1 it works well, no problem!

**Comment by wimg** [comment]
Same issue on Galaxy S7 with Superman ROM

**Comment by jannikac** [comment]
Same Issue on ALEXNDR.G930FXXU3ERJE with Moro Kernel. Only 20.1 works.

**Comment by dbooty99** [comment]
Add me to the list! S7 with superman rom.

**Comment by nutpantz** [comment]
Fixed for my s7 in 20.3

**Comment by wimg** [comment]
I can confirm it works fine for my S7 as well.

**Comment by ViRb3** [comment]
OnePlus 5T, LineageOS 16 (Android 9). Tried Magisk 20.2 and 20.3 - Magisk works propely for a brief period right after boot, but in 1-2 minutes it will say "Magisk not installed" and there is no root access until another reboot. I tried uninstalling and clean installing with no modules, but nothing seems to help. Rolled back to 20.1, everything is working smoothly. If there's any way I can help debug this please let me know.

**Comment by ViRb3** [comment]
Do any of you have Greenify installed? It was causing "Magisk not installed" for me on Magisk v20.1-v20.4 (canary).

**Comment by crystalcoma** [comment]
I am having the same issue on Moto G7 Power
Flashed A/B ASOP 10 GSI Image. It has a native SU build in. I deleted the /Vendor Su file as well.
Magisk Manager won't patch the Image and flashing the zip didn't work either. I tried Stable and Beta Magisk 20.1-3
