### ISSUE TITLE
Mobile rebooting automatically

### ISSUE THREAD

**Issue by VarunSaiTeja** [topjohnwu/Magisk#2200]
I am using Samsung M30s
November 2019 Security Patch
Mobile rebooting automatically after few seconds (if booted with magisk system)

Installed magisk_patched.tar via odin as per instructions mentioned in below link 
https://topjohnwu.github.io/Magisk/install.html#magisk-in-recovery

**Comment by VarunSaiTeja** [comment]
Attatched Log File
[log.txt](https://github.com/topjohnwu/Magisk/files/4017972/log.txt)

**Comment by reisub0** [comment]
Same phone Model number: SM-M307F. Magisk version: 20.1
I've encountered random reboots and sometimes full blown bootloops whenever I use Magisk on this phone.

The cause appears to be a kernel panic logged in the `kmsg` by the android.bg thread. I don't really know much about lower-level details of Android but I'm reasonably familiar with Linux and am willing to spend time and effort debugging this, if you point me to the right direction and/or resources.

[Here's the output of `cat /proc/last_kmsg` on one of the few times I got into the system](https://github.com/topjohnwu/Magisk/files/4051565/lastkmsg.log)

**Comment by VarunSaiTeja** [comment]
> Same phone Model number: SM-M307F. Magisk version: 20.1
> I've encountered random reboots and sometimes full blown bootloops whenever I use Magisk on this phone.
> 
> The cause appears to be a kernel panic logged in the `kmsg` by the android.bg thread. I don't really know much about lower-level details of Android but I'm reasonably familiar with Linux and am willing to spend time and effort debugging this, if you point me to the right direction and/or resources.
> 
> [Here's the output of `cat /proc/last_kmsg` on one of the few times I got into the system](https://github.com/topjohnwu/Magisk/files/4051565/lastkmsg.log)

Issue Fixed Now
Problem in our M30s Kernal
https://forum.xda-developers.com/galaxy-m30s/development/unofficial-twrp-3-3-1-0-galaxy-m30s-t4035019
Flash twrp from here, it also updates kernal image

Issue fixed now
