### ISSUE TITLE
SIM card "No service" in Magisk 20.2

### ISSUE THREAD

**Issue by alissonlauffer** [topjohnwu/Magisk#2201]
After updating Magisk from 20.1 to 20.2, my SIM card is not working anymore. But if I uninstall Magisk, my SIM card works again.
I also tested with a clean install of the 20.2. Again the same issue.

Device information:
Model: Moto G5S Plus
ROM: POSP (Android 10, non-GSI)

**Comment by martyfender** [comment]
Please report issues using the Canary debug build only, with logs, here on github.

**Comment by alissonlauffer** [comment]
Okay. I got the same issue with canary debug builds. logcat below:

[boot.log](https://github.com/topjohnwu/Magisk/files/4017448/boot.log)

**Comment by imaadhrizni** [comment]
Same issue on v20.2 and on Canary build.

Device information:
Model: One Plus 6T Global
ROM: OOS 10.3

**Comment by MetaColon** [comment]
Why was this closed? I have the same issue in 21.4

**Comment by MetaColon** [comment]
@topjohnwu I still have this problem with the latest Canary build (fb8000b5 (22104)).

**Comment by Deeka0** [comment]
I've been away from rooting for a while and surprisingly with the latest release (Magisk v23.0), i'm facing this issue. Was this resolved earlier in any kind of way?

I have a Tecno Spark 4 air (KC6) running pie stock rom.

**Comment by MetaColon** [comment]
@Deeka0 no it wasn't, though I have a feeling that BusyBox might be involved

**Comment by alidavoodi2680** [comment]
Sehttps://github.com/topjohnwu/Magisk/issues/2201#issuecomment-894697322nt from Nine
________________________________

**Comment by MetaColon** [comment]
@Deeka0 wiping the cache (via Recovery) seems to be a pretty reliable solution. It's still super annoying of course, as it has to be done after essentially every reboot.

**Comment by djerius** [comment]
I'm seeing this on Magisk 26.1, One Plus 5T, Oxygen OS 10.0.1.

If I flash the modified boot.img, no SIM; reflashing the original returns service.

Clearing Cache in TWRP didn't fix this for me.

I don't have a useful "previously working" setup to compare with, as I upgraded Magisk after updating the device from OxygenOS 9 to 10.

**Comment by djerius** [comment]
> I'm seeing this on Magisk 26.1, One Plus 5T, Oxygen OS 10.0.1.

I had done an OTA full upgrade from Oxygen OS 9.x. 

To see if accumulated cruft was causing the issue. I performed a factory reset of 10.0.1.,  installed Magisk, and flashed the modified boot.img.  Everything now works.

**Comment by taizenska** [comment]
pls dm in tg @taizenska
need devloper
