### ISSUE TITLE
[Function Suggestion] Can the module support multiple users?【功能建議】模塊是否可以支持多用戶？

### ISSUE THREAD

**Issue by 2220209876** [topjohnwu/Magisk#2204]
Multi-user can be used in ROOT mode, can multi-user function be added in module mode?
The current module enable status is the same as that of the master user, and the module functions can also be used normally by other users.
ROOT模式可以用多用戶，模塊模式是否也可以加入多用戶功能呢？
現在的模塊啟用狀態是和主用戶啟用狀態一致的，模塊功能也能在其它用戶正常使用。

**Comment by topjohnwu** [comment]
很抱歉，但是要實作這個非常複雜，而且 Magisk Module 是拿來更改系統檔案，是沒有辦法區分用戶的

**Comment by 2220209876** [comment]
> 很抱歉，但是要實作這個非常複雜，而且 Magisk Module 是拿來更改系統檔案，是沒有辦法區分用戶的

在其它用戶裡加一個模塊開關名單呢？
模塊在主用戶里安裝，其它用戶可以關閉某一個模塊。
