### ISSUE TITLE
Support for Huawei patches

### ISSUE THREAD

**Issue by Mexit** [topjohnwu/Magisk#2206]
Huawei P10 Plus update file:
http://update.dbankcdn.com/TDS/data/files/p3/s15/G4105/g1755/v346738/f1/full/filelist.xml

After patch installation (with clean RECOVERY_RAMDISK), and Magisk install patch is not detected.

We need to mount partition with adb:
`mount -r -t ext4 -o seclabel,nosuid,nodev,noexec,noatime,nodiratime,data=ordered /dev/block/sdd58 /patch_hw`

Can Magisk do it automatically?

**Comment by topjohnwu** [comment]
I think you didn't understand how recovery mode works, please read official instructions
