### ISSUE TITLE
Google Pixel 3 - Android 10 all downloads os Magisk Manager 20.2 failed

### ISSUE THREAD

**Issue by ovz93br43v7** [topjohnwu/Magisk#2207]
I downloaded magisk manager from the Github page and also compared the signature before using it. My device is a Google Pixel 3 with the latest Android 10 (December Update) and Magisk Manager 20.2. 
After installation I granted all permissions and selected install, patch boot.img. The download of Magisk.zip failed everytime. All other apps can access internet without problems. I don't installed any other app after factory reset, so no other app could prevent internet access. 

I also tired already restart, deinstallation and new installation of magisk manager and factory reset  But my magisk manager is not able to download and patch my boot.img.

Any idea what is wrong?!?

**Comment by topjohnwu** [comment]
I have no idea if you don't provide any logs. Also, Pixel is always supported first party.

**Comment by ovz93br43v7** [comment]
Sorry for that. Attached a logcat printout.

[log_Pixel3_magisk_manager_failed_download.txt](https://github.com/topjohnwu/Magisk/files/4021872/log_Pixel3_magisk_manager_failed_download.txt)
