### ISSUE TITLE
Magisk manager always crashing when i flash new update of any module

### ISSUE THREAD

**Issue by HafizZiq** [topjohnwu/Magisk#2208]
Here the log
https://del.dog/pepebifepy

**Comment by beeshyams** [comment]
Did you update to the latest Magisk Manager released yesterday? It specifically says old versions will not work

**Comment by HafizZiq** [comment]
> Did you update to the latest Magisk Manager released yesterday? It specifically says old versions will not work
Everything on latest state..

![Screenshot_20200104-221628](https://user-images.githubusercontent.com/46204743/71766875-e33b9780-2f3f-11ea-9850-817a52cb137d.jpg)

**Comment by topjohnwu** [comment]
Sorry, but this is not reproducible on any other device
