### ISSUE TITLE
TV Banner Magisk Manager APK Icon Editor

### ISSUE THREAD

**Issue by bubuleur** [topjohnwu/Magisk#2209]
Hello
I come to you to find out if you can create a shortcut for Android TV
Attached logo
![banner_custom](https://user-images.githubusercontent.com/21688137/71755311-466af280-2e8a-11ea-8ec6-dd0314e46372.png)
With the Magisk Manager v7.3.4 version I could add a shortcut using Apk Icon Editor to put on my nvidia shield tv but on your new update I can no longer do it 
Why ?
You blocked something so I couldn't do it anymore?
Thanking you

**Comment by alexa-v2** [comment]
The newer apps are obfuscated by the way, hence why it can no longer read them

**Comment by bubuleur** [comment]
How i don't understand ?

**Comment by bubuleur** [comment]
up please

**Comment by topjohnwu** [comment]
#2027
