### ISSUE TITLE
Magiskhide not work

### ISSUE THREAD

**Issue by ImpGL** [topjohnwu/Magisk#221]
u0_a376@kingdom_row:/ $ su
root@kingdom_row:/ # sh /magisk/.core/magiskhide/enable
MagiskHide: Moving and re-linking /sbin binaries
chcon:  Could not label u:object_r:system_file:s0 with -h:  No such file or directory
MagiskHide: Removing dangerous read-only system props
MagiskHide: Killing com.google.android.gms.unstable
MagiskHide: Starting MagiskHide daemon
root@kingdom_row:/ #

Android 5.0.2.

** Magisk post-fs mode running...
** Magisk post-fs-data mode running...
* Running post-fs-data.d
* Loading core props
* Preparing modules
* Stage 1: Mount system and vendor mirrors
* Stage 2: Mount dummy skeletons
* Stage 3: Mount module items
* Stage 4: Execute module scripts
post-fs-data: /magisk/xposed/post-fs-data.sh
Xposed: Mount: /magisk/xposed/system/lib/libsigchain.so
Xposed: Mount: /magisk/xposed/system/lib/libart.so
Xposed: Mount: /magisk/xposed/system/lib/libart-disassembler.so
Xposed: Mount: /magisk/xposed/system/lib/libart-compiler.so
Xposed: Mount: /magisk/xposed/system/bin/patchoat
Xposed: Mount: /magisk/xposed/system/bin/oatdump
Xposed: Mount: /magisk/xposed/system/bin/dex2oat
Xposed: Mount: /magisk/xposed/system/bin/app_process32
* Stage 5: Mount mirrored items back to dummy
** Magisk late_start service mode running...
* Enabling systemless hosts file support
* Enabling BusyBox
* Linking binaries to /sbin
* Starting MagiskSU
* Running service.d
service.d: /magisk/.core/service.d/radio_magisksu.sh
MagiskHide: Moving and re-linking /sbin binaries
MagiskHide: Removing dangerous read-only system props
MagiskHide: Killing com.google.android.gms.unstable
MagiskHide: Starting MagiskHide daemon
MagiskHide: Update process/package list:
MagiskHide: [com.google.android.gms.unstable]
Zygote(0) ns=L 

[boot.img.zip](https://github.com/topjohnwu/Magisk/files/1037690/boot.img.zip)

**Comment by coolerprog** [comment]
Please check this thread:
https://github.com/topjohnwu/Magisk/issues/209
