### ISSUE TITLE
Princess Connect! Re:Dive detecting magisk after 20 secs then close

### ISSUE THREAD

**Issue by Yurashina** [topjohnwu/Magisk#2210]
Hi,
I've been using magisk since i installed on my phone for a lot of thing and still work fine.

But lately, i installed Princess Connect! Re:Dive and tried multiples method to make it work, without success.
The issue does like it:

1. Starting the game
2. Game launching without problem
3. I come on mainscreen
4. Waiting around 15~ 20secs before it close then when to open a mail app again

The case appear when magisk is installed, work without magisk installed on kernel image.

Note: the apk of magisk is not detected.

Thank for advance

**Comment by Philip1327** [comment]
Same issue with kirara Fantasia 

Believe both are made by same devs so wouldn't surprise me if issue is related. 

I've tried everything on the best practices guides and such and still no luck. 

If anyone needs logs let me know and I'll grab them for you. 

Running One Plus 5, Magisk 20.02, OOS 9.0.9, with magisk hide and repackage and the props config module.

**Comment by topjohnwu** [comment]
#1152
