### ISSUE TITLE
Buildable sample config in config.prop.sample

### ISSUE THREAD

**Issue by krokofant** [topjohnwu/Magisk#2213]
It would be great if this was pre-filled with enough data to compile via build.py -c config.props.sample

**Comment by topjohnwu** [comment]
Well, if one can't figure out how to modify config.prop, maybe he don't actually need to build Magisk by oneself...

**Comment by krokofant** [comment]
@topjohnwu Sounds reasonable. I was thinking of streamlining an automatic build workflow but this is not really an issue. It's easy enough automate these settings as is.
