### ISSUE TITLE
[Question] Is there a way to manually request root access for an app through adb?

### ISSUE THREAD

**Issue by Mark-Joy** [topjohnwu/Magisk#2216]
I got into a weird situation.
First run after installation, the app requested root access. I granted it via an pop-up window, but then I uninstalled the app for some reasons.
Then I re-installed the app, but this time it did not request root access or whatever reason that the pop-up window did not appear.
The app is [ViPER4Android FX](https://labs.xda-developers.com/store/app/com.pittvandewitt.viperfx).
So the question is: Is there a way to manually request root access for an app through adb? so the pop-up window can appear on my phone

**Comment by skittles9823** [comment]
Check the super user tab in magisk manager, if ViPER4Android is there remove it then open it again and see if it requests root.

As for forcing a root request from an app, I don't think it's possible. Best you could do is use `magisk --sqlite` to add the app to magisks database, or just force allow root requests in magisks settings.

**Comment by topjohnwu** [comment]
Nope, it is not possible as it will be a security breach
