### ISSUE TITLE
Permission denied.

### ISSUE THREAD

**Issue by seci20** [topjohnwu/Magisk#2217]
Hi boot.img magiskinit inject but not work. Permission denied problem. How should I provide a solution ? My goal is to make root directly without installing magisk apk.

Source code line error.

```
	// Wait for ack from daemon
	if (read_int(fd)) {
		// Fast fail
		fprintf(stderr, "%s\n", strerror(EACCES));
		return EACCES;
	}
```

LogCat Log

> 1-06 00:38:18.306  3776  3776 I Magisk  : * Device API level: 28
> 01-06 00:38:18.316  3776  3777 D Magisk  : resetprop: getprop [ro.crypto.state]: [encrypted]
> 01-06 00:38:18.316  3776  3777 D Magisk  : resetprop: getprop [init.svc.vold]: [running]
> 01-06 00:38:18.335  3776  3777 I Magisk  : ** post-fs-data mode running
> 01-06 00:38:18.337  3776  3777 I Magisk  : * Initializing Magisk environment
> 01-06 00:38:18.347  3776  3777 E Magisk  : su: cannot find manager
> 01-06 00:38:18.348  3776  3777 I Magisk  : * Mounting mirrors
> 01-06 00:38:18.349  3776  3777 I Magisk  : mount: /sbin/.magisk/mirror/product <- /sbin/.magisk/block/product
> 01-06 00:38:18.349  3776  3777 I Magisk  : mount: /sbin/.magisk/mirror/vendor <- /sbin/.magisk/block/vendor
> 01-06 00:38:18.350  3776  3777 I Magisk  : mount: /sbin/.magisk/mirror/data <- /sbin/.magisk/block/data
> 01-06 00:38:18.350  3776  3777 I Magisk  : link: /sbin/.magisk/mirror/system <- /sbin/.magisk/mirror/system_root/system
> 01-06 00:38:18.350  3776  3777 E Magisk  : * Magisk environment setup incomplete, abort
> 01-06 00:38:19.333  3776  3939 I Magisk  : ** late_start service mode running
> 01-06 00:38:35.447  3776  5182 I Magisk  : ** boot_complete triggered
> --------- beginning of system
> 01-06 00:38:42.677  3776  6353 D Magisk  : su: request from pid=[6349], client=[7]
> 01-06 00:38:42.677  3776  6353 D Magisk  : su: request from uid=[2000]
> 01-06 00:38:42.681  3776  6353 E Magisk  : su: cannot find manager
> 01-06 00:38:42.681  3776  6353 W Magisk  : su: request rejected (2000)
> 01-06 00:44:34.924  3776 11064 D Magisk  : su: request from pid=[11062], client=[8]
> 01-06 00:44:34.925  3776 11064 D Magisk  : su: request from uid=[2000]
> 01-06 00:44:34.926  3776 11064 E Magisk  : su: cannot find manager
> 01-06 00:44:34.926  3776 11064 W Magisk  : su: request rejected (2000)

**Comment by topjohnwu** [comment]
You have to use Magisk Manager to accept su requests for the first time. After the initial grant, you can uninstall the app if you want.

**Comment by seci20** [comment]
How can we get him to take direct permission, sir? I want it to be root directly before the apk is installed.I compiled the source code myself. I do not want to leave your labor unrequited.

**Comment by seci20** [comment]
Which parts of the source code should I edit to get direct permission? I don't want the apk installed.

**Comment by WakerOpYT** [comment]
I am getting the **same** error while **installing,** _guys!_
