### ISSUE TITLE
Magisk is unable to patch SM-T295's firmware.

### ISSUE THREAD

**Issue by Dan9a7b** [topjohnwu/Magisk#2218]
I've been trying to root `Samsung Galaxy Tab A8 2019 LTE (SM-T295)`.

```
Software:
```
Firmware:
- `SM-T295_1_20191017110714_9yp5hpp7oy_fac`
(ver. T295XXU2ASJ1 / T295OXM2ASJ1 / T295XXU2ASJ1 / T295XXU2ASJ1)
- `SM-T295_1_20191104160354_qs36dk1kwc_fac`
(ver. T295XXU2ASJ1 / T295OXM2ASJ1 / T295XXU2ASJ5 / T295XXU2ASJ1)

Odin:
- ver. 3.13.1
- ver. 3.13.3
- ver. 3.14.1

Magisk & Magisk Manager:
- Stable \ v20.2 \ v7.5.0 \ "Boot Mode"
- Stable \ v20.2 \ v7.5.0 \ "Recovery Mode"

```
Magisk Manager's Patch Logs:
```
1. [`SM-T295_1_20191017110714_9yp5hpp7oy_fac` \ Stable \ v20.2 \ v7.5.0 \ "Boot Mode"](https://pastebin.com/fMfCzRqj)
2.  [`SM-T295_1_20191017110714_9yp5hpp7oy_fac` \ Stable \ v20.2 \ v7.5.0 \ "Recovery Mode"](https://pastebin.com/GAeWePFA)
3.  [`SM-T295_1_20191104160354_qs36dk1kwc_fac` \ Stable \ v20.2 \ v7.5.0 \ "Boot Mode"](https://pastebin.com/iGgw1rtL)
4.  [`SM-T295_1_20191104160354_qs36dk1kwc_fac` \ Stable \ v20.2 \ v7.5.0 \ "Recovery Mode"](https://pastebin.com/ct9Bmy8u)

```
ERROR:
```
**Every** imaginable combination of the software mentioned above results in the same error:
- [The device in download mode reports: "`SECURE CHECK FAIL : vbmeta"](https://imgur.com/a/8hi270w)
- [Odin's Log](https://pastebin.com/D4dzuQ7x)

Sorry for not providing more logs, but since `Odin` fails to flash the magisk-patched image (because `magisk` patches it incorrectly) I don't exactly know where to look for them. Once You point me, i'll gladly provide them.

**Comment by Fox2Code** [comment]
Please check that your boot loader is unlocked before installing Magisk.

Also, magisk need only patch `boot.img` and don't need `vbmeta.img` so you should try to only flash the `boot.img` and skip everything else.

In this case, it's doesn't seem to be Magisk fault if the flash fails and your logs show clearly that `boot.img` has passed the security check.

You should try to get help on **XDA** if you want to have help because this is not the right place here.

**Comment by mrpenceng** [comment]
https://forum.xda-developers.com/apps/magisk/sm-t285-root-t4050805

**Comment by osm0sis** [comment]
What does "overlay" the boot.img mean?

Upload the boot.img and magisk-patched.img so we can compare them and see if there's an obvious issue.

**Comment by rafeeknm** [comment]
i have Tab A SM-T295 Bootloader version 4 after upgrading from 3 to 4 touch not working.  i have tried so many things to downgrade or root nothing possible at the moment  please help for downgrade or root this device from bootloader 4 to 3 thanks in advance any experienced peoples please do something
