### ISSUE TITLE
Pixel 3 with Magisk Manager 7.5.0 (265) on Beta Channel -> no OTA update for stock system

### ISSUE THREAD

**Issue by fbfrank** [topjohnwu/Magisk#2223]
Magisk itself runs fine. I followed your installation guide. Device is rooted.
I am unable to follow the guide for OTA updates with magisk as there is no stock image to restore to, see screenshot
![Screenshot_20200106-221359](https://user-images.githubusercontent.com/46959669/71849654-d602e200-30d2-11ea-9534-a2c871705484.png)

Why is there no stock boot image? Or, where is it located? Thank you
.

**Comment by topjohnwu** [comment]
There are many possibilities why you don't have a stock image backup. You can download stock boot images directly from Google as you are using a Pixel

**Comment by fbfrank** [comment]
For sure I HAVE a stock boot image, John! I followed your installation
instructions, how could I not have one?
Magisk is not able to locate it, though. Or did not back-up properly.
Sorry, but is there no solution for that issue, as you closed it instantly?

Frank

John Wu <notifications@github.com> schrieb am Mo., 6. Jan. 2020, 23:00:
