### ISSUE TITLE
Permission denied.

### ISSUE THREAD

**Issue by seci20** [topjohnwu/Magisk#2224]
Which parts of the source code should I edit to get direct permission? I don't want the apk installed. and thank you for your efforts. Where can I donate to you ?

I'm getting an error here.

```
	// Wait for ack from daemon
	if (read_int(fd)) {
		// Fast fail
		fprintf(stderr, "%s\n", strerror(EACCES));
		return EACCES;
	}
```

device error

`Permission denied.`

**Comment by Didgeridoohan** [comment]
Github issues is for tracking bugs, not for this...

Please close this so that John doesn't have to, and seek aid on developer forums like XDA instead.

**Comment by topjohnwu** [comment]
@seci20 you should take a look at `su_daemon.cpp`, where the daemon handles the UID verification. If you know some C++, you should be able to figure it out.
