### ISSUE TITLE
magisk with google signing keys 

### ISSUE THREAD

**Issue by rockygsm** [topjohnwu/Magisk#2226]
Hello
i have  received one device which use google test and release keys. android version 7.1.1 64bit arm
its possible/allowed to modify magisk.zip to google test key or release key? 
Device do not support fastboot flash command due to unknown reason.
its do support recovery update.zip and fastboot update.zip writing.

Any idea or hint how to build magisk for update.zip in fastboot or stock recovery ?
i can post files if need for confirmation.

**Comment by topjohnwu** [comment]
In theory you can use any zip/jar signer tool to sign zips, please search them online yourself
