### ISSUE TITLE
Bootloop with latest Magisk update on my LG-G3 with stock Rom

### ISSUE THREAD

**Issue by mikhoul** [topjohnwu/Magisk#2227]
I downgraded to the previous version via TWRP and it fixed the issue.

Regards :octocat:

**Comment by aiamuzz** [comment]
could be the same issue as reported here ... https://github.com/topjohnwu/Magisk/issues/2203 & https://github.com/topjohnwu/Magisk/issues/2212

**Comment by topjohnwu** [comment]
Fixed in latest canary, please read before opening issues
