### ISSUE TITLE
VBMeta Error on Magisk 20.2 and Canary (Samsung A20e - A202F)

### ISSUE THREAD

**Issue by alexn9630** [topjohnwu/Magisk#2229]
![unnamed](https://user-images.githubusercontent.com/58658679/71920307-c218b800-3186-11ea-8851-e7da5a92bbcf.jpg)

The author did not believe me last time so here is a picture.

**Comment by coens97** [comment]
Hi I have the same error message. I used Magisk canary version 20.3-242e64d7 (20202) and Manager with version 7.5.1-15bd2da8 (266)

**Comment by coens97** [comment]
I found another way to fix it, it works now.

**Comment by alexn9630** [comment]
> I found another way to fix it, it works now.

Mind sharing how you fix it? And it is on the a20e?

**Comment by coens97** [comment]
https://forum.xda-developers.com/galaxy-a20/how-to/root-samsung-galaxy-a20-rooting-guide-t3954872
Instead of patching the whole AP image, only patch the boot.img. Make sure to rename the generated image back to boot.img or else it won't work.
