### ISSUE TITLE
Can't select individual app components [MagiskHide]

### ISSUE THREAD

**Issue by alexa-v2** [topjohnwu/Magisk#2230]
As of this moment I cannot add or remove individual app components to MagiskHide via Magisk Manager. Doing so from a root shell works fine. Via the app I can only select the whole app. Selection of an individual component causes the box to be highlighted briefly (normal animation) but not checked. Checking `magiskhide ls` shows nothing changed. In addition to that, the app doesn't show components added via `magiskhide add`

Device: pixel 2 xl
ROM: Stock Android 10, January patch
Magisk: 20.3-242e64d7 ( 20202)
Magisk Manager: 7.5.1-15bd2a8 (266)
Modules used: Doesn't matter. Confirmed this issue on first device setup after data wipe, eg no apps or Magisk modules

Logs: Logcat, Magisk log
[log.txt](https://github.com/topjohnwu/Magisk/files/4032723/log.txt)

[magisk_log_20200107_170558.log](https://github.com/topjohnwu/Magisk/files/4032724/magisk_log_20200107_170558.log)

If there's any other information you need do not hesitate to request it

**Comment by alexa-v2** [comment]
Issue also occurs on latest stable, on PixelDust X (Android 10, December patch)

**Comment by topjohnwu** [comment]
Fixed: afa178fdeca5b6ede91a1c7ef807982ae39f8cfa

**Comment by alexa-v2** [comment]
Can confirm issue is resolved
