### ISSUE TITLE
Suggestion: add package name to the module

### ISSUE THREAD

**Issue by 1456158721** [topjohnwu/Magisk#2233]
This avoids duplicate updates

**Comment by skittles9823** [comment]
What?

**Comment by 1456158721** [comment]
> What?

Like This:
![image](https://user-images.githubusercontent.com/35886522/71971065-cb685a00-3244-11ea-92ef-8770235098e0.png)

**Comment by skittles9823** [comment]
That isn't duplicate updates. They're different modules and have different ID's
