### ISSUE TITLE
Module's service.sh scripts are not ran with Magisk 20.2

### ISSUE THREAD

**Issue by F-i-f** [topjohnwu/Magisk#2234]
Not of my modules service.sh scripts are running after upgrading to 20.2.
The Magisk log doesn't show that any service.sh files are ran (the post-fs-data.sh are logged and ran).

**Comment by alexa-v2** [comment]
Can you replicate with the latest canary?

**Comment by Montblanc0** [comment]
I think this issue is related to [this one](https://github.com/topjohnwu/Magisk/issues/2295). I can't check out canary build, maybe @F-i-f can?
