### ISSUE TITLE
hide列表里面应用不全

### ISSUE THREAD

**Issue by aioscn** [topjohnwu/Magisk#2239]
hide列表里面有些应用没有，比如云闪付和建设银行，求大神

**Comment by topjohnwu** [comment]
右上角可以選擇顯示全部 system app

**Comment by aioscn** [comment]
勾选了，还是没有

**Comment by ShuosiWang** [comment]
同样的问题...一些 app 没有找到

**Comment by aioscn** [comment]
用终端命令添加
/sbin/magiskhide add 包名







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ShuosiWang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 下午4:44
收件人:&nbsp;"topjohnwu/Magisk"<Magisk@noreply.github.com&gt;;
抄送:&nbsp;"箫篮剑"<313989877@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [topjohnwu/Magisk] hide列表里面应用不全 (#2239)





 
同样的问题...一些 app 没有找到

**Comment by ShuosiWang** [comment]
> 用终端命令添加 /sbin/magiskhide add 包名
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"ShuosiWang"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月21日(星期四) 下午4:44 收件人:&nbsp;"topjohnwu/Magisk"<Magisk@noreply.github.com&gt;; 抄送:&nbsp;"箫篮剑"<313989877@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [topjohnwu/Magisk] hide列表里面应用不全 (#2239) 同样的问题...一些 app 没有找到 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

原来还能这样玩哈哈，可以可以。

这个问题我最后发现是跟系统的支付保护有冲突，非常神奇。我需要隐藏的是建行 app

> 手机： realme x2 pro
> 系统：Color OS 6.1 （安卓9）

在系统自带的支付保护里面去掉建行，然后重启一下手机就可以在 Magisk Hide 里面找到建行了。

然后就有个疑问，Magisk 不应该是最高权限么？连 XprivacyLua 都可以读到建行 APP，为啥 Magisk Hide 没能找到？

**Comment by misaka72233** [comment]
问题：Magisk hide list 只显示系统应用

> 手机： MI9SE
> 系统：MIUI12.5.4 （安卓11）
> Magisk： 23.0
> Magisk Manager：x

描述：我习惯性把手机 app 上读取应用列表的权限关掉，发现magisk hide只显示系统应用
解决：后来把读取应用列表权限打开，就没问题了
