### ISSUE TITLE
Error ' failed on 'etc/hosts'

### ISSUE THREAD

**Issue by mlokk999** [topjohnwu/Magisk#2240]
![Screenshot_20200103-144609](https://user-images.githubusercontent.com/59709333/72126448-3321c080-337d-11ea-83a8-e997a7c660cd.jpg)

**Comment by topjohnwu** [comment]
Enable custom hosts in Magisk Manager settings

**Comment by mlokk999** [comment]
![Screenshot_20200110-184845](https://user-images.githubusercontent.com/59709333/72166385-28e1df80-33da-11ea-82d9-530f3ffd1c00.jpg)

**Comment by mlokk999** [comment]
Still nothing
