### ISSUE TITLE
Stuck on Nvidia Logo updating Magisk to 20.3 - Nvidia SHIELD TV 8.0.1

### ISSUE THREAD

**Issue by thekiefs** [topjohnwu/Magisk#2243]
I have a custom install 8.0.1 boot img found [here](https://forum.xda-developers.com/showpost.php?p=80775967&postcount=193) that comes with Magisk 20.1

I tried updating Magisk from 20.1 to 20.3 in Magisk Manager using the "Direct Install" method. I  checked "Preserve AVB 2.0/dm-verify". After reboot I got stuck on the Nvidia Logo. This issue was apparently fixed in #2063 but I'm still running into issues.

To fix it I had to re-flash the custom provided image (above) and then install Magisk Manager again, which has the older 20.1 version of Magisk. This process has been broken since Nvidia Shield TV Experience 8.0.0 and Magisk 19.0

Below are the logs I could gather. Unfortunately I tried doing the Logcat boot script found [here](https://www.didgeridoohan.com/magisk/MagiskHideHelp) but there was no log in the sdcard that I could find after reflashing the working boot.img listed above.

[magisk_install_log_2020-01-10T14_18_11Z.log](https://github.com/topjohnwu/Magisk/files/4047750/magisk_install_log_2020-01-10T14_18_11Z.log)
[nvidia_shield logcat.log](https://github.com/topjohnwu/Magisk/files/4047751/nvidia_shield.logcat.log)

**Comment by bobpiesz** [comment]
I have encountered the same issue 8.0.1 developer image.

2017 16gb Darcy

I did a direct install, let it reboot, and it showed that magisk was no longer installed.

I ran a couple reboot cycles, and after the third restart, I'm stuck on NVIDIA logo. 

I'm going to hook up my laptop shortly here and try to dig out some logs.

**Comment by osm0sis** [comment]
The above should help according to @rootfan in the other Issue. Though the Shield may still need that bootloader state script workaround as mentioned over there.
