### ISSUE TITLE
adb root doesn't work on android 10

### ISSUE THREAD

**Issue by dianlujitao** [topjohnwu/Magisk#2250]
```
$ adb root
restarting adbd as root
```
and frozen. 

logcat shows
```
01-12 16:30:58.826  2713  7654 I adbd    : adbd restarting as root
```
but nothing happened, adbd doesn't restart as expected.

adb root access is enabled from magisk manager

Tested on latest lineageos 17.1, works before installing magisk.

**Comment by topjohnwu** [comment]
Disable MagiskHide and reboot if you want adb root

**Comment by alexa-v2** [comment]
@topjohnwu not technically necessary

@dianlujitao use the magiskhide props module to set ro.secure and ro.adb.secure to 0. If that fails, may need ro.debuggable set to 0 (but usually the first two, if not just ro.adb.secure is enough)

**Comment by knox** [comment]
@linuxandria setting these props didn't make adb root work for me. i had to disable MagiskHide as suggested.

**Comment by linuxandria** [comment]
> @linuxandria setting these props didn't make adb root work for me. i had to disable MagiskHide as suggested.

Weird, you tried all 3? That's always gotten it to work for me

**Comment by knox** [comment]
> Weird, you tried all 3? That's always gotten it to work for me

I've changed `ro.secure` to 0 and added `ro.adb.secure` with 0 as a custom property, `ro.debuggable` was 0 before. Tried with LOS 17.1 and Magisk 20.3 on Pixel 3.

**Comment by linuxandria** [comment]
> > Weird, you tried all 3? That's always gotten it to work for me
> 
> I've changed `ro.secure` to 0 and added `ro.adb.secure` with 0 as a custom property, `ro.debuggable` was 0 before. Tried with LOS 17.1 and Magisk 20.3 on Pixel 3.

Probably something about Android 10 then I've only checked on 9.
