### ISSUE TITLE
More magisk CLI functions

### ISSUE THREAD

**Issue by linuxandria** [topjohnwu/Magisk#2254]
At the moment, there is somewhat limited magisk functionality via CLI. You have su, magiskghide, resetprop, and a couple other random goodies.

What I'd like to see is more. 
For instance:
- **Install modules** - magisk --install-module (or -im for short) /path/to/module.zip
- **Remove (specific) module** - magisk --remove-module (or -rm for short) $MODID (or regex to match $MODID)
- **Magiskhide list possible targets** - magiskhide ls --possible (or similar)
- **Update magisk** - magisk update /path/to/magisk.zip
- **Remove magisk from the system** - magisk restore [complete|boot]

This would be aimed primarily at power users (and the remove a specific module nice for a module causing issues - the current option is way too broad and may honestly cause more issues). Just a little enhancement I really wish were present.

Thoughts and input is welcome. I'm sure I didn't cover everything you cannot currently do with magisk via CLI

**Comment by topjohnwu** [comment]
1. Module installation is done through complicated scripts, it cannot be easily recreated with just a command
2. You can already remove a module by `touch /data/adb/modules/<id>/remove` and reboot
3. This is not possible as the list is obtained by Magisk Manager via Android's Java API (and it is not trivial)
4. Same as 1.
5. Same as 1.
