### ISSUE TITLE
Magisk sometimes overwrites /dev/null with a textual command output

### ISSUE THREAD

**Issue by hyphenrf** [topjohnwu/Magisk#2255]
This is definitely a badly written sed pipe but I'm not sure from where it comes. It happens scarcely so I can't really reproduce but I think the output that gets pushed to /dev/null turning it to a regular text file might aid in debugging:

    # cat /dev/null

    sed: /data/.magisk: No such file or directory
    sed: /cache/.magisk: No such file or directory
    Broadcast completed: result=0

If anyone has issues with overwritten /dev/null, this is how to restore it (run as root):
```sh
mknod /dev/null c 1 3
chmod 666 /dev/null
```

**Comment by Didgeridoohan** [comment]
Whatever it is that's happening, it would likely be here:
https://github.com/topjohnwu/Magisk/blob/3049a81c3bfb981018df744b4f8ce34023be2248/scripts/util_functions.sh#L27

**Comment by shakalaca** [comment]
@hyphenrf did you install any modules ?

**Comment by sithsupersu** [comment]
no I didn't install any chance modules.

**Comment by hyphenrf** [comment]
> @hyphenrf did you install any modules ?

Yeah: microg installer, systemless hosts, joy pixels, exsdcard access, busybox android ndk, bariol font, and app systemizer.  
I'm on android 7.1.2, btw

might also be worth mentioning (maybe this is related to the issue maybe not) that Magisk fails to update itself (20.0, 7.3.5)

**Comment by topjohnwu** [comment]
I don't think this is related to Magisk, any program running as root can cause this
