### ISSUE TITLE
Can't access media after installing 20.4

### ISSUE THREAD

**Issue by MauJFernandez** [topjohnwu/Magisk#2256]
> Hi, yesterday I updated Magisk to 20.4 and after reboot I can't access my media from the apps unless I clear their app data. I first noticed it today when I opened Play Music, I was getting constant and immediate force closes, I can't access my galleries (I use Focus Go and Piktures) nor I can't open the galleries from WhatsApp or Telegram. I tested clearing the data from Play Music and Piktures and now they work OK, but clearing the data from WhatsApp or Telegram is a PITA, any way to fix this?

I posted that in this link from reddit https://www.reddit.com/r/Magisk/comments/eo4y8k/help_cant_access_media_after_magisk_update/, if you need something please tell me, I'll provide what I can.

Thanks.

**Comment by MauJFernandez** [comment]
Now I'm getting com.android.media force closes when I connect it to transfer files, I can't even open WhatsApp because it closes instantly.

**Comment by topjohnwu** [comment]
Sorry, but no other people have experience the same issue.
Also, no logs = no fix
