### ISSUE TITLE
Advanced Settings Resets

### ISSUE THREAD

**Issue by alroy214** [topjohnwu/Magisk#2257]
Fixed an issue by preserving force encryption and preserving AVB 2.0, it all worked.
After a reset the both the "preserve" ticks became deactivated and the "recovery mode" tick became active.
Before reset:
![photo_2020-01-14_12-01-46](https://user-images.githubusercontent.com/31711733/72334411-ee23c400-36c5-11ea-9b2e-d3f93f856a24.jpg)
After reset:
![photo_2020-01-14_12-01-33](https://user-images.githubusercontent.com/31711733/72334386-e7954c80-36c5-11ea-8ee6-e1ff67f7f18b.jpg)

Samsung Galaxy S10 Android 10.

**Comment by alroy214** [comment]
Sometimes it works, sometimes it doesn't but when the "preserve" ticks don't change my problems are non but after a few couple of resets, the ticks are back to deactivated :c

**Comment by topjohnwu** [comment]
S10 should be running recovery mode, please don't mess with that as Samsung devices can very easy brick themselves, causing you to lose all your data.
Read the installation instructions in official docs carefully.

**Comment by alroy214** [comment]
@topjohnwu it's fixed sticking after a reinstall, now I can pass everything and even the Samsung Account thing now works. You know I read the installation instructions, just needed it for the special occasion to some that problem from before. 
P.S. now that I have the Samsung Account running even if it bricks I have my data *relaxed sigh* but I understand why is should be in recovery in the general case
