### ISSUE TITLE
Minimal ramdisk environment for magiskinit64

### ISSUE THREAD

**Issue by evdenis** [topjohnwu/Magisk#2258]
What is the minimal ramdisk env for magiskinit64? My phone (S10) doesn't have a ramdisk, so I want to rebuild the kernel with build-in ramdisk (CONFIG_INITRAMFS_SOURCE).

Is it enough to have only init file in initrd?
```
file /init usr/magiskinit64 0755 0 0
```

Do I need to create .backup folder with .magisk file?

**Comment by topjohnwu** [comment]
Samsung does not allow ramdisk in boot images (this is enforced in the bootloader). Please read the instructions and install Magisk in your recovery image.

**Comment by topjohnwu** [comment]
@evdenis yes, that is sufficient, however please also include the current config in `/.backup/.magisk`
