### ISSUE TITLE
Certain MTK devices not supported 

### ISSUE THREAD

**Issue by kirito96** [topjohnwu/Magisk#226]
Hello, I'd like to request support for another type of MTK boot.img path. The older MTK(MT6572/82/92 MT8127) devices uses /dev/bootimg as the boot path while the newer devices (MT67xx and MT6580) use /dev/block/platform/mtk-msdc.0/11120000.msdc0/by-name/boot

@osm0sis had previously fixed that for me in his AK2 script here : https://github.com/osm0sis/AnyKernel2/commit/c13647eb2ea9cdc46a51e27a74a58b8271edbc6b

It might help in someway. 

Below is the scatter file for the device which shows the partitions and mount points. 

![block](https://cloud.githubusercontent.com/assets/6293753/26764616/6b8aafda-4916-11e7-80b7-df09cf705829.jpg)

And here is the boot.img: https://www.androidfilehost.com/?fid=673368273298960836

**Comment by osm0sis** [comment]
The only MTK I've seen that doesn't work with my borrowed omni code is the terrifying implementation in the hongyu72 device. I can't even begin to explain what's going on there. 😜

**Comment by DeicPro** [comment]
This function search for boot image
https://github.com/topjohnwu/Magisk/blob/e780c76c93db53501f1d1616802c6583e6da3a19/scripts/flash_script.sh#L82

This calls the patch script with the boot image como argument
https://github.com/topjohnwu/Magisk/blob/e780c76c93db53501f1d1616802c6583e6da3a19/scripts/flash_script.sh#L308

**Comment by kirito96** [comment]
Ok, ignore my previous comment about not being simple xD. I'll check this out (Y). Thanks.

**Comment by XRevan86** [comment]
On MT6582 what mitigates the issue is something like this:
```diff
--- a/scripts/boot_patch.sh
+++ b/scripts/boot_patch.sh
@@ -55,6 +55,13 @@ fi
 BOOTIMAGE="$1"
 [ -e "$BOOTIMAGE" ] || abort "$BOOTIMAGE does not exist!"
 
+if [ ! -b "$BOOTIMAGE" ] && which nanddump nandwrite >/dev/null 2>&1; then
+  BOOTIMAGE_FILE="$TMPDIR/boot.img"
+  nanddump -f "$BOOTIMAGE_FILE" "$BOOTIMAGE"
+else
+  BOOTIMAGE_FILE="$BOOTIMAGE"
+fi
+
 # Flags
 [ -z $KEEPVERITY ] && KEEPVERITY=false
 [ -z $KEEPFORCEENCRYPT ] && KEEPFORCEENCRYPT=false
@@ -71,7 +78,7 @@ chmod -R 755 .
 CHROMEOS=false
 
 ui_print "- Unpacking boot image"
-./magiskboot --unpack "$BOOTIMAGE"
+./magiskboot --unpack "$BOOTIMAGE_FILE"
 
 case $? in
   1 )
@@ -101,9 +108,9 @@ case $? in
   0 )  # Stock boot
     ui_print "- Stock boot image detected"
     ui_print "- Backing up stock boot image"
-    SHA1=`./magiskboot --sha1 "$BOOTIMAGE" 2>/dev/null`
+    SHA1=`./magiskboot --sha1 "$BOOTIMAGE_FILE" 2>/dev/null`
     STOCKDUMP=stock_boot_${SHA1}.img.gz
-    ./magiskboot --compress "$BOOTIMAGE" $STOCKDUMP
+    ./magiskboot --compress "$BOOTIMAGE_FILE" $STOCKDUMP
     cp -af ramdisk.cpio ramdisk.cpio.orig
     ;;
   1 )  # Magisk patched
@@ -169,7 +176,7 @@ fi
 ##########################################################################################
 
 ui_print "- Repacking boot image"
-./magiskboot --repack "$BOOTIMAGE" || abort "! Unable to repack boot image!"
+./magiskboot --repack "$BOOTIMAGE_FILE" || abort "! Unable to repack boot image!"
 
 # Sign chromeos boot
 $CHROMEOS && sign_chromeos
--- a/scripts/util_functions.sh
+++ b/scripts/util_functions.sh
@@ -210,7 +211,11 @@ flash_image() {
   else
     COM2="cat -"
   fi
-  if [ -b "$2" ]; then
+  if [ ! -b "$2" ] && which nanddump nandwrite >/dev/null 2>&1; then
+    nandwrite -p "$2" /dev/zero >/dev/null 2>&1
+    eval $COM1 | eval $COM2 | nandwrite -p "$2" >/dev/null
+    [ $? != 0 ] && return 1
+  elif [ -b "$2" ]; then
     local s_size=`stat -c '%s' "$1"`
     local t_size=`blockdev --getsize64 "$2"`
     [ $s_size -gt $t_size ] && return 1
```
Possibly related: #24, #75, #190, #227.

**Comment by kirito96** [comment]
I didn't realize people were still looking into this. I will check this out when I have time. Thanks for your efforts.
