### ISSUE TITLE
Magisk v12 does not work on BQ Aquaris E5 HD with stock ROM 2.1.0 (Android 5.0)

### ISSUE THREAD

**Issue by David91YT** [topjohnwu/Magisk#227]
Without root or any other modification, the ZIP of the Magisk v12 gives the following error when trying to install it by recovery (TWRP 3.1.1-0):

*********************************
Magisk v12.0 Boot Image Patcher
*********************************

- Mounting /system(ro), /cache, /data
- Device platform: arm
- Constructing environment
- /data/magisk.img detected!
- Mounting /data/magisk.img to /magisk
- Found Boot Image: /dev/bootimg
- Unpacking boot image
! Unable to unpack boot image
Process Updater has finished with ERROR: 1

Boot image:
https://mega.nz/#!rBchEK7b!1F6VwEhHgTlwR09QD2-U5t33CLHG9yuI5hJV7Bsg0Pk

**Comment by kirito96** [comment]
You have the same problem as me 😆

**Comment by DeicPro** [comment]
@kirito96 that easy to do, is only edit the install script like this:
```
if [ -f /dev/bootimg/the-file-or-partition ]
then BOOTIMG="/dev/bootimg/the-file-or-partition"
else BOOTIMG="regular-partition-path"
fi
```
and replace all partition path with `$BOOTIMG` in the script. This is an example, IDK as is the script and if BOOTIMG var is already used for another thing.

**Comment by David91YT** [comment]
If you could create a file or modify the Magisk directly to do what you indicated ... I am not a programmer; I am a simple user who likes to make the most of his mobile; I have no programming skills at all.

When you talk about modifying the installation script, I do not know what file you mean (?). If you could explain it in detail, step by step, and at the end I can install the Magisk in this demoniac mobile, I would appreciate it xD

**Comment by kirito96** [comment]
It's not that simple else I would've done it already.
