### ISSUE TITLE
Emulator.sh

### ISSUE THREAD

**Issue by its4win** [topjohnwu/Magisk#2270]
Hi,
I try to run emulator.sh to install magisk in AVD
but i got error 

"CANNOT LINK EXECUTABLE "/sbin/magisk": library "libandroidicu.so" not found"

![image](https://user-images.githubusercontent.com/58930060/72508508-5a462980-3878-11ea-8fcb-ecadfbe78928.png)

any solutions?
Thanks

AVD : Nexus_5X_API_29_x86
Magisk 20.3
Magiskinit from Magisk-v20.3 > x86 > magiskinit

**Comment by topjohnwu** [comment]
@imswebra build the binary from scratch, the current script requires changes in `master` that is not publicly released

**Comment by its4win** [comment]
@topjohnwu , do u mean to build binary from binary.py ?
This error to,
jni/external/Android.mk:237: jni/external/mincrypt/Android.mk: No such file or directory

![image](https://user-images.githubusercontent.com/58930060/72581836-48659480-3913-11ea-873b-26d14e627f39.png)

any solutions?
Thanks
