### ISSUE TITLE
[ERROR] Unable to retrieve local hardware address libnet ( ioctl: Permission denied ). MAGISK BUG

### ISSUE THREAD

**Issue by stanIee** [topjohnwu/Magisk#2275]
This is a bug found. This prevents me from doing my job. My Job is to find vulnerability in Network. Only now I can't. It's not a problem in the app. I tried multiple apps and they all drop the same error.

**Comment by linuxandria** [comment]
I'd get this has absolutely zero to do with specifically magisk. Have you tried going permissive via `su -c setenforce 0`?

**Comment by stanIee** [comment]
I tried this just now on my terminal. it doesnt seem to  work

**Comment by linuxandria** [comment]
Definitely a device/ROM issue then

Recommend closing as this isn't related directly to magisk

**Comment by stanIee** [comment]
I won't close it since I am not the only one that has this problem. Some other people had the same error with Magisk as root. I would really like to fix this problem. Maybe someone else could help. so I rather let it open.

**Comment by shakalaca** [comment]
On any devices with Magisk installed ? Which app ?

**Comment by stanIee** [comment]
I get this error on my Samsung Galaxy J6 with these apps: Dsploit, Network spoofer and zAnti.

**Comment by stanIee** [comment]
I'm sorry. may I get an explanation on why this was closed?

**Comment by stanIee** [comment]
If anyone could potentially give me any fix for this specific issue. or maybe this could he taken in the next update.

**Comment by stanIee** [comment]
Well thanks for the support on  this. And thanks for closing this without even fixing my problem I appreciate it. I thought this was a helpful community. Bet it isnt then huh. Well thanks for trying to help me with the command. and John. you just closed my app for no reason. This has in fact to do with specifically Magisk. since I'm not the only one. I guess you can ignore not. that is kinda sad.

**Comment by shakalaca** [comment]
Those apps are kind of old, are they running well with other root solution ?

**Comment by stanIee** [comment]
Yes. they do work with other root's. they sometime error but this specific error is only known by the Magisk users

**Comment by 123omari123** [comment]
I also have this problem, every app i tried it drops this error. But one interesting thing, when I installed old version of WiFIKill - Pro v2.0.2 P.apk- it worked, but new version not.

**Comment by 123omari123** [comment]
finally, I solved this problem, it is not magisk issue , it needed permissive selinux mode, so I installed custom kernel on my phone and everything works perfect.
