### ISSUE TITLE
Root behaves strangely on Android 10

### ISSUE THREAD

**Issue by Gieted** [topjohnwu/Magisk#2276]
After installing Magisk 20.3 under Android 10 some root features work and some don't.
Using root explorer I was able to:

- change permissions of directory
- change owner of directory
- list directories and files within them
- delete files
- move and copy files

However, I can't:

- create a file
- read files

Because of this some root apps don't work, for example I can't install BussyBox using BussyBox installer.

I know I haven't provided enough information to detect the issue, but I don't know what you need, just ask me anything you want.

**Comment by Gieted** [comment]
[magisk.log](https://github.com/topjohnwu/Magisk/files/4075759/magisk.log)
[catlog.txt](https://github.com/topjohnwu/Magisk/files/4075761/logcat_01-17-2020_09-34-55.txt)

**Comment by linuxandria** [comment]
Just so you know, under Android 10 and magisk files in system are not modifiable directly. A lot of Android 10 devices have forced RO system (eg, EROFS or ext4 dedup or dynamic partition), and magisk now respects SaR implementation.
I've never been able to directly modify system with magisk, but after all it's a _systemless_ root method.

For BusyBox use the BusyBox magisk module, available in the repo in magisk Manager

**Comment by Gieted** [comment]
I have been using Magisk for many custom roms from Android 7, but I never faced problems with root apps. Even if Magisk is systemless, modifications that the root apps do, don't have to be. Busybox was only an example, there are many other apps that will fail, because being unable to read/create files in root mode is unexpected. Correct me if I'm wrong.

**Comment by linuxandria** [comment]
You got lucky ig
Any recent ROM I've tested in modifications don't persist across reboots

**Comment by Gieted** [comment]
By telling "root directories" I didn't mean /system, but rather all other directories listed under /*. The one that I care most about is /cache, because it is the one that most of the root apps use for some stuff.

Also /system isn't just not persistent across reboots, it can't be mounted at all.

**Comment by Gieted** [comment]
And as I told I in fact can both read and write to /* and /system, by moving the files from/to external storage, I just can't perform operation of direct read and file creation.

**Comment by topjohnwu** [comment]
@Gieted starting in Android 10, root directory is no longer writable as it is part of the read-only system partition

**Comment by Gieted** [comment]
@topjohnwu I wasn't talking about root directory itself, but rather it's content for example /cache, which is totally writable (even Magisk itself writes its logs there)
