### ISSUE TITLE
Magisk not working on redmi 8a (probably because of non standard boot image)

### ISSUE THREAD

**Issue by redmi8** [topjohnwu/Magisk#2277]
I am running MIUI V11.0.3.0.PCPINXM_20191119.0000.00_9.0_in (Android 9) on 32/3gb Redmi 8a Indian version 
and i tried installing magisk with the patch boot image and recovery method. Both failed.

I think that the boot.img they use is non standard as the tools i used for unpacking ramdisk out of it fails or give only kernel and empty ramdisk folder

Even magisk patched image reduce its size almost half. It does boots with patched image but magisk does not works.

I am attaching the original and patched images here.
[boot images.zip](https://github.com/topjohnwu/Magisk/files/4076205/boot.images.zip)

Please let me know if you need logs or to test anything else. Thanks.

**Comment by Gieted** [comment]
What "Magisk does not work" means? Magisk Manager says Magisk isn't installed?

**Comment by redmi8** [comment]
> What "Magisk does not work" means? Magisk Manager says Magisk isn't installed?

It says magisk is not installed
![photo_2020-01-17_15-42-29](https://user-images.githubusercontent.com/59997625/72604138-58479d80-3940-11ea-991d-71243deb9656.jpg)

**Comment by redmi8** [comment]
@topjohnwu why did you closed it? Is it fixed now or if you need logs

**Comment by gam2046** [comment]
@topjohnwu Is there any new news about this issues
