### ISSUE TITLE
Compile issue with FrankeNDK r4 r3 and Ndk 20 and 21 

### ISSUE THREAD

**Issue by pipop62** [topjohnwu/Magisk#2278]
FrankeNDK-r4/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: error: LLVM gold plugin has failed to create LTO module: Unknown attribute kind (62) (Producer: 'LLVM9.0.8svn' Reader: 'LLVM 8.0.7svn')
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/arm64-v8a/magisk] Error 1
make: *** Waiting for unfinished jobs....

Build binary failed!

**Comment by pipop62** [comment]
Figured it out:

build.py clean doesn't remove native/obj dir so if you use android ndk to build and then switch to FrankeNDK, event after cleaning it won't compile.

Also the release page of FrankeNDK shows wrong branch to pull latest release:
git clone --branch r3 --depth 1 https://github.com/topjohnwu/FrankeNDK.git

instead of r4.
Thanks.

**Comment by linuxandria** [comment]
If you've solved, please close this issue.

**Comment by pipop62** [comment]
> If you've solved, please close this issue.

gonna close it, but those two bugs should be addressed, thanks for your time and work.
