### ISSUE TITLE
Installed a module and got stuck in a bootloop on Pixel 4. Nothing I am trying works.

### ISSUE THREAD

**Issue by NyleCohen** [topjohnwu/Magisk#2281]
Hi. I have Magisk installed on my pixel 4 and got into a bootloop when I installed a module. I thought this would be easily fixable but I have tried all of the methods I can find for the Pixel 4 and none of them are working for some reason. I've tried flashing a stock image, flashing magisk_patched.img, flashing a custom core only image I made, flashing a core only image someone else made and some other methods. Since the pixel 4 doesn't have TWRP yet there is no way to flash a file to get rid of the bootloop. The module I was trying to install was Edexposed YAHFA (Sandhook didn't bootloop, but did not correctly install.) Any help would be appreciated. Thanks!

**Comment by linuxandria** [comment]
Not magisk issue. Module issue.
You're going to have to clean flash stock (wipe data too)

Recommend closing

**Comment by NyleCohen** [comment]
This is a noob question, but how would I go about doing this? Thanks for the quick reply.
