### ISSUE TITLE
 Failed to initialize runtime (check log for details)

### ISSUE THREAD

**Issue by redmi8** [topjohnwu/Magisk#2283]
I am running MIUI V11.0.3.0.PCPINXM_20191119.0000.00_9.0_in (Android 9) on 32/3gb Redmi 8a Indian version.
And the magisk install fails. Here are the logs.
[dmesg.log](https://github.com/topjohnwu/Magisk/files/4080258/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/4080259/recovery.log)

**Comment by shakalaca** [comment]
Can you try the Canary build ?

**Comment by redmi8** [comment]
@shakalaca I tried the canary build but it fails with same errors.
Failed to initialize runtime in recovery.log
and avc denied for magisk zip in dmesg.log

Same to what was there in 20.3 stable

**Comment by redmi8** [comment]
The solution to avoid this error that worked for me is to install miui from xiaomi eu and then magisk could be installed.
