### ISSUE TITLE
x86 support

### ISSUE THREAD

**Issue by Cyrupruk89** [topjohnwu/Magisk#2285]
Hello! I tried to flash Magisk 20.3 on my Galaxy Tab 3 using twrp. It doesn't show me any errors so i rebooted system. But Magisk Manager are saying magisk is not installed and showing me notification about magisk update but there is nothing to update.
My device GT-P5200
Android 4.4.2
x86
TWRP 2.8.6.0

**Comment by Cyrupruk89** [comment]
Btw in /data there is magisk folder but uninstaller ends with error.

**Comment by Emulatorer** [comment]
#2277

**Comment by Cyrupruk89** [comment]
But SuperSU works so I have to use it instead of Magisk. RIP
