### ISSUE TITLE
[Device support] v13.2 Axon 7 variant A2017U  (failed to open database) su crashes plus boot.img

### ISSUE THREAD

**Issue by bluenote73** [topjohnwu/Magisk#229]
I see some other posts about the Axon 7, but it seems like they are for other variants and that they may differ.  Here is latest available boot.img for the A2017U variant (other variants are A2017G, A2017)
Sorry if I'm mistaken and this isn't needed :)  Thanks!

Here is a mega link, I'm not sure if there's a better preferred filehost: https://mega.nz/#!XdNVGQ5T!HuMI1cs_A_Rk-RH6RZ1vUSCd-suUOj4iC0NUPYT0snk

Also in case there's a problem with that link, files are also available in this thread: https://forum.xda-developers.com/axon-7/development/rom-guide-updates-to-stock-files-via-t3469484

A2017U files are this post: https://forum.xda-developers.com/showpost.php?p=68873482&postcount=2

Thank you!

**Comment by bluenote73** [comment]
Here is an output of trying to run SU as after a virgin install of v13 54e6a79
[magisk_debug.log.txt](https://github.com/topjohnwu/Magisk/files/1116669/magisk_debug.log.txt)
[magisksu_log.txt](https://github.com/topjohnwu/Magisk/files/1116670/magisksu_log.txt)

**Comment by bluenote73** [comment]
Here's a recovery.log from trying to install Magisk c4377ed.  I note a 'segmentation fault' around line 301.
thanks

[recovery.log.txt](https://github.com/topjohnwu/Magisk/files/1123182/recovery.log.txt)

**Comment by bluenote73** [comment]
SU doesn't work at all, magisk hide works, magisk modules work, safetynet passes.  Here's logs as detailed in the beta instructions for SU problems. Running C4377ed.

[magisk_debug.log.txt](https://github.com/topjohnwu/Magisk/files/1126179/magisk_debug.log.txt)
[magisksu_log.log.txt](https://github.com/topjohnwu/Magisk/files/1126180/magisksu_log.log.txt)

**Comment by bluenote73** [comment]
After MM uninstall plus flashing magisk uninstall then stock and boot.img flash, installing magisk v13.1, then magisk manager keeps crashing when anything tries to request SU. adb shell su reports 'permission denied'.  (Segmentation fault has disappeared from previous logs) Here are my logs:

[magisksu_log.txt](https://github.com/topjohnwu/Magisk/files/1137458/magisksu_log.txt)
[magisk_recovery.log.txt](https://github.com/topjohnwu/Magisk/files/1137457/magisk_recovery.log.txt)

**Comment by bluenote73** [comment]
Using v13.2 - after a MM uninstall from android, then flash magisk uninstaller, then clear cache/dalvik, then flash stock boot.img, then flash Magisk 13.2, su continues to crash every time it is requested.  Here's my logs:

[recovery.log.txt](https://github.com/topjohnwu/Magisk/files/1146689/recovery.log.txt)
[magisksu_log.txt](https://github.com/topjohnwu/Magisk/files/1146690/magisksu_log.txt)

**Comment by Dryness** [comment]
Just chiming in as well with my own logs replicating the force close upon any su request using the stock Axon 7 A2017U 7.1.1 rom (b25).  
Magisk hide works and passes SafetyNet, but whenever user permission for root is requested, Magisk Manager force closes, presumably because the su database does not exist.

[magisksu_log.txt](https://github.com/topjohnwu/Magisk/files/1146794/magisksu_log.txt)
[recovery_log.txt](https://github.com/topjohnwu/Magisk/files/1146796/recovery_log.txt)

**Comment by bluenote73** [comment]
Oops.  Accidently closed.  Reopened.

**Comment by Dryness** [comment]
From the general support thread, it was suggested that /data/user/0 was not correctly symlinked, and the lack of multi-user on the stock Axon 7 image may be part of the issue.  I've verified that the symlink does appear to exist:
```
~ # ls -l /data/user/0
lrwxrwxrwx    1 root     root            10 Apr  6  1970 /data/user/0 -> /data/data

~ # stat /data/user/0
  File: '/data/user/0' -> '/data/data'
  Size: 10              Blocks: 0          IO Block: 4096   symbolic link
Device: fe00h/65024d    Inode: 1302530     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 1970-04-06 06:01:24.000000000
Modify: 1970-04-06 06:01:24.000000000
Change: 1970-04-06 06:01:24.000000000
```
I added the following two modifications to enable multi-user:
```
fw.max_users=10
fw.show_multiuserui=1
```
Which "worked" in that I have the ability to create users on the stock rom now.  I removed and re-installed Magisk 13.2 and Magisk Manager 5.0.6 but sadly there's been no change in our ability to run anything under `su`.

[magisk_log.txt](https://github.com/topjohnwu/Magisk/files/1156069/magisk_log.txt)
[recovery.log.txt](https://github.com/topjohnwu/Magisk/files/1156070/recovery.log.txt)

**Comment by Dryness** [comment]
An update for Magisk 13.3 and Manager 5.1:  still no change, unfortuantely.

I completely removed all traces of Magisk, and re-created the symlink between /data/user/0 and /data/data.  I then rebooted back into recovery and installed Magisk 13.3 (log attached), followed by a reboot back into system to install Magisk 5.1.  Any su request continues to fail and FC Manager with the same results in the magisksu_log (also attached):
`Failed to open database '/data/user/0/com.topjohnwu.magisk/databases/su.db'.`

[magisksu_log_5.1.txt](https://github.com/topjohnwu/Magisk/files/1159829/magisksu_log_5.1.txt)
[recovery.log_13.3.txt](https://github.com/topjohnwu/Magisk/files/1159830/recovery.log_13.3.txt)

I did (accidentally) install Manager 4.3.3 (while using Magisk 13.3), and was at least able to get root in terminal emulator - however, after granting permission, Manager dies, and the "duration" selection doesn't get saved (again, no db access).  In case it helps anything, I've also attached the magisksu_log file:
[magisksu_log_4.3.3.txt](https://github.com/topjohnwu/Magisk/files/1159836/magisksu_log_4.3.3.txt)
