### ISSUE TITLE
How build magiskboot windows ? 

### ISSUE THREAD

**Issue by seci20** [topjohnwu/Magisk#2290]
Hi. How do I compile as magiskboot.exe ? I want to run Magiskboot on windows.

**Comment by Fox2Code** [comment]
Hi `magiskboot` can't be compiled in `.exe` however, you can run the Linux x86/x86_64 files on your computer with **WSL** or **Cygwin** (Check on Google)
But I would recommend you to use **WSL** for maximum compatibility
