### ISSUE TITLE
/vendor/etc/vintf/manifest.xml symlinking

### ISSUE THREAD

**Issue by guitardedhero** [topjohnwu/Magisk#2291]
/vendor/etc/vintf/manifest.xml fails to be symlinked by a module in time to register hardware services that are added to this file when existing in a module setting.

Placing this same modified xml directly on the partition allows the added hardware services to register successfully.

This prevents my current porting project from being a pure Magisk module as /vendor/etc/vintf/manifest.xml must be edited in place at this time. Thanks, John.

gh

**Comment by skittles9823** [comment]
Would be interesting to see if simple_mount would have made this possible, but I don't remember when it was removed and if the last version it existed in supported Q.

**Comment by Zackptg5** [comment]
You can addon any system or vendor init rc script to this as well

**Comment by topjohnwu** [comment]
No future plans are made to support pre-init complex mounting.
