### ISSUE TITLE
Magisk 20.3 breaks SELinux manipulation

### ISSUE THREAD

**Issue by Montblanc0** [topjohnwu/Magisk#2292]
I am running MIUI 11.0.4.0 based on Pie on my Redmi Note 7 and on this device I need SELinux to be set as Permissive in order for Viper to install drivers and work properly. Everything was fine on 19.3 but when I tried installing Viper from scratch after upgrading Magisk to 20.3, it always fails to copy drivers.

I found out that modules that set SELinux as Permissive on boot did not work anymore with this version of Magisk as getenforce will always return Enforcing with any module I tried. So I manually changed SELinux status with "setenforce 0" and made sure it returned Permissive, but Viper still failed to copy drivers.

I assume this behaviour is not only related to Viper but to anything requiring a Permissive SELinux.

Reverting to 19.3 made everything work smoothly again. Probably the last working version is 20.1.

Here are some posts on the xda thread describing the issue:

https://forum.xda-developers.com/showpost.php?p=81525727&postcount=37945
https://forum.xda-developers.com/showpost.php?p=81530487&postcount=37952
https://forum.xda-developers.com/showpost.php?p=81534843&postcount=37960
https://forum.xda-developers.com/showpost.php?p=81538463&postcount=37963

**Comment by fox8091** [comment]
Honestly no module should rely on permissive SELinux. We have a way to set custom rules, they should use that.

**Comment by topjohnwu** [comment]
If you cannot set selinux to permissive, this is nothing related to Magisk

**Comment by aIecxs** [comment]
it's funny that you tracked down issue to specific Magisk version but issue is ignored as "not related to Magisk"

**Comment by linuxandria** [comment]
_Because it isn't._ It's not @topjohnwu fault they haven't updated their app to work correctly.
As suggested don't set permissive; rather add the rules you need.

**Comment by aIecxs** [comment]
and here comes the funny suggestion again.. so the solution for setting permissive is not setting permissive because the changed usage behavior is not a bug its a feature

**Comment by linuxandria** [comment]
Permissive isn't really a solution it's a workaround and an insecure one at that.

You do realize that if you're SELinux is permissive, I don't need camera permission, I can just open the relevant HAL? No? 

Anyhow not gonna argue security but this is the way it's going to be because some OEMs and kernels don't allow permissive anyhow, and for good reason

**Comment by linuxandria** [comment]
If you need to allow them to work, go through logcat and find `avc: {denied}` and I beloeve msfjarvis has a good guide on how to write sepolicy if you look around.
