### ISSUE TITLE
[feature request] manager to support the use of an http proxy

### ISSUE THREAD

**Issue by lolorc** [topjohnwu/Magisk#2293]
hi there,

android apps providing a way to setup an http proxy is not very common, the f-droid app allows it for instance.
In my case, my device has a restricted network access, It would be easier to use an http proxy than accepting connections to tcp 80/443 for github.com, raw.githubusercontent.com, api.github.com and codeload.github.com
Do you think it would be a valid feature to add to the manager ?

**Comment by topjohnwu** [comment]
Doesn't Android support setting proxy in global network settings? Anyways, I don't want to complicate the app anymore, so this feature will not be considered.
