### ISSUE TITLE
Module Files have inaccurate SELinux Context labels

### ISSUE THREAD

**Issue by Jman420** [topjohnwu/Magisk#2294]
I'm not sure if this is really an issue in Magisk or if it's the responsibility of the Module Devs, but I've noticed that the Module Files all get labeled with 'system_file' context even if the files are put into the 'vendor' partition.  This has resulted in Audio Mods breaking in Android10 where SELinux Rules seem to be more strict around what parts of the file system the Android Audio System can access.

I've managed to work around this by using 'chcon' to manually change the SELinux Contexts after the Module has been installed.  I'm not sure if other issues could be related to this as well...

**Comment by topjohnwu** [comment]
It is the module dev's responsibility to make sure all files are set to the proper secontext. Magisk will also clone the original context it is replacing if the target file exists.
