### ISSUE TITLE
Magisk 20.3 breaks some modules compatibility (replicable)

### ISSUE THREAD

**Issue by Montblanc0** [topjohnwu/Magisk#2295]
I am opening this issue just once more because I think the [previous one](https://github.com/topjohnwu/Magisk/issues/2292) was misunderstood.

1) Modules like SELinux manager (and any other trying to change SELinux status on boot) DO NOT WORK anymore on Magisk 20.3 (SELinux status is set as Enforcing on boot even if stated otherwise)
2) Module like SELinux manager WORK again on 20.1 and SELinux is correctly set as Permissive.
3) Reverting Magisk to 20.1 makes every module and app work perfectly again.
4) Upgrading Magisk to 20.3 breaks module compatibility again so this is a replicable issue on my device.

If SELinux Manager is working for you on 20.3, this means the problem is probably with MIUI compatibility.

On 20.3 I CAN INDEED change SELinux status with "setenforce 0" and it will say it is Permissive.

I hope this time you will get the time to read carefully, and if anything is unclear or you require any info or log, please don't bother asking, I'm here to help resolve this issue.

**Comment by BilliTheKid** [comment]
Still not fixed with 20.4

**Comment by topjohnwu** [comment]
Please make the module's developer know and adjust to newer Magisk versions
