### ISSUE TITLE
Build failed on v20.3 and v20.2

### ISSUE THREAD

**Issue by ajayyy** [topjohnwu/Magisk#2296]
I cannot get the build to succeed on v20.3 or v20.2. I have tried on Windows, Windows subsystem for linux (ubuntu) as well as TravisCI.

I have tried redownloading Java and the Android SDK + NDK multiple times.

Here is my TravisCI build: https://travis-ci.org/ajayyy/Travis-CI-Magisk-Builder/builds/640169213

The error I am getting:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'build.gradle' line: 65

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Ambiguous method overloading for method java.io.File#<init>.
     Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.net.URI]
        [class java.lang.String]
   > java.io.IOException: The filename, directory name, or volume label syntax is incorrect
```

This happens during the Magisk Manager build.

**Comment by linuxandria** [comment]
I'm having issues with prebuilts not being cloned correctly and Magisk failing to build
Might be related?

**Comment by ajayyy** [comment]
I think this issue related to a gradle update?

**Comment by ajayyy** [comment]
Well, I don't know how it took me so long to try, but it was a very simple mistake.

Omitting the following from config.props caused this issue.

```
keyStore=release-key.jks
keyStorePass=
keyAlias=
keyPass=
```

I misinterpreted the comments into saying that they don't have to be there. This is potentially solved in
