### ISSUE TITLE
General Magisk Hide improvement suggestion

### ISSUE THREAD

**Issue by Senliast** [topjohnwu/Magisk#2298]
It's not a Magisk Hide request for a certain app, but a general improvement suggestion.
The Magisk Hide protection is pretty well, therefore some apps started to detect root with checking for common files / folders in /sdcard, that are typically present on rooted devices (for example, TWRP, Titanium Backup, substratum). For example, Fortnite is now checking for TWRP folder))). And Magsik can systemlessly remove files / folders, can it 🤔? And my suggestion is, that magisk automatically hides these folders for those apps, for which Magisk Hide is activated.
Would it be possible?

**Comment by topjohnwu** [comment]
Nope sorry, that is not how MagiskHide works :)
You will have to remove those files/folders yourself
