### ISSUE TITLE
Slow on boot

### ISSUE THREAD

**Issue by avently** [topjohnwu/Magisk#23]
Without Magisk my phone needs ~4 seconds to boot until Android bootanimation appears. And ~4 seconds to shutdown. 
With Magisk this numbers are: ~40 seconds and ~10 seconds. 
Is it a normal behavior?

CM14.1, Mediatek mt6735, only one module

**Comment by topjohnwu** [comment]
This means the scripts are not executed correctly, need more info to debug

**Comment by avently** [comment]
What can i do?

**Comment by avently** [comment]
This is a stock boot and logs. What an additional information you need?
[magisk.zip](https://github.com/topjohnwu/Magisk/files/645447/magisk.zip)

**Comment by avently** [comment]
@topjohnwu any news?

**Comment by jsaxon2** [comment]
Have you tried with the latest beta yet? Please try that first and if it is still an issue, can you get a logcat of your bootup. Also, you said you only had one module. Which module is it?

**Comment by avently** [comment]
No matter what module I use. I tried only v4a module and the result still the same. Where I can get the latest beta? Could not find it

**Comment by jsaxon2** [comment]
Try latest version from here: https://forum.xda-developers.com/apps/magisk/unofficial-magisk-v10-beta-built-t3521901

**Comment by avently** [comment]
Same result. Log attached
[log.txt](https://github.com/topjohnwu/Magisk/files/680117/log.txt)

**Comment by avently** [comment]
So you closed the issue but leave the problem unresolved?
