### ISSUE TITLE
Magisk v13 170606 doesn't pass safetynet  on Samsung note 3 sm-n9005

### ISSUE THREAD

**Issue by kramer04** [topjohnwu/Magisk#230]
I have Samsung note 3 on custom Rom MM phronesis v6 with lsskernel 3.9

MagiskV13 0606 doesn't install on TWRP 
So I install 0206 then I can install 0606

1) Root is ok

2) I can't pass safetynet at all.
 In log I have this : 
06-07 00:13:35.306   501 13096 E Magisk  : fopen: /magisk/.core/hidelist failed with 2: No such file or directory
I create .core in /magisk

3) so it adds com.google.android.gms.unstable

But I can't pass safetynet

See the log

--------- beginning of system
--------- beginning of main
10-23 09:18:14.483   248   248 D Magisk  : client: connect fail, try launching new daemon process
10-23 09:18:14.780   251   251 I Magisk  : Magisk v13.170606 daemon started
10-23 09:18:14.780   251   252 D Magisk  : sepol: Starting large patch thread
10-23 09:18:14.780   251   254 I Magisk  : ** post-fs mode running
10-23 09:18:15.563   251   259 I Magisk  : ** post-fs-data mode running
10-23 09:18:15.613   251   259 I Magisk  : * Mounting /data/magisk.img
10-23 09:18:15.626   251   259 I Magisk  : * Running post-fs-data.d scripts
10-23 09:18:15.630   251   259 I Magisk  : * Loading modules
06-07 00:03:09.869   396   396 D Magisk  : client: connect fail, try launching new daemon process
06-07 00:03:14.286   501   501 I Magisk  : Magisk v13.170606 daemon started
06-07 00:03:14.296   501   791 D Magisk  : sepol: Starting large patch thread
06-07 00:03:14.302   501   501 E Magisk  : mkdir /magisk 493 failed with 17: File exists
06-07 00:03:14.312   501   793 I Magisk  : ** late_start service mode running
06-07 00:03:16.412   501   791 D Magisk  : sepol: Large patch done
06-07 00:03:16.556   501   793 I Magisk  : * Running service.d scripts
06-07 00:03:16.556   501   793 I Magisk  : * Running module service scripts
06-07 00:04:03.636   501  6798 D Magisk  : su: request from client: 12
06-07 00:04:03.636   501  6798 D Magisk  : su: request from uid=[10180] (#1)
06-07 00:04:03.636   501  6799 D Magisk  : su: collector started
06-07 00:04:03.636   501  6798 E Magisk  : stat /data/user/0/com.topjohnwu.magisk failed with 2: No such file or directory
06-07 00:11:54.146   501 12725 D Magisk  : su: request from client: 11
06-07 00:11:54.146   501 12725 D Magisk  : su: request from uid=[10165] (#1)
06-07 00:11:54.146   501 12725 D Magisk  : su: wait_result waiting for 12726
06-07 00:11:54.146 12726 12726 D Magisk  : su: child process started
06-07 00:11:54.146 12726 12726 D Magisk  : su: argc=[2]
06-07 00:11:54.146 12726 12726 D Magisk  : su: argv[0]=[su]
06-07 00:11:54.146 12726 12726 D Magisk  : su: argv[1]=[-v]
06-07 00:11:54.146 12726 12726 D Magisk  : su: cwd=[/]
06-07 00:11:54.146 12726 12726 D Magisk  : su: pts_slave=[]
06-07 00:11:54.149   501 12725 D Magisk  : su: return code to client: 0
06-07 00:11:54.329   501 12729 D Magisk  : su: request from client: 14
06-07 00:11:54.329   501 12729 D Magisk  : su: request from uid=[10165] (#1)
06-07 00:11:54.333   501 12729 D Magisk  : su: wait_result waiting for 12730
06-07 00:11:54.333 12730 12730 D Magisk  : su: child process started
06-07 00:11:54.333 12730 12730 D Magisk  : su: argc=[1]
06-07 00:11:54.333 12730 12730 D Magisk  : su: argv[0]=[su]
06-07 00:11:54.333 12730 12730 D Magisk  : su: cwd=[/]
06-07 00:11:54.333 12730 12730 D Magisk  : su: pts_slave=[]
06-07 00:13:35.226   501 13096 I Magisk  : * Starting MagiskHide
06-07 00:13:35.226   501 13096 D Magisk  : resetprop: New prop [persist.magisk.hide]
06-07 00:13:35.233   501 13096 D Magisk  : resetprop: setprop [persist.magisk.hide]: [1] by property_service
06-07 00:13:35.233   501 13096 I Magisk  : hide_pre_proc: Hiding sensitive props
06-07 00:13:35.233   501 13096 D Magisk  : hide_list: initialize...
06-07 00:13:35.236   501 13096 I Magisk  : hide_list add: [com.google.android.gms.unstable]
06-07 00:13:35.306   501 13096 E Magisk  : fopen: /magisk/.core/hidelist failed with 2: No such file or directory
06-07 00:13:35.306   501 13096 I Magisk  : proc_monitor: init ns=mnt:[4026531840]
06-07 00:13:37.386   501 13096 I Magisk  : proc_monitor: zygote ns=mnt:[4026534526]
06-07 00:14:00.889   501 13096 I Magisk  : proc_monitor: com.google.android.gms.unstable (PID=13143 ns=mnt:[4026534632])
06-07 00:14:00.893 13097 13097 I Magisk  : hide_daemon: Permissive detected, hide the state
06-07 00:14:00.893 13097 13097 I Magisk  : hide_pre_proc: Re-linking /sbin
06-07 00:14:00.896 13097 13097 I Magisk  : hide_daemon: Unmounted (/sbin)
06-07 00:14:00.896   501 13096 D Magisk  : proc_monitor: hide daemon response code: 0
06-07 00:15:13.023   501 13294 D Magisk  : su: request from client: 11
06-07 00:15:13.023   501 13294 D Magisk  : su: request from uid=[10168] (#1)
06-07 00:15:13.029 13295 13295 D Magisk  : su: child process started
06-07 00:15:13.029 13295 13295 D Magisk  : su: argc=[3]
06-07 00:15:13.029 13295 13295 D Magisk  : su: argv[0]=[su]
06-07 00:15:13.029 13295 13295 D Magisk  : su: argv[1]=[-c]
06-07 00:15:13.029 13295 13295 D Magisk  : su: argv[2]=[/system/bin/sh]
06-07 00:15:13.029 13295 13295 D Magisk  : su: cwd=[/]
06-07 00:15:13.029 13295 13295 D Magisk  : su: pts_slave=[]
06-07 00:15:15.586   501 13294 D Magisk  : su: wait_result waiting for 13295
06-07 00:15:35.263   501 13294 D Magisk  : su: Client killed unexpectedly
06-07 00:15:35.263   501 13294 D Magisk  : su: return code to client: 0
06-07 00:15:44.906   501 13526 I Magisk  : * Stopping MagiskHide
06-07 00:15:44.906   501 13526 D Magisk  : resetprop: New prop [persist.magisk.hide]
06-07 00:15:44.913   501 13526 D Magisk  : resetprop: setprop [persist.magisk.hide]: [0] by property_service
06-07 00:15:44.913   501 13096 D Magisk  : proc_monitor: running cleanup
06-07 00:15:44.983 13097 13097 D Magisk  : hide_daemon: received termination request
06-07 00:15:44.989   501 13096 D Magisk  : proc_monitor: terminating...
06-07 00:15:47.519   501 13530 I Magisk  : * Starting MagiskHide
06-07 00:15:47.519   501 13530 D Magisk  : resetprop: New prop [persist.magisk.hide]
06-07 00:15:47.526   501 13530 D Magisk  : resetprop: setprop [persist.magisk.hide]: [1] by property_service
06-07 00:15:47.526   501 13530 I Magisk  : hide_pre_proc: Hiding sensitive props
06-07 00:15:47.526   501 13530 D Magisk  : hide_list: initialize...
06-07 00:15:47.526   501 13530 I Magisk  : hide_list add: [com.google.android.gms.unstable]
06-07 00:15:47.576   501 13530 I Magisk  : proc_monitor: init ns=mnt:[4026531840]
06-07 00:15:47.613   501 13530 I Magisk  : proc_monitor: zygote ns=mnt:[4026534526]
06-07 00:16:42.676   501 13530 I Magisk  : proc_monitor: com.google.android.gms.unstable (PID=13581 ns=mnt:[4026534537])
06-07 00:16:42.676 13531 13531 I Magisk  : hide_daemon: Permissive detected, hide the state
06-07 00:16:42.679 13531 13531 I Magisk  : hide_daemon: Unmounted (/sbin)
06-07 00:16:42.679   501 13530 D Magisk  : proc_monitor: hide daemon response code: 0
  

_Sent from my Samsung SM-N930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by TheComputerGuy96** [comment]
@kramer04 Try to turn off and on Magisk Hide

**Comment by topjohnwu** [comment]
Please don't report SafetyNet related issues unless you provide an improvement to the hide mechanism, thanks
