### ISSUE TITLE
New Magisk Manager Canary does not work repackaged

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#2301]
Zenfone 4, Android 9.0 stock 
After upgrading over the old repackaged version, Magisk Manager is looping on the "Upgrade to full Magisk Manager to finish the setup" screen.
[Log_2020-01-22_20-26-39.txt](https://github.com/topjohnwu/Magisk/files/4100625/Log_2020-01-22_20-26-39.txt)

When doing a clean install of the new Magisk Manager and trying to repackage it, there is a toast that the process has failed.
[Log_2020-01-22_20-41-05.txt](https://github.com/topjohnwu/Magisk/files/4100632/Log_2020-01-22_20-41-05.txt)

**Comment by linuxandria** [comment]
I can't repacke it all so ig your issue is an improvement 😝

**Comment by kam821** [comment]
+1
same situation on Mi 8 / MIUI11 (xiaomi.eu/ /Android 10.
Looks like canary stub is broken, changing repo to Canary (debug) before hide Manager fix that, but there is another problem with storage access privilege.
There are two identical "Storage" in app privileges, and Manager itself asking over again about permit access to storage while trying to Install Magisk/module from sdcard.

**Comment by Jon8RFC** [comment]
I had the same issue with the looping of "upgrade to full" with magisk hidden.  I uninstalled manager via android (not magisk), installed manager stable, but my modules list was empty despite modules still running, so I uninstalled manager stable (via android, not magisk) and installed magisk canary, and my modules reappeared.  I then installed magisk and it patched successfully.  Cannot repackage and hide magisk, however.

Pixel 4
QQ1B.200105.004

**Comment by BilliTheKid** [comment]
> I had the same issue with the looping of "upgrade to full" with magisk hidden. I uninstalled manager (via android, not magisk), installed manager stable, but my modules list was empty despite modules still running, so I uninstalled manager stable (via android, not magisk) and installed magisk canary, and my modules reappeared. I then installed magisk and it patched successfully. Cannot repackage and hide magisk, however.
> 
> Pixel 4
> QQ1B.200105.004

Everytime i press the module button on the new UI it keeps crashing.

**Comment by BilliTheKid** [comment]
> Zenfone 4, Android 9.0 stock
> After upgrading over the old repackaged version, Magisk Manager is looping on the "Upgrade to full Magisk Manager to finish the setup" screen.
> [Log_2020-01-22_20-26-39.txt](https://github.com/topjohnwu/Magisk/files/4100625/Log_2020-01-22_20-26-39.txt)
> 
> When doing a clean install of the new Magisk Manager and trying to repackage it, there is a toast that the process has failed.
> [Log_2020-01-22_20-41-05.txt](https://github.com/topjohnwu/Magisk/files/4100632/Log_2020-01-22_20-41-05.txt)

Yep getting the same
![Screenshot_20200124-172104](https://user-images.githubusercontent.com/56843472/73092738-11741d80-3ed5-11ea-8744-8a25171b60d3.png)

**Comment by Didgeridoohan** [comment]
Has anyone with this issue tried disabling Play Protect when trying to hide the Manager, or if that doesn't work try with setting SELinux to permissive?

**Comment by Scrumplex** [comment]
Disabling Play Protect does not fix the issue. As well as running `setenforce 0` doesn't fix the issue

**Comment by radioactiv** [comment]
ADB Logcat from the "Install full version" loop:

```01-24 14:20:21.432 15539 15539 I AppLifecycleTracker: App transition to foreground
01-24 14:20:21.433   816   816 D Zygote  : Forked child process 6096
01-24 14:20:21.438  1336  1365 I ActivityManager: Start proc 6096:com.A.z.rbv5.M.C5O2m:remote/u0a208 for activity {com.A.z.rbv5.M.C5O2m/a.r}
01-24 14:20:21.452  6096  6096 E .M.C5O2m:remot: Not starting debugger since process cannot load the jdwp agent.
01-24 14:20:21.480  6096  6096 W .M.C5O2m:remot: resources.arsc in APK '/data/app/com.A.z.rbv5.M.C5O2m-e8hYLcqZjvVZFIHXN5tJgA==/base.apk' is compressed.
01-24 14:20:21.483  6096  6096 D MMStub  : a.y
01-24 14:20:21.484  6096  6096 W .M.C5O2m:remot: Unsupported class loader
01-24 14:20:21.527  6096  6096 E MMStub  : dyn load
01-24 14:20:21.527  6096  6096 E MMStub  : java.lang.NoSuchMethodException: a.e.<init> [class java.lang.Object]
01-24 14:20:21.527  6096  6096 E MMStub  : 	at java.lang.Class.getConstructor0(Class.java:2332)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at java.lang.Class.getConstructor(Class.java:1728)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at a.g.attachBaseContext(:5)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at android.app.Application.attach(Application.java:351)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at android.app.Instrumentation.newApplication(Instrumentation.java:1156)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1218)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at android.os.Looper.loop(Looper.java:214)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at java.lang.reflect.Method.invoke(Native Method)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-24 14:20:21.527  6096  6096 E MMStub  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-24 14:20:21.532  6096  6096 D MMStub  : a.r
01-24 14:20:21.532  6096  6096 D MMStub  : create a.r
01-24 14:20:21.534  1336  4387 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10008000 pkg=com.A.z.rbv5.M.C5O2m cmp=com.A.z.rbv5.M.C5O2m/a.z} from uid 10208
01-24 14:20:21.540  1336  4387 W ActivityTaskManager: Duplicate finish request for ActivityRecord{4f0813f u0 com.A.z.rbv5.M.C5O2m/a.r t702 f}
01-24 14:20:21.541  6096  6096 I .M.C5O2m:remot: System.exit called, status: 0
01-24 14:20:21.542  6096  6096 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
01-24 14:20:21.542  1336  1359 E system_server: Invalid ID 0x00000000.
01-24 14:20:21.558  1336  2793 I ActivityManager: Process com.A.z.rbv5.M.C5O2m:remote (pid 6096) has died: fore TOP 
01-24 14:20:21.560  1336  1366 I libprocessgroup: Successfully killed process cgroup uid 10208 pid 6096 in 0ms
01-24 14:20:21.560   816   816 I Zygote  : Process 6096 exited cleanly (0)```

**Comment by Tornado15550** [comment]
Setting the update channel to Canary (Debug) does fix repackaging of Manager and also allows installation of the stub APK (stub-debug.apk).

**Comment by diareuse** [comment]
@topjohnwu any chance this https://github.com/topjohnwu/Magisk/commit/c011f6b0b213f1f5950c1a5b2c409b302b4e462d could fix the issue?

**Comment by neekless** [comment]
Still failing with 272

**Comment by lss4** [comment]
Same here. Just tried the canary update 1e2de1bb and Hide Magisk Manager still fails here.

**Comment by diareuse** [comment]
It doesn't fail when I build my own apk from source though 🤔 Ugh

**Comment by KaMyKaSii** [comment]
@topjohnwu still having the same issue
[Log_2020-01-27_14-02-28.txt](https://github.com/topjohnwu/Magisk/files/4118335/Log_2020-01-27_14-02-28.txt)

**Comment by kam821** [comment]
There is one workaround, install full debug apk, then change repo into standard Canary and Hide Manager.
Like before - hide function is working only on debug apk, but in previous version changing to canary before hide Manager causes looping on "Upgrade to full", now its working.

**Comment by KaMyKaSii** [comment]
Working now, thanks!
