### ISSUE TITLE
Magisk not working after reboot

### ISSUE THREAD

**Issue by 4n3y3** [topjohnwu/Magisk#2307]
Phone: Huawei P20 Lite
ROM: Omni
Magisk: 20.3

Downloaded the Magisk.zip file through Magisk manager.
Flashing the Magisk zip using TWRP is success.
But rebooting to system showing Magisk isn't installed.

So I was to try flash it again. But booting TWRP is failed.
It ended up booting to system. At this time Magisk manager showing it as installed.

To be concluded: 
1) Rebooting to system will delete Magisk root.
2) Rebooting to recovery (TWRP) will fail and boot to system. In that case Magisk manager saying root installed

Any solution to make root access stable and keep TWRP in recovery partition?

**Comment by topjohnwu** [comment]
Please read instructions to install Magisk on Huawei devices without using TWRP
