### ISSUE TITLE
'LG ThinQ' app can detect a device has been rooted even with Magisk Hide on

### ISSUE THREAD

**Issue by ashmandias** [topjohnwu/Magisk#2308]
I am unable to use the LG ThinQ app -- it immediately closes the app with a message that their app cannot run on rooted devices. In talking with support, they admitted that their application looks to see if any root related apps are installed.  I have uninstalled 'Root Explorer' and 'Root Checker Basic', the only two other root related apps I have, and their app still refuses to run. 

It seems likely that they are seeing Magisk Manager. I'm reporting this in the hope that someone else can find a way to hide root from this app -- and any app that is using the same detection garbage.

**Comment by ashmandias** [comment]
I'd like to add that using the random name option in Magisk does not seem to work. Not sure what they are seeing.

**Comment by Fox2Code** [comment]
In the Magisk Manager settings you have the option to hide MagiskManager
Please enable this option if you don't want MagiskManager to be detected

**Comment by ashmandias** [comment]
That's already enabled.

**Comment by skittles9823** [comment]
What modules do you have installed? I'd be very surprised if they were detecting a repackaged magisk manager itself.

Also when you repackaged did you change the app name to something completely unrelated to magisk or manager? For example I change my manager name to emojis.

**Comment by ashmandias** [comment]
I did have it named 'Manager' -- I will give changing it a try.

**Comment by Jon8RFC** [comment]
It works.  I use it and also had to figure out why it was difficult.

You either have to end task ThinQ or end task and clear data of ThinQ, after you've renamed Magisk.  I think you can get away with just "end task"ing it.  It checks upon fresh start of the app, if I recall correctly.  If it detected Magisk once, and you hide/repackage Magisk, it goes off of its last state of "Magisk detected", unless you end task ThinQ.

**Comment by Didgeridoohan** [comment]
Besides that we have confirmation that it's not actually an issue, we also have this: https://github.com/topjohnwu/Magisk/issues/1152

Please close this so that John doesn't have to.

**Comment by Massimo-B** [comment]
I can't get "LG ThinQ" starting either. It always reports about the rooted device.
I have Magisk 21.2 (21200) and Manager 8.0.5 (4802). In MagiskHide I have enabled the checkbox for "LG ThinQ". There are also 2 checkboxes enabled for "com.lgeha.nuts" and "ccom.lgeha.nuts:error_activity". I deleted the data and stopped and restarted the app, but it always complains and quits.

**Comment by Massimo-B** [comment]
"LG ThinQ" is stubborn, got it working one time in the past by moving Magisk to internal storage and renaming/repacking the Manager to a different name.
After the renaming I got issues with infinite loop with the dialog of updating. So I removed Magisk completely and flashed it from Recovery. Magisk is now up-to-date (20.0) again and working as usual. But "LG ThinQ" again rejects to start on rooted device. Magisk is installed on internal storage, "LG ThinQ" is on the Hide list, data cleaned, device restarted, still rejecting.
I would need to rename the Manager again, going to the options, "Hide Magisk App"... Now I have 2 Managers, one called Magisk as usual, the other with my new name. The new one leads to the infinite update loop again: "Magisk Manager, Upgrade to complete Magisk manager for completion...download and install?"

**Comment by Massimo-B** [comment]
I updated the module "MagiskHide Props Config" to v5.4.0-v122, now hiding works again.

**Comment by tunastek** [comment]
> I updated the module "MagiskHide Props Config" to v5.4.0-v122, now hiding works again.

Hi can you enligthen us step by step pls. I m trying to figure out too.

**Comment by AltarOfMyEgo** [comment]
> > I updated the module "MagiskHide Props Config" to v5.4.0-v122, now hiding works again.
> 
> Hi can you enligthen us step by step pls. I m trying to figure out too.

Hi @tunastek , I had the same issue but after updating Magisk to 22.1, it does not get detected by LG ThinQ anymore.

Regards,

**Comment by iFA88** [comment]
Hey i have the same issue now with Magisk 25.2, zygisk is enabled and set the module and his submodule to enabled in the denylist. I also installed MagiskHide Props Config v6.1.2 and renamed Magisk to some random word.
Sadly even i clear all data of LG ThinQ and even after reboot says it can not be run on rooted device :S
Any suggestion?

**Comment by Jon8RFC** [comment]
Are you using this as well?
https://github.com/Displax/safetynet-fix/releases
Then reboot

Then clear data for the LG thinq app and try again.

**Comment by iFA88** [comment]
> Are you using this as well? https://github.com/Displax/safetynet-fix/releases I'd undo and then remove magisk props config. Then reboot.
> 
> Then clear data for the LG thinq app and try again.

Thank you very much! Thats solved it!
