### ISSUE TITLE
[Feature] Allow image AVBv1 signing with custom key

### ISSUE THREAD

**Issue by MaxwellDPS** [topjohnwu/Magisk#2323]
Allow image signing with custom keys to follow the User settable root of trust on phones that allow it, ie pixel. Since OTA updates could be patched sigend and installed to slot B with a locked bootloader

https://source.android.com/security/verifiedboot/device-state#user-settable-root-of-trust

## EDIT

Looking into it this should be fairly easy and is super useful, as far as security goes. I dont personally do much Kotlin or android UI dev, but to anyone better with it here is what would be needed.

Looking into it here is where images are signed in [MagiskInstaller.kt](https://github.com/topjohnwu/Magisk/blob/0dc9f5c324e8aeb4223aba343f45e50a1bc8aca3/app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt#L275)
```java
SignBoot.doSignature("/boot", input, out, null, null)
```
note `null, null` -> `x509 , key`
and in the [signboot.java](https://github.com/topjohnwu/Magisk/blob/65eca316359b477f2350e72d7afdaa67af23dd19/signing/src/main/java/com/topjohnwu/signing/SignBoot.java#L97) file its defaulting to the verity keys ie `/keys/verity.x509.pem`
```java
            BootSignature bootsig = new BootSignature(target, signableSize);
            if (cert == null) {
                cert = SignBoot.class.getResourceAsStream("/keys/verity.x509.pem");
            }
            X509Certificate certificate = CryptoUtils.readCertificate(cert);
            bootsig.setCertificate(certificate);
            if (key == null) {
                key = SignBoot.class.getResourceAsStream("/keys/verity.pk8");
            }
```

Now this is where my android programming skills drop, we need a place to select our own cert and key that will pass that location to SignBoot.doSignature in MagiskInstaller.kt
```java
SignBoot.doSignature("/boot", input, out, custom_cert_loc, custom_key_loc)
```

**Comment by linuxandria** [comment]
I'm going to bump this, as I own a pixel 2 xl myself and this would be a nice feature to see although I'm not sure the difficulty in implementation.

**Comment by MaxwellDPS** [comment]
So looking into it it should be fairly easy to implement, just need spot for user to specify DER coded x509 and pks8 Key (unencrypted). and here is[ ASOP's tool](https://android.googlesource.com/platform/system/extras/+/master/verity/BootSignature.java) for this task. to someone more knowledgeable with the code this would be super easy, if I have time I'll submit a push.
on windows it looks like

Signing: `java -jar AOSP_BootSignature.jar /boot magisk_patched.img AVB_KEY.pk8 AVB.der boot_patched_signed.img`

Verifying: `java -jar AOSP_BootSignature.jar -verify boot_patched_signed.img`

**Comment by MaxwellDPS** [comment]
Scratch that, the Boot signing  is implemented [here](https://github.com/topjohnwu/Magisk/blob/master/signing/src/main/java/com/topjohnwu/signing/SignBoot.java). So we just need the ability to use custom certs... This should be easy

**Comment by MaxwellDPS** [comment]
Looking into it here is where images are signed in [MagiskInstaller.kt](https://github.com/topjohnwu/Magisk/blob/0dc9f5c324e8aeb4223aba343f45e50a1bc8aca3/app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt#L275)
```java
SignBoot.doSignature("/boot", input, out, null, null)
```
note `null, null` -> `x509 , key`
and in the [signboot.java](https://github.com/topjohnwu/Magisk/blob/65eca316359b477f2350e72d7afdaa67af23dd19/signing/src/main/java/com/topjohnwu/signing/SignBoot.java#L97) file its defaulting to the verity keys ie `/keys/verity.x509.pem`
```java
            BootSignature bootsig = new BootSignature(target, signableSize);
            if (cert == null) {
                cert = SignBoot.class.getResourceAsStream("/keys/verity.x509.pem");
            }
            X509Certificate certificate = CryptoUtils.readCertificate(cert);
            bootsig.setCertificate(certificate);
            if (key == null) {
                key = SignBoot.class.getResourceAsStream("/keys/verity.pk8");
            }
```

Now this is where my android programming skills drop, we need a place to select our own cert and key that will pass that location to SignBoot.doSignature in MagiskInstaller.kt
```java
SignBoot.doSignature("/boot", input, out, custom_cert_loc, custom_key_loc)
```

**Comment by osm0sis** [comment]
You guys can pretty easily do this from the command line already. :+1: 

```
:/ $ su
:/ # . /data/adb/magisk/util_functions.sh
:/ # find_manager_apk
:/ # eval $BOOTSIGNER
BootSigner <actions> [args]
Input from stdin, outputs to stdout

Actions:
   -verify [x509.pem]
      verify image, cert is optional
   -sign [x509.pem] [pk8] [name]
      sign image, name, cert and key pair are optional
      name should be /boot (default) or /recovery

:/ # eval $BOOTSIGNER -verify < /sdcard/magisk_patched.img
Invalid image: not signed
:/ # eval $BOOTSIGNER -sign < /sdcard/magisk_patched.img > /sdcard/magisk_patched-signed.img
:/ # eval $BOOTSIGNER -verify < /sdcard/magisk_patched-signed.img
Signature is VALID
```

**Comment by linuxandria** [comment]
But a way to do it inline with flashing magisk would be mighty handy

**Comment by osm0sis** [comment]
Why though? I've seen relocked bootloaders fail with anything but images signed using an OEM or verity key, so signing with your own sounds pretty pointless.. 😕

**Comment by digitalcircuit** [comment]
As I have a device that (presumably, not yet gathered the courage to test) supports the ["User-settable root of trust" linked to in the first comment](https://source.android.com/security/verifiedboot/device-state#user-settable-root-of-trust ), I'd like to "install and use custom versions of Android without sacrificing the security improvements of Verified Boot", where custom in this case means "Magisk atop stock."

It's a way of avoiding ["evil maid" attacks](https://en.wikipedia.org/wiki/Evil_Maid_attack ) where [quick physical access compromises your Android device](https://defreez.com/articles/android-evilmaid.html ).  Granted, with Magisk seeming to not support signed modules, this may be less effective at preventing all unexpected (i.e. not user-chosen) tampering, but I'd suspect this at least raises the barrier.

**Comment by vvb2060** [comment]
`avb_custom_key` need avb2.0, Magisk BootSigner use avb1.0

**Comment by vvb2060** [comment]
https://android.googlesource.com/platform/external/avb/+/master/avbtool.py
