### ISSUE TITLE
Issues loading custom Kernals on new build

### ISSUE THREAD

**Issue by BilliTheKid** [topjohnwu/Magisk#2324]
New Canary build causing bootloops when loading custom kernals.

**Comment by linuxandria** [comment]
Sounds like your kernel developer needs to update with the latest magisk changes, eg overlay.d, or your kernel is just plain broken. Check for updates from your maintainer.

Try permissive selinux if all else fails.

All being said, most likely not a magisk issue

**Comment by BilliTheKid** [comment]
Selinux Manager is broken in Magisk Canary so this won't work.
