### ISSUE TITLE
New build not hiding banking app.

### ISSUE THREAD

**Issue by BilliTheKid** [topjohnwu/Magisk#2325]
This worked flawlessly but now even when bidding is triggering Root in my banking app.

**Comment by linuxandria** [comment]
#1152 
Also see https://www.didgeridoohan.com/magisk/MagiskHide

Highly recommend closing

**Comment by BilliTheKid** [comment]
I've has root for years with Magisk and I'm well aware what you mentioned. There has been now issue with it up till the Debug build and new manager hence why I brought it to your attention.
