### ISSUE TITLE
Selinux Manager not working on new build

### ISSUE THREAD

**Issue by BilliTheKid** [topjohnwu/Magisk#2326]
Module loads but doesn't appear and does not switch

**Comment by linuxandria** [comment]
Sounds like the maker of the module needs to update for the latest magisk changes.

Recommend closing as it's not a magisk issue.

**Comment by topjohnwu** [comment]
The module is discontinued.

**Comment by BilliTheKid** [comment]
What's an alternative? Even Selinux app does not work. I'd like to point out all of this was running flawlessly before the new update

**Comment by linuxandria** [comment]
@BillTheKid just use `setenforce 0` as needed from a root (su) shell
