### ISSUE TITLE
Various modules crashing tab on New build

### ISSUE THREAD

**Issue by BilliTheKid** [topjohnwu/Magisk#2327]
It seems some but not all modules and mods are crashing the modules tab. When uninstalled it reopens no problem. Culprits so far are Viber, Dolby and the GCAM mod.

**Comment by topjohnwu** [comment]
Fixed

**Comment by pbanj** [comment]
I just updated and it's still crashing

**Comment by undermark5** [comment]
I have updated as well, still having crashes. I don't think I've got any of those modules installed either.

**Comment by linuxandria** [comment]
Can everybody who's having issues please provide:

ROM
Device
Modules installed
If you theme manager using substratum or similar
Logcat of the issue
Magisk logs (taken from canary debug update channel)

Personally never had the issue but I have a hunch it may be ROM related.

**Comment by pbanj** [comment]
Pixel 3a stock with Magisk.
![https://cdn.discordapp.com/attachments/399670410565910529/671046243480502281/Screenshot_20200126-123743.png](url)
Swift installer
As for logs I'll grab them later today

**Comment by pbanj** [comment]
Update today seems to have fixed it

**Comment by pbanj** [comment]
It's doing it again lol. I'll grab logs later today when i have some time.
