### ISSUE TITLE
Root can be detected in work profile

### ISSUE THREAD

**Issue by yangzhaofeng** [topjohnwu/Magisk#2340]
According to #1888 , I installed Magisk Manager in work profile and switched my multi-user mode to "Device owner managed" and hided root for the apps in Magisk Manager in work profile. However, the apps can also ask for root access, which is to be granted or denied in main profile. In addition, the Magisk hide in "User-Independent" mode also does not work. Even Terminal Emulator can ask for root access with a single "su" in work profile.

I use Android 10 on Google Pixel (2016). The Magisk version is 20.3 and manager version is 7.5.1(267) and the package name is not original (generated by "hide magisk manager").

**Comment by Fox2Code** [comment]
A pull request is already waiting to fix this issue #1840
Will probably be fixed in the next Magisk release

**Comment by goodwin** [comment]
A pull request is waiting for more than 4 months. I really hope it will be included at all somewhere in time :-D

**Comment by topjohnwu** [comment]
#2181
