### ISSUE TITLE
Can't Hide Magisk Manager

### ISSUE THREAD

**Issue by gudenau** [topjohnwu/Magisk#2344]
Since the ugly UI update it is not possible to hide Magisk Manager without using the debug build of Magisk Manager. It fails with a generic message of "Failed to hide Magisk Manager" without a message in the logs.

Also when using the debug build and having it hidden "Magisk Manger" contains random characters.

![Screenshot_20200127-153921](https://user-images.githubusercontent.com/5642329/73216366-7f118b00-411b-11ea-83ab-7e7c06158da9.png)

**Comment by kam821** [comment]
Already mentioned in: #2301

**Comment by gudenau** [comment]
> Already mentioned in: #2301

That one is closed though.

**Comment by Jon8RFC** [comment]
Updated to 272 and it fails to hide. Uninstalled and installed 272 and it still fails.

**Comment by lss4** [comment]
Can confirm. Setting channel to Canary Debug, clear repo cache, then download and install Magisk Manager (which will be the debug build), and I can successfully hide the Manager.

As for showing random characters, I think it's merely an aesthetic effect simply telling you that the Manager has been hidden, with no real meaning.

**Comment by topjohnwu** [comment]
Fixed in 1d89fe503ba07f9dca15dc9c952b5b725e8ffb96
