### ISSUE TITLE
No Uninstall Button

### ISSUE THREAD

**Issue by gudenau** [topjohnwu/Magisk#2345]
On the new UI there isn't an uninstall button.
![Screenshot_20200127-153921](https://user-images.githubusercontent.com/5642329/73216461-a6685800-411b-11ea-8ea9-3dfc68f2e03c.png)

**Comment by xerta555** [comment]
As the uninstall button is on button of the screen, we suppose that you don't have scroll down?

**Comment by neekless** [comment]
Surprise

![ScreenRec_20200128_093259](https://user-images.githubusercontent.com/22426822/73228895-c9bcf280-416f-11ea-91f7-7e37f25d4f9a.gif)

**Comment by gudenau** [comment]
> Surprise
> 
> ![ScreenRec_20200128_093259](https://user-images.githubusercontent.com/22426822/73228895-c9bcf280-416f-11ea-91f7-7e37f25d4f9a.gif)

How did you get it to scroll? It doesn't scroll for me at all.

**Comment by RikkaW** [comment]
@topjohnwu @diareuse The problem does exist. The auto-hide of the app bar and bottom bar requires scrolling a certain distance, so it's possible the content height is not enough to trigger the auto-hide.

**Comment by diareuse** [comment]
> @topjohnwu @diareuse The problem does exist. If the content height is a little lower to be scrollable, the bottom bar will cover the uninstall button.

The homepage will be rewritten anyways. And the bottombar just hides the text, the button itself is full-width, so for the time being it can be uninstalled even on those particular devices.
