### ISSUE TITLE
Fatal error after installing on Xiaomi mix2s

### ISSUE THREAD

**Issue by qq3092547800** [topjohnwu/Magisk#2347]
Restart after installation cannot enter the desktop and the black screen is repeated all the time
ROM:https://hugeota.d.miui.com/20.1.16/miui_MIMIX2S_20.1.16_22b50df6b0_10.0.zip

**Comment by qq3092547800** [comment]
以上為機翻...希望能解決

**Comment by topjohnwu** [comment]
Please use the latest canary, this issues if fixed
