### ISSUE TITLE
Hiding is no longer fully functioning with HP WU game

### ISSUE THREAD

**Issue by andyrozman** [topjohnwu/Magisk#2348]
I am using Magisk since I started using new phone (about 2 years now)... In july 2019 I started having problem with "Harry Potter Wizards Unite" game, and I started using hide functionality... It worked great, until yesterday, when new version came out. It seems they extended their root check, and it can now detect root (I doesn't say that, it just says Device incompatible).

If fix (or workaround) could be found I would be very thankful...

I followed instructions to the letter and it worked until new version was released (2.9.0, 27.1.2020), so its not a user error.

**Comment by topjohnwu** [comment]
#1152
