### ISSUE TITLE
Magisk > 20.1 bootloops Asus Zenfone Zoom (x86 CPU) - some logs provided

### ISSUE THREAD

**Issue by tcmaps** [topjohnwu/Magisk#2356]
Versions 20.2, 20.3 and 20.4 / canary+debug only boot up to the pin code prompt, then reboot.

Version 20.1 and below work.

magisk.log is almost empty:
`
--------- beginning of main
--------- beginning of system
01-29 14:02:27.580   334   334 I Magisk  : Magisk v20.4-0dc9f5c3(20303) daemon started  
01-29 14:02:27.650   334   334 I Magisk  : * Device API level: 23  
01-29 14:02:27.650   334   341 I Magisk  : ** late_start service mode running  
01-29 14:03:07.482   334  1779 I Magisk  : ** boot_complete triggered  
`
[magisk.log](https://github.com/topjohnwu/Magisk/files/4128231/magisk.log)

[kmsg](https://github.com/topjohnwu/Magisk/files/4128234/kmsg.log)

[console-ramops](https://github.com/topjohnwu/Magisk/files/4128237/console-ramops.log)

[recovery last_log](https://github.com/topjohnwu/Magisk/files/4128242/recovery_last.log)

[recovery log](https://github.com/topjohnwu/Magisk/files/4128244/recovery.log)

adb logs can't be obtained while booting, sh stays on 'wating for device'

Didgeridoohan's bootlog script in post-fs-data also hasn't save anything.

**Comment by linuxandria** [comment]
Post-fs-data is never triggered from looks of magisk log
Place the script in service.d ensuring 755 permissions

**Comment by tcmaps** [comment]
Placed the script in /data/adb/service.d/, chmod 755, +x but still no log file neither in /sdcard nor /cache

**Comment by linuxandria** [comment]
Ouch, that means magisk is almost completely failing to initialize

**Comment by topjohnwu** [comment]
Fixed in #2386
