### ISSUE TITLE
Magisk Modules Incompatible with overlayfs

### ISSUE THREAD

**Issue by androidacy-user** [topjohnwu/Magisk#2359]
I'm running OxygenOS 10.3.0 on a OnePlus 7 Pro, and the Debloat module is not replacing files in /product correctly.

The `find` command indicates it's doing what it should (eg $MODPATH/product/app/badapp/.replace) and magisk logs indicate it was replaced.

However, the app is still installed as a system app and using a root file manager to examine the folders, the actual contents (not what should be magic mounted) shows up. 

Logs to follow.

_Sent from my OnePlus 7 Pro using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by linuxandria** [comment]
[Magisk Logs](https://drive.google.com/file/d/1-3VuA7gMeuW4itqGHWEXyTrYIuF4aeBi/view?usp=drivesdk)
[Boot log](https://drive.google.com/file/d/1-2D6FcaoWPgrVzfI9scEUj7XWsPZNC4V/view?usp=drivesdk)

_Sent from my OnePlus 7 Pro using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by skittles9823** [comment]
Might want to give this module an install and see if that helps.

https://github.com/Magisk-Modules-Repo/overlayfix

**Comment by linuxandria** [comment]
Refuses to install saying it's not needed

**Comment by linuxandria** [comment]
Weird it installed this time around.
However still no go.

**Comment by skittles9823** [comment]
Hmm, must be a different issue to the one I was thinking about then.

**Comment by Didgeridoohan** [comment]
@linuxandria What's the output of `cat /proc/mounts`?

**Comment by linuxandria** [comment]
[This](https://drive.google.com/file/d/1-KyfIuKYOqmQ4JPSKTcw8Lyx1RTLwhLS/view?usp=drivesdk)

**Comment by Didgeridoohan** [comment]
From what I can see it is the same issue that @Zackptg5's script is supposed to fix. You have an overlay of /product after the Magisk mounts, so nothing Magisk related is available in /product...

**Comment by linuxandria** [comment]
I flashed said module as I already said and it didn't help

**Comment by Zackptg5** [comment]
My module currently doesn't address replacements. Overlay mounts work by combining everything present in the lowerdirs. If you look at your mounted /product folder, you'll see the . replace file from your module and the original files as well.

I'm working on an update to address this. Hoping to get it working right this weekend when I get the chance to work on jt5

**Comment by linuxandria** [comment]
@Zackptg5 nonetheless would be nice to see magisk natively support `overlayfs` as I'm sure with more devices launching with 10 (and obviously some upgrading to it) will utilize it for sale of RO system setups. 

Interestingly enough if I'm not mistaken, OnePlus has made /product entirely an `overlayfs`. Looks like it is actually located in /system/product

**Comment by Zackptg5** [comment]
@linuxandria I would too. The trouble with oneplus's overlay implementation is that they do it when boot completes which is why magisk mounts are all effectively overwritten

**Comment by Zackptg5** [comment]
@linuxandria Can you give this a go? Works fine for me
[Overlay_Mount_Fix_v1.2.zip](https://github.com/topjohnwu/Magisk/files/4143318/Overlay_Mount_Fix_v1.2.zip)

**Comment by linuxandria** [comment]
@Zackptg5 well I no longer had to worry about it replacing files correctly.....
.... because my device stopped booting.

About 2-3 sec into the boot process it completely froze, then would reboot, then would freeze again until I forced rebooting to bootloader via key combo.

**Comment by Zackptg5** [comment]
From the overlay zip? It's just a service.d script that doesn't even run until it's about booted. Ugh, I don't get how there's such varying results with this

**Comment by linuxandria** [comment]
@Zackptg5 I have absolutely no idea what OnePlus did here but you're script broke boot so badly my logging script never starts - meaning I don't even have logs.

Initially I blamed it on EdXposed because I just updated it but uninstalling that did no good.

And ofc disabling yours didn't completely work b/c you use /data/adb/service d. But yeah, stumps me as to why that'd kill the device too.

**Comment by Zackptg5** [comment]
@linuxandria
Just updated overlay fix in the mag repo. Completely redone from last version, no issues reported with it so give it a shot (it's different from the betas I dropped on TG).

**Comment by linuxandria** [comment]
@Zackptg5 looks ok. Hopefully @topjohnwu can figure out a native fix.

**Comment by osm0sis** [comment]
Any improvement on this with the new module logic in 20405?

**Comment by linuxandria** [comment]
> Any improvement on this with the new module logic in 20405?

No improvement unfortunately

**Comment by Kein** [comment]
Is my issue related? I'm running MIUI 11/pie on Note7, after installation of a single module
https://github.com/Magisk-Modules-Grave/gjf_bt
I no longer can mount anything for rw. logcat has some overlay-related log entries when remount requested

**Comment by techIndia-hacker** [comment]
Any solution guys?

**Comment by techIndia-hacker** [comment]
Ok the module works fine. Thanks

**Comment by osm0sis** [comment]
Could be worth trying with 24304, original init handles a lot more now

**Comment by HuskyDG** [comment]
This problem is not fixed yet

**Comment by osm0sis** [comment]
K. Can you provide fresh logs of Magisk interacting with overlayfs and failing to work as intended?

**Comment by HuskyDG** [comment]
> K. Can you provide fresh logs of Magisk interacting with overlayfs and failing to work as expected?

This is not my problem, but someone on Telegram reports to me.
https://t.me/HuskyDG/57

**Comment by tehcneko** [comment]
Magisk breaks pangu overlays in A13 based MIUI.

overlay on /system/app type overlay (ro,seclabel,relatime,lowerdir=/mnt/vendor/mi_ext/system/app/:/product/pangu/system/app/:/system/app)
overlay on /system/framework type overlay (ro,seclabel,relatime,lowerdir=/product/pangu/system/framework/:/system/framework)
overlay on /system/etc/sysconfig type overlay (ro,seclabel,relatime,lowerdir=/mnt/vendor/mi_ext/system/etc/sysconfig/:/system/etc/sysconfig)
overlay on /system/etc/permissions type overlay (ro,seclabel,relatime,lowerdir=/mnt/vendor/mi_ext/system/etc/permissions/:/product/pangu/system/etc/permissions/:/system/etc/permissions)
