### ISSUE TITLE
Allow adding genfscon statements via magiskpolicy/sepolicy rules

### ISSUE THREAD

**Issue by AuroraWright** [topjohnwu/Magisk#2367]
I have a (currently private) module which uses magisk's custom .rc feature to run a sh script (I uploaded it here https://hastebin.com/bexodacele.bash ) on late-init, which as you suggested in this issue: https://github.com/topjohnwu/Magisk/issues/875 reimplements the sepolicy building in bash using `secilc` and a custom .cil file I provide (uploaded it here: https://hastebin.com/wemazihofu.sql ). 

However, the drawback of this is that I have to rebuild a sepolicy from scratch and can't expand the one already loaded in the kernel, and it also now conflicts with Magisk's new `sepolicy.rule` feature, unless I re-implement `sepolicy.rule` loading as well.
It also doesn't work with kernels that only allow loading the sepolicy once.

I would use `sepolicy.rule`but, in order to get FUSE filesystems working properly, the following genfscon statement is needed: `genfscon fuseblk / u:object_r:vfat:s0`
and Magisk currently lacks the ability to inject `genfscon`statements.

I'm aware it's a pretty niche request but it'd be nice if Magisk eventually supported doing that natively.

**Comment by topjohnwu** [comment]
@AuroraWright sure thing, I'll look into supporting this feature once I got time :)

**Comment by topjohnwu** [comment]
@AuroraWright just checked, this feature seems pretty straightforward to implement :)

**Comment by AuroraWright** [comment]
Thanks, much appreciated! ^^
