### ISSUE TITLE
Dialog boxes no longer centered

### ISSUE THREAD

**Issue by neekless** [topjohnwu/Magisk#2369]
Manager 273 Dialog boxes in many places are no longer centralized
![Screenshot_20200131-092755](https://user-images.githubusercontent.com/22426822/73505080-58787c00-43c9-11ea-8bcd-88236536bc3b.jpg)
![Screenshot_20200131-092912](https://user-images.githubusercontent.com/22426822/73505084-5a423f80-43c9-11ea-876b-63fcb7acbba1.jpg)
![Screenshot_20200131-092955](https://user-images.githubusercontent.com/22426822/73505089-5d3d3000-43c9-11ea-8a24-fcf884a86af7.jpg)

**Comment by topjohnwu** [comment]
@diareuse I can also confirm this too

**Comment by diareuse** [comment]
Yeeees. Love the constraint layout updates that _fix_ one thing and completely obliterate another. Ugh
