### ISSUE TITLE
Pokemon Go doesn't work with hide root

### ISSUE THREAD

**Issue by szamuka** [topjohnwu/Magisk#237]
From yesterday Pokemon Go doesn't work with hide root

**Comment by szamuka** [comment]
Xiaomi Redmi Note 3
Android 6.0.1

**Comment by Didgeridoohan** [comment]
Yes, we know. No need to open an issue about it...

If you take a look at the Magisk forum over at XDA you'll see that there's currently nothing else that matters except the fact Google updated SafetyNet and "broke" Magisk Hide.

It's already been dealt with on the developers side and we'll see a new release when it's ready.

Meanwhile you can try enabling Core only mode and possibly disable systemless hosts in the Manager settings.

**Comment by multi-rom-user** [comment]
The current fix until magisk devs can find the proper code to use is to enable core only mode in magisk and reboot your device. You will then (or should be) be passing CTS so those apps don't know you are rooted. 

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Leeo97one** [comment]
It works for me with Magisk Core only.

**Comment by sou7611** [comment]
I've been trying to solve this on a nexus 9.

Have no option, anywhere, to even select "Core Only", as of latest builds.  It's gone.

On the Nexus 9, safetynet is completely broken, even with the latest v13 build.

Same exact build, on another device running marshmallow works flawlessly for safetynet.

**Comment by topjohnwu** [comment]
Please don't report SafetyNet related issues unless you provide an improvement to the hide mechanism, thanks
