### ISSUE TITLE
Magisk Not Requesting Storge Permission for Modules

### ISSUE THREAD

**Issue by gudenau** [topjohnwu/Magisk#2383]
Magisk doesn't request/automatically grant/bypass the need for the storage permission when downloading a module, causing downloads to fail.

![Screenshot_20200201-135602](https://user-images.githubusercontent.com/5642329/73598195-bc4e9200-44fa-11ea-9ae1-b36b74420b21.png)

![Screenshot_20200202-093645](https://user-images.githubusercontent.com/5642329/73610670-93340d00-459f-11ea-83a7-de658e0ab614.png)

**Comment by diareuse** [comment]
Did you try granting the storage permission by any chance?

**Comment by gudenau** [comment]
Oh, that's the issue then.

Guess I'm going to have to change the issue.

**Comment by osm0sis** [comment]
@diareuse is this confirmed still need to be fixed upstream from the current Canary?

**Comment by diareuse** [comment]
Nah, the PR has been merged. Upstream has this fixed in https://github.com/topjohnwu/Magisk/commit/88d917b66264aa2f0f49f4ae5c4e0d08ca83a1d6

**Comment by Utkarshjadon** [comment]
Can you please tell me which rom and version are you using in m facing the exact same problem but It says that no permission needed by magisk and it doesn't asks for storage

**Comment by Utkarshjadon** [comment]
Can you please tell me which rom and version are you using in m facing the exact same problem but It says that no permission needed by magisk and it doesn't asks for storage 😭🥲😥

**Comment by Drygord** [comment]
This drained hours of my time trying to resolve. Sigh. 

The entire purpose of rooting a phone is to get enhanced permissions. NOT to have to ask and grant permissions for things that were perfectly accessible before rooting.
