### ISSUE TITLE
Hide Magisk Manager app prompting to upgrade to full Magisk Manager 7.5.1

### ISSUE THREAD

**Issue by davex2012** [topjohnwu/Magisk#2384]
Hei, When trying to hide Magisk Mangager to Manager i get upgrade to full magisk manager to finish the setup. Any idea how to fix this. 
![Screenshot_20200201-222117](https://user-images.githubusercontent.com/15570883/73599624-b3cf7900-4545-11ea-8a8c-6521491e3222.jpg)
![Screenshot_20200201-222137](https://user-images.githubusercontent.com/15570883/73599625-b3cf7900-4545-11ea-910e-9e8ece6937de.jpg)
[magisk_log_20200201_224138.log](https://github.com/topjohnwu/Magisk/files/4143283/magisk_log_20200201_224138.log)

**Comment by linuxandria** [comment]
Normal behavior.

Recommend closing.
