### ISSUE TITLE
Why is Magisk hide unmounting /pds?

### ISSUE THREAD

**Issue by pizzadude** [topjohnwu/Magisk#239]
On my Moto G 2014 running Lineage OS, with Magisk v13, it says in the log that Magisk hide is unmounting /pds. 

/pds is used for things such as the IMEI.

Is this supposed to happen? It seems kind of risky to mess with the IMEI partition.

**Comment by topjohnwu** [comment]
Is it still doing this?

**Comment by pizzadude** [comment]
I don't think so. It doesn't say it's unmounting /pds in the Magisk log anymore.

_Sent from my Motorola Moto G 2014 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
