### ISSUE TITLE
fc on direct install in Magisk Manager

### ISSUE THREAD

**Issue by martyfender** [topjohnwu/Magisk#2395]
Latest Canary mm fc's when choosing direct install on the black flash screen, on both my Nextbook Ares 8A, x86, Android 6.0.1 tablets and my Onn 8 Android 9 tablet. A filtered logcat from the Android 9 tablet is attached. I tried deleting app data and cache, also.
[Log_2020-02-03_15-57-44.txt](https://github.com/topjohnwu/Magisk/files/4150645/Log_2020-02-03_15-57-44.txt)

[magisk_log_20200203_181036.log](https://github.com/topjohnwu/Magisk/files/4150651/magisk_log_20200203_181036.log)

Update: On my Android 9 device, I keep getting additional setup required and the system reboots until the next time it does it again and it has done this quit a few times with this build, throughout the day.
Thanks

**Comment by shakalaca** [comment]
Would you please grab full logcat instead of filtered one ? :)

**Comment by martyfender** [comment]
[Log_2020-02-04_08-41-39.txt](https://github.com/topjohnwu/Magisk/files/4153631/Log_2020-02-04_08-41-39.txt)

**Comment by martyfender** [comment]
[Log_2020-02-04_08-41-39.zip](https://github.com/topjohnwu/Magisk/files/4155884/Log_2020-02-04_08-41-39.zip)
