### ISSUE TITLE
Please add legacy theme to future Magisk Manager versions

### ISSUE THREAD

**Issue by deltabravozulu** [topjohnwu/Magisk#2398]
Hi! I really appreciate your creation. I recently updated to MagiskManager-v7.5.2-ed58cf95(274) and it is a very good looking update. 

With that said, like a lot of users, change is difficult for me. I am hoping you can add a theme to the custom theme list that allows a person to utilize Magisk as it was in older versions. It was simple, but it made sense. I can figure out the new setup, certainly, but I'd like the option to go back.

**Comment by Didgeridoohan** [comment]
https://twitter.com/topjohnwu/status/1220260862436368384?s=20
