### ISSUE TITLE
[FeatureSug][MagiskHide] SEQR root detection still works with magisk Hide enabled

### ISSUE THREAD

**Issue by MaxRink** [topjohnwu/Magisk#240]
As Android Pay is not available in Germany yet our best alternative is an app called SEQR.
But MagiskHide fails to hide Root, so it doesnt work.
looking at logcat, my guess is that SEQR also does a ROM-detection via the display_id, which magioskhiode does not obfuscate ( iirc it fails at anything but user)

**Comment by ckoehnen** [comment]
Is there a process to debug SEQR? E.g. filesystem/api access logging? I don't think SEQR's detection is rom signature related. I think it might be based on some filesystem/folder or configuration modifications rooting causes.

**Comment by MaxRink** [comment]
Well, by a quick look id say the root detection is ahndled inside their cryptoframework
IDA should be able to debug this on an actual device, i dont have a licence atm tho.

**Comment by ninov** [comment]
I had the same problem since I updated SEQR to its newest version.
A workaround is to install an old version of SEQR (if you don't have a backup, try google, but **verify the apk's signature**)

Also, I tried changing ro.build.displayid to something sane, but it didn't help.

**Comment by fblaese** [comment]
The HCE Compliance Checker App (https://play.google.com/store/apps/details?id=com.hce.compliance.checker) might be helpful for further investigation. It should use the same root detection methods.

For me it shows the same error as the updated (06/13/17) Seqr App does in logcat. [Root Management Apps]
For some reason the HCE Compliance Checker doesn't complain about root if it's monitored by strace...

**Comment by Iradj** [comment]
So on my side I've done some researches too and found out some hints maybe. 
- The first thing that i found out is i decompiled the SEQR Version 2.6.23 and 2.6.27 the .23 works with Magisk Hide and the .27 don't. In one smali file that i have found in both, they have pretty much the same root detections (13 root entries ) BUT in the .23 version there is a line with "R_ROOT_BBOX" in the .27 version we don't have the line but instead, we have the R_ROOT_FILES line. 
- I downloaded the Root-Inspector from devadvance repo and hide it with Magisk and on Java level search everything passes except the deamonsu that fails that's something that Magisk still not can Mask apparently but on native library level everything passes.
**SEQR 2.6.23:**
![seqr2 6 23](https://user-images.githubusercontent.com/29755207/27770545-b0fbf656-5f40-11e7-8553-efc8e83e676b.png)
**SEQR 2.6.27:**
![seqr2 6 27](https://user-images.githubusercontent.com/29755207/27770553-ca455580-5f40-11e7-96ef-a87cdf382115.png)
**Root-Inspector:**
![20170702_155810](https://user-images.githubusercontent.com/29755207/27770562-f1b4d65e-5f40-11e7-9752-7929031f297c.png)

**Comment by ms223iu** [comment]
I can confirm everything that @Iradj and @ninov wrote. SEQR v2.6.23 works just fine while v2.6.27 detects modifications/root.  

OxygenOS 4.5.6 (Android 7.1.1)
Magisk 13.3 / MAGISKSU (Passing SafetyNet checks)

Hopefully it's something you guys will have time to look into but going with SEQR v2.6.23 is our best bet at this time. Cheers and thanks a lot!

**Comment by zozanyo** [comment]
Same here with LineageOS 14.1 (7.1.2)...v2.6.23 works... Disabled autoupdate till MagiskHide gets fixed

**Comment by Yakie996** [comment]
someone has a v 2.6.23 apk? please :)

**Comment by BassT23** [comment]
http://www.apkmonk.com/download-app/com.seamless.seqr/3_com.seamless.seqr_2017-05-08.apk/

**Comment by warpi** [comment]
Just downloaded the above mentioned file and I received version 4.6.23. I am using Magisk 13.3 which does work with e.g. Netflix. But SEQR with TAP and PAY function does not work with the latest or the proposed version 4.6.23. Do I do something wrong or is this still a problem with Magisk? I think it is a little bit sad because SEQR is the only mobile payment solution existing and I need root in order to save my battery using "Battery Charge Limit" app.

**Comment by BassT23** [comment]
The link I've posted is 4.6.23
For me it works (Tap and Pay) - tested in several Stores in the last few days.

SGS7 flat
Android 7.0 (Superman 2.6.0)
Magisk 13.3 with Hide
