### ISSUE TITLE
[legacy][jfltexx][SAR] Magisk flashes without error. Manager says 'Not installed'

### ISSUE THREAD

**Issue by dkati** [topjohnwu/Magisk#2401]
Good evening @topjohnwu

i am side, the official maintainer of jfltexx (samsung s4). The ROM has got the SAR philosophy enabled, android 10 rom boots fine but i have issues with magisk.

- TWRP flashes the flashable magisk zip
- zip recognizes the SAR
- but when i be back to runtime, magisk manager says that magisk is not installed.

i talked with dees_troy for a while and we finally said that its not TWRP issue but magisk.

What can i do for u in order to debug that thing ?

Thanks

**Comment by dkati** [comment]
[recovery.log](https://github.com/topjohnwu/Magisk/files/4155377/recovery.log)

**Comment by shakalaca** [comment]
If you can run 'adb root' then grab 
1. output of `adb logcat`
2. output of `dmesg`
3. output of `mount`
4. /cache/magisk.log

**Comment by dkati** [comment]
[mount.log](https://github.com/topjohnwu/Magisk/files/4163643/mount.log)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/4163644/dmesg.log)
[logcat.log](https://github.com/topjohnwu/Magisk/files/4163645/logcat.log)
There is no /cache/magisk dir/file/folder

**Comment by JarlPenguin** [comment]
arm device? If I understand correctly you guys have no ramdisk in the boot image, right?

**Comment by dkati** [comment]
yes its arm32

u mean prebuilt ramdisk inside kernel.img ?

here is the device tree
https://github.com/LineageOS/android_device_samsung_jf-common

**Comment by shakalaca** [comment]
Would you please try the following steps ?
1. Disable CONFIG_ANDROID_FSTAB_FAKE in kernel config
2. Move /vendor/etc/fstab.qcom to / (inside ramdisk)
3. Replace "/vendor/etc/fstab.qcom" with "/fstab.qcom" in init.qcom.rc

If the system can be brought up, then try to patch the boot.img with Magisk again.

**Comment by dkati** [comment]
Rom zip didn't even get flashed. 

Failed to unmount /system. No such volume 

Error creating fstab

**Comment by shakalaca** [comment]
Logs ? You rebuilt TWRP ?

**Comment by dkati** [comment]
I use the latest official Twrp
I rebuilt the whole rom
Logs tomorrow. Thanks for interest

**Comment by dkati** [comment]
I use the latest official Twrp
I rebuilt the whole rom
Logs tomorrow. Thanks for interest

**Comment by dkati** [comment]
[recovery.log](https://github.com/topjohnwu/Magisk/files/4174472/recovery.log)

**Comment by dkati** [comment]
[recovery.log](https://github.com/topjohnwu/Magisk/files/4174478/recovery.log)

**Comment by shakalaca** [comment]
OK don't rebuild the whole rom, replace the kernel in boot.img and add fstab.qcom to ramdisk and see if the phone boots.

**Comment by dkati** [comment]
I don't think it will boot but I will try

**Comment by topjohnwu** [comment]
Close this issue as this has nothing to do with Magisk itself.

ROMs using fake DTB can **NEVER** be supported due the fundamental way how fake DTB works. You either have to use a real DTB so `magiskboot` can patch it, or use a fstab file in the ramdisk so `magiskinit` can patch it at boot time

**Comment by topjohnwu** [comment]
Please check this Twitter thread for more info: https://twitter.com/topjohnwu/status/1226644269261213696

**Comment by shakalaca** [comment]
Just did a quick test on my A-Only SAR device, removing the dt entry in kernel and change

```
/dev/block/platform/msm_sdcc.1/by-name/system         /system      ext4    ro,barrier=1                                                     wait,recoveryonly
```
to 
```
/dev/block/platform/msm_sdcc.1/by-name/system         /system      ext4    ro,barrier=1                                                     wait,recoveryonly,first_stage_mount
```

in /fstab.qcom (Adding fs flag : first_stage_mount) works for me :)

**Comment by dkati** [comment]
@shakalaca please get me at dkatikaridis@gmail.com since this issue is closed
