### ISSUE TITLE
mount system/system_root is incorrect in android-10.0 twrp when dynamic partition

### ISSUE THREAD

**Issue by wzsx150** [topjohnwu/Magisk#2411]
https://github.com/topjohnwu/Magisk/blob/f2d2f28e23af00db4a776a6ded8b0c34f8129f62/scripts/util_functions.sh#L192

when /system is mounted by dm-0, 'mount --move' will be error.
so maybe do umount /system then mount on /system_root. 

--move maybe not support mapper block.

has tested on redmi k30 5G in twrp.

**Comment by aIecxs** [comment]
or use bind mount overlays

**Comment by wzsx150** [comment]
some android-10.0 twrp has be built, so hope as soon as fix this bug

**Comment by linuxandria** [comment]
TWRP does not offically support android 10 and thus no one really knows how they will implement dynamic partitions, thus @topjohnwu may not fix this until then because what if he fixes it for your unofficial TWRP and turns out offically they do it a whole other way?

**Comment by aIecxs** [comment]
lol thats just a simple fix. instead of

    mount --move /system /system_root
we could just

    mount -o bind /system /system_root
    mount -o bind /system_root/system /system

(and umount between to stay clean) btw `mount --move` does not work for me even manually with busybox or toybox. afaik this is for @osm0sis to look at (don't hit me :D

**Comment by osm0sis** [comment]
Sounds more like a bug that your TWRP is using dm-0 mapper instead of actual partition mounting?

**Comment by aIecxs** [comment]
idk... but the --move error is not related to twrp. i get always Invalid argument
<details>
  <summary>Click to expand</summary>

    Microsoft Windows [Version 6.1.7601]
    Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.
    
    C:\Android>adb push C:\Downloads\UPDATE-Busybox.Installer.v1.31.1-ALL-signed.zip /sdcard
    * daemon not running; starting now at tcp:5037
    * daemon started successfully
    C:\Downloads\UPDATE-Busybox.Installer....ed. 7.9 MB/s (5683204 bytes in 0.683s)
    
    C:\Android>adb shell
    CUBOT_KING_KONG:/ $ cd /data/local/tmp
    CUBOT_KING_KONG:/data/local/tmp $ 7z x /sdcard/UPDATE-Busybox.Installer.v1.31.1-ALL-signed.zip busybox-arm
    
    7-Zip [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
    p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,32 bits,4 CPUs LE)
    
    Scanning the drive for archives:
    1 file, 5683204 bytes (5551 KiB)
    
    Extracting archive: /sdcard/UPDATE-Busybox.Installer.v1.31.1-ALL-signed.zip
    --
    Path = /sdcard/UPDATE-Busybox.Installer.v1.31.1-ALL-signed.zip
    Type = zip
    Physical Size = 5683204
    Comment = signed by SignApk
    
    Everything is Ok
    
    Size:       1333952
    Compressed: 5683204
    CUBOT_KING_KONG:/data/local/tmp $ mv busybox-arm busybox
    CUBOT_KING_KONG:/data/local/tmp $ chmod 0755 busybox
    CUBOT_KING_KONG:/data/local/tmp $ su
    CUBOT_KING_KONG:/data/local/tmp # getenforce
    Permissive
    CUBOT_KING_KONG:/data/local/tmp # ./busybox mount -o remount,rw /
    CUBOT_KING_KONG:/data/local/tmp # mkdir /system_root
    CUBOT_KING_KONG:/data/local/tmp # ./busybox mount --move /system /system_root
    mount: mounting /system on /system_root failed: Invalid argument
    255|CUBOT_KING_KONG:/data/local/tmp # ./busybox mount -o bind /system /system_root
    CUBOT_KING_KONG:/data/local/tmp # grep /system /proc/mounts
    /dev/block/platform/mtk-msdc.0/11120000.msdc0/by-name/system /system ext4 ro,seclabel,relatime,data=ordered 0 0
    /dev/block/platform/mtk-msdc.0/11120000.msdc0/by-name/system /system_root ext4 ro,seclabel,relatime,data=ordered 0 0
    CUBOT_KING_KONG:/data/local/tmp # ./busybox umount /system
    umount: can't unmount /system: Device or resource busy
    1CUBOT_KING_KONG:/data/local/tmp # ./busybox umount -l /system
    CUBOT_KING_KONG:/data/local/tmp # grep /system /proc/mounts
    /dev/block/platform/mtk-msdc.0/11120000.msdc0/by-name/system /system_root ext4 ro,seclabel,relatime,data=ordered 0 0
    CUBOT_KING_KONG:/data/local/tmp #

</details>

**Comment by osm0sis** [comment]
You shouldn't be trying to run those commands while booted, they're for recovery setup only.

**Comment by aIecxs** [comment]
Thanks! It came to my mind the moment i had to use lazy umount.. my bad, i run toolbox from mksh in recovery. the reason must be busy /system

yes i have seen the mount function i came across to it when gapps was failing to detect system-as-root (btw maybe it's better to test -a in case build.prop is a symlink) but that's OT here

**Comment by osm0sis** [comment]
#2496 might address this issue.

**Comment by wzsx150** [comment]
> Sounds more like a bug that your TWRP is using dm-0 mapper instead of actual partition mounting?
not a bug.
android-10.0 dynamic partition, the mount partion is not actual partition.
dynamic partition is dm block and linked at  /dev/block/mapper/{$dynamic partition name} by init

**Comment by wzsx150** [comment]
> #2496 might address this issue.

can it fix the bug about mounting dynamic partition?

**Comment by osm0sis** [comment]
TWRP for Android 10 hasn't even been merged yet, so I'm not sure where you're getting this from. Why don't you add the linked changes to the latest Magisk canary zip and test if it helps?

**Comment by wzsx150** [comment]
this is the same as #2496 

but I will make twrp support magisk.zip mount --move

**Comment by osm0sis** [comment]
Cool. I guess you should close this issue then, please. :+1:
