### ISSUE TITLE
Magisk manager displays wrong language randomly

### ISSUE THREAD

**Issue by linuxandria** [topjohnwu/Magisk#2415]
When set to system default language some texts displays in a completely random language. The only default language on my device is English.

Inconsistently reproducible (random in the occurrence).

OnePlus 7 pro, OxygenOS

Repackaged magisk manager v274

![Screenshot_20200207-070433](https://user-images.githubusercontent.com/45006100/74028477-66ee0700-4978-11ea-9d50-f84e308e42e3.jpg)

**Comment by kam821** [comment]
+1
I noticed, that this problem doesn't depend on the language setting, but is completely random.
Sometimes restarting Manager or theme change repairs most or all of the headers/descriptions, sometimes just scroll the screen up and down fix that.

**Comment by JarlPenguin** [comment]
I can also confirm on default system language. Doesn't happen on English for me

**Comment by neekless** [comment]
![Screenshot_20200212-093451](https://user-images.githubusercontent.com/22426822/74295144-0f64e800-4d38-11ea-8267-baa9b77f5406.jpg)

I can reproduce (inconsistently) even when forcing it to English

**Comment by topjohnwu** [comment]
0d7474cc88c8f5412fbbd449ea336b79c4ef77fa
