### ISSUE TITLE
Allow linking against private libraries

### ISSUE THREAD

**Issue by dvc94ch** [topjohnwu/Magisk#2418]
I rooted my phone yesterday for the purpose of installing libraries locally so that I can accelerate my compile/run cycle and implemented a magisk module to do it. I wasn't aware that it wouldn't work on android versions larger than 7. Is there a way to circumvent this? I'm new to android development, I know you don't take kindly to beginner questions so feel free to close without comment if you like.

- https://developer.android.com/about/versions/nougat/android-7.0-changes.html#ndk

Added the library to `/etc/public.libraries.txt`. The library is owned by root:root with 0644 permissions. The only thing that that does is `libnativeloader: Error preloading public library libflutter_engine.so: dlopen failed: library "libflutter_engine.so" not found`. Copying it to the `/data/app/$APPNAME/lib/arm64/` folder works so the library is "ok"

**Comment by topjohnwu** [comment]
Unfortunately, this won't be an easy fix. You can see online for "hacks" to workaround linker namespace limitations, however in my experience that won't work on Android 10 anymore. I don't recommend you to go down that rabbit hole unless necessary.
