### ISSUE TITLE
MagiskManager constantly gets killed by OS (loses root, etc)

### ISSUE THREAD

**Issue by sou7611** [topjohnwu/Magisk#242]
Consistently, MagiskManager is getting killed by the OS

This results in no root access (since Manager provides SU), no MagiskHide, etc.

The only fix is to either reboot, or swipe-right the app in the recent apps list, and relaunch Manager, then all works correctly until the OS kills the manager app again.  This can happen within minutes.

There is no logging as to what is going on, because when the OS kills the app (and root/SU is lost), there is no more logging (there is no access to the log file to write log entries).

This has progressively gotten worse as v13 development has progressed.  It is not fixed with latest source.

**Comment by DeicPro** [comment]
yeah, but really you don't lost root.. is a gui stuff only..

**Comment by sou7611** [comment]
While it's true the device doesn't lose root, the fact that magisk manager handles MagiskSU tasks means you effectively lose access to root, because all su requests fail.

**Comment by DeicPro** [comment]
Yeah, it is a problem... BTW I would like the su database was a Magisk part and not Magisk Manager, to if I want all CLI not to have to ininstall the app and left /data/data/com.topjohnwu.magisk/databases/su.db file only.. So Magisk Manager to be 100% GUI and nothing more.

**Comment by sou7611** [comment]
That would seemingly solve the su issue.

**Comment by DeicPro** [comment]
Nope, it would the same, is only a suggestion apart of this issue, because the "BTW" (By The Way).

**Comment by sou7611** [comment]
Been trying Memory Locker to see if it helps prevent the app from being killed .... early results seem positive.  This is the app that changes an application's priority level, so the OS memory manager would be less likely to kill the app when scavenging memory, vs normal.

**Comment by sou7611** [comment]
Memory Locker does not solve the issue, just delays it.

Magisk Manager is still (apparently) a high priority kill target for the OS.

When it's killed, ALL SU REQUESTES ARE DENIED, and everything stops working as a result ... anything using magiskhide, su, etc.

This needs to be a high priority fix.

**Comment by DeicPro** [comment]
The only stuff is related to the app is ask to allow su permissions... Saved su permissions, Magisk Hide, etc, are working correctly without the app.

**Comment by sou7611** [comment]
Not in my experience.

when MagiskManager is killed by OS, all su operations case working.

You can't request SU, can't execute anything as root, etc.

It's like when Manager dies, so does MagiskSU

**Comment by sou7611** [comment]
Also worth noting - when this happens SafetyNet starts failing as well (unknown if this is due to magiskhide failing, or some other cause).

**Comment by DeicPro** [comment]
Is not in your experience, is a fact. All works without Magisk Manager but new MagiskSU request. If you uninstall the app, but keep `/data/data/com.topjohnwu.magisk/databases/su.db`, you can use root in an app which you allowed request before.

**Comment by sou7611** [comment]
No you can't .... I've tested this ...

you CANNOT get a su request to pass when MagiskManager is taskkilled by the
OS, nor after you swipe -right to kill the app.

It DOES NOT WORK.

It will not work until you restart MagiskManager.

Try it - force-stop MagiskManager, and try and open something like Adaway
or TitaniumBackup.  You su request will get rejected.

**Comment by DeicPro** [comment]
Rejected if was not allow before as I said... If is previously allowed, MagiskSU read the database a give the root permissions.

**Comment by sou7611** [comment]
NO IT IS NOT .... you're not reading what I'm typing or testing yourself.

A *previously approved SU request*, from a *previously approved app* is NOT
ALLOWED SU ACCESS when MagiskManager is taskkilled.

This breaks ALL su requests.

Don't just blindly reply to me, try it.  It's broken.

**Comment by DeicPro** [comment]
![screenshot_2017-06-20-22-20-43-122_jackpal androidterm](https://user-images.githubusercontent.com/12710770/27354146-e35364c4-5606-11e7-98ac-d5e59736c522.png)
![screenshot_2017-06-20-22-21-09-588_org adaway](https://user-images.githubusercontent.com/12710770/27354151-e8b44e9c-5606-11e7-8a06-44a85b279c0e.png)

**Comment by sou7611** [comment]
And again, I beg to differ.  This is after the OS task killer kills Magisk
Manager.

[image: Inline image 1]

And this is what happens when you attempt a SU related task:


[image: Inline image 2]

In addition, any safety net related task also fails (A-pay, Pogo, etc).

Killing and restarting MagiskManager restores all functionality to normal.

This happens with ANY of the v13 betas, it happens with the version I
compiled myself from the latest source.  It's endemic to the current tree.

**Comment by DeicPro** [comment]
![screenshot_2017-06-20-22-51-46-918_com scottyab rootbeer sample](https://user-images.githubusercontent.com/12710770/27355381-19e215b8-560b-11e7-90cc-5f3a7c903085.png)
![screenshot_2017-06-20-22-51-34-751_com scottyab safetynet sample](https://user-images.githubusercontent.com/12710770/27355380-19df78f8-560b-11e7-965e-15fce056faf8.png)

**Comment by sou7611** [comment]
That is not what I see.  I pasted what I see.  It's broke.

Please stop arguing this and pasting pictures.  It obviously works on your
system.  I have multiple devices here where it doesn't, both marshmallow
and nougat.

Other people have replied on XDA that SAY THE SAME EXACT THING.

This is an issue, and you're trying to argue it into not being one.

**Comment by DeicPro** [comment]
Yeah is an issue, but only affect to the popup of su request, not affect ALL as you says.

**Comment by sou7611** [comment]
also breaks, in my experience, safetynet

**Comment by DeicPro** [comment]
Your SafetyNet broken problem can't to be related with this, makes no sense.. is 100% binary stuff.

BTW, Interesting.. the Magisk Manager was killed by the system and I could allow a su popup request... In previous releases I couldn't...

**Comment by zjjpp** [comment]
I don't know about this, this is a heated debate. Have you tried disabling battery optimization for magisk manager in settings? although you said system task killer so that may not work... Sorry if I am repeating anything. 😃

**Comment by sou7611** [comment]
There's no option to do that, plus in a week it's apparently used all of 2 seconds of time for 0.0ma of computed power usage ...

I don't think it's getting battery killed

On June 20, 2017 8:35:26 PM EDT, zjjpp <notifications@github.com> wrote:
>I don't know about this, this is a heated debate. Have you tried
>disabling battery optimization for magisk manager in settings? although
>you said system task killer so that may not work... Sorry if I am
>repeating anything. 😃 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/topjohnwu/Magisk/issues/242#issuecomment-309929488

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
