### ISSUE TITLE
SystemUI Crashes after MagiskManager has been run

### ISSUE THREAD

**Issue by bengalih** [topjohnwu/Magisk#2420]
I am trying to run Magisk/MagiskManager on [this Custom Lollipop ROM](https://forum.xda-developers.com/hd8-hd10/orig-development/rom-slimlp-t3996003) on my Amazon Fire device.

Any version of MagiskManager after 5.7.0 will crash System UI when using the square soft button (recent apps).  All that is necessary to reproduce this issue is to install MagiskManager, open it once and then try to toggle recent apps.  System UI will crash with a dialog and upon clicking OK the desktop will reinitialize.

Force closing MagiskManager from with app settings seems to make the problem go away, but as long as it has been run once (and is presumable running in the recent tasks?) it will crash SystemUI.

I have tried this with the latest Canary debug build available from the main page as of 2/8/20.  I can't seem to see the full version in the UI.  It shows:

Version: 7.5.2-...cf95
Code: 274
Mode: Normal

Attached is a logcat which shows me using the recent apps to toggle between a few open apps, then opening MagiskManager and then trying again which creates the systemUI crash.

Any help is appreciated.  If I could provide some specific info to the ROM developer to fix would be fantastic.
[logcat.log](https://github.com/topjohnwu/Magisk/files/4176376/logcat.log)

**Comment by bengalih** [comment]
Possibly related to:
https://github.com/topjohnwu/MagiskManager/commit/74ccfe60885ad4fd2d10d3312138b2d178be4e7d

?

**Comment by Fox2Code** [comment]
From your logcat:
```
--------- beginning of crash
E/AndroidRuntime( 8065): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime( 8065): Process: com.android.systemui, PID: 8065
E/AndroidRuntime( 8065): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 8065): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime( 8065): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 8065): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 8065): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 8065): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 8065): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 8065): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 8065): Caused by: java.lang.ClassCastException: android.graphics.drawable.LayerDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
E/AndroidRuntime( 8065): 	at com.android.systemui.slimrecent.AppIconLoader.getResizedBitmap(AppIconLoader.java:144)
E/AndroidRuntime( 8065): 	at com.android.systemui.slimrecent.AppIconLoader.getAppIcon(AppIconLoader.java:94)
E/AndroidRuntime( 8065): 	at com.android.systemui.slimrecent.AppIconLoader.access$000(AppIconLoader.java:46)
E/AndroidRuntime( 8065): 	at com.android.systemui.slimrecent.AppIconLoader$BitmapDownloaderTask.doInBackground(AppIconLoader.java:199)
E/AndroidRuntime( 8065): 	at com.android.systemui.slimrecent.AppIconLoader$BitmapDownloaderTask.doInBackground(AppIconLoader.java:169)
E/AndroidRuntime( 8065): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime( 8065): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 8065): 	... 3 more
```
Seem more an error from your ROM than a Magisk issue
MagiskManager in this case folow android standard
Try to disable slimrecent to **"**fix**"** the problem
You can also report this issue to your ROM maker

**Comment by bengalih** [comment]
> Seem more an error from your ROM than a Magisk issue
> MagiskManager in this case folow android standard
> Try to disable slimrecent to **"**fix**"** the problem
> You can also report this issue to your ROM maker

Thanks.  Don't see anyway to disable that without disabling all of SystemUI, which isn't really feasible.

I see this issue has been closed - but I do have a question about how an issue like this should be handled.

Clearly the base of this ROM hasn't been updated in many years since it is Lollipop based.
I would assume that the ROM devs were not aware of any issues at that point of development stopping because Magisk 5.7.0 (and prior) ran fine.  At some point since then however Magisk made some changes to the UI which appear to conflict with how the Recents list was implemented.

Magisk is supposed to be fully compatible with Lollipop, so this seems a bit chicken-and-egg to me in terms of Magisk introducing a change to a version that came out past the date of the OS in its prime.  From closing the issue it seems like @topjohnwu feels like this is an issue for the ROM developers, but it seems there is an argument that there is some onus on MagiskManager to ensure that it doesn't break compatibility with older implementations it is supposed to be compatible with?

Not trying to lay blame, just trying to understand how the development cycle give and take would normally be handled on an issue like this?

thanks
