### ISSUE TITLE
[API 28+] Magisk Manager theme mode does not follow system mode on OxygenOS when it is set to dark

### ISSUE THREAD

**Issue by KB4284848** [topjohnwu/Magisk#2432]
First of all thanks for the work you put into Magisk, I've noticed this minor bug and figured I should report it to let you know.

Reproduction steps:

- Install Magisk Manager on a OnePlus device
- Ensure theme is set to Dark in Settings -> Display -> Theme
- Launch it
- Click on Themes
- Click on Theme Mode
- Select "Follow system"

Device: OnePlus 5T running OxygenOS 9.0.10
Magisk Manager version: 7.5.2-ed58cf95(274)

Screen record: https://i.imgur.com/WM9y9Cw.mp4
Logcat: [logcat_magisk_debug.txt](https://github.com/topjohnwu/Magisk/files/4180395/logcat_magisk_debug.txt)

Additional note: 

OxygenOS Pie and above stores the system theme at `content://settings/system/oem_black_mode` with returns being 0 for light, 1 for dark and 2 for colourful/default theme [(source)](https://github.com/oxygen-updater/oxygen-updater/blob/master/app/src/main/java/com/arjanvlek/oxygenupdater/internal/ThemeUtils.java#L106)

**Comment by topjohnwu** [comment]
@KB4284848 Magisk Manager uses official APIs to determine whether device is using global dark mode or not. This API is only officially added in Android 10. Personally, I do not plan to add specific OEM setting detection as this is too much effort for such trivial thing. We allow the user to choose which theme to use anyways.

**Comment by KB4284848** [comment]
@topjohnwu fair enough, thanks for explaining!
