### ISSUE TITLE
Magisk fails to install on Moto X Pure (6.0)

### ISSUE THREAD

**Issue by sou7611** [topjohnwu/Magisk#244]
Latest code fails to install.

Mounting /system(ro), /cache, /data
Device platform: arm64
Constructing environment
Creating /data/magisk.img
! Magisk image mount failed ...
Updater process ended with ERROR: 1

**Comment by sou7611** [comment]
Had to revert the following to get this to work again:

Commits on Jun 16, 2017
 @topjohnwu
Several small fixes
topjohnwu committed 2 days ago
96f8efc  
Commits on Jun 15, 2017
 @topjohnwu
Only use binaries/libs in /system
topjohnwu committed 2 days ago
 3   a90e8b6

**Comment by russel5** [comment]
Can confirm this too.
And data partition not responce after this, can't mount or umount
Revert this [https://github.com/topjohnwu/Magisk/commit/96f8efc27aec9b7f37b98b210dd17f2f6d00ccc6](url) fix this issue
Phone - Z3 Compact
Recovery - TWRP 3.1.1

**Comment by NinjaBoyLao** [comment]
has this been handled or what? Same device and similar issue, SafetyNet is suddenly not passing as of july 13th, and clean installing doesn't help. Unrooted and uninstalled and passed safetynet just fine so I know its something magisk is doing or not doing
