### ISSUE TITLE
Feature request: add password as authentication

### ISSUE THREAD

**Issue by eike-fokken** [topjohnwu/Magisk#2441]
After being educated about security of rooting in general and magisk in particular in issue #2414  I suggest the following enhancement:

Instead of only allowing finger print, please offer a choice of authentication with fingerprint or pin
(If it is simpler codewise, maybe there is an api for using the authentication of the lock screen).

Rationale:
I dislike having no authentication at all, as then it is super easy, even by accident to get root access.
I also dislike the fingerprint because (at least in lineage 16) there is no way to have a lock screen pin  (no print) but also have a fingerprint for magisk.
I dislike fingerprint unlock because it is easy to force my finger on the phone but (more) difficult to make me give up my pin.

My current setup includes hiding and protecting magisk manager and all settings (to make it impossible to uninstall magisk manager) as well as choosing "deny" as default reaction to the root access query.

I would very much like instead to choose "prompt" for the query and protect the prompt with a pin. As then its much less of a hassle to actually grant root access when I want it.

In case my setup is just security theater and its easy to get root access with it anyways, please educate me (further).

**Comment by Fox2Code** [comment]
A pin seems to be a good idea for authentification especially if multiple users use your device.
The fingerprint scanner on my phone is actually on the home button si my finger is often on it.
I'm also thinking of a timer into the `Accept` button could avoid accepting the request by mistake.
And I also think to restrict the access to the MagiskManager app via fingerprint or pin.
But this feature will not be implemented until the MagiskManager design is not finished.

**Comment by linuxandria** [comment]
I've used a few cheap devices with no fp sensor and this would be a great feature for those devices.

**Comment by topjohnwu** [comment]
Sorry, but I won't take new feature requests for now.

**Comment by Minabsapi** [comment]
In case you're returning to feature requests, unless it deserves its own issue I'd like to extend this feature by asking to make it available for ADB authentication as well. That would be better than having to go into the manager app settings and enabling root for ADB then disabling it when done, as it's error-prone (had root enabled over ADB even after setting the parameter off, had to turn USB debugging on and off to fix)
