### ISSUE TITLE
Installing Custom Recovery/ROM

### ISSUE THREAD

**Issue by soraaa** [topjohnwu/Magisk#2447]
Does install magisk always lock the bootloader?
I have unlocked my device but after I install magisk, it lock the bootloader again

What if I want to install custom ROM like TWRP or clean flash ROM, Do I need to unlock my bootloader again? Will this cause problems on my device due to the magisk that already installed?

**_P.S:
My device is Redmi K20_**

**Comment by Fox2Code** [comment]
Your ROM can't boot if your bootloader is locked so if you have Magisk installed and your phone boot normally this means that your bootloader is unlocked.

I think it's just MagiskHide faking the bootloader state to locked to avoid triggering root detection and SafetyNet.

So don't worry if it shows that your bootloader is locked if you have Magisk installed it's probably not the case. 

If you still want more information you can read this issue #2414

**Comment by Didgeridoohan** [comment]
Magisk does not lock the bootloader. You're misunderstanding something.

**Comment by soraaa** [comment]
> Your ROM can't boot if your bootloader is locked so if you have Magisk installed and your phone boot normally this means that your bootloader is unlocked.
> 
> I think it's just MagiskHide faking the bootloader state to locked to avoid triggering root detection and SafetyNet.
> 
> So don't worry if it shows that your bootloader is locked if you have Magisk installed it's probably not the case.
> 
> If you still want more information you can read this issue #2414

Ah, yes...I tried to deactivate MagiskHide and my bootloader status is now unlocked. Thanks for information :)
