### ISSUE TITLE
Magisk fails to install correctly on nexus 9 (7.1.1)

### ISSUE THREAD

**Issue by sou7611** [topjohnwu/Magisk#245]
Magisk fails on Nexus 9.

Installation runs without error, but all systemless functions are missing.

Also cannot install modules.  No errors, but modules simply aren't there after reboot.

Due to systemless issue, cannot run adaway, cannot install busybox, etc.

**Comment by DeicPro** [comment]
where is the log?

**Comment by DeicPro** [comment]
Where is the log? What Magisk version are you using?

If is the latest Magisk v13 Beta, go to this thread and read it to know the log topjohnwu need https://forum.xda-developers.com/apps/magisk/beta-magisk-v13-0-0980cb6-t3618589

**Comment by sou7611** [comment]
This is with a hand-built from latest sources, also tried with latest beta (same result, as expected)

Modules DO work, however, so ignore that part.

The systemless issue is more interesting.  Systemless is actually working, but it's not being setup correctly as a default within Magisk.  Since MagiskManager no longer offers the option to expressly turn systemless hosts on and off (or even systemless itself) ... or, for that matter, even enable/disable MagiskHide, all this has to happen automatically by the system.

It is not.  There is no system ghosting (e.g. systemless overlays) happening at all.

But if you install a module that activates a layer of ghosting (e.g. the Adblock module), the hosts file gets mapped, and now something like Adaway works as expected.

Logging is not going to be useful here - there is no error at all, and the log shows nothing abnormal.  Everything is as you expect it to be if working normally.

Can still grab them if desired, but it will be a waste of time.

**Comment by sou7611** [comment]
Did a full factory reset, reflashing all partitions with latest code (June 2017).

Tried again.  Same exact result, except now it's failing to install MagiskManager as well.

Flashing that manually, then running the Manager shows Magisk is installed, as you'd expect from the lack of errors while flashing the zip.

Again, no systemless defaults (so adaway fails, ericcson's busybox fails), and safetynet also fails.

Replicated with official 13beta zips, as well as compiled-from-source zips.  Same result.

**Comment by sou7611** [comment]
Tried again, full factory restore/flash with the June software, attempted reinstalling Magisk, same exact results.

Something is major broken here.

**Comment by sou7611** [comment]
Update :

Install is still broken, but some stuff was fixable manually ...

1) magisk is failing to enable systemless items (it's installing, but zero systemless defaults are setup), so out of the box, busybox cannot be installed, nor can systemless hosts.

2) module flashing from magiskmanager is not working.  Modules have to be flashed from TWRP.

3) magiskhide is broken - have to manually RESETPROP "persist.magisk.hide" and "persist.magisk.root", which are not getting set by the installer.  MagiskManager log clearly shows it's not enabling magiskhide due to the missing prop.  Once adding by hand is done, and the Nexus 9 is rebooted, magiskhide works as expected, and safetynet passes.

The last two items that don't work, are systemless hosts, and systemless busybox ... can't figure out how to fix that as there's nothing logged that indicates an error. It just doesn't work.  When I compare the bootup log for magisk to a working device it's identical.

Was able to workaround via the existing adblock/busybox modules which, interestingly enough, work by enabling their respective systemless directories ...

which shows it's not a backend issue with magisk, it's a setup/config issue via the installer.

**Comment by topjohnwu** [comment]
Should be fixed
