### ISSUE TITLE
Magisk Manager module install UI bug

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#2453]
Hi,
Since the graphical redesign of Magisk Manager, I always have the same problem: when installing a module (any module) either from storage or from the internet (Github), I have this graphical bug:
![Screenshot_20200212-230211](https://user-images.githubusercontent.com/20888017/74381760-58767400-4dec-11ea-930e-101e741cabf4.png)

The logcat: 
[logcat.txt](https://github.com/topjohnwu/Magisk/files/4195272/logcat.txt)

I also point out that the display bug I was encountering on the main section is no longer present since the second redesign of the main page.

**Comment by Fox2Code** [comment]
I have a similar problem I think the FlashActivity is not cleared on each redraw that causes the graphical bug.

**Comment by topjohnwu** [comment]
8453282fa6580021201b6bdbb15ef9f320b7f1e8
