### ISSUE TITLE
Canary update channel settings were inadvertently left out of todays build, 276

### ISSUE THREAD

**Issue by martyfender** [topjohnwu/Magisk#2455]
Canary update channel settings in Magisk Manager were inadvertently left out of todays build, 276.
Onn 8, Android 9.

Thanks

**Comment by wangdaning** [comment]
Don't think they were left out, just not showing on some devices. They do show on my Pixel 3 February android 10 release.

**Comment by kam821** [comment]
+1
1) After the latest update, Manager/Magisk dont contain the major version number, but only build id.
2) Apk in canary version, both release and debug, dont have Canary/Canary (debug) repositories builtin.
3) Manually setting the repo address to canary release.json does not help.
The application is constantly trying to find Magisk / Magisk Manager update.
4) Installing older Canary build, setting repo to Canary and trying to hide Manager -> result =  beta / stable version installed, instead Canary.

**Comment by kam821** [comment]
I had to install manually set repo to Canary / install older Canary, hide Manager (causes installed beta/stable) and then Hide again (repo manually set into canary release.json)
Now latest version is installed and property hidden.

**Comment by topjohnwu** [comment]
1e7e06d1cc741b0b70dcf4f6d24bae0b5022d066
