### ISSUE TITLE
Solution for VERY SLOW installation with TWRP on some Samsung devices.

### ISSUE THREAD

**Issue by Nodens-** [topjohnwu/Magisk#246]
I have verified this myself and the problem is /dev/random and actually a bug in TWRP.
The workaround is to bind /dev/urandom to /dev/random prior to installing either via TWRP terminal or adb.

Since Magisk does not really need high quality entropy, the installer should default on /dev/urandom to avoid this problem for now and possibly future regressions in TWRP.

Referencing:
https://forum.xda-developers.com/showpost.php?p=72722325&postcount=1342

The workaround cuts the installation time from 2-4 hours to seconds, as it should be.

**Comment by DeicPro** [comment]
2-4 hours? What?

**Comment by Nodens-** [comment]
Yes apparently there is something wrong with the kernel on some TWRP and /dev/random is causing the blocking behavior. I have experienced 2-4 hours long installation of the v13 betas myself with 3+ being the norm.
 The xdadev thread has several reports of 2+ hours. The issue is resolved by the workaround first posted by Chainfire, binding /dev/urandom to /dev/random.
 I do not know if the Magisk installer is reading /dev/random directly or via an API call but it should use /dev/urandom instead to resolve the current issue and avoid possible regressions in the future.
 Although technically this is a TWRP issue, magisk installer doesn't need high quality entropy, so there's no reason for not making sure the installer is always as fast as possible regardless of TWRP version (not to mention that some devices may never get a fix in their TWRP images).

**Comment by tdunham91** [comment]
I addressed this issue and added the changes to update-binary here:
https://forum.xda-developers.com/showpost.php?p=72730850&postcount=1425

]##########################################################################################
# Environment
##########################################################################################
## Forcing mount of /dev/urandom to /dev/random
## To resolve TWRP behavior resulting in an extremely slow install
mount -o bind /dev/urandom /dev/random

ui_print "- Constructing environment"
.
.
.
.
.
if ! $BOOTMODE; then
  mv /sbin_tmp /sbin
  ui_print "- Unmounting partitions"
  umount /magisk
  losetup -d $MAGISKLOOP 2>/dev/null
  rmdir /magisk
  umount -l /system
fi
## Unmount dev/random
umount /dev/random

ui_print "- Done"
exit 0
[/CODE]

**Comment by Nodens-** [comment]
Fixed in commit 2a86bc8695cdae5aa0fd14715bd22fb31abc4229 closing.
