### ISSUE TITLE
Magisk can't hide some app cause minimum security.

### ISSUE THREAD

**Issue by kaug5164** [topjohnwu/Magisk#2460]
![received_181001636487892](https://user-images.githubusercontent.com/13131156/74492510-af21a200-4f01-11ea-9451-5162e3d93a39.jpeg)
![received_192691581793750](https://user-images.githubusercontent.com/13131156/74492516-b183fc00-4f01-11ea-9ccc-9174e17bdd19.png)

Now application TMB Touch and True Wallet will not work anymore for device that unlock bootloader i try to hide magisk manager and hide that app still not working. Do you have any solution to bypass this security?

**Comment by skittles9823** [comment]
#1152 I'd recommend closing this.
