### ISSUE TITLE
SELinux patches

### ISSUE THREAD

**Issue by hrap1919** [topjohnwu/Magisk#2469]
To read dmesg 
"allow magisk kernel system { syslog_read syslog_mod }"

To change the property ro.boot.verifiedbootstate (for moto g7 power "ocean")
"allow magisk exported2_default_prop property_service { set }"

To bind tcp-sockets
"allow magisk port tcp_socket { name_bind }"
"allow magisk node tcp_socket { node_bind }"

Also, the Type 3 policy statement for enforcing a domain is actually "enforce class". This contradicts with "magiskpolicy --help"

**Comment by hrap1919** [comment]
In addition, the execution allowSuClient("magisk") in sepol_magisk_rules (in rules.cpp) prevents some avc-warnings.

**Comment by linuxandria** [comment]
Why don't you open up a pull request :P

**Comment by hrap1919** [comment]
Why you are asking this?

**Comment by topjohnwu** [comment]
@hrap1919 Magisk's installation also applies this rule `allow magisk * * *`, so all of your proposals shall not be needed.
