### ISSUE TITLE
Multi-user feature is not working.

### ISSUE THREAD

**Issue by StephyMV** [topjohnwu/Magisk#247]
I just want to report that the multi-user feature has not yet worked. I did report this in the Beta thread, but I was instructed by Didgeridoohan to open an issue on GitHub too, as my reports and files in the thread were overshadowed by a sea of messages on the "SafetyNet farse".
I did not test the latest beta version due to reports of it taking hours to flash.
Attached are the Manager's logs of the versions I tried.

Also, it still isn't flashable through TWRP, so I'm attaching Samsung's 2017 boot.img of my A7 2017 (SM-A720F), in TWRP's *.win backup format (sorry, I don't know how to extract these files), so that it can be analyzed and figured out, and become flashable through TWRP, just as v12 already is.

[Original_Boot_Image_A7_2017.zip](https://github.com/topjohnwu/Magisk/files/1085220/Original_Boot_Image_A7_2017.zip)

[Boot_Image_with_no-verity-no-encrypt_by_ashyx.zip](https://github.com/topjohnwu/Magisk/files/1085242/Boot_Image_with_no-verity-no-encrypt_by_ashyx.zip)

[b3da28e.zip](https://github.com/topjohnwu/Magisk/files/1085193/b3da28e.zip)

[a90e8b6.zip](https://github.com/topjohnwu/Magisk/files/1085194/a90e8b6.zip)

**Comment by virajmalia** [comment]
Multi-user support **NOT** present as of Magisk v13.1
Is it possible to have a global support or something? I believe the problem exists due to separate data partitions for different users. Can symlinking binaries and libraries make it happen or do we need a complete overhaul?

**Comment by topjohnwu** [comment]
Sorry, I currently don't have much time, but I'll look into it :)

**Comment by psychowood** [comment]
Fyi, it started working after I flashed 13.6 (1360), wasn't working before (tested up to 13.3). Nexus 6 with PureNexus 7.1.2.
