### ISSUE TITLE
Not Performing Aditional Setup in Latest Canary.

### ISSUE THREAD

**Issue by NULL0B** [topjohnwu/Magisk#2471]
I have just patched ramdisk. And when i open canary manager it does not ask for perform aditionally setup. And says magisk canary installed. 
In ver 20.3 worked, this one has another bug whe the app is retriving json file for latest magisk version, and i click perform aditional install it failed. Maybe you can't notice because dont have an slow connection as i do. ALSO When screen rotates the dialog desapeears and never gets rebooted.

**Comment by linuxandria** [comment]
I'm guessing you don't actually need additional setup. Unless you wiped data after flashing magisk you generally don't

Recommend closing.

**Comment by NULLO0B** [comment]
> I'm guessing you don't actually need additional setup. Unless you wiped data after flashing magisk you generally don't
> 
> Recommend closing.
And what about rotation issuue while performing aditional install, and install fail when magisk is getting json in slow connection.
---------------
This is what i did:
I just patched ramdisk in AvD
Version 20.3  asked about aditional setup. but canary dont
And started it from 0.
gzip -d < ramdisk.img > ramdisk.cpio
cp -af ramdisk.cpio ramdisk.cpio.orig
printf "KEEPVERITY=false\nKEEPFORCEENCRYPT=false\nRECOVERYMODE=false" > config
./magiskboot cpio ramdisk.cpio "add 750 init magiskinit" "patch" "backup ramdisk.cpio.orig" "mkdir 000 .backup" "add 000 .backup/.magisk config"
gzip -9 < ramdisk.cpio > /sdcard/modified.img

**Comment by linuxandria** [comment]
Well that's why
You didn't use a supported method to patch it


Also please, one issue per issue
