### ISSUE TITLE
Set language glitch

### ISSUE THREAD

**Issue by palmbeach05** [topjohnwu/Magisk#2476]
When opening up Magisk Manager and going to the settings screen on revisions containing the new layout (canary releases since mid/late January 2020), random menu options and entries do not conform with the set language, and instead are displayed in another language. This is seen using various languages being set for use and with the System Default. An example is attached.

![Screenshot_20200219-075604_Magisk_Manager](https://user-images.githubusercontent.com/5945226/74836566-a22ff480-52ed-11ea-872d-ccd5746d6f6e.png)

![Screenshot_20200219-081010_Magisk_Manager](https://user-images.githubusercontent.com/5945226/74837365-54b48700-52ef-11ea-8946-106dd6513077.png)

**Comment by Didgeridoohan** [comment]
Fixed in https://github.com/topjohnwu/Magisk/commit/0d7474cc88c8f5412fbbd449ea336b79c4ef77fa

You can close this and wait for next release to test.
