### ISSUE TITLE
Android 11 (R) Support - Currently Bootlooping on Stable and Canary

### ISSUE THREAD

**Issue by danteissaias** [topjohnwu/Magisk#2477]
Magisk causes a bootloop in the following conditions:
- Pixel 3 running Android R
- `boot.img` patched with latest Canary

**Comment by notquitedante** [comment]
Magisk also causes a bootloop in the following conditions:
- Pixel 3 running Android R
- `boot.img` patched with latest Magisk canary debug

**Comment by notquitedante** [comment]
After 2 bootloop cycles it boots into fastboot with `Enter reason: no valid slot to boot`

**Comment by linuxandria** [comment]
Please be aware the is a developer preview and as such not likely to receive any support from @topjohnwu

**Comment by H4NG-MAN** [comment]
> Magisk causes a bootloop in the following conditions:
> 
> * Pixel 3 running Android R
> * `boot.img` patched with latest Canary

**Comment by MrBaNkS** [comment]
Oh boy..lol

**Comment by Justsnoopy30** [comment]
Same for me.

**Comment by yurikoles** [comment]
Same for Pixel 3a (sargo).

**Comment by AndroidDeveloperLB** [comment]
@linuxandria from which version do you think it will work?
I remember that on Q, it was possible to use Magisk at some phase, before it became final.

**Comment by skittles9823** [comment]
It won't work at all. John got Q support in very fast when it was first dropped. R has significant changes which makes Magisk support more of a challenge.

I'd suggest just waiting for John to have the time to get Magisk compatible with R and not attempt to root otherwise.

**Comment by bell18-web** [comment]
Please help i stress for 2 week...

**Comment by Justsnoopy30** [comment]
Bump.

**Comment by Didgeridoohan** [comment]
@Justsnoopy30 This isn't a forum. You don't bump issues...

As long as the issue still is open it'll be taken care of, one way or another.

**Comment by topjohnwu** [comment]
dfbd1305b310531d55da46d9542eeab788c68aef

**Comment by AndroidDeveloperLB** [comment]
Wait, this means that Magisk is now available for R ? 
What is going on?
I thought it's way too early to ask this...

**Comment by knackl3s** [comment]
Awesome!
It works on my Pixel 2.

**Comment by AndroidDeveloperLB** [comment]
What works?
Magisk on R ?

**Comment by knackl3s** [comment]
> What works?
> Magisk on R ?

Yes, simply compile the latest debug code.

**Comment by AndroidDeveloperLB** [comment]
@knackl3s Is this the same as this one:
https://www.xda-developers.com/latest-magisk-canary-release-adds-support-for-android-11/
?

**Comment by Didgeridoohan** [comment]
@AndroidDeveloperLB Yes, the current Canary release works on Android 11. But be aware that there are still other more or less major issues with it (as of release 20405).

**Comment by AndroidDeveloperLB** [comment]
@Didgeridoohan Which issues? Maybe I can live with them :)
I'm now back on Android 10 (had 11 for a while), and I think about updating to 11...

**Comment by Didgeridoohan** [comment]
So far it's mainly been about module mounting issues it seems (there's been a lot of under-the-hood changes), but the best way to keep track of the progress is to monitor the Github issues and John's Twitter.

**Comment by AndroidDeveloperLB** [comment]
So other than modules, it works fine?
Does "Edge sense plus" module work fine? Currently it's the only one I use.

**Comment by Didgeridoohan** [comment]
You'd have to give it a go and try, I wouldn't know.

**Comment by AndroidDeveloperLB** [comment]
@Didgeridoohan OK sorry and thank you.

**Comment by doct0rX** [comment]
Still now fixed! just tried it out and stuck on bootloop
```
- Magisk Canary Debug
- Android 11 Stable release
```
