### ISSUE TITLE
Seems like Pokémon Go upgraded their anti-root

### ISSUE THREAD

**Issue by lapo-luchini** [topjohnwu/Magisk#2478]
![image](https://user-images.githubusercontent.com/420454/74915034-ce1da980-53c3-11ea-817f-bd6083814619.png)

**Comment by lapo-luchini** [comment]
BTW: I don't have any "TWRP" folder (so I don't think it's [related to this](https://twitter.com/topjohnwu/status/1229500193709555712)), I installed Magisk using TWRP in RAM with `fastboot boot` in order to have clean partition and possibility to do OTAs (which have been doing with no need for TWRP for the last 5 monthly upgrades already).

**Comment by pbanj** [comment]
You might still have a twrp folder. Worth checking. Also have you hid the manager

**Comment by lapo-luchini** [comment]
Sure, I just double-checked both.

**Comment by Jon8RFC** [comment]
Pixel 4. Google Play store is certified. Safety net passes. Custom kernel.

I just installed it, Magisk is hidden/renamed, did NOT run Pokemon Go, went into Magisk Hide and selected all four options in Pokemon Go, ran it, logged in, everything was working.  Uninstalled, reinstalled, repeated the process, and it refused to run.  Did a force stop of pokemon go, tried again and it worked.  Closed the app, began writing this post, opened it again, and it didn't work.  It seems like whenever it doesn't work, doing a force close and trying again resolves it.

**Comment by linuxandria** [comment]
Unless you can tell us _how_ they are doing it or contribute on _how to solve_ this detection, #1152 applies and you should close this issue

**Comment by lapo-luchini** [comment]
I didn't know about #1152, and don't have time on hand to learn how to debug it myself, so I'll close this.

**Comment by lapo-luchini** [comment]
> a force close and trying again resolves it.

To me more like… sometimes it stops immediately and sometimes up to 30 seconds after showing the map. But always pretty fast (I managed to capture a single Pokémon launching it like 15 times in a row).

Safety net passes, all [best practices](https://topjohnwu.github.io/Magisk/tutorials.html#best-practices-for-magiskhide) followed.
