### ISSUE TITLE
Newbie Question

### ISSUE THREAD

**Issue by hyoungtaikkim** [topjohnwu/Magisk#2480]
Sorry, but I have better ask somewhat basic and even stupid questions. 

== Background
    1. I could have rooted my custom made Android tablet with Magisk successfully. It was great. ;)
    2. I would like to build the source at my Windows 10 and try to study how it works. However I have some problems.
            a. I have done git cloned including sub modules as explained and set up ANDROID_HOME and ANDROID_NDK_HOME as suggested and installed colorama, but I have used just Android NDK, not FrankeNDK though.
            

== Questions 
    1. Is there any step by step guide about how to build the source?
    2. Am I supposed to build the full source by running build.py instead of Android Studio?
    3. Where is config.prop? Am I supposed to create this file like config.prop.sample?
    4. Even if I have tried something like ">python build.py -c config.prop all -h", nothing seems to be done except a command window appears and disappears.
    5. When I tried to build the source through Android Studio, there was some error like Ambiguous method overloading...... at gradle file.
               a. I have tried the zip file of version 20.03, but same error though.

Anyway thanks for great software. ;)

**Comment by wangdaning** [comment]
I would say yes at number 3, but never tried building in windows so cannot really help.

**Comment by topjohnwu** [comment]
Q1: Get the env right, and use `build.py`
Q2: Yes. In fact, building the app without `build.py` won't even build by default as some resources will be missing
Q3: Yes
Q4: It means there is something wrong with your python setup

I always made sure that the project can be built with all platforms, so most will be your own user error. It would take some time to setup on Windows, but I can assure that things do work.

Another option for you is to use WSL and simply build it in its Linux env.

**Comment by hyoungtaikkim** [comment]
Thanks. I will try to check it out based on your comment. 

Thanks again. ;)
