### ISSUE TITLE
Possible to enter MagidkHide in a race condition

### ISSUE THREAD

**Issue by linuxandria** [topjohnwu/Magisk#2481]
I was testing out a grep command and needed a clean environment so tried doing it in MagidkHide.

And the output of the command came _before_ any of the unmounted blabla stuff. Meaning the command executed before MagidkHide hid anything.
![Screenshot_20200221-195331](https://user-images.githubusercontent.com/45006100/75082952-21871900-54e4-11ea-8ad7-8db19d9bacb7.png)

This more than even previously posted issues about gms detecting supposedly hidden things temporarily proves MagidkHide isn't hiding fast enough for some things.

**Comment by linuxandria** [comment]
With noting introducing a 0.2 sec sleep does cause it to behave correctly; however any amount of time is enough to detect root if you're fast enough

**Comment by topjohnwu** [comment]
I don't you fully understand how MagiskHide works, there is nothing racing about in Magisk. If GMS is able to detect something, it is because it is detecting something I didn't or couldn't hide. Also, you are using the MagiskHide exec command wrong
