### ISSUE TITLE
Compilation issues with build.py

### ISSUE THREAD

**Issue by Mijotchi** [topjohnwu/Magisk#2482]
I'm trying to use build.py but I can't, a variable needs to be defined, I don't know how to solve :/
Console:

> $ python3 build.py -h
> 
> Please add Android SDK path to ANDROID_HOME environment variable!
> 
> $

**Comment by Didgeridoohan** [comment]
Come on... Magisk's Github issues isn't really the place for basic building issues.

General tip: when you run into issues like this, it is very likely that someone already answered it somewhere on the internet. Searching for the error message (or applicable) with your search engine if choice should always be the first thing to try:
https://duckduckgo.com/?q=Please+add+Android+SDK+path+to+ANDROID_HOME+environment+variable!&t=brave&ia=qa
