### ISSUE TITLE
Unable to edit system files with Magisk v20.3

### ISSUE THREAD

**Issue by beingkha3** [topjohnwu/Magisk#2484]
I am unable to edit, delete or replace any files from the root system folder with any of the root file explorers in my Oneplus 7 Pro OOS 10.3.1.
I am also unable to change the boot animation using magisk modules.

**Comment by wangdaning** [comment]
You cannot manually edit the /system on Android 10, you need to make a module to do your changes. For the boot animation, make sure the module is targeting the correct location. I do not have the same device, so cannot really give specifics on this.

**Comment by beingkha3** [comment]
Thanks for replying and so sorry, I actually was going to remove this issue. I will mark it as closed now.
I actually downloaded the latest root explorer and with the help of it i was able to make changes for the root system files.

**Comment by ahronshor** [comment]
i can change files in system in android 10.
but you need to run this command in terminal before `mount -orw,remount /`.

**Comment by skittles9823** [comment]
@ahronshor won't work on any Android 10 launch device or any device which gained logical partitions when they were updated to 10.
