### ISSUE TITLE
[Asus Zenfone 5Z] Init fails when Magisk is installed

### ISSUE THREAD

**Issue by kailashrs** [topjohnwu/Magisk#2489]
On the 5Z, on an Android 10 based custom ROM, the device is stuck on the Android logo (doesn't even make it to bootanimation). The only logs I could get are console-ramoops, which I have attached. Not sure if I'm right but it appears init is failing to mount partitions (?).

Anyway, here is ramoops: https://del.dog/thuhysilal.txt

**Comment by kailashrs** [comment]
@shakalaca can you help? Seeing you have the most experience with Asus devices...

**Comment by shakalaca** [comment]
1. Which custom ROM ? 
2. Magisk version ?

**Comment by kailashrs** [comment]
> 1. Which custom ROM ?
> 2. Magisk version ?

LineageOS, with the latest canary release of Magisk

**Comment by shakalaca** [comment]
This one ? https://forum.xda-developers.com/zenfone-5z/development/rom-lineageos-17-0-t3967702
It's unofficial and no source code of device tree and kernel, I'm afraid there's nothing I can do for you :(

**Comment by kailashrs** [comment]
> This one ? https://forum.xda-developers.com/zenfone-5z/development/rom-lineageos-17-0-t3967702
> It's unofficial and no source code of device tree and kernel, I'm afraid there's nothing I can do for you :(

Uh no, its a yet unpublicized release due to Magisk being broken, sorry I should have mentioned that beforehand! Anyway, here are the kernel sources: https://github.com/5z-devs/android_kernel_asus_sdm845/commits/lineage-17.1

**Comment by kailashrs** [comment]
Here is the device tree: https://github.com/BlissRoms-Devices/android_device_asus_Z01R. More recent changes aren't online yet, will ask the developer to push them once he comes online.

**Comment by kailashrs** [comment]
https://github.com/LineageOS/android_device_asus_Z01R/commits/lineage-17.1

@shakalaca here is the up to date device tree

**Comment by kailashrs** [comment]
Issue fixed, hugest thanks to @shakalaca for taking his time to point out the issue!
