### ISSUE TITLE
Xiaomi Mi9t Recovery bootloop after magisk install

### ISSUE THREAD

**Issue by Vanman989** [topjohnwu/Magisk#2492]
Hi, I've installed magisk 20.3 by patching boot image and by TWRP but it always results in the phone having a recovery bootloop after install. Do you have a link to a tutorial to show me how to give you log files? Or could you please tell me how to give you the info you need to figure out whats happening.

![image](https://user-images.githubusercontent.com/25638713/75482586-fdf32f80-5a09-11ea-9ab5-2445ae553643.png)

**Comment by sabpprook** [comment]
Is your device come from China and flash global ROM?
This is the reason why device will get recovery bootloop. https://github.com/topjohnwu/Magisk/pull/2470

**Comment by Vanman989** [comment]
> Is your device come from China and flash global ROM?
> This is the reason why device will get recovery bootloop. #2470

Yes I think mine is Chinese to Global

**Comment by aIecxs** [comment]
advanced - keep force encryption

**Comment by Vanman989** [comment]
> advanced - keep force encryption

Hi, dosnt fix issue

**Comment by sabpprook** [comment]
Use custom update channel with this URL to create magisk_patched.img
```
https://ppt.cc/fQfj1x
```

**Comment by Vanman989** [comment]
> Use custom update channel with this URL to create magisk_patched.img
> 
> ```
> https://ppt.cc/fQfj1x
> ```

Thank you for helping. Do you have information on how to use a custom update channel for patch image?

**Comment by Vanman989** [comment]
> > Use custom update channel with this URL to create magisk_patched.img
> > ```
> > https://ppt.cc/fQfj1x
> > ```
> 
> Thank you for helping. I put URL in magisk manager app settings "Update Channel". I refreshed magisk manager app and installed update to magisk manager app that came up.

I tried to create a magisk_patched.img with the new magisk manager app but I cant find the magisk_patched_img

**Comment by sabpprook** [comment]
> > Use custom update channel with this URL to create magisk_patched.img
> > ```
> > https://ppt.cc/fQfj1x
> > ```
> 
> Thank you for helping. I put URL in magisk manager app settings "Update Channel". I refreshed magisk manager app and installed update to magisk manager app that came up.
> 
> I tried to create a magisk_patched.img with the new magisk manager app but I cant find the magisk_patched.img

The file will be generated under "/sdcard/Download"

**Comment by Vanman989** [comment]
I reinstalled application encase. When clicking lets go. It just exists the program immediately and not magisk_patched.img to be found anywhere.
![image](https://user-images.githubusercontent.com/25638713/75636814-d78df800-5c86-11ea-99aa-d8a07bef2c7e.png)

**Comment by sabpprook** [comment]
Please install Magisk manager 7.5.1 and try again, there is a problem with "canary" manager.

**Comment by Vanman989** [comment]
> Please install Magisk manager 7.5.1 and try again, there is a problem with "canary" manager.

I reinstalled Magisk manager 7.5.1 but now the custom update channel is not refreshing to update to your manager

**Comment by sabpprook** [comment]
> > Please install Magisk manager 7.5.1 and try again, there is a problem with "canary" manager.
> 
> I reinstalled Magisk manager 7.5.1 but now the custom update channel is not refreshing to update to your manager

It's okay.
I force it to use manager 7.5.1 to avoid manager update, all you need is make a magisk_patched.img and flash it.

**Comment by Vanman989** [comment]
> > > Please install Magisk manager 7.5.1 and try again, there is a problem with "canary" manager.
> > 
> > 
> > I reinstalled Magisk manager 7.5.1 but now the custom update channel is not refreshing to update to your manager
> 
> It's okay.
> I force it to use manager 7.5.1 to avoid manager update, all you need is make a magisk_patched.img and flash it.

Sorry to confirm. I use your custom update channel in magisk manager settings and use magisk manager 7.5.1 to create patched image and that will solve my bootloop issue when I flash image? If it dosnt. Will the magisk 20.3 uninstall file remove it?

**Comment by sabpprook** [comment]
> > > > Please install Magisk manager 7.5.1 and try again, there is a problem with "canary" manager.
> > > 
> > > 
> > > I reinstalled Magisk manager 7.5.1 but now the custom update channel is not refreshing to update to your manager
> > 
> > 
> > It's okay.
> > I force it to use manager 7.5.1 to avoid manager update, all you need is make a magisk_patched.img and flash it.
> 
> Sorry to confirm. I use your custom update channel in magisk manager settings and use magisk manager 7.5.1 to create patched image and that will solve my bootloop issue when I flash image? If it dosnt. Will the magisk 20.3 uninstall file remove it?

Yup, and uninstaller will work fine. Nothing to worry.

**Comment by Vanman989** [comment]
> > > > > Please install Magisk manager 7.5.1 and try again, there is a problem with "canary" manager.
> > > > 
> > > > 
> > > > I reinstalled Magisk manager 7.5.1 but now the custom update channel is not refreshing to update to your manager
> > > 
> > > 
> > > It's okay.
> > > I force it to use manager 7.5.1 to avoid manager update, all you need is make a magisk_patched.img and flash it.
> > 
> > 
> > Sorry to confirm. I use your custom update channel in magisk manager settings and use magisk manager 7.5.1 to create patched image and that will solve my bootloop issue when I flash image? If it dosnt. Will the magisk 20.3 uninstall file remove it?
> 
> Yup, and uninstaller will work fine. Nothing to worry.

Amazing! it worked! thanks so much!

**Comment by osm0sis** [comment]
Sounds like this was fixed by #2470. Please close the issue, since it has been merged. :+1:

**Comment by notr1ch** [comment]
Having the same issue on my K20 Pro with 11.0.5.0.QFKEUXM, eagerly awaiting the canary release to test this fix.

**Comment by Vanman989** [comment]
> > > > > Please install Magisk manager 7.5.1 and try again, there is a problem with "canary" manager.
> > > > 
> > > > 
> > > > I reinstalled Magisk manager 7.5.1 but now the custom update channel is not refreshing to update to your manager
> > > 
> > > 
> > > It's okay.
> > > I force it to use manager 7.5.1 to avoid manager update, all you need is make a magisk_patched.img and flash it.
> > 
> > 
> > Sorry to confirm. I use your custom update channel in magisk manager settings and use magisk manager 7.5.1 to create patched image and that will solve my bootloop issue when I flash image? If it dosnt. Will the magisk 20.3 uninstall file remove it?
> 
> Yup, and uninstaller will work fine. Nothing to worry.

Hi, I had to reset my phone. WIll this work with Magisk 20.4? Or does magisk 20.4 fix the issue I was having?

**Comment by osm0sis** [comment]
It's merged, use v20.4 stable.
