### ISSUE TITLE
Sideload New Android Version with Magisk

### ISSUE THREAD

**Issue by rahulbansiwal** [topjohnwu/Magisk#2493]
Hi there,

I have rooted my Pixel 3 with Magisk and in near future when new Android Version(11) is available , will I be able to side-load it with Magisk or do I have to un-root first and then flash the Update and again root the device. Also I am wondering since I rooted my device I am not been able to receive OTA updates(Feb and Jan Patch) is it possible that it must be because my device is rooted?

P.S Thanks in advance.

**Comment by wangdaning** [comment]
Please check root of this repo for the magisk/docs and the tutorial in the README.md  file. It explains all about OTA. Most likely you are not getting an OTA available for some other reason, have you tried to check manually. As far as A11, well, it is pretty far off from official release, so the questions are a bit premature, imo.

**Comment by linuxandria** [comment]
Support questions are better handled at xda or other platforms. 
Recommend closing.
