### ISSUE TITLE
Runtime storage resizing

### ISSUE THREAD

**Issue by dcastro172** [topjohnwu/Magisk#25]
Magisk uses a fixed size storage of 64MB, isn't better an API to resize storage per module?

**Comment by topjohnwu** [comment]
It will resize every boot time and installation. Check the scripts and my module template

**Comment by dcastro172** [comment]
But is not a Magisk function, it is hard-coded in module.

**Comment by topjohnwu** [comment]
Here are two possible cases:
Case 1 - In recovery: The template flashing scripts will handle the resize of the image, depending on the size of the module content and the free space of the image.
Case 2 - In Magisk Manager: The scripts will create another image, determine the size needed to contain the module contents. At the next boot time, Magisk will found the new image, resize the previous image to fit the contents in the new image, and merge the two images, then delete the new image.

On macOS (and I think also desktop Linux) supports something called "sparse image", which is image files that expand its own size when contents are added. The image Magisk uses cannot be resized when it is in use, and also there is no way to easily create a sparse image without proper kernel support. So the only way is to use my template module to flash modules.

**Comment by dcastro172** [comment]
Sorry for delay, 

1-) It's about abstraction, to move hardcoded bash code to C in a 'magisk' executable and:

    magisk -extend $(ZIP_SIZE) -blabla

2-) Why you need to create a new image and merge it? Cache module contents and execute resizing like first question?
 
Also I think than is better an wiki page about Magisk's technical details for very new users like me, prevent dumb questions like 2.

**Comment by topjohnwu** [comment]
@dcastro172 the info on XDA is now outdated, I need to find some time to update the threads
