### ISSUE TITLE
REQ: Unshrink data partition

### ISSUE THREAD

**Issue by b16r05** [topjohnwu/Magisk#2503]
Hello!
 Not sure if this has happened, but I think my data partition has shrunk. My device (s10e) used to show 107 GB, now it shows ~ 15.7 GB. Is there a way to un-shrink data partition and restore it? I have TWRP at the moment. Was about to install LOS17.1 but stopped.

Reason: I did the stupid thing even though you asked not to, "**Never flash only an AP file, as Odin can shrink your /data file-system if you do.**" Someone in the forums had a thorough, detailed post, saying to flash tarred files to AP slot (did not mention by themselves or with other files as well).
Thanks!

**Comment by topjohnwu** [comment]
I dunno how to fix that, please ask in forums
