### ISSUE TITLE
Magisk Hide stops working if installing any module

### ISSUE THREAD

**Issue by Senliast** [topjohnwu/Magisk#2505]
I have Android 10, and latest Magisk Stable 20.3, also I did clean reinstall of Magisk.

Magisk Hide works fine if no modules installed, but if installing any single module, (NO MATTER WHICH ONE!), all apps, for which Magisk Hide is selecting, starts to detect root.

On my pixel 2 on Android 9, it doesn't happen, Magisk Hide works fine with modules.

**Comment by Senliast** [comment]
May i ask why u closed it? Its obviously a Magisk problem.

**Comment by wangdaning** [comment]
Go back to main issues page and check the first pinned issue.

**Comment by Didgeridoohan** [comment]
I would say that it's more a matter of not using the latest Canary build (100% necessary when reporting about bugs) and not including any kind of log whatsoever...

**Comment by Senliast** [comment]
I tried to install latest canary build build, now my phone doesn't boot anymore, even if installing official build, seems the encryption is broken. I have to reinstall it.

And what does my issues have to do with the pinned one?? I am not asking "fix root detection in the app x" but I am saying that magisk hide stops working for all apps, if installing a module! That must be a general issue of magsik...

**Comment by Didgeridoohan** [comment]
It doesn't have anything to do with the pinned issue, which is why I wrote my message...

**Comment by wangdaning** [comment]
Was my mistake, apologies.
