### ISSUE TITLE
Install magisk v20.0 build from source failed, but Magisk-v20.0.zip from official release success.

### ISSUE THREAD

**Issue by eagle518** [topjohnwu/Magisk#2508]
As the title show, I build v20.0 source and flash zip in twrp suceess, but no magisk after restart.
then i reinstall Magisk-v20.0.zip from official released and success, why?

英文不咋的，中文再描述一遍：
根据v20.0源码编译后通过twrp安装，刷机显示成功，但开机后发现magik安装失败；
然后若直接安装官方编译好的Magisk-v20.0.zip则magisk安装成功，对比发现magiskinit&magiskinit64不同，替换为自行编译版则会安装失败。

**Comment by mickelfeng** [comment]
how do you solve the problem?

**Comment by mickelfeng** [comment]
> As the title show, I build v20.0 source and flash zip in twrp suceess, but no magisk after restart.
> then i reinstall Magisk-v20.0.zip from official released and success, why?
> 
> 英文不咋的，中文再描述一遍：
> 根据v20.0源码编译后通过twrp安装，刷机显示成功，但开机后发现magik安装失败；
> 然后若直接安装官方编译好的Magisk-v20.0.zip则magisk安装成功，对比发现magiskinit&magiskinit64不同，替换为自行编译版则会安装失败。

你好，你是怎么解决这个问题的？
