### ISSUE TITLE
[RMX2030] Unsupported/Unknown image format

### ISSUE THREAD

**Issue by fertion** [topjohnwu/Magisk#2510]
I want to root my phone through boot.img patching since I couldn't find any custom recovery on internet. Then I got this message.

- Device platform: arm64-v8a
- Copying image to cache
- Unpacking boot image
! Unsupported/Unknown image format
! Installation failed

Device : Realme 5i RMX2030
boot.img file : [https://drive.google.com/open?id=1214-n0DVVZONDB7KnY7cmjtjBvaAsyFX](url)
I extracted it from zip update from realme official site (RMX2030EX_11_A.16)

Waiting for your response. Thanks.

**Comment by shakalaca** [comment]
You have to decrypt boot.img before patching.

**Comment by fertion** [comment]
> You have to decrypt boot.img before patching.

how? I'm newbie

**Comment by osm0sis** [comment]
> > You have to decrypt boot.img before patching.
> 
> how? I'm newbie

You'll have to check your device forum for how to decrypt your OEM's OTA boot.img. It's beyond the scope of Magisk, so please close this issue.
