### ISSUE TITLE
Unable to write system permission on native Android 10 because of dynamic partition

### ISSUE THREAD

**Issue by a447948814** [topjohnwu/Magisk#2514]
It seems that the problem is：https://github.com/topjohnwu/Magisk/issues/2520

**Comment by a447948814** [comment]
Like these models：xiaomi 10、xiaomi 10 pro、redmi k30 5G、and so on...

**Comment by a447948814** [comment]
By the way, the Mask.20.3， can't be swiped directly through the twrp

**Comment by skittles9823** [comment]
This isn't something Magisk can fix.

You can't mount logical partitions as read, write.

**Comment by a447948814** [comment]
What should I do?I need to modify systeam，Can Google only solve this problem?

**Comment by a447948814** [comment]
> This isn't something Magisk can fix.
> 
> You can't mount logical partitions as read, write.

What should I do?I need to modify systeam，Can Google only solve this problem?

**Comment by linuxandria** [comment]
> > This isn't something Magisk can fix.
> > You can't mount logical partitions as read, write.
> 
> What should I do?I need to modify systeam，Can Google only solve this problem?

Do it systemless-ly of course! Isn't that the beauty of magisk?

**Comment by PeterCxy** [comment]
On devices with dynamic partitions it's only possible to use something like LineageOS Recovery or AOSP Recovery, and there's a fix in pull request #2496 for those. TWRP doesn't even support dynamic partitions yet so your link to the other issue doesn't make any sense.

**Comment by wzsx150** [comment]
this is the same as #2496 

but I will make twrp support magisk.zip mount --move

**Comment by nehaonestore** [comment]
I am unable to root my samsung galaxy S20 which I recently got it of INS region please suggest.
I successfully flashed my patched AP.tar file but phone stuck at warning screen

**Comment by osm0sis** [comment]
> This isn't something Magisk can fix.
> 
> You can't mount logical partitions as read, write.

This issue should be closed, @a447948814, there is no way to directly modify the system partition files on dynamic/logical partitions due to ext4-dedup being read-only by design.

**Comment by PeterCxy** [comment]
@osm0sis 

There exists custom ROMs for dynamic partition devices and we do not enable ext4-dedup on custom ROMs normally for this exact reason. For now the only problem of using Magisk on these custom ROMs with dynamic partitions is that it could not mount /system properly due to what is described (and fixed) in PR #2496.

**Comment by topjohnwu** [comment]
This is a limitation of Android 10's nature, not something Magisk can fix

**Comment by aIecxs** [comment]
@osm0sis how does magisk manager patch avb/dm-verity in vendor/fstab on SAR A-only super.img? is there some kind of overlay?
https://chat.stackexchange.com/transcript/119624

**Comment by osm0sis** [comment]
Not sure what I'm looking at there, but my understanding is all the fstab stuff happens on-the-fly now during init.
