### ISSUE TITLE
Magisk doesn't support TWRP 3.4.1b of Android 10

### ISSUE THREAD

**Issue by a447948814** [topjohnwu/Magisk#2520]
Because the mount command of Magick is not compatible with Android 10's rec environment when mounting partition, so it can't mount system correctly and get environment information correctly. The obvious feature is that when the card is swiped, it recognizes that the system environment is arm, not arm64. Obviously, arm64 is right. 

( Reference: https://weibo.com/6033736159/IxkSrznql  )

**Comment by wangdaning** [comment]
Do the older versions of TWRP work?

**Comment by PeterCxy** [comment]
1. Does TWRP 3.4.1b even exist? I just checked their source tree and I'm 100% sure their version is still 3.3.1. (reference: https://github.com/TeamWin/android_bootable_recovery/blob/android-9.0/variables.h#L20)
2. TWRP has never supported Android 10's dynamic partitions, so you may need to try AOSP Recovery or LineageOS Recovery with PR #2496 applied.

**Comment by wzsx150** [comment]
this is the same as #2496 

but I will make twrp support magisk.zip mount --move

**Comment by osm0sis** [comment]
Yep, this should be closed. TWRP has barely started their Android 10 bring-up, and until they finish and figure out how they're going to support things there's no point trying to support a (very early) WIP in Magisk.
