### ISSUE TITLE
All versions from 19.1 and onward do not allow software to click.

### ISSUE THREAD

**Issue by BadWolf0081** [topjohnwu/Magisk#2522]
Hello:  Myself and many others use magisk and love the product however any version above 19.0 (19.1 and onward) will only allow our software to click the screen 5 or 6 times before it can't click on anything anymore.  We need it to be able to click on the screen continually like it can in 19.0 and below.

This is a bigger issue now since Smali is no longer working on older versions like 18.1 and some phones don't work with 19.0 that used to with 18.1, going to a newer magisk works but then they stop clicking the screen after 5 or 6 clicks until you reboot.

**Comment by linuxandria** [comment]
Could you link your app?

**Comment by BadWolf0081** [comment]
> 
> 
> Could you link your app?

https://github.com/Map-A-Droid/MAD/blob/master/APK/RemoteGpsController.apk

**Comment by Grennith** [comment]
For reference, the clicks are called via `input tap <X> <Y>`

**Comment by muckelba** [comment]
You can use [this script](https://github.com/Map-A-Droid/MAD/blob/master/mapadroid/websocket/dummy_debug_rgc.py) to run a small websocket server where RGC (RemoteGpsController) can connect to. The syntax to send touch commands from the server to the phone is: `screen click <x> <y>`.

**Comment by osm0sis** [comment]
Any chance this is intentional to avoid hijacking of your root control?

**Comment by muckelba** [comment]
Not sure, but automated clicking is a typical usecase for apps like tasker and such, isn't it?

**Comment by topjohnwu** [comment]
@BadWolf0081 there is nothing regarding to root is changed from v19.0 to v19.1.
If your app is simply calling commands using a root shell, then the issue lies in the device itself, not Magisk.

**Comment by Grennith** [comment]
> @BadWolf0081 there is nothing regarding to root is changed from v19.0 to v19.1.
> If your app is simply calling commands using a root shell, then the issue lies in the device itself, not Magisk.

I don't wanna disappoint, but that issue is across a broad variety of ROMs and devices
