### ISSUE TITLE
Allow manual module install abort

### ISSUE THREAD

**Issue by linuxandria** [topjohnwu/Magisk#2523]
I wish there was a in-UI way to foribly abort a module installation.

Backstory:
I was experimenting with logic that utilized a while...do loop, and, well, forgot the exit condition. I also verbosely logged to /sdcard. I only noticed something was wrong when I ran out of space on my 256 GB device becuase of my 200GB log file.
While that tale is I'm sure amusing, I had to force stop manager to make install end. It would be nice to have a straightforward way to do this.

The flow would be:
1. Install module
2. "Oops I don't want to do that;'
3. Hit abort button (maybe beside save icon).
4. Confirmation dialog "Do you really want to abort install?"
5. If answer is yes, call abort() and end installation

**Comment by topjohnwu** [comment]
@linuxandria there is no way I can safely stop an installation.
What you are doing here (force closing the app) will likely put your device in some unusable state if a module installation script is doing some weird stuff. The module installation scripts are not ran in a sandbox, they run in root.
