### ISSUE TITLE
Magisk Hide - mountpoints are not hidden

### ISSUE THREAD

**Issue by Senliast** [topjohnwu/Magisk#2524]
Hey, I already opened an issue, because magisk Hide stops working for many apps after enabling any module, that mounts files, but you closed it. Now, I made some researches and hope, I have enough informations, to be useful for you.

So, I have a Pixel 2 with Android 9 and a Xiaomi Mi 9T Pro with Android 10, both Magisk 20.3.
If I install modules on the Pixel - everything fine, the mountpoints are hidden, the banking app, i test it with starts, but if on the Xiaomi - the mountpoints are still visible and the banking app crashes. Of course, I enabled Magisk Hide on both devices. The program, I am using to monitor partitions changes, called DiskInfo. May be it's a problem with Android 10, or with certain ROMs / Devices?

Here are also screenshots attached.

![cv_1583531272506](https://user-images.githubusercontent.com/23285435/76125871-077a2a00-5ffe-11ea-88e7-49fb884394ed.jpg)
![cv_1583531460377](https://user-images.githubusercontent.com/23285435/76125876-09dc8400-5ffe-11ea-90fc-689eeaa455e4.jpg)
![cv_1583531363597](https://user-images.githubusercontent.com/23285435/76125581-6a1ef600-5ffd-11ea-89b0-5135978bb0b0.jpg)
![cv_1583531329049](https://user-images.githubusercontent.com/23285435/76125587-6be8b980-5ffd-11ea-9a93-29e8143f244f.jpg)
![cv_1583531236933](https://user-images.githubusercontent.com/23285435/76125597-6ee3aa00-5ffd-11ea-96db-bfb45a6bf048.jpg)

**Comment by Emulatorer** [comment]
#1152

**Comment by kam821** [comment]
@Senliast 
I think it may be related https://github.com/topjohnwu/Magisk/issues/2406

**Comment by topjohnwu** [comment]
Xiaomi doing dumb shit, I'm not surprised.
I don't have any Xiaomi device to test on, so unless someone is willing to investigate and create a PR, it will not get fixed.
