### ISSUE TITLE
Bootloop When Flashing Patched boot.img

### ISSUE THREAD

**Issue by xXHenlolXx** [topjohnwu/Magisk#2525]
Hello, I just updated my Mi Mix 3 to android 10 (released today). As I don't want to use twrp, I decided to use the method of patching boot.img, but this is giving me bootloop. It remains on the Xiaomi boot screen, it doesn't even go to the booting animation.

Thanks in advance.
[boot.zip](https://github.com/topjohnwu/Magisk/files/4301104/boot.zip)

Edit: So I tried to flash Magisk using twrp, but the bootloop problem persists.

**Comment by sabpprook** [comment]
probably the same problem to this issue https://github.com/topjohnwu/Magisk/issues/2492

**Comment by xXHenlolXx** [comment]
I don't think so. The device is not rebooting to recovery, it ain't booting. I was already using the 7.5.1 manager to create patched boot.img and v20.3 when flashing. The weird thing is that Magisk was working before (also MIUI 11, but android 9).

**Comment by klemenko1** [comment]
My phone doesn't boot when i install magisk. It happens with patched boot.img and with TWRP install. So i guess no root for me. I've tried everything. 

Mi A3 Android 10 V11.0.7.0.QFQMIXM

**Comment by osm0sis** [comment]
Please close this Issue since it sounds like it's a duplicate.
