### ISSUE TITLE
#2534

### ISSUE THREAD

**Issue by S555555** [topjohnwu/Magisk#2537]
#2534

**Comment by S555555** [comment]
Bxbdnfjff

**Comment by Justsnoopy30** [comment]
Stop spamming issues mentioning an issue.

**Comment by S555555** [comment]
#2534

**Comment by S555555** [comment]
#2537

**Comment by S555555** [comment]
S555555

**Comment by 488315** [comment]
Stop

**Comment by S555555** [comment]
#2004

**Comment by S555555** [comment]
#2030

**Comment by S555555** [comment]
#2534

**Comment by 488315** [comment]
Can you stop spamming @topjohnwu please close this

**Comment by Justsnoopy30** [comment]
Check the profile of @S555555. Clearly a spam account.

**Comment by 488315** [comment]
Reported to GitHub 
    	
    	

    	Get Outlook for iOS
    
  




On Thu, Mar 12, 2020 at 3:39 PM -0700, "Justsnoopy30" <notifications@github.com> wrote:















Check the profile of @S555555. Clearly a spam account.

**Comment by S555555** [comment]
#2534

**Comment by S555555** [comment]
#2534

**Comment by Justsnoopy30** [comment]
> Reported to GitHub Get Outlook for iOS On Thu, Mar 12, 2020 at 3:39 PM -0700, "Justsnoopy30" <notifications@github.com> wrote: Check the profile of @S555555. Clearly a spam account. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Good :)

**Comment by S555555** [comment]
#2537

**Comment by Justsnoopy30** [comment]
Just reported too.
