### ISSUE TITLE
Magisk instalation failed on Ulefone Power

### ISSUE THREAD

**Issue by szamuka** [topjohnwu/Magisk#254]
I can't install magisk on Ulefone Power

![19686593_1326821510765021_464237436_o](https://user-images.githubusercontent.com/21019458/27712677-68492d94-5d28-11e7-9e16-6a423efb5538.png)

**Comment by JERW86** [comment]
Magisk-v13.0(96f8efc) is no longer the latest beta. Flash your unmodified boot.img again and try [v13.0(54e6a79)](https://forum.xda-developers.com/apps/magisk/beta-magisk-v13-0-0980cb6-t3618589).
