### ISSUE TITLE
Public statement on current situation

### ISSUE THREAD

**Issue by SachseConstruct** [topjohnwu/Magisk#2540]
Hello, my name is Todd Sachse and this is my public statement regarding whole Magisk situation.

First of all, dear John, I understand the struggle you have to go through every day, but there's the thing called responsibility. Every adult does know about that and you have to be responsible for your actions and consequences of your actions. Thus, your software may be licensed without warranty, but your actions aren't. You created this software and responsible for that. Therefore, my moral and financial damage is result of your actions, not your software.

Secondly, I have received rude messages from this individual @osm0sis and I'm not happy about that. I come to your with respect and you hit me with disrespect. I and my lawyers currently discuss methods of punishment for your behavior. Trust me, if we can't do this legal way, I'll make sure you will have consequences alter way.

Third, I read all the comments and we decided to sue both Google and John Wu due my moral damage and my company's financial damage.
BUT, I give John 24 hours to compensate my moral and financial damage, and we will not go to court. I will soon send you an email with full calculation.

Best regards,
Todd

**Comment by osm0sis** [comment]
Every adult knowing about being responsible would indicate you need to take responsibility for your choice unlocking and rooting your device.

**Comment by xCuri0** [comment]
fuk off nigga

**Comment by Didgeridoohan** [comment]
![net-troll](https://user-images.githubusercontent.com/14870954/76611479-df695a00-651a-11ea-84cb-9691503ce82a.jpg)

**Comment by topjohnwu** [comment]
@SachseConstruct I am not responsible for your own decision to unlock your bootloader. If you want to fix your phone, restore your device back to stock, and relock the bootloader.

**Comment by topjohnwu** [comment]
I can very easily prove to you that even without Magisk, your bank app will still not work since you unlocked your bootloader. If you think this is not acceptable, you should complain to your bank and Google, as they are the one who both decide the boundary where to draw the line.

This will be the last time I response to you.
