### ISSUE TITLE
Default magiskhide behavior

### ISSUE THREAD

**Issue by linuxandria** [topjohnwu/Magisk#2541]
As of right now we are not entirely sure what the final state of CTS is going to be. Some users are reporting they are once again passing when they had started failing. 

In addition, basicIntegrity is still fooled by magiskhide (which some apps only check that not CTS) and some apps don't rely on Safety net at all.

However in 612b51d48f9771a65cfab045f931573f42d3a494 you have changed default magiskhide behavior. I think at the very least that commit needs reevaluating.

My preferred solution is to ask the user of magisk manager first run

**Comment by linuxandria** [comment]
We all know Google loves to roll things out, roll it back, roll it out, change it, and then forget it, then roll out something different. We should probably wait to see what the final product will be

**Comment by Justsnoopy30** [comment]
Looks like the roll it back part came true. I have not done anything since last night when cts profile was failing and today me and other people are seeing that it is passing.

**Comment by Justsnoopy30** [comment]
+1 to change magiskhide back to enabled by default.

**Comment by Justsnoopy30** [comment]
An assigned was added to the issue on the issue tracker.
https://issuetracker.google.com/issues/151316418

**Comment by Justsnoopy30** [comment]
And just overnight the issue went from 11 stars to 137 stars.

**Comment by osm0sis** [comment]
I feel like it was a warning shot from Google, and maybe MagiskHide should stay disabled by default to help appease them. :grinning:

**Comment by JoshuaDoes** [comment]
@osm0sis I almost wanna reply with nothing but ":eyes:"

**Comment by Sumit3301** [comment]
I hope it stays that way forever but it probably wont :/

**Comment by kinesight** [comment]
I also got 2 Green Ticks 😬 Yesterday it wasn't like thisssssss 👀

**Comment by topjohnwu** [comment]
It is very clear at this point that Google is willing to use key attestation for SafetyNet checks, I don't see a point fighting a non winning battle.

The functionality is not removed, it is just no longer enabled by default, as I do want to let people understand that this will not stay long.

**Comment by linuxandria** [comment]
> It is very clear at this point that Google is willing to use key attestation for SafetyNet checks, I don't see a point fighting a non winning battle.
> 
> The functionality is not removed, it is just no longer enabled by default, as I do want to let people understand that this will not stay long.

Nonetheless every app that doesn't use CTS checking will still pass with Hide on. People will not understand why now _every_ app detects root by default.
In addition the new CTS checking **only checks bootloader status** not actual root, which Hide is still useful for

**Comment by osm0sis** [comment]
If you care about hide just turn it on...

**Comment by osm0sis** [comment]
Cleaned up and pinned to catch any further discussion 👍

**Comment by linuxandria** [comment]
Also irritating enough it shuts it off if I had it on.
As I own a OnePlus device and hardware attestation was never an issue anyway that's highly annoying to have to find out why safety net it suddenly tripped especially if I didn't already know this changed behavior

**Comment by osm0sis** [comment]
That shouldn't be the case.. I'm on latest Canary and MagiskHide has never shut itself off.

**Comment by linuxandria** [comment]
Every time I reflash magisk it does that

**Comment by osm0sis** [comment]
> Every time I reflash magisk it does that

Uh, not intended. Works fine here.
