### ISSUE TITLE
Canary Magisk Manager crashes on pre-Android 5.0

### ISSUE THREAD

**Issue by martobg10** [topjohnwu/Magisk#2544]
### What are the issues I have:
* Graphical issue (_screenshots at the end_)
* Magisk Manager crashes ([Updated Logcat from March 29, 2020](https://my.pcloud.com/publink/show?code=XZ1QGMkZynnh4RwJm4jHDN1O6EqaeBaN4n4X))

### In which version of Canary Magisk Manager is this happening:
`Canary Debug ef9d077c (279)`
_[Build date: March 28, 2020]_

### Device specifications:
_Device_: Alcatel Pixi 3 7" 3G /9002X/     _(tablet)_
_OS_: Android Kitkat 4.4.2
_RAM_: 512MB
_CPU_: MT8312 _(not sure)_

### Notes:
I don't have these problems with Stable Magisk Manager 7.5.1 (267) (7).

### Screenshots describing the graphical issue:

![Screenshot_2020-03-29-21-55-48](https://user-images.githubusercontent.com/44940748/77858429-2a1dee00-720c-11ea-9438-371b73df749e.png)
![Screenshot_2020-03-29-21-55-30](https://user-images.githubusercontent.com/44940748/77858428-29855780-720c-11ea-83b1-bf4912c14cd2.png)

**Comment by topjohnwu** [comment]
What Android version are you on?
The app currently isn't rigorously tested on old platforms

**Comment by martobg10** [comment]
@topjohnwu,

**Device:** Alcatel Pixi 3 7" 3G /9002X/
**OS:** Android 4.4.2
**RAM:** 512MB
**CPU:** MT8312 _(not sure)_

**Comment by skittles9823** [comment]
@topjohnwu you should be able to test it on AOSiP Pie on the nexus 5x, it happens to me on that.

**Comment by osm0sis** [comment]
Is this a different graphical issue from #2506?

**Comment by diareuse** [comment]
This is completely different from what I can see. It doesn't even have insets applied, so something must've gone fundamentally wrong lol 🧐

**Comment by martobg10** [comment]
I uploaded a new logcat, using the newest version of Canary Magisk Manager. The download link will no longer disappear. I added new screenshots because I have a new graphical issue(it is on the first screenshot). Before, the background wasn't black.
I also rewrote the post to make it more useful.

I have another problem, the Magisk Manager does not find the boot image, which is visible in the second screenshot, but I will make a new issue.

**Comment by martobg10** [comment]
Why did you close this? The UI issues seen on the screenshots are still available. Also, the crashing problem with Magisk Manager is also not fixed. Only issue with the black background color is fixed.

**Comment by osm0sis** [comment]
Ah, I misunderstood. Thought you were saying it was resolved. :+1:

**Comment by diareuse** [comment]
Just a clarification:
The #2506 fixes UI issue where window background is not set correctly. Your logs, however, show significant crashes in ViewCompat which are beyond our reach. We'll need to wait until Google gets this resolved.

**Comment by martobg10** [comment]
@diareuse,
I'm with Android 4.4.2.
I don't think Google will fix this problem for such an old version of Android. Even if they do, I don't believe that Alcatel will put an update on a 5-year-old tablet. On my Pocophone F1 with Android 10, I absolutely don't have any UI issues with the new design of Magisk Manager, unlike other people I see that open new issues here.
**And my issues with the UI are with new design, on the stable version of Magisk Manager, I don't have any of these UI problems.**

**Comment by diareuse** [comment]
This is an update through library we include, not a system update. They **will** fix it eventually, since it produces crashes up to API level 28, where the requested API actually exists.

Stable version doesn't use window insets (transparent nav/status bars), hence it doesn't crash nor hides underneath it.

**Comment by topjohnwu** [comment]
The latest canary is now fully tested and runs perfectly on Android 4.2+
