### ISSUE TITLE
updating manager from 277 to 278 unhides it and breaks magisk updates

### ISSUE THREAD

**Issue by yepyepyep4711** [topjohnwu/Magisk#2550]
I have a hidden Manager (277) and Magisk is (20306). I'm using the canary channel, Android 9 and a OnePlus5.

If I update Manager by tapping the "update available" notification, the updated Manager won't hide itself, will not replace the older version and Magisk Updates will not offer "Direct Install" as a method anymore. Thankfully I was able to delete the new version and will stay with the old one until there is a solution. If more details are needed, ask away! Thanks all and cheers. (Stay in front of your screens, it will keep you safe from Corona :wink:)

**Comment by osm0sis** [comment]
This didn't occur on my OP7T. Can you try again with the next Canary?

**Comment by osm0sis** [comment]
Hidden Manager updates are broken completely with Manager Canary 279, and @topjohnwu has reworked the stub, so once #2595 gets fixed, this will likely be resolved too.

Follow along there, and report if it's still an issue with the next Manager Canary (280).

**Comment by yepyepyep4711** [comment]
Exact same issue moving from 282 to 283
