### ISSUE TITLE
Huawei P20 Pro (CLT-L29) bricked after dtbo.img patch @ Magisk Canary [72f6770d]

### ISSUE THREAD

**Issue by psyphreak** [topjohnwu/Magisk#2552]
I'm an owner of a CLT-L29 (CLT-LGRP2-OVS) device running EMUI 9.1.0.380, and yesterday when I've updated to the latest canary build [https://github.com/topjohnwu/magisk_files/blob/canary/app-release.apk (72f6770d - 278)], my watch [and the only place I've "the proof" (of what happenned to my device)] showed me a warning (image attached), and after initiating the reboot, my device went dead and have been like that the previous 24h [almost 48h now..] without any hardware buttons even working.. I can't seem to charge the phone, or even turn it on adb/fastboot modes, and since it "messed" with dtbo.img, could this mean that the main "device tree" for HW detections on boot, got screwed and I lost the phone entirely?! 😞 please help me out, I'm "without hope" and even words for this, I just need to know.. 😔 if the phone can be restored, in some sort of way, or if it's possible.. thanks, once again, for your time!

![DTBO](https://user-images.githubusercontent.com/7433528/76790303-80c00c80-67b6-11ea-8712-f20b2885f94d.png)

**Comment by topjohnwu** [comment]
You should be able to reboot to erecovery mode or fastboot mode to flash stock images
