### ISSUE TITLE
Stuck on flashing boot.img

### ISSUE THREAD

**Issue by TheRealLouCipher** [topjohnwu/Magisk#2554]
Trying to patch boot.img but it gets stuck on flashing. Running latest Canary 20307 on Pixel 3 XL Android 10 february update.
![Screenshot_20200317-110116](https://user-images.githubusercontent.com/41365311/76845792-b957f880-683f-11ea-88a3-a2d1f393617d.png)

**Comment by zhenchao** [comment]
Patching boot.img will freeze when there is magisk.zip in /data/data/com.topjohnwu.magisk/cache.
After removing magisk.zip, patching works normally once

**Comment by TheRealLouCipher** [comment]
@zhenchao Thanks a bunch! Works like a charm!

**Comment by zhenchao** [comment]
> @zhenchao Thanks a bunch! Works like a charm!

No thanks, but I don't think it's time to close this issue
