### ISSUE TITLE
Broken ramdisk patching AMLogic AMLSECU! signed boot.img

### ISSUE THREAD

**Issue by zhenchao** [topjohnwu/Magisk#2555]
Device Model:MiBox 3s (MDZ-19-AA)
SoC:AMLogic S905X-H
MIUI TV 1.5.63 (Android 6.0)
Stock boot:[link](https://1drv.ms/u/s!ArpHBtnXvt7HxS6ZxWm92GCJBU6x?e=Vozh0M)

log:
`- Device platform: arm64-v8a
- Copying image to cache
2034+0 records in
2034+0 records out
2082816 bytes (2.0MB) copied, 0.033044 seconds, 60.1MB/s
1410+1 records in
1410+1 records out
1443916 bytes (1.4MB) copied, 0.024592 seconds, 56.0MB/s
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [6961152]
RAMDISK_SZ      [929792]
SECOND_SZ       [38912]
EXTRA_SZ        [0]
PAGESIZE        [2048]
NAME            []
CMDLINE         []
CHECKSUM        [18401b41c3c3cb4df2af95d1b4109ef9eead8b25000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [raw]
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
bad cpio header
- Magisk patched boot image detected
Loading cpio: [ramdisk.cpio]
bad cpio header
Loading cpio: [ramdisk.cpio]
bad cpio header
- Patching ramdisk
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [6961152]
RAMDISK_SZ      [929792]
SECOND_SZ       [38912]
EXTRA_SZ        [0]
PAGESIZE        [2048]
NAME            []
CMDLINE         []
CHECKSUM        [18401b41c3c3cb4df2af95d1b4109ef9eead8b25000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [raw]
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [6961152]
RAMDISK_SZ      [929792]
SECOND_SZ       [38912]
EXTRA_SZ        [0]
PAGESIZE        [2048]
NAME            []
CMDLINE         []
CHECKSUM        [fd74bdacb7851baf01fdef276abcd77a27330bdf000000000000000000000000]

****************************
 Output file is placed in 
 /storage/emulated/0/Download/magisk_patched.img 
****************************
- All done!
`

**Comment by osm0sis** [comment]
Ramdisk format is nothing I've ever seen before.

```

Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers

Supplied image: MiBox3s_boot.img

Setting up work folders...

Image type: AOSP

Splitting image to "split_img/"...
BOARD_KERNEL_CMDLINE 
BOARD_KERNEL_BASE 01078000
BOARD_NAME 
BOARD_PAGE_SIZE 2048
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 00008000
BOARD_RAMDISK_OFFSET fff88000
BOARD_SECOND_OFFSET ffe88000
BOARD_TAGS_OFFSET fef88100
BOARD_HEADER_VERSION 0

Unrecognized format.
Error!
```

That means my file binary magic list didn't recognize it at all.

![Screenshot_20200317-124556](https://user-images.githubusercontent.com/2858716/76874027-4d7c8c80-684d-11ea-9980-1ad20da41b2d.jpg)

**Comment by shakalaca** [comment]
Just notice there's a "AMLSECU!" string in boot.img and do a quick search, I think this repo is for S905X : https://github.com/znly/uboot-amlogic/blob/master/common/cmd_imgread.c

Got a lot work to do ...

**Comment by osm0sis** [comment]
Oof, so they put some kind of uboot inside a normal boot.img? Weird, it doesn't even match normal uboot magic.

**Comment by osm0sis** [comment]
@shakalaca I'm not even sure that uboot fork would be able to build the Android bootimg we see above. :confused:

**Comment by osm0sis** [comment]
I'll leave it for @topjohnwu to inspect the boot.img and AML source link above, but basically, if this is a new variant of their AMLSECU! idea, and it means simply that the ramdisk is encrypted (which is how it looks), then there's probably no way to support this without their key to decrypt it back to .cpio.gz.

**Comment by James4Deutschland** [comment]
bro I've got my mi mix 2 phone kernel built but no way to unpack the old boot.img, saying there's an unrecognized format.
i'm using twrp official app for image extraction.

**Comment by James4Deutschland** [comment]
would it be fine using aosp to rebuild a boot.img and flash it back?

**Comment by James4Deutschland** [comment]
by the way it is fine to only separate kernel and ramdisk.cpio.gz alone using some unpack tool, but how do i suppose to do to unpack the kernel file? seems to be gzip format but can't extract. no way to get that boot.img-zImage file.

**Comment by osm0sis** [comment]
Do not hijack Issues for unrelated devices. Go ask on xda in the Magisk General Discussion thread and someone will help you.

**Comment by osm0sis** [comment]
Well, I'm 95% sure this isn't doable with what we currently know, so I'm closing it.
