### ISSUE TITLE
Freeze and reboot since 20.2 version (20.2以上版本系統會凍結之後重開)

### ISSUE THREAD

**Issue by Bob-YsPan** [topjohnwu/Magisk#2557]
I tried to install Magisk on my stock android 6.0 rom, It freezes since upgrade to 20.2 version Magisk
When the system startup almost done it freezes(Charging LED lit, sometimes it loading lock screen)
Downgrade to 20.1 works fine.

Phone: Asus Zenfone 2(ZE551ML), Intel Atom Z3580
My phone used Borets24 custom kernel now, I tried to flash stock kernel problem still the same.
I also use this site tool to sign the boot image to pass boot signature check
https://forum.xda-developers.com/zenfone2/development/script-boot-recovery-image-signature-t3690522
(Sorry for my bad English)

Chinese description below:
我嘗試安裝Magisk在我原生rom的Zenfone 2(ZE551ML)上，當系統快啟動完成的時候(充電指示燈會亮，有時候會出現鎖定畫面)會凍結重開
降版至20.1後目前使用正常

我手機目前有用Borets24的第三方內核，但是換成原廠內核問題一樣
另外我有用這個工具簽名boot image讓系統可以順利啟動
https://forum.xda-developers.com/zenfone2/development/script-boot-recovery-image-signature-t3690522

**Comment by osm0sis** [comment]
Try with the latest Canary please.

**Comment by shakalaca** [comment]
No problems on my ZenFone 2 with Canary build (20308) :)

**Comment by Bob-YsPan** [comment]
Oh... Yes, the latest canary version work!

I also tested on my phone, It boots up like screenshot below.

Hope this fix can added to the next stable release😃

![Screenshot_20200321-004218](https://user-images.githubusercontent.com/46966555/77185876-10462200-6b0d-11ea-8252-8ce8dbe0b6af.png)
