### ISSUE TITLE
Random Reboots on v20.1

### ISSUE THREAD

**Issue by iPlasmaTechy** [topjohnwu/Magisk#2558]
I keep on getting random reboots/boot loops on Magisk v.20.1. This also happened on Magisk v20.3. Here are my logs. My device is Samsung A50 running Android 10
[magisk_log_20200318_191944.log](https://github.com/topjohnwu/Magisk/files/4349411/magisk_log_20200318_191944.log)

**Comment by osm0sis** [comment]
Try with the latest Canary please and provide logs.

**Comment by iPlasmaTechy** [comment]
> Try with the latest Canary please and provide logs.

Canary didn't work last time I tried... Can you provide me with a link to the latest version of canary? By the way, my device uses Treble.

**Comment by osm0sis** [comment]
Switch to the custom channel in Manager using this link: https://bit.ly/2oIlk3A

Update Manager and Magisk through it.

**Comment by iPlasmaTechy** [comment]
> Switch to the custom channel in Manager using this link: https://bit.ly/2oIlk3A
How do I do that? Also my recovery is bootlooped but my normal one is working fine..

**Comment by iPlasmaTechy** [comment]
Magisk also crashes when I try downloading the file to zip file to flash

**Comment by osm0sis** [comment]
Install app-debug.apk manually from here: https://github.com/topjohnwu/magisk_files/tree/canary?files=1

**Comment by iPlasmaTechy** [comment]
> Install app-debug.apk manually from here: https://github.com/topjohnwu/magisk_files/tree/canary?files=1

Magisk still crashing

**Comment by osm0sis** [comment]
Open a new issue and provide logs from Canary.

**Comment by iPlasmaTechy** [comment]
Direct install missin & error
`- Mounting /system, /vendor
! Cannot mount /system
- Unmounting partitions
Updater process ended with ERROR: 1`

**Comment by iPlasmaTechy** [comment]
Wait so do I patch my boot.img, convert it into .tar and flash it using odin? If so, which part of Odin? AP?

**Comment by osm0sis** [comment]
I don't own your device, so I don't know. Check your device's forum or ask in the Magisk thread for flashing details for your device.

**Comment by ShotTard** [comment]
./tsu
.

**Comment by iPlasmaTechy** [comment]
Whenever I try rebooting to magisk (recovery), my phone gets stuck in a boot loop.
