### ISSUE TITLE
4g lte problems Magisk 20.3

### ISSUE THREAD

**Issue by chuy19312** [topjohnwu/Magisk#2561]
I'm using a Hisense L675 with android 6.0, i did an factory reset on my phone and opened magisk manager and saw an message about additional setup, i installed it and now it doesn't get 4g LTE signal, i'm using Magisk 20.3 and Magisk Manager 7.5.1, i installed magisk manager as user app, also i noticed the additional setup message appears on other phones with android lollipop and marshmallow i will try to do a factory reset, if it doesn't get fixed i will give an advice to you

**Comment by osm0sis** [comment]
Try with the latest Canary

**Comment by chuy19312** [comment]
i will try, but i don't think it will work, i uninstalled an installed magisk again and nothing, when i reinstalled magisk i get an no signal in my notification bar, first i will try a factory reset and then i will try installing canary version

**Comment by chuy19312** [comment]
well, i did a factory reset but now it takes really much to get 4g mobile data and doesn't get 4g lte data, i will try with flashing an firmware and never installing magisk again, i had similar problems with other phones when i get the same message, i still will not close this issue to tell if this fixes it

**Comment by chuy19312** [comment]
well, flashed some partitions and i get mobile data again, but on wifi get an nvdata error signal, i will check how to fix it, but i will not install magisk until additional setup message gets fixed

**Comment by osm0sis** [comment]
Alright.. open a new issue if you find something reproducible on the latest Canary and have some logs. :+1:
