### ISSUE TITLE
Magisk manager canary flashing screen display problem(Magisk manager canary 刷寫模組輸出畫面問題)

### ISSUE THREAD

**Issue by Bob-YsPan** [topjohnwu/Magisk#2565]
Look like the screenshot below...
When the output fill up the whole screen and scroll, it appears a lot of ghost on the screen.

![Screenshot_20200321-100430](https://user-images.githubusercontent.com/46966555/77217506-144e6000-6b5e-11ea-8ac2-2914172899f1.png)

Device:
Zenfone 2(Intel atom Z3580)
Power VR Rogue G6430
(Sorry for my bad English again...)

Chinese Description:
像截圖那樣…
當輸出填滿了整個螢幕再加上捲動一下，畫面就會出現很嚴重的殘影。

**Comment by topjohnwu** [comment]
#2544
