### ISSUE TITLE
Magisk vce7cb1ee(20306) bootloop on Realme 2 Pro

### ISSUE THREAD

**Issue by tuyennn** [topjohnwu/Magisk#2575]
I found this issue on the Realme 2 Pro RMX1801 variants using the canary version of Magisk.

The phone can not boot up, the issue was not happened on Magisk 17.1 and 19.3
Here is the detailed log cat.

[bootlog.log](https://github.com/topjohnwu/Magisk/files/4365437/bootlog.log)

The vce7cb1ee(20306) was tried on some RMX1801 variants, some worked, some didn't

**Comment by topjohnwu** [comment]
Checked your logs, it seems like there is something messing with the rootfs mounts and does not seem to be an issue with Magisk itself, but rather the modifications you've installed.

May you try a clean install (no scripts/modules/MagiskHide)?

**Comment by tuyennn** [comment]
I tried several times which clean install the 20306 or dirty flash(upgrade on working 17.1 or 19.3), it always stuck on boot. Any suggestion with rootfs?

**Comment by tuyennn** [comment]
Hi @topjohnwu as your explanation this was caused by rootfs but how about the 19.3 version, it worked well on device, so Magisk > 19.3 broke the rootfs?
