### ISSUE TITLE
After "Hide Magisk Manager", app keeps prompting to upgrade to full Magisk Manager

### ISSUE THREAD

**Issue by jthreja** [topjohnwu/Magisk#2584]
I know this issue has been raised and closed.
I tried using the latest canary Magisk Manager and still got the same issue.

Can you please help.

logcat attached.

[logcat_03-24-2020_09-29-43.txt](https://github.com/topjohnwu/Magisk/files/4373335/logcat_03-24-2020_09-29-43.txt)

**Comment by topjohnwu** [comment]
If you need to hide, use the public stable/beta channels as they are confirmed to work
