### ISSUE TITLE
Magisk broken on Android x86

### ISSUE THREAD

**Issue by KubekSzklany** [topjohnwu/Magisk#2587]
Hello. I want to install magisk on android x86 64 bit, version 8.0 or above. I installed latest magisk, but wifi not working and I cant install any modules, even from zip package. I tried magisk 19 but it is not working too. Latest working magisk is 17.1, but i want to install module (Ar Core Enabler) which requires magisk 18+. What can i do?

**Comment by osm0sis** [comment]
You need to give more device info, your ROM and setup, your device boot.img. The log from installing Magisk in recovery, nd magisk.log and logcat after

**Comment by KubekSzklany** [comment]
Device info dont really matter, it not working on every android x86 device, for example: https://forum.xda-developers.com/android/help/wifi-issues-installation-magisk-android-t4061349 or https://forum.xda-developers.com/apps/magisk/magisk-modules-installable-android-x86-t3938622

**Comment by osm0sis** [comment]
Cool. We don't have one, so provide some details and logs like I provided or I'll be forced to close this issue.

**Comment by topjohnwu** [comment]
#2551

**Comment by osm0sis** [comment]
@topjohnwu that one's for emulators, this one is actual x86 phones.
