### ISSUE TITLE
[Question] Upgrade Magisk 

### ISSUE THREAD

**Issue by alexdonh** [topjohnwu/Magisk#2591]
Sorry I'm not sure whether it's allowed to post a question, but since you saying you no longer follow XDA thread so here I go.

My device is non-A/B and uses system-as-root so I went all the way with Magisk in Recovery method. So say if I want to upgrade Magisk, what I should do is first, patch the AP image with latest Magisk; second, Flash the magisk_patched.tar only? Or should I better flash all magisk_patched.tar, CP, BL and HOME_CSC altogether?

**Comment by osm0sis** [comment]
xda is still the place to ask installation related questions and get general support.
