### ISSUE TITLE
Commandline option to repackage Magisk Manager

### ISSUE THREAD

**Issue by muckelba** [topjohnwu/Magisk#2593]
Hey, i'm not sure if that was asked before, but is it possible to repackage the Magisk Manager from the commandline? If not, can this be added?

**Comment by topjohnwu** [comment]
Sorry, the repackage logic is very complex and is completely implemented to Java/Kotlin, so no commandline option can be easily implemented

**Comment by krzee** [comment]
there could not be a way to execute the intent from commandline so that the apk does the repackage process?

**Comment by krzee** [comment]
in case anybody comes across this hoping to find answers:
`monkey -p com.topjohnwu.magisk 1
sleep 30
input tap 39 42
sleep 5
input tap 150 537
sleep 5
input tap 315 552
sleep 5
input tap 881 277
input keyevent 61
sleep 2
input keyevent 61
sleep 2
input keyevent 66`
