### ISSUE TITLE
Manager Stuck "Flashing" a Image File

### ISSUE THREAD

**Issue by gudenau** [topjohnwu/Magisk#2596]
When attempting to patch a boot image file Magisk hangs on the "Flashing" screen. I have let it go for a good 30 minutes or so.

The boot.img is from coral-qq1b.200105.004.

boot.img SHA-1: 1ec2135830e888de2b73c37f71961b3dc425f008

![screenshot](https://user-images.githubusercontent.com/5642329/77818943-1cddf380-7094-11ea-9395-8cba88a35513.png)

**Comment by gudenau** [comment]
And it randomly decided to work. I have no idea.

**Comment by osm0sis** [comment]
I've had this happen once too. Force Closing and trying again got it to work. Manager Canary is a fickle beast right now. If it happens again grab logs and open a new issue with more info. :+1:
