### ISSUE TITLE
Out-of-box LG G2/G3 support

### ISSUE THREAD

**Issue by dcastro172** [topjohnwu/Magisk#26]

**Comment by dcastro172** [comment]
@topjohnwu Why at https://github.com/topjohnwu/Magisk/blob/master/scripts/flash_script.sh#L234 you use fingerprint instead of ro.product.brand to detect a Samsung device?

**Comment by topjohnwu** [comment]
@dcastro172  Because that's what Chainfire does in his SuperSU
