### ISSUE TITLE
Magisk 13+ prevents Call Recording

### ISSUE THREAD

**Issue by JERW86** [topjohnwu/Magisk#260]
Hi

Magisk v13.0 (c4377ed) seems to cause call recorder, package name com.skvalex.callrecorder, to fail. Recently, when I tried to record a call, a message appeared in my notifications. The message reads, "An error has occurred, this call cannot  be recorded." This happens every time I go to record a call. The app recorded calls as expected while Magisk v12 was installed but has been unable to record calls since I have been using the Magisk 13 Betas builds.

To make sure it is an issue with the Magisk Betas, I tried to record a call with Magisk v13.0 (c4377ed) installed. It failed and I got the error message mentioned above. Then I clean flashed my boot.img and flashed Magisk v12 and reinstalled Magisk Manager 4.3.3. I made a call and it recorded as expected without issue.

Steps to reproduce 

1.Download and install CallRecoder_2.4.1_alpha05 [link](https://forum.xda-developers.com/showthread.php?t=1441643)
2. Open app and grant root (root is granted)
3. Accept terms of service and app permissions.
4. App should automatically set the correct settings for a call recording 
5. Dismiss helpful hints
6. Tap/swipe on left side menu and tap settings
7. Tap recording tab 
8. toggle recording on (upper right corner)
 9. Back out and make call (I tested by calling my voicemail). 

A green circle button will appear in the right side of the phone app when ringing.
 When other end picks up or voicemail service connects the circle is supposed to automatically turn red and there is an icon that looks like a tape running in notifications. This indicates that it is recording the call.

But when Magisk v13.0 (c4377ed) is installed, when the call connects the circle button remains green and when tapped it does not turn red and a triangle icon appears in notifications. When notifications are pulled down I see the error message stated above.

Also when I go back in the call recorder app I see that the app has attempted to record the call but the the file. The recoded call deration is 0:00. Attached are Magisk logs and debug logs created by the call recorder app and a regular logcat.

I also included logs from Magisk 12 when the app is working correctly for comparison purposes and clean boot.img. I hope these are helpful.
[Magisk 13 prevents Call Recording.zip](https://github.com/topjohnwu/Magisk/files/1130122/Magisk.13.prevents.Call.Recording.zip)

Phone: XT1625 (Moto G 2016 U.S. Non-Amazon)/ROM: GZR Tesla-athene-7.1.2. OFFICIAL-20170611/Android Version: 7.1.2/Security Patch Level: June 05, 2017/Kernel: ElementalX-G4-1.08-LOS/Magisk v13.0 (c4377ed) with Magisk Manager 5.0.3/MagiskSU/microG GmsCore v0.2.4-103/NanoMod Patcher 9.2-20170610/Google Play Store/Recovery: Unofficial TWRP athene 3.1.1_shreps

**Comment by JERW86** [comment]
This is still occurring on Magisk 13.1 I have also e-mailed the the Dev of the app about the issue' New logs are attached. 
[call recorder 2.4.1Alpha 05 Magisk 13.1 Fail logcat.tar.gz](https://github.com/topjohnwu/Magisk/files/1143536/call.recorder.2.4.1Alpha.05.Magisk.13.1.Fail.logcat.tar.gz)

**Comment by robustini** [comment]
Same problem with version 13.2.

**Comment by geser2008** [comment]
I can confirm the problem.

**Comment by luckylittle** [comment]
Same here. Here is my info:
Root Access:
	Access Granted
SU:
	su found
UID/GID:
	uid=0(root)
	gid=0(root)
	groups=0(root)
	context=u:r:su:s0
Utils:
	toybox
	toolbox
Path:
	/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
Path:
	/sbin/
Version:
	13.2:MAGISKSU (topjohnwu)
Permissions:
	rwxrwxrwx
Owner:
	root:root
SELinux:
	Enforcing
BOARD           
	 angler 
BOOTLOADER      
	 angler-03.62 
BRAND           
	 google 
CPU_ABI         
	 arm64-v8a 
DEVICE          
	 angler 
DISPLAY         
	 NMF26F 
FINGERPRINT     
	 google/angler/angler:7.1.1/NMF26F/3425388:user/release-keys 
HARDWARE        
	 angler 
HOST            
	 wpds15.hot.corp.google.com 
ID              
	 NMF26F 
MANUFACTURER    
	 Huawei 
MODEL           
	 Nexus 6P 
PRODUCT         
	 angler 
TAGS            
	 release-keys 
TYPE            
	 user 
UNKNOWN         
	 unknown 
USER            
	 android-build 
CODENAME        
	 REL 
INCREMENTAL     
	 3425388 
RELEASE         
	 7.1.1 
SDK_INT         
	 25 
RADIO           
	 angler-03.78

**Comment by Avihailev** [comment]
It is very easy actually to solve the problem, the call recorder is not working not because it doesn't get root access,  from version 13 of magisk they didn't include busybox libraries, and call recorder must have it in order to work, so all you got to do is install busybox for magisk, you can find it here:
https://forum.xda-developers.com/showpost.php?p=64228091&postcount=420
It worked for me.. Enjoy..

**Comment by JERW86** [comment]
@Avihailev I have @osm0sis busybox 1.26.2 installed as a magisk module.. and call recoder from the link in the first post still doesn't work.. what version are you running? Maybe the next update he's working on will work?
 I'm running Magisk 13.3 with Manager 5.1.1
CallRecorder 2.4.1 alpha 06 with root app alpha01

New logs
[Successfully bound to service but never got onServiceConnected callback.log.txt](https://github.com/topjohnwu/Magisk/files/1161273/Successfully.bound.to.service.but.never.got.onServiceConnected.callback.log.txt)
[org.skvalex.cr.root app.log.txt](https://github.com/topjohnwu/Magisk/files/1161275/org.skvalex.cr.root.app.log.txt)

**Comment by geser2008** [comment]
Installing  busybox 1.26.2 haven't made any changes for me. Call recorder still does not 
record anything. In the debug option of Call recorder Root access checker status switches from "Yes" to "Please wait..." after making a call.
[Logcat.txt](https://github.com/topjohnwu/Magisk/files/1161802/Logcat.txt)

**Comment by antopet** [comment]
Not sure how relevant but thought I'd post in case it helps. 
Having only started using magsik over su recently and call recording being one of the main reasons for wanting root. I've always had to install ALSAMIXER to get call recording to work properly. 
I've noticed that since using magisk alsamixer is showing 
`amixer: Mixer default load error: Operation not permitted
`
both call recorder and alsamixer both have root access but like the above comment after a failed call recording root access checker on call recorder changes from yes to please wait.
Nexus 5x Stock 7.1.2 magisk 13.3 bb 1.26.2

**Comment by Avihailev** [comment]
I don't know.. It worked for me.. I'm in android 7.1.2 with magisk su 13.3 and busybox for magisk 1.25, are you sure you installed the busybox correctly? .. When I didn't had the busybox it didn't worked correctly but now it worked fine.. Did you enter the busybox manager and pressed install and got the dialog message that it installed correctly?

**Comment by antopet** [comment]
just did a double check of busybox yup installed 1.26.2

**Comment by JERW86** [comment]
[Boldbeast Call Recorder](https://play.google.com/store/apps/details?id=com.boldbeast.recorder) works for me using Magisk 13.3. I will leave this issue open for a couple more days in case someone else has more to contribute to the discussion.

**Comment by antopet** [comment]
What settings did you use with boldbeast I'll test on N5x

**Comment by noto10** [comment]
Android 5.1 on Samsung Note 4. Magisk v13.3 breaks Call Recorder v2.4. Busybox v1.27.1 installed.

**Comment by robustini** [comment]
At this time the issue has not been solved, even with version 13.3.
Maybe with version 14 will they do it? 👎

**Comment by SunsparcSolaris** [comment]
Using Stericson's BusyBox 1.27.1 and the Magisk Module BusyBox 1.27.1 will not allow skvalex's CallRecorder to work at all. Installing the Magisk module cleared my call history too, by the way.

I can provide any information needed, just need to know what to provide and how to get it.

**Comment by JERW86** [comment]
Update from the Dev of CallRecoder: [Magisk support coming soon](https://forum.xda-developers.com/showthread.php?t=1441643&p=73484126)

BoldBeast Call Recorder setting suggestions:
- Let app automatically detect settings
If call recording sounds distant or has a lot of stastic look [here](www.boldbeast.com/forum/forum1-boldbeast-call-recorder.html) for your phone settings. 
Enable root manually by tapping Settings--> Call Settings-->Fix Recording Issues-->Rooted Options Section-->Enable Root

*make sure Boldbeast app starts on boot otherwise the app will not allow you to record calls.

Since a solution have been found and Magisk support will be added to CallRecorder, I am closing this issue.
