### ISSUE TITLE
Not quite sure if we can remount system partition with r/w privilege in Android Q with Magisk.

### ISSUE THREAD

**Issue by cosinio** [topjohnwu/Magisk#2603]
I got one Android Q device, and get Magisk installed properly by pitching boot.img file. After that I want to remount system partition with r/w privilege but it doesn't work. Someone told that cause Android Q's dynamic partition feature so we have no way to access the partition. Is that true? Is there any other way to achieve that?

Also someone told that we can use magisk module to edit files in system partition, but how to do that？is there some reference for me to refer? and the most important thing is....   Is the editing work still take effect after the device reboots?

Many thanks.

**Comment by senposage** [comment]
if verity is enabled Nope

**Comment by Didgeridoohan** [comment]
Not a Magisk issue. Please close.

You'll find info on how to make a module in the documentation (check the readme for the link), and it works across reboots.

**Comment by cosinio** [comment]
Thank u for your guide and I'll close the issue.
