### ISSUE TITLE
UI of Manager ef9d077c (279) : graphical glitches

### ISSUE THREAD

**Issue by gkg2k** [topjohnwu/Magisk#2608]
![Screenshot_20200328-113438_Magisk_Manager](https://user-images.githubusercontent.com/62812519/77832209-9c230400-7134-11ea-8b8f-bf5edfdba452.png)

Hi, the latest manager ef9d077c shows hard graphical glitches on LG G4 H815 running Lineage OS 16 (9.0)

**Comment by topjohnwu** [comment]
#2598
