### ISSUE TITLE
Nexus 6P July 2017 Update: ctsProfile and basicIntegrity is false

### ISSUE THREAD

**Issue by neelchauhan** [topjohnwu/Magisk#261]
I have a Nexus 6P with the July 2017 update, rooted with Magisk and TWRP, but don't have any custom kernel or other root mod (other than the tethering trick, which was done by editing build.prop). When I do the SafetyNet check, I get both ctsProfile and basicIntegrity as false. I am using Magisk 13.0 Beta (build c4377ed).

A screenshot is below:

![screenshot_20170709-090258](https://user-images.githubusercontent.com/5403564/27994169-24d106c6-6486-11e7-897a-2beecb14e91c.png)

**Comment by multi-rom-user** [comment]
Basic methods to make it work. 
1. Enable Magisk Hide under the settings tab.
2. Ensure your USB debugging is unticked under developer options in settings. 
3. Unroot fully using magisk uninstaller package, reboot to recovery again, and reflash magisk root.

**Comment by Didgeridoohan** [comment]
If you do have Magisk Hide enabled, have you tried the age old trick of toggling Hide off and on again?

**Comment by DeicPro** [comment]
Are you try Magisk v12 + Universal SafetyNet Fix v2 Beta 4? Is in the Magisk forum

**Comment by topjohnwu** [comment]
Please don't report SafetyNet related issues unless you provide an improvement to the hide mechanism, thanks
