### ISSUE TITLE
Feature request Provide Magiskinit64 in 64 bits instead of 32 bits!

### ISSUE THREAD

**Issue by ytrezq** [topjohnwu/Magisk#2610]
Because the current 64 bits versions are compiled for 32 bits.
Should be a small enhancement.

**Comment by topjohnwu** [comment]
Not it's not, the magisk binary is 64 bit, which is what actually matters.
MagiskInit is optimized for size, and 64 bit static binaries are significantly larger.

**Comment by ytrezq** [comment]
@topjohnwu just was thinking there’s should be a reason if vendors do compile for 64 bits.
