### ISSUE TITLE
Modifying the boot.img results is the rooting warrenty efuse being triggered on the Samsung Galaxy Tab s3

### ISSUE THREAD

**Issue by ytrezq** [topjohnwu/Magisk#2611]
The signing works for being able to load the image but the kernel still detects a difference which results in:

    Set Warrenty Bit: Kernel
being displayed at the top left corner of the display on boot.

And indeed NetFlix can no longer be installed and SafeNet applications refuse to run.

**Comment by topjohnwu** [comment]
Please ask Samsung why they implemented efuse on their device, not me.

**Comment by ytrezq** [comment]
@topjohnwu sorry, I thought rooting devices while still being able to pass SafeNet was the purpose of this project.
