### ISSUE TITLE
Xperia X Perforamnce Magisk v20.4 update bootloop

### ISSUE THREAD

**Issue by worm202** [topjohnwu/Magisk#2613]
Yesterday I've updated to 20.4 through Magisk Manager (Direct flashing method). There was no error messages and I hit reboot button. But it won't start. It shows Sony logo for a while and reboots (animated logo doesn't appear).

Flashing unrooted boot.img through fastboot brings the device back to life. Installing 20.3 through TWRP - device works too. Installing 20.4 - device gets bootloop.

magisk.log doesn't seem to be generated. I have one in /cache, but it is from earlier boot before update. I'm not sure how to obtain kmsg.

Even battery screen doesn't show. When I plug charging cable - it goes to the flashmode instantly.

Device: F8132 (Xperia X Performance)
Firmware: 41.3.A.2.107 (Android 8.0)

**Comment by osm0sis** [comment]
@worm202: Give us patched images from 20.3 (working) and 20.4 (broken) so we can compare. Logs from recovery installation might also be helpful.

Is it only on upgrade, or does patching stock boot.img with stable Manager also result in a magisk_patched.img that bootloops?
