### ISSUE TITLE
Bootloop after Magisk 20.4 update

### ISSUE THREAD

**Issue by me-me-me-me** [topjohnwu/Magisk#2614]
After update from Magisk 20.3 app to 20.4 --> bootloop
disabled all modules one by one  doing reboots  at every module --> bootloop
unistalled all modules one by one  doing reboots  at every module --> bootloop
Unistalled 20.4 version  whit Magisk-uninstaller-20200323 --> phone boot ok
Reinstalled 20.4 version from recovery --> again bootloop
Unistalled 20.4 version  whit Magisk-uninstaller-20200323 --> phone boot ok
Installed 20.3 version from recovery --> phone boot ok

I'm try to get the installation and boot logs

---
Samsung A5 2017
Lineageos 16.0 20200325
fde enabled

**Comment by me-me-me-me** [comment]
From recovery.log:

- Adding addon.d survival script
java.io.IOException: unexpected end-of-contents marker
	at a.s92.a(Unknown Source:14)
	at a.s81.<init>(Unknown Source:8)
	at a.v3.a(Unknown Source:69)
	at a.a.main(:1)
- Unpacking boot image

[recovery.log](https://github.com/topjohnwu/Magisk/files/4399397/recovery.log)

**Comment by me-me-me-me** [comment]
Linked to #2594  ?

**Comment by me-me-me-me** [comment]
Not enough info?
I described the problem, listed the attempts made, put the logs, what other information do you need?
There are other issues related to version 20.4 bootloops, I'm here to help

**Comment by martobg10** [comment]
https://github.com/topjohnwu/Magisk/issues/2621
