### ISSUE TITLE
No uninstaller link in README.MD

### ISSUE THREAD

**Issue by yeliaBdE** [topjohnwu/Magisk#2615]
Having a link to the Magisk uninstaller in README.MD would be handy.

**Comment by me-me-me-me** [comment]
Having Magisk uninstaller zip preinstalled could be better

**Comment by yeliaBdE** [comment]
Agreed

**Comment by osm0sis** [comment]
Feel free to make a PR.

**Comment by yeliaBdE** [comment]
> Feel free to make a PR.

I would love to, but I know enough about what would be involved to know that I don't know enough to be able to do it. Sorry...

**Comment by osm0sis** [comment]
Okay, well @topjohnwu is well aware of what he can put in his own project's readme, so I'll close this. Thanks for your support! :slightly_smiling_face:

**Comment by sharathdaniel** [comment]
I've created a PR #2858 
Every downloads is linked in Readme, why not the uninstaller? I believe this makes people to find it easier.
