### ISSUE TITLE
Add Donation Link to Readme

### ISSUE THREAD

**Issue by diabl0w** [topjohnwu/Magisk#2616]
Please add a donation link to readme! You deserve donations!

**Comment by linuxandria** [comment]
Donation links are easily found on the home screen of Magisk Manager :)

**Comment by diabl0w** [comment]
yes, but this is the homepage of magisk

**Comment by osm0sis** [comment]
Feel free to make a PR.

**Comment by osm0sis** [comment]
@topjohnwu is well aware of what he can put in his own project's readme, so I'm going to close this. Thanks for your support!
