### ISSUE TITLE
Xiaomi on Android 10 Magisk Canary

### ISSUE THREAD

**Issue by lucenera** [topjohnwu/Magisk#2620]
I have used the last two versions from the Magisk canary branch on a Xiaomi Mi 9. With stock ROM, MIUI based ROM and AOSP based ROM, I have encountered these same problems: if I try to download a module from the Magisk repository, during the download, Magisk Manager is closed unexpectedly; or the module is downloaded, but on reboot it goes into recovery instead of rebooting the system.  Same if I try to update Magisk or Magisk Manager via Magisk Manager.
No problem on stable.

**Comment by osm0sis** [comment]
These should be resolved in the next Canary.

https://github.com/topjohnwu/Magisk/commit/a623a5b7cc46b508500aaacc47e864dc762731c6
