### ISSUE TITLE
Unable to install modules from disk in Manager version 280

### ISSUE THREAD

**Issue by Firefds** [topjohnwu/Magisk#2622]
Using Magisk Manager canary version 280, I'm unable to flash modules from disk.
When I choose a zip file the app is stuck on the animated Flashing screen. No logs are shown or updated. 
I tries both from internal and external storage.
Install from disk workes in 279.

I tried flashing the Nano module from repo. It flashes ok.
I removed it, and tried to flash it from disk - same issue, doesnt flash.

Again, nothing appears in magisk logs and flash log file is empty.

**Comment by osm0sis** [comment]
#2620
