### ISSUE TITLE
Update 20.3 to 20.4 on encrypted LOS 17.1 (Samsung Galaxy S10) currupts boot image

### ISSUE THREAD

**Issue by pascalwilhelm** [topjohnwu/Magisk#2623]
My System: Samgsung Galaxy S10 (Exynos), Magisk rooted LOS 17.1 with FDE.
Updated Magsik 20.3 to 20.4 with Magisk Manager 7.5.1
Reboot ended in bootloop (boot to the boot image, wait +/- 5min reboot). (not decrypt prompt)
I could enter Recovery (TWRP) but no decrypt prompt either. 
ADB: getprop about crypto resulted in empty responses.
I reflashed original boot image (magisk patched boot image) with Odin. --> I could again boot to the system. Now Magisk Manager shows installed version 20.4 (which is apparently not true, as I reflashed the old boot image)
--> what could have caused this issue? how can I provide better information to avoid this in the future?

**Comment by osm0sis** [comment]
Sounds similar to #2613 G

Give us patched images from 20.3 (working) and 20.4 (broken) so we can compare. Logs from installation might also be helpful.

**Comment by pascalwilhelm** [comment]
This link has the boot image provided by Ivan_Meler (xda, LOS17.1 for S10) Magisk prepatched 
https://drive.google.com/open?id=19FrkbAQjRq6S_C0mOayQIE0MZCU2Bzci


The following link has the boot image of the former after upgrade to magisk 20.4:
https://drive.google.com/open?id=14MzdGKH7sQ8lgmyzZ7GejRm_fGYEa8IM

**Comment by osm0sis** [comment]
Ramdisk is empty on your "pre-patched" one, so I don't think it was patched by Magisk.. you'll have to talk to the OP of the thread you got that from, since I'm not sure how they must have manually rooted your device to get it working.

Unfortunately that also makes this issue invalid.
