### ISSUE TITLE
Not a bug but a question on the project: how do you get /sbin/su to be executable?

### ISSUE THREAD

**Issue by ytrezq** [topjohnwu/Magisk#2626]
Because when I try to add other executables under `/sbin` at run time and set the correct dac permission and Selinux context on them, I’m getting `permission denied` (at least when not root) errors even with the correct Selinux context and dac permission applied on the files.

Also, how do I disable SeLinux?  Because using `setenforce 0` as root under adb doesn’t change anything.

**Comment by ytrezq** [comment]
@topjohnwu sorry but why no answer?

Why not documenting how Magisk works in general?

**Comment by linuxandria** [comment]
@ytrezq support questions are generally handled at the XDA thread
