### ISSUE TITLE
After installing magisk, `/default.prop` in the ramdisk from oem is no longer being used.

### ISSUE THREAD

**Issue by ytrezq** [topjohnwu/Magisk#2627]
Beside `ro.adb.secure=0` and `ro.secure=0` and `ro.oem_unlock_supported=1` and `ro.debuggable=1` are no longer set (this how I did set them permanently before installing magisk).

**Comment by topjohnwu** [comment]
These props are sensitive for detection. Disable MagiskHide if you want to keep them intact

**Comment by ytrezq** [comment]
@topjohnwu do you mean that Magisk is detected as tempering or that it simply prevents it from functioning completely?

It prevents running adb as root and thus transferring files like block device to computer directly.
