### ISSUE TITLE
Magisk safety net fails 

### ISSUE THREAD

**Issue by AleeSsandro93** [topjohnwu/Magisk#2633]
Hi, i am using redmi note 7 with magisk 20.3 and then 20.4. Since 25 March (before that day everything worked perfectly) sometimes pokemon go shows "device not compatible". The screen appears when the game identifies the root. After i close pokemon go, i check safety net in magisk, it failed. But seconds later, i tried check safety net, it suddenly pass without doing anything and i can play again. Is there something to fix this? does anyone know why this is happening? Is it a magisk or google problem? Why it only happens on some devices? It is happening to many people in the community on discord and reddit.
I am attaching a couple of links.

https://www.reddit.com/r/PokemonGoSpoofing/comments/fpo3w7/comment/fln0ccj?utm_medium=android_app&utm_source=share

https://www.reddit.com/r/PokemonGoSpoofing/comments/fpnkpx/device_os_or_software_is_not_compatible/

https://forum.xda-developers.com/apps/magisk/discussion-pokemon-magisk-discussion-t3465722/page444

https://youtu.be/3K_-ddz4uxg

pending reply, thank you in advance

**Comment by osm0sis** [comment]
#1152 

https://www.didgeridoohan.com/magisk/MagiskHideSafetyNet and XDA for further help.
