### ISSUE TITLE
[Feature Request] App Shortcut for safety net check

### ISSUE THREAD

**Issue by Charaktor** [topjohnwu/Magisk#2634]
It'd be really nice to have an app shortcut (long press app icon) for magisk manager that jumps right into the integrated safety net check, as I frequently use it, e.g. before using google pay.

**Comment by osm0sis** [comment]
@diareuse + @topjohnwu, it's also worth noting that the existing 3 shortcuts for Manager are broken currently.

**Comment by diareuse** [comment]
Yeah, it didn't get reimplemented after I moved to navigation components. And this is not a bad idea :)

**Comment by Abhi011999** [comment]
> @diareuse + @topjohnwu, it's also worth noting that the existing 3 shortcuts for Manager are broken currently; all just open the main page, Manager hidden or unhidden.

All four options (superuser, magisk hide, downloads and modules) are working fine on 7.5.1 on A10

**Comment by osm0sis** [comment]
There are only 3, but you're right, it's weirdly working again. 🤔

We just need the SafetyNet one added. :+1:

**Comment by Abhi011999** [comment]
Oh i am sorry didn't knew canaries were the context.

**Comment by zgfg** [comment]
IMO, SafetyNet test should be possible and useful in Magisk Manager even if Magisk is not installed  (currently you cannot get to the menu)- specially now when Canary 288 was extended to show (thanks for this goodie) whether CTS uses Basic or Hardware attest
![IMG_20200630_152224](https://user-images.githubusercontent.com/51943147/86135752-86cec480-baeb-11ea-9987-cb6b4ac1922e.jpg)

**Comment by diareuse** [comment]
You mean like... If you don't have [your](https://play.google.com/store/apps/details?id=org.freeandroidtools.safetynettest) [phone](https://play.google.com/store/apps/details?id=com.flinkapps.safteynet) [rooted](https://play.google.com/store/apps/details?id=com.atominvention.rootchecker) [huh?](https://play.google.com/store/apps/details?id=com.rodolphestore.rootchecker) Dunno that seems like there are no other alternatives 😏

**Comment by zgfg** [comment]
I know for the stand-alone SafetyNet checkers. But this new one in Canary Manager 288 shows whether CTS uses Basic or Hardware backed attest (and you don't have this info in the other checkers, you can only read it from logcat - for what you also need root)

E.g., for somebody with unlocked BL, if Manager would show that Hardware based CTS is forced by Google, it would mean that Magisk with Magisk Hide, spoofing device fingerprint, EdXposed, whatever, cannot help to pass SafetyNet/CTS

**Comment by osm0sis** [comment]
https://github.com/topjohnwu/Magisk/pull/2828#issuecomment-675821423
