### ISSUE TITLE
Boot loop on Samsung Galaxy Note 10+ N975F, Android 10

### ISSUE THREAD

**Issue by doclucas** [topjohnwu/Magisk#2638]
I just installed a fresh installation of Dr. Ketan latest ROM.
It comes with Magisk 20.3
Updating to 20.4 causes boot loop. Only way out is to uninstall magisk through recovery.
After successfully booting, tried to install magisk 20.4 via TWRP again. That causes boot loop again. Uninstalled.
Any way to fix this?

Thanks

**Comment by Didgeridoohan** [comment]
If the ROM includes a modified Magisk (for convenience of not having to boot through recovery), you can't expect a regular Magisk update to work. Close this issue and wait for your ROM developer to bring an update instead.

**Comment by doclucas** [comment]
Ok
