### ISSUE TITLE
Pixel C:  13.1 fails installation with "Unable to unpack boot image", regression from 13.0(c4377ed)

### ISSUE THREAD

**Issue by mmirg** [topjohnwu/Magisk#264]
Installation fails on My Pixel C using the 13.1 release with an "unable to unpack boot image" error.  
The beta build 13.0(c4377ed) did not exhibit this issue.  I have attached a recovery.log including the output from both the failure to install 13.1 as well as a successful installation of 13.0(c4377ed).

I get the same error trying to install the most recent uninstaller script on the device as well.  I have instead resorted to re-flashing clean partitions before attempting an update to Magisk.

[recovery.log](https://github.com/topjohnwu/Magisk/files/1137584/recovery.log.txt)

**Comment by crivchri** [comment]
Same problem here...

**Comment by topjohnwu** [comment]
Sorry lol, stupid bug here, easy fix :)

**Comment by mmirg** [comment]
13.2 still hasn't fixed this issue completely.  The installer appears to complete successfully but it results in a boot loop, both when applied through the Magisk Manager installer or manually through TWRP.  As with 13.1, I'm able to install it by tossing the 13.2 magisk binary into the old 13.0 installation zip.  I recognize that this not an identical issue to the "unable to unpack boot image" error so I'm happy to open a new issue if you prefer.
