### ISSUE TITLE
Creating ramdisk on boot.img shouldn't work but does?

### ISSUE THREAD

**Issue by diabl0w** [topjohnwu/Magisk#2642]
I have a device that is **non-AB** but **is** system-as-root" running android 9.
It has no ramdisk on the boot.img, but instead has the ramdisk on the recovery.img.

Well, at first I was confused, and messed up by patching the boot.img instead of the recovery.img. However, everything is working perfectly!

I don't understand why this is working. According to the docs it shouldnt be, because its not supposed to boot from the boot.img ramdisk. it seems that magisk created a ramdisk on the boot.img that wasn't there previously. Booting into normal system works perfectly with magisk running, rebooting to recovery works perfectly going straight into recovery.

The recovery ramdisk is untouched by magisk and has all the "initd" stuff in it. The boot.img that was patched by magisk has a new ramdisk that contains only an "init" binary and a ".backup/.magisk" file.

I thought that the system wasn't supposed to boot from the boot.img ramdisk, why is this working?

I previously opened https://github.com/topjohnwu/Magisk/issues/2641 which was the rabbit hole I went down to find this issue out

**Comment by osm0sis** [comment]
Some devices this works for, others it does not. A-only SAR is a nightmare to support. :slightly_frowning_face:
