### ISSUE TITLE
Module script not working after latest upgrade

### ISSUE THREAD

**Issue by tomoechan** [topjohnwu/Magisk#2647]
My service.sh as attached had been working great up until latest upgrade of Magisk to 20400. Calling iptables by its absolute path didn't fix this problem. In Magisk log I could see my service.sh being called during boot, but my iptables was still empty after booting up. Running this script manually worked. Please help.

[service.sh.txt](https://github.com/topjohnwu/Magisk/files/4428263/service.sh.txt)

**Comment by osm0sis** [comment]
Do your testing within a busybox standalone shell to resolve any compatibility issues with it.

```
:/ $ su
:/ # /sbin/.magisk/busybox/busybox sh -o standalone
~ #
```

**Comment by tomoechan** [comment]
> Do your testing within Magisk's busybox standalone shell to resolve any compatibility issues with it.
> 
> ```
> :/ $ su
> :/ # /sbin/.magisk/busybox/busybox sh -o standalone
> ~ #
> ```
Thank you mate, your suggestion gave the right direction.

It turns out my /system/bin/sh has different behaviour from that of sh in both Magisk's busybox directory and standalone busybox.

Specifically, my local sh accepts 'array=(foo boo)' initialization of array, but those in Magisk don't, they throw error:

 ./sh: syntax error: unexpected "("

After some research it seems like behavior of Magisk sh is the norm, but if I want to keep my service.sh, what should I do? Adding a shebang at the begging of the file like '#!/system/bin/sh' has no effect.

**Comment by tomoechan** [comment]
I will close this issue, rewriting shell script in vanilla sh syntax should be enough to fix this.

**Comment by osm0sis** [comment]
https://unix.stackexchange.com/a/384618
