### ISSUE TITLE
Possible documentation issue when it comes to device being SAR

### ISSUE THREAD

**Issue by KB4284848** [topjohnwu/Magisk#2648]
Greetings,

I have a OnePlus 5T (A only device), running H2OS internal Q leaked build (downloadable at http://download.h2os.com/5T/DP/OnePlus5THydrogen_43_OTA_054_all_2003241909_5f6e407973f2403b.zip ) and Magisk Manager `5537b083` (282) reports that my device is `system-as-root`.
![Screenshot_20200403-201837](https://user-images.githubusercontent.com/42769194/78404386-9890f080-75fe-11ea-9ba3-dd64e501acf2.jpg)

_However_, command provided in [documentation ](https://github.com/topjohnwu/Magisk/blob/f8b4190a11fc5dd3a5c7162d72a27b5bf174ef4a/docs/install.md#knowing-your-device) to check whether device is SAR or not (`getprop ro.build.system_root_image`) returns `false` when ran.
![image](https://user-images.githubusercontent.com/42769194/78403873-806ca180-75fd-11ea-8cec-411a6a1fd57c.png)

As SAR seems to be an Android 10 requirement: https://twitter.com/topjohnwu/status/1174392827112935425 https://twitter.com/topjohnwu/status/1174392830426378240 , I'm slightly confused.

For reference, on Pie OOS 9.0.11 (downloadable at https://oxygenos.oneplus.net/OnePlus5TOxygen_43_OTA_054_all_2002242025_81ae0ff9d1c34a3f.zip )  , Manager reports device is not SAR.

**Comment by topjohnwu** [comment]
@KB4284848 Magisk's definition of SAR is different from Google's. Yes it is very confusing, but you should trust whatever Magisk Manager is telling you because that is what internally Magisk treats your device.

**Comment by KB4284848** [comment]
@topjohnwu gotcha, thanks a lot for the explanation 😅
