### ISSUE TITLE
Theme creation for Magisk Manager Canary

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#2649]
Hi,

As @diareuse is the main dev of the Manager UI, i quote you.
So, I don't think you remember, but when you were coding the new UI of the Manager, I asked you if it would be possible to change the color of all the displayable graphical elements.

To put it simply, you answered that it would be possible, but only by joining the team dedicated to this.
Since I have time for this and I want a theme to my liking, how should I proceed to make one and submit it to you?

Depending on your answer, I might be able to propose several themes, it all depends on how you (the team) see things.

Thank you in advance for your answer.

**Comment by topjohnwu** [comment]
@xerta555 the app will be open for theming once the development is relatively stable. Right now the code is moving fast and I don't want to add unnecessary complications

**Comment by xerta555** [comment]
> @xerta555 the app will be open for theming once the development is relatively stable. Right now the code is moving fast and I don't want to add unnecessary complications

No problem, i understand totaly, ty for the info.
Post a news when themers could start to work on that.
