### ISSUE TITLE
Gained Root Access on Android Studio Emulator

### ISSUE THREAD

**Issue by sunilpaulmathew** [topjohnwu/Magisk#2651]
@topjohnwu 
This is not an issue or bug report. I did some experiments with Magisk installation files on Android Studio Emulator and surprisingly got Magisk worked (at least gained root access) within a few simple steps. Sharing the procedure here, if it helps someone. Feel free to ignore, if it is already known or you think its a bullshit.

Tested and confirmed working on the following x86 images

- **Pixel 3a XL (API 28/29)** (Not working on API R) non-Google-Play emulator (Sadly, not working on some of the Google-Play (e.g. Pixel 3a X: not sure about others) supported devices: Unable to run "adb root").

Here are the steps

1. Open Terminal/cmd or whatever you have (myself use Git Bash on Windows 10) and run "**adb root**" (The output should be "_**restarting adbd as root**_" or "_**adbd is already running as root**_")
2. Run "**adb remount**" (Ignore it, if the output shows some errors)
3. Download the latest Magisk and  "**[emulator.sh"](https://github.com/topjohnwu/Magisk/blob/master/scripts/emulator.sh)** from the official Magisk repo to the emulator.
4. Start a new root shell by running "**adb shell**" followed by "**su**"
5. Copy "**emulator.sh**" and "**magiskinit**" file from the respective architecture folder (x86 in my case) to "**/data/local/tmp**"
6. Execute "**emulator.sh**" by running "**sh /data/local/tmp/emulator.sh**" (It definitely through a number of errors, just ignore it).
7. Now install "**Magisk Manager**" apk.
8. Upon first launching, **Magisk Manager** shows the "**Requires Additional Setup**" message. Just ignore it.
Congrats. You are now **Rooted**

**Please Note**: This may not be the perfect method as the Magisk environment is not completely installed (e.g. **BusyBox**?). However, you can test your root apps in the emulator using this technique. Also, after each restart, you have to re-execute "**/data/local/tmp/emulator.sh**" **_(Step 6_**) to re-acquire root access.

**Screenshots**

![IMG_20200405_122852](https://user-images.githubusercontent.com/15515387/78472498-94b5b900-7739-11ea-807d-c4b7acc7fb61.jpg)
![IMG_20200405_122918](https://user-images.githubusercontent.com/15515387/78472516-bca51c80-7739-11ea-8bd4-1d280c916f25.jpg)

**Comment by osm0sis** [comment]
Yeah that's why emulator.sh exists.
