### ISSUE TITLE
New Hungarian Translation

### ISSUE THREAD

**Issue by gidano** [topjohnwu/Magisk#2652]
Hi,
I've made the Hungarian translation.
Unfortunately I couldn't find any other way to submit, I hope you will be in the right place here...?!<br>
Sincerelly,
gidano from Hungary<br>
[MM.Hungarian.translation.strings.zip](https://github.com/topjohnwu/Magisk/files/4433699/MM.Hungarian.translation.strings.zip)

**Comment by Didgeridoohan** [comment]
You need to open a pull request for that, not an issue.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by gidano** [comment]
That's okay! I've been working on this for an hour,
i may have read maybe everything but i am not able to open a pull request...
