### ISSUE TITLE
Repo spam

### ISSUE THREAD

**Issue by Prakyy** [topjohnwu/Magisk#2655]
I'm sure magisk can detect what Phone you are using. My request would be whenever a dev makes a device specific module like 'headphone boost for OnePlus 6' it should only show in repo for people viewing magisk on that Phone. Basically, seeing modules that you can't use in your repo is basically spam. I'm guessing this would be a pretty low-level priority but I hope any improvements are welcome.

**Comment by topjohnwu** [comment]
The repo will be cleaned up soon
