### ISSUE TITLE
No OTAs available with Magisk

### ISSUE THREAD

**Issue by Samg381** [topjohnwu/Magisk#2657]
[Please see a reddit discussion I created for this issue.](https://www.reddit.com/r/GooglePixel/comments/fwmp2x/no_ota_with_magisk)

Since owning my Pixel 4XL since launch, and being rooted with Magisk, I've yet to receive one OTA update via the settings app.

When a monthly update is announced, I'll open the update page within settings and hit 'Check for update'. The first time I do this the phrase 'Preparing system update' appears, promptly followed by 'Your system is up to date". All additional attempts result in the latter message.

I have attempted to uninstall Magisk before checking for an update to no avail.

**Comment by topjohnwu** [comment]
This is a Google issue, not a Magisk issue. Tell Google to fix their god damn update check button (I'm suffering this myself). Please note that no updates coming have very little to do with Magisk, it's all up to Google.

**Comment by chriscjs** [comment]
What worked for me was uninstalling Magisk **before** checking for updates in the settings app.  Otherwise some flag is set that prevents the OTA from being received, for I don't know how long but not permanently.   Then go through the normal Magisk OTA process before rebooting.  An unlocked bootloader has nothing to do with it.   This has worked on my Pixel 3a since I tested it last month (just applied July OTA).  Before that I used sideload.  Updates through settings app are much smaller than direct download from google.

**Comment by yakidd** [comment]
> What worked for me was uninstalling Magisk **before** checking for updates in the settings app. Otherwise some flag is set that prevents the OTA from being received, for I don't know how long but not permanently. Then go through the normal Magisk OTA process before rebooting. An unlocked bootloader has nothing to do with it. This has worked on my Pixel 3a since I tested it last month (just applied July OTA). Before that I used sideload. Updates through settings app are much smaller than direct download from google.
> Edit:
> Making sure "Automatic system updates" is turned off in Developer options may help this.

Need some clarification here.. uninstall Magisk entirely or just the Magisk Manager (the manager is installed via APK)?

**Comment by yakidd** [comment]
Or did you mean:
1. Launch Magisk Manager
2. Click uninstall
3. Click complete uninstall
4. Wait and then install OTA
5. Use Magisk Manager to patch inactive slot

Please let me know.

Regards,

**Comment by chriscjs** [comment]
Not completely uninstall Magisk.  Just restore images.  If you've already checked for updates before doing that,  may have to wait for some days (or weeks?) before trying again.  That's why its important not to check for updates until **after** restoring the stock boot images.
