### ISSUE TITLE
LOS 17.1 Android 10 Bootloop

### ISSUE THREAD

**Issue by zlyfer** [topjohnwu/Magisk#2662]
Hello, I tried to flash Magisk on my OnePlus 3 and now it doesn't boot anymore.
I tried sideloading the Magisk-Uninstaller via TWRP but it didn't help.

OS: Lineage OS 17.1 based on Android 10
Magisk I tried to flash: 20.4

Does anyone have suggestion on how I can unbrick my phone?

**Comment by osm0sis** [comment]
Remove the addon.d script and reflash your ROM, you will be unrooted.
