### ISSUE TITLE
Module List Crashes

### ISSUE THREAD

**Issue by gudenau** [topjohnwu/Magisk#2663]
When opening the module list on ef9d077c it crashes 99.9% of the time.

There are no stack traces im the app logs and I currently don't have power so I can't use logcat to trace it.
![Screenshot_20200408-194505](https://user-images.githubusercontent.com/5642329/78846488-93062280-79d1-11ea-91fd-03a78ef8b80c.png)

**Comment by osm0sis** [comment]
#2631
