### ISSUE TITLE
Modifying manifest.xml prior to hwservicemanager starting

### ISSUE THREAD

**Issue by sztaylor** [topjohnwu/Magisk#2665]
Hi, 
I need to make a modification to the /system/vendor/manifest.xml and have the hwservicemanager reflect the change. I have tried to work around this by using the module/service.sh functionality to kill/restart the hwservicemanager. This works but seems to make the device unstable resulting in random reboots.
Do you have any recommendations that use magisk to update the manifest.xml prior to hwservicemanager starting?
Thank you.

**Comment by topjohnwu** [comment]
Maybe in post-fs-data mode? That is the earliest you can get in Magisk
