### ISSUE TITLE
[Request] Bring back Magisk Hide by default

### ISSUE THREAD

**Issue by ananjaser1211** [topjohnwu/Magisk#2666]
Disabling magisk hide is causing the majority of people in our samsung groups to no longer pass SafetyNet.

it was pinned down to having magisk hide enabled/disabled. This is especially relevant with custom kernel users, while a stock kernel + magisk it passes just fine with hide OFF, custom kernels do not, and needs no other modifications besides flipping that switch back on

many people "who used to pass just fine" no longer do due to something as simple as HIDE being toggled off. So can we keep MagiskHide enabled by default [again ](https://github.com/topjohnwu/Magisk/commit/612b51d48f9771a65cfab045f931573f42d3a494)? i dont see any harm in keeping it ON. but meanwhile keeping it off is preventing many people from using their favourite apps on devices that so far has not been affected by google TEE based CTS

I understand how the new check is going to make it "useless" but what about the millions of older devices that will not even be affected by this change. not everyone is using devices backed by hardware key attestation support (Atleast base on this [app](https://github.com/vvb2060/KeyAttestation) phones upto samsungs Note 8 do not)

**Why not just turn it on yourself ?**
Because I and thousands of other users in our groups expect it to always be on, and when people started failing CTS they thought it was due to google escalation (I did too as well) but that was not the case. And now we have to mention to everyone not passing that they need to go turn hide on.

This is just an extra step that is honestly not necessary. especially when its been over a month since the first Key attestation discussion, and most of the devices are still passing just fine. and many of them will continue to do so (S7s, S8s S9s and even S10s are passing with no issues)

I am sure you already know this. i am not asking to "improve magisk hide and bypass google". all im asking is to flip that switch back to ON for the rest of us that probably wont deal with hardware key attestation until we upgrade our devices. and for everyone else who still pass just fine right now, but are unable to due to hide being off

**Comment by osm0sis** [comment]
No.

**Comment by ananjaser1211** [comment]
> No. Stop "expecting it to be on".

Great solution, im sure everyone using magisk is going to realize they are failing CTS because that thing is off on their own.

**Comment by osm0sis** [comment]
Yep. RTFM.

**Comment by ananjaser1211** [comment]
Thanks for linking the dup, i did not see it when i was searching for similar issues. i also emailed you before i noticed the issue was reopened for discussion.

Anyhow, in that dup i found a reply for the question i was asking. https://github.com/topjohnwu/Magisk/issues/2541#issuecomment-599020967

Feel free to close it permanently now.

Thanks for your time again.
