### ISSUE TITLE
LZ4 Ramdisk

### ISSUE THREAD

**Issue by TheNotOnly** [topjohnwu/Magisk#2668]
Magisk unable to patch kernel with LZ4 compressed ramdisk

**Comment by osm0sis** [comment]
This was fixed awhile back. Log and boot.img?

**Comment by TheNotOnly** [comment]
Hi, Magisk is able to patch the image but it doesn't work somehow. I patched via cli also, no errors but root's not there.

Below is the output from cli:

darren@vps01:~/magisk/x86$ ./magiskboot unpack boot.img
Parsing boot image: [boot.img]
HEADER_VER      [0]
KERNEL_SZ       [15661950]
RAMDISK_SZ      [25024193]
SECOND_SZ       [0]
EXTRA_SZ        [0]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-04]
PAGESIZE        [4096]
NAME            []
CMDLINE         [video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_                                                                                                  levels.sleep_disabled=1 service_locator.enable=1 swiotlb=2048 androidboot.configfs=true androidboot                                                                                                  .usbcontroller=a600000.dwc3 loop.max_part=7 androidboot.selinux=permissive androidboot.hardware=jud                                                                                                  yln buildvariant=userdebug]
CHECKSUM        [a1111a976f9961c0694248f3e1dbf12c243ee1d0000000000000000000000000]
KERNEL_DTB      [1241201]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [lz4_legacy]
darren@vps01:~/magisk/x86$ ./magiskboot cpio ramdisk.cpio \
> "mkdir 000 .backup" \
> "mv init .backup/init" \
> "add 750 init magiskinit"
Loading cpio: [ramdisk.cpio]
Create directory [.backup] (0000)
Move [init] -> [.backup/init]
Add entry [init] (0750)
Dump cpio: [ramdisk.cpio]
darren@vps01:~/magisk/x86$ ./magiskboot hexpatch kernel \
> 736B69705F696E697472616D6673 \
> 77616E745F696E697472616D6673
darren@vps01:~/magisk/x86$ ./magiskboot repack boot.img
Parsing boot image: [boot.img]
HEADER_VER      [0]
KERNEL_SZ       [15661950]
RAMDISK_SZ      [25024193]
SECOND_SZ       [0]
EXTRA_SZ        [0]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-04]
PAGESIZE        [4096]
NAME            []
CMDLINE         [video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_                                                                                                  levels.sleep_disabled=1 service_locator.enable=1 swiotlb=2048 androidboot.configfs=true androidboot                                                                                                  .usbcontroller=a600000.dwc3 loop.max_part=7 androidboot.selinux=permissive androidboot.hardware=jud                                                                                                  yln buildvariant=userdebug]
CHECKSUM        [a1111a976f9961c0694248f3e1dbf12c243ee1d0000000000000000000000000]
KERNEL_DTB      [1241201]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [lz4_legacy]
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [15661950]
RAMDISK_SZ      [20505948]
SECOND_SZ       [0]
EXTRA_SZ        [0]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-04]
PAGESIZE        [4096]
NAME            []
CMDLINE         [video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_                                                                                                  levels.sleep_disabled=1 service_locator.enable=1 swiotlb=2048 androidboot.configfs=true androidboot                                                                                                  .usbcontroller=a600000.dwc3 loop.max_part=7 androidboot.selinux=permissive androidboot.hardware=jud                                                                                                  yln buildvariant=userdebug]
CHECKSUM        [4ee3af805ecf91c8133d462863305555933ad58e000000000000000000000000]

**Comment by osm0sis** [comment]
boot.img? What's the last version that worked for you?

**Comment by TheNotOnly** [comment]
Guess it was before 20.1 not sure, but it was definitely working before and stopped working after a Magisk update.

Here is boot.img: https://drive.google.com/open?id=1Vx4jA_nOjmg8uWQDVwK08VZ8-RXBLT51

**Comment by osm0sis** [comment]
Does Canary 20202 work for you? That's where it was confirmed fixed in #2203 the last time it was broken.

**Comment by TheNotOnly** [comment]
Hi I've tested several versions. But none seem to work anymore. Tested bersion 19.3, 19.4, 20.2, 20.3 including canary 20202.

Any ideas what the problem might be from? The same kernel with the Ramdisk compressed in gzip works fine. But as soon as compression is changed to lz4 doesn't seem to be patched by magisk anymore, whether it be via zip, app or using anykernel3 with compression set to lz4 in the script. To be noted, if boot image is patched then repacked in lz4, it works fine.

**Comment by osm0sis** [comment]
Honestly that doesn't make a ton of sense, and other users with lz4_legacy ramdisks reported success again after we fixed it in 20202, as you can see on that issue thread I linked. I'll try manually unpacking and patching it to see what I can see.

**Comment by osm0sis** [comment]
Wait, you said "none seem to work anymore" ? What version did it used to work on? What changed if the old ones don't work? This is sounding more like user error.. e.g. make sure you're using an untouched ROM boot.img, since some other modification might have broken something in the ramdisk.

**Comment by lss4** [comment]
My Razer Phone 2 is currently on 20401 and still working, using Trinity Kernel 20200306. This kernel seems to be lz4 compressed as well (according to Android Image Kitchen).

**Comment by osm0sis** [comment]
> My Razer Phone 2 is currently on 20401 and still working, using Trinity Kernel 20200306. This kernel seems to be lz4 compressed as well (according to Android Image Kitchen).

Yep, and I checked the header magic myself and it's lz4_legacy, like yours was.

**Comment by TheNotOnly** [comment]
Hi,
I'm using an untouched boot image, compiled fresh from rom. Only thing I did was change ramdisk compression using AIK and patch with magisk manager. Kernel boots fine but doesn't have root.

**Comment by osm0sis** [comment]
You can't just change ramdisk compression with AIK, the kernel has to support it, and clearly you've broken something while messing with it since it works for others with lz4_legacy.

Use the untouched boot.img, without messing with it, with Magisk and your device will be rooted.

Locking this now.
