### ISSUE TITLE
Xiaomi Redmi Note 3 (kenzo) bootloops after magisk 13.1 stable

### ISSUE THREAD

**Issue by gundopanth** [topjohnwu/Magisk#267]
After updating magisk on my phone from magisk v12 to v13.1 it bootloops.Tried installing through magisk manager,twrp but still bootloops.Stock boot image link : http://s000.tinyupload.com/index.php?file_id=36529834505206556451

**Comment by Braccoz** [comment]
redmi 4 prime bootloops too. latest 13.0 beta works. stock boot image: https://www.mediafire.com/?vg90g0hm10zg2t2

**Comment by hyakki-** [comment]
same issue on my Xiaomi Redmi Note 3 and Magisk 13.1 it's not really a bootloop but it hangs on the "MI" boot logo for about 5~ minutes , then proceeds to show the boot animation, unfortunately it seems like this is a backup boot image (failsafe?), magisk shows unrooted and uninstalled.

I tried 
magisk uninstaller twrp (aswell as clearing cache/data from magisk manger), uninstall apk
clean flash magisk 13.1 in twrp (same result)
-
twrp - magisk uninstaller, masgisk 12.0 - phone booted right up, magisk working again.

so some bug with 13.1 and xiaomi

some positive news is I flashed 13.1 on Samsung Galaxy Tab Pro 8.4 w/ LineageOS 13.0 without issue.

Anyways  keep up the good work, Magisk is awesome tool.

**Comment by Braccoz** [comment]
on redmi 4 prime it doesn't boot even after 10 minutes of sitting there

**Comment by JohnEdwa** [comment]
Can confirm the issue on 4 Prime as well, running Xiomi.eu rom  - stuck on "Mi" logo.

**Comment by JERW86** [comment]
Try these steps I mentioned [here](https://forum.xda-developers.com/showpost.php?p=72990463&postcount=15680) to help topjohnwu resolve the issue.

**Comment by hyakki-** [comment]
Tried what you suggested but there is no /data/magisk_debug.log

**Comment by alien2003** [comment]
same here

**Comment by JERW86** [comment]
@hyakki-  and  @alien2003 Did you flash the Magisk uninstaller or your clean boot image? See #272.

**Comment by hyakki-** [comment]
Yeah flashed unintaller, restored stock boot same issue

**Comment by hyakki-** [comment]
Magisk 13.1 build 170713 fixes the boot issue (commit bdbb3c6), I haven't tested other features yet, but appears rooted and working

**Comment by gundopanth** [comment]
Thanks hyakki its working fine but just safetynet
