### ISSUE TITLE
Magisk Manager re-installs itself on reboot

### ISSUE THREAD

**Issue by blacklightpy** [topjohnwu/Magisk#2672]
I changes the package name of Magisk Manager and uninstalled it, but after a reboot it gets reinstalled with the default package name. The fake package isn't uninstalled, but I have to uninstall the package after each reboot. Please fix this by either not reinstalling the package each time or remembering the modified package name.

**Comment by wangdaning** [comment]
It cannot be fixed unless there is more information as to why it happens. I cannot see it magically reinstalling, so... Device, magisk version, logs?

**Comment by blacklightpy** [comment]
> It cannot be fixed unless there is more information as to why it happens. I cannot see it magically reinstalling, so... Device, magisk version, logs?

I thought it was obvious. Anyways.

Device: Samsung Galaxy M10 (SM-M105F)
Magisk Version: 20.1
Log attached:
[magisk_log_20200411_071226.log](https://github.com/topjohnwu/Magisk/files/4463883/magisk_log_20200411_071226.log)

As I guessed, it seems to look for Magisk Manager installation and when it can't find it, it reinstalls the apk. But it's ignoring the renamed Manager.

**Comment by topjohnwu** [comment]
You device is messed up as it cannot establish a root database. Please make sure you have Magisk installed properly
