### ISSUE TITLE
Samsung Pass is bypassing Magisk hide.

### ISSUE THREAD

**Issue by ytrezq** [topjohnwu/Magisk#2673]
Samsung Pass is a Universal password manager which works across all applications regardless of specific support.

As soon as it detects a rooted device, it refuses to work. Even enabling MagiskHide on it doesn’t change anything (though I may have an idea why because the bootloader is adding something related to it on the cmdline which would require an additional patch of the kernel).

I agree for remote control for debugging purposes. I’m using the latest versions.

**Comment by osm0sis** [comment]
#1152

**Comment by ytrezq** [comment]
@osm0sis but this is about a new filter. I mean preventing `androidboot.warranty_bit=1` to be passed on the cmdline.

**Comment by Didgeridoohan** [comment]
It's a Samsung app. Are you sure it's not just checking Knox (in which case there's nothing to do about it)?

**Comment by osm0sis** [comment]
That cmdline becomes the props modified here: https://github.com/topjohnwu/Magisk/blob/master/native/jni/magiskhide/hide_policy.cpp#L14

I don't think there's anything else that can be done with cmdline, IIRC. @topjohnwu, can you confirm?

**Comment by ytrezq** [comment]
> It's a Samsung app. Are you sure it's not just checking Knox (in which case there's nothing to do about it)?
I think it’s checking through the cmdline.

**Comment by Didgeridoohan** [comment]
But apps do not have access to cmdline... They use the props, which MagiskHide changes.

Are you using a Samsung device?

**Comment by osm0sis** [comment]
Nope, can't control the bootloader, again IIRC. Hopefully @topjohnwu can chime in to explain for certain.

**Comment by osm0sis** [comment]
I think I remember custom kernels being able to modify the cmdline bootloader state to green, but again that's outside of the scope of Magisk.

**Comment by brad-hue** [comment]
I'm sorry I think, it is a virus..I downloaded  something :(

**Comment by ytrezq** [comment]
> But apps do not have access to cmdline... They use the props, which MagiskHide changes.
> 
> Are you using a Samsung device?

@osm0sis yes of course as Samsung if for Samsung devices only as far I’m aware.

In fact this is by just changing the cmdline that I can boot on my sdcard instead of the Internal storage (by changing the `root=` parameter).
I don’t think they use this, but both on Linux and Android the cmdline is available through `/proc/cmdline`.

**Comment by osm0sis** [comment]
It can be read there, yes, but not technically changed AFAIK.

**Comment by Didgeridoohan** [comment]
Regular apps can't read /proc/cmdline, you'd need root for that.

I still maintain that the most likely scenario is that the app checks the Knox counter.
