### ISSUE TITLE
Modules 

### ISSUE THREAD

**Issue by phoenixmet2011** [topjohnwu/Magisk#2676]
Some modules doesn't work in this release, with 20.3 works fine, I realize a clean install for magisk but not working by example the recovery manager and xposed both from repository, the xposed only works for me if install from internal memory and not from sdcard. I have a moto g4 play in nougat 7.1.1.

![Screenshot_20200411-040017](https://user-images.githubusercontent.com/561890/79038657-01510d80-7ba9-11ea-9b7c-6a0061a55bd5.png)
![Screenshot_20200411-040020](https://user-images.githubusercontent.com/561890/79038658-02823a80-7ba9-11ea-920d-a5c189e6991c.png)

![Screenshot_20200411-040020](https://user-images.githubusercontent.com/561890/79038850-b637fa00-7baa-11ea-9c1a-ae88abf255f2.png)

**Comment by topjohnwu** [comment]
Please report this issue to the module developer

**Comment by phoenixmet2011** [comment]
sorry, you can update the Xposed module for install with this release? Only install with 89 version from internal or sd card but with 90v not install
