### ISSUE TITLE
why ？Do not allow adding new files/folders in partition root folder

### ISSUE THREAD

**Issue by z826540272** [topjohnwu/Magisk#2679]
magicmount:
Do not allow adding new files/folders in partition root folder
because of this i cannot add what i want in system
and the module development guide doesnt mention it at all 😒 its so trolling
wasted a lot of time ,
and  ..i didn't use the system or vendor root dir
my phone doesnt have a vendor partition .
im using /system/vendor ,once i create a folder after reboot it just disappear 
i have no idea
i dont know why magisk doesnt support that？
please tell me

**Comment by topjohnwu** [comment]
Because it leads to bootloop on some devices.
