### ISSUE TITLE
Magisk on cheryl , los 17.1

### ISSUE THREAD

**Issue by 666zam** [topjohnwu/Magisk#2681]
#![Screenshot_20200412-141441_Magisk_Manager](https://user-images.githubusercontent.com/63543951/79068555-17092480-7cc8-11ea-9f4d-e7a3299f753a.png)
Hi! I can't install magisk on Cheryl after update to los 17.1.
Magisk manager is installed.

**Comment by 666zam** [comment]
Hi, sir!
I ser you've closed my issue. But can you give me a hint, what am I doing
wrong, and how to install magisk on Cheryl los 17.1?
I guess its not as simple as it was.
Could you please respond?

Thank you,

Anton.



Den sön 12 apr. 2020 14:40John Wu <notifications@github.com> skrev:

**Comment by Y24** [comment]
@666zam Maybe you could see the related document to seek for help.

**Comment by 666zam** [comment]
Sorry, I didn't get it. Which document?

Den tors 16 apr. 2020 08:25Y24 <notifications@github.com> skrev:
