### ISSUE TITLE
[Bug] Magisk Flashing UI doesn't wrap output

### ISSUE THREAD

**Issue by linuxandria** [topjohnwu/Magisk#2688]
If a modules output in one line exceeds the screen, part of that output is not seen at all. Magisk manager should automatically wrap output if possible.

In addition padding for start of output is off. Part of the first letter isn't visible.

**Comment by osm0sis** [comment]
It's scrollable

**Comment by linuxandria** [comment]
> It's scrollable. You also haven't given any details about what Manager or Magisk version you're using or even a screenshot. Only bug reports with Canary will be accepted.

I would think what I'm referring to is rather obvious, and I run nothing but canary (debug) lol

**Comment by linuxandria** [comment]
20401 / 282 of it helps

**Comment by osm0sis** [comment]
It's not obvious since it isn't happening for others, so a screenshot would be useful to illustrate.

**Comment by linuxandria** [comment]
As soon as my Manager stops crashing 9/10 times I open modules tab I'll grab a screenshot buy I meant cuts off on the sides.
Yes, it's scrollable, bit it should wrap nonetheless. Much better UX, especially on a mobile device where that apps not requiring side scrolling is usually expected.

**Comment by topjohnwu** [comment]
I absolutely hate text wrapping, so nah this won't happen :p

**Comment by linuxandria** [comment]
I hate not being able to by default see everything :p
