### ISSUE TITLE
Magiskboot windows build error.

### ISSUE THREAD

**Issue by seci20** [topjohnwu/Magisk#2689]
Hi master. Why build error ? I'm showing the library path, still failing. 

```
C:\cygwin64\home\SeCi\1>g++ main.cpp -o ilk
main.cpp:7:10: fatal error: mincrypt/sha.h: No such file or directory
    7 | #include <mincrypt/sha.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

![1](https://user-images.githubusercontent.com/13988176/79241379-ab67b880-7e7b-11ea-9a71-5b971eb5cd03.PNG)
![Ekran Alıntısı](https://user-images.githubusercontent.com/13988176/79241386-ac004f00-7e7b-11ea-9ab8-8b016a412db6.PNG)

**Comment by Didgeridoohan** [comment]
Well, according to that screenshot there is no sha.h in the mincrypt directory. There's a sha.c though.

**Comment by topjohnwu** [comment]
Direct building with `g++` is not supported, please use `build.py`, which uses `ndk-build`, which is a custom Android NDK makefile

**Comment by seci20** [comment]
> Direct building with `g++` is not supported, please use `build.py`, which uses `ndk-build`, which is a custom Android NDK makefile

my goal is to create magiskboot.exe. When I compile it with Ndk build, it is not compiled as exe. I have been working on this for a long time, I am a delphi expert, my knowledge of C ++ is weak so I have a hard time. Is there an article? nasıl Magiskboot.exe yapabilirim.Sorry for bothering you, but I really need this.

**Comment by seci20** [comment]
> Well, according to that screenshot there is no sha.h in the mincrypt directory. There's a sha.c though.

There is sha.h in inculed but genede is giving error.
