### ISSUE TITLE
Canary Magisk Manager version  (282)  crashes on android 10

### ISSUE THREAD

**Issue by djemilbakhti** [topjohnwu/Magisk#2690]
device: redmi 7a
log:

beginning of crash
04-15 09:45:08.327  6274  6274 E AndroidRuntime: FATAL EXCEPTION: main
04-15 09:45:08.327  6274  6274 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 6274
04-15 09:45:08.327  6274  6274 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 12
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at java.util.Arrays.rangeCheck(Arrays.java:123)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at java.util.Arrays.fill(Arrays.java:2828)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at androidx.recyclerview.widget.StaggeredGridLayoutManager$d.d(:2)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at androidx.recyclerview.widget.StaggeredGridLayoutManager.c(Unknown Source:31)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at androidx.recyclerview.widget.StaggeredGridLayoutManager.a(Unknown Source:1)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$f.a(Unknown Source:38)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at ft.a(:1)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at ft.b(Unknown Source:0)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:14)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:37)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.b(:52)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:2)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7773)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:726)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-15 09:45:08.327  6274  6274 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
04-15 09:45:08.327  6274  6274 E ThreadGroup: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 12
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at java.util.Arrays.rangeCheck(Arrays.java:123)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at java.util.Arrays.fill(Arrays.java:2828)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at androidx.recyclerview.widget.StaggeredGridLayoutManager$d.d(:2)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at androidx.recyclerview.widget.StaggeredGridLayoutManager.c(Unknown Source:31)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at androidx.recyclerview.widget.StaggeredGridLayoutManager.a(Unknown Source:1)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at androidx.recyclerview.widget.RecyclerView$f.a(Unknown Source:38)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at ft.a(:1)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at ft.b(Unknown Source:0)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:14)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:37)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at androidx.coordinatorlayout.widget.CoordinatorLayout.b(:52)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:2)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.View.layout(View.java:22466)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewGroup.layout(ViewGroup.java:6304)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7773)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.Choreographer.doCallbacks(Choreographer.java:791)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.Choreographer.doFrame(Choreographer.java:726)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.os.Handler.handleCallback(Handler.java:883)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.os.Handler.dispatchMessage(Handler.java:100)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.os.Looper.loop(Looper.java:214)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at android.app.ActivityThread.main(ActivityThread.java:7356)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at java.lang.reflect.Method.invoke(Native Method)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-15 09:45:08.327  6274  6274 E ThreadGroup:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
04-15 09:45:08.329  6274  6274 I opjohnwu.magis: System.exit called, status: 1
04-15 09:45:08.329  6274  6274 I AndroidRuntime: VM exiting with result code 1, cleanup skipped.
04-15 09:45:08.349  1586  1928 W InputDispatcher: channel 'ba1f1f9 com.topjohnwu.magisk/a.b (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-15 09:45:08.350  1586  1928 E InputDispatcher: channel 'ba1f1f9 com.topjohnwu.magisk/a.b (server)' ~ Channel is unrecoverably broken and will be disposed!
--------- beginning of system
04-15 09:45:08.369  1586  2834 I WindowManager: WIN DEATH: Window{ba1f1f9 u0 com.topjohnwu.magisk/a.b}
04-15 09:45:08.370  1586  2834 W InputDispatcher: Attempted to unregister already unregistered input channel 'ba1f1f9 com.topjohnwu.magisk/a.b (server)'
04-15 09:45:08.371  1586  4195 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=27, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND Uid: 10182] ], android.os.BinderProxy@3df8b52)
04-15 09:45:08.374  2013  2013 D ImageWallpaper: wallpaper visibility changes to: true
04-15 09:45:08.375  1586  2775 I ActivityManager: Process com.topjohnwu.magisk (pid 6274) has died: fore TOP 
04-15 09:45:08.383  1586  2775 W ActivityTaskManager: Force removing ActivityRecord{8c364cb u0 com.topjohnwu.magisk/a.b t103}: app died, no saved state
04-15 09:45:08.383   805   805 I Zygote  : Process 6274 exited cleanly (1)
04-15 09:45:08.418  1586  1616 W ActivityManager: setHasOverlayUi called on unknown pid: 6274
04-15 09:45:08.420   804   804 I netd    : firewallSetUidRule(3, 10182, 2) <0.05ms>
04-15 09:45:08.470  1586  1659 I libprocessgroup: Successfully killed process cgroup uid 10182 pid 6274 in 94ms
04-15 09:45:10.146  1586  2775 D WificondControl: Scan result ready event
04-15 09:45:10.146  1181  2359 I LOWI-8.6.0.33: [LOWI-Scan] lowi_close_record:Scan done in 133608ms, 2 APs in scan results

**Comment by topjohnwu** [comment]
Fixed d810e6c82df6e6cf8e8a7cfcf0d1449bfae9e115
