### ISSUE TITLE
Magisk update uninstalled itself

### ISSUE THREAD

**Issue by V10lator** [topjohnwu/Magisk#2694]
I just updated from Magisk 20.3 to 20.4 from within Magisk Manager. As always Magisks Manager wanted to reboot afterwards but instead of rebooting into the new Magisk version it rebootet into recovery.

This is on a Honor 9 Lite, so AFAIK Magisk should replace recovery.

Currently I have Resurrection Remix from OpenKirin running on that phone, so I'm able to reboot to recovery with ease and normally this brings back Magisk on a failed (read: normal, none-recovery) boot but since the update this just brings me to recovery, too.

**Comment by linuxandria** [comment]
If you can try to grab logcat and pstore that would help greatly
