### ISSUE TITLE
Android 10.0 keep restarting at boot after Magisk Patch

### ISSUE THREAD

**Issue by engrahmadosama** [topjohnwu/Magisk#2696]
My Android Phone Inifnix Note 4 (x604) having Android One Software after updating to Android Q is unable to root,
Whenever i try to patch magisk img file, phone is stuck at restarting at boot screen.
please help

**Comment by linuxandria** [comment]
Boot logs and how you attempted root are very welcome :p

**Comment by engrahmadosama** [comment]
I took the stock boot.img,
patched it using Magisk Application,
Rebooted Phone to Bootloader,
Unlocked the bootloader, and flashed patched boot.img
i used following commands for the purpose.

adb reboot bootloader
fastboot flashing unlock
fastboot flash boot magisk_patched.img
fastboot reboot

After Reboot, device keep rebooting after first logo is appeared. I even tried to reflash my stock boot.img but it did not worked, and I have to reflash entire System using Sp Flashtools (it's mediatek processor)

Moreoever, my device has a/b partition system
and dear please guide me how to extract boot logs from my phone.
