### ISSUE TITLE
Basic Integrity Fail

### ISSUE THREAD

**Issue by Justsnoopy30** [topjohnwu/Magisk#2697]
On my Pixel 3 XL running stock firmware with magisk, Basic Integrity (and cts profile of course due to hardware key attestation probably) is failing. No modules are enabled, no apps are granted superuser rights, and Magisk is in safe mode with Magisk Hide enabled. The device is running Android 10 with the March Security Patch, and Magisk is the latest canary release ef9d077c (20401). Hardware key attestation affects only cts-profile IIRC, so basic integrity shouldn't be failing.

**Comment by slim2none4u** [comment]
Pixel 3xl and I pass. Guessing it's on your end.
![551](https://user-images.githubusercontent.com/19349989/79587612-c9fac900-80a0-11ea-919e-a0c5e886b33a.jpg)
![552](https://user-images.githubusercontent.com/19349989/79587767-062e2980-80a1-11ea-8a93-160d28181ad5.jpg)
![553](https://user-images.githubusercontent.com/19349989/79587800-0e866480-80a1-11ea-8f6a-4bd2913aba8c.jpg)

**Comment by Justsnoopy30** [comment]
Turned back off Magisk safe mode, re-enabled modules, and: 
![Screenshot_20200417-110402](https://user-images.githubusercontent.com/33374736/79589596-4b4f5d00-809b-11ea-8c8b-03dc3bb8233a.png)
![Screenshot_20200417-110526](https://user-images.githubusercontent.com/33374736/79589642-5c986980-809b-11ea-91dc-572938615eb7.png)

**Comment by linuxandria** [comment]
That's due to edxposed not magisk.

In edxposed manager, go to settings and enable app list and pass safety net. Then reboot

**Comment by Justsnoopy30** [comment]
Already did that.

**Comment by Justsnoopy30** [comment]
This also happens with exposed disabled in Magisk Safe Mode.

**Comment by linuxandria** [comment]
Try hiding
Google services framework: all
Google play store: download_service and recovery_mode
Google play services: unstable, snet, learning, persistent (not 100% sure last two help)

That usually solves any safety net issues for me.

If that still fails, uninstall magisk completely, flash latest stock, reflash magisk, and enable Hide and add the above targets. If you're passing before installing any modules, install your usual one by one until you find the one that triggered it.

You may also try clearing data of Google play services and framework after hiding them

**Comment by Justsnoopy30** [comment]
I have tried in Magisk Safe Mode and both basic integrity and cts profile fail.

**Comment by Justsnoopy30** [comment]
I do not see any of those in the Magisk Hide list.

**Comment by Justsnoopy30** [comment]
Interesting. I just completely cleared all the Google Play Services data and now both pass :smile:

**Comment by Justsnoopy30** [comment]
Both are now failing again, I tried clearing Google Play Services data but it still fails. The only thing I can think of that I did between it passing and failing is updating Magisk.

**Comment by Justsnoopy30** [comment]
I also reflashed the latest stock factory image without wiping data and then patched the boot image with magisk and flashed it.

**Comment by Justsnoopy30** [comment]
After some testing, this is somehow caused by EdXposed and it passes when EdXposed is disabled and the data of Google Play Services is cleared. My EdXposed isn't working due to not startings any modules as modules.list wasn't found (even though it exists).

**Comment by Justsnoopy30** [comment]
Forgot to close, ty.
