### ISSUE TITLE
Bootloop on Samsung A5 2017 with encrypted Lineageos 16.0

### ISSUE THREAD

**Issue by getwet** [topjohnwu/Magisk#2700]
Hi,

I tried to install Magisk to my LOS device over TWRP. I flashed the Magisk-v20.4.zip package over install and do a wipe dalvik cache after.  But after a reboot I saw only the Samsung A5 logo and the device starts into bootloop. I stopped it's with install doing an uninstall. There was no error message during the Installation.
What was wrong, does anybody know the problem?

**Comment by osm0sis** [comment]
Not a lot to go on here. What's the last Canary build that worked? Install logs?

**Comment by hkzlab** [comment]
I can say that I have the same identical issue:

- Installing LOS 16 on my a5y17lte and magisk (20.4) WITHOUT enabling encryption gets me a working phone (without encryption)
- Installing LOS 16 and Magisk (20.4) and enabling encryption gets me a bootloop (until I format data)

See posts 1625 and 1626 here:
https://forum.xda-developers.com/samsung-a-series-2017/development/rom-lineageos-16-0-galaxy-a57-2017-t3876673/page163

Apparently from post 1626 there, using Magisk 20.3 is fine, haven't tried the latest canary build myself, but I have a spare A520F I can use for tests, so I can gladly run a check if needed @osm0sis

**Comment by getwet** [comment]
Can confirm hkzlab's post.
Sorry I forgot, my device is also encrypted. I've got also not problems with 20.3 and encryption.

**Comment by me-me-me-me** [comment]
Same as my #2614

**Comment by kenan1099** [comment]
Not sure if same issue, but same phone (coincidentally :P) same rom, when I install magisk and try to access developer options, the phone soft resets
