### ISSUE TITLE
Make Manager donation/links more compact

### ISSUE THREAD

**Issue by Mikesew1320** [topjohnwu/Magisk#2705]
![Screenshot_20200419-123110](https://user-images.githubusercontent.com/43565227/79692195-763cdb00-826c-11ea-8938-4f4ab930fa5d.jpg)
Can u improve the layout marked on the Screenshot above please? It makes the manager UI too boring.

Just try to make it simpler(minimal) as of the older Magisk Manager app. Why making too huge needed?

Thanks!

**Comment by pbanj** [comment]
Id be happy if it was made uniform at least

**Comment by diareuse** [comment]
As of now, no plans to make donations UI "more exciting".

**Comment by Mikesew1320** [comment]
> As of now, no plans to make donations UI "more exciting".

Seems u are selfish!
