### ISSUE TITLE
Magisk Manager repeating the Magisk installation when changing the interface language

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#2706]
I don't know if it's a known problem, but at least for me the MM Canary Debug is not updating itself using the same package name as the current repackaged version. For this reason, I am returning MM to its original package name when I need to update it. Today, I noticed something interesting: after updating the MM and then installing the Magisk update, I went to the MM settings and changed the language and this caused the MM to automatically open the flash screen and then install the Magisk update again. I changed the  language a few times and every time Magisk was installed directly again.
ZenFone 4 with Android 9
[installingagain.txt](https://github.com/topjohnwu/Magisk/files/4499650/installingagain.txt)

**Comment by osm0sis** [comment]
I followed your steps and I can't reproduce this. How did you start the update? Was it using the update notification?

**Comment by topjohnwu** [comment]
@osm0sis the current activity recreation logic resends the intent. Might consider sending an empty intent instead to fix this issue. @diareuse I'll handle this myself once I'm done with the native stuffs.

**Comment by topjohnwu** [comment]
Fixed 867bab8513ca30c8767cb8706b6088c90a932697
