### ISSUE TITLE
Latest canary bootloops OnePlus 7T

### ISSUE THREAD

**Issue by linuxandria** [topjohnwu/Magisk#2707]
I did an upgrade from the previous canary to the latest (20402).
I'd love to report on the new module mount logic.... but now if any magisk patched image is flashed my device doesn't boot. Even reflashed an older canary patched image.
Clean flashing magisk by flashing the uninstaller not an option - this device launched with a10 so no custom recovery available.
No logs, my logging script wasn't getting ran and I don't have access to any of the places logs are stored because they all require root access to get to. And for whatever reason `adb root` is getting stuck at restarting adb as root.
OnePlus 7T, android 10, my personal build of MSM-Xtended Mutate (mostly identical to @jacks84 trees)

**Comment by linuxandria** [comment]
/data/cache also isn't accessible without getting root access. ADB never started so no logs from there.

**Comment by linuxandria** [comment]
Okay on OxygenOS flashing the previous canary (via patched boot off) gets me out of the boot loop. Seems to be tied to certain modules, ones that have more stuff (a fully set up ccbins, Renovate Ice, or xXx seems to trigger the boot loop)
Also I did find out that my log script was running just `logd` never starts lol. Log files were produced without any logs in them

**Comment by linuxandria** [comment]
Just tried an upgrade to 20404, still bootloops.

Last working version was 20401.

**Comment by norbertc** [comment]
I also experienced this on my Pixel 4 XL on Android 10. Reverting to 20404 allows my device to boot. No logs found.

**Comment by norbertc** [comment]
I also experienced this on my Pixel 4 XL on stock Android 10 (April update). Reverting to 20401 allows my device to boot. No logs found.

**Comment by topjohnwu** [comment]
@linuxandria may you test the latest canary now?

**Comment by IdanHo** [comment]
Happend as well on my device (Xiaomi Redmi Note 5 Pro), canary versions 20402, 20403, 20404 did not work on my device, but it seems the latest canary version (20405) did fix the problem @topjohnwu

**Comment by linuxandria** [comment]
> @linuxandria may you test the latest canary now?

Well it boots. That's the good news.

Took me awhile to post this because I couldn't access anything via https....
.... because of an permission denied error on /system/etc/security/cacerts...
.. caused by a module that was working fine k 20401.
IDK if that really needs a separate issue though.

**Comment by linuxandria** [comment]
Upon further investigation, it looks like with the Move Certificates module, every cert besides the one in the module has 0000 permissions and says 0 bytes. So no, nothing can access them.

**Comment by osm0sis** [comment]
Might need to open a new issue for that one, since I can confirm the 7T bootloop issue is resolved, and all my modules seem to be working fine. :+1:
