### ISSUE TITLE
Magisk canary v20402 boot results for selected modules.

### ISSUE THREAD

**Issue by wbedard** [topjohnwu/Magisk#2708]
Device configuration as follows:
OnePlus 6T w/ OOS 10.3.2 (Android 10); full device encryption enabled

Initial steps taken:
- Updated Magisk Manager to canary v283
- Updated Magisk to v20402
- Placed device in Airplane Mode
- Rebooted into boot-loop

In TWRP
- Reinstalled TWRP + Magisk canary v20401
- Rebooted successfully
- Disabled Airplane Mode

In Magisk Manager:
- Updated Magisk to v20402
- Disabled all modules
- Placed device in Airplane Mode
- Rebooted successfully

In Magisk Manager, enabled following modules in order with indicated results:
1. Busybox for Android NDK v1.3.1.1; rebooted successfully
2. Systemless hosts 1.0; rebooted successfully
3. ZipSigner & Zip for Android v3.0; rebooted successfully
4. Aria2c for android v0.1.1 & DNSCrypt-Proxy2 v2.9.5; rebooted successfully
5. Single User Mod v1.6; rebooted successfully
6. Advanced Charging Controller v2020.4.17-beta; rebooted successfully
7. SQLite for ARM aarch64 devices v1.3; rebooted successfully
8. Google Dialer Framework v5; rebooted successfully
9. Global Optimized GPS File Replacer v6; **experienced boot-loop**
9a. Disabled module in TWRP and rebooted
10. OOS Native Call Recording Enabler v8.0; rebooted successfully
11. Substratum (app v1022); rebooted successfully

[ Update: Device booted fine under Magisk v20401 and previous with all modules listed above. ]

Thanks for all your work in supporting and improving Magisk!

**Comment by osm0sis** [comment]
#2707
