### ISSUE TITLE
BOOTLOOP : LATEST Magisk Canary creates BOOTLOOP on TECNO Camon CX Air

### ISSUE THREAD

**Issue by Mikesew1320** [topjohnwu/Magisk#2710]
BRAND:-TECNO

MODEL:-Camon CX Air

CHIPSET:-MT6737M

ANDROID:-BASE ROM= 7.0(N)  PORT ROM= 7.0(N)

RAM:-2GB

[TECNO Camon CX Air Details](https://m.gsmarena.com/tecno_camon_cx_air-ampp-9445.php)

**Comment by osm0sis** [comment]
#2707

**Comment by lennyAiko** [comment]
I just had same bootloop issue, had to wipe my data.
