### ISSUE TITLE
Latest Magisk (e219867c) fail to mount tmps for modules

### ISSUE THREAD

**Issue by Fox2Code** [topjohnwu/Magisk#2713]
The new module mount rewrite seem to not handle tmpfs mount correctly

This issues can caused my phone to bootloop

I put the full magisk.log file + isolated the interesting part of the logs directly in the issue
```
04-20 07:33:21.416  3136  3137 E Magisk  : mount tmpfs->/system/etc/permissions failed with 2: No such file or directory
04-20 07:33:21.416  3136  3137 I Magisk  : mnt_tmp : /system/etc/permissions <- tmpfs
04-20 07:33:21.416  3136  3137 E Magisk  : open: /system/etc/permissions/android.hardware.bluetooth_le.xml failed with 2: No such file or directory
04-20 07:33:21.416  3136  3137 E Magisk  : mount /sbin/.magisk/mirror/system/etc/permissions/android.hardware.bluetooth_le.xml->/system/etc/permissions/android.hardware.bluetooth_le.xml failed with 2: No such file or directory
```
[magisk.log](https://github.com/topjohnwu/Magisk/files/4501968/magisk.log)

## How to reproduce

1. Install a module that will make Magisk use tmpfs (like xmlpak)
2. Install latest Magisk version
3. Reboot

**Comment by bombadier** [comment]
I am having a similar problem with ViperMod, cannot install the driver, log attached

[mount tmpfs fail.txt](https://github.com/topjohnwu/Magisk/files/4503112/mount.tmpfs.fail.txt)

[Full_magisk_log_20200420_121734.log](https://github.com/topjohnwu/Magisk/files/4503100/magisk_log_20200420_121734.log)

**Comment by topjohnwu** [comment]
Thanks, it's a bug in the new module mounting system. Good catch!

**Comment by enovella** [comment]
I can confirm it as well on Pixel3a with latest Android 11 beta:
![Screenshot from 2020-04-20 14-07-56](https://user-images.githubusercontent.com/14809754/79751823-878cf280-8313-11ea-8c48-75b82d4cc205.png)
