### ISSUE TITLE
Always "Checking for updates"

### ISSUE THREAD

**Issue by RA1NN1AR** [topjohnwu/Magisk#2714]
In China region.

**Comment by topjohnwu** [comment]
Magisk hosts all files on GitHub. Maybe kindly ask your government why they're blocking GitHub?

**Comment by linuxandria** [comment]
> Magisk hosts all files on GitHub. Maybe kindly ask your government why they're blocking GitHub?

"Excuse me could you pretty please unblock GitHub? See I really need to update my magisk, and...."

Sorry, somebody had to.
