### ISSUE TITLE
After updating the latest version of magisk (e219867c (20402)), Edxposed related errors appear

### ISSUE THREAD

**Issue by qq3092547800** [topjohnwu/Magisk#2715]
As mentioned, after the update, Edxposed shows that it is activated but the xposed module does not take effect.  The update before e219867c (20402) did not show this kind of situation. After the update, SELinux needs to be closed to take effect.  After communicating with the author of edxposed, it is expressed as a problem of magisk. The device model is Xiaomi MIX2S MIUI11 Android 10.

**Comment by Fox2Code** [comment]
Please provides logs if possible.
And I think there a high chance of this issue being related to #2713

**Comment by qq3092547800** [comment]
> 请提供日志（如果可能）。
> 而且我认为这个问题与[＃2713](https://github.com/topjohnwu/Magisk/issues/2713)相关的可能性很高[](https://github.com/topjohnwu/Magisk/issues/2713)
Okay, the log is as follows
[magisk_log_20200421_013115.log](https://github.com/topjohnwu/Magisk/files/4505092/magisk_log_20200421_013115.log)

**Comment by qq3092547800** [comment]
The log shows a strange time ...

**Comment by Fox2Code** [comment]
Ok, it's not related to the issue I created...
If you say when you disable SELinux EdXposed work again it's possible that the SELinux context is not correctly set when creating bind mount.

**Comment by qq3092547800** [comment]
> 好的，这与我创建的问题无关...
> 如果您说当再次禁用SELinux EdXposed工作时，可能在创建绑定安装时未正确设置SELinux上下文。

Okay thank you

**Comment by qq3092547800** [comment]
> Ok, it's not related to the issue I created...
> If you say when you disable SELinux EdXposed work again it's possible that the SELinux context is not correctly set when creating bind mount.

Okay thank you

**Comment by osm0sis** [comment]
Modules and booting are broken on a lot of devices right now, so maybe try again with 20405 when it comes.

**Comment by pokemontotalwar** [comment]
@osm0sis is a download of the version before 20402 available at all?

**Comment by qq3092547800** [comment]
> Modules and booting are broken on a lot of devices right now (20402+), so maybe try again with 20405 when it comes.

Unfortunately, the problem was not resolved in (20405) ...

**Comment by qq3092547800** [comment]
> Modules are still screwed up in 20405, I'll let you know when things seem to be generally working again.

Okay thank you

**Comment by osm0sis** [comment]
Okay, I guess they are generally working again with 20405, but there are still a few outliers/regressions in the new module logic topjohnwu is working on. Try again with 20406 when it's out please.

**Comment by qq3092547800** [comment]
> Okay, I guess they are generally working again with 20405, but there are still a few outliers/regressions in the new module logic topjohnwu is working on. Try again with 20406 when it's out please.

Oh ... the 20406 version does not seem to be displayed in the update

**Comment by osm0sis** [comment]
**_when it's out_**

**Comment by qq3092547800** [comment]
> **_when it's out_**

Ok

**Comment by topjohnwu** [comment]
Fixed 2468f5a6c4661d1cfe591511717bd56580a4e0ca
