### ISSUE TITLE
Latest Canary Manager does not show installed modules

### ISSUE THREAD

**Issue by WrichikBasu** [topjohnwu/Magisk#2717]
After the issue in #2631 was fixed, I uninstalled and reinstalled the canary release of Magisk Manager from the link given in the readme.md of this repository. Now the modules tab loads, but unfortunately it does **not** list the **installed** modules. The list of remote modules (i.e. those I haven't installed) comes up fine.

This is on Samsung Galaxy On7 running Android 6.0.1. The version of Magisk is 20.4 stable.

Note that the stable version of Manager can load the installed modules properly.

One screenshot of the problem:

![screenshot_canary_manager](https://user-images.githubusercontent.com/56736644/79747199-e9a42280-8328-11ea-90b1-a129f9e3e5df.png)

I can upload the logcat if requested.

**Comment by topjohnwu** [comment]
@WrichikBasu you have to use the manager with latest Magisk
