### ISSUE TITLE
HUAWEI P9 EVA-AL00 B377  bootloop ERROR

### ISSUE THREAD

**Issue by AmateurX-14** [topjohnwu/Magisk#272]
ROM: HUAWEI P9 EVA-AL00 B377

i use TWRP  flash Magisk-v13.1.zip  but my device is not supported!

ROM Download: 
[https://tuttoandroid.net/forum/threads/guida-huawei-p9-cambiare-paese-vendor-oeminfo-cust-upgrade-firmware-6-0-e-7-0-con-dload-e-twrp.54719/](url)

Download link at  # 1 floor at the bottom

> “Anticipazione (Spoiler): Firmware Cinesi”
>“Anticipazione (Spoiler): Android 7.0 - EMUI 5.0”
>“EVA-AL00B377 system data”

**Comment by JERW86** [comment]
Try [this](https://forum.xda-developers.com/showpost.php?p=72990463&postcount=15680) to help solve the issue

**Comment by AmateurX-14** [comment]
I try Magisk-v13.1-170711.zip but my device bootloop agian
and magisk_debug.log  does not exist with  /data

**Comment by AmateurX-14** [comment]
ohhh!! I was flash the uninstall pack before.  now i can see magisk_debug.log

`--------- beginning of main
W/auditd  (  352): type=2000 audit(0.0:1): initialized
I/auditd  (  352): type=1403 audit(0.0:2): policy loaded auid=4294967295 ses=4294967295
W/auditd  (  352): type=1404 audit(0.0:3): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295
W/modem_sysboot_s(  213): type=1400 audit(0.0:4): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
I/auditd  (  362): type=1403 audit(0.0:5): policy loaded auid=4294967295 ses=4294967295
W/modem_sysboot_s(  213): type=1400 audit(0.0:6): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:7): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:8): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:9): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:10): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:11): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:12): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
I/Magisk  (  361): Magisk v13.1 (170711)(170711) daemon started
I/Magisk  (  361): ** post-fs mode running
I/logcat  (  366): type=1400 audit(0.0:13): avc: denied { read } for name="hwlog_switch" dev="tmpfs" ino=1299 scontext=u:r:su:s0 tcontext=u:object_r:logcat_device:s0 tclass=chr_file permissive=1
I/logcat  (  366): type=1400 audit(0.0:14): avc: denied { open } for path="/dev/hwlog_switch" dev="tmpfs" ino=1299 scontext=u:r:su:s0 tcontext=u:object_r:logcat_device:s0 tclass=chr_file permissive=1
W/modem_sysboot_s(  213): type=1400 audit(0.0:15): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:16): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:17): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:18): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:19): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:20): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:21): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:22): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:23): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:24): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:25): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:26): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
W/modem_sysboot_s(  213): type=1400 audit(0.0:27): avc: granted { setsched } for scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
I/        (  392): debuggerd: starting
I/        (  391): debuggerd: starting
I/auditd  (  362): type=1403 audit(0.0:28): policy loaded auid=4294967295 ses=4294967295
I/teecd   (  390): 
I/teecd   (  390): ********* framework multi-user notify on socket successfully initialized *********
I/vdc     (    1): 200 395 Command succeeded
I//system/bin/tzdatacheck(  406): tzdata file /data/misc/zoneinfo/current/tzdata does not exist. No action required.
I/lowmemorykiller(  418): Using in-kernel low memory killer interface
E/XmlParser(  417): open file:/vendor/etc/HwFrameworkNormalization.xml filed in parseXml
E/XmlParser(  417): parse File:/vendor/etc/HwFrameworkNormalization.xml failed
I/libEGL  (  417): egl_cache_t() !XML_VALUE_GETCORRECT NAME_MAXKEYSIZE
E/XmlParser(  417): open file:/vendor/etc/HwFrameworkNormalization.xml filed in parseXml
E/XmlParser(  417): parse File:/vendor/etc/HwFrameworkNormalization.xml failed
I/libEGL  (  417): egl_cache_t() !XML_VALUE_GETCORRECT NAME_MAXTOTLESIZE
I/libEGL  (  417): egl_cache_t() maxKeySize:1024  maxTotalSize:65536
I/SurfaceFlinger(  417): sUseExtendedImpls=0, 
I/SurfaceFlinger(  417): SurfaceFlinger is starting
E/        (  417): new: SurfaceFlingerEx
I/SurfaceFlinger(  417): SurfaceFlinger's main thread ready to run. Initializing graphics H/W...
E/XmlParser(  417): open file:/vendor/etc/HwFrameworkNormalization.xml filed in parseXml
E/XmlParser(  417): parse File:/vendor/etc/HwFrameworkNormalization.xml failed
E/XmlParser(  417): open file:/vendor/etc/HwFrameworkNormalization.xml filed in parseXml
E/XmlParser(  417): parse File:/vendor/etc/HwFrameworkNormalization.xml failed
I/SurfaceFlinger(  417): initConfigsFromXmlFile:  vsyncPhaseOffsetNs 9000000; sfVsyncPhaseOffsetNs 9000000
E/bastetd (  425): [BastetXmlParser] parseBastetXml# Can not load: /data/bastet/hw_bastet_partner.xml
E/bastetd (  425): [BastetXmlParser] parseBastetXml# Can not parse: /system/emui/china/xml/hw_bastet_partner.xml
E/bastetd (  425): [BastetXmlParser] parseFastGrabScreenOffRKT# TAG_RRC_KEEP_TIME is null!
E/bastetd (  425): [BastetXmlParser] parseBastetXml# Can not load: /system/emui/base/xml/hw_bastet_partner.xml
W/linker  (  412): /vendor/lib64/libperfhub.so: unused DT entry: type 0xf arg 0x38e6
W/linker  (  412): /vendor/lib64/libhwuibp.so: unused DT entry: type 0xf arg 0xe3a
I/HisiKeyMaster(  394): hisi_km_open start
I/gralloc (  417): alloc_device_get_ddr_interlace:319: get ddr interlace fail, fd=-1, err=No such file or directory
I/gralloc (  417): init_frame_buffer_locked:340: using (fd=20)
I/gralloc (  417): id           = hisifb0
I/gralloc (  417): xres         = 1080 px
I/gralloc (  417): yres         = 1920 px
I/gralloc (  417): xres_virtual = 1080 px
I/gralloc (  417): yres_virtual = 5760 px
I/gralloc (  417): bpp          = 16
I/gralloc (  417): r            = 11:5
I/gralloc (  417): g            =  5:6
I/gralloc (  417): b            =  0:5
I/gralloc (  417): init_frame_buffer_locked:347: width        = 64 mm (428.625000 dpi)
I/gralloc (  417): height       = 114 mm (427.789459 dpi)
I/gralloc (  417): refresh rate = 60.00 Hz
I/gralloc (  417): gralloc_prealloc_thread_init:212: gralloc_prealloc_thread_init in pid 417
I/gralloc (  417): gralloc_prealloc_thread_init:247: gralloc_prealloc_thread_init out pid 417
W/hwcomposer(  417): Connect:100: Disp resolution(1080 x 1920), fps: 62 Hz.
I/SurfaceFlinger(  417): Using composer version 1.4
I/SurfaceFlinger(  417): EGL information:
I/SurfaceFlinger(  417): vendor    : Android
I/SurfaceFlinger(  417): version   : 1.4 Android META-EGL
I/SurfaceFlinger(  417): extensions: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_create_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update 
I/SurfaceFlinger(  417): Client API: OpenGL_ES
I/SurfaceFlinger(  417): EGLSurface: 8-8-8-8, config=0x7f7f6e5008
I/SurfaceFlinger(  417): OpenGL ES informations:
I/SurfaceFlinger(  417): vendor    : ARM
I/SurfaceFlinger(  417): renderer  : Mali-T880
I/SurfaceFlinger(  417): version   : OpenGL ES 3.2 v1.r12p1-04bet0.76b1d268c59a490265a02c702c8aa55c
I/SurfaceFlinger(  417): extensions: GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture G
I/SurfaceFlinger(  417): GL_MAX_TEXTURE_SIZE = 8192
I/SurfaceFlinger(  417): GL_MAX_VIEWPORT_DIMS = 8192
I/gralloc (  417): alloc_device_get_ddr_interlace:319: get ddr interlace fail, fd=-1, err=No such file or directory
I/gralloc (  417): alloc_device_alloc:564: Alloc handle(0x7f7f20f400): interfmt=200000001, stride=1088, size=8486912, usage=0x1a00
I/gralloc (  417): alloc_device_alloc:564: Alloc handle(0x7f7f656c00): interfmt=200000001, stride=1088, size=8486912, usage=0x1a00
I/gralloc (  417): alloc_device_alloc:564: Alloc handle(0x7f7f656e00): interfmt=200000001, stride=1088, size=8486912, usage=0x1a00
E/XmlParser(  412): open file:/vendor/etc/HwFrameworkNormalization.xml filed in parseXml
E/XmlParser(  412): parse File:/vendor/etc/HwFrameworkNormalization.xml failed
I/libEGL  (  412): egl_cache_t() !XML_VALUE_GETCORRECT NAME_MAXKEYSIZE
E/XmlParser(  412): open file:/vendor/etc/HwFrameworkNormalization.xml filed in parseXml
E/XmlParser(  412): parse File:/vendor/etc/HwFrameworkNormalization.xml failed
I/libEGL  (  412): egl_cache_t() !XML_VALUE_GETCORRECT NAME_MAXTOTLESIZE
I/libEGL  (  412): egl_cache_t() maxKeySize:1024  maxTotalSize:65536
E/XmlParser(  467): open file:/vendor/etc/HwFrameworkNormalization.xml filed in parseXml
E/XmlParser(  467): parse File:/vendor/etc/HwFrameworkNormalization.xml failed
I/libEGL  (  467): egl_cache_t() !XML_VALUE_GETCORRECT NAME_MAXKEYSIZE
E/XmlParser(  467): open file:/vendor/etc/HwFrameworkNormalization.xml filed in parseXml
E/XmlParser(  467): parse File:/vendor/etc/HwFrameworkNormalization.xml failed
I/libEGL  (  467): egl_cache_t() !XML_VALUE_GETCORRECT NAME_MAXTOTLESIZE
I/libEGL  (  467): egl_cache_t() maxKeySize:1024  maxTotalSize:65536
E/        (  412): [xmlFilesLoad:69] Load XML File [/system/vendor/etc/restart_app.xml] Failed : errorID(3)
E/        (  412): [xmlFilesLoad:69] Load XML File [/vendor/etc/restart_app.xml] Failed : errorID(3)
E/        (  412): [xmlFilesLoad:69] Load XML File [/system/etc/restart_app.xml] Failed : errorID(3)
E/        (  412): [loadRestartWhiteList:856] RestartWhiteList XML is not existence 
E/        (  412): [xmlFilesLoad:69] Load XML File [/system/vendor/etc/decodebitmap.xml] Failed : errorID(3)
E/        (  412): [xmlFilesLoad:69] Load XML File [/vendor/etc/decodebitmap.xml] Failed : errorID(3)
E/        (  412): [xmlFilesLoad:69] Load XML File [/system/etc/decodebitmap.xml] Failed : errorID(3)
E/        (  412): [xmlFilesLoad:69] Load XML File [/system/vendor/etc/landscape.xml] Failed : errorID(3)
E/        (  412): [xmlFilesLoad:69] Load XML File [/vendor/etc/landscape.xml] Failed : errorID(3)
E/        (  412): [xmlFilesLoad:69] Load XML File [/system/etc/landscape.xml] Failed : errorID(3)
E/        (  412): [loadLandScapeList:939] LandScape XML is not existence 
E/teecd   (  390): Error: unable to parse xml file
I/HisiKeyMaster(  394): hisi_km_open success
I/HisiKeyMaster(  394): hisi_km_begin start
I/HisiKeyMaster(  394): open first km session
I/HisiKeyMaster(  394): out_params is NULL
I/HisiKeyMaster(  394): out_params_buffer_len = 4096
I/HisiKeyMaster(  394): hisi_km_begin success
I/HisiKeyMaster(  394): hisi_km_finish start
I/HisiKeyMaster(  394): output data size=256
I/HisiKeyMaster(  394): hisi_km_finish success
I/HisiKeyMaster(  394): hisi_km_close start
I/HisiKeyMaster(  394): hisi_km_close success
E/        (  467): rmt_oeminfo_get_info, get data from server fail
E/hw_oeminfo_impl(  467): int hw_get_bootanimationparam_mccmnc(uchar *), rmt_oeminfo_get_info fail
E/BootAnimation(  467): BootAnimation, hwbootanim_mccmnc read error
E/        (  467): rmt_oeminfo_read, get data from server fail
E/BootAnimation(  467): BootAnimation, hwbootanim_ringmode read error
E/        (  467): rmt_oeminfo_read, get data from server fail
E/BootAnimation(  467): BootAnimation, hwbootanimswitch read error
I/ServiceManager(  467): Waiting for service media.audio_policy...
I/HisiKeyMaster(  394): hisi_km_open start
E/teecd   (  390): Error: unable to parse xml file
I/HisiKeyMaster(  394): hisi_km_open success
I/HisiKeyMaster(  394): hisi_km_close start
I/HisiKeyMaster(  394): hisi_km_close success
I/ServiceManager(  467): Waiting for service media.audio_policy...
I/vdc     (    1): 200 539 Command succeeded
I//system/bin/tzdatacheck(  540): tzdata file /data/misc/zoneinfo/current/tzdata does not exist. No action required.
I/Magisk  (  361): ** post-fs-data mode running
I/Magisk  (  361): * Mounting /data/magisk.img
`
