### ISSUE TITLE
How to modify file's rights while using magisk module

### ISSUE THREAD

**Issue by cosinio** [topjohnwu/Magisk#2723]
For android Q's dynamic partition feature, I'm using magisk module to update file in system partition which works like a charm, but is there any way to modify the file's rights? something like "chmod xxx system/blablabla".  As I can see, all files will set to 0644 by default .

**Comment by linuxandria** [comment]
In customize.sh add:
```
chmod <permissions, eg 0755> -R $MODPATH/system/files/path/goes/here
chown -R <user>:<user> $MODPATH/system/file/path
```

The only difference from usual is the need to prefix everything with $MODPATH in customize.sh in your module.
To adjust at runtime: (I recommend doing this in post-fs-data.sh to prevent confilcts)
```
MODDIR=${0%/*}
chmod -R <permissions, eg 0755> $MODDIR/system/files/path
chown -R <user>:<user> $MODDIR/system/files/path
```

If you need more help I can help you out on telegram: https://t.me/inlmagisk

**Comment by cosinio** [comment]
@linuxandria  Thank u for your reply, I'll make a research on that and try to check if it works for me.

**Comment by cosinio** [comment]
@Didgeridoohan  Thank you for your tips, but i've tried set_perm function and even chmod,chown commadn in customize.sh, it seems doesn't work.  

In my zip folder:

── META-INF
│   └── com
│       └── google
│           └── android
│               ├── update-binary      <--- The same with module_installer.sh 
│               └── updater-script     <---  "#MAGISK"
│
├── customize.sh                       

├── ...
├── ... System
│               └── app
│                    └── MyAppFolder
│                         └── My.apk


In customize.sh, i've tried 

set_perm $MODPATH/system/app/MyAppFolder/My.apk 0 0 000 000 

Then I add this module in magisk restart the device,  the My.apk file in MyAppFolder is still in 644 previlege.

**Comment by Didgeridoohan** [comment]
@cosinio Remove that last 000 and see if that works better. I'm using set_perm in my module customize.sh without issue:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/1f89f205e0ba67cac95fbd9467780e794c117ace/customize.sh#L33
