### ISSUE TITLE
tmpfs mounts can mount into mirror mounts

### ISSUE THREAD

**Issue by linuxandria** [topjohnwu/Magisk#2725]
As of 20401, the Move Certificates module caused no issue.

As of 20405, every certificate in /system/etc/security/cacerts has 0000 permissions and says 0B, except the one installed by the module.

This behavior causes every single HTTPS connection to fail of course.

Further testing is required to see if this effects other modules.

Logcat to follow, showing the errors.

Device: OnePlus 7T, Android 10, OxygenOS 10.0.9

**Comment by linuxandria** [comment]
[logcat.log](https://github.com/topjohnwu/Magisk/files/4516772/logcat.log)
[magisk.log](https://github.com/topjohnwu/Magisk/files/4516774/magisk.log)

**Comment by osm0sis** [comment]
Since they're 0 byte files, sounds like the mirror mounts over the dummy skeleton files failed for some reason.

**Comment by topjohnwu** [comment]
This is yet another bug in the module implementation. tmpfs mounts will mount into mirror mounts, which defeats the point of mirrors.

**Comment by linuxandria** [comment]
This is not resolved in 20406

**Comment by topjohnwu** [comment]
It is why this issue isn't closed dude

**Comment by linuxandria** [comment]
> It is why this issue isn't closed dude

I saw that "fix modules mounting edge cases" in the changelog, and besides that it's always nice to know if you accidentally fix something by fixing something else lol
