### ISSUE TITLE
Magisk Manager (stable) potential weak link for Magisk Hide

### ISSUE THREAD

**Issue by Palaryel** [topjohnwu/Magisk#2726]
I use Magisk Hide mostly in order to be able to use banking apps while rooted. A couple of days ago my banking app (com.starfinanz.smob.android.bwpushtan) updated to version 1.1.2

After the update the app started detecting that the device is rooted (despite no other changes to the device). I tried reinstalling Magisk and Magisk Manager, restoring/rehiding the manager, etc...

Eventually I discovered that Manager seems to be triggering the detection, since even if the device stays rooted (rooted boot image flashed) the app is NOT detecting root if Manager is uninstalled (regardless if Manager is repackaged to another name or not).

Today I tried the canary build for the manager (Magisk itself remained on stable) and the app is not detecting root.

I suspect the app found a way to recognize the stable Manager app even if repackaged (maybe by detecting the icon or something similar?).

**Comment by osm0sis** [comment]
Canary is the way forward, and you already found it works there, so the issue is invalid. Keep using Canary. :+1:
