### ISSUE TITLE
Need magiskboot windows source.

### ISSUE THREAD

**Issue by seci20** [topjohnwu/Magisk#2727]
Hi. I have been dealing for a long time and I could not compile magiskboot application as exe. Can you explain how to compile for free or paid ?

**Comment by osm0sis** [comment]
You were already answered in #2677 and #2689. We won't answer you at all next time and will simply close your issues.

**Comment by seci20** [comment]
> You were already answered in #2677 and #2689. We won't answer you at all next time and will simply close your issues.

I know, but I wasn't successful at compiling, so I write over and over again. I am a Delphi expert, I don't understand c ++ so I ask for your help.
