### ISSUE TITLE
I was wondering if theres a way to make this work on my device

### ISSUE THREAD

**Issue by DJDISDABEST** [topjohnwu/Magisk#2728]
The device i want to root is a Tracfone a502dl made by TLC
system specs:
model: A502DL
android version: 8.1.0
android security patch level: March, 5, 2019
kernel version: 4.4.95+ Thu March 7  18:44:38  2019
build number: vG7S
custom build version: alps-mp-o1.mp1-
V1.112_k39tv1.bsp_P27

People in other places have said this phone will be challenging to root

**Comment by osm0sis** [comment]
This isn't the place. Try xda or FreakTab.
