### ISSUE TITLE
Huawei ascend xt h1611 bootloop on 13.1 install 

### ISSUE THREAD

**Issue by nocturne-** [topjohnwu/Magisk#273]
Previously had 12.0 installed and working great, upgraded the manager and used it to install 13.1, and got a bootloop on reboot. Flashed stock boot.img, rebooted to find everything working fine, attempted to install 13.1 via zip in twrp - bootloop again. Uninstall script (updated version) doesn't seem to be working either (same bootloop, waited on it a good 30 minutes). 

Stock boot.img : https://drive.google.com/file/d/0B9h4eGxm1-85ZVlrNHNNLW1jcE0/view?usp=drivesdk

**Comment by JERW86** [comment]
Try [this](https://forum.xda-developers.com/showpost.php?p=72990463&postcount=15680) to help solve the issue.
