### ISSUE TITLE
Pixel 4 XL Bootloop

### ISSUE THREAD

**Issue by hanschke** [topjohnwu/Magisk#2731]
hello,

I use Android 11 DP 2.1 and patched the boot.img and flash with adb to get root. I have done a mistake and try to install edxposed canary. I stuck on bootloop and have to flash boot.img to get a working phone.

If I try to flash the patched boot.img from magisk canary again I stuck on bootloop again and do a power of after 10 minutes for waiting. I flash boot.img from stock again and the phone boots.

How can I fix it?

**Comment by topjohnwu** [comment]
GitHub issues is not a place to ask for tech support
