### ISSUE TITLE
[Feature Request] Automatically check “Recovery Mode” in Advanced Settings

### ISSUE THREAD

**Issue by Cyberavater** [topjohnwu/Magisk#2732]
Make Magisk Manager detect if the device supports  'System-as-root' and automatically check “Recovery Mode” in Advanced Settings.

An app that can detect 'System-as-root' support;
https://github.com/kevintresuelo/treble

It'd be wise to check it's source code and implement it on Magisk Manager.

**Comment by topjohnwu** [comment]
It already does this when recovery mode is required

**Comment by Cyberavater** [comment]
Well it says here https://topjohnwu.github.io/Magisk/install.html#boot-image-patching

> If you are patching a recovery image, manually check “Recovery Mode” in Advanced Settings!
