### ISSUE TITLE
Issue with direct install 

### ISSUE THREAD

**Issue by mtriple** [topjohnwu/Magisk#2735]
Signture isse
[magisk_install_log_2020-04-24T13:12:49Z.log](https://github.com/topjohnwu/Magisk/files/4528295/magisk_install_log_2020-04-24T13.12.49Z.log)

**Comment by osm0sis** [comment]
Device info?

**Comment by mtriple** [comment]
samsung a8 andriod 6.0.1. i installed older version of the manger and its working fine.

**Comment by osm0sis** [comment]
Sounds like #2609 then, though your output is a bit different. What the last old version of Manager that works for you?

**Comment by mtriple** [comment]
i think 4 versions earlier im not sure .. but i manage to install the superuser update via recovery..

**Comment by osm0sis** [comment]
That's still pretty vague, I need you to tell us exactly which Manager worked last please.

**Comment by osm0sis** [comment]
Follow up in #2609. I'm closing this as a duplicate.
