### ISSUE TITLE
HOW TO USE SNAPCHAT WITH MAGISK WITH NEW SAFETYNET

### ISSUE THREAD

**Issue by EduardJipa** [topjohnwu/Magisk#2737]
Basically just completely uninstall edxposed & magisk, which will delete TWRP too, then boot & reset the caches and delete app data for:

- Google Play Store
- Google Play Services
- Google Services Framework
- Google Pay
- Snapchat

Reboot, log in to snapchat (It may fail a few times, worked 3rd try in for me)

May work for other apps such as google pay or netflix

(Also sorry if this is the wrong section, just wanted to help others in the same situation as I was)

**Comment by QkiZMR** [comment]
Lol, this is not xda forum dude 😄

**Comment by EduardJipa** [comment]
Yeah I know haha, just wanted to help a few in my situation out
