### ISSUE TITLE
Magisk v13.1 does not work on stock ROM of P8 Lite, and quite possibly most Huawei ROMs

### ISSUE THREAD

**Issue by JpegXguy** [topjohnwu/Magisk#274]
Running EMUI 4.0.3, build ALE-L21C432B602.
Everything goes well in TWRP while flashing, but the manager app is not installed. After installing it manually, the result is no root and no Magisk. The last v13 beta (c4377ed) works fine.

[Here](http://update.hicloud.com:8180/TDS/data/files/p3/s15/G1084/g104/v88317/f1/full/update.zip)'s the firmware package. (It contains the UPDATE.APP file that can be split into .img files with [Huawei Update Extractor](https://forum.xda-developers.com/showthread.php?t=2433454))

Anyhow the stock boot image by itself is attached: [boot.zip](https://github.com/topjohnwu/Magisk/files/1139748/boot.zip)

**Comment by Ante0** [comment]
Could you attach twrp log? adb pull /tmp/recovery.log after flashing or use the Copy Log button in twrp. 

It works on Mate 9, but I'm on emui 5.0.

**Comment by JpegXguy** [comment]
Interesting. I have attached the recovery log after doing a factory reset and rebooting to TWRP. 
[recovery.txt](https://github.com/topjohnwu/Magisk/files/1141650/recovery.txt)

**Comment by JpegXguy** [comment]
13.2 works flawlessly
