### ISSUE TITLE
Extend the file_contexts [magiskpolicy]

### ISSUE THREAD

**Issue by Paschalis** [topjohnwu/Magisk#2744]
### Problem:
I would like to extend the `file_contexts` to set a directory to particular class.
For example, similarly to [this](https://cs.android.com/android/platform/superproject/+/master:system/sepolicy/private/file_contexts;l=577?q=%22%2Fdata%2Fmisc%2Fprofiles%22&ss=android%2Fplatform%2Fsuperproject), I would like to add the following:
`/data/misc/profiles/mydata(/.*)?       u:object_r:user_profile_data_file:s0`

I have looked both into [sepolicy.rule](https://github.com/topjohnwu/Magisk/blob/master/docs/guides.md#sepolicyrule) and [magiskpolicy](https://github.com/topjohnwu/Magisk/blob/master/docs/tools.md#magiskpolicy), but I haven't figured this out. I've also looked on all the [issues](https://github.com/topjohnwu/Magisk/issues) concerning selinux.

### Why I need a separate folder:
This would allow me creating per app data and store them to the `mydata` folder.
I could have used `cur` or `ref` folders but those are managed by other components, and are probably deleted on application reinstallation or removal. Same with the internal storage of the app.
So having a separate folder would preserve those data for me. And given that all other rules are already setup for profile `cur` and `ref` folders, making and marking another folder as `user_profile_data_file` should be the only modification to policy that I will required to do.

### Why I need to use this in a similar manner with ART profiles: (e.g. [cur](https://cs.android.com/android/platform/superproject/+/master:system/sepolicy/private/file_contexts;l=577?q=%22%2Fdata%2Fmisc%2Fprofiles%22&ss=android%2Fplatform%2Fsuperproject))
I am modifying the runtime (ART) and the compiler for a research project. I am testing on apps that I haven't written, and I need to store some data. The apps should not require extra special permissions as I won't be modifying them (no sdcard permissions , no su, nothing extra..).

**Comment by linuxandria** [comment]
@topjohnwu this is actually a curious use case that I really don't think magiskpolicy currently covers. Do you think it would be possible to extend it to do this? 
Because from my current understanding this would require recompiling sepolicy completely and if one is on a stock rom that's not do easily done....

**Comment by Paschalis** [comment]
@linuxandria my knowledge on the subject is limited, but would allow people to "tinker" in a more secure way. Currently I think the only you can do is to patch the policy rules to give _more_ permissions than it should for existing file contexts. Which might be a good workaround that imposes some risks.

With #2744 in place (if it's not already possible) I could have ideally done this for the above example:

**file_contexts:**
`/data/misc/profiles/mydata(/.*)? u:object_r:MY_CLASS:s0`

**my_magisk_module:**
 ─ **sepolicy.rule**:

```
allow appdomain MY_CLASS:dir { search write add_name };
allow appdomain MY_CLASS:file create_file_perms;
```


currently I think you can only do "workarounds"


this would essentially allow adding new classes and then handling them

**Comment by reiryuki** [comment]
I have a file with new SE context u:object_r:hal_dms_default_exec:s0 with my module

I only put this to sepolicy.rule so the device can confirm the new SE context (not consider it as "unlabeled"):

`type hal_dms_default_exec`
