### ISSUE TITLE
Magisk Hide not work to richart app

### ISSUE THREAD

**Issue by jjim4963tw** [topjohnwu/Magisk#2746]
model：HTC U11
OS：Android 9 (HTC Official)
Magisk Manager：7.5.1
Magisk：20.4(20400)

today richart app update to 2.16.0 magisk hide not work!!!

use hide magisk manager and safe Mode not work either

**Comment by miaulightouch** [comment]
it's not related to Magisk.

please use root detector like [RootBeer](https://play.google.com/store/apps/details?id=com.scottyab.rootbeer.sample) to checkout which root feature wasn't hidden.

richart would check all of these feature, even the system.prop check.

if you encounter the "test-keys" problem, you should replace all props that contain "test-keys" to "release-key".
a magisk module: *MagiskHide Props Config* with few configure, may fix this issue.
