### ISSUE TITLE
Systemless Hosts module breaks sensors on Pixel 3a XL

### ISSUE THREAD

**Issue by Ninespire** [topjohnwu/Magisk#2751]
Pixel 3a XL bonito on Android 10 QQ2A.200405.005

Hello, I've noticed after I patch Magisk to the boot.img file, flash with fastboot, I try to enable systemless hosts and multiple sensors stop working. The sensors work before enabling systemless hosts.

My accellerometer, magnetometer, compass, gyroscope, and barometer stop working. This was observed with the Sensor Test app by Andrey Efrernov. 

Removing the module and rebooting doesn't restore functionality, I need to reflash the patched boot.img to restore the sensors.

Thank you!

**Comment by linuxandria** [comment]
There's actually an issue on Google's issue tracker for the sensor issue.

Weird that systemless hosts would mess it up tho....

**Comment by Ninespire** [comment]
If you're referring to the bug that's fixed by copying someone else's persist partition, I have reason to think that this isn't related to that issue. My phone didn't respond to any of the fixes I could find that fix that issue.

**Comment by topjohnwu** [comment]
Sorry, but this does not make any sense. There might be other factors that caused this issue (and is triggered by the addition of the host module), but definitely not the host module itself.
