### ISSUE TITLE
Samsung A51 Problem

### ISSUE THREAD

**Issue by breakersvd** [topjohnwu/Magisk#2753]
I know that this issue is duplicated but i want to add more info about this problem.

Flashed the stock firmware by ODIN then patched the same firmware using Magisk APK and Flashed 
by ODIN result a VBMETA SIGN error.

KEEPVERITY=true
KEEPFORCEENCRYPT=true
RECOVERYMODE=true

I Flashed the original `vbmeta` to fix the problem but a new problem happened because of `recovery` partition footer avb signature so I signed the Magisk patched recovery using avbtool and the error is fixed, But when doing normal boot, the device boots successfully without Magisk, When booting into recovery mode, the device goes into bootloop.

Flashed the stock firmware again then patched the boot image only and flashed by ODIN,
the result is reboot to download mode after execute the `init` exists in ramdisk in boot image
and the reason for that is patching the `fstab` file (changing /system to /system_root).

If we remove the patch fstab code the device will boot but without Magisk because the init Second stage will not executed.

About `vbmeta` & `vbmeta_samsung`:

**vbmeta info:**

> Minimum libavb version:   1.0
Header Block:             256 bytes
Authentication Block:     576 bytes
Auxiliary Block:          7680 bytes
Algorithm:                SHA256_RSA4096
Rollback Index:           0
Flags:                    0
Release String:           'avbtool 1.1.0'
Descriptors:
    Chain Partition descriptor:
      Partition Name:          recovery
      Rollback Index Location: 4
      Public key (sha1):       559e72df14e102d4162957661d6103c4f09d842d
    Chain Partition descriptor:
      Partition Name:          dtbo
      Rollback Index Location: 5
      Public key (sha1):       559e72df14e102d4162957661d6103c4f09d842d
    Chain Partition descriptor:
      Partition Name:          prism
      Rollback Index Location: 10
      Public key (sha1):       559e72df14e102d4162957661d6103c4f09d842d
    Chain Partition descriptor:
      Partition Name:          optics
      Rollback Index Location: 11
      Public key (sha1):       559e72df14e102d4162957661d6103c4f09d842d
    Prop: com.android.build.boot.os_version -> '10'
    Prop: com.android.build.boot.security_patch -> '2019-12-01'
    Prop: com.android.build.system.os_version -> '10'
    Prop: com.android.build.system.security_patch -> '2019-12-01'
    Prop: com.android.build.vendor.os_version -> '10'
    Prop: com.android.build.vendor.security_patch -> '2019-12-01'
    Hash descriptor:
      Image Size:            31175200 bytes
      Hash Algorithm:        sha256
      Partition Name:        boot
      Salt:                  c69868bd475a558a65815295a9d0a37b3631b24c69ab93761932d3e50ed49bec
      Digest:                251721b9daa83b27ef3a5633b1b5c2dcd4e61bbbe988c6cc71db6c9489269c34
      Flags:                 0
    Hash descriptor:
      Image Size:            3252752 bytes
      Hash Algorithm:        sha256
      Partition Name:        bootloader
      Salt:                  3c9c156f6dc6c1b51ce538b13c424d9e7ed1c60bb6c9bb5529ae1026d3b536cd
      Digest:                98fd54fe49926fb76e5c2ced73d9384edb2424281b88b0fa7a4bd27f5642356f
      Flags:                 0
    Hash descriptor:
      Image Size:            4112912 bytes
      Hash Algorithm:        sha256
      Partition Name:        cm
      Salt:                  e8b281d338f306f9f9f903281c6ffec2f0e5d6088cdc565a483e60a748aaa181
      Digest:                5266d200197442410b630a9b8406b032c890ecb63e719a676ea18e1a6a5d80af
      Flags:                 0
    Hashtree descriptor:
      Version of dm-verity:  1
      Image Size:            4194304 bytes
      Tree Offset:           4194304
      Tree Size:             36864 bytes
      Data Block Size:       4096 bytes
      Hash Block Size:       4096 bytes
      FEC num roots:         2
      FEC offset:            4231168
      FEC size:              40960 bytes
      Hash Algorithm:        sha256
      Partition Name:        odm
      Salt:                  9a95018ca7bcc07ef9a0ba3dff320630c87033355e8cf29789d24c39bb6f275a
      Root Digest:           1639ece65b569f5ec7049f26555df85a461cf3cbc75c5f885742aa5008d948be
      Flags:                 0
    Hashtree descriptor:
      Version of dm-verity:  1
      Image Size:            684888064 bytes
      Tree Offset:           684888064
      Tree Size:             5402624 bytes
      Data Block Size:       4096 bytes
      Hash Block Size:       4096 bytes
      FEC num roots:         2
      FEC offset:            690290688
      FEC size:              5464064 bytes
      Hash Algorithm:        sha256
      Partition Name:        product
      Salt:                  2fb44545abb42376949ffa086f348c12572d2f5ead4bdb798a782660b4ff06b0
      Root Digest:           4f75adadac999d68ce18f043377c53224d4a0df6044767b5d67c43c5a8bc5cbb
      Flags:                 0
    Hashtree descriptor:
      Version of dm-verity:  1
      Image Size:            4740907008 bytes
      Tree Offset:           4740907008
      Tree Size:             37335040 bytes
      Data Block Size:       4096 bytes
      Hash Block Size:       4096 bytes
      FEC num roots:         2
      FEC offset:            4778242048
      FEC size:              37773312 bytes
      Hash Algorithm:        sha256
      Partition Name:        system
      Salt:                  5da38be32b40441e7d72907b7c9c92342ad7a0b6c7d1bef3f3fc6ffb4cd6ebf7
      Root Digest:           e6635418579c73be61c626de63713bd8d7433e8b8c5611fcb8d150afe9f1bee7
      Flags:                 0
    Hashtree descriptor:
      Version of dm-verity:  1
      Image Size:            591912960 bytes
      Tree Offset:           591912960
      Tree Size:             4665344 bytes
      Data Block Size:       4096 bytes
      Hash Block Size:       4096 bytes
      FEC num roots:         2
      FEC offset:            596578304
      FEC size:              4718592 bytes
      Hash Algorithm:        sha256
      Partition Name:        vendor
      Salt:                  191530540024e9a6d3b64eab97adabc55d602350dc7850068ccb60c9c2e4b132
      Root Digest:           06acdb602fb937770ed912b0360b9f2bd628654c48dcd1d411087067ce107585
      Flags:                 0

**vbmeta_samsung info:**

> Minimum libavb version:   1.0
Header Block:             256 bytes
Authentication Block:     576 bytes
Auxiliary Block:          2048 bytes
Algorithm:                SHA256_RSA4096
Rollback Index:           0
Flags:                    0
Release String:           'avbtool 1.1.0'
Descriptors:
    Hashtree descriptor:
      Version of dm-verity:  1
      Image Size:            4194304 bytes
      Tree Offset:           4194304
      Tree Size:             36864 bytes
      Data Block Size:       4096 bytes
      Hash Block Size:       4096 bytes
      FEC num roots:         2
      FEC offset:            4231168
      FEC size:              40960 bytes
      Hash Algorithm:        sha256
      Partition Name:        odm
      Salt:                  9a95018ca7bcc07ef9a0ba3dff320630c87033355e8cf29789d24c39bb6f275a
      Root Digest:           1639ece65b569f5ec7049f26555df85a461cf3cbc75c5f885742aa5008d948be
      Flags:                 0
    Hashtree descriptor:
      Version of dm-verity:  1
      Image Size:            684888064 bytes
      Tree Offset:           684888064
      Tree Size:             5402624 bytes
      Data Block Size:       4096 bytes
      Hash Block Size:       4096 bytes
      FEC num roots:         2
      FEC offset:            690290688
      FEC size:              5464064 bytes
      Hash Algorithm:        sha256
      Partition Name:        product
      Salt:                  2fb44545abb42376949ffa086f348c12572d2f5ead4bdb798a782660b4ff06b0
      Root Digest:           4f75adadac999d68ce18f043377c53224d4a0df6044767b5d67c43c5a8bc5cbb
      Flags:                 0
    Hashtree descriptor:
      Version of dm-verity:  1
      Image Size:            4740907008 bytes
      Tree Offset:           4740907008
      Tree Size:             37335040 bytes
      Data Block Size:       4096 bytes
      Hash Block Size:       4096 bytes
      FEC num roots:         2
      FEC offset:            4778242048
      FEC size:              37773312 bytes
      Hash Algorithm:        sha256
      Partition Name:        system
      Salt:                  5da38be32b40441e7d72907b7c9c92342ad7a0b6c7d1bef3f3fc6ffb4cd6ebf7
      Root Digest:           e6635418579c73be61c626de63713bd8d7433e8b8c5611fcb8d150afe9f1bee7
      Flags:                 0
    Hashtree descriptor:
      Version of dm-verity:  1
      Image Size:            591912960 bytes
      Tree Offset:           591912960
      Tree Size:             4665344 bytes
      Data Block Size:       4096 bytes
      Hash Block Size:       4096 bytes
      FEC num roots:         2
      FEC offset:            596578304
      FEC size:              4718592 bytes
      Hash Algorithm:        sha256
      Partition Name:        vendor
      Salt:                  191530540024e9a6d3b64eab97adabc55d602350dc7850068ccb60c9c2e4b132
      Root Digest:           06acdb602fb937770ed912b0360b9f2bd628654c48dcd1d411087067ce107585
      Flags:                 0

As we can see the `vbmeta_samsung` is not responsible for recovery or boot images.
And the `vbmeta` is responsible for a lot of images including (boot, recovery).
And the bootloader does a secure check for the recovery image But as i said above we can sign the recovery using avbtool and get rid of all vbmeta patching or editing by flash.

So our problem now is in the FirstStageInit during boot process
@topjohnwu 
Hope you can fix it and i am ready to test

**Comment by topjohnwu** [comment]
Try to install Magisk with `KEEPVERITY=false`. I have ran into this issue in emulators

**Comment by breakersvd** [comment]
@topjohnwu 
I Tried but now the device goes into bootloop not to Download mode.

[fstabs.zip](https://github.com/topjohnwu/Magisk/files/4557723/files.zip)

**Comment by breakersvd** [comment]
@topjohnwu 
New thing was noticed:
Replacing ramdisk init with `magiskinit` 64bit will cause the bootloop (That means the magiskinit 64bit is never executed or crashed).
But using `magiskinit` 32bit is executed successfully and the code reaches the prepare function of FirstStageInit function but as mentioned above reboot to download modebecause of fstab patches

**Comment by map220v** [comment]
I patched boot.img with last Canary Magisk (debug) and got kmsg
KEEPVERITY=false
KEEPFORCEENCRYPT=false
RECOVERYMODE=false
[kmsg2.txt](https://github.com/topjohnwu/Magisk/files/4559964/kmsg2.txt)

**Comment by map220v** [comment]
Another kmsg with
KEEPVERITY=true
KEEPFORCEENCRYPT=false
RECOVERYMODE=false
[kmsg.txt](https://github.com/topjohnwu/Magisk/files/4560019/kmsg.txt)

**Comment by linuxandria** [comment]
```
[0:      12.938] LoadJPEG took 18 msec
avb_cmdline : androidboot.vbmeta.device=PARTUUID=52444E41-494F-2044-5642-4D4554410000 androidboot.vbmeta.avb_version=1.1 androidboot.vbmeta.device_state=unlocked androidboot.vbmeta.hash_alg=sha256 androidboot.vbmeta.size=17088 androidboot.vbmeta.digest=372f4df04c405f067c7e010b70c2fe2cf6124221066a9c211c345ed399c1a9af androidboot.vbmeta.invalidate_on_error=yes androidboot.veritymode=enforcing androidboot.verifiedbootstate=orange
[0:      13. 73] [TIMA trusted boot]: SEAndroid MAGIC failure (boot.img)
```

It's trying to verify boot and as expected failing.

Veritymode is enforcing, you have to find a way to get it permissive

**Comment by map220v** [comment]
@linuxandria Kernel still boots i can see magiskinit in kmsg

**Comment by linuxandria** [comment]
> @linuxandria Kernel still boots i can see magiskinit in kmsg

Yes kernel start booting but nonetheless that's the biggest thing I suspect preventing successful boot

**Comment by map220v** [comment]
@linuxandria Thats weird i still can boot my Permissive kernel and TWRP from boot.img

**Comment by linuxandria** [comment]
> @linuxandria Thats weird i still can boot my Permissive kernel and TWRP from boot.img

Not selinux permissive but verity permissive?

**Comment by map220v** [comment]
@linuxandria SELinux permissive .

I Think Samsung bootloader (Samsung S-Boot 4.0) sets androidboot.veritymode=enforcing i can't fix that.

**Comment by linuxandria** [comment]
> @linuxandria SELinux permissive .
> 
> I Think Samsung bootloader (Samsung S-Boot 4.0) sets androidboot.veritymode=enforcing i can't fix that.
> 
> Edit: After i changed data partition file system from f2fs to ext4, kernel not panics and phone now just stuck in boot loop.

Oof. You need a way to make verity not verify boot then. Probably a custom kernel.

**Comment by breakersvd** [comment]
@map220v 
Are you sure this log is from kernel booting process ?
I see info related to recovery boot process.

**Comment by map220v** [comment]
@breakersvd it's last_kmsg it's has bootloader load process, recovery and boot.img kernel 
search for magisk to find kernel boot process

**Comment by breakersvd** [comment]
@map220v 
Try just unpack and then repack the boot image without any patches then flash it
and get the kmsg log to see if the android.vbmeta error exists then it is not our problem

**Comment by map220v** [comment]
@breakersvd i patched stock boot.img. I don't have vbmeta error. only Magiskd service error

<0>[    8.349858]  [4:        magiskd: 4445] Unable to handle kernel read from unreadable memory at virtual address 4f35aa748

**Comment by breakersvd** [comment]
@map220v 
did the device boot after patch ?

**Comment by map220v** [comment]
@breakersvd no magiskd makes kernel panic 

also before kernel panic Magisk mounts system without error
magiskinit: SecondStageInit
magiskinit: Switch root to /system_root

**Comment by breakersvd** [comment]
@map220v 
So you think this happened after all patches are done and when the original init try to exec magisk rc codes ?

**Comment by map220v** [comment]
@breakersvd yes. post-fs-data from init.rc launches magiskd daemon

**Comment by breakersvd** [comment]
@map220v 
Could you explain to me how to get the `kmsg` log after bootloop because i am editing the Magisk codes and trying to do some fixes ?

**Comment by map220v** [comment]
@breakersvd after magisk bootloop i flashing TWRP that i ported from samsung a50
We can't flash TWRP in recovery partition thats why i made boot.img with TWRP ramdisk inside.

**Comment by breakersvd** [comment]
@map220v 
Could you share the TWRP with me ?

**Comment by map220v** [comment]
@breakersvd https://drive.google.com/file/d/1h2tDyrmkY_aHL4w-15r6zzfqCfJ-Y_-M/view?usp=sharing

**Comment by breakersvd** [comment]
@map220v 
Thanks, I will feedback with latest tests

**Comment by breakersvd** [comment]
@map220v 
It confused me, Without RC patches the device boots successfully with magisk files and su but without permissions because there is no daemon launched, Once i launch the daemon the kernel crash then force reboot.

I will contact John to check the issue and check the daemon compatibility with this device

**Comment by seci20** [comment]
Do you have any information about the new init ? eft dongle uses new init. The codes in Init seem to belong to you. @osm0sis @topjohnwu

**Comment by map220v** [comment]
I can boot Magisk with post-fs-data only if i have
/proc/sys/kernel/panic_on_oops set to 0

**Comment by rodrigofd** [comment]
@map220v how exactly did you set /proc/sys/kernel/panic_on_oops to 0 ?

**Comment by linuxandria** [comment]
> @map220v how exactly did you set /proc/sys/kernel/panic_on_oops to 0 ?

Boot script

```
#!/system/bin/sh
echo "0" > /proc/sys/kernel/panic_on_oops
```

You'll need to mess with *.rc scripts yo get it to run early enough probably

**Comment by osm0sis** [comment]
If you want to add more info, add it to the original Issue thread. #2272
