### ISSUE TITLE
Samsung Galaxy A30s SM-A307FN

### ISSUE THREAD

**Issue by Xmaster111** [topjohnwu/Magisk#2755]
Samsung Galaxy A30s SM-A307FN

One UI version: 1.5
Android version: 9
A307FNXXU2ATB1 / 
A307FNOEM2ASL3 /
A307FNXXU2ATB1

MagiskManager-v7.5.1.apk
![Fail](https://user-images.githubusercontent.com/47426810/80804536-c180b300-8bb5-11ea-82db-51f8be515fe0.jpg)

boot.ini files extracted from the original firmware by sammobile, the files were in boot.img.lz4 format, I just deleted .lz4 and patched it on the phone with Magisk 7.5.1, am I wrong?

```
- Device platform: arm64-v8a
- Copying image to cache
2034+0 records in
2034+0 records out
2082816 bytes transferred in 0.016 secs (130176000 bytes/sec)
1410+1 records in
1410+1 records out
1443916 bytes transferred in 0.012 secs (120326333 bytes/sec)
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
PXA_BOOT_HDR
HEADER_VER      [0]
KERNEL_SZ       [30496912]
RAMDISK_SZ      [301990144]
SECOND_SZ       [1110066]
EXTRA_SZ        [16777224]
PAGESIZE        [1179865170]
NAME            [18A002KU]
CMDLINE         [elinux=permissive ¬
�  ]
CHECKSUM        [0c949f3a03d568dc00b008a13991c9b600d029e132916adc00b04aa139913f01]
Segmentation fault
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
Add entry [init] (0750)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
PXA_BOOT_HDR
HEADER_VER      [0]
KERNEL_SZ       [30496912]
RAMDISK_SZ      [301990144]
SECOND_SZ       [1110066]
EXTRA_SZ        [16777224]
PAGESIZE        [1179865170]
NAME            [18A002KU]
CMDLINE         [elinux=permissive ¬
�  ]
CHECKSUM        [0c949f3a03d568dc00b008a13991c9b600d029e132916adc00b04aa139913f01]
Segmentation fault
! Unable to repack boot image!
! Installation failed

```

Update: 
original files from the firmware: 
http://s000.tinyupload.com/?del_id=49989507021221193223
or
[boot.img.zip](https://github.com/topjohnwu/Magisk/files/4564068/boot.img.zip)

**Comment by osm0sis** [comment]
Looks fun. Upload the boot.img please.

**Comment by Displax** [comment]
@osm0sis 
Yep, I also came across this strange thing.
Similar boot.img.lz4 from another samsung ROM: [boot.zip](https://github.com/topjohnwu/Magisk/files/4563294/boot.zip)

**Comment by ahronshor** [comment]
I previously managed get root on this device with version 20.3,
But there is a problem with mobile data that constantly turns on and off and fails to work at all.

**Comment by Xmaster111** [comment]
> Looks fun. Upload the boot.img please.
> 
> Odds are you just need to decompress it first, but I'll confirm.

Here the original file from firmware: http://s000.tinyupload.com/?del_id=49989507021221193223

**Comment by osm0sis** [comment]
@Displax thanks! Yep, just needs to be decompressed first.

@Xmaster111 your link doesn't work, but see above, it's an archive. Basically, you wouldn't try to patch boot.img.zip and expect it to work, so this is user error and I'll close it.

Get the lz4 plugin or fork for 7zip to easily unpack, or get the lz4 command-line tool and do `lz4 boot.img.lz4` and it'll unpack it for you, and then you can try patching it again, which will work. :+1:

**Comment by hassaneinazawi** [comment]
Root Galaxy A30s

**Comment by hassaneinazawi** [comment]
Root
