### ISSUE TITLE
[Feature] Core Only mode without TWRP, ADB and without Core only images

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#2756]
An idea - why Magisk Manager could not write its info about the installed modules and/or requested Core Only mode to its folder /data/data/com.topjohnwu.magisk (or the corresponding obfuscated name in case of repackaged Manager) - it doesn't need root to access this private app Data folder

Then, in case of bootloops due to eg bad modules there would be no need for TWRP, adb shell magisk command or Core Only patched images

Simply, you would flash stock image to boot without Magisk, but open Magisk Manager and flag that you want (next time) Core Only mode or certain modules to be disabled or removed.
Then flash your normal Magisk patched image (not the Core Only one), Magisk will find the requested flags from /data/data/com.topjohnwu.magisk and it will reboot to the requested Core Only mode, or it will disable or remove particular module(s)

That can also work in case of repackaged Manager - Magisk will first find from magisk.db at /data/adb the obfuscated package name (as it already does) and it will read then those flags from that obfuscated folder name under /data/data/

Since the other data (db, modules, etc) will be still kept in /data/adb, they will still be preserved in case of uninstalling Magisk Manager or deleting its Data (as of now)

For backward compatibility Magisk can continue to support old flags like "disable" also in /data/adb/modules/* and ".disable_magisk" in /cache

**Comment by linuxandria** [comment]
Because modules shouldn't cease to exist of manager is uninstalled.

In addition /data/adb was chosen as it's normally present, and permissions and selinux restrictions basically means nothing besides magisk can write to it (to prevent magisk detection)

**Comment by zgfg** [comment]
But in that case, when bootloop happens - some people have no choice or it is to complicated for them to get out:

- TWRP (supporting encrypted storages) does not exist for all devices

- adb wait-for-device shell magisk --remove-modules also does not work for all devices
(eg, my Huawei P9, MIUI 8 and it never did since the feature was introduced to Magisk - althogh I know how to use it since it works with no problem on my Xiaomi Mi 9T)

And making his own Core Only image is by no means a task for every user (and cannot be accomplished quickly when people have bootlooops)

Ofc, one could flash stock boot/ramdisk/recovery, but then he boots without root and as that Magisk Manager does not allow removing/disabling bad modules.
So no help - whenever he flashes 
the patched image back - he will have bootloop again

Only Factory reset remains for such user

That's why this idea to change/improve things

**Comment by linuxandria** [comment]
> But in that case, when bootloop happens - some people have no choice or it is to complicated for them to get out:
> 
> - TWRP (supporting encrypted storages) does not exist for all devices
> 
> - adb wait-for-device shell magisk --remove-modules also does not work for all devices
> (eg, my Huawei P9, MIUI 8 and it never did since the feature was introduced to Magisk - althogh I know how to use it since it works with no problem on my Xiaomi Mi 9T)
> 
> And making his own Core Only image is by no means a task for every user (and cannot be accomplished quickly when people have bootlooops)
> 
> Ofc, one could flash stock boot/ramdisk/recovery, but then he boots without root and as that Magisk Manager does not allow removing/disabling bad modules.
> So no help - whenever he flashes 
> the patched image back - he will have bootloop again
> 
> Only Factory reset remains for such user
> 
> That's why this idea to change/improve things 

Once again that could easily result in accidentally removing modules and a method for detection magisk.

My vote is for a hardware key combination, as that would be more universal.

@topjohnwu also had a good suggestion of implementation of a boot loop/boot failure detector and automatically kicking into core only mode as necessary.

**Comment by zgfg** [comment]
Sorry but what does it mean it would lead to uninstall (I always prefer first to disable) wrong module?
It's the user who can in the firs place install the wrong module (causing the bootloop).
And it's the user who must decide which module to disable (or uninstall) in case of a bootlopp

Even if you enter the Core Only mode by hardware key combo, you must also have a way to mark which modules to disable or uninstall - hence user can again mark the 'wrong' module

Btw, currently if you enter the Core Only mode you even don't see any modules, and you can only disable (or uninstall) them manually by going with a root explorer to /data/adb/modules which is even more prone to the user errors

PS: There is also another proposal #2131 for entering to the Core Only mode in case of bootloop, but that method (based on XDA guides) does not work for all devices as commented there

**Comment by linuxandria** [comment]
> Sorry but what does it mean it would lead to uninstall - I always prefer first to disable - the (wrong) module?
> It's the user who can in the first place install the wrong module (causing the bootloop).
> And it's the user who must decide which module to disable (or uninstall) in case of a bootloop to test if it helps
> 
> (Usually the easiest way to start would always be to disable the last module that was just installed - because before that, it should have had been working.
> And to reboot and test if it helped to fix the bootloop.
> If it does - only then uninstall that module.
> If not - reenable that module and try with another)
> 
> But currently if you enter the Safe mode you even don't see any modules, and you can only disable (or uninstall) them manually by going with a root explorer to /data/adb/modules which is even more prone to the user errors (and most users are not familiar with)
> 
> Hence the useful solution for the Safe mode which will help to user to fix the bootloops caused by modules would be:
> - a full proof way to enter the Safe mode (could be by hardware keys)
> - once in Safe mode, user must have control which modules are installed, to select which one to disable (or even uninstall)
> 
> Currently lot of users (per XDA threads and comments) end up by Factory resetting to clean up and start with installing Magisk and modules all over
> 
> PS: There is also another proposal #2131 for entering to the Safe mode  but that method (based on XDA guides) does not work for all devices as commented there

Because on app uninstall or app data clear every single module would disappear. Some "cleaning" apps could delete your modules and some of these apps come baked in OEM ROMs.

In addition selinux restrictions may prevent eg substratum from creating it's module in another apps data directory.

Your original suggestion was to put modules in manager's app data directory.

**Comment by zgfg** [comment]
Thinking twice, there are not so many hardware key combinations (with Vol+, Vol- and Pow buttons), and the combination must not be in collision with any of the combination (they may very from device to device) for Fastboot, Recovery, Downlink, System Safe mode, etc

Moreover, there are newest devices with no hardware Vol buttons

So I don't see that hardware key combination is a viable method to force Safe mode for Magisk

**Comment by zgfg** [comment]
> Because on app uninstall or app data clear every single module would disappear. Some "cleaning" apps could delete your modules and some of these apps come baked in OEM ROMs.
> 
> In addition selinux restrictions may prevent eg substratum from creating it's module in another apps data directory.
> 
> Your original suggestion was to put modules in manager's app data directory.

Only the flag (currently ".disable_magisk" in /cache)
to boot next time to Safe mode should go to Manager's private folder

Magisk db and modules stay at /data/adb

If you have a bootloop you flash stock image and reboot.
You are now without root but you can still open Manager and check that you want the safe mode.
So it leaves flag in its private data folder.

You flash again root image patched by Magisk and reboot.
While booting, Magisk finds the flag and goes to Safe mode.
Although modules are not running, nothing prevents Manager to read from /data/adb/modules which modules were installed so far.
Hence you can go through them and mark which of them you want to disable (or remove) next time

Therefore, uninstalling (or cleaning Data) for Manager app does not affect modules and Magisk db - just as it all works as of now

**Comment by linuxandria** [comment]
> > Because on app uninstall or app data clear every single module would disappear. Some "cleaning" apps could delete your modules and some of these apps come baked in OEM ROMs.
> > 
> > In addition selinux restrictions may prevent eg substratum from creating it's module in another apps data directory.
> > 
> > Your original suggestion was to put modules in manager's app data directory.
> 
> Only the flag (currently ".disable_magisk" in /cache)
> to boot next time to Safe mode should go to Manager's private folder
> 
> Magisk db and modules stay at /data/adb
> 
> If you have a bootloop you flash stock image and reboot.
> You are now without root but you can still open Manager and check that you want the safe mode.
> So it leaves flag in its private data folder.
> 
> You flash again root image patched by Magisk and reboot.
> While booting, Magisk finds the flag and goes to Safe mode.
> Although modules are not running, nothing prevents Manager to read from /data/adb/modules which modules were installed so far.
> Hence you can go through them and mark which of them you want to disable (or remove) next time
> 
> Therefore, uninstalling (or cleaning Data) for Manager app does not affect modules and Magisk db - just as it all works as of now
> 
> 

That would work fine.... Provided you are decrypted and have a manager installed.

**Comment by zgfg** [comment]
> That would work fine.... Provided you are decrypted and have a manager installed

There is no need for decrypted storage (just as Magisk and Magisk Manager already do not require decrypted storage).
When you boot with root, Manager has access to /data/adb as it does now.
When booting with no root, it has access to its private Data as any other app

Decrypted storage is only needed for  TWRP , those devices that have TWRP but TWRP does not support to ask for Android's display unlock pin to use it to get access to the encrypted file system

Or for custom ROMs who also don't support encryption

But Magisk and Manager have nothing with encryption. They have access to the file system through Android, like all other apps and Android cares itself for encryption

Also, if you got bootloop with Magisk module(s), it means that Magisk and Manager were installed.
You flash stock image, it only removes Magisk but Manager app is still installed.

**Comment by topjohnwu** [comment]
a5d7c41d209527fe7b45a2ef7d031add9b6fad24
