### ISSUE TITLE
SM-A307FN mobile networks issue (MM267)

### ISSUE THREAD

**Issue by Xmaster111** [topjohnwu/Magisk#2759]
Data:
A30s, SM-A307FN, **A307FNXXU2BTD1 (Android 10)**
Magisk 20.4 (20400)
Magisk Manager 7.5.1 (267)
***
Flash boot.ini via ODIN (Boot.ini) on stock firmware (A307FNXXU2ATB1_A307FNOEM2ASL3_ITV)
[boot.zip](https://github.com/topjohnwu/Magisk/files/4567202/boot.zip) 

[Original boot.ini from Firmware.zip](https://github.com/topjohnwu/Magisk/files/4568196/Original.boot.ini.from.Firmware.zip)

• Does not recognize the sim-card
• I cannot access the "Mobile networks" settings
• I noticed a general slowdown of the phone (as if it were overloaded with processes or with full memory)
***
![A30s_002](https://user-images.githubusercontent.com/47426810/80857850-9483dd00-8c55-11ea-9628-bef25e24cbf0.jpg)
![A30s_001](https://user-images.githubusercontent.com/47426810/80857877-cbf28980-8c55-11ea-939d-ef48b8a52b79.jpg)

***

What information can I provide to help me focus on the problem?
***
--------- beginning of main
--------- beginning of system
05-01 21:34:50.272  3862  3862 I Magisk  : Magisk 20.4(20400) daemon started
05-01 21:34:50.272  3862  3862 I Magisk  : * Device API level: 28
05-01 21:34:50.302  3862  3863 I Magisk  : ** post-fs-data mode running
05-01 21:34:50.304  3862  3863 I Magisk  : * Initializing Magisk environment
05-01 21:34:50.322  3862  3863 I Magisk  : * Mounting mirrors
05-01 21:34:50.323  3862  3863 I Magisk  : mount: /sbin/.magisk/mirror/product
05-01 21:34:50.323  3862  3863 I Magisk  : mount: /sbin/.magisk/mirror/vendor
05-01 21:34:50.323  3862  3863 I Magisk  : mount: /sbin/.magisk/mirror/data
05-01 21:34:50.323  3862  3863 I Magisk  : link: /sbin/.magisk/mirror/system
05-01 21:34:50.326  3862  3863 I Magisk  : * Setting up internal busybox
05-01 21:34:50.344  3862  3863 I Magisk  : * Running post-fs-data.d scripts
05-01 21:34:50.347  3862  3863 I Magisk  : * Running module post-fs-data scripts
05-01 21:34:50.347  3862  3863 I Magisk  : * Loading modules
05-01 21:34:50.357  3862  3870 I Magisk  : * Starting MagiskHide
05-01 21:34:50.357  3862  3870 I Magisk  : hide_policy: Hiding sensitive props
05-01 21:34:50.358  3862  3870 I Magisk  : hide_list init: [com.google.android.gms/com.google.android.gms.unstable]
05-01 21:34:50.363  3862  3870 I Magisk  : hide_list init: [org.microg.gms.droidguard/com.google.android.gms.unstable]
05-01 23:34:51.416  3862  4018 I Magisk  : ** late_start service mode running
05-01 23:34:51.416  3862  4018 I Magisk  : * Running service.d scripts
05-01 23:34:51.432  3862  4018 I Magisk  : * Running module service scripts
05-01 23:35:08.115  3862  5451 I Magisk  : ** boot_complete triggered
05-01 23:35:50.265  3862  3870 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[9450] UID=[10036]
05-01 23:36:36.603  3862  3870 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[12360] UID=[10036]
--------- beginning of crash
05-01 23:38:02.396  3862  3870 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[17086] UID=[10036]

***
thanks for the help in the previous discussion, I was able to advance to the boot as a result of your help

**Comment by JARVIS-AI** [comment]
Is it default custome ROM ?
Can you provide the log ?

**Comment by Xmaster111** [comment]
stock rom, Sir.

**Comment by sabpprook** [comment]
Try Android 10 firmware.

**Comment by Xmaster111** [comment]
> Try Android 10 firmware.

117/5000
I believe that there is no firmware with Android 10 for Mi 9T Global
http://c.mi.com/oc/miuidownload/detail?device=1700361
I'm wrong?

**Comment by sabpprook** [comment]
> > Try Android 10 firmware.
> 
> I believe that there is no firmware with Android 10 for Mi 9T Global
> http://c.mi.com/oc/miuidownload/detail?device=1700361
> I'm wrong?

Didn't we talking about Samsung SM-A307FN on firmware A307FNXXU2ATB1?

**Comment by abdmeh11** [comment]
Make magisk patched firmware and rename recovery.img to boot.img and compressed it with 7-zip to tar and flash if it's not work with u text me on my phone no to find a solution on telegram  +962787575320

**Comment by Xmaster111** [comment]
> > > Try Android 10 firmware.
> > 
> > 
> > I believe that there is no firmware with Android 10 for Mi 9T Global
> > http://c.mi.com/oc/miuidownload/detail?device=1700361
> > I'm wrong?
> 
> Didn't we talking about Samsung SM-A307FN on firmware A307FNXXU2ATB1?

A307FNXXU2ATB1 has Android 9
A307FNXXU2BTD1 has Android 10 ( 27-04-2020)

Now I format the phone, I flash the new firmware (A307FNXXU2BTD1) that has Android 10, then I try again to root with Magisk and see what happens. Before trying other solutions.
Do you all agree?

P.S. I was not aware of the new firmware for the A30s, thanks for the tip

**Comment by sabpprook** [comment]
> > > > Try Android 10 firmware.
> > > 
> > > 
> > > I believe that there is no firmware with Android 10 for Mi 9T Global
> > > http://c.mi.com/oc/miuidownload/detail?device=1700361
> > > I'm wrong?
> > 
> > 
> > Didn't we talking about Samsung SM-A307FN on firmware A307FNXXU2ATB1?
> 
> A307FNXXU2ATB1 has Android 9
> A307FNXXU2BTD1 has Android 10 (27-04-2020)
> 
> Now I format the phone, I flash the new firmware (A307FNXXU2BTD1) that has Android 10, then I try again to root with Magisk and see what happens. Before trying other solutions.
> Do you all agree?
> 
> P.S. I was not aware of the new firmware for the A30s, thanks for the tip, thank you

Yes, upgrade to A307FNXXU2BTD1 will fix this issue.

**Comment by Xmaster111** [comment]
Ok, the connection problem is fixed just like you said, but there is another problem:
if I use the root to uninstall apps included in the firmware,  the phone enters the bootloop on Download... and no way to load Android

**Comment by topjohnwu** [comment]
That is unrelated to Magisk. You should be aware that devices are more and more unforgiving when you directly modify system apps. Tons of root apps that "remove system apps" is outdated and will brick your device, as you personally experienced
