### ISSUE TITLE
Magisk 13.1 doesn't work on Wileyfox Swift COS13

### ISSUE THREAD

**Issue by aacprime** [topjohnwu/Magisk#276]
Everything worked perfectly when I had magisk 12 installed on my smartphone (wileyfox swift COS13). No problems at all, working root and safetynet passed.
Then magisk prompted to upgrade to 13.1, which I did. After rebooting I lost root access. Magisk manager (which was still of version 4) was showing me that magisk isn't installed. Then I've installed magisk manager 5.0.4 and it just crashed every time I've tried to launch it.
After that I did full wipe via twrp and flashed fresh new firmware (COS13 once again) + magisk 13.1 afterwards. Magisk manager wasn't in apps list, so I had to download it from xda and install it by myself. And then it crashed after launching again.
Here is stock boot image: https://drive.google.com/open?id=0BysY8u1gxamNYkZWRER1aWNyT28

**Comment by JERW86** [comment]
Have you tried clearing the app's data? A logcat of the Magisk Manager crash will be helpful.

**Comment by aacprime** [comment]
Clearing the app's data wouldn't help especially after wiping and flashing new firmware.
Here is logcat of starting system and launching magisk manager [1.txt](https://github.com/topjohnwu/Magisk/files/1141782/1.txt)
