### ISSUE TITLE
a51 root init need.

### ISSUE THREAD

**Issue by seci20** [topjohnwu/Magisk#2762]
Eft dongle wrote new init. Magisk source codes appear in the init file.

boot repack and unpack processes.

https://forum.xda-developers.com/showthread.php?t=2073775

When we install magiskinit, the device becomes bootloop. Which areas do we need to organize ?

**Comment by map220v** [comment]
@seci20 Magiskinit on A51 Works fine.
Magisk on A51 not working because magisk --post-fs-data causes Kernel Panic

**Comment by seci20** [comment]
> @seci20 Magiskinit on A51 Works fine.
> Magisk on A51 not working because magisk --post-fs-data causes Kernel Panic

What do I need to fix in init.cpp?

**Comment by map220v** [comment]
@seci20 you need to delete from magiskrc.inc "magisk --post-fs-data" part.
But with this changes Magisk Modules won't work. Only su will work.

**Comment by seci20** [comment]
> @seci20 you need to delete from magiskrc.inc "magisk --post-fs-data" part.
> But with this changes Magisk Modules won't work. Only su will work.

Need just su bro. Thanks. Do you have a chance to send a sample file?

**Comment by map220v** [comment]
This file?
[magiskrc.inc.txt](https://github.com/topjohnwu/Magisk/files/4582844/magiskrc.inc.txt)

**Comment by seci20** [comment]
is not it right ?

#include <magisk.hpp>
#include <selinux.hpp>

constexpr char MAGISK_RC[] =
"\n"

"on post-fs-data\n"
"    start logd\n"
"    rm " UNBLOCKFILE "\n"
"    start %2$s\n"
"    wait " UNBLOCKFILE " 10\n"
"    rm " UNBLOCKFILE "\n"
"\n"

"service %3$s %1$s/magisk --service\n"
"    class late_start\n"
"    user root\n"
"    seclabel u:r:" SEPOL_PROC_DOMAIN ":s0\n"
"    oneshot\n"
"\n"

"on property:sys.boot_completed=1\n"
"    start %4$s\n"
"\n"

"service %4$s %1$s/magisk --boot-complete\n"
"    user root\n"
"    seclabel u:r:" SEPOL_PROC_DOMAIN ":s0\n"
"    oneshot\n"
"\n"
;

**Comment by map220v** [comment]
This file correct.

**Comment by seci20** [comment]
but still throws reboot at boot.

**Comment by map220v** [comment]
Try this boot.img i patched it
https://drive.google.com/file/d/1yEQjbhF4WgH_7ueYfliNCC3mjhf_Uqid/view?usp=sharing

**Comment by seci20** [comment]
> Try this boot.img i patched it
> https://drive.google.com/file/d/1yEQjbhF4WgH_7ueYfliNCC3mjhf_Uqid/view?usp=sharing

I want to get root permission with stock boot.img.When I do with eftinit, there is no problem. The device gets bootloop when I use magiskinit

**Comment by seci20** [comment]
> Try this boot.img i patched it
> https://drive.google.com/file/d/1yEQjbhF4WgH_7ueYfliNCC3mjhf_Uqid/view?usp=sharing

have you played in another source file ?

**Comment by seci20** [comment]
> Try this boot.img i patched it
> https://drive.google.com/file/d/1yEQjbhF4WgH_7ueYfliNCC3mjhf_Uqid/view?usp=sharing

Have you edited another source file ?

**Comment by map220v** [comment]
I Deleted magisk --post-fs-data it's works for me.

**Comment by seci20** [comment]
> I Deleted magisk --post-fs-data it's works for me.

I delete it in the same way, but the device is bootloop. The problem disappears when I install eftinit :(

**Comment by map220v** [comment]
@seci20 I Patched it again https://drive.google.com/open?id=1AvtwteSobCJrp6bhp2osfTYKIu1vxPDh
try also Factory reset in recovery after installing it.

**Comment by seci20** [comment]
> @seci20 I Patched it again https://drive.google.com/open?id=1AvtwteSobCJrp6bhp2osfTYKIu1vxPDh
> try also Factory reset in recovery after installing it.

yes the boot.img you provided is working. Init, which I made and added, doesn't work.

can you patch it ? I want to make sure of the problem.

https://drive.google.com/open?id=1EdzLLVtdHUpK7dI0ZT0iqqYOOdNIji4H

**Comment by seci20** [comment]
> @seci20 I Patched it again https://drive.google.com/open?id=1AvtwteSobCJrp6bhp2osfTYKIu1vxPDh
> try also Factory reset in recovery after installing it.

The problem is solved when I do with your init file right now. can you please send me the source code.

**Comment by map220v** [comment]
@seci20 https://github.com/map220v/Magisk

**Comment by seci20** [comment]
> @seci20 https://github.com/map220v/Magisk

Thanks <3

**Comment by abdmeh11** [comment]
Any one can patch boot for m315f thanks

**Comment by abdmeh11** [comment]
@seci20

**Comment by bagbyte** [comment]
@seci20 how did you solve it?

Currently, my situation is the following:

- if I patch only boot.img it goes in bootloop
- if I patch the whole AP (or just boot.img + vbmeta.img + recovery.img) the phone goes in download mode with a red error complaining about vbmeta
- if I use the patched boot.img provided by @map220v, the phone is rooted but whatever module I try to install, even tho the installation succeeds (no errors/warnings in the installation log), the module is not installed (even if the module folder is present in `/data/adb` folder)

I have a SM-A515F DBT, it hasn't the UI 2.1 update yet, can this be the issue? I read something about binary 3, but not sure how to understand if my version is binary 3 or not.

@map220v do you think if you provide the 3 files (boot.img + vbmeta.img + recovery.img) patched on your device, will it work on mine? would it solve the Magisk modules installation issue?

**Comment by map220v** [comment]
@bagbyte Magisk works only on Binary 3
A515FXX**U3**BTD4
It's Binary 3 Firmware.
After Updating Phone just patch boot.img from AP-A515FXXU3BTD4 and flash.

**Comment by islamadel99** [comment]
wow @bagbyte but i want tell you i used magisk on j730f u4 before and the root very good with me but why it not working with u3 binary on A51 or the root working only for limite binary
