### ISSUE TITLE
Magisk not working 20408 (modules section not clickable) 

### ISSUE THREAD

**Issue by usamaiqbal1177** [topjohnwu/Magisk#2763]
Device is poco F1. It's showing no log in magisk manager but I have saved matlog. Modules and safety... The tool section and module section is unclickable. 
[logs-2020-04-09-17-21-57.zip](https://github.com/topjohnwu/Magisk/files/4581891/logs-2020-04-09-17-21-57.zip)
![Screenshot_20200505-202704851](https://user-images.githubusercontent.com/58624914/81085500-bb216c80-8f10-11ea-9cbb-c9f2319b28c5.jpg)

**Comment by osm0sis** [comment]
Flash again over untouched boot.img

**Comment by usamaiqbal1177** [comment]
> Flash again over untouched boot.img

Thanks, but I tried that multiple times. Cause this used to happen in previous version before and flashing over untouched boot.img fixed it but now it doesn't....

**Comment by Didgeridoohan** [comment]
@usamaiqbal1177 I just want to point out that the screenshot you've provided shows that Magisk isn't installed. You might want to try again...

**Comment by usamaiqbal1177** [comment]
> Flash again over untouched boot.img

Thanks, bruh. I flashed stock boot img and then flash 20408 and then it worked... This time it didn't work with dirty flashing as it always used to... Thanks a lot @osm0sis

**Comment by osm0sis** [comment]
Yep, not sure if you were using a custom kernel, but basically anything in /overlay.d/sbin will result in the above issue. overlay.d has been broken since 20402, and this was thought fixed for 20408 but obviously not. I've made @topjohnwu aware. :+1:
