### ISSUE TITLE
issue with new magisk canary update 87de0e7a (20408) Android Q/S20+

### ISSUE THREAD

**Issue by personaingrata** [topjohnwu/Magisk#2764]
i updated magisk through the manager today, update went fine but after reboot MM 284 is not detecting magisk and prompt to install magisk. no root detected, no modules shown in magisk. so i patched a virgin boot.img with MM, flashed through odin, same result, magisk not detected. flushed all magisk modules via adb, reboot and magisk root is detected again. downloaded and installed busybox, reboot. magisk gone, flushed again modules via adb, reboot, magisk there. enabled systemless hosts in MM and magisk fails again after reboot. downgraded back to 20407 with previously patched boot.img and everything is working again.

sorry for not providing a logcat, phone is a Galaxy S20+ sm-g986b on latest ATD5 fw, android Q

**Comment by topjohnwu** [comment]
Apparently root works fine, it only breaks when you attempt to install modules. Without any logs, I cannot help you
