### ISSUE TITLE
[BUG] Stub randomly needs to upgrade to full manager

### ISSUE THREAD

**Issue by linuxandria** [topjohnwu/Magisk#2766]
With absolutely no pattern to it, randomly my hidden manager decides it needs to needs to redownload the full version. This is _especially_ annoying as GitHub is going 100K/s for me recently.

App data shouldn't be getting cleaned. I definitely don't touch it and I don't use any shady "junk cleaners".

Device: OnePlus 7T
Android: 10
Manager: 284 (9) [hidden]

If any logs would be helpful please specify which.

**Comment by osm0sis** [comment]
Are you on stock ROM? If so I have this exact device and setup and no such issue. 🤔

**Comment by linuxandria** [comment]
@osm0sis happens across ROMs for me, idr if on OOS

Anyhow I can't test as I'm stuck on a device with no fastboot implementation rn (yikes!)

_Sent from my VIEW 1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
