### ISSUE TITLE
mv fails when installing module in Manager

### ISSUE THREAD

**Issue by Chariblaze** [topjohnwu/Magisk#2769]
I encountered this when installing the [Xposed module](https://github.com/Magisk-Modules-Repo/xposed) in Magisk 20.4. [Moving XposedBridge.jar fails](https://github.com/Magisk-Modules-Repo/xposed/blob/master/install.sh#L142), though in the next line copying the rest of the files works fine.

[dmesg-magisk-mv-fail.txt](https://github.com/topjohnwu/Magisk/files/4589045/dmesg-magisk-mv-fail.txt) -- dmesg from after installing the module with the May 5 Canary (iirc). The error shows up on line 1173:

`[   93.751892] type=1400 audit(1588790950.447:112): avc: denied { associate } for pid=3144 comm="exe" name="XposedBridge.jar" scontext=u:object_r:device:s0 tcontext=u:object_r:labeledfs:s0 tclass=filesystem permissive=0`

20.3 -- mv works
[Canary b39f4075/20302 from Jan 10](https://github.com/topjohnwu/magisk_files/tree/e463926c39f2c0a4b69e74e39d0bf45748ee1f4e) -- mv works
[The next Canary, 0dc9f5c3/20303 from Jan 22](https://github.com/topjohnwu/magisk_files/tree/93f63beb9426a131141a29d66fd124dbd2a9a41c) -- mv broken
20.4 -- mv broken
[Canary 87de0e7a/20408 from May 5](https://github.com/topjohnwu/magisk_files/tree/a980c6ab309ff668f0ca9b7b6dca5a3e88f13f92) -- mv broken

OS was Marshmallow 6.0.1. Tested them with Manager v7.5.1 and Canary 284, the version didn't seem to matter.

When flashing the module from recovery in all tested versions, mv works fine and the JAR is moved.

Edit: [MagiskFrida has a mv, it works fine](https://github.com/Magisk-Modules-Repo/magisk-frida/blob/master/install.sh#L152) -- sorry, I should have tested more modules first.

**Comment by linuxandria** [comment]
SEPolicy issue looks like.

I'm not sure John is willing to update the Xposed module as it says it won't receive any more updates, so you may be on your own to create the appropriate SEPolicy.
