### ISSUE TITLE
Magisk canary 20409 shows as not installed 

### ISSUE THREAD

**Issue by DanGLES3** [topjohnwu/Magisk#2774]
Whenever i install 20409 i lose root and the manager shows magisk as not being installed, oddly modules are still mounted correctly, Magisk Manager doesn't show any logs, so if there's any other way to get Magisk logs please let me know 

Device: Moto G 2015
Rom:AOSPA Quartz (Android 10)

**Comment by linuxandria** [comment]
Tried clean install?

**Comment by DanGLES3** [comment]
yes, still doesn't work

**Comment by DanGLES3** [comment]
even after restoring the stock boot image and installing magisk on it, Magisk still shows as not installed

**Comment by awbruce** [comment]
I'm having same issue on my Pixel 3 XL with stock Android 11 DP4.

I can see that this has been closed. Does it mean it's been fixed?

**Comment by linuxandria** [comment]
> I'm having same issue on my Pixel 3 XL with stock Android 11 DP4.
> 
> I can see that this has been closed. Does it mean it's been fixed? 

See #2779
