### ISSUE TITLE
Fails to boot on Pixel 2 with stock Android 10 (2020.05)

### ISSUE THREAD

**Issue by lazywebm** [topjohnwu/Magisk#2775]
Hi there,

first of all, thank you for providing us with some great pieces of software. I've been using Magisk + Magisk Manager for years on a Pixel 2, so far without issues up until Android stock 2020.05.
I do the monthly stock android updates for my phone by manually flashing the corresponding (walleye) image (fastboot update image-walleye..). Sadly this it won't seem to work with the latest may update, after doing "fastboot flash boot magisk_patched.img" Android seems to be stuck on the loading screen (small loading bar after the google animation). I've tried the older TWRP sideload method as well, same result. I've tried patching the image with canary as well as stable. 
Not using any additional Magisk modules. 
My phone is now running the unrooted may update. Any advice or things I might have overlooked?

Thanks!

**Comment by Andrew-M3373** [comment]
> Hi there,
> 
> first of all, thank you for providing us with some great pieces of software. I've been using Magisk + Magisk Manager for years on a Pixel 2, so far without issues up until Android stock 2020.05.
> I do the monthly stock android updates for my phone by manually flashing the corresponding (walleye) image (fastboot update image-walleye..). Sadly this it won't seem to work with the latest may update, after doing "fastboot flash boot magisk_patched.img" Android seems to be stuck on the loading screen (small loading bar after the google animation). I've tried the older TWRP sideload method as well, same result. I've tried patching the image with canary as well as stable.
> Not using any additional Magisk modules.
> My phone is now running the unrooted may update. Any advice or things I might have overlooked?
> 
> Thanks!

I have a pixel 2 (walleye) also, and flashing the Magisk image works just fine. I also do the OTA updates over adb and am currently on 2020.05. Have you tried installing it by sideloading the installation zip in TWRP wit adb? This is what I have been doing for the past year. 

Let me know if this helps!

**Comment by lazywebm** [comment]
> 
> I have a pixel 2 (walleye) also, and flashing the Magisk image works just fine. I also do the OTA updates over adb and am currently on 2020.05. Have you tried installing Magisk by sideloading the installation zip in TWRP with adb? This is what I have been doing for the past year.
> 
> Let me know if this helps!

Thanks for your answer.
That's what I tried after my usual method, but with the factory image. Do you have an exact list of the things you're doing?

**Comment by lazywebm** [comment]
Andrew-M3373, thank you for sharing your detailed instructions! Made it work by sideloading TWRP and Magisk. Just a little funny since I haven't used TWRP for a year or so, but anyway, I'll be updating my documentation accordingly.
Thanks again and have a nice weekend.
