### ISSUE TITLE
Segfault in magiskpolicy prevents Magisk from booting

### ISSUE THREAD

**Issue by jenslody** [topjohnwu/Magisk#278]
already posted about that in xda-forum: https://forum.xda-developers.com/showpost.php?p=72993007&postcount=15721

In short:
Tested on Samsung J5 with latest stock MM.
While magiskpolicy tries to modify the extracted sepolicy it segfaults.
sepolicy stays unchanged, gets repacked and Magisk is not loaded at boot.
No root, no MagiskManager ...

I found where it segfaults:
it happens in type_set_expand() in expand.c from sepolicy.
If expand is not explicitely set the code tries to look whether the type has the new TYPE_FLAGS_EXPAND_ATTR_TRUE flag set.
The type is extracted from the policydb->type_val_to_struct array.
For some obscure reason it tries to extract from an invalid position, because p->p_types.nprim has a larger value, then on all (most) other places in the program and the type is read from the next memory-location after the array.
In my case it's always 13, so the simple check for null does not work and the program tries to read the flag from an invalid pointer.
This happens only, if the set should not explicitely be expanded.
A simple workaround is to ignore the new flag, but leave the rest of the code untouched.
Here comes a patch that does that:
```diff
@@ -2558,12 +2558,22 @@ int type_set_expand(type_set_t * set, ebitmap_t * t, policydb_t * p,
 
 		if (!type) {
 			goto err_types;
 		}
 
-		if (type->flavor == TYPE_ATTRIB &&
-		    (expand || (type->flags & TYPE_FLAGS_EXPAND_ATTR_TRUE))) {
+		/* Workaround for magiskpoliy crash
+		 * Ignore the new TYPE_FLAGS_EXPAND_ATTR_TRUE for now, it's not used anyway
+		 * and move the check for explicitely expanding as first, because type can be
+		 * invalid, but not null.
+		 * For some reason p->p_types.nprim can be larger than the actual initialized
+		 * memorypool for p->type_val_to_struct allows.
+		 * I try to investigate further.
+		 * jenslody (07-11-2017)
+		 */
+/*		if (type->flavor == TYPE_ATTRIB &&
+		    (expand || (type->flags & TYPE_FLAGS_EXPAND_ATTR_TRUE))) { */
+		if (expand && type->flavor == TYPE_ATTRIB) {
 			if (ebitmap_union(&types, &type->types)) {
 				goto err_types;
 			}
 		} else {
 			if (ebitmap_set_bit(&types, i, 1)) {


```

**Comment by topjohnwu** [comment]
Wow, really great job!! Thank you very much!

**Comment by jenslody** [comment]
A little more investigating:
the only needed fix seems to be:
```diff
@@ -301,18 +301,10 @@ int create_domain(char *d) {
 	policydb->attr_type_map = realloc(policydb->attr_type_map, sizeof(ebitmap_t) * policydb->p_types.nprim);
 	ebitmap_init(&policydb->type_attr_map[value-1]);
 	ebitmap_init(&policydb->attr_type_map[value-1]);
 	ebitmap_set_bit(&policydb->type_attr_map[value-1], value-1, 1);
 
-	//Add the domain to all roles
-	for(unsigned i=0; i<policydb->p_roles.nprim; ++i) {
-		//Not sure all those three calls are needed
-		ebitmap_set_bit(&policydb->role_val_to_struct[i]->types.negset, value-1, 0);
-		ebitmap_set_bit(&policydb->role_val_to_struct[i]->types.types, value-1, 1);
-		type_set_expand(&policydb->role_val_to_struct[i]->types, &policydb->role_val_to_struct[i]->cache, policydb, 0);
-	}
-
 	src = hashtab_search(policydb->p_types.table, d);
 	if(!src)
 		return 1;
 
 	if(policydb_index_decls(NULL, policydb))
@@ -322,10 +314,18 @@ int create_domain(char *d) {
 		return 1;
 
 	if(policydb_index_others(NULL, policydb, 0))
 		return 1;
 
+	//Add the domain to all roles
+	for(unsigned i=0; i<policydb->p_roles.nprim; ++i) {
+		//Not sure all those three calls are needed
+		ebitmap_set_bit(&policydb->role_val_to_struct[i]->types.negset, value-1, 0);
+		ebitmap_set_bit(&policydb->role_val_to_struct[i]->types.types, value-1, 1);
+		type_set_expand(&policydb->role_val_to_struct[i]->types, &policydb->role_val_to_struct[i]->cache, policydb, 0);
+	}
+
 	return set_attr("domain", value);
 }
 
 int set_domain_state(char* s, int state) {
 	type_datum_t *type;

```
Before the call of policydb_index_others (at least) the type_val_to_struct array seems not to be correctly initialized (after inserting the new type_datum_t) and therefore type_set_expand can lead to a segfault.
