### ISSUE TITLE
Lost root on Pixel 3 XL Android 11 DP4

### ISSUE THREAD

**Issue by awbruce** [topjohnwu/Magisk#2780]
Pixel 3 XL on Android 11 DP4 lost root after updating to latest canery build:
Magisk :  a62bdc58 (20409)
Magisk manager :  87deDe7a (284) (9)
```

**Comment by laupuy** [comment]
Hi, seems like #2779 
did you reboot with magisk without issue before?

**Comment by awbruce** [comment]
Yeah, had permanent root on previous canary builds.
