### ISSUE TITLE
service.d script not run

### ISSUE THREAD

**Issue by meiser79** [topjohnwu/Magisk#2781]
Hi,

I'm running 20409 on my Xiaomi Mi 9 T Pro (crDroid 6.5).

I just saw that the service.d scripts are not run anymore. magisk.log shows:

> 05-09 10:51:59.241   713  1279 I Magisk  : ** late_start service mode running
05-09 10:52:00.663   713   722 D Magisk  : proc_monitor: ptrace zygote PID=[734]
05-09 10:52:00.663   713   722 D Magisk  : proc_monitor: ptrace zygote PID=[735]
05-09 10:52:07.782   713  2926 I Magisk  : ** boot_complete triggered

But there're 3 scripts in the folder.

BTW, post-fs-data.d scripts still run fine.

**Comment by topjohnwu** [comment]
Your scripts have executable permissions set?

**Comment by meiser79** [comment]
yes, they have permission 755.
I'd like to add that service.sh scripts in modules folder also don't run on boot.

**Comment by meiser79** [comment]
Why don't I see these LOGI entries in magisk.log?

        LOGI("* Running service.d scripts\n");
        exec_common_script("service");

        LOGI("* Running module service scripts\n");
        exec_module_script("service", module_list);


Where is pfs_done set to true? I can't find it in the code? Does it mean that pfs_done is still false and that's why the function returns?

**Comment by meiser79** [comment]
Reverting to canary 20407, and it works. So it's a regression introduced by "Support Safe Mode detection" commit.

> 05-09 13:37:50.303   710  1292 I Magisk  : ** late_start service mode running
> 05-09 13:37:50.303   710  1292 I Magisk  : * Running service.d scripts
> 05-09 13:37:50.304   710  1292 I Magisk  : service.d: exec [gpay.sh]
> 05-09 13:37:50.316   710  1292 I Magisk  : service.d: exec [net_unix.sh]
> 05-09 13:37:50.328   710  1292 I Magisk  : service.d: exec [props.sh]
> 05-09 13:37:50.343   710  1292 I Magisk  : * Running module service scripts
> 05-09 13:37:50.344   710  1292 I Magisk  : sshd: exec [service.sh]
> 05-09 13:37:51.745   710   719 D Magisk  : proc_monitor: ptrace zygote PID=[731]
> 05-09 13:37:51.745   710   719 D Magisk  : proc_monitor: ptrace zygote PID=[732]
>

**Comment by topjohnwu** [comment]
Fixed c6569ce022f178b8ba091c7e7e3f86609d451e67
