### ISSUE TITLE
vbmeta partition to be reflashed after ROM flash

### ISSUE THREAD

**Issue by meiser79** [topjohnwu/Magisk#2782]
Hi,

I'm running 20409 on my Xiaomi Mi 9 T Pro (crDroid 6.5).

After I flash a new crDroid ROM with Magisk addon.d script, I have to reflash the vbmeta partition so that the device boots (found out by try&error till I found the one partition).

IIRC, it started with version 20407, this was my first installed version after switching from v20.4. Please find attached the recovery log.

[recovery_log.zip](https://github.com/topjohnwu/Magisk/files/4603052/recovery_log.zip)

**Comment by luisbandalap** [comment]
Same issue here.

I'm on Xiaomi Mi 9T Pro (EvolutionX 4.3 Rom). It started around march for me, with latest release of magisk.

Flashing vbmeta fixes issue.

[logs.zip](https://github.com/topjohnwu/Magisk/files/4625825/logs.zip)

**Comment by meiser79** [comment]
Why was this issue report closed? It's still valid for me.

@luisbandalap What do you mean by "rooms"? How did you fix it exactly?

**Comment by luisbandalap** [comment]
@meiser79  my bad, i mean to say "rom". to fix it there are three ways:

1. Take a copy of vbmeta.img from your vendor zip and replace it in your crDroid's update zip.
2. Report this issue to Mi 9T's crDroid maintainer (vbmeta.img should not be flashed from rom zip if there is suport for multiple region's vendor).
3. Flash vendor .zip expected from crDroid (it could be europe or india).
