### ISSUE TITLE
MODPATH incorrect in customize.sh

### ISSUE THREAD

**Issue by TheDauntless** [topjohnwu/Magisk#2785]
I have a module that, on device boot, needs to copy files from one directory on the system to another system directory. I do this by overlaying a directory on /system and copying the files into my local directory so that they end up on /system.

I tried a few ways of doing this with the new module structure, but apparently it's no longer possible. I tried two things:

**1. Copy the files in service.sh**
Since $MODPATH is not available in service.sh or post-fs-data.sh anymore, I don't know the location of my plugin
2. **Set up service.sh through customize.sh**
customize.sh does have access to $MODPATH, but the $MODPATH there has `/data/adb/modules_update/mymodname` as value instead of `/data/adb/modules/mymodname`

Shouldn't those environment variables that are available in customize.sh just be made available in service.sh? (And shouldn't MODPATH be the correct value in customize.sh?)

Versions: 20400 and 7.5.1

**Comment by Didgeridoohan** [comment]
This is not a bug, it's a feature. Seriously.

That is the correct path when installing a module through the Manager (in other words, when using customize.sh). It's not a good idea to install over already mounted files (those in /data/adb/modules), so the modules_update directory is used and then it's merged with the regular directory when you reboot.

Nothing to see here, you can close the issue

**Comment by Didgeridoohan** [comment]
And oh yeah... $MODPATH can definitely be used in your boot scripts, as long as it's defined at the beginning of the file (like it's always been before).

**Comment by linuxandria** [comment]
> And oh yeah... $MODPATH can definitely be used in your boot scripts, as long as it's defined at the beginning of the file (like it's always been before).

(In boot scripts it's $MODDIR not $MODPATH but templwte script has it yes)

**Comment by linuxandria** [comment]
> This is not a bug, it's a feature. Seriously.
> 
> That is the correct path when installing a module through the Manager (in other words, when using customize.sh). It's not a good idea to install over already mounted files (those in /data/adb/modules), so the modules_update directory is used and then it's merged with the regular directory when you reboot.
> 
> Nothing to see here, you can close the issue 

Though I am curious if any issue has ever actually occured directly modifying a module file? Never had one here but my modules aren't especially complicated

**Comment by Didgeridoohan** [comment]
> > And oh yeah... $MODPATH can definitely be used in your boot scripts, as long as it's defined at the beginning of the file (like it's always been before).
> 
> (In boot scripts it's $MODDIR not $MODPATH but template script has it yes)

Ah, yes... Forgot about the difference in the variable name. Still, same result.

**Comment by Didgeridoohan** [comment]
> > This is not a bug, it's a feature. Seriously.
> > That is the correct path when installing a module through the Manager (in other words, when using customize.sh). It's not a good idea to install over already mounted files (those in /data/adb/modules), so the modules_update directory is used and then it's merged with the regular directory when you reboot.
> > Nothing to see here, you can close the issue
> 
> Though I am curious if any issue has ever actually occured directly modifying a module file? Never had one here but my modules aren't especially complicated

It has the potential to cause issues, so better to avoid those.

**Comment by TheDauntless** [comment]
> And oh yeah... $MODPATH can definitely be used in your boot scripts, as long as it's defined at the beginning of the file (like it's always been before).

The file that originally had the default MODPATH definition was removed, and since I saws the MODPATH variable, I assumed this was the new way to do it.

But you are correct, the guide actually does mention to create the MODDIR yourself, so it is indeed not a bug.

Thanks for the input.
