### ISSUE TITLE
Latest Canary is loading all modules (including disabled)

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#2786]
Zenfone 4 with Android Pie.
[magisk_log_20200509_114233.log](https://github.com/topjohnwu/Magisk/files/4603794/magisk_log_20200509_114233.log)
[bootlog.txt](https://github.com/topjohnwu/Magisk/files/4603772/bootlog.txt)

![Screenshot_20200509-114334500](https://user-images.githubusercontent.com/17092335/81476921-11c9c780-91eb-11ea-8cad-ad5cd058f838.jpg)
![Screenshot_20200509-114611638](https://user-images.githubusercontent.com/17092335/81476935-1ee6b680-91eb-11ea-97f1-c2b48802775d.jpg)

**Comment by KaMyKaSii** [comment]
I put Magisk in safe mode and still all modules continue to be loaded
[magisk.txt](https://github.com/topjohnwu/Magisk/files/4607208/magisk.txt)
[liveboot.txt](https://github.com/topjohnwu/Magisk/files/4607210/liveboot.txt)

**Comment by topjohnwu** [comment]
aac6ad73dad8fc5fb97e920df8ee2a3a952020b9
