### ISSUE TITLE
Bug causing borked volume and messenger app

### ISSUE THREAD

**Issue by MixedMotives** [topjohnwu/Magisk#2788]
20409  causes messaging app freezing and volume will not go all the way down. 20400 doesn't cause this 

On OnePlus 7t

**Comment by linuxandria** [comment]
Has to be a you issue, I can't reproduce on my 7T

**Comment by MixedMotives** [comment]
It doesn't occur on 20400, after downgrade it's fine

**Comment by MixedMotives** [comment]
[magisk_log_20200509_111424.log](https://github.com/topjohnwu/Magisk/files/4604266/magisk_log_20200509_111424.log)

**Comment by MixedMotives** [comment]
the log
[magisk_log_20200509_112542.log](https://github.com/topjohnwu/Magisk/files/4604269/magisk_log_20200509_112542.log)
 after downgrade running 20400 no issue

**Comment by osm0sis** [comment]
My 7T is also completely fine. Most likely you've got some crazy module you need to uninstall.
