### ISSUE TITLE
Magisk automatically revert back to latest canary even after downgrading

### ISSUE THREAD

**Issue by JakunGamer** [topjohnwu/Magisk#2789]
So I've been used Magisk Canary 20401 for a while now. When there's 20409, I've updated it and things work fine. But my installed audio mod doesn't work anymore ( guitardedhero's Dolby Atmos Pie/Q port ). That's why I reverted back to v20401. But for some weird reason, at first it displayed correctly as v20401 but then somehow it changed back to v20409, making my audio mod stopped working. Try reinstall the recovery boot img that contain v20401 but no luck. Even tried to flash the v20.4 Stable zip but the same things happened. Why is that happening? How to fix it?

**Comment by osm0sis** [comment]
Sorry, but support/debugging can only be given for the latest Canary.. If there's an issue with a module please inform the module dev.
