### ISSUE TITLE
Stuck on MI Boot Logo

### ISSUE THREAD

**Issue by DzikrRully** [topjohnwu/Magisk#279]
Help me please, when install Magisk 13.1 on my phone from recovery and I get success notify. But after reboot to system my phone stuck on boot logo.

Phone : XiaoMi RedMi 4 Prime (Unlocked)
ROM : MIUI Global Stable 8.2.4.0
Boot Image : Clean from ROM
Recovery : TWRP
Problems : Get success installation notify, but  stuck on boot logo after installation.

Boot Image Link : https://drive.google.com/file/d/0B2Rmcm-OrofUOGVpblBxNGFlYzQ/view

**Comment by JERW86** [comment]
Take a look a look a look at #272. it might help you provide a log to help solve the issue.

**Comment by gundopanth** [comment]
I had the same problem on my redmi note 3.Installing the latest magisk 13.2 fixed the problem

**Comment by Alish-2004** [comment]
If you have Installed custom rom reinstall it, this is because the boot image was changed by the magisk installer
