### ISSUE TITLE
Root SM-A515fF successfully with MagiskManage..

### ISSUE THREAD

**Issue by adittya1** [topjohnwu/Magisk#2790]
its simple trick just like easy peasy lemon quisy...

Just visite my youtube channel...
Make sure subscribe please please🙏🙏🙏

https://www.youtube.com/channel/UCBVpSYb1xfSz0LGFubdTvnA

Inshaallah i'll upload how to root samsung galaxy SM-A515F....

Thank you...
![Screenshot_20200510-192011](https://user-images.githubusercontent.com/47035354/81504807-044c3480-92f4-11ea-811d-3d832bf2805f.jpg)
![Screenshot_20200510-191634_Root Checker Basic](https://user-images.githubusercontent.com/47035354/81504808-057d6180-92f4-11ea-8e44-3bc696a9abc5.jpg)

**Comment by osm0sis** [comment]
Don't spam your bullshit here.
