### ISSUE TITLE
cant root vivo y17

### ISSUE THREAD

**Issue by aditgani21** [topjohnwu/Magisk#2792]
Device model : VIVO Y17 (1902
ROM: Stock ROM (Funtouch Os/ Android Pie)

vivo y17 is not A/B and is system-as-root (SAR) so the only method is to patch recovery.img.

1 patched recovery.img with Magisk Manager Stable/Canary ---> no error
2 flashed patched_recovery.img --> no error
3 rebooted through recovery ---> no bootloop
Issue : Magisk is not installed and the device is not rooted.

I can't grab Magisk log from /cache/ as the device is not rooted.
help me

![Screenshot_20200511_143914](https://user-images.githubusercontent.com/65148082/81532178-8bea7f80-9396-11ea-9bdf-d9ac9f335d63.jpg)
![Screenshot_20200511_144029](https://user-images.githubusercontent.com/65148082/81532232-a1f84000-9396-11ea-9397-ec51f1c831cd.jpg)

**Comment by wangdaning** [comment]
Flash the magisk_patched.img?

**Comment by aditgani21** [comment]
@wangdaning 
yeah im already to flash patched recovery.img via fastboot.

**Comment by aditgani21** [comment]
@wangdaning and if try flash empty vbmeta.img to disable dm_verity .
my device bootloop .
fortunately i already have stock  vbmeta.img
