### ISSUE TITLE
Magisk shown as uninstalled after installing a module

### ISSUE THREAD

**Issue by enovella** [topjohnwu/Magisk#2795]
### Setup
- Device: Pixel3a
- Android: R, latest beta
- Magisk: latest from Canary builds
- Magisk module: https://github.com/ViRb3/magisk-frida (used to work 3-4 weeks ago in previous Magisk versions)

Patched the `boot.img` and got root. Alright so far.
<img src="https://user-images.githubusercontent.com/14809754/81692155-3e394a00-945e-11ea-8e70-897833c8b56e.png" width="50%">

### Problem
Installing modules makes me to lose the ability of getting a root shell via `su` and tweaking modules is disabled because Magisk seems to be "uninstalled".
<img src="https://user-images.githubusercontent.com/14809754/81692151-3d081d00-945e-11ea-838f-72dfc1d1b818.png" width="50%">

### Logs 
```sh
[13:39 edu@xps onedir] (master)>  adb shell
sargo:/ $ su
sargo:/ $ su
sargo:/ $ id
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc),3011(uhid) context=u:r:shell:s0
```

```sh
[13:40 edu@xps onedir] (master)>  tmp/platform-tools/adb shell su -c id
uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0
```

**Comment by laupuy** [comment]
Hi,
ditto here https://github.com/topjohnwu/Magisk/issues/2779
;)

**Comment by daveholladay** [comment]
I've reproduced this with a null module containing only a module.props file + the installer.
Once it's uninstalled `su` in a shell doesn't work, but `adb shell su -c <command>` does execute as root.

**Comment by daveholladay** [comment]
Magisk 2aede977(20407) works as expected on exactly the same configuration.

**Comment by enovella** [comment]
To recover your rootshell:

```sh
$adb shell su -c rm -rf /data/adb/modules/$MODULE_NAME
```

**Comment by enovella** [comment]
FYI -- `122b4d66 (20411)` has the same problem

**Comment by tnhillbilly17** [comment]
3xl same issue package rename before flashing module solved issue

**Comment by enovella** [comment]
Latest build `e02e46d0 (20414)` fixes the issue.
