### ISSUE TITLE
Device not supported by module

### ISSUE THREAD

**Issue by Samy2020** [topjohnwu/Magisk#2796]
Pls add redmi note 4 in supported devices of BootAmoji module in magisk
![Screenshot_20200512-182114](https://user-images.githubusercontent.com/65251231/81734588-58e8de80-94b1-11ea-9309-b1411dd0d3da.jpg)

**Comment by DanGLES3** [comment]
that's up to the module developer not Topjohnwu

**Comment by osm0sis** [comment]
☝️
