### ISSUE TITLE
Stuck at boot animation when hitting reboot somewhere in LOS 17.1

### ISSUE THREAD

**Issue by UltraBlackLinux** [topjohnwu/Magisk#2798]
Whenever I reboot my phone, its stuck at the LOS loading animation forever. I can boot to my sys though, if I enter the recovery mode and hit reboot system now.
I tried everything and came to the conclusion, that magisk is causing this problem.
Is there a way to fix this? Im not very happy with this solution, because I cant get my sys to work after a Reboot if I have no pc and usb cable nearby.
Ty for Help

**Comment by xarantolus** [comment]
I had the same problem, thank you for the TWRP reboot trick.

This happened only after installing Bromite System WebView, everything was fine before.

**Comment by UltraBlackLinux** [comment]
Im actually doing this wiith the original LOS recovery xD

**Comment by UltraBlackLinux** [comment]
Im having this problem with magisk itself. No module/app is causin this problem

**Comment by osm0sis** [comment]
See #2695; lots of devices that are upgraded/retrofitted to Android 10 seem to be having issues.

Please add your info to the pile over there in the existing issue.
