### ISSUE TITLE
[Huawei] Honor 8 - can't flash Magisk 13.1

### ISSUE THREAD

**Issue by sir-wallaby** [topjohnwu/Magisk#280]
![img_20170712_160846](https://user-images.githubusercontent.com/5182721/28139887-f4d140f8-6723-11e7-9322-0e036b92bb00.jpg)
[stock_boot_7a596603fe1c03015f589cc482a4e0b9e006499a.img.gz](https://github.com/topjohnwu/Magisk/files/1143308/stock_boot_7a596603fe1c03015f589cc482a4e0b9e006499a.img.gz)

[recovery.txt](https://github.com/topjohnwu/Magisk/files/1143314/recovery.txt)

**Comment by Ante0** [comment]
Well, it can't find cat or grep. Could you try 'grep' command and then 'cat' command in twrps terminal and see if they work there?

**Comment by sir-wallaby** [comment]
grep works. For some reason cat does not seem to work in TWRP. seems odd to me.

**Comment by Ante0** [comment]
Did you try 13.2 yet?

**Comment by JpegXguy** [comment]
13.2 + Manager v5.0.6 works beautifully on P8 Lite. I suspect it will be the case with Honor 8 as well

**Comment by sir-wallaby** [comment]
No luck with 13.2 either.

**Comment by JpegXguy** [comment]
I assume you went clean with uninstaller first. Well, the betas are an option as well.

**Comment by sir-wallaby** [comment]
yeah, i've tried uninstaller -> reboot -> flash Magisk 13.2 (no go)
 and flashing stock boot.img -> reboot -> flash magisk 13.2 (no go)

**Comment by Ante0** [comment]
Could you flash v12?

**Comment by sir-wallaby** [comment]
i'll flash v12 and upload log.

**Comment by Ante0** [comment]
Sorry, meant if you had it flashed prior to trying v13

**Comment by sir-wallaby** [comment]
yeah, v12 seemed to work fair enough. Couldn't pass safetynet but, at least devices was rooted then. Now i'm unrooted and can't flash magisk.

**Comment by JpegXguy** [comment]
Do any of the betas work?

**Comment by sir-wallaby** [comment]
i'll try some of the beta's next. v12 does flash, but, I get an unusually long boot time and then Magisk manager doesn't detect Magisk is installed. actually, do I need to use the older version of magisk manager for v12?

**Comment by JpegXguy** [comment]
Wait, so v12 doesn't work? Anyhow always flash the uninstaller first

**Comment by Ante0** [comment]
Yes, the current manager (5.0.x) is only for v13+.
You can get the 4.3.3 from: https://github.com/topjohnwu/MagiskManager/releases

Also, see if updating twrp does anything: https://forum.xda-developers.com/honor-8/development/twrp-t3566563

**Comment by sir-wallaby** [comment]
ok, updating twrp now.

**Comment by sir-wallaby** [comment]
uninstaller for v12?

**Comment by JpegXguy** [comment]
Doesn't the most current one work for v12?

**Comment by sir-wallaby** [comment]
unsure

**Comment by sir-wallaby** [comment]
Here is log I get when I install v12.0. It does successfully flash, but as noted above, it doesn't seem to actually install Magisk. (this was flashed with the newest version of TWRP too)

[recovery.txt](https://github.com/topjohnwu/Magisk/files/1153511/recovery.txt)

**Comment by sir-wallaby** [comment]
So, I can't even uninstall v12 though without flashing my boot.img. just keeps error-ing out with grep not found.?

[recovery_uninstallerv12.txt](https://github.com/topjohnwu/Magisk/files/1153528/recovery_uninstallerv12.txt)

**Comment by JpegXguy** [comment]
Maybe there's an issue with your system?

**Comment by sir-wallaby** [comment]
yeah, probably the most likely issue here.

**Comment by Ante0** [comment]
Using TWRP's file manager, check in /sbin if you find cat and grep

**Comment by sir-wallaby** [comment]
yes, both are located in /sbin

**Comment by Ante0** [comment]
Are you on stock B385 kernel now?

**Comment by sir-wallaby** [comment]
yes stock kernel at the moment.

**Comment by Ante0** [comment]
Tried by flashing your boot image, B385, on my Mate 9. Then flashed Magisk 13.2 and it installed fine. So nothing seems to be wrong there either. It's grep and cat that are messing stuff up. I guess you could flash the boot image I just rooted and manually place magisk.img from v13.2 in /data/... But a permanent fix would be nicer.

**Comment by sir-wallaby** [comment]
so, what's up with the grep and cat on my device? if it installs fine on yours with my boot image, i'm unsure of where the issue is?

**Comment by sir-wallaby** [comment]
Hey @Ante0 , I've tried about everything I can think of, short of wiping my device completely, which I want to avoid doing. 

Could you just load in my stock boot.img, flash the new magisk 13.3 and then upload it back here for me. I would be super grateful. thanks.

**Comment by Ante0** [comment]
@sir-wallaby pick the one you want (If you're currently decrypted or not). Verity is removed in both.
https://mega.nz/#!csljjbaT!6K0wlVih3zYQjEHZLgbjKBqdYI3OuQrcM9pxnB5VwOE = Encrypted, flag in fstab were not changed (forceencrypt is enabled).
https://mega.nz/#!Y9cFCBDJ!FD7Va-1QdIIYG4WrO2f_g9KRsB8dHvW8Eh7CezT0KkE = Forceencrypt flag in fstab was changed to encryptable.
Not sure if you can flash them through TWRP, I had to 'dd' to get it. Fastboot should work if you can't through twrp

**Comment by sir-wallaby** [comment]
ok, sorry, just woke up. I'll check these out. I think flashing in Fastboot will be more likely. I could never get the original boot.img to flash through TWRP anyway, it always ended up getting me to e-recovery.

**Comment by Ante0** [comment]
Do you still have /data/magisk.img? If you used Uninstaller scripts it's gone.

**Comment by sir-wallaby** [comment]
Let me double check on this.

**Comment by antihistamines** [comment]
I have an FRD-L04 on B385 and I have no issues with any Magisk version including 13.3. I'm also able to flash boot images from TWRP.

Obviously though your device is having issues, perhaps start this thread over at XDA and close this issue? It seems to be device-specific.

**Comment by sir-wallaby** [comment]
Closed.

**Comment by sir-wallaby** [comment]
Thanks for all the helps guys. Solved the issue by extracting the SYSTEM.IMG from the B385 UPDATE.APP and then flashing that over top of my SYSTEM partition. Then, the Magisk13.3.zip flashed successfully.
