### ISSUE TITLE
Feature question - not sure if module like this exists

### ISSUE THREAD

**Issue by bojanv55** [topjohnwu/Magisk#2802]
I have a use-case where I would need to install one android app normally on android phone with magisk pre-installed, and then install this magisk module (not sure if it exists, and if not if it is possible to be developed at all) that would act as a wrapper/proxy - proxifying all network traffic that goes in/out. Also, I would need to be able to tell magisk module where to route traffic from this app only (other apps should not be affected).
Is there anything like this?

Other part of functionality would be sync of application state between two different phones - so if app db on one phone (or any other file) is modified - it is automatically synced to other phone.

**Comment by osm0sis** [comment]
This is not the place to ask about random modules. Ask in the Magisk General Discussion thread on xda.
