### ISSUE TITLE
xiaomi redme 8a Magisk can not install

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#2804]
使用 Android Image Kitchen解压boot对比了下。 猜测原因是boot.img-zImage 未被patch。 

在提问之前我先搜索了一下issues 我并不是第一个提出问题的人。
不过似乎没有人能够回答这个问题，就被关闭了。 不知道是什么原因。
请问topjohnwu大神能回答一下再关闭嘛 非常感谢

Use Android image kitchen to decompress boot and compare. The guess is that boot.img-zimage is not patched.

I searched for issues before asking questions. I'm not the first one to ask questions.

But no one seemed to be able to answer that question, and it was shut down. I don't know why.

Would you like to ask the top John Wu God to answer and close it again? Thank you very much

Magisk 19.3 20.4 都试过不行。 别人的手机所以没机会测试金丝雀版本

**Comment by sabpprook** [comment]
版本資訊都沒給，我看是要請鬼拿藥單了

**Comment by androiddisk** [comment]
> 版本资讯都没给，我看是要请鬼拿药单了

哦哦 谢谢提醒 Magisk 19.3 20.4都试过不行。别人的手机所以没机会测试金丝雀版本

**Comment by gam2046** [comment]
Is there any news?
