### ISSUE TITLE
Flashing Magisk causes my phone to go into a bootloop? (SM-A600FN)

### ISSUE THREAD

**Issue by ChachyDev** [topjohnwu/Magisk#2806]
### My phone doesn't seem to mount anything when booting when I have flashed Magisk

I am not the best at rooting stuff so I asked my friend to read through the logs and he said that it was not mounting anything but when I flash Magisk on Pie it seems fine I have sent my logs in this also :)

**My device is an SM-A600FN and yes I did flash RMM Bypass and No-Verify already**

[dmesg.log](https://github.com/topjohnwu/Magisk/files/4639746/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/4639747/recovery.log)

**Comment by osm0sis** [comment]
Sounds like the recently closed #2695; lots of devices that are upgraded/retrofitted to Android 10 seem to be having issues.

**Comment by ChachyDev** [comment]
Ah, the "solution" didn't seem to work for my phone :/

**Comment by UltraBlackLinux** [comment]
If u mean my "Solution" - Did u try this from the los recovery? Didnt try from twrp/...

**Comment by Atatar7** [comment]
That's not caused by magisk. You can have  root without twrp. If you want twrp use Zackptg5's encryption disabler.

**Comment by ChachyDev** [comment]
I managed to fix this by taking my OEM's boot image and using Magisk Manager to patch it and then flashed it. Thanks for the help!
