### ISSUE TITLE
Failed to patch Galaxy Tab S6 Lite (SM-P610)

### ISSUE THREAD

**Issue by B1gM1k3** [topjohnwu/Magisk#2808]
Hi,
Tried to Magisk Root my new SM-P610 (Tab S6 lite). Bootloader is unlocked.
After installing the patched file, i have this message :
ODIN MODE (AVB Fail)
vbmeta: Error verifying vbmeta image: OK_NOT_SIGNED (3)
vbmeta: VERIFICATION_DISABLED bit is set.
CUSTOM VBMETA
VBMETA : No sign info
VBMETA ,
Thanks for helping :-)

**Comment by osm0sis** [comment]
#2272
