### ISSUE TITLE
Bootloop with Huawei recovery_ramdisk

### ISSUE THREAD

**Issue by Slimakoi** [topjohnwu/Magisk#2810]
Hello, I'm trying to get Magisk on my Huawei P Smart 2018 (FIG-LX1, EMUI 9) by flashing the zip file with TWRP, it says that everything was successful but when I boot to the system it doesn't have root permissions and when I try to boot into recovery mode it boot loops. The operating system is a custom rom as you may have guessed, its ASOP Extended 7.0 running android 10.

Ill be attaching the default recovery image ([RECOVERY_RAMDISK.img](https://drive.google.com/file/d/1SunIr_yngx1RqextWe-ZbctdHyicS5rT/view?usp=sharing))

**Comment by osm0sis** [comment]
https://topjohnwu.github.io/Magisk/install.html#emui-9-or-higher

**Comment by Slimakoi** [comment]
> 
> 
> https://topjohnwu.github.io/Magisk/install.html#emui-9-or-higher

Still doesn't work, it reboots and starts booting from system

**Comment by osm0sis** [comment]
Is this still an issue on the latest Canary?

**Comment by Slimakoi** [comment]
I was using the emui 9 stock recovery and patched it and installed, and was using the latest version of Magisk (7.5.1)
I changed firmwares due to the issue but i still have the ramdisk i used, unfortunately not the ramdisk patched version.
EMUI 9 Ramdisk: https://drive.google.com/file/d/1v67eMnh61-Q54JrmqkoThJJ2uikQBC6y/view?usp=sharing

**Comment by osm0sis** [comment]
You need to try with the latest Canary or I'll have to close the issue.

**Comment by Slimakoi** [comment]
I'll close it due to not being able to change firmware to test it again. Thanks anyways for your help.

**Comment by osm0sis** [comment]
Alright, if you or don't other Huawei use come into some time to test, please open a new issue.
