### ISSUE TITLE
Magisk 20.4 Notification at bottom of screen, can not clear.

### ISSUE THREAD

**Issue by bmazak** [topjohnwu/Magisk#2817]
Just started to see a message with the Magisk Icon at bottom of screen that says Re-pro Cache cleared. It's transparent so it does not interfere with Icons under it. Can not clear this message. Other message was Busy Box Pro denied Super User access.  When I granted it then the Busy Box Granted Super User access message appeared but can not clear the message.  After about 10 min message goes away.  Problem is I wasted time trying to clear this because I never saw a stuck message like this before.  Only since flashing Android 10 Evolution.  Is there a time setting for this message?  I'm still trying to figure out why Busy Box Pro was denied Access in the first place since that was the original message this morning.  I got a automatic reboot this morning and would like to know what has access to my phone to cause it to reboot automatically.  Is that a Hack? OnePus One still kicking.

**Comment by bmazak** [comment]
I want you guys to know we Love the fact that you cared enough for us to produce a program like Magisk and we love you for it.

**Comment by osm0sis** [comment]
Use Canary Manager.

**Comment by bmazak** [comment]
I found the answer, just go to Time to take action in Settings, Accessibility and set it to Default. It is 5 sec.  I had it at 15 seconds. For Android 10 Evolution on OnePlus One
