### ISSUE TITLE
Installing module with custom mount points breaks RW  remounting

### ISSUE THREAD

**Issue by Kein** [topjohnwu/Magisk#2818]
MIUI 11/9.0 on Note7, Magisk 20.4 installed normally (flashed) through TWRP.

After installation of a single module
https://github.com/Magisk-Modules-Grave/gjf_bt
I no longer can mount anything for `rw`. `mount`, after being given remount command, exits normally, as if it did its job but attempt to write or delete anything from system-root dies due to timeout with permission error. This also break every file manager (Total Commander, Root Explorer) that remounts `/` for root browsing/writing of the system. I thought at first it was outdated module but after some more research I dont believe it is relevant at all, it just uses mount points.

Attached the mount output:
[mounts_mod.log](https://github.com/topjohnwu/Magisk/files/4660486/mounts_mod.log)

Let me know if logcat needed (but it has no relevant data).

**Comment by osm0sis** [comment]
If you turn on Safe Mode in Manager and reboot. Any change?

**Comment by Kein** [comment]
You mean Core Mode? Yes, then it works just fine.

**Comment by osm0sis** [comment]
Okay, sounds legit like a regression then. @topjohnwu will need to take a look.

**Comment by Kein** [comment]
Just curious, do the proposed (and implemented) changes here have any relevance to the issue: https://github.com/topjohnwu/Magisk/commit/ec3705f2ed187863efc34af5415495e1ee7775d2 ?

**Comment by topjohnwu** [comment]
Most likely module issue. Modules does in fact can cause certain locations unable to be rw

**Comment by Kein** [comment]
Why was this silent-dropped? Is this resolved?

**Comment by Kein** [comment]
How would I know it is a module issue,what can possible cause that? A similar module with seemingly the same structure has no issues.
