### ISSUE TITLE
Unable To Unpack Boot Image On Lenovo Tab3 Essential (tb3-710f)

### ISSUE THREAD

**Issue by pogo-pogo** [topjohnwu/Magisk#282]
Here's the end of the messages:
- Unpacking boot image
! Unable to unpack boot image
Updater process ended with ERROR: 1
Error installing zip file '/external_sd/Magisk-v13.1.zip'
Updating partition details...
...done

I'm using the stock rom and "recovery3_twrp302_Lenovo_TB3-710F.zip" from here:
https://www.androidfilehost.com/?w=files&flid=80021

Hope I've attached the bootimg properly:
[ROM_9.zip](https://github.com/topjohnwu/Magisk/files/1145713/ROM_9.zip)

Edited to say thanks for any help!

**Comment by IzaacJ** [comment]
Same issue here, also complete stock and same twrp.
