### ISSUE TITLE
Why is my storage space smaller

### ISSUE THREAD

**Issue by CHonesetDoPa** [topjohnwu/Magisk#2820]
I found that my "Magisk Manager" took up 12gb of space. It's now used with "EdXpoesd". I want to know how to clean up my space.I found a big folder in "/sbin/.magisk/".Here is a folder called"mirror".I wonder if I can delete this to free up my space.
Thanks.

**Comment by linuxandria** [comment]
@CHonesetDoPa it's not really taking up space; everything in /sbin/.magisk is just a mirror of actual data on the device, nothing more.

Any claims your rom is making about it taking up 12gb are it just interpreting the mounts wrong (if I had to guess you had about 12gb of stuff in /data 😜)

_Sent from my Pixel 3 XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CHonesetDoPa** [comment]
Thank you.(๑ゝω╹๑)
