### ISSUE TITLE
Oppo Realme 5 GSI stuck at first boot.

### ISSUE THREAD

**Issue by VL4Z3F1R3** [topjohnwu/Magisk#2825]
I'm trying to root my Realme 5 that is flashed with Havoc os 3.5 with modified magisk by phh, the installation is always successful via TWRP but if when you rebooted the device, it stucks at the Realme 5 logo. The device returns to normal when you flashed the installation. Any solutions?

**Comment by osm0sis** [comment]
If the ROM has modified Magisk built-in then you need to ask them to update it or fix it.
