### ISSUE TITLE
Why is my storage space smaller (How I can fix it up))

### ISSUE THREAD

**Issue by CHonesetDoPa** [topjohnwu/Magisk#2826]
I'm so sorry that I have to ask  you again about this question(#2820 )
I found my phone's Storage space is getting smaller after using "Magisk"and"EdXpoesd".
Emm,my Magisk version is 19.4(19400)
My EdXpoesd version is v0.5.0.0(4548)(YAHFA)
Android version is 9(pie)
My phone is “xiaomi redmi note8”,miui11(20.3.26)
I have fed back this question to Xiaomi, but they didn't answer me.
Something went wrong and I had a lot less space.
I think it's because the system thinks that ".magisk" is actually stored data.
How I can fix it?
Do I need to upgrade？
Thank you.

**Comment by osm0sis** [comment]
Sounds like your file manager app just needs to be updated. Ask any further questions in the Magisk General Discussion thread on xda.
