### ISSUE TITLE
Can not install magisk 13.1.1 on H96 Pro+ S912 Android 6.0.1

### ISSUE THREAD

**Issue by atboxshop** [topjohnwu/Magisk#283]
The problem is , Magisk manager could not detect the boot image location. My boot image location is on dev/block/boot. I tried to config like that on manager but no luck. Pls help me out, Thanks
I attached recovery and boot.img file
[Archive.zip](https://github.com/topjohnwu/Magisk/files/1147231/Archive.zip)

**Comment by Ante0** [comment]
Check /dev/block/mmcblk1p8, that's the alternative location of boot according to log. 
Though it throws a lot of errors about commands not found too...

**Comment by atboxshop** [comment]
Thanks Ante0, I will try that boot location and let you know. 👍😁

**Comment by atboxshop** [comment]
If topjohnwu can make this magisk patch worki g on window, it will be easier. All we need to do is copy boot.img out of the box and patching it, after that we copy back to the box, overwrite the existing one. 👍 and done.

**Comment by Ante0** [comment]
It could be your TWRP version, or the actual twrp build for your device.
Have you successfully installed any other Magisk version?

**Comment by atboxshop** [comment]
Yes, I have successfully installed twpr on my device. I use twpr 3.0.2 of t95z plus device but it is compatible with my device. I dont think it is twpr problem because I can install supersu or dolby atmos by that twpr. But I can not install any version of magisk. The problem is alway the boot image could not be found.

**Comment by Ante0** [comment]
Seeing the log it's more than that. It throws errors at every command it
tries to run.
