### ISSUE TITLE
MagiskDetector

### ISSUE THREAD

**Issue by jbro129** [topjohnwu/Magisk#2836]
I came across this 
https://github.com/vvb2060/MagiskDetector

It can detect su and Magisk even with Magisk hide selected for the app. I just thought I'd bring this to your attention @topjohnwu in case you weren't aware already.

Love your work btw

**Comment by osm0sis** [comment]
Yeah @vvb2060 is our homie.

**Comment by kam821** [comment]
MagiskHide mounts detection bug is already reported, you have to wait.
https://github.com/topjohnwu/Magisk/issues/2406

**Comment by vvb2060** [comment]
@kam821 In fact, this app uses 5 independent methods to detect. 😆  I think the mount detection method of other apps is too simple.

**Comment by jbro129** [comment]
> @kam821 In fact, this app uses 5 independent methods to detect.  I think the mount detection method of other apps is too simple.

Sounds like detecting Magisk is pretty easy to do. Are methods of preventing these detection methods being worked on? I know some app developers don't want their users being rooted or having Magisk regardless if Magisk is even affecting their app specifically.
