### ISSUE TITLE
Pixel C - Purenexus A: 7.1.2 Boot into Recovery after install - worked one time

### ISSUE THREAD

**Issue by devz3r0** [topjohnwu/Magisk#284]
hi

I installed Magisk 13.0 (Update 13.2 did that too) on my Pixel C, after try to setup Magisk,
the flash process worked fine without errors.
After I want to boot into the system I got thrown into TWRP.
Here I shared the boot image and the Logs TWRP could dig out:
https://cloud.r-d-w.net/s/magisk

One time I got Magisk running was that time I destroyed my systempartition with flashing the boot image (dont ask what I thought at that place) to it and restoring the OS with a full flash. But after update to 13.2 it was gone to recovery again.
TWRP is 3.1.1.0

**Comment by lhw** [comment]
There is definitely a regression for the Pixel C.
Magisk-v13.0(96f8efc): Tested and working
Magisk-v13.1: Fails to flash
Magisk-v13.2: Flashes but causes a "No command" after Google logo on boot

**Comment by devz3r0** [comment]
Correct, I tried Magisk-v13.0(96f8efc) again, it is working now again.

**Comment by mmirg** [comment]
13.3 fails in the same way on Pixel C.

**Comment by lhw** [comment]
Still broken as of 13.5 Beta

**Comment by devz3r0** [comment]
13.6 works on my device.
