### ISSUE TITLE
Ing Homebank app detects Magisk root

### ISSUE THREAD

**Issue by eblis** [topjohnwu/Magisk#2841]
This issue is very similar to https://github.com/topjohnwu/Magisk/issues/985 but with the [latest ING Homebank app for Romania](https://play.google.com/store/apps/details?id=ro.ing.mobile.banking.android.activity).
I was able to hide root for the previous version of Homebank by enabling Magisk Hide and repackaging Magisk Manager, but I cannot get this to work with the latest version of the ING app.

Do you know how I could find out more information about what the app is doing, maybe a log or something similar ?

**Comment by osm0sis** [comment]
#1152

**Comment by waahhhh** [comment]
A similar problem occurred with the app "ING Banking to go" since the last update.
In my case version 3.5.1 doesn't allow rooted devices - sad very sad.
I backed up the data of the app (using Titanium Backup) and than uninstalled it.
After that I installed version 3.4.1 from https://apkdownload.com and restored the app data using Titanium Backup.

Maybe you could try the same by downgrading from version 4.0.6 to 6.16 (or older).
https://apkdownload.com/ING-HomeBank/ro.ing.mobile.banking.android.activity.html

**Comment by eblis** [comment]
I've been doing a bit of digging and from what I can tell the previous version of ING Homebank, the one that works uses [GuardSquare's Dexguard](https://www.guardsquare.com/en/products/dexguard) to check for root, whereas the newest version, the one that detects root no matter what I try uses [InsideSecure](https://www.insidesecure.com/us/Company/Press-releases/Inside-Secure-delivers-Application-Protection-to-defend-against-malicious-attacks-on-Android-Java-devices).

From what I can tell none of the people that have upgraded to the latest version of the ING Homebank app can get it to work with Magisk

**Comment by eblis** [comment]
I've managed to disassemble the two root related methods from the native library - I can't disassemble the whole library even with 250+ GB of RAM, it still runs out of memory :(

[liba.so.c.zip](https://github.com/topjohnwu/Magisk/files/4712169/liba.so.c.zip)

**Comment by rontav** [comment]
What got it to work for me was renaming the Manager app (not sure if relevant) and enabling Magisk Core Only Mode (and a reboot). After opening the app I was surprised to see that I got over the root check. I was even more surprised when I disabled the Core Only Mode and saw that the app still worked after a reboot.

**Comment by luckysquid** [comment]
same problem with last ing italy update.
App detect root.
safetynet is ok, ing app and magisk app is hidden from menu

**Comment by eblis** [comment]
It was suggested that the recent detection of root might have happened because of March's security update - but I've just performed an update on a separate banking app and that one hasn't picked up on the root.

@osm0sis Is there any chance that this issue with ING Homebank will be looked into please ?

**Comment by luckysquid** [comment]
I use Android 9 with 2019 March security patch. So old security patch :(
Other banks app donesn't found the root. it's a ING issue

**Comment by eblis** [comment]
> What got it to work for me was renaming the Manager app (not sure if relevant) and enabling Magisk Core Only Mode (and a reboot). After opening the app I was surprised to see that I got over the root check. I was even more surprised when I disabled the Core Only Mode and saw that the app still worked after a reboot.

This does not work for me with either of the 2 releases that started detecting root (they've made one update since I first reported the issue)

**Comment by alex26aly** [comment]
Any updates here? I can't get the ING app working, tried with magisk core enabled, but with no success

**Comment by osm0sis** [comment]
Read what I linked when I closed it.

**Comment by eblis** [comment]
I think what we're trying to say is if it is possible to have a look into this method of detecting root, in case it's something new?

Quite a lot of people are starting to have problems, while they don't experience these problems with others apps they're hiding root from. Are you saying that none of us are following best practices for hiding root ?

I have updated other banking apps since the March security patch and none of them detect root, except for ING.

**Comment by osm0sis** [comment]
Read the link. If you aren't providing any insights into the detection your issues are useless, will be closed and ignored. The next step will be locked since you seem to refuse to comprehend the above

**Comment by luckysquid** [comment]
@osm0sis we don't want to waste your time.
What can we do to help analyze the problem?

**Comment by osm0sis** [comment]
You clearly don't know how to analyze and provide technical insights into how to fix it, so now this gets locked, per my last reply.
