### ISSUE TITLE
Magisk blocks Andrax! Need to delete?

### ISSUE THREAD

**Issue by vertolazer** [topjohnwu/Magisk#2843]
I am very upset that Magisk is blocking Andrax !!  If in the near future this does not change, I will have to put another root!

**Comment by xfjtshgl** [comment]
Same issue

**Comment by linuxandria** [comment]
> I am very upset that Magisk is blocking Andrax !! If in the near future this does not change, I will have to put another root!

First of all it's actually the opposite way around. Andrax blocks magisk, which also means any other root method will have the same result if it doesn't flat out brick your device.

Also: #1152

**Comment by linuxandria** [comment]
Highly recommend closing as it's already known there's several working methods to detect magisk and @topjohnwu is working on what he can

**Comment by NH-Killer** [comment]
They are talking about ANDRAX: https://andrax.thecrackertechnology.com damn,,,

**Comment by Didgeridoohan** [comment]
> Chroot by magisk does not work on some devices with android 9 and 10 syscall never starts.
> 
> Close issue without responding clearly states that they know what is happening and it is purposeful

Wow... Paranoid much? Your issue was closed because it didn't contain any kind of useful information that would be expected in a bug report.

**Comment by NH-Killer** [comment]
> > Chroot by magisk does not work on some devices with android 9 and 10 syscall never starts.
> > Close issue without responding clearly states that they know what is happening and it is purposeful
> 
> Wow... Paranoid much? Your issue was closed because it didn't contain any kind of useful information that would be expected in a bug report.

Don't exist any information, simple like that chroot is blocked and never start... is impossible strace too... no error...

**Comment by NH-Killer** [comment]
And useful information is not to harm one system to favor another!

**Comment by Didgeridoohan** [comment]
> And useful information is not to harm one system to favor another!

Ok, my curiosity is getting the better of my and I'll bite. What kind of blocking and harm is it that you guys think that Magisk is doing?

**Comment by NH-Killer** [comment]
> > And useful information is not to harm one system to favor another!
> 
> Ok, my curiosity is getting the better of my and I'll bite. What kind of blocking and harm is it that you guys think that Magisk is doing?

Can you tell me? Closing all threads related with ANDRAX...

Let me try explain...

I'm the dev of ANDRAX, ANDRAX need chroot to start or container...

If we try run chroot in a root shell the container never start only keep in a type of "loading" stat, we can strace because strace keep in this "loading" type.

This only occour in some devices with Android 9 and 10, my users tried canary builds too

**Comment by Didgeridoohan** [comment]
The issue are closed because all they say is "something doesn't work, fix" without anything to go on.

If there's a bug in Magisk, find it and provide the proper information for John to work with. He's not gonna go jump through hoops for you...

**Comment by linuxandria** [comment]
TBH I thought it was another magiskhide not works plz fix issue lol

**Comment by NH-Killer** [comment]
> There's no conspiracy (as you seem to think)...
> 
> The issue are closed because all they say is "something doesn't work, fix" without anything to go on.
> 
> If there's a bug in Magisk, find it and provide the proper information for John to work with. He's not gonna go jump through hoops for you...

Maybe will take a while, i downloaded the source code... don't worry more about it, when i find the problem i'll provide a fix but source closed to my users if you don't want help, i not will help too...

**Comment by Didgeridoohan** [comment]
Wow...

I'm curious though: where did you read that nobody here wants help?

**Comment by osm0sis** [comment]
That also would violate GPL, so.. :roll_eyes:

**Comment by NH-Killer** [comment]
> That also would violate GPL, so.. roll_eyes

#antitrust

**Comment by osm0sis** [comment]
Cool story. Locking this now due to your behavior. When you can provide a clear issue report at a reasonable level of discourse feel free to open a new issue.
