### ISSUE TITLE
Magisk bootloop, SELinux: Could not load policy: Out of memory

### ISSUE THREAD

**Issue by yshui** [topjohnwu/Magisk#2848]
Phone: Xperia XZ1 Compact
Firmware: 47.2.A.11.228 (Android 9)
Magisk version: 20.4

Installing magisk worked for a couple of times, then suddenly my phone doesn't boot. In TWRP, I can get boot dmesg via /sys/fs/pstore. I see `SELinux: Could not load policy: Out of memory`, then kernel panic, then reboot.

Reflashing the phone firmware then installing magisk again doesn't fix this problem.

**Comment by topjohnwu** [comment]
Try the latest canary build
