### ISSUE TITLE
SafetyNet fails even with only core enabled in magisk 13.2

### ISSUE THREAD

**Issue by gundopanth** [topjohnwu/Magisk#285]
CTS as well as basic integrity fails even when only core module enabled after updating magisk to 13.2 from 12.0. It would also fail in 12.0 if core modules was not enabled.In 12.0 after enabling core module only it would still fail.To make it pass in 12.0 I would cd to magiskhide folder using terminal and then give disable and enable command.But in 13.2 the enable and disable file in /magisk/.core/magiskhide is not there any more.Thats why safetynet fails.Device:Redmi Note 3 kenzo
Rom:MIUI 8.5.2.0
Stock boot image: http://s000.tinyupload.com/index.php?file_id=36529834505206556451

**Comment by Ante0** [comment]
It's integrated in the magisk binary as an applet, so just run
su
magiskhide --disable
Will disable it.

**Comment by NinjaBoyLao** [comment]
I experience this issue as well on stock ROM for Moto X Pure. I never had to run enable and disable commands, but I now can't get safetynet to pass with any reliability, it seems entirely random

**Comment by gundopanth** [comment]
Ante0 even after enable disable through terminal safety net fails

**Comment by sou7611** [comment]
Fails for me too, only remedy is a complete removal of magisk.  There is no combination of magisk/magiskhide that works.

**Comment by sou7611** [comment]
See :

https://github.com/topjohnwu/Magisk/issues/291

**Comment by Ante0** [comment]
@sou7611 that's pretty new though, but worth a shot for OP. I passed yesterday (or 2 days ago) but not today, the fix works though until reboot.

**Comment by sou7611** [comment]
I created a tasker task that applies the build.prop mods ... just import the task, then create a profile that runs it at boot.

https://www.dropbox.com/s/e5b58aenm66ohwj/Remove_Build.Prop_Magisk_Entries.tsk.xml?dl=0

**Comment by devz3r0** [comment]
should be fixed now in 13.3.

**Comment by gundopanth** [comment]
Fails even in 13.3

**Comment by Ante0** [comment]
Did you figure out what was wrong? 
Check in log if it's similar to this at the end:

`I(  356:  461) * Starting MagiskHide
I(  356:  461) hide_utils: Hiding sensitive props
I(  356:  461) hide_list: [com.google.android.gms.unstable]
I(  356:  461) proc_monitor: init ns=mnt:[4026531840]
I(  356:  526) ** late_start service mode running
I(  356:  526) * Running service.d scripts
I(  356:  526) * Running module service scripts
I(  356:  461) proc_monitor: zygote ns=mnt:[4026532981] zygote64 ns=mnt:[4026532980]
I(  356:  461) proc_monitor: com.google.android.gms.unstable (PID=4918 ns=mnt:[4026533087])
I( 4952: 4952) hide_utils: Re-linking /sbin
I(  356:  461) proc_monitor: com.google.android.gms.unstable (PID=7800 ns=mnt:[4026533162])
`

**Comment by Ante0** [comment]
The Re-linking /sbin is important.

**Comment by gundopanth** [comment]
It doesn't relink /sbin
Check my log : http://s000.tinyupload.com/index.php?file_id=83128387923327061570

What is the solution?

**Comment by Ante0** [comment]
For me, it's  enabling kernel logging. I'm not sure how it's done for your device. 

Run this in a terminal: logcat -b events -v raw -t 10
And report output. 
Also check this thread for some troubleshooting (if you haven't already): https://forum.xda-developers.com/apps/magisk/magisk-magisk-hide-troubleshooting-tips-t3561828/post71154562#post71154562

**Comment by NinjaBoyLao** [comment]
he's got a xiaomi it looks like, based on his mention of MIUI. just go get the "Universal SafetyNet Fix" module and try using that, it's available as a magisk module from within the app

**Comment by gundopanth** [comment]
It doesn't work i tried it
