### ISSUE TITLE
Error: unable to repack boot image 

### ISSUE THREAD

**Issue by kbhavik** [topjohnwu/Magisk#2850]
I'm new to this so tried playing with my old lying around  asus zenfone A500cg running lollipop stock rom.
Tried to patch official boot img using latest Magisk Manager but got error. 
Logs and boot image attached.

[magisk_install_log_2020-06-01T00:04:44Z.log](https://github.com/topjohnwu/Magisk/files/4708185/magisk_install_log_2020-06-01T00.04.44Z.log)

[boot.zip](https://github.com/topjohnwu/Magisk/files/4708187/boot.zip)

**Comment by Displax** [comment]
It seems related to https://github.com/topjohnwu/Magisk/issues/2847

**Comment by kbhavik** [comment]
Will there be a fix for that?

**Comment by shakalaca** [comment]
boot.img with OSIP header is not supported in Magisk, you may check this repo instead: https://github.com/shakalaca/MagiskOnIntelDevices

**Comment by kbhavik** [comment]
> boot.img with OSIP header is not supported in Magisk, you may check this repo instead: https://github.com/shakalaca/MagiskOnIntelDevices

Thanks a lot. Just a quick question. Will it support android 4.4.2 boot image as well for same zenfone 5.
