### ISSUE TITLE
whether magisk can patch system.img

### ISSUE THREAD

**Issue by aditgani21** [topjohnwu/Magisk#2852]
I have tried various ways to rooting my device.
my device used system as root.
i try to pacth recovery.img and flash it and reboot to recovery like explained by [install magisk to recovery](https://topjohnwu.github.io/Magisk/install.html) 
my device still no have root.
please help me

**Comment by osm0sis** [comment]
Magisk is systemless, either patched boot.img or recovery.img, or in some cases a ramdisk.img of some kind. If you're not sure how to do it for your device ask in your device forum or the Magisk General Discussion thread on xda. This is not the place.
