### ISSUE TITLE
ANDRAX installation in android

### ISSUE THREAD

**Issue by aksploit** [topjohnwu/Magisk#2853]
Sir ANDRAX is not able to install in my device
They told that it's magisk problem 
Please help!!!!

**Comment by osm0sis** [comment]
#2834

**Comment by AbelGit00** [comment]
> Sir ANDRAX is not able to install in my device They told that it's magisk problem Please help!!!!

You cant install Andrax with magisk > https://snakesecurity.org/andrax-documentation/install-and-update/
