### ISSUE TITLE
[Feature Request] Host magisk archive somewhere with global accessibility

### ISSUE THREAD

**Issue by hanabi1224** [topjohnwu/Magisk#2854]
Currently raw.github.com is blocked in Mainland China, thus Magisk Manager can neither check for update or download magisk without VPN. It will be awesome to change the manifest and archive to a different host with better accessibility, thanks!

**Comment by linuxandria** [comment]
If you have a better suggestion for github hosted modules we're all ears

**Comment by topjohnwu** [comment]
We already had DoH included in the ToT Magisk Manager, please wait for the next release
