### ISSUE TITLE
Magisk Installation sets selinux to permissive & saftynet fails

### ISSUE THREAD

**Issue by being-yash-t** [topjohnwu/Magisk#2855]
Device & OS: Redmi Note 6 Pro, Android 10 Syberia OS (CAF)

When magisk is not installed:
    Selinux status: enforcing
    SafetyNet: Both Pass

When magisk is installed:
    Selinux status: permissive
    SafetyNet: Both Fail

By both I mean ctsProfile & basicIntegrity

Whats should I do to fix this?

**Comment by topjohnwu** [comment]
Magisk does not set selinux to permissive, it is either a module or a boot script

**Comment by being-yash-t** [comment]
> Magisk does not set selinux to permissive, it is either a module or a boot script

But I didn't used any modules, I mostly use magisk in core mode.
You just closed the issue? Like that?
