### ISSUE TITLE
Andrax v5r  not installing 

### ISSUE THREAD

**Issue by aksploit** [topjohnwu/Magisk#2856]
Andrax v5r is not installing..... 
Please fix 
![IMG_20200602_231955](https://user-images.githubusercontent.com/46085882/83552660-bcea4a00-a527-11ea-8e54-a1598fd6923d.jpg)

**Comment by topjohnwu** [comment]
No one is blocking anything, the code is open source, there is no blacklist whatsoever.
Tell the developer to fix their own code, or if there is indeed a bug in Magisk, either file a bug report explaining the issue, or directly create a PR to fix the issue.

**Comment by osm0sis** [comment]
The developer already has an issue with appropriate info that was closed too hastily and I've been working with him in it.

#2834
