### ISSUE TITLE
ANDRAX not working

### ISSUE THREAD

**Issue by avi9456** [topjohnwu/Magisk#2857]
ANDRAX not working properly

**Comment by linuxandria** [comment]
I'm getting a strange feeling here, like someone's creating a bunch of fake accounts to push this issue 👀 
Nevertheless this isn't a high priority issue most likely and will be dealt with in its own time

**Comment by Didgeridoohan** [comment]
Someone have just rather stupidly decided that it's a good idea to spread false info:
https://github.com/topjohnwu/Magisk/issues/2856

**Comment by linuxandria** [comment]
@Didgeridoohan FastHub is breaking the link in the first post lol

_Sent from my VIEW 1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by osm0sis** [comment]
#2834
