### ISSUE TITLE
[Feature Request] magisk patcher for PCs

### ISSUE THREAD

**Issue by yangzhaofeng** [topjohnwu/Magisk#2859]
Currently not all devices have a twrp image build. Rooting these devices may require the user copying the boot image to the phone and patch it with magisk manager and copy back to PC and then flash. But theoretically the process of patching the boot image can be done on PCs so the extra steps of copying can be omitted. Is it possible to separate an utilitiy to do that on PCs?

**Comment by topjohnwu** [comment]
Won't happen because all the tools for patching boot images are designed to run on Android. Porting it to PC will take tons of effort, even if we only need to port to Linux desktop, nevermind Windows or macOS.

**Comment by yangzhaofeng** [comment]
It seems that only porting to Linux is also a great idea. As flashing images runs in command lines, it is also not necessary to write GUI for patching tools.

**Comment by Fox2Code** [comment]
MagiskBoot already work on Linux so I think if you have WSL you just need to follow [/scripts/boot_patch.sh](https://github.com/topjohnwu/Magisk/blob/master/scripts/boot_patch.sh)  
  
Also, don't forget to read [/docs/install.md](https://github.com/topjohnwu/Magisk/blob/master/docs/install.md) before doing anything

**Comment by yangzhaofeng** [comment]
@Fox2Code This script calls magiskboot that runs only on Android devices. It will be nicer if the binaries can run on x64 devices that crossbuild a Magisk patched image.

**Comment by ahronshor** [comment]
I built this script past and he worked really well on Linux
because I used the magiskboot from X86 folder
and magiskinit from arm folder,
the magiskboot runs in build time only and the magiskinit is pached in init in the device.
But my script is not perfect with the latest versions of Magisk,
And I have to update it all the time with each version change.

**Comment by Fox2Code** [comment]
Magisk have both `arm` and `x86_64` support

Download Magisk from the [releases page](https://github.com/topjohnwu/Magisk/releases) and extract `/x86/magiskboot`

Note: Running 32bit binary does not work with WSL1 and require WSL2 

An alternative is also to have a PC / VM running Linux

I already used this technique to patch boot images

**Comment by yangzhaofeng** [comment]
Oh I see. `magiskboot` is independent with `magiskinit` so I can copy them from different directories to cross build a patched Magisk image. Thank you very much!

**Comment by osm0sis** [comment]
See https://github.com/topjohnwu/Magisk/issues/2727

**Comment by AreYouLoco** [comment]
I did downloaded v23 release but cannot find magiskboot nor magiskinit in the prebuild apk.

**Comment by SecT0uch** [comment]
For reference, [here](https://dev.sect0uch.world/SecT0uch/Magisk_boot_flasher#run-patch-boot-locally) is how I managed to run the script from my x64 Linux.
Getting the same output file as via the app.  :)

**Comment by Melechtna** [comment]
> For reference, [here](https://dev.sect0uch.world/SecT0uch/Magisk_boot_flasher#run-patch-boot-locally) is how I managed to run the script from my x64 Linux. Getting the same output file as via the app. :)

This doesn't seem to work with payload.bin files, like with lineageOS

**Comment by SecT0uch** [comment]
As written in  the project, I finally gave up this solution and did this instead: https://topjohnwu.github.io/Magisk/ota.html

**Comment by rajarshikhatua100** [comment]
These projects somehow does this - https://github.com/ColdWindScholar/Magisk_Patch_Python , https://github.com/affggh/Magisk_patcher ( https://github.com/svoboda18/magiskboot ) , https://github.com/daboynb/magisk_for_linux
