### ISSUE TITLE
Using Magisk Hide slows down apps drastically

### ISSUE THREAD

**Issue by Gieted** [topjohnwu/Magisk#2860]
Android version: 10
Magisk version: 20.4 (20400)
Magisk Manager version: 7.5.1 (267)

Enabling Magisk Hide for an app seems to slow it down. On some apps this effect is nearly unnoticeable, but on some it's rendering the app unusable and cause it to crash.
Apps tested to slow down drastically are:

- [Revolut](https://play.google.com/store/apps/details?id=com.revolut.revolut&hl=en_US)
- [Allegro](https://play.google.com/store/apps/details?id=pl.allegro&hl=en_US)

Discord app also seems to be slowed down a little by enabling Magisk Hide.

I can provide you with any info/logs if required.

**Comment by skittles9823** [comment]
Make sure to only apply magisk hide on apps that actually need it. I know for a fact that Revolut and Discord don't check for root. Allegro I'm not sure about, but I doubt it needs magisk hide to run.

**Comment by Gieted** [comment]
> Make sure to only apply magisk hide on apps that actually need it

I'm actually been doing so, this is my usual setup:

![signal-attachment-2020-06-03-102237](https://user-images.githubusercontent.com/35242233/83613552-39127b00-a584-11ea-8255-bfb91c4b81a8.jpeg)

Discord don't check for root, still it's worth a mention, because this micro "lags" that happen on each navigation are very visible there. Revolut checks for root and disables fingerprint sing-in if it's present. Allegro only displays irritating "your device is rooted" message on each start, so it's not that big deal.

**Comment by skittles9823** [comment]
> Revolut checks for root and disables fingerprint sing-in if it's present.

Huh, I didn't realise that, good to know.

> Allegro only displays irritating "your device is rooted" message on each start, so it's not that big deal.

Does the lag stop if you don't hide both of them?
Honestly you're probably going to have to choose between dealing with microstutters or slight inconveniences when opening them.

**Comment by Gieted** [comment]
> Does the lag stop if you don't hide both of them?

Yes if I unhide them they work flawlessly.

The problem is there are no "micro stutters", but rather second long freezes on each navigation, that makes app unusable. Also, they often just restart on themselves (probably out of memory or timeout crashes). This really isn't normal, I've used same apps with Magisk Hide back on my old phone with Android Pie and nothing like this ever happened.

**Comment by Gieted** [comment]
I can confirm that the lags go away, after enabling Magisk Core, any suggestions?

**Comment by Gieted** [comment]
After some more investigation I can say that this issue haven't got any link to Magisk, so we can close that one. This issue seems to be caused, by QuickSwitch module. I don't know if this problem is caused by QuickSwitch directly or maybe Lawnchair Launcher. I will probably post issue under QuickSwitch instead.

**Comment by osm0sis** [comment]
See #2359
