### ISSUE TITLE
Internal storage wiped after re-installing Magisk 20.3

### ISSUE THREAD

**Issue by 5TDg9** [topjohnwu/Magisk#2862]
**Info**
Phone: OnePlus 3T, Lineage OS
Magisk: v20.3
TWRP: v3.3.1-1

**Problem Cases**

Magisk was working correctly a long time. I wanted to repack/rename Magisk Manager through settings because another app was not working and detecting Magisk package.
During the repacking process i accidently turned off the screen and probably because of this the reinstallation was not fully completed.
I was not able to start the new MagiskManager package.
So i downloaded Magisk here from github again, went into recovery mode and installed it again without any errors. But after reboot all user data and internal storage data is gone now.
The phone storage is encrypted with a password that is different from the screen lock pin.

**Comment by osm0sis** [comment]
We don't accept bug reports for anything older than the latest Canary.
