### ISSUE TITLE
Flashing magisk on Unisoc SC9863A tablet does not start

### ISSUE THREAD

**Issue by GalaxyNight** [topjohnwu/Magisk#2866]
I flashed magisk20.4.zip from TWRP, but after that I can't start it and it stops at the boot logo.

Devices: bootloader unlocked Teclast P80X
(I used Google Translate. I'm sorry if I've made you feel uncomfortable.)

**Comment by lpn418** [comment]
I flashed magisk20.4.zip from TWRP, but after Second reboot, I can't start it and it stops at the boot logo.
Xiaomi Mi Mix 2，Havoc-OS-3.5 and AICP 15.0 rom
so i uninstall magisk20.4，its working fine.

**Comment by osm0sis** [comment]
@lpn418 do not hijack issues that aren't for your device.

**Comment by alhasan8** [comment]
How to unlock Unisoc Sc9863a Bootloader please help me . 
I know how to use adb and fastboot...but I can't  unlock Bootloader of my phone. 
 Help 
8basshz@gmail.com 
please

**Comment by osm0sis** [comment]
This is not the place. Go to xda or FreakTab

**Comment by mocarela** [comment]
Has been anything done here? I have the same problem with Teclast P80X (G5K8) with all Magisk versions that I had a chance to put my hands on.

**Comment by Homi74** [comment]
> Has been anything done here? I have the same problem with Teclast P80X (G5K8) with all Magisk versions that I had a chance to put my hands on.

Patched boot.img must be signed, otherwise the system will not boot, maybe try:
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
