### ISSUE TITLE
Bootloop in Redmi Note 5 - Miui v20.6.4

### ISSUE THREAD

**Issue by CassiusBrandhuber** [topjohnwu/Magisk#2868]
I installed Miui v20.5.28, and then I Installed Magisk v20.4 -> Everything is ok.
With new version of Miui v.20.6.4 I can't do same thing. I installed the new version of Miui system and all works very well, but if I install Magisk v20.4, boot remains in boolloop.

**Comment by Fox2Code** [comment]
Please try the following:
- Disables all modules  
- Install latest Magisk Canary debug
- Provides `magisk.log` and `logcat` if the problem is still not resolved

It's really hard for Magisk devs to know where your problem came from if you don't give enough information

**Comment by CassiusBrandhuber** [comment]
I disabled all modules and change to Magisk Canary debug. I reinstalled Miui v20.6.4 and Magisk v20.4. Now everything is ok again. 
Thanks.
