### ISSUE TITLE
Xiaomi Mi 9T Recovery bootloop after magisk flash

### ISSUE THREAD

**Issue by xVIulian** [topjohnwu/Magisk#2869]
So, I bought like 5 days ago a brand new Xiaomi Mi 9T, and yesterday I tried to unlock the bootloader, and it worked, then I installed twrp and it still booted up... but when I flashed magisk it just kept on reboting into twrp... then I uninstalled magisk but it still wasnt booting into android! I then tried to install again the rom, thinking that at this point I had a corrupted rom... but still nothing.. it just wont boot... then, big mistake I made, I literally cleaned everything... now my pc doesnt even recognize the phone properly and I cant send file to the phone anymore... what can I do to fix my phone...

**Comment by osm0sis** [comment]
That's a pretty unfortunate series of events.. likely all you had to do was backup your boot partition in TWRP before install Magisk and then restore that after you encountered issues.. Magisk might even work flashed on the recovery partition instead.

You'll likely need to contact Xiaomi to recover your device from its current state, unless you can find an MSM tool for your device on xda similar to what OnePlus does for their devices.
