### ISSUE TITLE
P10 android Pie touch issues  stilll with magisk 20

### ISSUE THREAD

**Issue by bernie99899** [topjohnwu/Magisk#2870]
vtr-l29    9.01.185 c432E1R1P9 

Without root,  touch screen works fine.

After rooting with MAGISK 20 touchscreen does not work at extreme left and right borders for all height display. If I uninstall root it works fine again.
The only way to solve the matter is to stop aptouch from terminal root shell.

terminal
su
stop aptouch

It is annoying.

Anyone found a workaround??

**Comment by osm0sis** [comment]
That's not something Magisk can be directly responsible for, nor can it work around something weird and device-specific like that, you'll have to ask in your device forums.
