### ISSUE TITLE
OnePlus 5T bootloop after flashing Magisk 20.4

### ISSUE THREAD

**Issue by scrouthtv** [topjohnwu/Magisk#2871]
Excuse me if this is the wrong place to ask, but I'm having problems installing Magisk to my OnePlus 5T.

I yesterday updated the phone to Android 10 using an image provided by OP. Then I installed the correct TWRP image and booted into it. I double-checked that it would not be overridden by the OEM recovery and then flashed Magisk 20.4 from GitHub's releases page and cleared Cache & Dalvik. I then tried booting into system but it's just showing the Boot Animation for 20 minutes now.

If I uninstall Magisk everything works again.

One more thing to note:
If I open a Terminal in TWRP (with & without Magisk installed) I get an error upon every new line:
```
dumpling:/ # any command
Linker: WARNING: couldn't read "/system/etc/ld.config.txt" for /sbin/toybox" (using default configuration instead): error reading file "/system/etc/ld.config.txt": Too many symbolic link encountered
WARNING: Linker: Warning: couldn't read "/system/etc/ld.config.txt" for /sbin/toybox" (using default configuration instead): error reading file "/system/etc/ld.config.txt": Too many symbolic link encountered
```
I guess  this results from some old Magisk modules I had installed before upgrading to Android 10 although I'm not sure.

[Someone](https://www.reddit.com/r/essential/comments/97r01q/bootloop_after_installing_magisk/e4b119u?utm_source=share&utm_medium=web2x) suggested
> to reflash the stock (or stock'ish) boot.img file

but I don't have any `boot.img`

How can I provide further logs to solve this issue or where can I get additional help?
Thanks in advance

**Comment by osm0sis** [comment]
Magisk has nothing to do with TWRP. TWRP bugs are their own. You can get the stock boot.img from Magisk's backup in /data, or reflash the Full OTA you used to update in the first place.

Did you try with the latest Magisk Canary?

**Comment by osm0sis** [comment]
No issues on my 5T with latest Android 10 stable from OnePlus, latest codeworkx TWRP, and latest Magisk Canary.

You'll need to check your install instructions on xda and try again.
