### ISSUE TITLE
Magisk 20.4 (20400) dont install OnePlus 7 PRO OOS 10.0.6

### ISSUE THREAD

**Issue by mkl81** [topjohnwu/Magisk#2876]
Hello,
I had a problem this morning when I woke up ...

I have one bootloop, 

I did the update 10.0.6GM21BA, 2 days ago, without problem.

magisk no longer want to install by twrp and magisk manager.
![Screenshot_20200612-114429](https://user-images.githubusercontent.com/65773460/84489578-301b5b00-aca2-11ea-85e3-8d285d94209f.jpg)
![Screenshot_20200612-114405](https://user-images.githubusercontent.com/65773460/84489580-314c8800-aca2-11ea-85a1-b1fa9a87d0a3.jpg)

I had to reinstall the boot oem by twrp, (advanced ➡️ fix recovery bootloop⏩)
![Screenshot_2020-06-12-05-21-16__01](https://user-images.githubusercontent.com/65773460/84493442-0bc27d00-aca8-11ea-92ce-eed992081a58.png)

To solve  the bootloop, but not magisk 😭

Thank😉,

**Comment by osm0sis** [comment]
Use the latest Canary.

**Comment by mkl81** [comment]
OK, thanks. I will look at it
