### ISSUE TITLE
Can't install Magisk

### ISSUE THREAD

**Issue by Valentin9377** [topjohnwu/Magisk#2881]
My phone is Samsung A30s (SM-A307FN)
Stock firmware downloaded (Latest Android 10 for my country). Moved the whole AP.tar to smartphone, open Magisk app then hit Install>Install>Select and patch a file. Copy recompiled file to PC. Flash stock BL, stock CP, stock HOME_CSC and the magisk_patched.tar AP. Then factory reset - done. 
Beside that now is written "The phone is not running Samsung official software" nothing changed. I installed by myself Magisk, opened and still remains "Magisk is not installed". 
These are my [boot.img](https://drive.google.com/file/d/1vQDF0MfT70LugRIQkFkrNEv2eXGG68y3/view?usp=sharing), [recovery.img](https://drive.google.com/file/d/1aIrxUBVNvNhhg9y7JWvLOXtveLJaZzcO/view?usp=sharing), [vbmeta.img](https://drive.google.com/file/d/1xwW4JU2f9j2RJQLkWlKh9jZUzV6miQqh/view?usp=sharing).

**Comment by Robertroll** [comment]
You must first extract the boot.img file from AP.tar, then copy boot.img to your phone. Finally select and patch boot.img with Magisk Manager.

Note: You may need to convert boot.lz4 to boot.img. In such case, you can follow this step to do it automatically from Windows: https://youtu.be/YCBUPmxB24s

**Comment by Valentin9377** [comment]
I already extracted boot.img.lz4 with 7-Zip-zstd. I patched also only boot.img file and then make it compress as .lz4, and then again as .tar for ODIN. But when I press start is look like begin flashing and then ODIN close by himself. But when I flash the whol AP.tar is not doing like this.
