### ISSUE TITLE
Recovery bootloop after installed magisk to recovery

### ISSUE THREAD

**Issue by CoREse** [topjohnwu/Magisk#2882]
My Xiaomi 9SE flashed magisk with twrp(3.3 and 3.4, both tried) after upgraded to android 10(MIUI 12.0), and then, without holding volume up, it goes straightly to recovery instead of boot partition.
I flashed boot partition and the MIUI 12 afterwards, it still remains.
Of course, I can boot into my system with magisk, if I have the magisked-twrp installed, but if I change the twrp with magisk-free one, recovery(twrp) is what I can only get. It seems like magisk changed my bootloader default behaviour somehow. I wonder why and how can I fix it? Thank you!

**Comment by CoREse** [comment]
the version of the magisk is the LATEST of course.

**Comment by osm0sis** [comment]
The kernel is patched to boot the ramdisk in the boot.img, this is normal behavior. Either reflash stock boot.img and reinstall TWRP, or, go into TWRP advanced and run the "fix recovery bootloop" option.
