### ISSUE TITLE
Pixel 3XL Android 11 Beta 1 - patched boot.img not working

### ISSUE THREAD

**Issue by kafisc1** [topjohnwu/Magisk#2886]
Hi together,

Root with the latest Magisk Canary (284) is not working on the Pixel 3 XL on Android 11 Beta 1 (crosshatch-rpb1.200504.018-factory-fbe094a6).
I did try to patch the boot.img and flashed it afterwards, but I'm stuck on boot animation.
I've reverted back on the original unpached boot.img for now.

Device: Pixel 3 XL
Version: Magisk Manager Canary 87de0e7a (284)  (9)
Android Version: Android 11 Beta 1 (crosshatch-rpb1.200504.018-factory-fbe094a6

Unpatched original boot.img: 
https://www.file-upload.net/download-14141871/boot.img.html

Magisk patched magisk_patched.img: 
https://www.file-upload.net/download-14141863/magisk_patched.img.html

**Comment by osm0sis** [comment]
topjohnwu's 3 XL and MishaalRahman's 3a XL were both rooted without issue on Android 11 Beta 1, so I'm sorry but the issue isn't on Magisk's side.
