### ISSUE TITLE
Can't hide app 🏦 bank

### ISSUE THREAD

**Issue by NaderKabir** [topjohnwu/Magisk#2888]
Can't bank app for don't rooted?

My is rooted but don't working app bank because is rooted I want hide app in Magisk Manager ver 20.4 ? Please help me 
![Screenshot_20200615-233838](https://user-images.githubusercontent.com/25882967/84677499-633f4200-af61-11ea-8d89-0884dd0478dd.jpg)
![Screenshot_20200615-233754](https://user-images.githubusercontent.com/25882967/84677504-65090580-af61-11ea-9bfa-248754a81244.jpg)

**Comment by osm0sis** [comment]
Read the manual.

**Comment by NaderKabir** [comment]
Thank you, but where is link manual?
