### ISSUE TITLE
Can't use bank app ? Error

### ISSUE THREAD

**Issue by NaderKabir** [topjohnwu/Magisk#2889]
Can't use bank app ?

My is rooted but don't working app bank because is rooted I want hide app in #Magisk Manager ver 20.4 ? Please help me  OnePlus 6 Android 10
![Screenshot_20200615-234013](https://user-images.githubusercontent.com/25882967/84677950-01330c80-af62-11ea-95a1-05f31ffd16bf.jpg)
![Screenshot_20200615-233838](https://user-images.githubusercontent.com/25882967/84677956-02643980-af62-11ea-8e12-93fb6e2eb87f.jpg)
![Uploading Screenshot_20200615-233754.jpg…]()

**Comment by osm0sis** [comment]
Pretty entitled of you creating multiple issues when you clearly haven't even read the instructions to know how to use MagiskHide.

Stop. Ask on xda if you're still having trouble.

**Comment by NaderKabir** [comment]
I give massage for help me No play
