### ISSUE TITLE
Android 11 Beta 1.5 Failure

### ISSUE THREAD

**Issue by Charaktor** [topjohnwu/Magisk#2892]
Hey there,

I tried updating my Pixel 4 via OTA to latest Beta 1.5 as usual.
After patching the inactive slot in Magisk Manager and rebooting my device, I still am in the same old slot. The Android updater stated that there is an failure and I should try it again. 
So I went other way and installed the new factory.img via fastboot (without -w) and flashed the patched boot.img afterwards. I could not boot into the OS. Fastboot opens on device and tells 'no valid boot slot available'. 
It looks to me like the latest minor Beta update added an new check or something similiar for boot images or something changed in the boot image, which magisk has to adapt. 

Has anybody tried updating and patching latest Android 11 Beta 1.5 on Pixel 4 and can prove me wrong or right?

Thanks in advance

EDIT: Just flashing the factory image without patched boot image works just fine. But magisk is missing.
EDIT2: Nvm. After fully booted OS without patched boot image and flashing patched image again via fastboot (just flash boot ; w/o boot_a or boot_b) it just worked fine. 
Issue can be closed, Sorry for inconvenience.

**Comment by Fox2Code** [comment]
Tou can close an issue you created by clicking on `Comment and Close` or `Close issue` in the bottom of the github page under the comment text box

**Comment by AndroidDeveloperLB** [comment]
You succeeded flashing patched boot file of Android 11 beta 1.5 on Pixel 4?
How ?
When I tried it, it stayed on the same screen, not allowing me to boot into the OS.
I tried it twice already.
To finally be able to boot into the the OS, I had to re-flash the entire firmware (without wipe).

**Comment by Charaktor** [comment]
I needed to setup my phone again from scratch and now the problem is back again. Doesn't matter what i try, everytime after I flash the patched boot img it wont boot up completely and reboots to bootloader menu with status 'no valid slot to boot'.
Is there any help?

**Comment by osm0sis** [comment]
That doesn't sound related to Magisk itself, you likely need to mark the slots good again.

**Comment by Charaktor** [comment]
How do I mark slots valid again?
As soon as I flash just the original boot.img again it boots up just fine.
I patched the boot.img in latest magisk manager canary, is there anything else I have to consider to get a possibly working patched magisk boot img?

**Comment by osm0sis** [comment]
Hmm as far as I know that's it. I'll ask @topjohnwu to confirm if R 1.5 is working on his device.

**Comment by osm0sis** [comment]
@topjohnwu reported: "Yes indeed, OTA does not work on latest Pixels, however a factory flash will fix it"

**Comment by Charaktor** [comment]
> @topjohnwu responded: "Yes indeed, OTA does not work on latest Pixels, however a factory flash will fix it"

Thanks for clearing things up.
