### ISSUE TITLE
Magisk Manager is detected even with random the packagename, but...

### ISSUE THREAD

**Issue by DeicPro** [topjohnwu/Magisk#2894]
The last version of this app detect Magisk Manager
https://www.apkmirror.com/apk/bankia/bankia/bankia-20-1-7-release/

Seems this app detects the job of Magisk Manager process or something and crash and open again showing error message by the developers. If you uninstall it then pass, even if only delete the apk in /data/app it pass too. The only way to keep Magisk Manager and pass in that app is moving Magisk Manager with random packagename to /system, so as a system app.

Explained easily:
Magisk Manager is user app = detected
Magisk Manager random is user app = detected
Magisk Manager is system app = detected
Magisk Manager random is system app = pass

More people is facing this, I installed that app only to try and confirm it. I didn't find nothing interesting in logcat, only crashes but without relevant information I guess.

**Comment by osm0sis** [comment]
#1152

**Comment by DeicPro** [comment]
I follow Magisk Hide practices perfectly, try the app and you will see. In previous versions of that app had been no problems with detection.

**Comment by DeicPro** [comment]
@osm0sis Doing a better research I found this app uses IBM Trusteer as anti-root solution, I was suspicius when see in the changelog, but I didn't search enough. Here there is some info (outdated I guess): https://mobilefirstplatform.ibmcloud.com/tutorials/en/product-integration/6.3/trusteer-android/

**Comment by DeicPro** [comment]
REPEAT, it is only with this app!! Everyone with this app in the 20.1.7 version is facing this detect problem, because they update to a better anti-root method and detect Magisk Manager in the ways I wrote in OP.
