### ISSUE TITLE
Pixel 2 Android R Can't hide Magisk Manager

### ISSUE THREAD

**Issue by bluehomewu** [topjohnwu/Magisk#2895]
![Screenshot_20200619-105823](https://user-images.githubusercontent.com/56945729/85092303-fdcaaa00-b21b-11ea-9122-07739d8c55aa.png)

![Screenshot_20200619-110104](https://user-images.githubusercontent.com/56945729/85092451-513cf800-b21c-11ea-8999-7850a3a434fc.png)

I try to change SELinux or clean cache,but not work.

[Here's the log with Magisk](https://drive.google.com/file/d/1-3tl_O6FqtJJYNhJx2zAIig6FpjH-gvK/view?usp=drivesdk)

**Comment by Fox2Code** [comment]
You send `magisk.log` but we need a `logcat`
The logs you send are only Magisk native part logs but these logs don't contain the application logs.
We need a logcat via `adb logcat` to be able to know why the hiding didn't work

**Comment by Didgeridoohan** [comment]
I'm going to guess it's Play Protect (it's usually that or selinux).
https://www.didgeridoohan.com/magisk/Magisk#hn_Cant_hide_the_Magisk_Manager

**Comment by Fox2Code** [comment]
Hum if it's Play Protect that block install we might need to use root to force install the APK.
However, we still need a `logcat` to see if it's really PlayProtect or not and how to fix the issue.
Please provide more information so we can fix the issue.

**Comment by bluehomewu** [comment]
> You send `magisk.log` but we need a `logcat`
> The logs you send are only Magisk native part logs but these logs don't contain the application logs.
> We need a logcat via `adb logcat` to be able to know why the hiding didn't work

OK.I will get logcat tomorrow.
Also I will try to disable play Protect  and hide it again.

**Comment by bluehomewu** [comment]
> Hum if it's Play Protect that block install we might need to use root to force install the APK.
> However, we still need a `logcat` to see if it's really PlayProtect or not and how to fix the issue.
> Please provide more information so we can fix the issue.

Yes!!!!
After I disable Play Protect it can hide it now.
Don't need to change SELinux status.
Thanks a lot.
I will close this issue.

**Comment by Didgeridoohan** [comment]
The Manager has root. That's kind of what it does... And generally it already circumvents Play Protect, but it seems like it doesn't always work.

The solution is simple though (if it is PP): disable Play Protect, hide Manager, enable Play Protect.
