### ISSUE TITLE
is there a solution to restore the fingerprint back on trt-l21a (huawei  y7 prime 2017 ) ?  

### ISSUE THREAD

**Issue by RealMahmoud** [topjohnwu/Magisk#2897]
hello .. i am facing that after installing magisk on trt-l21a  the fingerprints settings gets hidden and the fingerprint no longer work .. is there a solution for this ?? ( trt-l21a) huawei y7 prime 2017

**Comment by osm0sis** [comment]
You need to ask in your device forum on xda.
