### ISSUE TITLE
Manager crashing when performing "Direct Install"

### ISSUE THREAD

**Issue by Displax** [topjohnwu/Magisk#2898]
Latest canary 0850bca9 
Log is here.

[log.txt](https://github.com/topjohnwu/Magisk/files/4807884/log.txt)

**Comment by Fox2Code** [comment]
I see:
```
java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)
```
I literaly got and fixed this error for a Minecraft project I made 
I Will fix this error soon because I know exactly how to fix it

**Comment by Fox2Code** [comment]
Done!
