### ISSUE TITLE
Filter button covers Magisk Hide toggle buttons

### ISSUE THREAD

**Issue by Jon8RFC** [topjohnwu/Magisk#2903]
Android 10 June 2020 update Pixel 4 with 3-button navigation enabled.

It gave me the impression that I needed the toggle to be visually available:
https://imgur.com/a/wgRYzJR

The downloads section allows for scrolling past the filter button, so it doesn't have the issue:
https://imgur.com/a/4kJUOOo

**Comment by osm0sis** [comment]
Yep, definitely a problem.

@diareuse, looks like the same fix for modules of adding a little extra space at the bottom of the list just needs to be applied to the MagiskHide list. :+1:
