### ISSUE TITLE
use the boot.img and recovery.img patch method on the MT6771 bootloop

### ISSUE THREAD

**Issue by 01soni247** [topjohnwu/Magisk#2904]
use the boot.img and recovery.img patch method on the MT6771 bootloop (Android 10),Before on Android 9 that didn't happen
This device has no custom recovery
Patch Magisk : https://drive.google.com/file/d/167DA22aKVL117b6sXg6IMcNrhcfAjP4s/view?usp=drivesdk
Stock 
https://drive.google.com/file/d/16ifR4ZmabGcf-DoNPHhA8uX8F9P50-7E/view?usp=drivesdk

**Comment by osm0sis** [comment]
#2695
