### ISSUE TITLE
App keeps getting denied root access

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [topjohnwu/Magisk#2906]
Magisk Version: 20.4
Manager Version: 7.5.1

When an app is requesting root access, Magisk automatically denies the app access without prompting me, even though my settings are to prompt me. Root works for other apps, and this app doesn't even show up in the Superuser menu to manually allow. Log just says denied.

The app is [Naptime](https://play.google.com/store/apps/details?id=com.franco.doze)

**Comment by Fox2Code** [comment]
Please test with the latest version of Magisk Canary and provide logs if it's doesn't work.
The Android version of your phone would be helpful too.
Thanks

**Comment by ThatNerdyPikachu** [comment]
Persists on Canary, Android 10 June 2020 security patch.

Have tried clearing Manager data, to no avail.

**Comment by ThatNerdyPikachu** [comment]
Fixed by wiping permission table in magisk database, probably not best solution, but it worked.

**Comment by osm0sis** [comment]
Sounds like your db got weird somehow.. unfortunately too rare an issue to figure out. Let us know if it happens again with some reliable way to reproduce. :+1:

**Comment by ffransa** [comment]
> Fixed by wiping permission table in magisk database, probably not best solution, but it worked.

hi, i really need this apk. can you share with me?

**Comment by ffransa** [comment]
> Fixed by wiping permission table in magisk database, probably not best solution, but it worked.

please let me know about this, i really need this.
