### ISSUE TITLE
adb device shows status "unauthorized"

### ISSUE THREAD

**Issue by deathrattle666** [topjohnwu/Magisk#2912]
I installed the latest canary (0850bca9 - 20416) as well as the current stable 20.4 version of magisk via recovery mode on my device Xiaomi Note 5 Pro "whyred". Unfortunately as soon as I install magisk, the status of adb device changes to "unauthorized". 
I am currently on android 10 with crdroid rom v6.7.

**Comment by topjohnwu** [comment]
The rom is using unrestricted ADBD which is tied to certain system props. Disable magiskhide and reboot will fix the issue

**Comment by deathrattle666** [comment]
Thanks a lot! That worked. You made me very happy! Thanks again!
