### ISSUE TITLE
Can not repaire boot.img

### ISSUE THREAD

**Issue by darkgirl** [topjohnwu/Magisk#2913]
Hi,
after I installed magisk 7.5.1, I want to repaire my boot.img
but after choose the image file, it did not show the repaire widget.

my system is android 8.1.0, and I did not find any log file in /android/data/com.xxx.magisk/
and I had checked the ready and write perimission is ok

so where can I find the log file or what should I do to provide more information?

thanks.

**Comment by darkgirl** [comment]
????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by linuxandria** [comment]
> Hi,
> after I installed magisk 7.5.1, I want to repaire my boot.img
> but after choose the image file, it did not show the repaire widget.
> 
> my system is android 8.1.0, and I did not find any log file in /android/data/com.xxx.magisk/
> and I had checked the ready and write perimission is ok
> 
> so where can I find the log file or what should I do to provide more information?
> 
> thanks.

FYI, if you can't search around enough and put in the effort to figure out how to grab logs John isn't going to help you 😉
