### ISSUE TITLE
Can't bypass Secure Check Fail Screen on SM-A207F

### ISSUE THREAD

**Issue by soum91** [topjohnwu/Magisk#2917]
I am trying to flash magisk on my Samsung SM-A207F on Android 10 following [this](https://topjohnwu.github.io/Magisk/install.html) instruction. But after flashing the patched AP file I can't boot into stock recovery to Wipe data/factory reset at step 10. As soon as I press **Volume Down + Power** to escape Download Mode and press **Volume Up + Power**, it takes me to **Secure Check Fail** screen, no matter how many times I try. I even tried patching only Boot.img that too results in the same error. I have used Magisk 20.4. Can anyone tell how to fix this or what am I doing wrong?

**Comment by linuxandria** [comment]
> I am trying to flash magisk on my Samsung SM-A207F on Android 10 following [this](https://topjohnwu.github.io/Magisk/install.html) instruction. But after flashing the patched AP file I can't boot into stock recovery to Wipe data/factory reset at step 10. As soon as I press **Volume Down + Power** to escape Download Mode and press **Volume Up + Power**, it takes me to **Secure Check Fail** screen, no matter how many times I try. I even tried patching only Boot.img that too results in the same error. I have used Magisk 20.4. Can anyone tell how to fix this or what am I doing wrong?

Sounds like you didn't properly unlock your bootloader to me

**Comment by soum91** [comment]
> > I am trying to flash magisk on my Samsung SM-A207F on Android 10 following [this](https://topjohnwu.github.io/Magisk/install.html) instruction. But after flashing the patched AP file I can't boot into stock recovery to Wipe data/factory reset at step 10. As soon as I press **Volume Down + Power** to escape Download Mode and press **Volume Up + Power**, it takes me to **Secure Check Fail** screen, no matter how many times I try. I even tried patching only Boot.img that too results in the same error. I have used Magisk 20.4. Can anyone tell how to fix this or what am I doing wrong?
> 
> Sounds like you didn't properly unlock your bootloader to me

Not really. I have
![properly](https://user-images.githubusercontent.com/3830681/85872467-9ac7ad00-b7f1-11ea-93c7-f6d6d63dcf70.png)
 unlocked bootloader to my knowledge.

**Comment by Fox2Code** [comment]
@soum91 Seems like a bootloader unlock issue and more a problem on the Samsung side than on Magisk side
But if you still think it's a Magisk issue you can still send the original boot image and the patched one
(Don't forget we only accept helping to fix issues from canary version that you can get [here](https://github.com/topjohnwu/magisk_files/tree/canary))

**Comment by soum91** [comment]
@Fox2Code, I too think this is being caused by some new mitigation to prevent any modification by Samsung on Android 10 [this](https://user-images.githubusercontent.com/3830681/85916601-2bdf6800-b874-11ea-85a0-b49a4f938ce5.png). Because any kind of modification to stock recovery or boot is causing this. BTW, I haven't tried with Canary version, tried using latest stable release. 
Still attaching stock boot and patched one here. Will give a try using canary version shortly. 

Attachments:
1. [Stock boot img](https://github.com/topjohnwu/Magisk/files/4840076/boot.img.zip)
2. [Patched img](https://github.com/topjohnwu/Magisk/files/4840082/magisk_patched.tar.zip)

**Comment by soum91** [comment]
Nope, same result with Canary version too!

**Comment by osm0sis** [comment]
This sounds like the same as #2272. Add your info there.

**Comment by gokaybiz** [comment]
I have same issue with SM-T297 device.
`SECURE CHECK FAIL : recovery.img`
