### ISSUE TITLE
Magisk is unable to patch Samsung Galaxy A8 Tab 2019 Wifi Only( SM-T290 ) 

### ISSUE THREAD

**Issue by Navneet-Kumar-Singh** [topjohnwu/Magisk#2923]
My device is non A/B  and is System-as-Root. 
Tried all possible ways but the same error is coming :

The device in download mode reports: "`SECURE CHECK FAIL : vbmeta"

And at the same time Odin reports " Complete (Write) operation failed "
Even when I used a original, non patched version of Odin same output came on my Samsung tablet.

![part1](https://user-images.githubusercontent.com/32897976/85923001-4e2ab300-b87f-11ea-8a70-852048c4772a.png)
![part2](https://user-images.githubusercontent.com/32897976/85923004-5256d080-b87f-11ea-8052-62d6eeebfd63.png)

Also I noticed that Magisk patches the vbmeta.img.lz4 also along with boot.img.lz4

**Comment by Navneet-Kumar-Singh** [comment]
Please help me

**Comment by Navneet-Kumar-Singh** [comment]
Help man, please........ topjohnwu ?

**Comment by 5c0tt1** [comment]
Naveet, please be patient, the devs **will** see this, and reply **when** available.

**Comment by osm0sis** [comment]
Same issue as #2272. Add your info there.

**Comment by Navneet-Kumar-Singh** [comment]
sorry for being impatient . i will wait now

**Comment by Navneet-Kumar-Singh** [comment]
> Naveet, please be patient, the devs **will** see this, and reply **when** available.

sorry for being impatient . i will wait now . but i love magisk and use it on my all devices . so i am being impatient as this type of error came for the first time on any of my devices . i thought magisk would definitely work on any Samsung device .

**Comment by blue-pine** [comment]
> Naveet, please be patient, the devs **will** see this, and reply **when** available.

Can you please delete this comment and and also from its edit history ?

**Comment by blue-pine** [comment]
@topjohnwu Can you please delete this message: " https://github.com/topjohnwu/Magisk/issues/2923#issuecomment-650560333 " , or this issue: " https://github.com/topjohnwu/Magisk/issues/2923#top " which was opened/created by me, because it has my sensitive info which I can't delete myself . Please
