### ISSUE TITLE
Patched Boot Ouput Format missing in latest update (v.7.5.1(267))

### ISSUE THREAD

**Issue by jmespiswini** [topjohnwu/Magisk#2924]
Hello. I'm new to this and I have a Samsung Galaxy J7+ (SM-C710F) device. I'm trying to flash the patched img file by magisk. The problem is I'm trying to flash it via adb but it won't work. I searched online so I used odin but the problem is the boot file is an img and odin won't flash it. It needs to be a .tar file. There is no option on magisk manager to make the file .tar instead of .img. I downloaded old version of magisk manager and saw that there is an option where I can select if I want the file to be .img or .img.tar but the problem is I can't install/flash because the old version that I downloaded always forces me to update to the new version.

English is not my first language and I just translated this using google translate, please excuse any wrong grammars.

Thank you

**Comment by Gusted** [comment]
You probably tried to patch a boot.img file that's why it's output a img. You need a .tar of your boot image and patch that and than flash that.
