### ISSUE TITLE
Latest Canary  Magisk Manager Module list didn't work.

### ISSUE THREAD

**Issue by bluehomewu** [topjohnwu/Magisk#2926]
[Here is the Magisk Manager log](https://drive.google.com/file/d/11dJ22AFSluQBbvnv-RSE7qqEsmluq4nQ/view?usp=drivesdk)

Module list can't show module,but module still working.

![Screenshot_20200628-235353](https://user-images.githubusercontent.com/56945729/85952313-f41f1000-b99a-11ea-9613-1067078b3698.png)
![Screenshot_20200628-235358](https://user-images.githubusercontent.com/56945729/85952316-f84b2d80-b99a-11ea-8960-367bc5a5116e.png)
![Screenshot_20200628-235439](https://user-images.githubusercontent.com/56945729/85952319-fc774b00-b99a-11ea-9591-3ba9dd7143b8.png)

**Comment by Navneet-Kumar-Singh** [comment]
Are you using a different Magisk Manager,  as your ui is different?

**Comment by bluehomewu** [comment]
> 由於您的用戶界面不同，您使用的是其他Magisk Manager嗎？



> Are you using a different Magisk Manager, as your ui is different?

I'm using official canary version Manager.
Not unofficially Manager.

**Comment by Shenron0** [comment]
Latest canary manager doesn't show your installed modules but log shows that they are installed. The only downside is you can't turn off/on modules but you can uninstall/install them if you flash the modules themselves

**Comment by martyfender** [comment]
I have the same issue on my Onn 8 Android 9 tablet with 20417.
[magisk_log_20200628_141656.log](https://github.com/topjohnwu/Magisk/files/4842788/magisk_log_20200628_141656.log)

**Comment by xerta555** [comment]
Same problem on my side.

I have update the Manager before updating Magisk. After this update, my modules list have diseppear.
And even after updating Magisk through the Manager, i had to force it 3 times, the 2 first times the Manager displayed "Download finished" (translated from French). I had to force-stop the Manager app (resurection remix default feature use am command), and specified no special install option and direct install.

Even after having reboot, my modules list always don't appear, but i know that the modules are enabled bcz the features provided by my modules continue to works.

**Comment by osm0sis** [comment]
Yep, confirmed issue in Canary Manager 286. Downgraded to 285 and all works again.

**Comment by xerta555** [comment]
> Certainly a noob question, but is it possible to downgrading though the Manager app and staying on Canary channel ? Or i must flash the zip through TWRP ?

**Comment by Shenron0** [comment]
@xerta555 that is indeed a noob question that doesn't need to be answered but I'll do it anyway to spare others. You can downgrade to the previous version  of the manager if you still have the APK or the magisk.zip by opening the zip and search for the APK inside it and yes you have to uninstall the current version you already have installed. But make sure Magisk Manager is not hidden and restored to normal without it being renamed

**Comment by osm0sis** [comment]
If you've got it hidden with the stub then you can go find the user_de directory for the hidden Manager and drop 285 into the dyn subdirectory as current.apk remembering to fix the ownership and perms like the one you're replacing. :wink:

**Comment by zgfg** [comment]
How to roll-back to Manager 285 (if you didn't have its apk downloaded) upon upgrading to Canary 286/20417:
https://forum.xda-developers.com/showpost.php?p=82944427&postcount=40410

And how to hide Manager then, keeping 285:
https://forum.xda-developers.com/showpost.php?p=82946185&postcount=40421

But hoping for quick fix and release of new Manager 287 🤩

**Comment by toyassir** [comment]
I am having issues with 285 and 286. Somehow it has connectivity issues (fails to hide manager, can not download safteynet stuff or modules and it shows loading... when checking for new versions). When I downgraded to 284 everything works but hiding it will reload the latest version 286.
![SmartSelect_20200629-084427](https://user-images.githubusercontent.com/63518354/85977242-e55d4b00-b9e4-11ea-8ded-e21c2d9f37fd.jpg)

**Comment by topjohnwu** [comment]
Fixed b1e0c5ff38a61d487a3a7dc3a6ca32e44fcf1f29
