### ISSUE TITLE
help bro in this err

### ISSUE THREAD

**Issue by almajroh** [topjohnwu/Magisk#2927]
@topjohnwu 
Hi bro .
The magisk Verification error in SaftyNet
When using EdXposed with hidden core, verification succeeds, verification succeeds in magisk and saftyNet test, but Google Play detects a malfunction, even if you wipe data and after using the phone for hours, programs will not run in the background, such as WhatsApp and others, so it answers the program entry to receive messages

my phone is :

Note 9 SM-N969F
ANDROID 10

I tried all the solutions in the internet

**Comment by osm0sis** [comment]
#1152

**Comment by almajroh** [comment]
> #1152

 hi bro
Can you explain me a little? plz
