### ISSUE TITLE
Magisk Manager does not update as it should if you minimize it during the download

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#2929]
If you put Magisk Manager to update and then minimize the app to use another one, for example if you have a bad internet connection and you don't want to wait on the screen, when you go back to Magisk Manager it doesn't start installing the update automatically and if you click on the notification of the completed download, the apk is opened by the standard package installer. Which is not a problem if you use the Manager with the default package name, but if you have hidden it, the new version is installed as a new app that cannot communicate with Magisk framework

**Comment by hirenshah** [comment]
Same issue when you tap the new update notification. It tries to install the non hidden version. You have to update from within the app for it to update the hidden version.
