### ISSUE TITLE
Latest canary a0b47f3c Manager breaks Recents navigation in R beta

### ISSUE THREAD

**Issue by Gondost** [topjohnwu/Magisk#2931]
I don't have a Magisk log since Magisk Manager runs fine. This affects the "2 Button / Pill" gesture setting, and at least on my Pixel 3.

After installing a0b47f3c Manager, 3rd party launchers don't work correctly with the Recent Apps menu. At minimum, Nova Launcher is affected. From the Home Screen, using the 2 Button navigation, swiping up does not launch the Recents. Once you're in an app, swiping up does launch the Recents, but it loads using the Pixel Launcher view of the Overview, as opposed to the normal one. If you go home from the Pixel Launcher view of Recents, it loads the Pixel Launcher home instead of the default home (which is Nova in my case).

I uninstalled a0b47f3c Manager and reinstalled 3c783448 and my Recents works again as it did before. 3c783448 Manager with a0b47f3c Magisk has no issues.

I don't know where to start on what logs would help identify the problem.

**Comment by topjohnwu** [comment]
Sorry, but this does not make sense. Either some root apps, boot scripts, or modules are the culprit
