### ISSUE TITLE
Magisk Manager does not show that the Magisk update succeeded

### ISSUE THREAD

**Issue by Masrepus** [topjohnwu/Magisk#2932]
I'm on stable Magisk 20400 and just switched from the stable Manager to the current canary version 288, in order to try out the new SafetyNet evalType test. This worked as it should, but now when I wanted to update from stable Magisk to canary 20418 via direct install, the UI got stuck at "Download complete". I expected something similar to the stable Manager behavior, where it stated that the install is done and offered a reboot button. The install itself worked, as a manual reboot showed. So I'm unsure whether "Download complete" is the desired way of notifying the user of a successful installation, but the old way of showing log output during installation felt better

**Comment by topjohnwu** [comment]
It should be, there is a flashing console screen when you do direct installs. Not sure what's wrong here without any further info

**Comment by vintagepc** [comment]
I too am seeing this with 20.4 after an "install to inactive slot" for an OTA update, if that helps.
