### ISSUE TITLE
[Request] Disable Animations option

### ISSUE THREAD

**Issue by Fruity-0** [topjohnwu/Magisk#2933]
After updating Magisk Manager 7.5.1, I have clipping animations of transitions between option cards.
In general, nothing bad is happening but in the system I have everything turned off animations because I value the reaction time and speed of operation without unnecessary trimming.
Is there any way to turn off the animations?

**Comment by osm0sis** [comment]
@diareuse, any way to make the animations optional? Could be a solution for the other animations-related issues as well and could automatically be disabled on older Android.

**Comment by diareuse** [comment]
No, animations cannot be toggled as far as I'm aware. It can be only removed on all devices or kept on every single one of them. Having "if" on every animation would get very quickly very messy.
---
@Fruity-0 I'd like to see a recording of this issue you're describing

**Comment by topjohnwu** [comment]
Closed due to no further interaction
