### ISSUE TITLE
[REQUEST] Import theme file for the Manager

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#2934]
Hi

Since I had asked if it would be possible for me to make a theme for Manager John, John answered: "Not for the moment, when we will have fix all major issues, we'll see".
Now that the biggest bugs have been fixed, would it be possible to add an option to be able to import a local file with the color settings for the Manager?

That would avoid having to add the theme for everyone that would be ideal for me.
Or if John wouldn't mind adding a theme in addition to the ones already proposed...

**Comment by xerta555** [comment]
@topjohnwu @diareuse any news about my request ? :)

**Comment by topjohnwu** [comment]
After evaluating this, unfortunately on Android this is not possible

**Comment by xerta555** [comment]
> After evaluating this, unfortunately on Android this is not possible

Would it be possible that I create another color theme to add to the existing ones in the manager?
Because sincerely I have a bit of lust for creating a substratum theme just for that....
