### ISSUE TITLE
Device lost support after android 10 OK on android 9 and older

### ISSUE THREAD

**Issue by fgl27** [topjohnwu/Magisk#2936]
The [device](https://github.com/fgl27/device_motorola_quark#device-configuration-for-moto-maxx-quark) work well on android 9 and older, but after android 10 it never worked.

Using latest version from release **Magisk v20.4** the magisk manager doesn't recognizes magisk su device boot OK.

Using latest version **20418** the device doesn't finises the boot process.

It also looses adb root, so logcat is limited, I took some logs from **20418**
[logcat.txt](https://github.com/topjohnwu/Magisk/files/4861473/logcat.txt)

Can't run `dmesg` because no SU, but via TWRP I can `cat console-ramoops` AKA `dmesg`
[console-ramoops.txt](https://github.com/topjohnwu/Magisk/files/4861474/console-ramoops.txt)

There is some odd `Unmounting` spaming on dmesg, data and cache are formatted as f2fs don't know if any relation have too many thing on the device data do change it to ext4, but will try it when I have some free time to backup it all.

Anyone has some experience with this issue?

**Comment by osm0sis** [comment]
Yes. Search before you post. #2695

**Comment by fgl27** [comment]
I did but that seems a too broad issue without much help, this seems more specific problem on latest version after all 20.4 boots and didn't work.

Any way I can post there
