### ISSUE TITLE
No service after installing Magisk

### ISSUE THREAD

**Issue by minhducsun2002** [topjohnwu/Magisk#2937]
Magisk version : 
![Screenshot_2020-07-02-08-27-08-115_com topjohnwu magisk](https://user-images.githubusercontent.com/32769878/86306269-02d92180-bc3e-11ea-845f-f53b1d126f14.jpg)

Logcat : 
[logcat_07-02-2020_08-22-59.txt](https://github.com/topjohnwu/Magisk/files/4861484/logcat_07-02-2020_08-22-59.txt)

**Comment by topjohnwu** [comment]
Something is messed up, might be rouge Magisk modules or scripts

**Comment by minhducsun2002** [comment]
Not really. This is a fresh install without modules.
