### ISSUE TITLE
Can't work on XIAOMI 10, Android 11 

### ISSUE THREAD

**Issue by mooseIre** [topjohnwu/Magisk#2938]
I tried canary channel magisk on XIAOMI 10( Android 11 Beta )  and it seemed  can't work  .

The installation process is in order and success.

Download [rom](https://hugeota.d.miui.com/20.6.30/miui_UMI_20.6.30_0d99b1b562_11.0.zip) if necessary

[boot.zip](https://github.com/topjohnwu/Magisk/files/4861645/boot.zip)

![image](https://user-images.githubusercontent.com/48538055/86309809-25276b00-bc4f-11ea-9c61-291d1605baca.jpg)

**Comment by psolyca** [comment]
It is the same as #2910 .
I have the same problem Huawei P9
