### ISSUE TITLE
Automatically translated Strings.xml localization for 30 more languages

### ISSUE THREAD

**Issue by akhilkedia** [topjohnwu/Magisk#2939]
Would you welcome a Pull Request with automatically translated Strings.xml for the following locales? These will be translated using Micrsoft Azure Cloud Translate.

````
["af", "bn", "bs", "cy", "da", "fa", "fi", "fil", "fj", "ga", "gu", "ht", "hu", "is", "kk", "kn", "mg", "mi", "ml", "mr", "ms", "mt", "pa", "sl", "sw", "ta", "te", "to", "ur", "yue"]
````

**Comment by osm0sis** [comment]
If nobody's submitted translations for those then likely there's no need currently.
