### ISSUE TITLE
port xposed failed,  what's the magiskpolicy rules for add xposed service?

### ISSUE THREAD

**Issue by xiangsf** [topjohnwu/Magisk#2943]
I am trying to port xposed to android 9/10,  and build a magisk module。 i got the following error:

E SELinux : avc:  denied  { add } for service=user.xposed.system pid=877 uid=0 scontext=u:r:system_server:s0 tcontext=u:object_r:default_android_service:s0 tclass=service_manager permissive=0
E ServiceManager: add_service('user.xposed.system',6) uid=0 - PERMISSION DENIED

xposed use service user.xposed.system to read/write files.   i add the following magiskpolicy rules, the error remains:

magiskpolicy --live "allow zygote default_android_service service_manager *"
magiskpolicy --live "allow system_server default_android_service service_manager *"
magiskpolicy --live "allow system_server magisk service_manager *"
magiskpolicy --save "allow zygote default_android_service service_manager *"
magiskpolicy --save "allow system_server default_android_service service_manager *"
magiskpolicy --save "allow system_server magisk service_manager *"

environment:
Magisk : 20.4
Device: pix2l
Rom: aosp
Android version: android-9.0.0_r1

**Comment by topjohnwu** [comment]
`magiskpolicy --live "allow system_server default_android_service service_manager add"`
Also, you can add multiple rules in a single command, `magiskpolicy --live "rule 1" "rule 2"`
