### ISSUE TITLE
what if i using microG and remove google play service ?

### ISSUE THREAD

**Issue by almajroh** [topjohnwu/Magisk#2946]
what if i using microG and remove google play service ?
 i can sking saftyNet ???

**Comment by vdbhb59** [comment]
> what if i using microG and remove google play service ?
> i can sking saftyNet ???
Yes, but without GFS on your system, it should not be an issue, as anyways SN is different thing.

**Comment by almajroh** [comment]
> > what if i using microG and remove google play service ?
> > i can sking saftyNet ???
> 
> Yes, but without GFS on your system, it should not be an issue, as anyways SN is different thing.

are you can explan to me more 
 what is GFS
