### ISSUE TITLE
Add support in Magisk Manager to patch boot.img using other versions - TO INCREASE SUPPORT TO EVEN MORE DEVICES,  PLEASE

### ISSUE THREAD

**Issue by Navneet-Kumar-Singh** [topjohnwu/Magisk#2947]
This is absolutely required because:
 1.) Most times new version of magisk cause bootloops, breaks some functionality or even dont flash at all (especially Samsung Galaxy series) , in that case old versions are flashed successfully and work well. The user is unable to make a patched boot.img through Magisk Manager as Magisk Manager always patches boot.img through the latest and not old Magisk version.

 2.)Not every phone has custom recovery build, so they can't just flash old version,especially new 2019 Samsung devices, eg Galaxy A8, Galaxy A10.1 , etc any many more, which are excellent to have root on.

I hope the reader understands my concern and doesn't close this issue.
Please accept my request.......

**Comment by Displax** [comment]
@Navneet-Kumar-Singh You can use custom update channel to patch boot.img any version you want.

**Comment by Navneet-Kumar-Singh** [comment]
> @Navneet-Kumar-Singh You can use custom update channel to patch boot.img any version you want.

I don't know how.

**Comment by vdbhb59** [comment]
> I don't know how.

Just use the old Magisk Manager, and it will work. Although on some Galaxy devices, post the initital reboot from old manager, and then upgrading can cause bootloop, but it should work on most of the galaxy devices. I have tried on around 8-10 different version starting from 20.3 stable to the latest canary.

**Comment by topjohnwu** [comment]
No old versions will be supported, so instead of using an old one, it is better to provide logs to fix issues.
This feature is useful to provide temp fixes to users, so I'll consider it in a future release
