### ISSUE TITLE
No root access on Android 6 devices since build 20415

### ISSUE THREAD

**Issue by martyfender** [topjohnwu/Magisk#2948]
Recent Canary builds have been working great on my Onn 8, Android 9 devices. With my Nextbook Ares 8A, Intel x86, Android 6.0.1 tablets, root access is not available. The last build to work with them was 20415. 
[magisk.log.bak.txt](https://github.com/topjohnwu/Magisk/files/4875641/magisk.log.bak.txt)

[magisk.log](https://github.com/topjohnwu/Magisk/files/4875628/magisk.log)

Maybe due to these and maybe other commits?

https://github.com/topjohnwu/Magisk/commit/ec3705f2ed187863efc34af5415495e1ee7775d2
https://github.com/topjohnwu/Magisk/commit/43146b8316a467cbd7dee0b3afe593a76291918a

**Comment by topjohnwu** [comment]
#2910
