### ISSUE TITLE
Status bar has white-coloured text on light theme

### ISSUE THREAD

**Issue by minhducsun2002** [topjohnwu/Magisk#2949]
The status icons, clock, ... are virtually impossible to see.
Dark theme, however, seems to set a black background, effectively eliminating the issue.
![Screenshot_2020-07-06-10-30-30-773_com topjohnwu magisk](https://user-images.githubusercontent.com/32769878/86553141-13f29d00-bf74-11ea-843f-9d8ca78db8eb.jpg)

**Comment by osm0sis** [comment]
That's your ROM.

**Comment by osm0sis** [comment]
![Screenshot_20200706-114209](https://user-images.githubusercontent.com/2858716/86605965-c0854c80-bf7d-11ea-8e62-3b5e3814de7a.jpg)

**Comment by minhducsun2002** [comment]
I can only say that MIUI always breaks something. Nevertheless, thank you for confirming

**Comment by osm0sis** [comment]
@diareuse, anything else to be done here to help accommodate?

**Comment by diareuse** [comment]
I haven't found a do-it-all "fix" for MIUI. They don't understand that translucent doesn't mean transparent (speaking of API `android:windowTranslucentStatus`) and refuse to fix their status bar color accordingly.

When I find a way to universally (pre)fix this on all devices I'll definitely submit it asap, until then use the dark mode please 🙃
