### ISSUE TITLE
zimperium magisk root detection analysis

### ISSUE THREAD

**Issue by jameshilliard** [topjohnwu/Magisk#2950]
This is a root detection framework used by some banking apps and employs a number of heuristics and appears to detect magisk on my android 10 device running lineageos which passes safetynet.

I've done some analysis and have identified some more info on how it appears to detect root.

This method is specifically designed to detect magisk:

- Iterate though properties using `__system_property_find_nth()`
- call `__system_property_read()` for each property
- check if property starts with `"init.svc."`
- check length of string after the `"init.svc."` prefix is `7`
- check all characters after "init.svc." are alphanumeric using `isalnum()`
- check service state is `"stopped"`

The zimperium detector also appears to run analysis on many filepaths, I haven't done much analysis on these yet but there might be some obvious info leaks that magisk doesn't cover.

I've identified the following proc paths so far as being read by zimperium for analysis:
```
/proc/%d
/proc/%d/
/proc/%d/attr/current
/proc/%d/attr/prev
/proc/%d/cgroup
/proc/%d/cmdline
/proc/%d/comm
/proc/%d/stat
/proc/%d/status
/proc/%d/task
/proc/%d/task/%d/attr/current
/proc/%d/task/%d/stat
/proc/buddyinfo
/proc/diskstats
/proc/loadavg << it tries to read this one a bunch when doing actions in the app that triggers root detection
/proc/meminfo
/proc/net/arp
/proc/net/dev
/proc/net/netstat
/proc/net/route
/proc/net/rt_cache
/proc/net/snmp
/proc/net/snmp6
/proc/net/stat/arp_cache
/proc/net/stat/ndisc_cache
/proc/net/stat/rt_cache
/proc/net/tcp
/proc/net/tcp6
/proc/net/udp
/proc/net/udp6
/proc/net/unix
/proc/net/wireless
/proc/schedstat
/proc/self/maps
/proc/stat
/proc/sys/kernel/pid_max
/proc/uid_stat/
/proc/uptime
/proc/vmstat
```

It seems to use the following data paths for analysis:
```
/data/local/
/data/local/bin/
/data/local/xbin/
/data/data/kingoroot.supersu/files/supersu.cfg
/data/user/%d/kingoroot.supersu/files/supersu.cfg
/data/data/kingoroot.supersu/logs/
/data/user/%d/kingoroot.supersu/logs/
/data/data/kingoroot.supersu/requests/
/data/data/supersu/
/data/data/supersu/system/
/data/data/kingoroot.supersu/connections/
/data/data/kingoroot.supersu/connections/system/
/data/data/kingoroot.supersu
/data/user_de/%d/eu.chainfire.supersu/files/supersu.cfg
/data/user/%d/eu.chainfire.supersu/files/supersu.cfg
/data/data/eu.chainfire.supersu/files/supersu.cfg
/data/user_de/%d/eu.chainfire.supersu/logs/
/data/user/%d/eu.chainfire.supersu/logs/
/data/data/eu.chainfire.supersu/logs/
/data/user_de/0/eu.chainfire.supersu/requests/
/data/data/eu.chainfire.supersu/requests/
/data/data/eu.chainfire.supersu/connections/
/data/data/eu.chainfire.supersu/connections/system/
/data/data/eu.chainfire.supersu
/data/local/tmp/
```

and the following system paths:
```
/system/sd/xbin/
/system/bin/failsafe/
/system/bin/
/system/xbin/
/system/etc/
/system/bin/.ext/
/system/usr/we-need-root/
/system/xbin/supolicy
/system/xbin/su
/system/xbin/ku.sud
/system/bin/su
/system/usr/iku/isu
/system/bin/am
/system/xbin/daemonsu
/system/xbin/sugote
/system/bin/.ext/.su
/system/su.d/
/system/su.d/$i
/system/xbin/daemonsu
/system/xbin/sugote-mksh
/system/bin/%s
/system/bin/toolbox
/system/xbin/sush
/system/bin
/system/framework
/system/lib
/system/vendor/sns/sensors/registry/
/system/vendor/sns/sensors/registry/registry/
/system/vendor/mpt/
/system/vendor/vzw/
```

It looks at these sbin paths:
```
/sbin/
/sbin/adbd
```

and the following dev paths:
```
/dev/.su.d
/dev/.su.d.complete
/dev/socket/su-daemon/
/dev/urandom
/dev/urandom
/dev/random
```

I've identified the following paths being watched using `inotify_add_watch()`:
```
/system/bin
/system/framework
/system/lib
```

**Comment by enovella** [comment]
Any sample APK to help you with the reversing?

**Comment by jameshilliard** [comment]
[This](https://play.google.com/store/apps/details?id=com.chase.sig.android) app uses it.

**Comment by vvb2060** [comment]
https://github.com/vvb2060/MagiskDetector/blob/e8f5b93406666454adb9642460a943b190d6ce03/app/src/main/java/io/github/vvb2060/magiskdetector/MainActivity.java#L149 More accurate deterministic detection method……

**Comment by jawz101** [comment]
I imagine XPrivacyLUA could disable the ability to detect it.   Or Android 11

**Comment by unixandria-xda** [comment]
> I imagine XPrivacyLUA could disable the ability to detect it. Or Android 11

Has anyone tried downloading the shell hooks and using those I'm combination with tracking and identifiers hooks? Might be a stopgap solution unless it checks for memory integrity

**Comment by jawz101** [comment]
there are also a few other community rules that may help as well.  Some mention restricting an app from using certain cat commands

**Comment by topjohnwu** [comment]
Thanks for the details, but if hidden correctly, none of the files you mentioned can be detected.
It might use some other known methods to detect Magisk, I'll "eventually" add them some time.
Thanks for the report!

**Comment by bengalih** [comment]
Curious if there has been any movement on this.? Zimperium and zAnti are becoming more prevalent.
I've personally been having problems with the Chase Mobile App.
What is interesting is that it appears to take a few moments to perform it's checking when the app is first launched.
I have about 5-8 seconds to open up a "protected" activity.  After that I will get a message that the device is rooted.

**Comment by bengalih** [comment]
Just checking in to see if anyone else in the community is working on this?  I last attempted while still on 10 using all known methods of obfuscating Magisk root (hide, repackage, etc.).  I tried multiple hooks from XPrivacyLua and had no success.  I believe some of my tests were skewed because of the delay that Zimperium has when launching an app on first run.  There appears to be approximately 10 seconds (give or take) before it can detect and block and therefore all protected activities will be available until it has initialized.  My testing app was Chase Mobile - and it is possible (even likely) that other apps delay startup until full scanning is done.  With Chase however you can access the protected activities before scanning is complete.  Due to this I believe I had some false positives when trying to bypass Zimperium.  However I don't believe I found any method of hiding/obfuscating root, or blocking access via hooks that worked to foil the detection.  We can only hope that Zimperium is too cost prohibitive for more vendors to start implementing, otherwise soon no apps will work with root.
Additionally, methods that create a secure system like Work Profiles, Samsung Folder, Island, etc also fail to block the detection from Zimperium.

**Comment by dimm0k** [comment]
why is this closed??

**Comment by ReanimationXP** [comment]
@topjohnwu Why was this closed if it's something to be implemented eventually?  Researching rooting and I hear popular apps like Chase are encountering this issue.

**Comment by ugurbor** [comment]
[This](https://play.google.com/store/apps/details?id=com.garanti.bonusapp) bank app also has Zimperium and I couldn't get around the root detection.
Tried latest canary + riru + riru-unshare and also with LSPosed and XPrivacyLUA.

**Comment by soredake** [comment]
Anyone tried this new denylist?

**Comment by paresh996** [comment]
Unable to get away with Zimperium detecting root. Disassembled the library it uses to detect root but the machine language goes above my head.

**Comment by paresh996** [comment]
> > Unable to get away with Zimperium detecting root. Disassembled the library it uses to detect root but the machine language goes above my head.
> 
> which package name?

Developed by Chase but privately shared with me. The experience is exactly same [as people describe](https://github.com/topjohnwu/Magisk/issues/2950#issuecomment-706570166) for the Chase Mobile app.
The app opens, uses the internet for a couple of seconds and then it says the device is rooted.
MagiskHide is enabled, HideMyApplist is hiding other apps and Universal SafetyNet FIx is in place. All other apps work.
[More details](https://xdaforums.com/t/chase-app-always-detects-root.4099627/)

**Comment by paresh996** [comment]
> Probably this app has more layers of protection. Did you run APKiD against the app?

```
[+] APKiD 2.1.5 :: from RedNaga :: rednaga.io
[*] P0.apk
 |-> anti_vm : possible VM check
[*] P0.apk!classes.dex
 |-> anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check, network operator name check, possible VM check
 |-> compiler : dexlib 2.x
[*] P0.apk!classes2.dex
 |-> anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check, SIM operator check, network operator name check
 |-> compiler : dexlib 2.x
[*] P0.apk!classes3.dex
 |-> compiler : dexlib 2.x
[*] P0.apk!lib/arm64-v8a/libz9.so
 |-> anti_vm : possible VM check
[*] P0.apk!lib/armeabi-v7a/libz9.so
 |-> anti_vm : possible VM check
```

**Comment by paresh996** [comment]
> Can you list the native libraries? Just run: `unzip -l apk`

libzcloud.so
libz9.so
libscp.so
libmodpng.so
libmodpdfium.so
libmodft2.so
libjniPdfium.so
libc++_shared.so

**Comment by Apihplays** [comment]
can you test this app ? [https://play.google.com/store/apps/details?id=com.bankislam.bimbmobile&hl=en](url) it has Zdefend from zimperium too

**Comment by enovella** [comment]
@Apihplays This is also protected with zShield

```sh
/com.bankislam.bimbmobile$ apkid .
[+] APKiD 3.0.0 :: from RedNaga :: rednaga.io
[*] ./base.apk!classes.dex
 |-> anti_debug : Debug.isDebuggerConnected() check
 |-> anti_vm : Build.BOARD check, Build.FINGERPRINT check, Build.HARDWARE check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, Build.TAGS check, SIM operator check, device ID check, emulator file check, possible VM check, ro.hardware check, ro.kernel.qemu check, ro.product.device check
 |-> compiler : unknown (please file detection issue!)
 |-> yara_issue : yara issue - dex file recognized by apkid but not yara module
[*] ./base.apk!classes2.dex
 |-> anti_vm : Build.MANUFACTURER check, Build.MODEL check, possible Build.SERIAL check
 |-> compiler : unknown (please file detection issue!)
 |-> yara_issue : yara issue - dex file recognized by apkid but not yara module
[*] ./base.apk!classes3.dex
 |-> anti_vm : Build.BOARD check, Build.FINGERPRINT check, Build.HARDWARE check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check
 |-> compiler : unknown (please file detection issue!)
 |-> yara_issue : yara issue - dex file recognized by apkid but not yara module
[*] ./base.apk!classes4.dex
 |-> compiler : unknown (please file detection issue!)
 |-> yara_issue : yara issue - dex file recognized by apkid but not yara module
[*] ./split_config.arm64_v8a.apk!lib/arm64-v8a/libapp.so
 |-> anti_hook : syscalls
[*] ./split_config.arm64_v8a.apk!lib/arm64-v8a/libfindsvictorian.so
 |-> anti_hook : syscalls
 |-> packer : Zimperium (zShield)
 |-> protector : Zimperium (zDefend)
[*] ./split_config.arm64_v8a.apk!lib/arm64-v8a/libghvovhdepe.so
 |-> anti_hook : syscalls
 |-> packer : Zimperium (zShield)
[*] ./split_config.arm64_v8a.apk!lib/arm64-v8a/libiproov-com-lib.so
 |-> anti_hook : syscalls
```
