### ISSUE TITLE
Magisk 20.4 fails to install Xposed on Android 6.0.1 and 7.1.1

### ISSUE THREAD

**Issue by jgb002002** [topjohnwu/Magisk#2951]
when i update to 20.4 it's fails to instal xposed on android 6.0.1 and 7.1.1 ,include arm and arm64 .

Here is the log:

- Copying zip to temp directory
- Installing Xposed_Framework-v90-beta3(9030).zip
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: XposedBridge.89.jar
  inflating: XposedBridge.90.jar
  inflating: post-fs-data.sh
  inflating: install.sh
  inflating: module.prop
*******************************
Xposed framework installer zip 
*******************************
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
   creating: 23/arm64/
   creating: 23/arm64/system/
   creating: 23/arm64/system/bin/
  inflating: 23/arm64/system/bin/app_process32
  inflating: 23/arm64/system/bin/app_process64
  inflating: 23/arm64/system/bin/dex2oat
  inflating: 23/arm64/system/bin/oatdump
  inflating: 23/arm64/system/bin/patchoat
   creating: 23/arm64/system/lib/
  inflating: 23/arm64/system/lib/libart-compiler.so
  inflating: 23/arm64/system/lib/libart.so
  inflating: 23/arm64/system/lib/libsigchain.so
  inflating: 23/arm64/system/lib/libxposed_art.so
   creating: 23/arm64/system/lib64/
  inflating: 23/arm64/system/lib64/libart-disassembler.so
  inflating: 23/arm64/system/lib64/libart.so
  inflating: 23/arm64/system/lib64/libsigchain.so
  inflating: 23/arm64/system/lib64/libxposed_art.so
- Xposed version: 89
- Device platform: arm64
- Copying files
_mv: can't create '/data/adb/modules_update/xposed/system/framework/XposedBridge.jar': Permission denied_
- Setting permissions
- Done

Everything is ok when i downgrade to 20.3

**Comment by 4512369781** [comment]
open install.sh, and change `mv $TMPDIR/$XPOSEDBRIDGE $MODPATH/system/framework/XposedBridge.jar`  to  `cp -af $TMPDIR/$XPOSEDBRIDGE $MODPATH/system/framework/XposedBridge.jar`

**Comment by osm0sis** [comment]
Not sure what's up here. The Xposed zips used to be @topjohnwu's baby, so I'll defer to him. Not sure if he's still maintaining them, but if so he'll likely want to know.

**Comment by damianos02** [comment]
> open install.sh, and change `mv $TMPDIR/$XPOSEDBRIDGE $MODPATH/system/framework/XposedBridge.jar` to `cp -af $TMPDIR/$XPOSEDBRIDGE $MODPATH/system/framework/XposedBridge.jar`
