### ISSUE TITLE
Cannot Hide Magisk 289

### ISSUE THREAD

**Issue by Jon8RFC** [topjohnwu/Magisk#2952]
Pixel 4
10.0.0 (QQ3A.200705.002, Jul 2020)

It doesn't write anything to the log but displays "hide magisk manager failed" at the bottom.  I force closed and tried hiding again, it failed, and doesn't seem to write to the log.  I've wiped my phone as well.  I once had [this issue before](https://github.com/topjohnwu/Magisk/issues/1979)

In trying to figure out why I can no longer pass safetynet or have "device is certified" in the play store as of the June 2020 update, I have done multiple factory image installs to both partitions, registering my new device id each time I wiped and wiped play store and play services data, locking the phone to confirm passing safetynet.  Unlocking and trying again has ctsprofile failing, reliably, even when magisk was hidden in a prior version, and setting up the props module didn't help.  In 289 on July 2020 update I cannot hide magisk to test, unfortunately.  Have any idea why this is happening?  Did I possibly install a new and irreversible "unlocked bootloader detection" method from the June 2020 factory image since I never update via OTA images and always via factory images?  I also did a factory image installation and wipe of (I think) the december 2019 image and ctsprofile continued to fail.  I can't format partitions since there isn't TWRP for Pixel 4, so I'm out of ideas since I'm not a linux guy or a software developer.

[magisk_log_20200707_022108.log](https://github.com/topjohnwu/Magisk/files/4882890/magisk_log_20200707_022108.log)

**Comment by Didgeridoohan** [comment]
https://www.didgeridoohan.com/magisk/Magisk#hn_Cant_hide_the_Magisk_Manager
and
https://www.didgeridoohan.com/magisk/MagiskHide#hn_Unlocked_bootloader_3

**Comment by Jon8RFC** [comment]
Ah, yes, I completely forgot about the new play protect disabling need, thanks!

Bummer, well it looks like my device is now irreversibly patched since going to a Oct 2019 build didn't resolve the problem before and it still shows "hardware" in Magisk safetynet tests running the Oct 2019 factory image on my Pixel 4.

You've all been warned.  I dirty-flashed the June 2020 factory image onto May 2020 and I've been stuck with failing safetynet ever since, despite wipes and even locking and re-unlocking the bootloader.

<details>
  <summary>Angry rant</summary>
  
It's not quite an iOS product, but Android's similarities to the Apple/bully/dictator mentality are increasing with each executive decision made by the Android leads.  I wouldn't be surprised if the Android higher-ups mostly use iOS devices and/or were poached from Apple.  Apple is already Apple, we don't need two of them; we need Android leads who use their own product and also use it for things other than facebook/instagram, selfies, and bitmojis.  The mandatory Android 9 wifi throttling idea was the biggest feeling of Apple yet, but likely not the last.  Low-flow toilets were annoying at first because they weren't designed well, but at least we could flush again.  I can only imagine the horror we'd experience if we heard the Android leads fielding ideas during meetings, like "Let's disallow screen timeouts longer than 20 seconds and require the user to be physically interacting with the screen--it will save battery life!" and then responding with "Wow, I had that same idea a few months ago!"  It's not a far-fetched scenario given the changes I've seen over the years nerfing usability with the UI/UX and nerfing overall functionality and productivity.
  
I remember my excitement buying my Motorola Droid in 2009 and deciding that Android was the future of handheld devices.  Boy was I wrong with the direction it started going with Jelly Bean, and the past 3 years have been dark times, indeed.
  
</details>
