### ISSUE TITLE
Magiskboot doesn't properly alter files or missing step

### ISSUE THREAD

**Issue by enovella** [topjohnwu/Magisk#2954]
Hi all,

I've been attempting to achieve a **repacked boot image** that comes **rooted** and with **developer options enabled** (adb_enable). For doing so, I've decided to employ `magiskboot` to add a modified `default.prop` file into the `ramdisk.cpio`. Important to mention that the `boot.img` provided was previously rooted by Magisk. Modified files were successfully included in the ramdisk.cpio because they were extracted after adding them to verify the correctness. Therefore, the only missing goal was to get adb enabled after booting.

During the way, I encountered different [issues](https://github.com/topjohnwu/Magisk/issues/2214#issuecomment-654504704) regarding some bootloader flags. However, this didn't affect me much so I won't enter in any debate about it.

## Setup
- Device: `Pixel3a Sargo`
- OS release: `Android 10 & June 2020 patches`
- Magisk: `Canary & stable` releases used

###  my_default.prop
My modifications were these two lines in `default.prop`:
```sh
persist.sys.usb.config=adb,mtp
persist.service.adb.enable=1
```

### Ramdisk patching via Magiskboot

`${BOOTIMAGE}` used was an already Magisk-patched boot.image.
```sh
# Unpack boot.img in current folder
./magiskboot unpack "${BOOTIMAGE}" || abort "! Unable to unpack boot image!"

# Patch ramdisk
./magiskboot cpio ramdisk.cpio "add 750 prop.default my_default.prop"  # Overwrite with my default.pro (symlinked to prop.default)

# Repack the boot image
./magiskboot repack $BOOTIMAGE || abort "! Unable to repack boot image!"
```

### Questions

1. Any bug in Magiskboot with this file? Is this file read-only? read from different location at boot?
2. Why did the changes not affect the Android properties?
3. Is there anything else to modify on the system/data partition?
4. Is there any missing step on my bootpatching's process?

Any feedback you can come up is for sure helpful. Many thanks in advance.

**Comment by topjohnwu** [comment]
@enovella the ramdisk in your device is the recovery ramdisk, Pixel 3a is using system-as-root.
Altering files in a SAR setup is complicated, read more about overlay.d in docs

**Comment by enovella** [comment]
hi @topjohnwu,

AFAIK, the overlay.d feature is only applicable to Magisk modules. I've been using this feature to overlay binaries and config files in SAR devices such as Pixel3a. It worked like a charm! However, I was interested in getting root and adb during boot (if possible right after a clean flash) so that means no time to install Magisk modules yet.

Gave a try to extract the recovery image from the official Google OTA firmware, but since this device is also A/B, the OTA's boot.img contains the recovery ramdisk. Used this OTA's boot.img to process it with the magisk patcher by specifying a `recovery mode` but I ended up getting errors such as `error booting boot.img` or `no valid slot to boot`.

Is there a way of overcoming this issue on a SAR + A/B setup without using modules?

Many thanks!

**Comment by rayfoss** [comment]
pixel 3a "no valid slot to boot" issues were probably due to me not having space to spare... you need around 12GB of free fast, and reliable storage to get the job done. Don't use your SD card, the web flasher is worse than local, it doesn't give proper errors.

I managed to Symlink all the images from my Downloads folder and `ln -s Downloads/bonito/* .` to save space.

I was close to declaring this thing a paper weight
