### ISSUE TITLE
Bootloop on installation of 20.4

### ISSUE THREAD

**Issue by sandorex** [topjohnwu/Magisk#2956]
It's a clean os with only gapps installed, magisk makes it bootloop
I've managed to fix it with the uninstaller

Only error i've found is
```
....
- Adding addon.d survival script
java.io.IOException: Invalid argument
	at java.io.FileInputStream.available0(Native Method)
	at java.io.FileInputStream.available(FileInputStream.java:323)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:342)
	at a.v3.a()
	at a.a.main(:1)
....
```

[recovery.log](https://github.com/topjohnwu/Magisk/files/4891214/recovery.log)

Device: HUAWEI P9 LITE L21
Android: 7.1 (Unofficial lineage os 14.1)

**Comment by osm0sis** [comment]
The error you found is unrelated. Bug reports are only accepted for the latest canaries.

**Comment by sandorex** [comment]
Where do i find the latest canary ?

**Comment by osm0sis** [comment]
Install Manager Canary from the readme link.

**Comment by sandorex** [comment]
Thank you

**Comment by sandorex** [comment]
I've created another issue for it to be more readable #2959 hope you dont mind
