### ISSUE TITLE
Razer Phone 2 Bootloop After X Number of Boots

### ISSUE THREAD

**Issue by Walaryne** [topjohnwu/Magisk#2957]
Hi,
Not sure how much info I can really give for this issue.
It seems to happen after many, many boot cycles on my Razer Phone 2 with Arter97's kernel as a base (r14) (Magisk 20.4).

I'm not sure how to get logs that far up in the Android boot process, but if someone can tell me how to get them, I can add them here when it happens again.

A reflash of Arter's kernel and Magisk 20.4 always fixes the problem, but I still get a little bit worried it could begin bootlooping at a time when I can't reflash it.

**Comment by osm0sis** [comment]
Use the latest Canary. We don't accept bug reports for anything else.
