### ISSUE TITLE
Huawei P9 Lite L21 Bootloop on installation (stable v14.2 works)

### ISSUE THREAD

**Issue by sandorex** [topjohnwu/Magisk#2959]
Patching the boot image did not work neither did flashing the zip
The device kept vibrating on an interval stuck in a bootloop

Device: HUAWEI P9 LITE L21
Android: 7.1 (Unofficial lineage os 14.1)
Magisk Version: 97b72a59(20419)

[magisk.log](https://github.com/topjohnwu/Magisk/files/4896766/magisk.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/4896762/recovery.log)

(I wasnt sure how to get the boot image so i got it from a TWRP backup)
[original-boot.zip](https://github.com/topjohnwu/Magisk/files/4896796/original-boot.zip)
[magisk-boot.zip](https://github.com/topjohnwu/Magisk/files/4896807/magisk-boot.zip)

**Comment by singh-manbir** [comment]
Device - Realme 5
Os - Lineage OS

magisk 20.4

patching boot image by magisk causes boot loop, reflashing firmware boot.img solves the issue, but magisk not installed if firmware boot.img is flashed.

kindly solve the issue

**Comment by Perrito213** [comment]
> Patching the boot image did not work neither did flashing the zip
> The device kept vibrating on an interval stuck in a bootloop
> 
> Device: HUAWEI P9 LITE L21
> Android: 7.1 (Unofficial lineage os 14.1)
> Magisk Version: 97b72a59(20419)
> 
> [magisk.log](https://github.com/topjohnwu/Magisk/files/4896766/magisk.log)
> [recovery.log](https://github.com/topjohnwu/Magisk/files/4896762/recovery.log)
> 
> (I wasnt sure how to get the boot image so i got it from a TWRP backup)
> [original-boot.zip](https://github.com/topjohnwu/Magisk/files/4896796/original-boot.zip)
> [magisk-boot.zip](https://github.com/topjohnwu/Magisk/files/4896807/magisk-boot.zip)

**Comment by Perrito213** [comment]
> > Patching the boot image did not work neither did flashing the zip
> > The device kept vibrating on an interval stuck in a bootloop
> > 
> > Device: HUAWEI P9 LITE L21
> > Android: 7.1 (Unofficial lineage os 14.1)
> > Magisk Version: 97b72a59(20419)
> > 
> > [magisk.log](https://github.com/topjohnwu/Magisk/files/4896766/magisk.log)
> > [recovery.log](https://github.com/topjohnwu/Magisk/files/4896762/recovery.log)
> > 
> > (I wasnt sure how to get the boot image so i got it from a TWRP backup)
> > [original-boot.zip](https://github.com/topjohnwu/Magisk/files/4896796/original-boot.zip)
> > [magisk-boot.zip](https://github.com/topjohnwu/Magisk/files/4896807/magisk-boot.zip)
> 
>

**Comment by Perrito213** [comment]
> Patching the boot image did not work neither did flashing the zip
> The device kept vibrating on an interval stuck in a bootloop
> 
> Device: HUAWEI P9 LITE L21
> Android: 7.1 (Unofficial lineage os 14.1)
> Magisk Version: 97b72a59(20419)
> 
> [magisk.log](https://github.com/topjohnwu/Magisk/files/4896766/magisk.log)
> [recovery.log](https://github.com/topjohnwu/Magisk/files/4896762/recovery.log)
> 
> (I wasnt sure how to get the boot image so i got it from a TWRP backup)
> [original-boot.zip](https://github.com/topjohnwu/Magisk/files/4896796/original-boot.zip)
> [magisk-boot.zip](https://github.com/topjohnwu/Magisk/files/4896807/magisk-boot.zip)

**Comment by Perrito213** [comment]
> > Patching the boot image did not work neither did flashing the zip
> > The device kept vibrating on an interval stuck in a bootloop
> > 
> > Device: HUAWEI P9 LITE L21
> > Android: 7.1 (Unofficial lineage os 14.1)
> > Magisk Version: 97b72a59(20419)
> > 
> > [magisk.log](https://github.com/topjohnwu/Magisk/files/4896766/magisk.log)
> > [recovery.log](https://github.com/topjohnwu/Magisk/files/4896762/recovery.log)
> > 
> > (I wasnt sure how to get the boot image so i got it from a TWRP backup)
> > [original-boot.zip](https://github.com/topjohnwu/Magisk/files/4896796/original-boot.zip)
> > [magisk-boot.zip](https://github.com/topjohnwu/Magisk/files/4896807/magisk-boot.zip)
> 
>

**Comment by singh-manbir** [comment]
> Patching the boot image did not work neither did flashing the zip
> The device kept vibrating on an interval stuck in a bootloop
> 
> Device: HUAWEI P9 LITE L21
> Android: 7.1 (Unofficial lineage os 14.1)
> Magisk Version: [97b72a5](https://github.com/topjohnwu/Magisk/commit/97b72a5941828b13839495d29c0d9138931a6598)(20419)
> 
> [magisk.log](https://github.com/topjohnwu/Magisk/files/4896766/magisk.log)
> [recovery.log](https://github.com/topjohnwu/Magisk/files/4896762/recovery.log)
> 
> (I wasnt sure how to get the boot image so i got it from a TWRP backup)
> [original-boot.zip](https://github.com/topjohnwu/Magisk/files/4896796/original-boot.zip)
> [magisk-boot.zip](https://github.com/topjohnwu/Magisk/files/4896807/magisk-boot.zip)

I have tried the magisk 20.0 and now it is working, Note that version 19, 17 or 15 does not work niether does version 20.4 work. Only the magisk version 20.0 works and my phone is now rooted.

**Comment by osm0sis** [comment]
You need to try the Canary versions around v20.0 and tell us which canary broke it to help narrow down the commits.

**Comment by singh-manbir** [comment]
[Magisk-v20.0.zip](https://github.com/topjohnwu/Magisk/files/4957398/Magisk-v20.0.zip)

I dont know much about coding and stuff, but this is the zip file that works.

**Comment by osm0sis** [comment]
I just linked you to the history of canaries, go back to the ones from around v20.0 and then download the debug zip from it to find the last Canary that works.

**Comment by singh-manbir** [comment]
https://github.com/topjohnwu/magisk_files/commit/8d6c096dc7a17940c3694b5d0e8acf6662cc5358

I think it is this one..

I have added screenshot of my Magisk Manager it shows version 20.0
![Screenshot_20200719-234141_Manager](https://user-images.githubusercontent.com/68508051/88129387-a0988e80-cbf5-11ea-828a-48468fd278b8.png)

**Comment by osm0sis** [comment]
No, you need to install the zip and test, or I'll be forced to close this issue for a lack of useful information.

**Comment by sandorex** [comment]
Ill try it as soon as a i can

**Comment by osm0sis** [comment]
Also, did you even try 20.1, 20.2 or 20.3? You only mention 20.4 and several older versions.

**Comment by singh-manbir** [comment]
> Also, did you even try 20.1, 20.2 or 20.3? You only mention 20.4 and several older versions.

yes I tried, 20.1, 20.2 or 20.3 does not work

**Comment by sandorex** [comment]
@osm0sis do you need me to test them too?

**Comment by sandorex** [comment]
Ok i've tried v20.0, v20.1, v20.3 (debug versions from the canary) and all of them resulted in boot loops

**Comment by osm0sis** [comment]
Wait, that whole time you guys were talking about different devices? 🤦‍♂️ 

Ugh, @singh-manbir, you shouldn't hijack issues.. it makes it more likely neither will get solved because it keeps developers from figuring things out. Open your own issue please.

**Comment by sandorex** [comment]
@osm0sis I will do that tommorow, please dont close the issue yet

**Comment by sandorex** [comment]
Sorry for delaying this so much here are the results so far (ill try to narrow it down)

The problem was introduced between `v14.0` and `v14.5`

**Comment by zgfg** [comment]
Was your last EMUI 4.x (Android 6) or 5.x (Android 7), or 8.x (Android 9  - probably never released for any P9 Lite cust)

If EMUI 5, you should have and need to patch Ramdisk (not Recovery-Ramdisk), not Boot - I'm surprised why do you mention Boot.img

It should not matter for LOS (custom ROM installs to System but booting partitions remain from last EMUI that was installed)

And I recall (I had P9 not Lite, but since last year I'm no more on Huawei) there was a problem with some Magisk 1x versions ('teenage' numbers - not sure was the last correct version 13 or 14, and was it finally resolved with 20.4 or earlier, but for many months and versions there was a bootloop) but that was eventually resolved and the last Stable 20.4 should be ok (hence if not working with 20.3, please still make sure you specifically test with 20.4)

**Comment by sandorex** [comment]
I have specifically tested 20.4 and it did not work, i tested patching the boot image and installation using TWRP

I was using Lineage 14 (Android 7) now i use EMUI 5.1 based ROM but i do not have the time to test and fiddle with this anymore, i just installed supersu thats known to work
