### ISSUE TITLE
MagiskManager update not detecting boot image after reboot

### ISSUE THREAD

**Issue by fmieres** [topjohnwu/Magisk#296]
This happened after latest update today.  (Downloaded, Installed, and Rebooted)

Any suggestion ?

![4c0ea35f-40eb-4a94-84f2-4d26b5109673](https://user-images.githubusercontent.com/10091062/28343419-a4ec266e-6bf3-11e7-8c6f-cbe51e0578f2.jpg)

**Comment by Ante0** [comment]
Try: 
1: restore your stock boot image and flash Magisk 13.3 from TWRP.

2: use uninstaller zip, this is probably what you will have to do. A lot of people have problems with 5.1.0.
5.1.0 and Magisk 13.3 seems to work fine after uninstaller but you will have to reinstall your modules.
Make backup of /data/magisk.img first, in case it doesn't work.

3: revert to manager 5.0.6.

In your case I would try flashing Magisk from TWRP, it seems it wasn't installed as it can't find Magisk.

**Comment by fmieres** [comment]
Just for the record I had it working before last update. Even for a couple of months. I will try re flashing from twrp as soon as i can, thanks for your quick response!

**Comment by fmieres** [comment]
Solved by itself. A Download updated Magisk notification. Installed , restarted , works!
