### ISSUE TITLE
SMS Failure Android 11 Beta 2

### ISSUE THREAD

**Issue by Charaktor** [topjohnwu/Magisk#2961]
Hey there,

I clean flashed the new Android 11 Beta 2 on my Pixel 4. Flashing magisk patched boot img worked fine, but afterwards I could not receive any SMS, which are important to me for 2FA logins. As soon as I flashed the original boot img again, all SMS came in immediately. Problem persists through different messaging apps and cleaning data did not help. 
Sending SMS is no problem when rooted. 
Has anybody else experience this issue. Is there anything I can do?

Thanks in advance.
Cheers.

**Comment by kuanhulio** [comment]
Have you updated _all_ the available apps through the Play Store?

I have an issue like that, but it's solved due to updating all the apps.

**Comment by arminhama** [comment]
> Hey there,
> 
> I clean flashed the new Android 11 Beta 2 on my Pixel 4. Flashing magisk patched boot img worked fine, but afterwards I could not receive any SMS, which are important to me for 2FA logins. As soon as I flashed the original boot img again, all SMS came in immediately. Problem persists through different messaging apps and cleaning data did not help.
> Sending SMS is no problem when rooted.
> Has anybody else experience this issue. Is there anything I can do?
> 
> Thanks in advance.
> Cheers.

I am experiencing the same issue on my Pixel 4. I spoke with my carrier (T-Mobile) and they could not find a network issue to blame for my troubles. I tried a different SMS app, cleared app data, and followed the various troubleshooting instructions from carrier support. I flashed the original boot.img and received SMS again. I will try kuanhulio's method with respect to updating my other apps and report back.

**Comment by kuanhulio** [comment]
If it doesn't work, try reflashing A11B2 and then update all your apps then flash `magisk_patched.img`.

**Comment by Charaktor** [comment]
> > Hey there,
> > I clean flashed the new Android 11 Beta 2 on my Pixel 4. Flashing magisk patched boot img worked fine, but afterwards I could not receive any SMS, which are important to me for 2FA logins. As soon as I flashed the original boot img again, all SMS came in immediately. Problem persists through different messaging apps and cleaning data did not help.
> > Sending SMS is no problem when rooted.
> > Has anybody else experience this issue. Is there anything I can do?
> > Thanks in advance.
> > Cheers.
> 
> I am experiencing the same issue on my Pixel 4. I spoke with my carrier (T-Mobile) and they could not find a network issue to blame for my troubles. I tried a different SMS app, cleared app data, and followed the various troubleshooting instructions from carrier support. I flashed the original boot.img and received SMS again. I will try kuanhulio's method with respect to updating my other apps and report back.

I'm on T-Mobile Germany. Updating apps first didn't help for me. No modules are active. No difference between stub and normal mm. Completely clean flash of A11B2.
But I found out, that magisk hide seems to be the culprit. When disabling magisk hide SMS come in again. Even when just the default activities from GMS are checked, it won't work. Could that really be an carrier specific problem? I kind of doubt it.
@topjohnwu you got any idea? Logcat attached. MM log button not useable.
[logcat_07-14-2020_10-10-21.txt](https://github.com/topjohnwu/Magisk/files/4917438/logcat_07-14-2020_10-10-21.txt)

**Comment by tobiasz-p** [comment]
@Charaktor I'm also having SMS and alarm issue when Magisk Hide is on. I'm using Huawei P8, magisk 20.4. Have you resolved an issue?
