### ISSUE TITLE
Magisk 20.4+ gets realme x2 Pro into bootloop...

### ISSUE THREAD

**Issue by Jerry1908** [topjohnwu/Magisk#2962]
Hello

On realme x2 Pro in custom roms we are getting bootloop after flashing  magisk 20.4 or newer(Magisk 20.2 or older doesn't work also, only magisk 20.3 works). What's really weird is that magisk 20.4+ boots on Stock rom but not in custom roms. The device doesn't boot so i can't bring dmesg or logcat but maybe recoverey logs would help?. Whatever will be needed, ill bring.

Thanks.

**Comment by cawidtu** [comment]
Maybe related to https://github.com/topjohnwu/Magisk/issues/2645?

**Comment by osm0sis** [comment]
Yep. Likely duplicate.
