### ISSUE TITLE
[Bug] xposed modules.list was not found (again)

### ISSUE THREAD

**Issue by swieder711** [topjohnwu/Magisk#2967]
I am the having problem with Xposed modules.list was not found.  I know that this problem was reported before and fixed in Magisk (20406).  But, I am running the Canary Magisk and am still seeing the issue.

![Screenshot_20200710-104329](https://user-images.githubusercontent.com/68071051/87167321-c55a4100-c29a-11ea-80b1-6a65473ab3a7.png)
![Screenshot_20200710-104341](https://user-images.githubusercontent.com/68071051/87167326-c7bc9b00-c29a-11ea-8064-e44738e0dfba.png)

Here is the Xposed Log file
[all.log](https://github.com/topjohnwu/Magisk/files/4903783/all.log)

![Screenshot_20200710-105242](https://user-images.githubusercontent.com/68071051/87167862-a27c5c80-c29b-11ea-8f13-669a863826b2.png)

I think the relevant piece is this:

7-10 08:44:27.995  1679  1679 I EdXposed:   no module log: false
07-10 08:44:28.997  1673  1673 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
07-10 08:44:29.287  1862  1862 E EdXposed: mmap failed, errno = Permission denied
07-10 08:44:29.287  1862  1862 E EdXposed: cannot hook method
07-10 08:44:29.287  1862  1862 E EdXposed: error when hooking com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker

Any suggestions for what to try next?

**Comment by swieder711** [comment]
I rolled back to the Stable Magisk Manager 7.5.1 (267) and module 20.4 (20400).  I was having issues with SU and granting permissions.

Where can I get 20406 with the fix for the SELinux issue?

**Comment by topjohnwu** [comment]
Report bug at Edxposed

**Comment by swieder711** [comment]
Hi TopJohn -  Thanks for looking at my issue.  Did you see the log info:

07-10 08:44:28.997 1673 1673 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
07-10 08:44:29.287 1862 1862 E EdXposed: mmap failed, errno = Permission denied

When this problem appear before. I saw that a change to Magisk with SEpolicy fixed it.  Do you think something else related to an EdXposed bug is now causing the issue?
