### ISSUE TITLE
Feature Request:  Magisk Recovery run mode

### ISSUE THREAD

**Issue by JperiodMichael** [topjohnwu/Magisk#2968]
On my tablet (Samsung SM-T290), Magisk is installed in recovery.  If the tablet is ever booted without Magisk, it is tricky to reboot with Magisk:  I have to shut down, then boot as if booting to recovery, then release some buttons at just the right time to signal Magisk that I do not really want to go to recovery.

Please consider changing the response to:

Booting to recovery goes to a Magisk menu, with options
* Continue to Recovery
* boot Android with Magisk
* boot Android with Magisk in core-only mode
* boot Android without Magisk

**Comment by Navneet-Kumar-Singh** [comment]
> On my tablet (Samsung SM-T290), Magisk is installed in recovery.  If the tablet is ever booted without Magisk, it is tricky to reboot with Magisk:  I have to shut down, then boot as if booting to recovery, then release some buttons at just the right time to signal Magisk that I do not really want to go to recovery.
> 
> Please consider changing the response to:
> 
> Booting to recovery goes to a Magisk menu, with options
> * Continue to Recovery
> * boot Android with Magisk
> * boot Android with Magisk in core-only mode
> * boot Android without Magisk

My dear friend  @JperiodMichael  , you are thinking of an easier way to get into Magisk while I have not even been able to install Magisk on SM-T290 my tab, it would be very kind of you if you would make a video on how did you install Magisk and give the link to video, please my dear friend I am begging you please , give me a tutorial on how were you able to install Magisk 20.4 on the tab. thank you .🥰

**Comment by JperiodMichael** [comment]
@Navneet-Kumar-Singh:  Please post on xda-developers.com, in the SM-T290 thread.  (I am "J.Michael" on xda-developers.)

**Comment by topjohnwu** [comment]
@JperiodMichael this would require to me create something similar to TWRP with full graphics stack, which is completely out of scope of Magisk's goal
