### ISSUE TITLE
[Feature] Select/Deselect all in Magisk hide selection. (SOLVED)

### ISSUE THREAD

**Issue by lss4** [topjohnwu/Magisk#2969]
Prior to Canary, Magisk Hide can be toggled at app level, but with Canary, it seems to have changed to toggle at component level and there's currently no option to toggle all of them at once (to mimic pre-Canary behavior).

As a result, I need to toggle them one by one if I want to hide it from all components, and some apps can have over 10 entries to toggle, which can be a lot of effort.

----------------

By the way, not sure if this is a bug or something with Canary 20419 (Magisk)/289 (Manager), but Magisk Hide does not appear to work. After toggling everything needed in Magisk Hide, re-entering Magisk Hide shows a list with nothing really toggled on, so I don't know whether it's really toggled on or not. I've already hidden the Magisk Manager (status shows Stub with the randomized package name).

**Comment by Didgeridoohan** [comment]
First - Use the eye on the left to toggle all components.

Second - is MagiskHide enabled? I seem to remember that you'll see that behaviour if it isn't enabled. Not sure if the Canary Manager has been updated to not show the hide list of MagiskHide isn't enabled.

**Comment by lss4** [comment]
Yes, you're right. The eye on the left did the job.

And Magisk Hide is indeed not on by default. Now it's working. The canary manager still shows the hide list even when it's disabled.

I think it's better to add a warning in the Magisk Hide view when Magisk Hide is off, and lead the user to the main Magisk Hide toggle.
