### ISSUE TITLE
Feature: Force evalType=BASIC for CTS Profile to pass SafetyNet

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#2972]
It has been confirmed on XDA that redefining or nullifying (deleting) the following Props forces CTS Profile attest to switch from Hardware to Basic, resulting in CTS Profile and SafetyNet to pass:
ro.product.model
ro.product.system.model
ro.product.vendor.model
ro.product.odm.model
ro.product.product.model

Seems it is a solution for now for rooted stock firmwares (with unlocked Bootloaders), because it seems that these Props are what CTS Profile attest is looking for to decide whether to use evalType BASIC or HARDWARE.
Solution was first posted on XDA by @Displax:
https://forum.xda-developers.com/showpost.php?p=83028387&postcount=40658

E.g. on my Xiaomi Mi 9T, MIUI 11 - Android 10, first four Props are all defined to "Mi 9T", while the fifth Prop is not defined.
Redefining the first (!) of them to "Unknown", "Basic" or just nullifying (deleting) that Prop results that CTS Profile attest will use evalType=BASIC, therefore passing the SafetyNet:
https://forum.xda-developers.com/showpost.php?p=83035713&postcount=40681

According to tests by other users - XDA posts number: 40658, 40661, 40679, 40680, 40681, 40682, 40683, it works on various phones.
It can be one another Prop from above for another particular phone, hence it makes sense to invalidate all the Props as above, just in case

Proposal:
To extend Magisk Hide feature and/or it can be an optional step for user to decide, to nullify (delete) or invalidate (redefine them to something like "unknown") the five ro.build.* Props if they exist

**Comment by Displax** [comment]
This is clearly temporary hack until Google will complete their device-based testing.
I don't think it's worth adding this to core hide_policy.

**Comment by zgfg** [comment]
True, but it can stay valid for long - e.g. it's already a month since Google extended evalType, and although you discovered that just last days, it would have work from day one they started with - and we don't know how long it can last

At least, it could be worth for a Canary build

**Comment by kuanhulio** [comment]
Wouldn't this be better as a Module instead?

That way, this feature doesn't have to be added then subsequently removed when Google actually finishes their CTS overhaul?

**Comment by zgfg** [comment]
Yes, @Displex made a module -thanks.
One can also use Magisk Hide Props Config and Edit/Delete custom props option.
Or SesEdit app (from Playstore), props to edit are under Android properties tab

But people would not be aware they have to look for external resources to make them SafetyNet pass

**Comment by kuanhulio** [comment]
> But people would not be aware they have to look for external resources to make them SafetyNet pass

And is that so bad? SafetyNet passing isn't an issue for me and I think other people would agree that it would be *nice* to have it pass, but not a need. Banking apps, certain apps like Netlix, GPay, yeah they don't work as they used to with root (with GPay, there is a trivial bypass) and hell, BofA will let you use the app even though you're rooted. Netflix, you can either sideload it or just pirate.

Rooting was always going to make stuff break, it's just that we had @topjohnwu and @osm0sis to cover our ass.

**Comment by RikkaW** [comment]
Key Attestation mechanism (what behinds SafetyNet) has the ability to attest device info like model, touching these props is totally meaningless.

**Comment by zgfg** [comment]
> Key Attestation mechanism (what behinds SafetyNet) has the ability to attest device info like model, touching these props is totally meaningless.

Before saying si, have you Tried. A

**Comment by RikkaW** [comment]
> > Key Attestation mechanism (what behinds SafetyNet) has the ability to attest device info like model, touching these props is totally meaningless.
> 
> Before saying si, have you Tried. Are we idiots if it works for us?!??
> 
> Currently, Google dis not introduce for all phones, this way you avoid it for your phone

The reason for "this can work" is Google simply hasn't used key attestation to verify the device model. Google can add this at any time, then your "solution" will become a super obvious sign of system modification.
