### ISSUE TITLE
OnePlus7T - boot.img patch does not work - boot loop.

### ISSUE THREAD

**Issue by Widmo** [topjohnwu/Magisk#2980]
OnePlus7T HD1903
I had working root, survived many OTA's, after each OTA I launched Magisk, flash inactive boot bank, it works perfect.

Last time i did the same, but have bootloop.
I downloaded ZIP with OTA, extracted payload, extracted stock boot.img, flash into phone so it boot
Tha same image I'm trying to patch with Magisk Manager 7.5.1 / Magisk Canary - but everytme i have bootloop.
Force encryption / dm-verify enabled.

I don't have any logs from Canary (or tell me how to get it) 
Logs from ADB logcat. 

It is one full log loop, 

Readable: https://pastebin.com/B2G76y9D

**Comment by osm0sis** [comment]
7T is my daily driver and I've been using Manager's Flash After OTA Install option and it all works fine. Can't speak to the rest of your method, but Magisk itself patches and works fine on latest 7T OOS stable.

**Comment by Widmo** [comment]
But patching stock boot.img does not work. 

Can you share me Yours patched HD1903 (EU) boot.img?

**Comment by osm0sis** [comment]
I have HD1905, but still, patching boot.img works fine. I dump the clean updated boot.img from the opposite slot before rebooting after every OTA.

**Comment by Widmo** [comment]
I did exactly the same, after OTA opened Magisk Manager and patch opposite slot before rebooting. Like many times before. 
But this time I had boot loop. 

Can You check if patched image is OK?

STOCK boot.img (working, no root)
https://drive.google.com/file/d/1mrZ43Wl_532dI1yB8UrOpq0T4fE3GqvS/view?usp=sharing

PATCHED (non working, bootloop)
https://drive.google.com/file/d/1qoqbpBoxI4fhg_jHSO0-jhJI-GJik0Oi/view?usp=sharing

**Comment by osm0sis** [comment]
Looks fine to me. Just like my magisk_patched.img from my extracted boot-HD1905_14_200519.img. Perhaps there's an issue with a module you have installed.. I can't imagine EU and NA are that different.

[magisk_patched-20419.img.zip](https://github.com/topjohnwu/Magisk/files/4926241/magisk_patched-20419.img.zip)
.

**Comment by Widmo** [comment]
OK, thank You. And is possible to locate witch module causes problem - or uninstall any module (without root) ?

**Comment by osm0sis** [comment]
Use adbd patched stock recovery for the 7T until TWRP has working decrypt, and then you can go into /data/adb/modules and delete things as needed.

https://forum.xda-developers.com/oneplus-7t/how-to/magisk-twrp-root-module-uninstall-t4002843/post82376013#post82376013

It should be flashable via a `fastboot boot`ed TWRP as well, so no root needed to get started there.

**Comment by Widmo** [comment]
Yupi! I did it!
Root is back. I'm so happy, thank Your for help. :) 

Maybe it is good idea to direct people to the link: 
https://forum.xda-developers.com/oneplus-7t/how-to/magisk-twrp-root-module-uninstall-t4002843

I did not know that it was issued by wrong module. 
Thank You one more time.

**Comment by osm0sis** [comment]
No, I direct linked to my post with my version of the solution, which is better.
