### ISSUE TITLE
Boot loop and cannot uninstall

### ISSUE THREAD

**Issue by hugoiturrieta** [topjohnwu/Magisk#2981]
I'll be as brief as possible for you. But please, I need the help of someone with knowledge. This is my only phone and I really need it.

-I followed this guide with little differences https://forum.xda-developers.com/moto-e5/how-to/guide-root-twrp-moto-e5-play-explained-t3856182
-I took precautions and I downloaded the respective twrp for my phone (moto e5 nora).
-I couldn't make a backup because I'm lower-class college student and I can't afford a micro sd bigger than 4gb (I should have given up here).
-I installed Magisk and i thought it went well because no errors showed (at least that's what I think)
-Now android bootloops showing some strange numbers (80012a99-867fda48-...)
-I tried to uninstall using the uninstaller.zip so I could install an older version of Magisk but when I try to "install" the uninstaller twrp says "cannot access /data please uninstall with magisk manager" but I just can't do it because android it's bootlooping.

Other data (it may be useful):
-After installing the last version of Magisk, abd won't recognize the phone ("adb devices") but "fastboot devices" will.
-I cannot repair /data but I can format it to ext4,ext2, etc (but it didn't work).
-I'm downloading stock image but I don't know how safe will it be to reinstall the whole Android. I'm afraid I can permanently damage my phone after what I have done here.

I'm sorry for my english, I ask for help to you because you guys in github are very nice and you know a lot more than I do.
I'm posting this issue in other sites too, so suggestions about forums will be apreciated. Thanks in advance.

**Comment by osm0sis** [comment]
You just need to wipe /data and flash the default boot.img for your ROM.

**Comment by AnotherPc** [comment]
I had the same problem with my Moto E5 - nora (XT1944-3), but I had to use a zip file in the TWRP installer

-- This is the Rom of my cell phone Moto E5 - Nora (XT1944-3) Versión LATAM. I am from México
https://www.stockrom.net/2020/04/xt1944-3-retla-oreo-opps27-91-176-11-13.html
