### ISSUE TITLE
Samsung Galaxy Tab S6 Lite doesnt like blank Vbmeta. Goes to odin with an avb failed error

### ISSUE THREAD

**Issue by Janer1** [topjohnwu/Magisk#2982]
I trieed patching the Tar with magisk and did the adb pull and tried flashing it., it didnt want to boot and instead gave me an avb error saying there was nothing in the vbmeta. Also it has a second vbmeta called samsung_vbmeta so i dont know if thats new or not.

**Comment by mu198** [comment]
I have now managed to root my tablet (SM-P610 / S6 Lite) 1) download firmware 2) extract the AP file 3) extract Boot.lz4 4) extract it to Boot.img 5) Flash with magisk 6) magisk_patched.tar rename to Boot.img 7) package the Boot.img into a .tar file (via 7z) 8) Flash Boot.tar via Odin 3.14 8) then immediately perform the recovery and factory reset
![IMG_20200714_184706](https://user-images.githubusercontent.com/65677888/87516723-23fa3300-c67e-11ea-9437-47e04416eb01.jpg)

**Comment by osm0sis** [comment]
Sounds invalid then. 👍
