### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by desk7** [topjohnwu/Magisk#2984]
Dear developer,
I know that Magisk and Magiskmanager are open source but I'd like to know if they send any kind of data from our smartphone. Unfortunately I can't find the answer elsewhere. the privacy policy here (https://magiskmanager.com/privacy-policy) is only about the website.

**Comment by Didgeridoohan** [comment]
That website has nothing to do with Magisk. Just profiting off the name.

**Comment by desk7** [comment]
Ok. So, apart from website, what is the privacy policy of Magisk and Magisk manager?



Da: Didgeridoohan<mailto:notifications@github.com>
Inviato: giovedì 16 luglio 2020 07:27
A: topjohnwu/Magisk<mailto:Magisk@noreply.github.com>
Cc: desk7<mailto:r.dima@outlook.it>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [topjohnwu/Magisk] Privacy policy (#2984)


That website has nothing to do with Magisk. Just profiting off the name.

**Comment by desk7** [comment]
Ok. So, apart from website, what is the privacy policy of Magisk and Magisk manager?

**Comment by Displax** [comment]
Magisk do not sent any of your data.
It is only connected to GitHub to check updates, so read it privacy policy. And it is may download proprietary SafetyNet module (contains GoogleApiClient), so read it privacy policy.

**Comment by topjohnwu** [comment]
@desk7 I do not have ANY data collected as I do not run a server
