### ISSUE TITLE
service. d module script sh ran out

### ISSUE THREAD

**Issue by silvi33** [topjohnwu/Magisk#2986]
![Screenshot_20200715-222238_Qute](https://user-images.githubusercontent.com/68015790/87612518-5cad1180-c73d-11ea-9ec3-4da4844e7756.jpg)
![Screenshot_20200715-222334_Qute](https://user-images.githubusercontent.com/68015790/87612527-633b8900-c73d-11ea-9858-6357d096a3cb.jpg)
![Screenshot_20200715-235812_7Zipper](https://user-images.githubusercontent.com/68015790/87612537-68003d00-c73d-11ea-85f1-1889e536d6dd.jpg)

**Comment by Didgeridoohan** [comment]
Magisk v17.3? Really? Only bug reports using the latest Canary is accepted, and this doesn't look like a bug anyway. More likely a module issue.

**Comment by silvi33** [comment]
Actually me for the root stuffs knowledge is =0. Starting I'm just try to root my phone with 0 knowledge but I tried many times to root. Finally my phone is rooted successfully with the magisk. After that, I saw many exciting modules i wanna too in my phone. Finally I'm just stacked in magiskhide prop config,  I have tried it to solve myself thru your configuration method but not success. But then I tried to find the gateway to contact you,I'm failed in xda developers gateway, but I'm found the link github and finally can type my problem to send to you 😪😪 . I'm apologise that if I made the trouble in group, really sorry...Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Didgeridoohan <notifications@github.com> Date: 16/07/2020  13:30  (GMT+08:00) To: topjohnwu/Magisk <Magisk@noreply.github.com> Cc: silvi <sammiteoh5932@gmail.com>, Author <author@noreply.github.com> Subject: Re: [topjohnwu/Magisk] service. d module script sh ran out (#2986) 
Magisk v17.3? Really? Only bug reports using the latest Canary is accepted, and this doesn't look like a bug anyway. More likely a module issue.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/topjohnwu/Magisk/issues/2986#issuecomment-659168182",
"url": "https://github.com/topjohnwu/Magisk/issues/2986#issuecomment-659168182",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Didgeridoohan** [comment]
Since this is the Magisk GitHub issues (and it doesn't seem like a Magisk problem), why don't you close this one (there'll be a button right next to the comment button) and instead post the logs mentioned in your first screenshot in either the MagiskHide Props Config [XDA thread](https://forum.xda-developers.com/apps/magisk/module-magiskhide-props-config-t3789228) or [GitHub page](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf). I'll see if I can help from there.

**Comment by silvi33** [comment]
Sure, I do it now. Thanks for your guidance and patience. Appreciate it.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Didgeridoohan <notifications@github.com> Date: 16/07/2020  16:12  (GMT+08:00) To: topjohnwu/Magisk <Magisk@noreply.github.com> Cc: silvi <sammiteoh5932@gmail.com>, Author <author@noreply.github.com> Subject: Re: [topjohnwu/Magisk] service. d module script sh ran out (#2986) 
Since this is the Magisk GitHub issues (and it doesn't seem like a Magisk problem), why don't you close this one (there'll be a button right next to the comment button) and instead post the logs mentioned in your first screenshot in either the MagiskHide Props Config XDA thread or GitHub page. I'll see if I can help from there.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/topjohnwu/Magisk/issues/2986#issuecomment-659237201",
"url": "https://github.com/topjohnwu/Magisk/issues/2986#issuecomment-659237201",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by silvi33** [comment]
Apologise for make trouble here.
