### ISSUE TITLE
manager更新到290（9）后，出现两个问题

### ISSUE THREAD

**Issue by UQJRlex** [topjohnwu/Magisk#2987]
在把manager更新到290（9）后，出现两点问题：

1.magisk hide正常工作，但manager没有任何hide显示标志。

2.打开模块页有小几率闪退。

系统 Android 10
机型 redmi note7 pro
已经隐藏magisk manager

![IMG_20200716_111218](https://user-images.githubusercontent.com/39591894/87622460-be797580-c755-11ea-868f-50f2264c19a0.jpg)

**Comment by eebssk1** [comment]
Same problem,mgaisk hide is still   showing in logs,but no mark on the settings.

**Comment by etofi** [comment]
Same Problem. In Version 285 it works in current one not.

**Comment by osm0sis** [comment]
#2992
