### ISSUE TITLE
Request for a separate Basic/Minimal Root-access Manager:

### ISSUE THREAD

**Issue by JagdishKumar1970** [topjohnwu/Magisk#2989]
Hello, 
@topjohnwu 

I think that many people(including me) don't need a full-fledged Root Manager with System-less Properties, Modules, Hide, …, but rather an Up-to-date equivalent to SuperSU(or add-on_su) because as far as i know "You can't have a bug in code you don't have" and Root-access Management is a very Critical component of Android and Win10-like approach is unacceptable in this(fundamental) Department of Android.

Recommended Package ID: 'basic.topjohnwu.magisk'.

Thankyou, and I'm really sorry if i disturbed or hurt someone's feelings…

**Comment by 61569864** [comment]
> Hello,
> @topjohnwu
> 
> I think that many people(including me) don't need a full-fledged Root Manager with System-less Properties, Modules, Hide, …, but rather an Up-to-date equivalent to SuperSU(or add-on_su) because as far as i know "You can't have a bug in code you don't have" and Root Access Management is a very Critical component of Android and Win10-like approach is unacceptable in this(fundamental) Department of Android.
> 
> Thankyou, and I'm really sorry if i disturbed or hurt someone's feelings…

**Comment by 61569864** [comment]
`
`

**Comment by JagdishKumar1970** [comment]
Please comment @topjohnwu @phhusson  and others...

**Comment by phhusson** [comment]
Why would you want me to comment?

I already have my own basic SU in my GSIs

**Comment by JagdishKumar1970** [comment]
> Why would you want me to comment?
> 
> I already have my own basic SU in my GSIs

I request your view or suggestion or approval on this.

Thank you…

**Comment by phhusson** [comment]
I've litterally just given you my view:

I also want a minimal SU, that I can embed in my ROM. That's why I did one.
(or rather I picked again what I did before Magisk, which was picked from
Koush which was picked from god knows when)
