### ISSUE TITLE
13.3 Doesn't work on LineageOS 14.1 (Nexus 6p)

### ISSUE THREAD

**Issue by snky1987** [topjohnwu/Magisk#299]
I have Nexus 6p with LineageOS 14.1 (20170717) installed and I do have running Magisk 13.2.

As soon as I update Magisk to 13.3 and reboot (tries zip flash as well) the Magisk Manager stuck on logo (green) screen. If I downgrade Magisk Manager then it says that there is no Magisk installed.

Things I tried:
1) Update by Download & Install
2) Uninstall via uninstaller and fresh install of 13.3 via TWRP

**Comment by coderobe** [comment]
An update to MagiskManager has been released, fixing this issue. Can you install the latest version of the Manager and try again?

**Comment by snky1987** [comment]
I can confirm it now works on Nexus 6p with Lineage OS 14.1 just fine (Installed from Magisk level). 

Thanks 👍
