### ISSUE TITLE
Samsung Galaxy M21 can't go to recovery from download mode after flashing modified tar

### ISSUE THREAD

**Issue by TheK0tYaRa** [topjohnwu/Magisk#2991]
Yes, it's #2272  clone. The issue is the phone can't be shut down after flashing, even by burning through the battery power. The instructions need to have info about "if the transfer to recovery can't be made - it's currently impossible to use Magisk"

**Comment by TheK0tYaRa** [comment]
Noticed that there is a file called `vbmeta_samsung.img.lz4` in the AP, it might be the root of the problem.

**Comment by TheK0tYaRa** [comment]
Also there is well known (after samsung released android 10) file - `super.img.lz4`

**Comment by TheK0tYaRa** [comment]
Checked md5 of files mentioned above, they don't change. Expected of `super.img.lz4`, but `vbmeta_samsung.img.lz4` not changing was unexpected. Please elaborate.

**Comment by osm0sis** [comment]
So, you say yourself "it's #2272 clone" ...

**Comment by mu198** [comment]
Just try to extract the Boot.img and flash it, my sm-p610 worked exynos 9611

**Comment by mu198** [comment]
https://github.com/topjohnwu/Magisk/issues/2272#issuecomment-658815505


Show here and read 🙈 testing

**Comment by 4ifi** [comment]
> Just try to extract the Boot.img and flash it, my sm-p610 worked exynos 9611

Tested on SM-M215F and got bootloop.
