### ISSUE TITLE
Bad 2SI checking logic for Android 11 devices?

### ISSUE THREAD

**Issue by simonsmh** [topjohnwu/Magisk#2994]
#2979

My device is Mi 10 with MIUI12 based on Android 11 Beta 1-3. After patching boot, the phone boots but magisk seems not working.

For my device, which is using Android 11 SAR A-only, Magisk is jumping into `RootFSInit` instead of `FirstStageInit` because of the `/apex` dir is missing in the ramdisk.

However, this device is definitely 2SI as it is necessary for dynamic partition device, right? With Android 10, It is working because the ramdisk contains `/apex` dir.

[boot.tar.gz](https://github.com/topjohnwu/Magisk/files/4935849/boot.tar.gz)
[new-boot.tar.gz](https://github.com/topjohnwu/Magisk/files/4935850/new-boot.tar.gz)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/4935852/dmesg.log)
[logcat.log](https://github.com/topjohnwu/Magisk/files/4935853/logcat.log)
[patchboot.log](https://github.com/topjohnwu/Magisk/files/4935854/patchboot.log)

https://github.com/topjohnwu/Magisk/blob/7fc9b908d447691253b55f09d358412b2025ca50/native/jni/init/init.cpp#L177-L193

And with `FirstStageInit` I still got bootloop instead, but let's track it on #3093

**Comment by osm0sis** [comment]
Same with OnePlus Android 11 Beta

**Comment by simonsmh** [comment]
@osm0sis As your device is A/B, magisk should work again with patching boot.img with creating apex folder and switch to `SARFirstStageInit` .

**Comment by osm0sis** [comment]
Yep, that's a viable workaround, but as you say detection will need to be fixed. This is likely another case of Google not following their own OEM specs, just as with adding recovery_a/recovery_b partitions back is the current standard everywhere except on Pixels where it's still boot-as-recovery.

**Comment by osm0sis** [comment]
I'm thinking looking for /apex OR /avb or /debug_ramdisk might be the way to go

**Comment by topjohnwu** [comment]
I would personally choose a more definite way, maybe parsing the init binary directly.

**Comment by Perrito213** [comment]
> #2979
> 
> My device is Mi 10 with MIUI12 based on Android 11 Beta 1. After patching boot, the phone boots but magisk seems not working.
> 
> For my device, which is using Android 11 SAR A-only, Magisk is jumping into `RootFSInit` instead of `FirstStageInit` because of the `/apex` dir is missing in the ramdisk.
> 
> However, this device is definitely 2SI as it is necessary for dynamic partition device, right? With Android 10, It is working because the ramdisk contains `/apex` dir.
> 
> [boot.tar.gz](https://github.com/topjohnwu/Magisk/files/4935849/boot.tar.gz)
> [new-boot.tar.gz](https://github.com/topjohnwu/Magisk/files/4935850/new-boot.tar.gz)
> [dmesg.log](https://github.com/topjohnwu/Magisk/files/4935852/dmesg.log)
> [logcat.log](https://github.com/topjohnwu/Magisk/files/4935853/logcat.log)
> [patchboot.log](https://github.com/topjohnwu/Magisk/files/4935854/patchboot.log)
> 
> Reference: https://github.com/topjohnwu/Magisk/blob/master/native/jni/init/init.cpp#L177
> 
> And with `FirstStageInit` I got bootloop instead as `init.rc` failed to load as Android 11 does not store it in ramdisk anymore.

**Comment by gyj1109** [comment]
@osm0sis @topjohnwu Is there any progress? I need Magisk on Oxygen OS DP3 urgently. Thanks!

**Comment by antnyhills** [comment]
> @osm0sis @topjohnwu Is there any progress? I need Magisk on Oxygen OS DP3 urgently. Thanks!

[https://androidfilehost.com/?fid=8889791610682913299](url)

Use this boot.img to get root working on OOS 11 DP3

I'm personally using it and its working correctly.

**Comment by simonsmh** [comment]
@antnyhills Could you provide a dmesg log for your boot.img?

**Comment by gyj1109** [comment]
> [https://androidfilehost.com/?fid=8889791610682913299](url)
> 
> Use this boot.img to get root working on OOS 11 DP3
> 
> I'm personally using it and its working correctly.
> 
> This is for the International OnePlus 8 Pro I should specify.

Thank you so much! I'm using exactly International OnePlus 8 Pro and that what I need!

Also, I wonder how you made it and hope it would be merge into Magisk.

BTW, you're using a wrong Markdown url pattern so that the url link to the Magisk Issue page.

**Comment by antnyhills** [comment]
> > [https://androidfilehost.com/?fid=8889791610682913299](url)
> > Use this boot.img to get root working on OOS 11 DP3
> > I'm personally using it and its working correctly.
> > This is for the International OnePlus 8 Pro I should specify.
> 
> Thank you so much! I'm using exactly International OnePlus 8 Pro and that what I need!
> 
> Also, I wonder how you made it and hope it would be merge into Magisk.
> 
> BTW, you're using a wrong Markdown url pattern so that the url link to the Magisk Issue page.

Thanks, should be fixed. This is not my work, so I'm unsure of what was done to make it work, sorry! :/

**Comment by stetorIT** [comment]
> 
> 
> > @osm0sis @topjohnwu Is there any progress? I need Magisk on Oxygen OS DP3 urgently. Thanks!
> 
> https://androidfilehost.com/?fid=8889791610682913299
> 
> Use this boot.img to get root working on OOS 11 DP3

there is something similar for the MI10 with MIUI12 ?

or any news on fixing this problem with android 11?

thx

**Comment by mrmazakblu** [comment]
I have similar issue. Appears magisk.init is not run at boot time. So device boots without having root. 
But the connection to Android 11 and the missing apex folder from boot.img ramdisk do not seem to be the only factor.  My device is Android 10 and has the apex folder, and still has the issue of magisk.Init not active when booted.

**Comment by osm0sis** [comment]
> I have similar issue. Appears magisk.init is not run at boot time. So device boots without having root.
> But the connection to Android 11 and the missing apex folder from boot.img ramdisk do not seem to be the only factor. My device is Android 10 and has the apex folder, and still has the issue of magisk.Init not active when booted.

Then it's not the same issue.
