### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by hsheidaryarad** [topjohnwu/Magisk#2997]
Hi, my superuser request is always denyed and n_t workin couple adays please help. Me,  my device is rooted but superuser request is not working, device is s7 edge android 8, api 26, i used your canary channel. Help and guide me please.

**Comment by hsheidaryarad** [comment]
why closed?

**Comment by Didgeridoohan** [comment]
https://github.com/topjohnwu/Magisk#bug-reports
