### ISSUE TITLE
Magisk manager update fails to be installed

### ISSUE THREAD

**Issue by TheK0tYaRa** [topjohnwu/Magisk#2998]
From version `07f712a1 (291)` to version `7.5.1 (267) (7)`

**Comment by Didgeridoohan** [comment]
That's not an update... That's a downgrade.

1 - Uninstall 291
2 - Install 267
3 - Close this GitHub issue.

**Comment by TheK0tYaRa** [comment]
oh, i had wrong update channel selected.
