### ISSUE TITLE
隱藏 Magisk Manager 失敗

### ISSUE THREAD

**Issue by Trevor1112** [topjohnwu/Magisk#2999]
Pixel 4 XL Android 11 beta 隱藏 Magisk Manager 失敗
Log: [https://drive.google.com/file/d/10n8IR-NAqaiumHJudLizLqyp1LottA38/view?usp=drivesdk](https://drive.google.com/file/d/10n8IR-NAqaiumHJudLizLqyp1LottA38/view?usp=drivesdk)

**Comment by Didgeridoohan** [comment]
Duplicate of #2975 

Please close

**Comment by Trevor1112** [comment]
Manager Canary is failure for me too
