### ISSUE TITLE
MagiskHide: Error occurred... Samsung stock boot.img

### ISSUE THREAD

**Issue by Badshah-k** [topjohnwu/Magisk#30]
Hi topjohnwu,

Some Samsung users, including myself, have reported Magisk Hide error on XDA support thread.

The issue is most likely with stock boot.img as a modified version of boot.img works without any issues.

Please see attached logs and boot.img files.

Magisk Error log messages:
Magisk v9 - "MagiskHide: Error occurred..."
Magisk v10 - "MagiskHide: Cannot read from logcat, abort..."

Hope you can resolve this issue.

Many thanks

[Stock Note 4.zip](https://github.com/topjohnwu/Magisk/files/676072/Stock.Note.4.zip)

[Custom Note 4.zip](https://github.com/topjohnwu/Magisk/files/676080/Custom.Note.4.zip)

**Comment by Badshah-k** [comment]
Just like to report the following issues have now been fully resolved on latest version of Magisk released today:
Magisk v9 - "MagiskHide: Error occurred..."
Magisk v10 - "MagiskHide: Cannot read from logcat, abort..."
Magisk v10 - "MagiskHide: Cannot monitor am_proc_start, abort..."

Many thanks for a quick resolution!

**Comment by koko115** [comment]
I still have problem with am_proc_start in 170101 on galaxy s7
![screenshot_20170103-001804](https://cloud.githubusercontent.com/assets/24860056/21597389/a0e7f76c-d14a-11e6-9704-0bc5ef3ff6b0.png)

**Comment by Badshah-k** [comment]
I think you need to install the latest version of Magisk manager from play store, including superuser topjohnwu r1, see screenshot:
![screenshot_2017-01-03-00-21-05 1289](https://cloud.githubusercontent.com/assets/23137114/21597951/0b578892-d14b-11e6-88bc-99c3e43b9cf2.png)

**Comment by topjohnwu** [comment]
Samsung kernel seems to hide namespace of processes.
Not sure if it is something to do with Knox.
However, this is already listed in the known issues in Magisk main thread.
