### ISSUE TITLE
[Request] Disable Animations option (part2)

### ISSUE THREAD

**Issue by Fruity-0** [topjohnwu/Magisk#3000]
I have a new phone and had to find a meaningful Android screen recorder and it took a while. I would ask you to open the topic and move the post to that topic or continue it here.
At the bottom, a video showing the line.

[LINK VIDEO](http://31.6.70.6/pliki/newtone/pliki/1.mp4)

**Comment by Didgeridoohan** [comment]
That's the stable Manager... Bug reports are only relevant if you are using the Canary releases.

**Comment by Fruity-0** [comment]
Where is the version info I have on my phone?

**Comment by Didgeridoohan** [comment]
What do you mean? It is very easy to see that you are using the stable release Manager rather than the Canary release. They look completely different... Try again with the Canary Manager.

**Comment by Fruity-0** [comment]
OK, I will check, although I am a little worried about the stability of the system or other unannounced situations, because you never know.
