### ISSUE TITLE
安裝 Magisk Manager 導致無法接收簡訊

### ISSUE THREAD

**Issue by Trevor1112** [topjohnwu/Magisk#3001]
Pixel 4 XL Android 11 beta
經反覆測試後發現安裝Magisk Manager會導致無法接收簡訊，移除Manager但不移除Magisk可以正常接收簡訊。
Log: [https://drive.google.com/file/d/10n8IR-NAqaiumHJudLizLqyp1LottA38/view?usp=drivesdk](https://drive.google.com/file/d/10n8IR-NAqaiumHJudLizLqyp1LottA38/view?usp=drivesdk)

**Comment by DenyDarko** [comment]
07-19 18:19:05.125   867   875 I Magisk  : proc_monitor: [com.google.android.apps.messaging] PID=[18799] UID=[10204]
Did you put messaging app on the hide list?

Remove it

**Comment by Trevor1112** [comment]
No I didn't

**Comment by Perrito213** [comment]
> Pixel 4 XL Android 11 beta
> 經反覆測試後發現安裝Magisk Manager會導致無法接收簡訊，移除Manager但不移除Magisk可以正常接收簡訊。
> Log: [https://drive.google.com/file/d/10n8IR-NAqaiumHJudLizLqyp1LottA38/view?usp=drivesdk](https://drive.google.com/file/d/10n8IR-NAqaiumHJudLizLqyp1LottA38/view?usp=drivesdk)

**Comment by Perrito213** [comment]
> 07-19 18:19:05.125   867   875 I Magisk  : proc_monitor: [com.google.android.apps.messaging] PID=[18799] UID=[10204]
> 
> Did you put messaging app on the hide list?
> 
> Remove it and try again.
> 
> Only put apps need to hide root in there. Remove everything else.

**Comment by Perrito213** [comment]
> > Pixel 4 XL Android 11 beta
> > 經反覆測試後發現安裝Magisk Manager會導致無法接收簡訊，移除Manager但不移除Magisk可以正常接收簡訊。
> > Log: [https://drive.google.com/file/d/10n8IR-NAqaiumHJudLizLqyp1LottA38/view?usp=drivesdk](https://drive.google.com/file/d/10n8IR-NAqaiumHJudLizLqyp1LottA38/view?usp=drivesdk) 
> 
>

**Comment by RikkaW** [comment]
I have the same problem (Pixel 4), but I "solve" the problem by temporarily disable SELinux.

**Comment by Trevor1112** [comment]
I think this is a bug

**Comment by osm0sis** [comment]
@RikkaW, can you identify the sepolicy rules at fault?

**Comment by 8lexliu** [comment]
I encountered the same issue, "solved" it by rebooting to safe mode, and when the messaging function returned to normal exit safe mode.
