### ISSUE TITLE
Magnetor module poco f1

### ISSUE THREAD

**Issue by senseev** [topjohnwu/Magisk#3002]
I am having issue in flashing magnetor module in my Poco F1 miui12 , pleas help me or give any suggestions

**Comment by Didgeridoohan** [comment]
Suggestion: close this issue and contact the creator of the module instead. Not a Magisk issue.

**Comment by senseev** [comment]
> Suggestion: close this issue and contact the creator of the module instead. Not a Magisk issue.

How can I contact about it

**Comment by Didgeridoohan** [comment]
No idea... Ever heard DuckDuckGo, Google, Bing, etc?

And: please close so that John or Chris doesn't have to...
