### ISSUE TITLE
Noticed the same with OnePlus Android 11 Beta 1 but hadn't identified the reason. You're right, no /apex in the ramdisk!

### ISSUE THREAD

**Issue by Perrito213** [topjohnwu/Magisk#3003]
Noticed the same with OnePlus Android 11 Beta 1 but hadn't identified the reason. You're right, no /apex in the ramdisk!

![Screenshot_20200717-130749](https://user-images.githubusercontent.com/2858716/87807364-8bef7b80-c82e-11ea-8005-7df759b537cc.jpg)

Pixel devices on the Beta must still have /apex or something.

_Originally posted by @osm0sis in https://github.com/topjohnwu/Magisk/issues/2994#issuecomment-660191434_

**Comment by osm0sis** [comment]
Why? Stop.
