### ISSUE TITLE
Oxygen os in poco f1

### ISSUE THREAD

**Issue by senseev** [topjohnwu/Magisk#3005]
I am having problem to use any version of Google camera, in my customer rom of oxygen is 10 in Poco f1 .pleas suggest any solution

**Comment by vdbhb59** [comment]
> I am having problem to use any version of Google camera, in my customer rom of oxygen is 10 in Poco f1 .pleas suggest any solution

What has this got to do with Magisk??

**Comment by senseev** [comment]
> > I am having problem to use any version of Google camera, in my customer rom of oxygen is 10 in Poco f1 .pleas suggest any solution
> 
> What has this got to do with Magisk??

I have no idea which magisk can help me,suggest me if you have any of it
