### ISSUE TITLE
Banking App Detected Root on Magisk Hide

### ISSUE THREAD

**Issue by malembo98** [topjohnwu/Magisk#3009]
This week after updating my banking apps they started to detected root
While using "Magisk Hide" and Renaming the Magisk Manager and Removing the TWRP Folder
How is this possible?

**Comment by malembo98** [comment]
SafetyNet Check **Passed**

**Comment by mu198** [comment]
The newest cannary build ?

**Comment by topjohnwu** [comment]
#1152
