### ISSUE TITLE
Reboot to recovery starts original recovery instead of Magisk on Huawei Honor 10, EMUI 9

### ISSUE THREAD

**Issue by cawidtu** [topjohnwu/Magisk#3012]
Since commit 8c4fd759c6fb5139f80a3416c6c2da7f2f2bd6f5 Magisk no longer works on may Huawei Honor 10, EMUI 9 vendor, OpenKirin AEX Beta 1 P1 Custom ROM. When rebooting to recovery, the originally installed recovery program (e.g. TWRP) is started instead of Magisk. Reverting the commit allows me to run the latest Magisk (f1fb7404c20dbdcb32517e2f870f7b5a5d8a7386) when booting through recovery.

I understand the critical commit is meant to retain a way of booting the original recovery but I do not understand exactly how I am supposed to boot Magisk with this commit implemented.

**Comment by topjohnwu** [comment]
Patch recovery ramdisk with the recovery mode option turned on
