### ISSUE TITLE
SAR and A/B interactions break internal install on Nintendo Switch

### ISSUE THREAD

**Issue by classic-gentleman** [topjohnwu/Magisk#3014]
This is quite peculiar but I believe is a legitimate case nevertheless.

As you may be aware, some hardware revisions of the Nintendo Switch are amenable to modding and Android ports have been created for it. Usually the port is installed to the SD card and it's straightforward. My particular setup, though, has Switchroot Pie installed to the eMMC, side by side with HorizonOS (and Ubuntu Linux, for the matter).

The HOS partitioning scheme is regular GPT, but it does reserve some partition names, of note:

```
PRODINFO -> /dev/block/mmcblk0p1
PRODINFOF -> /dev/block/mmcblk0p2
BCPKG2-1-Normal-Main -> /dev/block/mmcblk0p3
BCPKG2-2-Normal-Sub -> /dev/block/mmcblk0p4
BCPKG2-3-SafeMode-Main -> /dev/block/mmcblk0p5
BCPKG2-4-SafeMode-Sub -> /dev/block/mmcblk0p6
BCPKG2-5-Repair-Main -> /dev/block/mmcblk0p7
BCPKG2-6-Repair-Sub -> /dev/block/mmcblk0p8
SAFE -> /dev/block/mmcblk0p9
SYSTEM -> /dev/block/mmcblk0p10
USER -> /dev/block/mmcblk0p11
```

Herein lies the problem. `mmcblk0p10`, that is, `SYSTEM`, is being confused for an A/B system partition because of the case insensitive compare here https://github.com/topjohnwu/Magisk/blob/f1fb7404c20dbdcb32517e2f870f7b5a5d8a7386/native/jni/init/mount.cpp#L67 and the inexistent slot here https://github.com/topjohnwu/Magisk/blob/f1fb7404c20dbdcb32517e2f870f7b5a5d8a7386/native/jni/init/mount.cpp#L246

A solution would be to _invert_ the tested scenario  in `SARBase::mount_system_root` and look for the NVIDIA naming scheme _first_, then with `system[+slot]`, and `abort` in case that fails.

Second possibility would be to attempt case sensitive first, then failing all that resort to case-insensitive. It would be more complicated though.

A third possibility is to completely split the code paths between A/B and non-AB SAR.

My vote goes to solution 1, for least impact.

**Comment by classic-gentleman** [comment]
Proposed patch:
[switch_ab.patch.txt](https://github.com/topjohnwu/Magisk/files/4954108/switch_ab.patch.txt)

**Comment by topjohnwu** [comment]
Hi, thanks for the detailed report!

Unfortunately, things aren't as simple as you assumed 😉, the comparison is explicitly case insensitive because on devices such as Samsung use full caps `SYSTEM` as the partition name.
There is literally no way Magisk can differentiate between these cases, so again, unfortunately, your current use case will not be supported.

There is a recommendation to fix this: don't use legacy SAR and switch to use 2SI instead. In that case, Magisk will not do the mounting, but rather defer to the original `init` to do the early mounting.

But 2SI depends on Android 10+, and I'm not sure about whether Android 10 is supported on switchroot.

**Comment by classic-gentleman** [comment]
I understand your point; however I guess the patch I proposed (the first approach) can't break anything. Unless the Tegra partition name might conflict with something else?

**Comment by topjohnwu** [comment]
Oh, so switchroot is using Tegra naming scheme for Android?

**Comment by classic-gentleman** [comment]
Yes, since the Switch _is_ a Tegra T210 device!

**Comment by topjohnwu** [comment]
Sure, I'll reopen this issue to keep track of this.
You proposed fix doesn't seem to break things at first glance.

**Comment by classic-gentleman** [comment]
I can attest this is working for me™ 😜

Now, if a more careful approach turns out necessary, I think it is possible to grab Switch-specific props or cmdline and adjust accordingly. But the simplest approach is the one in the patch and I'm not foreseeing conflicts with other devices.

**Comment by osm0sis** [comment]
Submit the patch as a pull request?

**Comment by classic-gentleman** [comment]
Thanks, gentlemen!
