### ISSUE TITLE
Custom recovery - Power menu security

### ISSUE THREAD

**Issue by ArmynC** [topjohnwu/Magisk#3020]
Right now, with Magisk on Samsung via Custom Recovery there's no way (beside unstable [xposed module](https://github.com/Firefds/FirefdsKit/commit/7311193ad946212bcdf338e7a4840439a9053ed4)) to disable/pin protect the power menu if the device is locked down (secure keyguard). Is there any way to resolve it? Thanks!

**Comment by osm0sis** [comment]
Not a Magisk development issue or question. Ask on xda.
