### ISSUE TITLE
Preserve force encryption doesn't stay unticked.

### ISSUE THREAD

**Issue by isrgish** [topjohnwu/Magisk#3025]
I'm trying to unencrypt my device.

When I untick the box by preserve force encryption and then reopen Magisk Manager i find its ticked again. I found on the net to add a `.magisk` file in `/cache` or `/data`. I tried this but it doesn't help.

Is there another way to get my device unecrypted?

Thank You,
Isr

**Comment by martyfender** [comment]
After doing this, did you format data, or factory reset the device, to create a new, unencrypted, data partition? You can't magically just unencrypt an existing data partition, as far as I know. This is based on my extensive experience with several older Android 6 devices.

**Comment by Didgeridoohan** [comment]
Just to clarify: the checkbox in itself does nothing. It only has effect when you install Magisk or patch a boot/recovery image.

If you want to remove the encryption from your device you need to uncheck, install Magisk and then follow the advice given above about formatting /data.

And please close this issue since this is not the place for general troubleshooting. Spare John or Chris from having to do it for you...

**Comment by mu198** [comment]
Yes look the last comments #2975

**Comment by isrgish** [comment]
I did a factory reset after patching the boot.img file. I still can't get it to be unencrypted.

Where can I ask these questions?

**Comment by Didgeridoohan** [comment]
I believe a factory reset isn't enough... A format is necessary.

XDA would be a good place.

**Comment by isrgish** [comment]
I formatted the userdata partition but I still have it encrypted.

**Comment by Didgeridoohan** [comment]
Well, did you first install Magisk with the preserve forced encryption flag disabled? Or any other zip to do the same? Unless you have done that prior to formatting data, nothing will happen...

**Comment by isrgish** [comment]
Yes These are the steps I followed

1. Installed Magisk Manager
2. Unticked the Preserve forced encryption.
3. Patched my boot.img.
4. Flashed patched boot.img.
5. Erased userdata partition.
6. Formatted userdata partition.
7. rebooted.

**Comment by Didgeridoohan** [comment]
If that didn't work there's nothing more I can help with. You'd likely be better off asking other users of you device on a forum like XDA.
