### ISSUE TITLE
How to successfully run commands such as gawk and rsync(2)

### ISSUE THREAD

**Issue by zhangweildlh** [topjohnwu/Magisk#3027]
https://github.com/topjohnwu/Magisk/issues/3023

Thank you for your reply!
I have set a delay in service.sh:"
... ...
sleep 15m
gawk
/data/data/io.neoterm/files/usr/bin/gawk
"
But these commands still cannot run successfully.

Later, I wrote these commands into the jj1.sh, and set the delay to run the jj1.sh in service.sh.
service.sh:"
sleep 15m
/data/data/io.neoterm/files/usr/bin/sh $MODPATH/system/data-app/jj1.sh"(Run Successfully)

jj1.sh:"
export LD_PRELOAD=/data/data/io.neoterm/files/usr/lib/libandroid-support.so
export LD_LIBRARY_PATH=/data/data/io.neoterm/files/usr/lib
export PATH=/data/data/io.neoterm/files/usr/bin:/data/data/io.neoterm/files/usr/bin/applets:$PATH
gawk
/data/data/io.neoterm/files/usr/bin/gawk"

But these commands in the jj1.sh still cannot run successfully

**Comment by Didgeridoohan** [comment]
Come on... Github issues isn't got general troubleshooting of your scripts, but for bug reports. Take it to XDA or other forum of choice instead.

And please close this do that John or Chris doesn't have to.

**Comment by zhangweildlh** [comment]
> Come on... Github issues isn't got general troubleshooting of your scripts, but for bug reports. Take it to XDA or other forum of choice instead.
> 
> And please close this do that John or Chris doesn't have to.
Thank you
