### ISSUE TITLE
Magisk Canary Manager is detecting wrong system format

### ISSUE THREAD

**Issue by Cyberavater** [topjohnwu/Magisk#3028]
Magisk Canary says My device is not A/B while Treble info says it's A/B. Even the GSI I'm using is A/B variant.

![Screenshot_20200728-122528](https://user-images.githubusercontent.com/32187927/88628309-45efae80-d09d-11ea-9af5-ecfae11bab14.png)
![Screenshot_20200728-122553](https://user-images.githubusercontent.com/32187927/88628318-4ab46280-d09d-11ea-8096-44212ac76418.png)

For this reason I think my device reboots to recovery after installing a module.

**Comment by Displax** [comment]
Your device is SAR but not A/B. All correct.
On GSI images and this app it's just wrong and outdated marking of images, when "A/B" means A/B itself and SAR with no real A/B too.
Look at the "Seamless updates" section - it present only on real A/B.

**Comment by Cyberavater** [comment]
But my boot is patched via magisk (by twrp) not recovery (it's only twrp). So, no point rebooting to recovery when boot.img itself is patched.

**Comment by topjohnwu** [comment]
Magisk Manager does not detect your device with dumb properties the device claims to be, it goes through your partitions to determine whether A/B partitions are discovered

**Comment by Cyberavater** [comment]
Understood, but if I install a-only variant GSI my device doesn't boot. So, it must be, A/B! At first I tried installing a-only because Treble Check app said so, then @phhusson recommend that I don't use that app and switch to Treble info to check it, as Treble Check gives wrong info. @phhusson can you say something on this?

**Comment by Cyberavater** [comment]
@topjohnwu Can you at least add a setting so that I can manually tell it to not to boot to recovery after installing module (since boot.img is patched not recovery.img).
