### ISSUE TITLE
Manager log issue

### ISSUE THREAD

**Issue by atarek1** [topjohnwu/Magisk#303]
Hello,
@topjohnwu 
i was investigating in this [issue](https://github.com/topjohnwu/MagiskManager/issues/202)

 i found inside log_monitor.c class below lines of code
`char *const command[] = { "logcat", "-s", "Magisk", "-v", "thread", NULL };
log_pid = run_command(0, &log_fd, "/system/bin/logcat", command);`

so i tried to run this command in android terminal and output was as attached screenshot. i tried to view history and check it but same output. 

i couldn't reach v12.0 code and manager v 4.4.0 to check changes cause it's working there.

i assume that any one have manager log working will be able to find output from this command and i think it's cause of manager log is empty in my case.

`su
logcat -s Magisk -v thread`

I tried to run above command in SU context and results as attached but manager log still empty so i suspect it tries to run this command without SU.

**Edit:**
i flashed new rom:nxteam magma. With magisk 13.3 flashed and without busy box after boot issue still exist then i flashed osm0sis "UPDATE.Busybox.Installer.v1.26.2-ALL-signed" after boot manager start log successfully, magisk.log and magisk_last.log created in /cache. After that
i flashed unfied hosts from magisk and reboot then manager stoped logging again. I tried to flash kernel then magisk but same result busybox system or systemless no results also. 

Could this info guide anyone to relate any troubleshooting approach
any advice.

Ps: current status:
Magisk v13.3
Manager v 5.1
Osm0sis systemless busybox
Modules: unifed hosts , viper4android fx by ahrion and audio modification lib by ahrion.
Safety net passes and root is functional flawlessly.

Regards,
Ahmed
**Matlog : [log.txt](https://github.com/topjohnwu/Magisk/files/1162482/log.txt)** 
![screenshot_20170720-123923](https://user-images.githubusercontent.com/29482903/28415003-2c5df202-6d4e-11e7-803a-545d7f1110ae.jpg)
![screenshot_20170720-144215](https://user-images.githubusercontent.com/29482903/28418462-109d9172-6d5c-11e7-82ac-2b40a86b0a50.jpg)
![screenshot_20170720-144229](https://user-images.githubusercontent.com/29482903/28418461-109cdfac-6d5c-11e7-9251-3187687e3d96.jpg)

**Comment by jenslody** [comment]
I found a possible reason for this issue (at least for @atarek1): a cleanup of log-files in cache-folder done by a script running in post-init-stage (after post-fs-data) done by phantom-kernel.
See: https://forum.xda-developers.com/showpost.php?p=73230207&postcount=17612 for more details.
