### ISSUE TITLE
Additional setup stuck

### ISSUE THREAD

**Issue by DeltaOn3X** [topjohnwu/Magisk#3030]
Hi, 

after updating my SM-N975F (Note 10+) to the latest firmware, i cant get magisk canary running. After patching the firmware it always stuck at the step, where you need to do the additional setup after running the Manager for the first time. It just stuck there until i close the app. This step usually requires seconds and not 15 minutes or longer. When i change to the stable/beta Manager, everything works but i cant change back to Canary so i have to uninstall stable and install canary again. After that i still need to rename the Manager again which also fails on the canary Version. 

On the firmware before everything worked fine.

I dont have any logs unfortunately and i need the canary version because of my banking apps. The stable is not an option. Im using no magisk atm and i just want to ask if this is a known issue and just want to let you guys know. 

Maybe someone has the same problem like me. 👍

**Comment by mu198** [comment]
Yes it is, just call magisk the next time you hide it, Manage, yes without r and it worked for me (sm-p610 / tab s6 lite)

**Comment by DeltaOn3X** [comment]
> Yes it is, just name magisk the next time you hide it, Manage, yes without r and it worked for me (sm-p610 / tab s6 lite)

Tank you for the reply, ill try it later or maybe i wait for an update. But still a huge thank you !

**Comment by mu198** [comment]
Yes, the problem itself was listed in # 2975, so I found the solution😉

**Comment by DeltaOn3X** [comment]
So ill give it a try with patching and seting up magisk with the stable manager, after that i switch to the canary manager and try to hide it with the name "manage" without "r"

**Comment by DeltaOn3X** [comment]
FYI i still didnt try the "workaround".i will wait for an update for this. Should this be open until it got fixed?

**Comment by osm0sis** [comment]
Noticed this on my Nexus 7 when I updated to Android 10 with wiped /data. Basically it downloads the zip but then fails to do the setup.

I found rebooting again sometimes works, and flashing the Magisk zip in recovery definitely works.

Looks like another issue from the recent Kotlin changes in Manager.

**Comment by unixandria-xda** [comment]
> Noticed this on my Nexus 7 when I updated to Android 10 with wiped /data. Basically it downloads the zip but then fails to do the setup.
> 
> I found rebooting again sometimes works, and flashing the Magisk zip in recovery definitely works.
> 
> Looks like another issue from the recent Kotlin changes in Manager.

I can reproduce consistently on a Pixel 3 xl and OnePlus 7 pro on a clean install.
Installing magisk directly works fine a d gets rid of the additional setup prompt

**Comment by DeltaOn3X** [comment]
> > Noticed this on my Nexus 7 when I updated to Android 10 with wiped /data. Basically it downloads the zip but then fails to do the setup.
> > I found rebooting again sometimes works, and flashing the Magisk zip in recovery definitely works.
> > Looks like another issue from the recent Kotlin changes in Manager.
> 
> I can reproduce consistently on a Pixel 3 xl and OnePlus 7 pro on a clean install.
> Installing magisk directly works fine and gets rid of the additional setup prompt

So you mean like osm0sis said, flashin magisk zip trough recovery would skip the additional setup?

**Comment by DeltaOn3X** [comment]
FYI, a new firmware got released for my Note 10+. Dont know if i should give it a another try

**Comment by unixandria-xda** [comment]
> > 
> > 
> > I can reproduce consistently on a Pixel 3 xl and OnePlus 7 pro on a clean install.
> > Installing magisk directly works fine and gets rid of the additional setup prompt
> 
> So you mean like osm0sis said, flashin magisk zip trough recovery would skip the additional setup?


That's essentially the same thing as through magisk manager provided data is decrypted in recovery so yes

**Comment by DeltaOn3X** [comment]
Installing the zip via recovery (stock) doesnt work. Hiding Magisk with "manage" after disabling google play protect works fine. Safetynet still fails after hiding the manager and hiding the google play services. Hidepropsconfig doesnt fix it. 

Im back to stock right now and wait for an fix. My bankin apps detected that ive rooted my phone so i have to go back to stock

**Comment by osm0sis** [comment]
Flash the Magisk zip manually in Manager's module page, that's the other option.

**Comment by DeltaOn3X** [comment]
> Flash the Magisk zip manually in Manager's module page or using Manager's Direct install option, that's the other option that was explained.
> 
> There's a different workaround for "Manage", see its own issue thread for that.

Sorry for the late reply, it doesnt matter what ive tried. Almost every workaround just failed. 

The workaround with "manage" works and i already saw the post. That worden for

**Comment by DeltaOn3X** [comment]
FYI there is a new update out, ill try it tomorrow and let you guys now if its workin again or not.

**Comment by DeltaOn3X** [comment]
Ok i didnt get the time to root my phone with the new version, did anyone else tried it ?

**Comment by osm0sis** [comment]
I tried it on my Nexus 7 again with 293, it's easy to reproduce.

```
mkdir /data/adb/disabled
mv /data/adb/* /data/adb/disabled/
reboot
```

then open Manager.

It continues to appear to download the Magisk zip but then fails to unpack it into /data/adb/magisk and was broken by the recent Kotlin rewrites.

CC: @topjohnwu @diareuse

**Comment by topjohnwu** [comment]
@osm0sis I will remove this feature completely and just prompt user to reinstall Magisk

**Comment by osm0sis** [comment]
Can Manager even install Magisk in that state? I don't think it can, since there's no busybox.

**Comment by DeltaOn3X** [comment]
Is there a reason why i cant install exposed zips like when i try to install edxposed canary i cant install it cuz it always fails with something like "unsupported file".
I can only install the framework from the modules but there isnt the canary one. 

I know it doesnt have something to do with this issue but yh. And btw when you go into magiskhide, there is typo (i guess) cuz it says MagiskHid without e :D

**Comment by topjohnwu** [comment]
@osm0sis yes it can, that's how boot image patch works: the zip itself serves the busybox

**Comment by DeltaOn3X** [comment]
I just tried it with the latest Version and it still stuck at the additional setup, hiding Manager is not workin everytime

**Comment by DeltaOn3X** [comment]
@mu198 where did you get the Info, that this Bug is still present ? A new update is out and i dont want to wipe my phone several times just to run into the additional setup loop. I didnt find anything on Twitter about this bug. 

I honestly dont know to give it another try nor spamming this issue everytime a update got released. :/

**Comment by mu198** [comment]
What I said was based on the hardware certificate 
![Screenshot_20200824-184214.jpg](https://user-images.githubusercontent.com/65677888/91072403-bf95a080-e639-11ea-92bf-5fa3d50f4ddc.jpg)

https://www.xda-developers.com/safetynet-hardware-attestation-hide-root-magisk/amp/?__twitter_impression=true

**Comment by mu198** [comment]
@DeltaOn3X This tweet was posted by @topjohnwu  This tweet was retweeted by @topj and he described the problem back in March

**Comment by DeltaOn3X** [comment]
Ahh yeah i already saw that and the fix you provided should work. But you also said, that the additional setup bug is still present and topjohnwu said it on Twitter :D. 

I think ill give it a try when some dev here will give me the go

**Comment by mu198** [comment]
Oh then I unfortunately expressed myself wrong, meant ehr only the "false" safety net.... 

Since my setup works on all devices, if I disable play protect, I can't say anything more about iteven😉

@DeltaOn3X

**Comment by mu198** [comment]
Have you tried it al with disable "play protect"??

**Comment by DeltaOn3X** [comment]
No but maybe it would help i dont know. I should give it a try to let you know.

**Comment by mu198** [comment]
Yes that would be nice 😉

**Comment by osm0sis** [comment]
Play Protect would have no effect on this issue, since it's a failure of an already installed app to download and unzip something to a specified folder, which it had no problem doing previous to the Kotlin rewrite.

**Comment by DeltaOn3X** [comment]
> Play Protect would have no effect on this issue, since this issue is a failure of an already installed app to download and unzip something to a specified folder, which it had no problem doing previous to the Kotlin rewrite.
> 
> I don't believe anything has changed that would fix it yet. And no need to fully wipe to check, see my previous comment for instructions: [#3030 (comment)](https://github.com/topjohnwu/Magisk/issues/3030#issuecomment-674419262)
> 
> @diareuse, any chance you could look at this? It might be pretty simple to fix, since it does appear to download the zip without issue.

I had to wipe my device because i turned off oem unlock haha, im about to root my phone and i dont know if i should wait for an update which maybe fix this issue. Is there any difference when i use the workaround by letting the 7.5.1 manager doing the additional setup and than hide the manager with the canary version ?

**Comment by mu198** [comment]
Do it right away with the Canarian version.... 
If you get a vbmeta error because you patched the AP use this one away with the boot.img
https://forum.xda-developers.com/showpost.php?p=79902328&postcount=29

If you want to pack the patched boot.img, into a .tar file, use the normal 7zip and not the modified one.

**Comment by DeltaOn3X** [comment]
Great news, with the latest version, the additional setup works perfect. I think we can close this.

**Comment by osm0sis** [comment]
Can confirm! @topjohnwu must have fixed the issue in his further cleanups without realizing. 🎉

**Comment by DeltaOn3X** [comment]
Pretty happy to be rooted again, thank you guys for the hard work and @osm0sis for the answers 👍 Even my bank app on the latest version works :D 

This might be offtopic but maybe usefull for @mu198. You dont need the zip file anymore, the hide props config module can do it now. Just use a terminal, su -> props -> option 2 "FORCE basic key attestation" and use the recommended model from the module. This will change hardware to basic and pass the safetynet easily.

**Comment by mu198** [comment]
@DeltaOn3X Yes that's nice, I'll try 😉

**Comment by mu198** [comment]
Yes thank you has worked.... 🤟
![IMG_20200825_051447](https://user-images.githubusercontent.com/65677888/91118767-00b99f00-e692-11ea-9d8f-077afb600646.jpg)

**Comment by Kollachi** [comment]
Tried the latest Canary version on my Oneplus 8 Pro and the setup fails all the time. What happened again?

**Comment by DeltaOn3X** [comment]
Try to install the zip in recovery

**Comment by Kollachi** [comment]
> Try to install the zip in recovery

Yes that's what I did and it worked.
