### ISSUE TITLE
Magisk permission overlay not showing

### ISSUE THREAD

**Issue by Andrew-afk** [topjohnwu/Magisk#3032]
Even if automatic action is Allow, the app does not get root privileges, now only the apps i prevously allowed works...
Also noticed this on the log:

--------- beginning of main
--------- beginning of system
(Magisk starting)
--------- beginning of crash
07-29 13:03:34.349  2557  3822 I Magisk  : ** boot_complete triggered
07-29 13:04:08.718  2557  2565 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[5771] UID=[10031]
07-29 13:04:41.433  2557  4319 W Magisk  : su: request rejected (10136) 
07-29 13:04:41.434  2557  4319 E Magisk  : write failed with 32: Broken pipe
07-29 13:05:01.382  2557  5343 W Magisk  : su: request rejected (10149)

Magisk binaries still working, so i guess there is a command line to allow root privileges to apps manually?

**Comment by osm0sis** [comment]
#2944
