### ISSUE TITLE
Incompatible With Android 11 GSIs

### ISSUE THREAD

**Issue by Scirese** [topjohnwu/Magisk#3039]
I tried to use the latest canary of magisk to root android 11 gsi on Redmi note 7. It just reboot into fastboot mode. I tried anyway that i know to install magisk,but it just do not boot.

Vendor:Lineage os 17.1 -20200716 nightly
GSI image : Google offical Android 11 Beta2
Magisk : 97b72a59

**Comment by osm0sis** [comment]
No. Incompatible with all GSIs. #844
