### ISSUE TITLE
Patched boot.img has no root

### ISSUE THREAD

**Issue by mrmazakblu** [topjohnwu/Magisk#3040]
Using current 20.4 magisk, patch from the app. The patched image boots but has no root. Magisk app shows not installed.

Device came with Android 10
Sar
Uses boot.img with ramdisk so did not use recovery mode.

Device =Blu G90
Mtk 6765

Issue happens both on stock ROM and aosp gsi.

**Comment by osm0sis** [comment]
#2994

**Comment by mrmazakblu** [comment]
> #2994

Does this mean as a work around for now, I just need to unpack boot and add a dir /apex?

**Comment by mrmazakblu** [comment]
Here is the patched img 

[magisk_patched-boot-v20.4.img.zip](https://github.com/topjohnwu/Magisk/files/5013058/magisk_patched-boot-v20.4.img.zip)

**Comment by osm0sis** [comment]
You also need to try latest canary, we don't accept bug reports for anything older.
