### ISSUE TITLE
[BUG] Additional setup mostly wipes device

### ISSUE THREAD

**Issue by ehem** [topjohnwu/Magisk#3041]
Subject says the main point.  After installing MagiskManager it says it "Requires Additional Setup".  If "OK" is selected, no errors or warnings appear, device simply reboots.  All settings are lost and all added Android applications are wiped.  I can confirm device hasn't been entirely wiped as some files remain on the emulated SDcardfs.

This device has been mostly wiped.  Magisk had been installed previously and the boot image has remained patched.  With the wiping, I'm trying to reinstall MagiskManager, but every time after restart all applications (including MagiskManager) have been wiped.  Device is using FDE, not FBE (hmm, thinking about this does switching between FDE/FBE require re-patching the boot image?).

> --------- beginning of main
> ** boot_complete triggered
> ** post-fs-data mode running
> * Initializing Magisk environment
> su: cannot find manager
> * Mounting mirrors
> mount: /sbin/.magisk/mirror/vendor
> mount: /sbin/.magisk/mirror/data
> link: /sbin/.magisk/mirror/system
> link: /sbin/.magisk/mirror/product
> * Magisk environment setup incomplete, abort
> ** late_start service mode running
> ** boot_complete triggered

**Comment by vdbhb59** [comment]
Give more details like what ROM, what model of phone, what Magisk Version, including Magisk Manager version. How did you flash Magisk, etc.
Plus some more log details.

**Comment by osm0sis** [comment]
Yeah, this is odd, since for any others who've reported in Additional Setup just plain doesn't work at all right now.

**Comment by ehem** [comment]
Upon further experimentation it seems I ran into fun security feature on device.  Seems the device manufacturer somehow made it so writes to a particular range of blocks _appear_ to succeed, but are silently discarded when Android is running.  If one rearranges things such that userdata is overlapping this area you don't get any hints that everything is _silently failing_.

Sorry about the noise, looks like this isn't actually a problem with MagiskManager, but instead a really annoying device security misfeature.

**Comment by osm0sis** [comment]
Interesting to hear about. Let us know if you find a workaround we should add to the installer.
