### ISSUE TITLE
Add files to /system is not working as declared in details.md !

### ISSUE THREAD

**Issue by McPcholkin** [topjohnwu/Magisk#3043]
Hi,  i already open this issue [3035](https://github.com/topjohnwu/Magisk/issues/3035) and answer be:

>@topjohnwu This is done to prevent bootloops, adding new items in top level mount points are explicitly disabled

In my opinion it incorrect, because i found in [documentation](https://github.com/topjohnwu/Magisk/blob/master/docs/details.md) this:

>Even though the mounting logic is pretty complicated, the final result of Magic Mount is actually pretty simple. For each module, the folder `$MODPATH/system` will be recursively merged into the real `/system`; that is: existing files in the real system will be replaced by the one in modules' system, and new files in modules' system will be added to the real system.

So it clear says **and new files in >modules' system will be added to the real system.** 

And now it not working, this is incorrect info in documentation or a BUG?

**Comment by topjohnwu** [comment]
LOL trust me, I wrote all the code 😂
I explicitly added the code to ignore adding new items in top level mounts.
Thanks for the reminder though, I'll update the documentation to be more clear about this!

**Comment by McPcholkin** [comment]
@topjohnwu I trust you, just point misunderstanding  in documentation and actual  app logic, i try write module based on documentation and it not work as described in documentation.
P.S.
Thanks you and all team for such useful tool!
