### ISSUE TITLE
magisk manager unable to detect target image

### ISSUE THREAD

**Issue by Songhan17** [topjohnwu/Magisk#3046]
![1](https://user-images.githubusercontent.com/62863341/89250369-32b58380-d647-11ea-904b-91be47bf5e38.png)
![2](https://user-images.githubusercontent.com/62863341/89250371-347f4700-d647-11ea-824b-a141cd980c45.png)
![3](https://user-images.githubusercontent.com/62863341/89250372-3517dd80-d647-11ea-8dac-0ddd5d5e2bff.png)
![4](https://user-images.githubusercontent.com/62863341/89250374-35b07400-d647-11ea-946e-81d4125866f2.png)
Download according to the prompts, installation failed...
MagiskManager-v7.5.1.apk
Magisk-v20.4.zip
please help !!

**Comment by osm0sis** [comment]
Try latest Canary. Bug reports for anything less aren't accepted.
