### ISSUE TITLE
[QUESTION] Is possible unlock the bootloader installing (patching the boot image o something else) Magisk?

### ISSUE THREAD

**Issue by Pignacolor** [topjohnwu/Magisk#3049]
I hope can I ask a question here... I have a Huawei Ascend G510-0100 (Qualcomm processor, android 4 and EMUI 1) with locked bootloader. I'm desperately looking for a solution to unlock it (since I don't have the code and Huawei no longer provides it) but I still haven't found it. So, perhaps in my ignorance, I was wondering ... Is there a way to unlock the bootloader by installing Magisk?

**Comment by DanGLES3** [comment]
No

**Comment by mu198** [comment]
By magisk not, but try the dcunlocker, maybe it can do that but unfortunately costs € 4.99
