### ISSUE TITLE
我用ndk-16编译成功了，但是在twrp刷的时候，提示我zip 不对 zip signature verification failed

### ISSUE THREAD

**Issue by supperlitt** [topjohnwu/Magisk#3052]
android 7.1.2 v 1.17 怎么回事？求指导

**Comment by supperlitt** [comment]
https://github.com/topjohnwu/Magisk/issues/531
意思就是说，用测试的签名就可以了？

**Comment by supperlitt** [comment]
应该怎么操作呢，不使用release编译也不行。

**Comment by osm0sis** [comment]
It's not signed with testkeys, just turn verification off in TWRP while you flash it.
