### ISSUE TITLE
v17版本，编译刷机报错，，Updater process ended with signal:11

### ISSUE THREAD

**Issue by supperlitt** [topjohnwu/Magisk#3053]
我编译了。v17版本，python build.py -r all

我是用的ndk-16b，还是说需要用 https://github.com/topjohnwu/FrankeNDK 这个ndk编译？
degist我已经通过了。
谢谢

update-binary 文件差别较大，我的5M，官方的2M+

**Comment by supperlitt** [comment]
我觉得可能是，我用的v17tree的代码。对应的link代码，有问题。导致。这种应该怎么clone呢？

**Comment by topjohnwu** [comment]
自己看看 README 吧

**Comment by supperlitt** [comment]
大佬，最后问一个问题，，，最新版的支持 7.1系统不？

**Comment by supperlitt** [comment]
新版本可以刷入，sandfish 7.1.2,但是手机无法开启。
所以我想用 v17.1。
但是需要历史版本的对应的连接符号native.这个应该怎么弄，我单独下载下来的，我怀疑是有问题的。所以。。再次麻烦
