### ISSUE TITLE
Latest Magisk manager auto reject root permission

### ISSUE THREAD

**Issue by Bob-YsPan** [topjohnwu/Magisk#3054]
Sorry press send before write problems...

The latest magisk manager can't grant root permission to app that not acquired permission before (or remove permission before)

Sorry for my bad English...
My device:
ZenFone 2 ZE551ML
Android 6.0.1

The log(Only error occurs record) : 

08-07 18:09:42.187   291 12218 D Magisk  : su: request from pid=[12214], client=[9]
08-07 18:09:42.187   291 12218 D Magisk  : su: request from uid=[10368]
08-07 18:09:42.187   291 12218 D Magisk  : magiskdb: query su_biometric=[0]
08-07 18:09:42.187   291 12218 D Magisk  : su: waiting child pid=[12219]
08-07 18:09:42.187 12219 12219 D Magisk  : su: fork handler
08-07 18:09:42.187 12219 12219 D Magisk  : su: use global namespace
08-07 18:10:30.707   291 12218 D Magisk  : su: return code=[0]
08-07 18:10:33.267   291 12665 D Magisk  : su: request from pid=[12663], client=[11]
08-07 18:10:33.267   291 12665 D Magisk  : su: request from uid=[10368]
08-07 18:10:33.267   291 12665 D Magisk  : magiskdb: query su_biometric=[0]
08-07 18:10:33.267   291 12665 D Magisk  : su: waiting child pid=[12666]
08-07 18:10:33.267 12666 12666 D Magisk  : su: fork handler
08-07 18:10:33.267 12666 12666 D Magisk  : su: use global namespace
08-07 18:10:53.467   291 13570 D Magisk  : su: request from pid=[13569], client=[12]
08-07 18:10:53.467   291 13570 D Magisk  : su: request from uid=[10263]
08-07 18:10:53.467   291 13570 D Magisk  : magiskdb: query su_biometric=[0]
08-07 18:10:55.427   291 12665 D Magisk  : su: return code=[0]
08-07 18:10:55.427   291 13570 E Magisk  : read (4 != -1) failed with 104: Connection reset by peer
08-07 18:10:55.437   291 13570 W Magisk  : su: request rejected (10263)
08-07 18:11:04.507   291 13697 D Magisk  : su: request from pid=[13694], client=[9]
08-07 18:11:04.507   291 13697 D Magisk  : su: request from uid=[10368]
08-07 18:11:04.507   291 13697 D Magisk  : magiskdb: query su_biometric=[0]
08-07 18:11:04.507   291 13697 D Magisk  : su: waiting child pid=[13698]
08-07 18:11:04.507 13698 13698 D Magisk  : su: fork handler
08-07 18:11:04.507 13698 13698 D Magisk  : su: use global namespace

**Comment by Displax** [comment]
Duplicate https://github.com/topjohnwu/Magisk/issues/2983
