### ISSUE TITLE
新版本可以刷入，sandfish 7.1.2,但是手机无法开启。

### ISSUE THREAD

**Issue by magicmomentmx** [topjohnwu/Magisk#3058]
新版本可以刷入，sandfish 7.1.2,但是手机无法开启。
所以我想用 v17.1。
但是需要历史版本的对应的连接符号native.这个应该怎么弄，我单独下载下来的，我怀疑是有问题的。所以。。再次麻烦

_Originally posted by @supperlitt in https://github.com/topjohnwu/Magisk/issues/3053#issuecomment-670798229_

**Comment by supperlitt** [comment]
大神，帮帮我吧。。。高版本可以刷入，但是无法开机。测试机器：6p和pix1
低版本，就遇到了输入的错误，这种，要分析的话，应该怎么着手呢？或者有没有联系方式。

**Comment by topjohnwu** [comment]
你測試的都是 Google 手機吧
那 100% 都是保證可以運作的，不會是 Magisk 的問題
