### ISSUE TITLE
[BusyBox] Applet lsof broken functionality

### ISSUE THREAD

**Issue by tytydraco** [topjohnwu/Magisk#3059]
# Issue
Magisk's built-in busybox applet `lsof` (`/sbin/.magisk/busybox/lsof`) is broken.

# Example Usage
`/sbin/.magisk/busybox/lsof /proc`

# Expected Output
```
COMMAND     PID       USER   FD      TYPE             DEVICE  SIZE/OFF       NODE NAME
magiskd     724       root    8r      DIR                0,4         0          1 /proc
lsof      16853       root    3r      DIR                0,4         0          1 /proc
```

# Actual Output
```
...
31965   /system/bin/app_process64       /system/app/OPAppUpgrader/OPAppUpgrader.apk
31965   /system/bin/app_process64       /system/product/overlay/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
31965   /system/bin/app_process64       /vendor/overlay/oneplus_shape_circle
...
```
This output spans for hundreds of lines, showing every running process on the device rather than the running processes in /proc.

The output is equivalent of specifying `/sbin/.magisk/busybox/lsof` without any path.

# Information
* Device: OnePlus 7 Pro
* Magisk: v20.4 (20400)
* Kernel: Stock 4.14 provided by OEM

# Notes
The toybox lsof implementation works correctly.

**Comment by topjohnwu** [comment]
Shouldn't this be an busybox issue rather than a Magisk issue?
@osm0sis any clue on this? I this a bug in my build process or busybox itself behaves like this?

**Comment by osm0sis** [comment]
Not broken, just super simple.

toybox:
```
:/ # lsof --help
usage: lsof [-lt] [-p PID1,PID2,...] [FILE...]

List all open files belonging to all active processes, or processes using
listed FILE(s).

-l      list uids numerically
-p      for given comma-separated pids only (default all pids)
-t      terse (pid only) output
```
Vs.

busybox:
```
:/ # busybox lsof --help
BusyBox v1.31.1-osm0sis (2020-05-06 20:45:25 ADT) multi-call binary.

Usage: lsof

Show all open files
```

As you can see, busybox lsof doesn't accept any command-line arguments, and you'll have to understand and parse the output yourself with grep, etc. if you want to use it. If the busybox output doesn't have what you need then you should use /system/bin/lsof

**Comment by tytydraco** [comment]
I see, thanks for the follow up. I went ahead and switched my script usage to fuser as that seems to work better for my use case.
