### ISSUE TITLE
Unable to access block devices created by mknod regardless of dac permissions.

### ISSUE THREAD

**Issue by ytrezq** [topjohnwu/Magisk#3060]
On my device, `vold` only create block devices for vfat/exfat partition on usb devices.

So in order to format or fsck ext4 partitions, I need to create the block device. Of course doing `mknod ~/public\:8,2 b 8 2;chmod 777 ~/public\:8,2` requires `su` and works

But the resulting file can t be read nor writen because of permissions issue. Even using `su`.

**Comment by unixandria-xda** [comment]
This does not sound like a magisk issue, but a device issue. Remember, just because you are using magisk while doing this, does not make it automatically the fault of magisk.

**Comment by ytrezq** [comment]
@unixandria-xda the secontext of Magisk should always ensure permissions access regardless of background problem. Being root normally prevents you to access anything on recent Android, but Magisk deal with Selinux for that.

 So this is something Magisk forgot to handle. This isn t device specific.

**Comment by topjohnwu** [comment]
@ytrezq show me the `selinux` audit logs, I cannot fix it without any information from you

**Comment by ytrezq** [comment]
> @ytrezq show me the `selinux` audit logs, I cannot fix it without any information from you
Problem is I don’t have a computer right now and amazon constantly cancel my orders while keeping the gift card so I can’t use adb for this right now.

However, I gave you the full repro. So why not doing it yourself on adb or a terminal app?

**Comment by JarlPenguin** [comment]
@ytrezq Why is it so hard to provide a log file?

**Comment by ytrezq** [comment]
I can t connect the device to anything else since I ve no computer.

**Comment by JarlPenguin** [comment]
You can download a terminal app and use the `logcat` command to fetch logs while running the command in a different window.

**Comment by topjohnwu** [comment]
Without proper report, I will not be investigating this issue
