### ISSUE TITLE
Repackage Magisk Manager Does Not Succeed

### ISSUE THREAD

**Issue by Saya47** [topjohnwu/Magisk#3061]
Hello!

When I try: `Magisk Manager -> Settings -> Hide Magisk Manager` and set a new name, a notification appears "Hiding Magisk Manager" and the notification disappears and nothing else happens! The same Magisk Manager with same name just exists.

This problem only happens on my Samsung Galaxy A5 2016. For example I have done this on my Samsung Galaxy Note 5 and it works just fine and a new Magisk Manager app gets installed.

From Magisk Manager, I clicked "Log" and cleared the Log and then redid the process (Hide Magisk Manager) and then I checked "Log" again and nothing was there.

Edit: I'm using the latest Magisk and Magisk Manger and I'm on Samsung Stock Rom (Nougat - no custom Rom).

Please help! Thanks in advance!

**Comment by Saya47** [comment]
I've been having this problem for two years, last time I tried, the Magisk Manager crashed, and I uninstalled it and reinstalled the APK. I think I know how to fix the problem, how do I clear cache for all Magisk stuff? I think this would fix the problem.

**Comment by Saya47** [comment]
I have uninstalled Magisk (flashed Zip) cleared Dalvik and Cache, reflashed Magisk, and installed Magisk Manager again and it still doesn't work.

**Comment by osm0sis** [comment]
#2975
