### ISSUE TITLE
No response or failure to Hide Magisk Manager

### ISSUE THREAD

**Issue by Criticise** [topjohnwu/Magisk#3062]
The logs caught are here, Don't know if it shows any   sighs

[https://drive.google.com/file/d/1-Qw8WsyWeCk7v8kQyX1u8XhoJA4Ifk2I/view?usp=drivesdk]() 
[https://drive.google.com/file/d/1-QBf_Z0Pc3_oFMnFfhTv9J3Y5GRZaKxq/view?usp=drivesdk]()

**Comment by vdbhb59** [comment]
Relates to [2975](https://github.com/topjohnwu/Magisk/issues/2975) and [2944](https://github.com/topjohnwu/Magisk/issues/2944)
