### ISSUE TITLE
Unable to flash Magisk on OnePlus Android 11 DP3

### ISSUE THREAD

**Issue by JeromeShaw** [topjohnwu/Magisk#3066]
On my OnePlus 8 (IN2010), which is updated to official Android 11 DP3, I still can't get Magisk status installed and I'm pretty sure that I'm using the Canary version (20419) to patch the boot.img and flash it.

**Comment by Rajathbharadwaj** [comment]
Try with OrangeFox recovery. Sometimes, it could be the recovery which might be causing  it.

**Comment by JeromeShaw** [comment]
> Try with OrangeFox recovery. Sometimes, it could be the recovery which might be causing it.

I can't find any recovery built for OOS11 DP3 on OnePlus 8, besides I've not used recovery to flash Magisk.

**Comment by osm0sis** [comment]
#2994
