### ISSUE TITLE
Apps crashing when Magisk is installed

### ISSUE THREAD

**Issue by sunsettrack4** [topjohnwu/Magisk#307]
Several apps crash because of an issue related to Magisk. The affected apps work fine when Magisk is not installed. 

Device: Samsung Galaxy Alpha
ROM: ResurrectionRemix OS v5.8.3
Magisk version: v13.3

Log file attached (example: Subway Surfers):
[magisk_app_crash.txt](https://github.com/topjohnwu/Magisk/files/1168245/magisk_app_crash.txt)

**Comment by Martin-Maat** [comment]
Same here. The odd thing is it continued to happen after I removed Magisk using the uninstaller (flashed it from TWRP) but the problems did start after I started first messing with Magisk, installing 13.1 and later 13.3. I have Resurrection Remix on a Samsung Note II.

Before I started messing with Magisk I had been using SuperSU and I removed that by flashing unSU from TWRP. Flashing a new RR rom plus GApps did not entirely fix it, I still cannot use GMail, it crashes seconds after it starts up, very consistently. Earlier I could not use SMS either but this was fixed after the reinstall of the ROM and GApps. The apps that did crash before then nicely re-asked for permissions while GMail never did.

**Comment by Martin-Maat** [comment]
I finally not only removed Magisk but re-installed SuperSU, first from the Play store. At startup it complained the phone was not rooted. Hmm.. that's odd.

I then downloaded the zip and installed SuperSU from TWRP. After reboot it no longer complained, it had managed to re-root the phone and everything worked like a charm again. No closing apps problems anymore whatsoever.

Perhaps unSU de-roots the device and Magisk never bothers to check for root. Or has its own root account, I don't know. All I know the phone was close to useless, and after getting rid of Magisk and re-installing SuperSU everything worked without issues again.
