### ISSUE TITLE
Manager 6c8fe465 updated to 07f721a1 doesn't work

### ISSUE THREAD

**Issue by ch3mn3y** [topjohnwu/Magisk#3079]
I'm using canary channel and latest Manager update doesn't work.
Tried "clean" install as well.

All I see is after MAGISK logo is my wallpaper.

Dunno if a log will help, I'm on phone and I don't see an option to add something else than pic.

**Comment by ch3mn3y** [comment]
[2020-08-13_13.30.zip](https://github.com/topjohnwu/Magisk/files/5068737/2020-08-13_13.30.zip)
Ok. Desktop mode was a way to upload log.

**Comment by osm0sis** [comment]
How about 293?

**Comment by ch3mn3y** [comment]
Now its fine 👍
