### ISSUE TITLE
VIPER4Android for Magisk cannot work

### ISSUE THREAD

**Issue by AnClark** [topjohnwu/Magisk#308]
After updating to the latest Magisk, VIPER4Android for Magisk (Topjohnwu's port provided in Magisk Manager's repo, v2.5.0.4) cannot work at all.

Issue: VIPER4Android's driver status shows "Abnormal", and all its functions are not available. But when I turn off SELinux in VIPER's manager, it returns to life.

Maybe it's a bug of Magisk's SELinux injection.

---
My device info:
[Model] Xiaomi Mi Max Prime
[ROM] Mokee Android 7.1.2  &  MIUI 8.2 with Android 7.0 (Problem occurs to both ROMs)
[Magisk Version] Magisk v13.3

**Comment by gaiaweylyn** [comment]
Can confirm this. Been trying many things to get it working. I have yet to do so. Keep getting the I/O error, and the Abnormal status.

**Comment by AnClark** [comment]
@gaiaweylyn But as I said above, Magisk has a package to install VIPER without bearing I/O error. It used to work well.

**Comment by Handy-E** [comment]
Same problem here. V4A not working with magisk 13.3 and LineageOS 14.1 (Android 7.1.2) on Sony z3c.
When I turn off SELinux everything works fine. But that's not a good solution for me.

**Comment by ShadySquirrel** [comment]
This worked for me since first 13.0 beta: https://forum.xda-developers.com/showpost.php?p=72707598&postcount=233

**Comment by AnClark** [comment]
@ShadySquirrel v13.0 doesn't have this problem. So have you ever updated to the latest Magisk?

**Comment by AnClark** [comment]
But there's no /magisk/.core/ directory on my device. Have you ever created one?

**Comment by ShadySquirrel** [comment]
If you have magisk folder on your root, core subfolder must be there :) It's a hidden dir (begins with dot as you can see) so it may not be displayed, so you may need to enable display of hidden files or try to input path directly if your file manager supports that. You can also use adb. I'm using FX and everything is there.

I'll probably fork original module @topjohnwu made and update it (template needs an update + this SELinux fix) someday soon, just to finish with some personal stuff first..

**Comment by AnClark** [comment]
Thanks a lot~~ No wonder I couldn't see that folder, as my file manager hid those folders by default. Now I can freely modify it.

**Comment by AnClark** [comment]
Everything works well now! Thank you, @ShadySquirrel ! 
Hope for your update~ :smiley:

**Comment by ShadySquirrel** [comment]
@AnClark I'm done, you can download module from [here](https://github.com/ShadySquirrel/ViPER4Android). Just select download as ZIP.

I've flashed it recovery and works properly on my device, Manager install should work, too. Beware , I've tested it only on my device (kiwi running LineageOS). If anything is wrong, open ticket there with logs and description.
