### ISSUE TITLE
Unable to unpack boot image' Issue

### ISSUE THREAD

**Issue by michaelsantosh** [topjohnwu/Magisk#3086]
Hey! Unable to get Magisk root, flashed from TWRP, please find the logs and boot.img 
Kernel log- [dmesg[1].log](https://github.com/topjohnwu/Magisk/files/5081176/dmesg.1.log)
TWRP log- [recovery[1].log](https://github.com/topjohnwu/Magisk/files/5081174/recovery.1.log)
Boot image inside this zip- [boot.zip](https://github.com/topjohnwu/Magisk/files/5081175/boot.zip)

**Comment by osm0sis** [comment]
That boot.img should patch fine in Magisk Manager, there's an odd permission denied in the recovery.log, but that just sounds like your recovery is somewhat broken and you should use the magisk_patched.img from Manager instead.

**Comment by michaelsantosh** [comment]
flashing the patched-boot.img gives bootloop @osm0sis
