### ISSUE TITLE
Is there a way to grant root privileges trough commands?

### ISSUE THREAD

**Issue by Andrew-afk** [topjohnwu/Magisk#3088]
Magisk root overlay is not showing with lastest official and canary, since june or march.
In Terminal emulator there is a magisk command, can i use it somehow to give root access to apps?
For example: magisk --grant com.app.name
Something like that?
Or maybe forcing to show an overlay?

**Comment by topjohnwu** [comment]
No, if this is possible then it will be a use security hazard. Please file a proper bug report about the root request dialog not showing.

**Comment by Andrew-afk** [comment]
> No, if this is possible then it will be a huge security hazard. Please file a proper bug report about the root request dialog not showing.

I did it but your mods closed it without solving it
