### ISSUE TITLE
Problems with safetynet on Xiaomi Devices

### ISSUE THREAD

**Issue by szamuka** [topjohnwu/Magisk#309]
I have problems with safetynet on Xiaomi Devices

I installed fix modul this:
[https://forum.xda-developers.com/apps/magisk/xiaomi-safetynet-fix-t3600431](url)

but safetynet false is all the time :(

![20292523_1354952871285218_1216377894_n](https://user-images.githubusercontent.com/21019458/28580912-1fcdb632-7161-11e7-9947-52fee90fa87b.png)

**Comment by FriskHD** [comment]
Same problem

**Comment by FriskHD** [comment]
Same with rn3

**Comment by DeicPro** [comment]
SafetyNet is not related with Magisk, you must not report this and also you did not give much information. Go to here to give you support with this problem: http://bit.ly/USNF-Testing

**Comment by szamuka** [comment]
@DeicPro 
I installed stable and later beta your fix, but I have this all the time :(

**Comment by DeicPro** [comment]
Install the v2 Beta 5 Test 6 and share the logs....
