### ISSUE TITLE
The sepolicy patch will cause bootloop for some Android 11 devices

### ISSUE THREAD

**Issue by simonsmh** [topjohnwu/Magisk#3093]
This bug should happen after #2994

While debugging around, I found that the sepolicy patch will cause bootloop, the device boots after commenting following parts.
I still didn't figure out where is the core of the problem and how to fix it.

Edit: I repacked the boot image to run under selinux permissive now, and checked that it is the sepolicy patch part issue.

Reference:
init patch part
https://github.com/topjohnwu/Magisk/blob/599ee57d39/native/jni/init/rootdir.cpp#L273-L276
sepolicy patch part
https://github.com/topjohnwu/Magisk/blob/599ee57d39/native/jni/init/rootdir.cpp#L284-L297

**Comment by canyie** [comment]
Sorry, wrong click :(
