### ISSUE TITLE
MagiskHide: Cannot monitor am_proc_start, abort... in Beta V10 161230

### ISSUE THREAD

**Issue by koko115** [topjohnwu/Magisk#31]
![screenshot_20170101-071001](https://cloud.githubusercontent.com/assets/24860056/21580403/ec19b1b6-cff2-11e6-8360-8b0a527b0054.png)
This is on Magisk Beta V10 from 30 December

![screenshot_20161231-210828](https://cloud.githubusercontent.com/assets/24860056/21580406/0d70a6c6-cff3-11e6-9299-4012502bd863.png)
And this is on Magisk Beta V10 from 29 December

Galaxy S7Edge with december firmware. Stock kernel enforcing

**Comment by topjohnwu** [comment]
Already mentioned in the Magisk main thread.
