### ISSUE TITLE
SU+RW not working post update to Manager 7.5.2.295(10)-d6062944

### ISSUE THREAD

**Issue by vdbhb59** [topjohnwu/Magisk#3107]
Problem: SU+Mount Writeable not working on today's release.
Working previously: Yes
Last working version: 7.5.2.293 / 7.5.2.294 && Canary 20.4.20420-6c8fe465
Failed Version: 7.5.2.295(10)-d6062944
Magisk: Canary 20.4.20420-6c8fe465
Device API Level: 29
Device: Samsung M305F
Android: 10
App: X-Plore/Amaze/Material File Manager/Root Xplorers
Logs: Attached
Snaps: Yes, where I try to overwrite /system/etc/gps_debug.conf
Expected: Should overwrite/get replaced successfully
Actual: Toast shows result as successful (OK), but actually does not get overwritten (see the file size) - original in /system/etc is 1.5kb, and the one to replace is 8kb, but after operation toast shows OK, the file is not replaced

![X-Plore - Overwrite + O Size](https://user-images.githubusercontent.com/60728004/91071655-fe225f80-e627-11ea-9187-656736376539.png)
![X-Plore - Result](https://user-images.githubusercontent.com/60728004/91071658-febaf600-e627-11ea-8068-3cd735d9886d.png)
[magisk_log_20200824_214412.log](https://github.com/topjohnwu/Magisk/files/5119126/magisk_log_20200824_214412.log)

**Comment by topjohnwu** [comment]
Magisk Manager does not affect how root works on your device. Please check if there are other things that has changed
