### ISSUE TITLE
Magisk Manager canary build 7e133b0c "error parsing package"

### ISSUE THREAD

**Issue by jparnell8839** [topjohnwu/Magisk#3117]
Problem: Magisk Manager canary build 7e133b0c receives the error "There was a problem parsing the package".

Environment: Pixel 4xl, stock Android 11 beta 3 build RPB3.200720.005, Magisk build 6c8fe465, Magisk Manager build d6062944

Expected result: Magisk Manager application to update to build 7e133b0c

Actual result: error "There was a problem parsing the package"

**Comment by pbanj** [comment]
I'm getting the same thing on my 3a running Android 10 August update

**Comment by hahapewpew** [comment]
I had that too on mine, but uninstalling and installing the new one works.

**Comment by Displax** [comment]
Clearing MM cache solwes this issue.

**Comment by topjohnwu** [comment]
Yes, it was fixed in the latest version, upgrading from an old version requires clearing up the cache
