### ISSUE TITLE
Magisk Manager (current) can't be used on devices with D-PAD navigation

### ISSUE THREAD

**Issue by tsynik** [topjohnwu/Magisk#3118]
such as Android TV devices, set-top boxes, Fire TV (it have Magisk as default root option) etc

Partial fix for main elements in this PR - https://github.com/topjohnwu/Magisk/pull/3111

It still doesn't have focus on settings popup dialogs and buttons. Also Install Magisk from main screen can't be completed with D-PAD.

Buttons  (OK, Cancel) on settings dialogs were active probably before this commit: https://github.com/topjohnwu/Magisk/commit/7e133b0cf4522f2acadb722b653a975d8dfb6fb7

for example, this buttons can't be pressed with D-PAD now: https://imgur.com/Dbu8qTr

**Comment by Fox2Code** [comment]
You should take a look at this issue:  #2027 (Original issue about Android TV support)

And also [`BaseUIFragment.onKeyEvent()`](https://github.com/topjohnwu/Magisk/blob/114a3c037fe86ea1714c216900a32d9f436a5916/app/src/main/java/com/topjohnwu/magisk/arch/BaseUIFragment.kt#L53) could be useful to detect D-PAD actions programmatically if needed

**Comment by tsynik** [comment]
Yup, this PR https://github.com/topjohnwu/Magisk/pull/2175 made D-PAD support to Magisk Manager 7.5.1 - it compatible with D-PAD navigation. Only missed reboot button focus after module update there ;-) Now we talk about current Manager UI

**Comment by topjohnwu** [comment]
@tsynik let's keep track of this in the PR, finally someone with actual Android TV hardware and contribute!
