### ISSUE TITLE
No full clean after customize.sh

### ISSUE THREAD

**Issue by gjf** [topjohnwu/Magisk#3119]
It looks like module_installer.sh does not clean everything correctly when customize.sh with SKIPUNZIP=1 is used.

To reproduce it try the following:
1. Create a simple module with pure customize.sh file with only one string SKIPUNZIP=1. I have attached that one.
[test.zip](https://github.com/topjohnwu/Magisk/files/5152959/test.zip)
2. Install it.
3. Reboot.

In theory this addon simply does nothing and no new modules should appear in Magisk as well as no new folders should be created in /data/adb/modules/
But it is not true in practice - /data/adb/modules/ contains this new module.

1. Installation log file: 
[magisk_install_log_2020-09-01T01_40_54Z.log](https://github.com/topjohnwu/Magisk/files/5152968/magisk_install_log_2020-09-01T01_40_54Z.log)
Pay attention on cp error.
2. New module folder in /data/adb/modules/ (archived, in fact - contains empty update file only): 
[testtesttest.zip](https://github.com/topjohnwu/Magisk/files/5152972/testtesttest.zip)
3. New empty item in /data/adb/modules_update (archived, in fact - empty): 
[modules_update.zip](https://github.com/topjohnwu/Magisk/files/5152975/modules_update.zip)

Looks like some mechanism that should completely wipe off the module folder works incorrectly.

**Comment by xerta555** [comment]
If I see things strictly in relation to the method of execution used: yes, I agree.

If I try to widen the answer and the angle of vision a bit: is installing a module on a system-as-root device, like yours with a slot "_b", compared to an Android device all that could be more standard.

I'm saying this in relation to the different partition mounting processes implemented on Magisk (https://github.com/topjohnwu/Magisk/blob/master/scripts/module_installer.sh#L113-L158), which could be questioned, and I say maybe.

Another hypothesis: it could be that this case is simply not yet supported in relation to the basic logic which is to install a module (simple or complex whatever), and not just a basic module installing nothing as a test.

**Comment by gjf** [comment]
Yes, I must agree: installing module without installing module itself is quite an unusual way of using.
But anyway - this is documented feature (https://topjohnwu.github.io/Magisk/guides.html): 

> If you need even more customization and prefer to do everything on your own, declare SKIPUNZIP=1 in customize.sh to skip the extraction and applying default permissions/secontext steps. Be aware that by doing so, your customize.sh will then be responsible to install everything by itself.

> Avoid using 'exit' as it will skip the termination cleanup steps

But in fact this "termination cleanup steps" are not complete.

In fact to make cleanup process complete I have to put the following line into customize.sh file:
`unzip -o "$ZIPFILE" remove -d $MODPATH >&2`

Sure empty "remove" file have to be included in module zip.

Anyway I have to report about this issue. Obviously normal documented way od using customize.sh should not result in cp error in logs and empty module in list.

So I hope it will be fixed.

**Comment by gjf** [comment]
> Another hypothesis: it could be that this case is simply not yet supported in relation to the basic logic which is to install a module (simple or complex whatever), and not just a basic module installing nothing as a test.
Please check this: https://github.com/gjf/CliptoPro
This module works and uses all documented features, but to remove traces it should implement the above mentioned "hack".
I think it is not correct by design, because this problem can be easily removed in module_installer.sh code.

**Comment by unixandria-xda** [comment]
I think that's part of using SKIPUNZIP, magisk handles no more logic for your module after initial environment setup, you are expected to implement that yourself.

Either don't use SKIPUNZIP, use MMT-ex, or implement the logic yourself. This is intended behavior.

**Comment by gjf** [comment]
Once again: read the documentation regarding "termination cleanup steps".
Either all logic should be performed by module - or "termination cleanup" is general.
Also what about cp errors in log? Should I handle it in my module also?
Why we are trying to cover rather than admit? :)

**Comment by topjohnwu** [comment]
@osm0sis if you have time, may you look into this? Many thx

**Comment by osm0sis** [comment]
The PSU died on my PC so I'm not going to be able to dig too deeply into things for a bit. 😞

**Comment by osm0sis** [comment]
I can at least start to look into this while waiting for my PSU to arrive in the mail later this month. 😛

**Comment by osm0sis** [comment]
Okay, so the problem arose when John simplified the module format so that it's literally just a zip of the module files and so just started unzipping things directly into /data/adb/modules to save time; he then added "Remove stuffs that don't belong to modules" to clean that up afterwards.

I think adding a simple `rmdir -p $MODPATH` will resolve this for all basic modules, and anything more complex or e.g. hijacks the install from customize.sh (like all of my modules :wink:) should be including their own cleanup code.
