### ISSUE TITLE
Moto G5 Plus: mount /dev/block/loop0->/magisk failed with 13: Permission denied

### ISSUE THREAD

**Issue by brandonsisco** [topjohnwu/Magisk#312]
Tried flashing stock firmware along with many variations of recovery & Magisk with no luck please help

--------- beginning of main
--------- beginning of system
I(  456:  498) ** post-fs-data mode running
I(  456:  498) * Mounting /data/magisk.img
E(  456:  498) mount /dev/block/loop0->/magisk failed with 13: Permission denied
I(  456:  771) ** late_start service mode running
I(  456:  771) * Running service.d scripts
I(  456:  771) * Running module service scripts
I(  456: 7628) * Starting MagiskHide
I(  456: 7628) hide_utils: Hiding sensitive props
I(  456: 7628) hide_list add: [com.google.android.gms.unstable]
E(  456: 7628) fopen: /magisk/.core/hidelist failed with 2: No such file or directory
I(  456: 7628) proc_monitor: init ns=mnt:[4026531840]

**Comment by petrblaho** [comment]
I see the same on Moto Z Play with lineage-14.1-20170724-nightly-addison using Magisk 13.3.

**Comment by brandonsisco** [comment]
Any update or suggestion?

**Comment by Theitfixer85** [comment]
same on moto g5 with linage 14.1-20170630-unofficial-cedric

**Comment by ldrolez** [comment]
in #333 somebody wrote "Seems to be an f2fs issue, occurs on Z Play and other devices too". Any idea on how to fix this?

**Comment by jaybz** [comment]
I have a Moto Z and I am encountering this issue as well. I tried mounting /dev/block/loop0 via adb as root and it does actually mount.

**Comment by brandonsisco** [comment]
Any update or workaround friends?

**Comment by petrblaho** [comment]
I installed different kernel (https://forum.xda-developers.com/moto-z-play/development/kernel-valyrian-v1-0-t3656380) for my Moto Z Play with LineageOS and Magisk works for me - I use it only for NanoMod.
