### ISSUE TITLE
Magisk is not installed issue

### ISSUE THREAD

**Issue by karthick4kumaran** [topjohnwu/Magisk#3120]
My mobile was successfully rooted with the latest Magisk Manager. I installed couple of modules from MagiskManager download section. It asked for a reboot. I rebooted the mobile, but after the mobile reboot, Magisk is showing as not installed. I had to reboot the mobile several times to get the issue fixed yesterday. Today after another manual mobile reboot, Magisk manager is again showing as "Magisk is not installed"

<img width="382" alt="Screenshot 2020-09-01 at 1 06 44 PM" src="https://user-images.githubusercontent.com/65916491/91821199-101d8700-ec54-11ea-9836-2e7990e11058.png">

**Comment by techIndia-hacker** [comment]
Magisk in recovery or boot?

**Comment by karthick4kumaran** [comment]
Magisk is in boot. I patched Magisk with the firmware and installed it through jODIN3. I am facing this issue often. I also saw many others reporting the same issue in several discussion forums.

**Comment by techIndia-hacker** [comment]
Device and os?

**Comment by karthick4kumaran** [comment]
I am not sure about the technical details. I patched Magisk with AP_ file that comes along with the files that we need for boot. Then I formatted my phone with those files.

**Comment by techIndia-hacker** [comment]
What device u have?

**Comment by karthick4kumaran** [comment]
Samsung Galaxy m30s 
sm-m307f

**Comment by karthick4kumaran** [comment]
You can find the rooting method that I followed to root my mobile here -> https://forum.xda-developers.com/galaxy-m30s/how-to/guide-samsung-galaxy-m30s-sm-m307f-video-t4008641

**Comment by techIndia-hacker** [comment]
The guide is wrong

**Comment by techIndia-hacker** [comment]
Untick auto reboot
Go to recovery and boot from there

**Comment by karthick4kumaran** [comment]
You mean in JODIN3 we should not check auto-reboot?

**Comment by karthick4kumaran** [comment]
Also just make to make everything clear...Magisk is not always saying it's Not Installed. Sometimes when I reboot the mobile it shows Not Installed. So I have to reboot the mobile n number of times till Magisk shows that as Installed. Don't you think it's an issue from Magisk side?

**Comment by techIndia-hacker** [comment]
Auto reboot should be un ticked. Reboot to recovery directly manually. U r
unable to follow instructions. It's not a magisk problem

**Comment by karthick4kumaran** [comment]
Then why does it show as Installed sometimes? If it's a problem with the rooting, then shouldn't it show as Not Installed always?

**Comment by techIndia-hacker** [comment]
No it happens cause sometimes the recovery partition gets triggered
