### ISSUE TITLE
[SUGGESTION] Possible to add swype effect ?

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#3121]
Hi

Would it be possible to add the possibility to gestures from left to right to move from one screen to another in the Magisk manager?

The idea would be to be able to move a finger from the right to the left of the screen to switch from the home screen to the "Superuser" screen, and vice versa.

I ask the question because it annoys me to have to use these little buttons when the application is visually modern.

I think that @diareuse primary could check if it could be feasible.

Thanks in advance.

**Comment by osm0sis** [comment]
I feel like @diareuse was against swipe effects when proposed previously. I'll leave it up to him to close this or not.

**Comment by diareuse** [comment]
It would complicate things quite a lot. On top of that it would worsen the experience for some users while swiping. _Let me elaborate_

---

The screens are optimized most importantly so the scroll is remembered whenever configuration changes or you return to the screen from another one. It's extremely vital that this behavior remains unchanged.

Memory usage is another concern as having multiple screens loaded at the same (as the pager requires) presents an unfortunate overhead and in some cases would indirectly cause some Out Of Memory issues.

Bottombar and Toolbar are not static at this point and move to maximize the content visible on screen at any given time. This would need to be removed or patiently calibrated on every single screen.

It would be really nice to have additional options, but having too many options sometimes degrades the overall experience. In this case all those aforementioned issues would come down like an avalanche and combine to a very confusing app. The pager pattern was not originally created to support these complex structures and remains only as a way of displaying simple data.

I guess nobody holds their phone upside down and so clicking that simple icon is even easier than performing a swipe. Although I (we) might not implement this suggestion at this time, I'd like to thank you for sharing this idea. :v:

**Comment by xerta555** [comment]
> The screens are optimized most importantly so the scroll is remembered whenever configuration changes or you return to the screen from another one. It's extremely vital that this behavior remains unchanged.

> Memory usage is another concern as having multiple screens loaded at the same (as the pager requires) presents an unfortunate overhead and in some cases would indirectly cause some Out Of Memory issues.

> Bottombar and Toolbar are not static at this point and move to maximize the content visible on screen at any given time. This would need to be removed or patiently calibrated on every single screen.

> It would be really nice to have additional options, but having too many options sometimes degrades the overall experience. In this case all those aforementioned issues would come down like an avalanche and combine to a very confusing app. The pager pattern was not originally created to support these complex structures and remains only as a way of displaying simple data.

Honestly I didn't understand much of the explanations given.
And the little that I did understand had nothing to do with the possibility of dragging a finger on the screen to change of categories in the app.

Maybe you could explain all this in another way?

**Comment by diareuse** [comment]
The app is optimized to look and behave this way. Having a dragging feature is not that complicated nevertheless when I'd add that the app will go brrrr on lower-end devices.

**Comment by xerta555** [comment]
> The app is optimized to look and behave this way. Having a dragging feature is not that complicated nevertheless when I'd add that the app will go brrrr on lower-end devices.

Why Magisk Manager will go <<brrr>> on lower-end devices ?
It's just a visual feature effect..

**Comment by osm0sis** [comment]
He explained already it's not just a visual effect, these all have a cost to CPU, GPU and RAM, and with swipe it's too significant.

**Comment by xerta555** [comment]
@diareuse So in the distant future it would not be impossible that this feature could added ?

**Comment by diareuse** [comment]
I'm not a fortune teller nor can I predict the future. It's not possible in present time, I can tell you that much.
