### ISSUE TITLE
Magisk manager patches boot.img of Redmi 9a incorrectly

### ISSUE THREAD

**Issue by ciunchikan** [topjohnwu/Magisk#3123]
Dear team,

I found the following issue

Phone: Xiaomi Redmi 9A
Firmware: dandelion_global_images_V12.0.3.0.QCDMIXM_20200714.0000.00_10.0_global_c021b1dc87

After patching boot.img its size was reduced from 64mb to 10.5mb. Booting from this file causes the device reboot.
Original boot.img is attached. 

 I really appreciate it if you manage to fix this issue. Feel free to contact me to test any changes.

[boot.zip](https://github.com/topjohnwu/Magisk/files/5158485/boot.zip)

Best regards,
Aliaksandr Tsiunchyk

**Comment by techIndia-hacker** [comment]
A/B partition or A only?
Flash magisk from twrp and retry

**Comment by ciunchikan** [comment]
> A/B partition or A only?
Sorry, I'am not the expert and don't really understand what you mean. But let me describe what I've done:
1) Installed Magisk manager from apk  ( version 7.5.1 )
2) Placed the boot.img into the internal storage
3) Connected phone with PC
4) Clicked "Install Magisk" and chose the option Select and Patch a File
5) In the next window I selected my boot.img and waited until the patch is done.  

> Flash magisk from twrp and retry
I cannot run twrp because it's not possible to install it on Redmi 9a yet

> Original boot.img isn't uploaded probably!!
I zipped it becuause the github does not allow to upload IMG files and it has restriction of the file size.
Here is the origianl file
https://drive.google.com/file/d/1Am5L-UFo8SoseBycWCFgNTJC4YSGjtW4/view?usp=sharing

**Comment by techIndia-hacker** [comment]
Before patching tick the verity and encryption options and retry

**Comment by ciunchikan** [comment]
I tried with and without the options "Preserve force encryption" and "Preserve AVB 2.0/dm-verity". In all cases the resulting boot.img is 10.5 MB

**Comment by techIndia-hacker** [comment]
Install Canary magisk manager and send a screenshot opening up all the
inverter"^" icons

**Comment by ciunchikan** [comment]
![image](https://user-images.githubusercontent.com/70604240/91986751-c7d69580-ed35-11ea-9820-4549dff743bc.png)
Do you mean this screenshot?

**Comment by techIndia-hacker** [comment]
See u don't have A/B. Then probably u have magisk in recovery

**Comment by ciunchikan** [comment]
No, I would be grateful if you provide it.

**Comment by techIndia-hacker** [comment]
So u r the first one trying to root redmi 9A👍

**Comment by techIndia-hacker** [comment]
Well well well, according to @topjohnwu  I am right. U need to flash it in recovery partition. Pull the recovery.img and patch it the same way u r doing it for boot.img. Flash it afterwards. 
Adb reboot recovery
U have root now

**Comment by techIndia-hacker** [comment]
![15990529378642670445567896852998](https://user-images.githubusercontent.com/58086339/91988900-7c2fe600-ed4d-11ea-89aa-7aebbb902cf1.jpg)

**Comment by ciunchikan** [comment]
Ok, thanks, will try it soon

**Comment by techIndia-hacker** [comment]
If ur successful post ur method and guide others in xda forum. Let me know

**Comment by ciunchikan** [comment]
Well, unfortunately it did't work out. 
I pathed recovery.img The size was reduced from 60mb to 20mb ( it's bigger than one for boot.img but still small )
then I flashed recovery partition by 
"fastboot flash recovery recovery.img"
and rebooted device. It fell into the constant rebooting. So I had to flash the original recovery.img back.
 Here is my recovery.img
https://drive.google.com/file/d/1_20_xn1RJTn5qBVxBjg4CuVmiKzCNOhG/view?usp=sharing

**Comment by techIndia-hacker** [comment]
Send the link of ur complete firmware and country name

**Comment by ciunchikan** [comment]
https://bigota.d.miui.com/V12.0.3.0.QCDMIXM/miui_DANDELIONGlobal_V12.0.3.0.QCDMIXM_816d42afde_10.0.zip

**Comment by Didgeridoohan** [comment]
Check the Manager screenshot again. It says "Ramdisk: Yes", so the ramdisk is in the boot image rather than the recovery. The issue could be that the device expects the full boot partition to be written, so the 10mb file is to small. Padding the file with zeros up to the expected size might do the trick.

**Comment by techIndia-hacker** [comment]
Nowadays devices have dynamic position so it should be resizing when flashed from fastboot

**Comment by ciunchikan** [comment]
Yes, I unlocked the bootloader with MI official tool

**Comment by techIndia-hacker** [comment]
U better try this command in fastboot

fastboot OEM unlock
Fastboot flashing unlock_critical

**Comment by ciunchikan** [comment]
Failed with the first command
![image](https://user-images.githubusercontent.com/70604240/92002608-b34fc880-ed48-11ea-9638-3eef50ece8c4.png)

**Comment by techIndia-hacker** [comment]
Try the next one

**Comment by ciunchikan** [comment]
![image](https://user-images.githubusercontent.com/70604240/92003570-dfb81480-ed49-11ea-8398-440e62388909.png)

**Comment by techIndia-hacker** [comment]
U don't have unlocked bootloader. That's why all this 😑

**Comment by ciunchikan** [comment]
Maybe this is because of the MTK processor
I used fastboot  getvar all and the result is 
![image](https://user-images.githubusercontent.com/70604240/92005264-f2cbe400-ed4b-11ea-8aec-e7a8bb5098b3.png)
 the full result attached
[fastboot_getvar_all.txt](https://github.com/topjohnwu/Magisk/files/5163318/fastboot_getvar_all.txt)

**Comment by techIndia-hacker** [comment]
Sorry bro I don't have any miui devices just because I knew about these issues, can't help u if bootloader rejects modified partitions.

**Comment by ciunchikan** [comment]
Anyway thanks for your effort. Maybe someone will patch recovery with TWRP

**Comment by techIndia-hacker** [comment]
Yeah twrp is needed

**Comment by osm0sis** [comment]
> Install Canary magisk manager and send a screenshot opening up all the inverted"^" icons

The size of the image is usually unimportant. Most of your boot.img is empty space.

**Comment by techIndia-hacker** [comment]
Well his bootloader is not accepting modified partitions

**Comment by osm0sis** [comment]
> Well his bootloader is not accepting modified partitions

Mi Unlock Tool does a weird half-unlock, where fastboot still won't allow commands but does accept flashing images, so honestly it could go either way on that one.

**Comment by ciunchikan** [comment]
> Anyway we'll wait to hear if Canary 20420 has any better effect, since it has rewritten init logic.

Unfortunately not. The resulting boot.img is the same

**Comment by osm0sis** [comment]
The size of the image doesn't matter, you need to test whether it boots. Try with 20424.

**Comment by techIndia-hacker** [comment]
Yeah run this fastboot boot boot.img after renaming magisk_patched.img

**Comment by zgfg** [comment]
I never had problems patching boot.img on Xiaomi Mi 9T, ranging from MIUI 10/A9 till now MIUI 12/A9

Similarly it works on some other models, so:

- You must patch BOOT.IMG, not ramdisk.img
It must be extracted exactly from the same Recovery/zip firmware you are running (you said yours is V12.0.3.0.QCDMIXM).
Once patched, it must be flashed by Fastboot or from TWRP to Boot, not to Ramdisk

- For me, patched boot img is 15,75 MB (stock is 64 MB), it DOESN'T MATTER

- Preserve Encryption and Preserve Verity MUST BE ON.
Recovery mode (third option) MUST BE OFF (by default is On, you must turn it Off)

- If you use the latest Canary (I always do), then Preserve Encryption and Preserve Verity options are no more available ('hardcoded' to On) but still you MUST TURN OFF Recovery option

This is all assuming that your firmware is still on Android 10, not yet 11 - for A11 there is another issue opened (scroll through Issues here on GitHib) claiming that Magisk  does not work for Xiaomi

**Comment by ciunchikan** [comment]
I tried with the latest Canary, flashed boot and got the Bootloop. I cannot modify /data/adb/modules  because I don't have twrp,  and I can't access the folder data without having root

**Comment by zgfg** [comment]
You can try to remove all Magisk modules by ADB, while booting:

- Have your Magisk patched boot.img flashed
- Power off the phone
- Connect PC by USB to the phone and open the ADB console on the PC
- Start booting the phone and execute from the PC:
> adb wait-for-device shell magisk --remove-modules

But it never worked on my Xiaomi

**Comment by zgfg** [comment]
However, there is onether trick you can do (just tested on my Mi 9T, MIUI 12, Android 10, Magisk Canary)

1) Have the Magisk patched boot.img flashed

2) Reboot to ANDROID SAFE MODE
- Start booting, wait for the mi logo and then press and keep pressed VOLUME MINUS
- When it boots (and waits for you to enter the pin), you will see on the bottom-left: Safe mode

3) Reboot to normal mode
- It should reboot with Magisk running but all modules disabled, see below
- Disable Airplane mode (it was enabled on my phone after rebooting from the Safe mode)
- Home screen will look like in Safe mode (I lost all icons for my installed apps), but don't worry,  found all my apps in App Drawer (if you didn't enable App Drawer, you would probably have all icons on the Home screens)

4) Open Magisk Manager
- Go to Settings and enable Magisk Hide (it was disabled after rebooting from Safe Mode)
- Check SafetyNet, it will ask you to download the code (it was lost after Safe Mode)
- TG, settings for apps that were granted root or enabled Hide Magisk from them was not lost

5) Open Modules tab in Magisk Manager
- All modules should be disabled
- Remove or keep disabled those causing the bootloop, enable the others

6) Reboot and organize again icons on the Home screen (most daunting part for me)

**Comment by ahsanjamshaid** [comment]
@ciunchikan any success bro? I also got this phone and need to root.

Have you tried to vbmeta disable method? Any success with that?

**Comment by icew4y** [comment]
> @ciunchikan any success bro? I also got this phone and need to root.
> 
> Have you tried to vbmeta disable method? Any success with that?

I know Rdmi 9 can be root by vbmeta disable. I've been looking for redmi9A...

**Comment by 735394006** [comment]
So it still hasn't been solved？

**Comment by ahsanjamshaid** [comment]
@735394006 No

**Comment by vartanjean1973** [comment]
Recovery done but issue with screen, now you can boot on recovery twrp and work with adb shell

**Comment by ahsanjamshaid** [comment]
> Recovery done but issue with screen, now you can boot on recovery twrp and work with adb shell

Please share file

**Comment by ahsanjamshaid** [comment]
I downloaded the file you shared on XDA, tried to boot into recovery without flashing and it does not boot into recovery, instead normal restart.

**Comment by ahsanjamshaid** [comment]
@topjohnwu can you please help? If this is already answered please mention the relevant link. I've tried all methods to patch boot.img with magisk, canary and beta an none works.

I only boot the patched image instead of flashing (because once in bootloop i might not get out without flashing full stock, happened earlier and dnt want again). Is this ok?

**Comment by ahsanjamshaid** [comment]
I flashed the magisk patched image using vbmeta image provided by @vartanjean1973. Boot loop issue is no more, but when i check magisk status it is not installed. What could be issue now?

Also the twrp recovery provided by him works, but some system mount issue is there. Tried to install magisk zip via this recovery and its error.

**Comment by Skythrew** [comment]
I have a Redmi 9A too and i'm trying to root it but when I flashed Magisk through OrangeFox Recovery (based on TWRP), I fell in a critical bootloop without fastboot access. So I flashed MIUI stock rom with the BROM mode and I saved my device but I can't understand why Magisk did that. @ahsanjamshaid Have you solved the problem ?

**Comment by ahsanjamshaid** [comment]
I got ot rooted long time ago, check this https://forum.xda-developers.com/t/redmi-9a-meyou-rom-rooted.4197311/

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Arhiv1t0r** [comment]
Hello, I need help with 12.0.22.0.QCDMIXM
I tried to root many times, but it only worked on 12.5.6.0.RCDMIXM but then the connection breaks.
Please help!
