### ISSUE TITLE
Write to /system/product not working

### ISSUE THREAD

**Issue by techIndia-hacker** [topjohnwu/Magisk#3124]
Device:- Oneplus 8
Android:- Oxygen OS Android 10
Magisk version:- 20.4 stable
Partition system:- A/B
Magisk installed in boot partition
Issue:- 
1) Installed debloater module. It failed to remove apps in product/priv-app folder, though it removes bloatware from system/priv-apps successfully.
2) I wrote a module to write audio files to system/product/ media/...  It failed to write to product partition. Symlinks for product partition were successfully created in data/adb/modules/my_module and media files were copied there but could not be placed in system/product.

**Comment by Displax** [comment]
https://github.com/topjohnwu/Magisk/issues/2359

**Comment by techIndia-hacker** [comment]
Thanks @Displax for pointing me out so quickly. The overlay module was the much needed fix. Though not sure why magisk is not able to mount product and vendor partitions natively

**Comment by unixandria-xda** [comment]
Please close this issue as it's resolved
