### ISSUE TITLE
[Help Request] Magisk Manager grays out flashable zips

### ISSUE THREAD

**Issue by UltraBlackLinux** [topjohnwu/Magisk#3125]
Problem
-----

So I tried multiple times now, either with nanodroid patcher that recently aquired magisk support with version 22.7: 
https://gitlab.com/Nanolx/NanoDroid
[NanoDroid-patcher-22.8.20200901.zip](https://github.com/topjohnwu/Magisk/files/5158912/NanoDroid-patcher-22.8.20200901.zip)

And with audiohq that was a magisk module all the time:
https://alcatraz323.github.io/audiohq/index_en.html
[audiohq_combined_091_2020_3_17.zip](https://github.com/topjohnwu/Magisk/files/5158910/audiohq_combined_091_2020_3_17.zip)

Device
-----

android 10 via Lineage OS
Magisk 20.4
Magisk M 7.5.1

**Comment by Didgeridoohan** [comment]
That likely comes from your default file explorer not correctly labeling those files as zips (even though they have the correct extension). Try a different explorer, and you can also try moving the files to a different location before opening in the Manager (that's worked for others).

**Comment by UltraBlackLinux** [comment]
thanks
