### ISSUE TITLE
20421 results in Bootloops/Qualcomm CrashDump Mode

### ISSUE THREAD

**Issue by unixandria-xda** [topjohnwu/Magisk#3128]
I can run 20420 fine, no problem.

20421 results in always rebooting to Qualcomm CrashDump Mode when trying to boot system, every time. Reverting to 20420 resolved this.

OnePlus 7 pro, OxygenOS Open Beta 17 (Android 10).

No logcat, pstore, anything because it never gets far enough in the boot process.

**Comment by palmbeach05** [comment]
I have a similar experience with my g7 power, it bootloops, and i am unable to pull any logs. Revert back to 20420 and everything is fine

**Comment by xerta555** [comment]
> Same issue for me too, where can i found the 20420 zip installer ?

**Comment by palmbeach05** [comment]
> > Same issue for me too, where can i found the 20420 zip installer ?

https://github.com/topjohnwu/magisk_files/blob/51e925d88c07d9fab2017d57c723e28c18a0d996/magisk-debug.zip

**Comment by xerta555** [comment]
> topjohnwu/magisk_files@`51e925d`/magisk-debug.zip

Effectivly it works for me too, so back on 20420.
So just wait that John fix it.

**Comment by j-whiteley** [comment]
\

> I can run 20420 fine, no problem.
> 
> 20421 results in always rebooting to Qualcomm CrashDump Mode when trying to boot system, every time. Reverting to 20420 resolved this.
> 
> OnePlus 7 pro, OxygenOS Open Beta 17 (Android 10).
> 
> No logcat, pstore, anything because it never gets far enough in the boot process.

Same here, OnePlus 6 (crDroid 6.9 for enchilada over OOS 10.3.5)

**Comment by palmbeach05** [comment]
> Same problem on my Note 10+, Android 10. It just bootloops until it starts without root.
> 
> Is there a way how i can flash 20420 again without twrp ? with the stock recovery i get a signature verification failed error.

Stock recovery = useless for what you want to do

**Comment by xerta555** [comment]
> Is there a way how i can flash 20420 again without twrp ? with the stock recovery i get a signature verification failed error.

Stock recovery is useless for this type of action.
Install again twrp and flash the zip directly.

**Comment by KaMyKaSii** [comment]
My Zenfone 4 is stuck on the ASUS logo, I don't know if it's the same problem. The device does not generate /proc/last_kmsg or /sys/fs/pstore/console-ramoops, I will attach the backup of the asdf partition which may have some relevant log
[asdf.ext4.win.tar.gz](https://github.com/topjohnwu/Magisk/files/5169762/asdf.ext4.win.tar.gz)

**Comment by Nemisor** [comment]
On Pixel 2XL with DP3, easiest recovery is to simply re-flash it using the android flash tool.

**Comment by KaMyKaSii** [comment]
> Same problem on my Note 10+, Android 10. It just bootloops until it starts without root.
> 
> Is there a way how i can flash 20420 again without twrp ? with the stock recovery i get a signature verification failed error.

1. Go to fastboot, flash stock boot.img/ramdisk.img and reboot to Android
2. Open Magisk Manager settings and set the below custom channel, it's just a edit pointing to 20420 files https://filebin.net/kqnvfqmpe955x366/debug.json?t=dcwdrfj2
3. Patch your stock boot.img/ramdisk.img and flash it using fastboot again

**Comment by DeltaOn3X** [comment]
> > Same problem on my Note 10+, Android 10. It just bootloops until it starts without root.
> > Is there a way how i can flash 20420 again without twrp ? with the stock recovery i get a signature verification failed error.
> 
> 1. Go to fastboot, flash stock boot.img/ramdisk.img and reboot to Android
> 2. Open Magisk Manager settings and set the below custom channel, it's just a edit pointing to 20420 files https://filebin.net/kqnvfqmpe955x366/debug.json?t=dcwdrfj2
> 3. Patch your stock boot.img/ramdisk.img and flash it using fastboot again

Thank you, ill try this out

**Comment by People-11** [comment]
same, on my Pixel 2, backing into 20420

**Comment by blackbox87** [comment]
After updating to f32a2991 (20421) my Pocophone F1 running LineageOS 16 kept booting to fastboot. I fixed it by booting to TWRP and reveting to 6c8fe465 (20420).

**Comment by blackbox87** [comment]
After updating to 20421 my Pocophone F1 running LineageOS 16 kept booting to fastboot. I fixed it by booting to TWRP and reveting to 20420.

**Comment by blackbox87** [comment]
After updating to 20421 my Pocophone F1 running LineageOS 16 kept booting to fastboot. I fixed it by booting to TWRP and reverting to 20420.

**Comment by KaMyKaSii** [comment]
> > > Same problem on my Note 10+, Android 10. It just bootloops until it starts without root.
> > > Is there a way how i can flash 20420 again without twrp ? with the stock recovery i get a signature verification failed error.
> > 
> > 
> > 
> > 1. Go to fastboot, flash stock boot.img/ramdisk.img and reboot to Android
> > 2. Open Magisk Manager settings and set the below custom channel, it's just a edit pointing to 20420 files https://filebin.net/kqnvfqmpe955x366/debug.json?t=dcwdrfj2
> > 3. Patch your stock boot.img/ramdisk.img and flash it using fastboot again
> 
> Thank you, ill try this out
> EDIT: Ok this is not an option as my device is not A/B :/

Mine isn't either. What's the problem? You just need to restore and then patch the same partition you did when you installed Magisk. By the way, I updated the custom channel link

**Comment by blackbox87** [comment]
After updating to 20421 my Pocophone F1 running LineageOS 16 it kept booting to fastboot. I fixed it by booting to TWRP and reverting to 20420.

**Comment by blackbox87** [comment]
After updating to 20421 my Pocophone F1 running LineageOS 16 kept booting to fastboot. I fixed it by booting to TWRP and reverting to 20420.

**Comment by DeltaOn3X** [comment]
> > > > Same problem on my Note 10+, Android 10. It just bootloops until it starts without root.
> > > > Is there a way how i can flash 20420 again without twrp ? with the stock recovery i get a signature verification failed error.
> > > 
> > > 
> > > 
> > > 1. Go to fastboot, flash stock boot.img/ramdisk.img and reboot to Android
> > > 2. Open Magisk Manager settings and set the below custom channel, it's just a edit pointing to 20420 files https://filebin.net/kqnvfqmpe955x366/debug.json?t=dcwdrfj2
> > > 3. Patch your stock boot.img/ramdisk.img and flash it using fastboot again
> > 
> > 
> > Thank you, ill try this out
> > EDIT: Ok this is not an option as my device is not A/B :/
> 
> Mine isn't either. What's the problem? You just need to restore and then patch the same partition you did when you installed Magisk. By the way, I updated the custom channel link

For System as root devices you cant restore on of the 3 patched partitions. Rooting my Note 10+ is not only patching the boot.img but the whole Firmware (AP one)

**Comment by mu198** [comment]
@DeltaOn3X, Have you tried to extract the boot from the AP and then repackage it as .tar

**Comment by DeltaOn3X** [comment]
> @DeltaOn3X, Have you tried to extract the boot from the AP and then repackage it as .tar

I made a backup 
Extracted boot, recovery and vbmeta, packed it in a tar file. 
Patched the tar file with magisk 20420 (thank you for the custom link!) 
Rebooted to download mode and flashed the patched tar with Odin (obviously ap tab) 
Now its workin again. 
Sideloading the patched imgs seperatly with abd gives me the same error again with "verification failed"

**Comment by mu198** [comment]
> > @DeltaOn3X, Have you tried to extract the boot from the AP and then repackage it as .tar
> 
> I made a backup
> Extracted boot, recovery and vbmeta, packed it in a tar file.
> Patched the tar file with magisk 20420 (thank you for the custom link!)
> Rebooted to download mode and flashed the patched tar with Odin (obviously ap tab) (auto-reboot on)
> Now its workin again.
> Sideloading the patched imgs seperatly with abd gives me the same error again with "verification failed"

What do you flash about adb sideload ???
And why?

**Comment by DeltaOn3X** [comment]
> > > @DeltaOn3X, Have you tried to extract the boot from the AP and then repackage it as .tar
> > 
> > 
> > I made a backup
> > Extracted boot, recovery and vbmeta, packed it in a tar file.
> > Patched the tar file with magisk 20420 (thank you for the custom link!)
> > Rebooted to download mode and flashed the patched tar with Odin (obviously ap tab) (auto-reboot on)
> > Now its workin again.
> > Sideloading the patched imgs seperatly with abd gives me the same error again with "verification failed"
> 
> What do you flash about adb sideload ???
> And why?

Look at @katmykasii reply

**Comment by mu198** [comment]
Yes, there is nothing about the adb sideload, as the Odin mode replaces the fastboot mode at Samsung

**Comment by jx-it** [comment]
For me neither magisk uninstaller.zip nor flashing 20420 worked. I'm still stuck in bootloop on Mi 9 SE. Any ideas?

**Comment by unixandria-xda** [comment]
> For me neither magisk uninstaller.zip nor flashing 20420 worked. I'm still stuck in bootloop on Mi 9 SE. Any ideas?

Weird, flashing 20420 immediately solved for me. Maybe dirty flash your ROM?

**Comment by jx-it** [comment]
> Weird, flashing 20420 immediately solved for me. Maybe dirty flash your ROM?

I also tried this, but it's still stuck.

**Comment by zgfg** [comment]
Same on Xiaomi Mi 9T, MIUI 12, Android 10

Tried patching boot.img with Magisk 20421 from Manager 296 and 297, same bootloop. 
[patching-Magisk-20421.log](https://github.com/topjohnwu/Magisk/files/5171183/patching-Magisk-20421.log)
[bootloop-patched-Magisk-20421.log](https://github.com/topjohnwu/Magisk/files/5171187/bootloop-patched-Magisk-20421.log)
[magisk_patched-20421.zip](https://github.com/topjohnwu/Magisk/files/5171191/magisk_patched-20421.zip)

**Comment by Lukasyus** [comment]
How can I revert back to the previous Magisk version or do anything for that matter if I can't even get my Oneplus 7 pro past the "The Bootloader is unlocked..." disclaimer screen? Please help...

**Comment by nabakolu** [comment]
Also had bootloop on Xperia XA2.
Using the Magisk installer zip i luckily still had on my sd card worked
to resolve the problem.
(even for a second time to check if it really was a Magisk problem)

**Comment by EvoXCX** [comment]
Same Oneplus 6 LineageOS 17.1

**Comment by topjohnwu** [comment]
61599059d5dd76d3994a33edaf8e2e77c5455bac

**Comment by unixandria-xda** [comment]
> [6159905](https://github.com/topjohnwu/Magisk/commit/61599059d5dd76d3994a33edaf8e2e77c5455bac)

All this trouble over a simple mixup lol

#beenthere
