### ISSUE TITLE
20421 Bootloops on Taimen (Pixel 2 XL)

### ISSUE THREAD

**Issue by ekeppel** [topjohnwu/Magisk#3129]
I've been running 20420 without issue.  This morning Magisk notified me of an update available to 20421, so I installed it.  It put the phone in a bootloop, and I had to run the Magisk Uninstaller in TWRP to recover from it.  Maybe it was a fluke on my phone, but I wanted to report this in case others run into the same problem.

**Comment by nekrommancer** [comment]
+ 1 for # 3129. I had to sideload uninstaller on TWRP.

**Comment by DRayX** [comment]
I had the same issue and just flashed Magisk 20.4 over it from the release to get back to booting.

**Comment by People-11** [comment]
20421 bootloop on my Pixel 2 too

**Comment by KaMyKaSii** [comment]
> I had the same issue and just flashed Magisk 20.4 over it from the release to get back to booting.
> 
> Edit: Tried to pin to 20420 by setting the custom channel URL to `https://github.com/topjohnwu/magisk_files/raw/51e925d88c/debug.json`, but realized that wouldn't actually work since the json file uses absolute references, so it would still load from the tip of canary. Might be nice if those were relative paths (e.g. `../magisk-debug.zip`) instead.

You can just use the custom channel link that I posted in the other issue:
https://github.com/KaMyKaSii/Unlock-SSH-on-Xiaomi-and-Redmi-WiFi-6-routers/raw/master/debug.json

**Comment by unixandria-xda** [comment]
#3128 , duplicate issue

**Comment by palmbeach05** [comment]
> I've been running 20420 without issue. This morning Magisk notified me of an update available to 20421, so I installed it. It put the phone in a bootloop, and I had to run the Magisk Uninstaller in TWRP to recover from it. Maybe it was a fluke on my phone, but I wanted to report this in case others run into the same problem.

Basically you have a qualcomm device like everyone else in the issue reported a few hrs before you reported in this thread

**Comment by ekeppel** [comment]
> > I've been running 20420 without issue. This morning Magisk notified me of an update available to 20421, so I installed it. It put the phone in a bootloop, and I had to run the Magisk Uninstaller in TWRP to recover from it. Maybe it was a fluke on my phone, but I wanted to report this in case others run into the same problem.
> 
> Basically you have a qualcomm device like everyone else in the issue reported a few hrs before you reported in this thread

Ah, ok.  I didn't realize it was related to the previously reported issue.    Thanks! :-)
