### ISSUE TITLE
MagiskSU doesn't preserve environment variables properly with the -m flag

### ISSUE THREAD

**Issue by sudoBash418** [topjohnwu/Magisk#313]
I ran these commands over adb to test:
`export TEST='test variable'; echo $TEST; /sbin/su -mc 'echo $TEST'`

It returns this:
`test var`
`<an empty line>`

I tried equivelent tests using different terminal emulators, over ssh, as well as using `--preserve-environment`, all resulting in the same problem.

Tested with Magisk versions: 13.3, 13.5, 13.6

Beta versions from [here](https://-developers.com/apps/magisk/beta-magisk-v13-0-0980cb6-t3618589).

UPDATE: Maybe OT, but I tried using LineageOS's addon su, and the same issue occurred.
It appears that phh's SU, MagiskSU, CyanogenMod's SU (which addon su is based off of) are all based off of https://github.com/koush/Superuser
Is this issue possibly affecting all https://github.com/koush/Superuser forks?
Or does this mean it's a problem on my end?

**Comment by tabepic** [comment]
As of now, I'm simply using a wrapper to dump the environment to a temp file, then su into another wrapper which loads the previous environment.

Very, very messy, if anyone wants it though, I'd be happy to publish it until this gets a proper fix.

**Comment by HJarausch** [comment]
Yes, please publish it.
I've tried to 'source' a file with PATH and LD_LIBRARY_PATH (after having executed /sbin/su) 
but this doesn't change the environment

**Comment by topjohnwu** [comment]
Thanks for pointing out the issue, will fix soon :)
