### ISSUE TITLE
Magisk Manager (canary) - Inactive confirm dialog

### ISSUE THREAD

**Issue by tsynik** [topjohnwu/Magisk#3131]
With Automatic Response - Grant for Superuser access Magisk shows inactive Confirm dialogue and there is no Dismiss timeout for it. User must press Back button to hide it.

**Comment by palmbeach05** [comment]
i can confirm this issue does exist.

**Comment by osm0sis** [comment]
I believe this is a duplicate of #2944. Please follow along there. :+1:
