### ISSUE TITLE
Bootloop on oneplus 3T oxygen os 9.0.6

### ISSUE THREAD

**Issue by dasche** [topjohnwu/Magisk#3132]
I was on canary version for months without any issues today i got an update to magisk manager and then an update to magisk itself, i updated straight away and rebooted. Device went to bootloop, couldn't pass the first oem boot logo. I had to boot to recovery to uninstall magisk.

This version as of 3 September 2020 of magisk canary is not compatible with OnePlus 3T on latest stock Android.

 Thought this could help the developer. Thanks.

**Comment by palmbeach05** [comment]
> I was on canary version for months without any issues today i got an update to magisk manager and then an update to magisk itself, i updated straight away and rebooted. Device went to bootloop, couldn't pass the first oem boot logo. I had to boot to recovery to uninstall magisk.
> 
> This version as of 3 September 2020 of magisk canary is not compatible with OnePlus 3T on latest stock Android.
> 
> Thought this could help the developer. Thanks.

#3128 , duplicate issue

**Comment by palmbeach05** [comment]
lets just face it, its hitting qualcomm devices hard. ticket is already open and has been for most of the day
