### ISSUE TITLE
Latest canary build cause bootloop on LineageOS 17.1 and ignore safe mode [Moto G7 Plus]

### ISSUE THREAD

**Issue by Tutul-** [topjohnwu/Magisk#3133]
The latest canary build is causing a bootloop early in the boot process (still on the bootloader boot image and before the usual boot vibration). The system enabled safe mode but magisk kept causing bootloop.

Regression to the previous canary build solve the problem but I can't check if the manager properly deactivate itself with the safe mode on because the app is locked. After reboot into normal mode, all modules where disabled, magisk hide was disabled too so I assume it was working (is it normal that the button for "core mode only" is missing from the latest manager ? I just find out it was missing but it's probably like that since a long time ^^")

I was unable to get any debug data to help you, sorry :-/

**Comment by palmbeach05** [comment]
> The latest canary build is causing a bootloop early in the boot process (still on the bootloader boot image and before the usual boot vibration). The system enabled safe mode but magisk kept causing bootloop.
> 
> Regression to the previous canary build solve the problem but I can't check if the manager properly deactivate itself with the safe mode on because the app is locked. After reboot into normal mode, all modules where disabled, magisk hide was disabled too so I assume it was working (is it normal that the button for "core mode only" is missing from the latest manager ? I just find out it was missing but it's probably like that since a long time ^^")
> 
> I was unable to get any debug data to help you, sorry :-/

#3128 , duplicate issue
