### ISSUE TITLE
Canary 20422 patched kernel boots to Fastboot

### ISSUE THREAD

**Issue by ch3mn3y** [topjohnwu/Magisk#3134]
Updating MAGISK to 20422 ends with constant boot into Fastboot. Device tries to boots OS, but than after kernel/device bootlogo it reboots and starts Fastboot.
Hard to get any loss as I don't know of a way to get dmesg when in Fastboot and rebooting it into recovery creates overwrites that file.

Dunno if prepatched and after kernels would be any good?

Similar thing was yesterday with 20421, but than I got no way to write here.

Device is Xiaomi Mi Max 3 with AEX 6.7 (Pie).

**Comment by Master0ne** [comment]
Confirmed, I've just experienced the same issue on a OnePlus 6 with LineageOS 16 for microG.

**Comment by KaMyKaSii** [comment]
Just like in the 20421 build, my Zenfone 4 with Android Pie (just one system partition, ramdisk on boot.img) remains stuck in the ASUS logo. This device does not generate /proc/last_kmsg or /sys/fs/pstore/console-ramoops, I will attach the backup of the asdf partition which may have some relevant log
[asdf.ext4.win.tar.gz](https://github.com/topjohnwu/Magisk/files/5172523/asdf.ext4.win.tar.gz)

> Hard to get any loss as I don't know of a way to get dmesg when in Fastboot and rebooting it into recovery creates overwrites that file.
No  /proc/last_kmsg or /sys/fs/pstore/console-ramoops that you can grab with TWRP?

**Comment by Master0ne** [comment]
I'm a little bit lost with this now. So I was able to boot back to Slot B on my OnePlus 6, but that one now tells me that Magisk is not installed.

I guess till the problem has been solved, the only way is to reinstall Magisk Canary 20420 to Slot A again, to be able to boot Slot A?

Where can I find the Magisk Canary 20420 zip to be flashed from TWRP?

**Comment by Master0ne** [comment]
Since I seem to to be unable to find the Magisk Canary 20420 zip here on GitHub, can someone please provide that file so that I can downgrade?

This is a major pita for me right now, because I really need the latest working Magisk Canary for my online banking apps to work.

**Comment by ch3mn3y** [comment]
> No /proc/last_kmsg or /sys/fs/pstore/console-ramoops that you can grab with TWRP?

Won't it just recreate the file cos I rebooted once again?
Will try in a moment.

> Since I seem to to be unable to find the Magisk Canary 20420 zip here on GitHub, can someone please provide that file so that I can downgrade?

https://support.halabtech.com/index.php?a=downloads&b=file&id=315750
Or look into Android Repository on Telegram.

**Comment by ch3mn3y** [comment]
#
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/5172828/dmesg.txt)

And last_kmsg was saved as empty file.

**Comment by ch3mn3y** [comment]
#3128 #3129 
Seems to be same issue

**Comment by Master0ne** [comment]
> > Since I seem to to be unable to find the Magisk Canary 20420 zip here on GitHub, can someone please provide that file so that I can downgrade?
> 
> https://support.halabtech.com/index.php?a=downloads&b=file&id=315750
> Or look into Android Repository on Telegram.

Thanks for the download link, but unfortunately it requires registration at HalabTech.com to be able to download that file, which I have just tried but didn't receive the email with the confirmation link.

I'm not on Telegram, so any chance for another download link that allows free download?

**Comment by TurtleRecall** [comment]
> I'm a little bit lost with this now. So I was able to boot back to Slot B on my OnePlus 6, but that one is still on stable 20.3 (20300) which does not work with my online banking apps.
> 
> I guess till the problem has been solved, the only way is to reinstall Magisk Canary 20420 to Slot A again, to be able to boot Slot A?
> 
> Where can I find the Magisk Canary 20420 zip to be flashed from TWRP?

Here's a link to 20420, found it in bug report for 20421 and had to use it myself. Would be handy if these were more readily available... 
https://github.com/topjohnwu/magisk_files/blob/51e925d88c07d9fab2017d57c723e28c18a0d996/magisk-debug.zip

**Comment by ihatemicrosoft-was-already-taken** [comment]
btw., same on Pixel 3 blueline

**Comment by ihatemicrosoft-was-already-taken** [comment]
> Where can I find the Magisk Canary 20420 zip to be flashed from TWRP?

It's always in the commit history of the canary branch. You don't have to dig around in bug reports (@TurtleRecall). It works like this:

1. go to https://github.com/topjohnwu/magisk_files
1. select canary branch
1. click "commits"
1. select older commit (in your case 51e925d)
1. click "Browse files"
1. (optional, but recommended) open `debug.json` and confirm magisk version
1. click `magisk-debug.zip`
1. click Download

This way you always should be able to download every version ever. Same applies for the master (i.e. release) branch.

**Comment by TurtleRecall** [comment]
> > Where can I find the Magisk Canary 20420 zip to be flashed from TWRP?
> 
> It's always in the commit history of the canary branch. You don't have to dig around in bug reports (@TurtleRecall). It works like this:
> 
> 1. go to https://github.com/topjohnwu/magisk_files
> 2. select canary branch
> 3. click "commits"
> 4. select older commit (in your case 51e925d)
> 5. click "Browse files"
> 6. (optional, but recommended) open `debug.json` and confirm magisk version
> 7. click `magisk-debug.zip`
> 8. click Download
> 
> This way you always should be able to download every version ever. Same applies for the master (i.e. release) branch.

Thanks, that's really helpful!

**Comment by xerta555** [comment]
Same issue for me too on my LG G6 (H870), bootloop.

**Comment by xdagee** [comment]
bootloop s10e (SM-g970f)

**Comment by ihatemicrosoft-was-already-taken** [comment]
Unfortunately 20423 won't fix the issue for me, I still end up in fastboot.

**Comment by hirenshah** [comment]
It fixed the issue for me on my Samsung Note 8 👍🏼

**Comment by xerta555** [comment]
The 20423 works on my LG G6 (H870) too.

> Unfortunately 20423 won't fix the issue for me, I still end up in fastboot.

Have you do a fresh Magisk install ?

**Comment by hirenshah** [comment]
> It fixed the issue for me on my Samsung Note 8 👍🏼

I spoke too soon. MM doesn't open any more and root access cannot be obtained.

**Comment by ch3mn3y** [comment]
With 20423 everything is fine. Thank You

**Comment by zgfg** [comment]
@ihatemicrosoft-was-already-taken wrote:
It's always in the commit history of the canary branch. You don't have to dig around in bug reports (@TurtleRecall). It works like this:
go to https://github.com/topjohnwu/magisk_files
select canary branch
click "commits"
select older commit (in your case 51e925d)
click "Browse files"
(optional, but recommended) open debug.json and confirm magisk version
click magisk-debug.zip
click Download
This way you always should be able to download every version ever. Same applies for the master (i.e. release) branch.

---
I need to download Magisk Canary 204xxx versions, but when I follow this approach it shows me only down till Oct 7, 2020, i.e., till v21001 (64effe93) and when I click to Older button nothing happens.
Where are Magisk Canary older than v21xxx gone?

Btw, this way it works for Magisk (Canary) zips. In the good old times, it was possible to find Canary json files for older versions, allowing to put them for Custom channel in Magisk Manager and to use for patching images with those old versions, not just for flashing the zip in TWRP
