### ISSUE TITLE
20422 still loops on boot logo on Onn 8

### ISSUE THREAD

**Issue by martyfender** [topjohnwu/Magisk#3135]
on my Onn 8, Android 9 tablet the last two builds, 20421 and 20422 loop at the bootlogo screen, perpetually looping as if constantly restarting. I effectively never reaches the animated boot screen.  rebooting to twrp and flashing 20420 brings back a working system. twrp last_log.gz does not seem to be open-able or I would have sent it. If there is any way I can provide you more info, let me know. A/B No, SAR Yes, Ramdisk No, on the Magisk Manager start up screen. This device always patches the boot.img and not the recovery image. So why is recovery mode automatically checked in MM? This device does have a separate recovery partition.

**Comment by Master0ne** [comment]
I'm affected by the same issue on my OnePlus 6. Where can I find the Magisk Canary 20420 zip file so that I can downgrade?

**Comment by topjohnwu** [comment]
#3134
