### ISSUE TITLE
How to ensure that the Magisk runs the shell file in the module at the specified time

### ISSUE THREAD

**Issue by zhangweildlh** [topjohnwu/Magisk#3137]
I made a Magisk module, the core of which is a shell file. It needs to run after 23 hours. “sleep 23h”

However, the execution failed because the Magisk was killed in the background

**Comment by xerta555** [comment]
> However, the execution failed because the Magisk was killed in the background

Could you a little bit of details please ?
"because the Magisk was filled in the background" have no sense.

**Comment by zhangweildlh** [comment]
Magisk Module:
|
|  ├─META-INF
|  ├─system
|   |   ├─app
|   |    |   |   j11.sh
|   customize.sh
|   module.prop
|   service.sh

the service.sh:
#!/system/bin/sh
... ...
sleep 23h
if [[ -x /system/app/j11.sh ]];then
.  /system/app/j11.sh
fi

**Comment by DanGLES3** [comment]
I believe this might be because Magisk wasn't designed to wait so long for module scripts as they're usually designed to run right before/after the device boots up

**Comment by xerta555** [comment]
> 
> 
> Magisk Module:
> |
> | ├─META-INF
> | ├─system
> | | ├─app
> | | | | j11.sh
> | customize.sh
> | module.prop
> | service.sh
> 
> the service.sh:
> #!/system/bin/sh
> ... ...
> sleep 23h
> if [[ -x /system/app/j11.sh ]];then
> . /system/app/j11.sh
> fi

We need logcat to see in depth.

**Comment by topjohnwu** [comment]
This has nothing to do with Magisk
