### ISSUE TITLE
Stuck on Samsung Note 8 Splash Screen

### ISSUE THREAD

**Issue by hirenshah** [topjohnwu/Magisk#3138]
I flashed the latest canary update to Magisk just now and when rebooting, my Samsung Note 8 froze on the splash screen.  I was able to get into TWRP and flash Magisk v20.4, which allowed my phone to boot.

I am out at the moment and needed my phone operational asap, so haven't had the opportunity to get any logs.  Happy to reattempt the update later on this evening and capture any necessary information.

**Comment by topjohnwu** [comment]
#3134
