### ISSUE TITLE
20423 now boots, but MM stucked at splash screen and no root to apps

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#3139]
Zenfone 4, Android 9.
Despite the toast "X was granted super user permissions" no app is able to use root permissions with the exception of Termux that the "su" command worked and I was able to dump the boot partition for testing. Attached is the boot log, Magisk log and a logcat.
[Logs.tar.gz](https://github.com/topjohnwu/Magisk/files/5175215/Logs.tar.gz)

**Comment by hirenshah** [comment]
Confirmed. This is what I'm experiencing after the last fix which resolved my Samsung Note 8 hanging on the splash screen.

**Comment by Howard20181** [comment]
It is an selinux issue.

**Comment by KaMyKaSii** [comment]
> It is an selinux issue.

You're right. After forcing the Manager to stop and running "su -c setenforce 0" in Termux, the Manager and the root access to apps works again

**Comment by Cyberavater** [comment]
Same here, In 20422 everything was working perfectly for me.

**Comment by Nemisor** [comment]
> > It is an selinux issue.
> 
> You're right. After forcing the Manager to stop and running "su -c setenforce 0" in Termux, the Manager and the root access to apps works again

Excellent command, thank you!
