### ISSUE TITLE
Canary builds from 20420 to current not working on Pixel 3 with Android 11 Beta 3

### ISSUE THREAD

**Issue by ihatemicrosoft-was-already-taken** [topjohnwu/Magisk#3141]
I have tested all canary builds from 20420 to 20424 on my Pixel 3 'blueline'. All of those will end up in bootloader/'Fastboot Mode' (Enter reason: no valid slot to boot).

Here is how I test:

1. Active slot is 'a'
1. Flash Pixel 3 Android 11 Beta 3 with `flash-all.sh` provided from Google
1. Extract `boot.img` from `image-blueline-rpb3.200720.005.zip`
1. Upload `boot.img` to the device
1. Install Magisk by patching uploaded image
1. Download `magisk_patched.img` to computer
1. `fastboot flash boot magisk_patched.img`
1. `fastboot reboot`

Here is something that I have observed: I'm unable to fix the issue (i.e. make the phone bootable again) by simply flashing the original `boot.img`. I still end up in the 'bootloader loop'. Instead, I have to run `flash_all.sh` again.

There is no bootable twrp at this time, so this is the only way to install for me.

I can't see any valuable information in the log, but here it is anyway:
[magisk_install_log_2020-09-05T10_23_10Z.log](https://github.com/topjohnwu/Magisk/files/5177764/magisk_install_log_2020-09-05T10_23_10Z.log)

I'd be happy to provide anything else that could be helpful.

**Comment by mrmazakblu** [comment]
Strange that cannot recover by flashing the extracted boot. This does not help the rooting issue directly, but try to verify flashing the extracted boot.img boots, without being patched. First

**Comment by ihatemicrosoft-was-already-taken** [comment]
Okay, so I have re-tested everything. Simply _booting_ `magisk_patched.img` will not permanently break anything. However, when I _flash_ it instead, I'm no longer able to boot with the stock `boot.img` using `fastboot`. However, I don't seem to need to flash everything again any more, simply flashing the stock `boot.img` will fix things again.

**Comment by palmbeach05** [comment]
We should not even talk about or consider 20421 since clearly it was messed up, and topjohnwu conceeded to error. Probably should reword title to reflect 20422 and up instead

**Comment by mu198** [comment]
I know it might be too easy, but have you ever tried the magisk_patched.img just renamed to Boot.img? And then flashed

**Comment by weebl2000** [comment]
@ihatemicrosoft-was-already-taken I seem to experience the same issue on my Pixel 3a. Did previous versions work for you?

**Comment by topjohnwu** [comment]
#3135
