### ISSUE TITLE
Random Reboots on magisk patched Stock ROM

### ISSUE THREAD

**Issue by meharg840** [topjohnwu/Magisk#3142]
I wasn't able to identify the reason but Im Getting Random reboots on my Samsung Device after doing a full ROM Flash via Odin with Magisk patched AP File. Everything seems to be working fine but device give random reboot. Does anyone have the same issue? need help on this one.

**Comment by HTAEDFOLEGNA** [comment]
Yes keeps rebooting when trying to boot rooted will only let me boot without root
