### ISSUE TITLE
magisk hide cli can add a onekey to add all the processes of pkg？

### ISSUE THREAD

**Issue by LittleTurtle2333** [topjohnwu/Magisk#3143]
I want to write a shell script to add all the app installed on my phone to magisk hide.

Only manager can, cli doesn’t seem to.

magisk hide cli can add a onekey to add all the processes of pkg？

![image](https://user-images.githubusercontent.com/32336368/92303143-cbbc1f00-efa4-11ea-8c3f-e0901e12ecb1.jpeg)

**Comment by LittleTurtle2333** [comment]
目前cli還沒有能添加全部process的功能。有點難弄

**Comment by LittleTurtle2333** [comment]
如果只hide主process，子process也會hide嗎？

If only the main process is hidden, will the child processes also be hidden?

**Comment by topjohnwu** [comment]
Anything forked from the main process will also remain hidden.
Services with separate processes does not fork from the main process, thus the need to list them out directly
