### ISSUE TITLE
All Magisk versions newer than 19.3 (including Canary) fail to hide root from certain apps

### ISSUE THREAD

**Issue by Kratos291** [topjohnwu/Magisk#3145]
The apps in question are the most recent games from Klab, the latest being Tales of Crestoria. With Magisk 19.3 using Magisk Hide and repackaging the manager, the game works fine, but with any version later than 19.3, the game would start for a couple seconds and force shut down, opening the browser to klab's website telling me that a prohibited action was detected. I have tested that with two different devices, an Xperia XZ1 running Android 9 Pie and an Nvidia Shield Tablet running Android 7.0. I have attached a log file from the latest Canary build on the Shield Tablet. Please tell if you need more information.

[magisk_log_20200905_210525.log](https://github.com/topjohnwu/Magisk/files/5178526/magisk_log_20200905_210525.log)

**Comment by Didgeridoohan** [comment]
First of all: #1152 

So please close this so John or Chris doesn't have to.

Second of all: I just tested on Canary 20424, hidden Manager 297 (stub 10), and the game starts without any issue. OnePlus 3T, Android Pie.

**Comment by Kratos291** [comment]
I won't close this because

1) it's not a new detection method

2) it works on 19.3

3) it's a Magisk related bug

4) it's good that it works for you with latest Magisk but not for me and a number of other people

**Comment by Kratos291** [comment]
lmao, closing this without commenting... Well, let Magisk be bugged then. Next time I won’t go out of my way and report bugs.
