### ISSUE TITLE
Hide Magisk Manager fails in Canary 294-297 (MIUI 12, Android 10)

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#3147]
Hide (repackage) Magisk Manager fails:

- Xiaomi Mi 9T, MIUI 12.0.2 (eea, stable), Android 10
- Canary Magisk 20424, Magisk Manager 297
- Everything else works fine
- Play Protect disabled, cleared Cache for Magisk Manager app
- It downloads the stub and pops-up that Hiding Magisk Manager has failed
- Doesn't depend on the new name I choose (tested also with default: Manager)
- Last Magisk Manager version where it worked was 293 (with just the known inconveniences in choosing the repackaged name), after that tested with 295, 296 and 297, Hiding MM always fails

Logs from Magisk Manager and Logcat attached:
[Magisk-log-failed_repackaging_Manager_297.log](https://github.com/topjohnwu/Magisk/files/5182346/Magisk-log-failed_repackaging_Manager_297.log)
[Logcat-log-failed_repackaging_Manager_297.zip](https://github.com/topjohnwu/Magisk/files/5182351/Logcat-log-failed_repackaging_Manager_297.zip)

**Comment by osm0sis** [comment]
@vvb2060, looks like another edge case with repackaging with Play Protect enabled, despite using shell user.

**Comment by vvb2060** [comment]
Maybe MIUI will prevent install app from adb shell……

**Comment by zgfg** [comment]
> Maybe MIUI will prevent install app from adb shell……

If you want, I can test something from Terminal to help you debugging, just describe what

E.g., pm and cmd commands like:
pm disable-user <pkg>
pm enable <pkg>
pm list packages
cmd package bg-dexopt-job
work fine, tested/used those few commands

**Comment by vvb2060** [comment]
su 2000 -c pm install /data/data/com.topjohnwu.magisk/cache/patched.apk

**Comment by zgfg** [comment]
su 2000 -c pm install /data/data/com.topjohnwu.magisk/cache/patched.apk

su -c pm install /data/data/com.topjohnwu.magisk/cache/patched.apk

su 2000 -c ls /data/data/com.topjohnwu.magisk/cache

su -c ls /data/data/com.topjohnwu.magisk/cache

---

SU user 2000 has no rights for 
/data/data/com.topjohnwu.magisk/cache
- while SU user does have:

[Code]
:/ $ su -c ls /data/data/com.topjohnwu.magisk/cach

patched.apk stub.apk

:/ $ su 2000 -c ls /data/data/com.topjohnwu.magisk/cache

Permission denied

:/ $ su 2000 -c pm install data/data/com.topjohnwu.magisk/cache/patched.apk

Exception occurred while executing:

java.lang.IllegalArgumentException: Error: Can't open file: /data/data/com.topjohnwu.magisk/cache/patched.apk
[/Code]

Should I try:
su -c pm install /data/data/com.topjohnwu.magisk/cache/patched.apk
?

![Screenshot_2020-09-08-09-23-55-920_com offsec nhterm](https://user-images.githubusercontent.com/51943147/92450915-50cd5100-f1bc-11ea-9acd-970583a935dc.jpg)

**Comment by vvb2060** [comment]
copy apk to `/data/local/tmp/`, chmod 744 , then su 2000 -c pm install it.

**Comment by zgfg** [comment]
[INSTALL_FAILED_USER_RESTRICTED] error:

:/ $ su 2000 -c ls /data/local/tmp/com.topjohnwu.magisk/cache

patched.apk stub.apk

:/ $ su 2000 -c ls -l /data/local/tmp/com.topjohnwu.magisk/cache/p* 

-rwxr--r-- 1 root root 22215 2020-09-07 11:03 /data/local/tmp/com.topjohnwu.magisk/cache/patched.apk

:/ $ su 2000 -c pm install /data/local/tmp/com.topjohnwu.magisk/cache/patched.apk

Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]

![Screenshot_2020-09-08-10-52-01-526_com mixplorer](https://user-images.githubusercontent.com/51943147/92456206-ee2b8380-f1c2-11ea-86c1-b14eda543404.jpg)
![Screenshot_2020-09-08-10-58-19-688_com offsec nhterm](https://user-images.githubusercontent.com/51943147/92456276-ff749000-f1c2-11ea-8b2b-7de86e08fec1.jpg)

**Comment by vvb2060** [comment]
> Install canceled by user

**Comment by zgfg** [comment]
> > Install canceled by user
I didn't cancel anything myself.
It reports the error immediately when I press Enter to execute the command

I also thought at first that I maybe pressed CtrlC or something, so repeated several times, always the same

And Play Protect was disabled
![Screenshot_2020-09-08-11-40-55-660_com android vending](https://user-images.githubusercontent.com/51943147/92460816-b4f61200-f1c8-11ea-9d1a-d54a2b5bcc79.jpg)

**Comment by zgfg** [comment]
> copy apk to `/data/local/tmp/`, chmod 744 , then su 2000 -c pm install it.

Finally I was able to install from 
data/local/tmp (uid=2000, shell has no rights to access original /data/data/com.topjohnwu.magisk/cache):
su 2000 -c pm install /data/local/tmp/com.topjohnwu.magisk/cache/patched.apk

but with an additional step - instead of with 'default' Developer options for ADB debugging:
![mm1](https://user-images.githubusercontent.com/51943147/92491734-dc61d480-f1f2-11ea-8cb6-76d4c27dfb9f.jpg)

I had to additionaly enable Installation from USB:
![mm2](https://user-images.githubusercontent.com/51943147/92491770-e683d300-f1f2-11ea-9620-7e8aa9c93262.jpg)

Then, it still asked me to allow USB installation of the repackaged Manager:
![mm3](https://user-images.githubusercontent.com/51943147/92491806-f4d1ef00-f1f2-11ea-82e0-2c1394326f14.jpg)
![mm4](https://user-images.githubusercontent.com/51943147/92492012-2e0a5f00-f1f3-11ea-9301-3230ea87de66.jpg)

However, now I have screwed up my MM😁
- I have both apps installed,  repacked Manager and Magisk Manager
(more interesting, the second icon, for Magisk Manager appeared only when I opened the repackaged Manager (stub) and allowed it to download and installed the 'juice'):
![mm5](https://user-images.githubusercontent.com/51943147/92491957-1f23ac80-f1f3-11ea-8cfe-38a02411abe3.jpg)

- both have incomplete Settings (only what you see on the screenshot, nothing more to scroll):
![mm6](https://user-images.githubusercontent.com/51943147/92492072-3cf11180-f1f3-11ea-9e58-bd60a0e50051.jpg)

- moreover, both have disabled SuperUser/Hide and Modules tabs:
![mm7](https://user-images.githubusercontent.com/51943147/92492189-5e51fd80-f1f3-11ea-8cad-f4f1d40c924f.jpg)

I guess, I could now safely remove both and regularly install Canary MM?

**Comment by vvb2060** [comment]
if disable `install via USB`, can install with root? 
`su -c pm install abc.apk`

**Comment by zgfg** [comment]
> if disable `install via USB`, can install with root?
> `su -c pm install abc.apk`

Yes, for uid=0 (root) pm install works with no need for the additional option Install via USB to be enabled

I put another app-release.apk to your folder:
/data/data/com.topjohnwu.magisk/cache/


with chmod 600 (like your patched.apk) and it was installed successfully:
su  -c pm install /data/data/com.topjohnwu.magisk/cache/app-release.apk




su  -c ls -l /data/data/com.topjohnwu.magisk/cache





Ok, I was able to install from 
data/local/tmp (uid=2000, shell has no rights to access original /data/data/com.topjohnwu.magisk/cache):
su 2000 -c pm install /data/local/tmp/com.topjohnwu.magisk/cache/patched.apk



but with an additional step - instead of with 'default' Developer options for ADB debugging:



I had to additionaly enable Installation from USB:


Then, it still asked me to allow USB installation of the repackaged Manager:


However, now I have screwed up my MM:
- I have both apps installed,  repacked Manager and Magisk Manager
(more interesting, the second icon for Magisk Manager appeared only when I opened the repackaged Manager (stub) and allowed it to download and installed the 'juice'):


- both have incomplete Settings (only what you see on the screenshot, nothing more to scroll):


- moreover, both have disabled SuperUser/Hide and Modules tabs:


> if disable `install via USB`, can install with root?
> `su -c pm install abc.apk`

Yes, for uid=0 (root) pm install works with no need for the additional option Install via USB to be enabled

I put another app-release.apk to your folder:
/data/data/com.topjohnwu.magisk/cache/
and with chmod 600 (like your patched.apk):
![IMG_20200908_210149](https://user-images.githubusercontent.com/51943147/92517993-f2ce5700-f217-11ea-8028-825c06e05823.jpg)

and it was installed successfully:
su  -c pm install /data/data/com.topjohnwu.magisk/cache/app-release.apk
![IMG_20200908_210622](https://user-images.githubusercontent.com/51943147/92518104-20b39b80-f218-11ea-9da5-2679bdc22775.jpg)

**Comment by zgfg** [comment]
I don't know why this (...) GitHub mixes two posts into a single one

When open it for editing, there is only my last post, when I save it shows two posts mixed, making it unclear what I wanted to write

Sh...

**Comment by topjohnwu** [comment]
49559ec0ec13aac09c62a8c422fc8126ebfd51a9

**Comment by zgfg** [comment]
Sorry if I misunderstood your fix in GitHub but I tried:
$ su 2000 -c pm install $tmp || pm install $tmp

and it didn't work for me, while the following worked:
$ (su 2000 -c pm install $tmp) || (su -c pm install $tmp)

Of course, if your context is already for uid=0 (root), then the first should work as well

From my Terminal:
$ whoami
u0_a221

$ tmp=/data/data/com.topjohnwu.magisk/cache/app-release.apk
$ ls -l $tmp
Permission denied

$ su 2000 -c ls -l $tmp
Permission denied

$ su -c ls -l $tmp
-rw------- 1 u0_a217 u0_a217_cache 24552506 2020-09-04 11:37 /data/data/com.topjohnwu.magisk/cache/app-release.apk

$ su 2000 -c pm install $tmp || pm install $tmp
Error: Unable to open file: /data/data/com.topjohnwu.magisk/cache/app-release.apk

$ (su 2000 -c pm install $tmp) || (su -c pm install $tmp)
Success

**Comment by osm0sis** [comment]
The Manager commands in the fix commit should be running as root, so should be fine. 👍

**Comment by zgfg** [comment]
Thanks, it works now with your latest Canary MM 298 (and Magisk 20425)

And debugging was interesting, driving me to learn more about shell commands

**Comment by Jammin69960** [comment]
Anyone got a copy of this patched.apk?

**Comment by gustasmor** [comment]
Try uninstalling the magisk manager, and then download the magisk manager 7.5.1, and then hide the magisk manager, after that just open the app, and update it through the hidden magisk manager, it should stay hidden, and after that, they'll ask you to add a shortcut of magisk manager, you should decline and then, you're all set.

**Comment by zgfg** [comment]
> Try uninstalling the magisk manager, and then download the magisk manager 7.5.1, and then hide the magisk manager, after that just open the app, and update it through the hidden magisk manager, it should stay hidden, and after that, they'll ask you to add a shortcut of magisk manager, you should decline and then, you're all set.

Ticket was fixed in Canary (workarounds would not work with the Canary 294-297 as listed above), now it works in 31x and closed
