### ISSUE TITLE
Magisk hide breaks Move certificate module

### ISSUE THREAD

**Issue by techIndia-hacker** [topjohnwu/Magisk#3148]
First of all my is problem is NOT "X app detects root" etc...
I request devs to read through.
Magisk:- 20.4 & 7.5.1 stable
                Also tested on latest canary builds as on 7/9/20
Device:- Oneplus 8
OS :- Oxygen android 10
Problem:- Installed adguard ssl certificate to user store. Use movecrt module to move that certificate to system store. Magisk hide any browser or any app. Adguard certificate is non trusted error comes and broswers show red icon instead of green lock.

Disabling magisk hide for that browser or the app solves the problem. Now the thing is adguard can't filter traffic of apps that need magisk hide. Please look into it

**Comment by DanGLES3** [comment]
Fixing that wouldn't be feasible as Magisk hide works by hiding any system modification from apps (so the app only sees the original/unmodified) system, changing that would literally break Magisk hide

**Comment by DanGLES3** [comment]
Also if you're on Android and use adguard you can simply use its private DNS by going into settings, wifi, private DNS, manual and inputting the following

dns.adguard.com

**Comment by techIndia-hacker** [comment]
Adguard dns is active but https filtering is needed too.
Can hiding modifications in /system/etc/security/cacert folder be excluded from magisk hide.
Please it's a request

**Comment by DanGLES3** [comment]
> Adguard dns is active but https filtering is needed too.
> 
> Can hiding modifications in /system/etc/security/cacert folder be excluded from magisk hide?
> 
> Please it's a request. This won't break magisk hide in any way as there is no way for apps to find out which certificate was written by system modification

Actually there is, the mount points can be easily read by non-hidden apps

**Comment by DanGLES3** [comment]
> > Adguard dns is active but https filtering is needed too.
> > 
> > Can hiding modifications in /system/etc/security/cacert folder be excluded from magisk hide?
> > 
> > Please it's a request. This won't break magisk hide in any way as there is no way for apps to find out which certificate was written by system modification
> 
> Actually there is, the mount points can be easily read by non-hidden apps, thus any mount point related to Magisk could easily be found

**Comment by topjohnwu** [comment]
That's how MagiskHide work
