### ISSUE TITLE
Magisk root detected even with hide

### ISSUE THREAD

**Issue by phr34k0** [topjohnwu/Magisk#3149]
Latest Magisk and Latest grab driver. Root detected even if hide 

![Screenshot_2020-09-08-00-44-26-060_com yB5P joEThL0a nJ](https://user-images.githubusercontent.com/13272249/92407322-cc9fad00-f16c-11ea-94b2-c518925a6c8c.png)
![Screenshot_2020-09-08-00-44-12-000_com grabtaxi driver2](https://user-images.githubusercontent.com/13272249/92407323-ce697080-f16c-11ea-8e08-170ef03a0103.png)
![Screenshot_2020-09-08-00-47-47-095_com android settings](https://user-images.githubusercontent.com/13272249/92407438-2ef8ad80-f16d-11ea-96cc-54912c46c282.png)

**Comment by mu198** [comment]
@phr34k0 Have you ever tried the latest canary build? 
Since the stable has not been revised for a long time 😉
