### ISSUE TITLE
Magisk cannot fix TWRP boot loop - but Supersu can - Pixel C

### ISSUE THREAD

**Issue by nigelhealy** [topjohnwu/Magisk#315]
All was working til I flashed the current stock ROM (July). I had stock, TWRP, Magisk. Then i upgraded to July via full stock and flash the images (bootloader, system, vendor, boot, cache) and then TWRP recovery and to go into TWRP to flash MAgisk.

This problem is somewhere between Pixel C stock ROM, TWRP and Magisk. I suspect the fault begins with stock ROM, TWRP is not able to address, SuperSU can fix this but Magisk cannot.

So:
- begin with everything stock, so stock cache recovery system vendor boot and bootloader
- it boots fine
- flash TWRP recovery (to then be able to flash magisk, if I do not flash magisk, and boot into system, then try to go back into recovery then TWRP is gone, get the "no command" droid exclamation screen, so that made me think this is a TWRP on Pixel C problem.

But:
- stock, flash TWRP, flash SuperSU
- it boots fine. 

So SuperSU is fixing whatever the problem TWRP has.

But:
- stock
- flash TWRP
- go into TWRP
- flash Magisk

Then I get bootloop back into TWRP, just as if I have stock+TWRP (with nothing else)/

So there is some issue which TWRP is not able by itself to address, Magisk doesnt fix it, but SuperSU does fix it.

I want Magisk for suhide. Currently I can only be stock recovery, or TWRP and SuperSU, not TWRP and Magisk.

Magisk appears to install just fine, no errors.

My only option is to try a clean install (so wipe data). I tried deleting Magisk files in /data

**Comment by devz3r0** [comment]
is that the same than this?
https://github.com/topjohnwu/Magisk/issues/284

**Comment by kingweee** [comment]
Same exact problem for me. I get stuck in a recovery bootloop (reboots repeatedly straight into recovery) if I flash 13.3 (through magisk manager or recovery)

How I currently have Magisk working:

- flash full stock (7.1.2 (N2G48B, Jul 2017)
- flash twrp-3.1.0-0-dragon (this recovery will stick, but twrp-3.1.1-0-dragon does not stick, I get the same "no command" if I flash 3.1.1-0)
- Flash Magisk-v13.0(96f8efc) in recovery.

Now though I can't flash the latest version of iYTBP (youtube adblocker). The modules fails to install in 13.0(96f8efc), and I'm getting ads in youtube. =(

**Comment by Kr0n0** [comment]
I have installed Oreo OPR6 + TWRP + the latest Magisk beta 13.6 with no issues on my Pixel C 👍  

Stock Image : [ryu-opr6.170623.010-factory-81a1479d.zip](https://developer.android.com/about/versions/oreo/download.html#top)
TWRP : [twrp-3.1.1-0-dragon-Android-O.img](https://eu.dl.twrp.me/dragon)
Magisk : [Magisk-v13.6(1360).zip](https://forum.xda-developers.com/attachment.php?attachmentid=4243710&d=1502915538)

**Comment by devz3r0** [comment]
thaks for trying that first, I installed 13.6 too, that seems to work on my device too (Purenexus)

**Comment by garoxas** [comment]
can confirm, Magisk-v13.6(1360) works with Pixel C 7.1.2 (N2G48B)
root works perfectly, ctsProfile and basicIntegrity all true
still got "Your device isn't compatible" in the Play Store though

**Comment by The-MAZZTer** [comment]
Magisk v13.3 also does not work with my Pixel C, but 13.6 worked fine. Both Android Nougat and Oreo resulted in booting to recovery with 13.3, but I tried 13.6 with Oreo and it seems to be booting fine now.

**Comment by kingweee** [comment]
> I installed 13.6 too, that seems to work on my device too (Purenexus)
> basic and cts are fine too.
> 

With stock android O (ryu-opr6.170623.010-factory-81a1479d), and Magisk-v13.6(1360), I fail both checks. =(

Not really a surprise though, back on 7.1.2 (ryu-n2g48b-factory-fa17d973), I was failing both checks on a fresh install (no su, no Magisk, no TWRP, just flashall from fastboot then an immediate test via the app "SafetyNet Helper Sample".

I made a post on xda and someone said that having an unlocked bootloader makes you fail the test even if you are running straight stock. Not sure if that is true but something isn't working right.

**Comment by The-MAZZTer** [comment]
My bootloader is unlocked. I have no issue with 13.6.

**Comment by kingweee** [comment]
> My bootloader is unlocked. I have no issue with 13.6.

Are you running ryu-opr6.170623.010-factory-81a1479d?

**Comment by The-MAZZTer** [comment]
Yes. I did a dirty flash of that factory image then installed Magisk 13.3. That resulted in booting to recovery so I re-flashed the stock boot.img and installed 13.6, which worked. It's worth nothing my Pixel C is not encrypted, I don't think it should really matter though.

Here is exactly what I did when I upgrade to Oreo:

1, Downloaded full factory image from Android 8 Developer site.
2. Extracted all img files including the ones inside of the inner zip.
3. TWRP 3.1.1.0 was already installed on my Pixel C (Download and fastboot flash recovery <twrp> at bootloader after step 5 if you don't have it).
4. Pushed Magisk installers to Pixel C for later use.
5. Rebooted Pixel C to bootloader.
6. fastboot flash bootloader <bootloader>
7. fastboot reboot-bootloader
8. fastboot flash boot boot.img
9. fastboot flash vendor vendor.img
10. fastboot flash system system.img
11. Held power and volume down until Pixel C powered off and booted into boot menu.
12. Selected reboot to recovery.
13. In TWRP, flash Magisk 13.3.
14. Wipe cache/dalvik (not sure if needed).
15. Reboot to system.
16. Device rebooted to TWRP (boot failed).
17. Reboot to bootloader using TWRP menu.
18. fastboot flash boot boot.img
19. Held power and volume down until Pixel C powered off and booted into boot menu.
20. Selected reboot to recovery.
21. In TWRP, flash Magisk 13.6.
22. Wipe cache/dalvik (not sure if needed).
23. Reboot to system.
24. Device booted to Oreo.
25. Ran Magisk Manager and did Safetynet check, all green.

**Comment by kingweee** [comment]
> 1, Downloaded full factory image from Android 8 Developer site.
> 2. Extracted all img files including the ones inside of the inner zip.
> 3. TWRP 3.1.1.0 was already installed on my Pixel C (Download and fastboot flash recovery at bootloader after step 5 if you don't have it).
> 4. Pushed Magisk installers to Pixel C for later use.
> 5. Rebooted Pixel C to bootloader.
> 6. fastboot flash bootloader
> 7. fastboot reboot-bootloader
> 8. fastboot flash boot boot.img
> 9. fastboot flash vendor vendor.img
> 10. fastboot flash system system.img
> 11. Held power and volume down until Pixel C powered off and booted into boot menu.
> 12. Selected reboot to recovery.
> 13. In TWRP, flash Magisk 13.3.
> 14. Wipe cache/dalvik (not sure if needed).
> 15. Reboot to system.
> 16. Device rebooted to TWRP (boot failed).
> 17. Reboot to bootloader using TWRP menu.
> 18. fastboot flash boot boot.img
> 19. Held power and volume down until Pixel C powered off and booted into boot menu.
> 20. Selected reboot to recovery.
> 21. In TWRP, flash Magisk 13.6.
> 22. Wipe cache/dalvik (not sure if needed).
> 23. Reboot to system.
> 24. Device booted to Oreo.
> 25. Ran Magisk Manager and did Safetynet check, all green.

I'll try it thanks. Mine went like this:

1. flash-all.bat ryu-opr6.170623.010-factory-81a1479d
2. Boot into Android O.
3. Enable developer options--->usb debugging
4. adb reboot bootloader.
5. fastboot flash recovery twrp-3.1.1-0-dragon-Android-O.img
6. Held power and volume down until Pixel C powered off and booted into boot menu.
7. Booted into TWRP
8. Used ADB Push Magisk-v13.6(1360).zip
9. Flashed the zip
10. Rebooted.
11. Magisk installed, fails CTS and basic.

I am encrypted though, that is one difference.

**Comment by kingweee** [comment]
Just followed your instructions:

1, Downloaded full factory image from Android 8 Developer site.
2. Extracted all img files including the ones inside of the inner zip.
3. Already had TWRP ( twrp-3.1.1-0-dragon-Android-O.img)
4. Pushed Magisk installers to Pixel C for later use.
5. Rebooted Pixel C to bootloader.
6. fastboot flash bootloader
7. fastboot reboot-bootloader
8. fastboot flash boot boot.img
9. fastboot flash vendor vendor.img
10. fastboot flash system system.img
11. Held power and volume down until Pixel C powered off and booted into boot menu.
12. Selected reboot to recovery.
Skipped the 13.3 stuff.
21. In TWRP, flash Magisk 13.6.
22. Wipe cache/dalvik (not sure if needed).
23. Reboot to system.
24. Device booted to Oreo.
25. Ran Magisk Manager and did Safetynet check, all green.

Yep, all green. Not sure what was wrong but thanks for the info. Looks good now.
