### ISSUE TITLE
Where does Magisk stores the magisk.db file?

### ISSUE THREAD

**Issue by Andrew-afk** [topjohnwu/Magisk#3151]
I'm in a quest for solving the **"su: request rejected"** issue. And as you might have guessed, lastest Official, Beta (267) and Canary (297) doesn't work.
The problem is that i have a custom rom (according to pinned issues). But Magisk was working after that issue, its just not showing the permission dialog.

I just want to know where does lastest Canary saves the magisk.db file, in case of succesful rooted device.

Here's what i'm going to do:
1. Get the file <-- From /?/?/
2. Edit it with a SQL editor, for adding the root apps
3. Overwrite the file.

If this method doesn't work then i need to restore the official rom on my device (which is impossible, because the official was of 32bits, while the actual is of 64bits, so i needed to use a repartitioner, and i can't find the flashable file for reverse it)

**Comment by Andrew-afk** [comment]
Also, if magisk uses a different format, can you send a link to the file? I have one saved of some older versions

**Comment by DanGLES3** [comment]
/data/adb/Magisk.db

**Comment by Andrew-afk** [comment]
> /data/adb/Magisk.db

Looka like Canary is using a different sql format, i need the official file

**Comment by osm0sis** [comment]
And/or #2944

**Comment by Andrew-afk** [comment]
> And/or #2944

I suppose this isn't closed yet, i don't have the file.

**Comment by osm0sis** [comment]
You don't need one, just use the Magisk uninstaller or recovery to clean out /data/adb, then reinstall.

**Comment by Andrew-afk** [comment]
> You don't need one, just use the Magisk uninstaller or recovery to clean out /data/adb, then reinstall.

I did all of that before, and still not working, that's the reason i'm asking for this file, magisk didn't created the file, i suppose it happens because i need at least one root app to write the file.
The logs shows that it's crashing at boot: "write failed with 32: broken pipe"
Again, my problem is the custom rom i'm using, since magisk blocks itself on GSIs (#844) the dialog is not showing anymore, but root in allowed apps still working.

**Comment by osm0sis** [comment]
No, Magisk creates it just by running. If you're running on a GSI then that's also not directly supported currently, as you pointed out.

**Comment by Andrew-afk** [comment]
> No, Magisk creates it just by running. If you're running on a GSI then that's also not directly supported currently, as you pointed out.

Then, why do previusly allowed apps still working?

Ok, i'll do it myself. Thanks for nothing osm0sis, you helped me a lot!

**Comment by Andrew-afk** [comment]
**I have the best friends in the world!. They gave me a copy of their files and with some edits now magisk is finally working!!**
I just need to reboot everytime i add a root app but i can live with it. Anyways, thanks for c̶l̶o̶s̶i̶n̶g̶ ̶i̶s̶s̶u̶e̶s̶ ̶w̶i̶t̶h̶ ̶n̶o̶ ̶a̶n̶s̶w̶e̶r̶ always assisting the community!

**Comment by osm0sis** [comment]
This isn't a help desk for general inquiries, go to xda. You're welcome. 😉
