### ISSUE TITLE
pixel 2 xl on android 11

### ISSUE THREAD

**Issue by alexstaj** [topjohnwu/Magisk#3154]
HI

Thanks for your work.  I just installed android 11 on pixel 2 xl.  I put twrp and installed magisk from zip (v20.4) from twrp.

then it just bootloops until I reinstall android 11.

help pleze

**Comment by stanleylhs** [comment]
Please read #3153

**Comment by Didgeridoohan** [comment]
For Android 11 you need to use the Canary releases for now.

This isn't actually an issue, so please close this so that Chris or John doesn't have to.

**Comment by alexstaj** [comment]
HI

where is the canary build zip file?

I couldn't find it under github releases
