### ISSUE TITLE
Solving the "Root overlay not showing"

### ISSUE THREAD

**Issue by Andrew-afk** [topjohnwu/Magisk#3155]
First of all: i really wanted to post this on xda, but my other account doesn't reach the 10 ***"helpful"*** posts, so if you are active in there, feel free to post this here to help out more people.

Let's go right to the point:
I'm using a custom rom, CSI, and magisk is not working, so i did a lot of research and finally came with a working solution:

**Setup:**

First, you'll need a SQL Editor, you can find it on playstore. 
I also modified one for get rid of ads, you can download it if you want. [SQLite_Editor_2.0.8_NoAd - Mediafire](http://www.mediafire.com/file/6qkbshy6qkk92wl/SQLite_Editor_2.0.8.apk/file) 

Next, you will need RAR app (or any other similar)
 At this point you should have one installed already, but here is a link for it: [RAR - PlayStore](https://play.google.com/store/apps/details?id=com.rarlab.rar)

And last, you'll need a custom made app by me, it's for get installed apps package name and uid, neccesary for editing magisk superuser database.  And also it has a copy of the magisk.db file on it.
*If you don't trust me, you don't need to, you can find another method somewhere.* * [MagiskRootFix - Mediafire](http://www.mediafire.com/file/l4c9vg2o3dlg95j/Rootfix_1.00.apk/file)

**Steps:**

Assuming everything is installed (including magisk), open RootFix, you will see a list of your installed apps. If you tap in one of them, you can copy the package name and uid.

![1599625911413](https://user-images.githubusercontent.com/60042213/92554692-f079f600-f233-11ea-920c-35608ee6e092.png)

• Tap on "Create magisk.db file", this will create a magisk database file in /sdcard/Databases.

• Next, open the SQL editor and open the created database file. Then tap in "policies".
• There is a table where all the allowed apps are located:

![1599626232704](https://user-images.githubusercontent.com/60042213/92555329-6763be80-f235-11ea-80bc-c10ae5dda774.png)

• As you can see, the first element is an app, all you need to do is add a new element, in the same format.
 Just tap on the add symbol and copy the desired app uid and package name, by tapping it in the list:
 
![1599626848502](https://user-images.githubusercontent.com/60042213/92555666-261fde80-f236-11ea-9bf0-498ac65498bd.png)

• And pasting it
![1599626872193](https://user-images.githubusercontent.com/60042213/92555672-3041dd00-f236-11ea-9b7a-40e9cec576cd.png)

**Comment by topjohnwu** [comment]
#3156
