### ISSUE TITLE
How to solve "Root overlay not showing" issue once for all

### ISSUE THREAD

**Issue by Andrew-afk** [topjohnwu/Magisk#3156]
First of all: i really wanted to post this on xda, but my other account doesn't reach the 10 "helpful" posts, so if you are active in there, feel free to post this here to help out more people.

This thread is for help those people with this same issue.

Let's go right to the point:
I'm using a custom rom, GSI, and magisk is not working, so i did a lot of research and finally came with a working solution:

**Setup:**

First, you'll need a SQL Editor, you can find it on playstore. 
I also modified one for get rid of ads, you can download it if you want. [SQLite_Editor_2.0.8_NoAd - Mediafire](http://www.mediafire.com/file/6qkbshy6qkk92wl/SQLite_Editor_2.0.8.apk/file) 

Next, you will need RAR app (or any other similar)
 At this point you should have one installed already, but here is a link for it: [RAR - PlayStore](https://play.google.com/store/apps/details?id=com.rarlab.rar)

And last, you'll need a custom app made by me, it's for get installed apps package name and uid, neccesary for editing magisk superuser database.  And also it has a copy of the magisk.db file on it.
*If you don't trust me, you don't need to, you can find another method somewhere.* * [MagiskRootFix - Mediafire](http://www.mediafire.com/file/l4c9vg2o3dlg95j/Rootfix_1.00.apk/file)

**Steps:**

Assuming everything is installed (including magisk), open RootFix, you will see a list of your installed apps. If you tap in one of them, you can copy the package name and uid.

![1599625911413](https://user-images.githubusercontent.com/60042213/92554692-f079f600-f233-11ea-920c-35608ee6e092.png)

• Tap on "Create magisk.db file", this will create a magisk database file in /sdcard/Databases.

• Next, open the SQL editor and open the created database file. Then tap in "policies".
• There is a table where all the allowed apps are located:

![1599626232704](https://user-images.githubusercontent.com/60042213/92555329-6763be80-f235-11ea-80bc-c10ae5dda774.png)

• As you can see, the first element is an app, all you need to do is add a new element, in the same format.
 Just tap on the add symbol, then go to RootFix and copy the desired app uid and package name, by tapping it on the list:
 
![1599626848502](https://user-images.githubusercontent.com/60042213/92555666-261fde80-f236-11ea-9bf0-498ac65498bd.png)

• And pasting it here:

![1599626872193](https://user-images.githubusercontent.com/60042213/92555672-3041dd00-f236-11ea-9b7a-40e9cec576cd.png)

• Then tap "add" (The bottom button)

**Just copy the last four values like in the picture. You can modify the permissions later in magisk manager.**

You can add as many apps as you want.

• Once you're done, make sure to save the file, open RootFix again and tap "Build module".
• A folder called "magiskmod" will appear right next to the database file.
Open it and select all. Then compress it as .zip file:

![1599627686648](https://user-images.githubusercontent.com/60042213/92556467-0f7a8700-f238-11ea-9f61-1f8d0f991e87.png)

And finally, all left to do is flash the zip as a magisk module:

![1599628105860](https://user-images.githubusercontent.com/60042213/92556973-2a99c680-f239-11ea-9547-251a3479a122.png)

• And hopefully just go to Superuser section and all your apps will be there!
![1599628151660](https://user-images.githubusercontent.com/60042213/92557020-48672b80-f239-11ea-94f2-1de8ced51083.png)

This is obviusly getting closed, but please, pin it or reference it in other issues with this problem.

**Comment by topjohnwu** [comment]
Please check #2944, there is an issue somewhere, and nobody is providing relevant info to me.
This is NOT a solution 😕

**Comment by Andrew-afk** [comment]
> Please check #2944, there is an issue somewhere, and nobody is providing relevant info to me.
> This is NOT a solution 😕

Yeah, all of us with this problem never gonna see that overlay again, this is the only way for now.

Luckely, there is one thing * **you** *  can do: Add an option to the manager where there is a list of apps, and when we click in one, it ask us to add this app as root app, then write the data to the database file, via magisk flasher in background.
That is what this method is doing. And i'm pretty sure it will work too.

You can add also a different overlay, one which requires "show in top" option in app settings, with a confirmation and this adds the app to the database

**Comment by Didgeridoohan** [comment]
@Andrew-afk What you've done here is not a solution. It is a workaround.

The only way to find a solution is if those who are affected help providing the relevant information for @topjohnwu to be able to fix it properly.

**Comment by Andrew-afk** [comment]
> @Andrew-afk What you've done here is not a solution. It is a workaround.
> 
> The only way to find a solution is if those who are affected help providing the relevant information for @topjohnwu to be able to fix it properly.

Well, topjhonwu blocked magisk in purpose for those devices with GSIs installed, so there isn't really an official fix then.
This "workaround" works fine.

**Comment by Didgeridoohan** [comment]
No-one has "blocked" GSIs. They're just often too full of non standard hacks to properly be able to support them (I guess you've read #844).

And to be honest your workaround is also a bit of a non standard hack, which is why (and of course I'm only guessing here) it was closed.

**Comment by Andrew-afk** [comment]
> No-one has "blocked" GSIs. They're just often too full of non standard hacks to properly be able to support them (I guess you've read #844).
> 
> And to be honest your workaround is also a bit of a non standard hack, which is why (and of course I'm only guessing here) it was closed.

I was expecting it to be closed anyways, github isn't for this things.

My workaround just uses the magisk module flasher to copy a file, that's it.
And, if the modules still working, then, why the overlay isn't showing?

Also, if magisk shows an overlay, why the option isn't showing in the android app manager?
I mean, if i go to "manage apps > magisk" there is no overlay option, shouldn't be one in there?

**Comment by Andrew-afk** [comment]
> No-one has "blocked" GSIs. They're just often too full of non standard hacks to properly be able to support them (I guess you've read #844).
> 
> And to be honest your workaround is also a bit of a non standard hack, which is why (and of course I'm only guessing here) it was closed.

Well, no replies. Of course something really is going on here.

**Comment by Didgeridoohan** [comment]
What kind of reply are you looking for? This ticket has been closed and done with, work on trying to fix the real issue continues elsewhere...
