### ISSUE TITLE
Google Pixel 2 bootloop on Android 11

### ISSUE THREAD

**Issue by kyoto44** [topjohnwu/Magisk#3157]
Installed latest version from canary branch via TWRP and boot doesn't even starts

**Comment by stanleylhs** [comment]
Try using the patch boot.img method, it works as in #3153

**Comment by IahmadDev** [comment]
boot.img method also creates a bootloop on my pixel 2, I had to reset it.

**Comment by MaxwellDPS** [comment]
Can confirm, boot Loop occurring on Pixel 4 flame using the manager app as well

**Comment by SkeleBones** [comment]
I am having the same issue on Pixel 2 XL.

**Comment by topjohnwu** [comment]
According to @stanleylhs, this is apparently user error

**Comment by kyoto44** [comment]
@topjohnwu user error? so if you and installing magisk on clean system and isn't boots it's user error?

**Comment by topjohnwu** [comment]
@kyoto44 don't install via TWRP, it's that simple.
TWRP is not designed to run on Android 11 yet

**Comment by kyoto44** [comment]
@topjohnwu so could you tell the way how i should install it?

**Comment by 109021017** [comment]
> @topjohnwu could you tell the way how me and others should install it?
You can install magisk without TWRP
1. patch your boot.img by magisk. 
2. reboot to bootloader
`adb reboot bootloader`
3. flash the new magisk patched boot img.
`fastboot flash boot magisk_patched.img`
4. reboot to system
`fastboot reboot`

But I am actually install it this way on my Pixel 2 XL. Stuck at Google Logo, after I doing this. Not sure if it's my problem or not.

**Comment by Didgeridoohan** [comment]
>But I am actually install it this way on my Pixel 2 XL. Stuck at Google Logo, after I doing this. Not sure if it's my problem or not.

Have you made sure that you don't have any modules installed that could be incompatible with A11?

**Comment by 109021017** [comment]
@Didgeridoohan No module has been installed yet.

**Comment by Didgeridoohan** [comment]
> @Didgeridoohan No module has been installed yet.

And no leftovers from a previous Magisk install? Did you perform a full uninstall of Magisk prior to updating, or wipe /data?

**Comment by 109021017** [comment]
> > @Didgeridoohan No module has been installed yet.
> 
> And no leftovers from a previous Magisk install? Did you perform a full uninstall of Magisk prior to updating, or wipe /data?

Yes, I clear the storage of Magisk Installer from Settings after update to canary version.

**Comment by mu198** [comment]
Have you also tried after the flashes to come to the stocj recovery and made a factory reset there, had worked for me

**Comment by 109021017** [comment]
> Have you also tried after the flashes to come to the stocj recovery and made a factory reset there, had worked for me

I don't want to wipe the data. But if that's the only way, I will give it a try.

**Comment by Didgeridoohan** [comment]
> Yes, I cleared the storage of Magisk Installer from Settings after update to canary version.

What? That wouldn't remove any modules... Modules are stored in /data/adb/modules, completely separate from the Manager. You would have to either do a complete uninstall of Magisk (not the Manager), manually delete them from /data/adb/modules or wipe /data to remove them.

**Comment by mu198** [comment]
> Haben Sie auch versucht, nach den Blitzen zur stocj-Wiederherstellung zu kommen und dort einen Werksreset durchzuführen, hatte für mich gearbeitet

You don't have to make a complete reset, your data can be preserved

Do they just have to look at what their recovery writes/says 😉

**Comment by 109021017** [comment]
> > Yes, I cleared the storage of Magisk Installer from Settings after update to canary version.
> 
> What? That wouldn't remove any modules... Modules are stored in /data/adb/modules, completely separate from the Manager. You would have to either do a complete uninstall of Magisk (not the Manager), manually delete them from /data/adb/modules or wipe /data to remove them.

1. I boot into TWRP temporarily, and delete the /data/adb/modules folder

**Comment by OneTw0** [comment]
> Try using the patch boot.img method and flash via fastboot, it works as in #3153

Also, at least for me. After trial & many errors. I realized my adb files where the culprit. I hadn't updated them. After that. Everything went smoothly. Running Android 11 Magisk on Pixel 2 XL.

**Comment by mstan** [comment]
HI all, re-opening this issue since I'm running into the same problem without any clear solution.

Pixel 2 XL unlocked. Android 11. Factory reset. Tried installing Magisk right out of the gate. Attempting either the TWRP method or fastboot magisk install method cause a bootlop. 

No modules are installed. Just trying a clean Magisk install on Android 11. Patched using Canary nightly. Doesn't seem to matter.

Double checked to see if /data/adb/modules was present. Folder doesn't even exist.

No idea where to go from here.
