### ISSUE TITLE
[Question] Prevent changing ro.build.type to user

### ISSUE THREAD

**Issue by Eva850** [topjohnwu/Magisk#316]
Hello, how can I prevent from changing ro.build.type to user? I can pass safetynet with ro.build.type=userdebug and switching it to user disables some system functionality for example Modem Switcher on Sony devices.

**Comment by Didgeridoohan** [comment]
Add a script with resetprop to /magisk/.core/service.d. It's run after MagiskHide changes the sensitive props and should be able to change it back to your preference.

`resetprop ro.build.type userdebug`

That prop change isn't meant for SafetyNet, but a lot of other apps use it to check for a "compromised" device.

**Comment by Eva850** [comment]
It works for me, thanks.
