### ISSUE TITLE
Magisk Manager UI is extremely confusing without an Internet connection - Install button is missing

### ISSUE THREAD

**Issue by realityexists** [topjohnwu/Magisk#3160]
https://topjohnwu.github.io/Magisk/install.html#samsung-system-as-root says:

> 4. In Magisk Manager: Install → Install → Select and Patch a File and select the AP tar file.

But this is what I see:

![Magisk-WiFi-off](https://user-images.githubusercontent.com/856400/92660445-b1fb3e80-f2fa-11ea-93af-ef372f951c78.png)

There is no install button to be found anywhere! It's only when an Internet connection is established that it appears:

![Magisk-WiFi-on](https://user-images.githubusercontent.com/856400/92660446-b293d500-f2fa-11ea-8d58-8fe5c8558e9d.png)

This may sound like a silly problem when you know about it, but it is *totally* non-obvious when you don't. I even ran into this about a year ago and *still* spent a good 20 minutes bashing my head against a wall and searching for solutions.

Please make the UI say something like "No Internet connection detected - connect to the Internet to install Magisk" and update the instructions to include this information as well. Better yet, don't require an Internet connection and allow me to patch with a Magisk ZIP file I downloaded from GitHub.

**Comment by topjohnwu** [comment]
Only report bugs on canary builds, thanks

**Comment by realityexists** [comment]
Has this changed in the canary build?
