### ISSUE TITLE
Sensitive Notifications setting keeps getting reset

### ISSUE THREAD

**Issue by hmnd** [topjohnwu/Magisk#3161]
Since Android 10, including latest Magisk canary on Android 11, the Sensitive Notifications setting keeps resetting to On, on my Pixel 2 XL. I have tried to disable all modules, revoke all Superuser access, disabling Magisk Hide, and even factory resetting and re-rooting my phone, to no avail. I have confirmed that this does not occur while unrooted.

**Comment by topjohnwu** [comment]
This doesn't seem reasonable that something Magisk can do, it might be tied to some hacks like MagiskHide or other modules, which is not something I can fix
