### ISSUE TITLE
Manager icon missing

### ISSUE THREAD

**Issue by Massi-X** [topjohnwu/Magisk#3163]
Hi, with the latest canary if you try to hide the manager the new app won't have any icon (standard bug droid).

Thank you for your hard work!

**Comment by unixandria-xda** [comment]
I think this is on purpose, because some app developer coudl in theory query all app icons and check if it matches the manager icon

**Comment by Didgeridoohan** [comment]
Yes, it is not a bug. It's a feature.

**Comment by Massi-X** [comment]
Wow so bad! Can we put a different icon maybe?

**Comment by Massi-X** [comment]
I don't know if can be better, but maybe a shortcut to the actual app like some app already do? (If you uninstall any of these apps you can see: this app is part of another application etc.)

**Comment by Massi-X** [comment]
Hi, I've opened it and see the hint to add a shortcut. But I didn't mean this type of shortcut. I mean an activity-alias declared in the manifest with the actual app icon, only if this is possible and don't get detected by other apps searching for it.
I think it is really unaesthetic, you make a damn good work with the manager itself and the missing icon is so bad.

If you think it is not an issue, close it. I'll live with this. Thank you.
