### ISSUE TITLE
Pixel 2 xl on android 11, cannot install magisk canary through boot.img

### ISSUE THREAD

**Issue by cantelope** [topjohnwu/Magisk#3165]
My pixel 2 xl is on android 11 (stock recovery, so android 11 applied cleanly and I lost root and magisk upon reboot).

**Uninstall old magisk** I've uninstalled magisk using:
adb reboot bootloader
fastboot boot twrp-3.3.0-0-taimen.img
install magisk-uninstall.zip
check that /data/adb/modules doesn't exist

**Prepare patched boot.img** I've updated to magisk manager canary, and downloaded the latest a11 taimen factory image from https://dl.google.com/dl/android/aosp/taimen-rp1a.200720.009-factory-f2d162ef.zip, extracted image-taimen-rp1a.200720.009.zip from it and extracted  boot.img from that.

Then I uploaded boot.img to my phone, used magisk manager canary to patch it, and downloaded magisk_patched.img to my computer.

Finally, I did 
```
adb reboot bootloader
fastboot flash boot magisk_patched.img
fastboot reboot
```

Upon rebooting, I get back to android 11 cleanly with no bootloops etc but with no magisk.

I've also tried with `fastboot --set-active=other`, but this gets stuck at google logo for a long time. gave up and rebooted a few times including to bootloader, and after that it goes back to android 11 without magisk.

Am I doing something wrong?

**Comment by topjohnwu** [comment]
I don't know what you did wrong here, but other people have Magisk running on Pixel 2 without an issue.
Please ask for help on forums, not here in GitHub issues.

**Comment by OneTw0** [comment]
> My pixel 2 xl is on android 11 (stock recovery, so android 11 applied cleanly and I lost root and magisk upon reboot).
> 
> **Uninstall old magisk** I've uninstalled magisk using:
> adb reboot bootloader
> fastboot boot twrp-3.3.0-0-taimen.img
> install magisk-uninstall.zip
> check that /data/adb/modules doesn't exist
> 
> **Prepare patched boot.img** I've updated to magisk manager canary, and downloaded the latest a11 taimen factory image from https://dl.google.com/dl/android/aosp/taimen-rp1a.200720.009-factory-f2d162ef.zip, extracted image-taimen-rp1a.200720.009.zip from it and extracted boot.img from that.
> 
> Then I uploaded boot.img to my phone, used magisk manager canary to patch it, and downloaded magisk_patched.img to my computer.
> 
> Finally, I did
> 
> ```
> adb reboot bootloader
> fastboot flash boot magisk_patched.img
> fastboot reboot
> ```
> 
> Upon rebooting, I get back to android 11 cleanly with no bootloops etc but with no magisk.
> 
> I've also tried with `fastboot --set-active=other`, but this gets stuck at google logo for a long time. gave up and rebooted a few times including to bootloader, and after that it goes back to android 11 without magisk.
> 
> Am I doing something wrong?

Make sure your adb fastboot tools are the most recent. I had the same issue. Untill I realized I had outdated platform tools.
