### ISSUE TITLE
Issue #2944 continued (new issue opened per request/advice)

### ISSUE THREAD

**Issue by palmbeach05** [topjohnwu/Magisk#3166]
Per @osm0sis , i am opening up this issue here as a continuation of #2944 . @topjohnwu requested logs there but never recieved them. Logs are attached here.

The past issue seems to continue in most recent update. While setting magisk to auto grant any requests for root access, the request is granted.

However, the pop up window that lets you chose to grant or deny pops up briefly, then fades to the background. When attempting to open magisk manager, the pop up window is displayed, and remains in a stuck position, the same stuck position seen in the previous issue. Hitting the back button, as in the previous issue, is the way to get out of it.

[logs-2020-09-10-16-51-55.zip](https://github.com/topjohnwu/Magisk/files/5205786/logs-2020-09-10-16-51-55.zip)

**Comment by topjohnwu** [comment]
Fixed in b510dc51acdb9f7dd7ec41dabe62cd637bbd16c5
