### ISSUE TITLE
latest canary bootloop on Redmi K20 Pro running A11

### ISSUE THREAD

**Issue by abdoi94** [topjohnwu/Magisk#3168]
Hi there, i tried to root my phone running A11 ROM with Q OEM vendor, but it sends me back to TWRP after installing it

included [in here](https://drive.google.com/drive/folders/1yqCDrjqbCrYD1cQnZRZkUcNRjtf0xm0g?usp=sharing), original boot img and patched one with ramoops

raphael is SAR/A-Only got released with Pie originaly

**Comment by topjohnwu** [comment]
Have you tried patching the recovery image with recovery mode selected?

**Comment by abdoi94** [comment]
> Have you tried patching the recovery image with recovery mode selected?

i did, same issue.... uploaded recovery mode ramoops to the same folder above

**Comment by linucksrox** [comment]
Hey I had a similar issue on a Pixel 3a. What I did was download the boot.img from Android 11 factory image, then patched from the latest canary of Magisk (running in the Android 10 still), did the upgrade, booted successfully without magisk, then applied the patched boot image (magisk_patched.img). It kept looping back to the bootloader.

Then I booted into Android 11, ran magisk and patched the stock boot.img again, this time it generated a file with a slightly different size. Went back to the bootloader, flashed that, and now it's working.

**Comment by pavanpaps** [comment]
Just reproduced your method of flashing and unfortunately it kicks me back to my recovery.

**Comment by pavanpaps** [comment]
> Hey I had a similar issue on a Pixel 3a. What I did was download the boot.img from Android 11 factory image, then patched from the latest canary of Magisk (running in the Android 10 still), did the upgrade, booted successfully without magisk, then applied the patched boot image (magisk_patched.img). It kept looping back to the bootloader.
> 
> Then I booted into Android 11, ran magisk and patched the stock boot.img again, this time it generated a file with a slightly different size. Went back to the bootloader, flashed that, and now it's working.

Just reproduced your method of flashing and unfortunately it kicks me back to my recovery.

**Comment by Viel0320** [comment]
try version 20422，it works well

**Comment by pavanpaps** [comment]
> try version 20422，it works well

Thank you for the help. It works here on my end here. Latest Canary seems to be causing me some issues (atleast on raphael)

**Comment by abdoi94** [comment]
> try version 20422，it works well

Yup, works here also, [this one](https://github.com/topjohnwu/magisk_files/blob/e4030f69a430a6fe845b28f8a9954b438b12d637/magisk-debug.zip)

**Comment by cptmacp** [comment]
20423 , seem to be working fine as well 
https://github.com/topjohnwu/magisk_files/commit/34fa199e57acaa99806b1353a351ef773b3249de



![image](https://user-images.githubusercontent.com/11556463/93005233-d4948e00-f56c-11ea-8d52-46540b5a620c.png)

**Comment by pndwal** [comment]
Hope all you guys are performing these tests with stock recovery flashed, NOT with incompatible TWRP (fully compatible with Android 10.0 at best)!... PW

**Comment by abdoi94** [comment]
may i ask why this got clsoed without any further comments ?

**Comment by pavanpaps** [comment]
The Thing here is
- 20422 works fine and boots and flashing subsequent versions via the manager works and does boot
- But the issue here is on the subsequent versions, i.e 20423, 20424, 20425 on a clean flash causes the system to reboot to recovery.
- Although I'm not sure if this is addressed in the newer version after 20425, if it is then its fine

**Comment by abdoi94** [comment]
@topjohnwu latest build d6dbab53 still bootloops, same issue as before,[console-ramoops-magisk-d6dbab53.txt](https://github.com/topjohnwu/Magisk/files/5292634/console-ramoops-magisk-d6dbab53.txt)

here is what i tried:
- patching boot from magisk app running A11 then flashing them, tried both boot and recovery mode (while running AOSP stock recovery)
- flashing latest zip from twrp

all methods results in rebooting to fastboot

**Comment by abdoi94** [comment]
more ramoops from v21

Booting up normally without anything, not even gapps
[console-ramoops-0-raphael-11-without-magisk.txt](https://github.com/topjohnwu/Magisk/files/5321744/console-ramoops-0-raphael-11-without-magisk.txt)

Magisk v21 installed through Twrp or patched boot img
[console-ramoops-0-raphael-11-magisk-bootloop.txt](https://github.com/topjohnwu/Magisk/files/5321745/console-ramoops-0-raphael-11-magisk-bootloop.txt)

v21 applied from within latest manager running canary 20422, it boots up fine
[console-ramoops-0-raphael-11-magisk-working.txt](https://github.com/topjohnwu/Magisk/files/5321746/console-ramoops-0-raphael-11-magisk-working.txt)

**Comment by abdoi94** [comment]
running canary 
[console-ramoops-0-magisk-21001-bootloop.txt](https://github.com/topjohnwu/Magisk/files/5321778/console-ramoops-0-magisk-21001-bootloop.txt)

**Comment by kondors1995** [comment]
Same here (K20 pro chinease A11) @topjohnwu

**Comment by pengus77** [comment]
Same here (Grus, MI 9 SE, AOSP 11). 20422 is the last one that doesn't force a reboot to recovery / fastboot after a clean flash. Also, having a subsequent version flashed via Manager and triggering a OTA update (addon.d) causes the system to reboot into recovery / fastboot. Funny thing is that I can upgrade to any version via Manager and works just fine.
