### ISSUE TITLE
Module Problem

### ISSUE THREAD

**Issue by George4All** [topjohnwu/Magisk#3169]
I am having a lot of problems with flashing zips to my phone. If I flash it from the downloads sections, it works perfectly but when I try  to flash a zip from internal storage, it says that it's installed. When I go to the Modules section (before rebooting) it doesnt show up and after I reboot, it's like nothing ever happened. I would really appreciate if someone could help. This has happened on ANX Camera, Youtube Vanced and way more

**Comment by Didgeridoohan** [comment]
Wrong place for this kind of thing. You should post over at XDA instead.

Relevant info to take a look at first:
https://www.didgeridoohan.com/magisk/Magisk#hn_Modules_seem_to_install_but_arent_there_after_rebooting

Please close this so that Chris or John doesn't have to.

**Comment by George4All** [comment]
Thanks, sorry. I'm new here
