### ISSUE TITLE
13.3 Install Failed On Xperia X Pure Stock ROM 7.1

### ISSUE THREAD

**Issue by Dave247** [topjohnwu/Magisk#317]
I've been having a lot of issues with v13+ on my device so I'm finally trying to get to the bottom of it. For whatever reason any version of Magisk 13+ refuses to install and comes up with an error. This has been done on a pure stock ROm after just having flashed from Flashtool. Attached is the recovery log when trying to install it, as well as my boot.img
[recovery.log.txt](https://github.com/topjohnwu/Magisk/files/1185757/recovery.log.txt)
[boot.img.zip](https://github.com/topjohnwu/Magisk/files/1185758/boot.img.zip)

**Comment by daniloscala** [comment]
i have this problem in xperia z5 premium
