### ISSUE TITLE
Modules aren't downloading

### ISSUE THREAD

**Issue by unixandria-xda** [topjohnwu/Magisk#3170]
Whenever I try to download a module in Manager, the dialog pops up but when I press download or install, nothing happens. The dialog goes away but nothing else happens.

Logs to follow

**Comment by unixandria-xda** [comment]
[logs-2020-09-11-10-36-04.zip](https://github.com/topjohnwu/Magisk/files/5209652/logs-2020-09-11-10-36-04.zip)

**Comment by topjohnwu** [comment]
Cannot reproduce, and logs have no relevant info
