### ISSUE TITLE
Magisk mount of persist is breaking Bluetooth

### ISSUE THREAD

**Issue by fgl27** [topjohnwu/Magisk#3179]
![Screenshot_20200914-021903_FX](https://user-images.githubusercontent.com/13755892/93046861-5bab3a00-f631-11ea-94ee-d7e716b94cd1.png)

The above file `.bt_nv.bin` is needed to be accessed by Bluetooth services in order to have it working, but because magisk mounts that partition in they mirrors folder the service can see it.

This is only a magisk issue as when I use the magisk uninstaller the persist folder mount on the root and all works.

**So how can I have those persist file visible to bin service?**

**Comment by fgl27** [comment]
The persist folder on the root is empty... The os is android 10 latest version of magisk release or canary cause this.

**Comment by Didgeridoohan** [comment]
Where's the Magisk log (from the Canary release)?

**Comment by fgl27** [comment]
[magisk_log_20200914_175121.log](https://github.com/topjohnwu/Magisk/files/5220912/magisk_log_20200914_175121.log)

BTW you guys should add issues templates. relying on readme is not enough

**Comment by fgl27** [comment]
Some extra info

[logcat.txt](https://github.com/topjohnwu/Magisk/files/5229011/logcat.txt)
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/5229013/dmesg.txt)

This is how a file manager see persist/

![Screenshot_20200915-220658_FX](https://user-images.githubusercontent.com/13755892/93280722-a5fef900-f7a0-11ea-9168-972943a2c6e6.png)

this is how the partition is mounted

```
cat proc/mounts | grep persist                                                                                                                  
/sbin/.magisk/block/persist /sbin/.magisk/mirror/persist ext4 rw,seclabel,relatime,data=ordered 0 0
```

fstab persist line:

`/dev/block/platform/msm_sdcc.1/by-name/persist      /persist    ext4    rw,nosuid,nodev,noatime,barrier=1,defcontext=u:object_r:persist_file:s0   wait,check,notrim`

**Comment by fgl27** [comment]
From the above we can see that is not just Bluetooth that is be affects is all that dependes on those file in /persist that can only access it via te correct path.

**Comment by fgl27** [comment]
The problem is the mnt_flags `defcontext`, also `context` causes problem.

**Can magisk address this issue?**

I can recompile this ROM and address the sepolicy changes but other device may not.

**Comment by topjohnwu** [comment]
@fgl27 thanks for investigating, I will address this after the next release

**Comment by kdnje** [comment]
kdnje:main
