### ISSUE TITLE
Pitfalls with Downgrading from Canary?

### ISSUE THREAD

**Issue by mentalisttraceur** [topjohnwu/Magisk#3182]
If I use the canary release now to patch an Android 11 OTA, and then later once official Magisk releases with Android 11 support come out I uninstall the canary release and use the official one for the next OTA, are there any pitfalls/risks of problems/breakage I should be aware of?

**Comment by osm0sis** [comment]
The new stable will be newer than the Canary at that time, so no. This isn't branched development. 👍
