### ISSUE TITLE
It Doesn't work on asus zenfone 4 ze554kl

### ISSUE THREAD

**Issue by thecheetaw** [topjohnwu/Magisk#3188]
![Screenshot_20200918-124002554](https://user-images.githubusercontent.com/71490396/93573676-ab309380-f9ac-11ea-9a60-2c887c6d1026.png)

**Comment by Mspy1** [comment]
You posted no information which can be helpful in any way.

**Comment by shakalaca** [comment]
version and adb log ?

**Comment by thecheetaw** [comment]
> You posted no information which can be helpful in any way.

Asus zenfone 4 ze554kl 
asus_z01kd
Android version: 9
