### ISSUE TITLE
Moto G5 not installing Magisk 13.3 ERROR1

### ISSUE THREAD

**Issue by Schwiftyyy** [topjohnwu/Magisk#319]
Whenever I try to flash the Magisk 13.3 zip file through TWRP it gives me the same error message.
After completely wiping my phone, and keeping to get the same error message I decided to come here as my last resort, I saved my logs, as you can see bellow.
Thanks in advance for any help you can give me.

[Logs.zip](https://github.com/topjohnwu/Magisk/files/1188598/Logs.zip)

**Comment by WolfezzKyne** [comment]
Same, even with custom roms

**Comment by Schwiftyyy** [comment]
I'm running stock android 7.0

**Comment by Theitfixer85** [comment]
You can flash 11.6 in twrp and then update to 13.3 via magisk manager however the safety net fails on both versions and you get mount /dev/block/loop0->/dev/source failed with 13: permission denied error in logs
