### ISSUE TITLE
Magisk Manager crashes after compilation

### ISSUE THREAD

**Issue by gillus123** [topjohnwu/Magisk#3190]
Hello,
The Magisk Manager from the "releases" works fine on my Pixel 3a (https://github.com/topjohnwu/Magisk/releases)
However the one that I recompiled doesn't work despite Magisk compilation looks fine:

> * Building Magisk Manager stub
> Output: out/stub-release.apk
> 
> * Building Magisk Manager
> Output: out/app-release.apk
> 
> * Building binaries: magisk magiskinit magiskboot busybox
> 
> * Packing Flashable Zip
> 
> * Signing Zip
> Output: out/Magisk-release.zip
> 
> * Packing Uninstaller Zip
> 
> * Signing Zip
> Output: out/Magisk-uninstaller.zip

At least everything look fine in command line (magisk, magiskinit, magiskhide...).
However the Manager crashes right after launching it, you can find the logcat log enclosed. 
BR,
Gil
[logcat_magisk_manager_crash.txt](https://github.com/topjohnwu/Magisk/files/5246632/logcat_magisk_manager_crash.txt)

**Comment by unixandria-xda** [comment]
IDK maybe there's a reason john hasn't built and released the current code even on canary :P

**Comment by gillus123** [comment]
> IDK maybe there's a reason john hasn't built and released the current code even on canary :P

Thanks, I will try to build an earlier source code, I guess the current code of Magisk on canary is compatible with any manager form v20.4

**Comment by varunhardgamer** [comment]
Had the same crash on my compiled "release" magisk, turns out proguard removes NavHostFragment while shrinking for release builds, got it fixed by adding 

`-keepnames class androidx.navigation.fragment.NavHostFragment`

in app/proguard-rules.pro

**Comment by tsynik** [comment]
I also have crashes with release builds from GIT but debug ones work fine ;-)

**Comment by gillus123** [comment]
> Had the same crash on my compiled "release" magisk, turns out proguard removes NavHostFragment while shrinking for release builds, got it fixed by adding
> 
> `-keepnames class androidx.navigation.fragment.NavHostFragment`
> 
> in app/proguard-rules.pro

Thanks, you rock man! It works for me ;)
