### ISSUE TITLE
MagiskHide

### ISSUE THREAD

**Issue by hani4k** [topjohnwu/Magisk#3191]
Hello, I'm using MagiskHide for some apps and it's working fine. But not for all apps. The app still detect that i have root.

Android 11 Pixel 4XL Magisk Canary latest.

**Comment by varunhardgamer** [comment]
> Hello, I'm using MagiskHide for some apps and it's working fine. But not for all apps. The app still detect that i have root.
> 
> Android 11 Pixel 4XL Magisk Canary latest.

https://github.com/topjohnwu/Magisk/issues/1152
