### ISSUE TITLE
Magisk does not handle system/framework mounting properly in some cases

### ISSUE THREAD

**Issue by jsaxon2** [topjohnwu/Magisk#32]
Here is what I have found. I have GPEDialer_HTC10 mod. It adds a file to the system/framework. I've since installed Viper10Rom Magisk Version. It does a .replace on the system/framework directory. If I remove the framework directory from my mod, everything works. If I leave the framework file in my mod, I see that Magisk is then mounting the framework files from Step 5 the mirrored files. This is preventing the ViperMagisk from booting do to using the stock framework files. Let me know what I can get for you.

This is the log that I have removed the framework file from my GPEDialer mod
[frameworkgood.txt](https://github.com/topjohnwu/Magisk/files/680042/frameworkgood.txt)

This is the log that includes viper with the .replace and my mod trying to add a file to framework.
[frameworknoboot.txt](https://github.com/topjohnwu/Magisk/files/680043/frameworknoboot.txt)

If I remove the .replace from the framework directory on the ViperMagisk Rom, I can get it to boot with my mod adding to the framework directory. Only thing is II need to add a framework/arm/.replace  framework/arm64/.replace and framework/oat/.replace so those do not get initialized.

Also, this is on Magisk I compiled on 12/31/16 from github.

**Comment by topjohnwu** [comment]
Thanks for the detailed report, it seems that you have done your researches before opening an issue, which I really appreciate it 💯 .
If a module claims to replace the whole folder, it always have the highest priority.
And yes, the best solution is to slightly modify the Viper Rom Module, which only hides the pre-optimized files, just as you stated.
Not a real Magisk issue so I'll close it now, however really appreciate your report!
