### ISSUE TITLE
Getting Magisk running on Android x86

### ISSUE THREAD

**Issue by lmore377** [topjohnwu/Magisk#3200]
I managed to get Magisk initially installed by packing the ramdisk and kernel together with mkbootimg and patching it with the Magisk app then replacing the original files with the patched ones. To get Magisk to see where the modules are I went into the terminal and made a symlink from /data/adb to /sbin/.magisk/mirror/data/adb which allowed it to see the modules and actually run them. Now I'm just stuck at getting magisk to link system.img to /sbin/.magisk/block/system and as a result the modules can't actually patch anything. Is there a specific script anywhere that handles generating /sbin/.magisk that I can edit or is that just handled by /init?

**Comment by topjohnwu** [comment]
Yes, that is handled by init. The only thing you should do is to replace the rootdir init with `magiskinit`. Please check install scripts to adapt to your needs.
