### ISSUE TITLE
Selinux pollicy loop device bug

### ISSUE THREAD

**Issue by agowa338** [topjohnwu/Magisk#321]
It seams that magisk does not add a selinux pollicy for it's applications linked to the system partition:

```
08-03 01:29:47.046  7999  7999 I sh      : type=1400 audit(0.0:87): avc: denied { getattr } for path="/system/bin/adb" dev="loop0" ino=64 scontext=u:r:shell:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1
08-03 01:29:47.046  7999  7999 I sh      : type=1400 audit(0.0:88): avc: denied { execute } for name="adb" dev="loop0" ino=64 scontext=u:r:shell:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1
08-03 01:29:47.046  8159  8159 I sh      : type=1400 audit(0.0:89): avc: denied { read open } for path="/system/bin/adb" dev="loop0" ino=64 scontext=u:r:shell:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1
08-03 01:29:47.056  8159  8159 I sh      : type=1400 audit(0.0:90): avc: denied { execute_no_trans } for path="/system/bin/adb" dev="loop0" ino=64 scontext=u:r:shell:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1
```
When selinux is set to permissive the applications can be started, with it turned on they are blocked.
It's always dev="loop0" that is denied.

At least these modules are affected:
- ADB & Fastboot for Android NDK
- Nano for Android NDK
- Busybox for Android NDK

I'm using the latest version of Magisk on a newly flashed stock rom (just reflashed the latest stock rom, **but without** wiping /data).
My device is a OnePlus 3T.

**Comment by Didgeridoohan** [comment]
None of those modules you mention use the module template. Could that be the reason? @osm0sis

**Comment by Didgeridoohan** [comment]
I just tested both Busybox and Nano on my OnePlus 3T (OOS 4.1.6, Franco Kernel r25, Magisk v13.3) and they work just fine with SELinux set to enforcing.

**Comment by osm0sis** [comment]
Stock ROM is more restrictive. I didn't set a context at install, and I'll fix that in my next release, but Magisk should also set one at link time like SuperSU.

**Comment by osm0sis** [comment]
@topjohnwu, shouldn't Magisk run a restorecon on all the merged paths during boot?

**Comment by topjohnwu** [comment]
@osm0sis it can't: the context of the files are set at installation, a restorecon will cause all of them be set to `u:r:system_file:s0`, which obviously will break many stuffs :)

**Comment by osm0sis** [comment]
Gotcha, I'll fix that on my side. Odd that it doesn't effect everyone, and that it's fine on SuperSU.
