### ISSUE TITLE
unable to update magisk on Samsung Tab E

### ISSUE THREAD

**Issue by lemmy04** [topjohnwu/Magisk#3211]
I have a Samsung Tab E lying around, then I try to update magisk to 20.4 (direct install) it fails.
Logfile says:

```
- Target image: /dev/block/mmcblk0p20
- Device platform: armeabi-v7a
2034+0 records in
2034+0 records out
2082816 bytes (2.0MB) copied, 0.058075 seconds, 34.2MB/s
1410+1 records in
1410+1 records out
1443916 bytes (1.4MB) copied, 0.045654 seconds, 30.2MB/s
boot_patch.sh: line 61: chmod: Permission denied
boot_patch.sh: line 64: ./magiskinit: Permission denied
- Unpacking boot image
boot_patch.sh: line 73: ./magiskboot: Permission denied
- Checking ramdisk status
- Stock boot image detected
boot_patch.sh: line 104: cat: Permission denied
- Patching ramdisk
boot_patch.sh: line 136: ./magiskboot: Permission denied
boot_patch.sh: line 148: rm: Permission denied
- Repacking boot image
boot_patch.sh: line 181: ./magiskboot: Permission denied
boot_patch.sh: line 51: rm: Permission denied
boot_patch.sh: line 52: rm: Permission denied
! Unable to repack boot image!
! Installation failed


Any ideas?
```

**Comment by osm0sis** [comment]
Fixed in Canary already. Don't report issues for stable. 🙄

**Comment by lemmy04** [comment]
and how am I supposed to update to the fixed version when updating doesn't work?

**Comment by osm0sis** [comment]
Download and install the Canary Manager, like always.

**Comment by mu198** [comment]
1. Restore Magisk Manager 
2. Install the new canary manager 
3. Update the system 
4. Hide the new magisk

**Comment by lemmy04** [comment]
>     1. Restore Magisk Manager
> 
>     2. Install the new canary manager
> 
>     3. Update the system
> 
>     4. Hide the new magisk

with restore you mean unhide, right? and where do i get that canary manager?

**Comment by mu198** [comment]
https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/app-debug.apk


And yes, That's what I mean

**Comment by lemmy04** [comment]
ok, so here's what I tried:

1. restore magisk manager
2. switch the installation source to the json file from https://forum.xda-developers.com/showpost.php?s=a0e16b14ee4d567de810af09382b1de8&p=83064771&postcount=4
3. update magisk manager to the version from canary
4. got offered a magisk update from canary
... and installing that failed exactly the same way. so, *not* fixed.
Please reopen.

**Comment by mu198** [comment]
Have you changed the update channel??? 
![Screenshot_20200927-225633](https://user-images.githubusercontent.com/65677888/94375555-cfab0f00-0114-11eb-8a35-4157662583fe.jpg)

**Comment by lemmy04** [comment]
i **had** it set to the caray channel but as custom url. Changed it to canary the "normal" way now, same thing - direct install, fails with the same permission errors. So .. *not* "fixed in canary" yet.
Please reopen.

**Comment by osm0sis** [comment]
I still doubt your method, since setting the channel line you suggest doesn't work.

See here for the exact same issue, which was in fact fixed: https://github.com/topjohnwu/Magisk/issues/2609

**Comment by lemmy04** [comment]
I wish someone would remove the "closed invalid" from this - or do I open a new one? I'm still having the same problem even with the official magisk manager 8.0.0 release. Also, Manager 8.0.0 doesn't show Magisk 21.0 as available on my Tab E...
