### ISSUE TITLE
Magisk Hide is causing memory leakage

### ISSUE THREAD

**Issue by KevinMX** [topjohnwu/Magisk#3214]
Phone Model: Sony Xperia XZ2 Compact / H8324

OS:Android 10 / 52.1.A.3.49, I'm on a custom kernel from [sjlls](https://github.com/sjllls/android_kernel_sony_sdm845) but the official stock kernel also have this problem, so I think there's nothing to do with the kernel.

Magisk Version: 20.4, I've tested on both stable and canary(compiled it myself on my laptop) and I can replicate the issue.

Enabling Magisk Hide to an app will cause a memory leakage,

 and on my 4GB RAM this will lead to OOM and the whole system will not respond, including adb. I tried Tencent TIM & Alipay & Taobao, which can cause OOM. And, if Magisk Hide is enabled for com.google.android.gms.unstable by default, which is also leaking memory on my device, I saw abnormal memory usage on my device (using the app Scene), for com.google.android.gms.unstable itself it comsumes up to 1.5~2GiB and then the system freezes. Even if it did not freeze it's extremely slow due to low memory.

Disable all modules does not help, sadly.

Some adb logs/dmesg as follows. If more information is needed please tell me.
[magisk.log](https://github.com/topjohnwu/Magisk/files/5289544/magisk.log)
[oom-dmesg.log](https://github.com/topjohnwu/Magisk/files/5289545/oom-dmesg.log)
[oom-adb.log](https://github.com/topjohnwu/Magisk/files/5289546/oom-adb.log)

**Comment by osm0sis** [comment]
Try with v21 Public Beta and give new logs please.

**Comment by KevinMX** [comment]
> Try with v21 Public Beta and give new logs please.

I'm on my way :)
BTW I'm on Magisk Lite now, which has no issues at all... I'll give the latest beta without any modules a shot...

**Comment by osm0sis** [comment]
Where's Magisk Lite? Sounds like some unofficial short.

**Comment by KevinMX** [comment]
> Where's Magisk Lite? Sounds like some unofficial fork.

Yeah it is an unofficial fork. See: https://github.com/vvb2060/Magisk/tree/liteThis fork disables module support entirely, and it uses whitelist mode, su is only avaliable for selected apps. I'm still troubleshooting if it is really my modules causing the issue, but last time I tried disabling all modules it did not help.

**Comment by KevinMX** [comment]
Seems I've got something. It's the QuickSwitch module. I'm looking at previous issues about QS and see if I have any luck...

**Comment by KevinMX** [comment]
Seems I'm gonna give up QS for now, I'll try the legacy Lawnstep... Closing issue for now.
