### ISSUE TITLE
Banking app and Magick Hide

### ISSUE THREAD

**Issue by awaregit** [topjohnwu/Magisk#3218]
Friend of mine can use succesfully Magick Hide for banking app "my Alpha Wallet" but not me.
We have same model of Samsung Galaxy Note 8 (SM-N950F), we both run Android 9 and we both have same version Magisk and Magisk Manager.
Any ideas what to look for?

Thank you indeed

**Comment by yukosky** [comment]
Did you hide the magisk manager too?

**Comment by yukosky** [comment]
F

**Comment by awaregit** [comment]
I treid this too. No solution.

**Comment by awaregit** [comment]
Let's say I wish to flash earlier version (17.2) while now I have 20.4. Will this lead to data loss?

**Comment by awaregit** [comment]
So here is a weird situation:
After uninstalling magisk manager app then a series of things took place:
1. My banking app now works ok 
2. Root checker says root not properly applied
3. All apps that need root to work (TitaniumBk, Adaway, CallRecorder) see device as rooted and work flawlessly.
In other words, as like magic everythinf works fantastic!
Problem/Question/Worry: What will happen after I reboot?

Any ideas please?
Thank you very much!
