### ISSUE TITLE
Magisk Manager says unsupported version 

### ISSUE THREAD

**Issue by reverseflash2** [topjohnwu/Magisk#3221]
In android 11 phh gsi after I install magisk canary when I open magisk manager canary it says unsupported version of magisk the app will pretend you do not have root.

**Comment by mu198** [comment]
have you switched from stable to canary manager?

If so, you need to restore the stable Magisk Manager and then install Canary.

**Comment by reverseflash2** [comment]
I tried stable magisk manager and canary and both said the same thing

P.s. this is on roar from phh
