### ISSUE TITLE
unsupported image format

### ISSUE THREAD

**Issue by LEENO82** [topjohnwu/Magisk#3223]
Hallo, i dumped Lg Q850 firmware Android 8.1.0 via jtag

trying to patch both
**boot_a.img** 
and 
**boot_b.img**
magisk give error:
**unsupported/unknown image format**

i uploaded here boot_a.img and boot_b.img
http://www.mediafire.com/file/fgy1bwpn6a4keuq/LG_Q850_-__BOOT.IMG_-_LinuxFalco_Dump.rar/file

Dump flashed back and phone is working so dump is good.

is possible to patch it for obtain root?

inform me if i have to upload any of following dumped partition:

drwxr-xr-x 2 root root 1460 2018-01-01 00:00:06.239999999 +0000 .
drwxr-xr-x 4 root root 1640 2018-01-01 00:00:06.239999999 +0000 ..
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.159999999 +0000 OP_a -> /dev/block/sda22
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.189999999 +0000 OP_b -> /dev/block/sda23
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.169999999 +0000 aboot_a -> /dev/block/sde3
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.169999999 +0000 aboot_b -> /dev/block/sde4
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.229999999 +0000 akmu_a -> /dev/block/sde29
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.179999999 +0000 akmu_b -> /dev/block/sde30
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.199999999 +0000 apdp -> /dev/block/sde31
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.219999999 +0000 boot_a -> /dev/block/sde17
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.169999999 +0000 boot_b -> /dev/block/sde18
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.139999999 +0000 carrier -> /dev/block/sda12
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.149999999 +0000 cdt -> /dev/block/sdd3
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.229999999 +0000 cmnlib64_a -> /dev/block/sde25
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.169999999 +0000 cmnlib64_b -> /dev/block/sde26
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.189999999 +0000 cmnlib_a -> /dev/block/sde23
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.189999999 +0000 cmnlib_b -> /dev/block/sde24
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.159999999 +0000 ddr -> /dev/block/sdd1
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.219999999 +0000 devcfg_a -> /dev/block/sde13
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.169999999 +0000 devcfg_b -> /dev/block/sde14
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.209999999 +0000 devinfo -> /dev/block/sde36
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.209999999 +0000 dip -> /dev/block/sde35
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.179999999 +0000 dpo -> /dev/block/sde34
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.129999999 +0000 drm -> /dev/block/sda2
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.139999999 +0000 eksst -> /dev/block/sda10
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.129999999 +0000 els -> /dev/block/sda4
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.139999999 +0000 encrypt -> /dev/block/sda9
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.169999999 +0000 fota -> /dev/block/sda11
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.189999999 +0000 fsc -> /dev/block/sdf4
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.239999999 +0000 fsg -> /dev/block/sdf3
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.149999999 +0000 ftm -> /dev/block/sda13
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.159999999 +0000 grow -> /dev/block/sda25
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.209999999 +0000 hyp_a -> /dev/block/sde9
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.159999999 +0000 hyp_b -> /dev/block/sde10
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.219999999 +0000 keymaster_a -> /dev/block/sde21
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.169999999 +0000 keymaster_b -> /dev/block/sde22
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.129999999 +0000 keystore -> /dev/block/sda8
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.189999999 +0000 laf_a -> /dev/block/sde19
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.189999999 +0000 laf_b -> /dev/block/sde20
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.139999999 +0000 misc -> /dev/block/sda6
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.179999999 +0000 modem_a -> /dev/block/sde15
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.179999999 +0000 modem_b -> /dev/block/sde16
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.209999999 +0000 modemst1 -> /dev/block/sdf1
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.209999999 +0000 modemst2 -> /dev/block/sdf2
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.129999999 +0000 mpt -> /dev/block/sda1
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.199999999 +0000 msadp -> /dev/block/sde32
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.139999999 +0000 oem_a -> /dev/block/sda16
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.149999999 +0000 oem_b -> /dev/block/sda17
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.169999999 +0000 persist -> /dev/block/sda15
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.239999999 +0000 persistent -> /dev/block/sdg1
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.179999999 +0000 pmic_a -> /dev/block/sde11
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.179999999 +0000 pmic_b -> /dev/block/sde12
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.139999999 +0000 power -> /dev/block/sda5
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.209999999 +0000 raw_resources_a -> /dev/block/sde5
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.159999999 +0000 raw_resources_b -> /dev/block/sde6
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.149999999 +0000 rct -> /dev/block/sda14
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.189999999 +0000 reserve -> /dev/block/sdd2
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.179999999 +0000 rpm_a -> /dev/block/sde7
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.169999999 +0000 rpm_b -> /dev/block/sde8
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.229999999 +0000 sec -> /dev/block/sde33
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.199999999 +0000 sid_a -> /dev/block/sde27
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.199999999 +0000 sid_b -> /dev/block/sde28
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.149999999 +0000 sns -> /dev/block/sda3
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.149999999 +0000 ssd -> /dev/block/sda7
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.139999999 +0000 system_a -> /dev/block/sda20
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.159999999 +0000 system_b -> /dev/block/sda21
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.209999999 +0000 tz_a -> /dev/block/sde1
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.159999999 +0000 tz_b -> /dev/block/sde2
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.149999999 +0000 userdata -> /dev/block/sda24
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:05.599999999 +0000 vendor_a -> /dev/block/sda18
lrwxrwxrwx 1 root root   16 2018-01-01 00:00:06.169999999 +0000 vendor_b -> /dev/block/sda19
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.149999999 +0000 xbl_a -> /dev/block/sdb1
lrwxrwxrwx 1 root root   15 2018-01-01 00:00:06.189999999 +0000 xbl_b -> /dev/block/sdc1
falcon:/dev/block/bootdevice/by-name $

**Comment by osm0sis** [comment]
The error is correct. Those are an unsupported/unknown image format. Either your jtag dump is faulty or the device is encrypting the images.

You'll know you've got normal images when they have "ANDROID!" somewhere in them near the beginning in a hex editor.

**Comment by LEENO82** [comment]
i will try to get kernel in different ways.

Kernel is only in boot_a.img? Or need boot_b.img too?

**Comment by osm0sis** [comment]
They are the kernel for the _a slot and the _b slot..
