### ISSUE TITLE
Intermittent Issue with command backgrounding using /sbin/su

### ISSUE THREAD

**Issue by seffparker** [topjohnwu/Magisk#3224]
## What is the issue?
When a target command is invoked via Magisk `su` bin with `-c` option, and with backgrounding using the `&` symbol, the command does not execute (most of the times).

## When works, when doesn't?
 - Works when the target command is not backgrounded, with SH or BASH shells:
```
termux@batmobile ~ $ /sbin/su -s /data/bin/bash -c 'id'
uid=0(root) gid=0(root) groups=0(root)

termux@batmobile ~ $ /sbin/su -s /system/bin/sh -c 'id'
uid=0(root) gid=0(root) groups=0(root)

root@batmobile root # /sbin/su -s /data/bin/bash -c 'id'
uid=0(root) gid=0(root) context=u:r:magisk:s0
```
 - Works when directly executed in shell with background mode:
```
root@batmobile root # id &
[1] 21008
root@batmobile root # uid=0(root) gid=0(root) context=u:r:magisk:s0

[1]+  Done                    id
```
 - Does NOT works when invoked as background mode
```
termux@batmobile ~ $ /sbin/su -s /system/bin/sh -c 'id &'

termux@batmobile ~ $ /sbin/su -s /data/bin/bash -c 'id &'

root@batmobile root # /sbin/su -s /data/bin/bash -c 'id &'
```

## What are tried, but doesn't help
 - Tested in termux fail-safe mode
 - Tired reflashing the full ROM
 - Tried reflashing the Magisk ZIp

## Why this bug concerns
I have daemon BASH scripts running as root, which is controlled via termux-notification buttons. Here, we need to use privilege escalations to properly communicate with the process that owned by root. This a the suggested method by @xeffyr
See https://github.com/termux/termux-api/issues/347

When the bash script has any commands with background mode, i.e, with the `&` symbol, the parts of the script does not executes when called as a termux-notification button action.

## Environment
 - Terminal: Termux v0.101
 - Magisk 20.4
 - Magisk Manager 7.5.1
 - Device: POCO F1 Global
 - ROM: MIUI 11.0.5 Stable
 - Android 9

**Comment by seffparker** [comment]
I have implemented a work-around by using `start-stop-daemon` to run the command in background instead of `&` method.

**Comment by osm0sis** [comment]
Try with latest Public Beta build please.

**Comment by zgfg** [comment]
My screenshots with Magisk Canary 21001, from Termux (black terminal) and NetHunter (blue terminal)

Cases for
su -c 'id &'
marked by green (ok) and red rectangles (nok)

su sessions marked by yellow ellipses on top

IMO, three cases ok, one nok (all reproducible), IDK if it's (all) up to Magisk
![IMG_20201005_154640](https://user-images.githubusercontent.com/51943147/95088952-dc86be80-0723-11eb-8bdf-e6301dc35a47.jpg)
![IMG_20201005_154952](https://user-images.githubusercontent.com/51943147/95088980-e6a8bd00-0723-11eb-9196-01b3876c1028.jpg)
![IMG_20201005_154111](https://user-images.githubusercontent.com/51943147/95089017-f1fbe880-0723-11eb-891e-0cff5e88ac47.jpg)
![IMG_20201005_154401](https://user-images.githubusercontent.com/51943147/95089054-faecba00-0723-11eb-86c7-baa8c7e7660c.jpg)

**Comment by seffparker** [comment]
Thanks @osm0sis for further investigating this bug. Since it is reproducible on different terminals, the issue must be with the Magisk SU.

**Comment by seffparker** [comment]
### What are tried, but doesn't help (Update 1#)
 - Tried all three mount-namespace options in Magisk Manager
 - Tried resetting the `/data/adb/Magisk.db`

**Comment by topjohnwu** [comment]
After further investigation, this is caused by the fact that the root shell is actually a remote shell.
So not a regression, but I'll see what I can do to make this work like it should

**Comment by evelbodevil** [comment]
Any update on this issue?  Not able to us in adb shell

**Comment by osm0sis** [comment]
@evelbodevil that's completely different from this issue

**Comment by seffparker** [comment]
The original issue still exists in the version 22

**Comment by seffparker** [comment]
Still present in Magisk 22.1

**Comment by patpolster** [comment]
#

**Comment by yujincheng08** [comment]
I believe this is expected:

```
sh -c 'id &'
```

does not produce output as well.

The problem is that you are launching a new shell process (like `sh -c`), and the shell runs some commands you provide. And if the command is running background, and the shell exits without waiting for that command, then a HUP signal will kill the command.

Either the following ways should work:

```
su -c 'id &
wait'
```
or
```
su -c 'id' &
```
or
```
su -c 'nohup id &'
```
