### ISSUE TITLE
[21.0] Magisk, "installed: N/A" through a patched boot.img

### ISSUE THREAD

**Issue by Akitakek** [topjohnwu/Magisk#3228]
- Got the new Magisk Manager (8.0.0), made it Beta branch (because by default it still says Manager 7.5.1 and Magisk 20.4 are latest)
- Clicked "Install", Selected my (stock) rom's boot.img for patching.
- Copied magisk_patched.img (which was around 65mb compared to the ~10mb it was with 20.4 btw) to desktop
- Rebooted to fastboot mode and:

1. fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
2. fastboot erase cache
3. fastboot flash boot magisk_patched.img
4. fastboot reboot

Now Magisk Manager says Installed: N/A.
Not sure if it's the Manager not properly detecting that Magisk is present, or Magisk that isn't installed properly.
This installation method worked fine with 20.4

Phone: Redmi Note 9 (Merlin)
Android: 10
MIUI: 12.0.3

If you need anything else, let me know.
For now, I will roll back to the previous versions of both the Manager and Magisk itself.

**Comment by Alpamayo57** [comment]
Same here. 
I tried them both, Magisk 64effe93 (21001) Canary version and Magisk 21.0. I flashed them with fastboot. No joy. Still Magisk Manager says N/A.

Phone: Oukitel WP5-PRO
Android 10
A/B = No
SAR = Yes
Ramdisk = Yes

I attached the log of the Canary installation and my zipped boot.img

[magisk_install_log_2020-10-03T14_36_23Z.log](https://github.com/topjohnwu/Magisk/files/5321648/magisk_install_log_2020-10-03T14_36_23Z.log)

[boot.zip](https://github.com/topjohnwu/Magisk/files/5321651/boot.zip)

**Comment by TooYoungTooSimp** [comment]
Same here, but I'm using MIUI12 over Android 11. (K30 5G)

**Comment by ryaniskira** [comment]
Are these A/B devices? If so I would argue that Magisk isn't installed at all, in fact I don't think it's actually Android 11 compatible and on A/B devices if one slot fails to boot it will revert to the previous slot. This is the behavior I am seeing on my Pixel 4 XL. If I flash the magisk patched image to both slots (thus giving it no fallback) It fails with "No valid slots to boot"

**Comment by ryaniskira** [comment]
Are these A/B devices? If so I would argue Magisk isn't installed at all, I think something's broken with Magisk 21 and on A/B if one slot fails to boot it'll revert to the other slot. On my Pixel 4 XL attempting to flash Magisk 21 causes it to swap slots, and upon boot Magisk Manager reports N/A for me too.

**Comment by topjohnwu** [comment]
From @abdoi94:

running canary 
[console-ramoops-0-magisk-21001-bootloop.txt](https://github.com/topjohnwu/Magisk/files/5321778/console-ramoops-0-magisk-21001-bootloop.txt)

**Comment by X1nto** [comment]
> Are these A/B devices? If so I would argue Magisk isn't installed at all, I think something's broken with Magisk 21 and on A/B if one slot fails to boot it'll revert to the other slot. On my Pixel 4 XL attempting to flash Magisk 21 causes it to swap slots, and upon boot Magisk Manager reports N/A for me too.

Happens on MTK devices only, both my phone (redmi 9) and tablet (Fire HD 8) say magisk isn't installed after flashing a patched image, while my old HTC One M8 has no problems whatsoever. Noticed this on Canary but didn't have any time to report, I'm suspecting a [recent commit](https://github.com/topjohnwu/Magisk/commit/c91ebfbcc118be728c7ecfbcc593cecb9b975619) but yet, I could be wrong

**Comment by kidonng** [comment]
> Happens on MTK devices only

According to @TooYoungTooSimp this happens on Qualcomm devices too.

**Comment by X1nto** [comment]
> > Happens on MTK devices only
> 
> According to @TooYoungTooSimp this happens on Qualcomm devices too.

Oops, missed that

**Comment by jfcherng** [comment]
I have the same setup with @TooYoungTooSimp's and failed to install v21 too.

- Mobile: Redmi K30 5G (Qualcomm 765G)
- ROM: `xiaomi.eu_multi_HMK305G_20.9.24_v12-11.zip` (MIUI 12 / Android 11)

---

Some people who use `Redmi K30 Pro` (MIUI 12 / Android 11) reported that they are fine with v21 though.

**Comment by Akitakek** [comment]
About the [commit](https://github.com/topjohnwu/Magisk/commit/c91ebfbcc118be728c7ecfbcc593cecb9b975619), I think it could indeed be the culprit. The magisk_patched.img is actually _larger_ than the stock Boot image, which could be causing issues if the partition it's flashed to isn't big enough?

**Comment by X1nto** [comment]
> About the [commit](https://github.com/topjohnwu/Magisk/commit/c91ebfbcc118be728c7ecfbcc593cecb9b975619), I think it could indeed be the culprit. The magisk_patched.img is actually _larger_ than the stock boot.img, which could be causing issues if the partition it's flashed to isn't big enough?
> 
> Just speculation though.

Not sure about your device but with mine, patched image actually matched stock boot image size, the reason I think that commit is the issue, is because of how directly it's involved in the patched image output, if someone could get a canary build that doesn't contain that commit, we could test if that's the issue

**Comment by jfcherng** [comment]
@TooYoungTooSimp You may try [this](https://github.com/topjohnwu/magisk_files/commit/8c12e3f5efd6687c4888d524a9e562880b8360c1) canary build which works for my K30 5G (MIUI 12 / Android 11).

@X1nto @Akitakek Maybe you guys can give the above build a try?

**Comment by topjohnwu** [comment]
> About the [commit](https://github.com/topjohnwu/Magisk/commit/c91ebfbcc118be728c7ecfbcc593cecb9b975619), I think it could indeed be the culprit. The magisk_patched.img is actually _larger_ than the stock boot.img, which could be causing issues if the partition it's flashed to isn't big enough?
> 
> Just speculation though.

No its not. It is literally just adding zeros in the boot image to match the original image size...

**Comment by osm0sis** [comment]
Sounds like 2SI/SAR detection being finicky again, as with #2994

**Comment by mrmazakblu** [comment]
Its been happening on My MTK A10 device since release. Tried each build from 17- 21 always shows not installed. And logcat has not a single line about magisk.init. Just couple lines about package manager and the magisk apk.

as to the size of the boot.img. My stock img is around 30md, and the patched img is close to 10mb. do not think oversized image is the issue

**Comment by mayulu** [comment]
Same here, but I succeeded updating Manager8.0.0(302) and Magisk 21.0(21000), it worked. After installing a module(miracast), it bootlooped. So I did the fastboot flash factory phone image and reinstall Magisk. It bootlooped again, and I did the fastboot flash factory phone image again. Magisk now shows "current:n/a".
My Phone is Pixel 4XL(Coral), Android 11.
[magisk_install_log_2020-10-04T06_22_02Z.log.txt](https://github.com/topjohnwu/Magisk/files/5324892/magisk_install_log_2020-10-04T06_22_02Z.log.txt)

**Comment by jerryliang122** [comment]
I patched a boot.img, after trying to install, magisk prompts N/A。My device is Xiaomi 10 lite, Qualcomm 765G。Android 11/ MIUI12.This is the log of logcat dmesg, and the boot of the original factory boot and 21001/303magisk patch I used https://homekd.jerryliang.top/#s/6RqPwW1g

**Comment by jakiki6** [comment]
Same for Pixel 3a with a bootloop. It switches slots.

**Comment by DrinkTaiTea** [comment]
I tried updating from 20.4 to Magisk 21.0 and the latest Magisk Manager 8. 0.0 (302) (11). My phone is the Huawei Mate 9 with HiSilicon Kirin 960 chipset. My install also said N/A and appeared to not be rooted. Methods attempted in order:
1: Installed Magisk Manager 8.0.0 from within Magisk Manager. - Worked
2: Direct install method within Magisk Manager to 21.0. - Appeared successful but no root and given N/A for install status.
3: Zip install through TWRP. Install appeared successful but same results as above.
4: Zip install of the previous version 20.4 that I had installed while maintaining the new Manager version 8.0.0. - Successful and functionality is restored as before.

The new Magisk Manager is working fine. Magisk itself is not.

**Comment by TooYoungTooSimp** [comment]
another thing is that some user can't install magisk via twrp 'thanks to' dynamic partition. I have no twrp to use so I can only do a direct install.

**Comment by X1nto** [comment]
> another thing is that some user can't install magisk via twrp 'thanks to' dynamic partition. I have no twrp to use so I can only do a direct install.

This is why I use fastboot to flash magisk, supporting flashing via twrp is a pain in the ass

**Comment by TooYoungTooSimp** [comment]
> > another thing is that some user can't install magisk via twrp 'thanks to' dynamic partition. I have no twrp to use so I can only do a direct install.
> 
> This is why I use fastboot to flash magisk, supporting flashing via twrp is a pain in the ass

patch boot image and flash it？ I believe it is the same as direct install. Or any other ways?

**Comment by DrinkTaiTea** [comment]
> > > another thing is that some user can't install magisk via twrp 'thanks to' dynamic partition. I have no twrp to use so I can only do a direct install.
> > 
> > 
> > This is why I use fastboot to flash magisk, supporting flashing via twrp is a pain in the ass
> 
> patch boot image and flash it？ I believe it is the same as direct install. Or any other ways?

I believe it is the same as direct install. The difference is you can choose any boot image to patch, so it gives more leeway.

**Comment by Akitakek** [comment]
I re-patched 20.4 without an issue. And am now using Manager 8.0.0 as well, works fine.

**Comment by TooYoungTooSimp** [comment]
as for me, neither 20.4 nor 21 works. (All direct install)

**Comment by Akitakek** [comment]
WE ARE NOT talking about direct install here, but about patching a boot.img and flashing it with fastboot.
Please stay on topic and create or add to the proper issue.

**Comment by jerryliang122** [comment]
> **WE ARE NOT** talking about direct install here, but about patching a boot.img and flashing it with fastboot.
> Please stay on topic and create or add to the proper issue.

Yes I know, but I have tried both methods here。PATCH and  direct install

**Comment by topjohnwu** [comment]
Can people test out the latest canary build and see if it fixes the issue?

**Comment by X1nto** [comment]
Already patching

**Comment by X1nto** [comment]
Nope, still shows N/A on 04995881 build. I would get installation logs but I'm not sure how 😅

**Comment by jerryliang122** [comment]
> Nope, still shows N/A on [0499588](https://github.com/topjohnwu/Magisk/commit/049958810731f070308adc4dfb85fb938b3a374c) build. I would get installation logs but I'm not sure how 😅

It works on Qualcomm 765G

**Comment by mrmazakblu** [comment]
Still not getting magisk init to start. On Either of my devices. 
Both mtk, both released on A-10

logcat shows only references to 'magisk' are the apk and surfaceflinger.

logcat clips with grep "magisk"  then grep "init"
https://del.dog/norylepanu

**Comment by Alpamayo57** [comment]
Nope. It shows  N/A on 04995881 (21002) (and MM d4d837a5 (308) )

Phone: Oukitel WP5-PRO_EEA_V03_20200723
Baseband version: MOLY.LR12A.R3.MP.V114.9
kernel = 4.9.190+
Android 10
A/B = No
SAR = Yes
Ramdisk = Yes

[magisk_install_log_2020-10-08T12_54_03Z.log](https://github.com/topjohnwu/Magisk/files/5347333/magisk_install_log_2020-10-08T12_54_03Z.log)

**Comment by TooYoungTooSimp** [comment]
> Can people test out the latest canary build and see if it fixes the issue?

k30 5g （sd765g） 21002 fix confirmed. really thanks for your work.

**Comment by abdoi94** [comment]
21002 still goes stragiht to fastboot for me, tried patching image and flashing with twrp

[console-ramoops-0-21002-raphael-a11.txt](https://github.com/topjohnwu/Magisk/files/5347873/console-ramoops-0-21002-raphael-a11.txt)

**Comment by squabbi** [comment]
Canary build 04995881 (21002) now shows Magisk installed on my Pixel 3 on Android 11, where v21.0 did not before.

**Comment by Alpamayo57** [comment]
Still no progress with MM (310) (12) and M (21004). No root for my Android 10

Phone: Oukitel WP5-PRO_EEA_V03_20200723
Baseband version: MOLY.LR12A.R3.MP.V114.9
kernel = 4.9.190+
Android 10
A/B = No
SAR = Yes
Ramdisk = Yes

**Comment by JoelJoos** [comment]
+1 on an OP8 Pro / Qualcomm device, can't get it working, either bootloop or installed N/A

**Comment by shmshd** [comment]
@squabbi could you tell me where did you download Canary? I searched for the Canary and could not find it anywhere.

**Comment by Keloku** [comment]
Phone: ONN Surf 10
Model:100003562
kernel = 4.9.190
Android 10
A/B = No
SAR = Yes
Ramdisk = Yes

I patch the boot img with magisk, flash to patched, boot is fine and manager states N/A.

**Comment by shmshd** [comment]
Canary build ```21004``` works fine without any issue in Pixel 4 XL running Android 11 ```RP1A.201005.004```.

**Comment by Alpamayo57** [comment]
Still it reports N/D with MM (311) (13) and M (21005). No root for my Android 10 device.

Phone: Oukitel WP5-PRO_EEA_V03_20200723
Baseband version: MOLY.LR12A.R3.MP.V114.9
kernel = 4.9.190+
Android 10
A/B = No
SAR = Yes
Crypto = File
Ramdisk = Yes

[magisk_install_log_2020-10-17T14_10_18Z.log](https://github.com/topjohnwu/Magisk/files/5395607/magisk_install_log_2020-10-17T14_10_18Z.log)

**Comment by topjohnwu** [comment]
#3024

**Comment by kidonng** [comment]
@topjohnwu maybe you are referring to #3042?

**Comment by infinixs5lite** [comment]
> > Can people test out the latest canary build and see if it fixes the issue?
> 
> k30 5g （sd765g） 21002 fix confirmed. really thanks for your work.

How do did u do it?

**Comment by haywirephoenix** [comment]
I'm currently experiencing this issue.

1. Clean install. 
2. Boot.img patched sucessfully, tried flashing through TWRP and Odin.
3. Wipe again.
4. Magisk listed in applications
5. SU is working, can get prompt
6. Installed: N/A | Ramdisk: Yes | A/B: No | SAR: No

Galaxy J5 SM-J500FN
Magisk 23.0
Android 6.0.1
(old I know!)

post boot log:

[logcat.txt](https://github.com/topjohnwu/Magisk/files/7137384/logcat.txt)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/7137385/dmesg.log)

**Comment by Felixkfantastic** [comment]
i need help with my infinix hot 5 aftr patching the img file it jst says all done

**Comment by KatayR** [comment]
Same problem here

**Comment by Omar2014isa** [comment]
Same for huawei p30 lite
Emui 12.0.1

**Comment by fadelhimawan879-hash** [comment]
Kaya gima
