### ISSUE TITLE
v13.3, Honor 7 : Rescue mode after installation

### ISSUE THREAD

**Issue by woolx** [topjohnwu/Magisk#323]
I have installed 13.3 successfully but when i reboot, the rescue mode appears with this error :

> Error!
> Func NO : 10 (boot image)
> Error NO : 2 (load failed)

12.0 worked perfectly
Honor 7 B370
Stock OS
Fresh installation

recovery log : https://pastebin.com/4rNYBTc7

Boot after installation:
[magisk-boot.zip](https://github.com/topjohnwu/Magisk/files/1199823/magisk-boot.zip)

Stock boot:
[stock-boot.img.zip](https://github.com/topjohnwu/Magisk/files/1199822/stock-boot.img.zip)

**Comment by woolx** [comment]
Works fine with B390.

**Comment by flowgunso** [comment]
Having the same issue. With Magisk 13.3 and a custom rom (r7 modaco) equivalent to B370.
