### ISSUE TITLE
Magisk manager fails to open

### ISSUE THREAD

**Issue by stashymane** [topjohnwu/Magisk#3230]
Just installed the v21 zip. Running AOSiP 10 12th September release (android 10)
Cleared storage, still persists.
Unable to start activity ComponentInfo{com.IRRxnoW.yncW7dBM/a.B}: android.view.InflateException: Binary XML file line #142 in com.topjohnwu.magisk:layout/0_resource_name_obfuscated: Binary XML file line #142 in com.topjohnwu.magisk:layout/0_resource_name_obfuscated: Error inflating class Button

Full log attached.
[logcat.txt](https://github.com/topjohnwu/Magisk/files/5321728/logcat.txt)

**Comment by topjohnwu** [comment]
Have you tried to not hide Magisk Manager?
Also, bug reports should use the canary channel so I can get debug stack traces

**Comment by stashymane** [comment]
Canary works fine - tried uninstalling manager & reflashing zip, doesn't crash anymore, even when hidden. Was a bit weird as I've never had issues upgrading by merely flashing again.
