### ISSUE TITLE
Samsung Galaxy A20s(SM-A207F) doesn't boot after flashing patched AP using Magisk 21(MM 8).

### ISSUE THREAD

**Issue by soum91** [topjohnwu/Magisk#3231]
Nothing has changed. I was really really excited about the new release but got immeasurably disappointed. It is just the same as it has been for like 1 year. It still gives bootloop and get stuck with **SECURE CHECK FAIL: boot.img**.  John Wu's tweets and magisk changelog seemed promising but it's still ALL THE SAME. It still doesn't work!
<img width="419" alt="Screen Shot 2020-10-03 at 7 04 58 PM" src="https://user-images.githubusercontent.com/3830681/94992369-619a9800-05ab-11eb-8994-1d43974ee42a.png">

**Comment by yukosky** [comment]
Close that, it's A20s issue.

**Comment by yukosky** [comment]
And magisk is fine, blame Samsung

**Comment by soum91** [comment]
@yukosky do you know John has worked extensively on Samsung device to make Magisk work on them? I would say this updated got released earlier than it was supposed to be because John Wu got a **SAMSUNG** device (Fold 2) and played with it. So people should be thankful to Samsung device. :/ I don't no why are you being salty about Samsung device. There is no reason to close the issue because it's not like John has dropped support for samsung device like he did for Huawei. And if John himself wants to close it, he will.

**Comment by soum91** [comment]
Also you have been trying to develop or solve the puzzle of making/flashing custom recovery for a while but haven't got anything significant, so it's only John Wu who can help.

**Comment by JarlPenguin** [comment]
@soum91 I don't see how he was being salty in anyway. That being aside, is the A20s an A/B or A-only device?

**Comment by soum91** [comment]
@JarlPenguin, either I misread it or it has been edited. Anyway I kinda overreacted. But there is trend on Github of making projects seem flawless/bugless by forcefully closing issue without actually addressing it. Maybe that thought came in the back of mind and I got triggered. :p And A20s is a SAR device.

**Comment by JarlPenguin** [comment]
If it's a SAR A-only device you should patch the recovery image for Magisk and follow the correct key combo to boot into system.

**Comment by soum91** [comment]
@JarlPenguin I followed John's [instruction](https://topjohnwu.github.io/Magisk/install.html#samsung-system-as-root) word by word(except for CSC because this device doesn't have CSC file). According to that it should boot normally without any key combo. Instead it's giving me loops as usual.

**Comment by yukosky** [comment]
The A20s, I have that device and it's bootloader issue, kernel don't help too.

**Comment by yukosky** [comment]
@JarlPenguin A20s is Fake AB (Aonly + SAR)

**Comment by piyush1097** [comment]
#3295 note 10 lite also giving vbmeta error verifying hash mismatched on magisk v8.0.1

**Comment by soum91** [comment]
@piyush1097 have you used Magisk 21? Did that work for you?

**Comment by yukosky** [comment]
Nothing works on that device. It is a high security coming from the bootloader, nothing lets you do custom bin in kernel, doing combo or not also does not work too.

**Comment by soum91** [comment]
@yukosky it's really weird, unbearably frustrating and unbelievable at the same time! @topjohnwu rooted Galaxy Fold 2, a phone that sits at the top in the production line, within 15 minutes or something! And this shitty cheap phone still stays unhackable like it's built for the president that can't be hack by anyone in this world? Is it believable?

**Comment by yukosky** [comment]
If you are so confident, do it for yourself, I say because I tried everything too.

**Comment by yukosky** [comment]
The only partitions that can have custom binary on the A20s (The ones I tested), is:
vendor
system
vbmeta, vbmetabak

Boot partition have high security, I know it’s frustrating.

**Comment by firemax13** [comment]
Anyway, we also tried to flash custom recovery like TWRP using flashify app or dd command and it does flashed and it doesn't show any secure check of on recovery.img but the one thing is, it doesn't boot at all into TWRP Recovery it does boot straight into system. We currently using phh GSI with su so we able to flash custom recovery, but still no luck of it. We heavily modified the TWRP Tree for this device but everyday we bricked it

**Comment by yukosky** [comment]
This problem is very frustrating

**Comment by sunamitheory** [comment]
don't worry @soum91, we are trying at our max to make TWRP bootable or achieve a concrete root method on it... thanks for @firemax13 and @yukosky for helping on development <3

**Comment by yukosky** [comment]
@sunamitheory u pro tester kthxbye, Ice pro dev

**Comment by yukosky** [comment]
@soum91 To summarize this root problem:

Bootloader, the only option left. **Technically** **Samsung Galaxy A20s** (AT LEAST UNTIL NOW, in the other binaries it may contain a failure to be able to root, as in the recovery itself) it is **impossible to root**, at most it is using Phh SU from Phhusson's AOSP GSI (Or others, like OptimiumOS private GSI) . There is no way beyond that, I know how frustrating this problem is and I understand you perfectly in that sense, but differentiating the Fold 2 5G with A20s is a totally different story, both devices are not the same, I hope you understand now.

**Comment by piyush1097** [comment]
@soum91 Yes I tried latest magisk 21 on Note10 lite (SM-N770F) , it didnt worked. It is showing error verifying vbmeta: HASH MISMATCHED after flashing patched AP. See my issue post #3295

**Comment by soum91** [comment]
> If you are so confident, do it for yourself, I say because I tried everything too.

@yukosky Nothing about being confident or anything. I'm just expressing my frustration. But I can't wrap my head around the fact that this shitty cheap has more security features than the phone that costs 10 times than this. Why is this? 
But now I see some hope of light as there are few people like you @firemax13 who are working. Also thanks @sunamitheory for that telegram group but you should make the group English only.

**Comment by yukosky** [comment]
> > If you are so confident, do it for yourself, I say because I tried everything too.
> 
> @yukosky Nothing about being confident or anything. I'm just expressing my frustration. I just can't wrap my head around the fact that this shitty cheap device has more security features than the phone that costs 10 times than this. Why is this?
> But now I see some light of hope as there are few people like you @firemax13 who are working on the device. Also thanks @sunamitheory for that telegram group but you should make the group English only.

:|

**Comment by sunamitheory** [comment]
> > If you are so confident, do it for yourself, I say because I tried everything too.
> 
> @yukosky Nothing about being confident or anything. I'm just expressing my frustration. I just can't wrap my head around the fact that this shitty cheap device has more security features than the phone that costs 10 times than this. Why is this?
> But now I see some light of hope as there are few people like you @firemax13 who are working on the device. Also thanks @sunamitheory for that telegram group but you should make the group English only.

You're welcome man, unfortunately off-topic is the thing that maintains that group alive yet, supported languages are PT/EN/ES (spanish). The tests we did until now, only headaches... idk if we need a dev help or just break the phone with a hammer ;(

**Comment by mu198** [comment]
@sunamitheory Have you tried the patched boot.img method before?

**Comment by piyush1097** [comment]
flashing patched boot.img works on Samsung Note10 lite but not patched AP. Patched AP gives error of hash mistmatched vbmeta error verifying

**Comment by piyush1097** [comment]
> @sunamitheory Have you tried the patched boot.img method before?

flashing patched boot.img works on Samsung Note10 lite but not patched AP. Patched AP gives error of hash mistmatched vbmeta error verifying

**Comment by piyush1097** [comment]
> @piyush1097 have you used Magisk 21? Did that work for you?

Yes I tried latest magisk 21 on Note10 lite (SM-N770F) , it didnt worked. It is showing error verifying vbmeta: HASH MISMATCHED after flashing patched AP. See my issue post #3295

**Comment by yukosky** [comment]
> @sunamitheory Have you tried the patched boot.img method before?

This don't work.

**Comment by yukosky** [comment]
We tried everything, what remains is to have a vulnerability in the partition or a binary that saves us.

**Comment by topjohnwu** [comment]
This seems to be a bootloader issue. When unlocked, the bootloader should not verify partitions. And also, the patched `vbmeta` also instructs the bootloader to ignore miss matches. Make sure the patched `vbmeta.img` is flashed properly

**Comment by sunamitheory** [comment]
> This seems to be a bootloader issue. When unlocked, the bootloader should not verify partitions. And also, the patched `vbmeta` also instructs the bootloader to ignore miss matches. Make sure the patched `vbmeta.img` is flashed properly

Unfortunately not, 100% sure that's a bootloader issue... 
I got one way to "achieve" root on A207M using null images to break binary checking of system and vendor to get GSIs working on it flashing via heimdall. Could mount vendor as rw, but something does not let magisk be installed or even editing fstab to mount as rw is not working. :(

**Comment by yukosky** [comment]
> This seems to be a bootloader issue. When unlocked, the bootloader should not verify partitions. And also, the patched `vbmeta` also instructs the bootloader to ignore miss matches. Make sure the patched `vbmeta.img` is flashed properly

Sad, but tried.

**Comment by Magendanz** [comment]
Note that the bootloader with Android 10 and later on the Samsung Galaxy Tab A 8.0 (2019) [SM-T290] is suffering from this same issue.  My TWRP builds had been working prior to the upgrade to Android 10, but now the bootloader gives me the blue "Secure Check Fail : recovery.img" screen.  Even signing the recovery image with the AVB hash footer doesn't help.

**Comment by shashankx86** [comment]
has any found a way to root a20s ??

**Comment by GitReflect** [comment]
Has there been any changes since ?? can anyone help with this issue..
ID:0/008> Added!!
<ID:0/008> Odin engine v(ID:3.1401)..
<ID:0/008> File analysis..
<ID:0/008> Total Binary size: 34 M
<ID:0/008> SetupConnection..
<ID:0/008> Initialzation..
<ID:0/008> Get PIT for mapping..
<ID:0/008> Firmware update start..
<ID:0/008> NAND Write Start!! 
<ID:0/008> SingleDownload.
<ID:0/008> recovery.img
<ID:0/008> vbmeta.img
<ID:0/008> FAIL! (Auth)



has there been any proper way for the rooting of Samsung A20s, I have tried all methods and each time I get a Fail

**Comment by Younss1211** [comment]
How to can rooted Samsung a20s
