### ISSUE TITLE
从20427开始修补boot失败

### ISSUE THREAD

**Issue by UQJRlex** [topjohnwu/Magisk#3234]
从20427版本开始，修补boot.img文件出现失败。
如图
![IMG_20200930_094323](https://user-images.githubusercontent.com/39591894/94996662-8d804280-05d8-11eb-86a8-44a91e177a49.jpg)

我的机型是Redmi note7pro，Android 10
其它情况如图
![IMG_20201004_002249](https://user-images.githubusercontent.com/39591894/94996846-96254880-05d9-11eb-8e10-e6f9d187ead9.jpg)

我当前所使用的boot.img文件是
[https://1drv.ms/u/s!AuQHm2raPd8QgXhhsFIwR1A154lo](https://1drv.ms/u/s!AuQHm2raPd8QgXhhsFIwR1A154lo)

**Comment by osm0sis** [comment]
It's a normal A-only Legacy SAR boot.img. The issue seems to be internal with Manager/Magisk.
