### ISSUE TITLE
Magisk fails on Coral with Android 11

### ISSUE THREAD

**Issue by ryaniskira** [topjohnwu/Magisk#3236]
Using both the latest Beta (21) and Canary (21001) Magisk fails to boot on the device. It either reverts to the other slot and boots (without Magisk of course) or when flashed to both slots it kicks back to the bootloader with "No valid slots to boot"

**Comment by topjohnwu** [comment]
Magisk always work on Pixel devices, user issue

**Comment by ryaniskira** [comment]
How can it be a "user issue" when I literally follow letter by letter the install guide?
