### ISSUE TITLE
Ugly icon for Hidden (repackaged) Magisk Manager

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#3238]
Upon Hiding Magisk Manqger, the new, repackaged app gets ugly, oversized, default Android icon.

Repackaging process offers you additionally to place a shortcut to the Home screen

With that, I have two icons on the Hone screen
![Screenshot_2020-10-04-00-11-27-936_com miui home](https://user-images.githubusercontent.com/51943147/95002677-f2d33400-05d6-11eb-9d5b-8d134726b8b2.jpg)

- Ugly, oversized, green default Androud icon, named Manager (name I chose when  repackaging) - left on the screenshot.
By long tapping, that icon provides direct access to Modules, MagiskHide and.Superuser

- Standard Magisk icon, naned Magisk Manager (not the given, repackaged name) - right on the screenshot below)
Long tapping to that shortcut offers only Remove - hence, that icon does not provide long tap Magisk functionality and therefore cannot be used to substitute for the uggly icon given with the repackaged Magisk Manqger

Both icons open the repackaged Canary Magisk Manager 303

**Comment by zgfg** [comment]
I'm not sure for the numbers but till Canary Magisk 294 or so, repackaged Manager still had the same standard Magisk Manager icon

And I saw this ugly icon first time with Canary Magisk 299 or so

**Comment by wangdaning** [comment]
Can't you just long press the app in the app drawer and change icon?

**Comment by Anang007** [comment]
The same icon after I hid it, the magisk icon disappeared and changed to an android icon.

**Comment by Anang007** [comment]
Me too. The magisk icon disappears and changes to an android icon. Until I install it again and the results are the same, maybe I have to repack it manually.

**Comment by sr1canskhsia** [comment]
Guys please read the FAQ. This is intended behaviour.

**Comment by zgfg** [comment]
"You can also manually ask the app to create the icon in Magisk Manager settings."

Screenshot from the repackaged Manager attached, I didn't find such option, there is only a setting to add shortcut but as described above, shortcut does not fully ork as the icon for the app
![Screenshot_2020-10-04-08-00-25-077_kiohcaw fydn](https://user-images.githubusercontent.com/51943147/95008424-0eabf980-061a-11eb-82db-ddf6b329baba.png)

**Comment by phil19989** [comment]
I have the same problem, except that once I repack Magisk Manager and then add a shortcut to the home screen, both apps have the ugly android icon. 
Strangely though, unlike what zgfg has reported, both my apps have the long press functionality working.

![Screenshot_20201004-184357_One UI Home](https://user-images.githubusercontent.com/52619207/95010014-f1a31500-0671-11eb-9ae3-1756334dd678.jpg)
![Screenshot_20201004-184352_One UI Home](https://user-images.githubusercontent.com/52619207/95010016-f5cf3280-0671-11eb-9157-3d8951eab672.jpg)

**Comment by Madis0** [comment]
Are there actually apps that check Magisk _by its icon now_? That's just... scary.

**Comment by topjohnwu** [comment]
https://topjohnwu.github.io/Magisk/faq.html#q-after-i-hidden-magisk-manager-the-app-icon-is-broken

**Comment by zgfg** [comment]
> https://topjohnwu.github.io/Magisk/faq.html#q-after-i-hidden-magisk-manager-the-app-icon-is-broken

I see you closed, but then just fix your FAQ, there is no such setting to change the icon (only to make the shortcut, but it doesn't provide the same functionality)

Screenrecording below, showing the whole process of Hiding Magisk Manager:
https://mega.nz/file/V0sVkCxY#RDOpE0sLAx9Z1zNUjHcFm2wHGOWPOAMBq-4Us9ZSjCM

- I had Magisk Chanary channel, and already Magisk Manager 303

- Upon hiding the Magisk Manager, it dropped to 302, asking me to update again to 303 (no big deal but strange?!)

- There is no setting to change the icon but only to install the Shortcut

- Shortcut installed (already while hiding, when it popped-up and suggested), but observe a difference with long tap functionality between the 'ugly' icon (on the left) and shortcut (standard Magisk icon look, on the right)

**Comment by unixandria-xda** [comment]
See, but the FAQ isn't wrong it never says it gets the icon back, it explicitly says creating a shortcut which, for me anyway, has been he expected icon

**Comment by AndnixSH** [comment]
> Are there actually apps that check Magisk _by its icon now_? That's just... scary.

I'm not sure but I had tried to play a game with a game protection called Xigncode, detected any hidden apps, so it's possible it might scanning apps list and detect icons.

**Comment by zgfg** [comment]
> See, but the FAQ isn't wrong it never says it gets the icon back, it explicitly says creating a shortcut which, for me anyway, has been he expected icon

**Screenshot and citation from the FAQ - at the time of reporting is in my post above - pkease scroll up and look to the screenshot:**:
"You can also manually ask the app to create the icon in Magisk Manager settings."
That is **explicitely**  I C O N (not shortcut), isn't it?!
