### ISSUE TITLE
Says Ramdisk No, but still works, annoyingly

### ISSUE THREAD

**Issue by gordboy** [topjohnwu/Magisk#3239]
Hello I have installed 21.0/8.0.0 on LineageOS 17.1 on both Xiaomi Redmi Note 8 (ginkgo) and Xiaomi Redmi Note 8T (willow).

They both report "Ramdisk No" but work perfectly fine, without any messing around.

I installed on each device with 2 different methods - by updating an existing 20.4/7.5.1 in the app, and by installing zip file in recovery (which works fine).

So this is not exactly a bug report, but more of a report that the Ramdisk detection in the app seems faulty, which is an annoyance as it meant I had to test this all out, due to the dire warning in the new docu about Ramdisk issues ...

**Comment by topjohnwu** [comment]
In the last section in [Android Booting Shenanigans](https://topjohnwu.github.io/Magisk/boot.html#piecing-things-together) is your answer. And I quote:

> Some Type III devices’ bootloader will still accept and provide initramfs that was manually added to the boot image to the kernel (e.g. some Xiaomi phones), but many device don’t (e.g. Samsung S10, Note 10). It solely depends on how the OEM implements its bootloader.

It is literally impossible for Magisk to know whether a device bootloader accepts ramdisk, so the assumption is to always inform the user to use recovery mode

**Comment by mluerig** [comment]
@gordboy so which of the two methods did you use for willow?
@topjohnwu so willow is a type III device?

**Comment by gordboy** [comment]
@mluerig I just installed Magisk from TWRP using zip file in the normal way ... and I am now on 22.0 with no issues.
