### ISSUE TITLE
21.0 version OTAinstalled to the inactive not work

### ISSUE THREAD

**Issue by gzshasha** [topjohnwu/Magisk#3240]
21.0 version OTAinstalled to the inactive not work
I can’t successfully upgrade to Android 11 on Android 10.
![install_inactive_slot](https://user-images.githubusercontent.com/21958077/95009978-826cf700-0658-11eb-8e3c-2a35f446f7a0.png)
![Screenshot_20201004-154532](https://user-images.githubusercontent.com/21958077/95009988-91ec4000-0658-11eb-923f-a85b99f68549.png)

**Comment by topjohnwu** [comment]
It is left out because it is no longer possible on Pixel devices
