### ISSUE TITLE
Invalid vbmeta header after upgrading from Magisk v20.4 to v21

### ISSUE THREAD

**Issue by alexdonh** [topjohnwu/Magisk#3241]
What I did

1. S10+ (Exynos) with Magisk v20.4 installed and working flawlessly
2. Upgrade Magisk Manager
3. Grab the AP.tar.md5 file (the current installed firmware - also the latest) and go with patching file
4. Make sure Recovery tick is on
5. Get the magisk_patched.tar
6. adb pull to PC and go with Odin
7. Since this is just an upgrade on the same firmware (just re-patch the AP with newer Magisk) so I had no doubt and went straight with HOME_CSC to preserve my data
8. The flashing passed successfully

But when I restart the phone to recovery mode, I got:

```
ODIN MODE (AVB fail)
recovery: Error validating footer. (0)
recovery: Error verifying vbmeta image: invalid vbmeta header (6)
CUSTOM RECOVERY
VBMETA G975FXXU8DTH7,  33961017R
```

I also tried re-flashing several times with no luck so far.

Then I went back to check Magisk issues and realized that starting from v21, vbmeta is no longer patched. So I think there must be something wrong with my old patched vbmeta and the original one.

I guess I would have to factory reset the phone and start from scratch.... Or maybe there's a way? @topjohnwu 

I appreciate your help.

**Comment by topjohnwu** [comment]
Thank you for your report! I was seeking for someone to confirm but in vain. I will come up with some other fix, stay tuned!

**Comment by alexdonh** [comment]
Got my phone working back without losing data! The trick was quite simple: create a new tar file with everything in new `magisk_patched.tar` EXCEPT the `vbmeta.img.lz4` and grab the `vbmeta.img` in old `magisk_patched.tar` over then flash all BL + AP (new tar file) + CP + HOME_CSC

Thanks God I still keep the old `magisk_patched.tar` haha

Hope this wordaround helps anyone getting the same issue (and havent gone with factory reset yet).

Now I can enjoy new Magisk and patiently wait for the fix.
 
![Screenshot_20201005-001105](https://user-images.githubusercontent.com/10590429/95022104-9d456880-0664-11eb-85f7-0eb3f594242f.jpg)

**Comment by topjohnwu** [comment]
@alexdonh may you try to patch your `AP.tar` with this test Magisk Manager?
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/5328036/app-debug.zip)

**Comment by ABSAhmad** [comment]
> 
> 
> @alexdonh may you try to patch your `AP.tar` with this test Magisk Manager?
> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/5328036/app-debug.zip)

I've had the same problem and this fixed it for me. Thanks for the quick fix and the great work in general!

Will donate as soon as I possibly can :)

**Comment by achmafooma** [comment]
I ran into this same issue trying to root and install the latest stock ROM for the Galaxy Tab A (T510). It occurred with attempts to use both Magisk 21 and 20.4.

The test Magisk Manager attached above resolved the issue and allowed me to root and flash successfully.

And the above comment reminded me that I have been meaning to make a donation :-). Will do that now.

**Comment by saadmasra** [comment]
#

**Comment by alexdonh** [comment]
Thanks a lot for very quick response! Just now I managed to have some time to try. The test Magisk Manager works like a charm!

**Comment by 9jS2PL5T** [comment]
I'm trying to root my M30s and having the same error message. I'm following this guide:
https://magiskapp.com/root-samsung-galaxy-m30s-using-magisk
At the end of Step 6 my device is not booting in Recovery Mode. It is booting into download mode and showing these error messages. Does anybody know where the problem is?

**Comment by bphd** [comment]
What this test MagiSK have magical in it? What happens that makes the device okay with it?
