### ISSUE TITLE
magisk 21, modules system/vendor files not mount on my file system

### ISSUE THREAD

**Issue by youling257** [topjohnwu/Magisk#3242]

**Comment by youling257** [comment]
[magisk20mount.txt](https://github.com/topjohnwu/Magisk/files/5322890/magisk20mount.txt)
[magisk21mount.txt](https://github.com/topjohnwu/Magisk/files/5322891/magisk21mount.txt)

**Comment by youling257** [comment]
magisk 21, system/vendor 、app、priv-app、lib、framework can mount

[magisk21mount.txt](https://github.com/topjohnwu/Magisk/files/5322894/magisk21mount.txt)

**Comment by topjohnwu** [comment]
You did not provide enough info.
Just as a side note, adding new files in mount roots (e.g. directly in `/vendor`) is explicitly disabled to prevent bootloops

**Comment by youling257** [comment]
i build magisk, reset --hard 15f155100c075ad7790ffc07295dfc3e24f2f192, it's bad, not mount files.
reset --hard 945a52a99f1f2659117dfd8508401b0370563c9e, it's good, mount files.
