### ISSUE TITLE
Update to Magisk Stable 20.4 from Stable 20.3 fails in Manager Stable (8.0.0)

### ISSUE THREAD

**Issue by theft07** [topjohnwu/Magisk#3243]
Install log (direct install in Magisk Manager): 
- Target image: /dev/block/mmcblk0p20
- Device platform: armeabi-v7a
2034+0 records in
2034+0 records out
2082816 bytes (2.0MB) copied, 0.036926 seconds, 53.8MB/s
1410+1 records in
1410+1 records out
1443916 bytes (1.4MB) copied, 0.026429 seconds, 52.1MB/s
boot_patch.sh: line 61: chmod: Permission denied
boot_patch.sh: line 64: ./magiskinit: Permission denied
boot_patch.sh: line 73: ./magiskboot: Permission denied
- Unpacking boot image
- Checking ramdisk status
boot_patch.sh: line 104: cat: Permission denied
boot_patch.sh: line 136: ./magiskboot: Permission denied
boot_patch.sh: line 148: rm: Permission denied
boot_patch.sh: line 181: ./magiskboot: Permission denied
boot_patch.sh: line 51: rm: Permission denied
boot_patch.sh: line 52: rm: Permission denied
- Stock boot image detected
- Patching ramdisk
- Repacking boot image
! Unable to repack boot image!
! Installation failed

Device : Samsung Galaxy Tab A(6) SM-T285
Android : Lollipop 5.1.1 TouchWiz 
Magisk : 20.3 (20300)
Manager : 8.0.0 (302)

(Flashing the 20.4 zip in twrp results in successful installation of 20.4 but after rebooting, the tablet becomes unusable after 20 or so seconds (looks like systemui is crashing))

Latest canary (64effe93 (21001)) gets same install error (direct install in magisk manager 64effe93 (303)) when trying to update from 20.3 stable : 
- Target image: /dev/block/mmcblk0p20
- Device platform: armeabi-v7a
2026+0 records in
2026+0 records out
2074624 bytes (2.0MB) copied, 0.050171 seconds, 39.4MB/s
1381+1 records in
1381+1 records out
1415016 bytes (1.3MB) copied, 0.044494 seconds, 30.3MB/s
boot_patch.sh: line 61: chmod: Permission denied
boot_patch.sh: line 64: ./magiskinit: Permission denied
boot_patch.sh: line 73: ./magiskboot: Permission denied
- Unpacking boot image
boot_patch.sh: line 104: cat: Permission denied
- Checking ramdisk status
- Stock boot image detected
boot_patch.sh: line 131: ./magiskboot: Permission denied
boot_patch.sh: line 143: rm: Permission denied
boot_patch.sh: line 176: ./magiskboot: Permission denied
boot_patch.sh: line 53: rm: Permission denied
boot_patch.sh: line 54: rm: Permission denied
- Patching ramdisk
- Repacking boot image
! Unable to repack boot image!
! Installation failed

Installing canary zip in twrp results in manager not detecting root

**Comment by topjohnwu** [comment]
v21.0 addresses a lot of these installation issues. If you want to debug, please file another issue (since it is a separate problem) with required logs and info for canary builds
