### ISSUE TITLE
OTA Upgrades Guide is out of date for Pixel upgrades

### ISSUE THREAD

**Issue by yuranlu** [topjohnwu/Magisk#3244]
The documentation for how to apply updates at https://topjohnwu.github.io/Magisk/ota.html#devices-with-ab-partitions says for A/B devices to use the "Install to inactive slot" option.

However, this option seems to have been recently disabled for Pixel devices: 
https://github.com/topjohnwu/Magisk/commit/0ef92a4866dd449939131cb424bc57ba65f9978a

It would be appreciated if there were some documentation on what to do instead in order to apply an OTA on a Pixel device.

**Comment by topjohnwu** [comment]
The OTA sections are not linked directly in the table on contents page for a reason: because they are outdated and I do not want to update it (yet). Will update the page to indicate the deprecated status
