### ISSUE TITLE
Magisk Hide failed (after 8.0.0 update)

### ISSUE THREAD

**Issue by sultan1986** [topjohnwu/Magisk#3247]
I have redmi note 5 pro,4 ram 64gb,rooted, after updating magisk manager hide magisk manager (renaming app)not working its says failed, i tried uninstalling the complete magisk and installed by recovery again but still its failed, i gave two three try again but its not working,
Help

**Comment by sultan1986** [comment]
And yes i updated magisk also 20.4 is installed ,

**Comment by faad26** [comment]
Same problem in redmi note 7, I try everything like you

**Comment by topjohnwu** [comment]
Use canary and provide logs

**Comment by sultan1986** [comment]
--------- beginning of main
--------- beginning of system
02-02 06:19:38.344   621   621 I Magisk  : Magisk 64effe93(21001) daemon started
02-02 06:19:38.345   621   621 I Magisk  : * Device API level: 28
02-02 06:19:45.793   621  1175 D Magisk  : resetprop: getprop [ro.crypto.state]: [encrypted]
02-02 06:19:45.793   621  1175 D Magisk  : resetprop: getprop [init.svc.vold]: [running]
02-02 06:19:45.834   621  1175 I Magisk  : ** post-fs-data mode running
02-02 06:19:45.840   621  1175 I Magisk  : * Initializing Magisk environment
02-02 06:19:45.864   621  1175 I Magisk  : * Mounting mirrors
02-02 06:19:45.864   621  1175 I Magisk  : mount: /sbin/.magisk/mirror/system
02-02 06:19:45.864   621  1175 I Magisk  : mount: /sbin/.magisk/mirror/vendor
02-02 06:19:45.864   621  1175 I Magisk  : mount: /sbin/.magisk/mirror/data
02-02 06:19:45.865   621  1175 I Magisk  : link: /sbin/.magisk/mirror/product
02-02 06:19:45.865   621  1175 I Magisk  : * Setting up internal busybox
02-02 06:19:45.890   621  1175 D Magisk  : resetprop: decode with protobuf [/data/property/persistent_properties]
02-02 06:19:45.891   621  1175 D Magisk  : resetprop: prop [persist.sys.safemode] does not exist
02-02 06:19:45.894   621  1175 I Magisk  : * Running post-fs-data.d scripts
02-02 06:19:45.895   621  1175 D Magisk  : magiskdb: query magiskhide=[1]
02-02 06:19:45.895   621  1175 I Magisk  : * Starting MagiskHide
Using Canary (switched from stable to canary)
Still get Hide magisk manager failed

**Comment by zgfg** [comment]
Go to Developer options and turn on Install from USB (!!!) - and try again.
When it pops-out, Allow to Install from USB

**Comment by AlliotTech** [comment]
> For Xiaomi:
> 
> Go to Developer options and turn on Install from USB (!!!) - and try again.
> When it pops-out, Allow to Install from USB and continue hiding/repackaging MM
> 
> See:
> #3147

I tried, and the problem is still unsolved
