### ISSUE TITLE
Issue with the design of the new Magisk Manager

### ISSUE THREAD

**Issue by xmxrtyx** [topjohnwu/Magisk#3250]
Hey topjohnwu,
Nice job on the new Magisk Manager, looks really nice.
I came across this issue some time back when I was flashing a mod.
![Screenshot_20201004-193636549](https://user-images.githubusercontent.com/56784444/95017809-30889900-0679-11eb-8434-1cdcad7f784d.jpg)
The 'Flashing' covers the text. Maybe you can reduce the opacity or move the 'Flashing' to a corner
Thank You

**Comment by magicgoose** [comment]
noticed the same thing. I don't think it needs to be over the console, there's plenty of space in the toolbar at the top. please move it.

**Comment by osm0sis** [comment]
@diareuse can address this perhaps. A couple more options could be some overscroll so one can pull the text up to read it, or, when you tap and hold on it it could disappear temporarily.

**Comment by diareuse** [comment]
Good idea @osm0sis 👍 I'll try to whip up something like that 🙂

**Comment by Mikesew1320** [comment]
Yeah, that's better. 😍
