### ISSUE TITLE
Secure Check Fail : recovery.img error on samsung A20s (SM-A207f) after flashing Magisk 

### ISSUE THREAD

**Issue by anazmohd95** [topjohnwu/Magisk#3251]
I was trying to root my a207f using magisk patched tar file, unfortunately the device stucked in secure check fail : recovery.img
the steps i did to flash magisk 
1- installed latest magisk on my device
2- extracted AP file from firmware file and copied to the device
3 - patched tar file from magisk manager and copied the patched AP .tar file to the pc by ADB Pull Command
4 - Flashed Patched AP with BL, CS, CSC through odin 

Can anybody help ... i really wanted to root my device

**Comment by osm0sis** [comment]
#3231

**Comment by Magendanz** [comment]
Note that the bootloader with Android 10 and later on the Samsung Galaxy Tab A 8.0 (2019) [SM-T290] is suffering from this same issue. My TWRP builds had been working prior to the upgrade to Android 10, but now the bootloader gives me the blue "Secure Check Fail : recovery.img" screen. Even signing the recovery image with the AVB hash footer doesn't help.

**Comment by shashankx86** [comment]
@Magendanz Hey can i use andoid 9

**Comment by Magendanz** [comment]
> @Magendanz Hey can i use andoid 9

Yeah, the workaround is to flash the last Android 9 aboot.mbn.lz4 and vaultkeeper.mbn.lz4 with your Odin tarball.

**Comment by Droid5xs** [comment]
> > @Magendanz Hey can i use andoid 9
> 
> Yeah, the workaround is to flash the last Android 9 aboot.mbn.lz4 and vaultkeeper.mbn.lz4 with your Odin tarball.

Will it work because I want to root my device

**Comment by Navneet-Kumar-Singh** [comment]
> > @Magendanz Hey can i use andoid 9
> 
> Yeah, the workaround is to flash the last Android 9 aboot.mbn.lz4 and vaultkeeper.mbn.lz4 with your Odin tarball.

Can you pls describe more about this , I have s4 binary and want to install twrp, shipped with android 9
