### ISSUE TITLE
"Rewrite skel_node mounting and construction logic" causes bootloop on x86 7.1

### ISSUE THREAD

**Issue by youling257** [topjohnwu/Magisk#3252]
Revert "Rewrite skel_node mounting and construction logic", not bootloop

https://github.com/youling257/Magisk

**Comment by osm0sis** [comment]
Uh, prove it?

**Comment by youling257** [comment]
https://github.com/topjohnwu/Magisk/issues/3242

**Comment by osm0sis** [comment]
What device?

**Comment by youling257** [comment]
cpu amd 3400g 256g nvme androidx86 7.1
