### ISSUE TITLE
Magisk Manager: Some UI issues on small-screen devices

### ISSUE THREAD

**Issue by Fs00** [topjohnwu/Magisk#3255]
I've encountered some layout issues in the new UI of Magisk Manager app on my (probably too) small screen phone (a Samsung Galaxy S3 Mini, 4" 800x480px).

- First, a serious usability issue: here the floating app bar covers the FAB, making the latter difficult to click on.
![Screenshot_20201003-222839](https://user-images.githubusercontent.com/30041551/95024817-cfb38d80-0685-11eb-94a9-fdfb75cc259a.png)

- SafetyNet test result is not vertically centered and does not use all the available space.
![Screenshot_20201003-222900](https://user-images.githubusercontent.com/30041551/95024862-07223a00-0686-11eb-921f-040c93c329e8.png)

- Lastly, "Update"/"Install" buttons in the home screen should probably be positioned on a new line when the screen width is too small for them to fit.
![Screenshot_20201003-222744](https://user-images.githubusercontent.com/30041551/95024680-06d56f00-0685-11eb-8c0e-0fb82ae2edc6.png)

**Comment by osm0sis** [comment]
Is your dpi jacked up or something? It doesn't look bad on my Galaxy Nexus, so.. 🤔

**Comment by Fs00** [comment]
Nope, I haven't changed my DPI scale. Galaxy Nexus has a bigger screen with a higher resolution, so that's why the app doesn't look bad.

**Comment by diareuse** [comment]
This is well known and code contains information that some elements do not fit neatly on some devices. Although the placement of these elements is not ideal it's still reachable but will be eventually fixed. Thanks.

**Comment by topjohnwu** [comment]
Partially addressed this issue: 5f63e889844a00e1d1ed33c152df4bf1eca10215
