### ISSUE TITLE
No "Install to Inactive Slot"

### ISSUE THREAD

**Issue by DoughMucker** [topjohnwu/Magisk#3256]
Was on Android 10 upgrading to Android 11 on a Pixel 4XL. Upgraded to Magisk Manager 8.00 and switched to v21.0 Beta Channel. After taking the OTA (steps 1 and 2), I switched to Magisk to patch to the inactive slot but was only presented with the Download Zip, Select and Patch a File, and Direct Install options. I was expecting the "Install to Inactive Slot" to be there too. Magisk shows "A/B  Yes" so it recognizes the 2 slots. 

I ended up downloading the factory image, patching the boot.img directly and installed the patched file with fastboot and all worked out in the end.

**Comment by osm0sis** [comment]
Intentional: https://github.com/topjohnwu/Magisk/commit/0ef92a4866dd449939131cb424bc57ba65f9978a

**Comment by DoughMucker** [comment]
Thanks for the clarification.

**Comment by LHJ** [comment]
Is this fixed and I'm just not finding where to do it, or is it still in progress?
