### ISSUE TITLE
Magisk 21 Selinux Policy Problem

### ISSUE THREAD

**Issue by boldbeastsoft** [topjohnwu/Magisk#3257]
Hi topjohnwu,

We start up a daemon by Magisk 21 and our app can't connect to the daemon by unix_stream_socket. If we set selinux to permissive it works at once. But Magisk 20 doesn't have this problem. Is this a bug or something changed intentionally?

Thanks.

**Comment by Didgeridoohan** [comment]
There has been selinux changes in v21. If you would have checked the release notes and the updated docs you would have found this:
https://topjohnwu.github.io/Magisk/details.html#selinux-policies

Maybe you'll find some answers there.
