### ISSUE TITLE
Feature request: Make "Systemless hosts" switchable

### ISSUE THREAD

**Issue by djechelon** [topjohnwu/Magisk#3258]
With regards to #3171 which seems related to systemless hosts module, and given that disabling the module fixes the boot loop issue.

More in general, I'd request that the systemless hosts module is shown as a switch-on-switch-off toggle, so that users can disable the module if needed.

Currently, tapping the "Systemless hosts" only enables it (at the next reboot). This may be undesired if one decides to upgrade A11 but has to switch off the module first. In general, it would be consistent with MagiskHide module.

I am currently using Magisk Manager Beta 8.0.0 (302)

**Comment by osm0sis** [comment]
You can just go remove the module..
