### ISSUE TITLE
Where can I enable Core Only Mode in the new Magisk Manager 8.0

### ISSUE THREAD

**Issue by 0rangeAppl3** [topjohnwu/Magisk#3259]
I been looking around and it seems the option to enable core only mode is removed from the newest manager. Is there anyway I can do it with the current version? Thank you

**Comment by topjohnwu** [comment]
There is no core only mode. To disable modules, boot into Safe Mode.
https://topjohnwu.github.io/Magisk/faq.html

**Comment by 0rangeAppl3** [comment]
> There is no core only mode. To disable modules, boot into Safe Mode.
> https://topjohnwu.github.io/Magisk/faq.html

Safe Mode disable ALL apps installed on device. The last Magisk Manager 7.5.1 have the option to Enable Core Only Mode in setting, where it only loads magisk core and no modules, other installed apps still available after reboot. Is there anyway I can do it now with MM 8.0?
Thanks

**Comment by Henri-J-Norden** [comment]
I can still toggle core-only mode with the Magisk Manager for Recovery Mode (mm) module, so core-only mode still exists and works (with Magisk 20.4). It is not at all understandable why this functionality, critical for debugging boot failures, would be hidden from the manager app.

**Comment by jazir5** [comment]
Please readd this, I don't know why you would remove this. I use this feature all the time, I don't understand why you couldn't leave the functionality from the old magisk version and put it in settings. If you won't readd it, what is the most recent magisk manager version that has it, I'll downgrade if necessary.
