### ISSUE TITLE
disk encryption and dm-verity patches cause bootloops on Huawei P10 Plus

### ISSUE THREAD

**Issue by rqou** [topjohnwu/Magisk#326]
If I directly install v13.3 via TWRP, the device will bootloop. If I install v12, it works. If I upgrade to v13.3 using Magisk Manager and check the "Keep force encryption" and "Keep dm-verity" boxes, it also works.

**Comment by Holo24** [comment]
Hi, can you send me the zip file with force encryption and dm verity please?

**Comment by Didgeridoohan** [comment]
@Holo24 

Type this in terminal before flashing the regular Magisk zip:
```
echo KEEPVERITY=true>>/data/.magisk
echo KEEPFORCEENCRYPT=true>>/data/.magisk
```
That'll make the installation script keep dm-verity and forced encryption on your device.

**Comment by Holo24** [comment]
@Didgeridoohan it worked ,thank you(on p10)

**Comment by Ante0** [comment]
It's my "fault". (I made the commit) 

If you decrypt first (Format Data) it will work fine. But not without decrypting. 
I wonder if the installer somehow can check if /data is decrypted already and then remove "fileencryptioninline" from fstab. I guess the difference is that when you are encrypted using disk-encryption the partition can't be read at all, but file-encryption allows you to partially read and write to the partition.
