### ISSUE TITLE
Adding Magisk to VMOS ROM manually?

### ISSUE THREAD

**Issue by AndnixSH** [topjohnwu/Magisk#3260]
I know VMOS app is not supported yet, and Manager couldn't detect image. But I wonder if i could add Magisk manually since the ROM zip is an entire ramdisk which I can modify it easly (See screenshot). The Manager app did reported that it has ramdisk

![image](https://user-images.githubusercontent.com/40742924/95095295-2c1cb880-072b-11eb-9e54-52b17ec2c7d2.png)

I have the file Magisk-20.4(20400).zip ready so what are the steps to add the files manually in order to get it running? I couldn't understand the zip installer scripts well

The ROM version is Android 5.1.1 armv7 and Android 7.1.2 arm64. Files permissions and symlink are automatically set once installed

**Comment by topjohnwu** [comment]
Please refer to the installation scripts, I will not manually support VMOS

**Comment by AndnixSH** [comment]
I don't ask to support it but how to add manually. Fortunately I just got started learning bash scripting
I will try to compare the whole RAM disk without magisk and one with magisk since it's much easier for me. If it don't help, I will learn more scripts

**Comment by AxomiyaGamer** [comment]
Did u got magisk on vmos?? If yes then please teach me too

**Comment by Lvblanc** [comment]
u can try patching boot.img in magisk app

**Comment by HuskyDG** [comment]
Hi, i made a modification for VMOS to install magisk on it but it is not work properly.
You can test https://github.com/HuskyDG/Magisk-on-VMOS

**Comment by Dorabotmaster** [comment]
Please it is saying 404 not foun ur link

**Comment by Dorabotmaster** [comment]
> Hi, i made a modification for VMOS to install magisk on it but it is not work properly. You can test https://github.com/HuskyDG/Magisk-on-VMOS

Helpp
