### ISSUE TITLE
Magisk Manager makes Android 11 boot image unbootable

### ISSUE THREAD

**Issue by jakiki6** [topjohnwu/Magisk#3261]
I updated to Android 11 today. If I patch the boot.img from the factory image and boot it, it doesn't boot and shows a black screen and kicks me back to the bootloader a few seconds later. I'm using a Pixel 3a. I don't have any boot logs.

[boot image](http://www.mediafire.com/file/3h3q9u8dxmd6jsw/magisk_patched_%283%29.img)

**Comment by jakiki6** [comment]
Manager: 8.0.0
Magisk: 21

**Comment by jakiki6** [comment]
Ok nvm it changed the update chanel to stable so it used v20.4 instead of v21.
Now it works

**Comment by saadmasra** [comment]
@jakiki6

**Comment by yangzhaofeng** [comment]
By the way, would you mind telling us the size of successfully packed boot image? Is it 32MB or 64 MB?

**Comment by jakiki6** [comment]
It's 64M
