### ISSUE TITLE
Galaxy Tab A (2019) (T510) Won't Boot With Magisk 21.0

### ISSUE THREAD

**Issue by achmafooma** [topjohnwu/Magisk#3262]
After getting past issue #3241, I discovered that the Galaxy Tab A (2019) (T510) will not boot normally with Magisk 21.0. It hangs at the first screen (the one with 'Secured by Knox' and 'Powered by Android' messages) and never continues. This occurs using both the root (via recovery) and non-root boot modes.

It happens before logcat starts logging anything so I don't have any error messages. Happy to help troubleshoot if there is some other way to get debug info for you.

The only way to boot it in this state is to bring up recovery and select "Reboot system now," which seems to work properly (but doesn't give root access). I ended up re-patching the ROM using Magisk 20.4 (with Magisk Manager from #3241), and that works as expected.

**Comment by Sap1k** [comment]
Many QCom devices also suffer from this, including my sdm660 based Redmi Note 7. The only difference is that the phone will give up and reboot into fastboot mode. Rebooting from recovery has no effect on the result. Flashing a different "MagiskCU" ZIP file and the beta rightafter fixes it.
It would be nice if @topjohnwu would look into this, since it doesn't seem to be an isolated issue

**Comment by topjohnwu** [comment]
@Sap1k what is the MagiskCU thing you're talking here? Link?

**Comment by Sap1k** [comment]
@topjohnwu It's been circulating all over Telegram and XDA (for devices that have the issue) so I wasn't able to trace it back to the source. However here's the .zip file if it helps
[MagiskCU.zip](https://github.com/topjohnwu/Magisk/files/5363459/MagiskCU.zip)

**Comment by KirbyFan102** [comment]
@Sap1k, how am I supposed to use that file? I have a Samsung phone.

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.
