### ISSUE TITLE
Can't update magisk su

### ISSUE THREAD

**Issue by th0rig** [topjohnwu/Magisk#3268]
Before i continue i apologize for error grammar spelling error or typo  and sorry if This issue are duplicate
Ok as title say i cant update magisk su i can update magisk manager with NO problem but not The Su and here my device specs
1.Smartfren andromax Es an indonesia exclusive phone
2.i'm on android Marshmallow 6.0.1 Cm13/Los13 based custom rom
Currently i'm on magisk v24.0 right Now safetynet passed with systemless xposed about xposed i curious if This mod the culprit i cant update here the screenshot
![Screenshot_20201006-135759](https://user-images.githubusercontent.com/52917124/95170482-b540f780-07de-11eb-9479-ae6657676574.png)

**Comment by topjohnwu** [comment]
The reason is already shown in the logs...

**Comment by th0rig** [comment]
So i just need to uninstall v20.4 in order to update to v.21.0 that's what you mean? Sorry for the typo before if you say so well then i just get along with what you said.
