### ISSUE TITLE
v21, android 11: bootloop at bootloader when flashing magisk patched img 

### ISSUE THREAD

**Issue by Hmmmmmmmmmm** [topjohnwu/Magisk#3271]
**What I've done**
- download stock image file from official Google site for [factory images ](https://developers.google.com/android/images#blueline)
- follow the instruction given by John Wu [here](https://topjohnwu.github.io/Magisk/ota.html)
- remove all modules use adb command
- when i flash the patched boot.img file, it stuck on the *G logo* with progress bar under it.
- After a certain period of time, it comes back to bootloader with a prompt saying: "no valid slot to boot".

**Device info**
I'm using android 11 on Pixel 3 (blueline), latest android security update (October) & Google play system update.. Build number: RP1A.201005.004
Magisk: Magisk Manager v8.0.1(304) , Magisk v21.0 to be installed.

I created [page on XDA forum](https://forum.xda-developers.com/apps/magisk/magisk-v21-android-11-bootloop-t4171919) too, people reported same issue there with Pixel models

**Comment by V10lator** [comment]
Same for me on a Honor 9 Lite with either Resurrection Remix OS 7.0.1 Beta 1 or AEX Beta 1 P1 (Minimal GApps).
I was able to install Magisk in the past but this time it ends in a bootloop when trying to reboot to recovery. I followed the instructions at https://topjohnwu.github.io/Magisk/install.html

**Comment by tino-247** [comment]
I had the same "no valid slot to boot" issue with 20.4 and it works fine with 21.0.

**Comment by topjohnwu** [comment]
Let's track it here #3277

**Comment by Hmmmmmmmmmm** [comment]
> Let's track it here #3277

Don't seem to be the same problem? Can't boot magisk_patched.img here 😂

**Comment by Starforce9** [comment]
I also have the same problem where it bootloops. Android 11 October Patch. Pixel 3a XL. Magisk Manager 8/Magisk 21

**Comment by PerfectSlayer** [comment]
Hi all,

First, the manager seems to have issue patching the boot.img file.
On first try, it only creates a 0 byte file, even if the log seems okay.
On the second try, when a `magisk_patched.img` already exists, it well created a 25m file. The 2nd log is the same.

Even using the 25m patched boot file, the device can't boot.

Configuration:
* Pixel 2 (walleye)
* Factory rom (walleye-rp1a.201005.004-factory)
* Manager 8.0.2 (307)
