### ISSUE TITLE
Magisk hangs out by pressing on Install or Download path buttons

### ISSUE THREAD

**Issue by xcme** [topjohnwu/Magisk#3273]
I decided to try Magisk on Huawei Nova with **locked** bootloader. I haven't used it before at all.

As the title says it just hangs out when I press on Download path section in Settings or on Install button. Then a windows with proposal to close Magisk appears.

Is it a common issue? What can I do? I tried to reinstall it but it didn't helped.

**Comment by EtianAM** [comment]
Something similar happens to me, I updated Magisk Manager and now I am unable to update Magisk or install any module. Stop responding

**Comment by xcme** [comment]
Oh, found the reason. I had to add Storage permission manually (the app doesn't ask for it) and now it works.

P.S. Haven't tested the app yet.

**Comment by EtianAM** [comment]
It is true, it blocks instead of asking, I activated it manually and it worked... That should work like this?

**Comment by quada** [comment]
similar issue, except when I press download and install buttons nothing happens at all.. I cannot manually grant storage access with OS I am using
