### ISSUE TITLE
Brocken bluetooth after flashing magisk on OOS 10.5.8 (OpNord)

### ISSUE THREAD

**Issue by TheHitekFive** [topjohnwu/Magisk#3275]
Hi,
I have the OnePlus Nord and bluetooth get brocken after flashing magisk (only on OxygenOS 10.5.8 EU).
On 10.5.7 no problems, but I prefer 10.5.8.
And with stock boot.img bluetooth work but in a logical way magisk doesn't work.
Please fix this bog.
Tested with :
- Magisk Canary (latest of 6 october 2020)
- Magisk Stable 20.4

**Comment by DeltaOn3X** [comment]
if you have the "Bluetooth Library Patcher" module installed, remove it and try again, it should work

**Comment by TheHitekFive** [comment]
Just a HID enabler

**Comment by TheHitekFive** [comment]
Ok it's fixed I have uninstaled blutooth HID enabler and it's work 😍 thank's
