### ISSUE TITLE
Remember super user selection

### ISSUE THREAD

**Issue by xtexChooser** [topjohnwu/Magisk#3278]
After I choose to allow, remember my choice. The application will directly reject or agree to the next application for root permissions.
I am very annoying. Some apps crazily applied for root permissions, many times, and I just did one operation. For some apps, you must apply for root every time you start it. Then MagiskSU asked me frantically.

**Comment by Didgeridoohan** [comment]
I cannot reproduce. You'll have to provide more details and logs. Take a look here for tips: https://www.didgeridoohan.com/magisk/MagiskHelp
