### ISSUE TITLE
I could not install any Magisk module.

### ISSUE THREAD

**Issue by xtexChooser** [topjohnwu/Magisk#3279]
I tried to install the module using Magisk Manager.
But it says "This ZIP is not a Magisk module."
and "Install failed."
I tried to download it locally (download ZIP from https://github.com/Magisk-Modules-Repo/foxy-boot). But still useless.

**Comment by zgfg** [comment]
Have you tried with any other module, like BusyBox NDK, MHCP, ADB & Fastboot NDK

Btw, tried yours, it failed saying that library is missing, hence something wrong with the module

Tested with latest Canary, flashing the module from MM
