### ISSUE TITLE
Magisk 21.0 breaks Mobile Signal Guru App

### ISSUE THREAD

**Issue by crazyuploader** [topjohnwu/Magisk#3281]
Hi, 

While it was cool to have `Magisk 21.0`, it unexpectedly broke something beyond my comprehension and rendered [Mobile Signal Guru App](https://play.google.com/store/apps/details?id=com.qtrun.QuickTest) useless, no matter how many times I restarted/changed kernels/ROMs (Android 10 by the way), the problem persisted. Attaching the screenshot below -

![image](https://user-images.githubusercontent.com/49350241/95312771-f56eab80-08ac-11eb-9e9f-581adac6039e.png)

And finally, it worked when I had switched back to `Magisk 20.3` (though it should work on `Magisk 20.4` as well). As for some basic info, here it is given below -

***Device:*** Whyred (Redmi Note 5 Pro)
***ROM:*** Android 10 (Not MIUI)
***Magisk Version:*** 21.0

Thanks in advance!

**Comment by zgfg** [comment]
You mean Network Signal Guru as on the Playstore - running fine with root granted on Xiaomi Mi 9T, eea MIUI 12 (A10), Magisk Canary 21001
![IMG_20201007_115731](https://user-images.githubusercontent.com/51943147/95316636-60f84f00-0894-11eb-94b0-8b393a727d2c.jpg)
![Screenshot_2020-10-07-11-53-01-974_com qtrun QuickTest](https://user-images.githubusercontent.com/51943147/95316670-6b1a4d80-0894-11eb-9707-be40efc571f4.jpg)

**Comment by Displax** [comment]
@crazyuploader you need set selinux mode to permissive.
Or wait new NSG version, where this issue is already fixed.

**Comment by crazyuploader** [comment]
> @crazyuploader you need set selinux mode to permissive.
> Or wait new NSG version, where this issue is already fixed.

NSG to work? Even on Android 10? It used to work with Magisk 20.3/20.4 so I thought it might have to do something with Magisk 21.0, but if it's not, my best bet is to stick with Magisk 20.3 only.
