### ISSUE TITLE
Magisk Manager (8.0.*) goes into loop while opening app in portrait mode on tablet

### ISSUE THREAD

**Issue by eberhardweber** [topjohnwu/Magisk#3283]
I've had an issue on my Samsung Tab S 10.1 LineageOS 14.1 tablet for a while. 

The previous version of Magisk Manager (v7.5.1) would start swapping viewpoint while flashing modules on the tablet, it would flicker from portrait to landscape to portrait all the way thru flashing. I could never use the "restart" button due to this bug in the Manager after flashing, but that was not a big deal - I'd simply switch out of the app and restart from the Android menu.

With the new 8.0 Manager (8.0.0. and 8.0.1), however, starting up the app in portrait mode on the tablet, the application goes into a startup loop, just displays its boot logo splash screen and then seems to restart, shutting down and starting up, never reaching functionality. 

If the app has already been booted up in landscape, opening it back up in portrait also loops it, reopening and closing its previously visible view until you attempt to close the app or switch to another.

In landscape, the application starts up properly so far.

Looking at how the app is behaving, I believe both bugs (the flashing screen looping between portrait and landscape in 7.5.1 and the program not starting up in 8.x) are related somehow.

**Comment by topjohnwu** [comment]
If you want the issue fixed, please install canary builds and upload a logcat
