### ISSUE TITLE
Some feature request and bug report

### ISSUE THREAD

**Issue by xtexChooser** [topjohnwu/Magisk#3286]
Append of #3278 and #3279

# Basic information
![Screenshot_20201007_200237](https://user-images.githubusercontent.com/46394906/95328408-1b5d7580-08d8-11eb-82f6-47b3c4578cb8.png)
![Screenshot_20201007_200331](https://user-images.githubusercontent.com/46394906/95328486-3203cc80-08d8-11eb-9257-add2f588430b.png)
Android 6.0.1
Samsung Galaxy S5(SM-G9008W)
I used TWRP to install Magisk.
But the Magisk Manager is not installed auto.
I installed it manually.

# Bugs
## 1. No logs
![Screenshot_20201007_200430](https://user-images.githubusercontent.com/46394906/95328579-552e7c00-08d8-11eb-83a1-57fab7cafa07.png)
Magisk Manager没有显示任何文本日志，但是su日志树可以显示
![Screenshot_20201007_200430](https://user-images.githubusercontent.com/46394906/95328687-7e4f0c80-08d8-11eb-8409-dee0936d4cf3.png)

## 2. Could not install any Magisk modules
I tried to install the module using Magisk Manager.
But it says "This ZIP is not a Magisk module."
and "Install failed."
![Screenshot_20201007_200730](https://user-images.githubusercontent.com/46394906/95328918-c110e480-08d8-11eb-812b-7cb3b8f8f770.png]
I tried to download it locally (download ZIP from https://github.com/Magisk-Modules-Repo/foxy-boot). But still useless.
I tried with other module.
Exported log:
```
- Copying zip to temp directory
! This zip is not a Magisk Module!
! Installation failed
```
> See video

# Feature request
## Remember super user selection
After I choose to allow, remember my choice. The application will directly reject or agree to the next application for root permissions.
I am very annoying. Some apps crazily applied for root permissions, many times, and I just did one operation. For some apps, you must apply for root every time you start it. Then MagiskSU asked me frantically.

# 附加
我的android.os.Build：
![Build](https://user-images.githubusercontent.com/46394906/95330523-409fb300-08db-11eb-8fd7-49b25130cc3f.png)
视频：https://xtex.lanzous.com/iop7bh8zlfg

**Comment by xtexChooser** [comment]
LogCat: https://xtex.lanzous.com/iSchGh9280b

**Comment by z826540272** [comment]
现在还有人在用三星S5啊，我也在用，不过我刷机了
