### ISSUE TITLE
Apps keep on asking for root access.

### ISSUE THREAD

**Issue by raeespulikkal** [topjohnwu/Magisk#3289]
I came across a problem which prompts me to give root access to apps even though I did it once giving it forever access. My device is Samsung galaxy Tab A6 , sm-t285 on stock ROM. The second problem is no logs are shown. And finally I dunno if I'm doing something wrong but the bottom bar sometimes disappears and I can't seem to find it.
![Screenshot_2020-10-07-22-17-11](https://user-images.githubusercontent.com/72516121/95361871-e7d81680-08ea-11eb-8ce2-5ac8a40ccca9.png)
![Screenshot_2020-10-07-22-17-06](https://user-images.githubusercontent.com/72516121/95361876-e9a1da00-08ea-11eb-90b1-65ad4b690840.png)
![Screenshot_2020-10-07-22-19-27](https://user-images.githubusercontent.com/72516121/95362065-2cfc4880-08eb-11eb-8ce2-bf09f6dc18b9.png)

I really love the new UI ❤️

**Comment by theft07** [comment]
I've got the same tablet and rom. This problem is present for me too on 21001. No logs are shown, no modules are loaded. When trying to add a module, error "this is not a magisk module" is shown.

**Comment by raeespulikkal** [comment]
> I've got the same tablet and rom. This problem is present for me too on 21001. No logs are shown, no modules are loaded. When trying to add a module, error "this is not a magisk module" is shown.

Phew. I'm not the only one.
I haven't checked if modules work cause I'm a beginner and haven't installed even one module. And I was gonna try if modules work and none of them showed up. The page is blank. I do have a good internet connection.

**Comment by raeespulikkal** [comment]
Update: I wanted to uninstall and try installing magisk and magisk module to see if the problem still persist but I can't even uninstall it through the app. It downloads the uninstaller file but when flashing it say the file is not a magisk module???

**Comment by nickeldan** [comment]
Still seeing this issue with Magisk 25.2 on a Nexus 5X.

**Comment by nickeldan** [comment]
I'm still seeing this issue with Magisk 25.2 on Nexus 5X.
