### ISSUE TITLE
Magisk not mounting system mirror and other structures

### ISSUE THREAD

**Issue by Zykreh** [topjohnwu/Magisk#329]
--------- beginning of main
I( 3162: 3162) Magisk v13.3(1330) daemon started
I( 3162: 3175) ** post-fs mode running
--------- beginning of system
I( 3162: 3257) ** post-fs-data mode running
I( 3162: 3257) * Mounting /data/magisk.img
I( 3162: 3257) * Running post-fs-data.d scripts
I( 3162: 3257) * Loading modules
I( 3162: 3257) xiaomi-safetynet-fix: constructing magic mount structure
I( 3162: 3257) * Mounting system/vendor mirrors
E( 3162: 3257) mount /dev/block/platform/155a0000.ufs/by-name/SYSTEM->/dev/magisk/mirror/system failed with 16: Device or resource busy
I( 3162: 3421) ** late_start service mode running
I( 3162: 3421) * Running service.d scripts
I( 3162: 3421) * Running module service scripts

Im using Aurora S8 Port rom in g935f, i also changed the kernel to batstock

**Comment by reversegear** [comment]
Having same issue with magisk 13.5+

13.3 works fine

failed with 16: Device or resource busy
