### ISSUE TITLE
Pixel 4 XL Android 11 stuck on Google Logo

### ISSUE THREAD

**Issue by hani4k** [topjohnwu/Magisk#3291]
My Pixel 4 XL running Android 11 stuck at the Google Logo after flashing the boot.img in the latest magisk stable channel. Do i need to change the channel to beta or canary to make a flash img?

**Comment by Hondo77** [comment]
Yes you do. Change to either Beta or Canary channel before patching the boot image. Beta 21.0 working fine on my Pixel 4 XL.

**Comment by matianhe** [comment]
> Yes you do. Change to either Beta or Canary channel before patching the boot image. Beta 21.0 working fine on my Pixel 4 XL.

Where can i find Canary channel?

**Comment by Hondo77** [comment]
> > Yes you do. Change to either Beta or Canary channel before patching the boot image. Beta 21.0 working fine on my Pixel 4 XL.
> 
> Where can i find Canary channel?

Settings>Update channel. For the Pixel 4 XL I would suggest setting it to the Beta channel, then patch your boot image. 

To set it to Canary you need to need to enter a custom channel URL: https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/debug.json

**Comment by matianhe** [comment]
> > > Yes you do. Change to either Beta or Canary channel before patching the boot image. Beta 21.0 working fine on my Pixel 4 XL.
> > 
> > 
> > Where can i find Canary channel?
> 
> Settings>Update channel. For the Pixel 4 XL I would suggest setting it to the Beta channel, then patch your boot image.
> 
> To set it to Canary you need to need to enter a custom channel URL unless you are already on the Canary Manager: https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/debug.json

Thanks
