### ISSUE TITLE
8.0.1 manager permission bug

### ISSUE THREAD

**Issue by DarkenLX** [topjohnwu/Magisk#3293]
Android version: 9
Device: LG V40 may affect others
Manager version: 8.0.1
Magisk: 20.4
Issue: doing anything that requires storage permission (if not set already to allow) causes the manager to freeze instead of bring up the usual ui prompt to allow storage access.

**Comment by zpcol** [comment]
same with me

**Comment by dasTohsy** [comment]
same here.
So i cant install magisk in magisk manager (for recovery).

**Comment by topjohnwu** [comment]
Thank you for the report, already fixed here: d9382f59bf8e25c68085f162cd808abed4a6c723
