### ISSUE TITLE
Error verifying vbmeta : HASH_MISMATCH error on Note10 lite (SM-N770F) on magisk 21 v8.0.1

### ISSUE THREAD

**Issue by piyush1097** [topjohnwu/Magisk#3295]
After flashing patched AP by **Magisk manager v8.0.1** on Note10 lite (SM-N770F) it's showing HASH_MISMATCH error. Hope you guys fix this as soon as possible.
![photo_2020-10-06_19-54-02](https://user-images.githubusercontent.com/59031072/95440218-4bf3ec80-0976-11eb-9417-bb51b7c330e2.jpg)

**Comment by piyush1097** [comment]
@soum91 please look into this issue too

**Comment by NightHammer1000** [comment]
Had this on my S6 Lite Tab too.

First off get a Stock Image and flash it to get the device running again.
After that:
Extract AP Package. Extract boot.lz4, Move Boot.img to Phone, Patch Using Magisk Manager, move magisk_patched.tar back to PC and Flash that using Odin in the AP Field.

Go directly to Recovery and Wipe Data.

Should work after that.

Magisk Manager does something wrong with the whole AP Package. But just patching the Boot.img works fine.

**Comment by KirbyFan102** [comment]
@NightHammer1000 Please provide more information! I patched the boot.img, but it gave me a file named Magisk_patched.tar instead. I tried compressing it with the modified 7zip, but then the download refused to run. Am I forgetting something?

**Comment by piyush1097** [comment]
> Had this on my S6 Lite Tab too.
> 
> First off get a Stock Image and flash it to get the device running again.
> After that:
> Extract AP Package. Extract boot.lz4, Move Boot.img to Phone, Patch Using Magisk Manager, move magisk_patched.tar back to PC and Flash that using Odin in the AP Field.
> 
> Go directly to Recovery and Wipe Data.
> 
> Should work after that.
> 
> Magisk Manager does something wrong with the whole AP Package. But just patching the Boot.img works fine.

I know patching only boot.img works but it messes with partition size later on, Something wrong with patching AP. Vbmeta check in Note10 lite checks for any custom or patched recovery, maybe thats why magisk patched AP giving error, cause keys of patched recovery doesnt getting matched to vbmeta.

**Comment by topjohnwu** [comment]
Please check #3262

**Comment by dex513** [comment]
I have the same problem with my samsung galaxy M21 android 12 smartphone when I did a root by Magisk I find this error

**Comment by sagar-limbani** [comment]
Same problem with my samsung m31s any solution ?

I'm not able to open in recovery mode
