### ISSUE TITLE
After updating manager 8.0.0, am I using a unknown source magisk manager?

### ISSUE THREAD

**Issue by vAn1she** [topjohnwu/Magisk#3296]
After In-APP updating, a notification bumped out and said 
"Always make sure you\'re using open-source Magisk Manager. Manager of unknown source can perform malicious actions."
I checked the text has existed in strings.xml before 8.0.0,

So I was the one who have been Man-in-the-middle attacked,
or will this message be shown to all users after version 8.0.0?

**Comment by topjohnwu** [comment]
Just a warning message to tell people to stop use unofficial Magisk Manager

**Comment by vAn1she** [comment]
Thank you very much, sir!
