### ISSUE TITLE
Hide Magisk Manager failed!

### ISSUE THREAD

**Issue by RealMaxHack** [topjohnwu/Magisk#3304]
I wanted to rebuild the application, but an error appears. "Hide Magisk Manager failed"

Version:

Magisk: 21.0(21000)
Installed: 21.00(21000)

Manager:
Latest: 8.0.2 (307) (11)
Installed: 8.0.2 (307)

My phone: Xiaomi Redmi 5 

![Screenshot_2020-10-09-13-44-49-857_com.topjohnwu.magisk.jpg](https://user-images.githubusercontent.com/49931842/95551769-a0aa6c80-0a35-11eb-9d97-0d00b1653c76.jpg)![Screenshot_2020-10-09-13-41-28-530_com.topjohnwu.magisk.jpg](https://user-images.githubusercontent.com/49931842/95551779-a2743000-0a35-11eb-8476-0dcea4eb3367.jpg)

**Comment by Didgeridoohan** [comment]
Likely a MIUI issue where you need to enable "Install from USB" in developer options. Could also be Play Protect that's acting up.

More details:
https://www.didgeridoohan.com/magisk/Magisk#hn_Cant_hide_the_Magisk_Manager

Not a Magisk issue, so you can close this (so that John or Chris doesn't have to).

**Comment by zgfg** [comment]
Thanks for adding USB to the Guide. Just please correct, setting is "Install via USB" (I made typos many times, sorry)
![Screenshot_2020-10-09-10-39-04-962_com android settings](https://user-images.githubusercontent.com/51943147/95562843-fb839a00-0a1c-11eb-9e67-9417b6137969.jpg)

However, upon enabling that option,@RealMaxHack will break at
https://github.com/topjohnwu/Magisk/issues/3297 (unless the new MM release with the fix would come earlier).
To circumvent, switch your Update channel to Stable (but leave Beta MM 8.0.2 307 and Magisk 21.0 21000) and then execute hiding/repackaging.
After the successful repackaging, you can switch the Channel back to Beta

**Comment by Didgeridoohan** [comment]
> Thanks for adding USB to the Guide. Just please correct, setting is "Install via USB" (I made typos many times, sorry)

Changed. Thank you.

> However, upon enabling that option,@RealMaxHack will break at
> #3297 (unless the new MM release with the fix would come earlier).
> To circumvent, switch your Update channel to Stable (but leave Beta MM 8.0.2 307 and Magisk 21.0 21000) and then execute hiding/repackaging.
> After the successful repackaging, you can switch the Channel back to Beta

That issue isn't found on the beta channel (only Canary channel is affected), so they'll be fine.

**Comment by RealMaxHack** [comment]
thanks for the help

**Comment by zgfg** [comment]
> > However, upon enabling that option,@RealMaxHack will break at
> > #3297 (unless the new MM release with the fix would come earlier).
> > To circumvent, switch your Update channel to Stable (but leave Beta MM 8.0.2 307 and Magisk 21.0 21000) and then execute hiding/repackaging.
> > After the successful repackaging, you can switch the Channel back to Beta
> 
> There's no need for all that... That issue isn't found on the beta channel (only Canary channel is affected), so they'll be fine.
Plesse see (2) in - tested yesterday,:
https://forum.xda-developers.com/showpost.php?p=83666887&postcount=41987

**Comment by Didgeridoohan** [comment]
> > > However, upon enabling that option,@RealMaxHack will break at
> > > #3297 (unless the new MM release with the fix would come earlier).
> > > To circumvent, switch your Update channel to Stable (but leave Beta MM 8.0.2 307 and Magisk 21.0 21000) and then execute hiding/repackaging.
> > > After the successful repackaging, you can switch the Channel back to Beta
> > 
> > 
> > There's no need for all that... That issue isn't found on the beta channel (only Canary channel is affected), so they'll be fine.
> 
> Plesse see (2) at (tested yesterday):
> https://forum.xda-developers.com/showpost.php?p=83666887&postcount=41987

Nope... Before replying to you above I double checked (I've tested when first investigating this issue, but just in case). Manager 307 can be repackaged using the beta channel. Again, beta channel is unaffected.

**Comment by zgfg** [comment]
I'm lazy to switch to Beta (from Canary) again, and to retest. But I did test yesterday with Beta channel, MM Beta 307, albeit with Magisk 21002 (Canary)

We'll see if somebody else reports for Beta (much less number of users)

**Comment by Didgeridoohan** [comment]
> I'm lazy to switch to Beta (from Canary) again, and to retest. But I did test yesterday with Beta channel, MM Beta 307, albeit with Magisk 21002 (Canary)

That's exactly the test I performed. Install beta Manager 307 (with Magisk 21002, but this is a Manager stub issue so the Magisk version doesn't matter), make sure it's on beta channel and repackage it. No issues.
