### ISSUE TITLE
I can't use patch boot image to get root permission on Pixel 3(Android 11)

### ISSUE THREAD

**Issue by C-starm** [topjohnwu/Magisk#3305]
Hi, I update my to Android 11, and use magisk manager to patch the boot image. But I can't install magisk while I boot the boot.img by magisk manager, becuse I can not find any button that install magisk to the device. Do you have any solution to solve this problem?Wish your reply, thx.

- Device type: Pixel 3 (blueline)
- System Version: 11.0.0 (RP1A.200720.009, Sep 2020)
- Magisk Version: 20,4(20400)
- Magisk Manager Version: 8.0.2(307)(11)

**Comment by zgfg** [comment]
It was mentioned elswhere that Magisk v21 ( currently only Beta or Magisk) are for Android 11.
See XDA, Magisk General thread
