### ISSUE TITLE
magiskhide cannot hide Google Services Framework

### ISSUE THREAD

**Issue by njtony11** [topjohnwu/Magisk#3306]
It seems that Google Services Framework is not hidden. Whether it is checked or not, after re-entering magiskhide, it is unchecked. When opening google feed, it is blank or the account error is displayed (not available in China), but the Google Services Framework is checked in magiskhide, Then press the home button to return to the desktop, then the google feed is normal, so it feels that magisk does not really hide the Framework.
P3aXL Android11，magisk manager v8.0.2, magisk v21
![1](https://user-images.githubusercontent.com/60228975/95582425-39101380-0a6d-11eb-8062-a856696df71f.png)
![2](https://user-images.githubusercontent.com/60228975/95582445-3e6d5e00-0a6d-11eb-89c6-9a90fe102431.png)

**Comment by Dark-Yox** [comment]
> After re-entering magiskhide, it is unchecked.

I can confirm same thing happening to me since the last  Magisk Manager update, tried cleaning the Manager data but doesn't solve the problem

### Environment 
Android 10 (arm64-v8a)
Magisk 21.0
Manager 8.0.2

### Screenshot

<img src="https://user-images.githubusercontent.com/45209462/95595040-0570c180-0a4c-11eb-80af-fe09ec61519d.png" width="480">

### Logs
```
10-08 23:11:36.127 627 18600 I Magisk : hide_list rm: [com.google.process.gapps] 
10-08 23:11:36.153 627 18603 I Magisk : hide_list rm: [com.google.process.gservices] 
10-08 23:11:38.469 627 18611 I Magisk : hide_list add: [com.google.android.gsf/com.google.process.gapps] 
10-08 23:11:38.511 627 18613 I Magisk : hide_list add: [com.google.android.gsf/com.google.process.gservices]
```

**Comment by njtony11** [comment]
> > 重新输入magiskhide后，将其取消选中。
> 
> 自上次Magisk Manager更新以来，我可以确认发生了相同的事情，尝试清除Manager数据但不能解决问题
> 
> ### 环境
> Android 10（arm64-v8a）
> SELinux强制
> Magisk 21.0
> Manager 8.0.2
> 
> ### 屏幕截图
> <img alt="" width="480" src="https://user-images.githubusercontent.com/45209462/95595040-0570c180-0a4c-11eb-80af-fe09ec61519d.png">
> 
> ### 日志
> ```
> 10-08 23:11:36.127 627 18600 I Magisk : hide_list rm: [com.google.process.gapps] 
> 10-08 23:11:36.153 627 18603 I Magisk : hide_list rm: [com.google.process.gservices] 
> 10-08 23:11:38.469 627 18611 I Magisk : hide_list add: [com.google.android.gsf/com.google.process.gapps] 
> 10-08 23:11:38.511 627 18613 I Magisk : hide_list add: [com.google.android.gsf/com.google.process.gservices]
> ```

I thought the problem only appeared on Android 11.
Android 10 used Manager7.5.2, Magisk 20.4 is perfect.

**Comment by vvb2060** [comment]
#3288 
This is just a display issue. When it is not expanded, it only cares about whether the process named `com.google.android.gsf` is hidden.  Because there is no such process name, the display is not checked.
ProgressBar displays the status of all processes, it is full, so you have hidden all processes.

**Comment by LordSithek** [comment]
I can confirm the same behavior on two of my devices running A10: Samsung Galaxy Tab S5e and Xiaomi Mi Note 10. On the latter I couldn't use Google Pay because of that, I had to rollback to 7.5.1

**Comment by flamer2** [comment]
me too,MI MIX2S Android 10 Magisk 22.1

**Comment by Dark-Yox** [comment]
I wonder why this wasn't fixed yet.

**Comment by Navneet-Kumar-Singh** [comment]
I think issue is in Google security got raised recently

**Comment by idanii** [comment]
Does anyone know what "MAGISK_MOUNT_POINT" means? I've been getting this error every single time I'm trying to open my bank app. They are detecting MagiskHide. How can I bypass their detection?

**Comment by Dark-Yox** [comment]
@idanii Did you try hiding the Magisk Manager in the settings?

**Comment by zadordima** [comment]
У меня такая же проблема.
