### ISSUE TITLE
Latest Magisk Manager v8.0.2 lacks the icon

### ISSUE THREAD

**Issue by joaocasarin** [topjohnwu/Magisk#3308]
Well, after hiding itself, it just loses its icon, leaving a standard android icon

**Comment by Ace081** [comment]
There is a setting called "Add shortcut to home screen" that does what you want.

**Comment by joaocasarin** [comment]
@Ace081 no, it doesn't, just take a look at how it is on my device:
![Screenshot_20201009-151241__01](https://user-images.githubusercontent.com/48847394/95617579-0866b480-0a42-11eb-9b83-f37c5d31ce61.jpg)

**Comment by Ace081** [comment]
It looked the same for me after upgrading to Magisk Manager 8.0. The setting I spoke of is a setting in Magisk Manager, not Android itself.

**Comment by topjohnwu** [comment]
https://topjohnwu.github.io/Magisk/faq.html
