### ISSUE TITLE
Disabling force encryption  when updating Magisk

### ISSUE THREAD

**Issue by 113408** [topjohnwu/Magisk#3309]
Hi All,
I'm trying to update Magisk using the command line instead of Magisk Manager. I use the util_functions.sh script with the Magisk.zip archive.
Basically the steps are:

1. Unzip the magisk archive somewhere on the phone
2. flatten all the files : mv arm/* common/* META-INF/com/google/android/update-binary .
3. replace magiskinit with 64 version
4. source the utils script
5. call get_flags to populate $RECOVERYMODE, $KEEPFORCEENCRYPT and $KEEPVERITY (all of them get true as value)
6. override MAGISKBIN with the location where I'm working
7. populate $BOOTIMAGE with the location of the boot image
8. call install_magisk

It all works well, the new-boot.img is pathced and flashed. I reboot the phone but then I get stuck on the Samsung Logo. While on the samsung logo I'm able to access the phone through ADB. I can see that the issue is the phone is not able to decrypt the /data folder (all the directories are still encrypted) this explains why the phone is stuck on the logo.

If I factory reset, the phone boots just fine and the update works well. But I would prefer if I can remove the encryption all together, or find a way to make it work with the encryption in place.

I know what I'm asking is possible because Magisk Manager is able to update Magisk without me having to factory reset.

Does anyone know either how to disable encryption before starting the update process OR how to make it work like on Magisk Manager ?

Thanks in advance

PS: The current boot.img has been patched with KEEPVERITY=true and KEEPFORCEENCRYPTION=true

**Comment by topjohnwu** [comment]
You should not mess with encryption, and if Magisk Manager is able to upgrade your device, there is nothing wrong with Magisk, and you are on your own here as I will not provide any support for manual installations
