### ISSUE TITLE
always mount Device or resource busy when emulator.sh run in android 9 avd  

### ISSUE THREAD

**Issue by cecini** [topjohnwu/Magisk#3311]
start avd with para -writable-system 
run emulator.sh, give erro info:
mount: mounting /dev/block/dm-0 on /sbin/.magisk/mirror/system_root failed: Device or resource busy

Switch to use rw mount option will ok ,but it will replace /sbin dir. Is it proper to use this workaround?

**Comment by topjohnwu** [comment]
Not really, `emulator.sh` is really only meant for developing root apps (including Magisk Manager) in an emulator, not for day-to-day usage
