### ISSUE TITLE
canary/debug.json has no proper links

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#3312]
Is this the right json for Canary (it used to be):
https://github.com/topjohnwu/magisk_files/raw/canary/canary.json

It cannot be used anymore for Custom channel (to update e.g. from Beta 307 to Canary 308), because there is no https link for app-debug.apk (neither for Magisk nor uninstaller).
Also, Note (Changelog) https links are missing:
![Screenshot_2020-10-10-11-31-43-593_com android chrome](https://user-images.githubusercontent.com/51943147/95652029-7cf72d00-0aee-11eb-83df-afa650a69303.jpg)

For comparison, Beta and Stable json files:
![Screenshot_2020-10-10-11-30-37-974_com android chrome](https://user-images.githubusercontent.com/51943147/95652045-99936500-0aee-11eb-89d9-63bbd2c3c999.jpg)
![Screenshot_2020-10-10-11-30-58-662_com android chrome](https://user-images.githubusercontent.com/51943147/95652051-a1eba000-0aee-11eb-8570-c32e79c4bc80.jpg)

**Comment by Didgeridoohan** [comment]
Check the comment on this commit:
https://github.com/topjohnwu/magisk_files/commit/fe98808bb1e3430dc5da5eae6ee5a14ed964af4c#diff-294a690da68d93a1e8bdd8b903861932

It's not the intention that users should use the direct links to the official json files for update channels...

Switching to the Canary build should be done by installing the Canary Manager and switch to the Canary channel. That way users won't have to experience issues when the json format is changed or the file is moved...

**Comment by zgfg** [comment]
Actually, I see no comment by the commit


It worked up to the recent. Btw, I wanted to update from the hidden Beta (yes, Beta 307 can be repackaged) to Canary by the custom link

Since 308 Canary as apk cannot be installed if you have repackaged Beta - it installs as a new Manager (alongside the hidden Beta), showing no Magisk found

**Comment by Didgeridoohan** [comment]
Scrolling?

At the top:
"New app will auto generate the actual links"

You can still use the debug.json if you really need to use the custom channel.

**Comment by zgfg** [comment]
Who and where will auto-generate the Custom channel link - clean install and Custom link is empty

If you mean the link for Canary channel, sorry, didn't expect that for some reason (?) even that would be removed now  - some intentional changes in UI/usability are not for good from the users perspective, unfortunately we'll have to live with
