### ISSUE TITLE
scripts/emulator.sh: "/system/xbin/su: inaccessible or not found"

### ISSUE THREAD

**Issue by mh-** [topjohnwu/Magisk#3316]
`scripts/emulator.sh` somehow assumes that `su` is already present on the AVD, but at least in the "Play Store" version, it's not. 
Instructions which `su` to use, and how to get it to `/system/xbin/` would be helpful :)

**Comment by topjohnwu** [comment]
It assumes the emulator is already rooted, which is required to install Magisk at runtime

**Comment by mh-** [comment]
Ok, thanks for the clarification. 
Meanwhile, I used [this](https://github.com/shakalaca/MagiskOnEmulator) in the `./patch.sh canary` flavour to root  the emulator and install Magisk at the same time.
