### ISSUE TITLE
After install Magisk, Bank apps detect "Root"

### ISSUE THREAD

**Issue by MadokaKanname** [topjohnwu/Magisk#3317]
Even device is NOT rooted, only installing Magisk Manager App, cause Bank Apps detecting that system is "Rooted".
After unistall, BANK apps like C6/Inter/Etc back to work.

**Comment by DanGLES3** [comment]
Try using the hide Magisk manager option, it should prevent apps from detecting Magisk by searching its package name

**Comment by MadokaKanname** [comment]
> Try using the hide Magisk manager option, it should prevent apps from detecting Magisk by searching its package name

Even using Hide Opt ennabled, some App like C6 detect magisk, other bank apps is working normal.

**Comment by DanGLES3** [comment]
> > Try using the hide Magisk manager option, it should prevent apps from detecting Magisk by searching its package name
> 
> Even using Hide Opt ennabled, some App like C6 Bank detect magisk, other bank apps is working normal.

Are you talking about Magisk hide or the hide Magisk manager option?

**Comment by topjohnwu** [comment]
#1152

**Comment by leobastiani** [comment]
> > Try using the hide Magisk manager option, it should prevent apps from detecting Magisk by searching its package name
> 
> Even using Hide Opt ennabled, some App like C6 Bank detect magisk, other bank apps is working normal.

Same problem here, if you find any solution, please contact me.

**Comment by leobastiani** [comment]
> > Try using the hide Magisk manager option, it should prevent apps from detecting Magisk by searching its package name
> 
> Even using Hide Opt ennabled, some App like C6 Bank detect magisk, other bank apps is working normal.

Same problem here, if you find any solution, please contact me. @MadokaKanname

**Comment by mateusjdev** [comment]
Same issue here too with same apps (Inter + C6), clean flash is ok but installing magisk with no changes in safety net leaves to root detection

**Comment by leobastiani** [comment]
A solution was found here
https://www.nextpit.com.br/forum/766179/poblema-com-apps-de-banco-plus-root-plus-custom-rom/page/4

**Comment by prschopf** [comment]
Its not working anymore. Now, it asks for an upgrade but there is no available upgrade.

**Comment by prschopf** [comment]
I had to disable service "nj.Y" in the version 2.30.1 (15/11/2020)
