### ISSUE TITLE
How to install magisk on Android x86 (PC rom)?

### ISSUE THREAD

**Issue by F1zus** [topjohnwu/Magisk#3318]
Hello. I installed assembly `AG-10-Bliss-OS-android_x86_64-202010071034_k-kernel-5.8-si-next-rmi_m-q_dgc-q-x86-generic_gms_cros-wv` and it works fine, it has a super su program by default to manage root access. I also need magisk for some programs. On the Internet, according to the instructions, you need to patch the ramdisk.img file, but there is no such file in this assembly. I tried patching the initrd.img file but magisk won't install. 
![Снимок экрана 2020-10-10 221940](https://user-images.githubusercontent.com/72674337/95666730-44466a80-0b65-11eb-8e0f-95a3c08e5bc5.png)
 How do I install magisk without ramdisk.img file?

**Comment by topjohnwu** [comment]
You cannot install Magisk without ramdisk. The `initrd` might be in a special format? You can try to transform the image to raw CPIO file and manually patch the file (please refer to installation scripts, I won't go into the process here)
