### ISSUE TITLE
V2ray 4.31.0运行错误

### ISSUE THREAD

**Issue by bigjunda** [topjohnwu/Magisk#3321]
SIGILL: illegal instruction
PC=0x4436c0 m=0 sigcode=1
instruction bytes: 0x0 0x6 0x38 0xd5 0xe0 0x7 0x0 0xf9 0xc0 0x3 0x5f 0xd6 0x0 0x0 0x0 0x0

goroutine 1 [running, locked to thread]:
golang.org/x/sys/cpu.getisar0(0x862140)
golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu_arm64.s:13 fp=0x400010fd50 sp=0x400010fd50 pc=0x4436c0
golang.org/x/sys/cpu.readARM64Registers()
golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu_arm64.go:65 +0x30 fp=0x400010fd70 sp=0x400010fd50 pc=0x442ee0
golang.org/x/sys/cpu.doinit()
golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu_linux_arm64.go:38 +0x2c fp=0x400010fd90 sp=0x400010fd70 pc=0x4431bc
golang.org/x/sys/cpu.archInit()
golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu_arm64.go:55 +0x20 fp=0x400010fda0 sp=0x400010fd90 pc=0x442e90
golang.org/x/sys/cpu.init.0()
golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu.go:199 +0x20 fp=0x400010fdb0 sp=0x400010fda0 pc=0x442430
runtime.doInit(0xf556a0)
runtime/proc.go:5625 +0x9c fp=0x400010fdf0 sp=0x400010fdb0 pc=0x50b4c
runtime.doInit(0xf62280)
runtime/proc.go:5620 +0x58 fp=0x400010fe30 sp=0x400010fdf0 pc=0x50b08
runtime.doInit(0xf5aca0)
runtime/proc.go:5620 +0x58 fp=0x400010fe70 sp=0x400010fe30 pc=0x50b08
runtime.doInit(0xf5dee0)
runtime/proc.go:5620 +0x58 fp=0x400010feb0 sp=0x400010fe70 pc=0x50b08
runtime.doInit(0xf5dc40)
runtime/proc.go:5620 +0x58 fp=0x400010fef0 sp=0x400010feb0 pc=0x50b08
runtime.doInit(0xf63aa0)
runtime/proc.go:5620 +0x58 fp=0x400010ff30 sp=0x400010fef0 pc=0x50b08
runtime.doInit(0xf5b420)
runtime/proc.go:5620 +0x58 fp=0x400010ff70 sp=0x400010ff30 pc=0x50b08
runtime.main()
runtime/proc.go:191 +0x1b8 fp=0x400010ffd0 sp=0x400010ff70 pc=0x439c8
runtime.goexit()
runtime/asm_arm64.s:1136 +0x4 fp=0x400010ffd0 sp=0x400010ffd0 pc=0x72e34

r0 0x1
r1 0x400010e3a0
r2 0x400010fd70
r3 0x4000195920
r4 0xa81ec0
r5 0xdb10
r6 0x1000
r7 0x4
r8 0xf2
r9 0x400019594f
r10 0x1000
r11 0x1
r12 0xa61624
r13 0x0
r14 0xf2
r15 0x0
r16 0x0
r17 0x8
r18 0x0
r19 0xf6a858
r20 0x400010fb10
r21 0x400010fc28
r22 0x4000002000
r23 0x0
r24 0x0
r25 0x0
r26 0xf556d8
r27 0xff7cb7
r28 0x4000000180
r29 0x400010fd48
lr 0x442ee0
sp 0x400010fd50
pc 0x4436c0
fault 0x0

**Comment by Didgeridoohan** [comment]
Wouldn't that be an issue with the app rather then Magisk?

**Comment by Mdog2008** [comment]
这个好像是v2ray的问题

**Comment by bigjunda** [comment]
单独运行没有问题，用magisk的脚本启动服务才会出现错误
