### ISSUE TITLE
v2ray 4.31.0 启动错误（Pixel3xl Android11）

### ISSUE THREAD

**Issue by felixet** [topjohnwu/Magisk#3326]
SIGILL: illegal instruction
PC=0x4436c0 m=0 sigcode=1
instruction bytes: 0x0 0x6 0x38 0xd5 0xe0 0x7 0x0 0xf9 0xc0 0x3 0x5f 0xd6 0x0 0x0 0x0 0x0

goroutine 1 [running, locked to thread]:
golang.org/x/sys/cpu.getisar0(0x862140)
	golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu_arm64.s:13 fp=0x400006bd50 sp=0x400006bd50 pc=0x4436c0
golang.org/x/sys/cpu.readARM64Registers()
	golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu_arm64.go:65 +0x30 fp=0x400006bd70 sp=0x400006bd50 pc=0x442ee0
golang.org/x/sys/cpu.doinit()
	golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu_linux_arm64.go:38 +0x2c fp=0x400006bd90 sp=0x400006bd70 pc=0x4431bc
golang.org/x/sys/cpu.archInit()
	golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu_arm64.go:55 +0x20 fp=0x400006bda0 sp=0x400006bd90 pc=0x442e90
golang.org/x/sys/cpu.init.0()
	golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu.go:199 +0x20 fp=0x400006bdb0 sp=0x400006bda0 pc=0x442430
runtime.doInit(0xf556a0)
	runtime/proc.go:5625 +0x9c fp=0x400006bdf0 sp=0x400006bdb0 pc=0x50b4c
runtime.doInit(0xf62280)
	runtime/proc.go:5620 +0x58 fp=0x400006be30 sp=0x400006bdf0 pc=0x50b08
runtime.doInit(0xf5aca0)
	runtime/proc.go:5620 +0x58 fp=0x400006be70 sp=0x400006be30 pc=0x50b08
runtime.doInit(0xf5dee0)
	runtime/proc.go:5620 +0x58 fp=0x400006beb0 sp=0x400006be70 pc=0x50b08
runtime.doInit(0xf5dc40)
	runtime/proc.go:5620 +0x58 fp=0x400006bef0 sp=0x400006beb0 pc=0x50b08
runtime.doInit(0xf63aa0)
	runtime/proc.go:5620 +0x58 fp=0x400006bf30 sp=0x400006bef0 pc=0x50b08
runtime.doInit(0xf5b420)
	runtime/proc.go:5620 +0x58 fp=0x400006bf70 sp=0x400006bf30 pc=0x50b08
runtime.main()
	runtime/proc.go:191 +0x1b8 fp=0x400006bfd0 sp=0x400006bf70 pc=0x439c8
runtime.goexit()
	runtime/asm_arm64.s:1136 +0x4 fp=0x400006bfd0 sp=0x400006bfd0 pc=0x72e34

r0      0x1
r1      0x400006a3a0
r2      0x400006bd70
r3      0x40000938f0
r4      0xa81ec0
r5      0xd458
r6      0x1000
r7      0x6
r8      0xf9
r9      0x400009391f
r10     0x1000
r11     0x1
r12     0xa61624
r13     0x0
r14     0xf9
r15     0x0
r16     0x0
r17     0x6
r18     0x0
r19     0xf6a858
r20     0x400006bb10
r21     0x400006bc28
r22     0x4000002000
r23     0x0
r24     0x0
r25     0x0
r26     0xf556d8
r27     0xff7cb7
r28     0x4000000180
r29     0x400006bd48
lr      0x442ee0
sp      0x400006bd50
pc      0x4436c0
fault   0x0

下面是v2ray那边负责人rprx的说法：
原因是 XTLS 用的 copy go 1.15.2 的 cpu 换成了 x/sys/cpu（标准做法）

根据 TG 上的反馈，该 CPU 上 termux 直接运行 v2ray-core v4.31.0 没有问题，但 magisk 有问题，所以建议给 magisk 提个 issue

**Comment by topjohnwu** [comment]
請開發者跟我說問題出在哪裡，你 post 這個 log trace 只是顯示 illegal instruction，是 machine code 的問題
