### ISSUE TITLE
No Preserve dm-verity option in 8.0.2 version

### ISSUE THREAD

**Issue by z826540272** [topjohnwu/Magisk#3327]
whats going on，
I cant modify the vendor partation because it lacking keep dm-verify option when install.

**Comment by z826540272** [comment]
after i flash my custom vbmeta. i can modify the vendor.
but it lacking of magisk manager support

**Comment by topjohnwu** [comment]
It is no longer available for normal SAR devices because patching AVB can cause bootloop on several devices. If you need it, you can always manually patch it (just like what you did here)
