### ISSUE TITLE
FEATURE REQUEST: NEED FILE ASSOCIATION FOR .zio FILES

### ISSUE THREAD

**Issue by Mikesew1320** [topjohnwu/Magisk#3330]
Can you add .zip file association or Magisk manager pls? So we don't need to open Magisk manager whenever we need to install a new module.

I mean, When we click .zip fron any fike manager app, there is Magisk manager in the list and we can choose it if it's a Magisk modules and we need to install it.

This saves a lot more time.

**Comment by topjohnwu** [comment]
This opens up a possibility to detect Magisk Manager, so nope, won't happen
