### ISSUE TITLE
How to replace and call the original file?

### ISSUE THREAD

**Issue by gam2046** [topjohnwu/Magisk#3332]
I have written `A2.so` to replace `A1.so` which comes with the system, but A2 needs to call the method of A1. The implementation of A1 of different devices may be inconsistent, but they all have consistent and common methods.

Therefore, how to access the original A1 file while providing A1 is like A2 is a **stub**.

**Comment by RikkaW** [comment]
Make a copy `A1.so` with some other name in `post-fs-data.sh`, the use the copy in `A2.so`.
