### ISSUE TITLE
How Keep Modules When Factory reset.

### ISSUE THREAD

**Issue by Kev1nKe** [topjohnwu/Magisk#3333]
when i factory reset all of mine installed modules all gone so is there any way to keep /data/adb/modules when factory reset it happens.

**Comment by Kev1nKe** [comment]
Some one who can help me to solve it I really appreciate!

**Comment by DanGLES3** [comment]
that's just not feasible, for that to happen the modules would have to be stored in some other partition, and there isn't any other widely avaliable partition with plenty of space like data (writing to system/vendor is out of question), the best solution would be to just use TWRP's file manager to copy the modules folders to an sdcard before factory resetting

**Comment by TheShanMan** [comment]
Related question: I have fairly extensive mods via several magisk modules, and I want them to run on the first boot after a factory reset. Could I just zip /data/adb/modules and then flash it from twrp immediately following a factory reset? Would the modules run on first boot even though (I assume) I'd still have to install the magisk app after booting back up?

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 06/09/2022, 09:16, ***@***.*** wrote:Related question: I have fairly extensive mods via several magisk modules, and I want them to run on the first boot after a factory reset. Could I just zip /data/adb/modules and then flash it from twrp immediately following a factory reset? Would the modules run on first boot even though (I assume) I'd still have to install the magisk app after booting back up?

**Comment by DanGLES3** [comment]
> Related question: I have fairly extensive mods via several magisk modules, and I want them to run on the first boot after a factory reset. Could I just zip /data/adb/modules and then flash it from twrp immediately following a factory reset? Would the modules run on first boot even though (I assume) I'd still have to install the magisk app after booting back up?

Not sure if that's feasible tbh, can't really help you much on that

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 06/09/2022, 09:23, ***@***.*** wrote:
Related question: I have fairly extensive mods via several magisk modules, and I want them to run on the first boot after a factory reset. Could I just zip /data/adb/modules and then flash it from twrp immediately following a factory reset? Would the modules run on first boot even though (I assume) I'd still have to install the magisk app after booting back up?

Not sure if that's feasible tbh, can't really help you much on that
