### ISSUE TITLE
MagiskHide does not list a particular app

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#3336]
On MIUI, there is a stock app Security and it finds the root
![IMG_20201013_180435](https://user-images.githubusercontent.com/51943147/95889028-328dde80-0d82-11eb-8fca-a51ba0a7994d.jpg)
![IMG_20201013_180655](https://user-images.githubusercontent.com/51943147/95888942-10945c00-0d82-11eb-9bdd-a931c446c7f1.jpg)

However, I want to enable Magisk Hide for that app, but cannot find it there even I enable Show system apps.
When I search for e.g. secu, it lists even some services with security in the package name, but not the Security app:
![IMG_20201013_180753](https://user-images.githubusercontent.com/51943147/95889009-286be000-0d82-11eb-8269-4d3d4a86002b.jpg)
![IMG_20201013_180942](https://user-images.githubusercontent.com/51943147/95888913-02ded680-0d82-11eb-88fd-c59f1ca7a278.jpg)

Btw, Security is /data/user/0 app
![IMG_20201013_183626](https://user-images.githubusercontent.com/51943147/95889890-556cc280-0d83-11eb-9d1a-804fc600dd86.jpg)

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/commit/fd552e68a9b3a5056dbe9abd4566dff78cdb3558
If  uid < 10000, they are **truly** privileged applications and are closely related to system stability. I don't think MagiskHide can prevent their detection. This application does not use any privileges, it just checks whether the `su` file exists?

**Comment by zgfg** [comment]
> [fd552e6](https://github.com/topjohnwu/Magisk/commit/fd552e68a9b3a5056dbe9abd4566dff78cdb3558)
> If uid < 10000, they are **truly** privileged applications and are closely related to system stability. I don't think MagiskHide can prevent their detection. This application does not use any privileges, it just checks whether the `su` file exists?
I didn't say it is UID=0 app, but a regular app that is not installed for user 999

All system and user apps (Magisk Hide correctly finds them) have their data folder at /data/user/0 which is actually mounted to /data/data

When you have a dual app, I have WhatsApp, then one its data folder is regularly (like all other apps) at /data/user/0=/data/data, and its dual/second instance (WhatsApp account corresponding to my second SIM) keeps its data at /data/user/999
![Screenshot_2020-10-13-19-36-27-757_com mixplorer](https://user-images.githubusercontent.com/51943147/95897132-50ad0c00-0d8d-11eb-8d73-1c09c46a175a.jpg)

Regarding to that Security app, it looks for various issues like viruses (AVL or Avast), which apps are exempted from Battery optiization, which apps are listed for autostart, which apps used battery a lot,  are there instslled apps that are rarely used, Cache and other files that can be deleted - hence lthe root is just one issue it looks for

**Comment by RikkaW** [comment]
@zgfg Android's user id (what you say) and Linux's uid (what @vvb2060 say) are two different things. The changes from @vvb2060 hide all apps which Linux uid below 10000. In your case, "Security" should be an app with Linux uid below 10000.

**Comment by zgfg** [comment]
> @zgfg Android's user id (what you say) and Linux's uid (what @vvb2060 say) are two different things. The changes from @vvb2060 hide all apps which Linux uid below 10000. In your case, "Security" should be an app with Linux uid below 10000.

'All normal' apps (963 or so in my case) have data folders at /data/user/0=/data/data, like YouTube, Magisk Manager, GMaps, you name it, and that Security app

Once again, /data/user/0 is mounted to /data/data, nothing else


Should I make 963 screenshots showing how all those apps have their data at /data/user/0= /data/data to prove that it is 'normal' app

Btw, if you navigate on your phone to /data/user/0, don't you see that it opens /data/data where all your (not dual instances of apos like WhatsApp, Terminal, Skype) have their data folders?

**Comment by zgfg** [comment]
This issue is just a follow app on discussion from XDA.
The another Xiaom user was able to see that the same Security app (and hide the root from) with Magisk Manager 7.5.1, but now he cannot anymore with Manager 8.0.2 - same app, he just updated the Magisk Manager and lost this app from Magisk Hide list
https://forum.xda-developers.com/showpost.php?p=83700349&postcount=42087

**Comment by zgfg** [comment]
Probably the answer is really in UID. Looking to his 2nd screensot, Security app runs under UID=1000, unlike the other apps that run under UID=10036

It means it was changed since Manager 7.5.1 - then Manager was showing this app in the Magisk Hide list. Maybe some new intensions - but with that older Manager it is possible to hide the root from that app

**Comment by zgfg** [comment]
Yeah. Canary Manager 310 doesn't show Security app in the list (Show system apps enabled, searching for secu finds nothing) and that Security app finds the root

I downgraded from Magisk Canary 21004 to Stable 20400 to be able to downgrade also from Canary Manager 310 to Stable 7.5.1 267

And indeed, old Manager then shows Security app in the Magisk hide list and when I enabled, Security app could no more find the root
![IMG_20201015_211057](https://user-images.githubusercontent.com/51943147/96176396-97853800-0f2c-11eb-9ceb-44aabf8888ae.jpg)

Then updated back to Magisk 24004, leaving Manager 7.5.1 - Magisk hide was still showing Security app in the list and hiding still worked

Finally I upated Manager back to 310, it does no more show Security app in the list, but the app still cannot find root because hiding from that app was remembered in DB

Hence it is nothing about UID (heavy artillery), just some "cosmetics' (?) in the newly redesigned Managers (8.5.2 or Canary) that they don't want to show Security app, although hiding from that app still works when it was pre-set by the old Manager

**Comment by vvb2060** [comment]
For security, apps with UID < 10000 are not displayed, but you can always use the `magiskhide` command to add the app you want to hide, provided you know what you are doing.

**Comment by zgfg** [comment]
Ok, you mean:
![Uploading Screenshot_2020-10-15-22-50-26-964_com.offsec.nhterm.jpg…]()

**Comment by zgfg** [comment]
Not happy (IMO, UI should be to make things easier for users, specially when something already worked and now is just restricted in the UI, but now will close
