### ISSUE TITLE
magisk v13 magisk manager FC on S5 G900H WANTED ROM

### ISSUE THREAD

**Issue by Asuly** [topjohnwu/Magisk#334]
magisk v13.3
magisk manger 5.1.1
 S5 G900H WANTED ROM
still giving me fc after 10 seconds of launching the app.

**Comment by Didgeridoohan** [comment]
[Logs](https://www.xda-developers.com/guide-sending-a-logcat-to-help-debug-your-favorite-app/) or it didn't happen.
