### ISSUE TITLE
随机包名隐藏 能不能选择旧版

### ISSUE THREAD

**Issue by AlliotTech** [topjohnwu/Magisk#3342]
先前是旧版，最近刷机刷了旧版，重新去随机包名隐藏的时候，会自动更新到最新版。  并且没有图标（是安卓APP的默认图标）  

已经路由器上全局代理，并且自定义通道也配了旧版的json。。。

**Comment by JasonKhew96** [comment]
> ...并且没有图标（是安卓APP的默认图标）...

https://topjohnwu.github.io/Magisk/faq.html#q-after-i-hidden-magisk-manager-the-app-icon-is-broken

**Comment by AlliotTech** [comment]
> > ...并且没有图标（是安卓APP的默认图标）...
> 
> https://topjohnwu.github.io/Magisk/faq.html#q-after-i-hidden-magisk-manager-the-app-icon-is-broken

感谢回复  这个看过了  其实主要的问题还是 怎样让随机包名隐藏不自动升级到最新版。。。 最新版还是有些小问题的。
原本打算卸载magisk manager然后pull项目来手动编译一个其他包名的  但是看到您上面的说的 貌似不太可行。  

我今天尝试想抓一下隐藏后自动下载的接口，路由到自己想要的版本的，但没有抓到23333

**Comment by vvb2060** [comment]
#3282 等这个PR实装，就是你要求的功能
