### ISSUE TITLE
Magisk does not work on Cyanogenmod 12.1 (Android 5.1.1)

### ISSUE THREAD

**Issue by ShevT** [topjohnwu/Magisk#335]
The latest working version of Magisk for Cyanogenmod 12.1 (Android 5.1.1) - v13.0 (0b4baad)
All versions that were released later do not work. The launcher reloads cyclically.
If I try to run MagiskManager, then my phone go reboot.
If I delete only MagiskManager, then problems with the system disappear.

[magisk_debug.zip](https://github.com/topjohnwu/Magisk/files/1223149/magisk_debug.zip)

**Comment by Haxk20** [comment]
have the same issue and even one bigger that magisk installs but after reboot to system kernel doesnt load up.

**Comment by Haxk20** [comment]
Well for me this version dont flash and says i need to use Bootbridge but when i use it bootbridge failed with ERROR 7

**Comment by TheComputerGuy96** [comment]
@Haxk20 What's your device and ROM?
