### ISSUE TITLE
MagiskHide applications very slow

### ISSUE THREAD

**Issue by eblis** [topjohnwu/Magisk#3352]
I've enabled Magisk Hide for some applications that don't want to run if root is found on the device and I noticed that those apps have started running **very** slowly since the last couple of Magisk updates.
I don't remember when the slowness has started, but it's been a couple of Magisk releases for sure.
The applications that I've experienced slowdowns include:
* Revolut
* ING Homebank
* Phone

The worst one by far in terms of slowness is Revolut, it's barely running, I have to click a button and wait 2-3 seconds before the application registers my click. If I remove Revolut from the MagiskHide list then everything starts running smoothly again.

**Comment by KevinMX** [comment]
Some issues that might be related:
#3214 https://github.com/skittles9823/QuickSwitch/issues/7 https://github.com/skittles9823/QuickSwitch/issues/15

IDK if you're using QuickSwitch, but this should be a Magisk Hide bug, according to @skittles9823 , and it's not solved, yet.

I think my previous issue should be reopened... I don't really have much time to test, you can enable Magisk Hide to an app, launch it, and see if the RAM usage of this app is abnormal. For my phone it just went out of memory, I think your slow downs might be the same issue.

**Comment by eblis** [comment]
Wow, thank you very much.
I uninstalled QuickSwitch (had it installed but wasn't really using it as it doesn't work with the Play version of Lawnchair) and now the apps are working smoothly again.

Unfortunately Youtube Vanced (installed by Vanced manager) is now gone and I cannot install it again ... I guess that's another rabbit hole I need to go down into.

**Comment by skittles9823** [comment]
Yea unfortunately with the nature of magisk hide, some issues like this happen, I'm not sure how much John has looked into it, but I've personally never had issues on my Pixel or Nexus devices, custom rom or stock.
