### ISSUE TITLE
Magiskhide no longer works for my homebank c6 bank

### ISSUE THREAD

**Issue by whoamikyo** [topjohnwu/Magisk#3354]
after my bank app updating the magiskhide doesn't work anymore, is there anything that can be done about it?

here the apk: https://apps.evozi.com/apk-downloader/?id=com.c6bank.app

thanks.

**Comment by techIndia-hacker** [comment]
I have tested this app. And really amazed to see how this detect root. They must have found some new technique and it's going to spread into other apps soon. It's bad.

App says "its not a physical device"

Phone - oneplus 8 pro
Android 10 still
Magisk manger 8.0.2
Magisk v20.4

**Comment by Nottt** [comment]
I'm also having the same issue. It's a shame we can't talk about magisk hide here. Then where it's the right place?

The app was working for ages, then suddenly stopped working

**Comment by techIndia-hacker** [comment]
Which device u have?

**Comment by Nottt** [comment]
I'm using a motorola g8 plus android 9. I didn't do anything and the app just stopped working. So it's not like I did something wrong

**Comment by whoamikyo** [comment]
> I'm also having the same issue. It's a shame we can't talk about magisk hide here. Then where it's the right place?
> 
> The app was working for ages, then suddenly stopped working

same app?

**Comment by techIndia-hacker** [comment]
Whats ur widewine status guys?

**Comment by Nottt** [comment]
https://play.google.com/store/apps/details?id=com.c6bank.app

This app

**Comment by Nottt** [comment]
What do you mean what is your widevine status?

**Comment by techIndia-hacker** [comment]
> What do you mean what is your widevine status?

L1 or L3?

**Comment by Nottt** [comment]
I don't know

**Comment by techIndia-hacker** [comment]
See the thing is @topjohnwu  said if u yourselves can find the way this app is detecting root then he is more than happy to fix it. But he does not have the time to implement fixes for each and every app out there. So, learn up how magisk works and do some work about it's detecting root. Use httpcanary app to monitor is network activities. Do some work urselves and display them here. Hopefully 
 @topjohnwu will see it

**Comment by Nottt** [comment]
Give me instructions in how to do it and i will do it

**Comment by techIndia-hacker** [comment]
Use httpcanary app with root to monitor its network activities and find out which domains it's visiting.

**Comment by Nottt** [comment]
What domains have to do with the root checking?

**Comment by prschopf** [comment]
Im having the same issue here with C6 Bank app:

Motorola Z XT1650-3
Lineage 17.1
Magisk 21.0
Magisk Manager 8.0.2
Magisk Hide enabled
Magisk name changed to "Gerenciador"
Edit device fingerprint enabled (to POCO F2 Pro Global)
Force BASIC key attestation enabled (to POCO F2 Pro Global)

After last app update, its not working anymore.

**Comment by whoamikyo** [comment]
this is sad, for now i have uninstalled magisk 😒

**Comment by prschopf** [comment]
Im still using Magisk but I gave up to use C6 Bank. Im using Banco Inter and Banco Next instead.

**Comment by prschopf** [comment]
Solved! Solution here: https://www.nextpit.com.br/forum/766179/poblema-com-apps-de-banco-plus-root-plus-custom-rom/page/4#3372628

**Comment by whoamikyo** [comment]
> Solved! Solution here: https://www.nextpit.com.br/forum/766179/poblema-com-apps-de-banco-plus-root-plus-custom-rom/page/4#3372628


Thanks, works for me too!

**Comment by Nottt** [comment]
Works for me too! great work

**Comment by prschopf** [comment]
Its not working anymore. Now, it asks for an upgrade but there is no available upgrade.

**Comment by prschopf** [comment]
I had to disable service "nj.Y" in C6 Bank app version 2.30.1 (15/11/2020)

**Comment by leonardoph2** [comment]
Hi! After latest update of C6 Bank, it has started getting root detected again. Any kind of solution?

**Comment by prschopf** [comment]
New solution is here: https://www.nextpit.com.br/forum/766179/poblema-com-apps-de-banco-plus-root-plus-custom-rom/page/6#3386133

**Comment by clinger-jr** [comment]
Solution doesn't work.

This issue exists, no Magisk Hide feature is effective (and it is highly wanted that it should).

**Comment by androidacy** [comment]
In case you haven't noticed, magiskhide is no longer a top priority. You're better off keeping a second cheap device to bank on, keeping it fully oem locked.

**Comment by prschopf** [comment]
There are more solutions here: https://www.nextpit.com.br/forum/766179/poblema-com-apps-de-banco-plus-root-plus-custom-rom/page/3#3392023

**Comment by clinger-jr** [comment]
they were tried and don't work on latest app version.

Thank you.

**Comment by 12heleno** [comment]
the app again blocked root access, could someone help me 😥 help

**Comment by prschopf** [comment]
Its still working for me, take a look: https://www.nextpit.com.br/forum/766179/poblema-com-apps-de-banco-plus-root-plus-custom-rom/page/4#3406698

**Comment by marquesinii** [comment]
It started to detect root even with riru unshare v2.0

The C6 devs are really wanting to block rooted devices...

**Comment by lcsvcn** [comment]
> Whats ur widevine status guys?

Mine is L1.

In order to check this guys, download com.liuzh.deviceinfo (AKA: Device Info) from play store, go to SYSTEM tab and then scroll to DRM content.

I am running:
- MagiskHide Props Config: v5.4.1
- Riru v26.1.1.r500
- Riru Enhanced Mode For Magisk Hide v2.0
- Universal SafetyNet Fix - v1.2.0
- MagiskHide is enabled and Magisk Manager is renamed (to avoid app seeing it installed)

Only C6 bank app is not working. (Any other banking app works properly)

**Comment by prschopf** [comment]
Its working fine for me using these:

MagiskHide Props Config: v5.4.1-v131
Riru v26.1.1.r500
Riru Enhanced Mode For Magisk Hide v2.0
MagiskHide is enabled and Magisk Manager is renamed (to avoid app seeing it installed)
Magisk 23.0
Magisk App 23.0
It passes ok in SafetyNet

In MagiskHide, check twice:
All processes are checked within C6 Bank.
Only check "com.google.android.gms.unstable" in Google Play Services.

Clear C6 Bank cache and data, in Android Settings/Apps

Using this configuration, I only some issues with Picpay. I have to try to open it 3 or 4 times before it really opens.

**Comment by Matheus2212** [comment]
Case someone is searching for a solution in almost end-year (2022), C6 had another update and all listed past methods no longer works.

**Comment by Matheus2212** [comment]
@androidacy-user oh sorry then. I'm having a hardtime finding a solution for the specific app on the original comment. Any recommendation is welcome. 

By the way, thanks.

**Comment by prschopf** [comment]
In Magisk, go to "Configurations" and "Configure Deny List".

**Comment by glaucoqs** [comment]
> In Magisk, go to "Configurations" and "Configure Deny List".

Dont worked...
