### ISSUE TITLE
MagiskManager "direct install" after OTA does not work

### ISSUE THREAD

**Issue by knox** [topjohnwu/Magisk#3356]
I've just applied another OTA update of latest official LineageOS 17.1 onto my Pixel 3 and as usual i went to MagiskManager afterwards to re-install Magisk. In the new MagiskManager 8 i could not find an explicit option to "install after OTA" so i've tried "direct install". But after reboot Magisk was gone and i had to re-install it via fastboot.

As it seems to me MagiskManager 8.0.2 failed to install into the right partition. This used to work seamlessly for me with the older MagiskManager 7.

**Comment by topjohnwu** [comment]
Install after OTA is removed for all Google devices for now (due to GMS OTAs has changed)
