### ISSUE TITLE
Error building Magisk from source

### ISSUE THREAD

**Issue by ZChuckMoris** [topjohnwu/Magisk#3357]
Downloaded magisk repo recursively, installed Android SDK through android-studio, already have set PATH and ANDROID_HOME, configure config.prop, but nothing works. I don't get it: what am i doing wrong?

```
$ ./build.py all

* Building Magisk Manager stub


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':native'.
> com.android.builder.sdk.LicenceNotAcceptedException: Failed to install the following Android SDK packages as some licences have not been accepted.
     ndk;21.1.6352462 NDK (Side by side) 21.1.6352462
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /home/moris/Magisk/Android-SDK

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Build stub failed!

```

**Comment by ZChuckMoris** [comment]
Installed Android NDK from Android Studio. Now i am getting next error:
```* Building Magisk Manager

ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1
Output: out/app-debug.apk

Traceback (most recent call last):
  File "./build.py", line 628, in <module>
    args.func(args)
  File "./build.py", line 567, in build_all
    build_binary(args)
  File "./build.py", line 287, in build_binary
    props = parse_props(op.join(ndk_path, 'source.properties'))
  File "./build.py", line 125, in parse_props
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/moris/Magisk/Android-SDK/ndk/magisk/source.properties'```

**Comment by ZChuckMoris** [comment]
removed Android NDK from Android Studio SDK Manager and installed it again, using `./build.py ndk`
Finally, built magisk successfully

**Comment by Sahil12524** [comment]
Hello Bro,
please can you help me too to fix that same exact error, i am about to build the same apk but with some modification for my Samsung Galaxy M12

**Comment by nullNullNone** [comment]
on a linux server without android studio

**Comment by nullNullNone** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Failed to install the following Android SDK packages as some licences have not been accepted.
        build-tools;34.0.0 Android SDK Build-Tools 34
        platforms;android-34 Android SDK Platform 34
     To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
     All licenses can be accepted using the sdkmanager command line tool:
     sdkmanager.bat --licenses
     Or, to transfer the license agreements from one workstation to another, see https://developer.android.com/studio/intro/update.html#download-with-gradle
     
     Using Android SDK: /home/asdfghijk2021

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s

! Build app failed!

**Comment by nullNullNone** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Failed to install the following Android SDK packages as some licences have not been accepted.
        build-tools;34.0.0 Android SDK Build-Tools 34
        platforms;android-34 Android SDK Platform 34
     To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
     All licenses can be accepted using the sdkmanager command line tool:
     sdkmanager.bat --licenses
     Or, to transfer the license agreements from one workstation to another, see https://developer.android.com/studio/intro/update.html#download-with-gradle

**Comment by DocMAX** [comment]
me too
```
* Building the Magisk app

Checking the license for package Android SDK Build-Tools 34 in /home/docmax/opt/cmdline-tools/licenses
License for package Android SDK Build-Tools 34 accepted.
Preparing "Install Android SDK Build-Tools 34 v.34.0.0".
"Install Android SDK Build-Tools 34 v.34.0.0" ready.
Installing Android SDK Build-Tools 34 in /home/docmax/opt/cmdline-tools/build-tools/34.0.0
"Install Android SDK Build-Tools 34 v.34.0.0" complete.
"Install Android SDK Build-Tools 34 v.34.0.0" finished.
Checking the license for package Android SDK Platform 34 in /home/docmax/opt/cmdline-tools/licenses
License for package Android SDK Platform 34 accepted.
Preparing "Install Android SDK Platform 34 (revision 2)".
"Install Android SDK Platform 34 (revision 2)" ready.
Installing Android SDK Platform 34 in /home/docmax/opt/cmdline-tools/platforms/android-34
"Install Android SDK Platform 34 (revision 2)" complete.
"Install Android SDK Platform 34 (revision 2)" finished.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Failed to find target with hash string 'android-34' in: /home/docmax/opt/cmdline-tools

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 23s
5 actionable tasks: 1 executed, 4 up-to-date

! Build app failed!

```

**Comment by DocMAX** [comment]
OK, doesn't work with cmd tools. You need Android Studio.
Build sucessfull.

**Comment by DocMAX** [comment]
Ok but after installing app-debug.apk when i open Magisk it imedatelly uninstalls and downloads Magisk from the internet. Wtf??
