### ISSUE TITLE
It doesn't find boot on x86 Asus ZE500CL (Z00D) running Lineage (LOS)

### ISSUE THREAD

**Issue by euleralves** [topjohnwu/Magisk#336]
Lineage is working great on Asus ZE500CL (Z00D) using lineage-14.1-20170812-nightly-Z00D-signed.zip  (https://download.lineageos.org/Z00D) but Magisk

I'd tried last Magisk 13.3 and its last beta 13.6 on TWRP 3.0 , 3.1 and 3.1.1 (everything else worked on these TWRP). I got "Unable to detect boot image".

I'd tried Magisk installation by ADB (https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445/)  but I got "Access denied /dev/temp" with Magisk 13.3 and "No boot image magic found!" with 13.6

If I try SuperSU 2.8 SR3, I get something alike: "Boot image: not found"

[boot.zip](https://github.com/topjohnwu/Magisk/files/1232902/boot.zip)
[dmesg.zip](https://github.com/topjohnwu/Magisk/files/1232907/dmesg.zip)
[recovery.zip](https://github.com/topjohnwu/Magisk/files/1232908/recovery.zip)

**Comment by mrkash69-the2nd** [comment]
was there a way to fix it or what
