### ISSUE TITLE
MagiskHide Repackaged and LuckyPatcher

### ISSUE THREAD

**Issue by KeerthanGopi** [topjohnwu/Magisk#3361]
Device: OnePlus 6
OS: OxygenOS (10.3.6)
Magisk Canary Version: 872c5520 (21004)
Magisk Manager Version: 339ca6d6c (310) (11)

MagiskHide crashes when repacked and also trips safetynet similair to #3276 
Lucky patcher also loses its root privileges and the root prompt doesnt come again.

Unfiltered Log: 
[Magisk-log.txt](https://github.com/topjohnwu/Magisk/files/5395321/Magisk-log.txt)

Edit: Issue still persist on the latest Magisk Manager and Magisk Canary.

**Comment by lss4** [comment]
It seems Magisk Manager 311 (13) can be repackaed just fine with 21004. However, I'm currently having issues with 21005. It just can't be installed.

Also, the crash issue seems to happen when both the original and hidden Magisk Manager are present (which was my case when testing the 21005), see #3383 that I just posted.

I'm not sure about Safety Net though, as I'm using microG without DroidGuard helper installed. It's not really reliable, but I personally don't really care about Safety Net anymore.

Not sure which version of Lucky Patcher you're using, but be sure to use the recent versions that repacks itself post-install. Older versions that used a known package name will certainly trip some app's environment checks even if it doesn't trip Safety Net, given its dubious nature.

**Comment by KeerthanGopi** [comment]
After a clean install of OxygenOS, magisk manager and magisk hide seems to be working fine. Even lucky patcher detects root.
