### ISSUE TITLE
Google Pixel 5 stuck on boot with repacked magisk boot image 

### ISSUE THREAD

**Issue by NAV-Management** [topjohnwu/Magisk#3362]
Hello everyone,

since yesterday I own the google pixel 5. since I like to use the cell phone only with root, I checked at xda if there is already something there.

The xda members have already created magisk patched boot images.  If these boot images were flashed with fastboot, the phone hangs up directly at startup.

I tried it myself then. First download the original rom and extract the boot image from it. Then patch the boot image with the Magisk Manager Canary Build.

After the patched boot image was flashed with fastboot, the pixel 5 hung up during the startup process.

Unfortunately it is not possible at this time that the pixel 5 is recognized in Windows and the log data is retrieved via ADB.

The only log data I got is the log for creating the patched boot image.
The other log I got is the Logcat.log, which was created after flashing the stock boot image and the pixel 5 was recognized in Windows.

Unfortunately there is currently no recovery (TWRP) for pixel 5, so I can't query the log data in TWRP to identify why the phone won't start.

Attached are the log data from Logcat.log and from creating the patched boot.img

[magisk_install_log_2020-10-17T01_01_51Z.log](https://github.com/topjohnwu/Magisk/files/5395523/magisk_install_log_2020-10-17T01_01_51Z.log)
[logcat.log](https://github.com/topjohnwu/Magisk/files/5395524/logcat.log)

**Comment by topjohnwu** [comment]
Please try out the latest canary that I just released, it should fix the issue

**Comment by silleftw** [comment]
root does now work, thank you john, but wifi is broken after patching the img.

**Comment by NAV-Management** [comment]
With magisk Build 210005 it boots up, root works and Wifi aswell.
