### ISSUE TITLE
Can't mount /system rw on magisk 20.4, Android 10

### ISSUE THREAD

**Issue by fusionneur** [topjohnwu/Magisk#3365]
Related: #1936 

OnePlus7TPro:/ # mount -o rw,remount /sbin/.magisk/mirror/system_root
'/sbin/.magisk/block/system_root' is read-only

Which is the correct way to allow write on /system/etc/selinux, for example? I suppose the equivalent for magisk is : /sbin/.magisk/mirror/vendor/etc/selinux/, but I am not sure.

**Comment by fusionneur** [comment]
Sorry, why did you close it as invalid?

**Comment by osm0sis** [comment]
v21 is the latest stable and there are newer canaries still.

**Comment by fusionneur** [comment]
ok going for the beta. thanks
