### ISSUE TITLE
Since when .core/props/ files won't be loaded?

### ISSUE THREAD

**Issue by wuchjun** [topjohnwu/Magisk#337]
It is a bug? Or since when this mode has been cancelled？And why to create this folder?

**Comment by DeicPro** [comment]
If not works then is a bug in your ROM. Have to properly report this, check the Magisk beta thread to know how to.

**Comment by wuchjun** [comment]
@DeicPro All are fine except loading from .core/props/. The props can be changed with a Magisk module or with boot script and the resetprop tool. And then I can't find any support that .core/props/ will be loaded in boot stages from the official Magisk documentation on Github and XDA GUIDE thread.

**Comment by Zackptg5** [comment]
I can confirm this too. I've tried on multiple roms and .core/props do not load. They've never loaded as far as I can remember through all of the older magisk versions that had it

**Comment by DeicPro** [comment]
Are you set 755 rwxr-xr-x permissions?

**Comment by Zackptg5** [comment]
In case anyone was wondering, changing permissions doesn't fix it either.
