### ISSUE TITLE
Pixel 3a XL / patching boot.img: unsupported/unknown image format

### ISSUE THREAD

**Issue by Malvineous** [topjohnwu/Magisk#3370]
Hi all,

Is patching of the Pixel 3a XL boot image supported?  I can see some issues here where people are saying they have patched it and had problems, but when I try to patch it I get the error `Unsupported/Unknown image format`.

I had a look in the code, and in magiskboot's [check_fmt()](https://github.com/topjohnwu/Magisk/blob/f3cd4da0264a9e31e403bddc0143a4548968e95c/native/jni/magiskboot/format.cpp#L26) it doesn't appear to look for the "FBPK" header in the 3aXL boot image.

![pixel3axl-bootimg-hex](https://user-images.githubusercontent.com/171656/96404896-63a55d80-121f-11eb-9f50-875e8eaff72a.png)

This was with the latest Android 11 factory image, so I went back to an old Android 9 factory image but the boot image is in the same format and also fails patching, so does this mean the 3aXL boot image format has never been supported?

I am a bit confused because I tried patching an old image from an unrelated device that had a `BOOTLDR!` signature instead and that unpacked successfully (but couldn't be repacked) although I could not see any code that looked for the `BOOTLDR!` signature either.  So I'm not sure if I'm looking in the wrong spot or just misunderstanding how the file formats are identified.

**Comment by shmshd** [comment]
So, it could probably not be the issue with Magisk. My Pixel 4 XL running Android 11 is rooted without any issue. 

Could you elaborate the issue in more detail by explaining the methods you've done?

**Comment by Malvineous** [comment]
Thanks for the reply.  I sideloaded the Magisk app, went to the install option, and it asked for a bootloader file to patch.  I gave it the bootloader .img I extracted from the factory firmware image, but that's when it said the file was in an unknown image format.

Did you install Magisk on your 4XL by patching the bootloader?

**Comment by shmshd** [comment]
> Thanks for the reply. I sideloaded the Magisk app, went to the install option, and it asked for a bootloader file to patch. I gave it the bootloader .img I extracted from the factory firmware image, but that's when it said the file was in an unknown image format.
> 
> Did you install Magisk on your 4XL by patching the bootloader?

there you made the mistake. Its not `bootloader.img`, it is `boot.img`

**Comment by Malvineous** [comment]
These are the files in the factory firmware image, are you saying the bootloader one is not the correct one?
```
bootloader-bonito-b4s4-0.3-6622442.img
flash-all.bat
flash-all.sh
flash-base.sh
image-bonito-rp1a.201005.004.zip
radio-bonito-g670-00067-200702-b-6648702.img
```

**Comment by shmshd** [comment]
> image-bonito-rp1a.201005.004.zip

Unzip the `image-bonito-rp1a.201005.004.zip` to get the `boot.img` file. This is not the place to ask for guidance. Please do some research before you jump into these kind of tasks. If you don't know what you are doing then you may brick your device.

**Comment by Malvineous** [comment]
Yep, that's what it was, my bad!  Unzipping the image.zip and using `boot.img` contained within that worked.  So sorry for the mistake!  Many thanks @shmshd for your help :)

**Comment by Malvineous** [comment]
No I wasn't asking for guidance, but I wasn't sure if my device was supported or not given the error.  There are unfortunately a lot of conflicting instructions so it's a bit difficult to know which ones actually work.  Now I know my device is supported it's all good.
