### ISSUE TITLE
Feature request - disable all modules if a system can't boot

### ISSUE THREAD

**Issue by avently** [topjohnwu/Magisk#338]
I searched for similar issues but couldn't find anything like this. 
Sometimes after installing modules system can't boot. It's really bad situation because it's not easy to fix without access to file manager in OS. 
What if you just disable all modules if you get to know that system can't boot? For example, I turning phone on and I see that system is stuck on logo. Magisk should somehow understand the situation and save the info to a file. After restart all modules should be disabled but /magisk folder mounted. 
What do you think? Is it real?

**Comment by mpqo** [comment]
A simple and effective approach is to make magisk look for a file named "magisk.nomodules" in external sdcard and in internal memory.

For example, a module prevent you from booting, you enter recovery and though adb or terminal "touch /sdcard/magisk.nomodule" and reboot.

:)

@topjohnwu what do you think?
