### ISSUE TITLE
Overwrite boot or recovery partition.

### ISSUE THREAD

**Issue by Tristandemuijnck** [topjohnwu/Magisk#3381]
My phone carrier told me to reset my phone to factory settings due to a non functional screen. I tried resetting the normal way however it didnt work. Then I tried flashing stock firmware and now i dont have any screen output so i think i bricked my s10+.
I have rooted my phone with magisk a couple months ago (system-as-root). So I think the issue is that i overwrote the boot or recovery partitions, as stated in the Additional notes section of the guide. ("Never, ever try to restore either boot or recovery partitions back to stock! You can easily brick your device by doing so, and the only way out is to do a full Odin restore with data wipe.")

My question is, how do I do this full odin restore with data wipe? Do you mean just flashing stock firmware?

**Comment by topjohnwu** [comment]
Flash full ODIN firmware with CSC (not HOME_CSC), it will wipe everything
