### ISSUE TITLE
Arrays in Module scripts not supported?

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#3388]
I tried to use an array in the customize.sh script but found the Magisk Installer failing.
Destilled down to a bare bone example:

--------------
# customize.sh
#
#myList=""
myList="abc 1.2.3  Pq-r_s"
#
# Magisk Module Installer fails here, converting both an empty or not list:
myArray=( $myList )
#myArray=( "a1" "__6P" )
#
echo Done
--------------

**Log:**
- Copying zip to temp directory
- Installing debloat.zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
*********
 debloat 
 by zgfg 
*********
*******************
 Powered by Magisk 
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
  inflating: module.prop
  inflating: README.md
update-binary: /data/adb/modules_update/debloat/customize.sh: line 7: syntax error: unexpected "("
*******************
- Extracting module files
! Installation failed
--------------

The same script executes just fine from a Terminal

If I understand correctly, Magisk Module Installer runs in ash shell, and ash does not support arrays?

In that case, I will go for a workaround...

**Comment by osm0sis** [comment]
There are plenty of options without using bashisms

https://unix.stackexchange.com/questions/384614/how-to-port-to-bash-style-arrays-to-ash
