### ISSUE TITLE
UI issues in Magisk Manager Canary 

### ISSUE THREAD

**Issue by pixincreate** [topjohnwu/Magisk#3389]
![Screenshot_2020-10-21-20-20-03-439_ hifcjc](https://user-images.githubusercontent.com/69745008/96738276-2c2fe000-13dc-11eb-92b3-54b591444c10.jpg)

If you look at the **top**(_in the status bar_), the Magisk Manager UI covers the whole status bar.

Along with that, Modules, that are installed on a device, show up again in the **Online Section** which is way more confusing.

**Comment by vvb2060** [comment]
#3358

**Comment by vvb2060** [comment]
Fixed
