### ISSUE TITLE
Phone rebooting into safe mode after rooting with Magisk

### ISSUE THREAD

**Issue by KirbyFan102** [topjohnwu/Magisk#3398]
My phone is the Samsung Galaxy M31, firmware version M315FXXU2ATIB, region ZTO. Someone's already posted a method to unlock the same phone in the xda-developers forum (https://forum.xda-developers.com/galaxy-m31/help/m31-root-method-t4172891), but I was unable to sucessfully root the phone with this. Every time, it keeps going back to safe mode. Am I forgetting something?
I've also tried the instructions on https://topjohnwu.github.io/Magisk/install.html, which also didn't work, giving me a vbmeta error. But at least that was _an_ error, now it's not telling me anything.

**Comment by topjohnwu** [comment]
Please ask for guides on XDA

**Comment by KirbyFan102** [comment]
Hold on, how is this question any different from something like https://github.com/topjohnwu/Magisk/issues/3231?
I'm not asking for a guide, I've read the guides. I'm asking for troubleshooting because the instructions I got didn't work, and I can't see any reason they wouldn't have.
