### ISSUE TITLE
Canary channel broken

### ISSUE THREAD

**Issue by Cyberavater** [topjohnwu/Magisk#3402]
Magisk canary channel showing the latest version  N/A. Opening module page, Magisk manager crashing.
[logcat_10-23-2020_13-23-29.txt](https://github.com/topjohnwu/Magisk/files/5427912/logcat_10-23-2020_13-23-29.txt)

**Comment by Didgeridoohan** [comment]
Make sure you have the Canary channel set, and not the custom channel with a URL.

Also make sure that the Manager has internet access and that nothing is blocking it.

Modules window crash is already fixed upstream (and is a sign that the Manager doesn't have internet access):
https://github.com/topjohnwu/Magisk/issues/3344

**Comment by Cyberavater** [comment]
1. Yes, I've set the channel to Canary and not to custom
2. I've internet connection in Magisk, everything works perfectly when I change the channel to stable or beta.

**Comment by slabua** [comment]
I can reproduce the issue too.

**Comment by Cyberavater** [comment]
Reinstall manager app. As, mine seems fixed after that.
