### ISSUE TITLE
Allow using Magisk Manager without internet connection

### ISSUE THREAD

**Issue by terryltoms** [topjohnwu/Magisk#3412]
Hi - in my opinion a great easy feature: 
Allow using the Magisk Managaer when Magisk zip file is already locally downloaded to phone, so **no need in internet connection**.

**Comment by zgfg** [comment]
AFAIK, you can flash Magisk zip from Manager's Module tab but with limitations:
- Only for direct update
I.e., you cannot patch an image, you can only take Direct install, and for that you ofc must already have root

But yes, the ability to also patch the image would be useful and great

**Comment by vvb2060** [comment]
https://github.com/vvb2060/Magisk/commit/9d033ac8807f7225ae85dac5b11ad64593fb1ea7 
Waiting for merge

**Comment by topjohnwu** [comment]
Addressed in latest canaries

**Comment by diabl0w** [comment]
there has been a regression where magisk manager no longer works without upgrading again
