### ISSUE TITLE
Can't boot to system with Magisk v21 installed

### ISSUE THREAD

**Issue by s3tupw1zard** [topjohnwu/Magisk#3413]
Hello,
I tried Magisk v21 with Atom OS v2.8 Android 11 ROM, but it reboots to Fastboot mode. Please fix this.

If you need any logs or kind of, please tell me where to get them.

regards

**Comment by s3tupw1zard** [comment]
P.S. my device is Redmi Note 8 ginkgo

**Comment by ad1tyas1ngh** [comment]
@topjohnwu I have a Realme 2 Pro. Same thing happens when flash Magisk v21 on my device. I can only use Magisk v21 on my device by first flashing a modded Magisk Canary File and then flashing v21 on top of it. It might have something to do with patching the boot image.

**Comment by Pipodi** [comment]
I can confirm the same issue too. Flashing RevengeOS (Oneplus 7 Pro) with a patched Magisk version works, when I flash v21 it goes into fastboot mode.

I tried what @ad1tyas1ngh said, but no luck.

**Comment by ad1tyas1ngh** [comment]
@Pipodi maybe this method only works for some devices. I heard it also works for lavender.

**Comment by s3tupw1zard** [comment]
So you mean patching the Boot Image with magisk Manager Not glashing the magisk ZIP File?

**Comment by ad1tyas1ngh** [comment]
@s3tupw1zard I meant that in our device group someone sent a modded zip file for Magisk which worked and booted fine. It was just an assumption that v21 didn't patch the boot image correctly.

**Comment by s3tupw1zard** [comment]
Ah okay

**Comment by Pipodi** [comment]
@ad1tyas1ngh I first did this:

- Flashed the patched version
- Opened Magisk Manager
- Updated to v21 from there (direct installation)
- Reboot

It got me in fastboot mode. After that I've uninstalled Magisk from TWRP with the uninstaller and I tried your method, flashing the patched version first, and then the v21 immediately after. Still in fastboot mode.

**Comment by s3tupw1zard** [comment]
The Problem is the Official Magisk Version. only use the patched magisk version.

**Comment by s3tupw1zard** [comment]
on my side it booted with patched. But i got a notification that dtbo image was patched. After this when booting, it shows redmi logo and then my phone is turning off. i think dtbo patching is the problem

**Comment by s3tupw1zard** [comment]
Requesting root isnt working too

**Comment by s3tupw1zard** [comment]
here are my logs:
https://pastebin.com/c8Ps9b0y

**Comment by ad1tyas1ngh** [comment]
@Pipodi Follow these steps:
1. Flash Modded Magisk
2. Uninstall the modded Magisk manager (don't uninstall magisk, uninstall only the apk file)
3. Flash v21 from recovery.
Done

**Comment by Pipodi** [comment]
@ad1tyas1ngh Nope, doesn't work for me. Maybe we are running two different versions of patched Magisk?

**Comment by ad1tyas1ngh** [comment]
@Pipodi let me ask a friend how he managed to install v21. I will get back to you as soon as he replies.

**Comment by ad1tyas1ngh** [comment]
@Pipodi He flashed the canary build, booted, rebooted into recovery, flashed v21 booted.

**Comment by Pipodi** [comment]
@ad1tyas1ngh I tried everything, even flashing the latest canary, but no luck. I'll wait for a more accurate and maybe official solution! Thanks anyway! :)

**Comment by ad1tyas1ngh** [comment]
@Pipodi no problem man. We all are here for the official solution 😄

**Comment by topjohnwu** [comment]
@ad1tyas1ngh @Pipodi where do you get the modified Magisk? And please tell the source to contribute back as Magisk is GPL licensed

**Comment by Pipodi** [comment]
@topjohnwu I found it in the Telegram Group of the RevengeOS for OnePlus 7 Pro. There's a topic on XDA too, but I think the modified version provided there is outdated compared to the one on the Telegram group.

**Comment by ad1tyas1ngh** [comment]
@topjohnwu The modded Magisk version doesn't work but the only way we can flash v21 is by first flashing it otherwise it gets into fastboot mode. In order to not use the modded one, I have switched back to Android 10 and using v20.4.

**Comment by ad1tyas1ngh** [comment]
@Pipodi Sorry man I just confirmed that v21 never worked with OnePlus 7 pro.

**Comment by KurashikiAzusa** [comment]
@topjohnwu The MagiskCU seems to be from an old version of Magisk Canary, version 20422. I cannot verify it because the magisk_files canary branch's older commits was wiped. I did however, source the 20422 files from various sources from googling.

MagiskCU.zip , Magisk-(61599059)-(20422).zip
SHA-1: EA218657D2F2C50FFEA99DF6E464183DA21D458F

**Comment by unresolvedsymbol** [comment]
@Pipodi Where does one obtain the mystery "patched" magisk installer?

**Comment by guchito9** [comment]
Hi, it's fixed for me in the latest canary

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.

**Comment by Snaxeko** [comment]
> @topjohnwu I have a Realme 2 Pro. Same thing happens when flash Magisk v21 on my device. I can only use Magisk v21 on my device by first flashing a modded Magisk Canary File and then flashing v21 on top of it. It might have something to do with patching the boot image.

Did you disabled AVB2.0 to make Magisk works on your Realme ? Personally I experience a boot issue like [here](https://github.com/topjohnwu/Magisk/issues/1533#issuecomment-497753001)
