### ISSUE TITLE
A little error on Samsung device with YES SAR Instructions

### ISSUE THREAD

**Issue by Shany94** [topjohnwu/Magisk#3414]
I found a little error that couldn't permit me to install correctly magisk_patched.img
It worked only when I changed its name in boot.img and I put it in an archive called boot.tar
It's been the only way I could flash correctly it throught Odin.  

So this part of instruction is partially incorrect:
"Reboot to download mode. Open Odin on your PC, and flash magisk_patched.tar as AP, together with BL, CP, and CSC (NOT HOME_CSC because we want to wipe data) from the original firmware."

Moreover all you need is insert and flash in Odin only boot.tar on AP and not BL, CP and CSC/CSC HOME 

Thank you very much for your wonderful work!

**Comment by topjohnwu** [comment]
Only flashing AP is reported to resize the data partition of several models, so no, there it is written in this way intentionally
