### ISSUE TITLE
Problems with Magisk in Pixel C

### ISSUE THREAD

**Issue by Istvan1986** [topjohnwu/Magisk#342]
Hello,

I´m new to GitHub so excuse me if I´m not do something as it be supposed to be done :)

I was using Magisk on my Pixel C during a lot of time but with the release of v13.3, when I update to it I also did it with a full wipe (I usually do that), my tablet starts to bootlooping into recovery and never boots again into ROM.

Usually when I face this kind of problems I just flash the uninstaller, magisk is gone and I´m back into the ROM. Now the uninstaller doesn't works and must make a full  wipe and reflash the ROM.

Also the @Didgeridoohan in the Mgisk General Support says to me that maybe I must upload my boot image to GitHub but I´m totally missed with that. I must say that I test with all the available ROMS for Pixel C and I always end up with the same error.

Thanks in advance.

Cheers.

**Comment by lhw** [comment]
Try the 13.6 Beta from the XDA Thread. It's working for me so far. 13.2 - 13.5 are broken on the Pixel C

**Comment by Istvan1986** [comment]
Really really thanks, Magisk v13.6 running perfectly on my Pixel C.
