### ISSUE TITLE
No connection available magisk 8.0.2

### ISSUE THREAD

**Issue by joaocasarin** [topjohnwu/Magisk#3424]
Latest Magisk Manager 8.0.2 with Magisk 21.0 is saying "No connection available" while there IS a connection when I try to see a module detail.

![Screenshot_20201028-132534](https://user-images.githubusercontent.com/48847394/97465805-2fb5f080-1921-11eb-9275-317198d965e3.jpg)

**Comment by topjohnwu** [comment]
Kill the app and restart?

**Comment by joaocasarin** [comment]
Fixed :D
