### ISSUE TITLE
Problems when toggling dark mode on a10

### ISSUE THREAD

**Issue by dviree** [topjohnwu/Magisk#3425]
Hey I never had a problem.
I use "op dark mode toggler" https://play.google.com/store/apps/details?id=com.harout.opdarkmodetoggler
Every time I toggle dark mode with the setting "force dark mode" magisk manager crashes saying it needs to install. (Only the manager)

Magisk v21 and I've used "hide magisk manager"

**Comment by topjohnwu** [comment]
No logs, no fix
