### ISSUE TITLE
Magisk Manager should allow access to modules menu without Magisk installed

### ISSUE THREAD

**Issue by DorCoMaNdO** [topjohnwu/Magisk#3426]
As a result of bootlooping after activating a module I used `fastboot boot` to boot the system with the stock boot image (since safe mode via holding down the volume down button did not seem to work, Pixel 3 XL, Android 11), thinking I could just open the manager and turn it off, but that was not the case and instead I had to use the ADB command to remove all the modules.
There is no reason to disallow access to the menu, especially when the manager could check if any modules are installed,

**Comment by DanGLES3** [comment]
The thing is, when magisk isn't installed the manager has no permission to access the module folder

**Comment by DorCoMaNdO** [comment]
It's gone but someone commented that without Magisk installed, the manager has no access to the modules, in that case wouldn't an option to disable all modules via some file in internal storage make sense, and adding an option for the manager to create it for you, then just reboot with Magisk installed but modules disabled (the file could be removed on boot, after modules are all disabled)?
I know it might sound similar to safe mode but safe mode did not work for me, I couldn't use any non-system apps including the manager while in safe mode.

**Comment by zgfg** [comment]
If you have a bootloop due to a module:
- leave Magisk installed
- boot to Android Safe mode (google to find a key combo for your phone)
- reboot to normal Android mode
- Magisk now boots with all modules disabled and Magisk hide turned off; you can now manage your modules and don't forget to switch Magisk hide back on

This is a new feature in Magisk v21 (not working in v20.4)

**Comment by DorCoMaNdO** [comment]
Well that did not work as I kept bootlooping, so I suspect it didn't turn off the modules, and yes I'm sure just having the module installed without being activated did not cause the system to bootloop since I've had the module installed for a week now before activating it, I just avoided using it for as long as I could since I feared it wouldn't be compatible.

**Comment by topjohnwu** [comment]
@DorCoMaNdO without Magisk (root), Magisk Manager not only cannot modify Magisk modules, it cannot even see it.
There is 100% no reason to show the module fragment when no active Magisk is installed

**Comment by topjohnwu** [comment]
https://topjohnwu.github.io/Magisk/faq.html
