### ISSUE TITLE
Oneplus 6t stuck on unlocked bootloader screen after installing modules, magisk v. 21.4

### ISSUE THREAD

**Issue by ickam** [topjohnwu/Magisk#3427]
Hi,
I seem to be stuck on bootloader unlock screen. I've installed magisk v. 21.4 and it worked fine until I installed a few modules.
My device is Oneplus 6t, can you help troubleshoot?
I tried power + volume up, but after I press power again, I get the exact same issue

**Comment by ickam** [comment]
I managed to fix this, by going fastboot --> boot to recovery --> recover stock boot image. Obviously I'm unrooted at the moment
I've seen on the Internet that the issue is caused by certain flags being passed, which are necessary to run with ramdisk, which breaks the system when phone reboots while charging. I don't know enough to know if that's true, but just in case, can I ask if we can disable ramdisk in magisk?

**Comment by topjohnwu** [comment]
There is no Magisk v21.4. Bug reports should use canary builds
