### ISSUE TITLE
Can't patch boot.img on Android 10 after removing both magisk_patched.img (through adb shell) and Magisk Manager

### ISSUE THREAD

**Issue by nooriro** [topjohnwu/Magisk#3428]
## Environment
* Google Pixel 4a with BL unlocked
* __Android 10 ( QD4A.200805.003 )__
* Magisk Manager [4e0a3f5e (311)](https://github.com/topjohnwu/magisk_files/blob/f9418d14b0f199e52eec7fb26ec922e7f0248244/app-debug.apk) - the latest canary build as of Oct 28, 2020

## Steps to Reproduce
1. `adb push boot.img /sdcard/Download/`
2. Install Magisk Manager.
3. Run Magisk Manager and patch `boot.img` to create `magisk_patched.img`.
4. __`adb shell rm /sdcard/Download/magisk_patched.img`__
5. __Remove Magisk Manager.__
6. Re-install Magisk Manager.
7. Run Magisk Manager and patch `boot.img` again.

## Expected Results
* `magisk_patched.img` file should be created again in `/sdcard/Download` directory.

## Actual Results
* `magisk_patched.img` file is not created in `/sdcard/Download` directory.
* Error message:
  ```
  - Device platform: arm64-v8a
  - Copying image to cache
  ! Process error
  ! Installation failed
  ```
* [Magisk install log](https://github.com/topjohnwu/Magisk/files/5455372/magisk_install_log_2020-10-28T19_15_19Z.log): same as the above error message

## More Infos
* Logcat ([full logcat here](https://github.com/topjohnwu/Magisk/files/5455376/sunfish-logcat-201028-1915.txt))
  ```
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: Error inserting bucket_display_name=Download owner_package_name=com.topjohnwu.magisk parent=10 volume_name=external_primary _display_name=magisk_patched.img mime_type=application/octet-stream _data=/storage/emulated/0/Download/magisk_patched.img title=magisk_patched group_id=-934002186 is_download=true date_added=1603880115 primary_directory=Download bucket_id=540528482 media_type=0 relative_path=Download/
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1599)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:2713)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3254)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at com.android.providers.media.MediaProvider.insert(MediaProvider.java:2903)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:154)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
  10-28 19:15:15.681  3496 18351 E SQLiteDatabase: 	at android.os.Binder.execTransact(Binder.java:994)
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: java.io.IOException: Can't insert magisk_patched.img.
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.utils.MediaStoreUtils.insertFile(MediaStoreUtils.kt:52)
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.utils.MediaStoreUtils.getFile(MediaStoreUtils.kt:99)
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.handleFile(MagiskInstaller.kt:248)
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.doPatchFile(MagiskInstaller.kt:374)
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Patch.operations(MagiskInstaller.kt:417)
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$2.invokeSuspend(MagiskInstaller.kt:391)
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
  10-28 19:15:15.684 21383 21409 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
  ```
  * https://github.com/topjohnwu/Magisk/blob/4e0a3f5e7211a03e8fb961ed486bd368795db156/app/src/main/java/com/topjohnwu/magisk/core/utils/MediaStoreUtils.kt#L52
  * https://github.com/topjohnwu/Magisk/blob/4e0a3f5e7211a03e8fb961ed486bd368795db156/app/src/main/java/com/topjohnwu/magisk/core/utils/MediaStoreUtils.kt#L99
  * https://github.com/topjohnwu/Magisk/blob/4e0a3f5e7211a03e8fb961ed486bd368795db156/app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt#L248
  * https://github.com/topjohnwu/Magisk/blob/4e0a3f5e7211a03e8fb961ed486bd368795db156/app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt#L374
  * https://github.com/topjohnwu/Magisk/blob/4e0a3f5e7211a03e8fb961ed486bd368795db156/app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt#L417
  * https://github.com/topjohnwu/Magisk/blob/4e0a3f5e7211a03e8fb961ed486bd368795db156/app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt#L391

* This problem happens on Android 10, regardless of whether Magisk is installed or not.
* Instead of step 4, executing `rm /sdcard/Download/magisk_patched.img` through [Teminal Emulator app](https://play.google.com/store/apps/details?id=jackpal.androidterm) makes the same problem.
* However, if you delete `magisk_patched.img` through an explorer app (such as the built-in __Files__ app, [__Files by Google__](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files), [__MiXplorer Silver__](https://play.google.com/store/apps/details?id=com.mixplorer.silver), and so on), the problem __doesn't happen__.
* __This problem doesn't happen on Android 11.__ Checked on Pixel 4a with Android 11 ( RP1A.201005.006 ).

**Comment by nooriro** [comment]
## Some workarounds for end users

### Use create-and-delete method
* Create a dummy `magisk_patched.img` file in `Download` folder in any way, 
  - For example, you can use `adb shell touch /sdcard/Download/magisk_patched.img` command to create the file. 
* and delete it __with any explorer app__ (e.g., the built-in __Files__ app, [__Files by Google__](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files), [__MiXplorer__](https://forum.xda-developers.com/showthread.php?t=1523691)/[__MiXplorer Silver__](https://play.google.com/store/apps/details?id=com.mixplorer.silver), ...) __on your device__.
  - *Do not use `rm` command to delete it.*

### Use ‘Files by Google’ app
* Install __Files by Google__ app (`com.google.android.apps.nbu.files`) [from Google Play Store](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files), run it, and allow permission.
  - *Don't be confused with the built-in __Files__ app (`com.google.android.documentsui`).*
* Select __Browse__ in the bottom navigation and click __Downloads__ in CATEGORIES.
  - *Don't be confused with __Internal storage__ (in STORAGE DEVICES) __> Download__.*
* Find `magisk_patched.img` in the list, long press it, and click the __trash can icon__ in the action bar.

### Use `content delete` command through adb shell
* on Windows Command Prompt:
  ```
  adb shell content delete ^
      --uri content://media/external/downloads ^
      --where """"relative_path='Download/' and _display_name='magisk_patched.img'""""
  ```
* on Linux bash:
  ```
  ./adb shell content delete \
      --uri content://media/external/downloads \
      --where "\"relative_path='Download/' and _display_name='magisk_patched.img'\""
   ```

**Comment by p3yot3** [comment]
I've tried the above workaround several times, no-go I'm afraid.

**Comment by vvb2060** [comment]
This is an AOSP bug, fixed on Android 11: MediaProvider becomes the file system handler (for FUSE) for external storage, making the file system on external storage and the MediaProvider database consistent.

**Comment by vvb2060** [comment]
I plan to append the current time to the file name to fix it.

**Comment by nooriro** [comment]
@vvb2060 How about __using the legacy storage model__ (instead of `MediaStore` APIs) on __`SDK_INT <= 29`__ devices?
I think it would be better to use the legacy storage model not only on Android Pie and earlier versions, __but also on Android 10.__

**Comment by vvb2060** [comment]
This is also recommended by Google. Android 10 scoped storage has too many problems.  But I think an easy way is change download folder in Magisk Manager Setting.
