### ISSUE TITLE
Latest Magisk Manager crashes

### ISSUE THREAD

**Issue by pixincreate** [topjohnwu/Magisk#3429]
Latest canary update has been crashing frequently ONLY when you **tap** on Modules section when **OFFLINE**. So, I cannot uninstall/install **ANY MODULES** from offline.

**Comment by DenyDarko** [comment]
Logcat or it never happened

**Comment by pixincreate** [comment]
Link to Logs: https://drive.google.com/file/d/13Ha4vES3bAs-iFvCQJ9CTKkNiFI6okC0/view?usp=drivesdk

**Comment by topjohnwu** [comment]
Fixed already, need to push a fix fa2dbe981e11185eff8fd73198180ae8b2fb5118
