### ISSUE TITLE
Pixel 5 has deployed hardware attestation

### ISSUE THREAD

**Issue by djechelon** [topjohnwu/Magisk#3432]
Looks like doomsday has come.

This is not an "issue" that I want developers to "fix", but just want to report. And will be closed soon.
Today I Magisked my brand new Pixel 5. The phone is fully "empty" (only Magisk installed) and tried to run SafetyNet.

The check fails as the attestation type is "hardware". Looks like now SafetyNet is able to check for bootloader integrity. And probably GPay is doomed for good.

Just wanted to share this with developers

**Comment by topjohnwu** [comment]
The whole Pixel lineup (except Pixel 1) has been using hardware attestation for months

**Comment by djechelon** [comment]
Uhmmm... my current P3XL does not. I could use GPay like a charm

**Comment by QkiZMR** [comment]
> Uhmmm... my current P3XL does not. I could use GPay like a charm

and is it rooted?

**Comment by djechelon** [comment]
Yes, using the GPay `chmod 600 trick`. Since Android 11 I couldn't enable the systemless host anymore as per #3171
