### ISSUE TITLE
Fake website?

### ISSUE THREAD

**Issue by MicaelJarniac** [topjohnwu/Magisk#3435]
Hi!

I've been searching for some info about how to get things to work well on A/B phones, and I stumbled across this website:
https://magisk.download

I couldn't find anything linking directly to this repo, and the "latest" version of the manager there is `7.5.0`, so I suspect it's not an official website.

I've searched on the issues here for that URL and found nothing, so I decided to ask if it's an official website or not. And if it isn't, I'd say it's a good idea to try to inform people to be careful, but I don't know if that's feasible.

**Comment by DanGLES3** [comment]
Magisk has no website, simple as that, all it's paged are located entirely on GitHub

**Comment by MicaelJarniac** [comment]
That's what I suspected, thanks!

**Comment by QkiZMR** [comment]
what about this https://magiskmanager.com/ ?

**Comment by DanGLES3** [comment]
> what about this https://magiskmanager.com/ ?

I repeat my answer, the only official Magisj Website is it GitHub repository

**Comment by mirsella** [comment]
there is dozen of fake site, i've counted 6 of thems on the in the top 10 first on duckduckgo.

maybe a warning in the github repo / manager app which say clearly that there is no official site, you any others source than https://github.com/topjohnwu/Magisk are fake and potentially malicious ? to try to share the message, i feel like there is a lot of people using those fake magisk as they are the first result and not a lot of information on it.

**Comment by dnd66** [comment]
Different question which is related to this topic: If magisk is downloaded from the correct source (https://github.com/topjohnwu/Magisk/releases/tag/v21.4), how can one know that e.g. Magisk-v21.4.zip has not been tampered with? Is e.g. the PGP signature somewhere indicated on github?

**Comment by info11786** [comment]
What about This https://magiskzip.pro/?

**Comment by mirsella** [comment]
@info11786 there's NO site for magisk. none. they are all unofficial, and so potentially (probably) malicious.

![Image](https://github.com/user-attachments/assets/c6994cc1-91f9-4224-a7a6-addccd2aa08a)
