### ISSUE TITLE
OnePlus 7 Pro newest OS stuck at boot screen

### ISSUE THREAD

**Issue by Shuaiouke** [topjohnwu/Magisk#3436]
As title says

**Comment by JoelJoos** [comment]
I think this is related to issue #3042 
Have the same issue on OP8 Pro with Android 11

**Comment by Shuaiouke** [comment]
But Im on android 10

**Comment by JoelJoos** [comment]
Yes, the problem is with Magisk itself and not really OS related... but I just realized we don't have MTK devices, but still got the same problem as the issue mentioned before
