### ISSUE TITLE
I can't install magisk in android x86 by VmWare directly

### ISSUE THREAD

**Issue by BobC10** [topjohnwu/Magisk#3437]
Could you give me suggestions?

[magisk_install_log_2020-11-01T17_24_18Z.log](https://github.com/topjohnwu/Magisk/files/5470506/magisk_install_log_2020-11-01T17_24_18Z.log)

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.

**Comment by patrickptk** [comment]
@topjohnwu Do you have any tutorial which shows how to install it on any android emulator or virtualbox, vmware. etc ?

**Comment by Mam0nga** [comment]
> @topjohnwu Do you have any tutorial which shows how to install it on any android emulator or virtualbox, vmware. etc ? I have tried to follow one of your written tutorials but could not manage to install magisk along with xposed ... Could you please help me?

Have you not found a solution to your problem?

**Comment by ErcinDedeoglu** [comment]
This problem today still pops
