### ISSUE TITLE
Unable to download bootctl

### ISSUE THREAD

**Issue by Imagine-Breaker** [topjohnwu/Magisk#3438]
```
- Target slot: _a
- Target image: /dev/block/sde11
- Device platform: arm64-v8a
2034+0 records in
2034+0 records out
2082816 bytes (2.0MB) copied, 0.017539 seconds, 113.3MB/s
1410+1 records in
1410+1 records out
1443916 bytes (1.4MB) copied, 0.009039 seconds, 152.3MB/s
- Unpacking boot image
Parsing boot image: [/dev/block/sde11]
HEADER_VER      [2]
KERNEL_SZ       [35270672]
RAMDISK_SZ      [13804665]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [1921396]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-10]
PAGESIZE        [4096]
NAME            []
CMDLINE         [androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=2048 loop.max_part=7 androidboot.usbcontroller=a600000.dwc3 buildvariant=user]
CHECKSUM        [7be2063217c8408469186fabe349d0405d565503000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Magisk patched boot image detected
Loading cpio: [ramdisk.cpio]
Remove [.backup]
Remove [.backup/.magisk]
Move [.backup/init] -> [init]
Dump cpio: [ramdisk.cpio]
Loading cpio: [ramdisk.cpio]
- Patching ramdisk
Add entry [init] (0750)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [dtb]
Found fstab in dtb.0000
Found entry [vendor] in fstab
Found entry [odm] in fstab
Found fstab in dtb.0001
Found entry [vendor] in fstab
Found entry [odm] in fstab
Found fstab in dtb.0002
Found entry [vendor] in fstab
Found entry [odm] in fstab
Found fstab in dtb.0003
Found entry [vendor] in fstab
Found entry [odm] in fstab
- Repacking boot image
Parsing boot image: [/dev/block/sde11]
HEADER_VER      [2]
KERNEL_SZ       [35270672]
RAMDISK_SZ      [13804665]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [1921396]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-10]
PAGESIZE        [4096]
NAME            []
CMDLINE         [androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=2048 loop.max_part=7 androidboot.usbcontroller=a600000.dwc3 buildvariant=user]
CHECKSUM        [7be2063217c8408469186fabe349d0405d565503000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
Repack to boot image: [new-boot.img]
HEADER_VER      [2]
KERNEL_SZ       [35270672]
RAMDISK_SZ      [13804665]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [1921396]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-10]
PAGESIZE        [4096]
NAME            []
CMDLINE         [androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=2048 loop.max_part=7 androidboot.usbcontroller=a600000.dwc3 buildvariant=user]
CHECKSUM        [7be2063217c8408469186fabe349d0405d565503000000000000000000000000]
- Flashing new boot image
! Unable to download bootctl
! Installation failed
```

**Comment by Randy-Light** [comment]
I have the same problem now

**Comment by topjohnwu** [comment]
Please upload Magisk Manager logcat, not install logs...

**Comment by Randy-Light** [comment]
![Screenshot_20201111-155429](https://user-images.githubusercontent.com/74242414/98820512-edb79f00-2436-11eb-9207-8ca1175715b5.jpg)

> --------- beginning of main
--------- beginning of system
01-12 05:10:12.552   738   738 I Magisk  : Magisk 20.4(20400) daemon started
01-12 05:10:12.552   738   738 I Magisk  : * Device API level: 29
01-12 05:10:12.579   738   739 I Magisk  : ** post-fs-data mode running
01-12 05:10:12.581   738   739 I Magisk  : * Initializing Magisk environment
01-12 05:10:12.606   738   739 I Magisk  : * Mounting mirrors
01-12 05:10:12.606   738   739 I Magisk  : mount: /sbin/.magisk/mirror/vendor
01-12 05:10:12.606   738   739 I Magisk  : mount: /sbin/.magisk/mirror/data
01-12 05:10:12.606   738   739 I Magisk  : link: /sbin/.magisk/mirror/system
01-12 05:10:12.606   738   739 I Magisk  : link: /sbin/.magisk/mirror/product
01-12 05:10:12.606   738   739 I Magisk  : * Setting up internal busybox
01-12 05:10:12.619   738   739 I Magisk  : * Running post-fs-data.d scripts
01-12 05:10:12.620   738   739 I Magisk  : * Running module post-fs-data scripts
01-12 05:10:12.620   738   739 I Magisk  : * Loading modules
01-12 05:10:12.620   738   739 I Magisk  : GCAM_Force_aux: loading [system.prop]
01-12 05:10:12.621   738   739 I Magisk  : GCAM_Force_aux: constructing magic mount structure
01-12 05:10:12.630   738   746 I Magisk  : * Starting MagiskHide
01-12 05:10:12.630   738   746 I Magisk  : hide_policy: Hiding sensitive props
01-12 05:10:12.630   738   746 I Magisk  : hide_list init: [com.google.android.apps.walletnfcrel/com.google.android.apps.walletnfcrel]
01-12 05:10:12.633   738   746 I Magisk  : hide_list init: [ua.privatbank.ap24/ua.privatbank.ap24]
01-12 05:10:12.635   738   746 I Magisk  : hide_list init: [com.mcdonalds.mobileapp/com.mcdonalds.mobileapp]
01-12 05:10:12.641   738   746 I Magisk  : hide_list init: [com.google.android.gms/com.google.android.gms.unstable]
01-12 05:10:12.643   738   746 I Magisk  : hide_list init: [org.microg.gms.droidguard/com.google.android.gms.unstable]
11-07 20:26:41.413   738  1249 I Magisk  : ** late_start service mode running
11-07 20:26:41.413   738  1249 I Magisk  : * Running service.d scripts
11-07 20:26:41.413   738  1249 I Magisk  : service.d: exec [v4afx.sh]
11-07 20:26:41.416   738  1249 I Magisk  : * Running module service scripts
--------- beginning of crash
11-07 20:26:54.411   738  3447 I Magisk  : ** boot_complete triggered
11-07 20:27:19.690   738   746 I Magisk  : proc_monitor: [com.google.android.apps.walletnfcrel] PID=[8293] UID=[10175]
11-07 20:27:25.129   738   746 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[9081] UID=[10210]
11-07 20:27:47.276   738   746 I Magisk  : proc_monitor: [ua.privatbank.ap24] PID=[13292] UID=[10592]
11-07 20:27:54.157   738   746 I Magisk  : proc_monitor: [com.google.android.apps.walletnfcrel] PID=[14105] UID=[10175]
11-07 20:27:59.770   738   746 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[14640] UID=[10210]
11-07 20:28:10.116   738   746 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[15060] UID=[10210]
11-07 20:29:35.745   738   746 I Magisk  : proc_monitor: [com.mcdonalds.mobileapp] PID=[17490] UID=[10630]
11-07 20:29:39.720   738   746 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[17682] UID=[10210]
11-07 20:54:21.860   738   746 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[23370] UID=[10210]
11-07 22:27:56.487   738   746 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[2356] UID=[10210]
11-07 22:31:35.769   738   746 I Magisk  : proc_monitor: [com.google.android.apps.walletnfcrel] PID=[3441] UID=[10175]
11-07 23:46:39.046   738   746 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[5675] UID=[10210]
11-08 06:39:04.697   738   746 I Magisk  : proc_monitor: [com.google.android.apps.walletnfcrel] PID=[8003] UID=[10175]
11-08 10:30:14.434   738   746 I Magisk  : proc_monitor: [com.google.android.apps.walletnfcrel] PID=[13796] UID=[10175]
11-08 12:44:43.655   738   746 I Magisk  : proc_monitor: [com.google.android.apps.walletnfcrel] PID=[16234] UID=[10175]
11-08 14:21:25.765   738   746 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[18776] UID=[10210]
11-08 14:24:20.498   738   746 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[20253] UID=[10210]
11-08 14:39:38.979   738   746 I Magisk  : proc_monitor: [ua.privatbank.ap24] PID=[22646] UID=[10592]
11-08 14:49:04.265   738   746 I Magisk  : proc_monitor: [com.google.android.apps.walletnfcrel] PID=[23989] UID=[10175]
11-08 15:23:57.752   738   746 I Magisk  : proc_monitor: [com.google.android.apps.walletnfcrel] PID=[28845] UID=[10175]
11-08 15:23:58.708   738   746 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[28928] UID=[10210]
11-08 16:51:09.408   738   746 I Magisk  : proc_monitor: [com.google.android.apps.walletnfcrel] PID=[7652] UID=[10175]
11-08 20:02:39.537   738   746 I Magisk  : proc_monitor: [com.mcdonalds.mobileapp] PID=[21396] UID=[10630]
11-08 20:31:54.901   738   746 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[24775] UID=[10210]
11-08 20:31:55.118   738   746 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[24816] UID=[10210]
11-08 20:31:57.842   738   746 I Magisk  : proc_monitor: [com.google.android.apps.walletnfcrel] PID=[24957] UID=[10175]
11-08 20:50:09.015   738   746 I Magisk  : proc_monitor: [com.mcdonalds.mobileapp] PID=[26565] UID=[10630]
11-11 14:10:05.708   729   737 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[19084] UID=[10210]
11-11 14:17:45.006   729   737 I Magisk  : proc_monitor: [com.google.android.apps.walletnfcrel] PID=[19657] UID=[10175]
11-11 14:52:51.436   729   737 I Magisk  : proc_monitor: [com.google.android.gms.unstable] PID=[24702] UID=[10210]

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.
