### ISSUE TITLE
GSI not booting without magisk pacthed boot, but after installing magisk manager it says magisk not installed.

### ISSUE THREAD

**Issue by reverseflash2** [topjohnwu/Magisk#3441]
So I installed Nusantara os V2.3 android 11 gsi and it did not boot at first but after I installed magisk it booted but magisk manager was not installed so I installed it and when I did it says magisk not installed.

**Comment by reverseflash2** [comment]
Actually now that I look inside system/bin magisk exists but magisk manager still say no magisk

**Comment by manofsteel2017** [comment]
Can be fixed if create an xbin folder and flash a modded version of magisk but that's unstable and we need official support

**Comment by osm0sis** [comment]
#844

**Comment by manofsteel2017** [comment]
I see you guys rather close the ticket without even bothering looking into the other person fixes but instead complain when someone fork magisk.

**Comment by osm0sis** [comment]
Post on the correct GSI issue if you want it to be taken into consideration
