### ISSUE TITLE
Android 10 -- SafetyNet failure

### ISSUE THREAD

**Issue by huang-jy** [topjohnwu/Magisk#3443]
I recently upgraded my phone to Android 10 (well, it was sort of forced, but anyway...)

And just today, I got a notification from Google Pay saying my device no longer met hardware requirements. (I was able to use Google Pay previously)

Magisk went funny and I had to reinstall Magisk and Manager, but looks like it is up to date:

![image](https://user-images.githubusercontent.com/2756283/97900321-641b1980-1d32-11eb-9157-e2de2babed2f.png)

However, when doing the SafetyNet test, it fails:

![image](https://user-images.githubusercontent.com/2756283/97900380-77c68000-1d32-11eb-8b1d-5b263e94a42c.png)

MagiskHide no longer works for things like Google Pay, *BUT* root still works for apps that don't care about SafetyNet, for example Titanium Backup

![image](https://user-images.githubusercontent.com/2756283/97900524-a80e1e80-1d32-11eb-9cf7-2dbe8f849eb1.png)

I can live without Google Pay for now, so flagging this up.

**Comment by zgfg** [comment]
Root works and it has nothing with SafetyNet passing or failing

But first of all,have you enabled Magisk Hide thriugh Magisk Manager settings?

**Comment by huang-jy** [comment]
> But first of all,have you enabled Magisk Hide thriugh Magisk Manager settings?

Yep

![image](https://user-images.githubusercontent.com/2756283/97957406-ffe46e00-1da2-11eb-9f2f-3e18b4a3aadf.png)

And Google Pay and Services are marked as hide as they were before

![image](https://user-images.githubusercontent.com/2756283/97957551-5a7dca00-1da3-11eb-923f-0586857028df.png)

**Comment by Didgeridoohan** [comment]
> > But first of all,have you enabled Magisk Hide thriugh Magisk Manager settings?
> 
> Yep

But the important question is: have you toggled it off and on again?

This isn't really a question for GitHub issues. And: #1152 

You can find lots of info on XDA and here: https://www.didgeridoohan.com/magisk/HomePage

I suggest you close the issue, so that John or Chris doesn't have to.

**Comment by huang-jy** [comment]
Okey. Closing
