### ISSUE TITLE
Please revert back to old magisk 7.5.1 as new one is unusable. 

### ISSUE THREAD

**Issue by Mr-trololol** [topjohnwu/Magisk#3446]
Device: Oneplus 7, Rom: crdroid                                                    I can't download modules can't remove modules can't update modules since buttons just don't work on 8.0.2 it's unusable & at last i can't revert back to old magisk 7.5.1 with renamed magisk manager name so please can you revert back to old version as stable while you guys work on a fix?

**Comment by zgfg** [comment]
From Settings, Apps, uninstall Magisk Manager (or whatever you renamed)

Then install Magisk Manager 7.5.1

Magisk DB (modules, Superuser, Magisk hide) are part of Magisk DB and won't be deleted by uninstalling Magisk Manager

(Although, don't really understand why buttons do not work for you, but apparently you don't like the new Manager and you are probably not familiar with to fix your issue)

Btw, TJW clearly stated that there will be no fail back and no maintenance of the old and new in parallel
