### ISSUE TITLE
Magisk working with Google gsi but froze and rebooted phone 

### ISSUE THREAD

**Issue by manofsteel2017** [topjohnwu/Magisk#3447]
Google version of gsi worked out of the box with magisk but it froze and rebooted the phone after like 2 to 3 mns which makes it unusable
I'm on note 20 ultra. 
I can provide logs if needed 
I see we aren't supposed to post about gsi but that's not Phh gsi but straight from the big guy

**Comment by osm0sis** [comment]
#844
