### ISSUE TITLE
Magisk v21 and manager v8.02 - root woks but manager clam N/D

### ISSUE THREAD

**Issue by mirek190** [topjohnwu/Magisk#3448]
magisk v21 and manager v8.02 - root woks - I can use apps which requires it  but manager claim N/D so most options not working in the manager.
Miui 12 android 10 - Mi Max 3.

**Comment by zgfg** [comment]
Have you tried deleted all data (and cache) for Manager, or even uninstalling , rebooting and installing Manager apk manually

It happens on Manager update but deleting data for Manager won't delete Magisk data (modules, apps marked for root grant or for Magisk hide)

**Comment by mirek190** [comment]
I tried reinstalling , uninstalling , clean data and cache of the manager app before posting here .

Root was ok on miui 11. Then I updated to miui 12.
Lost root ( that's normal ) .
 So under recovery ( had to install recovery again - trwp ) installed magisk 20.4 and rebooted device ( no errors ) .
Root stared working again ( apps has access to root  but manager not .
During running app manager  I'm getting message " root not granted "  and app claim root installed - N/D...

I tried install magisk 21 under trwp  
Everything went ok ..no errors .
Rebooted ( roots works on other apps )  and tried app manager again ...and claims root not installed - N/D.

My idea is to remove completely root and install magisk again .
But how to do that under trwp  ?

I'm so confused.

**Comment by Didgeridoohan** [comment]
Sounds like you still have a hidden Manager installed (the hint is that you get "root denied" when opening the Manager). The solution to that would be to uninstall both Managers before installing the Manager again.

**Comment by mirek190** [comment]
I uninstalled manager and installed again ...still the same situation....
How to uninstall magisk completely ?

**Comment by Didgeridoohan** [comment]
> I uninstalled manager and installed again ...still the same situation....
> How to uninstall magisk completely ?

But did you check if you have a second Manager installed? Likely the previously hidden one... If my guess is correct you'll have to also uninstall that.

**Comment by mirek190** [comment]
> > I uninstalled manager and installed again ...still the same situation....
> > How to uninstall magisk completely ?
> 
> But did you check if you have a second Manager installed? Likely the previously hidden one... If my guess is correct you'll have to also uninstall that.

YES !
You're right .
I had a hidden one installed as well. 
I removed hidden magisk manager then installed manager 8.02 and WORKS as should. 

Thank you for help.

**Comment by Didgeridoohan** [comment]
Got it! Great.

Now you can close this issue (since it's not actually an issue).

**Comment by mirek190** [comment]
Problem solved
