### ISSUE TITLE
Vendor image does not match system

### ISSUE THREAD

**Issue by Rocky471** [topjohnwu/Magisk#3449]
I have a Moto G turbo (Merlin) and i installed Havoc OS and Magisk in it. Everything works fine except the Camera and the proximity sensor. Whenever I open camera it crashes. I have installed many camera apps and tried it. In the sock rom it used to work fine. Also when I get a call I get a call my screen turns blank and I am not able to attend it.

I think there is some problem with the vendor image cause whenever I switch off my phone and turn it on again it gives an error "
The vendor image does not match system. Please flash the MPDS24.107-56-1-28 vendor image for you device"

Please tell me a way to fix this. I searched for the vendor image in my stock rom but i just found a .xml file that has a similar name. I don't know how to flash an xml file. It would be gr8 if anyone could please provide me with the vendor image for my phone and tell me how to flash it so that I could get this error fixd and take photos again!!
![Screenshot_20201104-204121](https://user-images.githubusercontent.com/66260177/98199725-e2093b80-1f51-11eb-9adb-de38da45674f.jpg)

**Comment by DanGLES3** [comment]
1-issue is not related to Magisk
2-Merlin doesn't have a vendor image (that's most likely a ROM bug)
3-that could either be the rom or something went wrong with the proximity sensor
