### ISSUE TITLE
Magisk does not work with latest S10e G970F firmware G970FXXU9DTJA_G970FOXM9DTJB_G970FXXU9DTJA

### ISSUE THREAD

**Issue by FunThomas76** [topjohnwu/Magisk#3453]
i flashed it like before (had the august firmware running fine with magisk) but now the phone runs in normal mode but booting with magisk (volume up + bixby + power) always ends in a reboot here after a long lime samsung logo shown

sometime i get the recovery screen that the phone couldn't start normally ...

reboot recovery cause is [system_server:13691]
unable to disable quotas on /dev/block/platform/13d60000.ufs/by-name/userdata because /system/bin/tune2fs is missing
#reason is [RescueParty]#
Supported Api: 3

it is not possible to flash the old august firmware here which i was running before, so at the moment only lastest stock without magisk is possible here

have tried magisk 20.4 and beta channel v21 no difference both not working on s10e

**Comment by FunThomas76** [comment]
tried to run magisk 20.4 and 21 with factory reset and this latest firmware (G970FXXU9DTJA) but no luck
it seems to be a problem with this firmware version, the version before (G970FXXS9DTI8) works fine with magisk
so it seems samsung broke something

**Comment by alroy214** [comment]
Yep

**Comment by FunThomas76** [comment]
S10+ works but not for the S10e

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.
