### ISSUE TITLE
Unable to uninstall the module installed from "Modules" screen.

### ISSUE THREAD

**Issue by bob333** [topjohnwu/Magisk#3455]
Hi, I installed Call Recorder - SKVALEX (2.1.0) version. I uninstalled the module and the app as it is not open source. The app is still displayed in the "MagiskHide" screen although it is not listed in the "pm list packages" command. The issue persists after reboot.

**Comment by topjohnwu** [comment]
It means the data is still there, you can remove it completely with `pm uninstall <pkg_name>`
