### ISSUE TITLE
Option to magisk hide from all in MagiskHide screen

### ISSUE THREAD

**Issue by vinnom** [topjohnwu/Magisk#3456]
Considering that converting MagiskHide to whitelisted based would be hard, it would be nice to have a "hide from all" option to check all apps from checklist, considering that apps which will not be blacklisted are considerable less frequent than the ones that will be. Then uncheck the ones we don't want blacklisted would be easier than check all the others

**Comment by DanGLES3** [comment]
That would not be good, due to the hacky way magisk hide works it's only designed to be used on a few apps at a time, using it on all app (unnecessarily) can lead to system instability

**Comment by vinnom** [comment]
hmm, I didn't know that, but I do it for almost all my apps for quite some time now and I didn't face any system instability, neither on AOSP ROMs or MIUI (device beryllium)

**Comment by DanGLES3** [comment]
> hmm, I didn't know that, but I do it for almost all my apps for quite some time now and I didn't face any system instability, neither on AOSP ROMs or MIUI (device beryllium)

Still, there is no benefit on doing that, if an app works with root using Magisk Hide in it is pointless

**Comment by topjohnwu** [comment]
@vinnom if you select all apps, your device will be very unstable...

**Comment by vinnom** [comment]
as I said, I do that for some time already everytime I change ROM and I didn't had any issues regarding stability until now. But if you guys say so, I'll stop doing that to avoid potential issues. I really didn't know it could lead unstability.
