### ISSUE TITLE
Compilation issue regarding nanopb

### ISSUE THREAD

**Issue by cawidtu** [topjohnwu/Magisk#3457]
While trying to compile the currently latest Magisk commit (2739d3cb670d740be4b577533229a65b3125bcfe) using Windows 10, Java 13.0.1 and the latest ndk provided via "python build.py ndk" (android-ndk-r21d-windows-x86_64.zip)" I ran into the below mentioned-issue regarding nanopb. I was able to build Magisk commits successfully a few weeks ago with the same environment before the ndk was updated.

`
jni/resetprop/persist_properties.cpp:21:2: error: Regenerate this file with the current version of nanopb generator.
#error Regenerate this file with the current version of nanopb generator.
 ^
jni/resetprop/persist_properties.cpp:59:14: error: unknown type name 'pb_msgdesc_t'
extern const pb_msgdesc_t PersistentProperties_msg;
             ^
jni/resetprop/persist_properties.cpp:60:14: error: unknown type name 'pb_msgdesc_t'
extern const pb_msgdesc_t PersistentProperties_PersistentPropertyRecord_msg;
             ^
jni/resetprop/persist_properties.cpp:70:53: error: unknown type name 'AUTO'
PB_BIND(PersistentProperties, PersistentProperties, AUTO)
                                                    ^
jni/resetprop/persist_properties.cpp:72:1: error: expected function body after function declarator
PB_BIND(PersistentProperties_PersistentPropertyRecord, PersistentProperties_PersistentPropertyRecord, AUTO)
^
5 errors generated.
`

**Comment by topjohnwu** [comment]
`git submodule update`
