### ISSUE TITLE
Every time I install Magisk after a factory reset, I get back an old boot animation and theme. How?

### ISSUE THREAD

**Issue by keeganjk** [topjohnwu/Magisk#346]
I have factory reset my phone a few times, but every time I install Magisk, I get back an old boot animation that I used from a custom ROM/Kernel I installed and I also get a custom Red accent color I installed. How?

**Comment by Ante0** [comment]
Is it restoring a boot image backup perhaps? 
Check /data/stock_boot_xxxxrandomnumbers.img.gz.
You could try removing that, restoring stock boot, then flash Magisk and see if that solves it.

**Comment by keeganjk** [comment]
I see /data/stock_boot_.img.gz

**Comment by keeganjk** [comment]
I think /data/stock_boot_.img.gz was the right file.

**Comment by keeganjk** [comment]
@Ante0 Wait, what exactly _is_ /data/stock_boot_xxxxxxxxxxxx.img.gz?

**Comment by topjohnwu** [comment]
@keeganjk this is a bug in v13.3. It is fixed in the newer betas

**Comment by Ante0** [comment]
@keeganjk
/data/stock_boot_xxxxxxxxxxxx.img.gz is just the backup of BOOT that Magisk makes when you install it. It's restored when you use the Magisk uninstaller. It may be used when you install a new version of Magisk too, I'm not sure of this.
But anyway, it's safe to remove if it causes problems. You'd just have to get/install stock boot through other means. For most firmware you can get it easily.

**Comment by keeganjk** [comment]
Okay.
