### ISSUE TITLE
I don't see Magisk 21.0 in Manager on any of my devices...

### ISSUE THREAD

**Issue by lemmy04** [topjohnwu/Magisk#3463]
I have several Samsung devices and none of them shows me Magisk newer than 20.4 as available...

- S5e running Android 9 T725XXU1ASH1
- S8+ running Android 9 G955FXX6DSL1
- S2 running Android 7 T719XXS2BSG1

..any ideas? Manager is the latest 8.0.2 on all of them.

Do i need to switch to a different update channel or something?

**Comment by topjohnwu** [comment]
Yes, switch to beta

**Comment by lemmy04** [comment]
i thought Magisk 21.0 was already released?

**Comment by lemmy04** [comment]
so i switched to the beta channel on my spare tablet and it seems to be fine.
One thing though, I now see ssh for magisk 0.11 as available module update, but when I try to install I get "download error", I suppose I take that to the maintainer of that module?

And... how stable is 21.0, seeing that it's still on the beta channel?

**Comment by mattmccutchen** [comment]
I just had the same question; fortunately, I found this issue before I lost much time.  It might help to mark beta versions of Magisk as "pre-release" on the GitHub releases page to make this clearer.
