### ISSUE TITLE
Magisk Manager：After modified Language to English and can't switch to others

### ISSUE THREAD

**Issue by bluehomewu** [topjohnwu/Magisk#3465]
[Log file](https://drive.google.com/file/d/1hJrDv6QfWO4dqUL9j0MJojIq6xkqJAc_/view?usp=drivesdk) 

![Screenshot_20201111-185033](https://user-images.githubusercontent.com/56945729/98802808-cc62ad00-244e-11eb-9392-7a0625a0106e.jpg)

**Comment by topjohnwu** [comment]
Cannot reproduce, kill the app and restart?

**Comment by bluehomewu** [comment]
> Cannot reproduce, kill the app and restart?

Not worked

**Comment by bluehomewu** [comment]
@tony8077616 also happen this issue on his device too.

**Comment by bluehomewu** [comment]
@topjohnwu 
Check this video please.
