### ISSUE TITLE
Doesn't hide root for Movistar play

### ISSUE THREAD

**Issue by Pecas93** [topjohnwu/Magisk#3469]
Hi, I post this issue because I have the problem for like 3 or 4 years. It's about Movistar play app. When I open the app see a message about problems with DRM, so It means magisk hide doesnt hide root for the app. I hope this issue can dissapear soon

**Comment by Didgeridoohan** [comment]
Not necessarily. DRM means [Digital Rights Management](https://en.wikipedia.org/wiki/Digital_rights_management) and most likely it's caused by your device not having the proper libraries for it.

**Comment by HerendraTJ** [comment]
#1152
