### ISSUE TITLE
Pixel 3 freezes after flashing patched boot.img

### ISSUE THREAD

**Issue by Davidyz** [topjohnwu/Magisk#3478]
I tried flashing patched boot image to my pixel 3 (running stock Android 11), and when I reboot from bootloader, the screen freezes after a few seconds. The physical bottons and fingerprint sensor seems to be functional but the phone has no response to the touch screen. The phone also didn't respond to ADB command, which means I couldn't reboot the phone through 'adb reboot'. I had to long press the power button to reboot into bootloader. Flashing the stock boot image saves the phone from freezing but the magisk is gone.

Magisk manager version: v8.0.1~v8.0.3

Magisk version: v21.0, v21.1(both claimed to support Android 11)

**Comment by topjohnwu** [comment]
100% module problem, not Magisk issue

**Comment by Davidyz** [comment]
> 100% module problem, not Magisk issue

But I have not installed any module yet. My first attempt was based on a 100% original stock Android 11 ROM and it keeps freezing so I haven't installed any modules in my phone yet.
