### ISSUE TITLE
Lenovo tab M8 bootloop after patching Android 10

### ISSUE THREAD

**Issue by isrgish** [topjohnwu/Magisk#3479]
After patching the boot.img and flashing it I'm in a bootloop.

**Edit: The file size of the boot.img is 33.55MB and the magisk_patched.img is only 10.72MB. This sounds wrong to me.**

As per this post [#2492](https://github.com/topjohnwu/Magisk/issues/2492) I did the following

1. Installed Magisk Manager 7.5.1
2. I changed the update channel to custom and entered `https://ppt.cc/fQfj1x`
3. Refreshed Magisk Manager (it changed Magisk to `cf846ed (20310)`).
4. I patched the boot image (In advanced settings I tried both leaving ticked and unticking `Preserve force encryption` and `PreserveAVB 2.0/dm-verity`)
5. flashed the patched image.

What am I missing here? Please help.

Thank You

**Comment by topjohnwu** [comment]
Use official canary channels

**Comment by isrgish** [comment]
I would like to clarify. Do I need to download the canary manager? I see that only the debug version is available. Is that the one?

**Comment by isrgish** [comment]
I'm still having the same bootloop after using the manager downloaded from [This link](https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/app-debug.apk.)

**Comment by isrgish** [comment]
I finally figured this out and got root. You need to flash the patched boot image file **after** you flash the vbmeta.img with --disable-verification.

Here are the steps I did to get root.
1. Copied boot.img from the firmware to my device.
2. Downloaded Magisk Manager. (The regular version, no need for the canary version).
3. Patched the boot.img with magisk manager.
   1. Clicked on `Install` on the righthand top in magisk manager.
   2. Clicked on `Next` Righthand top.
   3. Selected `Select and Patch a File`.
   4. picked the boot.img file I had copied in step 1. Magisk manager patched the file.
4. Copied the patched file pack to my PC.
5. Booted into Fastboot.
6. (Flashed the patched boot image to my device `fastboot flash boot path-to-patched-boot-image`) **I don't think this is needed here but it is what I had done.**
7. Flashed the vbmeta.img from the firmware with the option --disable-verification. `fastboot --disable-verification flash vbmeta path-to-vbmeta-image`**It does not need to be an empty vbmeta image.**
8. Flashed the patched boot image to my device `fastboot flash boot path-to-patched-boot-image`. (A second time, but as mention before I don't think the first time is necessary).
9. fastboot reboot.

**...And now I have root.**

**Disclaimer use this info at your own risk. I take no responsibility for it.**

[This answer is copied from Android Enthusiasts Give credit where it is rightly earned](https://android.stackexchange.com/a/231267/278012).

**Comment by AntiTrustInc** [comment]
i am stuck on a bootloop as well..  the lenovo screen keeps popping.. i cant get into fastboot or recovery.. i flahed the darn recovery and boot.img..  but repatched them with magisk...  why am i in a bootloop.  did i brick it?

**Comment by AntiTrustInc** [comment]
it keep sboot looping adb nor fastboot will inititate

**Comment by AntiTrustInc** [comment]
at what point do either of the tools show the opportunity to flash it?

**Comment by isrgish** [comment]
First power off then boot to fastboot with the hardware buttons see below.

**Power off the device:** Hold the power button from  20 - 30 seconds even if device powers off while you still need to hold for at least 20 seconds.
**Boot to Fastboot:** Hold the Volume Down Button while holding hold the power button till the device starts. then release the power button. This should bring you into Fastboot.
