### ISSUE TITLE
Magiskboot x86: Google Pixel 4a 5G boot image crashes on canary

### ISSUE THREAD

**Issue by enovella** [topjohnwu/Magisk#3480]
Reopened issue https://github.com/topjohnwu/Magisk/issues/3434. Affecting the x86 binary

## Setup

- OS: Ubuntu 18.04 LTS x64

## Log
```sh
Dump cpio: [ramdisk.cpio]
Patch @ 0145FFC6 [736B69705F696E697472616D667300]->[77616E745F696E697472616D667300]
- Repacking boot image
Parsing boot image: [boot.img]
HEADER_VER      [3]
KERNEL_SZ       [11562794]
RAMDISK_SZ      [14119334]
OS_VERSION      [11.0.0]
OS_PATCH_LEVEL  [2020-10]
PAGESIZE        [4096]
CMDLINE         []
KERNEL_FMT      [lz4]
RAMDISK_FMT     [lz4_legacy]
Repack to boot image: [new-boot.img]
Segmentation fault (core dumped)
! Unable to repack boot image!
```

```sh
$ dmesg
[175554.497434] traps: magiskboot[18747] trap divide error ip:804b330 sp:ffa31940 error:0 in magiskboot[8048000+6e000]
```

## Reproduce
[boot.img.zip](https://github.com/topjohnwu/Magisk/files/5446760/boot.img.zip)

**Comment by topjohnwu** [comment]
@enovella `magiskboot` is meant to run on Android, not on desktop Linux. The `x86` binary works perfectly on an x86 Android Emulator (Android Studio AVD). Unless doing development (I assume that is what you are doing here), Magisk installation is strongly recommended to run through Magisk Manager on the same device you are going to install on.
