### ISSUE TITLE
Magisk 21.0: Almost completely boots, then shuts down

### ISSUE THREAD

**Issue by UltraBlackLinux** [topjohnwu/Magisk#3483]
Hey there, 
I just opdated my LOS to 2020-11-07, and I can't boot to it anymore with magisk. Everytime it's almost done booting, the screen goes black, the vibrator vibrates for 1 sec, then my phone shuts down - What should I do? It's super annoying.
Thanks!

cheryl
LOS 17.1 (AND 10)

**Comment by osm0sis** [comment]
Try 21.1?

**Comment by UltraBlackLinux** [comment]
@osm0sis Where do I download that release - It's not on the official website yet...

**Comment by UltraBlackLinux** [comment]
huh - 2 reboots later it's broken again

**Comment by UltraBlackLinux** [comment]
after alot of trying - It doesn't seem to work. I was happy bc canary finally fixed the boot mounting problems, but it's just buggy and unstable, sadly, I am going back to stable...

**Comment by UltraBlackLinux** [comment]
@osm0sis could you look into this? All lineageos releases for cheryl seem to have that problem since 24.10.2020

**Comment by osm0sis** [comment]
Yikes. I'm going to run my regression testing on magiskboot soon and hopefully it turns up something obvious for us to fix for a few devices, but this one sounds like a magiskinit issue.

I think the bottom line is we need logs. Also if it broke on Lineage's side then there must be something in their changelog for that first broken nightly which would help?

**Comment by UltraBlackLinux** [comment]
@osm0sis sadly I don't have any acces to a changelog anymore, maybe the update file has a changelog in it?

**Comment by osm0sis** [comment]
What? Their whole download site contains has a changelog. You need to provide a log from the failed boot, then narrow down exactly which Lineage build first caused the issue.

**Comment by UltraBlackLinux** [comment]
I know which build it caused, I don't know, how to get a boot log, and lastly, the changelogs are only for the next build (also the changelog on the mainpage is too new. The build that works is like 4 versions behind now)

**Comment by UltraBlackLinux** [comment]
@osm0sis Magisg 21.4 is also not working :/
