### ISSUE TITLE
Magisk dc5e78e1(21006) & 1469b82a(21101) edXposed fails to load modules (sepolicy) (Samsung S20 Android 10)

### ISSUE THREAD

**Issue by personaingrata** [topjohnwu/Magisk#3486]
i updatet latest canary to dc5e78e1(21006) & 1469b82a(21101) through the manager, in both versions edXposed fails to load modules, but edXposed framework Status is shown "Active", i guess this is due to big magisk sepolicy changes lately. flashing back to magisk 4e0a3f5e(21005) from twrp solves the problem, edXposed works properly again. i can reproduce this issue by flashing any of the above named magisk versions.

phone: samsung galaxy s20+ 5G / SM-G986B
latest stock fw: G986BXXS5BTJ4
stock kernel: 4.19.87-19891288

i got some logs and zipped them, please have a look at this issue
[Magisk-edxposed_logs.zip](https://github.com/topjohnwu/Magisk/files/5541007/Magisk-edxposed_logs.zip)

**Comment by kotori2** [comment]
https://github.com/RikkaApps/Riru/issues/133
Riru was also affected

**Comment by topjohnwu** [comment]
Fixed 0064b01ae03b2f0dfff9f858e91df0c24a468dcd
