### ISSUE TITLE
Magisk Crashing com.android.systemui.SystemUIService

### ISSUE THREAD

**Issue by DenisLanks** [topjohnwu/Magisk#3488]
**Cause:**
SystemUIService load icon from package. It expect a drawable but receive LayerDrawable.

**Solution**
Use Bitmap instead of vector image. Just compatibility reason.

**Model**
KEN XIN DA R6

**Kernel**
3.18.19+
**Android**
6.0

**Logcat**
java.lang.RuntimeException: Unable to create service com.android.systemui.SystemUIService: java.lang.ClassCastException: android.graphics.drawable.LayerDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.app.ActivityThread.handleCreateService(ActivityThread.java:3088)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.app.ActivityThread.-wrap4(ActivityThread.java)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:111)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:207)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:5765)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
11-14 14:43:19.220 17744 17744 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.graphics.drawable.LayerDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:2236)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.app.ApplicationPackageManager.loadItemIcon(ApplicationPackageManager.java:2091)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:155)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.content.pm.ComponentInfo.loadDefaultIcon(ComponentInfo.java:184)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:2243)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.app.ApplicationPackageManager.loadItemIcon(ApplicationPackageManager.java:2091)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:155)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at com.android.systemui.recents.misc.SystemServicesProxy.getActivityIcon(SystemServicesProxy.java:488)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at com.android.systemui.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(RecentsTaskLoader.java:407)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at com.android.systemui.recents.model.RecentsTaskLoadPlan.executePlan(RecentsTaskLoadPlan.java:238)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at com.android.systemui.recents.model.RecentsTaskLoader.loadTasks(RecentsTaskLoader.java:477)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at com.android.systemui.recents.Recents.start(Recents.java:271)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:125)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:31)
11-14 14:43:19.220 17744 17744 E AndroidRuntime:   at android.app.ActivityThread.handleCreateService(ActivityThread.java:3078)

**Comment by topjohnwu** [comment]
This is not caused by Magisk, should be some incompatible modules

**Comment by DenisLanks** [comment]
But, it just happen with magisk. Wich module exacly is not compatible?
