### ISSUE TITLE
刷入21101修补后的boot无法进入系统

### ISSUE THREAD

**Issue by leihen** [topjohnwu/Magisk#3492]
[boot.zip](https://github.com/topjohnwu/Magisk/files/5542325/boot.zip)

刷入使用（21101）修补的boot时自动进入fastboot，无法进入系统（x50proplay Android11）
已上传boot
之前Android10修补boot后，boot大小由96M缩小到60M，现在Android11修补后大小无变化
我该如何抓取dmesg日志，没有twrp，没有找到方法抓取，我该如何反馈更多有用的内容来解决，还请您告知，谢谢

translate by google

When flashing in the boot patched with （21101）, it will automatically enter fastboot, and cannot enter the system (x50proplay Android11)
Boot uploaded
Android10 patched the boot, the boot size was reduced from 96M to 60M, and now there is no change in the size after Android11 patched
How can I grab the dmesg log, there is no twrp, and I have not found a method. How can I feed back more useful content to solve it? Please let me know, thank you

**Comment by leihen** [comment]
貌似需要解包删掉oplus.fstab里面的avb相关，然后重新打包再修补

**Comment by yuxuxin233** [comment]
有方法了吗？

**Comment by scarlet-glass** [comment]
请问这个文件是在哪个路径下啊？ @leihen

**Comment by leihen** [comment]
> 请问这个文件是在哪个路径下啊？ @leihen

你是问哪个文件的路径？boot文件提取需要去你所使用的刷机包里提取，有的能直接看到，有的需要提取，修补后的magisk_patched.img文件在download文件夹,oplus.fstab需要解包boot文件才能看到

**Comment by scarlet-glass** [comment]
> > 请问这个文件是在哪个路径下啊？ @leihen
> 
> 你是问哪个文件的路径？boot文件提取需要去你所使用的刷机包里提取，有的能直接看到，有的需要提取，修补后的magisk_patched.img文件在download文件夹,oplus.fstab需要解包boot文件才能看到

我知道magisk_patched.img文件在download文件夹。原boot.img的ramdisk目录都是空的。你说的这个oplus.fstab文件是在哪里？

**Comment by leihen** [comment]
> > > 请问这个文件是在哪个路径下啊？ @leihen
> > 
> > 
> > 你是问哪个文件的路径？boot文件提取需要去你所使用的刷机包里提取，有的能直接看到，有的需要提取，修补后的magisk_patched.img文件在download文件夹,oplus.fstab需要解包boot文件才能看到
> 
> 我知道magisk_patched.img文件在download文件夹。原boot.img的ramdisk目录都是空的。你说的这个oplus.fstab文件是在哪里？
你是使用什么解包的，我是在电脑上解包的（电脑是用Android Image Kitchen解包的，xda可下，手机好像镜像工厂可行？不清楚），就在ramdisk里，而且在split_img里面有个xxxcpio.gz里面（应该是boot的备份文件）可能也需要修改，还未验证不修改是否可行

![image](https://user-images.githubusercontent.com/55120120/100851023-9352b100-34bf-11eb-9629-276ff093c453.png)

能够root是因为我是在普通版机型出的可用的boot解包对比出来的，只有几个文件不一样，替换修补后不一样的文件才有root，具体如何操作的作者并没有分享

**Comment by leihen** [comment]
> > > 请问这个文件是在哪个路径下啊？ @leihen
> > 
> > 
> > 你是问哪个文件的路径？boot文件提取需要去你所使用的刷机包里提取，有的能直接看到，有的需要提取，修补后的magisk_patched.img文件在download文件夹,oplus.fstab需要解包boot文件才能看到
> 
> 我知道magisk_patched.img文件在download文件夹。原boot.img的ramdisk目录都是空的。你说的这个oplus.fstab文件是在哪里？

这个方式适合我这台realmex50proplay，今天系统更新，我直接解包boot后只修改了ramdisk/oplus.fstab，然后打包修补（21100），root可用，未测试未修改修补是否可行，毕竟未更新仍是21100

**Comment by deepsea887** [comment]
pixel 3屡试屡败

**Comment by leihen** [comment]
> pixel 3屡试屡败

你使用的什么版本？之前看到过pixel3使用canary通道修补boot，成功获取root了，应该不需要修改什么吧

**Comment by leihen** [comment]
> pixel 3屡试屡败
自定义通道试试这个呢
https://raw.githubusercontent.com/Oosl/Magisk_Disable_ALL_Modules/master/disable.json

**Comment by deepsea887** [comment]
> > pixel 3屡试屡败
> 
> 你使用的什么版本？之前看到过pixel3使用canary通道修补boot，成功获取root了，应该不需要修改什么吧

当时是R刚出来的时候，刷了11.0.0 (RP1A.200720.009, Sep 2020)，在9月底看到吴大大上发推说用canary没有问题，但是我试了却不行。

**Comment by scarlet-glass** [comment]
> > > > 请问这个文件是在哪个路径下啊？ @leihen
> > > 
> > > 
> > > 你是问哪个文件的路径？boot文件提取需要去你所使用的刷机包里提取，有的能直接看到，有的需要提取，修补后的magisk_patched.img文件在download文件夹,oplus.fstab需要解包boot文件才能看到
> > 
> > 
> > 我知道magisk_patched.img文件在download文件夹。原boot.img的ramdisk目录都是空的。你说的这个oplus.fstab文件是在哪里？
> 
> 这个方式适合我这台realmex50proplay，今天系统更新，我直接解包boot后只修改了ramdisk/oplus.fstab，然后打包修补（21100），root可用，未测试未修改修补是否可行，毕竟未更新仍是21100

那可能需要作者那边去更新修复了

**Comment by Davidyz** [comment]
> > > pixel 3屡试屡败
> > 
> > 你使用的什么版本？之前看到过pixel3使用canary通道修补boot，成功获取root了，应该不需要修改什么吧
> 
> 当时是R刚出来的时候，刷了11.0.0 (RP1A.200720.009, Sep 2020)，在9月底看到吴大大上发推说用canary没有问题，但是我试了却不行。

是可以的，但是需要把systemless host禁用掉不然会死机（手持pixel 3 十一月安全补丁，刷了21.1 beta版的magisk）

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.
