### ISSUE TITLE
Modules fail to install in TWRP on Magisk 21.1

### ISSUE THREAD

**Issue by gossbill** [topjohnwu/Magisk#3493]
I have Magisk 21.1 (21100, beta) installed. I've found that trying to flash a module in TWRP gives an error 127 due to "xargs: /data/adb/magisk/busybox: No such file or directory". (See line 766 and following in recovery log).
However, if I first flash the Magisk zip (line 796ff) and then the module (line 935) it works.

After rebooting the phone (just rebooting recovery doesn't cause the issue) the installation of modules will fail again.

Notes:
- see also the discussion starting here https://forum.xda-developers.com/showthread.php?t=2239421&p=83926347
- I've also tried MagiskHidePropsConf-v5.3.6 and I get the same error
[21.1-module-recovery.zip](https://github.com/topjohnwu/Magisk/files/5543087/21.1-module-recovery.zip)

**Comment by topjohnwu** [comment]
Fixed
