### ISSUE TITLE
Magisk do not autoinstall after update LineageOS 

### ISSUE THREAD

**Issue by BigmenPixel0** [topjohnwu/Magisk#3496]
When I updated LineageOS through Updater, I must go to Magisk Manager and install Magisk to another slot without reboot. (Yandex Phone, Android Q, A/B, SAR)

**Comment by BigmenPixel0** [comment]
On devices without Treble support Magisk have autoinstall after update

**Comment by topjohnwu** [comment]
This is an limitation of how LineageOS's OTA is setup
