### ISSUE TITLE
Upgrade to v21.1 Won't boot, Reverting to 20.x still won't boot

### ISSUE THREAD

**Issue by diabl0w** [topjohnwu/Magisk#3497]
Hi everyone,
going to perhaps provide too much info, since I am not sure what is relevant:

I have a chinese device, Onyx Boox Max3. Recovery with the device is difficult if magisk/modules go wrong (no twrp for device, and no hardware buttons for safe mode). After trying to update to v21.1, my device will no longer boot...

I have a magisk module, called foxy-boot, that changes my boot screen into a bootlog. So if I see the normal bootscreen on boot, I already know there is a problem. I thought, no big deal after the issue, because I had a patched boot img on my computer to fastboot boot from.
The problem is, after fastboot booting the old magisk-patched img (running magisk v20.x), the device still will not boot. However, it must get farther in the boot process because it at least loads the foxy-boot module that shows the bootlog on bootup. This means that somehow installing magisk v21.1 changed something in my /data/adb, otherwise I should have been able to boot right up with the old image, back to pre v21.1 status. 

I can see in the foxy-boot logs that I am getting an error "zygote onrestart unable to write to file /sys/power/state, unable to write file contents: invalid arguement" and that error loops while trying to boot.
I am not really seeking help to recover my device, I think I can figure it out. But I would like to help somehow provide logs or whatever is needed to help fix magisk 21.1 so that it can work on my device.

**Comment by diabl0w** [comment]
update: so not being able to boot and all the other issues I had are related to the Quickstep magisk module I installed. The module creates an overlay.d in /data/ , but the problem is that the overlay is only available when the device boots with magisk and the quickstep module. if the device boots in an unrooted mode, android stock tries to find the overlay and it fails, therefore it won't boot. therefore, not booting after the update was merely a symptom of not having root after reboot because upgrading to v21.1 somehow failed.
**That being said** the question remains, why did upgrading to v21.1 cause my device to completely lose magisk?

**Comment by diabl0w** [comment]
update2: installing v21.1 a second time has succeeded. I am 100% positive the only difference between the first and second install was the disabling of the Quickstep module. I am not sure if that means that this is the root cause of the problem though, as I have no actual log evidence. Technically this is solved, but I am not sure if this should be looked into further to make sure magisk upgrades are compatible with the user's current installed modules. I think I am going to leave this issue open, but feel free to close if you feel otherwise, and if you need some logs or something let me know

**Comment by winstonma** [comment]
Hi @diabl0w, I own a Onyx Boox Nova and I would like to apply Magisk on it. However after several attempts I still have trouble obtaining the kernel image.

So would you mind sharing how could you obtain the kernel from your Max 3? Thanks

**Comment by diabl0w** [comment]
> Hi @diabl0w, I own a Onyx Boox Nova and I would like to apply Magisk on it. However after several attempts I still have trouble obtaining the kernel image.
> 
> So would you mind sharing how could you obtain the kernel from your Max 3? Thanks

does that device have an unlocked bootloader?

**Comment by winstonma** [comment]
> 
> 
> > Hi @diabl0w, I own a Onyx Boox Nova and I would like to apply Magisk on it. However after several attempts I still have trouble obtaining the kernel image.
> > So would you mind sharing how could you obtain the kernel from your Max 3? Thanks
> 
> does that device have an unlocked bootloader?

I really am not sure. But Onyx Boox Nova uses Rockchip RK3288 and I could dump and restore the image in the fastboot mode. I wrote my procedures in this [article](https://medium.com/@winstonhyypia/how-to-backup-and-restore-android-system-on-rockchip-device-c7058098216) but really have no idea how to proceed.

**Comment by diabl0w** [comment]
> > > Hi @diabl0w, I own a Onyx Boox Nova and I would like to apply Magisk on it. However after several attempts I still have trouble obtaining the kernel image.
> > > So would you mind sharing how could you obtain the kernel from your Max 3? Thanks
> > 
> > 
> > does that device have an unlocked bootloader?
> 
> I really am not sure. But Onyx Boox Nova uses Rockchip RK3288 and I could dump and restore the image in the fastboot mode. I wrote the procedures in this [article](https://medium.com/@winstonhyypia/how-to-backup-and-restore-android-system-on-rockchip-device-c7058098216) but really have no idea how to proceed.

AFAIK if you do not have an unlocked bootloader, the device will refuse to boot even if you did manage to patch the boot.img with magisk. I do not know how to pull the image from rockchip devices, only Qualcomm. once you do pull the image.. just copy it to your device, install magisk manager, and tellagisk to patch the img on your sdcard

**Comment by winstonma** [comment]
> 
> 
> > > > Hi @diabl0w, I own a Onyx Boox Nova and I would like to apply Magisk on it. However after several attempts I still have trouble obtaining the kernel image.
> > > > So would you mind sharing how could you obtain the kernel from your Max 3? Thanks
> > > 
> > > 
> > > does that device have an unlocked bootloader?
> > 
> > 
> > I really am not sure. But Onyx Boox Nova uses Rockchip RK3288 and I could dump and restore the image in the fastboot mode. I wrote the procedures in this [article](https://medium.com/@winstonhyypia/how-to-backup-and-restore-android-system-on-rockchip-device-c7058098216) but really have no idea how to proceed.
> 
> AFAIK if you do not have an unlocked bootloader, the device will refuse to boot even if you did manage to patch the boot.img with magisk. I do not know how to pull the image from rockchip devices, only Qualcomm. once you do pull the image.. just copy it to your device, install magisk manager, and tell magisk to patch the img on your sdcard

Actually I use the tool to dump the boot.img and throw it to the Magisk Manager, apply the patch, and apply the patched boot.img. However it won't boot. Then I have to apply the original boot.img in order to get the device boot up.

Does it mean that I have an unlocked bootloader?

**Comment by diabl0w** [comment]
> > > > > Hi @diabl0w, I own a Onyx Boox Nova and I would like to apply Magisk on it. However after several attempts I still have trouble obtaining the kernel image.
> > > > > So would you mind sharing how could you obtain the kernel from your Max 3? Thanks
> > > > 
> > > > 
> > > > does that device have an unlocked bootloader?
> > > 
> > > 
> > > I really am not sure. But Onyx Boox Nova uses Rockchip RK3288 and I could dump and restore the image in the fastboot mode. I wrote the procedures in this [article](https://medium.com/@winstonhyypia/how-to-backup-and-restore-android-system-on-rockchip-device-c7058098216) but really have no idea how to proceed.
> > 
> > 
> > AFAIK if you do not have an unlocked bootloader, the device will refuse to boot even if you did manage to patch the boot.img with magisk. I do not know how to pull the image from rockchip devices, only Qualcomm. once you do pull the image.. just copy it to your device, install magisk manager, and tell magisk to patch the img on your sdcard
> 
> Actually I use the tool to dump the boot.img and throw it to the Magisk Manager, apply the patch, and apply the patched boot.img. However it won't boot. Then I have to apply the original boot.img in order to get the device boot up.
> 
> Does it mean that I have an unlocked bootloader?

it means it's locked... look up the adb commands to unlock the bootloader. if the commands succeed, then you can flash your bootimg and boot with magisk. if the commands fail, then it's not possible on your device

**Comment by winstonma** [comment]
> 
> 
> > > > > > Hi @diabl0w, I own a Onyx Boox Nova and I would like to apply Magisk on it. However after several attempts I still have trouble obtaining the kernel image.
> > > > > > So would you mind sharing how could you obtain the kernel from your Max 3? Thanks
> > > > > 
> > > > > 
> > > > > does that device have an unlocked bootloader?
> > > > 
> > > > 
> > > > I really am not sure. But Onyx Boox Nova uses Rockchip RK3288 and I could dump and restore the image in the fastboot mode. I wrote the procedures in this [article](https://medium.com/@winstonhyypia/how-to-backup-and-restore-android-system-on-rockchip-device-c7058098216) but really have no idea how to proceed.
> > > 
> > > 
> > > AFAIK if you do not have an unlocked bootloader, the device will refuse to boot even if you did manage to patch the boot.img with magisk. I do not know how to pull the image from rockchip devices, only Qualcomm. once you do pull the image.. just copy it to your device, install magisk manager, and tell magisk to patch the img on your sdcard
> > 
> > 
> > Actually I use the tool to dump the boot.img and throw it to the Magisk Manager, apply the patch, and apply the patched boot.img. However it won't boot. Then I have to apply the original boot.img in order to get the device boot up.
> > Does it mean that I have an unlocked bootloader?
> 
> it means it's locked... look up the adb commands to unlock the bootloader. if the commands succeed, then you can flash your bootimg and boot with magisk. if the commands fail, then it's not possible on your device

Never try that. Let me try that later

I assumed the device is unlocked (but I never run `fastboot flashing unlock` command) as it won't boot after I applied the patched boot.img. But I will double check that when I have time to touch my device today.

Thank you very much

**Comment by topjohnwu** [comment]
I only provide support when no modules is involved.

**Comment by winstonma** [comment]
@diabl0w I forgot to say. The Rockchip devices (e.g. Boox Nova, only the old version) has no fastboot mode. And as I can load the kernel to make the device failed to boot up. I guess the bootloader is unlocked.
