### ISSUE TITLE
Magisk makes device freeze ,lag and not usable.

### ISSUE THREAD

**Issue by bukyapavankumar** [topjohnwu/Magisk#3499]
From magisk 20.3 or so it happens.previously when I flash magisk once app was pre-installed and everything was in working fine.but from 20.3 or so or new method? I have to flash magisk once and then open the app and install it and reboot it .also when  u enable magisk hide it freezes.please fix this issue.
Device :asus zenfone max pro M1.force reboot was only option to fix this.but sadly my power button was broken and cannot do it.hence my device stayed dead.

**Comment by bukyapavankumar** [comment]
Why is this closed

**Comment by Didgeridoohan** [comment]
Because there's nothing here to work with. The least you could do is to follow the [bug report instructions](https://github.com/topjohnwu/Magisk#bug-reports).
