### ISSUE TITLE
Generated boot image does not boot on Moto X 2014

### ISSUE THREAD

**Issue by 5685C4A059D5** [topjohnwu/Magisk#35]
On the XT1095, flashing with supersu systemless already installed causes an error: using sukernel to restore ramdisk: Unable to restore ramdisk
Furthermore, flashing with stock boot image creates a broken boot image (causes "boot failed" on boot).

There is no log in /cache
This is the boot image with systemless supersu: https://my.mixtape.moe/dmkiew.win

This probably has something to do with super-bootimg having the same issue. I've opened an issue there, and attached the stock boot image.
https://github.com/phhusson/super-bootimg/issues/46

**Comment by topjohnwu** [comment]
Thanks, I'll check when I got time.

**Comment by 5685C4A059D5** [comment]
Looks like the problem was an old version of supersu (2.67). sukernel didn't have --cpio-restore, causing line 382 in the install script to exit with code 0 without actually doing anything. Maybe line 393 can be changed to notify this to the user.

After this I tried flashing magisk v9, however the generated boot image causes "boot failed" on boot, apparently the same issue as super-bootimg.
