### ISSUE TITLE
Xiaomi 10 pro  MIUI 12.2.1 install boot_patched.img failed

### ISSUE THREAD

**Issue by xspeed1989** [topjohnwu/Magisk#3502]
@topjohnwu 
my phone can boot after flash boot_patched.img, but the manager display magisk is not installed!

**Comment by equatorian** [comment]
I change update channel to Beta, and try patching the image again, after that it flashed successfully. installed version 21.1(21100)
I am using Xiaomi 10 on MIUI 12.2.2

**Comment by xspeed1989** [comment]
> I change update channel to Beta, and try patching the image again, after that it flashed successfully. installed version 21.1(21100)
> I am using Xiaomi 10 on MIUI 12.2.2

thanks, I flash magisk with zip mode successfully
