### ISSUE TITLE
Viper4android  drivers are not loading with magisk 21.1  in Samsung  s20 fe 

### ISSUE THREAD

**Issue by Bala8787** [topjohnwu/Magisk#3508]
I tried flashing  viper4android  2.7  magisk module with  magisk 21.1 and the drivers are not loading and showing unsupported  whereas  its working with magisk 20.4 version but getting  unable to remount  issue with magisk 20.4. Please  fix this issue in 21.1 version

**Comment by zgfg** [comment]
Are you sure it is about Magisk - V4A has been recently updated to v2.7.2.1 and to make it work on some devices: Settings, enable Legacy mode

**Comment by Bala8787** [comment]
I'm sure about this issue.its is due to magisk 21 if i downgrade to magisk 20.0 its loading viper drivers and processing. i have tried legacy mode and no luck .. Attached screenshot for your reference
![Screenshot_20201128-052853_ViPER4Android FX](https://user-images.githubusercontent.com/74846255/100489567-d7018f80-313a-11eb-9b35-f6b94ed95ab2.jpg)
![Screenshot_20201128-053309](https://user-images.githubusercontent.com/74846255/100489621-4bd4c980-313b-11eb-8cde-65899283bdf1.jpg)

**Comment by zgfg** [comment]
Ok maybe something specific on your phone. But I could attach you my sceeenshots how with Magisk Canary v21101, I have driver running and processing ok when I enable Legacy mode, and how driver goes to state Abnormal when I disable Legacy mode

**Comment by Bala8787** [comment]
with magisk 20.0 its working for same viper version any idea? it's not about on my phone many of the users facing this issue on Samsung devices. attached the xda blog screenshot
https://forum.xda-developers.com/android/apps-games/app-viper4android-fx-2-6-0-0-t3774651/page396/amp/
![Screenshot_20201128-055202_Brave](https://user-images.githubusercontent.com/74846255/100490011-12518d80-313e-11eb-8e16-06b48bfa12ce.jpg)

**Comment by zgfg** [comment]
I don't know that way since I moved to Magisk v21 much earlier than V4A was updated - I happily used previous V4A version with no issue

Only when V4A was updated I had Abnormal state and it took me an hour or so to realize that I needed Legacy mode to get it working (I don't recall if earlier V4A even had that Legacy mode option in Settings - I never needed, it worked out of the box)

**Comment by Bala8787** [comment]
just noted.. when i enable legacy mode with master filter and equaliser enabled in viper the audio volume goes high and again going down to normal volume within a sec.

**Comment by Iron-E** [comment]
This is still happening; there are many of us on the XDA thread. I've spoken to both authors of Viper and they're fairly certain it's magisk.

I have some logs I'll upload when I get to my computer that should help in the diagnosis.

It seems two things are required:

1. Magisk 20.0
2. SELinux Permissive

SELinux permissive should not be necessary as stated by TeamDeWit, they said that was also a hint something was wrong with Magisk.

Keep in mind I don't know a lot about the intricacies behind any of these projects, I've just been playing telephone for Dev teams and so I'm forwarding this along.

I'll @ you when I have the logs uploaded.

**Comment by rogacz1988** [comment]
I too have that bug.
