### ISSUE TITLE
Magisk v14.0 patch boot image failed on S8

### ISSUE THREAD

**Issue by parizene** [topjohnwu/Magisk#351]
Issue on Samsung S8 when patching boot image (Build: G950FXXU1AQH3) Are encrypted storage devices supported?

[BL_G950FXXU1AQH3_CL12050265_QB14545607_REV00_user_low_ship.tar.md5.zip](https://github.com/topjohnwu/Magisk/files/1282844/BL_G950FXXU1AQH3_CL12050265_QB14545607_REV00_user_low_ship.tar.md5.zip)

![screenshot_20170907-010238](https://user-images.githubusercontent.com/419124/30137097-7633745a-936a-11e7-8a93-160e1c5ad9ad.png)

**Comment by SB13X** [comment]
The Boot.img you need to patch isn't found under BL. Its found under the bit of the fimrware package beginning with AP and needs to be opened and extracted with 7Zip.

**Comment by parizene** [comment]
@SB13X yes, my fault. patched boot.img from AP with no problem. the only issue is:
ctsProfile: false, basicIntegrity: false
![screenshot_20170912-234921](https://user-images.githubusercontent.com/419124/30347551-2481ec36-9815-11e7-8f40-8dd7d23b746a.png)
