### ISSUE TITLE
Problem：Android crash dumper failed to attach process because magisk already took its role

### ISSUE THREAD

**Issue by eebssk1** [topjohnwu/Magisk#3514]
Android 10 MiUI 12
This is found by chance when I debug a edxposed error.
https://github.com/ElderDrivers/EdXposed/issues/643
This make it a bit hard when no access to adb.And I checked as the log said there's no such dump for it in tombstone directory.

I don't know if this can be solved since magisk widely use ptrace for it to function...

**Comment by slimshouki** [comment]
Same here
Bootloop on stable xiaomi.eu 12
After updating edxposed to  0.5.0.6.4568
Riru core to v22

**Comment by eebssk1** [comment]
> Same here
> Bootloop on stable xiaomi.eu 12
> After updating edxposed to 0.5.0.6.4568
> Riru core to v22

please post this issur to edxposed repo,not magisk.

**Comment by eebssk1** [comment]
Disable magisk hide should do,looks like there's no other way.Feel free to close.
