### ISSUE TITLE
XiaoMi 10 ultra upgrade magisk from 21000 to 21100 failed

### ISSUE THREAD

**Issue by Jssmme** [topjohnwu/Magisk#3515]
can not boot devices success 
keep rebooting inf times

**Comment by troublewind** [comment]
the same, XiaoMi 10 stable miui12 (Android Q), above 21005 (21006~21101) all can't successfully enter the system, whether patch boot or twrp flash zip.
小米10 穩定版MIUI12 Android Q，只有刷入21005以下才能正常啟動，21006以上都會卡在第一屏一直重啟，修補boot和卡刷方式都試過了，但是開發版Android R的刷最新版貌似沒問題。

**Comment by Jssmme** [comment]
miui 12.0.13 stable here official package
android  10

**Comment by coderstory** [comment]
作者好像不管miui了

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.
