### ISSUE TITLE
Cubot X19 Says Ramdisk No but works with patched boot not recovery

### ISSUE THREAD

**Issue by sale2000** [topjohnwu/Magisk#3516]
Again one more  Shenanigans...

https://github.com/topjohnwu/Magisk/issues/3239

![cubot-x19](https://user-images.githubusercontent.com/35148108/100143901-4a36a780-2e96-11eb-9ecd-22c9d291ed08.png)

May be you can add https://topjohnwu.github.io/Magisk/install.html#patching-images

NOTE: Devices can crazy; try patching boot if recovery does not work - even if ramdisk is NO.

**Comment by zgfg** [comment]
It's been always the case also for Xiaomi, MIUI 10-12, Android 9-10 - Ramdisk No but patching boot.img yes

**Comment by topjohnwu** [comment]
It is something special with Xiaomi, which is an *exception*, thus not written in the instructions.
