### ISSUE TITLE
Magisk failed to mirror /system in CM11

### ISSUE THREAD

**Issue by FerryAr** [topjohnwu/Magisk#3519]
Device : Samsung Galaxy Young 2
Android version : 4.4.2
ROM : CM11
log : [magisk.log](https://pastebin.com/kPfpKr9k)

Also when I look magisk log via Manager, it crashed : [logcat](https://pastebin.com/98tGVTuJ)

Magisk v21.1
Magisk Manager v8.0.3

**Comment by roshantiwari434** [comment]
I'm too facing this issue. Let me know if you find any solution.
Right now I'm trying twrpupdate guide about installing [magisk zip](https://twrpupdate.com/download-latest-magisk-zip/). What process you're following to installing magisk.

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.
