### ISSUE TITLE
Periodic updater will always vibrate no matter what

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [topjohnwu/Magisk#3522]
I have managed to disable vibration on my phone entirely, except for when the phone is rebooting and except when . . Magisk's periodic updater finds an update. I would like an option to disable that vibration. Better: the notification should vibrate if the system is set to vibrate-on-notifications and not otherwise.

Magisk 20.4
'Manager' 8.0.3 (though actually I encountered the version before updating Magisk.)
Android version: Lollipop

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/commit/a4c48847d1a459041cc46fbc40036c61024561d5

**Comment by LinuxOnTheDesktop** [comment]
Thanks. However, I am unclear what you have done. Have you made the manager vibrate only when Android is set to vibrate for notifications?

**Comment by LinuxOnTheDesktop** [comment]
@topjohnwu 

Please answer the question that I ask in my post that is immediately about this post.
