### ISSUE TITLE
Modified system/build.prop does not work

### ISSUE THREAD

**Issue by foobar66** [topjohnwu/Magisk#3525]
I have a module in which I want to use a modified system.build prop.
Module itself works fine.
When I do:
# cat /system/build.prop
on the phone, I can see the modified properties
However, if I do:
# getprop XXX
then I still see the property as it was defined in the original system/build.prop
So, are the properties in system/build.prop read BEFORE magisk mounts the file?
I can see that Magisk properly bind_mounts the file:
>>> 11-29 09:53:43.830   727   728 I Magisk  : bind_mount: /system/build.prop

**Comment by Displax** [comment]
You do not need to replace *.prop files directly, you need to use resetprop instead.

**Comment by foobar66** [comment]
Yes, but even when using resetprop, still for some properties it looks like the value is not changed but taken from system/build.prop? Could that be the case?
