### ISSUE TITLE
Patched recovery.img on Unisoc device

### ISSUE THREAD

**Issue by mccalas89** [topjohnwu/Magisk#3528]
Hi, recently got a Blu phone (G60/V70 from Best buy) with a Unisoc sc9863a. In order to root with Magisk, patching recovery image was necessary. 

However, flashing the Magisk patched image hangs on writing (for minutes until manual reboot). In order to solve this, a custom vbmeta.img must be produced and flashed first; then, the magisk_patched.img must be signed using the same (custom) key linked in the custom vbmeta using avbtool. 

1) this works with Magisk Manager 8.0.3 patched images. 

2) the latest canary Manager patched images, however, do not. They're too large in size (and have other unnecessary footer information) and aren't recognized as a vbmeta image by avbtool, so they can't be used to root these devices.

Edit: Magisk MANAGER

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.
