### ISSUE TITLE
Magisk fails to patch kernel on Moto G7 Play

### ISSUE THREAD

**Issue by pbarrette** [topjohnwu/Magisk#3529]
The G7 Play appears to be a 2SI device.
A ramdisk exists in the boot image, which is recognized by Magisk Manager 7.5.1, 8.0.3 and 1469b82a (315).
Inspection of the ramdisk shows that "/init" is a symlink to "/system/bin/init"

Things appear to go wrong when Magisk reports KERNEL_FMT = raw:
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
```
HEADER_VER      [1]
KERNEL_SZ       [10267097]
RAMDISK_SZ      [7522715]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-10]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyMSM0,115200,n8 androidboot.console=ttyMSM0 androidboot.hardware=qcom user_debug=30 msm_rtb.filter=0x237 ehci-hcd.park=3 androidboot.bootdevice=7824900.sdhci lpm_levels.sleep_disabled=1 earlycon=msm_hsl_uart,0x78af000 androidboot.usbconfigfs=true vmalloc=300M loop.max_part=7 printk.devkmsg=on androidboot.hab.csv=20 androidboot.hab.product=channel androidboot.hab.cid=50 buildvariant=user veritykeyid=id:b640f6ee9102b88daa3450b13ef25fc9eb143d63]
CHECKSUM        [d7faf8147e5649ddce2900c66733bda96a726280000000000000000000000000]
- Unpacking boot image
KERNEL_DTB      [304833]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
```

Full log: [magisk_install_log_2020-11-30T000701Z.log](https://github.com/topjohnwu/Magisk/files/5614754/magisk_install_log_2020-11-30T000701Z.log)

The attached [boot image](https://github.com/topjohnwu/Magisk/files/5614570/boot.zip), zipped for size, has a gzip image at offset 0x51BC, but it isn't recognized by the patcher. This is probably because of the header.

Using Magisk Manager v7.5.1 with the custom channel [here](https://github.com/pbarrette/magisk751/blob/main/beta.json) allows me to patch my boot.img with Magisk v21.1 using the advanced Recovery option.
Once the magisk_patched.img is flashed to boot, Magisk is active only when the device is first put into fastboot mode, then booted into recovery via the fastboot menu.
Booting into recovery by any other means (vol-up+power, adb reboot recover, Magisk Manager reboot options) cause the system to boot normally and Magisk isn't active.

Once magisk is active, MM displays "Ramdisk: No".
Updating Magisk, however, fails because the Magisk binary correctly notes that there is a ramdisk, but because of the zImage recognition issue, it does not get patched.

When this occurs, Magisk becomes inactive regardless of boot method, having replaced the working method with one which does not function.

**Comment by pbarrette** [comment]
Ah. So it's actually a 32bit, ramdisk based, S2I, A/B thing with the legacy zImage type mentioned here: https://github.com/topjohnwu/Magisk/issues/1674.

I understand why you wouldn't want to tackle trying to fix the issue. The patched compressed kernel must be the exact same number of bytes as the original in order to keep the offsets correct. I got really close (1 byte off) just by "gzip -9 -n file", but still had to tweak some compile dates to get it exactly right. That's a judgement call and not something I'd want to tackle via full automation.

Still though, perhaps instead of producing a magisk_patched.img file and saying everything went great, you could trap the error out of "magiskboot hexpatch" and warn the user that the patch failed and it may be a known issue?

Also great would be a way to override the auto-recognition and allow patching in recovery mode again.

Maybe the title of this one should be: Magisk **silently** fails to patch kernel on Moto G7 Play.

**Comment by topjohnwu** [comment]
If your device is really 2SI, the kernel does not need any patch at all, which is why it works with recovery mode.

**Comment by pbarrette** [comment]
Ok. I'll trust your judgement on that.

The problem remains that Magisk, for this device:
1 - Fails to notify that the kernel couldn't be patched.
2 - Doesn't allow the option to patch in recovery mode.
3 - Produces a patched boot image that doesn't work in either normal, or recovery mode.

It seems that line 166 of [boot_patch.sh](https://github.com/topjohnwu/Magisk/blob/master/scripts/boot_patch.sh) reports an exit code of 1, which seems like something that could be trapped and produce a warning message or error.

Magisk Manager 7.5.1 allowed an override in the advanced options which would allow you to target recovery mode. From what I can tell, it just set the $RECOVERYMODE environment variable.

Since the G7 Play doesn't have a recovery partition, and, so far as I can tell, no recovery_dtbo, neither Magisk Manager nor the installer scripts will properly patch a boot image.

That leaves only 3 ways to get a working Magisk install:
1 - Install an older version of Magisk Manager, point it at a custom channel, and manually select Recovery Mode.
2 - Use an ADB shell to execute the script with "$RECOVERYMODE=true"
3 - Unpack, patch kernel, and repack your boot image by hand.

**Comment by xenomorph3613** [comment]
Sorry topjohnwu, but pbarrette seems correct and definitely accurate in his big report. Since Magisk 7.5.1 its gotten worse with the G7play. Too bad you can regress development of ther Magisk as it seems older versions work better all around. I don't really care for the new interface on MM 8.x.x. Why not leave things as they were. If they weren't broke don't fix.

**Comment by pbarrette** [comment]
That seems a bit harsh @xenomorph3613.

Personally, I'm growing to like the new interface, even if it was a bit confusing at the start.

I can understand how this isn't necessarily a simple problem to fix. The devs here have different priorities and a very large base of users who are likely to get themselves into trouble if the manual selection of recovery mode is exposed to those users. Of course, anyone modding their boot image should already be aware of potential trouble, but if you break booting entirely, that's on a different scale of problems compared to Magisk not working.

This leaves the G7 Play (and probably a few others) in the minority of the user base. The reality is that it works for most people and the hardest thing about writing code is handling all the edge cases like ours in a way that doesn't turn the entire code base into edge case handling.

For example: If the installer script fails to patch the kernel, my guess is that's perfectly OK for most cases. The script indiscriminately tries to hexpatch some Samsung specific items. Those patches fail on all non-samsung devices. So you need to figure out exactly when it's not OK if the "skip/want" hexpatch fails.

I don't know what the decision chart looks like for most devices. Maybe IF (KERNEL_FMT = raw && RAMDISK_SZ != 0 && HEXPATCH = failed) would be enough to trigger a warning, but I again, don't know. Maybe it would take a new function like "magiskboot findhex kernel 736B69705F696E697472616D667300" to determine when recovery mode should be triggered for devices like ours.

Either way, it's not entirely trivial.

**Comment by topjohnwu** [comment]
@pbarrette your situation seems a bit weird here. If your device does not have a recovery partition, then the recovery mode option is **definitely NOT** designed for you.

The fact that enabling recovery mode works is bizarre, because it does not actually change any behavior of Magisk itself, but rather an indication for Magisk Manager to install to the correct location subsequently.

Can you upload the output of this command in ADB shell? `cat /proc/mounts`

Thanks

**Comment by pbarrette** [comment]
@topjohnwu 

I am currently away from any computer which would allow me to replace the device's boot image with the stock version. Instead, I have attached a copy of /proc/mounts taken from the device with magisk installed and working from a normal, system boot.

This instance was installed by:
- Unpack boot image with AIK
- Extract kernel gz with hex editor.
- Patch skip / want with hex editor.
- Re-gzip to original size by tweaking build timestamp values in kernel.
- Re-insert gz to kernel image via hex editor.
- Re-pack with AIK.
- Patch image with magisk on device with MM 7.5.1 and custom channel.
- Fastboot flash boot.

[proc-mounts.txt](https://github.com/topjohnwu/Magisk/files/5720934/proc-mounts.txt)

The soonest I can provide output from an unmodified boot would be the 3rd of January.

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.
