### ISSUE TITLE
MagiskR - patch for Xiaomi Mi 9T, A11 beta?!

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#3534]
As claimed elswhere (I didn't try A11 beta myself), the only way to install Magisk to Xiaomi.eu A11 beta for Mi 9T requires:
- flashing through TWRP MagiskR.zip
https://mega.nz/file/R9lwQbaA#od4dnJOm-cx9bEaufdpqZb9dDxCM5l96l-qu8Oi8sLA
- then flashing Magisk Canary 21.1

Patching or just flashing Canary does not work (as they claim)

More info:
http://t.me/RedmiK20GlobalOfficial

Unfortunately, couldn't find who/where was the author

There are similar zips (under the other names) for installling Android 11 to the other Xiaomi phones

IMO, it would be of interest to reverse engineer and to include the fix into the Canary itself

**Comment by zgfg** [comment]
@topjohnwu

**Comment by vvb2060** [comment]
Magisk use GPL 3.0, You should ask them for the source code.

**Comment by Sanzium** [comment]
> 
> 
> Magisk use GPL 3.0, You should ask them for the source code.

Problem is that nobody seems to know where these modded zips come from. Another one is called "magisk_debug (2).zip", here is a copy in case it helps: https://drive.google.com/file/d/19fOJd83UxhvfW16ckg5S2ORwK8YaVTxj/view?usp=sharing
It's used in MI 9 Android 11 roms, but I have also seem it mentioned on the MI 10 forum on xiaomi.eu, on OnePlus 6 forum on XDA and on Mi 9T and Redmi Note 8 on 4pda.
There is something quite interesting about it, it has in util_functions.sh MAGISK_VER="MODDED" and MAGISK_VER_CODE=42069. This version code, when you type as a commit in a github url, actually shows a commit, but says it's from a fork. I don't know if it is possible to know which fork.

**Comment by zgfg** [comment]
> Magisk use GPL 3.0, You should ask them for the source code.

Please read what I wrote:
"Unfortunately, couldn't find who/where was the author"

Canmot ask if cannot find who is the author

**Comment by vvb2060** [comment]
The author of MagiskR is topjohnwu, the file you provided is exactly the same as https://github.com/AnErW/magisk_files-1/commit/615321c218c9e2a53c50eff74fd67b1b3c72157f

**Comment by vvb2060** [comment]
https://github.com/AnErW/magisk_files-1/commits/canary 
Start testing from 61599059, can you test which version can't be used since?

**Comment by zgfg** [comment]
> https://github.com/AnErW/magisk_files-1/commits/canary
> Start testing from [6159905](https://github.com/topjohnwu/Magisk/commit/61599059d5dd76d3994a33edaf8e2e77c5455bac), can you test which version can't be used since?

Unfortunately, all json files point to the same, (latest) magisk-debug.zip - same URL:
https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/magisk-debug.zip
They don't point to the Canary release for that particular version whose version number is listed in the json file

Nevertheless, cannot test since I don't have (unstable) A11 beta on my daily driver Mi 9T

**Comment by vvb2060** [comment]
?

**Comment by zgfg** [comment]
> If you don't understand how to test, I will wait for other people's test results.

I do understand how to test but don't have device to test!

**Comment by vvb2060** [comment]
xiaomi 9/9T/9T pro，redmi k20/k20p，Realme XT (RMX1921)，Realme X (RMX1901)
With the help of others, I have found the cause of the problem.

**Comment by Sanzium** [comment]
> xiaomi 9/9T/9T pro，redmi k20/k20p，Realme XT (RMX1921)，Realme X (RMX1901)
> With the help of others, I have found the cause of the problem.

I was going to test, so there's no need anymore?

**Comment by vvb2060** [comment]
The problem has been confirmed.

**Comment by Sanzium** [comment]
Ok, thank you!

**Comment by pndwal** [comment]
> xiaomi 9/9T/9T pro，redmi k20/k20p
> With the help of others, I have found the cause of the problem.


Just for my understanding, is a fix among these ("patch collection") commits being pushed?
https://github.com/topjohnwu/Magisk/pull/3533

Can you say which problem, and if fix is included in your latest Alpha build?
https://github.com/vvb2060/magisk_files/tree/alpha
👍 PW

**Comment by zgfg** [comment]
Closing the ticket - issue fixed with today's Magisk Canary 21102, Magisk Manager 316

Btw, in the meantime I have installed 
MIUI 12.3/Android 11 Beta 20.12.10  
to my Xiaomi Mi 9T to be able to test

Now with Canary v 21102 (just like with v20422=MagiskR), I can patch my original boot.img from Xiaomi Mi 9T Xiaomi.eu, without causing bootloop (booting was failing to Fastboot) and without the need to root first with Magisk 20422

Yesterday I have also successfully tested alpha pre-release from@wb2060

All Canary releases 20423-21101 had the issue - 20422 was ok and now 21102 is also ok 👍👍👍

**Comment by zgfg** [comment]
More details about testing:

https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-84135245

https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-84137125
