### ISSUE TITLE
Slowing down the Android Pie 9.0

### ISSUE THREAD

**Issue by Geagichi** [topjohnwu/Magisk#3535]
Hi guys, I've installed Galaxy S5 Plus SM-G901F Lineage OS 16.0 Android Pie 9.0 Official ROM and I was so happy 'till I've installed Magisk 21.0 Riru v21.3 | Riru - EdXposed v0.4.6.4 (SandHook) and Xposed Installer v 3.1.4 by dvdandroid. It's slowing my phone. When I open YouTube or anything else It takes some time to open them and when I have multiple applications opened it's barely loads them. I don't know what to do can anyone help me with an advice or anything else? Please guys.

**Comment by MJRweb** [comment]
这些框架一般不是影响开机速度嘛，开APP应该不影响吧，建议在edxp里面那个优化一下

**Comment by Geagichi** [comment]
> 这些框架一般不是影响开机速度嘛，开APP应该不影响吧，建议在edxp里面那个优化一下

So how do I optimize the boot speed? Should I uninstall Magisk and edxposed?
