### ISSUE TITLE
Please open source stub source code

### ISSUE THREAD

**Issue by jpfe1005** [topjohnwu/Magisk#3537]
I know that the stub source code is not made public to avoid targeted detection, so can you open source the original code? No obfuscation, no anti-detection, just the basic functionality of stub. This way we can modify and build it ourselves, completely different from your version. I know that your version will change its name periodically, but that's not enough, I want the superuser management application to be completely open source.
Also, I didn't receive any warning about using closed-source code when hiding, and I only discovered this fact when I couldn't find the source code, which worries me.

**Comment by TheK0tYaRa** [comment]
You know that you can reverse-engineer anything that is patched if you just try, right?

**Comment by unixandria-xda** [comment]
All of magisk is open source, the source that you are looking for is under the aptly named stub/ folder at the root of this repository. Please close this issue

**Comment by jpfe1005** [comment]
@osm0sis I think @unixandria-xda  may not understand magisk and made the wrong comment, but you shouldn't. As a collaborator, you should know that stub isnot open source. Because of 2e4dc91b964597016eecf007a14dfea0ad1d4fb2, the previously open source stub(c3968a26cf4220941ecb8e48fd8d3b2452935e30) can no longer be used normally.

**Comment by jpfe1005** [comment]
Please reopen this issue

**Comment by jpfe1005** [comment]
@TheK0tYaRa Don't you think it would be ridiculous to mention decompilation in a software that claims to be 100% open source?

**Comment by jpfe1005** [comment]
I fully understand that the safety net is not open source and am satisfied with the pre-use warning. But with stub, there is no pre-use warning, and there is a deliberate attempt to confuse the **two** stubs in fact, and try to mislead others that stub is open source.

**Comment by osm0sis** [comment]
I think @topjohnwu has been pretty clear he won't open source the updated stub.

**Comment by jpfe1005** [comment]
I never asked for open source safety net, I just asked for the original stub to be open sourced so that the hidden features of the manager would work.
If you think this issue is wontfix, please stop promoting Magisk as completely open source software and add a warning about the closed source code before hiding magisk manager.

**Comment by topjohnwu** [comment]
I removed the code because it is extremely frustrating to maintain 2 different code sets.
TBH, 99% of hiding logic lies in the main APK, not in the stub. If I got some time, I can try to implement a simple dumb loader.

**Comment by mcdoe** [comment]
Hey @osm0sis is full snet reflective dex downloaded to /data/data/com.topjohnwu.magisk/snet/oat? If not how we snag it?
