### ISSUE TITLE
android 10 magiskhide and hide magisk manager issue

### ISSUE THREAD

**Issue by willyyyyy1** [topjohnwu/Magisk#3538]
hello  John Wu
my phone is Redmi K30
use android 10 
and i use twrp 
install magisk 21.1 success
![297533](https://user-images.githubusercontent.com/16967188/100745998-140ba180-341b-11eb-9d6a-87b75696812c.jpg)
Q1. but i wnat hide magisk manager  always failed......
![297519](https://user-images.githubusercontent.com/16967188/100745356-233e1f80-341a-11eb-80aa-b6294afa6d78.jpg)
Q2.  i use magisk hide to hide some bank app
but when i open bank app  
show some tip your phone rooted not safe
so i thnk magisk hide can't use on my phone..

**Comment by unixandria-xda** [comment]
Disable play protect, this is a known issue.

Also do not report issues unless you're on canary, and close this issue

**Comment by willyyyyy1** [comment]
> hello John Wu
> my phone is Redmi K30
> use android 10
> and i use twrp
> install magisk 21.1 success
> ![297533](https://user-images.githubusercontent.com/16967188/100745998-140ba180-341b-11eb-9d6a-87b75696812c.jpg)
> Q1. but i wnat hide magisk manager always failed......
> ![297519](https://user-images.githubusercontent.com/16967188/100745356-233e1f80-341a-11eb-80aa-b6294afa6d78.jpg)
> Q2. i use magisk hide to hide some bank app
> but when i open bank app
> show some tip your phone rooted not safe
> so i thnk magisk hide can't use on my phone..

**Comment by variainfantry155** [comment]
[]()
