### ISSUE TITLE
Samsung SM-T590 incompatibility

### ISSUE THREAD

**Issue by UDPSendToFailed** [topjohnwu/Magisk#3539]
I tried to root my SM-T590, but it seems like Magisk is not compatible with the device. 

Steps I have followed:

- Download the latest Magisk Manager from releases, download the FW with matching version as on my device
- Extract boot.img from the FW and decompress boot.img.lz4 using LZ4 command line tool
- Patch boot.img in Magisk Manager (in the original guide there was also a step to enable "Keep AVB2.0/dm-verity", but that's missing from Magisk Manager, so I skipped it)
- Adb pull the patched boot.img back to my PC
- Enable OEM Unlock on the tablet, after the factory reset has finished, set it up and turn it off
- Boot into recovery mode, from here boot into bootloader mode
- Compress the boot.img into a .tar archive using 7-Zip, since Odin doesn't support .img filetype
- Select boot.img.tar to AP in Odin, start flashing, and this is where it failed, the tablet says "Only official released binaries are allowed to be flashed"

Also, I have attached a screenshot of Odin. 

![image](https://user-images.githubusercontent.com/16057404/100797771-f2161d00-3422-11eb-9f1b-01818f7e0233.png)

Thanks a lot for help!

**Comment by UDPSendToFailed** [comment]
Solved, the bootloader wasn't unlocked, connecting the tablet to WiFi did the trick.

**Comment by UDPSendToFailed** [comment]
Edit: Not really solved, it doesn't boot, ask me to do a factory reset due to missing dm-verity bypass :/

**Comment by unixandria-xda** [comment]
This is outside the scope of magisk.

Please ask in your device specific thread on XDA or similar, and close this issue.

**Comment by UDPSendToFailed** [comment]
Okay, finally I managed to do it with installing TWRP, wiping data, flashing _Disable_Dm-Verity_ForceEncrypt_08.18.2019.zip_ and then flashing the latest Magisk.zip from releases.
