### ISSUE TITLE
Flashing patched boot results in bootloop (SM-G715FN)

### ISSUE THREAD

**Issue by liorshwa** [topjohnwu/Magisk#3541]
Trying to root the Samsung Galaxy Xcover Pro (Exynos 9611, 2 vbmeta partitions : vbmeta, samsung_vbmeta, Android 10, G715FNXXS6ATG1 stock build)
Patched stock boot with magisk , flashed with odin, results in bootloop.
tried to flash an "empty" vbmeta (generated by avbtool ) after that which resulted in Download Mode with vbmeta error

There is no TWRP and no custom Roms for this device, i compiled TWRP from source but can't flash it because of vbmeta

would be really happy for some help with rooting this device, i have a physical device on me so i can pull any information needed ( as long as i have read permission for it ; )   )

is there a way to create custom signed vbmeta images to go along with custom binaries that we flash?
or is there a way to disable/ turn-off/ bpass AVB/ dm-verity altogether?

i read some articles about this device and i know it's SAR with Ramdisk, which means Magisk is installed into recovery.
the new magisk app doesn't have the "Advanced Settings" like the old one had so i can't disable dm-verity \ vbmeta and can't enable Recovery Mode, the only thing i can do is to create a patched boot.img

i tried following guides of the Galaxy A51 which has the same SoC but with no luck

the guide looked promising and had a lot of good feedback on xda but it didn't work for me (i got stuck at 24:28 when my phone was stuck in a bootloop and the phone in the tutorial booted succesfully after flashing patched boot)

Link to guide : https://www.youtube.com/watch?v=oZD2jkkKX_E&t=1572s

EDIT: Patching of boot.img was done using the latest version of Magisk 8.0.3(314)

**Comment by topjohnwu** [comment]
Please read the official installation instruction linked in README
