### ISSUE TITLE
Flashing magisk after hiding magisk manager cuses issues

### ISSUE THREAD

**Issue by sd3993** [topjohnwu/Magisk#3542]
Step 1 - Flash magisk 21.1 and hide Magisk Manager
Step 2 - Reboot to twrp and flash magisk again and reboot
Step 3 - Rom now has both hidden magisk manager and original one.

The original one needs to be manually uninstalled in order for the hidden one to work again.

UPDATE for better understanding :

After Step 3, The hidden manager does not even run until the original one is manually uninstalled.

Also, none of the magisk functions(like Magisk hide, root, etc) work until the original MM is uninstalled.

Prior to 20.4, the original MM would get automatically removed after boot(instead of needing to be removed manually).

**Comment by osm0sis** [comment]
That's not an issue, you just need to know which one to run.

**Comment by sd3993** [comment]
Can you please explain why this is not an issue?
The hidden manager does not even run until the original one is manually uninstalled.

Is this an intended behavior?
Prior to 20.4, the original MM would get automatically removed after boot(instead of needing to be removed manually)

**Comment by osm0sis** [comment]
Ah if that is a regression then you may be right

**Comment by vvb2060** [comment]
https://github.com/vvb2060/Magisk/commit/536ba88a1d886c441439fd9c44aabcaf36d83886 does not handle `/data/magisk.apk` when Magisk Manager is hidden, because stub is not open source ......
Problems affecting use have been fixed.

**Comment by qttc** [comment]
the same for me.
Is it possible to fix it without uninstalling and clearly install again?
