### ISSUE TITLE
How to proceed now?

### ISSUE THREAD

**Issue by DaniV5** [topjohnwu/Magisk#3546]
got a TCL C5 android 8.1
managed to unlock the bootloader

i don't have root right now but i could make a copy of boot and boot2 using mtk-su
i'm not sure why i have 2 boot files
magisk can patch boot

they are 24 MB and after magisk patch it goes to 7.7 MB is this correct?

is there any way to test if everything is correct before flashing?
i know fastboot can boot img files
would this work?

as i can copy everything from /dev/block i guess i can just reflash everything is i get a bootloop
but in the magisk doc it says to not try to flash the stock over magisk

so i'm not sure right now how i should proceed with this

**Comment by unixandria-xda** [comment]
This is not a support forum, please ask your question on xda or similar.

Please close this issue.
