### ISSUE TITLE
Hash Mismatch error after installing Magisk

### ISSUE THREAD

**Issue by liorshwa** [topjohnwu/Magisk#3550]
I followed the magisk installation guide for my device (Samsung Galaxy Xcover Pro, SAR and Ramdisk) and after flashing Patched_AP alongside BL, CP, and CSC . the phone reboots to download mode and i get avb Hash Mismatch error

**Comment by topjohnwu** [comment]
Samsung bootloader issue, cannot fix

**Comment by d5sword** [comment]
Same issue: #3637

I have found a workaround for this problem and successfully rooted that phone. See  #3637.
