### ISSUE TITLE
Nexus 5 issue with Magisk

### ISSUE THREAD

**Issue by sn-o-w** [topjohnwu/Magisk#3551]
The commit https://github.com/topjohnwu/Magisk/commit/ff0a76606e350931b6523aa894428011a4beb3ea prevents Nexus 5 from booting into Android. I only see Google logo and device self-restarts after every ~10 seconds showing same Google logo again and again. I made a short video: https://youtube.com/watch?v=aE3X-mqpZ1s

I dunno if I can collect somehow logs or other relevant info, but by reverting https://github.com/topjohnwu/Magisk/commit/ff0a76606e350931b6523aa894428011a4beb3ea phone boots into ROM.

**Comment by topjohnwu** [comment]
Should be fixed in later commits

**Comment by sn-o-w** [comment]
Yeah, I can confirm. Later commits fix the problem 👍
