### ISSUE TITLE
replace folder and repopulate it [possible?]

### ISSUE THREAD

**Issue by Sekkei** [topjohnwu/Magisk#3552]
Good day , I read the docu but couldn't find a satisfying answer 
How 'should' I do the following:
replace folder in system with empty one ( or unmount it ? )
and than create or mount it again with my files 

especially if I should mount or replace , and with methods for both of them 'should' I use to get the best compatibility with magisk ? 

Thank you in advance and for reading

**Comment by topjohnwu** [comment]
There is already a way, please read the docs more carefully and experiment it more yourself
