### ISSUE TITLE
Magisk v.21.1 bootloops LG G5 H830 (T-Mobile)

### ISSUE THREAD

**Issue by picorealm** [topjohnwu/Magisk#3553]
Have tested it thoroughly.  v.21.1 causes the LG G5 H830 to bootloop.  Only way to recover is to put phone in download mode and reflash stock ROM .kdz.

Using TWRP 3.4.0-1 and no-verity-opt-encrypt-6.1.zip

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.
