### ISSUE TITLE
How do I enable dm-verity again?

### ISSUE THREAD

**Issue by LoganDark** [topjohnwu/Magisk#3554]
I am experimenting with self-signing boot images and vbmeta and then relocking the bootloader of my phone for added security. I know custom roots of trust are supported because of the presence of an avb_custom_key partition in fastboot.

With a self-signed vbmeta, dm-verity should work with Magisk, correct? No boot loop or "error correction"?

Magisk Manager seems to be missing the option to preserve dm-verity now, I am using version 8(.0.3). I've seen older screenshots where there were two checkboxes at the bottom of the screen, below the SafetyNet test - where did they go?

**Comment by topjohnwu** [comment]
They are no longer used because they are no longer relevant with AVB 2.0

**Comment by LoganDark** [comment]
So re-locking the bootloader will enable dm-verity? Or is dm-verity not used at all by AVB2?

**Comment by google-mirror** [comment]
Locked BL does not trust avb_custom_key

**Comment by LoganDark** [comment]
> Locked BL does not trust avb_custom_key

Doesn't it do this on Pixel phones...? My phone is a OnePlus 7 Pro
