### ISSUE TITLE
Don't add microG to hide list automatically or create option to disable automatic adding

### ISSUE THREAD

**Issue by mityax** [topjohnwu/Magisk#3559]
I first noticed this when I was wondering why microG kept crashing on my newly set up device (Pixel 5/ProtonAOSP/Latest Magisk Canary/Latest MicroG + DroidGuard Helper). Apparently, it crashed because it was in the magisk hide list. When I remove it from the list, microG works perfectly fine.

However, each time I reboot my device, microG is added to the list again automatically. I guess it's done here: [hide_utils.cpp:197](https://github.com/topjohnwu/Magisk/blob/1e45c63ea5c7685e488625d42c14810f0cdcd3a6/native/jni/magiskhide/hide_utils.cpp#L197).

I'd suggest adding an option to the magisk settings to prevent this or, alternatively, adding a check at startup hide list initializing so microG doesn't get re-added if it has been removed manually before.

**Comment by lss4** [comment]
Guess this answered the strange phenomenon I observed with DroidGuard Helper in the Magisk Hide menu, which I didn't give more care about as I don't really care about Safety Net anymore.

In the Magisk Hide menu, unlike other apps, the DroidGuard Helper appears unchecked when not expanded, but it's actually checked underneath and the check mark only appears when expanded.
