### ISSUE TITLE
Magisk 21100 on December patch breaking things

### ISSUE THREAD

**Issue by jcxmt125** [topjohnwu/Magisk#3560]
After update to the December patch on my pixel 3, battery icon broke along with a few bugs here and there, wasn't there before flashing magisk after update. I am new, so I'm not sure how to help the investigation, so please tell me how and I'll do my best!

**Comment by topjohnwu** [comment]
This has nothing to do with Magisk itself. It is 100% caused by modules

**Comment by jcxmt125** [comment]
Sorry, confirmed it was the 9tiles module. Have reported it in the
appropriate place.
