### ISSUE TITLE
Doogee S88 Global bootloop

### ISSUE THREAD

**Issue by pieterhouwen** [topjohnwu/Magisk#3561]
When flashing the boot image after patching with Magisk the device enters a bootloop. 
When patching the boot image I don't see any errors.

Stock boot, patched boot and Magisk 20.4: https://mega.nz/folder/vcIwwJob#7e63HNUXN1eQrCFRLkc7JA

Can I do something myself to see how I can fix this?

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.
