### ISSUE TITLE
Magisk breaks Tidal

### ISSUE THREAD

**Issue by darkdex52** [topjohnwu/Magisk#3562]
Model: G780F
Android 10
Magisk 20.4 flashed through Odin

Installing Magisk root breaks Tidal completely. On stock rom Tidal works perfectly, but with Magisk, even with MagiskHide and renamed Magisk, Tidal hangs on playback on every song @19 seconds in exactly.

[catlog](https://pastebin.com/akZ8ZQUS)
[catlog2](https://pastebin.com/H4khadPQ)

**Comment by unixandria-xda** [comment]
> Model: G780F
> Android 10
> Magisk 20.4 flashed through Odin
> 
> Installing Magisk root breaks Tidal completely. On stock rom Tidal works perfectly, but with Magisk, even with MagiskHide and renamed Magisk, Tidal hangs on playback on every song @19 seconds in exactly.
> 
> [catlog](https://pastebin.com/akZ8ZQUS)
> [catlog2](https://pastebin.com/H4khadPQ)

#1152 

Please close this issue.

**Comment by darkdex52** [comment]
> > Model: G780F
> > Android 10
> > Magisk 20.4 flashed through Odin
> > Installing Magisk root breaks Tidal completely. On stock rom Tidal works perfectly, but with Magisk, even with MagiskHide and renamed Magisk, Tidal hangs on playback on every song @19 seconds in exactly.
> > [catlog](https://pastebin.com/akZ8ZQUS)
> > [catlog2](https://pastebin.com/H4khadPQ)
> 
> #1152
> 
> Please close this issue.

Issue is not related to MagiskHide but to Magisk being installed on the system itself.

**Comment by unixandria-xda** [comment]
> Issue is not related to MagiskHide but to Magisk being installed on the system itself.

But it is. If magisk is what's crashing it, 99% chance it's detecting root somehow. All you can do is try to enable magiskhide on it and close this issue

**Comment by unixandria-xda** [comment]
And this is all moot anyway, bug reports are only accepted for the latest canary version
