### ISSUE TITLE
permissions on .sh files in /vendor/ are not retained

### ISSUE THREAD

**Issue by foobar66** [topjohnwu/Magisk#3564]
I have a magisk module which overrides some xml files in /vendor/etc
/vendor/etc also contains 2 ".sh" files which mormally have execute permission.
However, magisk mounts them as:
   4 -rw-r--r-- 1 root root     2241 2009-01-01 01:00 vendor.memplus.sh
   4 -rw-r--r-- 1 root root  2872 2009-01-01 01:00 ftm_power_config.sh
So the execute permission is somehow lost in the bind moints.
I have tries to set it in post-fs-data.sh
that works, in the sense that I update $MODULE/system/vendor/etc but still once the system is booted and I check the 2 above files the execute permission is missing

**Comment by foobar66** [comment]
Sorry, my mistake, I thought that the files had to be executable but they are not executable on the original /vendor partition either. Is it correct that therefore, Magisk will NOT allow me to change the permissions (e.g. make the executable)?

**Comment by variainfantry155** [comment]
https://github.com/topjohnwu/Magisk/issues/3564#issue-760963466
