### ISSUE TITLE
Magisk v.21.1 bootloops Xiaomi Blackshark 3 KNE-A0

### ISSUE THREAD

**Issue by tunnelkeeper** [topjohnwu/Magisk#3568]
After installing Magisk v21.1 the device ends up in a bootloop. 
v21.0 does work ... 

Please let me know whats needed to discover the root issue here.

**Comment by LinnyR** [comment]
me too

**Comment by xbjfk** [comment]
It seems to me that the ramdisk detection is broken: magisk thinks my phone doesn't have a ramdisk in 21.1 but thinks it does in 21.0

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.
