### ISSUE TITLE
Magisk 21.1 and Android 11 Dec 2020 Patch

### ISSUE THREAD

**Issue by mizzpenny** [topjohnwu/Magisk#3569]
Installed the stock 11.0.0 (RQ1A.201205.011 Dec, 2020) patch for my pixel 5. I used Magisk to patch the boot.img file. Boot to bootloeader and flash the magisk boot file. Reboot and the phone would not boot up. It is just stuck on the G. After an hour, I gave up. Rebooted into bootloader and boot back to the stock boot.img file and it boots up.

I know 21.1 is still in beta, but figure I would report this issue for the Dec patch. Nov patch works.. so reverting back to that for now.

**Comment by PaulPizz** [comment]
canary build works

**Comment by wSedlacek** [comment]
Where can I find the canary builds? I've been looking all over and all I see is the stable builds in the releases.

**Comment by mauri-lab** [comment]
I have similar issue on Pixel 3 xl using december patch. I cant boot after patching magisk patched boot.img. It starts loading and i see G logo but returns to bootloader with error no valid slot to boot. After patching stock boot.img phone boots normally. I have used beta and canary builds, with same result.

**Comment by varunhardgamer** [comment]
> Where can I find the canary builds? I've been looking all over and all I see is the stable builds in the releases.

https://github.com/topjohnwu/magisk_files/tree/canary

**Comment by wSedlacek** [comment]
> > Where can I find the canary builds? I've been looking all over and all I see is the stable builds in the releases.
> 
> https://github.com/topjohnwu/magisk_files/tree/canary

Are these official builds?

**Comment by Didgeridoohan** [comment]
Yes, those are official builds. The intended way of installing the Canary builds is to install the Canary Manager and switch to the Canary update channel.

You'll always find the link to the Canary Manager in the readme for the Magisk repo: https://github.com/topjohnwu/Magisk

**Comment by wSedlacek** [comment]
Why was this closed without a statement or reference to the commit that resolved the issue?

**Comment by Didgeridoohan** [comment]
If the Canary build works (as stated), it's not actually an issue...
