### ISSUE TITLE
能否增加自定義包裝名稱的功能？

### ISSUE THREAD

**Issue by JinShichang** [topjohnwu/Magisk#3570]
我注意到有些APP已經能夠檢測隨機包裝名稱的magisk了，因此有些情況下隱藏magisk的功能並不起作用，除非將magisk manager卸載才可以避免，但是每次反復安裝卸載並不是一個好的辦法，因此能不能增加自定義包裝名稱的功能，我嘗試過自行修改包裝名稱，可以避免檢測，但是magisk manager內的功能並不能正常工作

**Comment by troublewind** [comment]
麻煩告知下哪些app會檢測隨機包名，避免踩坑，謝謝

**Comment by vvb2060** [comment]
如果在随机包名后依然被检测，我不认为自定义包名可以躲避。另外，你的设备是Android9之前吗？从Android9开始，才能比较有效地隐藏magisk manager。
