### ISSUE TITLE
bootlooped on Samsung Galaxy A21s

### ISSUE THREAD

**Issue by MegDuck** [topjohnwu/Magisk#3572]
Magisk bootlooped on this phone. 

(logs)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/5683358/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/5683359/recovery.log)

**Comment by namjeff** [comment]
+1

**Comment by LinnyR** [comment]
Version 21.1 caused bootloop in MiUI12, while version 20.4 was normal.

**Comment by namjeff** [comment]
> Version 21.1 caused bootloop in MiUI12, while version 20.4 was normal.

did you manage to root the A21s?

**Comment by MegDuck** [comment]
> > Version 21.1 caused bootloop in MiUI12, while version 20.4 was normal.
> 
> did you manage to root the A21s?

I think our device is not supported. We can try build a boot with magisk.

**Comment by namjeff** [comment]
> > > Version 21.1 caused bootloop in MiUI12, while version 20.4 was normal.
> > 
> > 
> > did you manage to root the A21s?
> 
> I think our device is not supported. We can try build a boot with magisk.

how do we do that? i'm desperate to root my device

**Comment by MegDuck** [comment]
> > > > Version 21.1 caused bootloop in MiUI12, while version 20.4 was normal.
> > > 
> > > 
> > > did you manage to root the A21s?
> > 
> > 
> > I think our device is not supported. We can try build a boot with magisk.
> 
> how do we do that? i'm desperate to root my device

Install boot.img, repack, and put to ramdisk magisk.

**Comment by namjeff** [comment]
> > > > > Version 21.1 caused bootloop in MiUI12, while version 20.4 was normal.
> > > > 
> > > > 
> > > > did you manage to root the A21s?
> > > 
> > > 
> > > I think our device is not supported. We can try build a boot with magisk.
> > 
> > 
> > how do we do that? i'm desperate to root my device
> 
> Install boot.img, repack, and put to ramdisk magisk.

Sorry for the continuous questions
Did that work for you?
Also can you give me more details im a little bit confused
Thank you

**Comment by MegDuck** [comment]
> > > > > > Version 21.1 caused bootloop in MiUI12, while version 20.4 was normal.
> > > > > 
> > > > > 
> > > > > did you manage to root the A21s?
> > > > 
> > > > 
> > > > I think our device is not supported. We can try build a boot with magisk.
> > > 
> > > 
> > > how do we do that? i'm desperate to root my device
> > 
> > 
> > Install boot.img, repack, and put to ramdisk magisk.
> 
> Sorry for the continuous questions
> Did that work for you?
> Also can you give me more details im a little bit confused
> Thank you

I'm bot do it

**Comment by topjohnwu** [comment]
I just released yet another canary build, it should fix bootloops for many devices. If you still experience bootloops, open a new issue with proper information needed for debugging. Thank you!
