### ISSUE TITLE
Boot image size mismatch after patching

### ISSUE THREAD

**Issue by RomanTheLegend** [topjohnwu/Magisk#3574]
Magisk 20400
boot.img extracted from this ROM: https://sourceforge.net/projects/crdroid/files/surya/7.x/crDroidAndroid-11.0-20201211-surya-v7.0.zip/download

size before patching ~132 MB
size after patching ~18.2 MB

Did patching few times - result is the same. No error in logs
Out of curiosity I flashed the boot with this file, and it didn't seem to break the system, but also Magisk was not detected by manager

**Comment by osm0sis** [comment]
Smaller doesn't matter, most of the boot partition is empty. Likely the patch worked but it failed to detect 2SI, use the latest Canary; we don't support issues for anything older.
