### ISSUE TITLE
Modal popups are broken after the language option change

### ISSUE THREAD

**Issue by HanabishiRecca** [topjohnwu/Magisk#3576]
I've changed the language option from `System Default` to `English` in the Manager app, after that all the modal popups became just empty. Cleaning the app data helps, but every time changing to `English` this bug happens again.
Magisk Manager version is latest 8.0.3 (314).

![Screenshot_1_Magisk_Manager](https://user-images.githubusercontent.com/13597663/102309269-3b6d7d00-3f8a-11eb-9a0c-677666f6ab4b.png)

![Screenshot_2_Magisk_Manager](https://user-images.githubusercontent.com/13597663/102309300-4d4f2000-3f8a-11eb-8bdf-906ca1ee8ca8.png)

![Screenshot_3_Magisk_Manager](https://user-images.githubusercontent.com/13597663/102309312-5213d400-3f8a-11eb-8344-e80f72c07d08.png)

**Comment by samoht0** [comment]
Yeah, can confirm this on two different devices running LOS 17.1. Broke with Manager 8.0.3, using 8.0.2 works fine.

**Comment by topjohnwu** [comment]
Please report bugs on canary builds
