### ISSUE TITLE
Dolby Module in Dynamic Partition

### ISSUE THREAD

**Issue by reiryuki** [topjohnwu/Magisk#3578]
Hi, I have Dolby Atmos/Audio modules. We need to modify /vendor/etc/vintf/manifest.xml directly to make Dolby dms hwservice working. But in dynamic partitions devices, we are not be able to modify any files directly, so, Dolby module fails to be working. Any workaround for this?

**Comment by Didgeridoohan** [comment]
Yes, the module should edit the files systemlessly... That's what Magisk is for. All relevant details are in the docs: https://topjohnwu.github.io/Magisk/guides.html

But this isn't the place for this kind of posts... Please close.

**Comment by reiryuki** [comment]
@Didgeridoohan But I hope Magisk can solve hwservice addition systemlessly without needs of modifying file directly, in future, like pre-init mount support. Due to dynamic partitions devices. Thanks.

**Comment by unixandria-xda** [comment]
> @Didgeridoohan But I hope Magisk can solve hwservice addition systemlessly without needs of modifying file directly, in future, like pre-init mount support. Due to dynamic partitions devices. Thanks.

Magisk runs mostly post init iirc to prevent some bootloops

**Comment by reiryuki** [comment]
@unixandria-xda no sir, my dolby magisk no need .rc to run.

**Comment by unixandria-xda** [comment]
> @unixandria-xda no sir, my dolby magisk no need .rc to run. It's need hidl addition at manifest.xml.

I meant it's not possible to run pre-init as magisk execs original init then does magisk stuff like mount modules. Hence why boot animation replacement can be hit and miss.

Honestly your best bet is to kill the service and restart it in a late start service script

**Comment by HackerPieDanny** [comment]
![Screenshot_20210315-013553.png](https://user-images.githubusercontent.com/50170092/111079947-3ee7b480-8537-11eb-9362-2d8c875d3c3c.png)

How can I fix it and flazh it into my pixel 4xl..
