### ISSUE TITLE
magisk 21.1 can't root sony xperia 1 II 921 firmware

### ISSUE THREAD

**Issue by inprivateme** [topjohnwu/Magisk#3580]
magisk 21.1 can't root sony xperia 1 II 921 firmware

**Comment by Nicklulucat** [comment]
Me too

**Comment by htcmagehoho** [comment]
yes..me too

**Comment by zgfg** [comment]
Canary 21102?

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.
