### ISSUE TITLE
Magisk gives bootloop with LOS 17.1 2020-12-15 on Moto G7plus

### ISSUE THREAD

**Issue by benutzer74** [topjohnwu/Magisk#3582]
**EDIT: what I have reported seem to be more a LineageOS problem than a Magisk issue.**
I had random reboots / bootlops to recovery ("Failed to load Android system").
I have now LOS 17.1 20201215 installed with Magisk 21.1 (beta channel) so far this works.
Please forgive. **You could safely delete this report**. Thanks for Magisk, great tool. (btw, would be nice to have PIN protection, not only fingerprint :-)

**Comment by giacomoferretti** [comment]
You can close this issue by yourself :wink:

**Comment by cocka11** [comment]
flash magisk 19.3 work fine for me
