### ISSUE TITLE
Snapchat

### ISSUE THREAD

**Issue by jsanchez05** [topjohnwu/Magisk#3583]
Snapchat works for a while then I am unable to record any videos. Happens on stock rooted. Only module installed is gpu drivers for 865 SoC.

Removing root makes Snapchat work again.

All Snapchat options disabled in magisk hide along with all Google play services.

**Comment by unixandria-xda** [comment]
#1152 

Snapchat is well known for issues.

Please close this issue

**Comment by jsanchez05** [comment]
So, is there a fix?
