### ISSUE TITLE
Entering URLs for Canary build jsons in Magisk Manager Custom Channel results in error

### ISSUE THREAD

**Issue by pndwal** [topjohnwu/Magisk#3584]
Flashing archived builds by Patching/updating from Magisk Manager requires valid URL in Custom Channel.

URL for raw json for archived stable/beta release builds are working as they contain full/valid "link" URLs for respective files.

However, URL for raw json for archived debug canary builds are NOT working as they DON'T contain full/valid "link" URLs for the files; the file versions appear correctly in Magisk Manager, but trying to download, update, or simply view changelog results in 'Download Error'. I believe the older (now removed) canary builds used to include working json code.

I know the Canary builds can still be used simply by editing the "link" code correctly with full/valid "link" URLs for respective files, hosting the edited json elsewhere and using full URL for edited json in Magisk Manager's Custom Channel, but this should be unnecessary.

I wonder if there is any way to fix jsons to work natively, or another way to configure Custom Channel to find filepaths that I'm missing.

**Comment by topjohnwu** [comment]
To use canary builds, you have to first manually download the APK from the README page

**Comment by pndwal** [comment]
> To use canary builds, you have to first manually download the APK from the README page

Many thanks @topjohnwu for your attention to this.

Unfortunately the advice hasn't helped respecting ARCHIVED / LEGACY Canary builds. (Many wish to try these for comparison / testing / rollback purposes, which I imagine is why an archive is maintained.)

Of course, I have Canary Manager APK, but the only way I can get Manager to correctly install (or download directly) older builds is to edit "link"s in json, host and use host location URL in Custom Channel as described.

Analysis:
Later build json code includes 'links' like:
"magisk": {
    "version": "d0896984",
    "versionCode": "21102",
    "link": "magisk-debug.zip",

This results in Download Error (despite selected version values appearing as 'Latest' on Manager home page).

Some earlier build json code includes 'links' like:
  "magisk": {
    "version": "64effe93",
    "versionCode": "21001",
"versionCode": "21001",
    "link": "https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/magisk-debug.zip",

This results in VERY latest Canary builds being downloaded / installed (despite earlier selected version values appearing as 'Latest' for selected Custom Channel on Manager home page).

There is no such problem using archived Stable / Beta builds I've tried; json code here appears to contain complete / working link URLs, unique to version.

**Comment by pndwal** [comment]
Many thanks also, @topjohnwu, for today's Canary build, and the hours of work involved!

I notice (happily) that this update includes many commits authored by @vvb2060.

I was actually interested in testing some issues apparently fixed in his recent Alpha builds, but these will now likely be resolved in official Canary also.

I would still be happy to hear of any resolution for problem Canary json links for future comparison of older canary builds (although I appreciate you will not likely be interested in debug function in these).

Kind regards, PW
