### ISSUE TITLE
[Feature] File or Content type URL protocol support for Custom update channel

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#3588]
Please add **file://** protocol support
- for URL to the json file in the Custom update channel
- for the "link" value in json file pointing to the magisk zip

E.g., that we could set Custom update channel to:
file:///sdcard/Download/debug.json

and that we can define inside the debug.json (unnecessary tags removed):
magisk": {
    "link": "file:///sdcard/Download/magisk-debug.zip"
}

Or with: 
file:///storage/emulated/0/Download/...

Or, alternatively, support for the **content://** type URLs (like DNS66 and AdAway similarly do)

**Comment by topjohnwu** [comment]
Sorry, but this isn't as easy as you think. You cannot directly access file URIs on modern Android.
An easy way is to setup a simple web server and set is as a custom channel (which is what I'm doing for development)

**Comment by zgfg** [comment]
Sorry but setting up a personal Web server is not that easy.
Actually, I have Github accont, hence I upload to Github both the json and zip and use Github for that Web server - but many users do not have

I know that Google makes it complicated (for the file protocol) - but Google pushes the methods for content protocol.
User could put the json and/or zip to Download folder, and Magisk Manager can use the built-in File Manager for user to navigate to the file

The same works for AdAway (it works on my A11), instead of https URI to the public hosts file, I can use the content URI pointing my local hosts file on the phone:
![IMG_20201229_075822](https://user-images.githubusercontent.com/51943147/103264832-2f32e800-49ac-11eb-8a49-c706d79b581d.jpg)
![IMG_20201229_080015](https://user-images.githubusercontent.com/51943147/103264847-3c4fd700-49ac-11eb-90f9-4c475c66f108.jpg)
![IMG_20201229_080102](https://user-images.githubusercontent.com/51943147/103264858-496cc600-49ac-11eb-842d-0673a459b90e.jpg)
