### ISSUE TITLE
Magisk installation disappears randomly

### ISSUE THREAD

**Issue by terrorist96** [topjohnwu/Magisk#359]
Not sure if this is an issue with Magisk or the Magisk Manager, but ever since version 14, I'll eventually get a notification telling me there's an update (to version 14), which is weird because I already have that installed. I open Magisk Manager and it says Magisk isn't installed. I reboot my phone, and it shows installed again (without reinstalling). Then eventually (after a few days) it'll happen again and I'll have to restart my phone again to fix it.

**Comment by terrorist96** [comment]
@topjohnwu closed with explanation?

**Comment by SuperSandro2000** [comment]
Issue not Q&A, go to XDA for that. 2nd old issue for 14, current is 16.6 iirc. 3rd no logs, didn't happen.

**Comment by terrorist96** [comment]
Lol. K.
