### ISSUE TITLE
Please help I just mistakely hide my magisk

### ISSUE THREAD

**Issue by Saikatsaha1996** [topjohnwu/Magisk#3590]
Please help how can I unhide my magisk manager application in my mobile

**Comment by giacomoferretti** [comment]
Uninstall and reinstall the Manager APK.

BTW, why do you need to unhide the Manager?

**Comment by zgfg** [comment]
If you used Hide Magisk Manager from the MM Settings, then open your renamed MM app (whatever the new name you gave it), go to its Settings and find the Unhide (Restore) Magisk Manager option
