### ISSUE TITLE
[Feature request] GPG signature + SHA256 for verifying download

### ISSUE THREAD

**Issue by ovz93br43v7** [topjohnwu/Magisk#3594]
Can you provide a gpg signature (plus fingerprint) and a SHA256 for verifying downloaded files?

**Comment by ovz93br43v7** [comment]
@topjohnwu Does this mean this is already available? I couldn't find it in your help / wiki...

**Comment by maltfield** [comment]
@topjohnwu why was this closed?? There's clearly no pgp signature available in the releases.

For example, the latest release (at the time of writing) is v23.0:

 * https://github.com/topjohnwu/Magisk/releases/tag/v23.0

There is currently no way for a user to safely download this file and cryptographically verify that it originated from you without modification in-transit. This is why we need a cryptographically signed digest file as @ovz93br43v7 requested.

For an example of how this should look, see:

 https://github.com/BusKill/buskill-app/releases/tag/v0.4.0

Note the presence of the `SHA256SUMS` file and its detached signature file `SHA256SUMS.asc`. This is incidental to how Debian signs their releases.

For more information on best-practices of release signing, please see

**Comment by ovz93br43v7** [comment]
@maltfield @topjohnwu 
According to my memory there was in the past a section "verifying downloads" in the installation instructions of Magisk, but this section is gone. :-1: 
I tried to find it in the wayback machine but had no success. :-/
