### ISSUE TITLE
Magisk 21.1 addon.d fails on LOS 17.1

### ISSUE THREAD

**Issue by pwn0r** [topjohnwu/Magisk#3595]
Hi,  recently this issue has been a bit annoying. There is not really much documentation on addon.d (apparently?) so I cannot really research myself much here. 

I have Magisk 21.1 installed on oneplus3 (which is not A/B obviously). I run LOS17.1 and update it quite often. It does appear to work from OTA updater, but here we are talking about dirty flash from TWRP 3.4.0

The sequence as follows, just repeated to double-check this today:

1. LOS17.1 2020-12-14 installed with Magisk 21.1

2. Reboot to TWRP, reflash Magisk for confirmation, says addon.d installed. Restart to system. Doublecheck -- that 99-whatever script is in the addond folder.  Magisk is installed (actually more reinstalled in this case as it was before. This step only to double-check that magisk is installed properly)

3. Reboot to TWRP, flash LOS 17.1 2020-12-21 from TWRP. Addon.d fails. If I reboot to system straight away then magisk manager is still there but magisk is not installed. 

It would be not much of a problem just to reflash magisk but in my case it apparently breaks configuration for one module and it is very annoying, requires time to redo it.  

And before you mention issue #2686 -- nope, not this case. The data is fully decrypted on this device.

**Comment by meiser79** [comment]
For me, it was https://github.com/topjohnwu/Magisk/pull/3494 which made it work again.

**Comment by topjohnwu** [comment]
If that PR fixes the issue, then it is already fixed in the latest build

**Comment by pwn0r** [comment]
thanks, it seems 21.2 has indeed fixed the issue on oneplus3
