### ISSUE TITLE
[Pixel 4a 5G] Magisk-Manager-v8.0.3 - "! Unable to repack boot image!"

### ISSUE THREAD

**Issue by andyvuj24** [topjohnwu/Magisk#3599]
**Using boot.img from bramble-rq1d.201205.012.a1-factory-469e0b57 downloaded from [here](https://dl.google.com/dl/android/aosp/bramble-rq1d.201205.012.a1-factory-469e0b57.zip)** 

```
- Device platform: arm64-v8a
- Copying image to cache
2034+0 records in
2034+0 records out
2082816 bytes (1.9 M) copied, 0.004860 s, 409 M/s
1410+1 records in
1410+1 records out
1443916 bytes (1.3 M) copied, 0.003606 s, 382 M/s
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [11574685]
RAMDISK_SZ      [369099084]
SECOND_SZ       [0]
EXTRA_SZ        [3]
PAGESIZE        [0]
NAME            []
CMDLINE         []
CHECKSUM        [0000000000000000000000000000000000000000000000000000000000000000]
Floating point exception
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
Add entry [init] (0750)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [11574685]
RAMDISK_SZ      [369099084]
SECOND_SZ       [0]
EXTRA_SZ        [3]
PAGESIZE        [0]
NAME            []
CMDLINE         []
CHECKSUM        [0000000000000000000000000000000000000000000000000000000000000000]
Floating point exception
! Installation failed
- Repacking boot image
! Unable to repack boot image!
```

**Comment by zgfg** [comment]
Is this Stable or Beta - Stable does not apply to A11

Have you tried with the latest Canary (Manager 316, Magisk 21102) - Canary is ahead of Beta

**Comment by andyvuj24** [comment]
SOLVED: Tried again with using the [Canary Build](https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/app-debug.apk) and it worked sucessfully!

> - Device platform: arm64-v8a
> - Magisk Manager: d0896984 (316)
> - Install target: d0896984 (21102)
> - Copying image to cache
> 2026+0 records in
> 2026+0 records out
> 2074624 bytes (1.9 M) copied, 0.003456 s, 572 M/s
> 1381+1 records in
> 1381+1 records out
> 1415016 bytes (1.3 M) copied, 0.002669 s, 506 M/s
> - Unpacking boot image
> Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
> HEADER_VER      [3]
> KERNEL_SZ       [11574685]
> RAMDISK_SZ      [14131679]
> OS_VERSION      [11.0.0]
> OS_PATCH_LEVEL  [2020-12]
> PAGESIZE        [4096]
> CMDLINE         []
> KERNEL_FMT      [lz4]
> RAMDISK_FMT     [lz4_legacy]
> - Checking ramdisk status
> Loading cpio: [ramdisk.cpio]
> - Stock boot image detected
> - Patching ramdisk
> Loading cpio: [ramdisk.cpio]
> Add entry [init] (0750)
> Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
> Loading cpio: [ramdisk.cpio.orig]
> Backup mismatch entry: [init] -> [.backup/init]
> Create directory [.backup] (0000)
> Add entry [.backup/.magisk] (0000)
> Dump cpio: [ramdisk.cpio]
> Patch @ 0146FFC6 [736B69705F696E697472616D667300]->[77616E745F696E697472616D667300]
> Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
> HEADER_VER      [3]
> KERNEL_SZ       [11574685]
> RAMDISK_SZ      [14131679]
> OS_VERSION      [11.0.0]
> OS_PATCH_LEVEL  [2020-12]
> - Repacking boot image
> PAGESIZE        [4096]
> CMDLINE         []
> KERNEL_FMT      [lz4]
> RAMDISK_FMT     [lz4_legacy]
> Repack to boot image: [new-boot.img]
> HEADER_VER      [3]
> KERNEL_SZ       [11440400]
> RAMDISK_SZ      [14452382]
> OS_VERSION      [11.0.0]
> OS_PATCH_LEVEL  [2020-12]
> PAGESIZE        [4096]
> CMDLINE         []
> 
> ****************************
>  Output file is written to 
>  /storage/emulated/0/Download/magisk_patched_hVfBt.img 
> ****************************
> - All done!
