### ISSUE TITLE
Bootloop pixel experience android 11 begonia

### ISSUE THREAD

**Issue by Dipanshu6** [topjohnwu/Magisk#3601]
I had magisk on But I clean flashed android 11 resulting in deletion of all of my data I tried installing magisk downloaded magisk from GitHub didn't change any settings clicked install it downloaded zip flashed it via twrp and the device won't boot flashed again still nothing. Lastly clean flashed rom again.

**Comment by zgfg** [comment]
For A11, are you using Canary, as required?
