### ISSUE TITLE
Fail to boot on Android 11 for Nokia 8.1

### ISSUE THREAD

**Issue by JohnChu101** [topjohnwu/Magisk#3608]
I tried to root my Nokia 8.1 (Android 11) with both Magisk v20.4 and v21.1. The installation method is patch boot image and flash into boot by fastboot. On 20.4 it caused a bootloop, and on 21.1 it brings me to a "Can't load Android System. Your data may be corrupt." screen.
I tried several times with original Magisk Manager and the canary version, the results are the same. Log file and boot image are attached.
[magisk_install_log_2020-12-26T22_34_15Z.log](https://github.com/topjohnwu/Magisk/files/5743229/magisk_install_log_2020-12-26T22_34_15Z.log)
[dtbo.zip](https://github.com/topjohnwu/Magisk/files/5743228/dtbo.zip)
[PNX-6100-boot.zip](https://github.com/topjohnwu/Magisk/files/5743230/PNX-6100-boot.zip)
[vbmeta.zip](https://github.com/topjohnwu/Magisk/files/5743231/vbmeta.zip)

**Comment by zgfg** [comment]
Instead of 21100, try with the latest 21102 Canary

**Comment by JohnChu101** [comment]
> Instead of 21100 Beta, did you try with the latest 21102 Canary

I tried to patch with Magisk Manager canary, latest beta version of magisk. I'm not sure about the version though, but I believe it is the 21102 version, no?

**Comment by JohnChu101** [comment]
> Instead of 21100 Beta, did you try with the latest 21102 Canary

I tried now. It's the same.

**Comment by JohnChu101** [comment]
Problem solved after i did a factory reset. Seems to be some conflict with the existing magisk modules.

**Comment by FattyMattier** [comment]
> Problem solved after i did a factory reset. Seems to be some conflict with the existing magisk modules.

Hi John, can you help to share how you root your Nokia 8.1 with Magisk?  I am with the android 11 from OTA, and extract Boot.img file from OTA already, I tried to root the phone but could not finish it, a circle appeared saying wiping the phone.  After my phone restarted, the phone was reset to android 11 and cleaned all the data and user settings.
