### ISSUE TITLE
Magisk is still in there even after stock firmware flash on SM-G970F

### ISSUE THREAD

**Issue by xdagee** [topjohnwu/Magisk#3611]
Hello, So I figured that Magisk is still in there even after flashing stock firmware (with re-partitioning and NAND Erase checked). This prevents me from booting directly into OS. Is there any help on how I can completely uninstall Magisk on SM-G970F?

**Comment by zgfg** [comment]
Magisk installs to Boot or Recovery (you should know for your phone which of the two).
Flash your stock Boot or Recovery

Use Uninstall Magisk from Magisk Manager (probably it won't work now correctly if you already wiped Data - you had to use it first)

**Comment by xdagee** [comment]
> Magisk installs to Boot or Recovery (you should know for your phone which of the two).
> Flash your stock Boot or Recovery
> 
> Use Uninstall Magisk from Magisk Manager (probably it won't work now correctly if you already wiped Data - you had to use it first)

Magisk installs in recovery (for my device SM-G970F). And if I use the Magisk Manager or the magisk uninstaller zip. It ends up not booting.
