### ISSUE TITLE
Magisk Installer (zip) installs broken Magisk Manager if a hidden one already exists

### ISSUE THREAD

**Issue by foxscore** [topjohnwu/Magisk#3616]
_Old : original/hidden
New : default/installed by script_

**Problem / How to replicate**
If you hide the magisk manager application and _(re-)_ install magisk, the installation script decides to also install the default version of magisk manager.

This will causes the following issues:
- The old Magisk Manager app will crash when you try to open it, but root-request-dialogs still work/show up
- The new Magisk Manager app will be denied root permissions (and thus be useless)

The problems will go away when you remove the new Magisk Manager.

**Solutions**
- Don't install Magisk Manager with the installer script
- Display a warning in the Magisk Manager app if it's missing root access, and offer the user to uninstall the app in such case.

**Comment by topjohnwu** [comment]
This is already address in the latest canary version
