### ISSUE TITLE
在不解包boot删除avb相关时，使用canary（21201）修补时，仍无法进入系统

### ISSUE THREAD

**Issue by leihen** [topjohnwu/Magisk#3624]
作者您好，看到您回复后，今天我卸载magisk（模块装有riru，riruedx，magiskhideprops忘记删除），重新刷回原boot后，使用21201修补后boot大小无变化，刷入后仍是一直重启到fastboot，我不知道如何获取内核日志。

目前解决root都是解包boot后，在oplus.fstab里面删除avb相关内容，打包再修补（21100）刷入，就可以获取root了，但是开启magiskhide，重启手机后，指纹功能无效，包括指纹解锁，指纹登录等操作，关闭重启即可恢复，如有需要，请告知如何获取对您有帮助的文件或日志
[boot.zip](https://github.com/topjohnwu/Magisk/files/5754036/boot.zip)

**Comment by vvb2060** [comment]
根据我们的测试，删除oplus.fstab中avb参数后，系统出现大量问题，部分系统应用丢失。疑似不再挂载相关分区。
所以，你说的解决方案不可行。

关闭，合并issue到 #3663

**Comment by leihen** [comment]
> 根据我们的测试，删除oplus.fstab中avb参数后，系统出现大量问题，部分系统应用丢失。疑似不再挂载相关分区。
> 所以，你说的解决方案不可行。
> 
> 关闭，合并issue到 #3663

在某社区看到一些机型（oppo/realme）确实是会丢失系统应用，影响使用，但该方式在realmex50pro系列没有问题
测试辛苦了，感谢付出
