### ISSUE TITLE
Potential Method for Passing Safety Net and Root Checks

### ISSUE THREAD

**Issue by bliu886** [topjohnwu/Magisk#3626]
On a Pixel 3a XL, I was able to pass Safety Net and pass all root checks by creating a new user account and installing apps on that account. I am using the Island app (https://play.google.com/store/apps/details?id=com.oasisfeng.island) to manage app installs. I used the "Manual setup for Island" steps in the setup guide (https://island.oasisfeng.com/setup.html#manual-setup-for-island-in-god-mode--demigod-mode) in order to create the new user account which also setup the Island app to be able to install/uninstall apps for the new user account.

Installing apps under the new user account was able to prevent those apps from detecting any sort of root and to pass Safety Net. This works because the new user account doesn't have read/write permission for the files that Safety Net uses to detect system modification and installed apps have the same permission.

Perhaps Magisk could do something similar where the apps that users mark to hide root from, will be installed on a different user account with the limited privileges.

**Comment by Didgeridoohan** [comment]
I think you've misunderstood how SafetyNet works.

Using isolation apps might work for specific apps root checking methods (of they look for other apps or files/folders on your device), but it won't work for SafetyNet detecting an unlocked bootloader through hardware backed key attestation (Magisk can already hide from all other parts of a SafetyNet check).

**Comment by vvb2060** [comment]
SafetyNet fully supports multiple users.
