### ISSUE TITLE
Samsung S9 boot loop. Wrong instruction. Need help.

### ISSUE THREAD

**Issue by iMaximal** [topjohnwu/Magisk#3634]
Hello,

Device: rooted Samsung S9

I followed the instruction:
https://magiskmanager.com/

My steps:
1. Download and install Magisk Manager
2. Download and install Magisk from Magisk using recommended option in app
3. Reboot
As a result boot loop.

I tried to boot to TWRP, using volume up + bixby + power keys.
There is no TWRP.

It's really problem for me. Please help to restore device.

**Comment by Didgeridoohan** [comment]
I wouldn't trust anything from that site. It's not used or endorsed by @topjohnwu. The only place for proper instructions and downloads are right here in the Magisk Github repo.

Just reinstall TWRP if you want to use that, or restore your device using Odin and then start again but use the official instructions instead.

And the Github issues are for reporting bugs, not support. Please close this...

**Comment by iMaximal** [comment]
OMG. I dissapointed.
Thank you for response.

I used Odin to reinstall original firmware, but networks are not working. Look like /efs folder is corrupted. :-( 
If it possible it will be great to check OS before installation that it is ready for performing.
Thank you.
