### ISSUE TITLE
LG G5 (H850) bootloop [H85030f]

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#3635]
So, this is an as clean as it gets installation (by formatting all partitions (including system, boot etc) on bootloader and using LGUP right after) and after magisk installation it simply won't boot when latest canary (as of today) is installed.

- The last successful working magisk was the release 20400.
- The firmware installed is the latest available: H85030f_00_OPEN_EU_OP_1122
- Encrypted or not encrypted storage makes no difference.

Bootloop video (nothing special):
https://user-images.githubusercontent.com/3320229/103456234-e3aa7200-4cfc-11eb-8c94-866bc4a8b776.mp4

Magisk installation logs & recovery logs:
[dmesg.log](https://github.com/topjohnwu/Magisk/files/5760166/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/5760167/recovery.log)

Original boot IMG:
[boot_6.zip](https://github.com/topjohnwu/Magisk/files/5760151/boot_6.zip)

Patched (by magisk) boot IMG:
[boot.emmc.zip](https://github.com/topjohnwu/Magisk/files/5760153/boot.emmc.zip)

cat /proc/mounts output without root:
[mounts(NOROOT).txt](https://github.com/topjohnwu/Magisk/files/5760156/mounts.NOROOT.txt)

Now, I'm more than happy to provide any boot related logs, however, I am unable to find any of those. 
Check the video too, the loop is so fast (it doesn't even try) and it simply won't generate a thing.

**Comment by etmatrix** [comment]
I confirm this issue. I don't understand because 21.1 now is a stable release. Today I tested and I got bootlop.
For me 21.2 is still beta. I rollback to 20.4.

**Comment by japanesephundroid** [comment]
Same here on an LG V20 (US996) that shares many parts with the LG G5 and has similar software.
This happens with Android 8.0 Stock software.
21.0 beta works fine (I currently use it).
21.1 beta and 21.2 stable immediately bootloop.

See also:
https://www.reddit.com/r/lgv20/comments/kvcni5/magisk_212_stable/
Lineage versions of this phone seem to work fine.

**Comment by topjohnwu** [comment]
I just released a new canary build, may you please try it out and report back?

**Comment by japanesephundroid** [comment]
> I just released a new canary build, may you please try it out and report back?

I tried the latest Canary build, it bootlooped as well.
Give me a while and I will upload the logs.

**Comment by japanesephundroid** [comment]
> > I just released a new canary build, may you please try it out and report back?
> 
> I tried the latest Canary build, it bootlooped as well.
> Give me a while and I will upload the logs.

[dmesg.log](https://github.com/topjohnwu/Magisk/files/5816008/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/5816009/recovery.log)

As @DenyDarko above I couldn't get a logcat.

**Comment by DenyDarko** [comment]
Hey @topjohnwu ,

Unfortunately, absolutely no change. Same bootloop

**Comment by topjohnwu** [comment]
I just released yet another canary build, it should fix bootloops for many devices. If you still experience bootloops, open a new issue with **proper information** needed for debugging. Thank you!

**Comment by DenyDarko** [comment]
@topjohnwu I'm still experiencing the same bootloop right after updating to this new Canary and rebooting. 
Same case, it doesn't even try to boot. Like boot is missing.

I'm aware you probably need last_kmsg.
Thing is that lg kernel doesn't generate it.

If anyone, you, @Didgeridoohan, @osm0sis , someone, has any idea on how to get such debugging longs from a kernel with those flags off, I'm more than happy to get them 🤷

**Comment by DenyDarko** [comment]
@japanesephundroid what about your device?

Did the last Canary solved it?

**Comment by japanesephundroid** [comment]
> @japanesephundroid what about your device?
> 
> Did the last Canary solved it?

@DenyDarko I did no try it after you said it bootlooped your phone.

It takes me a while to get the phone up and running after.

I may do it if I find a way to get a logcat during.

**Comment by DenyDarko** [comment]
@japanesephundroid you can't, don't bother with this.

We need a kernel with debug options enabled. Something I can't do and probably neither you.

If any of the contributors mentioned above is interested in debugging this, they can certainly help with the log part.

**Comment by japanesephundroid** [comment]
Just as an update to all that commented in this since the issue is now closed.

This seems to be the issue we are having:
https://github.com/topjohnwu/Magisk/issues/3751

**Comment by japanesephundroid** [comment]
Another update from the https://github.com/topjohnwu/Magisk/issues/3722 issue

> I made some investigation and checked that replacing the file in the Magisk-v21.4.zip/arm/magiskboot with the magiskboot from v21.0 and flashing that one fixes the problem.

I can confirm that doing this enabled me installing Magisk 21.4 without the bootloop.
So if somebody wants to try 21.4 until the issue is fixed can try that.
