### ISSUE TITLE
Can't root Galaxy Xcover Pro

### ISSUE THREAD

**Issue by liorshwa** [topjohnwu/Magisk#3637]
Tried to root the samsung Galaxy Xcover Pro (SM - G715FN), but failed, wanted to figure out why.

i attached a screenshot of the main magisk screen...
according to readme the process for rooting my device is :

patching AP and flashing Patched_AP alongside BL, CP, CSC but i'm stuck in a bootloop after flash (even after factory wipe when prompted)

i think i know why the bootloop but wanted to confirm (my knowledge in the subject is almost nonexistent):

this device has 2 vbmeta partitions (i have no clue abou the role of each one of them)
one is named vbmeta.img, second one is vbmeta_samsung.img

after patching AP with magisk - only vbmeta is changed, vbmeta_samsung is untouched

i think it is trying to verify something but fails

also wanted to ask where i can find the script that patches the vbmeta file , to try and patch vbmeta_samsung by myself

i uploaded both vbmeta images if that'd help :

[vbmetas.zip](https://github.com/topjohnwu/Magisk/files/5760868/vbmetas.zip)

![Screenshot_20210102-231423](https://user-images.githubusercontent.com/57096892/103466781-a66fcf80-4d50-11eb-8041-3d7bbc41a480.jpg)

also there is vbmeta.img in BL which i think overwrites the patched AP one during flash process

**Comment by zgfg** [comment]
Instead of Stable and half a year old Magisk 20.4, try with Beta or Canary 21.2 (specially, Android 11 is not supported by 20.4)

**Comment by liorshwa** [comment]
> Instead of with Stable and half a year old Magisk 20.4, try with Beta or Canary 21.2 (specially, Android 11 is not supported by 20.4)

OK, will try and report back

**Comment by liorshwa** [comment]
same result with beta 21.1 build (bootloop - see the Galaxy splash screen and restart)
this phone is very similar to a51 in terms of it's ROM and system properties (2 vbmeta images, ramdisk, SAR)
so i tried to follow step by step videos of root guides for this phone but no luck there

**Comment by zgfg** [comment]
Sorry, I can't help you further, not familiar with Sammies - maybe ask also on XDA Magisk thread ( if didn't already)

**Comment by liorshwa** [comment]
ok, thanks anyways

**Comment by liorshwa** [comment]
still looking for help

**Comment by iynere** [comment]
@LSGio hey there, did you ever figure this out?

**Comment by Xcl4m4t10n** [comment]
I bought this phone 2 days ago and was wondering if there is any advance on this. I tried to do the steps with Magisk, this is it:

-Install Magisk.

-Patch AP.

-Copy it to PC.

-ReFlash with ODIN.

But when I do that, I got errors during installation on Download mode and the phone bricks. So I don't know if I am doing something wrong or happens that this device can't be rooted.

I have been searching but can't find any reliable information about, could you please give me some information or help?

Thank you!

**Comment by d5sword** [comment]
Finally, I have successfully rooted Samsung Galaxy Xcover Pro (SM-G715FN/DS, Europe Version, Android 11, Firmware version: G715FNXXS9CUF2). :)

I also had the same problem as you before (vbmeta HASH_MISMATCH error), but I found a workaround that I described here:
https://forum.xda-developers.com/t/is-possible-to-root-xcover-pro.4290087/post-85317391
