### ISSUE TITLE
Google Pixel5 cannot use

### ISSUE THREAD

**Issue by kongzue** [topjohnwu/Magisk#3640]
I use Pixel5 and the latest version of Magisk (Canary) 8.0.4 (1770) to patch my Pixel5 boot.img file, but I can't boot up after fastboot brushing, it shows that after rebooting several times automatically into fastboot, use original system image is working, I need your help.

The system image is 11.0.0 (RQ1A.201205.011, Dec 2020, All carriers except AT&T and Verizon)

**Comment by AncientVale** [comment]
Am also experiencing this issue on 11.0.0 (RQ1D.210105.003, Jan 2021, Verizon)

**Comment by paradox8599** [comment]
I use Pixel 5 too but experienced a different issue.
with the Jan update (RQ1A.210105.003) and Magisk 21201.

After I installed some modules and reboot, most of my apps won't start(including Magisk Manager), if stock at apps' starting screen too long, the system automatically restarts and stuck at loading screen when booting (Big G with a loading bar below). 

I have tried with different modules, disabled Magisk Hide, the problem remains.

Even removing all the modules at system start with adb `adb wait-for-device shell magisk --remove-modules` does not help.

**Comment by itismo** [comment]
Is anyone actually with a Pixel 5 and January 2020 patch with working Magisk?

**Comment by kongzue** [comment]
These are my Pixel 5 device information.
![copy_temp](https://user-images.githubusercontent.com/10115359/103980400-cb35ce00-51ba-11eb-9d6a-fd14b17c8720.jpg)
![copy_temp2](https://user-images.githubusercontent.com/10115359/103980411-ccff9180-51ba-11eb-90cf-3774286dbce7.jpg)

**Comment by itismo** [comment]
> These are my Pixel 5 device information.
> ![copy_temp](https://user-images.githubusercontent.com/10115359/103980400-cb35ce00-51ba-11eb-9d6a-fd14b17c8720.jpg)
> ![copy_temp2](https://user-images.githubusercontent.com/10115359/103980411-ccff9180-51ba-11eb-90cf-3774286dbce7.jpg)
> 

Did update normally through OTA then flash patched boot?

**Comment by kongzue** [comment]
> Did update normally through OTA then flash patched boot?

Yes. patch the boot.img file that fails to boot after it is flashed into the system.
