### ISSUE TITLE
Bootloop on Asus ROG 3 with Magisk v21.1 and v21.2 on Android 10 Default ROM

### ISSUE THREAD

**Issue by dhrumil292** [topjohnwu/Magisk#3641]
I am having Boot loop with Asus ROG 3 with Magisk versions 21.1 and 21.2

Version 21.0 is working Absolutely fine.

**Comment by qnorsten** [comment]
Perhaps you should try and provide some logs and additional other info? I doubt anyone can figure out the problem from this issue.

**Comment by dhrumil292** [comment]
Please guide me... how to send log

I am Using logcAt extreme application but don't know how to send log

Also suggest another method to send logs

Have a nice day
