### ISSUE TITLE
Magisk Manager is unable to show apps in list like yono or Google Pay to hide in MagiskHide

### ISSUE THREAD

**Issue by dhrumil292** [topjohnwu/Magisk#3642]
In MagiskHide Section of Magisk Manager, sometimes Manager is not able to show apps to hide

Like.. 

Yono SBI
Axis Bank
Bhim UPI
ETC..

**Comment by variainfantry155** [comment]
Etc

**Comment by variainfantry155** [comment]
```
Etc

```

**Comment by variainfantry155** [comment]
- [x]

**Comment by zgfg** [comment]
Use magiskhide command from Terminal app to manually add a package/activity to the Magisk hide list.
Consult Magisk Github docs

**Comment by zgfg** [comment]
See much older ticket:
https://github.com/topjohnwu/Magisk/issues/3336

**Comment by METALG0D** [comment]
> In MagiskHide Section of Magisk Manager, sometimes Manager is not able to show apps to hide
> 
> Like..
> 
> Yono SBI Axis Bank Bhim UPI ETC..



> In MagiskHide Section of Magisk Manager, sometimes Manager is not able to show apps to hide
> 
> Like..
> 
> Yono SBI Axis Bank Bhim UPI ETC..

any solution?
