### ISSUE TITLE
chattr/lsattr on mirrored files

### ISSUE THREAD

**Issue by kiber-io** [topjohnwu/Magisk#3643]
Hi!
Since magisk does not support replacing files in /apex by default, I had to use pull request #3017. Files started to be replaced, but the question arose in particular replacing files with magisk - attributes of the original file are not taken into account. For example, the original files in /apex have the "Extents" attribute:
```
willow:/apex/com.android.art/javalib # lsattr core-oj.jar
--------------e----- core-oj.jar
```
And now look at the file that magisk put:
```
willow:/apex/com.android.art/javalib # lsattr core-oj.jar
-------------------- core-oj.jar
```
Trying to set the attribute manually does not lead to anything.
```
willow:/apex/com.android.art/javalib # chattr +e core-oj.jar
chattr: core-oj.jar: setting flags to =e failed: Operation not supported on transport endpoint
```
Actually a question, whether it is possible to fix it?

**Comment by topjohnwu** [comment]
The `+e` flag is not user-settable, please refer to Linux manpages
