### ISSUE TITLE
Magisk Manager Prompt Timing Out Super Quickly, Even After Changing Settings

### ISSUE THREAD

**Issue by dragonBall561** [topjohnwu/Magisk#3644]
Hence the title, I have tried changing the settings to make the prompt slower on my phone but it keeps timing out in ~3-5secs. 

Magisk: 21.2
Magisk Manager: 8.0.4
I have EdXposed Manager, that might be messing with it.

**Comment by nogaff** [comment]
Same here on a Pixel 2 with stock Android 11 and no modules installed.

After a fresh install of Magisk the root prompt was defaulting to 10 seconds as expected, but after changing the request timeout in Magisk Manager, the prompt now only displays for 4 seconds, and the timeout value in the Magisk Manager settings appears blank.

Attempting to change the timeout setting again makes no difference.

Clearing data for Magisk Manager reverts the timeout to the default 10 seconds, but the issue returns if I attempt to change the timeout to another value again.

**Comment by Vaqtincha** [comment]
Maybe this commit is to blame https://github.com/topjohnwu/Magisk/commit/ec1af9dc1ea8bb503103765ec46e2c0b6da79c62

**Comment by dragonBall561** [comment]
I think maybe one of those arrays were actually useful :)

**Comment by maidmeow4** [comment]
Same here, on a fresh install of manager v8.0.4, root prompt timeout just 2 seconds, then got declined immediately.
Removed v8.0.4 and install v8.0.3 then upgrade to v8.0.4 solved my problem.

**Comment by HanabishiRecca** [comment]
Because the timeout setting seems to just doesn't work. Every time after the app restart it resets to empty.

![image](https://user-images.githubusercontent.com/13597663/104042059-c6453e80-51fb-11eb-961d-ab236051f7d8.png)

**Comment by vvb2060** [comment]
https://github.com/vvb2060/Magisk/commit/a4acd9939f3b69ca7875d524d97ba269b8e648dc
Waiting for merge

**Comment by dragonBall561** [comment]
yes but you haven't added it as a pr. I dont see it there.

**Comment by maxweisspoker** [comment]
For anybody else having this problem, as far as I can tell, the code change results in the appliaction using whatever timeout you select divided by ten. So my solution has been to select 60 seconds, which gives a prompt lasting for 6 seconds. And of course, if you miss the prompt, you can go into the settings and manually enable the app's root access.

Glad to see this is known and there is a PR waiting.

**Comment by tsynik** [comment]
> [vvb2060@a4acd99](https://github.com/vvb2060/Magisk/commit/a4acd9939f3b69ca7875d524d97ba269b8e648dc)
> Waiting for merge

Don't you need make PR for this?
