### ISSUE TITLE
Help me when i am patching my boot.img through magisk manager it is saying unable to unpack /unknown image format please help me. I am providing you my boot.img please help me.

### ISSUE THREAD

**Issue by vishal12345678901234567890** [topjohnwu/Magisk#3647]
Help me when i am patching my boot.img through magisk manager it is saying unable to unpack /unknown image format please help me. I am providing you my boot.img please help me.
I am providing in zip format because the website is not allowing me to send .img . So just extract it and see what is the problem.please help me . I am using oppo f15 (cph2001) and the boot image which iam sending is from the latest firmware of oppo f15 ( CPH2001PUEX_11_OTA_1470_all_GlioAPybO0Vk) software version - CPH2001EX_11_C.47
[boot.zip](https://github.com/topjohnwu/Magisk/files/5773181/boot.zip)
It is showing like this:
[magisk_install_log_2021-01-06T05:26:57Z.log](https://github.com/topjohnwu/Magisk/files/5773188/magisk_install_log_2021-01-06T05.26.57Z.log)

**Comment by zgfg** [comment]
Have you looked around (also to Magisk Github Changelogs) to find that Stable 20.4 is from the beginning of 2020

Try with Beta or Canaryn21.2

**Comment by vishal12345678901234567890** [comment]
Can you try to patch my boot.img because i am doing it but it is showing unsupported / unknown image format

**Comment by vishal12345678901234567890** [comment]
Please help me zgfg

**Comment by zgfg** [comment]
I'm telling you to not use old Stable 20.4 but Beta or Canary 21.2

Change Update channel in Magisk Manager to Beta, then update Magisk Manager (it will show you that there is new version), then try to pattch again - it will show you that latest Magisk is 21.2, not 20.4

Or, go here to Msgisk Github, fund Canary Magisk Manager, download and install.
Make sure in its Settings that Update channel is Canary, then try to patch your boot image

But also, read Magisj documentation, maybe your phone requires to patch Recovery image, not Boit

**Comment by Didgeridoohan** [comment]
You already have an answer to what's wrong:
https://github.com/topjohnwu/Magisk/issues/755#issuecomment-754690933

And before you ask: no, I cannot help you decrypt it.

**Comment by vishal12345678901234567890** [comment]
Can't you decrypt it genius Didgeridoohan

**Comment by vishal12345678901234567890** [comment]
Help me anyone

**Comment by zgfg** [comment]
You should look to your device Forum how the other users for the same phone/manufacturer decrypt the boot img.
Unpacking OTA firmwares and extracting images are device soecific and users with other phones cannot help you for your Oppo

You could also try different approach:
- if for your phone you indeed have to patch boot img (not recovery)
- and if there is fully compatible TWRP (or another custom Recuvery) for your phone

Then, you can backup Boot from TWRP, and you shall try patching the backed-up boot.emmc.win (as the boot img for your phone).
Again, I would recommend using Beta or Canary Magisk, not the old Stable 20.4 - e.g. if you have Android 11 or MTK chipset, then it will be only supported by Beta/Canary 21.2, not by the old Stable 20.4 (read the Magisk Changelogs and go through the other tickets solved with 21.2)

Generally, consult the forums for your phone, you're probably not alone, so how the other users decrypt img, install Magisk, etc

**Comment by vishal12345678901234567890** [comment]
Please anyone give me a fine answer . Please
