### ISSUE TITLE
adbd root and magisk hide conflict

### ISSUE THREAD

**Issue by CCint3** [topjohnwu/Magisk#3648]
Device: pixel
Rom: 10.0.0 (QP1A.191005.007.A3, Dec 2019)

I used a hexadecimal editor to modify the system.img and vendor.img files so that adbd has root privileges.

But when I opened magisk hide and restarted the device, the adbd root privileges became normal privileges.

How should this be resolved? After MAGISK HIDE is opened, ADBD still has root privileges?

**Comment by topjohnwu** [comment]
MagiskHide changes props that disable ADBD root, there is no way around it
