### ISSUE TITLE
Xperia 1 ii Android 11 official version magisk21.2 does not work

### ISSUE THREAD

**Issue by SJKSJ2** [topjohnwu/Magisk#3662]
[dmesg.log](https://github.com/topjohnwu/Magisk/files/5797386/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/5797388/recovery.log)

The model used is Sony Xperia 1 ii (XQ-AT52) Android 11 firmware.

The official version of Magisk that is experiencing the problem is version 21.2 (21200)
I installed the zip file with twrp
In this case, it is impossible to enter the Android itself, and only the Sony logo is repeated.

In this case, both beta versions 21.0~21.2 are the same

However, if you install the old version 20.4, you will be able to boot again. However, Magisk itself cannot be installed.

Manager uses the latest version 8.0.5 (4802)
Same symptom occurred in previous versions

I saved the recovery log and dmesg log in Recovery, but I don't know if the log files are correct
please check

Thank you for always having a good experience!

**Comment by Lucifersian** [comment]
使用一加7pro，pe10，同样情况。若更新21.2后，重启会卡在Qualcom Crashdump Mode。使用twrp刷入20.4则可正常开机。尝试了使用选择并修补档案提取了pe10的boot.img得到了magisk_patched_qJ2ku.img，在升级21.2后使用fastboot刷入magisk_patched_qJ2ku.img，依旧卡在Qualcom Crashdump Mode。

**Comment by topjohnwu** [comment]
@SJKSJ2 may you upload your stock boot image?

**Comment by topjohnwu** [comment]
Also, can you also provide the device info detected in Magisk Manager

**Comment by ACiDC0re** [comment]
Hi, 

same for me. Bootloop on Android 11 with Sony Xperia 1 II.
Tried with Canary and Stable.

I attached the stock boot image (EU Version)

Where can I find the device info in the magisk manager?

[boot_X-FLASH-ALL-2389.zip](https://github.com/topjohnwu/Magisk/files/5814756/boot_X-FLASH-ALL-2389.zip)

**Comment by SJKSJ2** [comment]
> Also, can you also provide the device info detected in Magisk Manager


[boot_X-FLASH-ALL-2389.zip](https://github.com/topjohnwu/Magisk/files/5814950/boot_X-FLASH-ALL-2389.zip)
[magisk_patched_zOgMc.zip](https://github.com/topjohnwu/Magisk/files/5814958/magisk_patched_zOgMc.zip)

XQ-AT52_Customized SEA_58.1.A.0.921-R2B firmware's default boot image and
This image file is a patch image file created in the manager app.

In my case, I did not use this because I installed the 21.2zip file with twrp.

Even if you manually install the file with adb instead of twrp, booting does not proceed in the same way.

**Comment by topjohnwu** [comment]
I just released a new canary build, may you please try it out and report back?

**Comment by SJKSJ2** [comment]
Please install it and we will give you quick feedback. Thank you

**Comment by SJKSJ2** [comment]
> I just released a new canary build, may you please try it out and report back?

I installed version 21202 of Canary

But the symptoms are the same

If you install the 20.4 zip file again, it will boot normally.
[dmesg.log](https://github.com/topjohnwu/Magisk/files/5815365/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/5815367/recovery.log)
![KakaoTalk_20210115_003647473](https://user-images.githubusercontent.com/77284225/104612701-d6609080-56c9-11eb-8520-76ce7f0e5cb7.png)

**Comment by topjohnwu** [comment]
I really need dmesg for a non-root session in order to debug this

**Comment by SJKSJ2** [comment]
> I really need dmesg for a non-root session in order to debug this

If so, can you tell me how to get the dmesg you need?

**Comment by topjohnwu** [comment]
You will need a custom kernel that can preserve last kernel dmesg, either through pstore or `/proc/last_kmsg`.
You install the custom kernel, boot, reboot to recovery, and get the last kernel logs from either location.
No clear instruction for how to do this as every single device is different. It also depends on kernel configurations

**Comment by SJKSJ2** [comment]
> You will need a custom kernel that can preserve last kernel dmesg, either through pstore or `/proc/last_kmsg`.
> You install the custom kernel, boot, reboot to recovery, and get the last kernel logs from either location.
> No clear instruction for how to do this as every single device is different. It also depends on kernel configurations

I kept trying, but it is difficult to obtain the last_kmsg log.
Probably because there is no su
Currently, I know that there is no way to acquire su in Android 11.
When inputting with the corresponding command
cat: /proc/last_kmsg: No such file or directory is displayed.

Do you ever need a log from adb shell cat /proc/kmsg?

**Comment by topjohnwu** [comment]
As I said, it is non trivial to get last kernel message, and unfortunately I cannot help you with that regard as each device is different. You can reach out to a custom kernel developer of your device for help

**Comment by topjohnwu** [comment]
I just released yet another canary build, it should fix bootloops for many devices. If you still experience bootloops, open a new issue with proper information needed for debugging. Thank you!

**Comment by riverO0o** [comment]
Now is Aug 10 and I get exactly the same error.
magisk is the latest version.
