### ISSUE TITLE
Magisk & Riru compatability

### ISSUE THREAD

**Issue by JMViertel85** [topjohnwu/Magisk#3664]
I am trying to install Riru core version 21.3 on my Moto Z2 Force.  With the new Magisk update, it won't let me manually install version 21.3 on my phone.  Because of this all Riru Edxposed modules on my phone are not working.  If you could tell me how to fix this issue or find a way to fix it in a newer update of Magisk it would be very appreciated.  
Thank you.

**Comment by theScrabi** [comment]
I think I have similar issues. I installed `21.2`, and now EdExposed is not working anymore. The EdExposed manager just tells it works but apparently exposed does not. I need it for signature spoothing for microg ant that tells me it is broken.

**Comment by QkiZMR** [comment]
I don't know if it's a problem with Riru but I can't even boot phone after update to 21.2. On 21.1 work fine. Moto Z3 Play here.

**Comment by linuxdep** [comment]
HTC U11 has after update to 21.2 a black screen, i have also run Riru running... 20.4 works fine

**Comment by Sh7777777** [comment]
Yes

**Comment by wangdaning** [comment]
It is an edxposed issue, you need to update that to be compatible with Riru core. I would suggest closing this issue as it is not a magisk issue.

**Comment by Raslin777** [comment]
Use custom channel till it gets sorted out...

https://raw.githubusercontent.com/topjohnwu/magisk_files/5bbdf65ab07249bb3560f5522ea1f71ff784c972/beta.json

**Comment by vvb2060** [comment]
Update Edxposed
