### ISSUE TITLE
Revolut is not working since 8.0.5 

### ISSUE THREAD

**Issue by 82a61101** [topjohnwu/Magisk#3670]
Oneplus 7tpro,
Android 10,
Magisk 21.2
Magisk manager :
Updated to 8.0.5 version. 
Revolut app stopped working saying cannot run on rooted devices.
Hide mode is enabled. 

Rolled back to 8.0.3, Revolut work is restored.

**Comment by IanWorthington** [comment]
Revolut working for me on 20.4 + 8.0.5
Asus zenfone 7

**Comment by Didgeridoohan** [comment]
#1152

**Comment by IanWorthington** [comment]
> #1152

Seems a tad officious?  If a new release BREAKS hide, I would say that that DOES warrant a report, no?  But not my project, so....
