### ISSUE TITLE
Cannot read xposed/edxposed error.log

### ISSUE THREAD

**Issue by Stillhard** [topjohnwu/Magisk#3671]
Since Magisk v21.2, the logs is not showing in the Xposed Installer/ EdXposed Manager.
Reverting to Magisk v21.1 fix the problem.

![photo_2021-01-12_13-32-18](https://user-images.githubusercontent.com/219005/104278178-bf0f8080-54da-11eb-9e09-b75605d5ed1f.jpg)
![photo_2021-01-12_13-32-04](https://user-images.githubusercontent.com/219005/104278181-c040ad80-54da-11eb-83aa-46f9dd455b4f.jpg)

**Comment by Haus3master** [comment]
I think it's edxposed fault, or, newer Magisk changed some of its core policies that require updating the module code...

**Comment by vvb2060** [comment]
Update edxposed

**Comment by Stillhard** [comment]
How can we blame it on **Xposed** too? sure you can blame it on EdXposed, but not **Xposed** 😭

**Comment by Stillhard** [comment]
@topjohnwu please re-open this as there still same problem to latest canary/debug

**Comment by LeeBinder** [comment]
Issue persists with Xposed. @topjohnwu, would you please reopen?

**Comment by Stillhard** [comment]
> Issue persists with Xposed. @topjohnwu, would you please reopen?

I can't remember since when the bug re-appeared, but with https://github.com/topjohnwu/Magisk/commit/0db405f2cc2062193620851093c1258f01942b7d the bug remains
