### ISSUE TITLE
Oneplus 8 pro magisk 21.1+ qualcomm crashdump

### ISSUE THREAD

**Issue by sdotter** [topjohnwu/Magisk#3673]
On Oneplus 8 pro android 10 i get qualcomm crashdump...
Cant boot into android... Tried 21.2... 21.1 same problem.
Works only on 21.0 or lower.
Fixed it by flashing backed up stock boot image
Couldnt get dmesg

**Comment by IanWorthington** [comment]
I had the same on asus zenfone 7 pro: bootloop + qualcomm crashdump
Reinstalled 20.4 using twrp, didn't try any other versions.
