### ISSUE TITLE
Can't flash modules (Mi A2 jasmine_sprout, PixelExperience 11)

### ISSUE THREAD

**Issue by Autoknacker** [topjohnwu/Magisk#3675]
Hello,

I flashed Magisk 21.2 using TWRP 3.5.0_9-0. Root is working, I can't flash modules tho. I wanted to flash a module I downloaded from XDA (I'm sure the module isn't broken or smth, it worked before I reset my phone). When I go ahead and flash it, Magisk doesn't give me any kind of error message and prompts me to reboot. After the reboot the module isn't installed. I can only install modules from within Magisk Manager. Also if I try to uninstall and re-flash Magisk, the uninstall.zip can't finish downloading

**Comment by Didgeridoohan** [comment]
Most likely incompatible module that worked with older releases of Magisk. Impossible to tell without the install log or possibly the module.

**Comment by Autoknacker** [comment]
Where do I find the log?
Should I upload the Module on GDrive or paste the link to XDA in here?
