### ISSUE TITLE
OnePlus 6 with android 10 gets random black screen on boot after updating from 20.4 to 21.2 

### ISSUE THREAD

**Issue by Thomasgitad** [topjohnwu/Magisk#3679]
Hello,
After updating magisk from 20.4 to 21.2 on stable chanel, everything seems ok, but when reboot after charging or power off and reboot,sometimes my phone get stuck on the homepage with a black screen, and later says"system is not responding", I will have to wait a while and then reboot again so it become normal.This just happened randomly,but when with 20.4,this stuck on reboot never happened.
Please check and update or may I know how to downgrade  to 20.4 without any lose?Thank you!

**Comment by v1993** [comment]
Same problem on different device. I've used (via TWRP) uninstaller from releases tab to get my phone to boot and will try to install old magisk (also via TWRP) now.

For me, zygote process kept dying and restarting forever.

**Comment by Thomasgitad** [comment]
Update：I tried to check MagiskHide Props moudle and midfield as follows: If boot takes longer than usual after setting a new fingerprint or a custom prop, try changing the boot stage to post-fs-data.      --- boot seems ok now. Why no need to modify on magisk 20.4?
