### ISSUE TITLE
CtsProfile failing since 12/01/2021

### ISSUE THREAD

**Issue by vlaraort** [topjohnwu/Magisk#3680]
Since 12/01/2021, looks like google has pushed some changes in their backends that make CtsProfile check not pass, It has been reported in a lot of forums and channels with different builds and magisk versions, betas and stables.

No workarounds has been found ATM sadly

https://forum.xda-developers.com/t/module-magiskhide-props-config-safetynet-prop-edits-and-more-v5-3-6.3789228/page-243

For example

**Comment by PropsFura** [comment]
You're right! I have the same issue since same update. I have tried to fix it at the same way I did earlier, doesn't seem to work. Let's wait until dev replies.

**Comment by PropsFura** [comment]
Also forcing basic key attestation and changing fingerprint doesn't work

**Comment by zgfg** [comment]
If it's already showing Basic eval type for CTS, then Forcing Basic cannot help

But btw, why should that be an issue (bug?) for Magisk

Magisk by default installs with MagiskHide disabled, and changing device fingerprint, forcing basic are not Magisk features

**Comment by saharandinesh** [comment]
CTS failing along with that Magisk Manager Hide (package name Change) getting failed.

**Comment by DoctorBagPhD** [comment]
Facing the same issue as OP, Google has changed something and SafetyNet is no longer passing. Changing my device's fingerprint does nothing, unfortunately, and I still fail the ctsProfile check.

basicIntegrity ✓
ctsProfile –
evalType BASIC

**Comment by gojmpz** [comment]
> Facing the same issue as OP, Google has changed something and SafetyNet is no longer passing. Changing my device's fingerprint does nothing, unfortunately, and I still fail the ctsProfile check.
> 
> basicIntegrity ✓
> ctsProfile –
> evalType BASIC

The same issue for me. Today Google play rolled big update and even forced to reboot. After that I cannot ctsProfile –

**Comment by PropsFura** [comment]
> If it's already showing Basic eval type for CTS, then Forcing Basic cannot help
> 
> But btw, why should that be an issue (bug?) for Magisk
> 
> Magisk by default installs even with MagiskHide disabled, and changing device fingerprint, forcing basic are not Magisk features
> 
> No guarantee that root will be hidden (btw, it asks here not to report issues about MagiskHide), and no guarantee about SafetyNet

I just thinking that it might be Magisk fault cause when I just have installed the update of Magisk, five minutes later I got a message from Google Pay that it won't work coz my device is rooted

**Comment by datspike** [comment]
> I just thinking that it might be Magisk fault cause when I just have installed the update of Magisk, five minutes later I got a message from Google Pay that it won't work coz my device is rooted
Nah I've got the message before updating Magisk.

**Comment by ewormPL** [comment]
Same problem here:

basicintegrity PASS
ctsProfile FAIL
evalType HARDWARE

**Comment by PropsFura** [comment]
> > I just thinking that it might be Magisk fault cause when I just have installed the update of Magisk, five minutes later I got a message from Google Pay that it won't work coz my device is rooted
> 
> Nah I've got the message before updating Magisk manager and Magisk itself
> 
> upd. I've had reports that this fixes the issue https://t.me/proton_p5_builds/34
> https://github.com/kdrag0n/safetynet-fix

Thank you, but how about Android 10? I have got one.

**Comment by PropsFura** [comment]
> > > I just thinking that it might be Magisk fault cause when I just have installed the update of Magisk, five minutes later I got a message from Google Pay that it won't work coz my device is rooted
> > 
> > 
> > Nah I've got the message before updating Magisk manager and Magisk itself
> > upd. I've had reports that this fixes the issue https://t.me/proton_p5_builds/34
> > https://github.com/kdrag0n/safetynet-fix
> 
> Thank you, but how about Android 10? I have got one.

nvm, have fixed it. Here is a fix for Android 10: https://forum.xda-developers.com/attachments/safetynet-fix-v1-0-2-android10-zip.5186073/

**Comment by QkiZMR** [comment]
@PropsFura how you fix it for Android 10? I want to do fix for Android 9.

**Comment by Varrkan82** [comment]
> > > > I just thinking that it might be Magisk fault cause when I just have installed the update of Magisk, five minutes later I got a message from Google Pay that it won't work coz my device is rooted
> > > 
> > > 
> > > Nah I've got the message before updating Magisk manager and Magisk itself
> >  https://forum.xda-developers.com/attachments/safetynet-fix-v1-0-2-android10-zip.5186073/

Don't work for Mi 9T Pro, Android 10, MIUI 12.0.3. Latest Magisk and Magisk Manager

**Comment by damonroberts95** [comment]
> > I just thinking that it might be Magisk fault cause when I just have installed the update of Magisk, five minutes later I got a message from Google Pay that it won't work coz my device is rooted
> 
> Nah I've got the message before updating Magisk manager and Magisk itself
> 
> upd. I've had reports that this fixes the issue https://t.me/proton_p5_builds/34
> https://github.com/kdrag0n/safetynet-fix

Flashing this on my Pixel 2 w/ stock Android 11 caused a crash as soon as the phone was unlocked, dumping you back to the lock screen. Had to uninstall Magisk to get it to boot again.
