### ISSUE TITLE
Fairphone 3 takes very long to boot if Magisk is installed and does not reboot most times if MagiskHide is activated

### ISSUE THREAD

**Issue by bege10** [topjohnwu/Magisk#3681]
- Fairphone 3
- TWRP recovery 3.4.0-0
- Magisk flashed via TWRP
   - Canary 6d88d8ad (21201) or
   - 20.4 or
   - 21.2
- OS (all Android 10)
   - Fairphone OS or 
   - LineageOS or 
   - /e/OS

If the phone has been turned on ~10 mins. or longer and I try to reboot (to system or TWRP recovery), the screen turns off and nothing happens any more and the phone does not react on any hardware buttons. I must take out the battery and put it back in to be able to boot the phone again. The phone is not completely shutdown, if I take out the battery and boot the next morning the battery charge has lost significantly.

For long term testing I did this:
- Install /e/OS (the issue is with all three mentioned OS)
- Test for 2 days: everything OK
- Install TWRP
- Test for 2 days: everything OK
- Install Magisk (no modules)
- Frequently tried to reboot the phone:
   - Less than ~10 mins. after booting the phone: phone boots OK
   - More than ~10 mins. after booting the phone: phone hangs as described

I also noticed that there is a delay in booting the phone if Magisk is flashed: Without Magisk it takes ~5 secs. from screen going off to reboot starts, with Magisk flashed and rebooting the phone shortly after is has been booted, it takes ~10 secs.

Log after booting the phone:
[magisk_log_2021-01-12T23_22_37Z.log](https://github.com/topjohnwu/Magisk/files/5805175/magisk_log_2021-01-12T23_22_37Z.log)
Log 20 minutes later (did not much happen):
[magisk_log_2021-01-12T23_44_36Z.log](https://github.com/topjohnwu/Magisk/files/5805253/magisk_log_2021-01-12T23_44_36Z.log)
(The changing time and date in the log comes from a bug in /e/OS that does not correctly support the RTC. Time and date must be set after each booting without SIM card.)

[TWRP-Backup of boot partition](https://www.file-upload.net/download-14437409/2021-01-13--05-38-58_e_FP3-userdebug_10_QQ3A200805001_engroot202.zip.html)

Boot log:
[20210113065924_boot_logcat.log](https://github.com/topjohnwu/Magisk/files/5806673/20210113065924_boot_logcat.log)
(Wrong date in the log same issue as with Magisk log)

**Comment by topjohnwu** [comment]
@bege10 have you tried disabling MagiskHide?

**Comment by sn-o-w** [comment]
Something extremely similar happens on my Nexus 5 as well. Sometimes device will not boot + delay after I reboot device (screen stays off pretty much before reboot starts, about 10-15 secs)

@topjohnwu I disabled MagiskHide and it seems this helps, but I'm not 100% sure of that. Maybe just placebo.

Anyways, installing and enabling a module like EdXposed will make the phone not booting most of the time, no matter if MagiskHide is disabled or enabled.

I'm not sure if this is caused by Magisk or EdXposed. Given the fact that @bege10 does not use EdXposed, I believe it could be caused by Magisk.

**Comment by sn-o-w** [comment]
I just make a test.

Rebooted device when EdXposed is disabled and MagiskHide disabled -> ~`10 seconds` (`5 seconds` "Phone is rebooting" notification + `5 seconds` screen off until rebooting and seeing Google logo)

Rebooted device when EdXposed is enabled and MagiskHide disabled -> ~`50 seconds` (`5 seconds` "Phone is rebooting" notification + `45 seconds` screen off until rebooting and seeing Google logo)

Almost a minute screen was off!

**Comment by bege10** [comment]
I tested only a few times. For now it looks like the phone boots correct if MagiskHide is disabled, hangs as decribed if enabled.

**Comment by bege10** [comment]
It looks like it takes as longer until booting starts as more modules are now installed. Together with Systemless Host I have now installed 10 modules. With Advanced Charging Control it takes up to 4 minutes from shutting down to the beginning of rebooting.

Canary 21406 (17) made it worse. After 10 mins. I took out the battery and booted the phone again. The phone did not reboot even with MagiskHide still being disabled. After installing Magisk 21.4 the state from before that Canary build is back: It takes 30 secs. to 4 mins. until the phone reboots.

**Comment by bege10** [comment]
Unfortunately the trouble continues also with the stable build. I had to uninstall and install anew Magisk to reduce the time until the phone reboots. It takes 30 to 300 secs until it starts to boot.
After installing Magisk anew I noticed that the time until the device eventually booted again lasted the longer the more modules where installed.
Meanwhile the phone randomly does not fully shutdown even with Magisk Hide disabled. After the screen turns black the phone does not react on any buttons or screen tapping, the battery has to be taken out to get the phone to boot again.

Is this issue an issue of Magisk or of the OS or the device interacting with Magisk?

**Comment by bege10** [comment]
Yesterday I updated to v22.0, rebooting took as long as always as posted above. Later I turned the phone off as every night.
Today the phone did not start, I had to remove the battery and put it in again to start the phone. The battery charge had dropped from 62% when turned off yesterday to 42% when started today.
So the booting/rebooting issue is still there with the new Magisk version.

**Comment by osm0sis** [comment]
This is weird and shouldn't really have anything to do with Magisk... Any change in latest Canary?

**Comment by bege10** [comment]
> ... shouldn't really have anything to do with Magisk... 

See my first post: Long term testing.

I had installed several Canaries until it went worse. Then I returned to stable/beta.
Current version is 22.0.
Current situation as before: rebooting takes 30 secs. - 4 mins. to start. About every 5th reboot or shutdown the phone does not react at all (must remove battery).

**Comment by osm0sis** [comment]
Okay, we need you testing on the latest canaries only though. 22004 currently.

**Comment by bege10** [comment]
> 
> 
> Okay, we need you testing on the latest canaries only though. 22004 currently.

Okay, will do ASAP in the next days.

**Comment by bege10** [comment]
> Okay, we need you testing on the latest canaries only though. 22004 currently.

You wrote "22004 currently". Magisk Manager shows 22003. Did you mean 22003 or shall I wait for 22004?

**Comment by osm0sis** [comment]
It's 22005 now. Use the latest.

**Comment by bege10** [comment]
> 
> 
> Okay, we need you testing on the latest canaries only though. 22004 currently.

I tested 22005, everything is still the same as reported https://github.com/topjohnwu/Magisk/issues/3681#issuecomment-799751479

**Comment by M-I** [comment]
+1
- Fairphone 3+
- /e/OS
- with stock recovery

I've never waited to see if the phone would eventually reboot. I've always been able to force poweroff/boot by holding the power button for ~10 seconds.

`adb reboot` works fine though.

Thanks, @bege10 for the [e.forum](https://community.e.foundation/t/fairphone-3-rooted-with-magisk-does-not-reboot/28273) post, I didn't make the connection with magisk.

**Comment by iRealistiX** [comment]
I think I have the same problem with my samsung galaxy a50 wich just freezes on the splash screen for like 2 minutes before showing the galaxy logo

Recovery: Orangefox r11
Magisk: v21.1
ROM: InfinityOS v3

**Comment by bege10** [comment]
> I've never waited to see if the phone would eventually reboot. I've always been able to force poweroff/boot by holding the power button for ~10 seconds.
> 
And I never waited that long when pressing the power button. Thank you for this workaround.

Nevertheless, it doesn't help with two issues:

1. If one does not want to reboot but shutdown the phone and it does not fully turn off, the battery has lost charge signiticantly the next day and the phone may not boot at all until one has charged for a while.
2. If one wants to reboot to recovery and one presses the power button very long one must be careful to press the volume up button in time not to land in system mode.

**Comment by bege10** [comment]
> `adb reboot` works fine though.

I just use adb and adb reboot bootloader does not work here, it hangs as with system commands, I have do reboot with hardware buttons.

**Comment by bege10** [comment]
@topjohnwu Hello,
the problem persists with v23001. Why did you close this issue?

**Comment by bege10** [comment]
@topjohnwu Today I wanted to reboot the phone with usb connection to PC and it did not reboot as before. But I noticed that while the screen was black the connection to the PC stopped and then was reestablished as an unspecified bulk usb device. That makes me believe that the phone does not freeze at shutdown but at very early boot even before it vibrates at the beginning of the boot process. Of course there is no log in this state of the phone.

**Comment by bege10** [comment]
> 
> 
> +1
> 
>     * Fairphone 3+
> 
>     * /e/OS
> 
>     * with stock recovery
> 
>     * Magisk 22.1
> 
> 
> I've never waited to see if the phone would eventually reboot. I've always been able to force poweroff/boot by holding the power button for ~10 seconds.
> 
> `adb reboot` works fine though.
> 
> Thanks, @bege10 for the [e.forum](https://community.e.foundation/t/fairphone-3-rooted-with-magisk-does-not-reboot/28273) post, I didn't make the connection with magisk.

Hi,
this issue has been closed without comment and solution.
Today I created a new issue.
https://github.com/topjohnwu/Magisk/issues/4434
If this is still an issue for you, too, would you, please, confirm it again?
Thank you very much.
