### ISSUE TITLE
shell script call ensure_bb() failed.

### ISSUE THREAD

**Issue by eagle518** [topjohnwu/Magisk#3682]
Magisk versionCode >= 20400 and busybox use standalone mode.

when call exec_command_sync("/system/bin/sh", "-c", script) in c/c++, script run failed in ensure_bb().

script like this:

constexpr char script[] = R"EOF(
#!/system/bin/sh

. /data/adb/magisk/util_functions.sh
setup_flashable

....  # failed and not reach here.

exit 0
)EOF";

exec_command_sync("/system/bin/sh", "-c", script);

**Comment by topjohnwu** [comment]
It should work now with the latest canary build
