### ISSUE TITLE
How to flash *.tar. xz files?

### ISSUE THREAD

**Issue by Rocky471** [topjohnwu/Magisk#3683]
Hi,

In the magisk manager app, in the modules section, when I select 'Add from internel storage option , it only  allows me to flash  ' *. zip'  files and all others are greyed out.

      I wanted to flash the Kali Nethunter module and the file format is   *.tar. xz
 
         How do I flash it??

Regards,
A happy Magisk user

**Comment by andyzot** [comment]
Did you get an answer? It says 'completed' but I don't see the solution??
