### ISSUE TITLE
Pixel XL lost sound with the latest Magisk Manager v8.0.5

### ISSUE THREAD

**Issue by lukepushsolo** [topjohnwu/Magisk#3691]
My Pixel XL running the last factory image 10.0.0 (QP1A.191005.007.A3, Dec 2019).
Recently I've found my moring alarm didn't work, phone calls didn't have ringstones and music player can't play music.
I tried to flash my phone and these issues disappeared, but after flashing Magisk v21.2 these issues arose again.
I flashed Magisk v21.1 and Magisk v21.0, both doesn't work. But once I downgrad to Magisk Manager v8.0.4, everything is fine.
I don't know how Magisk Manager v8.0.5 had caused these bugs, hope it would been fixed soon otherwise I really don't want to upgrade Magisk Manager anymore. IT REALLY COST ME SOME TIME TO FIND OUT WHAT HAPPENED!

**Comment by topjohnwu** [comment]
I am running on your exact same device, exact same OS, exact same Magisk, and sound is working. Are you a troll?
