### ISSUE TITLE
Systemless hosts module affect Google Services sync

### ISSUE THREAD

**Issue by jeka57** [topjohnwu/Magisk#3696]
Magisk Canary 21202 (installed at the moment) and older. 
If Systemless hosts module is enabled, Google Services such as Gmail and Google Photos doesn't work properly: I don't receive notifications from Gmail and I can't run synchronization manually.
When I disable the module, synchronization works again with no problem. And it's caused not adblocking app because I tried to disable and uninstall it. 

I've checked hosts files and found only one difference:

When the module is disabled
> 127.0.0.1 localhost
>  ::1 ip6-localhost

When the module is enabled
> 127.0.0.1 localhost
>  ::1 localhost

Any idea how can it cause such problems? Please help me :(

**Comment by Stillhard** [comment]
Duplicate #3686

**Comment by topjohnwu** [comment]
#3171

**Comment by jeka57** [comment]
Hi guys! Thanks for the replay!

> Duplicate #3686
Why is it a duplicate? I have no problem with adaway, hosts adds correctly when the module is enabled.

> #3171
So I saw that issue but I have no freezes at all, just synchronization problem. Additionally, my phone is Xiaomi Mi10 not Pixel. Is it connected with "F2FS driver bug" in a some way?

**Comment by Stillhard** [comment]
I have the problem too, i'm on nougat (yeah ikr), can't open youtube's videos via app using youtube's API.
So many bugs since v21, i reported one here #3671 and got closed instantly.
I hope all the great devs here can figure out the problem(s).
