### ISSUE TITLE
Latest canary Magisk unix_stream_socket policy

### ISSUE THREAD

**Issue by fenghao119** [topjohnwu/Magisk#3697]
When a program listens on unix_stream_socket with root privileges, the untrusted_app can not connect to this socket.  It must run `magiskpolicy --live "allow untrusted_app_all magisk unix_stream_socket { connectto }"` command to sovle this program.

**Comment by topjohnwu** [comment]
@fenghao119 it is explicitly designed to do that because it is a security issue when non root apps can connect to a root process. If you need communication, you should do it the other way: open a socket on the non-root process, and have to root process connect to it

**Comment by topjohnwu** [comment]
If you are looking for a proper way for communicating to a root daemon process from your root app, please take a look at `libsu`'s root service.
https://github.com/topjohnwu/libsu

**Comment by fenghao119** [comment]
@topjohnwu Thank you for your advice

**Comment by pandatabe** [comment]
#3697
