### ISSUE TITLE
Magisk Hide with SuperSU

### ISSUE THREAD

**Issue by vsilvar** [topjohnwu/Magisk#37]
In the latest version, magisk hide is automatically disabled if SuperSU is detected.
This means that, with a stock kernel, safety net will fail because I was relying on magisk to remove the tampered read-only system props.
Shouldn't the removal of the system props still run even if SuperSU is installed?

Magisk Version: v10.2
Android Version: 6.0.1

**Comment by topjohnwu** [comment]
I can consider make the reset tampered prop as a default setting.
BTW, how do you hide SuperSU? Using suhide?

**Comment by vsilvar** [comment]
Yes I was using suhide to hide both SuperSU and Xposed.
It's my understanding that there isn't any other method to hide Xposed, or am I wrong?
