### ISSUE TITLE
Bootloop after update to latest magisk version for LG G5 H850

### ISSUE THREAD

**Issue by nrvk-cell** [topjohnwu/Magisk#3700]
Today i have updated Magisk on my LG G5 H850 to the latest version. It was several days that I received the notification from the app, so this morning i decided to update. I selected the direct update (recommended) and hit "Restart".
After reboot now it opens LG logo, then the bootloader unlocked warning and it restarts to LG logo in loop.
I can't enter recovery mode, but only fastboot mode, when try to connect to download mode it pops up the firmware update but it's stuck at 0%.
I don't know how to provide a `dmesg` because I can't connect it to the pc.
Thanks for your help.

**Comment by topjohnwu** [comment]
I just released yet another canary build, it should fix bootloops for many devices. If you still experience bootloops, open a new issue with **proper information** needed for debugging. Thank you!

**Comment by dschall** [comment]
Same here.
I installed the magisk update from 12-28-2020 on my LG G5 H830 and now the phone is in a boot loop.
Sorry, I can't provide more information here, but, well, the phone's not working and I can't access any information on it.

**Comment by nrvk-cell** [comment]
I 

> Same here.
> I installed the magisk update from 12-28-2020 on my LG G5 H830 and now the phone is in a boot loop.
> Sorry, I can't provide more information here, but, well, the phone's not working and I can't access any information on it.

I solved it by installing the latest version of twrp, full wipe and installed the rom lineage 18.1 (with gapps lite) and magisk v20. I think I'll stick to this version of magisk to avoid a bootloop again.

**Comment by dschall** [comment]
> I solved it by installing the latest version of twrp, full wipe and installed the rom lineage 18.1 (with gapps lite) and magisk v20. I think I'll stick to this version of magisk to avoid a bootloop again.

I solved it by booting into TWRP (it finally worked after mashing the power button during boot), flashing a stock boot.img, followed by Magisk v21.
That even preserved my data and everything.
