### ISSUE TITLE
Revolut root detection

### ISSUE THREAD

**Issue by fusionneur** [topjohnwu/Magisk#3701]
I read that I shouldn't open such bug, but this is a matter which involves many ppl.

Even with magisk repackaged and revolut hidden from detecting magisk, with the new update 7.31 revolut locked out rooted users.

Is there any hope for us?

**Comment by t0ma5** [comment]
same here.. uninstalling Magisk Manager is my temporary fix

**Comment by fusionneur** [comment]
reason for closure?

**Comment by Mspy1** [comment]
> 
> 
> reason for closure?

**DO NOT** open issues regarding root detection.

**Comment by fusionneur** [comment]
So what options are there since more and more banking apps detect it. This is deffinetely something that could be improved on magisk side, so why would you close it...?

**Comment by Aethusx** [comment]
change manager name in settings, worked for me

**Comment by t0ma5** [comment]
it was the first I did but it didn't work. Manager stopped working
completely :(

**Comment by alakdae** [comment]
Changing name doesn't work with latest Revolut version 7.31

**Comment by flyl0-x** [comment]
same issue

**Comment by DanCasterIt** [comment]
Same issue. Further if I try to change name Magisk manager blocks and after I force reboot, the manager doesn't see anymore Magisk. Reinstalling or uninstalling and reinstalling Magisk does not solve the problem unless I install Magisk 21.0, Update to recent Magisk and then I'm at the starting point again

**Comment by fusionneur** [comment]
Personally i tried the magisk feature from settings to repackage it under different name, but didn't help.

**Comment by alex193a** [comment]
ℹ️ For information purposes: 
Revolut 7.31+ searches for a file called "**magisk**" in the following paths:
/cache/
/data/
/data/local/
/data/local/bin/
/data/local/xbin/
/dev/
/sbin/
/su/bin/
/system/bin/
/system/bin/.ext/
/system/bin/failsafe/
/system/sd/xbin/
/system/usr/we-need-root/
/system/xbin/

It also check if these apps are installed:
com.alephzain.framaroot
com.amphoras.hidemyroot
com.amphoras.hidemyrootadfree
com.devadvance.rootcloak
com.devadvance.rootcloakplus
com.formyhm.hideroot
com.formyhm.hiderootPremium
com.kingo.root
com.kingroot.kinguser
com.koushikdutta.superuser
com.noshufou.android.su
com.noshufou.android.su.elite
com.saurik.substrate
com.smedialink.oneclickroot
com.thirdparty.superuser
com.topjohnwu.magisk
com.yellowes.su
com.zachspong.temprootremovejb
com.zhiqupk.root.global
de.robv.android.xposed.installer
eu.chainfire.supersu

**Comment by fusionneur** [comment]
one might give a try to storage isolation riru app and magisk module. I have a feeling that it might do the trick

**Comment by hugoncosta** [comment]
Can confirm the newest version works again with root (7.31.1)

**Comment by izrut** [comment]
7.32(beta) detects the root

**Comment by fusionneur** [comment]
Works on 7.31.2

I used:
AM Pre-release > hide with magisk option
Magisk > hide for revolut, repackage magisk

Revolut will require photo of yourself again

**Comment by izrut** [comment]
> Revolut 7.32(beta) detects the root.
> 
> Samsung S8
> Android 10 FluidOS
> Magisk 21.3 / Manager 8.0.6

I succeeded running Revolut again. 
When U open the Magisk at the bottom of the screen (on Android) 4 icons apper.
Select the "Shield" and choose Revolut app in the following menu.

Cheers!

**Comment by Germano0** [comment]
> **DO NOT** open issues regarding root detection.

Why not? It is the Magisk Hide purpose!

**Comment by DomenicoakaTDG** [comment]
### How to solve the ROOT problem with the Revolut App (method updated to 20-01-21
Hi everyone, I'm Domenico. A daily-basis user of the Revolut App. I'm currently on my SONY XPERIA XZ PREMIUM (Model: G8141) with the STOCK ROM but rooted Android 9 system, and this method is how you WILL solve the problem (I hope for good, not only specific to my case) without UNISTALL nothing! Almost forgot → The version of the Revolut app is the 7.32, so it's the latest!

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
PROCEDURE ↓
**You got Magisk for manage your root privileges, right? Otherwise I can't help you, I'm sorry! But if you have MAGISK (like the 99,99 % of user that rooted their phones have) you must update to the specific version that I will list hereafter: 21.4 (21400) version of MAGISK and 8.0.7 (4834) version of the MANAGER. What are you waiting for? Just update to those, or I can't assure you the method I will explain to you will work. Done? Good... So open MAGISK up and select the Jigsaw puzzle icon (in the "floating deck" that appears if you scroll down enough made of four "buttons") to install new modules. Once you're done that you'll find yourself in another screen. In that screen scroll down and find, and then install, the module called 'Magisk DRM Disabler (MDD)'. Let Magisk works its magic and reboot the Android System. If all went smooth, I assure that the annoying screen that Revolut don't support rooted phones anymore will not bother you anymore and you can log again with your profile on the Revolut App!
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

P.S: The application even if correctly working, is lacking many "animations" (can I call them that way? IDRK) and on-screen pop-ups that used to appear previous to this WORKAROUND. I think is related to the module that removes completely *Digital Rights Management* (DRM) from the SYSTEM as other applications gives me random errors (DON'T WORRY: NO critical errors). You can always unistall and reinstall when needed! Hope this clears things out if you encounter problems outside Revolut from now on. I witnessed a EXTRA overall slowness of the system after the module installed but a really light one! So DO IT AT YOUR OWN RISK. That been said I freaking hope that sooner than later Revolut will retrace its steps and fix the issue! 
That would do it for me! Thank you for reading till the end and TO THE NEXT ONE!
Bye 👋

![Magisk Module](https://user-images.githubusercontent.com/77741077/105206096-421d8000-5b46-11eb-9746-a64f9aa840a2.png)
![Magisk version](https://user-images.githubusercontent.com/77741077/105206100-42b61680-5b46-11eb-8351-85d30299fd19.png)
![Revolut App version](https://user-images.githubusercontent.com/77741077/105206102-434ead00-5b46-11eb-97c4-0fd58888ac05.png)

**Comment by fusionneur** [comment]
you don't need to do that... (previous comment). AM-prerelease can hide it.

**Comment by t0ma5** [comment]
> AM-prerelease

???

**Comment by fusionneur** [comment]
AppManager (the pre-release 2.5.22 is the one i tested and works). you can find it on github or f-droid

**Comment by t0ma5** [comment]
> 
> 
> AppManager (the pre-release 2.5.22 is the one i tested and works). you can find it on github or f-droid

https://i.imgur.com/CjBkRQo.jpg   ??? :)

**Comment by fusionneur** [comment]
when you open an app settings inside AM > go to ... (top right) > enable magisk hide 

For some reason this works (even if in magisk was already hidden previously)....

**Comment by t0ma5** [comment]
> 
> 
> when you open an app settings inside AM > go to ... (top right) > enable magisk hide
> 
thanks for the tip! but I get this msg "Could not enable MagiskHide"

**Comment by fusionneur** [comment]
You can open an issue to AM, I didn't get any message though.. cheers

**Comment by DomenicoakaTDG** [comment]
Thanks for the responses guys, but I had already said the App Manager Magisk Hide options didn't work for me! So I came up with that procedure. I hope helps other with the same problem. Peace out ✌️

**Comment by drdedus** [comment]
can we in install revolut beta with the latest stable magisk and just the hide option for revolut enabled?
do we need to rename the magisk? 
i am with los16.

**Comment by DocMAX** [comment]
is revolut still not working?

**Comment by fusionneur** [comment]
did you try it? give more details .. magisk version, revolut version. did you try AM (as suggested above)?

**Comment by alakdae** [comment]
It's working now correctly

W 15 lutego 2022 18:37:26 DocMAX ***@***.***> napisał:

**Comment by alakdae** [comment]
Magisk 23.0
Revolut version 8.40.1
Just using MagiskHide

W 15 lutego 2022 18:53:22 Future ***@***.***> napisał:

**Comment by fusionneur** [comment]
things to try (from previous comments):
1. repack magisk into an apk with different name (see magisk settings)
2. use magisk hide (v23)
3. use AM (Application Manager from f-droid) - magisk hide feature (v23)
4. upgrade to magisk v24, enable zygisk and denylist and add it to the denylist

Personally, after upgrading to v24 i didn't even have to add it to the denylist and it was working, but I had the magisk repacked with different name, so point 1. should be enough i suppose.

**Comment by fusionneur** [comment]
what version of AM do you use?

**Comment by fusionneur** [comment]
I think you might be using the alpha version .. in that case i see in your list magisk denylist which could be used from am or from magisk itself after enabling zygisk on magisk >v24

**Comment by GenTapDude** [comment]
> what version of AM do you use?

3.0.0 alpha01

**Comment by LorisTecnology** [comment]
https://telegra.ph/How-to-Hide-Root-In-Magisk-Canary-01-07

i've used this and works flawlessly

**Comment by GenTapDude** [comment]
> https://telegra.ph/How-to-Hide-Root-In-Magisk-Canary-01-07
> 
> i've used this and works flawlessly

I managed to fix it myself after posting my previous comment but thanks. The tutorial you linked looks clean and simple so it might be helpful for any one that comes here.

**Comment by steed182** [comment]
> > https://telegra.ph/How-to-Hide-Root-In-Magisk-Canary-01-07
> > i've used this and works flawlessly
> 
> I managed to fix it myself after posting my previous comment but thanks. The tutorial you linked looks clean and simple so it might be helpful for any one that comes here.

After trying this myself I can confirm that the approach that LorisTecnology talks about works flawlessly!

**Comment by FOREVEREALIZE** [comment]
Using Magisk 25.2 and Revolut 4.5, adding Revolut to the DenyList, enforcing the DenyList and turning on Zygisk, it worked flawlessly

**Comment by reptilano** [comment]
[Help] How to open banking apps on Emulator with Magisk (Bluestacks, LDPlayer, MEMu...)?

I tried installing Magisk and following the steps for root. However I still dont manage to open banking apps such as revolut, or any at all...

**Comment by t0ma5** [comment]
> [Help] How to open banking apps on Emulator with Magisk (Bluestacks, LDPlayer, MEMu...)?
> 
> I tried installing Magisk and following the steps for root. However I still dont manage to open banking apps such as revolut, or any at all...

What [FOREVEREALIZE](https://github.com/FOREVEREALIZE) wrote is very simple and it works perfectly. Try it :)

**Comment by victorballester7** [comment]
Hi @t0ma5 and the others!

I'm having problems in signing up in Revolut from my rooted phone (Xiaomi k20 = mi 9t). I've already putted Revolut into the Deny list and changed and hided the name of Magisk app. The problem is in the id verification, that opens a 'camera app' from 'onfido | real identity' and my screen turns black with the top bar and so cannot scan my identity card. Is this something related to root (I suppose it is...). In that case, do you know what can I do? My other banking apps work fine and even the Google wallet!

Thank you, I will appreciate any kind of help!!!

**Comment by edricus** [comment]
![Screenshot_20231217-211011](https://github.com/topjohnwu/Magisk/assets/83724412/2161b526-f0c5-4500-ae8d-bc22037c5118)
![Screenshot_20231217-211139](https://github.com/topjohnwu/Magisk/assets/83724412/d94a0f0c-744c-4be0-9cff-16f2cbc1a370)
![Screenshot_20231217-211148](https://github.com/topjohnwu/Magisk/assets/83724412/5c97ed9b-fde0-44e1-b9a0-abc770b94479)

Anyone else having this problem ?  
Revolut isn't installable anymore  
I have a Pixel 6A on Android 14 and it install just fine with stock android  
I passed safetynet and it's still not installable  
HOW ???

**Comment by victorballester7** [comment]
Can you install other apps? It happend to me that I couldn't, but then hiding other apps from the system (the ones related to installation of packages) in magisk solved that.

**Comment by edricus** [comment]
> Can you install other apps? It happend to me that I couldn't, but then hiding other apps from the system (the ones related to installation of packages) in magisk solved that.

What apps are you talking about ? Yes I can install any apps just fine, and hiding play store, play service, package installer and restarting doesn't solve the problem

**Comment by victorballester7** [comment]
Then, you can try installing Revolut from an apk through your browser.

**Comment by edricus** [comment]
update:
[Followed this tutorial](https://droidwin.com/how-to-hide-root-from-apps-via-magisk-denylist/#STEP_2_Enable_Zygisk_and_Enforce_DenyList)  
Now it's installable, look like the play store keep the rooted state in cache so we have to delete it (from every play related applications) and restart the device
Thanks for the fast responses

**Comment by ziomek64** [comment]
> update:
> [Followed this tutorial](https://droidwin.com/how-to-hide-root-from-apps-via-magisk-denylist/#STEP_2_Enable_Zygisk_and_Enforce_DenyList)  
> Now it's installable, look like the play store keep the rooted state in cache so we have to delete it (from every play related applications) and restart the device
> Thanks for the fast responses 

Is it still working?

**Comment by VeRychard** [comment]
> I use magisk 28.1 and as of today Revout app works. But the 'Revolut Business' doesn't work. Any hints highly appreciated.

can you tell me what your setup is? what modules and hide settings you have? I just installed freshly everything and cannot get Revolut to work.

**Comment by VeRychard** [comment]
> just add revolut to magisk denylist, either from magisk (28.1) itself or from AM (application manager v3.1.7 build 430)

I've started with that as well, but it kept telling me that I cannot use it on a rooted device, then I went on with Zygisk next, Zygisk Assistant, Shamiko, even installed the Magisk Alpha, nothing solved it. Can you tell me which version of Revolut do you have? I got 10.60.1 and none of the above methods worked with it :/

**Comment by VeRychard** [comment]
After a restart now it only says it doesnt support devices with custom firmware 😢

**Comment by VeRychard** [comment]
Lineage 21, on a Xiaomi Redmi Note 9 Pro (joyeuse). Can it be that it recognizes the bootloader is open?

**Comment by VeRychard** [comment]
> > After a restart now it only says it doesnt support devices with custom firmware 😢
> 
> firmware refers to kernel, and lineage indeed has its own kernel depending on the model
> 
> i am using original OS ROM (oxygenos on oneplus)
> 
> did you try resetting revolut's app data ?

Yes I have but no success. Now I'm looking for an older working version, maybe I can log in there and then update it.

**Comment by VeRychard** [comment]
In the end I went with a different ROM on Stock firmware and the Magisk hide solution (zygisk + systemless host + play integrity fix) with any extra black magic, and now everything works ^^ thanks for the notes and links, they helped a lot

**Comment by VeRychard** [comment]
> > In the end I went with a different ROM on Stock firmware and the Magisk hide solution (zygisk + systemless host + play integrity fix) with any extra black magic, and now everything works ^^ thanks for the notes and links, they helped a lot
> 
> mind sharing the technical details including the black magic :) ?

Sorry, typo.. without any black magic. 😄 

So the full process was:
I had a wiped phone with unlocked bootloader >> installed stock firmware >> installed PixelOS >> Magisk (patched boot.img), applied Zygisk, Systemless Hosts, and added the module Play Integrity Fix (by chiteroman) >> Installed Revolut >> hid Magisk from Revolut via the DenyList, enabled Enforce Denylist >> Restart >> Revolut works as it should

**Comment by VeRychard** [comment]
> > PixelOS
> 
> ah sorry, i got it. i thought pixelOS is the default stock os for Xiaomi.

Yea, I had to install original Xiaomi EU image first so the PixelOS could piggyback on it (I might be wrong, but that was the order I had to install them)

**Comment by VeRychard** [comment]
> uname -a

Oh my.. 🤯 
Sure, here it is
`Linux localhost 4.14.336-gcf64d5f0a97a #1 SMP PREEMPT Tue Aug 20 12:21:01 CEST 2024 aarch64 Toybox`

**Comment by XanderTheDev** [comment]
I'm also on lineageos 21 (but with microg). I also can't use Revolution. This is my kernel info:

`Linux localhost 4.14.190-perf+ #1 SMP PREEMPT Wed Aug 7 06:52:07 UTC 2024 aarch64 Toybox`

**Comment by XanderTheDev** [comment]
> > I'm also on lineageos 21 (but with microg). I also can't use Revolut. This is my kernel info:
> > `Linux localhost 4.14.190-perf+ #1 SMP PREEMPT Wed Aug 7 06:52:07 UTC 2024 aarch64 Toybox`
> 
> Hmm, nothing from the banned list.. Do you get the error of "rooted device" or "custom firmware" from Revolut?


![Screenshot_20250109-204950_Revolut](https://github.com/user-attachments/assets/20d65359-2d54-4482-a39f-0b7f35fb5314)

Translation for above text: Sorry Revolut does not support rooted devices

**Comment by VeRychard** [comment]
Have you tried any combination of Zygisk next, Zygisk Assistant, Shamiko, and play integrity fix? For me they proved to be enough to get over the "rooted" error (with some reboots), and after I got stuck with a new error of "no custom firmwares". Maybe it will work for you.

**Comment by XanderTheDev** [comment]
> Have you tried any combination of Zygisk next, Zygisk Assistant, Shamiko, and play integrity fix? For me they proved to be enough to get over the "rooted" error (with some reboots), and after I got stuck with a new error of "no custom firmwares". Maybe it will work for you.

I only have Zygisk - LSposed 1.9.3_mod and play integrity fix v18.2 from chiteroman.

What are those other things you mentioned?

**Comment by VeRychard** [comment]
Some modules I've been trying for a workaround based on the provided links and sources of the community.

**Comment by XanderTheDev** [comment]
> > I'm also on lineageos 21 (but with microg). I also can't use Revolut. This is my kernel info:
> > `Linux localhost 4.14.190-perf+ #1 SMP PREEMPT Wed Aug 7 06:52:07 UTC 2024 aarch64 Toybox`
> > Oh yea BTW, I have no problems with Play Integrity or safetynet. I have MEETS_DEVICE_INTEGRITY on play integrity and all passes on basic for safetynet
> 
> did you add revolut to the denylist in magisk?

Yes

**Comment by XanderTheDev** [comment]
> Some modules I've been trying for a workaround based on the provided links and sources of the community.

What combination do you have? I just installed Shamiko and turned off enforce denylist, but that changes nothing (also after rebooting and resetting the revolut app)

**Comment by VeRychard** [comment]
> > Some modules I've been trying for a workaround based on the provided links and sources of the community.
> 
> What combination do you have? I just installed Shamiko and turned off enforce denylist, but that changes nothing (also after rebooting and resetting the revolut app)

I had zygisk next instead of the default zygisk (u need to turn that off) and zygisk assistant for the hiding of magisk itself iirc when the "rooted" error was gone. (also make sure that in the deny list you have all the checks ticked for revolut)

**Comment by XanderTheDev** [comment]
> > > Some modules I've been trying for a workaround based on the provided links and sources of the community.
> > 
> > 
> > What combination do you have? I just installed Shamiko and turned off enforce denylist, but that changes nothing (also after rebooting and resetting the revolut app)
> 
> I had zygisk next instead of the default zygisk (u need to turn that off) and zygisk assistant for the hiding of magisk itself iirc when the "rooted" error was gone. (also make sure that in the deny list you have all the checks ticked for revolut)

Ok did that, but still same error in revolut

**Comment by bugsyb** [comment]
I've run into same issue - the latest Revolut 10.61 does some additional checks and Magisk 28.1 with what worked well Zygisk, Magisk hidden under different name, Revolut on the DenyList, but no "Enforce" - worked for years. Now it does not.
Didn't have time to run tests, though those having it running on this Revolut version - would be great if could share.
For sure Revolut 10.49 didn't have that issue, though it refuses to work and calls for an update. Feeling is that there's an interim version which will work and yet not being that smart to find Magisk.
We need to outsmart it again :)

**Comment by skadge** [comment]
@bugsyb tried today with 10.54: loke 10.56, I can reach the login screen, but it then requires to update to the latest app version.

**Comment by bugsyb** [comment]
> @bugsyb tried today with 10.54: loke 10.56, I can reach the login screen, but it then requires to update to the latest app version.
> 
> What if we spoof the app version in the apk directly? 😅

Ha, that's thinking out of the box :) I might give it a try if will fail trying other approaches. This might be though a bit too tricky for others and pretty tiring with all the app changes/updates.

Hopefully there's another way to get around this latest problem. What the heck did they change and why are they trying to lock it out.

**Comment by JingMatrix** [comment]
You may try blocking its internet request of version checking.

**Comment by bugsyb** [comment]
Any thoughts on an easy way how to do it without disassembling apk?

**Comment by SelfRef** [comment]
I've tried to use Zygisk Assistant to hide root from Revolut but it's not working either. No other app, including banking apps are complaining about root when added to Deny List.

**Comment by LorisTecnology** [comment]
use Hail, hide magisk from list

**Comment by r0d0dendr0n** [comment]
> use Hail, hide magisk from list

Which mode to hide Magisk did you use in Hail?

**Comment by SelfRef** [comment]
> use Hail, hide magisk from list

It is not necessary. Magisk has built-in ability to hide itself within a different package name, but it won't work in the case of Revolut.

**Comment by bugsyb** [comment]
Revolut 10.60 - on one of the phones, running a vendor custom firmware (Unihertz), Android 14, Magisk 28 (hidden under different name), Zygisk, Revolut not on Deny List, Shamiko 1.1, all Google removed, just MicroG and it works!
Happy to share if any further details would make it easy to narrow it down why it works here and how to make it working elsewhere.
The downside is... that Revolut Team might be watching this thread too. 

I have no clue why would they want to block it all - as it is my own decision on where I want to run their software and if I make it safe for myself or not - they will either way deny any responsibility in any case - so wtf?! Just don't block it Revolut Team.

**Comment by ag16243151** [comment]
I got it to work somehow...
Here is what i know.
OnePlus 13 CN variant, flashed OxygenOs15
Magisk alpha installed. Hidden.
Deny list: Google Play Services, Google Play Services for AR, Google Play Store, Revolut.
DenyList not enforced.
Modules installed: Play Integrity Fix 18.3 by chiteroman, shamiko 1.2.1, Zygisk Next 1.2.7
Here a few pictures.

![Image](https://github.com/user-attachments/assets/4614c17d-4456-4a94-afff-3110345366e0)
![Image](https://github.com/user-attachments/assets/c79b46c0-f82e-449e-b29b-30a5b04ac07e)
![Image](https://github.com/user-attachments/assets/375a0a2f-fb47-4b12-9aa7-8b2781b878d5)

**Comment by EvgeniySpinov** [comment]
@ag16243151 
Question is: does it work when you've logged out and going to login again? Because this is when root detection happens in a hard way.

**Comment by ag16243151** [comment]
@EvgeniySpinov 
Just logged out, deleted App data and logged back in.
Can confirm as working.

**Comment by EvgeniySpinov** [comment]
Thank you for confirmation. I've installed Shamiko 1.2.1, Play integrity fix 18.3v, Magisk 28.1 and was able to pass root screen. Revolut in Deny List and Deny List is enforced.

However now I have "custom firmware is not allowed" message. I'm using LineageOS 21. Is it something that could be fixed by Magisk and/or modules?

**Comment by ag16243151** [comment]
@EvgeniySpinov 
Maybe its because im running OxygenOS instead of a AOSP based ROM?!
Not sure though. Never got the "custom firmware is not allowed" message.

**Comment by bugsyb** [comment]
To finish my update - I've found out that Revolut might need to be installed also from Play Store.
Tried all what worked on other system/phone on tablet running crDroid and can't get it to work - didn't manage to get there Play Store yet.

In the past, there was Xprivacy project for LSPosed, which allowed to spoof anything requested by any software. Maybe this would be a route (unsure if that Xprivacy is alive still).

**Comment by EvgeniySpinov** [comment]
I'm installing it from Play Store. Tried to tinker with older versions, but anything from 10.50 till 10.58 (excluding) asks for update on login and 10.58+ are detecting root. Cannot get past that stage, it seems without Magisk Alpha.

**Comment by bugsyb** [comment]
Aurora store - this is what I've used and it shows as installed from MicroG - maybe I've missed to configure something on that tablet, or crDroid gets discovered as rooted device - seen it as listed that by kernel name it will just always fail.

Found just now also this:
https://github.com/0bbedCode/XPL-EX/tree/new
Though the moment it is enabled for Revolut it shows even different error prior really loading app, claiming environment is unsecure.

**Comment by SelfRef** [comment]
I'm really not a fan of this shady Magisk Alpha fork, but it looks like this is the only solution that works for me on stock Nothing Phone (1) + microG for now. Not even hiding Magisk app is necessary.

**Comment by bugsyb** [comment]
Just a gut feel - maybe Revolut searches in a specific way specifically for Magisk existence and because of some minor differences does not catch Alpha? I've a feeling that it might be just a coincidence rather than on purpose added feature in Alpha.

**Comment by r0d0dendr0n** [comment]
@bugsyb alpha also spoofs rom version. Even if you hide root, when you're on custom rom like lineage, revolut will say it only works on stock.

Alpha did the trick for me.

**Comment by r0d0dendr0n** [comment]
None of the above.

I installed from App Center.

Yeah, the site looks like it says it will take over my life, enslave my town and god knows what else. I guess my soul is not worth that much. At least Revolut is working.

**Comment by SelfRef** [comment]
> what is app center . is it brand specific? can you paste a link or suggestion where i can find it?

This is the official download page, just hit Download:
`https://install.appcenter.ms/users/vvb2060/apps/magisk/distribution_groups/public`

Take into account it's NOT open source and a little fishy, so use at your own risk. I personally didn't find anything concerning by using it, but you never know.

**Comment by r0d0dendr0n** [comment]
> ok found some info about it, but as you said, being closed source - i also highly recommend against it, unless you want your revolut money gone

Yeah, that old thread where one guy says that m alpha dev is "extremely untrustworthy". Read on and you see: "To be very honest: I hate this childish behavior of developers bashing developers."

It's just words against words. And the magiskalpha telegram has over 50k subscribers. The fork is a couple of years old and no one has been stolen from... yet. Maybe devs are planning an exit scam. Maybe they're honest.

**Comment by bugsyb** [comment]
A silly ask - is there a way to have an option in standard Magisk please to do what Alpha does - spoof of kernel? 
That would be amazing and less risky.

**Comment by r0d0dendr0n** [comment]
> > reason for closure?
> 
> **DO NOT** open issues regarding root detection.

Afaik the developers are not interested in hiding root.

**Comment by MagicRB** [comment]
Is there no way to bypass this with a Magisk module? I heard that APatch does work, so thats a way, personally Magisk Alpha is unnacceptable
