### ISSUE TITLE
Update Manager to 8.05 was ok, but Bootloop after Update 21.2 from 20.4 - Poco F2 Pro Miui 12.0.4 QJKMIXM 

### ISSUE THREAD

**Issue by Wayne-interrssierts** [topjohnwu/Magisk#3702]
First, i have no TRWP installed. 

Well, after the boot loop I thought, just install the original Boot.img from the firmware and then the cell phone works again, that only worked halfway, cell phone booted normally again, BUT NO WiFi anymore, as soon as I switched it on, the WiFi symbol remained 1 second blue, then gray again, so it only stayed on for about 1 second.

I had to completely install the original firmware using the fastboot method, which luckily worked without losing my data.

But what I don't understand at all is that there is absolutely NO possibility via the Magisk Manager to downgrade an older version of Magisk in the case of a brick and not only that, also the trick with the URL as RAWLINK no longer works, because the older version is almost impossible to find immediately, so that the link can be generated, it couldn't be more unfriendly to the user, the shit cost me hours until I had a fully functional system again and finally rooted again with version 20.4.

Now the new update Miui 12.2.4 with Android 11 came, which I also installed, the system is still stable, but I have not yet patched and flashed the original Boot.img with Magisk 20.4, but I better not get the 21.2 back try or who can guarantee that there is no boot loop this time with the new Android 11 and new Miui 12.2.4 RJKMIXM version?

**Comment by Kwbmm** [comment]
Got in a bootloop flashing 21.2 too..

Also using Poco F2 Pro but MIUI 12.0.3 QJKEUXM .

Fixed it by going into twrp and flashing 20.4 (it's a version I already had on the phone)

**Comment by topjohnwu** [comment]
There is a new canary build
