### ISSUE TITLE
Magisk cannot handle g7 play, "Bad system call" on repack

### ISSUE THREAD

**Issue by jnotuo** [topjohnwu/Magisk#3703]
``` 
g7 play
  android 10 (lunched 9)
  A/B partitions
  no recovery partition
  bootloader uses skip_initramfs
Boot: kernel mounts partition system_x as / (ramdisk is *not* used)
Recovery boot: kernel mounts ramdisk as /
-----------------------------------------------
Install Magisk (last canary 04c53c35):
  Ramdisk:Yes  A/B:Yes  SAR:Yes
Boot: kernel mounts partition system_x as / (no magisk)
Recovery boot: 'magisk init' calls RecoveryInit (enter in recovery)
-----------------------------------------------
One way for magisk work *only* in this case is:
patch getinfo.cpp:
   if (1 /*key == "RECOVERYMODE" && value == "true"*/) {
and init.cpp will call SARInit or RecoveryInit
```
 
[proc-mounts.txt](https://github.com/topjohnwu/Magisk/files/5822001/proc-mounts.txt)

[boot.img.gz](https://github.com/topjohnwu/Magisk/files/5822020/boot.img.gz)

**Comment by topjohnwu** [comment]
Is your device 32-bit?

**Comment by jnotuo** [comment]
Yes.

**Comment by krystalgamer** [comment]
Magisk v23 and canary still don't work with g7 play :/

Flashing boot.img or installing via twrp yields similar results - they run successfully but magisk is not installed.
Is there anything we can do in the meantime?

**Comment by osm0sis** [comment]
Any luck with 23013? A number of regressions have been fixed.

**Comment by jnotuo** [comment]
Install error: Bad system cal
[magisk_install.log.gz](https://github.com/topjohnwu/Magisk/files/7501050/magisk_install.log.gz)
[boot-52-22-14.img.gz](https://github.com/topjohnwu/Magisk/files/7501058/boot-52-22-14.img.gz)

l

**Comment by osm0sis** [comment]
Note your boot.img does repack without error on my device, so it's some issue within the repack function that your device can't handle.

@chaosmaster if you have time please take a look at the log, I have a hunch the bad sys call is during the ZIMAGE support repack.

**Comment by chaosmaster** [comment]
Unfortunately I cannot reproduce the error, the provided boot.img repacks fine here as well :thinking:

**Comment by osm0sis** [comment]
Exactly, must be something related to the device/OS. Any logs @jnotuo could grab for you to help figure it out?

**Comment by chaosmaster** [comment]
Can't think of anything useful ATM.
All I can think of is building a magiskboot binary with some debug-printfs added.
Though not sure when I'll have the time to do that.

**Comment by osm0sis** [comment]
Here's the most recent static arm strace binary I've got: https://androidfilehost.com/?fid=4349826312261818888 

Might show something if @jnotuo could get root some other way to run it.

**Comment by jnotuo** [comment]
The bad system call is from "truncate".
Is not using truncate64 ?!?
sizeof(off_t) = 4
strace (termux)
[strace.log.gz](https://github.com/topjohnwu/Magisk/files/7505632/strace.log.gz)

**Comment by jnotuo** [comment]
Tried to generate de boot.img on PC (linux) using
native/out/x86_64/magiskboot
and the size of new-boot.img is 4313108480 bytes ?!?

hdr->kernel_size()  -->   unsigned 32 bits
off_t  -->  64 bit signed

the casting corrects:
ftruncate(fd, lseek(fd, -(off_t)hdr->kernel_size(), SEEK_CUR));

**Comment by chaosmaster** [comment]
Adding the cast to off_t fixes the "Bad system call" ?
Does the kernel boot?

**Comment by jnotuo** [comment]
The cast not fixes "Bad system call" because it tries to use ftruncate sys call that not exist.
I did not try to install new-boot.img generate in PC.

**Comment by chaosmaster** [comment]
On PC repack works fine for me without the cast.

**Comment by jnotuo** [comment]
try compile and execute:
<pre>

#include <stdio.h>
int main()
{
	unsigned int u = 100;
	long i, j;
	i = -u;
	j = -(long)u;
	fprintf(stderr, "i=%lx j=%lx u=%u\n",
			i, j, u);
	fprintf(stderr, "sizeof(i)=%ld sizeof(u)=%ld\n",
		       sizeof(i), sizeof(u));
}

i=ffffff9c j=ffffffffffffff9c u=100
sizeof(i)=8 sizeof(u)=4
</pre>
Using gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)

**Comment by jnotuo** [comment]
I comment the lines of the first kernel compress, using only compress(ZOPFLI,..)
This avoid the usage of ftruncate and the system installs and boot OK!!!

**Comment by chaosmaster** [comment]
I was able to reproduce the issue when running 32-bit magiskboot inside termux
64-bit magiskboot works fine.
32-bit also works fine when run via `adb shell`
It seems seccomp doesn't allow using ftruncate on 32-bit, but does on 64-bit.

**Comment by osm0sis** [comment]
Why not just switch all to lseek without ftruncate? Also @jnotuo reported ftruncate64 might work instead?

**Comment by chaosmaster** [comment]
Not sure, my [original PR](https://github.com/topjohnwu/Magisk/pull/4526/files) used lseek, @topjohnwu added the ftruncate during a rewrite.
I created a [new PR](https://github.com/topjohnwu/Magisk/pull/4915) that skips the ftruncate on ARM.
ftruncate64 is not available on arm32.

**Comment by chaosmaster** [comment]
@jnotuo can you test this?
https://github.com/topjohnwu/Magisk/actions/runs/1441550694

**Comment by jnotuo** [comment]
One alternative is compress into temporary file and if the size is ok, memcpy to the destination image.

**Comment by jnotuo** [comment]
The test is OK.
https://github.com/topjohnwu/Magisk/actions/runs/1441550694

**Comment by osm0sis** [comment]
Make sure this one works too: https://github.com/topjohnwu/Magisk/actions/runs/1443839962

**Comment by jnotuo** [comment]
It works !!!

**Comment by osm0sis** [comment]
Alright then, next Canary will officially work!
