### ISSUE TITLE
magisk su(tsu) termux bug

### ISSUE THREAD

**Issue by kevin01523** [topjohnwu/Magisk#3704]
![Screenshot_20210116-014433](https://user-images.githubusercontent.com/8380242/104760942-13e21e00-579d-11eb-837c-3778b72c8d11.jpg)
magisk canary update 
20102-20103 breaks termux tsu command
https://github.com/cswl/tsu

**Comment by topjohnwu** [comment]
There is nothing related to `su` changed from 20102 to 20103, please contact the `tsu` developer for this

**Comment by kevin01523** [comment]
hmm this also affects ktweak
![Screenshot_20210116-200041](https://user-images.githubusercontent.com/8380242/104811319-8f8fa980-5835-11eb-9844-7ebe7e8b4948.jpg)

notnot maybe its related to bash or maybe path

**Comment by lugdunum-1964** [comment]
For some reason the handling of the -c option has changed, which causes this. 
su -c 'echo 1 2 3' should run 'echo' as command and 1 2 3 as parameters. In stead it tries to run 'echo 1 2 3' as command. This happened 2 magisk updates ago.

As workaround run su -c sh -c 'echo 1 2 3'
