### ISSUE TITLE
boot hanging after upgrade to 21.2 on xiaomi MI 9 (cepheus)

### ISSUE THREAD

**Issue by NANASHI0X74** [topjohnwu/Magisk#3705]
Hey, tried upgrading to magisk 21.2 the day before yesterday, after which I haven't been able to boot-
I get to the bootanimation (which displays some unusual colorbanding and flashing in the background), but it never finishes.
I've then tried various things short of clean flashing my rom/wiping data- uninstalling and reinstalling either magisk 20.4 or 21.2, dirty flashing rom, flashing firmware/vendor package and then flashing rom. I'm really keen on recovering my device without losing data at the moment 😅
I'm attaching two boot logs-

this one is after flashing https://netactuate.dl.sourceforge.net/project/xiaomi-vendor-updater-project/cepheus_eea_global-stable/fw-vendor_cepheus_miui_CEPHEUSEEAGlobal_V12.0.1.0.QFAEUXM_4d28c84f58_10.0.zip, then flashing https://sourceforge.net/projects/derpfest/files/cepheus/DerpFest-10-Official-cepheus-20200912.zip/download, which was also previously installed (android 10)
[boot.log](https://github.com/topjohnwu/Magisk/files/5822334/boot.log)

this one is after installing magisk 20.4 which was installed the last time my device booted
[boot2.log](https://github.com/topjohnwu/Magisk/files/5822335/boot2.log)

here's a little more information about the device:
https://github.com/DerpFest-Devices/device_xiaomi_cepheus-dev

Any insight what's the problem?

**Comment by topjohnwu** [comment]
Only report issues on canary releases

**Comment by NANASHI0X74** [comment]
how can I flash the canary zip/ where can I download it?
