### ISSUE TITLE
Canary build shows Tapjacking Protection info although disabled

### ISSUE THREAD

**Issue by bege10** [topjohnwu/Magisk#3708]
After installing the Canary build for this https://github.com/topjohnwu/Magisk/issues/3681 bug report Magisk shows the Tapjacking Protection info although this feature is disabled. Nevertheless root access is granted.

All phone details, logs and files please see at the linked bug.
Issue continues with Canary build 04c53c35 (21203).

**Comment by vvb2060** [comment]
Always show toast to let you know that superuser are allowed in suspicious situations.
