### ISSUE TITLE
[Feature request] Exceptions for Tapjacking Protection

### ISSUE THREAD

**Issue by bege10** [topjohnwu/Magisk#3709]
I use Everywhere Launcher com.appindustry.everywherlauncher which allows to show floating launch handles all the time. This, of course, triggers Tapjacking Protection. I'd like to enable Tapjacking Protection but exclude this app. Could you add the feature to add exceptions to the Tapjacking Protection, please?

**Comment by GHolk** [comment]
I use Paper Launcher, and I face the same problem.

**Comment by vvb2060** [comment]
No exceptions. You can disable Tapjacking Protection, or allow it in Magisk Manager after deny.

**Comment by topjohnwu** [comment]
Disable it in settings
