### ISSUE TITLE
Sudo not working anymore in v21.3

### ISSUE THREAD

**Issue by woheller69** [topjohnwu/Magisk#3711]
with the latest version I get that the command is "inaccessible or not found" e.g. when performing
sudo logcat -d -f /sdcard/logcat.txt in Termux

With v21.2 it was working

**Comment by emptyteeth** [comment]
```shell
su net_admin -c "nohup COMMAND >/dev/null 2>&1 &"
```
this also stop working,  got "inaccessible or not found" error.   
have to remove the double quotes to make it working again, with slightly different behaviour.

**Comment by woheller69** [comment]
I restored previous version of Magisk and everything works fine again

**Comment by topjohnwu** [comment]
It shall be fixed in the latest canary release
