### ISSUE TITLE
Moto G7 Power does not power on with v 21.3

### ISSUE THREAD

**Issue by Irihapeti** [topjohnwu/Magisk#3713]
After installing v21.3, the phone would not power on. The screen remained black after requesting a reboot, and the power button was completely unresponsive. (Therefore, I can't provide any logs, unfortunately.)

Nothing unexpected had happened during the install.

I was able to reinstall v21.2 after loading TWRP from fastboot. No problems with this version (or with any previous version, for that matter).

G7 Power Details in Magisk Manager:
  Ramdisk: Yes
  A/B: Yes
  SAR: Yes
  Crypto:  File

  (architecture: aarch64)

No problems with my Moto G4 Play.
  Ramdisk: Yes
  A/B: No
  SAR: Yes
  Crypto: N/A

  (architecture: armv7l)

**Comment by Haus3master** [comment]
Try reflashing your device firmware, as, it seems to be bricked by your description, and then try again, also, does it work with previous versions of Magisk?

**Comment by Irihapeti** [comment]
Thanks. v21.4 is working properly.
