### ISSUE TITLE
Can't turn on Wi-Fi after updating to latest Magisk on Redmi 7

### ISSUE THREAD

**Issue by DontNoticeMeh** [topjohnwu/Magisk#3715]
My device is Redmi 7 with Paranoid Android 10. When i first booted with magisk 21.3 for some reason the booting time is longer than before, but at least it booted up to android. When i enable wifi from quick settings it just says "turning on", so i go to settings to enable it. When i enable the wifi from settings it just turn off wifi it self. Any solution?. I can provide catlog if needed

**Comment by Manaplayer** [comment]
Same problem on Xiaomi Mi10 too. And with enabling mobile data too.

**Comment by rxk-code** [comment]
Hi,Is your wifi problem solve? What Magisk version did you install?-- Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 21/1/21, 00:02 Manaplayer <notifications@github.com> wrote:

   
  Same problem on Xiaomi Mi10 too. And with enabling mobile data too.

**Comment by Manaplayer** [comment]
Seems to be a big problem with Android 11 on a lot of devices - I have tested down to 20.4 and it is the same issue.

**Comment by rxk-code** [comment]
https://youtu.be/fUHOeMJItNITry this method, i am not sure if the wifi is ok.I will try to ask the poster of this video and let you know later.If magisk rooting has problem on android 11, I just preorder galaxy s21 ultra, need to wait for a fix then.--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 22/1/21, 3:14 am Manaplayer <notifications@github.com> wrote:

   
  Seems to be a big problem with Android 11 on a lot of devices - I have tested down to 20.4 and it is the same issue.

**Comment by rxk-code** [comment]
The youtube poster replied and he confirmed that wifi and data is working fine after rooting android 11.--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 22/1/21, 3:14 am Manaplayer <notifications@github.com> wrote:

   
  Seems to be a big problem with Android 11 on a lot of devices - I have tested down to 20.4 and it is the same issue.

**Comment by DontNoticeMeh** [comment]
> Hi,Is your wifi problem solve? What Magisk version did you install?-- Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 21/1/21, 00:02 Manaplayer <notifications@github.com> wrote: Same problem on Xiaomi Mi10 too. And with enabling mobile data too. —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

Hello, sorry for not replying for days. I installed magisk version 21.3 on Android 10, the wifi still isn't fixed yet so i switched to another rom and installed magisk 21.1, after a week or more I can't use my data so i updated to version 21.4 . After updating I can't seem to turn on my wifi again, i also tried using that gsi fix magisk module, that fixed my data problem (but slow speed) but still i can't turn on my wifi, so i tried flashing a custom kernel and it fixed my slow data but still can't turn on wifi. I may do a clean flash of my rom or reinstall magisk today

**Comment by DontNoticeMeh** [comment]
Update: turns out my data is still slow

**Comment by DontNoticeMeh** [comment]
Update after clean flash: Installed magisk 21.1, everything works normally now

**Comment by rxk-code** [comment]
So sad to hear that the problem wasn't fixed yet. I received my new galaxy s21 ultra 2 weeks ago, still waiting for someone successfully root their phone trying mine.--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 4/2/21, 6:29 pm DontNoticeMeh <notifications@github.com> wrote:

   
   
   Hi,Is your wifi problem solve? What Magisk version did you install?-- Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 21/1/21, 00:02 Manaplayer notifications@github.com wrote: Same problem on Xiaomi Mi10 too. And with enabling mobile data too. —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. 
   
  Hello, sorry for not replying for days. I installed magisk version 21.3 on Android 10, the wifi still isn't fixed yet so i switched to another rom and installed magisk 21.1, after a week or more I can't use my data so i updated to version 21.4 . After updating I can't seem to turn on my wifi again, i also tried using that gsi fix magisk module, that fixed my data problem (but slow speed) but still i can't turn on my wifi, so i tried flashing a custom kernel and it fixed my slow data but still can't turn on wifi. I may do a clean flash of my rom or reinstall magisk today

**Comment by rxk-code** [comment]
Are running on android 10 or 11?--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 4/2/21, 6:58 pm DontNoticeMeh <notifications@github.com> wrote:

   
  Update after clean flash: Installed magisk 21.1, everything works normally now

**Comment by DontNoticeMeh** [comment]
> Are running on android 10 or 11?--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 4/2/21, 6:58 pm DontNoticeMeh <notifications@github.com> wrote: Update after clean flash: Installed magisk 21.1, everything works normally now —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

I currently use an Android 10 rom on my phone right now

**Comment by dhukia45** [comment]
Same problem redmi note 7pro
Rom Google pixal experience

**Comment by liukepeng** [comment]
same problem oneplus 7T, any solutions?

**Comment by pojavluncher2021** [comment]
May be a problem where Magisk reset the network settings or WiFi App is no
longer working due to Magisk, No root should fix the issue, I guess use One
Click Root

**Comment by VytskaLT** [comment]
I've got the same issue. For a while, Magisk worked perfectly, but then suddenly booting up takes much longer, when I unlock my phone it says "System UI isn't responding", can't turn on wifi or mobile data (says no sim card detected) and in a few minutes the whole phone crashes and turns on "Qualcomm Crashdump Mode". I remember disabling MagiskHide at about the time this started happening.

I tried:
- Reinstalling Magisk with the flash zip and the patch image techniques
- Reinstalling LineageOS (without factory resetting)
- Enabling and disabling MagiskHide

The issues are completely gone when I uninstall Magisk.
I'm on OnePlus 8, the latest LineageOS, and Magisk 23.
I can give you logs if I get instructions on how to get them.

**Comment by DiegoArmando-27** [comment]
same issue
redmi note 8t pixel experience android 10

**Comment by piegamesde** [comment]
@topjohnwu why was this closed?

**Comment by errno0x82** [comment]
https://github.com/topjohnwu/Magisk/issues/7389
