### ISSUE TITLE
magisk 21.3 can't root sony xperia 1 II Android 11

### ISSUE THREAD

**Issue by ShionKagurazaka** [topjohnwu/Magisk#3716]
Just can't boot into system ;(
I don't know the reason :( 
I try to flash it in TWRP and I try to flash it in fastbotd:(
It doesn't work :(

**Comment by Haus3master** [comment]
Did you try flashing the boot image to both slots A/B, I think your device is partitioned as as A/B SAR....

**Comment by ShionKagurazaka** [comment]
> Did you try flashing the boot image to both slots A/B, I think your device is partitioned as as A/B SAR....

I use your way. try to flash both A/B ,but it doesn't work.
