### ISSUE TITLE
Magiskhide does not work

### ISSUE THREAD

**Issue by Maxym4uk** [topjohnwu/Magisk#3717]
When I upgraded magisk to 21.3 stable verison, It worked on other previous versions, magiskhide stopped working.  Because of this, the safety check does not pass.  Samsung s8 phone.  Lineage os firmware 17.1

**Comment by Haus3master** [comment]
Please provide additional information like, if you are on stable or canary, if previous versions worked, etc, so that it fulfills the bug report requirements....

**Comment by Maxym4uk** [comment]
`
[magisk_log_2021-01-17T09:54:22Z.log](https://github.com/topjohnwu/Magisk/files/5825709/magisk_log_2021-01-17T09.54.22Z.log)
`

**Comment by Maxym4uk** [comment]
![Screenshot_20210117-095600_Magisk_Manager](https://user-images.githubusercontent.com/68429567/104834759-39108280-58aa-11eb-8c5e-f63bf7f38fd6.png)

**Comment by topjohnwu** [comment]
Already fixed in canary version...

**Comment by Maxym4uk** [comment]
> Вже виправлено в канарській версії ...

and when will it be in the stable version?

**Comment by Haus3master** [comment]
It will take a bit of time, till then, if you want to, join canary, I myself have joined it yesterday, and also, you are required to be on canary to report bugs...
