### ISSUE TITLE
"Pretty" shortcut cannot be opened

### ISSUE THREAD

**Issue by jbro129** [topjohnwu/Magisk#3718]
My device: Samsung Galaxy Note 9 SM-N960F/DS on 10.0
I am using the Magisk canary builds
Magisk: 21392
Manager: 4829

For the past few Manager updates the shortcuts its generated have not been launchable. Upon clicking the shortcut a toast message says "App isn't installed". Previously the shortcuts would only not work upon a Manager app update, but would work when a new shortcut was created using that updated Manager. 
I do not remember the exact build # of the Magisk Manager canary build where this first started happening.

I'm also using Nova Launcher as my launcher. I do not know if that could be related to this issue as the shortcuts used to work regardless of me using it and now they don't.

I have attached a screen recording of what this looks like.
https://user-images.githubusercontent.com/15088428/104833671-62a8ba00-5868-11eb-995c-158cb00abf3d.mp4

**Comment by jbro129** [comment]
I can attach a logcat filtered by the manager package name and the term "Magisk" or "Manag3r" as that's what I named the Manager if it'll help isolate what's causing this.

**Comment by Haus3master** [comment]
It should work, because the pretty icon is just an alias to open the hidden manager...

**Comment by jbro129** [comment]
> It should work, because the pretty icon is just an alias to open the hidden manager...

It should but for some reason it isn't. :/

**Comment by Haus3master** [comment]
When you add the pretty icon to the home screen, it will probably look like this, please confirm if it looks like this...
![Screenshot_20210117-125700_Trebuchet](https://user-images.githubusercontent.com/66825701/104834157-a2e95600-58c3-11eb-820d-bc8073b50f60.png)

**Comment by Haus3master** [comment]
Oh, NVM I saw the screen recording, and, please update your Magisk manager and Magisk itself, it might fix it(highly doubt it but just give it a try)...

**Comment by jbro129** [comment]
> When you add the pretty icon to the home screen, it will probably look like this, please confirm if it looks like this...
> ![Screenshot_20210117-125700_Trebuchet](https://user-images.githubusercontent.com/66825701/104834157-a2e95600-58c3-11eb-820d-bc8073b50f60.png)

It looks exactly like that. I attached a screen recording of the shortcut being created and me trying to open it in the first post.

**Comment by Haus3master** [comment]
Yes, I saw that, sorry, I didn't look at the screen recording initially....

**Comment by Haus3master** [comment]
Just update your Magisk, create an alias(pretty icon) and reboot your device, then see if it works....

**Comment by jbro129** [comment]
Sorry for the late reply. After updating Magisk Manager and Magisk to the newest canary builds my phone was stuck in a bootloop. I had to uninstall magisk then reinstall via patching my system.img then reinstalling all my modules. After all of that the shortcut was working. I dont know why this all happened but everything is working again now. Thank you for the help @Haus3master.

**Comment by jbro129** [comment]
For now I'll close this issue as it pretty much resolved. I'll reopen if the shortcut gives me issues again. Thank you again :)
