### ISSUE TITLE
Magisk 21.3 prevents booting on rooted Fire HD 10 (2017) on FireOS 5.6.8.0

### ISSUE THREAD

**Issue by smithbill17** [topjohnwu/Magisk#3719]
I have been running my Amazon Fire HD 10 (2017) on Amazon FireOS 5.6.8.0 rooted with TWRP 3.2.0 and Magisk v20.4.

On receiving the "Magisk update available" notification, I downloaded v21.3 zip, went into TWRP recovery, wiped Cache/dalvik, flashed Magisk v21.3, wiped Cache/dalvik and rebooted.

FireOS then gives the "Fire, optimising system storage and applications" screen which creeps along. On reaching the end (about 20mins) it becomes stuck. 60mins later it's still stuck.

If I force reboot, it remains stuck on the "Fire" screen. If I wipe caches & repeat, the same thing happens.

I can reboot into TWRP and reflash Magisk v20.4 and everything then works.

So there must be some issue with Magisk v21.3 that prevents Fire HD 10 (2017) on FireOS 5.6.8.0 from booting.

**Comment by jmozmoz** [comment]
I have the same problem with Moto G7+ (lake) using LineageOS 16. Both Magisk 21.2 and 21.3 causes this stall during boot. Downgrading via TWRP to Magisk 20.4 solves the problem.

**Comment by mosteo** [comment]
Likewise for a BQ X5+
