### ISSUE TITLE
Not sure how muscat bank app detect that my phone has root.. even when i am hiding it from root .. by just putting random username and password in that app u will see that the app says it cannot run in jailbrake or rooted phone

### ISSUE THREAD

**Issue by qtr1st** [topjohnwu/Magisk#3721]
## READ BEFORE OPENING ISSUES

All bug reports require you to **USE CANARY BUILDS**. Please include the version name and version code in the bug report.

If you experience a bootloop, attach a `dmesg` (kernel logs) when the device refuse to boot. This may very likely require a custom kernel on some devices as `last_kmsg` or `pstore ramoops` are usually not enabled by default. In addition, please also upload the result of `cat /proc/mounts` when your device is working correctly **WITHOUT ROOT**.

If you experience issues during installation, in recovery, upload the recovery logs, or in Magisk Manager, upload the install logs. Please also upload the `boot.img` or `recovery.img` that you are using for patching.

If you experience a crash of Magisk Manager, dump the full `logcat` **when the crash happens**. **DO NOT** upload `magisk.log`.

If you experience other issues related to Magisk, upload `magisk.log`, and preferably also include a boot `logcat` (start dumping `logcat` when the device boots up)

**DO NOT** open issues regarding root detection.

**DO NOT** ask for instructions.

**DO NOT** report issues if you have any modules installed.

Without following the rules above, your issue will be closed without explanation.

**Comment by Haus3master** [comment]
Please do not ask for help with such things, we can't do anything and you broke rules regarding root detection, please read the rules, they will show up when you try to open an issue, reports like this will be closed without explanation....

**Comment by wait-what** [comment]
Did you even read your own post? You yourself said "DO NOT open issues regarding root detection."

Despite that, you should check if SafetyNet is intact. Magisk manager has a button for it on the home screen.

**Comment by qtr1st** [comment]
Are u topjohn?
I have done all 
Magisk hide 
Hide magisk manager 
Hide app as well 
Checked safetynet and it passed

its somehow like a challange this app 
If u can make it work

**Comment by qtr1st** [comment]
By the way i have seen the rules .. but just wanted to say that hide doesnt work properly or maybe this app engineered to find root

**Comment by qtr1st** [comment]
Thnx for trying
