### ISSUE TITLE
Still hide in 21.4 doesnt work properly🤣 ... think even if u change it to 21.99999 it will not work properly

### ISSUE THREAD

**Issue by qtr1st** [topjohnwu/Magisk#3723]
## READ BEFORE OPENING ISSUES

All bug reports require you to **USE CANARY BUILDS**. Please include the version name and version code in the bug report.

If you experience a bootloop, attach a `dmesg` (kernel logs) when the device refuse to boot. This may very likely require a custom kernel on some devices as `last_kmsg` or `pstore ramoops` are usually not enabled by default. In addition, please also upload the result of `cat /proc/mounts` when your device is working correctly **WITHOUT ROOT**.

If you experience issues during installation, in recovery, upload the recovery logs, or in Magisk Manager, upload the install logs. Please also upload the `boot.img` or `recovery.img` that you are using for patching.

If you experience a crash of Magisk Manager, dump the full `logcat` **when the crash happens**. **DO NOT** upload `magisk.log`.

If you experience other issues related to Magisk, upload `magisk.log`, and preferably also include a boot `logcat` (start dumping `logcat` when the device boots up)

**DO NOT** open issues regarding root detection.

**DO NOT** ask for instructions.

**DO NOT** report issues if you have any modules installed.

Without following the rules above, your issue will be closed without explanation.

**Comment by Haus3master** [comment]
It is fixed, not sure why it's happening for you, try disabling and re-enabling Magisk hide...

**Comment by qtr1st** [comment]
I did still didnt work

**Comment by qtr1st** [comment]
I also forced stopped the app .. deleted twrp folder deleted magisk from download folder .. still didnt work

**Comment by Haus3master** [comment]
Oh... I'm not sure why that's happening, but, have you tried to join canary, I'm on canary, this issue was fixed a few hours ago.... Try Magisk canary, Magisk hide works flawlessly...

**Comment by qtr1st** [comment]
I am on magisk canary brother

**Comment by qtr1st** [comment]
I tried both stable and canary

**Comment by Haus3master** [comment]
Actually, could you elaborate on how is broken, for example, the apps seem to be unchecked, it some apps that never detected root started to detect root, etc....

**Comment by qtr1st** [comment]
Yeah that app after recent update to it started to detect root (muscat bank app) as i said earlier try random user and password .. u will see app message that root detected ... same is with pubg but i dont care about pubg .. i was using muscat bank app but stopped recently becuase of root detection

**Comment by Haus3master** [comment]
Actually, it's not the fault of Magisk hide, the Muscat app started to detect root by looking for root binaries after the update, also, hiding root binaries is a complex task...
Just to verify, all of us are having the same issue with Muscat(yes, I use it too) your only option for now is to use a device with stock rom, I guess...

**Comment by Haus3master** [comment]
Revolt, for example started detecting root even if Magisk hide is enabled after a recent update.... I'm using an old version of the revolut app that doesn't have the new detection method....

**Comment by qtr1st** [comment]
Thanks for ur honesty .. i wish u can work something out to make this app work and i am ready to donate i will also ask my friends too to donate with me

**Comment by Haus3master** [comment]
Sadly, I'm just a newbie, i started using Magisk about a month ago, so, I can't be of much help, sorry :(

**Comment by qtr1st** [comment]
Heheheh its ok brother.. anyhow wish our voice reach to topjohn to help fixing the issue and as i said we are ready to donate

**Comment by Haus3master** [comment]
The problem here is that everytime he fixes anything, app developers try to find out on how to detect root, it's like a cat and mouse game, we don't know what will happen, for example Google rolled out hardware attestation making devices harder to pass safetynet if they are rooted.... (It gets a bit tiring for him to keep up)...

**Comment by qtr1st** [comment]
Ofcourse we all know about this.. but as an encouragement we can donate to make him work harder to find different way me and my friends

**Comment by Haus3master** [comment]
Yeah, true...

**Comment by Haus3master** [comment]
Well, since we have reached the conclusion of this issue, could you please close this issue...

**Comment by qtr1st** [comment]
Lets wait for topjohn if he agree .. so i can donate partialy then wait for the final update to donate more

**Comment by Haus3master** [comment]
Okay...

**Comment by GiantWaffle** [comment]
21.4 update still crashes me on boot just like 21.2 & 21.3 -- Restore to 20.4 and it works again.

The first post says you have to be running Canary.  There is no choice for that.  The Channel choices are Stable, Beta & Custom.  What am I supposed to do?

LG (H910A) V20 Running Nougat 7.0

**Comment by Haus3master** [comment]
Go to the readme and download the magisk manager canary from there....

**Comment by Haus3master** [comment]
![Screenshot_20210117-230510](https://user-images.githubusercontent.com/66825701/104851053-8e837880-5918-11eb-9872-f46ca6e04b44.png)

**Comment by qtr1st** [comment]
Would suggest some root path files to have differnet names and paths to be difficult to detect by apps .. i believe keeping magisk name inside the same data/adb folder would be easily detected
