### ISSUE TITLE
blockdev: /dev/block/mmcblk0p33: Permission denied

### ISSUE THREAD

**Issue by zhihuiyuze** [topjohnwu/Magisk#3724]
Hello, I don’t know if this is a mistake. My phone can be rooted normally, and this log will only be displayed in the magisk log without causing module exceptions. However, magisk cannot be updated.

Redmi9 MIUI11.0.9
`- Target image: /dev/block/mmcblk0p33
- Device platform: arm64-v8a
- Magisk Manager: 8.0.7 (4834)
- Install target: 21.4 (21400)
2026+0 records in
2026+0 records out
2074624 bytes (2.0MB) copied, 0.010013 seconds, 197.6MB/s
1381+1 records in
1381+1 records out
1415016 bytes (1.3MB) copied, 0.007782 seconds, 173.4MB/s
- Unpacking boot image
Parsing boot image: [/dev/block/mmcblk0p33]
HEADER_VER      [2]
KERNEL_SZ       [9671927]
RAMDISK_SZ      [1083679]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [108943]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-11]
PAGESIZE        [2048]
NAME            []
CMDLINE         [bootopt=64S3,32N2,64N2 buildvariant=user]
CHECKSUM        [5d9841b2b729dd7ce8c041b84a44e44f7743e0b2000000000000000000000000]
KERNEL_DTB      [108879]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
Loading cpio: [ramdisk.cpio]
Remove [.backup]
Remove [.backup/.magisk]
Move [.backup/init] -> [init]
Dump cpio: [ramdisk.cpio]
- Magisk patched boot image detected
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [dtb]
Loading dtbs from [kernel_dtb]
- Repacking boot image
Parsing boot image: [/dev/block/mmcblk0p33]
HEADER_VER      [2]
KERNEL_SZ       [9671927]
RAMDISK_SZ      [1083679]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [108943]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-11]
PAGESIZE        [2048]
NAME            []
CMDLINE         [bootopt=64S3,32N2,64N2 buildvariant=user]
CHECKSUM        [5d9841b2b729dd7ce8c041b84a44e44f7743e0b2000000000000000000000000]
KERNEL_DTB      [108879]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
Repack to boot image: [new-boot.img]
HEADER_VER      [2]
KERNEL_SZ       [9671927]
RAMDISK_SZ      [1088496]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [108943]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-11]
PAGESIZE        [2048]
NAME            []
CMDLINE         [bootopt=64S3,32N2,64N2 buildvariant=user]
CHECKSUM        [909cbf9106e5e7ca955088ba50e2bdcba365b8db000000000000000000000000]
- Flashing new boot image
blockdev: /dev/block/mmcblk0p33: Permission denied
! Installation failed
! /dev/block/mmcblk0p33 is read only`

[
[magisk_log_2021-01-18T00:43:49Z.log](https://github.com/topjohnwu/Magisk/files/5826454/magisk_log_2021-01-18T00.43.49Z.log)

**Comment by Haus3master** [comment]
Does your phone use a Mediatek processor? If your device uses a mtk processor, then you can't update magisk via the manager because Mediatek made some changes in the kernel to prevent critical partitions from being modified when the system is booted, your only option is to either update magisk from a custom recovery or, to patch and flash a boot image from bootloader everytime you want to update...

**Comment by topjohnwu** [comment]
Exactly the reason stated above.

**Comment by zhihuiyuze** [comment]
I find it very strange why it was possible to update through magisk before but not now. Is it because MediaTek submitted the code to Android?

**Comment by faketask93** [comment]
Is there any way to edit these partitions in mtk devices . I don't have any custom recovery working fr my device I have tried every single. My device is Lenovo tab m8 fhd (8705f). Thanks in advance: )
