### ISSUE TITLE
Parallel installations

### ISSUE THREAD

**Issue by FatalBulletHit** [topjohnwu/Magisk#3726]
I accidentally started 2 parallel installations at the same time when I tried to update Magisk today.
The first installation was successful, the second one failed. Rebooting caused a boot loop.

Step to reproduce:
1. Double click "LET'S GO" (_I assume that's what caused it_)

To prevent this from accidentally happening, I suggest to verify that no installation is running before starting an installation.

**Comment by vvb2060** [comment]
#3915
