### ISSUE TITLE
Magisk v21.4 wipes boot-appended vbmeta, unbootable on Unihertz Titan (and other Mediatek devices with Android 10)

### ISSUE THREAD

**Issue by ValdikSS** [topjohnwu/Magisk#3727]
Unihertz Titan does not have dedicated vbmeta partition, Android 10 image on this device has vbmeta appended to boot.img, which is padded to partition size.

Magisk Manager 8.0.7 (4832), upon Magisk 21.4 (21400) installation, wipes vbmeta header and footer from boot.img on this device, making it unbootable.
Magisk Manager does not offer to preserve dm-verity on this device, and the log file does not contain any strings regarding AVB (as it was with Android 9 on this device).

Adding blank vbmeta with disabled verification manually into the patched image allows device to boot again.

Please check the following archive with three files:
* boot_10.img — original boot.img from the firmware
* magisk_patched.img ­— the file patched by Magisk Manager
* magisk_patched_noavb_manual.img — patched file with manually added vbmeta data and footer.

**https://files.catbox.moe/9cp3eo.zip**

Log file of direct (re)installation on top of already patched image. The resulting image came without vbmeta, rendering device unbootable.
[magisk_install_log_2021-01-17T22:37:05Z.log](https://github.com/topjohnwu/Magisk/files/5826759/magisk_install_log_2021-01-17T22.37.05Z.log)

**Comment by nift4** [comment]
This affects other MediaTek devices like the Gigaset GS290 and the Volla Phone too

**Comment by nakomaru** [comment]
Possibly related: 21.4 fails to install on Honor 9 STF-L09 on C635 firmware using TWRP 3.2.1 (after about two years of using Magisk on this setup). Instead, it seems to brick TWRP which causes an automatic factory restore, losing both root and TWRP.

**Comment by osm0sis** [comment]
Any improvement on latest Canary?

**Comment by ChrisPHL** [comment]
+1
This seems to have severe impact. :-/ My GS290 does not boot after patching with the Magisk versions seen in the starting post.

**Comment by nift4** [comment]
Canary works fine here

**Comment by ChrisPHL** [comment]
Oh, I'm not familiar with "canray" what exactly does that mean? Where can I download the canary version of Magisk? Does "canary" mean something like "latest"?

**Comment by ValdikSS** [comment]
commit 027ec7026252bf1615c19205855ae58a79f1225e fixes the issue, canary build works fine.

**Comment by nift4** [comment]
@ChrisPHL it is the development version of Magisk
