### ISSUE TITLE
No file selection dialog in in Manager when patching boot.img

### ISSUE THREAD

**Issue by dragonnn** [topjohnwu/Magisk#3728]
Latest Magisk Manager 8.0.7 (4834).
When I choose the radio button "Select and Path a File" I only get the toast but not file dialog launches.
Phone is running Android 9, it is an Oukitel WP6.
I have File Manager installed on my phone, tried already Total Commander, MK Explorer but I think it also has the default Android File Selection App.
I wanted to try an older version of Manager, before 8.0.7 but every time I try to launch it forces me to first download the new version.
Any help with that?
I can provide logcat-s but I am not sure how to filter them to only relevant parts.
That is really frustrating to get stuck on such issue, hope I can get help some help.
Thanks!

**Comment by topjohnwu** [comment]
Just get the full logcat dump

**Comment by dragonnn** [comment]
[logcat.txt](https://github.com/topjohnwu/Magisk/files/5828382/logcat.txt)
Sure :). I see that sometimes when I select "Select and Path a File" something flashes over Magisk Manager for a brew sec, but hard to tell what app that is.

**Comment by topjohnwu** [comment]
Can't see anything special in the logs. We are using the standard Android APIs to request a file, if something is wrong, there is serious issue with your system.

**Comment by dragonnn** [comment]
Thanks for taking a look. I didn't notice problems in other applications but maybe the manufacture screw up something in his build of Android, wouldn't surprises me if this is the case. I will probably try to flash AOSP, I have saw some unofficial builds for my phone.
