### ISSUE TITLE
Update to 21.4 caused  bootloop

### ISSUE THREAD

**Issue by EduApps-CDG** [topjohnwu/Magisk#3729]
i have just updated from 21.2 to 21.4 and this happened.

Please help me!

[kernel-log.txt](https://github.com/topjohnwu/Magisk/files/5827045/kernel-log.txt)
[magisk-log.txt](https://github.com/topjohnwu/Magisk/files/5827046/magisk-log.txt)
[mounts.txt](https://github.com/topjohnwu/Magisk/files/5827047/mounts.txt)

**Comment by EduApps-CDG** [comment]
im ready to provide aditional info

**Comment by EduApps-CDG** [comment]
I flashed magisk uninstaller, and installed 21.2 again. please tell me when i can update magisk again

**Comment by thebackgroundeffect101** [comment]
Completely uninstall Magisk. (Flash uninstaller zip in recovery if necessary) Reboot. Install Magisk Manager v8.0.7. Download v21.4. Flash it in Recovery. Reboot to system. That worked for me.

**Comment by EduApps-CDG** [comment]
im going to try, but its almost 01:00 AM here, so ill do it tomorrow.

But i think it will work, i made the same thing for downgrading

**Comment by ZerOri** [comment]
me too~

**Comment by dix93** [comment]
Yep, same here. I uninstalled Magisk from twrp but wan't able to boot.

I also tried:
- to flash the boot.img of my rom
- to install the 21.2 version of magisik

Non of this worked. :(

**Comment by ZerOri** [comment]
> Yep, same here. I uninstalled Magisk from twrp but wan't able to boot.
> 
> I also tried:
> 
> * to flash the boot.img of my rom
> * to install the 21.2 version of magisik
> 
> None of this worked :( Please help

Me too,I'm Xiaomi mi9,MIUI12,what's your phone?

**Comment by dix93** [comment]
> > Yep, same here. I uninstalled Magisk from twrp but wan't able to boot.
> > I also tried:
> > 
> > * to flash the boot.img of my rom
> > * to install the 21.2 version of magisik
> > 
> > None of this worked :( Please help
> 
> Me too,I'm Xiaomi mi9,MIUI12,what's your phone?

Running Lineage OS for Davinci (Xiaomi Mi9T)

**Comment by ZerOri** [comment]
> > > Yep, same here. I uninstalled Magisk from twrp but wan't able to boot.
> > > I also tried:
> > > 
> > > * to flash the boot.img of my rom
> > > * to install the 21.2 version of magisik
> > > 
> > > None of this worked :( Please help
> > 
> > 
> > Me too,I'm Xiaomi mi9,MIUI12,what's your phone?
> 
> Running Lineage OS for Davinci (Xiaomi Mi9T)

I see,so this is not MIUI's problem,😀

**Comment by xDonatello** [comment]
On Mi 9 Lite many people have had the same problem.
The phone restarts in fastboot, without the possibility to open the TWRP recovery.
Someone solved it by uninstalling Magisk via ADB

**Comment by dix93** [comment]
No way to solve it by uninstalling. But I can enter in TWRP

**Comment by topjohnwu** [comment]
It's an issue with edxposed, not Magisk

**Comment by dix93** [comment]
I have not exposed installed, but I still have the issue. 

Just to stay updated, I also tried to format the system, and install the v21.2 of Magisk.
It seemed to work, but after the first reboot the boot loop happened again. Flashing the boot.img of the Rom just help to see the splash screen of Lineage OS, but after few second it comes back in boot loop.

I don't know what is the problem, but to solve it I'm going to format again and not using Magisk at all.

**Comment by EduApps-CDG** [comment]
for me its working fully fine only up to 21.2

**Comment by xDonatello** [comment]
My users also don't have Xposed, yet they went into softbrick 😕

**Comment by Didgeridoohan** [comment]
@EduApps-CDG Did you try on v21.4 without EdXposed?

**Comment by metafaniel** [comment]
Same problem here. Updated to the latest version _without_ Xposed module installed and _without_ Magisk hidden but I still got a bootloop.
How to proceed now? I'm using a Huawei Y5 MYA-L13.
