### ISSUE TITLE
magisk 21.4 errors

### ISSUE THREAD

**Issue by m8ax** [topjohnwu/Magisk#3730]
i found one error in 21.4, all apps root works fine except es file explorer , no work root in this app.

**Comment by EduApps-CDG** [comment]
i think it's mostly like an error in ES File Explorer

**Comment by m8ax** [comment]
> i think it's mostly like an error in ES File Explorer.
> Or you should check if this app is blocked on Magisk

in 21.3 mostly apps not run root well, in 21.4 all roots apps run ok except es file explorer, i checked on in magisk its not blocked. with 21.2 all apps root run ok include es file explorer..

**Comment by NKS31** [comment]
Same error faced my me. Es file explorer's root explorer feature doesn't works in magisk 21.4. please fix this.
