### ISSUE TITLE
Magisk su stopped interpreting the -c option correctly

### ISSUE THREAD

**Issue by lugdunum-1964** [topjohnwu/Magisk#3733]
Please review the (closed) magisk su(tsu) termux bug #3704

It's not tsu. If I use /bin/su directly there's the same issue. The argument to the -c option doensn't get split into command and arguments but gets passed to exec as one string.

Up until the last update this worked:
/bin/su -c 'echo 1 > bla'

now i get 
/bin/sh: echo 1 > bla: inaccessible or not found

Workaround is 
/bin/su -c sh -c 'echo 1 >bla'

**Comment by topjohnwu** [comment]
What version are you on? Magisk v21.4 should fix this issue

**Comment by lugdunum-1964** [comment]
I was on 21.3, just got the upgrade notification. And 21.4 fixes it indeed. Thanks for the quick reply and fix.!!!
