### ISSUE TITLE
socket pipe issue still persists in v21.4 

### ISSUE THREAD

**Issue by akramraza2** [topjohnwu/Magisk#3734]
after v20.4 , sockets made on unix domain are unable to bind because the selinux mode is set to Enforcing. Updating to v21.2 had the issue . After updating to v21.4 this issue has been resolved for android version below 10 , but still persists for versions above 10.
Tested on two seperate devices , Motorola G5 plus( android 8) and One Plus 7T (android 10).
Also , sockets can be bound by setting the mode to Permissive at runtime using setenforce 0 , but this is not allowed in samsung devices with stock kernel.

**Comment by topjohnwu** [comment]
Duplicate: #3697, quote:

> It is explicitly designed to do that because it is a security issue when non root apps can connect to a root process. If you need communication, you should do it the other way: open a socket on the non-root process, and have to root process connect to it
