### ISSUE TITLE
Magisk Wrong sepolicy.rule Directory Installation

### ISSUE THREAD

**Issue by reiryuki** [topjohnwu/Magisk#3735]
Magisk app since 8.0.7 (4834) until now and Magisk zip v21.4 until the latest sepolicy.rule bug

If I toggling disable/enable any module or remove/restore, or installing a module with Magisk app, sepolicy.rule files are installing to /cache/magisk but the sepolicy.rules folder is linked to /sbin/.magisk/mirror/persist/magisk. It doesn't syncronized. I have to move the /cache/magisk folder to /sbin/.magisk/mirror/persist/ manually because of it.

$RULESDIR detecting sepolicy.rule directory is /cache/magisk, but actually is /mnt/vendor/persist/magisk or /sbin/.magisk/mirror/persist/magisk for my device (R4A)

I modify util_functions.sh, moving the "Remove all existing rule folders (rm -rf ...)" to the after $RULESDIR detection. It's fixing for module installation but app toggler still bug. I think it's no longer using utilfunctions.sh for those toggler.

Looks like the $active_dir is not detected after rm -rf. Placing the rm -rf before detecting link is a faulty. The "Remove all existing rule folders (rm -rf ...)" should be placed after detecting $RULESDIR, not before it, so the $active_dir can be detected correctly..

Thank you

![Screenshot_20210118-160646612](https://user-images.githubusercontent.com/46316533/104896161-58420980-59a9-11eb-88ad-02cd2645bf46.jpg)

![Screenshot_20210118-160653636](https://user-images.githubusercontent.com/46316533/104896186-642dcb80-59a9-11eb-9094-a4a77173a18c.jpg)
[logcat_01-18-2021_16-07-15.txt](https://github.com/topjohnwu/Magisk/files/5829135/logcat_01-18-2021_16-07-15.txt)

![Screenshot_20210119-114412178](https://user-images.githubusercontent.com/46316533/104989058-2df55800-5a4c-11eb-8e56-5cd5ff798b7e.jpg)

**Comment by osm0sis** [comment]
Similar to this I had noticed recently that sepolicy.rule files are somehow being copied to both /metadata/magisk and /mnt/vendor/persist/magisk on my OP8T. The way the copy_sepolicy_rules function reads there should only be one location. :thinking_face:

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/commit/0783f3d5b6d46d0a0ed8897de4c8027838af1688 I think it's fixed now.

**Comment by osm0sis** [comment]
@reiryuki, can you confirm?

**Comment by reiryuki** [comment]
@osm0sis @vvb2060 Nope still

![Screenshot_20210318-072638582](https://user-images.githubusercontent.com/46316533/111555871-deb57480-87bb-11eb-9952-8254cc85698e.jpg)
![Screenshot_20210318-072733018](https://user-images.githubusercontent.com/46316533/111555857-db21ed80-87bb-11eb-87e3-6e787d0444b7.jpg)
![Screenshot_20210318-072620825](https://user-images.githubusercontent.com/46316533/111555862-dcebb100-87bb-11eb-8896-9dfc6d8e1a68.jpg)
![Screenshot_20210318-072628404](https://user-images.githubusercontent.com/46316533/111555869-de1cde00-87bb-11eb-90a5-fe6120e74d15.jpg)

**Comment by reiryuki** [comment]
![Screenshot_20210318-072532967](https://user-images.githubusercontent.com/46316533/111556098-5a172600-87bc-11eb-924a-a75cdb91bcf2.jpg)
![Screenshot_20210318-072638582](https://user-images.githubusercontent.com/46316533/111556102-5c798000-87bc-11eb-9c06-1d37f5a329b4.jpg)

**Comment by reiryuki** [comment]
I mean the
`rm -rf /data/unencrypted/magisk /cache/magisk /metadata/magisk /persist/magisk /mnt/vendor/persist/magisk`
should be placed after `RULESDIR=....`

**Comment by vvb2060** [comment]
`readlink -f /sbin/.magisk/mirror/sepolicy.rules`
What is its output?

**Comment by reiryuki** [comment]
No output at all after rm -rf
Tried at terminal emulator

**Comment by vvb2060** [comment]
?

**Comment by vvb2060** [comment]
`ls -l /sbin/.magisk/mirror`

**Comment by reiryuki** [comment]
![Screenshot_20210318-132815544](https://user-images.githubusercontent.com/46316533/111583412-f65a2080-87ee-11eb-91ae-188cde4355df.jpg)


![Screenshot_20210318-133336120](https://user-images.githubusercontent.com/46316533/111583416-f823e400-87ee-11eb-9c05-5d434f5d019c.jpg)
(readlink is not detected)

![Screenshot_20210318-133557295](https://user-images.githubusercontent.com/46316533/111583417-f8bc7a80-87ee-11eb-8155-1d051d6d465b.jpg)
(readlink is detected)
