### ISSUE TITLE
new issue with es file explorer

### ISSUE THREAD

**Issue by m8ax** [topjohnwu/Magisk#3736]
es file explorer does not let me activate the root option, it says that the device cannot be rooted, it is enabled in magisk and everything but nothing does not work root in this app since 21.3. Years ago in a forum they gave this solution in case in your next version of magisk you want to solve it, or it gives you an idea of ​​the failure.

https://android.stackexchange.com/questions/155222/es-file-explorer-pro-root-access-error-on-android-6

**Comment by Paget96** [comment]
It's not a problem with ES File explorer only. It's not possible to grant root to any new installed app.

**Comment by m8ax** [comment]
with 21.2 grant root ok in es file explorer why in 21.4 no ?

**Comment by m8ax** [comment]
if i insatll a new app thars require root , runs fine. only es file explorer have problems , with 21.2 runs ok all rooted apps

**Comment by FAROK000** [comment]
Solution? ?

**Comment by FAROK000** [comment]
I am using version 22.0 Is it ok to install 21.2 above the new one?
Cuzz i didn't found a solution for that!!💔

**Comment by thethiny** [comment]
@m8ax it's ES File Explorer problem. Magisk 21 does not work with ES File Explorer. Magisk 22 works with ES Explorer 4.9. Magisk 23 doesn't work with ES File explorer (yet).
