### ISSUE TITLE
Magisk Manager Issues on Android KitKat

### ISSUE THREAD

**Issue by theft07** [topjohnwu/Magisk#3739]
1) MM 8.0.7 stable and MM f5593e05 (4835) (15) canary crash when going to the 'magisk log' part inside the app (the little bug icon at the bottom) on android 4.4.4;
Logcat of the crash (from canary build): https://drive.google.com/file/d/1XXHPpv3RDQ3VJQkKeLmIRkPXXxh_80ND/view?usp=sharing

2) MM 8.0.7 stable and MM f5593e05 (4835) (15) canary fail to patch an odin .tar file (Android 4.4.4 TouchWiz) resulting in this magisk install log: https://drive.google.com/file/d/1gsuUVD2wQ0GaB-1GkMjeUO7neww90hXm/view?usp=sharing

*Boot.img of the kitkat firmware needed for patching: https://drive.google.com/file/d/12wJp_ptXFrB1YKr9rr7RZ988MCJEn3lj/view?usp=sharing

**Comment by topjohnwu** [comment]
Fixed ccb55205e6da41be064b3421d85e05c36062d9c7
