### ISSUE TITLE
Viper4android with Magisk 21.x - Samsung s20 plus Exynos

### ISSUE THREAD

**Issue by Gorli** [topjohnwu/Magisk#3744]
Dear developers,

I would like to address an already mentioned but unfortunately also closed (?) "problem". (Issue 3508)
Magisk is without a doubt unique and amazing. Why don't I need to emphasize. I would also like to thank ALL of those responsible for this wonderful work!

But now I use Magisk to do things that would not be possible without Magisk. This includes the control of the audio output via V4A v. 2.7.2.1.

Android 11 is now also supported by Magisk v 21.x thanks to your wonderful work. To do this, Magisk 21.x must be installed. I am using the SAMSUNG Galaxy S20 Plus Exynos!

However, I have to agree with the previous speakers and would like to point out again and again that since Magisk 21.x it is no longer possible to install or successfully activate the driver for V4A.

For what reason this is no longer possible I cannot judge, but I am thinking of an interaction of the partitions of Android 11 or the driver path changing or an authorization problem for the files ?!
This certainly has nothing to do with legacy mode or other procedures / settings and does not work either.

For this reason I am currently running my Samsung Galaxy S20 plus Exynos with Magisk 20.4, Android 10 - the freedom based on Magisk is so important to me that I can achieve what I want.

For this reason, I would like to ask you politely, perhaps to take up this problem again.

In the hope of a positive response and a solution, I remain with best regards

Goarli

**Comment by wangdaning** [comment]
Threads are getting closed on this because it is something that the module dev needs to address. You cannot really expect the magisk project to be based on whether or not one specific module is working, can you?

**Comment by Gorli** [comment]
Good day,

thank you for your quick reply and opinion!

I absolutely agree with you. This can certainly NOT depend on a module - that's how I see it.

Well, my request was not a requirement or a condition. It should only help me to take the next step with your experience or assumption.

I will have to contact the developers of V4A!

Whether it is related to the technical questions directed at you was only a question of finding or assuming!

Nevertheless, many thanks for your comments and efforts!

Goarli

**Comment by Gorli** [comment]
Hello again,

who searches will find it!

The following post helped me and led me to my successful goal!

https://forum.xda-developers.com/t/app-all-root-solutions-6-0-phia4android-fx-2-7.3774651/post-84209895

Viper4Android FX 2.7.2.1 now also works with Magisk 21.x (21.4)

Kind regards
Goarli
