### ISSUE TITLE
Suggest to change root paths and names 

### ISSUE THREAD

**Issue by qtr1st** [topjohnwu/Magisk#3745]
As some app uses the search in their files to stop app from working
![80EE3585-5D83-4577-86CE-FD2F82E9A79F](https://user-images.githubusercontent.com/75439362/105038033-dff24b80-5a6f-11eb-8189-57df0a2ec1b1.png)

**Comment by zgfg** [comment]
How long would that work?
The source code is available here, hence the new names will be, too

**Comment by Haus3master** [comment]
Another method is to randomise the names, like when we hide Magisk manager with a random package name, but, one caveat is that, it will be extremely difficult to do such level of spoofing, other binaries audio require updating when the name is randomised...
