### ISSUE TITLE
Touch Screen Not Working on A11.

### ISSUE THREAD

**Issue by mynameisanf** [topjohnwu/Magisk#3747]
Device:- Motorola One Macro (lima, XT2016-1) (MT6771)
Stock boot image (magisk patched), and stock kernel. 
I know that issues related to GSIs are not supported but I wanted to send some logs so someone could look into this (I also sent this in PHH group so the issue could be looked at, I can't test this on custom ROMs either (no development for device). So my device's touch screen stop working on any Android 11 GSI, if I use magisk with it (Doesn't work at all). On Android 10 it's fine. Only Android 11 has this issue. So, if you can look into these logs and check the issue, it would be great.
[touchscreenissue(lima).log](https://github.com/topjohnwu/Magisk/files/5841817/touchscreenissue.lima.log)

**Comment by DiegoTorres18** [comment]
Hello, have you found a solution? The same thing happens to me

**Comment by Legwaz** [comment]
no meu one macro só funcionava o touch quando eu removia o magisk
