### ISSUE TITLE
Oneplus 7T OxygenOS 11 (Beta 1) - Don't Boot

### ISSUE THREAD

**Issue by bobaoapae** [topjohnwu/Magisk#3750]
Version Name: f5593e05
Version Code:21401
Device: Oneplus 7T (Global)
OS Version: OxygenOS 11 (Beta 1)

After patch and flash boot extracted from payload.bin, phone is stuck on logo screen. I don't know how to get kernel log without root, if you know i way i will send kernel log.

[logcat_bootlop.txt](https://github.com/topjohnwu/Magisk/files/5845030/logcat_bootlop.txt)
[mounts_bootlop.txt](https://github.com/topjohnwu/Magisk/files/5845032/mounts_bootlop.txt)
[mounts_ok.txt](https://github.com/topjohnwu/Magisk/files/5845035/mounts_ok.txt)

**Comment by Lishoo** [comment]
Hi, try to install this zip in the modules -> install from memory and see if the problem is fixed.
[modMagisk-v21.4.zip](https://github.com/topjohnwu/Magisk/files/5846013/modMagisk-v21.4.zip)

**Comment by bobaoapae** [comment]
I cant use modules because i don't have working any magisk version on my phone now

**Comment by Didgeridoohan** [comment]
@Lishoo Where did you get that Magisk zip, how is it modded and by who? Just throwing random zips out there (that shouldn't be trusted without knowing where they come from, and even then it's a good idea to be very cautious) isn't the best troubleshooting practice...

**Comment by Lishoo** [comment]
@Didgeridoohan I made that zip, check out my post here:
https://github.com/topjohnwu/Magisk/issues/3722#issuecomment-764042492

**Comment by bobaoapae** [comment]
Latest canary build. Same error
@topjohnwu
