### ISSUE TITLE
Magisk 21.4 unable to repack boot image during update

### ISSUE THREAD

**Issue by gjf** [topjohnwu/Magisk#3751]
Samsung SM-P605 device running Android 5.1.1 (latest stock ROM).
Magisk 20.4 / manager 8.0.7 are installed and working.
The manager requires an update to 21.4 but cannot repack image during install.
The log file is attached and it seems the scripts are not alright.
[magisk_install_log_2021-01-20T23_11_15Z.log](https://github.com/topjohnwu/Magisk/files/5845085/magisk_install_log_2021-01-20T23_11_15Z.log)

The error exists both in automatic mode and manual boot patching. The only way to update is to install in recovery.

**Comment by topjohnwu** [comment]
This should already be fixed with the latest Magisk Manager version
