### ISSUE TITLE
[Feature Request] Ability to downgrade magisk from manager app

### ISSUE THREAD

**Issue by ShrirajHegde** [topjohnwu/Magisk#3754]
Ability to  downgrade/download older magisk versions from manager app

**Comment by BigmenPixel0** [comment]
> Ability to downgrade/download older magisk versions from manager app

you may download need version of magisk and flash it like module

**Comment by bootsmann** [comment]
I also have to downgrade magisk because after magisk update today Android is crashing/freezing while connecting to wlan. Phone has no internet connection anymore.

**Comment by zgfg** [comment]
Downgrading is possible by taking URL for an older Stable json or preparing your own json for an older Canary version, and by using Custom  Update Chnnel: https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-84345005

Btw, I had asked for a more generic feature, ability to use local custom json file, unfortnately it was dismissed/closed:
https://github.com/topjohnwu/Magisk/issues/3588

**Comment by topjohnwu** [comment]
No

**Comment by IzzySoft** [comment]
Sad. That "no" almost left me with a half-broken device now, as some essential (for me) modules stopped working with v27. I managed reverting to v26.4 thanks to a bunch of backups I had kept, but the whole thing would have been much easier were there an "emergency downgrade" option available. Like, if an update had side-effects (as in my case) to offer "undo update". You know, similar to changing your screen resolution, just without the timeout for auto-revert if you don't respond (one might notice the side-effect only hours or even days later).

Note: I'm not talking about "downgrade to whatever" here – but about having a sane fallback solution should an update cause issues. Magisk could even see that itself in cases like mine: A module that was enabled before and working fine not loading anymore after the upgrade would be an indicator for these.

Maybe you could consider that "specific downgrade case", @topjohnwu?

**Comment by itskhawer** [comment]
I upgraded to v27 and now some of my apps are not able to detect root and some of the Magisk modules are not working. Now I want to downgrade to v26.4 but all I am afraid of is losing my data and root access. I wish Magisk had that option to downgrade as explained beautifully by @IzzySoft. I couldn't agree more that this "NO" is very sad to see.
