### ISSUE TITLE
Install Failed unsupported/format OPPO A9 (2020)

### ISSUE THREAD

**Issue by Schesch1** [topjohnwu/Magisk#3756]
I have tried numerous times not to root my Oppo A9 (2020) with magisk, but i keep getting to same error can someone please help.

[oppo a9 2020 boot.zip](https://github.com/topjohnwu/Magisk/files/5859491/oppo.a9.2020.boot.zip)

**Comment by Displax** [comment]
You need to decrypt it first

**Comment by SiriusDelta8** [comment]
How should it be deciphered?
