### ISSUE TITLE
"No command" after flashing patched boot.img on Likebook Mars T80D (Android 8)

### ISSUE THREAD

**Issue by daffy1234** [topjohnwu/Magisk#3757]
Installing the manager works fine. I tried both the boot.img and recovery.img methods. Both with and without `Preserve AVB 2.0/dm-verify`. For one, flashing with fastboot doesn't work at all.

Flashing the patched boot fails with this:

    fastboot: error: Couldn't parse partition size '0x0000000000010000(blk)'.

Flashing the patched recovery fails with this:

    Sending 'recovery' (30390 KB)                      FAILED (remote: 'not support "-u" option')

So I use rockchip's own flashing tool RKDevTool instead. Flashing the patched boot.img (with and without the preserve dm-verify option) boots to a broken android logo with "No command". Flashing the patched recovery.img boots normally, except when i tell it to boot to recovery (this device has no recovery key combo, I have to force it to boot to recovery with `adb reboot recovery`) it boots to yet another "No command" screen.

The device I'm trying to run this on is a Boyue Likebook Mars T80D e-reader tablet. It's android 8 based and uses a rockchip RK3368.

Any ideas? Anything I should test?

Here's the device tree if that's helpful https://github.com/daffy1234/T80D-device-tree

**Comment by jpzex** [comment]
This broken Android with no command written on screen is the recovery. You can access it's commands by tapping volume buttons several times. Sadly it will give you limited possibilities as install update from SD (OTA ZIP), factory reset (wipe data), wipe /cache (if available) and maybe other things too.

**Comment by daffy1234** [comment]
Is there any way to install Magisk without being kicked into recovery? I also tried flashing a patched recovery.img but that had the same No Command effect when booting to recovery. There's no way to boot into recovery with this device without going through a normal boot first (no volume buttons, only a power and reset button, which goes into a firmware loading mode not recovery mode) so the people at the TWRP building support group said it might be restoring the recovery partition when booting normally. Not sure where to go from here.

**Comment by topjohnwu** [comment]
Rockchip boot images are not supported
