### ISSUE TITLE
Latest version of Magisk canary does not work (21402)

### ISSUE THREAD

**Issue by Lishoo** [topjohnwu/Magisk#3762]
Phone LG g6 h870 Android 9

Magisk log:

```
-Device platform: arm64-v8a
-Installing: 658d74e0 (21402)
! Installation failed
- Copying image to cache
! Process error
```

Boot image:
[orginal_boot.zip](https://github.com/topjohnwu/Magisk/files/5862778/orginal_boot.zip)

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/pull/3692/commits/d8e6e85c0148d9c187ccc0a0b241748d3d0e60c8

**Comment by Lishoo** [comment]
Magisk Manager (canary) shows that latest available is 6951d926 (21402)(16)
Installed is 658d74e0 (21402) but there is no way to update it to the latest version, after install or download the version is always 658d74e0 (21402)

**Comment by gossbill** [comment]
The reason the error occurred is because Magisk Manager hasn't been granted Storage permission and, I'm guessing, is getting to write the output to /cache instead.
Once MM had storage permission the patching process works fine.

**Comment by vvb2060** [comment]
8f08ae5

**Comment by Lishoo** [comment]
@gossbill Magisk has permission to access the storage, but the error occurs.

**Comment by vvb2060** [comment]
@Lishoo  21405 fixed

**Comment by Lishoo** [comment]
Not really ;) the first try to patch boot.img always fails, but the second, and next do success but the ramdisk is still damaged.

**Comment by vvb2060** [comment]
Cannot reproduce

**Comment by gossbill** [comment]
@Lishoo - For me 21405 works nicely. I did a clean install (uninstalled the current Magisk Manager then installed Magisk 21405). When I select install Magisk>Select and patch file the first time I'm prompted to grant Magisk Manger storage permission (I'm on Android 10) and then the patch process proceeds cleanly to completion.

**Comment by Lishoo** [comment]
I'v tried to reinstall Magisk, the problem still the same, after Magisk starts I select install Magisk->Select and patch file, Magisk thinks a while and than fails, then I select the same file and then success, then again I select any other boot.img and success, but when I exit Magisk, and start again, the first time I try to patch boot.img always fails.

**Comment by vvb2060** [comment]
No log, no fix.

**Comment by Lishoo** [comment]
This is the magisk log :)
[magisk_install_log_2021-01-25T204816Z.log](https://github.com/topjohnwu/Magisk/files/5870304/magisk_install_log_2021-01-25T204816Z.log)

**Comment by rohanz6** [comment]
This works for me
-     Download the latest Canary release of Magisk from https://github.com/topjohnwu/Magisk. 
-     Uninstall the current version of Magisk. 
-     Install the downloaded Canary release of Magisk. 
-     Open the Magisk app. 
-     Click on Update and select Direct Install.
