### ISSUE TITLE
Cannot install BusyBox NPC

### ISSUE THREAD

**Issue by wpigoury** [topjohnwu/Magisk#3763]
Hi,

Since update to merged Magisk canary (6951d926 (21402) for Magisk and 658d74e0 (21402) for manager), I cannot install BusyBox anymore (neither build fetched from module library > Busybox_for_Android_NDK-1.31.1(13120).zip nor previous version installed from disk > Busybox_for_Android_NDK-1.31.1(13119).zip).
Joining install log below, oddly nothing appears in Magisk log.

I'm on OnePlus8T (Android 11) for 2 months now and I have been using Magisk for quite some time on previous device, but never had this issue before.

I tried reinstalling the module several times and reinstalling current version of Magisk as well without success.
Before trying to downgrade, anyone have any idea of what can be the issue?

Thanks.

```
- Copying zip to temp directory
- Installing Busybox_for_Android_NDK-1.31.1(13120).zip
- Current boot slot: _b
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
*****************************
 Busybox for Android NDK 
 by osm0sis @ xda-developers 
*****************************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
unzip: can't open 'diffusion_config.sh': Read-only file system
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
grep: module.prop: No such file or directory
/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: .: line 510: can't open './diffusion_config.sh': No such file or directory
! Installation failed
```

**Comment by wbedard** [comment]
I'll second that on my OnePlus 6T (Android 10).  I left a notice for osm0sis in his XDA support thread.

**Comment by wpigoury** [comment]
I did some more testing and it seems only osm0sis modules are concerned by this issue.
I tried installing ZipSigner and Nano with same error at the end.
I also tried installing Riru and Magiskhide Props Config from other Devs which worked flawlessly.

Looks like osmOsis modules are using some feature that has been removed from Magisk.
I don't know who should fix this though.

**Comment by xerta555** [comment]
Works again 👍🏻

**Comment by wpigoury** [comment]
All good now yes, thanks for the quick fix.
