### ISSUE TITLE
Patch Image method failed on 21403

### ISSUE THREAD

**Issue by pndwal** [topjohnwu/Magisk#3765]
Have updated using direct Install fine once again.

However, patching image is still ending with:
- Device platform: arm64-v8a
- Installing: 4cc41ecc (21403)
- Copying image to cache
! Process error
! Installation failed

[magisk_log_2021-01-25T17:31:02Z.log](https://github.com/topjohnwu/Magisk/files/5864643/magisk_log_2021-01-25T17.31.02Z.log)

Xiaomi Redmi Note 8T, MIUI 12 (Android 10), Magisk 21403, Magisk Storage Permission is 'Allowed'. PW

**Comment by zgfg** [comment]
Failing for me also on Xiaomi Mi 9T, Xiaomi.eu 21.1.20

Mine is A11 and with 21402 and 21403 I can no more patch my boot.img.
With 21401 and earlier, I was always patching and absolutely with no problem

Btw, I see the app Magisk in Settings, but on my A11 I don't see any way control its storage access

**Comment by zgfg** [comment]
Attching screnshots and log
![Screenshot_2021-01-25-07-38-31-391_com topjohnwu magisk](https://user-images.githubusercontent.com/51943147/105670092-c40fff00-5ee0-11eb-950d-15bddb9ae1ea.jpg)
![Screenshot_2021-01-25-07-38-54-329_com topjohnwu magisk](https://user-images.githubusercontent.com/51943147/105670128-d25e1b00-5ee0-11eb-8d86-bca2270b5a89.jpg)
![Screenshot_2021-01-25-07-39-56-201_com miui securitycenter](https://user-images.githubusercontent.com/51943147/105670143-da1dbf80-5ee0-11eb-9b81-55974c448b31.jpg)
[magisk_log_2021-01-25T07_37_47Z.log](https://github.com/topjohnwu/Magisk/files/5864676/magisk_log_2021-01-25T07_37_47Z.log)

**Comment by zgfg** [comment]
Ok, I took now Direct method and it worked 

But if I was not already rooted with 21401, IMO direct method could not be used
and I would not be able to install Magisk anymore (without flashing through TWRP which is not recommended and I don't like it anyway, or again by first installing 21401)

**Comment by Didgeridoohan** [comment]
Already fixed upstream:
https://github.com/topjohnwu/Magisk/commit/8f08ae59ac8bad0b17270b42f24f100d38cba2fc

**Comment by zgfg** [comment]
With 21405 patching works again fine for me

**Comment by Didgeridoohan** [comment]
So most likely a temporary glitch.

**Comment by pndwal** [comment]
Many thanks TJW!
