### ISSUE TITLE
21404: Cannot update Manager from 21403, parsing package error

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#3767]
Xiaomi Mi 9T, Xiaimi.eu A11

Today updated to 21403 by Direct method (patching the image still failed with 21403, ref #3765 like it failed with 21402)

Now wanted to update to the newest 21404 but cannot even update the Manager part anymore
![Screenshot_2021-01-25-11-06-13-310_com topjohnwu magisk](https://user-images.githubusercontent.com/51943147/105691926-2297a600-5efe-11eb-873b-f27c13619a66.jpg)
![Screenshot_2021-01-25-11-00-17-304_com miui packageinstaller](https://user-images.githubusercontent.com/51943147/105691964-2dead180-5efe-11eb-8f86-222f61e33a18.jpg)
[magisk_log_2021-01-25T11_06_25Z.log](https://github.com/topjohnwu/Magisk/files/5865758/magisk_log_2021-01-25T11_06_25Z.log)

**Comment by topjohnwu** [comment]
Cannot reproduce, and you are not providing the correct logs

**Comment by zgfg** [comment]
After two times failing to update through the app, I spotted Notification that 21404 was downloaded, clicked and it installed without any package error (hence package error only when updating through the app)

**Comment by zgfg** [comment]
> Cannot reproduce, and you are not providing the correct logs

Tell me then what kind of logs

Bug is present

**Comment by zgfg** [comment]
Ok, worked fine with 21405 (and patching too)

**Comment by pndwal** [comment]
"Tell me then what kind of logs"
Just found the basic info on main page:
https://github.com/topjohnwu/Magisk#bug-reports
👍
