### ISSUE TITLE
Latest canary version 07bd36c9 (21505) damages boot.img / removes RAW data

### ISSUE THREAD

**Issue by Lishoo** [topjohnwu/Magisk#3770]
Latest version of Magisk still damages the boot.img when patching, output boot.img is 10mb instead of 22mb.
Differences in logs 
patched and working v21.4 (magiskboot) 
```
CHECKSUM        [b8aa7cfc33c9db071a53a39d5aae8fd4233e6d9a000000000000000000000000]
KERNEL_DTB      [5140711]
**KERNEL_FMT      [lz4_legacy]**
RAMDISK_FMT     [gzip]
**EXTRA_FMT       [raw]**
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
**KERNEL_SZ       [18114732]**
RAMDISK_SZ      [5325552]
SECOND_SZ       [0]
EXTRA_SZ        [0]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2019-05]
PAGESIZE        [4096]
NAME            []
```

Not working lates canary build
```
- Repacking boot image
CHECKSUM        [b8aa7cfc33c9db071a53a39d5aae8fd4233e6d9a000000000000000000000000]
KERNEL_DTB      [5140711]
**KERNEL_FMT      [lz4_lg]**
RAMDISK_FMT     [gzip]
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
**KERNEL_SZ       [5140719]**
RAMDISK_SZ      [5325552]
SECOND_SZ       [0]
EXTRA_SZ        [0]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2019-05]
PAGESIZE        [4096]
NAME            []
```
KERNEL_FMT      [lz4_legacy] | **KERNEL_FMT      [lz4_lg]**
EXTRA_FMT       [raw] |
KERNEL_SZ       [18114732]  | **KERNEL_SZ       [5140719]**

![Screenshot_20210125-222656](https://user-images.githubusercontent.com/1045996/105769354-fe6bb180-5f5d-11eb-873e-d20d9380e60c.png)

[org_boot.zip](https://github.com/topjohnwu/Magisk/files/5869823/org_boot.zip)
[magisk_patched_working.zip](https://github.com/topjohnwu/Magisk/files/5869856/magisk_patched_working.zip)

[magisk_install_log_2021-01-25T204816Z.log](https://github.com/topjohnwu/Magisk/files/5869816/magisk_install_log_2021-01-25T204816Z.log)
[magisk_install_log_2021-01-25T205452Z.log](https://github.com/topjohnwu/Magisk/files/5869817/magisk_install_log_2021-01-25T205452Z.log)
[magisk_install_log_2021-01-25T210419Z.log](https://github.com/topjohnwu/Magisk/files/5869838/magisk_install_log_2021-01-25T210419Z.log)
[magisk_patched_Qehwh.zip](https://github.com/topjohnwu/Magisk/files/5869820/magisk_patched_Qehwh.zip)
[magisk_patched_QGew2.zip](https://github.com/topjohnwu/Magisk/files/5869849/magisk_patched_QGew2.zip)

Previously replacing the magiskboot from v21.0 in the .zip package fixed the problem, but now I think it's impossible?

After direct install (recommended) boot loop
[magisk_install_log_2021-01-25T225919Z.log](https://github.com/topjohnwu/Magisk/files/5869946/magisk_install_log_2021-01-25T225919Z.log)

Flashing magisk_patched_boot.img (v20.4) (previously working) magisk stopped to work (no root)
![Screenshot_20210125-230307](https://user-images.githubusercontent.com/1045996/105772080-f1e95800-5f61-11eb-83b6-37da75959a64.png)

The only way to restore root is to install Magisk Manager v8.0.7 (4834) and reboot.

**Comment by Lishoo** [comment]
I'v finally made my own build and fix that bug
![Screenshot_20210203-011917](https://user-images.githubusercontent.com/1045996/106681061-0790fa00-65c0-11eb-9e2e-e1855c797e36.png)
If someone needs the fix urgently install this version o magisk

[magisk_with_fix.zip](https://github.com/topjohnwu/Magisk/files/5915314/magisk_with_fix.zip)

**Comment by llucax** [comment]
Why is this closed if the bug is still present?

**Comment by Lishoo** [comment]
Because the solution is known, I think @topjohnwu will fix this in the next update.
