### ISSUE TITLE
最新金丝雀版识别构架错误

### ISSUE THREAD

**Issue by bugme2** [topjohnwu/Magisk#3771]
金丝雀版本会把aarch64修改成armv8l，导致linuxdeploy的部分场景识别不到正确的构架，影响使用，使用21.4暂无此问题。
![-1f8c8b7c80c7ed02](https://user-images.githubusercontent.com/40169265/105844139-b313da80-6013-11eb-901e-1597c604ef2a.jpg)

**Comment by vvb2060** [comment]
看不懂，似乎是第三方具有错误的行为假设。请说明操作步骤、预期现象和实际现象。

**Comment by topjohnwu** [comment]
沒錯，只要你的系統裡有 `/system/lib64`，64-bit binary 就會被安裝
