### ISSUE TITLE
Biometrics not supported

### ISSUE THREAD

**Issue by diiegg** [topjohnwu/Magisk#3773]
I have a OP7pro with custome ROM (evolution x androind 11) Magisk is canary

Its says that biometric authentication is not supported in this device or settings are no enable...

[logs](https://drive.google.com/file/d/158Vy4NJZZMDbAid_No5z7EINeSDHjnVJ/view?usp=sharing)

**Comment by Didgeridoohan** [comment]
You've got the SafetyNet Fix module installed. That's known to break fingerprint authentication on some devices. Most likely this is a module issue, not anything to do with Magisk.
