### ISSUE TITLE
Uninstalled with Magisk uninstall script, bootlooped and unable to get back into the phone

### ISSUE THREAD

**Issue by jazir5** [topjohnwu/Magisk#3777]
I was trying to downgrade to an earlier magisk version and I ran the uninstaller script. I did not have twrp installed as I have an LG G7(there is no permanent twrp), and I was forced to reboot via auto reboot. 

My phone rebooted to a android logo with an X. I tried reinstalling the stock boot image via QFIL, and it still won't boot past the LG logo. I also tried reflashing the rooted boot image with the latest version of magisk via qfil, that doesn't work either. 

How can I fix this without wiping? Unfortunately the data isnt backed up, so I would really like to get the phone back up and working if possible.

**Comment by topjohnwu** [comment]
If restoring back to stock boot image doesn't work, then there is nothing Magisk can do. What the uninstaller does is simply restoring the boot image and remove some Magisk specific files. Uninstalling Magisk really only involves restoring boot image.

**Comment by jazir5** [comment]
@topjohnwu 

Then why would using the uninstaller result in this bootloop where it can't pass the lg logo? Is there anything else I can try?
