### ISSUE TITLE
MagiskInstaller task does not install or update /system/addon.d/99-magisk.sh

### ISSUE THREAD

**Issue by mdoggydog** [topjohnwu/Magisk#3782]
The MagiskManager app does not install or update `/system/addon.d/99-magisk.sh`.

If Magisk is initially installed via "Patching Images" (i.e., patching `boot.img` with MagiskManager and then manually flashing via `fastboot flash boot` --- the method recommended for 100% reliability by the [installation instructions](https://topjohnwu.github.io/Magisk/install.html)), then `/system/addon.d/99-magisk.sh` **will not** be installed and Magisk will not automatically survive future OTA updates of LineageOS (for example).

If Magisk is initially installed via "Custom Recovery" (i.e., `adb sideload` the installation `.zip` while booted to a custom recovery), then `addon.d.sh` **will** get copied to `/system/addon.d/99-magisk.sh`.  However, that file will never get updated by subsequent updates via the MagiskManager app.  (Note that, when invoked as `/system/addon.d/99-magisk.sh`, the script will almost immediately jump to the copy at `/data/adb/magisk/addon.d.sh`, which does get updated --- so only changes that affect this trampoline mechanism would make a noticeable difference.)

**Comment by topjohnwu** [comment]
This is expected as the script is simply a loader to the actual installer scripts

**Comment by mdoggydog** [comment]
> This is expected as the script is simply a loader to the actual installer scripts

Just to be clear, I am talking about code paths executed via `tasks/MagiskInstaller.kt`.

The only code which sets up `/system/addon.d/99-magisk.sh` is in `updater-script` (also known as `scripts/flash_script.sh`) --- and this script is never executed by `MagiskInstaller.kt`.  `updater-script` is only executed by `update-binary` (`scripts/update_binary.sh`), and that is only executed when Magisk is installed via the installer .zip in a custom recovery.

As of `ec8fffe61` (2021-01-22), `update-binary` is not invoked by `MagiskInstaller.kt` at all.  Before `ec8fffe61`, `update-binary` could be invoked by `MagiskInstaller.kt`, like this:
```
sh update-binary sh boot_patch.sh $srcBoot
```
But, when `update-binary` was invoked this way, it would only execute `boot-patch.sh`.

My apologies if I missed something, but I have not been able to find any code path leading from `MagiskInstaller.kt` that touches `/system/addon.d/`, in code from today back to at least 2019-07.
