### ISSUE TITLE
Magisk 6fb20b3e crashes when I try to flash(directly install) the latest version

### ISSUE THREAD

**Issue by Cyberavater** [topjohnwu/Magisk#3785]
Android 7; It didn't happen before the manager merge update.
log: 
[logcat_01-28-2021_12-26-59.txt](https://github.com/topjohnwu/Magisk/files/5885397/logcat_01-28-2021_12-26-59.txt)

**Comment by Mikesew1320** [comment]
> Android 7; It didn't happen before the manager merge update.
> log:
> [logcat_01-28-2021_12-26-59.txt](https://github.com/topjohnwu/Magisk/files/5885397/logcat_01-28-2021_12-26-59.txt)

Same here

**Comment by Cyberavater** [comment]
Now I'm getting a new error when direct installing.

[magisk_install_log_2021-01-31T13_23_44Z.log](https://github.com/topjohnwu/Magisk/files/5899329/magisk_install_log_2021-01-31T13_23_44Z.log)
