### ISSUE TITLE
LG G5 (H830) bootloop (Magisk 21.1+)

### ISSUE THREAD

**Issue by Disappear9** [topjohnwu/Magisk#3787]
System:
```
Fulmics ROM 5.5
Android ver: 7.0
Kernel ver: 3.18.97-H830_v1.5.5-mk2000
sec patch: 2017/11/06
```

Tested magisk ver:
```
CANARY 6fb20b3e BOOTLOOP
20.4 OK
21.0 OK
21.1 BOOTLOOP
21.2 BOOTLOOP
21.3 BOOTLOOP
21.4 BOOTLOOP
```

Logs:

[console-ramoops.txt](https://github.com/topjohnwu/Magisk/files/5887477/console-ramoops.txt)
[console-ramoops-long.txt](https://github.com/topjohnwu/Magisk/files/5887481/console-ramoops-long.txt)
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/5887482/dmesg.txt)
[recovery.txt](https://github.com/topjohnwu/Magisk/files/5887483/recovery.txt)

**Comment by DenyDarko** [comment]
https://github.com/topjohnwu/Magisk/issues/3635

I've already provided everything you did but didn't bother reopening another issue as I don't have the knowledge to build the kernel with debug flags enabled.

**Comment by Lishoo** [comment]
Hi, try the build from my last post on this topic https://github.com/topjohnwu/Magisk/issues/3770

**Comment by Disappear9** [comment]
> Hi, try the build from my last post on this topic #3770

It works!
