### ISSUE TITLE
Cant get a valid ID - Xiaomi framework issue.

### ISSUE THREAD

**Issue by defineltd** [topjohnwu/Magisk#3788]
Each time restart my phone, for the first 5 minutes of use, i have no sim connection (Network/phone/data) and this popup occurs every few seconds.

![image](https://user-images.githubusercontent.com/78157813/106151703-a04ff180-614a-11eb-9488-9896fd89c43b.png)

It happens after I install magisk, if i uninstall, it goes back to normal.

I've tried with several versions of xiaomi.eu's ROMS, and versions 21.xx (all version 21's) and still have the same issue. Any insight on how to fix this would be greatly appreciated.

**Comment by zgfg** [comment]
Which Xiaomi phone and Xiaomi.eu A10 or A11 beta?

Do you have modules installed - disable and reboot

If MIUI Optimization is disabled, turn it on

No problem on my Mi 9T, Xiaomi.eu 21.1.20 A11 beta, Magisk 21406 Canary

**Comment by defineltd** [comment]
> Which Xiaomi phone and Xiaomi.eu A10 or A11 beta?
> 
> Do you have modules installed - disable and reboot
> 
> If MIUI Optimization is disabled, turn it on
> 
> No problem on my Mi 9T, Xiaomi.eu 21.1.20 A11 beta, Magisk 21406 Canary

Xiaomi CC9 pro (note 10) A11 21.1.20 also.

NO modules at all, happens right from the first installation of magisk. tried magisk 21.0-21.4 with no changes, MIui optimization you mean battery optimization? thats off for magisk, yeah.

**Comment by zgfg** [comment]
I thought about Development options / MIUI Optimization, but seems it's not present in Xiomi.eu

Updated to today's Xiaomi.eu 21.1.28, still ok for me

Magisk does not need to be Battery optimization Off

**Comment by defineltd** [comment]
updating now, let's see i its any different.
