### ISSUE TITLE
Force Close while Tap Save Install Log

### ISSUE THREAD

**Issue by reiryuki** [topjohnwu/Magisk#3792]
Magisk Manager 8.0.7 (4834)

Force closed when tapping save install process logs at the top right corner after installing any modules

[Magisk-logcat_01-26-2021_07-22-24.txt](https://github.com/topjohnwu/Magisk/files/5891135/Magisk-logcat_01-26-2021_07-22-24.txt)

**Comment by topjohnwu** [comment]
No crash logs is included, and use canary for reports

**Comment by reiryuki** [comment]
Okay sir
