### ISSUE TITLE
Patching the same boot.img intermittently fails (21406)

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#3795]
Xiaomi Mi 9T, A11, Magisk 21406

Keeping my boot.img file in Downloads folder (Internal memory) and patching every time exactly the same file, same way (with Recovery option disabled, by default):
- Install (patch)
- back
- Install (patch)
- back
etc.

Same file, same conditions - but sometimes:
- it patches successfully
![Success](https://user-images.githubusercontent.com/51943147/106325051-78f84200-627a-11eb-9303-1f82a8cdce50.jpg)

- sometimes it fails with Procces error
![Screenshot_2021-01-29-21-55-17-510_com topjohnwu magisk](https://user-images.githubusercontent.com/51943147/106326471-da211500-627c-11eb-9ef8-7fcfa4b6b72e.jpg)

- sometimes it stays forever in Flashing and I can only kill the Magisk (Manager) app
![Flashing-forever](https://user-images.githubusercontent.com/51943147/106325143-a0e7a580-627a-11eb-9491-42807a518cb0.jpg)

Success rate is between one or two times out of five attempts, but there is no pattern which outcome to expect

Patching started to fail after the recent merging of Magisk and Manager - before, I never ever observed that problem

Logcat:
[logcat-2021-01-29-20-37-15.zip](https://github.com/topjohnwu/Magisk/files/5896216/logcat-2021-01-29-20-37-15.zip)

Install logs from failed patching attempts:
[magisk_install_log_2021-01-29T20_31_02Z.log]
(https://github.com/topjohnwu/Magisk/files/5896218/magisk_install_log_2021-01-29T20_31_02Z.log)
[magisk_install_log_2021-01-29T20_32_22Z.log](https://github.com/topjohnwu/Magisk/files/5896220/magisk_install_log_2021-01-29T20_32_22Z.log)
[magisk_install_log_2021-01-29T20_33_05Z.log](https://github.com/topjohnwu/Magisk/files/5896221/magisk_install_log_2021-01-29T20_33_05Z.log)
[magisk_install_log_2021-01-29T20_35_47Z.log](https://github.com/topjohnwu/Magisk/files/5896224/magisk_install_log_2021-01-29T20_35_47Z.log)
[magisk_install_log_2021-01-29T20_36_24Z.log](https://github.com/topjohnwu/Magisk/files/5896226/magisk_install_log_2021-01-29T20_36_24Z.log)

boot.img (zipped, to be able to attach) I was using
[boot_img.zip](https://github.com/topjohnwu/Magisk/files/5896267/boot_img.zip)

**Comment by dr4go** [comment]
Additional information, but Galaxy S10 here when trying to patch the full AP file. It still doesn't work on 21407 since the Magisk Manager merge. Please see the Magisk log here:
[magisk_install_log_2021-01-30T22_35_34Z.log](https://github.com/topjohnwu/Magisk/files/5898765/magisk_install_log_2021-01-30T22_35_34Z.log)

**Comment by zgfg** [comment]
Cannot reproduce with 21408, closing
