### ISSUE TITLE
LG V20 (h918) bootloop and bricked updating to Magisk 21.4

### ISSUE THREAD

**Issue by frohro** [topjohnwu/Magisk#3802]
Sorry, I cannot get you a canary build number.  Maybe this is a feature request for Magisk Manager, to try and keep others from bricking their phone like I just did updating to Magisk 21.4.

I rooted my h918 and flashed h91820h.  I downloaded the TWRP app, and had it flash the latest TWRP, without rebooting.  Then I went to Magisk, and had it update to 21.4, and let it reboot.  The phone went into a boot loop, and it is so tight, I can only get into fastboot; no system, download or recovery.  LG removed any commands from fastboot that would allow you to do anything to unbrick your phone, so mine is a brick, and I am pretty convinced it is not possible to bring it back, based on my reading after the fact.  It would have been so nice to have a warning of that problem from Magisk Manager.  I believe it is a combination of flashing TWRP then updating Magisk, without rebooting in between that caused the problem.  There are other bug reports that LG phones have the bootloop problem, but mine is not fixable, because I was updating TWRP at the same time.  It would be nice to have a little warning not to reboot before trying to update Magisk if you just updated TWRP, and are using a LG phone.

Again, sorry I don't have the canary build number or know if it was a canary, because my phone is bricked.

Rob

**Comment by Lishoo** [comment]
fastboot flash boot boot.img doesn't work?
what about fastboot boot twrp.img ?
