### ISSUE TITLE
new Canary

### ISSUE THREAD

**Issue by Henry2o1o** [topjohnwu/Magisk#3804]
With last Canary, MIUI 12.5 Android 11 does not start anymore.  

Mi Note 10

**Comment by zgfg** [comment]
Mi 9T, Xiaomi.eu 21.1.28 (MIUI 12.5, A11) and Canary 21407 everything works

Patched the extracted boot.img and flashed (by Fastboot) to Boot

**Comment by Henry2o1o** [comment]
OK 👍
