### ISSUE TITLE
Samsung Galaxy S21Ultra Exynos stuck on bootscreen (21407) (21408)

### ISSUE THREAD

**Issue by m8980** [topjohnwu/Magisk#3808]
Hello, 

I'm on a new Samsung Galaxy S21Ultra (Exynos) FW: G998BXXU1AUAC , which is unrooted but Knox tripped.
Its not possible for me to boot the device properly after patching the usual files. Magisk Canary is installed in last version (21407).
My Device stuck on bootscreen after flashing stock fw with patched files. Its the samsung bootscreen which appears direct after unlocked bootloader warning screen. 

Here are some screenshots with additional information:

![Screenshot_Magisk_Canary_Version](https://user-images.githubusercontent.com/78386308/106525749-c677e780-64e4-11eb-8341-8cf39975959c.jpg)
![Screenshot_Magisk_patched_boot](https://user-images.githubusercontent.com/78386308/106525753-c7a91480-64e4-11eb-84d4-1c348d495153.jpg)
![Screenshot_Magisk_patched_boot+vbmeta](https://user-images.githubusercontent.com/78386308/106525755-c841ab00-64e4-11eb-9d63-f6f3d13f4a24.jpg)
![Screenshot_Magisk_patched_recovery](https://user-images.githubusercontent.com/78386308/106525756-c841ab00-64e4-11eb-900b-7dc4ca4cd105.jpg)
![Screenshot_Magisk_patched_vbmeta_fail](https://user-images.githubusercontent.com/78386308/106525759-c841ab00-64e4-11eb-9982-9f4f9879848e.jpg)
![Screenshot_Magisk_patched_vendor_boot](https://user-images.githubusercontent.com/78386308/106525761-c8da4180-64e4-11eb-880b-2e5786471570.jpg)
![Screenshot_S21Ultra_Versioninfo](https://user-images.githubusercontent.com/78386308/106525763-c8da4180-64e4-11eb-8a83-1a741a116ecb.jpg)

And here are stock and patched files. I've uploaded them to gdrive because of the 10 MB file size limit @github.

stock boot.img:
[https://drive.google.com/file/d/1bartvV8oHYZo86lirqdM49zMdETzJc1h/view?usp=sharing](url)

stock recovery.img:
[https://drive.google.com/file/d/1D3lwLA4P1tDrg49all1HBzpubk6p6cu4/view?usp=sharing](url)

stock vendor_boot.img:
[https://drive.google.com/file/d/1LonBHwL2BUKdmcNYaA0zmlolGEsXRR1m/view?usp=sharing](url)

stock vbmeta.img:
[https://drive.google.com/file/d/1PtnxbccUmSo9r8acdYpmMOWoZBKAOm0l/view?usp=sharing](url)

patched boot.img:
[https://drive.google.com/file/d/1MmUA76pQ5OfynBuaoq2UL_VxrKnbHDnC/view?usp=sharing](url)

patched recovery.img:
[https://drive.google.com/file/d/1AccBijZHYJvhlgKDbyJKttmXHMj_lXeP/view?usp=sharing](url)

patched vendor_boot.img:
[https://drive.google.com/file/d/1Sf0T7IZIhqlaj66cSCXwIdLtokraNe4c/view?usp=sharing](url)

patched boot+vbmeta.tar:
[https://drive.google.com/file/d/12DMrtWj5dt2rUJy3Dl3mJwa72n6MIjb8/view?usp=sharing](url)

I hope you can take a look into this issue.

Best regards

edit 01.02.2021: I'm not be able to pull a logcat during the stuck on bootscreen. Kernel is pure stock.

**Comment by m8980** [comment]
No boot error. Just stuck on boot screen. Flashing stock files in combination with patched files is not a problem. Flashing successfully

**Comment by mrambossek** [comment]
was the same for me - i never had signature mismatch etc errors or anything like that - flashing always worked - just stuck on the logo after that. unfortunately my issue #3796 was closed without any comment on how to proceed, so i am stuck on what i even COULD do...

**Comment by m8980** [comment]
I investigated a little bit and it seems, that A11 devices are using Boot Image Header V3
Take a look:
[https://source.android.com/devices/bootloader/boot-image-header](url) & [https://source.android.com/devices/architecture/kernel/generic-kernel-image](url)

Maybe there is an Update necessary for Magisk to support Boot Image Header V3.

**Comment by Didgeridoohan** [comment]
@m8980 https://github.com/topjohnwu/Magisk/commit/4aeac3b8f406b6bcc28ac6115be36a6c9688f1bb

**Comment by ahronshor** [comment]
I tryed to open the boot with aik-linux tool boot it fails,
But in hex editor we can see what the image is signed with a new singature called SEANDROIDENFORCESignerVer03,

That's what I found there:
`SEANDROIDENFORCESignerVer0336570698RG996BXXU1ATLD20201208204624SM-G996B_EUR_XX_EKEY0SRPTG24B001SRPTG24B001usrfrpmrkboot.img`

And later there is an AVB signature there:
`AVB0@  ���avbtool 1.1.0`

**Comment by m8980** [comment]
I was able to run a test built TWRP. So i pulled some log files and the /cache folder.

Maybe they can help.

[dmesg_S21U_G998BXXU1AUB6_Exynos_1.log](https://github.com/topjohnwu/Magisk/files/5975588/dmesg_S21U_G998BXXU1AUB6_Exynos_1.log)
[dmesg_S21U_G998BXXU1AUB6_Exynos_2.log](https://github.com/topjohnwu/Magisk/files/5975589/dmesg_S21U_G998BXXU1AUB6_Exynos_2.log)
[recovery_S21U_G998BXXU1AUB6_Exynos_1.log](https://github.com/topjohnwu/Magisk/files/5975590/recovery_S21U_G998BXXU1AUB6_Exynos_1.log)
[recovery_S21U_G998BXXU1AUB6_Exynos_2.log](https://github.com/topjohnwu/Magisk/files/5975591/recovery_S21U_G998BXXU1AUB6_Exynos_2.log)
[cache_S21U_G998BXXU1AUB6_Exynos_1.zip](https://github.com/topjohnwu/Magisk/files/5975592/cache_S21U_G998BXXU1AUB6_Exynos_1.zip)
[cache_S21U_G998BXXU1AUB6_Exynos_2.zip](https://github.com/topjohnwu/Magisk/files/5975593/cache_S21U_G998BXXU1AUB6_Exynos_2.zip)

**Comment by m8980** [comment]
issue is fixed with latest canary 21409. Thanks
