### ISSUE TITLE
Unable to patch boot.img

### ISSUE THREAD

**Issue by Jon8RFC** [topjohnwu/Magisk#3811]
Pixel 5 on January 2021 patch.  Unable to patch February 2021 boot.img on Magisk 21407

Copying image to cache
Installation failed

I looked at the app permissions and there are no permissions requested.

[magisk_log_2021-02-02T06_37_17Z.log](https://github.com/topjohnwu/Magisk/files/5911147/magisk_log_2021-02-02T06_37_17Z.log)
[logcat_02-02-2021_06-32-59.txt](https://github.com/topjohnwu/Magisk/files/5911148/logcat_02-02-2021_06-32-59.txt)
![Screenshot_20210202-064011](https://user-images.githubusercontent.com/12204953/106601797-b03c4c80-6521-11eb-8eff-da3827d8df4c.png)
![Screenshot_20210202-064426](https://user-images.githubusercontent.com/12204953/106602251-59834280-6522-11eb-9235-d9b920bcc2db.png)

**Comment by Jon8RFC** [comment]
Unhiding magisk was the solution to letting it patch.  Hiding magisk again caused it to fail again.

**Comment by SmallEngineMechanic** [comment]
I had the exact same issue in my Pixel 3, my solution was to use an older patched image (not recommended) and I ran `fastboot boot oldmagisk.img` then direct installed from Magisk once i booted from that older image
It seems to only be an issue with patching files.

**Comment by tramp20** [comment]
> 
> 
> Unhiding magisk was the solution to letting it patch (storage permissions issue?). Hiding magisk again caused it to fail again.

This did not help on my Sony Z1c with LOS 17.1: the boot.img was patched but Magisk shows as N/A :-(

**Comment by Lishoo** [comment]
After magisk update I had the issue, disabling storage permission, and then enabling solved the problem.

**Comment by Jon8RFC** [comment]
> > Unhiding magisk was the solution to letting it patch (storage permissions issue?). Hiding magisk again caused it to fail again.
> 
> This did not help on my Sony Z1c with LOS 17.1: the boot.img was patched but Magisk shows as N/A :-(

Well, I specifically patched a boot.img file, I didn't patch directly.  You could try patching a boot.img file when unhidden and see if that works for you.  I didn't even try patching directly, because I never do that with Android monthly security updates, or else I run the risk of temporarily invalidating google play services device certification and getting gpay cards removed.

**Comment by SmallEngineMechanic** [comment]
> > > Unhiding magisk was the solution to letting it patch (storage permissions issue?). Hiding magisk again caused it to fail again.
> > 
> > This did not help on my Sony Z1c with LOS 17.1: the boot.img was patched but Magisk shows as N/A :-(
> 
> Well, I specifically patched a boot.img file, I didn't patch directly.  You could try patching a boot.img file when unhidden and see if that works for you.  I didn't even try patching directly, because I never do that with Android monthly security updates, or else I run the risk (nuisance) of temporarily invalidating google play services device certification and getting gpay cards removed.

interesting I have never run across that issue 
but I typically do patch boot.img for monthlies but I had to do it this way this time

**Comment by DrSeussFreak** [comment]
Pixel 4XL, my fix was to change the update channel from Canary to Beta and then back

**Comment by zgfg** [comment]
> Unhiding magisk was the solution to letting it patch (storage permissions issue?). Hiding magisk again caused it to fail again.

Same problem on Xiaomi Mi 9T, A11

When Magisk Manager is hidden (actually, why Settings says Hide Magisk Manager when the app is now integrated with Magisk and it is now called magisk app?), every time patching fails
[magisk_install_log_2021-02-03T21_22_00Z.log](https://github.com/topjohnwu/Magisk/files/5921276/magisk_install_log_2021-02-03T21_22_00Z.log)

**Comment by osm0sis** [comment]
Fixed in f37e8f4
