### ISSUE TITLE
Compatible with the old root execution method

### ISSUE THREAD

**Issue by RainThings** [topjohnwu/Magisk#3813]
Some applications are not compatible with the new magisk root, should you consider compatibility, such as ES file explorer or other applications.  Thank you!

**Comment by RainThings** [comment]
> Some applications are not compatible with the new magisk root, should you consider compatibility, such as ES file explorer or other applications. Thank you!

The above content is translated by a translator, the meaning may not be accurate, please forgive me.

**Comment by Lishoo** [comment]
Just checked what do you mean but root work in ES file explorer
![Screenshot_20210203-135727](https://user-images.githubusercontent.com/1045996/106750479-304cda00-6628-11eb-9caa-e1c12a855caa.png)
![Screenshot_20210203-135606](https://user-images.githubusercontent.com/1045996/106750484-30e57080-6628-11eb-876c-45bb6945e39b.png)
