### ISSUE TITLE
Compatible with the old root execution method

### ISSUE THREAD

**Issue by RainThings** [topjohnwu/Magisk#3814]
Some applications are not compatible with the new magisk root, should you consider compatibility, such as ES file explorer or other applications. Thank you!

Download this application here
https://disk.ano404.top/ES%E6%96%87%E4%BB%B6%E6%B5%8F%E8%A7%88%E5%99%A8_4.2.4.2.1.apk

**Comment by RainThings** [comment]
I have caused misunderstanding, I am very sorry.
Below are more details on this issue.
![IMG_20210203_213533](https://user-images.githubusercontent.com/61218971/106754495-01565880-6668-11eb-969f-17e60fa770eb.jpg)
The app tried to use the old request method, but this caused it to have this problem.

**Comment by topjohnwu** [comment]
There is nothing to fix here. The app developer is responsible for updating its app
