### ISSUE TITLE
Bootloop on Android 9 in recovery without ramdisk

### ISSUE THREAD

**Issue by unpackerR** [topjohnwu/Magisk#3817]
Bootloop on Hafury A7 after flashing patched recovery.img.

The official firmware includes a "ramdisk.img" and "ramdisk-recovery.img" file even though it shows "Ramdisk **No**" in Magisk manager. Is this normal?

[recovery_and_recovery_patched.zip](https://github.com/topjohnwu/Magisk/files/5922563/recovery_and_recovery_patched.zip)

**Comment by osm0sis** [comment]
The boot.img doesn't have a ramdisk, it's separate as a ramdisk.img as you said. Have you tried patching the ramdisk.img instead of ramdisk-recovery.img?

**Comment by Wizard254** [comment]
> Bootloop on Hafury A7 after flashing patched recovery.img.
> 
> The official firmware includes a "ramdisk.img" and "ramdisk-recovery.img" file even though it shows "Ramdisk **No**" in Magisk manager. Is this normal?
> 
> [recovery_and_recovery_patched.zip](https://github.com/topjohnwu/Magisk/files/5922563/recovery_and_recovery_patched.zip)

Have come across this, if your device has an A-Only Partition system, but supports System_as_root. You therefore need to patch the stock boot.img file, with Magisk Manager recovery mode deselected. Leave the recovery files alone.

**Comment by topjohnwu** [comment]
This is a non standard partition layout that Magisk will not support
