### ISSUE TITLE
Issues with Update channel in Canary v21407

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#3818]
If I change the Update channel to Stable, it will show as the 'latest Manager' 21400 (which is not quite correct - 21400 is the latest Magisk but not Magisk Manager version for Stable)
![IMG_20210204_094155](https://user-images.githubusercontent.com/51943147/106866947-57111c00-66cd-11eb-8e60-7f84dd341135.jpg)

Anyway, when I try then to install Manager - it fails with package parsing error (frankly, I didn't expect that downgrading 'Manager' app could work)
![IMG_20210204_094045](https://user-images.githubusercontent.com/51943147/106867012-6abc8280-66cd-11eb-884d-2c1e0db2fa6a.jpg)

But more important, image can be still patched, but instead of patching with that 21400 (Stable) it patches again with my installed 21407 Canary
![IMG_20210204_094008](https://user-images.githubusercontent.com/51943147/106867169-917ab900-66cd-11eb-86bc-de1b3f868039.jpg)

Before the merge of Magisk and Manager it was perfectly possible to patch an older Stable Magisk from Canary Manager (or vice versa), etc

**Comment by topjohnwu** [comment]
In the new model, there is no "app" version anymore. And the channel has nothing to do which version you installed
