### ISSUE TITLE
In TWRP cannot install module after installing Magisk 21407 zip

### ISSUE THREAD

**Issue by gossbill** [topjohnwu/Magisk#3819]
Magisk 21407
Android 11 (unofficial Los 18.1)
OnePlus 3T

When I do a clean rom install I flash Magisk followed by my module.
But when I flash Magisk 21407 (APK renamed to zip) followed by my module, the module fails to install due to a failure in mounting system.

If I reboot TWRP, I can install the module as long as I don't flash Magisk.

I've attached two log files.
Recovery1.log: Magisk is already installed and I can flash Magisk again successfully, but flashing Magisk again (in the same TWRP session) fails due to mounting issues.

Recovery2.log: Magisk is already installed and I can successfully install my module (done twice). I can also install Magisk but after that installing the module fails.

I've also attached a copy of my module.
[recovery1.zip](https://github.com/topjohnwu/Magisk/files/5928308/recovery1.zip)
[recovery2.zip](https://github.com/topjohnwu/Magisk/files/5928310/recovery2.zip)
[MyMods-los-18.1-intSD-210202n.zip](https://github.com/topjohnwu/Magisk/files/5928313/MyMods-los-18.1-intSD-210202n.zip)

**Comment by topjohnwu** [comment]
This is a bug in many custom recoveries, no way around that

**Comment by gossbill** [comment]
Would you mind clarifying what the problem is? Because Magisk 21.4 doesn't have the problem of leaving /system in a busy state and neither does OpenGapps.
What is Magisk 21407 doing that causes /system to be left in an unmountable state? 
Lines from recovery log when trying to install after 21407:
mount: mounting /dev/block/sde20 on /system failed: Device or resource busy
! Cannot mount /system
>
