### ISSUE TITLE
Repacking with random package is not working.

### ISSUE THREAD

**Issue by SohailRaheman** [topjohnwu/Magisk#3822]
Repacking with random package is not working. A message is popping after repacking "re-launch the app" and the manager is not opening. :(
I am on Android 10, Device: OnePlus 3
![Screenshot_20210206-085435__01](https://user-images.githubusercontent.com/38825540/107108260-b05b8580-685c-11eb-9c1b-559abb3a6a8b.jpg)

**Comment by oldman20** [comment]
![Screenshot_20210206-164530_One UI Home](https://user-images.githubusercontent.com/39668756/107115836-dc4d2a00-68a1-11eb-9ea2-107ce8e40c68.jpg)
Same issue on Note 9 N960F android 10 drketan rom. And this issue looping!
![Screenshot_20210206-164514](https://user-images.githubusercontent.com/39668756/107115824-cdff0e00-68a1-11eb-893e-e7400f9aa97d.jpg)

**Comment by topjohnwu** [comment]
No logs, no fix

**Comment by githtz** [comment]
Sam problem here. What logs are helpful? Logcat?
