### ISSUE TITLE
Magisk Manager does not display any installed modules

### ISSUE THREAD

**Issue by peasoft** [topjohnwu/Magisk#3823]
I installed some modules with TWRP, but Magisk Manager does not display any modules I installed. There is a file named 'disable' in /data/adb/modules/* , I delete it, but after I restart the phone, the file is still here.
My phone's Android version: 5.1
Magisk version: 21.4(21400)
Magisk Manager version: 8.0.7(4834)(15)

**Comment by osm0sis** [comment]
Does your twrp decrypt data correctly?
