### ISSUE TITLE
Lenovo M10 HD 2nd Gen  X306F boot loop if boot.img is patched - android 10

### ISSUE THREAD

**Issue by tkalfaoglu** [topjohnwu/Magisk#3832]
I recently installed magisk manager and extracted the boot.img from tb-x306f_rf01_200926 upon doing a fastboot flash boot magisk_patched.img , the machine goes into a boot loop.
Am I doing something wrong?

**Comment by Didgeridoohan** [comment]
First - are you using the latest Canary releases (21408 as of writing this). There's been some recent commits that might help with broken patched boot images on some systems.

Second - Did you read the "Read before opening issues" text when you opened the issue? Providing logs and possibly your boot image is also something that's needed or your issue will likely be closed due to lack of details.

**Comment by tkalfaoglu** [comment]
Many thanks. I installed canary, and saved the install log. The device is brand new -- arrived yesterday. I would love to assist please let me know how else I can help. 

- Device platform: arm64-v8a
- Installing: 721dfdf5 (21408)
- Copying image to cache
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [9349522]
RAMDISK_SZ      [795276]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [102141]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-07]
PAGESIZE        [2048]
NAME            []
CMDLINE         [bootopt=64S3,32N2,64N2 buildvariant=user]
CHECKSUM        [7a65509dd6c537b3354109ef77322804828b2724000000000000000000000000]
KERNEL_DTB      [102077]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
- Unpacking boot image
Loading cpio: [ramdisk.cpio]
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [dtb]
Loading dtbs from [kernel_dtb]
Patch @ 012E8284 [736B69705F696E697472616D667300]->[77616E745F696E697472616D667300]
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [9349522]
RAMDISK_SZ      [795276]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [102141]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-07]
PAGESIZE        [2048]
NAME            []
CMDLINE         [bootopt=64S3,32N2,64N2 buildvariant=user]
CHECKSUM        [7a65509dd6c537b3354109ef77322804828b2724000000000000000000000000]
KERNEL_DTB      [102077]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
Repack to boot image: [new-boot.img]
HEADER_VER      [2]
KERNEL_SZ       [9353555]
RAMDISK_SZ      [1282708]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [102141]
OS_VERSION      [10.0.0]
OS_PATCH_LEVEL  [2020-07]
PAGESIZE        [2048]
NAME            []
CMDLINE         [bootopt=64S3,32N2,64N2 buildvariant=user]
CHECKSUM        [d17d651f9e8530bbe01157ff2b072d76b6a5f4e3000000000000000000000000]

****************************
 Output file is written to 
 /storage/emulated/0/Download/magisk_patched_kLjPW.img 
****************************
cp: can't preserve ownership of 'busybox': Operation not permitted
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
- All done!

**Comment by tkalfaoglu** [comment]
I have been unable to get logcat to work during boot to see why it was looping - because I don't know how to do it on a non-rooted device. If you'd like the logcat logs, please let me know how to obtain them.

**Comment by tkalfaoglu** [comment]
This is the boot image that the tablet uses..

[boot.zip](https://github.com/topjohnwu/Magisk/files/5964818/boot.zip)

**Comment by osm0sis** [comment]
Looks like a normal hdr v2 avb v2 boot.img, looks like 2SI and the ramdisk contains init, fstab.mt6765 and fstab.mt8768

**Comment by tkalfaoglu** [comment]
Many thanks. What do you suggest I try? It just bootloops

**Comment by osm0sis** [comment]
No idea, just doing a basic inspection for when topjohnwu can eventually get to it in case it rings any bells.

**Comment by chuntera** [comment]
I encountered similar issue for lenovo tab10 hd 2nd gen (x306f) when patching boot image with MagiskManager 8.07.
Unfortunately I didn't capture the Magisk log before I did a device reset.  I was using latest Lenovo image "TB_X306F_S100134_210120_BMP".

**Comment by chuntera** [comment]
Possibly need to [update vbmeta](https://forum.xda-developers.com/t/seeking-advice-on-rooting-smart-tab-m10-fhd-plus-2nd-gen.4080371/post-83969725) which is android ["verified boot"](https://source.android.com/security/verifiedboot/avb)

**Comment by tkalfaoglu** [comment]
THANK YOU!

sudo fastboot --disable-verification flash vbmeta vbmeta.img

Fixed the problem and the machine is rooted without any ill effects..
