### ISSUE TITLE
New Safetycheck package in Google Play Services

### ISSUE THREAD

**Issue by UnicornsOnLSD** [topjohnwu/Magisk#3843]
Google Play Services has a new thing called com.google.android.gms:snet, which isn't currently being MagiskHidden by default. When not hidden, basicIntegrity fails. With it hidden, Safetynet passes fine. Should this new service be added to the default hide list, along with gms.unstable?

My Google Play Services version is Version 21.02.14 (150400-352619232)

![Screenshot_20210212-045657_Manager~2](https://user-images.githubusercontent.com/44349936/107732330-ffd40280-6cef-11eb-9847-16380c2666e4.png)

**Comment by zgfg** [comment]
I just checked, I also have it at the bottom but it was not checked-in and I'm still passing SafetyNet

Xiaomi.eu 21.2.3, A11
