### ISSUE TITLE
A/B OTA progress?

### ISSUE THREAD

**Issue by WimVDK** [topjohnwu/Magisk#3849]
Initially i thought it was something with my device (Pixel 3XL) but i've only just now found out (found the twitter post by @topjohnwu moments ago) that the option to "flash to inactive slot" was temporarily disabled due to google making changes to the OTA (or the procedure). So i'm wondering (forgive me if this has been asked before) if there has been any progress made on that part to re-enable that functionality, or if it will be coming back at all in general.

Until then is downloading the factory image, extracting the boot.img file and patching it and then flashing the factory image (and removing the -w flag) the only way to update and keep root?

**Comment by topjohnwu** [comment]
No progress on that, unless someone else is willing to contribute

**Comment by WimVDK** [comment]
I'd be happy to contribute in a way of testing builds, but coding is beyond my skill set. Do you have plans of eventually getting this to work again (don't care if for example its 6months down the road before you even look at that again). Just to get an idea of this.

**Comment by real-or-random** [comment]
As long as this is not solved, I think it would make sense to update https://topjohnwu.github.io/Magisk/ota.html and expand the docs there/remove the content. The only note is still the link to twitter which is about a year old and I guess this is why people are asking here.
