### ISSUE TITLE
Google Chrome Beta Can't result in MagiskHide

### ISSUE THREAD

**Issue by zpcol** [topjohnwu/Magisk#3852]

**Comment by Haus3master** [comment]
Since, Chrome is just a webview provider, so, it won't require any Magisk hide. Of root detection is added at any point, the developers of Magisk will add it, until then, hide rest of your apps. 
This issue sums it up entirely

https://github.com/topjohnwu/Magisk/issues/595

**Comment by zpcol** [comment]
so the props module doesn't work on chrome?

**Comment by Didgeridoohan** [comment]
Github issues aren't for general troubleshooting, but for reporting bugs. If you need help to get something working it's better to post on XDA. Please close this...
