### ISSUE TITLE
magisk 21.4 system_root read only in android 10

### ISSUE THREAD

**Issue by spaceuser-0** [topjohnwu/Magisk#3857]
in my phone xiaomi redmi note 9 merlin dont have partition "system.img" but i have partition "super.img". I think that's why the "root system" is read only.  is there a solution to the system_root read only problem?

**Comment by pndwal** [comment]
This is not a Magisk problem.

All recent devices Launched W/ Android 9 or later have new dynamic/logical partition scheme.

**Comment by zgfg** [comment]
You can read Magisk docs to see how to use Systemless root mechanism (use Magisk to dynamically mount your wanted changes to your System (as Root)

All new Magisk modules do that, that is also how e.g. Systemless hosts assures that AdAway writes to the /data/adb/modues/hosts/system/etc/hosts file and Magisk then mounts that file over /system/etc/hosts on each reboot

**Comment by trying89** [comment]
> You can read Magisk docs to see how to use Systemless root mechanism - using Magisk to dynamically mount your wanted changes to your System (as Root)
> 
> All new Magisk modules do that, that is also how e.g. Systemless hosts assures that AdAway writes to the /data/adb/modues/hosts/system/etc/hosts file while Magisk then mounts that file over /system/etc/hosts on each reboot

link address：https://topjohnwu.github.io/Magisk/guides.html#the-system-folder ，magisk modules.
