### ISSUE TITLE
Google login problems, when Gapps is used as a magisk module

### ISSUE THREAD

**Issue by wahyu6070** [topjohnwu/Magisk#3859]
i made gapps into magisk module, it caused google login problem, all permissions are correct but it still problematic.
https://github.com/wahyu6070/litegapps

maybe you can try litegapps yourself to find out the error
https://wahyu6070.github.io/litegapps   (install magisk module version)

maybe someone who knows magisk can fix this

**Comment by topjohnwu** [comment]
Ask the module developer for support
