### ISSUE TITLE
TAN2go app detects rooted device now -> can Magisk hide against detection again?

### ISSUE THREAD

**Issue by ScrambledBrain** [topjohnwu/Magisk#3870]
Hi,

since version 2.7.1 from end of January of app TAN2go [com.starfinanz.mobile.android.dkbpushtan] the app now detects my [Magisk] rooted device OnePlus 7T.

I already tried: deinstall app, install app, MagiskHide the app again, start the app afterwards.

The app redirects now everytime to a website after each start, where it states, that the app could not be started for example because of a rooted device etc.

So, could someone check the TAN2go app, how it detects the rooted device and improve the MagiskHide feature? ;D

Thanks in advance.

Info:
- Magisk v21.4
- Magisk Manager v8.0.7 [already re-packed to a random apk]
- MagiskHide enabled

**Comment by Lishoo** [comment]
I confirm that on latest canary build the problem persists (21410) MagisHide Enabled and Magisk re-packed with custom name.

**Comment by ScrambledBrain** [comment]
OEM unlock is needed to change the bootloader.
This could be possible, that it checks OEM unlock :/
But maybe it checks something else.
Is it possible, that somebody finds out, what it checks?
I'm no developer at all and wouldn't know, where or what to I would have to investigate.

**Comment by github-nic** [comment]
2.7.1 working for me following [this](https://www.elcombri.de/dkb-tan2go-mit-visa-secure-trotz-root-auf-android-geraeten-in-2020/) tutorial on rooted Wileyfox Swift with Magisk Canary Build 21410. Hide enabled, Manager repacked.

**Comment by osm0sis** [comment]
Doesn't sound like a regression on Magisk's side.

**Comment by 0x23marco** [comment]
> Doesn't sound like a regression on Magisk's side.
> 
> Sounds like there's still a working method above. 👍
> 
> Also #1152. 😉

Yeah of course there's a way to work around this issue but not with current magisk canary installed.
As described you have to use additional software like "island" than it works...
It's s a regression on Magisk side!

**Comment by ScrambledBrain** [comment]
Yeah, it seems, that more and more apps detect rooting in some way, which makes Magisk not useful anymore.
Hopefully somebody can find the way, how these apps detect rooting and Magisk can hide against this detection.
Especially banking apps currently seem to have new detection methods.

**Comment by osm0sis** [comment]
Magisk's not useful anymore? So sorry you have root still and a systemless modification framework. 🙄
