### ISSUE TITLE
Bug in util_functions.sh mount_apex function

### ISSUE THREAD

**Issue by gossbill** [topjohnwu/Magisk#3871]
Magisk 21410 (and previous versions of the new format)
Recovery log attached.
[recovery.zip](https://github.com/topjohnwu/Magisk/files/6013959/recovery.zip)

Line 333 of util_functions.sh (in function mount_apex) currently reads:
  DEST=/apex/$(strings apex_manifest.pb | head -n 1)
It should read:
  DEST=/apex/$(strings $APEX/apex_manifest.pb | head -n 1)

This results in warnings in the the recovery logs saying:
  strings: apex_manifest.pb: No such file or directory
and the directories under /apex not to be mounted properly: 
 - Mounting /apex/
instead of:
- Mounting /apex/com.android.adbd

Note, correcting the code also fixes the issue reported in issue #3819.

**Comment by osm0sis** [comment]
Hi Bill! Care to submit a Pull Request?

**Comment by gossbill** [comment]
I've never used GitHub so I have no idea how to go about creating a Pull Request. I'd be quite happy if you or anybody else would do that.
My interest is in getting the problem fixed, irrespective of who found the solution. 😊
