### ISSUE TITLE
[BUG] since Magisk 21.0. dalvik-cache arm64 Problem / permissions?

### ISSUE THREAD

**Issue by dasTohsy** [topjohnwu/Magisk#3877]
Hello. Sorry, my english is extream bad. So i use often google translate.
if my bugreport ist not correct, sorry. reading the english description is hard for me and i not understood all.
please tell me, if i do something wrong with this report, so i can to it better next time.

sorry, i can show in windows console "adb logcat", but i dont know how i can save it an to what timepoint.
if i have the "complete error" with riru and edexposed, i cant log in android, because the PIN works not if i have the issue. so i dont know, what i must du, to help you to find the issue.

Some of us have a problem with "edexposed" and "dalvik-cache/arm64".

after test al lot of combiantions of magisk, riru core and riru edexposed i mean i found the problem exist in Magisk since Version 21.0.
version 20.4 works well, but 21.0 and all new magisk have this problem.

Plese show here:
https://github.com/ElderDrivers/EdXposed/issues/832

if magisk an edxposed is installed, after delete dalvik cache, the files in arm64 not recreated. 
without riru and edxposed the error is not so hard, but exists. i reproduced an error with the app "root browser" from jummy.
if i go into folder "dalvik-cache/arm64" the app crashes EVER after second. only ths folder an only with magisk 21.0 and newer.

i mean, other error that i have longer, comes from this problem.

i use "cat logcat" to find the problem (sorry, i not a android professional user, i not know linus good).
the error that i found, you found if you use the link to edxposed issue.

logcat says, there are problems with the "permissioins".

please tell me, if i do something wrong with this report, so i can to it better next time.

greetings from old germany.
Toshy

**Comment by dasTohsy** [comment]
2.
hmm... if i be at android loginscreen (cant enter my pin) i use adb:
adb shell
then
ls
show first picture.
![grafik](https://user-images.githubusercontent.com/53551490/108612864-a5702b80-73ec-11eb-81a4-e2c8df44db90.png)
adb shell ls show this in 2nd picture
![grafik](https://user-images.githubusercontent.com/53551490/108612871-b4ef7480-73ec-11eb-9d30-23e8cc48fc7b.png)

is this normal? i never the this characters at adb shell

**Comment by topjohnwu** [comment]
Please do not report bugs with Edxposed installed

**Comment by LoneDev6** [comment]
Found the cause of this issue:
https://forum.xda-developers.com/t/closed-dev-magisk-canary-channel-bleeding-edge-builds.3839337/page-47#post-79074070

**Comment by LoneDev6** [comment]
I think it's an actual bug of Magisk since I uninstalled EdXposed, uninstalled Magisk and still got the error.
The problem disappeared only after a downgrade to a version before that commit https://github.com/topjohnwu/Magisk/commit/081074ad9d5c02e589f265373c0dfa867c9eeaff

**Comment by kobsmey** [comment]
This issue still exist in Magisk 24.1 when zygisk is enabled. Any fix please?

**Comment by encap** [comment]
Any solution? Still broken 25.2
