### ISSUE TITLE
[REQUEST] Support system_ext

### ISSUE THREAD

**Issue by androidacy** [topjohnwu/Magisk#3882]
As far as I can tell in the docs, and from my experience with magisk module development, only /system, /vendor, and /product are supported. 

However, as newer devices are shipping with a system_ext partition, it seems prudent for Magisk to also support this.

My current test device (OnePlus 7T) stores it's fonts, some framework jar files, and quite a bit of it's bloatware in /system_ext.

The implementation is unclear, because either devices have this partition or they don't: there's no /system/system_ext like with vendor or product. My proposed solution would be to transparently mount system_ext into system on devices without the actual partition, with either the root folder as $MODPATH/system_ext (makes more sense as it should never be under /system on an actual device) or $MODPATH/system/system_ext (for module file containment).

**Comment by osm0sis** [comment]
Already supported for nearly a year: https://github.com/topjohnwu/Magisk/commit/8ca5a048d6c5f276ae57e2f408d057e8dfcbbb5a

**Comment by osm0sis** [comment]
And this will handle the documentation issue, since you're right about there being no mention of it currently, which is in error: https://github.com/topjohnwu/Magisk/pull/3883

**Comment by androidacy** [comment]
Oh, thanks very much!
