### ISSUE TITLE
since v22 : Cts Profile on mi8 does no longer pass

### ISSUE THREAD

**Issue by Catfriend1** [topjohnwu/Magisk#3884]
since v22 : Cts Profile on mi8 does no longer pass

how can i downgrade?

it passed on all stables before

**Comment by Didgeridoohan** [comment]
This is not the place for those kind of posts (you've got XDA for that). But, just try toggling MagiskHide off and on (unless it's off in which case you should turn it on).

If you still can't get things working you've got lots of info on how to solve it here:
https://www.didgeridoohan.com/magisk/MagiskHide#hn_SafetyNet

And then you can close this...

**Comment by Catfriend1** [comment]
It was on , turned off and on - no luck.

**Comment by Didgeridoohan** [comment]
@Catfriend1 Then you can check the link I gave you to see if there's anything there that can help you figure things out.

**Comment by Catfriend1** [comment]
Solution: https://androidfilehost.com/?fid=17248734326145715358 and https://xiaomi.eu/community/threads/tutorial-working-fix-for-safetynet-cts-profile-failed.59384/page-2 and https://drive.google.com/file/d/1-4lPgS7Fky49b8eN7EIPuxjIsJlC4ETh/view

**Comment by Didgeridoohan** [comment]
@Catfriend1 Yes, that was covered in the link I posted... In there you'll even find a link to the [XDA thread](https://forum.xda-developers.com/t/magisk-module-universal-safetynet-fix-1-1-0.4217823/) for that module, with up-to-date versions of it.

**Comment by ghost** [comment]
please delete issue
