### ISSUE TITLE
DM-Verity check s21 vs a51

### ISSUE THREAD

**Issue by zSN4KEz** [topjohnwu/Magisk#3887]
Good day,

Recently rooted my a51 and at first got a dm failed msg. Luckily there was a dm disable zip for the device. However, I want to root my s21 now and I am not sure if it will fail the dm check on the new canary magisk on my s21. Kindly advise if the new version of magisk does indeed disable the dm check?

**Comment by topjohnwu** [comment]
S21 is tested to work with Magisk out of the box
