### ISSUE TITLE
Cannot Select and Patch a File within Magisk App

### ISSUE THREAD

**Issue by jparnell8839** [topjohnwu/Magisk#3896]
Phone: Pixel 4 XL
OS: Android 11 2021-02-05
Magisk Version(s): 21.4 / 22.0

Steps:

1. Download factory image from Google
2. Extract image from zip
3. Extract boot.img from image zip
4. adb push boot.img to /storage/emulated/0/boot.img
5. Open Magisk app. Select Install → Select and Patch a File → select boot.img

Results: Cannot proceed. "LET'S GO →" to initiate patching is greyed out and unselectable.

Expected results: start patching boot.img

**Comment by OAJJAIN** [comment]
I too have a similar issue on OnePlus 6 A10 running custom rom. I am on the latest magisk canary.
Haven't been able to install any zip for the last two canary updates.
The steps I followed were:
1. Open Magisk app
2. Navigate to modules.
3. Clicked on install from storage
4. Choose the zip file 
Now the zip should have have flashed but there the black screen that usually shows installing zip didn't come, like it crashed or something.

**Comment by maxweisspoker** [comment]
Just commenting that this happened for me, and the fix was to reboot after installing the new Manager app. System was still on 21.4, and reboot worked fine. Then "Let's Go" worked as expected.

However, I should note that I found several patched boot images, which seem to indicate that "Let's Go" did in fact work when I clicked on it previously, but it just didn't show the screen or give any indication that it was working.

So my advice is to check your Download folder and see if you have patched images there already. And alternatively, reboot and then try it.

**Comment by jparnell8839** [comment]
> Just commenting that this happened for me, and the fix was to reboot after installing the new Manager app. System was still on 21.4, and reboot worked fine. Then "Let's Go" worked as expected.
I wish I could say the same for me, but it didn't. I even cleared data, uninstalled, downloaded fresh apk, install, restart, and it still doesn't work for me. The "Let's Go →" link is still greyed out and not selectable after choosing boot.img.

**Comment by KaMyKaSii** [comment]
That seems to be one of the limitations of Android 11 on what apps can access in internal storage, doesn't it? Try to move the img/zip file to /storage/emulated/0/Android/data/(Manager package name) and see if it works by selecting the file from there

**Comment by jparnell8839** [comment]
That's not a bad suggestion, unfortunately it doesn't exactly work out. The built-in Files app supplied by Google that Magisk uses as the file selector doesn't have view into any of the package folders in /storage/emulated/0/Android/data/*

I adb pushed boot.img to /storage/emulated/0/Android/data/com.topjohnwu.magisk/boot.img, and when I select "Select and patch a file", I can get as far as the Android directory, but from there it only lists "media" and "obj" - no access to data.

I agree that it definitely appears to be a permissions issue... one that started with the Feb 05 image.

I also cant use twrp and the recovery image, because twrp doesn't support Android 11 decrypting yet. So I'm dead in the water, and unfortunately it looks like I may have to factory reset to  January patch level and stay there to get root back.

**Comment by osm0sis** [comment]
Try with 22003?

**Comment by jksab** [comment]
Hi there Same Issue
I updated to the canary version and yet nothing

right at opening it
[https://i.imgur.com/4fpoEGW.png](url)

once I select the boot.img
https://i.imgur.com/IwcdEjL.png

**Comment by Swordfishx86** [comment]
Similar Situation here on Android 10 with Magisk bf80b08b (22003):
Install -> Options -> [x] Recovery Mode -> Next
Method -> Select and Patch a File -> [select file] -> goes back to Install

**Comment by topjohnwu** [comment]
Magisk is using stock Android document provider API. Please make sure you are using a properly functioning ROM

**Comment by jparnell8839** [comment]
For what it's worth, this does appear to be a Google issue. While I was on the stock Pixel 4 XL image (which one would assume would be a properly functioning ROM), after applying the April patch level (while still being on the same Magisk version), I could patch the boot image as I could prior to February. So it looks like something wasn't working right on Google's end.
