### ISSUE TITLE
Magisk v22 update moto g6 bricks boot.img

### ISSUE THREAD

**Issue by unkn0wboy** [topjohnwu/Magisk#3897]
Installed update from magisk manager on moto g6 android 9, but get issues to install magisk v22: When restart my phone i got the "fastboot:invalid boot.img" Be careful, i tried to reinstall trought TWRP but got the "Updater process ended with error:1" Now i reflash my system backup. Dah

**Comment by chavocarlos** [comment]
I solved my problem flashing stock boot.img again 
Reboot in TWRP.
Flashed magisk patched boot img again.
Reboot in TWRP.
Flashing Magisk 21.4 again. (Finised OK)
Reboot in TWRP.
Unisntalling Magisk 21.4 (Finised OK)
Reboot in TWRP.
Flashing Magisk 22 (Finished OK)
Fixed

I have an OnePlus 6. Hope helps.
