### ISSUE TITLE
Manager can't update itself

### ISSUE THREAD

**Issue by QkiZMR** [topjohnwu/Magisk#3899]
I'm trying to update Manager (Magisk Hide enabled) and when I try to run Manager it asks me about update
![Screenshot_20210223-212210~2](https://user-images.githubusercontent.com/7574087/108904031-4b56ac80-761e-11eb-87da-3868d47a600e.png)
After tapping Ok, toast "Downloading" shows and then another toast with "Rerun manually Manager" text. Again I'm trying to run Manager and same question as above in loop. How can I update Manager with Magisk Hide enabled?
Magisk version: 21.4 currently installed.
Android version: 9
Device: Moto Z3 Play

**Comment by QkiZMR** [comment]
Ah, shiet. I didn't read release page https://topjohnwu.github.io/Magisk/releases/22000.html. Is there any solution to stop updating process and back to old installed Magisk Manager?

**Comment by jparnell8839** [comment]
> Ah, shiet. I didn't read release page https://topjohnwu.github.io/Magisk/releases/22000.html. Is there any solution to stop updating process and back to old installed Magisk Manager?

You'll have to clear data and uninstall, then download the new apk and install manually. Should work after that.

**Comment by QkiZMR** [comment]
Already tried. Still asking for update.

**Comment by QkiZMR** [comment]
After removing Magisk completly and installing again I was able to update Magisk Manager to newest version. Magisk is still 21.4 but I will pause updates for some time.

**Comment by techIndia-hacker** [comment]
Update to magisk v22 it's perfectly fine and close the issue
