### ISSUE TITLE
Bootloop on Oneplus 8 Pro

### ISSUE THREAD

**Issue by Lycidias93** [topjohnwu/Magisk#3900]
Hello, I got a bootloop after updating my oneplus 8 pro from magisk 21.4 to 22 inside magisk on Android 11. I restored magisk manager before

Flashing stock boot.img did not work

**Comment by chavocarlos** [comment]
I solved my problem flashing stock boot.img again 
Reboot in TWRP.
Flashed magisk patched boot img again.
Reboot in TWRP.
Flashing Magisk 21.4 again. (Finised OK)
Reboot in TWRP.
Unisntalling Magisk 21.4 (Finised OK)
Reboot in TWRP.
Flashing Magisk 22 (Finished OK)
Fixed

I have an OnePlus 6. Hope helps.

**Comment by Lycidias93** [comment]
Thanks, but sadly the OnePlus 8 pro has no twrp for now...

**Comment by techIndia-hacker** [comment]
I have 7t. No bootloop faced. A stable magisk update should not cause these problems.🧐🤨

**Comment by techIndia-hacker** [comment]
Hace u tried flashing the factory build with all the partitions. Were u using a custom kernel previously?

**Comment by Lycidias93** [comment]
Yes, I had Radioactive Custom Kernel installed.
I tried fastboot rom flashing but no luck. (Dead phone after that)
Only MSM unbrick tool brought my phone back

**Comment by techIndia-hacker** [comment]
Yes custom kernels are causing these issues in oneplus. It's because of poor implementation of the custom kernel not a magisk bug
