### ISSUE TITLE
Phone got bricked after installing Magisk App to v22

### ISSUE THREAD

**Issue by winstonma** [topjohnwu/Magisk#3905]
Initially my phone was running Magisk v21 with Magisk Hide. Then when I saw the Magisk notification I installed Magisk v22 App. After the installation and startup of the App, I selected update Magisk v22 and installed Magisk.

However when I reboot my phone, I don't see the company logo (It's Xiaomi Redmi Note 8), which indicates my phone couldn't properly bootup. Then I connected my phone to my laptop, then I tried both `adb` and `fastboot` and both failed.

I would like to see how can I get back to the bootloader mode. It turns out my phone is bricked. I am following the unbricking process. But it is really sad when my phone is bricked in the morning and then I need to wait til I got back home to unbrick the phone as I need to download multiple large files (MIUI, Custom ROM) which my office network is slow.

EDIT: I just realize that I should restore Magisk Manager, as per [release note](https://topjohnwu.github.io/Magisk/releases/22000.html). It turns out I should not press the update button when I saw the Magisk manager update notification.

**Comment by winstonma** [comment]
It turns out that my phone is bricked and I am unbrinking my phone. Seems the wrong procedures can eventually cause my phone into bricked state.

**Comment by winstonma** [comment]
I should not say it is being solved as I only solve the bricking problem but it is still possible that other people would get the phone bricking problem.

**Comment by techIndia-hacker** [comment]
If fastboot is not accessible, it's bad, hard brick

**Comment by v0gler** [comment]
I Just updated my Magisk Manager with Hide via Update notification. Phone wasn't rebooted an Magisk not updated. What should I do now?

**Comment by kayg04** [comment]
@winstonma, hey, I had the exact issue on a Redmi Note 8 Pro. It was a hard brick but I was able to recover by following a tutorial linked in the telegram group for the Redmi Note 8 Pro. I'm sure there's a group for your phone too and the folks over there should be able to help you.

**Comment by techIndia-hacker** [comment]
> I Just updated my Magisk Manager with Hide via Update notification. Phone wasn't rebooted an Magisk not updated. What should I do now?

Did u do the same mistake as the above guy?

**Comment by v0gler** [comment]
> > I Just updated my Magisk Manager with Hide via Update notification. Phone wasn't rebooted an Magisk not updated. What should I do now?
> 
> Clear data and uninstall magisk. Reinstall from official sources. Get hold of ur official boot partition (or anyither as applicable) and select and patch the file.

Full uninstall via App? Which data should I clear?

**Comment by techIndia-hacker** [comment]
Magisk app data

**Comment by v0gler** [comment]
> Magisk app data not data partition

When I clear Magisk Manager App data, backed up Boot.img will be deleted right? So first uninstall via App, Just restore Boot img or Full? And then clear App data via Android settings?

**Comment by winstonma** [comment]
> 
> 
> @winstonma, hey, I had the exact issue on a Redmi Note 8 Pro. It was a hard brick but I was able to recover by following a tutorial linked in the telegram group for the Redmi Note 8 Pro. I'm sure there's a group for your phone too and the folks over there should be able to help you.

Yes I am following [this video](https://youtu.be/wm0UFvjSvVg) to unbrick the phone. Thanks

The main point of opening this issue is not I want to find out how to unbrick the phone (although I really want to know). But it is because I want to let the developer know that some phone got bricked during the update process.

**Comment by techIndia-hacker** [comment]
> > Magisk app data not data partition
> 
> When I clear Magisk Manager App data, backed up Boot.img will be deleted right? So first uninstall via App, Just restore Boot img or Full? And then clear App data via Android settings?

U can restore the backed up partition first. I forgot about the backup

**Comment by Tobbe3108** [comment]
This happened to me as well. However I did restore the app before installing.
I have a OnePlus 6t with OxygenOS 10.3.8

**Comment by winstonma** [comment]
@topjohnwu just wonder if the following options could be considered

- If upgrade is not allowed in hidden version, would it be possible that the hidden magisk wouldn't allow user from installing Magisk
- Also, I really not sure my phone is bricked is caused by Magisk upgrade or hidden magisk
