### ISSUE TITLE
Samsung A50 lost Magisk after latest v22

### ISSUE THREAD

**Issue by bilogic** [topjohnwu/Magisk#3906]
I did the update via direct patching as usual, after rebooting, my device lost root and Magisk. Still able to enter TWRP. Help! Thank you.

**Comment by nitindavis** [comment]
Me too

**Comment by bilogic** [comment]
Thanks, let's hope there is a solution, I don't want to wipe my phone again, restoring data is such a pain.

**Comment by techIndia-hacker** [comment]
I did be that bein Samsung M40 without errors. What is ur os and what steps did u follow

**Comment by bilogic** [comment]
Samsung Android 10.
Just go into Magisk and update. Direct patching.

**Comment by techIndia-hacker** [comment]
Did u install magisk in recovery partition or boot as usual?

**Comment by bilogic** [comment]
For A50, it is installed in recovery.

**Comment by techIndia-hacker** [comment]
U need to boot through recovery then. Did u do that?

**Comment by bilogic** [comment]
Yes of course, as mentioned in the title, my magisk was working until v22, when I lost it after the update.

**Comment by techIndia-hacker** [comment]
Try flashing all stock partitions and then patch the boot.img this time and retry

**Comment by bilogic** [comment]
bro, please... I already said I want to avoid that... I know it will definitely work, but why did the update fail?

**Comment by techIndia-hacker** [comment]
Cause patching recovery in Samsung is not recommended since 2020 September or so. And relax u won't loose ur data if u follow what i said before. Keep in mind flash Home CSE and NOT CSE
