### ISSUE TITLE
[Pixel 5 DP1] failed to load/verify boot images

### ISSUE THREAD

**Issue by tlxxxsracer** [topjohnwu/Magisk#3907]
Patched boot.img of Android 12 DP1. I go to flash and upon rebooting, devices boots immediately into fastboot mode giving the reason of "Failed to load/verify boot images"

**Comment by Demoox** [comment]
Got the same problem on my Mi6. After the reboot the phone boots into fastboot mode and hangs there. No way to exit fastboot, tried rebooting to system through TWRP, but nothing has changed. I'm on Android 10 tho

**Comment by Martina-Neumayer** [comment]
If you're able to go into the TWRP, you need to flash working boot.img for your device/system.
But firstly do a data backup from TWRP, because it is possible that you may lose your data by flashing.

**Comment by QkiZMR** [comment]
> But firstly do a data backup from TWRP, because it is possible that you may lose your data by flashing.
By flashing boot partition?? I think not.

**Comment by Demoox** [comment]
Found the problem. I was not careful during installation, as it says that I have to disable Magisk Hide before updating. I suggest to flash back your boot.img and then use the Magisk App to patch it and flash that instead

**Comment by Martina-Neumayer** [comment]
@QkiZMR I am not 100% sure. Better is to be on the safe side with the backup done ;)

**Comment by QkiZMR** [comment]
That's strange. Flashing boot itself should not wipe data but unlocking bootloader does.

**Comment by tlxxxsracer** [comment]
Please can we keep the issue for the xiaomi device in a separate issue report. Mine specifically states Pixel 5 with android 12 DP1

**Comment by Martina-Neumayer** [comment]
@QkiZMR Yeap it is so. I need to restore normal boot. Read: the locked one. To do so, I need to depack standard stock system image, extract from it the boot.img and flash it to the device. But it will be the locked one. So.. next I need to unlock it again and here my device will reset itself to the factory state. Normally I use TitaniumBackup for backuping my devices in the 1 to 1 mode, but with locked boot and without no root I can't use them.
Here is a next android-dumb-as-hell paradox.

Okay.. let's back on topic. ;)

**Comment by osm0sis** [comment]
Try with 22003?
