### ISSUE TITLE
Wi-fi not turning on after installing magisk 22 through recovery patch

### ISSUE THREAD

**Issue by maruashok** [topjohnwu/Magisk#3909]
On clean flash AOSP ROM i installed magisk through patched recovery as my boot does't support RAMDISK, magisk and root is working fine but i am not able to turn on wi-fi, other things ike mobile data,bluetooth, gps is working fine, if i flash fastboot full package and custom ASOP ROM again without magisk than wi-fi is woking fine,

Note - wifi works fine with v21.4 magisk build

**Comment by techIndia-hacker** [comment]
Specify ur device and OS. Follow the rules. Or else nobody will bother to look at ur problem

**Comment by maruashok** [comment]
Device : Redmi Note 7 Pro
OS : Havoc Os Android 10 Build

**Comment by Displax** [comment]
@maruashok 
You patched and flash wrong img, which not for your ROM build.

**Comment by techIndia-hacker** [comment]
May be retry by patching boot.img

**Comment by bo-skor** [comment]
magisk 22.1 update by automatical. same problem
