### ISSUE TITLE
Samsung Note 3 Android 5.0 lost root after v22.0

### ISSUE THREAD

**Issue by anwar-alsilwy** [topjohnwu/Magisk#3910]
Everything was fine in Magisk 21.4.
But after update to v22.0, I noticed that Magisk root is lost and show's me:
Installed: N/A.
![Screenshot_2021-02-24-07-06-20-1](https://user-images.githubusercontent.com/71539261/108947511-a82f8280-7671-11eb-95af-b586df71e0bd.jpg)

I renamed the .apk file to .zip file, and it flashed successfully on TWRP , BUT root still lost and (Installed: N/A).
I also tried method of (Direct install) but it show's me: installation failed !!!!!
![Screenshot_2021-02-24-07-20-37-1](https://user-images.githubusercontent.com/71539261/108947547-bc737f80-7671-11eb-80f8-c8e0640e0f7b.jpg)

Any suggestions please?

**Comment by techIndia-hacker** [comment]
There is some bug for old signature sceme, keep using 21.4 for now. Also the future magisk versions r generally built for android 10 and above. For ur device there is no meaning for using higher versions. I strongly recommend using v20.4 as it was the most stable one
