### ISSUE TITLE
Magisk v22 update, fastboot bootloop

### ISSUE THREAD

**Issue by CrepeTF** [topjohnwu/Magisk#3913]
Device: OnePlus 6t
Firmware: OxygenOS 10.3.8

### Steps to reproduce
1. Update manager
2. Unhide manager
3. Update magisk to v22

### Details
After the steps above, I have been stuck in a bootloop on the fastboot screen.

**Comment by azio7** [comment]
i have this problem too
1. update lineage yesterday
2. update manager after update lineage
3. until just now,i unhide manager
4. i cant open any apps
5. i reboot my device
Device: xiaomi mix 2s
Firmware: lineage 17.1

**Comment by Sameroz** [comment]
Temporary fix seems to be:
  1. extract the "boot.img" from an existing original ROM on your PC
  2. use fastboot command to flash that original boot.img
  3. reboot to system. Phone should work

You can root again, but use Magisk 21.4. There seems to be something buggy in version 22.0.

**Comment by Martina-Neumayer** [comment]
Or if you can't connect to the PC, use TWRP to flash working boot.img
Sadly.. Some devices are so bricked that they are not recognizable by the PC.

**Comment by martmists-gh** [comment]
It should be noted that not all phones have a boot.img publicly available, and as such need a complete reflash as result.

**Comment by CrepeTF** [comment]
Stock boot image for **OxygenOS 10.3.8**
[boot.img.zip](https://github.com/topjohnwu/Magisk/files/6035382/boot.img.zip)
