### ISSUE TITLE
Uninstaller missing for version 22.0

### ISSUE THREAD

**Issue by nudgegoonies** [topjohnwu/Magisk#3914]
Instead of the uninstaller there is the stubrelease-apk:
https://github.com/topjohnwu/Magisk/releases/tag/v22.0

**Comment by HemanthJabalpuri** [comment]
See this https://topjohnwu.github.io/Magisk/install.html#uninstallation

**Comment by nudgegoonies** [comment]
Thank you very much. Seems like something changed and i have to read through the docs again. With 21.4 it was still there:
https://github.com/topjohnwu/Magisk/releases/tag/v21.4

**Comment by QkiZMR** [comment]
What if your phone is bricked or when you cant open Magisk Manager because of force close?
