### ISSUE TITLE
Spelling mistake in French translation

### ISSUE THREAD

**Issue by mooms06** [topjohnwu/Magisk#3916]
I don't know how to make a PR, but the change is pretty straightforward: change `Restorer` to `Restaurer`. 
The weird thing is the mistake is made in the title  but not in the text below ! (see image).

![image](https://user-images.githubusercontent.com/25405517/108994111-ad092c00-769b-11eb-8133-4febce4961ed.png)

**Comment by etmatrix** [comment]
With this [guide](https://www.dataschool.io/how-to-contribute-on-github/) with can make a PR. The change is very easy, so you can't wrong.

**Comment by mooms06** [comment]
Thank you, but that suppose installing a Git client on my local machine right ?

It's a little bit inconvenient just to change a word...

**Comment by etmatrix** [comment]
You can change file online with github. Try to see this https://docs.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository

**Comment by etmatrix** [comment]
I have done for you, all this from my smartphone with a simple browser.
I think all can contribute to open source project.
