### ISSUE TITLE
Xiaomi Redmi note 7 lavender update to magisk  v22 issue

### ISSUE THREAD

**Issue by kearmau5** [topjohnwu/Magisk#3918]
hi everyone
this is seriously hard to deal with...this new innovation of magisk made every one in issue during updates
could anyone explain the right way to update from 21.4 to 22 without any issue 
the device is getting to fastboot mode and could not boot into system....the boot image is corrupted by this new version 
any way i managed to fix things by restoring to stock boot image file to the device
i use xiaomi.eu stable version with MIUI 12.0.3.0
however i patched to boot image inside the magisk 22 app but still do not want to flash it through ADB 
the developper sais nothing about bootlooping during fastboot/ADB flash
anyway i rolled back to 21.4 waiting for some experience from others 
and btw i can say in the name of 29 same users that this migration from zip file to self apk is USELESS

**Comment by Didgeridoohan** [comment]
It's very likely that the issue with getting stuck in fastboot after updating to v22, that you and many others (me included) have experienced is a fluke caused by certain conditions in the Magisk app causing the boot image to become corrupted (that hopefully have been fixed upstream).

If you now have a successfully patched v22 boot image there should be no problems installing that (you could probably even update from the app). If nothing else you now know exactly how to restore your device if things go wrong again...

**Comment by kearmau5** [comment]
> It's very likely that the issue with getting stuck in fastboot after updating to v22, that you and many others (me included) have experienced is a fluke caused by certain conditions in the Magisk app causing the boot image to become corrupted (that hopefully have been fixed upstream).
> 
> If you now have a successfully patched v22 boot image there should be no problems installing that (you could probably even update from the app). If nothing else you now know exactly how to restore your device if things go wrong again...

I didn't patch boot.img
Why should i go on some complicated commands while i have a custom recovery
I just uninstalled all the magisk garbage remaining and reinstalled it through recovery but this time with the stock boot image

**Comment by Didgeridoohan** [comment]
You did write that you have patched a boot image with v22...
> however i patched to boot image inside the magisk 22 app but still do not want to flash it

And you do not need to go through any complicated commands. I even wrote that you probably even can update from within the Magisk app since many report that the second time they try updating works just fine.

And if you have a custom recovery you can just rename the .apk to .zip and flash it there, just like you say.

I'm not quite sure what it is you're trying to say...

**Comment by techIndia-hacker** [comment]
Magisk v21 and up is for android 11 and up. No point in updating. These are not feature update. Magisk should block updates in incompatible devices

**Comment by kearmau5** [comment]
> You did write that you have patched a boot image with v22...
> 
> > however i patched to boot image inside the magisk 22 app but still do not want to flash it
> 
> And you do not need to go through any complicated commands. I even wrote that you probably even can update from within the Magisk app since many report that the second time they try updating works just fine.
> 
> And if you have a custom recovery you can just rename the .apk to .zip and flash it there, just like you say.
> 
> I'm not quite sure what it is you're trying to say...

Yeah i wrote it at the first time
But then i managedt to go through other option which is better i think

**Comment by techIndia-hacker** [comment]
John doesn't have time to make it compatible for each and every device I guess

**Comment by Didgeridoohan** [comment]
> Magisk v21 and up is for android 11 and above. No point in updating for older devices. These are not feature updates. Magisk should block update in incompatible devices.
> 
> I recommend using magisk 20.4 which was the most stable version for android 9 and older

That's just wrong... Just because A11 compatibility is added it doesn't mean that there aren't changes that benefit all users...

Example from the latest changelog:
- [App] Support hiding the Magisk app with advanced technique (stub APK loading) on Android 5.0+ (it used to be 9.0+)
- [App] Disallow re-packaging the Magisk app on devices lower than Android 5.0

**Comment by kearmau5** [comment]
> Magisk v21 and up is for android 11 and above. No point in updating for older devices. These are not feature updates. Magisk should block update in incompatible devices.
> 
> I recommend using magisk 20.4 which was the most stable version for android 9 and older

Nope
Very wrong mate
If the v22.0 version wasn't worth to updtae we wouldn't make all this conversation

**Comment by Didgeridoohan** [comment]
> The think about making the app a flashable zip made every system to go on brick because magisk has already took the original boot image...so when you go in it corrupt the system's boot image

The combination of Magisk internals and the apk isn't in itself what caused all these issues. It's more likely caused by an unrelated bug that hopefully is fixed already. And even if it is caused by the combination that can also be fixed, so you're probably just gonna have to learn to live with the new combined setup.

**Comment by kearmau5** [comment]
> > The think about making the app a flashable zip made every system to go on brick because magisk has already took the original boot image...so when you go in it corrupt the system's boot image
> 
> The combination of Magisk internals and the apk isn't in itself what caused all these issues. It's more likely caused by an unrelated bug that hopefully is fixed already. And even if it is caused by the combination that can also be fixed, so you're probably just gonna have to learn to live with the new combined setup.

Yeah that's right 
We should repeat the cenario every once i guess

**Comment by gene-pavlovsky** [comment]
I've had the same issue on my LG V30. I've updated Manager to 22.0 and for updating to Magisk 22.0, the instructions seemed to suggest that I should restore the original Magisk app, which I did. After that when I proceeded to install Magisk 22.0, selected the direct method as usual, and clicked to proceed, but nothing happened. I tried a few times. The device didn't reboot, there were no error messages either, just no reaction. I did a manual reboot and got stuck in fastboot mode. I was able to recover by booting into TWRP, then flashing Magisk uninstaller, stock ROM (no wipe), Magisk 22.0 (.apk renamed to .zip), wipe cache/dalvik and reboot.

I haven't had any issues with previous updates, just this time with 22.0. Staying up to date is a good policy generally, but in some cases "if it ain't broke, don't fix it" applies...

**Comment by Didgeridoohan** [comment]
> Is it going to be required to restore original apk before every future update, and then hide the Manager app under a random ID again? Or is it a one time requirement when upgrading from pre-22.0 to 22.0?

It should only be required when updating from pre-v22.0.

**Comment by techIndia-hacker** [comment]
> > Magisk v21 and up is for android 11 and above. No point in updating for older devices. These are not feature updates. Magisk should block update in incompatible devices.
> > I recommend using magisk 20.4 which was the most stable version for android 9 and older
> 
> That's just wrong... Just because A11 compatibility is added it doesn't mean that there aren't changes that benefit all users...
> 
> Example from the latest changelog:
> 
> * [App] Support hiding the Magisk app with advanced technique (stub APK loading) on Android 5.0+ (it used to be 9.0+)

This feature of hiding is a magisk apk feature and not magisk core. U can use magisk v22 app on magisk 20.4 core for stability. As the other guy wrote "if it ain't broke (for android 9 and before), don't fix it"

**Comment by gene-pavlovsky** [comment]
> It should only be required when updating from pre-v22.0.

That's good to hear. And what would be your recommendation regarding future updates? Is there a point to update Magisk core again and again, if it works fine? (I have Android 9). If there is, what is the safest update method?

**Comment by Didgeridoohan** [comment]
> This feature of hiding is a magisk apk feature and not magisk core. U can use magisk v22 app on magisk 20.4 core for stability. As the other guy wrote "if it ain't broke (for android 9 and before), don't fix it"

That was an example... There are many other fixes and features that can benefit other Android versions than 11. But of course, you are free to use whatever release you want (if things are working as you want and you do not need any of the new features or fixes, there is rarely any need to update). I was merely pointing out that your statement that Magisk v21+ is only for Android 11 is wrong.

**Comment by SigmaDolphin** [comment]
Same happened to me when i tried to update to 22.0 on a OnePlus 3T with OOS 9.0.6
Installer corrupted my boot.img as well and I had to download the stock rom to reflash the stock boot.img
patched boot.img using Magisk App and reflashed the patched boot.img and now everything is working fine
Still this gave me the scare of my life because I thought for a moment I had to flash stock rom and lose all my stuff to recover my phone

**Comment by techIndia-hacker** [comment]
> Same happened to me when i tried to update to 22.0 on a OnePlus 3T with OOS 9.0.6
> tried using the Magisk Uninstaller and it didn't help, I kept getting an error when the uninstaller tried to unpack boot.img apprantly the Magisk App corrupted my boot.img and I had to download the stock rom to reflash the stock boot.img
> Patched boot.img using Magisk App and reflashed the patched boot.img and now everything is working fine
> Still this gave me the scare of my life because I thought for a moment I had to flash stock rom and lose all my stuff to recover my phone

U didn't have custom kernel or any other modification installed?

**Comment by SigmaDolphin** [comment]
> 
> And u didn't have custom kernel or any other modification installed?
i was using stock OOS 9.0.6, and the only modification i had was the previous version of Magisk itself

**Comment by techIndia-hacker** [comment]
> > And u didn't have custom kernel or any other modification installed?
> 
> i am using stock OOS 9.0.6, and the only modification i had was the previous version of Magisk itself

In that case u open another issue and not just comment below a redmi device issue. U provide proper details of ur device os and what did u do as in update procedure. Put them according to the rules and John will surely look into it

**Comment by user2w3e** [comment]
> > > Magisk v21 and up is for android 11 and above. No point in updating for older devices. These are not feature updates. Magisk should block update in incompatible devices.
> > > I recommend using magisk 20.4 which was the most stable version for android 9 and older
> > 
> > 
> > That's just wrong... Just because A11 compatibility is added it doesn't mean that there aren't changes that benefit all users...
> > Example from the latest changelog:
> > 
> > * [App] Support hiding the Magisk app with advanced technique (stub APK loading) on Android 5.0+ (it used to be 9.0+)
> 
> This feature of hiding is a magisk apk feature and not magisk core. U can use magisk v22 app on magisk 20.4 core for stability. As the other guy wrote "if it ain't broke (for android 9 and before), don't fix it"

I did just that, getting the same result after the update.  And now I will not touch magisk updates
