### ISSUE TITLE
Can you please reopen #3877?

### ISSUE THREAD

**Issue by dasTohsy** [topjohnwu/Magisk#3919]
hello.

Sorry, my english is bad. so you eventually understood me not correct.
please reopen #3877.

The error becomes more noticeable as soon as edxposed is installed.
In my estimation, the error is also there WITHOUT Edxposed.
It is then difficult to notice. Or it just triggers minor problems.

I also had errors with UNINSTALLED Edxposed. but the problem without edxposed / riru 
but the problems are smaller.
at least I thought.
However, it can be assumed that some longer lasting problems can be traced back to it. (sometime crashed apps after updates)

****The "root browser" e.g. also crashes WITHOUT edxposed and WITHOUT riru as soon as the "arm64" directory is called up. only with this directory there are probably problems.****
--> the only do this since magisk 21.0, not with 20.4 and before.

However, I am therefore also describing the problem in the "edxposed" section, because they may find the error there more quickly. Because the errors are the errors are multiplied. 

If you not wish reopen or if you want to wait the reopen will "edxposed" know the place of problem, its okay. i want only help you. no problem.

greetings Toshy.

**Comment by topjohnwu** [comment]
Please follow the issue template and provide proper info. Complaining on GitHub will not change anything
