### ISSUE TITLE
Samsung S7 Exynos android 8 problem.

### ISSUE THREAD

**Issue by calatorius** [topjohnwu/Magisk#3922]
## READ BEFORE OPENING ISSUES

All bug reports require you to **USE CANARY BUILDS**. Please include the version name and version code in the bug report.

If you experience a bootloop, attach a `dmesg` (kernel logs) when the device refuse to boot. This may very likely require a custom kernel on some devices as `last_kmsg` or `pstore ramoops` are usually not enabled by default. In addition, please also upload the result of `cat /proc/mounts` when your device is working correctly **WITHOUT ROOT**.

If you experience issues during installation, in recovery, upload the recovery logs, or in Magisk Manager, upload the install logs. Please also upload the `boot.img` or `recovery.img` that you are using for patching.

If you experience a crash of Magisk Manager, dump the full `logcat` **when the crash happens**. **DO NOT** upload `magisk.log`.

If you experience other issues related to Magisk, upload `magisk.log`, and preferably also include a boot `logcat` (start dumping `logcat` when the device boots up)

**DO NOT** open issues regarding root detection.

**DO NOT** ask for instructions.

**DO NOT** report issues if you have any modules installed.

Without following the rules above, your issue will be closed without explanation.

**Comment by calatorius** [comment]
I tried all the methods, I patched correctly the boot.img but in my samsung s7 exynos is imposiible to enter in fastboot mode.
If I use adb devices it recognize it but not with fastboot devices. And if i use adb reboot fastboot ir reboot the phonr normally and no enters in fastboot mode so I dont know what to do, I tried with twrp flashing magisk 22.zip and it bricks and need to flash the stock rom again. So I'm in a infinite bucle and dont know what to do

**Comment by etmatrix** [comment]
Have you tried with 

    adb reboot bootloader

**Comment by calatorius** [comment]
yes of course, and the movil reboots at normal mode, no fastboot mode

**Comment by etmatrix** [comment]
I tested with Samsung J3 and works, I don't know S7. Have you tried with manual mode?

**Comment by calatorius** [comment]
which is manual mode?
pressing power+volumen down continue?
it reboot only like adb reboot bootloader.
If i tried to use odin or flashing with twrp the patched boot.img it fails

**Comment by etmatrix** [comment]
On j3 vol-down+home+power, I see on youtube for s7 vol-down+power. If doesn't work something is wrong on your smartphone

**Comment by calatorius** [comment]
OEM is enabled in menu, I think samsung s7 exynos with oreo lost fastboot screen, you can use odin and adb works then fastboot mode is enable but no the screen to use with fastboot command, I see more people has the same problem, but the result is that I cant use magisk 22

**Comment by etmatrix** [comment]
If the bootloader is unlocked with odin you can flash it.
Is there an error on odin when you try to flash?
With odin you can't flash boot.img directly, you must to create a tar file with boot.img.

**Comment by calatorius** [comment]
yes, I patched with both methods , if i with the boot method odin fails, with recovery method it works fine, but after that the movil enter in a infinite boot loop
