### ISSUE TITLE
v22.0 select file to patch open contacts app instead of file manager, so not able to patch anything.

### ISSUE THREAD

**Issue by bikkoism** [topjohnwu/Magisk#3931]
ulcool u2
android 8.1 go
stock rom

This issue is not only on this phone or this specific version of magisk. All magisk just do not open valid app to select file on some phones, so not able to navigate/select boot.img file.

**Comment by zgfg** [comment]
Maybe you have previously used that app instead of the regular File explorer and assigned that app to automatically open all img files.
Then unassign that app

Or install a third party File Manager like MiXplorer

**Comment by Didgeridoohan** [comment]
As above... The Magisk app simply uses the standard Android apis for dealing with files. Check your associations.
