### ISSUE TITLE
Magisk Version 22.0 can not download any zip file

### ISSUE THREAD

**Issue by habibur-098** [topjohnwu/Magisk#3938]
[magisk_install_log_2021-02-26T10:04:43Z.log](https://github.com/topjohnwu/Magisk/files/6047381/magisk_install_log_2021-02-26T10.04.43Z.log)

**Comment by topjohnwu** [comment]
Everything is working perfectly in your logs

**Comment by habibur-098** [comment]
Why I can't root Samsung Galaxy A2 Core?
If the logs are correct.! Then why my device in not being rooted?
