### ISSUE TITLE
Magisk app shows Magisk is not installed despite it's operational (Galaxy Tab S2 Android 7.0)

### ISSUE THREAD

**Issue by randompasser** [topjohnwu/Magisk#3942]
On Canary build 79ee85c0 (22001), the Magisk companion app shows Magisk is not installed despite logcat and magisk.log both indicate it's loaded correctly. Apps and adb shell can invoke MagiskSU as expected but a user cannot revoke existing superuser authorisations nor manage modules and MagiskHide due to the Magisk app not presenting those options.
![Screenshot_20210226-135433](https://user-images.githubusercontent.com/33059426/109263765-cb5b5d00-783e-11eb-93ec-52fce4d92ae4.png)

This issue was replicated on a Galaxy Tab S2 (Android 7.0, Linux 3.10), whose boot.img can be found below.

[boot.img.tar.gz](https://github.com/topjohnwu/Magisk/files/6047784/boot.img.tar.gz)

[magisk.log](https://github.com/topjohnwu/Magisk/files/6047706/magisk.log)

[logcat.log](https://github.com/topjohnwu/Magisk/files/6047698/logcat.log)

**Comment by Didgeridoohan** [comment]
Then you probably have a hidden app that's taking care of superuser management and the app you've taken a screenshot of is just a dummy app at this point..

I suggest you uninstall both and start over. In worst case, delete the /data/adb/magisk.db file to reset.

And after that you can close this issue so it doesn't clutter up the issue tracker.

**Comment by randompasser** [comment]
Issue still presists after reinstalling Magisk by uninstalling via `uninstall.zip` in custom recovery, reflashing the stock using Odin, and then patch boot.img again.

Neither the system Settings app nor the output of `pm list packages` show any leftovers from pervious diguised Magisk Manager installations.

Magisk 21.7 and Manager 8.0.7 on the same device are unaffacted by this issue. As soon as the Manager  app is updated 22.0 it no longer sees the existing installation of Magisk, attempting a direct install in this state results in the following error:
```
- Target image: /dev/block/
- Device platform: armeabi-v7a
- Installing: 22.0 (22000)
! Unable to check signature
! Installation failed
```

A similar issue was reported before as #3912, I suspect this is an issue specific to legacy non-SAR Samsung devices.
