### ISSUE TITLE
Magisk 22: Root access not working correctly

### ISSUE THREAD

**Issue by seffparker** [topjohnwu/Magisk#3943]
The apps like ES Explorer and Temux:API commands stopped working after updating to Magisk version 22.0 (from 20.4).

They all worked before the upgrade. Other tested apps like EX Kernel Manager, Termux App etc works fine even now.

I'm sure the issue is related to SEPolicy since disabling the SELinux will fixes all the issues. I'm aware that the recent updates to Magisk brought some changes to SEPolicy behaviour. 

Is it something:
1. The app developer should fix
2. The user have to apply an SE policy rule
3. A bug with Magisk itself

**Comment by Didgeridoohan** [comment]
Option 1.

Please close this so that John doesn't have to.

**Comment by seffparker** [comment]
Just an update, I'd able to fix (somewhat a work-around) as per [this article](https://android.stackexchange.com/questions/207484/how-to-fix-selinux-avc-denied-errors-when-launching-dnscrypt-as-init-d-script)
