### ISSUE TITLE
Message "Abnormal State" after updating to 22.0

### ISSUE THREAD

**Issue by MelwinQ** [topjohnwu/Magisk#3946]
After updating to 22.0, I get the message
"Abnormal State; An "su" command that does not belong to Magisk is detected. Please remove the other unsupported su."
I am not aware of any having other su. MagiskManger had been reset before update to default settings as recommended.

The same result when deinstalling Magisk before switching to 22.
Same result when cstarting from different Magisk-versions before the update.

channel: Canary
device: Sony Xperia Z5 compact
os: Android 7

Thanks for the great work, though!

[magisk_log_2021-02-26T08_30_41.zip](https://github.com/topjohnwu/Magisk/files/6050597/magisk_log_2021-02-26T08_30_41.zip)

**Comment by ameaninglessname** [comment]
Same situation here at 22.1, indeed, there should be a "system su" on my rom, so this message is correct.
But why would magisk hide stop working? (A app could detect root now...)

**Comment by ameaninglessname** [comment]
Just don't use the system su (root manager), telling this by my own experience. That why magisk complains.
