### ISSUE TITLE
Stuck in download-mode bootloop after flashing new Magisk! Please help...

### ISSUE THREAD

**Issue by jjgh** [topjohnwu/Magisk#3947]
Hi everyone,
I tried installing Magisk on my Samsung a40 by carefully following instructions at https://topjohnwu.github.io/Magisk/install.html#samsung-system-as-root but after flashing magisk_patched.tar as AP + BL + CP + CSC my phone reboots and is then stuck in a bootloop with only download mode available.

The download mode has some red writings saying:

vbmeta: Error verifying vbmeta file: HASH_MISMATCH (3)
vbmeta: VERIFICATION_DISABLED bit is set.
CUSTOM VBMETA
VBMETA A405FNXXU3BTK4, 36252767A

What can I do now? I hope I can find a solution ASAP!
Thanks!

**UPDATE: I reflashed stock firmware and I could boot again normally. Of course now the phone is in an unrooted state... so how do we root it?**

**Comment by TheLando** [comment]
> Hi everyone,
> I tried installing Magisk on my Samsung a40 by carefully following instructions at https://topjohnwu.github.io/Magisk/install.html#samsung-system-as-root but after flashing magisk_patched.tar as AP + BL + CP + CSC my phone reboots and is then stuck in a bootloop with only download mode available.
> 
> The download mode has some red writings saying:
> 
> vbmeta: Error verifying vbmeta file: HASH_MISMATCH (3)
> vbmeta: VERIFICATION_DISABLED bit is set.
> CUSTOM VBMETA
> VBMETA A405FNXXU3BTK4, 36252767A
> 
> What can I do now? I hope I can find a solution ASAP!
> Thanks!
> 
> **UPDATE: I reflashed stock firmware and I could boot again normally. Of course now the phone is in an unrooted state... so how do we root it?**

Try using TWRP

**Comment by jjgh** [comment]
@TheLando the Samsung Galaxy a40 guide at https://twrp.me/samsung/samsunggalaxya40.html says that I first need to root my device with Magisk and then flash TWRP... So I think I either find what is wrong with the current Magisk method or have to find another way to root it... 

> If you intend to root your (a40) device, be advised that Magisk will be installed to the recovery partition, not the usual boot partition. Both TWRP and Magisk-rooted Android boot using the recovery kernel, with the device's hardware keys used to choose between TWRP and Android at boot time.
> **You are therefore strongly advised to first root your device with Magisk** and then pre-root a TWRP image before flashing it to recovery.

@topjohnwu why did you close this? Looking at the error I reported in the previous post, don't you think there's an issue with Magisk?

**Comment by jjgh** [comment]
@topjohnwu why did you close this?

**Comment by bughunter2** [comment]
<sup>(I'm posting this here too since this bug report seems to be a popular search result as well.)</sup>

**Solution:**

For those stumbling upon this... I've had this with two different Samsung phones now. Both times, I was able to fix it.

I've posted the solution here:

https://github.com/topjohnwu/Magisk/issues/4395#issuecomment-2864564582
