### ISSUE TITLE
Unstable Magisk App UI on 22.0 (OnePlus 3T)

### ISSUE THREAD

**Issue by SigmaDolphin** [topjohnwu/Magisk#3948]
Since i updated to 22.0 i noticed the app has become unstable, the app sometimes hangs when opening it, going to recents and back into the app seems to solve the problem, also noticed it appears as if Magisk opens two instances of itself because when opening it and press the Back button another Magisk main screen appears, doing this also prevents the hanging/freezing mentioned
I don't know if it may be related to the boot images getting corrupted but i remember it hanging, not responding and appearing as its opening multiple instances of itself when clicking the "Let's Go" button when trying to update the rest of Magisk to 22.0 and i did got my boot.img corrupted

My phone is a OnePlus 3T running OOS 9.0.6

**Comment by nickswang** [comment]
Having similar issue on Android 7.1. Earlier versions of magisk will run okay but they won't function without first trying to update
