### ISSUE TITLE
Add fastlane for F-Droid

### ISSUE THREAD

**Issue by linsui** [topjohnwu/Magisk#3950]
I opened an [MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8457) to include Magisk in F-Droid. Could you please add fastlane? See https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ . Thanks!

**Comment by vvb2060** [comment]
Magisk has its own upgrade system, new versions can be pushed to everyone immediately after release. 
If you need reproducible builds: https://github.com/topjohnwu/Magisk/actions

**Comment by linsui** [comment]
Yep, I know. But there are still some users who want to get Magisk from F-Droid. 😂

**Comment by linsui** [comment]
@osm0sis Any reasons?

**Comment by osm0sis** [comment]
F-Droid has been requested before but I believe @topjohnwu was clear there are no plans for that being how Magisk will be built or distributed.

**Comment by linsui** [comment]
I thought he does not oppose to include Magisk in F-Droid. See https://github.com/topjohnwu/Magisk/issues/1023

**Comment by osm0sis** [comment]
Fair enough

**Comment by vvb2060** [comment]
https://gitlab.com/fdroid/fdroiddata/-/commit/3193a4d0315d33ba98f04601a1bab812893083b0

**Comment by yephny** [comment]
@vvb2060 Why isn't F-Droid preferred over Github Actions for reproducable builds?

**Comment by nikitasius** [comment]
@vvb2060 hi, thats very interresting. It's modded just a ci/cd script and it's impossible to disable?
* https://gitlab.com/fdroid/fdroiddata/-/commits/master/metadata/com.topjohnwu.magisk.yml
* bumping to version 25.1 and your rollbacks to 24.3
