### ISSUE TITLE
i can't find magisk_patched.img after installing magisk app

### ISSUE THREAD

**Issue by HafidInspirative** [topjohnwu/Magisk#3955]
hello anyone, can you tell me how to fix it? when i'm installing magisk for first time and reboot to recovery, it comes bootloop.. I need a solution ASAP... i'm so sad failed to install magisk :(

**Comment by HideakiAtsuyo** [comment]
Search the original img of your phone os and install it back :)

**Comment by HideakiAtsuyo** [comment]
> hello anyone, can you tell me how to fix it? when i'm installing magisk for first time and reboot to recovery, it comes bootloop.. I need a solution ASAP... i'm so sad failed to install magisk :(

Search the original img of your phone os and install it back :)
