### ISSUE TITLE
What is odin tar file?how to download it for Android 10 tab

### ISSUE THREAD

**Issue by Lite-os15** [topjohnwu/Magisk#3956]

**Comment by etmatrix** [comment]
Try to read this [doc](https://topjohnwu.github.io/Magisk/install.html)

**Comment by HideakiAtsuyo** [comment]
1) Unlock the bootloader
2) USB Debug => active
3) Take [[Search your device TWRP version(Go to download links and "primary (Europe/Americas)")]](https://twrp.me/Devices) a `.img.tar` [[TWRP Versions]](https://twrp.me)
4) Launch [[Odin(3.14.4)]](https://odin-samsung.com/download/255/Odin3-v3.14.4.zip) (If it's a bad version/file just use reply functions and i will update the link)
5) Put your phone in Download Mode
6) Uncheck in "Options" the reboot option [[Like this]](https://i.imgur.com/uJicQc7.png)
7) Click `AP` and select your TWRP img [[Like this]](https://i.imgur.com/hVPwcKw.png)
8) START
9) Reboot your phone directly in Recovery Mode(not in normal mode)
10) In TWRP: 
=> 1) "Wipe" => "Format Data" => Type "yes" and validate.
=> 2) (Not necessary i think) "Reboot" => "Recovery"
=> 3)  "Install" (select the good storage with "Select Storage") install them in the order:
11) "no-verify-opt-encrypt-6.1.zip" [[Last Version]](https://build.nethunter.com/android-tools/no-verity-opt-encrypt)
12) "RMM_Bypass_v3_corsicanu.zip"[[v3]](https://androidfilehost.com/?fid=4349826312261812478)
13) "Magisk-v22.0.zip" [[Last Version]](https://github.com/topjohnwu/Magisk/releases) => At this step also check "Reboot after installation is complete"

It's finished(for me it's all i had to do, fast and easy) :)

**Comment by palmbeach05** [comment]
This is off topic. Can we get this closed?

**Comment by HideakiAtsuyo** [comment]
> This is off topic. Can we get this closed?

It's just a little help sorry to be off topic.

**Comment by HideakiAtsuyo** [comment]
> _No description provided._

You need to find your TWRP `TAR` file here: https://twrp.me/Devices

Search your device in the list, click on the name, go to `Download Links:` and select `Primary (Americas)` or 
`Primary (Europe)` then in the list take the last `.img.tar` ( https://i.imgur.com/YwFharc.png )

Now you know what file you need EL FAMOSO TAR FILE(It's a type of archive file, like any zip file but isn't the exactly same compression) :)

**Comment by HideakiAtsuyo** [comment]
> This is off topic. Can we get this closed?

It's just a little help sorry to be off topic.
