### ISSUE TITLE
Module download error

### ISSUE THREAD

**Issue by santhu1702** [topjohnwu/Magisk#3957]
I worked fine till morning 
After updating magick now it's not working
But packages are installing manually #
![Screenshot_20210228-091913](https://user-images.githubusercontent.com/58586232/109409778-7002a980-79bb-11eb-8cb4-9b7b8c2f5551.png)

**Comment by jeanrivera** [comment]
![Screenshot_20210228-155258892](https://user-images.githubusercontent.com/24832354/109433193-20cd7080-79dd-11eb-8c8e-bd8b9a7b2b00.jpg)
Make sure you give magisk storage access permission, if you did, then a logcat will need to be provided.
