### ISSUE TITLE
64-bit detection not reliable

### ISSUE THREAD

**Issue by yath** [topjohnwu/Magisk#3961]
Hi,

d2bc2cfcf87e4506569b0c6904b6213297f45646 installs the 64-bit Magisk binary into the initramfs if it detects a `/system/lib64` directory. On my [TV](https://github.com/yath/tpm171e), however, the kernel is an `armv7l` one and cannot execute 64-bit binaries, yet there is a `/system/lib64` directory (with only an `arm64` `libnanovoice.so`, I dunno why that is :shrug:). This results in a `magisk64.xz` binary installed into the initrd, and init failing to execute it (“<11>[   58.786037] init: cannot execve('/sbin/magisk'): Exec format error”).

I don’t know of a good way to solve this, otherwise I’d send a PR. I guess the most reliable way (apart from guessing from `uname -m`) would be attempting to execute the 64-bit binary in `boot_patch.sh` and if it does not succeed, set `IS64BIT` to false. init could alternatively fall back to the 32-bit version if exec fails with `ENOEXEC`.

Thanks for your work!\
Sebastian

**Comment by osm0sis** [comment]
Any change with 22003?

**Comment by osm0sis** [comment]
I've got an idea for this too, using magisk64 as a test.

**Comment by osm0sis** [comment]
@yath can you run these commands as shown below?

```
su
. /data/adb/magisk/util_functions.sh
api_level_arch_detect
echo $IS64BIT
```
