### ISSUE TITLE
Please give link to update-binary from Magisk.zip of canary build (20307, 72f6770d)

### ISSUE THREAD

**Issue by soft391** [topjohnwu/Magisk#3962]
Hi, @topjohnwu, greetings from norway, @shakalaca has used the update-binary from the magisk.zip of the above build in his great magiskonemulator project, but this magisk.zip appears to no longer be in this repo. It would be good to have the original 'cause it contains a blob. Would it be possible obtain the magisk.zip for this release?
https://github.com/shakalaca/MagiskOnEmulator/blob/master/update-binary

**Comment by palmbeach05** [comment]
It might be necessary for @shakalaca to adapt to the new era of magisk or watch his project remain in the past. I commend him for at least making efforts to prepare for android 12, but its time to move away from the past.

**Comment by topjohnwu** [comment]
@soft391 the APK itself is the flashable zip. Please read the release notes...

**Comment by soft391** [comment]
@topjohnwu  I'm aware of that. I'm looking for the specific release above because shakalaca's code has a blob in it. A security issue, not a technical issue. I mistakenly flashed a device with sensitive data on it.
