### ISSUE TITLE
Broken display logic for "Install to Inactive Slot (After OTA)" option

### ISSUE THREAD

**Issue by shugo-chara** [topjohnwu/Magisk#3963]
![Screenshot_2021-03-01-10-38-23-579_l oybq yjfpfvi c](https://user-images.githubusercontent.com/20610965/109442075-7d329d80-7a7a-11eb-9a9a-75d291889465.png)
mi11
miui12.5
After installing magisk22.0/22001, the "install to another slot" option disappears.
Reinstall magisk and system still can't enable this feature.

DEVICE DESCRIPTION
Model: Mi11
Android version: 11
System build version: 21.2.25

MAGISK SETUP DESCRIPTION
Manager version: 22.0/22001
Installation method: patching boot image/install
![Screenshot_2021-03-01-10-36-05-143_l oybq yjfpfvi c](https://user-images.githubusercontent.com/20610965/109441937-1a410680-7a7a-11eb-87e7-3ed1b951366c.png)

**Comment by Displax** [comment]
Because it's not supported on Android 11. Please close this.

**Comment by vvb2060** [comment]
Did it work properly before?  Mi 11 is a virtual A/B device, we believe that virtual A/B does not support installation to another slot.

**Comment by osm0sis** [comment]
I have told you it's NOT correctly hiding it on Virtual A/B devices either @vvb2060, so sounds like it may also be hiding it on devices it shouldn't either?

**Comment by shugo-chara** [comment]
> Did it work properly before? Mi 11 is a virtual A/B device, we believe that virtual A/B does not support installation to another slot.
I was using this method to install magisk until I upgraded to 22. The Mi11 is a virtual a/b, but it also works fine with the "install to another slot" feature.
Unfortunately after upgrading to 22, he disappeared. I have tried many ways to find out why. However, some users of this model seem to be able to use it normally. I don't know what the problem is.
@osm0sis

**Comment by vvb2060** [comment]
@shugo-chara  Maybe the SELinux of your device is permissive, so Magisk app detected the virtual A/B.
@osm0sis Maybe only OnePlus virtual A/B devices cannot use "install to other slots".?

**Comment by osm0sis** [comment]
@vvb2060 Pixel devices on Virtual A/B also don't work with "Install to Inactive Slot", which is why we originally hid it on them specifically.

@shugo-chara Please provide the output of `getprop | grep virtual` at both a user and root prompt.

Here's mine:
```
:/ $ getprop | grep virtual
[persist.sys.wfd.virtual]: [0]
[ro.surface_flinger.force_hwc_copy_for_virtual_displays]: [true]
[ro.surface_flinger.max_virtual_display_dimension]: [4096]
:/ $ su -c getprop | grep virtual
[persist.sys.wfd.virtual]: [0]
[ro.surface_flinger.force_hwc_copy_for_virtual_displays]: [true]
[ro.surface_flinger.max_virtual_display_dimension]: [4096]
[ro.virtual_ab.enabled]: [true]
:/ $
```

**Comment by shugo-chara** [comment]
@osm0sis 
$ getprop | grep virtual
[persist.sys.wfd.virtual]: [0]
[ro.surface_flinger.force_hwc_copy_for_virtual_displays]: [true]
[ro.surface_flinger.max_virtual_display_dimension]: [4096]
[ro.virtual_ab.enabled]: [true]
$ su -c getprop | grep virtual
[persist.sys.wfd.virtual]: [0]
[ro.surface_flinger.force_hwc_copy_for_virtual_displays]: [true]
[ro.surface_flinger.max_virtual_display_dimension]: [4096]
[ro.virtual_ab.enabled]: [true]

**Comment by shugo-chara** [comment]
@vvb2060 You've reminded me. I think you are right, I just checked selinux status it is in permissive mode.
After executing setenforce 1 and reopening the magisk app, the option to install unused slots appears again. Thank you!

@osm0sis I noticed that the system default selinux is permissive mode. Although it can be turned off manually to revert updates to the a/b partition, magisk should probably support use in permissive mode. With a frequently updated rom like miui, it is tedious and error-prone to manually unpack the rom to extract the boot for patching each time.

**Comment by osm0sis** [comment]
That's not the desired effect. It should be hidden on all Virtual A/B devices, except perhaps MIUI now.

**Comment by osm0sis** [comment]
I think just whatever effect SELinux has on it needs to be fixed. It only showing when SELinux was enforcing shouldn't be a problem in a root app.

Then we just need some way to identify which Virtual A/B devices use Google's Incremental OTA, and that would need to be added.

**Comment by terlynn4** [comment]
> I think just whatever effect SELinux has on it needs to be fixed. It only showing when SELinux was enforcing shouldn't be a problem in a root app.

Agreed. I'm experiencing this issue as well on my OnePlus 9 Pro, where the "Install to inactive slot" is only present if SELinux is set to enforcing. While I realize SELinux enforcement is "best practice" I had intentionally changed it to permissive to resolve an unrelated issue, and in doing so I lost the ability to keep root after an OTA.

**Comment by osm0sis** [comment]
Fixed by https://github.com/topjohnwu/Magisk/commit/053f4d481d603e2e8e7f3bd51d2e8fef9c8a6dbc
