### ISSUE TITLE
SAMSUNG DEVICE UPGRADE

### ISSUE THREAD

**Issue by L-Ryland** [topjohnwu/Magisk#3964]
My device is Samsung s10+ sdd855, somehow I have managed to boot directly into Magisk mode without clicking any buttons although the Magisk app shows that my device does not support ramdisk but SAR says yes. I have read the installtion guide of your page, but it seems there is no detailed guide how to upgrade to a new release after a successfull Magisk install. 

For example, now I'm on v21.4 and I would like to upgrade v22.0, should I repatch my firmware and flash `AP` tar again, or directly install new Magisk.zip same as other ramdisk-supported device?  

I used to use a Redmi device and install Magisk seems quite convenient and I can easily upgrade if there is any new version, switch to Samsung device and it seems more complicated. I hope you can give an instruction. @topjohnwu

**Comment by palmbeach05** [comment]
> My device is Samsung s10+ sdd855, somehow I have managed to boot directly into Magisk mode without clicking any buttons although the Magisk app shows that my device does not support ramdisk but SAR says yes. I have read the installtion guide of your page, but it seems there is no detailed guide how to upgrade to a new release after a successfull Magisk install.
> 
> For example, now I'm on v21.4 and I would like to upgrade v22.0, should I repatch my firmware and flash `AP` tar again, or directly install new Magisk.zip same as other ramdisk-supported device?
> 
> I used to use a Redmi device and install Magisk seems quite convenient and I can easily upgrade if there is any new version, switch to Samsung device and it seems more complicated. I hope you can give an instruction. @topjohnwu

If you have twrp, take the v22 apk and rename the extension from apk to zip and flash. He's said this in his guides and release notes

**Comment by Haus3master** [comment]
Yes, he even explicitly mentioned that Magisk manager has been turned into a do it all package, just change the file extension from.apk to .zip and then you will be able to flash it in a custom recovery...

**Comment by gitthangbaby** [comment]
Thanks guys, i read the big announcement with bold letters thousand times and still didn't get the joke that Magisk is in APK. Wondering why S10 wouldn't stay rooted on Android 11 with "latest" 21.4 i was planning to sell it, but i just recovered it using the advice above:)

**Comment by L-Ryland** [comment]
> > My device is Samsung s10+ sdd855, somehow I have managed to boot directly into Magisk mode without clicking any buttons although the Magisk app shows that my device does not support ramdisk but SAR says yes. I have read the installtion guide of your page, but it seems there is no detailed guide how to upgrade to a new release after a successfull Magisk install.
> > For example, now I'm on v21.4 and I would like to upgrade v22.0, should I repatch my firmware and flash `AP` tar again, or directly install new Magisk.zip same as other ramdisk-supported device?
> > I used to use a Redmi device and install Magisk seems quite convenient and I can easily upgrade if there is any new version, switch to Samsung device and it seems more complicated. I hope you can give an instruction. @topjohnwu
> 
> If you have twrp, take the v22 apk and rename the extension from apk to zip and flash. He's said this in his guides and release notes

But I don’t have any twrp installed, how am I supposed to do an upgrade?

**Comment by techIndia-hacker** [comment]
Extract the boot.img from AP.tar Patch it using the magisk manager. Repackage the modified boot.img into boot.tar
After flashing all stock firmware using Odin, restart the phone only to boot into recovery. Power off and reenter download mode and flash the newly created boot.tar in AP. U r rooted
