### ISSUE TITLE
magisk cannot update /Dev/block/mmcblk0p31 read only file system 

### ISSUE THREAD

**Issue by tkalfaoglu** [topjohnwu/Magisk#3966]
Lenovo m10 x306f was rooted by patching the boot image. Now then the canary magisk app tries to update magisk directly, it complains that /Dev/block/mmcblk0p31 read only file system

**Comment by tkalfaoglu** [comment]
Why closed?

**Comment by vvb2060** [comment]
Use fastboot to upgrade msgisk. your device's kernel prevents writing to the boot partition after booting.

**Comment by tkalfaoglu** [comment]
Wonderful -- thank you very much..
