### ISSUE TITLE
Is magiskmanager.com legitimate?

### ISSUE THREAD

**Issue by royimous** [topjohnwu/Magisk#3967]
I searched for "magisk" and the first result is magiskmanager.com

This Github repo says Github is the only official place to download Magisk, but that website looks very legitimate.

Just wanted to be sure ┌(▀Ĺ̯▀)┐

**Comment by dcoolArne** [comment]
You already said it, the github is the only official place so why should it be legitimate?

**Comment by pndwal** [comment]
Can't you even read two headings on Magisk main page here?... You certainly haven't read down to posting bug issues. 🙄

**Comment by palmbeach05** [comment]
> I searched for "magisk" and the first result is magiskmanager.com
> 
> This Github repo says Github is the only official place to download Magisk, but that website looks very legitimate.
> 
> Just wanted to be sure ┌(▀Ĺ̯▀)┐

@topjohnwu @osm0sis can you close this?

And by looking at the page source code, it is downloading from the link posted in your v22 commit. Idk what, if any, action you want to take regarding that site

**Comment by 1M0G9F5FZNUMKLGGLY** [comment]
# #

**Comment by royimous** [comment]
> You already said it, the github is the only official place so why should it be legitimate?

Maybe the the readme here wasn't up to date. That's why I asked. Also, posting this question means anyone else searching for my question will get the answer.

**Comment by palmbeach05** [comment]
> > You already said it, the github is the only official place so why should it be legitimate?
> 
> Maybe the the readme here wasn't up to date. That's why I asked. Also, posting this question means anyone else searching for my question will get the answer.

The hell it wasn't updated. Topjohnwu isn't that sloppy. You just were lazy. See commit dated 7 days ago vs your issue posted 9 hours ago.

https://github.com/topjohnwu/Magisk/commit/79ee85c0f99f4cdfe09b4e9685d7d8c5c25f55f9#diff-01e6d9ffed056a02cae8d8a0ec5d476a64d017bf85c0d5a94bb23ca21f33f5aa
