### ISSUE TITLE
Minor remark for the installation instructions: might need to add ":raw" when flashing via fastboot

### ISSUE THREAD

**Issue by 7wells** [topjohnwu/Magisk#3968]
Dear John Wu,

I hope my message finds you well. Thank you so much for this great tool! Please allow me a minor remark about the [installation instructions](https://topjohnwu.github.io/Magisk/install.html), which are really helpful.

I had to add ":raw" to flash the patched boot image, hence:
```
PS C:\Users\user\Desktop> fastboot flash:raw boot .\magisk_patched_8wkc5.img
Sending 'boot' (23067 KB)                          OKAY [  0.535s]
Writing 'boot'                                     OKAY [  0.587s]
Finished. Total time: 1.160s
```
Without the ":raw" parameter:
```
PS C:\Users\user\Desktop> fastboot flash boot .\magisk_patched_8wkc5.img
fastboot: error: Couldn't parse partition size '0x'.
```
It seems to depend on the fastboot version used. Mine is 30.0.5-6877874. Sorry that I have no more details, though, when ":raw" needs to be added and when not.

Would you consider it worth to add this in your installation instructions?

**Comment by vvb2060** [comment]
```
 flash PARTITION [FILENAME] Flash given partition, using the image from
                            $ANDROID_PRODUCT_OUT if no filename is given.

 flash:raw PARTITION KERNEL [RAMDISK [SECOND]]
                            Create boot image and flash it.
```

**Comment by topjohnwu** [comment]
@7wells your bootloader is not following proper fastboot protocol. This does not apply to everyone, so it will not be added to the instructions

**Comment by 7wells** [comment]
Ok. Just for the record: It's a Lenovo Tab4 8 Plus tablet (8704x). Would not all users of this model experience the same? Anyway, I totally respect your decision.

**Comment by Displax** [comment]
It's fastboot issue. Will be fixed in future releases.

https://android-review.googlesource.com/c/platform/system/core/+/1611279
https://android-review.googlesource.com/c/platform/system/core/+/1579087
https://issuetracker.google.com/issues/183835416
