### ISSUE TITLE
Will there be a future ZIP install option?

### ISSUE THREAD

**Issue by SubZero5** [topjohnwu/Magisk#3973]
Hi,

I sometimes install ROMs on my devices. It was nice to have a zip file to install and in case of any emergency to uninstall the app an uninstall zip file was great.

Are you planning to release a ZIP installer and a ZIP uninstaller?

**Comment by Didgeridoohan** [comment]
You might want to read the current release notes and installation instructions.

Hint: rename the .apk to .zip and uninstall.zip respectively.

And then you can close this...
