### ISSUE TITLE
Magisk Manager not Opening After Updating to v22

### ISSUE THREAD

**Issue by CyberSolutions8799** [topjohnwu/Magisk#3977]
I updated my Magisk Manager using the update option available inside the Magisk Manager program.
My Magisk Manager was hidden at the time of updating.

But after the update the program won't open anymore and always give me the error "Unfortunately, Magisk has stopped."

Can anyone please tell me how to fix this...

**PS:** I was running Magisk Manager v8.0.7 & Magisk v21.4 before the update.

**Comment by pndwal** [comment]
Should have restored manager/app to unhidden before updating app or Magisk as stated (in bold) in release notes that appear before Patch or Direct update procedures.

Retrospectively, it should be a simple matter of uninstalling any hidden app or stub existing as well as new manager/app, then re-installing current app.

**Comment by CyberSolutions8799** [comment]
@pndwal 
Actually, I've always updated the program without unhiding it, so didn't know that it'd be a problem with this update.

I've tried uninstalling the Hidden Magisk Manager and reinstalling the older version (v8.0.7), but it didn't recognize my magisk.

**Comment by pndwal** [comment]
So did you uninstalling every app? (hidden app, stub apk, as well as new manager/app) then re-install the current (new) app as suggested?

**Comment by CyberSolutions8799** [comment]
@pndwal 
I uninstalled the Hidden Magisk Manager & I've never installed the Stub Apk.
Then I installed the Old Version v8.0.7 (not the new one v22) but it didn't recognize my Magisk.

Do I need to flash the new Magisk_v22.zip using TWRP? I already have Magisk v21.4 Installed.

**Comment by pndwal** [comment]
I'm guessing you not only updated app to 22.0, but Magisk root as well, so you will need to install/update to compatible 22.0 app (Install apk, not zip).

If you actually have 21.4 you should see Update (Magisk) button after installing 22.0 app as long as no manager/app is hidden/renamed while updating.

**Comment by CyberSolutions8799** [comment]
@pndwal 
When the update came, I just clicked on the update option of the Magisk Manager (not the Magisk root) from inside the Magisk Manager app.

After the app got installed, it never opened and now I can't even check what version of Magisk I have.

Now I don't know what to do since I can't open the Magisk Manager application, I can't even unhide the program.
