### ISSUE TITLE
[I am not running a 'Canary' build but I post this anyway:]Hang-on-boot after latest upgrade; am trying to uninstall from Recovery but your instructions are unclear

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [topjohnwu/Magisk#3978]
The instructions to which my title refers are [here](https://www.didgeridoohan.com/magisk/MagiskUninstall). They say:

> When booted to a custom recovery, you can use the uninstall zip (rename the Magisk app apk to uninstall.zip) to uninstall Magisk. It uses the same uninstall script as mentioned above.

Am I to take it that there is file called `Magisk.apk` that I am to rename as `uninstall.zip` and then flash? OK (but that could have been clearer). But _where_ is that file?

I would give details of my Magisk version, but I cannot easily access those details. For, I am stuck in recovery.

EDITED to fix formatting problems.

**Comment by pndwal** [comment]
As John has stated clearly on his GitHub, XDA threads, etc:
"Please note that the only source of official Magisk information and downloads is Github. Beware of any other websites."
It's on the main Magisk repo page, from which you got to 'Issues'.
https://github.com/topjohnwu/Magisk#downloads

**Comment by LinuxOnTheDesktop** [comment]
'It's' - what's? Does this 'it' refer to documentation? But then you write of 'issues'; but, ah, OK, there are links to documentation under (surprisingly enough) the heading 'downloads'. Do any of those links explain clearly and fairly explicitly how to uninstall Magisk from a recovery environment? Note also that other (seeming unofficial) documentation on the matter, documentation to be found on the web, is dire.

All of this though is now academic to me. For, Magisk got my phone in such a bad way that the only solution I found was to uninstall it permanently. I am grateful though for the years in which Magisk worked for me.

**Comment by LinuxOnTheDesktop** [comment]
Really you should close this issue only once you are satisfied that the instructions that you do (yourselves and officially) provide suffice to allow the moderately novice user to recover from unbootability that seems to have been caused recently by your software and for which, as I say, at least the rest of the web has no good instructions.

**Comment by pndwal** [comment]
'It's' what you were looking for of course (the APK file, not documentation); you asked "Am I to take it that there is file called Magisk.apk that I am to rename as uninstall.zip and then flash? OK (but that could have been clearer). But where is that file?"

Also, the documentation is NOT under the heading 'downloads', it's under 'useful-links'!

FWIW, documentation is very clear and as simply laid out as it can be... but you seem to have some difficulty with plain English.
