### ISSUE TITLE
Error trying to flash patched boot.img

### ISSUE THREAD

**Issue by pseudorandomnumber** [topjohnwu/Magisk#3979]
doing:
fastboot flash boot boot.img

I got following:
fastboot: error: Couldn't parse partition size '0x'.

fixed it by adding :raw to the flash command like so:
fastboot flash:raw boot boot.img

Maybe, You can add this to the instructions.

**Comment by pndwal** [comment]
https://github.com/topjohnwu/Magisk/issues/3968
