### ISSUE TITLE
Root, factory reset, exec bugs

### ISSUE THREAD

**Issue by breakersvd** [topjohnwu/Magisk#398]
Hi Dev,

I worked on compiling Magisk sources with adding features for latest SAMSUNG android securities

i want to tell you about a bugs i found in magisk and fixed, not-fixed:
1 - Magisk didn't apply root stuffs (didn't do anything) in the first boot after factory reset because of depending on 'SECURE_DIR' variable (/data/adb) so the fix i changed it to (/cache) and every thing was fine even in the first boot.
2 - in the boot stage 'late_start' no 'system()' function codes is running until arrived to 'core only' so rebooting command is not working until we set 'reboot' variable to '1' and check it in 'core only' stage then reboot when Magisk fails to some reasons

these two small bugs i found in samsung devices (android 7.1.1 - 8.0.0 - 7.0 - 6.0.1)
and the fix is simple as you read

another big problem on MTK based devices..

one of my tests on MTK devices returns with failure status (i.e. 'magiskinit' patched the sepolicy with magisk rules and patched 'init.rc' successfully but the original 'init' didn't run magisk services)
after some tests i detected that the problem from 'sepolicy' patching rules
so i repatched the 'sepolicy' using 'supolicy "permissive *"' option and every thing run ok and the init run init.rc codes the phone rooted !

i continue with magisk with all available solutions to fix the problem:
1 - i tried to add "sepol_permissive("*");" in 'magiskinit.c' before "sepol_magisk_rules()" but didn't solve the issue 
2 - i tried to run "adb shell /data/local/tmp/magiskpolciy --load /data/local/tmp/sepolicy --save /data/local/tmp/sepolicy_patched 'permissive *'" and inject the new patched sepolicy in the boot.img but also didn't solve the issue
3 - i compiled "sepolicy-inject & sesearch & seinfo" for windows using Cygwin and compared the 'sepolicy' patched by 'supolicy' & the other one patched with 'magisk' and the result was:
- Permissive attributes are the same in the both
- Allow items in the supolicy patched sepolicy are greater than magisk one (about 9000 more) 

unfortunately i could not solve the issue and i could not find a way to apply "supolicy permissive *" patch with magisk

Now i have ideas to solve the issue:
1 - Find a way to run "execv("/init", argv);" separately (i.e. start it without waiting it to finish) 
and then run a code in "for(; {}" loop like "mkdir /test_system_server" then we test "access()" to the that DIR and if we access to it that mean the origianl init binary arrived to mount and boot the system server so we can run magisk --* codes to patch sepolicy & start root daemon.......
2 - Always do early mount for system and find a code to execute ELF binaries so we return to first solution and can run magisk --* codes .....................
3 - Create a new parameter to magiskpolicy and name it "permissive" that applies exactly like supolicy "permissive *" (i.e. applies permissive & allow rules)

Any help or suggestions i'm ready to test and debug :)

**Comment by topjohnwu** [comment]
For the Samsung issue I'll double check with my beta testers.

For the MTK issue, you are using CF's `supolicy`, it will always inject its own rules regardless what you tell it to do. If your device is suffering SELinux issues, you should just capture a boot logcat (run `adb logcat > log.txt` before your device boot, then connect your device to the PC and boot your device), it will log the AVC errors and I'll know what additional rules are needed.

**Comment by breakersvd** [comment]
This is the logcat file,

as you said started from powered off device until boot finished,
i'm ready for new tests or "sepol_*" new patches.

[Logcat_MTK_6.0.1_Magisk_1671.txt](https://github.com/topjohnwu/Magisk/files/2210631/Logcat_MTK_6.0.1_Magisk_1671.txt)

**Comment by breakersvd** [comment]
And this the dmesg log

[dmesg_log_MTK_6.0.1_Magisk_1671.txt](https://github.com/topjohnwu/Magisk/files/2212068/dmesg_log_MTK_6.0.1_Magisk_1671.txt)

**Comment by topjohnwu** [comment]
Viewing from your logs, you don't seem to have Magisk installed

**Comment by breakersvd** [comment]
I told you i flashed Magisk but the problem the patched sepolicy needs more rules to exec "service" command,

after device booted i checked "/init.rc" & "sepolicy" and they already patched with magisk and i found "init.magisk.rc"

we could understand from this the "service" didn't exec "init.magisk.rc" codes to run "magisk" binary (sure because of patching sepolicy after my tests written in OP)

thanks for understanding
