### ISSUE TITLE
Restore the app after restarting 

### ISSUE THREAD

**Issue by aaref1234** [topjohnwu/Magisk#3980]
Hi .

I have a problem with the latest version of the application, which is when I restart the device, another icon for the application appears, and the root is detected by the applications. 

To solve this problem, I open the original application and then the other icon disappears .

And this problem occurs constantly after every restart of the device .

Thank you .

**Comment by pndwal** [comment]
It's doubtful that this is a Magisk issue.

Did you restore manager/app to unhidden before updating app or Magisk as Instructions (in bold) in release notes that appear before Patch or Direct update procedures proscribe? (Old hiding methods are incompatible with the new.)

Retrospectively, solution should be a simple matter of uninstalling any hidden app or stub existing as well as new manager/app, (ALL Magisk apps), then re-installing current app.

**Comment by aaref1234** [comment]
The problem is not in detecting the root .

The problem is that the manager, after restarting the device, shows another icon for the manger, and the manager must be opened in order for the other icon to disappear .

**Comment by pndwal** [comment]
Sure, but did you have any hidden Manager/app when updating either Magisk root or Magisk manager/app?

**Comment by aaref1234** [comment]
I do not know .

What is the solution to this problem ?

**Comment by pndwal** [comment]
Locate any Magisk manager/app you hid (renamed) (go through your app list) and uninstall this AND current Magisk app. Then reinstall current only.

**Comment by aaref1234** [comment]
I uninstalled, reinstalled and hidden the app all over again and I expect the problem is resolved. 

Thank you .

**Comment by pndwal** [comment]
No worries... Next time you should ask here before posting issue:
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/

**Comment by aaref1234** [comment]
I have a problem and I think the magisk app or the activation files are the cause of the problem but I'm not sure .

The problem is the device randomly restarts constantly .

How do I know this ?
