### ISSUE TITLE
Magisk cannot cope with android 8.1

### ISSUE THREAD

**Issue by vpolinov** [topjohnwu/Magisk#3981]
Device: 360 qiku n6 lite

I can successfully patch boot.img if my device is running under stock Android 7.1

Once I flash Androin 8.1 (pure stock ROM by 360) and try to patch boot.img with subsequent flash of patched boot.img, my device fails to boot.

Attached are:

- boot patch log
- very sad result of trying to boot with patched boot.img

[magisk_install_log_2021-03-06T134940Z.log](https://github.com/topjohnwu/Magisk/files/6094836/magisk_install_log_2021-03-06T134940Z.log)

![IMG_20210306_091215 1](https://user-images.githubusercontent.com/67873235/110197638-0c1a2e00-7e5e-11eb-90d4-54f72b095c28.jpg)

**Comment by osm0sis** [comment]
Try 22003?

**Comment by vpolinov** [comment]
Tried 22004 - same issue.

**Comment by osm0sis** [comment]
It's up to 22103 now. Try that.

**Comment by vpolinov** [comment]
My typo: not 22004 but 22**1**04 - and system crashed same way as before.

**Comment by osm0sis** [comment]
Can't read what that says, but maybe it just needs to have the fastboot disable verity disable verification vbmeta command run?

**Comment by vpolinov** [comment]
Thanks for suggesting to flash vbmeta but this partition is all zeroes on my device.

**Comment by vpolinov** [comment]
Same red state when boot.img is patched by v.23.0
