### ISSUE TITLE
Gihub frontpage: problem with the 'downloads' and 'useful links' sections

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [topjohnwu/Magisk#3982]
It is not ideal that the so-called 'downloads' section consists in large part of text about documentation.

Worse: _is unclear whether **or not** the documentation that is mentioned in the 'downloads' section comprises the links that appear a little way below_. The links I mean are those that appear under the heading of 'useful links'.

Here is a screenshot that shows what I am describing.

_[ Start of screenshot ]_
![image](https://user-images.githubusercontent.com/47056543/110197924-9a82b580-7e46-11eb-95ab-85dc2af72950.png)
_[ End of screenshot ]_

I take it that the documentation - the documentation cited in the 'downloads' notice - _does_ comprise the materials cited under 'useful links'. But you need to make this clear. For, documentation is important for software that can render one's device unbootable.

(If I am right about what constitutes the official documentation, then I was criticised, in a recent bug report that I wrote, for citing . . the official documentation. Moreover, and as that other bug report explained, the documentation seemed to be not at all adequate. I realise that I cannot ask for my money back, but, really, there are problems here - and indeed, seemingly, with your latest update to the software itself.)

**Comment by Didgeridoohan** [comment]
The "Downloads" section consists of: downloads... Have you tried pressing "Magisk", "Magisk beta" or "Magisk Canary"?
