### ISSUE TITLE
[Feature Request] Magisk prompt when first open newly installed app

### ISSUE THREAD

**Issue by DestroyerXyz** [topjohnwu/Magisk#3984]
Magisk should ask if you want to enable MagiskHide on any app when you first open it after installing just like the Android permission prompts.

**Comment by osm0sis** [comment]
So you want it to intercept the opening of every app on a device? That's just not feasible.

**Comment by DestroyerXyz** [comment]
Just when first opened after install @osm0sis

**Comment by DestroyerXyz** [comment]
Maybe like someway to add it to a permission for every app so it appears with the other prompts

**Comment by osm0sis** [comment]
No, that's not how Android works.

**Comment by DestroyerXyz** [comment]
Does Android call some function or process for the system permission prompts or maybe some function everytime a new app is opened? Maybe you can find that out by attaching a debugger to an app @osm0sis ?

**Comment by osm0sis** [comment]
Monitoring for that would be insane.
