### ISSUE TITLE
Is there a running commentary on safetynet updates?

### ISSUE THREAD

**Issue by mcdoe** [topjohnwu/Magisk#3986]
Is the reflective code still unobfuscated, or do we have to attempt to do memory scanning? I'm wondering if there's already a running commentary of modules, like here:
https://koz.io/inside-safetynet-3/

**Comment by osm0sis** [comment]
This was the last mention of open sourcing the Magisk snet apk: https://github.com/topjohnwu/Magisk/issues/3537#issuecomment-738056760
