### ISSUE TITLE
Unable to repack boot image (segmentation fault)

### ISSUE THREAD

**Issue by Henk2484** [topjohnwu/Magisk#3989]
[magisk_install_log_2021-03-07T13_36_49Z.log](https://github.com/topjohnwu/Magisk/files/6097103/magisk_install_log_2021-03-07T13_36_49Z.log)
Latest canary build fails on repacking boot image on Pixel 3 with Android 11.
Both stock boot image (when selecting to patch a file) as well as previously patched image.

Log content:

- Target image: /dev/block/sda11
- Device platform: arm64-v8a
- Installing: 45e0df9c (22002)
Parsing boot image: [/dev/block/sda11]
HEADER_VER      [2]
KERNEL_SZ       [19800181]
RAMDISK_SZ      [12219561]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [862396]
OS_VERSION      [11.0.0]
OS_PATCH_LEVEL  [2021-02]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 androidboot.console=ttyMSM0 printk.devkmsg=on msm_rtb.filter=0x237 ehci-hcd.park=3 service_locator.enable=1 cgroup.memory=nokmem lpm_levels.sleep_disabled=1 usbcore.autosuspend=7 loop.max_part=7 androidboot.boot_devices=soc/1d84000.ufshc androidboot.super_partition=system buildvariant=user]
CHECKSUM        [4d1c77cad4aea4b1dc966c3bb7010d81c029d8bd000000000000000000000000]
- Unpacking boot image
KERNEL_FMT      [lz4]
RAMDISK_FMT     [gzip]
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Magisk patched boot image detected
Loading cpio: [ramdisk.cpio]
Remove [overlay.d]
Remove [overlay.d/sbin]
Remove [overlay.d/sbin/magisk32.xz]
Remove [overlay.d/sbin/magisk64.xz]
Remove [.backup/.rmlist]
Remove [.backup]
Remove [.backup/.magisk]
Move [.backup/init] -> [init]
Dump cpio: [ramdisk.cpio]
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [dtb]
- Repacking boot image
Parsing boot image: [/dev/block/sda11]
HEADER_VER      [2]
KERNEL_SZ       [19800181]
RAMDISK_SZ      [12219561]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [862396]
OS_VERSION      [11.0.0]
OS_PATCH_LEVEL  [2021-02]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 androidboot.console=ttyMSM0 printk.devkmsg=on msm_rtb.filter=0x237 ehci-hcd.park=3 service_locator.enable=1 cgroup.memory=nokmem lpm_levels.sleep_disabled=1 usbcore.autosuspend=7 loop.max_part=7 androidboot.boot_devices=soc/1d84000.ufshc androidboot.super_partition=system buildvariant=user]
CHECKSUM        [4d1c77cad4aea4b1dc966c3bb7010d81c029d8bd000000000000000000000000]
KERNEL_FMT      [lz4]
RAMDISK_FMT     [gzip]
Repack to boot image: [new-boot.img]
Segmentation fault
! Unable to repack boot image!
! Installation failed

**Comment by repsorp** [comment]
Same error message when trying to update to last canary version

```
Repack to boot image: [new-boot.img]
Segmentation fault
! Unable to repack boot image!
! Installation failed
```

Config:
Pixel 4a
Android 11

[magisk_install_log_2021-03-07T13_35_46Z.log](https://github.com/topjohnwu/Magisk/files/6097130/magisk_install_log_2021-03-07T13_35_46Z.log)

**Comment by osm0sis** [comment]
Try with 22003?

**Comment by repsorp** [comment]
Confirmation
Works fine with 22003
