### ISSUE TITLE
16.7 "boot loop" to fastboot

### ISSUE THREAD

**Issue by BTOdell** [topjohnwu/Magisk#399]
Version 16.7 just put my OnePlus 5T into a "boot loop" after installing it using the Magisk Manager app. I don't know if this is an actual boot loop because it starts to boot to the system and then instead goes to fastboot and stays there.
I was able to boot to the recovery and uninstall Magisk using the uninstall zip.

**Comment by topjohnwu** [comment]
Are you using latest OOS beta with Treble, or ROMs without Treble?

**Comment by MBDdk** [comment]
I'm using the latest stable release of OOS for the 5T (OnePlus5TOxygen_43_OTA_036_all_1806131716)

**Comment by topjohnwu** [comment]
Thanks, I'll test it on my own device!

**Comment by storm49152** [comment]
I know this is already closed, but for the record: this also happened on OP5 with LineageOS-15.1-20180716 (Android 8.1.0). Like the OP I reverted to Magisk-6.6 for now.

**Comment by topjohnwu** [comment]
@storm49152 @BTOdell the fix is already pushed to the public! Stop reverting to old builds LOL

**Comment by storm49152** [comment]
Maybe so. But I reverted before it was fixed.. ;-) I'll update later, thanks!
