### ISSUE TITLE
No installation dialogue

### ISSUE THREAD

**Issue by Qyrln** [topjohnwu/Magisk#3991]
Hello , Devs
ROM : 7.1.2 AOSP based ROM
Magisk : canary 22003

When I install modules , magisk can't proceed to installation dialogue , same problem when I try to update magisk via direct install

[logcat_03-07-2021_21-36-30.txt](https://github.com/topjohnwu/Magisk/files/6097941/logcat_03-07-2021_21-36-30.txt)

**Comment by KaMyKaSii** [comment]
Poco M3, Android 10.
Same with me. After updating the Manager, the installation screen does not appear after tapping "Lets'go" to upgrade Magisk or installing any module. But the installation happens in the background. After rebooting, Magisk is up to date.
[updating_manager_and_magisk.txt](https://github.com/topjohnwu/Magisk/files/6112560/updating_manager_and_magisk.txt)

**Comment by topjohnwu** [comment]
Please try 22005 and create a new issue if you still encounter this issue
