### ISSUE TITLE
Virus Detection

### ISSUE THREAD

**Issue by MYSERY555** [topjohnwu/Magisk#3992]
Hi bro , I'm Using Magisk v22 , Android OS 9... MIUI 12. Stable Rom with Stock. Till v21 thrs no issue. But v22 Detecting as virus by miui 12 security app and auto removing every time. I tried hide and change name lock app but its detecting same. Any solution ?

**Comment by zgfg** [comment]
su
magiskhide add com.miui.securitycenter

**Comment by MYSERY555** [comment]
Thanks bro , But i fixed by another way. 

1) If the miui is default security app in the device means we cant add magisk in exception list from the scan result ( Long hold )... 

2) Installed Kaspersky antivirus and scan fully it will detect virus ( but not self remove ) just click the ok button and exit.

3) Open miui security , scan system now it will show the result of virus in drop down box ( no auto remove ). From there we can add it on Exception.

4) Renaming magisk as Manager ( default ) somehow its detecting in miui , so i renamed to FreeFire. Hope this method will help to few for other virus detection in miui. 

![Screenshot_2021-03-09-01-50-43-589_com miui securitycenter](https://user-images.githubusercontent.com/80148013/110377470-77404c00-807a-11eb-8dd8-469544420b0b.jpg)
