### ISSUE TITLE
Error trying to open Manager (its hidden)

### ISSUE THREAD

**Issue by andre3ro** [topjohnwu/Magisk#3994]
how to open, unhide, update and hide again? im getting an error, my magisk is hidden but everytime that i want to open it says that need to update, click on update says that need to open manually click on cancel nothing happens, how to proceed??

**Comment by etmatrix** [comment]
I uninstalled Magisk and installed again and hidden with new version. It's just my way, maybe there is a way more easy.

**Comment by andre3ro** [comment]
i think that too, but i dont have it as "magisk" i have the app packed as random app (hiden entirely) not hiden for apps, even the icon looks like a damaged app, but i think that i fixed but i restored my telephone xd and appears are magisk manager updated and now its Magisk itself

**Comment by helpfulBrother** [comment]
> i think that too, but i dont have it as "magisk" i have the app packed as random app (hiden entirely) not hiden for apps, even the icon looks like a damaged app, but i think that i fixed but i restored my telephone xd and appears are magisk manager updated and now its Magisk itself

I have the same issue and haven't found a solution yet.  When you say you 'restored' your telephone, what steps did you take?
