### ISSUE TITLE
Loosing root when using system.prop

### ISSUE THREAD

**Issue by Shadowghost** [topjohnwu/Magisk#40]
I made an Magisk module to accomplish the changes the su.d scripts of ARISE sound system apply. To make that work, some props need to be added. Whenever i am adding the props to system.prop, the device boots up and root is lost. The phh-superuser-module is still active in Magisk Manager but the phh-superuser-app tells me to udated the binary su. The interesting thing here is: When I set the props manually within the post-fs-data.sh script they get applied and I still have root after the reboot.
Here's the module, when someone wants to test it for himself: https://www.dropbox.com/s/ncml9qg0obe349m/ARISE4Magisk.zip

Regards

**Comment by topjohnwu** [comment]
The loading system.prop has some issues, will issue an update soon.

**Comment by Shadowghost** [comment]
Thanks for all your work. 👍

**Comment by topjohnwu** [comment]
All system prop issues should be fixed now
