### ISSUE TITLE
Magisk manager unable to detect installed magisk on " 43c1105d "...

### ISSUE THREAD

**Issue by Haus3master** [topjohnwu/Magisk#4005]
Hello,
I'm on magisk canary version " 43c1105d " and after the device is rebooted after the update, none of my arm64 devices recognized the magisk installation, upon opening the app after the reboot the apps gives a popup shown in the image below, and there is no way to bypass this, 
and by hitting on 'install' it installs the manager but then, the manager no longer recognizes the installed magisk and this is a screenshot proving it...
![Screenshot_20210309-180942](https://user-images.githubusercontent.com/66825701/110472911-f3cb3d00-8103-11eb-8190-7aba1773129c.png)
and by hitting on installs it installs the manager but then, the manager no longer recognizes the installed magisk and this is a screenshot proving it...
![Screenshot_20210309-181822](https://user-images.githubusercontent.com/66825701/110472988-0b0a2a80-8104-11eb-9ee8-41d3a28c9b70.png)
This is happening on the lenovo tb-8504x and moto G5s and they both have arm64-v8a processor, phones with 32 bit chips are unaffected so far...
Edit: Just to clarify, magiskhide and all the modules do load from the previous version, only the manager isn't detecting the installation, apps that were previously granted root access still have them, but, there is no way to give an app fresh permission to root access...
Edit 2: I'm not sure about which logs from when are needed to be uploaded here, so, if any logs are required, I'm ready to provide them...
Device:Lenovo TB-8504x and Moto G5s Montana
Android version: Android 9 on both devices (Lineage os on the lenovo and pixel experience on the Motorola)
Magisk version name: " 43c1105d "
Magisk version code: 22004

**Comment by vvb2060** [comment]
Version code do not require parentheses.

**Comment by Haus3master** [comment]
> Version code do not require parentheses.

Oh, thank you very much for the info! :)

**Comment by Didgeridoohan** [comment]
I've got the same thing on my OP3T (also arm64) running an Android 9 ROM (ArrowOS). Gonna try to grab some logs later, but it doesn't seem like 22004 is saving a Magisk log for me...

**Comment by Haus3master** [comment]
> I've got the same thing on my OP3T (also arm64) running an Android 9 ROM (ArrowOS). Gonna try to grab some logs later, but it doesn't seem like 22004 is saving a Magisk log for me...

No, it is not able to save any magisk logs, and since I haven't granted root access to the "Shell" package, I'm plain out of luck..., so, please post your logs here...

**Comment by Didgeridoohan** [comment]
Well, the Magisk log doesn't get saved on 22004, but it runs... Attaching a boot logcat (where you can see the Magisk log as well) and a logcat when opening the Magisk app. No idea if they show anything...

[boot.log](https://github.com/topjohnwu/Magisk/files/6119379/boot.log)
[Magisk_22004_NA.txt](https://github.com/topjohnwu/Magisk/files/6119380/Magisk_22004_NA.txt)

**Comment by aIecxs** [comment]
this is probably usage problem - please try and report back
https://android.stackexchange.com/q/231184

**Comment by Didgeridoohan** [comment]
> this is probably usage problem - please try and report back
> https://android.stackexchange.com/q/231184

Yes, that would be a great solution (and a common problem for this issue). But, I didn't have the app hidden when updating...

And installing app build 22003 makes it recognise the installed 22004 binaries, but updating to app 22004 changes the installed status to N/A again. Which I just now realised is information I haven't shared previously...

**Comment by AndrewKvas** [comment]
Me too magisk manager unable to detect installed magisk on "43c1105d".
Android 8.0.0

**Comment by Didgeridoohan** [comment]
> And installing app build 22003 makes it recognise the installed 22004 binaries, but updating to app 22004 changes the installed status to N/A again. Which I just now realised is information I haven't shared previously...

Apparently this was some kind of weird fluke and I have not been able to reproduce a working setup with app 22003 since...

But, I can confirm the commit above fixes it.

**Comment by Haus3master** [comment]
> > And installing app build 22003 makes it recognise the installed 22004 binaries, but updating to app 22004 changes the installed status to N/A again. Which I just now realised is information I haven't shared previously...
> 
> Apparently this was some kind of weird fluke and I have not been able to reproduce a working setup with app 22003 since...
> 
> But, I can confirm the commit above fixes it.

Then, on that note, we just have to wait a bit for the owner to release a canary update...

**Comment by Haus3master** [comment]
Did a new canary update come out as of now?
