### ISSUE TITLE
Magisk manager 22.0 don't see Magisk installed

### ISSUE THREAD

**Issue by gjf** [topjohnwu/Magisk#4008]
Device: Samsung Galaxy Note 10.1 (2014) SM-P605 (lt03lte)
Android version: 5.1.1 (stock ROM)
Magisk version name: 43c1105
Magisk version code: 22004

Magisk manager starting from 22.0 (22000 and latest canary 22004) cannot see Magisk installed.
Although installation in recovery was successful.
Now Magisk reports Magisk: N/A, Ramdisk: Yes.

When downgraded Magisk manager to 8.0.7 it detects Magisk succesfully (both Magisk and ramdisk are "yes") but older manager requires "extended update", tries to download zip and fails.

Also it must be noted Magisk Manager 22.0 cannot install Magisk in automatic mode.

Describing pictures are here:
![110659840-01e88e80-81d4-11eb-8c76-96d47805368d](https://user-images.githubusercontent.com/322186/110662501-a075ef00-81d6-11eb-8970-0c30b3af8dc2.png)

![110659874-090f9c80-81d4-11eb-8d1e-db2264435117](https://user-images.githubusercontent.com/322186/110662530-a66bd000-81d6-11eb-86c1-06b8f7765cc8.png)

**Comment by Haus3master** [comment]
I too have the same issue, but, I don't have the installation failure... (I also have opened an issue regarding this, it seems to be persistent in arm64 devices...)

**Comment by osm0sis** [comment]
#4005

**Comment by gjf** [comment]
I really don't understand the point: both duplicated topics are closed?

**Comment by osm0sis** [comment]
No 4005 is open and the main issue for this bug.

**Comment by gjf** [comment]
Yup pardon me - I was confused. So will wait for fix patiently :)
