### ISSUE TITLE
[wishlist] mount product partition for Huawei devices

### ISSUE THREAD

**Issue by manguz** [topjohnwu/Magisk#401]
Hi, I'm new to Magisk and this may be already asked.
Is it possible to mount in magisk product partition in huawei devices?
Many stuff are there these days.
Sorry to bother you and many thanks for your work

**Comment by manguz** [comment]
I mean , i know I can manage to mount the partition and modify with the service
but I don't think it will work early for bootanimations and sounds that reside there.
thanks again

**Comment by topjohnwu** [comment]
I don't plan to add this anytime soon, so I'll close this for now
