### ISSUE TITLE
Stuck into Requires Additional Setup : Setup Failed

### ISSUE THREAD

**Issue by Artificialintelligence64** [topjohnwu/Magisk#4010]
Followed every steps to install Magisk corectly and the phone is also rooted with Magisk. But every time I open Magisk app, it shows "Requires Additional Setup", when tapped on "YES", it always shows "Setup Failed". Also none of the magisk modules are *installing*.

*** I do not have any magisk module installed because none of them are installing but failing to install.

Device: Redmi Note 8 (Pixel Experience Custom ROM)
Android version: 11
Magisk version name: 22.0 (Canary)
Magisk version code: 22000
Log File: [magisk_log_2021-03-11T08_06_18Z.log](https://github.com/topjohnwu/Magisk/files/6120058/magisk_log_2021-03-11T08_06_18Z.log)
Stock Boot Image: [Stock boot image.zip](https://github.com/topjohnwu/Magisk/files/6120128/Stock.boot.image.zip)
Magisk Patched Boot Image: [magisk_patched_KTdQK.zip](https://github.com/topjohnwu/Magisk/files/6120108/magisk_patched_KTdQK.zip)

**Comment by vvb2060** [comment]
```
03-25 18:16:15.577   660   661 I : * Initializing Magisk environment
03-25 18:16:15.605   660   661 E : mkdir /data/adb/magisk 493 failed with 1: Operation not permitted
03-25 18:16:15.606   660   661 E : * Magisk environment incomplete, abort
```
It looks like the ROM of this device is broken.
