### ISSUE TITLE
I can't boot my Pixel 5 into Safe mode when it bootloop.卡開機時無法進入安全模式（updated new information 3/12）

### ISSUE THREAD

**Issue by k5711628** [topjohnwu/Magisk#4011]
Device: Pixel 5
Android version: Android 11(RQ2A.210305.006)
Magisk version name: 43c1105d
Magisk version code: 22004

English:
1. I can't boot my Pixel 5 into Safe mode by holding hot keys when it bootloop.
(This bootloop can be solved by "adb wait-for-device shell magisk --remove-module")

2. I tried to hold the hot keys to boot into Safe Mode. Then I reboot. However, the modules DIDN'T BE DISABLED.

Updated in 3/12:
3. I install the module which used to make my Pixel 5 bootloop, and my Pixel 5 bootloop. 
Then I made my Pixel 5 into bootloader. 
Use the Command "fastboot boot boot.img".
 (Use the official boot.img which didn't be patched by Magisk.)
My Pixel 5 can boot normally.
However, I lost the root permission.
Then I boot into Safe Mode by long pressing Power off button in the screen.
After boot into the Safe Mode, I reboot normally.
Then, the root permission back.
The Pixel 5 could boot normally, and all modules were disabled by Magisk.

中文:
我裝了某個模組，然後卡開機了，這不打緊，因為我可以進"adb wait-for-device shell magisk --remove-module"移除所有模組開機嘛。但是有一個問題，我在卡開機的時候，無論我怎麼重開機，按音量減鍵，都無法進入安全模式。

另外，我移除所有模組後可以正常開機了，但是問題又出現了：
(以下測試的模組，我裝的是正常的模組，不死機的那種）
1：當我用音量減鍵進入安全模式，之後重開機，Magisk並沒有關閉模組
2：但是我透過長按螢幕上的關機/重開機鍵，進入安全模式後再重開機，Magisk確實的把所有模組關閉了

最弔詭的來了：
我透過音量減鍵進入安全模式，之後透過長按螢幕上的關機/重開機鍵，再進入一次安全模式後，再重開機，Magisk把所有模組都關閉了。

看起來是，進入安全模式的方法的不同會影響到Magisk是否會關閉模組

3/12更：我剛剛又嘗試裝了有問題的模組，也就是故意導致bootloop
接著我進bootloader執行
"fastboot boot boot.img(原廠)"
就可以開機了，
當然，暫時喪失root
於是我長按螢幕上的關機鍵
按確定進安全模式
進安全模式後又重開機一次
就可以正常開機
而這時Magisk就會回到
"關閉模組，但不喪失root的狀態"了

請幫忙修正，感謝您

**Comment by shakalaca** [comment]
有辦法抓到按音量鍵進入 safe mode 時的 magisk.log 嗎？

**Comment by k5711628** [comment]
[magisk.log](https://github.com/topjohnwu/Magisk/files/6129377/magisk.log)

**Comment by shakalaca** [comment]
進入 safe mode 的條件有兩個

1. persist.sys.safemode == 1。在重開機選擇進入 safe mode 的時候系統會設定這個值，所以一定會跑 disable_module
2. check_key_combo() 會檢查是否按下 volume down

從你的 log 來看並沒有偵測到 volume down 的事件，所以還是跑正常流程，因此重開機後模組沒有被停用。你先試試看如果看到 google logo 時多按幾下 volume down 會不會讓 magisk 跑 safe mode ?  如果還是沒用，代表可能需要新的偵測按鈕方法..

**Comment by k5711628** [comment]
沒辦法欸，模組依然沒被關閉。
而且一開始bootloop的時候，
我沒辦法用音量鍵進系統的安全模式。

（我猜）時間點也許是這樣？
系統開機=》
系統以persist.sys.safemode判斷要不要進SafeMode=》
Magisk以persist.sys.safemode跟音量鍵判斷要不要載入模組=》
進Google動畫，此時系統開放使用者按音量鍵進Safe Mode(上一步已經載入好模組)

而且官網是這麼寫的：
“當手機開始播放動畫時，按住調低音量按鈕，直到動畫結束且手機以安全模式啟動為止。”
而且加上我自己試了之後，一定要等動畫開播按才會允許使用者按音量鍵進Safe Mode。

我對這部分不是很懂......

**Comment by vvb2060** [comment]
通过长按重启——重新启动并进入安全模式，是在此刻添加persist.sys.safemode，重启后系统会在**system_server**启动时检测到它然后进入安全模式。
在开机时一直按住音量键，系统会在**system_server**启动时检测按键，设置persist.sys.safemode并进入安全模式。

对于情况一，magisk可以在post-fs-data读取 persist 属性，禁用所有模块。
但对于情况二，此时system_server还未启动，magisk必须自己检测按键。如果没有一直按住：过早松开、过晚开始按住或者不断松开按住，可能：仅触发magisk禁用模块、仅触发系统进入安全模式或都没有触发。

**Comment by k5711628** [comment]
> 通过长按重启——重新启动并进入安全模式，是在此刻添加persist.sys.safemode，重启后系统会在**system_server**启动时检测到它然后进入安全模式。
> 在开机时一直按住音量键，系统会在**system_server**启动时检测按键，设置persist.sys.safemode并进入安全模式。
> 
> 对于情况一，magisk可以在post-fs-data读取 persist 属性，禁用所有模块。
> 但对于情况二，此时system_server还未启动，magisk必须自己检测按键。如果没有一直按住：过早松开、过晚开始按住或者不断松开按住，可能：仅触发magisk禁用模块、仅触发系统进入安全模式或都没有触发。

所以system_server是在magisk載入模組後才啟動的嗎？
那我不管怎麼按音量減都沒辦法了啊......

**Comment by k5711628** [comment]
>   （恕刪）......如果還是沒用，代表可能需要新的偵測按鈕方法..

如果說，換個思路，
像magisk --remove-module那樣，
新增一條可以“關掉模組開機”的指令
是否可行？

因為如果是magisk --remove-module的話
還要一個一個把模組裝回來

可是如果是像我這樣按按鍵進不去Safe Mode的人
用“fastboot boot 原廠boot.img"的方法開進Safe Mode
又顯的很迂迴......

**Comment by k5711628** [comment]
更新：
@shakalaca 
我剛剛又試了一次
從螢幕一亮起的瞬間（提示bootloader已解鎖那邊）
斷斷續續的按住音量減鍵
按住一次的時間是“三秒又多一點（0.5秒左右）”
放開又按住
但是！！
Google 動畫一開始動
我就放開按鍵
避免進入“裝置的”安全模式（不然桌面小工具會被移除掉......）
然後進去之後
看了一下log
Magisk有偵測到我按了按鍵了
也的確把模組關了
