### ISSUE TITLE
43c1105d (22004)the version will show namespace #4015

### ISSUE THREAD

**Issue by byxiaorun** [topjohnwu/Magisk#4016]
magisk 43c1105d (22004) show namespace in when su is authorized
![IMG_20210311_235431_418](https://user-images.githubusercontent.com/31344394/110816748-96cbb480-82c6-11eb-8062-db0203061020.jpg)
[magisk_log_2021-03-11T23:50:30Z.log](https://github.com/topjohnwu/Magisk/files/6124320/magisk_log_2021-03-11T23.50.30Z.log)

Device: Xiaomi jason
Android version:9
Magisk version name: 43c1105d
Magisk version code: 22004

**Comment by Didgeridoohan** [comment]
Yup, seeing the same thing when calling su in a terminal app on 22004.

And your log also shows that there are issues with the Magisk log on this build...
