### ISSUE TITLE
16.6和16.7在Nubia(Android 8.1.0)设备上无限重启

### ISSUE THREAD

**Issue by youyim123** [topjohnwu/Magisk#402]
作者你好，我尝试了最近的两个版本v16.6和v16.7 ，正常刷入后重启，手机无法开机一直循环重启。我在刷入了magisk几乎所有版本后发现小于v14的版本正常工作，v14-v16.4可以开机但magisk不工作，v16.6和v16.7刷入后无限重启。

**Comment by breakersvd** [comment]
Please provide device info like: (Model, android version, CPU, Arch.....)
or upload (build.prop) for your device,
and you could try latest beta 16.71 [(Magisk-V16.71.zip)](https://github.com/topjohnwu/Magisk/releases/download/v16.7/Magisk-v16.7.zip)

**Comment by topjohnwu** [comment]
@youyim123 在沒有給我任何資訊的情況下，我無法做任何事情。
等你有新發現在reopen這個issue吧

**Comment by youyim123** [comment]
@breakersvd  I flash latest beta 16.71, and bootloop.

[build.prop.txt](https://github.com/topjohnwu/Magisk/files/2212043/build.prop.txt)
[magisk-v16.7.log](https://github.com/topjohnwu/Magisk/files/2212040/magisk-v16.7.log)
[recovery-v16.7.log](https://github.com/topjohnwu/Magisk/files/2212041/recovery-v16.7.log)
[dmesg-v16.7.log](https://github.com/topjohnwu/Magisk/files/2212042/dmesg-v16.7.log)

**Comment by youyim123** [comment]
@topjohnwu
 device：nubia Z17、Z18mini、red magic
Android：Android8.1.0
CPU：MSM8998、sdm660（Z18 mini）
我刷入v16.4後開機，開機密碼被改變，Magisk Manager狀態未安裝。如果我通過Magisk Manager選擇 Patch Boot Image File後刷入patched_boot.img，Magisk Manager狀態安裝，但Magisk不工作（沒有模塊，su等）。如果你還需要任何有用的東西，我隨時可以效勞。
[log-v16.4.txt](https://github.com/topjohnwu/Magisk/files/2212114/log-v16.4.txt)
[magisk-v16.4.log](https://github.com/topjohnwu/Magisk/files/2212115/magisk-v16.4.log)
[recovery-v16.4.log](https://github.com/topjohnwu/Magisk/files/2212116/recovery-v16.4.log)
[dmesg-v16.4.log](https://github.com/topjohnwu/Magisk/files/2212117/dmesg-v16.4.log)

**Comment by topjohnwu** [comment]
@youyim123 我是有聽說 Magisk 在 nubia 手機上會毀損 data 加密，有人嘗試吳嘉蜜使用是沒有問題的。
你要試試看嗎?

**Comment by youyim123** [comment]
@topjohnwu 我願意試試，我希望Magisk可以在更多設備上完美運行。

**Comment by youyim123** [comment]
你好，最近的v17.2可以在Z18mini上正常工作，但是在Z18（SDM845 Android8.1.0）仍然无限重启，这是cache/boot_fail.log和cache/magisk.log。如果你还需要其他信息，请联系我。感谢！
[log.zip](https://github.com/topjohnwu/Magisk/files/2422544/log.zip)
