### ISSUE TITLE
Magisk 43c1105 (22004) not able to grant root permissions.

### ISSUE THREAD

**Issue by Lishoo** [topjohnwu/Magisk#4021]
Hi, Magisk version 43c1105 (22004) is not able to grant root permissions, when using any file explorer to list root directory there is no Magisk popup to grant root permissions, I even tried to disable the popup and always grant root permissions but it didn't help.
![Screenshot_20210312-170146](https://user-images.githubusercontent.com/1045996/110969777-5d905480-8359-11eb-80a2-5dece857931c.png)
![Screenshot_20210312-170157](https://user-images.githubusercontent.com/1045996/110969789-6123db80-8359-11eb-8bb8-08fd602be418.png)
![Screenshot_20210312-170207](https://user-images.githubusercontent.com/1045996/110969805-65e88f80-8359-11eb-9f4b-31805b4a6d44.png)

Using the same canary build without patching the boot.img with the latest version still works like the main build 22.0
![Screenshot_20210312-172304](https://user-images.githubusercontent.com/1045996/110969918-844e8b00-8359-11eb-9352-f57371c2ff94.png)
![Screenshot_20210312-173001](https://user-images.githubusercontent.com/1045996/110969931-87497b80-8359-11eb-9438-61ffe73e4675.png)
![Screenshot_20210312-173009](https://user-images.githubusercontent.com/1045996/110969952-8b759900-8359-11eb-9121-ad796a36f970.png)

Device: LG G6
Android version:9.0
Magisk version name: 43c1105
Magisk version code: 22004

**Comment by Lishoo** [comment]
Root permissions work if were granted by previous version. But Magisk is not able to grant any new root permissions.

**Comment by Lishoo** [comment]
Reverting back those changes fixes the issue 43c1105d62916a3031bd13ba0cd0e30d6a1fa4db
https://github.com/topjohnwu/Magisk/commit/43c1105d62916a3031bd13ba0cd0e30d6a1fa4db

**Comment by topjohnwu** [comment]
Should be fixed in 22005
