### ISSUE TITLE
Intune Company Portal breaks Magiskhide

### ISSUE THREAD

**Issue by ysaliens** [topjohnwu/Magisk#4026]
Magiskhide no longer works with latest Company Portal Intune app.

Not working: Company Portal Intune 5.0.5084.0
Working: Company Portal Intune 5.0.5067.0

Latest Magisk 22 on both and no other changes except version of intune. Is there some subprocess in the new intune that isn't picked up by Magisk?

Device: OnePlus 7Pro
Android version: 10
Magisk version name: 22
Magisk version code: 22004

**Comment by elnfrov** [comment]
Seeing this issue being closed: is it known cq fixed?

**Comment by skupjoe** [comment]
Can this be reopened?

**Comment by Didgeridoohan** [comment]
#1152
