### ISSUE TITLE
[Feature Request] Add Export Magisk Installer zip file in Magisk App

### ISSUE THREAD

**Issue by Raspberry-Monster** [topjohnwu/Magisk#4031]
Device: 
Android version: Android 11
Magisk version name: Magisk V22
Magisk version code: 22000

It is very important for some users to install Magisk in the recovery.Because some rom (Like MIUI) will replace third-party version of Recovery (Such as TWRP) to manufacturer ones. So If there is no any zip file , some user can't install Magisk conveniently because they cannot flash boot.img unless they use fastboot.
So Could you please add Exporty Magisk Install Zip File in the Magisk App? Thank you !

**Comment by osm0sis** [comment]
The app automatically downloads itself when updating or installing, and the app is the zip, you just need to rename it.
