### ISSUE TITLE
[Feature Request] Add Export Magisk Installer zip file in Magisk App

### ISSUE THREAD

**Issue by Raspberry-Monster** [topjohnwu/Magisk#4032]
Device:
Android version: Android 11
Magisk version name: Magisk V22
Magisk version code: 22004

It is very important for some users to install Magisk in the recovery.Because some rom (Like MIUI) will replace third-party version of Recovery (Such as TWRP) to manufacturer ones. So If there is no any zip file , some user can't install Magisk conveniently because they cannot flash boot.img unless they use fastboot.
So Could you please add Exporty Magisk Install Zip File in the Magisk App? Thank you !

**Comment by pndwal** [comment]
Whats wrong with renaming changing apk extension to zip as per instructions?

**Comment by Raspberry-Monster** [comment]
> Whats wrong with changing .apk extension to .zip as per instructions?

Well, It seems that there is nothing bad happened.
But I think that it is better to make it shows in Magisk App because some rom (Especially Chinese Brand Rom) wil remove apk File(Although you can disable it.) And most people won't read wiki because there are too lazy or they just can't understand English.So they will have no idea if there is no instruction about install Magisk in Magisk App. So I open this issue.
Anyway Thank you for replying me.

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/commit/eaf4d8064b1112a65461f6ede0b2fd7e0a6d9d74 If you use in-app updates, we will save a copy of the apk to storage. If you update via external, just download the apk again.

**Comment by Raspberry-Monster** [comment]
> [eaf4d80](https://github.com/topjohnwu/Magisk/commit/eaf4d8064b1112a65461f6ede0b2fd7e0a6d9d74) If you use in-app updates, we will save a copy of the apk to storage. If you update via external, just download the apk again.

OK Thank you. I will close this issue.
