### ISSUE TITLE
Boot fails if SAR image and /product can't be mounted/is absent at all

### ISSUE THREAD

**Issue by hh85v2** [topjohnwu/Magisk#4039]
Device: Ummidigi Bison
Android version: 10
Magisk version name: canary
Magisk version code: 22004
Issue:

It's a common (thus not good anyway) practice to completely delete /poduct logical partition while flashing GSI ROMs in order to increase the free space to fit /system image. Stock boot init does not care about it, but patched does. After a shot stuck device reboots to bootloader.
There is the log below, while boot with damaged partition In the case of absent one the only difference is that the error message says about 'absent device or smth' instead of 'bad geometry':

[ 1.398153] (5)[1:init]init 8: [libfs_mgr]superblock s_max_mnt_count:65535,/dev/block/dm-2
[ 1.400772] (5)[1:init]EXT4-fs (dm-2): mounted filesystem without journal. Opts:
[ 1.400795] (5)[1:init]init 8: [libfs_mgr]__mount(source=/dev/block/dm-2,target=/vendor,type=ext4)=0: Success
[ 1.401117] (5)[1:init]init 8: [libfs_mgr]superblock s_max_mnt_count:65535,/dev/block/dm-0
[ 1.401689] (5)[1:init]EXT4-fs (dm-0): bad geometry: block count 354341 exceeds size of device (1 blocks)
[ 1.401719] (5)[1:init]init 8: [libfs_mgr]__mount(source=/dev/block/dm-0,target=/product,type=ext4)=-1: Invalid argument
[ 1.401731] (5)[1:init]init 8: Failed to mount /product: Invalid argument
[ 1.401810] (5)[1:init]init 8: Failed to mount required partitions early ...
[ 1.410004] (5)[1:init]init 8: #0 pc 00000000000e33f0 /init
[ 1.410041] (5)[1:init]init 3: #1 pc 000000000006b494 /init
[ 1.410051] (5)[1:init]init 3: #2 pc 000000000006d9f4 /init
[ 1.410059] (5)[1:init]init 3: #3 pc 000000000009e030 /init
[ 1.410066] (5)[1:init]init 3: #4 pc 00000000000631f4 /init
[ 1.410073] (5)[1:init]init 3: #5 pc 000000000014082c /init

If wontfix, please add to troubleshooting section in the docs smth. like 'Magisk is incompartible with GSI
ROMS without /product partition", cause the problem can be not so obvious for ordinary users.

**Comment by hh85v2** [comment]
Ah, it apeared I have been quite wrong about deleting /product parttition is a not-so-good practice. The official Google guide says:

On Android 10 devices that have smaller system partitions, the following error message might appear when flashing the GSI:

` Resizing 'system_a'    FAILED (remote: 'Not enough space to resize partition')`
 ` fastboot: error: Command failed`

Use the following command to delete the product partition and free up space for the system partition. This provides extra space to flash the GSI:

`$ fastboot delete-logical-partition `

Quoted from https://source.android.com/setup/build/gsi#flashing-gsis.

So, this is not a user fault, but a real Magisk issue.

**Comment by topjohnwu** [comment]
First stage init does not modify the init binary in a way that causes any early mount logic changes.
Check the code of `FirstStageInit::prepare` in `twostage.cpp`, the only thing it patches is force init to load from fstab file instead of device tree. All early mount logic is done by the init binary included in the boot image
