### ISSUE TITLE
Magisk enforces /data encryption

### ISSUE THREAD

**Issue by bugsyb** [topjohnwu/Magisk#404]
First of all, great thanks for superb Magisk!

It seems like Magisk re-enforces "/data" to be encrypted. Every time it is installed even on already running Oreo with encryption blocked by remove encryption.zip (https://drive.google.com/file/d/1tCLamw9j07bhRgEd6qhymqUxExazy04c/view), once Magisk zip is installed in the next System boot "/data" gets encrypted and consecutively prohibits any further installs in TWRP, i.e. Xposed, etc.

I'm not alone with these troubles on Oreo (8.0) as others run into them too:
https://forum.xda-developers.com/s7-edge/help/root-8-0-oreo-t3785267/
Somehow it seems like some people are able to keep "/data" unencrypted though it seems to me that Magisk scripts and scripts in "remove encryption.zip" contradict eachother and no-verity-opt-encrypt-6.0.zip didn't change that much as it doesn't allow to keep /data unencrypted.

Unfortunately it didn't work for me. I'm on SM-G930FD and below are scenarios I've tried with TWRP 3.1.1 and TWRP 3.2.2 (as the latter had some problems restoring FlashFire backup).

The moment Magisk v16.0 or v16.7 is installed even with no-verity-opt-encrypt-6.0.zip straight after it (without TWRP reboot), the moment it boots into System, encryption starts or better to say, after next reboot to TWRP, partition is not readable and standard "unable to find crypto footer" is reported by TWRP.

The "remove encryption.zip" doesn't play well with Magisk as if installed after Magisk then Magisk is not visible as App in drawer and even if Magisk apk (v5.8.3) is installed afterwards, it reports Magisk as not installed. The /data would still remain not encrypted, though if Magisk is installed within TWRP afterwards even with "no-verity-opt-encrypt-6.0.zip" then "/data" gets encrypted.

There's one more detail I've noticed - that "remove encryption.zip" causes after reboot that TWRP doesn't ask if it should work in RO mode.

Probably the best would be if Magisk could be updated in a way that it would play well with "remove encryption.zip" or would have a flavour which would disable encryption.

Tests performed (did much more):
Code:

Format ext4
Magisk v16.7
remove encryption
Result: no magisk - but system not encrypted (quick reboot after setup)
reboot
all works nice
reboot to TWRP - /data still readable
reboot to System - all works fine - no Magisk
Magisk install from APK. v5.8.3 (shows status within Magisk as not installed)
TWRP install magisk
Reboot to System (sdcard gets encrypted - no screen security is set)
TWRP shows data as /encrypted

Format ext4
Magisk v16.7
no-verity
Result: FS encrypted

Format ext4
Magisk
no-verity
remove
Result: no magisk installed, but not encrypted

What worked
Format
Magisk
remove encryption
// no magisk yet
reboot TWRP ro
install Magisk v16.7
no-verity
// reboot
// magisk installed but system encrypted

**Comment by ryder203** [comment]
OK... now I know what is going on. For 2 days now I wonder why my Pixel 2 XL gets screwed up when updating ROMs. I remove security features (PIN/fingerprint), flash the update and TWRP patch, reboot the ROM, boot back to TWRP and flash magisk, debloat and use adaway, reboot (without setting PIN/fingerprint) and my device is screwed because all is encrypted and does not boot anymore.
Not even full complete nandroids boot after Magisk encryption mess-up.
This is a serious problem.

**Comment by Zackptg5** [comment]
Have you created a '.magisk' file with FORCEENCRYPT=false in any of these paths: /.backup/.magisk /data/.magisk /cache/.magisk /system/.magisk
magisk 16.7 will throw an error if you put it at the /data location so choose somewhere else (I always use cache. If you don't have a cache partition, use /data/cache). 

Magisk default behavior is to keep whatever verity and forceencrypt settings are already present on your rom/boot.img. This file acts as an override so make this file and place it before flashing magisk

**Comment by bugsyb** [comment]
Above tests were done on S7 and Magisk 16.0.
Since then I've moved to S9 and Magisk 16.7 - didn't observe this problem anymore.
Will try to test again with S7 and Magisk 16.7, but might be able to do it only in 2-3 weeks.

**Comment by arnaudf92** [comment]
Hi,
Same behavior with a rooted S7 and Magisk 16.7
However .magisk file contains FORCEENCRYPT=false.

**Comment by dioni21** [comment]
Hi folks,

Sorry to ask here, but I could not find any other info on this problem.

I’m seeing this in a Samsung S7 exynos, with stock rom 8.0.0, Magisk 18.1 and manager 7.0

Format /data, reset boot, install Magisk, install remove encryption, boot. Everything apparently ok, but some reboots later, /data is again encrypted.

Any help is greatly appreciated.

**Comment by dioni21** [comment]
Humm, maybe it is TWRP’s fault, for not dealing with partitions with quotas in Oreo?

**Comment by Zackptg5** [comment]
@dioni21 
Try this: https://forum.xda-developers.com/android/software/universal-dm-verity-forceencrypt-t3817389
Follow the instructions in the OP

**Comment by dioni21** [comment]
I don't think disabling quota is a good option.  I heard that they use it for some kind of faster space calculation.  I've been doing this in my Unix systems for years!

I will try this version of TWRP as soon as I have time to try all procedure again:

https://forum.xda-developers.com/galaxy-s7/development/recovery-official-twrp-herolte-t3333770/post77296102#post77296102
