### ISSUE TITLE
magiskpolicy syntax error

### ISSUE THREAD

**Issue by gam2046** [topjohnwu/Magisk#4041]
Device: XiaoMi
Android version: API 29
Magisk version name:  21.1
Magisk version code: 21100

I have written a magisk module, which contains one system service.(`ServiceManager.addService`)
But when I got this service, I got an error message:
`E/SELinux:  avc:  denied  { find } for service=fd_llts pid=24681 uid=10171 scontext=u:r:untrusted_app:s0:c171,c256,c512,c768 tcontext=u:object_r:default_android_service:s0 tclass=service_manager permissive=0`
I tried to add such a SELINUX rule, but it didn't work:
`allow untrusted_app default_android_service:service_manager find;`

I tried again through magisk CLI, and got the prompt of syntax error:
```
# magiskpolicy --live "allow untrusted_app default_android_service:service_manager find;"
Syntax error in 'allow untrusted_app default_android_service:service_manager find;'

"allow *source_type *target_type *class *perm_set"
"deny *source_type *target_type *class *perm_set"
"auditallow *source_type *target_type *class *perm_set"
"dontaudit *source_type *target_type *class *perm_set"
```

Is my rule writing wrong, or is there an error in understanding magisk

**Comment by Displax** [comment]
```magiskpolicy --live "allow untrusted_app default_android_service service_manager { find }"```

**Comment by gam2046** [comment]
> `magiskpolicy --live "allow untrusted_app default_android_service service_manager { find }"`

Thanks, I'm new for SELINUX. After I added this rule, I still received an error message
`E/SELinux: avc: denied { find } for service=fd_llts pid=24681 uid=10171 scontext=u:r:untrusted_app:s0:c171,c256,c512,c768 tcontext=u:object_r:default_android_service:s0 tclass=service_manager permissive=0`

Is it because my rules are written incorrectly, or because the service mode I started is incorrect?

I started a program in `service.sh` through `app_process`, and then added a system service.

Here are some information

```
# ps  -Zef
u:r:magisk:s0                  root           889   798 2 21:04:58 ?     00:00:08 com.example.daemon.test
```

I hope that an ordinary application can access the system service provided by me through `Binder` to perform some privileged operations.
