### ISSUE TITLE
Magisk app does not install modules in the latest Canary build

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#4044]
Device: Poco M3
Android version: 10
Magisk version name: f152b4c2
Magisk version code: 22005

The problem of the Magisk installation screen not appearing was fixed in the last Canary build, but now it is not possible to install modules through the app, it closes after the module download is complete. Installation through the command line by magisk64 works normally. Attached is logcat during Magisk update and attempt to install modules by Magisk app.
[logcat.txt.zip](https://github.com/topjohnwu/Magisk/files/6149549/logcat.txt.zip)

**Comment by zgfg** [comment]
Confirming:

Install a module from repo.
On completing the download, Magisk apk 22005 crashes

It leaves Download completed notification - open the notification and Magisk apk restarts (through the splash screen) and only then it continues to install the downloaded module zip file

**Comment by Haus3master** [comment]
> Confirming:
> 
> Install a module from repo.
> On completing the download, Magisk apk 22005 crashes
> 
> It leaves Download completed notification - open the notification and Magisk apk restarts (through the splash screen) and only then it continues to install the downloaded module zip file

I too am getting three same issue on all 3 of my devices...

**Comment by Qyrln** [comment]
> Confirming:
> 
> Install a module from repo.
> On completing the download, Magisk apk 22005 crashes
> 
> It leaves Download completed notification - open the notification and Magisk apk restarts (through the splash screen) and only then it continues to install the downloaded module zip file

Same

**Comment by fcerebel** [comment]
The log is captured with Magisk f152b4c2(22005) on Pixel 3XL with Android 12 DP 2

step to reproduce:
1, Download (chose download and install option) a magisk module. 
2, As soon as the magisk module download finished, it crashes.

_The issue does not occur if Download only is selected in module install option_ 

related (and pretty straightforward) logcat:
> 15992-16165/com.topjohnwu.magisk E/App: java.lang.IllegalStateException: Method setCurrentState must be called on the main thread
>         at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
>         at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:120)
>         at androidx.navigation.NavBackStackEntry.updateState(NavBackStackEntry.java:150)
>         at androidx.navigation.NavBackStackEntry.setMaxLifecycle(NavBackStackEntry.java:130)
>         at androidx.navigation.NavController.popBackStackInternal(NavController.java:326)
>         at androidx.navigation.NavController.navigate(NavController.java:1052)
>         at androidx.navigation.NavController.navigate(NavController.java:944)
>         at androidx.navigation.NavController.navigate(NavController.java:877)
>         at androidx.navigation.NavController.navigate(NavController.java:863)
>         at androidx.navigation.NavController.navigate(NavController.java:1152)
>         at com.topjohnwu.magisk.core.download.DownloadService.onFinish(DownloadService.kt:33)
>         at com.topjohnwu.magisk.core.download.DownloadService.onFinish$suspendImpl(DownloadService.kt:26)
>         at com.topjohnwu.magisk.core.download.DownloadService.onFinish(Unknown Source:0)
>         at com.topjohnwu.magisk.core.download.BaseDownloader.startDownload(BaseDownloader.kt:77)
>         at com.topjohnwu.magisk.core.download.BaseDownloader$startDownload$1.invokeSuspend(Unknown Source:12)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

DownloadService.kt:
https://github.com/topjohnwu/Magisk/blob/master/app/src/main/java/com/topjohnwu/magisk/core/download/DownloadService.kt

**Comment by hwangjr** [comment]
Same on OPPO R9s Android 6.1, Magisk 22005. 
Now I need to download the plugin first, and install from SDCard.

**Comment by tony8077616** [comment]
Same with problem on OnePlus 5T with Android 11
Download only from repo or install from repo may crash

`03-23 07:57:47.975 D/AppCompatDelegate(18475): Exception while getting ActivityInfo
03-23 07:57:47.975 D/AppCompatDelegate(18475): android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{vr.hizq/com.topjohnwu.magisk.core.SplashActivity}
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:467)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at androidx.appcompat.app.AppCompatDelegateImpl.isActivityManifestHandlingUiMode(AppCompatDelegateImpl.java:2649)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at androidx.appcompat.app.AppCompatDelegateImpl.updateForNightMode(AppCompatDelegateImpl.java:2499)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at androidx.appcompat.app.AppCompatDelegateImpl.applyDayNight(AppCompatDelegateImpl.java:2374)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreate(AppCompatDelegateImpl.java:494)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:114)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at com.topjohnwu.magisk.core.SplashActivity.onCreate(SplashActivity.kt:25)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.app.Activity.performCreate(Activity.java:8000)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.app.Activity.performCreate(Activity.java:7984)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.os.Looper.loop(Looper.java:223)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at java.lang.reflect.Method.invoke(Native Method)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-23 07:57:47.975 D/AppCompatDelegate(18475): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-23 07:57:48.089 I/AdrenoGLES-0(18475): QUALCOMM build                   : e883189, Ia11ce2d146
03-23 07:57:48.089 I/AdrenoGLES-0(18475): Build Date                       : 09/02/20
03-23 07:57:48.089 I/AdrenoGLES-0(18475): OpenGL ES Shader Compiler Version: EV031.31.04.00
03-23 07:57:48.089 I/AdrenoGLES-0(18475): Local Branch                     : gfx-adreno.lnx.2.0
03-23 07:57:48.089 I/AdrenoGLES-0(18475): Remote Branch                    : quic/gfx-adreno.lnx.2.0
03-23 07:57:48.089 I/AdrenoGLES-0(18475): Remote Branch                    : NONE
03-23 07:57:48.089 I/AdrenoGLES-0(18475): Reconstruct Branch               : NOTHING
03-23 07:57:48.089 I/AdrenoGLES-0(18475): Build Config                     : S L 10.0.5 AArch64
03-23 07:57:48.089 I/AdrenoGLES-0(18475): Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
03-23 07:57:48.094 I/AdrenoGLES-0(18475): PFP: 0x005ff112, ME: 0x005ff066
03-23 07:57:48.125 I/Gralloc4(18475): mapper 4.x is not supported
03-23 07:57:48.125 W/Gralloc3(18475): mapper 3.x is not supported
03-23 07:57:48.687 I/vr.hizq (18475): The ClassLoaderContext is a special shared library.
03-23 07:57:48.691 I/vr.hizq (18475): The ClassLoaderContext is a special shared library.
03-23 07:57:48.694 W/vr.hizq (18475): ClassLoaderContext classpath size mismatch. expected=1, found=0 (PCL[/system/framework/org.lineageos.platform.jar*4146228725] | PCL[])
03-23 07:57:48.716 V/NativeCrypto(18475): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 287 native methods...
03-23 07:57:48.737 I/ProviderInstaller(18475): Installed default security provider GmsCore_OpenSSL
03-23 07:57:48.824 I/AppCompatDelegate(18475): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
03-23 07:57:48.825 D/AppCompatDelegate(18475): Exception while getting ActivityInfo
03-23 07:57:48.825 D/AppCompatDelegate(18475): android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{vr.hizq/com.topjohnwu.magisk.ui.MainActivity}
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:467)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at androidx.appcompat.app.AppCompatDelegateImpl.isActivityManifestHandlingUiMode(AppCompatDelegateImpl.java:2649)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at androidx.appcompat.app.AppCompatDelegateImpl.updateForNightMode(AppCompatDelegateImpl.java:2499)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at androidx.appcompat.app.AppCompatDelegateImpl.applyDayNight(AppCompatDelegateImpl.java:2374)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreate(AppCompatDelegateImpl.java:494)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:114)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at com.topjohnwu.magisk.arch.BaseUIActivity.onCreate(BaseUIActivity.kt:50)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at com.topjohnwu.magisk.ui.MainActivity.onCreate(MainActivity.kt:42)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.app.Activity.performCreate(Activity.java:8000)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.app.Activity.performCreate(Activity.java:7984)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.os.Looper.loop(Looper.java:223)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at java.lang.reflect.Method.invoke(Native Method)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-23 07:57:48.825 D/AppCompatDelegate(18475): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-23 07:57:48.996 W/System  (18475): A resource failed to call close. 
03-23 07:57:49.217 D/OkHttp  (18475): --> GET https://topjohnwu.github.io/magisk-files/canary.json
03-23 07:57:49.510 E/cutils-trace(18475): Error opening trace file: No such file or directory (2)
03-23 07:57:49.618 D/OkHttp  (18475): <-- 200 OK https://topjohnwu.github.io/magisk-files/canary.json (401ms, unknown-length body)
03-23 07:57:51.073 D/OkHttp  (18475): --> GET https://magisk-modules-repo.github.io/submission/modules.json
03-23 07:57:51.500 D/OkHttp  (18475): <-- 200 OK https://magisk-modules-repo.github.io/submission/modules.json (426ms, unknown-length body)
03-23 07:57:51.546 D/OkHttp  (18475): --> GET https://cdn.jsdelivr.net/gh/Magisk-Modules-Repo/riru-core@54e20f31eb61dfc329d46646059f0650bd3fe452/module.prop
03-23 07:57:51.556 D/OkHttp  (18475): --> GET https://cdn.jsdelivr.net/gh/Magisk-Modules-Repo/riru_lsposed@8836eeb7f4a7ee8b0d1fb101c71f28758496b664/module.prop
03-23 07:57:51.561 D/OkHttp  (18475): --> GET https://cdn.jsdelivr.net/gh/Magisk-Modules-Repo/bromitewebview@27b1f4d84efc6291799d77527da81d21ecbbe98e/module.prop
03-23 07:57:51.782 D/OkHttp  (18475): <-- 200 OK https://cdn.jsdelivr.net/gh/Magisk-Modules-Repo/bromitewebview@27b1f4d84efc6291799d77527da81d21ecbbe98e/module.prop (220ms, 264-byte body)
03-23 07:57:51.783 D/OkHttp  (18475): <-- 200 OK https://cdn.jsdelivr.net/gh/Magisk-Modules-Repo/riru-core@54e20f31eb61dfc329d46646059f0650bd3fe452/module.prop (236ms, 199-byte body)
03-23 07:57:51.791 D/OkHttp  (18475): <-- 200 OK https://cdn.jsdelivr.net/gh/Magisk-Modules-Repo/riru_lsposed@8836eeb7f4a7ee8b0d1fb101c71f28758496b664/module.prop (234ms, 231-byte body)
03-23 07:59:36.307 I/AppCompatDelegate(18475): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
03-23 07:59:38.407 D/OpenGLRenderer(18475): endAllActiveAnimators on 0x71f7aeaae0 (RippleDrawable) with handle 0x7117ae0100
03-23 07:59:38.454 D/OkHttp  (18475): --> GET https://github.com/Magisk-Modules-Repo/riru_lsposed/archive/8836eeb7f4a7ee8b0d1fb101c71f28758496b664.zip
03-23 07:59:39.735 D/OkHttp  (18475): <-- 200 OK https://codeload.github.com/Magisk-Modules-Repo/riru_lsposed/zip/8836eeb7f4a7ee8b0d1fb101c71f28758496b664 (1280ms, 2195480-byte body)
03-23 07:59:39.811 D/OkHttp  (18475): --> GET https://api.github.com/repos/topjohnwu/Magisk/branches/master
03-23 07:59:40.426 D/OkHttp  (18475): <-- 200 OK https://api.github.com/repos/topjohnwu/Magisk/branches/master (614ms, unknown-length body)
03-23 07:59:40.442 D/OkHttp  (18475): --> GET https://cdn.jsdelivr.net/gh/topjohnwu/Magisk@336f1687c12c954161f72aa123bb1feb258146f9/scripts/module_installer.sh
03-23 07:59:40.606 D/OkHttp  (18475): <-- 200 OK https://cdn.jsdelivr.net/gh/topjohnwu/Magisk@336f1687c12c954161f72aa123bb1feb258146f9/scripts/module_installer.sh (163ms, 612-byte body)
03-23 07:59:41.156 E/App     (18475): java.lang.IllegalStateException: Method setCurrentState must be called on the main thread
03-23 07:59:41.156 E/App     (18475): 	at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
03-23 07:59:41.156 E/App     (18475): 	at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:120)
03-23 07:59:41.156 E/App     (18475): 	at androidx.navigation.NavBackStackEntry.updateState(NavBackStackEntry.java:150)
03-23 07:59:41.156 E/App     (18475): 	at androidx.navigation.NavBackStackEntry.setMaxLifecycle(NavBackStackEntry.java:130)
03-23 07:59:41.156 E/App     (18475): 	at androidx.navigation.NavController.popBackStackInternal(NavController.java:326)
03-23 07:59:41.156 E/App     (18475): 	at androidx.navigation.NavController.navigate(NavController.java:1052)
03-23 07:59:41.156 E/App     (18475): 	at androidx.navigation.NavController.navigate(NavController.java:944)
03-23 07:59:41.156 E/App     (18475): 	at androidx.navigation.NavController.navigate(NavController.java:877)
03-23 07:59:41.156 E/App     (18475): 	at androidx.navigation.NavController.navigate(NavController.java:863)
03-23 07:59:41.156 E/App     (18475): 	at androidx.navigation.NavController.navigate(NavController.java:1152)
03-23 07:59:41.156 E/App     (18475): 	at com.topjohnwu.magisk.core.download.DownloadService.onFinish(DownloadService.kt:33)
03-23 07:59:41.156 E/App     (18475): 	at com.topjohnwu.magisk.core.download.DownloadService.onFinish$suspendImpl(DownloadService.kt:26)
03-23 07:59:41.156 E/App     (18475): 	at com.topjohnwu.magisk.core.download.DownloadService.onFinish(Unknown Source:0)
03-23 07:59:41.156 E/App     (18475): 	at com.topjohnwu.magisk.core.download.BaseDownloader.startDownload(BaseDownloader.kt:77)
03-23 07:59:41.156 E/App     (18475): 	at com.topjohnwu.magisk.core.download.BaseDownloader$startDownload$1.invokeSuspend(Unknown Source:12)
03-23 07:59:41.156 E/App     (18475): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-23 07:59:41.156 E/App     (18475): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
03-23 07:59:41.156 E/App     (18475): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
03-23 07:59:41.156 E/App     (18475): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
03-23 07:59:41.156 E/App     (18475): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
03-23 07:59:41.156 E/App     (18475): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
03-23 07:59:41.157 I/vr.hizq (18475): System.exit called, status: 1
03-23 07:59:41.157 I/AndroidRuntime(18475): VM exiting with result code 1, cleanup skipped.
`

**Comment by zgfg** [comment]
Working now with Canary 22006
