### ISSUE TITLE
Magisk Manager still not detecting magisk 

### ISSUE THREAD

**Issue by jeffreyorazulike** [topjohnwu/Magisk#4046]
Device: itel A11
Android version: 6.0
Magisk version name: " f152b4c2 "
Magisk version code: 22005

Magisk manager not still detecting magisk even after flashing patched boot image, I thought that the commit referencing issue #4005 fixed it

![Screenshot_20210316-152640.png](https://user-images.githubusercontent.com/42023982/111331885-9d18b280-8671-11eb-87bd-09f0c7a85b5a.png)

**Comment by Haus3master** [comment]
Not sure why it isn't working for you, but, after patching a fresh image with the latest canary and flashing it, mine works fine... ![Screenshot_20210316-230321.png](https://user-images.githubusercontent.com/66825701/111353977-d837d780-86ab-11eb-84ac-a532a8acc096.png)
Just make sure to reinstall the app after flashing this patched image, just to be sure...

**Comment by Didgeridoohan** [comment]
@jeffreyorazulike judging by your post in #4005, you're experiencing a different issue. The one in that ticket didn't show up with v22.0, but in a later Canary release.

If you've still got issues you need to troubleshoot that and gather relevant information and logs for a new issue ticket.

**Comment by jeffreyorazulike** [comment]
> Not sure why it isn't working for you, but, after patching a fresh image with the latest canary and flashing it, mine works fine... ![Screenshot_20210316-230321.png](https://user-images.githubusercontent.com/66825701/111353977-d837d780-86ab-11eb-84ac-a532a8acc096.png)
> Just make sure to reinstall the app after flashing this patched image, just to be sure... 
Still not working 
Did you use fastboot or your device's flashing tool
