### ISSUE TITLE
Magisk manager not detecting magisk ( N/A)

### ISSUE THREAD

**Issue by akano12** [topjohnwu/Magisk#4047]
Device: samsung galaxy j6+ (sm-j610f)
Android version: 9.0 
Magisk version name: "f152b4c"
Magisk version code: 22005

This issue started since upgrading to magisk to 22004 ("43c1105"),
can't give apps su permission, can't access modules and can't access magisk hide. (screenshot below)

what logs do i need to provide to help detect the issues?
also magisk wasn't hidden/repackaged with different name

![Screenshot_20210316-220018](https://user-images.githubusercontent.com/50032603/111372614-8a1ed600-86a3-11eb-838f-4ecdf644272f.jpg)

**Comment by dantecpu** [comment]
@akano12 I get same message if network is offline, gets right message once connected to internet.

**Comment by jeffreyorazulike** [comment]
Same here, the latest canary build fixed the issue for some devices, mine not included

**Comment by kluknawa235** [comment]
same on Xiaomi mi note 10 with GSI image.
try latest canary but not see

**Comment by ZaxonXP** [comment]
Also does the same on OnePlus 3T with LOS 17.1

**Comment by shakalaca** [comment]
@akano12 would you please grab an output of `adb logcat` when launching the Magisk app ? :)
and did you completely lost su for adb shell ?

**Comment by shakalaca** [comment]
> Also does the same on OnePlus 3T with LOS 17.1
> [magisk_install_log_2021-03-17T19:40:22Z.log](https://github.com/topjohnwu/Magisk/files/6166584/magisk_install_log_2021-03-17T19.40.22Z.log)

22005 works on my OT3T w/ LOS 17.1 (0315 nightly), what's your filesystem for userdata ? is it encrypted ? how did you install magisk ? twrp or patch boot.img ?

**Comment by kluknawa235** [comment]
edit:

I try update TWRP to 3.5.1 on my mi note 10.

download latest canary apk file and i rename to zip file.
after flash this zip file on twrp magisk works now
![Screenshot_20210321-162508_Magisk](https://user-images.githubusercontent.com/20387776/111910635-7fc55900-8a62-11eb-84a0-fd40f76ac206.png)

**Comment by ZaxonXP** [comment]
> > Also does the same on OnePlus 3T with LOS 17.1
> > [magisk_install_log_2021-03-17T19:40:22Z.log](https://github.com/topjohnwu/Magisk/files/6166584/magisk_install_log_2021-03-17T19.40.22Z.log)
> 
> 22005 works on my OT3T w/ LOS 17.1 (0315 nightly), what's your filesystem for userdata ? is it encrypted ?

I did not encrypt user data. I can check if you tell me how. :)

Also I tried to update my TWRP to the latest and do as @kluknawa235 suggested. It did not work. I still have the Magisk Installed status as N/A. What else could I try?
![Screenshot_20210321-212402_Magisk](https://user-images.githubusercontent.com/6058640/111920188-f461bd00-8a8d-11eb-8891-84a060b1ca12.png)

**Comment by shakalaca** [comment]
@ZaxonXP would you please grab me the log ?
1. Reboot your phone
2. execute `adb logcat > log.txt` on your computer
3. Launch Magisk app
4. Ctrl + C to save the log

**Comment by ZaxonXP** [comment]
Here is the log file: 
[logcat.txt](https://github.com/topjohnwu/Magisk/files/6182154/logcat.txt)

**Comment by tinloaf** [comment]
I seem to have hit the same bug. I just installed Magisk v. 22.0 on my Xiaomi Mi 8 ("dipper") running LineageOS (Nightly build from 2021-02-11). Magisk shows installed as "N/A", and when starting the Magisk app, I get a toast notification informing me that root access was denied to Magisk.

Here is a log from opening the Magisk app right after system start: https://cloud.tinloaf.de/s/QMztpmyd6D4cM7g

**Comment by krafi99** [comment]
> Device: samsung galaxy j6+ (sm-j610f)
> Android version: 9.0
> Magisk version name: "f152b4c"
> Magisk version code: 22005
> 
> This issue started since upgrading to magisk to 22004 ("43c1105"),
> can't give apps su permission, can't access modules and can't access magisk hide. (screenshot below)
> 
> what logs do i need to provide to help detect the issues?
> also magisk wasn't hidden/repackaged with different name
> 
> ![Screenshot_20210316-220018](https://user-images.githubusercontent.com/50032603/111372614-8a1ed600-86a3-11eb-838f-4ecdf644272f.jpg)

Do you know what the last working version was?

**Comment by dwdjanika** [comment]
- [x]  ~~~~

**Comment by Didgeridoohan** [comment]
@tinloaf You might not be experiencing the bug that's described in this issue. You might have both a hidden and regular Magisk app installed:
https://www.didgeridoohan.com/magisk/Magisk#hn_Magisk_app_was_denied_superuser_access

**Comment by tinloaf** [comment]
@Didgeridoohan Indeed. It wasn't the two-apps problem, but I had a stale database under /data/adb/magisk.db. I had recovered my phone after a wipe, and restored a backup I had of /data. That probably got the database there… thanks!

**Comment by FatihAlper** [comment]
I'm facing with same issue. Tried multiple times in canary and 22.0 stable branch, with fresh install but no luck. Device is J320-H. Also totally agree with the op. The problem started with 22.0 Upgrade.

**Comment by ZaxonXP** [comment]
> @tinloaf You might not be experiencing the bug that's described in this issue. You might have both a hidden and regular Magisk app installed:
> https://www.didgeridoohan.com/magisk/Magisk#hn_Magisk_app_was_denied_superuser_access

Removing Magisk by adb command, then reinstalling Magisk solved the problem in my case. Thank you @tinloaf for mentioning this. :)

**Comment by krafi99** [comment]
What is the solution to this issue?

**Comment by Brt-L** [comment]
Just responding on the title: Magisk Manager not detecting magisk ...

If a previous version of Magisk was repackaged (renamed/hidden), the name of this package is saved in /data/adb/magisk.db. If after installing a new version, the Manager doesn't detect magisk, find in this .db file the 'strings' table and change the value of key 'requester' to 'com.topjohnwu.magisk'. If you copy the .db file to a Linux OS, you can easily modify it with sqlite and then in recovery mode put it back in place. If no other problem raised beside, Magisk Manager will now detect magisk.

Make sure meanwhile the old repacked version of Magisk is deleted ...

Maybe some automatic check/repair can be build into the installation procedure ?

Happy *** Magisking ***

Bart.
