### ISSUE TITLE
Latest Magisk Manager Removed Camera from rom

### ISSUE THREAD

**Issue by dantecpu** [topjohnwu/Magisk#4048]
Updated from 22004 to 22005, init sepoolicy changements removed camera from rom, revert to 22004 restored camera on Android 11.

rom here: https://github.com/zeelog/OTA/releases/tag/38.0

**Comment by dantecpu** [comment]
You closed bug, but bug is still there bot

**Comment by Didgeridoohan** [comment]
> You closed bug, but bug is still there bot

That's because, just like it said, you did not follow the issue template...
