### ISSUE TITLE
Segmentation fault during patching boot with integrated TWRP

### ISSUE THREAD

**Issue by Displax** [topjohnwu/Magisk#4049]
Device: Xiaomi Mi A1
Android version: 9
Magisk version name: f152b4c2
Magisk version code: 22005

Yes, I know Magisk shouldn't be perfectly compatible with integrated TWRP in boot.img. But anyway, this behavior has not happened before 22000, I think.
If wontfix - it's OK, but maybe someone take a look at this.

boot.img: https://drive.google.com/file/d/1Huw6LPW3bCLrngckWUCu7aGdOx5Ht_Dx/view?usp=sharing
log:
```
- Target image: /dev/block/mmcblk0p23
- Device platform: arm64-v8a
- Installing: f152b4c2 (22005)
- Unpacking boot image
Parsing boot image: [/dev/block/mmcblk0p23]
HEADER_VER      [1]
KERNEL_SZ       [9866617]
RAMDISK_SZ      [18271145]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2020-08]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992]
CHECKSUM        [b5a3f652ac387570269b5683ff05ae4004b3324e000000000000000000000000]
Segmentation fault
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Parsing boot image: [/dev/block/mmcblk0p23]
- Repacking boot image
HEADER_VER      [1]
KERNEL_SZ       [9866617]
RAMDISK_SZ      [18271145]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2020-08]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992]
CHECKSUM        [b5a3f652ac387570269b5683ff05ae4004b3324e000000000000000000000000]
Segmentation fault
! Unable to repack boot image!
! Installation failed

```

**Comment by osm0sis** [comment]
Sounds like a regression after the magiskboot refactor. Thanks for the solid report. 👍

**Comment by osm0sis** [comment]
@topjohnwu, I can confirm the seg fault with a manual attempt to unpack with magiskboot 22005:
```
:/data/local/tmp # /data/adb/magisk/magiskboot unpack boot.img
Parsing boot image: [boot.img]
HEADER_VER      [1]
KERNEL_SZ       [9866617]
RAMDISK_SZ      [18271145]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2020-08]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992]
CHECKSUM        [b5a3f652ac387570269b5683ff05ae4004b3324e000000000000000000000000]
Segmentation fault
139|:/data/local/tmp #
```


AIK-mobile unpacks without issue, seems like a normal unsigned hdr_v1 boot.img:
```
Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers

Supplied image: boot.img

Setting up work folders...

Image type: AOSP

Splitting image to "split_img/"...
BOARD_KERNEL_CMDLINE console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992
BOARD_KERNEL_BASE 0x80000000
BOARD_NAME 
BOARD_PAGE_SIZE 2048
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x01000000
BOARD_SECOND_OFFSET 0x00f00000
BOARD_TAGS_OFFSET 0x00000100
BOARD_OS_VERSION 9.0.0
BOARD_OS_PATCH_LEVEL 2020-08
BOARD_HEADER_VERSION 1
BOARD_HEADER_SIZE 1648

Unpacking ramdisk to "ramdisk/"...

Compression used: gzip
101041 blocks

Done!
```

**Comment by osm0sis** [comment]
I'll tackle the boot_patch.sh part of the issue.

**Comment by DespairFactor** [comment]
I have this with a stock P4XL ramdisk as well with custom kernel. I was just searching for this. Stable unpacks fine, but get segfaults on unpacking with canary. Below are the logs if it helps any.

Stable:
 - Device platform: arm64-v8a
- Installing: f152b4c2 (22005)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [15495312]
RAMDISK_SZ      [10147831]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [496473]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 androidboot.console=ttyMSM0 msm_rtb.filter=0x237 ehci-hcd.park=3 service_locator.enable=1 cgroup.memory=nokmem usbcore.autosuspend=7 androidboot.usbcontroller=a600000.dwc3 swiotlb=2048 androidboot.boot_devices=soc/1d84000.ufshc loop.max_part=7 buildvariant=user]
CHECKSUM        [433a715d1aedd2b165dec896d6d69436c67bac08000000000000000000000000]
KERNEL_DTB_SZ   [496473]
KERNEL_FMT      [lz4]
RAMDISK_FMT     [gzip]
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [dtb]
Loading dtbs from [kernel_dtb]
Patch @ 01DE566C [736B69705F696E697472616D667300] -> [77616E745F696E697472616D667300]
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [15495312]
- Repacking boot image
RAMDISK_SZ      [10147831]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [496473]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 androidboot.console=ttyMSM0 msm_rtb.filter=0x237 ehci-hcd.park=3 service_locator.enable=1 cgroup.memory=nokmem usbcore.autosuspend=7 androidboot.usbcontroller=a600000.dwc3 swiotlb=2048 androidboot.boot_devices=soc/1d84000.ufshc loop.max_part=7 buildvariant=user]
CHECKSUM        [433a715d1aedd2b165dec896d6d69436c67bac08000000000000000000000000]
KERNEL_DTB_SZ   [496473]
KERNEL_FMT      [lz4]
RAMDISK_FMT     [gzip]
Repack to boot image: [new-boot.img]
HEADER_VER      [2]
KERNEL_SZ       [15495312]
RAMDISK_SZ      [10493526]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [496473]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 androidboot.console=ttyMSM0 msm_rtb.filter=0x237 ehci-hcd.park=3 service_locator.enable=1 cgroup.memory=nokmem usbcore.autosuspend=7 androidboot.usbcontroller=a600000.dwc3 swiotlb=2048 androidboot.boot_devices=soc/1d84000.ufshc loop.max_part=7 buildvariant=user]
CHECKSUM        [c5694e6f49e791257a22fcf5352a08c644e1e4d4000000000000000000000000]

****************************
 Output file is written to 
 /storage/emulated/0/Download/magisk_patched_zeCpQ.img 
****************************
- All done!


Canary: 

- Device platform: arm64-v8a
- Installing: f152b4c2 (22005)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [27719279]
RAMDISK_SZ      [12421915]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [497099]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 androidboot.console=ttyMSM0 printk.devkmsg=on msm_rtb.filter=0x237 ehci-hcd.park=3 service_locator.enable=1 androidboot.memcg=1 cgroup.memory=nokmem usbcore.autosuspend=7 androidboot.usbcontroller=a600000.dwc3 swiotlb=2048 androidboot.boot_devices=soc/1d84000.ufshc buildvariant=user]
CHECKSUM        [a17800a8171bf565799da41373d5f35c8e813ed1000000000000000000000000]
Segmentation fault
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [27719279]
RAMDISK_SZ      [12421915]
SECOND_SZ       [0]
- Repacking boot image
RECOV_DTBO_SZ   [0]
DTB_SZ          [497099]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 androidboot.console=ttyMSM0 printk.devkmsg=on msm_rtb.filter=0x237 ehci-hcd.park=3 service_locator.enable=1 androidboot.memcg=1 cgroup.memory=nokmem usbcore.autosuspend=7 androidboot.usbcontroller=a600000.dwc3 swiotlb=2048 androidboot.boot_devices=soc/1d84000.ufshc buildvariant=user]
CHECKSUM        [a17800a8171bf565799da41373d5f35c8e813ed1000000000000000000000000]
Segmentation fault
! Unable to repack boot image!
! Installation failed
