### ISSUE TITLE
pixel 2 xl android p beta 3 使用16.7无法开机

### ISSUE THREAD

**Issue by Sherlock-Holo** [topjohnwu/Magisk#406]
手机pixel 2 xl 64G版，系统为android p beta3 (dp4) ，刷入了16.7，magisk manager为最新版，使用patch boot.img方式刷入，开机卡在了白屏过进度条这里

PS: 16.6根本无法patch dp4的boot.img所以无法测试16.6是否工作正常

**Comment by vvb2060** [comment]
pixel2 android p beta4 (dp5) ，magisk 16.7，patch boot方式，工作正常。

**Comment by Sherlock-Holo** [comment]
已更新dp5，尚未测试magisk

vvb2060 <notifications@github.com> 于 2018年7月31日周二 20:14写道：

**Comment by Sherlock-Holo** [comment]
@vvb2060 pixel 2 xl dp5 magisk 16.7，patch boot方式

- 保持强制加密和保留avb2.0没勾选 失败
- 保持强制加密和保留avb2.0 勾选 失败

**Comment by Sherlock-Holo** [comment]
具体表现在开机已出现G，下面进度条不停的过可是过了很久都没反应

**Comment by Sherlock-Holo** [comment]
https://fars.ee/3v3h/ 这是选择了保留强制加密的开机log
- 保留强制加密勾选 开机失败

**Comment by Sherlock-Holo** [comment]
https://fars.ee/cp_4/ 这是正常开机log

**Comment by topjohnwu** [comment]
Fixed in 59f78d7dfce51d3f61351bb60ceb2dfd727c0daa
