### ISSUE TITLE
Brick after update to v22.0 (RAZER PHONE)

### ISSUE THREAD

**Issue by PrzemoVi** [topjohnwu/Magisk#4078]
Device: RAZER PHONE 1
Android version: 8.0
Magisk version name: V22.0
Magisk version code: ---

I had many troubles while installing magisk on this device because of Slot A&B policy, everything was working property until last update - I clicked "begin" as always with same settings and nothing happened. I tried three times.
I thought it was network problem so I closed magisk and left it for later.
When by battery ran out and my device shut down and I was unable to boot it on slot A or B. I was stuck on first razer logo.
My boot image was bricked, I was unable to enter recovery or fastboot.
After an hour I finally managed to enter fastboot and flashed stock boot.img and now my phone is working property.

And now I don't know what to do next - patch stock boot.img using magisk and flash it?
But what about TWRP?
Last time I had to boot TWRP and then patch both boot images using twrp flashable zip, and then, finally install magisk .zip.
Do I really have to flash twrp, copy patched image to memory, patch using magisk and flash it again using TWRP?
This new installation procedure is overcomplicated.

I just want you to fix updater - I bricked my device while I was 500km from my home, app was not responding, there was no progress-bar or anything indicating that an update was in progress.

Thanks.

**Comment by KaMyKaSii** [comment]
This issue has probably already been fixed in Canary
https://github.com/topjohnwu/Magisk/issues/3949
