### ISSUE TITLE
Sign releases with pgp and/or provide sha256sum's or md5

### ISSUE THREAD

**Issue by Perflyst** [topjohnwu/Magisk#408]
Hi

Could you provide sha256sum or md5 file sum? 
This way users can be sure that the file is not broken or that something went wrong during the download.
If you could sign the releases with a pgp key, as the LineageOS team does, the security would be even better.

**Comment by ShadySquirrel** [comment]
+1 for PGP key signing and file hashsum, there are lots of fake flashable zips on the web...

**Comment by topjohnwu** [comment]
I will start signing all release zips with the same key used in Magisk Manager. I will provide the fingerprint of the certificate so you can use JDK's `keytool` and `jarsigner` to verify the signature and certificate

**Comment by adombeck** [comment]
>  I will provide the fingerprint of the certificate

I can't find the fingerprint. Did you publish it somewhere?

**Comment by yan12125** [comment]
> I can't find the fingerprint. Did you publish it somewhere?

FWIW, I found it here: https://github.com/topjohnwu/Magisk/blob/master/README.MD#signature-verification
