### ISSUE TITLE
"ZOOM Cloud Meetings" Detecting Root

### ISSUE THREAD

**Issue by CyberSolutions8799** [topjohnwu/Magisk#4086]
Even though SafetyNet Check is passes and I've hidden the app in MagiskHide, the app is still detecting root.
I'm using Magisk v22.

**Proof:** https://imgur.com/a/SKOtU98
**Zoom App:** https://play.google.com/store/apps/details?id=us.zoom.videomeetings

**Comment by Didgeridoohan** [comment]
@CyberSolutions8799 You haven't hidden all components of Zoom (see the red bar above the app in the Hide list). Do that and it'll work.

**Comment by e-t-l** [comment]
I have this problem even though Zoom is installed on a Work Profile, and Magisk is set to "Only owner has root access." Any idea how/why Zoom is still detecting root?
