### ISSUE TITLE
Samsung One UI 3 - No root, failed recovery state

### ISSUE THREAD

**Issue by ArmynC** [topjohnwu/Magisk#4093]
Seems that since One UI 3, trying to enter in the root state, by accessing the combo recovery, results in `[PDP] Back-up : fail setup-wizard [ FINISH ]` error and no root. Everytime after a reboot, in order to access the rooted environment is necessary to insert in the phone a pc connected usb-c interface.

I'm not aware how widespread it is, but that's how it works for me, so I think that this one should be stated in the documents.

Device: Samsung Galaxy S10
Android version: 11
Magisk version name: fb8dc07
Magisk version code: 22006

**Comment by NULL0B** [comment]
Yes the pc is required. The key combo patch needs to be extended. With Corsicanu TWRP i was able to boot to recovert whitout PC so is a good point to start looking for a patch.
Currently im using LADB to enter in adb privileges and command `reboot recovery` you need to be connected to wifi though.

**Comment by elcosomalo1** [comment]
+1 here...  I'm with the exact same issue of having to reboot into recovery with the USB-C cable connected. I'm on a Note 10 (N970F)

**Comment by threejsmaster** [comment]
I'm have this problem but connecting USB-C don't work.

**Comment by Shituation** [comment]
> I'm have this problem but connecting USB-C don't work.

Try connecting your phone to an active USB-C cable (plugged to pc) then with the cable connected, hold power + Vol up until past the screen that says bootloader is unlocked and tells you to press the power key to continue DO NOT LET GO THE KEYS (power + vol up) UNTIL YOU PASS THIS SCREEN. Then when the phone continues to the next screen telling that the rom is not the original LET GO the keys. You will not see anything different, but when the phone boots up, go to magisk app and it should have the root manager enabled.
