### ISSUE TITLE
sepolicy wrong status on latest canary

### ISSUE THREAD

**Issue by NarwanyZiomus** [topjohnwu/Magisk#4098]
On latest version its starts showing On LSPosed that message.
![Screenshot_20210325-143723_LSPosed](https://user-images.githubusercontent.com/41604636/112483861-b6a8b100-8d79-11eb-8971-279499dfd7f2.jpg)

API version
93

Framework version
v1.3.4 (5501)

Manager version
v1.3.4 (5501)

System version
11 (API 30)

Device
Samsung SM-G996B

System ABI
arm64-v8a

Device: SM-G996B
Android version: 11
Magisk version name: 66e30a77
Magisk version code: 22006

**Comment by alroy214** [comment]
API version
93

Framework version
v1.3.4 (5501)

Manager version
v1.3.4 (5501)

System version
11 (API 30)

Device
Samsung SM-N986B 

System ABI
arm64-v8a

**Comment by NarwanyZiomus** [comment]
So for sure its 22006,ive restore twrp backup which was made yesterday on 22005. I swap LSPosed to edxposed to be sure. 
![Screenshot_20210325-144405](https://user-images.githubusercontent.com/41604636/112486737-71d24980-8d7c-11eb-9a28-d7130a9678d6.jpg)
Now i goin to update to 22006 via magisk app and lets see what happened with edxposed and firefds for example

**Comment by alroy214** [comment]
> UPDATE!!!
> 
> SO edxposed with firefds works after swap LSPosed to edxposed then patch 22006 via magisk reboot and voila
> ![Screenshot_20210325-151736_EdXposed Manager](https://user-images.githubusercontent.com/41604636/112488313-b8747380-8d7d-11eb-9864-63cae96cfe31.jpg)
> ![Screenshot_20210325-151813_Firefds Kit R](https://user-images.githubusercontent.com/41604636/112488337-be6a5480-8d7d-11eb-8f37-adde538ad1fb.jpg)
> 
> So for sure its 22006,ive restore twrp backup which was made yesterday on 22005. I swap LSPosed to edxposed to be sure.
> ![Screenshot_20210325-151340](https://user-images.githubusercontent.com/41604636/112487124-c5dd2e00-8d7c-11eb-9e5a-9ba5444d436e.jpg)
> ![Screenshot_20210325-151523_EdXposed Manager](https://user-images.githubusercontent.com/41604636/112487421-fae98080-8d7c-11eb-9b5a-91a2d6b63537.jpg)
> 
> Now i goin to update to 22006 via magisk app and lets see what happened with edxposed and firefds for example

Can you check if Xposed-Edge works? Cause the policy is not working and causes it to crash in boot

**Comment by NarwanyZiomus** [comment]
Nope it doesn't work 
![Uploading Screenshot_20210325-161044_Xposed edge.jpg…]()

**Comment by osm0sis** [comment]
Magisk Install log shows part of the issue as well:
```
- Flashing new boot image
mkdir: can't create directory '/dev/T99XCO5/.magisk/mirror/sepolicy.rules/': No such file or directory
cp: can't create '/dev/T99XCO5/.magisk/mirror/sepolicy.rules/quickstepswitcher/sepolicy.rule': Path does not exist
- All done!
```

**Comment by dangelization** [comment]
I got 22005 working fine with LSPosed, but 22006 breaks it.
Same problem reported as OP, LSPosed says SEPolicy is not loaded properly. Oneplus 7Pro running android 11.
Let me know if anyone needs log(and what log do you need). I have already reverted back to 22000.

**Comment by Howard20181** [comment]
Same here
[20210328.zip](https://github.com/topjohnwu/Magisk/files/6217064/20210328.zip)

**Comment by No-WaY-SA** [comment]
Sorry I have same problem 
![Screenshot_20210404-015034_Firefds Kit  R](https://user-images.githubusercontent.com/68426919/113494821-d61ba880-94f4-11eb-926d-d568191bdb0b.jpg)
![Screenshot_20210402-184343_LSPosed](https://user-images.githubusercontent.com/68426919/113494831-e03da700-94f4-11eb-88bf-bb936a0a6612.jpg)

How to solve it?

**Comment by osm0sis** [comment]
It's fixed in the next canary release.

**Comment by No-WaY-SA** [comment]
how i can get it please? I'm on 22 stable
and canary channel shows only 22003

**Comment by osm0sis** [comment]
Update to 22003, then you'll see 22006 and can update to that, then wait for the next canary. Keyword next.

**Comment by No-WaY-SA** [comment]
Thanks it fixed now

**Comment by DestroyerXyz** [comment]
How do I get Canary? I am currently on 23000

**Comment by osm0sis** [comment]
Check the README
