### ISSUE TITLE
MagiskManager and 'latest' version

### ISSUE THREAD

**Issue by computersalat** [topjohnwu/Magisk#410]
Hi,

MagiskManager (5.7.0 - 5.8.3) does show `v16.0` as `latest version`.
Shouldn't it show `v16.7` as `latest version` ?

**Comment by dark-basic** [comment]
Magisk v.16 is stable
Magisk v.16.7 is a beta
in the magisk settings. you can choose the update channel.
Sorry for my English. 😅😅😅

**Comment by computersalat** [comment]
@dark-basic 
aaah ... why not adding `beta` to version string ? This would be self-explaining ...
Anyway thank you for clarification.
And about your English ... I don't think mine is better ;-)
