### ISSUE TITLE
No root installed magisk N/A on all versions since 22001 on Intel x86 Android 6.0.1 patched boot.img

### ISSUE THREAD

**Issue by martyfender** [topjohnwu/Magisk#4103]
Device: nextbook ares 8a intel x86
Android version:6.0.1
Magisk version name: canary 22006
Magisk version code: 22006

I save the patched boot.img from 22001 and it works fine. All newer versions show magisk as installed as na. 
Attached is a twrp recovery log, but the only magisk seen in twrp file manager is from 22001, so it appears that no new magisk log is being created after flashing and rebooting the system. 
[recovery.log](https://github.com/topjohnwu/Magisk/files/6208239/recovery.log)
[boot.zip](https://github.com/topjohnwu/Magisk/files/6208250/boot.zip)

I also tried direct install and flashing suceeds but upon roboot no root is installed, in magisk manager it also shows installed N/A.

Attached is the magisk.log saved in mm from the working canary 22001, if that may be useful. 
[magisk_log_2021-03-25T19:15:34Z.log](https://github.com/topjohnwu/Magisk/files/6208380/magisk_log_2021-03-25T19.15.34Z.log)

UPDATE: attached is a boot logcat after flashing 22006.
[bootlogcat.txt](https://github.com/topjohnwu/Magisk/files/6208620/bootlogcat.txt)

All of the previous versions since 22001 work fine on my 2, Onn 8, Android 9 devices, using the patched boot.img method and flashing in TWRP.
Thanks

**Comment by shakalaca** [comment]
any log for launching Magisk app ?

**Comment by Haus3master** [comment]
In not sure about x86, but, the issue you mentioned previously happened on arm64-v8a devices, but, this was fixed about 2-3 updates ago...

**Comment by martyfender** [comment]
> 
> 
> any log for launching Magisk app ?
[logcat.txt](https://github.com/topjohnwu/Magisk/files/6212018/logcat.txt)

**Comment by shakalaca** [comment]
> > any log for launching Magisk app ?
> > [logcat.txt](https://github.com/topjohnwu/Magisk/files/6212018/logcat.txt)
> 
> Is this what you mean? This is an adb logcat where I launched the magisk app then closed it.

yeap, but I didn't see the log of su handler. Can you show me the result of `pm dump com.topjohnwu.magisk|grep CpuAbi` ?

**Comment by martyfender** [comment]
> > > any log for launching Magisk app ?
> > > [logcat.txt](https://github.com/topjohnwu/Magisk/files/6212018/logcat.txt)
> > 
> > 
> > Is this what you mean? This is an adb logcat where I launched the magisk app then closed it.
> 
> yeap, but I didn't see the log of su handler. Can you show me the result of `pm dump com.topjohnwu.magisk|grep CpuAbi` ?

How do I do that, adb or adb shell? I tried in a terminal app  ut didn'g get anything?

**Comment by shakalaca** [comment]
1. can you execute `su` from adb shell ?
2. if you can run `su`, what's the output of command `busybox` ?

**Comment by martyfender** [comment]
I'm looking forward to a new build to test.

Thanks

**Comment by martyfender** [comment]
Thanks everyone for fixing this issue. I will now close it.
