### ISSUE TITLE
Magisk 22+ not detect and/or crashing on android 6.0.1 arm v7a 

### ISSUE THREAD

**Issue by valuesw** [topjohnwu/Magisk#4107]
Device: Samsung Galaxy Note 4
Android version: 6.0.1
Magisk version name: 22 
Magisk version code: 22006

Magisk 22+ not detect and/or crashing on android 6.0.1 arm v7a

Magisk 21.4 works great. but when I update the manager to version 22 or up, magisk binary does not detected and the application crashing. this applies to all magisk 22+ builds, including stable/beta/canary. please fix this

**Comment by xtexChooser** [comment]
Me, too. I am SMG9008W, Android 6.0.1.
The modules look like running correctly on my device, but the manager tell me "Installed N/A"

**Comment by valuesw** [comment]
> 
> 
> Me, too. I am SMG9008W, Android 6.0.1.
> The modules look like running correctly on my device, but the manager tell me "Installed N/A"
> But the "Ramdisk" is Yes

same.

**Comment by DrSaad77** [comment]
Hi, I have the same issue on Marshmallow 6.0.1
v.21.4 is working fine, and when I update Manager to v.22, hop the pb start, impossible to install Magisk Root anymore...
Can someone look into this please?? of course I am ready to provide any log required.
![Screenshot_2021-03-31-20-34-29](https://user-images.githubusercontent.com/36936960/113255256-472e4680-92d0-11eb-9e98-52e20a7755ff.png)

**Comment by pndwal** [comment]
Did ANY of you guys forget to UnHide / Restore hidden Manager / app from Settings BEFORE updating, as per 22(000) series release Notes? PW

**Comment by DrSaad77** [comment]
dont worry I took care of that point.
Actually it was never turned on. I mean I can not trn off Hide, or UnHide in Setting, if at the start this feature is not used by me.
I made sure the tick is turned off before to update to v.22, and still error when trying to update Magisk.
Manager itself is updating to v.22 fine, I mean the apk is being install, then when I open Magisk, I get this:
![Screenshot_2021-03-31-20-40-17](https://user-images.githubusercontent.com/36936960/113269235-ed824800-92e0-11eb-8312-2d3151a526f0.png)
Plus this error when trying to install Root.
![Uploading Screenshot_2021-03-31-20-34-29.png…]()

**Comment by xtexChooser** [comment]
> Did ANY of you guys forget to UnHide / Restore hidden Manager / app to normal (unhidden) from Settings BEFORE updating app (not Magisk root), as per 22(000) series release Notes? PW

I uninstalled and installed the old version of manager.
Magisk is detected and then I disabled Magisk Hide and all modules.
Then I re-installed the new version of manager but Magisk is still not detected

**Comment by leppit** [comment]
Hi,

Issue with: Magisk 22006 and other 22+
Channel: Canary, but also on others
Plattform: Android 6.0 Marshmallow, armeabi-v7a
Device: Samsung Note 4 SM-N910F
UI: TouchWiz
Recovery: TWRP

Magisk_install_log
- Target image: /dev/block/
- Device platform: armeabi-v7a
- Installing: 66e30a77 (22006)
! Unable to check signature
! Installation failed

- I get this log when I try to install Magisk within the Messenger.
- Patching by TWRP with Devik delete works.
- SU requests afterward pop up properly, may be granted, but are not remembered

Issue 1: Magisk (Manager) does not install/patch within the app, creating that signature error
Issue 2: Magisk (Manager) does not detect patched Magisk, shows only n/a
Issue 3: Magisk (Manager) wants to install current Manager though it is installed
Issue 4: Magisk (Manager) does not offer all features to control SU, hide, etc., though Magisk is patched and SU requests working

Done so far without solving the problem:
- uninstalled/reinstalled Manager
- unpatched/repatched stock boot vi TWRP
- repatched Magisk boot-image

Last Version without these Issues:
Magisk 8.0.7 (pre 22)

**Comment by leppit** [comment]
see also  #4169

**Comment by xtexChooser** [comment]
I think it is only because the manager can not detect.
The terminal can run `magisk -v` or `magisk -V` correctly

**Comment by leppit** [comment]
> 
> 
> I think it is only because the manager can not detect.
> The terminal can run `magisk -v` or `magisk -V` correctly

yes, terminal replies corrrect Magisk Version Name -V and Code -v

see also issue #4173
