### ISSUE TITLE
Infinix Hot 10 X682C (MTK hdr_v2) Boot loop from patched boot/recovery

### ISSUE THREAD

**Issue by o-kotb** [topjohnwu/Magisk#4112]
Device: infinix hot 10 X682C
Android version: Android 10 (it says XOS v7.0.0 but I don’t think it matters)
Magisk version name: 66e30a77
Magisk version code: 22006
[boot.img mega link](https://mega.nz/file/Ow5RWARY#rj6WPAhUBZkB4U9FkF89uLoqmnCF6aqWc9iYzdlKtnE) 
[“cat /proc/mounts” output](https://pastebin.com/4Nur28nh) 
I’m unable to provide dmesg logs as I can’t root.

Every time I flash either the boot or recovery images, my phone boot loops. It boots up with the infinix logo and says

“Orange State

Your device has been unlocked and can't be trusted
Your device will boot in 5 seconds” then reboots.

I can’t even access recovery mode. I can’t do anything but use sp flash tool to unbrick my device.

I can’t use twrp either as there are no official builds and my device needs to be rooted to build one on my own.

**Comment by relaxeaza** [comment]
Same with Moto G5S Plus

**Comment by osm0sis** [comment]
@topjohnwu, looks like a fairly normal boot.img:

```

Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers

Supplied image: boot.img

Setting up work folders...

Image type: AOSP

Signature with "AVBv2" type detected.

Splitting image to "split_img/"...
BOARD_KERNEL_CMDLINE bootopt=64S3,32N2,64N2 buildvariant=user
BOARD_KERNEL_BASE 0x40078000
BOARD_NAME CY-X682C-H694-C
BOARD_PAGE_SIZE 2048
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x07c08000
BOARD_SECOND_OFFSET 0x00e88000
BOARD_TAGS_OFFSET 0x0bc08000
BOARD_OS_VERSION 10.0.0
BOARD_OS_PATCH_LEVEL 2020-06
BOARD_HEADER_VERSION 2
BOARD_HEADER_SIZE 1660
BOARD_DTB_SIZE 112012
BOARD_DTB_OFFSET 0x0bc08000

Unpacking ramdisk to "ramdisk/"...

Compression used: gzip
3616 blocks

Done!
```

**Comment by o-kotb** [comment]
I found a guide from looking up some of the keywords you just said (it all went over my head). And surprise surprise, the vbmeta verity thing was it after all. After I disabled it, the boot image worked like a charm. Judging by how simple that process was, I’m probably not the first person to open an issue like this so this is probably a dupe (sorry). But this should be in the instructions page as it may be helpful to people who are new to Android like me. Thanks by the way.

**Comment by SirJpe** [comment]
> Device: infinix hot 10 X682C
> Android version: Android 10 (it says XOS v7.0.0 but I don’t think it matters)
> Magisk version name: [66e30a7](https://github.com/topjohnwu/Magisk/commit/66e30a772395423d124ac84c16ddf384d6c3bc10)
> Magisk version code: 22006
> [boot.img mega link](https://mega.nz/file/Ow5RWARY#rj6WPAhUBZkB4U9FkF89uLoqmnCF6aqWc9iYzdlKtnE)
> [“cat /proc/mounts” output](https://pastebin.com/4Nur28nh)
> I’m unable to provide dmesg logs as I can’t root.
> 
> Every time I flash either the boot or recovery images, my phone boot loops. It boots up with the infinix logo and says
> 
> “Orange State
> 
> Your device has been unlocked and can't be trusted
> Your device will boot in 5 seconds” then reboots.
> 
> I can’t even access recovery mode. I can’t do anything but use sp flash tool to unbrick my device.
> 
> I can’t use twrp either as there are no official builds and my device needs to be rooted to build one on my own.

i am also having this same orange state issue pls someone help i cant use sp flash tool its giving me errors
