### ISSUE TITLE
magisk Canary  not working in samsung android 10 device

### ISSUE THREAD

**Issue by ebinshaji** [topjohnwu/Magisk#4115]
I just tried rooting SM-M013F/DS which is running in android 10 go edition. it successfully patched boot.img  and i ve flashed using Odin3_v3.14.1. boot is working fine and when i open Magisk Canary it showing Magisk not installed.

but when rooted another Samsung device running in android 8 using an older version of magisk (few months before) it works fine and my device has been rooted 

Device: SM-M013F/DS
Android version: Android 10
Magisk version name:Canary  22006
Magisk version code: 22006
![Screenshot_20210327-094827](https://user-images.githubusercontent.com/39409167/112710866-7cc2d200-8e81-11eb-9f81-fb2d77b224b9.jpg)

[Smm01core.zip](https://github.com/topjohnwu/Magisk/files/6215083/Smm01core.zip)

**Comment by krafi99** [comment]
It is prohibited to open issues regarding root detection.

**Comment by ebinshaji** [comment]
ok sorry for issue. if u can just add compatibility for android 10 go edition

**Comment by pndwal** [comment]
> It is prohibited to open issues regarding root detection.

Regarding root detection by Magisk App??? Why? ... Of course it's not!

It is prohibited to"Submit MagiskHide Requests".

Is the issue resolved? PW
