### ISSUE TITLE
Magisk not found

### ISSUE THREAD

**Issue by xtexChooser** [topjohnwu/Magisk#4116]
Device:  Samsung SMG9008W
Android version: 6.0.1(SDK 23)
Magisk version name:  22.0
Magisk version code: I do not know

Today, I open Magisk Manager and open the Magisk Hide
Then Magisk Manager ask me to update it, I allowed.
I am using the Test/Beta channel(I am using Chinese translation, so I do not know the English word of it)
After I updated it(The name of the app is changed to Magisk), I tried to open the manager.
The splash activity is opened but it is finished(close/exit) after a few seconds.
I can not open the main page.
I try to re-install the manager, re-install the magisk, but there are no any results.
Then I downloaded the Magisk uninstaller and the installer from the official website, and install them using ADB Sideload in TWRP.
And re-install the manager from the website.
Now, I can open the Magisk app, but it shows no magisk was found.
I clicked the Install button but it tell me "Verification failure"(Install failure)
I re-tried above steps, but there are no any results.
But my modules look like running right
But I can not manage the modules.

**Comment by pndwal** [comment]
You probably haven't unhidden old 'Manager' before updating app as per Release Notes:
https://topjohnwu.github.io/Magisk/releases/22000.html

It's a MANAGER/APP hiding incompatibility, not Magisk in ramdisk!

I suspect you have a hidden version of manager Installed, and you only need to find/remember the name you chose, remove BOTH this and current app (normal app uninstalls), and reinstall app to fix conflicts. Nb. module /setting data witll be unaffected as it is in /data/adb.

This is support / discussion thread for future issues:
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/ PW
