### ISSUE TITLE
Partially activated" SEPolicy is not loaded properly.

### ISSUE THREAD

**Issue by andr6** [topjohnwu/Magisk#4118]
Device: Oneplus8
Android version: Oxygen OS
Magisk version name: 22006 66e30a7
Magisk version code: 22006

Upgrade to latest magisk canary version. Installed LSPosed 1.3.4 and manager. Manager shows "Partially activated" SEPolicy is not loaded properly. Module xprivacylua is not loaded.

**Comment by Displax** [comment]
Duplicate https://github.com/topjohnwu/Magisk/issues/4098
