### ISSUE TITLE
magisk.me legit?

### ISSUE THREAD

**Issue by DumbGameMaker** [topjohnwu/Magisk#4120]
i was installing magisk, right? so i looked up 'magisk' and went to magisk.me. i downloaded it (not from github) and opened the app, to find the warning about only downloading from github. I uninstalled and reinstalled the magisk from the github, but i wonder if magisk.me is legit or a scam, or if you even know about it?

**Comment by QkiZMR** [comment]
Magisk zip downloaded from magisk.me has same checksum as downloaded from Github.

**Comment by Didgeridoohan** [comment]
Even though they might be providing the correct file, they're not legit. Only ever download from John's GitHub.

**Comment by DumbGameMaker** [comment]
> Magisk zip downloaded from magisk.me has same checksum as downloaded from Github.

what checksum algo? if it is CRC or SHA1, magisk.me can add some junk comments and make it have the same checksum, even though it has different contents

**Comment by QkiZMR** [comment]
I checked md5. But now just check with sha512. Same checksum.

**Comment by b4n6-b4n6** [comment]
> Even though they might be providing the correct file, they're not legit. Only ever download from John's GitHub.

This cannot be understated - they can serve malware only in some regions or some time
