### ISSUE TITLE
scripts/emulator.sh cannot mount overlay on /system/bin (22006)

### ISSUE THREAD

**Issue by phuongnd08** [topjohnwu/Magisk#4123]
Device: Android Emulator Initial Preview 3 (Mac M1) - https://github.com/google/android-emulator-m1-preview/releases
Android version: 11
Magisk version name: build from source - commit fb8dc075
Magisk version code: 22006

scripts/emulator.sh fail right here:
```
  mount -t overlay overlay -olowerdir=/system/bin,upperdir=/dev/magisk/upper,workdir=/dev/magisk/work /system/bin
```

With error:
```
mount: 'overlay'->'/system/bin': Operation not supported on transport endpoint
```

I guess the syntax changed on android 11? Or perhaps there is specific settings need to be set on the emulator itself?

**Comment by phuongnd08** [comment]
For the record: I need to change a few things to be able to build the arm64 binary and then load it to the emulator which I pushed to my fork: 

https://github.com/phuongnd08/Magisk

**Comment by phuongnd08** [comment]
@shakalaca What do you think?

**Comment by phuongnd08** [comment]
Btw I would offer to pay 200$ in crypto for anyone who can help getting Magisk run on Android Emulator Initial Preview 3 before Mar 30 2020.

**Comment by topjohnwu** [comment]
This means the kernel does not support overlayfs in this specific case.
There are other issues related to M1 models (specifically, the emulator is 64-bit only, which Magisk currently does not support)

**Comment by phuongnd08** [comment]
That 64bit emulator is probably compiled from the same source code as the x86 or 32bit arm? I wonder why would overlayfs is left out?

To my understanding, the current compilation process of Magisk only produce 32bit version of magiskinit and magiskboot which won't run on that 64bit emulator, but I was able to compile the 64bit arm version by changing the flag:

![image](https://user-images.githubusercontent.com/184037/112913134-4b693100-9123-11eb-879f-6d412f3599b7.png)

Is it not enough?

If overlayfs is not working, how about the other 2 mounting methods: rootfs and sar? Will they offer the same benefit as overlayfs?

**Comment by vvb2060** [comment]
7717f0a6b0c4e4c72f38c90272062a6912a0d7c5 https://github.com/topjohnwu/Magisk/actions?query=event%3Apush
