### ISSUE TITLE
Requires Magic Mount to support system_ext of a separate partition

### ISSUE THREAD

**Issue by E7KMbb** [topjohnwu/Magisk#4124]
Most of the Android11 ​​ROM, their system_ext partition is independent, some files that need to be modified by the module are moved to this partition, so can they be supported by separate partitions like product and vendor?

**Comment by E7KMbb** [comment]
@topjohnwu

**Comment by Didgeridoohan** [comment]
@E7KMbb It is supported:
https://topjohnwu.github.io/Magisk/guides.html#magisk-modules

And has been for some time:
https://github.com/topjohnwu/Magisk/commit/8ca5a048d6c5f276ae57e2f408d057e8dfcbbb5a

Although that info was missing in the docs initially, but has now been in there for a little over a month:
https://github.com/topjohnwu/Magisk/commit/5ac0e64edb16ef4d568869b98e24f08499d150e4

**Comment by E7KMbb** [comment]
@Didgeridoohan But it did not actually work, my module did not work on the system_ext in a separate partition

**Comment by Didgeridoohan** [comment]
In that case I see a few possibilities. Either your module is faulty somehow, there's a bug in Magisk or there's something else.

If you're certain that your module is ok you need to open a proper bug report with logs from the latest Canary release and plenty of details.
