### ISSUE TITLE
OnePlus N10: Requested download size is more than max allowed

### ISSUE THREAD

**Issue by ZaxonXP** [topjohnwu/Magisk#4127]
I installed the latest canary Magisk v.66e30a77 (22006) on OnePlus N10 and downloaded the latest [OnePlus update](https://www.oneplus.com/support/softwareupgrade/details?code=PM1605857280263) for the phone, extracted boot.img, then patched it in Magisk. However when I tried to flash it I got following error:
```
$ fastboot flash boot magisk_patched-22006_0BtIp.img
target didn't report max-download-size
sending 'boot' (98304 KB)...
FAILED (remote: Requested download size is more than max allowed
)
finished. total time: 0.001s
```
There is no TWRP for this phone yet, so I cannot do this way.

How can I flash the patched image?

Attaching log from Magisk
[magisk_install_log_2021-03-29T15:15:01Z.log](https://github.com/topjohnwu/Magisk/files/6222051/magisk_install_log_2021-03-29T15.15.01Z.log)
![Screenshot_20210329-151641](https://user-images.githubusercontent.com/6058640/112844920-8bd59a00-90a4-11eb-9126-ac8d9b1b8d00.jpg)

.

Device: OnePlus Nord N10 5G
Android version: Oxygen OS 10.5.10.BE89BA
Magisk version name: 66e30a77 (22006)
Magisk version code: 66e30a77 (22006)

**Comment by Displax** [comment]
What platform-tools (fastboot) version you use?

**Comment by ZaxonXP** [comment]
I downloaded the latest version of canary, installed it and then I was able to patch the boot and successfully flash it. So it was my bad using not the latest version.
