### ISSUE TITLE
[wishlist] Magisk Modules Update Notifications

### ISSUE THREAD

**Issue by jack1142** [topjohnwu/Magisk#413]
I think it would be useful to have notification about available updates for Magisk Modules like we have for new app versions.

**Comment by PrakarshRocks** [comment]
Yeeeeeaaaaa this is needed a lot!

**Comment by topjohnwu** [comment]
Magisk Manager will go through major rewrite soon

**Comment by zacchi4k** [comment]
The rewrtire has happened, but I still don't get any notifications, so it looks like this hasn't been implemented. Correct me if I'm wrong
