### ISSUE TITLE
最新版LSPosed SEPolicy未被正确加载

### ISSUE THREAD

**Issue by chengdaowei** [topjohnwu/Magisk#4137]
Device: 
Android version:
Magisk version name: 
Magisk version code:

**Comment by Chinesebo** [comment]
API 版本
100

Xposed API 调用保护
已启用

Dex 优化器包装
支持

框架版本
1.9.2 (7024)

管理器包名
com.android.shell

系统版本
12 (API 32)

设备
Xiaomi Redmi Note 7 Pro 

系统架构
arm64-v8a
