### ISSUE TITLE
Magisk v22+ produces a boot.img of zero size

### ISSUE THREAD

**Issue by dr4go** [topjohnwu/Magisk#4138]
Device: Samsung Galaxy S10 (SM-G973F)
Android version: 11 (R)
Magisk version name: 66e30a77
Magisk version code: 22006

As you know the Galaxy S10 is a SAR device without included ramdisk and boots from the recovery.img. So you need to patch the recovery.img to be able to root the device. Everything with the patched recovery is fine, that is not the problem.
But what I've realized right now is - imho - quite a regression, because the boot.img Magisk creates is of zero size. Afaict it may again be a sepolicy issue when creating the boot.img. Please refer to the attached magisk install log, thanks a lot in advance.

[magisk_install_log_2021-04-02T13_39_22Z.log](https://github.com/topjohnwu/Magisk/files/6249402/magisk_install_log_2021-04-02T13_39_22Z.log)

![patched_ap](https://user-images.githubusercontent.com/597874/113413817-cc425a00-93bb-11eb-9b62-4cd87a8e3ce1.png)

**Comment by topjohnwu** [comment]
Tested on stock Android 11 One UI (Z Fold 2), and it's working completely fine

**Comment by dr4go** [comment]
First of all: Thanks for everything! Really impressed of your work and your achievements. A big inspiration!

Sorry for having performed such a bad testing job before reporting. When running the patching of the AP from a hidden Magisk app, I'm still able to reproduce the issue with a zero byte boot.img:
[magisk_install_log_2021-04-09T18_04_43Z.log](https://github.com/topjohnwu/Magisk/files/6287303/magisk_install_log_2021-04-09T18_04_43Z.log)

When restoring Magisk and run the patch job from a restored (=unhidden) Magisk app, everything is fine:
[magisk_install_log_2021-04-09T18_01_33Z.log](https://github.com/topjohnwu/Magisk/files/6287321/magisk_install_log_2021-04-09T18_01_33Z.log)

As I have now a workaround, I'm already happy. 😉

**Comment by Didgeridoohan** [comment]
@dr4go Your install logs show that there are errors when patching from a hidden app, but there's no info on why it errors out... And as you see John was not able to reproduce on another One UI Android 11 device. Are you running a custom ROM?

You would have to gather more info, like a logcat, that shows in more details why things fail. After you've done that you could consider open a new report (or alternatively reopen this one) with all the relevant info and logs.

**Comment by dr4go** [comment]
@Didgeridoohan I believe John tried to reproduce it on an unhidden Magisk app. That is why it didn't occur.
No custom ROM, not even TWRP installed, just the pure patched flashed image. If he doesn't react within a few days, I'll reopen a new one... Sure I can also attach a logcat then. But as being mentioned: I believe it will also occur on his device if Magisk is hidden.

**Comment by Didgeridoohan** [comment]
John knows about it (I notified him about your update), but as I said there's nothing that can be done without more info on why things fail while the app is hidden. No need to wait for a reaction.

Gather more info that can be used to pinpoint the issue and reopen this/open a new bug report.
