### ISSUE TITLE
Unable to do complete uninstall via magisk app

### ISSUE THREAD

**Issue by zputnyq** [topjohnwu/Magisk#4140]
Device: Xperia M4 (E2306)
Android version: 6.0.1 stock
Magisk version name: 66e30a77
Magisk version code: 22006

Thanks for hard work John & all other people who contribute here.

I have a problem when uninstalling Magisk canary 22006.
Pressing complete uninstall do nothing on Magisk Canary app but no problem with uninstalling from twrp.

Here's attached logs.

[logs-2021-04-02-23-42-36.zip](https://github.com/topjohnwu/Magisk/files/6250565/logs-2021-04-02-23-42-36.zip)

I hope it's the correct logs

**Comment by osm0sis** [comment]
I know the /data/magisk_backup thing is broken currently, so that could have something to do with it.

**Comment by osm0sis** [comment]
Try again? magisk_backup seems to be working fine again for me in 22101.

**Comment by zputnyq** [comment]
> Try again? magisk_backup seems to be working fine again for me in 22101.

Yes I try it, it still the same

https://user-images.githubusercontent.com/31039796/114258200-26ac6d80-99ef-11eb-8d0c-578d08fccc38.mp4
