### ISSUE TITLE
SEPolicy正确正确加载

### ISSUE THREAD

**Issue by q1363679989q** [topjohnwu/Magisk#4150]
![Screenshot_20210404-214519](https://user-images.githubusercontent.com/55631703/113511975-1599d180-9595-11eb-959f-94603e788321.jpg)
![Screenshot_20210404-222425](https://user-images.githubusercontent.com/55631703/113511925-d9667100-9594-11eb-898a-5da82f28d8cb.jpg)

Device: 一加7Tp
Android version:10.0
Magisk version name: 66e30a77
Magisk version code: 22006

**Comment by q1363679989q** [comment]
![Uploading Screenshot_20210404-222425.jpg…]()

**Comment by osm0sis** [comment]
#4098
