### ISSUE TITLE
Magisk app hiding/renaming bug

### ISSUE THREAD

**Issue by TechyAditya** [topjohnwu/Magisk#4152]
Device: Poco X2
Android version: 11
Magisk version name: f42a87b
Magisk version code: 22006

### Issues

I'm having issues with magisk 22.0 in masking app package name and app name of the app. This issue happened in evolution x custom rom. It just installs duplicate app, then do not uninstall old apk automatically. Opening them causes heavy lag in phone. 

### Workaround
Only workaround I found is, rolling back to magisk 21.4, then hiding and masking magisk app in the random name 'dogecoin', then updating to magisk 22.0. This is the only thing worked for me. Please fix the minor bug.

**Comment by TechyAditya** [comment]
Heavy lag, I meant that pixel launcher and system apps works well fine, no user apps even launch, just stuck on the welcome screen logo. And system ui and prompts too. It was too unexpected.

**Comment by topjohnwu** [comment]
Cannot reproduce
