### ISSUE TITLE
Google Sargo April 2021 update. No valid slot to boot after patching factory boot.img (seems to only be issue with 22006)

### ISSUE THREAD

**Issue by johnnydunlop** [topjohnwu/Magisk#4156]
Hi,

After applying the latest April 2021 update today, it appears that patching the new factory boot.img and flashing it results in a boot failure and kicks me back into fastboot with reason: No valid slot to boot. Flashing the original factory boot.img allows the OS to boot without any issues.

This wasnt an issue before the April 2021 update and I havent changed anything in my process. So wondering what may have changed to cause this.

I am unable to provide a logcat as the boot process does not seem to get far enough to allow adb to find the device.

Device: Google Pixel 3a Sargo
Android version: Android 11
Magisk version name: Canary
Magisk version code: 22006

Thanks in advance!

**Comment by usb9245** [comment]
When I try, the stable version(22000) can boot but the canary version(22006) does not.

**Comment by johnnydunlop** [comment]
> When I try, the stable version(22000) can boot but the canary version(22006) does not.

You are correct! I patched boot.img with Magisk stable 22000 and Android booted fine. Looks like its only an issue with Canary (perhaps only 22006). Thanks!

**Comment by osm0sis** [comment]
Any different with 22007?

**Comment by johnnydunlop** [comment]
> Any different with 22007?

Patching stock boot.img works with 22007. I just tested and Android booted successfully.

**Comment by osm0sis** [comment]
Perfect, so resolved then. 👍
