### ISSUE TITLE
ES file Explorer rooted faild

### ISSUE THREAD

**Issue by wjcwqc** [topjohnwu/Magisk#4159]
Device: any
Android version:9
Magisk version name: 22.0
Magisk version code: 22000

ES file explorer get root failed in thrid step .
ES 文件浏览器无法获得 root 。
I tried many version of ESFE .
我尝试了多种es文件浏览器的版本。
es文件浏览器在点击“root 工具箱 ”时 会弹出三次获取root。在第三次时会显示获取失败然后无法获取root权限。
This problem only shows in magisk version 22000 only before today.
I wish it can be fixed when next version or anyone can tell me why this problem happened.

**Comment by wjcwqc** [comment]
问题已解决，新版magisk需要 禁用selinux后才可完成完整授权。

**Comment by 276562578** [comment]
@wjcwqc 请问如何操作金庸selinux呢？我用root权限运行setenforce 0无效

**Comment by wjcwqc** [comment]
> @wjcwqc 请问如何操作禁用selinux呢？我用root权限运行setenforce 0无效

错误信息是什么？我直接setenforce 0就行
