### ISSUE TITLE
Feature request - By default, hide from every app

### ISSUE THREAD

**Issue by dioni21** [topjohnwu/Magisk#416]
Today we have to add which apps we want to hide magisk from.  Just for paranoia, I want to hide it from everything except what I want to allow su.

I think hiding should be de default operation.

**Comment by topjohnwu** [comment]
I agree with your point too, but due to the way how MagiskHide currently works, that is not possible. However if Magisk only need to hide root, it is actually possible.
I **can** introduce a new mode with this capability, but that will require tons of work, so it will not happen soon until all current Magisk issues are ironed out.

**Comment by vvb2060** [comment]
@djechelon MagiskManager targetSdk=28
`logcat -b events -s notification_cancel_all` This is the only way to let us know that xxx **may** have been installed.

**Comment by djechelon** [comment]
Not sure @vvb2060. I understand I might not have done enough homework to discover that intent `ACTION_PACKAGE_ADDED` changed behaviour in Oreo, but I have tried to do some more research. Still, the docs don't say it's deprecated.

[Stackoverflow](https://stackoverflow.com/questions/45996338/how-to-register-for-action-package-added-and-action-package-removed-on-android-o) linking the [Docs](https://developer.android.com/about/versions/oreo/background#broadcasts)

> This says that you cannot register these intents in your manifest. You can still register them programmatically to receive them when your app is running.

So Magisk, who is already granted to receive `ACTION_BOOT_COMPLETE` or `ACTION_LOCKED_BOOT_COMPLETED` may use the two broadcasts, especially the second, to programmatically register the listener I had into my mind.

I see a pitfall: on SDK < 24 where Locked Boot is not available, I have no such information whether Boot Complete is broadcasted only at unlock or even when phone is locked. You are capable of installing apps via Google Play Store for the web even with phone locked. But I have no record of Whatsapp not pushing notifications until your first unlock the device.

**Comment by dioni21** [comment]
+1 to multiple selection

**Comment by Didgeridoohan** [comment]
@Rolf-Smit Since you should not add too many apps to the Hide list, but simply those that explicitly look for root, I would save my precious time if I where you... Having too many apps and processes on the Hide list might have a detrimental effect on system stability.

**Comment by Nottt** [comment]
So is there any reason I shouldn't add all my apps to the hide list ?

**Comment by Originalimoc** [comment]
This should be revisited. F banks

**Comment by llucax** [comment]
Multiple selection and also a way to hide from all services from an app without having to "expand" the app services would also be very helpful.
