### ISSUE TITLE
[NON URGENT]A doubt, maybe a bug in the app?

### ISSUE THREAD

**Issue by nihalanand697** [topjohnwu/Magisk#4162]
I read about randisk article and what i understood is that there are devices without no ramdisk and thus magisk wont patch the boot image in that case. I have been seeing that the app suggests that my device (redmi note 7 lavender) doesnt have a ramdisk.
but Ive always flashed it through recovery as a zip and it patches the boot image.
so it seems that the device does have a ramdisk. Am I mistaken in understanding the concept or is it really a bug?
![Screenshot_20210407-005353_notes](https://user-images.githubusercontent.com/47318989/113767426-4a945880-973c-11eb-8f89-1e791bb4a96d.png)

**Comment by Didgeridoohan** [comment]
That's as expected and is what's described in the last two paragraphs here:
https://topjohnwu.github.io/Magisk/boot.html

**Comment by nihalanand697** [comment]
> That's as expected and is what's described in the last two paragraphs here:
> https://topjohnwu.github.io/Magisk/boot.html

Thank you for helping, so it means my decice is type 3 but ptovides initramfs right?
