### ISSUE TITLE
Bootloop with Magisk 22.0 on Xiaomi POCO X3 NFC

### ISSUE THREAD

**Issue by klorinczi** [topjohnwu/Magisk#4165]
Device: Xiaomi POCO X3 NFC
ROM: surya_eea_global_images_V12.0.7.0.QJGEUXM_20201221.0000.00_10.0_eea_6c03e13a9f.tgz
Android version: 10.0
Magisk version name: 483dbcd
Magisk version code: 22007

Bootloop with Magisk 22.0 on Xiaomi POCO X3 NFC.
It was installed in TWRP v3.4.0.
I had same bootloop when flashed with patched boot.img.

Magisk 21.4 works fine on Xiaomi POCO X3 NFC, it boots successfully.

So the difference must be in Magisk 22.0 which causes bootloop.

**Comment by Didgeridoohan** [comment]
Did you actually try it on build 22007? Asking since you mention v22.0 in your text...

Also: any modules installed? If so, have you tried disabling those?

Lastly: Logs? Install log and boot logcat (if possible) would probably be useful.

**Comment by osm0sis** [comment]
@klorinczi is it still not working with 22102? Upload logs as requested and also boot.img or we'll have to close this issue for a lack of useful information.

**Comment by klorinczi** [comment]
@osm0sis: Magisk v22.1 is released now, so I will test it as recommended.

**Comment by osm0sis** [comment]
@klorinczi no update?

**Comment by klorinczi** [comment]
Sorry, I had no time to test it with v22.1.

I have v21.4 installed on Xiaomi Poco X3 NFC with MIUI 12.0.7 (Android 10) and it works fine.

**Comment by osm0sis** [comment]
Great. Test with Canary and upload logs as requested or I'll close this.
