### ISSUE TITLE
Systemless hosts module

### ISSUE THREAD

**Issue by No-WaY-SA** [topjohnwu/Magisk#4166]
Device: S10+ G975F
Android version: android 11 (9fubd)
Magisk version name: 9c0e1879 (22007)
Magisk version code: 9c0e1879 (22007)
[Magisk log](https://we.tl/t-2OaUdoP5bg) 

I need the correct way to disable Systemless hosts module and restore it to status of previous condition before applying this module from setting.
As it conflicts with some program the i need it hopelessly 

Can you help me?

**Comment by Didgeridoohan** [comment]
GitHub issues isn't for general instructions, but to report about bugs.

If you want to disable/uninstall a module, you do that under the modules section of the Magisk app (the puzzle piece in the bottom navigation bar).
