### ISSUE TITLE
Magisk Hide Toogle Keeps Reseting to "Disabled" for Isolated Process

### ISSUE THREAD

**Issue by jh0bc** [topjohnwu/Magisk#4176]
Device: Xiaomi Mi 9t Pro
Android version: 11
Magisk version name: Canary (f623b988)
Magisk version code: 22101

**To make clear as possible, this bug report is not about a detection of Magisk but about of some issue with the handling isolated processes name.**

This problem happened some time ago with "Mandiri" app and the commit https://github.com/topjohnwu/Magisk/commit/68656521259bdf5b12c8d2a6177f6907dfc65f1a fixed this.

Issue about name handling: https://github.com/topjohnwu/Magisk/issues/3997

But now another app "BM Online" present the same behavior. The toggle for the Isolated Process keeps resetting every time

I checked the log of Magisk when adding the app to the Hide List and the main process appears just fine, but don't show anything about the isolated one.

I'm using the Riru Unshare v. 2.0 by @vvb2060 to enable isolated process handling for Magisk.

Play Store Link: https://play.google.com/store/apps/details?id=com.BanqueMisr.MobileBanking

Log:
 
[magisk_log_2021-04-09T14_15_45Z.log](https://github.com/topjohnwu/Magisk/files/6287457/magisk_log_2021-04-09T14_15_45Z.log)

**Comment by Sherbi** [comment]
The same in BM Online 
Device: Xiaomi Mi 10T Global
Android version: 11
Magisk version name: Canary (f623b98)
Magisk version code: 22101

**Comment by MuhmdRaouf** [comment]
I tried to hide it multiple times as much as i could but couldn't,
I followed the https://topjohnwu.github.io/Magisk/tutorials.html#best-practices-for-magiskhide yet not working.
So I tried to track down the logcat and find out the following
```
ActivityManager: Start proc 22552:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0i5 for  {com.BanqueMisr.MobileBanking/org.chromium.content.app.SandboxedProcessService0:0}
```

it opens up the activity within a chromium SandboxedProcessService and this service is not showing in the MagiskHide to use it, also my app has 2 entries in MagiskHide one for the app itself and one for tmpService
the tmpService always go back to unchecked whenever I close Magisk app and open it again.

I hope that could help to hide application like these from Magisk

**Comment by Sherbi** [comment]
Jhobc is a Senior Member in XDA

Found solution for it by using Momohideing
https://github.com/canyie/Riru-MomoHider

It solve hideing the isolated to detect magisk
Just follow the module structure
