### ISSUE TITLE
Samsung Galaxy s10e stuck on Download Mode ( DT load fail)

### ISSUE THREAD

**Issue by maquille** [topjohnwu/Magisk#4178]
Device: Samsung Galaxy s10e SM-G970F
Android version: Anroid 10 G970FXXU4BTA8
Magisk version name: 22
Magisk version code: 22101

1- I tried to update my old version of magisk via magsik manager - it worked after rebooting phone -
2- Tried to downgrade magisk via titanium backup by restoring app + data magsik - then I restarted my phone and stuck into download mode with this message

ODIN MODE (DT Load Fail)
[DTH] dt table headet check Fail <unknown error>
Load_kernel: could not do Normal boot. (DT LOAD Fail)
vbmeta: Error verifying vbmeta image: OK_NOT_SIGNED (3)
vbmeta: VERIFICATION_DISABLED bit is set.
CUSTOM VBMETA
VBMETA: No sign info
VBMETA

3- My priority is to keep my data without doing a factory reset. I have a lot of informations..
Thanks a lot.

**Comment by topjohnwu** [comment]
No logs, no fix

**Comment by maquille** [comment]
I'm sorry, I'm totally lost. How can I find a log please ? I only have the download screen. Please help me.

**Comment by maquille** [comment]
You mean that there is no solution ? I don't really understand. Can you please just give me your opinion on this.
I have no response from anywhere. I'm searching since yesterday..
