### ISSUE TITLE
Magisk startup operations should use different channel

### ISSUE THREAD

**Issue by Madis0** [topjohnwu/Magisk#419]
The notification "Magisk startup operations" should use a different channel than the "Magisk updates" one, because:

- it doesn't need to have importance level of high, low would make more sense
- that's the point of notification channels

**Comment by topjohnwu** [comment]
There is no more notifications for on boot notifications 👍

**Comment by topjohnwu** [comment]
Check this commit: 6263d684d9f81ff7ae015dee9eea5d43deabd488
