### ISSUE TITLE
Package is downloaded again if install unknown apps permission was not given

### ISSUE THREAD

**Issue by cl-ement05** [topjohnwu/Magisk#4191]
Device: Xiaomi Mi 8 (dipper)
Android version: 11 (PE11)
Magisk version name: e136fb3a
Magisk version code: 22102

Note : this bug seems to happen only in Android 11 since on my Galaxy A7 running Android 10 I do not face it

When installing a Magisk update, if the "Install apps from unknown sources" permission is not given to Magisk, the Android prompt appears as usual saying I need to go to settings and enable the permission. However, when this permission is enabled and I go back to Magisk, installation seems to have been *restarted* and the app package is downloaded again (I saw the blue bar and download icon). Note : I don't have to click on "Install" again, this second download process starts automatically

**Comment by QkiZMR** [comment]
Is it same as https://github.com/topjohnwu/Magisk/issues/4189?

**Comment by cl-ement05** [comment]
> 
> 
> Is it same as #4189?

No it isn't. I didn't hide or rename the Magisk App. I simply not gave permission to let Magisk install unknown apps, in this case a Magisk update to V22.1

**Comment by topjohnwu** [comment]
This is a limitation of your system, not something related to Magisk

**Comment by cl-ement05** [comment]
> This is a limitation of your system, not something related to Magisk

Oh it may be. But I was thinking about something like Magisk remembering that the package is already downloaded so there is no need to download it again

Then Magisk could start again the installation operation _asking_ the system to install the package downloaded previously

Isn't this possible ? Why would it be a system limitation since downloading the update pkg is Magisk s job ?
