### ISSUE TITLE
Please Support Pre Init Mounting Like Before

### ISSUE THREAD

**Issue by reiryuki** [topjohnwu/Magisk#4193]
Device: Xiaomi Redmi 4A
Android version: 10
Magisk version name: Canary
Magisk version code: 22102

[magisk_log_2021-04-12T10:40:34Z.log](https://github.com/topjohnwu/Magisk/files/6293800/magisk_log_2021-04-12T10.40.34Z.log)

I heard from someone, previously, long time ago, Magisk was supports pre init mounting, but after some updates it's no longer supports. It will be wonderful if Magisk supports pre init mount again because some of my mods needs pre init mount to be working like /vendor/etc/vintf/manifest.xml replacement. I have ever tried restarting hwservice_manager with many methods but it never be succeed and I'm give up. Only pre init mount can solve it. It's ok if Magisk will not supports it again but I hope it is not related to misunderstanding and slandering about someone in the past that causing Magisk to stop this supports. Btw, thanks for sepolicy.rule fixation.

Thanks in advance
Regards reiryuki

**Comment by topjohnwu** [comment]
Sorry, but this is impossible due to modern Android's restrictions.
Managing sepolicy.rules is already extremely complicated, adding pre-init mounts will not only make the situation even worse, but also might not work properly due to selinux restrictions.

**Comment by reiryuki** [comment]
@topjohnwu But can it be just for /vendor/etc/vintf/manifest.xml? I only need this file as pre init mounted not at all

**Comment by androidacy** [comment]
> @topjohnwu But can it be just for /vendor/etc/vintf/manifest.xml? I only need this file as pre init mounted not for all files..

That would make it even _more_ complicated, to pick and choose which files to work with.

You might take a look at magisk's support for `overlay.d`, not sure if it covers your use case but worth a shot.

**Comment by reiryuki** [comment]
@androidacy is that configured under boot_patch.sh inside magisk or can be configured under customize.sh via module?

**Comment by reiryuki** [comment]
@androidacy Or like this?
![Screenshot_20210419-163303187](https://user-images.githubusercontent.com/46316533/115215039-4e0ce400-a12d-11eb-8c29-755a61d765f2.jpg)
