### ISSUE TITLE
Latest Canary broke audio functionality on ColorOS roms

### ISSUE THREAD

**Issue by SoreScythe** [topjohnwu/Magisk#4197]
Same problem as the one in #4195 but can't reopen the issue so i had to open a duplicate.

I upgraded magisk following the official instructions and the issue persists.

Audio stopped working completely after installing the latest magisk available via the magisk manager app. other things doesn't seem to affected still.

This is on the stock rom which is ColorOS and the issue is playing any kind of audio file fails using the an app or through the terminal.
Music players just give a toast saying "unable to play the specified file" then proceeds to other files(which also fails to play).
video playbacks work Without issue.

please do instruct me on getting the required logs.

Device: Realme 5
Android version: Android Pie(9)
Magisk version name: e136fb31
Magisk version code: 22102

log finally uploaded succesfully
[magisk_log_2021-04.log](https://github.com/topjohnwu/Magisk/files/6296672/magisk_log_2021-04.log)

**Comment by SoreScythe** [comment]
[Magisk Log](https://pastebin.com/wJiNXSaL) since github seems to have a problem...

**Comment by SoreScythe** [comment]
Here's an excerpt containing lines with audio and err keywords

> [audio.deep_buffer.media]: [true]
> [audio.offload.buffer.size.kb]: [32]
> [audio.offload.gapless.enabled]: [true]
> [audio.offload.min.duration.secs]: [30]
> [audio.offload.video]: [true]
> [init.svc.audioserver]: [running]
> [init.svc.vendor.audio-hal-2-0]: [running]
> [persist.audio.fluence.speaker]: [true]
> [persist.audio.fluence.voicecall]: [true]
> [persist.audio.fluence.voicerec]: [false]
> [persist.vendor.audio.fluence.speaker]: [true]
> [persist.vendor.audio.fluence.voicecall]: [true]
> [persist.vendor.audio.fluence.voicerec]: [false]
> [persist.vendor.audio.ras.enabled]: [false]
> [ro.boottime.audioserver]: [12252922755]
> [ro.boottime.vendor.audio-hal-2-0]: [11938903015]
> [ro.qc.sdk.audio.fluencetype]: [none]
> [ro.qc.sdk.audio.ssr]: [false]
> [ro.vendor.audio.sdk.fluencetype]: [fluence]
> [ro.vendor.audio.sdk.ssr]: [false]
> [tunnel.audio.encode]: [true]
> [vendor.audio.adm.buffering.ms]: [2]
> [vendor.audio.dolby.ds2.enabled]: [false]
> [vendor.audio.dolby.ds2.hardbypass]: [false]
> [vendor.audio.flac.sw.decoder.24bit]: [true]
> [vendor.audio.hw.aac.encoder]: [true]
> [vendor.audio.noisy.broadcast.delay]: [600]
> [vendor.audio.offload.buffer.size.kb]: [32]
> [vendor.audio.offload.gapless.enabled]: [true]
> [vendor.audio.offload.multiaac.enable]: [true]
> [vendor.audio.offload.multiple.enabled]: [false]
> [vendor.audio.offload.passthrough]: [false]
> [vendor.audio.offload.pstimeout.secs]: [3]
> [vendor.audio.offload.track.enable]: [true]
> [vendor.audio.parser.ip.buffer.size]: [262144]
> [vendor.audio.safx.pbe.enabled]: [true]
> [vendor.audio.tunnel.encode]: [false]
> [vendor.audio.use.sw.alac.decoder]: [true]
> [vendor.audio.use.sw.ape.decoder]: [true]
> [vendor.audio_hal.in_period_size]: [144]
> [vendor.audio_hal.period_multiplier]: [3]
> [vendor.audio_hal.period_size]: [192]
> ^@05-30 06:56:24.038   569   571 D : bind_mnt: /system/bin/audioserver <- /sbin/.magisk/mirror/system/bin/audioserver
> [persist.dirac.acs.ignore_error]: [1]
> [persist.sys.first_errTime]: [false]
> [persist.sys.hw_errTime]: [0000/00/00/0000]
> [persist.sys.ic_errTime]: [2020/09/29/1345]
> [ro.crypto.allow_encrypt_override]: [true]
> [ro.product.wtconfig.blueberry]: [Blueberry]
> [setupwizard.feature.predeferred_enabled]: [false]

**Comment by SoreScythe** [comment]
it seems that even youtube playback has been affected as well. Youtube videos show the generic "There was a problem while playing" error.

This is a shot in the dark but is the issue somehow related to DRM?
maybe magisk deleted some DRM related files while updating the module. I'll upload the magisk update log in a while

**Comment by osm0sis** [comment]
Magisk doesn't touch anything drm.

Try `setenforce 0` and see if it works again.

**Comment by topjohnwu** [comment]
Closed due to lack of follow up info
