### ISSUE TITLE
[Feature request] Quick settings tile

### ISSUE THREAD

**Issue by flocke** [topjohnwu/Magisk#420]
First of let me start by thanking you for your incredible work on Magisk. I've been using it basically since its release on all my devices and never had a serious problem.

Now on to my idea: I suggest adding a quick settings tile to Magisk Manager that, upon single tap, triggers a Safety Net check and displays the result. For example it could display a checkmark if both ctsProfile and basicIntegrity pass, a X if both fail and maybe a "-" if only one fails.
And as a bonus I would suggest adding an option to restart Magisk Hide upon long press on the tile (or something similar).

The reason for that is that on my device Magisk Hide stops working after a while. When I restart my phone it is fine and passes SafetyNet for a period of time, but after that it starts failing. When that happens I have two possibilities: reboot my phone or go to Magisk Manager -> Settings and disable and immediately enable Magisk Hide again. After that SafetyNet passes again. The tile I suggested would make this process so much more comfortable.

**Comment by Madis0** [comment]
I would suggest three tiles:
- open app 
- toggle superuser for all (do not enable those that weren't enabled previously) 
- safetynet check

**Comment by Madis0** [comment]
https://github.com/matteosecli/Magisk-Root-Toggle There used to be a better app in Play Store, but it seems to be removed now.

**Comment by topjohnwu** [comment]
This seem very complicated and I don't think putting work in such thing in a root manager app worth the effort LOL.
I won't be implementing this anytime soon, I'll close this for now
