### ISSUE TITLE
LOS 18.1 onePlus-One boot-loop after enable LSposed, can you help me please?!

### ISSUE THREAD

**Issue by hamedsbt** [topjohnwu/Magisk#4203]
Device: onePlus-One (bacon)
Android version:11 (LOS 18.1, Device API level: 30)
Magisk version name: 22.1
Magisk version code: 22100

I've installed
01- Lineage-18.1-20210409-microG-bacon.zip
02- magisk Magisk-22.1(22100)
03- Riru-v25.3.4.r399.84f7084(399)
04- Riru_-_LSPosed-v1.3.5(5551)

After reboot, I stuck on boot-loop :(

I have only Riru & LSposed as activated modules.

I attached the boot.log (generated by: https://www.didgeridoohan.com/magisk/MagiskHelp#:~:text=If your Magisk log is,what happens )
[bootlog_LSposed_bootloop.zip](https://github.com/topjohnwu/Magisk/files/6298820/bootlog_LSposed_bootloop.zip)
[magisk.log](https://github.com/topjohnwu/Magisk/files/6298821/magisk.log)

@yujincheng08 (the LSposed contributer) say:
_Magisk tries to load system.prop from LSPosed and it gets stuck!
So there's nothing to do with LSPosed. This is magisk's bug._

![image](https://user-images.githubusercontent.com/7298328/114440053-eca1be00-9bde-11eb-9330-8a796412acf1.png)

**Comment by hamedsbt** [comment]
I have bee updated to latest canary version: 22102 but bootloop not fixed.

**Comment by yujincheng08** [comment]
Please reopen a new issue with proper title...
