### ISSUE TITLE
In order to fix FR translations : What is the difference between "OS apps" and "System apps" ?

### ISSUE THREAD

**Issue by cl-ement05** [topjohnwu/Magisk#4210]
Device: Any
Android version: Any
Magisk version name: 22.1
Magisk version code: 22102

Both [this translation](https://github.com/topjohnwu/Magisk/blob/c4e8dda37cd932049dbf637f47a150ecd08705f0/app/src/main/res/values-fr/strings.xml#L101) and [this one](https://github.com/topjohnwu/Magisk/blob/c4e8dda37cd932049dbf637f47a150ecd08705f0/app/src/main/res/values-fr/strings.xml#L102) mean *Show System apps*.

The only difference between them is that the first one would translate to "System applications" whereas the second one would be "System apps". 

So apart from the way the word application is written, there is no clear difference here between OS apps and System apps.

So how do you differentiate OS apps from System apps

**Comment by vvb2060** [comment]
OS core apps
