### ISSUE TITLE
Magisk Stub fails to upgrade to the full Magisk App

### ISSUE THREAD

**Issue by X1nto** [topjohnwu/Magisk#4215]
Tried to install Magisk v22.1 and upon opening the stub APK, the upgrade to the full app failed with PackageManager's "There was a problem parsing the package". The same issue occurs on the e136fb3a canary build. Digging into the logcat showed me the following error message: 
```
InstallStaging: Error staging apk from content URI
InstallStaging: java.io.FileNotFoundException: No files supported by provider at content://com.topjohnwu.magisk.provider/cache_files/manager.apk
InstallStaging: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
InstallStaging: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
InstallStaging: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1983)
InstallStaging: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1798)
InstallStaging: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1475)
InstallStaging: 	at com.android.packageinstaller.InstallStaging$StagingAsyncTask.doInBackground(InstallStaging.java:174)
InstallStaging: 	at com.android.packageinstaller.InstallStaging$StagingAsyncTask.doInBackground(InstallStaging.java:167)
InstallStaging: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
InstallStaging: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
InstallStaging: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
InstallStaging: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
InstallStaging: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
InstallStaging: 	at java.lang.Thread.run(Thread.java:923)
```
Full logcat: [logcat.txt](https://github.com/topjohnwu/Magisk/files/6312971/logcat.txt)

Further details:
Magisk was installed via TWRP as I did not have enough time to patch the boot image, although, I believe that doesn't even matter in this scenario.

Device: Redmi 9
Android version: 11 (Custom ROM, Nezuko OS v1.2)
Magisk version name: e136fb3a
Magisk version code: 22102

**Comment by androidacy** [comment]
Can confirm occurs on a oneplus 7T.
Tested OxygenOS, DerpFest, and YAAP. All android 11, all have the same error.

In addition the stub downloaded from github has the same issue.

**Comment by morrisalex** [comment]
Also seen today on a Samsung SM-T500. Magisk was installed via patching the official Samsung firmware with the Magisk app before unlocking the bootloader, then using Odin to apply the patched firmware. After booting, Magisk reported the same "There was a problem parsing the package" message.

**Comment by osm0sis** [comment]
Can confirm, the stub dumped by magisk_patched.img on a clean install does not currently work. Also trying to install from a Magisk update notification gives a similar looking issue.

**Comment by X1nto** [comment]
In case anyone needs magisk working as soon as possible, you can manually download the magisk app from the url found stable.json or canary.json (if you are using canary) in magisk-files repo and install it.

**Comment by topjohnwu** [comment]
It turns out to be a bug within the closed source stub build script, I have fixed it internally
