### ISSUE TITLE
SafetyNet API Error

### ISSUE THREAD

**Issue by palmbeach05** [topjohnwu/Magisk#4216]
Device: Moto G7 Power
Android version: 10
Magisk version name:  e136fb3a
Magisk version code: 22102

In the past 24 hrs, Magisk Check SafetyNet gives an error. Magisk properly installed and patched. External root checker verifies root. Issue seems to be across multiple devices. Tried the advice from Didgeridoohan given from here https://github.com/topjohnwu/Magisk/issues/4183 but issue persists. Internet connection is good.

![IMG_20210414_215114_915 1](https://user-images.githubusercontent.com/5945226/114803054-c873e780-9d6c-11eb-95db-2a0f015ebc07.jpg)
![Screenshot_20210414-215851965 1](https://user-images.githubusercontent.com/5945226/114803090-d6296d00-9d6c-11eb-9de6-c444d45c346a.jpg)

**Comment by jfeise** [comment]
Devices: OnePlus 5T, OnePlus 7Toro Mc Karen
Version: 22102
Same issue across my devices.

**Comment by dark-basic** [comment]
In other tests these pass, it is only happening in the magisk safetynet test. Sorry for my bad English.. 😅😅

**Comment by dark-basic** [comment]
![Screenshot_20210414-210616_SafetyNet_`attest`](https://user-images.githubusercontent.com/28790924/114807066-c6f9ed80-9d73-11eb-908d-272efab199a2.png)
 Is a safetynet issues or magisk safetynet test issues. 😬

**Comment by magdydl** [comment]
Same problem here huawei y9 2019
In the last 24 hours safetynet was work correctly. Not it's given Error!
![Screenshot_20210415_045302_com topjohnwu magisk](https://user-images.githubusercontent.com/38022649/114807334-87002e00-9da6-11eb-8d04-23d1c5295c71.jpg)
![Screenshot_20210415_045314_org freeandroidtools safetynettest](https://user-images.githubusercontent.com/38022649/114807351-8e273c00-9da6-11eb-9900-69f152e0a2d9.jpg)

**Comment by androidacy** [comment]
Getting the API error from Magisk, but other safetynet checkers still work (and pass, phew)

**Comment by chknatwork** [comment]
Device: OnePlus 7TPro
Android version: 11
Magisk version name: e136fb3a
Magisk version code: 22102 (20)

Same issue as above but RootChecker verifies that SafetyNet passes. Reset my phone to try again and now I am unable to get SafetyNet to pass on both Stable and Canary.

**Comment by AuroraWright** [comment]
Magisk = fail (N/A)
Root checker = fail (can't access Google Play Services)
Safetynet Helper Sample = pass
This is all pretty weird tbh

**Comment by androidacy** [comment]
Please have some patience and wait for a fix.

More than likely, if I'm not much mistaken, this'll all be cleared up tomorrow. Usually when that happens, the Safetynet API key has had it's quota exhausted

**Comment by realKarthikNair** [comment]
https://twitter.com/topjohnwu/status/1382563209995964418?s=19

**Comment by osm0sis** [comment]
Already fixed for the next Canary. It's superficial only, the device still passes if it did before.
