### ISSUE TITLE
Upgrade from Magisk 20.3 to 22.1 impossible with Magisk App

### ISSUE THREAD

**Issue by maquille** [topjohnwu/Magisk#4219]
![Screenshot_20210415-142217](https://user-images.githubusercontent.com/61931490/114868363-1a148480-9df6-11eb-83ac-3cf593c2fbb9.jpg)
Hi everyone,
I tried to upgrade magisk from my older version (20.3) to the newest (22.1) with magisk manager (22.1) ---> I did it with Direct Installation - all seems to be OK --> phone Reboot automatically with recovery mode ---> all seems to be normal (I can use Titanium ect..) but when I go into the magisk app I have this message : "This version of magisk does not support magisk versions lower than 20.4. The application will behave as if magisk is not installed. Make sure to update Magisk as soon as possible."
I did it 3/4 times but still the same problem.

Device: SM G970F
Android version: android 10
Magisk version name: 22.1
Magisk version code: 22102

[magisk_install_log_2021-04-15T14:10:19Z.log](https://github.com/topjohnwu/Magisk/files/6317773/magisk_install_log_2021-04-15T14.10.19Z.log)

**Comment by vvb2060** [comment]
```
- Target image: /dev/block/sda14
- Device platform: arm64-v8a
- Installing: 22.1 (22100)

......

- Flashing new boot image
Magisk v20.3(20300) (by topjohnwu) multi-call binary

Usage: magisk [applet [arguments]...]
   or: magisk [options]...
```
It looks like there is a problem with the installation logic.

**Comment by maquille** [comment]
Ok. Si what can I do?

**Comment by leppit** [comment]
Please check issue #4174 for similarities.
