### ISSUE TITLE
Magisk causing memory leak

### ISSUE THREAD

**Issue by ZeloIsGay** [topjohnwu/Magisk#4220]
Device: Redmi Note 7 (Lavender)
Android version: 11
Magisk version name: e136fb3a
Magisk version code: 22102

Through version 21.0 all to latest canary, on a cleanly flashed version of EvolutionX Android 11 with no modules enabled, I've taken all other factors into consideration and concluded that Magisk is causing a memory leak and causing system memory usage to slowly rise, causing applications to force close and such. This issue does not happen before installing Magisk (2hr of uptime on clean flash, 1.3gb of system usage. 2hr of uptime on Magisk flash, 2.0gb of system usage) and I also installed a custom kernel and ran multiple kmemleak scans thinking it may have been a kernel memory leak but that showed nothing at all. I'd be happy to share anything at all if needed. Thank you.

EDIT: Here is Magisk log, hope it is helpful. 
[magisk_log_2021-04-15T16_05_08Z.log](https://github.com/topjohnwu/Magisk/files/6318635/magisk_log_2021-04-15T16_05_08Z.log)

EDIT2: This also causes an increase in battery drain which leads to the device heating up significantly.

**Comment by topjohnwu** [comment]
Try disable MagiskHide, or if you want it enabled, reboot after toggling the feature
