### ISSUE TITLE
[v22.1+] The busybox binary is messed

### ISSUE THREAD

**Issue by seffparker** [topjohnwu/Magisk#4225]
After upgrading from 22.0 to 22.1, noticed many applets in the built-in busybox binary is messed.

For example, the _date_ applet is not following device timezone. The _start-stop-daemon_ applet is writing invalid PID into pid-file. 

Device: Xiaomi POCO F1
Android version: 9
Magisk version name: 22.1
Magisk version code: 22103

**Comment by osm0sis** [comment]
Can confirm on 22103, something is weird with Magisk busybox, even vs. my SELinux compile which is also NDK Clang through @topjohnwu's box-kitchen:
```
:/ $ busybox date
Sat Apr 17 10:31:56 ADT 2021
127|:/ $ su
:/ #
:/ # date
Sat Apr 17 10:34:06 ADT 2021
:/ # busybox date
Sat Apr 17 10:35:49 ADT 2021
:/ # /data/adb/magisk/busybox date
Sat Apr 17 13:33:44 GMT 2021
```

My guess would be something with the old libc in use for Magisk compiles?

**Comment by seffparker** [comment]
> What's the last version with working busybox?

busybox in Magisk 22.0 worked fine for me till the update into 22.1. I only noticed the issues with these two applets since I use `date` for logging and `start-stop-daemon` to overcome the issue #3224 

There may be other applets broken too.

**Comment by osm0sis** [comment]
I've been in touch with @topjohnwu about this and he's confirmed it's almost certainly the libc in use for the busybox build, since he went back to using the r10e NDK libc starting with v22.1. The fix would be to use the current NDK libc for the busybox builds.

**Comment by osm0sis** [comment]
Well yeah, mine works fine, but you'd have to manually copy it over Magisk's to get it to use it for internal functions, and I think that still wouldn't help with the Magisk app stuff.

**Comment by Zarkoob** [comment]
> still wouldn't help with any Magisk app stuff which might be affected since it's busybox is built in.

So just stay on v22.0 then? Or is it ok to use v22.1+ @osm0sis ?

**Comment by osm0sis** [comment]
It's not really a critical error; we haven't seen it affect anything integral to Magisk at this point.
