### ISSUE TITLE
Magisk Failed to install - boot.img is Read Only

### ISSUE THREAD

**Issue by isrgish** [topjohnwu/Magisk#4226]
Device:  LenovaTB-8705F
Android version: 10
Magisk version name: e136fb3a
Magisk version code: 22102

I'm trying to update to the new magisk update (2021.4.9 Magisk v22.1) via direct install  but the installation fails because the boot.img is read only. I have never had this before and the current boot.img was patched via magisk. 

I'm attaching the install lopg.
[magisk_install_log_2021-04-15T151117Z.log](https://github.com/topjohnwu/Magisk/files/6320624/magisk_install_log_2021-04-15T151117Z.log)

**EDIT**
I was able to patch the boot.img and then flash it with fastboot. But I still can't do the direct install.

**Comment by osm0sis** [comment]
#4219

**Comment by vvb2060** [comment]
```
blockdev: /dev/block/mmcblk0p28: Permission denied
! /dev/block/mmcblk0p28 is read only
```
MTK kernel prevents writing to emmc at runtime.

**Comment by isrgish** [comment]
Is there a way around this? As far as I remember I always was able to do a direct install until now.

**Comment by isrgish** [comment]
> #4219

As far as I can tell Issue #4219 says that it installed and rebooted but he gets some message that he needs to upgrade. While by me it doesn't even install and I get Failed to install because it's read only.

**Comment by osm0sis** [comment]
Yeah it's what vvb said, not the duplicate I thought. You can use Magisk app to patch a dumped boot.img then flash it from bootloader.

**Comment by jelabarre59** [comment]
And how do you get the boot.img file?
