### ISSUE TITLE
22103 basicIntegrity & ctsProfile keep failing, even in external apps

### ISSUE THREAD

**Issue by coldarchie** [topjohnwu/Magisk#4231]
Device: Nokia 6.1
Android version: 11 (LineageOS 18.1)
Magisk version name: [`f49966d8`](https://github.com/topjohnwu/Magisk/commit/f49966d86e4c50a8788b032ff6236b0c5ce32dda)
Magisk version code: 22103

After updating Magisk to 22103, basicIntegrity and ctsProfile keeps failing. I tried to toggle MagiskHide off and on, reinstall & uninstall all modules, but neither of these worked. Root works however.
I did not have Xposed or something related to it and both ctsProfile and basicIntegrity were passing before the update. The only thing I modified is a single line in build.prop, but it was before the update.

Here are dmesg & Magisk logs:
[dmesg.log](https://github.com/topjohnwu/Magisk/files/6323723/dmesg.log)
[magisk.log](https://github.com/topjohnwu/Magisk/files/6323727/magisk_log_2021-04-16T13_10_43Z.log)

![Screenshot_20210416-131032_Magisk](https://user-images.githubusercontent.com/24700967/114998099-0c283780-9eba-11eb-9ac2-3bfa4b6d952b.png)
![Screenshot_20210416-125103_SafetyNet_Test](https://user-images.githubusercontent.com/24700967/114998119-0fbbbe80-9eba-11eb-81f3-1020f5732a3c.png)

**Comment by kearmau5** [comment]
I have 22100 and it is the same problem

**Comment by osm0sis** [comment]
No. Already fixed. Update to the latest Canary.
#4216

**Comment by osm0sis** [comment]
Can you try this CI build instead? https://github.com/topjohnwu/Magisk/actions/runs/751925199

**Comment by kearmau5** [comment]
> Can you try this CI build instead? https://github.com/topjohnwu/Magisk/actions/runs/751925199

I have a stable built 22100...what can i do to fix the safetynet issue

**Comment by osm0sis** [comment]
22100 it's just cosmetic and SafetyNet is still actually passing

**Comment by osm0sis** [comment]
For the record 22103 passes fine on my OP8T, so whatever it is it's some kind of edge case.

**Comment by kearmau5** [comment]
![Screenshot_2021-04-16-13-20-48-202_hcr wo](https://user-images.githubusercontent.com/78478945/115031960-4a245c00-9eb8-11eb-958d-caa859515041.png)
I have thoose modules installed
Safety net used to pass despite having them or whitout

**Comment by osm0sis** [comment]
You clearly didn't listen to me at all. Stop derailing this issue.

**Comment by kearmau5** [comment]
> You clearly didn't listen to me at all. Stop derailing this issue.

Talk respectfully please and try to explain a easy 
We are not here to make this kind of slapping
Say something could help or don't say anything
No i wont switch to canary i used to work with stable with no issues until now

**Comment by ndr48291** [comment]
I made clean flash of DotOS rom on Mi 9T. Safetynet test fails in Magisk 22.1 but passes in Safetynet app. Netflix works fine. Phone works fine. Magisk hide is working.


![Screenshot_20210416-124254](https://user-images.githubusercontent.com/46603635/115043450-33443080-9edd-11eb-8aa4-02b5e4095a47.png)
![Screenshot_20210416-124324](https://user-images.githubusercontent.com/46603635/115043457-34755d80-9edd-11eb-9f66-b3f5e746c404.png)

**Comment by kearmau5** [comment]
> I made clean flash of DotOS rom on Mi 9T. Safetynet test fails in Magisk 22.1 but passes in Safetynet app. Netflix works fine. Phone works fine. Magisk hide is working.
> 
> ![Screenshot_20210416-124254](https://user-images.githubusercontent.com/46603635/115043450-33443080-9edd-11eb-8aa4-02b5e4095a47.png)
> ![Screenshot_20210416-124324](https://user-images.githubusercontent.com/46603635/115043457-34755d80-9edd-11eb-9f66-b3f5e746c404.png)

Same here
The app passes and magisk fails

**Comment by osm0sis** [comment]
> @coldarchie Can you try this CI build instead? https://github.com/topjohnwu/Magisk/actions/runs/751925199
> 
> Download the artifact zip and install the debug apk.

@coldarchie please still try this and report back when able.

**Comment by pndwal** [comment]
> Edit: Oh wait, misread. I see you're already on latest. 👍

Could this be related to modified build.prop user mentioned, or method used? PW

**Comment by coldarchie** [comment]
> 
> 
> > Can you try this CI build instead? https://github.com/topjohnwu/Magisk/actions/runs/751925199
> > Download the artifact zip and install the debug apk.
> 
> @coldarchie please still try this and report back when able.

Sorry for not paying attention on this issue, I needed Google Pay ASAP so I had to reflash my phone.

**Comment by pndwal** [comment]
Guess you mean reflashed with no custom mods & relocked bootloader?

Also, was buildprop change done systemlessly, or by mod to restore r/w in Android 11?

Just curious! 🙂

**Comment by Dev0110** [comment]
The issue is still there...
Can you reopen this issue?

**Comment by coldarchie** [comment]
> 
> 
> Guess you mean reflashed with no custom mods & relocked bootloader?
> 
> Also, was buildprop change done systemlessly, or does r/w system work in LOS (seems no was mod used to restore r/w in Android 11)?
> 
> Just curious! 🙂

i had unlocked bootloader and i had to install busybox & magiskhide props to pass ctsprofile

**Comment by osm0sis** [comment]
So lifetime writes was > 0 on system.. That could explain it.
