### ISSUE TITLE
Can't Patch Boot.img

### ISSUE THREAD

**Issue by bosscarlos** [topjohnwu/Magisk#4242]
![Screenshot_20210416-110143](https://user-images.githubusercontent.com/13984263/115052638-c791a180-9ea3-11eb-8c4f-671ff0784eae.jpg)
[boot.img.zip](https://github.com/topjohnwu/Magisk/files/6326453/boot.img.zip)

What is the difference between Normal and Canary version? anyway it failed in both

Device: SG M31
Android version:11
Magisk version name: 22.1
Magisk version code: 22103

**Comment by osm0sis** [comment]
That's a boot.img.lz4, not a boot.img, so you can probably guess what you need to do first before patching. 🙂
