### ISSUE TITLE
After installing the module and restarting, Magisk will not load SEPolicy rules

### ISSUE THREAD

**Issue by Vstory** [topjohnwu/Magisk#4248]
**Device Information**
- Device: Xiaomi Note 3
- Android version: 9.0
- Magisk version name: f49966d8
- Magisk version code: 22103

**Describe the bug**
After installing the [LSPosed module](https://github.com/LSPosed/LSPosed/releases),restart the device. The module shows that SEPolicy is not loaded correctly. At this time, Magisk must be reinstalled before SEPolicy can be loaded normally.

[boot.zip](https://github.com/topjohnwu/Magisk/files/6330581/boot.zip)
[logcat.zip](https://github.com/topjohnwu/Magisk/files/6330582/logcat.zip)
[magisk_log_2021-04-18T13-57-08Z.zip](https://github.com/topjohnwu/Magisk/files/6330583/magisk_log_2021-04-18T13-57-08Z.zip)

**Comment by yujincheng08** [comment]
seems to be related to https://github.com/topjohnwu/Magisk/commit/aa020578955e0063aada2d618c6432faf92a0d33

**Comment by yujincheng08** [comment]
try this from @vvb2060 

[app-release.zip](https://github.com/topjohnwu/Magisk/files/6386332/app-release.4.zip)

**Comment by Vstory** [comment]
> try this from @vvb2060
> 
> [app-release.zip](https://github.com/topjohnwu/Magisk/files/6386332/app-release.4.zip)

Thank you. Testing. . .

**Comment by Vstory** [comment]
Thank you all!
