### ISSUE TITLE
Galaxy A8/A8+ incompatibility 

### ISSUE THREAD

**Issue by BlackMesa123** [topjohnwu/Magisk#426]
Hello everyone.
Galaxy A8/A8+ users are reporting that flashing Magisk on their phone with Samsung Experience 9.0 (Android 8.0.0) up breaks their baseband, preventing them to use all its related features; after some tries we actually found it's related to the patched "init" file in ramdisk. Here there are the various logs to look closer this issue:
https://drive.google.com/open?id=1F0kBmFjG45Zh1-yvDYHVCKip7XEZ8SGo
Hope those will be helpful for the possible future fix of the issue, let me know if you need more infos/file to look at. Greetings!

**Comment by breakersvd** [comment]
@BlackMesa123 @topjohnwu 
I have this device and i worked on this bug about two days and in the last it was fixed

compiled magisk sources from latest commit (2018 - 08 - 12).

the problem (losing baseband modem functions) is because xmount overlay for `sbin` dir,

so the fix is like the next:

in file `bootstages.c` in `startup` function on [mount the /sbin tmpfs overlay]:
comment out the code: `xmount("tmpfs", "/sbin", "tmpfs", 0, NULL);`
now the problem must be fixed but we could not access to execute any file in `/sbin` dir
so we change `setfilecon("/sbin", "u:object_r:rootfs:s0");` to `setfilecon("/sbin", "u:object_r:system_file:s0");`.

Now everything should works fine like my device.

I tested it on some samsung devices and every thins was fine
but i don't know if this edits create a new bugs.

![screenshot_20180812-014641_root checker basic](https://user-images.githubusercontent.com/36429390/43996730-c75a014c-9dd1-11e8-9a52-a78958017ec6.jpg)

**Comment by BlackMesa123** [comment]
Great news then!
You mind if I merge your fix in my fork and release it on XDA temporarely, of course with credits lol.
Users should be happy and also topjohnwu can take all the time he wants to work on the issue and find a workaround that should be enough for all the devices

**Comment by BlackMesa123** [comment]
Great news then!
You mind if I merge your fix in my fork and release it on XDA temporarely, of course with credits lol.
Users should be happy and also topjohnwu can take all the time he wants to work on the issue and find a workaround that should be enough for all the devices

**Comment by breakersvd** [comment]
@BlackMesa123 
Sure we will share but first i need to do more checks because in android (5.1.1 - 6.0.1) need more work to allow user access to files in `/sbin` even if we set contexts to `system_file`,,
i'm working on it now

**Comment by BlackMesa123** [comment]
Good luck with it. Now gonna release a temporary zip for jackpot Oreo OS users till there's a better fix/gets fixed on a Stable/Beta official build

**Comment by breakersvd** [comment]
@BlackMesa123 @topjohnwu 

Now fixed A530F bug and executing magisk tools in rootfs (this file is ready to release and test):
- changelog:
-- commented out this line `xmount("tmpfs", "/sbin", "tmpfs", 0, NULL);`
-- added `non_overlay_sbin_codes();` function instead of `/sbin` overlay (to allow execute binaries),
    the function added in `late_start>core_only:` stage

tested on FrankeNDK.
i don't know if this edit will destroy root ability on other devices, anyway
@topjohnwu this is a temporary solution and i'm sure you will find a stable one as you always do

here is the file ready to compile:

[bootstages.txt](https://github.com/topjohnwu/Magisk/files/2280723/bootstages.txt)

@BlackMesa123 If you don't mind just compile with this file and tell us if that worked for you too.

Thanks in advance,

**Comment by 587saboor** [comment]
@breakersvd I tested @BlackMesa123's modified magisk that has your code that fixes the problem, but when I open magisk manager, it fc

**Comment by breakersvd** [comment]
@587saboor i think that zip is need to be recompiled with last bootstages.txt file above

**Comment by 587saboor** [comment]
@breakersvd oh ok, if you can, can you compile magisk for us?
currently @BlackMesa123 is asleep

**Comment by breakersvd** [comment]
@587saboor I'm working on it now, magisk needs more rules to patch sepolicy to get all permissions to su

**Comment by breakersvd** [comment]
@BlackMesa123 @587saboor 
Even with fix Baseband issue or not; Magisk needs to fix su access and i reported it to topjohnwu
[https://github.com/topjohnwu/Magisk/issues/470](https://github.com/topjohnwu/Magisk/issues/470)

**Comment by topjohnwu** [comment]
@breakersvd with this fix, it is impossible to hide root with MagiskHide. The `/sbin` overlay IS the critical key to MagiskHide.
Do you guys have a custom kernel that sets SELinux to permissive and see if it works?

**Comment by BlackMesa123** [comment]
@topjohnwu I released almost a month ago a test version of [my custom kernel](https://github.com/DevKingsTeam/android_kernel_samsung_universal7885) (it has SELinux Permissive aswell) but users reported Magisk wasn't working there too. Gonna release the stable version today and tell my testers to try v16.7 on it and check if it works

**Comment by topjohnwu** [comment]
OK, I nailed down the baseband issue to this service: `cpboot-daemon` in `init.baseband.rc`. For some reason the service cannot be started.
@BlackMesa123 you logs are not early enough, I can only see failures but they happens way too late (it is doing retries), do you have any ways to capture `dmesg` and `logcat` as early as possible (I would love to see logs from the beginning of boot)

**Comment by topjohnwu** [comment]
Ah, found it: 
`[   21.151486] defex: safeplace violation [task=init (/init), child=/root/cbd, uid=0]`
It's Samsung's stupid kernel blocking it from executing from `/root`

**Comment by topjohnwu** [comment]
@BlackMesa123 disable this in your defconfig to build a custom kernel that support Magisk
`CONFIG_SECURITY_DEFEX=y`
We will need to dig deeper to find out how to hexpatch the kernel to prevent this from happening

**Comment by BlackMesa123** [comment]
@topjohnwu gonna see what I can do. Thanks for your time!

**Comment by 587saboor** [comment]
@topjohnwu have you found the general fix yet?
(the one that doesnt need a custom kernel)

**Comment by BlackMesa123** [comment]
@587saboor he needs to find out which bytes needs to be patched to disable or at least avoid Defex to block the bins in the folders defined in its rules file. It isn't easy since to find the correct bytes to patch he needs to reverse the compiled kernel in order to have at least a clear deassembled code (with all the functions and branches), you just need to have patience till he finds out the issue

**Comment by breakersvd** [comment]
@BlackMesa123  @topjohnwu  @587saboor 
Finally i found a hexpatch for the stock kernel (tested on A530F 8.0.0)

in stock kernel sources:
`security/defex_lsm/defex_procs.c @318:`

> if (!p || p->pid == 1 || !p->mm) - [stock]
> if (!p || p->pid != 1 || !p->mm) - [patched]

and the matched bytes for that code is the hexpatch code:

`./magiskboot --hexpatch kernel b91f040071802f005460de b91f040071812f005460de`

Included in this build
[https://mega.nz/#!nJZzWY7R!aXjEWqzr_TeZQIz8QPsI6dAy9GuAd6tY8sjZ1-IkN30](https://mega.nz/#!nJZzWY7R!aXjEWqzr_TeZQIz8QPsI6dAy9GuAd6tY8sjZ1-IkN30)

this worked completely for my device on build A530FXXU2BRG3
with baseband and full root access

**Comment by 587saboor** [comment]
@breakersvd great! now i have root working https://mega.nz/#!Dp9lkYZb!p9yAHB0zBmSz87WUpE1NroXjmQ8-k2D6-qTcBjhAKZI

**Comment by BlackMesa123** [comment]
@breakersvd if Defex finally doesn't blocks nothing with that patch, this is a really good news. I suggest you to create a pull request so that @topjohnwu can add it in his future release, expecially since Samsung is starting to add Defex LSM in its new devices (confirmed that Note9 has it aswell)

**Comment by breakersvd** [comment]
@BlackMesa123 Yes with this patch defex will return to `task_defex_enforce` with DEFEX_ALLOW value and this will allow to execute anything from every where with any PID

**Comment by geiti94** [comment]
@breakersvd for N9 a new patch is needed. looks like samsung updated defex on note 9. i tryed your magisk zip but after boot no ril

**Comment by breakersvd** [comment]
@geiti94 Ok i will take a look into the kernel image and the source and see what i can do

**Comment by breakersvd** [comment]
@geiti94 Samsung didn't released the sources of N9 kernel but i have a hexpatch to test,
could you give it a try with your device ?

**Comment by geiti94** [comment]
@breakersvd yes sure i can try

**Comment by breakersvd** [comment]
@geiti94 
Flash the stock kernel then flash this zip:
[https://mega.nz/#!udx3nKBI!27vCCCUu8M8flYkdVKI7Of9g2ts_a7Afw3nj6HF69gk](https://mega.nz/#!udx3nKBI!27vCCCUu8M8flYkdVKI7Of9g2ts_a7Afw3nj6HF69gk)

**Comment by geiti94** [comment]
@breakersvd tested now. it bootloops at note 9 logo

**Comment by breakersvd** [comment]
@geiti94 Ok i think i need to wait samsung until release the N9 kernel sources

**Comment by geiti94** [comment]
@breakersvd thats what i am waiting too for compile finally a twrp for it. i need for the moment to patch the kernel with magisk on my s9+ then make a backup and reflash it on my n9

**Comment by DrKetan** [comment]
@geiti94 @breakersvd @topjohnwu N960F kerenl source out now

**Comment by breakersvd** [comment]
@DrKetan yes i saw that
i downloaded the sources and working now

**Comment by DrKetan** [comment]
@breakersvd 
`if (!p || p->pid == 1 || !p->mm)`
is already there, hex code you posted is not there on older kernel, I am downloading latest base so will check if same hex code available

**Comment by breakersvd** [comment]
@DrKetan if you have the device i will upload a new magisk zip to test,
did you have it and could you test ?

**Comment by DrKetan** [comment]
@breakersvd sure.

**Comment by breakersvd** [comment]
@DrKetan ok flash the stock kernel then flash this zip
[https://mega.nz/#!6F5UhKAL!PXl1bvn5WsmqXlLKYF41UddHQ0UdG00GgfJYW_-YEFE](https://mega.nz/#!6F5UhKAL!PXl1bvn5WsmqXlLKYF41UddHQ0UdG00GgfJYW_-YEFE)

**Comment by DrKetan** [comment]
@breakersvd Will do in 1-2 hrs and back to you. Thank you very much.

**Comment by breakersvd** [comment]
@DrKetan Ok, hope this file works fine

**Comment by DrKetan** [comment]
@breakersvd yes this code there in kernel b91f0400710030005460c6

**Comment by breakersvd** [comment]
@DrKetan I know but i just want to test in the device if it will disable it or not

**Comment by DrKetan** [comment]
WTH I am not able to reboot to download mode with vol down + bixby + power

**Comment by breakersvd** [comment]
Do it with adb:
`adb reboot download`

**Comment by BlackMesa123** [comment]
@DrKetan combination changed. Hold volume down+bixby buttons then plug your USB-C cable to your pc, it should boot in Download Mode then

**Comment by DrKetan** [comment]
@BlackMesa123 that did the trick Thank you.
@breakersv flashed & reset , waiting

**Comment by DrKetan** [comment]
Booted, need to check root Now

**Comment by breakersvd** [comment]
@DrKetan before check root, what about the baseband and network ?

**Comment by DrKetan** [comment]
Hey everything fine................
only one thing missing.. Your Paypal ID, kindly provide. Thank you very very much

**Comment by breakersvd** [comment]
@DrKetan SO glad to hear that, thanks for your tests

**Comment by BlackMesa123** [comment]
Well seems this story has finally reached an happy ending, aswell another Sammy security feature has been defeated once again (lel), thanks a lot you all, time to enjoy Magisk on newer devices/fws. @topjohnwu you decide when to close this issue and merge the new hexpatches on your future builds ;)

**Comment by DrKetan** [comment]
Yes agree @BlackMesa123
@breakersvd please your PayPal ID

**Comment by breakersvd** [comment]
@DrKetan thanks for your appreciation but no need for that it is just my work that i love

**Comment by DrKetan** [comment]
@breakersvd Thank you very very much. highly appreciate your work and service to community!

@topjohnwu kidndly accept and oblige for first successful Note 9 root with magisk
Confirmation number: 1JH41555BE2154130

**Comment by topjohnwu** [comment]
@breakersvd I've come up with my own hex pattern that might work even better
For N9, the original hex pattern `603A46B91F0400710030005460C642F9` disassembles to
```
LDR	W0, [X19, #0x638]
CMP	W0, #0x1
B.EQ	#0x608
LDR	X0, [X19, #0x588]
```
The 2 + 3 line is `p->pid == 1`, your patch changes it to `p->pid != 1`, which technically does not completely defeat the check. I come up with a better patch: `603A46B91F00006B0030005460C642F9`, which disassembles to
```
LDR	W0, [X19, #0x638]
CMP	W0, W0
B.EQ	#0x608
LDR	X0, [X19, #0x588]
```
The 2nd line can be seen as `p->pid == p->pid`, which means the 3rd line will always branch, which makes the operation simply `if (true)`

For the A8 variant, the only difference is that the branch offset is a bit different.
Stock: `006044B91F040071802F005460DE41F9`
```
LDR	W0, [X0, #0x460]
CMP	W0, #1
B.EQ	#0x5F8
LDR	X0, [X19, #0x3B8]
```
Patch: `006044B91F00006B802F005460DE41F9`
```
LDR	W0, [X0, #0x460]
CMP	W0, W0
B.EQ	#0x5F8
LDR	X0, [X19, #0x3B8]
```

Dunno why the exact same code compile to different instructions, gonna hope this 2 variants are all we will get in the future.

**Comment by topjohnwu** [comment]
Oh I know what you mean, it just seems  to be that `init` (PID=1) will always run in the whitelist so it technically won't be a problem. My patch is simply just an instruction before your's so it should do the same job.
Also, I choose to patch the instruction that is general (the other instructions have non-general offsets), I'm still finding a way to do these patches generally.

**Comment by breakersvd** [comment]
@topjohnwu 
I think no need to do like this search because samsung always update it's codes and in N9 samsung added more codes to optimizing `vmlinux` (i.e. FIPS and SMU (system mount rw protection)) so all offsets will be changed than original `gcc`
And if you try with chainfire RKP patch it will not work anymore but the good part is that samsung didn't enable RKP in N9 yet..

I think hexpatch binary is good in this way and no need to consume your time with it, for me i'm working now to add a patch to `magiskinit.c` to prevent RMM during boot (which disables oem unlock option and lock the bootloader and so losing root).

**Comment by BlackMesa123** [comment]
@breakersvd I'm pretty much informed about it since me and my team did the fix (lel). RMM State is hardcoded in bootloader so I doubt you can disable it from there, the trigger instead is in system frameworks and the only way it triggers is:
- 1 com.samsung.android.rlc (Rlc.apk) installed and with a version up to 2.0.00
- 2 ro.security.vaultkeeper.feature prop enabled
- 3 "CscFeature_RMM_EnableCode" bool enabled in CSC Features
Adding a script that does the job is enough to disable the protection. Regarding set it back to Normal without waiting the 168h uptime it's almost impossible since to unlock the phone contacts Samsung RMM Servers with a query and server then returns a token that is used by vaultkeeperd to write the flag (I doubt we can write the flag without a token and without root permissions)

**Comment by breakersvd** [comment]
@BlackMesa123 
The `RMM STATE` is coded in the `kernel ramdisk` and the `sboot` and the `system`.
on first boot the kernel runs `/system/bin/vaultkeeperd` and this elf file checks property `ro.security.vaultkeeper.feature` then if it was 1 it checks the service provider for the SIM if it match the CSC on device then it enable `oem unlock` and edit `steady` partition to unlock the bootloader.

Actually i did it with `magiskinit.c` to patch the `init.rc` to prevent it from create RMM `/dev/socket` and preventing from executing the `vaultkeeperd` binary also to edit the property and removing `Rlc.apk` and this success on [J600F, S8, S9, A8 7.1.1....] only waiting for 7 days to finish to test on my A8 8.0.0.

**Comment by BlackMesa123** [comment]
@breakersvd 
Nothing new basically lol, we figured out those things months ago when Samsung started to push Rlc v2 on their firmwares, so when first case of RMM Locks went ahead. [Here](https://forum.xda-developers.com/showpost.php?p=75360965&postcount=22) there's my post on XDA regarding RMM with attached a zip flashable file that does the magic, while [here](https://forum.xda-developers.com/samsung-a-series-2017/how-to/guide-root-install-twrp-samsung-t3747535) there's a thread by my collaborator @corsicanu full dedicated to the issue, with all the explanations and guides on how to get unlocked and how to not trigger anymore the lock (it's anyway enough to just remove Rlc.apk to not trigger the lock in frameworks, but in our custom kernels we anyway keep ro.security.vaultkeeper.feature to 0 and remove vaultkeeperd service aswell)

**Comment by breakersvd** [comment]
@BlackMesa123 
that is what i make the `magiskinit` to do during the boot and this happened successfully with all samsung devices except A8 8.0.0 because the kernel executes `vaultkeeperd` service before running `magisk` on `late_start` stage (unlike all samsung RMM devices) so i moved the patch to `magiskinit` (i.e. before running the original init binary) and just wait my device to test if it success

**Comment by FreshAvocado12** [comment]
Hello devs. J7 Pro J730G is also having this issue after Oreo 8.1.0 update. No baseband and imei when magisk is installed :/

**Comment by breakersvd** [comment]
[Magisk_2018-09-17_Defex.zip](https://github.com/topjohnwu/Magisk/files/2424093/Magisk_2018-09-17_Defex.zip)

**Comment by BlackMesa123** [comment]
@FreshAvocado12 
> Hello devs. J7 Pro J730G is also having this issue after Oreo 8.1.0 update. No baseband and imei when magisk is installed :/

Seems like Defex hexpatches needs to be rewrote because each device's kernel needs different patch due to different offsets. In my opinion add 250 patches in boot_patch.sh is a bit dirty, we might need a way to identify where Defex hex code to patch is located via script and then patch it

**Comment by breakersvd** [comment]
The defex codes bytes offsets is changed on each new upgrade for whole series of Samsung not each device, for example the above file supports both (J730*, J701*)

**Comment by BlackMesa123** [comment]
@breakersvd 
> The defex codes bytes offsets is changed on each new upgrade for whole series of Samsung not each device, for example the above file supports both (J730*, J701*)

So soc kernel sources related? Both J you mentioned have universal7870 soc so if the hexpatches are ok for both, they should be ok for all the 7870 phones with Defex. The problem still persists, different offsets so it needs more than 1 patch in boot_patch.sh, which is a bit dirty to see

**Comment by BlackMesa123** [comment]
@breakersvd 
> That is true but detecting hexpatches that need to be changed is not easy without sources until now,
> maybe this will be easier in future by another marks in the same offset of defex code, but now i do not have a time to detect that, hope soon

7870 8.1 sources are already out actually, [https://github.com/mohitmallick17/Quantum-Oreo-J7xelte](here) an example (j7xelte/J701x sources)

**Comment by breakersvd** [comment]
@BlackMesa123 
Yes i downloaded the source and compiled it and find the hexpatch and tested it and it is working (see the history of the zip file)

**Comment by FreshAvocado12** [comment]
I feel so good being replied by devs :D

**Comment by FreshAvocado12** [comment]
It works @breakersvd thank you!

Thanks a lot and to all of you here :) can i post this on XDA?

**Comment by breakersvd** [comment]
@FreshAvocado12 
It is already exists on XDA

@BlackMesa123 
I need an EFS dump from Oreo A530F, did you have it and could help me with sending it ?

**Comment by FreshAvocado12** [comment]
Thanks @breakersvd

**Comment by BlackMesa123** [comment]
@breakersvd 
> @BlackMesa123
> I need an EFS dump from Oreo A530F, did you have it and could help me with sending it ?

What file do you need?

**Comment by breakersvd** [comment]
EXT4 EFS dump [/dev/block/mmcblk0p3]

**Comment by BlackMesa123** [comment]
@breakersvd
> @BlackMesa123
> EXT4 EFS dump [/dev/block/mmcblk0p3]

I know, but what specific file you need from efs?

**Comment by breakersvd** [comment]
@BlackMesa123 
[nv_data.bin] I'm trying to bypass HWID with between two devices

**Comment by DrKetan** [comment]
@@breakersvd It seems latest base RI* have break the hex patch :( will confirm after getting new boot.img as I haven't yet downloaded, but users report suggest it's same.

**Comment by breakersvd** [comment]
@DrKetan 
Samsung did not release the (RI*) base until now, anyway i will do some tries and compares.

Please let continue talking on XDA
My account https://forum.xda-developers.com/member.php?u=9489654
I joined to XDA and i am planning to do some useful stuff and need your help 😉

**Comment by breakersvd** [comment]
@BlackMesa123 @DrKetan 
https://forum.xda-developers.com/android/software-hacking/test-disable-defex-security-samsung-t3851487

**Comment by DrKetan** [comment]
@breakersvd Sorry for late reply, actually I was checking opensource site and yet not released source so haven't visited here.  I think something went wront there as account is disabled. Anyway I haven't yet download latest built, BTW RJ* also available, should I go with RI or RJ also fine? I will download it tonight and try to test earliest possible. Thank you.

**Comment by breakersvd** [comment]
@DrKetan 
I face an account problem on XDA.
Anyway i found a **ONE** hex code that may remove defex security for all Samsung devices
and also maybe support Note 9 on Samsung SEC U2 - Base RI*.

if you have the device flash the full stock RI base that the old defex patch does not solve it and upload the boot.img.lz4 from the rom for me

**Comment by BlackMesa123** [comment]
@breakersvd 
> Anyway i found a **ONE** hex code that may remove defex security for all Samsung devices
> and also maybe support Note 9 on Samsung SEC U2 - Base RI*.

It is something in exec.c or another module which aren't directly Defex ones? (I doubt last one since an unique hexpatch is impossible due to diff offsets)

**Comment by breakersvd** [comment]
@BlackMesa123 
Including libs will always generate random offsets so i searched deeper and i found it in `fs/exec.c`
and the compiled codes for this file can not changed from device to another because it contents an unique code to defex that will never changed with all compilers and it is the main executing process during boot unlike the defex C files that may contents codes that defined in other lib.

The hex patch code that i detect is found in the all of models:
J730*
J530*
J701*
N960*
A530*
A730*
So i expect to support all of them, i just waiting to confirm device from any tester.

**Comment by DrKetan** [comment]
> @DrKetan
> I face an account problem on XDA.
> Anyway i found a **ONE** hex code that may remove defex security for all Samsung devices
> and also maybe support Note 9 on Samsung SEC U2 - Base RI*.
> 
> if you have the device flash the full stock RI base that the old defex patch does not solve it and upload the boot.img.lz4 from the rom for me

Here boot.img from bri firmware and failed with previous patch
If you want me to test, let me know 
http://www.mediafire.com/file/vd2n68vqzy1n8g3/boot.zip/file

Thank you

**Comment by breakersvd** [comment]
@DrKetan 
Here is the Magisk patched boot image:
https://mega.nz/#!uchlyCaT!7QjLSWPnP0UKtXcJkwLCf0DjyxFMVkt7SrLN_qtBLS8
could we continue on XDA thread please ?
https://forum.xda-developers.com/android/software-hacking/test-disable-defex-security-samsung-t3851487

**Comment by DrKetan** [comment]
> @DrKetan
> Here is the Magisk patched boot image:
> https://mega.nz/#!uchlyCaT!7QjLSWPnP0UKtXcJkwLCf0DjyxFMVkt7SrLN_qtBLS8
> could we continue on XDA thread please ?
> https://forum.xda-developers.com/android/software-hacking/test-disable-defex-security-samsung-t3851487

Perfect! 
Worked like a charm!

**Comment by breakersvd** [comment]
Baseband and root and everything ? !

**Comment by Austcool-Walker** [comment]
Samsung tablets are also facing an on-slot of Defex rooting prevention the SM-T380 and SM-T385 are also not able to get root because of Defex...
