### ISSUE TITLE
Patching boot.img on Galaxy Tab S6 lite (with lineage) fails

### ISSUE THREAD

**Issue by 0mark** [topjohnwu/Magisk#4262]
I have a Galaxy Tab S6 lite (gta4xlwifi) running Lineage 18.1 (Microg version from 2021-04-10). I extracted the boot.img and tried patching it, but i get:
```
! Installation failed
- Device platform: arm64-v8a
- Installing: 22.1 (22100)
! Unable to extract files
```
I also tried with the complete tar file, different methods of copying the files and different versions (22 and 22.1) of the Magisk App. I also tried turning it off and on again :D

The only occurance of "unable to extract files" appears to be in _extractFiles_ in _MagiskInstaller.kt_ (the Method also prints the other messages beforehand, so i guess its the right one). Maybe that helps. If i can provide more information or try something out let me know.

**Comment by 0mark** [comment]
Sorry, i thought i did. I try again, but as i'm not sure what was wrong, so i shall ask. I guess its about the format? I have the device and version information as well as the log in continuous text instead of a list respectively a file?

Sorry for asking, but i think just trying until it works would not be helpful either.

**Comment by mmokrejs** [comment]
Still magisk should state what file was selected for patching (it is easy on teh phone to pick a wrong file) and re-state whether *.img.lz4 or *.img or AP_*.tar or AP_*.tar.md5 files are expected. Would be helpful.
