### ISSUE TITLE
Magisk app bug

### ISSUE THREAD

**Issue by techIndia-hacker** [topjohnwu/Magisk#4265]
Device: oneplus 7t
Android version: 11
Magisk version name: 22.1
Magisk version code: 22100

Magisk app has a bug. The safetynet check fails but in reality safetynet has no problem at all.
![Screenshot_20210421-160409](https://user-images.githubusercontent.com/58086339/115540438-ad98fa00-a2bb-11eb-9392-e24e53da939b.jpg)
![Screenshot_20210421-160323](https://user-images.githubusercontent.com/58086339/115540472-b2f64480-a2bb-11eb-91f8-8e1de30ee776.jpg)

**Comment by techIndia-hacker** [comment]
@osm0sis please fix this. This is occurring on all Android devices irrespective of oem or os version

**Comment by Didgeridoohan** [comment]
@techIndia-hacker It's already been fixed: https://github.com/topjohnwu/Magisk/commit/94ec11db588b3096aef68cdbcfd16bf0b436b7c5

But, there's of course nothing that can be done for older releases of the Magisk app...

**Comment by techIndia-hacker** [comment]
Release a small bug fix update 🙂

**Comment by osm0sis** [comment]
Use the Canary
