### ISSUE TITLE
Installation fail after copy to cache on boot.img for Joying JY-VOS01N4GS (Spreadtrum x86_64)

### ISSUE THREAD

**Issue by parityboy** [topjohnwu/Magisk#4285]
This platform is based on the Intel Airmont SC9853i and is running Android 8.1.0. The last time I used Magisk to root one of these units was around July 2020, so I guess that would have been Magisk Manager 7.5.1 and Magisk 20.3.  This time around however (using the latest 22.1 as well as the latest canary build), it is failing to patch the boot image file, simply saying "Installation failed."

I have attached the unpatched boot image as well as the logs from the latest Canary build.

Device: Joying JY-VOS01N4GS
Android version: 8.1.0
Magisk version name: fb8000b5 (22104) (21)
Magisk version code: 22104

[logcat.txt](https://github.com/topjohnwu/Magisk/files/6372841/logcat.txt)
[magisk_install_log_2021-04-25T13:28:50Z.log](https://github.com/topjohnwu/Magisk/files/6372857/magisk_install_log_2021-04-25T13.28.50Z.log)
[boot.img.gz](https://mega.nz/file/zRg1DaSY#RlXt860k2gb43-tVamo5xiZK1pxAqgn-4C-s5upZ8rM)

**Comment by osm0sis** [comment]
Please tell me you didn't try to patch it still compressed as boot.img.gz ... 🤨

Otherwise, looking like a normal hdr "v0" image with dt here:
```

Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers

Supplied image: boot.img

Setting up work folders...

Image type: AOSP

Splitting image to "split_img/"...
BOARD_KERNEL_CMDLINE console=ttyS1,115200n8 loglevel=1 androidboot.hardware=sp9853i buildvariant=user
BOARD_KERNEL_BASE 0x00000000
BOARD_NAME 
BOARD_PAGE_SIZE 2048
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x01000000
BOARD_SECOND_OFFSET 0x00f00000
BOARD_TAGS_OFFSET 0x00000100
BOARD_OS_VERSION 8.1.0
BOARD_OS_PATCH_LEVEL 2018-05
BOARD_DT_SIZE 129024

Unpacking ramdisk to "ramdisk/"...

Compression used: gzip
33677 blocks

Done!
```

**Comment by parityboy** [comment]
**@osm0sis** 

Hahaha no I didn't. :grin: The boot.img file is the very same one I successfully patched last year with the older version of Magisk, but this time around it fails.  I really cannot understand why.

**Comment by osm0sis** [comment]
Yeah something wonky with the copy and flash environment I guess

**Comment by todlove** [comment]
https://github.com/rajkumardusad/Tool-X/discussions/217#discussion-2356639

**Comment by todlove** [comment]
https://github.com/TheAlgorithms/Python/issues?q=is%3Aopen+label%3Ahacktoberfest-accepted+author%3Atodlove

**Comment by todlove** [comment]
> [rajkumardusad/Tool-X#217 (comment)](https://github.com/rajkumardusad/Tool-X/discussions/217#discussion-2356639)https://github.com/TheAlgorithms/Python/issues?q=is%3Aopen+label%3Ahacktoberfest-accepted+author%3Atodlove

**Comment by androidacy** [comment]
Can we like not hijack github comments to spam please

**Comment by parityboy** [comment]
**@osm0sis**

I had a thought: is it possible to lock Magisk to a known working version? Or pull a known working version and install it manually?

**Comment by osm0sis** [comment]
Yep, GitHub Releases and the Canary repo apk history are both readily available. Then just don't update.

**Comment by parityboy** [comment]
> Yep, GitHub Releases and the Canary repo apk history are both readily available. Then just don't update.

I installed Magisk Manager 7.5.1 from the Releases page.  However, it insists on installing the latest Magisk, which it detects as 22.1 (22100).  How would I coerce it into installing Magisk 20.3?

**Comment by osm0sis** [comment]
Install the zip through the Modules page or use recovery

**Comment by Nashmi97** [comment]
97c1e181c5a96217021d96bcdc4d4e31fbfce2ac

**Comment by RaXorX** [comment]
Can we instead not run the patch files ourselves? I didn't look much but the boot_patch.sh can be passed a boot.img file. I ran that up and it created a stock_boot.img file but no patched file. In the terminal all went smoothly and from the looks of it, seems like the patched boot.img is created by util_functions.sh probably unless I am wrong.

**Comment by osm0sis** [comment]
Any luck with 23013? Some regressions were fixed.

**Comment by osm0sis** [comment]
No response in 2 weeks so I'll presume fixed unless new logs and confirmation from 23014 are produced.

**Comment by KingDutchIsGood** [comment]
This still happen on 23.00 magisk. Prime OS x86_64

**Comment by osm0sis** [comment]
I didn't ask about 23.0 I asked about Canary 2301x. Try with 23015. Fresh logcat and install log with the latest Canary if it's still happening.
