### ISSUE TITLE
Bootloop on Xiaomi Redmi Note 9 4G

### ISSUE THREAD

**Issue by xp-hard** [topjohnwu/Magisk#4290]
Device: Xiaomi Redmi Note 9 4G
Android version: 10 (merlin_global_images_V11.0.5.0.QJOMIXM_20200609.0000.00_10.0_global)
Magisk version name: fb8000b
Magisk version code: 22104

I tried to install Magisk on my phone both by fastboot and TWRP (ver 3.4.1b-0606), but it caused a bootloop.
Magisk logs, TWRP logs, original boot.img and patched-boot.img are in archive
[install log + TWRP log + patched boot + original boot.zip](
https://github.com/topjohnwu/Magisk/files/6400414/install.log.%2B.TWRP.log.%2B.patched.boot.%2B.original.boot.zip)

P.S. I tried to do it with stable versions to but they also caused the bootloop

**Comment by osm0sis** [comment]
Did an older version ever work for you?

**Comment by xp-hard** [comment]
I tried the latest's stable release and it's working fine. Thanks.
