### ISSUE TITLE
Magisk not working on lenovo yoga 1380f, device dosn't boot after flashing boot.img

### ISSUE THREAD

**Issue by odin81** [topjohnwu/Magisk#4300]
Device: Lenovo yoga Tablet 2 Pro 1380f
Android version: 5.0.1
Magisk version name: 22.1
Magisk version code: 22104

After patching and flashing the boot.img the device isn't booting any more.
The error message is "EFILINUX ERROR [android_image_start_buffer:737] boot image digital signature verification failed : 0000001A"
Also see attached screenshot
![e5082851-3c1b-46bf-b469-2e64d3b5f122](https://user-images.githubusercontent.com/228052/116767087-2de2fc00-aa2e-11eb-9e36-a602c1cc395d.jpg)

I get the device back working by flashing back the original boot.img with recovery.

I already tried it about 4 years ago with the same error.

The xposed framework was working on this device.
Any idea how to get this fixed?

I have attached my patched boot.img and the original boot.img
[boot.zip](https://github.com/topjohnwu/Magisk/files/6408711/boot.zip)
[magisk_patched-22104_Ufqes.zip](https://github.com/topjohnwu/Magisk/files/6408714/magisk_patched-22104_Ufqes.zip)

Here is the magisk log:
- Device platform: x86
- Installing: fb8000b5 (22104)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/data/data/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [7651744]
RAMDISK_SZ      [3529435]
SECOND_SZ       [0]
EXTRA_SZ        [1024]
PAGESIZE        [2048]
NAME            []
CMDLINE         [loglevel=4 console=logk0 earlyprintk=nologger androidboot.bootmedia=sdcard androidboot.hardware=byt_t_ffrd8 watchdog.watchdog_thresh=60 androidboot.spid=xxxx:xxxx:xxxx:xxxx:xxxx:xxxx androidboot.serialno=01234567890123456789 oops=panic panic=40 vmalloc=172M debug_locks=0 bootboost=1 vga=current i915.modeset=1 drm.vblankoffdelay=1 acpi_backlight=vendor i915.mipi_panel_id=3]
CHECKSUM        [8ad9ec742f58d1219d36245c3386cfbddd700741000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
EXTRA_FMT       [raw]
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Patch with flag KEEPVERITY=[false] KEEPFORCEENCRYPT=[false]
Found fstab file [fstab]
Found fstab file [fstab.byt_t_ffrd8]
Found fstab file [fstab.charger.byt_t_ffrd8]
Found fstab file [fstab.ramconsole.byt_t_ffrd8]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [extra]
- Repacking boot image
Parsing boot image: [/data/data/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [7651744]
RAMDISK_SZ      [3529435]
SECOND_SZ       [0]
EXTRA_SZ        [1024]
PAGESIZE        [2048]
NAME            []
CMDLINE         [loglevel=4 console=logk0 earlyprintk=nologger androidboot.bootmedia=sdcard androidboot.hardware=byt_t_ffrd8 watchdog.watchdog_thresh=60 androidboot.spid=xxxx:xxxx:xxxx:xxxx:xxxx:xxxx androidboot.serialno=01234567890123456789 oops=panic panic=40 vmalloc=172M debug_locks=0 bootboost=1 vga=current i915.modeset=1 drm.vblankoffdelay=1 acpi_backlight=vendor i915.mipi_panel_id=3]
CHECKSUM        [8ad9ec742f58d1219d36245c3386cfbddd700741000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
EXTRA_FMT       [raw]
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [7651744]
RAMDISK_SZ      [3807451]
SECOND_SZ       [0]
EXTRA_SZ        [1024]
PAGESIZE        [2048]
NAME            []
CMDLINE         [loglevel=4 console=logk0 earlyprintk=nologger androidboot.bootmedia=sdcard androidboot.hardware=byt_t_ffrd8 watchdog.watchdog_thresh=60 androidboot.spid=xxxx:xxxx:xxxx:xxxx:xxxx:xxxx androidboot.serialno=01234567890123456789 oops=panic panic=40 vmalloc=172M debug_locks=0 bootboost=1 vga=current i915.modeset=1 drm.vblankoffdelay=1 acpi_backlight=vendor i915.mipi_panel_id=3]
CHECKSUM        [a37442146a8d9797194b1c715322630a5630a819000000000000000000000000]

****************************
 Output file is written to 
 /storage/emulated/0/Download/magisk_patched-22104_Ufqes.img 
****************************
cp: can't preserve ownership of 'busybox': Operation not permitted
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
- All done!

And here the output of the mounts:
0_a106@YT2:/ $ cat /proc/mounts
rootfs / rootfs ro,relatime 0 0
tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,mode=600 0 0
none /dev/cpuctl cgroup rw,relatime,cpu 0 0
adb /dev/usb-ffs/adb functionfs rw,relatime 0 0
proc /proc proc rw,relatime 0 0
binfmtmisc /proc/sys/fs/binfmtmisc binfmt_misc rw,relatime 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
none /sys/kernel/debug debugfs rw,relatime,mode=755 0 0
none /sys/fs/cgroup tmpfs rw,seclabel,relatime,mode=750,gid=1000 0 0
pstore /sys/fs/pstore pstore rw,relatime 0 0
none /acct cgroup rw,relatime,cpuacct 0 0
tmpfs /mnt/asec tmpfs rw,seclabel,relatime,mode=755,gid=1000 0 0
tmpfs /mnt/obb tmpfs rw,seclabel,relatime,mode=755,gid=1000 0 0
/dev/block/by-name/factory /factory ext4 rw,seclabel,nosuid,nodev,noatime,data=ordered 0 0
/dev/block/by-name/system /system ext4 ro,seclabel,noatime,data=ordered 0 0
/dev/block/by-name/cache /cache ext4 rw,seclabel,nosuid,nodev,noatime,data=ordered 0 0
/dev/block/by-name/config /config ext4 rw,seclabel,nosuid,nodev,noatime,data=ordered 0 0
/dev/block/by-name/data /data ext4 rw,seclabel,nosuid,nodev,noatime,discard,noautodaalloc,data=ordered 0 0
/dev/block/by-name/logs /logs ext4 rw,seclabel,nosuid,nodev,relatime,data=ordered 0 0
none /logs/pstore pstore rw,relatime 0 0
/dev/fuse /mnt/shell/emulated fuse rw,nosuid,nodev,relatime,userid=1023,groupid=1023,defaultpermissions,allowother 0 0
tmpfs /storage/emulated tmpfs rw,seclabel,nosuid,nodev,relatime,mode=751,gid=1028 0 0
/dev/block/vold/179:17 /mnt/media_rw/sdcard1 vfat rw,dirsync,nosuid,nodev,noexec,relatime,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/block/vold/179:17 /mnt/secure/asec vfat rw,dirsync,nosuid,nodev,noexec,relatime,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/fuse /storage/sdcard1 fuse rw,nosuid,nodev,relatime,userid=1023,groupid=1023,defaultpermissions,allowother 0 0
/dev/fuse /storage/emulated/0 fuse rw,nosuid,nodev,relatime,userid=1023,groupid=1023,defaultpermissions,allowother 0 0
/dev/fuse /storage/emulated/legacy fuse rw,nosuid,nodev,relatime,userid=1023,groupid=1023,defaultpermissions,allowother 0 0

**Comment by topjohnwu** [comment]
This is an issue with your bootloader. An unlocked bootloader should not verify the boot image's signatures
