### ISSUE TITLE
Android P APIs for SU requests

### ISSUE THREAD

**Issue by Madis0** [topjohnwu/Magisk#432]
I think that Magisk Manager should use the new authentication APIs for superuser requests if it is run on Android P.

- For normal SU request, [Android Protected Confirmation](https://developer.android.com/preview/features/security#android-protected-confirmation) [(article)](https://www.digitaltrends.com/mobile/android-protected-confirmation-i-o-voting/)
- For biometrics-based SU request, [unified biometric authentication](https://developer.android.com/preview/features/security#biometric-auth) [(article)](https://www.androidpolice.com/2018/05/09/android-p-dp2-adds-new-api-support-fingerprint-face-iris-authentication/)

The first would prevent more kinds of malware/hijacking and the second would let users use their face or iris alongside fingerprint to authenticate.

**Comment by SuadMoh** [comment]
Is SU reqest working fine?? or not ???
which script i can use in my app to have root permissiion???

**Comment by topjohnwu** [comment]
Currently, I have no idea how to integrate the new UI with superuser requests. Maybe one day if I'm too bored I'll think if there is a better way to rewrite the whole UI

**Comment by Madis0** [comment]
The biometrics UI should be easier to implement as the OS provides it's own UI, FWIW.
