### ISSUE TITLE
modules list empty

### ISSUE THREAD

**Issue by tkalfaoglu** [topjohnwu/Magisk#4328]
Device:  LG G4
Android version: 9, ressurection remix 7.0.2
Magisk version name: 22.1
Magisk version code: 22104

Resurrection remix 7.0.2 on an LG G4.

Everything works great thank you, except online modules list empty..

Tried lots of things. Reinstalled app. Cleared data, pulled down to refresh, selected the clear repo cache in settings, etc..the online module list stays empty.. 

Ps. Terrible bug report system. Spent half an hour trying to report this problem.

**Comment by pndwal** [comment]
Is internet blocked by firewall app, ad blocking (custom hosts) etc?

**Comment by tkalfaoglu** [comment]
YES - I had lucky patcher block ads on the hosts file. I turned it off and got my list..
Weird how Magisk's modules are affected by that. Many thanks!
