### ISSUE TITLE
Magisk Manager - Feature Request: Remain on Modules Page After Module Install

### ISSUE THREAD

**Issue by stylemessiah** [topjohnwu/Magisk#4333]
Simple feature request...for anyone who installs multiple modules post ROM flash, can we please (for the love of god) have Magisk Manager remain on the Modules page after pressing back from a module install?

At the moment it returns to the main page...

Please help reduce the number of clicks needed by those of us testing multiple ROM's every week :)

Cheers

Device: Pixel 2XL
Android version: 11
Magisk version name: Magisk-22.1
Magisk version code: 22104

**Comment by NitroVenom** [comment]
Do it so that we can see a "install another module" besides the save installation log button 🤤

**Comment by stylemessiah** [comment]
Thanks @osm0sis

**Comment by osm0sis** [comment]
Still a useful request despite the module repo being removed. Multiple manual module installs, for example.

**Comment by stylemessiah** [comment]
> 
> 
> Still a useful request despite the module repo being removed. Multiple manual module installs, for example. 👍

One appreciates your continued support good Sir. 

Probably more useful now than ever :)

(me aka 73sydney)

**Comment by vvb2060** [comment]
@RikkaW
