### ISSUE TITLE
STCPay is able to detect root

### ISSUE THREAD

**Issue by nurullahsaeem** [topjohnwu/Magisk#4334]
Device: OnePlus 8 (IN2010)
Android version: Oxygen OS 11.0.5.5.IN21AA
Magisk version name: fb83000b5
Magisk version code: 22104

Latest version of STCPay is able to detect root even after enabling MagiskHide &  hiding the Magisk app. Safetynet is working & I'm able to use other banking apps. 
Here is the App: [STCPay](http://bit.ly/33qbgwS)
Logcat: [magisk_log_2021-05-09T21_22_29Z.log](https://github.com/topjohnwu/Magisk/files/6448167/magisk_log_2021-05-09T21_22_29Z.log)

**Comment by tyso77** [comment]
Asbra

**Comment by tyso77** [comment]
https://github.com/github/docs/blob/7b99fd054abd0dfb02c6f88e73fc45ed68935cce/CONTRIBUTING.md

**Comment by tyso77** [comment]
Egydy bra

**Comment by tyso77** [comment]
Gwtbwtb5qbrj.udnd6num

**Comment by tyso77** [comment]
Cs4qjbtbh jzmdu

**Comment by nurullahsaeem** [comment]
The banking app STCPay is able to detect Magisk somehow. 
Just **freezing magisk** using **Ice Box** makes the app usable again.
