### ISSUE TITLE
[PIXEL 4A 5G] failed to load/verify boot images

### ISSUE THREAD

**Issue by jihoy79** [topjohnwu/Magisk#4342]
When I try to flash magisk patched img on my pixel 4a 5g device with the code below,

"fastboot flash boot magisk_patched.img && fastboot reboot"

device shows an error "failed to load/verify boot images" and unable to boot

Device: Google Pixel 4a 5g
Android version: 12 (developer beta 3)
Magisk version name: 6b34ec3a
Magisk version code: 22105

**Comment by Displax** [comment]
Use the latest fastboot
https://developer.android.com/studio/releases/platform-tools
