### ISSUE TITLE
Direct Install method not working at my phone and no convenient fastboot install offered

### ISSUE THREAD

**Issue by Elias481** [topjohnwu/Magisk#4346]
Device: Xiaomi Mi Note 9
Android version: 10
Magisk version name: f822ca5b
Magisk version code: 23001

The Direct Install fails because the "boot partition" /dev/block/mmcblk0p34 is read only.
That might be related to dm-verify somehow which I did not disable afaik, but I like to disable as less security features as possible.
So I either would like a fix for the Direct Install and also would like the option to create a fastboot flashable boot.img without need for selecting the input image, as the file managers today are not appropriate, so cannot select the device directly and need to create the sourc boot.img in an extra step before, wich is the least I would like to avoid.

**Comment by cyl3x** [comment]
I had the same problem with my Xiaomi Mi 9T (Android 11). It was not the hardest thing to fix, but I was a little bit shocked for a moment.

**Comment by zgfg** [comment]
I have Xiaomi Mi 9T and for my all so far MIUI 10-11, Android 9-10 stock firmwares I could use both Patch & Flash or Direct install, with no problem

For patching, I extract boot.img by MiXplorer from the downloaded ZIP/recovery ROM, but I can also patch boot.emmc.win as backed-up by TWRP

From Magisk mngr/apk, when I choose Select and patch, it opens the built-in file mngr and I can pick up the boot img to patch

Now, I am on Xiaoimi.eu weeklies MIUI 12.6, Android 11, also on Magisk Canary 23001 and still both Patch & Flash but also Direct install methods work - see screenshots regarding to Direct install
![Screenshot_2021-05-13-07-14-22-167_com offsec nhterm](https://user-images.githubusercontent.com/51943147/118084295-c3807300-b3c0-11eb-975c-45000215ccf9.jpg)
![IMG_20210513_075429](https://user-images.githubusercontent.com/51943147/118084370-e3179b80-b3c0-11eb-8cab-9aaf226c2a56.jpg)

Hence, as far as I can see, my Boot is linked to /dev/block/sde48 and it's read-write

Btw, @cyl3x, what is your ROM on Mi 9T having read-only Boot?

**Comment by zgfg** [comment]
![Screenshot_2021-05-13-07-05-29-497_com mixplorer beta](https://user-images.githubusercontent.com/51943147/118085570-e744b880-b3c2-11eb-947e-813d47c290e5.jpg)
![Screenshot_2021-05-13-07-04-19-294_com mixplorer beta](https://user-images.githubusercontent.com/51943147/118085578-eb70d600-b3c2-11eb-8896-3a4dc6aa1894.jpg)

**Comment by zgfg** [comment]
![IMG_20210513_081435](https://user-images.githubusercontent.com/51943147/118085855-5d491f80-b3c3-11eb-8622-3804b4a7f0e8.jpg)
![IMG_20210513_081402](https://user-images.githubusercontent.com/51943147/118085869-62a66a00-b3c3-11eb-9826-2b4b33bdfddb.jpg)

**Comment by topjohnwu** [comment]
Looks like a ROM issue, not a Magisk issue

**Comment by cyl3x** [comment]
@zgfg i'm on xiaomi.eu weekly release. Since last Magisk installation nothing has changed. I don't have the knowledge to find the issue, but it has fixed with flashing the untouched boot.img from the downloaded rom

**Comment by Elias481** [comment]
> Looks like a ROM issue, not a Magisk issue

The magisk issue is not to have an option to create patched image read directly from partition in the first place.
Currently I do not know whether any improvement possible in magisk code to apply the patch online. I might investigate later. So if there is any way to temporary remove write protection or get around it.
I do not believe the issue will solve with patching stock boot as suggested here, but maybe I even test that.
It's this special kind of virtual partition so there may be reasons not to have it read write. Or maybe it's just that I do not want to disable Verity if not needed, just for a patch for time to time. So why not just offer an option or an error Händler that allows to keep the patched boot image on write error, for manual flashing?
