### ISSUE TITLE
Magisk Downloads position in list is lost

### ISSUE THREAD

**Issue by gqqnbig** [topjohnwu/Magisk#435]
我安装了Magisk v16.4，到下载界面，向下滚动一段距离，随便下载一个模块。然后会显示命令行，显示安装成功，然后我点击虚拟的返回按键。

期望的行为：Magisk返回到原来的滚动位置，所以我可以继续向下滚，寻找喜欢的模块。

实际的行为：Magisk返回到了列表顶端。

**Comment by MlgmXyysd** [comment]
Same question.
