### ISSUE TITLE
Black screen after boot in Lineage

### ISSUE THREAD

**Issue by xtexChooser** [topjohnwu/Magisk#4354]
Device:  Samsung SM-G9008W(kltechndou)
Android version: Lineage, lineage-18.1-20210513-nightly-kltechndou-signed.zip, Android 11
Magisk version name: 7717f0a
Magisk version code: 23001

I patched the boot.img extracted from the lineage install package and flash it to boot partition using fastboot like:
```
fastboot flash boot boot.img
```

Then I reboot my phone, I installed two modules to Magisk: MagiskFrida(from the repository), TaiChi(the lastest release from https://github.com/taichi-framework/TaiChi)

** My phone works correcly when there are no any modules **

Then I reboot again, after booting animation, it shows me the launcher with a black background, and there is no status bar.

But I also can open Magisk Manager, I try to uninstall the MagiskFrida and reboot.

It shows me a black screen, no launcher and no status but.

I can not open the activity history, only a black screen.

But I can power off my phone, I tryed to reboot to safe mode, but my phone starts a bootloop

Then I flashed the old boot.img(directly extracted from ZIP, original) and reboot, my phone works correctly now but there is no magisk.

# About TaiChi Magisk module

I flashed Lineage today.

Before I flash Lineage, I am using the original ROM from Samsung.

Magisk works correctly(but there are some problems in **Magisk Manager**) with the **SAME** Taichi module file before I use lineage.

# More Information

SAR: True
A/B: False
RAMDISK: True

**Comment by xtexChooser** [comment]
The old problem in Magisk Manager: #4147

Tip: Before my phone shows me a blackscreen, I opened touch position display in the developer settings and it works when my phone shows a blackscreen. A breathing light is on, then goes out later, a few seconds later it vibrates and then the breathing light lights up again, continuously looping.

**Comment by Didgeridoohan** [comment]
Sounds like it's Taichi causing issues, not Magisk. That it worked on your previous setup is in no way a guarantee that it'll work on your new setup...

**Comment by xtexChooser** [comment]
See https://github.com/taichi-framework/TaiChi/issues/1254 for logs


> Sounds like it's Taichi causing issues, not Magisk. That it worked on your previous setup is in no way a guarantee that it'll work on your new setup...

Thanks, I also reported it to TaiChi

**Comment by xtexChooser** [comment]
I checked the problem is caused by Taichi module
