### ISSUE TITLE
Device boot PIN prevents Magisk from working

### ISSUE THREAD

**Issue by shelaf** [topjohnwu/Magisk#4357]
Device: Asus Zenfone 5z
Android version: 10
Magisk version name: f822ca5b
Magisk version code: 23001

Magisk does not work well if the device boot PIN is set.

1. Su works.
2. Can't save any superuser settings.
3. Magisk Hide is same.
4. Hide the Magisk app does not work.
5. If disabled the device boot PIN, all works fine.
6. Boot.img patched with Magisk v20.4 works fine even if the device boot PIN is set (with Magisk Manager 23001).

[magisk_log_2021-05-15T193826Z.log](https://github.com/topjohnwu/Magisk/files/6486398/magisk_log_2021-05-15T193826Z.log)

**Comment by shakalaca** [comment]
https://github.com/topjohnwu/Magisk/pull/1601
https://github.com/topjohnwu/Magisk/commit/fe644e10d0244250379ea726359597034d949706

**Comment by osm0sis** [comment]
Looks like this was fixed. 👍

**Comment by shelaf** [comment]
Please tell me in which version it was fixed.

**Comment by osm0sis** [comment]
Maybe I misunderstood why @shakalaca referenced those commits 🤔

**Comment by osm0sis** [comment]
Try 23013? A number of regressions have been fixed.

**Comment by shelaf** [comment]
Tried 23014. But, the situation hasn't changed much.

Magisk does not work well if the device boot PIN is set.

1. Su works.
2. Can't save any superuser settings.
3. If disabled the device boot PIN, all works fine.
4. Flashing boot.img patched with Magisk v20.4 shows that it is not installed (with Magisk Manager 23014).

[magisk_log_2021-11-13T111456Z.log](https://github.com/topjohnwu/Magisk/files/7531255/magisk_log_2021-11-13T111456Z.log)

**Comment by shelaf** [comment]
Further investigation revealed that the superuser settings are saved even if device boot PIN is set, without additional setup when starting Magisk.

**Comment by yujincheng08** [comment]
` 05-15 19:38:02.582   648 12136 E : sqlite3_exec: attempt to write a readonly database`

**Comment by yujincheng08** [comment]
Could you provide adb logcat with latest CI?

**Comment by shelaf** [comment]
Sorry for the slow response.
In ver24306, works fine with boot PIN. Thanks.

**Comment by shelaf** [comment]
This issue recurs in version 25201.

**Comment by canyie** [comment]
provide logcat with 25201?

**Comment by shelaf** [comment]
with boot pin:
[magisk_log_2022-07-30T12.20.59.log](https://github.com/topjohnwu/Magisk/files/9224708/magisk_log_2022-07-30T12.20.59.log)

without boot pin:
[magisk_log_2022-07-30T12.24.57.log](https://github.com/topjohnwu/Magisk/files/9224714/magisk_log_2022-07-30T12.24.57.log)

**Comment by canyie** [comment]
Hmm, I mean `adb logcat`, not magisk log.
Also I see there are new errors that do not happen in 23001:
```
07-30 10:48:08.425 13771 13771 E : write failed with 32: Broken pipe
07-30 10:48:09.577 13799 13799 E : write failed with 32: Broken pipe
```
The error `sqlite3_exec: attempt to write a readonly database` is gone, so things may have been changed
