### ISSUE TITLE
Module not uninstalled if installing and uninstalling the module without rebooting

### ISSUE THREAD

**Issue by cl-ement05** [topjohnwu/Magisk#4363]
Device: Xiaomi Mi 8 (dipper)
Android version: 11
Magisk version name: f822ca5b
Magisk version code: 23001

Well title says it all.. If you install a module and then uninstall it without rebooting in the middle of this operation, Magisk won't uninstall the module. And the module will still be present at next reboot.

Note : I tested this with the SSH module for Magisk

**Comment by osm0sis** [comment]
The SSH module doesn't appear to properly clean up after itself ever:
https://github.com/Magisk-Modules-Repo/ssh/blob/master/install.sh#L158-L161

🤔

**Comment by osm0sis** [comment]
I can confirm using the similarly simple SQLite module. I believe this used to work, so would be a regression.

**Comment by cl-ement05** [comment]
> I can confirm using the similarly simple SQLite module. I believe this used to work as expected, so would be a regression.

Oh ok so it is not the module's fault ?

**Comment by osm0sis** [comment]
Well the SSH module leaves extra shit behind, but that's different from the issue at hand.

**Comment by cl-ement05** [comment]
> The SSH module doesn't appear to properly clean up after itself in an uninstall ever:
> https://github.com/Magisk-Modules-Repo/ssh/blob/master/install.sh#L158-L161
> 
> 🤔

So there would be 2 problems here ? :
1. Magisk showing an uninstalled module even after it has been uninstalled
2. SSH module related : some folders are not removed

So about the second question I have some kind of enhancement proposal. AFAIK Magisk uninstalls a module itself that's to say Magisk handles uninstallation task and the module has no control over it. So it would be great (especially in my case) that before Magisk does the uninstall task, it calls some sh function to run to let the module clean up some extras that Magisk couldn't remove. Sorry for my english 😢

**Comment by osm0sis** [comment]
Magisk already has this feature. The SSH module dev just isn't using it.

**Comment by cl-ement05** [comment]
> Magisk already has this feature.

Just to say : I tried to reproduce the exact same situation with Magisk V21.4 and same thing happens

**Comment by vvb2060** [comment]
I think this is the expected behavior, updating the module will reset any flags.

**Comment by osm0sis** [comment]
The UI is misleading then, since it appears that even with an update queued that the module can also be tagged for removal.

**Comment by cl-ement05** [comment]
> It is not allowed to update the module to be removed and it is not allowed to remove the module to be updated.

In my case, when a module is about to be installed (only reboot is needed to finish installation) does it have the update flag or is there any "to be installed" flag ?

**Comment by cl-ement05** [comment]
> The UI is misleading then, since it appears that even with an update queued that the module can also be tagged for removal.

Yes, when a module has the update flag, the remove button should be grayed out

**Comment by androidacy** [comment]
Imo, remove flag should override anything else.

I think the best way to approach this is give flags "weight", ie once one is found others are ignored. For instance, once remove flag is found, execute the necessary uninstall steps and move on, even if it also has the update flag.

Maybe show a warning in magisk manager "This module has a pending update. Are you sure you'd like to proceed with uninstall?"

**Comment by vvb2060** [comment]
`https://github.com/topjohnwu/Magisk/pull/4384/commits/5e49f3c464cc6a63ae31a975d73ac545066f784c`
