### ISSUE TITLE
SafteyNet API Error on v23 install

### ISSUE THREAD

**Issue by charltonstanley** [topjohnwu/Magisk#4372]
Device: pixel 3 (blueline)
Android version: 10 (Lineage 17.1)
Magisk version name:  rhk.t
Magisk version code: 23.0 (23000) (21)

Hi there, I have managed to update magisk to v23 via an roundabout method, however I still get the safteynet API error that this version fixed (according to the release notes). I'm unsure of what other logs you need for this; please let me know and I will get them uploaded.
Also, per the template instructions, I attempted to install the canary build from the canary tree, however it seems that the canary tree has been archived and that it is both ahead and behind master tree. So I wasn't able to comply with those since it seems that I don't know how to install canary builds. If somebody could help me with that, I'd be happy to install it and report back if this SafteyNet API issue still persists.

Thanks in advance.

**Comment by charltonstanley** [comment]
since the annoying little bot decided to close my issue I went ahead and tried the archived canary build and it actually did have the version number that the annoying little bot called out was the canary version.  I still get a safteynet api error on canary build.
thanks.

**Comment by Displax** [comment]
@charltonstanley clear your hosts

**Comment by charltonstanley** [comment]
@Displax thanks for the reply!
I'm not exactly sure how to do that.  I tried googling it and I found results where I could clear the default browser's cache as well as navigating to `/etc/hosts` and making sure that only the loopback addresses were present. Is that what you were referring to?

thanks again!

**Comment by Didgeridoohan** [comment]
The API error that was caused by the API key having been revoked is fixed in v23. If you continue having this error your device is simply not able to connect to the Google servers (for whatever reason).

https://www.didgeridoohan.com/magisk/MagiskHide#hn_SafetyNet_API_error

**Comment by charltonstanley** [comment]
@Didgeridoohan thanks a ton for the link. That is an extremely detailed page you have there--very helpful! :) Through it and some other research, I found that I misunderstood the requirements for SafetyNet as well as how it works. I didn't realize you needed Google Play Services (via GApps) installed in order for SafetyNet to work. I have been rocking the Aurora Store instead for (nearly) all my app needs. Sorry to have troubled everyone and thanks for the help/info!
