### ISSUE TITLE
Where can I download the latest Canary zip file

### ISSUE THREAD

**Issue by furopi** [topjohnwu/Magisk#4379]
Hey Guys,

can someone link me to the latest canary zip file please? I'm using a Amazon Fire HD 10 and I absolutely have to manually install the zip via twrp... Thank you in advance!

Kind regards,

Florian

Device: Amazon Fire HD 10 
Android version: 7.1
Magisk version name: 23 
Magisk version code:

**Comment by Didgeridoohan** [comment]
There's no longer any provided zips. Download the apk and rename to .zip.
https://topjohnwu.github.io/Magisk/install.html#custom-recovery
