### ISSUE TITLE
Active "systemless host" has problem with LINE application

### ISSUE THREAD

**Issue by backzaa** [topjohnwu/Magisk#4383]
I have problem with Line application.
When active systemless host in setting. LINE can't load all picture.

![Screenshot_2021-05-24-11-13-30-592_jp naver line android](https://user-images.githubusercontent.com/36920655/119431029-05ec6d00-bd3c-11eb-88c9-05315bcdccd8.jpg)

When deactive this Line app no has problem.

Magisk 23.0
Xiaomi mi note 3
Android 9.0
Miui 12.0

**Comment by Didgeridoohan** [comment]
Sounds like you have an entry in your hosts file that blocks LINE. You should probably look at that rather than it being an issue with Magisk.
