### ISSUE TITLE
Patched boot.img is 0KB when using Canary builds

### ISSUE THREAD

**Issue by gmg2719** [topjohnwu/Magisk#4385]
Device: ZTE A2021
Android version:11
Magisk version name: Canary 
Magisk version code: 23001
I use magisk patch boot.img , but got a patched one with 0KB.  However, when I use the latest released version, the patched boot.img is the same size of original boot.img. It seems Canary build got a issue on my boot.img. I attached the boot.img and the install log. Please help me to analyze it. Thanks!
[magisk_install_log_2021-05-27T23_19_10Z&&img.zip](https://github.com/topjohnwu/Magisk/files/6555135/magisk_install_log_2021-05-27T23_19_10Z.img.zip)

**Comment by gmg2719** [comment]
it seems my issue.

**Comment by Didgeridoohan** [comment]
There's not really any difference between the current stable (23000) and the current canary (23001) releases.

I couldn't reproduce your result with the provided boot image and canary 23001... Seems to work as expected, so maybe something was wrong with your setup?
