### ISSUE TITLE
Error verifying vbmetadata HASH MISMATCH

### ISSUE THREAD

**Issue by mariushilleke** [topjohnwu/Magisk#4387]
Device: Samsung Galaxy A51 
Android version: 11
Magisk version name: Magisk v23.0
Magisk version code: ¯\_(ツ)_/¯

Following along the installation-tutorial I experienced the same message from issue #3259.

I was using `samfirm.js` with `samfirm -m SM-A515F -r DBT` and got the respective tars.

```
28/05/2021  13:13     5,752,688,830 AP_A515FXXU4EUD7_CL21582303_QB39761917_REV00_user_low_ship_meta_OS11.tar.md5
28/05/2021  13:00         2,427,057 BL_A515FXXU4EUD7_CL21582303_QB39761917_REV00_user_low_ship.tar.md5
28/05/2021  13:14        26,542,269 CP_A515FXXU4EUD7_CP19011510_CL21582303_QB39761917_REV00_user_low_ship.tar.md5
28/05/2021  13:20       605,020,348 CSC_OMC_OXM_A515FOXM4EUD7_CL21582303_QB39761917_REV00_user_low_ship.tar.md5
28/05/2021  13:17       604,979,393 HOME_CSC_OMC_OXM_A515FOXM4EUD7_CL21582303_QB39761917_REV00_user_low_ship.tar.md5
```

Since my device had boot ramdisk I did not check for **Recovery Mode**.

I used Magisk to patch the firmware-file and got `magisk_patched-23000_ZnHmH.tar`.

But using this with Odin to flash it as AP with the other components as `BL`, `CP` and `CSC` (NOT `HOME_CSC`) delivered the screen from the above mentioned issue with a message saying `hash mismatch` and error verifying vb_metadata.

Do I have to extract something from the `AP`-file that only has to be patched and used as `AP` with Odin for flashing?

Or did I mistakenly used the wrong firmware, I got the information about model and region from the settings?

**Comment by mariodantas** [comment]
> Device: Samsung Galaxy A51
> Android version: 11
> Magisk version name: Magisk v23.0
> Magisk version code: ¯_(ツ)_/¯
> 
> Following along the installation-tutorial I experienced the same message from issue #3259.
> 
> I was using `samfirm.js` with `samfirm -m SM-A515F -r DBT` and got the respective tars.
> 
> ```
> 28/05/2021  13:13     5,752,688,830 AP_A515FXXU4EUD7_CL21582303_QB39761917_REV00_user_low_ship_meta_OS11.tar.md5
> 28/05/2021  13:00         2,427,057 BL_A515FXXU4EUD7_CL21582303_QB39761917_REV00_user_low_ship.tar.md5
> 28/05/2021  13:14        26,542,269 CP_A515FXXU4EUD7_CP19011510_CL21582303_QB39761917_REV00_user_low_ship.tar.md5
> 28/05/2021  13:20       605,020,348 CSC_OMC_OXM_A515FOXM4EUD7_CL21582303_QB39761917_REV00_user_low_ship.tar.md5
> 28/05/2021  13:17       604,979,393 HOME_CSC_OMC_OXM_A515FOXM4EUD7_CL21582303_QB39761917_REV00_user_low_ship.tar.md5
> ```
> 
> Since my device had boot ramdisk I did not check for **Recovery Mode**.
> 
> I used Magisk to patch the firmware-file and got `magisk_patched-23000_ZnHmH.tar`.
> 
> But using this with Odin to flash it as AP with the other components as `BL`, `CP` and `CSC` (NOT `HOME_CSC`) delivered the screen from the above mentioned issue with a message saying `hash mismatch` and error verifying vb_metadata.
> 
> Do I have to extract something from the `AP`-file that only has to be patched and used as `AP` with Odin for flashing?
> 
> Or did I mistakenly used the wrong firmware, I got the information about model and region from the settings?

redo it with magisk canary 23001 and re-open the issue as the bot closes automatically if not done with 23001
