### ISSUE TITLE
Fail to install Magisk Framework on Android Container within Chrome OS

### ISSUE THREAD

**Issue by 1457384613gh** [topjohnwu/Magisk#4389]
Fail to install Magisk Framework on Android as a sub-system within Chrome OS as the host system (some on [Brunch](https://github.com/sebanc/brunch))

Device: rammus, hatch, or volteer of Chrome OS
Android version: Android 11 x86_64 within Chrome OS r90 stable
Magisk version name: v23.0
Magisk version code: 23001

The system partition of the Android is SquashFS, named `system-raw.img`, and `vendor-raw.img` too. Everything is read-only but data of users.
Before Android 11, the unusual but only one way to install SuperSU is [arob of Gerriarob](https://github.com/Gerriarob/arob), which you might consult.

I have also asked help there https://github.com/Gerriarob/arob/issues/13
![Screenshot 2021-05-28 09.06.24.png](https://user-images.githubusercontent.com/69227436/119968389-fdb45c00-bfdf-11eb-90c3-fe783ce9f55d.png)
![Screenshot 2021-05-28 18.12.02.png](https://user-images.githubusercontent.com/69227436/119968666-4e2bb980-bfe0-11eb-8e98-100a0fcb74ff.png)

**Comment by newbit1** [comment]
You can try my script [rootCROS](https://github.com/newbit1/rootCROS)
It has its limitations like no Modules support, but it does provide root Access via Magisk.
If I try to replace he stock init with magiskinit, the container doesn't get mounted and the
apps won't start. So, this is the best I could come up with for now.

What ChromeOS Android 11 Image do you use? Never seen one before.
On AVDs, Magisk works pretty well up to Android S. Check out my script [rootAVD](https://github.com/newbit1/rootAVD) as well.

**Comment by 1457384613gh** [comment]
> You can try my script [rootCROS](https://github.com/newbit1/rootCROS)
> It has its limitations like no Modules support, but it does provide root Access via Magisk.
> If I try to replace he stock init with magiskinit, the container doesn't get mounted and the
> apps won't start. So, this is the best I could come up with for now.
> 
> What ChromeOS Android 11 Image do you use? Never seen one before.
> On AVDs, Magisk works pretty well up to Android S. Check out my script [rootAVD](https://github.com/newbit1/rootAVD) as well.

Thank you ! How nice you are !

**Comment by yujincheng08** [comment]
It should be a wontfix like support for WSA.

You should integrate Magisk into it manually like https://github.com/LSPosed/MagiskOnWSA.
