### ISSUE TITLE
What are snet.jar and stub-release.apk

### ISSUE THREAD

**Issue by superbonaci** [topjohnwu/Magisk#4392]
What are for `snet.jar` and `stub-release.apk`?

Device: rammus, hatch, or volteer of Chrome OS
Android version: Android 11 x86_64 within Chrome OS r90 stable
Magisk version name: v23.0
Magisk version code: 23001

**Comment by superbonaci** [comment]
In case developer attends the issue please update README

**Comment by yatli** [comment]
I see from the app that the SafetyNet check API is not foss -- maybe the in-app download is pointing to that jar?
