### ISSUE TITLE
MagiskHide makes "low latency for game" disappear

### ISSUE THREAD

**Issue by gykkuo** [topjohnwu/Magisk#4404]
Device: Mi 10
Android version: 11
Magisk version name: 23.0
Magisk version code: 23001

[magisk_log_2021-05-31T18_40_57Z.log](https://github.com/topjohnwu/Magisk/files/6569709/magisk_log_2021-05-31T18_40_57Z.log)
![Screenshot_2021-05-31-18-23-18-970_com topjohnwu magisk](https://user-images.githubusercontent.com/48140624/120181604-e9848080-c1d2-11eb-9c05-086439250d72.jpg)
![Screenshot_2021-05-31-18-25-01-736_com topjohnwu magisk](https://user-images.githubusercontent.com/48140624/120181610-eb4e4400-c1d2-11eb-9250-fd2fa88084ce.jpg)

**Comment by pndwal** [comment]
Is anything selected in MagiskHide list other than Google Play Services?

**Comment by gykkuo** [comment]
> Is anything selected in MagiskHide list other than Google Play Services?

I tried to choose GMS only and it doesn't work

**Comment by gykkuo** [comment]
> Is anything selected in MagiskHide list other than Google Play Services?

when it is available,I turn on the Hide and shut Settings down manually.it will disappear

**Comment by pndwal** [comment]
> > Is anything selected in MagiskHide list other than Google Play Services?
> 
> I tried to choose GMS only and it doesn't work

Toggle MagiskHide off, then on in Settings.Then check only Google Play Services com.google.android.gms.unstable service (SafetyNet) is checked in MagiskHide list.

**Comment by gykkuo** [comment]
> > > Is anything selected in MagiskHide list other than Google Play Services?
> > 
> > 
> > I tried to choose GMS only and it doesn't work
> 
> Uncheck everything in MagiskHide list including all Google Play Services components.
> 
> Toggle MagiskHide off, then on in Settings
> 
> Then check only Google Play Services com.google.android.gms.unstable service (SafetyNet) is checked in MagiskHide list.

tried, it does not work

**Comment by gykkuo** [comment]
> > > Is anything selected in MagiskHide list other than Google Play Services?
> > 
> > 
> > I tried to choose GMS only and it doesn't work
> 
> Uncheck everything in MagiskHide list including all Google Play Services components.
> 
> Toggle MagiskHide off, then on in Settings
> 
> Then check only Google Play Services com.google.android.gms.unstable service (SafetyNet) is checked in MagiskHide list.

i tried what you said,

and i tried toggled Hide on, closed setting and toggled ff, but it didn't appear.

it means I must reboot when it is vanish

**Comment by pndwal** [comment]
No; assuming hide is on, I said clear MagiskHide list, then toggle MagiskHide off then on (NOT on then off) in settings. Then check list... 😉

**Comment by gykkuo** [comment]
> No; assuming hide is on, I said clear MagiskHide list, then toggle MagiskHide off then on (NOT on then off) in settings. Then check list... 😉

I mean, i tried your idea, and I tried my idea
None of them worked

**Comment by Didgeridoohan** [comment]
Perhaps the feature is somehow dependent on one of the prop values that MagiskHide changes...

Check the Magisk log, under "hiding sensitive props" to see which props are changed, from what value and to what value. Then you could experiment with those to see if it makes any difference.

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/blob/master/native/jni/magiskhide/hide_policy.cpp#L53

**Comment by vvb2060** [comment]
It can't be fixed, you should ask MIUI to remove the region restriction.
