### ISSUE TITLE
Is this the end of Magisk?

### ISSUE THREAD

**Issue by mo123** [topjohnwu/Magisk#4412]
Since John Wu joined the Google Security Team,
will Magisk even be maintained anymore by someone else?

We can all say goodbye to passing Safetnet in future as all the loopholes will be patched instantly by Google and John Wu.

https://www.androidpolice.com/2021/05/17/google-hires-an-android-community-rooting-guru/

This issue can be closed.
I just wanted to inform users since 90% of users following Magisk on Github don't even know of this news.

Device: 
Android version:
Magisk version name: 
Magisk version code:

**Comment by CookieXD** [comment]
what the? No Comments?!
I really want to know the plans for the future of Magisk are!

**Comment by Didgeridoohan** [comment]
There won't be comments on the future of Magisk in some random Github issue... For news, just keep an eye on John's Twitter. That's where you'll find it first, whenever there is any news to be found.

**Comment by edo0** [comment]
@Didgeridoohan 
>That's where you'll find it first, whenever there are any news to be found.

Hopefully he will be able to comment on the subject of magisk, and not be gagged even from communicating about it - looking at how management reacted to his previous, now deleted, tweet

**Comment by osm0sis** [comment]
> Is this the end of Magisk?

No.
