### ISSUE TITLE
Magisk has appRisk:Generisk

### ISSUE THREAD

**Issue by venomop10** [topjohnwu/Magisk#4413]
I scannee magisk in virustotal it has appRisk:Generisk
Its not safe

**Comment by Didgeridoohan** [comment]
It's safe. That is one single hit on VirusTotal, and from the looks of it caused by nothing but an empty app label.

**Comment by venomop10** [comment]
Thanks im scared

**Comment by IzzySoft** [comment]
current version (2600) shows 3 hits now. In addition to Symantec's GenericRisk, Fortinet now reports the same, and Microsoft's yells "Trojan".
