### ISSUE TITLE
poco m3 PRO bootloop (installed via app patched boot.img

### ISSUE THREAD

**Issue by bucefalo2** [topjohnwu/Magisk#4419]
Device:  Poco m3 pro 5g
Android version: 11 rp1a.200720.011
Magisk version name: Magisk v23
Magisk version code: 
hello everyone !
i've this issue on Poco M3 pro 5g ! I tried also with Magisk v22.1 (there is no twrp available at the moment ) so i patch boot.img 
i also tried to fastboot 
`fastboot flash boot_a boot.img
fastboot flash boot_b boot.img`
same thing.. it just goes in loop so i need to reinstall original boot.img
( i also tried to use custom channel http://ppt.cc/fQfj1x )
thank you for all your help

**Comment by bucefalo2** [comment]
where?

**Comment by phatal** [comment]
any solutions? Face with same problem now.

**Comment by Displax** [comment]
You need to disable vbmeta check.
https://forum.xda-developers.com/t/root-gained.4290689
