### ISSUE TITLE
Magisk Hide对某游戏不起作用

### ISSUE THREAD

**Issue by lijun0326** [topjohnwu/Magisk#442]
首先原谅我用中文发issue（因为我英文太烂了x）
游戏在此
https://play.google.com/store/apps/details?id=com.aniplex.kirarafantasia
自从1.9更新以后，Magisk Hide+随机包名对于该游戏不起作用
环境：Android 8.1.0，Magisk 5.8.3，v16.4

**Comment by funnypro** [comment]
我问一下，你设备的SafetyNet是不是没过啊？

**Comment by funnypro** [comment]
@lijun0326 那么模块分别有什么？？

**Comment by funnypro** [comment]
@lijun0326 在Magisk安装时能过SafetyNet吗？

**Comment by lijun0326** [comment]
@funnypro 只能过basicIntegrity，MIUI，但是我觉得这游戏不会检查safetyNet（毕竟国内开发商

**Comment by funnypro** [comment]
@lijun0326 那我似乎没招了，看一下文档也许有什么帮助

**Comment by topjohnwu** [comment]
@lijun0326 我實際測試過後可以運行，你可能需要把 USB 偵錯關閉。
如果你是用OnePlus， 7b5d79d313dd027ded83e512a6e14a4a70ac9084 可以修復一些問題

**Comment by lijun0326** [comment]
@topjohnwu 你试试打开以后等30s？刚打开的时候可能不会闪退。我试了下v16.7是这样。
