### ISSUE TITLE
Bootloop with Xiaomi Poco M3 Pro 5G (device needs `fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img`)

### ISSUE THREAD

**Issue by eberhardweber** [topjohnwu/Magisk#4421]
Device: Xiaomi Poco M3 Pro 5G (camellian)
Android version: camellian_eea_global_images_V12.0.8.0.RKSEUXM_20210519.0000.00_11.0_eea_fc5972c36a.tgz
Magisk version name: f822ca5b
Magisk version code: 23001

Patching the Magisk-patched boot.img causes a bootloop on my new Poco M3 Pro 5G / Redmi Note 10 5G (same device, camellian).

> fastboot flash boot boot.img
> Sending 'boot_b' (65536 KB)                        OKAY [  1.441s]
> Writing 'boot_b'                                   OKAY [  0.218s]
> Finished. Total time: 2.276s

Just booting the patched boot.img gives the following error:

> fastboot boot magisk_patched-23001_1VHSg.img
> Sending 'boot.img' (65536 KB)                      OKAY [  1.525s]
> Booting                                            FAILED (Status read failed (Too many links))
> fastboot: error: Command failed

Here is the Magisk install log and the boot.img used for patching:

[magisk_install_log_2021-06-08T14_55_47Z.log](https://github.com/topjohnwu/Magisk/files/6616248/magisk_install_log_2021-06-08T14_55_47Z.log)

[boot.img](https://send.vis.ee/download/461d9facd7afda57/#aeQJtUXrc-1JL-R6lo1VKQ)

Unfortunately I don't believe there exists a custom recovery for the device yet, so my hands are a bit tied, but I figured it's better to get a report in quickly.

**Comment by bucefalo2** [comment]
oh.. nice to read your report.. i did post a report but was removed not sure if i did something wrong in reporting it though!
i could flash patched boot  but than it goes in bootloop and i need to boot boot.img regular again !

**Comment by bucefalo2** [comment]
I've got ROOT !! solution
i've uploaded a vbmeta.img on xda ... you need that !! in order to get root i did this
i used magisk 22.1 ( probably it works on v23 as well but .. well mine was tested on that )
ptach your boot.img on magisk as you normally do 
you need to flash vbmeta.img first : 
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img  ( the one i uploaded is an empty one )
than you just fastboot flash boot boot.img
this time will work !!!!!! it worked for me 
check my post on xda : 
[https://forum.xda-developers.com/t/root-gained.4290689/](url)

**Comment by akalivaty** [comment]
> I've got ROOT !! solution
> i've uploaded a vbmeta.img on xda ... you need that !! in order to get root i did this
> i used magisk 22.1 ( probably it works on v23 as well but .. well mine was tested on that )
> ptach your boot.img on magisk as you normally do
> you need to flash vbmeta.img first :
> fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img ( the one i uploaded is an empty one )
> than you just fastboot flash boot boot.img
> this time will work !!!!!! it worked for me
> check my post on xda :
> [https://forum.xda-developers.com/t/root-gained.4290689/](url)

Unfortunately, for my device, poco x3 pro, this method is not working.

**Comment by filt3rek** [comment]
@bucefalo2 thanks for your solution, it worked for me too with a Wiko View 3.

BTW, I also want to thank Magisk developpers/contributors for their work and inform Wiko View 3 users for who Magisk tells that there is NO RAMDISK, that the "normal" procedure works fine, not the "recovery" one. I've tried both, recovery doesn't work but boot does work.

Cheers

**Comment by osm0sis** [comment]
https://twitter.com/Hikari_Calyx/status/1368542481692856322

Looks like initial vbmeta disable command is expected and required. Magisk could maybe just document it better, but it's otherwise a non-issue. 👍
