### ISSUE TITLE
SEPolicy on HTC U12+ GSI

### ISSUE THREAD

**Issue by mfuerni** [topjohnwu/Magisk#4422]
XPosed is not able to hook System Framework, because SEPolicy is not loaded properly on HTC U12+ with ViperExperience.
Tried LSPosed and EdXposed with Riru, but XPrivacyLua doesn't work on both.

Unfortunately, my Magisk logs are empty: "Magisk logs are empty, that's weird"

Device: HTC U12+
Android version: 11, ViperExperience Beta 5
Magisk version name: f822ca5b
Magisk version code: 23001

**Comment by vvb2060** [comment]
Please read the LSPosed's Telegram Group FAQ
