### ISSUE TITLE
Service.d not running

### ISSUE THREAD

**Issue by Kronos2308** [topjohnwu/Magisk#4423]
The files on service.d are not loaded
no modules installed and the files are executable 755
<img style="display:inline" src="https://user-images.githubusercontent.com/36446521/121452384-3e748380-c997-11eb-9080-ef1805257c21.jpg" width="200"/><img style="display:inline" src="https://user-images.githubusercontent.com/36446521/121452390-3fa5b080-c997-11eb-9c03-e54bdf6098a7.jpg" width="200"/>

Device: Xiaomi Redmi4X
Android version: 7.1.2
Magisk version name: 23.0
Magisk version code: Stable

**Comment by Feri891** [comment]
Resmi 5a work
