### ISSUE TITLE
MagiskSU as standalone app .apk

### ISSUE THREAD

**Issue by DI555** [topjohnwu/Magisk#4432]
many of us used to use SuperSU long time ago...and even now when its frowzen.. , and we're feeling a lack of just functions of it..
could it be possible to create just MagiskSU standalone app?
and if standalone MagiskSU would be seamless compatible with Magisk app, - it would be really great magic !!!
many thanks in advance for this feature !!!

**Comment by DI555** [comment]
@topjohnwu , may be you'd find this feature not bad,
i would appreciate for answer!!!

**Comment by mariodantas** [comment]
Great request, hope they provide an anser to your request !
