### ISSUE TITLE
Fairphone 3 randomly does not reboot or fully shutdown with Magisk

### ISSUE THREAD

**Issue by bege10** [topjohnwu/Magisk#4434]
Device: Fairphone 3
Android version: 10 (/e/OS 0.17-q based on FairphoneOS, LineageOS for microG)
Magisk version name: f822ca5b
Magisk version code: 23001

The phone randomly (about every 4th or 5th time) does not reboot (need to press power button for 10-15 secs. to boot again) or does not fully shutdown (need to press the power button 10-15 secs. to boot the next morning and battery has lost about 20% of charge).

This began after installing Magisk:
For long term testing I did this:

- Install ROM (the issue is with /e/OS, LineageOS and FairphoneOS)
- Test for 2 days: everything OK
- Install TWRP
- Test for 2 days: everything OK
- Install Magisk (no modules)
- Frequently tried to reboot the phone:
   - Less than ~10 mins. after booting the phone: phone boots OK
   - More than ~10 mins. after booting the phone: phone hangs as described

This behavior has not changed after several months, OTA updates and with or without Magisk modules.
It has been confirmed 
-  https://github.com/topjohnwu/Magisk/issues/3681#issuecomment-828284643
-  https://community.e.foundation/t/fp3-e-mit-magisk-bootet-nur-wenn-der-akku-kurz-entfernt-wird/28707 (in German)

When the phone is connected to the computer for logcat and it does not reboot:
- the computer looses connection with the phone at shutdown as expected
- while the phone remains black and does not reboot the computer announces after some seconds a new device which then is named QUSB_BULK
- the phone must be rebooted via long pressing the power button as described above

**Logs when phone reboots correct:**
[logcatReboot_after.txt](https://github.com/topjohnwu/Magisk/files/6672357/logcatReboot_after.txt)
[logcatReboot_before.txt](https://github.com/topjohnwu/Magisk/files/6672358/logcatReboot_before.txt)
[magisk_log_2021-06-17T17_00_22Z_Reboot_before.log](https://github.com/topjohnwu/Magisk/files/6672363/magisk_log_2021-06-17T17_00_22Z_Reboot_before.log)
[magisk_log_2021-06-17T17_05_46Z_Reboot_after.log](https://github.com/topjohnwu/Magisk/files/6672364/magisk_log_2021-06-17T17_05_46Z_Reboot_after.log)

**Logs when phone does not reboot:**
[logcatNoReboot_after.txt](https://github.com/topjohnwu/Magisk/files/6672368/logcatNoReboot_after.txt)
[logcatNoReboot_before.txt](https://github.com/topjohnwu/Magisk/files/6672369/logcatNoReboot_before.txt)
[magisk_log_2021-06-17T19_26_39ZNoReboot_before.log](https://github.com/topjohnwu/Magisk/files/6672370/magisk_log_2021-06-17T19_26_39ZNoReboot_before.log)
[magisk_log_2021-06-17T19_32_03ZNoReboot_after.log](https://github.com/topjohnwu/Magisk/files/6672371/magisk_log_2021-06-17T19_32_03ZNoReboot_after.log)

**Comment by M-I** [comment]
Don't know if this will help debug this issue, but in termux, if you `reboot` in super user, it works.
```
su
reboot
```
`poweroff` isn't available in termux.
 
Reboot from Magisk (top right reboot icon) also works.

**Comment by bege10** [comment]
> 
> 
> Don't know if this will help debug this issue, but in termux, if you `reboot` in super user, it works.
> 
> ```
> su
> reboot
> ```
> 
> `poweroff` isn't available in termux.
> 
> Reboot from Magisk (top right reboot icon) also works.

Thank you.
I will try termux.
Here reboot from Magisk is the same as described above.

**Comment by M-I** [comment]
> > Don't know if this will help debug this issue, but in termux, if you `reboot` in super user, it works.
> > ```
> > su
> > reboot
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `poweroff` isn't available in termux.
> > Reboot from Magisk (top right reboot icon) also works.
> 
> Thank you.
> I will try termux.
> Here reboot from Magisk is the same as described above.

You're right Magisks reboot doesn't work. I probably tried just after `reboot` from termux,     It must have been a "Less than ~10 mins. after booting the phone:" reboot.

**Comment by bege10** [comment]
I tried to reboot with

- Termux: 90 secs. until reboot instead of up to 15 secs. normally.
- Normal terminal: same
- Power button: no reboot.

So this is not a good workaround either at least on my phone. Long pressing the power button is faster and more reliable.

**Comment by bege10** [comment]
> 
> 
> Don't know if this will help debug this issue, but in termux, if you `reboot` in super user, it works.
> 
> ```
> su
> reboot
> ```
> 
> `poweroff` isn't available in termux.
> 
The only way I found to reliably power off the phone is to reboot to recovery (most times with long pressing power button and volume up for 10-15 seconds after the screen has gone off) and to power off the phone from TWRP.

BTW, I found these commands for power control in terminal (just for information, not working either for this issue).

- svc power reboot
- svc power reboot recovery
- svc power shutdown

**Comment by osm0sis** [comment]
MagiskHide has been replaced by DenyList, which is powered by Zygisk. Is this resolved in 23013?

**Comment by bege10** [comment]
> 
> 
> MagiskHide has been replaced by DenyList, which is powered by Zygisk. Are these Fairphone issues resolved in 23013?

No, unfortunately not.
I never used MagiskHide. So the issue probably is not related to it.

**Comment by osm0sis** [comment]
Well you did mention MagiskHide causing problems in your other linked issue in the original post here. Alright though, I'll leave this open, but some new logs would be nice.

**Comment by bege10** [comment]
> 
> 
> Well you did mention MagiskHide causing problems in your other linked issue in the original post here. Alright though, I'll leave this open, but some new logs would be nice.

Yes, that was my fault in the beginning because the phone randomly does reboot correctly, but it turned out that it is independent from Hide enabled or disabled. That's why I did not mention it in this issue any more.

Did you find anything in the many logs I added above?

Here is another Magisk log after the phone has not rebooted for 10 mins. and I forced reboot with long pressing the power button.

[magisk_log_2021-11-15T14_47_08Z_no-reboot.log](https://github.com/topjohnwu/Magisk/files/7540918/magisk_log_2021-11-15T14_47_08Z_no-reboot.log)

**Comment by yujincheng08** [comment]
Any luck with Magisk 24?

**Comment by bege10** [comment]
As far as I can say the issue happens less often but it still happens quite often with reboot and reboot to recovery. I did not use shutdown any more because of this issue. I started testing shutdown. Results will take a while because I shutdown the phone in the evening and in the morning I can see whether the battery has been discharged significantly. I will continue testing while I am in hospital for two weeks.
But as said, at least with reboot and reboot to recovery the issue persists.

**Comment by canyie** [comment]
Recently I faced a similar reboot issue after I messed mounts of some key partitions, so I think investigating mounts when issue occurs may help.
In addition, I also think dangerous kernel patching may cause this issue.

**Comment by canyie** [comment]
Can you upload your original boot.img and the magisk patched one?

**Comment by bege10** [comment]
Here they are (I hope this is what you need)
https://www.dropbox.com/s/oxel1o83x3qhayq/boot.img?dl=0
https://www.dropbox.com/s/olbhj4l79758u53/boot_patched.img?dl=0

**Comment by canyie** [comment]
How about this boot image? Please report whether Magisk is working, and whether the reboot issue still does exist after flashing this one.
[boot_no_kernel_patch.zip](https://github.com/topjohnwu/Magisk/files/8398754/boot_no_kernel_patch.zip)

**Comment by bege10** [comment]
> How about this boot image? Please report whether Magisk is working, and whether the reboot issue still does exist after flashing this one. [boot_no_kernel_patch.zip](https://github.com/topjohnwu/Magisk/files/8398754/boot_no_kernel_patch.zip)

Shall I just flash it with TWRP?

**Comment by canyie** [comment]
> Shall I just flash it with TWRP?

Both TWRP and fastboot flashing are good.

**Comment by bege10** [comment]
- I only did a few tests with reboot. The device reboots very quick
- Apps don't have root access any more
- In Magisk app SU and modules tabs are greyed out
- When I rebooted to recovery to restore the boot partition TWRP had vanished, recovery of /e/OS showed up
- To restore TWRP I followed the instructions for this device that used to work
  -  adb reboot bootloader
  - fastboot boot twrp.img
  - in the booted TWRP
    - Advanced -> Flash Current TWRP
    - I got the error "E: can not find ramdisk-files.txt"

- Luckily it was enough to just restore the boot partition from the booted TWRP to get both back, TWRP and the boot partition.

**Comment by canyie** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8404574/app-debug.zip)
Try this? Kernel patch and magiskinit reserved, but won't patch init.rc so magiskd won't start.
You WILL LOSE ROOT, don't worry, just test if reboot issue still exists. You can get magisk back by re-flashing official magisk

**Comment by bege10** [comment]
> 



> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/8404574/app-debug.zip) Try this? Kernel patch and magiskinit reserved, but won't patch init.rc so magiskd won't start. You WILL LOSE ROOT, don't worry, just test if reboot issue still exists. You can get magisk back by re-flashing official magisk

Install this as APK?
Reboot necesary?
To get Magisk back
- install Magisk APK?
- or flash Magisk zip with TWRP?
- or restore boot partition with TWRP as I did before?

**Comment by canyie** [comment]
> Install this as APK?
Reboot necesary?

Unzip it, you will get a magisk apk, then you can flash it via Direct Install or TWRP (just like how you update official magisk).
Yes, reboot is necessary.

> To get Magisk back
install Magisk APK?
or flash Magisk zip with TWRP?
or restore boot partition with TWRP as I did before?

Just restore boot partition with TWRP as I did before

**Comment by bege10** [comment]
Direct install fails.

I am confused with what you say about install and flash.
How to flash an APK with TWRP? I only know how to flash IMG and ZIP files.
And I know of flashing Magisk as ZIP file in TWRP (patching boot partition) and directly installing Magisk app as APK (add app to control Magisk).

**Comment by canyie** [comment]
Rename it to .zip then you can flash it with TWRP.

**Comment by bege10** [comment]
Of course! 🥴
A few tests with rebooting to system and recovery:
When the phone reboots it does it very quick.
But it still sometimes hung so that I had to force booting with pressing the power button rather long.

**Comment by debian-user-france1** [comment]
I have a fairphone 3 and do not experience such thing. I'm only experiencing slow shutdown times if the ram is full and the zram filled up.

**Comment by osm0sis** [comment]
Latest TWRP versions also support flashing anything named Magisk-*.apk to make it easier too! 👍

**Comment by canyie** [comment]
Oh I have removed many things and the bug still persist :(
I think it's most likely caused by kernel patch. It cannot be fixed by us if so :(
Please try this, magiskinit will just execute the original init to continue booting
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8417221/app-debug.zip)

**Comment by bege10** [comment]
The issue appears irregularly, therefore it is a bit uncertain if I you tell the test results after a few tests.
But as far as I can say rebooting to system works quite quick (just a few seconds), also booting after shutdown. If hanging happens with both app-debug versions it only happens when I reboot to recovery.
Maybe it was just luck that only rebooting to recovery did hang with the app-debug versions, maybe it gives you another hint what may cause the issue?
In the past with normal Magisk hanging irregularly happened with all three power actions: reboot to system, reboot to recovery and shutdown.

It is difficult to do longer testing with different debug-apps/boot partitions because this phone is for daily use.

**Comment by bege10** [comment]
> Oh I have removed many things and the bug still persist :( I think it's most likely caused by kernel patch. It cannot be fixed by us if so :( Please try this, magiskinit will just execute the original init to continue booting [app-debug.zip](https://github.com/topjohnwu/Magisk/files/8417221/app-debug.zip)

I hope this is news that makes it possible to continue finding out the cause for this issue:
Over Easter I tested with this debug apk and the phone always rebooted very quick and shutdown worked correct also.
As soon as I restored the original boot partition the issue was back.

As said before, with the previous debug apk the issue only happened when rebooting to recovery (only a few tests).

**Comment by VA1DER** [comment]
The issue occurs 100% of the time when using /e/OS in conjunction with Magisk.

**Comment by canyie** [comment]
I still think kernel patching is the reason since all reboot functions should work without magisk core. Perhaps we can try to inject Magisk into system.img directly to avoid kernel patch and see if the issue disappeared. I'm not good with images, so we need the help of others :D . If the issue disappeared, this would be wontfix like #906 and #5124 unless we found a new way to avoid kernel patching.

**Comment by bege10** [comment]
> The issue occurs 100% of the time when using /e/OS in conjunction with Magisk.

Oh, I am lucky! Here it is only about 50%. 😊

**Comment by bege10** [comment]
> I still think kernel patching is the reason since all reboot functions should work without magisk core. Perhaps we can try to inject Magisk into system.img directly to avoid kernel patch and see if the issue disappeared. I'm not good with images, so we need the help of others :D . If the issue disappeared, this would be wontfix like #906 and #5124 unless we found a new way to avoid kernel patching.

I am pretty clueless about kernel patching and images. Do yo mean Magisk does kernel patching and one could circumvent that by injecting it into system.img? Or have the OS developers patched the kernel and that is incompatible with Magisk? Who can help to find the issue and maybe the team that can fix it?

**Comment by bege10** [comment]
A long story with an amazing end: After a few weeks after updating to v25 I can say that this Magisk version solved the issue. 🎉👍
