### ISSUE TITLE
Magisk causes bootloops on the Moto G7 with retrofitted dynamic partitions

### ISSUE THREAD

**Issue by JarlPenguin** [topjohnwu/Magisk#4435]
Device: Moto G7
Android version: 11
Magisk version name: f822ca5b
Magisk version code: 23001

This seems to be caused by magiskinit reading the cmdline too early unlike the stock init binary, thus detecting skip_initramfs in the cmdline rather than androidboot.force_normal_boot=1 (we use a kernel patch to change skip_initramfs into androidboot.force_normal_boot=1 since river is originally an A/B non-retrofit device launched with Android 9), and thus tries to mount the system partition which fails due to it being "dynamic".

Logs report as expected:
```
[    2.648739,1] magiskinit: Kernel cmdline info:
[    2.648751,1] magiskinit: skip_initramfs=[1]
[    2.648759,1] magiskinit: force_normal_boot=[0]
```

**Comment by voltagex** [comment]
Same on Lineage 18.1, on a G7 Power (ocean, not river AFAIK). @JarlPenguin do you have a workaround? I also don't think I can get the logs off this thing as it's booted to Lineage Recovery.

**Comment by voltagex** [comment]
Still after a fix.

**Comment by JarlPenguin** [comment]
> Same on Lineage 18.1, on a G7 Power (ocean, not river AFAIK). @JarlPenguin do you have a workaround? I also don't think I can get the logs off this thing as it's booted to Lineage Recovery.
> 
> Even uninstalling Magisk doesn't seem to fix the bootloop.

Hi - no fix or workaround yet; I've tried forcing the variables to true/false where needed in the Magisk code; doesn't help.

**Comment by NitroVenom** [comment]
> > Same on Lineage 18.1, on a G7 Power (ocean, not river AFAIK). @JarlPenguin do you have a workaround? I also don't think I can get the logs off this thing as it's booted to Lineage Recovery.
> > Even uninstalling Magisk doesn't seem to fix the bootloop.
> 
> Hi - no fix or workaround yet; I've tried forcing the variables to true/false where needed in the Magisk code; doesn't help.

Hi pro maintainer

**Comment by derrodirik** [comment]
Hello, unfortunately the problem still exists. Will there be a fix for this?

**Comment by pojavluncher2021** [comment]
Actually, try holding the power button for 15-20 seconds, it will work

**Comment by osm0sis** [comment]
Any further change with 23013? Why rely on a kernel patch? Why don't you set something in the boot.img cmdline?

**Comment by osm0sis** [comment]
No response in 2 weeks so I'll presume fixed unless new logs and confirmation from 23014 are produced.

**Comment by JarlPenguin** [comment]
Apologies for the lack of info, I didn't see the email until now.

> @JarlPenguin @voltagex @derrodirik Any further change with 23014?

Same result in 23014. https://paste.gg/p/anonymous/e955fefa181345af87f035107046243c

> Why rely on a kernel patch? Why don't you set something in the boot.img cmdline?

Setting `androidboot.force_normal_boot=1` in the boot.img cmdline results in recovery mode not being accessible. Since the G7 is a legacy A/B device we relied on the presence of `skip_initramfs` in the cmdline to either pass or not pass the above-mentioned parameter (hence a kernel patch being needed).

**Comment by osm0sis** [comment]
Okay, and Magisk relies on skip_initramfs being patched out of the kernel, so perhaps you'll have a add another kernel patch to support Magisk. 🤔

**Comment by JarlPenguin** [comment]
Right, `skip_initramfs` is already disabled on the kernel side: https://github.com/PixelExperience-Devices/kernel_motorola_sdm632/commit/04902beaae883e4b2f2f255814f5dd11d0c3daaf

https://github.com/PixelExperience-Devices/kernel_motorola_sdm632/commit/44049b8ca890e489d783d2f11b6636905d23a52f is the commit for replacing `skip_initramfs` in the cmdline to `androidboot.force_normal_boot=1` by the way.

**Comment by osm0sis** [comment]
Problem is that cmdline patching function you added will also get patched to want_initramfs due to the hex patch, unless you can obfuscate it

**Comment by JarlPenguin** [comment]
Thanks for the insight, it gave me some ideas. I'll look into the possible solutions.

**Comment by osm0sis** [comment]
I think it's gotta be a wontfix on Magisk's side though, since it's not really anything Magisk can accommodate, so closing this.

**Comment by JarlPenguin** [comment]
https://github.com/PixelExperience-Devices/kernel_motorola_sdm632/commit/29e8bec6bc186308b04580b5e8dbf94809834cff fixed the issue.  Unfortunately we couldn't force the boot image to pass anything other than `skip_initramfs` as it is forced into the cmdline by the bootloader, but at least the solution linked above works!
