### ISSUE TITLE
Cannot load self-compiled Magisk to the device

### ISSUE THREAD

**Issue by phuongnd08** [topjohnwu/Magisk#4437]
Device: Note 9
Android version: 10
Magisk version name: 23
Magisk version code: 23001

The device is already rooted with Magisk 23
I then build the latest github code base with `./build.py all`
Then I install app-debug.apk into the device:
```
adb install out/app-debug.apk
```
Then use "Direct Install" in attempt to install the latest magisk, however, the installation failed, logging: 
```
! Unable to check signature
! Installation failed
```

I have already set my `config.prop` as below:

```
##########################################################
# All variables in config.prop are optional
# Removing or leaving them blank will keep default values
##########################################################

# The version name of Magisk. Default: git HEAD short SHA1
version=22.1.04

# Output path. Default: out
outdir=out

#####################################################
# Signing configs for signing zips and APKs
# These 4 variables has to be either all set or not
#####################################################

# Path to keystore file
keyStore=mymagisk.keystore
# Keystore password
keyStorePass=mymagisk
# The desired key alias in the keystore
keyAlias=mymagisk
# Password of specified key alias
keyPass=mymagisk
```

THe keystore was generated with:

```
keytool -genkey -v -keystore mymagisk.keystore -alias mymagisk -keyalg RSA -keysize 2048 -validity 10000
```

**Comment by androidacy** [comment]
This is not a building help forum. Make sure you follow the docs word for word, and familiarize yourself with APK and APK signing.

I can confirm it's not a magisk problem as I sometimes compile magisk myself :)

**Comment by osm0sis** [comment]
You already have the official apk installed? You need to uninstall it before installing one with a different signature.
