### ISSUE TITLE
Can't boot android 11 with magisk mt6763 arm64-a

### ISSUE THREAD

**Issue by HedigehoG** [topjohnwu/Magisk#4438]
Device: Doogee BL9000
Android version: 11 (crDroid/AOSP)
Magisk version name: Canary
Magisk version code: 23001

I again try install android 11 on my BL9000, but device can not boot if install magisk 22+ (early versions don't try), boot does not change from device logo boot.
A similar situation was with android 10, but the load was endless on the boot ROM screen, it was solved by installing Magisk-phh, current [Magisk-v23.0-Stable-phh.zip](https://github.com/topjohnwu/Magisk/files/6680221/Magisk-v23.0-Stable-phh.zip)

logs that i can get:
[mounts.txt](https://github.com/topjohnwu/Magisk/files/6680524/mounts.txt) (taken from android 10)
[boot.zip](https://github.com/topjohnwu/Magisk/files/6680225/boot.zip) (original boot 8.1)
[magisk log.zip](https://github.com/topjohnwu/Magisk/files/6680234/magisk.log.zip)

**Comment by osm0sis** [comment]
So that random zip you say fixes it appears to have added script to boot_patch.sh to delete init.zygote32.rc and init.zygote64_32.rc from the ramdisk. Not sure if that's sufficient on its own to get it working or if there are other changes to magiskinit, perhaps you can test that idea.

For reference zygote32.rc contains:
```
service zygote /system/bin/app_process -Xzygote /system/bin --zygote --start-system-server
    class main
    priority -20
    user root
    group root readproc
    socket zygote stream 660 root system
    onrestart write /sys/android_power/request_state wake
    onrestart write /sys/power/state on
    onrestart restart audioserver
    onrestart restart cameraserver
    onrestart restart media
    onrestart restart netd
    onrestart restart wificond
    writepid /dev/cpuset/foreground/tasks
```

And 64_32.rc contains:
```
service zygote /system/bin/app_process64 -Xzygote /system/bin --zygote --start-system-server --socket-name=zygote
    class main
    priority -20
    user root
    group root readproc
    socket zygote stream 660 root system
    onrestart write /sys/android_power/request_state wake
    onrestart write /sys/power/state on
    onrestart restart audioserver
    onrestart restart cameraserver
    onrestart restart media
    onrestart restart netd
    onrestart restart wificond
    writepid /dev/cpuset/foreground/tasks

service zygote_secondary /system/bin/app_process32 -Xzygote /system/bin --zygote --socket-name=zygote_secondary --enable-lazy-preload
    class main
    priority -20
    user root
    group root readproc
    socket zygote_secondary stream 660 root system
    onrestart restart zygote
    writepid /dev/cpuset/foreground/tasks
```

**Comment by osm0sis** [comment]
@HedigehoG if you don't try my suggestion I'm going to have to close this as not enough info.

**Comment by HedigehoG** [comment]
Sorry for the long answer, this is my main device and it is not always possible to spend 4+ hours testing.
Deleting files did not change the situation, without a patch it loads and with a patch it does not even reach the loading animation.
But I attached the file tombstone
[boot.mag23.zip](https://github.com/topjohnwu/Magisk/files/7025600/boot.mag23.zip)

**Comment by osm0sis** [comment]
Did you manually delete those files from your stock boot image to test? It takes 4 minutes, not 4 hours, and I asked you to try that an entire month ago.

**Comment by osm0sis** [comment]
Also you just multiple versions of Android, with basically different problems on each, and don't provide boot.img for the current version you're having trouble on.

**Comment by HedigehoG** [comment]
> Did you manually delete those files from your stock boot image to test? It takes 4 minutes, not 4 hours, and I asked you to try that an entire month ago.

Yes, changing the ramdisk is very fast, but installing a different version of android on the main device is problematic when the twrp image is 20 + gb.

But the requested data was collected and the result remained the expected "Not sure if that's sufficient on its own to get it working..." 
And the only problem is with installing magisk on android 11 (logs and boot's https://github.com/topjohnwu/Magisk/files/7025600/boot.mag23.zip)

**Comment by osm0sis** [comment]
Try with the latest testing fork alpha? https://github.com/vvb2060/magisk_files/blob/master/app-release.apk

**Comment by HedigehoG** [comment]
> his will be a duplicate of #4447
Maybe, but from the answers with solutions they only have to disable the boot check, which is clearly not my case (there are no problems with the firmware even on a locked bootloader)

In previously attached logs:
01-01 00:01:40.537   383   383 I : Magisk 1eb83ad8-alpha-31(23001) daemon started
 01-01 00:01:40.539   383   383 I : * Device API level: 30
 01-01 00:01:40.563   383   385 I : ** post-fs-data mode running
 01-01 00:01:40.564   383   385 I : * Mounting mirrors
 01-01 00:01:40.564   383   385 I : mount: /sbin/.magisk/mirror/system
 01-01 00:01:40.564   383   385 I : mount: /sbin/.magisk/mirror/vendor
 01-01 00:01:40.565   383   385 I : mount: /sbin/.magisk/mirror/data
 01-01 00:01:40.565   383   385 I : link: /sbin/.magisk/mirror/cache
 01-01 00:01:40.565   383   385 I : link: /sbin/.magisk/mirror/product
 01-01 00:01:40.565   383   385 I : link: /sbin/.magisk/mirror/system_ext
 01-01 00:01:40.565   383   385 E : /data/adb is not present, abort
 01-01 00:01:40.565   383   385 I : * Loading modules
 01-01 00:01:41.865   383   521 I : ** late_start service mode running
 01-01 00:01:41.866   383   521 I : * Running service.d scripts
 01-01 00:01:41.866   383   521 E : opendir: /data/adb/service.d failed with 2: No such file or directory
 01-01 00:01:41.866   383   521 I : * Running module service scripts
 
tombstone_00
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'unknown/unknown/unknown:11/RP1A.200720.011/phh:userdebug/test-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2018-01-01 00:01:42+0000
pid: 494, tid: 494, name: android.hardwar  >>> /vendor/bin/hw/android.hardware.media.omx@1.0-service <<<
uid: 1046
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    r0  00000000  r1  000001ee  r2  00000006  r3  ffce2520
    r4  ffce2534  r5  ffce2518  r6  000001ee  r7  0000016b
    r8  ffce2520  r9  ffce2530  r10 ffce2550  r11 ffce2540
    ip  000001ee  sp  ffce24f0  lr  ee484881  pc  ee484894

backtrace:
      #00 pc 00038894  /apex/com.android.runtime/lib/bionic/libc.so (abort+172) (BuildId: aafb85e52ab877ff2b7f3604343b37fa)
      #01 pc 0000603f  /vendor/lib/libminijail_vendor.so (minijail_parse_seccomp_filters_from_fd+74) (BuildId: 4383e751851dc1b59775ef6792b1267d)
      #02 pc 000015ad  /vendor/lib/libavservices_minijail_vendor.so (android::SetUpMinijail(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)+300) (BuildId: 0365e90df573f821fa8add3cce9883fe)
      #03 pc 00001621  /vendor/bin/hw/android.hardware.media.omx@1.0-service (main+156) (BuildId: 67d330fd09ffbb43367cd95c3f181203)
      #04 pc 00033137  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+66) (BuildId: aafb85e52ab877ff2b7f3604343b37fa)
....
01-01 00:01:42.258   494   494 E android.hardware.media.omx@1.0-service: libminijail[494]: failed to compile seccomp filter BPF program from fd 6

**Comment by osm0sis** [comment]
Alright I'll leave it open in case John or vvb see something of value

**Comment by pojavluncher2021** [comment]
> Alright I'll leave it open in case John or vvb see something of value

Try to use superuser + F1VM, Remember
It has Android version 7.1
Also ask vvb or John to add A confirmation dialog if you are trying to start magisk 23.0 on Android 4, 3, 2.3 asking you to downgrade to 22.1 or v21
F1VM is better than magisk
And who needs the XPosed installer when you can get superuser access

**Comment by HedigehoG** [comment]
Try to use superuser... But it's not magisk way.
Костыльное решение установить патч системы и magisk-phh.
https://4pda.to/forum/index.php?showtopic=774072&view=findpost&p=942629
Duplicate of #71

**Comment by pojavluncher2021** [comment]
> Try to use superuser... But it's not magisk way.
> Костыльное решение установить патч системы и magisk-phh.
> https://4pda.to/forum/index.php?showtopic=774072&view=findpost&p=942629
> Duplicate of #71 

Magisk is trash and mimicking root, DO NIT INSTALL MAGISK!!, DONT BACKUP MAGISK!!, MAGISK IS A KNOCKOFF OF KINGROOT.DONT INSTALL OKAY?, Sorry for being quite angry but please don't install it, Delete magisk, Who cares about it.

**Comment by DiVa4YoU** [comment]
I understand why your angry, so am I.. I have always used kingroot and have rooted so many phones, within minutes. Just this 1 time i thought i might try magisk and I've ended up spending countless hours trying 2 root my phn (galaxy s21) with magisk and it said all these other apps I had to download with it to make it work. Not 1 of the apps works, so I'm deleting magisk and all the bloatware it put on my phone..
Thankyou so much for warning me, atleast I know its not me that has a problem.. Cheers for that buddy..  👍👍👍

**Comment by pojavluncher2021** [comment]
No problem, How about F1VM, It's soooo much better, Saves you countless
hours of time, All you had to do, Is use superuser That's all!
*AND I HATE MAGISK, DIE MAGISK*
Okay I'm not doing that anymore please don't kill me

**Comment by osm0sis** [comment]
Any change with 23013? A number of regressions have been fixed.

**Comment by osm0sis** [comment]
No response in 2 weeks so I'll presume fixed unless new logs and confirmation from 23014 are produced.
