### ISSUE TITLE
New ZIP signing code results in build failure.

### ISSUE THREAD

**Issue by ianmacd** [topjohnwu/Magisk#444]
Today's commit 32809e56d003d9fb87ad419bea53a7c89a13e5a3 introduces a build problem when it comes to signing the ZIP:

* Signing Zip

Exception in thread "main" java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.topjohnwu.utils.SignAPK.sign(SignAPK.java:88)
	at com.topjohnwu.utils.ZipSigner.main(ZipSigner.java:36)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
	... 6 more

Cheers,

Ian

**Comment by topjohnwu** [comment]
You supplied a wrong keystore password, just like the Exception implied.
Can you successfully build APKs with release flag on? It uses the same JKS

**Comment by ianmacd** [comment]
Yes, that's the thing. I can successfully build the MM APK using the same JKS. I made this JKS specifically for the purpose of building MM, but it's not being correctly applied to the ZIP file.

**Comment by ianmacd** [comment]
At the risk of providing superfluous information, the password I am providing in config.prop is correct. I just verified with apksigner on the command line that this is working as expected to sign the APK.

**Comment by topjohnwu** [comment]
@ianmacd continue from #445 , so the tool itself is working but the script is the problem?

**Comment by ianmacd** [comment]
Yes.

The issue is not the password, because I can sign APKs with the same key, and I can manually sign a ZIP file with the key:

$ java -jar ./utils/build/libs/zipsigner-3.0.jar release-key.jks XXXXX org.caliban XXXXX out/unsigned.zip out/signed.zip

The failure only occurs when the signing process is called via build.py.

Oddly, the code works as is for @kantjer. It's failing only for me.

Could it be related to metacharacters in the password? You don't appear to use the shell for anything, so I don't think it's that. I just can't think of anything else it could be.

**Comment by ianmacd** [comment]
I've figured it out by adding a bit of code to build.py.

keyStorePass and keyPass are like this in my config.prop:

keyStorePass="foo"
keyPass="bar"

It turns out that the quotes are ignored when signing the APK, but passed to the subprocess when signing the ZIP.

I guess you should make that behaviour consistent: either the quotes are or are not allowed.

**Comment by ianmacd** [comment]
Ugh. It's worse than that.

The quotes are actually **required** to sign the MM APK, because I have spaces in my passwords.

To sign the ZIP, however, I have to remove them again, because they are passed as string literals.

**Comment by topjohnwu** [comment]
May you try this updated script?
[build.py.zip](https://github.com/topjohnwu/Magisk/files/2260498/build.py.zip)
(It is zipped because Github does not support uploading `*.py`)

**Comment by topjohnwu** [comment]
@ianmacd thanks for the investigation, quotes should not be required and **should** be considered part of the password if included, I will fix it soon :)

**Comment by ianmacd** [comment]
Fixed now. Thanks.
