### ISSUE TITLE
Magisk Manager App ca no longer be hidden/renamed in 23.X?

### ISSUE THREAD

**Issue by noahbliss** [topjohnwu/Magisk#4443]
Device: Mi 9t Pro (not relevant)
Android version: MIUI 12 (doesn't matter for this bug_
Magisk version name: Canary
Magisk version code: 23001

Ability to hide the Magisk Manager app using a randomized/custom app name seems missing from 23.X. This was necessary to getting around Google for Work device policy enforcement. Any reason this was removed?

**Comment by osm0sis** [comment]
It wasn't removed. Mine's hidden right now. The option is only available if you're already rooted.

**Comment by noahbliss** [comment]
Got it, was able to wash rinse and repeat and that worked, seems like a bit of a limitation to require root to enable this feature. Removing work accounts so I can install the magisk app to rename the magisk app is very inconvenient.

**Comment by YumeMichi** [comment]
> It wasn't removed. Mine's hidden right now. The option is only available if you're already rooted.

What the hell? I don't understand. 🤣
