### ISSUE TITLE
New zip signing code fails.

### ISSUE THREAD

**Issue by ianmacd** [topjohnwu/Magisk#445]
You closed #444 after asking me a question, but before I could reply.

The issue is NOT the password. I can sign APKs with the same key, and I can manually sign a ZIP file with the key:

$ java -jar ./utils/build/libs/zipsigner-3.0.jar release-key.jks XXXXX org.caliban XXXXX out/unsigned.zip out/signed.zip

The failure only occurs when the signing process is called via build.py.

**Comment by topjohnwu** [comment]
Duplicate #444.
You should re-open the issue, not create a new one :)

**Comment by ianmacd** [comment]
Sorry. Didn't realise I had the power to do that.
