### ISSUE TITLE
Patched image comes with 0 bytes

### ISSUE THREAD

**Issue by AzCreep** [topjohnwu/Magisk#4453]
My magisk app doesn't patch the image file from original boot like the patched file comes as 0 bytes and it doesn't patch it

![image](https://user-images.githubusercontent.com/49355027/123189964-a4343580-d496-11eb-829f-d8f7285ea7a7.png)

Device: Redmi Note 9s
Android version: 11
Magisk version name: v23.0 and tested also v22.1
Magisk version code: (23000) (21)

**Comment by androidacy** [comment]
Before you go through the trouble of opening yet another issue, please test with latest canary version. Ie, version 23001, and if the issue persists, open another issue stating the version code as 23001
