### ISSUE TITLE
Image patched file 0 bytes (Canary version)

### ISSUE THREAD

**Issue by AzCreep** [topjohnwu/Magisk#4454]
So im rooting my phone for third time and im trying to root on the latest firmware that is V12.0.2.0 RJWMIXM and for some reason the patched images always come as 0 bytes i don't know what is going on i tried all versions of magisk and it's not going 
so i decided to give a shot with the canary version and it's still not working maybe i'm doing something wrong but this process worked for me in the past 

So i will post the log might be usefull

[magisk_install_log_2021-06-24T02_51_53Z[1].log](https://github.com/topjohnwu/Magisk/files/6705743/magisk_install_log_2021-06-24T02_51_53Z.1.log)

![image](https://user-images.githubusercontent.com/49355027/123190730-05103d80-d498-11eb-8d7b-3d891ddeadbb.png)

Device: Redmi Note 9s
Android version: 11
Magisk version name: f822ca5b
Magisk version code: (23001) (21)

**Comment by androidacy** [comment]
Hmm why did that trigger the bot

**Comment by AzCreep** [comment]
Maybe i did something wrong i’m sorry :c


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
