### ISSUE TITLE
Patched file with 0 bytes (canary version)

### ISSUE THREAD

**Issue by AzCreep** [topjohnwu/Magisk#4455]
So im rooting my phone for third time and im trying to root on the latest firmware that is V12.0.2.0 RJWMIXM and for some reason the patched images always come as 0 bytes i don't know what is going on i tried all versions of magisk and it's not going 
so i decided to give a shot with the canary version and it's still not working maybe i'm doing something wrong but this process worked for me in the past 

So i will post the log might be usefull

[magisk_install_log_2021-06-24T02_51_53Z[1].log](https://github.com/topjohnwu/Magisk/files/6705743/magisk_install_log_2021-06-24T02_51_53Z.1.log)

![image](https://user-images.githubusercontent.com/49355027/123190730-05103d80-d498-11eb-8d7b-3d891ddeadbb.png)

Device: Redmi Note 9s
Android version: 11
Magisk version name: f822ca5b
Magisk version code: 23001

**Comment by AzCreep** [comment]
Oh just to add that when i actually get a patched file with something besides 0 bytes my phone just gets stuck on the logo when rebooting and it doesn't go in just wanna let you all know

**Comment by pndwal** [comment]
Just a thought since it's Xiaomi; you have unchecked recovery mode, right?

**Comment by zgfg** [comment]
Can you attach your boot.img - patching the given img should work from any other phone

**Comment by pndwal** [comment]
Actually, John fixed a similar problem (on a Sammy device) just before his last releases:
https://github.com/topjohnwu/Magisk/commit/6b34ec3ab993e7339a6e879c4b6c1b3ea2a8ad0b

In case this was not fully resolved, please say if you are patching with App restored or hidden.

If App was hidden, try un-hidden (App, Settings, Restore the Magisk app). PW

**Comment by AzCreep** [comment]
@zgfg https://mega.nz/file/bK4ikJyb#bBJdRLsGVrRTEpVHcgpdf7Q_PhaKxh1aqcPAcD-i-YE

**Comment by AzCreep** [comment]
@pndwal i actually rooted this phone 2 times before but since system updates time to time i was always able to do  it but for some reason it's not working now cause it get stucks on the logo

**Comment by pndwal** [comment]
You mean you took OTA without restoring stock images, and now bootloops? Or other?

Flashing boot or recovery image or both will likely get it booting again... PW

**Comment by AzCreep** [comment]
ye like i did the root the 3rd the same way i did the other times like i go to magisk i patch the image then i drag to my pc to fastboot into the phone but for some reason it just stucks on the logo "MIUI" when starting the phone

**Comment by AzCreep** [comment]
@pndwal so what i do to unloop the thing is just fastboot the original boot.img and it works again i was thinking do it threw TRWP but i don't know if it will be a decent way

**Comment by pndwal** [comment]
Could do if you have TWRP. Fastboot just more reliable especially if twrp is half-baked.

Unclear if you took OTA. If so, ensure you download complete new ROM to get boot image, flash and check that that boots, then patch n try... PW

**Comment by AzCreep** [comment]
Ye i download full ROM from Original website the boot image works fine but after i patch it on magisk the patched.img doesn't let me boot on the phone it stucks on the logo

**Comment by zgfg** [comment]
> @zgfg https://mega.nz/file/bK4ikJyb#bBJdRLsGVrRTEpVHcgpdf7Q_PhaKxh1aqcPAcD-i-YE
Successfully patched, uploading (again 128 MB) to my Mega - will post you the link

Log:
- Device platform: arm64-v8a
- Installing: 1eb83ad8-alpha (23001)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [14876310]
RAMDISK_SZ      [797535]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [2165802]
OS_VERSION      [11.0.0]
OS_PATCH_LEVEL  [2021-04]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=1 androidboot.usbcontroller=a600000.dwc3 earlycon=msm_geni_serial,0xa88000 loop.max_part=7 msm_rtb.enabled=1 buildvariant=user]
CHECKSUM        [2b0216547a6a648b245c214cadfdf84b1baf5f0c000000000000000000000000]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
VBMETA
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [dtb]
Patch @ 01C4B2EC [736B69705F696E697472616D667300] -> [77616E745F696E697472616D667300]
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [14876310]
RAMDISK_SZ      [797535]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [2165802]
OS_VERSION      [11.0.0]
OS_PATCH_LEVEL  [2021-04]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=1 androidboot.usbcontroller=a600000.dwc3 earlycon=msm_geni_serial,0xa88000 loop.max_part=7 msm_rtb.enabled=1 buildvariant=user]
CHECKSUM        [2b0216547a6a648b245c214cadfdf84b1baf5f0c000000000000000000000000]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [2]
KERNEL_SZ       [14876321]
RAMDISK_SZ      [1248336]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [2165802]
OS_VERSION      [11.0.0]
OS_PATCH_LEVEL  [2021-04]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=1 androidboot.usbcontroller=a600000.dwc3 earlycon=msm_geni_serial,0xa88000 loop.max_part=7 msm_rtb.enabled=1 buildvariant=user]
CHECKSUM        [e40c89b27de95b0b09c9e0c711d6044ac79b9ef0000000000000000000000000]

****************************
 Output file is written to 
 /storage/emulated/0/Download/magisk_patched-23001_DCCr0.img 
****************************
- All done!

**Comment by zgfg** [comment]
@AzCreep 
Your boot.img patched:
https://mega.nz/file/s9dTjAAC#37QDmXJqp8ut3dJcjgpWZDMiP3aA1_D8p9KihFwAJuE

If anything goes wrong, just flash again your original boot.img

Please report/confirm

**Comment by AzCreep** [comment]
@zgfg it did the same my other patches did like he goes to the logo "MIUI" slowly flashes from bright to dark and after like 40 seconds or so maybe a minute he reboots and gives me a menu if i want to restart or clear the data"

**Comment by zgfg** [comment]
Did you previously have Magisk with some modules installed - maybe you have s bootloop due to some module

In that case use TWRP, Advanced, File Mngr, go to /data/adb/modules

Each submodule belongs to one folder. Put an empty file, named exactly: disable
to each subfolder and try booting with Magisk (patched boot img)

Is your phone maybe A/B device, how does Magisk app show (upload a screenshot)

**Comment by AzCreep** [comment]
ohhh i did have some modules cause i created this tutorial to bypass the mcdonalds root check 

here's the link if you wanna check out:  https://www.reddit.com/r/androidroot/comments/mxiphy/mcdonalds_root_check_failure_bypass_2021/

and here's the screenshot

![Screenshot_2021-06-26-19-36-48-592_com miui home](https://user-images.githubusercontent.com/49355027/123522715-feabdc80-d6b6-11eb-9673-2c918a8d21b8.jpg)

**Comment by AzCreep** [comment]
@zgfg oh i used trebel check for that a/b device and it says mine its only A-only system partition

**Comment by AzCreep** [comment]
> Did you previously have Magisk with some modules installed - maybe you have s bootloop due to some module
> 
> In that case use TWRP, Advanced, File Mngr, go to /data/adb/modules
> 
> Each submodule belongs to one folder. Put an empty file, named exactly: disable
> to each subfolder and try booting with Magisk (patched boot img)
> 
> Another thing-
> is your phone maybe A/B device, how does Magisk app show (upload a screenshot)

OMG i used orangefox for checking cause i couldn't find a version of twpr compatible with my phone and i deleted the modules inside and it rooted!!! thank you @zgfg for the help!!

**Comment by zgfg** [comment]
Ok, resolved, you can close
