### ISSUE TITLE
Magiak更新通道问题

### ISSUE THREAD

**Issue by funnypro** [topjohnwu/Magisk#446]
在MagiskManager设置Magisk更新通道为自定义且不输入任何东西并取消时，更新通道仍然为自定义

~~语文似乎全还给语文老师了~~

**Comment by Hickoo** [comment]
有magisk专版xposed框架包的历史包吗，因为小米好像刷beta3的会卡开机动画

**Comment by funnypro** [comment]
@Hickoo 你那是Android几的？

**Comment by Hickoo** [comment]
@funnypro 8.0 米6

**Comment by funnypro** [comment]
@Hickoo 看一下论坛啥的？？？
