### ISSUE TITLE
Magisk Hide 

### ISSUE THREAD

**Issue by adi90x** [topjohnwu/Magisk#4461]
Hey,

Is there any way to reverse the way it work ?
I.E : hide root to every application unless specified ?

Regards,
Adrien

**Comment by Jon8RFC** [comment]
@adi90x I believe I once read that the more things which are selected to be hidden, the more sluggish things become or the more power is consumed or the more likely things are to not work properly.  The main takeaway was "don't enable it for an app unless you actually need it".
