### ISSUE TITLE
Oneplus 8T ~ Magisk OTA patching results in "qualcomm crashdump" mode on reboot.

### ISSUE THREAD

**Issue by GenTarkin** [topjohnwu/Magisk#4476]
Following the OTA rooting method in the guide outlined here:
https://www.thecustomdroid.com/oneplus-8-pro-magisk-rooting-guide/
Resulted in crashdump mode on reboot =(
Luckily I was able to boot fastboot, then switch slot back to pre OTA update. Then I was able to do the normal "select a file and patch boot.img, then flash it using fastboot" approach and that process worked fine after the followup non-patched OTA attempt.
I used the newest version of magisk to patch, v23.
And this attempt was on my 8T.
Previously, like last week I had performed the same on a Oneplus 8, and it went just fine.
I did read that there was some 'difference' on oneplus devices made starting in april '21 that leads to this problem, dont know if thats just theory or what.

**Comment by osm0sis** [comment]
What regional variant ROM are you on? Sounds like you may be having issues with OnePlus switching to incremental Google OTAs.

There's currently no way for Magisk to get in the middle of this for now, since there are partition checks post-reboot when the snapshot merges occur, so here's a working method I've worked out: https://forum.xda-developers.com/t/tools-zips-scripts-osm0sis-odds-and-ends-multiple-devices-platforms.2239421/page-149#post-84764713

**Comment by GenTarkin** [comment]
Thanks for the guide, I used this one to recover: https://forum.xda-developers.com/t/guide-oneplus-8t-easy-root-for-all-unlocked-variants.4210775
I'll try yours next OTA =)

Im on stock ROM / international.    Ive done the OTA on the fly process on my OP8, same region rom: international stock ROM and had no issues. But yeah, got the crashdump on the 8T using same process.

**Comment by osm0sis** [comment]
Yeah 8T is when they switched to using incremental Google OTA, specifically on International/North American ROM, on stable channel.

**Comment by GenTarkin** [comment]
Hrm... interesting, well the OTA I did on my 8, felt like an "incremental" a well, it was a small download around 350MB ... so it definitely wasnt a 2GB+ "Full OTA" ... if Im understanding/applying the terminology correctly =)

**Comment by osm0sis** [comment]
Depends if Google serves it, also the other key here is that 8T is the first OnePlus Virtual A/B device. 🙂
