### ISSUE TITLE
Wifi not turning on (Android 11 Evolution X Rom MI A3)

### ISSUE THREAD

**Issue by omnibeast** [topjohnwu/Magisk#4478]
My device wifi is not turning on after flasing latest magisk zip file using custom recovery.

**Comment by androidacy** [comment]
This sounds like a device specific problem you should request assistance for in your device thread on xda or device group.

**Comment by iHemal** [comment]
i think you messed up with dtbo
flash the correct one from official evo group
it will fix
magisk is not causing anything here
