### ISSUE TITLE
Canary 23001 (f822ca5b)- select and patch file opens contacts. 

### ISSUE THREAD

**Issue by Patacakes** [topjohnwu/Magisk#4489]
Device: NX659J
Android version:android 10
Magisk version name: f822ca5b
Magisk version code: 23001

Issue:  when selecting install on the Magisk manager app. i tap "select and patch a file" it opens my list of contacts instead of my file browser.  so I cannot search for or select the boot.img to convert.

**Comment by osm0sis** [comment]
Doesn't on my device. Works as expected. So somehow your contacts app is listed as the default file picker on your device or something else weird is going on in Magisk. You need to upload a logcat of the behavior.

**Comment by xerta555** [comment]
> 
> 
> Device: NX659J
> Android version:android 10
> Magisk version name: [f822ca5](https://github.com/topjohnwu/Magisk/commit/f822ca5b23bea0a1b7a6e97841e253398e79fb8e)
> Magisk version code: 23001
> 
> Issue: when selecting install on the Magisk manager app. i tap "select and patch a file" it opens my list of contacts instead of my file browser. so I cannot search for or select the boot.img to convert.

Hi, maybe you could try to delete/remove the default open app associations for your contacts app. Because if your contacts app have wrong setting(s) for open association, it could explain your issue.
You can do that in your Settings app.

**Comment by osm0sis** [comment]
@Patacakes if you don't try our ideas to troubleshoot then I'm going to close this as not enough info.

**Comment by Patacakes** [comment]
hello,

thank you for your ideas,

checking stock file browsers permissions changed nothing.

I unbricked my phone and reinstalled rom fresh. the problem is gone so I have no way to repeat the issue until it randomly starts doing it again if i ever root my phone in the future.

i do appreciate the help, but first and foremost i needed my phone in working order.

if this issue re occurs again i will take logs and post them for you.

Kind Regards

Pat.


________________________________
