### ISSUE TITLE
Add ability to customize installing of Magisk

### ISSUE THREAD

**Issue by am4z1ng** [topjohnwu/Magisk#449]
Hello, John!

Will it be possible to add ability to customize installing of Magisk by renaming its zip file, e.g. add some special phrases to the name of zip file - "keepverity" ("verity"), "keepforceencrypt" ("encrypt"), "noverity", "noforceencrypt" ("noencrypt")?

Best Regards

**Comment by topjohnwu** [comment]
You can already customize installation using config files in /data/.magisk and many other locations.
I'll document more clearly soon.
