### ISSUE TITLE
Magisk "not installed" on OnePlus Nord (Android 11), previously-rooted apps still rooted

### ISSUE THREAD

**Issue by antgel** [topjohnwu/Magisk#4491]
Device: OnePlus Nord (avicii)
Android version: 11 (new update `NordOxygen_14.O.21_OTA_0210_all_2107031751_609c7093bad8455`)
Magisk version name: Canary
Magisk version code: f822ca5b (23001)

When I first got my phone (with Android 10), Magisk worked great. At some point, it started to display "Installed: N/A". See following screenshot:
![image](https://user-images.githubusercontent.com/295571/125161992-37a38100-e18e-11eb-9e93-56cadf7ffe64.png)

Unfortunately due to being busy, I didn't make notes at the time, but I think it was after an OTA upgrade to OxygenOS. When it worked, I would always download the update, run the "install in other slot" option, then reboot, and my new update would be rooted and work like a charm.

Since this issue started, apps like Titanium Backup can still get root and the SafetyNet check still passes, but because the Magisk app thinks that Magisk isn't installed, I can't access modules, hide, or any other features.

This has been going on for a few months, and I didn't know if it was something I missed, so when I got notifed about the new install today, I thought it was an opportunity to try again.

I downloaded the OTA to my phone and installed it. I also copied the OTA zip to my computer. I ran payload_dumper on the OTA zip to get the boot.img, copied that back to the phone and patched it with Magisk. I then copied it back to the computer and installed it to the phone in fastboot mode with `fastboot flash boot magisk_patched-23000_ed2rC.img`. I rebooted the phone and the situation persits.

I would like to attach the log, but I can't get it from the Magisk app because it doesn't think Magisk is installed, and I can't get it from the shell because su doesn't work:
```
$ adb shell
Nord:/ $ ls /cache
ls: /cache: Permission denied
1|Nord:/ $ ls /data/cache
ls: /data/cache: Permission denied
1|Nord:/ $ su
^C # Note I did Ctrl-C here, su hangs
130|Nord:/ $ magisk -v
23.0:MAGISK
```

Please let me know if there is any more information that I can give you to help you to help me. I am happy to pull whatever logs etc you need, I am just not an expert.

**Comment by antgel** [comment]
I'm using 23001?!?! @topjohnwu Help! :)

**Comment by BudDeuce** [comment]
You can type this: Magisk version code: 23001 @antgel

**Comment by antgel** [comment]
Thanks. I moved to LineageOS, and now more stuff (like this) works, including the appalling Bluetooth issues with the factory firmware. It may be an older OS, but at least it's stable.
