### ISSUE TITLE
[ERROR] Magisk not installing in J3 2016 (SM-J320H)

### ISSUE THREAD

**Issue by FrannDzs** [topjohnwu/Magisk#4494]
Hi, good evening, sorry for the inconvenience, I am having trouble installing Magisk with a Samsung J3 (SM-J320H).
I have tried patching the BOOT image and patching the full firmware and have done hard reset. I am attaching the logs and boot.img. I hope you have the solution, greetings!

Device: SM-J320H
Android version: 5.1.1
Magisk version name: V23 (latest)
Magisk version code: 23001

[boot.zip](https://github.com/topjohnwu/Magisk/files/6804287/boot.zip)
[magisk_install_log_2021-07-12T17_24_46Z[1].log](https://github.com/topjohnwu/Magisk/files/6804295/magisk_install_log_2021-07-12T17_24_46Z.1.log)
[magisk_install_log_2021-07-12T17_44_46Z[1].log](https://github.com/topjohnwu/Magisk/files/6804296/magisk_install_log_2021-07-12T17_44_46Z.1.log)

**Comment by osm0sis** [comment]
Not sure why that one auto-closed  🤔
