### ISSUE TITLE
Bluetooth app crashes continuously

### ISSUE THREAD

**Issue by SinjinJang** [topjohnwu/Magisk#4496]
I've finished to patch boot image and install Magisk app successfully.
However after below step, Bluetooth app was crashed continuously.
The way to stop showing crash message is to turn Bluetooth device off and Bluetooth Search option off in Android Setting.

* Reproduce Step:
  1) Finishing Magisk rooting
  2) Wi-Fi connection
  3) Magisk app launch and reboot to finish additional setup of Magisk
  4) Once the device is boot up, Bluetooth app was crashed at some point.
    : In my observation, rebooting the device seemed to be essential for reproducing this issue.

* Attached logs:
  - [dmesg_2021-07-13.txt](https://github.com/topjohnwu/Magisk/files/6805726/dmesg_2021-07-13.txt)
  - [logcat_2021-07-13.txt](https://github.com/topjohnwu/Magisk/files/6805730/logcat_2021-07-13.txt)
  - [magisk_log_2021-07-13T11:53:20Z.log](https://github.com/topjohnwu/Magisk/files/6805734/magisk_log_2021-07-13T11.53.20Z.log)

* Environments:
  - Device: Teclast P10HD+
  - Android version: Android 10
  - Magisk version name: v23.0 
  - Magisk version code: 23001

Thank you in advance.

**Comment by pndwal** [comment]
Is boot image patched and flashed extracted from exactly the same ROM package / version you are booting? PW

**Comment by SinjinJang** [comment]
> Is boot image patched and flashed extracted from exactly the same ROM package / version you are booting? PW

Yes, I'm sure. I only have one kind of stock firmware.
For reference, there was no problem on stock firmware before rooting.

**Comment by pndwal** [comment]
No OTA taken either?

**Comment by SinjinJang** [comment]
(Sorry for late reply.)
Hmm, when I connected Wi-Fi, there was some automatic update.
However I think this is just for updating some default apps to latest, not firmware side.
I've check that my stock firmware is latest version.

**Comment by shrihanDev** [comment]
I have this problem too, on LineageOS, but it is kinda rare. It usually happens when it is about to power off because of low battery.

**Comment by osm0sis** [comment]
No modules? My hunch would be your ROM doesn't like the selinux changes, or somehow it dislikes the way Magisk has mounted wherever the Bluetooth apk lives. 🤔

**Comment by osm0sis** [comment]
Any change with 23013?

**Comment by SinjinJang** [comment]
Oops, sorry for late check.
I want to test it, but I don't have the tablet anymore :-(
If this is the problem only for me, you could close this issue.
