### ISSUE TITLE
Stylo 6 the first ever with magisk root canary installed but issues 

### ISSUE THREAD

**Issue by Warlockguitarman** [topjohnwu/Magisk#4499]
Device: Q730MM Stylo 6
Android version:20
Magisk version name: 23 canary
Magisk version code:f822ca5b (23001) 

[magisk_log_2021-07-14T10:23:21Z.log](https://github.com/topjohnwu/Magisk/files/6817315/magisk_log_2021-07-14T10.23.21Z.log)
[magisk_log_2021-07-14T10:22:45Z.log](https://github.com/topjohnwu/Magisk/files/6817322/magisk_log_2021-07-14T10.22.45Z.log)
[magisk_log_2021-07-14T02:59:48Z.log](https://github.com/topjohnwu/Magisk/files/6817334/magisk_log_2021-07-14T02.59.48Z.log)

**Comment by Warlockguitarman** [comment]
What am i doing wrong? Im running canary and i added magisk logs

**Comment by osm0sis** [comment]
It was because the version code is just "23001"
