### ISSUE TITLE
Weird issue/interaction between Magisk >16 and Webview

### ISSUE THREAD

**Issue by catfluoride** [topjohnwu/Magisk#451]
I'm experiencing a weird problem. I'm on a Honor 9 with latest stock ROM (368) and Magisk 16.0 installed through ADB. No modules installed.

Now, everything works beautifully. On the other hand, every Magisk version >16 causes issues with Webview: apps that rely on it such as Aquamail or Twidere simply return white pages. This happens independently of Webview version or brand (being it Chrome or AOSP).

I know this is probably a highly specific situation, but I wonder if someone could suggest me something to try to overcome the issue.

Thanks a lot in advance

**Comment by funnypro** [comment]
已经排除了可能是其他的东西造成的问题吗？

**Comment by funnypro** [comment]
已经排除了可能是其他的东西造成的问题吗？
