### ISSUE TITLE
Feature Request: Add an option for Magisk in the Share/Open With menu for quick installation of ZIP files.

### ISSUE THREAD

**Issue by shrihanDev** [topjohnwu/Magisk#4512]
Device: j7elte (Samsung J7 2015) 
Android version: 10 (Q) (LineageOS)
Magisk version name: 23.0
Magisk version code: 23001 (?)

As per the title, I just wanted to suggest that there should be an option for installing a module with Magisk in the Share or Open With menu of a zip file, so that it can be directly installed from a file manager, without having to open Magisk and navigating to the location (again). I dunno, I think it makes the app a bit productive.

I hope it doesn't sound nonsense, and that this issue is not against the guidelines or something.

**Comment by topjohnwu** [comment]
If the app is able to accept shared files, it would be very easy to detect, so unfortunately this feature will not be accepted
