### ISSUE TITLE
disable moudle

### ISSUE THREAD

**Issue by w2016561536** [topjohnwu/Magisk#4513]
Would you like to add a new feature "When device reboot serval times then magisk turn into "kernel mode" and disable all moudles". I think it is useful for the user who doesn't have a third-party recovery.

Thanks!

**Comment by Didgeridoohan** [comment]
Just boot your device to Safe Mode and you'll get the same result.
https://topjohnwu.github.io/Magisk/faq.html#q-i-installed-a-module-and-it-bootlooped-my-device-help

**Comment by w2016561536** [comment]
> Just boot your device to Safe Mode and you'll get the same result.
> https://topjohnwu.github.io/Magisk/faq.html#q-i-installed-a-module-and-it-bootlooped-my-device-help

My phone model : Samsung A6060
system : Android 11 ,One ui 3.1

thanks for your precise advice. 
But samsung banned all user apps when it is triggered ,and magisk doesn't support to move manager into system.
Although root premission is useable .I dont't know whether magisk has disabled moudles.

**Comment by Didgeridoohan** [comment]
You didn't read the link I posted, did you? I'll paraphrase...

That's exactly how Safe Mode works. Magisk detects that you boot to Safe Mode, disables all modules and when you reboot back to regular Android they stay disabled.

**Comment by w2016561536** [comment]
> You didn't read the link I posted, did you? I'll paraphrase...
> 
> That's exactly how Safe Mode works. Magisk detects that you boot to Safe Mode, disables all modules and when you reboot back to regular Android they stay disabled.

Sorry ,that is my fault .It relly works.
Thanks for your contribution to magisk project!
