### ISSUE TITLE
Moto G7 power: installing Magisk leads to heavy graphical glitches

### ISSUE THREAD

**Issue by RalfJung** [topjohnwu/Magisk#4514]
After installing Magisk on the Moto G7 power, the screen starts acting up: everything is normal right after boot, but when turning the screen off an on again, all colors are wrong -- like when someone randomized the color palette of a GIF file. This seems to be a [common problem with this device](https://forum.xda-developers.com/t/display-problems-after-flash-rom-magisk-gapps.4162955/).

To fix this, I have to uninstall Magisk and *then* do a factory reset -- the issue somehow persists even once Magisk is gone.

Magisk log file: [magisk_log_2021-07-24T11_03_39Z.log](https://github.com/topjohnwu/Magisk/files/6872145/magisk_log_2021-07-24T11_03_39Z.log)

Device: Moto G7 Power ("ocean")
Android version: LineageOS 18.1
Magisk version name: v23
Magisk version code: 23001

**Comment by osm0sis** [comment]
You're going to need a logcat and dmesg while you're at it. The fact that it persists suggests some kind of issue with calibration files for example. Must be something your device doesn't like about zygote forking or something.

**Comment by RalfJung** [comment]
Here's an `adb logcat` that starts as close to the device boot as I could make it:
[bootlog.txt](https://github.com/topjohnwu/Magisk/files/6880963/bootlog.txt)

And here's the output of `adb shell dmesg` (after `adb root`):
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/6880970/dmesg.txt)

Are those the logs you were asking for?

**Comment by RalfJung** [comment]
> The fact that it persists suggests some kind of issue with calibration files for example. 

Is there any way to reset those? I am trying really hard to find away to get rid of this glitch without wiping the data partition, and so far I failed. This would be useful to at least temporarily have root...
I did try to `fastboot flash boot_a` and `fastboot flash boot_b` the original `boot.img` back, and even to reinstall LineageOS entirely, but none of that helped. Neither did properly powering off the device (instead of just rebooting all the time).

**Comment by RalfJung** [comment]
Actually it might be that this problem is triggered reliably by Magisk, but can arise even without:
https://www.reddit.com/r/LineageOS/comments/mmwuli/lineage_os_181_moto_g7_power_ocean_issues/
https://www.reddit.com/r/LineageOS/comments/mmxvm7/colors_glitched_wrong_looks_like_negatives_on/

**Comment by npjohnson** [comment]
Yeah, this isn't magisk's fault at all, custom ROM bug.
