### ISSUE TITLE
samsung tab s6 lite

### ISSUE THREAD

**Issue by bardiarajabi** [topjohnwu/Magisk#4517]
Device: Samsung tab s6 lite
Android version: 11
Magisk version name: v23
Magisk version code: 23001
Downloaded stock device files.
Android 11 region UK.
Binaries are match (4)
The tablet shows An error has occured while updating the device software.
The Error Description:"While writing cache to tablet via odin tablet says":Only official binaries are allowed(vbmeta)
And Odin shows failed!

**Comment by osm0sis** [comment]
Duplicate of #4395?

**Comment by bardiarajabi** [comment]
Discovered the problem.
It was Knox guard causing the problem.
