### ISSUE TITLE
safetynet check fail

### ISSUE THREAD

**Issue by pw44** [topjohnwu/Magisk#4522]
hi, i'm using lineageos 18.1 on a sagit.

checking  safetynet before rooting shows ok, after rooting with magisk 23.0, safetynet check fails.

any clue? 

thx in advance.

**Comment by Didgeridoohan** [comment]
Did you turn on MagiskHide?
Make sure that the ROM uses a certified device fingerprint?

Those two should suffice, since the device is old enough to not have hardware backed key attestation.

**Comment by pw44** [comment]
yes, magisk is turned on.

as far i know, lineageos 18.1 users certified device fingerprint.

by checking safetynet before installing magisk, return ok, safetynet 
check passed. after magisk 23.0 install, sfatynet check fails.

Am 27.07.21 um 08:46 schrieb Didgeridoohan:

**Comment by Didgeridoohan** [comment]
MagiskHide turned on, not Magisk... MagiskHide needs to be enabled manually on a new install. Check the settings for the "MagiskHide" toggle.

**Comment by pw44** [comment]
Thx! that did it. enabling magisk hide, made it work.



Am 27.07.21 um 15:21 schrieb Didgeridoohan:
