### ISSUE TITLE
Issues with LSPosed

### ISSUE THREAD

**Issue by huztek** [topjohnwu/Magisk#4534]
Device: Xiaomi Mi 10 Ultra (CAS) / Xiaomi M2007J1SC
Android version: 11
Magisk version name: f8ca225b
Magisk version code: 23001

I keep getting this error in LSPosed "SEPolicy is not loaded properly, modules that hook System Framework will not work." 

I'm told to report this issue here.

More details are given below about my device;

API version:
93

Framework version:
v1.4.7 (5803)

Manager version:
v1.4.7 (5803)

System version:
11 (API 30)

Device:
Xiaomi M2007J1SC 

System ABI:
arm64-v8a

**Comment by osm0sis** [comment]
https://github.com/topjohnwu/Magisk/issues/4488#issuecomment-880167644

**Comment by wolfsstolz** [comment]
Same problem here with a Xiaomi Redmi Note 9 Pro. I come from Germany and my English is not the best

**Comment by wolfsstolz** [comment]
> Device: Xiaomi Mi 10 Ultra (CAS) / Xiaomi M2007J1SC
> Android version: 11
> Magisk version name: f8ca225b
> Magisk version code: 23001
> 
> I keep getting this error in LSPosed "SEPolicy is not loaded properly, modules that hook System Framework will not work."
> 
> I'm told to report this issue here.
> 
> More details are given below about my device;
> 
> API version:
> 93
> 
> Framework version:
> v1.4.7 (5803)
> 
> Manager version:
> v1.4.7 (5803)
> 
> System version:
> 11 (API 30)
> 
> Device:
> Xiaomi M2007J1SC
> 
> System ABI:
> arm64-v8a

OK, open Magisk Manager and go to:
First Page, in below , you go under magisk and now click on install , then direct Install.
Now you must make a reboot only and all will be good.

**Comment by alidavoodi2680** [comment]
Let's set up a meeting to discuss this.


Sent from Nine
________________________________
