### ISSUE TITLE
[Feature request] : Bank app is detecting rooted phone despite Magisk

### ISSUE THREAD

**Issue by Latruffy** [topjohnwu/Magisk#4535]
Hello,
I own a Samsung A5 (2016) running LineageOS.
Since several versions of Magisk (presently I'm running v23), my bank app detects that my phone is rooted, and then refuses to work, despite I added this app to MagiskHide list.
Could you please have a look, and try to solve this issue ?

Test case : 
- app : Monabanq from the Play Store
- select the upper button "JE SUIS DEJA CLIENT" (in french)
- get then a red box "Informations sécurité
Pour des raisons de sécurité, l'application ne supporte plus les appareils rootés. Pour continuer d'utiliser l'application, enlevez le root si vous l'avez mis en place vous-même ou contactez votre revendeur pour réinitialiser le téléphone."

And I can't access the next screen requesting credentials to logon.

Thanks by advance.
Best regards

**Comment by Jon8RFC** [comment]
Works for me.  Try this example video and the steps in the video description:
https://www.youtube.com/watch?v=UaWh9BOdMdI

**Comment by Latruffy** [comment]
Thanks for trying to help me.
I perform the same steps (+ Magisk app hiden), but my bank app still detects root.
BTW, installing the safety-fix mod caused my phone to bootloop, so that I had to uninstall it from TWRP terminal.
It seems it doesn't apply to my phone model CPU or perhaps OS (Samsung A5 2016 running LineageOS 17.1).

**Comment by Latruffy** [comment]
I solved the issue, after having seen that my bank app was installed on my SD card formated to be used as adoptable storage.
After moving it to the internal storage, the app now succeeds in running (but I had to add it the the Magisk hidelist, and to hide the Magisk app).
Issue solved.
May it help or give some ideas to someone.
