### ISSUE TITLE
Redmi Note 8 Pro Magisk Patch Problem.

### ISSUE THREAD

**Issue by Casper-88** [topjohnwu/Magisk#4539]
Dear Mr/Miss,
Redmi Note 8 Pro Bootloop Problem solve

First Disable Android Verified Boot (AVB). 
vbmeta.img Extract from official rom you use.
Use last version adb https://androidmtk.com/download-15-seconds-adb-installer disable AVB
Old version adb 1.4.3 cannot disable, want use last version 15_Second_ADB_Installer_v1.5.6.zip.
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img

Then use PC fastboot flash boot magisk_patched.img can normal login phone.
Please let people know First Disable Android Verified Boot (AVB) before fastboot flash boot magisk_patched.img.

---------------------------------------------------------------------------------------------------

Now new problem Magisk cannot hidden root from MacDonald app.
Your device did not pass our security check. Please check that you run a Google trusted OS version, 
that the device is not rooted and you have no harmful apps installed.

Device: Redmi Note 8 Pro
Android version: Android 11
Magisk version name: Magisk Manager 23.0
Magisk version code: 23001

**Comment by osm0sis** [comment]
```

Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers

Supplied image: boot.img

Removing old work folders and files...

Setting up work folders...

Image type: AOSP

Splitting image to "split_img/"...
ANDROID! magic found at: 0
BOARD_KERNEL_CMDLINE bootopt=64S3,32N2,64N2 buildvariant=user
BOARD_KERNEL_BASE 0x40078000
BOARD_NAME 
BOARD_PAGE_SIZE 2048
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x07c08000
BOARD_SECOND_OFFSET 0xbff88000
BOARD_TAGS_OFFSET 0x0bc08000
BOARD_OS_VERSION 11.0.0
BOARD_OS_PATCH_LEVEL 2021-07
BOARD_HEADER_VERSION 2
BOARD_HEADER_SIZE 1660
BOARD_DTB_SIZE 165278
BOARD_DTB_OFFSET 0x0bc08000

Unpacking ramdisk to "ramdisk/"...

Compression used: gzip
3427 blocks

Done!
```

2SI ramdisk with fstab.mt6785 and fstab.emmc

**Comment by Casper-88** [comment]
> 
> 
> ```
> 
> Android Image Kitchen - UnpackImg Script
> by osm0sis @ xda-developers
> 
> Supplied image: boot.img
> 
> Removing old work folders and files...
> 
> Setting up work folders...
> 
> Image type: AOSP
> 
> Splitting image to "split_img/"...
> ANDROID! magic found at: 0
> BOARD_KERNEL_CMDLINE bootopt=64S3,32N2,64N2 buildvariant=user
> BOARD_KERNEL_BASE 0x40078000
> BOARD_NAME 
> BOARD_PAGE_SIZE 2048
> BOARD_HASH_TYPE sha1
> BOARD_KERNEL_OFFSET 0x00008000
> BOARD_RAMDISK_OFFSET 0x07c08000
> BOARD_SECOND_OFFSET 0xbff88000
> BOARD_TAGS_OFFSET 0x0bc08000
> BOARD_OS_VERSION 11.0.0
> BOARD_OS_PATCH_LEVEL 2021-07
> BOARD_HEADER_VERSION 2
> BOARD_HEADER_SIZE 1660
> BOARD_DTB_SIZE 165278
> BOARD_DTB_OFFSET 0x0bc08000
> 
> Unpacking ramdisk to "ramdisk/"...
> 
> Compression used: gzip
> 3427 blocks
> 
> Done!
> ```
> 
> 2SI ramdisk with fstab.mt6785 and fstab.emmc

Can you help me eddit fix problem then upload boot.img let me download?

**Comment by osm0sis** [comment]
I'm adding more information so someone who understands the fstab parsing more can hopefully look into fixing it for you later

**Comment by Casper-88** [comment]
> 
> 
> I've only added more information so someone who understands the fstab parsing more can hopefully look into fixing it for you later.
Thank you fixing it later.
After fixing hope you can upload boot.img let many people can use pc flash and use Magisk.

**Comment by Casper-88** [comment]
> 
> 
> I've only added more information so someone who understands the fstab parsing more can hopefully look into fixing it for you later.

Thank you fixing it later.
After fixing hope you can upload boot.img let many people can use pc flash and use Magisk.

**Comment by CNLM** [comment]
disable verification/verity on vbmeta

**Comment by Casper-88** [comment]
> 
> 
> disable verification/verity on vbmeta

How to disable verification/verity on vbmeta?
Can you edit boot.img then upload to me?

**Comment by osm0sis** [comment]
It's not a boot.img thing, it's a fastboot command, Google it please.

**Comment by Casper-88** [comment]
> 
> 
> It's not a editable boot.img thing, it's a fastboot command, Google it please. Hopefully will work for you.

Some people say want patch-vbmeta.img. Do you know to do it?

**Comment by Casper-88** [comment]
> 
> 
> disable verification/verity on vbmeta

Thank give me know. Now no problem bootloop.

**Comment by osm0sis** [comment]
MagiskHide thread on xda to see if anyone knows how to get it working.

**Comment by Casper-88** [comment]
> 
> 
> MagiskHide thread on xda to see if anyone knows how to get it working.

You try install McDonald's see MagiskHide still can let McDonald' app detect root in MIUI 12.5.
https://play.google.com/store/apps/details?id=com.mcdonalds.mobileapp&hl=en
