### ISSUE TITLE
No  file included on magisk release. only apk & jar

### ISSUE THREAD

**Issue by pojavluncher2021** [topjohnwu/Magisk#4540]
You forgot to include a tar or raw image file. Without that how will I install magisk.

Also magisk root granter crashes

Device:  Redmi 9C
Android version: 10.QP1A
Magisk version name: 23.0
Magisk version code: ?

**Comment by Didgeridoohan** [comment]
The installation instructions are available in the docs here on GitHub. You're supposed to provide the image file yourself...
