### ISSUE TITLE
[Feature request] Change misleading text of flash notification when tapjacking protection is disabled

### ISSUE THREAD

**Issue by bege10** [topjohnwu/Magisk#4543]
Device: Fairphone 3
Android version: 10
Magisk version name: f822ca5b, German locale
Magisk version code: 23001

When tapjacking protection is disabled the flash notification that shows up when granting root permission shows the same text (root permission _not_ granted) as when the protection is enabled - at least. This text is misleading because root permission _is_ granted.
Can you, please, change the text to a warning that root permission has been granted in a suspicious situation?

**Comment by techIndia-hacker** [comment]
Yes with tapjacking protection disabled, buggy toast is still displayed that overlay...

**Comment by vvb2060** [comment]
> Because an app is obscuring a superuser request, Magisk can’t verify your response

This does not mean that root permission is granted, it is just a generic warning that the request could not be verified.

**Comment by bege10** [comment]
> > Because an app is obscuring a superuser request, Magisk can’t verify your response
> 
> This does not mean that root permission is granted, it is just a generic warning that the request could not be verified.

When tapjacking protection is _disabled_ in Magisk options, root permission _is_ granted although the toast says the request could not be verified. The toast remains the same no matter whether tapjacking protection is enabled or disabled. The text should change with the status of this option.

**Comment by vvb2060** [comment]
Why, that's what the button does. When the pop-up disappears, it means the button is pressed.

**Comment by bege10** [comment]
> Why, that's what the button does. When the pop-up disappears, it means the button is pressed.

That's what I see after I checked Magisk. The toast makes me think something went wrong.
In a previous issue topjohnwu commented that the toast shall remain with tapjacking protection disabled to show that root permission is requested in a suspicious situation. The toast neither tells that nor that permission is granted. It says the request could not be verified. If root permission is nevertheless granted, that information is wrong: the request has been verified and granted.
What is the problem with changing the text of the toast to an accurate information?

**Comment by bege10** [comment]
> I think you are confusing the function of the different toasts, this toast only indicates that Magisk is unable to verify the request

Magisk _does_ verify and grant the request. The toast is misleading.

> A later toast will indicate if root permission is allowed:
> 
Not here

https://user-images.githubusercontent.com/1184237/132238822-ed981113-fd90-47b5-8eec-4f3bbe5a0411.mp4

**Comment by vvb2060** [comment]
Can't reproduce

https://user-images.githubusercontent.com/26996262/170830532-79dfb426-ab39-4fde-8af6-b82cb4007d0c.mp4

**Comment by bege10** [comment]
The German text says: "Because an app covers the superuser request Magisk cannot verify your answer."
This text is the same whether tap-jacking protection is on or off. On my phone it is off and therefore the text is misleading because Magisk _does verify_ the answer and _grants superuser access_.
There should be different texts for tap-jacking protection on and off.

**Comment by vvb2060** [comment]
Magisk accepted the response, but was unable to verify if this was from the user's true intent. 
If you are not satisfied with the translation, you can open PR to change it

**Comment by pndwal** [comment]
Seems issue is not the first toast (failure to verify is still correct) as stated, but that the next toast (regarding root grant) is not showing with users system/configuration...
