### ISSUE TITLE
Losing Root after reboot 

### ISSUE THREAD

**Issue by AzCreep** [topjohnwu/Magisk#4545]
Device: Xiaomi Redmi Note 9S
Android version: 11 MIUI 12.0.4
Magisk version name: f822ca5b
Magisk version code: 23001

So...yeah the tittle is pretty much self explanatory i have tried a lot of stuff....this is the 4th time i root my phone everything goes smooth all rooted and stuff but i noticed 2 strange things while rooting

So i root threw Minimal ADB and Fastboot directly to phone and i noticed for the first time like i dont have to type as my second step fastboot reboot cause it auto reboots himself and im like...ok 
and the second thing is everything is bypassing exept one bank app (cause there is always that black sheep of the group) and when i was trying to fix that everytime i reboot my phone it loses root access.

I search online found some people who had same problem and i tried their solutions for example changing update channel to beta still didn't work 
Removing the Magisk hide (which i desperatly need it) and still didn't work 
I'm running out of ideas here so i would love if someone knows what's going on 

P.S: My phone forced to updated so that's why i'm having this trouble and second sorry for my grammar sometimes it's not my first language

**Comment by Casper-88** [comment]
First Disable Android Verified Boot (AVB).
vbmeta.img Extract from official rom you use.
Use last version adb https://androidmtk.com/download-15-seconds-adb-installer disable AVB
Old version adb 1.4.3 cannot disable, want use last version 15_Second_ADB_Installer_v1.5.6.zip.
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img

**Comment by AzCreep** [comment]
oh thank you it's working now! thanks for the help!
