### ISSUE TITLE
MagiskHide Cannot use McDonald's App.

### ISSUE THREAD

**Issue by Casper-88** [topjohnwu/Magisk#4546]
Dear Miss/Miss,
https://play.google.com/store/apps/details?id=com.mcdonalds.mobileapp
Redmi Note 8 Pro Miui 12.5 problem Magisk cannot hidden root from MacDonald app.
https://bigota.d.miui.com/V12.5.2.0.RGGIDXM/begonia_id_global_images_V12.5.2.0.RGGIDXM_20210718.0000.00_11.0_global_9676464a79.tgz
Your device did not pass our security check. Please check that you run a Google trusted OS version,
that the device is not rooted and you have no harmful apps installed.

Device: Redmi Note 8 Pro
Android version: 11
Magisk version name: candy
Magisk version code: 23001

**Comment by osm0sis** [comment]
#1152
