### ISSUE TITLE
Unable to install using TWRP recovery

### ISSUE THREAD

**Issue by DavisNT** [topjohnwu/Magisk#4547]
Latest TWRP recovery (v3.5.2) has unzip command that doesn't support glob wildcards. Magisk 23 cannot be installed from TWRP recovery 3.5.2 (using [Custom Recovery](https://topjohnwu.github.io/Magisk/install.html#custom-recovery) method), because first commands in `update-binary` use glob wildcard in built-in unzip command.

Recovery: TWRP 3.5.2
Magisk version name: ~~v23.0~~ 1eb83ad8
Magisk version code: 23001

There are two proposed fixes (any one of them fixes this issue): 
1. https://github.com/topjohnwu/Magisk/pull/4384/commits/fb4eb7249b648d69bff7e0a969feca25b3141ac1 from https://github.com/topjohnwu/Magisk/pull/4384
2. https://github.com/topjohnwu/Magisk/pull/4544

~~This issue seems to be a part of https://github.com/topjohnwu/Magisk/issues/4394~~

**Comment by osm0sis** [comment]
... I sideloaded the Magisk APK to TWRP on my OP9Pro like 2 days ago without issue.

**Comment by DavisNT** [comment]
Busybox unzip will AFAIK always work, however Android libziparchive unzip (as @vvb2060 mentioned in his commit description) will work only on Android 11.0 and newer based TWRP. 
Here is libziparchive code for Android 10 (no glob support): https://android.googlesource.com/platform/system/core/+/refs/tags/android-10.0.0_r47/libziparchive/unzip.cpp#57
And here is libziparchive for Android 11 (glob support via `fnmatch(3)`): https://android.googlesource.com/platform/system/core/+/refs/tags/android-11.0.0_r40/libziparchive/ziptool.cpp#95

Unofficial lemonadep TWRP ( https://github.com/nebrassy/device_oneplus_lemonadep-TWRP ) is based on Android 11 that has glob wildcard support in libziparchive unzip.
I had the problem on dipper (Android 9.0 based TWRP) that uses libziparchive unzip without glob wildcard support.

**Comment by osm0sis** [comment]
Right, but TWRP only recently switched to libziparchive, before that they used Lineage's unzip which also supported glob.

**Comment by DavisNT** [comment]
Sorry! 
The glob is only in [master branch](https://github.com/topjohnwu/Magisk/blob/master/scripts/update_binary.sh), but **not** in [v23.0 tag](https://github.com/topjohnwu/Magisk/blob/v23.0/scripts/update_binary.sh) (I had built Magisk from source). That explains why others are not experiencing this problem. 
If #4384 (or at least [fb4eb72](https://github.com/topjohnwu/Magisk/pull/4384/commits/fb4eb7249b648d69bff7e0a969feca25b3141ac1) from it) will get merged before next release, then nobody using the official releases should have this problem.

**Comment by Midottt** [comment]
> Latest TWRP recovery (v3.5.2) has unzip command that doesn't support glob wildcards. Magisk 23 cannot be installed from TWRP recovery 3.5.2 (using [Custom Recovery](https://topjohnwu.github.io/Magisk/install.html#custom-recovery) method), because first commands in `update-binary` use glob wildcard in built-in unzip command.
> 
> Recovery: TWRP 3.5.2
> Magisk version name: ~~v23.0~~ 1eb83ad8
> Magisk version code: 23001
> 
> There are two proposed fixes (any one of them fixes this issue): 
> 1. https://github.com/topjohnwu/Magisk/pull/4384/commits/fb4eb7249b648d69bff7e0a969feca25b3141ac1 from https://github.com/topjohnwu/Magisk/pull/4384
> 2. https://github.com/topjohnwu/Magisk/pull/4544
> 
> ~~This issue seems to be a part of https://github.com/topjohnwu/Magisk/issues/4394~~

-
