### ISSUE TITLE
在Pixel 2 XL上的Android P正式版刷入Magisk16.7之后卡在启动界面

### ISSUE THREAD

**Issue by zeewinpeng** [topjohnwu/Magisk#455]
机器： Pixel 2 XL
android版本： Android P正式版（实际上之前在Android P Beta3上也有这个问题）
Magisk版本： 16.7

刷入zip包之后， 启动系统， 会卡在google logo那里，启动动画一直播放，但是不会进入系统桌面。

这个时候adb shell已经能够使用了， su也能正常使用， 但是就是手机进不了桌面。

**Comment by wanzaimian** [comment]
用twrp进文件管理 删掉 /data/adb/magisk.img和magisk.db这两个文件

**Comment by lijun0326** [comment]
#406 看起来这个bug从DP3就有了啊（还好DP2就回滚到O了

**Comment by topjohnwu** [comment]
Fixed in 59f78d7dfce51d3f61351bb60ceb2dfd727c0daa

**Comment by JiangLi23** [comment]
我也遇到了同样的问题，应该是Magisk的版本太低了，我用的最新版本解决问题。
