### ISSUE TITLE
SEPolicy is not loaded properly

### ISSUE THREAD

**Issue by OgnistyPoland** [topjohnwu/Magisk#4555]
Device: Xiaomi Mi 9T Pro
Android version: 11
Magisk version name: f8ca225b
Magisk version code: 23001

![129617128-0d656fce-edaf-4fd5-bad2-fb68b8bd8456](https://user-images.githubusercontent.com/32206254/129617741-ca11c619-c22f-4394-b913-7b00847696ea.jpg)
![129617117-c1128641-b443-4c74-8d35-b6340fc8c424](https://user-images.githubusercontent.com/32206254/129617745-40f3da11-6372-42ba-9204-f9d53b119a81.jpg)

Hello, I tried to install Riru and Lsposed, but it's not working as it should. I thought it was fixed in 23.0 update?

[magisk_log_2021-08-16T21_13_01Z.log](https://github.com/topjohnwu/Magisk/files/6994845/magisk_log_2021-08-16T21_13_01Z.log)

**Comment by osm0sis** [comment]
https://github.com/topjohnwu/Magisk/issues/4488#issuecomment-880167644

**Comment by OgnistyPoland** [comment]
> [#4488 (comment)](https://github.com/topjohnwu/Magisk/issues/4488#issuecomment-880167644)

But I dont have any modules
