### ISSUE TITLE
MagiskHide failed after several hours of screen-off time

### ISSUE THREAD

**Issue by ahxxm** [topjohnwu/Magisk#457]
It can't be reproduced reliably yet, but there's high chance(>40%) that after several(>=2) hours of screen off, MagiskHide will stop working: the process `magiskd` is in ps result, root works as well, only Safetynet is down. I'll have to reboot to make it work again.

I've been experiencing this issue since upgrade my Oneplus3 from LineageOS 14(Android 7) + Magisk 16.0 to LineageOS 15(Android 8) + Magisk master commit since 16.0. Release versions and [custom built](https://github.com/ahxxm/Magisk/tree/ci) ones that keep up with master commits are all used, none of them helps.

**Comment by DenyDarko** [comment]
LineageOS 15 is not officially released as stable for 3(T). I only see nightlies on their download section. 
 
It's probably a bug within the ROM.

Furthermore, bug reports without logs are useless:

https://www.didgeridoohan.com/magisk/MagiskHideHelp

**Comment by ahxxm** [comment]
You're right, what kind of log can I provide to locate the bug?

Custom built Magisk is debug version using my release key, I'll upload adb and Magisk log once bug reproduced. What else could be helpful?

**Comment by ahxxm** [comment]
[magisk_log_20180809_075629.log](https://github.com/topjohnwu/Magisk/files/2272439/magisk_log_20180809_075629.log)
[logcat.txt](https://github.com/topjohnwu/Magisk/files/2272441/logcat.txt)

I've been playing game from 7:44 to 7:55, immediately after game stops working(around `08-09 07:55:31.327` as shown in logcat.txt), I opened MagiskManager to verify Safetynet status and result confirmed Magiskhide loss.

@DenyDarko any thoughts?

**Comment by topjohnwu** [comment]
@ahxxm for some reason the log monitor missed the SafetyNet process
`08-09 07:45:00.379   929  1732 I ActivityManager: Start proc 21564:com.google.android.gms.unstable/u0a68 for service com.google.android.gms/.droidguard.DroidGuardService`
Does not follow with a MagiskHide notice
I'll check what I can do to optimize MagiskHide

**Comment by ahxxm** [comment]
lowmemorykiller is killing process `com.google.android.gms.unstable` frequently, is that relevant?

btw I've consulted lineage developer about this, the model [does not](https://github.com/LineageOS/android_kernel_oneplus_msm8996/blob/lineage-15.1/arch/arm64/configs/lineageos_oneplus3_defconfig) have `CONFIG_MEMCG_SWAP` enabled, which incorrectly triggers `find_and_kill_process` [branch](https://github.com/LineageOS/android_system_core/blob/lineage-15.1/lmkd/lmkd.c#L690). the issue might be fixed in near future..

**Comment by ahxxm** [comment]
just upgraded to latest LineageOS build, and (dirty) [fixed](https://github.com/ahxxm/Magisk/commit/10f23c41e3c899d81d1e9ec54620fbb5b85150de) Safetynet call. `com.google.android.gms.unstable` has not been killed yet, magiskhide works as well

**Comment by ahxxm** [comment]
but seems network change can invalidate magiskhide temporarily: when I switched to 4g from wifi(my 4g can't access Google) safetynet validation fails occasionally, but once proxy is up it works again...

**Comment by topjohnwu** [comment]
Continue in #585
