### ISSUE TITLE
Magisk hide not working on Axis Mobile v7.1 apk

### ISSUE THREAD

**Issue by amol-17** [topjohnwu/Magisk#4570]
Device: POCO F1 MIUI 12.0.0.2
Android version: Android ver 10
Magisk version name: 23.0
Magisk version code: 23001

The latest version of Axis Mobile app (7.1) is able to detect whether the phone is rooted.
### Things I have done: 
- Used magisk hide and enabled it on google play services as well as Axis App
- Hide magisk app using different name.

After going through the logs, this is a new setting which I found while using magisk hide. This was not present in previous version of Axis Mobile app (<7.0) 

**[isolated/com.axis.mobile:com.lookout.rootdetectioncore.internal.processdetection.IsolatedProcessRootDetectionService]**

Hope to fix this asap

**Comment by charles17b** [comment]
Hi

**Comment by Didgeridoohan** [comment]
From that I can see it's simply detecting the Magisk app. That is possible even with the Magisk app repackaged with a random name...

You can either uninstall the Magisk app or use an app that can freeze/disable the Magisk app whenever you need to use the Axis app, and then reinstall/unfreeze/enable the Magisk app again afterwards.

It's a known thing and not much can be done about it until Google forces apps in the Play Store to target API 30.

**Comment by osm0sis** [comment]
#1152
