### ISSUE TITLE
[enhancement request] add prompt to downgrade modules

### ISSUE THREAD

**Issue by token0** [topjohnwu/Magisk#4575]
If user installing a lower version of already installed module, ask user to **downgrade or uninstall**, instead of just blunt uninstall. Please add this feature. Thanks.

Device: irrelevant
Android version: irrelevant
Magisk version name: 23
Magisk version code: 23001

**Comment by Didgeridoohan** [comment]
That's not a feature of the default module installation script. Sounds like you need to talk to whomever made the module you're using...

**Comment by token0** [comment]
So, that is a module feature! Thanks for clarification!
