### ISSUE TITLE
Pixel 2 keeps restarting with new Android 9

### ISSUE THREAD

**Issue by KptCheeseWhiz** [topjohnwu/Magisk#458]
My phone keeps rebooting when using patched_boot.img as boot image.
I am using Magisk v16.7 on beta channel (stable channel doesn't work because it fails at extracting files)

Here's the logs (seems like Google UI is crashing)
[logcat_with_patched_boot.log](https://github.com/topjohnwu/Magisk/files/2267841/logcat_with_patched_boot.log)
[logcat_with_stock_boot.log](https://github.com/topjohnwu/Magisk/files/2267842/logcat_with_stock_boot.log)

Thank you

**Comment by topjohnwu** [comment]
Try remove all your module (remove `/data/adb/magisk.img`) via TWRP or ADB shell
There are other issues regarding Pixel 2 (XL), but your report just looks like modules causing the issues

**Comment by zhujunsan** [comment]
same issue here and it got solved.
may be something to do with the old `Active Edge Mod for Pixel 2 and Pixel 2 XL` mod, not so sure.
