### ISSUE TITLE
Donations improvement

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#459]
Hey John,

This is not a Magisk issue but an idea regarding donations. 

Recently I've noticed that I give around 15-20% of my donation to you for PayPal fees which is terrible. 
PayPal has already enough money, they don't need my donation.

You may thing enabling the "donation button" 
which lowers the fees a lot.
When you have some free time check if you're eligible for that :)

https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/donate_step_1/#

**Comment by topjohnwu** [comment]
My old PayPal account is Taiwanese account, which does not support donations LOL.
I'm moving to US soon, I'll update my donation options soon!
