### ISSUE TITLE
Magisk is not giving root permissions

### ISSUE THREAD

**Issue by Pikachuvitoria** [topjohnwu/Magisk#460]
08-08 10:08:52.611   319   319 I Magisk  : ** Initializing Magisk
08-08 10:08:52.613   319   319 I Magisk  : * Creating /sbin overlay
08-08 10:08:52.619   319   319 I Magisk  : * Mounting mirrors
08-08 10:08:52.620   319   319 I Magisk  : mount: /sbin/.core/mirror/system
08-08 10:08:52.620   319   319 I Magisk  : link: /sbin/.core/mirror/vendor
08-08 10:08:52.621   319   319 I Magisk  : bind_mount: /sbin/.core/mirror/bin
08-08 10:08:52.621   319   319 I Magisk  : * Setting up internal busybox
08-08 10:08:52.976   326   326 I Magisk  : Magisk v16.7(1671) logger started
08-08 10:08:52.979   322   322 I Magisk  : Magisk v16.7(1671) daemon started
08-08 10:08:52.987   322   328 I Magisk  : ** post-fs-data mode running
08-08 10:08:52.989   322   328 I Magisk  : Create /data/adb/magisk.img with size 64M
08-08 10:08:53.199   322   328 I Magisk  : * Mounting /data/adb/magisk.img
08-08 10:08:53.776   322   328 I Magisk  : * Running post-fs-data.d scripts
08-08 10:08:53.776   322   328 I Magisk  : * Running module post-fs-data scripts
08-08 10:08:53.776   322   328 I Magisk  : * Loading modules
08-08 10:08:53.782   322   345 I Magisk  : * Starting MagiskHide
08-08 10:08:53.782   322   345 I Magisk  : hide_utils: Hiding sensitive props
08-08 10:08:53.783   322   345 I Magisk  : hide_list add: [com.google.android.gms.unstable]
08-08 10:08:55.526   322   479 I Magisk  : ** late_start service mode running
08-08 10:08:55.527   322   479 I Magisk  : * Running service.d scripts
08-08 10:08:55.527   322   479 I Magisk  : * Running module service scripts
08-08 10:10:01.680   322   345 I Magisk  : proc_monitor: com.google.android.gms.unstable
08-08 10:11:32.940  3215  3215 E Magisk  : select failed with 2: No such file or directory

Only that "error message on the last line

**Comment by shoeper** [comment]
I had the same issue, recently. Also with "select failed with 2: No such file or directory"

**Comment by shoeper** [comment]
It is similar for me. Also recently the hosts file stopped working sometimes. Other times it works without issues.

**Comment by gabes100** [comment]
So far have not had issues on 17.1, I did however disable magiskHide when I had 16.7 and it seemed to fix my issue

**Comment by shoeper** [comment]
I obviously do not have a long time experience but it looks like 17.1 also fixed the issues for me. It also looks like my hosts adblock list is working reliable again which wasn't the case with 16.x.

So, I think this can be closed.

**Comment by topjohnwu** [comment]
The new communication model is different now, please report again if the issue still exists in Canary channel

**Comment by rocketpencil** [comment]
#593 retry

"17.2-906b4aad" does not solve the problem.

errorlog output
select failed with 9: Bad file descriptor

[magisk_log_20180917_121446.log](https://github.com/topjohnwu/Magisk/files/2387315/magisk_log_20180917_121446.log)
