### ISSUE TITLE
Bootloop when upgrading ROM with decrypted data

### ISSUE THREAD

**Issue by Megver83** [topjohnwu/Magisk#4614]
Device: Redmi Note 8 (ginkgo)
Android version: LineageOS 17.1
Magisk version name: f822ca5
Magisk version code: 23000

I used to have official LOS 17.1 with encrypted data and Magisk. Everything was fine, upgrades didn't brake anything.
Later, I formatted data, flashed DFE and changed to a decrypted installation on the same ROM ([here's why](https://forum.xda-developers.com/t/solved-twrp-of-bootloop-after-restoring-data-partition.4319761/) if it helps). Magisk works fine too, but when upgrading the LOS release (manually or through the updater) I get a bootloop.

One way to upgrade the ROM without ending in a bootloop, is to uninstall Magisk, flash the ROM and reinstall Magisk again ([here's a more detailed explanation](https://forum.xda-developers.com/t/solved-twrp-of-bootloop-after-restoring-data-partition.4319761/#post-85556745) of how to do this). Looks like it may be a survival addon issue? Also, another way to avoid bootloop is to upgrade the ROM and wipe data. I discovered that when removing the /data/adb and /data/adbroot directories, I can successfully boot, too, but I've to reinstall Magisk.

[dmesg-bootloop.txt](https://github.com/topjohnwu/Magisk/files/7078602/dmesg-bootloop.txt)

**Comment by osm0sis** [comment]
Orrrrr something to do with DFE

**Comment by Megver83** [comment]
Would it be possible for magisk to be in charge of this? e.g. with an option to flash DFE (or whatever) before re-rooting. Or directly have something like "keep data decrypted" in the manager.

I'd like to test a survival addon for DFE, since I know shell scripting I'd just have to learn how this addon scripts work and then create one, unless this is a really simple job so that maybe you could send me a simple script to test.

**Comment by osm0sis** [comment]
Honestly that's above-and-beyond that OF does that.. and it should be something DFE provides to ensure it sticks through OTAs. 🤷‍♂️

And nah, they're shell scripts. The twrp_ab could still be a good reference since your DFE script will need to run after addon.d but before Magisk, but you'll also want to look at a regular addon.d script too. There are a few simple ones in my thread you can check out for reference.
