### ISSUE TITLE
Magisk is unable to hide root and fails saftey net on Android Oreo

### ISSUE THREAD

**Issue by anaganisk** [topjohnwu/Magisk#463]
When use verify saftey net status, I get an error saying. Due to some changes in play store, its not possible to check Saftey net on repackaged magisk manager. And Google Tez, is able to detect that the phone has been rooted despite hiding it from the app.

**Comment by topjohnwu** [comment]
Repackaged Magisk Manager is not possible to check SN, just as the error message says. You can use other external programs to do the testing.
I'll check Tez if I got the time
