### ISSUE TITLE
Magisk canary / Safetynet failed on mi 8 dipper since today

### ISSUE THREAD

**Issue by Catfriend1** [topjohnwu/Magisk#4630]
Device: xiaomi mi 8 dipper running pixel experience 11 plus
Android version: 11
Magisk version name:  canary 
Magisk version code: 
f822ca5b

**Comment by Catfriend1** [comment]
hey it shows 23001 and the commit..I have this!

the problem also cannot be solved by installing kdrag0n's v1.2 fix ( https://github.com/kdrag0n/safetynet-fix/issues/78 )

**Comment by ghost** [comment]
please delete issue
