### ISSUE TITLE
Magisk canary / Safetynet failed on mi 8 dipper since today

### ISSUE THREAD

**Issue by Catfriend1** [topjohnwu/Magisk#4631]
Device: xiaomi mi 8 dipper running pixel experience 11 plus
Android version: 11
Magisk version name: canary
Magisk version code: 23001

I cannot pass the cts profile.

f822ca5

**Comment by Catfriend1** [comment]
hey it shows 23001 and the commit..I have this!

the problem also cannot be solved by installing kdrag0n's v1.2 fix ( kdrag0n/safetynet-fix#78 )

**Comment by Catfriend1** [comment]
ref https://github.com/topjohnwu/Magisk/issues/4630

**Comment by Didgeridoohan** [comment]
That's not a Magisk issue. Google is tinkering on their end... Several ways of circumventing already if you take a look around XDA.

Of course, it's just a matter of time before they cut us modders out of SN for good...

**Comment by Catfriend1** [comment]
Workaround : https://github.com/kdrag0n/safetynet-fix/issues/78#issuecomment-912054082

**Comment by Catfriend1** [comment]
Workaround : https://www.youtube.com/watch?v=I9A3yxAi-Ww

**Comment by ghost** [comment]
please delete issue
