### ISSUE TITLE
[MagiskHide] KNOX Samsung not working

### ISSUE THREAD

**Issue by Ashwin-droid** [topjohnwu/Magisk#4635]
Device: SM-G615F
Android version: 8.1.0
Magisk version name: 23001.
Magisk version code: 23001.

As said in the title knox is not working as say for secure folder, samsung pay mini (dont use), Shealth but dev check info says that my warranty is valid (not in reality as i have twrp) any hackey workaround?

**Comment by osm0sis** [comment]
#1152

See here though for the recent SafetyNet change which might affect your Knox detection too: https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/page-2379#post-85578621
