### ISSUE TITLE
Bootloop after installing the patched boot image on Android 11 on Sony Xperia 1

### ISSUE THREAD

**Issue by staynam** [topjohnwu/Magisk#4638]
I'm with Xperia 1 dual J9110_Customized CN_55.2.A.4.154-R12C.
According to #3752 I tried to

1. unsin bluetooth_X-FLASH-ALL-A2CD.sin,
2. magisk patch boot.img
3. unpacked the pacthed boot.img with AIK
But I cannot locate the correct fstab file(s) in my unpacked boot.img folder.
All I can find is recovery.fstab which is definitely not the correct one. It doesnt't help either if I do sequence as 1,3&2.

Could anyone plz help me to removed system_ext from the boot.img?
Thanks so much.
https://drive.google.com/file/d/1XGC7cGGAmj8AIfuRoa6BlK9u6lLjECuY/view?usp=sharing

Device: sony xperia 1
Android version: Android11 55.2.A.4.154-R12C
Magisk version name: v23.0
Magisk version code: 23001

**Comment by username-is-not** [comment]
Unlucky, there's no offical TWRP build for it... otherwise Magisk is installed via custom recovery. 

`https://twrp.me/Devices/Sony/`

... Strange, it's not such an old device and the SoC is superb; although the 855+ had been the right way (the correct choice, think Sony had eliminated themselves with this series). 

Anyway, never mind all that... can this help, link to binaries is there - and whatever else:

`https://developer.sony.com/posts/xperia-1-added-to-sonys-open-devices-program/`

**Comment by osm0sis** [comment]
Looks like hdr_v2 boot.img with 2SI boot-as-recovery ramdisk.

```
Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers

Supplied image: boot-X1.img

Setting up work folders . . .

Image type: AOSP

Signature with "AVBv2" type detected.

Splitting image to "split_img/" . . .

ANDROID! magic found at: 0
BOARD_KERNEL_CMDLINE androidboot.hardware=qcom androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=2048 loop.max_part=7 androidboot.usbcontroller=a600000.dwc3 oemboot.earlymount=/dev/block/platform/soc/1d84000.ufshc/by-name/oem:/mnt/oem:ext4:ro,barrier=1:wait,slotselect,first_stage_mount buildproduct=griffin_dsds buildid=KUMANO-1.2.0-210427-1148 panic_on_err=1 buildvariant=user
BOARD_KERNEL_BASE 0x00000000
BOARD_NAME
BOARD_PAGE_SIZE 4096
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x01000000
BOARD_SECOND_OFFSET 0x00000000
BOARD_TAGS_OFFSET 0x00000100
BOARD_OS_VERSION 11.0.0
BOARD_OS_PATCH_LEVEL 2021-05
BOARD_HEADER_VERSION 2
BOARD_HEADER_SIZE 1660
BOARD_DTB_SIZE 1180830
BOARD_DTB_OFFSET 0x01f00000

Unpacking ramdisk to "ramdisk/" . . .

Compression used: gzip
46143 blocks

Done!
```

I don't see any reason Magisk shouldn't already be able to handle this. 😕

**Comment by osm0sis** [comment]
Any luck with 23013? A number of regressions have been fixed.

**Comment by osm0sis** [comment]
It's been 3 weeks, presuming fixed unless further confirmation and fresh logs are posted.

**Comment by hongsheep** [comment]
> 

hey dude have you solve the J9110 issue with magisk patched boot img? does it work with the latest magisk patch?
