### ISSUE TITLE
[Does not affect all ROMs] Regression after "Remove unnecessary sepolicy rules" commit

### ISSUE THREAD

**Issue by VladWinner** [topjohnwu/Magisk#4647]
Some sepolicy rules for deodexed ROMs [were removed](https://github.com/topjohnwu/Magisk/commit/e136fb3a4fcba9d39f9c65bcfa521697f21694d3#diff-41906340e085dac39dbff041a66517d526239f213c453a37d508701d1cde3d8dL210 ) from the latest builds of Magisk (23+) as "outdated". 
However, returning these strings can eliminates many lag spikes on some deodexed ROMs so deleting these lines seems premature and affects smooth running on some devices. 
I assume that reason ["This should not be done"](https://github.com/topjohnwu/Magisk/commit/e136fb3a4fcba9d39f9c65bcfa521697f21694d3#:~:text=this%20should%20not%20be%20done) does not work when the project is aimed at a large number of devices, and not just for the most recent phones or stable ROMs. I have another confirmation from at least 7 users that this solution helped them get rid of noticeable lags after installing Magisk 23+ on Android 11 and 12. Yes, this problem does not concern everyone, but the affected devices users simply do not have information about a workaround, they can only explore rolling back to pre-23 version of Magisk.

Strings that fix the issue:

    // Support deodexed ROM on Oreo
    allow("zygote", "dalvikcache_data_file", "file", "execute");

    // Support deodexed ROM on Pie (Samsung)
    allow("system_server", "dalvikcache_data_file", "file", "write");
    allow("system_server", "dalvikcache_data_file", "file", "execute");

HWUI rendering monitoring before re-adding the strings (Settings app):
![image](https://user-images.githubusercontent.com/13555921/132126826-45094eff-3206-446a-905a-bc747a212b08.png)

After re-adding the strings:
![image](https://user-images.githubusercontent.com/13555921/132126961-e9894d04-2c00-4342-8929-668e6de5c45f.png)

In fact, I'm not the first to discover this behaviour, but I tried to translate the explanation into English and upload it here to be able to influence it.
Source posts by original authors (in Russian): 
[Explanation](https://4pda.to/forum/index.php?showtopic=774072&st=39520#entry106725378) 
[Workaround module description](https://4pda.to/forum/index.php?showtopic=915158&view=findpost&p=109055085)

You can even not return these strings back to the build, it is enough to record info here for those who notice strange behavior on their devices.

Device: Xiaomi Mi 8
Android version: 11 RKQ1.210528.001
Magisk version name: Canary f822ca5b (23001) (21)
Magisk version code: 23001

**Comment by canyie** [comment]
I don't think it is regression. These sepolicies should be added by ROM developers if this is really needed. I think users of these romd will get same problem with no magisk installed.

**Comment by vvb2060** [comment]
> I think users of these ROMs will get same problem with no magisk installed.

If the ROM developer won't fix this issue, you can use magiskpolicy live patch.
