### ISSUE TITLE
MagiskSu日志

### ISSUE THREAD

**Issue by cxyzzz** [topjohnwu/Magisk#465]
magiskSu的日志能显示详细内容吗？像Supersu那样，点击日志能显示具体命令

**Comment by topjohnwu** [comment]
我也有想過這個功能，但是實作上需要幾乎從開始0重寫，因此目前不在考慮範圍內。

**Comment by funnypro** [comment]
@topjohnwu 是因为MagiakSU的上游分支没考虑过这个功能吗？
