### ISSUE TITLE
Using wrong file manager app to open a file to patch cause an unuseful error

### ISSUE THREAD

**Issue by thebestnom** [topjohnwu/Magisk#4650]
Device: OnePlus 7t
Android version:  11
Magisk version name: canary
Magisk version code: 23001
tested on canary and tested on self compiled version
got error 
```
Process error
Instalaation error
```
while trying to patch boot.img, read the bug was that magisk couldn't read the boot.img, tried for way to much to give magisk read permission, but while doing that I saw the error in logcat was `java.io.IOException: read failed: (Software caused connection abort) android`, so I decided for no reason to check if it actually the file manager that I choose the file is the problem (which it was of course, used solid explorer, didn't think that would be a problem) 

I suggest adding try choose the file in a different file explorer app to make it easier for the next person who stuck on this

**Comment by topjohnwu** [comment]
This is an issue of the file explorer, not Magisk. The Magisk app is using standard Android API to select files

**Comment by thebestnom** [comment]
@topjohnwu Yes, this is a in file explorer, but it will be (I guess) a problem while using any file manager thats not targeted at android 11, the problem in magisk is that the error is unhelpful
