### ISSUE TITLE
[MAGISKHIDE] Samsung KNOX not working

### ISSUE THREAD

**Issue by Ashwin-droid** [topjohnwu/Magisk#4651]
Device: SM-G615F
Android version: 8.1.0
Magisk version name: 23001.
Magisk version code: 23001.

Dont close this issue. I promise to close this issue on resolved

Please reference issue #4635
More info this time -
My safetynet is passing with basicintrigety and ctsprofile (uses basic eval as my device is quite old) 
So no more SafetyNet issues
Proof-

![Screenshot_20210906-084841.jpg](https://user-images.githubusercontent.com/58349846/132155999-949962a8-5800-4682-b072-51f7de434e28.jpg)

Root only apps - 'Root browser' and 'vpn hotspot' (also tried uninstalling it but no luck)

Modules installed - busybox by osmosis (also tried uninstalling it but still no luck)

Else I follow all best magiskhide practices perfectly

Here is the recording

https://user-images.githubusercontent.com/58349846/132155063-582fea7b-3ad3-4129-8d24-616c3b1c0931.mp4

**Comment by usrDottik** [comment]
I've a Samsung Galaxy A70. 

It detects that you have installed a modded Boot Image VIA Download Mode and it triggers the KNOX BIT, You can check it VIA download mode, once the KNOX BIT is tripped all KNOX related stuff won't work. Here is an example of a tripped bit.
![imagen](https://user-images.githubusercontent.com/81375555/132163103-33f2d3af-65ef-4030-a775-1b7764fd858c.png)

**Comment by Ashwin-droid** [comment]
Yes I know that my KNOX warranty bit is tripped (because of rooting) but magisk should patch it regardless by setting some build prop rules ([from changelog](https://github.com/topjohnwu/Magisk/blob/f822ca5b23bea0a1b7a6e97841e253398e79fb8e/docs/changes.md#v120))
To quote it 

> [MagiskHide] Add built in prop rules to fake KNOX status Samsung apps requiring KNOX status to be 0x0 should now work (Samsung Pay not tested)

> "(Samsung Pay not tested)"

so apps like secure folder should work right?? 
that's the reason that devcheckinfo said 0x0 otherwise without magiskhide it would have said 0x1 (tested)
check the time if you think it is fake (pun intended)
Without magiskhide-
![Screenshot_20210906-112752_DevCheck](https://user-images.githubusercontent.com/58349846/132168165-fc7fe5c9-e5d5-426b-889d-34a8d552d569.jpg)

With magiskhide-
![Screenshot_20210906-112836_DevCheck](https://user-images.githubusercontent.com/58349846/132168222-b9857de4-0012-42e1-a608-71255d67e671.jpg)

As for safetynet reference the closed issues by osmosis 

> #1152
> 
> See here though for the recent SafetyNet change which might affect your Knox detection too: https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/page-2379#post-85578621

**Comment by osm0sis** [comment]
#1152 and https://topjohnwu.medium.com/state-of-magisk-2021-fe29fdaee458
