### ISSUE TITLE
`build.py emulator` is slow on windows because of `LOCAL_SHORT_COMMANDS` from busybox

### ISSUE THREAD

**Issue by yujincheng08** [topjohnwu/Magisk#4657]
There's `LOCAL_SHORT_COMMANDS := true` in busybox/Android.mk. It will generate cflags file in both compile and link steps. So everytime to build busybox in windows there will be tons of `cmp` between cflags files  and will be stuck for mins.

The solution is to switch to `APP_SHORT_COMMANDS`:
```diff
--- a/native/jni/Application.mk
+++ b/native/jni/Application.mk
@@ -10,6 +10,9 @@ APP_STRIP_MODE   := --strip-all
 # Busybox should use stock libc.a
 ifdef B_BB
 APP_PLATFORM     := android-22
+ifeq ($(OS),Windows_NT)
+APP_SHORT_COMMANDS := true
+endif
 else
 # Make Busybox cflag stable
 APP_CFLAGS       += -D__MVSTR=${MAGISK_VERSION} -D__MCODE=${MAGISK_VER_CODE}
--- a/native/jni/external/busybox/Android.mk
+++ b/native/jni/external/busybox/Android.mk
@@ -18,8 +18,4 @@ LOCAL_CFLAGS := \
 -w -include include/autoconf.h -D__USE_BSD \
 -DBB_VER=\"$(BB_VER)\" -DBB_BT=AUTOCONF_TIMESTAMP

-ifeq ($(OS),Windows_NT)
-LOCAL_SHORT_COMMANDS := true
-endif
-
 include $(BUILD_EXECUTABLE)
```

Device: Windows
Android version: N/A
Magisk version name: ca99808
Magisk version code: 23001

**Comment by yujincheng08** [comment]
more detail here in Chinese: https://t.me/vvb2060Channel/474

**Comment by osm0sis** [comment]
Yeah, not sure why that was removed in https://github.com/topjohnwu/Magisk/commit/775d095b3cc2bd20514dca3ab5c57c6e89085c59

Also related: https://github.com/topjohnwu/ndk-box-kitchen/pull/4

**Comment by yujincheng08** [comment]
yes. and now she found this was wrong. the proper way to do so is to place APP_SHORT_COMMANDS within ifdef B_BB
