### ISSUE TITLE
How to reinstall magisk after hard reset/wipe data?

### ISSUE THREAD

**Issue by 464551** [topjohnwu/Magisk#4669]
My device got bootloop after installing gravity box on android 11, then i just factory reset my phone, install root checker and the device is still rooted! 😅 now how i re install magisk since my device has been rooted before?

Sorry i dont know how to post comment so i make this thread. Thanks
Device: note 10s
Android version: 11
Magisk version name: 2.3
Magisk version code:

**Comment by usrDottik** [comment]
I think you should just reinstall MagiskSU aka Magisk Manager, and just. That
