### ISSUE TITLE
NDK_TOOLCHAIN_VERSION deprecated

### ISSUE THREAD

**Issue by ahxxm** [topjohnwu/Magisk#467]
the warning:

```
Android NDK: WARNING: Deprecated NDK_TOOLCHAIN_VERSION value: 4.9. 
GCC is no longer supported and will be removed in the next release. 
See https://android.googlesource.com/platform/ndk/+/master/docs/ClangMigration.md.
```

was introduced by [this line](https://github.com/topjohnwu/Magisk/commit/0f34f0033c22fabd4fd13dffabdc53cd9af0f6a7#diff-2f089b273fabbe691e5d8e408fcdce5aR11)

the build will use prebuilt llvm instead of gcc within ndk after removing this line, result binary works on my device

**Comment by topjohnwu** [comment]
BusyBox built with Clang doesn't work properly. It is the only thing left using GCC. All other binaries will be built with Clang.

**Comment by topjohnwu** [comment]
The binary looks like it works properly, but extensive testing has shown some issues in certain applets.
