### ISSUE TITLE
magiskboot: not found

### ISSUE THREAD

**Issue by Enlightening-stars** [topjohnwu/Magisk#4672]
Device: picxl 2
Android version: 9.0 
Magisk version name: 23.0:MAGISK 
Magisk version code: 23.0:MAGISK

![image](https://user-images.githubusercontent.com/86091961/132958928-c4691b65-7db1-4298-9ba9-86396336d433.png)
but
![image](https://user-images.githubusercontent.com/86091961/132958949-2392a798-9ded-4865-9dcf-48867444e22a.png)

**Comment by Didgeridoohan** [comment]
The magiskboot binary isn't exposed to the system, so that's expected.

**Comment by Enlightening-stars** [comment]
> magiskboot 二进制文件不会暴露给系统，所以这是意料之中的。

how to use masikboot this tools  ???

**Comment by Enlightening-stars** [comment]
> > magiskboot 自带文件不会暴露给系统，所以这是意料的。
> 
> 如何使用 masikboot 这个工具？？？

那这个maiskboot 工具在哪里找到 可以用？？？
