### ISSUE TITLE
Why you joined google 

### ISSUE THREAD

**Issue by bx1hacker** [topjohnwu/Magisk#4678]
You just removed magiskhide because of money you have finished your carrier we all pubg hacker just root and use magisk because of magisk hide and now we are going to find some new app and files to get this opportunity of hiding root bye bye magisk #dump_carrier #fuckgoogle

**Comment by Sushrut1101** [comment]
lol

**Comment by kvxrun** [comment]
ah yes, the poopji heckah

**Comment by bencetari** [comment]
Bro. Android is a hobby. Google employed him and honestly, who wouldn't catch this opportunity?
Also using MagiskHide for PubGay hack is retardness.
Hiding your root status has way more benefit than that unoptimized piece of shit that's made for PC, not a fucking mobile phone.

**Comment by Sushrut1101** [comment]
> ah yes, the poopji heckah

🤣

**Comment by bencetari** [comment]
If you want pubGay hack. get it for PC and use something that actually has something to do with gaming with you know. Physical buttons and an x86 CPU instead of sth with ARM.

**Comment by NitroVenom** [comment]
Lmao 🤣

**Comment by ElytrA8** [comment]
fuck you mam
Respect devolopers they are not your slaves

**Comment by hraj9258** [comment]
Why don't u thanks him that at least he is continuing the magisk project, even after joining google

**Comment by DeinMathelehrer** [comment]
I got a solution for you :D look here this dude uses the new root app it's a bit difficult but it works!!!!!!!! 
https://www.youtube.com/watch?v=dQw4w9WgXcQ

@bx1hacker

**Comment by Bounty780** [comment]
Lmao cringe.

THE DUDE GOT A PRIZED JOB AND YOU'RE TELLING HIM "WHY YOU JOINED GOOGLE"

**Comment by salmannotkhan** [comment]
"You have ruined/finished your CARRIER by joining Google"

- Big brain hecker

**Comment by salmannotkhan** [comment]
"You have ruined/finished your CARRIER by joining Google"

- Big brain hecker

**Comment by herobuxx** [comment]
Why he should care ur PUBG hacking over his own career lmao. Can u guarantee his life can get better 
than works at  cuz he makes your POOPG Hacking possible?


You sussy Baka

**Comment by Sushrut1101** [comment]
> Why he should care ur PUBG hacking over his own career lmao. Can u guarantee his life can get better
> than works at cuz he makes your POOPG Hacking possible?
> 
> You sussy Baka

🤣

**Comment by usrDottik** [comment]
WT* bruh, you can't just come in front of the creator of the application you use, Magisk, and tell him he only wants money, when literally, he still did Magisk, even when his patreon has very little supporters...

**Comment by Pushton** [comment]
Every pussie need sympathy of developer and support and showing some f**cking acting. I was telling him to don't remove magiskhide and the scripter just taked advantage to get sympathy. Lol scripters

**Comment by Pushton** [comment]
> I got a solution for you :D look here this dude uses the new root app it's a bit difficult but it works!!!!!!!!
> https://www.youtube.com/watch?v=dQw4w9WgXcQ
> 
> @bx1hacker

It really helped so much everyone use this script wow its legit every hacker should know this brilliant man thanks for helping from youtube
https://www.youtube.com/watch?v=dQw4w9WgXcQ
