### ISSUE TITLE
INSTALL_FAILED_OLDER_SDK

### ISSUE THREAD

**Issue by lamar-studio** [topjohnwu/Magisk#4694]
Device: 小米盒子1s
Android version:4.4.2
Magisk version name: v23.0
Magisk version code: 23001

**Comment by Didgeridoohan** [comment]
Magisk v23+ only supports Android 5+.
https://topjohnwu.github.io/Magisk/releases/23000.html

**Comment by lamar-studio** [comment]
> Magisk v23+ only supports Android 5+.
> https://topjohnwu.github.io/Magisk/releases/23000.html

if i want to root Android 4+, how can i do? use the old Magisk version?

**Comment by Didgeridoohan** [comment]
Stay in v22.1.
