### ISSUE TITLE
Add notice that you can't see any modules from the repository in ALPHA version.

### ISSUE THREAD

**Issue by qg0** [topjohnwu/Magisk#4699]
Device: Xiaomi redmi note 10 pro
Android version: 11
Magisk version name: v23.0
Magisk version code: 23001 (21)

I propose to add the notice (some text near the search icon or in the search result) that you can't see any modules from the repository in ALPHA version and the change of the update channel won't help to solve the issue, you need to install an old APK.

The first module ("MagiskHide Props Conf") was installed manually from the zip [archive](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/releases/tag/v6.0.2). The second one ("Systemless hosts" has appeared after I turned on it in the settings. I don't see any modules from the repository.

![Screenshot_2021-09-19-05-05-27-529_com topjohnwu magisk](https://user-images.githubusercontent.com/919099/133910325-c07c390d-19db-4f49-b9a9-4d975c47150c.jpg)

**Comment by osm0sis** [comment]
Search remains for the scenario scare the user has installed a bunch of modules now, I guess, but yeah, not super useful / more confusing than useful.

**Comment by qg0** [comment]
> 
> 
> Search remains for the scenario where the user has installed a bunch of modules now, I guess, but yeah, not super useful / more confusing than useful.

The search icons could be still here. But some notice that the repo doesn't work is a good idea. I couldn't understand why I don't see any modules.

**Comment by osm0sis** [comment]
You either follow John on Twitter or you read the changelog.
