### ISSUE TITLE
A530F Oreo no REAL root access

### ISSUE THREAD

**Issue by breakersvd** [topjohnwu/Magisk#470]
Hi @topjohnwu 

Again the Galaxy A530F (A8 2018) on Android 8.0.0 (that has imei losing bug)

regardless of baseband losing bug (i fixed it by removing sbin overlay as mentioned in [Baseband is not working anymore]) there is a real bug:

Compiled magisk with two tries (1 - removed sbin overlay // 2 - untouched sources) and both tries the same results:

-- Magisk is installed and everything is executed and Magisk apk show me that everything is ok
-- adb shell have full root permissions
-- all root check applications return with success results

but the problem with applications that need root permissions like [Titanium Backup, ES File Explorer.....],
root checker applications that run commands like [su -v, su -V, su -c id] are working fine
but applications that run [su] to do the root functions don't work and return with fail value

Here is needed files:

-- Root exists:
![capafesdgjhture](https://user-images.githubusercontent.com/36429390/44005570-240811f2-9e7e-11e8-966d-317baf1558b9.PNG)

-- Root checkers:
![screenshot_20180812-224353](https://user-images.githubusercontent.com/36429390/44005753-4a44cb14-9e81-11e8-81e4-89ac603a3d2b.jpg)

-- Titanium Backup:
![screenshot_20180812-222944_titanium backup](https://user-images.githubusercontent.com/36429390/44005647-4b1aa4fc-9e7f-11e8-984b-fab7ed056435.jpg)

-- Magisk log (last two requests are return with fail [ES File Explorer & Titanium Backup]):
[magisk.log](https://github.com/topjohnwu/Magisk/files/2281262/magisk.log)

-- LogCat:
[logcat.zip](https://github.com/topjohnwu/Magisk/files/2281266/logcat.zip)

-- Stock Boot image for Oreo A530F:
[https://mega.nz/#!TQQ3zR5A!TFO3c-KqJHAOMZqP9Ht6NkCWIHrBqNvMRg0ijjVv7Sk](https://mega.nz/#!TQQ3zR5A!TFO3c-KqJHAOMZqP9Ht6NkCWIHrBqNvMRg0ijjVv7Sk)

Note: the problem exists also in compiled magisk without touching source (without removing sbin overlay).

EDIT: I monitored the executing process for `su` binary and the output to applications and i found result `Killed`;

-- ES File Explorer:
![capsdfgjhgture](https://user-images.githubusercontent.com/36429390/44006086-a5bc9e04-9e86-11e8-969d-2f7ff08b9f10.PNG)

-- Titanium Backup:
![image](https://user-images.githubusercontent.com/36429390/44006083-93068270-9e86-11e8-8ace-15ebc7b70d22.png)

Thanks in advance.

**Comment by salimskiy** [comment]
Can you share your compiled magisk?

**Comment by salimskiy** [comment]
ok.thank you

**Comment by BlackMesa123** [comment]
Did you checked if in logcat there are SELinux denials?

**Comment by breakersvd** [comment]
[Magisk_16.72_UnOfficial_UnStable.zip](https://mega.nz/#!PFhiDQYD!Z9hOewCkAR0RXzqMXKcg-0krdQQhxkz0wq_6M7JexFI)

Yes i checked it, there are some denials but this problem not from them, anyway i fixed them by adding `sepol_allow();` but the result are the same

**Comment by breakersvd** [comment]
@topjohnwu this is the problem exactly
![screenshot_20180813-003919_terminal emulator](https://user-images.githubusercontent.com/36429390/44006725-cad5414a-9e91-11e8-8ceb-3750b8c50006.jpg)

**Comment by salimskiy** [comment]
breakersvd

root is.Magisk Manager does not work
https://mega.nz/#!3A8mlISR!Q7BPXE5lLarDUOGeVCTXD_G9sA4G-NRtUxE3g-UlsWQ

**Comment by breakersvd** [comment]
@salimskiy 
MagiskManager is a root manager not a root tool
in the Magisk_16.72 zip i removed the force needing for MagiskManager to exec the su commands
i.e. even if MagiskManager didn't crash the problem will stay and it is not the reason for the problem

**Comment by salimskiy** [comment]
@breakersvd
I already understand, thank you.

**Comment by topjohnwu** [comment]
Let's move the discussion here into #426
