### ISSUE TITLE
[Feature Request] color codes

### ISSUE THREAD

**Issue by JohnFawkes** [topjohnwu/Magisk#471]
please add a way to change the color of the install text in magisk during install like terminal color codes kind of thing. I know aroma had this feature as well by doing [COLOR="red"] ui_print bsbbsbsv [/COLOR] it would be a nice thing to have to highlight important information during install

**Comment by mrturcot** [comment]
This is for bugs/issues not feature requests.

**Comment by topjohnwu** [comment]
I don't think it is possible in recovery, and it would be very difficult to implement in Magisk Manager. Not going to add this for the time.
