### ISSUE TITLE
build app failed

### ISSUE THREAD

**Issue by XxWwCc** [topjohnwu/Magisk#4712]
* Building the Magisk app

e: G:\Test\Magisk\buildSrc\src\main\java\Codegen.kt: (278, 16): Unresolved reference: transferTo

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Build app failed!

**Comment by SliverBullet5563** [comment]
me too!!!

**Comment by alangecker** [comment]
had the same issue , but I managed now to build it successfully after switching to openjdk-11 :)

**Comment by Joyoe** [comment]
> had the same issue , but I managed now to build it successfully after switching to openjdk-11 :)

Me too, had the same issue and after upgrading JDK to OpenJDK 11 the issue resloved, then I am not sure if it will rasie new compatiblity issues as the target JDK is 1.8.

And acutually, after implemeting OpenJDK 11, when importing costumized libsu or even importing libsu from https://github.com/topjohnwu/libsu I kept received compaltibity issues regarding koltin, gradle and JDK.

**Comment by Jamy325** [comment]
Change transferTo to copyTo
