### ISSUE TITLE
Android compilation error

### ISSUE THREAD

**Issue by clondy999** [topjohnwu/Magisk#4747]
I set up the environment according to the tutorial and compiled it, but the following errors occurred
![1632995917(1)](https://user-images.githubusercontent.com/73311186/135431770-d878f8ff-341b-41d1-8604-6ed0435b253a.png)

**Comment by usrDottik** [comment]
You may need extra dependencies. Did you look at the debugging message **Module magiskinit depends on undefined modules: cxx mincrypt** maybe searching and installing those packages can work
