### ISSUE TITLE
Rooted, but device doesn't mount hw_product partition anymore

### ISSUE THREAD

**Issue by qianmo-xw** [topjohnwu/Magisk#4772]
Device: HUAWEI enjoy 20Pro DVC-AN20
Android version: HarmonyOS2.0
Magisk version name: 23001
Magisk version code: 23001
CPU is MT6873
In fact, I have already unlocked the unlock bootloader of Huawei MTK devices, based on Hongmeng's Huawei bootloader, and tried to patch Ramdisk with Magisk. It can successfully boot and enter the system. Due to Huawei’s unique super partition structure, Huawei’s product partition is displayed on the device as the hw_product partition. Magisk cannot mount this partition, resulting in loss of parameters and lack of customized applications on the device. Similar to applications such as cameras. However, the machine does not have fstab.mt6873 in the ramdisk. Even if I try to mount it with the mount command, it will prompt me /etc/fstab/ no such file. I wonder if we can change it from the init stage.If I flash into the official Ramdisk image to start, it is all normal.
I found that some parameters are completed by reading hw_product, so the mounting of this partition is extremely important.
this is ramdisk file
[ramdisk_offical.zip](https://github.com/topjohnwu/Magisk/files/7351575/ramdisk_offical.zip)
[ramdisk_patch.zip](https://github.com/topjohnwu/Magisk/files/7351578/ramdisk_patch.zip)

![QQ图片20211015151835](https://user-images.githubusercontent.com/83547396/137447686-364ace55-6d8a-49ca-8dce-b20125a30660.jpg)
![QQ图片20211015151839](https://user-images.githubusercontent.com/83547396/137447700-cbe9a74b-3296-4902-949f-93b451ba8e77.jpg)
.

**Comment by qianmo-xw** [comment]
![Uploading 微信图片_20211021224605.jpg…](
![微信图片_20211021224615](https://user-images.githubusercontent.com/83547396/138302107-c5c16dfc-9e4e-4462-902a-fb90b86e0b43.jpg)
![微信图片_20211021224620](https://user-images.githubusercontent.com/83547396/138302115-2fdae38e-d594-40ba-a172-117f676ff4af.jpg)
)
no patch recovery

**Comment by yujincheng08** [comment]
> > See if there's any way you can grab logs from the patched ramdisk.img attempting to boot. I think that's the right way, and so the logs could help figure out what's changed in the Huawei Treble support in Magisk.
> 
> Can you give me some suggestions or methods? Go to the get log, some ADB command

adb bugreport

**Comment by canyie** [comment]
Try #5146 (build artifacts can be downloaded from  https://github.com/topjohnwu/Magisk/actions/runs/1671811121 )

**Comment by yujincheng08** [comment]
Should be addressed by 810d27a618908621a7eca32f9adccab2611746ee

**Comment by acastillorobles77** [comment]
@qianmo-xw how did you unlock the bootloader?
