### ISSUE TITLE
Can't execute "pm" or "am" commands on Android Pie due to SELinux restriction

### ISSUE THREAD

**Issue by tliebeck** [topjohnwu/Magisk#478]
All "pm" and "am" commands fail when executed using Magisk su on an Android Pie device.  Test device is an Essential PH-1, stock/latest PPR1.180610.091, Magisk 16.7.

This behavior can be replicated by using an on-device terminal app (not via ADB), entering su mode, and simply executing "pm" or "am".

The following SELinux rejection will be logged:
type=1400 audit(0.0:82148): avc: denied { read write } for path="/dev/pts/2" dev="devpts" ino=5 scontext=u:r:system_server:s0 tcontext=u:object_r:untrusted_app_all_devpts:s0:c5 12,c768 tclass=chr_file permissive=0

The commands work properly if SELinux is placed in permissive mode.

Checking my current security context using /proc/self/attr/current...

As app user: u:r:untrusted_app_27:s0:c512,c768 
As magisk su user: is u:r:magisk:s0:

The "pm" command will fail running either as a normal user or root user, with an identical SELinux rejection message showing the source context as "u:r:system_server:s0"

The "am" command will not fail if it is run with no arguments as a normal app user, but will fail if run as root.

Both am and pm commands will work over ADB, as either a normal user as root.

Thank you!

**Comment by DenyDarko** [comment]
Already fixed for next release :

f1edc8443c31a77ae978d8288909485ea5dbd34a

**Comment by tliebeck** [comment]
Awesome, thank you!
