### ISSUE TITLE
Corrupt recovery after patching TWRP 3.5.2_9.2

### ISSUE THREAD

**Issue by longnguyen2004** [topjohnwu/Magisk#4786]
Device: Xiaomi Redmi 6a (cactus)
Android version: Android 9 (MIUI 11)
Magisk version name: v23.0
Magisk version code: f822ca5b

Trying to patch this version of TWRP with Magisk results in an unbootable recovery (trying to boot from it results in a black screen, then the phone reboots into system)

Magisk log: [magisk.log](https://github.com/topjohnwu/Magisk/files/7378028/magisk.log)
Original recovery: [twrp-3.5.2_9-2-cactus.img](https://dl.twrp.me/cactus/twrp-3.5.2_9-2-cactus.img)

**Comment by kaotisk-hund** [comment]
I have the same issue

**Comment by kaotisk-hund** [comment]
> I have the same issue

I had a backup of the boot image to recover from, also it happens the SAR value to be Yes.

Is it okay if we use TWRP to make a backup of the boot, patch it with magisk and the reboot to recovery mode to install the patched version?
