### ISSUE TITLE
Properties being set from disabled module

### ISSUE THREAD

**Issue by Didgeridoohan** [topjohnwu/Magisk#48]
A module that changes properties through system.prop still changes these props while disabled. Other modifications are not loaded from the disabled module.

User 4RK4N on xda have reported the same issue: https://forum.xda-developers.com/showpost.php?p=70673263&postcount=85

**Comment by topjohnwu** [comment]
Ah.. crap, I forgot to implement a check
Thanks for the report

**Comment by topjohnwu** [comment]
Fixed
