### ISSUE TITLE
Touchscreen not working after magisk is flashed

### ISSUE THREAD

**Issue by yordanBUL** [topjohnwu/Magisk#4800]
So after i flashed Magisk in to the phone touchscreen not reading and the fix is to flash a stock miui 12.5 rom

Device: Xiaomi Redmi Note 9
Android version: 11
Magisk version name: 97c1e18
Magisk version code: 23001

**Comment by osm0sis** [comment]
boot.img, magisk_patched.img, patching log, magisk.log and logcat or nobody can help you here.
