### ISSUE TITLE
Magisk Stuck On Repacking Boot Image

### ISSUE THREAD

**Issue by akano12** [topjohnwu/Magisk#4810]
Device:  Samsung Galaxy J6+ (SM-J610F)
Android version: 9.0
Magisk version name: d7e7d 
Magisk version code: 23010

Installed the app without problems,however when trying to update magisk it gets stuck  on 'Repacking boot image' forever.
I tried renaming the app to zip and flashing through recovery and still same issue, it gets stuck on 'Repacking boot image' and now my phone is stuck in bootloop and won't turn,constantly restarting on 'Samsung Galaxy J610f
[dmesg.log](https://github.com/topjohnwu/Magisk/files/7406302/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/7406303/recovery.log)
'

**Comment by canyie** [comment]
ok, so it is a regression since #4596 . I added some log in this build: https://github.com/canyie/Magisk/actions/runs/1401399326 , could you test it? you device will gets into bootloop, don't worry, just upload logs here 😂

**Comment by akano12** [comment]
> 
> 
> ok, so it is a regression since #4596 . I added some log in this build: https://github.com/canyie/Magisk/actions/runs/1401399326 , could you test it? you device will gets into bootloop, don't worry, just upload logs here 😂

[log.zip](https://github.com/topjohnwu/Magisk/files/7446405/log.zip)

**Comment by canyie** [comment]
well, I believe this is Samsung kernel magic because:
• Your log seems normal but xwrite() fails with EFAULT.
• Write to another file works file, only /init cannot be written.
• Can't reproduce this on non-Samsung devices.

So I think #4837 is a proper fix for this. Thanks for your help!

**Comment by vvb2060** [comment]
This should be related to the kernel, can you provide the version number? https://opensource.samsung.com/uploadSearch?searchValue=SM-J610F

**Comment by akano12** [comment]
@osm0sis the bootloop issue has been solved thanks to canyie's PR, 
but the repacking issue hasn't been fixed, magisk takes around 15 minutes to finish repacking the boot image (from 5-10 seconds to 15 minutes)

**Comment by yujincheng08** [comment]
> > This should be related to the kernel, can you provide the version number? https://opensource.samsung.com/uploadSearch?searchValue=SM-J610F
> 
> check this https://androidfilehost.com/?fid=6006931924117926060 + _PIE ONLY: Due to some new securities in Samsung's latest Pie kernels, root will not work with the stock kernel. The patched kernel below is required to gain root on Pie. (NOTE: flashing a custom kernel on PIe breaks the lockscreen. Ensure NO lockscreen is enabled before installing the kernel.)_
> 
> this is custom kernel (it's stock, just some securities have been removed/patched to make magisk work) the lockscreen & biometrics issues have been solved by flashing a zip to patch few things.
> 
> more info on this thread https://forum.xda-developers.com/t/recovery-root-twrp-3-3-1-1-galaxy-j6-j610f-fn-g-ds.3875150/

we need the source of this kernel.
