### ISSUE TITLE
Magisk app in hidden mode does not start after app upgraded to latest version

### ISSUE THREAD

**Issue by logical-and** [topjohnwu/Magisk#4815]
Device: Pixel 5
Android version: 11
Magisk version name:  d7e7d
Magisk version code:  23010

Please see the attached [logcat.log](https://github.com/topjohnwu/Magisk/files/7412166/logcat.2.log). Unfortunately, I don't remember what version was before (most likely 23.0, since I installed it initially in June of 2021).

It happened after the application proposed to upgrade, and I tapped OK.

![image](https://user-images.githubusercontent.com/1403109/138737665-a2605ca9-41a1-4c4b-98fa-2d17b9d3a1b5.png)

Is there a workaround I could apply to fix the application?

**Comment by osm0sis** [comment]
@logical-and: This seems resolved for me with 23001 -> 23011 hidden. Can you confirm?

**Comment by logical-and** [comment]
Wait, wait - I didn't have a chance to retest this. I'll try to perform the update on Sat, approximately!

**Comment by logical-and** [comment]
Not quite fixed for me - what should I do to check it exactly? When I start application it keeps closing. I can install Magisk from scratch - but afraid if it won't make my Pixel 5 a brick

**Comment by 1235789gzy1** [comment]
Just brush in the repaired boot.img file again

**Comment by 1235789gzy1** [comment]
> Not quite fixed for me - what should I do to check it exactly? When I start application it keeps closing. I can install Magisk from scratch - but afraid if it won't make my Pixel 5 a brick

Just brush in the repaired boot.img file again

**Comment by canyie** [comment]
Try #4981? It's looks like a fix for this issue.
