### ISSUE TITLE
Magisk Hide selections disappear

### ISSUE THREAD

**Issue by wondering639** [topjohnwu/Magisk#483]
Hi all,

today I wanted to use Magisk Hide the first time. I went to Magisk Manager - Magisk Hide, selected an app. Used the back button, again visited Magisk Manager - Magisk Hide and nothing was selected. I didn't find any apply button or similar. Am I missing something? Thanks!

Note: Using a Pixel 2, Magisk 16.0 and Manager 5.8.3 (129).

**Comment by vvb2060** [comment]
#461
