### ISSUE TITLE
android-12.0.0_r7 raven bootloop

### ISSUE THREAD

**Issue by ASerbinski** [topjohnwu/Magisk#4839]
Device: raven (Pixel 6 Pro)
Android version: android-12.0.0_r7 built from AOSP
Magisk version name: canary
Magisk version code: 23011

The unit briefly shows the "google" logo then reboots. No log collection is possible.

[magisk_patched-23011_jnQrV.img.gz](https://github.com/topjohnwu/Magisk/files/7443539/magisk_patched-23011_jnQrV.img.gz)

**Comment by osm0sis** [comment]
Also https://forum.xda-developers.com/t/read-this-before-rooting-your-raven.4352531/
