### ISSUE TITLE
Samsung Galaxy J5 2016 won't boot - ZIMAGE_KERNEL patching broken

### ISSUE THREAD

**Issue by daywalk3r666** [topjohnwu/Magisk#4849]
Device: j5xnlte (J5 2016)
Android version: Blissrom 14.7 (android 11)
Magisk version name: canary
Magisk version code: 23011

With all new canary builds and github builds my j5 is stuck on bootscreen. Any solutions?

**Comment by osm0sis** [comment]
What was the last version to work?

**Comment by daywalk3r666** [comment]
Yes

**Comment by osm0sis** [comment]
How did you root it with 23001? Upload the .img you patched.

**Comment by osm0sis** [comment]
Oh wait, already fixed upstream for the next Canary, I think.

#4810

**Comment by daywalk3r666** [comment]
#4837 won't fix the issue
[magisk_install_log_2021-10-31T09:34:16Z.log](https://github.com/topjohnwu/Magisk/files/7448368/magisk_install_log_2021-10-31T09.34.16Z.log)
Stock kernel
[boot.zip](https://github.com/topjohnwu/Magisk/files/7448372/boot.zip)
Patches kernel
[magisk_patched-23011_qTJmQ.zip](https://github.com/topjohnwu/Magisk/files/7448381/magisk_patched-23011_qTJmQ.zip)
@osm0sis

**Comment by canyie** [comment]
please grab kernel logs like https://github.com/topjohnwu/Magisk/issues/4810#issuecomment-951467752 and upload them here

**Comment by daywalk3r666** [comment]
> please grab kernel logs like [#4810 (comment)](https://github.com/topjohnwu/Magisk/issues/4810#issuecomment-951467752) and upload them here

Should i used your github build vor last canary

**Comment by daywalk3r666** [comment]
No files in sys/fs/pstore
[dmesg.log](https://github.com/topjohnwu/Magisk/files/7449134/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/7449135/recovery.log)

**Comment by canyie** [comment]
Can you get an adb connection when it stuck? I really don't know how to debug remotely without logs...

**Comment by osm0sis** [comment]
I don't see anything in the boot.img that would be problematic:

```
Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers

Supplied image: boot.img

Setting up work folders...

Image type: AOSP

Footer with "SEAndroid" type detected.

Splitting image to "split_img/"...
ANDROID! magic found at: 0
BOARD_KERNEL_CMDLINE console=null androidboot.hardware=qcom user_debug=23 msm_rtb.filter=0x3F ehci-hcd.park=3 androidboot.bootdevice=7824900.sdhci androidboot.selinux=permissive buildvariant=userdebug
BOARD_KERNEL_BASE 0x80000000
BOARD_NAME 
BOARD_PAGE_SIZE 2048
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x01000000
BOARD_SECOND_OFFSET 0x00f00000
BOARD_TAGS_OFFSET 0x00000100
BOARD_OS_VERSION 10.0.0
BOARD_OS_PATCH_LEVEL 2021-10
BOARD_DT_SIZE 722944

Unpacking ramdisk to "ramdisk/"...

Compression used: gzip
2696 blocks

Done!
```

2SI ramdisk with init and fstab.qcom.

Is this a 64bit device? The magisk_patched.img only contains magisk32.xz in overlay.d

**Comment by daywalk3r666** [comment]
sry no adb connection at this stage. no its arm32 devive, sry haven't found the 23001.
[magisk_patched-23000_IJfuf.img.zip](https://github.com/topjohnwu/Magisk/files/7450617/magisk_patched-23000_IJfuf.img.zip)
idk if this maybe helps. here is the kernel source
https://gitea.jenslody.de/jens/android_kernel_samsung_msm8916

**Comment by osm0sis** [comment]
app-debug.apk here is 23001: https://github.com/topjohnwu/magisk-files/commit/4f737b70868eb3f8b71e48518f919819cbf5ad63

**Comment by daywalk3r666** [comment]
[23001.zip](https://github.com/topjohnwu/Magisk/files/7450660/23001.zip)

**Comment by daywalk3r666** [comment]
[last_log.txt](https://github.com/topjohnwu/Magisk/files/7451083/last_log.txt)
 This is the recovery log. line 1601 is the beginning of installing magisk canary 23011

**Comment by osm0sis** [comment]
`diff magisk_install_log_2021-11-01T04.55.03Z.log magisk_install_log_2021-10-31T09.34.16Z.log > diff.txt`:
```
2c2
< - Installing: f822ca5b (23001)
---
> - Installing: e3f63994 (23011)
17c17,18
< KERNEL_FMT      [raw]
---
> ZIMAGE_KERNEL
> KERNEL_FMT      [gzip]
21d21
< Loading cpio: [ramdisk.cpio]
22a23
> Loading cpio: [ramdisk.cpio]
53c54,55
< KERNEL_FMT      [raw]
---
> ZIMAGE_KERNEL
> KERNEL_FMT      [gzip]
60c62
< RAMDISK_SZ      [1022922]
---
> RAMDISK_SZ      [1042639]
68c70
< CHECKSUM        [2e720b147d142ac17e0b0bd20099be747546c30e000000000000000000000000]
---
> CHECKSUM        [f5b628066a7e3ba2ccb2ea5b80eef56d60f63ed3000000000000000000000000]
72c74
<  /storage/emulated/0/Download/magisk_patched-23001_KRdzl.img 
---
>  /storage/emulated/0/Download/magisk_patched-23011_qTJmQ.img 
```

**Comment by daywalk3r666** [comment]
Ok thanks for your help. Then i will wait for a fix.

**Comment by osm0sis** [comment]
@chaosmaster, any chance you've got time to take a look here? I believe ZIMAGE_KERNEL was your baby. 🤔

**Comment by chaosmaster** [comment]
The kernel indeed appears to be a zImage which was previously detected as RAW and could not be patched at all.
The kernel looking empty for some part should be the result of zopfli recompression.
I'll have to take a closer look to see why the recompressed kernel won't boot.

**Comment by osm0sis** [comment]
Because it worked before so it must not need the zimage patching, no?

**Comment by chaosmaster** [comment]
Yes if it worked before without zImage support, the kernel probably doesn't require any patching.
I'll take a closer look at it.

**Comment by chaosmaster** [comment]
It seems the image is a zImage but with an xz-compressed kernel instead of gzip (so xzImage?).
This results in a 0-byte kernel during unpack stage which explains the empty kernel-space in the final image.

**Comment by chaosmaster** [comment]
@daywalk3r666 can you test this?
https://github.com/topjohnwu/Magisk/actions/runs/1417505056

**Comment by daywalk3r666** [comment]
> @daywalk3r666 can you test this? https://github.com/topjohnwu/Magisk/actions/runs/1417505056

thx this fix my issue
![Screenshot_20211103-172400_Magisk](https://user-images.githubusercontent.com/15938117/140101451-88b34401-a6a0-4c72-b0ab-7c858ded88f3.png)

**Comment by osm0sis** [comment]
It's not merged yet. 😉
