### ISSUE TITLE
magiskinit regression between 23010 and 23011 after 50710c72

### ISSUE THREAD

**Issue by WillowSauceR** [topjohnwu/Magisk#4853]
Edit: Commit found to be the breaking change is https://github.com/topjohnwu/Magisk/commit/50710c72ad7a1c67879319bb1e37c33fdf7166de

I updated magisk from the CANARY channel as usual, but restarted after completing the "direct installation" and lost everything. It was as if the boot had not been modified. Later, I tried to extract the original boot and patched it and then flashed it with twrp, but it didn't work. But the old version (20310 and before) everything is OK

direct installation:
![Screenshot_2021-10-31-00-59-41-811_com topjohnwu magisk](https://user-images.githubusercontent.com/63277109/139543561-413609d9-a4c7-40b3-bdca-0acd45ac9da3.jpg)
Select and Patch a File
![Screenshot_2021-10-31-01-01-26-386_com 
topjohnwu magisk](https://user-images.githubusercontent.com/63277109/139543566-803bb084-df4a-4ad1-aa77-fdfdd0e4d5de.jpg)

Device: Redmi Note 9 5G
Android version:11
Magisk version name: 13352d49
Magisk version code: 23011

**Comment by WillowSauceR** [comment]
logs in magisk app
[magisk_log_2021-10-31T01_51_05Z.log](https://github.com/topjohnwu/Magisk/files/7447326/magisk_log_2021-10-31T01_51_05Z

**Comment by canyie** [comment]
logs link 404

**Comment by WillowSauceR** [comment]
Okay, do I need to upload anything else?

**Comment by WillowSauceR** [comment]
After the problem occurred, I downloaded many versions from action, and finally found that the last working version was [Magisk Build #817](https://github.com/topjohnwu/Magisk/actions/runs/1384103977)
log file: 
[magisk_log_2021-10-31T16_33_48Z.log](https://github.com/topjohnwu/Magisk/files/7448374/magisk_log_2021-10-31T16_33_48Z.log)


[Magisk Build #818](https://github.com/topjohnwu/Magisk/actions/runs/1384593861) / [commit 50710c7](https://github.com/topjohnwu/Magisk/commit/50710c72ad7a1c67879319bb1e37c33fdf7166de) unable to work properly

**Comment by Gong-Mi** [comment]
➕1
 23011 Root did not start successfully

**Comment by Gong-Mi** [comment]
可以用中文吗

Install to Inactive Slot (After OTA)
This method installation cannot start magisk root

**Comment by Gong-Mi** [comment]
765 Android 11
 Can

**Comment by WillowSauceR** [comment]
> 可以用中文吗
> 
> Install to Inactive Slot (After OTA) This method installation cannot start magisk root

是啊，无论怎么样都无法在新版本[commit 50710c7](https://github.com/topjohnwu/Magisk/commit/50710c72ad7a1c67879319bb1e37c33fdf7166de)或者更新的版本上正常启用root和模块，不过被修补过的boot倒是完成了关闭开机校验的任务，我的twrp在开机后没有被官方rec覆盖

Yes, It can't enable root and modules normally on the version [commit 50710c7](https://github.com/topjohnwu/Magisk/commit/50710c72ad7a1c67879319bb1e37c33fdf7166de) or newer no matter what, but the patched boot has completed the task of turning off the boot verification. My TWRP is not overwritten by the official MIUI recovery after booting.

**Comment by Gong-Mi** [comment]
应该是mtk安卓11的问题
我 k35-765-安卓11就没有问题。


It should be an issue with MTK Android 11 
No problems with my K35-765-Android 11's

**Comment by Gong-Mi** [comment]
然后重新刷会23010的boot就能启动root

Then re-brush the 23010 boot to start the root

**Comment by canyie** [comment]
Reviewed this commit with @yujincheng08 , nothing found. May I have your `/proc/cmdline` file? 

看了一遍这个 commit 没找到什么特别的东西，能上传 `/proc/cmdline` 这个文件看看吗？

**Comment by WillowSauceR** [comment]
> Reviewed this commit with @yujincheng08 , nothing found. May I have your `/proc/cmdline` file?
> 
> 看了一遍这个 commit 没找到什么特别的东西，能上传 `/proc/cmdline` 这个文件看看吗？

console=tty0 console=ttyS0,921600n1 root=/dev/ram vmalloc=400M slub_debug=OFZPU swiotlb=noforce initcall_debug=1 firmware_class.path=/vendor/firmware page_owner=on loop.max_part=7 has_battery_removed=0 ramoops.mem_address=0x4d010000 ramoops.mem_size=0xe0000 ramoops.pmsg_size=0x10000 ramoops.console_size=0x40000 androidboot.boot_devices=bootdevice,soc/11230000.mmc,11230000.mmc,soc/11270000.ufshci,11270000.ufshci ramoops.mem_address=0x4d010000 ramoops.mem_size=0xe0000 ramoops.pmsg_size=0x10000 ramoops.console_size=0x40000 bootopt=64S3,32N2,64N2 buildvariant=user root=/dev/ram  androidboot.verifiedbootstate=orange androidboot.atm=disabled androidboot.meta_log_disable=0 mtk_printk_ctrl.disable_uart=1 androidboot.serialno=ojy5fmcmmzkfea8p androidboot.bootreason=reboot androidboot.hwc=CN androidboot.hwlevel=MP androidboot.hwversion=1.9.0 androidboot.secureboot=1 androidboot.dp=7 androidboot.chipid=0x4cacc276811fcc2ab34de44bcdd59413 androidboot.cpuid=0x4cacc276811fcc2ab34de44bcdd59413e5d05dc9b269e65187aa5e7b gpt=1 usb2jtag_mode=0 androidboot.dtb_idx=0 androidboot.dtbo_idx=0

**Comment by yujincheng08** [comment]
```
<12>[    2.289104] .(5)[1:init]magiskinit: open: /proc/bootconfig failed with 2: No such file or directory
<12>[    2.289572] .(5)[1:init]magiskinit: fopen:  failed with 2: No such file or directory
<12>[    2.289585] .(5)[1:init]magiskinit: fopen:  failed with 2: No such file or directory
```

**Comment by yujincheng08** [comment]
Spent two hours for a typo :)

**Comment by WillowSauceR** [comment]
I downloaded and used the [Build #876](https://github.com/topjohnwu/Magisk/actions/runs/1412090922) version in Action. After flashing patched boot, everything is normal and all functions can be used normally.

**Comment by Gong-Mi** [comment]
OKOK
No problem.
