### ISSUE TITLE
C6bank detects root magisk

### ISSUE THREAD

**Issue by Robloxy2moon** [topjohnwu/Magisk#4866]
I used the canary, zygisk and denial version and nothing works   I've had problems with this database and unfortunately they can detect root magisk on the system. 

app: c6 bank

Device: Poco X3 nfc
Android version:11
Magisk version name: 23.1
Magisk version code: ea75a09f

**Comment by Didgeridoohan** [comment]
@Robloxy2moon Apart from #1152, I just tested that app on Magisk build 23012 and had no issues starting it without it detecting root.
https://www.didgeridoohan.com/magisk/MagiskHide#hn_Hiding_root_from_apps
