### ISSUE TITLE
Only TWRP install works, bootloop in Realme 8 RMX3085 after installing patched boot.img

### ISSUE THREAD

**Issue by EngRudhy** [topjohnwu/Magisk#4868]
Hi I faced bootloop

Device: Realme 8 RMX3085
Android version: 11
Magisk version name: canary
Magisk version code: 23011

**Comment by osm0sis** [comment]
Last working Canary version? boot.img? Patching log? last_kmsg/console-ramoops after the bootloop?

**Comment by EngRudhy** [comment]
I do not know how to get the last_kmsg/console-ramoops

and the Patching log you mean in the magisk app ?
Canary version : d232cba0 ( 23012 )

Original boot.img :  [boot.zip](https://github.com/topjohnwu/Magisk/files/7485704/boot.zip)
Patched boot.img : [magisk_patched-23012_8Pta9.zip](https://github.com/topjohnwu/Magisk/files/7485711/magisk_patched-23012_8Pta9.zip)

I can send you any else information you need please help me or guide me

**Comment by EngRudhy** [comment]
you mean this log ? :![Logs](https://user-images.githubusercontent.com/40672066/140506830-d42aa383-f72c-41b6-b24a-be0d0dbc8003.jpg)

**Comment by osm0sis** [comment]
No, we need logs of the patching process, and after it falls to boot.

**Comment by EngRudhy** [comment]
Yes this is the logs

patching logs : [magisk_install_log_2021-11-05T23_17_50Z.log](https://github.com/topjohnwu/Magisk/files/7488759/magisk_install_log_2021-11-05T23_17_50Z.log)
 
after rebooting logs : [magisk_log_2021-11-05T23_29_04Z.log](https://github.com/topjohnwu/Magisk/files/7488764/magisk_log_2021-11-05T23_29_04Z.log)

**Comment by osm0sis** [comment]
Ah well you've got the "ownership" issue, for one:
```
cp: can't preserve ownership of 'busybox': Operation not permitted
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
```

**Comment by EngRudhy** [comment]
And is this something I can fix or should I surrender ):

**Comment by osm0sis** [comment]
I noticed the 00 -> 03 issue in your final magisk_patched.img vs. your original boot.img as well, so you could try the command here on your magisk_patched.img to see if it gets it working: https://github.com/topjohnwu/Magisk/issues/4447#issuecomment-907622256

**Comment by EngRudhy** [comment]
@osm0sis I have edit the patched boot and try still the same Issue !
Any other Ideas :😅

**Comment by osm0sis** [comment]
Nope, we need dmesg of the failing boot or we likely won't be able to help you.

**Comment by osm0sis** [comment]
One last idea, did you try reflashing the ROM's vbmeta with `fastboot flash vbmeta --disable-verity --disable-verification vbmeta.img`

Sometimes that's necessary for a device to accept modified images.

**Comment by EngRudhy** [comment]
Already do this and also bootloop !

Now I am working on a TWRP for my device since it is not supported and the twrp is not released
I am working on it from zero hope I succeed after all 👍

**Comment by osm0sis** [comment]
Try 23013?

**Comment by EngRudhy** [comment]
@osm0sis  Hi been a while 
the twrp is working now and I am able to pull the kmsg log is that helpful

**Comment by EngRudhy** [comment]
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/7498006/dmesg.txt)
[logcat.txt](https://github.com/topjohnwu/Magisk/files/7498008/logcat.txt)

**Comment by EngRudhy** [comment]
I have solved the problem By using TWRP-Eng  and magisk canary version 23013 !

**Comment by EngRudhy** [comment]
I have solve this By using TWRP that I made it and using Magisk (23013)
Thank you

**Comment by osm0sis** [comment]
So you just needed to Magisk patch to recovery partition? Or are you saying Magisk patched things differently when installed from TWRP?

**Comment by EngRudhy** [comment]
the magisk_patched.img didn't work 

the  Magisk installing through the TWRP Is worked

**Comment by osm0sis** [comment]
Gonna need a log from the Magisk app and from TWRP then.

**Comment by osm0sis** [comment]
Alright, closing this without further requested info from @EngRudhy

**Comment by minhas0** [comment]
Hey, how did you unlock your BL, I couldn't do it, my device was just rebooting without unlocking BL

**Comment by EngRudhy** [comment]
@minhas0 
Use the last version of  MTKuniversal

**Comment by Vignesh5633** [comment]
Hey my device rmx3241
I also face bootloop after flashing patched boot.img even when in twrp

**Comment by 124sami** [comment]
Can anyone tell me a safe way to unlock RMX3085 bootloader without data loss ?
