### ISSUE TITLE
Turn on Zygisk makes all apps crashed when launch on Windows Subsystem for Android

### ISSUE THREAD

**Issue by someone5678** [topjohnwu/Magisk#4872]
If you turn on Zygisk on Magisk app on WSA all apps immediately crashed when launch.
Only notification can be recieved.

By reverting this [commit](https://github.com/topjohnwu/Magisk/commit/d232cba02ded4dff4c1ccdc9e6180622926f49c8) fix the issue.

Device: Windows Subsystem for Android
Android version: Android 11
Magisk version name: canary
Magisk version code: 23012

**Comment by topjohnwu** [comment]
This should be addressed in 63f670fc3696f8a824d77754097e546a4c7bf45e
