### ISSUE TITLE
OnePlus 5T canary 23012 doesn't display in my modules in the search box,

### ISSUE THREAD

**Issue by Tatuatul** [topjohnwu/Magisk#4874]
doesn't display in my modules in the search box, whatever I look for doesn't show me anything.
example: I'm looking for busybox, riru core, can't find anything, whatever I look for.
![WhatsApp Image 2021-11-02 at 23 24 07](https://user-images.githubusercontent.com/75882179/139953982-80976bc0-a776-4929-8358-6e6287ebf0f6.jpeg)

Device: OnePlus 5T
Android version: 9
Magisk version name: canary
Magisk version code: 23012

**Comment by Didgeridoohan** [comment]
Do you happen to be talking about this part of the changelog:
`[App] Downloading modules within the Magisk app is removed`

For details on the reasoning behind that:
https://topjohnwu.medium.com/state-of-magisk-2021-fe29fdaee458

**Comment by Tatuatul** [comment]
I understand, thank you, what alternatives do we have to magisk if it doesn't work anymore?

**Comment by osm0sis** [comment]
I thought you said it didn't show your installed modules

**Comment by osm0sis** [comment]
Magisk works fine, you just have to install modules manually using the zips, obviously.
