### ISSUE TITLE
Banking app Vipps detecting root - Zygisk enabled with Enforce Denylist

### ISSUE THREAD

**Issue by niket67** [topjohnwu/Magisk#4875]
Device: OnePlus 8 Pro
Android version: 11
Magisk version name: d232cba0
Magisk version code: 23012

Norwegian banking app: Vipps is detecting root all of a sudden (or after app update), when configured in Zygisk denylist.
Vipps app version: 2.101.0

I am using the latest magisk canary build.

**Comment by Didgeridoohan** [comment]
First of all: #1152 (don't ask about root detection in the github issues)
Second: No issues here on Canary. The app starts as soon as added to the Deny list.

You might want to close this (it'll be closed anyway soon enough), and then go check here for tips:
https://www.didgeridoohan.com/magisk/MagiskHide#hn_Hiding_root_from_apps

If you need further assistance you've got XDA.

**Comment by niket67** [comment]
Done based on rules.

**Comment by niket67** [comment]
> First of all: #1152 (don't ask about root detection in the github issues) Second: No issues here on Canary. The app starts as soon as added to the Deny list.
> 
> You might want to close this (it'll be closed anyway soon enough), and then go check here for tips: https://www.didgeridoohan.com/magisk/MagiskHide#hn_Hiding_root_from_apps
> 
> If you need further assistance you've got XDA.

Noted,
Thanks for the info, I'll read up on the article you posted,
