### ISSUE TITLE
Denylist

### ISSUE THREAD

**Issue by cocka11** [topjohnwu/Magisk#4879]
Device: Xiaomi redmi 7
Android version:Lineage 18.1
Magisk version name: d232cba0
Magisk version code: 23012

denylist does not work does not hide root from applications.

Log
https://www.mediafire.com/file/wxyawhskeoxhte9/magisk_log_2021-11-03T21_11_31Z.log/file

**Comment by Didgeridoohan** [comment]
First of all: #1152 

Second: it does, but it's very likely that any apps looking for root detect other stuff than just Magisk.

Close this issue (it'll get closed soon anyway), take a look here for tips (and if you need more help you're better off heading over to XDA):
https://www.didgeridoohan.com/magisk/MagiskHide#hn_Hiding_root_from_apps

**Comment by 0purple** [comment]
https://github.com/vvb2060/riru-unshare

@cocka11

**Comment by cocka11** [comment]
Thanks bro
