### ISSUE TITLE
"Installed" still "N/A" after flashing

### ISSUE THREAD

**Issue by thenicnic** [topjohnwu/Magisk#4884]
Device: Sony Xperia Z3 Compact (D5803)
Android version: 11 (CarbonROM 9)
Magisk version name: 23.0
Magisk version code: 23000

Great instructions but unfortunately I haven't been successful in installing Magisk for my latest configuration. I have the latest CarbonROM 9 build (Android 11-based; "CARBON-CR-9.0-R-WEEKLY-z3c-20211027-0359.zip") on Sony Xperia Z3 Compact and TWRP 3.2.3-0. Ramdisk: "Yes".

Tried flashing with APK renamed to ZIP, the log gives me no error but Magisk 23.0 app says "Install: N/A"

Same with the 7 MB "boot.img" extracted from the above CarbonROM ZIP and patched with Magisk app: After successful flash it takes no effect.

target didn't report max-download-size
sending 'boot' (7134 KB)...
OKAY [  0.232s]
writing 'boot'...
OKAY [  0.480s]
finished. total time: 0.730s

But the log shows a "can't preserve ownership" error at copying, is this important? Log and image attached.

**Comment by diresi** [comment]
Hmm. I still have this issue with canary Magisk 23014. I remember that it used to work some months ago, but I somehow factory reset and reinstalled LOS18 and can't seem to properly install Magisk again :/

**Comment by diresi** [comment]
> Hmm. I still have this issue with canary Magisk 23014. I remember that it used to work some months ago, but I somehow factory reset and reinstalled LOS18 and can't seem to properly install Magisk again :/

I don't know how I messed things up, but starting anew and patching LOS boot.img worked now. Sorry for the noise, thanks for all your work!
