### ISSUE TITLE
Realme XT root problems

### ISSUE THREAD

**Issue by M4sterC** [topjohnwu/Magisk#4890]
Device: Realme XT-RMX1921 
Android version:10
Magisk version name: d232cba0
Magisk version code: 23012

aways that i try to make root the device does not start after flash the magisk on twrp, it only give me a message saying that the boot.image file was destroyed, i`ve already tried different versions, and it aways do the same, i have tried to install with a computer too, patching the boot file with the magisk app, and flashing with fastboot tools, but it also does not work.
My device is on the RMX1921_11_C.14 rom, and android 10, can anyone pls help me ?

**Comment by osm0sis** [comment]
Another Realme device.. any chance your issue is the same as #4868 ?

**Comment by M4sterC** [comment]
[magisk_install_log_2021-11-05T233514Z.log](https://github.com/topjohnwu/Magisk/files/7489732/magisk_install_log_2021-11-05T233514Z.log)
[magisk_patched-23000_TTrpF.zip](https://github.com/topjohnwu/Magisk/files/7489733/magisk_patched-23000_TTrpF.zip)
[original boot file.zip](https://github.com/topjohnwu/Magisk/files/7489734/original.boot.file.zip)

here are the patch log, the patched boot img, and the original boot.img, when i flash the patched img, the device got bricked with this message 

![error](https://user-images.githubusercontent.com/93799128/140595202-cc138647-091a-4587-82b9-474d267519b5.png)

it happens when i try to flash with twrp, and with a computer, the process of flashing does not present any error, tell me if you need the log of this process too

**Comment by osm0sis** [comment]
That says 23000, you need to be testing with latest Canary 23012 like your issue report says.

**Comment by osm0sis** [comment]
Ah crap, hdr_v1 SAR with no ramdisk, hardest to support. 😕

```

Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers

Supplied image: boot.img

Setting up work folders...

Image type: AOSP

Signature with "AVBv2" type detected.

Splitting image to "split_img/"...
ANDROID! magic found at: 0
BOARD_KERNEL_CMDLINE console=ttyMSM0,115200n8 earlycon=msm_geni_serial,0xA90000 androidboot.hardware=qcom androidboot.console=ttyMSM0 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 service_locator.enable=1 androidboot.configfs=true androidboot.usbcontroller=a600000.dwc3 swiotlb=1 loop.max_part=7 buildvariant=user
BOARD_KERNEL_BASE 0x00000000
BOARD_NAME 
BOARD_PAGE_SIZE 4096
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x01000000
BOARD_SECOND_OFFSET 0x00f00000
BOARD_TAGS_OFFSET 0x00000100
BOARD_OS_VERSION 10.0.0
BOARD_OS_PATCH_LEVEL 2021-07
BOARD_HEADER_VERSION 1
BOARD_HEADER_SIZE 1648

Warning: No ramdisk found to be unpacked!

Done!
```

**Comment by osm0sis** [comment]
Looks like you have recovery mode set in your /.backup/.magisk, did you set this when you patched it?

```
KEEPVERITY=true
KEEPFORCEENCRYPT=true
RECOVERYMODE=true
SHA1=71ddf18c46f45200d08d9f8bb1694904523b9871
```

**Comment by M4sterC** [comment]
ok, sorry here are the files you ask, in the correct version version, the error still the same,  the log of patching process, without recovery this time, and the patched boot img, i have just tried flash right now, and get the same error 

[magisk_install_log_2021-11-06T000300Z.log](https://github.com/topjohnwu/Magisk/files/7489783/magisk_install_log_2021-11-06T000300Z.log)
[magisk_patched-23012_2feEs.zip](https://github.com/topjohnwu/Magisk/files/7489784/magisk_patched-23012_2feEs.zip)
 the log of patching process, without recovery this time, and the patched boot img, i have just tried flash right now, and the error is the same

**Comment by osm0sis** [comment]
```
cp: can't preserve ownership of 'busybox': Operation not permitted
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
```
Again..

And the kernel_dtb segfault. Try again with the Actions CI build app-debug.apk (in the artifacts zip) here since it'll have that dtb fix, then another patching log and magisk_patched.img please: https://github.com/topjohnwu/Magisk/actions/runs/1427745089

**Comment by M4sterC** [comment]
[magisk_install_log_2021-11-06T003935Z.log](https://github.com/topjohnwu/Magisk/files/7489823/magisk_install_log_2021-11-06T003935Z.log)
[magisk_patched-23012_xmL3e.zip](https://github.com/topjohnwu/Magisk/files/7489824/magisk_patched-23012_xmL3e.zip)

**Comment by osm0sis** [comment]
Okay, last idea for now. Try the command here on your magisk_patched.img to see if it gets it working: https://github.com/topjohnwu/Magisk/issues/4447#issuecomment-907622256

**Comment by M4sterC** [comment]
any suggest where i can find my recovery.img ?, i have already install twrp, and i dont have the stock recovery backup

**Comment by osm0sis** [comment]
No idea. You could try patching the TWRP img though, since that should work too.

Did the hexpatch work? That's the important thing to try first.

**Comment by M4sterC** [comment]
Yes, i tried the hexpatch on the boot.img and it dont work same error, already tried on the twrp recovey image, once that i dont have the stock recovery of my device, and, same error

**Comment by M4sterC** [comment]
Just to say, on both logs, recovery and boot.img, the logs get same ownership errors

**Comment by osm0sis** [comment]
Yeah I think that's just unrooted patching being weird and doesn't actually affect the patching itself.

**Comment by osm0sis** [comment]
Maybe try reflashing the ROM's vbmeta with fastboot flash vbmeta --disable-verity --disable-verification vbmeta.img

Sometimes that's necessary for a device to accept modified images.

**Comment by M4sterC** [comment]
i tried reflash the vbmeta.img, but i only got this message : 
``C:\adb\fastboot.exe: unrecognised option `--disable-verity'``

**Comment by M4sterC** [comment]
FINALLY IT WORKED, THANKS A LOT, I HAVE  JUST FLASHED THE VBMETA IMAGE WITH THE COMMAND YOU SAID, AND THEN FLASHED MAGISK.ZIP WITH TWRP, AND IT WORKED PERFECTLY

**Comment by osm0sis** [comment]
Ah, so basically just an initial install method knowledge issue. 😝

I think that command does need to be added to the Magisk documentation, so I'll look into that.
