### ISSUE TITLE
Magisk app force closed during collecting list of apps in configure deny list

### ISSUE THREAD

**Issue by zputnyq** [topjohnwu/Magisk#4895]
Device: Xperia M4 (E2306)
Android version: stock 6.0.1
Magisk version name: 258e89c9
Magisk version code: 23013

After activating both zygisk & enforce denylist then rebooting my device, I tried to put gms to denylist. But when I entered "configure denylist" section, it was loading the list & then force closed the magisk app.

Logcat attached, hope it's the correct log & could help

[logcat.txt](https://github.com/topjohnwu/Magisk/files/7491970/logcat.txt)
<!--

**Comment by osm0sis** [comment]
I found enabling DenyList doesn't work the first time you try, before installing 23010+, and once rebooted then it'll "stick". Maybe try toggling it off and on again?

**Comment by zputnyq** [comment]
> I found enabling DenyList doesn't "stick" the first time you try after updating the app to 23010+ but before Direct Installing 23010+. Once rebooted into 23010+ then it'll "stick". Maybe try toggling it off and on again?

Sorry for my bad english, I meant magisk app force closed during collecting list of app in configure denylist

I tried toggling zygisk & enforce denylist off & on doesn't solve this issue on my device. Magisk app still force closed during collecting app list.

**Comment by osm0sis** [comment]
Ah okay, that doesn't happen for me here. Can you provide the Magisk app log as well?

**Comment by zputnyq** [comment]
> Ah okay, that doesn't happen for me here. Can you provide the Magisk app log as well?

Here's the magisk app's log
[magisk_log_2021-11-07T18:11:51Z.log](https://github.com/topjohnwu/Magisk/files/7492147/magisk_log_2021-11-07T18.11.51Z.log)

**Comment by yujincheng08** [comment]
Should use `ProcessCompat.isApplicationUid` instead.
