### ISSUE TITLE
Build binary error 

### ISSUE THREAD

**Issue by ichason** [topjohnwu/Magisk#4904]
build binary error :
C:\Users\cc\Desktop\Magisks\1\Magisk>python build.py binary
Building binaries: magisk magiskinit magiskboot busybox
jni/magiskboot/compress.cpp:124:59: error: use of undeclared identifier 'crc32_z'; did you mean 'crc32'?
zo({}), out(nullptr), outsize(0), bp(0), crcvalue(crc32_z(0L, Z_NULL, 0)), in_size(0) {
^~~~~~~
crc32
jni/external/zlib\zlib.h:1780:23: note: 'crc32' declared here
ZEXTERN uLong ZEXPORT crc32 OF((uLong crc, const Bytef *buf, uInt len));
^
jni/magiskboot/compress.cpp:181:20: error: use of undeclared identifier 'crc32_z'; did you mean 'crc32'?
crcvalue = crc32_z(crcvalue, buf, len);
^~~~~~~
crc32
jni/external/zlib\zlib.h:1780:23: note: 'crc32' declared here
ZEXTERN uLong ZEXPORT crc32 OF((uLong crc, const Bytef *buf, uInt len));
^
2 errors generated.
make: *** [C:/Users/cc/AppData/Local/Android/Sdk/ndk/magisk/build//../build/core/build-binary.mk:478: obj/local/armeabi-v7a/objs/magiskboot/magiskboot/compress.o] Error 1
make: *** Waiting for unfinished jobs....
Build binary failed!

What's the problem?

Device: No (AS 4.3 Build And Java Version=11)
Android version:7.0.1
Magisk version name: 97c1e18
Magisk version code: 23013
------------------------------------------------------------------------

When I manually modify the code, this error has passed, but the next problem follows. Here are some errors, and the rest are similar  

I manually replace "crc32_z" with "CRC32", and the problem is over：

`C:/Users/cc/AppData/Local/Android/Sdk/ndk/magisk/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin\ld: ./o
bj/local/x86/objs\utils\missing.o: previous definition here
C:/Users/cc/AppData/Local/Android/Sdk/ndk/magisk/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin\ld: err
or: C:/Users/bonree/AppData/Local/Android/Sdk/ndk/magisk/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/lib/i686-linux-android/21/libc.a(stdio.o): multiple definit
ion of 'getline'
C:/Users/cc/AppData/Local/Android/Sdk/ndk/magisk/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin\ld: ./o
bj/local/x86/objs\utils\missing.o: previous definition here
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [C:/Users/cc/AppData/Local/Android/Sdk/ndk/magisk/build//../build/core/build-binary.mk:738: obj/local/x86/magiskboot] Error 1
[arm64-v8a] Executable     : magiskboot

`
------
Here are my steps. Please check them for me:
1 .git clone --recurse-submodules https://github.com/topjohnwu/Magisk.git
    However, I failed to download the files in. gitmodules because of the network. Then I manually downloaded them and 
    put them in the native / JNI / external and tools / termux elf cleaner directories;

2. build.py ndk ， succeed~
3. build.py binary will prompt the above error

python：3.8，java 11

Please~

**Comment by ichason** [comment]
hello?

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/actions/workflows/build.yml?query=event%3Apush
