### ISSUE TITLE
Suggestion: Dialog for custom Safetynet API Key

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#491]
Hey @topjohnwu

Well.. As Google now limits the requests/day, it might be a nice idea for individuals to be able to use their own API Key in the Magisk app.

Not only it'll reduce the load on the main app API key, but it will be a nice workaround for the limit.

It's pretty easy and straightforward process for everyone to obtain an API key just by following some Readme that I'm pretty sure it'll be written by @Didgeridoohan xD

**Comment by topjohnwu** [comment]
I'm pretty confident that the main key shall never have a quota issue, I'll consider this option once things aren't working out properly 👍
