### ISSUE TITLE
LineageOS 18.1 no sound and no sensors after booting with Magisk

### ISSUE THREAD

**Issue by powerman** [topjohnwu/Magisk#4911]
Device: SAMSUNG Galaxy Tab S5e SM-T720
Android version: 11 `lineage-18.1-20211101-nightly-gts4lvwifi-signed.zip`
Magisk version name: 258e89c9
Magisk version code: 23013

This device requires installing Magisk into recovery.

I've used Magisk app to patch `twrp-3.5.2_9-0-gts4lvwifi.img`, then renamed it to `recovery.img`, packed using tar and flashed using Odin. Next I installed LineageOS from recovery using official guide, without any addons.

As long as I use installed LineageOS without trying to boot it through recovery (i.e. without activating Magisk) - everything works just fine. But if I boot through recovery for the first time I get Magisk (which is works fine!) but I *lose sound and sensors* (e.g. screen orientation detection doesn't work anymore).

Only way to restore sound and sensors after that - format data from TWRP and install LineageOS. Anything else doesn't work - booting from system instead of recovery (i.e. without Magisk) or data wipe from lineage settings.

I run `adb logcat -d` after rebooting LineageOS before first boot through recovery/Magisk, see `logcat2.txt`.
Then I did the same after booting through recovery and then rebooting once again from recovery (with Magisk), see `logcat6magisk.txt`.
Then I did the same after booting through recovery and then rebooting once again from system (without Magisk, to make it easier to see the differences), see `logcat7.txt`.
[logcat2.txt](https://github.com/topjohnwu/Magisk/files/7500856/logcat2.txt)
[logcat6magisk.txt](https://github.com/topjohnwu/Magisk/files/7500857/logcat6magisk.txt)
[logcat7.txt](https://github.com/topjohnwu/Magisk/files/7500858/logcat7.txt)

**Comment by powerman** [comment]
After reading #4394 I've tried (after Magisk uninstalled itself from recovery and I've once again installed LOS and booted once) to install canary app-debug.apk from TWRP instead of using recovery - and at a glance it worked!

P.S. Moreover, tablet is now booting several times faster and without needs to boot through recovery.

**Comment by powerman** [comment]
Not sure is this important, but every time I boot Magisk from recovery I get SELinux disabled, but now with Magisk on system SELinux is still in enforced mode.

**Comment by osm0sis** [comment]
When running from recovery you're running from TWRP's ramdisk, so I think you kind of inherited whatever hacks they used to get recovery working, like excluding modules/configs and using permissive.

I'd be interested to hear if it worked any better using Lineage OS Recovery, but glad it's working on boot partition now too.
