### ISSUE TITLE
Magisk fails to handle special sepolicy on Oculus Go

### ISSUE THREAD

**Issue by moocow1452** [topjohnwu/Magisk#4914]
Device:  Oculus Go (pacific)
Android version: 7.1.2
Magisk version name: 258e89c9
Magisk version code: 23013

Oculus released an unlocked build for the Oculus Go that allows user access to boot and system, as well as adb root, but not vbmeta or recovery. When patching Magisk into boot, it will flash, but on boot, it goes to a black void with a "no command" error on the display for about a minute, then goes to recovery and reboot immediately takes it back to recovery until the original boot.img is reflashed. I have a console-ramoops attached among  other things, but because reflashing boot.img wipes the file, and I cant get into the system without reflashing the good boot.img, I'm not sure how relevant it is to Magisk.

[magisk_install_log_2021-11-08T13.log](https://github.com/topjohnwu/Magisk/files/7500255/magisk_install_log_2021-11-08T13.log)
[console-ramoops.txt](https://github.com/topjohnwu/Magisk/files/7500256/console-ramoops.txt)
[boot.zip](https://github.com/topjohnwu/Magisk/files/7500257/boot.zip)
[proc-mounts.txt](https://github.com/topjohnwu/Magisk/files/7500260/proc-mounts.txt)
[magisk_patched-23013_FemzM.zip](https://github.com/topjohnwu/Magisk/files/7500261/magisk_patched-23013_FemzM.zip)

Thank you for your time.

**Comment by osm0sis** [comment]
Oh wow, it runs on Android 7.1? Rough...

I don't see any mention of Magisk in that console-ramoops, so it doesn't seem like it's from the failed boot, unfortunately.

**Comment by SARankDirector-Minecraft** [comment]
> You'll have to see if there's any way to get proper logs.. since it's so old maybe it has a boot.img ramdisk and you can make it adb insecure using AIK?

why do we need adb insecure if we can do adb root and adb shell

**Comment by osm0sis** [comment]
Yep you're probably right, hadn't reread his post.

**Comment by moocow1452** [comment]
Not sure I can get ADB from the bootloop, whatever crashes happens before adb starts up, or at least adb on my PC cannot find the device after the magisk flash. If reflashing the original boot.img is the only way to bring the device to a bootable state, but it wipes any logging data, is there a recommended way to stick a script in the Magiskified boot that will log kernel messages to /sdcard, so that the logs will survive a reflash, but those changes would not otherwise interfere with the installation attempt?

**Comment by osm0sis** [comment]
Maybe the adb insecure default.prop changes will allow you to connect earlier in the failed boot up.

**Comment by moocow1452** [comment]
No dice unfortunately. ADB still won't start before it crashes.

**Comment by osm0sis** [comment]
Well I'm fresh out of ideas. 😕🤷‍♂️

**Comment by moocow1452** [comment]
[magisk_log_2021-11-13T.log](https://github.com/topjohnwu/Magisk/files/7532774/magisk_log_2021-11-13T.log)
[magisk_log_2021-11-13T16.log](https://github.com/topjohnwu/Magisk/files/7532775/magisk_log_2021-11-13T16.log)
[magisk_patched-23014_cjK37.zip](https://github.com/topjohnwu/Magisk/files/7532776/magisk_patched-23014_cjK37.zip)
[magisk_install_log_2021-11-13T16.log](https://github.com/topjohnwu/Magisk/files/7532777/magisk_install_log_2021-11-13T16.log)

What happens is that I flash the magisk boot, and it goes into a bootloop with recovery or sticks me in the black void until I flash the old boot. At least, that's what happened until I did a factory reset, reflashed the unlocked sideload, and tried the new canary build. Now I have completely new behavior where it takes the Magisk boot, and is able to reboot into home, but it doesn't appear that anything changed, magisk doesn't have new permissions, and there's no last_ksmg or console-ramoops to send along, I got what I could if you see something interesting.

**Comment by canyie** [comment]
magisk app log is useless if not rooted. Run `adb bugreport` and upload the bugreport file, which may contains something interesting.

**Comment by moocow1452** [comment]
[bugreport-NGI77B-2021-11-16-16-34-42.zip](https://github.com/topjohnwu/Magisk/files/7549994/bugreport-NGI77B-2021-11-16-16-34-42.zip)
How does this look?

**Comment by canyie** [comment]
It looks too late... Set the "log buffer size" to the maximum value from developer options, reboot your device and run bugreport as early as possible.

**Comment by moocow1452** [comment]
[bugreport-NGI77B-2021-11-17-12-06-16.zip](https://github.com/topjohnwu/Magisk/files/7556563/bugreport-NGI77B-2021-11-17-12-06-16.zip)
Ran adb reboot & adb bugreport, this is what turned up.

**Comment by canyie** [comment]
Looks like magisk is not installed, can't find anything about magisk (even magiskinit) in your bugreport 🤔 
Just simply checked the patched boot.img and it looks good to me. Does `fastboot boot magisk_patched.img` works for you?

**Comment by moocow1452** [comment]
> Looks like magisk is not installed, can't find anything about magisk (even magiskinit) in your bugreport 🤔 Just simply checked the patched boot.img and it looks good to me. Does `fastboot boot magisk_patched.img` works for you?

[bugreport-NGI77B-2021-11-21-12-23-47.zip](https://github.com/topjohnwu/Magisk/files/7576728/bugreport-NGI77B-2021-11-21-12-23-47.zip)
[magisk_install_log_2021-11-21T.log](https://github.com/topjohnwu/Magisk/files/7576730/magisk_install_log_2021-11-21T.log)
[magisk_patched-23014_Ohbfs.zip](https://github.com/topjohnwu/Magisk/files/7576733/magisk_patched-23014_Ohbfs.zip)

Made everything fresh again. `fastboot boot magisk_patched-23014_Ohbfs.img` flashed a boot.img that was the size of the patched file. (19025KB) It gave the no connection error, then restarted and booted to Home, but it still seemed unrooted according to Magisk. Could it try to reconfigure itself, fail, then revert to the old boot? Or is that beyond it"s capacity?

**Comment by ChinaLinda** [comment]
same issue for me

**Comment by ChinaLinda** [comment]
More information. After reboot my Oculus Go after fastboot flash，the adb cannot work.

**Comment by moocow1452** [comment]
same behavior happens with the latest canary
[bugreport-NGI77B-2021-11-25-14-44-41.zip](https://github.com/topjohnwu/Magisk/files/7605045/bugreport-NGI77B-2021-11-25-14-44-41.zip)
.

**Comment by SARankDirector-Minecraft** [comment]
Any updates?

**Comment by canyie** [comment]
Finally I have another holiday... I can start debugging again...
Does [osm0sis's build](https://github.com/topjohnwu/Magisk/issues/4914#issuecomment-967348988) still causes your device bootloop? If not, does these properties change? What is the output of `getprop ro.secure` ?

**Comment by moocow1452** [comment]
> Finally I have another holiday... I can start debugging again... Does [osm0sis's build](https://github.com/topjohnwu/Magisk/issues/4914#issuecomment-967348988) still causes your device bootloop? If not, does these properties change? What is the output of `getprop ro.secure` ?

[bugreport-NGI77B-2021-12-03-23-30-39.zip](https://github.com/topjohnwu/Magisk/files/7653291/bugreport-NGI77B-2021-12-03-23-30-39.zip)

After letting it sit for about a minute in the No Command void, it gave me this bug report. Get prop ro.secure returned 1.

**Comment by canyie** [comment]
Wow, the properties not changed... It just looks like your device refuses modified boot.img... we cannot do anything if that... 
Maybe @osm0sis can make a patched image with `default.prop` changes but without magisk to confirm this?

**Comment by osm0sis** [comment]
Could it be some kind of evil, backported SAR or Treble where it's not the boot image ramdisk actually being used, despite this thing running on Android 7.1.2.

**Comment by osm0sis** [comment]
Took a closer look at the ramdisk and yup! It may actually be boot-as-recovery, making this a SAR device! That explains the prop changes failing.

So, the next move would be for @moocow1452 to try and use adb root to mount system partition rw and change the SAR /default.prop in the booted device with those adb insecure changes, then hopefully we can get logs from boottime with Magisk flashed.

**Comment by moocow1452** [comment]
> So, the next move would be for @moocow1452 to try and use adb root to remount system partition rw and change the SAR /default.prop in the booted device with those adb insecure changes, then hopefully he can get logs from early boottime with Magisk flashed.


Sounds great! I'm familiar with making those changes on a custom boot image and pushing it with fastboot, but how would I make those changes on the live device? Or am I misunderstanding you?

**Comment by moocow1452** [comment]
Checking in. It turns out default.prop was in root the whole time, so that's be being a dummy. 

I am getting a permission denied error when I try to alter the file or do anything top-level. I have done adb root and adb remount on my device, and even did "mount -o rw,remount /" for good measure. Maybe @ChinaLinda could have better luck? Is there another method I could try or is the answer that stock software cannot be rooted and it's time to get into the ROM game?

**Comment by osm0sis** [comment]
Recovery is in the boot.img, booted root directory is in the system partition. So remounting rw to edit booted system with adb root would be your only hope.

Was your /proc/mounts list above from after flashing Magisk, or before?

**Comment by ChinaLinda** [comment]
I have done adb root and adb remount on my device , the situation has not improved.

I tried to use supersu to root the device instead. It seems to have succeeded.  https://github.com/ChinaLinda/OculusGoEthernet/blob/main/add_super_su.md

**Comment by moocow1452** [comment]
`echo 0 > /sys/fs/selinux/enforce`

That did it, thanks @ChinaLinda 

I can replace the new default.prop, but now it's stuck on the boot screen. Is there a special chmod involved for default.prop?

**Comment by osm0sis** [comment]
Could be worth trying with 24304, original init handles a lot more now.

**Comment by moocow1452** [comment]
[magisk_log_2022-03-27.log](https://github.com/topjohnwu/Magisk/files/8359491/magisk_log_2022-03-27.log)
[magisk_patched-24304_2ogYZ.zip](https://github.com/topjohnwu/Magisk/files/8359496/magisk_patched-24304_2ogYZ.zip)
[magisk_install_log_2022-03-27T23.log](https://github.com/topjohnwu/Magisk/files/8359497/magisk_install_log_2022-03-27T23.log)
[bugreport-NGI77B-2022-03-27-23-51-41.zip](https://github.com/topjohnwu/Magisk/files/8359512/bugreport-NGI77B-2022-03-27-23-51-41.zip)


That's the latest Canary on a fresh install. I could try to get you the insecure logs as well if you think that would help. Looks like something might be going on with Busybox that wasn't before.

**Comment by osm0sis** [comment]
Yeah wait for 24305 so that the busybox issue gets resolved, then fresh logs including insecure would be good. 👍

**Comment by canyie** [comment]
> 24 14 0:15 /.magisk/rootdir/sepolicy /sepolicy rw,relatime shared:8 - tmpfs tmpfs rw,seclabel,size=1385244k,nr_inodes=346311,mode=755
25 14 0:15 /.magisk/rootdir/init.rc /init.rc rw,relatime shared:9 - tmpfs tmpfs rw,seclabel,size=1385244k,nr_inodes=346311,mode=755

Looks like Magisk is now working on your device except the busybox issue? At least latest MagiskInit can mount something, it's a good start.

**Comment by moocow1452** [comment]
Magisk doesn't say that it's working, nor does Amaze allow me to use root functionality, so I don't think everything is there. Still, progress is progress, and I can poke around more this weekend.

**Comment by osm0sis** [comment]
Definitely try with 24305 with fresh logs.

**Comment by moocow1452** [comment]
[bugreport-NGI77B-2022-04-03-19-32-33.zip](https://github.com/topjohnwu/Magisk/files/8405818/bugreport-NGI77B-2022-04-03-19-32-33.zip)
[magisk_install_log_2022-04-03T.log](https://github.com/topjohnwu/Magisk/files/8405819/magisk_install_log_2022-04-03T.log)
[magisk_log_2022-04-03-insecure.log](https://github.com/topjohnwu/Magisk/files/8405909/magisk_log_2022-04-03-insecure.log)
[magisk_log_2022-04-03T.log](https://github.com/topjohnwu/Magisk/files/8405820/magisk_log_2022-04-03T.log)
[bugreport-NGI77B-insecure.zip](https://github.com/topjohnwu/Magisk/files/8405908/bugreport-NGI77B-insecure.zip)

Here's what I could get this weekend. Hopefully one of these help?

**Comment by canyie** [comment]
```
<13>[    5.197064] init: Starting service 'V7kwwYCVy'...
<13>[    5.197556] init: Service 'V7kwwYCVy' (pid 539) forked success
<11>[    5.197775] init: cannot setexeccon('u:r:magisk:s0'): Invalid argument
```
Yeah! My guess is correct, sepolicy patch doesn't work!

```
<12>[    1.710675] magiskinit: Patching monolithic policy
<12>[    1.710686] magiskinit: Load policy from: /sepolicy
<12>[    1.733604] magiskinit: opendir: /sbin/.magisk/mirror/data/unencrypted/magisk failed with 2: No such file or directory
<12>[    1.733625] magiskinit: Dumping sepolicy to: [.magisk/rootdir/sepolicy]
<12>[    1.749437] magiskinit: Mount [.magisk/rootdir/sepolicy] -> [/sepolicy]
```
magiskinit doesn't report any error with sepolicy patching. Maybe your device loads sepolicy from a different path 🤔 Can you upload /init and /system/lib64/libselinux.so ?

**Comment by moocow1452** [comment]
[Requested Files.zip](https://github.com/topjohnwu/Magisk/files/8415011/Requested.Files.zip)
Here's what I was able to get.

**Comment by canyie** [comment]
https://github.com/canyie/Magisk/actions/runs/2094258424
How about this build? Download artifact, unzip it, and install app-debug.apk, patch boot image via the new magisk, and flash it.

**Comment by canyie** [comment]
![image](https://user-images.githubusercontent.com/31466456/161785772-cdc24f49-4b51-4c50-8921-9334745670b2.png)
Device will load /sepolicy.unlocked if androidboot.adb.rootable=1 and skip_initramfs (Legacy SAR) was given on the kernel cmdline. But I think we can just always hijack sepolicy.unlocked since we don't see other devices with this special behavior

**Comment by moocow1452** [comment]
[magisk_log_2022-04-05.log](https://github.com/topjohnwu/Magisk/files/8423596/magisk_log_2022-04-05.log)
[bugreport-NGI77B-2022-04-06-00-28-16.zip](https://github.com/topjohnwu/Magisk/files/8423597/bugreport-NGI77B-2022-04-06-00-28-16.zip)
[magisk_install_log_2022-04-05.log](https://github.com/topjohnwu/Magisk/files/8423598/magisk_install_log_2022-04-05.log)
Here's what I got. No obvious changes from within Magisk, still seems to be unrooted.

**Comment by canyie** [comment]
Does /sepolicy.unlocked exist on your device?

**Comment by canyie** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8425701/app-debug.zip)
Just noticed your device uses legacy SAR so the root partition is not writable. Please try this build.

**Comment by moocow1452** [comment]
> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/8425701/app-debug.zip) Just noticed your device uses legacy SAR so the root partition is not writable. Please try this build.

Good news, it worked. There is an issue with the Superuser prompts displaying properly, but that might be more of a big with Oculus TV and it not displaying properly in VR. It also seems to go away once it's restarted, don't know if the current workaround was supposed to be a one time deal. But progress is progress.

**Comment by canyie** [comment]
YEAH! UI problems on VR devices may have a very low priority to address, but anyway, we finally get the core functions worked.  I'm not good with UI, I will submit the fix to upstream, and let other devs increases the progress. 🚀

**Comment by osm0sis** [comment]
Sounds similar to the old OnePlus sepolicy_debug situation. Would just symlinking them work like it did there?

https://github.com/topjohnwu/Magisk/blob/master/native/jni/init/selinux.cpp#L33-L37

**Comment by canyie** [comment]
> Sounds similar to the old OnePlus sepolicy_debug situation. Would just symlinking them work like it did there?
> 
> https://github.com/topjohnwu/Magisk/blob/master/native/jni/init/selinux.cpp#L33-L37

Tried and didn't work. I think it's because the device is a SAR device so the root partition is not writable.

**Comment by osm0sis** [comment]
Ah right
