### ISSUE TITLE
Feature Request: Hide/Disable the modules section if device isn't rooted.

### ISSUE THREAD

**Issue by shrihanDev** [topjohnwu/Magisk#4925]
In 23013, if the user isn't rooted, the Modules section is still visible, and opening it yields a blank screen. It will be more suitable to hide the section altogether, kinda like how the Superuser section is handled.

Also, if the user IS rooted, but has no modules installed, it'd be feasible to include a message such as "No modules installed" to improve the UX a tad bit.

Device: any
Android version: any
Magisk version name: 23013
Magisk version code: 23013

**Comment by osm0sis** [comment]
Yeah that's a regression since they rewrote the bar at the bottom.
