### ISSUE TITLE
No modules show up, can't refresh the module repo either

### ISSUE THREAD

**Issue by keithah** [topjohnwu/Magisk#4939]
Device: Pixel 5
Android version: 12
Magisk version name: 23014 
Magisk version code: 7e9d4512

No modules are showing up, I click on the upper right hand corner icon to refresh and nothing happens. I can install from storage however.

**Comment by Didgeridoohan** [comment]
The changelog is a wonderful thing:
>[App] Downloading modules within the Magisk app is removed
