### ISSUE TITLE
Temporary root Pixel 6 not working (`fastboot boot magisk_patched.img`)

### ISSUE THREAD

**Issue by testcenter** [topjohnwu/Magisk#4941]
Device: Pixel 6 (oriole)
Android version: 12 (November Update)
Magisk version name: 7e9d4512
Magisk version code: 23014

I didn't wipe my phone via the `--disable-verity`. (So I am still on stock `boot.img` as well as stock `vbmeta.img`; but unlocked the bootloader via `fastboot flashing unlock`)
For now, I would be totally fine with the temporary root solution.

Unfortunately, when running `fastboot boot magisk_patched-23014_xyz.img` nothing happens.
The phone simply reboots into the bootloader, showing no error at all.
(Checked multiple times the `sha256` of the downloaded zip + recreated the `magisk_patched-23014_xyz.img` file -> no errors on that)

Some informations showing in the `Fastboot Mode`:
```
Secure boot: PRODUCTION
Device state: unlocked
Boot slot: a
Enter reason: reboot bootloader
```

Also `fastboot` does not deliver any error message:

```
$ fastboot --verbose boot magisk_patched-23014_vIwsx.img 
Sending 'boot.img' (65536 KB)                      OKAY [  1.048s]
Booting                                            OKAY [  0.006s]
Finished. Total time: 1.121s
```

edit:
forgot to mention: I am using the latest `fastboot` version:
```
$ fastboot --version
fastboot version 31.0.3-7562133
Installed as /home/testcenter/android/sdk/platform-tools/fastboot
```
```

**Comment by HuskyDG** [comment]
Is the command correct?

**Comment by testcenter** [comment]
Yes, the commands are correct.

**Comment by osm0sis** [comment]
Try again with the Artifacts zip app-debug.apk here: https://github.com/topjohnwu/Magisk/actions/runs/1487046691 - there were fixes for hdr v4.

**Comment by testcenter** [comment]
Hey osm0sis,

Yeah, I already saw that commit and was looking forward to try it out :smile: 

unfortunately it is the same behavior with 632971af ... :see_no_evil:

**Comment by testcenter** [comment]
Just to make my steps clear (I don't think I made something wrong, as I run this procedure since years :smile: ):

* I updated my phone via the ota file in recovery (`adb sideload oriole-ota-.....`). (currently running the latest November bulletin).
* Download the factory image matching the ota version, extract it; get the `boot.img` file.
* Push the `boot.img` file to the phone
* Patch the file via magisk
* Pull the file (`magisk_patched-<version>_<random>`)
* Reboot the phone to bootloader
* Boot the image `fastboot boot magisk_patched-xyz_abc`

**Comment by vvb2060** [comment]
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img

**Comment by vvb2060** [comment]
If you are using `fastboot flash`, you also need to wipe data. `fastboot boot` you only need to disable vbmeta.

**Comment by testcenter** [comment]
Thanks for the tip @vvb2060,


So I tried to flash `vbmeta` to disable verification:
`fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img` 
But then the phone doesn't boot at all (always asks me to `Try again` or `Factory Reset` - this is what I want to avoid :sweat_smile: ).

No matter if I boot normally (no `fastboot boot` command) or with `fastboot boot magisk_patched-xyz_abc.img`

So I flashed the `vbmeta` again with no commands (to be able to boot without root again :sweat_smile: )

**Comment by vvb2060** [comment]
It seems that unlike the Pixel5 situation, you may have to wipe the data once. My guess is that the keystore is bound to the signature of the boot image, making it impossible to decrypt the data partition. It is no longer possible to switch between the two signatures at will as it was before.

**Comment by vvb2060** [comment]
https://android.googlesource.com/platform/system/vold/+/e8de4ffd73b7da76dfae8ee959226dca9df45ae5
https://source.android.com/security/keystore/version-binding

**Comment by yujincheng08** [comment]
Confirmed by @RikkaW it can *somehow* be fixed by correcting vbmeta's flags. She's having Pixel 5 Android 12 rooted permanently by Magisk without cleaning userdata. We need more people to help test now.

**Comment by testcenter** [comment]
Thats great news! :tada: 

I also have a Pixel 5 with Android 12. (did not yet factory reset it with vbmeta verification disabled)
So I can also take a look at this :+1:

**Comment by yujincheng08** [comment]
This issue should be fixed by https://github.com/topjohnwu/Magisk/commit/f4ed6274a4c8294cc4804385bc29957f0a73934d

**Comment by testcenter** [comment]
I can confirm, that with f4ed627 I can boot into root :muscle:  (via `fastboot boot magisk_patched-xyz_abc.img`)
Just gave it a try on the Pixel 6 with December update. (`oriole-sq1d.211205.016.a1`)
Thanks a lot for investigating in this :bow:
