### ISSUE TITLE
Feature request: Hide / Disable the back button while installing a module or patching the images.

### ISSUE THREAD

**Issue by shrihanDev** [topjohnwu/Magisk#4956]
Device: any
Android version: any
Magisk version name: 23014
Magisk version code: 23014

As per the title, if a module is being installed or the boot / recovery image is being patched, there's a back button beside the "Installing" text. While the back button doesn't interfere with the said processes, it is better to actually remove or hide it, in order to contribute to a better UX.

**Comment by vvb2060** [comment]
I tend to auto reboot after install done.

**Comment by vvb2060** [comment]
This is part of the UI, and there is no "disable" semantics for this button.
