### ISSUE TITLE
Huawei sequel

### ISSUE THREAD

**Issue by Yoanndp** [topjohnwu/Magisk#496]
I have seen your last tweet (https://twitter.com/topjohnwu/status/1032673806622617600?s=19)

How will it go next?  Is Huawei support finished?

**Comment by Kirk1984** [comment]
I think this combined with the descision to not allow the user to unlock the bootloader anymore is a strong indicator that huawei isn't worth any effort IMHO.

**Comment by mlodyseven** [comment]
Well, but I guess there are some people who still use Huawei with unlocked BL and custom ROMs such as me. Well, I blame Huawei too, but I'd rather want my phone still supported, more or less.

**Comment by Yoanndp** [comment]
Exactly @mlodyseven , I still own a Huawei phone with an unlocked bootloader. I'm thinking about flashing a custom rom on soon so I hope topjohnwu will continue huawei support.

**Comment by topjohnwu** [comment]
I do own an Honor View 10, I will support it while I can. If anything breaks catastrophically, I wouldn't spend effort on Huawei devices though since it will not be on my priority.
