### ISSUE TITLE
"Hide the Magisk App" fails without "Install Unknown Apps" permission

### ISSUE THREAD

**Issue by huw0** [topjohnwu/Magisk#4960]
"Hide the Magisk App" fails if Magisk Manager does not have permission to "Install Unknown Apps". There is no prompt that this functionality is missing. Instead the hidden app is in a half-installed state where there is a launcher icon but it cannot be launched.

Magisk Manager should check that it has this permission before attempting to hide.

This permission prompt for this successfully appears when updating (or reinstalling) Magisk Manager from within Magisk Manager. After this the "Hide the Magisk App" function works successfully.

Device: Pixel 5
Android version: 11
Magisk version name: 23014
Magisk version code: 23014

**Comment by vvb2060** [comment]
@osm0sis Can you reproduce it?

**Comment by osm0sis** [comment]
On MIUI I definitely can

**Comment by vvb2060** [comment]
@osm0sis

https://user-images.githubusercontent.com/26996262/143257979-67c3649f-b762-4431-b8ed-2d3c37bc8dfd.mp4

**Comment by Howard20181** [comment]
> @osm0sis
> 
>  video_2021-11-24_22-35-06.mp4

MIUI 12.5 21.11.23 Nightly
Android 11

**Comment by vvb2060** [comment]
https://user-images.githubusercontent.com/26996262/143258228-6788beed-f799-4208-aad2-880269b2755e.mp4

**Comment by osm0sis** [comment]
I'll add my Poco X2 video here later. 😛

**Comment by huw0** [comment]
Probably should've mentioned in the ticket - this is with the latest LineageOS, rather than stock AOSP.
I note one of the videos shows a USB install popup - if it makes a difference I have ADB debug disabled.

**Comment by vvb2060** [comment]
No one can reproduce it or provide a valid log.

**Comment by osm0sis** [comment]
I can reproduce the issue, repeatedly, with ease.

**Comment by vvb2060** [comment]
I need video for details.
> ActivityManager: Killing 9793:com.topjohnwu.magisk/u0a166 (adj 700): REQUEST_INSTALL_PACKAGES changed.

**Comment by osm0sis** [comment]
Added above. 👍

**Comment by BartmanEH** [comment]
How do we make "hide the Magisk app" work when we're staying with v23 to keep MagiskHide?
