### ISSUE TITLE
Zygisk doesn't start

### ISSUE THREAD

**Issue by tillnelown** [topjohnwu/Magisk#4961]
On my phone zygisk doesn't start anymore, it worked once with the USNF but after  adding lsposed (or maybe it was just the reboot? i hadn't used zygisk before) and rebooting it stopped working. I removed all modules and toggled zygisk multiple times (also toggled the blacklist) but it's still disabled.

Device: Samsung Galaxy S9 (SM-G960F/samsungexynos9810)
Android version: 10/SDK 29
Magisk version name: Canary/7e9d4512:MAGISK
Magisk version code: 23014

![zygisk-off](https://user-images.githubusercontent.com/47001331/142743100-e7d6ffb4-e0f5-49fe-8f14-da643a78da05.jpeg)

**Comment by tillnelown** [comment]
Installing the modules on another device doesn't seem to cause issues and zygisk stays on, maybe cause of samsung? 
SAR, A partition only, patched (AP) image

**Comment by yujincheng08** [comment]
the logcat is too late and Magisk log is useless

**Comment by tillnelown** [comment]
> the logcat is too late and Magisk log is useless

how do i get an earlier logcat then? "adb -d logcat" gives me a few more boot logs but they don't seem that helpful:
`
--------- beginning of main
11-22 19:02:04.158   358   358 I SELinux : SELinux: Loaded service_contexts from:
11-22 19:02:04.159   358   358 I SELinux :     /system/etc/selinux/plat_service_contexts
11-22 19:02:04.166   359   359 I hwservicemanager: hwservicemanager is ready now.
11-22 19:02:04.169   360   360 I SELinux : SELinux: Loaded service_contexts from:
11-22 19:02:04.169   360   360 I SELinux :     /vendor/etc/selinux/vndservice_contexts
11-22 19:02:04.333   368   368 D libmdf  : libmdf v2.9.0.0 On 64bit PLATFORM
--------- beginning of system
11-22 19:02:04.335   368   368 I vold    : Vold 3.0 (the awakening) firing up
[...]
`

**Comment by tillnelown** [comment]
I figured out what is causing this, installing lsposed zygisk version will somehow prevent zygisk from starting even when removed afterwards on Samsung(maybe? sample size of 2) devices until...something happens to reset this, i figured it out after zygisk was enabled after my latest logcat and installing the Lsposed module which caused it to be disabled again(sadly no log of this). This issue seems to be a bit between Lsposed and magisk because of the lingering effect, should i post it on their tracker or keep it here?

**Comment by Yuzyuz01** [comment]
> 

I already unistalled the lsposed, but it still not working on zygisk (Samsung note 8)

**Comment by skobkin** [comment]
I think I may have a similar problem on my Oneplus 9 Pro.
Some of system boots ends up with Zygisk not enabled. But if I reboot, it will be enabled.
I don't know what can cause that.
