### ISSUE TITLE
Can't boot to recovery, ramdisk says "no" after flashing magisk

### ISSUE THREAD

**Issue by npv12** [topjohnwu/Magisk#4976]
After flashing the magisk, in magisk manager, ramdisk shows "no". It is "yes" before flashing magisk. Oneplus 7 pro has recovery inside of its boot partition and after flashing magisk, recovery becomes inaccessible. When trying to boot to recovery, it would just boot back to system. 

Furthermore since ramdisk shows no, flashing to opposite slot also fails. 

Before flashing magisk
![photo_2021-11-24_16-17-03](https://user-images.githubusercontent.com/59979143/143224342-2c3f983b-0b5c-4ff1-bb4c-00adf1a9866f.jpg)

After flashing magisk
![photo_2021-11-24_16-08-03](https://user-images.githubusercontent.com/59979143/143223268-3b408c62-cf10-4e2c-810e-790c8a99646e.jpg)

Since i am unsure on what all logs you would need I am attaching a boot log and a dmesg. Do let me know if you need anything else.
[boot.log](https://github.com/topjohnwu/Magisk/files/7594975/boot.log)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/7595011/dmesg.log)

Note: This issue didn't exists on android 11 or below. 

Device: Oneplus 7 ( pro ) - guacamole(b)
Android version: 12.0
Magisk version name: 5d6d2417
Magisk version code: 23015

**Comment by idoybh** [comment]
Recovery is still accessible via volume up in boot btw. I can confirm the same symptoms here. Seems like magisk doesn't detect ramdisk here and installs to recovery instead.

**Comment by Hans155922** [comment]
小米10u的21.12.01开发板也遇到这个问题了

**Comment by usrDottik** [comment]
did you try patching boot.img? Remember that Recovery Installations are almost abandoned, patching boot.img could workaround that issue (I understood that you installed Magisk via TWRP, not througha a boot.img patch)

**Comment by npv12** [comment]
> did you try patching boot.img? Remember that Recovery Installations are almost abandoned, patching boot.img could workaround that issue (I understood that you installed Magisk via TWRP, not through a boot.img patch), remember that topjohnwu said that trying to get information on the environment in a custom recovery is not 100% success rate, that might cause it to not detect boot ramdisk and it patches the recovery ramdisk, which btw if it flashed that way(recovery hijacking), you can use the [Magisk In Recovery](https://topjohnwu.github.io/Magisk/install.html#magisk-in-recovery) method to get Magisk up and running

I have tried both, using twrp/recovery to flash magisk and also patched the boot.img and flash that to gain root

Twrp has not been fully functional for my device for about an year now and patching my boot img is my go-to way to root. 

Doing both had exactly the same result. It roots fine but ramdisk says "No"

**Comment by idoybh** [comment]
> did you try patching boot.img? Remember that Recovery Installations are almost abandoned, patching boot.img could workaround that issue (I understood that you installed Magisk via TWRP, not through a boot.img patch), remember that topjohnwu said that trying to get information on the environment in a custom recovery is not 100% success rate, that might cause it to not detect boot ramdisk and it patches the recovery ramdisk, which btw if it flashed that way(recovery hijacking), you can use the [Magisk In Recovery](https://topjohnwu.github.io/Magisk/install.html#magisk-in-recovery) method to get Magisk up and running

Yes same results for both methods.

**Comment by vratska** [comment]
same here, Oneplus 7, Android 12, any way to fix it?

**Comment by yujincheng08** [comment]
If you tried to unpack boot.img using magiskboot, you will find a `recovery_dtbo` file. Thus magisk is working on recovery mode.

**Comment by yujincheng08** [comment]
Try #5070
Note that you have to restore to factory boot and reboot and patch boot again.

**Comment by npv12** [comment]
> Try #5070 Note that you have to restore to factory boot and reboot and patch boot again.

Can confirm, this works!

**Comment by idoybh** [comment]
> > Try #5070 Note that you have to restore to factory boot and reboot and patch boot again.
> 
> Can confirm, this works!

Same here. Thank you @yujincheng08

**Comment by MeenoTEK** [comment]
> Try #5070 Note that you have to restore to factory boot and reboot and patch boot again.

What's factory boot?

I have this issue where magisk says Ramdisk - No even after reflashing.

I use a mi 9T and my phone has no sound (i work around this by using Audio compatibility patch, AML and Viper).

Right now, the patches aren't working and I'm curious if it's because the ramdisk says No.

**Comment by Vaqif977** [comment]
Hello, my ramdisk is not working How can I fix it?
