### ISSUE TITLE
unsupported/unkown image format

### ISSUE THREAD

**Issue by El-bana** [topjohnwu/Magisk#4978]
Device: oppo a15 cph2185
Android version: 10
Magisk version name: 5d6d241
Magisk version code: 23015

i downloaded the official oppo firmware extracted the zip copied a 38mb boot.img file selected it on magisk but it gives me unsupported/unkown image format

**Comment by osm0sis** [comment]
You probably didn't extract the boot.img correctly. But how would anyone know since you haven't uploaded it?

**Comment by El-bana** [comment]
ok sorry for that, but that's all i needed i forgot using oppo_ozip_decrypt tool before unzipping the file
thanks a lot for the help

**Comment by munnamatiurrahman** [comment]
Can you send me magisk patch file for oppo a15s?
