### ISSUE TITLE
magisk app dont detect magisk

### ISSUE THREAD

**Issue by yonggamer** [topjohnwu/Magisk#4979]
Device: samsung GT-I9505
Android version:5.0.1
Magisk version name: 5d6d2417
Magisk version code: 23015
![Screenshot_2021-11-24-18-36-37](https://user-images.githubusercontent.com/24843208/143287906-24518e13-c00d-4e80-8326-cd3e9832f3af.png)

**Comment by osm0sis** [comment]
#4174
