### ISSUE TITLE
Extremely slow directly installing/patching zopfli kernel using latest Canary

### ISSUE THREAD

**Issue by sn-o-w** [topjohnwu/Magisk#4980]
Device: Google Nexus 5
Android version: Android 10
Magisk version name: 5d6d2417
Magisk version code: 23015

---

It always gets stuck here:

![Screenshot_20211125-042841_Magisk](https://user-images.githubusercontent.com/2406819/143369366-089b07d9-d7e3-4969-b7c4-8815c91fc79e.png)

Kernel file: 
[boot-file.tar.gz](https://github.com/topjohnwu/Magisk/files/7599791/boot-file.tar.gz)

**Comment by vvb2060** [comment]
Wait 10 minutes, zopfli very slow.

**Comment by sn-o-w** [comment]
I had to wait 5 minutes, wooow...

**Comment by sn-o-w** [comment]
@osm0sis Can you please reopen this issue? I've edited the title to better reflect the issue I'm still facing.

**Comment by osm0sis** [comment]
I think the insinuation is there isn't a good way to speed up zopfli much more. @chaosmaster should be able to say for sure.

**Comment by sn-o-w** [comment]
> I think the insinuation is there isn't a good way to speed up zopfli much more. @chaosmaster should be able to say for sure.
> 
> Edit: For reference, using your boot.img, latest magiskboot on my OnePlus 8T takes 30-45 seconds to repack it, so imagine how hard the Nexus 5 must be struggling.

Switching between apps or the screen timing out will prevent Magisk's ongoing patching process from succeeding. It's kinda annoying to wait so much time on the same screen and to make sure the process ends properly.

**Comment by osm0sis** [comment]
Hmm yeah I agree the backgrounding shouldn't fail

**Comment by chaosmaster** [comment]
> I think the insinuation is there isn't a good way to speed up zopfli much more. @chaosmaster should be able to say for sure.
> 
> Edit: For reference, using your boot.img, latest magiskboot on my OnePlus 8T takes 30-45 seconds to repack it, so imagine how hard the Nexus 5 must be struggling.

zopfli could be sped up substantially by disabling blocksplitting and using only one iteration as done in #4878
This was changed with @topjohnwu's recent rewrite in 048b2af0fc8d0f8b1a69733b1834f39f88845777

**Comment by osm0sis** [comment]
So reopen this for further review of that?

**Comment by chaosmaster** [comment]
I wouldn't mind, it's up to John

**Comment by osm0sis** [comment]
The loss of speed is a regression of sorts 😉

**Comment by sn-o-w** [comment]
I just want to let you know that the following commit https://github.com/topjohnwu/Magisk/commit/ae34659b26fd96c63cf0c390ddfee72ec6edfa32 substantially improves the flashing process duration.

Now I have about 5-10 seconds instead of 2-3 minutes, other older devices might also perform much faster.

Thanks @yujincheng08 ❤️
