### ISSUE TITLE
Magisk_patched.img boot image broken.

### ISSUE THREAD

**Issue by SharkieCodes** [topjohnwu/Magisk#4988]
Hey, I wanted to root my Xiaomi Redmi 9 (MIUI 12.5.3, Android 11), I got the correct boot.img and put in Magisk, it gives me the magisk_patched.img. Then i move over to my pc open the platform-tools, put my phone in fastboot. Then i type `fastboot flash boot magisk_patched.img`  then `fastboot reboot` then i get a bootloop, I have seen multiple people struggle with the magisk_patched.img file for android 11. Is there any way you can fix that? Thanks!

**Comment by Mkjng** [comment]
Software not updated
