### ISSUE TITLE
Samsung M52 5G

### ISSUE THREAD

**Issue by Ralegend** [topjohnwu/Magisk#4993]
Hi.
My device is Samsung M52 5G. I tried the 23015 canary and followed the guide:
https://topjohnwu.github.io/Magisk/install.html
I am trying to root the phone for hours and no luck!
What am I doing wrong? Odin flash done than stuck with the "This phone is not running Samsung's official software...."
Please help me and save my next hours. Thank you.

Device:  Samsung M52 5G
Android version: 11
Magisk version name: Canary
Magisk version code: 23015

**Comment by Ralegend** [comment]
“E:[libfs_mgr]Error updating for slotselect”
After hours of trying, I think this stock recovery mode warning might be the reason. Because I know I am doing the right steps for Magisk installation.

**Comment by vvb2060** [comment]
No valid info

**Comment by rjhigh** [comment]
Facing the same issue. Magisk patched image gets created fine, but the device bootloops after it is flashed with this image via Odin. (Stock firmware flashing works fine).

**Comment by Ralegend** [comment]
> Facing the same issue. Magisk patched image gets created fine, but the device bootloops after it is flashed with this image via Odin. (Stock firmware flashing works fine).

Hi rjhigh. It has been 1 month and still trying root the phone but no luck. :(

**Comment by rjhigh** [comment]
> > Facing the same issue. Magisk patched image gets created fine, but the device bootloops after it is flashed with this image via Odin. (Stock firmware flashing works fine).
> 
> Hi rjhigh. It has been 1 month and still trying root the phone but no luck. :(

I 'm unable to get any booting logs but I think this might be the same issue as [this](https://github.com/topjohnwu/Magisk/issues/4795)

**Comment by rjhigh** [comment]
@Ralegend now use the canary build(23016), it has been fixed.

**Comment by Ralegend** [comment]
Finally rooted. Thank you.

**Comment by rev4rt** [comment]
> Finally rooted. Thank you.

How to root? Can you help me?
