### ISSUE TITLE
Email not working

### ISSUE THREAD

**Issue by scramblr** [topjohnwu/Magisk#5004]
Device: All
Android version: Any
Magisk version name: Main
Magisk version code: 23

Hello,

I was trying to email the team to let them know about the bug in the website that refers to version 22 instead of 23. This issue is being raised to communicate that **admin [at] magisk.me** does not work. Below are the headers.

`<admin@magisk.me>: host aspmx.l.google.com[142.251.5.27] said: 550-5.1.1 The email account that you tried to reach does not exist. Please try 550-5.1.1 double-checking the recipient's email address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1 https://support.google.com/mail/?p=NoSuchUser f13372325990wrm.317 - gsmtp (in reply to RCPT TO command) etc etc.. if you need the full headers, just let me know.`

Thank you.

**Comment by b4n6-b4n6** [comment]
magisk.me is not affiliated with this project or author AFAIK
