### ISSUE TITLE
Can't revert back stable version after installing Canary build

### ISSUE THREAD

**Issue by cs853120** [topjohnwu/Magisk#5012]
Device: GOOGLE PIXEL 4 XL
Android version:Android 12
Magisk version name: Magisk Canary 23013
Magisk version code: 258e89c9

Hi.
After installing the Canary version
I can't revert back to stable vesrion (23.0)
the manager doesn't detect my magisk (I can see root access was denied in the roast message) when I installing 23.0 by using fastboot to flash boot.img
but when I installing back to 58e89c9. the manager can detect the root.
is there anything to instaling back to the stable version without wiping whole system?

**Comment by MrHappy** [comment]
I have the same issue with latest Canary.
Is there a way?
