### ISSUE TITLE
sepolicy.rule Wrong Directory Installation via Recovery/TWRP

### ISSUE THREAD

**Issue by reiryuki** [topjohnwu/Magisk#5013]
Device: Xiaomi Redmi 4A (rolex)
Android version: Android 11
Magisk version name: 5d6d2417
Magisk version code: 23015

Something like this is happened again when I install a module with sepolicy.rule via Recovery/TWRP
https://github.com/topjohnwu/Magisk/issues/3735#issue-788092045

sepolicy.rule files are installed to /cache/magisk but the sepolicy.rules directory is linked to /persist/magisk
[magisk_log_2021-12-05T04_43_13Z.log](https://github.com/topjohnwu/Magisk/files/7654775/magisk_log_2021-12-05T04_43_13Z.log)

![Screenshot_20211205-044414](https://user-images.githubusercontent.com/46316533/144725771-ca171f8e-f9f1-49ab-972f-5dc091f40b2f.png)
![Screenshot_20211205-044348](https://user-images.githubusercontent.com/46316533/144725772-94206343-198f-472a-ba23-f56a172fc79a.png)
![Screenshot_20211205-044402](https://user-images.githubusercontent.com/46316533/144725774-055063d1-0513-406d-bcba-4f4fa2463fee.png)
![Screenshot_20211205-044427](https://user-images.githubusercontent.com/46316533/144725775-82011f69-6bfc-490e-a6a9-f7d5744660ca.png)

**Comment by canyie** [comment]
Is your `cache` partition format f2fs?

**Comment by canyie** [comment]
Hi, please try this build: https://github.com/canyie/Magisk/actions/runs/1566769795

**Comment by vvb2060** [comment]
@reiryuki If there is no response, this issue will be closed

**Comment by reiryuki** [comment]
@canyie emmm yes my /data and /cache using f2fs
But no problem I have moved to magiskpolicy --live "..." command instead of using sepolicy.rule now but I will try the build soon

**Comment by reiryuki** [comment]
@vvb2060 sorry for late response, I was busy last week 😅

**Comment by osm0sis** [comment]
@reiryuki and does that test build work for you?

**Comment by reiryuki** [comment]
@osm0sis
Yes I've tried both the release and the debug, but I have to mount /persist first before installing a module with sepolicy.rule, otherwise the sepolicy rule dir can't be detected. Is it because the Magisk failed to mount /persist ?

This is without mount /persist before install
![Screenshot_2022-01-01-12-09-23](https://user-images.githubusercontent.com/46316533/147844816-f65433b6-fc0f-4676-b020-df17455997cb.png)

This is with mount /persist before install
![Screenshot_2022-01-01-12-11-42](https://user-images.githubusercontent.com/46316533/147844824-22a8987e-9289-458f-98c5-2521dbd45b5c.png)

**Comment by canyie** [comment]
I'm not sure manually mount /persist will be a good idea since I know some devices "claim“ they has /metadata or /cache partition in their fstab but don't mount it actually (see #4642). Anyway, I will submit canyie/Magisk@3167f0b76eacc3ae7825d5f39348aa3898b6eccc as a fix for wrong sepolicy rules directory, and maybe someone will submit a further fix.

**Comment by reiryuki** [comment]
yep, grep ext4 should be a workaround 😊👌

**Comment by osm0sis** [comment]
Ah yes, metadata is often raw emmc. Good catch
