### ISSUE TITLE
Patching boot.img on A/B devices via app

### ISSUE THREAD

**Issue by georgekav2** [topjohnwu/Magisk#503]
The app should not allow, the users of A/B devices to patch the boot image file via the app. 

The true kernel loaded initramfs resides in system.img. If you patch the boot.img, you actually accepting to patch the recovery ramdisk. Thus, flashing the boot.img via fastboot, will have no effect.

**Comment by topjohnwu** [comment]
You obviously don't know how Magisk works, so I'll close this issue.

**Comment by HikariCalyx** [comment]
You can refer my root guide written for Nokia 7 plus:

https://forum.xda-developers.com/nokia-7-plus/how-to/guide-how-to-root-ab-partition-scheme-t3792509

You shouldn't flash patched boot image to the device with fastboot command, instead you should perform temporarily boot from patched boot image, then reinstall Magisk zip in Magisk Manager to make the root permanently.
