### ISSUE TITLE
All right, only after patching core need manual remove this in hex edit.

### ISSUE THREAD

**Issue by badmonster** [topjohnwu/Magisk#5037]
Boot partition_size: 0x1000000
After patching boot-sign.img need in end remove from hex:

`00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`

Device: Asus Zenfone Go ZC500TG Z00VD
Android version: 10 Q (stable) core 4.9.188
Magisk version name: 23
Magisk version code: 23015

**Comment by osm0sis** [comment]
Hard to tell what your issue is from your (lack of) description, but it looks like you're removing a single empty page. If so, I think that's already fixed upstream with 0a28dfe1e2c200d84e28b7d1db059c0c91f2d105 and will be in the next Canary (23016).

**Comment by badmonster** [comment]
> Hard to tell what your issue is from your (lack of) description, but it looks like you're removing a single empty page. If so, I think that's already fixed upstream with [0a28dfe](https://github.com/topjohnwu/Magisk/commit/0a28dfe1e2c200d84e28b7d1db059c0c91f2d105) and will be in the next Canary (23016).

Thank you, so match!
