### ISSUE TITLE
Pixel 6 pro, recent android december update breaks root.

### ISSUE THREAD

**Issue by mclarence** [topjohnwu/Magisk#5057]
Device: Google Pixel 6 Pro 512GB
Android version: Android 12 (`SQ1D.211205.016.A1, Dec 2021`)
Magisk version name: 5d6d2417
Magisk version code: 23015

The recent android december update for google pixel 6 breaks root. Magisk manager does not detect root even after flashing the boot image.

Steps to reproduce:

1. Coming from the november 2021 patch (was rooted), I downloaded the factory image from Google's website, extracted and modified the flash-all.bat to not wipe the data when flashing. The following line was modified:
```
...
fastboot -w update image-raven-sq1d.211205.016.a1.zip
```

to

```
...
fastboot update --disable-verity --disable-verification image-raven-sq1d.211205.016.a1.zip
````
As you can see verity and verification was disabled and vbmeta did not need to be flashed. I tried to flash vbmeta again but it made no difference.

2. After successful flashing, I let the system boot normally.
3. I then extracted the boot.img file from the factory image zip and patched it with magisk manager.
4. I rebooted to bootloader and flashed the magisk patched boot image with
`fastboot flash boot --slot=all magisk_patched.....img`
5. I reboot again, the system boots up successfully. I then check magisk manager to see that it has not detected that it has been installed. It simply says _Installed N/A, Zygisk No, Ramdisk Yes_
6. I attempted to flash again, but it did not work.

Attached logcat:
[logcat.txt](https://github.com/topjohnwu/Magisk/files/7708574/logcat.txt)

**Comment by Hal1ucinogen** [comment]
Pixel 6 also encountered the same problem

**Comment by Hondo77** [comment]
Also happens on the Android 12 sq1d.211205.017, Dec. 2021 US carriers version of the Pixel 6 Pro using Magisk Canary 23015 using the same method except without the --slot=all when fastboot flashing the patched boot image.

**Comment by yujincheng08** [comment]
Please grab a bugreport after reboot: https://developer.android.com/studio/debug/bug-report

**Comment by mclarence** [comment]
[Bugreport.zip](https://github.com/topjohnwu/Magisk/files/7708859/Bugreport.zip)

**Comment by Hondo77** [comment]
> Please grab a bugreport after reboot: https://developer.android.com/studio/debug/bug-report
[bugreport-raven-SQ1D.211205.017-2021-12-13-23-11-52.zip](https://github.com/topjohnwu/Magisk/files/7708885/bugreport-raven-SQ1D.211205.017-2021-12-13-23-11-52.zip)

**Comment by yujincheng08** [comment]
I think it's caused by this commit:
https://cs.android.com/android/_/android/platform/system/core/+/e98afa2687eb56184dad8569b929eba04fb93068

Will test and submit a PR.

**Comment by yujincheng08** [comment]
Please try #5059

**Comment by mclarence** [comment]
![Screenshot_20211214-171917](https://user-images.githubusercontent.com/25338414/145944014-1c8d1e03-22d5-478e-a842-96b9f318fbb2.png)
![Screenshot_20211214-172009](https://user-images.githubusercontent.com/25338414/145944019-e306088b-caea-4a79-9cf6-31c705cf8b2f.png)

Appears to be working now!

Thanks!!!

**Comment by smemsh** [comment]
My magisk installation still shows `5d6d2417 (23015)` as the latest canary, and MAGISK_VER / MAGISK_VER_CODE in app-debug.apk seem to confirm.  Where does one obtain this `65e020f6 (23015)` version shown in screenshot above? It requires one to build manually in order to apply December update?

**Comment by smemsh** [comment]
I was able to build current trunk a4faa3f3 (still says version 23015) using README instructions (had to install "command line tools" rather than "build tools" for `sdkmanager --licenses` to work), installing via `adb install` (after uninstalling old one), and root has now been restored in the generated boot.img.  Since many will try upgrade after December update, might be a good idea to release a new canary...

**Comment by smemsh** [comment]
23016 canary has been released now which contains this patch
