### ISSUE TITLE
Magisk not working on Pixel 6 Pro December update

### ISSUE THREAD

**Issue by PavelMasuk** [topjohnwu/Magisk#5061]
Device: Pixel 6 Pro(not attached to carrier)
Android version: 12.0.0 (SQ1D.211205.016.A1, Dec 2021)
Magisk version name: canary
Magisk version code: 5d6d2417(23015)

also tested with magisk alpha and got the same result
Magisk version name: alpha
Magisk version code: b76a3614-alpha(23015)

verity and verification disabled
tried flashing boot both with and without --slot=all

After rebooting to system magisk says that phone is not rooted and suggests to root it
Looks like Google has made some changes to boot.img in latest December security patch
also boot.img is now around 60mb compared to previous 100mb

Full story:
When I updated to the latest December security patch, flashed new magisk_patch_boot.img and booted to system it said rebooting, factory reset. Then it booted to some king of recovery mode with 2 options: factory reset and try again. and every time after trying again and booting to system it was saying "restarting, factory reset" right after entering password.
When I confirmed factory reset, disabled varity and verification again, and tried to root using magisk alpha, nothing happened.
When I tried magisk canary(aforementioned version) with option --slot=all, i got thing endless "restarting, factory reset" again, after installing stock boot image it still keeps "restarting and factory resetting".

So currently magisk is not working on Android 12 December security patch

**Comment by canyie** [comment]
#5059
