### ISSUE TITLE
About MagiskSU

### ISSUE THREAD

**Issue by leenchan** [topjohnwu/Magisk#507]
su [any_user_id/name]
lost groups and cant access network.

adb shell
hlte:/ $ id
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc),3011(uhid) context=u:r:shell:s0
hlte:/ $ curl baidu.com
<html>
<meta http-equiv="refresh" content="0;url=http://www.baidu.com/">
</html>
hlte:/ $ su - shell
hlte:/ $ id
uid=2000(shell) gid=2000(shell) groups=2000(shell) context=u:r:magisk:s0
hlte:/ $ curl baidu.com
curl: (6) Couldn't resolve host 'baidu.com'
6|hlte:/ $ su -v
16.7:MAGISKSU (topjohnwu)

**Comment by vvb2060** [comment]
Intended Behavior

**Comment by Freed-Wu** [comment]
Does there exist any method to keep/add group after `magisk su` like `gpasswd` in GNU/Linux? I found after `su -l <termux-username>`, there are no group for `<termux-username>`. Not any method to add any permission?

**Comment by Freed-Wu** [comment]
![Screenshot from 2022-06-06 17-23-37](https://user-images.githubusercontent.com/32936898/172133906-c9050b42-a8fc-4484-ad94-eb9fc6ed5dde.png)
