### ISSUE TITLE
Way to build Magisk into a ROM via aosp build process

### ISSUE THREAD

**Issue by robsee** [topjohnwu/Magisk#509]
It would be great if there were a way to build Magisk into a rom as part of the compilation process. Minimally, if you could patch the boot.img on a separate host (instead of on phone), that would work.

**Comment by topjohnwu** [comment]
I do plan to add support to Magisk, including system-based like bundling into GSIs

**Comment by robseesuny** [comment]
I've kind of gotten it working now, but it requires patching system/core/init to end up in the ramdisks as init.orig. Then I hacked magiskinit to do its stuff, and then rename init.orig to init, and continue

**Comment by Black-Seraph** [comment]
Any news on this yet?

**Comment by 9e3fce0a** [comment]
I'm also keen to get this working with something like https://github.com/dan-v/rattlesnakeos-stack

See [reddit discussion here](https://www.reddit.com/r/RattlesnakeOS/comments/a9jben/can_you_root_this/)

Any tips?

**Comment by alexa-v2** [comment]
Any progress on this?

My team developing lunaOS (https://github.com) wishes to ship our ROM (and preferably our GSI variant) with magisk as our root solution. I personally love the whole systemless mods (less chance of bricking a device) and the wealth of module available

However, we wish to know if it's even possible and if so how

**Comment by rootinchase** [comment]
Has there been any update on this?

Is it in progress? Are there things tripping you up? Is it on a back burner?

**Comment by topjohnwu** [comment]
The Magisk building system is complicated and I'm not so sure about integrating directly into AOSP. Once Magisk actually support being installed with GSI images, I might investigate on how to embed prebuilt Magisk binaries easily with the build system

**Comment by Geofferey** [comment]
In regards to this even tho it has been closed. I have successfully integrated magisk with my builds. Here are the changes you need to make. 

A modification to build/core/Make
https://github.com/Geofferey/omni_android_build/commit/d60958780e6b26d7cb0cec5939b82df3df74a68f

A repo to copy magiskinit to PRODUCT_OUT
https://github.com/Geofferey/android_vendor_magisk

**Comment by steadfasterX** [comment]
I wanted to have an almost fully compatible solution which is hopefully future proof so  Geofferey's solution was not sufficient for my needs (no offense! just its not what I needed).

So I made a complete different approach and the result has been integrated into my extendrom project where you can easily (once you got the details) root your ROM within the AOSP build process.

It will always download Magisk itself, unpacks it, and use the binaries within to patch automatically the boot.img with official(!) Magisk scripts (not just replacing init).

All the details and how it needs to be setup can be found here:
1. setup extendrom: https://github.com/sfX-android/android_vendor_extendrom/
1. setup pre-rooting: https://github.com/sfX-android/android_vendor_extendrom/wiki/extendrom_flags#extendrom_preroot_boot

It may look overwhelming first but it is flexible and fits all my needs while staying at close as possible to Magisk itself.

The main goal for me was having a rooted ROM while keeping full AVB / dm-verity support on my bootloader locked OnePlus device.

maybe that's useful for someone else so I wanted to add it here.

**Comment by corrmaan** [comment]
Thanks @steadfasterX for posting your solution. I worked on a similar task of getting Magisk integrated to a LineageOS build with OpenGApps and AVB/dm-verity support. Not to hijack your post, but if anyone is interested please check it out here: https://github.com/corrmaan/docker-lineage-cicd.

It's forked from https://github.com/lineageos4microg/docker-lineage-cicd with other code from https://github.com/dan-v/rattlesnakeos-stack, and is mainly tailored to my Pixel 2, but maybe others will find it useful.

**Comment by mohrezaei** [comment]
I just documented [another solution](https://gist.github.com/mohrezaei/fe76ab2091e834b6edb2ab9f11e31c07) which was inspired by @steadfasterX, with the following differences:

- No need to use modified Magisk scripts
- Works during signing, so no need to add/change anything inside the build tree

**Comment by corrmaan** [comment]
@mohrezaei That's a cool way to do it!

**Comment by lxy0797** [comment]
> > I just documented [another solution](https://gist.github.com/mohrezaei/fe76ab2091e834b6edb2ab9f11e31c07) which was inspired by @steadfasterX, with the following differences:
> > 
> > * No need to use modified Magisk scripts
> > * Works during signing, so no need to add/change anything inside the build tree
> 
> nice stuff! unfortunately it does not work inside the AOSP build process as when the patch script gets executed the binaries get denied on newer Android versions (https://sx.ix5.org/info/post/android-q-changes/ -> PATH restrictions)
> 
> and just for info: my approach has changed and uses the magisk scripts completely untouched now ;)

Could u tell me the new method? I want to have a try.thx

**Comment by steadfasterX** [comment]
> > > I just documented [another solution](https://gist.github.com/mohrezaei/fe76ab2091e834b6edb2ab9f11e31c07) which was inspired by @steadfasterX, with the following differences:
> > > 
> > > * No need to use modified Magisk scripts
> > > * Works during signing, so no need to add/change anything inside the build tree
> > 
> > 
> > nice stuff! unfortunately it does not work inside the AOSP build process as when the patch script gets executed the binaries get denied on newer Android versions (https://sx.ix5.org/info/post/android-q-changes/ -> PATH restrictions)
> > and just for info: my approach has changed and uses the magisk scripts completely untouched now ;)
> 
> Could u tell me the new method? I want to have a try.thx

if that q was for me then read: https://github.com/topjohnwu/Magisk/issues/509#issuecomment-911720167

**Comment by akash07k** [comment]
My Device is Virtual A/B and launched with Android 12.
It doesn't have separate boot partition.
Any way to make your solution work with my device?
I wan't to integrate magisk right in the rom
> > > > I just documented [another solution](https://gist.github.com/mohrezaei/fe76ab2091e834b6edb2ab9f11e31c07) which was inspired by @steadfasterX, with the following differences:
> > > > 
> > > > * No need to use modified Magisk scripts
> > > > * Works during signing, so no need to add/change anything inside the build tree
> > > 
> > > 
> > > nice stuff! unfortunately it does not work inside the AOSP build process as when the patch script gets executed the binaries get denied on newer Android versions (https://sx.ix5.org/info/post/android-q-changes/ -> PATH restrictions)
> > > and just for info: my approach has changed and uses the magisk scripts completely untouched now ;)
> > 
> > 
> > Could u tell me the new method? I want to have a try.thx
> 
> if that q was for me then read: [#509 (comment)](https://github.com/topjohnwu/Magisk/issues/509#issuecomment-911720167)

**Comment by steadfasterX** [comment]
> My Device is Virtual A/B and launched with Android 12. It doesn't have separate boot partition. Any way to make your solution work with my device? I wan't to integrate magisk right in the rom
 
I see no reason why it should not work

**Comment by beedell-roke** [comment]
@topjohnwu, since solutions exist, but don't appear to have been integrated into this codebase, why is this closed? More importantly, why is it closed as completed, rather than unplanned, if undesirable?

**Comment by zearp** [comment]
It would be great indeed, currently I have to faff about with extracting the latest apk and hope it all works to patch the boot.img on my build/ota Linux machine without a phone or phone app. I'd be happy with a stand-alone Linux version at this point but integration where you add an xml file that pulls in all we need to build Lineage or other roms with Magisk fully integrated and ready to have modules added would be a very nice QoL update.

**Comment by steadfasterX** [comment]
@zearp did u see https://github.com/topjohnwu/Magisk/issues/509#issuecomment-911720167 ?

**Comment by robsee** [comment]
> [@zearp](https://github.com/zearp) did u see [#509 (comment)](https://github.com/topjohnwu/Magisk/issues/509#issuecomment-911720167) ?

I have been using this since 2021 for my private builds, and other than a couple tweaks every so often to line up with changes in the android build process, its been working really well. Using it on Pixel 9 Android 16 QPR1 currently.

**Comment by zearp** [comment]
@steadfasterX Looking at it now and I am a bit overwhelmed lol, but I will follow the wiki and see where I end up. Thanks for pointing your solution out and thank you @robsee for confirming the 2021 solution still works today, that sounds like a good long term solution even if it might be overwhelming for me now. I'll try and wrap my head around it as it seems to be the best solution and working long term.

I'm currently using Micro G's docker thing on an old mini pc to compile and also use that for my own ota updates, all working well. So far I only added some local manifests to include extra apps and Micro G itself. Reading the wiki a bit it seems to also use a local manifest but also needs other modifications. Would it be better to use the normal Lineage way of compiling when using extendrom? Using the docker builder seems to remove any change I make when it runs its repo sync.

**Comment by zearp** [comment]
Very cool project @steadfasterX. I couldn't get it to work with Android 16 but building for 15 went well. I'll wait for support for Android 16 and in meantime hope @topjohnwu will (re)consider making it easier to integrate Magisk in AOSP builds without 3rd party utils.
