### ISSUE TITLE
Loss of features from phh's root manager to the built-in one

### ISSUE THREAD

**Issue by josephcsible** [topjohnwu/Magisk#51]
Now that Magisk manages root itself instead of using phh's app, none of the following is possible anymore:
- [ ] Controlling access with a PIN
- [ ] Per-app control over root notifications (this is what I really miss) and logging
- [ ] Control over how root works in multiuser environments
- [ ] Removing apps from the list of permitted/denied ones

**Comment by topjohnwu** [comment]
These are planned features, and most work lies in Magisk Manager

For 2. and 4., try to tap the card in your app :)
I should create a tutorial regarding this, people don't seem to notice the expanding cards

**Comment by josephcsible** [comment]
Ah, I tried dragging the cards downward (like expanding a notification) and long-pressing them to no avail. I didn't think to try just a normal tap. Thanks!
