### ISSUE TITLE
 Magisk hide is not working 23016

### ISSUE THREAD

**Issue by swx-tr** [topjohnwu/Magisk#5111]
Device: 
Android version:
Magisk version name: 
Magisk version code:

**Comment by swx-tr** [comment]
Device Pixel 5
23016

**Comment by HuskyDG** [comment]
MagiskHide is removed from Magisk Canary

**Comment by swx-tr** [comment]
I see, what can wee do for hiding from some apps?

**Comment by HuskyDG** [comment]
Two method:
- Enable Zygisk, and enforced the DenyList but riru modules will not work after zygisk is enabled
- Install Magisk alpha, and enable MagiskHide

Remember to install correct Magisk apk

**Comment by swx-tr** [comment]
Thank you so much.
