### ISSUE TITLE
Upgrading to Canary (92546e8a) (23016) causes boot loop on OnePlus 7T Pro with Boot Reason: fs_mgr_mount_all when installing to inactive slot.

### ISSUE THREAD

**Issue by chknatwork** [topjohnwu/Magisk#5119]
Device: OnePlus 7T Pro
Android version: 11
Magisk version name: 92546e8a
Magisk version code: 23016

Causes bootloop to recovery which shows boot reason message. Had to set to a different active slot to get phone to boot.

**Comment by yujincheng08** [comment]
wheres ur log

**Comment by yujincheng08** [comment]
it maybe fixed by #5070

**Comment by osm0sis** [comment]
Or possibly #5134

**Comment by vvb2060** [comment]
no log
