### ISSUE TITLE
Magisk wont boot Canary (92546e8a) (23016) 

### ISSUE THREAD

**Issue by zainullahk** [topjohnwu/Magisk#5123]
i  am on phusson gsi  android 12 and when i flash your canary build it does not boot without magisk it does boot 

Device:  A71
Android version: 12
Magisk version name: CANARY 92546e8a 
Magisk version code: 23016
[boot-loop-kernel-log.txt](https://github.com/topjohnwu/Magisk/files/7776832/boot-loop-kernel-log.txt)

**Comment by yujincheng08** [comment]
#4760

**Comment by zainullahk** [comment]
what can i do with this?

**Comment by zainullahk** [comment]
@osm0sis why is this a duplicate?

**Comment by osm0sis** [comment]
Because of #4402

**Comment by zainullahk** [comment]
That is on dsu
This is on a gsi when it is flashed on the actual system

**Comment by osm0sis** [comment]
Well I think this is technically the latest then: https://github.com/topjohnwu/Magisk/issues/844#issuecomment-782994903

**Comment by zainullahk** [comment]
@osm0sis  please open this issue again as that fix has been merged and my issue is not fixed
