### ISSUE TITLE
Repacking kernel causes bootloop on many MT6763 devices

### ISSUE THREAD

**Issue by Smankusors** [topjohnwu/Magisk#5124]
Device: Oppo F5 Youth (CPH1725)
Android version: 7.1.1
Magisk version name: 92546e8a
Magisk version code: 23016

Hello everyone, I tried to root my device using Magisk .But after flashed the patched boot.img, my device bootlooped, it's stuck at Oppo logo, and then resetting itself again. 😭

When I flashed the before Magisk patched boot.img, it returns to normal

Here I uploaded the `/proc/last_kmsg` and `/proc/mounts`. I also included the... non-stock boot.img I used to patch (contexts in the bottom of this post). But I also used the stock boot.img, it didn't work either.

~[last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/7777169/last_kmsg.txt)~ (wrong last_kmsg)
[mounts.txt](https://github.com/topjohnwu/Magisk/files/7777173/mounts.txt)
[boot.zip](https://github.com/topjohnwu/Magisk/files/7777179/boot.zip)

---

Some contexts about this device,
* The firmware that I used is version A41
* I think I accidentally broke the i2c interface? The battery doesn't want to charge, the touchscreen didn't work
* The boot.img I attached was modified before patched by Magisk. But the bootloop is not caused by this, because the stock boot.img also didn't work
  * I moved the system and data partition out from eMMC to external microSD, so it make me easier to browse the filesystem when I don't have the root
  * Modification to force enable the OTG function (it's on "SMANKUSORS defined code" section)

**Comment by yujincheng08** [comment]
last_kmsg shows nothing about magisk.

**Comment by Smankusors** [comment]
> last_kmsg shows nothing about magisk.

hmm it seems to be replaced by the charging mode, I will try again tomorrow...

**Comment by Smankusors** [comment]
oh no. It's nothing now. Here is the content of `/proc/last_kmsg`

```
ram console header, hw_status: 0, fiq step 0.
Not Clear, old status is 0.
```

I think the kernel failed to load? Because usually the power cuts off after the kernel initialized. But after patched by Magisk, the power never cuts off, and then reset itself.

**Comment by Smankusors** [comment]
oh finally, I got it working by revert patched kernel to the original kernel. Seems something gone wrong with this?

```
Patch @ 0121F78F [736B69705F696E697472616D667300] -> [77616E745F696E697472616D667300]
```

**Comment by yujincheng08** [comment]
send your original boot.img

**Comment by Smankusors** [comment]
I did on the first post, the boot.zip. Well it's not stock, but the kernel is still in stock condition

**Comment by yujincheng08** [comment]
If hex patching kernel causes the issue, it cannot be fixed by Magisk. Use custom kernel instead.

**Comment by Smankusors** [comment]
couldn't that be adding an option to the Magisk app to not do the hex patching? The Magisk works fine with the stock kernel though

**Comment by yujincheng08** [comment]
As long as a kernel source of your device is provided, we cannot fix it. Just leave this issue open as a tracker.

**Comment by Fox2Code** [comment]
The hexpatch is for system as root which is an Andorid 10 thing, could the patch be disabled for older Andorid versions as it is not required, I doubt Andorid 7.1.1 needs a patch designed for Android 10 and after.

I think putting Andorid 8 (Because of project treble) as the minimum API level to apply this patch seems a fine thing to do.

I don't see any devices older than that having use of this patch.

**Comment by gghhkm** [comment]
[magisk_patched-25200_UD3Vz.img.zip](https://github.com/topjohnwu/Magisk/files/9277349/magisk_patched-25200_UD3Vz.img.zip)

**Comment by canyie** [comment]
Another user reports the bootloop also happens while the SAR kernel patch is not applied, probably the kernel patch is not the reason of bootloops. Can you try this build?
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/9764479/app-debug.zip)

**Comment by canyie** [comment]
Can you try this build?https://github.com/canyie/Magisk/actions/runs/4150249379
