### ISSUE TITLE
Deny list breaks text forms on apps

### ISSUE THREAD

**Issue by SyoAzure** [topjohnwu/Magisk#5127]
When an app with text form (ie. banking apps and Google PlayStore) is added in the deny list if the app is open  on a text form the app force close, if the app is removed from deny list it open normally, this only happen in A12 roms

Device: Redmi Note 7
Android version: 12
Magisk version name: 92546e8a
Magisk version code: 23016

**Comment by yujincheng08** [comment]
no log no fix.
