### ISSUE TITLE
Magisk Hide not working for CrackProof protection

### ISSUE THREAD

**Issue by lijun0326** [topjohnwu/Magisk#513]
应用：https://play.google.com/store/apps/details?id=jp.co.cygames.princessconnectredive
现象：magisk hide对该应用启动并使用随机包名隐藏，并且关闭adb调试，应用可以打开20秒左右，之后检测到root闪退，v1.6.0以及之前版本无此症状（未加壳）
壳的说明：https://www.hypertech.co.jp/en/products/crackproof-for-android-so/
#442 也是这个壳，同样的症状
真心希望作者可以抽空研究下这个壳QAQ

**Comment by ok8634673** [comment]
不能玩公主链接我要死了.jpg

**Comment by polarbear127** [comment]
The same problem here  Magisk hide doesn't work anymore :(

**Comment by funnypro** [comment]
话说没有安装Xposed吧？

**Comment by lijun0326** [comment]
明显没有。。

滑稽Pro <notifications@github.com> 于 2018年9月2日周日 08:58写道：

**Comment by funnypro** [comment]
@lijun0326 等开发者回复好了

**Comment by lijun0326** [comment]
非常感谢！！

**Comment by lijun0326** [comment]
If someone don't want to compile or wait for next release:
@ok8634673 
[Magisk-v17.1.1.zip](https://github.com/topjohnwu/Magisk/files/2364232/Magisk-v17.1.1.zip)
