### ISSUE TITLE
Bootloop after flashing patched Magisk image on Samsung Galaxy M52 

### ISSUE THREAD

**Issue by rjhigh** [topjohnwu/Magisk#5136]
Hi everyone,

Followed steps just as per Magisk install doc. Patched the AP tar file. On flashing the patched image, the device boots till below image, turns off, erases once, comes back to the below screen and this continues.  
No TWRP available for this device currently.

Device: Samsung Galaxy M52
Android version: Android 11 (September 1st 2021 patch) (OneUI v3.1)
Magisk version name: v23.0
Magisk version code: 23016

Attaching log captured via *#9900#. First flashed patched image, device rebooted, flashed with stock firmware and then captured this log.zip
[log.zip](https://github.com/topjohnwu/Magisk/files/7784697/log.zip)
[magisk_install_log_2021-09-16T12_59_57Z.log](https://github.com/topjohnwu/Magisk/files/7784700/magisk_install_log_2021-09-16T12_59_57Z.log)
![IMG_3240](https://user-images.githubusercontent.com/22727692/147568101-896a36b5-fcb7-4d53-a253-2abacc3fda60.jpeg)

**Comment by yujincheng08** [comment]
Basically the same as #4966: `magiskinit` launches itself endlessly.

**Comment by yujincheng08** [comment]
Please use this magisk to grab the log again: https://github.com/topjohnwu/Magisk/issues/4966#issuecomment-1001109632

**Comment by exocetdj** [comment]
i am having the same issue on F926B (fold 3) -> i used the aforementioned build and still got stuck at the red text screen unfortunately

**Comment by yujincheng08** [comment]
> i used the aforementioned build and still got stuck at the red text screen

That's for grabbing log, not for a fix. So send the log, otherwise, no fix will be done.

**Comment by exocetdj** [comment]
well that's how things work lol! 

so,  what i was told would happen with that debug build would be a blank screen appearing after red text screen - this would be the point at which i take the log. 

In light of this, when would one grab the log when booted into system following restore? just concerned that any useful information will be lost as i am unable to take a log at the red text screen of course.

**Comment by yujincheng08** [comment]
generate a bugreport.(*#9900#) I will contain last kmsg if exists.

**Comment by exocetdj** [comment]
many thanks ill do that now

**Comment by exocetdj** [comment]
apologies if this is TMI but i have found these after run
[dumpstate_lastkmsg_229_20211228_182255_MP.log.gz](https://github.com/topjohnwu/Magisk/files/7785993/dumpstate_lastkmsg_229_20211228_182255_MP.log.gz)
ning dumpstate/logcat under *#9900#

[dumpstate_latest_lastkmsg.log.gz](https://github.com/topjohnwu/Magisk/files/7785994/dumpstate_latest_lastkmsg.log.gz)

**Comment by yujincheng08** [comment]
That's the right log but hv u install this magisk: https://github.com/topjohnwu/Magisk/issues/4966#issuecomment-1001109632 ?

**Comment by exocetdj** [comment]
yep - i flashed it via twrp (and then had to reflash stock recovery after due to the incompatibility with current TWRP and a12) and then rebooted - i then had the familiar issue with deadloop on red text screen. 

i let it hang for a few mins but then went to download to flash stock so i could reboot and do *#9900#

**Comment by yujincheng08** [comment]
steps are right but the log is not right hmm. I will send you another version.

**Comment by exocetdj** [comment]
Many thanks

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7786089/app-debug.zip)
Here you are. Grab the log with the same steps.

**Comment by exocetdj** [comment]
that's great - thanks for sorting that logs to follow shortly

**Comment by yujincheng08** [comment]
@exocetdj so where's the log

**Comment by exocetdj** [comment]
sorry, my kids had invaded my android time -> im just restoring stock now to grab the logs, the loop was defo shorter on this one so we should be on to a winner with these. logs in 10/15 mins

**Comment by exocetdj** [comment]
No kmsg in that one, ill rerun the flash to make sure i didnt muck something up

**Comment by exocetdj** [comment]
@yujincheng08 please see below - apologies for delay - these are captured following flashing the app-debug you supplied

[dumpstate_lastkmsg_237_20211228_212111_KP.log.gz](https://github.com/topjohnwu/Magisk/files/7786382/dumpstate_lastkmsg_237_20211228_212111_KP.log.gz)
[dumpstate_latest_lastkmsg.log.gz](https://github.com/topjohnwu/Magisk/files/7786384/dumpstate_latest_lastkmsg.log.gz)

**Comment by yujincheng08** [comment]
Ok, I found the core issue:
```
<14>[    1.955375] [5:           init:    1]  init: Switching root to '/first_stage_ramdisk'
<14>[    1.955531] [5:           init:    1]  init: [libfs_mgr]ReadFstabFromDt(): failed to read fstab from dt
<11>[    1.955792] [5:           init:    1]  init: [libfs_mgr]Error updating for slotselect
<11>[    1.955797] [5:           init:    1]  init: [libfs_mgr]ReadFstabFromFile(): failed to load fstab from : '/fstab.qcom'
<14>[    1.955803] [5:           init:    1]  init: Failed to fstab for first stage mount
```

**Comment by yujincheng08** [comment]
@exocetdj could you share the stock boot.img?

**Comment by yujincheng08** [comment]
@exocetdj and btw could you upload the current kmsg (that is, the kmsg for a normal boot with stock boot.img)?

**Comment by exocetdj** [comment]
great work!!

yep there's no fstab.qcom that i know of in a12 on my device anyway as its been renamed - boot image incoming and ill reboot a couple of times and get that kmsg

**Comment by exocetdj** [comment]
stock BUL6 F926B boot.img (zipped)

[boot.zip](https://github.com/topjohnwu/Magisk/files/7786553/boot.zip)

**Comment by exocetdj** [comment]
stock boot logs


[dumpstate_latest_lastkmsg.log.gz](https://github.com/topjohnwu/Magisk/files/7786584/dumpstate_latest_lastkmsg.log.gz)
[dumpstate_lastkmsg_237_20211228_212111_KP.log.gz](https://github.com/topjohnwu/Magisk/files/7786585/dumpstate_lastkmsg_237_20211228_212111_KP.log.gz)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7786598/app-debug.zip)
Use this magisk to grab log. Expectedly, your device should boot normally but without magisk.

**Comment by yujincheng08** [comment]
I know what's going on now. Will fix it soon.

**Comment by exocetdj** [comment]
this build did actually boot - will grab logs regardless

**Comment by yujincheng08** [comment]
Yes, this build should boot. I missed another thing.

But anyway, try this build, it should work:
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7786652/app-debug.zip)

**Comment by exocetdj** [comment]
yep i will do now, many thanks

**Comment by exocetdj** [comment]
looking good i think, what do you reckon?

![image](https://user-images.githubusercontent.com/59484940/147614251-9da28525-6e5f-47bc-9811-01aae9792db1.png)

**Comment by yujincheng08** [comment]
@exocetdj See #5139 for details.

**Comment by exocetdj** [comment]
@yujincheng08 many thanks for sorting this out - i will have a test and update if i face any issues

**Comment by exocetdj** [comment]
do you need anything further from me? i am new to github

**Comment by yujincheng08** [comment]
No more needed. But you can test the CI build of my PR if you wish. Thanks for your cooperation.

**Comment by exocetdj** [comment]
thanks and will do. big respect to you mate

**Comment by rjhigh** [comment]
@yujincheng08 [This](https://github.com/topjohnwu/Magisk/actions/runs/1632622731) has worked beautifully.  Let me know if you still need [these](https://github.com/topjohnwu/Magisk/issues/5136#issuecomment-1002190900) logs . Thanks much.

**Comment by yujincheng08** [comment]
@exocetdj @rjhigh Hi, could you do me a favor to have a test about #5146? This PR may have a conflict with my previous fix #5139 and my lead to a bootloop on Samsung devices. If there's bootloop could you also provide lastkmsg? Many thanks.

**Comment by exocetdj** [comment]
Yep will do when I'm at my PC in the morning UK time. Not a problem at all

**Comment by exocetdj** [comment]
My rom teammate has tested 5146 and it boots rooted absolutely fine

**Comment by exocetdj** [comment]
I will confirm after work also

**Comment by yujincheng08** [comment]
@exocetdj Thanks for your info!

**Comment by exocetdj** [comment]
No problem and thanks for sorting this out - i have a few happy rom users now :)

Also thanks for the opportunity to test - i have since tested the newer build and its functioning well with root and the modules i have installed (Audio mod library, bluetooth lib patcher, Universal safteynet fix, viper4android and my own cscfeatures and fonts module) are all working. Happy new year!!
