### ISSUE TITLE
Magisk denylist break input manager

### ISSUE THREAD

**Issue by SyoAzure** [topjohnwu/Magisk#5153]
If Denylist is activated the apps on the deny list crashes due the input form is not loading, I attach the logs from Magisk and Logcat reader from an app in the denylist, this only happens on Android 12

[logcat_12-31-2021_01-01-49.txt](https://github.com/topjohnwu/Magisk/files/7795561/logcat_12-31-2021_01-01-49.txt)
[magisk_log_2021-12-31T01_05_13Z.log](https://github.com/topjohnwu/Magisk/files/7795562/magisk_log_2021-12-31T01_05_13Z.log)

Device: Redmi Note 7
Android version: 12
Magisk version name: 92546e8a
Magisk version code: 23016

**Comment by yujincheng08** [comment]
Uninstall any font module.

**Comment by vvb2060** [comment]
This is the expected behavior of Android 12.
