### ISSUE TITLE
Samsung A52s 5G bootloop

### ISSUE THREAD

**Issue by A-johani** [topjohnwu/Magisk#5156]
Device: Samsung Galaxy A52s 5G (SM-A528B)
Android version: 11
Magisk version name: 92546e8
Magisk version code: 23016

this device bootloops with the latest canary version  & no way to collect kernel log without root , also we dont have TWRP for the device .

boot.img : 
[boot.zip](https://github.com/topjohnwu/Magisk/files/7798342/boot.zip)

**Comment by canyie** [comment]
maybe fixed by #5139

**Comment by A-johani** [comment]
where can we try the fix ?

> maybe fixed by #5139

**Comment by canyie** [comment]
https://github.com/topjohnwu/Magisk/actions/runs/1632403163

**Comment by A-johani** [comment]
> https://github.com/topjohnwu/Magisk/actions/runs/1632403163

it still bootlooped

**Comment by Janer1** [comment]
Did you uninstall old magisk and installed the app-release of it?

**Comment by A-johani** [comment]
> Did you uninstall old magisk and installed the app-release of the one posted by canyie

yes , its worth mentioning that am on phh gsi

**Comment by Janer1** [comment]
> > Did you uninstall old magisk and installed the app-release of the one posted by canyie
> 
> yes , its worth mentioning that am on phh gsi

You didn't do it on stock? Iirc, I think there's a pre-rooted ohh gsi. I used it on my tab S7 Fe before root was fixed for us

**Comment by A-johani** [comment]
> > > Did you uninstall old magisk and installed the app-release of the one posted by canyie
> > 
> > 
> > yes , its worth mentioning that am on phh gsi
> 
> You didn't do it on stock? Iirc, I think there's a pre-rooted ohh gsi. I used it on my tab S7 Fe before root was fixed for us

its root but not magisk , is there a way to retain root from stock to gsi ?

**Comment by zainullahk** [comment]
#4760

**Comment by yujincheng08** [comment]
Try #5146

**Comment by yujincheng08** [comment]
> no way to collect kernel log without root

bugreport can collect kernel log without root...

**Comment by A-johani** [comment]
> Try #5146

It's also bootloop


> > no way to collect kernel log without root
> 
> bugreport can collect kernel log without root...

Where i can find it ??

**Comment by yujincheng08** [comment]
@A-johani https://developer.android.com/studio/debug/bug-report

**Comment by A-johani** [comment]
> @A-johani https://developer.android.com/studio/debug/bug-report

Ok here you go :
[bugreport-a52sxq-SQ1A.211205.008-2022-01-05-03-36-30-dumpstate_log-4819.txt](https://github.com/topjohnwu/Magisk/files/7811250/bugreport-a52sxq-SQ1A.211205.008-2022-01-05-03-36-30-dumpstate_log-4819.txt)
[bugreport-a52sxq-SQ1A.211205.008-2022-01-05-03-36-30.zip](https://github.com/topjohnwu/Magisk/files/7811251/bugreport-a52sxq-SQ1A.211205.008-2022-01-05-03-36-30.zip)
[dumpstate-stats.txt](https://github.com/topjohnwu/Magisk/files/7811253/dumpstate-stats.txt)

**Comment by yujincheng08** [comment]
I cannot see anything about magisk in your bugreport. You should flash Magisk pathed boot.img, reboot and let the phone bootloop for a while and flash the original boot.img and reboot and grab the bug report.

**Comment by A-johani** [comment]
> I cannot see anything about magisk in your bugreport. You should flash Magisk pathed boot.img, reboot and let the phone bootloop for a while and flash the original boot.img and reboot and grab the bug report.

ok try this : 
[bugreport.zip](https://github.com/topjohnwu/Magisk/files/7812334/bugreport.zip)
[bugreport.txt](https://github.com/topjohnwu/Magisk/files/7812336/bugreport.txt)
[dumpstate.txt](https://github.com/topjohnwu/Magisk/files/7812337/dumpstate.txt)

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/148169562-345bbc53-c9e3-4bbc-8e6a-a8a8f3d09768.png)
Crashes around here. will send you a version with more log.

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7812442/app-debug.zip)
Flash this Magisk and do the same step to grab bug report.

**Comment by A-johani** [comment]
> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/7812442/app-debug.zip) Flash this Magisk and do the same step to grab bug report.

hi , sorry i dont have TWRP , not available for our device

can give me the apk ?

**Comment by yujincheng08** [comment]
rename .zip to .apk

Github does not support uploading .apk so I renamed it to .zip.

**Comment by A-johani** [comment]
ok , here it is :

[bugreport.zip](https://github.com/topjohnwu/Magisk/files/7816830/bugreport.zip)
[bugreport.txt](https://github.com/topjohnwu/Magisk/files/7816832/bugreport.txt)
[dumpstate.txt](https://github.com/topjohnwu/Magisk/files/7816834/dumpstate.txt)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7816900/app-debug.zip)
use this to grab bug report

**Comment by yujincheng08** [comment]
Okay, found the problem:
```
<12>[    1.693013] [7:           init:    1]  magiskinit: cil: Building AST from Parse Tree
<12>[    1.693013] [7:           init:    1]  
<12>[    1.727396] [7:           init:    1]  magiskinit: cil: Re-declaration of typealias sysfs_usb_supply
<12>[    1.727396] [7:           init:    1]  
<12>[    1.727411] [7:           init:    1]  magiskinit: cil: Previous declaration of type
<12>[    1.727424] [7:           init:    1]  magiskinit: cil:  at /system_ext/etc/selinux/system_ext_sepolicy.cil:58
<12>[    1.727429] [7:           init:    1]  magiskinit: cil: 
<12>[    1.727429] [7:           init:    1]  
<12>[    1.727433] [7:           init:    1]  magiskinit: cil: Bad typealias declaration
<12>[    1.727438] [7:           init:    1]  magiskinit: cil:  at /vendor/etc/selinux/vendor_sepolicy.cil:824
<12>[    1.727442] [7:           init:    1]  magiskinit: cil: 
<12>[    1.727442] [7:           init:    1]  
<12>[    1.727446] [7:           init:    1]  magiskinit: cil: Problem
<12>[    1.727451] [7:           init:    1]  magiskinit: cil:  at /vendor/etc/selinux/vendor_sepolicy.cil:824
<12>[    1.727454] [7:           init:    1]  magiskinit: cil: 
<12>[    1.727454] [7:           init:    1]  
<12>[    1.727459] [7:           init:    1]  magiskinit: cil: Failed to build ast

```

**Comment by yujincheng08** [comment]
you are using a userdebug rom. so can you `adb root`?

**Comment by yujincheng08** [comment]
Please try this:
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7818862/app-debug.zip)

**Comment by A-johani** [comment]
> Please try this: [app-debug.zip](https://github.com/topjohnwu/Magisk/files/7818862/app-debug.zip)



> Please try this: [app-debug.zip](https://github.com/topjohnwu/Magisk/files/7818862/app-debug.zip)

Sorry for the delay , am at work , few hours and i will try it , thanks

**Comment by yujincheng08** [comment]
Also, could you grab a bugreport after rebooting from a normal boot?
and a bugreport after recovering from #5146

**Comment by yujincheng08** [comment]
OK, this bug is from this commit:
https://github.com/phhusson/platform_external_selinux/commit/92f05d0daa9acbef1ffb1139473099b0652208c6#diff-50e51ff57d3ae808906395ca0f39371b58c11b862e0cd698c66b7910b0507cf6R142-R149

Cannot be fixed by Magisk. Luckily, you can make your own customized magisk for phh. Here is an example:
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7819601/app-debug.zip).

With patch:

[phh.zip](https://github.com/topjohnwu/Magisk/files/7819607/phh.zip)

**Comment by A-johani** [comment]
> OK, this bug is from this commit: [phhusson/platform_external_selinux@92f05d0#diff-50e51ff57d3ae808906395ca0f39371b58c11b862e0cd698c66b7910b0507cf6R142-R149](https://github.com/phhusson/platform_external_selinux/commit/92f05d0daa9acbef1ffb1139473099b0652208c6#diff-50e51ff57d3ae808906395ca0f39371b58c11b862e0cd698c66b7910b0507cf6R142-R149)
> 
> Cannot be fixed by Magisk. Luckily, you can make your own customized magisk for phh. Here is an example: [app-debug.zip](https://github.com/topjohnwu/Magisk/files/7819601/app-debug.zip).
> 
> With patch:
> 
> ```diff
> Submodule native/jni/external/selinux contains modified content
> diff --git a/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c b/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c
> index 60ecaaff..b926780b 100644
> --- a/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c
> +++ b/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c
> @@ -143,8 +143,14 @@ int cil_gen_node(struct cil_db *db, struct cil_tree_node *ast_node, struct cil_s
>  					cil_node_to_string(ast_node), key);
>  				cil_tree_log(node, CIL_ERR, "Previous declaration of %s",
>  					cil_node_to_string(node));
> -				rc = SEPOL_ERR;
> -				goto exit;
> +				if (strcmp(key, "sysfs_usb_supply") == 0 ||
> +					strcmp(key, "hostapd") == 0 ||
> +					strcmp(key, "rpmb_device") == 0) {
> +					cil_log(CIL_ERR, "Ignoring...");
> +				} else {
> +					rc = SEPOL_ERR;
> +					goto exit;
> +				}
>  			}
>  			/* multiple_decls is enabled and works for this datum type, add node */
>  			cil_list_append(prev->nodes, CIL_NODE, ast_node);
> ```

sorry to say still bootloops ,
is the patch already integrated ??

**Comment by yujincheng08** [comment]
Integrated. If it still bootloops you can provide bugreport.

**Comment by A-johani** [comment]
> Integrated. If it still bootloops you can provide bugreport.

[bugreport.zip](https://github.com/topjohnwu/Magisk/files/7819751/bugreport.zip)
[dumpstate.txt](https://github.com/topjohnwu/Magisk/files/7819753/dumpstate.txt)
[bugreport.txt](https://github.com/topjohnwu/Magisk/files/7819754/bugreport.txt)

**Comment by yujincheng08** [comment]
Oh, I missed something else for that build. Use this instead:
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7819803/app-debug.zip)

```diff
Submodule native/jni/external/selinux contains modified content
diff --git a/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c b/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c
index 60ecaaff..b926780b 100644
--- a/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c
+++ b/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c
@@ -143,8 +143,14 @@ int cil_gen_node(struct cil_db *db, struct cil_tree_node *ast_node, struct cil_s
                                        cil_node_to_string(ast_node), key);
                                cil_tree_log(node, CIL_ERR, "Previous declaration of %s",
                                        cil_node_to_string(node));
-                               rc = SEPOL_ERR;
-                               goto exit;
+                               if (strcmp(key, "sysfs_usb_supply") == 0 ||
+                                       strcmp(key, "hostapd") == 0 ||
+                                       strcmp(key, "rpmb_device") == 0) {
+                                       cil_log(CIL_ERR, "Ignoring...");
+                               } else {
+                                       rc = SEPOL_ERR;
+                                       goto exit;
+                               }
                        }
                        /* multiple_decls is enabled and works for this datum type, add node */
                        cil_list_append(prev->nodes, CIL_NODE, ast_node);
diff --git a/native/jni/external/selinux/libsepol/cil/src/cil_resolve_ast.c b/native/jni/external/selinux/libsepol/cil/src/cil_resolve_ast.c
index d1d220f8..491a4e1b 100644
--- a/native/jni/external/selinux/libsepol/cil/src/cil_resolve_ast.c
+++ b/native/jni/external/selinux/libsepol/cil/src/cil_resolve_ast.c
@@ -512,7 +512,12 @@ int cil_resolve_aliasactual(struct cil_tree_node *current, void *extra_args, enu
        }
        if (NODE(alias_datum)->flavor != alias_flavor) {
                cil_log(CIL_ERR, "%s is not an alias\n",alias_datum->name);
-               rc = SEPOL_ERR;
+               if (strcmp(alias_datum->name, "hostapd") == 0 ||
+                       strcmp(alias_datum->name, "sysfs_usb_supply") == 0 ||
+                       strcmp(alias_datum->name, "rpmb_device") == 0)
+                       rc = 0;
+               else
+                       rc = SEPOL_ERR;
                goto exit;
        }

@@ -554,6 +559,10 @@ int cil_resolve_alias_to_actual(struct cil_tree_node *current, enum cil_flavor f

        if (alias->actual == NULL) {
                cil_tree_log(current, CIL_ERR, "Alias declared but not used");
+               if (strcmp(a1->datum.name, "hostapd") == 0 ||
+                       strcmp(a1->datum.name, "sysfs_usb_supply") == 0 ||
+                       strcmp(a1->datum.name, "rpmb_device") == 0)
+                       return SEPOL_OK;
                return SEPOL_ERR;
        }
```

**Comment by A-johani** [comment]
> Oh, I missed something else for that build. Use this instead: [app-debug.zip](https://github.com/topjohnwu/Magisk/files/7819803/app-debug.zip)
> 
> ```diff
> Submodule native/jni/external/selinux contains modified content
> diff --git a/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c b/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c
> index 60ecaaff..b926780b 100644
> --- a/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c
> +++ b/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c
> @@ -143,8 +143,14 @@ int cil_gen_node(struct cil_db *db, struct cil_tree_node *ast_node, struct cil_s
>                                         cil_node_to_string(ast_node), key);
>                                 cil_tree_log(node, CIL_ERR, "Previous declaration of %s",
>                                         cil_node_to_string(node));
> -                               rc = SEPOL_ERR;
> -                               goto exit;
> +                               if (strcmp(key, "sysfs_usb_supply") == 0 ||
> +                                       strcmp(key, "hostapd") == 0 ||
> +                                       strcmp(key, "rpmb_device") == 0) {
> +                                       cil_log(CIL_ERR, "Ignoring...");
> +                               } else {
> +                                       rc = SEPOL_ERR;
> +                                       goto exit;
> +                               }
>                         }
>                         /* multiple_decls is enabled and works for this datum type, add node */
>                         cil_list_append(prev->nodes, CIL_NODE, ast_node);
> diff --git a/native/jni/external/selinux/libsepol/cil/src/cil_resolve_ast.c b/native/jni/external/selinux/libsepol/cil/src/cil_resolve_ast.c
> index d1d220f8..491a4e1b 100644
> --- a/native/jni/external/selinux/libsepol/cil/src/cil_resolve_ast.c
> +++ b/native/jni/external/selinux/libsepol/cil/src/cil_resolve_ast.c
> @@ -512,7 +512,12 @@ int cil_resolve_aliasactual(struct cil_tree_node *current, void *extra_args, enu
>         }
>         if (NODE(alias_datum)->flavor != alias_flavor) {
>                 cil_log(CIL_ERR, "%s is not an alias\n",alias_datum->name);
> -               rc = SEPOL_ERR;
> +               if (strcmp(alias_datum->name, "hostapd") == 0 ||
> +                       strcmp(alias_datum->name, "sysfs_usb_supply") == 0 ||
> +                       strcmp(alias_datum->name, "rpmb_device") == 0)
> +                       rc = 0;
> +               else
> +                       rc = SEPOL_ERR;
>                 goto exit;
>         }
> 
> @@ -554,6 +559,10 @@ int cil_resolve_alias_to_actual(struct cil_tree_node *current, enum cil_flavor f
> 
>         if (alias->actual == NULL) {
>                 cil_tree_log(current, CIL_ERR, "Alias declared but not used");
> +               if (strcmp(a1->datum.name, "hostapd") == 0 ||
> +                       strcmp(a1->datum.name, "sysfs_usb_supply") == 0 ||
> +                       strcmp(a1->datum.name, "rpmb_device") == 0)
> +                       return SEPOL_OK;
>                 return SEPOL_ERR;
>         }
> ```

now it doesn't bootloop but Magisk says not installed
[bugreport.zip](https://github.com/topjohnwu/Magisk/files/7819883/bugreport.zip)
[bugreport.txt](https://github.com/topjohnwu/Magisk/files/7819887/bugreport.txt)
[dumpstate.txt](https://github.com/topjohnwu/Magisk/files/7819888/dumpstate.txt)

**Comment by yujincheng08** [comment]
reboot twice and get the bugreport again.

**Comment by zainullahk** [comment]
thanks for that build! it works for me it says to instal magisk but magisk
itself works !

**Comment by zainullahk** [comment]
> now it doesn't bootloop but Magisk says not installed [bugreport.zip](https://github.com/topjohnwu/Magisk/files/7819883/bugreport.zip) [bugreport.txt](https://github.com/topjohnwu/Magisk/files/7819887/bugreport.txt) [dumpstate.txt](https://github.com/topjohnwu/Magisk/files/7819888/dumpstate.txt)

that does not matter
magisk works 
thats the important part
 if the modules are grayed out flash it again

**Comment by zainullahk** [comment]
> app-debug.zip

will this get branched into main magisk? 
as right now i dont see a way of updating to newer versions

**Comment by A-johani** [comment]
> reboot twice and get the bugreport again.

[bugreport-a52sxq-SQ1A.211205.008-2022-01-06-21-56-51.zip](https://github.com/topjohnwu/Magisk/files/7824106/bugreport-a52sxq-SQ1A.211205.008-2022-01-06-21-56-51.zip)
[bugreport-a52sxq-SQ1A.211205.008-2022-01-06-21-56-51-dumpstate_log-8357.txt](https://github.com/topjohnwu/Magisk/files/7824107/bugreport-a52sxq-SQ1A.211205.008-2022-01-06-21-56-51-dumpstate_log-8357.txt)
[dumpstate-stats.txt](https://github.com/topjohnwu/Magisk/files/7824108/dumpstate-stats.txt)

**Comment by zainullahk** [comment]
@yujincheng08  your one works but updating to the new one does not boot
any idea if this fix will merge into magisk canary?

**Comment by zainullahk** [comment]
> reboot twice and get the bugreport again.

how do i add this fix to magisk stable?

**Comment by A-johani** [comment]
> Oh, I missed something else for that build. Use this instead: [app-debug.zip](https://github.com/topjohnwu/Magisk/files/7819803/app-debug.zip)
> 
> ```diff
> Submodule native/jni/external/selinux contains modified content
> diff --git a/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c b/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c
> index 60ecaaff..b926780b 100644
> --- a/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c
> +++ b/native/jni/external/selinux/libsepol/cil/src/cil_build_ast.c
> @@ -143,8 +143,14 @@ int cil_gen_node(struct cil_db *db, struct cil_tree_node *ast_node, struct cil_s
>                                         cil_node_to_string(ast_node), key);
>                                 cil_tree_log(node, CIL_ERR, "Previous declaration of %s",
>                                         cil_node_to_string(node));
> -                               rc = SEPOL_ERR;
> -                               goto exit;
> +                               if (strcmp(key, "sysfs_usb_supply") == 0 ||
> +                                       strcmp(key, "hostapd") == 0 ||
> +                                       strcmp(key, "rpmb_device") == 0) {
> +                                       cil_log(CIL_ERR, "Ignoring...");
> +                               } else {
> +                                       rc = SEPOL_ERR;
> +                                       goto exit;
> +                               }
>                         }
>                         /* multiple_decls is enabled and works for this datum type, add node */
>                         cil_list_append(prev->nodes, CIL_NODE, ast_node);
> diff --git a/native/jni/external/selinux/libsepol/cil/src/cil_resolve_ast.c b/native/jni/external/selinux/libsepol/cil/src/cil_resolve_ast.c
> index d1d220f8..491a4e1b 100644
> --- a/native/jni/external/selinux/libsepol/cil/src/cil_resolve_ast.c
> +++ b/native/jni/external/selinux/libsepol/cil/src/cil_resolve_ast.c
> @@ -512,7 +512,12 @@ int cil_resolve_aliasactual(struct cil_tree_node *current, void *extra_args, enu
>         }
>         if (NODE(alias_datum)->flavor != alias_flavor) {
>                 cil_log(CIL_ERR, "%s is not an alias\n",alias_datum->name);
> -               rc = SEPOL_ERR;
> +               if (strcmp(alias_datum->name, "hostapd") == 0 ||
> +                       strcmp(alias_datum->name, "sysfs_usb_supply") == 0 ||
> +                       strcmp(alias_datum->name, "rpmb_device") == 0)
> +                       rc = 0;
> +               else
> +                       rc = SEPOL_ERR;
>                 goto exit;
>         }
> 
> @@ -554,6 +559,10 @@ int cil_resolve_alias_to_actual(struct cil_tree_node *current, enum cil_flavor f
> 
>         if (alias->actual == NULL) {
>                 cil_tree_log(current, CIL_ERR, "Alias declared but not used");
> +               if (strcmp(a1->datum.name, "hostapd") == 0 ||
> +                       strcmp(a1->datum.name, "sysfs_usb_supply") == 0 ||
> +                       strcmp(a1->datum.name, "rpmb_device") == 0)
> +                       return SEPOL_OK;
>                 return SEPOL_ERR;
>         }
> ```

please add this commit to canary or bete magisk channel
