### ISSUE TITLE
S21 Snapdragon G9910 bootloop after flashing magisk canary in TWRP

### ISSUE THREAD

**Issue by Ivixmax** [topjohnwu/Magisk#5158]
Device: S21 Snapdragon G9910 
Android version:12
Magisk version name: 92546e8
Magisk version code: 23016

Bootloop after flashing latest magisk canary from TWRP.Also dont work patching AP file of samsung firmware and flashing in Odin,bootloop
[boot.zip](https://github.com/topjohnwu/Magisk/files/7803934/boot.zip)
this is the patched boot img

**Comment by yujincheng08** [comment]
Fixed by #5139

**Comment by Ivixmax** [comment]
> Fixed by #5139

And what is the fix? How can i flash the fix? I cant find the new magisk fixed...

**Comment by yujincheng08** [comment]
Github action https://github.com/topjohnwu/Magisk/actions/runs/1647419297

**Comment by Ivixmax** [comment]
> Github action https://github.com/topjohnwu/Magisk/actions/runs/1647419297

I dont understand you....can you explain me? Sorry for my bad

**Comment by yujincheng08** [comment]
Download the artifact, install the Magisk in it and flash that Magisk.

**Comment by Ivixmax** [comment]
> Download the artifact, install the Magisk in it and flash that Magisk.

Ah okkkk.thanks a lot of.i try😊

**Comment by Ivixmax** [comment]
> Download the artifact, install the Magisk in it and flash that Magisk.

ok,i can confirm that this fix works like a charm now.
i pacthed the AP file of samsung firm(last android 12) and then i flashed from Odin.
Thank you very much!!!!!!!!

**Comment by yujincheng08** [comment]
You can close this issue now.
