### ISSUE TITLE
Suggestion: more logical GUI for MagiskManager

### ISSUE THREAD

**Issue by aapo** [topjohnwu/Magisk#516]
I found it little bit hard to understand logic behind MagiskManager.

In main view MagiskManager now shows latest version and installed version. And installed version means checking 'magisk -v' (checking if there are magisk daemon running).

How about adding third field, something like 'Magisk tools downloaded : v16.0"

And then buttons could be (instead of 'Install'+'Select method'):
*Download newer Magisk tool from update channel
*Upgrade already installed Magisk
*Uninstall Magisk =Unroot
*Generate patched boot.img

**Comment by topjohnwu** [comment]
Magisk Manager will always download the latest zip from the channel you've chosen. There is no way to download and install any old versions.
I don't know what you mean: Magisk tools downloaded?
The current daemon should always match with the tools it requires, or else you might go into some trouble.
