### ISSUE TITLE
Samsung S21 G9910 Android 12  G9910ZCU2BUL3 bootloop

### ISSUE THREAD

**Issue by MelanPrince** [topjohnwu/Magisk#5162]
Device: SM-G9910
Android version:12 G9910ZCU2BUL3
Magisk version name: 92546e8a / 23.0
Magisk version code: 23016 /23000
this device bootloops with the latest canary version. android 11 work.

boot
[boot.zip](https://github.com/topjohnwu/Magisk/files/7804643/boot.zip)

**Comment by yujincheng08** [comment]
Fixed by #5139
