### ISSUE TITLE
Toast is shown behind Navigationbar

### ISSUE THREAD

**Issue by nugel** [topjohnwu/Magisk#5163]
Device: Google Pixel 6 Pro
Android version: 12 SQ1D.211205.016.A1
Magisk version name: 92546e8a
Magisk version code: 23016 (23)

Steps to reproduce: 

- Go to Superuser
- Turn anything on or off
- A confirmation toast is displayed under the navigationbar

Screenshot: https://i.imgur.com/GNk0XIA.png

**Comment by yujincheng08** [comment]
This issue was brought by @RikkaW, and apparently, she is too lazy to fix it.
