### ISSUE TITLE
Open com.android.documentsui in ListView by default

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#517]
Hello,

At each time we want to install a Magisk module through the Magisk Manager app, it open the "Files" app (com.android.documentsui) in the ListView class by default to let the user long-press on a `zip` file to install it.
It is not practical to have to press the button each time to switch between the grid mode display and the list mode display, because in grid mode, the full name of the desired ZIP file is not written entirely. 

If we take the case of a file name that is a bit long with a version number noted at the end of it, then we must switch to list display mode to be able to see exactly the full zip file name.

By opening the "Files" app directly, it opens by default in "list" mode. This phenomenon of opening in grid mode apparently occurs only by opening the application to search for one or more files in particular.

Would it be possible to define the opening method in Class ListView?

Thanks in advance.

**Comment by topjohnwu** [comment]
I don't think this is possible, the way the UI renders depends on your system
