### ISSUE TITLE
SystemUI on Samsung Dex force closes using Magisk Build f303e158 

### ISSUE THREAD

**Issue by exocetdj** [topjohnwu/Magisk#5176]
[dumpstate_lastkmsg_274_20220106_225215_MP.log.gz](https://github.com/topjohnwu/Magisk/files/7825277/dumpstate_lastkmsg_274_20220106_225215_MP.log.gz)
[dumpstate_latest_lastkmsg.log.gz](https://github.com/topjohnwu/Magisk/files/7825280/dumpstate_latest_lastkmsg.log.gz)

As the issue title suggests - after flashing f303e158 build and disabling force encryption, Samsung DEX experiences force closes on SystemUI please see attached logs - no other modifications have been made to the device firmware and no modules installed - please let me know what other info you require

![image](https://user-images.githubusercontent.com/59484940/148466661-dd14f866-5edc-423a-8b79-9cda5111e37a.png)

Device: Z Fold 3
Android version: Android 12
Magisk version name: Alpha
Magisk version code: f303e158 (23016)

**Comment by exocetdj** [comment]
[LOGCAT1914.txt](https://github.com/topjohnwu/Magisk/files/7835926/LOGCAT1914.txt)

That should hopefully show the issue in action (adb logcat)

**Comment by yujincheng08** [comment]
> [LOGCAT1914.txt](https://github.com/topjohnwu/Magisk/files/7835926/LOGCAT1914.txt)
> 

Nothing's helpful from this log

**Comment by exocetdj** [comment]
Thanks for the reply and I was meaning to update here that we have since learned this is due to forcencryption on z fold 3 being disabled so that twrp can be installed. It's another samsung boobytrap.

Happy to report no such issues when tested, rooted with stock recovery installed so magisk is fine in this context.
