### ISSUE TITLE
关于安装到第二分区功能的一些特殊情况

### ISSUE THREAD

**Issue by HikariCalyx** [topjohnwu/Magisk#518]
在中国大陆发售的Nokia手机(不包括Nokia 6 第一代)以及Sharp Aquos S2/S3/S3 mini采用A/B无缝更新机制。

由于在大陆无法访问Google服务，OTA更新均由FIH自己的服务器和更新程序完成。

由于安装到第二分区功能在现在版本的Magisk Manager被拿掉了，这种情况下如何确保OTA完成后将Magisk安装到第二分区的boot？

我可以提供原始固件和解包方法供研究。

**Comment by topjohnwu** [comment]
早在7/20就加回此功能: 07140d33a76f66cdc9a9f5c4d757b0afa52d6eef
請耐心等待更新(很快就會發布了)
