### ISSUE TITLE
Post-fs-data.sh error

### ISSUE THREAD

**Issue by gauchotche** [topjohnwu/Magisk#5185]
Device: ZUK Z2
Android version: 8.1.0
Magisk version name: 92546e8a
Magisk version code: 23016

When trying to run Shamiko it's returning a magisk error. I've tried completely removing and reinstalling magisk, but the same error persists. Magisk log attached in the end.

![WhatsApp Image 2022-01-07 at 18 43 37](https://user-images.githubusercontent.com/33750853/148646658-e6dd8dc3-8933-4b42-a13e-679c2ed6f0db.jpeg)
![WhatsApp Image 2022-01-08 at 09 45 50](https://user-images.githubusercontent.com/33750853/148646616-c479bd33-e434-4789-9b13-560c73e55202.jpeg)
![WhatsApp Image 2022-01-08 at 10 47 43](https://user-images.githubusercontent.com/33750853/148646617-bb9ca95c-61c4-4542-925b-86135a19cf82.jpeg)
![WhatsApp Image 2022-01-08 at 09 10 40](https://user-images.githubusercontent.com/33750853/148646619-104bb168-b89b-4a13-8258-049e8ff4e528.jpeg)
[magisk.log](https://github.com/topjohnwu/Magisk/files/7833399/magisk.log)
.

**Comment by traversone** [comment]
as requested, my experience very similar to previous one

Device: HK1 BOX (S905X3 cpu)
Android version: 9.0, Stock Android Box
Magisk version name: 92546e8
Magisk version code: 23016

---Magisk Logs---
92546e8a (23016)

01-08 19:21:12.014  3357  3357 I : Magisk 92546e8a(23016) daemon started
01-08 19:21:12.016  3357  3357 I : * Device API level: 28
01-08 19:21:12.070  3357  3359 D : resetprop: getprop [ro.crypto.state]: [unencrypted]
01-08 19:21:12.072  3357  3359 I : ** post-fs-data mode running
01-08 19:21:12.072  3357  3359 I : * Mounting mirrors
01-08 19:21:12.076  3357  3359 I : mount: /sbin/.magisk/mirror/product
01-08 19:21:12.076  3357  3359 I : mount: /sbin/.magisk/mirror/vendor
01-08 19:21:12.076  3357  3359 I : mount: /sbin/.magisk/mirror/data
01-08 19:21:12.076  3357  3359 I : link: /sbin/.magisk/mirror/cache
01-08 19:21:12.076  3357  3359 I : link: /sbin/.magisk/mirror/metadata
01-08 19:21:12.076  3357  3359 I : link: /sbin/.magisk/mirror/system
01-08 19:21:12.077  3357  3359 I : mount: /sbin/.magisk/mirror/system_root
01-08 19:21:12.077  3357  3359 I : * Initializing Magisk environment
01-08 19:21:12.156  3357  3359 D : resetprop: decode with protobuf [/data/property/persistent_properties]
01-08 19:21:12.157  3357  3359 D : resetprop: prop [persist.sys.safemode] does not exist
01-08 19:21:12.388  3357  3359 I : * Running post-fs-data.d scripts
01-08 19:21:12.393  3357  3359 D : magiskdb: query zygisk=[1]
01-08 19:21:12.393  3357  3359 D : magiskdb: query denylist=[0]
01-08 19:21:12.393  3357  3359 D : bind_mnt: /sbin/.magisk/modules <- /sbin/.magisk/mirror/data/adb/modules
01-08 19:21:12.411  3357  3359 I : * Running module post-fs-data scripts
01-08 19:21:12.413  3390  3390 I : riru-core: exec [post-fs-data.sh]
01-08 19:21:12.501  3390  3390 I : zygisk_shamiko: exec [post-fs-data.sh]
01-08 19:21:12.533  3357  3359 I : riru-unshare: ignore
01-08 19:21:12.533  3357  3359 I : riru-core: ignore
01-08 19:21:12.533  3357  3359 I : safetynet-fix: ignore
01-08 19:21:12.535  3357  3359 I : * Loading modules
01-08 19:21:12.536  3357  3359 D : bind_mnt: /system/bin/app_process32 <- /sbin/.magisk/zygisk/app_process32
01-08 19:21:12.797  3357  3359 D : zygisk: setup files for pid=[3411]
01-08 19:21:13.395  3411  3411 D : zygisk32: inject 2nd stage
01-08 19:21:14.078  3357  3359 I : ** late_start service mode running
01-08 19:21:14.131  3357  3359 I : * Running module service scripts
01-08 19:21:14.131  3357  3359 I : zygisk_shamiko: exec [service.sh]
01-08 19:21:16.569  3411  3411 I : zygisk32: replaced com/android/internal/os/Zygote#nativeForkAndSpecialize
01-08 19:21:16.569  3411  3411 I : zygisk32: replaced com/android/internal/os/Zygote#nativeForkSystemServer
01-08 19:21:23.228  3357  3359 D : zygisk: setup files for pid=[3811]
01-08 19:21:23.779  3811  3811 D : zygisk32: inject 2nd stage
01-08 19:21:24.333  3811  3811 I : zygisk32: replaced com/android/internal/os/Zygote#nativeForkAndSpecialize
01-08 19:21:24.334  3811  3811 I : zygisk32: replaced com/android/internal/os/Zygote#nativeForkSystemServer
01-08 19:21:35.027  3357  3359 I : ** boot_complete triggered
01-08 19:21:50.093  3357  3359 D : su: request from pid=[5645], client=[13]
01-08 19:21:50.093  3357  3359 D : su: request from uid=[10083]
01-08 19:21:50.093  3357  3359 D : magiskdb: query zygisk=[1]
01-08 19:21:50.093  3357  3359 D : magiskdb: query denylist=[0]
01-08 19:21:50.093  3357  3359 D : su: waiting child pid=[5647]
01-08 19:21:50.094  5647  5647 D : su: fork handler
01-08 19:21:50.097  5647  5647 D : su: use global namespace
01-08 19:22:01.104  3357  5660 D : su: request from pid=[6194], client=[15]
01-08 19:22:01.104  3357  5660 D : su: request from uid=[10059]
01-08 19:22:01.105  3357  5660 D : magiskdb: query zygisk=[1]
01-08 19:22:01.105  3357  5660 D : magiskdb: query denylist=[0]
01-08 19:22:01.107  3357  5660 D : magiskdb: query policy=[2] log=[1] notify=[1]
01-08 19:22:01.118  3357  5660 D : su: waiting child pid=[6202]
01-08 19:22:01.119  6202  6202 D : su: fork handler
01-08 19:22:01.123  6202  6202 D : su: use namespace of pid=[6194]

**Comment by martyfender** [comment]
Device: onn 8 gen one
Android version 9 stock rom
Magisk version: 558710bb-alpha-3
Magisk version code: 23016
I have the above issue also with shamiko installed
[magisk_log_2022-01-09T16_17_54.838.zip](https://github.com/topjohnwu/Magisk/files/7836254/magisk_log_2022-01-09T16_17_54.838.zip)
[last_kmsg.zip](https://github.com/topjohnwu/Magisk/files/7836255/last_kmsg.zip)
[logcat.zip](https://github.com/topjohnwu/Magisk/files/7836257/logcat.zip)

**Comment by vvb2060** [comment]
Assignees to @yujincheng08

**Comment by pndwal** [comment]
@vvb2060, please say why this is closed: can't see a PR.

Is it Shamiko issue (message misleading), or is Post-fs-data.sh error real?

**Comment by vvb2060** [comment]
This is the problem with flock and Shamiko  is using it.

**Comment by pndwal** [comment]
"Shamiko Preview
... Android 8.1+ theoretically supported, but only tested on 11..."

FWIW, I suspect that while Shamiko supports Android 8.1 / 9 in theory, 8.1 / 9 may not be supported in fact... (I'm guessing 'Broken Magisk' error itself may in fact be misleading, and that incompatibility w/ Android 8.1 / 9  may be the real cause of 'failure to run'; Magisk may not be broken at all).

If this is the case I guess it'll be handled in closed source Shamiko...

**Comment by pndwal** [comment]
> This is the problem with flock and Shamiko is using it.

Ah, thanks... Ignore my post above then... Is there likely to be a fix? Problem in Magisk, Shamiko or Android?

**Comment by pndwal** [comment]
> It seems @yujincheng08 could help, but i'm not sure on how to bring this problem to him?

? He's been assigned...
https://github.com/topjohnwu/Magisk/issues/5185#issuecomment-1008555417

And vv has commented... Need to wait... They're collaborators...

**Comment by yujincheng08** [comment]
I am not a collaborator of Magisk though.

**Comment by canyie** [comment]
Magisk works fine. Issue is comes from Shamiko itself.
