### ISSUE TITLE
Disable modules function

### ISSUE THREAD

**Issue by DoganM95** [topjohnwu/Magisk#5188]
Device: Google Pixel 3 xl 
Android version: 12
Magisk version name:  v23.0
Magisk version code: 23016

Not a bug report, but an enhancement / feature request.

Please add a `--disable-modules` flag to the magisk shell utility, so all modules can be disabled.
Currently only `--remove-modules` exists, but deletes all modules. It would be extremely helpful to be able to disable only, 
as you would not need to reinstall all modules again after a bootloop caused by a faulty module.

Even better would be a key-sequence on boot like "power button 5 times" to disable all modules, like xposed had.
Safe mode does not work on many devices with magisk installed, so not an option to disable modules.

**Comment by HuskyDG** [comment]
> Device: Google Pixel 3 xl Android version: 12 Magisk version name: v23.0 Magisk version code: 23016
> 
> Not a bug report, but an enhancement / feature request.
> 
> Please add a `--disable-modules` flag to the magisk shell utility, so all modules can be disabled. Currently only `--remove-modules` exists, but deletes all modules. It would be extremely helpful to be able to disable only, as you would not need to reinstall all modules again after a bootloop caused by a faulty module.
> 
> Even better would be a key-sequence on boot like "power button 5 times" to disable all modules, like xposed had. Safe mode does not work on many devices with magisk installed, so not an option to disable modules.

Use this module if you want, its simple script
https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver

**Comment by DoganM95** [comment]
Thanks, i will use this as a fallback option. 
I think the in-built features i mentioned still need to be implemented to not rely only on modules as core functionality.

**Comment by HuskyDG** [comment]
> Thanks, i will use this as a fallback option.
I think the in-built features i mentioned still need to be implemented to not rely only on modules as core functionality.

Safe mode work for me, actually you don't even need my modules for it.
The features you mention only works if the users enable USG debugging, without it you cannot communicate to adb and execute command.
Also you need a PC or any device else to connect to adb.

**Comment by yujincheng08** [comment]
`touch /data/adb/modules/{module_name}/disable`

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/pull/5030#pullrequestreview-826023782
