### ISSUE TITLE
Zygisk denylist makes app force close

### ISSUE THREAD

**Issue by andrewlowell22** [topjohnwu/Magisk#5192]
Hi I'm trying to hide McDonald's app from magisk because it can't be used with root. So i tried to hide McDonald's app in zygisk, but after i hide it McDonald's app keep force close. I also try to hide another apps and same thing happens. Tried change to magisk v23.0 but still same. Any solution ?

Device: mi 10T
Android version: 11
Magisk version name: 92546e8a
Magisk version code: 23016

**Comment by HuskyDG** [comment]
Zygisk DenyList is not meant for hiding root, it revert all magisk changes.
You can use Shamiko module for hiding purpose.
