### ISSUE TITLE
Huawei phones not supported? 

### ISSUE THREAD

**Issue by Relected** [topjohnwu/Magisk#5200]
why are Huawei devices not supported? I can still unlock my huawei bootloader using PotatoNV  

and I can still flash a custom gsi rom and an unofficial twrp because it's still possible to flash an old stock rom that doesn't have the patches that break magisk

Maybe it's only the instructions that got removed but the tool itself still works? 

Device: huawei y9 fla-lx1 
Android version: 9
Magisk version name: Canary
Magisk version code: 23016

**Comment by justin-himself** [comment]
If the so called Harmony OS is not Android, as Huawei officially claims, then why do you expect to install a ROOT Tool built for Android systems to work on that platform?
I believe the Magisk Project has no reason to continue  supporting a brand that no longer manufactures Android phones, so it is reasonable to remove the support entirely to avoid wasting time on debugging only to adapt Huawei.
However, the older version probably still works for your phone. So enjoy it~

**Comment by Relected** [comment]
@justin-himself but my phone runs android 9 tho? it's from 2018

**Comment by HuskyDG** [comment]
> @justin-himself but my phone runs android 9 emui 9 tho? it's from 2018, I don't know what harmony os is

If you want, read this, since **Huawei** devices doesn't have `boot` partition.
https://github.com/topjohnwu/Magisk/blob/171738787600cba32da5a3f9c39e31e78ba0032a/docs/install.md#huawei
And this issue should be closes since it is invalid
