### ISSUE TITLE
Magisk breaking fingerprint navigation 

### ISSUE THREAD

**Issue by krux3r** [topjohnwu/Magisk#521]
So, I've been having problems on Huawei P10 Lite running a treble rom (Bootleggers 2.3, 8.1.0).

So, the issue is after installing huawei camera/nfc fix magisk module, fingeprint sensor starts acting weirdly.

Treble developer told me to tell the magisk dev about this and I should send him this: https://github.com/phhusson/device_phh_treble/blob/android-8.1/rw-system.sh#L53

I hope that will help somehow.

Thanks in advance!

**Comment by neekless** [comment]
I think you should send this to the module dev

**Comment by krux3r** [comment]
@topjohnwu anything?

**Comment by topjohnwu** [comment]
No logs, no fix.

**Comment by phhusson** [comment]
Additional infos:
rw-system.sh is run from init:
https://github.com/phhusson/device_phh_treble/blob/android-8.1/vndk.rc#L3
Its selinux context is "phhsu_context" which is permissive

Its SELinux policy is here: https://github.com/phhusson/device_phh_treble/blob/android-8.1/sepolicy/su.te

**Comment by krux3r** [comment]
Here is the log from boot after installing the module.
[log.txt](https://github.com/topjohnwu/Magisk/files/2382616/log.txt)

**Comment by Dil3mm4** [comment]
@topjohnwu, get over here and take a look, @phhusson stated exactly where the mess happens.

**Comment by krux3r** [comment]
@topjohnwu bump. Everything is included now.

**Comment by krux3r** [comment]
I know you're busy with the new root for Pixel 3, but are there any clues about this @topjohnwu ?

**Comment by topjohnwu** [comment]
Move to a single issue (#844) regarding GSIs
