### ISSUE TITLE
wifi is not working 

### ISSUE THREAD

**Issue by Baanu** [topjohnwu/Magisk#5213]
Device: Mi A1
Android version: 9
Magisk version name: 92546e8a
Magisk version code: 23016

**Comment by Displax** [comment]
Use **same** boot.img from your **same** ROM build.

**Comment by GreenLunar** [comment]
Can you please tell me how to obtain it, in case I've installed [LineageOS](https://download.lineageos.org/tissot)?
I've tried anything to convert that `payload.bin` file from `lineage-18.1-20220118-nightly-tissot-signed.zip`.

**Comment by Displax** [comment]
Use one of this tools:
https://github.com/ssut/payload-dumper-go
https://github.com/sabpprook/payload_dumper

**Comment by GreenLunar** [comment]
@Baanu

Install Lineage 18.1 and then...

> I used the Lineage recovery. Install update. Put the magisk.app in download folder and renamed it to .zip.
Magiskhide did the trick.
> 
> Edit: and it survived the OTA update.

Source:
https://forum.xda-developers.com/t/rom-11-0-unofficial-lineageos-18-1-tissot.4177407/page-8#post-86091669
https://forum.xda-developers.com/m/nonomen.1429674/
