### ISSUE TITLE
[feature request] per-command root permission (as opposed to per-app), perhaps as advanced feature?

### ISSUE THREAD

**Issue by arolano** [topjohnwu/Magisk#5229]
Device:  any 
Android version: 12
Magisk version name: canary
Magisk version code: 23016

Basically, what it says on the tin can, allow particular apps to have their root rights filtered and denied/granted on per-command basis  as opposed to now 

Usecase:
When something like tasker tries to run /path/to/good.sh as root, it is allowed.
Any other root action(s) are denied 
Have a per-action whitelist for chosen app.

Probably a lot of fuss but would somewhat tighten up capacities of massively powerful apps doing root things.

**Comment by topjohnwu** [comment]
Root apps does not run through Magisk per-command. It requests a root shell from Magisk, and then it simply directly interacts with the root shell, which has nothing to do with Magisk. Even more advanced apps will simply launch root services and run Java/native code via Binder IPC, which also have nothing to do with Magisk
