### ISSUE TITLE
Can't install modules in magisk canary

### ISSUE THREAD

**Issue by BlackRxc** [topjohnwu/Magisk#5236]
Can't install modules in magisk canary after update 23017
-->

Device: Samsung Galaxy S21 Exynos
Android version: 12
Magisk version name: 5f4cd50c
Magisk version code: 23017

Video:
[Video with problem](https://drive.google.com/file/d/1HBgCB3VNcYHm5TZxS0h2Ak5K9YVIgkLe/view?usp=drivesdk)

**Comment by canyie** [comment]
Does [this build](https://github.com/topjohnwu/Magisk/actions/runs/1723149826) works and [this build](https://github.com/topjohnwu/Magisk/actions/runs/1723155621) fail?

**Comment by yujincheng08** [comment]
Send the log.

**Comment by BlackRxc** [comment]
[magisk_log_2022-01-21T17_08_25Z.log](https://github.com/topjohnwu/Magisk/files/7914342/magisk_log_2022-01-21T17_08_25Z.log)
it is not work also in the 23016 build.

**Comment by canyie** [comment]
So, it doesn't work even in this build, right? https://github.com/topjohnwu/Magisk/actions/runs/1723149826

**Comment by BlackRxc** [comment]
yes

**Comment by canyie** [comment]
hmmm... how about this: https://github.com/topjohnwu/Magisk/actions/runs/1723134843

**Comment by BlackRxc** [comment]
https://user-images.githubusercontent.com/98125991/150552409-9b79db76-c3e1-4550-8187-e0a80123d301.mp4
