### ISSUE TITLE
[Feature request] Patches for system/sepolicy to integrate required SELinux policies for Magisk when building ROMs

### ISSUE THREAD

**Issue by hmtheboy154** [topjohnwu/Magisk#5254]
Device: PCs with x86_64 CPUs
Android version: 11
Magisk version name: https://github.com/topjohnwu/magisk-files/commit/08bd8f97fe0fc4941bf3ea05db7459905488cd39 
Magisk version code: 23017

Hello, I am currently building custom Android-x86 images and I want to integrate Magisk into the build process so that the image will have root by default. The thing is, while copying files and making init.*.rc is ok (I based on what LSPosed team did with [MagiskOnWSA](https://github.com/LSPosed/MagiskOnWSA/blob/main/.github/workflows/magisk.yml) ) I am still trying to find a way to patch the SELinux policies. I tried to put `magiskpolicy` into the init.*.rc script or init.sh but Magisk still can't show up.
So I wonder if someone could provide a patch to directly add policies into system/sepolicy to make Magisk running without the need of manually patching using `magiskpolicy` tool ?

**Comment by yujincheng08** [comment]
MagiskOnWSA also patches system sepolicies.

**Comment by HuskyDG** [comment]
> MagiskOnWSA also patches system sepolicies.

Is this, right?

```
magiskpolicy --load system/vendor/etc/selinux/precompiled_sepolicy --save system/vendor/etc/selinux/precompiled_sepolicy --magisk "allow * magisk_file lnk_file *"
```

**Comment by hmtheboy154** [comment]
> > MagiskOnWSA also patches system sepolicies.
> 
> Is this, right?
> 
> ```
> magiskpolicy --load system/vendor/etc/selinux/precompiled_sepolicy --save system/vendor/etc/selinux/precompiled_sepolicy --magisk "allow * magisk_file lnk_file *"
> ```

I tried to add this to Android.mk in [bootable/newinstaller](https://git.osdn.net/view?p=android-x86/bootable-newinstaller.git;a=blob;f=Android.mk;h=51b90378d3de201cb8b756754f4b92324bd86d60;hb=refs/heads/r-x86) of Android-x86, add the command from the line 61, I put magiskpolicy in `device/generic/common` but when running the build it just froze.

This is the line when it's trying to make install.img, which already have precompiled_sepolicy from what I saw.

**Comment by hmtheboy154** [comment]
![image](https://user-images.githubusercontent.com/39849246/150790064-ec554f0a-d264-4e66-9873-61db26c40060.png)

`magiskpolicy` is still frozen to run on Linux even with canary build `cbe97cdf`, while stable 23.0 isn't. 
I don't know why but even run like on Temrinal without putting it into any kind of script it still froze
