### ISSUE TITLE
search button in modules section dose not appear

### ISSUE THREAD

**Issue by AbdEl-RahmanKhaled** [topjohnwu/Magisk#5261]
Device:  Redmi Note 10 pro (sweet)
Android version: 12
Magisk version name:  Canary 23018
Magisk version code: cbe97cdf (23018)

![Screenshot_2022-01-24-10-41-32-859_waly kvy tagb rlq](https://user-images.githubusercontent.com/36802135/150750527-5a1f400d-294f-47dd-bfba-79508ee92a81.jpg)

![Screenshot_2022-01-24-10-49-47-586_waly kvy tagb rlq](https://user-images.githubusercontent.com/36802135/150750813-ad805504-6cd5-4e1d-a7b9-0b305260f213.jpg)

**Comment by yujincheng08** [comment]
it's removed
