### ISSUE TITLE
17.0刷入后指纹解锁失效，手动输入密码解锁立刻进入锁屏界面，显示无sim

### ISSUE THREAD

**Issue by armrf** [topjohnwu/Magisk#528]
重新插卡也不行，刷会16.7正常，同时从release下载的5.9.0也是无法解析安装包（5.7.0及以前的可以直接安装）。不会上传附件只能把日志复制到这里希望有帮助

**Comment by funnypro** [comment]
你这个日志是16.7的啊……

**Comment by armrf** [comment]
17.1又刷了一次，还是这个问题，操作步骤magisk manager还原镜像，然后到rec刷了卸载包，再刷17.1。
(∩_∩)再rec刷入当前版本是不是以前的日志记录？

**Comment by funnypro** [comment]
听上去似乎很扯淡
但是能不能请把问题详情的日志内容去掉……
它多到我尝试回复你时Fasthub会停止运行

**Comment by funnypro** [comment]
听上去似乎很扯淡
但是能不能请把问题详情的日志内容去掉……
它多到我尝试回复你时Fasthub会停止运行

**Comment by funnypro** [comment]
听上去似乎很扯淡
但是能不能请把问题详情的日志内容去掉……
它多到我尝试回复你时Fasthub会停止运行

**Comment by funnypro** [comment]
我先去升级一下Fasthub
如果升级到最新版还有这个问题的话那真是太糟糕了

**Comment by funnypro** [comment]
我已经被Fasthub的停止折服了
本以为Magisk会把所有日志全数输出的
假设是的话在/sbin/.core/img/.core/post-fs-data.d/下面新建一个文件
#!/system/bin/sh
logcat -b main -b events -b crash -v threadtime >/data/u3d_bugtest.log
然后随便命名就行，文件权限770
然后刷入Magisk17.1并把所有问题重新复现数次
然后记得把/sbin/.core/img/.core/post-fs-data.d/下面的那个文件删掉，再刷回Magisk16.7
然后用github的桌面网页上传附件（不过不是很推荐，日志中可能包含隐私信息）
看不懂的话用Chrome的网页翻译（不过操作时个人建议不要用翻译后的状态操作，因为这会出现奇奇怪怪的问题）

**Comment by topjohnwu** [comment]
詳情不明，關閉issue
