### ISSUE TITLE
Samsung SM-G900V Phone Slow and Unresponsive on Wi-Fi or LTE.

### ISSUE THREAD

**Issue by twindragon6** [topjohnwu/Magisk#5283]
Device: Samsung SM-G900V (KLTE)
Android version: 11
Magisk version name: e8f31c78
Magisk version code: 24001

Lineage-18.1-20220123-nightly-klte-signed
[boot.zip](https://github.com/topjohnwu/Magisk/files/7945659/boot.zip)
[magisk_patched-24001_yNfuD.zip](https://github.com/topjohnwu/Magisk/files/7945660/magisk_patched-24001_yNfuD.zip)

Rooted Logs:
[magisk_log_2022-01-26T03_25_08.log](https://github.com/topjohnwu/Magisk/files/7945665/magisk_log_2022-01-26T03_25_08.log)
[magisk_log_2022-01-26T03_27_49.log](https://github.com/topjohnwu/Magisk/files/7945666/magisk_log_2022-01-26T03_27_49.log)
[magisk_log_2022-01-26T03_27_56.log](https://github.com/topjohnwu/Magisk/files/7945667/magisk_log_2022-01-26T03_27_56.log)
[magisk_log_2022-01-26T03_47_52.log](https://github.com/topjohnwu/Magisk/files/7945668/magisk_log_2022-01-26T03_47_52.log)
[magisk_log_2022-01-26T03_50_51.log](https://github.com/topjohnwu/Magisk/files/7945669/magisk_log_2022-01-26T03_50_51.log)
[magisk_log_2022-01-26T03_56_20.log](https://github.com/topjohnwu/Magisk/files/7945670/magisk_log_2022-01-26T03_56_20.log)
[magisk_log_2022-01-26T03_57_37.log](https://github.com/topjohnwu/Magisk/files/7945671/magisk_log_2022-01-26T03_57_37.log)
[magisk_log_2022-01-26T03_59_29.log](https://github.com/topjohnwu/Magisk/files/7945673/magisk_log_2022-01-26T03_59_29.log)

Rooted Matlog:
[logs-2022-01-26-03-59-54.zip](https://github.com/topjohnwu/Magisk/files/7945674/logs-2022-01-26-03-59-54.zip)
[logs-2022-01-26-03-33-14.zip](https://github.com/topjohnwu/Magisk/files/7945675/logs-2022-01-26-03-33-14.zip)

Non-Rooted Logs:
[magisk_log_2022-01-24T21_05_51.log](https://github.com/topjohnwu/Magisk/files/7945677/magisk_log_2022-01-24T21_05_51.log)

build.board: MSM8974
build.bootloader: G900VVRU2DQL1
build.brand: samsung
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: kltevzw
build.display: lineage_klte-userdebug 11 RQ3A.211001.001 10038725
build.fingerprint: samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CRH1:user/release-keys
build.hardware: qcom
build.host: lineage-buildkite
build.id: RQ3A.211001.001
build.manufacturer: samsung
build.model: SM-G900V
build.product: kltevzw
build.radio: unknown
build.serial: unknown
build.tags: release-keys
build.time: 1642905566000
build.type: userdebug
build.user: buildkite-agent
version.codename: REL
version.incremental: 10038725
version.release: 11
version.sdk_int: 30

Modems:
20180118_G900V_QL1_BASEBAND-FIRMWARE_MODEM
20180118_G900V_QL1_MODEM
20180118_G900V_QL1_MODEM_NON-HLOS

**Comment by vvb2060** [comment]
Is there any evidence that this was caused by magisk?

**Comment by twindragon6** [comment]
Yes
[magisk_log_2022-01-27T19_00_47.log](https://github.com/topjohnwu/Magisk/files/7955970/magisk_log_2022-01-27T19_00_47.log)
[magisk_log_2022-01-27T21_29_28.log](https://github.com/topjohnwu/Magisk/files/7955971/magisk_log_2022-01-27T21_29_28.log)
[logs-2022-01-27-19-20-22.zip](https://github.com/topjohnwu/Magisk/files/7955972/logs-2022-01-27-19-20-22.zip)
[logs-2022-01-27-21-28-56.zip](https://github.com/topjohnwu/Magisk/files/7955973/logs-2022-01-27-21-28-56.zip)

**Comment by topjohnwu** [comment]
#5307
