### ISSUE TITLE
Canary and Beta dont work on older 64 Bit Devices (Problem is with new Canary too)

### ISSUE THREAD

**Issue by Hylianer95** [topjohnwu/Magisk#5294]
Good Day , i tryed the new Beta and the Manager dont work, same with the new Canary.
The Changelog say 64Bit are only supported, but my S8 (G950F) is a 64 Bit Device.
Manager23.0 work with Canary and Beta, but Magisk Hide Dont work and Zygisk isnt here.
But Manager Canary dont work with Canary Magisk, but with Magisk 23 and Canary.
same with Beta.

Canary and Beta work fine on my S21 and S21 Ultra.

![dddd](https://user-images.githubusercontent.com/78214536/151408906-cab85aaa-768a-4532-be82-99871e4036c5.png)

Device:  G950F
Android version: 9
Magisk version name: 24001
Magisk version code: 24001

**Comment by yujincheng08** [comment]
no log == no fix.

**Comment by yujincheng08** [comment]
> The Changelog say 64Bit are only supported

Please learn English with more effort. Your English teacher is crying.
