### ISSUE TITLE
unable to mount ramdisk - Galaxys s6 edge

### ISSUE THREAD

**Issue by yuukiw** [topjohnwu/Magisk#53]
if get unable to mount ramdisk when i want to install v11 on my Galaxys s6 edge

**Comment by c727** [comment]
no logs. samsung stock kernels are known to have issues
https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445

**Comment by yuukiw** [comment]
log:
https://docs.google.com/document/d/1NUkPBatVRZRfrgvHLJ63Qb8S5UFjcqHke4h73MRagOk/edit?usp=sharing

**Comment by Didgeridoohan** [comment]
Your boot image is already patched for SuperSU but no stock boot image backup is available. That causes the installer script to fail since it can't restore a stock ramdisk. Solution: use a clean boot image and start from the beginning.

**Comment by yuukiw** [comment]
and how to get this clean boot image without loosing all apps?

**Comment by Didgeridoohan** [comment]
Check your device/ROM thread, but it's not a Magisk issue. You can close this one...

**Comment by yuukiw** [comment]
i reflashed a the bootloader and still get the same problem. (you meant the bl with boot imager or?) or did you mean the firmware.

**Comment by Didgeridoohan** [comment]
No. The boot image. Bootloader has nothing to do with it. If you have a stock system, just flash your stock boot image. If you have a custom ROM, go ask in that thread for advice.

This is not the place for this. 

Go to your device/ROM thread!
