### ISSUE TITLE
fgo still detect magisk after update to the latest magisk version

### ISSUE THREAD

**Issue by s06010** [topjohnwu/Magisk#530]
after update to latest magisk 17.0   fgo (jp)still detect magisk itself  therefore can't play it any more do anyone know what happen? 

logs;https://drive.google.com/file/d/1-JGxbha960hmiuOgstBhQOs9XzJYukdO/view?usp=drivesdk

app;https://play.google.com/store/apps/details?id=com.aniplex.fategrandorder

**Comment by topjohnwu** [comment]
Duplicate #502
