### ISSUE TITLE
Cannot boot into download mode from Magisk app

### ISSUE THREAD

**Issue by Ubimo** [topjohnwu/Magisk#5301]
I cannot boot into download mode anymore from the magisk app.
No modules or other mods. Stock ROM.
Booting into recovery is working.

Device: Samsung Galaxy S20 FE 5G
Android version: 12
Magisk version name: Canary
Magisk version code: 24001

Edit: 
Magisk 24.1 was released just now. 
Boot to download mode still won't work. The phone just reboots, without going into download mode.

**Comment by alexisju** [comment]
Yeah bootloop for me too after upgrade 23>24.1 (OnePlus 8 Pro). 
Forgot to disable modules first...

**Comment by vvb2060** [comment]
We need to know the command, for example `/system/bin/reboot download`

**Comment by Ubimo** [comment]
I do not know the magisk app command for "boot to download".
