### ISSUE TITLE
Samsung SM-G900V Phone Slow and Unresponsive on Wi-Fi or LTE  jdwp control socket: Connection refused

### ISSUE THREAD

**Issue by twindragon6** [topjohnwu/Magisk#5307]
Device: 
Android version: 11
Magisk version name: 32fc34f9
Magisk version code: 24101

Lineage-18.1-20220123-nightly-klte-signed
https://download.lineageos.org/klte/changes/
https://mirrorbits.lineageos.org/full/klte/20220123/lineage-18.1-20220123-nightly-klte-signed.zip

[boot.zip](https://github.com/topjohnwu/Magisk/files/7961528/boot.zip)
[magisk_patched-24101_dX0Kt.zip](https://github.com/topjohnwu/Magisk/files/7961530/magisk_patched-24101_dX0Kt.zip)

Rooted Logs:
[magisk_log_2022-01-28T11_41_13.log](https://github.com/topjohnwu/Magisk/files/7961531/magisk_log_2022-01-28T11_41_13.log)

Rooted Matlog:
[logs-2022-01-28-11-40-42.zip](https://github.com/topjohnwu/Magisk/files/7961535/logs-2022-01-28-11-40-42.zip)

Non-Rooted Logs:
[magisk_log_2022-01-24T21_05_51.log](https://github.com/topjohnwu/Magisk/files/7961536/magisk_log_2022-01-24T21_05_51.log)

build.board: MSM8974
build.bootloader: G900VVRU2DQL1
build.brand: samsung
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: kltevzw
build.display: lineage_klte-userdebug 11 RQ3A.211001.001 10038725
build.fingerprint: samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CRH1:user/release-keys
build.hardware: qcom
build.host: lineage-buildkite
build.id: RQ3A.211001.001
build.manufacturer: samsung
build.model: SM-G900V
build.product: kltevzw
build.radio: unknown
build.serial: unknown
build.tags: release-keys
build.time: 1642905566000
build.type: userdebug
build.user: buildkite-agent
version.codename: REL
version.incremental: 10038725
version.release: 11
version.sdk_int: 30

Modems:
20180118_G900V_QL1_BASEBAND-FIRMWARE_MODEM
20180118_G900V_QL1_MODEM
20180118_G900V_QL1_MODEM_NON-HLOS

**Comment by twindragon6** [comment]
The issues from #5276 and #5283 are still present in 24101

**Comment by twindragon6** [comment]
SELINUX PERMISSIVE ROOTED LOGS:
[logs-2022-01-29-15-30-11.zip](https://github.com/topjohnwu/Magisk/files/7965053/logs-2022-01-29-15-30-11.zip)
[magisk_log_2022-01-29T15_30_35.log](https://github.com/topjohnwu/Magisk/files/7965054/magisk_log_2022-01-29T15_30_35.log)

ADDITIONAL ROOTED LOGS:
[logs-2022-01-28-23-03-26.zip](https://github.com/topjohnwu/Magisk/files/7965056/logs-2022-01-28-23-03-26.zip)
[magisk_log_2022-01-28T23_04_02.log](https://github.com/topjohnwu/Magisk/files/7965057/magisk_log_2022-01-28T23_04_02.log)

**Comment by twindragon6** [comment]
Additional Security Info:

Lineage-18.1-20220123-nightly-klte-signed
https://download.lineageos.org/klte/changes/
https://mirrorbits.lineageos.org/full/klte/20220123/lineage-18.1-20220123-nightly-klte-signed.zip

OS /
[default.prop.txt](https://github.com/topjohnwu/Magisk/files/7967081/default.prop.txt)

system
[build.prop.txt](https://github.com/topjohnwu/Magisk/files/7967087/build.prop.txt)

product
[build.prop.txt](https://github.com/topjohnwu/Magisk/files/7967091/build.prop.txt)

system_ext
[build.prop.txt](https://github.com/topjohnwu/Magisk/files/7967096/build.prop.txt)

vendor
[build.prop.txt](https://github.com/topjohnwu/Magisk/files/7967099/build.prop.txt)

etc
[build.prop.txt](https://github.com/topjohnwu/Magisk/files/7967103/build.prop.txt)

system/etc/permissions
[permissions.zip](https://github.com/topjohnwu/Magisk/files/7967083/permissions.zip)

**Comment by brevilo** [comment]
I doubt this is related to Magisk. I see these messages flying by constantly on a fresh LineageOS 18.1 *without* Magisk.

**Comment by brevilo** [comment]
Update: activating USB debugging (in developer settings) stops the noise... Go figure...

**Comment by mtekman** [comment]
Can confirm I'm seeing these messages for all apps, and that USB debugging enabling turns them off.

Lineage 18.1-20211022

**Comment by Enlinks** [comment]
@twindragon6 can you confirm if enabling USB Debugging helped with your slowness and unresponsive issues? I'm having similar problems when using Wireguard. It seems that enabling USB Debugging might have corrected the behavior but I'll still testing to see if the issue comes back.

**Comment by RahifM** [comment]
is there a proper fix for this other than enable usb debugging? my bank apps dont allow me to enable the developer option so as i disable developer options the usb debugging is also disabled and these spams happen again

**Comment by wu-lee** [comment]
Possibly related? https://gitlab.com/LineageOS/issues/android/-/issues/4445
