### ISSUE TITLE
Zip signature verification failed in TWRP [17.0]

### ISSUE THREAD

**Issue by Displax** [topjohnwu/Magisk#531]
Magisk 17.0 can not be installed when "Zip signature verification" option is enabled in TWRP.
> Installing zip file '/sdcard/Magisk-v17.0.zip'
Checking for Digest file...
Skipping Digest check: no Digest file found
Verifying zip signature...
I:read key e=3 hash=20
I:1 key(s) loaded from /res/keys
I:comment is 1216 bytes; signature 1198 bytes from end
I:failed to verify against RSA key 0
E:failed to verify whole-file signature
I:Zip signature verification failed: 1
Zip signature verification failed!
Error installing zip file '/sdcard/Magisk-v17.0.zip'

**Comment by topjohnwu** [comment]
Disable zip signature verification in TWRP, it is false security.
TWRP will only check whether it is signed by the test key, which it isn't because the zip is signed with my own private key.

**Comment by SsNipeR1** [comment]
_**Hey, can you give me the signed zip, because i have stock recovery and i cant disable zip verification?**_

**Comment by Didgeridoohan** [comment]
@SsNipeR1 You'll need to install this way: https://topjohnwu.github.io/Magisk/install.html#boot-image-patching

**Comment by ovz93br43v7** [comment]
> Disable zip signature verification in TWRP, it is false security.
> TWRP will only check whether it is signed by the test key, which it isn't because the zip is signed with my own private key.

How can we verify our download of Magisk and Magisk Manager? I think I remember that this was sometimes part of the FAQ but I can't find the instructions anymore....

**Comment by shakib1213** [comment]
> Disable zip signature verification in TWRP, it is false security.
> TWRP will only check whether it is signed by the test key, which it isn't because the zip is signed with my own private key.

bro when i try to instal magisk it says digest Verfication failed
