### ISSUE TITLE
Samsung M30s screen auto-rotation don't work

### ISSUE THREAD

**Issue by SIRoNAME** [topjohnwu/Magisk#5317]
Device: Samsung M30s
Android version:11
Magisk version name: [32fc34f](https://github.com/topjohnwu/Magisk/commit/32fc34f9226743c2b0be75c0c3bc427031305464) 
Magisk version code: 24101

24.0 v. screen auto-rotation work, but in new release 24.1 v. it doesn't work.
If need log file or something else, just ask me and say where it can be found.

**Comment by vvb2060** [comment]
no log

**Comment by SIRoNAME** [comment]
> no log

;But i sayed that if it need log files just say how i can get them..

**Comment by treety7** [comment]
Same issure btw
