### ISSUE TITLE
Google Play System Update makes device stuck at bootanimation

### ISSUE THREAD

**Issue by rama982** [topjohnwu/Magisk#5321]
Device: Infinix Note 10 Pro
Android version: 11
Magisk version name: 32fc34f
Magisk version code: 24101

With stock rom whenever google play system auto update happens after installing magisk, after reboot system will stuck at bootanimation and need factory reset. this is very frustrating. Need advice on how to disable the updates or anything related.
Also this happen on both v23 and latest canary version.

**Comment by HuskyDG** [comment]
Maybe cause by some modules (no longer compatible with new update) or something?

**Comment by vvb2060** [comment]
Unable to reproduce, and no log.
