### ISSUE TITLE
Zygisk not turning on

### ISSUE THREAD

**Issue by Navneet-Kumar-Singh** [topjohnwu/Magisk#5328]
Installed fresh magisk 24.1 and zygisk is saying its turned off.
[magisk_log_2022-01-29T20:13:22.log](https://github.com/topjohnwu/Magisk/files/7963924/magisk_log_2022-01-29T20.13.22.log)

-->

Device: SM-A920F
Android version: 10
Magisk version name:
Magisk version code: 24101

**Comment by canyie** [comment]
> ro.crypto.state: [encrypted]
ro.crypto.type: [block]
persist.sys.zygote.early: [true]

Duplicated of #5229

**Comment by yujincheng08** [comment]
try this
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7965869/app-debug.zip)
rename zip to apk to install the app
