### ISSUE TITLE
Magisk flash successful but apk show no magisk installed

### ISSUE THREAD

**Issue by Lektorek** [topjohnwu/Magisk#5330]
Installed magisk 24.1 via twrp and it was successful, after boot to system apk was installed but apk says magisk wasn't installed. Even when full system reinstall and wipe all data, issue still persist. No logs in magisk apk, greyed out superuser and moduls options on bottom. Intresting thing is i can still prove super user rights in apk's like lucky patcher.
Magisk:
![Screenshot_20220129-175905](https://user-images.githubusercontent.com/26118085/151669928-6ddadc2f-f290-49e6-bd5f-1ff1ffb3cefc.jpg)
Options:
![Screenshot_20220129-180044](https://user-images.githubusercontent.com/26118085/151669986-6a3af9aa-b409-4b49-b6d5-019e71b92905.jpg)
Logs:
![Screenshot_20220129-180223](https://user-images.githubusercontent.com/26118085/151670018-b57699f8-cccd-463e-8522-4c86c7659db4.jpg)
![Screenshot_20220129-180227](https://user-images.githubusercontent.com/26118085/151670019-ae6806e7-208f-4d01-8c5b-324980771090.jpg)
-->

Device: Samsung Galaxy Note 8 (greatlte)
Android version: 9 (pie)
Magisk version name:  canary (latest)
Magisk version code: 24101

**Comment by 1Panic** [comment]
I have the same problem!

Device: Samsung Galaxy S8
Android version: 9 (pie)
Magisk version: 24100

**Comment by UnknownDeviceKali** [comment]
I'm going through the same problem. I went to update to version 24, but I forgot to remove hidden mode from magisk... I ended up uninstalling the hidden application. I already tried to reinstall magisk in the latest version, I have root access, but magisk has the same status (not installed)

**Comment by UnknownDeviceKali** [comment]
I'm going through the same problem. I went to update to version 24, but I forgot to remove hidden mode from magisk... I ended up uninstalling the hidden application. I already tried to reinstall magisk in the latest version, I have root access, but magisk has the same status (not installed).  GALAXY NOTE 8

**Comment by korboybeats** [comment]
I'm experiencing the same issue too on Galaxy S6 Edge. I literally have reset my phone probably over a dozen times now trying to get Magisk 24.1 to work.. thank god it's not just me

**Comment by pafaf** [comment]
> Installed magisk 24.1 via twrp and it was successful, after boot to system apk was installed but apk says magisk wasn't installed. Even when full system reinstall and wipe all data, issue still persist. No logs in magisk apk, greyed out superuser and moduls options on bottom. Intresting thing is i can still prove super user rights in apk's like lucky patcher. Magisk: ![Screenshot_20220129-175905](https://user-images.githubusercontent.com/26118085/151669928-6ddadc2f-f290-49e6-bd5f-1ff1ffb3cefc.jpg) Options: ![Screenshot_20220129-180044](https://user-images.githubusercontent.com/26118085/151669986-6a3af9aa-b409-4b49-b6d5-019e71b92905.jpg) Logs: ![Screenshot_20220129-180223](https://user-images.githubusercontent.com/26118085/151670018-b57699f8-cccd-463e-8522-4c86c7659db4.jpg) ![Screenshot_20220129-180227](https://user-images.githubusercontent.com/26118085/151670019-ae6806e7-208f-4d01-8c5b-324980771090.jpg) -->
> 
> Device: Samsung Galaxy Note 8 (greatlte) Android version: 9 (pie) Magisk version name: canary (latest) Magisk version code: 24101

Same here,  v23 says it's installed, when update app to 24.1, says not !!!
![Screenshot_20220129-200511](https://user-images.githubusercontent.com/33636275/151677643-c67752c1-93c8-41ea-87b7-e198e8e8ebe0.jpg)
! Since this o cannot have v23 successfully installed 
![Screenshot_20220129-195959](https://user-images.githubusercontent.com/33636275/151677628-8d98d40c-faad-4401-9531-826952deb543.jpg)

**Comment by osm0sis** [comment]
#4174

**Comment by bamfg** [comment]
Is there a custom rom that has magisk preindtalled in as a system app !?

**Comment by madduck** [comment]
Same issue here with 24102 on a OnePlus5T. I flashed the patched boot.img, can use e.g. `/system/bin/su` for existing apps, but the manager doesn't see Magisk installed, and thus does not give me access to modules and su policy.
