### ISSUE TITLE
WiFi won't work after rescued from Magisk 17 loop

### ISSUE THREAD

**Issue by JackieMium** [topjohnwu/Magisk#534]
I've experienced this seceral times that after a Magisk update, WiFi stops working. Usually I just reboot to TWRP and flash firmware amd ROM，then flash Magisk and WiFi is fine. But today WiFi is completely broken after rescue from the boot loop when updated to Magisk 17. This was what happened:

When Magisk Manager notified about Magisk 17 update, I click update and install. Then phone was stuck at a boot loop. So I flashed firmware and ROM to boot amd then boot my phone. I noticed WiFi stopped working so I downloaded Magisk uninstaller and rebooted to TWRP and flashed it to get rid of Magisk 17. However, WiFi was still down after this. I then rebooted to TWRP and flashed Magisk 16. Boot was fine and root  is working. While WiFi is still down. I flased uninstaller again, follwed by flashing firmware and ROM. WiFi still down.

I don't want to clear data and started from scatch. What do I do now? waitimg for a solaution.

My phone is OnePlus 3T, ROM is RR-5.8.5-Sultan from XDA, firmware 4.5.1. ROM and firmware are fine since I've used it for long and kept them from the day I downloaded them.

_Sent from my ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cilone** [comment]
+1

**Comment by Displax** [comment]
Yep. It`s reset chmod on /data/misc/wifi/p2p_supplicant.conf for some reason.
If manually revert it to the 0755 all was OK.

**Comment by JackieMium** [comment]
@Displax well, actually it's already 0755 when I checked.

![](https://i.imgur.com/G8qRu6J.png)

_Sent from my ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by topjohnwu** [comment]
Issue resolved, close issue.
