### ISSUE TITLE
Magisk 24.1 - DenyList for all [Feature Request]

### ISSUE THREAD

**Issue by jd1900** [topjohnwu/Magisk#5341]
I don't know if I understood properly, but if so, when applied denylist, Magisk/zygote doesn't apply to those processes.
Being this the case, why not deny all processes by default (or as an option) and then be able to uncheck those which are useful to be able to access root?

Wouldn't that be faster and better?

Device: Pixel 5
Android version: Android 12
Magisk version name: 32fc34f
Magisk version code: 24101

**Comment by HuskyDG** [comment]
I think this not a good idea.
Your system may become unstable since how DenyList works is same as a part of MagiskHide does.
https://github.com/topjohnwu/Magisk/issues/3456

**Comment by vvb2060** [comment]
This will only get slower and worse.

**Comment by jd1900** [comment]
So... Is it better to only include apps that may detect root?

**Comment by HuskyDG** [comment]
> So... Is it better to only include apps that may detect root? (In terms of performance)

Wanna hide magisk for all apps exclude app that need root access?
