### ISSUE TITLE
Magisk - Zygisk not turning on

### ISSUE THREAD

**Issue by pablo8899** [topjohnwu/Magisk#5353]
Device: Samsung Galaxy S8 (SM-G950F)
Android version: 9
Magisk version name: 32fc34f
Magisk version code: 24101

Hi i have problem with Zygisk:
![Screenshot_20220201-134913](https://user-images.githubusercontent.com/37773477/151972043-eaf04e5b-8f66-4f9a-ada0-a30b54ec49df.jpg)

I have tried solution from this issue https://github.com/topjohnwu/Magisk/issues/5299 but nothing seems to work (my device doesn't have FDE support).

Logs:
[magisk_log_2022-02-01T13_49_09.log](https://github.com/topjohnwu/Magisk/files/7978565/magisk_log_2022-02-01T13_49_09.log)
[bootlog.txt](https://github.com/topjohnwu/Magisk/files/7978195/bootlog.txt)

I should also attach init.rc file but in my case it has 0 bytes and i can't copy it idk why.

**Comment by canyie** [comment]
>  F linker  : CANNOT LINK EXECUTABLE "/system/bin/app_process64": library "/sbin/.magisk/zygisk/zygisk.app_process64.1.so" not found

zygisk32 success to inject into zygote but zygisk64 keeps crashing.

**Comment by canyie** [comment]
May I have the output of `su -c ls -lZ /sbin/.magisk/zygisk/`?

**Comment by pablo8899** [comment]
> May I have the output of `su -c ls -lZ /sbin/.magisk/zygisk/`?

sure:

total 1080
-rwxr-xr-x 1 root shell u:object_r:zygote_exec:s0 141116 2022-02-01 13:47 app_process32
-rwxr-xr-x 1 root shell u:object_r:zygote_exec:s0 223608 2022-02-01 13:47 app_process64
-rwxr-xr-x 1 root shell u:object_r:zygote_exec:s0 141116 2022-02-01 13:47 zygisk.app_process32.1.so
-rwxr-xr-x 1 root shell u:object_r:zygote_exec:s0 141116 2022-02-01 13:47 zygisk.app_process32.2.so
-rwxr-xr-x 1 root shell u:object_r:zygote_exec:s0 223608 2022-02-01 13:47 zygisk.app_process64.1.so
-rwxr-xr-x 1 root shell u:object_r:zygote_exec:s0 223608 2022-02-01 13:47 zygisk.app_process64.2.so

**Comment by canyie** [comment]
Try this build? https://github.com/canyie/Magisk/actions/runs/1779468520

**Comment by pablo8899** [comment]
> Try this build? https://github.com/canyie/Magisk/actions/runs/1779468520

Hi 
Now i have problem with core detection 
![Screenshot_20220202-081719](https://user-images.githubusercontent.com/37773477/152110667-f6c90372-8fa0-4d3b-9a8d-f6ce09203d8f.jpg)

**Comment by AlexeSimon** [comment]
Same phone, same issue, all my "rootphobic" apps have been going nuts!
I also use a different build you linked on another thread to solve magisk not being detected. 
I tried to hide magisk using hsu, magiskhide props config, riru+universal safetynet fix (riru) but no success.

**Comment by canyie** [comment]
Forgot to merge the master branch again :( please try this one: https://github.com/canyie/Magisk/actions/runs/1784306205

**Comment by AlexeSimon** [comment]
@canyie Still a "No" and rootphobic behavior despite all the modules.

[magisk_log_2022-02-02T16:46:15.log](https://github.com/topjohnwu/Magisk/files/7987937/magisk_log_2022-02-02T16.46.15.log)

(Thank you btw for your reactiveness and for how much you are helping 👍)

**Comment by pablo8899** [comment]
Yes - zygisk still says "no"
[bootlog2.txt](https://github.com/topjohnwu/Magisk/files/7988091/bootlog2.txt)

 F linker  : CANNOT LINK EXECUTABLE "/system/bin/app_process64": library "/sbin/.magisk/zygisk/zygisk.app_process64.1.so" not found

**Comment by yujincheng08** [comment]
Please use this to grab bootlog
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7992915/app-debug.zip)

**Comment by pablo8899** [comment]
@yujincheng08 so I should send You magisk log only now or with logcat?

**Comment by yujincheng08** [comment]
with logcat plz.

**Comment by pablo8899** [comment]
@yujincheng08 thats what i get:
[bootlog.log](https://github.com/topjohnwu/Magisk/files/7992995/bootlog.log)
[magisk_log_2022-02-03T093228.log](https://github.com/topjohnwu/Magisk/files/7992996/magisk_log_2022-02-03T093228.log)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7993064/app-debug.zip)
Use this to grab logcat again. And kmsg as well.

**Comment by pablo8899** [comment]
@yujincheng08 idk if i did smth wrong but kernel log has only 0.5 mb
[bootlog.log](https://github.com/topjohnwu/Magisk/files/7993251/bootlog.log)
[kmsg.log](https://github.com/topjohnwu/Magisk/files/7993252/kmsg.log)

**Comment by yujincheng08** [comment]
What is the output of command `file /sbin/.magisk/zygisk/zygisk.app_process64.1.so`

**Comment by pablo8899** [comment]
/sbin/.magisk/zygisk/zygisk.app_process64.1.so: cannot open

**Comment by yujincheng08** [comment]
do this in root shell

**Comment by pablo8899** [comment]
when i run this command with "su" it doesn't load

**Comment by pablo8899** [comment]
alright I got this via termux
/sbin/.magisk/zygisk/zygisk.app_process64.1.so: ELF shared object, 64-bit LSB arm64, dynamic (/system/bin/linker64), BuildID=80a7158f0837bf132e3cd14dba6f32570ce15e5c, stripped

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7993573/app-debug.zip)
Use this to grab log

**Comment by pablo8899** [comment]
[bootlog.log](https://github.com/topjohnwu/Magisk/files/7993652/bootlog.log)

**Comment by pablo8899** [comment]
it seems like x64 library injected now but i still have "Zygisk: no"

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7993844/app-debug.zip)
Try this and grab log.

**Comment by pablo8899** [comment]
@yujincheng08 
[bootlog.log](https://github.com/topjohnwu/Magisk/files/7993894/bootlog.log)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7994002/app-debug.zip)
Try this and grab log

**Comment by pablo8899** [comment]
[bootlog.log](https://github.com/topjohnwu/Magisk/files/7994087/bootlog.log)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7994148/app-debug.zip)
Try this and grab log

**Comment by pablo8899** [comment]
[bootlog.log](https://github.com/topjohnwu/Magisk/files/7994214/bootlog.log)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7994489/app-debug.zip)
Try this and grab log

**Comment by pablo8899** [comment]
[bootlog.log](https://github.com/topjohnwu/Magisk/files/7994528/bootlog.log)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7996181/app-debug.zip)
Try this and grab log

**Comment by pablo8899** [comment]
OMG it works now Zygisk is enabled !  thank you very very very much @yujincheng08  and @canyie for your time spending of my issue ! I really appreciate this ! 
![Screenshot_20220203-171937](https://user-images.githubusercontent.com/37773477/152383493-8d436d65-4dd3-40bd-bb87-b358226b1959.jpg)
Do you need still bootlogs ?

**Comment by yujincheng08** [comment]
At last, plz try this:
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7996468/app-debug.zip)

**Comment by pablo8899** [comment]
> At last, plz try this: [app-debug.zip](https://github.com/topjohnwu/Magisk/files/7996468/app-debug.zip)

this version also works !

**Comment by AlexeSimon** [comment]
> At last, plz try this: [app-debug.zip](https://github.com/topjohnwu/Magisk/files/7996468/app-debug.zip)

Worked for me too! And I could finally hide the Magisk App and use my banking apps.

[magisk_log_2022-02-03T18:27:39.log](https://github.com/topjohnwu/Magisk/files/7996838/magisk_log_2022-02-03T18.27.39.log)

**Comment by AlexeSimon** [comment]
Gj and thank you for your help all 👍

**Comment by jeancarlosna** [comment]
![Screenshot_20220203-193621](https://user-images.githubusercontent.com/33769125/152440944-2bb55dc5-1ac8-42c6-80cd-c89752b2478c.jpg)
![Screenshot_20220203-193629](https://user-images.githubusercontent.com/33769125/152440945-d7e5f784-f587-4672-9bc0-1b21155e01ae.jpg)
![Screenshot_20220203-193640](https://user-images.githubusercontent.com/33769125/152440962-de91803b-f8b3-481b-a0a6-bdf8e1019d28.jpg)

[magisk_log_2022-02-03T193319.log](https://github.com/topjohnwu/Magisk/files/7998731/magisk_log_2022-02-03T193319.log)
[init.zip](https://github.com/topjohnwu/Magisk/files/7998732/init.zip)

Am I doing something wrong? T.T

**Comment by maingocvinh** [comment]
how to get the above modules, my magisk doesn't show the module to install

**Comment by pablo8899** [comment]
> how to get the modules, my magisk app doesn't show the module to install

Read changelog

**Comment by fardinrast** [comment]
> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/7996181/app-debug.zip) Try this and grab log

Hi @yujincheng08 
I need your help
My phone is S7 edge and zygisk is off. I can't turn it on

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 06/09/2022, 10:16, ***@***.*** wrote:
app-debug.zip Try this and grab log

Hi @yujincheng08

I need your help

My phone is S7 edge and zygisk is off. I can't turn it on

**Comment by fardinrast** [comment]
Fix your bot!

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 06/09/2022, 10:23, ***@***.*** wrote:Fix your bot!

**Comment by SPYazdani** [comment]
@fardinrast 
https://github.com/topjohnwu/Magisk/issues/6248

**Comment by gayratiism** [comment]
> OMG it works now Zygisk is enabled ! thank you very very very much @yujincheng08 and @canyie for your time spending of my issue ! I really appreciate this ! ![Screenshot_20220203-171937](https://user-images.githubusercontent.com/37773477/152383493-8d436d65-4dd3-40bd-bb87-b358226b1959.jpg) Do you need still bootlogs ?

Please, can you tell me how to use this file?

**Comment by gayratiism** [comment]
> OMG it works now Zygisk is enabled ! thank you very very very much @yujincheng08 and @canyie for your time spending of my issue ! I really appreciate this ! ![Screenshot_20220203-171937](https://user-images.githubusercontent.com/37773477/152383493-8d436d65-4dd3-40bd-bb87-b358226b1959.jpg) Do you need still bootlogs ?

**Comment by gayratiism** [comment]
Please, can you tell me how to use this file?

**Comment by Oramous** [comment]
Hi, module install keeps failing on old galaxy s7. I've tried multiple times but it keeps getting stuck in the same place. It says:
"--uploading archive for odex modding (/data/adb/modules_update/NFCScreenoff/bin/curl), it may take a while (42mb)
!! odex strategy failed.
! Installation failed"

**Comment by Ruslan779555** [comment]
@ yujincheng08 I have almost the same problem. Can you write your nickname in TG? I want to ask for help

**Comment by cyberalt1** [comment]
Still an issue in 2025, please fix.
