### ISSUE TITLE
Magisk does not mount data partition on some devices

### ISSUE THREAD

**Issue by dhruvkrishnavaid** [topjohnwu/Magisk#5354]
Device: Micromax Canvas Nitro 3
Android version: 5.1 (lollipop)
Magisk version name: 32fc34f9
Magisk version code: 24101

Device boots up normally and root works. But I cannot use modules. `/sbin/.magisk/mirror/data` doesn't exist. Worked fine till version 23.0.

[magisk_install_log_2022-02-01T19:10:18.log](https://github.com/topjohnwu/Magisk/files/7978932/magisk_install_log_2022-02-01T19.10.18.log)
[magisk_log_2022-02-01T19:28:43.log](https://github.com/topjohnwu/Magisk/files/7978937/magisk_log_2022-02-01T19.28.43.log)

```
$ su
WARNING: linker: /sbin/su: unused DT entry: type 0x6ffffef5 arg 0x16fc
WARNING: linker: /sbin/su: unused DT entry: type 0x6ffffffe arg 0x1f34
WARNING: linker: /sbin/su: unused DT entry: type 0x6fffffff arg 0x2
root@E352:/data/data/com.termux/files/home # cd /sbin/.magisk/mirror
root@E352:/sbin/.magisk/mirror # ls
system
vendor
```

![Screenshot_2022-02-01-19-37-29](https://user-images.githubusercontent.com/69188774/151983461-95400a18-e49b-4b61-ab2c-21e6a003bd55.png)
![Screenshot_2022-02-01-19-39-38](https://user-images.githubusercontent.com/69188774/151983624-ae15fe12-746e-448c-8800-3349d442315e.png)

**Comment by dhruvkrishnavaid** [comment]
I checked the boot log attached in #5328, it mounts the data partition mirror. So I guess, it's issue with some devices.

**Comment by Displax** [comment]
Confirmed. Same on Android 5.1.1 device.

**Comment by HuskyDG** [comment]
Does `/sbin/.magisk/block/data` exist?

**Comment by HuskyDG** [comment]
Let us know the output of `mount | grep ' /data '`?

**Comment by dhruvkrishnavaid** [comment]
`/sbin/.magisk/block` is completely empty.
```
# cd /sbin/.magisk/block
root@E352:/sbin/.magisk/block # ls
root@E352:/sbin/.magisk/block #
```

And `mount | grep ' /data '` returns 
```
/emmc@usrdata /data ext4 rw,seclabel,nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered 0 0
```

**Comment by yujincheng08** [comment]
Use this to grab log:
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7992797/app-debug.zip)

**Comment by dhruvkrishnavaid** [comment]
@yujincheng08 Here are the logs
[magisk_install_log_2022-02-03T14:33:09.log](https://github.com/topjohnwu/Magisk/files/7993135/magisk_install_log_2022-02-03T14.33.09.log)
[magisk_log_2022-02-03T14:34:36.log](https://github.com/topjohnwu/Magisk/files/7993136/magisk_log_2022-02-03T14.34.36.log)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7993207/app-debug.zip)
Use this to grab log again.

**Comment by dhruvkrishnavaid** [comment]
Still the same
[magisk_install_log_2022-02-03T15:12:17.log](https://github.com/topjohnwu/Magisk/files/7993425/magisk_install_log_2022-02-03T15.12.17.log)
[magisk_log_2022-02-03T15:15:08.log](https://github.com/topjohnwu/Magisk/files/7993426/magisk_log_2022-02-03T15.15.08.log)

**Comment by yujincheng08** [comment]
Cannot see the log I added. Could you use adb logcat to grab the log?

**Comment by yujincheng08** [comment]
Oh I may know what's going on.

**Comment by dhruvkrishnavaid** [comment]
Yeah, please wait.
Let me capture the logcat.

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7993504/app-debug.zip)
Use this to grab the log instead.

**Comment by dhruvkrishnavaid** [comment]
[magisk_install_log_2022-02-03T15:37:09.log](https://github.com/topjohnwu/Magisk/files/7993566/magisk_install_log_2022-02-03T15.37.09.log)
[magisk_log_2022-02-03T15:42:53.log](https://github.com/topjohnwu/Magisk/files/7993568/magisk_log_2022-02-03T15.42.53.log)

**Comment by dhruvkrishnavaid** [comment]
Here's the result of `adb -d logcat`
[logcat.log](https://github.com/topjohnwu/Magisk/files/7993615/logcat.log)

**Comment by yujincheng08** [comment]
Can you send `/proc/mounts`?

**Comment by dhruvkrishnavaid** [comment]
https://drive.google.com/file/d/10sRLjYEFBb0CouqSDfS3jCxscJnCK1po/view?usp=drivesdk

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7993845/app-debug.zip)
Use this to grab log.

**Comment by dhruvkrishnavaid** [comment]
Here it is
[magisk_install_log_2022-02-03T16:28:40.log](https://github.com/topjohnwu/Magisk/files/7993901/magisk_install_log_2022-02-03T16.28.40.log)
[magisk_log_2022-02-03T16:30:01.log](https://github.com/topjohnwu/Magisk/files/7993904/magisk_log_2022-02-03T16.30.01.log)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/7994129/app-debug.zip)
Use this to grab log

**Comment by dhruvkrishnavaid** [comment]
Congrats 🎉
Modules are now working and `/sbin/.magisk/mirror/data` is getting mounted.
Here are the logs
[magisk_install_log_2022-02-03T17:13:40.log](https://github.com/topjohnwu/Magisk/files/7994186/magisk_install_log_2022-02-03T17.13.40.log)
[magisk_log_2022-02-03T17:16:22.log](https://github.com/topjohnwu/Magisk/files/7994187/magisk_log_2022-02-03T17.16.22.log)

**Comment by HuskyDG** [comment]
> Congrats 🎉 Modules are now working and `/sbin/.magisk/mirror/data` is getting mounted. Here are the logs [magisk_install_log_2022-02-03T17:13:40.log](https://github.com/topjohnwu/Magisk/files/7994186/magisk_install_log_2022-02-03T17.13.40.log) [magisk_log_2022-02-03T17:16:22.log](https://github.com/topjohnwu/Magisk/files/7994187/magisk_log_2022-02-03T17.16.22.log)

Yo!!!
