### ISSUE TITLE
Safetynet v17.1

### ISSUE THREAD

**Issue by Yoanndp** [topjohnwu/Magisk#536]
My phone (Honor 8 | FRD-L09C432Bxxx) was passing safetynet test in v16 successfully (before the API reform) but now since the v17.1, MagiskManager says me that safetynet fails. Any idea? Or maybe a new API bug?

_PS:_ I flashed MagiskUninstaller.zip (from XDA) then Magisk-v17.1.zip (also from XDA)
_PPS_: Google Pay works fine

Also, Magisk hide seems to not work properly (Bank/Governement app detects root but before it was working fine)

After all of that, I re-tried to flash Magisk Uninstaller and boot to check  SafetyNet state. Effectively, a part of the problem comes from Magisk. Now I can pass basic integrity (this one fixed bank and government app I said earlier) however I still can't pass CTS.

[Screenshot](https://ibb.co/g6vqSz) 

[Screenshot after Magisk Uninstaller](https://ibb.co/h1oqCz)

**Comment by topjohnwu** [comment]
SafetyNet passes on all my devices, I do not support individual devices

**Comment by Yoanndp** [comment]
Note: for an unknown reason, after flashing stock recovery and then reflash TWRP again, it seems fixed.
