### ISSUE TITLE
Can't hide Magisk-app anymore after downgrade

### ISSUE THREAD

**Issue by iw2ngg** [topjohnwu/Magisk#5361]
I recently downgraded Magisk from V24.1 to V23 (I need magisk hide, as long as it continues to work... ).

Everything works well (SafetyNet test passes, apps gets root access as expected, and so on...) except the Magisk-app, itself, hiding function.

When I try to hide the app...
The empty proxy app with random package is created as expected but it dies without opening manager and the real "Manager" still remains in the app drawer.

Now I have to uninstall the magisk-app everytime I need to use some apps that detects it and, later, reinstall it again (fortunatelly settings are kept).

Before the said upgrade-downgrade the magisk-app hide worked well.

I already:

completelly uninstalled and reinstalled magisk from a clean boot.img (cleaning the cache)
tested with selinux in permissive mode
tested with google play protection disabled.

LogCat (proxy app/stub starting, "stkbp.qwyhwsy" is the randomly generate package name):
---

ActivityManager: Start proc 19729:stkbp.qwyhwsy/u0aXXX for activity stkbp.qwyhwsy/e.s

ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] pkg=stkbp.qwyhwsy cmp=stkbp.qwyhwsy/com.topjohnwu.magisk.core.SplashActivity (has extras)} from uid 10XXX

AndroidRuntime: Process: stkbp.qwyhwsy, PID: 19729

AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{stkbp.qwyhwsy/e.s}: android.content.ActivityNotFoundException: Unable to find explicit activity class {stkbp.qwyhwsy/com.topjohnwu.magisk.core.SplashActivity}; have you declared this activity in your AndroidManifest.xml?

AndroidRuntime: Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {stkbp.qwyhwsy/com.topjohnwu.magisk.core.SplashActivity}; have you declared this activity in your AndroidManifest.xml?

ActivityManager: Process stkbp.qwyhwsy (pid 19729) has died: prcp TOP

Device: Nexus 6p
Android version: Lineage OS 15.1
Magisk version name: V23 and V24.1
Magisk version code: 24101

**Comment by ayanamist** [comment]
The same problem and i havent upgrade to magisk 24 before this issue happens.

**Comment by ayanamist** [comment]
I know what happened.
Please use custom channel and set channel url to `https://raw.githubusercontent.com/topjohnwu/magisk-files/afe2c304e59f631280cc26ccc6d40a7cf04f7f37/stable.json` and it will work again
