### ISSUE TITLE
SM-G975F (G975FXXSEFUL1) Android 11 running Binary E dosen't work at all ive tried evrything for days still nothing

### ISSUE THREAD

**Issue by Mafia932z** [topjohnwu/Magisk#5367]
Device: SM-G975F (G975FXXSEFUL1)
Android version: Android 11 
Magisk version name: app-debug.apk
Magisk version code: 32fc34f9 (24101) (24)

**Comment by pndwal** [comment]
Issues here are for Magisk... If SM-G975F (G975FXXSEFUL1) Android 11 dosen't work, why post here? 🤪
