### ISSUE TITLE
Post-fs-data permission denied

### ISSUE THREAD

**Issue by XstepAhead** [topjohnwu/Magisk#5369]
---Magisk Logs---

02-02 15:08:27.432   502   504 I : ** post-fs-data mode running
02-02 15:08:27.432   502   504 E : unlock mmcblk0p32 failed with 13: Permission denied
02-02 15:08:27.432   502   504 E : unlock mmcblk0boot0 failed with 13: Permission denied
02-02 15:08:27.433   502   504 E : unlock mmcblk0p36 failed with 13: Permission denied
02-02 15:08:27.433   502   504 E : unlock mmcblk0p27 failed with 13: Permission denied
02-02 15:08:27.433   502   504 E : unlock mmcblk0p31 failed with 13: Permission denied
02-02 15:08:27.434   502   504 E : unlock mmcblk0p26 failed with 13: Permission denied
02-02 15:08:27.434   502   504 E : unlock mmcblk0p19 failed with 13: Permission denied
02-02 15:08:27.435   502   504 E : unlock mmcblk0p21 failed with 13: Permission denied
02-02 15:08:27.437   502   504 E : unlock mmcblk0p20 failed with 13: Permission denied
02-02 15:08:27.438   502   504 E : unlock mmcblk0p24 failed with 13: Permission denied
02-02 15:08:27.438   502   504 E : unlock mmcblk0p34 failed with 13: Permission denied
02-02 15:08:27.438   502   504 E : unlock mmcblk0p29 failed with 13: Permission denied
02-02 15:08:27.439   502   504 E : unlock mmcblk0p28 failed with 13: Permission denied
02-02 15:08:27.439   502   504 E : unlock mmcblk0p37 failed with 13: Permission denied
02-02 15:08:27.439   502   504 E : unlock mmcblk0p23 failed with 13: Permission denied
02-02 15:08:27.440   502   504 E : unlock mmcblk0p30 failed with 13: Permission denied
02-02 15:08:27.440   502   504 E : unlock mmcblk0p35 failed with 13: Permission denied
02-02 15:08:27.440   502   504 E : unlock mmcblk0p25 failed with 13: Permission denied
02-02 15:08:27.440   502   504 E : unlock mmcblk0p17 failed with 13: Permission denied
02-02 15:08:27.444   502   504 E : unlock mmcblk0 failed with 13: Permission denied
02-02 15:08:27.444   502   504 E : unlock mmcblk0p22 failed with 13: Permission denied
02-02 15:08:27.444   502   504 E : unlock dm-0 failed with 13: Permission denied
02-02 15:08:27.445   502   504 E : unlock dm-1 failed with 13: Permission denied
02-02 15:08:27.445   502   504 E : unlock dm-2 failed with 13: Permission denied
02-02 15:08:27.446   502   504 E : unlock mmcblk0p38 failed with 13: Permission denied
02-02 15:08:27.446   502   504 E : unlock mmcblk0p33 failed with 13: Permission denied
-->

Device: Redmi 9C
Android version: Android 10
Magisk version name: canary
Magisk version code: 24101

**Comment by XstepAhead** [comment]
![Uploading Screenshot_2022-02-03-18-52-19-437_com.topjohnwu.magisk.jpg…]()

**Comment by XstepAhead** [comment]
![Screenshot_2022-02-03-18-52-19-437_com topjohnwu magisk](https://user-images.githubusercontent.com/61716582/152337909-19e52003-0b54-417e-ae6a-08bd72285e1b.jpg)

**Comment by yujincheng08** [comment]
expected behavior for MTK devices.
