### ISSUE TITLE
Zenfone 3 Updater Process Ended with Error: 2 After update to Magisk 17.0

### ISSUE THREAD

**Issue by EnderDragonEP** [topjohnwu/Magisk#537]
When I try to update Magisk 16.0 to 17.0 use TWRP, I get this message says "Updater Process Ended with Error: 2". And after that, I try flash Magisk 16.0, I still get this massage. I reinstall rom and it still show this error message to me.
By the way, new Magisk 17.1 I still get this error message...

**Comment by topjohnwu** [comment]
Try restore your boot image back to stock (or flash uninstaller), and re-flash again.

**Comment by EnderDragonEP** [comment]
I tried, and I got other error messages...
But It ok now. I find other solution, seems like factory reset is the only way, so I reset my phone and reinstall magisk 17.1, It working now.
