### ISSUE TITLE
Suggestion: compare the size of boot.img before, and after Magisk patch

### ISSUE THREAD

**Issue by Lishoo** [topjohnwu/Magisk#5375]
Device: LG G6 h870
Android version: 9.0 PIE
Magisk version name: Canary
Magisk version code: 24101

Hello, I'v got a suggestion, to compare the output boot.img to the input boot.img in both cases, direct flash and just patching.
I'v got few times the situation when I directly patched the boot.img and after reboot there was a bootloop, the reason was an issue where the output of the boot.img was around 9mb, but should be about 23mb.
The idea is to compare the patched image to the not patched, and if the difference was more than 1mb, the direct flash should be aborted, and Magisk should warn the user that the boot.img is most likely corrupt.

**Comment by vvb2060** [comment]
upload boot.img and patched.img

**Comment by Lishoo** [comment]
[magisk_patched-24001_PzwBx.zip](https://github.com/topjohnwu/Magisk/files/8011524/magisk_patched-24001_PzwBx.zip)
[https://github.com/topjohnwu/Magisk/files/8011500/orginal_boot.zip](url)

**Comment by yujincheng08** [comment]
I don't think it is feasible. Magisk will compress the boot image again, and a working patched image may be smaller than the original one.

**Comment by Lishoo** [comment]
I just wanted to suggest to add an option to check if the patched boot.img is ok or not, some bugs in the code gives the output of wrong size, so magisk could compare the orginal boot.img to the patched boot.img, and if the size difference is more than Xmb lets say more than 2mb then magisk should abort flashing, and if the user would try to manually patch the boot, then magisk should WARN the user :)
