### ISSUE TITLE
Manager is not able to install itself and the stub is not installable since version 24 (Android 7)

### ISSUE THREAD

**Issue by towlie** [topjohnwu/Magisk#5377]
I freshly installed magisk and the manager. But when I try to install any update of the manager it silently fails. 
hiding the manager also fails with an inifnite loop.

When I try to install the stub manually, it throws a parsing error message. The stub on v23 doesn't have this error.

My guess is that something changed that makes the stub incompatible with Android 7. Same goes for the install mechanism of the manager within the app.

Device:  Redmi Note 4 (mido)
Android version: Android 7
Magisk version name: 24 and 24.1
Magisk version code: 32fc34f9 24101

**Comment by yujincheng08** [comment]
No log, no fix.

**Comment by towlie** [comment]
This log should include the process of installing updating manager and trying to hide the manager:
[2022-02-05-11-20-21.txt](https://github.com/topjohnwu/Magisk/files/8007808/2022-02-05-11-20-21.txt)

**Comment by yujincheng08** [comment]
```
02-05 11:15:59.026 D/ GuardProvider(18608): start parse apk : /data/app/vmdl1980828047.tmp
02-05 11:15:59.027 V/ResourceType(18608): No package identifier when getting name for resource number 0x00000000
02-05 11:15:59.030 V/ResourceType(18608): No package identifier when getting name for resource number 0x00000000
02-05 11:15:59.034 D/ GuardProvider(18608): parse apk failed !
02-05 11:15:59.035 D/PackageVerifyedRecevier(3666): verify package /data/app/vmdl1980828047.tmp info:  null
02-05 11:15:59.036 D/PackageVerifyedRecevier(3666): verify package /data/app/vmdl1980828047.tmp finish false
02-05 11:15:59.037 I/com.android.server.pm.PackageManagerServiceInjector(1666): MIUILOG- INSTALL_FAILED_VERIFICATION_FAILURE  uid: 10210 pkg : com.topjohnwu.magisk
02-05 11:15:59.037 E/PackageInstaller(1666): Commit of session 1980828047 failed: FAILED_VERIFICATION_FAILURE MIUI
```

**Comment by towlie** [comment]
I tested the latest build and I can confirm that this fixes the issue. 
Thank you for your dedicated work!
