### ISSUE TITLE
phone shuts down after a minute upon interaction

### ISSUE THREAD

**Issue by Relected** [topjohnwu/Magisk#5379]
I don't really know if it's considered a bootloop or not? But after i flash magisk to recovery_ramdisk the phones does boot, and it's perfectly usable... well for about a minute, then it suddenly restarts, and it boots and restarts after a minute again.
Currently, I haven't interacted with my device for several minutes, and It's still on, so I don't know how or why this is happening
it constantly boots into recvery_ramdisk and i cant get it to boot without magisk

edit: i managed to boot my phone normally, so far no sudden shut downs
edit 2: i tried booting into magisk again and it still has the same issue, works for a while and then reboots (i passed safetynet btw)
edit 3: so apparently the shut down is triggered after interacting with the magisk app for a certain amount of time
Edit 4: apparently flashing stock recovery_ramdisk solved it? My phone doesn't restart everytime now, but I have lost root privileges

Device: Huawei y9 2018 fla-lx1/fla-l21
Android version: 9
Magisk version name: Canary
Magisk version code: 24101

**Comment by Sali41** [comment]
#5379

**Comment by Relected** [comment]
@Sali41 what?

**Comment by pndwal** [comment]
#5380 is strange!.. your issue spawning more!?..😂

Does Magisk show Ramdisk = yes or no for this device?

**Comment by Relected** [comment]
@pndwal  nope, I flashed into recovery, more specifically, recovery_ramdisk

BTW the phone was rooted successfully when it was usable

**Comment by yujincheng08** [comment]
no log, no fix

**Comment by Relected** [comment]
> no log, no fix

[magisk_log_2022-02-05T15:40:23.log](https://github.com/topjohnwu/Magisk/files/8008109/magisk_log_2022-02-05T15.40.23.log)

**Comment by Relected** [comment]
@yujincheng08 so I refalshed magisk on my phone and I am met with the same issue, but this time the phone reboots normally without magisk hijacking recovery
AND that only happens when interacting with the magisk manager app, or the safetynet check app, other apps work just fine

**Comment by yujincheng08** [comment]
useless log

**Comment by yujincheng08** [comment]
Use `adb logcat` to grab log until it restarts.

**Comment by Relected** [comment]
@yujincheng08 unfortunately I have installed a custom ROM due to the frustration thaty system keeps rebooting and the problem gotnfixed,bso I guessbthe issue east stock rom, I will open this issue later of I encounter the same issue
