### ISSUE TITLE
Magisk 17 boot loop

### ISSUE THREAD

**Issue by DovaMerith** [topjohnwu/Magisk#538]
So when i installed the update for magisk last night, my Galaxy S5 G900tl KLTE, running Resurrection Remix 5.8.5 (android 7.1) with Kali Nethunter rom Mod got stuck in boot loop.

Like it didn't even show the roms boot loader, it just showed the phones BIOS screen of "Samsung Galaxy S5".

**Comment by Yoanndp** [comment]
You have to flash Magisk Uninstaller (from XDA) first, then download Magisk v17.1 and flash it

**Comment by DovaMerith** [comment]
Honestly thatts crazy, shouldnt the new version automatically remove the
old?

**Comment by Yoanndp** [comment]
@DovaMerith Topjohnwu made a mistake while releasing his last version. Please refer to his Twitter, there's a thread about this 😉

**Comment by Yoanndp** [comment]
You should close this thread because this is resolved. Topjohnwu will appreciate it
