### ISSUE TITLE
Internal BusyBox broken, Pixel 6 Pro Android 12

### ISSUE THREAD

**Issue by AIMBOT312** [topjohnwu/Magisk#5381]
Device: Pixel 6 Pro
Android version: 12, January 2022 security update
Magisk version name: 32fc34f9
Magisk version code: 241011

Internal busybox broken, Tried to install a module from Emoji Replacer, got this error (see screenshot).
![image](https://user-images.githubusercontent.com/44841254/152665484-82ca1409-1917-46cc-bf5d-ce2ed4e20484.png)

**Comment by yujincheng08** [comment]
Android 12 has no /sbin

**Comment by RikkaW** [comment]
`/sbin` folder is removed from Android 11

**Comment by vvb2060** [comment]
It's not Magisk's problem
