### ISSUE TITLE
Hide the Magisk app function fails in legacy builds

### ISSUE THREAD

**Issue by pndwal** [topjohnwu/Magisk#5382]
Device: Huawei: n/a
Android version: n/a
Magisk version name: n/a
Magisk version code: 24101

**Hide the Magisk app function fails in legacy builds**

Many use older Magisk versions for various reasons.

Lately, many are staying with 23.0, and have noticed that the Hide the Magisk app' function is failing since later 24.x has been released.

This is because the app is calling JSON here
https://github.com/topjohnwu/magisk-files
which always points to latest file versions including stub which has has often become incompatible.

A proper fix for older stable builds may be difficult, but here is one solution to fetch the compatible stub file:

Perhaps a SpecialInstructions.txt file could be included with assets for each older release like this:

**Special Instructions txt**

**In order to avoid issues with the Hide the Magisk app function, please set Update Channel to Custom and place the following URL (for raw JSON file address) in the
Custom Channel dialogue box:**
https://raw.githubusercontent.com/topjohnwu/magisk-files/xxxxxxxxxxxxxxxxcccc/stable.json

**Reset Update Channel to Stable or Beta after this process in order to see proper information for App - Latest, including versions and release notes.**

Going forward (in future builds) the solution should be more simple:

We already have 'Use the local version of the stub when it cannot be downloaded' since 24.0 it seems. If we now _Always_ use the local version of the stub the issue should be gone in downstream builds.

**Comment by vvb2060** [comment]
No support for old versions.

**Comment by pndwal** [comment]
> No support for old versions.

How about 'Always use the local version of the stub' in current versions?... At least then Hide App function would continue to work for any slow to update.

(Nb. Hide function breaks as soon as an update arrives, so if any unhide app they cannot easily hide app again unless they update. 😕 )

**Comment by pndwal** [comment]
Further, I can understand no support for old Canary builds etc, but I can see good reasons to have at least a few stable releases working properly.

Eg, many Android 6, 7 users needed to fall back to 21.x till now (we finally have a fix downstream! 👍) and similarly several Android 8, 9 Samsung users can't  use 24.x and are falling back to 23.0. - However they need to find magisk-files repo and get instruction on using address for raw JSON in Custom Channel in order to restore hidden Magisk app...

**Comment by Sali41** [comment]
> Device: Huawei: n/a
> Android version: n/a
> Magisk version name: n/a
> Magisk version code: 24101
> 
> **Hide the Magisk app function fails in legacy builds**
> 
> Many use older Magisk versions for various reasons.
> 
> Lately, many are staying with 23.0, and have noticed that the Hide the Magisk app' function is failing since later 24.x has been released.
> 
> This is because the app is calling JSON here
> https://github.com/topjohnwu/magisk-files
> which always points to latest file versions including stub which has has often become incompatible.
> 
> A proper fix for older stable builds may be difficult, but here is one solution to fetch the compatible stub file:
> 
> Perhaps a SpecialInstructions.txt file could be included with assets for each older release like this:
> 
> **Special Instructions txt**
> 
> **In order to avoid issues with the Hide the Magisk app function, please set Update Channel to Custom and place the following URL (for raw JSON file address) in the
> Custom Channel dialogue box:**
> https://raw.githubusercontent.com/topjohnwu/magisk-files/xxxxxxxxxxxxxxxxcccc/stable.json
> 
> **Reset Update Channel to Stable or Beta after this process in order to see proper information for App - Latest, including versions and release notes.**
> 
> Going forward (in future builds) the solution should be more simple:
> 
> We already have 'Use the local version of the stub when it cannot be downloaded' since 24.0 it seems. If we now _Always_ use the local version of the stub the issue should be gone in downstream builds.

**Comment by pndwal** [comment]
@Sali41 STOP SPAMMING

**Comment by pndwal** [comment]
For anyone with this issue, I've put working (official) URLs for Custom Channel by build for pre 24.0, and current working solution for 24.0+ here:
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-86380117
😀👍

**Comment by canyie** [comment]
I think this can be simply resolved by  just disabling network...
