### ISSUE TITLE
Hiding data partition

### ISSUE THREAD

**Issue by dioni21** [topjohnwu/Magisk#539]
As far as I understood, Magisk works manipulating mount views between processes.

I has came to my knowledge that some software is "detecting" root by searching data partitions for known names.  For example, Pokemon Go appears to be doing just that: 

https://www.reddit.com/r/TheSilphRoad/comments/98c4ge/probably_figured_out_how_pogo_scans_your/
https://pokewreck.com/research/pokemon-go-reading-device-files-privacy/
https://forum.xda-developers.com/showpost.php?p=77365368&postcount=3745

How hard would be to add some kind of sandbox or filter to Magisk options?  This should be separate from root, as we surely have some apps that we want to hide root, but give access to data store.

**Comment by topjohnwu** [comment]
Nope, that's not possible as apps are stored in data.
I already placed all Magisk related stuffs that requires to be placed in data to an undetectable location. The `MagiskManager` folder in your internal data is also not used anymore, feel free to delete it if you want
