### ISSUE TITLE
🤔 

### ISSUE THREAD

**Issue by HideakiAtsuyo** [topjohnwu/Magisk#5393]
Hi, sorry but how am I supposed to put the canary canal ? When I use custom and put "Canary" or "canary" it say "not available" so I was wondering if you can tell me thanks 🤔

I'm actually using the 24100 and I can't get the last update due to the channel problem

Device: Samsung Galaxy A8 2018
Android version: 9.0
Magisk version name: Beta
Magisk version code: 24102

**Comment by Lishoo** [comment]
Just instal the canary app, it is on the main site, here is the link
https://raw.githubusercontent.com/topjohnwu/magisk-files/canary/app-debug.apk

**Comment by HideakiAtsuyo** [comment]
> Just install the canary app, it is on the main site, here is the link [(https://raw.githubusercontent.com/topjohnwu/magisk-files/canary/app-debug.apk)](url)

![](https://i.imgur.com/yXjL1hA.png) funny hyper link... and thanks for it !

**Comment by HideakiAtsuyo** [comment]
Will the Canary build only get Canary updates or will I have to get it everytime from the Canary release manually ?

**Comment by osm0sis** [comment]
You can't just type "Canary" into custom, it has to be the URL of the .json

**Comment by HideakiAtsuyo** [comment]
> You can't just type "Canary" or "canary" into custom, it has to be the URL of a valid channel .json, e.g. https://raw.githubusercontent.com/topjohnwu/magisk-files/master/canary.json

Thanks for this detial I'll keep it in mind I didn't knew ;)
