### ISSUE TITLE
[Wontfix] Zygisk cannot activate on some old Samsung devices with old kernel (3.19-)

### ISSUE THREAD

**Issue by yujincheng08** [topjohnwu/Magisk#5395]
For some old Samsung devices, there's a kernel restriction that whenever `exec` an ELF from `/proc`, the process can no longer call some systemcalls. For kernel 3.19+, the workaround is `fexecve`, but it does not exist for the old kernel. Users with those devices should use a custom kernel bypassing such a restriction or a newer version.

**Comment by hanoshita** [comment]
I am on GalaxyS5 with kernel 3.4.113 which is even older, and Zygisk is successfully activated

**Comment by pndwal** [comment]
> I am on GalaxyS5 with kernel 3.4.113 which is even older, and Zygisk is successfully activated, I won't blame old samsung devices for something that seems a kernel regression affecting your device.

How is yours older?

@yujincheng08 is a dev; This Wontfix notice is a spin-off of her fix:
[Refactor Zygisk loading](https://github.com/topjohnwu/Magisk/commit/ff7ac582f013dbc27b27e4194424044ee79c3980)[](https://github.com/yujincheng08)[](https://github.com/topjohnwu) 
Co-authored-by: topjohnwu <topjohnwu@gmail.com>
@[yujincheng08](https://github.com/topjohnwu/Magisk/commits?author=yujincheng08)
@[topjohnwu](https://github.com/topjohnwu/Magisk/commits?author=topjohnwu)
yujincheng08 and topjohnwu committed 3 days ago

That fixed this issue for devices with kernel version >= 3.19.

 ... There is no specific device! This is a general Wontfix notice re Zygisk issue on "some Samsung devices w/ pre 3.19 kernel version...

**Comment by canyie** [comment]
@hanoshita It depends on was Samsung added their stupid exec limitation in the kernel of your device, or not. If Zygisk works on your device, just enjoy it. This is just a notice which points out Zygisk bug reports from Samsung devices using old kernels will be ignored.

**Comment by gregsskyles** [comment]
> > Device: Samsung Android version: N/A Magisk version name: N/A Magisk version code: 24102
> > For some old Samsung devices, there's a kernel restriction that whenever `exec` an ELF from `/proc`, the process can no longer call some systemcalls. For kernel 3.19+, the workaround is `fexecve`, but it does not exist for the old kernel. Users with those devices should use a custom kernel bypassing such a restriction or a newer version.

Thank you for such a clear, understandable and explicit explanation of the issue!

**Comment by yujincheng08** [comment]
> > > Device: Samsung Android version: N/A Magisk version name: N/A Magisk version code: 24102
> > > For some old Samsung devices, there's a kernel restriction that whenever `exec` an ELF from `/proc`, the process can no longer call some systemcalls. For kernel 3.19+, the workaround is `fexecve`, but it does not exist for the old kernel. Users with those devices should use a custom kernel bypassing such a restriction or a newer version.
> 
> Thank you for such a clear, understandable and explicit explanation of the issue!

This is just a copy from this issue...

**Comment by gregsskyles** [comment]
Sorry, missed the earlier comment- came in the middle of this issue. But the thanks still applies to the OP.

**Comment by praveen28624** [comment]
I have Samsung device. It's kernel version is 3.18.140. I have same issue

**Comment by June-AV** [comment]
Tried to install from magisk 21.4 and Disable_Dm-Verity_ForceEncrypt_03.04.2020 with TWRP and update magisk to latest version all normal Zygisk is on. Tried Patch Magisk 24 to AP File Samsung Zygisk won't turn on. Must Change init.rc 

Kernel : 3.18.140

**Comment by IverCoder** [comment]
The latest Canary has fixed this issue. The changelog says so and I have tested it on kernel v3.10.

**Comment by praveen28624** [comment]
> The latest Canary has fixed this issue. The changelog says so and I have tested it on kernel v3.10.

How do I get latest canary?

**Comment by praveen28624** [comment]
> Tried to install from magisk 21.4 and Disable_Dm-Verity_ForceEncrypt_03.04.2020 with TWRP and update magisk to latest version all normal Zygisk is on. Tried Patch Magisk 24 to AP File Samsung Zygisk won't turn on. Must Change init.rc
> 
> Kernel : 3.18.140

How do I get magisk 21.4

**Comment by pndwal** [comment]
> The latest Canary has fixed this issue. The changelog says so and I have tested it on kernel v3.10.

I think there is no fix as stated.

some 3.19- kernels have the exec limitation, some don't, so some will work w/ Zygisk and some won't...

**Comment by xx979xx** [comment]
I have Samsung S8 (SM-G950F) running Android 9 Pie, I struggled with this issue and I find the solution that worked for me very well.
1- Download and install Magisk canary 24.1 721d8d33(24101) from #5353 Do not install the latest canary 9968af07(24103) it causes boot loop.
from @yujincheng08:
> At last, plz try this: [app-debug.zip](https://github.com/topjohnwu/Magisk/files/7996468/app-debug.zip)

2- After installation, rename the file to `magisk.apk` and install the manger.
3- Only upgrade the manager to latest canary for better functionality. Do not upgrade Magisk!!!

**Comment by yujincheng08** [comment]
I came up with an idea that may fix this:

use `/system/bin/linker[64] /proc/self/fd/x` to exec the origin app_process

but `/proc/self/exec` is the linker...

**Comment by luca990** [comment]
hi, with latest canary works, tested on Samsung S7 LineageOS 18.1 Android 11 kernel 3.18.140

**Comment by nm17** [comment]
> I came up with an idea that may fix this:

So is this issue a wontfix or not? Is there a fix planned?

**Comment by ipdev99** [comment]
Canary 24102 broke Zygisk on Nexus 7 (2013) and Pixel C tablets.

After this commit https://github.com/topjohnwu/Magisk/commit/183e5f2ecc1be14bb8ab186f33d3f5cfdab077d3

Zygisk again works on Nexus 7 (2013) and Pixel C tablets.
_Both are currently running Lineage 19.1 builds._

Device: Nexus 7 (2013)
Android version: 12L (SDK32)
Architecture: arm
Kernel version: 3.4.113

Device: Pixel C
Android version: 12L (SDK32)
Architecture: arm64
Kernel version: 3.18.140

Might be time to close this issue. :thinking:

**Comment by canyie** [comment]
@ipdev99 The issue we are talking about is only for Samsung devices

**Comment by nm17** [comment]
@canyie I think I have the same issue on a Meizu M5 Note (old phone, around Android 7). Not sure how to prove it though

**Comment by canyie** [comment]
@nm17 I think it's better to open a new issue for that. Upload boot logcat so devs can take a look.

**Comment by rmjspaz7284** [comment]
![Screenshot_20220415-090126_MEGA](https://user-images.githubusercontent.com/101934230/163808723-f1263850-5af4-4fb5-81b6-a203e2b68f9d.jpg)

**Comment by rmjspaz7284** [comment]
> Device: Samsung Android version: N/A Magisk version name: N/A Magisk version code: 24102
> 
> For some old Samsung devices, there's a kernel restriction that whenever `exec` an ELF from `/proc`, the process can no longer call some systemcalls. For kernel 3.19+, the workaround is `fexecve`, but it does not exist for the old kernel. Users with those devices should use a custom kernel bypassing such a restriction or a newer version.

**Comment by rmjspaz7284** [comment]
#5754

**Comment by canyie** [comment]
Fixed by 9fbd079
