### ISSUE TITLE
Magisk 11 breaks Viper4Android

### ISSUE THREAD

**Issue by cbdreinulldrei** [topjohnwu/Magisk#54]
Although your own Viper implementation does not work on Nougat, it does work when deepbuffer is #commented out.

Magisk 11 breaks it.

**Comment by Shadowghost** [comment]
Interesting, I don't even need any selinux additions since v11 to run viper. It even works when setting whole environment to enforced and not the standard pseudo-permissive mode, not quite sure if that is intended though.

**Comment by cbdreinulldrei** [comment]
Problem was the changed sepolicy syntax. Guess some modules will need updates now.
