### ISSUE TITLE
Apps crashing when zygisk is enabled

### ISSUE THREAD

**Issue by raveen2k3** [topjohnwu/Magisk#5400]
Device: Poco X3 ( karna / surya ) 
Android version: 12 ( Arrow Os)
Magisk version name: 24.1
Magisk version code:  24102

[Matlog report]( https://pastebin.com/r9a4fABM) 

Apps just getting killed by input manager.

**Comment by canyie** [comment]
Please attach full logs instead of the filtered one

**Comment by raveen2k3** [comment]
Issue fixed after clean flash
