### ISSUE TITLE
Checkbox bug in DenyList

### ISSUE THREAD

**Issue by VladWinner** [topjohnwu/Magisk#5407]
The video demonstrates checkbox bug:
https://imgur.com/a/EnhUQhj

[Magisk.log](https://github.com/topjohnwu/Magisk/files/8022859/Magisk.log)

Device: Samsung Galaxy S20 FE Snapdragon, One UI 4.0
Android version: 12
Magisk version name: 1a1b346c
Magisk version code: 24102

**Comment by yujincheng08** [comment]
expected behavior

**Comment by VladWinner** [comment]
@yujincheng08 Why "expected"? This behavior does not affect other apps in DenyList. Have you opened Magisk.log?

**Comment by yujincheng08** [comment]
The checkbox only shows whether recommended processes are selected when collapse. There's no recommended processes for GMS so this is blank when collapsed.

You can reproduce this behavior for other apps by selecting only non-recommended processes.
