### ISSUE TITLE
Right after reboot Magisk runs sh, eating lots of cpu.

### ISSUE THREAD

**Issue by ElCoyote27** [topjohnwu/Magisk#541]
Hi,
I have a concern perhaps related to Magisk.
I've been noticing high cpu usage right after rebooting my phone. Simple Monitor shows the topmost app is 'sh' and thanks to Terminal I traced it to a process started by 
magiskd -post-fs-data.
I usually keep my phone clean but this is making my phone sluggish enough to notice.
Here is my environment:
Xiaomi Mi Mix, LineageOS 15.1 20180828
Magisk 5.9.1.139 with zipfile v17.1
(Had this issue with 5.8.0 and v16.7 too)
Any ideas?

**Comment by shoeper** [comment]
And what is the issue? Magisk is doing some initialization on reboot.

**Comment by ElCoyote27** [comment]
The issue is that it doesn't look like just 'some initialization'. The thing keeps one core at max speed for lots of minutes.

**Comment by MartinX3** [comment]
Here it is always there and drains my battery over the day.

Snapdragon 845
Sony xperia xz2 with omnirom

It is two times open and each consumes ~15% CPU.

**Comment by MartinX3** [comment]
@topjohnwu could you reopen it?
And which logs do you need?
It consumes 74% battery in 11:14 hours
Battery life is usually 2 days here

**Comment by ElCoyote27** [comment]
Hi @MartinX3 I suspect that if you look closer, you'll find that /system/bin/sh is the process eating up your cpus. This is happening because Magisk doesn't properly terminate the shells it forks. This issue is almost as old as Unix-like systems.
I usually deal with it this way after reboot:
- Wait a few minutes after reboot, Go into 'Simple System Monitor' -> 'Active Processes'.
- Kill the most active /system/bin/sh.
(Repeat a couple times as Magisk starts a couple shells).
This is a big annoyance and it's been blatantly ignored by the developers.

**Comment by MartinX3** [comment]
Oh.
I looked into htop and just saw 2 magiskd process eating it
So it is the sh instead?
That's sad.

I assumed this module triggers this bug  fast
https://forum.xda-developers.com/apps/magisk/module-magisk-selinux-permissive-script-t3577549

**Comment by MartinX3** [comment]
Damn
A night in permissive with "setenforce 0", wake up, go into htop, again the CPU drain by these two processes.

**Comment by MartinX3** [comment]
Upgraded to 19.0
Still enforcing

Now two magiskd processes always need 100% each and drain my device.
