### ISSUE TITLE
Can't update and stuck with "Require addition setup", zygisk can't be use normally

### ISSUE THREAD

**Issue by mslxl** [topjohnwu/Magisk#5419]
Device:  Realme Neo (RMX3031)
Android version: 11
Magisk version name: canary
Magisk version code: 24102

Magisk manager always remind me "Require addition setup" , if I click "ok" and repeat install, it will appear again after reboot.

The `Update` button is light up, but it couldn't update magisk although it show "All done". After reboot the version code is not changed.

![Screenshot_2022-02-10-23-13-25-36_785cfb1f0fb0c9a2030c9b38a1c3479a](https://user-images.githubusercontent.com/11132880/153437213-ea6612c9-2c87-4b21-ac55-ef22f7c0993d.jpg)

Magisk manager show that the zygisk is be supported, but it will turn to "No" if I install any module that related to zygisk. After uninstall zygisk module, magisk manager will show "Yes" again.

[magisk_log_2022-02-10T22_58_04.log](https://github.com/topjohnwu/Magisk/files/8041940/magisk_log_2022-02-10T22_58_04.log)

 
[logcat_boot.log](https://github.com/topjohnwu/Magisk/files/8041968/logcat_boot.log)

[logcat_start_magisk_manager_and_click_update.log](https://github.com/topjohnwu/Magisk/files/8041986/logcat_start_magisk_manager_and_click_update.log)

**Comment by mslxl** [comment]
Addition: Superuser can work normally

**Comment by mslxl** [comment]
> ![image](https://user-images.githubusercontent.com/5022927/153492273-4552f08e-3aa8-477e-99dc-b4b3eb0e1fef.png)
> 

it will execute update script and show me "All done", but version code will not change after reboot.

**Comment by mslxl** [comment]
In short, the "update" button doesn't take effect.

Maybe my words it's hard to understand, should I use other device to record a video?
@yujincheng08

**Comment by yujincheng08** [comment]
If you cannot update Magisk, submit another issue. "require addition setup" is definitely because your app's version and core's version are not mathed.

**Comment by mslxl** [comment]
I have mentioned "It cannot update Magisk core" above.  :cry:

Just now I tried "Select and Patch a File" instead of "Direct install". it's so lucky that  my device can't boot after patched  `boot.img` and flash it by hand. So I decide to buy a new phone.

I don't want to open another issue since I can't offer more information later, just leave this issue to others who use same device as me to remind they take care of flashing `boot.img` file.

**Comment by aricooperdavis** [comment]
I'm in the same position with a POCO M4 Pro (Fleur) - the "Direct Install" button doesn't seem to actually have changed the magisk version when it reboots, despite it reporting success.
