### ISSUE TITLE
avd_patch fails due to AVD for Android 31 ramdisk.img not being gzip but rather lz4

### ISSUE THREAD

**Issue by akhilkedia** [topjohnwu/Magisk#5421]
The command `./build.py avd_patch android-sdk/system-images/android-31/google_apis/x86_64/ramdisk.img` fails with `gzip: invalid magic` at line https://github.com/topjohnwu/Magisk/blob/12093a3dad7e2bd0109d6d4ff5f44d694ba4bb04/scripts/avd_patch.sh#L60

Decompressing the original ramdisk with lz4 and recompressing it with gzip using the below commands results in the script running successfully.
```
lz4 -d ramdisk.img ramdisk.cpio
gzip ramdisk.cpio
cp ramdisk.cpio.gz android-sdk/system-images/android-31/google_apis/x86_64/ramdisk.img
<Boot Emulator>
./build.py avd_patch android-sdk/system-images/android-31/google_apis/x86_64/ramdisk.img
```

Also, while the script succeeds, cold booting the emulator after this results in the emulator never starting, but I do not know if this is related to the lz4/gzip issue.

Device: AVD Emulator
Android version: API 31 x86_64 AVD
Magisk version name: canary
Magisk version code: 24102

**Comment by yujincheng08** [comment]
Try #5426
