### ISSUE TITLE
Patching  boot.img fails (Copying to cache, Process error)

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#5429]
Device: Xiaomi 11 Lite 5G NE (Lisa)
Android version: 11
Magisk version name: Canary
Magisk version code: 24102

Stock MIUI 12.5.8 Global

I'm not able to patch the boot image, it always fails with:
Copying image to cache
! Process error
! Installation failed

However, if I take Direct install, it works.

To originally install Magisk, I had to flash it through TWRP (since patching did not work).
I upgraded to 24102 by using Direct install

I tried also patching boot.img from my other phone, from Xiaomi Mi 9T (where I can patch it's boot.img), but here on this
Xiaomi 11 Lite 5G NE patching again
fails while copying the image to Cache with the same error

![IMG_20220210_215356](https://user-images.githubusercontent.com/51943147/153505473-c640cb47-35b2-4dc4-ae46-849bbdba01c8.jpg)

![IMG_20220210_215544](https://user-images.githubusercontent.com/51943147/153505561-5fae35a7-b6bc-4907-82a6-76dc99ce44de.jpg)

[magisk_install_log_2022-02-10T22_47_50.log](https://github.com/topjohnwu/Magisk/files/8044686/magisk_install_log_2022-02-10T22_47_50.log)

[magisk_log_2022-02-10T22_48_03.log](https://github.com/topjohnwu/Magisk/files/8044687/magisk_log_2022-02-10T22_48_03.log)

**Comment by zgfg** [comment]
[logcat.zip](https://github.com/topjohnwu/Magisk/files/8044769/logcat.zip)

**Comment by yujincheng08** [comment]
This is nothing to do with Magisk. Magisk tries to read the boot.img after you selected it from a file manager, but it fails.

**Comment by zgfg** [comment]
@yujincheng08 thanks for the hint

I now carefully retested many times and with various boot images

On both phones, new Lisa (Xiaomi 11 Lite 5G NE) and the old Davinci (Xiaomi Mi 9T), both running MIUI 12.5+, A11:

- If I use the stock Files, patching works with no problem

- Reported Copying to Cache / Process error happens when I use MiXPlorer

----

However, one thing is strange. On my old Davinci (daily driver for two years) I always used MiXplorer (I had stock Files frozen) and never observed any problem with patching, up to Magisk Alpha 23017

Then I froze MiXPlorer (wanted to have more RAM).

Now when I un-froze MiXPlorer it also fails patching with Magisk 24102 also on that old Davinci

On Davinci, I didn't change anything (same ROM, same version of MiXPlorer), hence it means that something changed on Magisk between 23017 and 24102, causing that the same version of MiXPlorer fails if used for patching

----

Anyway, I will now use the stock Files, patching works fine with
