### ISSUE TITLE
pixel 2 xl android 9 , magisk 17.1 boot struck

### ISSUE THREAD

**Issue by Sherlock-Holo** [topjohnwu/Magisk#543]
iamges: taimen-ppr1.180610.009-factory-3fb33477

magisk: 17.1

I try every combination with enable force encrypt and AVB/2.0 option and then flash the pacth.boot.img, it stuck, when i read log from adb: the most is 

> 09-02 10:29:48.008 I/crash_dump32( 1804): performing dump of process 1797 (target tid = 1797)
> 09-02 10:29:48.020 E/crash_dump32( 1804): unable to connect to activity manager: Connection refused
> 09-02 10:29:48.020 E//system/bin/tombstoned(  963): Tombstone written to: /data/tombstones/tombstone_01
> 09-02 10:29:48.215 I/ServiceManager(  902): Waiting for service sensorservice...
> 09-02 10:29:48.247 W/ServiceManagement(  783): Waited one second for android.frameworks.sensorservice@1.0::ISensorManager/default. Waiting another...
> 09-02 10:29:49.217 I/ServiceManager(  902): Waiting for service sensorservice...
> 09-02 10:29:49.247 W/ServiceManagement(  783): Waited one second for android.frameworks.sensorservice@1.0::ISensorManager/default. Waiting another...
> 09-02 10:29:50.221 I/ServiceManager(  902): Waiting for service sensorservice...
> 09-02 10:29:50.247 W/ServiceManagement(  783): Waited one second for android.frameworks.sensorservice@1.0::ISensorManager/default. Waiting another...

maybe the pid is different with every booting, I don't know how magisk work but I know when we see crash, dump etc on the log, it usually is a bad news

I feel dispoint with magisk, when I using nexus 6p magisk help me a lot and when my pixel 2 xl on android o, magisk works well too, but when I started use P, after flash patch boot to install magisk, boot stuck any times.

 Hope anyone could tell me how to do unless flashing with TWRP, I want to enjoy OTA

**Comment by rmit-s3235459-johan-vanzyl** [comment]
Same here. v17.0 worked fine. v17.1 causes bootloops

**Comment by topjohnwu** [comment]
All my testers using Pixel 2/ Pixel 2 XL reports no issues at all.
I have a Pixel XL on Android P myself and there are no issues whatsoever.

@rmit-s3235459-johan-vanzyl this is impossible, the changes in v17.0 to v17.1 is too minor to cause any behavior difference.

**Comment by Sherlock-Holo** [comment]
should I disable secure boot on my pixel 2 xl?

**Comment by Sherlock-Holo** [comment]
I fastboot boot twrp.img and then rm -rf /data/adb/* and then refresh magisk, it's ok

**Comment by Sherlock-Holo** [comment]
yes and I remember I clean /usually/adb directory to resolve it.

Ivan Ng <notifications@github.com> 于 2018年12月10日周一 16:24写道：
