### ISSUE TITLE
zygisk sets umask to 000

### ISSUE THREAD

**Issue by shadmansaleh** [topjohnwu/Magisk#5435]
I'm facing a strange issue, if I enable zygisk `umask` for users/apps gets set to `000` . That means If I create any directory it by default gets `0777` permission. I think magisk is setting it to 0 then forgetting to set it back to 22 somewhere :/

Copy of #5434 I can reproduce it on canary too :D

Device: SM-J700H
Android version: 11
Magisk version name:  canary
Magisk version code: 24102

**Comment by yujincheng08** [comment]
should be here

https://github.com/topjohnwu/Magisk/blob/ea75a09f95bb6d3117f4050f0c99266c007edaf6/native/jni/core/applets.cpp#L32
