### ISSUE TITLE
Don't abort install script when TWRP can't mount system

### ISSUE THREAD

**Issue by asuka-mio** [topjohnwu/Magisk#5439]
Device: 
Android version:12
Magisk version name: magisk canary 25
Magisk version code: 24102

Try adb sideload a magisk zip to install magisk in twrp, and twrp can't mount system partition, then the install process will abort. Since we used erofs on system and other ro partitions, mount it in twrp will be meaningless, so just ignore that error and continue patching and flashing boot partition

**Comment by asuka-mio** [comment]
Actually I removed "mount_partitions" in flash script then it works well, but i know it's not a graceful fix

**Comment by vvb2060** [comment]
https://topjohnwu.github.io/Magisk/install.html#custom-recovery

**Comment by nofishonfriday** [comment]
Hi, I have the same problem.
@asuka-mio 
> Actually I removed "mount_partitions" in flash script then it works well, but i know it's not a graceful fix

Could you give detailed instructions please?

**Comment by asuka-mio** [comment]
> Hi, I have the same problem. @asuka-mio
> 
> > Actually I removed "mount_partitions" in flash script then it works well, but i know it's not a graceful fix
> 
> Could you give detailed instructions please?
> 
> edit: Reverted to v24.1 (from v24.3) which doesn't have this issue.

https://github.com/topjohnwu/Magisk/blob/edb76503d36f05a757fa4e652a2dfbbb471695ad/scripts/flash_script.sh#L40
Just delete this line

**Comment by osm0sis** [comment]
These are different issues. 24.1 didn't have the NDK busybox readlink regression, and the erofs thing is new. I agree there's no reason to require system mounted nowadays.

**Comment by osm0sis** [comment]
I take it back, mounting system is important for the installation to determine whether the device is SAR (SYSTEM_ROOT=true), as this determines whether Magisk will set KEEPVERITY=true for its config.

I don't see a way around it, so I'd suggest you have your recovery maintainer add erofs support to be able to mount system ro.
