### ISSUE TITLE
Magisk 17 and 17.1 issues

### ISSUE THREAD

**Issue by anishmworld** [topjohnwu/Magisk#544]
My setup is Redmi Note 4 (mido), LOS 15.1, no custom kernel.
I was on 16.7 before the update.  
After updating to 17.0, these things happened:  
- during every boot, the boot animation would suddenly disappear, but the screen remained on.  
- Then after some time, the lock screen appears, but the sim card is not detected.  
- after a reboot, the sim is detected.  
- apps which connect to the internet are working fine, but browsers wouldn't load any Google pages and play store went crazy. Other Google apps were working, though.  
- the internal storage got kind of crazy. Renaming files would take 2-3 attempts, trying to install any app would give an error, some files in folders went missing.  
- going into storage info for any app would say "couldn't compute package sizes" for all the storage headings (app size, user data, cache etc.)  
- Hotspot and flash toggles didn't work, Camera apps would show a black screen and say that there is space "<20" pictures even though there is enough space.  
- reverted to 16.7, everything went back to normal. However, the files that went missing were not found again.  

After updating to 17.1, during boot the screen would suddenly turn off. Not like going black like during 17.0, the screen will actually be off. The phone then didn't respond to any inputs. Force rebooting multiple times led to the same thing. Reverted to 16.7 and now working fine.

**Comment by topjohnwu** [comment]
This seems to be some MIUI issue, dunnot how to fix due to the fact I don't have one.
Some developers might be able to figure it out though.

**Comment by anishmworld** [comment]
I'm not on MIUI. As mentioned above, I've got Lineage OS 15.1
