### ISSUE TITLE
hi, i ran into a magisk problem.  I uploaded it as an APK from the module section to downgrade the application version to 23.0.  When I restarted the phone, it didn't detect root.  can you just help?

### ISSUE THREAD

**Issue by Ba9972** [topjohnwu/Magisk#5444]
Device: general Mobile GM 9 pro
Android version:10
Magisk version name: 24.1 
Magisk version code: 24102

**Comment by yujincheng08** [comment]
No support for old version. Closed.

**Comment by pndwal** [comment]
Check you didn't leave app hidden. See if a prior app named Settings (default) or some name you chose is in device settings, apps... Uninstall if found.
