### ISSUE TITLE
Mount fail on over v20.4

### ISSUE THREAD

**Issue by TsXor** [topjohnwu/Magisk#5445]
Device: Huawei Honor V9 (DUK-AL20)
Android version: 9 (LineageOS, flashed on 'base package' EMUI8)
Magisk version name: magisk canary
Magisk version code: 24102

Magisk version above v20.4 will fail to mount things with `magiskinit` 
Magiskinit returns the following errors: (collected from `dmesg`)
```
[   15.122406] [pid:1,cpu6,init]magiskinit: mount ->/bfi failed with 19: No such device
[   15.161254] [pid:1,cpu6,init]magiskinit: mount ->/dfx failed with 19: No such device
[   15.198242] [pid:1,cpu6,init]magiskinit: mount ->/odm failed with 22: Invalid argument
[   15.235961] [pid:1,cpu7,init]magiskinit: mount ->/cust failed with 22: Invalid argument
[   15.273773] [pid:1,cpu7,init]magiskinit: mount ->/misc failed with 19: No such device
[   15.311614] [pid:1,cpu5,init]magiskinit: mount ->/ramdisk failed with 22: Invalid argument
[   15.350128] [pid:1,cpu6,init]magiskinit: mount ->/rrecord failed with 19: No such device
[   15.387878] [pid:1,cpu7,init]magiskinit: mount ->/system failed with 22: Invalid argument
[   15.425354] [pid:1,cpu7,init]magiskinit: mount ->/version failed with 22: Invalid argument
[   15.462615] [pid:1,cpu5,init]magiskinit: mount ->/vendor failed with 22: Invalid argument
[   15.500396] [pid:1,cpu7,init]magiskinit: mount ->/product failed with 22: Invalid argument
[   15.508514] [pid:1,cpu5,init]magiskinit: mount /dev/block/data->/dev/mnt/data failed with 22: Invalid argument

[   15.539611] [pid:1,cpu6,init]magiskinit: Unmount [/dev/mnt/cache]
[   15.539642] [pid:1,cpu6,init]magiskinit: umount2 /product failed with 22: Invalid argument
[   15.539642] [pid:1,cpu6,init]magiskinit: umount2 /vendor failed with 22: Invalid argument
[   15.539642] [pid:1,cpu6,init]magiskinit: umount2 /version failed with 22: Invalid argument
[   15.539642] [pid:1,cpu6,init]magiskinit: umount2 /system failed with 22: Invalid argument
[   15.539672] [pid:1,cpu6,init]magiskinit: umount2 /rrecord failed with 22: Invalid argument
[   15.539672] [pid:1,cpu6,init]magiskinit: umount2 /ramdisk failed with 22: Invalid argument
[   15.539672] [pid:1,cpu6,init]magiskinit: umount2 /misc failed with 22: Invalid argument
[   15.539672] [pid:1,cpu6,init]magiskinit: umount2 /cust failed with 22: Invalid argument
[   15.539672] [pid:1,cpu6,init]magiskinit: umount2 /odm failed with 22: Invalid argument
[   15.539703] [pid:1,cpu6,init]magiskinit: umount2 /dfx failed with 22: Invalid argument
[   15.539703] [pid:1,cpu6,init]magiskinit: umount2 /bfi failed with 22: Invalid argument
[   15.551055] [pid:1,cpu5,init]magiskinit: Unmount [/sys]
[   15.562500] [pid:1,cpu6,init]magiskinit: Unmount [/proc]
```
While magisk v20.4 and below returns no such errors。

Note: The 'base package' is EMUI8, so there's no thing about `erofs`.

**Comment by TsXor** [comment]
[dmesg_3.txt](https://github.com/topjohnwu/Magisk/files/8053395/dmesg_3.txt)
Collected with command `adb wait-for-device root && adb shell dmesg > \path\to\this\file`

**Comment by TsXor** [comment]
> Is this related to #5412 ? If your real issue is, magisk 21+ does not work, then I think this is harmless.
> 
> ```
> magiskinit: sepol: no selinux
> magiskinit: Inject magisk services: [KCSWlwJLCI] [xP08VHGWati] [94POoEP]
> init: Loading SELinux policy
> init: Compiling SELinux policy
> selinux: SELinux: Loaded policy from /dev/sepolicy.iYtnML\x0a
> init: starting service 'KCSWlwJLCI'...
> init: cannot setexeccon('u:r:magisk:s0') for KCSWlwJLCI: Invalid argument
> ```
> 
> I think the real reason should be this, your rom using weird sepolicy path so magisk failed to patch it. May you upload `/init`? And can you confirm the `/dev/sepolicy.iYtnML` file does still exist after reboots?

I need to say that I do think it is a thing related to SElinux. As you can see, v21.0 was a huge update to `Magiskpolicy` and after v21.0 there's definitely NO changes about `Magiskpolicy` declared in the changelog.

**Comment by TsXor** [comment]
[init.zip](https://github.com/topjohnwu/Magisk/files/8053520/init.zip)
and
```
:/ # ls -l /dev | grep sepolicy
(returns nothing)
```

**Comment by TsXor** [comment]
@canyie
This might really be things about sepolicy according to [this webpage](https://www.dazhuanlan.com/alistertt/topics/1306720#:~:text=%E4%B8%8B%E8%BD%BD%20Bootimg.exe%20%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%B7%A5%E5%85%B7%E7%94%A8%E6%9D%A5%E8%A7%A3%E5%8C%85%20ramdisk.img%20%E6%8A%8A%20ramdisk.img%20%E6%94%B9%E5%90%8D%E4%B8%BA,boot.img%EF%BC%8C%E5%B9%B6%E4%B8%8E%20bootimg.exe%20%E6%94%BE%E5%88%B0%E5%90%8C%E4%B8%80%E4%B8%AA%E6%96%87%E4%BB%B6%E5%A4%B9%20%E5%9C%A8%E8%AF%A5%E6%96%87%E4%BB%B6%E5%A4%B9%E5%90%AF%E5%8A%A8%20cmd%EF%BC%8C%E8%BE%93%E5%85%A5%20bootimg.exe%20--unpack-bootimg%20%EF%BC%8C%E8%A7%A3%E5%8C%85).
It mentions:
> 提取 sepolicy 文件。
> 由于 EMUI8 使用了 split sepolicy，所以 ramdisk 下没有 sepolicy 文件，
> 不过你可以从 vendor.img 中找到他。
In English: (I know you won't need this ;) )
> Extracting sepolicy file。
> Due to the application of split sepolicy on EMUI8, there's no sepolicy file in ramdisk,
> but you can find it in vendor.img.

**Comment by canyie** [comment]
![image](https://user-images.githubusercontent.com/31466456/153737872-a1758aa0-f2de-403f-ab43-e0325b211997.png)
Sorry, should be here, your rom uses split sepolicy which means it actually uses cil files in /system, /vendor and /odm partitions. Magisk fails to mount them, and recognized it as no selinux device. We need the boot.img file and vendor_boot.img (if it exists)  to find out why.
应该是这里，你的系统用的是 split sepolicy ，实际是存在 /system /vendor /odm 这些分区里，magisk 挂载失败然后把设备识别成没有 selinux。需要 boot.img 和 vendor_boot.img（如果有的话）来调查。

**Comment by TsXor** [comment]
[ramdisk.tar.gz](https://github.com/topjohnwu/Magisk/files/8055142/ramdisk.tar.gz)
ramdisk.img unpacked with Android image Kitchen.
On EMUI8 partitions devices boot.img is ramdisk.img ;)

**Comment by TsXor** [comment]
I think this issue will most probably end up with confirming that it is something tricky on my device instead of magisk update that causes this.
So I think I should focus on solving this problem on my side. Is it possible that I can extract the policy from vendor.img and put in into appropriate path in ramdisk.img so that magisk can recognize it?

**Comment by TsXor** [comment]
I noticed that there's a `sepolicy` file under the recovery_ramdisk in a normal working EMUI9.1 device, so I tried repacking the ramdisk.img with the `precompiled_sepolicy` from vendor, and my phone failed to boot, didn't even execute userinit and leave me a dmesg log :(

**Comment by TsXor** [comment]
@canyie 
lol the real reason was found out! This issue is the same as #3021
I did a `cat /proc/cmdline` and found `androidboot.hardware=<value>` was really missing!
On the working EMUI9 device, `cat /proc/cmdline` got `androidboot.hardware=hi3660`
Note: `hi3660` represents kirin960&960s, the working EMUI9 device is MediaPad M5 which uses kirin960s, and Honor V9 uses kirin960.
However, although it seems that the problem is solved now, I haven't really tried this because changing the kernel cmdline requires me to complie a kernel from source myself. I'll close this when I successfully re-compile the kernel and resolve this issue.
省流：找到解决方法了，需要重新编译内核，编译太费劲了得等几天，问题解决了再关issue

**Comment by TsXor** [comment]
说实话俩中国人操着英语交流挺搞笑的，但如果不这么做我就会被当成sb小白然后立马随便找个理由close掉（迫真）

**Comment by vvb2060** [comment]
> Android version: 9 (LineageOS, flashed on 'base package' EMUI8)

看起来是这个自定义ROM的问题

**Comment by TsXor** [comment]
> > Android version: 9 (LineageOS, flashed on 'base package' EMUI8)
> 
> 看起来是这个自定义ROM的问题

See [this link](https://www.coolapk.com/feed/32027374). He have that LineageOS flashed on 'base package' EMUI8 as well.
See what's in that link requires you to have Coolapk installed on your phone, and I think you can do it.
What's more, while I was still at EMUI5 I tried to flash magisk patched ramdisk.img as well but was faced with the same issue.

**Comment by TsXor** [comment]
> > Android version: 9 (LineageOS, flashed on 'base package' EMUI8)
> 
> 看起来是这个自定义ROM的问题

I asked that person to exec `cat /proc/cmdline` and he got `androidboot.hardware=hi3650`

**Comment by TsXor** [comment]
@canyie 
I'm feeling sorry to disturb you, but I just executed `cat /proc/cmdline` again and found somehow `androidboot.hardware=hi3660` was there, so it may just be a fault of my eye :(
Then I noticed #4306. I tried to complie 8ab0453 & 0c99c4d and found that I was faced with the exactly same issue.
I did further test and found something. Sorry but my poor English doesn't allow me to give full description, so I have to switch my language :(
0.  8ab0453 的成功log：
```
[   15.079498] [pid:1,cpu6,init]magiskinit: Early mount system
[   15.083892] [pid:1,cpu6,init]magiskinit: Found system_a: [mmcblk0p57] (179, 57)
[   15.098266] [pid:1,cpu7,init]EXT4-fs (mmcblk0p57): mounted filesystem without journal. Opts: (null)
[   15.098327] [pid:1,cpu7,init]magiskinit: Early mount vendor
[   15.098358] [pid:1,cpu7,init]magiskinit: Found vendor_a: [mmcblk0p54] (179, 54)
[   15.109039] [pid:1,cpu7,init]EXT4-fs (mmcblk0p54): mounted filesystem with ordered data mode. Opts: (null)
[   15.109100] [pid:1,cpu7,init]magiskinit: Early mount product
[   15.109100] [pid:1,cpu7,init]magiskinit: Found product_a: [mmcblk0p55] (179, 55)
[   15.119964] [pid:1,cpu7,init]EXT4-fs (mmcblk0p55): mounted filesystem with ordered data mode. Opts: (null)
[   15.119995] [pid:1,cpu7,init]magiskinit: Early mount odm
[   15.120025] [pid:1,cpu7,init]magiskinit: Found odm_a: [mmcblk0p18] (179, 18)
[   15.134185] [pid:1,cpu6,init]EXT4-fs (mmcblk0p18): mounted filesystem with ordered data mode. Opts: (null)
[   15.134216] [pid:1,cpu6,init]magiskinit: Found persist: [mmcblk0p2] (179, 2)
[   15.136688] [pid:1,cpu7,init]EXT4-fs (mmcblk0p2): VFS: Can't find ext4 filesystem
[   15.136901] [pid:1,cpu7,init]magiskinit: mount /dev/block/persist->/dev/mnt/persist failed with 22: Invalid argument
```
注：
```
lrwxrwxrwx 1 root root   21 2022-02-16 17:38 system_a -> /dev/block/mmcblk0p57
lrwxrwxrwx 1 root root   21 2022-02-16 17:38 vendor_a -> /dev/block/mmcblk0p54
lrwxrwxrwx 1 root root   21 2022-02-16 17:38 product_a -> /dev/block/mmcblk0p55
lrwxrwxrwx 1 root root   21 2022-02-16 17:38 odm_a -> /dev/block/mmcblk0p18
lrwxrwxrwx 1 root root   20 2022-02-16 17:38 persist -> /dev/block/mmcblk0p2
```
1.对device tree路径的识别没有问题。 8ab0453 和 0c99c4d 都在dmesg中返回了`dt_dir=[/proc/device-tree/firmware/android]`
注：稳定版v20.4无法获取这一项，它并不在logd中打印这些信息。
2.从 0c99c4d 开始，会输出和最初一样的挂载错误信息。
3.关于两个fstab: `/vendor/etc/fstab.hi3660` 和 `/proc/device-tree/firmware/android/fstab`。如挂载错误提示，`/bfi` `/dfx` `/misc` `/rrecord` 对应的设备并不存在。但是问题在于，它们只存在于`/proc/device-tree/firmware/android/fstab`，`/vendor/etc/fstab.hi3660`中并没有这几项。
4.我查看了 0c99c4d ，很抱歉我对C++连最基本的了解都没有过，但是我看出了在这次更改中`mount_root(分区名)`这个函数被替换为了`dt_early_mount()`，而

**Comment by TsXor** [comment]
I finally got time to torture my phone ;)
For debugging, I added `LOGD("mount params:1.%s; 2.%s; 3.%s; 4.%d.",blk_info.block_dev, entry.mnt_point.data(), entry.type.data(), MS_RDONLY);` after the call of `xmount` in order to get the arguments `xmount` used.
Fortunately my phone successfully boot and enable me to get some dmesg log :)
The parameter log: (so sorry but I do not know anything about C and missed `\n`)
```
[   11.781097] [pid:1,cpu4,init]magiskinit: mount ->/bfi failed with 19: No such device
[   11.781127] [pid:0,cpu0,swapper/0]magiskinit: mount params:1.; 2./bfi; 3.emmc; 4.1.
[   11.823089] [pid:1,cpu5,init]magiskinit: mount ->/cust failed with 22: Invalid argument
[   11.823089] [pid:1,cpu7,init]magiskinit: mount params:1.; 2./cust; 3.ext4; 4.1.
magiskinit: mount ->/system failed with 22: Invalid argument
[   11.864135] [pid:6,cpu6,kworker/u16:0]magiskinit: mount params:1.; 2./system; 3.ext4; 4.1.
[   11.905151] [pid:1,cpu7,init]magiskinit: mount ->/ramdisk failed with 22: Invalid argument
[   11.905151] [pid:1,cpu7,init]magiskinit: mount params:1.; 2./ramdisk; 3.ext4; 4.1.
magiskinit: Setup persist: [mmcblk0p2] (179, 2)
[   11.914031] [pid:1,cpu5,init]EXT4-fs (mmcblk0p2): VFS: Can't find ext4 filesystem
[   11.914062] [pid:1,cpu5,init]magiskinit: mount /dev/block/persist->/dev/mnt/persist failed with 22: Invalid argument
(*note: Mounting persist is in another function which calls `xmount`. I didn't add parameter logging to that function.)
[   11.914093] [pid:1,cpu5,init]magiskinit: sepol: no selinux
```
It seems that there's something wrong about the fiest parameter: `blk_info.block_dev`
@canyie

**Comment by vvb2060** [comment]
把 /proc/device-tree/firmware/android 打包上传，persist分区是在这里配置的吧？然后坏了

**Comment by TsXor** [comment]
> 把 /proc/device-tree/firmware/android 打包上传，persist分区是在这里配置的吧？然后坏了
但是persist在 0c99c4d 造成system vendor product odm全体不能挂载之前就已经坏了。persist更有可能是由于更往前的更改或者treble rom的魔改坏掉的。

**Comment by vvb2060** [comment]
东西呢

**Comment by TsXor** [comment]
> 东西呢

[android.zip](https://github.com/topjohnwu/Magisk/files/8098511/android.zip)

**Comment by TsXor** [comment]
> persist分区不是从DT配置的，没有找到；也没有在你前面发的fstab.hi3660里面找到。

但是persist分区不是重点，在 0c99c4d 之前它也不能正常挂载，尽管如此还是一切正常

**Comment by TsXor** [comment]
> According to the code, if [0c99c4d](https://github.com/topjohnwu/Magisk/commit/0c99c4d93f638d5cde9a232321af791c54be278b) could behave normally, it should log `"Setup %s: [%s] (%d, %d)\n", dev.partname, dev.devname, dev.major, dev.minor` where [8ab0453](https://github.com/topjohnwu/Magisk/commit/8ab045331bf0055ef92a8ca4e26c66bf2108724f) log `"Found %s: [%s] (%d, %d)\n", dev.partname, dev.devname, dev.major, dev.minor` For example, where [8ab0453](https://github.com/topjohnwu/Magisk/commit/8ab045331bf0055ef92a8ca4e26c66bf2108724f) log: `magiskinit: Found system_a: [mmcblk0p57] (179, 57)` [0c99c4d](https://github.com/topjohnwu/Magisk/commit/0c99c4d93f638d5cde9a232321af791c54be278b) should log: `magiskinit: Setup system_a: [mmcblk0p57] (179, 57)` but [0c99c4d](https://github.com/topjohnwu/Magisk/commit/0c99c4d93f638d5cde9a232321af791c54be278b) have no such log. The latest canary have `Setup` log entry for only `userdata` and `cache` :
> 
> ```
> [   15.500549] [pid:1,cpu7,init]magiskinit: Setup userdata: [mmcblk0p59] (179, 59)
> [   15.508544] [pid:1,cpu5,init]magiskinit: Setup cache: [mmcblk0p17] (179, 17)
> ```
> 
> **Why I mention this:** This log is just after `sprintf(blk_info.block_dev, "/dev/block/%s", dev.devname);`( [0c99c4d](https://github.com/topjohnwu/Magisk/commit/0c99c4d93f638d5cde9a232321af791c54be278b) ) or `sprintf(block_dev, "/dev/block/%s", dev.devname);`( [8ab0453](https://github.com/topjohnwu/Magisk/commit/8ab045331bf0055ef92a8ca4e26c66bf2108724f) ), which does the job of getting the first parameter of `xmount`.

根据这个可以判定，很可能是 0c99c4d 中其他文件的更改导致了sprintf（提供xmount的第一个参数）和logd（正常行为是在dmesg中记录Setup xxx）所属的if语句：`if (strcasecmp(dev.partname, blk_info.partname) == 0) {`不满足条件，导致它俩都没被执行，因此xmount的第一个参数为空，dmesg里也没有Setup xxx

**Comment by vvb2060** [comment]
确认一下，设备不是 A/B 设备，但cmdline里面存在`androidboot.slot_suffix=_a`，对吧？
这是否是自定义ROM的失误？

**Comment by vvb2060** [comment]
估计你对细节很感兴趣，问题在这里。
https://github.com/topjohnwu/Magisk/blob/e7c82f20e3d7d7b47221b454508d07aefc14e7c0/native/jni/init/mount.cpp#L166-L168

以system分区为例，相当于
```
sprintf(blk_info.partname, "%s%s", "system_a", "_a"); 
```
所以`blk_info.partname`的值为`system_a_a`。
如果你想做兼容处理，可以在168行前检查`blk_info.partname`并完成修改。

**Comment by vvb2060** [comment]
810d27a fixed
