### ISSUE TITLE
Kernel 32bit after flashing Magisk with TWRP, Flashing via Manager is fine

### ISSUE THREAD

**Issue by SoLdieR9312** [topjohnwu/Magisk#545]
Device: SM-G96X, SM-G95X
Magisk Version: 17.1
Since you dropped 64bit binaries, Kernel always outputs as 32 bit if i flash magisk in TWRP.
Flashable detects device as arm64, but the -v8a extension is not mentioned there.

If i update Magisk via Manager, it detects arm64-v8a and Kernel is displayed as 64bit.

**Comment by topjohnwu** [comment]
Nothing is wrong here, Magisk will always use 32 bit binaries
