### ISSUE TITLE
Magisk support with Samsung GSIs

### ISSUE THREAD

**Issue by Svirusx** [topjohnwu/Magisk#5452]
Device: Samsung Galaxy S20 FE 5g
Android version: Android 12 (GSI)
Magisk version name: 1a1b346
Magisk version code: 24102

Latest version of magisk make bootloop with GSIs on S20 FE 5G
Hey i found that here is one version of magisk which support GSI on S20 FE 5g exactly
"version": "92546e8a",
"versionCode": "23016",
Downloadable here: https://github.com/topjohnwu/Magisk/files/7819803/app-debug.zip
Have this version something special which made it bootable with GSIs?

I tried to find source code of this version to try to fix latest magisk to work with GSI but i couldn't find anything.

Looks like this special version of magisk is based on:
"version": "7a8237a3",
"versionCode": "23016",
I found only "https://github.com/topjohnwu/magisk-files/commit/08bd8f97fe0fc4941bf3ea05db7459905488cd39"

**Comment by yujincheng08** [comment]
no special support for it.

**Comment by yujincheng08** [comment]
Duplicate of #5432
