### ISSUE TITLE
Magisk 17.1 Apps Crashing when added to Magisk Hide

### ISSUE THREAD

**Issue by saurjk** [topjohnwu/Magisk#546]
Any app I add to Magisk Hide crashes everytime I try to open them. The logcat is below:

09-02 09:05:34.789 I/ActivityManager(1341): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=nl.rabomobiel/nl.rabobank.bankierenplus.URActivity (has extras)} from uid 10108 pid 3613
09-02 09:05:34.804 D/RestartProcessManager(1341): Update Total Launch Times :nl.rabomobiel
09-02 09:05:34.804 D/RestartProcessManager(1341): updateSelf :  nl.rabomobiel, size : 2
09-02 09:05:34.804 D/RestartProcessManager(1341): Increase Total Launch Time : nl.rabomobiel, times : 3, index : 1
09-02 09:05:34.804 D/RestartProcessManager(1341): Last Running Package : nl.rabomobiel , start time 1535871934804
09-02 09:05:34.815 I/ActivityManager(1341): Start proc 16248:nl.rabomobiel/u0a249 for activity nl.rabomobiel/nl.rabobank.bankierenplus.URActivity
09-02 09:05:34.815 I/Magisk  (676): proc_monitor: nl.rabomobiel
09-02 09:05:34.869 E/AndroidRuntime(16248): Process: nl.rabomobiel, PID: 16248
09-02 09:05:34.869 E/AndroidRuntime(16248): java.lang.RuntimeException: Unable to create application nl.rabobank.bankierenplus.AppController: android.content.res.Resources$NotFoundException: String array resource ID #0x5080012
09-02 09:05:34.869 E/AndroidRuntime(16248): 	at nl.rabobank.bankierenplus.AppController.onCreate(SourceFile:36)
09-02 09:05:34.872 W/ActivityManager(1341):   Force finishing activity nl.rabomobiel/nl.rabobank.bankierenplus.URActivity
09-02 09:05:34.875 I/ActivityManager(1341): Showing crash dialog for package nl.rabomobiel u0
09-02 09:05:34.875 D/RestartProcessManager(1341): Duration is too short, ignore : 69 in nl.rabomobiel
09-02 09:05:35.374 W/ActivityManager(1341): Activity pause timeout for ActivityRecord{4d82a69 u0 nl.rabomobiel/nl.rabobank.bankierenplus.URActivity t607 f}
09-02 09:05:36.851 W/ActivityManager(1341):   Force finishing activity nl.rabomobiel/nl.rabobank.bankierenplus.URActivity
09-02 09:05:36.857 I/ActivityManager(1341): Killing 16248:nl.rabomobiel/u0a249 (adj 900): crash
09-02 09:05:36.859 D/ActivityManager(1341): Process nl.rabomobiel has 0 services
09-02 09:05:36.882 D/EmbryoManager(1341): prepare nl.rabomobiel user 0
09-02 09:05:36.902 W/ViewRootImpl[rabomobiel](1341): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=611.0, y[0]=792.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=718441, downTime=718434, deviceId=5, source=0x1002 }

**Comment by HeyItsJono** [comment]
Same issue here. Latest Magisk Manager, Magisk 17.1, Oreo 8.1 (July patch), Pixel 2XL. Complete uninstall/reinstall didn't fix the problem.

[Magisk Log](https://pastebin.com/3i0fJrND), [Logcat](https://pastebin.com/S7JXeZ5T).

**Comment by DanielCeregatti** [comment]
Here simply attempting to pull up the Magisk Hide option inside of Magisk 17.1 crashes the app. Apps that require explicit hiding are not working.

**Comment by dragonbiteshard** [comment]
Same issue. In Magisk Manager v17.1 - app crashes phone freezes and requires a hard restart when any app is selected in Magisk Hide.  Originally in v17 just trying to select Magisk Hide option crashed Magisk and then android - also requiring a hard restart.  * S6 edge + 7.0 (latest build ((AUG)).

**Comment by ranahan** [comment]
Same here. V17.1 
App crashes phone freezes and requires a hard restart when trying to select Magisk Hide un Config. After hard reset option keeps selected,  and when trying to Select magisk hide. App crashes.

**Comment by ThotSoft** [comment]
Just like my problem. But with just 17.0 i got crash, but my problem is far more worse. Magisk Log doesn't work at all, only root access work. Every single method on XDA threads failed and also tried old closed thread but no solution. 16 works superb, Safety Check also work fine on 16. But now whenever I installed Xposed, Safety Net doesn't passed any test. I even tried flash stock boot and patched again but, same problemo Magisk Hide button, and Safety Check failure with any modules whether modules is upgraded or latest brand new, they crash like a charms. Look like we have to wait Sir.John, think he will figure it out soon.

**Comment by HeyItsJono** [comment]
Y'all should post logs if you're having the same issue, might help.

@ThotSoft Xposed has always broken SafetyNet. There is no way to pass SafetyNet while you have the Xposed module enabled, you'll have to disable Xposed in Magisk and reboot whenever you want to pass SafetyNet.

**Comment by alvinhochun** [comment]
Similar issue, any apps added to Magisk Hide would crash on Resources.NotFoundException, though mine has a different stack trace.

Nexus 5X, Android 8.1.0 OPM2.171019.029
Magisk 17.1, Magisk Manager 6.0.1 (151)

```
10-21 20:35:07.358  3294  6501 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.scottyab.safetynet.sample/com.scottyab.sateynet.sample.MainActivity (has extras)} from uid 10098
10-21 20:35:07.393  3294  6590 I ActivityManager: Start proc 15392:com.scottyab.safetynet.sample/u0a147 for activity com.scottyab.safetynet.sample/com.scottyab.sateynet.sample.MainActivity
10-21 20:35:07.394  2916  2928 I Magisk  : proc_monitor: com.scottyab.safetynet.sample
10-21 20:35:07.442 15392 15392 W asset   : Asset path /system/framework/framework-res.apk is neither a directory nor file (type=1).
10-21 20:35:07.446 15392 15392 W asset   : Asset path /system/framework/framework-res.apk is neither a directory nor file (type=1).
10-21 20:35:07.453 15392 15392 W ResourceType: No known package when getting value for resource number 0x01120037
10-21 20:35:07.454 15392 15392 D AndroidRuntime: Shutting down VM
10-21 20:35:07.454 15392 15392 E AndroidRuntime: FATAL EXCEPTION: main
10-21 20:35:07.454 15392 15392 E AndroidRuntime: Process: com.scottyab.safetynet.sample, PID: 15392
10-21 20:35:07.454 15392 15392 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.scottyab.safetynet.sample/com.scottyab.sateynet.sample.MainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x1120037
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-21 20:35:07.454 15392 15392 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x1120037
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:215)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.content.res.Resources.getBoolean(Resources.java:1057)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.view.Window.getDefaultFeatures(Window.java:1692)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.view.Window.<init>(Window.java:674)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:303)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:312)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.app.Activity.attach(Activity.java:6946)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2711)
10-21 20:35:07.454 15392 15392 E AndroidRuntime:        ... 9 more
10-21 20:35:07.457  3294  5585 W ActivityManager:   Force finishing activity com.scottyab.safetynet.sample/com.scottyab.sateynet.sample.MainActivity
10-21 20:35:07.463  3294  3416 I ActivityManager: Showing crash dialog for package com.scottyab.safetynet.sample u0
10-21 20:35:07.491  3294 15234 I OpenGLRenderer: Initialized EGL, version 1.4
10-21 20:35:07.491  3294 15234 D OpenGLRenderer: Swap behavior 2
10-21 20:35:07.959  3294  3415 W ActivityManager: Activity pause timeout for ActivityRecord{8920800 u0 com.scottyab.safetynet.sample/com.scottyab.sateynet.sample.MainActivity t6935 f}
10-21 20:35:07.968  3294  3415 I ActivityManager: Killing 14478:com.google.android.gm/u0a91 (adj 906): empty #17
10-21 20:35:07.969  3294  3417 W zygote64: kill(-14478, 9) failed: No such process
10-21 20:35:08.011  3294  3417 W zygote64: kill(-14478, 9) failed: No such process
10-21 20:35:08.011  3294  3417 I zygote64: Successfully killed process cgroup uid 10091 pid 14478 in 42ms
10-21 20:35:08.249  3294  3415 I ActivityManager: Killing 14380:com.google.android.apps.walletnfcrel/u0a95 (adj 906): empty #17
10-21 20:35:08.250  3294  3417 W zygote64: kill(-14380, 9) failed: No such process
10-21 20:35:08.291  3294  3417 W zygote64: kill(-14380, 9) failed: No such process
10-21 20:35:08.291  3294  3417 I zygote64: Successfully killed process cgroup uid 10095 pid 14380 in 41ms
```

**Comment by topjohnwu** [comment]
This commit (9592a699865930a54ccd1ca193ae3acf909111e9) could fix the issue, please open a new issue if the problem persists.

**Comment by HeyItsJono** [comment]
> This commit ([9592a69](https://github.com/topjohnwu/Magisk/commit/9592a699865930a54ccd1ca193ae3acf909111e9)) could fix the issue, please open a new issue if the problem persists.

Thanks for your efforts, unfortunately the issue persists in Magisk 18.0. I've opened a new issue as requested (#876)
