### ISSUE TITLE
fr.bnpp.digitalbanking is evading magiskhide detection in a way that even using the feature for using Magisk under a random app id doesn t works

### ISSUE THREAD

**Issue by ytrezq** [topjohnwu/Magisk#5468]
Basically the same as https://forum.webseodesigners.com/off-topic-f15/solved-mes-comptes-bnp-paribas-erreur-technique-81-t4164.html since the app is maintained by the same team.
![Screenshot_20220215-234819_Hello bank!](https://user-images.githubusercontent.com/3824869/154199406-dd029313-fd54-4d99-a33c-036ccc68ac76.jpg)
More exactly, the app works normally but if you want to wire funds to anyone, you have to enable an app only feature called digital key acting as 2fa for authorizing anything using the app. There are no alternatives (agents won t wire funds for you and it can t be done through their website).

This is the last bank of the country not subject to widespread iban discrimination offering current account allowing to deposit fiat without a mandatory maintenance fee.

I wasn t expecting that rooting the phone would result in me receiving late payments complaint for not be able to add the bank account of my new tenant.

Magisk version code: 24102

**Comment by yujincheng08** [comment]
magiskhide was removed.
