### ISSUE TITLE
Most recent Magisk on Pixel (CalyxOS) doesn't boot properly with Zygisk enabled (how do I disable zygisk with ADB)?

### ISSUE THREAD

**Issue by arolano** [topjohnwu/Magisk#5478]
Device: Pixel 3AXL
Android version: CalyxOS (AOSP 11)
Magisk version name: Most recent canary
Magisk version code: 24102

Boot gets stuck on bootanimation.
Adb is available and root works but I don't know / can't find how to disable Zygisk from command line .
Stopping magisk daemon allows boot to complete but then I can't change options from the app

**Comment by arolano** [comment]
And no, five reboots don't solve it - apparently zygisk "thinks" it started successfully

**Comment by yujincheng08** [comment]
magisk --sqlite 'update settings set value=1 where [key]="zygisk"'
