### ISSUE TITLE
when zygisk enabled, execute su will report "applet not found"

### ISSUE THREAD

**Issue by ychuang1029** [topjohnwu/Magisk#5483]
Device: vivo x30
Android version: 7.1.2
Magisk version name: 24102
Magisk version code: 24102

connect.cpp
![image](https://user-images.githubusercontent.com/16041820/154961814-da3016d2-73b9-4881-8f17-10955c0e27b7.png)

applets.cpp
![image](https://user-images.githubusercontent.com/16041820/154961890-0a6145a7-d574-419c-9f91-29f5523b161a.png)

argv[0] = /proc/self/fd/%d
I think basename will not match any applets.

**Comment by canyie** [comment]
Can you confirm? /proc/self/fd/<app_process_64> should be the fd refers the original app_process

**Comment by ychuang1029** [comment]
the fd refers the right file, the problem is argv[0] will always be /proc/self/fd/xxx, linux kernel won't modify it.
So main will read argv[0]=/proc/self/fd/xxx, it do not know to execute app_process_main or magisk_main or call which applet.

**Comment by ychuang1029** [comment]
The simple way to fix it, execve filename=/proc/self/fd/xxx, but argv[0]=/system/bin/app_process

**Comment by yujincheng08** [comment]
that file refers to the original app_process. not magisk's binary.
