### ISSUE TITLE
open fifo file without O_NONBLOCK may stuck forever

### ISSUE THREAD

**Issue by ychuang1029** [topjohnwu/Magisk#5484]
Device: vivo x30
Android version: 7.1.2
Magisk version name: 24102
Magisk version code: 24102

connect.cpp
![image](https://user-images.githubusercontent.com/16041820/154962297-302f7641-bb1c-4860-8f51-72816b6eda26.png)

open may never return when missing O_NONBLOCK.

**Comment by yujincheng08** [comment]
True.
> O_NONBLOCK

    When opening a FIFO with O_RDONLY or O_WRONLY set: If O_NONBLOCK is
    set:

        An open() for reading only will return without delay. An open()
        for writing only will return an error if no process currently
        has the file open for reading.

    If O_NONBLOCK is clear:

        An open() for reading only will block the calling thread until a
        thread opens the file for writing. An open() for writing only
        will block the calling thread until a thread opens the file for
        reading.
