### ISSUE TITLE
DSU support

### ISSUE THREAD

**Issue by TheArtyomMDev** [topjohnwu/Magisk#5488]
Device: Redmi Note 10 Pro
Android version: 11
Magisk version name: 24102
Magisk version code: 24102

Since android 10 there was a DSU feature, when you can install second GSI rom. It's possible to choose system.img and vendor.img for second rom but not boot.img.
Right now DSU doesn't support installing different boot.img so if you install second rom with DSU then a boot from original rom will be used.
I have my boot patched with Magisk so Magisk is working in original rom but not on DSU (Magisk Manager shows Magisk isn't installed). Could you please make Magisk working on DSU rom?

**Comment by canyie** [comment]
#5146

**Comment by yujincheng08** [comment]
#5146 may support DSU. However, according to Jhon, DSU is only for tests, and Magisk won't make any special workaround to support it. So let's hope #5146 works.

**Comment by TheArtyomMDev** [comment]
So I need to build Magisk from your commit to have DSU support?

**Comment by Tuoivanh** [comment]
Bonjour ,

Nous venons de télécharger surr votre Website  et installer Magisk . Quand nous lançons  module est grisé comme image sur le lien en bas 

https://transfert.free.fr/XVBVIWZ

Merci de nous aider puis passez une excellente journée

Ctd
