### ISSUE TITLE
How to disabled the phh's superuser?

### ISSUE THREAD

**Issue by SakuraSa233** [topjohnwu/Magisk#55]
Because phh's superuser can't be detected by some apps (like Tasker)
So,I want to find a way to disabled the phh's superuser and go to use SuperSU.
By the way,is there any module that can install SuperSU.
Thanks/谢谢/ありがとうございます

**Comment by c727** [comment]
Installation Instructions

https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445

**Comment by SakuraSa233** [comment]
Is there a module that can installl SuperSU directly?That is easier to do.

**Comment by c727** [comment]
SuperSU has to be installed BEFORE Magisk

**Comment by Didgeridoohan** [comment]
This is not an issue for GitHub. Please close...
