### ISSUE TITLE
New installed app's data directory (and content) permission is set to 0777 when Zygisk is enabled

### ISSUE THREAD

**Issue by ryenyuku** [topjohnwu/Magisk#5502]
Device: Infinix X692 (GSI)
Android version: 11 (May happen on other version too)
Magisk version name: 1a1b346c
Magisk version code: 24102

![Screenshot_20211228-133905_Termux](https://user-images.githubusercontent.com/59136093/156148201-2ff1138e-8c72-4c85-b51d-d1cd5046c9f2.png)
This **ONLY** happens when Zygisk is enabled, otherwise it's set to 0770

**Comment by topjohnwu** [comment]
Fixed in d021bca6efa78a90d5e5ce101e43985b9b8973b7
