### ISSUE TITLE
MIUI doesn't allow Magisk to install apk

### ISSUE THREAD

**Issue by pndwal** [topjohnwu/Magisk#5503]
Device: Xiaomi Redmi Note 8T
Android version: 10
Magisk version name: Canary 9968af07
Magisk version code: 24103

'Hide the Magisk app' function fails for me with never-ending 'Hiding the Magisk app' message.

This occurs with or without internet access.

[magisk_log_2022-03-02T16:15:04.log](https://github.com/topjohnwu/Magisk/files/8166785/magisk_log_2022-03-02T16.15.04.log)

**Comment by kkq22** [comment]
Device: Xiaomi 9
Android version: 11
Magisk version name: Canary https://github.com/topjohnwu/Magisk/commit/9968af0785bbee3d806668afdc6f47bf9942a520
Magisk version code: 24103
'Hide the Magisk app' function fails for me too ！！！

**Comment by cjohnson46** [comment]
Not sure if this is the feature you're talking about, but I found this.

From the documentation:

"The new build marks the final retirement of MagiskHide. This is not something unexpected, though, as we have already [seen the removal of MagiskHide](https://www.xda-developers.com/magisk-canary-release-android-12-support/) on the Canary channel. Magisk v24.0 doesn’t come with any kind of root hiding feature out of the box, but you can still use third-party modules to circumvent root detection and [pass SafetyNet](https://www.xda-developers.com/how-to-pass-safetynet-android/)."

**Comment by pndwal** [comment]
> Not sure if this is the feature you're talking about, but I found this.
> 
> From the documentation:
> 
> "The new build marks the final retirement of MagiskHide. This is not something unexpected, though, as we have already [seen the removal of MagiskHide](https://www.xda-developers.com/magisk-canary-release-android-12-support/) on the Canary channel. Magisk v24.0 doesn’t come with any kind of root hiding feature out of the box, but you can still use third-party modules to circumvent root detection and [pass SafetyNet](https://www.xda-developers.com/how-to-pass-safetynet-android/)."

No; please don't confuse issues...

This is app hiding, not root hiding and not part of old MagiskHide... It was not removed, and it is working on many devices...

**Comment by pndwal** [comment]
> This is MIUI's bug.

OK... But also some kind of regression? ... It always worked before (incl. 24102) ... Please say whats changed (I haven't updated OS lately)...

**Comment by pndwal** [comment]
I now have 24201; Hide app still fails, but now it finishes with 'failed' notice...

Tried Logcat Extreme app... Will these do?:

[Log_2022-03-02_22-56-50.txt](https://github.com/topjohnwu/Magisk/files/8169461/Log_2022-03-02_22-56-50.txt)
- Magisk-specofic log
[Log_2022-03-02_23-03-31.txt](https://github.com/topjohnwu/Magisk/files/8169462/Log_2022-03-02_23-03-31.txt)
- Complete log...

**Comment by shohoku521** [comment]
Magisk app 24103 hiding upgrade to 24201

> I now have 24201; Hide app still fails, but now it finishes with 'failed' notice...
> 
> Tried Logcat Extreme app... Will these do?:
> 
> [Log_2022-03-02_22-56-50.txt](https://github.com/topjohnwu/Magisk/files/8169461/Log_2022-03-02_22-56-50.txt) Magisk-specofic log
> 
> [Log_2022-03-02_23-03-31.txt](https://github.com/topjohnwu/Magisk/files/8169462/Log_2022-03-02_23-03-31.txt) Complete log...

Magisk app 24103 hiding upgrade to 24201

**Comment by pndwal** [comment]
Thanks for your efforts ladies. 🙂

Has something changed with v26 stub handling to cause this? Can something be changed / reverted in Magisk to accommodate MIUI?

**Comment by vvb2060** [comment]
disable miui optimization

**Comment by pndwal** [comment]
> disable miui optimization

Strange; this doesn't appear in my developer options...🤔

**Comment by pndwal** [comment]
> disable miui optimization

Many thanks for this workaround!

As mentioned, 'Turn on MIUI optimisation' does not show on opening Developer options for my device w/ MIUI 12.0.4. However, I was able to see the option as follows:

By scrolling to the option 'Reset to default values' under AUTO-FILL, then clicking this 4 times, 'Turn on MIUI optimisation' is displayed as the second-last option. Nb. This process is required to display the option every time Developer options is opened.

So I have now been able to disable 'Turn on MIUI optimisation', select / complete 'Hide the Magisk app' process without issue, then go back and re-enable 'Turn on MIUI optimisation'. 👍 🎉

... It would still be nice to see a workaround for MIUI integrated in Magisk, perhaps even reverting whatever change in stub or Hide the Magisk app process caused the regression in 24103, 24201...

Anyway, just having a working method (if convoluted) is much appreciated! PW

**Comment by VD171** [comment]
> disable miui optimization

Hi, vvb2060. First, Thank you very much for your wonderful contribution.
May I ask you something?
Do you suggest to keep disabled MIUI OPTIMIZATION  as default ?
Or just if there is any problem with MIUI ? 
Regards
