### ISSUE TITLE
Log menu freezes app

### ISSUE THREAD

**Issue by aryankaran** [topjohnwu/Magisk#5505]
Device: Xiaomi Redmi 7 (onclite)
Android version:10
Magisk version name: 9968af07
Magisk version code: 24103
Rom: MIUI 12.5.3 CN (stock rom)

The log menu seems to be bugged up ...

As soon as I try to open the open logs menu the app totally freezes up and i have to fore stop app and re open the app ...

See video

https://user-images.githubusercontent.com/89232299/156200620-098d63c2-c449-4d19-8efd-ecbc62e58d88.mp4

**Comment by osm0sis** [comment]
logcat is needed

**Comment by yujincheng08** [comment]
@osm0sis This issue may be reproduced by a large log. Textview is actually extremely slow when rendering a large amount of text.

**Comment by vvb2060** [comment]
I plan to refactor with RecyclerView , but not in v24.3.

**Comment by canyie** [comment]
Maybe [this library](https://github.com/Rosemoe/Sora-Editor) is a better choice? Tested showing a 10M+ txt file and all works good.
