### ISSUE TITLE
Multiple modules adding the same subdirectory will fail to be added to the tree

### ISSUE THREAD

**Issue by osm0sis** [topjohnwu/Magisk#5511]
Device: OnePlus 8T (kebab)
Android version: 11
Magisk version name: 7cfce9ff
Magisk version code: 24201

Discovered an interesting bug back in August which I reported internally and @topjohnwu said might be "an algorithm issue", but I presume it's since been forgotten so wanted to open it up to everyone to take a look since development has been much more collaborative lately (🎉)!

Basically, if 2+ modules have changes in the same newly added subdirectory (i.e. the subdirectory did not exist before either module) only the first loaded module's changes (alphabetical at boot) to that new subdirectory get added.

My example of this can be seen with /system/usr/libexec in the Git and SSH modules attached, but I have confirmed with @Didgeridoohan it can happen anywhere, and so is a decently large flaw in the Magisk skeleton tree creation process.

[magisk_log_2022-03-02T09_14_07.log](https://github.com/topjohnwu/Magisk/files/8169787/magisk_log_2022-03-02T09_14_07.log)

[Git_for_Android-2.23.0(2230).zip](https://github.com/topjohnwu/Magisk/files/8169526/Git_for_Android-2.23.0.2230.zip)
[SSH_for_Magisk-1.0(100)-osmod.zip](https://github.com/topjohnwu/Magisk/files/8169547/SSH_for_Magisk-1.0.100.-osmod.zip)

**Comment by HuskyDG** [comment]
That's true.
I make a test:
`/data/adb/modules/module_1/system/bin/new/file_1`
`/data/adb/modules/module_2/system/bin/new/file_2`

After reboot, i only see `file_1` in `/system/bin/new` because magisk directly mount `/data/adb/modules/module_1/system/bin/new`

**Comment by yujincheng08** [comment]
Try #5602

**Comment by yujincheng08** [comment]
Submitted another fix in #5618. Please try again.
