### ISSUE TITLE
Nexus 5 unable to boot since the commit e7c82f2

### ISSUE THREAD

**Issue by sn-o-w** [topjohnwu/Magisk#5516]
Device: Google Nexus 5
Android version: Android 10
Magisk version name: 7cfce9ff
Magisk version code: 24201

---

For some reason, Nexus 5 is unable to boot due to the following commit https://github.com/topjohnwu/Magisk/commit/e7c82f20e3d7d7b47221b454508d07aefc14e7c0. The device is simply stuck at the Google logo phase, it doesn't even get to LineageOS boot animation. So I dunno how can I collect logs at this early phase.

Creating Magisk build against the master branch and reverting https://github.com/topjohnwu/Magisk/commit/e7c82f20e3d7d7b47221b454508d07aefc14e7c0 seems to work, I get a working Magisk build on my Nexus 5, I get past the Google logo phase and the device will successfully boot up.

By Google logo phase I mean this:

![IMG_20220302_165357](https://user-images.githubusercontent.com/2406819/156390390-57aca36f-b8d7-483b-860c-25af48524795.jpg)

^ It's just stuck at this phase with the commit https://github.com/topjohnwu/Magisk/commit/e7c82f20e3d7d7b47221b454508d07aefc14e7c0. So I dunno what other information I can provide to you.

**Comment by sn-o-w** [comment]
> log?

How can I collect logs at this phase? 🤔

The device is not detected by the computer, so I'm not sure what to do.

**Comment by sn-o-w** [comment]
[2022-03-02_181645_dmesg.txt](https://github.com/topjohnwu/Magisk/files/8171141/2022-03-02_181645_dmesg.txt)

Is this useful? 🤔

I extracted it via TWRP, but I'm not sure if contains relevant information.

**Comment by WikiBayer** [comment]
Self problem with the Poco x3 pro (vayu)

**Comment by xx979xx** [comment]
I have the same problem with Samsung S8 (SM-G950F)
canary 24.1 721d8d33(24101) is working fine

**Comment by tplank** [comment]
Can confirm this issue with a **ZUK Z2**.
Stuck at initial boot logo before lineageOS boot animation shows up with 24.**2**
Flashing back to 24.**1** solves the problem.

**Comment by gecelerde** [comment]
Same issue with Xperia Z2 Lineage OS 18.1. Tried without having TWRP installed (as instructions suggested for Android 11) and with a clean Magisk install but the device is still stuck at the logo. 24.1 is working without an issue.

**Comment by faizauthar12** [comment]
@tplank which kernel version you're using? 3.18 or 4.4?

**Comment by vvb2060** [comment]
https://lwn.net/Articles/800509/

**Comment by tplank** [comment]
> @tplank which kernel version you're using? 3.18 or 4.4?

It's 4.4.
![Screenshot_20220303-083915_Einstellungen](https://user-images.githubusercontent.com/2746238/156518965-fb997617-7c44-4189-91c5-f50f0fc582f0.png)

**Comment by tramp20** [comment]
I have the same problem on my Sony Z1c LOS 18.1 since Magisk 24103.
Updated either with Magisk app (direct) or with flashing the original boot.img with TWRP.

Kernel 3.4.113

**Comment by pagkly** [comment]
@tramp20 
@sn-o-w 
@topjohnwu 
Got similar problem but my device ended up successfully booting just verryyy slowlyy after more than 1 minute.

Samsung Galaxy Note 3 (hlte)
Kernel 3.4.113
Interestingly it has similar chipset Snapdragon 800 and kernel to Nexus 5 and Z1c.
