### ISSUE TITLE
`readlink -f` from busybox is broken for kernel version < 3.6

### ISSUE THREAD

**Issue by honk0504** [topjohnwu/Magisk#5530]
Device: Nexus 7 (2013) WiFi (flo)
Android version: Android 11 (lineage 18.1 - lineage-18.1-20220228-nightly-flox-signed)
Magisk version name: 7cfce9f
Magisk version code: 24201

I patched the boot.img and got an magisk patched boot file. I booted into TWRP (twrp-3.6.0_9-0-flo) and installed the patched boot image. No errors. After booting the device freeze. I have to re-install org boot.img to make it work again.
I took magisk.apk and renamed it to magisk.zip. I trying to install magisk.zip with TWRP.
ERROR!

Magisk 24.2 Installer

! Cannot mount /system
'- Unmount partition
Prozess Updater endet mit FEHLER: 1
Fehler beim Installieren von ZIP '/sdcard/Download/magisk-v24.2.zip'
Partitions-Informationen werden aktualisiert...
... Fertig

**Comment by osm0sis** [comment]
More than likely this: #5516

It's already fixed for the next Canary and point release.

**Comment by osm0sis** [comment]
Oh wait, that recovery install issue is new..

**Comment by disc0nct** [comment]
Same error!, I had to re-flash Magisk v24.1 back to make it work again.

**Comment by Displax** [comment]
Duplicate https://github.com/topjohnwu/Magisk/issues/5439
But nobody seems to want fix it...

**Comment by osm0sis** [comment]
It used to work though, so still should

**Comment by schneemaier** [comment]
I have the same issue

**Comment by StickyDigit** [comment]
Same here on Flox with LOS 18.1.

Magisk 24.2 resulted in stuck boot. Reinstalled 24.1 via TWRP. All ok.

Magisk 24.3 updated from app and worked, but did not survive routine LOS firmware update via TWRP.

24.3 wouldn't re-install from TWRP (couldn't find /system after umount). Had to reinstall 24.1 with TWRP, then update to 24.3 from the app.

**Comment by canyie** [comment]
Reverting busybox binary can fix this issue. Further investigation tells the busybox's `readlink` command with `-f ` option doesn't work for now.
![Screenshot_2022-03-18-22-18-57-415_bin mt plus](https://user-images.githubusercontent.com/31466456/159020842-55dadb76-61a8-4796-9d08-86b2cd2fa3ad.jpg)
![IMG_20220318_222413_327](https://user-images.githubusercontent.com/31466456/159020863-9669b7d0-bf2d-4a43-8cd1-f95a3de74662.jpg)
I guess the upgrade of ndk triggers some bugs in busybox.

**Comment by StickyDigit** [comment]
Following, I adb'd into twrp (3.5.2_9.0)

```
~ # busybox  | grep "BusyBox v"
BusyBox v1.22.1 bionic (2021-04-06 01:17 +0000) multi-call binary.

~ # echo ":$( readlink /system ):"
:/system_root/system:

~ # echo ":$( readlink -f /system ):"
::
```
"readlink -f" fails as you describe. Returns empty. FWIW, readlink -f /system || echo bad, echoes bad.
TWRP has not changed, and AFAIK the busybox is in/from that.
The same "readlink -f" is in util_functions.sh find_block() on 24.1, which somehow installs ok on TWRP.

**Comment by osm0sis** [comment]
Magisk's busybox (in its apk/zip) is where the regression lies, TWRP's busybox has no effect on it.

**Comment by yujincheng08** [comment]
This is because of https://github.com/android/ndk/issues/1260

**Comment by osm0sis** [comment]
That issue sounds pretty old, though, and might not directly affect a static busybox? Also interesting how it worked fine in Magisk 24.1.

**Comment by yujincheng08** [comment]
@osm0sis I have fixed it. But I need you to make the change to busybox kitchen. Could you help me?

**Comment by osm0sis** [comment]
Nice! Same as here on Magisk repo we don't merge without John, but I can review PRs, etc.

**Comment by yujincheng08** [comment]
(off topic: could you review #5618?

**Comment by yujincheng08** [comment]
Try artifacts of #5620.

**Comment by osm0sis** [comment]
> (off topic: could you review #5618?

Running it already as we speak, and taking a look. 👍

**Comment by Displax** [comment]
Can confirm this patch fix installation from TWRP. But not fix https://github.com/topjohnwu/Magisk/issues/5555, magisk still half-workable. su works, but other stuff broken (logs, normal setup, additional setup, etc.).
Log from https://github.com/topjohnwu/Magisk/pull/5620 : [log.txt](https://github.com/topjohnwu/Magisk/files/8309995/log.txt)

**Comment by osm0sis** [comment]
> Try artifacts of #5620.

Can also confirm this fixes flashing in flox TWRP. The PR CI build and 24303 both have broken root, but I can also confirm that's fixed upstream in the latest CI. 👍

**Comment by osm0sis** [comment]
Follow-up: Not a full test, but I was able to test out addon.d by copying the arm busybox from your PR CI build over HEAD CI's /data/adb/magisk/busybox and all worked perfectly. 🎉

**Comment by yujincheng08** [comment]
Fixed here: b1faa5eed4f5c52cc60a90ca74744a77fde07575

**Comment by debian-user-france1** [comment]
Still no new release.. How can I get this patch?

**Comment by osm0sis** [comment]
Wait patiently or run the latest CI build from GitHub Actions.

**Comment by tfft** [comment]
Based on the number of people that have noted this issue/problem/bug and have downgraded, it might make sense to spin-off a 24.3.1 release simply to address this one problem allowing ample time for 24.4 to run its course.

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/blob/e327565434446f0602dae24bb0887a5a04bf5a0d/native/src/base/files.rs#L81-L91
