### ISSUE TITLE
magisk 17 does not show root prompt 

### ISSUE THREAD

**Issue by cheetoslover** [topjohnwu/Magisk#554]
im using nougat 7.1.2 and after installing the latest magisk i can't grant any of my apps root permissions the prompt does not show at all and i have to install previously version v16 with the latest apk and it works fine im using infinix HOT 2
and keep ur awesome work here :)

Best regards,

**Comment by topjohnwu** [comment]
No info provided, close issue

**Comment by cheetoslover** [comment]
09-05 17:31:18.403 I/ActivityManager(547): Process com.topjohnwu.magisk (pid 6315) has died
09-05 17:36:32.313 I/ActivityManager(547): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.SplashActivity bnds=[180,248][360,430] (has extras)} from uid 10101 on display 0
09-05 17:36:32.357 I/ActivityManager(547): Start proc 8341:com.topjohnwu.magisk/u0a75 for activity com.topjohnwu.magisk/.SplashActivity
09-05 17:36:32.457 W/System  (8341): ClassLoader referenced unknown path: /data/app/com.topjohnwu.magisk-1/lib/arm
09-05 17:36:33.575 I/ActivityManager(547): START u0 {cmp=com.topjohnwu.magisk/.MainActivity (has extras)} from uid 10075 on display 0
09-05 17:37:55.354 E/Magisk  (8546): select failed with 2: No such file or directory
09-05 17:38:16.664 E/Magisk  (8605): select failed with 2: No such file or directory
09-05 17:38:58.325 I/ActivityManager(547): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.SplashActivity bnds=[180,248][360,430] (has extras)} from uid 10101 on display 0
09-05 17:38:58.805 I/ActivityManager(547): Displayed com.topjohnwu.magisk/.MainActivity: +460ms
09-05 17:39:02.580 I/ActivityManager(547): Killing 8341:com.topjohnwu.magisk/u0a75 (adj 900): remove task
09-05 17:39:11.619 E/Magisk  (8697): select failed with 2: No such file or directory

**Comment by cheetoslover** [comment]
when im on magisk 16 it works fine but when i upgrade to 17.1 i cant get any grant prompet screen but the old apps is working fine when i add them at v 16 i tried different apps and it all the same i cant give them root access
