### ISSUE TITLE
sqlite3_exec failed by leave errmsg unchanged cause sqlite3_free crash

### ISSUE THREAD

**Issue by ychuang1029** [topjohnwu/Magisk#5542]
Device: vivo x30
Android version: 10
Magisk version name: 24.2
Magisk version code: 24201

![image](https://user-images.githubusercontent.com/16041820/156880618-3ea587e3-ea46-4e02-b554-401ec345a0e7.png)

![image](https://user-images.githubusercontent.com/16041820/156880626-fe7f277c-1eed-42a7-9371-80dc5a426173.png)

char *err is not initialized to nullptr.
sometimes when database file is corrupted, sqlite3_exec will fail but leave err unchanged.
so err will be some random value but not nullptr, then sqlite3_free will crash!!!
solution:
1. check return value for actual success or fail.
2. set err default to nullptr.

**Comment by yujincheng08** [comment]
sqlite3_free a nullptr is safe.

**Comment by ychuang1029** [comment]
the problem is errmsg may be a random value, but not nullptr

**Comment by canyie** [comment]
> If the 5th parameter to sqlite3_exec() is not NULL then any error message is written into memory obtained from [sqlite3_malloc()](https://www.sqlite.org/c3ref/free.html) and passed back through the 5th parameter. To avoid memory leaks, the application should invoke [sqlite3_free()](https://www.sqlite.org/c3ref/free.html) on error message strings returned through the 5th parameter of sqlite3_exec() after the error message string is no longer needed. If the 5th parameter to sqlite3_exec() is not NULL and no errors occur, then sqlite3_exec() sets the pointer in its 5th parameter to NULL before returning.

If no error occurs, the `err` will be nullptr; if any error occurs, the `err` will be error message, which will be a valid string until call `sqlite3_free`.

**Comment by ychuang1029** [comment]
![image](https://user-images.githubusercontent.com/16041820/156882725-aa5bd821-2cde-434c-8075-67316134a7b6.png)
this line return error, but do not change errmsg.
