### ISSUE TITLE
"No Command" After uninstalling Magisk 17 on Google Pixel 2XL causing soft brick.

### ISSUE THREAD

**Issue by derwentx** [topjohnwu/Magisk#555]
Hi there,
I'm a huge fan of Magisk, and how comparitively easy it's been to root my phone so thanks for the awesome work!

I'm posting this issue not because I expect you to be able to fix it from the minimal information I've been able to give you, but in the hope that other people who experience the same problem will be able to save themself some time.

I had Magisk 17.1 installed on Android 8.1 and I uninstalled it in order to upgrade to Oreo. When I uninstalled magisk, it rebooted and I was stuck in the "no command" screen, even after rebooting, it seems like the system boot had stopped working.

If like me your intention was to upgrade android, the way out of this is to boot into the "no command" screen, press "power + volume up" to get to the menu, then use the volume buttons to select "Install update from ADB" and sideload an OTA update https://developers.google.com/android/ota 

Would it be worth me updating the wiki with this information?

Thanks.

**Comment by topjohnwu** [comment]
This means that the original boot image is not backed up properly, thus the uninstallation is not 100% complete. The symptom you're experiencing is that the kernel is patched to always boot from ramdisk, which is where the stock recovery exists. That's why your device will always boot to recovery no matter what you do.

**Comment by arbaes** [comment]
Don't want to necrobump, but google led me here, so if it can help anyone here's the fix:

1. Find the correct stock boot.img according to your stock rom version.
2. Boot your phone in fastboot mode
3. `$ fastboot flash boot stock_boot.img`
4. `fastboot reboot`

**Comment by xchehub** [comment]
I made same mistake for my pixel2.
How can I fins the stock_book.img?
Where I can download it?
Does the factory image include the stock_boot.img?

> Don't want to necrobump, but google led me here, so if it can help anyone here's the fix:
> 
> 1. Find the correct stock boot.img according to your stock rom version.
> 2. Boot your phone in fastboot mode and connect it to a PC with fastboot installed
> 3. `$ fastboot flash boot stock_boot.img`
> 4. `fastboot reboot`
