### ISSUE TITLE
stuck boot logo latest canary and beta.

### ISSUE THREAD

**Issue by gigabyte-1000** [topjohnwu/Magisk#5554]
Device: Xiaomi Redmi Note 3
Android version: 11
Magisk version name: v24.2
Magisk version code: 24201

Stuck on mi boot logo after flashing the latest canary build and also beta build, I should mention the last Canary build I tried was 1a1b346c which worked & booted fine, attached boot.img and patched boot.
[boot_images.zip](https://github.com/topjohnwu/Magisk/files/8192232/boot_images.zip)

**Comment by canyie** [comment]
Please retry with the latest CI build, this may already be fixed. https://github.com/topjohnwu/Magisk/actions/runs/1932106012

**Comment by pagkly** [comment]
@gigabyte-1000 might want to check out #5516

**Comment by gigabyte-1000** [comment]
> Please retry with the latest CI build, this may already be fixed. https://github.com/topjohnwu/Magisk/actions/runs/1932106012

Thanks, you are correct, this CI build fixes it.
