### ISSUE TITLE
magisk hide问题

### ISSUE THREAD

**Issue by armrf** [topjohnwu/Magisk#556]
使用hide直接关机，开机后无限进入锁屏界面
17.1    5.9.1  安卓6.0 oppo
0903最新的（哦，天鬼知道我昨天干了什么，刷了十多次抓取的还是丢失了。）
[magisk_log_20180903_094130.log](https://github.com/topjohnwu/Magisk/files/2343994/magisk_log_20180903_094130.log)
[magisk_log_20180903_094029.log](https://github.com/topjohnwu/Magisk/files/2344004/magisk_log_20180903_094029.log)
[magisk_log_20180901_174514.log](https://github.com/topjohnwu/Magisk/files/2344005/magisk_log_20180901_174514.log)
[magisk_install_log_20180902_214654.log](https://github.com/topjohnwu/Magisk/files/2344007/magisk_install_log_20180902_214654.log)

**Comment by topjohnwu** [comment]
This commit (9592a699865930a54ccd1ca193ae3acf909111e9) could fix the issue, please open a new issue if the problem persists.
