### ISSUE TITLE
[APP] Can't hide or restore app because of UI overlap

### ISSUE THREAD

**Issue by Displax** [topjohnwu/Magisk#5574]
Device: Google Pixel 4a (5G)
Android version: 12L (12.1)
Magisk version name: 7cfce9ff
Magisk version code: 24201

Installation app query window from system is under of the Magisk restoration/installation wait window.

<details>

![Screenshot_20220309-165500 1](https://user-images.githubusercontent.com/16293419/157469322-16657829-705c-4a36-b987-854240d0437e.png)

![Screenshot_20220309-165753 1](https://user-images.githubusercontent.com/16293419/157469368-c25b593f-4ea8-41f2-a52a-e026df09364c.png)

</details>

**Comment by Displax** [comment]
Partially fixed by https://github.com/topjohnwu/Magisk/commit/237794b05c1c7c4f932e0bf9eb7472782b435984
But can be still relevant if root install not used.

**Comment by vvb2060** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/26996262/170831217-52eaef45-3d7c-4bb8-b0d9-bd94c565c4d0.png)

**Comment by vvb2060** [comment]
I think it's a system problem.
