### ISSUE TITLE
Samsung S22+  not possible to mount    #mount -orw,remount /   '/dev/block/dm-0' is read-only

### ISSUE THREAD

**Issue by mauroa85** [topjohnwu/Magisk#5578]
Device: SM-S906B/DS
Android version:12 (build S906BXXU1AVA7)
Magisk version name: https://github.com/topjohnwu/Magisk/commit/2c092ffdef46512e94dd1b9c974e4b280e1da7fa
Magisk version code: 24301

Hello after i patched The Magisk files with version 26 and patching again with 27 I had the same result

#mount -orw,remount /
'/dev/block/dm-0' is read-only

Here is the log file
[magisk_log_2022-03-10T11_37_27.log](https://github.com/topjohnwu/Magisk/files/8223160/magisk_log_2022-03-10T11_37_27.log)

regarding any other information that will be needed to fix this situation or other data please feel free to ask with the commands and I will reply with any info requested.

**Comment by topjohnwu** [comment]
That is expected due to the new logical partitioning scheme. Nothing Magisk can do here

**Comment by mauroa85** [comment]
Thank you for your quick reply,
 this will be possible in a near future?
