### ISSUE TITLE
还是Magiak更新通道问题

### ISSUE THREAD

**Issue by funnypro** [topjohnwu/Magisk#558]
也许是因为我没有在 https://github.com/topjohnwu/Magisk/issues/446 把这个问题描述完的原因吧……  
~~其实那时候的问题是选中自定义通道，不管有没有确认，它都会把更新通道设置为自定义~~当然，这个似乎不重要了  

目前来说它的问题仍然存在，例如当然不输入内容并取消时通道确实没有设置为那个不能用的自定义  
但是，在不切换到其他页面再切换回去时，它的选项还是在自定义那里  

还有一个情况，就是什么都不输入并点击好
~~（我个人认为那个按钮的文本应该是‘确认’，而不是‘好）’~~
之后，似乎MagiskManager并没有验证这个更新通道就直接使用了  

我个人认为应该在设置自定义更新通道时应该对自定义服务器索要什么东西
~~由于我并没有这方面的经验，我也不知道是什么。或许直接索要Magisk的版本信息？~~
以证明它是Magisk更新版本用的服务器

**Comment by topjohnwu** [comment]
搞成這樣太複雜了，不會想要實現.....
