### ISSUE TITLE
Unisoc sc9863a "Magisk patched (Flag 3) boot img not flashing" 

### ISSUE THREAD

**Issue by hasanbd80** [topjohnwu/Magisk#5585]
### Stock Boot.img is flashing on fastboot mode but magisk patched.img is not flashing !

**Difference between these two is
Stock boot file---- Flags: 0
Magisk patched file ---- Flags: 3 !
.
.**

(1) Stock img information screenshot
![image](https://user-images.githubusercontent.com/101275948/157902119-0d18f40b-d4d8-4714-bfa2-99337b39b740.png)

(2) Magisk patched img information screenshot
![image](https://user-images.githubusercontent.com/101275948/157902187-ee0611ac-ce49-4df8-8df5-2336bfbed509.png)

.
.
Device: i97
Android version: 9
Magisk version name: 2c092ffd
Magisk version code: 24301
.
.
**Log**:

- Device platform: arm64-v8a
- Installing: 2c092ffd (24301)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [1]
KERNEL_SZ       [17299864]
RAMDISK_SZ      [0]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2019-07]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyS1,115200n8 buildvariant=user]
CHECKSUM        [3df2cbce881be51f50a8d7576277da9a1d3934e4000000000000000000000000]
KERNEL_FMT      [raw]
VBMETA
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Patch @ 00C89BE6 [736B69705F696E697472616D667300] -> [77616E745F696E697472616D667300]
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [1]
KERNEL_SZ       [17299864]
RAMDISK_SZ      [0]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2019-07]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyS1,115200n8 buildvariant=user]
CHECKSUM        [3df2cbce881be51f50a8d7576277da9a1d3934e4000000000000000000000000]
KERNEL_FMT      [raw]
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [1]
KERNEL_SZ       [17299864]
RAMDISK_SZ      [832232]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2019-07]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyS1,115200n8 buildvariant=user]
CHECKSUM        [2d78228c86a4d04da16200accbcb491ee7d53f9e000000000000000000000000]

****************************
 Output file is written to 
 /storage/emulated/0/Download/magisk_patched-24301_O360Z.img 
****************************
cp: can't preserve ownership of 'busybox': Operation not permitted
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
- All done!

**Comment by hasanbd80** [comment]
**Stock .img files:**
![image](https://user-images.githubusercontent.com/101275948/158004341-2af2a584-b5fb-4a35-b829-7eb7d9d7be94.png)

### link:
https://drive.google.com/drive/folders/1Dil75j34gMjo3Q_CsQwVT4P8kB3bBzBr?usp=sharing

**Comment by yujincheng08** [comment]
There's now an option to set this flag in Magisk.

**Comment by hasanbd80** [comment]
> There's now an option to set this flag in Magisk.
> 
> FYI: [2285706](https://github.com/topjohnwu/Magisk/commit/228570640eb42333d42b79d17e6301fc0513adb6), [f4ed627](https://github.com/topjohnwu/Magisk/commit/f4ed6274a4c8294cc4804385bc29957f0a73934d)

![image](https://user-images.githubusercontent.com/101275948/158010935-fabaad6a-b984-4a9b-8c86-4acf598af11d.png)

2285706,f4ed627 patched with 23.0 till Flag 3

**Comment by yujincheng08** [comment]
23.0 is no longer maintained.

**Comment by hasanbd80** [comment]
> 23.0 is no longer maintained.

I can't root my phone for flag 3 only.
I have tried many times with custom flags 3,2,0 vbmeta and
I have also modified the Magisk patched flag 3 img to  flag 0 Magisk img .
but the problem is I don't have  RSA.pem (official)
1) Is there any way to patch boot/recovery file into Magisk with flag 0 ?
2) When this issue will be updated?

**Comment by yujincheng08** [comment]
1. Magisk 24+ has an option to set this flag to 0 or 3
2. Already

**Comment by hasanbd80** [comment]
> 1. Magisk 24+ has an option to set this flag to 0 or 3
> 
>     2. Already

I changed the flag 3 to 0 in .cpp file
but i don't know how to build  the app & I am getting error 
i don't understand this line 
 Windows: Add `C:\Path\To\Android Studio\jre\bin` to environment variable `PATH`
![image](https://user-images.githubusercontent.com/101275948/158061119-7501aebc-c723-4150-81c0-081020a6873e.png)

**Comment by yujincheng08** [comment]
You don't need to compile Magisk. Just use the official build.

**Comment by hasanbd80** [comment]
> You don't need to compile Magisk. Just use the official build.

Ok 
which version? can you give me the link please
I have already checked magisk v24.3 patched img still flag 3 
![image](https://user-images.githubusercontent.com/101275948/158062339-0c21125f-d3e5-4de5-95c9-80dac8c87f0a.png)

**Comment by yujincheng08** [comment]
v24.3

**Comment by hasanbd80** [comment]
> v24.3

Where is the option in magisk app (2.4v)?
 or It automatically detects

**Comment by hasanbd80** [comment]
> v24.3
Ok I got it.
Problem - magisk patched flag 0 boot / recovery not flashing ...
But original stock  boot/recovery is flashing in 1-2 sec 
screenshot 1 (magisk patched img)
![image](https://user-images.githubusercontent.com/101275948/158068442-abea4500-b074-4880-a21a-bb2f4f17fe8f.png)

**Comment by hasanbd80** [comment]
> v24.3

Add a new option that we can flash vbmeta,img in magisk and that new vbmeta will match with patched boot/recovery.img

**Comment by piisamman** [comment]
this is the only way i know and if works for me "
python avbtool add_hash_footer --image xxxx.img --partition_name recovery --partition_size 36700160 --key rsa4096_vbmeta.pem --algorithm SHA256_RSA4096" required private key and avbtool

**Comment by GitxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxHub** [comment]
> ### **Stock .img files:**
> ![image](https://user-images.githubusercontent.com/101275948/158004341-2af2a584-b5fb-4a35-b829-7eb7d9d7be94.png)
> 
> **_Link:_** https://drive.google.com/drive/folders/1Dil75j34gMjo3Q_CsQwVT4P8kB3bBzBr?usp=sharing
> 
> ### Please help me I have been trying to root my phone for 1 year.

me to :( bat no root :((
