### ISSUE TITLE
Duplicate module

### ISSUE THREAD

**Issue by s1204IT** [topjohnwu/Magisk#5586]
The installation log shows that "**- Replace target:**" is executed twice.
```
TAB-A04-BR3:/ # ls -la /data/adb/modules/
total 32
drwxr-xr-x 4 root root 4096 2022-03-12 18:58 .
drwx------ 6 root root 4096 2022-03-12 19:04 ..
drwxr-xr-x 3 root root 4096 2022-03-12 18:57 CPad3-Retail
drwxrwxrwx 2 root root 4096 2022-03-12 18:57 CPad3-Retail
```

Device: TAB-A04-BR3
Android version: 7.0
Magisk version name: 2c092ffd
Magisk version code: 24301

What else do I need to submit?

**Comment by s1204IT** [comment]
Screenshot
![m](https://user-images.githubusercontent.com/52069677/158014252-b230a65e-7f40-40a1-8412-aff96492f558.png)

**Comment by yujincheng08** [comment]
Is it possible to have two files with the same name in the same directory???

**Comment by s1204IT** [comment]
No.
It should be impossible, but for some reason it is duplicated.

**Comment by yujincheng08** [comment]
I think that may be corruption in your filesystem. It may not be relative to Magisk.

**Comment by yujincheng08** [comment]
Could you install https://play.google.com/store/apps/details?id=me.zhanghai.android.files and screenshot `/data/adb/modules`?

**Comment by topjohnwu** [comment]
Either this is a Unicode attack on filenames or the filesystem being broken, nothing to do with Magisk
