### ISSUE TITLE
WARNING: linker: su: unsupported flags DT_FLAGS_1=0x8000001 

### ISSUE THREAD

**Issue by zputnyq** [topjohnwu/Magisk#5589]
Device: Xperia M4 (E2306)
Android version: 6.0.1 (stock)
Magisk version name: 2c092ff
Magisk version code: 24301

Hi all,
I get that WARNING: linker: su unsupported flags DT_FLAGS_1=0x8000001 after typing su on terminal emulator (termone plus v 4.0.0) since canary 24102. May someone has explanation/reason for why that happen.
![Screenshot_20220313-130524](https://user-images.githubusercontent.com/31039796/158047852-14202bb6-111f-4bdc-82fe-95cc69367fc6.png)

**Comment by aguys123** [comment]
Same with my 2013 Moto G on Nougat ROM. Seems like only happens on Nougat and below as I don't have such a problem on Oreo ROM.

**Comment by etmatrix** [comment]
[Here](https://github.com/termux/termux-packages/issues/4894) there is a workaround and I think it will be the unique solution.

**Comment by canyie** [comment]
how about `magisk su`? termux have an unique su command so maybe its su instead of magisk's is being called.

**Comment by Displax** [comment]
> how about `magisk su`? termux have an unique su command so maybe its su instead of magisk's is being called.

Same on Android 5.1.1 (looks likes on all old Android platforms). In my case there is some other warnings:
```
root@grouper:/ # magisk su
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8000001
WARNING: linker: magisk: unused DT entry: type 0x6ffffef5 arg 0x107c
WARNING: linker: magisk: unused DT entry: type 0x6ffffffe arg 0x103c
WARNING: linker: magisk: unused DT entry: type 0x6fffffff arg 0x2
```

**Comment by Felix-Kyun** [comment]
is this issue fixed ?? cause I just installed magisk and I am getting this warning and termux's elf cleaner also doesn't work, its my first time rooting so idk if I messed smth up

**Comment by Displax** [comment]
> is this issue fixed ?? cause I just installed magisk and I am getting this warning and termux's elf cleaner also doesn't work, its my first time rooting so idk if I messed smth up 
> 

Use latest Magisk canary
