### ISSUE TITLE
Samsung zygisk with no early zygote

### ISSUE THREAD

**Issue by jooomoooj** [topjohnwu/Magisk#5592]
Device: Samsung Galaxy J6
Android version: 12
Magisk version name: na
Magisk version code: 24301

I tried canaries and eventually using alpha because im hoping zygisk thing was fixed.. before 24.1 it was working then until implementing invalidating early zygote it doesnt work i checked my init.rc there is no such thing as persist.sys.zygote.early.. so how about ignoring this property for those who do not have so that zygisk would work.

https://github.com/topjohnwu/Magisk/actions/runs/1788464031

**Comment by canyie** [comment]
Please attach `/system/etc/init/init.rc` and `$(magisk --path)/.magisk/rootdir/system/etc/init/init.rc`

**Comment by jooomoooj** [comment]
This was taken from root directory no such thing inside system/etc/init/ 
[init.rc.txt](https://github.com/topjohnwu/Magisk/files/8244685/init.rc.txt)

**Comment by canyie** [comment]
then attach `$(magisk --path)/.magisk/rootdir/init.rc`

**Comment by jooomoooj** [comment]
> then attach `$(magisk --path)/.magisk/rootdir/init.rc`

But i cant find it i even check /sbin and /data/adb/magisk all i see is /.backup

**Comment by jooomoooj** [comment]
> 

Sorry i found it now but directory was inside /.magisk/rootdir/system/etc/init/hw not what u told
[magisk-init.rc.txt](https://github.com/topjohnwu/Magisk/files/8250825/magisk-init.rc.txt)

**Comment by pndwal** [comment]
> > then attach `$(magisk --path)/.magisk/rootdir/init.rc`
> 
> But i cant find it i even check /sbin and /data/adb/magisk all i see is /.backup

Open a terminal emulator app, type 'su', then type 'magisk --path'...

I get /sbin (but this is Android 10)... So I find init.rc in /sbin/.magisk/rootdir as indicated! 👍

**Comment by jooomoooj** [comment]
> > > then attach `$(magisk --path)/.magisk/rootdir/init.rc`
> > 
> > 
> > But i cant find it i even check /sbin and /data/adb/magisk all i see is /.backup
> 
> Open a terminal emulator app, type 'su', then type 'magisk --path'...
> 
> Result I get is /sbin (but mine is Android 10; your Magisk tmpfs mount path will be different)... So I find init.rc in /sbin/.magisk/rootdir as indicated! 👍

As u can see i already uploaded.. im just waiting for reply if ever

**Comment by yujincheng08** [comment]
we need full bootlog.

**Comment by Devun** [comment]
Please find attached the full boot log, I hope this will help you in solving this issue :).
[dmesg.log](https://github.com/topjohnwu/Magisk/files/8331053/dmesg.log)

Have a nice day

**Comment by yujincheng08** [comment]
I mean full bootlog, not dmesg. Please use adb logcat and ensure your log buffer is large enough.

**Comment by canyie** [comment]
@Devun Please check #5604 and #5623. Perhaps your issue has been fixed.

**Comment by Devun** [comment]
When reading the 2 referenced issues I think that indeed that problem has already been resolved. Good work!!!
Have a nice day

**Comment by jooomoooj** [comment]
Yes fixed in alpha version..
![Screenshot_20220324-195102312](https://user-images.githubusercontent.com/101556532/159910571-a04b308c-93bc-4380-b1c8-1cbf3c594f35.jpg)
