### ISSUE TITLE
Loosing root

### ISSUE THREAD

**Issue by Shadowghost** [topjohnwu/Magisk#56]
Messings around with magic mount atm but can't get logs or anything because root gets lost. The module adds some things to /system and sets some props, but that shouldn't break root access I suppose.

**Comment by c727** [comment]
you can get the logs in recovery /cache/magisk.log

**Comment by Shadowghost** [comment]
Nevermind seems like the last module I installed and removed manually did somehow fuck up Magisk, reflashed system and boot and all worked again. I can try reproducing it again if you want me to.

**Comment by Shadowghost** [comment]
Okay so here we go. The problem appears while testing the (not yet release ready as you can think) Magisk version of ARISE. Goal is to make it fully systemless with magic mount. The install script does it's job, everything needed is written to the module directory inside /data/magisk.img (which is ofc resized correctly). When looking at Magisk log everything seems to be mounted fine but root is still not working.
Recovery log: https://www.dropbox.com/s/6eh3dp2pb3bvha9/last_log?dl=0
Magisk log after install and bootup: https://www.dropbox.com/s/cfvpgxryaj22hyg/magisk.log?dl=0
If you need the installer or any Infos about ARISE itself just ask on XDA or PM.

**Comment by c727** [comment]
set correct permissions?

close this issue, it's not magisk related. you can ask about modules at xda...

**Comment by Shadowghost** [comment]
When Magisk is loosing root then it should be a Magisk issue when the module itself isn't changing crucial parts of /system. The point is that nothing else gets "installed" by the module than a proper system-install of ARISE would install. The latter one doesn't break root, so I thought it is Magisk related since ARISE shouldn't change anything which hinders Magisk to work properly.

**Comment by c727** [comment]
no module posted
no access to logs

**Comment by Shadowghost** [comment]
Updated my post, logs should be accessible now (sorry for the inconvenience).
And here's the module: https://cloud.strife.tk/index.php/s/H7Gu3MRz6RIcEXI

PS: We are aware that there still are bugs in the installer script but that shouldn't break root.

**Comment by c727** [comment]
your module may not work, but can you test if you still loose root with busybox disabled in magisk manager?

**Comment by Shadowghost** [comment]
Will report back when I have time.
Just some things I encountered while testing: Sometimes I have root for like 10 seconds after boot, then I was able to access /system and check if files were in place, but they are not (at least not all). When mounting magisk.img in TWRP and checking its contents everything is where it belongs. Seems like something on mounting procedure goes wrong. I'll update the module link to the most recent attempt.

**Comment by Shadowghost** [comment]
Some progress: Seems to be related to Magisk messing up /vendor mount. All other files get placed where they should but vendor is either not modified or just the files from the module. I think the mountpoint automatically created by magisk is somehow messing with the files.

**Comment by topjohnwu** [comment]
Vendor related issues are fixed
