### ISSUE TITLE
Add a new option that we can flash vbmeta.img in Magisk app and that new vbmeta will match with patched boot/recovery.img

### ISSUE THREAD

**Issue by hasanbd80** [topjohnwu/Magisk#5601]
### Add a new option that we can flash vbmeta.img in magisk and that new vbmeta will match with patched boot/recovery.img !
**magisk patched img not flashing**
![image](https://user-images.githubusercontent.com/101275948/158771836-2223f736-e4a3-4682-be4c-9e5b94100feb.png)

**VBMeta offset size is not matching** 

![image](https://user-images.githubusercontent.com/101275948/158772129-d9d375c2-a342-4a51-9baf-ac84c5eba8c7.png)
### Stock img

Original image size: 25319424 bytes
**VBMeta offset:** 25321472

### Patched img

Original image size: 25812992 bytes *
**VBMeta offset:** 25812992 ****

![image](https://user-images.githubusercontent.com/101275948/158773140-1e77612c-4719-41c3-a064-c4fe3d05250f.png)
vbmeta Stock image: (Unisoc sc9863a)
https://drive.google.com/drive/folders/1Dil75j34gMjo3Q_CsQwVT4P8kB3bBzBr

Device: i97 (Chip Unisoc sc9863a)
Android version: 9
Magisk version name: 24.3
Magisk version code: 24301

**Comment by vvb2060** [comment]
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img

**Comment by hasanbd80** [comment]
> fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img

This Also Not Working !! i can flash vbmeta but with --disable-verity --disable-verification  vbmeta not flashing
(I have latest fastboot that have --disable-verity --disable-verification with this options)

**Comment by hasanbd80** [comment]
> fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img

reopen this issue till not flashing 
version 25.1 post https://github.com/topjohnwu/Magisk/issues/6018
