### ISSUE TITLE
Magiskinit causes `security_setenforce` fails with Invalid argument

### ISSUE THREAD

**Issue by FercusHUN** [topjohnwu/Magisk#5607]
Device: Realme 7 5G
Android version: 11
Magisk version name: Canary
Magisk version code: 24302

Upgrade and patch with or without vbmeta patch stock boot.img same error.
24301 was perfect
[magisk_install_log_2022-03-18T11_15_06[1].log](https://github.com/topjohnwu/Magisk/files/8303829/magisk_install_log_2022-03-18T11_15_06.1.log)
[magisk_install_log_2022-03-18T11_22_22[1].log](https://github.com/topjohnwu/Magisk/files/8303830/magisk_install_log_2022-03-18T11_22_22.1.log)

**Comment by canyie** [comment]
Please follow these steps to grab an useful log:
1. Flash magisk patched boot.img
2. Reboot and let it bootloop
3. Wait atleast 2 mins, flash the stock boot.img and boot to android system
4. Run `adb bugreport` and upload the bugreport file

**Comment by FercusHUN** [comment]
Updated to 24303, no bootloop, just reboot to bootloader.
[bugreport-RMX2111EEA-RP1A.200720.011-2022-03-18-13-14-58.zip](https://github.com/topjohnwu/Magisk/files/8304385/bugreport-RMX2111EEA-RP1A.200720.011-2022-03-18-13-14-58.zip)

**Comment by FercusHUN** [comment]
No bootloop in 24303, just reboot to fastboot mode after flashing patched
img.

残页 ***@***.***> ezt írta (időpont: 2022. márc. 18., P, 14:04):

**Comment by FercusHUN** [comment]
[console-ramoops-0.zip](https://github.com/topjohnwu/Magisk/files/8304797/console-ramoops-0.zip)

**Comment by yujincheng08** [comment]
[    3.293919]  (6)[1:init]magiskinit: security_setenforce(true) failed: Invalid argument

**Comment by FercusHUN** [comment]
Can I do anything?

**Comment by yujincheng08** [comment]
send boot.img

**Comment by yujincheng08** [comment]
send `/system/bin/init` as well

**Comment by yujincheng08** [comment]
@user456789 Can you upload `/system/bin/init`?

**Comment by user456789** [comment]
[init.zip](https://github.com/topjohnwu/Magisk/files/8308581/init.zip)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8308620/app-debug.zip)
Can this build boot?

**Comment by user456789** [comment]
YES! Everything seems to work now. Partition is mounted.
Thank you! :+1:

**Comment by yujincheng08** [comment]
@user456789 can you give me the output of `su -c getenforce`?

**Comment by user456789** [comment]
It says "Enforcing"

**Comment by yujincheng08** [comment]
Ok, can you plz try this build?

@user456789
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8308685/app-debug.zip)

**Comment by user456789** [comment]
This one doesn't boot again.

**Comment by yujincheng08** [comment]
@user456789 ramoops plz?

**Comment by user456789** [comment]
[console-ramoops-0.log](https://github.com/topjohnwu/Magisk/files/8308695/console-ramoops-0.log)

**Comment by yujincheng08** [comment]
Oh, I made a typo. Try this again:
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8308697/app-debug.zip)

**Comment by user456789** [comment]
This is working but it Requires Additional Setup over and over.
Still says "Enforcing".

[magisk_install_log_2022-03-19T07:12:21.log](https://github.com/topjohnwu/Magisk/files/8308720/magisk_install_log_2022-03-19T07.12.21.log)
[magisk_log_2022-03-19T07:15:35.log](https://github.com/topjohnwu/Magisk/files/8308721/magisk_log_2022-03-19T07.15.35.log)

**Comment by yujincheng08** [comment]
For Requires Additional Setup, you need to rename the magisk I sent you to an `apk` file and install it.

**Comment by user456789** [comment]
Yeah I did that, otherwise I couldn't have tested, at least I don't know another way. Retried, but still this message.

**Comment by user456789** [comment]
Maybe because I played around with Zygisk in between (with the first build you sent) and disabled it later for your testing? Sorry, I'm still learning.

**Comment by Stillhard** [comment]
> This is working but it Requires Additional Setup over and over. Still says "Enforcing".
> 
> 
I can confirmed this.
But using [this artifact](https://github.com/topjohnwu/Magisk/suites/5720501337/artifacts/189025595) directly there's no such problem

**Comment by FercusHUN** [comment]
[init.zip](https://github.com/topjohnwu/Magisk/files/8308969/init.zip)

**Comment by yujincheng08** [comment]
@FercusHUN Try [this artifact](https://github.com/topjohnwu/Magisk/suites/5720501337/artifacts/189025595)

**Comment by FercusHUN** [comment]
This working fine

**Comment by FercusHUN** [comment]
Will this problem occur in the next update?

**Comment by qianmo-xw** [comment]
> Maybe because I played around with Zygisk in between (with the first build you sent) and disabled it later for your testing? Sorry, I'm still learning.

So,bro,how to unlock bootloader on emui10？I already have unlock code.
