### ISSUE TITLE
last canary won't work on samsung j5 2016

### ISSUE THREAD

**Issue by daywalk3r666** [topjohnwu/Magisk#5609]
Device: Samsung J5 2016
Android version: 10 Los 17.1
Magisk version name: canary
Magisk version code:24302

![Screenshot_20220318-120142_Magisk](https://user-images.githubusercontent.com/15938117/158993484-57113d8d-8497-463d-805a-b189b07416c3.png)
[magisk_install_log_2022-03-18T11:53:43.log](https://github.com/topjohnwu/Magisk/files/8304005/magisk_install_log_2022-03-18T11.53.43.log)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/8304012/dmesg.log)
[recovery.log](https://github.com/topjohnwu/Magisk/files/8304013/recovery.log)

**Comment by canyie** [comment]
> [    5.557681]  [0:           init:    1] init: init first stage started!
[    5.557771]  [0:           init:    1] init: First stage mount skipped (recovery mode)

Your dmesg is grabbed in recovery mode so it is useless. Please upload bugreport instaed.

**Comment by daywalk3r666** [comment]
your pull request fix the issues

**Comment by canyie** [comment]
It's not merged yet 😋 so let's reopen until official version fixes this.
