### ISSUE TITLE
Failed to dlopen zygisk module

### ISSUE THREAD

**Issue by rowhel95** [topjohnwu/Magisk#5611]
Device: Samsung Galaxy S20+ 5G
Android version: 12
Magisk version name: Canary
Magisk version code: 24303

Failed to dlopen zygisk module: dlopen failed: file offset for the library "/jit-cache" >= file size: 0 >= 0

Is something going wrong?

[magisk_log_2022-03-18T13_52_46.log](https://github.com/topjohnwu/Magisk/files/8304561/magisk_log_2022-03-18T13_52_46.log)

**Comment by yujincheng08** [comment]
nothing. just ignore it.
