### ISSUE TITLE
Android 11 Samsung GAlaxy S21+5G  Not passoble to mount / 

### ISSUE THREAD

**Issue by mauroa85** [topjohnwu/Magisk#5612]
Device: 
Android version:11
Magisk version name:  24303
Magisk version code: 243030

With the new version is not possible to do  #  mount -orw,remount /
'/dev/block/dm-0' is read-only

On previous versions this was possible.

**Comment by HuskyDG** [comment]
> Device: Android version:11 Magisk version name: 24303 Magisk version code: 243030
> 
> With the new version is not possible to do # mount -orw,remount / '/dev/block/dm-0' is read-only
> 
> On previous versions this was possible.

Maybe your system partition is ext4 dedup?
https://mobile.twitter.com/topjohnwu/status/1170404631865778177?lang=vi=2ahUKEwjj8u2P8tD2AhW-yzgGHR5hCYsQjjh6BAgOEAE&usg=AOvVaw2zUMZ9rHVSG2mNQ6c4PhTy

**Comment by mauroa85** [comment]
On S21 +5G android 11 e 12   , The magisk version that is working is  24201 (23)
The latest one does not work
