### ISSUE TITLE
Magisk install/update fastboot graveyard digger

### ISSUE THREAD

**Issue by Stillhard** [topjohnwu/Magisk#5617]
Device: 
Android version: 11
Magisk version name: 87613269
Magisk version code: 24303

After Magisk install/update, the device just boot to fastboot and do nothing, revert to old patched or orig boot.img will make it boot normally.

**_failed_** magisk patched boot.img: 
[magisk_patched-24301_oJjU3.zip](https://github.com/topjohnwu/Magisk/files/8308380/magisk_patched-24301_oJjU3.zip)

good **magisk** patched boot.img (last used from 810d27a6): 
[magisk_patched-24303_PT0Wd.zip](https://github.com/topjohnwu/Magisk/files/8308381/magisk_patched-24303_PT0Wd.zip)

orig boot.img: 
[boot.zip](https://github.com/topjohnwu/Magisk/files/8308382/boot.zip)

**Comment by yujincheng08** [comment]
Need dmesg if device does not boot.

**Comment by Stillhard** [comment]
> Need dmesg if device does not boot.

Here you go (taken after i switched back to good magisk patched boot.img right after update failed) [dmesg.log](https://github.com/topjohnwu/Magisk/files/8308488/dmesg.log)

**Comment by yujincheng08** [comment]
last_kmsg is empty. Maybe find ramoops?

**Comment by Stillhard** [comment]
> last_kmsg is empty. Maybe find ramoops?

I tried, i can't find it in this device

```
Infinix-X695C:/ $ su
Infinix-X695C:/ # zcat /proc/config.gz |grep PSTORE
CONFIG_PSTORE=y
CONFIG_PSTORE_ZLIB_COMPRESS=y
# CONFIG_PSTORE_LZO_COMPRESS is not set
# CONFIG_PSTORE_LZ4_COMPRESS is not set
CONFIG_PSTORE_CONSOLE=y
CONFIG_PSTORE_PMSG=y
CONFIG_PSTORE_RAM=y
Infinix-X695C:/ #

Infinix-X695C:/ # cat /mnt/console-ramoops-0
cat: /mnt/console-ramoops-0: No such file or directory
1|Infinix-X695C:/ #

1|Infinix-X695C:/ # ls /mnt
androidwritable  asec    expand     media_rw  pass_through  runtime  secure   user
appfuse          cd-rom  installer  obb       product       sdcard   traffic  vendor
Infinix-X695C:/ #
```

Kind to direct me what else needed?

**Comment by yujincheng08** [comment]
In `/sys/fs/pstore/`

**Comment by Stillhard** [comment]
> In `/sys/fs/pstore/`

Ah... you're too good
Here they're [ramoops.zip](https://github.com/topjohnwu/Magisk/files/8308627/ramoops.zip)

**Comment by yujincheng08** [comment]
Nothing helpful.

Flash magisk 24303, reboot and let it fall to fastboot, flash old magisk that works, reboot, and get ramoops.

**Comment by Stillhard** [comment]
> Nothing helpful.
> 
> Flash magisk 24303, reboot and let it fall to fastboot, flash old magisk that works, reboot, and get ramoops.

Ok, hold up

**Comment by Stillhard** [comment]
@yujincheng08 - I tried [this ](https://github.com/topjohnwu/Magisk/issues/5607#issuecomment-1072941927) and it boot normally, is it the same problem/fix for my prob?

**Comment by yujincheng08** [comment]
Duplicated of #5607

**Comment by Stillhard** [comment]
Way to go 👍- thx @yujincheng08
