### ISSUE TITLE
Boot animation replacement doesn't work since 16.4

### ISSUE THREAD

**Issue by TpmKranz** [topjohnwu/Magisk#562]
Upgrading from 16.0 to 17.1, I noticed that the boot animation from @osm0sis' [Nexus Media module](https://github.com/Magisk-Modules-Repo/Nexus-Media-Installer) doesn't override my ([rather obnoxious](https://www.youtube.com/watch?v=jq303ZYOMl0)) stock boot animation anymore.

A bit more investigation produced that it stopped working with Magisk 16.4.

I'll attach the Magisk logs of every version I tried:

- [16.0](https://github.com/topjohnwu/Magisk/files/2345454/magisk1600.log)
- 16.1 bootlooped for me :man_shrugging:
- [16.2](https://github.com/topjohnwu/Magisk/files/2345456/magisk1620.log)
- [16.3](https://github.com/topjohnwu/Magisk/files/2345457/magisk1630.log)
- [16.4](https://github.com/topjohnwu/Magisk/files/2345458/magisk1642.log) (:arrow_left: where it stopped working)
- [16.6](https://github.com/topjohnwu/Magisk/files/2345459/magisk1662.log)
- [16.7](https://github.com/topjohnwu/Magisk/files/2345460/magisk1671.log)
- 17.0 is 2spooky4me
- [17.1](https://github.com/topjohnwu/Magisk/files/2345461/magisk1710.log)

Is this a Magisk bug/feature or should I open an issue at the module's repo?

Thank you for everything!

**Comment by Didgeridoohan** [comment]
That's a side effect of removing the post-fs stage and replacing it with a new simple mount that unfortunately doesn't kick in early enough on all devices.

https://forum.xda-developers.com/showpost.php?p=76371726&postcount=42

**Comment by TpmKranz** [comment]
Shoot, so no easy fix for me, except switching to a device where the mounting happens to happen early enough?

Is it something @topjohnwu plans to/wants to/can fix? If so, I'd gladly help testing; I'm on a Moto Z2 Play with stock Oreo 8.0, `KEEPVERITY` and `KEEPFORCEENCRYPT` both set to `true` and a device password set.

**Comment by osm0sis** [comment]
Nope. He made everything post-fs-data to simplify it and has no intention of adding post-fs back.

Only solution for you is to force my module to install to /system by renaming it with -system in the filename and flashing it from recovery.

**Comment by TpmKranz** [comment]
Bummer. Thanks for taking the time to explain it to me.

I'd hoped to stay completely systemless since not keeping dm-verity complicates modding on my phone/stock firmware. (If anyone's interested, read [this](https://forum.xda-developers.com/showpost.php?p=77191765&postcount=38) and [this](https://forum.xda-developers.com/showpost.php?p=77193684&postcount=39).)

If @topjohnwu ever changes his mind, I'll be here ready to test (and get rid of that awful bootanimation systemlessly :yum:).

Please close this issue at your discretion, and thanks again. Have a nice day, y'all!
