### ISSUE TITLE
Lastest Magisk Canary 24303 is no longer launched on BlissOS Android 9

### ISSUE THREAD

**Issue by HuskyDG** [topjohnwu/Magisk#5621]
Device: BlissOS (Android-x86)
Android version: 9
Magisk version name: 87613269
Magisk version code: 24303

This is report from Android-x86 (Android on PC) not Android on actual devices. Maybe this issue is invalid!

Lastest Magisk Canary 24303 is no longer working on BlissOS Android 9 but previous Magisk version code 24301 works fine.

I guess `magisk --[trigger]` not work during boot.

But `magisk --daemon` is still working...

If you need some information, tell me.

**Comment by HuskyDG** [comment]
i grabbed this log via Debug mode of BlissOS. I don't know it will be helpful

[boot_log.txt](https://github.com/topjohnwu/Magisk/files/8309744/boot_log.txt)

**Comment by yujincheng08** [comment]
Try #5615?

**Comment by HuskyDG** [comment]
Tried 0f07bbb3 and problem still presist

**Comment by HuskyDG** [comment]
> Try #5615?

Oh i knew, magiskpolicy is no longer an applet  of magiskinit. I am using `avd_magisk.sh` to integrate magisk into BlissOS.

**Comment by HuskyDG** [comment]
I have fixed this problem by myself
