### ISSUE TITLE
"Fullscreen/Immersive Gestures (Q-S)" module doesn't work properly or causes bootloop

### ISSUE THREAD

**Issue by Rokcy98** [topjohnwu/Magisk#5624]
Device: Asus Zenfone 8
Android version: 12
Magisk version name: 3dc7d77e
Magisk version code: 24304

Latest canary build is preventing the module "Fullscreen/Immersive Gestures (Q-S)" from working properly.
It fails to work if it's the only module enabled, and it causes bootloop if it's enabled alongside with quickswitch.
It worked just fine until previous release, alongside with Lawnchair and Quickswitch enabled.

**Comment by Rokcy98** [comment]
I'm attaching Magisk Log and Logcat during the bootloop
[log.txt](https://github.com/topjohnwu/Magisk/files/8314527/log.txt)
[magisk_log_2022-03-21T10_49_41.log](https://github.com/topjohnwu/Magisk/files/8314528/magisk_log_2022-03-21T10_49_41.log)

**Comment by yujincheng08** [comment]
Both logs are useless.
For the first log, I cannot see anything about Magisk
For the second log, I cannot see any modules installed in Magisk.

**Comment by Rokcy98** [comment]
That's everything I get if I take logs after trying to boot with both modules enabled, (alongside with bootloop saver of course).
I don't know how could I get more informations, if you need something more ask me!

**Comment by yujincheng08** [comment]
[Log Catcher-v22.5(27).zip](https://github.com/topjohnwu/Magisk/files/8314888/Log.Catcher-v22.5.27.zip)

> A Magisk module that can help you save the log
> required Magisk 20.4+
> The log is saved to /cache/bootlog by default
> If /cache does not exist, save to /data/local/bootlog
> If you don't want to kill the logcat process after boot completed, you can create a file named boot.lcs to /data/local/logcatcher/ .
> 
> When the system boot normally and /data/local/logcatcher/boot.lcs is not detected, the logs will be packaged and copied to the Download folder
>

**Comment by Rokcy98** [comment]
> [Log Catcher-v22.5(27).zip](https://github.com/topjohnwu/Magisk/files/8314888/Log.Catcher-v22.5.27.zip)
> 
> > A Magisk module that can help you save the log
> > required Magisk 20.4+
> > The log is saved to /cache/bootlog by default
> > If /cache does not exist, save to /data/local/bootlog
> > If you don't want to kill the logcat process after boot completed, you can create a file named boot.lcs to /data/local/logcatcher/ .
> > When the system boot normally and /data/local/logcatcher/boot.lcs is not detected, the logs will be packaged and copied to the Download folder

Should I just install it and replicate the bootloop, or do I need to insert a command or something like that?

**Comment by Rokcy98** [comment]
[boot.log](https://github.com/topjohnwu/Magisk/files/8315022/boot.log)

**Comment by yujincheng08** [comment]
Can you send these two modules?

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8316943/app-debug.zip)
Try this and grab log

**Comment by Rokcy98** [comment]
how should I install it?
I renamed it to apk, but it says invalid package

**Comment by Rokcy98** [comment]
![Screenshot_20220321-170842](https://user-images.githubusercontent.com/62332789/159302959-04881050-8571-47ab-9660-60282e47208e.png)
"app not installed, because the package is invalid"

**Comment by Rokcy98** [comment]
Do I need to uninstall my magisk manager first?

**Comment by yujincheng08** [comment]
Yes

**Comment by Rokcy98** [comment]
![Screenshot_20220321-170842](https://user-images.githubusercontent.com/62332789/159304266-29678660-ad97-468d-881b-b44a7dfaf4a8.png)
that's my situation now

**Comment by Rokcy98** [comment]
![Screenshot_20220321-171654](https://user-images.githubusercontent.com/62332789/159304322-7ebdb572-0265-45a9-890b-01e2754cd5e8.png)
That's my situation now

**Comment by yujincheng08** [comment]
> ok, installed, what should I do now?

I said grab log.

**Comment by yujincheng08** [comment]
Yes;
Yes.

**Comment by Rokcy98** [comment]
Doing it right now

**Comment by Rokcy98** [comment]
[boot-2022-03-21-17-39-48.log](https://github.com/topjohnwu/Magisk/files/8317366/boot-2022-03-21-17-39-48.log)
It boots, but the module completely removed the gesture navigation option, instead of simply hiding the navbar, so it's not working properly

**Comment by Rokcy98** [comment]
I contacted DanGLES3 (the dev of the module), this morning, he helped me as you did.
He confirmed this commit: https://github.com/topjohnwu/Magisk/commit/dd5a3416bf4d4154b0c402b02225c4fcacf465bc was causing the problem. He gave me a build with this commit reversed and everything worked

**Comment by yujincheng08** [comment]
I know that commit causes the problem. But reverting it will cause other problem.

**Comment by Rokcy98** [comment]
> I know that commit causes the problem. But reverting it will cause other problem.

Ok, I'll try your build then

**Comment by Rokcy98** [comment]
[boot-2022-03-21-18-14-23.log](https://github.com/topjohnwu/Magisk/files/8317860/boot-2022-03-21-18-14-23.log)
Nope, always the same problem as the previous build you sent me

**Comment by Rokcy98** [comment]
So, you both got to know what's the problem, that's good.
I got to go for an hour or two, keep sending me builds if you want, I'll test them as soon as I can.
Thanks for your work

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8318361/app-debug.zip)
