### ISSUE TITLE
User data + Internal storage wiped after flashing 17.1 via TWRP

### ISSUE THREAD

**Issue by zhuhang-jasper** [topjohnwu/Magisk#563]
After flashing the lastest 17.1 magisk zip via TWRP, rebooted my phone and everything is wiped.
User data and internal storage were wiped. And I am faced with the new phone setup again.

I never see before anyone mentioning data will be wiped. Is this a bug?

**Comment by topjohnwu** [comment]
No info provided, closed

**Comment by zhuhang-jasper** [comment]
What info do you need?
Magisk 17.1 flashed via latest TWRP version, on Samsung A720F/DS running stock rom Android 8.0.0 Oreo.
Internal storage + data wiped. 
In what occasion does Magisk wipe user-data??
