### ISSUE TITLE
Magisk cant patch custom kernel

### ISSUE THREAD

**Issue by June-AV** [topjohnwu/Magisk#5631]
I installed ares kernel and magisk to stock rom after rebooting blank screen and logo samsung doesn't show up. but install kernel without install magisk reboot normally. have tried different versions of magisk but the result is still the same.
This Log.

[dmesg.log](https://github.com/topjohnwu/Magisk/files/8314740/dmesg.log)

[recovery.log](https://github.com/topjohnwu/Magisk/files/8314741/recovery.log)

[last_ksmg & boot.img.zip](https://github.com/topjohnwu/Magisk/files/8314756/last_ksmg.boot.img.zip)

Device: Samsung
Android version: 10
Magisk version code: 24304

**Comment by yujincheng08** [comment]
`<14>[    6.64#%25]  [4:         ( init:    1] init� Command 'sdart apexd& action=post-fs-data */init.rk:>14) took 0ms�and failed: Could n�t start service: File /systmm/bin/apexd(labeled "u:objekt_r:apexd_exec:s�")�has incorrect label"or no�doma�n transitio� from u:r:kernel:s0 to another �ELinux domain defined. �ave"yoe konfigubed your rervi�e correctly? httpb://source.andrni�.bom/�eburity/selinux/device-pnlicy��ab�l_new_servicec_`ndOaddress_denhals`

**Comment by yujincheng08** [comment]
I don't think the log was grabbed using magisk 24304.
