### ISSUE TITLE
Impossible to update Magisk

### ISSUE THREAD

**Issue by gu1zm0-1337** [topjohnwu/Magisk#5633]
Device: Galaxy S10 (SM-G973F)
Android version: 12
Magisk version name: 3dc7d77e
Magisk version code: 24304

hi, today i updated to Magisk app to 3dc7d77e (24304) the magisk app get opened back it asks for additional setup so i clicked ok, checked "Recovery Mode"then "Direct Install", rebooted my device and when i open magisk, it still asks for additional setup my magisk is stuck at version 753808a4 (24302).

- Root is still working correctly
- I tried with and without modules

thanks for your work

[magisk_install_log_2022-03-22T19_02_32.log](https://github.com/topjohnwu/Magisk/files/8326842/magisk_install_log_2022-03-22T19_02_32.log)

**Comment by yujincheng08** [comment]
Try to patch boot.img and flash it by fastboot

**Comment by pndwal** [comment]
Could try test build with fixes in artifacts here:
https://github.com/topjohnwu/Magisk/actions/runs/2021986845
- good for me... 🙂

**Comment by Jon8RFC** [comment]
Unsure if this applies, but I've had a similar issue in the past. Root worked, but the app acted as if it wasn't rooted after updating and then rebooting. It was a problem with updating magisk while magisk was hidden. It somehow installed as an unhidden magisk, which didn't work, and my hidden magisk still existed, but also didn't work. Root apps worked. I think what I did was attempt to manually delete everything about the old hidden magisk (from reading guides), uninstall the new/updated magisk app, reboot, then install magisk app again. Then it worked as expected, and I could then hide it again.

**Comment by gu1zm0-1337** [comment]
Hi,

Ok so i repatched the full firmware with the new version and reflashed it over the old one and it did the work, thanks you all
