### ISSUE TITLE
ih8sn modul\Safetynet error with the last Canary

### ISSUE THREAD

**Issue by WikiBayer** [topjohnwu/Magisk#5634]
CTS Profile match fails.
Only a magisk downgrade will help

Device: Poco X3 Pro
Android version: AICP 16.1 with ih8sn module and microG
https://github.com/Hakimi0804/ih8sn-magisk
Magisk version name: 3dc7d77e
Magisk version code: 24304

**Comment by osm0sis** [comment]
Please ask the ih8sn developer to look into it and create a bug report that actually contains useful information.
