### ISSUE TITLE
Unable to root my Pixel, ending up everytime with a bootloop

### ISSUE THREAD

**Issue by MarQc13** [topjohnwu/Magisk#564]
Hi! 

I'm trying to root again my Pixel (sailfish) after the Pie 9 upgrade with latest Magisk Manager 17.1 and everything end up in a bootlooping mode. 

I have the lastest sdk-tools installed. 
Bootloader unlocked
Build version : PPR1.180610.010

I have the original boot file and I know it's working well since it's the one I flash to resolve the bootloop on my device. 

I'm using Magisk to flash the boot file as requested, I then transfer the patched_boot in my sdk-platform folder and performing this command : 

---
C:\android-sdk\platform-tools>c:\windows\system32\cmd.exe
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\android-sdk\platform-tools>adb devices
List of devices attached
* daemon not running; starting now at tcp:5037
* daemon started successfully
FA69Pxxxxxxxx    device

C:\android-sdk\platform-tools>adb reboot-bootloader

C:\android-sdk\platform-tools>fastboot devices
FA69Pxxxxxxxxx    fastboot

C:\android-sdk\platform-tools>fastboot flash boot --slot all patched_bootP9.img
Sending 'boot_a' (29973 KB)                        OKAY [  1.042s]
Writing 'boot_a'                                   OKAY [  0.266s]
Sending 'boot_b' (29973 KB)                        OKAY [  0.834s]
Writing 'boot_b'                                   OKAY [  0.901s]
Finished. Total time: 3.353s

C:\android-sdk\platform-tools>fastboot reboot
Rebooting
Finished. Total time: 0.030s
---
(To revert the bootlooping)
---

C:\android-sdk\platform-tools>adb devices
List of devices attached
FA69Pxxxxxxx    device

C:\android-sdk\platform-tools>adb reboot-bootloader

C:\android-sdk\platform-tools>fastboot flash boot --slot all bootpie9.img
Sending 'boot_a' (29753 KB)                        OKAY [  1.051s]
Writing 'boot_a'                                   OKAY [  0.266s]
Sending 'boot_b' (29753 KB)                        OKAY [  0.834s]
Writing 'boot_b'                                   OKAY [  0.300s]
Finished. Total time: 2.788s

C:\android-sdk\platform-tools>fastboot reboot
Rebooting
Finished. Total time: 0.009s

C:\android-sdk\platform-tools>  
---
(bootloop resolved)

Can you help me to pinpoint where I'm doing it wrong please? 

TIA

**Comment by topjohnwu** [comment]
I own a Pixel XL, not issues for me.
