### ISSUE TITLE
Abnormal use of ram when systemless hosts is active

### ISSUE THREAD

**Issue by Hadjigit** [topjohnwu/Magisk#5650]
hello,
I noticed an abnormal use of ram by google play services, play store and gboard after enabling systemless hosts 

The former apps works normally if i deactivate systemless hosts. The same issue with the stable version 24300

Screenshot:

![Screenshot_2022-03-25-19-03-33-776_com miui securitycenter](https://user-images.githubusercontent.com/102378518/160179556-b489fd7d-ae7a-4a30-8e4d-1d62bf38b396.jpg)

> 

Device: xiaomi redmi note 10 (mojito)
Android version: 12
Magisk version name:  3dc7d77e
Magisk version code: 24304

[magisk_log_2022-03-25T19_03_58.log](https://github.com/topjohnwu/Magisk/files/8353014/magisk_log_2022-03-25T19_03_58.log)

Extra info: 

![IMG_20220325_193412](https://user-images.githubusercontent.com/102378518/160181246-708fae1e-f01b-4b06-a8b9-ea96db2bc84a.jpg)

**Comment by HuskyDG** [comment]
Try add these things into DenyList to revoke modification

**Comment by Hadjigit** [comment]
> Try add these things into DenyList to revoke modification

I did add every app and service that has xxx.google.xxx in its name. 

> Google play services: from 1gb went down to 600 mb of ram usage

> Chrome: from 500mb to 270mb ram usage 

> Gboard and play store ram usage was normal

(I tried to keep the same context of opened apps and tabs)

**Comment by yujincheng08** [comment]
send the host you defined

**Comment by yujincheng08** [comment]
send the host you defined

**Comment by Hadjigit** [comment]
> send the host you defined

I just activated systemless hosts... I defined nothing

**Comment by cyberboh** [comment]
Dont use huge hosts file, they are useless. Just use what u need, try hosts by StevenBlack, its enough.

**Comment by Hadjigit** [comment]
> Try Adaway - works fine for me.

Dns66 also works fine, I'm not looking for an alternative since i don't want another app working in the background

**Comment by Hadjigit** [comment]
> Dont use huge hosts file, they are useless. Just use what u need, try hosts by StevenBlack, its enough.

Just activating systemless hosts will load my ram without any hosts applied or modules installed.

**Comment by topjohnwu** [comment]
This seems like an issue with your device/OS. Magisk is simply replacing the host file, nothing fancy
