### ISSUE TITLE
Superuser permission settings wrong notification

### ISSUE THREAD

**Issue by rowhel95** [topjohnwu/Magisk#5665]
Device: Samsung Galaxy S20+ 5G
Android version: 12
Magisk version name: 704f9154
Magisk version code: 24305

When disabling/enabling logs or notifications for superuser permission the bottom notification is showing each others status, so if you disable logs the notification shows the status of notifications

https://user-images.githubusercontent.com/17615589/160942032-c4581173-70d9-48c9-9b85-bf41e3521b21.mp4

**Comment by HuskyDG** [comment]
> Device: Samsung Galaxy S20+ 5G Android version: 12 Magisk version name: [704f915](https://github.com/topjohnwu/Magisk/commit/704f91545e8433c382af25c136d06bee07684d7e) Magisk version code: 24305
> 
> When disabling/enabling logs or notifications for superuser permission the bottom notification is showing each others status, so if you disable logs the notification shows the status of notifications
> 
>  Screen_Recording_20220331-002854.mp4

Your system has delayed on each toast notification

**Comment by rowhel95** [comment]
nope those notifications are instant and even enabling/disabling for first time without notification shows wrong message

**Comment by HuskyDG** [comment]
> nope those notifications are instant and even enabling/disabling for first time without notification shows wrong message

You are right!
