### ISSUE TITLE
Re: User data & Internal storage wiped after flashing 17.1 via TWRP

### ISSUE THREAD

**Issue by zhuhang-jasper** [topjohnwu/Magisk#567]
Reference closed issue: #563 
What info do you need?

**Info**
Phone: **Samsung A720F/DS running stock rom Android 8.0.0 Oreo.**
Magisk: **v17.1** 
TWRP: **v3.2.3**

**Problem Cases**
1. Flash samsung stock rom build `A720FXXU3CRF3` (only AP) using Odin. 
Then flash TWRP. Boot into TWRP, flash `Magisk 17.1` zip, flash `no-verity-opt-encrypt` zip, reboot system, Internal storage + data wiped.
2. Flash samsung stock rom build `A720FXXU3CRF3` (BL, AP, CP, HOME_CSC) using Odin. 
Then repeat all same steps as 1.

If you want the log, then I have to intentionally wipe my user data just to get you that.

In what occasion does Magisk wipe user-data??

**Comment by rgawenda** [comment]
Are you really sure it's wiped or '"not mounted". I found that 17.x doesn't mount internal storage for me (whyred, pixel experience pie). Booting into twrp shows everithing it's on its place. Uninstalling 17.x and flashing 16.7 again works for me

**Comment by zhuhang-jasper** [comment]
@rgawenda Yes, it is wiped. After the reboot of flashing 17.1, i need to go through the new phone setup (language, google account, etc) And the internal storage was wiped as well (music, photo,etc).

**Comment by zhuhang-jasper** [comment]
Is it possible because magisk is "too smart" to detect the data partition is encrypted and inaccessible, so it goes ahead to format it without user consent? (Samsung stock have data partition encrypted, need to format it to remove encryption, usually should be a manual task)

**Comment by topjohnwu** [comment]
Of course not, Magisk does not wipe anything. It is most likely some weird setup of your device.

**Comment by zhuhang-jasper** [comment]
This happens two times to me after flashing magisk.
