### ISSUE TITLE
Not Supported Patching "boot.img" File on Oppo A92

### ISSUE THREAD

**Issue by Jockey19** [topjohnwu/Magisk#5678]
Device: OPPO A92
Android version: 11 (with update minor 11.1/CPH2059.C.35)
Magisk version name: N/A
Magisk version code: 24305

Not yet supported in device arm64-v8a. Error while the patch "boot.img" file. Show alert in logs, "Unsupported/unknown image format"

![Screenshot_2022-04-02-08-05-17-33_785cfb1f0fb0c9a2030c9b38a1c3479a](https://user-images.githubusercontent.com/86283749/161359832-3f090729-91dc-45f0-997c-ba3b27cdd5c5.jpg)

[File "boot.img" OTA Oppo A92](https://www.mediafire.com/file/f9be7w0tgy6ck47/boot.img/file)

**Comment by canyie** [comment]
Please upload the boot.img

**Comment by osm0sis** [comment]
Money says it's the boot.img.p extracted from an OTA 😉

**Comment by Jockey19** [comment]
> 

So how can I get the boot files right?

**Comment by Jockey19** [comment]
> Please upload the boot.img



> Please upload the boot.img

I've added the boot file at the bottom of the comments. Thanks

**Comment by osm0sis** [comment]
Not sure where you got that but it's definitely not a boot partition, the magic in the first few bytes is "MSDOS" which on Oppo/OnePlus makes it more likely to be a spunvm or modem dump, not boot.

**Comment by Jockey19** [comment]
> Not sure where you got that but it's definitely not a boot partition, the magic in the first few bytes is "MSDOS 5.0" which on Oppo/OnePlus makes it more likely to be a spunvm or modem dump, not boot. Go find a device forum for your model and ask there how to to root.

Means Oppo devices are not supported to root with Magisk.
Thanks.

**Comment by osm0sis** [comment]
No it means you need to use the boot image to root them, just like every other device.
