### ISSUE TITLE
Magisk "device owner managed" multiuser mode does not work when used between owner (0) and secondary (10) accounts 

### ISSUE THREAD

**Issue by arolano** [topjohnwu/Magisk#5679]
Device: Pixel 3A XL Bonito
Android version: 12L
Magisk version name: Canary
Magisk version code:  24305

Tested on both most recent Canary and stable release. Exactly same behavior.

Steps to reproduce:
Install Magisk and confirm it works fine
Create and configure a secondary user (UserId 10)
Install magisk to secondary user 
In Device Owner account (UserId 0) switch magisk to "device Owner Managed" mode 

Expectation:
Root access for apps in Secondary Account (10) will be manageable from Device Owner account (so I would need to switch to Owner to actually grant / tune root access, as a kind of heavy-duty tapjacking / user error protection)

Behavior:
requests from Secondary account are always rejected (per log), silently. Root UI does not show any switches for apps from secondary account

Switching to "independent" mode allows root to function on Secondary acc (10) but it is not what I need, I'd like to use the (nominally present :) ) option of "device owner managed" to have device owner acc (0) manage the Secondary (10)'s root access 

Additional notes:
Tested on Canary (latest) and stable release.
Tested both zygisk and non-zygisk
behavior stays same

**Comment by vvb2060** [comment]
https://source.android.google.cn/devices/tech/admin/multi-user

Device Owner Only -> Single User (System user only) `android.os.usertype.full.SYSTEM`
device owner managed -> Profile (A profile is a subset of, and tied to, the existence of a user.)  `android.os.usertype.profile.*`
User-Independent -> Secondary user `android.os.usertype.full.SECONDARY`

**Comment by vvb2060** [comment]
> Create and configure a secondary user (UserId 10)

You should use "User-Independent" mode

**Comment by sourcevault** [comment]
whats a `user-Independent`  Mode ?

I created a user like so :
```
su -l
pm --create-user vvb2060
```

It creates `android.os.usertype.full.SECONDARY` by default. 

how do you give user `vvb2060` root access ?

**Comment by null-dev** [comment]
For anybody else who ended up here:

If you want to grant to an app running in a profile (`android.os.usertype.profile.*`, AKA work profile or secure folder but NOT a completely separate secondary user), you need to have the app installed in both the profile and the device owner user. Otherwise the prompt that asks for root will not work.

**Comment by vvb2060** [comment]
@null-dev This is a bug and we will fix it.
