### ISSUE TITLE
Magisk can not process boot images

### ISSUE THREAD

**Issue by Displax** [topjohnwu/Magisk#568]
Sometimes (sometimes not) Magisk can not process boot images in magisk manager (v5.9.1). It is failed after "Signing boot image with test keys". When downgrade Magisk Manager to v5.8.3 all works fine with no issues. In TWRP this issue also appears.
Some examples:
![img1](https://user-images.githubusercontent.com/16293419/45045198-f0f6b980-b07a-11e8-9154-3bab1dcbeece.png)
![img2](https://user-images.githubusercontent.com/16293419/45045199-f0f6b980-b07a-11e8-977a-458924708592.png)
![img3](https://user-images.githubusercontent.com/16293419/45045200-f0f6b980-b07a-11e8-8682-2e85ccd2447b.png)
![img4](https://user-images.githubusercontent.com/16293419/45045202-f0f6b980-b07a-11e8-8240-dfff2044d852.jpg)

**Comment by pundoo** [comment]
Any update on this? I'm also having the same issue.

**Comment by topjohnwu** [comment]
No log, can't fix

**Comment by ayucapal** [comment]
> Try granting Magisk Manager permission to access Storage.

thank you so much.
