### ISSUE TITLE
OTA triggers red `eio` screen then bootloops on Pixel 6

### ISSUE THREAD

**Issue by capntrips** [topjohnwu/Magisk#5685]
Device: Pixel 6
Android version: 12.1
Magisk version name: 704f9154
Magisk version code: 24305

The red `eio` [screen](https://source.android.com/security/verifiedboot/boot-flow#dm-verity-corruption) issue has existed since the March update on 24304. While falling back to 24301 worked for the March update, the April update bootloops.

While I experienced it during the initial OTA for both the March and April updates, I have been unable to replicate the `eio` screen issue on subsequent test reinstalls, though i did experience it [once](https://github.com/topjohnwu/Magisk/issues/5685#issuecomment-1090191730) when rolling back to the previous slot.

It is probably worth noting that some XDA members reported issues taking OTAs prior to the above issues arising.

**Note:** The April OTA installed on a Pixel 5a on 24305 without issue.

**Comment by bzz11g** [comment]
Confirm this

**Comment by bzz11g** [comment]
Device: Pixel 6
Android version: 12.1
Magisk version name: https://github.com/topjohnwu/Magisk/releases/tag/v24.3
Magisk version code: 24300

Confirm this issue on stable Magisk

**Comment by capntrips** [comment]
I clean flashed `220305.013.a3` and took the `220405.004` OTA with no apps or modules on 24305, and this time I did not get the `eio` screen, though it did still bootloop. I'm not sure if the difference is related to the data or the fact that I had previously installed `220405.004`.

I'll try to repeat the same procedure with my usual modules tonight, to see if that is enough to trigger the `eio` screen, again.

In the meantime, here is the output from `dmesg` from stock and rooted (24305) `220305.013.a3` and `220405.004`:

[oriole-sp2a.220305.013.a3-stock-dmesg.log](https://github.com/topjohnwu/Magisk/files/8419627/oriole-sp2a.220305.013.a3-stock-dmesg.log)
[oriole-sp2a.220405.004-stock-dmesg.log](https://github.com/topjohnwu/Magisk/files/8419626/oriole-sp2a.220405.004-stock-dmesg.log)
[oriole-sp2a.220305.013.a3-24305-dmesg.log](https://github.com/topjohnwu/Magisk/files/8419624/oriole-sp2a.220305.013.a3-24305-dmesg.log)
[oriole-sp2a.220405.004-24305-dmesg.log](https://github.com/topjohnwu/Magisk/files/8419625/oriole-sp2a.220405.004-24305-dmesg.log)

Here are the `ramoops` and `dmesg` gathered immediately after bootlooping and rolling back to the previous slot after attempting to take the `220405.004` OTA on 24305:

[oriole-sp2a.220405.004-upgrade-console-ramoops.log](https://github.com/topjohnwu/Magisk/files/8419623/oriole-sp2a.220405.004-upgrade-console-ramoops.log)
[oriole-sp2a.220305.013.a3-rollback-dmesg.log](https://github.com/topjohnwu/Magisk/files/8419622/oriole-sp2a.220305.013.a3-rollback-dmesg.log)

**Comment by yujincheng08** [comment]
`oriole-sp2a.220405.004-24305-dmesg` looks quite normal. It seems like the problem is not caused by `magiskinit` but `magiskd`. Since you can get the `dmesg` while bootlooping, you can also access `adb logcat` right? Could you please provide `adb logcat` as well?

**Comment by capntrips** [comment]
The first four there are from a normally running device. Only the last two were from a bootloop. `adb` never connects while bootlooping. The full Google logo displays briefly, then it drops to the bootloader.

**Comment by yujincheng08** [comment]
So the first four logs are useless.

But the last two logs have nothing about magisk.

**Comment by yujincheng08** [comment]
It should have fixed by #5603. Weird.

**Comment by yujincheng08** [comment]
Send boot.img

**Comment by yujincheng08** [comment]
And please try artifacts of https://github.com/topjohnwu/Magisk/actions/runs/2001480153

**Comment by capntrips** [comment]
Here are the stock boot image and patched ones generated by 24305 and artifacts you linked:

[boot.img.gz](https://github.com/topjohnwu/Magisk/files/8425473/boot.img.gz)
[magisk_patched-24305_4qsnL.img.gz](https://github.com/topjohnwu/Magisk/files/8425469/magisk_patched-24305_4qsnL.img.gz)
[magisk_patched-24301_1skdS.img.gz](https://github.com/topjohnwu/Magisk/files/8425467/magisk_patched-24301_1skdS.img.gz)

Here is the /system/bin/init from `220305.013.a3` running on 24305:

[system-bin-init.gz](https://github.com/topjohnwu/Magisk/files/8425472/system-bin-init.gz)

I'm happy to pull the file from a different configuration.

I'm installing the April OTA using the artifacts now. I'll report back when it is done.

**Comment by yujincheng08** [comment]
Is  https://github.com/topjohnwu/Magisk/actions/runs/2001480153 still causing bootloop?

**Comment by capntrips** [comment]
The OTA is installing, but the optimizing step takes a while. I'll share the results when it is done.

**Comment by capntrips** [comment]
It hung at the Google logo. I let it sit for 5-10 minutes, but it never progressed and `adb` never connected. There was no `ramoops` after switching back to the previous slot.

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8426318/app-debug.zip)
How about this ver?

**Comment by capntrips** [comment]
An XDA member [suggested](https://forum.xda-developers.com/t/dev-eol-vbmeta-patcher-devinfo-patcher-and-boot-image-tool.4360405/post-86699069) the 24301 [build](https://github.com/vvb2060/magisk_files/tree/2ab37e5993d669708dbfa500635d2d83968eadf6) of Magisk Alpha, and it worked. I'll roll back to `220305.013.a3` and try the one you posted next.

**Comment by capntrips** [comment]
I tried to take a shortcut and switch back to the previous slot without directly flashing `220305.013.a3` and I got the red `eio` screen. I wonder if rolling back to the previous slot after failing to boot after the OTA is was caused it the times noted in the OP (in those cases I let it revert naturally, after bootlooping 3 times).

In any case, I had to flash `220405.004` to clear that message. I'm not back on `220305.013.a3` and am installing the OTA. I'll let you know if the build you posted above works when it is done.

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8428087/app-debug.zip)
Without ramoops it's hard to debug. Just add a `kill 1` to force the kernel to generate ramoops after 10s.

**Comment by capntrips** [comment]
No luck, that one hangs at the Google logo, as well.

**Comment by yujincheng08** [comment]
Try #5690?

**Comment by capntrips** [comment]
It worked. Let me know if you need me to run any more tests.

**Comment by c-stella** [comment]
@yujincheng08 
#5690 also fails on my device, but I've managed to connect adb while bootlooping, so I took logcat. Couldn't pull ramoops though. Can you maybe provide the ways to pull ramoops?
[logcat.log](https://github.com/topjohnwu/Magisk/files/8445371/logcat.log)
[magisk_patched-24305_0VBWp.img.gz](https://github.com/topjohnwu/Magisk/files/8445374/magisk_patched-24305_0VBWp.img.gz)

And just in case stock boot.img.
[boot.img.gz](https://github.com/topjohnwu/Magisk/files/8445378/boot.img.gz)

**Comment by Rodrigo19842010** [comment]
> Dispositivo: Pixel 6 Versão Android: 12.1 Nome da versão Magisk: https://github.com/topjohnwu/Magisk/releases/tag/v24.3 Código da versão Magisk: 24300
> 
> Confirme este problema no Magisk estável

**Comment by yujincheng08** [comment]
Fixed.
