### ISSUE TITLE
Doesn't Grant root access

### ISSUE THREAD

**Issue by Donad678** [topjohnwu/Magisk#569]
I can't get root access, my log message is:

09-05 01:58:34.062   319   319 I Magisk  : ** Initializing Magisk
09-05 01:58:34.063   319   319 I Magisk  : * Creating /sbin overlay
09-05 01:58:34.071   319   319 I Magisk  : * Mounting mirrors
09-05 01:58:34.073   319   319 I Magisk  : mount: /sbin/.core/mirror/system
09-05 01:58:34.073   319   319 I Magisk  : link: /sbin/.core/mirror/vendor
09-05 01:58:34.073   319   319 I Magisk  : bind_mount: /sbin/.core/mirror/bin
09-05 01:58:34.074   319   319 I Magisk  : * Setting up internal busybox
09-05 01:58:34.472   326   326 I Magisk  : Magisk v17.1(17100) logger started
09-05 01:58:34.473   322   322 I Magisk  : Magisk v17.1(17100) daemon started
09-05 01:58:34.482   322   328 I Magisk  : ** post-fs-data mode running
09-05 01:58:34.482   322   328 I Magisk  : Create /data/adb/magisk.img with size 64M
09-05 01:58:34.742   322   328 I Magisk  : * Mounting /data/adb/magisk.img
09-05 01:58:35.741   322   328 I Magisk  : * Running post-fs-data.d scripts
09-05 01:58:35.741   322   328 I Magisk  : * Running module post-fs-data scripts
09-05 01:58:35.741   322   328 I Magisk  : * Loading modules
09-05 01:58:35.747   322   344 I Magisk  : * Starting MagiskHide
09-05 01:58:35.747   322   344 I Magisk  : hide_utils: Hiding sensitive props
09-05 01:58:35.748   322   344 I Magisk  : hide_list add: [com.google.android.gms.unstable]
09-05 01:58:38.023   322   432 I Magisk  : ** late_start service mode running
09-05 01:58:38.027   322   432 I Magisk  : * Running service.d scripts
09-05 01:58:38.027   322   432 I Magisk  : * Running module service scripts
09-05 02:00:36.075   322   344 I Magisk  : proc_monitor: com.google.android.gms.unstable
09-05 02:01:18.622   322   344 I Magisk  : proc_monitor: com.google.android.gms.unstable
09-05 02:01:35.478  3497  3497 E Magisk  : select failed with 2: No such file or directory

**Comment by funnypro** [comment]
What happens after the terminal enters su  
~~辣鸡苟歌翻译~~

**Comment by cheetoslover** [comment]
i have the same issue after upgrading to v17.1 but at v16 works fine


09-05 17:31:18.403 I/ActivityManager(547): Process com.topjohnwu.magisk (pid 6315) has died
09-05 17:36:32.313 I/ActivityManager(547): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.SplashActivity bnds=[180,248][360,430] (has extras)} from uid 10101 on display 0
09-05 17:36:32.357 I/ActivityManager(547): Start proc 8341:com.topjohnwu.magisk/u0a75 for activity com.topjohnwu.magisk/.SplashActivity
09-05 17:36:32.457 W/System  (8341): ClassLoader referenced unknown path: /data/app/com.topjohnwu.magisk-1/lib/arm
09-05 17:36:33.575 I/ActivityManager(547): START u0 {cmp=com.topjohnwu.magisk/.MainActivity (has extras)} from uid 10075 on display 0
09-05 17:37:55.354 E/Magisk  (8546): select failed with 2: No such file or directory
09-05 17:38:16.664 E/Magisk  (8605): select failed with 2: No such file or directory
09-05 17:38:58.325 I/ActivityManager(547): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.SplashActivity bnds=[180,248][360,430] (has extras)} from uid 10101 on display 0
09-05 17:38:58.805 I/ActivityManager(547): Displayed com.topjohnwu.magisk/.MainActivity: +460ms
09-05 17:39:02.580 I/ActivityManager(547): Killing 8341:com.topjohnwu.magisk/u0a75 (adj 900): remove task
09-05 17:39:11.619 E/Magisk  (8697): select failed with 2: No such file or directory

**Comment by Donad678** [comment]
@funnypro when i enter su in terminal nothing happens, no root promt, no error message, no root access

**Comment by topjohnwu** [comment]
Duplicate #460
