### ISSUE TITLE
Unable to see magisk manager after install 

### ISSUE THREAD

**Issue by geminikj** [topjohnwu/Magisk#570]
Unable to see magisk manager after install

**Comment by geminikj** [comment]
[recovery.log](https://github.com/topjohnwu/Magisk/files/2351174/recovery.log)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/2351175/dmesg.log)

**Comment by Saranpornoil** [comment]
Comment on issue

**Comment by Saranpornoil** [comment]
about 2 hours ago

**Comment by geminikj** [comment]
When I try to install manually, installation fails, attached screenshot 
![screenshot_20180905-152124](https://user-images.githubusercontent.com/42990448/45085908-83e92f80-b11f-11e8-8bb3-9afd6aa5fcdc.jpg)

**Comment by funnypro** [comment]
Try to enter commands in the terminal first  
`pm install -r $magisk_apk_path`  
Then open a new terminal window input  
`logcat -v threadtime | grep apk`  
You should see some useful information later.

**Comment by funnypro** [comment]
$magisk_apk_path based on the actual apk location

**Comment by geminikj** [comment]
Tried as suggested, I get attached error from terminal Emulator, I downloaded this apk from github.com 
![screenshot_20180906-231246](https://user-images.githubusercontent.com/42990448/45175237-8d12f300-b22a-11e8-9701-a04bb741d403.jpg)

**Comment by funnypro** [comment]
@geminikj Android version?

**Comment by geminikj** [comment]
Android Version 8.1.0  on oneplus 6 
![screenshot_20180907-083540](https://user-images.githubusercontent.com/42990448/45196288-210bab80-b279-11e8-8d7f-844c93568c77.jpg)

**Comment by geminikj** [comment]
I just now upgraded to Android P, and still same issue

**Comment by topjohnwu** [comment]
I have an OnePlus 6, and it works just fine on my device.
There is something wrong with your system.

**Comment by geminikj** [comment]
I am able to install all other apk, unlocked bootloader and open beta 1 oxygen os rom, twrp, what could be wrong

Only this apk does not get installed..

**Comment by funnypro** [comment]
@geminikj pm clear com.topjohnwu.magisk
