### ISSUE TITLE
Configure Denylist Search Issues

### ISSUE THREAD

**Issue by zputnyq** [topjohnwu/Magisk#5717]
Device: Xperia M4 (E2306)
Android version: stocl 6.0.1
Magisk version name: 63a89d9f
Magisk version code: 24306

Hello all,

There are 2 issues on my device in search feature of configure denylist.
1. Typing in its search box seems a bit laggy, the typed letter(s) appear a bit longer.
2. About search result. The search result include some apps that doesn't belong to the keyword. -> no problem on this point, the word just truncated.

I attached screen shots & video for it

![Screenshot_20220411-211840](https://user-images.githubusercontent.com/31039796/162762061-9f1e02bb-da25-4ced-9853-52bd7432557d.png)
![Screenshot_20220411-211851](https://user-images.githubusercontent.com/31039796/162762163-9afe2da3-5913-481c-a318-b9a3f24c36f3.png)

https://user-images.githubusercontent.com/31039796/162762232-9708faca-dc6b-42b6-8a8d-66d294d4257e.mp4

**Comment by pndwal** [comment]
It's including processes... Have you checked for 'play' etc in processes for each item listed?...

**Comment by zputnyq** [comment]
> It's including processes... Have you checked for 'play' etc in processes for each item listed?...

Some have that process name & some not when I checked by tapping the item listed.

**Comment by pndwal** [comment]
Please say which Item(s) are in error...

All those I have in common w/ your screenshot have *play* in one or more processes, except Instagram but mine is 230.0.0.20.108, and I'm guessing yours is an earlier version with com.instagram.andriod.video**play**er or similar?

**Comment by zputnyq** [comment]
> 

It's according to magisk's list.
This apps don't have play process.
![Screenshot_20220412-205400](https://user-images.githubusercontent.com/31039796/162981832-8cf98653-db54-47a0-80da-1378acda4bfc.png)
![Screenshot_20220412-205349](https://user-images.githubusercontent.com/31039796/162981881-0902472f-a017-49e4-920f-44b1002a82fa.png)
![Screenshot_20220412-205133](https://user-images.githubusercontent.com/31039796/162981916-93118f07-127c-45d6-933c-64fe06ee1786.png)

Moreover scrolling down on processes list of app like chrome which has many list of process, display sometimes jump up & freeze.

For instagram, I'm using old version & yes it has the process you mentioned.

**Comment by pndwal** [comment]
I have maps and drive...
Maps has:com.google.android.apps.maps:**play**core_missing_splits_activity
Drive has:
com.google.android.apps.docs:**play**core_missing_splits_activity
You are seeing these, but truncated in portrait screen mode:
com.google.android.a...issing_splits_activity
Please try viewing in landscape screen mode...

Sorry, I can't comment on your lag / freezing issue. 🙂

**Comment by zputnyq** [comment]
> I have maps and drive... Maps has: com.google.android.apps.maps:**play**core_missing_splits_activity Drive has: com.google.android.apps.docs:**play**core_missing_splits_activity You are seeing these, but truncated in portrait screen mode: com.google.android.a...issing_splits_activity Please try viewing in landscape screen mode...
> 
> Sorry, I can't comment on your lag / freezing issue. 🙂

My apology. I don't know if they are truncated & able to be seen on lanscape mode.
Yes they all have the play word.

No problem

**Comment by yujincheng08** [comment]
expected behavior.
