### ISSUE TITLE
bootloop after flashing patch boot.img

### ISSUE THREAD

**Issue by ASIMKHAN222** [topjohnwu/Magisk#5720]
Device:  vivo s1
Android version: 11
Magisk version name: canary 27
Magisk version code: 24306

i flashed patch boot.img dump via mtk client with fastboot...after flash device stuck in bootloop ?
please Help
how can i get root access ? 

stock boot.img
[boot.zip](https://github.com/topjohnwu/Magisk/files/8476093/boot.zip)

magisk install log
[magisk_install_log_2022-04-13T00_47_37[1].log](https://github.com/topjohnwu/Magisk/files/8476125/magisk_install_log_2022-04-13T00_47_37.1.log)

**Comment by vporoxnenko** [comment]
the same shit with galaxy s10e. Magisk was updated and after reboot I'm in the loop

**Comment by canyie** [comment]
Please grab a kernel log when it bootloop like https://github.com/topjohnwu/Magisk/issues/5607#issuecomment-1072347395 and https://github.com/topjohnwu/Magisk/issues/5607#issuecomment-1072389939

**Comment by ASIMKHAN222** [comment]
> Please grab a kernel log when it bootloop

adb bugreport
[bugreport-1907-RP1A.200720.012-2022-04-14-13-16-24.zip](https://github.com/topjohnwu/Magisk/files/8487533/bugreport-1907-RP1A.200720.012-2022-04-14-13-16-24.zip)

**Comment by canyie** [comment]
The bugreport looks normal. Can you upload /sys/fs/pstore ?

**Comment by ASIMKHAN222** [comment]
> 

How to Get That? My device have not any compatible TWRP

**Comment by canyie** [comment]
I guess old versions was working on your device, maybe reinstalling the old one (so you get root) and extract that via adb?

**Comment by ASIMKHAN222** [comment]
> 

Actually Device was running on Android 10 after updating an OTA
 Device Got Android 11 version..

**Comment by yujincheng08** [comment]
She means old version of magisk...

**Comment by ASIMKHAN222** [comment]
> She means old version of magisk...

Oh,  BTW Device have separate Vbmeta Partition
 i also try to disable or flash empty vbmeta 
By these commands,
`fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
`Fastboot flash vbmeta vbmeta. Img. empty`

device Again start Bootloop
