### ISSUE TITLE
Bootloop after magisk update

### ISSUE THREAD

**Issue by vporoxnenko** [topjohnwu/Magisk#5722]
Magisk just updated itself and restarts the phone. After that I'm in bootloop

Device: Galaxy s10e
Android version: 11
Magisk version name: 24.306 (before update it was 22.000)
Magisk version code: 24306
[dmesg_.log](https://github.com/topjohnwu/Magisk/files/8476668/dmesg_.log)
[last_ksmg.log](https://github.com/topjohnwu/Magisk/files/8476669/last_ksmg.log)

**Comment by yujincheng08** [comment]
```
<12>[    1.921648]  [7:           init:    1] magiskinit: open: /.backup/init failed with 2: No such file or directory
<6>[    1.926568]  [7:           init:    1] EXT4-fs (sda26): Root reserved blocks 2816
<6>[    1.927782]  [7:           init:    1] New pool created id:0
<6>[    1.927868]  [7:           init:    1] EXT4-fs (sda26): mounted filesystem without journal. Opts: (null)
<6>[    1.928324]  [7:           init:    1] EXT4-fs (sda27): Root reserved blocks 1587
<6>[    1.929079]  [7:           init:    1] New pool created id:1
<6>[    1.929111]  [7:           init:    1] EXT4-fs (sda27): mounted filesystem without journal. Opts: (null)
<12>[    1.929171]  [7:           init:    1] magiskinit: lstat /sbin failed with 2: No such file or directory
<12>[    1.929203]  [7:           init:    1] magiskinit: open: /sbin failed with 2: No such file or directory
<12>[    1.929212]  [7:           init:    1] magiskinit: fdopendir failed with 9: Bad file descriptor
```

Looks like the boot is corrupted. Try to patch the boot again.

**Comment by vporoxnenko** [comment]
> ```
> <12>[    1.921648]  [7:           init:    1] magiskinit: open: /.backup/init failed with 2: No such file or directory
> <6>[    1.926568]  [7:           init:    1] EXT4-fs (sda26): Root reserved blocks 2816
> <6>[    1.927782]  [7:           init:    1] New pool created id:0
> <6>[    1.927868]  [7:           init:    1] EXT4-fs (sda26): mounted filesystem without journal. Opts: (null)
> <6>[    1.928324]  [7:           init:    1] EXT4-fs (sda27): Root reserved blocks 1587
> <6>[    1.929079]  [7:           init:    1] New pool created id:1
> <6>[    1.929111]  [7:           init:    1] EXT4-fs (sda27): mounted filesystem without journal. Opts: (null)
> <12>[    1.929171]  [7:           init:    1] magiskinit: lstat /sbin failed with 2: No such file or directory
> <12>[    1.929203]  [7:           init:    1] magiskinit: open: /sbin failed with 2: No such file or directory
> <12>[    1.929212]  [7:           init:    1] magiskinit: fdopendir failed with 9: Bad file descriptor
> ```
> 
> Looks like the boot is corrupted. Try to patch the boot again.

I did it with old 22.0 version, 24.300 and 24.306, still no success (

**Comment by yujincheng08** [comment]
send the stock boot.img and the patched one.

**Comment by vporoxnenko** [comment]
> send the stock boot.img and the patched one.

where can I get both of them? I guess I can get patched right from magisk zip file, correct?

**Comment by yujincheng08** [comment]
Read Magisk's installation guide.

**Comment by pndwal** [comment]
> > send the stock boot.img and the patched one.
> 
> where can I get both of them? I guess I can get patched right from magisk zip file, correct?

> Read Magisk's installation guide.

Can these be extracted from AP (Android Processor binary) tar files?... Or dump somehow?

**Comment by vporoxnenko** [comment]
> Read Magisk's installation guide.

if I understood correctly, It's required to patch stock img with magisk, but right now I can load only twrp, so idk how can I patch the boot.img. Actually I see twrp works under se-linux, so adb tools are not available there ((

**Comment by vporoxnenko** [comment]
> Dmesg grabbed in recovery mode is useless. Please grab a kernel log when it bootloop like [#5607 (comment)](https://github.com/topjohnwu/Magisk/issues/5607#issuecomment-1072347395) and [#5607 (comment)](https://github.com/topjohnwu/Magisk/issues/5607#issuecomment-1072389939)

I can't patch boot.img, as right now I can load twrp only

**Comment by pndwal** [comment]
> > Read Magisk's installation guide.
> 
> if I understood correctly, It's required to patch stock img with magisk, but right now I can load only twrp, so idk how can I patch the boot.img. Actually I see twrp works under se-linux, so adb tools are not available there ((

I think dev wanted a stock and a patched image from attempts above...
> I did it with old 22.0 version, 24.300 and 24.306, still no success (

These should be on your PC I guess, but seems she is assuming standard boot.img files, not Sammy AP tar files...
