### ISSUE TITLE
Pixel XL (marlin) + Android P - Stuck on Google logo and then reboot.

### ISSUE THREAD

**Issue by spleenandcigars** [topjohnwu/Magisk#573]
I was using Magisk in Android O for quite a while after discovering how to unlock the boot loader and had no issues whatsoever with any modules i tried there or at Xposed. After the the Android P came out, i was anxious to check out the final update and performed a factory reset (just to start fresh) and flashed the full factory image from Google website.... Then we get to the point i'm now.

No matter what order or procedure i try in TWRP to flash Magisk, it'll always be stuck at Google loading screen logo and after a minute or so it'll reboot into TWRP again. I tried clean install, flashing and leave it until it reboots 3 times into TWRP, flashing and cleaning cache, installing Magisk apk first and then flashing.... Anyway, here's the log:

This is my recovery.log: https://pastebin.com/C6vS7P4D
This is my dmesg.log (kernel): https://pastebin.com/Np1tFmmU

**Comment by topjohnwu** [comment]
I'm using Pixel XL on Android P as a daily driver. There is something wrong with your setup, not Magisk.

**Comment by spleenandcigars** [comment]
Weird... Even after a clean format it won't boot.
