### ISSUE TITLE
zgisk module acquisition problem

### ISSUE THREAD

**Issue by LarissaLycoris** [topjohnwu/Magisk#5730]
Device: Android 11
Android version:24.3
Magisk version name: zgisk
Magisk version code: 24306

Is there any way to get the context of the injected application in the 24 version of the zgisk version module? Now it seems that the context of the injected application cannot be obtained because the loading mechanism is too early. I want to create a window after obtaining the context when opening the injected application. Thanks, give me an idea.

Chinese->
请问24版本的zgisk版本模块 有什么办法可以获取注入应用的上下文呢？现在好像因为加载机制太早了导致无法获取注入应用的上下文，我想打开注入应用的时候获取到上下文以后创建窗口。感谢，提供个思路也可以的.

**Comment by canyie** [comment]
你可以通过 java hook、binder hook、native hook 等方式等到 context 被创建出来后再反射获取，甚至可以开个线程不停反射轮询 context。

**Comment by canyie** [comment]
zygisk 自带了一个 got hook 的 api，如果满足不了需求请自行引入其他 hook 框架处理。

**Comment by LarissaLycoris** [comment]
> zygisk 自带了一个 got hook 的 api，如果满足不了需求请自行引入其他 hook 框架处理。

好的，谢谢你回复我

**Comment by LarissaLycoris** [comment]
> zygisk 自带了一个 got hook 的 api，如果满足不了需求请自行引入其他 hook 框架处理。

 还有一个小问题->    env->FindClass就会导致被注入应用卡死是咋回事捏

**Comment by LarissaLycoris** [comment]
> zygisk 自带了一个 got hook 的 api，如果满足不了需求请自行引入其他 hook 框架处理。

![T$ 05WFYJ%_QDM`8H{$0NSY](https://user-images.githubusercontent.com/99528736/163145574-b16ef97c-88d7-4124-91d0-2c4c8f13b6f6.png)

这样写有问题么api
