### ISSUE TITLE
[App] Biometric Authentication causes broken pipe error

### ISSUE THREAD

**Issue by outis151** [topjohnwu/Magisk#5736]
When using Biometric Authentication for superuser requests the dialog box freezes after selecting the "Grant" button.
The following error appears in the magisk log every time this happens:
`E : write failed with 32: Broken pipe`

Usually the second dialog box that appears after that works fine.

Device: OnePlus 5
Android version: 11
Magisk version name: 24.3
Magisk version code: 24306

**Comment by vvb2060** [comment]
No log and cannot be reproduced
