### ISSUE TITLE
selinux hijack with fifo somtimes stuck forever

### ISSUE THREAD

**Issue by ychuang1029** [topjohnwu/Magisk#5742]
Device:  vivo x30
Android version: 10
Magisk version name:  24306
Magisk version code: 24306

![image](https://user-images.githubusercontent.com/16041820/163530621-d2b2b53e-eeb2-401f-8691-4fce4a253b2e.png)

![image](https://user-images.githubusercontent.com/16041820/163530884-f75785f4-fa98-47fe-8674-2af4a51b5e15.png)

The execution sequence is as follows:
1) init: mkfifo MOCK_LOAD
2) init: bind MOCK_LOAD to "/sys/fs/selinux/load"
3) init: fork child without wait, continue to load selinux policy
4) init: open "/sys/fs/selinux/load" with O_RDWR, fifo with O_RDWR will always return immediately.
5) init: write and close "/sys/fs/selinux/load"
6) child: open MOCK_LOAD with O_RDONLY，waiting for writer，but there will be no writer anymore, stuck forever.

my test code:
```c
int main(int argc, char* argv[])
{
	unlink("load");
	mkfifo("load", 0666);
	int pid = fork();
	if (pid < 0)
	{
		return pid;
	}
	if (pid > 0)
	{
		// parent
		printf("parent: writing to load...\n");
		//sleep(2);
		int fd = open("load", O_RDWR);
		if (fd < 0)
		{
			printf("parent: open load fail errno=%d\n", errno);
			return fd;
		}
		write(fd, "test", 4);
		close(fd);
		printf("parent: write to load done\n");
		return 0;
	}
	// child
	sleep(2);
	printf("child: reading from load...\n");
	int fd = open("load", O_RDONLY);
	if (fd < 0)
	{
		printf("child: open load fail errno=%d\n", errno);
		return fd;
	}
	char buffer[16];
	int ret = read(fd, buffer, sizeof(buffer) - 1);
	if (ret > 0)
	{
		buffer[ret] = 0;
		printf("child: %s\n", buffer);
	}
	close(fd);
	return 0;
}
```

**Comment by yujincheng08** [comment]
those are for android 8-9. For android 10, ld_preload is used. so this issue is invalid.

**Comment by ychuang1029** [comment]
whatever, even it is for android 8-9, hijack_sepolicy still has same problem

**Comment by ychuang1029** [comment]
I already found this problem in my device, the issue is very real...

**Comment by ychuang1029** [comment]
![image](https://user-images.githubusercontent.com/16041820/163563317-f431884b-ca45-4a5e-86af-466cfeaf55fb.png)
even use preload, you are still call the security_load_policy from /system/lib64/libselinux, which will opening fifo with O_RDWR, then there will be small chance to stuck.

**Comment by canyie** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/31466456/163584980-f41d92dd-d25b-4ad5-a95b-f86d119ccdbf.png)
![image](https://user-images.githubusercontent.com/31466456/163585013-a982d744-39d4-4a50-8cdf-365f4b03159c.png)
> Under Linux, opening a FIFO for read and write will succeed both
       in blocking and nonblocking mode.  POSIX leaves this behavior
       undefined.  This can be used to open a FIFO for writing while
       there are no readers available.  A process that uses both ends of
       the connection in order to communicate with itself should be very
       careful to avoid deadlocks.

> (Linux-specific:) If you open on the reading side with O_RDWR, then:
The open() will not block.
poll() will give a POLLIN revent when data is ready to be read. However, for named pipes, EOF will not cause POLLIN or POLLHUP revents.
read() will block until the requested number of bytes is read, it is interrupted by a signal, or some other fatal IO error occurs. For named pipes, it will not return errno == EAGAIN, nor will it even return 0 on EOF. It will just sit there until the exact number of bytes requested is read, or until it receives a signal (in which case it will return the number of bytes read so far, or return -1 and set errno == EINTR if no bytes were read so far).
If the writer closes, the reader will not lose the ability to read the named pipe later if another writer opens the named pipe, but the reader will not receive any notification either.

**Comment by yujincheng08** [comment]
@canyie If the buffer of the fifo is full, writing will be blocked until the reader consumes the content. So the problem is that the policy is too small...

**Comment by yujincheng08** [comment]
Anyway, `load` does not need to be fifo now. Simply a tmpfs file should be enough for the hijacking.

**Comment by vvb2060** [comment]
> write(fd, "test", 4);

Try to exceed buffer (cat /proc/sys/fs/pipe-max-size)

**Comment by ychuang1029** [comment]
> 

It is unreliable to rely on the CPU execution order to ensure that the code is executed correctly. Who knows what happens to the user's machine

**Comment by vvb2060** [comment]
所以光速虚拟机做了什么让它坏掉了呢？
毕竟需要同时满足 
1. sepolicy小于4096 bytes 
2. 卡住magisk fork后到open MOCK_LOAD前的执行流
才能触发你描述的问题

**Comment by canyie** [comment]
c2b74aa
