### ISSUE TITLE
"Permission denied" records in the log

### ISSUE THREAD

**Issue by vpolinov** [topjohnwu/Magisk#5750]
Device: Realme C25s
Android version: 11
Magisk version name: Canary
Magisk version code: 24306
No modues installed

Magisk patches stock boot just fine. Device boots with flashed patched boot.img also fine.  No crashes, no bootloops.
However, I can see a lot of "unlock dm-xx failed with 13: Permission denied" records in magisk log which does not seem to me to be correct.

The names of partitions where "deny access" happens and which are listed in the log, are parts of SUPER partition:

dm-4 (my_manifest)
dm-5 (my_preload)
dm-8 (my_stock)
dm-3 (my_heytap)
dm-7 (my_region)
dm-0 (my_carrier)
dm-1 (my_company)
dm-2 (my_engineering)
dm-6 (my_product)
dm-9 (odm)
dm-10 (product)
dm-12 (vendor)
dm-11 (system)

I cannot mount any of above partitions for RW access.

Attached are:
- magisk log
- stock version of boot.img
- magisk patched boot.img

[magisk_log_2022-04-17T12_54_11.log](https://github.com/topjohnwu/Magisk/files/8501446/magisk_log_2022-04-17T12_54_11.log)
[boot.A.18.stock.img.zip](https://github.com/topjohnwu/Magisk/files/8501447/boot.A.18.stock.img.zip)
[boot.A.18.magisk_canary.24306.img.zip](https://github.com/topjohnwu/Magisk/files/8501448/boot.A.18.magisk_canary.24306.img.zip)

If described above behaviour is normal, I'd be grateful for someone to confirm it.

**Comment by yujincheng08** [comment]
Expected for MTK devices.
