### ISSUE TITLE
`com.topjohnwu.signing.SignBoot` does not exist when signing boot

### ISSUE THREAD

**Issue by some6508** [topjohnwu/Magisk#5753]
Device: Redmi K40
Android version: 12
Magisk version name: Canary
Magisk version code: 24306

### There is a problem with the `BOOTSIGNERCLASS=com.Topjohnwu.Signing.SignBoot` variable in `util_functions.sh`. Magisk.apk does not have this class.
````
Unable to locate class 'com/topjohnwu/signing/SignBoot'
java.lang.ClassNotFoundException: com.topjohnwu.signing.SignBoot
Exception in thread "main" java.lang.ClassNotFoundException: com.topjohnwu.signing.SignBoot
````

**Comment by pndwal** [comment]
A singing boot? - I have two squeeky ones! 😁

**Comment by pndwal** [comment]
Please hide this again if you like, but title still says "... singing boot"! 😜...
Might want to fix it...
