### ISSUE TITLE
LineageOS 19 Bootloop

### ISSUE THREAD

**Issue by mako123456** [topjohnwu/Magisk#5770]
Device: Pixel 5
Android version: 12 (LineageOS, 19-20220427)
Magisk version name: 63a89d9f
Magisk version code: 24306

Hello everyone, after Update my device from Lineageos 18 to 19 (android 12) i tried reinstall / root my device with Magisk again.  After flashed the patched boot.img, my device bootlooped at several trys. When I flashed the boot.img from the installed lineageos, it returns to normal. I have also tried the "old way", to rename the .apk to .zip an install it with sideload, same result.

Here I uploades the /proc/mounts (normal boot with lineage img), the original boot.img and the magisk_patched.img
[proc_mounts.txt](https://github.com/topjohnwu/Magisk/files/8584797/proc_mounts.txt)
[magisk_patched.img.zip](https://github.com/topjohnwu/Magisk/files/8584798/magisk_patched.img.zip)
[boot.img.zip](https://github.com/topjohnwu/Magisk/files/8584799/boot.img.zip)

Thanks!

**Comment by canyie** [comment]
Upload `/sys/fs/pstore` in TWRP after bootloop?
And grab a bugreport if that folder is empty? Guide: https://github.com/topjohnwu/Magisk/issues/5607#issuecomment-1072347395

**Comment by mako123456** [comment]
Bugreport attached 
no TWRP install, used recovery file for install lineage
[bugreport-redfin-SP2A.220405.004-2022-04-29-06-58-03.zip](https://github.com/topjohnwu/Magisk/files/8588231/bugreport-redfin-SP2A.220405.004-2022-04-29-06-58-03.zip)

**Comment by canyie** [comment]
```
pid: 7715, tid: 7715, name: system_server  >>> zygote64 <<<
uid: 1000
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'Executing untrusted code from /data/dalvik-cache/arm64/system@framework@services.jar@classes.dex'
```
Try removing the `spoof_AVDapi30` module? Flashing Magisk and reboot, your device will go into bootloop but you should able to take an adb connection. You can `touch /data/adb/modules/spoof_AVDapi30/disable` via `adb shell` with root, and reboot.
