### ISSUE TITLE
After Magisk 17.1 on OnePlus3, GooglePay won't let me pay.

### ISSUE THREAD

**Issue by max01986** [topjohnwu/Magisk#578]

**Comment by grest** [comment]
Same problem on Xperia Z2 (Sirius)

**Comment by rote66** [comment]
Same problem on Sharp 507sh （Android one）

**Comment by topjohnwu** [comment]
Working fine for me, there might be something wrong with your setup that breaks SafetyNet.

**Comment by grest** [comment]
@topjohnwu, any hints what may be wrong with the setup? Or how to debug it?
