### ISSUE TITLE
Help what is this

### ISSUE THREAD

**Issue by cleycley** [topjohnwu/Magisk#5784]
Device: Samsung galaxy A51
Android version: 11
Magisk version name: 63a89d9f
Magisk version code: 24306
![Screenshot_20220501-143127](https://user-images.githubusercontent.com/94766648/166152359-576789e6-ddb5-4a03-8710-bcd040a6af9f.jpg)

**Comment by cleycley** [comment]
this happened after i updated the app

**Comment by canyie** [comment]
If you don't know how to resolve it, please ask questions on XDA, instead of just spamming our email with 6 issues thanks 🙏

**Comment by cleycley** [comment]
> 

I didn't send any spam, I just didn't know how to post here yet, and I was trying, I just want to be able to solve this problem, more education please

**Comment by HuskyDG** [comment]
> > 
> 
> I didn't send any spam, I just didn't know how to post here yet, and I was trying, I just want to be able to solve this problem, more education please

What the heck you move Magisk app to system??
