### ISSUE TITLE
magisk --remove-modules did not work

### ISSUE THREAD

**Issue by Jon8RFC** [topjohnwu/Magisk#5788]
Device: Pixel 6 Pro
Android version: SP2A.220505.002
Magisk version name: cc79a96f
Magisk version code: 24307

Upon encountering a bootloop after updating Android from April 2022 to May 2022, running `adb wait-for-device shell magisk --remove-modules` would, in fact, immediately reboot the phone, but the modules were not removed and the phone would still bootloop.  I tried it multiple times.

I know that magisk was not removing/disabling the modules because I successfully went into safe mode, which disabled all of the modules.  I was able to reboot into regular, non-safe mode android, delete the suspected culprit module, enable all others, and reboot successfully.  I tried `adb wait-for-device shell magisk --remove-modules` numerous times during multiple reboots before ever trying safe mode.  I'd guess that I tried about 15 separate times on 15 separate bootloop occurrences.

The culprit module was created using [smali patcher](https://forum.xda-developers.com/t/module-smali-patcher-7-4.3680053/).  It was created while my phone was on android April 2022 didn't work after the update to android May 2022, and I had to recreate it.  It works fine on May 2022 after I recreated a new module.

Here is the module which caused the bootloop (or somehow disallowed the magisk command from working) _after updating to android May 2022_:  
[SmaliPatcherModule_april22.zip](https://github.com/topjohnwu/Magisk/files/8628531/SmaliPatcherModule_april22.zip)
Here is the new module I recreated which causes no issues whatsoever:
[SmaliPatcherModule_may22.zip](https://github.com/topjohnwu/Magisk/files/8628532/SmaliPatcherModule_may22.zip)

I actually encountered this on 24306 (and I also tested a 24300 magisk-patched boot.img out of desperation) and forgot to report it.  I really don't want to risk having to go through the arduous process of safe mode changing settings and undoing so many things if `adb wait-for-device shell magisk --remove-modules` doesn't work in 24307.  I don't have a spare device to test on. EDIT:  actually, I can't _properly_ test, either, until the June 2022 update, IF the module fails again then.

Your test scenario may not be able to properly replicate this issue if you merely install the module and reboot, if it's the module somehow disallowing the command from functioning, depending on how magisk's boot process works while enabling modules alongside android and loading modules.  I was successfully using the module--I was booted successfully into android--until I dirty flashed the android factory image update (and also installed the magisk patched boot.img) and went from android April 2022 to android May 2022.  So if the way magisk functions would preempt the same failure, your test device needs to have _already_ enabled and successfully booted with the "bad module" on April 2022, and then dirty flash the May 2022 factory image with a magisk-patched boot.img.
When I was stuck in the bootloop, magisk wasn't ever trying to enable any new modules.  That's my concern if there isn't a readily-apparent bug with the command not working under the conditions of a module bootloop during a system update in which the module was already functioning prior to the system update.

I used both commands during my attempts:
`adb shell magisk --remove-modules`
and then after thinking I wasn't entering it quickly enough (it failed if the phone wasn't detected yet), I tried:
`adb wait-for-device shell magisk --remove-modules`

**Comment by vvb2060** [comment]
https://source.android.com/devices/tech/ota/user-data-checkpoint

All writes to the data partition will be undone until the device is successfully booted. It is not recommended to use this command, always disable modules via safe mode.
