### ISSUE TITLE
Magisk forgets previous root requests with lsposed enabled

### ISSUE THREAD

**Issue by UltraBlackLinux** [topjohnwu/Magisk#5798]
Hey there,
I have an issue that I hope complies with the rules:
Whenever having LSposed enabled, Riru or Zygisk both cause this issue, Magisk fails to remember all root requests and restarting the phone results in me being spammed with root requests, which get denied even though I have Magisk set to automatically grant all root requests. The list is just always empty.
Is this an LSposed issue? If yes, why can it even cause this?
Thanks!

Device: cheryl
Android version: 12
Magisk version name: 42e5f51
Magisk version code: 24308

(Please be kind, bot)

**Comment by pndwal** [comment]
Have you tried this with all XPosed modules disabled?

**Comment by vvb2060** [comment]
Show You Applist

**Comment by UltraBlackLinux** [comment]
> Show Your Applist

https://github.com/kdrag0n/android12-extensions This is all I am using. This shouldn't interfere with Magisk

**Comment by UltraBlackLinux** [comment]
> Have you tried this with all XPosed modules disabled?

Same thing, as expected.

**Comment by UltraBlackLinux** [comment]
@vvb2060 Please reopen this, it's not fixed yet :/
