### ISSUE TITLE
Viper4Android Module Causing Phone not to boot Nexus 6p

### ISSUE THREAD

**Issue by Nubston** [topjohnwu/Magisk#58]
Nexus 6p PureNexus 7.1.1 Flash Kernal

As the title says when i install Viper4Android from your repo i just end up in constant boot state  till the battery runs out have to run magisk uninstaller to get phone to boot again

**Comment by ooshkamils515** [comment]
Same issue here.  It looks like the entire /vendor partition is being replaced with only the files from the mod.  Both /vendor and /system/vendor are empty, except for the mod's files.  Logcat: http://pastebin.com/hfByxbHw  Downgrading back to Magisk 10.2 everything works fine.

**Comment by sjanello** [comment]
Using ARISE4Magisk2.92.zip, phone will boot but it sticks at the "Google" post screen for 30s before booting normally. Nexus 6p, Pure Nexus, Elemental X kern. Vendor folders look fine on my device.

**Comment by Zackptg5** [comment]
The ARISE4Magisk modules are different from this v4a module so try to keep that on the xda thread or telegram channels for arise sound systems. As for the vendor issues, they were just fixed in magisk v11.5 so maybe it'll work now?

**Comment by ooshkamils515** [comment]
Fixed here!

**Comment by ooshkamils515** [comment]
Spoke too soon, the phone will now boot, but the mods files in /vendor/ are not mounting at all now

**Comment by Zackptg5** [comment]
I think the update magisk update was pulled for having some issues so hopefully it'll be fixed in the next one

**Comment by ooshkamils515** [comment]
Ok so with 11.6 and the latest Viper4Android 2.5.0.5 the mounting issue is fixed.  The mod doesn't actually work, as in the viper driver can't be found, but I think that's a separate issue.

**Comment by topjohnwu** [comment]
Those are selinux issues, need more audit logs
You can set to permissive, it shall work
