### ISSUE TITLE
Failed to open Magisk app

### ISSUE THREAD

**Issue by CharlotteFallices** [topjohnwu/Magisk#5808]
Not crashed, just didn't respond :(
![Screenshot_20220508-204808.png](https://user-images.githubusercontent.com/47619464/167297081-26bd3d6c-448e-4ca5-a1ef-a7f1e8c8e277.png)
Device: Pixel 6p
Android version:13b1
Magisk version name: 24.3
Magisk version code: 24308

**Comment by canyie** [comment]
#5787
