### ISSUE TITLE
Magisk app after hide it stuck on logo

### ISSUE THREAD

**Issue by skelletR** [topjohnwu/Magisk#5809]
Hi, I have latest canary version, all working, but when try hide the magisk app, when hide it and open just stuck on logo nothing else, and delete it and install again the magisk without problem but can't hide it, and this happen and in the previous version 24307, in 24306 work

Device: Sony Xperia Z5
Android version:7.1.1
Magisk version name: 42e5f515
Magisk version code: 24308

**Comment by zputnyq** [comment]
Probably this #5574

**Comment by skelletR** [comment]
How do it this work in my phone? I try it again, just hide it with name( setting) and open and stuck in l
[magisk_log.log](https://github.com/topjohnwu/Magisk/files/8654553/magisk_log.log)
ogo
![Screenshot_20220509-214111](https://user-images.githubusercontent.com/25982450/167478802-9adf79d4-6dc7-4354-a0ae-1b5f5e7c8dc2.png)

**Comment by vvb2060** [comment]
Duplicate of #5787
