### ISSUE TITLE
Downloading Magisk zip securely

### ISSUE THREAD

**Issue by soaringowl2145** [topjohnwu/Magisk#581]
Is there currently a way to verify the checksum and/or signature of the Magisk zip that is downloaded from xda?

If not can we please have the zips signed and/or checksums released with the zip to make sure the download has not been corrupted and/or tampered with?

Thank you!

**Comment by sjayminsgithub** [comment]
Use the latest Magisk Manager, that already checks the checksums of downloaded zips and if they don't match, re-downloads the zip.
This issue should be closed to let others be in focus.
Best regards.

**Comment by soaringowl2145** [comment]
Suppose you do not already have it installed and are downloading for the first time.  How would you check it then?

**Comment by vvb2060** [comment]
#408
