### ISSUE TITLE
Enabling Zygisk causes bootloop on Samsung Galaxy S8

### ISSUE THREAD

**Issue by rhavish** [topjohnwu/Magisk#5810]
Device: Samsung Galaxy S8 SM-G950F Exynos
Android version: 8
Magisk version name: Canary
Magisk version code: 42e5f515 (24308)

The kernel version is 4.4.111.

Hi, I'm unable to enable Zygisk and reboot my device without ending up in a bootloop. This happens with zero modules installed and I've tested it from a fresh install of Magisk with no settings changed except Zygisk.

I did search around and wonder if it's related to [#5395](https://github.com/topjohnwu/Magisk/issues/5395) but thought I should be ok as my kernel is above 3.19.

I've included bootlogs from when it failed:
[boot.log](https://github.com/topjohnwu/Magisk/files/8655330/boot.log)
[boot_2.log](https://github.com/topjohnwu/Magisk/files/8655735/boot_2.log)

**Comment by canyie** [comment]
In your log I cannot find anything about zygote, try to grab a new one with `adb logcat`? 🤔

**Comment by rhavish** [comment]
Sorry about that, not sure why it didn't work correctly. Here's the logcat file:
[logcat.txt](https://github.com/topjohnwu/Magisk/files/8658601/logcat.txt)

Happy to grab more logs if needed, thanks for looking at this.

**Comment by canyie** [comment]
Did you turn on Zygisk? The log looks normal

**Comment by rhavish** [comment]
My mistake, I think I captured the previous log just after switching it on. Here's the log the captures it being toggled on:
[logcat.txt](https://github.com/topjohnwu/Magisk/files/8658674/logcat.txt)

**Comment by canyie** [comment]
You still don't enable Zygisk... Grab log when it goes into bootloop
And it's seems you have Xposed installed, try to uninstall Xposed and try again?

**Comment by rhavish** [comment]
Sorry, I didn't realise Xposed was even installed. I thought I had removed it previously but it must have failed. Once I removed it, Zygisk was enabled with no problems.

Thanks very much for flagging that Xposed was still installed, I wouldn't have figured that out myself.

**Comment by PaulPintang** [comment]
What do you think why it's conflicting when Xposed installed?
