### ISSUE TITLE
pixel3axl with lineageos_19.1_20220507 bootloop after install magisk24.3  Device: Google Pixel 3A XL Android version: 12 lineage-19.1-20220507-nightly-bonito-signed.zip Magisk version name: 24300 Magisk version code: 24300  below is dmesg.log and cat.log without root https://drive.google.com/drive/folders/1M2pw89DViZegDYrPFzHOr1Qdn0uyCTEe?usp=sharing

### ISSUE THREAD

**Issue by designanalog** [topjohnwu/Magisk#5815]
pixel3axl with lineageos_19.1_20220507 bootloop after install magisk24308

Device: Google Pixel 3A XL
Android version: 12 lineage-19.1-20220507-nightly-bonito-signed.zip
Magisk version name: 24308
Magisk version code: 24308

below is dmesg.log and cat.log without root
https://drive.google.com/drive/folders/1M2pw89DViZegDYrPFzHOr1Qdn0uyCTEe?usp=sharing

**Comment by canyie** [comment]
![image](https://user-images.githubusercontent.com/31466456/167887570-37241a96-48a0-45d5-9b5d-ba9fbbf522f2.png)
Do you know what is Canary build?

**Comment by designanalog** [comment]
i did not know what is Canary build
and i did not know where to download it

**Comment by designanalog** [comment]
i did not know what is Canary build
and i did not know where to download it
