### ISSUE TITLE
Props replacing issue

### ISSUE THREAD

**Issue by xzr467706992** [topjohnwu/Magisk#582]
Device: ZUK Z2
ROM: Pie-semi-gsi
Magisk version: 17.1

I did this when the issue happened:
-Reboot
-Boot completed (at lockscreen now)
-Do nothing for some minutes
-Unlock
-Nothing replaced

But if i do this,everything is fine.
-Reboot
-Boot completed (at lockscreen now)
-Unlock immediately
-Everything is fine

Please look into it

**Comment by topjohnwu** [comment]
Most likely something to do with FBE encryption, nothing Magisk related.

**Comment by xzr467706992** [comment]
@topjohnwu I didnt enable that:joy:
