### ISSUE TITLE
Android 12L x86_64 cannot `direct install (recommended)`

### ISSUE THREAD

**Issue by 1457384613gh** [topjohnwu/Magisk#5821]
Device: Android Generic Device
Android version: Android 12L x86_64 beta
Magisk version name: 42e5f515(24308)
Magisk version code: 42e5f515(24308)(28)

There is an Android 12L x86_64 beta with kernel-SU.
But it cannot `direct install (recommended)`.
And it cannot patch `kernel` and `initrd.img`, DIRECTLY.

![Screenshot_20220512-112624](https://user-images.githubusercontent.com/69227436/167986848-c62b1b32-cfa1-48b6-b235-c9d376ee5ce8.png)
![Screenshot_20220512-112632](https://user-images.githubusercontent.com/69227436/167986861-caea6cba-d213-4b8a-866c-146170a86ba9.png)
![Screenshot_20220512-112639](https://user-images.githubusercontent.com/69227436/167986868-0484aa4c-0990-40f3-92da-d3a4eabf3368.png)

Please update it to be able to patch `kernel` and `initrd.img` DIRECTLY and to `direct install (recommended)` for Android x86.
You can release two packages.

- One is `magisk-arm64.apk` for mobile phones and pads with android arm installed, which can patch `boot.img`.

- Another is `magisk-x86_64.apk` for PCs with Android x86 installed, which can patch `kernel` and `initrd.img`, DIRECTLY.

Here the link of the OS is,
https://sourceforge.net/projects/blissos-dev/files/Android-Generic/PC/aosp/gapps/12L/

**Comment by HuskyDG** [comment]
https://github.com/huskydg/initrd-magisk

**Comment by 1457384613gh** [comment]
> https://github.com/huskydg/initrd-magisk

OK, I get it.
I have been seeing a `initrd.img` edited by you.
By the way, I have another question about `initrd.img` to ask.
I want to set a f2fs partition as `/data`.
So I set `DATA=/dev/block/sda3` by editing grub.
If sda3 is ext4, it will run successfully.
If sda3 is f2fs, f2fs v1.14, it will still remain LOGO, and cannot enter the desktop.
And then I check, only to find that there is no `mount.f2fs` in `initrd.img/sbin` and `/system/bin`.
But there is more than nothing into f2fs.
At least, there is `Android/data/com.xxxx` in f2fs.
So f2fs could be written, but cannot be mounted.
You know so much about initrd.img.
So could you give me a `mount.f2fs` to make me copy into `initrd.img/sbin` and /system/bin.
Or if only you could give another better way to mount a f2fs partition, f2fs v1.14, as `/data`!

**Comment by HuskyDG** [comment]
> > https://github.com/huskydg/initrd-magisk
> 
> OK, I get it. I have been seeing a `initrd.img` edited by you. By the way, I have another question about `initrd.img` to ask. I want to set a f2fs partition as `/data`. So I set `DATA=/dev/block/sda3` by editing grub. If sda3 is ext4, it will run successfully. If sda3 is f2fs, f2fs v1.14, it will still remain LOGO, and cannot enter the desktop. And then I check, only to find that there is no `mount.f2fs` in `initrd.img/sbin` and `/system/bin`. But there is more than nothing into f2fs. At least, there is `Android/data/com.xxxx` in f2fs. So f2fs could be written, but cannot be mounted. You know so much about initrd.img. So could you give me a `mount.f2fs` to make me copy into `initrd.img/sbin` or `/system/bin`?. Or if only you could give another better way to mount a f2fs partition, f2fs v1.14, as `/data`!

send me `initrd.img` from Android 12L x86_64 beta

**Comment by 1457384613gh** [comment]
I have already installed by `Magisk.Terminal.Emulator.apk`.
![(GF 3T0R)TZOM)W4HG9`KFG](https://user-images.githubusercontent.com/69227436/168457436-97e90b73-5195-4677-9ea8-e4f1fc09bafe.png)


Here it is, [initrd.zip](https://github.com/topjohnwu/Magisk/files/8694308/initrd.zip)

**Comment by HuskyDG** [comment]
> * I have already installed by using `Magisk.Terminal.Emulator.apk`.
> 
> ![(GF 3T0R)TZOM)W4HG9`KFG](https://user-images.githubusercontent.com/69227436/168457436-97e90b73-5195-4677-9ea8-e4f1fc09bafe.png)
> 
> # Here it is, [initrd.zip](https://github.com/topjohnwu/Magisk/files/8694308/initrd.zip)
> Thank you very much for your early reply and how earnest you are!​

Android x86 project doesn't support f2fs filesystem for now

**Comment by 1457384613gh** [comment]
> Android x86 project doesn't support f2fs filesystem for now

What a pity!
But thank you!

**Comment by hmtheboy154** [comment]
> > Android x86 project doesn't support f2fs filesystem for now
> 
> What a pity! But thank you!

Get busybox on Magisk and then try to `busybox modprobe f2fs`
There might be a chance that the fs got compiled as a module

**Comment by 1457384613gh** [comment]
> busybox modprobe f2fs

I'm sorry but I have never used busybox, yet.
I don't know how to operate.
Could you send links about how to use busybox?
I will try to understand.

**Comment by hmtheboy154** [comment]
Just type the command that I gave with root and then check with `cat /proc/filesystems`

**Comment by 1457384613gh** [comment]
![Screenshot_20220515-163004.png](https://user-images.githubusercontent.com/69227436/168464081-9dc02413-21bd-4e86-862c-ed3c280c2c5b.png)

**Comment by HuskyDG** [comment]
> ![Screenshot_20220515-163004.png](https://user-images.githubusercontent.com/69227436/168464081-9dc02413-21bd-4e86-862c-ed3c280c2c5b.png)
> 
> There is no f2fs. But there is `f2fs.ko` in kernel.



> ![Screenshot_20220515-163004.png](https://user-images.githubusercontent.com/69227436/168464081-9dc02413-21bd-4e86-862c-ed3c280c2c5b.png)
> 
> There is no f2fs. But there is `f2fs.ko` in kernel.

try running `busybox modprobe f2fs` as @hmtheboy154 said

**Comment by 1457384613gh** [comment]
![Screenshot_20220520-184824](https://user-images.githubusercontent.com/69227436/169514360-aabd69bb-03cf-4a08-b9d2-ea6da8d27c63.png)
