### ISSUE TITLE
[Feature request] Disable direct install on FireOS devices

### ISSUE THREAD

**Issue by tsynik** [topjohnwu/Magisk#5829]
Magisk used on many FireOS devices for root and more.
It's TWRP recovery need to rewrite itself into kernel after any boot image flash, so Magisk installed and works fine when flashed from recovery. But after direct install / update from system and Magisk Manager itself device become completely unbootable and it required even apply short-pin NAND unlock again. So many users broke their devices with Magisk update.
Is there a way to disable direct Magisk install from Manager for fireos devices? I can provide additional info and system properties to implement this feature. Thanks!

Device: Fire TV 4K
Android version: 7.1.2
Magisk version name: 24310
Magisk version code: 24310

**Comment by romhacks** [comment]
Relevant link for FireOS rooting that mentions this: https://forum.xda-developers.com/t/unlock-root-twrp-unbrick-fire-hd-8-2018-karnak-amonet-3.3963496/

**Comment by vvb2060** [comment]
> Don't flash boot/recovery images from FireOS (FlashFire, MagiskManager etc.)

**Comment by tsynik** [comment]
Relevant link for FireOS rooting that mentions this - but many user as granprents never readed those links and broked their devices by accidenal update.

> Relevant link for FireOS rooting that mentions this: https://forum.xda-developers.com/t/unlock-root-twrp-unbrick-fire-hd-8-2018-karnak-amonet-3.3963496/

Relevant link for FireOS rooting that mentions this - but many user as granprents never readed those links and broked their devices by accidenal update.

> Don't flash boot/recovery images from FireOS (FlashFire, MagiskManager etc.)

It doesn't mean we can't block this action on client side.
