### ISSUE TITLE
Freezing on boot logo (before actually booting android) after installing patched boot.img

### ISSUE THREAD

**Issue by furopi** [topjohnwu/Magisk#5832]
Device: Xiaomi Mi 11 (venus)
Android version: 12 (MIUI 13)
Magisk version name: Magisk Canary
Magisk version code: 24310

Hi,

I keep getting freezes after installing the patched boot.img via fastboot. My device was rooted perfectly fine with Magisk Alpha before, but I updated to the latest xiaomi.eu weekly ROM and I can't get it up and running anymore. Any chance I could get some help here?

Thank you!

**Comment by canyie** [comment]
Send `/sys/fs/pstore` when it bootloops?

**Comment by furopi** [comment]
Thanks for your reply! But how am I supposed to do that when I have no root and no twrp? That's why I'm patching the boot.img... Sorry if I'm acting kinda noobish here!!
