### ISSUE TITLE
Can't approve grant / deny root access with D-PAD on SDK <= 25

### ISSUE THREAD

**Issue by tsynik** [topjohnwu/Magisk#5834]
All Magisk Managers after Magisk Manager 7.5.1 have this bug. User can't press Allow or Deny buttons on root request dialogue. It happens on Android 7.x (API 25) and probably less. It worked fine with Magisk 20.4 and Magisk Manager 7.5.1.

Device: Fire TV 4K
Android version: 7.1.2
Magisk version name: 24310
Magisk version code: 24310

**Comment by yujincheng08** [comment]
@RikkaW https://developer.android.com/training/tv/start/controllers

**Comment by tsynik** [comment]
On Android 9+ Allow button gain focus after dialog window appears (and can be pressed or switched to Deny or list), but on 7.1.2 and less it doesn't, and pressing any D-PAD arrows or SELECT doesn't help at all.

**Comment by tsynik** [comment]
[0001-fix-request-dialog-module-log-and-denylist-navigation.patch.zip](https://github.com/topjohnwu/Magisk/files/8736211/0001-fix-request-dialog-module-log-and-denylist-navigation.patch.zip)

@topjohnwu this patch fixes request dialog, module, log and denylist navigation with d-pad

**Comment by vvb2060** [comment]
Can't reproduce
https://user-images.githubusercontent.com/26996262/170833336-4583e524-f7e7-4c03-8ab5-2adcc967a407.mp4

**Comment by tsynik** [comment]
> Can't reproduce

This issue is about deny / grant root permission request _dialogue_, not that list.

**Comment by vvb2060** [comment]
1:52

**Comment by tsynik** [comment]
> 1:52

Device API level: 27? this happen on < 26

**Comment by tsynik** [comment]
And just adding RequestFocus in acivity_request.xml 
![rf](https://user-images.githubusercontent.com/1551446/171072663-6797decf-0227-4324-8730-c18cbaf68066.png)
fixes this behavior for it

**Comment by vvb2060** [comment]
> on Android < 9 
？

**Comment by tsynik** [comment]
> ？

< != 9 but actually according emulator tests focus exists on api 26 and up and doesn't on api 25
