### ISSUE TITLE
Problem rooting on GloDroid v0.7.5 (PinePhone Pro)

### ISSUE THREAD

**Issue by cyleaf** [topjohnwu/Magisk#5840]
Device: PinePhone Pro (Explorer Edition)
Android version: 13 Tiramisu (kernel version: 5.17.0-android13-0-GloDroid-gcaea44ae4d05   [Tue May 10])
Magisk version name: [a29ae15](https://github.com/topjohnwu/Magisk/commit/a29ae15ff704c5e09f0a7aa6c15bb0ce7af89100)
Magisk version code: 24312

I am having trouble rooting the device via magisk on the latest prerelease of GloDroid (it worked on the version before that).
To clarify on [v0.7.4](https://github.com/GloDroid/glodroid_manifest/releases/tag/v0.7.4) it works, but on [v0.7.5](https://github.com/GloDroid/glodroid_manifest/releases/tag/v0.7.5) it does not.
I was also advised to say that GloDroid has switched to bootimgv4 and ramdisk is in vendor_boot.img.
Patching boot.img has no effect, but if then I additionally patch vendor_boot.img, this causes the device to be unable to boot.

All .img files that I use are linked above inside of the releases. 
They are located inside of the pinephonepro asset for that release.

What could be the issue? Thank you for your help!

**Comment by yujincheng08** [comment]
No log.
