### ISSUE TITLE
Boot loop with Pixel 4a on Lineage 19 (Android 12)

### ISSUE THREAD

**Issue by kchurch05** [topjohnwu/Magisk#5843]
Device: Pixel 4a (Sunfish)
Android version: 12 (Lineage 19, 19/05/2022 build)
Magisk version name: Canary
Magisk version code: 24312

Longtime satisfied Magisk user here. Was running Lineage 18.1 on my Pixel 4a and recently updated to 19. Unfortunately I lost root when I did so, so trying to get that back so I can back up my application data.

Currently keep getting a bootloop each time I flash the patched image and reboot. At one point (not sure what I did differently, sorry!) it actually did boot into Lineage with the modified boot image, but when I opened up Magisk and it rebooted itself to complete the install, it got stuck in a bootloop again. Have tried the "old way" by flashing the apk as a zip, but same bootloop result.

I've attached dmesg and the /proc/mounts. Have also attached the adb bugreport when the bootloop is occurring ("-bootloop.zip") **and** when it's on the normal, working boot image ("-normal.zip).

Using Lineage Recovery/fastboot and not TWRP. Unlocked bootloader version s5-0.4-8048734.

TIA!!
[dmesg.log](https://github.com/topjohnwu/Magisk/files/8749242/dmesg.log)
[procmounts.txt](https://github.com/topjohnwu/Magisk/files/8749244/procmounts.txt)
[bugreport-sunfish-SP2A.220505.002-2022-05-22-20-19-36-normal.zip](https://github.com/topjohnwu/Magisk/files/8749245/bugreport-sunfish-SP2A.220505.002-2022-05-22-20-19-36-normal.zip)
[bugreport-sunfish-SP2A.220505.002-2022-05-22-20-15-36-bootloop.zip](https://github.com/topjohnwu/Magisk/files/8749247/bugreport-sunfish-SP2A.220505.002-2022-05-22-20-15-36-bootloop.zip)

**Comment by yujincheng08** [comment]
I dont think edxposed supoorts Android 12.

**Comment by kchurch05** [comment]
@yujincheng08 - I removed the module, not sure why it's showing up in the bug report. Is this something Magisk is doing or is xposed still lurking in the filesystem?

Thanks for your help. :)
