### ISSUE TITLE
Boot loop with RedMI k40 on MIUI EU 13

### ISSUE THREAD

**Issue by konghui** [topjohnwu/Magisk#5845]
Device: RedMI K40 (POCO F3)
Android version: MIUI EU 13.0.5.0 (Android 12 SKQ1.211006.001)
Magisk version name: 756d8356
Magisk version code: 24312

Recently I upgraded my system from MIUI EU12 to MIUI EU13, When I flash the patched image to the phone with `fastboot flash boot magisk_patched-24312_xxx.img`. The phone can't boot up successfully. The screen hung on the boot logo screen and rebooted many times, Here is the log of `adb logcat`. If you need me to provide more logs, tell me, please. Thank you very much.
[logcat.log](https://github.com/topjohnwu/Magisk/files/8749512/logcat.log)

**Comment by yujincheng08** [comment]
```
05-22 21:13:44.090   866   866 E StorageRedirectInject: open /data/adb/storage-isolation/bin/main.test.dex failed with 2 from remote: No such file or directory
05-22 21:13:44.090   866   866 E StorageRedirectInject: failed to read from rirud
```

**Comment by RikkaW** [comment]
@yujincheng08 The module that contains `main.test.dex` is an old special test version, it should not be used.

**Comment by yujincheng08** [comment]
@RikkaW It's not me that use this ver

**Comment by konghui** [comment]
@RikkaW what should I do to fix this issue? Have any suggestion?

**Comment by RikkaW** [comment]
@konghui Your problem may not relate to my module
