### ISSUE TITLE
Problem rooting on GloDroid v0.7.5 (PinePhone Pro) #2

### ISSUE THREAD

**Issue by cyleaf** [topjohnwu/Magisk#5849]
Follow up on the closed [issue](https://github.com/topjohnwu/Magisk/issues/5840):

Device: PinePhone Pro (Explorer Edition)
Android version: 13 Tiramisu (kernel version: 5.17.0-android13-0-GloDroid-gcaea44ae4d05 [Tue May 10])
Magisk version name: [afa364cf](https://github.com/topjohnwu/Magisk/commit/afa364cfc38ed04137cc56b1ca308747207799f4)
Magisk version code: 24312

I am having trouble rooting the device via magisk on the latest prerelease of GloDroid (it worked on the version before that).
To clarify on [v0.7.4](https://github.com/GloDroid/glodroid_manifest/releases/tag/v0.7.4) it works, but on [v0.7.5](https://github.com/GloDroid/glodroid_manifest/releases/tag/v0.7.5) it does not.
I was also advised to say that GloDroid has switched to bootimgv4 and ramdisk is in vendor_boot.img.
Patching and flashing boot.img has no effect.
Patching and flashing vendor_boot.img has no effect.
Patching and flashing both together causes the device to be unable to boot.

I have gathered several logs(dmesg, logcat, magisk) and they are inside the artifacts archives below.
Inside, in the files the 'pre', refers to pre-flash of the patched boot.img, and 'post' refers to after that.
### v0.7.4 logs (working):
[v0.7.4_logs_artifacts.zip](https://github.com/topjohnwu/Magisk/files/8757492/v0.7.4_artifacts.zip)
(the patched boot.img here is too large so it doesn't let me upload it)

### v0.7.5 logs (not working):
[v0.7.5_logs_artifacts.zip](https://github.com/topjohnwu/Magisk/files/8757496/v0.7.5_artifacts.zip)
[boot_patched-v0.7.5.zip](https://github.com/topjohnwu/Magisk/files/8757499/boot_patched-v0.7.5.zip)

What could be the issue? Thank you for your help!

PS: All original .img files that I use are linked at the very top, inside the releases, in the pinephonepro asset for that release.

**Comment by cyleaf** [comment]
Oops, I forgot to upload a patched vendor_boot.img (it could be of help perhaps?)
[vendor_boot_patched-v0.7.5.zip](https://github.com/topjohnwu/Magisk/files/8757589/vendor_boot_patched-v0.7.5.zip)

**Comment by yujincheng08** [comment]
Why are you patching vendor_boot. Magisk does not require patching vendor_boot.

**Comment by cyleaf** [comment]
I don't know how magisk works internally (or android even) and I saw people say to ignore vendor_boot but I just did it to see what would happen, and magisk didn't reject it either. I saw that in v0.7.4 the boot.img is considerably larger than in v0.7.5 so that got me curious too.

**Comment by yujincheng08** [comment]
Restore vendor_boot and patch only boot. If it does not work, send bugreport.
