### ISSUE TITLE
Bootloop after flashing the patched image files Samsung Galaxy A03 (SM-A035G/DSN)

### ISSUE THREAD

**Issue by im4gin4tion** [topjohnwu/Magisk#5850]
Device: Samsung Galaxy A03 (SM-A035G/DSN)
Android version: 11 (Baseband version: A035GXXU1AVC1)
Magisk version name: Magisk Debug (v24.3)
Magisk version code: 756d8356 (24312)

![VideoCapture_20220523-210524](https://user-images.githubusercontent.com/82507484/169894450-934db093-c796-452e-a87d-92edf0e88a63.jpg)

[magisk_install_log_2022-05-23T21_48_02.log](https://github.com/topjohnwu/Magisk/files/8757665/magisk_install_log_2022-05-23T21_48_02.log)

[boot_img_vbmeta_img.zip](https://github.com/topjohnwu/Magisk/files/8757773/boot_img_vbmeta_img.zip)

**Comment by canyie** [comment]
Can anyone follow these steps to capture a kernel log? https://github.com/topjohnwu/Magisk/issues/5607#issuecomment-1072347395 and https://github.com/topjohnwu/Magisk/issues/5607#issuecomment-1072389939

**Comment by im4gin4tion** [comment]
Sorry I don't have the phone anymore...

**Comment by ForcedSignup** [comment]
I hope I got the stuff you requested @canyie @yujincheng08 
If not, I can try to redo the procedure.
And if some other info needed, just tell me what to try and I'll hop on to it within days :)

[dumpstate-2022-07-08-02-03-57.zip](https://github.com/topjohnwu/Magisk/files/9084104/dumpstate-2022-07-08-02-03-57.zip)

**Comment by yujincheng08** [comment]
@ForcedSignup nothing relative to magisk found in ur zip.
