### ISSUE TITLE
Secure check fail recovery.img while rooting SAMSUNG GALAXY TAB A 8.0 LTE [SM-T295] with Magical 24.3

### ISSUE THREAD

**Issue by darshanraok** [topjohnwu/Magisk#5856]
Device:Samsung Galaxy Tab A 8.0 LTE SM-T295
Android version:11
Magisk version name:Magisk debug 24.3
Magisk version code:24313
![170064442-d1ce2370-b2fe-45e3-ae74-3ffde1df5dec](https://user-images.githubusercontent.com/64535064/170318539-477d0fe7-e4b2-4f3c-bed6-856ae6294777.jpg)

[Recovery.img]
(https://drive.google.com/file/d/1-I0VY2Yf9CnKV54ENqGL78aXJxscipM4/view?usp=drivesdk)

**Comment by ITProggeruz** [comment]
Any fix?
