### ISSUE TITLE
Secure check fail recovery.img while rooting SAMSUNG GALAXY TAB A 8.0 LTE [SM-T295] with Magisk 24.3

### ISSUE THREAD

**Issue by darshanraok** [topjohnwu/Magisk#5857]
Device:Samsung Galaxy Tab A 8.0 LTE SM-T295
Android version:11
Magisk version name:Magisk debug 24.3
Magisk version code:24313

[recovery.img]

(https://drive.google.com/file/d/1-I0VY2Yf9CnKV54ENqGL78aXJxscipM4/view?usp=drivesdk) 

![170064442-d1ce2370-b2fe-45e3-ae74-3ffde1df5dec]

(https://user-images.githubusercontent.com/64535064/170319913-72967a68-871f-4f3b-8c13-0f10637ef63a.jpg)

**Comment by pndwal** [comment]
Have you unlocked bootloader?

**Comment by yujincheng08** [comment]
Close because of the absence of logs.

**Comment by darshanraok** [comment]
> Close because of the absence of logs.

How can I get the logs

**Comment by darshanraok** [comment]
> Have you unlocked bootloader?
> 
> Edit: Oh it's you! 😁... Did bootloader get re-locked?

No in developer option it says bootloader is already unlocked

**Comment by darshanraok** [comment]
Someone tell me where I can get the logs

**Comment by darshanraok** [comment]
> Have you unlocked bootloader?
> 
> Edit: Oh it's you! 😁... Did bootloader get re-locked?

Where I can get the logs

**Comment by pndwal** [comment]
https://github.com/topjohnwu/Magisk#bug-reports

**Comment by darshanraok** [comment]
> https://github.com/topjohnwu/Magisk#bug-reports

unable to understand
