### ISSUE TITLE
Secure Check Fail recovery.img while rooting Samsung galaxy Tab A 8.0 LTE [SM-T295]

### ISSUE THREAD

**Issue by darshanraok** [topjohnwu/Magisk#5863]
Device:Samsung Galaxy Tab A 8.0 LTE SM-T295
Android version:11
Magisk version name:8dfb30fe
Magisk version code:24313

[Recovery.img patched](https://drive.google.com/file/d/111_h4LkXw2WkbAg5COAumw0VvFHg7c2a/view?usp=drivesdk) 

[Recovery.img original](https://drive.google.com/file/d/1-I0VY2Yf9CnKV54ENqGL78aXJxscipM4/view?usp=drivesdk) 

[Boot.img original](https://drive.google.com/file/d/114w56xtjQUtEe2sBVG2AW9B-ekoyaUxO/view?usp=drivesdk) 

[Install logs](https://drive.google.com/file/d/11334HgbYyn9ONzX60nJB3F6Idr0EQ7Xz/view?usp=drivesdk) 

[Logs](https://drive.google.com/file/d/114Aa9my38hk2YaMOwLILVE9vAKYnHgQb/view?usp=drivesdk) 

![image]
(https://user-images.githubusercontent.com/64535064/170646405-2a59f54f-36e2-4f29-b5a3-3bb30772ca88.jpg)

**Comment by darshanraok** [comment]
Let me know if i miss anything

**Comment by canyie** [comment]
have you unlocked the bootloader?

**Comment by darshanraok** [comment]
> have you unlocked the bootloader?

My device bootloader is unlocked

**Comment by johnt1989** [comment]
Patch the boot.img only and flash a disabled vbmeta.img

**Comment by darshanraok** [comment]
> Patch the boot.img only and flash a disabled vbmeta.img

It wont work bcz magisk says ramdisk No

**Comment by johnt1989** [comment]
![Screenshot_20220528-033730](https://user-images.githubusercontent.com/75329354/170821776-fc997dcd-090f-4ab2-8278-fb5ef2aec687.jpg)

this is a partition A style device

**Comment by darshanraok** [comment]
> ![Screenshot_20220528-033730](https://user-images.githubusercontent.com/75329354/170821776-fc997dcd-090f-4ab2-8278-fb5ef2aec687.jpg)
> 
> this is a partition A style device

I didn't understand

**Comment by johnt1989** [comment]
https://topjohnwu.github.io/Magisk/boot.html

**Comment by darshanraok** [comment]
> https://topjohnwu.github.io/Magisk/boot.html

Is there a way to check in which type [1,2,3,4]category does my device belongs to

**Comment by johnt1989** [comment]
your ram disk is located in your recovery and not in the boot img file 2019 samsung devices  same as mine sm-n975u but i digress 
Download the firmware select the AP file and patch the 
ap.tar.md5 file using magisk app you will get a patched.tar file use that patched file in the ap slot

XDA has more info search multi disabler for more info

**Comment by darshanraok** [comment]
> your ram disk is located in your recovery and not in the boot img file 2019, samsung devices same as mine sm-n975u but i digress Download the firmware select the AP file and patch the ap.tar.md5 file using magisk app you will get a patched.tar file use that patched file in the ap slot
> 
> XDA has more info search multi disabler for more info

After that my device get stuck in 
"Secure check fail recovery.img"
And it doesnt boot back to system from there

**Comment by pndwal** [comment]
> > https://topjohnwu.github.io/Magisk/boot.html
> 
> Is there a way to check in which type [1,2,3,4]category does my device belongs to

Type III (A-only legacy SAR) in John's doc.

I posted XDA workaround here:
https://github.com/topjohnwu/Magisk/issues/5854#issuecomment-1136238818

This also allows Magisk in recovery to work...

It would be good to see a proper (integrated) fix however...

**Comment by darshanraok** [comment]
> > > https://topjohnwu.github.io/Magisk/boot.html
> > 
> > 
> > Is there a way to check in which type [1,2,3,4]category does my device belongs to
> 
> Type III (A-only legacy SAR) in John's doc.
> 
> I posted XDA workaround here: [#5854 (comment)](https://github.com/topjohnwu/Magisk/issues/5854#issuecomment-1136450313)
> 
> This also allows Magisk in boot to work...
> 
> It would be good to see a proper (integrated) fix however...

In XDA the guide is not for my device i agree same model but different region and on android 11 with one ui 3.1 but it for android 10

**Comment by pndwal** [comment]
> > > > https://topjohnwu.github.io/Magisk/boot.html
> > > 
> > > 
> > > Is there a way to check in which type [1,2,3,4]category does my device belongs to
> > 
> > 
> > Type III (A-only legacy SAR) in John's doc.
> > I posted XDA workaround here: [#5854 (comment)](https://github.com/topjohnwu/Magisk/issues/5854#issuecomment-1136450313)
> > This also allows Magisk in boot to work...
> > It would be good to see a proper (integrated) fix however...
> 
> In XDA the guide is not for my device i agree same model but different region and on android 11 with one ui 3.1 but it for android 10 Edit : I already seen that before posting issue here

Sorry, how is it not for your device?... Didn't you upgrade thru One UI 3.1, Android 10?

**Comment by darshanraok** [comment]
> > > > > https://topjohnwu.github.io/Magisk/boot.html
> > > > 
> > > > 
> > > > Is there a way to check in which type [1,2,3,4]category does my device belongs to
> > > 
> > > 
> > > Type III (A-only legacy SAR) in John's doc.
> > > I posted XDA workaround here: [#5854 (comment)](https://github.com/topjohnwu/Magisk/issues/5854#issuecomment-1136450313)
> > > This also allows Magisk in boot to work...
> > > It would be good to see a proper (integrated) fix however...
> > 
> > 
> > In XDA the guide is not for my device i agree same model but different region and on android 11 with one ui 3.1 but it for android 10 Edit : I already seen that before posting issue here
> 
> Sorry, how is it not for your device?... Didn't you upgrade thru One UI 3.1, Android 10?

My device currently running Android 11 with one ui 3.1 and 1 Nov 2021 -android security patch

**Comment by pndwal** [comment]
Ok, so [johnt1989](https://github.com/johnt1989) and I are saying Magisk in boot can work on your device despite no OEM ramdisk in boot... I'm guessing that w/ Android 11, BL v4 and anti-rollback may prevent you from using that solution however... I wasn't suggesting you settle for that workaround/hack in any case... As I said,
> It would be good to see a proper (integrated) fix however...

**Comment by johnt1989** [comment]
![Screenshot_20220528-054037_DevCheck](https://user-images.githubusercontent.com/75329354/170825928-22f58ee1-1ceb-4346-bb19-7c436190029b.jpg)
a12 and magisk works just fine

**Comment by darshanraok** [comment]
> Ok, so [johnt1989](https://github.com/johnt1989) and I are both saying Magisk in boot can work on your device despite no OEM ramdisk in boot... I'm guessing that w/ Android 11, BL v4 and anti-rollback may prevent you from using that solution however... I wasn't suggesting you settle for that workaround/hack in any case... As I said,
> 
> > It would be good to see a proper (integrated) fix however...

Ok i will wait for the fix

**Comment by darshanraok** [comment]
> a12

I didnt understand and why did you removed the screenshot

**Comment by johnt1989** [comment]
> > Ok, so [johnt1989](https://github.com/johnt1989) and I are both saying Magisk in boot can work on your device despite no OEM ramdisk in boot... I'm guessing that w/ Android 11, BL v4 and anti-rollback may prevent you from using that solution however... I wasn't suggesting you settle for that workaround/hack in any case... As I said,
> > > It would be good to see a proper (integrated) fix however...
> 
> Ok i will wait for the fix

![Screenshot_20220528-054037_DevCheck](https://user-images.githubusercontent.com/75329354/170826144-101497e6-db7d-4e7f-9cf1-726a8b37a6e7.jpg)

removed the screen sbot and re added it due to battery icon wasnt nice

**Comment by darshanraok** [comment]
> > > Ok, so [johnt1989](https://github.com/johnt1989) and I are both saying Magisk in boot can work on your device despite no OEM ramdisk in boot... I'm guessing that w/ Android 11, BL v4 and anti-rollback may prevent you from using that solution however... I wasn't suggesting you settle for that workaround/hack in any case... As I said,
> > > > It would be good to see a proper (integrated) fix however...
> > 
> > 
> > Ok i will wait for the fix
> 
> ![Screenshot_20220528-054037_DevCheck](https://user-images.githubusercontent.com/75329354/170826144-101497e6-db7d-4e7f-9cf1-726a8b37a6e7.jpg)
> 
> removed the screen sbot and re added it due to battery icon wasnt nice

Your device binary is 7 mine is 4 and also it gives the warning after flashing it

**Comment by johnt1989** [comment]
if you flashed a unlock token to unlock the bootloader
do not update the bootloader bit number

**Comment by darshanraok** [comment]
> if you flashed a unlock token to unlock the bootloader do not update the bootloader bit number

What is unlock token and Bootloader bit number?

**Comment by johnt1989** [comment]
contact me on discord
Slug#4106
i feel this topic has went offtopic

**Comment by darshanraok** [comment]
> contact me on discord Slug#4106 i feel this topic has went offtopic

Ok i will be there in 2 minutes

**Comment by darshanraok** [comment]
Still waiting for the solution to this problem

**Comment by MadTooth** [comment]
Жди, ждун

**Comment by dualbios4** [comment]
Any solution to root SM-T295 With version 4 of the bootloader.

**Comment by jessejgm** [comment]
Still waiting for an update on the U4 bootloader. Still with the secure check fail error.

**Comment by canyie** [comment]
According to #6226 removing `vbmeta.img` from AP.tar before patching/flashing might help. Have you tried that?

**Comment by Navneet-Kumar-Singh** [comment]
By shorting the test points behind the tablet Samsung Galaxy A8 2019 (SM-T290), I have accessed the edl mode (QHSUSB_BULK device shown in device manager in PC) on this tablet t290, so now can we force flash bootloader or aboot.mbn to s3 from s4? I installed drivers for the QHSUSB_BULK device and then I knew that it's Qualcomm HS USB Loader 9008 , which means I bypassed secondary bootloader or download mode and now I have successfully entered the primary bootloader or emergency download mode(edl mode) . Now I can force flash original binary 3 bootloader but I don't know how as tools like QFIL tool using Firehose protocol require a raw_program file and a patch file which I don't have for this tablet in its stock firmware I downloaded from samfrew website though I probably saw the required 'meta' files(raw and patch file) in a ota.zip file which is inside Ap.tar.md5 file of this tablet, but that ota.zip has password protection and I can't access it. Alone I was able to advance till this point , can anyone help me to get further from this point and flash s3 bootloader? Pls I am eager to do anything as I saved a Nandroid backup of this tablet which includes my study career related important data , and I want to restore that Nandroid to get those data. Any help is appreciated. Pls help me . I beg you.

**Comment by shyambandla** [comment]
> By shorting the test points behind the tablet Samsung Galaxy A8 2019 (SM-T290) or t295(another tablet if anyone has this instead), I have accessed the edl mode (QHSUSB_BULK device shown in device manager in PC) on this tablet t290, so now can we force flash bootloader or aboot.mbn to s3 from s4 to get twrp working back? I installed drivers for the QHSUSB_BULK device and then I knew that it's Qualcomm HS USB Loader 9008 , which means I bypassed secondary bootloader or download mode and now I have successfully entered the primary bootloader or emergency download mode(edl mode) . Now I can force flash original binary 3 bootloader but I don't know how as tools like QFIL tool using Firehose protocol require a raw_program file and a patch file which I don't have for this tablet in its stock firmware I downloaded from samfrew website though I probably saw the required 'meta' files(raw and patch file) in a ota.zip file which is inside Ap.tar.md5 file of this tablet, but that ota.zip has password protection and I can't access it. Alone I was able to advance till this point , can anyone help me to get further from this point and flash s3 bootloader? Pls I am eager to do anything as I saved a Nandroid backup of this tablet which includes important data , and I want to restore that Nandroid to get those data. Any help is appreciated. Pls help me .

bro have you got any luck with this ?? a lot of us stuck here

**Comment by shyambandla** [comment]
> Device:Samsung Galaxy Tab A 8.0 LTE SM-T295 Android version:11 Magisk version name:8dfb30fe Magisk version code:24313
> 
> [Recovery.img patched](https://drive.google.com/file/d/111_h4LkXw2WkbAg5COAumw0VvFHg7c2a/view?usp=drivesdk)
> 
> [Recovery.img original](https://drive.google.com/file/d/1-I0VY2Yf9CnKV54ENqGL78aXJxscipM4/view?usp=drivesdk)
> 
> [Boot.img original](https://drive.google.com/file/d/114w56xtjQUtEe2sBVG2AW9B-ekoyaUxO/view?usp=drivesdk)
> 
> [Install logs](https://drive.google.com/file/d/11334HgbYyn9ONzX60nJB3F6Idr0EQ7Xz/view?usp=drivesdk)
> 
> [Logs](https://drive.google.com/file/d/114Aa9my38hk2YaMOwLILVE9vAKYnHgQb/view?usp=drivesdk)
> 
> ![image] (https://user-images.githubusercontent.com/64535064/170646405-2a59f54f-36e2-4f29-b5a3-3bb30772ca88.jpg)

have you got any luck solving this issue. a lot of us stuck at this step

**Comment by Navneet-Kumar-Singh** [comment]
> > Device:Samsung Galaxy Tab A 8.0 LTE SM-T295 Android version:11 Magisk version name:8dfb30fe Magisk version code:24313
> > [Recovery.img patched](https://drive.google.com/file/d/111_h4LkXw2WkbAg5COAumw0VvFHg7c2a/view?usp=drivesdk)
> > [Recovery.img original](https://drive.google.com/file/d/1-I0VY2Yf9CnKV54ENqGL78aXJxscipM4/view?usp=drivesdk)
> > [Boot.img original](https://drive.google.com/file/d/114w56xtjQUtEe2sBVG2AW9B-ekoyaUxO/view?usp=drivesdk)
> > [Install logs](https://drive.google.com/file/d/11334HgbYyn9ONzX60nJB3F6Idr0EQ7Xz/view?usp=drivesdk)
> > [Logs](https://drive.google.com/file/d/114Aa9my38hk2YaMOwLILVE9vAKYnHgQb/view?usp=drivesdk)
> > ![image] (https://user-images.githubusercontent.com/64535064/170646405-2a59f54f-36e2-4f29-b5a3-3bb30772ca88.jpg)
> 
> have you got any luck solving this issue. a lot of us stuck at this step

Unfortunately no progress till now bro , but still I am trying . Also pls share any research source links which you encountered so that I can progress more. And pls update here also if you get something. I will also update you if I get something. Thank you brother 🙏

**Comment by Navneet-Kumar-Singh** [comment]
SM-T290 tablet got new update of binary 5 but it's available in Brazil and some other countries but not currently in India. Can anyone boot twrp with binary 5 ? Pls inform me. Thank you 🙏

**Comment by shyambandla** [comment]
> SM-T290 tablet got new update of binary 5 but it's available in Brazil and some other countries but not currently in India. India will soon get the update, but to test now we can install the Brazil ROM . I tried but still the same issue. Can anyone boot twrp with binary 5 with any workaround ? Pls inform me. Thank you 🙏

it's not even working with edl mode ??

**Comment by Navneet-Kumar-Singh** [comment]
Unfortunately, currently no brother

**Comment by gs-music** [comment]
> By shorting the test points behind the tablet Samsung Galaxy A8 2019 (SM-T290) or t295(another tablet if anyone has this instead), I have accessed the edl mode (QHSUSB_BULK device shown in device manager in PC) on this tablet t290, so now can we force flash bootloader or aboot.mbn to s3 from s4 to get twrp working back? I installed drivers for the QHSUSB_BULK device and then I knew that it's Qualcomm HS USB Loader 9008 , which means I bypassed secondary bootloader or download mode and now I have successfully entered the primary bootloader or emergency download mode(edl mode) . Now I can force flash original binary 3 bootloader but I don't know how as tools like QFIL tool using Firehose protocol require a raw_program file and a patch file which I don't have for this tablet in its stock firmware I downloaded from samfrew website though I probably saw the required 'meta' files(raw and patch file) in a ota.zip file which is inside Ap.tar.md5 file of this tablet, but that ota.zip has password protection and I can't access it. Alone I was able to advance till this point , can anyone help me to get further from this point and flash s3 bootloader? Pls I am eager to do anything as I saved a Nandroid backup of this tablet which includes important data , and I want to restore that Nandroid to get those data. Any help is appreciated. Pls help me .

I was able to decrypt the ota.zip file (fota.zip) using this tutorial on the XDA forum: https://xdaforums.com/t/possible-way-to-self-sign-recovery-and-roms-on-s7-just-need-some-help.3618744/

Sorry for my English, I'm using Google Translate.

I wanted to use postmarketos on the tablet but I needed a binary 3 bootloader.

**Comment by jithurx** [comment]
> By shorting the test points behind the tablet Samsung Galaxy A8 2019 (SM-T290) or t295(another tablet if anyone has this instead), I have accessed the edl mode (QHSUSB_BULK device shown in device manager in PC) on this tablet t290, so now can we force flash bootloader or aboot.mbn to s3 from s4 to get twrp working back? I installed drivers for the QHSUSB_BULK device and then I knew that it's Qualcomm HS USB Loader 9008 , which means I bypassed secondary bootloader or download mode and now I have successfully entered the primary bootloader or emergency download mode(edl mode) . Now I can force flash original binary 3 bootloader but I don't know how as tools like QFIL tool using Firehose protocol require a raw_program file and a patch file which I don't have for this tablet in its stock firmware I downloaded from samfrew website though I probably saw the required 'meta' files(raw and patch file) in a ota.zip file which is inside Ap.tar.md5 file of this tablet, but that ota.zip has password protection and I can't access it. Alone I was able to advance till this point , can anyone help me to get further from this point and flash s3 bootloader? Pls I am eager to do anything as I saved a Nandroid backup of this tablet which includes important data , and I want to restore that Nandroid to get those data. Any help is appreciated. Pls help me .

I have the firmware file which has the raw and patch file of sm-t295 (binary 3) but to flash it the edl loader is required (firehose file). That's something that's not yet available for this device, or maybe it is but I am missing out ?

**Comment by Dubicrack-YT** [comment]
I'm new to this and I'm having problems flashing TWRP on the SM-T290, due to something in the system that blocks the unofficial software and you can't continue unless you flash the official samsung software again, I started researching on the internet and I found the vbmeta.img file, I don't know if that can be causing the unofficial software to be blocked even with the bootloader unlocked, and the tablet's fastboot mode doesn't work either, I have a SM-A045M/DS and the PC recognizes its fastboot mode but it is not detected on my tablet, I have already searched for drivers but nothing works.

**Comment by Dubicrack-YT** [comment]
Apparently the vbmeta.img has nothing to do with this, I saw on another page and it is because the bootloader is broken and even if it is unlocked it continues to run the signature check.

https://us.community.samsung.com/t5/Tablets/SM-T290-SM-T295-bootloader-unlock-does-not-allow-flashing-any/td-p/2781332

**Comment by Dubicrack-YT** [comment]
The only solution would be to downgrade from binary 5 to 3 but it is not possible, if someone has binary 3 they should downgrade to version T290XXU3CVG3.

**Comment by Utsav80** [comment]
Device:Samsung Galaxy Tab A 8.0 LTE SM-T295

Android version:11

I have patch my ap file with magisk and when i go for flashing in odin. odin says pass but in download mode it shows error Secure check fail Vbmeta. i have tried disable vbmeta but shows same error please help me to root my device
