### ISSUE TITLE
denylist: rescanning apps

### ISSUE THREAD

**Issue by RV7PR** [topjohnwu/Magisk#5871]
Device: Samsung Galaxy A53 (SM-A536B)
Android version: 12
Magisk version name: 
Magisk version code: 24314

Each second there is multiple "denylist: rescanning apps" in log

[magisk_log_2022-05-29T20_45_06.log](https://github.com/topjohnwu/Magisk/files/8794064/magisk_log_2022-05-29T20_45_06.log)

**Comment by canyie** [comment]
https://github.com/topjohnwu/Magisk/blob/0cc29350a0e27ab1081752a55e4d170a235be31c/native/jni/core/package.cpp#L30-L38

**Comment by canyie** [comment]
Should be fixed in 4ea8bd0229016c1d82c3505918336d6aa260704d
