### ISSUE TITLE
Realme gt neo 2t RUI v3.0 (Android 12) canary 24314 bootloop

### ISSUE THREAD

**Issue by NortimO** [topjohnwu/Magisk#5875]
Bootloop (24313 work but constantly requests requests for root access although it is already granted (sd maid, adguard etc.))

Device: Realme GT Neo 2T
Android version: 12
Magisk version name: Canary
Magisk version code: 24314

**Comment by vvb2060** [comment]
no log

**Comment by NortimO** [comment]
> no log

Please tell then how and where do I get the boot log?
