### ISSUE TITLE
Mi A2 lite (daisy) can't create magisk patch boot image

### ISSUE THREAD

**Issue by thantoeaungat** [topjohnwu/Magisk#588]
Mi A2 lite version = V9.6.4.0 ( Pure android )
Magisk App Version = MagiskManager-v5.9.1

Download boot image file
http://www.mediafire.com/?ps8de97975g2ndm

Contact me
========
thantoeaung@live.com

Install logs
=======
- Copying image to cache
- Device platform: arm64-v8a
- Existing zip found
- Extracting files
- Boot image is signed with AVB 1.0
boot_patch.sh[73]: can't create /proc/self/fd/: Is a directory
MagiskBoot v17.1(17100) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
KERNEL [30215640]
RAMDISK [5543954]
SECOND [0]
EXTRA [0]
PAGESIZE [2048]
OS_VERSION [8.1.0]
PATCH_LEVEL [2018-07]
NAME []
CMDLINE [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992]
CHECKSUM [2359f745d50bfb7d77e054ee62f4a917bc788197]
DTB [20567027]
KERNEL_FMT [gzip]
RAMDISK_FMT [gzip]
boot_patch.sh[98]: can't create /proc/self/fd/: Is a directory
MagiskBoot v17.1(17100) (by topjohnwu) - Boot Image Modification Tool
Loading cpio: [ramdisk.cpio]
boot_patch.sh[120]: can't create /proc/self/fd/: Is a directory
boot_patch.sh[120]: can't create /proc/self/fd/: Is a directory
MagiskBoot v17.1(17100) (by topjohnwu) - Boot Image Modification Tool
Compressing to [stock_boot_121c96ea2f6fe400e98bdf0179ad0d3532041352.img.gz]
boot_patch.sh[126]: can't create /proc/self/fd/: Is a directory
MagiskBoot v17.1(17100) (by topjohnwu) - Boot Image Modification Tool
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Save SHA1: [121c96ea2f6fe400e98bdf0179ad0d3532041352] -> [.backup/.sha1]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Dump cpio: [ramdisk.cpio]
MagiskBoot v17.1(17100) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v17.1(17100) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v17.1(17100) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v17.1(17100) (by topjohnwu) - Boot Image Modification Tool
Patch @ 015196F0 [736B69705F696E697472616D6673]->[77616E745F696E697472616D6673]
boot_patch.sh[169]: can't create /proc/self/fd/: Is a directory
MagiskBoot v17.1(17100) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
KERNEL [30215640]
RAMDISK [5543954]
SECOND [0]
EXTRA [0]
PAGESIZE [2048]
OS_VERSION [8.1.0]
PATCH_LEVEL [2018-07]
NAME []
CMDLINE [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992]
CHECKSUM [2359f745d50bfb7d77e054ee62f4a917bc788197]
DTB [20567027]
KERNEL_FMT [gzip]
RAMDISK_FMT [gzip]
Repack to boot image: [new-boot.img]
KERNEL [30217531]
RAMDISK [5782664]
SECOND [0]
EXTRA [0]
PAGESIZE [2048]
OS_VERSION [8.1.0]
PATCH_LEVEL [2018-07]
NAME []
CMDLINE [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992]
CHECKSUM [193901aa15e66ed08910c5624a011b241511b5f5]
MagiskBoot v17.1(17100) (by topjohnwu) - Boot Image Modification Tool
Cleaning up...
- Signing boot image with test keys
! Installation failed

**Comment by topjohnwu** [comment]
Already fixed here: d520b3d2a03a24802a79b15e38860596135f9dac
Please be on the Canary builds before reporting issues!
