### ISSUE TITLE
Bootloop upon activating Zygisk on Oneplus 3

### ISSUE THREAD

**Issue by buhbbl** [topjohnwu/Magisk#5884]
I have tried this multiple times and everytime I activate Zygisk on my Oneplus 3 its gets stuck in a bootloop. After inspecting the logcat, I found that it gets stuck in the warning mentioned in Issue https://github.com/topjohnwu/Magisk/issues/543. I need to fix it using the solution mentioned there, deleting the contents of "/data/adb", which also gets rid of magisk.

Bootlog: [logcat.log](https://github.com/topjohnwu/Magisk/files/8799422/logcat.log)
dmesg log: [dmesg.log](https://github.com/topjohnwu/Magisk/files/8799427/dmesg.log)

Device: Oneplus 3 (A3003)
Android version: 8.0.0
Magisk version name: 24.3
Magisk version code: 24300

Edit: Updated the version code

**Comment by canyie** [comment]
> I Magisk  : Magisk 24.3(24300) daemon started

**Comment by HuskyDG** [comment]
> Magisk version name: 24.3

**Comment by buhbbl** [comment]
> I Magisk  : Magisk 24.3(24300) daemon started

Magisk does start, but this is bootlog from the time when my phone enters a bootloop.

> #5883

Sorry, about that I did add the version code and the issue was closed by the bot

**Comment by pndwal** [comment]
So it's still an "invalid bug report".

You've fudged the version code. You're not running Magisk with latest fixes (wastes Devs time as they won't test 24300), nor are do you have Debug version required for bug reports (built w/ verbose logging etc), and bot already told you: "Please report issues using the latest debug Magisk build (version code: 24314)"!
