### ISSUE TITLE
Failed to use adb remount command

### ISSUE THREAD

**Issue by hlyzh** [topjohnwu/Magisk#590]
I tried adb root command still not helpful.
I can use adb shell with su command but I can not use remount, push/pull command 

Device: Mi6/sagit
ROM: Lineage 15.1 / Android 8.1.0
Magisk 17.1
Magisk Manager 5.9.1

![capture](https://user-images.githubusercontent.com/19305975/45269655-4524e380-b457-11e8-9f2a-80d9b51e99aa.PNG)

**Comment by topjohnwu** [comment]
This is expected
