### ISSUE TITLE
Repackaged Magisk app 24315 won't open

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#5905]
Device: ASUS Zenfone 4
Android version: 9
Magisk version name: 2106751e
Magisk version code: 24315

When updating the Magisk app from version 24313 to 24315, the app no ​​longer opens. The name of the repackaged app is `q.ehb`. When uninstalling the current app and installing the official apk, the Magisk app opens, but when you repackage it, the same problem happens again.
[magiskappnotopeningafterupdate.txt](https://github.com/topjohnwu/Magisk/files/8832486/magiskappnotopening.txt)
[tryingtorepackageagain.txt](https://github.com/topjohnwu/Magisk/files/8832575/tryingtorepackageagain.txt)

**Comment by macerg** [comment]
I have issues with this too. It's to do with the magisk hide feature. If you uninstall your previous hidden version of magisk, you can open the 'new' Magisk app. The 'hide' feature doesn't work however. Sorry to be so short but busy.

**Comment by EnGamma** [comment]
I think I have the same problem.  I got notification to click/press to download and install update.  Did so and now Magisk won't open.  Stuck now.  I see "Magisk-(-1).apk" in Downloads.

Can I try to uninstall renamed/hidden Magisk and then install the apk in downloads?

**Comment by macerg** [comment]
Yes, but if you previously hid Magisk,  deinstall that

**Comment by pndwal** [comment]
I (+ others on XDA forums) have the same experience... 

When taking Hide the Magisk app function, OS almost freezes, hiding doesn't complete, two apps are left when interrupted...

I have Xiaomi Redmi Note 8T

**Comment by canyie** [comment]
I think the breaking commit might be 9ab7550970d0bb1222ec721cca534c1dac7cfb43?

**Comment by canyie** [comment]
9016e6727d76d84c5c098ed519dae15c1be35049

**Comment by pndwal** [comment]
Just tried actions build [Fix stub app loading on older Android versions](https://github.com/topjohnwu/Magisk/actions/runs/2442433414)
Magisk Build #1895

It's broken for me; app-release.apk and app-debug.apk ask for additional setup which fails to complete...

**Comment by EnGamma** [comment]
Thanks, delete then reinstall (sideload) worked.

**Comment by pndwal** [comment]
> Just tried actions build [Fix stub app loading on older Android versions](https://github.com/topjohnwu/Magisk/actions/runs/2442433414) Magisk Build #1895
> 
> It's broken for me; app-release.apk and app-debug.apk ask for additional setup which fails to complete...

This remains broken for me in [Better stub launch flow](https://github.com/topjohnwu/Magisk/actions/runs/2445209895)

Strangely, app-release.apk and app-debug.apk are only loading stub of ~100kb, not full app (11 / 18 mb) which also fails to "Upgrade to full Magisk..."

Am I missing something?

**Comment by KaMyKaSii** [comment]
> Strangely, app-release.apk and app-debug.apk are only loading stub of ~100kb, not full app (11 / 18 mb) which also fails to "Upgrade to full Magisk..."
> 
> Am I missing something?

It is normal for the stub app to be only a few KB. I just updated to Magisk 24316 and the repackaged app is working again.
