### ISSUE TITLE
Magisk is not installed issue in v17.1

### ISSUE THREAD

**Issue by usmanmughalji** [topjohnwu/Magisk#591]
I flashed latest  v17.1 after first boot it's worked fine than after some hours it's disappeared and shows only magisk not installed and say's download again but i already installed it perfectly, so i have to reboot my device again, again to fix this issue. Many users facing this issue. Please fix it. The most stable version i use is v16.2.

**Comment by sekaiacg** [comment]
I also have this problem. After the device is started for more than ten hours, there will be a chance that the magisk root will be lost because the magisk process disappears.
I think it is a problem caused by 32-bit binaries.
I am testing to compile 64-bit binaries using the latest source code....

**Comment by topjohnwu** [comment]
@sekaiacg nope it's not. Can anyone upload Magisk logs when using Canary channel? I need those to debug.....

**Comment by topjohnwu** [comment]
Unfortunately official release won't get the required logs. You have to use the Canary builds. Check the README, reporting issues requires you to use Canary builds.

**Comment by sekaiacg** [comment]
Understood, so I couldn't find a valuable log before.

**Comment by PetNoire** [comment]
Its likely caused by a bad module. I know universal-safetynet-fix was a specific example that caused this. Had to update the module for 17

**Comment by sekaiacg** [comment]
Tested for more than 1 day, finally there is no prompt to install, the following is the log.
[magisk.log](https://github.com/topjohnwu/Magisk/files/2375113/magisk.log)

**Comment by bookhankaa** [comment]
Not installed in a few hours after installed. 17.1, 16.7 same issues. MM 5.9.1 in both cases.

**Comment by sekaiacg** [comment]
@topjohnwu 
After a week of testing, many people reported that magisk lost in mi6 miui alpha(oreo) root privileges (not installed).
I made the following command:
1.adb shell
2.su
Tip: No daemon is currently running!
The problem is that the daemon is killed? Is there a way to do a permanent process (can't kill)?
Every time something goes wrong, you need to restart the device...
![2018-09-20 15-07-30](https://user-images.githubusercontent.com/33929605/45801600-eda03680-bce6-11e8-9938-d9ec0be6c1fb.png)

**Comment by sekaiacg** [comment]
I can't get the kmsg log without root. Is it possible to change the process name magicskd ->xxxxxxxx to prevent being killed?

**Comment by usmanmughalji** [comment]
Guy's You are all using latest 3.2.3 Recovery? Please Confirm. If not Please Use latest updated recovery for your device and try to clean install magisk.

**Comment by topjohnwu** [comment]
Can you test turning MagiskHide off? I think might be some instability there and I'd love to confirm it.

**Comment by sekaiacg** [comment]
Yes, I will turn off magiskhide for testing.

**Comment by sekaiacg** [comment]
Is it possible that it is caused by a security patch?
Https://source.android.com/security/bulletin/2018-08-01

**Comment by sekaiacg** [comment]
There are also some devices: mi5 gemini (miui (oreo) alpha), this problem also occurs, more devices and rom, their users did not report this bug.
I think the problem is more that the magisk process is killed. To this end, we can only study the signal (SIGTERM, SIGKILL) that is sent to the magisk process in the kernel and output it to kmsg to determine whether the magic is targeted by miui.

**Comment by usmanmughalji** [comment]
In Redmi 4/4x (santoni) Groups some users reported that the issue is with recovery that's why the "magisk is not installed" issue we are facing. we must use latest recovery 3.2.3 if you are device is treble support use treble or non treble recovery must. i am also facing this issue so, that's why i opened the issue here because i was using too old recovery yesterday i updated to latest recovery for my device i clean flashed new rom and flashed latest magisk 17.1 clean everything worked fine in non-treble rom (normal build) and treble rom. i am using from yesterday so no issue i found in magisk 17.1 and i gonna wait for few hours for more checking magisk 17.1 than maybe please closed this issue yourself. you know better what to do now guys.

**Comment by sekaiacg** [comment]
After testing to close magiskhide can not solve this problem. Recovery has been 3.2.3.

**Comment by hariedo** [comment]
I have this issue, and also have had no luck in getting root back.

* I (still) have an unlocked bootloader.
* I (still) have TWRP 3.2.3-0 installed, and can use it.
* I had Magisk 16.7 and root but the "Something is wrong with your device" message at startup so tried flashing 17.1.
* After flashing Magisk 17.1, no more "Something is wrong" message.
* Some time later, Magisk app says "Magisk not installed" and a root checker app says no root.
* I can reapply 16.4 in TWRP with no errors, but no success to regain root.
* I can go back to TWRP 3.2.3-0 installer, and reapply 16.4 (says "stock boot image detected" so should be clean) with no errors, but no success to gain root.

**Comment by ezxpro** [comment]
This problem is not exclusive to the mi5. I have a moto G5 and either in stock nougat (7.0) or stock Oreo (8.1) or in custom roms (for instance lineage 14.1 armeabi-v7) I had this problem on all available 17.x magisk builds.

There's are also other issue such as losing only root access or the download section disappearing from magisk manager.
I experienced all of them on 17.x builds.

Magisk 16.0 seems unaffected by the root loss or magisk not installed bug, but I had instances where the download section would not show up. Magisk 16.7 also seems vulnerable to the bugs herein presented, I experienced them but I can't remember the circumstances

**Comment by cryptoz** [comment]
Just happened on pixel 2xl pie, nitrogen is, 3.2.3. I had slot issues in my first attempts at installing.

**Comment by maunsen** [comment]
I have the same problem on a Mi MIx 2s with Miui 10 Beta 8.11.8 Android Pie.

I installed Magisk 17.3 via adb sideload without any error message.
When I reboot, MagiskManager 6.0.1 shows, that Magisk is not installed.

I tried uninstalling with Magisk Uninstaller and reflashing, but it didn't work.

**Comment by abstractultra** [comment]
Also having the same problem on Xiaomi Mi6 with Atomic OS 8.1

**Comment by gen0uu** [comment]
i have same problem too. but i have a solution 

> after install magisk in twrp install any magisk module then reboot

*some times doesn't worked

**Comment by Natalcia** [comment]
Same issue on LOS 14.1 i9305. First boot with fresh magisk will be fine for 5~ hours. After reboot just closing Magisk Manager will result in this bug

**Comment by Didgeridoohan** [comment]
Has anyone in here tested this on any current Canary build? I only see mentions of v17.1, v17.2 and v17.3...

**Comment by Natalcia** [comment]
> Has anyone in here tested this on any current Canary build? I only see mentions of v17.1, v17.2 and v17.3...

I'm on canary right now and it's still broken

**Comment by Didgeridoohan** [comment]
@Natalcia And it doesn't matter if you have MagiskHide enabled or not?

**Comment by Natalcia** [comment]
> @Natalcia And it doesn't matter if you have MagiskHide enabled or not?

I can't check right now because manager broke completely and shows "Magisk is not installed" even after rebooting, custom font module is working fine. I will try to reinstall and turn MagiskHide off when I get back from school.

**Comment by topjohnwu** [comment]
@Natalcia can you provide more details? Like full magisk.log after the crash occurs? (Please upload logs using latest debug Canary build)

**Comment by Natalcia** [comment]
I had problems with uploading .log so I renamed it to .txt 🤷


[magisk.txt](https://github.com/topjohnwu/Magisk/files/2615143/magisk.txt)

**Comment by agyild** [comment]
I am having the same issue on Xiaomi MI6 on LOS 15.1. Also SafetyNet checks fail always as well.

**Comment by abstractultra** [comment]
Even when MagiskHide is disabled, I still lose root eventually on AtomicOS Oreo 8.1 on Xiaomi Mi 6

**Comment by Newex** [comment]
Same problem here.  
After a while, Magisk is not installed is reported.
Also if I do a fresh install (factory reset from TWRP), and install Magisk, the first time it will pass SafetyNet check. But after a while (probably after installing BusyBox) SafetyNet check will fail.

**Device info**
Oneplus 6t model A6013
OxygenOS v. 9.0.6 / Android 9
Security patch level: November 1, 2018
Custom kernel: 4.9.106-ElementalX-OP6-3.06

Magisk 17.3
Magisk Manager: 6.0.1 (151)

**Modules**
Busybox for android NDK v.1.29.3
Energized Protection updated Nov 30, 2018
Viper4AndroidFX v.1.8.1

**Magisk Settings**
Magisk Hide: enabled
Systemless hosts: enabled
Preserve force encryption: checked
Preserve AVB 2.0/dm-verity: checked

**Comment by s7dhansh** [comment]
For me the culprit was multi-rom on poco miui pie beta. As per the Dev, I reflashed my rom, then magisk **and then multi-room**. Root restored.

**Comment by abstractultra** [comment]
Has anybody found a solution yet?

**Comment by abstractultra** [comment]
It's not fixed. It is still happening on Magisk 18.0

**Comment by usmanmughalji** [comment]
@abstractultra which device and custom rom?

**Comment by hyakki-** [comment]
started to recently have this issue on my xiaomi redmi note 3 / Havoc OS (android 9, Magisk 18), out of the blue it says no root / magisk not installed , after a reboot everything back working again.

I will try to disable magisk hide and see if problem resolves.

**Comment by abstractultra** [comment]
@usmanmughalji Xiaomi Mi6 with AtomicOS 8.1

**Comment by sivansundar** [comment]
Using 18.0. Clean flashed the rom and it is no more. Flashed 18 again and I don't see Magisk anymore. su gives me permission denied. Same issue with 16 as well. 

Using Moto G4Plus | AEX 6.2 | Android Pie 9

**Comment by hyakki-** [comment]
I think it has been fixed on the Canary build, no issue for several days.
Magisk (b7f69238) (18007)
    Fix segfault on several devices

**Comment by sivansundar** [comment]
Thanks @hyakki-. Will check this out. 

But on the Canary thread it states that `SafetyNet / CTS / XXX app won't work after enabling MagiskHide:`

Does that mean that apps like Google Pay and Snap wouldn't work? Or in that case, patching a universal safety net patch would work?

**Comment by Didgeridoohan** [comment]
> Thanks @hyakki-. Will check this out.
> 
> But on the Canary thread it states that `SafetyNet / CTS / XXX app won't work after enabling MagiskHide:`
> 
> Does that mean that apps like Google Pay and Snap wouldn't work? Or in that case, patching a universal safety net patch would work?

That's not a statement meaning that MagiskHide doesn't work. It's part of the troubleshooting section of the OP on how to report different issues (Manager crashing, things not working as expected, etc). The section you quoted is simply an instruction on what to do if you're having issues with SafetyNet or MagiskHide. And the instruction is: Do NOT report in the Canary thread...

And as a side note: if you're talking about the Universal SafetyNet fix module, don't use it. Most versions of it (that I've seen) are quite buggy and may cause issues with Magisk. There are better ways available, available in the Magisk repo even...

**Comment by mezzan** [comment]
Hi guys

I have exactly this problem. I'm working on a single-board computer i.MX7D with Android Things 1.0.8
I have installed Magisk Manager v.6.1.0. Manager correctly create patched_boot.img but it shows "Magisk not installed" after the new boot.img is flashed.

**Comment by KunwarVSuryavanshi** [comment]
I am having the same issue.
After I flashed magisk zip it was working for 10-13 hrs but after that I am seeing magisk not installed in the magisk manager app even after I tried to install it using the magisk app it downloaded the file and I installed the same still after that it is showing same message.

I think that it is due to magisk hide config that I installed using magisk. 

If someone finds solution to this please help.

**Comment by ashishjangra206** [comment]
@topjohnwu I'm having same issue on v18.1(manager 7.0.0) and I tried 10 times but still broken and showing magisk not installed.

Device: Asus Zenfone Max Pro M1
Rom: Pixel Rom,Havoc Os etc


Magisk is perfectly installed in twrp 3.2.3.0

**Comment by adrianodennanni** [comment]
I have the same problem as @ashishjangra206 

Device: Motorola Moto G4
Rom: ArrowOS (AOSP 9.0)

**Comment by AmalvishnuKS** [comment]
I have the same issue. After restart it shows, magisk not installed.

Device: Redmi 4x
Rom: Pixel Experience (9.0)

**Comment by adrianodennanni** [comment]
@ashishjangra206 and @AmalvishnuKS I solved this in my device. I moved the Magisk Manager installed app from SD Card to Internal Storage, and erased app storage after it.

**Comment by AmalvishnuKS** [comment]
@adrianodennanni But my app is already installed on internal storage.

**Comment by esauvisky** [comment]
This is probably NOT the same issue as most of you are having, but just in case:

Had this issue right now, after updating the module [Bash For Android](https://github.com/Zackptg5/Bash-For-Android/) and choosing the (experimental) option to replace the default shell from sh to bash.

It only happens via `adb`, if the shell is running on your device (i.e.: on any terminal emulator app) `su` works fine.

**TL;DR:** If Magisk shows it's installed, and `su` works in a shell _within_ the device, you most likely have the module above installed with the experimental option enabled! ;)

**Comment by TheGreySquare** [comment]
Same issue as the others.
Redmi 4X, 3/32.

Oreo ROMs worked fine.
Pie ROMs having Magisk issues since I first installed Pie in August, 2018.

Many people saying that they don't have this issue on Redmi 4X, 2/16, which is weird.
Magisk just randomly dissapears, and you can flash it 20-30 times before it appears again (With or without installed modules).

Magisk 19.1
Pixel Experience ROM, Android Pie.
