### ISSUE TITLE
Magisk Manager: log window cant be scrolled with TV remote, D-PAD on Android TV 7, Fire OS 6 and ohers

### ISSUE THREAD

**Issue by tsynik** [topjohnwu/Magisk#5915]
Here is example video - https://user-images.githubusercontent.com/1551446/171092370-54b667eb-939a-4243-b1e4-00ca05289077.mov

Device: Fire TV 4K
Android version: 7.1.2
Magisk version name: 24315
Magisk version code: 24315

**Comment by tsynik** [comment]
possible solution in #5917

**Comment by yujincheng08** [comment]
I am merging Android TV related issues into one #5916.
