### ISSUE TITLE
Bootloop problem

### ISSUE THREAD

**Issue by ThotSoft** [topjohnwu/Magisk#592]
As i can't activate and bypass Safetynet I tried to install Magisk fresh so, I tried uninstall and click Restore Image successfully and then Full Uninstall successful too. But, when I reboot my phone, Hang in boot/bootloop. So, I'd reboot into recovery and then into bootloader and restore my backup boot.img but still unable to and stuck on boot logo. Please, tell me what to do? and also tell me what and when I'd made mistaked? I'll be very thankful to you.

**Comment by topjohnwu** [comment]
Restoring stock boot image completely removes Magisk, if it still stuck in bootloop it is not my fault.
Maybe the stock backup isn't matching?
