### ISSUE TITLE
Error after installing "Systemless Xposed"

### ISSUE THREAD

**Issue by rocketpencil** [topjohnwu/Magisk#593]
After installing Systemless Xposed, Doesn't Grant root access & no promt or root premission
Installed Xposed_Framework_(SDK_26_arm64)-90.2-beta4-test1_(Systemless).zip (Xposed Issue [#310](https://github.com/rovo89/Xposed/issues/310))
  https://forum.xda-developers.com/showpost.php?p=77269446&postcount=7439

does not solve with Magisk Issue #460, #574, #569

errorlog output
 select failed with 2: No such file or directory

- Device&Software info:
    - Huawei P20 lite (Japan Model HWV32)
    - EMUI 8.0.0
    - Magisk 17.2-39be7a62
    - Magisk Manager 5.9.2-39be7a62
        -  Magisk Core Only Mode : Disable
        -  Magisk Hide : Disable
        -  Systemless hosts : Disable
    - Xposed Installer 3.1.5

magisk issue?
xposed issue?

Please tell me the solution.

[magisk_log_20180910_213450.log](https://github.com/topjohnwu/Magisk/files/2367089/magisk_log_20180910_213450.log)

![screenshot_20180910-213235](https://user-images.githubusercontent.com/43143121/45304680-91ede480-b553-11e8-9283-4b5c797b6769.jpg)

**Comment by topjohnwu** [comment]
Duplicate #460
