### ISSUE TITLE
Magisk App Stuck at Logo

### ISSUE THREAD

**Issue by zputnyq** [topjohnwu/Magisk#5931]
Device: Xperia M4
Android version: 6.0.1 (stock)
Magisk version name: 24316
Magisk version code: 24316

Hi all,
I'm encountering stuck at mogisk logo when trying to open it. Back button is still functioning, no freezing on device just stuck at magisk logo but granting root permission could pop up on app that requested it.
I install this magisk (v24316) by doing clean install /flashing patched boot.img using adb fastboot so there is no left over from previous magisk (v23). I have removed modules before > reboot & then do complete uninstall of v23.

I hope this log could help
[logs-2022-06-07-15-27-24.zip](https://github.com/topjohnwu/Magisk/files/8851635/logs-2022-06-07-15-27-24.zip)

**Comment by yujincheng08** [comment]
try magisk 25

**Comment by zputnyq** [comment]
> try magisk 25

I have tried it & it's the same.

**Comment by yujincheng08** [comment]
launch app. and when it stuck, `su -c kill -s SIGQUIT $(pidof com.topjohnwu.magisk)` and send `/data/anr/trace_*`
