### ISSUE TITLE
Samsung not booting after update

### ISSUE THREAD

**Issue by ToperPlayYT** [topjohnwu/Magisk#5934]
Device: Samsung Galaxy S21 5G (SM-G991B)
Android version: 12
Magisk version name: 25
Magisk version code: 25001

I updated magisk to build 25001, and my samsung stuck on "Samsung Galaxy". I can't provide what happened because i don't have custom recovery.

**Comment by Yilliee** [comment]
Similar result when updating from v24.1 to v25.
The device continuously kept rebooting at the splash screen.

**Comment by canyie** [comment]
Read these to grab log: https://github.com/topjohnwu/Magisk/issues/5607#issuecomment-1072347395 and https://github.com/topjohnwu/Magisk/issues/5607#issuecomment-1072389939

**Comment by canyie** [comment]
Try #5945?
