### ISSUE TITLE
Patching an already patched img result in a bootloop

### ISSUE THREAD

**Issue by Rolodo** [topjohnwu/Magisk#5938]
When patching a stock image and booting it's working fine,
When patching an already patched image the device bootloop.

Here's what I tested 
Working: patching a stock file manualy, then booting with [boot.zip](https://github.com/topjohnwu/Magisk/files/8855801/boot.zip)
fastboot boot .\P6P_a13_b2.1\magisk_patched-[magiskVersion_random].img
Working: patching directly a stock image then rebooting [boot.zip](https://github.com/topjohnwu/Magisk/files/8855801/boot.zip)
Working: repatching an already patched image on the same version

Not working: using my previously patched image (24316) (that booted) 
Direct install, detect an already patched version process then bootloob on reboot
I can reproduce the issue with my saved files [magisk_patched-24316_kVECi.zip](https://github.com/topjohnwu/Magisk/files/8855805/magisk_patched-24316_kVECi.zip)

I do not know if this is a issue affecting other versions as well but it's been 2 updates that did this to my device I was able to fix by repatching the sock image but I'm posting in case this is affecting others as well.

Device:
Android version: 13 Beta 2.1
Magisk version name: cacf8736
Magisk version code: 25001

**Comment by etihwjd** [comment]
Can confirm, flashing latest magisk over a patched boot.img has resulted in a bootloop on P6P

**Comment by Tareku99** [comment]
Installed Magisk v24. App still shows latest to be 24.3. 
Both flashed the zip in recovery and patched the patched_boot and flashed. 
No bootloop... checked root status with different app and it says present but Magisk sayings N/A to installed. 
Buggy release? Tested on android 5.0.2

**Comment by etihwjd** [comment]
Pre-patched [boot.img](https://drive.google.com/file/d/1DbzNBylkmxem9RcRCAQz9JROaRbFTxMB/view?usp=drivesdk) for Android 13 beta 2.1 on P6P (Raven) with Magisk 25.0

**Comment by Hondo77** [comment]
I have experienced a similar behavior. I believe it's been since Canary 24314 and later versions (including Canary 25001) that whenever I update Magisk to a new Canary version via direct install I end up in a bootloop after rebooting. Patching the boot image, however, results in the phone booting up fine. 

Pixel 6 Pro
Android 13 Beta 2.1

**Comment by canyie** [comment]
Ramdisk seems to be corrupted. Related issues: #5722
![image](https://user-images.githubusercontent.com/31466456/172512145-8b7f6a7e-285e-46c2-8071-ef4cc4dee7f1.png)
![image](https://user-images.githubusercontent.com/31466456/172512176-7b5d42d0-8b38-430a-b02a-a75b80f8052a.png)

**Comment by canyie** [comment]
magiskboot backups the previous magiskinit, causing duplicated initializations?
![image](https://user-images.githubusercontent.com/31466456/172514734-3029fe68-51e9-4b72-9c99-89ac97ce3a59.png)
![image](https://user-images.githubusercontent.com/31466456/172514769-ce135417-c494-41ce-95ad-0b75ea28db44.png)
