### ISSUE TITLE
`magiskboot` cannot repack boot.img without ramdisk TWICE

### ISSUE THREAD

**Issue by yujincheng08** [topjohnwu/Magisk#5944]
Device: Pixel 6P
Android version: 13 Beta 2.1
Magisk version name: debug
Magisk version code: 25001

**Comment by canyie** [comment]
https://github.com/topjohnwu/Magisk/issues/5938#issuecomment-1149367676

**Comment by 283665389** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我现在无法亲自回复您的邮件。我将尽快给您回复。
