### ISSUE TITLE
In v17.1 Magisk Hide failing for *all* apps if Chrome is included in the hide list

### ISSUE THREAD

**Issue by paarnoutse** [topjohnwu/Magisk#595]
After upgrading from Magisk 16.0 to 17.1 at my device (OnePlus 5 running OxygenOS 5.1.5), Magisk Hide didn't work anymore.
As a result:
- Even for hided apps, '/sbin' was available in Env. Path
- Therefore root could easily be detected by any app
(eg. by Intune, being a big problem for me)
- For same reason any SafetyNet check failed
- Etc.

Just found the reason for Magisk Hide failing in v17.1 at my device (while all was OK at v16.0):
==> If Chrome is included in the Magisk Hide selection,
==> hiding failed for any app, so it seems to break the
==> Magisk Hide functionality of Magisk v17.1.

After removing Chrome from my hide list, no root detection anymore for the other hided apps, and safenet checks (also the Magisk build-in check) OK now.
In the meantime I've checked/verified this at several other devices, and it looks to be a general Magisk v17.1 behavior.

Logcats available (with and without Chrome being hided, so hiding for other apps working and not working), but not found any indications or errors there.

**Comment by topjohnwu** [comment]
Why would you hide Chrome? It is used as WebView provider, just don't do that.

**Comment by paarnoutse** [comment]
This wasn't intended as a request to make it possible again (like in v16 0) that Chrome (or WebView) can be hided.
It was just to make you aware about the fact that when someone had Chrome in his hide list of Magisk v16.0 (for whatever reason, and useless or not), he will after an upgraden to 17.1 end-up with failing hides for any app WITHOUT having any idea about the reason.

When adding Chrome in the hide list is useless, then - because of the major impact for an unknown reason by the user - I would recommend to check and block/remove Chrome in the Magisk hide list.
It would save a lot of frustration by impacted users...

**Comment by paarnoutse** [comment]
After removing Chrome from the hide list (because in Magisk v17.2 it breaks hiding for any other app), root is detected when accessing Office365 Work account OneDrive / SharePoint URL's via Chrome.
As a result your device registration (device enrollment via Microsoft Intone Company Portal) is removed, and all Microsoft apps (Outlook, OneDrive, SharePoint, Skype for Business etc.) for a Work account will be blocked 😩

Ergo:
Hiding Chrome is *not* useless, and even *required* for Microsoft Intune users to prevent that their device will be blocked.
