### ISSUE TITLE
Magisk 25+ app stuck on splash screen

### ISSUE THREAD

**Issue by whc2001** [topjohnwu/Magisk#5954]
Device: OnePlus 8 Pro
Android version: 11 ([Jaguar V21](https://forum.xda-developers.com/t/rom-11-0_r56-jaguar-oneplus-8-official-v21-updated-june-7-2022.4340771/))
Magisk version name: debug
Magisk version code: cacf8736(25001)

The Magisk app will hang at splash screen (mask logo) if version installed > 24.3. If I install the app with <=24.3 then it works but some of the module I need seem do not support the older version. Root request window still works but app would not enter the main screen.

I found #5931 to be similar however redownloading apk does not help. Running `su -c kill -s SIGQUIT $(pidof com.topjohnwu.magisk)` when stuck generates ANR log is attached:

[logcat.txt](https://github.com/topjohnwu/Magisk/files/8864539/logcat.txt)
[trace_03.txt](https://github.com/topjohnwu/Magisk/files/8864541/trace_03.txt)

**Comment by canyie** [comment]
```
"DefaultDispatcher-worker-6" daemon prio=5 tid=25 Waiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x131c0ca0 self=0xb4000070750bc270
  | sysTid=12822 nice=0 cgrp=default sched=0/0 handle=0x6e8d76b000
  | state=S schedstat=( 0 0 0 ) utm=4 stm=1 core=7 HZ=100
  | stack=0x6e8d5f4000-0x6e8d5f6000 stackSize=1039KB
  | held mutexes=
  at sun.misc.Unsafe.park(Native method)
  - waiting on an unknown object
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:868)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1023)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1334)
  at com.topjohnwu.magisk.core.utils.RootUtils$Connection.await(RootUtils.kt:116)
  at com.topjohnwu.magisk.ui.SplashActivity.preLoad(SplashActivity.kt:117)
  at com.topjohnwu.magisk.ui.SplashActivity.onCreate$lambda-1(SplashActivity.kt:58)
  at com.topjohnwu.magisk.ui.SplashActivity.$r8$lambda$9qxAjDCyE1ve9ERhNJdvTwrQsQA(SplashActivity.kt:-1)
  at com.topjohnwu.magisk.ui.SplashActivity$$ExternalSyntheticLambda1.onShell(D8$$SyntheticClass:-1)
  at com.topjohnwu.superuser.internal.MainShell.lambda$returnShell$0(MainShell.java:60)
  at com.topjohnwu.superuser.internal.MainShell$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:-1)
  at com.topjohnwu.magisk.core.utils.DispatcherExecutor$execute$1.invokeSuspend(DispatcherExecutor.kt:20)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by whc2001** [comment]
> ```
> "DefaultDispatcher-worker-6" daemon prio=5 tid=25 Waiting
>   | group="main" sCount=1 dsCount=0 flags=1 obj=0x131c0ca0 self=0xb4000070750bc270
>   | sysTid=12822 nice=0 cgrp=default sched=0/0 handle=0x6e8d76b000
>   | state=S schedstat=( 0 0 0 ) utm=4 stm=1 core=7 HZ=100
>   | stack=0x6e8d5f4000-0x6e8d5f6000 stackSize=1039KB
>   | held mutexes=
>   at sun.misc.Unsafe.park(Native method)
>   - waiting on an unknown object
>   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
>   at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:868)
>   at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1023)
>   at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1334)
>   at com.topjohnwu.magisk.core.utils.RootUtils$Connection.await(RootUtils.kt:116)
>   at com.topjohnwu.magisk.ui.SplashActivity.preLoad(SplashActivity.kt:117)
>   at com.topjohnwu.magisk.ui.SplashActivity.onCreate$lambda-1(SplashActivity.kt:58)
>   at com.topjohnwu.magisk.ui.SplashActivity.$r8$lambda$9qxAjDCyE1ve9ERhNJdvTwrQsQA(SplashActivity.kt:-1)
>   at com.topjohnwu.magisk.ui.SplashActivity$$ExternalSyntheticLambda1.onShell(D8$$SyntheticClass:-1)
>   at com.topjohnwu.superuser.internal.MainShell.lambda$returnShell$0(MainShell.java:60)
>   at com.topjohnwu.superuser.internal.MainShell$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:-1)
>   at com.topjohnwu.magisk.core.utils.DispatcherExecutor$execute$1.invokeSuspend(DispatcherExecutor.kt:20)
>   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>   at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
>   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
>   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
>   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
>   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
>   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> ```

May I ask if this is about something I can take care of on my end, or for the developers?

**Comment by Displax** [comment]
> for the developers?

Yep.

**Comment by vvb2060** [comment]
```
06-08 15:26:47.784 12344 12344 E IPC     : Error in IPCMain
06-08 15:26:47.784 12344 12344 E IPC     : java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
06-08 15:26:47.784 12344 12344 E IPC     : 	at com.topjohnwu.superuser.internal.RootServerMain.<init>(SourceFile:7)
06-08 15:26:47.784 12344 12344 E IPC     : 	at com.topjohnwu.superuser.internal.RootServerMain.main(Unknown Source:23)
06-08 15:26:47.784 12344 12344 E IPC     : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-08 15:26:47.784 12344 12344 E IPC     : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
06-08 15:26:47.784 12344 12344 E IPC     : Caused by: java.lang.reflect.InvocationTargetException
06-08 15:26:47.784 12344 12344 E IPC     : 	at java.lang.reflect.Method.invoke(Native Method)
06-08 15:26:47.784 12344 12344 E IPC     : 	at com.topjohnwu.superuser.internal.RootServerMain.<init>(SourceFile:5)
06-08 15:26:47.784 12344 12344 E IPC     : 	... 3 more
06-08 15:26:47.784 12344 12344 E IPC     : Caused by: java.lang.RuntimeException: Unable to instantiate Application():java.lang.RuntimeException: Unable to instantiate application android.app.Application: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
06-08 15:26:47.784 12344 12344 E IPC     : 	at android.app.ActivityThread.attach(ActivityThread.java:7389)
06-08 15:26:47.784 12344 12344 E IPC     : 	at android.app.ActivityThread.systemMain(ActivityThread.java:7433)
06-08 15:26:47.784 12344 12344 E IPC     : 	... 5 more
06-08 15:26:47.784 12344 12344 E IPC     : Caused by: java.lang.RuntimeException: Unable to instantiate application android.app.Application: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
06-08 15:26:47.784 12344 12344 E IPC     : 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1270)
06-08 15:26:47.784 12344 12344 E IPC     : 	at android.app.ActivityThread.attach(ActivityThread.java:7385)
06-08 15:26:47.784 12344 12344 E IPC     : 	... 6 more
06-08 15:26:47.784 12344 12344 E IPC     : Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
06-08 15:26:47.784 12344 12344 E IPC     : 	at com.android.internal.gmscompat.dynamite.GmsDynamiteHooks.initGmsServerApp(GmsDynamiteHooks.java:81)
06-08 15:26:47.784 12344 12344 E IPC     : 	at com.android.internal.gmscompat.GmsHooks.initApplicationBeforeOnCreate(GmsHooks.java:209)
06-08 15:26:47.784 12344 12344 E IPC     : 	at android.app.Instrumentation.newApplication(Instrumentation.java:1163)
06-08 15:26:47.784 12344 12344 E IPC     : 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1262)
06-08 15:26:47.784 12344 12344 E IPC     : 	... 7 more
06-08 15:26:47.784 12344 12344 I com.topjohnwu.magisk:root: System.exit called, status: 1
```
