### ISSUE TITLE
Bootloop after OTA

### ISSUE THREAD

**Issue by capntrips** [topjohnwu/Magisk#5959]
Device: Pixel 6 Pro
Android version: 12.1 (SQ3A.220605.009.B1)
Magisk version name: cacf8736
Magisk version code: 25001

The standard OTA process from the [guide](https://topjohnwu.github.io/Magisk/ota) was followed, but it bootlooped. Here's the log:

[console-ramoops-0.log](https://github.com/topjohnwu/Magisk/files/8876167/console-ramoops-0.log)

The relevant lines seem to be:

```
[    1.257611][    T1] init: [libfs_mgr]Created logical partition system_b on device /dev/block/dm-0
...
[    1.263952][    T1] init: [libfs_avb]Returning avb_handle with status: Success
[    1.264042][    T1] init: [libfs_avb]Built verity table: '1 /dev/block/dm-0 /dev/block/dm-0 4096 4096 216517 216517 sha256 b5abedbc7a21e42b338ea3977800ccc43a5cd0e3a682afeee52271a552ca7c20 1a5edec5bd4392e3181b5f908b2a446b31116d8e8010660bd5035b16c539a51f 10 use_fec_from_device /dev/block/dm-0 fec_roots 2 fec_blocks 218224 fec_start 218224 restart_on_corruption ignore_zero_blocks'
[    1.264207][    T1] device-mapper: verity: sha256 using implementation "sha256-ce"
[    1.264717][    T1] init: [libfs_mgr]Set readahead_kb: 128 on /sys/class/block/dm-10/queue/read_ahead_kb
[    1.264754][    T1] init: [libfs_mgr]Set readahead_kb: 128 on /sys/class/block/dm-0/queue/read_ahead_kb
[    1.264803][    T1] init: [libfs_mgr]Set readahead_kb: 128 on /sys/class/block/sda26/../queue/read_ahead_kb
[    1.266138][  T265] device-mapper: verity-fec: 254:0: FEC: recursion too deep
[    1.266142][  T265] device-mapper: verity: 254:0: metadata block 216517 is corrupted
[    1.266158][  T265] debug-reboot: Create reboot monitor timer now
[    1.269090][  T265] Reboot command: 'dm-verity device corrupted'
```

Note this is not from a device I have access to. It has happened every month. This is on the stock ROM with the stock kernel. Booting from the patched image after installing the latest build with the flash tool works without issue.

There are a handful of people on the forums that seem to have the same issue, though I haven't seen any logs, but I suspect this isn't an isolated issue.

**Comment by SammCheese** [comment]
Device: Pixel 6
Android version: 13 (TPB3.220513.017)
Magisk version name: cacf873
Magisk version code: 25001

Can confirm this issue.

Patching the Inactive slot after an OTA Update and rebooting results in a Bootloop.

Patching a boot.img via magisk and flashing it over fastboot manually allows the device to boot normally with root.

This issue seems to have started with #5825

**Comment by vvb2060** [comment]
The OTA feature doesn't work on pixel devices.

**Comment by vvb2060** [comment]
Fix it requires implementing the partition digest calculation to overwrite the original value, PR welcome.

https://android.googlesource.com/platform/system/update_engine/

**Comment by bugith** [comment]
I don't know if this was fixed, but [this time](https://xdaforums.com/t/nothing-phone-1-repo-nos-ota-img-guide-root.4464039/post-90484819) I didn't meet bootloop
