### ISSUE TITLE
cacf8736 cause Screen flashing

### ISSUE THREAD

**Issue by maxdarksol** [topjohnwu/Magisk#5968]
Device:Xiaomi MI8(Dipper)
Android version:10 (stock MIUI12.5.2) kernel:4.9.186-perf-g10af704
Magisk version name:cacf8736
Magisk version code:(25001)(D)
更新后遭遇闪屏，可以正常进入系统，但在系统界面或用户app内，会不定时无预兆的黑屏1秒随即自行点亮，但录屏不体现闪屏，包括beta版25000也存在这个问题，回退至24.3恢复正常。

**Comment by fariborz4** [comment]
Hi

**Comment by fariborz4** [comment]
Hi

**Comment by vvb2060** [comment]
没有日志
