### ISSUE TITLE
Unchecked Recovery mode but Magisk still install it into Recovery image instead of Boot image

### ISSUE THREAD

**Issue by HuskyDG** [topjohnwu/Magisk#5972]
Device: Redmi Note 7
Android version: 11
Magisk version name: 6f74ed6c
Magisk version code: 25001
Ramdisk: No

When update Magisk app to 6f74ed6c and open, Magisk automatically check Recovery Mode buy Magisk is installed into boot image. My device does not have ramdisk in boot image but install Magisk into boot image is working.
![Screenshot_20220613-180508717](https://user-images.githubusercontent.com/84650617/173341554-d89d013c-4bbb-4d86-b687-7fa6dfcb2a6c.jpg)

Then I uncheck Recovery Mode to let Magisk app install Magisk into boot image :

![Screenshot_20220613-180513335](https://user-images.githubusercontent.com/84650617/173341703-49b0bfa8-64f7-49d1-b75a-fe869a0016b8.jpg)

But while installing, Magisk detect and install into `/dev/block/by-name/mmcblk0p61` (recovery image device block)
![Screenshot_20220613-180531037](https://user-images.githubusercontent.com/84650617/173342106-ee55edd3-66e4-4c0a-856a-b2cab7c86141.jpg)

Check command in Terminal:
![Screenshot_20220613-180601311](https://user-images.githubusercontent.com/84650617/173342270-57182a2e-9b3c-4556-b612-d53240ffbac5.jpg)

I guess 2248af00f3cb33e560bc378fd41f9b3b6c9a85d7 cause this problem

**Comment by HuskyDG** [comment]
I guess the problem can be reproduced on device SAR A-only so i think i don't need to include bugreport or log.

**Comment by canyie** [comment]
`cat $(magisk --path)/.magisk/config` ?

**Comment by HuskyDG** [comment]
> `cat $(magisk --path)/.magisk/config` ?

Empty

**Comment by canyie** [comment]
Looks like the same problem as #5673:
1. The checkbox doesn't work
2. MagiskInit not extracting magisk config to `MAGISKTMP`

**Comment by canyie** [comment]
Can you capture a kernel log on boot?

**Comment by HuskyDG** [comment]
> Can you capture a kernel log on boot?

[last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/8890810/last_kmsg.txt)

**Comment by HuskyDG** [comment]
Maybe you will ask installation log so I will drop it here

[magisk_install_log_2022-06-13T19.06.09.log](https://github.com/topjohnwu/Magisk/files/8890865/magisk_install_log_2022-06-13T19.06.09.log)

**Comment by canyie** [comment]
https://github.com/topjohnwu/Magisk/blob/6f74ed6cebe3d1f5a69ee53e91ac4616ddb88440/native/jni/init/twostage.cpp#L67-L69
https://github.com/topjohnwu/Magisk/blob/6f74ed6cebe3d1f5a69ee53e91ac4616ddb88440/native/jni/init/rootdir.cpp#L142-L143

typo?

**Comment by canyie** [comment]
Can you test if `$(magisk --path)/.magisk/config` is not empty on this build?
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8891126/app-debug.zip)

**Comment by HuskyDG** [comment]
> Can you test if `$(magisk --path)/.magisk/config` is not empty on this build? [app-debug.zip](https://github.com/topjohnwu/Magisk/files/8891126/app-debug.zip)

Seem like it fixed
![Screenshot_20220613-202404630](https://user-images.githubusercontent.com/84650617/173363705-08781282-b704-495d-b465-d23d8d157e8d.jpg)
![Screenshot_20220613-202411993](https://user-images.githubusercontent.com/84650617/173363714-74b198a1-1a7e-488d-a9ae-ac285b502c1f.jpg)
