### ISSUE TITLE
Unable to access /data/data on Android 11 with a root file explorer (2)

### ISSUE THREAD

**Issue by Joey11904** [topjohnwu/Magisk#5974]
Device: Motorola G5s Plus (sanders)
Android version: 11
Magisk version name: cacf8736
Magisk version code: 25001

(Opening this again after #5973 was accidentally closed by the bot)

When accessing /data/data with root file explorer, only the app's data folder and Google Play Services folder (com.google.android.gms) appear, other app folders somehow "disappear." But when I run su directly (like from Termux), and list /data/data from there, all folders appear just fine.

Magisk log: [magisk_log_2022-06-13T18.56.07.log](https://github.com/topjohnwu/Magisk/files/8891048/magisk_log_2022-06-13T18.56.07.log)
Logcat: [logcat.zip](https://github.com/topjohnwu/Magisk/files/8891054/logcat.zip)

![Screenshot_20220613-182532054](https://user-images.githubusercontent.com/33566635/173355193-fc0e632c-44a5-435a-ae3e-64ddd34e6ef9.jpg)
![Screenshot_20220613-182557686](https://user-images.githubusercontent.com/33566635/173355210-8b49eded-bdf9-4f04-b3a8-14def14deb8a.jpg)

**Comment by HuskyDG** [comment]
Use any file manager use `su -mm` such as [Material Files](https://f-droid.org/en/packages/me.zhanghai.android.files) or change Mount namespace mode to Global

**Comment by Joey11904** [comment]
> Use any file manager which use `su -mm` command such as [Material Files](https://f-droid.org/en/packages/me.zhanghai.android.files) or change Mount namespace mode to Global

Changed mount namespace to global and it works now. Thanks! :smiley:
