### ISSUE TITLE
CrackProof has detected magisk

### ISSUE THREAD

**Issue by MoePus** [topjohnwu/Magisk#599]
A newly installed android with only Magisk manger can be detected.
as well as a rooted(by magisk) phone without the manger can be detected.
even su is disabled(NO app or adb),magisk can be detected.
also MagiskHide is on.

CrackProof is a shell by an odd company.It can 'protect' programs on android and windows or the other platform.
I guess it scans every name of mainfest.xml of the package.....I am not familiar with how root works...

the sample can be found in game
princess connect redive
or other top games from dmm player.

wish you can beat the dirty shell.

**Comment by topjohnwu** [comment]
It is already fixed upstream and you should try out Canary builds before opening an issue here.....
Go read the "Bug Report" section in the README
