### ISSUE TITLE
hiding/restoring app not always working

### ISSUE THREAD

**Issue by RV7PR** [topjohnwu/Magisk#5998]
Device: Samsung Galaxy A53 SM-A536B
Android version: 12
Magisk version name: b9c93c66 (latest actions build)
Magisk version code: 25001

half of the time restoring/hiding magisk app is not working

[magisk_log_2022-06-18T16.18.38.log](https://github.com/topjohnwu/Magisk/files/8933771/magisk_log_2022-06-18T16.18.38.log)

![Screenshot_20220618-161230](https://user-images.githubusercontent.com/17615589/174442797-81bf59c5-fa32-4e33-a47a-7cf3dabc1c4c.jpg)

**Comment by topjohnwu** [comment]
This should fix your issue: 9fd1f41e8b8314be2acaee32f44f7a4e4969f06e

**Comment by RV7PR** [comment]
It's still happening😕
[magisk_log_2022-06-19T11.49.48.log](https://github.com/topjohnwu/Magisk/files/8935092/magisk_log_2022-06-19T11.49.48.log)

**Comment by TanMusong** [comment]
Turning off all modules before hide Magisk, it works for me.
