### ISSUE TITLE
Magisk not working on Nexus 5 LineageOS 14.1

### ISSUE THREAD

**Issue by LutzPS** [topjohnwu/Magisk#60]
Boot: https://www.mediafire.com/?qw1umufupg82152

Thank you

**Comment by Didgeridoohan** [comment]
Any details? What does "not working" mean? Can it install? Does it bootloop? No root? Etc...

Logs are a good thing as well. Recovery log, Magisk log, logcat, whatever's applicable.

**Comment by LutzPS** [comment]
All functions ok, but safetynet not bypass.

**Comment by Didgeridoohan** [comment]
Then it's not Magisk that's malfunctioning, but possibly Magisk Hide. Can you hide root from root apps? Try adding a root checker to the Hide list and see if it recognises root or not. If that works Magisk Hide is functioning and your setup has something that triggers SafetyNet. 

Until you can show that there's a bug with Magisk Hide causing SafetyNet to trigger, this topic is better suited for the Magisk support thread on xda. I'd close this issue if I were you...

**Comment by LutzPS** [comment]
I tried this **"Can you hide root from root applications? Try adding a root checker to the Hide list and see if it recognizes root or not."**, hide root ok, but and safetynet can not pass;
Maybe that **"If this works Magisk Hide is working and your configuration has something that triggers the SafetyNet"**, how can I know what triggers the SafetyNet?

**Comment by Didgeridoohan** [comment]
Close this issue and go here: https://forum.xda-developers.com/showpost.php?p=70426733&postcount=7120

If you need further help after that you can post in the Magisk support thread.
