### ISSUE TITLE
Bootloop on non-2SI SAR Samsung device

### ISSUE THREAD

**Issue by TenSeventy7** [topjohnwu/Magisk#6000]
Device: Samsung Galaxy A50 (SM-A505GN)
Android version: 12
Magisk version name: bb64ba0ef6a9bdbfcb1a2ceb4e4900f94b0deb95
Magisk version code: 25101

My Samsung Galaxy A50 running Android 12 fails to boot on the latest beta and canary releases. I couldn't fetch other Magisk logs and can only pull `last_kmsg` as the device is stuck at the splash screen and never proceeds to the boot animation.

The way Magisk is installed on the device is by forcing and 'embedding' an initramfs during kernel build time. Could this be a problem? It was/is booting on Magisk v24.3.

Attached here is the kernel log as well as the built kernel image.

[boot.zip](https://github.com/topjohnwu/Magisk/files/8935427/boot.zip)
[last_kmsg.log](https://github.com/topjohnwu/Magisk/files/8935425/last_kmsg.log)

**Comment by yujincheng08** [comment]
<12>[    2.132492]  [4:           init:    1] magiskinit: open: /proc/bootconfig failed with 2: No such file or directory
<12>[    2.215205]  [4:           init:    1] magiskinit: mknod failed with 2: No such file or directory
<12>[    2.215265]  [4:           init:    1] magiskinit: mount /dev/root->/system_root failed with 2: No such file or directory
<12>[    2.215729]  [4:           init:    1] magiskinit: mount /dev/root->/system_root failed with 19: No such device
<12>[    2.215736]  [4:           init:    1] magiskinit: Cannot mount root partition, abort

**Comment by canyie** [comment]
Please capture kmsg with debug builds.

**Comment by TenSeventy7** [comment]
> Please capture kmsg with debug builds.

Hello! This is a kmsg with a debug build.

[last_kmsg_debug.log](https://github.com/topjohnwu/Magisk/files/8935510/last_kmsg_debug.log)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8935645/app-debug.zip)
try this

**Comment by vvb2060** [comment]
```
ANDROID! magic found at: 0
BOARD_KERNEL_CMDLINE androidboot.selinux=permissive androidboot.selinux=permissive loop.max_part=7
BOARD_KERNEL_BASE 0x10000000
BOARD_NAME SRPRL05B007KU
BOARD_PAGE_SIZE 2048
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0xf0000000
BOARD_SECOND_OFFSET 0xf0000000
BOARD_TAGS_OFFSET 0x00000100
BOARD_OS_VERSION 12.0.0
BOARD_OS_PATCH_LEVEL 2022-01
BOARD_HEADER_VERSION 1
BOARD_HEADER_SIZE 1648

Warning: No ramdisk found to be unpacked!

Done!
```

ramdisk.cpio created by magiskboot does not have `/dev`

**Comment by 3arthur6** [comment]
Same issue with another Samsung phone, S20 Ultra (SM-G988N).



> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/8935645/app-debug.zip) try this

The problem persists with this one too. I attach the built boot image and last_kmsg.

[last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/8936477/last_kmsg.txt)
[boot.zip](https://github.com/topjohnwu/Magisk/files/8936478/boot.zip)

**Comment by TenSeventy7** [comment]
> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/8935645/app-debug.zip) try this

**Confirmed booting on my device.** Thank you very much for the help!

Here is the booting log, if it helps anyone:

[booting.log](https://github.com/topjohnwu/Magisk/files/8936668/booting.log)

**Comment by pndwal** [comment]
Question.

Does this:
> ramdisk.cpio created by magiskboot does not have `/dev`

affect only to A-only Legacy SAR devices (no OEM ramdisk in boot), or can A/B non-2SI SAR devices be affected?... (and If so, can 2SI devices be affected?)
