### ISSUE TITLE
Resigned with own keys Magisk v25.1 can' be hided

### ISSUE THREAD

**Issue by tsynik** [topjohnwu/Magisk#6002]
Custom Magisk v25.1 build from source with build.py -r all and own certs defined in config.sh can't be hided - after repackaging stub and downloading current.apk from custom releases link magisk daemon throws an error:

```
06-19 17:30:51.056   193  1820 W Magisk  : pkg: cannot find manager for user=[0]
06-19 17:30:52.051  6171  6171 E J       : 	at com.topjohnwu.magisk.core.App.<init>(SourceFile:6)
06-19 17:32:23.588   193  4832 E Magisk  : cert: invalid APK format
06-19 17:32:23.588   193  4832 E Magisk  : pkg: dyn APK signature mismatch: /data/user_de/0/igmdrqaqetcfjc.ag/dyn/current.apk
06-19 17:32:23.660  6320  6320 I Magisk  : pm_clear: igmdrqaqetcfjc.ag (user=0) 
06-19 17:32:32.152  6350  6350 I Magisk  : pm_clear: Success 
06-19 17:32:32.154   193  4832 W Magisk  : pkg: cannot find manager for user=[0]
```
![dl-link](https://user-images.githubusercontent.com/1551446/174486878-fea3c560-e7ad-4b65-98c7-3e187b964ffe.png)

Same apk works with daemon when not hided (no signature issues).
Source and release apk can be found here - https://github.com/tsynik/Magisk/releases

Device: Fire TV
Android version: 7.2.1
Magisk version name: v25.1
Magisk version code: 25101

**Comment by HuskyDG** [comment]
Magisk with `version code % 100 != 0` will be considered as Magisk Canary. And the url `https://github.com/tsynik/Magisk/releases/download/${Config.version}/app-release.apk` in picture is only used if Magisk stub is not `canary`

**Comment by tsynik** [comment]
> Magisk with `version code % 100 != 0` will be considered as Magisk Canary. And the url `https://github.com/tsynik/Magisk/releases/download/${Config.version}/app-release.apk` in picture is only used if Magisk stub is not `canary`

Link was correct - canary defined in build.gradle.kts as !Config.version.contains("."). I found the source of the issue: that error was not from certs and also existed on debug builds where was no certs verification. It was uninitialized AppContext from modified Info.kt code.
