### ISSUE TITLE
Add file with checksums for all assets

### ISSUE THREAD

**Issue by Kayetic** [topjohnwu/Magisk#6008]
Would it be possible to attach a file with each release that contains the official checksums for all the assets?
So that we can verify the files we download.

**Comment by przemolb** [comment]
This issue is **not** relevant to any version of Magisk.
Because you don't have any other type of ticket (i.e.: RFE or feature) he had to use an "issue" as the type of ticket.
Please open it again and consider the checksums as it will increase the security of distribution of Magisk files.
