### ISSUE TITLE
Enable wiki for this repository

### ISSUE THREAD

**Issue by dovatti** [topjohnwu/Magisk#6010]
I think it would be useful to enable `wiki` for this repository since Magisk does not have an official website ([this](magiskmanager.com) is not the official website and you **_might not_** download anything from here).
In wiki we could help to create better documentation both for installing, developing, creating issues, and more.
Another reason for doing so: we could debloat [`README.md`](https://github.com/topjohnwu/Magisk/blob/master/README.MD) making it shorter and nicer.

I think anyone could help to create this `wiki` page for documentation, and if doing so, Magisk could improve itself a lot.
Note: I know the existence of [`this`](https://topjohnwu.github.io/Magisk/) but I think it should be document directly here, in the official repository.

**Comment by yujincheng08** [comment]
https://topjohnwu.github.io/Magisk/

official
