### ISSUE TITLE
Magisk patched img not flashing 

### ISSUE THREAD

**Issue by hasanbd80** [topjohnwu/Magisk#6018]
Device: i97
Android version: 9
Magisk version name: 9183a0a6
Magisk version code: 25101
Fastboot screen : "fastboot mode
                           info : lock flag is unlock !"
I have waited for 1 min but not flashing . I waited 5 minutes in the previous attempt not flashing patched recovery img

![image](https://user-images.githubusercontent.com/101275948/175020113-b34f3fe9-a291-4790-9901-b1f86010ff0d.png)

log :
- Device platform: arm64-v8a
- Installing: 9183a0a6 (25101)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [1]
KERNEL_SZ       [17299864]
RAMDISK_SZ      [8013086]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [1022]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2019-07]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyS1,115200n8 buildvariant=user]
CHECKSUM        [9859a75224aa288473aabd0389db153795ea54bf000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
VBMETA
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Patch @ 00C89BE6 [736B69705F696E697472616D667300] -> [77616E745F696E697472616D667300]
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [1]
KERNEL_SZ       [17299864]
RAMDISK_SZ      [8013086]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [1022]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2019-07]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyS1,115200n8 buildvariant=user]
CHECKSUM        [9859a75224aa288473aabd0389db153795ea54bf000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [1]
KERNEL_SZ       [17299864]
RAMDISK_SZ      [8445874]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [1022]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2019-07]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyS1,115200n8 buildvariant=user]
CHECKSUM        [30d0c3c46259ea948d756a80972358ef1a28971b000000000000000000000000]

****************************
 Output file is written to 
 /storage/emulated/0/Download/magisk_patched-25101_Yx9By.img 
****************************
cp: can't preserve ownership of 'busybox': Operation not permitted
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
cp: can't preserve ownership of 'magiskpolicy': Operation not permitted
- All done!

**Comment by hasanbd80** [comment]
Please also check My previous issue on this 
https://github.com/topjohnwu/Magisk/issues/5601

**Comment by tony8077616** [comment]
> Hi, how did you get 25101? Only 25100 is available. You built it?

You can always get the Magisk CI build version in Action

**Comment by hasanbd80** [comment]
> does previous version of Magisk work?

I am trying to root my phone from magisk 22

**Comment by yujincheng08** [comment]
Then it's not Magisk's issue. Check your USB cable or so.

**Comment by hasanbd80** [comment]
> Then it's not Magisk's issue. Check your USB cable or so.

i unplugged usb after waiting 1-5 min

**Comment by gitclone-url** [comment]
> 

Buy a new phone man

**Comment by mnnbjv04-collab** [comment]
> Use debug build. https://github.com/topjohnwu/magisk-files/raw/canary/app-debug.apk
