### ISSUE TITLE
Magisk with safetynet pass app bank blocked

### ISSUE THREAD

**Issue by RyukSniper** [topjohnwu/Magisk#602]
Hi, my mom have One Plus 2 with android 8.1 with magisk 17 and bank app detect root with magisk hide activate and whiout magisk manager app, bank app work. Can have magisk manager app installed and bank app work? How change name apk magisk?

**Comment by Entropy512** [comment]
Magisk Manager has a separate "hide magisk manager" option (it's in Settings for the manager, it's independent of MagiskHide).

You may need to delete your old MagiskManager folder after enabling this feature.

**Comment by RyukSniper** [comment]
@Entropy512 very thanks :D
