### ISSUE TITLE
 Patching Fails With Process Error

### ISSUE THREAD

**Issue by ethanhall** [topjohnwu/Magisk#6032]
Fresh OEM flash, full reset, Magisk first app installed.

Following instructions:

https://topjohnwu.github.io/Magisk/install.html

Ramdisk: No
Device: Samsung Note 10+ (SM-N975F/DS - D2S)
Android version: 12 (XXV)
Magisk version name:app-debug.apk (com.topjohnwu.magisk)
Magisk version code: 9183a0a6 (25101)(D)

Log:

- Device platform: arm64-v8a
- Installing: 9183a0a6 (25101)
- Processing tar file
-- Extracting: boot.img
-- Extracting: recovery.img
! Process error
! Installation failed

Image:

Sourced from samloader on linux.
AP_N975FXXU8HVE5_CL24230781_QB51756434_REV01_user_low_ship_meta_OS12.tar.md5

App log, boot and recovery images- download below, too large to attach here.
https://filedn.eu/luiVtu7Eqcn8hlYx5SlY3iV/

**Comment by pndwal** [comment]
This?:
https://github.com/topjohnwu/Magisk/issues/6000

Try this:
https://github.com/topjohnwu/Magisk/issues/6000#issuecomment-1159733754

or this Actions run build:
[Create `/dev` on stub cpio](https://github.com/topjohnwu/Magisk/actions/runs/2541799970)
... Extract from zip in artifacts...

**Comment by canyie** [comment]
```
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: java.io.IOException: Content checksum mismatch
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at net.jpountz.lz4.LZ4FrameInputStream.readBlock(LZ4FrameInputStream.java:259)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at net.jpountz.lz4.LZ4FrameInputStream.read(LZ4FrameInputStream.java:344)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at java.io.FilterInputStream.read(FilterInputStream.java:133)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at java.io.FilterInputStream.read(FilterInputStream.java:107)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:110)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.cleanPump(MagiskInstaller.kt:168)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.processTar(MagiskInstaller.kt:198)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.handleFile(MagiskInstaller.kt:276)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.patchFile(MagiskInstaller.kt:409)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Patch.operations(MagiskInstaller.kt:457)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$result$1.invokeSuspend(MagiskInstaller.kt:426)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by ethanhall** [comment]
> ```
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: java.io.IOException: Content checksum mismatch
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at net.jpountz.lz4.LZ4FrameInputStream.readBlock(LZ4FrameInputStream.java:259)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at net.jpountz.lz4.LZ4FrameInputStream.read(LZ4FrameInputStream.java:344)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at java.io.FilterInputStream.read(FilterInputStream.java:133)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at java.io.FilterInputStream.read(FilterInputStream.java:107)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:110)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.cleanPump(MagiskInstaller.kt:168)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.processTar(MagiskInstaller.kt:198)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.handleFile(MagiskInstaller.kt:276)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.patchFile(MagiskInstaller.kt:409)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Patch.operations(MagiskInstaller.kt:457)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$result$1.invokeSuspend(MagiskInstaller.kt:426)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
> 06-24 00:50:47.467 26265 26287 E MagiskInstallImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> ```

Thanks.  So does this indicate that the AP archive is corrupt?  Or is it necessary to convert the .md5 to .tar?

**Comment by pndwal** [comment]
If that's the case, did you transfer the AP using MTP?...

If so, nb. instruction (for Samsung (System-as-root)):
> Start the installation, and copy the patched tar file to your PC using ADB:
adb pull > /sdcard/Download/magisk_patched_[random_strings].tar
> DO NOT USE MTP as it is known to corrupt large files.

and try again using ADB pull... MTP transfer issues are a common problem w/ Magisk for Samsung...

**Comment by ethanhall** [comment]
> If that's the case, did you transfer the AP using MTP?...
> 
> If so, nb. instruction (for Samsung (System-as-root)):
> 
> > Start the installation, and copy the patched tar file to your PC using ADB:
> > **adb pull** > /sdcard/Download/magisk_patched_[random_strings].tar
> > **DO NOT USE MTP** as it is known to corrupt large files.
> 
> and try again using ADB pull... MTP transfer issues are a common problem w/ Magisk for Samsung...

I followed the instructions to the letter.  I coped the AP file directly to the SD card plugged into the slot on my laptop, and then moved the card to the phone.

**Comment by Nemris** [comment]
Leaving this here in case it's useful - for an A40 with system-as-root, it's possible to patch just the boot.img, taken from the boot.tar.lz4, itself from the AP part of the .zip. You will need the appropriate tools for handling LZ4, though, depending on your distro.

**Comment by ethanhall** [comment]
> Leaving this here in case it's useful - for an A40 with system-as-root, it's possible to patch just the boot.img, taken from the boot.tar.lz4, itself from the AP part of the .zip. You will need the appropriate tools for handling LZ4, though, depending on your distro.

Interesting, thanks for this and the other helpful comments.

I solved by the issue by doing two things: downloading a new stock image with a different CSC code (BTC), and using Firja instead samloader for the download.  Even though the ROM was performing well on the phone, there must have been something in it that Magisk did not like.
