### ISSUE TITLE
Is this the cause of Magisk Hide/Saftety Net we face?

### ISSUE THREAD

**Issue by ThotSoft** [topjohnwu/Magisk#604]
For post-installation to succeed, the old kernel must be able to:
Mount the new filesystem format: The filesystem type cannot change unless there's support for it in the old kernel, including details such as the compression algorithm used if using a compressed filesystem (i.e. SquashFS).
Understand the new partition's post-install program format: If using an Executable and Linkable Format (ELF) binary, it should be compatible with the old kernel (e.g. a 64-bit new program running on an old 32-bit kernel if the architecture switched from 32- to 64-bit builds). Unless the loader (ld) is instructed to use other paths or build a static binary, libraries will be loaded from the old system image and not the new one.

**Comment by topjohnwu** [comment]
I don't understand what you are talking about
