### ISSUE TITLE
Direct Install reports success but doesn't update Magisk

### ISSUE THREAD

**Issue by aricooperdavis** [topjohnwu/Magisk#6051]
Device: POCO M4 Pro (Fleur)
Android version: 11.0.0
Magisk version name: 9183a0a6 
Magisk version code: 25101

I am trying to update to v25.1 so I update the Magisk App to the most recent debug build, which works. I then try and update Magisk (the system) via the Magisk App which also appears to work:

[magisk_install_log_2022-06-28T09.18.23.log](https://github.com/topjohnwu/Magisk/files/8999076/magisk_install_log_2022-06-28T09.18.23.log)

However, on reboot the Magisk App gives me the "Requires Additional Setup" message, as the Magisk (system) version that it reports is still 25000 - the Direct Install update doesn't appear to have worked.

Following the process again, as prompted by the message, doesn't sucessfuly update Magisk either.

The weird thing is that if I patch the stock boot.img using the Magisk app and flash it manually using fastboot it does work, so this must be an issue with the way that the Magisk app is flashing the boot.img.

**Comment by pndwal** [comment]
If you ever used Hide the Magisk app, uninstall all Magisk apps, both full app and stub ('hidden').app (look for 'Settings' or custom name you chose in device settings, Apps)... Then reinstall full 25101 Canary or Debug App...

**Comment by aricooperdavis** [comment]
Thanks for the tip. In this case I have never used "Hide the Magisk app", nor are there any magisk modules installed, Zygisk is not enabled, there is nothing on the Deny List etc. It's a brand new Magisk install.

**Comment by fenix7guerra** [comment]
Same problem in Redmi Note 8 (Ginkgo)

**Comment by pndwal** [comment]
> Same problem in Redmi Note 8 (Ginkgo)

That's strange; thats different device type (A-only legacy SAR)...

Also, I have RN8T (same boot type) W/ Android 10, and had no such issue taking Direct install from 25001 to 25101 (Canary)...

**Comment by aricooperdavis** [comment]
> Same problem in Redmi Note 8 (Ginkgo)

What Android version?

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/blob/70fd03d5fc7f7864730e4ccfe2db0f6e20d715a7/scripts/util_functions.sh#L493

Your device's kernel prevents writing to the boot partition at runtime.  We've done our best to detect this, but your device is an exception.  You can only flash boot with fastboot.

**Comment by aricooperdavis** [comment]
Interesting! Would this appear in a log, and if so which one?

**Comment by LorrdWealth** [comment]
I'm currently facing this. What solution did you do to get it solved

**Comment by pndwal** [comment]
> I'm currently facing this. What solution did you do to get it solved

A few devices are like this:

> Your device's kernel prevents writing to the boot partition at runtime. We've done our best to detect this, but your device is an exception. You can only flash boot with fastboot.

So you will simply need to do initial installation (patch boot image using app and flash with fastboo6 etc) instead of normal Direct install each time you update Magisk... 😉
