### ISSUE TITLE
Magisk not detected in recovery mode after install

### ISSUE THREAD

**Issue by neo279** [topjohnwu/Magisk#6055]
Device: SM-A405FN/DS
Android version: 11
Magisk version name: v25.1
Magisk version code: 25101(D)

Magisk app reports N/A for installed status, phone does not have RAM Disk and I did follow special case to Samsung install instructions.

Trying to root clean stock firmware, patching seems to be successful.

When booting in Android Recovery, I can see a message in kernel log about magiskinit disabling system-as-root due to volume up key detected and following with Android Recovery init not Android Init.

I am not able to download such logs from booted recovery as my phone does not seem to be rooted.

[logcat.txt](https://github.com/topjohnwu/Magisk/files/9023318/logcat.txt) (debug enabled)
[install-log-251.txt](https://github.com/topjohnwu/Magisk/files/9023320/install-log-251.txt)

[recovery.zip](https://github.com/topjohnwu/Magisk/files/9023328/recovery.zip)

I do receive a vibration before splash screen when booting into recovery mode, which does not happen with regular boot, that's the only way I think I am in recovery mode where Magisk should be enabled.

I can use the phone (I don't experience bootloops or restarts), but Magisk does not seem to be initialized.

**Comment by yujincheng08** [comment]
plz capture a bugreport
