### ISSUE TITLE
Detected by a specific app and rejected

### ISSUE THREAD

**Issue by vivian8421** [topjohnwu/Magisk#6056]
Device: Mi10U
Android version:12
Magisk version name:4eb71830-alpha
Magisk version code:25101

Be detected by a specific application like '360jiagu.so'(such as YiDongHuiShengHuo PackageName:com.sitech.ac) and prompt 'there is a certain risk of the environment being root' and then flash back
 After analysis, the detection method is kernel detection, when boot.img patched will be prohibited 
 This detection method will invalidate the root defense measures  and MagiskHide/Riru/Zygisk will be exposed
Can you prevent this kind of kernel detection? Thank you.

**Comment by topjohnwu** [comment]
No
