### ISSUE TITLE
ps4 remote play 2.70 can detect root with magisk hide

### ISSUE THREAD

**Issue by pbbqdd** [topjohnwu/Magisk#606]
Magisk version 17.1 the lastest PS4 remote play return 88001003 error when app lunch.but 2.60 don't with the same setting.

**Comment by topjohnwu** [comment]
Confirmed, thanks for the report!

**Comment by Billym254** [comment]
Thank you topjohnwu. Any workround while using the latest ps4 remote play..I am using Magisk 18.1 but still getting the 88001003 error

**Comment by ahjsrhj** [comment]
hiding Magisk Manager works just fine

**Comment by orangpelupa** [comment]
its detected again on latest ps4 remoteplay despite magisk already repacked and hidden from ps4 remoteplay

**Comment by lividhen** [comment]
I am now having this issue
