### ISSUE TITLE
Magisk Build issues on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by localacct** [topjohnwu/Magisk#6066]
Hi

I am building the Magisk repository on Ubuntu 22.04 LTS VM (built from scratch) and I have followed the instructions on (https://github.com/topjohnwu/Magisk)

- git clone the repository
- Install Android Studio from apt
- Install Python 3.10 (Already comes with Ubuntu).
- Install Rust
- Configured PATH variable (PATH="/opt/android-studio-2021.2.1/android-studio/jre/bin:$PATH" )
- Configured ANDROID_SDK_ROOT variable (ANDROID_SDK_ROOT=/home/user/Android/Sdk) in .bashrc

I ran these commands
````export PATH="/opt/android-studio-2021.2.1/android-studio/jre/bin:$PATH"````
````./build.py -v binary magisk````

As well as
````PATH="/opt/android-studio-2021.2.1/android-studio/jre/bin:$PATH" ./build.py -v binary magisk````

````
mv target/x86_64-linux-android/debug/libmagisk.a -> ../../native/out/x86_64/libmagisk-rs.a
Android NDK: ERROR:jni/Android.mk:boot-rs: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/../out/armeabi-v7a/libmagiskboot-rs.a exists  or that its path is correct   
/home/user/Android/Sdk/ndk/magisk/build/core/prebuilt-library.mk:51: *** Android NDK: Aborting    .  Stop.
````

I checked that libmagiskboot-rs.a is not in ````Magisk/native/out/armeabi-v7a/````. There is only libmagisk-rs.a. I did a search in the filesystem for libmagiskboot-rs.a but could not find any files with that name.

Are there any other settings I need to configure?

OS: Ubuntu 22.04 LTS
Magisk version code: 25101

magisk.stubVersion=32
magisk.versionCode=25101
magisk.ondkVersion=r24.2

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/blob/70fd03d5fc7f7864730e4ccfe2db0f6e20d715a7/.github/workflows/build.yml#L25

CI builds fine
