### ISSUE TITLE
Magisk‘s’ operation not permitted to patch

### ISSUE THREAD

**Issue by dergrey** [topjohnwu/Magisk#6072]
I tried to use magisk method to root my Xperia 10II cellphone, but when I tried to patch boot.img, then a problem occured: Operation not permitted

I had met this problem last year, today I find that Magisk has suppot to sony devices, so what can i do to solve this problem?

Device: Sony Xperia 10II
Android version:11.0.0
Magisk version name:25101
Magisk version code:25101

**Comment by dergrey** [comment]
> - Device platform: arm64-v8a
> - Installing: 25.1 (25101)
> - Copying image to cache
> - Unpacking boot image
> Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
> HEADER_VER      [2]
> KERNEL_SZ       [15375561]
> RAMDISK_SZ      [725033]
> SECOND_SZ       [0]
> RECOV_DTBO_SZ   [0]
> DTB_SZ          [507405]
> OS_VERSION      [11.0.0]
> OS_PATCH_LEVEL  [2021-09]
> PAGESIZE        [4096]
> NAME            []
> CMDLINE         [androidboot.hardware=qcom androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=1 loop.max_part=7 cgroup.memory=nokmem,nosocket buildproduct=pdx201 buildid=SEINE-1.1.1-210827-1512 oemboot.earlymount=/dev/block/platform/soc/4744000.sdhci/by-name/oem:/mnt/oem:ext4:ro,barrier=1:wait,slotselect,first_stage_mount buildvariant=user]
> CHECKSUM        [c5cb87efb54a39af97a306580cc80ed90abb3c95000000000000000000000000]
> KERNEL_FMT      [gzip]
> RAMDISK_FMT     [gzip]
> VBMETA
> - Checking ramdisk status
> Loading cpio: [ramdisk.cpio]
> - Stock boot image detected
> - Patching ramdisk
> Loading cpio: [ramdisk.cpio]
> Add entry [init] (0750)
> Create directory [overlay.d] (0750)
> Create directory [overlay.d/sbin] (0750)
> Add entry [overlay.d/sbin/magisk32.xz] (0644)
> Add entry [overlay.d/sbin/magisk64.xz] (0644)
> Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
> Loading cpio: [ramdisk.cpio.orig]
> Backup mismatch entry: [init] -> [.backup/init]
> Record new entry: [overlay.d] -> [.backup/.rmlist]
> Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
> Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
> Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
> Create directory [.backup] (0000)
> Add entry [.backup/.magisk] (0000)
> Dump cpio: [ramdisk.cpio]
> Loading dtbs from [dtb]
> Patch @ 01E54B97 [736B69705F696E697472616D667300] -> [77616E745F696E697472616D667300]
> - Repacking boot image
> Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
> HEADER_VER      [2]
> KERNEL_SZ       [15375561]
> RAMDISK_SZ      [725033]
> SECOND_SZ       [0]
> RECOV_DTBO_SZ   [0]
> DTB_SZ          [507405]
> OS_VERSION      [11.0.0]
> OS_PATCH_LEVEL  [2021-09]
> PAGESIZE        [4096]
> NAME            []
> CMDLINE         [androidboot.hardware=qcom androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=1 loop.max_part=7 cgroup.memory=nokmem,nosocket buildproduct=pdx201 buildid=SEINE-1.1.1-210827-1512 oemboot.earlymount=/dev/block/platform/soc/4744000.sdhci/by-name/oem:/mnt/oem:ext4:ro,barrier=1:wait,slotselect,first_stage_mount buildvariant=user]
> CHECKSUM        [c5cb87efb54a39af97a306580cc80ed90abb3c95000000000000000000000000]
> KERNEL_FMT      [gzip]
> RAMDISK_FMT     [gzip]
> VBMETA
> Repack to boot image: [new-boot.img]
> HEADER_VER      [2]
> KERNEL_SZ       [15375554]
> RAMDISK_SZ      [1170100]
> SECOND_SZ       [0]
> RECOV_DTBO_SZ   [0]
> DTB_SZ          [507405]
> OS_VERSION      [11.0.0]
> OS_PATCH_LEVEL  [2021-09]
> PAGESIZE        [4096]
> NAME            []
> CMDLINE         [androidboot.hardware=qcom androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=1 loop.max_part=7 cgroup.memory=nokmem,nosocket buildproduct=pdx201 buildid=SEINE-1.1.1-210827-1512 oemboot.earlymount=/dev/block/platform/soc/4744000.sdhci/by-name/oem:/mnt/oem:ext4:ro,barrier=1:wait,slotselect,first_stage_mount buildvariant=user]
> CHECKSUM        [ccc34f9b4971cd6004ec805d9c94efbc231c65cb000000000000000000000000]
> 
> ****************************
>  Output file is written to 
>  /storage/emulated/0/Download/magisk_patched-25101_hrRva.img 
> ****************************
> cp: can't preserve ownership of 'busybox': Operation not permitted
> cp: can't preserve ownership of 'magisk32': Operation not permitted
> cp: can't preserve ownership of 'magisk64': Operation not permitted
> cp: can't preserve ownership of 'magiskboot': Operation not permitted
> cp: can't preserve ownership of 'magiskinit': Operation not permitted
> cp: can't preserve ownership of 'magiskpolicy': Operation not permitted
> - All done!
>

**Comment by vvb2060** [comment]
ignore it

**Comment by pndwal** [comment]
Sorry, bit confused; looks like it patched fine... (am I wrong?)

But can you flash and boot it?

**Comment by dergrey** [comment]
> 



> Sorry, bit confused; looks like it patched fine... (am I wrong?)
> 
> ... But can you flash and boot it?

cp: can't preserve ownership of 'busybox': Operation not permitted
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
cp: can't preserve ownership of 'magiskpolicy': Operation not permitted

**Comment by pndwal** [comment]
Ok, so that log (last part) was nothing to do with patching...

Ownership issue seems to be related to Verity...

After checking this per instructions:

> Next, we need to know whether your device has a separate vbmeta partition...

Was the answer yes or no?

If the answer was yes, did you try this option?:

> (Optional) If your device has a separate vbmeta partition, you can patch the vbmeta partition with command:
fastboot flash vbmeta --disable-verity --disable-verification vbmeta.img

If no, did you do this?:

> If your device does NOT have a separate vbmeta partition, check the “Patch vbmeta in boot image” option
