### ISSUE TITLE
Deny-list

### ISSUE THREAD

**Issue by THardi** [topjohnwu/Magisk#6075]
Setting "Google Play Services" in the deny list is regularly forgotten.  ...gms + .gms.unstable
Created in the stable version, "Update" to Debug, restart, no longer checked.

Device: Blackview BV9900Pro + Poco X3 MiuiMix
Android version: 9 + 11
Magisk version name: 9183a0a6
Magisk version code: 25101 (D)

**Comment by Displax** [comment]
Expected behavior. Because you use UNSF.

**Comment by pndwal** [comment]
> Expected behavior. Because you use UNSF.

To be clear, that's Universal NetSafety Fix... 🙃 😜

**Comment by THardi** [comment]
Thanks.
