### ISSUE TITLE
Wifi Crash on Xiaomi with Magisk 25101, 25100 and 25000

### ISSUE THREAD

**Issue by rezakelidari** [topjohnwu/Magisk#6077]
Device: Xiaomi Redmi 8 Global (Olive)
Android version: 10 Q (MIUI: 12.5.3 Stable)
Magisk version name: 25.1
Magisk version code: 25101

**(I tried all these things with version 25101)**

I have a Redmi 8 which I rooted with Magisk version 25000 and twrp-3.6.2_9-0-olive. When I opened Magisk Manager, it showed that the update version 25100 is available and I installed it. After installation, when I entered the app, an update option was displayed next to Magisk and I clicked on it. I installed the update with "direct install (recommended)".

After installing the update and restarting the phone, the Wi-Fi stopped working (when I turned it on, it turned off immediately) and the Wi-Fi sharing option disappeared.

After all this I went into recovery mode (twrp recovery) to install version 25000 but accidentally forgot to do so and just rebooted from there. Then it was strange that the version of Magisk was 25, but the version of the program was still 25.1. The Wi-Fi problem was also solved with version 25000.

**Finally, I tried all these from the beginning with version 25101 and the problem was still there**

**Comment by vvb2060** [comment]
no log
