### ISSUE TITLE
Can Magisk work without MagiskManager?

### ISSUE THREAD

**Issue by vvb2060** [topjohnwu/Magisk#608]
```
boolean hasMagiskManager() {
        int flags=PackageManager.GET_RECEIVERS|PackageManager.MATCH_UNINSTALLED_PACKAGES;
        List<PackageInfo> List = getPackageManager().getInstalledPackages(flags);
        for (PackageInfo apk : List) {
            ActivityInfo[] receivers = apk.receivers;
            if (receivers != null) {
                for (ActivityInfo i : receivers) {
                    if (i.name.contains("com.topjohnwu.magisk")) {
                        return true;
                    }
                }
            }
        }
        return false;
```
We can uninstall Magisk Manager, but new superuser request need it. Can Magisk work without Magisk Manager?
Or other way can pass this check?

Update: now I see 78534de , but `SuReceiver` ……

**Comment by topjohnwu** [comment]
There is an option to repackage Magisk Manager with random package names, and now most classes (except a few that some part of Magisk hardcodes the class name) are obfuscated, it will be very difficult to detect Magisk Manager after hiding it. BTW, a new way to communicate between Magisk and Magisk Manager is WIP so no `SuReceiver` is required, please stay tuned :)

**Comment by vvb2060** [comment]
I know repackage, It's why code doesn't check package name. I think it is very easy to check out **now**.
I am looking forward to the new way of communication.
