### ISSUE TITLE
Bootloop After flashing magisk patched boot image 

### ISSUE THREAD

**Issue by swappp777** [topjohnwu/Magisk#6092]
(my previous issue was closed without any update)

Device:Vivo 1802
Android version: 8.1
Magisk version name:canary build
Magisk version code:25101

required files
https://drive.google.com/drive/folders/11SziZfcz7_YAYnSEl3LQE-MtB5K3MZjJ
 
can't provide bootloop log since i don't have custom recovery or root or kernal

the stock boot.img being used is correct one cause it fixed bootloop upon flashing

**Comment by swappp777** [comment]
The bug report file has been included in same folder now

it includes kernal log.
So... someone with better knowledge please look into this

**Comment by vvb2060** [comment]
We couldn't find `magiskinit` in your log

**Comment by swappp777** [comment]
> We couldn't find `magiskinit` in your log

but why you closing issue straight up?.....
issues section is for end users mostly who face issues and not some developer

i am not developer to know what is wrong and what is not!

i request to reopen issue

**Comment by vvb2060** [comment]
We can't fix it without log, what's the point of keeping the issue open?

**Comment by Swapmemaybe** [comment]
> We can't fix it without log, what's the point of keeping the issue open?

They I could have provided different log files…..what’s the point to close issue straight up?
What log do you want ?

**Comment by canyie** [comment]
Your device seems does not support recording `last_kmsg`, so there is no way to grab `last dmesg` without root. But since it's a VIVO device, the problem is most likely to be some kernel restrictions that unfortunately Magisk cannot fix. Please check #5148 for details.

**Comment by swappp777** [comment]
> Your device seems does not support recording `last_kmsg`, so there is no way to grab `last dmesg` without root. But since it's a VIVO device, the problem is most likely to be some kernel restrictions that unfortunately Magisk cannot fix. Please check #5148 for details.

Thank You!!!....for this response
this is the type of answer everyone expects before their issue gets closed
🤞🙏

**Comment by swappp777** [comment]
> > Your device seems does not support recording `last_kmsg`, so there is no way to grab `last dmesg` without root. But since it's a VIVO device, the problem is most likely to be some kernel restrictions that unfortunately Magisk cannot fix. Please check #5148 for details.
> 
> Thank You!!!....for this response this is the type of answer everyone expects before their issue gets closed 🤞🙏
> 
> also i would like to point out that the last_kmsg is in bugreport file.....the one require by developer supposed to be different?

also i think my issue is totally different.....🙄?
