### ISSUE TITLE
Zygisk kills root

### ISSUE THREAD

**Issue by poiuzzz** [topjohnwu/Magisk#6095]
Device: Xiaomi Redmi Note 4
Android version: 7, MIUI Global 11.0.2
Magisk version name: 25.1
Magisk version code: 25101

Update to 25.1 from Magisk 24.2 (hide app faild) works.
After activating Zygisk, root disapears.

I had to install Magisk via TWRP because installing via fastboot didn't work.

Can you help?

[magisk_log_2022-07-12T01.15.36.log](https://github.com/topjohnwu/Magisk/files/9105688/magisk_log_2022-07-12T01.15.36.log)

**Comment by vvb2060** [comment]
https://developer.android.com/studio/debug/bug-report

**Comment by poiuzzz** [comment]
[bugreport-NRD90M-2022-07-17-17-43-36.zip](https://github.com/topjohnwu/Magisk/files/9128003/bugreport-NRD90M-2022-07-17-17-43-36.zip)

**Comment by yujincheng08** [comment]
```
07-17 17:40:47.865  8456  8456 E Magisk  : Access denied
```

?

**Comment by poiuzzz** [comment]
Maybe it happend when Magisk will install the app automaticly after first start? 
This does not work on my device. So I stopped the process and installed the app via local apk.

**Comment by 2011** [comment]
I don't know if this comes from the same problem, but I have also had huge problems with Zygisk (on just one device - other devices work fine with it). After upgrading to 25.1 from 24.3, flashing boot, turing on Zygisk and rebooting, the Magisk app simply showed "Installed: N/A" for Magisk (I have never used "Hide the Magisk App").

The device (a Teclast T10 tablet with the exact model number of E3C5) has the latest stock firmware (1.05_20180306) built from Android 7.0.

I eventually ended up reformatting /data to recover (which, after I installed the Magisk app, and with no further flashing, then showed Magisk 25.1 installed). I attempted (one more time) to turn on Zygisk, and the system reverted to the previous state after rebooting (the Magisk app showed "Installed: N/A" for Magisk), which I recovered from by wiping /data again.

I doubt I can provide many technical details on this (especially since I now have an extreme reluctance to activating Zygisk on this device), but I will try to any questions that I can.

**Comment by mastertIT** [comment]
i can confirm a similar issue, seems after the first reboot after zygisk is enabled, magisk hooks init and crashes consistently, which stops most of the important android processes from failing to start eventually a watchdog timer causes the phone to bootloop.

a boot logcat shows this, attached
[logcat1.zip](https://github.com/topjohnwu/Magisk/files/9173064/logcat1.zip)
.

**Comment by canyie** [comment]
https://github.com/canyie/Magisk/actions/runs/2761467990
can anyone reproduce the problem on this build and grab logcat?

**Comment by poiuzzz** [comment]
I installed app-debug.zip via TWRP but root did not work. App could not be installed because of: "The package conflicts with an existing package by the same name"

**Comment by canyie** [comment]
You have to uninstall the original app before installing mine.
Also I'm asking a bootlog, it requires adb, not root.

**Comment by poiuzzz** [comment]
> You have to uninstall the original app before installing mine.
I did
> And, I'm asking for a bootlog, it requires adb, not root.
Don't I need an img file?
eg: fastboot flash boot /home/per/magisk_patched-25101_bqUzh.img
I have only found apk.
Sorry for my ignorance

**Comment by alvkN** [comment]
> I don't know if this comes from the same problem, but I have also had huge problems with Zygisk (on just one device - other devices work fine with it). After upgrading to 25.1 from 24.3, flashing boot, turing on Zygisk and rebooting, the Magisk app simply showed "Installed: N/A" for Magisk (I have never used "Hide the Magisk App").
> 
> The device (a Teclast T10 tablet with the exact model number of E3C5) has the latest stock firmware (1.05_20180306) built from Android 7.0.
> 
> I eventually ended up reformatting /data to recover (which, after I installed the Magisk app, and with no further flashing, then showed Magisk 25.1 installed). I attempted (one more time) to turn on Zygisk, and the system reverted to the previous state after rebooting (the Magisk app showed "Installed: N/A" for Magisk), which I recovered from by wiping /data again.
> 
> I doubt I can provide many technical details on this (especially since I now have an extreme reluctance to activating Zygisk on this device), but I will try to any questions that I can.

facing same issue with 25.2

**Comment by canyie** [comment]
> Don't I need an img file?

Use my apk to patch your boot image then flash... or flash it in twrp... just like how do you install official builds...

**Comment by poiuzzz** [comment]
Still the same problem: 
App could not be installed because of: "The package conflicts with an existing package by the same name"

**Comment by canyie** [comment]
Then just flash it in TWRP and upload boot logcat...

**Comment by poiuzzz** [comment]
[logcat.log](https://github.com/topjohnwu/Magisk/files/9259252/logcat.log)

**Comment by poiuzzz** [comment]
I installed on another Redmi Note 4 latest /e/ OS (based on Android 9, XiaomiOS on Android 7). Magisk/Zygisk works fine on this device.

**Comment by canyie** [comment]
You said you have installed official Magisk on another Redmi Note 4 and it works just fine with Zygisk?

**Comment by canyie** [comment]
Can you `su` in adb shell or termux while magisk app doesn't detect root?

**Comment by poiuzzz** [comment]
> You said you have installed official Magisk on another Redmi Note 4 and it works just fine with Zygisk?
And Magisk 24.2 works fine on both devices even if Zygisk enabled?

right, but only with the Android 9 based /e/OS. I have two Redmi 4 with original OS. Both have the same problem.

**Comment by poiuzzz** [comment]
su in Termux is ok. Titanium backup asks successful for root. But Magisk or AdAway app will not detect root at all.

**Comment by canyie** [comment]
With stock kernel or custom kernel?

**Comment by poiuzzz** [comment]
stock

**Comment by canyie** [comment]
Okay I have reproduced it on my device... I'm will take a look into it... Please mark this as a regression since 24.x seems to be working

**Comment by poiuzzz** [comment]
>  Please mark this as a regression 
How? Can you give me a hint, please

**Comment by canyie** [comment]
Oh sorry, I'm talking to the collaborators, they have the permission to label issues 😆

**Comment by canyie** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/9275521/app-debug.zip)
Root should be available in this build, but Zygisk cannot be activated 🤔 Needs to find out why the new loading method introduced in commit 8186f253e8c0ba0ed48e8ca41ae40110f967391e doesn't work on your device.

**Comment by canyie** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/9276540/app-debug.zip)
Can you test if Zygisk can work in this build?

**Comment by Haus3master** [comment]
> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/9276540/app-debug.zip) Can you test if Zygisk can work in this build?

I too have a device on Android 7 with this issue, can i test this build?

**Comment by Haus3master** [comment]
> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/9276540/app-debug.zip) Can you test if Zygisk can work in this build?

Yes, so far zygisk does load and it's status is also reflected in the manager, and all of my modules seem to be working...

**Comment by Haus3master** [comment]
Also able to grant root access to my apps...

**Comment by schdie** [comment]
I'm having the same problem, after activating Zygisk root is not longer available. I used the app-debug version @canyie posted and it does not detect root either. Without activating Zygisk everything's ok. In order to get root again re-flashing the boot partition through fastboot is not enough, I had to uninstall magisk through recovery and then reflash the boot partition.

Device: nvidia shield tablet
Android version: 7
Magisk version name: 25.2 (I also used the app-debug and the log is from there)
[magisk_log_2022-12-01T17.04.44.log](https://github.com/topjohnwu/Magisk/files/10135883/magisk_log_2022-12-01T17.04.44.log)

**Comment by Sabbianelcul** [comment]
Same problem here on a Lenovo p2 with android 7. Zygisk unroots my phone after activating it and rebooting.

**Comment by prasadmanjulago** [comment]
This issue is present on Samsung Note 5 SM-N920L.is there any work around?

**Comment by canyie** [comment]
Install the latest canary/debug build 25206. If the issue persists, please open a new issue with logs. Thank you!

**Comment by schdie** [comment]
> 25206

Just for the record 25206 fixed it in my case. I wonder what commit did it though.
