### ISSUE TITLE
new version (25.*)  make unbootable boot.img

### ISSUE THREAD

**Issue by Eugene7219** [topjohnwu/Magisk#6097]
Device: google pixel5a
Android version: 12 (last jule update)
Magisk version name: 25.1
Magisk version code: 25101

after patching boot.img device can`t boot (no bootloop)
when i to return to last 24 version and patching boot.img - device boot and working normally.

Thanks.

**Comment by spookybear0** [comment]
I am also experiencing this issue on stable and canary versions of magisk.
