### ISSUE TITLE
Feature request: Log terminal output of root sessions.

### ISSUE THREAD

**Issue by pthfdr-42** [topjohnwu/Magisk#610]
A feature I miss in SuperSU is that you can choose to log the whole terminal output, so you can inspect what the applications are really doing, and what are actually going wrong.
This is where Magisk lacks.

**Comment by MrSaMaDo** [comment]
This So Good ;)

**Comment by AllanThisgaard** [comment]
I would like to second this feature 👌 Magisk is truly a phenomenal piece of software, but as always, everything can be improved.

Often times an app requests root permissions, and what happens from there on out is like a black box. It would be really convenient and at times even reassuring to monitor the apps. 
I imagine that the command the application wishes to execute with root permissions is intercepted or evaluated by Magisk (I'm playing it safe here 😅). When what happens a quick log entry would be marvelous 👍🙏

**Comment by TanyaEleventhGoddess** [comment]
I would like to see this feature too I was coming here exactly for asking this

**Comment by Surge1223** [comment]
Wanna chime in and say I'd love this on per app choice basis, just echo'ing out the su executed commands and both capturing the stdout would help me tons lmao

**Comment by OmlineEditor** [comment]
Tell me the approximate dates when this functionality will appear?
a very necessary function, it is not enough.

**Comment by EsEnZeT** [comment]
This should be core functionality implemented from start.

**Comment by etmatrix** [comment]
I hope a day @topjohnwu implement this enhancement.

**Comment by topjohnwu** [comment]
This feature requires significant rewriting the root stdin/stdout from scratch, and it won't be stable at all. There is no point in actually logging the shell input/output, since if anyone really wants to hide what it is doing, it can do all the things directly in native code, not through shell commands.

There is no plans for implementing this feature at any point in the future, closed

**Comment by QkiZMR** [comment]
But if someone hide something in native code first this code will have to be running by su. Then I will know which binary was ran.

**Comment by Minabsapi** [comment]
By "There are no plans for implementing this feature at any point in the future", do you mean you and current collaborators will not work on this, or that you'll even not merge PR that would bring this feature?

**Comment by OraBB1t** [comment]
I really hope somebody would work on this.
