### ISSUE TITLE
Can't open "Log" section in Magisk App

### ISSUE THREAD

**Issue by Dima-diep** [topjohnwu/Magisk#6101]
Device: Xiaomi Mi Note 3
Android version: 10
Magisk version name: 9183a0a6:MAGISK:D
Magisk version code: 25101

Logcat:
07-16 08:16:46.720  1447  3453 W WindowManager: Failed looking up window callers=com.android.server.wm.InputManagerCallback.interceptKeyBeforeDispatching:182 com.android.server.input.InputManagerService.interceptKeyBeforeDispatching:1933 <bottom of call stack> 
07-16 08:16:47.131  1447  2310 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{bde71bb u0 txelgwimyhh.wd.r/d.a4 t8211}
07-16 08:16:47.132  1447  2310 W ActivityTaskManager: Activity pause timeout for ActivityRecord{bde71bb u0 txelgwimyhh.wd.r/d.a4 t8211}

[Please, say if you need full logcat from booting system time to crash time].

There is a bug. When I've opened "Log" section in hided Magisk app, app is freezing. I can't open any other app section, I can only terminate the app for restarting it.

This problem also in restored Magisk app, not only hided.

**Comment by BillingCode** [comment]
How do you filter this trash in your email when most of I fake reports used
for tracking purposes?

**Comment by canyie** [comment]
#5505
