### ISSUE TITLE
Pixel 5a bootloops after flashing patched image.

### ISSUE THREAD

**Issue by spookybear0** [topjohnwu/Magisk#6128]
Device: Pixel 5a (barbet)
Android version: Android 12 LineageOS 19.1 nightly (lineage_barbet-userdebug 12 SQ3A.220705.003.A19303e636cd)
Magisk version name: 25.2
Magisk version code: 25201 (Debug)

I have tried patching `boot_factory.img` (which is the stock firmware boot image) and I have also tried patching `boot_LOS.img` (which is the boot image from the current version of my rom). I've tried 25.2, 25.1, 25.0, 24.3 versions of magisk on both images.

The one difference between when I patch factory vs LOS is that when I patch factory it gets to the LineageOS boot screen and right before it finishes it reboots.

`magisk_patched-25201_6IuvM.img` is the boot image I flashed with `fastboot flash boot magisk_patched-25201_6IuvM`.

dm-verity and verification is disabled, no modules are installed.

I'm not sure if I uploaded the logs right but if needed I can provide more.

Anyone have any ideas?

Thanks.

[boot_factory.zip](https://github.com/topjohnwu/Magisk/files/9176430/boot_factory.zip)
[boot_LOS.zip](https://github.com/topjohnwu/Magisk/files/9176431/boot_LOS.zip)
[magisk_patched-25201_6IuvM.zip](https://github.com/topjohnwu/Magisk/files/9176455/magisk_patched-25201_6IuvM.zip)
[mounts.txt](https://github.com/topjohnwu/Magisk/files/9176473/mounts.txt)
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/9176474/dmesg.txt)

**Comment by canyie** [comment]
send logcat? `adb logcat`

**Comment by spookybear0** [comment]
Weirdly enough, after enough tries flashing it, it finally worked for some reason, still unsure why it wasn't working in the first place but I think that is enough grounds for this issue to be closed, unless anyone thinks otherwise.
