### ISSUE TITLE
AP firmware patching and bootloop (Galaxy A5 , Android 6.0.1)

### ISSUE THREAD

**Issue by cronel** [topjohnwu/Magisk#6133]
Device: Galaxy A5 SM-A500H 
Android version: 6.0.1
Magisk version name: 25.2 (debug)
Magisk version code: 25201

I patched my AP firmware (it's AP-only android 6.0.1 for samsung sm-a500h (galaxy A5 2015)) using magisk debug and caused bootloop (magisk 23 and 25.2 release are same) (because i don't have a CSC i wiped data and cache in recovery too but again bootloop happens) do you have any idea?

also attached kmsg (flashed and opened custom TWRP recovery causes end part of this log file to have recovery entries I think, anyway can you understand why bootloop happens?)

[kmsg.txt](https://github.com/topjohnwu/Magisk/files/9184801/kmsg.txt)

**Comment by yujincheng08** [comment]
nothing about magisk found in your kmsg.

**Comment by cronel** [comment]
I tested magisk 20.0 and it works, even boot image patching works and whole firmware is not needed, so problem is from magisk 23 25 and debug, and I think until 22100 could work (because at my magisk version 20.0 latest update available I get is 22100 and not higher though still haven't updated to see if 22100 works too), so please fix the problem causing magisk past 22100 to not work on older devices (like my samsung Galaxy A5 SM-A500H)

**Comment by yujincheng08** [comment]
Please provide last_kmsg with magiskinit's log. Otherwise, we couldn't help you.

**Comment by cronel** [comment]
again I tested latest magisk (by patching original boot image) but again led to not booting (when booting Samsung first logo appears and it's stuck there and at top it's written kernel and it won't even lead to next Samsung logo which is it's logo with fade in/out animation!)

I checked kmsg and it's empty:
/proc # du -sh kmsg
0       kmsg

as I said, in /proc/kmsg is empty but there is **last_kmsg** in /cache/recovery which I attached it too.

"log" which I attached is also in /cache/recovery which I thought could be useful.

also I tested old versions and before magisk 21.3 all version work well but after 21.3 each version have some kind of problem!

any idea?

PS:
ramdisk is yes.
found nothing in  /sys/fs/pstore
didn't find  /system/bin/init
I can solve bootloop by installing original boot image.
couldn't find magiskinit's log

[last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/9466655/last_kmsg.txt)

[log.txt](https://github.com/topjohnwu/Magisk/files/9466657/log.txt)
