### ISSUE TITLE
[Canary] Magisk daemon does not start with first try

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#614]
Hey @topjohnwu,

After your recent Canary, a trivial issue appeared :

04-24 07:17:32.401   621   621 D Magisk  : client: connect fail, try launching new daemon process
04-24 07:17:32.412   625   625 D Magisk  : client: connect fail, try launching new daemon process
04-24 07:17:32.412   625   625 I Magisk  : Magisk v17.2-906b4aad(17103) logger started
04-24 07:17:32.412   621   621 I Magisk  : Magisk v17.2-906b4aad(17103) daemon started

I guess as Magisk successfully starts, it's nothing major, but I though I should notify you. 

I've mentioned it in the XDA Canary thread too to ask for a confirmation before opening an issue.

**Comment by topjohnwu** [comment]
This is normal, just ignore the log
