### ISSUE TITLE
Samsung system init check fstab avb flag cause boot loop

### ISSUE THREAD

**Issue by himekifee** [topjohnwu/Magisk#6141]
Device: Samsung Tab S7 Plus (T976B)
Android version: 12
Magisk version name: 25.2
Magisk version code: 25201

For some reason, samsung decided to make their `/system/bin/init` check for `avb` flags in `fstab`. If it presents, it launchs `vdc` with the flag `enablefilecrypto`, which will not work because `/data` is not encrypted. Then the system boot loop. Since commit [810d27a](https://github.com/topjohnwu/Magisk/commit/810d27a618908621a7eca32f9adccab2611746ee), magiskinit no longer patch verity in `fstab`, causing the issue. Manual unpack ramfs and remove `avb` related flag from `fstab.qcom` successfully boots the system, and `magisk` works perfectly. Since this is a design decision, I don't see an elegant way to bypass this issue. Any idea for this?

**Comment by himekifee** [comment]
By not planned you mean we bunch of Samsung users will stay on 24.3 forever?

**Comment by vvb2060** [comment]
We won't support devices that won't boot without magisk installed.

**Comment by himekifee** [comment]
That's an interesting point but it without magisk actually boots. Idk what happened there.

**Comment by himekifee** [comment]
Also boots with Magisk 24.3. Git bisect show the commit I mentioned is the root cause.

**Comment by vvb2060** [comment]
Can your device boot normally without install magisk?

**Comment by himekifee** [comment]
Good question and the answer is no. I think I need to binary patch then. If I do that, will the change be merged? If so, where should I put the patch function?

**Comment by vvb2060** [comment]
If your device doesn't boot in the first place, why do you think this is a problem that should be fixed by magisk?

**Comment by himekifee** [comment]
Not a fix by magisk, but use magisk's power to overcome the issue. Since the old version accident solved the issue. It would be beneficial to do something that makes users transit to a newer version seamlessly.

**Comment by himekifee** [comment]
Or maybe I just write a recovery script to patch. NVM then.

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/blob/master/docs/releases/25000.md
Read the changelog again (or, first time?)

**Comment by vvb2060** [comment]
We knew the problem from the start, but patching fstab would make more normal devices bootloop, break DSU functionality, and introduce a lot of complexity. So, now this is the choice we make.

**Comment by starbucks2010** [comment]
I guess I'm also in this situation with my s22 s908b custom rom.
It boots ok on kernel patched with magisk 24301 but it bootloops if I update to magisk 24302 or any othere newer version.

@himekifee I think many users will highly appreciate if you would make your script available for testing.

**Comment by himekifee** [comment]
Unfortunately, I don't have enough time to make such a script. The concept is simple. Just extract your boot partition, unpack, extract raminitramfs, delete all avb occurabce from fstab, repack initramfs, repack boot.img and flash. Imo this can be done through `anykernel` but I just don't have time to write it.

**Comment by starbucks2010** [comment]
> 

The problem is that there's no fstab file in the s22 kernel so maybe we should look elsewhere for these avb references.

**Comment by himekifee** [comment]
If not fstab then maybe dtb or vendor.

**Comment by DrKetan** [comment]
vendor-boot.img have fstab, should try patching it manually. I have S22 ultra S908E and no such issue though.

**Comment by starbucks2010** [comment]
patched manually all fstab files from vendor_boot.img and the device boots fine on magisk 24301 but still bootllops after updating magisk.

**Comment by HuskyDG** [comment]
You can try patch boot image with magisk v25.0 but magiskinit is v24.3

**Comment by metorm** [comment]
Hi @himekifee , I think I am faced with this problem. Would you share your solution briefly? I am familiar with Linux but not android, so I do not know how can I unpack a Samsun ROM and repack it back.

**Comment by himekifee** [comment]
I had a TWRP recovery and I retrieved /dev/last_kmg after a failed boot. I found vold is summoned with a crypt flag that failed because there is no encryption. The only thing I remembered that can tell vold something is encrypted is by fstab. You can first pull the boot partition from the phone, then use [Android_boot_image_editor](https://github.com/cfig/Android_boot_image_editor.git) to change the fstab and package it back.

**Comment by edward0181** [comment]
> I had a TWRP recovery and I retrieved /dev/last_kmg after a failed boot. I found vold is summoned with a crypt flag that failed because there is no encryption. The only thing I remembered that can tell vold something is encrypted is by fstab. You can first pull the boot partition from the phone, then use [Android_boot_image_editor](https://github.com/cfig/Android_boot_image_editor.git) to change the fstab and package it back. This all requires a TWRP.

Somehow, on my Samsung a13ve, (MTK), it's not working. Pulled original boot.img from FW files, changed fstabs with boot image editior, and reflashed back to boot partition in TWRP... still bootloops to the same issue.

 libc: Unable to set property "ro.boottime.init.count.cache to 1-2-3

**Comment by KingMahmud** [comment]
@himekifee Hey, could you please tell me how you solved the issue? I read your comments but could'nt understand anything.

**Comment by KingMahmud** [comment]
> > @himekifee Hey, could you please tell me how you solved the issue? I read your comments but couldn't understand anything.
> 
> It might not actually be the issue for your device. Basically, it requires you editing the fstab file inside initramfs, I suggest you find some article on google to have a good understanding how it works.

Okay, i will see. By the way, why do you think its not the same issue and what issue you is going on?

**Comment by KingMahmud** [comment]
@edward0181 Have you solved your issue?

**Comment by rajarshikhatua100** [comment]
why magisk why
