### ISSUE TITLE
System app added to Deny List is missing after reboot

### ISSUE THREAD

**Issue by laheller** [topjohnwu/Magisk#6146]
Device: Samsung Galaxy S20+
Android version: 12
Magisk version name: 25.2
Magisk version code: 9b61bdfc (25201)

I added the system package **com.google.android.gms** to Deny List.
After reboot and open, the above package is **missing** from Deny List.

**Comment by Displax** [comment]
Expected behavior, because you use USNF.

**Comment by laheller** [comment]
> Expected behavior, because you use USNF.

@Displax 
What is USNF ?

**Comment by Displax** [comment]
> > Expected behavior, because you use USNF.
> 
> @Displax 
> What is USNF ?
> 

Universal safetynet fix

**Comment by laheller** [comment]
@Displax  @vvb2060 
OK, now it's clear.
Without Universal SafetyNet Fix it works as expected.
Use case is BTW hide Magisk and root from Google Wallet app to be able to use mobile payment.

**Comment by pndwal** [comment]
> @Displax @vvb2060 OK, now it's clear. Without Universal SafetyNet Fix it works as expected. Use case is BTW hide Magisk and root from Google Wallet app to be able to use mobile payment.

USNF removes gms at boot as it uses targeted hiding for SafetyNet (com.google.android.gms.unstable) process etc.
