### ISSUE TITLE
Magisk 17.1 - Downloads - Search Not Working

### ISSUE THREAD

**Issue by 0pLuS0** [topjohnwu/Magisk#616]
Hi,

Essential PH-1
Magisk 17.1 - flashed in twrp

When I first open Magisk after I've flashed in 17.1 and try to do a Downloads Search nothing will appear. But playing around with Magisk, if I "Hide Magisk Manager" and reboot, I'm now able to Search for Modules to download.

In 16.7 I never had this problem, not sure what's going on now.

By the way, I've been doing a lot of custom rom hacking and flashing, sometimes when I install 17.1 this isn't happening, then another time I install it, it's not working again...

Sorry I forgot to save a log, and I created a TWRP back and restored it after I corrected the problem, so I see now the logs don't have anything from that time period.

If you need a log later, I'll try to get one for you.

Hmm

**Comment by topjohnwu** [comment]
This seems pretty random, maybe the repo database is incorrectly created. You can simply clean the database in Magisk Manager settings.

**Comment by 0pLuS0** [comment]
@topjohnwu ``` Clear Repo Cache``` I'm assuming?

Has this been happening for others?

Thanks

**Comment by Madis0** [comment]
Can confirm on Android 8.1/Magisk Manager 5.9.1. From what I understand, it is a module issue and it has been fixed in Magisk Manager code, but not pushed for everyone. https://github.com/topjohnwu/Magisk/commit/2c0436216f6f0bc2403986aa2771af03b1e4a91c

**Comment by 0pLuS0** [comment]
@Madis0 thanks

**Comment by Madis0** [comment]
Fixed by Magisk Manager 6.0.0 on my end.
