### ISSUE TITLE
修改su为sc请求帮助

### ISSUE THREAD

**Issue by qiurigao** [topjohnwu/Magisk#6162]
Device:vivo
Android version:11
Magisk version name:25.2
Magisk version code:25201

修改以下两处su为sc后，编译出来的apk依旧基于su命令进行版本检测，是否还需要修改其他的代码。
如何从源码修改apk使其调用sc命令检测状态？
https://github.com/topjohnwu/Magisk/blob/master/native/src/include/magisk.hpp#L31
https://github.com/topjohnwu/Magisk/blob/master/native/src/core/applets.cpp#L13

**Comment by qiurigao** [comment]
![Screenshot_2022-08-03-16-40-39-71_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/22121479/182565781-1058701c-1fe4-4466-bcb9-de22a0582cfe.jpg)

**Comment by qiurigao** [comment]
楼上为app-debug.apk
这是app-release.apk
![Screenshot_2022-08-03-16-48-33-75_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/22121479/182566606-9fc20f79-f1df-4c18-8fd9-47199f981fd8.jpg)

**Comment by canyie** [comment]
https://github.com/topjohnwu/libsu 代码在这里，把里面的 su 改掉

**Comment by qiurigao** [comment]
> https://github.com/topjohnwu/libsu 代码在这里，把里面的 su 改掉

多谢大佬指导，我都快搞郁闷了现在就差改挂载了，默认情况挂载不了vivo的设备

**Comment by qiurigao** [comment]
> https://github.com/topjohnwu/libsu在这里，把里面的su改掉

我怎么在magisk源码里找不到这个引用啊，模块里也没有

**Comment by qiurigao** [comment]
https://jitpack.io/#qiurigao/libsu
