### ISSUE TITLE
fix build bug 

### ISSUE THREAD

**Issue by qiurigao** [topjohnwu/Magisk#6165]
Device:all
Android version:11
Magisk version name:25.2
Magisk version code:25201
https://github.com/topjohnwu/Magisk/pull/6163/commits/4d6c974096d8542f7e68eb950f080e5fa91401dd

**Comment by canyie** [comment]
`cd native/src/external/zopfli && git checkout 831773bc28e318b91a3255fa12c9fcde1606058b`
