### ISSUE TITLE
MagiskHide invalid for the package "tw.com.twmp.twhcewallet"

### ISSUE THREAD

**Issue by pinomeng** [topjohnwu/Magisk#617]
Magisk 17.1
Magisk Manager 5.9.1
LeeDrOiD 10 V5.2.1 (Android 8.0.0)
Android Security Patch: Dec 1, 2017
HTC 10 (pme)

Enabled MagiskHide and hide MagiskManager package.

Sometime ago, the app "tw.com.twmp.twhcewallet" (a locally payment service in Taiwan for HCE credit card, like Google Pay) working normally.

But now it will show error R when I open this app (means this device has root or found MagiskManager installed).

I'm guess that the app not only search package name (com.topjohnwu.magisk) but also search app name (Magisk Manager), or other reasons.

Please help to resolve this problem : (

**Comment by pinomeng** [comment]
> Update to Canary and try it again

Hi @SuperSandro2000 ,
I'm installed canary version (Magisk: 17.2-906b4aad, App: 5.9.2-2c043621) and still invalid.
I've enabled MagiskHide and hided Magisk package.

Other bank app (will check root permission) work normally.

**Comment by pinomeng** [comment]
I'm try to uninstall MagiskManager and open the app again, it work.
So I guess that it's found MagiskManager and determined the device is rooted.

Have you thought about changing the app name when hide MagiskManager?

**Comment by SuperSandro2000** [comment]
The package and service names are hidden and I don't think that the app blocks you based on display name.

**Comment by pinomeng** [comment]
I'm updated to Magisk 17.2 and MagiskManager 6.0.0, same as before.

**Comment by SuperSandro2000** [comment]
Did you clear the apps data in between tries?

**Comment by pinomeng** [comment]
@SuperSandro2000 I tried, same as before.

but, I tried to rename MagiskManager's app name, it's work! the app will not show error for me : )

https://i.imgur.com/EcEfjhG.png

**Comment by charlie2alpha** [comment]
This is hardly surprising if you consider apps were detecting root by looking for the Magisk manager download folder in the internal storage. That folder is no longer created or used so, the service names became randomized so now they resorted to this little trick, detecting the presence of Magisk manager by its display name!

**Comment by TenshoDaijin** [comment]
Hey can u pls tell me how u rename the app ?
I have the same problem withe Magisk 17.2

**Comment by TenshoDaijin** [comment]
> @SuperSandro2000 I tried, same as before.
> 
> but, I tried to rename MagiskManager's app name, it's work! the app will not show error for me : )
> 
> https://i.imgur.com/EcEfjhG.png
> 
> https://i.imgur.com/X7ipcpB.png

Hey can u pls tell me how u rename the app ?
I have the same problem withe Magisk 17.2

**Comment by topjohnwu** [comment]
Please try out the latest Canary Build with the updated MagiskHide. If it still don't work, try to uninstall Magisk Manager, and report the results after uninstalling. Thank you

**Comment by pinomeng** [comment]
@topjohnwu, I'm tried to clean install the latest Canary Build (17.4-ec472309) and Magisk Manager (6.0.1-ec472309).
After installed, I'm hided Magisk Manager in settings and checked the payments app in MagiskHide, this app still show error R.
I'm uninstalled Magisk Manager app or rename display name, the payments app will work normally.

**Comment by topjohnwu** [comment]
@pinomeng thank you for confirming, will add an option to rename display name
