### ISSUE TITLE
Magisk 16.7,17.1

### ISSUE THREAD

**Issue by pockyep** [topjohnwu/Magisk#618]
Flash some custom rom having issue with error 1, mounting /vendor
some slightly older rom does not hit this issue when flash (full device partitions format & wipe already done)
Tracing around, should it be TWRP or Magisk related?
For this instance, using TWRP santoni 3.2.3 (latest)

**Comment by Pi3Gey** [comment]
Not from ROM side Issue, it's your Device that is fully Treble Now. Better change Recovery that support Treble/vendor. Official Recovery doesn't support that. Also join https://t.me/r4xofficial for futher queries and Kindly Close the Issue as it's not magisk Related.. ☮️
