### ISSUE TITLE
MagiskHide crashes

### ISSUE THREAD

**Issue by TurboToniTT** [topjohnwu/Magisk#619]
Hi there!

I am currently running Magisk on the BQ Aquaris X2 Pro.
So far everything works perfectly! But there are problems with MagiskHide...

Everytime i try to open MagiskHide the MagiskManager will crash.

The Magisk log itself doesnt show anything about this.

I used the magiskhide binary to disable everything from the current hide list.
But it didn't have any effect...

I also used the adb logcat command to troubleshoot and captured this error message:

```
09-18 09:47:27.679 10767 11001 W ResourceType: No known package when getting value for resource number 0x7f060002
09-18 09:47:27.679 10767 11001 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
09-18 09:47:27.679 10767 11001 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 10767
09-18 09:47:27.679 10767 11001 E AndroidRuntime: android.content.res.Resources$NotFoundException: String resource ID #0x7f060002
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at android.content.res.Resources.getText(Resources.java:339)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at android.content.res.Resources.getString(Resources.java:433)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at com.topjohnwu.magisk.adapters.ApplicationAdapter.getLabel(ApplicationAdapter.java:63)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at com.topjohnwu.magisk.adapters.ApplicationAdapter$$Lambda$1.compare(Unknown Source:1082)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at java.util.TimSort.binarySort(TimSort.java:296)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at java.util.TimSort.sort(TimSort.java:239)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at java.util.Arrays.sort(Arrays.java:1498)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at java.util.ArrayList.sort(ArrayList.java:1470)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at java.util.Collections.sort(Collections.java:201)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at com.topjohnwu.magisk.adapters.ApplicationAdapter.bridge$lambda$0$ApplicationAdapter(ApplicationAdapter.java:2078)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at com.topjohnwu.magisk.adapters.ApplicationAdapter$$Lambda$0.run(Unknown Source:2)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-18 09:47:27.679 10767 11001 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
09-18 09:47:27.681  3461  4447 W ActivityManager:   Force finishing activity com.topjohnwu.magisk/.MainActivity
09-18 09:47:27.682  3461  4447 D ActivityTrigger: ActivityTrigger activityPauseTrigger
09-18 09:47:27.685  3461  5218 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{75b1b4e com.bq.launcher} is now in focus and seems to be in full-screen mode
09-18 09:47:27.685  3461  5218 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.bq.launcher/com.android.searchlauncher.SearchLauncher/27
09-18 09:47:27.696  3461  3504 D CompatibilityInfo: mCompatibilityFlags - 10
09-18 09:47:27.696  3461  3504 D CompatibilityInfo: applicationDensity - 420
09-18 09:47:27.696  3461  3504 D CompatibilityInfo: applicationScale - 1.0
09-18 09:47:27.697  3461  3505 I ActivityManager: Showing crash dialog for package com.topjohnwu.magisk u0
09-18 09:47:27.698  4510  4510 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1556 android.content.ContextWrapper.bindService:684 com.google.android.libraries.gsa.launcherclient.i.b:13 com.google.android.libraries.gsa.launcherclient.LauncherClient.reconnect:107 com.google.android.libraries.gsa.launcherclient.LauncherClient.onStart:67
```

Any ideas?

Thanks in advance!

Best greetings,
Toni

**Comment by ANR2ME** [comment]
Hmm.. i'm using Redmi Note 5 AI (China) + MIUI 10 Global Stable but didn't have any crash on MagiskHide, although one of banking app i used (Go Mobile by CIMB Niaga) seems to detect root again recently, so i'm not sure whether MagiskHide really works or broken recently.

However, Magisk 17.1 started to crashes recently (last night) whenever i tried to search modul from Download section -_- it was fine a few days ago.

**Comment by JTandT** [comment]
Several LG V30 users are also experiencing a crash when trying to open Magisk Hide on the newest versions of Magisk Manager with both v16.0 and v17.1. My Superuser and Magisk logs are both empty after the crash just like OP. [DanielCeregatti also referenced this issue](https://github.com/topjohnwu/Magisk/issues/546#issuecomment-418156968) in another thread.

The only current fix is to downgrade to [Magisk Manager 5.8.3 (129)](https://github.com/topjohnwu/Magisk/releases/tag/manager-v5.8.3). This fixes the crash when opening Magisk Hide.

**Comment by nvspradeep** [comment]
App crashes on magisk hide after upgrading to v17. 1 Device :One plus 5 Oreo 8.1

**Comment by dragonbiteshard** [comment]
#546

**Comment by CrescendoFang** [comment]
Root checking in **Go Mobile by CIMB Niaga**

`.class public Lcom/kony/rooted/TestRoot;
.super Ljava/lang/Object;
.source "TestRoot.java"


# direct methods
.method public constructor <init>()V
    .locals 0

    .prologue
    .line 5
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static isRooted()I
    .locals 6

    .prologue
    .line 8
    const/4 v3, 0x1

    .line 10
    .local v3, "rooted":I
    :try_start_0
    invoke-static {}, Ljava/lang/Runtime;->getRuntime()Ljava/lang/Runtime;

    move-result-object v4

    const-string/jumbo v5, "su"

    invoke-virtual {v4, v5}, Ljava/lang/Runtime;->exec(Ljava/lang/String;)Ljava/lang/Process;

    move-result-object v2

    .line 12
    .local v2, "p":Ljava/lang/Process;
    new-instance v1, Ljava/io/DataOutputStream;

    invoke-virtual {v2}, Ljava/lang/Process;->getOutputStream()Ljava/io/OutputStream;

    move-result-object v4

    invoke-direct {v1, v4}, Ljava/io/DataOutputStream;-><init>(Ljava/io/OutputStream;)V

    .line 15
    .local v1, "os":Ljava/io/DataOutputStream;
    const-string/jumbo v4, "echo \"Do I have root?\" >/system/sd/temporary.txt\n"

    invoke-virtual {v1, v4}, Ljava/io/DataOutputStream;->writeBytes(Ljava/lang/String;)V

    .line 17
    const-string/jumbo v4, "exit\n"

    invoke-virtual {v1, v4}, Ljava/io/DataOutputStream;->writeBytes(Ljava/lang/String;)V

    .line 18
    invoke-virtual {v1}, Ljava/io/DataOutputStream;->flush()V

    .line 19
    invoke-virtual {v2}, Ljava/lang/Process;->waitFor()I

    .line 20
    invoke-virtual {v2}, Ljava/lang/Process;->exitValue()I
    :try_end_0
    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0

    move-result v4

    const/16 v5, 0xff

    if-eq v4, v5, :cond_0

    .line 22
    const/4 v3, 0x1

    .line 33
    .end local v1    # "os":Ljava/io/DataOutputStream;
    .end local v2    # "p":Ljava/lang/Process;
    :goto_0
    return v3

    .line 25
    .restart local v1    # "os":Ljava/io/DataOutputStream;
    .restart local v2    # "p":Ljava/lang/Process;
    :cond_0
    const/4 v3, 0x0

    goto :goto_0

    .line 28
    .end local v1    # "os":Ljava/io/DataOutputStream;
    .end local v2    # "p":Ljava/lang/Process;
    :catch_0
    move-exception v0

    .line 29
    .local v0, "e":Ljava/lang/Exception;
    const/4 v3, 0x0

    .line 30
    goto :goto_0
.end method
`

**Comment by CrescendoFang** [comment]
Seems Go Mobile is using KonyLabs' root detector.
And it's calling **isRooted** command.
