### ISSUE TITLE
Scrolling returns to top while installing magisk module

### ISSUE THREAD

**Issue by Kingsman44** [topjohnwu/Magisk#6195]
While installing module on each of new text appears, it scrolls to top. This happens on each magisk version after 24.3 (24300)

Video of bug:

https://user-images.githubusercontent.com/58323485/185040590-0ec36f19-9221-4d54-a991-41ba48fd4f8a.mp4

Device: Redmi Note 4
Android version: 12L
Magisk version name: 25.2
Magisk version code: 25201

**Comment by Mdasim78** [comment]
Please fix this horrible ux issue at earliest possible.
Regards.

**Comment by saitamasahil** [comment]
I hope this bug will be fixed soon as it used to work perfectly before 24.3 update.

**Comment by ISAK-SWE05** [comment]
I have same problem on 25.2

**Comment by JanForShort** [comment]
> I have same problem on 25.2

same issue on same version.sad. rom:PE+

**Comment by HennyBro** [comment]
It's still not fixed. This is a very annoying (but seemingly small) bug. Why is it taking ages to fix it? Is there even a fix in the works? Or is it just being ignored?

**Comment by ISAK-SWE05** [comment]
> It's still not fixed. This is a very annoying (but seemingly small) bug. Why is it taking ages to fix it? Is there even a fix in the works? Or is it just being ignored?

Hopefully they are working on it, also I noticed (at least for me) that it only happens when it's updating, so when it's done with a thing you can scroll down.

**Comment by jbradley8484** [comment]
I hope to root my phone so I can link to my tv

**Comment by ISAK-SWE05** [comment]
> I hope to root my phone so I can link to my tv

There is no problem rooting.
