### ISSUE TITLE
Found unsupported boot image type

### ISSUE THREAD

**Issue by eparla774** [topjohnwu/Magisk#6196]
Device: Promethean ActivBoard Titanium AP7-B
Android version: 8.0.0
Magisk version name: 9b61bdfc
Magisk version code: 25201

Neither MagiskBoot, nor AIK can unpack type of boot image used by this device

[Full Update Package](https://inspire.activsoftware.co.uk/ap7/5.3.0/AP7B-Update.zip) (Official manufacturer site)
The update package has srrange structure: 1.Zip file with touch controller firmwares, manifest and normal android ota package inside. 2. Android ota package with some images (including problematic boot image, strange images and some partitions as directories)

**Comment by osm0sis** [comment]
That's not normal Android at all, the boot.img and recovery.img have "MZ" binary magic, which is DOS, and appears to just be the uncompressed kernel binary.

**Comment by eparla774** [comment]
Device Specification List:
[ActivPanel_2019_E_Titanium_SS_0921v1.5_EN_INTL.pdf](https://github.com/topjohnwu/Magisk/files/9389188/ActivPanel_2019_E_Titanium_SS_0921v1.5_EN_INTL.pdf)
Magisk app when installed on it shows Ramdisk: Yes

**Comment by eparla774** [comment]
It uses normal Android 8 and based on some HiSilicon SoC

**Comment by osm0sis** [comment]
It's not normal if it has a header of MZ instead of ANDROID!

**Comment by eparla774** [comment]
I got this from file command
.../AP7B-Update/update_5.3.0.45 $ file boot.img
boot.img: Linux kernel ARM64 boot executable Image, little-endian, 4K pages

**Comment by eparla774** [comment]
Because of Hi3751V811.dtb file i think it uses Hi3751V811 SoC [Description on HiSilicon Site](https://www.hisilicon.com/en/products/smart-media/TV/Hi3751V811)

**Comment by yujincheng08** [comment]
We are not going to support this device. You should find out where the ramdisk is and try to inject magiskinit into it.
