### ISSUE TITLE
suggestion: disable update button when user has already updated but not restarted the system

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#6214]
Device: ASUS Zenfone 4
Android version: 9
Magisk version name: 38ab6858
Magisk version code: 25203

Sometimes the user upgrades Magisk but doesn't want to restart at the moment. After closing the app and opening it again, you are faced with the "Requires adittional setup" screen that takes you back to the update installation screen. I think reinstalling the update won't do any harm, but ideally, you wouldn't have to do it again.  I recommend that when updating, save which version is currently installed (and not the one running on the daemon) and then disable the update button with a "Restart required" message, and go back to being functional again just in case a new one Magisk update (as a critical bug fix) above the installed version is released. It would be nice if the same principle were also used with modules. Thanks for your great work!

**Comment by topjohnwu** [comment]
There is no way the app can reliably detect this, so unfortunately this is impossible.
