### ISSUE TITLE
Incomplete copy of busybox due to getattr reporting the wrong file size

### ISSUE THREAD

**Issue by alexwilson1** [topjohnwu/Magisk#6221]
Device: WSA
Android version: 12.1
Magisk version name: 25203
Magisk version code: 25203

Update:

[Issue](https://github.com/LSPosed/MagiskOnWSALocal/issues/224) on WSA with busybox copy not being completed seems to be due to the [getattr function not reporting the correct size.](https://github.com/LSPosed/MagiskOnWSALocal/issues/224)

**Comment by yujincheng08** [comment]
That case, I suppose, only happens when either fd is a socket or some other stream fd.

Need more investigation.

**Comment by DeadSamurai8** [comment]
> Device: WSA Android version: 12.1 Magisk version name: 25203 Magisk version code: 25203
> 
> Update:
> 
> [Issue](https://github.com/LSPosed/LSPosed/issues/2081) on WSA with busybox copy not being completed seems to be due to the [getattr function not reporting the correct size.](https://github.com/LSPosed/LSPosed/issues/2081#issuecomment-1225302423)

**Comment by yujincheng08** [comment]
not magisk's issue
