### ISSUE TITLE
Zygisk Enabled causes Fennec browser to force closed when tapping on its address bar

### ISSUE THREAD

**Issue by zputnyq** [topjohnwu/Magisk#6227]
Device: Sony Xperia M4
Android version: 6.0.1
Magisk version name: 25.2
Magisk version code: 25203 (D)

[device_info.txt](https://github.com/topjohnwu/Magisk/files/9438425/device_info.txt)
[logcat.txt](https://github.com/topjohnwu/Magisk/files/9438427/logcat.txt)

**Comment by yujincheng08** [comment]
the logcat is not a crash log

**Comment by zputnyq** [comment]
"unable to get realpath for the library", it happens when zygisk is enabled.

**Comment by yujincheng08** [comment]
its just warnings

**Comment by yujincheng08** [comment]
since no crash log provided, close

**Comment by zputnyq** [comment]
[logcat.txt](https://github.com/topjohnwu/Magisk/files/9443814/logcat.txt)



https://user-images.githubusercontent.com/31039796/187182483-ba249148-7ee8-407e-9812-9a0dd453a094.mp4



Ok, you don'r need to re open it.
