### ISSUE TITLE
Magisk Zygisk breaks NDK C++ native breakpoints and stacktraces

### ISSUE THREAD

**Issue by twisted89** [topjohnwu/Magisk#6229]
Please actually test this before closing the issue without explanation!
The NDK issue was created before I realised Magisk was the real cause, I've left them open to cover all bases.

Device: Tested multiple - Samsung S20 FE, LG G6, HTC One M7
Android version: 11 &12
Magisk version name: 25.2
Magisk version code: 25203

With the latest Magisk installed and the Zygisk option enabled NDK C++ breakpoints cease to function, LLDB reports the error

warning: failed to set breakpoint side 0xa3d741c for breakpoint -5.1: error: 9 sending the breakpoint request.

Upon uninstalling Magisk or disabling Zygisk breakpoints then work again.

https://github.com/android/ndk/issues/1754

**Comment by twisted89** [comment]
Guessing this is just getting ignored then.

**Comment by ys1231** [comment]
I have the same problem, At present, you can only turn off the zygisk mode.
This problem bothered me for two days. At first, I had all kinds of guesses.
The problem was found only after repeated tests.

**Comment by canyie** [comment]
Try this instead of official zygisk?
https://github.com/Dr-TSNG/ZygiskOnKernelSU

**Comment by 5ec1cff** [comment]
Try executing `umount /system/bin/app_process64` in global namespace (e.g. `adb shell` ) before debugging.

**Comment by canyie** [comment]
Fixed in 9fbd079
