### ISSUE TITLE
Device Reboot into 900E Mode

### ISSUE THREAD

**Issue by qianmo-xw** [topjohnwu/Magisk#6238]
Device:Red Magic7
Android version:12
Magisk version name:25203
Magisk version code:25203
When Devices Use V24.3 can normal boot，When I USE Magisk Manger 25203 to Update direct install and reboot，Device will show RedMagic logo only，after 10 seconds，device boot to Qualcomm HS-USB Diagnostics 900E
How can I catch log for you？

**Comment by yujincheng08** [comment]
https://developer.android.com/studio/debug/bug-report
