### ISSUE TITLE
Versions of Magisk >=16.7 cannot be flashed using BootBridge

### ISSUE THREAD

**Issue by Yuki-nyan** [topjohnwu/Magisk#624]
The script change in Magisk 16.7 causes the installer to detect the real boot partition rather than the temporary one created by Bootbridge, therefore version 16.6 is the most recent one that can be flashed to a device with a Sony ELF32 boot image.

**Comment by Yuki-nyan** [comment]
Any update on this as there are now ELF32 devices (e.g. Xperia SP) which have official LineageOS 15.1 builds?

**Comment by topjohnwu** [comment]
You might want to notify the developer of BootBridge. I currently have no interest in supporting ELF boot image formats.
