### ISSUE TITLE
KB2000, C13, flash the magisk patched boot.img, it will be stuck on the lock screen for a few seconds, and then automatically enter the fastboot mode

### ISSUE THREAD

**Issue by ml863606** [topjohnwu/Magisk#6242]
Hello, when I use fastboot to flash the magisk patched boot.img, it will be stuck on the lock screen for a few seconds, and then automatically enter the fastboot mode, during which I cannot perform any operations, the logcat log is attached below, looking forward to answer, thanks

Device: KB2000(OnePlus8T)
Android version: ColorOS13
Magisk version name: 6e299018
Magisk version code: 25203

[all_2022-09-02_21-20-08.log](https://github.com/topjohnwu/Magisk/files/9478200/all_2022-09-02_21-20-08.log)
[kmsg_2022-09-02_21-20-08.log](https://github.com/topjohnwu/Magisk/files/9478202/kmsg_2022-09-02_21-20-08.log)

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/blob/0b82fe197c342789589689eaee0890e99176ee7e/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L27

**Comment by Arif4551** [comment]
Ini versi saya tolong buatin file boot.imgnya bang

RMX3630ekspor_11_C.13_2023072116320000
