### ISSUE TITLE
Magisk 25. Zygisk does not start

### ISSUE THREAD

**Issue by CDS83** [topjohnwu/Magisk#6246]
Zygisk is toggled to on in settings but not triggered. The issue seems to be different compared to similar problems already mentioned here.

Device: LENOVO M10 X605F
Android version: 11 (Lineage 18.1)
Magisk version name:  canary
Magisk version code: 25203

![Screenshot_20220903-132236_Magisk](https://user-images.githubusercontent.com/48164232/188270003-fe5d4c68-1e0d-4067-aef8-9975b081a778.png)

[magisk_log_2022-09-03T12.56.37.log](https://github.com/topjohnwu/Magisk/files/9482558/magisk_log_2022-09-03T12.56.37.log)

**Comment by HuskyDG** [comment]
It seems `zygisk64` unable to start

**Comment by canyie** [comment]
Can you execute this command in a root shell and upload the output?
`readlink -f /proc/$(pidof zygote64)/exe`

**Comment by CDS83** [comment]
Thanks for your replies ! Here is the ouput of this command:

_/system/bin/app_process64_

**Comment by canyie** [comment]
Upload `/system/etc/init/hw/init.zygote64_32.rc`?

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 05/09/2022, 08:45, ***@***.*** wrote:Upload /system/etc/init/hw/init.zygote64_32.rc?

**Comment by CDS83** [comment]
Here it is:

[init.zygote64_32.rc.zip](https://github.com/topjohnwu/Magisk/files/9487117/init.zygote64_32.rc.zip)

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 05/09/2022, 16:07, ***@***.*** wrote:Here it is:
init.zygote64_32.rc.zip

**Comment by canyie** [comment]
Try to capture a bootlog? Connect your phone to a PC, `adb logcat > boot.log`, start your phone, then upload `boot.log`

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 05/09/2022, 16:21, ***@***.*** wrote:Try to capture a bootlog? Connect your phone to a PC, adb logcat > boot.log, start your phone, then upload boot.log

**Comment by HuskyDG** [comment]
@SPYazdani Spam bot?

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 05/09/2022, 17:46, ***@***.*** ***@***.*** Spam bot?

**Comment by CDS83** [comment]
Hi, here is a boot log:
[boot.zip](https://github.com/topjohnwu/Magisk/files/9491768/boot.zip)

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 06/09/2022, 05:40, ***@***.*** wrote:Hi, here is a boot log:
boot.zip

**Comment by SPYazdani** [comment]
@HuskyDG 
Apologies, not a spambot. There is an error in the SMTP notifications for an exterior system I manage not authenticating correctly, causing the template to auto -reply all.
I'm implementing a fix soon.

**Comment by CDS83** [comment]
You're right. `setprop ctl.restart zygote` makes zygisk start, however it breaks other things like wifi. I've tested several combinations, but I could not make the tablet work with zygisk using a non-Lenovo ROM, so I've had to fall back to the latest ROM from the manufacturer. Many thanks for your analysis and your time.
