### ISSUE TITLE
Magisk Hide working, Superuser working, but modules aren't

### ISSUE THREAD

**Issue by LizardHarry** [topjohnwu/Magisk#625]
Currently, some of my Magisk modules like Viper4AndroidFX or Google Product Sans Font aren't working. I don't know what's the issue.
Log:
```
09-19 21:51:37.643  1287  1287 I Magisk  : ** Initializing Magisk
09-19 21:51:37.651  1287  1287 I Magisk  : * Creating /sbin overlay
09-19 21:51:37.661  1287  1287 I Magisk  : * Mounting mirrors
09-19 21:51:37.662  1287  1287 I Magisk  : mount: /sbin/.core/mirror/system
09-19 21:51:37.662  1287  1287 I Magisk  : link: /sbin/.core/mirror/vendor
09-19 21:51:37.662  1287  1287 I Magisk  : bind_mount: /sbin/.core/mirror/bin
09-19 21:51:37.667  1287  1287 I Magisk  : * Setting up internal busybox
09-19 21:51:38.174  1364  1364 I Magisk  : Magisk v17.1(17100) logger started
09-19 21:51:38.183  1125  1125 I Magisk  : Magisk v17.1(17100) daemon started
09-19 21:51:38.189  1125  1367 E Magisk  : mount (null)->/ failed with 16: Device or resource busy
09-19 21:51:38.190  1125  1367 I Magisk  : ** post-fs-data mode running
09-19 21:51:38.194  1125  1367 I Magisk  : * Mounting /data/adb/magisk.img
09-19 21:51:38.199  1125  1366 I Magisk  : ** late_start service mode running
09-19 21:51:38.240  1125  1366 I Magisk  : * Running service.d scripts
09-19 21:51:38.240  1125  1366 E Magisk  : opendir: /sbin/.core/img/.core/service.d failed with 2: No such file or directory
09-19 21:51:38.240  1125  1366 I Magisk  : * Running module service scripts
09-19 21:51:38.249  1125  1372 I Magisk  : * Starting MagiskHide
09-19 21:51:38.249  1125  1372 I Magisk  : hide_utils: Hiding sensitive props
09-19 21:51:38.251  1125  1372 I Magisk  : hide_list add: [com.google.android.gms.unstable]
09-19 21:51:38.373  1125  1367 I Magisk  : * Running post-fs-data.d scripts
09-19 21:51:38.374  1125  1367 I Magisk  : post-fs-data.d: exec [propsconf_post]
09-19 21:51:38.777  1331  1331 E Magisk  : bind failed with 98: Address already in use
09-19 21:51:39.376  1125  1367 I Magisk  : * Running module post-fs-data scripts
09-19 21:51:39.376  1125  1367 I Magisk  : magisk_selinux_manager: exec [post-fs-data.sh]
09-19 21:51:39.392  1125  1367 I Magisk  : MagiskHidePropsConf: exec [post-fs-data.sh]
09-19 21:51:39.440  1125  1367 I Magisk  : * Loading modules
09-19 21:51:39.440  1125  1367 I Magisk  : Volume_Steps_Increase: loading [system.prop]
09-19 21:51:43.819  1896  1896 I Magisk  : Magisk v17.1(17100) daemon started
```

I have all modules activated and updated. I'm using an LG H850 with stock Android 7.0 (Software Version: V20s-262-02) and Magisk v.17.1. 
Hope someone could help me. Thx anyways :P

**Comment by patrick-armitage** [comment]
Same exact problem with LG v20 H910.  Magisk logs that modules are starting, but many modules have no effect, such as Google Product Sans, iOS emoji, systemless Nova and others.  Everything else works fine

**Comment by KevinX8** [comment]
I have the same issue, any modules that need to symlink to /sbin/.core/mirror do not work for me on the latest havocP GSI (27/10) on my Axon 7.

**Comment by zertyuiop** [comment]
I had this problem on my OnePlus One. It can be caused by some outdated modules, in your case I think it is Volume Step Increase Module. Delete it and test. Or you can better delete all your modules and test them working one by one. I have some thoughts where is the problem, but I have not found it yet.

**Comment by patrick-armitage** [comment]
> I had this problem on my OnePlus One. It can be caused by some outdated modules, in your case I think it is Volume Step Increase Module. Delete it and test. Or you can better delete all your modules and test them working one by one. I have some thoughts where is the problem, but I have not found it yet.

In my case these are new modules downloaded from within Magisk Manager repo, initially they work but upon reboot they appear to fail to load, 1 out of every 10 or so reboots they may start working again

**Comment by topjohnwu** [comment]
This is very likely caused by broken F2FS kernel drivers of your kernel, there is nothing I can do to fix that.
