### ISSUE TITLE
magisk_patched for android 13 hangs at google logo

### ISSUE THREAD

**Issue by adamf663** [topjohnwu/Magisk#6250]
Since upgrading to android 13 on my pixel 6 pro, I am unable to install magisk.
Using the boot.img from the 13.0 google factory image, magisk generates a magisk_patchedxxxxxxx.img file.
Doing a fastboot boot magisk_patchedxxxxxxxxxx.img hangs at the google logo and never moves on to the animated G logo.
Flashing it to boot and rebooting yields the same hang.
The hang is before the adb service runs.

Device: pixel 6 pro
Android version: 13, build tp1a.220624.021
Magisk version name: 38ab6858
Magisk version code: 25203

**Comment by brownursidaeR** [comment]
Pixel 6 with same issue, but it would reboot on the animated g logo, reflashing the stock boot image would boot normally

**Comment by yujincheng08** [comment]
no log no fix

**Comment by adamf663** [comment]
No adb, no log.

**Comment by adamf663** [comment]
Also, how pray tell does anything log anything when the phone doesn't boot?

**Comment by avboy1337** [comment]
Pixel 5 and pixel 6pro are ok
