### ISSUE TITLE
超级多的进程

### ISSUE THREAD

**Issue by yyy33** [topjohnwu/Magisk#6255]
Device: motorola edge x30
Android version: 12
Magisk version name: https://github.com/topjohnwu/Magisk/commit/6066b5cf86703512451a021cf1aaf1a877530af7
Magisk version code: 25203

请问这是内存内存泄漏了吗，运行一天左右就这样了，必须重启。
![Screenshot_20220909-015117](https://user-images.githubusercontent.com/51548147/189193510-cd15ff34-5563-4d50-84cf-e588a13ac259.png)

**Comment by canyie** [comment]
https://github.com/topjohnwu/libsu/blob/master/service/src/main/java/com/topjohnwu/superuser/internal/BinderHolder.java#L28

I think this regression can only happen while the app keeps crashing (the AMS will try to restart it, and it crashes again) before it binding with root service.
The solution may be, setting a timeout in the root service. While the timeout reaches and no app has bound with us, exit the root service.

这里有代码会在 app 死掉的时候退出 root service，所以可能是在 app 收到广播与 root service 绑定之前持续崩溃引发的。我能想到的解决办法是设定一个超时时间，超时时间到了还没有 app 绑定上来就认为 app 死了然后退出 root service。

**Comment by yyy33** [comment]
> https://github.com/topjohnwu/libsu/blob/master/service/src/main/java/com/topjohnwu/superuser/internal/BinderHolder.java#L28
> 
> I think this regression can only happen while the app keeps crashing (the AMS will try to restart it, and it crashes again) before it binding with root service. The solution may be, setting a timeout in the root service. While the timeout reaches and no app has bound with us, exit the root service.
> 
> 这里有代码会在 app 死掉的时候退出 root service，所以可能是在 app 收到广播与 root service 绑定之前持续崩溃引发的。我能想到的解决办法是设定一个超时时间，超时时间到了还没有 app 绑定上来就认为 app 死了然后退出 root service。

经过你提醒，我复现了这个问题，是termux中tsu脚本引起的，执行下面的命令就会出现我这种情况
![Screenshot_20220909-104915](https://user-images.githubusercontent.com/51548147/189264998-b6bed6ac-7fcb-4a81-ae08-bf772c237522.png)
![Screenshot_20220909-105029](https://user-images.githubusercontent.com/51548147/189265034-44f04fd5-7162-4d11-a8a9-63f389afe105.png)
