### ISSUE TITLE
overlay.d not merging rc files

### ISSUE THREAD

**Issue by c0decafe** [topjohnwu/Magisk#6270]
Device: moto g200 5G (xpeng_p)
Android version: 12 (2022-07-01)
Magisk version name: 38ab6858
Magisk version code: 25203

essentially similar to #6093, contents of my custom rc file do not get merged into the system init nor any files within `/system/etc/init/*/*`.

i tested scripts under ./sbin as well and they get installed correctly, so issue seems to be specific to the rc handling.

the boot image layout is per the [docs](https://topjohnwu.github.io/Magisk/guides.html), verified by extracting it via dd and unpacking.

Is that a known problem (related the permission denied errors below?) or am i missing something?

``` console
xpeng:/sdcard/Download/out/ramdisk # find overlay.d
overlay.d/
overlay.d/custom.rc
overlay.d/sbin
overlay.d/sbin/magisk64.xz
overlay.d/sbin/magisk32.xz
```

``` console
xpeng:/sdcard/Download/out/ramdisk # cat overlay.d/custom.rc 
on pre-init
    mkdir /test 0775 root system
```

``` console
xpeng:/ #  dmesg | grep -i magisk
[   14.428464] init: starting service 'exec 48 (/dev/Hu7i/magisk --boot-complete)'...
[   14.430029] init: SVC_EXEC service 'exec 48 (/dev/Hu7i/magisk --boot-complete)' pid 3433 (uid 0 gid 0+0 context default) started; waiting...
[   14.435326] type=1400 audit(1663259959.387:117): avc: denied { read } for comm="magisk" name="bin" dev="dm-2" ino=44 scontext=u:r:magisk_client:s0 tcontext=u:object_r:vendor_file:s0 tclass=dir permissive=0
[   14.435360] type=1400 audit(1663259959.387:118): avc: denied { search } for comm="magisk" name="tests" dev="dm-8" ino=107 scontext=u:r:magisk_client:s0 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0
[   14.435375] type=1400 audit(1663259959.387:119): avc: denied { search } for comm="magisk" name="tests" dev="dm-8" ino=107 scontext=u:r:magisk_client:s0 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0
[   14.435388] type=1400 audit(1663259959.387:120): avc: denied { search } for comm="magisk" name="tests" dev="dm-8" ino=107 scontext=u:r:magisk_client:s0 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0
[   14.435400] type=1400 audit(1663259959.387:121): avc: denied { search } for comm="magisk" name="tests" dev="dm-8" ino=107 scontext=u:r:magisk_client:s0 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0
[   14.435411] type=1400 audit(1663259959.387:122): avc: denied { read } for comm="magisk" name="/" dev="dm-8" ino=3 scontext=u:r:magisk_client:s0 tcontext=u:object_r:system_data_root_file:s0 tclass=dir permissive=0
[   14.438969] init: Service 'exec 48 (/dev/Hu7i/magisk --boot-complete)' (pid 3433) exited with status 0 waiting took 0.009000 seconds
[   14.438977] init: Sending signal 9 to service 'exec 48 (/dev/Hu7i/magisk --boot-complete)' (pid 3433) process group...

```

``` console
xpeng:/ # logcat | grep -i magisk
09-15 19:39:14.543  1176  2362 I SystemServerTimingAsync: InitThreadPoolExec:Update app-ops uidState in case package com.topjohnwu.magisk changed
09-15 19:39:15.129  1176  1176 V StorageManagerService: Package com.topjohnwu.magisk does not have legacy storage
```

**Comment by romanovj** [comment]
why grep magisk? The one who execute .rc script is init

script:

on load_persist_props_action
  exec u:r:su:s0  -- /system/bin/mount -t overlay overlay -o lowerdir=/system,upperdir=/data/system/ou,workdir=/data/system/ow /system


logcat | grep /mount

09-18 22:33:54.606     0     0 I [09-18 19:33:54] init: starting service 'exec 47 (/system/bin/mount -t overlay overlay -o lowerdir=/system,upperdir=/data/system/ou,workdir=/data/system/ow /system)'...
09-18 22:33:54.609     0     0 I [09-18 19:33:54] init: SVC_EXEC service 'exec 47 (/system/bin/mount -t overlay overlay -o lowerdir=/system,upperdir=/data/system/ou,workdir=/data/system/ow /system)' pid 1896 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
09-18 22:33:54.663     0     0 I [09-18 19:33:54] init: Service 'exec 47 (/system/bin/mount -t overlay overlay -o lowerdir=/system,upperdir=/data/system/ou,workdir=/data/system/ow /system)' (pid 1896) exited with status 0 waiting took 0.054000 seconds
09-18 22:33:54.663     0     0 I [09-18 19:33:54] init: Sending signal 9 to service 'exec 47 (/system/bin/mount -t overlay overlay -o lowerdir=/system,upperdir=/data/system/ou,workdir=/data/system/ow /system)' (pid 1896) process group...

**Comment by c0decafe** [comment]
Tried the below, assuming it was being indeed merged, but not executed properly (wrong hook, context or missing path etc) 

```rc
on load_persist_props_action
   exec u:r:su:s0 -- /system/bin/touch /dev/test
```
but no luck
```console
xpeng:/ # ls /dev/test
ls: /dev/test: No such file or directory
1|xpeng:/ # logcat | grep /touch
```
any pointers on how i should debug this?

**Comment by romanovj** [comment]
first of all, does it work for you on magisk 24.3 stable?

**Comment by c0decafe** [comment]
@romanovj could not fully install [v24.3](https://github.com/topjohnwu/Magisk/releases/download/v24.3/Magisk-v24.3.apk), getting the below, which then upgrades to the latest stable no matter what:
![image](https://user-images.githubusercontent.com/220505/191078159-1f955190-a9d8-4a35-bb4d-a58da405004f.png)

any other ideas?

**Comment by romanovj** [comment]
flash stock boot, install magisk 24.3, patch boot with it

**Comment by pndwal** [comment]
... Or take Direct Install Debug build to bypass [Force app version not lower than daemon](https://github.com/topjohnwu/Magisk/commit/b9c93c66f6a3c85fd4560c1c709ee9482330353c) in 25.1+ (Nb. This will also bypass [Enforce package signature verification](https://github.com/topjohnwu/Magisk/commit/083ef803fea855d6962528dab5a85462253c4dcc) to take CI builds etc), then Direct Install 24.3...

... Also, to rebuild Magisk config files clean after downgrading, remove contents of /data/adb and reboot...

And setting Custom channel to "https://raw.githubusercontent.com/topjohnwu/magisk-files/3f127524b63d5001d391af9a1fe2f7d1590a088c/stable.json" will overcome issues with incompatible (latest) stub for 'Hide the Magisk app'...

**Comment by c0decafe** [comment]
@romanovj  tried @pndwal's  (thank you) then a clean boot as well, still the same:

``` console
xpeng:/data/adb/modules/test # cat custom.rc                                               
on load_persist_props_action
   exec u:r:su:s0 -- /system/bin/touch /dev/test
xpeng:/data/adb/modules/test # ls -als /dev/test
ls: /dev/test: No such file or directory
```

I presume something about the device?

**Comment by romanovj** [comment]
on magisk 24.3 you can see modified  init.rc
/sbin/.magisk/rootdir/system/etc/init/hw/init.rc

everything new should be at the bottom

**Comment by romanovj** [comment]
with wich command did you push script to the boot.img?

**Comment by c0decafe** [comment]
@romanovj installing via zip bundle with script based on [customize.sh](https://github.com/HuskyDG/magisk-overlay.d-sample-patch/blob/main/customize.sh)

I couldn't find `/sbin`, but found the merged(!) `init.rc` it under `/dev/d423/.magisk/rootdir/system/etc/init/hw`

Is the lack of `/sbin` relevant here?

Nothing in the logs regarding `/dev/test` or `/sbin`

``` console
xpeng:/dev/d423/.magisk/rootdir/system/etc/init/hw # magisk -v                               
24.3:MAGISK
xpeng:/dev/d423/.magisk/rootdir/system/etc/init/hw # grep /dev/test init.rc                                                                                                                  
   exec u:r:su:s0 -- /system/bin/touch /dev/test
xpeng:/dev/d423/.magisk/rootdir/system/etc/init/hw # ls -asl /dev/test
ls: /dev/test: No such file or directory
```

**Comment by romanovj** [comment]
lol, I only use GSI roms, that's why I have magisk in /sbin folder....

what about logs?

**Comment by c0decafe** [comment]
Could not find anything relevant in the logs.

But now that i can inspect the output `init.rc` i can confirm that is not an rc merge issue, but most likely a permissions issue.

ie, the below snippet works for both v24.3 and latest stable:

``` rc
:/data/adb/modules/test # cat custom.rc
on init
   mkdir /dev/test
```

What doesn't work however is `mkdir /test` (I'm essentially trying to run an application that requires a specific absolute path/mount without a chroot), no matter at which stage i try to create it.

Any pointers on how i should debug this would be really appreciated.

I'll close this issue in the meantime, thank you @romanovj @pndwal

**Comment by romanovj** [comment]
I don't if I'm right, but isn't root is overplayed by system partition?  So if you want /test then you need to modify /system before  pivot root or edit / after... maybe with overlayfs

Isn't it easier to use existing already folders?
