### ISSUE TITLE
OS boot stuck

### ISSUE THREAD

**Issue by pashamcr** [topjohnwu/Magisk#6296]
Device: Xiaomi Redmi 4 Prime
ROM: https://www.opendesktop.org/p/1427615/
Android version: 10
Magisk version name: 25.2
Magisk version code: 25203

After this commit https://github.com/topjohnwu/Magisk/commit/ff2513e2761f7435a47df9e6606f605f8af9d75e the system cannot boot, all subsequent versions of Magisk do not allow android to boot. 
There are a lot of similar lines in the bugreport-rr, I don’t know if this applies to the problem:
`CANNOT LINK EXECUTABLE "/system/bin/app_process32": "/dev/preload.so" is 64-bit instead of 32-bit`
[bugreport-rr_markw-QQ3A.200905.001-2022-09-29-20-24-52.txt](https://github.com/topjohnwu/Magisk/files/9684960/bugreport-rr_markw-QQ3A.200905.001-2022-09-29-20-24-52.txt)

Is this possible to fix, or is it a firmware bug?

**Comment by canyie** [comment]
Looks like `/system/bin/init` is not dynamic but static executable, so our `LD_PRELOAD` not getting loaded. Could you upload that file?

**Comment by pashamcr** [comment]
@canyie 
[init.zip](https://github.com/topjohnwu/Magisk/files/9689875/init.zip)

**Comment by canyie** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/9690703/app-debug.zip)
Can this build boot?

**Comment by pashamcr** [comment]
@canyie thanks a lot for the fixes, android has booted up. Will this fix be applied to future versions of Magisk?

**Comment by canyie** [comment]
I have submitted my fix in #6296, not sure if John wants to merge it.

**Comment by pashamcr** [comment]
@canyie thank you for your help. If this change doesn't make it into Magisk, I'll apply it myself in the future and build the app for myself.
