### ISSUE TITLE
ScreenCast don't work after Magisk is installation !

### ISSUE THREAD

**Issue by tnagorran** [topjohnwu/Magisk#6303]
Device: Pixel 6
Android version: 13
Magisk version name: 25.2
Magisk version code: 25203
ASOP: GrapheneOS

I don't know why, but after installing Magisk INSTANTLY, I can't do ScreenCast (or use Displaylink app for run ScreenCast).

I tried reinstalling my phone and everything works but after just installing Magisk (without needing to root) ScreenCast (or use Displaylink app for run ScreenCast) doesn't work, I can uninstall Magisk and Displaylink apps but it doesn't work again, I have to reinstall my image to be able to use ScreenCast (or use Displaylink app for run ScreenCast) again :/

for more precision, the popup asking me if I want to share my screen does not appear anymore.

it's really strange! do you think the Magisk application is detected by the OS and is set a flags?

I can test for you if you need it, I was thinking of compiling a version of Magisk compiled with another name so if you already have a version that does this I would tell you if it worked.

**Comment by pndwal** [comment]
> ... after just installing Magisk (without needing to root) ScreenCast (or use Displaylink app for run ScreenCast) doesn't work...

Do you mean screencast fails with just Magisk App installed (and no root)?... If so it sounds like a detection issue...

Have you installed @Displax's mod of @kdrag0n's Universal SafetyNet fix to pass SafetyNet and new Play Integrity deviceIntegrity verdict?
https://forum.xda-developers.com/t/magisk-module-universal-safetynet-fix-2-3-1.4217823/post-87198517

Also, have you taken 'Hide the Magisk app' Magisk function?... Nb. Some apps require further hiding/ obfuscation of Magisk App eg. using LSPosed Hide My Applist module...

If detection is the issue, this is not a Magisk issue/problem... Of course it could still be a Magisk issue if root is breaking screencast function, or other, eg user error (flashed mismatched boot.img eg after an ITA update, etc).

**Comment by pndwal** [comment]
Nb. Also, this issue will likely simply be closed by contributing Devs in the absence of required logs... 😉

**Comment by tnagorran** [comment]
![IMG_20221003_143703](https://user-images.githubusercontent.com/109517029/193653466-8e68c533-eeb2-40af-afe0-5c19649539e3.jpg)
![IMG_20221003_143727](https://user-images.githubusercontent.com/109517029/193653469-cd1b2004-8162-49a3-aa2a-96add343f04a.jpg)
![IMG_20221003_143743](https://user-images.githubusercontent.com/109517029/193653471-036da084-0caf-42c9-a45a-4b3c54232cc8.jpg)
![IMG_20221003_143805](https://user-images.githubusercontent.com/109517029/193653473-c5a066c0-e679-4979-bafb-6183cc96a51e.jpg)

 I already did that BUT I don't need root for the screencast doesn't work I just needed to install magisk, root doesn't change anything the apair blockade after just install magisk and I can uninstall or root or root+hide it doesn't change anything. 

Everything works perfectly, but directly after the installation of magisk (no root or boot.IMG patch at that time (do this does not change the blocking even with a hide because the blocking occurs after the installation of magisk even if I root and can import that I uninstall magisk or anything else even if the root the simple fact of installing magisk causes the blocking permanently) I am forced to reinstall by flashing my phone to use screencast again

Im test 2time and 2time all works but directly after magisk is install ScreenCast and probably author feature go alone and the only way to recovery you feature I need to re install by flashing completely the phone because uninstall or elle don't works

**Comment by tnagorran** [comment]
I can record my freshly installed phone and see that everything is working,
and right after installing magisk.apk, my screencast (and probably auther feature) shuts down and never shows up again without a full reinstallation

**Comment by pndwal** [comment]
Nb. Magisk App is not Magisk; it's just a 'dashboard' or manager for Magisk... So seems you mean Magisk App is detected while Magisk is not installed...

So evidently this is a detection issue, and Hide the Magisk app function may not be sufficient to hide itself if you have enabled that...

I'm not familiar with casting on any device, but seems Pixel 6 only has native support for ChomeCast... If you rely on a 3rd party app for compatibility ('Displaylink', other), it may be that that is detecting magisk...

Did you try further hiding Magisk App from these using HMA LSPosed module as mentioned?...

Does ChromeCast work?

I doubt I can provide any further useful clues, but please say if you have any reason to believe native casting code is detecting Magisk...
