### ISSUE TITLE
(Update) ScreenCast don't work after Magisk is installation !

### ISSUE THREAD

**Issue by tnagorran** [topjohnwu/Magisk#6304]
Device: Pixel 6
Android version: 13
Magisk version name: 25.2
Magisk version code: 25203
ASOP: GrapheneOS

Update:
https://github.com/topjohnwu/Magisk/issues/6303

Note: you can wait for my answer before closing, closing the issues does not solve the problem, 
especially since the reasons you gave were explained, the error occurs even before patching the image so it's not a flash or hide_module error, and since the error occurs happens right after installation so magisk doesn't say anything

**Comment by yujincheng08** [comment]
> the error occurs even before patching the image

Apparently, there's nothing to do with Magisk.

**Comment by pndwal** [comment]
I did tell you
> If detection is the issue, this is not a Magisk issue/problem...
