### ISSUE TITLE
No available debug builds on Github

### ISSUE THREAD

**Issue by Eonfge** [topjohnwu/Magisk#6308]
Device: OnePlus 7 Pro
Android version: Android 11, Lineage OS 18.1 latest weekly
Magisk version name: 25.2
Magisk version code: 25203

When MagiskBot closed my bug report related to a magisk crash, I was unable to find the debug-build that MagiskBot makes mention of.  Please add some instruction to the MagiskBot on how to obtain the latest debug-build so that I can provide constructive bug reports. If users must build the debug-version themselves, please tell so.

**Comment by pndwal** [comment]
No need to build...

GitHub main page, button under 'Downloads'...
