### ISSUE TITLE
25204 breaks basic integrity.

### ISSUE THREAD

**Issue by Originalimoc** [topjohnwu/Magisk#6314]
Device: any
Android version: 12/12L
Magisk version name: c3b4678f
Magisk version code: 25204

Denylist won't work:
Momo reports found Magisk/su/zygisk.
Terminal can access su command.

The code refactor/cleaning is not logically intentional.

**Comment by Originalimoc** [comment]
Why can I install old version on one device but on another device it just force closed and get replaced by the stub 1.0 version.

**Comment by Originalimoc** [comment]
Possible related log: /data/data/com.android.systemui not found

**Comment by Originalimoc** [comment]
I remember since Android 11 access to /data/data is restricted even syscall uid is root, ls command returns only current app and GMS directory even in root shell.
?

**Comment by Originalimoc** [comment]
Then if to_app_id(uid) for whatever reason returns -1, denylist will fail because hit that sysui unmouny bypass.

**Comment by Jcbrewster4180** [comment]
Privacy.blog – Privacy news and resources for WordPress
<https://drive.google.com/file/d/1_IrhMVhaTtCv1Z3SSRBrInSo9Qbp-bJg/view?usp=drivesdk>

**Comment by HuskyDG** [comment]
> I remember since Android 11 access to /data/data is restricted even syscall uid is root, ls command returns only current app and GMS directory even in root/su shell. ?

Don't you know mount namespace?

**Comment by HuskyDG** [comment]
It seems there is the problem that magisk doesn't unmount and trip Play Integrity check

**Comment by HuskyDG** [comment]
> Why can I install old version on one device but on another device it just force closed and get replaced by the stub 1.0 version.

Caused by a "signature enforcement" signature, prevent you from installing unofficial magisk build. I don't see this feature useful.

**Comment by ShiinaMono** [comment]
me too,it's bad

**Comment by Jcbrewster4180** [comment]
I've shared an item with you:

  externalObjects: {}
https://drive.google.com/file/d/1K2i2lrGnqgVHr42HnK1VsipD9Wt0H4wg/view?usp=sharing&invite=CKWD1s4K&ts=6349467b

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

19714141902A

**Comment by Jcbrewster4180** [comment]
I've shared an item with you:

flow-35.log
https://docs.google.com/document/d/1UhfYtAFINu4PDsvLc-22Y-ixd_sNAD9E6ZySdZXC0LI/edit?usp=sharing&invite=COCW1sAO&ts=6363e732

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

https://docs.google.com/document/d/1UhfYtAFINu4PDsvLc-22Y-ixd_sNAD9E6ZySdZXC0LI/edit?usp=drivesdk

**Comment by Jcbrewster4180** [comment]
I've shared an item with you:

LibraryCloudStorage
https://docs.google.com/document/d/1uXUr8S3DLnSdadCCMU6PYVlPKCVU0Ec8PWOx-l3iSiw/edit?usp=sharing&invite=CMTxgaYI&ts=636447fe

It's not an attachment -- it's stored online. To open this item, just click  
the link above.
