### ISSUE TITLE
25205 stat /data/data/com.android.systemui failed

### ISSUE THREAD

**Issue by 54271** [topjohnwu/Magisk#6322]
Device: pixel 6 pro
Android version: 13
Magisk version name: canary
Magisk version code: 25205

10-12 08:14:29.519   816   818 E : stat /data/data/com.android.systemui failed with 2: No such file or directory

i got this error a few times in magisk log, is it normal?

**Comment by osm0sis** [comment]
I'm seeing this too. Even weirder, /data/data/com.android.systemui exists.

**Comment by jeanrivera** [comment]
I can confirm this too

**Comment by Originalimoc** [comment]
Just about to open a new issue too XD.
This requires a better handling.
Not breaking anything on Android 12 though, maybe Android 8/8.1?

**Comment by canyie** [comment]
It seems that Magisk accesses it too early and `/data/data` not decrypted yet?

**Comment by HuskyDG** [comment]
How about stat `/data/user_de/0/com.android.systemui`

**Comment by WYC-2020** [comment]
I can confirm this too

**Comment by osm0sis** [comment]
Doesn't look too early in the log, it's at late_start and boot_competed even.

As for user_de, it doesn't exist in all Zygisk-supported Android versions, I think.

**Comment by HuskyDG** [comment]
stat com.android.sysui was just to get uid of systemui
Do you think users will add sysui to denylist?

**Comment by HuskyDG** [comment]
iirc `/data/data` is only decrypted after user unlock screenlock

**Comment by canyie** [comment]
According to John's comments, just unmounting `app_process` also breaks system? So it's no need to add SystemUI to denylist, just turning Zygisk on is enough to break the system?

**Comment by HuskyDG** [comment]
He means unmount `app_process` breaks SystemUI and *reproducible on the official AVD running API 26 and 27*

**Comment by Jcbrewster4180** [comment]
> Device: pixel 6 pro
> Android version: 13
> Magisk version name: canary
> Magisk version code: 25205
> 
> 10-12 08:14:29.519   816   818 E : stat /data/data/com.android.systemui failed with 2: No such file or directory
> 
> i got this error a few times in magisk log, is it normal?

[]()
