### ISSUE TITLE
Custom ROM won't retain root after flashing custom kernel and rebooting

### ISSUE THREAD

**Issue by DarkPoe** [topjohnwu/Magisk#6328]
[logcat.txt](https://github.com/topjohnwu/Magisk/files/9792817/logcat.txt)

Device: Pixel 6 Pro
Android version: 13
Magisk version name: Canary
Magisk version code: 25205

Currently running RiceDroid 7.0 on my Pixel 6 Pro which I can root the stock boot.img without issues, but when trying a custom kernel (Kirisakura 4.2.0), it will install, but when rebooting, it won't be rooted

**Comment by vvb2060** [comment]
Ask the kernel dev
