### ISSUE TITLE
Magisk v17.2 and Magisk Manager

### ISSUE THREAD

**Issue by Deviltrucker** [topjohnwu/Magisk#633]
Well, the newer versions of Magisk 17.1 and 17.2 won't detect root apps like Kernel Auditor.
About Magisk manager I always have a crash no matter what version is (on the old ones didn't happen) when I tap on the module to see information about the module.
Downgraded to 16.7 just to use root apps without any issue but the manager still crashes

**Comment by topjohnwu** [comment]
No log = no fix

**Comment by Deviltrucker** [comment]
Initializing Magisk
09-21 17:39:07.682   263   263 I Magisk  : * Creating /sbin overlay
09-21 17:39:07.692   263   263 E Magisk  : symlinkat /root/supolicy->supolicy failed with 17: File exists
09-21 17:39:07.692   263   263 I Magisk  : * Mounting mirrors
09-21 17:39:07.692   263   263 I Magisk  : mount: /sbin/.core/mirror/system
09-21 17:39:07.692   263   263 I Magisk  : link: /sbin/.core/mirror/vendor
09-21 17:39:07.692   263   263 I Magisk  : bind_mount: /sbin/.core/mirror/bin
09-21 17:39:07.692   263   263 I Magisk  : * Setting up internal busybox
09-21 17:39:07.792   270   270 I Magisk  : Magisk v17.2(17200) logger started
09-21 17:39:07.792   267   267 I Magisk  : Magisk v17.2(17200) daemon started
09-21 17:39:07.802   267   272 I Magisk  : ** post-fs-data mode running
09-21 17:39:07.802   267   272 I Magisk  : * Mounting /data/adb/magisk.img
09-21 17:39:07.922   267   272 I Magisk  : * Running post-fs-data.d scripts
09-21 17:39:07.922   267   272 I Magisk  : * Running module post-fs-data scripts
09-21 17:39:07.922   267   272 I Magisk  : * Loading modules
09-21 17:39:07.922   267   272 I Magisk  : extendwifi: loading [system.prop]
09-21 17:39:07.922   267   272 E Magisk  : Illegal property name: [gsm.operator.iso-country ]
09-21 17:39:07.922   267   272 E Magisk  : Illegal property name: [gsm.sim.operator.iso-country ]
09-21 17:39:07.922   267   272 I Magisk  : opengl_skia_enabler: loading [system.prop]
09-21 17:39:07.922   267   282 I Magisk  : * Starting MagiskHide
09-21 17:39:07.922   267   282 I Magisk  : hide_utils: Hiding sensitive props
09-21 17:39:07.922   267   282 I Magisk  : hide_list: [com.google.android.gms.unstable]
09-21 17:39:07.972   267   282 E Magisk  : proc_monitor: Your kernel doesn't support mount namespace :(
09-21 17:39:08.863   267   344 I Magisk  : ** late_start service mode running
09-21 17:39:08.863   267   344 I Magisk  : * Running service.d scripts
09-21 17:39:08.863   267   344 I Magisk  : * Running module service scripts
09-21 17:39:08.863   267   344 I Magisk  : CloudflareDNS4Magisk-IPv6: exec [service.sh]
09-21 17:39:08.863   267   348 I Magisk  : * Starting MagiskHide
09-21 17:39:08.863   267   348 I Magisk  : hide_utils: Hiding sensitive props
09-21 17:39:08.863   267   348 I Magisk  : hide_list: [com.google.android.gms.unstable]
09-21 17:39:08.913   267   348 E Magisk  : proc_monitor: Your kernel doesn't support mount namespace :(
09-21 17:39:09.013   267   344 I Magisk  : swaptorpedo: exec [service.sh]
09-21 17:43:48.772 12782 12782 E Magisk  : select failed with 2: No such file or directory
