### ISSUE TITLE
Magisk N/A With ( SAR A/B Device + boot - recovery )

### ISSUE THREAD

**Issue by blackfa1con** [topjohnwu/Magisk#6333]
We have problem making the Magisk work with this custom imx8 pcb.
The pcb use android 9 with A/B slots and boot_a/boot_b partitions only and no recovery...
The recovery binary embedded inside the boot img.
After many test and research we find that the kernel always load the init from system partition in normal boot, after patch and flash the boot_a.img and boot_b.img the magisk init load only from recovery and no way to make system boot to normal mode with magisk init...

how to integrate the magisk inside system.img or patch the boot_a.img to always load init from the boot ramdisk not the system part?

Patched boot_a.img : https://easyupload.io/s0slo7
Stock boot_a.img : https://easyupload.io/egf7y1

Device: IMX8 Custom rom
Android version: 9 
Magisk version name: Debug
Magisk version code: 25205

**Comment by vvb2060** [comment]
Ask the ROM dev

**Comment by vvb2060** [comment]
This is expected behavior
