### ISSUE TITLE
Magiskboot fails to get cmdline on 5.4 kernel

### ISSUE THREAD

**Issue by pedrozzz0** [topjohnwu/Magisk#6341]
Magiskboot fails to get the cmdline properly on 5.4 kernel, not sure if it happens on below too

(Unpacking)
Parsing boot image: [/dev/block/by-name/boot_b]
HEADER_VER      [3]
KERNEL_SZ       [42713600]
RAMDISK_SZ      [12415119]
OS_VERSION      [11.0.0]
OS_PATCH_LEVEL  [2022-09]
PAGESIZE        [4096]
CMDLINE         []
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
VBMETA

Device: Motorola edge 20 (berlin)
Android version: 12 (motorola/berlin_global/berlin:11/S1RGS32.53-18-22-4/afcdf0:user/release-keys)
Magisk version name: [a468fd94](https://github.com/topjohnwu/magisk-files/blob/master/canary.json)
Magisk version code: 25205 (34)
Kernel version: 5.4.147-moto-g4060eeb60788 
#1 Thu Aug 18 00:02:08 CDT 2022
cmdline: cgroup_disable=pressure log_buf_len=256K rcupdate.rcu_expedited=1 rcu_nocbs=0-7 kpti=off quiet console=null androidboot.hardware=qcom androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 androidboot.usbcontroller=a600000.dwc3 swiotlb=0 loop.max_part=7 cgroup.memory=nokmem,nosocket pcie_ports=compat loop.max_part=7 iptable_raw.raw_before_defrag=1 ip6table_raw.raw_before_defrag=1 androidboot.hab.csv=14 androidboot.hab.product=berlin androidboot.hab.cid=50 firmware_class.path=/vendor/firmware_mnt/image buildvariant=user quiet androidboot.verifiedbootstate=orange androidboot.keymaster=1 androidboot.vbmeta.avb_version=1.0 androidboot.vbmeta.device_state=unlocked androidboot.vbmeta.hash_alg=sha256 androidboot.vbmeta.size=6464 androidboot.vbmeta.digest=690a6fc0b919334c9e7819df52ca925cc1efa4e9bd4ef97c8d4178a2b1e98885 androidboot.vbmeta.invalidate_on_error=yes androidboot.veritymode=enforcing androidboot.bootdevice=1d84000.ufshc androidboot.fstab_suffix=default androidboot.boot_devices=soc/1d84000.ufshc androidboot.serialno=ZY22G335P3 androidboot.device=berlin androidboot.revision=pvt2 androidboot.hwrev=0xC200 androidboot.radio=ROW androidboot.powerup_reason=0x00004000 androidboot.bootreason=reboot msm_poweroff.download_mode=0 androidboot.bootloader=MBM-3.0-berlin_global-1f15ff22498-220817 androidboot.carrier=reteu androidboot.hardware.sku=XT2143-1 androidboot.mode=normal androidboot.baseband=msm msm_drm.dsi_display0=qcom,mdss_dsi_mot_csot_nt37701_667_1080x2400_dsc_cmd_v2:timing1: androidboot.slot_suffix=_b rootwait ro init=/init androidboot.dtbo_idx=6 androidboot.dtb_idx=2 androidboot.force_normal_boot=1 storage_mfrid=0x12C androidboot.secure_hardware=1 androidboot.cid=0x0032 androidboot.write_protect=0 androidboot.bl_state=2
androidboot.ssm_data=00000000000FEEE1

**Comment by pedrozzz0** [comment]
[Boot image for reference](https://drive.google.com/file/d/15PS36ep35CwkFBuS_hPIArDX2Qwl6OnR/view?usp=drivesdk)

**Comment by topjohnwu** [comment]
The boot image cmdline and kernel cmdline is not the same thing

**Comment by pedrozzz0** [comment]
nvm, how it used to work since on 5.4 and below it was working

**Comment by pedrozzz0** [comment]
@topjohnwu the cmdline issue is actually a regression, cmdline works fine on a old magiskboot version
