### ISSUE TITLE
Magisk still break boot recovery ramdisk

### ISSUE THREAD

**Issue by cuynu** [topjohnwu/Magisk#6347]
I have submited issue on Magisk debug build 9183a0a6 about this problem. its has been fixed on official Magisk v25.1 but when i update to 25.2 or Magisk debug build a468fd94, That problem recurred again, I still can't get into recovery after patching it with magisk debug build a468fd94. Recovery ramdisk is in the boot partition because my device is A/B device, because recovery ramdisk is broken so i can't access adb to grab logcat.

Device:Sony Xperia XZ2
Android version:11
Magisk version name:25205
Magisk version code:a468fd94 25205 (D)

Original boot image 
[boot_original.zip](https://github.com/topjohnwu/Magisk/files/9843803/boot_original.zip)
Magisk patched boot image
[boot_patched.zip](https://github.com/topjohnwu/Magisk/files/9843811/boot_patched.zip)

**Comment by pndwal** [comment]
Seems your previous issue
https://github.com/topjohnwu/Magisk/issues/6061
was 'fixed' by merging this:
https://github.com/topjohnwu/Magisk/pull/6040

I don't fully understand why it fixed your issue, but notice that the statement "With Android 13 GKI kernels, the boot partition has no ramdisk..." is not strictly correct; In A11 GKI means the ramdisk is split into generic and vendor ramdisks; boot.img retains generic ramdisk while vendor parts are now in vendor_boot partition... GKI in A13 also retains generic ramdisk where devices are updated to 13; In devices launched with 13, GKI, ie. boot.img, does actually 'have no ramdisk' as generic ramdisk is now moved out to init_boot.img with vendor parts remaining in vendor _boot...

I'm wondering if a lack of clarity on how GKI is implemented meant the fix, using symlink to boot into recovery, was not properly thought through... Or perhaps there's been some other regression...

**Comment by yujincheng08** [comment]
If it's a regression, could you locate the problematic commit?

**Comment by cuynu** [comment]
> Seems your previous issue #6061 was 'fixed' by merging this: #6040
> 
> I don't fully understand why it 'fixed' your issue initially, but notice that the statement "With Android 13 GKI kernels, the boot partition has no ramdisk..." is not strictly correct; In A11 GKI means the ramdisk is split into generic and vendor ramdisks; boot.img retains generic ramdisk while vendor parts are now in vendor_boot partition... GKI in A13 also retains generic ramdisk where devices are updated to 13; In devices launched with 13, GKI, ie. boot.img, does actually 'have no ramdisk' as generic ramdisk is now moved out to init_boot.img with vendor parts remaining in vendor _boot...
> 
> I'm wondering if a lack of clarity on how GKI is implemented meant the fix, using symlink to boot into recovery, was not properly thought through... Or perhaps there's been some other regression...

My device has nothing related to GKI or vendor_boot

**Comment by pndwal** [comment]
> My device has nothing related to GKI or vendor_boot

... And yet it seems that fix worked initially for you...

Anyway, I have only a fundamental understanding of Google architecture, changes and how OEMs implement... @yujincheng08 is a main Magisk dev... My comments might  help, but she will most likely be able fix your issue...

You should now supply information she requests if possible... Looks like she wants you narrow down which debug build between 25.1 and 25.2 reintroduced the issue... Perhaps you could also test CI (workflow) builds from Actions to further narrow down commit w/ regression...
