### ISSUE TITLE
Zygisk Module: root companion unable to perform transaction when module is linking libraries `android`

### ISSUE THREAD

**Issue by BryanGIG** [topjohnwu/Magisk#6351]
Device: Poco X3 NFC
Android version: 12
Magisk version name: a468fd94
Magisk version code: 25205

When i compile my zygisk module with `-landroid` it seems like the root companion is connected but unable to perform transaction between process

Here's logcat that i capture:
* Before using `-landroid`
![image](https://user-images.githubusercontent.com/91574316/197647428-e7a4761a-7eb5-4d8e-8e1d-d09a81ec941e.png)
* After using `-landroid` enabled
![image](https://user-images.githubusercontent.com/91574316/197648249-32e1119f-2f3a-4314-aeb9-6963cb0a4334.png)

**Comment by yujincheng08** [comment]
Expected behavior. You need to deal with it yourself.
