### ISSUE TITLE
`readlink` and `readlinkat`'s parameters should have `__restrict__` keywords

### ISSUE THREAD

**Issue by yujincheng08** [topjohnwu/Magisk#6353]
Device: any
Android version: any
Magisk version name: any
Magisk version code: 25205

> The restrict keyword is added to the readlink()/readlinkat() prototype for alignment with the ISO/IEC 9899:1999 standard.

The following code is UB:

https://github.com/topjohnwu/Magisk/blob/916e373edba1ca18b3356e51b7e0b6be9c18c5e1/native/src/zygisk/entry.cpp#L163-L166

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/blob/v25.2/native/jni/base/files.cpp#L12-L15
https://github.com/topjohnwu/Magisk/blob/6066b5cf86703512451a021cf1aaf1a877530af7/native/jni/base/files.cpp#L12-L15

This is also related to the signature verification failure of the stable version
