### ISSUE TITLE
Pixel Watch panics on boot

### ISSUE THREAD

**Issue by shinyquagsire23** [topjohnwu/Magisk#6356]
I managed to coax the boot images out of my Pixel Watch with some [fastboot shenanigans](https://gist.github.com/shinyquagsire23/824d4e6b08379f3b537fa703d2b1874a) and patched them with Magisk from my phone, however the patched image unfortunately does not work with `fastboot boot`. I haven't attempted to flash any modified boot.imgs, since I haven't figured out how to enter fastboot without going through Android, yet.

[kernel logs](https://gist.github.com/shinyquagsire23/c00a107f11e71f03b6a8489f91e57bb3)
[Boot Images](https://drive.google.com/drive/folders/1m_gkqAopDyn4MhTtdYisGWWwpbMqoZxJ?usp=sharing)

The kmsg logs were pulled using the bug report tool, not sure if that culls anything or not.

Device: Google Pixel Watch
Android version: Wear OS 3.5 (Build RWD9.220429.053.G1)
Magisk version name: a468fd94
Magisk version code: 25205

**Comment by Dionicio3** [comment]
Fyi, Google has official instructions to enter fastboot on the watch you can give a try
https://support.google.com/googlepixelwatch/answer/12661804?hl=en&ref_topic=12651863#zippy=%2Creset-to-factory-settings%2Cforgot-pin-or-passcode

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/9867402/app-debug.zip)
Please pull kernel logs with this build.

**Comment by shinyquagsire23** [comment]
@yujincheng08 for whatever reason, the apk you uploaded asks to be updated immediately on first boot (with no other options)

**Comment by shinyquagsire23** [comment]
One possibly weird detail: The kernel is 64-bit, but the Pixel Watch has a 32-bit init/zygote. Also, the app-debug.apk @yujincheng08 linked installs fine on the watch, but I cannot select any files to be able to patch `boot_a` on the watch itself unfortunately (says "No application can handle this action.")

**Comment by shinyquagsire23** [comment]
[kernel log](https://gist.github.com/shinyquagsire23/b6c15153ccf555177fec0736f9fc7dea), with boot_a patched on-device thanks to some help from XDA. Same crash point, more or less.

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/9879709/app-debug.zip)
use this build to grab kernel log again

**Comment by shinyquagsire23** [comment]
That one boots all the way through!
[kmsg for good measure](https://gist.github.com/shinyquagsire23/ea961d32c8e70009f1769e5b7e02e0cf)
![FgIaRiLVIAUwExD](https://user-images.githubusercontent.com/1224096/198507522-a990ffea-5321-48e8-8fdb-f2d5381ec6f1.jpg)

**Comment by yujincheng08** [comment]
I did nothing but add more logs.

**Comment by shinyquagsire23** [comment]
...oh dear, lol. Well I guess I can at least debug a bit easier now, I might double check and see if the old builds still crash.

**Comment by shinyquagsire23** [comment]
I tried the initial on-watch-patched boot_a again, and it hangs on boot somehow. [kmsg](https://gist.github.com/shinyquagsire23/e505acbdf9b1e6912febc52312c22b5c).

It's possible I mixed up the boot images initially, so the crashes are:
- Phone-patched boot_a: Kernel panic
- First watch-patched boot_a: Boot hang
- Second watch-patched boot_a: Boots consistently

**Comment by Tiebe** [comment]
> I tried the initial on-watch-patched boot_a again, and it hangs on boot somehow. [kmsg](https://gist.github.com/shinyquagsire23/e505acbdf9b1e6912febc52312c22b5c).
> 
> It's possible I mixed up the boot images initially, so the crashes are:
> - Phone-patched boot_a: Kernel panic
> - First watch-patched boot_a: Boot hang
> - Second watch-patched boot_a: Boots consistently

Have you tried repatching with the normal apk?

**Comment by Tiebe** [comment]
I said fuck it and patched + flashed (not boot) my watch with the latest canary build. It boots fine and I have root! Build a468fd94

**Comment by shinyquagsire23** [comment]
Hmmm yeah I'm going to assume that `fastboot boot` has integrity issues with my current jig, there doesn't seem to be any other explanation. That, or it's a fastboot bug and something in the ramdisk is being corrupted by it. I guess if something comes up the issue can be reopened.
