### ISSUE TITLE
Could not get root access to multiple command

### ISSUE THREAD

**Issue by catzy007** [topjohnwu/Magisk#6359]
Hi, i currently want to create script involving running multiple commands `&& || |` via adb and su. But it seems like only the first command is running under root. Is this behavior to be expected?

This is running `"whoami && whoami"` under magisk su
![magisk adb su](https://catzy007.github.io/things/magisk-report/adb.png)

Similar command under ubuntu su
![ubuntu su](https://catzy007.github.io/things/magisk-report/ubuntu.png)

Thank you for your support.

[magisk.log](https://gist.github.com/catzy007/74efa293611a08b2ddf46272046aee9a)

Device: Samsung Galaxy J2 Prime 
Android version: 6.0.1
Magisk version name: any
Magisk version code: 25205

**Comment by yujincheng08** [comment]
expected. this is because the quote is for the bash from your PC. thus it's equal to:
```
adb shell "su -c whoami && whoami"
```
and there're two commands: `su` and `whoami` running as shell.

**Comment by catzy007** [comment]
It works, thank you
