### ISSUE TITLE
Change Magisk manager setting cause it breakdown

### ISSUE THREAD

**Issue by Jack-Myth** [topjohnwu/Magisk#638]
I meet a problem.
After I install magisk it can work fine with my phone. I can add modules normally. But once I change magisk setting like enable fingerprint or add any application in magisk hide, the magisk stop working. the magisk manager says the masigk is not installed. All item(Module,Magisk hide,etc) in side menu are disappeared. Root and magisk hide doesn't work,but the actived Modules still work. reboot doesn't fix it. I must uninstall and reinstall magisk.
I add the application to /magisk/.core/hidelist. It seems works and doesn't have any error.
but I don't know how to change the other setting without the magisk manager.

Here is the log(when I enable fingerprint):
09-23 12:38:12.249 1684-2521/? V/FingerprintService: startAuthentication(com.topjohnwu.magisk), -2072228419587972219, 0, 0, 0, true
    starting client AuthenticationClient(com.topjohnwu.magisk), initiatedByClient = true)
09-23 12:38:12.268 1684-2521/? W/FingerprintService: client com.topjohnwu.magisk is authenticating...
09-23 12:38:12.271 861-861/? D/SurfaceFlinger: duplicate layer name: changing com.topjohnwu.magisk/a.b to com.topjohnwu.magisk/a.b#1
09-23 12:38:17.154 1684-2521/? V/FingerprintService: onAuthenticated(owner=com.topjohnwu.magisk, id=-1219258248, gp=0)
09-23 12:38:17.162 1684-2521/? V/FingerprintService: Done with client: com.topjohnwu.magisk
09-23 12:38:24.093 11195-11195/? D/Magisk: resetprop: prop [persist.magisk.hide] does not exist
09-23 12:38:25.499 1684-2415/? D/RestartProcessManager: increase duration : 55685 for com.topjohnwu.magisk
09-23 12:38:25.500 1684-2822/? V/Prevent: leaving, current: com.topjohnwu.magisk
09-23 12:38:25.501 1684-2822/? D/Prevent: action: user leaving activity, package: com.topjohnwu.magisk, count: 1
09-23 12:38:26.508 1684-2410/? D/Prevent: action: destroy activity, package: com.topjohnwu.magisk, count: 0
09-23 12:38:26.508 1684-2410/? V/Prevent: destroy all activity: com.topjohnwu.magisk
09-23 12:38:26.514 1684-2410/? I/ActivityManager: Killing 11043:com.topjohnwu.magisk/u0a122 (adj 900): remove task
09-23 12:38:26.537 2576-2884/? D/SystemServicesProxy: Task is killed:com.topjohnwu.magisk, 0
09-23 12:38:26.538 1684-2410/? I/ActivityManager: Force stopping com.topjohnwu.magisk appid=10122 user=0: from pid 2576
09-23 12:38:26.538 1684-2410/? D/ActivityManager: Process com.topjohnwu.magisk has 0 services
09-23 12:38:26.548 1684-2410/? D/EmbryoManager: prepare com.topjohnwu.magisk user 0
09-23 12:38:26.555 1684-2552/? I/Prevent: action: PACKAGE_RESTARTED, package: com.topjohnwu.magisk
09-23 12:38:26.577 603-11062/? D/Magisk: su: return code: [0]

**Comment by topjohnwu** [comment]
Your log doesn't show anything related to the crash
