### ISSUE TITLE
Module download notification always hangs

### ISSUE THREAD

**Issue by RV7PR** [topjohnwu/Magisk#6385]
Device: Samsung Galaxy A53 (SM-A536B)
Android version: 13
Magisk version name: cf9957ce
Magisk version code: 25205

[magisk_log_2022-11-12T09.37.49.log](https://github.com/topjohnwu/Magisk/files/9994538/magisk_log_2022-11-12T09.37.49.log)

![Screenshot_20221112_093322_One UI Home](https://user-images.githubusercontent.com/17615589/201466218-435203f1-3181-43d4-86ad-eeb9e1288465.jpg)

**Comment by osm0sis** [comment]
I've noticed this recently as well.

**Comment by canyie** [comment]
Anyone tried the [latest CI build](https://github.com/topjohnwu/Magisk/actions/runs/3769199887)? I cannot reproduce it, maybe it was already fixed

**Comment by osm0sis** [comment]
I can reproduce it on latest CI

[magisk_log_2022-12-24T04.08.13.log](https://github.com/topjohnwu/Magisk/files/10298209/magisk_log_2022-12-24T04.08.13.log)

**Comment by canyie** [comment]
Ah, I'm able to reproduce the issue on Android 12. It seems to be working on Android 10.
And I found an interesting thing, for the first download, the notification works without any issue; after it succeeded and I click "Download" again, when it completes, the new notification does not cancel. I guess 87bec70d9f442493e129c4caf9aabcc78ced2833 is the bad commit

**Comment by canyie** [comment]
![image](https://user-images.githubusercontent.com/31466456/210138423-d7b1f063-e44c-406d-89ce-a47e6f25bdb0.png)
The change can fix the issue for me. But why???

**Comment by canyie** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/10327602/app-debug.zip)
Can anyone test if it solves the issue? It works for me.
And happy new year! This comment is posted at 23:59 2022/12/31 UTC+8

**Comment by osm0sis** [comment]
Looks like it works here! Nice job! Happy New Years! 🙂
