### ISSUE TITLE
Updating from APP >> Notification hangs forever.

### ISSUE THREAD

**Issue by Zibri** [topjohnwu/Magisk#6388]
Device: Redmi Note 10 pro (sweet)
Android version: 12.0 (MIUI V13.0.12)
Magisk version name: 337626c0-delta
Magisk version code: (25205)

From magisk home, clicking on APP >> UPDATE, first downloads the app with a progress bar, then a notification also with a progress bar stays there forever.

At the moment the update is triggered because version 1ddb52be-delta (25205) is available.

Nothing relevant in the log file.

**Comment by HuskyDG** [comment]
You are using my unofficial magisk build, please close this

**Comment by Zibri** [comment]
Yes, sorry.. I noticed after...
