### ISSUE TITLE
Bluetooth keeps stopping

### ISSUE THREAD

**Issue by lorenzoPrimi** [topjohnwu/Magisk#6389]
I have a problem with the Bluetooth that stops working as soon as I install Magisk from TWRP.

Steps to reproduce:
- Wipe the phone
- Restart the phone, add the google account, do basic configuration (both restoring from backup or setting brand new phone causes this issue)
- Flash Magisk from TWRP
- As soon as you restart the phone you get the message  "Bluetooth keeps stopping" Even after installing the Magisk app

Crash Log https://pastebin.com/h0zSZHw7
Magisk Log
[magisk_log_2022-11-13T19.10.51.log](https://github.com/topjohnwu/Magisk/files/9997939/magisk_log_2022-11-13T19.10.51.log)

I tried creating the folder `/data/user_de/0/com.xiaomi.bluetooth/databases/` chowning to bluetooth:bluetooth and chmod to 777 but didn't change the situation

Environments:
Device: Redmi Note 8
Android version: Android 10
Magisk version name: https://github.com/topjohnwu/Magisk/commit/cf9957ce4d0f369a7eb83143af8acb9942e516b2
Magisk version code: 25205

**Comment by yassineomarii** [comment]
Same here :/
Mi 8 - Evolution x - A13

**Comment by Joghurt** [comment]
For me it's alternating between stopping "Dolby Atmos" and Bluetooth.
Going back to Magisk 22.0 doesn't fix the problem.
OnePlus 7 Pro (A11)

**Comment by ArcyMods** [comment]
I had this issue on my Xiaomi Redmi 8 aswell. For some reason, when i reset my phone it started working again. Absolutely no idea as to whats going wrong.

**Comment by Klairm** [comment]
same problem here, Alcatel 3X 5048Y 2019

**Comment by yujincheng08** [comment]
Close because there is no response to my request for kmsg.

**Comment by Klairm** [comment]
> Close because there is no response to my request for kmsg.

I'm sorry, how can I provide the kmsg?

**Comment by lorenzoPrimi** [comment]
> For me it's alternating between stopping "Dolby Atmos" and Bluetooth. Going back to Magisk 22.0 doesn't fix the problem. OnePlus 7 Pro (A11)

I don't have that phone with me anymore. 
But it would be good if anybody can provide the kmesg, as this is a bug that many people have and needs to be fixed. Closing the issue doesn't solve the problem, just hides it.

**Comment by vvb2060** [comment]
We can't fix it, PR welcome.

**Comment by yassineomarii** [comment]
I wanted to capture kmsg. But since yesterday, bluetooth is working just fine on my phone (with magisk installed) for some reason :/

Mi 8 - Evolution x - A13

**Comment by lorenzoPrimi** [comment]
Apparently, it's not a bug in magisk, but in TWRP.
Here is the problem: https://www.reddit.com/r/PixelExperience/comments/hmhwxa/xiaomi_redmi_note_8_bluetooth_keeps_stoping/
And here is a backup link for the fix: https://dosya.co/065850v69htp/BT-fix-for-PE-20190618.zip.html

Didn't work for me, maybe you will have better luck

**Comment by Joghurt** [comment]
Not so sure about that: I had to reinstall my phone since uninstalling Magisk didn't help, but now I'm running on the latest TWRP with the "older" Magisk 23.0 just fine.

**Comment by lorenzoPrimi** [comment]
@Joghurt to me after formatting this problem re-appear the first time I reboot into TWRP, before even installing Magisk

**Comment by Joghurt** [comment]
@lorenzoPrimi Not sure if by formatting you mean the whole thing or just back to factory settings - I completely re-installed the whole firmware from scratch with the factory tool "MsmDownloadTool V4.0.exe".

**Comment by AlphaGeek1** [comment]
Here is what worked for me.. and what didn't work.  I am on a OnePlus 7 Pro (GM1915) with stock OOS 11 and using TWRP recovery.  Right now, I am on TWRP 3.6_11-0 and using Magisk 25.2.  

What doesn't work:  Wipe (factory reset), boot system and run setup.  Reboot recovery, flash Magisk, reboot system.  Bluetooth (and keychain, and Atmos...) is broken.  Constant message coming up about these stopping.

What worked:  boot recovery, wipe (factory reset), now flash Magisk <-- this is the difference because the Android one-time setup has not run yet, reboot system, go through setup.  I did not see Magisk app, so I installed Magisk 25.2 APK via File Manager.  Upon opening, it says additional setup needed and reboots device.  Once rebooted, device is rooted, bluetooth works.

**Comment by hyw0810** [comment]
> Here is what worked for me.. and what didn't work. I am on a OnePlus 7 Pro (GM1915) with stock OOS 11 and using TWRP recovery. Right now, I am on TWRP 3.6_11-0 and using Magisk 25.2.
> 
> What doesn't work: Wipe (factory reset), boot system and run setup. Reboot recovery, flash Magisk, reboot system. Bluetooth (and keychain, and Atmos...) is broken. Constant message coming up about these stopping.
> 
> What worked: boot recovery, wipe (factory reset), now flash Magisk <-- this is the difference because the Android one-time setup has not run yet, reboot system, go through setup. I did not see Magisk app, so I installed Magisk 25.2 APK via File Manager. Upon opening, it says additional setup needed and reboots device. Once rebooted, device is rooted, bluetooth works.

it works, thks！

**Comment by Avsynthe** [comment]
> Here is what worked for me.. and what didn't work. I am on a OnePlus 7 Pro (GM1915) with stock OOS 11 and using TWRP recovery. Right now, I am on TWRP 3.6_11-0 and using Magisk 25.2.
> 
> What doesn't work: Wipe (factory reset), boot system and run setup. Reboot recovery, flash Magisk, reboot system. Bluetooth (and keychain, and Atmos...) is broken. Constant message coming up about these stopping.
> 
> What worked: boot recovery, wipe (factory reset), now flash Magisk <-- this is the difference because the Android one-time setup has not run yet, reboot system, go through setup. I did not see Magisk app, so I installed Magisk 25.2 APK via File Manager. Upon opening, it says additional setup needed and reboots device. Once rebooted, device is rooted, bluetooth works.

So the reason why this works is because the TWRP bug takes hold the moment it is ever entered into and the only way to fix it is to factory reset.

Hence why flashing Magisk before leaving and coming back for it is what is working. Similarly, if you EVER re-enter TWRP again, the bug will reappear. I learned this the hard way by following your steps, got absolutely everything set up and working and needed to go back to TWRP for something unrelated. I entered, realised I hadn't removed my lock pattern so I rebooted. The bug returned. Very upsetting haha.

From what I can see, it's a TWRP 3.7_XX-X bug as rolling back to 3.6_XX-X allows me to enter and leave TWRP all I want.

**Comment by xiaofengjue** [comment]
hurt ,it's so hurt! (痛，太痛了！)  here's what I suffered : https://www.cnblogs.com/sillage/p/17317928.html   , it is so odd.

**Comment by Qleses** [comment]
**Please any working help to resolve to 100% this bug?**
I have Samsung Galaxy A22 5G, I don't have TWRP but I root and flash Magisk with Odin, I follow this steps:
[https://forum.xda-developers.com/t/guide-to-root-galaxy-a22-5g-unlock-bootloader-and-flash-official-firmware-noob-friendly.4404371/](url)

After installing Magisk, everytime when booting up the device (or rebooting), in less two minutes a message saids:
Bluetooth Agent Keeps Stopping
-App info
-Close app
Image:[https://i.ibb.co/8gf003n/1111111111111111111.jpg](url)

**I only solved it with wipe data/factory reset.** But after install Magisk the problem begins again.
Other solution like Seetings>Aplications, Show System apps>Bluetooth Agent, press Force stop aplication, and clear data and cache don't work for me.

**Comment by darkon12** [comment]
Redmi Note 8 here.
What worked:
Boot TWRP
Wipe everything, format data.
Install rom.
Reboot TWRP
Install magisk.zip
Setup OS
Install magisk.apk
Magisk working, blutooth working.

**Comment by Danstiv** [comment]
Hi all.
I'm planning to switch to another firmware at the beginning of 2024, and I want to try to find the reason for the Bluetooth not working.
Does anyone have any initial ideas on where to look and if anyone would be interested in this?

**Comment by Danstiv** [comment]
> and I want to try to find the reason for the Bluetooth not working.

https://github.com/TeamWin/android_bootable_recovery/issues/332#issuecomment-1818839953

> su -> restorecon -R -F /data

It works.

**Comment by darkon12** [comment]
F*** ME !!!
It worked !

**Comment by darkon12** [comment]
After some research I found out that the actual folder is /data/user_de/0
At least on my redmi note 8 and probably all xiaomi.
I guess that TWRP 3.7 messes with SELinux parameters in this folder and possibly others.
This is a thing that developers should know for future versions.

**Comment by norz3n** [comment]
@Danstiv

Bro, thank you so much for finding this solution!
