### ISSUE TITLE
Feature Request : Liveboot like implementation in the apk itself + A native terminal in magisk manager itself!

### ISSUE THREAD

**Issue by dg28gadhavi** [topjohnwu/Magisk#640]
I will like to request two features  
1st which i miss from Chainfire SuperSu = LIVEBOOT 
A toggle switch in magisk manager would be great with LIVEBOOT like feature
2nd A native Material terminal in the Magisk manager apk itself would be great!!

**Comment by makorus** [comment]
Would love to see both features!

**Comment by topjohnwu** [comment]
@dg28gadhavi I don't know how Liveboot works LOL, I'm not that advanced in writing root apps.
There are tons of terminal emulators out there, I don't want to clutter Magisk Manager even further.
