### ISSUE TITLE
Magisk app doesn't detect magisk

### ISSUE THREAD

**Issue by Otus9051** [topjohnwu/Magisk#6404]
Device:
Android version: 13 (TrebleDroid GSI)
Magisk version name: `a468fd94` (25205) (34) D
Magisk version code: `a468fd94` (25205) (34) D

Installed Magisk via TWRP. Booted back to Android. Bootup is fine, `su` is installed. 
![image](https://user-images.githubusercontent.com/58171861/203384941-cfc5bc72-5742-4a07-b584-87780130d053.png)

[magisk_log_2022-11-22T23.18.21.log](https://github.com/topjohnwu/Magisk/files/10069812/magisk_log_2022-11-22T23.18.21.log)

**Comment by pndwal** [comment]
You haven't indicated your device, but installation via custom recovery was designed for legacy ramdisk booting devices... On A13 you have either SAR or 2SI booting (older devices are upgraded to 2SI W/ A10)... Moreover there is no TWRP version compatible with A13 yet; 3.7.0 is for A12 so you'll likely have issues w/ A13...

Have you tried recommended in-app patching and fastboot flashing method?

**Comment by Otus9051** [comment]
> Are you sure you didn't flash an old Magisk.zip archive?
> 
> You haven't indicated your device, but installation via custom recovery was designed for legacy ramdisk booting devices... On A13 you have either SAR or 2SI booting (older devices are upgraded to 2SI w/ A10)... Moreover there is no TWRP version compatible with A13 yet; 3.7.0 is for A12 so you'll likely have issues w/ A13...
> 
> Have you tried recommended in-app patching and fastboot flashing method?

Nope. The latest debug.
It is a Samsung A7 2018, I have flashed Magisk via TWRP a lot of times, and it had worked, no idea what happened here.
I will try the in-app patching and see what happens.

**Comment by pndwal** [comment]
So launched as legacy ramdisk, now uses 2SI 'SAR'...

Nb. Samsung (System-as-root) caveats in official instructions (especially Important Notes) now apply to your device despite the statement "If your Samsung device is NOT launched with Android 9.0 or higher, you are reading the wrong section." (That was written before ramdisk boot-type devices were upgrading to 10+.)

**Comment by canyie** [comment]
```
---Magisk Logs---
17 me.phh.superuser cm-su subind suinit (-1)
```
?

**Comment by Otus9051** [comment]
> ```
> ---Magisk Logs---
> 17 me.phh.superuser cm-su subind suinit (-1)
> ```
> 
> ?

Checking. It still probably has phh-su.

**Comment by Otus9051** [comment]
Indeed a user fault. Had phh-su.

**Comment by HuskyDG** [comment]
phh's GSI comes with built-in SU
