### ISSUE TITLE
After updating to miui 13.0.10  I flashed the new patched image via fastboot, Now previous root apps and installed modules still working(+ lsposed), but magisk installed: N/A,  Before updating miui, magisk was hidden, and zygisk was enabled 

### ISSUE THREAD

**Issue by ahmedhosnypro** [topjohnwu/Magisk#6411]
Device: Redmi Note 10s
Android version: 12
Magisk version name: a468fd94
Magisk version code: 25205

**Comment by pndwal** [comment]
Find your previous hidden (stub) Magisk app and uninstall it (from system settings, apps if necessary)...

**Comment by ahmedhosnypro** [comment]
Thanks a lot
