### ISSUE TITLE
Accelerometer and gyroscope crashes after flashing Magisk.

### ISSUE THREAD

**Issue by s8n0** [topjohnwu/Magisk#6414]
Device: Oneplus5t
Android version: Android10
Magisk version name: a468fd94
Magisk version code: 25205

Auto Rotation stops working after installing Magisk. No Modules have been installed.

Uninstalling Magisk doesn't fix the problem. Once Magisk is installed it alters the sensors and stops them. Sometimes sensors work after rebooting. But then stops randomly. Sensors work fine only after clean flashing ROM.

[magisk_log_2022-11-13T19.10.51.log](https://github.com/topjohnwu/Magisk/files/10119126/magisk_log_2022-11-13T19.10.51.log)

[magisk_log_2022-11-30T08.49.29.log](https://github.com/topjohnwu/Magisk/files/10119144/magisk_log_2022-11-30T08.49.29.log)

**Comment by yujincheng08** [comment]
0 byte logs are really helpful.
