### ISSUE TITLE
Enabling Zygisk on Samsung Galaxy S10 causes Boot Loop

### ISSUE THREAD

**Issue by pjk2563** [topjohnwu/Magisk#6418]
I'm running Magisk on a custom build of the cruel kernel for android 11. So far everything works fine, but now that I need Zygisk I'm running into issues. Simply enabling Zygisk causes the phone to boot loop until I can disable Zygisk in the sql db over adb. I could use some more information.

What are the full requirements to get Zygisk running? I thought I saw somewhere that it needs a kernel patch or special selinux policies, but I can't find that on any of the official docs.

Device: Samsung Galaxy S10
Android version: 11
Magisk version name: 24.1, app is 24.3
Magisk version code: 25205

**Comment by pndwal** [comment]
Though that would happen without logs... How can Devs diagnose, especially custom kernel, without logs?...
