### ISSUE TITLE
After enabling zygisk, uninstall manager and restart the phone. Manager does not install automatically

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#6426]
Device:OP5911
Android version:12.0
Magisk version name:a468fd94:MAGISK:D (25205)
Magisk version code:25205
After enabling zygisk, uninstall manager and restart the phone. Manager does not install automatically

```
magisk --sqlite "REPLACE INTO settings VALUES ('zygisk', 1)"
```

**Comment by androiddisk** [comment]
[            goto not_found;](https://github.com/topjohnwu/Magisk/blob/master/native/src/core/package.cpp#L123)

**Comment by androiddisk** [comment]
why closed？
@yujincheng08

**Comment by yujincheng08** [comment]
@androiddisk because of no log.

**Comment by canyie** [comment]
#6547
