### ISSUE TITLE
Magisk app fails to detect magisk

### ISSUE THREAD

**Issue by daitj** [topjohnwu/Magisk#6427]
Device: Philips TV 75PML9506
Android version: 11.0 (Android TV)
Magisk version name: ed37ddd5(25205) 
Magisk version code: 25205
[logcat.log](https://github.com/topjohnwu/Magisk/files/10181490/logcat.log)
[magisk_log_2022-12-08T04.12.34.log](https://github.com/topjohnwu/Magisk/files/10181541/magisk_log_2022-12-08T04.12.34.log)
[magisk-boot-image-patch.log](https://github.com/topjohnwu/Magisk/files/10185584/magisk-boot-image-patch.log)

I patched the boot image and installed the latest debug version of magisk apk,  I can request su permission by using `/sbin/magisk su`  and I do get the confirmation dialog to grant or deny. But my magisk app says magisk is not installed.

I checked other similar issues here with app not detecting magisk, I have tried all of the options suggested but nothing helped.

There are these two lines in log, I wonder if it has something to do with SELinux permissions?
```
12-08 03:53:55.684  1857  1857 W magisk  : type=1400 audit(0.0:91): avc: denied { read } for name="bin" dev="dm-4" ino=25 scontext=u:r:magisk_client:s0 tcontext=u:object_r:vendor_file:s0 tclass=dir permissive=0
12-08 03:53:55.684  1857  1857 W magisk  : type=1400 audit(0.0:92): avc: denied { read } for name="/" dev="mmcblk0p72" ino=2 scontext=u:r:magisk_client:s0 tcontext=u:object_r:system_data_root_file:s0 tclass=dir permissive=0
``` 
I do not have any hidden, old version of magisk stub app, Could it be something with this ROM, as it is Android TV rom may be magisk needs some extra workaround to work on this device?

**Comment by canyie** [comment]
```
PATH=/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin

5985 5206 0:23 / /sbin rw,relatime master:12 - tmpfs tmpfs rw,seclabel,size=1395124k,nr_inodes=348781,mode=755
```
Android 11+ devices with the `/sbin` directory. Magisk injects itself into `/sbin` but the `PATH` variable does not include `/sbin` so Magisk cannot detect it. #4309
Is your device using stock ROM?

**Comment by daitj** [comment]
Yes it is a stock rom, there are no custom rom available for this device. Is there any workaround for this? I couldn't find anything in the issue you linked.

**Comment by canyie** [comment]
Try artifacts from https://github.com/canyie/Magisk/actions/runs/3662990735 and see if it works?

**Comment by fusebyte** [comment]
> Device: Philips TV 75PML9506 Android version: 11.0 (Android TV) Magisk version name: [ed37ddd](https://github.com/topjohnwu/Magisk/commit/ed37ddd57099226081d2641e139eb32d0e945a5f)(25205) Magisk version code: 25205 [logcat.log](https://github.com/topjohnwu/Magisk/files/10181490/logcat.log) [magisk_log_2022-12-08T04.12.34.log](https://github.com/topjohnwu/Magisk/files/10181541/magisk_log_2022-12-08T04.12.34.log) [magisk-boot-image-patch.log](https://github.com/topjohnwu/Magisk/files/10185584/magisk-boot-image-patch.log)
> 
> I patched the boot image and installed the latest debug version of magisk apk, I can request su permission by using `/sbin/magisk su` and I do get the confirmation dialog to grant or deny. But my magisk app says magisk is not installed.
> 
> I checked other similar issues here with app not detecting magisk, I have tried all of the options suggested but nothing helped.
> 
> There are these two lines in log, I wonder if it has something to do with SELinux permissions?
> 
> ```
> 12-08 03:53:55.684  1857  1857 W magisk  : type=1400 audit(0.0:91): avc: denied { read } for name="bin" dev="dm-4" ino=25 scontext=u:r:magisk_client:s0 tcontext=u:object_r:vendor_file:s0 tclass=dir permissive=0
> 12-08 03:53:55.684  1857  1857 W magisk  : type=1400 audit(0.0:92): avc: denied { read } for name="/" dev="mmcblk0p72" ino=2 scontext=u:r:magisk_client:s0 tcontext=u:object_r:system_data_root_file:s0 tclass=dir permissive=0
> ```
> 
> I do not have any hidden, old version of magisk stub app, Could it be something with this ROM, as it is Android TV rom may be magisk needs some extra workaround to work on this device?

Hi, i'm trying to root my tv too but even if i patched the boot.img with magisk and flashed it via fastboot i get no superUser permissions. I would be interested to know how you managed to root a 2021 philips tv.
Mine is a 65oled705/12 from 2020 and its firmware is TPM191E

**Comment by daitj** [comment]
@fusebyte  My process was like this: 

1. Get boot.img for your current firmware version and patch it using magisk app
2. Enable debugging mode 
3. Use USB-A to USB-A cable in USB 1.0 port and get adb working
4. Reboot to fastboot from adb
5. Unlock bootloader, it will WIPE the device and boots the device
6. Repeat step 2-4
7. Flash patched boot.img, installed latest magisk. 
8. Magisk needs to perform some extra installation and reboots the device. 
9. Rooted.

You can get `boot.img` for your version from an update package, use toengel's archive to get the update package. The update package is encrypted, you will need to use openssl and passfile (cannot share it here, but if you look around you will find it) to decrypt it.

Then you will get decrypted zip which then can be extracted and you can use `payload_dumper` tool to get `boot.img` from `payload.bin`

**Comment by fusebyte** [comment]
> @fusebyte My process was like this:
> 
> 1. Get boot.img for your current firmware version and patch it using magisk app
> 2. Enable debugging mode
> 3. Use USB-A to USB-A cable in USB 1.0 port and get adb working
> 4. Reboot to fastboot from adb
> 5. Unlock bootloader, it will WIPE the device and boots the device
> 6. Repeat step 2-4
> 7. Flash patched boot.img, installed latest magisk.
> 8. Magisk needs to perform some extra installation and reboots the device.
> 9. Rooted.
> 
> You can get `boot.img` for your version from an update package, use toengel's archive to get the update package. The update package is encrypted, you will need to use openssl and passfile (cannot share it here, but if you look around you will find it) to decrypt it.
> 
> Then you will get decrypted zip which then can be extracted and you can use `payload_dumper` tool to get `boot.img` from `payload.bin`

Thank you a lot for your reply, anyway that Is exactly what i did but i get no root permission, "su command not found".
I get no errors during the procedure, i don't know what else to try

**Comment by daitj** [comment]
@fusebyte 
Have you tried checking logs? Did you get same error like my initial post or something else?

**Comment by fusebyte** [comment]
> @fusebyte Have you tried checking logs? Did you get same error like my initial post or something else?

If i type su i get command not found

**Comment by daitj** [comment]
I mean `adb logcat | grep magisk`

**Comment by fusebyte** [comment]
> I mean `adb logcat | grep magisk`
I get just this warning:
01-14 14:50:31.086  2361  2742 W installd: Ignoring /data/data/com.topjohnwu.magisk/lib with unexpected GID 0 instead of 10112

Do i need to check patching logs? where did you find them? thank you

**Comment by daitj** [comment]
You should also check logs within the Magisk app, there is a whole tab for logs there.

**Comment by classiphil** [comment]
I am running in the same problem:
Ignoring /data/data/com.topjohnwu.magisk/lib with unexpected GID 0 instead of 10115

**Comment by classiphil** [comment]
[log.txt](https://github.com/user-attachments/files/16019117/log.txt)

That is the logcat grep magisk

**Comment by classiphil** [comment]
Verison 81658d45 (27002) gives me ! Unable to patch ramdisk after - Pre-init storage partition: userdata

**Comment by classiphil** [comment]
Does it matter, that Magisk announces the platform "armeabi-v7a" but my uname -a shows "armv8l"?

**Comment by fusebyte** [comment]
@classiphil Did you managed to root tpm191e?

**Comment by classiphil** [comment]
Nope :(
