### ISSUE TITLE
Sony Xperia TX hayabusa can't install newer version Magisk with BootBridge

### ISSUE THREAD

**Issue by w7513981** [topjohnwu/Magisk#643]
Hello, topjohnwu
I can't install Magisk v17.1 and v16.7 with BootBridge, but v16.0 can be installed

我沒辦法用BootBridge安裝Magisk近期的兩個版本, 但舊版的v16可以正常安裝
安裝v17.1和v16.7時安裝程序會提示在mmcblk0p2, 安裝v16.0時變成mmcblk0p4

這裡是記錄檔
https://pastebin.com/iEJKVb2u

Thanks,

**Comment by w7513981** [comment]
[recovery.log](https://github.com/topjohnwu/Magisk/files/2408968/recovery.log)

Backup recovery.log here

**Comment by krasCGQ** [comment]
#624

**Comment by topjohnwu** [comment]
Duplicate #624
