### ISSUE TITLE
Folder mount

### ISSUE THREAD

**Issue by ahmadprayoxxsy** [topjohnwu/Magisk#644]
Magisk does not support applications (folder mount)
os android v.6.0.1
![screenshot_20180925-070926](https://user-images.githubusercontent.com/37769813/45986008-840e8800-c058-11e8-9d8b-f3f5747af48e.png)

**Comment by Didgeridoohan** [comment]
That is entirely up to the app developer and is not something that Magisk should have to fix. Contact the developer and ask them to update their app.

And close the issue please.
