### ISSUE TITLE
Magisk doesn't flash if `data` is not decrypted and mounted

### ISSUE THREAD

**Issue by akash07k** [topjohnwu/Magisk#6448]
I'm using Magisk on my Xiaomi Poco F4 (munch) and facing an issue which I think is the bug of Magisk, and it doesn't seem right.
So, if I boot to recovery and try to flash Magisk, it fails, but if I decrypt and mount the data, then it flashes correctly.
However, what I think is it should not be the case, because even though the data is not decrypted and mounted, Magisk needs to only patch the bootimage and accessing the data partition shouldn't be needed most of the times.
So, any way to workaround this issue and expected fix?
Actually since it is a Virtual A/B device, Magisk doesn't retain after every rom update and we are required to flash it everytime from the scratch.
Patching the bootimage everytime is not much practical solution.

Device: Xiaomi Poco F4 (munch)
Android version: 13.0
Magisk version name: 25.2
Magisk version code: 25205

**Comment by AngelofVerdant** [comment]
Yea, that sounds like a real hassle mate. Will be picking up my Redmi Note 10 Pro tomorrow to test this. I'm not sure how Android 13 partitions work, could be an Android 13 thing you never know

**Comment by cyberboh** [comment]
@akash07k This not about magisk failure, but its about your recovery to be used to flash magisk.
1st- You need recovery that support decryption
2nd- After boot to recovery, insert your PIN/Password/Pattern
3rd - Flash magisk and profit!

Or

Remove any PIN/Password/Pattern before entering recovery , it shouldn't ask for decryption and then flash magisk, profit!

**Comment by yujincheng08** [comment]
https://github.com/topjohnwu/Magisk/pull/3037#issuecomment-667522249

**Comment by akash07k** [comment]
You didn't got my point.
Since magisk needs to patch the bootimage only, the data decription should not be required at all.
This is not a recovery issue.

> @akash07k This not about magisk failure, but its about your recovery to be used to flash magisk. 1st- You need recovery that support decryption 2nd- After boot to recovery, insert your PIN/Password/Pattern 3rd - Flash magisk and profit!
> 
> Or
> 
> Remove any PIN/Password/Pattern before entering recovery , it shouldn't ask for decryption and then flash magisk, profit!

**Comment by akash07k** [comment]
Thanks buddy, please check and let me know your findings.
Thinking to give Lygisk a try now since this issue is straight away closed. :(
> Yea, that sounds like a real hassle mate. Will be picking up my Redmi Note 10 Pro tomorrow to test this. I'm not sure how Android 13 partitions work, could be an Android 13 thing you never know
