### ISSUE TITLE
Google backup account greyed out in backup & reset settings on 5 similar devices, core only mode fixes it. SOLVED This was caused by the Sysconfig Patcher Module

### ISSUE THREAD

**Issue by martyfender** [topjohnwu/Magisk#645]
I have 5 Nextbook Ares 8A's with Android 6.0.1 x86. On some of them I am using the latest Canary build and on others, unofficial builds. On all of them, for some time now, in settings, backup, the backup account is greyed out. I removed all modules, removed the Google account and readded it and that did not solve it. What did solve it was to enable core only mode and reboot. I am attaching a magisk.bak log before core only mode and a magisk. Log with core only mode enabled.
I did the uninstall of all modules on one of my other devices, not the one here I posted logs for. More device info is in my signature, as always.
Does anyone have any idea why this is happening?
This was also reported by another user in the Sysconfig Patcher Module forum.

Logs posted here:
https://forum.xda-developers.com/showpost.php?p=77702430&postcount=105

@topjohnwu I solved this. the problem was caused by the Sysconfig Patcher Module on all 5 devices.

**Comment by topjohnwu** [comment]
@martyfender since this is an issue of a module not Magisk, I cannot fix anything.

**Comment by neekless** [comment]
> Thanks, @topjohnwu , I realize that you can't do anything about it, but I do not know how to close issues I have posted myself, or I would have. For future reference, how do I do that?


![gitclose](https://user-images.githubusercontent.com/22426822/47550639-66239400-d932-11e8-9487-d12c5932e8ed.PNG)
