### ISSUE TITLE
Error building binary from source

### ISSUE THREAD

**Issue by NBA613** [topjohnwu/Magisk#6451]
I'm trying to build Magisk 25.2 from source on Windows...
I followed exact instructions here: https://github.com/topjohnwu/Magisk#building-and-development
After running "build.py binary" I get the following error:

* Building binaries: magisk magiskinit magiskboot magiskpolicy busybox

error: linker `link.exe` not found
  |
  = note: program not found

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017, VS 2019 or VS 2022 was installed with the Visual C++ option

error: could not compile `quote` due to previous error
error: could not compile `proc-macro2` due to previous error
error: could not compile `winapi` due to previous error
error: failed to compile `cxxbridge-cmd v1.0.72 (C:\Users\sband\Downloads\Magisk\native\src\external\cxx-rs\gen\cmd)`, intermediate artifacts can be found at `C:\Users\sband\Downloads\Magisk\native\src\external\cxx-rs\target`

cxxbridge-cmd installation failed!

***

Is MSVC actually required without being mentioned in the build guide? If yes, can the guide be updated to reflect that? If not, what is the issue?
Device: Any
Android version: Any
Magisk version name: 25.2
Magisk version code: 25205

**Comment by yujincheng08** [comment]
> If yes, can the guide be updated to reflect that

We are working to remove such requirement. Or, though unlikely, no more supports for building on windows.

**Comment by QuantumNone** [comment]
I have the same issue...
cxxbridge-cmd installation failed!

**Comment by QuantumNone** [comment]
Also why cannot magisk already build binaries and let download them instead of letting the user do it?

**Comment by vnfsjnaa** [comment]
What I found when trying to compile is the whole folder of files under ...native/external and some other files such as flags.h, cxx.h/cxx.hpp, plus possibly more...
So there's no way to compile for others prove this program is 100% transparent.
