### ISSUE TITLE
Can't root Moto X40

### ISSUE THREAD

**Issue by Goooler** [topjohnwu/Magisk#6457]
Device:
Android version: Android 13 (T1TR33.4-15-6)
Magisk version name: v25.2
Magisk version code: 25205

[magisk_log_2022-12-23T20.20.16.log](https://github.com/topjohnwu/Magisk/files/10294991/magisk_log_2022-12-23T20.20.16.log)
[boot.img](https://drive.google.com/file/d/1_NgyPBzeyLUR-csegF-Y6c8BuuJ_0Av1/view?usp=share_link)
[boot_patched.img](https://drive.google.com/file/d/1m0SP1WykjsZLsLP3PCSa6Sq0Z-sAsfez/view?usp=share_link)

**Comment by yujincheng08** [comment]
need [bugreport](https://developer.android.com/studio/debug/bug-report)

**Comment by Goooler** [comment]
[bugreport-rtwo_cn-T1TR33.4-15-6-2022-12-23-22-15-33.zip](https://github.com/topjohnwu/Magisk/files/10295583/bugreport-rtwo_cn-T1TR33.4-15-6-2022-12-23-22-15-33.zip)

**Comment by yujincheng08** [comment]
too late. plz reboot and then capture bugreport ASAP.

**Comment by Goooler** [comment]
Actually I did it, anyway again

[bugreport-rtwo_cn-T1TR33.4-15-6-2022-12-23-22-38-41.zip](https://github.com/topjohnwu/Magisk/files/10295699/bugreport-rtwo_cn-T1TR33.4-15-6-2022-12-23-22-38-41.zip)

**Comment by yujincheng08** [comment]
hmm, so sad still too late. cannot see any log from magiskinit.

**Comment by Goooler** [comment]
Are these steps below right?

1. `fastboot boot magisk_patched-25200_ioyu2.img`
2. `adb bugreport ~/Downloads`

**Comment by yujincheng08** [comment]
yes

**Comment by yujincheng08** [comment]
> ------ KERNEL LOG (dmesg) ------
> <6>[    6.754633][  T858] BM_ULOG: bm_ulog_print_buffer: 0x000000001D4F76B9: Warn: battman_pmio_spmi_readmultibytes: battman_pmio_spmi_readmultibytes: DalSpmi_ReadLong Failed BusID = 0, SlaveId = c, Register = 100, status = 5
> <6>[    6.754638][  T858] BM_ULOG: bm_ulog_print_buffer: 0x000000001D4F785D: Warn: battman_pmio_spmi_readmultibytes: battman_pmio_spmi_readmultibytes: DalSpmi_ReadLong Failed BusID = 0, SlaveId = d, Register = 100, status = 5
> <6>[    6.754644][  T858] BM_ULOG: bm_ulog_print_buffer: 0x000000001D4FAC54: Info: BattMngrTech_ChgTableMgmt_GetDevCfg: BattMngrTech_ChgTableMgmt_GetDevCfg:: debug_batt_id_min = 2000, debug_batt_id_max = 14000, normal_batt_id_min = 15000, normal_batt_id_max = 140000, smart_batt_id_min = 240000, smart_batt_id_max = 450000, numOfChargingTable = 2, authentication feature enable = 0


The first line of dmesg is not started with 0

**Comment by yujincheng08** [comment]
maybe `adb wait-for-device bugreport ~/Downloads` before the adb connected

**Comment by Goooler** [comment]
`adb wait-for-device bugreport ~/Downloads`:

[bugreport-rtwo_cn-T1TR33.4-15-6-2022-12-23-22-48-42.zip](https://github.com/topjohnwu/Magisk/files/10295748/bugreport-rtwo_cn-T1TR33.4-15-6-2022-12-23-22-48-42.zip)

**Comment by yujincheng08** [comment]
no luck. still too late...

**Comment by Goooler** [comment]
😭

**Comment by yujincheng08** [comment]
i think you should complie your own kernel to increase CONFIG_LOG_BUF_SHIFT to a large number

**Comment by yujincheng08** [comment]
https://github.com/MotorolaMobilityLLC

**Comment by Goooler** [comment]
I'll try, thanks for your help!

**Comment by yujincheng08** [comment]
Oh your device is using gki. maybe you can build a gki.

**Comment by yujincheng08** [comment]
And, specs launched initially with android 13 should patch init_boot. Are you patching init_boot?

**Comment by Goooler** [comment]
You meant I should patch init_boot.img instead of boot.img on Android 13?

**Comment by yujincheng08** [comment]
> You meant I should patch init_boot.img instead of boot.img on Android 13?

yes.

**Comment by Goooler** [comment]
My bad, it works after patching the `init_boot.img`. Thanks again!

**Comment by Goooler** [comment]
Just a little suggestion, if we can amend a field in patched file name to easily differentiate it was patched from `boot.img` or `init_boot.img`?
