### ISSUE TITLE
vendor_boot v4 vendor_ramdisk_table, multi-ramdisk and bootconfig support

### ISSUE THREAD

**Issue by osm0sis** [topjohnwu/Magisk#6460]
Device: All vendor_boot_img_hdr_v4+
Android version: All Android 12+ (from launch)
Magisk version name: a468fd94
Magisk version code: 25205

For complete vendor_boot v4 support, proper multi-ramdisk table/unpack/repack and bootconfig support is needed.

bootconfig is basically another cmdline with no size limit, and vendor_ramdisk_table needs to be parsed and updated for any potential splitting and edits of the vendor_boot v4 monolithic multi-ramdisk.

**Comment by yujincheng08** [comment]
in fact, @topjohnwu has privately stated that there wont be support for vendor boot repack.

**Comment by osm0sis** [comment]
That's disappointing, but the request should still stand.

**Comment by yujincheng08** [comment]
> custom recovery installation and custom kernel vendor_boot dlkm changes

Looks like there's nothing about Magisk. @topjohnwu, @vvb2060, and I won't support it. Let's assign it to you.

**Comment by osm0sis** [comment]
Stop being passive aggressive. It remains open as a feature request for magiskboot for some other dev in the future who has the time and ability, as I clearly already said.

**Comment by nilz3000** [comment]
PR for this issue is out. Currently it doesn't support adding or removing ramdisk fragments.

**Comment by behomonth** [comment]
Against the imposition of the manufacturers, please you knowledgeable people help the whole world for V4. 

@osm0sis @yujincheng08 @vvb2060 @nilz3000 @phhusson @topjohnwu

**Comment by Yaf532** [comment]
- [ ]

**Comment by Yaf532** [comment]
- [ ]
