### ISSUE TITLE
Leak fd from magiskinit on legacy SAR devices

### ISSUE THREAD

**Issue by selfmusing** [topjohnwu/Magisk#6463]
1. https://github.com/topjohnwu/Magisk/pull/6445 https://github.com/topjohnwu/Magisk/actions/runs/3770178605 (Getting Endless Bootanimation after flashing this build) 

2. https://github.com/topjohnwu/Magisk/pull/6444 is also causing endless boot animation

Attaching Logcat below :
[logcat.txt](https://github.com/topjohnwu/Magisk/files/10298263/logcat.txt)

Device: Redmi Note 7 Pro
Android version: Android 13 December Security Patch
Magisk version name: 3c0a81d  
Magisk version code: 25205

**Comment by yujincheng08** [comment]
anylog about only using #6444?

**Comment by selfmusing** [comment]
OKAY! Here is your bugreport for #6444 : 

[bugreport-derp_violet-TQ1A.221205.011-2022-12-24-16-56-03.zip](https://github.com/topjohnwu/Magisk/files/10298453/bugreport-derp_violet-TQ1A.221205.011-2022-12-24-16-56-03.zip)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/10298617/app-debug.zip)
Try this build (.apk renamed to .zip)?

**Comment by baraa272** [comment]
Booted with no problems but whole system is stuttery and laggy 
Needs some fixes

**Comment by yujincheng08** [comment]
Could you try to disable all modules and see if it boots?

**Comment by selfmusing** [comment]
OK i will try it & report soon.

**Comment by selfmusing** [comment]
> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/10298622/app-debug.zip)
> 
> Try this build (.apk renamed to .zip)?

getting the same endless bootloop

[logcat.txt](https://github.com/topjohnwu/Magisk/files/10298895/logcat.txt)

Now i check if device boots normally after disabling modules.

**Comment by selfmusing** [comment]
> Could you try to disable all modules and see if it boots?

Device still did not boot , even after disabling all modules.

Here is another BUG-REPORT :
[bugreport-derp_violet-TQ1A.221205.011-2022-12-24-22-11-21.zip](https://github.com/topjohnwu/Magisk/files/10298902/bugreport-derp_violet-TQ1A.221205.011-2022-12-24-22-11-21.zip)

**Comment by yujincheng08** [comment]
Strange. Cannot see any log from magiskinit. That pr is refactoring magiskinit so I need log from magiskinit.

**Comment by yujincheng08** [comment]
plz check `ls -lah /proc/1/fd` during bootloop

**Comment by yujincheng08** [comment]
Oh never mind. Found the problem.
