### ISSUE TITLE
17.1 Bootloops on Pixel XL

### ISSUE THREAD

**Issue by zosxavius** [topjohnwu/Magisk#647]
It doesn't matter if TWRP is installed or not. It bootloops back to recovery. I got around this before by only installing Magisk 16.7 beta and not TWRP at the same time. Now I get a bootloop regardless.  I tried both installing via recovery as well as ADB sideload. Same result. The uninstaller does at least fix the problem.  This is running the latest Pie update btw. I tried from a fresh factory image install and had zero luck. Something's wrong here.

**Comment by wljohnson05** [comment]
I'm running 16.6 on a Nexus 6 running android 8.1.0, and I have the same issue. I haven't tried 16.7, but I tried 17.1 when it came out and 17.2, but once I flash them (either by direct install or going to recovery and flashing it), it just goes to the normal booting screen, then eventually times out I guess and reboots back into recovery. For me, flashing the 16.6 version back allows me to boot the phone again.

**Comment by topjohnwu** [comment]
I'm using Pixel XL as daily driver, you are doing something wrong

**Comment by zosxavius** [comment]
What could I possibly be doing wrong? 

Boot TWRP from fastboot----->Flash Magisk

Those are the steps I take on a fresh factory image. Please tell me how I am doing something wrong. :/

**Comment by zosxavius** [comment]
> I'm using Pixel XL as daily driver, you are doing something wrong

So you are saying that it works with TWRP? I cannot get it to work with TWRP. Or by itself. And yes, I have flashed this every way I possibly can try. Via twrp....via adb sideload.... There are only two steps here. So what am I screwing up? I tried several times and got the same bootloop. I flashed a factory image every time too just to rule out that somehow something wasn't flashing right. I also tried all the instructions i could find on the web. They all pretty much give the same steps. Seriously I tried for like 2 days to do this and never could get it it to work. 16.7 worked when I tried it on the August security update image. I wasn't getting an OTA for the september update and I flashed again and here we are.

**Comment by wljohnson05** [comment]
I still have the same issue as well on a different phone.

**Comment by zosxavius** [comment]
https://www.reddit.com/r/Magisk/comments/95lsd4/help_anyone_getting_a_bootloop_with_magisk_and/

We are hardly alone. What is going on here? Dismissing our problem as user error is frustrating.

**Comment by zosxavius** [comment]
https://www.reddit.com/r/Magisk/comments/9ixaec/help_phone_wont_boot_after_magisk_171/

**Comment by zosxavius** [comment]
User error huh?

**Comment by zosxavius** [comment]
Also.....

https://forum.xda-developers.com/apps/magisk/bootloop-magisk-update-t3836904/page13

**Comment by zosxavius** [comment]
OK.

I deleted my accounts and removed my pin. I then flashed over the latest factory image. 100% clean. I booted into TWRP without installing it and then installed Magisk 17.1.

And of course it bootlooped. There is literally nothing else I can try at this point. It doesn't work despite your insistence that it does.

**Comment by zosxavius** [comment]
OK 17.1 works fine.

Just don't install TWRP and only use it to flash. You can sideload Magisk. Also make sure that your google account and pin are cleared out. Then do a factory ROM install, then boot TWRP, then install magisk. Done. Just don't install TWRP when it asks you.

**Comment by zosxavius** [comment]
Sorry for the frustration. Never fun to just be told "you are doing it wrong" when you are following guides online that have flawed information.

**Comment by wljohnson05** [comment]
So every Android update requires the clear out process? Just wondering what changed so much to break the whole process...

**Comment by zosxavius** [comment]
> So every Android update requires the clear out process? Just wondering what changed so much to break the whole process...

Its possible that it was indeed user error. Once you are rooted, updates shouldn't break root anyways.

This is what I did:

1. Remove google user and pin
2. Install Magisk ----> Bootloop
3. Flash factory rom
4. Still bootlooping....OK...Factory Reset
5. OK it Boots.
6. Magisk Uninstaller just to clear out anything lingering
7. Boot TWRP via fastboot
8. Sideload magisk.17.1.zip
9. Reboot but DO NOT install TWRP in system when it asks
(I honestly think that was where I was going wrong here because I always swipe it out of habit when it prompts me. I've been flashing for a decade now....)
10. You should have a fresh clean factory install that is now rooted.

Try those steps!
