### ISSUE TITLE
Override DNS cannot set DNS with 17.x on Oreo

### ISSUE THREAD

**Issue by neverfox** [topjohnwu/Magisk#649]
With Magisk 17.x on Oreo (both 17.1, 17.2 beta, and 17.3 canary tried), the [Override DNS](https://play.google.com/store/apps/details?id=net.mx17.overridedns&hl=en_US) app cannot set the DNS as root (granted forever successfully). This app is usually the recommended one, as far as I know, for 3rd-party control of the DNS settings as root when using something like the DNSCrypt module. Now when it tries to set the DNS, you get a notification about an error (patchSELinuxSeTools failed) and the DNS remains unchanged. I've seen this mentioned in a few forums now but with no response. DNSCrypt with its own iptables works fine but I generally avoid this method as it often results in no internet connection on some public networks; with Override DNS I can set a fallback from 127.0.0.1 like Cloudflare. For the time being I've turned off DNSCrypt and Override DNS and am using the Cloudflare module successfully but would like to see if this can be resolved. I'm not absolutely certain this is a Magisk issue (and only suspect because of the aforementioned reports) as I also switched to Oreo before trying Override DNS again (which I had been using on Nougat with lower versions of Magisk).

Running Magisk 17.3-cfe32f1a on Oreo 8.0.0 May 1 patch level on an LG V30. Magisk Manager 6.0.0 (147).

**Comment by lev2k** [comment]
I can confirm this.
Override DNS works fine with 16.x but not 17.x (patchSELinuxSeTools failed)

**Comment by forkoz** [comment]
It's not working on nougat either. same message.

**Comment by knight-rider** [comment]
Anybody knows how to reverse to 16.x? Simply installing older ZIP doesn't seem to solve the problem

**Comment by topjohnwu** [comment]
Closed as this is not an Magisk issue. The developer needs to update the app.
Use @neverfox's solution now
