### ISSUE TITLE
[LineageOS 19.1] Inability to install Magisk's APK.

### ISSUE THREAD

**Issue by Terrorgor** [topjohnwu/Magisk#6498]
Device: SM-A205FN (Samsung Galaxy A20)
Android version: 12
Magisk version name: debug
Magisk version code: 25206

Explaination: I'm getting error parsing the package in android, adb says this:
![image](https://user-images.githubusercontent.com/117653363/210179912-136a5f9c-cd4d-4917-ae5b-d747dd073b28.png)

**Comment by yujincheng08** [comment]
Where you get the apk?

**Comment by vvb2060** [comment]
cannot reproduce
