### ISSUE TITLE
ADB command promp

### ISSUE THREAD

**Issue by devsqdi** [topjohnwu/Magisk#6507]
Command 'adb shell su' dos not complete.

Example 'adb shell' vs 'adb shell su' and than ls command:
xxxx@xxxx-lap ~/sq/xxxx[mxxxx] $  adb shell
b0q:/ $ su
b0q:/ # ls
acct                cache    data_mirror     etc                metadata

xxxx@xxxx-lap ~/sq/xxxx[mxxxx] $ adb shell su
ls
acct
apex
audit_filter_table
bin
...

All testet on latest Debug build.

Device: Samsung SM-S908U
Android version: 13
Magisk version name: 25206
Magisk version code: 25206

**Comment by yujincheng08** [comment]
plz refine ur english b4 submission

**Comment by canyie** [comment]
This should be expected. `adb shell sh` behaves the same.
