### ISSUE TITLE
Encryption not working on LineageOS 8.1 with Magisk 17.2

### ISSUE THREAD

**Issue by sdembis** [topjohnwu/Magisk#651]
After encrypting LineageOS 8.1, phone bootloops continually on Android is starting.  Happens with encryption being done both before and after installing Magisk 17.2 on clean rom installs with latest TWRP preview images on LG G4's.
Any help, suggestions, solves would be much appreciated.
Regards,
S.

**Comment by mbethke** [comment]
@sdembis https://forum.xda-developers.com/apps/magisk/dev-magisk-canary-channel-bleeding-edge-t3839337 I suppose

**Comment by sdembis** [comment]
@mbethke  - Than you - will check it out.
