### ISSUE TITLE
Magisk Manager shows green screen on second open

### ISSUE THREAD

**Issue by huangsijun17** [topjohnwu/Magisk#6515]
Device: Red Magisk 8 Pro+
Android version: 13
Magisk version name: Canary
Magisk version code: 25206

On Red Magisk 8 Pro+, Magisk Manager shows green screen on second open, and can be restarted after deleting the software data.
![498FF1236C7BA40F48280C06B57BA0CD](https://user-images.githubusercontent.com/31504595/211705741-5ad1891d-6dec-4849-a239-01492ba92813.jpg)
Device owner: @danyi

**Comment by yujincheng08** [comment]
where's the log?

**Comment by huangsijun17** [comment]
> where's the log?

Sorry, the equipment is not mine, he is still on a business trip. Screenshots will be added to me later. Next time he has a computer let him print the log.

**Comment by huangsijun17** [comment]
> where's the log?

After entering the command `adb logcat | findstr com.topjohnwu.magisk` and opening the Magisk Manager, no logs can be printed.

**Comment by yujincheng08** [comment]
@huangsijun17 then post ALL adb logcat

**Comment by yujincheng08** [comment]
Also, when stuck, run kill -s SIGQUIT $(pidof com.topjohnwu.magisk) as root and upload /data/anr/ folder.

**Comment by huangsijun17** [comment]
> Also, when stuck, run `kill -s SIGQUIT $(pidof com.topjohnwu.magisk)` as root and upload `/data/anr/` folder.

[log.tar.gz](https://github.com/topjohnwu/Magisk/files/10402541/log.tar.gz)

**Comment by yujincheng08** [comment]
Still waiting for the full adb logcat. I suspect this is the same as #5880, but no log to prove it.

Further, the posted ANR shows you are not using a debug version. You should post a log with the debug version.

I will close it as stale if there's no further response.

**Comment by huangsijun17** [comment]
> Still waiting for the full adb logcat. I suspect this is the same as #5880, but no log to prove it.
> 
> Further, the posted ANR shows you are not using a debug version. You should post a log with the debug version.
> 
> I will close it as stale if there's no further response.

I confirm that I had packaged and uploaded the entire _anr_ directory at the end of last year.

**Comment by yujincheng08** [comment]
But I meant full adb logcat. Full adb logcat and ANR are diffrent.

**Comment by yujincheng08** [comment]
Feel free to open a new issue with both the full adb logcat and the ANR on a DEBUG version of Magisk.
