### ISSUE TITLE
Magisk 17.1 - Updates Delay - Bug Or Server Issue?

### ISSUE THREAD

**Issue by 0pLuS0** [topjohnwu/Magisk#652]
Hello,

Using a OnePlus 5T on Oxygen OS 5.1.5 Oreo 8.1.0, I noticed for the past 2 days, when I install Magisk and it popups a window telling me there's an update and I click install, nothing happens.

Then I also have an overhead notification saying there's an update, so I then tap on it, and it's taking almost a minute before the download starts.

I've never had problems with updates, but this is also a new device, so I'm not sure if there's an issue going on here with a bug in Magisk in this regards, or some server issues on your end?

I'm attaching a logcat, I hope it will help.

[logcat.txt](https://github.com/topjohnwu/Magisk/files/2421987/logcat.txt)

**Comment by topjohnwu** [comment]
It should be an issue in your device's DownloadManager. I'll be moving to using my own implementation soon.

**Comment by 0pLuS0** [comment]
Have you heard of others having this issue in a OnePlus 5T? I've used Magisk on two other devices without issue, Xiaomi Mi A1, and Essential...

Hmm
