### ISSUE TITLE
Unsupported/Unknown image format

### ISSUE THREAD

**Issue by music-cat-bread** [topjohnwu/Magisk#6550]
### Issue
Unable to patch boot image nor from Magisk App or from TWRP recovery.
Magisk is unable to unpack boot image for unknown reason.

### Details, logs and boot image:
Ramdisk is present.
No seperate vbmeta partition.
Using latest canary debug apk.
Boot loader is unlocked.
ROM is stock never flashed.
BOOT is stock never flashed.
Only flashed partition was recovery which currently has TWRP on it.

[boot.img](https://vvyy.xyz/files/bin/boot.img) (exported using SIN extractor in Flashtool, SIN file has been downloaded using XperiFirm)
[part_boot.img](https://vvyy.xyz/files/bin/part_boot.img) (boot image extracted using dd from TWRP terminal)
There is no difference present between these two files except that part_boot.img has additional zeros at the end because dd was used. Both produce the same result when used in Magisk app or Mgisk.zip from TWRP.

[magisk_log_2023-01-20T22.54.53.log](https://gist.github.com/music-cat-bread/f1d864920d6d84213ba33e5243a79e28)
[magisk_install_log_2023-01-20T22.54.41.log](https://gist.github.com/music-cat-bread/233a054a84b5429bc18c2b81a207b3d1)

Device: Xperia XZ (F8331)
Android version: 8.0.0
Magisk version name: 831a398b
Magisk version code: 25206

Thanks in advice!

**Comment by osm0sis** [comment]
https://forum.xda-developers.com/t/mod-boot-bridge-for-sony-elf.3506883/
