### ISSUE TITLE
MagiskManager not detecting Magisk

### ISSUE THREAD

**Issue by CMLNT** [topjohnwu/Magisk#6552]
Device: BYD CAR PAD Dilink4.0  669 8+128
Android version: 10 UI4.0
Kernel Version: Linux 4.19.81-perf aarch64
Magisk version name: Canary
Magisk version code: 831a198b (25206)

MagiskManager not detecting Magisk 
magisk_log:
https://raw.githubusercontent.com/CMLNT/Dilink4_For_BYD/main/magisk_log_2023-01-21T09.08.32.log

**Comment by canyie** [comment]
Please set logging buffer size to the maximum value in system settings, reboot, then upload bugreport https://developer.android.com/studio/debug/bug-report

**Comment by canyie** [comment]
Any update? I'm going to close this issue as not enough information
