### ISSUE TITLE
Opening apps causes the system to crash and reboot sometimes, if Zygisk is used.

### ISSUE THREAD

**Issue by MarisaDAZA** [topjohnwu/Magisk#6569]
Device: Honor 8X (JSN-AL00a)
Android version: 8.1.0
Magisk version name: Debug
Magisk version code: 831a398b (25206) (D)

I have tried different apps one by one, and used `adb logcat` before opening them.  This is not a problem of a specific app, and it is irregular. ​Sometimes it happened, sometimes not, when I opened the same app.
Here are four logs that started before I opened the apps.
[1.log](https://github.com/topjohnwu/Magisk/files/10516996/1.log)
[2.log](https://github.com/topjohnwu/Magisk/files/10516997/2.log)
[3.log](https://github.com/topjohnwu/Magisk/files/10516999/3.log)
[4.log](https://github.com/topjohnwu/Magisk/files/10517000/4.log)

**Comment by canyie** [comment]
No crash can be found from your logs, perhaps it's a kernel panic? Can you check if there are some files under `/sys/fs/pstore` after it crashes and reboots? If so, can you upload them?

**Comment by MarisaDAZA** [comment]
> No crash can be found from your logs, perhaps it's a kernel panic? Can you check if there are some files under `/sys/fs/pstore` after it crashes and reboots? If so, can you upload them?

I added _'.txt'_ suffix, because github _don't support that file type._
[console-ramoops-0.txt](https://github.com/topjohnwu/Magisk/files/10750498/console-ramoops-0.txt)

**Comment by MarisaDAZA** [comment]
> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/10883672/app-debug.zip) Try this build?

There is another problem in this build: My device stuck in the boot screen after I flashed the patched file. I tried to format _cache partition_ , it was finally booted. Anyway, it hasn't crashed again up to now because of Zygisk.

**Comment by MarisaDAZA** [comment]
> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/10883672/app-debug.zip) Try this build?

It seems that the promblem still happens in the v26.1 release. Wasn't it solved in that build?

**Comment by yujincheng08** [comment]
@MarisaDAZA NO. Fixes to zygisk have been postponed to the next release.

**Comment by MarisaDAZA** [comment]
Interestingly, it seems that Magisk-alpha doesn't have this bug.

**Comment by canyie** [comment]
It's because Magisk-alpha has merged the fix.

I'll mark this issue as `enhancement` because John has announced "Huawei devices are not officially supported" in 4f73534837bda59fd58ca010fe25d3d66556883e, which means these devices are not guaranteed to be supported. As investigations have already stopped, keeping the `needs investigation` label is inappropriate.

**Comment by maingocvinh** [comment]
Any app added to Denylist will get an app stopped working error, how to solve it? If required I post any log please guide how to get it in various cases, such as while installing magisk using twrp error, magisk app stuck opening at the mask logo...

**Comment by MarisaDAZA** [comment]
> 

Why not open a new issue?

**Comment by maingocvinh** [comment]
I had about three unplanned closures and no one helped, cared or told me to upload logs

**Comment by MarisaDAZA** [comment]
> I had about three unplanned closures and no one helped, cared or told me to do sth like upload logs. It was the same with the magisk N/A bug on my samsung j5 before, I posted my problem in other people's have same issue like me and worked with the developers to solve it well, while I posted my own I will be closed as not planned and I don't have well supported, so I had no choice but to rely on everyone's problems. I know my English is sp bad that I can't make impress talk on anyone

That's because you should use debug version of Magisk. I think someone told you clearly. 
And, if your English is not good, you can use translator.

**Comment by yujincheng08** [comment]
fixed
