### ISSUE TITLE
baseband unknown only when booted magisk

### ISSUE THREAD

**Issue by aIecxs** [topjohnwu/Magisk#6570]
Device: Redmi 6 (`cereus`)
Android version: `9.0` (MIUI V11.0.4.0.PCGMIXM)
Magisk version name: `831a398b`
Magisk version code: `25206`

baseband unknown every time booted in Magisk. booting from stock boot baseband working again. no matter which Magisk version tried down to v22.1 without modules always flashed into recovery.

might related #426

[magisk_install_log_2023-01-28T01.12.34.log](https://github.com/topjohnwu/Magisk/files/10524017/magisk_install_log_2023-01-28T01.12.34.log)
[magisk_log_2023-01-28T01.14.40.log](https://github.com/topjohnwu/Magisk/files/10524019/magisk_log_2023-01-28T01.14.40.log)

**Comment by canyie** [comment]
#1801
It seems that MTK devices don't have some mountpoints in recovery.fstab, which are need for radio.
Btw, you own a Xiaomi device, so I think you should patch boot.img instead of recovery.img. Maybe issue will be solved by doing so

**Comment by canyie** [comment]
I'm closing the issue as it seems can't be fixed by Magisk (with information we currently have), and patching boot.img instead works for Xiaomi devices

**Comment by aIecxs** [comment]
I bet I had no ramdisk in boot. however, tried many times to patch boot.img with no result - until now. I patched recovery and used the direct install into boot - it works now!

anyway for the record my mount logs
[standard.txt](https://github.com/topjohnwu/Magisk/files/10771607/standard.txt)
[magisk_recovery.txt](https://github.com/topjohnwu/Magisk/files/10771612/magisk_recovery.txt)
[magisk_boot.txt](https://github.com/topjohnwu/Magisk/files/10771613/magisk_boot.txt)

**Comment by tuyennn** [comment]
> I bet I had no ramdisk in boot. however, tried many times to patch boot.img with no result - until now. I patched recovery and used the direct install into boot - it works now!
> 
> anyway for the record my mount logs [standard.txt](https://github.com/topjohnwu/Magisk/files/10771607/standard.txt) [magisk_recovery.txt](https://github.com/topjohnwu/Magisk/files/10771612/magisk_recovery.txt) [magisk_boot.txt](https://github.com/topjohnwu/Magisk/files/10771613/magisk_boot.txt)

Same issue thought, could you have any guide for it, for sharing,
