### ISSUE TITLE
Magisk Manager stops responding

### ISSUE THREAD

**Issue by ozarktech** [topjohnwu/Magisk#658]
I was following the directions in this forum https://forum.xda-developers.com/g-pad-x-80/how-to/guide-how-to-root-t-mobile-version-v530-t3777513 to root my tablet. I followed the above directions and everything worked great until I got Magisk Manager installed. It opened briefly the first time I opened it, then closed. Now when I open it, It hangs on the splash screen, then eventually says Magisk Manager isnt responding, do you want to close it? I went into app setting and force stopped it. I uninstalled and reinstalled. I restarted tablet several times. Did a fresh download and install, all with same results. Maybe this is an issue to open with Magisk, and not here, but this is what I ran into when I followed these instructions. I ran root checker and it says it's not rooted  Android version 7.0 Security patch level april 1, 2017. baseband version MPSS>TA.2.3.c4-00014-8940_GEN_PACK-1 kernel 3.18.31 Build NRD90U Software version V53010a 
I also reran the fastboot commands and tried several older versions of Magisk Manager but no luck.

**Comment by topjohnwu** [comment]
This mean you are not properly rooted. Also you don't post any logs so I can't fix anything
