### ISSUE TITLE
Unable to root the device with patched boot.img

### ISSUE THREAD

**Issue by ItzMiracleOwO** [topjohnwu/Magisk#6582]
Device: Redmi K60 Pro
Android version: Android 13
Magisk version name: 831a398b
Magisk version code: 25206

Hi,
I recently has tried to root my phone with magisk but failed, the bootloader has been unlocked.

Using the patched `boot.img`, tried multiple times but still unable to install magisk.
In the app, button for modules and su is disabled and it seems that it has no get the root premission

I have tried flash in the stock ROM using the offical tool MiFlash, the issue persists.

Commands ran:
![image](https://user-images.githubusercontent.com/76854136/216332381-9b40c70f-8eff-4c36-a50a-c4e25f67e090.png)

Thanks

New post using debug version, for original issue, see Closed #6581 

Original boot.img file and patched boot.img (both 25.2 and debug) file is attached as .zip files.
[magisk_patched-25200_sjCuk.zip](https://github.com/topjohnwu/Magisk/files/10569205/magisk_patched-25200_sjCuk.zip)
[magisk_patched-25206_soQyV.zip](https://github.com/topjohnwu/Magisk/files/10569259/magisk_patched-25206_soQyV.zip)
[boot.zip](https://github.com/topjohnwu/Magisk/files/10569207/boot.zip)

**Comment by ItzMiracleOwO** [comment]
Also:
![image](https://user-images.githubusercontent.com/76854136/216334051-84b1e8f3-d60c-42a6-be95-a7de3fecc541.png)

**Comment by canyie** [comment]
I believe your device does have `init_boot.img` so you should patch `init_boot.img` instead
