### ISSUE TITLE
Magisk ignores `init_boot.img` in tar file

### ISSUE THREAD

**Issue by DrKetan** [topjohnwu/Magisk#6585]
Device: Samsung S23 Ultra
Android version: A13
Magisk version name:831a398b
Magisk version code:25206

Patched samsung S23 Ultra (SM-S918B) kernel & vbmeta with Magisk and Flashed without error, Magisk not installed . Log and kernel (patched & stock) included

[Magisk_debug_s23u.zip](https://github.com/topjohnwu/Magisk/files/10582765/Magisk_debug_s23u.zip)

[boot_Patched.zip](https://github.com/topjohnwu/Magisk/files/10582772/boot_Patched.zip)
[boot_stock.zip](https://github.com/topjohnwu/Magisk/files/10582777/boot_stock.zip)

**Comment by BlackMesa123** [comment]
S23 device family shipped with Android 13 meaning it uses the new boot [header version 4](https://source.android.com/docs/core/architecture/bootloader/boot-image-header?hl=en#header-v4), adding the new `init_boot.img` in the [tar patching](https://github.com/topjohnwu/Magisk/blob/57d83635c6512f5e58753c7a1ae2d515c18cb70f/app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt#L177) process should fix the issue.

**Comment by canyie** [comment]
Upload installation log？

**Comment by canyie** [comment]
After taking a look at the code I believe the issue exists, but "simply setting `srcBoot` to `init_boot.img` if exists" will cause some kernel patches failed to apply. Not sure if Samsung's GKI kernel still need these kernel patches, need further investigation on it.

**Comment by BlackMesa123** [comment]
> After taking a look at the code I believe the issue exists, but "simply setting `srcBoot` to `init_boot.img` if exists" will cause some kernel patches failed to apply. Not sure if Samsung's GKI kernel still need these kernel patches, need further investigation on it.

Are you talking about the Samsung-specific kernel image patches? Are these still working nowadays? Since they’re pretty old (RKP patch from SuperSU and the Defex one is 5 yo). Would be great if someone could test a patched init_boot.img to check if everything is okay

**Comment by BlackMesa123** [comment]
I also was able to extract the kernel config from the stock image and it looks like some security kernel components aren't anymore a thing, probably due to how GKI works (talking about microHypervisor, RKP etc., of course we can’t be sure until we get our hands on the kernel sources)

**Comment by canyie** [comment]
Tried manually patch the boot.img, it seems Magisk still applies the "Remove Samsung defex" patch to the kernel. Not sure if Magisk will still work on Samsung's GKI kernel without the patch.
```
- Device platform: arm64-v8a
- Installing: 831a398b (25206)
- Processing tar file
-- Extracting: boot.img
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [4]
KERNEL_SZ       [47020544]
RAMDISK_SZ      [0]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2023-01]
PAGESIZE        [4096]
CMDLINE         []
KERNEL_FMT      [raw]
SAMSUNG_SEANDROID
VBMETA
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Record new entry: [init] -> [.backup/.rmlist]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Patch @ 004DC51C [821B8012] -> [E2FF8F12]
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [4]
KERNEL_SZ       [47020544]
RAMDISK_SZ      [0]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2023-01]
PAGESIZE        [4096]
CMDLINE         []
KERNEL_FMT      [raw]
SAMSUNG_SEANDROID
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [4]
KERNEL_SZ       [47020544]
RAMDISK_SZ      [512640]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2023-01]
PAGESIZE        [4096]
CMDLINE         []
-- Writing: boot.img

****************************
 Output file is written to 
 /storage/emulated/0/Download/magisk_patched-25206_ycb8H.tar 
****************************
cp: can't preserve ownership of 'busybox': Operation not permitted
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
cp: can't preserve ownership of 'magiskpolicy': Operation not permitted
- All done!
```

**Comment by canyie** [comment]
@DrKetan Can you test if Magisk works after doing these steps?
1. Open AP.tar, remove `boot.img` and rename `init_boot.img` to `boot.img`
2. Patch the modified tar file
3. Open the patched AP.tar, rename `init_boot.imf`

**Comment by DrKetan** [comment]
Thanks @canyie
I don't own device yet but will do as suggest and ask a tester to test
Which magisk you suggest to patch?

**Comment by BlackMesa123** [comment]
> Tried manually patch the boot.img, it seems Magisk still applies the "Remove Samsung defex" patch to the kernel. (RKP Patch fails since 2020 , #3485) Not sure if Magisk will still work on Samsung's GKI kernel without the patch.

I remember I opened the issue regarding the "new" Samsung Defex kernel module back in 2018 (#426), new iterations of this driver seems to now [check for the verifiedbootstate flag in cmdline](https://github.com/BlackMesa123/android_kernel_samsung_sm7325/blob/ac2cb3bb56b7101c07c1c5426bf39aaf8257d17b/security/samsung/defex_lsm/core/defex_lsm.c#L66) and accordingly enable/disable the checks, looks like it is the case for this device as well:

<img width="622" src="https://user-images.githubusercontent.com/13062958/216764072-24fd4292-290b-4215-978d-86f3abeb0a47.png">

**Comment by DrKetan** [comment]
> > Tried manually patch the boot.img, it seems Magisk still applies the "Remove Samsung defex" patch to the kernel. (RKP Patch fails since 2020 , #3485) Not sure if Magisk will still work on Samsung's GKI kernel without the patch.
> 
> I remember I opened the issue regarding the "new" Samsung Defex kernel module back in 2018 (#426), new iterations of this driver seems to now [check for the verifiedbootstate flag in cmdline](https://github.com/BlackMesa123/android_kernel_samsung_sm7325/blob/ac2cb3bb56b7101c07c1c5426bf39aaf8257d17b/security/samsung/defex_lsm/core/defex_lsm.c#L66) and accordingly enable/disable the checks, looks like it is the case for this device as well:
> 
> <img alt="" width="622" src="https://user-images.githubusercontent.com/13062958/216764072-24fd4292-290b-4215-978d-86f3abeb0a47.png">

Yes, I can recall now and I have participated in discussion and tested successfully patched kernel. Thank you @BlackMesa123

**Comment by yujincheng08** [comment]
I have worked on this issue before. Patches are not yet submitted tho. As it depends on #6438, the fix will be submited once it's merged.

**Comment by DrKetan** [comment]
> @DrKetan Patch the full AP.tar which contains `init_boot.img` don't work, right? If so, can you test if Magisk works after doing these steps?
> 
> 1. Open AP.tar, remove `boot.img` and rename `init_boot.img` to `boot.img`
> 2. Patch the modified tar file
> 3. Open the patched AP.tar, rename `boot.img` back to `init_boot.img`
> 4. Flash the new AP.tar

OK, I did it (Patched init_boot.img by renaming) but same issue no magisk installed. I have checked and init_boot is patched. Attached here patched & stock all files
[S23_debug_patched.zip](https://github.com/topjohnwu/Magisk/files/10608647/S23_debug_patched.zip)
[S23_debug _stock.zip](https://github.com/topjohnwu/Magisk/files/10608648/S23_debug._stock.zip)

**Comment by tvarsis** [comment]
Is this the same issue that are giving issues with OTA on Google Pixel 7 which also uses init_boot?

**Comment by canyie** [comment]
@tvarsis If you face bootloop after OTA, check #5959
