### ISSUE TITLE
Magisk Manager stopped | Chrome not as system app

### ISSUE THREAD

**Issue by kyolab1** [topjohnwu/Magisk#659]
[Note 9, Oreo 8.1] 
After uninstalling the included Chrome (System App Remover Root), and installing e.g. the latest Chrome apk as user app instead, html viewer stops working, which also crashes Magisk Manager, when trying to open any of the app detail pages popups within Magisk Manager/Downloads.
Maybe Magisk Manager could be independent of Chrome and HTML viewer installed as system app?

**Comment by Didgeridoohan** [comment]
The Manager isn't dependent on Chrome as a system app (I don't even have Chrome installed at all and have no issues). You might have messed up your WebView somehow. Don't know about Samsung, but on a normal Android device you can set your WebView implementation under Developer options. Start there...

**Comment by kyolab1** [comment]
Hi Didgeridoohan, thanks for your reply. I am talking stock rom (N960FD). As soon as I uninstall chrome, html viewer (SecHTMLViewer.apk) gives error when e.g. opening a txt file. And it seems Magisk Manager is using that to show the app details popup. 
I will now try to uninstall both chrome and html viewer and clear data on webview (which I have not touched at all until now). I understand this is not necessarily a Magisk Manager specific issue, but it does seem to use at least the defaul hmtlviewer (which does not work without the default chrome).
