### ISSUE TITLE
Instructiosn should be more specific about init_boot

### ISSUE THREAD

**Issue by sebolio** [topjohnwu/Magisk#6591]
I followed the instructions and used `init_boot.img` image instead of  `boot.img`, but they aren't specific about the fact that you have to use `fastboot flash init_boot <file>` and instead show `fastboot flash boot <file>`, which is confuse and incorrect. Please add more specific instructions about what command to use for each file. I only found the right command in xda-developers forums.

Device: Pixel 7 Pro
Android version: 13
Magisk version name: 25.2
Magisk version code: 25206

**Comment by BlackMesa123** [comment]
The usage of the fastboot command can be seen by running `fastboot --help`:

```
➜  ~ fastboot --help
usage: fastboot [OPTION...] COMMAND...

flashing:
 update ZIP                 Flash all partitions from an update.zip package.
 flashall                   Flash all partitions from $ANDROID_PRODUCT_OUT.
                            On A/B devices, flashed slot is set as active.
                            Secondary images may be flashed to inactive slot.
 flash PARTITION [FILENAME] Flash given partition, using the image from
                            $ANDROID_PRODUCT_OUT if no filename is given.
```
