### ISSUE TITLE
Magisk Stub

### ISSUE THREAD

**Issue by TugaPowerROM** [topjohnwu/Magisk#66]
Version 10.2 was the latest one that create the Magisk stub app, with 11.0 and 11.1 the stub app its not being installed anymore.

**Comment by nicegamer7** [comment]
I can confirm this, I am running Android 5.1. There are no errors during install.

**Comment by nicegamer7** [comment]
Is there some sort of log we can provide to help fix this, or was this intentional?

**Comment by topjohnwu** [comment]
Maybe I missed out something, thanks for the report!

**Comment by topjohnwu** [comment]
Fixed
