### ISSUE TITLE
When trying to patch boot.img, Magisk closes.

### ISSUE THREAD

**Issue by unnamed24** [topjohnwu/Magisk#6601]
Device: Xiaomi Redmi Note 10S.
Android version: 12
Magisk version name: Debug
Magisk version code: 25206

In general, subject, I downloaded the latest firmware from the "Fastboot" section, unpacked boot.img from the archive, then sent it to the phone's internal memory via "adb push", but if select this boot.img in Magisk and click "Let's Go." , Magisk closes.
Logcat attached as a ZIP archive due to GitHub restrictions.
[unnamed.zip](https://github.com/topjohnwu/Magisk/files/10717267/unnamed.zip)

**Comment by yujincheng08** [comment]
Cannot see crash log

**Comment by vvb2060** [comment]
this is not magisk log
