### ISSUE TITLE
[Feature request] Hide root from newly installed apps 

### ISSUE THREAD

**Issue by kaliiiiiiiiii** [topjohnwu/Magisk#6613]
My case: I want to __hide Magisk__ from my device, even from other, __newly installed apps__.

That's where my issue starts:
- With zygisk enabled, It's not possible to hide root from apps which get installed in the future.

What I'd need:
- A switch (in the settings) which, when enabled __denies all new root-requests__.  And maybe leaves a notification. ==> Whitelist
- Other solution?

Device: Oneplus7-
Android version: 11
Magisk version name: 25.2
Magisk version code: 25206

**Comment by canyie** [comment]
https://topjohnwu.github.io/Magisk/faq.html#q-why-is-x-app-detecting-root

**Comment by kaliiiiiiiiii** [comment]
> https://topjohnwu.github.io/Magisk/faq.html#q-why-is-x-app-detecting-root

@canyie But wouldn't a whitelist for the zygisk deny list need to be implemented directly into Magisk?

**Comment by canyie** [comment]
No. "Whitelist" brings a lot of performance degrades and many users will abuse this feature

**Comment by axelkar** [comment]
> No. "Whitelist" brings a lot of performance degrades and many users will abuse this feature

Can you clarify what you mean? What does DenyList currently do? Is it like literally giving an unmodified environment from pre-Magisk install? Disable Zygisk or revert it altogether? I know that `/system/bin/su` is hidden for apps with DenyList.

You developers of Magisk feel really hostile, and I understand that having people constantly making low-effort bug reports is annoying, but please be friendly. Better documentation would help. Perhaps describing, in Magisk Manager itself (not online), what the options do would help.
