### ISSUE TITLE
Approaching total cache storage limit (13.74 GB of 10 GB Used)

### ISSUE THREAD

**Issue by mymine** [topjohnwu/Magisk#6618]
Approaching total cache storage limit (13.74 GB of 10 GB Used)
![Screenshot_2023-02-20-16-20-46-872_com tugoubutu liulanqi](https://user-images.githubusercontent.com/2943365/220051161-f91bd146-287f-496c-99f4-8a35e3935e08.jpg)
Device: Pixel 7 Pro
Android version: 13
Magisk version name: 25.2
Magisk version code: 25206

**Comment by yujincheng08** [comment]
ok.
