### ISSUE TITLE
Magisk can't install modules, even saved in /emulated/0/Download/

### ISSUE THREAD

**Issue by 5x3** [topjohnwu/Magisk#6630]
Device: Xiaomi Redmi 9C NFC 4/128 (MIUI 12.5.2.0)
Android version: 11 RP1A.200720.011
Magisk version name:  io.github.huskydg.magisk
Magisk version code: 25.6 25206

When select file to install:
```
 Copying zip to temp directory
! Unzip error
```

`E js      : java.io.FileNotFoundException: /data/user/0/com.topjohnwu.magisk/cache/flash/updater-script: open failed: ENOENT (No such file or directory)`

same error with 25.2 and 24.3.

**Comment by 5x3** [comment]
looks like updater-script script file is missing somehow, I can place this file by hand, but I cant find it somewhere to copy to directory mentioned above. Not sure problem relate do Android 11, it can be related to MIUI 12.5 and it's R/O /system etc (just guessing).

**Comment by osm0sis** [comment]
Use official Magisk if you want to report issues to official Magisk.

**Comment by 5x3** [comment]
I'm not aware where your official last debug build lives, please remember of usability of your product.
 
please provide Magisk self fix for modulename-main.zip with a single subdirectory modulename-main inside, why Magisk trying to re-learn whole world than just fit non "release" modules archives?

Should be fixed as:
if 'modulename-main.zip/modulename-main/' directory exists and no other dirs exists aside (dir is only one) and
if 'modulename-main.zip/modulename-main/INF_files_etc' all the files inside this subdir - then
repack inernaly 'modulename-main.zip/modulename-main/INF_files_etc' as  -> 'modulename-main.zip/INF_files_etc'
before take install attempt.

**Comment by osm0sis** [comment]
It's linked in the readme, sorry that took you longer than 5 minutes to find. Open a new issue when you're ready to file a proper issue report with the latest debug build and with logs.
