### ISSUE TITLE
Hiding magisk app always hangs

### ISSUE THREAD

**Issue by RV7PR** [topjohnwu/Magisk#6632]
Device: Samsung Galaxy S23 Plus (SM-S916B)
Android version: 13
Magisk version name: 92077ebe
Magisk version code: 25206

[logcat_02-26-2023_06-11-36.txt](https://github.com/topjohnwu/Magisk/files/10833029/logcat_02-26-2023_06-11-36.txt)
[magisk_log_2023-02-26T06.01.43.log](https://github.com/topjohnwu/Magisk/files/10833030/magisk_log_2023-02-26T06.01.43.log)

![Screenshot_20230226_060052](https://user-images.githubusercontent.com/17615589/221393770-b06a5e2e-8d44-4505-b5f4-6cf85fd6d9c6.jpg)

**Comment by RV7PR** [comment]
Updating not working either

[magisk_log_2023-02-27T03.46.34.log](https://github.com/topjohnwu/Magisk/files/10835707/magisk_log_2023-02-27T03.46.34.log)
[logcat_02-27-2023_03-48-00.txt](https://github.com/topjohnwu/Magisk/files/10835706/logcat_02-27-2023_03-48-00.txt)

https://user-images.githubusercontent.com/17615589/221463272-7589b024-9a6b-4bf2-be4d-1b37e023babf.mp4

**Comment by ssrubsd** [comment]
same

**Comment by dragonloverlord** [comment]
Update installed for me but magisk instantly closes on launch. I'm using a Google Pixel 4a on Android 13 T2B3.230109.004 so it appears the update itself is broke for now.

**Comment by AllenChangMusic** [comment]
I can second this. Even with the new artifact that was generated a few hours ago that fixed the modules, it is not possible to hide the app. It will try to install the hidden apk, but it will then say installation failed.

**Comment by otonieru** [comment]
> Update installed for me but magisk instantly closes on launch. I'm using a Google Pixel 4a on Android 13 T2B3.230109.004 so it appears the update itself is broke for now.

yes. i think last update is broken. On my Pixel 7 Pro, it installed, but crash immediately when opening as well.
