### ISSUE TITLE
Magisk app crashing on appstart (25207)

### ISSUE THREAD

**Issue by SammCheese** [topjohnwu/Magisk#6637]
### Context:
The canary build has been installed and the app would immediate crash when clicked. 
Uninstalled and reinstalled to make sure it wasnt related to the app being hidden before, same thing happened. 
I've installed the Debug version to report the bug however the crash does not happen on the debug version of the app. So this report is from the `canary` version. How much this helps is questionable

### Device Info

Device: Google Pixel 6 (oriole)
Android version: Android 14 UpsideDownCake (UPP1.230113.009)
Magisk version name: 7dbfba
Magisk version code: 25207

### Logcat  Logs

[MAGISK_log_2023_02_27_01_36_16.log](https://github.com/topjohnwu/Magisk/files/10835225/MAGISK_log_2023_02_27_01_36_16.log)

**Comment by lonkarjay** [comment]
+1.
Same is happening for Android 12 also.

**Comment by bugme2** [comment]
一样，大概18号之后的commit就开始闪退，反馈bug被关闭了，我以为作者会注意到。

**Comment by lssong99** [comment]
I concur that latest Canary cannot start on Pixel 6 Pro 13 QPR beta 2. Uninstall then reinstall same. Magisk hide is enabled.

**Comment by canyie** [comment]
The breaking commit is 9b1e17337373f0e6364e30a9fcae84a5c62275d9

**Comment by 1814239758** [comment]
(25207) Canary Chanel Crash the same on my device. However debug chanel (25207) works well, maybe could try this version?

**Comment by AllenChangMusic** [comment]
> 

It doesn't let you hide the app though. So still issues in there.

**Comment by Haseo97** [comment]
Same issues on A13.

**Comment by scrocle** [comment]
same issue. A13

**Comment by wansenlyt** [comment]
same issue. Pixel6pro

**Comment by supermansaga** [comment]
> same issue. Pixel6pro with TQ1A.230205.002

Pixel 7 Pro with the same exact build has the issue too. Glad I found the pack had already reported. Looking forward to the update. Many thanks

**Comment by Nergal-di-Cuthah** [comment]
Tried again after topjohnwu closed still the same. Unlocked Pixel 6 pro February update. Tried clearing cache clearing data. Downgrading to stable (got generic icon no open). Installed 25206 (had to use apkmirror as i can't seem to find the canaries on github though I'm sure theyre there.

**Comment by RV7PR** [comment]
You can use the actions build
https://github.com/topjohnwu/Magisk/actions/runs/4279623994

**Comment by Nergal-di-Cuthah** [comment]
I think that's a tad over my head today, i'll wait for a commit thank yoi, and especially thank the people who can use the actions build to confirm the fixes

**Comment by shizonic** [comment]
The actions build installation gets blocked by play protect. Even if I choose "Install anyway" it fails to install.

**Comment by Nergal-di-Cuthah** [comment]
Ok weird 207 debug worked. Can i keep debug and be upgraded to non-debug when next version pops. Again thank you all.
