### ISSUE TITLE
Magisk hide cause the Google Play Service stop running

### ISSUE THREAD

**Issue by singleNeuron** [topjohnwu/Magisk#664]
When I opened the Magisk hide and tried to start the SafetyNet check, it showed a Invalid return value. and the Google Play Service stop runninfg.
It also caused other apps stopping running if I add them into the list of Magisk Hide.
I'm using StatixOS-0919 on Google Nexus 6p, Magisk 17.2, Maganer 6.0

>build.board: angler
build.bootloader: angler-03.79
build.brand: google
build.cpu_abi: arm64-v8a
build.cpu_abi2:
build.device: angler
build.display: PPR2.180905.005 test-keys
build.fingerprint: google/angler/angler:8.1.0/OPM6.171019.030.K1/4947289:user/release-keys
build.hardware: angler
build.host: jvps
build.id: PPR2.180905.005
build.manufacturer: Huawei
build.model: Nexus 6P
build.product: angler
build.radio: unknown
build.serial: ENU7N16126004212
build.tags: release-keys
build.time: 1537356670000
build.type: user
build.user: jertlok
version.codename: REL
version.incremental: eng.jertlo.20180919.113115
version.release: 9
version.sdk_int: 28
10-08 02:57:07.783 W/ctxmgr (4783): [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10032):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null , 3pMdlId = null , pid = 4783). Was: 3 for 57, account#-517948760#
10-08 02:57:08.265 I/Magisk (612): hide_list: [com.google.android.gms.unstable]
10-08 02:57:11.336 I/ActivityManager(1441): Start proc 6121:com.google.android.gms.unstable/u0a32 for service com.google.android.gms/.droidguard.DroidGuardService
10-08 02:57:11.447 I/Magisk (612): proc_monitor: com.google.android.gms.unstable
10-08 02:57:11.873 I/LocationReportEnabler(6121): install hook for com.google.android.gms (0)
10-08 02:57:12.790 W/ctxmgr (4783): [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10032):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null , 3pMdlId = null , pid = 4783). Was: 3 for 57, account#-517948760#
10-08 02:57:14.892 E/JavaBinder(6121): at syc.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):44)
10-08 02:57:14.892 E/JavaBinder(6121): at syc.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):2)
10-08 02:57:14.892 E/JavaBinder(6121): at szh.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):22)
10-08 02:57:14.892 E/JavaBinder(6121): at szh.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):20)
10-08 02:57:14.892 E/JavaBinder(6121): at wss.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):3)
10-08 02:57:14.892 E/JavaBinder(6121): at cgm.onTransact(:com.google.android.gms@13280037@13.2.80 (100400-211705629):5)
10-08 02:57:14.892 E/JavaBinder(6121): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.message.BasicNameValuePair" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/framework/com.android.location.provider.jar", zip file "/data/app/com.google.android.gms-_vBuLr0d5fmyB1t1P26e2g==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-_vBuLr0d5fmyB1t1P26e2g==/lib/arm64, /data/app/com.google.android.gms-_vBuLr0d5fmyB1t1P26e2g==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
10-08 02:57:14.896 E/AndroidRuntime(6121): Process: com.google.android.gms.unstable, PID: 6121
10-08 02:57:14.896 E/AndroidRuntime(6121): at syc.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):44)
10-08 02:57:14.896 E/AndroidRuntime(6121): at syc.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):2)
10-08 02:57:14.896 E/AndroidRuntime(6121): at szh.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):22)
10-08 02:57:14.896 E/AndroidRuntime(6121): at szh.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):20)
10-08 02:57:14.896 E/AndroidRuntime(6121): at wss.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):3)
10-08 02:57:14.896 E/AndroidRuntime(6121): at cgm.onTransact(:com.google.android.gms@13280037@13.2.80 (100400-211705629):5)
10-08 02:57:14.896 E/AndroidRuntime(6121): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.message.BasicNameValuePair" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/framework/com.android.location.provider.jar", zip file "/data/app/com.google.android.gms-_vBuLr0d5fmyB1t1P26e2g==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-_vBuLr0d5fmyB1t1P26e2g==/lib/arm64, /data/app/com.google.android.gms-_vBuLr0d5fmyB1t1P26e2g==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
10-08 02:57:15.192 I/ActivityManager(1441): Process com.google.android.gms.unstable (pid 6121) has died: vis BFGS
10-08 02:57:15.193 W/ActivityManager(1441): Scheduling restart of crashed service com.google.android.gms/.droidguard.DroidGuardService in 1000ms
10-08 02:57:15.204 D/Prevent (1441): action: app died, package: com.google.android.gms, count: 0
10-08 02:57:16.224 I/ActivityManager(1441): Start proc 6172:com.google.android.gms.unstable/u0a32 for service com.google.android.gms/.droidguard.DroidGuardService
10-08 02:57:16.387 I/Magisk (612): proc_monitor: com.google.android.gms.unstable
10-08 02:57:17.014 I/LocationReportEnabler(6172): install hook for com.google.android.gms (0)
10-08 02:57:18.825 W/ctxmgr (4783): [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10032):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null , 3pMdlId = null , pid = 4783). Was: 3 for 57, account#-517948760#

My English is poor because it's not my local language, please don't mind, thx.

**Comment by singleNeuron** [comment]
I'm sorry that I maybe send an error log before.

> build.board: angler
build.bootloader: angler-03.79
build.brand: google
build.cpu_abi: arm64-v8a
build.cpu_abi2: 
build.device: angler
build.display: PPR2.180905.005 test-keys
build.fingerprint: google/angler/angler:8.1.0/OPM6.171019.030.K1/4947289:user/release-keys
build.hardware: angler
build.host: jvps
build.id: PPR2.180905.005
build.manufacturer: Huawei
build.model: Nexus 6P
build.product: angler
build.radio: unknown
build.serial: ENU7N16126004212
build.tags: release-keys
build.time: 1537356670000
build.type: user
build.user: jertlok
version.codename: REL
version.incremental: eng.jertlo.20180919.113115
version.release: 9
version.sdk_int: 28

10-08 02:57:07.783 W/ctxmgr  (4783): [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10032):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 4783). Was: 3 for 57, account#-517948760#
10-08 02:57:08.265 I/Magisk  (612): hide_list: [com.google.android.gms.unstable]
10-08 02:57:11.336 I/ActivityManager(1441): Start proc 6121:com.google.android.gms.unstable/u0a32 for service com.google.android.gms/.droidguard.DroidGuardService
10-08 02:57:11.447 I/Magisk  (612): proc_monitor: com.google.android.gms.unstable
10-08 02:57:11.873 I/LocationReportEnabler(6121): install hook for com.google.android.gms (0)
10-08 02:57:12.790 W/ctxmgr  (4783): [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10032):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 4783). Was: 3 for 57, account#-517948760#
10-08 02:57:14.892 E/JavaBinder(6121): 	at syc.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):44)
10-08 02:57:14.892 E/JavaBinder(6121): 	at syc.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):2)
10-08 02:57:14.892 E/JavaBinder(6121): 	at szh.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):22)
10-08 02:57:14.892 E/JavaBinder(6121): 	at szh.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):20)
10-08 02:57:14.892 E/JavaBinder(6121): 	at wss.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):3)
10-08 02:57:14.892 E/JavaBinder(6121): 	at cgm.onTransact(:com.google.android.gms@13280037@13.2.80 (100400-211705629):5)
10-08 02:57:14.892 E/JavaBinder(6121): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.message.BasicNameValuePair" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/framework/com.android.location.provider.jar", zip file "/data/app/com.google.android.gms-_vBuLr0d5fmyB1t1P26e2g==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-_vBuLr0d5fmyB1t1P26e2g==/lib/arm64, /data/app/com.google.android.gms-_vBuLr0d5fmyB1t1P26e2g==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
10-08 02:57:14.896 E/AndroidRuntime(6121): Process: com.google.android.gms.unstable, PID: 6121
10-08 02:57:14.896 E/AndroidRuntime(6121): 	at syc.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):44)
10-08 02:57:14.896 E/AndroidRuntime(6121): 	at syc.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):2)
10-08 02:57:14.896 E/AndroidRuntime(6121): 	at szh.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):22)
10-08 02:57:14.896 E/AndroidRuntime(6121): 	at szh.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):20)
10-08 02:57:14.896 E/AndroidRuntime(6121): 	at wss.a(:com.google.android.gms@13280037@13.2.80 (100400-211705629):3)
10-08 02:57:14.896 E/AndroidRuntime(6121): 	at cgm.onTransact(:com.google.android.gms@13280037@13.2.80 (100400-211705629):5)
10-08 02:57:14.896 E/AndroidRuntime(6121): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.message.BasicNameValuePair" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/framework/com.android.location.provider.jar", zip file "/data/app/com.google.android.gms-_vBuLr0d5fmyB1t1P26e2g==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-_vBuLr0d5fmyB1t1P26e2g==/lib/arm64, /data/app/com.google.android.gms-_vBuLr0d5fmyB1t1P26e2g==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
10-08 02:57:15.192 I/ActivityManager(1441): Process com.google.android.gms.unstable (pid 6121) has died: vis  BFGS
10-08 02:57:15.193 W/ActivityManager(1441): Scheduling restart of crashed service com.google.android.gms/.droidguard.DroidGuardService in 1000ms
10-08 02:57:15.204 D/Prevent (1441): action: app died, package: com.google.android.gms, count: 0
10-08 02:57:16.224 I/ActivityManager(1441): Start proc 6172:com.google.android.gms.unstable/u0a32 for service com.google.android.gms/.droidguard.DroidGuardService
10-08 02:57:16.387 I/Magisk  (612): proc_monitor: com.google.android.gms.unstable
10-08 02:57:17.014 I/LocationReportEnabler(6172): install hook for com.google.android.gms (0)
10-08 02:57:18.825 W/ctxmgr  (4783): [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10032):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 4783). Was: 3 for 57, account#-517948760#

**Comment by Ante0** [comment]
What modules do you have installed? For me Busybox was causing this, and Universal host block caused basic integrity check to fail. Uninstalling both fixed it.
