### ISSUE TITLE
25207 completely breaks

### ISSUE THREAD

**Issue by Originalimoc** [topjohnwu/Magisk#6645]
Device: Redmi K30 Pro
Android version: 12
Magisk version name: 7dbfba7
Magisk version code: 25207

issue 6637 related maybe

MIUI 13/14
Android 12
Not obfs manager package name
fresh img flash or recovery install
can't launch manager
even freeze system

**Comment by Originalimoc** [comment]
su (toast) and mounting still working though

**Comment by canyie** [comment]
Duplicate of #6637
