### ISSUE TITLE
magisk still unable hide fgo in latest canary build

### ISSUE THREAD

**Issue by s06010** [topjohnwu/Magisk#665]
fgo (jp) still detect  magisk  in canary build 

with error code 61（it means that detect magisk manger or other root app etc but i only install magisk manger as a root app）

devices; oneplus 6 (A6003)
os ; android 9 with oxygen os 9.0(stable vision)

here are the logkit and the magisk log

logkit:https://drive.google.com/file/d/1tiWBtoICoDhKUAWd-656rPYz4jK_a3dO/view?usp=drivesdk

magisklog;https://drive.google.com/file/d/1Hz8j3QSit49HHiVLVlBgGyeOtrBixy7s/view?usp=drivesdk

**Comment by topjohnwu** [comment]
It is working fine on mine, it is something wrong on your side
