### ISSUE TITLE
Root can be detected on multi-user.

### ISSUE THREAD

**Issue by SakuraWald** [topjohnwu/Magisk#6669]
Device: Google Pixel 7 Pro
Android version: Android 13
Magisk version name: 25.2
Magisk version code: 25208

Install magisk on your owner user, and enable zygisk, set multiuser mode to only owner has root access. Then switch to another user (non-owner user). You can use AIDA64, see the device is rooted device: yes. But if you use AIDA64 on your owner user, then you can see rooted device: no

NOTE: the `multi-user` controls the `root access`, on `non-owner user`, you can use `root checker` to see that root access is unavailable, but you can use `AIDA64` to see that fact that: the device is rooted.

NOTE: if set `multiuser mode` to `device owner managed`, and install magisk on `non-owner user`, then you can set `denylist` on `non-owner user`, and `AIDA64` will not detect the root status. (Showing `rooted device: no`)

**Comment by yujincheng08** [comment]
expected behavior.
