### ISSUE TITLE
Hide xposed 

### ISSUE THREAD

**Issue by devjava81** [topjohnwu/Magisk#667]
Some app detect xposed framework in jni and some another method
proc/pid/maps
Some body can help me modify xposed (rename package)

**Comment by SuperSandro2000** [comment]
Not possible

**Comment by devjava81** [comment]
> Not possible

I think topjohnwu can do this, just replace XposedBrige framework :(

**Comment by Didgeridoohan** [comment]
If you just want to hide the Xposed Installer by changing the package name that's something you can do yourself (Google it if you don't know how).

If you're talking about hiding Xposed itself it isn't possible. And trust me, @topjohnwu has looked at it...

Please close this issue, it has nothing to do here.
