### ISSUE TITLE
Magisk stopped working after installing latest LineageOS 20 build

### ISSUE THREAD

**Issue by AviciiPL** [topjohnwu/Magisk#6671]
Device: Pixel 2 XL
Android version: LineageOS 20 (20230302)
Magisk version name: 2717feac
Magisk version code:  25209

Hi.
After installing latest LineageOS build, magisk completely stopped working.
I don't know what's wrong. Maybe magisk patcher stopped working properly.
Befre I must patch boot.img every LineageOS update.  It worked all the time. 
But not now.
Magisk App show this log:
[magisk_log_2023-03-02T22.35.23.log](https://github.com/topjohnwu/Magisk/files/10876036/magisk_log_2023-03-02T22.35.23.log)
boot.img
[boot.zip](https://github.com/topjohnwu/Magisk/files/10876050/boot.zip)
magisk_patched.img
[magisk_patched.zip](https://github.com/topjohnwu/Magisk/files/10876053/magisk_patched.zip)
Some logs missing? Just tell me what logs you need.
I don't think this is a modules fault (systemless, skvalex recorder), because in my prevous case, module cause bootloop.

**Comment by yujincheng08** [comment]
follow this to get a bugreport https://developer.android.com/studio/debug/bug-report

**Comment by AviciiPL** [comment]
I don't think this is a problem with android. I have 2 slots. on B i have latest LOS version, where magisk doesn't working.
I can change active slot. on A I have prevous LOS version, where magisk worked, but not now. Latest working Magisk version is 25207 on LineageOS 20.0-20230223

**Comment by yujincheng08** [comment]
no log no fix.

**Comment by AviciiPL** [comment]
[bugreport-lineage_taimen-TQ1A.230205.002-2023-03-03-07-40-26.zip](https://github.com/topjohnwu/Magisk/files/10878944/bugreport-lineage_taimen-TQ1A.230205.002-2023-03-03-07-40-26.zip)

**Comment by yujincheng08** [comment]
From the log, looks like the patched boot was not used.

**Comment by AviciiPL** [comment]
> From the log, looks like the patched boot was not used.

I don't know why. I flashed boot.img on two slots. From prevous LineageOS version and latest. Magisk version 25208 and 25209.

**Comment by yujincheng08** [comment]
[new-boot.zip](https://github.com/topjohnwu/Magisk/files/10879053/new-boot.zip)
Try this boot

**Comment by AviciiPL** [comment]
> [new-boot.zip](https://github.com/topjohnwu/Magisk/files/10879053/new-boot.zip) Try this boot

Yes. Now it's working.
