### ISSUE TITLE
Lost some system functions upon installing Magisk on Android P

### ISSUE THREAD

**Issue by braveheartleo** [topjohnwu/Magisk#668]
Much in the same fashion as that of #597, it seems that there are other issues as well when installing Magisk on Android P, at least on a Nokia 7 plus TA-1046 and confirmed by several other users [1]

The system fingerprint is
`Nokia/Onyx_00WW/B2N_sprout:9/PPR1.180610.011/00WW_3_22C:user/release-keys`

Upon fastbooting a patched boot.img using MagiskManager 6.0 canary debug build with a Magisk 17.3, also a canary debug build, the system experiences some system glitches as follows:

1) Vibration intensity for haptic feedback is increased
2) Certain system gestures become unavailable like Lift to check phone or Swipe up from home
3) Double tap to wake becomes unavailable
4) Some other glitches I may have missed

The thing is that as soon as the system is restarted, said glitches disappear and the system returns to normal. The same is also observed even when Direct Install Magisk to the system after achieving root privileges and then uninstalling afterwards. No modules were used nor installed upon testing.

This did not happen back when the system was running Android Oreo 8.1. It seems that having Magisk is causing glitches to this system running Pie, at least on this hardware.

I could not zero in on where the issue may be, so perhaps someone would be able to guide me on troubleshooting this further. I'm attaching the debug logs upon patching the boot.img and booting it subsequently via fastboot.

I could also provide screenies for the missing gestures before and after applying the Magisk patch, as well as the stock boot image.

Here is the link to the Magisk install log:
https://pastebin.com/ZTAxxG50

And here is the link to the magisk run log:
https://pastebin.com/15XCZ0Sc

[1] https://forum.xda-developers.com/nokia-7-plus/development/investigate-magisk-installed-missed-t3851492

**Comment by topjohnwu** [comment]
@braveheartleo can you give me the output of `cat /proc/mounts` when unrooted (with Magisk uninstalled)? Thank you!

**Comment by k3dar** [comment]
@topjohnwu here is cat /proc/mounts when unrooted: https://pastebin.com/wzNDxvGg

**Comment by Gravemind2015** [comment]
@topjohnwu here is another one. Saw some extra lines in mine so decided to post it.
https://pastebin.com/s02z3TYC

**Comment by braveheartleo** [comment]
@topjohnwu I have asked other members from xda who are experiencing the issue to help out. I have since rolled back to Oreo, and so I could not provide relevant info atm. ;-)

**Comment by topjohnwu** [comment]
This commit (9592a699865930a54ccd1ca193ae3acf909111e9) could fix the issue, please open a new issue if the problem persists.
