### ISSUE TITLE
Refactor sepolicy.rules resolve more

### ISSUE THREAD

**Issue by vvb2060** [topjohnwu/Magisk#6684]
Background: We need to find a partition after booting that can store module rule, because some devices have cache/metadata partitions but they will not be mounted after booting.  The target partition needs to be mounted by system so we can write safely.

#6480 partially solves this problem, but it mounts partition as read-write and keeps it until booted, writing module rules to it is dangerous, we don't know the correct mount parameters. In addition, some people reported that their recovery env is completely different from normal boot.

normal boot
```
16659 14366 259:51 / /cache rw,nosuid,nodev,noatime master:23 - ext4 /dev/block/bootdevice/by-name/cache rw,seclabel,data=ordered
```
[magisk_log_2023-03-05T10.45.11.log](https://github.com/topjohnwu/Magisk/files/10890848/magisk_log_2023-03-05T10.45.11.log)

twrp
```
29 1 259:13 / /cache rw,relatime - ext4 /dev/block/bootdevice/by-name/cache rw,seclabel,data=ordered
```
![IMG_20230305_132347_490](https://user-images.githubusercontent.com/26996262/222943297-072d167a-a63b-4458-8c21-30093250a741.jpg)

Therefore, we should stop find partition in recovery. If magisk is installed via recovery, it will be in a limited state and will need to be reflashed in app. This will ensure proper functionality and simplify code.

**Comment by vvb2060** [comment]
cc @yujincheng08

**Comment by reiryuki** [comment]
If Magisk has to be re-flashed on system boot, what about some Mediatek devices that don't allow modification of boot.img on system boot (read-only) and can only be flashed via recovery?

**Comment by yujincheng08** [comment]
@reiryuki `fastboot flash boot` should work. If you insist on using a custom recovery, you can patch the boot and flash it in recovery.

**Comment by osm0sis** [comment]
Just out of curiosity, why the switch to device id major:minor?

**Comment by reiryuki** [comment]
Why don't use device id major:minor only if by-name links are not detected. Using it just in case. Just a suggestion. FYI Magisk Delta reverted this changes.

**Comment by yujincheng08** [comment]
we dont know if the links exists!

**Comment by yujincheng08** [comment]
the worst thing is, some devices may not mount the partition that used by magisk for sepolicy rules. so we MUST determine the partiton after boot.

**Comment by reiryuki** [comment]
allright 👍

**Comment by osm0sis** [comment]
> just for human-readability
> 
> Not all devices have by-name links.

True! But would still be listed in the fstab with the same mountpoint in that case.

**Comment by yujincheng08** [comment]
magiskinit no longer parses fstab.

**Comment by osm0sis** [comment]
> the worst thing is, some devices may not mount the partition that used by magisk for sepolicy rules. so we MUST determine the partiton after boot.

> magiskinit no longer parses fstab.

Ah, fair point, metadata is often not mounted to anywhere, and persist can be mounted anywhere or nowhere. I just seemed to recall Magisk made its own mountpoint of the partition used so it didn't matter if the OS mounted it or not.

**Comment by yujincheng08** [comment]
> Magisk made its own mountpoint of the partition used so it didn't matter if the OS mounted it or not

The first floor explains:

> it mounts partition as read-write and keeps it until booted, writing module rules to it is dangerous, we don't know the correct mount parameters.


Further, mounting it as RW prevents us from using f2fs partition (see #3171). And the annoying thing is, many custom ROMs format cache and metadata as f2fs. And magisk thus cannot even find one suitable partition.

**Comment by vvb2060** [comment]
![image](https://user-images.githubusercontent.com/26996262/225601422-225efbf7-11ff-4914-bc03-2c902d17c3ed.png)
![image](https://user-images.githubusercontent.com/26996262/225601482-487f9d47-9ba1-461b-adce-ccaa3e63a597.png)
