### ISSUE TITLE
Nexus 6P goes into bootloop.

### ISSUE THREAD

**Issue by spiral6** [topjohnwu/Magisk#67]
[Here's the stock boot.img.](https://superuser.phh.me/nexus/angler/MDB08K/orig-boot.img)

Multiple people have been having issues with this on reddit, as seen [here](https://www.reddit.com/r/Android/comments/5sb8ft/magisk_v11_released/dde2l4p/) and [here](https://www.reddit.com/r/Android/comments/5sb8ft/magisk_v11_released/ddeb592/). 

I have TWRP, and installed the Magisk v1.1.zip file on it without errors. However, booting into my phone never finishes, with it being stuck on the bootanimation endlessly.

**Comment by topjohnwu** [comment]
I'm nearly 100% sure Nexus 6P is supported.
Do you have modules installed? From I'm concerned, ViPER4Android will break the device.
Or maybe you are using some custom roms?

**Comment by Buttars** [comment]
@topjohnwu How do I manually remove the sound mod, viper I think, manually after running the uninstall?

**Comment by spiral6** [comment]
@topjohnwu Only app I have is systemless SuperSU. At one point I had Xposed, but I uninstalled it. It's a generally stock rom.

**Comment by Buttars** [comment]
@spiral6 It's the remains of old magisk, if you never installed magisk, it's the old remains of root. Try unsuing and then try again.

**Comment by Serubin** [comment]
@topjohnwu This issue is present on several different Nexus 6P roms. It's appears to also be an issue with Dolby Atmos. 
It's present with Phhs superuser as well.

**Comment by Buttars** [comment]
Don't mess with anything audio, don't use 3rd part root atm at least till it's fixed.

**Comment by Serubin** [comment]
@Buttars It's not fixed. It's an issue with or without root, and with any root.

**Comment by Serubin** [comment]
@topjohnwu Any further updates? It seems that for whatever reason the entire /vendor is being wiped on boot.

Here is a logcat of boot: http://pastebin.com/ZeWqAHrM (Link due to length)

**Comment by topjohnwu** [comment]
Sorry, I'm only one person, I'll look into this issue after some other stuffs are done!

**Comment by Serubin** [comment]
@topjohnwu That's okay! All the hard work is much appreciated :)

**Comment by topjohnwu** [comment]
Vendor issue is fixed
