### ISSUE TITLE
Can't create pull request for Turkish translations.

### ISSUE THREAD

**Issue by muhammeteminturgut** [topjohnwu/Magisk#670]
I have updated the Turkish translation but i can't create pull request. Anybody help?

Updated Strings:
https://github.com/muhammeteminturgut/Magisk/blob/master/app/src/full/res/values-tr/strings.xml

**Comment by 0xXA** [comment]
Ok you need press compare button or create pull request option from GitHub web UI or sippy desktop mode on Android bro
