### ISSUE TITLE
Unable to find sepolicy rules dir

### ISSUE THREAD

**Issue by fatalcoder524** [topjohnwu/Magisk#6712]
Device: OnePlus 11 5g (CPH2447)
Android version: 13
Magisk version name: 981ccabb (25210) and 2717feac (25209)
Magisk version code: 25209 and 25210

Using Oxygen OS A.08 | Feb 5 2023 security patch

Can't install Magisk Canary 25209 and 25210. Currently using Magisk Canary 25206. Not sure if other versions work.

[magisk_install_log_2023-03-08T20.47.53.log](https://github.com/topjohnwu/Magisk/files/10922108/magisk_install_log_2023-03-08T20.47.53.log)

[magisk_install_log_2023-03-08T20.45.00.log](https://github.com/topjohnwu/Magisk/files/10922113/magisk_install_log_2023-03-08T20.45.00.log)

**Comment by yujincheng08** [comment]
should be fixed by #6691

**Comment by fatalcoder524** [comment]
The thing is I just rebooted my phone and after reboot, it says it's in 25210. Install was successfully.

**Comment by yujincheng08** [comment]
oh yeah. the first installation will show that prompt but that's not an error.

**Comment by yujincheng08** [comment]
oh wait. we may need a migration. otherwise, the first boot after upgrade will loss all sepolicy rules. let see how @vvb2060 thinks.

**Comment by vvb2060** [comment]
This is only a display issue and does not affect usage. Other issue will be discussed after #6691 merge.
