### ISSUE TITLE
Android 14 DP2 not rooted

### ISSUE THREAD

**Issue by AllenChangMusic** [topjohnwu/Magisk#6715]
Device: Pixel 7 Pro
Android version: Android 14 DP2
Magisk version name: 4709a32
Magisk version code: 25210

Boots normally, but no root with patched init_boot.
Trying again now with patching boot.img to see whether they have gone back to previous behavior (as with P6P)
Will update when more information available with logs

Reports on XDA find some P6P users suggesting that root is working, BUT app is not detecting the root.

**Comment by Tiebe** [comment]
Same issue, app doesn't report root, but when running `adb shell su` the popup does come up and gets me elevated privileges in adb shell

**Comment by Hondo77** [comment]
Are you guys actually not rooted or is the Magisk app just reporting that you are not rooted? Sounds like it may be similar to what is happening on my Pixel 6 Pro. 

https://github.com/topjohnwu/Magisk/issues/6441#issuecomment-1460721388

**Comment by AllenChangMusic** [comment]
> 

It's a bit different though. Since this is on P7P. It doesn't have anything to do with using the P7P boot image on P6P (which is a google issue). Rather, the app is not correctly detecting root which seems to be correctly patched.

**Comment by Hondo77** [comment]
> Are you guys actually not rooted or is the Magisk app just reporting that you are not rooted? Sounds like it may be similar to what is happening on my Pixel 6 Pro.
> 
> [#6441 (comment)](https://github.com/topjohnwu/Magisk/issues/6441#issuecomment-1460721388)
> 
> > 
> 
> It's a bit different though. Since this is on P7P. It doesn't have anything to do with using the P7P boot image on P6P (which is a google issue). Rather, the app is not correctly detecting root which seems to be correctly patched.
> 
> @topjohnwu @yujincheng08

Yep, I realize it doesn't have anything to do with the P7P boot image on the P6P. I just meant the part about the Magisk app saying I'm not rooted even though the apps and modules that were previously getting superuser permission are still getting them, seemingly indicating that I am indeed rooted but the Magisk app is just not reporting that.

**Comment by Tiebe** [comment]
[logcat.txt](https://github.com/topjohnwu/Magisk/files/10924783/logcat.txt)
Attached `logcat -d` of system boot

**Comment by AllenChangMusic** [comment]
Logcat says something about the app not having legacy storage. I wonder whether it has to do with the new changes to A14? It's not detecting root/modules because it's being locked out without storage permissions?

**Comment by Tiebe** [comment]
I just looked through the code, and it seems to detect root by spawning a shell and checking if that shell has root privileges. Should(?) have nothing to do with storage permissions I'd assume.

Here's another logcat from the debug build of the app:
[logcat2.txt](https://github.com/topjohnwu/Magisk/files/10924854/logcat2.txt)

**Comment by yujincheng08** [comment]
Logs here:

```
java.io.IOException: Stream Closed
	at java.io.FileOutputStream.write(FileOutputStream.java:399)
	at java.io.FileOutputStream.write(FileOutputStream.java:357)
	at java.io.DataOutputStream.writeInt(DataOutputStream.java:197)
	at com.topjohnwu.magisk.core.su.SuRequestHandler$respond$2.invokeSuspend(SuRequestHandler.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by vvb2060** [comment]
https://android-review.googlesource.com/c/platform/system/sepolicy/+/2388478

**Comment by pndwal** [comment]
Anyone tried patching init_boot.img with 25209, pre 25210 neglected mkdir in Make Private... issue?... Or with 25206, pre 25207 major selinux refactoring issues?...
