### ISSUE TITLE
BYD Dilink5.0 Android12 not running `magiskinit`

### ISSUE THREAD

**Issue by CMLNT** [topjohnwu/Magisk#6717]
Device: BYD CAR PAD Dilink5.0 780G 12+256G
Android version: 12
Magisk version name: magisk_debug
Magisk version code:25210(D)

MagiskManager not detecting Magisk 
也没有 Apk 安装图标,请帮忙看看
fastboot flash boot+vendor_boot
magisk_log+boot.img+recovery.img+magisk_boot.img+bugreport
https://drive.google.com/drive/folders/1AIm1NB58M9meQc_zRR3NmM-APY0raX9_?usp=share_link

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/10927334/app-debug.zip)
Use this version to grab bugreport.

**Comment by CMLNT** [comment]
> 



> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/10927334/app-debug.zip)
> Use this version to grab bugreport.

已经重新上传
https://drive.google.com/drive/folders/14AUMDWfZGZipgJroxkxlzmQLfk87avWd?usp=share_link

**Comment by yujincheng08** [comment]
4.0 的车也跑一下

**Comment by CMLNT** [comment]
> 4.0 的车也跑一下

https://github.com/topjohnwu/Magisk/issues/6719#issuecomment-1461330214  已重新上传

**Comment by yujincheng08** [comment]
你 patch 的 vendor_boot？有没有 init_boot？

**Comment by CMLNT** [comment]
> 你 patch 的 vendor_boot？有没有 init_boot？
这个是我从 OTG 的payload.bin 提取出来的镜像 好像没有 init_boot
cmlnt@cmlntdeMacBook-Pro Di5.0_23.1.2.2209156.1.23.2.2.2209152.2 % ls -l
total 21163496
-rwx------  1 cmlnt  staff      151552  1 30 12:17 abl.img
-rwx------  1 cmlnt  staff      208896  1 30 12:17 aop.img
-rwx------  1 cmlnt  staff     2617344  1 30 12:17 bluetooth.img
-rwx------  1 cmlnt  staff   100663296  1 30 12:17 boot.img
-rwx------  1 cmlnt  staff      188416  1 30 12:17 cpucp.img
-rwx------  1 cmlnt  staff       53248  1 30 12:17 devcfg.img
-rwx------  1 cmlnt  staff    67108864  1 30 12:17 dsp.img
-rwx------  1 cmlnt  staff    25165824  1 30 12:17 dtbo.img
-rwx------  1 cmlnt  staff       90112  1 30 12:17 featenabler.img
-rwx------  1 cmlnt  staff     3678208  1 30 12:17 hyp.img
-rwx------  1 cmlnt  staff       20480  1 30 12:17 imagefv.img
-rwx------  1 cmlnt  staff      270336  1 30 12:17 keymaster.img
-rwx------  1 cmlnt  staff   179646464  1 30 12:17 modem.img
-rwx------  1 cmlnt  staff       16384  1 30 12:17 multiimgoem.img
-rwx------  1 cmlnt  staff     1220608  1 30 12:17 odm.img
-rwx------  1 cmlnt  staff   201482240  1 30 12:17 product.img
-rwx------  1 cmlnt  staff       57344  1 30 12:17 qupfw.img
-rwx------  1 cmlnt  staff       49152  1 30 12:17 shrm.img
-rwx------@ 1 cmlnt  staff  5004414976  1 30 12:20 system.img
-rwx------  1 cmlnt  staff   390918144  1 30 12:20 system_ext.img
-rwx------  1 cmlnt  staff     3723264  1 30 12:20 tz.img
-rwx------  1 cmlnt  staff      126976  1 30 12:20 uefisecapp.img
-rwx------@ 1 cmlnt  staff  3697833225  1  1  2009 update.zip
-rwx------  1 cmlnt  staff        8192  1 30 12:20 vbmeta.img
-rwx------  1 cmlnt  staff        4096  1 30 12:20 vbmeta_system.img
-rwx------  1 cmlnt  staff  1051430912  1 30 12:20 vendor.img
-rwx------  1 cmlnt  staff   100663296  1 30 12:20 vendor_boot.img
-rwx------  1 cmlnt  staff     3670016  1 30 12:20 xbl.img
-rwx------  1 cmlnt  staff      225280  1 30 12:20 xbl_config.img

**Comment by CMLNT** [comment]
更新分区信息
cmlnt@cmlntdeMacBook-Pro boot_editor_v13r2 % adb shell ls -l /dev/block/by-name
total 0
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 ALIGN_TO_128K_1 -> /dev/block/sdd1
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 ALIGN_TO_128K_2 -> /dev/block/sdf1
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 abl_a -> /dev/block/sde8
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 abl_b -> /dev/block/sde32
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 aop_a -> /dev/block/sde1
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 aop_b -> /dev/block/sde25
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 apdp -> /dev/block/sde50
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 bluetooth_a -> /dev/block/sde5
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 bluetooth_b -> /dev/block/sde29
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 boot_a -> /dev/block/sde11
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 boot_b -> /dev/block/sde35
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 cancollect -> /dev/block/sda15
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 catecontentfv -> /dev/block/sde62
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 catefv -> /dev/block/sde61
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 cdt -> /dev/block/sdd2
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 cluster -> /dev/block/sda13
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 collect -> /dev/block/sda11
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 collect2 -> /dev/block/sda12
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 connsec -> /dev/block/sde65
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 cpucp_a -> /dev/block/sde20
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 cpucp_b -> /dev/block/sde44
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 ddr -> /dev/block/sdd3
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 devcfg_a -> /dev/block/sde12
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 devcfg_b -> /dev/block/sde36
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 devinfo -> /dev/block/sde48
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 dip -> /dev/block/sde49
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 dsp_a -> /dev/block/sde9
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 dsp_b -> /dev/block/sde33
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 dtbo_a -> /dev/block/sde15
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 dtbo_b -> /dev/block/sde39
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 featenabler_a -> /dev/block/sde21
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 featenabler_b -> /dev/block/sde45
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 frp -> /dev/block/sda5
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 fsc -> /dev/block/sdf5
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 fsg -> /dev/block/sdf4
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 hyp_a -> /dev/block/sde3
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 hyp_b -> /dev/block/sde27
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 imagefv_a -> /dev/block/sde17
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 imagefv_b -> /dev/block/sde41
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 keymaster_a -> /dev/block/sde10
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 keymaster_b -> /dev/block/sde34
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 keystore -> /dev/block/sda4
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 limits -> /dev/block/sde52
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 limits-cdsp -> /dev/block/sde53
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 logdump -> /dev/block/sde57
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 logfs -> /dev/block/sde55
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 mdcompress -> /dev/block/sde64
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 mdtp_a -> /dev/block/sde7
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 mdtp_b -> /dev/block/sde31
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 mdtpsecapp_a -> /dev/block/sde6
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 mdtpsecapp_b -> /dev/block/sde30
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 metadata -> /dev/block/sda9
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 misc -> /dev/block/sda3
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 modem_a -> /dev/block/sde4
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 modem_b -> /dev/block/sde28
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 modemst1 -> /dev/block/sdf2
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 modemst2 -> /dev/block/sdf3
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 multiimgoem_a -> /dev/block/sde19
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 multiimgoem_b -> /dev/block/sde43
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 oems -> /dev/block/sda14
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 persist -> /dev/block/sda2
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 qmcs -> /dev/block/sde23
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 quantumsdk -> /dev/block/sde56
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 qupfw_a -> /dev/block/sde13
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 qupfw_b -> /dev/block/sde37
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 qweslicstore_a -> /dev/block/sde24
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 qweslicstore_b -> /dev/block/sde47
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 rawdump -> /dev/block/sda10
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 rtice -> /dev/block/sde67
lrwxrwxrwx 1 root root 14 2023-03-10 08:03 sda -> /dev/block/sda
lrwxrwxrwx 1 root root 14 2023-03-10 08:03 sdb -> /dev/block/sdb
lrwxrwxrwx 1 root root 14 2023-03-10 08:03 sdc -> /dev/block/sdc
lrwxrwxrwx 1 root root 14 2023-03-10 08:03 sdd -> /dev/block/sdd
lrwxrwxrwx 1 root root 14 2023-03-10 08:03 sde -> /dev/block/sde
lrwxrwxrwx 1 root root 14 2023-03-10 08:03 sdf -> /dev/block/sdf
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 secdata -> /dev/block/sde60
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 shrm_a -> /dev/block/sde18
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 shrm_b -> /dev/block/sde42
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 splash -> /dev/block/sde51
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 ssd -> /dev/block/sda1
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 storsec -> /dev/block/sde58
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 super -> /dev/block/sda6
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 toolsfv -> /dev/block/sde54
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 tz_a -> /dev/block/sde2
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 tz_b -> /dev/block/sde26
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 tzsc -> /dev/block/sde66
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 uefisecapp_a -> /dev/block/sde16
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 uefisecapp_b -> /dev/block/sde40
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 uefivarstore -> /dev/block/sde59
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 userdata -> /dev/block/sda16
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 vbmeta_a -> /dev/block/sde14
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 vbmeta_b -> /dev/block/sde38
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 vbmeta_system_a -> /dev/block/sda7
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 vbmeta_system_b -> /dev/block/sda8
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 vendor_boot_a -> /dev/block/sde22
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 vendor_boot_b -> /dev/block/sde46
lrwxrwxrwx 1 root root 16 2023-03-10 08:03 vm-data -> /dev/block/sde63
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 xbl_a -> /dev/block/sdb1
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 xbl_b -> /dev/block/sdc1
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 xbl_config_a -> /dev/block/sdb2
lrwxrwxrwx 1 root root 15 2023-03-10 08:03 xbl_config_b -> /dev/block/sdc2

**Comment by yujincheng08** [comment]
所以 patch 的是 boot 并且刷到 boot_a 和 boot_b  上了吗

**Comment by CMLNT** [comment]
> 

同时 2刷到了 a 和 b 分区

**Comment by yujincheng08** [comment]
竟然能 adb

那 /system/xbin/su 是不是能 root？

**Comment by CMLNT** [comment]
> 竟然能 adb
> 
> 那 /system/xbin/su 是不是能 root？

似乎是不行的
DiLink5.0:/ $  /system/xbin/su 
/system/bin/sh: /system/xbin/su: inaccessible or not found
127|DiLink5.0:/ $

**Comment by CMLNT** [comment]
我刚刚使用昨天的 debug 版本 patch 了 dilink5 都刷新了 boot a b 现在两个车机都死在开机画面了hhh

**Comment by yujincheng08** [comment]
Should be the same compatibility problem with #6719.
