### ISSUE TITLE
Titanium Backup Problem

### ISSUE THREAD

**Issue by deadmans96** [topjohnwu/Magisk#672]
Titanium Backup app doesn't recognize the root access with Magisk it doesn't show the Magisk permession popup when i open it.
Possibly i assure that because of that program checks out for root files in xbin folder

**Comment by DenyDarko** [comment]
Drop this abandonware and use Swift Backup.

**Comment by neekless** [comment]
I'm using magisk and my titanium backup recognizes root access with no problems. What version of magisk are you running?

**Comment by storm49152** [comment]
I was having the same issue and tried various without success. But I just stumbled on this, and that worked perfectly:
https://www.reddit.com/r/Nexus6P/comments/6f1rgj/titanium_backup_crashes_on_me_with_712_installed/

Basically:
- Uninstall TB
- Make sure TB is not listed in MM.
- Use a root explorer to delete /data/data/com.keramidas.TitaniumBackup
- Reinstall TB
And when you now start TB is should ask for root access again (that is, it did for me).

**Comment by storm49152** [comment]
I do however get a message from TB:

Your SU binary (version "17.2:MAGISKSU (topjohnwu)") is functional but might now work reliably on some Android 4.3+ ROMs. If you encouter any issues in TB, please try SuperSU instead.

I've never seen issues with TB and Magisk, so I think it's safe to ignore.

**Comment by topjohnwu** [comment]
Obviously not a Magisk issue :)

**Comment by Emulatorer** [comment]
Same issue here magisk can't grant supersu because titanium backup didn't detect supersu in magisk 😅

**Comment by gloeyisk** [comment]
> Same issue here magisk can't grant supersu because titanium backup didn't detect supersu in magisk

It does for me. Screenshot attached.
![IMG_20191005_213936](https://user-images.githubusercontent.com/43908341/66256658-4b9ca080-e7ba-11e9-8c15-68135b74dadb.jpg)

**Comment by Emulatorer** [comment]
![Screenshot_20191006-000713](https://user-images.githubusercontent.com/37603562/66257650-77c21c80-e7ce-11e9-8b8e-33439c414cfa.png)
![Screenshot_20191006-000955](https://user-images.githubusercontent.com/37603562/66257653-7ee92a80-e7ce-11e9-8b80-4401a056e708.png)

**Comment by gloeyisk** [comment]
@Emulatorer ehich TiBu app do you install? The one from Play or pirated ones? I bought these Pro Key app and never face such issue. Tried with SuperSU (long ago), losSU (Lineage root add-on), now with Magisk and everything seems to be working fine.
I hope you use the Play one.

**Comment by Emulatorer** [comment]
It's came from playstore :(

**Comment by gloeyisk** [comment]
> It's came from playstore :(

Try to reinstall the app, hope it help.

**Comment by Shad0wSmurf** [comment]
Use the android busy box module. Titanium is looking at, (now this is just going off your images btw.) /system/bin/su, but root chexker noticed that there is the root succeeded with /system/xbin/su.

Try the busy box from the play store, install it on the system/bin directory

**Comment by Emulatorer** [comment]
Nothing changes :<
![Screenshot_20191006-130535](https://user-images.githubusercontent.com/37603562/66264557-16d02e00-e83a-11e9-9640-31a449b58492.png)
![Screenshot_20191006-130500](https://user-images.githubusercontent.com/37603562/66264558-1d5ea580-e83a-11e9-98fd-0e274ffdbc0a.png)

**Comment by Shad0wSmurf** [comment]
https://github.com/Magisk-Modules-Repo/busybox-ndk

**Comment by Emulatorer** [comment]
@Shad0wSmurf I already use that :<
[Uploading Screenshot_20191006-222557.png…]()

**Comment by MokkoBird** [comment]
Even if this thread is a little older, my soultion was a different. titaniumBackup was using the wrong su-binary. 
Solution:
1) open a terminal 
2) type "which su" and see if it points to the same binary (in your case /system/bin/su)
3) if not, reboot in recovery, rename /system/bin/su and restart
(4) you might need to reinstall Titanium Backup and clear the data folder)

**Comment by CapitalF** [comment]
> I know I'm five years later but I suffered this issue with Android 14 and solved it easily: I entered preferences -> last option (something like "other preferences to solve problems, it's different in my language) and checked the "force system busybox".
> 
> I don't recommend the app for backups as it wasn't updated in five years, but for me is still useful to manage apps.

I was just trying to load up TiBackup today on my LineageOS 21/Android 14 Pixel 8 and it seems to be running into the same issue, but your fix isn't working for me.

I think TiBackup is finally dead to me.

**Comment by Hammerhand17** [comment]
Have you installed "BusyBox for Android NDK" module?

**Comment by KlausHans** [comment]
Installing BusyBox for Android NDK and then applying "force system busybox" works, thanks!
Got the module from the zipUrl in the update.json: https://xdaforums.com/attachments/update-busybox-installer-v1-36-1-all-signed-zip.6000117/

**Comment by Dustbunny76** [comment]
Pixel 9 on Android 15.  Thank you KlausHans. The update fixed it.  Its a magisk module, install from Magisk.
