### ISSUE TITLE
Fix magisk --daemon and su --mount-master parameters

### ISSUE THREAD

**Issue by WandersonKalil** [topjohnwu/Magisk#6724]
Allow to start the su/daemon with init's mount namespace without rebooting the phone after magiskd has been killed.

Adjust switch_mnt_ns() to open(/proc/1/ns/mnt) if --mount-master is set, to prevent the daemon/su session from inherinting the caller's mount namespace from Terminal Emulator/ADB Shell.

Device: S20 FE
Android version: 12
Magisk version name: 981ccab (25210)
Magisk version code: 25210

**Comment by vvb2060** [comment]
It is undefined behavior for a process other than init to start magiskd.

**Comment by WandersonKalil** [comment]
Are you saying that the --daemon option is useless for any other process aside from init? But if the user chooses  to start the daemon manually (as stated in the magisk --help option? 


If the daemon is started manually, it will inherit the caller's mount namespace instead of init's mount namespace, breaking apps (file managers) which expects the full view of files after calling su --mount-master.

**Comment by vvb2060** [comment]
The meaning of --mount-master is the same as magiskd, it does not mean init, nor does it mean full view.

**Comment by vvb2060** [comment]
#6673 We are planning to hide the internal details of magiskd from init's mount namespace.

**Comment by WandersonKalil** [comment]
> The meaning of --mount-master is the same as magiskd, it does not mean init, nor does it mean full view.

@vvb2060 

su --mount-master means that the caller's app/process will inherit the init't mount namespace instead of its own mount namespace.  By inherinting the init's mount namespace, the app/process will get full view of filesystem (for example, when opening /data/data/). If the app/process inherit its own mount namespace, it will see only its own package name and the app/process package name which started the daemon.

**Comment by vvb2060** [comment]
https://en.m.wikipedia.org/wiki/Undefined_behavior

**Comment by WandersonKalil** [comment]
> #6673 We are planning to hide the internal details of magiskd from init's mount namespace.

@vvb2060  By calling:

_xunshare(CLONE_NEWNS); xmount(nullptr, MAGISKTMP.data(), nullptr, MS_PRIVATE | MS_REC, nullptr);_

you are creating a private mount namespace, ignoring the --mount-master and the global mount namespace mode in the magisk app.

**Comment by yujincheng08** [comment]
magisk's busybox provides nsenter

**Comment by yujincheng08** [comment]
nsenter -t 1
magisk --daemon
su -M

solved

**Comment by WandersonKalil** [comment]
> nsenter -t 1
> magisk --daemon
> su -M
> 
> solved

@yujincheng08  Developers will never call nsenter, but su --mount-master instead.

**Comment by yujincheng08** [comment]
i did use su -M

**Comment by WandersonKalil** [comment]
> i did use su -M

@yujincheng08 As already stated, calling su -M/-mm/--mount-master alone does not work.

**Comment by yujincheng08** [comment]
why not?
`nsenter -t 1 magisk --damon` makes the new magiskd runs under init's ns. thus su -M will thus work again.

**Comment by WandersonKalil** [comment]
> why not?
> `nsenter -t 1 magisk --damon` makes the new magiskd runs under init's ns. thus su -M will thus run under init's ns.
> 

nsenter works  as expeceted, but not su when called alone (without nsenter).  Nobody will call `nsenter -t 1 magisk --damon`. The call is `magisk --daemon`.

**Comment by yujincheng08** [comment]
nah. magiskd is expected to run under init's ns. so its the caller's responsibility to launch magiskd in correct ns.

**Comment by yujincheng08** [comment]
launching magiskd in other ns is undefined behaviour, and it wont be supported.

**Comment by WandersonKalil** [comment]
> launching magiskd in other ns is undefined behaviour, and it wont be supported.

@yujincheng08 You are wrong.  We are not wanting to launch the daemon into another mount namespace different from init's mount namespace. If we don't open and setns to init's mount namespace, the --daemon and --mount-master becomes obsolete/useless.

**Comment by vvb2060** [comment]
@yujincheng08 

> It is undefined behavior for a process other than init to start magiskd.

Not other namespaces, but it should not be started.  magiskd is designed not to die, if magiskd crashed it should be fixed.

**Comment by WandersonKalil** [comment]
> to solve this problem, you should launch magiskd in the correct ns by using nsenter.

Again, nobody will use nsenter to call magisk or su.

**Comment by yujincheng08** [comment]
i will definitely call nsenter.

also, magisk mount wont work if magiskd is not working under init's ns. so if you are in a different ns and want to launch magiskd, you should use nsenter. if u dont do so, it's unexpected how magiskd works.

**Comment by yujincheng08** [comment]
its the caller's responsibility to make sure that `magisk --daemon` is executed under the correct environmnent. that is, uid=0, full capability, enough selinux permission to switch to u:r:magisk:s0, workdir is magisktmp, using the same file as su, etc.

its behavior is undefined if one of the aforementioned conditions is not satisfied.

**Comment by yujincheng08** [comment]
its wrong to think that a simple call of `magisk --daemon` is enough to launch a magiskd. it indeed requires a lot of steps.

https://github.com/topjohnwu/Magisk/blob/master/scripts/avd_magisk.sh

NOBODY will call `magisk --daemon` without any preparation.

**Comment by WandersonKalil** [comment]
@yujincheng08 @vvb2060  @topjohnwu 

We should not handle mount namespaces in the daemon itself, only in the child process. If you set the mount namespace to private in the daemon, all su sessions will inherit the new created daemon's mount namespace instead init's mount namespace, breaking the --mount-master option (used by file manager apps or Link2SD (which ls -l /data/data/* for apps size of files/cache/database). Magisk app itself uses the --mount-master option and gets stuck into a green screen after discovering that the mount namespace is not init's mount namespace (the magisk app readlink(/proc/self/ns/mnt) and readlink(/proc/1/ns/mnt) and compare the two results, if the results are different, it gets stuck in the green splash screen.

**Comment by yujincheng08** [comment]
Didn't you understand magiskd is designed to run in init's mount namespace?

**Comment by WandersonKalil** [comment]
> Didn't you understand magiskd is designed to run in init's mount namespace?

Yes, but if the daemon gest killed?

**Comment by yujincheng08** [comment]
@WandersonKalil even if it gets killed, shouldn't the restarted one run in init's mount namespace?

**Comment by WandersonKalil** [comment]
> @WandersonKalil even if it gets killed, shouldn't the restarted one run in init's mount namespace?

@yujincheng08 it should, but doesn't.  By  the restarted daemon process will inherit     the mount namespace of the process that started it. Thus the need to open /proc/1/ns/mnt and call setns() so that the daemon inherit the init's mount namespace  again instead of the caller's mount namespace.

**Comment by yujincheng08** [comment]
@WandersonKalil Because it assumes the caller starts the daemon under init's namespace. So why not starts it under init's namespace?

**Comment by yujincheng08** [comment]
@WandersonKalil Why are u ignoring my previous comment: https://github.com/topjohnwu/Magisk/issues/6724#issuecomment-1462339337?

**Comment by yujincheng08** [comment]
@WandersonKalil You should launch magisk daemon by `nsenter`. Everybody is doing so except for you!

**Comment by WandersonKalil** [comment]
> @WandersonKalil Because it assumes the caller starts the daemon under init's namespace. So why not starts it under init's namespace?

"Caller" is any app/process/program that call su --daemon or su --mount-master. If the daemon's caller is init, the daemon will inherit the init's mount namespace.  However, if the the caller is any other app/process/program, the daemon will inherit the app/process/program that started the daemon (makink all calls to su --mount-master inherit that mount namespace instead of init's mount namespace. In order to fix that unexpected  behavior, we need to open(/proc/1/ns/mnt) and call setns() so we regain init's mount namespace again.

**Comment by yujincheng08** [comment]
@WandersonKalil It's the caller's responsibility to switch the ns, not magisk

**Comment by WandersonKalil** [comment]
> @WandersonKalil You should launch magisk daemon under init's mount namespace. Everybody is doing so except for you!

This is possible only if the daemon is not killed. If it is killed, the only way to get init's mount namespace again is rebooting the phone.

**Comment by yujincheng08** [comment]
@WandersonKalil As I said, nsenter works. But you dont wanna do so. So, blame whom?

**Comment by yujincheng08** [comment]
btw, magisk daemon requires root. if it gets killed, you wont hv root anymore, and u wont be able to start magisk daemon again.

**Comment by vvb2060** [comment]
> Magisk app itself uses the --mount-master option and gets stuck into a green screen after discovering that the mount namespace is not init's mount namespace (the magisk app readlink(/proc/self/ns/mnt) and readlink(/proc/1/ns/mnt) and compare the two results, if the results are different, it gets stuck in the green splash screen.

Stop lying, it works fine.

**Comment by WandersonKalil** [comment]
> Didn't you understand magiskd is designed to run in init's mount namespace?

@yujincheng08 @vvb2060  is wanting to make the daemon's mount namespace private/isolated, which will  obviously fully break  the already broken --mount-master option.

**Comment by WandersonKalil** [comment]
> > Magisk app itself uses the --mount-master option and gets stuck into a green screen after discovering that the mount namespace is not init's mount namespace (the magisk app readlink(/proc/self/ns/mnt) and readlink(/proc/1/ns/mnt) and compare the two results, if the results are different, it gets stuck in the green splash screen.
> 
> Stop lying, it works fine.

@vvb2060  I have tested it and it doesn't work.

**Comment by vvb2060** [comment]
Stop lying, myself, and all magisk alpha users can open magisk app.

**Comment by WandersonKalil** [comment]
> Stop lying, myself, and all magisk alpha users can open magisk app.

@vvb2060 I'm not lying.  The Magisk app really gets stuck in the splash screen after comparing /proc/self/ns/mnt and discovered that result is different from /proc/1/ns/mnt.

**Comment by WandersonKalil** [comment]
@topjohnwu @vvb2060 @yujincheng08  The bug really exists. So, why not fix it?

**Comment by vvb2060** [comment]
Interesting, I found no code in the magisk and libsu source code that would cause this behaviour. And I can open app normally.

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/libsu/commit/25cf6df6322006f9eba3d9df0f2cef8928251d0f This code was submitted by me, it does have semantic issue now, I think it should be possible to remove the ROOT_MOUNT_MASTER flag.

**Comment by WandersonKalil** [comment]
> Interesting, I found no code in the magisk and libsu source code that would cause this behaviour. And I can open app normally.

@vvb2060 

Steps to reproduce:

1: open Terminal Emulator and call su;
2: find and kill the magiskd process;
3: start the magiskd with magisk --daemon;
4: Try to open the Magisk app and it will get stuck in the splash screen due to this bug I'm speaking.

**Comment by vvb2060** [comment]
Steps to reproduce:

1: open Terminal Emulator and call su -mm;
2: find and kill the magiskd process;
3: start the magiskd with magisk --daemon;
4: work fine

**Comment by WandersonKalil** [comment]
@vvb2060 Yes, I'm using 25210. I don't know why, but the Magisk app gets stuck after calling magisk -V, even though the results of /proc/self/ns/mnt and /proc/1/ns/mnt are equal after killing and restarting the daemon.

**Comment by WandersonKalil** [comment]
@vvb2060 Could you  point me to the source code we the Magisk app call magisk -v and magisk -V?

**Comment by vvb2060** [comment]
> correct steps:
1: open Terminal Emulator and call su -mm;
2: find and kill the magiskd process;
3: start the magiskd with /sbin/magisk --daemon;

Oh, sorry I forgot to copy stub.apk, any way, start magiskd is a complicated thing. https://github.com/topjohnwu/Magisk/issues/6724#issuecomment-1462354437 

> It is undefined behavior for a process other than init to start magiskd.

**Comment by vvb2060** [comment]
Correct again, the reason for the stuck should be zygisk status error.

**Comment by WandersonKalil** [comment]
> https://github.com/topjohnwu/libsu/commit/25cf6df6322006f9eba3d9df0f2cef8928251d0f This code was submitted by me, it does have semantic issue now, I think it should be possible to remove the ROOT_MOUNT_MASTER flag.

The ROOT_MOUNT_MASTER flag is an interesting construct, so you don't need to remove it.

**Comment by WandersonKalil** [comment]
@vvb2060 I found the Magisk app is blocking  on the splash screen after calling  magisk -V.

For some reason, the Magisk app does not work when I give it intant/automatic root access. Interestingly, if I give it 1 second prior to allowing it root access, it works perfectly with no blocking on the splash screen. So, the fix for the Magisk app blocking on the splash screen is sleep(1) prior to giving it root access.
