### ISSUE TITLE
Support for motorola phones one more time 

### ISSUE THREAD

**Issue by 404neko** [topjohnwu/Magisk#6732]
Device: Moto Z (XT1650)
Android version: 8.0
Magisk version name: Magisk v25.2
Magisk version code: 25210

I believe that some maintainers have heard a little about the "motorola boot issues after install Magisk"
Like this #5415

I found a patched patched Magisk flashable zip and 2 functions inside it:

```
manufacturer_detect() {
  MANUFACTURER=`grep_prop ro.product.manufacturer`
  ISMOTO=false
  if [ "$MANUFACTURER" = "Motorola" -o "$MANUFACTURER" = "motorola" ]; then ISMOTO=true; fi;
}

fuck_motorola() {
  ui_print "- Fuck Motorola hab/verify protect"
  mount -o rw,remount /system
  mount -o rw,remount /vendor
  rm -rf /system/vendor/etc/init/hw/init.mmi.hab.rc
  rm -rf /vendor/etc/init/hw/init.mmi.hab.rc
  sed -i "s@,verify@@g" /system/vendor/etc/fstab.qcom
  sed -i "s@,verify@@g" /vendor/etc/fstab.qcom
}
```

manufacturer_detect is executed after 
```
$BOOTMODE || remove_system_su 
```
and
 
$ISMOTO || fuck_motorola is executed after 
```
install_magisk
```

wish officially support for motorola phones 🥺
I think non-patched magisk will kill my phone ( 

Append:
I try to patch Magisk 25.2 using code above and seems success, but installed pack keep uninstalling because enforcing of certificate,
wish officially support for motorola phones for one more time

**Comment by vvb2060** [comment]
https://dumps.tadiphone.dev/dumps/motorola/deen_sprout/-/blob/10-QPK30.51-bffa2-release-keys/vendor/bin/init.mmi.hab.sh

It doesn't look like this script is causing any problems.

**Comment by vvb2060** [comment]
https://dumps.tadiphone.dev/dumps/motorola/deen_sprout/-/blob/10-QPK30.51-bffa2-release-keys/vendor/etc/init/hw/init.mmi.hab.rc

/vendor/bin/init.mmi.hab.sh can be easily overridden with magisk module.

**Comment by yujincheng08** [comment]
The init.rc you removed is to disable partition verification for vendor and system. But Magisk never modifies vendor and system partitions. So your boot issue isn't caused by Magisk but your modification of vendor and system.

**Comment by 404neko** [comment]
> The init.rc you removed is to disable partition verification for vendor and system. But Magisk never modifies vendor and system partitions. So your boot issue isn't caused by Magisk but your modification of vendor and system.

I compared my system partition and factory image, it did modified by some 3rd software, I am sorry for my bothering

**Comment by illgetit87** [comment]
Hi, sorry I sent you a log file without explaining why. I was wondering if
everything is working fine. I own Motorola moto g pure. I hope the email
with the log file made any sense. I'm really new at Andriod developer.  I
hope thing are working well and I'm wondering how I install the patch.zip
file. I hope you can take time to out of your busy schedule to help me and
give me some pointers. Thanks and hope to hear from you soon
