### ISSUE TITLE
Systemless hosts file feature is broken on latest Canary build

### ISSUE THREAD

**Issue by gjf** [topjohnwu/Magisk#6738]
Device: Any (checked on OPT7Pro, Xiaomi 11 Lite 5G NE)
Android version: A12, A13
Magisk version name: 981ccabb(25210)
Magisk version code: 981ccabb(25210)

Systemless hosts file feature is broken - hosts file applying does not work.

Ways to reproduce:
1. Enable systemless hosts file module in magisk settings.
2. Reboot.
3. Install any hosts file altering app - AdAway is a good example.
4. Try to enable AdAway - it will download default hosts filters, build hosts file and show the error when trying to apply it.

Latest stable build (25200) works well so far.

**Comment by osm0sis** [comment]
Yep, already fixed upstream.

**Comment by Displax** [comment]
> > wait for 25211
> 
> Just to let you know: 25211 is still affected.
> 
> Don't update and wait for 25212? )))

https://github.com/topjohnwu/Magisk/pull/6817

**Comment by gjf** [comment]
So after reports about a bug DevTeam fixed it with a typo?
And we have waited for this fix for over a month - and nobody found this typo?
Nice!
Something is rotten in the state of Denmark...

**Comment by vladuhin** [comment]
Still broken in 25211, log says magisk try mounting /data/adb/moduleshosts/system/etc/hosts (yes, without slash / ), viper4fx same

**Comment by xerta555** [comment]
> Still broken in 25211, log says magisk try mounting /data/adb/moduleshosts/system/etc/hosts (yes, without slash / ), viper4fx same

Bootloop on my side with the new canary version of today: when i unlock my device after the bootanimation, my device constantly do a soft reboot, back to `25209` fix my issue like with the `25210` version (due to another issue).

The gas plant is getting complicated apparently..
