### ISSUE TITLE
Dialog drawing in MM is making some weird glitch. 

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#675]
Well, I'm not sure how to describe this in a good way for someone to understand so I just uploaded a screen record (as zip, mp4 is not supported by github). 

[mobizen_20181013_132847.zip](https://github.com/topjohnwu/Magisk/files/2475353/mobizen_20181013_132847.zip)

OnePlus 6, Open Beta 4.

Latest Canary MagiskManager.

**Comment by neekless** [comment]
Have also experienced this when viewing module readmes in the downloads section.

Video in link:
https://drive.google.com/open?id=1rZmecfS2wgxSzJT7ERuXy_asXgDl9lDZ

**Comment by topjohnwu** [comment]
This is a bug in your system's webview implementation. The whole UI of the README is rendered by system webview.
