### ISSUE TITLE
#654提交合并後，magisk可以在nubia上使用但模塊無法安裝

### ISSUE THREAD

**Issue by youyim123** [topjohnwu/Magisk#676]
https://github.com/topjohnwu/Magisk/pull/654 這個提交合并後可以在nubia(zte) Android O設備上使用，但是在Nubia Z18（sdm845）上卻無法安裝模塊，由於Z18的data分區使用的是f2fs格式，所以在twrp裏嘗試刷入F2FS_Loopback_Bug_Workaround-2018.10.9.zip，卻無法成功刷入。同樣為f2fs格式的Nubia red magic(MSM8998)卻可以直接正常使用magisk各功能。如果你需要任何幫助請聯係我，感謝！安裝的是這個版本magisk https://github.com/kantjer/MagiskFiles/raw/master/Magisk-v17.3.r8-2018101310.zip
libc: Access denied finding property "persist.vendor.dpm.feature" 
[log.zip](https://github.com/topjohnwu/Magisk/files/2475420/log.zip)

**Comment by youyim123** [comment]
17.3-e1a65276版本依舊這樣，而且MagiskManager刷入界面點擊關閉無效。
![screenshot_2018-10-17-20-27-56](https://user-images.githubusercontent.com/19865880/47086363-d6a02600-d24b-11e8-9182-96db1207f8b5.png)
[magisk_install_log_20181017_202710.log](https://github.com/topjohnwu/Magisk/files/2487370/magisk_install_log_20181017_202710.log)
[magisk_install_log_20181017_161131.log](https://github.com/topjohnwu/Magisk/files/2487371/magisk_install_log_20181017_161131.log)
[magisk_log_20181017_202544.log](https://github.com/topjohnwu/Magisk/files/2487372/magisk_log_20181017_202544.log)

**Comment by topjohnwu** [comment]
I cannot fix your broken F2FS driver in your device's kernel. Either switch to EXT4, or flash an updated custom kernel.
