### ISSUE TITLE
Magisk does not work on A14 DP2 

### ISSUE THREAD

**Issue by wine97** [topjohnwu/Magisk#6766]
Hello, I recently tried to root my pixel, but unfortunately the root doesn't work at the moment It doesn't matter if I try it via boot.img or init_boot.img 

Device: Pixel 7 Pro
Android version: Android 14 UPP2 (UPP2.230217.004)
Magisk version name: 25.2
Magisk version code: 25210

**Comment by Displax** [comment]
https://github.com/topjohnwu/Magisk/issues/6715

**Comment by diosvany** [comment]
> Ok it still Not fixed thx

Im having the same issue if you use any root checker from the play store it will confirm that you are rooted but magisk say otherwise

**Comment by canyie** [comment]
Download and install latest CI build (which have fixed this issue): https://github.com/topjohnwu/Magisk/actions/runs/4465470061
