### ISSUE TITLE
Issues running with "Anbox"

### ISSUE THREAD

**Issue by ShapeShifter499** [topjohnwu/Magisk#678]
Anbox is a full Android setup working under Linux in it's own container. It shares the same kernel with whatever Linux install you have. More information can be found at https://anbox.io/

Right now an alternative root solution SuperSU appears to work fine, https://github.com/anbox/anbox/issues/894

But since Anbox doesn't have a bootloader I'm not quite sure how to get Magisk working. I feel like it should be able to run, it just fails to install because it's looking for a bootloader image to patch. If anyone has any further ideas, it would be appreciated.

**Comment by ShapeShifter499** [comment]
@topjohnwu Any possibility of this happening?  This would help with apps that could run but refuse because the setup is tripping SafetyNet

**Comment by topjohnwu** [comment]
As long as you can replace `/init` with `magiskinit`, and make sure it has a writable `rootfs`, Magisk can be installed very easily

**Comment by ShapeShifter499** [comment]
@topjohnwu Ok I figured how to extract the busybox used and everything is installed to /data/adb/magisk with /init replaced with magiskinit. Now Anbox is hanging at starting init with no helpful error messages. 

Below is the latest log from Anbox.
```
+ echo 'Waiting for filesystem being prepared ...'
Waiting for filesystem being prepared ...
+ wait 2
+ prepare_filesystem
+ '[' ! -e /dev/qemu_pipe ']'
+ chown system:system /dev/qemu_pipe
+ chmod 0666 /dev/qemu_pipe
+ '[' ! -e /dev/qemu_trace ']'
+ continue
+ '[' ! -e /dev/goldfish_pipe ']'
+ continue
+ '[' ! -e '/dev/input/*' ']'
+ continue
+ echo 'Starting real init now ...'
Starting real init now ...
+ /init
```

**Comment by ShapeShifter499** [comment]
I should add that the "rootfs" used in Anbox is technically not writable when booted and running. One has to generate a new "rootfs" image or unpack it and edit it directly (from what I know). 

i.e. ```sudo unsquashfs android.img```  then edit the files and repack ```sudo mksquashfs squashfs-root android.img -b 131072 -comp xz -Xbcj ia64```

**Comment by TitusLabienus** [comment]
Did anybody make progress with running Anbox together with Magisk?

**Comment by ShapeShifter499** [comment]
@TitusLabienus not yet no. I'd love someone to pickup and try to make it work.

**Comment by brucbr** [comment]
@ShapeShifter499 you can enable a rootfs overlay and place files in the corresponding directory. 

@topjohnwu Do you mean to literally just replace the init file with the magiskinit file with identical ownership and permissions?

**Comment by ShapeShifter499** [comment]
@brucbr I tried but it doesn't do anything. I really think you need magiskinit in place of the init file.  So either replace the init of the whole linux system you are on (which I think might break stuff)  or find a way to run a separate init just for anbox making it the magiskinit.

**Comment by brucbr** [comment]
Mine hangs on /init

I did do some messing around earlier, doing a fresh install of anbox.

**Comment by ShapeShifter499** [comment]
@brucbr are you trying to run magiskinit as the init?   how?

**Comment by brucbr** [comment]
As stated before, rootfs overlay

**Comment by ShapeShifter499** [comment]
@brucbr I don't know what else to do here honestly

**Comment by michele-perrone** [comment]
Any update on this?
