### ISSUE TITLE
Why Magisk canary is still on 981ccabb, it's been weeks since the basic function breaking mounting bug on it was fixed

### ISSUE THREAD

**Issue by Originalimoc** [topjohnwu/Magisk#6781]
Device: doesn't matter
Android version: 13
Magisk version name: 981ccabb
Magisk version code: 25210

**Comment by yujincheng08** [comment]
jhon has been busy recently. dont urge.

**Comment by Originalimoc** [comment]
Not urge, can just stay at previous version
