### ISSUE TITLE
Lsplt updates will cause the Shamiko module to hide China Life Insurance

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#6784]
Device:redmi note11pro
Android version:12
Magisk version name:87e036a1:MAGISK:D
Magisk version code:25210
[log.txt](https://github.com/topjohnwu/Magisk/files/11053506/log.txt)

https://github.com/topjohnwu/Magisk/commit/87e036a1906389de9f4c5566493aca15ac096dc8

I compiled and tested it myself

This submission of lsplt will cause the Shamiko module to hide the logo of the "中国人寿寿险" on the first screen of the app

Other apps have hidden effects that don't work. This may not be true. But my China Life Insurance has indeed expired

**Comment by androiddisk** [comment]
[base.zip](https://github.com/topjohnwu/Magisk/files/11053519/base.zip)
[base.z01.zip](https://github.com/topjohnwu/Magisk/files/11053521/base.z01.zip)
[base.z02.zip](https://github.com/topjohnwu/Magisk/files/11053522/base.z02.zip)
[base.z03.zip](https://github.com/topjohnwu/Magisk/files/11053526/base.z03.zip)
[base.z04.zip](https://github.com/topjohnwu/Magisk/files/11053528/base.z04.zip)
[base.z05.zip](https://github.com/topjohnwu/Magisk/files/11053530/base.z05.zip)

**Comment by androiddisk** [comment]
I uploaded the app with the test card in the logo on the first screen

Due to the lack of support for large file uploads and some suffixes, I can only rename them after being compressed into volumes.



Please rename base.z01.zip to base.z01 after downloading



Thank you for your efforts

**Comment by yujincheng08** [comment]
because that versiom of lsplt introduce extra logs. disabling the log solves the problem.
