### ISSUE TITLE
Bootloop upon fastboot installation with FP3-8901.4.A.0021.0-gms-0b368514-user

### ISSUE THREAD

**Issue by Stygian88** [topjohnwu/Magisk#6786]
Device: Fairphone 3+ (FP3)
Android version: 11
Magisk version name: 981ccabb (D)
Magisk version code: 25210

FP3-8901.4.A.0021.0-gms-0b368514-user has introduced retrofitted Dynamic Partitions to the fairphone 3(+) and when preforming the update via fastboot boot.img patching results in a bootloop of the device until a counter is hit and the device is booted into fastboot.
Checking Fairphone's forurms preforming the update via ota from FP3-8901.4.A.0019.2-gms-53c17a08-user works as expected but not patching the boot.img as per the linked thread: https://forum.fairphone.com/t/magisk-fairphone-os/93689/6     
I have attached the boot.img files and the output of cat /proc/mounts made on FP3-8901.4.A.0021.0-gms-0b368514-user.

[Output of `adb shell cat /proc/mounts`]
[proc_mounts.txt](https://github.com/topjohnwu/Magisk/files/11068769/proc_mounts.txt)
[Clean original boot.img] 
[FP3-8901.4.A.0021.0-gms-0b368514-user_orignal_boot.img.zip](https://github.com/topjohnwu/Magisk/files/11068695/FP3-8901.4.A.0021.0-gms-0b368514-user_orignal_boot.img.zip)
[Patched with magisk manager 981ccabb (25210) (D)
[FP3-8901.4.A.0021.0-gms-0b368514-user_magisk_patched-25210_boot.img.zip](https://github.com/topjohnwu/Magisk/files/11068692/FP3-8901.4.A.0021.0-gms-0b368514-user_magisk_patched-25210_boot.img.zip)

**Comment by yujincheng08** [comment]
I dont quite understand your issue.

From your words, you said patching boot image and flash it via fastboot will result in bootloop. But from the link you provided (https://forum.fairphone.com/t/magisk-fairphone-os/93689), it says installing magisk via twrp is not working anymore and the only working way to install magisk is via patching boot.

**Comment by Stygian88** [comment]
Rereading the page I linked to with a more awake mind, That link isn't that helpful to my case but towards the end of it states doing it ota is currently the only functional method at this time. I don't seem to be alone going by the linked to comment on the release page for the update, https://forum.fairphone.com/t/fp3-software-update-8901-4-a-0021-0/93443/56

Patching the boot image pulled from the latest (FP3-8901.4.A.0021.0-gms-0b368514-user) fastboot offline update package from the manual installation support page (https://support.fairphone.com/hc/en-us/articles/360048050332) results in a bootloop of the device it's been flashed to until the original image is flashed back

**Comment by yujincheng08** [comment]
Is there boot animation during bootloop? If so, are you able to `adb` during bootloop?

BTW, how do you perform OTA? Update, and then in the Magisk app, select direct install to the other slot?

**Comment by Stygian88** [comment]
There is not no, it doesn't hit that stage of the boot progress. I only see the branding/powered by android static screen alongside the bootloader unlocked warning before a reboot

I believe so yes, that is the method. I haven't yet attempted it myself yet as downgrading will require formatting the phone and although I have a backup of my apps/data I'd rather not rebuild the device if I can help it.

**Comment by yujincheng08** [comment]
> There is not no

What do you mean? I don't quite understand your English. From your latter description, it looks like there's no boot animation. But you said, `there's not no`, so there's boot animation?

> I haven't yet attempted it

`it` means what?

> I'd rather not rebuild the device

So maybe we are stuck here. You didn't provide any log, and we cannot locate the problem.

**Comment by Stygian88** [comment]
> What do you mean? I don't quite understand your English. From your latter description, it looks like there's no boot animation. But you said, there's not no, so there's boot animation?

There is no boot animation

> it means what?

The ota update method while the phone is on, I've been doing it via fastboot update packages provided by the manufacturer

>So maybe we are stuck here. You didn't provide any log, and we cannot locate the problem.

The earliest chance I will have to downgrade will be the 2nd of April (Sunday) as I am working and would like to have a functional phone in the meantime, flashing boot images  or attempting to pull logs on the weekday when I finish work is a possibility I can do in the meantime before then

**Comment by vvb2060** [comment]
no log

**Comment by chaosmaster** [comment]
It's actually even weirder, Fairphone instead of updating their bootloader to set `androidboot.force_normal_boot=1` patched their kernel to replace `skip_initramfs` with `androidboot.force_normal_boot=1` in the cmdline:
https://gerrit-public.fairphone.software/plugins/gitiles/kernel/msm-4.9/+/refs/heads/rel/11/fp3/8901.4.A.0022/fs/proc/cmdline.c

But because magisk patches the kernel with "skip_initramfs" => "want_initramfs" that doesn't work anymore.

Attached is a magisk_patched boot_image with just the skip/want patch reverted which works fine in all modes.

[FP3-8901.4.A.0022.0-boot_magisk_patched_skip_initramfs.img.zip](https://github.com/topjohnwu/Magisk/files/11646684/FP3-8901.4.A.0022.0-boot_magisk_patched_skip_initramfs.img.zip)

**Comment by Stygian88** [comment]
Thank you for looking into this, I'm currently driving 19.2 on that phone currently. I should be able to test that binary by manually flashing it with fastboot alongside the update rest of the images on the 10th/11th

**Comment by mart-e** [comment]
Hello,

> Attached is a magisk_patched boot_image with just the skip/want patch reverted which works fine in all modes.

I also have a FP3 and have the same issue while trying to install Magisk on FP3-8901.4.A.0022.0-gms-5bdac72d-user.
I have tried your image and it solved my bootloop issue.
Thank you :)

**Comment by Stygian88** [comment]
I can confirm that flashing the [FP3-8901.4.A.0022.0-boot_magisk_patched_skip_initramfs.img.zip](https://github.com/topjohnwu/Magisk/files/11646684/FP3-8901.4.A.0022.0-boot_magisk_patched_skip_initramfs.img.zip) image file works as expected to allow the phone to boot with magisk running. 
Using [47d2d4e3] (D) magisk manager does prompt for Requires additional setup which will currently result in a bootloop as the upstream change request have not yet been merged but otherwise seems to work as expected so far since I put it in place at 12:49 BST (UTC +1)

**Comment by norpol** [comment]
Thank you @chaosmaster, unzipping and `fastboot boot FP3-8901.4.A.0022.0-boot_magisk_patched_modified.img` finally let me start my phone. I previously installed `Magisk-v26.1.apk` via TWRP and instantly was presented with the bootloop. 

After my first boot the phone crashed, not sure what that was about but now after going into fastboot once more and then running

`fastboot flash boot ./FP3-8901.4.A.0022.0-boot_magisk_patched_modified.img`

and then `fastboot reboot` I was thankfully able to access my phone again.

**Comment by vvb2060** [comment]
try #7147 with twrp, I don't think it will work until twrp uses the latest kernel.
patch boot will work.

**Comment by Irkam** [comment]
Hi @chaosmaster after unzipping your image and flashing it the device finally started with `fastboot boot` but then wireless just doesn't work. However `FP3-8901.4.A.0023.0` has been out in the meantime so I would guess something happened there. Could you describe the steps for patching my own magisk patched image? 

Is it preferable to build the whole Magisk and comment out the portions that move skip_initramfs to want_initramfs (such as [right here](https://github.com/topjohnwu/Magisk/blob/feb47cd88c68e46068f898b1c2f0f75588d5603e/native/src/boot/dtb.cpp#L143)), or should I use a script to patch /init from within the image?

**Comment by chaosmaster** [comment]
@Irkam until a fix is merged you can use the app-builds created by one of the PRs that attempt to fix the issue:
https://github.com/topjohnwu/Magisk/suites/13452929666/artifacts/738307098
https://github.com/topjohnwu/Magisk/suites/14892793092/artifacts/848469709
