### ISSUE TITLE
Magisk "not installed" after required first reboot after install

### ISSUE THREAD

**Issue by neelchauhan** [topjohnwu/Magisk#6791]
On a Pixel 7 running LineageOS 20.0, on both the 20230317 and 20230324 snapshots, if I install Magisk Debug or Canary, launch Magisk for the first time, and then reboot, Magisk then shows up as "not installed", and therefore I can't use Magisk modules.

It happens on both sideloading and patching the `init_boot.img`.

I can use the stable Magisk v25.2 fine without this issue. This issue didn't appear in earlier Canary builds either, on the same Pixel 7.

Note: I have two Pixel 7 devices, one is my main device and the other is a backup, both bootloader unlockable versions, so testing this isn't an issue. I don't know if it affects other brands, but if so I can test LOS 20 on a OnePlus 9 also.

Device: Pixel 7
Android version: Android 13 - LineageOS 20.0
Magisk version name: 25.2
Magisk version code: 25210

**Comment by yujincheng08** [comment]
Grab a [bugreport](https://developer.android.com/studio/debug/bug-report) with patched `init_boot.img`
