### ISSUE TITLE
After reboot to finalise Magisk setup on S23, root is lost

### ISSUE THREAD

**Issue by LennertVA** [topjohnwu/Magisk#6797]
Device: Samsung S23 (S911B)
Android version: 13
Magisk version name: Debug
Magisk version code: 981ccabb (25210) (D)

After the final reboot to finalise Magisk setup, root is lost.

Steps to reproduce:
1. OEM unlock, bootloader unlock, void warranty, etc, etc - the usual prep dance
2. Install Magisk on stock ROM
3. Patch AP via file method (firmware downloaded via samfirm -m SM-S911B -r EUX)
4. Download patched  AP magisk_patched-25210_FkrwL.tar to computer
5. Flash patched AP plus BL, CP and CSC with odin
6. Walk through initial phone setup
7. Verify that root is indeed OK (rootbeer sample):

![Screenshot_20230330_093046_RootBeer Sample](https://user-images.githubusercontent.com/1744652/228766932-006b36fc-f305-4549-89d1-63adfcb9b740.jpg)

8. Verify that Magisk can indeed see root (cancel initial reboot request popup to be able to take screenshot):

![Screenshot_20230330_093236](https://user-images.githubusercontent.com/1744652/228767135-96d95cb4-7054-4240-87c2-a10511f4a27f.jpg)

9. Reboot phone as suggested
10. Once rebooted, root is lost.

![Screenshot_20230330_094051](https://user-images.githubusercontent.com/1744652/228767463-47b6dd70-eef8-406c-9cbc-e730b60076c6.jpg)

![Screenshot_20230330_094106_RootBeer Sample](https://user-images.githubusercontent.com/1744652/228767531-35798d21-03a8-4c9d-bd93-cec946c22c77.jpg)

Am I missing something? Is reboot to recovery still required as it used to be on S10e (I tried that, but it loads into stock Samsung recovery)?

Magisk log added:

[magisk_log_2023-03-30T09.43.25.log](https://github.com/topjohnwu/Magisk/files/11109174/magisk_log_2023-03-30T09.43.25.log)

**Comment by yujincheng08** [comment]
magisk log is not helping. Need adb logcat or bugreport.
