### ISSUE TITLE
Moto G XT1032 / Custom ROM Identity Crisis 6 -> Installation Fails

### ISSUE THREAD

**Issue by don0tdisturb** [topjohnwu/Magisk#68]
Hello there,

I'm having problems with Magisk on XT1032 with ROM Identity Crisis 6, the installer detects that the boot is patched for SuperSU and won't install.

I've attached the boot.img, the ROM is this one: https://forum.xda-developers.com/moto-g/development/rom-identity-crisis-6-t3324595

The boot.img is here: https://mega.nz/#!4tYyXADI!zrrd4F_SO17UJX2bYEl9fK1bHs35pPxvSgCFKv3be7o

It would be nice to have Magisk patched for this ROM, as it's as far as 1st gen Moto G users can get to Android 6.0 without heavy customization.

This is from the current install script:
`- SuperSU patched boot detected!
- Adding auto patch script for SuperSU
losetup: /data/su.img: No such file or directory
losetup: /data/su.img: No such file or directory
losetup: /data/su.img: No such file or directory
losetup: /data/su.img: No such file or directory
losetup: /data/su.img: No such file or directory
losetup: /data/su.img: No such file or directory
losetup: /data/su.img: No such file or directory
losetup: /data/su.img: No such file or directory
! SU image mount failed...
! Please immediately flash SuperSU now
! Installation will complete after flashing SuperSU
Updater process ended with ERROR: 1

`

Let me know if you need some more information, or if I can help on some way. 

Best regards!

**Comment by topjohnwu** [comment]
The install message stated quite clearly, you have to re-flash SuperSU in order to make it work.
Have you tried it yet?
