### ISSUE TITLE
Root no longer possible after last OS update

### ISSUE THREAD

**Issue by faekyu** [topjohnwu/Magisk#6802]
Device: Motorola Edge 30 (dubai)
Android version: Android 13 QPR2 (final release)
Magisk version name: Canary
Magisk version code: 981ccabb (25210)

Issue description:
After the update to Android 13 QPR2-based ROM (it started at either LineageOS build: lineage-20.0-20230330 or lineage-20.0-20230323), i can't get root working with Magisk anymore.

I used it for a long time to constantly patch boot.img (from LineageOS, after extracting it from payload.bin on each update) and it worked flawlessly, until i had to reinstall LineageOS and it so happens that i settled on this new ROM release which doesn't work with Magisk patching. So, even im not 100% sure if it's a result of the reinstall or update, but it really must be the latter. In the meanwhile, Magisk version didn't change, i clearly remember a successful boot.img patch on this same version, 981ccabb (25210).

My steps and results:
1) take boot.img from the latest LineageOS for my device to Magisk Install menu (for patching it with root)
2) it completes, so i take the magisk_patched file to my PC, and put my phone in fastboot
3) i flash the patched boot image:
```
fastboot flash boot_a boot_patched.img
fastboot flash boot_b boot_patched.img
```
and shut down, reboot the device. I expect that the phone has root access now, and that Magisk menu reflects this

But it does not. Magisk acts like there is no root by having a greyed out "Superuser" menu and displaying N/A at Magisk installed state (stands for unsuccessful flashing of the patched boot image, or the boot image having been incorrectly patched - i suspect the latter. My fastboot flash returned SUCCESS without errors, and also, i didnt change anything in my routine of using those exact same commands and environment, since when i last used Magisk with a properly working root)

So, this is what makes me think that recent ROM/Android Quarterly updates made Magisk unable to properly patch the boot image with root. Besides the rom, i also got firmware update 55-106-3 but i dont think that can mess with this. Just saying.

I attach the required log files:
[recovery.log](https://github.com/topjohnwu/Magisk/files/11129810/recovery.log)
[magisk_log_2023-04-01T16.44.23.log](https://github.com/topjohnwu/Magisk/files/11129812/magisk_log_2023-04-01T16.44.23.log)
[bootLogCat.log](https://github.com/topjohnwu/Magisk/files/11129813/bootLogCat.log)
[MagiskAppOpenLogCat.log](https://github.com/topjohnwu/Magisk/files/11129822/MagiskAppOpenLogCat.log)

So, the boot logcat is from a boot after flashing the patched boot image that Magisk produced. Then, recovery.log is from a recovery session after that point as well, and so is the Magisk log file (from Magisk itself) and the Magisk App open logcat is from opening main Magisk app (where the Superuser is greyed out, etc) around the time i begin that logcat capture, it it helps. cc @topjohnwu

**Comment by yujincheng08** [comment]
fixed

**Comment by vvb2060** [comment]
You are using Android 14

**Comment by yujincheng08** [comment]
https://github.com/topjohnwu/Magisk/actions/workflows/build.yml?query=branch%3Amaster

**Comment by KatayR** [comment]
Same thing happened after I updated my phone to latest Lineage os(lineage-20.0-20230410-nightly-cheeseburger)

**Comment by KatayR** [comment]
> > Same thing happened after I updated my phone to latest Lineage os(lineage-20.0-20230410-nightly-cheeseburger)
> 
> @KatayR
> 
> It's only relevant if you still have the problem with newer Magisk builds, as this issue got fixed. Please mention the build number

Latest, 26100.

Steps:
-Clean LineageOS installation. Clean magisk installation. No problems.
-Hide magisk app.
-...
-Uninstall magisk app(just the app) and update lineage os.
-Since magisk is gone after OS update, reinstall Magisk as  I always did before. But magisk app doesn't detect it. 

But I "kinda" solved it. I changed my recovery to TWRP and reinstalled magisk. Now it works. Tho, if I reinstall Lineage recovery(latest or outdated) again and reinstall magisk, same bug occurs. 
So now I have to use TWRP recovery if I want to use magisk.
