### ISSUE TITLE
Magisk not installed in magisk manager 

### ISSUE THREAD

**Issue by aptop6** [topjohnwu/Magisk#681]
Whenever I open magisk manager it says magisk not installed . .. 
![screenshot_20181016-110818](https://user-images.githubusercontent.com/22258395/46994989-6783de00-d134-11e8-8dac-044ce2a8feda.png)

**Comment by xerta555** [comment]
> Whenever I open magisk manager it says magisk not installed . ..

It will take a little more information than a very common phrase like "doesn't work", such as the make and model of your phone, did you initially install Magisk? 
If yes, what method did you use? 
Did you get a particular error message?
Which version of Android do you use?
Do you have a custom ROM installed or have you rooted your system?
