### ISSUE TITLE
Systemless hosts not working/typo

### ISSUE THREAD

**Issue by dd805bb** [topjohnwu/Magisk#6815]
Device: P7P
Android version: 13 QPR3 BETA 2
Magisk version name: CANARY
Magisk version code: 25211

![Screenshot_20230404-063854](https://user-images.githubusercontent.com/41106849/229811383-cf4fb23b-737a-4e6f-a483-f28e3cbb13db.png)
![Screenshot_20230404-062915~2](https://user-images.githubusercontent.com/41106849/229811397-476c1ce8-6b2f-4b6f-a223-da1d254b4ab6.png)

Systemless hosts mounting has a typo.
The location should be /data/adb/module/hosts/system/etc/hosts

Not 

/data/adb/moduleshosts/system/etc/hosts

**Comment by Hondo77** [comment]
Can confirm Systemless Hosts not working on Pixel 6 Pro, Android 14 DP2 with same log as above.
