### ISSUE TITLE
Unable to mount system rw

### ISSUE THREAD

**Issue by DrKetan** [topjohnwu/Magisk#6832]
Device:Samsung S23Ultra
Android version:13
Magisk version name:e2545e57
Magisk version code:26001

unable to mount system on new magisk 26 (system is already rw and working fine wih Magisk 25.2)
mount -o remount,rw /magiskpath/.magisk/mirror/system 
No issue with
mount -o remount,rw /magiskpath/.magisk/mirror/system_ext
[magisk_log_2023-04-06T02.22.37.log](https://github.com/topjohnwu/Magisk/files/11163083/magisk_log_2023-04-06T02.22.37.log)

**Comment by Displax** [comment]
Expected https://github.com/topjohnwu/Magisk/pull/6805

**Comment by DrKetan** [comment]
> Expected #6805

sir any workaround?

**Comment by pndwal** [comment]
So this was resolved by using correct mountpoint:
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-88379737
🙂
