### ISSUE TITLE
An easy way to detect Magisk

### ISSUE THREAD

**Issue by vvb2060** [topjohnwu/Magisk#684]
```
File backupPath = new File("/.backup");
if (backupPath.exists()) return true;
```
demo:https://github.com/vvb2060/MagiskChecker/releases/latest

Magisk need move `/.backup` to other path.

**Comment by topjohnwu** [comment]
Currently work in process....

**Comment by TenshoDaijin** [comment]
MagiskManager dont found :/ so what can i do ?

i do the magisk from /backup in the main path /device

**Comment by krasCGQ** [comment]
@tcmaps: SafetyNet still passes on mine and my device is still listed as Certified.

**Comment by topjohnwu** [comment]
Done: 149fa6318929c1bcb21a501bbc3b0ead6c3aad5f

**Comment by xxRaiyanxxYT** [comment]
@topjohnwu
it Detects Magisk but does not detect magisk manager little bit of confusing 😂
