### ISSUE TITLE
Request : Can you increase default  magisk image size for systemless hosts

### ISSUE THREAD

**Issue by dg28gadhavi** [topjohnwu/Magisk#685]
df -h : ( output )

/sbin/.core/block/loop08     size = 153M used = 122M  free = 31M  80% /system_root/system/etc/hosts

The host files i use are of around 35mb+ size

So it will be great if it can be increased around by more 30mb !

Regards !

**Comment by topjohnwu** [comment]
It is impossible to resize the image live, so unfortunately it is impossible to fix this issue.
I might come up with a new hosts module soon, hopefully it will fix this issue.

**Comment by tgc12** [comment]
> It is impossible to resize the image live, so unfortunately it is impossible to fix this issue.
> I might come up with a new hosts module soon, hopefully it will fix this issue.

It is still a problem with last update and the in-built Systemless Hosts Module.

With Adaway or Energized or any other option to load a custom Hosts file, if you exceed the free space in magisk.img they give an error (not enough space), should't it work like in other modules and create a magisk_merge.img to add in the next reboot?

Thank you.
