### ISSUE TITLE
Changed files by a module does not follow original SELinux context

### ISSUE THREAD

**Issue by Displax** [topjohnwu/Magisk#6859]
Device: All
Android version: All
Magisk version name: e2545e57
Magisk version code: 26001

Prewiusly, on Magisk 25xxx (I think before `sepolicy.rule` rewriting) all changed files by a module inherited original SELinux files context.
On new Magisk versions 26xxx Magisk just assigns the standard context ( `u:object_r:vendor_file:s0` or `u:object_r:system_file:s0` )

**TEST**
Original context:
```
bramble:/ # ls -lZ /vendor/bin/hw/wpa_supplicant
-rwxr-xr-x 1 root shell u:object_r:hal_wifi_supplicant_default_exec:s0  3026872 2009-01-01 02:00 /vendor/bin/hw/wpa_supplicant
```

Changed context by module:
```
bramble:/ # ls -lZ /vendor/bin/hw/wpa_supplicant
-rwxr-xr-x 1 root shell u:object_r:vendor_file:s0  3026872 2023-04-09 16:22 /vendor/bin/hw/wpa_supplicant
```

For this reason, many modules will not work or even cause a bootloops.

**Comment by yujincheng08** [comment]
Basically, magisk "bind mounts" modules' files or the original file. And bind mount won't change the secontext. So I think it's because you didn't correctly set the secontext of your module files?

`ls -lZ /data/adb/modules/{your module}/system/vendor/bin/hw/wpa_supplicant` shows what?

**Comment by Displax** [comment]
> `ls -lZ /data/adb/modules/{your module}/system/vendor/bin/hw/wpa_supplicant` shows what?

```
bramble:/ # ls -lZ /data/adb/modules/superpupermodule/system/vendor/bin/hw/wpa_supplicant
-rwxr-xr-x 1 root shell u:object_r:vendor_file:s0  3026872 2023-04-09 16:52 /data/adb/modules/superpupermodule/system/vendor/bin/hw/wpa_supplicant
```

**Comment by yujincheng08** [comment]
aha, thats why your module's not working. your original file is `u:object_r:vendor_file:s0`, so the bind mount results in `u:object_r:vendor_file:s0`. It's not magisk's issue.

**Comment by Displax** [comment]
> So I think it's because you didn't correctly set the secontext of your module files?
Of course I can set all permissions/groups/secontext manually, but earlier all this stuff setts automatically.

**Comment by yujincheng08** [comment]
that's incorrect behavior to set automatically. what if the module's author intentionally what to change the file's context?

**Comment by Displax** [comment]
> that's incorrect behavior to set automatically. what if the module's author intentionally want to change the file's context?

Original problem is for my module: https://github.com/Displax/modem-fix

In system context of /vendor/firmware/carrierconfig/cfg.db is `u:object_r:vendor_fw_file:s0`
When applying module by Magisk 25x that context still `u:object_r:vendor_fw_file:s0` but on Magisk 26x it changes on `u:object_r:vendor_fw_file:s0` and module doesn`t work.

**Comment by vvb2060** [comment]
> that's incorrect behavior to set automatically. 

No, magisk never had this behavior.

**Comment by Displax** [comment]
Original problem is for my module: https://github.com/Displax/modem-fix

In system context of /vendor/firmware/carrierconfig/cfg.db is u:object_r:vendor_fw_file:s0
When applying module by Magisk 25x that context still u:object_r:vendor_fw_file:s0 but on Magisk 26x it changes on u:object_r:system_file:s0 and module doesn`t work.

**Comment by yujincheng08** [comment]
Let me clarify the thing more.
1. Magisk bind-mounts modules' files to target locations. And the context will follow.
2. Magisk 25.2 will synchronize the context [here](https://github.com/topjohnwu/Magisk/blob/6066b5cf86703512451a021cf1aaf1a877530af7/native/jni/core/module.cpp#L489).
3. But the context synchronization only happens to one bind mount. If Magisk lazily bind-mounts a module's directory, only the context of the directory will be synchronized, leaving all its content files intact.
4. Moreover, if other modules use ".replace", the context of subdirectory files will also be intact.
5. So relying on such an indeterminate internal behavior is not safe.
6. The key that causes the problem is changing the module mount to RO to avoid the f2fs issue.

**Comment by yujincheng08** [comment]
One more notable thing. Magisk previously synchronized the context directly to the modules' files. So the synchronization is _permanent_ unless the module generates new files every boot. I think such modules are not many.

**Comment by vvb2060** [comment]
We might update the module install script to help lazy developers set the context, or add some comments to let developers understand the importance of context.  So reopen.

**Comment by Displax** [comment]
Ok, thank you. It is not big deal for me to change context manually, but some note to the module development docs might be very useful.

**Comment by osm0sis** [comment]
Magisk used to always use the module's context, that's why I added this: https://github.com/topjohnwu/Magisk/commit/18065826b96dd2c7bff122f869726bbcf697c8dd
