### ISSUE TITLE
Magisk Cause bootloop on Moto Z3 Verizon 8.1.0 Firmware

### ISSUE THREAD

**Issue by betaxab** [topjohnwu/Magisk#686]
**Issues:**

I have a problem with Unable to boot on Moto Z3 android 8.1 Firmware.
I don't know what the reason is, only Magisk v14.5 can make the phone boot up.

**Detailed Description:**

When I flashed latest magisk and then reboot the phone, the phone will first be stuck in the logo for a while, and then will crash and restart, Loop like this.

Then I try magisk one by one, I found that only the magisk 14.5 can be normal booted.

Since the phone did not release the adb device, I can't get the adb logcat with issue magisk. I checked the pstore, it is nothing, not any files.

This is the magisk 14.5 log:

https://gist.github.com/betaxab/69cb722866829a1e8945fd037b728770

This is the magisk canary log:

> 
> 03-27 20:28:11.281   771   771 I Magisk  : Magisk v17.3-e1a65276(17204) daemon started
> 03-27 20:28:11.303   776   776 I Magisk  : Magisk v17.3-e1a65276(17204) logger started
> 03-27 20:28:11.304   771   772 I Magisk  : ** post-fs-data mode running
> 03-27 20:28:11.306   771   772 I Magisk  : * Mounting /data/adb/magisk.img
03-27 20:28:11.382   771   772 I Magisk  : * Running post-fs-data.d scripts
03-27 20:28:11.382   771   772 I Magisk  : * Running module post-fs-data scripts
03-27 20:28:11.382   771   772 I Magisk  : * Loading modules
03-27 20:28:11.385   771   772 D Magisk  : resetprop: prop [persist.magisk.hide] does not exist
03-27 20:28:11.385   771   792 I Magisk  : * Starting MagiskHide
03-27 20:28:11.385   771   792 D Magisk  : resetprop: deleteprop [persist.magisk.hide]
03-27 20:28:11.385   771   792 I Magisk  : hide_utils: Hiding sensitive props
03-27 20:28:11.385   771   792 D Magisk  : resetprop: prop [ro.boot.vbmeta.device_state] does not exist
03-27 20:28:11.385   771   792 D Magisk  : resetprop: getprop [ro.boot.verifiedbootstate]: [orange]
03-27 20:28:11.385   771   792 D Magisk  : resetprop: setprop [ro.boot.verifiedbootstate]: [green] by modifing prop data structure
03-27 20:28:11.385   771   792 D Magisk  : resetprop: getprop [ro.boot.flash.locked]: [0]
03-27 20:28:11.385   771   792 D Magisk  : resetprop: setprop [ro.boot.flash.locked]: [1] by modifing prop data structure
03-27 20:28:11.385   771   792 D Magisk  : resetprop: getprop [ro.boot.veritymode]: [logging]
03-27 20:28:11.385   771   792 D Magisk  : resetprop: setprop [ro.boot.veritymode]: [enforcing] by modifing prop data structure
03-27 20:28:11.385   771   792 D Magisk  : resetprop: prop [ro.boot.warranty_bit] does not exist
03-27 20:28:11.385   771   792 D Magisk  : resetprop: prop [ro.warranty_bit] does not exist
03-27 20:28:11.385   771   792 D Magisk  : resetprop: getprop [ro.debuggable]: [0]
03-27 20:28:11.385   771   792 D Magisk  : resetprop: getprop [ro.secure]: [1]
03-27 20:28:11.385   771   792 D Magisk  : resetprop: getprop [ro.build.type]: [user]
03-27 20:28:11.385   771   792 D Magisk  : resetprop: getprop [ro.build.tags]: [release-keys]
03-27 20:28:11.385   771   792 D Magisk  : resetprop: prop [ro.build.selinux] does not exist
03-27 20:28:11.385   771   792 D Magisk  : hide_list: initialize...
> 03-27 20:28:11.385   771   792 I Magisk  : hide_list: [com.google.android.gms.unstable]

↑ Sure, it is full log, it only shows up here! no further log!

**Thinking:**

Motorola Moto Z3 has only two types of firmware, ZUI OS and verizon. Because ZUI OS is too ugly, We usually use verizon‘s firmware. I tested ZUI OS, Magisk latest(Also includes older versions like 16.4, 17.1, 17.2) can worked properly, but verizon's firmware is not working.

Will it return to normal if I flash the ZUI OS’s kernel(boot.img)?

If I don't flash magisk, it can booted properly, no issues can be normal use.

As long as I flash magisk (except 15.4), it will not boot.

So I think it's a system part issue, it's not related about the kernel.

Because I am not a professional, I don't know how to solve this problem. If you need me to do something, please tell me.

**Comment by topjohnwu** [comment]
This commit (9592a699865930a54ccd1ca193ae3acf909111e9) could fix the issue, please open a new issue if the problem persists.
