### ISSUE TITLE
Magisk 26 (26001) Total Commander See /Data Partition as Read Only

### ISSUE THREAD

**Issue by yogifrog** [topjohnwu/Magisk#6865]
Device: Sony Xperia XZ1 (G8341)
Android version: Android 9.0 (Pie)
Magisk version name: 26 (Debug Build)
Magisk version code: 26001

With Magisk Version 26 and Debug Build 26001 Total Commander can't Write to /data anymore it See the Partition as ReadOnly, with Magisk 25 it Works, on Screenshot you see Creating a Folder for Example Fails with ReadOnly and ask for RW Remount but data is Mounted as RW Already, via Terminal and RootExplorer no Problem Create/Delete Folders and Copy/Move/Delete Files works here.

![Screenshot_20230410-073850](https://user-images.githubusercontent.com/46760421/230833955-adcb00c5-23f7-4e1f-ad44-7b692d55e303.png)

**Comment by vvb2060** [comment]
app bug

**Comment by yogifrog** [comment]
This Means Total Commander have a bug with Magisk 26?

**Comment by VisionR1** [comment]
> This Means Total Commander have a bug with Magisk 26?

I have Magisk Delta v26.1 stable. If you have Zygisk enabled or riru first try to disabled and after try it again, i have the almost same error when go to delete or copy and paste from internal storage to data/data, with Zygisk enable and test and riru i have error, without work fine without errors

**Comment by VisionR1** [comment]
> app bug

Sure is app bug? If you can read my issue in Magisk Delta
https://github.com/HuskyDG/magisk-files/issues/156

**Comment by VisionR1** [comment]
> app bug

Sure is app bug? If you can read my issue in Magisk Delta
This write the developer of Total Commander
![IMG_20230827_144219](https://github.com/topjohnwu/Magisk/assets/25982450/efeb690a-c3a2-4038-9c83-4b61273eb2d6)

**Comment by VisionR1** [comment]
> Have you tried switching mount namespace to global?

No, first time some tell this, don't know before this, i read i similar issue from 2020 with another management app, but now i have the old Magisk Delta 25210 canary

![Uploading IMG_20230828_000900.jpg…]()

**Comment by VisionR1** [comment]
Maybe a solution
![IMG_20230906_142626](https://github.com/topjohnwu/Magisk/assets/25982450/5dca136d-9324-495f-957d-4a67c9c630c6)

**Comment by vvb2060** [comment]
you can try magisk alpha, it hides magisk internal mount points.
(if use `su -mm`, won't hide. I think every file manager uses the global namespace, so this suggestion may not be helpful.

**Comment by VisionR1** [comment]
> you can try magisk alpha, it hides magisk internal mount points. (if use `su -mm`, won't hide. I think every file manager uses the global namespace, so this suggestion may not be helpful. I think `su -t 1` will work on magisk alpha

Thanks for info, now I'm waiting for the total commander beta to fix this, if can fix it

**Comment by VisionR1** [comment]
No fix, for now
![IMG_20230918_155450](https://github.com/topjohnwu/Magisk/assets/25982450/769df120-07c7-4bf4-8d1e-018e3f7019bb)

**Comment by vvb2060** [comment]
We have provided enough documentation to help developers and make sure that magisk behaves as developers expect. The fact that other file managers are working properly attests to this.
I recommend using [Material Files](https://github.com/zhanghai/MaterialFiles), which is open source and available for developers to learn how to manage files.

**Comment by VisionR1** [comment]
> Sorry, all I see is your refusal to cooperate with the developer in investigating the issue.

I had give many information with Magisk v26.1, i had one month with this issue, the developer send me a beta version of the app, but still not working

**Comment by VisionR1** [comment]
> We have provided enough documentation to help developers and make sure that magisk behaves as developers expect. The fact that other file managers are working properly attests to this. I recommend using [Material Files](https://github.com/zhanghai/MaterialFiles), which is open source and available for developers to learn how to manage files.

Yeah, understand, the developer say ( i will make a detailed code comparison, but it's very surprising )
