### ISSUE TITLE
Magisk 26.1 stable APK refuses to install

### ISSUE THREAD

**Issue by TenSeventy7** [topjohnwu/Magisk#6876]
Device: Samsung Galaxy A50 (SM-A505GN)
Android version: 12.0
Magisk version name: d0c93842
Magisk version code: `26101`

Magisk 26.1 stable APKs refuse to install. Logcat for Magisk shows "APK signature mismatch" and attempts to uninstall the new APK and reinstalls the stub. The APK won't stay installed both when upgrading from 25.2 and manually installing 26.1.

**Canary and Debug APKs install fine on kernels compiled with Magisk canary/debug.**

**Edit:** I forgot to mention that 25.2 APKs install fine and stick.

[logcat.txt](https://github.com/topjohnwu/Magisk/files/11200766/logcat.txt)
[Stable.zip](https://github.com/topjohnwu/Magisk/files/11200775/Stable.zip)
[Canary.zip](https://github.com/topjohnwu/Magisk/files/11200778/Canary.zip)

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk#signing-and-distribution

**Comment by TenSeventy7** [comment]
The problem is that I'm using the official release APKs from the releases page.

**Comment by TenSeventy7** [comment]
Unfortunately it isn't going to be possible as Magisk is 'embedded' in the kernel image as a stub.
