### ISSUE TITLE
Note about new [defex] hex patch code

### ISSUE THREAD

**Issue by breakersvd** [topjohnwu/Magisk#689]
Hi @topjohnwu 
I just want to inform you that the new hexpatch code of **dedex** is working for:
- N960F (sec U2 - base RI)

And not working for these models:
- J701F
- J610F
- G570F
- G611F
- N960F (sec U1 - base RH)
- J730F
- J530F
- A530F
- A730F

And i found an unique and one hexpatch code to fix it on all devices listed above.
I published it here https://forum.xda-developers.com/android/software-hacking/test-disable-defex-security-samsung-t3851487
And this is the code: `821B8012` -> `A21B8052` (Tested)
Or if we will use the code that you got `821B8012` -> `E2FF8F12`
The only problem you added `004138D5` in the beginning and this hexs is related to N9 only.

**Comment by topjohnwu** [comment]
@breakersvd, the instruction you are patching is `mov w2, #-221`, which is the same one as mine. That instruction however, it pretty "broad" in my opinion since it literally means that every instruction setting the lower 32 bit of `r2` to -221 should be replaced. The value `-221` is pretty unique and from what I can see it does not happen anywhere else other than `fs/exec.c`.

I added `mrs x0, sp_el0` into the pattern because from what I experimented with the Note 9 sources, the compiler consistently generates machine code that sets the first parameter (`x0`) the instruction before the one we are targeting. I added it to "fail proof" false patches. But if what you said is true, then I guess I'll have to drop it.

**Comment by Newseedman** [comment]
#689

**Comment by breakersvd** [comment]
@topjohnwu 
 These bytes `821B8012` are related to `-__NR_execve` and this is unique in the all `defex` sources.

and the patched bytes `A21B8052` just converts the mark `-` to `+` because the function `task_defex_enforce` depending on `< 0` or `> 0 ` comparing,

So by changing `-` to `+` this will reverse the comparing result from `DEFEX_DENY` to `DEFEX_ALLOW`
and this extra bytes in the beginning `004138D5` is not related to defex and it is changed on each kernel Base

And about this

> But if what you said is true, then I guess I'll have to drop it.

Here is a [magiskboot.zip](https://github.com/topjohnwu/Magisk/files/2493743/magiskboot.zip)
compiled from latest release for `magiskboot` sources for Windows by me,

you can navigate to the thread that i pasted above and download boot images from the users and unpack them then (as you know) `magiskboot.exe --hexpatch kernel 004138D5821B8012 004138D5E2FF8F12` and you can see by yourself that is true

**Comment by topjohnwu** [comment]
@breakersvd throw the hex pattern into a aarch64 disassembler and you'll know what I'm saying :). BTW I'm not arguing with you about that your points are incorrect, I'm just here to get the facts straight.

The only thing related to `-__NR_execve` is `-221`. `821B8012` translates to `mov w2, #-221`. So any invocation of any function with the 3rd parameter set as `-221` will generate the instruction. So for example a function `int dummy(int a, int b, int c)`, anywhere in the code that calls `dummy(any, any, -221)` will contain the same pattern. The instruction basically means: put the value `-221` into the register `w2`.

Luckily in this case regarding the Samsung kernel, we do not have `-221` assigned to `w2` anywhere else other than the one we are targeting.

**Comment by breakersvd** [comment]
@topjohnwu 
I know what you are saying and I know the disassembled hex codes but it is never important to me since I get the codes and comparing without need for it (this what I do when I have the source code),

Anyway all what i speak about is the hexpatch codes and the direct affect on the security and I just want to give you the final working codes after testing with users and the disassembled hex codes are not important in for us in this case

**Comment by 7763sea** [comment]
> @topjohnwu
> These bytes `821B8012` are related to `-__NR_execve` and this is unique in the all `defex` sources.
> 
> and the patched bytes `A21B8052` just converts the mark `-` to `+` because the function `task_defex_enforce` depending on `< 0` or `> 0 ` comparing,
> 
> So by changing `-` to `+` this will reverse the comparing result from `DEFEX_DENY` to `DEFEX_ALLOW`
> and this extra bytes in the beginning `004138D5` is not related to defex and it is changed on each kernel Base
> 
> And about this
> 
> > But if what you said is true, then I guess I'll have to drop it.
> 
> Here is a [magiskboot.zip](https://github.com/topjohnwu/Magisk/files/2493743/magiskboot.zip)
> compiled from latest release for `magiskboot` sources for Windows by me,
> 
> you can navigate to the thread that i pasted above and download boot images from the users and unpack them then (as you know) `magiskboot.exe --hexpatch kernel 004138D5821B8012 004138D5E2FF8F12` and you can see by yourself that is true

can you share to me magiskboot.zip source code ? very thanks.

**Comment by Ricky310711** [comment]
> @topjohnwu
> These bytes `821B8012` are related to `-__NR_execve` and this is unique in the all `defex` sources.
> 
> and the patched bytes `A21B8052` just converts the mark `-` to `+` because the function `task_defex_enforce` depending on `< 0` or `> 0 ` comparing,
> 
> So by changing `-` to `+` this will reverse the comparing result from `DEFEX_DENY` to `DEFEX_ALLOW`
> and this extra bytes in the beginning `004138D5` is not related to defex and it is changed on each kernel Base
> 
> And about this
> 
> > But if what you said is true, then I guess I'll have to drop it.
> 
> Here is a [magiskboot.zip](https://github.com/topjohnwu/Magisk/files/2493743/magiskboot.zip)
> compiled from latest release for `magiskboot` sources for Windows by me,
> 
> you can navigate to the thread that i pasted above and download boot images from the users and unpack them then (as you know) `magiskboot.exe --hexpatch kernel 004138D5821B8012 004138D5E2FF8F12` and you can see by yourself that is true

Are you able to share the compilation code for this?
