### ISSUE TITLE
Cant install Magisk 26.1

### ISSUE THREAD

**Issue by RobertoMM1986** [topjohnwu/Magisk#6895]
When im try to download and install Magisk 26.1 on my phone (I have installed 25.2v) nothing happend then when i close Magisk and i open again i receive this message : "Update to the full version of Magisk Manager to complete the installation. Do you want to proceed with the download and instrallation?" then i press ok and nothing happend....also if im try to install the APK its telling me i have installed but when i open Magisk i have the old version installed...

Device: Redmi Note 8 PRO
Android version: 10
Magisk version name: 26.1
Magisk version code: 26101

**Comment by Meteorities** [comment]
I also faced this issue. Method below works for me:
1. Uninstall old and already hided Magisk Manager app.
2. Download the latest release of Magisk Manager in official Github page.
3. Install that Magisk Manager and open it.
4. Magisk Manager will be able to detect old Magisk installation and prompt update. Update Magisk via directly install method now.
5. System will prompt operation success. Now reboot, and after rebooting, everything works fine as usual. You can hide new Magisk Manager now.

**Comment by PurpleProg** [comment]
I have the same issue : 
With a stock boot flashed, magisk work fine.
I patch my stock boot.img file with magisk V26.1 then i flash it with fastboot.
After that, when i launch magisk for the first time afler the flash it crash and the app don't have icon anymore, it's said that it's a V1 but it was V26.1 before flash. After the first time (the app just close the first time), when y launch it it's ask for download a update and if i said yes it download for ever.

I alredy try to install the V26.1 from the apk,  it's said that it update magisk but in i still got the same issue.
How can i root my phone ?

My device is a Xiaomi redmi note 10s , android 13, MIUI V14.0.2.0 TKLMIXM

**Comment by RobertoMM1986** [comment]
> I also faced this issue. Method below works for me:
> 
> 1. Uninstall old and already hided Magisk Manager app.
> 2. Download the latest release of Magisk Manager in official Github page.
> 3. Install that Magisk Manager and open it.
> 4. Magisk Manager will be able to detect old Magisk installation and prompt update. Update Magisk via directly install method now.
> 5. System will prompt operation success. Now reboot, and after rebooting, everything works fine as usual. You can hide new Magisk Manager now.

Hi and ty for your answer!
So i have to unROOT my phone and then ROOT again with the last update?

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk#signing-and-distribution
