### ISSUE TITLE
The compiled binary has changed from a few hundred k to a few m 编译出来的二进制从以前的几百k，变成了几m

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#6897]
Device:xxx
Android version:xxx
Magisk version name:26.1
Magisk version code:26101
The compiled binary has changed from a few hundred k to a few m 编译出来的二进制从以前的几百k，变成了几m
Due to this submission

https://github.com/topjohnwu/Magisk/commit/9279f30e89c36d11f766aed28b9dec1d17530415

**Comment by androiddisk** [comment]
APP_STRIP_MODE   := --strip-all
Can solve it

**Comment by osm0sis** [comment]
I think that's intentional on the debug zips

**Comment by androiddisk** [comment]
Compiled from the latest synchronized source code. Both the official and debug versions of the compiled binary are several megabytes larger than before. However, strangely enough, the compiled size of Actions is only a few hundred kb

同步的最新源码下来编译的。编译的无论正式版还是debug版本 二进制比以前大了几兆。 不过奇怪的是Actions编译出来的大小只有几百kb
