### ISSUE TITLE
After flashing into magisk 26.x, The third-party app cannot use root privileges to modify the module files that have been flashed into the Maigsk app

### ISSUE THREAD

**Issue by yuanwofei** [topjohnwu/Magisk#6898]
Issue: After the mobile phone is flashed into magisk 26.x, the third-party app cannot use root privileges to modify the module files that have been flashed into the Maigsk app, but the magisk 25.x version can.

There is a /system/vendor/etc/xxx.conf file in my magisk module. After flashing in the magisk 25.x app, the third-party app can successfully modify the content of the file with root privileges, but magisk 26.1 modification failed, prompting "Read-only file system".

Device:  Xiaom MI 13
Android version:  13 (MIUI 14.0.21)
Magisk version name: d0c93842
Magisk version code: 26101

**Comment by yujincheng08** [comment]
expected

**Comment by theseanl** [comment]
Does this mean that no workaround is/and will available to the current and future Magisk releases?

I'm a user of OP's app https://play.google.com/store/apps/details?id=com.yuanwofei.cardemulator.pro and found this issue while trying to figure out why the app is not functioning.

**Comment by yujincheng08** [comment]
The thing is, this is initially an unexpected behavior that files modified by modules are writable by apps with some permissions. And Magisk 26.1 now mounts those files as read-only.

The correct way to write to modified files is to modify the corresponding file in `/data/adb/modules`.
