### ISSUE TITLE
"Magisk is not installed" after reboot on samsung note5 n9200

### ISSUE THREAD

**Issue by woyaojizhu8** [topjohnwu/Magisk#69]
Hi topjohnwu,
I  installed magisk manager and flashed Magisk-v11.1.zip  on my n9200 with stock 6.0.1 rom ( unmodified) , but when I opened magisk manager , it said " magisk is not installed ", while the root function showed and worked correctly . I followed  the instructions in magisk manager to download  and install magisk . After installation, magisk manager said that  magisk  was installed , but after I  rebooted my note5, it showed " magisk is not installed " again. 
Sorry for my poor English. I hope you can resolve this issue. Thanks.
[boot.emmc.win.zip](https://github.com/topjohnwu/Magisk/files/771472/boot.emmc.win.zip)

**Comment by woyaojizhu8** [comment]
你好，我使用三星n9200（官方rom，除了刷入twrp外未进行任何修改，安卓版本6.0.1）安装magisk manager 并通过twrp刷入Magisk-v11.1.zip后，显示如下：
![screenshot_20170214-005419](https://cloud.githubusercontent.com/assets/16593993/23209110/c3f0c5e4-f932-11e6-8363-64ee8a5a4009.png)

在magisk manager内下载并安装 magisk后，显示magisk已正确安装，重启后仍然是“未安装magisk”的状态。root功能工作正常，而magisk 模块无法工作，例如xposed systemless 在安装后显示“Xposed 框架87.0(Systemless by topjohnwu)版已安装，但尚未激活”。
另附magisk log:

[magisk_error_20170222_192110.log.zip](https://github.com/topjohnwu/Magisk/files/793177/magisk_error_20170222_192110.log.zip)

**Comment by TurokO8A** [comment]
#94  this is occuring on several Samsung stock kernels, please continue to post on this one as it concerns several devices.

**Comment by topjohnwu** [comment]
Samsung issues are all fixed
