### ISSUE TITLE
V26+ app disappears and won't reinstall

### ISSUE THREAD

**Issue by dtriguero** [topjohnwu/Magisk#6900]
Device: Samsung galaxy s10+ sm-g975f/ds
Android version: android 12 oneui 4.1
Magisk version name: 26.1
Magisk version code: 26101

Running ambasadii v5.6 rom with ambasadii v6.8 kernel which is pre-rooted with Magisk v25.2. Manger v25.2 installs and can update to latest manager. Developer released updated kernel to v6.9 with new Magisk v26.1. After flashing new kernel manager app disappears and v26+ manager can not be reinstalled. However v25.2 manager can and when try updating app after it immediately disappears again. V26+ can be manually put over 25.2 and opened but doesn't survive reboot. V26 can however survive reboot and remain installed if manually put in system/app or system/priv-app. Root and modules seem to work for things previously granted and activated regardless of app not being installed but without manager no way to grant or remove anything after.

[Ambasadii_Cruel-HVJ5-G97xF-v6.8-S.zip](https://github.com/topjohnwu/Magisk/files/11238910/Ambasadii_Cruel-HVJ5-G97xF-v6.8-S.zip)

[Ambasadii_Cruel-HVJ5-G97xF-v6.9-S-magisk-v26.1.zip](https://github.com/topjohnwu/Magisk/files/11238911/Ambasadii_Cruel-HVJ5-G97xF-v6.9-S-magisk-v26.1.zip)

**Comment by yujincheng08** [comment]
> [magisk_log_2023-04-13T10.46.02.log](https://github.com/topjohnwu/Magisk/files/11238763/magisk_log_2023-04-13T10.46.02.log)

Empty

**Comment by yujincheng08** [comment]
looks like you are using unofficial Magisk and thus the app is not compatible.

**Comment by vvb2060** [comment]
> Developer released updated kernel to v6.9 with new Magisk v26.1.

ROM developers have built in unofficial Magisk, you can't use official magisk due to signature verification.

https://github.com/topjohnwu/Magisk#signing-and-distribution

**Comment by osm0sis** [comment]
You can try flashing Magisk via recovery so that it tries to remove the system su, you can also try my unSU zip.

**Comment by osm0sis** [comment]
Yes, it's in the ramdisk now.

**Comment by osm0sis** [comment]
What? magiskinit is also in the ramdisk...

**Comment by osm0sis** [comment]
Ah, you should open an actual issue for that... that's not expected or intentional behavior from Magisk.

In the meantime the kernel developer will have to run magisk --preinit-device while booted, and then add the output as the value of PREINITDEVICE= in /.backup/.magisk
