### ISSUE TITLE
Unable to boot with magisk

### ISSUE THREAD

**Issue by LordArrin** [topjohnwu/Magisk#6901]
Device: Lenovo J607F
Android version: 13
Magisk version name: 26.1
Magisk version code: 26100

Device is falling into qualcomm crashdump mode when trying to boot with patched boot. Magisk 25* had the same issue.

[boot.zip](https://github.com/topjohnwu/Magisk/files/11239008/boot.zip)
[cat proc mounts.txt](https://github.com/topjohnwu/Magisk/files/11239016/cat.proc.mounts.txt)
[boot magisk.zip](https://github.com/topjohnwu/Magisk/files/11239026/boot.magisk.zip)
[magisk_log_2023-03-23T22.49.12.log](https://github.com/topjohnwu/Magisk/files/11239356/magisk_log_2023-03-23T22.49.12.log)

**Comment by vvb2060** [comment]
You are using a custom ROM, please ask the ROM developer
