### ISSUE TITLE
Add feature for extremely root hidden

### ISSUE THREAD

**Issue by maingocvinh** [topjohnwu/Magisk#6903]
Device: Samsung Galaxy J5 (2016)
Android version: 6.0.1
Magisk version name: 26.1
Magisk version code: 26101

Can't hide root Techcombank App, must have disable root function like SuperSU to access some apps. Zygisk cannot hide root for Techcombank, please download and test it. Magisk can overcome Momo, etc... I have changed Magisk app name, removed apps that use root, hidden root for all system apps for anti-spy but no success. Also Knox faked 0x0 with kernel. When I use boot image without original signature then device status say Custom and without root ramdisk Techcombank app opens normally.

**Comment by vvb2060** [comment]
magisk has removed the hidden root function

**Comment by maingocvinh** [comment]
how to not detected by bank app?

**Comment by maingocvinh** [comment]
> magisk has removed the hidden root function

how to not detected by bank app?

**Comment by maingocvinh** [comment]
> magisk has removed the hidden root function

why not add disable roor function like supersu? then I can install fake magisk app and bank app will not detect. how to not detected by bank app: disable root, delete supersu app. Is magisk still a useful app for restrict root detection, man? Denylist crash every app in list, can't add full progress to denylist like chrome or google, please fix it!
