### ISSUE TITLE
Magisk 26.1 on Lineage OS 20 cause factory reset EVERYTIME device reboots

### ISSUE THREAD

**Issue by justin-himself** [topjohnwu/Magisk#6905]
Device: Samsung Galaxy Tab S5e LTE (gts4lv)
Android version: 13 (Lineage OS 20)
Magisk version name: 26.1
Magisk version code: 26101

After sideloading Magisk, boot into system, (first time will be fine) and reboot, all data on the phone will be lost and the first time setting guide will pop up. If reboot again, the data will be wiped again.

**Comment by vvb2060** [comment]
no log

**Comment by marvinwankersteen** [comment]
@justin-himself Do you found a solution? Today exactly the same happend with my S5e and LOS20.
I have no idea what is the problem. I also can not reinstall magisk. It's very strange.
