### ISSUE TITLE
Feature request: Automatically disable all existing modules after fresh Magisk install

### ISSUE THREAD

**Issue by Aaron1011** [topjohnwu/Magisk#6909]
I recently re-installed Magisk (it had been removed after I updated my LineageOS install to a newer Android version). However, I didn't realize that I still had old Magisk modules on my device from my previous Magisk install. These modules turned out to be incompatible with my current Android version, and resulted in a bootloop.

Fortunately, I was able to fix this by running `adb wait-for-device shell magisk --remove-modules`, and then rebooting my device. However, it took some time reading through the logcat output to figure out that Magisk was trying to load modules.

It would be very helpful if performing an install of Magisk (not an upgrade of an existing version) automatically disabled all of previously installed modules, and prompted the user to consider re-enabling them from inside the Magisk Manager app (once they're verified that the modules are compatible with their current Android version). This would help prevent accidental bootloops when installing Magisk.

Device: OnePlus 9 Pro (lemonadep)
Android version: 13 (LineageOS 20-20230411-NIGHTLY-lemonadep)
Magisk version name: 26.1
Magisk version code: 26101

**Comment by osm0sis** [comment]
How would it know the difference? Clearly /data/adb was intact, you only lost Magisk in the boot image.
