### ISSUE TITLE
After updating to magisk v.26 I can't patch the boot file

### ISSUE THREAD

**Issue by sab009** [topjohnwu/Magisk#6910]
Device: Samsung Note 10.1 (GT-N8000)
Android version: 9 (Lineage OS 16)
Magisk version name: 26.1
Magisk version code: 

my tablet was rooted and I got magisk 24 installed via custom recovery method. (Custom recovery = TWRP)
after updating to magisk v.26 I could install it via custom recovery but it didn't get installed in the app and i didn't have root access.
I found out that after magisk v.26 custom recovery method isn't completed (according to release notes) and I should install it through patching the boot method.
the problem is that I can't boot the tablet into FASTBOOT mode because it's only got Odin mode ( or Download mode ).
I can't flash the .img file via Odin.
in installation instruction section, the Samsung method isn't helpful because my rom is Lineage OS and it's got boot.img file, not AP tar file.
then I decided to install magisk v.25 via custom recovery but the result was like before.
can you help me?

Ramdisk = yes
vbmeta partition = does NOT have

**Comment by RobertoMM1986** [comment]
I did fresh install and i was able to install last magisk 26.1 BUT i received this problem:
![Screenshot_2023-04-18-03-53-29-816_com topjohnwu magisk](https://user-images.githubusercontent.com/99040310/232656350-79da7190-c546-4e2a-9927-3f9ae7e73314.jpg)

![Screenshot_2023-04-18-03-57-46-044_rikka safetynetchecker](https://user-images.githubusercontent.com/99040310/232656428-5ce4e1a5-f8a3-4dc6-9b5e-f4711a67060a.jpg)

Then i installed SafetyNet 2.4.0 and both basic integrity and CTS passed BUT everytime i open Magisk i receive the same messages from the first screenshot then i flashed again from magisk last update AGAIN and now seens like all fine...
what caused this problem? im really fixed??? ty so much for your support!!!
