### ISSUE TITLE
Problem with Magisk 26.1

### ISSUE THREAD

**Issue by RobertoMM1986** [topjohnwu/Magisk#6912]
I did fresh install and i was able to install last magisk 26.1 BUT i received this problem:

![232657093-04c873c0-304b-4ccf-a2f1-54b66cf85a73](https://user-images.githubusercontent.com/99040310/232657662-6d4d1b2d-eb3b-4ed6-a272-88697e5bcd57.jpg)

![232657133-78cd1383-2380-4129-bcb9-c74f330dcbda](https://user-images.githubusercontent.com/99040310/232657674-e9b467bf-5eee-4ee9-82ab-cdff240fdfc8.jpg)

Then i installed SafetyNet 2.4.0 and both basic integrity and CTS passed BUT everytime i open Magisk i receive the same messages from the first screenshot then i flashed again from magisk last update AGAIN and now seens like all fine...
what caused this problem? im really fixed??? ty so much for your support!!!

Device: Redmi NOTE 8 PRO
Android version: 10
Magisk version name: 26.1
Magisk version code: 26101

**Comment by yujincheng08** [comment]
no log.
