### ISSUE TITLE
Magisk 26.1 Stuck on Boot Animation

### ISSUE THREAD

**Issue by Rifa335** [topjohnwu/Magisk#6925]
Device: Infinix Hot 10 | X682B
Android version: Android 10
Magisk version name: d0c93842
Magisk version code: (26101)(D)

After installing the update using flashing patched boot file Android just doesn't want to boot, its just stuck on the Boot animation. I've first tried the stable version and its like that, so i try it on the Debug version and still stuck on Boot Animation

**Comment by canyie** [comment]
Provide log please

**Comment by Rifa335** [comment]
Oh yeah i forgot to give it a Logcat Sorry

**Comment by Rifa335** [comment]
here's the logcat
[logcat.txt](https://github.com/topjohnwu/Magisk/files/11308605/logcat.txt)
I Prematurely turn off the logcat because i think it just looping
