### ISSUE TITLE
ZIP Files Downloaded From Chrome Won't Install

### ISSUE THREAD

**Issue by ThePieMonster** [topjohnwu/Magisk#6926]
Device: Google Pixel 6 Pro
Android version: Android 13
Magisk version name: https://github.com/topjohnwu/Magisk/commit/d0c9384233412c91d3538336e26fb419dd40c850
Magisk version code: (26101)(D)

ZIP files downloaded to the device will not install or show the typical ZIP file icon as shown below.

If the file is "copied" / "duplicated" using a file explorer application, then the file will be shown as a ZIP file.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/11359134/233908567-ff742da7-5347-499f-b998-4389a09992cb.png">

**Comment by ThePieMonster** [comment]
> not magisk problem

How so? Usually GitHub users provide a explanation with their posts.

**Comment by AllenChangMusic** [comment]
Magisk uses the native file selector.
It's likely that the file downloaded is flagged as "foreign", not sure if there's a setting to change or whehter you have to unlock it though

**Comment by ThePieMonster** [comment]
> Magisk uses the native file selector. It's likely that the file downloaded is flagged as "foreign", not sure if there's a setting to change or whehter you have to unlock it though

@AllenChangMusic I can see that being the issue. I see this across several devices when trying to install a module as well. Duplicating the file solves this issue every time. I wonder if there is some way of marking files as "safe" when downloaded through Google Drive or Chrome, etc. ...

**Comment by vvb2060** [comment]
Look at your picture, the media type of the first one is a file, and the media type of the second one is a ZIP archive. This is a problem with chrome or the website, it's not setting the correct media type.
