### ISSUE TITLE
Android Not Booting on Magisk 26.1

### ISSUE THREAD

**Issue by Rifa335** [topjohnwu/Magisk#6927]
Device: Infinix Hot 10 | X682B
Android version: Android 10
Magisk version name: d0c9384
Magisk version code: (26101)(D)

Now I Know this is my third time applying this. The first time i dont use the debug build, the second time i forgot to put up a Logcat. But, now here's a logcat.
[logcat.txt](https://github.com/topjohnwu/Magisk/files/11308699/logcat.txt)
The Problem is the same, just theres a logcat now

Im Very-very sorry for the last time for forgetting to up the Logcat
Much Sorry

**Comment by Rifa335** [comment]
Oh and to add things up everytime i flash the new patched Magisk 26.1 boot file, i have to reflash the super partition because idk just maybe adding some notes.
I think it bricked something on the Super partition

**Comment by yujincheng08** [comment]
```
04-24 16:02:51.731 12595 12595 D AndroidRuntime: Shutting down VM
04-24 16:02:51.731 12595 12595 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
04-24 16:02:51.731 12595 12595 E AndroidRuntime: java.lang.RuntimeException: failed to set system property
04-24 16:02:51.731 12595 12595 E AndroidRuntime: 	at android.os.SystemProperties.native_set(Native Method)
04-24 16:02:51.731 12595 12595 E AndroidRuntime: 	at android.os.SystemProperties.set(SystemProperties.java:196)
04-24 16:02:51.731 12595 12595 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:419)
04-24 16:02:51.731 12595 12595 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:393)
04-24 16:02:51.731 12595 12595 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-24 16:02:51.731 12595 12595 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-24 16:02:51.731 12595 12595 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

What's the output of `su -c getprop` while bootlooping?

**Comment by vvb2060** [comment]
![image](https://user-images.githubusercontent.com/26996262/234172141-288e8733-d7b3-497c-9941-6c7b1e654bba.png)

**Comment by Rifa335** [comment]
> What's the output of `su -c getprop` while bootlooping?

Permission Denied

**Comment by yujincheng08** [comment]
Your system props service is stuck because of too many `dev.mnt.blk` properties. This is strange. I doubt if you are running the official ROM.

From the [code](https://cs.android.com/android/platform/superproject/+/android-10.0.0_r1:system/core/init/mount_handler.cpp;drc=793f4b503e200a29638e289b3ad85422f3d187f2;l=86) of AOSP, if the mount point is not a directory, there won't be corresponding `dev.mnt.blk` property. Magisk avoid creating these properties by always mounting directorires as tmpfs. However, from your getprop result, your ROM creates such properties even if the mount point is a file.

**Comment by Rifa335** [comment]
I Am Running the Official Infinix ROM, Of wich XOS Dolphin V7.0.0. Its Quite hard putting A Custom ROM on MTK devices, 

So, what do i do now?
Just wait the next Update?

**Comment by yujincheng08** [comment]
It wont be fixed.

**Comment by Rahimmosavi258** [comment]
> Device: Infinix Hot 10 | X682B Android version: Android 10 Magisk version name: [d0c9384](https://github.com/topjohnwu/Magisk/commit/d0c9384233412c91d3538336e26fb419dd40c850) Magisk version code: (26101)(D)
> 
> Now I Know this is my third time applying this. The first time i dont use the debug build, the second time i forgot to put up a Logcat. But, now here's a logcat. [logcat.txt](https://github.com/topjohnwu/Magisk/files/11308699/logcat.txt) The Problem is the same, just theres a logcat now
> 
> Im Very-very sorry for the last time for forgetting to up the Logcat Much Sorry

**Comment by vvb2060** [comment]
78ca682bc56cb70e025d5eb8522bfbea9279eb2b
