### ISSUE TITLE
su does not exist, but /system/bin/magisk does.

### ISSUE THREAD

**Issue by ItsJustSomeDude** [topjohnwu/Magisk#6930]
Device: Moto G7 (river)
Android version: 13
Magisk version name: d0c93842
Magisk version code: 26101 (D)

Since I updated to Magisk 26.1 this issue started happening.  The Magisk app says:

Installed: N/A
Zygist: Yes
Ramdisk: Yes

When I flash the unpatched boot image, it says

Installed: N/A
Zygist: No
Ramdisk: Yes

The Superuser and Modules tabs are grayed out.  No other apps can use root.  Running `su` in Termux gives the "No su program detected" message.  But... `/system/bin/magisk` is still there.  I can run `/system/bin/magisk su` in Termux and I get a root shell.  Modules are also working.

The modules I had installed continued to work, but I deleted the `modules` directory as a troubleshooting step, and nothing changed.

I'm using the ROM LineageOS MicroG 20.0.

Here are patched and unpatched boot images and boot logcat.
[bootLineage.zip](https://github.com/topjohnwu/Magisk/files/11327309/bootLineage.zip)
[magisk_patched-26101_JBaVs.zip](https://github.com/topjohnwu/Magisk/files/11327327/magisk_patched-26101_JBaVs.zip)
[cat.log](https://github.com/topjohnwu/Magisk/files/11327404/cat.log)
[magisk.log](https://github.com/topjohnwu/Magisk/files/11327436/magisk.log)

Thank you all very much in advance for the assistance!

**Comment by yujincheng08** [comment]
duuplicate of #6914

**Comment by ishitasingh678** [comment]
No 'su' binary found
SU_SEARCH_PATHS: /system/bin/su /debug_ramdisk/su /system/xbin/su /sbin/su /sbin/bin/su /system/sbin/su /su/xbin/su /su/bin/su /magisk/.core/bin/su
sudo requires a 'su' binary that supports the '-c', '--shell', '--preserve-environment' and '--mount-master' options

Error pls help
