### ISSUE TITLE
Can't install any module

### ISSUE THREAD

**Issue by JellyShadow** [topjohnwu/Magisk#6939]
Device:
Android version: 13
Magisk version name: 26.1
Magisk version code: 26101

Can't install any module

Logs:

Copying zip to temp directory
Installing Pixel-Launcher-Extended-Online-Installer-Version-1.5.zip
/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: source: line 33: can't open '/data/adb/magisk/util_functions.sh': No such file or directory
! Installation failed

**Comment by yujincheng08** [comment]
you should fix the env

**Comment by JellyShadow** [comment]
And how do i do that?
