### ISSUE TITLE
crosshatch: "error booting boot.img" 

### ISSUE THREAD

**Issue by adpoliak** [topjohnwu/Magisk#695]
I unlocked the bootloader on a fresh-out-of-the-box Pixel 3 XL ("crosshatch"), installed Magisk Manager 6.0 via the Github Release, uploaded the factory "boot.img" via ADB, patched said image with Magisk 17.2, then downloaded "patched_boot.img" and applied it via `fastboot flash boot_a patched_boot.img`.
Upon issuing `fastboot set_active a && fastboot reboot`, the device ends up at the Fastboot screen with the following message:

`Enter reason: error booting boot.img`.

After that, issuing `fastboot flash boot_a boot.img && fastboot set_active a && fastboot reboot`, the device successfully boots back into Android--obviously without Magisk features present.

Interestingly, the size of the created "patched_boot.img" is about half that of the stock "boot.img".
The Magisk Install Log is [attached](https://github.com/topjohnwu/Magisk/files/2497475/magisk_install_log_20181019_173758.log).
The stock boot image was extracted from https://developers.google.com/android/images#crosshatch.
If the patched boot image would be of use, I can look for a place to upload it.

**Comment by adpoliak** [comment]
I retried with Magisk Canary, same result.
Install Log is [attached](https://github.com/topjohnwu/Magisk/files/2497552/magisk_install_log_20181019_183823.log).

**Comment by djechelon** [comment]
Same problem. Patched with 17.3, result image size halved.
