### ISSUE TITLE
Two small bugs regarding Magisk Manager's UI

### ISSUE THREAD

**Issue by naxitoo** [topjohnwu/Magisk#6958]
Device: SM-G780G (Galaxy S20 FE 4G Snapdragon)
Android version: 13, OneUI 5.1
Magisk version name: Debug
Magisk version code: d0c93842 (26101) (D)
---
**Bugs are the following:**

**1)** The "You're log free, try using your root apps more" (`R.string.log_data_none`) TextView is shown even when there are log items present

**2)** When switching **only** from Home to Logs (or viceversa) in the navigation bar, a vertical three-dot icon appears in the app bar and disappears like 0.5s after. When pressed, this button displays an empty dialog box

Below I leave a screenshot and a screen recording which show exactly what happens:

https://user-images.githubusercontent.com/104278947/235320152-b96d9c7d-f92b-4803-8a0d-0c4bee66daa1.mp4

<img src="https://user-images.githubusercontent.com/104278947/235320155-ee924736-c7cf-4c87-9e6c-1e7238f7d70a.jpg" width="290"/>

**Comment by vvb2060** [comment]
1. 4de93cfd4b8a596e1abf7302d99429e2bcc200ee
2. fe6b658c028e30f2972dd854b02ef2dd9a99d5b7

**Comment by topjohnwu** [comment]
Fixed :)
