### ISSUE TITLE
Unable to patch Ramdisk Samsung A125W

### ISSUE THREAD

**Issue by samuel1003** [topjohnwu/Magisk#6973]
Using older Magisk version patch OK but device bootloop, check Cat atached Here: 
[Cat Mount.txt](https://github.com/topjohnwu/Magisk/files/11412389/Cat.Mount.txt)

**Using newest magisk version this problem:**

Device: **Samsung A12 A125W**
Android version: 12
Magisk version name: 26.1
Magisk version code: 26101

- Device platform: arm64-v8a
- Installing: d0c93842 (26101)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [16217757]
RAMDISK_SZ      [1482609]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [112061]
OS_VERSION      [12.0.0]
OS_PATCH_LEVEL  [2022-12]
PAGESIZE        [2048]
NAME            [SRPTK17A005]
CMDLINE         [bootopt=64S3,32N2,64N2 loop.max_part=7]
CHECKSUM        [781af21cce065060d48bd04b9099306948d9645d000000000000000000000000]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [raw]
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
bad cpio header
- Magisk patched boot image detected
Loading cpio: [ramdisk.cpio]
bad cpio header
- Patching ramdisk
resetprop: getprop [ro.crypto.state]: [encrypted]
preinit device: cache
- Pre-init storage partition device ID: cache
Loading cpio: [ramdisk.cpio]
bad cpio header
! Unable to patch ramdisk
! Installation failed

[boot.img.zip](https://github.com/topjohnwu/Magisk/files/11412386/boot.img.zip)

**Comment by vvb2060** [comment]
unable to unzip boot.zip, please upload again

**Comment by yujincheng08** [comment]
Here you are:
[boot.zip](https://github.com/topjohnwu/Magisk/files/11414068/boot.zip)

**Comment by yujincheng08** [comment]
Tested boot image without any problem. But it does not match your log. Your log shows `RAMDISK_FMT [raw]` but I tested and it shows `RAMDISK_FMT     [gzip]`

```
magiskboot unpack boot.img
Parsing boot image: [boot.img]
HEADER_VER      [2]
KERNEL_SZ       [16217757]
RAMDISK_SZ      [1482609]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [112061]
OS_VERSION      [12.0.0]
OS_PATCH_LEVEL  [2022-12]
PAGESIZE        [2048]
NAME            [SRPTK17A005]
CMDLINE         [bootopt=64S3,32N2,64N2 loop.max_part=7]
CHECKSUM        [781af21cce065060d48bd04b9099306948d9645d000000000000000000000000]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
SAMSUNG_SEANDROID
VBMETA
```


```
magiskboot cpio ramdisk.cpio test
Loading cpio: [ramdisk.cpio]
```

```
echo $?
0
```
