### ISSUE TITLE
Feature Request: EarlyMount, Replace files systemlessy before Init starts 

### ISSUE THREAD

**Issue by NULL0B** [topjohnwu/Magisk#6983]
Device: SM-G973F
Android version: 12
Magisk version name: Debug
Magisk version code: https://github.com/topjohnwu/Magisk/commit/d0c9384233412c91d3538336e26fb419dd40c850 (26101) (D)

**Request:** Currently I think, magisk does not provide a way to replace files before Init is called.

**Case of Study:**
I was fixing (an official rom) issue regarding permissions to `system` user in a /vendor/etc/init/somescript.rc
I patched it systemlessy so I edited the script but when magisk replaces it is too late with no effects.
Also is late to change `system` user permissions in  /system/etc/permissions/platform.xml

In both ways there is no way to fix it systemlessy because Magisk acts after Init.

**Overlay.d** does not fit for this thask because there is no need to append to Init.rc.

**An example of the feature** could be found here in this closed source almost-unmantained  fork:
https://huskydg.github.io/magisk-files/docs/internal-guide.html

**Comment by yujincheng08** [comment]
see #6467, you can replace existing rc with overlay.d and it wont append to init.rc. So your request has been satisfied.

anyway, we somehow working on preinit replacement, as we already changed the preinit sepolicy folder name to preinit (https://github.com/topjohnwu/Magisk/commit/4e2b88b3d09249e68b94e486f50cf6b17faedd8f). So it may come together with the new mount API.
