### ISSUE TITLE
Bootloop after flashing Magisk v17.1 by TWRP

### ISSUE THREAD

**Issue by softtama** [topjohnwu/Magisk#699]
Hi. Could you help on my issue here, please?

I want to root my Xiaomi Mi 8 SE, its bootloader is already unlocked. I've tried these steps to attempt to root the system:

1. `adb reboot bootloader`
2. `fastboot flash recovery mi8se-twrp-0629.img` (from https://xiaomifirmware.com/download/9528/), success
3. `fastboot reboot`
4. Reboot to the system
5. Install latest Magisk Manager (`MagiskManager-v6.0.0.apk`) from this GitHub repository
6. Download Magisk file (`Magisk-v17.1(17100).zip`) from Magisk Manager
7. Reboot to TWRP recovery mode
8. Flash Magisk file via TWRP, success
9. Reboot to the system
10. I got bootloop

I don't know what's wrong. I'm new to this so I'm afraid if I look for and try to attempt existing solutions they will just make it worse. What do I need to do to get rid of the bootloop? Thank you.

**Comment by topjohnwu** [comment]
You shouldn't be opening an issue if you cannot provide any debug information.
This is not a support platform.
