### ISSUE TITLE
The rooting process with Magisk failed on the MiPad 5 Pro.

### ISSUE THREAD

**Issue by DKNight-9207** [topjohnwu/Magisk#6996]
This problem only happened on miui new version
When i install it with flashing boot.img, the system will crash after a few second and then turnback to bootloader.
whatever the magisk version is V26.1 or V25.2, they all fail.
mipad 5 pro have no TWRP support, so I can't install magisk with TWRP.

Device: Mipad 5 pro
Android version: 13
MIUI version: 14.0.3.0 (TKYCNXM)
Magisk version name: 26.1(debug) /26.1 / 25.2
Magisk version code: d0c93842 (26101)
[magisk_install_log_2023-05-16T01.35.38.log](https://github.com/topjohnwu/Magisk/files/11480481/magisk_install_log_2023-05-16T01.35.38.log)

**Comment by yujincheng08** [comment]
no crash log?

**Comment by DKNight-9207** [comment]
the system crash Immediately after entering the password.
I'm not sure if this log was generated after I installed the magisk_boot.img or after I flashed back the original boot.img.
[magisk_log_2023-05-16T11.56.57.log](https://github.com/topjohnwu/Magisk/files/11483871/magisk_log_2023-05-16T11.56.57.log)

**Comment by yujincheng08** [comment]
we need crash log

**Comment by DKNight-9207** [comment]
where i can get it?

**Comment by yujincheng08** [comment]
adb logcat

**Comment by DKNight-9207** [comment]
[crash_log.zip](https://github.com/topjohnwu/Magisk/files/11483915/crash_log.zip)

**Comment by DKNight-9207** [comment]
I found that it also unwork in poco f3.
thistime the system doesn't crash, but magisk app can't find the root.
I fill this problem happened on MIUI14, maybe there's something change?

MIUI: 14.0.4.0 (TKHMIXM)
Android: 13 TKQ1.220829.002
magisk: d0c93842
poco f3 system log:
[log.txt](https://github.com/topjohnwu/Magisk/files/11487064/log.txt)

**Comment by yujincheng08** [comment]
not the same with the poco f3's (05-16 18:58:41.632   895   921 W Magisk  : pkg: no dyn APK, ignore)

**Comment by yujincheng08** [comment]
as for ur mipad 5 pro. it looks like there's something irregular in ur log, but irrelevant to magisk. is ur phone normal if u restore to stock boot?

**Comment by DKNight-9207** [comment]
poco f3 have  rooted after delete hidden magisk app
mipad 5 pro have been rooted after reset all the data.
RIP for my data......
