### ISSUE TITLE
problems with cache modules

### ISSUE THREAD

**Issue by stangri** [topjohnwu/Magisk#7]
This is a follow up to http://forum.xda-developers.com/showpost.php?p=69080257&postcount=42, however in my case the /cache/magisk doesn't get created when flashing thru twrp either.

I'm attaching the module I've tested with and the screenshot from Magisk Manager.
[GoogleAssistantEnabler.zip](https://github.com/topjohnwu/Magisk/files/523333/GoogleAssistantEnabler.zip)
![screenshot_20161011-184346](https://cloud.githubusercontent.com/assets/4768176/19294588/e91a95d4-8fe2-11e6-9c10-179b4e0d4571.png)
Logs: 
[magisk_logs.zip](https://github.com/topjohnwu/Magisk/files/523350/magisk_logs.zip)

The message "Module will be updated at next reboot" stays on forever (I've rebooted 3 times).

**Comment by kudiaborm** [comment]
Also experiencing this issue on Nexus 6P

**Comment by stangri** [comment]
That's weird, from issue #9 it looks like come cache modules work on Nexus 6p, so I thought the problem was only evident on arm and not arm64 phones.

**Comment by stangri** [comment]
Looks like it was fixed either in v8 or in the fix for the cache modules.
