### ISSUE TITLE
Install failure on Samsung i9100 boot.img

### ISSUE THREAD

**Issue by dragonGR** [topjohnwu/Magisk#70]
Hello, I can't make magisk work on the galaxy S2., I tried 3-4 various AICP nightlies and same error. Tried with Resurrection Remix also, same thing. Below you can see a picture, the boot.img and the recovery.log. Thanks.

![img_20170212_111542_1024](https://cloud.githubusercontent.com/assets/10290836/22889398/aa96da8e-f211-11e6-8f30-14475b233b54.jpg)
https://hastebin.com/uzaxeqeray.sql (recovery.log)
https://ufile.io/9f006 (boot.img)

**Comment by dragonGR** [comment]
@topjohnwu  Tested with the recent version of https://github.com/stangri/MagiskFiles and same error. Same recovery log as https://hastebin.com/uzaxeqeray.sql

**Comment by lucabravi** [comment]
Same to me

**Comment by hubbert0** [comment]
**_### do you have any solutions?_**

- twrp-3.0.2-0-i9100
- lineage-14.1-20180920-nightly-i9100-signed
- Magisk-v17.1
