### ISSUE TITLE
Magisk Database Corrupts in Certain Environments (F2FS)

### ISSUE THREAD

**Issue by adrianer** [topjohnwu/Magisk#700]
When I use the option "Hide Magisk Manager" in Magisk 17.1 with Magis Manager 6.0.0 (147) on my OnePlus 3T with Lineage OS 15.1 (any of the latest builds) then at first everything seems to work. But after an hour or two, no app gets root anymore (also no pop up appears asking for the permission) and when trying to launch the Magisk Manager it hangs for ever. The same happens after a reboot - only that then additionally a "basic" Magisk Manager is installed in parallel to the not working one asking to download the full manager.

This was already happening for me with some 16.X versions of Magisk, so is not new with 17.1.

I've already tried to completely uninstall Magisk and reinstalling it several times, but nothing seems to help...

BTW. This issue sounds similar to issue #655.

**Comment by Rhyme** [comment]
Happening to me on Pixel 3 XL

**Comment by Rhyme** [comment]
^ I realize my earlier comment is not helpful but I'm off work now, so I can contribute two logs

magisk_log_20181021_130721.log - this is from before doing 'Hide Magisk Manager'. Everything is good here, but I can't play FGO, or use AndroidPay, as it detects MagiskManager. So I hide it.

magisk.log - this is after I 'Hide Magisk Manager'. When I 'Hide Magisk Manager' it does leave behind a non-functional Magisk Manager with the original package name, which I then uninstall. Manager then believes Magisk is not installed at all, the option to restore magisk manager is gone. Uninstalling and reinstalling via .apk restores magisk, but loops back to issue of Google Pay and FGO..

[magisk.log](https://github.com/topjohnwu/Magisk/files/2499466/magisk.log)
[magisk_log_20181021_130721.log](https://github.com/topjohnwu/Magisk/files/2499467/magisk_log_20181021_130721.log)

**Comment by Rhyme** [comment]
Screenshot of the 'stub' I get after rebooting the phone, as well.
![screenshot_20181021-132118](https://user-images.githubusercontent.com/11220496/47271573-36464c00-d540-11e8-910b-5b46aab2fadc.png)

**Comment by bdr99** [comment]
I'm also having this issue on my Pixel 3. Let me know if there is any way I can help.

**Comment by topjohnwu** [comment]
I've tested on multiple devices, including the latest Pixel 3 XL, and no issues are found so far. Most likely the issue is that the database isn't set properly to allow the switch to occur.

**Comment by topjohnwu** [comment]
I just found out the potential issue here, will investigate further

**Comment by topjohnwu** [comment]
Fixed
