### ISSUE TITLE
17.2 stuck booting on Pixel

### ISSUE THREAD

**Issue by bitching** [topjohnwu/Magisk#701]
My phone automatically downloaded the PPR2.181005.003 OTA image, and occasionally got stuck before i'm ready to the OTA update, so i have to force it to reboot.
the phone is up-to-date after the reboot and certainly i had no chance to perform the (Magisk Manager → Install → Install to Inactive Slot) procedure.
so i lost root and got magisk uninstalled.
then i flashed the 17.2 patched boot image, phone stuck booting and stay on the Google's logo.
and get booted after flashing back the original boot.img.

i want to keep my data and get magisk installed again.
is there anyway?
thanks in advance!

**Comment by topjohnwu** [comment]
Pixel are always my priority and should never fail. It is something wrong on your side

**Comment by bitching** [comment]
I found a solution at https://forum.xda-developers.com/pixel-xl/how-to/guide-pixel-xl-android-9-0-pie-unlock-t3825866
the reason why i sutck booting is i didn't excute ```fastboot flash boot --slot all boot.img``` before installing magisk.
i finally got root again.
thanks for you all.
