### ISSUE TITLE
Magisk seems to not support rooting on Edge 40 Pro yet

### ISSUE THREAD

**Issue by faekyu** [topjohnwu/Magisk#7011]
Device: Motorola Edge 40 Pro (rtwo / XT2301-4)
Android version: 13
Magisk version name: Debug
Magisk version code: 26101

After buying a new device, the above, i cannot get root working with Magisk. I believe there is an issue that holds Magisk back from successfully modifying boot.img to add root capabilities. This device was released last month.

My steps and results:
1) take boot.img from the latest stock ROM version (`RTWO_G_T1TR33.43_20_28`) for my device to Magisk Install menu (for patching it to have root)
2) it completes, so i take the magisk_patched file to my PC, and put my device in fastboot mode
3) i flash the patched boot image:
```
fastboot flash boot_a boot_patched_26101.img

Sending 'boot_a' (98304 KB)                        OKAY [  2.278s]
Writing 'boot_a'                                   OKAY [  0.102s]
Finished. Total time: 10.200s

fastboot flash boot_b boot_patched_26101.img

Sending 'boot_b' (98304 KB)                        OKAY [  2.279s]
Writing 'boot_b'                                   OKAY [  0.107s]
Finished. Total time: 2.395s
```

** I did this in both fastbootD and bootloader mode, but that doesn't change anything to this issue.

Now, when i start the device back up, i notice there is no root access; Magisk also has greyed out 'Superuser' menu, as if there was no successful flash of a boot.img that was correctly patched to have root capabilities. This is the problem.

Attaching required log files:
[PostFlashBoot_magisk_log_2023-05-23T20.42.06.log](https://github.com/topjohnwu/Magisk/files/11547466/PostFlashBoot_magisk_log_2023-05-23T20.42.06.log)
[firstBootPostFlash_logcat.txt](https://github.com/topjohnwu/Magisk/files/11547470/firstBootPostFlash_logcat.txt)
[DuringMagiskPatchingGUI_logcat.txt](https://github.com/topjohnwu/Magisk/files/11547477/DuringMagiskPatchingGUI_logcat.txt)
[DuringMagiskPatchingGUI_magisk_install_log_2023-05-23T20.24.24.log](https://github.com/topjohnwu/Magisk/files/11547478/DuringMagiskPatchingGUI_magisk_install_log_2023-05-23T20.24.24.log)

Log file names are self explanatory, i collected for varying cirumstances, like during Magisk patching the stock boot.img (and a logcat after this process was done) if it helps, but of course the focus should be on first boot logs, and the Magisk log when entering the app post-flashing the patched boot.img, when it still acts like there is no root access, and Superuser menu is greyed out.

Here are the boot.img:
[boot_patched_26101.zip](https://github.com/topjohnwu/Magisk/files/11547502/boot_patched_26101.zip)
[boot_stock_nonpatched.zip](https://github.com/topjohnwu/Magisk/files/11547503/boot_stock_nonpatched.zip)

@vvb2060 @yujincheng08 @topjohnwu Thanks in advance, i hope i will be able to use Magisk Rooted on my new device.

**Comment by vvb2060** [comment]
https://topjohnwu.github.io/Magisk/install.html
