### ISSUE TITLE
Magisk 24.1 Showing Installed N/A - Root Functions Intact

### ISSUE THREAD

**Issue by ang3lo-azevedo** [topjohnwu/Magisk#7014]
Device: Nothing Phone 1 (Abra)
Android version: 13
Magisk version name: 26.1
Magisk version code: 26102

Hello, I can't install Magisk on my phone.

Much like #5339 
I recently updated my phone to 1.5.4 and patched the Magisk modified boot.img, and it seems to have patched the boot.img because I have an aplication (LiveBoot) that shows a live log when the device is turning on, before it shows the lockscreen, and that app only works with root, but for some reason when I open the Magisk app after booting with the modified boot.img it doesn't show it beeing installed and doesn't show the option to install it.

Magisk shows like this

![](https://user-images.githubusercontent.com/66081804/241008287-ae389716-50e3-4967-82f6-5ac85897ad59.png)

LSPosed shows like this

![](https://user-images.githubusercontent.com/66081804/241008350-05819dce-b708-4f1f-ac41-865e6952fabb.png)

And my apps detect root

![](https://user-images.githubusercontent.com/66081804/241008427-44461bb8-76ed-4f96-84df-158c883ed4d3.png)

**Comment by yujincheng08** [comment]
https://github.com/topjohnwu/Magisk/commit/dd93556ad89916b433f481f9d4a3dcdaaca980bd
