### ISSUE TITLE
Magisk Manager crashes when Magisk Hide is opened

### ISSUE THREAD

**Issue by doylefermi** [topjohnwu/Magisk#702]
[Log_2018-10-20_19-47-49.txt](https://github.com/topjohnwu/Magisk/files/2498226/Log_2018-10-20_19-47-49.txt)

![screenshot_20181020-195554_magisk_manager](https://user-images.githubusercontent.com/8755940/47256726-32fc8300-d4a2-11e8-927a-721d2dff70dd.png)

`
10-20 19:48:07.881  1528  8039 I ActivityManager: START u0 {cmp=com.topjohnwu.magisk/a.b (has extras)} from uid 10243

10-20 19:48:07.989  8040  8040 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;

10-20 19:48:07.989  8040  8040 I zygote64:   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)

10-20 19:48:07.989  8040  8040 I zygote64:   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)

10-20 19:48:07.989  8040  8040 I zygote64:   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)

10-20 19:48:07.989  8040  8040 I zygote64:   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)

10-20 19:48:07.989  8040  8040 I zygote64:   at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)

10-20 19:48:07.989  8040  8040 I zygote64:   at void com.topjohnwu.magisk.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:57)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1215)

10-20 19:48:07.989  8040  8040 I zygote64:   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2733)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2858)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1591)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.os.Looper.loop() (Looper.java:164)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6500)

10-20 19:48:07.989  8040  8040 I zygote64:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)

10-20 19:48:07.989  8040  8040 I zygote64:   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:460)

10-20 19:48:07.989  8040  8040 I zygote64:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)

10-20 19:48:07.989  8040  8040 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.topjohnwu.magisk-_azWR1u_Es3H1F1YMLc8Jg==/base.apk"],nativeLibraryDirectories=[/data/app/com.topjohnwu.magisk-_azWR1u_Es3H1F1YMLc8Jg==/lib/arm64, /system/lib64, /vendor/lib64]]

10-20 19:48:07.989  8040  8040 I zygote64:   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)

10-20 19:48:07.989  8040  8040 I zygote64:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)

10-20 19:48:07.989  8040  8040 I zygote64:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)

10-20 19:48:07.989  8040  8040 I zygote64:   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)

10-20 19:48:07.989  8040  8040 I zygote64:   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)

10-20 19:48:07.989  8040  8040 I zygote64:   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)

10-20 19:48:07.989  8040  8040 I zygote64:   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)

10-20 19:48:07.989  8040  8040 I zygote64:   at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)

10-20 19:48:07.989  8040  8040 I zygote64:   at void com.topjohnwu.magisk.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:57)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1215)

10-20 19:48:07.989  8040  8040 I zygote64:   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2733)

10-20 19:48:07.989  8040  8040 I zygote64:   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2858)`

**Comment by topjohnwu** [comment]
Fixed upstream
