### ISSUE TITLE
Big problems with Magisk v26.1

### ISSUE THREAD

**Issue by IIDarkNessYT** [topjohnwu/Magisk#7035]
Device: Xiaomi Redmi 8
Android version: 13
Magisk version name: 26.1
Magisk version code: 26102

Greetings. Already a month ago I installed Magisk version 26.1 (26102). During all this time, he himself stopped working several times and could not determine whether I had superuser rights or not. Further, my phone began to hang on its own sometimes with a black screen and completely reboot while hanging on the boot animation. I installed only two programs that use superuser rights: Total Commander and BusyBox. What to do next - I do not know, the only option left is to delete it all. And I did my duty - I told you about this problem.
[magisk_log_2023-05-31T19.42.18.log](https://github.com/topjohnwu/Magisk/files/11616785/magisk_log_2023-05-31T19.42.18.log)
![Screenshot_20230531-200006_Magisk](https://github.com/topjohnwu/Magisk/assets/81167599/9a4ec2ed-4fc3-4782-b198-bad2321af1ae)

**Comment by j0110** [comment]
#6914

**Comment by yujincheng08** [comment]
your log does not show you are having magisk running (no magisktmp mounted)
