### ISSUE TITLE
Subsequent update stucks at "Downloading magisk"

### ISSUE THREAD

**Issue by Napator** [topjohnwu/Magisk#7036]
Good afternoon,

When i've been asked to update magisk from v25.0, it rebooted the system, and now when i lauch the magisk app again, it ask to download and install subsequent update. But this update never finish and stucks at "Downloading magisk".

I've checked the data consumption during download process, but no data is consumed.

I can't find any log since the magisk app doesn't open and the lineageos recovery does't have file manager.

Thank you for your help.

Device: OnePlus 8T
Android version: 12 (lineageos 19.1)
Magisk version name: 26.1
Magisk version code: 26102

**Comment by yujincheng08** [comment]
just install the magisk app manually.

**Comment by xwjqv** [comment]
Hi, i have the same problem,
but somehow the signatures are incompatible and i can't install it manually.
When looking at the logcat logs, i see a similar error when using the automatic method.

I think that the version of my dummy app was signed by the wrong signature.

This happend after trying to reinstall magisk after an update of Lineageos 18 to 20,
where i forgot to uninstall magisk beforehand.

Is there a way to fix this?
I tried to uninstall the dummy app but it does not work.

Device: Motorola G7 plus
Android version: 13
Magisk version name: 26.1
Magisk version code: 26102

**Comment by iyyappanmk19** [comment]
> Good afternoon,
> 
> When i've been asked to update magisk from v25.0, it rebooted the system, and now when i lauch the magisk app again, it ask to download and install subsequent update. But this update never finish and stucks at "Downloading magisk".
> 
> I've checked the data consumption during download process, but no data is consumed.
> 
> I can't find any log since the magisk app doesn't open and the lineageos recovery does't have file manager.
> 
> Thank you for your help.
> 
> Device: OnePlus 8T Android version: 12 (lineageos 19.1) Magisk version name: 26.1 Magisk version code: 26102

I have same problem.
I fixed it.
Solution:
I just installed root checker app
When I click VERIFY ROOT it ask grant root permission,
Now magisk ask download
After I click download magisk downloaded. Then it's shows upgrade option and click to upgrade, magisk manager successfully installed.

**Comment by Codemaster-AR** [comment]
> > Good afternoon,
> > When i've been asked to update magisk from v25.0, it rebooted the system, and now when i lauch the magisk app again, it ask to download and install subsequent update. But this update never finish and stucks at "Downloading magisk".
> > I've checked the data consumption during download process, but no data is consumed.
> > I can't find any log since the magisk app doesn't open and the lineageos recovery does't have file manager.
> > Thank you for your help.
> > Device: OnePlus 8T Android version: 12 (lineageos 19.1) Magisk version name: 26.1 Magisk version code: 26102
> 
> I have same problem. I fixed it. Solution: I just installed root checker app When I click VERIFY ROOT it ask grant root permission, Now magisk ask download After I click download magisk downloaded. Then it's shows upgrade option and click to upgrade, magisk manager successfully installed.

Nope i tried twice it didnt work.
