### ISSUE TITLE
[Magisk-v17.3(17300).zip] [download via mobile] same md5 as github Magisk-v17.2.zip -KNOWN ISSUE

### ISSUE THREAD

**Issue by rprimus** [topjohnwu/Magisk#707]
Sun Oct 21 14:11:32 BST 2018

Updated Magisk-Manager and installed recommended v17.3(17300).zip on mobile.
Still showed 17.2 installed.

Downloaded only via phone and installed via recovery.  Installer logged 17.2 was being installed.

![screenshot_2018-10-21-14-06-48](https://user-images.githubusercontent.com/278414/47267434-ad2d1600-d53b-11e8-8f13-7f4b7cb4cbe4.png)

Downloaded (github) released files and uploaded 17300 from phone:

```
: ; md5sum Magisk-v17.*
a8b466bb888306cc6adbb8ab365d03c6	Magisk-v17.2.zip
a8b466bb888306cc6adbb8ab365d03c6	Magisk-v17.3(17300).zip
72c0a50e9996524b6cae9267a4eb52fa	Magisk-v17.3.zip
```

P.S.    Selecting download only from Magisk-Manager - file was found in `/sdcard/Downloads` not in the usual `/sdcard/MagiskManager` folder.

**Comment by apnof** [comment]
can confirm for direct install method via MagiskManager app: installing "17.3" and after reboot magiskManager still reports 17.2 and wants to update.

**Comment by rprimus** [comment]
Sun Oct 21 14:25:09 BST 2018

Update:

Have successfully installed 17.3 via github release:

![screenshot_2018-10-21-14-22-14](https://user-images.githubusercontent.com/278414/47267558-5f191200-d53d-11e8-8b70-3d9ed3573c6e.png)

![screenshot_20181021-142609](https://user-images.githubusercontent.com/278414/47267565-70621e80-d53d-11e8-9cee-0e0d15d29561.jpg)

**Comment by topjohnwu** [comment]
Fixed the beta channel

**Comment by Q-ATRO86** [comment]
gg
