### ISSUE TITLE
Using Magisk 26.1 cause automatic reboot to fastboot

### ISSUE THREAD

**Issue by CNOCM** [topjohnwu/Magisk#7072]
Device:Meizu 16th
Android version:10
Magisk version name:26.1
Magisk version code:26102

I've had root for years and used Magisk without issue. Today, I decide to updeta my Magisk version (before this, i've use 25.2for a long time)and so I performed the update like I usually do:

Install the update through TWRP
Reboot
Boot loop / can't boot and automatic reboot to fastboot

When using version 26.1,
after successfully installing succeeds [install.log](https://github.com/topjohnwu/Magisk/files/11720053/magisk_install_log_2023-06-12T15.47.59.log) and restarting the phone, it automatically restarts to fastboot mode after displaying the first screen for 1 second, and the same issue occurs upon subsequent restarts.
When using version 25.2,
the device can start and operate normally without any problem.

[boot.zip](https://github.com/topjohnwu/Magisk/files/11720085/boot.zip) is the original boot image of the device,and
[magisk_patched-26100_13AVm.zip](https://github.com/topjohnwu/Magisk/files/11720088/magisk_patched-26100_13AVm.zip) is the image patched with version 26.1.

Summary of issue:
Patching succeeds (no warnings or errors)
Boot fails
Automatic reboot to fastboot

[dmesg.log](https://github.com/topjohnwu/Magisk/files/11720256/dmesg.log)
[mounts.txt](https://github.com/topjohnwu/Magisk/files/11720257/mounts.txt)

last_kmsk - inaccessible or not found
pstore ramoops - inaccessible or not found

I was using Zygote, Magisk hide / MagiskHidePropsConf, and safetynet-fix prior to losing root access.

Since I am unable to boot up properly, I cannot provide any more logs about version 26.1. However, I am able to provide logs without Magisk and with version 25.2.

**Comment by yujincheng08** [comment]
use 26102
