### ISSUE TITLE
Manager not loading

### ISSUE THREAD

**Issue by pashamcr** [topjohnwu/Magisk#7078]
Device: Alcatel Idol3
Android version: 7
Magisk version name: 26.1
Magisk version code: 26102

The last working commit is 40f25f4d56fc25f95209b68f4bee20eb4e7e30d3. After installing bf6359abaa65d9dc5c2873c59e256ab3d0f45f7b and patching boot - instead of a manager I have a stub, installing apk on top - without result.
In logcat: `lseek64 failed with 9: Bad file discriptor`

**Comment by canyie** [comment]
please attach logs

**Comment by pashamcr** [comment]
@yujincheng08 thanks for the fix, Magisk is working fine.
