### ISSUE TITLE
LineageOS 20 Bootloop

### ISSUE THREAD

**Issue by czornomasz** [topjohnwu/Magisk#7089]
Device: Poco F3 (M2012K11AG)
Android version: 13
Magisk version name: 47d2d4e3
Magisk version code: 26102

Hello everyone, after Update my device from Lineageos 19 to 20 i tried reinstall / root my device with Magisk again. After flashed the patched boot.img, my device bootlooped at several trys. When I flashed the boot.img from the installed lineageos, it returns to normal. I have also tried the "old way", to rename the .apk to .zip an install it with sideload, same result.

[bugreport-lineage_alioth-TQ2A.230505.002-2023-06-16-14-44-44.zip](https://github.com/topjohnwu/Magisk/files/11772837/bugreport-lineage_alioth-TQ2A.230505.002-2023-06-16-14-44-44.zip)
[proc_mounts.txt](https://github.com/topjohnwu/Magisk/files/11772839/proc_mounts.txt)
[Uploading magisk_patched-26102_697s6.zip…]()
[Uploading boot.zip…]()

**Comment by Aurellion** [comment]
Hi, I just ran into the same problem. May I ask how you resolved it?

**Comment by Opocx** [comment]
Did u solved it? I also have the same problem on Los 20 published 10 April.
