### ISSUE TITLE
Manager默认root为MagiskSU

### ISSUE THREAD

**Issue by vgohja17408** [topjohnwu/Magisk#709]
Manager默认root为MagiskSU，导致使用其它SU时(比如MIUI开发版自带SU)因为没有magiskpolicy而造成数据库初始化失败(执行db_sepatch无效)，应用程序打开就崩溃。无法安装Magisk。
在6.0.1之前因为有`Data.magiskVersionCode < Const.MAGISK_VER.FBE_AWARE`能正常使用。

**Comment by topjohnwu** [comment]
Duplicate
