### ISSUE TITLE
`magiskinit` not involved on Sony Walkman NW-A105

### ISSUE THREAD

**Issue by ttwards** [topjohnwu/Magisk#7091]
Device:Sony Walkman NW-A105
Android version:P 9.0.0
Magisk version name:Debug
Magisk version code: 26102
According to the log, magisk is successfully installed to the boot image(I guess), and I unpacked the patched one, and found magisk32/64.xz in ramdisk/overlay.d/sbin/, but magisk won't work.
![Screenshot_20230617-003006](https://github.com/topjohnwu/Magisk/assets/105055513/03c0274b-fa08-4127-ac15-834ee8d53614)
 This is the stock boot.img: [Stock.img](https://mega.nz/file/ut8DiaaB#zR2npnjFNT6p2hb8yQMH9nCarXlfeeikiBmxFBtfMMc) This is the patched boot.img: [Patched.img](https://mega.nz/file/eoNT1LxQ#Q02P6gtGKiqmbJ9HV3_tbl-02XRxUoBuCSrOebcfX2s) This is the log file: [log](https://mega.nz/file/z5FD0ZRD#ASIWk668LYbvBEYErW4Aiamgq5WXjZDEtNplkf3lKZw)

**Comment by ttwards** [comment]
This is /proc/mounts
`~ $ cat /proc/mounts
/dev/root / ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr,acl 0 0
devtmpfs /dev devtmpfs rw,seclabel,relatime,size=1577776k,nr_inodes=394444,mode=755 0 0
tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,mode=600,ptmxmode=000 0 0
none /dev/memcg cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
none /dev/stune cgroup rw,nosuid,nodev,noexec,relatime,schedtune 0 0
none /dev/cpuctl cgroup rw,nosuid,nodev,noexec,relatime,cpu 0 0
none /dev/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent 0 0
cg2_bpf /dev/cg2_bpf cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
adb /dev/usb-ffs/adb functionfs rw,relatime 0 0
mtp /dev/usb-ffs/mtp functionfs rw,relatime 0 0
ptp /dev/usb-ffs/ptp functionfs rw,relatime 0 0
proc /proc proc rw,relatime 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
none /sys/kernel/debug debugfs rw,seclabel,relatime,mode=755 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,seclabel,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
tmpfs /mnt tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
/dev/block/by-name/var /mnt/vendor/var ext4 rw,rootcontext=u:object_r:mnt_vendor_file:s0,seclabel,nodev,noexec,noatime,discard,data=ordered 0 0
/dev/block/by-name/opt1 /mnt/vendor/opt1 ext4 rw,rootcontext=u:object_r:mnt_vendor_file:s0,seclabel,nodev,noexec,noatime,discard,data=ordered 0 0
/dev/block/by-name/opt2 /mnt/vendor/opt2 ext4 rw,rootcontext=u:object_r:mnt_vendor_file:s0,seclabel,nodev,noexec,noatime,discard,data=ordered 0 0
/dev/block/by-name/opt3 /mnt/vendor/opt3 ext4 rw,rootcontext=u:object_r:mnt_vendor_file:s0,seclabel,nodev,noexec,noatime,discard,data=ordered 0 0
/dev/block/by-name/idd /mnt/vendor/idd ext4 rw,rootcontext=u:object_r:mnt_vendor_file:s0,seclabel,nodev,noexec,noatime,discard,data=ordered 0 0
/dev/block/by-name/rca /mnt/vendor/rca ext4 rw,rootcontext=u:object_r:mnt_vendor_file:s0,seclabel,nodev,noexec,noatime,discard,data=ordered 0 0
exfatfuse /mnt/media_rw/F46E-C93B fuse.exfatfuse rw,nosuid,nodev,relatime,user_id=0,group_id=1065,allow_other 0 0
/mnt/media_rw/F46E-C93B /mnt/runtime/default/F46E-C93B sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6 0 0
/mnt/media_rw/F46E-C93B /mnt/runtime/read/F46E-C93B sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18 0 0
/mnt/media_rw/F46E-C93B /mnt/runtime/write/F46E-C93B sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18 0 0
/dev/block/dm-0 /mnt/expand/c80822cc-13b4-4d28-a968-d31401d22cf0 ext4 rw,dirsync,seclabel,nosuid,nodev,noatime,data=ordered 0 0
/mnt/expand/c80822cc-13b4-4d28-a968-d31401d22cf0/media /mnt/runtime/default/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal 0 0
/mnt/expand/c80822cc-13b4-4d28-a968-d31401d22cf0/media /mnt/runtime/read/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal 0 0
/mnt/expand/c80822cc-13b4-4d28-a968-d31401d22cf0/media /mnt/runtime/write/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal 0 0
/dev/block/platform/30b60000.mmc/by-name/vendor_a /vendor ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr,acl,inode_readahead_blks=8 0 0
none /acct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0
none /config configfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/block/by-name/userdata /data ext4 rw,seclabel,nosuid,nodev,noatime,nodiratime,noauto_da_alloc,resgid=1065,errors=panic,data=ordered 0 0
tmpfs /storage tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
/mnt/media_rw/F46E-C93B /storage/F46E-C93B sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6 0 0
/mnt/expand/c80822cc-13b4-4d28-a968-d31401d22cf0/media /storage/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal 0 0
tmpfs /storage/self tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0`

**Comment by yujincheng08** [comment]
please provide a bugreport

**Comment by Lishoo** [comment]
I'm just curious, did you flash the patched boot image to the partition? Without that it won't work.

**Comment by ttwards** [comment]
> I'm just curious, did you flash the patched boot image to the partition? Without that it won't work.

Yes of course!!!!😶

**Comment by ttwards** [comment]
> please provide a bugreport

Do you mean logcat or something?

**Comment by yujincheng08** [comment]
https://developer.android.com/studio/debug/bug-report

**Comment by ttwards** [comment]
> https://developer.android.com/studio/debug/bug-report

[Here it is, thank you very very much!!!](https://mega.nz/file/ax1hGYoA#1R_UMGJHIQW_G1-dyZXdjXaRfOIk1a_vlu-htRlPM-c)

**Comment by yujincheng08** [comment]
dmesg shows nothing about magiskinit. looks like you didn't install magisk properly.

**Comment by ttwards** [comment]
Hmmm I have no idea what caused it.... I patched it, flashed it to both ab partitions, flashed vbmeta to disable dm-verity. I unpacked the patched one and found magisk64/32.xz. Is it issue from init?

**Comment by yujincheng08** [comment]
hv u even had this device work with magisk?

from the log I think `skip_initramfs` takes effect even tho magisk has patched the kernel to avoid `skip_initramfs`

```
<6>[    4.848209] EXT4-fs (mmcblk2p5): mounted filesystem without journal. Opts: (null)
<6>[    4.848244] VFS: Mounted root (ext4 filesystem) readonly on device 179:5.
<6>[    4.850021] devtmpfs: mounted
<6>[    4.851503] Freeing unused kernel memory: 4800K
<14>[    4.869089] init: init first stage started!
<14>[    4.870327] init: Using Android DT directory /proc/device-tree/firmware/android/
<14>[    4.872642] init: [libfs_mgr]fs_mgr_read_fstab_default(): failed to find device default fstab
<14>[    4.900923] init: [libfs_mgr]Returning avb_handle with status: 3
<14>[    4.900951] init: [libfs_mgr]AVB HASHTREE disabled on: /vendor
```

**Comment by ttwards** [comment]
> hv u even had this device work with magisk?
> 
> from the log I think `skip_initramfs` takes effect even tho magisk has patched the kernel to avoid `skip_initramfs`
> 
> ```
> <6>[    4.848209] EXT4-fs (mmcblk2p5): mounted filesystem without journal. Opts: (null)
> <6>[    4.848244] VFS: Mounted root (ext4 filesystem) readonly on device 179:5.
> <6>[    4.850021] devtmpfs: mounted
> <6>[    4.851503] Freeing unused kernel memory: 4800K
> <14>[    4.869089] init: init first stage started!
> <14>[    4.870327] init: Using Android DT directory /proc/device-tree/firmware/android/
> <14>[    4.872642] init: [libfs_mgr]fs_mgr_read_fstab_default(): failed to find device default fstab
> <14>[    4.900923] init: [libfs_mgr]Returning avb_handle with status: 3
> <14>[    4.900951] init: [libfs_mgr]AVB HASHTREE disabled on: /vendor
> ```
No...it never worked...... Is there anything I can help with? I don't know how to disable `skip_initramfs`

**Comment by yujincheng08** [comment]
here u are the kernel source of your device:
https://oss.sony.net/Products/Linux/Audio/NW-A105.html

u can compile a kernel with `skip_initramfs` disabled:
in `init/initramfs.c`, change the following line
```c
__setup("skip_initramfs", skip_initramfs_param);
```
into
```
__setup("want_initramfs", skip_initramfs_param);
```


if it works, you will the following log in ur bugreport:
```
Trying to unpack rootfs image as initramfs
```

**Comment by ttwards** [comment]
Ok, trying now. thank you very much for your kindness!

**Comment by Blackilykat** [comment]
Had the same issue on my Pixel 7 pro. I used to have root before the march update and it was fine before, but after flashing init_boot it just showed Installed: N/A like in the screenshot posted in the original post. 
I fixed the issue by rolling back to 24.3 (24300)

**Comment by ttwards** [comment]
> Had the same issue on my Pixel 7 pro. I used to have root before the march update and it was fine before, but after flashing init_boot it just showed Installed: N/A like in the screenshot posted in the original post. I fixed the issue by rolling back to 24.3 (24300)

I've tried that, not working.
Will report after compiling the kernel, I haven't got time to do yet....

**Comment by maingocvinh** [comment]
sorry but I'm too lazy to create a bug report. all apps will always be stopped if i add it to denylist, magisk 25 I can't open magisk app manager after install root, magisk 26 I can't use denylist. my device: ss j5 (2016), android 7.1

**Comment by ttwards** [comment]
Sorry for asking such a stupid question, I've already compiled the kernel, but I just can't find the initrd.img or something like that, here's my out/ dir, could you please tell me where it is？ Thanks for your help
`ttwards@ttwards-Virtual-Machine:~/a105/vendor/nxp-opensource/kernel_imx/out$ ls -l
总用量 122328
drwxrwxr-x  3 ttwards ttwards     4096 6月  22 10:06 arch
drwxrwxr-x  3 ttwards ttwards     4096 6月  22 10:10 block
-rw-rw-r--  1 ttwards ttwards  1335132 6月  22 10:21 built-in.o
drwxrwxr-x  2 ttwards ttwards     4096 6月  22 10:08 certs
drwxrwxr-x  2 ttwards ttwards    12288 6月  22 10:22 crypto
drwxrwxr-x 82 ttwards ttwards     4096 6月  22 10:21 drivers
drwxrwxr-x  2 ttwards ttwards     4096 6月  22 10:10 firmware
drwxrwxr-x 31 ttwards ttwards     4096 6月  22 10:16 fs
-rw-rw-r--  1 ttwards ttwards 28738048 6月  22 10:41 Image
drwxrwxr-x  4 ttwards ttwards     4096 6月  22 10:06 include
drwxrwxr-x  2 ttwards ttwards     4096 6月  22 10:21 init
drwxrwxr-x  2 ttwards ttwards     4096 6月  22 10:09 ipc
drwxrwxr-x 14 ttwards ttwards    12288 6月  22 10:14 kernel
drwxrwxr-x 12 ttwards ttwards    16384 6月  22 10:22 lib
-rw-rw-r--  1 ttwards ttwards      565 6月  22 10:08 Makefile
drwxrwxr-x  2 ttwards ttwards    12288 6月  22 10:11 mm
-rw-rw-r--  1 ttwards ttwards    31396 6月  22 10:11 modules.builtin
-rw-rw-r--  1 ttwards ttwards     9051 6月  22 10:21 modules.order
-rw-rw-r--  1 ttwards ttwards   675076 6月  22 10:21 Module.symvers
drwxrwxr-x 23 ttwards ttwards     4096 6月  22 10:16 net
drwxrwxr-x  8 ttwards ttwards     4096 6月  22 10:08 scripts
drwxrwxr-x  5 ttwards ttwards     4096 6月  22 10:09 security
drwxrwxr-x 22 ttwards ttwards     4096 6月  22 10:11 sound
lrwxrwxrwx  1 ttwards ttwards        2 6月  22 10:08 source -> ..
-rw-rw-r--  1 ttwards ttwards  5310929 6月  22 10:21 System.map
drwxrwxr-x  2 ttwards ttwards     4096 6月  22 10:08 usr
drwxrwxr-x  4 ttwards ttwards     4096 6月  22 10:11 virt
-rwxrwxr-x  1 ttwards ttwards 35827984 6月  22 10:21 vmlinux
-rw-rw-r--  1 ttwards ttwards 53490704 6月  22 10:21 vmlinux.o`

**Comment by ttwards** [comment]
Sorry for asking such a stupid question, I've already compiled the kernel, but I just can't find the initrd.img or something like that, here's my out/ dir, could you please tell me where it is？ Thanks for your help!
`drwxrwxr-x  3 ttwards ttwards     4096 6月  22 10:06 arch
drwxrwxr-x  3 ttwards ttwards     4096 6月  22 10:10 block
-rw-rw-r--  1 ttwards ttwards  1335132 6月  22 10:21 built-in.o
drwxrwxr-x  2 ttwards ttwards     4096 6月  22 10:08 certs
drwxrwxr-x  2 ttwards ttwards    12288 6月  22 10:22 crypto
drwxrwxr-x 82 ttwards ttwards     4096 6月  22 10:21 drivers
drwxrwxr-x  2 ttwards ttwards     4096 6月  22 10:10 firmware
drwxrwxr-x 31 ttwards ttwards     4096 6月  22 10:16 fs
-rw-rw-r--  1 ttwards ttwards 28738048 6月  22 10:41 Image
drwxrwxr-x  4 ttwards ttwards     4096 6月  22 10:06 include
drwxrwxr-x  2 ttwards ttwards     4096 6月  22 10:21 init
drwxrwxr-x  2 ttwards ttwards     4096 6月  22 10:09 ipc
drwxrwxr-x 14 ttwards ttwards    12288 6月  22 10:14 kernel
drwxrwxr-x 12 ttwards ttwards    16384 6月  22 10:22 lib
-rw-rw-r--  1 ttwards ttwards      565 6月  22 10:08 Makefile
drwxrwxr-x  2 ttwards ttwards    12288 6月  22 10:11 mm
-rw-rw-r--  1 ttwards ttwards    31396 6月  22 10:11 modules.builtin
-rw-rw-r--  1 ttwards ttwards     9051 6月  22 10:21 modules.order
-rw-rw-r--  1 ttwards ttwards   675076 6月  22 10:21 Module.symvers
drwxrwxr-x 23 ttwards ttwards     4096 6月  22 10:16 net
drwxrwxr-x  8 ttwards ttwards     4096 6月  22 10:08 scripts
drwxrwxr-x  5 ttwards ttwards     4096 6月  22 10:09 security
drwxrwxr-x 22 ttwards ttwards     4096 6月  22 10:11 sound
lrwxrwxrwx  1 ttwards ttwards        2 6月  22 10:08 source -> ..
-rw-rw-r--  1 ttwards ttwards  5310929 6月  22 10:21 System.map
drwxrwxr-x  2 ttwards ttwards     4096 6月  22 10:08 usr
drwxrwxr-x  4 ttwards ttwards     4096 6月  22 10:11 virt
-rwxrwxr-x  1 ttwards ttwards 35827984 6月  22 10:21 vmlinux
-rw-rw-r--  1 ttwards ttwards 53490704 6月  22 10:21 vmlinux.o`

**Comment by ttwards** [comment]
> here u are the kernel source of your device: https://oss.sony.net/Products/Linux/Audio/NW-A105.html
> 
> u can compile a kernel with `skip_initramfs` disabled: in `init/initramfs.c`, change the following line
> 
> ```c
> __setup("skip_initramfs", skip_initramfs_param);
> ```
> 
> into
> 
> ```c
> __setup("want_initramfs", skip_initramfs_param);
> ```
> 
> if it works, you will the following log in ur bugreport:
> 
> ```
> Trying to unpack rootfs image as initramfs
> ```

I've tried that, unfortunately it doesn't work.... Here's a bugreport, I can't understand it... I tried KernelSU as well, it worked! But I'm also willing to get Magisk working. 
![图片](https://github.com/topjohnwu/Magisk/assets/105055513/0ea14cfa-48f5-45aa-ab78-3ffee7f82dca)

**Comment by yujincheng08** [comment]
I dont see ur bugreport.

**Comment by ttwards** [comment]
Sorry I forgot that....hhh.
[bug.zip](https://github.com/topjohnwu/Magisk/files/11843487/bug.zip)
Here it is, I figured that KernelSU just SAYS it is working, but nothing works at all.
Perhaps Sony did something to the kernel I guess....

**Comment by ttwards** [comment]
Oh KernelSU says overlayfs isn’t supported in the kernel, is it related?

**Comment by yujincheng08** [comment]
looks like there's nothing to do with `skip_initramfs`.

here's the thing:

magisk modifies ramdisk (which calls initramfs in the kernel), replacing the original `init` with `magiskinit`. but ur dmesg shows that the `init` was not replaced by `magiskinit`. something similar happened on other sony devices, that the `init` was actually `init_real`. but from the kernel cmdline, I still see `init=/init`. its quite troublesome for me to investigate this device. since u hv the ability to compile the kernel, I think u also hv to the ability to find out the core issue? plz try to find out where the actually `init` called by the kernel is located. I can assist u somehow.

FYI, I saw there's a partition named `mmcblk2p5` mounted before init starts, could u see what's this partition is and what's the content of it? maybe u can use ksu to help u with it.

**Comment by ttwardsCN** [comment]
I've mistakenly bricked it, I'm trying to fix it with the emmc dump made before, will try after repairing

**Comment by RQYP** [comment]
> I've mistakenly bricked it, I'm trying to fix it with the emmc dump made before, will try after repairing

Did you ever manage to unbrick?

**Comment by Mdmahim20** [comment]
Hello

**Comment by notcbw** [comment]
> looks like there's nothing to do with `skip_initramfs`.
> 
> here's the thing:
> 
> magisk modifies ramdisk (which calls initramfs in the kernel), replacing the original `init` with `magiskinit`. but ur dmesg shows that the `init` was not replaced by `magiskinit`. something similar happened on other sony devices, that the `init` was actually `init_real`. but from the kernel cmdline, I still see `init=/init`. its quite troublesome for me to investigate this device. since u hv the ability to compile the kernel, I think u also hv to the ability to find out the core issue? plz try to find out where the actually `init` called by the kernel is located. I can assist u somehow.
> 
> FYI, I saw there's a partition named `mmcblk2p5` mounted before init starts, could u see what's this partition is and what's the content of it? maybe u can use ksu to help u with it.

I have a similar device, NW-ZX507. I can confirm, mmcblk2p5 is system_a. Does this mean that the init under system partition is called instead of the one in the ramdisk?

**Comment by Moisz42** [comment]
Hello there! I bricked mine while debloating. Now is stuck on the loading screen waves. Is there something I can do?

**Comment by Moisz42** [comment]
Hi there, I bricked mine while debloating. Is there something I can do? I'm stuck in the boot screen.

**Comment by notcbw** [comment]
> Moisz42

Hey, I have unpacked the firmware 4.06 and you can use fastboot to restore the system partition with it.

Link: [https://drive.google.com/file/d/1hiNf9VFeh0osPwbGtI2NeH9T5AHZtUJK/view?usp=sharing](https://drive.google.com/file/d/1hiNf9VFeh0osPwbGtI2NeH9T5AHZtUJK/view?usp=sharing)

**Comment by Moisz42** [comment]
Thank you. I will try it.

**Comment by Moisz42** [comment]
Okay, so I found A [YouTube ](https://www.youtube.com/watch?v=8yYyhf-2vWw&ab_channel=RanenPo) video to access recovery, and I wiped everything back to stock, BUT! I'm interested in your line of work @notcbw. I will try to follow your instructions

**Comment by Moisz42** [comment]
Hi I tried to get root access using the linked steps, but I cannot disable the AVB using uuu.

I have the following issue:

I have the blank vbmeta.img in my path, but when running the command, I get an error.

```
PS C:\adb> fastboot --disable-verity --disable-verification flash vbmeta_a blank_vbmeta.img
C:\adb\fastboot.exe: unknown option -- disable-verity
```
Since I'm using windows I entered:

 `uuu FB: --disable-verity --disable-verification flash vbmeta_a blank_vbmeta.img`

And I get:
`Error: Unknown Command:FB: --disable-verity --disable-verification flash vbmeta_a blank_vbmeta.img`

I have posted this on the [2019_android_walkman](https://github.com/notcbw/2019_android_walkman), when I encountered it, but OP is not familiar with windows. So I've been stuck.

**Comment by raleighlittles** [comment]
@ttwards Off topic but where did you get your boot.img? I'm trying to root the NW-A306 (newer version)

**Comment by ttwards** [comment]
I get it from the emmc chip directly. I used a programmer to read data from it after I took it off with a heat gun.
BTW, I'm preparing for my gaokao (university entrance exam), I may not appear here until 2024/6/10. Sry for that... If everything goes well, I guess I can see u guys in HKUST. LOL

**Comment by ttwards** [comment]
And the verity issue, you can see the code of fastboot from AOSP, when it excutes "--disable-verity --disable-verification", it actually modifies a few bits of data in boot.img (perhaps another one?... The one with signatures in it, I guess. My memory is really poor and is filled with math & chemistry now..) 
I dont remember it well, you can see in the source and MODIFY IT YOURSELF, uuu DOES NOT support "--disable-verity --disable-verification".
