### ISSUE TITLE
Hidden app payload.bin boot patching hangs at processing

### ISSUE THREAD

**Issue by osm0sis** [topjohnwu/Magisk#7107]
Device: OnePlus 9 Pro
Android version: 13 (Lineage 20)
Magisk version name: a8c4a33e
Magisk version code: 26103

Patching payload.bin in the app seems to have a broken installDir setup currently so it hangs at processing due to no +x on magiskboot:

*magisk_install_log_2023-06-23T11.13.15.log*:
```
- Device platform: arm64-v8a
- Installing: a8c4a33e (26103)
sh: ./magiskboot: Permission denied
- Processing zip file
- Processing payload.bin
```

![Screenshot_20230623-111339_FX](https://github.com/topjohnwu/Magisk/assets/2858716/a846e00f-b39e-4700-9261-438354f66357)

Patching a boot.img file directly sets up installDir correctly and still works as expected:

![Screenshot_20230623-111632_FX](https://github.com/topjohnwu/Magisk/assets/2858716/c60859c4-6499-43c8-998e-2236dc82bfea)

**Comment by osm0sis** [comment]
Interestingly, it also worked fine on an older ROM zip that contains a boot.img file in the zip root.

**Comment by vvb2060** [comment]
Before, the script was executed first, so chmod +x was executed, and now magiskboot is executed first.

**Comment by vvb2060** [comment]
Only hidden app have this issue
