### ISSUE TITLE
[Feature Request] add few more options for payload.bin extraction

### ISSUE THREAD

**Issue by HemanthJabalpuri** [topjohnwu/Magisk#7110]
Device: any
Android version: any
Magisk version name: a8c4a33e
Magisk version code: 26103

Since magiskboot already supports extraction of any partition, please add support for `listing the partitions` that are in payload.bin and support for `extracting all` at once without any partition names mentioned.

Thanks

**Comment by romanovj** [comment]
you can use payload-dumper-go in termux

./payload-dumper-go --help
Usage of ./payload-dumper-go:
  -c int
        Number of multiple workers to extract (shorthand) (default 4)
  -concurrency int
        Number of multiple workers to extract (default 4)
  -l    Show list of partitions in payload.bin (shorthand)
  -list
        Show list of partitions in payload.bin
  -o string
        Set output directory (shorthand)
  -output string
        Set output directory
  -p string
        Dump only selected partitions (comma-separated) (shorthand)
  -partitions string
        Dump only selected partitions (comma-separated)
