### ISSUE TITLE
"Direct Install" fails on arm (v7a) devices.

### ISSUE THREAD

**Issue by ipdev99** [topjohnwu/Magisk#7114]
Device: Nexus 7 (2013)
Android version: Android 13 (Lineage 20)
Magisk version name: dbc2236dd
Magisk version code: 26103

Device: Nexus 5
Android version: Android 7.x (Lineage 14.1)
Magisk version name: dbc2236dd
Magisk version code: 26103

Using the "Direct Install" option fails on arm32 (v7a).
The "Select and Patch a File" option works as expected.

---

The correct boot partition is found.

Nexus 7 (2013) "Direct Install"
```
- Target image: /dev/block/mmcblk0p14
- Device platform: armeabi-v7a
- Installing: dbc2236dd-ip (26103)
- Unpacking boot image
Invalid argument (os error 22)
! Unsupported/Unknown image format
! Installation failed.
```
<i>by-name</i>
`lrwxrwxrwx 1 root root   21 2023-06-22 19:05 boot -> /dev/block/mmcblk0p14`

Nexus 5 "Direct Install"
```
- Target image: /dev/block/mmcblk0p19
- Device platform: armeabi-v7a
- Installing: dbc2236dd-ip (26103)
- Unpacking boot image
Invalid argument (os error 22)
! Unsupported/Unknown image format
! Installation failed
```
<i>by-name</i>
`lrwxrwxrwx 1 root root  21 1970-02-04 19:28 boot -> /dev/block/mmcblk0p19`

---

Using the "Select and Patch a File" option.
- No problem patching the stock (lineage) boot image pulled from the rom.
- No problem patching a previously Magisk patched boot image.
- No problem using `dd` to dump the boot partition into an image file and patching it with Magisk.

**Comment by ipdev99** [comment]
Looks like one of the changes (commits) from the 12.Jun is the reason.
<i>The error also causes Magisk to fail a complete uninstall.</i>

12.Jun (top commit 9d6f6764c)
```
****************************************
 Magisk 9d6f6764c-ip(26102) Uninstaller
****************************************
- Target image: /dev/block/mmcblk0p19
- Device platform: armeabi-v7a
- Unpacking boot image
Invalid argument (os error 22)
! Unsupported/Unknown image format
```

10.Jun (top commit c1038ac6f)
```
****************************************
 Magisk c1038ac6f-ip(26102) Uninstaller
****************************************
- Target image: /dev/block/mmcblk0p19
- Device platform: armeabi-v7a
Parsing boot image: [/dev/block/mmcblk0p19]
HEADER_VER	[0]
KERNEL_SZ	[8511872]
RAMDISK_SZ	[1684385]
SECOND_SZ	[0]
EXTRA_SZ        [0]
OS_VERSION	[7.1.2]
OS_PATCH_LEVEL  [2021-06]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyHSL0,115200,n8 androidboot.hardware=hammerhead user_debug=31 maxcpus=2 msm_watchdog_v2.enable=1 androidboot.bootdevice=msm_sdcc.1 buildvariant=userdebug]
CHECKSUM        [42695bc066805efaf096edca35f7b869d3ff0168000000000000000000000000]
- Unpacking boot image
KERNEL_DTB_SZ   [1405424]
ZIMAGE_KERNEL
```

**Comment by ipdev99** [comment]
Since I run personal builds, from the official branch, it was recommended to me to use `git bisect` to find the origin of the error.

The upper half of the (12.Jun.2023) commits had an error patching even a stock image with the "Select and Patch a File" option.
<i>I expected this since it was fixed later. :wink:</i>

The issue with arm (v7a) "Direct Install" starts with:
```
[ip@lost Magisk]$ git bisect good 
23c1f0111bb23d56d63fda0ca57e18c15e6b7811 is the first bad commit
commit 23c1f0111bb23d56d63fda0ca57e18c15e6b7811
Author: topjohnwu <topjohnwu@gmail.com>
Date:   Mon Jun 12 01:07:43 2023 -0700

    Improve Rust implementation
    
    - Move mmap_file implementation into Rust
    - Introduce Utf8CStr as the better c-string type to use

 native/src/base/cxx_extern.rs |  30 ++++++--
 native/src/base/files.cpp     |  30 +++-----
 native/src/base/files.hpp     |   4 +-
 native/src/base/files.rs      | 173 ++++++++++++++++++++++++++++++++----------
 native/src/base/lib.rs        |   4 +
 native/src/base/misc.rs       | 156 +++++++++++++++++++++++++++++++++++--
 native/src/boot/cpio.rs       |  62 +++++----------
 native/src/boot/payload.rs    |   4 +-
 native/src/boot/ramdisk.rs    |   5 +-
 9 files changed, 351 insertions(+), 117 deletions(-)
[ip@lost Magisk]$
```

Normally I know enough to follow along but..

I know nothing about 'rust'. :smile:

**Comment by yujincheng08** [comment]
This is because @topjohnwu hardcoded `BLKGETSIZE64` as `0x80081272`. But it's not true on 32bit devices.
