### ISSUE TITLE
Please consider making PREINITDEVICE optional.

### ISSUE THREAD

**Issue by mohrezaei** [topjohnwu/Magisk#7125]
With the introduction of the PREINITDEVICE in v26, the following usages of Magisk has become much harder:

- Per the docs: "any installation of Magisk v26+ using custom recovery will be incomplete"
- It's no longer possible to run `boot_patch.sh` on anything other than the actual device, because it invokes a new dependency: `magisk32/64` (it was only dependent on `magiskinit` and widely available OS utils before).
- It's much harder to streamline Magisk in a build-from-source environment. 
- It's much harder to use Magisk on a bootlocked (with a custom key) device. On such a device, installation requires properly signing of the bootimg.

I don't really know how many modules make use of `sepolicy.rules`, nor how many different devices can use that now vs before PREINITDEVICE. 

If it is at all possible, please consider making PREINITDEVICE optional.

Device: Any
Android version: Any
Magisk version name: 26103
Magisk version code: 26103

**Comment by mohrezaei** [comment]
Logs of running `boot_patch.sh` on a Linux x86 host for an arm boot img.
[patch-26103.txt](https://github.com/topjohnwu/Magisk/files/11885151/patch-26103.txt)
[patch-25001.txt](https://github.com/topjohnwu/Magisk/files/11885153/patch-25001.txt)

**Comment by mohrezaei** [comment]
The coredump in 26103 might be #7109 . If not, I can file another bug for it.

**Comment by yujincheng08** [comment]
`PREINITDEVICE` is actually optional. You can predefine the `PREINITDEVICE` environment variable.

**Comment by mohrezaei** [comment]
What value can I set the env variable to for it not to interfere with the boot process?
