### ISSUE TITLE
Magisk Manager默认root为MagiskSU，不分辨是否使用的是其它SU

### ISSUE THREAD

**Issue by rdvogp93201** [topjohnwu/Magisk#713]
Magisk Manager默认root为MagiskSU，其它SU(比如MIUI开发版自带SU)没有magiskpolicy工具，导致无法打开数据库文件(db_sepatch无效)。应用程序打开就崩溃，无法安装Magisk。
在6.0.1之前，因为有`Data.magiskVersionCode < Const.MAGISK_VER.FBE_AWARE`，应用程序不崩溃。

**Comment by topjohnwu** [comment]
Merged
