### ISSUE TITLE
Patching AP file deletes stock boot.mg from tar on Samsung S23

### ISSUE THREAD

**Issue by DrKetan** [topjohnwu/Magisk#7132]
Device:Samsung S23 Ultra
Android version:13
Magisk version name:26.1
Magisk version code:26103

Latest Magisk while Patching AP files, successfully patching init_boot.img and root works fine but it deletes stock boot.img file from AP tar
This cause when someone update firmware by just flashing Magisk patched AP (without updating stock firmware), kernel doesn't get update or may cause bootloop if old kernel doesn't work on updated firmware.
Attached screenshot of Stock AP file & Magisk Patched AP file

![no_boot_img](https://github.com/topjohnwu/Magisk/assets/16444023/a0bb2d4b-633a-454b-a37e-14bb4ddf08ad)
Patched AP

![stock_AP](https://github.com/topjohnwu/Magisk/assets/16444023/60fc1fd2-aa50-4c71-9d26-78dcb7e3530d)
Stock AP

**Comment by BlackMesa123** [comment]
@DrKetan have you checked whether or not #7133 fixes the issue?
https://github.com/topjohnwu/Magisk/actions/runs/5431075757

**Comment by DrKetan** [comment]
> @DrKetan have you checked whether or not #7133 fixes the issue? https://github.com/topjohnwu/Magisk/actions/runs/5431075757

Yes, I have tested 26103 and it's fixed. Thank you very much
