### ISSUE TITLE
Can't boot on Magisk higher than v23.0

### ISSUE THREAD

**Issue by fortifying** [topjohnwu/Magisk#7138]
Device: Realme 3 Pro
Android version: 10
Magisk version name: Stable
Magisk version code: 26103

Can't boot while flashing magisk higher than 23.0, it stucked on splash screen then go back to recovery, can't take logs also..

Device doesn't have ramdisk, trying to patch recovery.img but same issue

It was fine on Android 11-13. but most Android 10 of this device can't boot v24 or higher. i just want to know why this happen.

Attached files are boot.img
[magisk_patched-26100_GJS2F.zip](https://github.com/topjohnwu/Magisk/files/11947488/magisk_patched-26100_GJS2F.zip)

**Comment by pndwal** [comment]
So does patching boot.img or flashing as .zip installer from custom recovery work with A11+ on this device, or have you always needed to patch recovery.img?

**Comment by fortifying** [comment]
> So does patching boot.img or flashing as .zip installer from custom recovery work with A11+ on this device, or have you always needed to patch recovery.img?

both patching boot.img and flash as zip working on A11+. didn't ever tried patch recovery.img on there tho. it's just make me confuse. can't take logs because when in splash screen it goes back to recovery. patching recovery.img did the same, it stuck on splash screen loop and never going to recovery

**Comment by yujincheng08** [comment]
> i just want to know why this happen

we want to know as well. but without any log, how come we know? closed because of no log.
