### ISSUE TITLE
Issues patching July 2023 Boot Image

### ISSUE THREAD

**Issue by LostInIgnorance** [topjohnwu/Magisk#7140]
Device: Pixel 6 Pro
Android version: TQ3A.230605.010
Magisk version name: Debug
Magisk version code: a8c4a33e (26103) (D)

I am unable to patch the July 2023 Pixel 6 Pro update boot.img

[magisk_install_log_2023-07-06T07.39.28[2].log](https://github.com/topjohnwu/Magisk/files/11968424/magisk_install_log_2023-07-06T07.39.28.2.log)

**Comment by DebianArch64** [comment]
> Device: Pixel 6 Pro Android version: TQ3A.230605.010 Magisk version name: Debug Magisk version code: [a8c4a33](https://github.com/topjohnwu/Magisk/commit/a8c4a33e918dac301cbc8fb197200b34df4c4d6c) (26103) (D)
> 
> I am unable to patch the July 2023 Pixel 6 Pro update boot.img
> 
> [magisk_install_log_2023-07-06T07.39.28[2].log](https://github.com/topjohnwu/Magisk/files/11968424/magisk_install_log_2023-07-06T07.39.28.2.log)

Reverting the magisk version helped for me - I looked for canary builds before the breaking CPIO changes

**Comment by LostInIgnorance** [comment]
@DebianArch64 Thanks for the heads up. I will use the Stable build for a while again
