### ISSUE TITLE
OnePlus 11 5G 13.1, direct install "Unable to find preinit dir", patching boot.img fails "Unable to patch ramdisk", patching payload.bin "No boot image found"

### ISSUE THREAD

**Issue by asheroto** [topjohnwu/Magisk#7159]
Device: OnePlus 11 5G (CPH2449)
Android version: 13
Magisk version name: 26.1
Magisk version code: 26103

## Summary

The titled suggests multiple issues, but as they are most likely related, I decided to put them all in one. Let me know if I need to separate them.

This may be related to issue #7109 as it is similar, but this is Android 13.1, not Android 14.

1.) When performing a direct install, I get an error that says "Unable to find preinit dir" after "Flashing new boot image". This may be a warning rather than an error, as **the device does actually boot without issue** after patching.
<details><summary>Details</summary>
<p><img src="https://github.com/topjohnwu/Magisk/assets/49938263/213d1e44-305b-44fb-8c5c-9cd297d3ee5c)"></p>
</details> 

2.) When performing a patch on the `boot.img` file, an error occurs that says "Unable to patch ramdisk".
<details><summary>Details</summary> 

```
- Device platform: arm64-v8a
- Installing: a8c4a33e (26103)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/data/user_de/0/r.qth.v.vbt/install/boot.img]
HEADER_VER      [4]
KERNEL_SZ       [46406144]
RAMDISK_SZ      [0]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2023-06]
PAGESIZE        [4096]
CMDLINE         []
KERNEL_FMT      [raw]
VBMETA
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
resetprop: get prop [ro.crypto.state]: [encrypted]
�preinit device: persist
- Pre-init storage partition: persist
�Add file [init] (100750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add file [overlay.d/sbin/magisk32.xz] (100644)
Add file [overlay.d/sbin/magisk64.xz] (100644)
Add file [overlay.d/sbin/stub.xz] (100644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Failed to process cpio: No such file or directory (os error 2)
! Unable to patch ramdisk
! Installation failed
```

</details>

3.) When performing a patch with the `payload.bin` file, an error occurs that says "No boot image found".

Will post logs here later and reply.

## ROM

These are the unpatched, original files.

[CPH2449_11_13.1.0.580(EX01)_BootFiles.zip](https://public.asheroto.com/android/oneplus/CPH2449_11_13.1.0.580%28EX01%29_BootFiles.zip) - boot.img, ini_boot.img, vbmeta.img, vendor_boot.img

[CPH2449_11_13.1.0.580(EX01)_Full_Dumped_Payload.zip](https://public.asheroto.com/android/oneplus/CPH2449_11_13.1.0.580%28EX01%29_Full_Dumped_Payload.zip) (dumped payload.bin using [payload-dumper-go](https://github.com/ssut/payload-dumper-go))

[CPH2449_11_13.1.0.580(EX01)_Full.zip (payload.bin)](https://public.asheroto.com/android/oneplus/CPH2449_11_13.1.0.580%28EX01%29_Full.zip)

[CPH2449_11_13.1.0.580(EX01)_Incremental.zip (payload.bin)](https://public.asheroto.com/android/oneplus/CPH2449_11_13.1.0.580%28EX01%29_Incremental.zip) - in case you want the incremental

## Log files

[cat /proc/mounts](https://gist.github.com/asheroto/a6b2b385920270699351fbc52ae72f76)

[magisk.log](https://gist.github.com/asheroto/98bbf3130f1305767a8276b9648a6858)

## Note
Because I was still able to boot and it did not cause any issues that I'm aware of with the direct install, I don't think this is necessarily an urgent issue. However, because it won't patch the boot files, I thought it was important to bring up.

I can get the dmesg or logcat if needed. Just let me know when to run it. :-)

**Comment by yujincheng08** [comment]
all screenshots are the same

also, u should save log and send them, other than posting screenshots

**Comment by asheroto** [comment]
Ah crap thanks. Clipboard fail.

I don't have the logs for 1, posted the logs for 2. Before I do 3, does processing a payload.bin file only extract it and patch? Or does it flash?

**Comment by yujincheng08** [comment]
the second iasue is #7109

**Comment by asheroto** [comment]
Thanks. I am assuming the third issue is related so will close this for now. Thank you.
