### ISSUE TITLE
Zygisk has umount2 error

### ISSUE THREAD

**Issue by mhmtnasir** [topjohnwu/Magisk#7161]
Device: Asus Zenfone 2 Laser (ZE550KL)
Android version: 7.1.2
Magisk version name: a8c4a33e
Magisk version code: 26103

Log attached. Zygisk will keep saying No in manager. [magisk.log](https://temp.sh/rXZLG/magisk.log)

**Comment by mhmtnasir** [comment]
Why was this closed with no response??

**Comment by NotNoelChannel** [comment]
> Why was this closed with no response??

They aren't planning to fix the issue
