### ISSUE TITLE
! Unable to repack boot image!

### ISSUE THREAD

**Issue by youyim123** [topjohnwu/Magisk#717]
v17.4-c2b01637
device：nubia Z18
cpu：sdm845
![screenshot_2018-10-22-13-47-46](https://user-images.githubusercontent.com/19865880/47279093-38241400-d601-11e8-90dd-db575553db76.png)
[magisk_install_log_20181022_134201.log](https://github.com/topjohnwu/Magisk/files/2500274/magisk_install_log_20181022_134201.log)

**Comment by topjohnwu** [comment]
FIxed

**Comment by silverik13** [comment]
Fixed how??
I have the same problem.
Want to install Magisk v18 without twrp
Same message as the pic above
What am i doin g wrong????

**Comment by silverik13** [comment]
[magisk_install_log_20190108_114116[1].log](https://github.com/topjohnwu/Magisk/files/2736362/magisk_install_log_20190108_114116.1.log)

**Comment by silverik13** [comment]
thankls for the quick reaction

**Comment by silverik13** [comment]
> @silverik13 The particular bug causing the issue mentioned here was fixed, yes. You might have another... Only way to know more about what's going on is with logs.

I uploaded logs. Can you help me?
