### ISSUE TITLE
"Superuser Request" getting blocked by the application

### ISSUE THREAD

**Issue by alx-xlx** [topjohnwu/Magisk#7170]
The Superuser Request gets overshadowed by another app before I can even Grant the permission. Its so fast that the the application gets gets on top of the request and I am unable to make any choice.

The app is httptoolkit and you can produce this issue by enabling the Android adb from the Pc version of httptoolkit

Can someone take a look at it, I also checked the Superuser section of magisk to see if it showed the current request there but it didn't.

The request was for com.android.shell

Device: Redmi Note 10
Android version: 12
Magisk version name: 26.1
Magisk version code: 26104

**Comment by vvb2060** [comment]
https://developer.android.com/guide/components/activities/background-starts
According to the specification, notifications should indeed be used instead of popups.  But considering usage habits, this may not be implemented.
