### ISSUE TITLE
I noticed that zygisk modules such as lsposed are loaded late, is there any way to load the module before the system_server process is created?

### ISSUE THREAD

**Issue by lt541013990** [topjohnwu/Magisk#7174]
Device: 服务器上的板卡、具体型号我也不清楚 sorry
Android version: android 10
Magisk version name: stable
Magisk version code: 26104

我调试lsposed时，发现zygisk加载lsposed时机是偏晚的，有办法把这个模块加载时机提到system_server创建前这种时机么？
我个人日志的tag是 LSP-TAG
https://github.com/topjohnwu/Magisk/files/12115819/2023_7_20_log.txt

**Comment by vvb2060** [comment]
看不懂

**Comment by lt541013990** [comment]
> 

zygisk加载运行它的模块时机是可控的么？

**Comment by yujincheng08** [comment]
![image](https://github.com/topjohnwu/Magisk/assets/5022927/e39ae778-2bee-40f1-95c6-6bdefd1732e3)
这不是 hook 上了吗

**Comment by lt541013990** [comment]
> ![image](https://user-images.githubusercontent.com/5022927/255103346-e39ae778-2bee-40f1-95c6-6bdefd1732e3.png) 这不是 hook 上了吗

那为什么system_server进程被创建时，forkCommon并没有被执行到呢?

    public static void forkCommon(boolean isSystem, String niceName, IBinder binder) {
        Startup.initXposed(isSystem, niceName, ILSPApplicationService.Stub.asInterface(binder));
        if ((niceName.equals(BuildConfig.MANAGER_INJECTED_PKG_NAME) || niceName.equals(BuildConfig.DEFAULT_MANAGER_PACKAGE_NAME))
                && ParasiticManagerHooker.start()) {
            Utils.logI("Loaded manager, skipping next steps");
            return;
        }
        Utils.logI("Loading xposed for " + niceName + "/" + Process.myUid());
        Startup.bootstrapXposed();
    }
