### ISSUE TITLE
Magisk won't work after installation and It's not a key sequence issue

### ISSUE THREAD

**Issue by 940842546** [topjohnwu/Magisk#7179]
Device: Samsung W2020
Android version: 12
Magisk version name: d390ca2f
Magisk version code: 26104
This is the log file: [bugreport2023072517.zip](https://github.com/topjohnwu/Magisk/files/12159550/bugreport2023072517.zip)
It's not a key sequence issue
This is recording: https://s-share.samsungcloudcn.com/rdqZVnkjkoUD
(Recovery Key Combo) → (Splash screen) → (Release all buttons) → (System with Magisk) not work
(Recovery Key Combo) → (Splash screen) → (Long press volume up) → (Recovery Mode) can't into recovery

**Comment by yujincheng08** [comment]
the log show it's apparently a key combo issue.

**Comment by 940842546** [comment]
> the log show it's apparently a key combo issue.

u can see the recording it's not a key combo issue.

**Comment by 940842546** [comment]
> the log from #7178 shows it's apparently a key combo issue.

log shows that maybe magisk Misjudgment caused the problem

**Comment by yujincheng08** [comment]
I am pretty sure Magisk wont detect a false positive KEYUP. I saw from the log that you are trying to boot to recovery mode and Magisk does avoid loading itself. I don't know why it boots to the system (rather than recovery mode) but I don't think it's Magisk's issue.

**Comment by 940842546** [comment]
> I am pretty sure Magisk wont detect a false positive KEYUP. I saw from the log that you are trying to boot to recovery mode and Magisk does avoid loading itself. I don't know why it boots to the system (rather than recovery mode) but I don't think it's Magisk's issue.

i find the problem 
Document description is not clear
Release the button on this page to load magisk correctly
![QQ截图20230725175703](https://github.com/topjohnwu/Magisk/assets/8674798/05dc4d2a-adfb-4571-8a89-3675551b9c35)

**Comment by yujincheng08** [comment]
it's your misunderstanding :)
