### ISSUE TITLE
Patched boot img flashing error on UNISOC CPU based android.

### ISSUE THREAD

**Issue by mdrakibur179** [topjohnwu/Magisk#7183]
I am having issue in flashing patched boot img in my phone. Magisk successfully patched it. But when I try to flash it using terminal it says "Failed (remote: 'write img failed')"

![IMG_20230723_010744_HDR](https://github.com/topjohnwu/Magisk/assets/115276185/8cc8e114-6933-4b77-a844-8804b8401757)

Device: Symphony Z33
Android version: 11
Magisk version name: 26.1
Magisk version code: 26104

**Comment by mdrakibur179** [comment]
All the drivers are installed properly. I test it by Linux also. It also unable to flash the patched boot img.

**Comment by canyie** [comment]
I also face the same issue on an Unisoc device. I fixed it by using ReserachDownload instead of fastboot to flash the image:
1. Download ReserachDownload tool and stock firmware
2. Open ReserachDownload and select the firmware
3. Click "Settings", un-tick all partitions except `FDL1`, `FDL2` and `boot`.
4. Double click the file path of `BOOT`, you will see a small button. Click it and select your patched boot image.
5. Click "Start". Fully shutdown your device, long press volume down, connect your device to your PC. Do not release the volume down button until you see `FDL2` is flashed. Do not disconnect your device until you see "PASSED".
6. Flashing is done. Disconnect your device and start it. You should be able to enjoy Magisk now~

I think Unisoc devices have some restrictions that prevent us from flashing boot partition by fastboot, so there is nothing to do with Magisk.

**Comment by mdrakibur179** [comment]
After doing this my phone is in bootloop. I need to fix this.
Is there any other way to root this UNISOC T610 CPU android?

**Comment by matrock47** [comment]
I have same issue when flashing patched boot img on unisoc device

**Comment by Axodique** [comment]
This will put you in a bootloop. Though fortunately you can use ResearchDownload to flash the original boot img again without losing any files on your phone. Sorry for upping dad issue but I'm just writing this as a warning for other people.

**Comment by canyie** [comment]
I found other ways to flash boot images on Unisoc device:

- Some Unisoc A/B devices don't recognize the active slot in bootloader mode. You will need to manually flash the active slot. For example, if `fastboot getvar current-slot` gives you `current-slot: a`, use `fastboot flash boot_a /path/to/magisk_patched.img`

- If the above didn't work, you can also try to reboot to `fastbootd` first by `adb reboot fastboot` or `fastboot reboot fastboot`, then use `fastboot flash boot /path/to/magisk_patched.img`

**Comment by Axodique** [comment]
Still the same bootloop, not matter what. I think in my phone's case the patched rom might be the problem.

**Comment by Fyramiz** [comment]
Did you try fastbootd(if device is super partition), and did you try SPD?

**Comment by Axodique** [comment]
Pretty sure it's a ROM issue, considering all flashing methods lead to the same thing. The phone isn't really meant to be rooted considering I had to go to a pretty roundabout way of unlocking the bootloader ([this one](https://www.hovatek.com/forum/thread-32287.html))

**Comment by Fyramiz** [comment]
Is your bootloader even unlocked then unlock it using the python script(unisoc-unlock)

**Comment by Axodique** [comment]
Yes... It's unlocked... I just explained how I unlocked it...

**Comment by Fyramiz** [comment]
> Pretty sure it's a ROM issue, considering all flashing methods lead to the same thing. The phone isn't really meant to be rooted considering I had to go to a pretty roundabout way of unlocking the bootloader ([this one](https://www.hovatek.com/forum/thread-32287.html))

Does the phone boot to the second stage loader? AKA you see the other message that says that the phone bootloader is unlocked, if only the first, then it's not a rom issue, if the second there is a PROBABILITY of the rom causing it, also if you have a device backup, flash a Treble-Droid based GSI(my experience with normal GSI's are bad on my unisoc device)

**Comment by leetree2001** [comment]
Yeah, I'm pretty sure the problem is you need a custom vbmeta-sign.img after unlocking the bootloader.. in the process of attempting to create one, try to get back to yah. Maybe, with any luck 🤞🤞

**Comment by leetree2001** [comment]
Yes it goes to lock flag is unlocked, skipping verify, when using some GSI's.a/b. But can't flash boot.img ,magisk-patch, it always fails something about to many links. I was in the process of checking out hovateck, they were saying you have to use custom vbmeta-sign.img. it's just a pain extracting key's and so forth.

**Comment by Seriousattempts** [comment]
> Yeah, I'm pretty sure the problem is you need a custom vbmeta-sign.img after unlocking the bootloader.. in the process of attempting to create one, try to get back to yah. Maybe, with any luck 🤞🤞

@leetree2001 is correct, you need to sign the boot.img and create a vbmeta.img along with it. You can refer to https://www.hovatek.com/forum/thread-32664.html, I've used that that has worked, along with https://github.com/skompc/retroid-pocket-3-plus-autoroot

@mdrakibur179 @matrock47 @Axodique @canyie
