### ISSUE TITLE
Manager6.0.1,更新bug死循環

### ISSUE THREAD

**Issue by MAYBreath** [topjohnwu/Magisk#719]
原先用模擬器可以順利安裝運行Manager6.0.0，然後進行安裝magisk

現在更新了Manager6.0.1后，每個模擬器都是FC閃退，
裝回Manager6.0.0就正常，但是程式會強制要求更新到最新的Manager，不更新到最新的還不讓安裝magisk，但是一安裝到最新的6.0.1又會閃退，現在根本沒法用了。。
可否不要強制更新最新才可以安裝magisk？或者修復一下閃退bug，謝謝。。

**Comment by fgotemp** [comment]
巧了，我也遇到了这个问题。6.0.1版本在genymotion模拟器里一旦赋予root权限，magisk manager就会闪退。不给root权限可以打开。。。
