### ISSUE TITLE
Cannot decompress ARM zImages

### ISSUE THREAD

**Issue by breakersvd** [topjohnwu/Magisk#720]
Hi @topjohnwu 

Samsung released a new device (and it seems this will be applied on the rest of future releases):
* Galaxy J6+ 2018 (SM-J610F) Android 8.1.0 Qualcomm Snapdragon

**EDIT:** Also found in:
* Galaxy J4+ 2018 (SM-J415F) Android 8.1.0 Qualcomm Snapdragon

And the boot image of this device comes with an compressed (custom `gzip` format) `kernel` part so nothing is able to change by hexpatching (skip_initramfs, defex, RKP......)

The output of `file kernel` linux command is:
`Linux kernel ARM boot executable zImage (little-endian)`

And the output of `binwalk kernel` linux command is:

> DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
> 36            0x24            Linux kernel ARM boot executable zImage (little-endian), load address: "0x00000000", end address: "0x00A03B08"
> 16495         0x406F          gzip compressed data, maximum compression, from Unix, NULL date (1970-01-01 00:00:00)
> 7825931       0x776A0B        MySQL ISAM compressed data file Version 1

And the `magiskboot` unpacking command gives `KERNEL_FMT      [raw]` output result but is not raw.
Here is the boot image for J610F [boot.zip](https://github.com/topjohnwu/Magisk/files/2501938/boot.zip)

The device in my hand if you want to test anything

Regards

**Comment by xerta555** [comment]
Samsung should calm down a little bit to constantly change the format and compression level of the deboot images of its devices...

**Comment by topjohnwu** [comment]
@breakersvd I would love to invite you to Magisk's development Slack group since you are one of the the main Samsung helper here. If you'd love to join, I just need your email address! I would be really grateful if you're willing to join, since Magisk always lags behind Samsung device support.

If you don't want your email address to be in the public, you can send me privately to topjohnwu@gmail.com

**Comment by breakersvd** [comment]
@topjohnwu 
I'm ready for that, here is my Email: sshsystems.pay@gmail.com.

Anyway i want to tell that i found a way to split the new kernel type and decrypt and decompress it and successfully rebuilding, but i just wait until releasing the source by Samsung to get some new patches and i will test and give you the final results and working plan.

Regards

**Comment by haroon-ali** [comment]
I've tried to install magisk using patch boot image on sm-j415f and it fails.
I've tried to install it using twrp, it claimed to be installed but it is not functioning. Not able to actually use root or install any modules.
I tried with latest versions of Magisk Manager v6.1.0 and Magisk v18.0
Attached is the official boot.img

[boot.zip](https://github.com/topjohnwu/Magisk/files/2706744/boot.zip)

**Comment by haroon-ali** [comment]
Is it fixed? I found no mention in commit log?
