### ISSUE TITLE
why libcxx removing exception and RTTI support.

### ISSUE THREAD

**Issue by androiddisk** [topjohnwu/Magisk#7211]
Device:Quantum Go Q2
Android version:7.1.1
Magisk version name:https://github.com/topjohnwu/Magisk/commit/66e30a772395423d124ac84c16ddf384d6c3bc10
Magisk version code:26104

The question I asked is not related to the use of Magisk. If you are not willing to answer my question
The initial exposure to NDK development started with masks. I am used to the development environment of masks, but I have a question about libcxx that I haven't understood yet. I can't use the c++ `throw` command now
May I ask why it is necessary to operate libcxx removal exception and RTTI support
If I delete the parameters of libcxx android.mk
```
LOCAL_ CPPFLAGS= -D_LIBCPP_NO_EXCEPTIONS \
-D_LIBCPP_NO_RTTI \
-D_LIBCXXABI_NO_EXCEPTIONS
```
Can we use the development environment of magisk to compile regular binary or lib.so

我的问题与Magisk使用无关，如果不愿意回答我的问题，恳请不要立马关闭我的问题，希望有人帮我解答一下，非常感谢

刚开始接触ndk开发就是从面具开始的。习惯了面具的开发环境，libcxx 有个疑问一直没弄懂。现在没办法用 throw 命令
 请问为什么一定要操作libcxx removing exception and RTTI support.

如果我删除libcxx android.mk的参数 
```
LOCAL_CPPFLAGS= -D_LIBCPP_NO_EXCEPTIONS \
-D_LIBCPP_NO_RTTI \
-D_LIBCXXABI_NO_EXCEPTIONS
```
然后用magisk的开发环境去编译普通二进制或者lib.so 可以么

**Comment by yujincheng08** [comment]
exception and rtti drastically increase the binary size and bring no advantages.
