### ISSUE TITLE
ro.boot.vbmeta.device could not be found on many devices

### ISSUE THREAD

**Issue by xiaoxindada** [topjohnwu/Magisk#7219]
Device: OnePlus 11
Android version: 13
Magisk version name: 4000369
Magisk version code: 26105

`ro.vbmeta.device prop` doesn't seem to be found on OnePlus 11 devices but there is `ro.boot.vbmeta.device_state` and it is indeed a device using vbmeta  /`dev/block/bootdevice-by-name/vbmeta_a` is exists

[getprop_log.txt](https://github.com/topjohnwu/Magisk/files/12290077/getprop_log.txt)

**Comment by osm0sis** [comment]
Same on OnePlus 9 Pro: https://github.com/topjohnwu/Magisk/pull/7216#issuecomment-1669835807

**Comment by vvb2060** [comment]
Only A/B devices have this property, which is better than completely unusable path test.

**Comment by osm0sis** [comment]
OnePlus 9 and 11 are A/B devices...

**Comment by osm0sis** [comment]
How about checking ro.product.ab_ota_partitions for vbmeta?

**Comment by vvb2060** [comment]
```
ro.product.ab_ota_partitions u:object_r:ota_prop:s0 exact string
```
app does not have permission to access ota_prop

**Comment by osm0sis** [comment]
> ```
> ro.product.ab_ota_partitions u:object_r:ota_prop:s0 exact string
> ```
> 
> app does not have permission to access ota_prop

Really? Damn, accessing it worked fine from unrooted prompt in Terminal Emulator app.

**Comment by vvb2060** [comment]
```
type ota_prop { property_type core_property_type system_property_type system_public_property_type }
```

Sorry, I only searched for allow rules and forgot to look at attribute, it is system_public_property_type

**Comment by osm0sis** [comment]
> ```
> type ota_prop { property_type core_property_type system_property_type system_public_property_type }
> ```
> 
> Sorry, I only searched for allow rules and forgot to look at attribute, it is system_public_property_type

Hey, that's great!

So perhaps `|| getprop ro.product.ab_ota_partitions | grep -w vbmeta` on what you have could be the best for coverage.

**Comment by osm0sis** [comment]
> > I just did some experiments and something like this could work:
> > `getprop ro.product.ab_ota_partitions | grep -w vbmeta`
> > since grep properly parses , as a word separator (and not _).
> 
> I think that's a good idea but you need to add the -o option here
> 
> getprop ro.product.ab_ota_partitions | grep -w vbmeta abl,aop,aop_config,bluetooth,boot,cpucp,devcfg,dsp,dtbo,engineering_cdt,featenabler,hyp,imagefv,init_boot,keymaster,modem,my_bigball,my_carrier,my_company,my_engineering,my_heytap,my_manifest,my_preload,my_product,my_region,my_stock,odm,oplus_sec,oplusstanvbk,product,qupfw,recovery,shrm,splash,system,system_dlkm,system_ext,tz,uefi,uefisecapp,vbmeta,vbmeta_system,vbmeta_vendor,vendor,vendor_boot,vendor_dlkm,xbl,xbl_config,xbl_ramdump OP591BL1:/ # getprop ro.product.ab_ota_partitions | grep -ow vbmeta getprop ro.product.ab_ota_partitions | grep -ow vbmeta vbmeta

-o just affects the output from grep, the internal matching still occurred and only matches ,vbmeta, because of -w. 🙂
