### ISSUE TITLE
Critical report on sudden increase in root detection bypass mechanism of magisk in the debug version 26105 (D) ("ee34f775")

### ISSUE THREAD

**Issue by Navneet-Kumar-Singh** [topjohnwu/Magisk#7229]
Device: Realme 5i (RMX2030) 
Android version: 10
Magisk version name: "ee34f775"
Magisk version code: 26105

Critical Feedback Report for topjohnwu (please take this into consideration while updating the stable build):
Till now YONO SBI app (bank app with best root detection in India) from play store was detecting magisk (all versions till latest stable build and till 2nd last debug build , note that this issue is resolved in latest debug 26105 (D) ("ee34f775") build of magisk). Yono app's security improvement responsibility has been provided this year to IBM.

All versions apart from the only working latest debug build (version above) , failed to hide themselves from the Yono SBI app , even though I hide magisk app , used shamiko with zygisk on, enforce denylist off and then including yono app in the deny list. Shamiko was working in blacklist mode.even after all this the app crashed itself as it detected magisk . This continued to happen until and unless I uninstalled magisk completely using the uninstall option in magisk app. After uninstall , yono SBI app started to work again when there was no magisk. Thus happened with all magisk versions except the debug version mentioned above.

Now when I clean install the debug version mentioned above then this issue is resolved and yono starts to work/start again(stops crashing itself). Mind that this yono app uses the best root/magisk detection mechanism for any banking app currently possible in India atleast.

So please find out what sudden change in the new debug update of magisk caused this to fix yono app, and then pls inculcate those same changes in stable channel too.
Currently I did the same things for fixing the Yono app crash which earlier didn't work, only difference is I updated to the debug version mentioned above.

I want (I request) these new root detection bypass changes in this new debug magisk version mentioned above to be universal and included in the magisk main channel.

Thanks
Love from India

**Comment by DanGLES3** [comment]
Whatever changes they may be they'll eventually arrive to the stable channel provided they don't cause any bugs (as the whole point of the debug/canary builds is testing stuff prior to a stable release), so it's not something that needs to be requested

**Comment by Navneet-Kumar-Singh** [comment]
Edit: New update on how the above report changed to a real issue : As I explained earlier after clean install of above debug version magisk , yono starts to work, but there is a catch I witnessed recently. Yono app will only if I installed yono 1st , and then clean installed the above debug version. As soon after this if I uninstall and reinstall yono app ( or update yono) , it will then not work(will again start to crash).
After Yono is not working now , Yono will again only work if again clean installed the Magisk ( that is full uninstall of Magisk, which I did from inside magisk app not custom recovery , then install the above debug magisk version again, which I installed from custom recovery). 
Final Conclusion: Anytime Yono is not working , it requires full clean reinstall of above magisk debug version again. So on every Yono app update I now have to got though the hassle of clean installing Magisk debug repetitively and then  set up both my modules and deny list again and again repetitively. This is the issue currently.
 So, is there any fix for this where magisk refreshes something of itself and then I can use Yono app after every update without clean installing and setting up magisk above debug version repetitively to skip all the set up hassle?

Status of this feedback report has now been change to CRITICAL ISSUE on my part.

Thank you
Love from India

**Comment by Navneet-Kumar-Singh** [comment]
Yeah , thanks for clearing , I now get the idea of why having 3 channels.
Excellent

**Comment by osm0sis** [comment]
Sounds like you need to be using Shamiko or something to hide stuff better. Not Magisk's problem.

**Comment by Navneet-Kumar-Singh** [comment]
> Sounds like you need to be using Shamiko or something to hide stuff better. Not Magisk's problem.

But even with Shamiko , only debug version of magisk works which means only factor is magisk version so I believe it's Magisk issue.

**Comment by osm0sis** [comment]
Magisk isn't concerned with hiding itself anymore.

https://github.com/topjohnwu/Magisk/issues/1152

**Comment by Navneet-Kumar-Singh** [comment]
> Magisk isn't overly concerned with hiding itself anymore.
> 
> #1152

Thank you for your honourable work 🙏
