### ISSUE TITLE
DenyList on Multiuser mode

### ISSUE THREAD

**Issue by noguxi** [topjohnwu/Magisk#7232]
Device: Mi A2
Android version: 13
Magisk version name: ee34f775
Magisk version code: 26105

There is no way to configure DenyList for non owner users apps when Multiuser mode is set to "Only  owner has root access". The magisk manager will only display owner apps at the DenyList, apps at other users will detect magisk. How about if with Multiuser mode set to "Only  owner has root access", all apps from non owner be at DenyList by default.

**Comment by vvb2060** [comment]
expected behavior

**Comment by infinity0** [comment]
Why is this expected behaviour? Even if the denylist is not enforced, certain other modules such as Shamiko look at the list to hide root detection, so it's a useful feature.

**Comment by infinity0** [comment]
Even though Magisk is not "enabled" for other users, apps on those users can still detect Magisk on user 0, until I use Shamiko. I would prefer not to have to install them on user 0 just to make this possible, since I only use them on the other users.
