### ISSUE TITLE
Write img fail! I need to root spd unisoc t610 cpu phone. Help me.

### ISSUE THREAD

**Issue by mdrakibur179** [topjohnwu/Magisk#7236]
I have UNISOC T610 CPU based android 11. I tried to flash patched-boot.img using command "fastboot flash boot patched-boot.img" but it says "write image failed". Then I tried spd research tool to flash that patched-boot.img file. This time my phone stucked into bootloop. Now I have flashed stock rom, my phone is okay. And has bootloader unlocked. How can I root it? Please give me a solution.

![Screenshot (1)](https://github.com/topjohnwu/Magisk/assets/115276185/c360d078-35f6-466e-a023-8bd1f9a229c2)

Device: Symphony Z33
Android version: 11
Magisk version name: 26.1
Magisk version code:  26105

**Comment by mdrakibur179** [comment]
Please I need your attention. Help me.

**Comment by vvb2060** [comment]
not magisk issue, we can't help you

**Comment by Praveenganisetti** [comment]
Hay are you ok, u find any solution
