### ISSUE TITLE
Stuck on activation after flashing Magisk patched AP on Samsung Galaxy S21 Ultra with China mainland firmware

### ISSUE THREAD

**Issue by mio-19** [topjohnwu/Magisk#7242]
reopen https://github.com/topjohnwu/Magisk/issues/7241

Only Chinese firmware has this problem. I have tried Hong Kong version and activated the phone successfully

Device: Samsung Galaxy S21 Ultra Snapdragon SM-G9980
Android version: 12
Magisk version name: v26.1
Magisk version code: 26105

1. Download latest CHC firmware using frija
2. Flash BL AP CP CSC with odin
3. Activated the phone. Installed Magisk debug. Patched AP. Transfered with `adb push` / `adb pull`. Checked sha512sum to ensure no corruption
4. Flash BL Patched AP CP CSC
5. Got `[2002] -45` Error code when doing activation

![image](https://github.com/topjohnwu/Magisk/assets/57285379/2c3702ef-5d64-4caa-8093-92245be6ca1c)
![image](https://github.com/topjohnwu/Magisk/assets/57285379/48b6b992-b24f-4609-b2af-29cba44e9a93)

**Comment by mio-19** [comment]
> @mio-19 flash the boot.img from the stock rom

Sorry?

**Comment by Star-Seven** [comment]
Disable \system\app\ActivationDevice_V2（If there is a tWRP, you can directly delete this app. If not, you need to enter the browser through the blind keyboard on the activation interface to download the pre prepared module and disable it）

**Comment by BlackMesa123** [comment]
@mio-19 anyway you can share some kernel/system logs to see what's going on under the hood?

**Comment by gopise** [comment]
same issue here. happened on Samsung galaxy s22 android 13.
Activation stage during initial setup will fail with 2002-45. Unable to enter the system. Log attached. It seems failed at attestation.

[activation.txt](https://github.com/topjohnwu/Magisk/files/12576996/activation.txt)

**Comment by BlackMesa123** [comment]
> same issue here. happened on Samsung galaxy s22 android 13. Activation stage during initial setup will fail with 2002-45. Unable to enter the system. Log attached. It seems failed at attestation.
> 
> [activation.txt](https://github.com/topjohnwu/Magisk/files/12576996/activation.txt)

Can you get a more complete log? I see the activation is trying to generate a SAK but it's failing, so taking a look at the keystore logs would be great to see why it's failing in the TEE side.

**Comment by osm0sis** [comment]
So is this seeming like a "not our issue" sort of thing at this point?

**Comment by BlackMesa123** [comment]
> So is this seeming like a "not our issue" sort of thing at this point?

Yeah this is not directly caused by Magisk, as installing any custom kernel will change the System Status in TEE to "Custom":
```
01-01 17:18:40.776   679   679 D keymaster_swd: keymaster_swd [ERR] (swd_key_attest:1348) SAK cannot be used for the compromised device
01-01 17:18:40.776   679   679 D keymaster_swd: keymaster_swd [WRN] (swd_run_cb:254) swd_key_attest() returns -45
01-01 17:18:40.777   679   679 W keymaster_tee: [WRN]Cmd 14, err -45
01-01 17:18:40.777   679   679 W keymaster_tee: [WRN]nwd_attest_key  ret -45
01-01 17:18:40.777   676   676 E keystore2/skeymint: !@ getCertificate : errorCode : -45
01-01 17:18:40.777   676   676 E keystore2/skeymint: !@ attestKey : errorCode : -45
```
SAK is used nowadays on most Samsung apps to verify the device integrity, it isn't hard to bypass as my KnoxPatch module does the job, but again nothing directly caused by Magisk

**Comment by Star-Seven** [comment]
> > Disable \system\app\ActivationDevice_V2（If there is a tWRP, you can directly delete this app. If not, you need to enter the browser through the blind keyboard on the activation interface to download the pre prepared module and disable it）
> 
> Care to explain how the blind keyboard method works? I mean even if i have downloaded such a module to disable ActivationDevice_V2, i can't install it through the magisk app cause i can't enter the system, i can't even finish magisk installation as i need to launch magisk app to let it finish additional setup and reboot the phone.

Based on this https://github.com/fei-ke/Magisk

**Comment by tcc0lin** [comment]
> > > Disable \system\app\ActivationDevice_V2（If there is a tWRP, you can directly delete this app. If not, you need to enter the browser through the blind keyboard on the activation interface to download the pre prepared module and disable it）
> > 
> > 
> > Care to explain how the blind keyboard method works? I mean even if i have downloaded such a module to disable ActivationDevice_V2, i can't install it through the magisk app cause i can't enter the system, i can't even finish magisk installation as i need to launch magisk app to let it finish additional setup and reboot the phone.
> 
> Based on this https://github.com/fei-ke/Magisk

666
