### ISSUE TITLE
su to non-root user loses internet connection

### ISSUE THREAD

**Issue by kxxt** [topjohnwu/Magisk#7249]
Hi, I found an issue regarding internet connection when using the MagiskSU binary to switch to a non-root user.

Steps to reproduce:

1. Connect phone to computer (adb)
2. Run `adb shell` (Non-rooted shell, the user is `shell`, UID=2000)
3. Run `ping 8.8.8.8`, it works fine.
4. Run `su` to switch to root user.
5. Run `ping 8.8.8.8`, it also works fine.
6. Run `su shell` to switch a non-root user (Other non-root users(e.g. u0_a189, etc) can also reproduce this issue). 
7. Run `ping 8.8.8.8`, it doesn't work anymore, complaining `socket: Permission denied`

This could also be reproduced in a terminal emulator app by
1. Run `su shell`
2. Run `ping 127.0.0.1` results in `socket: Permission denied`

With an AOSP emulator(product sdk_phone_x86_64-userdebug), the stock su binary doesn't have these bugs. I tried to reproduce this bug with the emulator, but I haven't figured out how to install Magisk for it.

**Update:** This bug still occurs after setting selinux to permissive by `setenforce 0`

Device: xiaomi-lmi
Android version: 13 (LineageOS 20)
Magisk version name:  ee34f775
Magisk version code: 26105

**Comment by yujincheng08** [comment]
u need to add group 3003(inet) for internet access.
