### ISSUE TITLE
Bootloop after Modification boot.img/recovery.img/AP.tar.md5

### ISSUE THREAD

**Issue by Systemx23x** [topjohnwu/Magisk#7256]
Device: SM-A125F
Android version: 12
Magisk version name: Canary
Magisk version code: 26105

Hi,
Iam on Firmware A125FXXS3CWF3 Binary 3, and every Modification on boot.img/recovery.img ends in Bootloop equal witch Method i use!!!
On Firmware A125FXXS2CVK2 Binary 2 all works Fine!!!!
The only working Method is to repack super.img with GSI ROM, it shows at Flash a error "Fused 3 > Binary 0 [super]"
but Flash goes On and GSI works Fine!!!

So now i ASK Ya to Help Please, why can i Modify Super.img with Flash Errors, but boot.img/recovery.img ends in Bootloop!!!!
The start after Flash Patched boot.img/recovery.img is not Normal, the Button Combo Vol+ + Power to enter Recovery Mode is not working, only VOL+ & VOL- & Power to start in Download Mode works!!!! I have Test all availible Modifications AP.tar.md5/Boot.img/Recovery.img different Magisk Version Official/Canary/Beta and older Releases all the same Results No Button Combo & Bootloop & only Download Mode!!!! As i Update the Device From CVK2 to CWF3 the OTA Update Info shows "add new Device Security & Performance"
when i Patch AP.tar.md5 it shows Warning short Warranty Flag vbmeta but boot.img/recovery.img brings no Notification!!!! when i Flash the Patched vbmeta.img the Warranty Flag is showen with Unlocked Bootloader Flag, and when i use a empty vbmeta no Warranty Flag is showen and Unlocked Bootloader Flag is not shown too!!! But all ends in the same way i have descripe!!!!

Its not the First Device with this Problem the SM-T295 on Latest Firmware have it too, and iam sure there are many more Devices they cant ROOT!!!

Iam Know in Magisk all works Fine so i read in Reports but there must be a Solution to Fix it!!!

**Comment by osm0sis** [comment]
Try 26203?

**Comment by Systemx23x** [comment]
Thx 4 the Info, I have try it but ends i have discripe in Bootloop

**Comment by TeisybeLT** [comment]
I can reproduce this as well. My reproduction steps:

1. Clean flash firmware
2. Follow magisk install guide (Patch AP thing)
3. Flash the patched AP
4. Bootloop :(

Also tried flashing BL, Patched AP, CP and CSC (Home and regular), same results.

**Comment by AresMZ** [comment]
Hello,
I have the same problem, I have a SAMSUNG A12 SM-125F (A125FXXS3CWF3) cell phone, and it stays in a loop. Is there any way to install root?

**Comment by TeisybeLT** [comment]
@AresMZ or @Systemx23x Could you guys please pull out boot logs for the Debug build of Magisk? I would be interested in taking a look, but I currently can't mess with my A12.

**Comment by Systemx23x** [comment]
I have a guess as to why the last firmware update made the device unrootable. I read that the IMEI bug appears when rooting with Magisk. According to reports, there was probably an ISSUE thread on Magisk that describes this, but it remained unanswered and was then deleted!!! So I am of the opinion that rooting has been prevented because of this

**Comment by Systemx23x** [comment]
> @AresMZ or @Systemx23x Could you guys please pull out boot logs for the Debug build of Magisk? I would be interested in taking a look, but I currently can't mess with my A12.

How can i read Logs when device not boot and start recovery and only Download mode or BROM mode?

**Comment by emmet4u** [comment]
Greeting guys. Any good news on binary 3 on SM-A125F. Can't wait to get it rooted well to avoid boot loops

**Comment by BlackMesa123** [comment]
> How can i read Logs when device not boot and start recovery and only Download mode or BROM mode?

How can devs figure out what's wrong without any debug logs then?

**Comment by TeisybeLT** [comment]
1. Download cannary build (the one that has debug options enabled)
2. Get boot logcat: `adb -d logcat` on PC and then boot
3. Since you have BROM, you can read permanent storage. You can try looking for last_kmesg

**Comment by Systemx23x** [comment]
> > 1. Download cannary build (the one that has debug options enabled)
> > 2. Get boot logcat: `adb -d logcat` on PC and then boot
> > 3. Since you have BROM, you can read permanent storage. You can try looking for last_kmesg
> 
> I don’t think the Galaxy A12 has fastboot or brom it just has odin i guess ?

1# You can try via Testpoint or via AndroidMetaUtility106 the BROM Mode
2# Start Recovery Mode and choose Restart Bootloader Mode than it starts in Fastboot Mode, but thats not helpfully wile the fastboot mode not have the Full Functions to use, the Device are not made with fastboot Mode full Support!! Also fastboot Mode is availible but its useless to Programm the Device!!!

**Comment by osm0sis** [comment]
It's been weeks so no logs.
