### ISSUE TITLE
Magisk Manager is trying to update Magisk from 17.3 to 17.3

### ISSUE THREAD

**Issue by equeim** [topjohnwu/Magisk#726]
I installed Magisk 17.3 (downloaded from Github releases page), rebooted and installed latest Magisk Manager. I noticed that Magisk Manager was displaying that the latest Magisk version is 17.1, so I changed update channel to beta. Now Magisk Manager says that I need to update Magisk to version 17.3 (even though it correctly displays that installed and latest versions are both 17.3).

**Comment by topjohnwu** [comment]
Why don't you just update it and see what will happen?
You don't need to open an issue for this question.

**Comment by equeim** [comment]
Well, I opened the issue because this looked like a bug in Magisk Manager to me.

**Comment by neekless** [comment]
> Well, I opened the issue because this looked like a bug in Magisk Manager to me.

If you looked at [this page](https://github.com/topjohnwu/magisk_files/commits/master) you'd know that there's a newer version of 17.3. Just because it's the same version number doesn't mean it's a bug.
