### ISSUE TITLE
App crashed when patching AP.tar

### ISSUE THREAD

**Issue by ryantsui1109** [topjohnwu/Magisk#7262]
Device: Samsung SM-X200
Android version: 13
Magisk version name: 26.2
Magisk version code: 26201

Hi, I was trying to root Samsung Galaxy Tab A 2022 (SM-X200), but magisk app crashes when logs show "--Copying: AGCP_DSP.bin" while patching AP.tar

**Comment by canyie** [comment]
logcat? and the file you are patching?

**Comment by LHC12580** [comment]
magisk更新到26.2最新版时候，抖音打开都会闪退，点赞，搜索栏，就闪退出来。机型联发科![Screenshot_2023-08-30-11-15-05-341_com.ss.android.ugc.aweme.jpg](https://github.com/topjohnwu/Magisk/assets/133021043/d66f7452-f4d0-493a-a7d2-d25ee605d36a)

**Comment by xuuhaoo** [comment]
<img width="1073" alt="image" src="https://github.com/topjohnwu/Magisk/assets/10423664/d3b7e418-2526-4543-910f-caaab5337fd6">
![image](https://github.com/topjohnwu/Magisk/assets/10423664/c51aa21f-a1d6-4997-b3e2-ee7b9099fbc1)

Crash when path the ap file
