### ISSUE TITLE
All 32-bit arm static executables segmentation fault after commit 41226c1

### ISSUE THREAD

**Issue by DerivativeOfLog7** [topjohnwu/Magisk#7264]
Device: Galaxy Tab 4 10.1" LTE (matisselte) (SM-T535)
Android version: 11 (LineageOS 18.1)
Magisk version name: e47e869f
Magisk version code: 26201

Magisk 26.1 can patch the boot.img just fine
<img src="https://github.com/topjohnwu/Magisk/assets/100133857/910e7bdb-4b81-4413-9d2a-64a6d412b399" width="150">
<img src="https://github.com/topjohnwu/Magisk/assets/100133857/f09be046-e61f-4885-92c6-0e4f08aee134" width="150">
<img src="https://github.com/topjohnwu/Magisk/assets/100133857/7ed6337a-8925-483e-8941-92fd5310fd48" width="150">

However, later versions behave weirdly
First of all, it detects the device as having no ramdisk, and asks about recovery mode and dm-verify
<img src="https://github.com/topjohnwu/Magisk/assets/100133857/8e006037-4440-43bb-a839-c3f9b0736f18)" width="150">
<img src="https://github.com/topjohnwu/Magisk/assets/100133857/9eb63258-6815-4390-905d-1e84f681d572" width="150">

After that, it just fails to patch
<img src="https://github.com/topjohnwu/Magisk/assets/100133857/3610c81a-38c2-4f30-a9af-a00d10fe7462" width="150">

If I install the newer manager right after flashing the 26.1 boot.img (before accepting the "requires additional setup" message), it won't detect Magisk is installed
If I install the newer manager after accepting that, everything breaks. The app icon disappears, and if I open it it says it needs to upgrade to full magisk manager. Android asks me to install the app, it works for a few seconds (still showing Magisk not installed), but then it crashes, disappears from the app drawer, and finally reappears having no icon, and you can repeat the cycle

This is happening on a fresh ROM install

boot.img: [boot.zip](https://github.com/topjohnwu/Magisk/files/12458244/boot.zip)

Dev Edit: The regression starts with commit https://github.com/topjohnwu/Magisk/commit/41226c12b8de48eaa0cf77983ff416fd42dfb8f0

**Comment by BlackMesa123** [comment]
Might be caused by https://github.com/topjohnwu/Magisk/commit/d12d9e82f1b688215e3d33b356b24296623e64bb

**Comment by yujincheng08** [comment]
You should provide log.

**Comment by DerivativeOfLog7** [comment]
> You should provide log.

Which one?
--
@YashvirGaming ??

**Comment by canyie** [comment]
try this build? https://github.com/topjohnwu/Magisk/actions/runs/6010307358

**Comment by DerivativeOfLog7** [comment]
> try this build? https://github.com/topjohnwu/Magisk/actions/runs/6010307358

Same problem as 26.2/debug

![Screenshot_20230829-130735_Magisk](https://github.com/topjohnwu/Magisk/assets/100133857/0cb3366c-4806-4c90-a56e-233cab99bf05)

**Comment by ynakao** [comment]
I have the same issue. When I updated Magisk v26.2, system info on the Home tab in the app became weird. In Magisk panel, `Installed` indicates `N/A` but `Zygisk` is `YES`. And while `Ramdisk` was `YES` when I installed Magisk before, it became `No` this time. In App panel, Installed version is v26.2, but Latest is v26.1.

![IMG_20230829_214649](https://github.com/topjohnwu/Magisk/assets/6405335/f74e770d-c1e8-4541-8e84-611e3516a8c3)

And I tried Magisk installation, install options showed up three choices, while the `Recovery Mode` option wasn't there in my first Magisk installation.

![IMG_20230829_214614](https://github.com/topjohnwu/Magisk/assets/6405335/c6bee080-0cd8-449b-9cba-d69698b17593)

I chose `Patch vbmata in boot image` same as first installation, and `Direct Install` in Method panel, but Magisk Installation failed, saying `! Unable to detect target image ! Installation failed`.

I found the person who encountered the same issue in the XDA Magisk General Support / Discussion thread.
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-88936271
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-88936297
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-88936861

I collected logcat during the process above.

```shell
% adb logcat|grep magisk
08-29 19:55:14.666   815  1006 I ActivityManager: Killing 15203:com.topjohnwu.magisk/u0a152 (adj 906): empty #17
08-29 21:08:01.007   815  1662 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.ui.MainActivity (has extras)} from uid 10032 on display 0
08-29 21:08:01.115   815  1051 I ActivityManager: Start proc 30781:com.topjohnwu.magisk/u0a152 for activity com.topjohnwu.magisk/.ui.MainActivity
08-29 21:08:02.487 30781 30807 D GmsProviderInstaller: Initializing provider for com.topjohnwu.magisk
08-29 21:09:16.978   815 31256 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.ui.MainActivity (has extras)} from uid 10032 on display 0
08-29 21:22:29.504   815 31251 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.ui.MainActivity (has extras)} from uid 10032 on display 0
08-29 21:49:54.712   815  1649 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.ui.MainActivity (has extras)} from uid 10032 on display 0
08-29 21:49:59.662   815 31256 I ActivityManager: Killing 30781:com.topjohnwu.magisk/u0a152 (adj 900): remove task
08-29 21:49:59.703   815  1051 I WindowManager: WIN DEATH: Window{ffe48c1 u0 com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity}
08-29 21:50:13.610   815  1051 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.ui.MainActivity (has extras)} from uid 10032 on display 0
08-29 21:50:13.673   815 31255 I ActivityManager: Start proc 3256:com.topjohnwu.magisk/u0a152 for activity com.topjohnwu.magisk/.ui.MainActivity
08-29 21:50:14.888  3256  3283 D GmsProviderInstaller: Initializing provider for com.topjohnwu.magisk
08-29 21:50:15.968   815   841 I ActivityManager: Displayed com.topjohnwu.magisk/.ui.MainActivity: +2s337ms
```

Device: Nexus 5
Android version: 7.1.2 (LineageOS with microG)

**Comment by DerivativeOfLog7** [comment]
> When I updated Magisk v26.2, system info on the Home tab in the app became weird. In Magisk panel, Installed indicates N/A

Excluding the app crashing and uninstalling itself, I also get this behaviour if I install manager 26.2 on the 26.1 patched environment

**Comment by osm0sis** [comment]
You could try the Canary builds from here and narrow down when it broke: https://github.com/topjohnwu/magisk-files/commits/canary

**Comment by newbit1** [comment]
> You could try the Canary builds from here and narrow down when it broke: https://github.com/topjohnwu/magisk-files/commits/canary

Thanks for the tip, I've a similar issue...
It works with Magisk canary [47d2d4e3 26102.log](https://github.com/topjohnwu/Magisk/files/12468240/magisk_install_log_26102.log)
And breaks with Magisk canary [a8c4a33e 26103.log](https://github.com/topjohnwu/Magisk/files/12468250/magisk_install_log_26103.log)

**Comment by canyie** [comment]
@newbit1 Please attach install logs from 26201 as well

**Comment by newbit1** [comment]
> Upload the image you failed to patch? And what's your device model?

Here are both, the stock boot.img and the patched one with 26102 [Archive.zip](https://github.com/topjohnwu/Magisk/files/12469647/Archive.zip)

It is an AVD, running Android 7

**Comment by GogoBorg** [comment]
Same issue with two devices. 

first LG G2 Lineage 18. Attaching installlog and boot.img attempting to patch.

With this device, it just fails and I lose root. cannot downgrade app to 26.1. Stuck with no Magisk and no root.
mtp://lge_LG-D801_092c072be529f28d/Internal%20shared%20storage/Download/magisk_install_log_2023-08-29T14.15.06.log

file attempted to patch: 
mtp://lge_LG-D801_092c072be529f28d/Internal%20shared%20storage/lineage-19.1-20230731-UNOFFICIAL-d801/boot.img

**Comment by GogoBorg** [comment]
the second device it failed bigly: lost recovery, lost OS.
This is Moto e5 hannah.
It finishes patching the file in the app, upon reboot recovery  lost and OS lost, too. could not boot recovery without re-flashing recovery via fastboot. Then had to reinstall system.
Could not boot system .

2nd attempt successful with debug app. boot.img first xferred to external SD card.
![Uploading Screenshot_20230829-162153_Trebuchet.png…]()
[after-flash-in-rec-of-patched-boot-&-reboot-successful-magisk_install_log_2023-08-29T16.17.06.log](https://github.com/topjohnwu/Magisk/files/12470318/after-flash-in-rec-of-patched-boot-.-reboot-successful-magisk_install_log_2023-08-29T16.17.06.log)
[after patch w-debug-app-magisk_log_2023-08-29T16.24.07.log](https://github.com/topjohnwu/Magisk/files/12470319/after.patch.w-debug-app-magisk_log_2023-08-29T16.24.07.log)
[Moto e5+ hannah-Lineage18-boot.img.zip](https://github.com/topjohnwu/Magisk/files/12470324/Moto.e5%2B.hannah-Lineage18-boot.img.zip)

**Comment by canyie** [comment]
@DerivativeOfLog7 @GogoBorg @ynakao @PalmDevs Magisk Canary/Debug 26202 is out. Please take a try with that build.

---

@newbit1 Your issue is different and is redirected to #7274

**Comment by DerivativeOfLog7** [comment]
> Magisk Canary/Debug 26202 is out. Please take a try with that build.
Unfortunately it still seems to be broken ("Ramisk: no" and cannot patch)
With unpatched boot.img:
![Screenshot_20230830-115016_Magisk](https://github.com/topjohnwu/Magisk/assets/100133857/f35bf696-1c54-473b-a286-48989e0060fd)
<img src="https://github.com/topjohnwu/Magisk/assets/100133857/910e7bdb-4b81-4413-9d2a-64a6d412b399" width="150">
![Screenshot_20230830-115159_Magisk](https://github.com/topjohnwu/Magisk/assets/100133857/82835a53-41d3-415e-8574-6f18acc2fcf7)
<img src="https://github.com/topjohnwu/Magisk/assets/100133857/910e7bdb-4b81-4413-9d2a-64a6d412b399" width="150">
![Screenshot_20230830-115039_Magisk](https://github.com/topjohnwu/Magisk/assets/100133857/c8072922-f412-451d-978d-c498b457d392)

At least the app doesn't crash anymore if installed when using a 26.1 patched boot.img, but it still doesn't detect the installed Magisk properly (I'm getting the surreal Installed: N/D, Zygisk: yes)
![Screenshot_20230830-115524_Magisk](https://github.com/topjohnwu/Magisk/assets/100133857/6e68f177-5301-45fb-ae07-3187b30eca65)
Furthermore, the "direct install" option appears, but if I try that the app crashes

**Comment by DerivativeOfLog7** [comment]
> Magisk Canary/Debug 26202 is out. Please take a try with that build.

Unfortunately it still seems to be broken ("Ramisk: no" and cannot patch)
With unpatched boot.img:
<img src="https://github.com/topjohnwu/Magisk/assets/100133857/f35bf696-1c54-473b-a286-48989e0060fd" width="150">
<img src="https://github.com/topjohnwu/Magisk/assets/100133857/82835a53-41d3-415e-8574-6f18acc2fcf7" width="150">
<img src="https://github.com/topjohnwu/Magisk/assets/100133857/c8072922-f412-451d-978d-c498b457d392" width="150">

At least the app doesn't crash anymore if installed when using a 26.1 patched boot.img, but it still doesn't detect the installed Magisk properly (I'm getting the surreal Installed: N/D, Zygisk: yes)
<img src="https://github.com/topjohnwu/Magisk/assets/100133857/6e68f177-5301-45fb-ae07-3187b30eca65" width="150">
Furthermore, the "direct install" option appears, but if I try that the app crashes
Logcat opening the new debug build (with 26.1 patched boot) and crashing by trying a direct install: 
[logcat.txt](https://github.com/topjohnwu/Magisk/files/12474547/logcat.txt)

**Comment by PalmDevs** [comment]
> @DerivativeOfLog7 @GogoBorg @ynakao @PalmDevs Magisk Canary/Debug 26202 is out. Please take a try with that build.
> 
> ---
> 
> @newbit1 Your issue is different and is redirected to #7274

Still broken as well for me. Same issue as what the author of the issue is having above.

**Comment by PalmDevs** [comment]
> Magisk Canary/Debug 26202 is out. Please take a try with that build.
Unfortunately it is still not working for me. Almost the exact same as the author of the issue, but it doesn't crash when I do a Direct install, it only fails. (I'll attach screenshot in a second)

**Comment by canyie** [comment]
Do you guys know how to use terminal (like Termux)? Are your devices are 32-bit?

**Comment by PalmDevs** [comment]
> Do you guys know how to use terminal (like Termux)? Are your devices are 32-bit?

I am using a 32-bit device, and I can run Termux just fine. What do I need to run to gather more information?

**Comment by canyie** [comment]
> > Do you guys know how to use terminal (like Termux)? Are your devices are 32-bit?
> 
> I am using a 32-bit device, and I can run Termux just fine. What do I need to run to gather more information?

Ah, nothing, I've successfully reproduced the crash on my side. 
![image](https://github.com/topjohnwu/Magisk/assets/31466456/9d1d3474-ddba-4828-b484-eb95425ab632)

**Comment by DerivativeOfLog7** [comment]
> Do you guys know how to use terminal (like Termux)? Are your devices are 32-bit?
Yes and yes

**Comment by DerivativeOfLog7** [comment]
Even the patching and inability to detect an already installed version are caused by busybox?

**Comment by osm0sis** [comment]
> Even the patching and inability to detect an already installed version are caused by busybox?

Busybox provides the shell.

**Comment by LHC12580** [comment]
magisk更新到26.2最新版时候，抖音打开都会闪退，点赞，搜索栏，就闪退出来。机型联发科![Screenshot_2023-08-30-07-44-18-460_ob.umz.l.jpg](https://github.com/topjohnwu/Magisk/assets/133021043/29f2125d-5cfa-40bd-9573-945ac1815225)

![Screenshot_2023-08-30-11-15-05-341_com.ss.android.ugc.aweme.jpg](https://github.com/topjohnwu/Magisk/assets/133021043/2dd883a9-db85-49ee-9855-5d62d928221c)

**Comment by DerivativeOfLog7** [comment]
> magisk更新到26.2最新版时候，抖音打开都会闪退，点赞，搜索栏，就闪退出来。机型联发科

Unrelated to this issue

**Comment by LHC12580** [comment]
退回magisk 26.1版本，打开抖音功能正常，则magisk26.2闪退



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 30, 2023 21:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [topjohnwu/Magisk] Busybox segmentation fault on 32-bit armdevices after commit 41226c1 (Issue #7264)




  
magisk更新到26.2最新版时候，抖音打开都会闪退，点赞，搜索栏，就闪退出来。机型联发科
  
Unrelated to this issue

**Comment by LHC12580** [comment]
另外告诉您，高通骁龙处理器，抖音功能正常使用，联发科则闪退。

**Comment by GogoBorg** [comment]
Still fails to patch 32bit device: tried debug and canary de00f1d5
- Device platform: armeabi-v7a
- Installing: de00f1d5 (26202)
- Copying image to cache
! Installation failed

**Comment by PalmDevs** [comment]
It works now after the latest canary build (`96e559fb`)! Thanks for fixing this very quickly.
