### ISSUE TITLE
Refactored magiskboot cpio handler causes stack_chk_fail crashes on Android 7 x86 AVD

### ISSUE THREAD

**Issue by canyie** [topjohnwu/Magisk#7274]
Device: x86 AVD
Android version: 7 & 7.1.1
Magisk version name:  6bdc57c
Magisk version code: 26202

Initially reported by @newbit1 in https://github.com/topjohnwu/Magisk/issues/7264#issuecomment-1697969029
The crash can be reproduced with a non-exist cpio.
It seems the crash happens when it is returning from Rust code to C++?
![image](https://github.com/topjohnwu/Magisk/assets/31466456/66c46f5a-8f2b-48cb-bc73-7700ef8a8730)
![image](https://github.com/topjohnwu/Magisk/assets/31466456/af047ced-ff61-4a16-b68f-069ae30a0814)

**Comment by LHC12580** [comment]
magisk更新到26.2最新版时候，抖音打开都会闪退，点赞，搜索栏，就闪退出来。机型联发科![Screenshot_2023-08-30-07-44-18-460_ob.umz.l.jpg](https://github.com/topjohnwu/Magisk/assets/133021043/e62700ec-d6fc-478e-956b-df6bca5e7d52)

![Screenshot_2023-08-30-11-15-05-341_com.ss.android.ugc.aweme.jpg](https://github.com/topjohnwu/Magisk/assets/133021043/fa7a84b1-2ae0-416b-a2a6-c1c0a3e75dcb)

**Comment by LHC12580** [comment]
我是想让开发者看到，我是小白，报意思



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 30, 2023 21:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [topjohnwu/Magisk] Refactored magiskboot cpio handler causesstack_chk_fail crashes on Android 7 x86 AVD (Issue #7274)




 
@LHC12580 能不能不要在每个无关的地方都刷屏你的弱智问题，你这样等于骚扰所有人，只会让你的 github 账号被 block

**Comment by yujincheng08** [comment]
If we dont patch static libraries, it works again. So it's a problem of `libc.a`.

**Comment by Mohamad1112we** [comment]
K
