### ISSUE TITLE
Revvl 6 5G - Metro - After Android 13 Update - Freeze on Boot/Magisk Patch Ignored

### ISSUE THREAD

**Issue by NinjaAdmin42** [topjohnwu/Magisk#7288]
Device: Revvl 6 5G
Android version: 13
Magisk version name: v26.2 (Debug)
Magisk version code: de00f1d5 (26202) (D)

Followed installation instructions to the letter. Magisk 26.1 worked great for the Android 12 variant. After the Android 13 update not so much. Fastbootd flash ends at logo boot screen/soft bricked. MTKClient ends with a normal non-root boot-up. Patch flashing vbmeta_a.img ends at Fastboot/stuck on bootloader. However, root did require vbmeta_a.img patch flashing on Android 12.

[magisk_install_log_2023-09-02T00.09.02.log](https://github.com/topjohnwu/Magisk/files/12503241/magisk_install_log_2023-09-02T00.09.02.log)
[magisk_log_2023-09-02T00.10.58.log](https://github.com/topjohnwu/Magisk/files/12503242/magisk_log_2023-09-02T00.10.58.log)
[boot_a.zip](https://github.com/topjohnwu/Magisk/files/12503247/boot_a.zip)
[magisk_patched-26202_kglea.zip](https://github.com/topjohnwu/Magisk/files/12503248/magisk_patched-26202_kglea.zip)
[vbmeta_a.zip](https://github.com/topjohnwu/Magisk/files/12503270/vbmeta_a.zip)

**Comment by osm0sis** [comment]
Try 26203?

**Comment by NinjaAdmin42** [comment]
96e559fb (2603) (C) met with the same response. Normal flashing results in normal non-root boot-up. Flashing with patching vbmeta_a results in a stuck on the bootloader.

[magisk_patched-26203_UKhhl.zip](https://github.com/topjohnwu/Magisk/files/12504338/magisk_patched-26203_UKhhl.zip)
[magisk_log_2023-09-02T11.17.52.log](https://github.com/topjohnwu/Magisk/files/12504339/magisk_log_2023-09-02T11.17.52.log)
[magisk_install_log_2023-09-02T11.17.42.log](https://github.com/topjohnwu/Magisk/files/12504341/magisk_install_log_2023-09-02T11.17.42.log)

**Comment by NinjaAdmin42** [comment]
I've tried flashing multiple ways. Always using 'adb push/pull' over MTP. Flashed via Bootloader, Fastbootd, FastbootEnhance, and MTKClient in BRom Mode. Each has met with a similar response. Freeze on logo boot screen, boot-up like normal non-rooted, and always reboot to Bootloader on boot-up after patching vbmeta_a.

**Comment by NinjaAdmin42** [comment]
Magisk Debug Log from after Flashing with the result of normal boot-up without root.

[magisk_log_2023-09-02T15.29.26.log](https://github.com/topjohnwu/Magisk/files/12504614/magisk_log_2023-09-02T15.29.26.log)

**Comment by NinjaAdmin42** [comment]
After the Magisk Update to 26.3, the same outcome. I tried Stable, Beta, Canary, and Debug.

Device: Revvl 6 5G
Android version: 13
Magisk version name: v26.301 (D)
Magisk version code: d4e552d0 (26301) (D)

[magisk_patched-26301_n5G4A.zip](https://github.com/topjohnwu/Magisk/files/12518599/magisk_patched-26301_n5G4A.zip)
[magisk_install_log_2023-09-04T22.32.06.log](https://github.com/topjohnwu/Magisk/files/12518600/magisk_install_log_2023-09-04T22.32.06.log)
[magisk_beforeFlash-log_2023-09-04T22.32.18.log](https://github.com/topjohnwu/Magisk/files/12518602/magisk_beforeFlash-log_2023-09-04T22.32.18.log)
[magisk_afterFlash-log_2023-09-04T22.41.06.log](https://github.com/topjohnwu/Magisk/files/12518603/magisk_afterFlash-log_2023-09-04T22.41.06.log)

**Comment by NinjaAdmin42** [comment]
Canary Log after Flash

[magisk_log_2023-09-04T23.05.13.log](https://github.com/topjohnwu/Magisk/files/12518680/magisk_log_2023-09-04T23.05.13.log)

**Comment by NinjaAdmin42** [comment]
I rolled back the firmware to Android 12, and achieved root via Magisk 26.300 (Stable) until a solution for the Android 13 update is found.

I only mention it because something is up with my vbmeta_a.img file. As patch flashing vbmeta_a is completely ignored now, as if it was never patched. Still have to hit power within 5 seconds on boot.

**Comment by kyrenlee** [comment]
need remake boot-patch.img ,reflashing the device.

**Comment by NinjaAdmin42** [comment]
> need remake boot-patch.img ,reflashing the device.

Reflashed stock firmware, Updated to Android 13, Dumped Payload to create BackUp (No Android 13 Firmware is currently available online), Changed boot_a.bin to boot_a.img, Transfered to Device using 'adb push,' Reinstalled Magisk 26.3, Patched boot_a.img to create magisk_patched-boot_a.img, Transfered to PC using 'adb pull,' Flashed via fastbootd, Flashed and Patched vbmeta_a.img, and the device bootloops to bootloader. 

So I reflashed the device from Payload backup, repeated the entire process minus the vbmeta_a.img patch, and the device does not recognize the magisk_patched-boot_a.img as anything other than a normal boot_a.img. No Root recognized. Still the same outcome. 

FYI, I even attempted the process with the current Magisk Delta Canary Version and was met with the same response.

**Comment by NinjaAdmin42** [comment]
I repeated the process again with 0352ea2c (26302) (D), and was met with the same No Root Recognized - magisk_patched-debug.img behaves as normal boot_a.img. 

#
[magisk_log_2023-10-24T20.14.23.log](https://github.com/topjohnwu/Magisk/files/13156038/magisk_log_2023-10-24T20.14.23.log)

**Comment by NinjaAdmin42** [comment]
Solved. I updated to Magisk Canary (aa6c7c15) (26401), ran the Android 13 update, and flashed the patched image directly to secondary partition with reboot after OTA. I have successfully achieved Root on Android 13.
