### ISSUE TITLE
Magisk 26.3, reflashing causes device to crash

### ISSUE THREAD

**Issue by TubaApollo** [topjohnwu/Magisk#7298]
After having problems updating the app from 26.1 -> 26.3 (app disappeared, icon disappeared etc) I tried the debug apk and manually installed it which worked. However, when trying to reflash the magisk patch, the device completely froze during the flashing process, forcing me to shut it down by long pressing the power button. It then rebooted normally, but the magisk app complained that the device needs a reflash. With 26.1 everything seemed to work fine, I am not sure which log to provide, I think I cannot provide the magisk.log since the device crashes during flashing? Also, how should I proceed, is it safest to downgrade the app back to 26.1, reflash and leave it that way for now? I can also try to provide logcat, I am just not sure which logs would be needed in this case.

Device: Volla Phone 22
Android version: 12
Magisk version name: 26.3
Magisk version code: 26301

**Comment by milad19s** [comment]
I have the same problem

**Comment by Vader77Darth** [comment]
I am also having issues with 26.3. I do direct install to update. Everything seems fine until it reboots. After it reboots, I open magisk and it says I am still on 26.1 with this error.
![Screenshot_2023-09-04-22-44-10-565_fjwsw fxjg ggtje](https://github.com/topjohnwu/Magisk/assets/87441738/cdee6c4e-8b18-4751-99bc-0e6584258ef0)

**Comment by osm0sis** [comment]
You just need to hit OK and let it Direct flash again. This is expected behavior after an initial flash from recovery.

**Comment by pndwal** [comment]
> You just need to hit OK and let it Direct flash again. This is expected behavior after an initial flash from recovery.

But seems this is happening after Direct install in-app...

**Comment by Vader77Darth** [comment]
Same. It doesn't matter how many times I click ok and then direct install again. This still keeps happening.

**Comment by osm0sis** [comment]
Sounds like another regression then. Can you walk your way back in the Canary builds and narrow down when the issue started?

https://github.com/topjohnwu/magisk-files/commits/canary

**Comment by osm0sis** [comment]
You also need to upload a last_kmesg/console-ramoops after your device reboot after the crash.

**Comment by Vader77Darth** [comment]
I think it might actually be mediatek making boot images read only after boot.

**Comment by osm0sis** [comment]
> I think it might actually be mediatek making boot images read only after boot.

Nope, because the user said it worked with Magisk 26.1.

**Comment by Vader77Darth** [comment]
I meant in my case. I have only ever installed with fastboot. failed when using direct install

**Comment by osm0sis** [comment]
> I meant in my case. I have only ever installed with fastboot. failed when using direct install

Then your case is different and you should open your own issue.

**Comment by Vader77Darth** [comment]
my issue has been resolved. thanks for your help.

**Comment by nieldk** [comment]
FTR. I solved this by 
1) installing magisk manager, then
2) installere magisk (26.1)

**Comment by TubaApollo** [comment]
I installed 26.1 fine after multiple OTAs, is there a difference between flashing directly and flashing OTAs? My device is also using mediatek, so it could be related to this.

**Comment by Vader77Darth** [comment]
Tuba, from what I have found, mediatek locks boot image after boot so magisk manager cannot install magisk updates. You must use fastboot to flash new patched boot image if I am correct.

**Comment by TubaApollo** [comment]
But why did updating with OTAs worked fine the whole time then, does the flashing doesnt work the same way there?

**Comment by osm0sis** [comment]
Because you have different issues.

**Comment by Vader77Darth** [comment]
How am I derailing the issue?

**Comment by osm0sis** [comment]
> How am I derailing the issue?

Because I told you and Tuba said 26.1 worked, whereas with your device no version works.

**Comment by Vader77Darth** [comment]
I was not derailing the issue: just trying to help. Reminder: 26.1 does work on my device.

**Comment by TubaApollo** [comment]
> You also need to upload a last_kmesg/console-ramoops after your device reboot after the crash.

It may also be related to mediatek, I want to clarify, I have not done direct flashing before, only multiple OTA installation flashing which worked fine, no idea if it makes a difference, sorry for the confusion. I tried to reinstall magisk app and downgrade it 26.1, it just doesnt want to work, the app has no icon and refused to start, same issues when upgrading to 26.3, but now i even have it with 26.1 which used to work fine before. So i could only check existing log files now, since there is no way for me to reflash it over the app 😂

**Comment by TubaApollo** [comment]
Ok the app worked again (no idea why) and I tried reflashing 26.1 and it crashed again, same behaviour as 26.3, so it is not version related, I just thought so. So, as Vader said, it could be related to mediatek locking the boot image after booting. Now I am thinking, if I wait for a new OTA that the manufacturer ships and flash 26.3 on that OTA, will it work? I mean so far flashing after OTA has always worked fine.

**Comment by Michael-R00T** [comment]
Hello,
I'm facing bootloop when i'm trying to update from 26.1 to 26.3
Poco F1
Android 10 - miui12
ramdisk was N0, before i started flashing. But It's yes now....

Also facing bootloop with the latest versions of Magisk-Alpha.

I tried everything:

Install directly through the magisk app -->bootloop (with and wihtout recovery checked)
Flash 26.3 via twrp --> bootloop
Extracted boot.img from rom, then patched with 26.3, then flashed through twrp --> bootloop
Restored un-rooted boot.img through twrp, then flashed 26.3 --> bootloop
Always, i was recovering phone with boot.img (26.1 patched) backup (twrp). Also restored recovery,img...

I've got stock kernel and i don't know how to take log from booting.

Any help?

**Comment by Xyphoseos** [comment]
Hi, same issue with A51 5G

**Comment by Sandeepkothari2525** [comment]
Same issue with k20 pro

**Comment by bladyle** [comment]
Same issue with k20 pro +1

**Comment by BenChich** [comment]
Hi,
I just installed magisk 26.3 on my Samsung Galaxy Tab A7 Lite. Everything was going fine. 
I did the command in termux to removes all the bootloader unlock warnings on boot, like it is said in this post [https://forum.xda-developers.com/t/tutorial-how-to-unlock-root-tab-a7-lite-t220-t225-install-lsposed-magisk-mods.4406933/](url), after I reboot via the "reboot" commande in Termux and then my tab goes in bootloop. I tried to wipe/factoryreset via recovery but it doesn't change anything... It won't boot anymore...
Any idea of what I should do ? Roll back to an old version ?
I have android 13.

**Comment by daftndaze** [comment]
Same issue with k20 pro

**Comment by SXUsr** [comment]
I'm getting the same issue too. Hope this is the right log.

dmesg__2023-09-22-18-33-36.log](https://github.com/topjohnwu/Magisk/files/12703255/dmesg__2023-09-22-18-33-36.log)

**Comment by canyie** [comment]
@SXUsr The log you provided is from recovery, which is not what we need. Connect your device to PC, use `adb shell su -c dmesg > dmesg.log`, reproduce the issue, then upload dmesg.log.

**Comment by SXUsr** [comment]
> @SXUsr The log you provided is from recovery, which is not what we need. Connect your device to PC, use `adb shell su -c dmesg > dmesg.log`, reproduce the issue, then upload dmesg.log.

Thanks. [dmesg.log](https://github.com/topjohnwu/Magisk/files/12708297/dmesg.log)

**Comment by kyrenlee** [comment]
need retry to make new boot-patch.img to reflashing the device

**Comment by realhuseyn** [comment]
@TubaApollo I have faced this issue today. My device is K20 Pro. My device was in bootloop. But I reflashed Magisk v26.3 in TWRP, after that, it works normally

**Comment by PowerUser64** [comment]
I had a similar problem to what is described above, with the app icon disappearing among other things (see #7491). Installing the debug release [`aa6c7c15`](https://github.com/topjohnwu/magisk-files/commit/b2de9648795c4eb7f2860a6e3c17487b3a9047d5) from [topjohnwu/magisk-files/debug.json](https://github.com/topjohnwu/magisk-files/blob/master/debug.json) solved the problems I was having. I have no clue why this fixed everything because the debug and stable releases are at the same commit right now, but if it works, it works. Hopefully some folks here will find this helpful.

**Comment by vvb2060** [comment]
[App] Prevent OOM when patching AP tarfiles

**Comment by wonkxin** [comment]
[kmsg.log](https://github.com/topjohnwu/Magisk/files/14157508/kmsg.log)
Magisk 26.1 is last version working on my Samsung Galaxy M51 SM-M515F
