### ISSUE TITLE
Magisk v11.1 do not pass safetynet

### ISSUE THREAD

**Issue by skeleton1911** [topjohnwu/Magisk#73]
Hi
i have an Elephone P8000 and Magisk dont work like it should.
In Magsik Manager its all fine.  Makisk v11.1 is installed and the SU for root is working
only the safetynet is not working. i get a CTS Error.
(also disabled and enabled magisk hide again with no result)
i hope you can help  :)
Thanks in advance

Boot Image (stock)
https://1drv.ms/u/s!Am93l3qEx-D_7xgTOM1EZa4zwlg-

**Comment by Didgeridoohan** [comment]
Some tips:
https://forum.xda-developers.com/showpost.php?p=70426733&postcount=7120

**Comment by Artrix** [comment]
I have same problem, Magisk 11.1 do not pass safetynet, only work v9
