### ISSUE TITLE
Amonet device bootloop after v26.3 install / update

### ISSUE THREAD

**Issue by tsynik** [topjohnwu/Magisk#7308]
Device: Fire TV 4K
Android version: Android 7.1.2
Magisk version name: Magisk v26.3
Magisk version code: 26301

There was added amonet root support in Magisk for rooted Fire TV devices: https://github.com/topjohnwu/Magisk/issues/5833 https://github.com/topjohnwu/Magisk/pull/6739

With v26.3 release it again have boot loop after direct install/update from Magisk Manager itself. Was installed and working fine Magisk/Manager v26.1, Manager was updated to v26.3 and installed v26.3 with direct install/update from it. Can provide more info by request.

Looks like its new issue: flashed fresh Fire TV 4K ROM, and installed debug canary Magisk 26301 zip from TWRP recovery after - same boot loop and only 1st fire tv logo and endless reboot soon. All previous Magisks (v24, v25, v26.0 v26.1) were flashed fine from TWRP and worked on this device.

Bad thing is I even can't stick now with working v26.1 - after clean reflash fw and installing v26.1 from twrp in OS Magisk Manager say "Additional install step required", and flashed v26.3 after, which breaks device again. And I need to open it, short pin, reflash fw and Magisk again from scratch. UPD: removed updated Magisk Manager v26.3 from Android and flashed OK v26.1 from previous apk v26.1

**Comment by osm0sis** [comment]
Can you narrow down which Canary build the regression starts occurring? https://github.com/topjohnwu/magisk-files/commits/canary

**Comment by tsynik** [comment]
> Can you narrow down which Canary build the regression starts occurring? https://github.com/topjohnwu/magisk-files/commits/canary

[e2545e57](https://github.com/topjohnwu/magisk-files/commit/76a6e7a53b6509dc6c2ae2974a2ea2a8b07d3a12)
[d0c93842](https://github.com/topjohnwu/magisk-files/commit/99853810619807f8b61c324fe70636a47e447419)
[47d2d4e3](https://github.com/topjohnwu/magisk-files/commit/48dc969d44f8493ac2421fa50c184c6792381abd)
flashed OK and working OS
[a8c4a33e](https://github.com/topjohnwu/magisk-files/commit/e18c68e390bdc83968c26a2b37d9b2563e665245)
reports Unsupported / unknown image format in TWRP after Unpacking boot image on install
[e47e869f](https://github.com/topjohnwu/magisk-files/commit/ff8fe1b1eb7817dc2444ddef9acd3e4b9f77cf20) and v26.2 release gave me error in TWRP after select (TWRP can't unpack such zip?)

**Comment by osm0sis** [comment]
Nice work! Okay, next step, check the commits between the two "Release new canary build" commits for 26104 and 26105 and try the GitHub Actions CI builds for each to find which caused the regression.

**Comment by tsynik** [comment]
> Nice work! Okay, next step, check the commits between the two "Release new canary build" commits for 26104 and 26105 and try the GitHub Actions CI builds for each to find which caused the regression.

There are too many commits, and I need to reopen my device and do short-pinning NAND and full reflash after. So it's like "Mission impossible". And I don't know where to find CI builds too.

**Comment by osm0sis** [comment]
You view in desktop mode, tap the checkmark on the commit, Details, Summary then get the artifact zip and extract the debug APK from it.

I'm curious about this one: https://github.com/topjohnwu/Magisk/actions/runs/5584023672

And then this one:
https://github.com/topjohnwu/Magisk/actions/runs/5617639740

**Comment by yujincheng08** [comment]
@tsynik Use a binary search.

**Comment by tsynik** [comment]
> 'm curious about this one: https://github.com/topjohnwu/Magisk/actions/runs/5584023672
> And then this one: https://github.com/topjohnwu/Magisk/actions/runs/5617639740

both flashed and working OK
```
mantis:/sdcard # twrp install app-debug.apk                                                                                                                                                              
Installing zip file '/data/media/0/app-debug.apk'
Installing zip file '/data/media/0/app-debug.apk'
Unmounting System...
[amonet] Load microloader from recovery... 
[amonet] Remove boot patch...
[amonet] OK
**********************************
 Magisk 39383229(26104) Installer 
**********************************
- Mounting /system
- No vbmeta partition, patch vbmeta in boot image
- Target image: /dev/block/mmcblk0p4
- Device platform: armeabi-v7a
- Constructing environment
- Adding addon.d survival script
- Unpacking boot image
- Checking ramdisk status
- Magisk patched boot image detected
- Patching ramdisk
- Pre-init storage partition: userdata
- Repacking boot image
- Flashing new boot image
- Unmounting partitions
- Done
[amonet] Install boot patch... 
[amonet] OK
[amonet] Install recovery patch... 
[amonet] ALREADY_INSTALLED
Done processing script file
```

**Comment by osm0sis** [comment]
Interesting, must be something less obvious then.. Like one of the magiskpolicy changes.

**Comment by tsynik** [comment]
> Interesting, must be something less obvious then.. Like one of the magiskpolicy changes.

This commit failed:
```
mantis:/sdcard # twrp install app-debug.apk                                                                                                                                                              
Installing zip file '/data/media/0/app-debug.apk'
Installing zip file '/data/media/0/app-debug.apk'
Unmounting System...
[amonet] Load microloader from recovery... 
[amonet] Remove boot patch...
[amonet] OK
**********************************
 Magisk 17ba5cba(26104) Installer 
**********************************
- Mounting /system
- No vbmeta partition, patch vbmeta in boot image
- Target image: /dev/block/mmcblk0p4
- Device platform: armeabi-v7a
- Constructing environment
- Adding addon.d survival script
- Unpacking boot image
- Checking ramdisk status
- Magisk patched boot image detected
- Patching ramdisk
- Pre-init storage partition: userdata
- Repacking boot image
- Flashing new boot image
- Unmounting partitions
- Done
[amonet] Install boot patch... 
[amonet] OK
[amonet] Install recovery patch... 
[amonet] ALREADY_INSTALLED
Done processing script file
```
and bootloop after. this ones have success: 4d25fd3d, 6408416c

**Comment by osm0sis** [comment]
That's https://github.com/topjohnwu/Magisk/commit/17ba5cba3e8470a1fd8dcefa2817954098e5710e

Not sure what those other 2 are, since they're not in the commit list.

**Comment by tsynik** [comment]
looks like it's somewhere here
<img width="261" alt="hist" src="https://github.com/topjohnwu/Magisk/assets/1551446/5bd9a4c8-59fc-4b33-b690-e9fddcade406">

**Comment by vvb2060** [comment]
Yes, maybe the patched sepolicy has some features that are only supported by the new kernel.  This is a common problem when upgrading dependencies.

**Comment by tsynik** [comment]
> Yes, maybe the patched sepolicy has some features that are only supported by the new kernel. This is a common problem when upgrading dependencies.

ftv uses this kernel https://github.com/pretoriano80/android_kernel_amazon_mantis - 4.4.

**Comment by topjohnwu** [comment]
@tsynik may you upload the boot image for me? In theory it shall contain the sepolicy file in the ramdisk so I can investigate

**Comment by tsynik** [comment]
> may you upload the boot image? In theory it shall contain the sepolicy file in the ramdisk so I can investigate

@topjohnwu you mean working one with Magisk? Or after failed Magisk flash? Only way I can dump it if I'll flash v26.3 for example from Manager in OS and make dd of emmc boot partition before reboot, as on reboot device not bootable at all and only way to restore is to make full reflash again.

**Comment by chromer030** [comment]
Same here, Android 7.1.2 arm64

v26.1 OK
v26.3 bootloop

**Comment by canyie** [comment]
Can you try if this build works?

**Comment by tsynik** [comment]
> Can you try if this build works?

I have this error with it:
```/sdcard # twrp install Magisk-debug.zip 
Installing zip file '/data/media/0/Magisk-debug.zip'
Installing zip file '/data/media/0/Magisk-debug.zip'
Checking for Digest file...
Invalid zip file format!
Error installing zip file '/data/media/0/Magisk-debug.zip'```

**Comment by canyie** [comment]
You need to decompress it first, then flash `app-debug.apk`

**Comment by tsynik** [comment]
> You need to decompress it first, then flash `app-debug.apk`

flashed and booted OK

```
/sdcard # twrp install app-debug.zip 
Installing zip file '/data/media/0/app-debug.zip'
Installing zip file '/data/media/0/app-debug.zip'
Checking for Digest file...
[amonet] Load microloader from recovery... 
[amonet] Remove boot patch...
[amonet] OK
**********************************
 Magisk 4eaf701c(26301) Installer 
**********************************
- Mounting /system
- No vbmeta partition, patch vbmeta in boot image
- Target image: /dev/block/mmcblk0p4
- Device platform: armeabi-v7a
- Constructing environment
- Adding addon.d survival script
- Unpacking boot image
- Checking ramdisk status
- Magisk patched boot image detected
- Patching ramdisk
- Pre-init storage partition: userdata
- Repacking boot image
- Flashing new boot image
- Unmounting partitions
- Done
[amonet] Install boot patch... 
[amonet] OK
[amonet] Install recovery patch... 
[amonet] ALREADY_INSTALLED
Done processing script file

**Comment by vvb2060** [comment]
`key.specified` is `uint16_t`, `__builtin_popcount` is used for `uint32_t`

**Comment by vvb2060** [comment]
```
./magiskpolicy --load /sbin/.magisk/selinux/load
Load policy from: /sbin/.magisk/selinux/load
libsepol.avtab_read_item: more than one specifier: 0x8004
Fail to load policy from sepolicy
```
`0x8004` is `AVTAB_ENABLED | AVTAB_ALLOWED`
