### ISSUE TITLE
Magasik 26.3 rebooting device causes to crash

### ISSUE THREAD

**Issue by Okfucker** [topjohnwu/Magisk#7314]
Device:Infinix x660c
Android version:10
Magisk version name:26.3
Magisk version code:26301

The issue is very very simple just.
Only a little problem in boot.img. when it will be to patchedboot.img. it just open it and work without no problem but when I reboot the device all of thing will be messy just messy. That will happen only when rebooted I am so happy to your app .your app is awesome
Hint: I disabled vbmeta for device

Any person that have a mind any?

**Comment by Okfucker** [comment]
?

**Comment by osm0sis** [comment]
Vague and no logs.
