### ISSUE TITLE
Can't install modules with "Install from storage" - see issue #7317

### ISSUE THREAD

**Issue by diassynthesis** [topjohnwu/Magisk#7319]
I'm sure that this issue is not related to Magisk Version.
So, please reopen it.

-->

Device:REDMI Note 8 Pro
Android version:11
Magisk version name:26
Magisk version code:26301

**Comment by canyie** [comment]
You are using an old unsupported Magisk version. Any bug reports from unsupported versions won't be accepted. Close again.
