### ISSUE TITLE
Is there a way to intall Magisk to an Android emulator?

### ISSUE THREAD

**Issue by PureDark** [topjohnwu/Magisk#732]
I have been trying for a long time and without luck.

Emulators don't have a recovery mode.... I read that someone was able to install Magisk V12.0 on Android x86 7.1.2 rc2, using this tools to create a "fake" boot.img using kernel and ramdisk.img files.

Thought I'd ask if it is possible in current version, or can the author made a simple way to install this on emulators.

**Comment by xxRaiyanxxYT** [comment]
Hi, @PureDark

its Possible in *Nox* emulator... Nox Emulator It has The boot Img. But For some region It doesn't has Revovery, also You can install Magisk in it

**Comment by zulu99-zulu99** [comment]
It is possible install magisk on google android emulator, that come with android studio.

get the ramdisk.img and kernel and create a boot.img

patch the created boot image with magisk manager

split the patched_boot.img and use the new ramdisk.img

The problem is that new versions of Magisk, break the compatibility with the emulator.

I tested on Android emulator OREO and PIE

The last working Magisk version on both Android OREO and PIE is the magisk 16.6 

The problem with Magisk 18 on Oreo and PIE is this:

`[    3.066551] init: cannot setexeccon('u:r:magisk:s0') for ab4bRgk: Invalid argument
[   13.074987] init: wait for '/dev/.magisk.unblock' timed out and took 10008ms
[   13.083000] init: Command 'wait /dev/.magisk.unblock 10' action=post-fs-data (/init.magisk.rc:6) took 10016ms and failed: wait_for_file() failed
[   13.089982] init: Service 'ab4bRgk' (pid 1585) exited with status 6`

**Comment by KishinMukito** [comment]
@xxRaiyanxxYT

you say its possible to install it on nox but how do you do it? i tried it using the direct install option in magisk manager and it said it failed

**Comment by qauck** [comment]
> 
> 
> It is possible install magisk on google android emulator, that come with android studio.
> 
> get the ramdisk.img and kernel and create a boot.img
> 
> patch the created boot image with magisk manager
> 
> split the patched_boot.img and use the new patched ramdisk.img
> 
> The problem is that new versions of Magisk, break the compatibility with the emulator.
> 
> I tested on Android emulator OREO and PIE
> 
> The last working Magisk version on both Android OREO and PIE is the magisk 16.6
> 
> The problem with Magisk 18 on Oreo and PIE is this:
> 
> `[ 3.066551] init: cannot setexeccon('u:r:magisk:s0') for ab4bRgk: Invalid argument [ 13.074987] init: wait for '/dev/.magisk.unblock' timed out and took 10008ms [ 13.083000] init: Command 'wait /dev/.magisk.unblock 10' action=post-fs-data (/init.magisk.rc:6) took 10016ms and failed: wait_for_file() failed [ 13.089982] init: Service 'ab4bRgk' (pid 1585) exited with status 6`
> 
> If the developer of Magisk can help, we are very happy. I have already a working PIE emulator with last arm translation working (houdini). The only problem is that i must add Magisk 16.6 because last versions not work.

Can you share more details for how to create/split the boot.img? or share the patched working image for the emulator?

**Comment by topjohnwu** [comment]
I run Magisk in emulators. Might release documentations on how to do it soon.

**Comment by schumi2004** [comment]
I'm also interested on how to do this, can't wait ;)

**Comment by Mygod** [comment]
A related but different enhancement would be to bring it to Chrome OS (i.e. Android containers). 😀

**Comment by MAYBreath** [comment]
still no release documentations..waiting for you untill I am dead..

**Comment by wordlesswind** [comment]
There will not be a general guide.

topjohnwu:
> The basic idea is to find a way to replace `init` to `magiskinit`. There will not be a general guide for that since emulators does not have a clear standard.

https://github.com/topjohnwu/Magisk/issues/1255#issuecomment-485891789

**Comment by vrqq** [comment]
Note: In Android Emulator from Android Studio, Android 9.0 PIE x86, the ramdisk.img is useless, this file will not be loaded by qemu. (Try to zero it and the emulator run normally.)

The system.img will be mounted to / (device root), and kernel will load system.img/init directly. (The characteristic of A/B system)
See the detail by : https://github.com/topjohnwu/Magisk/issues/503

So, the Systemlessly should be implemented by another method in kernel?

By android-studio-ide-182.5314842-windows + Hypervisor Platform && Android 9.0 x86 without Google APPs.

**Comment by wordlesswind** [comment]
I think many people are not using Android Emulator from Android Studio.
Most people use virtual machines based on VirtualBox(etc. [MuMu](https://mumu.163.com/global/download/en/))
They provide a hard disk image directly instead of an installation image.
I tried to extract the boot partition using [DiskGenius](https://www.partitionguru.com/), but I failed.

**Comment by darkforce95** [comment]
any news on magisk on android emulator such as bluestack or memu ?

**Comment by neoblackxt** [comment]
I failed to install Magisk on Android O, P, and Q, but succeed on N. P image is system-as-root. I modified the advancedFeatures.ini file by changing "SystemAsRoot = on" to "off", but still failed, it even can't boot complete.

**Comment by neoblackxt** [comment]
Good news! [Update emulator.sh to support all AVD images](https://github.com/topjohnwu/Magisk/commit/ee39616a8bf5a55917f4dc6b0fcd45c70210b917)

**Comment by andronoob** [comment]
I got Magisk 20.1 installed on my AVD: https://github.com/topjohnwu/Magisk/issues/1255#issuecomment-559696946

I hope my comment would be helpful, however, I take no responsibility of potential damage/info leak/apocalypse etc :-)

**Comment by MAYBreath** [comment]
> I think many people are not using Android Emulator from Android Studio.
> Most people use virtual machines based on VirtualBox([MuMu](https://mumu.163.com/global/download/en/), [NoxPlayer](https://en.bignox.com/), etc. )
> They provide a hard disk image directly instead of an installation image.
> I tried to extract the boot partition using [DiskGenius](https://www.partitionguru.com/), but I failed.

I totally agree with you，but now magisk' emulator just support useless ADV..I even can not able open the pokemon on it.what a pity

**Comment by ttimasdf** [comment]
> I think many people are not using Android Emulator from Android Studio.
> Most people use virtual machines based on VirtualBox([MuMu](https://mumu.163.com/global/download/en/), [NoxPlayer](https://en.bignox.com/), etc. )
> They provide a hard disk image directly instead of an installation image.
> I tried to extract the boot partition using [DiskGenius](https://www.partitionguru.com/), but I failed.

@wordlesswind 

Nox VM use a shared, read-only system image for all VMs created with same template. You could open the virtual machine configuration with text editor to get the vmdk path. Open it with VMDK with DiskGenius, you can easily find in the MBR section that the Android system is booted by GRUB. You could further down from here 😄 

The example below is taken from a [community modified](https://www.52pojie.cn/thread-1185871-1-1.html) version of Android 5 base image of NoxVM.

![image](https://user-images.githubusercontent.com/2762704/93735581-ec74ad80-fc0f-11ea-9cad-2e29bbab2963.png)

**Comment by HemanthJabalpuri** [comment]
I have successfully, installed Magisk in MEmu 7.3.2 Android 7.1(25) x86(32) with https://forum.xda-developers.com/t/guide-magisk-and-xposed-for-memu-7-3-2.4222919/

**Comment by HemanthJabalpuri** [comment]
@wordlesswind @ttimasdf @Apihplays
If we can able to replace ramdisk in MEmu or LDPlayer with the paths as shown here https://forum.xda-developers.com/t/guide-magisk-supersu-and-xposed-for-memu-7-3-2-or-ldplayer-4-0-45.4222919/post-84723623 we can able to full root it.

Thanks

**Comment by Relers** [comment]
@HemanthJabalpuri 
If you have any success, reply in thread please
