### ISSUE TITLE
Can module's script send log to magisk log?

### ISSUE THREAD

**Issue by noname8964** [topjohnwu/Magisk#733]
can post-fs-data or service script in module send logs to magisk log?
I source /data/adb/magisk/util_function.sh and use ui_print but nothing in magisk manager logcat.

**Comment by Didgeridoohan** [comment]
Completely the wrong place! Close this and open a thread on xda instead!

**Comment by noname8964** [comment]
OK, thanks

**Comment by alexyao2015** [comment]
For anyone else that comes here from Google, Magisk logs are retrieved in the app [here](https://github.com/topjohnwu/Magisk/blob/b1faa5eed4f5c52cc60a90ca74744a77fde07575/app/src/main/java/com/topjohnwu/magisk/data/repository/LogRepository.kt#L32). Simply writing to `/cache/magisk.log` will cause the log to appear in the app.
