### ISSUE TITLE
Manual magiskboot AVB1 signing broken

### ISSUE THREAD

**Issue by osm0sis** [topjohnwu/Magisk#7330]
Device: Any
Android version: Any
Magisk version name: d4e552d0
Magisk version code: 26301

Using an unsigned boot.img, `magiskboot sign boot.img` shows the input file info, then just hangs; instead of outputting a signed copy to the input file in-place, it appears to fill the input file to 4gb then resets back to zero bytes, then loops. No change to the other command-line options (i.e. /boot or /recovery for [name], or supplying a [x509.pem pk8] pair) seems to make any difference.

AVB1 signing does work fine with `magiskboot repack boot.img`. Wondering if it's because `magiskboot sign` is the only magiskboot feature that doesn't have optional [outfile] handling, so perhaps it's trying to write as it reads, creating an infinite file? On that note, having [outfile] handling to match the other features would be nice!

Less serious, but also worth mentioning that when using an AVB2 (VBMETA) signed boot.img, `magiskboot verify boot.img` (and therefore also `magiskboot unpack boot.img`) shows the following error/warning output in the log:
```
[boot/sign.rs:241] unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [1] (primitive)
```

**Comment by yujincheng08** [comment]
any example boot image for test?

**Comment by osm0sis** [comment]
Any unsigned boot.img, I'll whip one up for you.

**Comment by lprot** [comment]
One more boot.img bringing the same error. Tested on the latest app-debug.apk

[boot.zip](https://github.com/user-attachments/files/18948457/boot.zip)

**Comment by osm0sis** [comment]
Not the same issue, open your own.
