### ISSUE TITLE
Magisk won't work on Sony Walkman NW-ZX507

### ISSUE THREAD

**Issue by notcbw** [topjohnwu/Magisk#7337]
Device: Sony Walkman NW-ZX507
Android version: 9.0.0
Magisk version name: Debug
Magisk version code: 26301

Similar to #7091. Magisk doesn't load despite the boot.img was patched and flashed. The original boot.img was attached with the logs taken while using the patched boot.img. I had to use KernelSU to take the dmesg so I apologise if that would cause incompatibilities, but it also didn't work before the kernel had KernelSU.

[dmesg.txt](https://github.com/topjohnwu/Magisk/files/12595864/dmesg.txt)
[logcat.txt](https://github.com/topjohnwu/Magisk/files/12595865/logcat.txt)
[boot-zx500.img.zip](https://github.com/topjohnwu/Magisk/files/12595868/boot-zx500.img.zip)

**Comment by notcbw** [comment]
I tried to disable skip_initramfs as per the suggested method in #7091 but it still doesn't seem to disable it. Here's the bugreport after changing `init/initramfs.c`:

[bugreport-icx1295_005-4.04.00-2023-09-16-00-39-09.zip](https://github.com/topjohnwu/Magisk/files/12639861/bugreport-icx1295_005-4.04.00-2023-09-16-00-39-09.zip)

[HERE's](https://drive.google.com/file/d/1z8CucsLx0LJ-0HU50QxVYnx8VHVroP7U/view?usp=sharing) the firmware used in the device (other than the kernel) in case it could provide some clue.

**Comment by canyie** [comment]
Since you have KernelSU, can you execute the following command with root and tell me its output?
```shell
ls -l /dev/block/bootdevice/by-name/
```

**Comment by notcbw** [comment]
> Since you have KernelSU, can you execute the following command with root and tell me its output?
> 
> ```shell
> ls -l /dev/block/bootdevice/by-name/
> ```

No such file or directory.

But the output for `/dev/block/by-name` is:
```
icx1295:/ # ls -l /dev/block/by-name                                                                                          
total 0
lrwxrwxrwx 1 root root 20 2023-10-04 14:29 boot_a -> /dev/block/mmcblk2p3
lrwxrwxrwx 1 root root 20 2023-10-04 14:29 boot_b -> /dev/block/mmcblk2p4
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 boot_logo -> /dev/block/mmcblk2p20
lrwxrwxrwx 1 root root 45 2023-10-04 14:29 bootloader -> /dev/block/platform/30b60000.mmc/mmcblk2boot0
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 bootloader_a -> /dev/block/mmcblk2p23
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 bootloader_b -> /dev/block/mmcblk2p24
lrwxrwxrwx 1 root root 20 2023-10-04 14:29 dtbo_a -> /dev/block/mmcblk2p1
lrwxrwxrwx 1 root root 20 2023-10-04 14:29 dtbo_b -> /dev/block/mmcblk2p2
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 fbmisc -> /dev/block/mmcblk2p12
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 idd -> /dev/block/mmcblk2p21
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 m4_os_a -> /dev/block/mmcblk2p25
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 m4_os_b -> /dev/block/mmcblk2p26
lrwxrwxrwx 1 root root 20 2023-10-04 14:29 metadata -> /dev/block/mmcblk2p8
lrwxrwxrwx 1 root root 20 2023-10-04 14:29 misc -> /dev/block/mmcblk2p7
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 nvp -> /dev/block/mmcblk2p15
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 opt1 -> /dev/block/mmcblk2p17
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 opt2 -> /dev/block/mmcblk2p18
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 opt3 -> /dev/block/mmcblk2p19
lrwxrwxrwx 1 root root 20 2023-10-04 14:29 presistdata -> /dev/block/mmcblk2p9
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 rca -> /dev/block/mmcblk2p22
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 rsv_boot -> /dev/block/mmcblk2p27
lrwxrwxrwx 1 root root 20 2023-10-04 14:29 system_a -> /dev/block/mmcblk2p5
lrwxrwxrwx 1 root root 20 2023-10-04 14:29 system_b -> /dev/block/mmcblk2p6
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 userdata -> /dev/block/mmcblk2p28
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 var -> /dev/block/mmcblk2p16
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 vbmeta_a -> /dev/block/mmcblk2p13
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 vbmeta_b -> /dev/block/mmcblk2p14
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 vendor_a -> /dev/block/mmcblk2p10
lrwxrwxrwx 1 root root 21 2023-10-04 14:29 vendor_b -> /dev/block/mmcblk2p11

```

Hope that's what you are asking for.

**Comment by canyie** [comment]
Hmmm, devices is A/B and no separated  recovery partition... `system_a` mounted as rootfs  🤔 

Can you replace these lines:
https://github.com/notcbw/2019_android_walkman/blob/6d933dd41c34c43d404b27de1ea08e5ca697050f/kernel_imx/init/initramfs.c#L626-L630
with a log:
```c
printk(KERN_INFO "Skipped checking skip_initramfs\n");
```
then compile the kernel to test?

**Comment by notcbw** [comment]
@canyie Here's the bug report
[bugreport-icx1295_005-4.04.00-2023-10-11-02-04-57.zip](https://github.com/topjohnwu/Magisk/files/12865521/bugreport-icx1295_005-4.04.00-2023-10-11-02-04-57.zip)

**Comment by canyie** [comment]
```
<3>[    5.117495] Warning: unable to open an initial console.
<6>[    5.133460] EXT4-fs (mmcblk2p5): mounted filesystem without journal. Opts: (null)
<6>[    5.133537] VFS: Mounted root (ext4 filesystem) readonly on device 179:5.
<6>[    5.134117] devtmpfs: mounted
<6>[    5.138177] Freeing unused kernel memory: 4800K
<14>[    5.183250] init: init first stage started!
```
`/system` still be directed mounted as root and our log is not printed 🤔

**Comment by notcbw** [comment]
```
<6>[    0.510306] Skipped checking skip_initramfs
```
Is this not it?

**Comment by notcbw** [comment]
Is it because of that in the kernel command line, the root is specified as the system partition? For the walkman the root parameter is like `root=PARTUUID=something` and not a ramdisk

I took a look at the kernel command for my pixel 7 and it just says `root=/dev/ram0`

But then this command was probably appended by u-boot. I can't change it in the boot image.

**Comment by notcbw** [comment]
I did some digging. Apparently it's a system-on-root device, and the ramdisk inside boot.img is only used for recovery. But for some reason, even if the ramdisk is patched, I can't enable magisk with the recovery key combination, and the magisk app says "Ramdisk: Yes"

**Comment by yujincheng08** [comment]
`root=PARTUUID=982f48bd-2a3c-43e0-bde6-b50258ed9774` can u figure out what parition is it?

**Comment by yujincheng08** [comment]
Is `CONFIG_INITRAMFS_FORCE` set in the kernel?

**Comment by cykrr** [comment]
> I did some digging. Apparently it's a system-on-root device, and the ramdisk inside boot.img is only used for recovery. But for some reason, even if the ramdisk is patched, I can't enable magisk with the recovery key combination, and the magisk app says "Ramdisk: Yes"


These are the contents of mmcblk2p5 (system_a)
```
root@DESKTOP-K6OM226:/mnt/tmp# ls
acct        d             init.environ.rc                init.usb.rc          oem          sdcard
bin         data          init.rc                        init.zygote32.rc     postinstall  storage
bugreports  default.prop  init.recovery.icx1293.emmc.rc  init.zygote64_32.rc  proc         sys
cache       dev           init.recovery.icx1293.rc       lost+found           product      system
charger     etc           init.recovery.icx1293.sd.rc    mnt                  res          ueventd.rc
config      init          init.usb.configfs.rc           odm                  sbin         vendor
root@DESKTOP-K6OM226:/mnt/tmp#
```

As it's system-as-root, could it be the case that the initramfs is on system and not ramdisk?
