### ISSUE TITLE
OutOfMemory error when patching AP tar

### ISSUE THREAD

**Issue by tyilo** [topjohnwu/Magisk#7341]
Magisk app runs out of memory when patching the AP tar for Samsung Galaxy Tab A8. The original AP file `AP_X200XXS3CWG2_X200XXS3CWG2_MQB67537159_REV00_user_low_ship_MULTI_CERT_meta_OS13.tar` is 8,148,398,200 bytes in size, which might be the problem?

Device: Samsung Galaxy Tab A8 (SM-X200)
Android version: 13
Magisk version name: 9aa466c7
Magisk version code: 26301

Logcat output:
```
09-13 15:51:24.830 19449 19481 I opjohnwu.magisk: Starting a blocking GC Alloc
09-13 15:51:24.830 19449 19481 I opjohnwu.magisk: Starting a blocking GC Alloc
09-13 15:51:24.860 19449 19481 I opjohnwu.magisk: Alloc concurrent copying GC freed 44116(1901KB) AllocSpace objects, 2(2056KB) LOS objects, 49% free, 6272KB/12MB, paused 231us,28us total 29.160ms
09-13 15:51:24.860 19449 19481 I opjohnwu.magisk: Forcing collection of SoftReferences for 750MB allocation
09-13 15:51:24.860 19449 19481 I opjohnwu.magisk: Starting a blocking GC Alloc
09-13 15:51:24.886 19449 19481 I opjohnwu.magisk: Alloc concurrent copying GC freed 11232(443KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5877KB/11MB, paused 31us,30us total 26.250ms
09-13 15:51:24.887 19449 19481 W opjohnwu.magisk: Throwing OutOfMemoryError "Failed to allocate a 787223172 byte allocation with 6018333 free bytes and 186MB until OOM, target footprint 12036669, growth limit 201326592" (VmSize 7034852 kB)
09-13 15:51:24.887 19449 19481 I opjohnwu.magisk: Starting a blocking GC Alloc
09-13 15:51:24.887 19449 19481 I opjohnwu.magisk: Starting a blocking GC Alloc
09-13 15:51:24.905 19449 19481 I opjohnwu.magisk: Alloc concurrent copying GC freed 41(63KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5861KB/11MB, paused 32us,22us total 17.683ms
09-13 15:51:24.905 19449 19481 I opjohnwu.magisk: Forcing collection of SoftReferences for 750MB allocation
09-13 15:51:24.905 19449 19481 I opjohnwu.magisk: Starting a blocking GC Alloc
09-13 15:51:24.930 19449 19481 I opjohnwu.magisk: Alloc concurrent copying GC freed 821(73KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5836KB/11MB, paused 29us,28us total 24.910ms
09-13 15:51:24.930 19449 19481 W opjohnwu.magisk: Throwing OutOfMemoryError "Failed to allocate a 787223176 byte allocation with 5976414 free bytes and 186MB until OOM, target footprint 11952830, growth limit 201326592" (VmSize 7034852 kB)
09-13 15:51:25.016   608   608 E YLog    : /system_ext/etc/ylogsource.conf load failed...  error  [2(No such file or directory)]  [startlogServcie]
09-13 15:51:25.052 19449 19449 E App     : java.lang.OutOfMemoryError: Failed to allocate a 787223176 byte allocation with 5976414 free bytes and 186MB until OOM, target footprint 11952830, growth limit 201326592
09-13 15:51:25.052 19449 19449 E App     :      at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:79)
09-13 15:51:25.052 19449 19449 E App     :      at kotlin.io.ByteStreamsKt.readBytes(IOStreams.kt:135)
09-13 15:51:25.052 19449 19449 E App     :      at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.processTar(MagiskInstaller.kt:210)
09-13 15:51:25.052 19449 19449 E App     :      at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.handleFile(MagiskInstaller.kt:407)
09-13 15:51:25.052 19449 19449 E App     :      at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.patchFile(MagiskInstaller.kt:533)
09-13 15:51:25.052 19449 19449 E App     :      at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Patch.operations(MagiskInstaller.kt:581)
09-13 15:51:25.052 19449 19449 E App     :      at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$result$1.invokeSuspend(MagiskInstaller.kt:550)
09-13 15:51:25.052 19449 19449 E App     :      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
09-13 15:51:25.052 19449 19449 E App     :      Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@483a6d0, Dispatchers.Main.immediate]
09-13 15:51:25.055 19449 19449 I opjohnwu.magisk: System.exit called, status: 1
09-13 15:51:25.055 19449 19449 I AndroidRuntime: VM exiting with result code 1, cleanup skipped.
09-13 15:51:25.129  1081  2872 D InputMethodManagerService: removeClient
09-13 15:51:25.130  1081  6407 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10226/19449, [NetworkRequest [ LISTEN id=294, [ Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&FOREGROUND&NOT_VCN_MANAG
ED Uid: 10226 RequestorUid: 10226 RequestorPkg: com.topjohnwu.magisk UnderlyingNetworks: Null] ]], android.os.BinderProxy@16c1820)
09-13 15:51:25.130  1081  1369 I WindowManager: WIN DEATH: Window{6200a8b u0 com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity}
09-13 15:51:25.130  1081  2872 D InputTransport: Input channel destroyed: 'ClientS', fd=735
09-13 15:51:25.130  1081  2872 V InputMethodManagerService: hideCurrentInputLocked : canceled, shouldHideSoftInput=false, mInputShown=false, mImeWindowVis=0
09-13 15:51:25.131   694   734 I gralloc4: unregister: id=27d000002ec, handle:0xb4000070379dee00, vaddr=0x702ac34000
09-13 15:51:25.132  1081  2522 I ActivityManager: Process com.topjohnwu.magisk (pid 19449) has died: fg  TOP (143,749)
09-13 15:51:25.132  1081  1369 D InputTransport: Input channel destroyed: '6200a8b', fd=890
09-13 15:51:25.132  1081  1369 W InputManager-JNI: Input channel object '6200a8b com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity (client)' was disposed without first being removed with the input manager!
09-13 15:51:25.132  1081  1369 D InputTransport: Input channel destroyed: '6200a8b', fd=891
09-13 15:51:25.133   624   624 I Zygote  : Process 19449 exited cleanly (1)
```

**Comment by BlackMesa123** [comment]
Looks like it is a limitation of your device due to the small amount of RAM it has (2/4GB as per [GSMArena](https://www.gsmarena.com/samsung_galaxy_tab_a8_10_5_(2021)-11265.php)), the processTar function might need to be reworked.

**Comment by BlackMesa123** [comment]
The issue seems to happen when handling the vbmeta img inside the AP tar:
https://github.com/topjohnwu/Magisk/blob/4745e86c1b319d0736c948e9dcf95d528c2f1941/app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt#L210
Maybe using `FileOutputStream` rather than `ByteArrayOutputStream` would be a way to fix this? I don't like the idea of enabling `android:largeHeap` in the app Manifest.

**Comment by darker16** [comment]
> Samsung Galaxy Tab A8 အတွက် AP tar ကို ဖာထေးသောအခါ Magisk အက်ပ်သည် မှတ်ဉာဏ်ကုန်သွားပါသည်။ မူရင်း AP ဖိုင် `AP_X200XXS3CWG2_X200XXS3CWG2_MQB67537159_REV00_user_low_ship_MULTI_CERT_meta_OS13.tar`သည် 8,148,398,200 bytes အရွယ်အစားဖြစ်ပြီး၊ မည်သည့်ပြဿနာရှိနိုင်သနည်း။
> 
> စက်ပစ္စည်း- Samsung Galaxy Tab A8 (SM-X200) Android ဗားရှင်း- 13 Magisk ဗားရှင်းအမည်: [9aa466c](https://github.com/topjohnwu/Magisk/commit/9aa466c7730ef4ef73195b476f9804ebf86932d2) Magisk ဗားရှင်းကုဒ်: 26301
> 
> Logcat အထွက်-
> 
> ```
> 09-13 15:51:24.830 19449 19481 I opjohnwu.magisk: Starting a blocking GC Alloc
> 09-13 15:51:24.830 19449 19481 I opjohnwu.magisk: Starting a blocking GC Alloc
> 09-13 15:51:24.860 19449 19481 I opjohnwu.magisk: Alloc concurrent copying GC freed 44116(1901KB) AllocSpace objects, 2(2056KB) LOS objects, 49% free, 6272KB/12MB, paused 231us,28us total 29.160ms
> 09-13 15:51:24.860 19449 19481 I opjohnwu.magisk: Forcing collection of SoftReferences for 750MB allocation
> 09-13 15:51:24.860 19449 19481 I opjohnwu.magisk: Starting a blocking GC Alloc
> 09-13 15:51:24.886 19449 19481 I opjohnwu.magisk: Alloc concurrent copying GC freed 11232(443KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5877KB/11MB, paused 31us,30us total 26.250ms
> 09-13 15:51:24.887 19449 19481 W opjohnwu.magisk: Throwing OutOfMemoryError "Failed to allocate a 787223172 byte allocation with 6018333 free bytes and 186MB until OOM, target footprint 12036669, growth limit 201326592" (VmSize 7034852 kB)
> 09-13 15:51:24.887 19449 19481 I opjohnwu.magisk: Starting a blocking GC Alloc
> 09-13 15:51:24.887 19449 19481 I opjohnwu.magisk: Starting a blocking GC Alloc
> 09-13 15:51:24.905 19449 19481 I opjohnwu.magisk: Alloc concurrent copying GC freed 41(63KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5861KB/11MB, paused 32us,22us total 17.683ms
> 09-13 15:51:24.905 19449 19481 I opjohnwu.magisk: Forcing collection of SoftReferences for 750MB allocation
> 09-13 15:51:24.905 19449 19481 I opjohnwu.magisk: Starting a blocking GC Alloc
> 09-13 15:51:24.930 19449 19481 I opjohnwu.magisk: Alloc concurrent copying GC freed 821(73KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5836KB/11MB, paused 29us,28us total 24.910ms
> 09-13 15:51:24.930 19449 19481 W opjohnwu.magisk: Throwing OutOfMemoryError "Failed to allocate a 787223176 byte allocation with 5976414 free bytes and 186MB until OOM, target footprint 11952830, growth limit 201326592" (VmSize 7034852 kB)
> 09-13 15:51:25.016   608   608 E YLog    : /system_ext/etc/ylogsource.conf load failed...  error  [2(No such file or directory)]  [startlogServcie]
> 09-13 15:51:25.052 19449 19449 E App     : java.lang.OutOfMemoryError: Failed to allocate a 787223176 byte allocation with 5976414 free bytes and 186MB until OOM, target footprint 11952830, growth limit 201326592
> 09-13 15:51:25.052 19449 19449 E App     :      at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:79)
> 09-13 15:51:25.052 19449 19449 E App     :      at kotlin.io.ByteStreamsKt.readBytes(IOStreams.kt:135)
> 09-13 15:51:25.052 19449 19449 E App     :      at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.processTar(MagiskInstaller.kt:210)
> 09-13 15:51:25.052 19449 19449 E App     :      at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.handleFile(MagiskInstaller.kt:407)
> 09-13 15:51:25.052 19449 19449 E App     :      at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.patchFile(MagiskInstaller.kt:533)
> 09-13 15:51:25.052 19449 19449 E App     :      at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Patch.operations(MagiskInstaller.kt:581)
> 09-13 15:51:25.052 19449 19449 E App     :      at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$result$1.invokeSuspend(MagiskInstaller.kt:550)
> 09-13 15:51:25.052 19449 19449 E App     :      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
> 09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
> 09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
> 09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
> 09-13 15:51:25.052 19449 19449 E App     :      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
> 09-13 15:51:25.052 19449 19449 E App     :      Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@483a6d0, Dispatchers.Main.immediate]
> 09-13 15:51:25.055 19449 19449 I opjohnwu.magisk: System.exit called, status: 1
> 09-13 15:51:25.055 19449 19449 I AndroidRuntime: VM exiting with result code 1, cleanup skipped.
> 09-13 15:51:25.129  1081  2872 D InputMethodManagerService: removeClient
> 09-13 15:51:25.130  1081  6407 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10226/19449, [NetworkRequest [ LISTEN id=294, [ Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&FOREGROUND&NOT_VCN_MANAG
> ED Uid: 10226 RequestorUid: 10226 RequestorPkg: com.topjohnwu.magisk UnderlyingNetworks: Null] ]], android.os.BinderProxy@16c1820)
> 09-13 15:51:25.130  1081  1369 I WindowManager: WIN DEATH: Window{6200a8b u0 com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity}
> 09-13 15:51:25.130  1081  2872 D InputTransport: Input channel destroyed: 'ClientS', fd=735
> 09-13 15:51:25.130  1081  2872 V InputMethodManagerService: hideCurrentInputLocked : canceled, shouldHideSoftInput=false, mInputShown=false, mImeWindowVis=0
> 09-13 15:51:25.131   694   734 I gralloc4: unregister: id=27d000002ec, handle:0xb4000070379dee00, vaddr=0x702ac34000
> 09-13 15:51:25.132  1081  2522 I ActivityManager: Process com.topjohnwu.magisk (pid 19449) has died: fg  TOP (143,749)
> 09-13 15:51:25.132  1081  1369 D InputTransport: Input channel destroyed: '6200a8b', fd=890
> 09-13 15:51:25.132  1081  1369 W InputManager-JNI: Input channel object '6200a8b com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity (client)' was disposed without first being removed with the input manager!
> 09-13 15:51:25.132  1081  1369 D InputTransport: Input channel destroyed: '6200a8b', fd=891
> 09-13 15:51:25.133   624   624 I Zygote  : Process 19449 exited cleanly (1)
> ```
