### ISSUE TITLE
Magisk crashing when trying to download module (no logcat either)

### ISSUE THREAD

**Issue by iiNexure** [topjohnwu/Magisk#7344]
Device: SM-T970
Android version: 13
Magisk version name: 26.3
Magisk version code: 26301

Magisk crashing when trying to install a module, apps like fox's magisk module manager can't install modules either, I disabled all modules to see if there is anything affecting it, I reinstalled magisk by direct download. The magisk app isn't giving me a log cat either. I don't know what else to do

**Comment by iiNexure** [comment]
I have tried lots of things, downgrading, using different variants of magisk (canary, stable, beta, debug) and still nothing

**Comment by vvb2060** [comment]
We can't help you without logs

**Comment by iiNexure** [comment]
Where can I get the log? Any directory with the log cat?
