### ISSUE TITLE
App loses Recovery mode user setting for A-only legacy SAR devices

### ISSUE THREAD

**Issue by pndwal** [topjohnwu/Magisk#7346]
[magisk_log_2023-09-13T07.25.50.log](https://github.com/topjohnwu/Magisk/files/12614486/magisk_log_2023-09-13T07.25.50.log)
Device: Xiaomi Redmi Note 8T
Android version: 11
Magisk version code: 26301

From 26105, Magisk App loses Recovery mode user setting for A-only legacy SAR devices... 

On my Xiaomi RN8T I do not need Recovery mode despite this being an A-only legacy SAR (Ramdisk - No) device (bootloader supports ramdisk in /boot as added by Magisk patching) so I uncheck the option. However whenever the App is fully closed and reopened or some App functions are performed, the option is automatically checked again in the Install menu...

This means that unless users are aware their selection is lost/overridden and reset this every time they open/use Magisk App, Xiaomi devices etc behave strangely:

if user takes reboot system they end up in recovery, and if taking Direct Install /recovery is patched... On Samsung devices /recovery will be patched when taking Patch image also...

I had hoped that this issue would be solved by these fixes in 26202:
[Fix device detection scripts and logic](https://github.com/topjohnwu/Magisk/commit/75d905a56d6d7ceee62dc83be9c637870bc35a65) and [Always check mounts to detect legacy SAR on bootmode](https://github.com/topjohnwu/Magisk/commit/de00f1d5a94b83ad7bf49b0bdffab310e58db471)
but it continues to affect L-SAR (A-only) device users...

Including a log here taken from Alpha Magisk, but I did confirm that the issue occurs on TJW Canary and Debug Magisk also... I can supply new (Debug build) log if needed.

**Comment by samulksy** [comment]
Hello.

I have a Moto G5S Plus phone that is stuck in an infinite loop, that is, it keeps restarting endlessly without being able to load the operating system. This happened after I moved Magisk from a system file to a regular file. Magisk is a tool that allows rooting the phone and modifying the operating system without changing the system partition. Rooting is for an anti-theft tracker to work on the phone's system.
I've tried various ways to uninstall Magisk from my phone, but none of them worked. I can't access the operating system or enable USB debugging, which are requirements for most file-copying methods and device settings. Enter recovery mode or bootloader mode, which are special modes that allow accessing some advanced functions of the device is possible, but do not offer the option to copy the files. The recovery mode would be to delete all current files. Deletar novos arquivos não é o que eu I need. Installing a new ROM, performing a hard reset, or unlocking the bootloader, those features are accessible.
I can only see the black screen with the Android robot, which presents the following options: qcom, bp tools, barcodes, factory mode, power off, recovery mode, and restart bootloader. None of these options allow me to uninstall Magisk or restore the original operating system.
I have the IMEI of my phone, which is a unique code that identifies my device and can be useful for blocking or tracking my phone in case of loss or theft. I also have important data on my phone that I would like to back up before performing any procedures that could erase them.
I would like to know if anyone from the Google community has any tips or solutions for my problem. I've already searched the internet and haven't found anything that helped me. I'm desperate and don't know what else to do.
Please, if anyone can help me, I would be very grateful.

Thank you for your attention.

**Comment by canyie** [comment]
```shell
cat $(magisk --path)/.magisk/config
```

**Comment by samulksy** [comment]
Please check the result.What do I do?Thanks.
    Em sábado, 16 de setembro de 2023 às 22:07:09 BRT, 残页 ***@***.***> escreveu:  
 
 

cat $(magisk --path)/.magisk/config

**Comment by canyie** [comment]
Can you test if this one did the trick?
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/12708095/app-debug.zip)

**Comment by pndwal** [comment]
> Can you test if this one did the trick? [app-debug.zip](https://github.com/topjohnwu/Magisk/files/12708095/app-debug.zip)

Partly... Thanks for efforts!

Setting no longer reverts to Recovery Mode selected, which is good for devices like Xiaomi that accept ramdisk in /boot despite Recovery = No...

However user selection is still not retained... If Recovery Mode is selected and app is fully closed, setting now reverts to Recovery Mode _unselected_... This is bad for devices like Samsung S10 where Bootloader doesn't accept ramdisk in /boot... Selection should be retained so reboot option works properly by rebooting to system with Magisk via recovery.

Before this regression, Recovery Mode user selection.was properly retained in both A-only L-SAR use cases.

**Comment by samulksy** [comment]
Hello.
Thank you for remembering the message.
I have not tested the application you present. I don't know how to trigger the application. You can present the application activation procedure.
I realized that I made a mistake by uninstalling Magisk the common way. Ordinary uninstallation of Magisk causes infinite reboots. The uninstallation was not through Magisk. I didn't know the situation was about to happen, so the USB debugger wasn't activated. The error was corrected as a formatting, but without deleting all the files on the cell phone. I found that procedure on YouTube. I want to take this opportunity to present that: One way of rooting to avoid vulnerability problems on your cell phone would be rooting without unlocking the bootloader. A cell phone without a bootloader causes the vulnerability. Magisk is good, but Magisk could be better.
Thank you for your attention.

    Em domingo, 24 de setembro de 2023 às 06:44:46 BRT, pndwal ***@***.***> escreveu:  
 
 



Can you test if this one did the trick? app-debug.zip


Partly... Thanks for efforts!

Setting no longer reverts to Recovery Mode selected, which is good for devices like Xiaomi that accept ramdisk in /boot despite Recovery = No...

However user selection is still not retained... If Recovery Mode is selected and app is fully closed, setting now reverts to Recovery Mode unselected... This is bad for devices like Samsung S10 where Bootloader doesn't accept ramdisk in /boot... Selection should be retained so reboot option works properly by rebooting to system with Magisk via recovery.

Before this regression, Recovery Mode user selection.was properly retained in both A-only L-SAR use cases.

**Comment by samulksy** [comment]
Hello again.
Who am I communicating with?
I don't know how to install the application. What would be the application installation procedure?
Thank you for your concern.

    Em domingo, 24 de setembro de 2023 às 05:27:08 BRT, 残页 ***@***.***> escreveu:  
 
 


Can you test if this one did the trick?
app-debug.zip

**Comment by pndwal** [comment]
> Hello again.
Who am I communicating with?...

You're not. You're spamming Magisk issues... So please STOP. ☹️

**Comment by samulksy** [comment]
I'm sorry. My intention was never to interfere with your work. I tried to present flaws in the search for improvement. 
I have nothing against Magisk. Magisk is a program. I use Magisk.
Thank you for your attention.

    Em domingo, 24 de setembro de 2023 às 12:02:05 BRT, pndwal ***@***.***> escreveu:  
 
 



Hello again.
Who am I communicating with?...


You're not. You're spamming Magisk issues... So please STOP. ☹️

**Comment by pndwal** [comment]
Also, Recovery Mode should be checked (selected) by default as the assumption with Ramdisk - No is that Magisk in /boot shouldn't work... However for Xiaomi etc, if user unchecks it (as bootloader actually supports manually added ramdisk), the setting (for Boot Mode Magisk) should persist (not revert).

This is the way it worked before 26105.

**Comment by canyie** [comment]
On devices whose bootloader really doesn't accept ramdisk in boot.img like many Samsung devices, the app should see `RECOVERYMODE=true` in `$(magisk --path)/.magisk/config` and automaticlly checks the checkbox, so I don't think we need retain the state after app is force closed.

**Comment by pndwal** [comment]
Oh... So this is a behaviour change!?... Will App now revert user setting to match config RECOVERYMODE value?... Will user settings stick if App is closed before rooting?... I guess whenever root is lost (eg after ROM updates) users may now need to reselect Recovery Mode?

Previously, Recovery Mode was simply pre-selected on any device where Ramdisk= No before even rooting (based on John's reasoning that we cannot expect bootloader support for ramdisk in/boot or Boot Mode Magisk where device shipped without generic ramdisk in boot), but if a user changed this (de-selected) the user selection would always stick (persist), and since the (2019) commit for adding ramdisk CPIO (with magiskinit) to /boot when missing, booting Boot Mode Magisk could be attempted and might succeed if B/L inexplicably supported it...

This behaviour has worked well for years and I'm just not sure of the benefits losing state retention in favour of automating Recovery Mode setting when root exists, especially as a user selection being lost/overridden both when rooted or (differently) before rooting is bound to cause confusion. 😬

**Comment by samulksy** [comment]
Hello.
Thanks for the tip.
In your mention it is not specified whether or not the application can maintain the bootloader. You highlight that the app checks a specific setting on Samsung devices to bypass bootloader restrictions, but does not mention whether the application is capable of modifying or maintaining the bootloader.
Thank you for your understanding and attention.

    Em terça-feira, 26 de setembro de 2023 às 07:06:02 BRT, 残页 ***@***.***> escreveu:  
 
 


On devices whose bootloader really doesn't accept ramdisk in boot.img like many Samsung devices, the app should see RECOVERYMODE=true in $(magisk --path)/.magisk/config and automaticlly checks the checkbox, so I don't think we need retain the state after app is force closed.

**Comment by samulksy** [comment]
Hi.
I don't know if you know, but I need an anti-theft app. An anti-theft application to work on the operating system. On Android operating system.I need a way for the anti-theft application to work on the system without the need for rooting.
Do you have tips?
Thank you.

    Em terça-feira, 26 de setembro de 2023 às 11:30:42 BRT, pndwal ***@***.***> escreveu:  
 
 


Oh... So this is a behaviour change!?... Will App now revert user setting to match config RECOVERYMODE value?... Will user settings stick if App is closed before rooting?... I guess whenever root is lost (eg after ROM updates) users may now need to reselect Recovery Mode?

Previously, Recovery Mode was simply pre-selected on any device where Ramdisk= No before even rooting (based on John's reasoning that we cannot expect bootloader support for ramdisk in/boot or Boot Mode Magisk where device shipped without generic ramdisk in boot), but if a user changed this (de-selected) the user selection would always stick (persist), and since the (2019) commit for adding ramdisk CPIO (with magiskinit) to /boot when missing, booting Boot Mode Magisk could be attempted and might succeed if B/L inexplicably supported it...

This behaviour has worked well for years and I'm just not sure of the benefits losing state retention in favour of automating Recovery Mode setting when root exists, especially as a user selection being lost/overridden both when rooted or (differently) before rooting is bound to cause confusion. 😬

**Comment by samulksy** [comment]
Hello.
I'm sorry.
What is your email address?
I need to send a message to you without inconvenience.
Thanks.
    Em quarta-feira, 27 de setembro de 2023 às 12:39:56 BRT, pndwal ***@***.***> escreveu:  
 
 


STOP SPAMMING on GitHub!... Are you trying to get banned???

**Comment by canyie** [comment]
I don't think there is a behavior change, because I think the state can't be retained before flashing in old versions as well

**Comment by pndwal** [comment]
Ah yes... I think you're right... Recovery mode was pre-selected if Ramdisk = No, but once rooted seems to revert to .magisk/config RECOVERYMODE value... My bad! (Just refreshed my memory w/ 26102)  🙃

So re.

> Can you test if this one did the trick? [app-debug.zip](https://github.com/topjohnwu/Magisk/files/12708095/app-debug.zip)

seems the regression fix actually works well... Sorry for the assumptions, and many thanks!
