### ISSUE TITLE
Lineage OS 20 on Xiaomi Poco F3 - Magisk causes UI crash/blinking

### ISSUE THREAD

**Issue by raqua** [topjohnwu/Magisk#7348]
Device: Xiaomi Poco F3
Android version: Android 13 / Lineage OS 20
Magisk version name: d4e552d0
Magisk version code: 26301

I had Magisk working on this device on Lineage 19, but after upgrade to Lineage 20 all works until I flash Magisk. Flashing produces no errors and appears to finish successfully. After boot I get only black screen. Holding power button, I get reboot menu. ADB is also still working. Reflashing Lineage OS fixes the issue.
When I removed my screen lock, after boot I get to my home screen, but it is blinking as if it is restarting rapidly, every second. Phone is unusable.
Note - there is no bootloop, there is GUI loop (?)
I have tried versions 26.1, 26.3. I use no modules.

What I tried and did:
- Installed Magisk by flashing apk from Lineage OS recovery as I always did until now.

- Installed using official method:
-- Downloaded boot.img from Lineage OS download page which is provided along the install image lineage-20.0-20230909-nightly-alioth-signed.zip
-- Uploaded it to phone
-- Installed debug version of Magisk
-- used Magisk to create patched boot image
-- Used "fastboot flash boot_a" and "fastboot flash boot_b" to flash the patched image from Lineage recovery

[logcat.log](https://github.com/topjohnwu/Magisk/files/12619499/logcat.log)
[magisk_install_log_2023-09-15T14.18.35.log](https://github.com/topjohnwu/Magisk/files/12619500/magisk_install_log_2023-09-15T14.18.35.log)
[magisk_log_2023-09-15T14.18.48.log](https://github.com/topjohnwu/Magisk/files/12619501/magisk_log_2023-09-15T14.18.48.log)
[mounts_without_magisk.log](https://github.com/topjohnwu/Magisk/files/12619502/mounts_without_magisk.log)

Original boot.img: https://drive.google.com/file/d/1k5TH438ChkshorMPNE53ar8yeYRIt4Lw/view?usp=sharing
Patched image: https://drive.google.com/file/d/1t9fJcGoCG-50GGD8DZZRDSaWZiE1uQfh/view?usp=sharing

Let me know if there is anything else I can check or provide. Thanks.

**Comment by yujincheng08** [comment]
```
02-06 20:47:12.595     0     0 W magiskinit: Load policy from: .magisk/selinux/load
02-06 20:47:12.647     0     0 W magiskinit: target type default_android_hwservice:hwservice_manager does not exist
02-06 20:47:12.647     0     0 W magiskinit: Error in: allow priv_app default_android_hwservice:hwservice_manager find ;
02-06 20:47:12.647     0     0 W magiskinit: target type hal_camerapostproc_xiaomi_hwservice:hwservice_manager does not exist
02-06 20:47:12.647     0     0 W magiskinit: Error in: allow priv_app hal_camerapostproc_xiaomi_hwservice:hwservice_manager find ;
02-06 20:47:12.647     0     0 W magiskinit: target type vendor_file:file does not exist
02-06 20:47:12.647     0     0 W magiskinit: Error in: allow priv_app vendor_file:file read ;
02-06 20:47:12.647     0     0 W magiskinit: Syntax error in ''
```

**Comment by yujincheng08** [comment]
Could you try if https://github.com/topjohnwu/Magisk/actions/runs/5653584168 works?

**Comment by yujincheng08** [comment]
`magiskinit: Load custom sepolicy patch: [/data/.magisk/preinit/ANXVerse/sepolicy.rule]`

module's issue.
