### ISSUE TITLE
Google Pixel 3a / Android 12.1 not booting with patched image

### ISSUE THREAD

**Issue by bilbo2** [topjohnwu/Magisk#7350]
Device:Google Pixel 3a
Android version: 12.1.0 (SP2A.220505.008, Sep 2022) factory image
Magisk version name: d4e552d0
Magisk version code: 26301

The device can boot fine with stock boot.img from "sargo" Pixel 3a factory image, version 12.1.0 (SP2A.220505.008, Sep 2022)

boot.img - https://drive.google.com/file/d/1KvUSn4PGPVZiaRZ0uGjb9kEi7L_j5FuE/view?usp=sharing

However with this image patched using latest debug version of Magisk d4e552d0 (26301), it will not boot (phone stuck on boot logo)
- I uploaded the boot.img to phone, used Magisk 26301 to create patched boot image, downloaded the patched image to PC and flashed it with fastboot

magisk_patched-26301_x2GzJ.img - https://drive.google.com/file/d/1WrQG5KmyuT9HytlGyDf_8ai8gYrxZmWD/view?usp=sharing

I was able to capture logs using 'adb logcat' from the failed boot, showing some crash:

[boot-logcat.log](https://github.com/topjohnwu/Magisk/files/12640334/boot-logcat.log)

Result of `cat /proc/mounts` when booting with working stock image:

[proc_mounts.txt](https://github.com/topjohnwu/Magisk/files/12640337/proc_mounts.txt)

Magisk logs:

[magisk_install_log_2023-09-16T09.36.04.log](https://github.com/topjohnwu/Magisk/files/12640335/magisk_install_log_2023-09-16T09.36.04.log)
[magisk_log_2023-09-16T09.36.21.log](https://github.com/topjohnwu/Magisk/files/12640336/magisk_log_2023-09-16T09.36.21.log)

I tried also older magisk versions 25206,26100,26300 with same results (stuck on boot), so apparently not a recent regression.
Let me know if there is anything else I can check or provide. Thanks.

**Comment by yujincheng08** [comment]
#08 pc 000000000000c302  [anon:dalvik-DEX data] (com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook+162)
