### ISSUE TITLE
Magisk not active if patched with release build(s) after "Add more to the Utf8CStr family".

### ISSUE THREAD

**Issue by ipdev99** [topjohnwu/Magisk#7356]
Hi.

I run personal build(s) of Magisk from the official repo (not a fork) so, the newest commits are always included.
I run new builds when I get home from work if there is a new commit.
_[ I understand that they are not supported because the commit(s) are (sometimes) still a work in progress. ]_

Long story short.

Last week, I updated using the "Direct Install" option from "4eaf701cb" to "4745e86c1" and lost root on reboot.
I went back to "4eaf701cb" for the night.

The next night, I installed the debug version on a different device to grab logs but, it worked?
So I tried the release build and once again, Magisk was not active after boot.

Tried on a few more devices.
Same story, the debug build(s) worked but the release build(s) did not.

This morning, I went backwards though the commits (using git bisect) to find when the release build(s) started to fail.
"Add more to the Utf8CStr family" 89aee6ffa was it.

Patched with release build.

```
oriole:/ $ magisk -V
/system/bin/sh: magisk: inaccessible or not found
```

Patched with debug build.
```
oriole:/ $ magisk -V
26301
oriole:/ $ magisk -v
89aee6ffa-ip:MAGISK:D
```

---

Device: Multiple
Android version: Multiple
Magisk version name: 89aee6ffa -> 877aeb66c
Magisk version code: 26301

Install log(s) look normal. (?)
_From Pixel 6 - Stock Android 13 (20230705)._
[P6 Debug install log](https://github.com/topjohnwu/Magisk/files/12643533/magisk_install_log_89aee6ffa-d.log)
[P6 Release install log](https://github.com/topjohnwu/Magisk/files/12643534/magisk_install_log_89aee6ffa-r.log)
[P6 Debug patched image](https://github.com/topjohnwu/Magisk/files/12643538/magisk_patched-89aee6ffa_debug.zip)
[P6 Release patched image](https://github.com/topjohnwu/Magisk/files/12643540/magisk_patched-89aee6ffa_release.zip)

**Comment by yujincheng08** [comment]
need bugreport

**Comment by canyie** [comment]
The signal that causes daemon to exit is SIGTRAP
![image](https://github.com/topjohnwu/Magisk/assets/31466456/bce59519-ff86-4ea6-8970-7fbc2b94c32b)
