### ISSUE TITLE
Magisk Build issues on Windows 11

### ISSUE THREAD

**Issue by Jyotidwi** [topjohnwu/Magisk#7370]
Hi

I am building the Magisk repository on Windows 11 (built from scratch) and I have followed the instructions on (https://github.com/topjohnwu/Magisk)

git clone the repository
Install Android Studio-2022.3.1.19
Install Python 3.8
Install JDK 17.0.8
setup environment variables properly
python build.py ndk
and then python build.py -vr binary

##
C:\Magisk>python build.py -vr binary

* Building binaries: magisk magiskinit magiskboot magiskpolicy busybox

    Finished release [optimized] target(s) in 19.78s
mv target\thumbv7neon-linux-androideabi\release\libmagiskpolicy.a -> ..\out\armeabi-v7a\libmagiskpolicy-rs.a
mv target\thumbv7neon-linux-androideabi\release\libmagisk.a -> ..\out\armeabi-v7a\libmagisk-rs.a
mv target\thumbv7neon-linux-androideabi\release\libmagiskboot.a -> ..\out\armeabi-v7a\libmagiskboot-rs.a
mv target\thumbv7neon-linux-androideabi\release\libmagiskinit.a -> ..\out\armeabi-v7a\libmagiskinit-rs.a
    Finished release [optimized] target(s) in 4.59s
mv target\i686-linux-android\release\libmagiskpolicy.a -> ..\out\x86\libmagiskpolicy-rs.a
mv target\i686-linux-android\release\libmagisk.a -> ..\out\x86\libmagisk-rs.a
mv target\i686-linux-android\release\libmagiskboot.a -> ..\out\x86\libmagiskboot-rs.a
mv target\i686-linux-android\release\libmagiskinit.a -> ..\out\x86\libmagiskinit-rs.a
    Finished release [optimized] target(s) in 3.71s
mv target\aarch64-linux-android\release\libmagiskpolicy.a -> ..\out\arm64-v8a\libmagiskpolicy-rs.a
mv target\aarch64-linux-android\release\libmagisk.a -> ..\out\arm64-v8a\libmagisk-rs.a
mv target\aarch64-linux-android\release\libmagiskboot.a -> ..\out\arm64-v8a\libmagiskboot-rs.a
mv target\aarch64-linux-android\release\libmagiskinit.a -> ..\out\arm64-v8a\libmagiskinit-rs.a
    Finished release [optimized] target(s) in 9.08s
mv target\x86_64-linux-android\release\libmagiskpolicy.a -> ..\out\x86_64\libmagiskpolicy-rs.a
mv target\x86_64-linux-android\release\libmagisk.a -> ..\out\x86_64\libmagisk-rs.a
mv target\x86_64-linux-android\release\libmagiskboot.a -> ..\out\x86_64\libmagiskboot-rs.a
mv target\x86_64-linux-android\release\libmagiskinit.a -> ..\out\x86_64\libmagiskinit-rs.a
Android NDK: WARNING: Building static executable but APP_PLATFORM android-23 is not the latest API level android-34. Build may not succeed.
Android NDK: WARNING: Building static executable but APP_PLATFORM android-23 is not the latest API level android-34. Build may not succeed.
Android NDK: WARNING: Building static executable but APP_PLATFORM android-23 is not the latest API level android-34. Build may not succeed.
Android NDK: WARNING: Building static executable but APP_PLATFORM android-23 is not the latest API level android-34. Build may not succeed.
[arm64-v8a] Install        : libinit-ld.so => libs/arm64-v8a/libinit-ld.so
[armeabi-v7a] Install        : libzygisk-ld.so => libs/armeabi-v7a/libzygisk-ld.so
[arm64-v8a] Install        : magiskpolicy => libs/arm64-v8a/magiskpolicy
[arm64-v8a] Install        : libzygisk-ld.so => libs/arm64-v8a/libzygisk-ld.so
[arm64-v8a] Install        : magiskboot => libs/arm64-v8a/magiskboot
[x86] SharedLibrary  : libinit-ld.so
ld.lld: error: undefined symbol: _GLOBAL_OFFSET_TABLE_
>>> referenced by preload.c:9 (src/init/preload.c:9)
>>>               lto.tmp:(preload_init)
>>> referenced by preload.c:13 (src/init/preload.c:13)
>>>               lto.tmp:(security_load_policy)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [C:/Users/NND/AppData/Local/Android/sdk/ndk/magisk/build/../build/core/build-binary.mk:654: obj/local/x86/libinit-ld.so] Error 1
make: *** Waiting for unfinished jobs....
[x86] Executable     : magiskboot
ld.lld: error: cannot find entry symbol _start; not setting start address
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [C:/Users/NND/AppData/Local/Android/sdk/ndk/magisk/build/../build/core/build-binary.mk:667: obj/local/x86/magiskboot] Error 1
[armeabi-v7a] Executable     : magiskboot
ld.lld: error: cannot find entry symbol _start; not setting start address
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [C:/Users/NND/AppData/Local/Android/sdk/ndk/magisk/build/../build/core/build-binary.mk:667: obj/local/armeabi-v7a/magiskboot] Error 1
[armeabi-v7a] Executable     : magiskpolicy
ld.lld: error: cannot find entry symbol _start; not setting start address
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [C:/Users/NND/AppData/Local/Android/sdk/ndk/magisk/build/../build/core/build-binary.mk:667: obj/local/armeabi-v7a/magiskpolicy] Error 1

! Build binary failed!

##

Are there any other settings I need to configure?

OS: Windows 11
Magisk version code: 26301

magisk.stubVersion=37
magisk.versionCode=26301
magisk.ondkVersion=r26.0

**Comment by vvb2060** [comment]
Each commit will test build on 3 platforms.
for Windows https://github.com/topjohnwu/Magisk/actions/runs/6238376011/job/16934090307
