### ISSUE TITLE
userdata img missing from magisk patched tar

### ISSUE THREAD

**Issue by drandrew1983** [topjohnwu/Magisk#7376]
Device: Samsung Galaxy Tab S7+
Android version: 13
Magisk version name: d4e552d0
Magisk version code: 26301 D

On trying to Patch AP.tar file by select and patch file in magisk, the produced patched image is smaller in size with about 1 GB. for some reason after updating magisk to the latest version, the produced magisk patched AP.tar image doesn't contain userdata.img.lz4

please fix

[magisk_log_2023-09-22T18.58.27.log](https://github.com/topjohnwu/Magisk/files/12703062/magisk_log_2023-09-22T18.58.27.log)
![Magisk patched](https://github.com/topjohnwu/Magisk/assets/33606175/a38eca99-2e2a-4030-9090-1b55f9b0fb6b)
![Original](https://github.com/topjohnwu/Magisk/assets/33606175/463221e2-2263-4e62-92d3-7f93fadbffd6)

**Comment by yujincheng08** [comment]
#7129
