### ISSUE TITLE
UI bug/suggestion:  denylist - default deny, bulk edit

### ISSUE THREAD

**Issue by alextmz** [topjohnwu/Magisk#7378]
Maybe not a huge one, but this feels like a UI bug simple to fix.

- Below "Enforce Denylist", add another toggle called "Deny by default" which would deny for any new application.
- On "Configure Denylist", add a "check all" capability.

I'm not sure if there's any downside on denying to all by default, but would like to know.

On the configure denylist, more complex filters would be useful, but also more development: "check only user apps", "Invert check toggle", and maybe a blacklist/whitelist and a backup/restore deny checks from text file. Awesome but luxuries really.

The first 2 items would save a lot of time for a lot of people with problematic applications and/or people that want to "deny all by default" and then open only as necessary. It's just a best practice from a security view.

Curious to know your take on it.

And thanks **a lot** for the absolutely awesome project. Magisk is a very very nice piece of software.

Device: Pixel XL
Android version: 11
Magisk version name: 26.3 (Debug)
Magisk version code: 26301

**Comment by CasperVerswijvelt** [comment]
I also feel that denying by default is a good idea. Most applications on a users device do not require root and some stop working at all when they detect root. In my eyes it makes more sense to change the behaviour to fit the majority of the apps on the phone.

Remembering to put an app in the denylist after installing it and before opening it is something that can be quickly forgotten. When that app then detects root the user needs to add to denylist and clear app data in an attempt to make the app functional, which is a bit of a hassle that could be avoided.

**Comment by sidneydemoraes** [comment]
+1 for this one. I was actually looking for a way to do that when I found this request.

**Comment by iamashwin99** [comment]
+1, not sure why this was closed, could we reopen?
