### ISSUE TITLE
Hide installed apps with Magisk Hide

### ISSUE THREAD

**Issue by Uumas** [topjohnwu/Magisk#739]
Some apps (like https://play.google.com/store/apps/details?id=fi.op.android.lompsa) detect installed apps like Titanium Backup and DriveDroid and refuse to work if they are installed. Could Magisk Hide also hide installed app list for the apps selected.

**Comment by vvb2060** [comment]
https://topjohnwu.github.io/Magisk/tutorials.html#best-practices-for-magiskhide
Just uninstalling them, Magisk can't do this.

**Comment by Uumas** [comment]
Is there some technical limitation making this impossible or is it just more work than it's worth?
I think there was (is?) an Xposed module (xPrivacy?) that can do this.
Also, another option would be to change the package name of the app like Magisk Manager does to itself.

**Comment by topjohnwu** [comment]
It is not possible (or practical) for a general solution, even if using modified system frameworks or Xposed to modify the framework to report filtered package lists. An app can simply check the existence of the folder `/data/data/<pkg_name>` (which is used by apps like FGO), and it will know whether the package is installed.

To mitigate that, you have to hijack `libc.so` to change the behavior of the super basic core functions to prevent detecting the existence of the folder/files completely natively. I do not have the proper knowledge or ability to do that.
