### ISSUE TITLE
[QUESTION] Magisk symlinks compatibility with Linux partitions types

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#740]
Hello @topjohnwu 
As Magisk works with symlinks, if a user have an EXT4 or EXT3 partition for is system, does Magisk will not be compatible or do u use a workarround ?

Thanks in advance

**Comment by topjohnwu** [comment]
Both EXT4 and EXT3 supports symlinks.

**Comment by xerta555** [comment]
> Both EXT4 and EXT3 supports symlinks.

And do u use a workaround with FAT32 has it don't support symlinks ?

**Comment by topjohnwu** [comment]
Systems and data will not be formatted with FAT32.
Magisk does not support magic mounting internal storage/external storage, so I don't know what you are aiming for.
