### ISSUE TITLE
Release build(s) broken after "Move more I/O operations into Rust"

### ISSUE THREAD

**Issue by ipdev99** [topjohnwu/Magisk#7408]
Release build(s) are broken starting with "Move more I/O operations into Rust" a55d570.

The release build patched images boot but, Magisk is not active.
Save for my Nexus 5, magisk is active but somewhat broken.

Nexus 5 Lineage 14.1 (Android v7.x).
Using the release build(s), magisk is active on boot but, gives the "Requires Additional Setup" dialog box.
_Even after selecting "OK" and the device reboots, the dialog box shows every time the app is opened._

---

The debug build(s) work as expected.

---

Device: Multiple
Android version: Multiple
Magisk version name: a55d57021 -> 6076b52c4
Magisk version code: 26301

Logs and stuff:
PocoF1 | MIUI Global 12.0.3 (Android 10).
[f1-boot_patched-a55d57021_R.zip](https://github.com/topjohnwu/Magisk/files/12841567/f1-boot_patched-a55d57021_R.zip)
[f1_magisk_first_boot.log](https://github.com/topjohnwu/Magisk/files/12841568/f1_magisk_first_boot.log)
[f1_magisk_install.log](https://github.com/topjohnwu/Magisk/files/12841569/f1_magisk_install.log)

Nexus 5 | Lineage 14.1 (Android 7.1.2).
[n5-boot_patched-a55d57021_R.zip](https://github.com/topjohnwu/Magisk/files/12841570/n5-boot_patched-a55d57021_R.zip)
[n5_magisk_first_boot.log](https://github.com/topjohnwu/Magisk/files/12841571/n5_magisk_first_boot.log)
[n5_magisk_install.log](https://github.com/topjohnwu/Magisk/files/12841572/n5_magisk_install.log)
[bugreport-NJH47F-2023-10-08-13-21-30.zip](https://github.com/topjohnwu/Magisk/files/12841582/bugreport-NJH47F-2023-10-08-13-21-30.zip)

Pixel 7 | Stock 20231005 (Android 14).
[p7-init_boot_patched-a55d57021_R.zip](https://github.com/topjohnwu/Magisk/files/12841573/p7-init_boot_patched-a55d57021_R.zip)
[p7_magisk_first_boot.log](https://github.com/topjohnwu/Magisk/files/12841574/p7_magisk_first_boot.log)
[p7_magisk_install.log](https://github.com/topjohnwu/Magisk/files/12841575/p7_magisk_install.log)
[bugreport-panther-UP1A.231005.007-2023-10-08-14-00-45.zip](https://github.com/topjohnwu/Magisk/files/12841584/bugreport-panther-UP1A.231005.007-2023-10-08-14-00-45.zip)

**Comment by vvb2060** [comment]
This is a known issue and build HEAD code is unsupported.
