### ISSUE TITLE
Build success but magisk and magiskinit size bigger than normal.

### ISSUE THREAD

**Issue by seci20** [topjohnwu/Magisk#7422]
i am builded source. Its compile success but device bootlop issue. And magiskinit bigger than original
![image](https://github.com/topjohnwu/Magisk/assets/13988176/33944edd-9d6c-4475-87c5-83d8c92538dd)

Device: Volla Phone 22
Android version: 12
Magisk version name: 26.3
Magisk version code: 26301

**Comment by yujincheng08** [comment]
expected. and magiskinit will be stripped when packing into apk.
