### ISSUE TITLE
OnePlus OOS10 reboot in recovery after some seconds

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#7425]
Hi

There are basic infos:

Device: OnePlus Nord N10 5G
Android version: 10
Magisk version name: 26.3
Magisk version code: 26301
ROM type: stock OOS rooted with Magisk

Since the publication of the second canary version following the publication of version v26.3, i have had the following problem:

I just test all stable/beta/canary/debug version >26.1, and after seconds during device start, my homescreen appear, and arround 4-5 seconds after, my device display the shutdown animation and just reboot in recovery mode.

I have to flash again Magisk v26.1 as zip file to be able to boot again propeply, install again v26.1 apk and flash again the v26.1 version with direct install method to be able to boot my device correctly.

No new Magisk/Xposed module added from i have this bug, so theoricaly the bug shouldn't come from what i use.

There is the logfile of the flash of v26.3 (beta channel): [magisk_install_log_2023-10-14T18.02.40.log](https://github.com/topjohnwu/Magisk/files/12906661/magisk_install_log_2023-10-14T18.02.40.log)

There are logfile from boot device stage (adb startup during bootanimation start) to the shutdown popup:
[dmesg.log](https://github.com/topjohnwu/Magisk/files/12887490/dmesg.log)
[logcat.txt](https://github.com/topjohnwu/Magisk/files/12906848/logcat.txt)

Hope theses two logfiles will be sufficient to know what happen on my side.

EDIT: logcat file updated with 26301 last debug version installed.

Thanks for support.

**Comment by xerta555** [comment]
@yujincheng08 Why did you close the thread?
Can you at least tell why?

**Comment by yujincheng08** [comment]
https://github.com/topjohnwu/Magisk/blob/36de62873a0c3b1fbd37f6baa6d4feab0784a436/.github/ISSUE_TEMPLATE/bug_report.md#L27-L27

**Comment by xerta555** [comment]
> https://github.com/topjohnwu/Magisk/blob/36de62873a0c3b1fbd37f6baa6d4feab0784a436/.github/ISSUE_TEMPLATE/bug_report.md#L27-L27

Fixed on my side.
Was due to a specific Magisk module
Sorry for the inconvenience.
