### ISSUE TITLE
Pixel 2XL Freezing with latest Magisk 

### ISSUE THREAD

**Issue by cjrivera04** [topjohnwu/Magisk#743]
I've noticed on my pixel 2 xl, when powered off and trying to charge, the phone gets stuck on the battery animation. The only way to power the phone is by a hard reboot. I've looked through the forums and it seems to be a problem for many pixel 2 xl owners. I'm not sure how to get a log for this either. I've asked others on XDA if they were able to get a log but I've had no luck. This was not a problem for Magisk 16.3 and lower. Just reporting the bug and I apologize for not getting an appropriate log.

**Comment by topjohnwu** [comment]
Have you tried the canary channel? I was told it was fixed.

**Comment by cjrivera04** [comment]
I did and I'm still experiencing the issue.

**Comment by jasoriab** [comment]
Hi,
Tested last canary version 17.4-411ea56a and have exactlly the same problem with my Pixel 2 XL (stock rom and kernel - Oct 2018)

**Comment by jasoriab** [comment]
Pixel 2 XL - Problem solved with the November update of Google - 9.0.0 (PQ1A.181105.017.A1, Nov 2018)
Even with the stable version 17.1, it is possible now charge the phone when is powered off.

**Comment by cjrivera04** [comment]
Thanks!!!

Chris
