### ISSUE TITLE
Bricked when tried "Reboot to Recovery"

### ISSUE THREAD

**Issue by arkzok** [topjohnwu/Magisk#7430]
When I pressed "Reboot to Recovery", my phone powered off. Nothing was happening. I tried to turn it back on by simply holding the power button - nothing. Power button + vol- -> nothing. Power button + vol+ -> Orange State: your device will boot in five seconds. Five seconds pass -> it powers off again. I tried to connect it to my computer, it's not in fastboot, it's actually powered off. Tried connecting while in Orange State -> still nothing. Also tried to hold vol- and vol+ buttons while connecting it to my computer, and I actually got "OPLUS preloader connected" notifcation, but then it disconnected and could never connect this way again.

Device: realme GT Neo 3 150W
Android version: 13
Magisk version name: 26.3
Magisk version code: 26301

**Comment by Lishoo** [comment]
Try to power it on with "Power button and the vol-" after Realme shows release the "vol-" button but hold still the Power button.

**Comment by kyrenlee** [comment]
hold still hold~

**Comment by Uggh66xx** [comment]
bootloop/card logo/startup micro-label

When the device updates Magisk version or patches boot.img or Magisk Modules. Causing this deadlock situation...

We need Magisk to add a fully automatic protection mode: when an abnormality is detected and the phone or emulator cannot be turned on. Automatically activate "Safe Mode" within 5 minutes
》》Most modern Android devices support pressing a special key combo at boot to enter Safe Mode as an emergency option. Magisk will detect Safe Mode being activated, and all modules will be disabled. Then reboot back to normal mode (the module disable state persists ) and manage your modules through the Magisk app.
https://topjohnwu.github.io/Magisk/faq.html

Why is this needed? Some Android devices cannot enter safe mode through special keys when they are not powered on at all.
![Screenshot_20231014-210021-1](https://github.com/topjohnwu/Magisk/assets/147297639/a05a1bab-0f4a-404b-b8ea-3720ae3eec3d)

**Comment by vvb2060** [comment]
Contact customer service, not us.

**Comment by arkzok** [comment]
Yeah, when was submitting the issue, I was kinda in panic and wrote wherever I could: XDA, 4PDA, here. But I now understand that this doesn't belong here, considering also that I already found a fix on XDA.

**Comment by JosVel2022** [comment]
> Yeah, when was submitting the issue, I was kinda in panic and wrote wherever I could: XDA, 4PDA, here. But I now understand that this doesn't belong here, considering also that I already found a fix on XDA.

Hi, how u could repair your device?
