### ISSUE TITLE
After update , SoundAssistant on Samsung not working properly and lsposed too

### ISSUE THREAD

**Issue by LUCID-DREE** [topjohnwu/Magisk#7453]
Device: Samsung A920F DS
Android version: ANDROID 10
Magisk version name:0352ea2c
Magisk version code:26302

After updating to this magisk version, and rebooting , phone showed just black screen . Then on long pressing power button it showed me power off and restart red and green icons on pitch black background which meant the phone booted but only black output on screen. Also strange pixeled lines appeared on my screen and becoming solid . After experimenting I found that with this new magisk, i can't avoid the Black screen and the screen vertical pixelated lines until I uninstall the zygisk lsposed module . I did and it got fixed and I saw lock screen asking for pasword as first thing on booting up. So now I can't use lsposed magisk module until further magisk bug update. After booting up I noticed that my volume control apps like Sound Assistant app by goodlocks on Samsung Galaxy Store stopped showing the customised Sero themed volume ui even though turned on, many widgets from Samsung one UI homescreen vanished which I had to bring back on my weak memory . So I installed the official Good Locks Lab app from galaxy store which reported that something was wrong with the configuration of this device which has been corrected to allow sound assistant to again work.After this correction message I reopened sound assistant app and now it was fixed and  showed back the customised Sero volume ui. But I still can't use zygisk lsposed. 
Something in this new version of Magisk manhandled the critical system files and so all this happened . I fixed most issues for the time being currently individually one at a time but lsposed zygisk version module is still not working. So please correct this magisk version so that lsposed zygisk can work again .Also flashlight is sometimes working and sometimes not on rooting with magisk and this is a very old issue which I reported but no one fixed.
Ask me anything you want.

Thank you 🙏🏿

**Comment by canyie** [comment]
You didn't provide any log, so no one can know what's happened to your phone, but according to your symptoms I think your problem it's likely to be the same as #7448. Close as a duplicate issue.
