### ISSUE TITLE
Magisk error log

### ISSUE THREAD

**Issue by mscalindt** [topjohnwu/Magisk#748]
Latest canary and normal builds have the attached error when flashing Magisk. I don't know if it's related, but I have SafetyNet API Error, so I looked through the log and found this error.

[magisk_log_20181031_014821.log](https://github.com/topjohnwu/Magisk/files/2532076/magisk_log_20181031_014821.log)

**Comment by topjohnwu** [comment]
The SafetyNet extension is working properly. Try clear the data of Magisk Manager to see if that fixes the issue. Also, do not use unofficial builds (if you are using one)

**Comment by mscalindt** [comment]
I already did that... I'm not using unofficial builds too.

**Comment by mscalindt** [comment]
The issue for SafetyNet API Error was caused because of outdated GMS.

**Comment by topjohnwu** [comment]
Then you know what to do: upgrade Google Play Service.
