### ISSUE TITLE
SystemUI does not work with Zygisk enabled

### ISSUE THREAD

**Issue by ubergeek77** [topjohnwu/Magisk#7489]
Device: Pixel 8 Pro
Android version: Android 14 (GrapheneOS)
Magisk version name: 26.4
Magisk version code: 26401 (aa6c7c15) (D)

---

I first reported this on a similar issue that has since been closed:

https://github.com/topjohnwu/Magisk/issues/7448#issuecomment-1784467986

I also reported that a certain build of Magisk with Zygisk improvements does not experience this issue:

https://github.com/topjohnwu/Magisk/issues/7448#issuecomment-1789929581

---

When Zygisk is enabled, SystemUI does not work properly. The system boots to the launcher, and apps can be opened and used, but the following elements are not loaded and therefore do not function:

- **System navigation** - the navigation bar does not show, regardless of if "3-button" or "gesture" navigation is used. Any kind of navigation, including gestures, is not possible. The user cannot go "back," "home," and the "recents" screen is not accessible.
- **Notification bar** - the notification bar is not visible, and the pull-down gesture to access quick settings does not function.
- **Power menu** - the standard power menu is not present. The system falls back to the safe mode power menu.
- **Lock screen** - the screen will simply turn off when the power button is tapped. If the power button is tapped again, the phone will resume in whatever app it was in, but without displaying the lock screen.

This issue occurs in both 26.3 and 26.4, the latter of which had some improvements to FD sanitization. This occurs **only with Zygisk enabled.** The broken SystemUI elements work again if Zygisk is disabled.

This issue ***does not occur*** on this build which appears to change the way Zygisk is injected:

https://github.com/topjohnwu/Magisk/actions/runs/6767188369

On this build, Zygisk works properly, and can be enabled safely without breaking SystemUI.

---

Boot logcat:
[boot-logcat.log](https://github.com/topjohnwu/Magisk/files/13290965/boot-logcat.log)

Magisk log:
[magisk_log_2023-11-07T19.12.26.log](https://github.com/topjohnwu/Magisk/files/13290948/magisk_log_2023-11-07T19.12.26.log)

**Comment by osm0sis** [comment]
Interesting I don't have this issue on Pixel 8 Pro stock.

**Comment by Unknown78** [comment]
I have similar issue on https://github.com/topjohnwu/Magisk/issues/7472#issuecomment-1800842969, I could boot, but my screen is black. I couldn't open Magisk to check whether Zygisk is successfully enabled or not.

**Comment by ubergeek77** [comment]
I doubt that is related, as your issue is happening on Android 7, which is quite old.

Try the build I linked and see if it helps?

**Comment by Unknown78** [comment]
Thanks for your suggestion, I've tried it. But it still the same, black screen.

**Comment by canyie** [comment]
The fix 9fbd079 has been merged into master branch

**Comment by pixincreate** [comment]
Cool, I was able to boot my pixel with [this](https://github.com/topjohnwu/Magisk/actions/runs/7078101816)(latest one) CI build except Zygisk (it never turns on) of course:
```
12-03 23:56:51.158   899   899 E : zygisk64: unknown signature of nativeForkAndSpecialize(II[II[[IILjava/lang/String;Ljava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZ[J)I
12-03 23:56:51.158   899   899 E : zygisk64: unknown signature of nativeSpecializeAppProcess(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZ[J)V
12-03 23:56:51.158   899   899 I : zygisk64: replace nativeForkSystemServer
12-03 23:56:51.621   900   900 E : zygisk32: unknown signature of nativeForkAndSpecialize(II[II[[IILjava/lang/String;Ljava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZ[J)I
12-03 23:56:51.621   900   900 E : zygisk32: unknown signature of nativeSpecializeAppProcess(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZ[J)V
```

**Comment by pixincreate** [comment]
Zygisk here is invasive from what I can see at this point.

**Comment by chenxiaolong** [comment]
> Cool, I was able to boot my pixel with [this](https://github.com/topjohnwu/Magisk/actions/runs/7078101816)(latest one) CI build except Zygisk (it never turns on) of course:
> 
> ```
> 12-03 23:56:51.158   899   899 E : zygisk64: unknown signature of nativeForkAndSpecialize(II[II[[IILjava/lang/String;Ljava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZ[J)I
> 12-03 23:56:51.158   899   899 E : zygisk64: unknown signature of nativeSpecializeAppProcess(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZ[J)V
> 12-03 23:56:51.158   899   899 I : zygisk64: replace nativeForkSystemServer
> 12-03 23:56:51.621   900   900 E : zygisk32: unknown signature of nativeForkAndSpecialize(II[II[[IILjava/lang/String;Ljava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZ[J)I
> 12-03 23:56:51.621   900   900 E : zygisk32: unknown signature of nativeSpecializeAppProcess(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZ[J)V
> ```

That specific issue is due to https://github.com/GrapheneOS/platform_frameworks_base/commit/b45048f74f912dbd4807adb53d9d261b1b413843.

**Comment by pixincreate** [comment]
So, they've added an extra field which takes in `null` value and in future, it will made to take `user_id`  if what I read is right...
