### ISSUE TITLE
[Feature Request]: Modules categories

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#749]
This idea came to my mind after the huge flood of different fonts came recently in the repo.
And this is only gonna get worse as more modules will be added.

It would be nice if categories were implemented based on tags (inside module props) so the modules can be somehow shorted (or excluded) inside MagiskManager. 

Like "Fonts", "Apps", "Utilities", "Hosts", "Region Oriented" etc etc.

**Comment by skittles9823** [comment]
The repo moderation team is also behind this idea (we were thinking about it when we were first brainstorming rules for the repo) although in my opinion i don't think the tag should be based in the module.prop as it would be better in my opinion to have an XML file that works similar to how the substratum themes showcase works where once a module gets accepted, the accepting moderator will go and fill out the XML according to the category the module fits in.

**Comment by DenyDarko** [comment]
Hmm, you're right, I didn't thought of the moderating parameter.

It's better for categories to be controlled by mods, yeah :)
