### ISSUE TITLE
JNI FatalError set_sched_policy(0, SP_DEFAULT) failed

### ISSUE THREAD

**Issue by Unknown78** [topjohnwu/Magisk#7493]
Device: Samsung Galaxy Note 4 SM-N910H
Android version: 7.1.1 Nougat (API 25), Custom ROM of [REFINED_NOTE8_7.1_T2.zip](https://t.me/RefinedNougat/491) and [Konup_RisingNote4_for_RefinedNote8_7.1.1_ver.2.3.zip](https://xdaforums.com/t/refined-note-8-7-1-1-exynos-updated-mod-risingnote4-ver-2-3.4363583/) and also Custom Kernel of [Helios_Kernel-V3.1-N910C.H-20200809.img](https://t.me/RefinedNougat/493)
Magisk version name: debug
Magisk version code: 26401

 I can boot and adb logcat, but my screen is black. The charging is working, the light of the back and menu button is okay, but I couldn't do anything. 

[logcat_log_2023-11-08T07.46.00.log](https://github.com/topjohnwu/Magisk/files/13291731/logcat_log_2023-11-08T07.46.00.log)

There's hundreds of this error  in the logcat,
```
art/runtime/jni_internal.cc:492] JNI FatalError called: frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:299: set_sched_policy(0, SP_DEFAULT) failed
```

<hr>

I've tried the build of https://github.com/topjohnwu/Magisk/actions/runs/6767188369 as per https://github.com/topjohnwu/Magisk/issues/7489#issuecomment-1800897677 suggestion, but it still gave me the black screen.
[logcat_log_2023-11-08T09.47.52.log](https://github.com/topjohnwu/Magisk/files/13291733/logcat_log_2023-11-08T09.47.52.log)

<hr>

I've also tried the build of #7487 as per https://github.com/topjohnwu/Magisk/issues/7472#issuecomment-1800942157 suggestion, but it still the same.
[logcat_log_2023-11-08T10.20.48.log](https://github.com/topjohnwu/Magisk/files/13291736/logcat_log_2023-11-08T10.20.48.log)

<hr>

P.S. If I try the debug 26401 app with debug 26301 patched kernel, the problem is gone.

**Comment by Unknown78** [comment]
Okay so this is a really weird one.

I've just try again the build of  https://github.com/topjohnwu/Magisk/pull/7487 as per https://github.com/topjohnwu/Magisk/issues/7472#issuecomment-1800942157 suggestion.

But one thing that is differs, instead of updating it from previous patched kernel of `26301 or 26302`, From [TWRP-3.7.0_9-treltexx-20221231.tar](https://xdaforums.com/t/exynos-galaxynote4-n910c-u-h-s-l-k-twrp-3-7-0_9-galaxy-note-4-custom-recovery-07-28-2021.4311777/), I flash the unpatched custom kernel/boot partition of [Helios_Kernel-V3.1-N910C.H-20200809.img](https://t.me/RefinedNougat/493). And then rename the `app-debug.apk` to `apk-debug.zip`, and then flash it straight from the recovery.

The system is boot fine, no black screen, here is the logs.
[logcat_log_2023-11-08T12.14.29.log](https://github.com/topjohnwu/Magisk/files/13292477/logcat_log_2023-11-08T12.14.29.log)
[magisk_log_2023-11-08T12.21.17.log](https://github.com/topjohnwu/Magisk/files/13292502/magisk_log_2023-11-08T12.21.17.log)

And here is the problem, 
![Screenshot_08 11 23_12 18 41](https://github.com/topjohnwu/Magisk/assets/25132599/c780dd4a-34b1-4006-acef-177d04d8e2df)

Whenever I open the app if I flash from recovery instead of from the Magisk app, I will be prompted to reinstall it again directly within the app. So I did that, and it causes blank unresponsive screen again. There is hundreds of `JNI FatalError` again in the logcat.
[logcat_log_2023-11-08T12.29.53.log](https://github.com/topjohnwu/Magisk/files/13292563/logcat_log_2023-11-08T12.29.53.log)

**Comment by canyie** [comment]
A huge refactor has been merged, can you test if this build works? https://github.com/topjohnwu/Magisk/actions/runs/6795685152

**Comment by Unknown78** [comment]
@canyie everything is working fine, good job!
[logcat_log_2023-11-08T19.14.57.log](https://github.com/topjohnwu/Magisk/files/13296555/logcat_log_2023-11-08T19.14.57.log)
[magisk_log_2023-11-08T19.22.09.log](https://github.com/topjohnwu/Magisk/files/13296625/magisk_log_2023-11-08T19.22.09.log)
