### ISSUE TITLE
Zygote crashes

### ISSUE THREAD

**Issue by RV7PR** [topjohnwu/Magisk#7496]
Device: Samsung Galaxy S23 Plus (SM-S916B)
Android version: 14
Magisk version name: ecb31ee (last commit)
Magisk version code: 26401

For example when opening an email from outlook the body wont load and i get a zygote crash

[magisk_log_2023-11-08T19.57.13.log](https://github.com/topjohnwu/Magisk/files/13300338/magisk_log_2023-11-08T19.57.13.log)

[crash-com-android-chrome_zygote-08_11-19-43-49_560.zip](https://github.com/topjohnwu/Magisk/files/13300372/crash-com-android-chrome_zygote-08_11-19-43-49_560.zip)
[crash-com-microsoft-emmx_zygote-08_11-19-51-14_276.zip](https://github.com/topjohnwu/Magisk/files/13300373/crash-com-microsoft-emmx_zygote-08_11-19-51-14_276.zip)
[crash-webview_zygote-08_11-19-57-14_420.zip](https://github.com/topjohnwu/Magisk/files/13300374/crash-webview_zygote-08_11-19-57-14_420.zip)

**Comment by RV7PR** [comment]
[crash-zygote64-09_11-00-23-17_311.zip](https://github.com/topjohnwu/Magisk/files/13302252/crash-zygote64-09_11-00-23-17_311.zip)

**Comment by Unknown78** [comment]
As per https://github.com/topjohnwu/Magisk/issues/7493#issuecomment-1801720612, maybe it could solve your problem.
> A huge refactor has been merged, can you test if this build works? https://github.com/topjohnwu/Magisk/actions/runs/6795685152

**Comment by RV7PR** [comment]
> As per [#7493 (comment)](https://github.com/topjohnwu/Magisk/issues/7493#issuecomment-1801720612), maybe it could solve your problem.
> 
> > A huge refactor has been merged, can you test if this build works? https://github.com/topjohnwu/Magisk/actions/runs/6795685152

I'm already using the latest build

**Comment by RV7PR** [comment]
No more crashes with  977c981

**Comment by RV7PR** [comment]
@Sadboy3ZR4 you should make a new issue and upload the magisk log using the debug build
