### ISSUE TITLE
Zygisk causes blank screen after upgrading to Magisk 26.4

### ISSUE THREAD

**Issue by shezik** [topjohnwu/Magisk#7507]
Device: Blackshark 4S (SHARK PRS-A0)
Android version: 11 (JOYUI 12.8 22.03.05 based on MIUI 12.5)
Magisk version name: aa6c7c15 (D)
Magisk version code: 26401

My phone boots to blank screen after boot animation finishes. Charging animation still plays normally but the last frame will stay on the screen. This occurred when I upgraded Magisk from 26.3 to 26.4 two days ago. I tried disabling all modules, upgrading to the latest canary debug build (aa6c7c15) but none helped.

The logcat log file attached below indicates something is wrong with Zygote (<tt>Abort message: 'JNI FatalError called: (zygote) Failed dup3() on descriptor 5: Invalid argument'</tt>). Turning Zygisk off by executing <tt>magisk --sqlite "UPDATE settings SET value = 0 WHERE key = 'zygisk'"</tt> as root in ADB shell fixes this blank screen issue but no Zygisk anymore :(

The following log files were retrieved with all modules disabled.

[boot_logcat_with_zygisk.txt](https://github.com/topjohnwu/Magisk/files/13328102/boot_logcat_with_zygisk.txt)
[magisk.log](https://github.com/topjohnwu/Magisk/files/13328104/magisk.log)

**Comment by Unknown78** [comment]
Try the latest build and see whether it'll solve your problem or not.
https://github.com/topjohnwu/Magisk/actions/workflows/build.yml

**Comment by shezik** [comment]
> Try the latest build and see whether it'll solve your problem or not. https://github.com/topjohnwu/Magisk/actions/workflows/build.yml

Thank you! It solves the issue perfectly, even though applying core patch was required (the apk signature is different).

**Comment by Unknown78** [comment]
I had the similar issue of `JNI FatalError` in https://github.com/topjohnwu/Magisk/issues/7493.
So I'm glad it solves your issue.

**Comment by shezik** [comment]
> I had the similar issue of `JNI FatalError` in #7493. So I'm glad it solves your issue.

I should have investigated further before opening a duplicate issue  :(

The developers probably want to release a new version soon. This bug caused some extra work since I expected a release to be stable and did not take any precaution.

**Comment by zygisk22** [comment]
A journey into disabling Zygisk

https://github.com/topjohnwu/Magisk/issues/7191#issuecomment-1840389614
