### ISSUE TITLE
Magisk blocks boot for 60s

### ISSUE THREAD

**Issue by danielm234** [topjohnwu/Magisk#7510]
Without magisk works fine

[   70.503041]I[6:      swapper/6:    0] sd 0:0:0:3: [sdd] tag#2 timing out command, waited 60s
[   70.503083]I[6:      swapper/6:    0] sd 0:0:0:3: [sdd] tag#2 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08 cmd_age=60s
[   70.503098]I[6:      swapper/6:    0] sd 0:0:0:3: [sdd] tag#2 Sense Key : 0x7 [current] 
[   70.503110]I[6:      swapper/6:    0] sd 0:0:0:3: [sdd] tag#2 ASC=0x27 ASCQ=0x1 
[   70.503124]I[6:      swapper/6:    0] sd 0:0:0:3: [sdd] tag#2 CDB: opcode=0x2a 2a 00 00 00 00 28 00 00 01 00
[   70.503138]I[6:      swapper/6:    0] blk_update_request: I/O error, dev sdd, sector 320 op 0x1:(WRITE) flags 0x800 phys_seg 1 prio class 0
[   70.503153]I[6:      swapper/6:    0] Buffer I/O error on dev sdd1, logical block 34, lost async page write
[   70.503395] [6:           init:    1] JBD2: recovery failed
[   70.503420] [6:           init:    1] EXT4-fs (sdd1): error loading journal

Device: S21
Android version: Android 13
Magisk version name: Magisk v26.4
Magisk version code: 26401

**Comment by Unknown78** [comment]
Please try the latest build and see whether it'll solve your problem or not.
https://github.com/topjohnwu/Magisk/actions/workflows/build.yml
