### ISSUE TITLE
Magisk manager uninstalls 

### ISSUE THREAD

**Issue by chuppito** [topjohnwu/Magisk#7517]
Device: pixel 6
Android version: 10
Magisk version name: 26.4
Magisk version code: 26401

Hello, I have android 14 on pixel 6 and I am root via magisk. I noticed that magisk manager had disappeared. I tried to install it and every time it disappears.
Root still works

**Comment by Unknown78** [comment]
Please try the latest build and see whether it'll solve your problem or not.
https://github.com/topjohnwu/Magisk/actions/workflows/build.yml

**Comment by a447948814** [comment]
现在只能从zip系统包直接修补boot，但是很多新设备需要修补init_boot，所以希望可以更新支持直接从zip系统包直接修补init_boot。感谢！

**Comment by chuppito** [comment]
This is the version I tested

**Comment by Unknown78** [comment]
Could you please attach/upload the logcat?

1. Uninstall Magisk
2. Start Logcat
3. Install Magisk
4. Launch Magisk
5. Wait for 1 minute
6. Stop Logcat

**Comment by chuppito** [comment]
<<< log_count = 7 >>>
[11-15 05:38:07.380 17454:17454 D/LogcatReader]
[LogcatLiveFragment] onServiceConnected

[11-15 05:38:08.789 17454:17454 I/ImeTracker]
com.dp.logcatapp:cd8b4a94: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT

[11-15 05:38:08.791 17454:17454 D/AutofillManager]
view not autofillable - not passing ime action check

[11-15 05:38:11.119 17454:17454 D/LogcatReader]
[Logcat] onActivityInBackground

[11-15 05:38:15.804 17454:17454 D/LogcatReader]
[Logcat] onActivityInForeground

[11-15 05:38:15.804 17454:17454 D/LogcatReader]
[Logcat] Posting pending logs

[11-15 05:38:15.817 17454:17454 D/LogcatReader]
[LogcatLiveFragment] onServiceConnected

**Comment by Unknown78** [comment]
Hm? why is it so few?

Could you please try again with `adb logcat`?

1. Uninstall Magisk
2. Enter and type `adb logcat -c` to clear previous logs.
3. Enter and type `adb logcat > logcat.log` to start the log.
4. Install Magisk
5. Launch Magisk
6. Wait for 1 minute
7. Press `CTRL+C` to stop
8. Attach/upload the `logcat.log` file

**Comment by chuppito** [comment]
11-15 06:22:15.759 27959 27959 I Finsky  : [2] ahsn.c(76): VerifyApps: Install-time verification requested for package com.topjohnwu.magisk, id = 48

11-15 06:22:15.767 27959 26810 I Finsky  : [824] VerifyAppsInstallTask.ajB(63): VerifyApps: Anti-malware verification task started for package=com.topjohnwu.magisk

11-15 06:22:15.768 27959 26810 I Finsky  : [824] VerifyAppsInstallTask.ajB(748): VerifyApps: Skipping anti malware verification (preconditions not met). package=com.topjohnwu.magisk

11-15 06:22:15.779 27959 27959 I Finsky  : [2] VerifyInstallTask.ajA(58): VerifyApps: Verification complete: id=48, package_name=com.topjohnwu.magisk

11-15 06:22:16.045 27649 27649 W ziparchive: Unable to open '/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/base.dm': No such file or directory

11-15 06:22:16.045 27649 27649 W ziparchive: Unable to open '/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/base.dm': No such file or directory

11-15 06:22:16.065 27649 27649 I artd    : Running dex2oat: /apex/com.android.art/bin/art_exec --drop-capabilities --set-task-profile=Dex2OatBootComplete --set-priority=background --keep-fds=6:7:8:9 -- /apex/com.android.art/bin/dex2oat64 --zip-fd=6 --zip-location=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/base.apk --oat-fd=7 --oat-location=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/oat/arm64/base.odex --output-vdex-fd=8 --swap-fd=9 --class-loader-context=PCL[] --classpath-dir=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA== --instruction-set=arm64 --instruction-set-features=default --instruction-set-variant=cortex-a55 --compiler-filter=verify --compilation-reason=install --compact-dex-level=none --max-image-block-size=524288 --resolve-startup-const-strings=true --generate-mini-debug-info --runtime-arg -Xtarget-sdk-version:34 --runtime-arg -Xhidden-api-policy:enabled --cpu-set=0,1,2,3,4,5,6,7 -j8 --runtime-arg -Xms64m --runtime-arg -Xmx512m --comments=app-version-name:26.4,app-version-code:26400,art-version:341010052

11-15 06:22:16.065 27649 27649 I artd    : Opened FDs: 6:/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/base.apk 7:/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/oat/arm64/base.odex.HwyKMs.tmp 8:/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/oat/arm64/base.vdex.gpQyqY.tmp 9:/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/oat/arm64/base.odex.swap.ElXMZC.tmp 

11-15 06:22:16.172 27743 27743 W dex2oat64: /apex/com.android.art/bin/dex2oat64 --zip-fd=6 --zip-location=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/base.apk --oat-fd=7 --oat-location=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/oat/arm64/base.odex --output-vdex-fd=8 --swap-fd=9 --class-loader-context=PCL[] --classpath-dir=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA== --instruction-set=arm64 --instruction-set-features=default --instruction-set-variant=cortex-a55 --compiler-filter=verify --compilation-reason=install --compact-dex-level=none --max-image-block-size=524288 --resolve-startup-const-strings=true --generate-mini-debug-info --runtime-arg -Xtarget-sdk-version:34 --runtime-arg -Xhidden-api-policy:enabled --cpu-set=0,1,2,3,4,5,6,7 -j8 --runtime-arg -Xms64m --runtime-arg -Xmx512m --comments=app-version-name:26.4,app-version-code:26400,art-version:341010052 --inline-max-code-units=0

11-15 06:22:16.172 27743 27743 I dex2oat64: /apex/com.android.art/bin/dex2oat64 --output-vdex-fd=8 --class-loader-context=PCL[] --classpath-dir=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA== --compiler-filter=verify --compilation-reason=install --compact-dex-level=none --max-image-block-size=524288 --resolve-startup-const-strings=true --generate-mini-debug-info --cpu-set=0,1,2,3,4,5,6,7 -j8 --comments=app-version-name:26.4,app-version-code:26400,art-version:341010052 --inline-max-code-units=0

11-15 06:22:16.372  1258  1872 I ArtService: Dexopt result: [packageName = com.topjohnwu.magisk] DexContainerFileDexoptResult{dexContainerFile=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/base.apk, primaryAbi=true, abi=arm64-v8a, actualCompilerFilter=verify, status=PERFORMED, dex2oatWallTimeMillis=-6442991, dex2oatCpuTimeMillis=490, sizeBytes=2600712, sizeBeforeBytes=0, extraStatus=[]}

11-15 06:22:16.374 27649 27649 W ziparchive: Unable to open '/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/base.dm': No such file or directory

11-15 06:22:16.374 27649 27649 W ziparchive: Unable to open '/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/base.dm': No such file or directory

11-15 06:22:16.391 27649 27649 I artd    : Running dex2oat: /apex/com.android.art/bin/art_exec --drop-capabilities --set-task-profile=Dex2OatBootComplete --set-priority=background --keep-fds=6:7:8:9 -- /apex/com.android.art/bin/dex2oat64 --zip-fd=6 --zip-location=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/base.apk --oat-fd=7 --oat-location=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/oat/arm/base.odex --output-vdex-fd=8 --swap-fd=9 --class-loader-context=PCL[] --classpath-dir=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA== --instruction-set=arm --instruction-set-features=default --instruction-set-variant=cortex-a53 --compiler-filter=verify --compilation-reason=install --compact-dex-level=none --max-image-block-size=524288 --resolve-startup-const-strings=true --generate-mini-debug-info --runtime-arg -Xtarget-sdk-version:34 --runtime-arg -Xhidden-api-policy:enabled --cpu-set=0,1,2,3,4,5,6,7 -j8 --runtime-arg -Xms64m --runtime-arg -Xmx512m --comments=app-version-name:26.4,app-version-code:26400,art-version:341010052

11-15 06:22:16.391 27649 27649 I artd    : Opened FDs: 6:/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/base.apk 7:/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/oat/arm/base.odex.MWjRwu.tmp 8:/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/oat/arm/base.vdex.l6RS1H.tmp 9:/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/oat/arm/base.odex.swap.1ZipkZ.tmp 

11-15 06:22:16.424 27754 27754 I dex2oat64: /apex/com.android.art/bin/dex2oat64 --output-vdex-fd=8 --class-loader-context=PCL[] --classpath-dir=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA== --compiler-filter=verify --compilation-reason=install --compact-dex-level=none --max-image-block-size=524288 --resolve-startup-const-strings=true --generate-mini-debug-info --cpu-set=0,1,2,3,4,5,6,7 -j8 --comments=app-version-name:26.4,app-version-code:26400,art-version:341010052 --inline-max-code-units=0

11-15 06:22:16.616  1258  1872 I ArtService: Dexopt result: [packageName = com.topjohnwu.magisk] DexContainerFileDexoptResult{dexContainerFile=/data/app/~~j1Zo2Zrsag_FX7iL_7Ubxw==/com.topjohnwu.magisk-TLlPxDVht8FAEXUIMm6JtA==/base.apk, primaryAbi=false, abi=armeabi-v7a, actualCompilerFilter=verify, status=PERFORMED, dex2oatWallTimeMillis=-6443077, dex2oatCpuTimeMillis=410, sizeBytes=2600456, sizeBeforeBytes=0, extraStatus=[]}

11-15 06:22:17.282  1258  1872 I AppsFilter: interaction: PackageSetting{bb1eb9a com.google.android.microdroid.empty_payload/10399} -> PackageSetting{3bfe54 com.topjohnwu.magisk/10598} BLOCKED

11-15 06:22:17.283  1258  1872 I AppsFilter: interaction: PackageSetting{3045ca8 com.example.kinginstaller/10373} -> PackageSetting{3bfe54 com.topjohnwu.magisk/10598} BLOCKED

11-15 06:22:17.381  1258  2160 I SdkSandboxManager: No SDKs used. Skipping SDK data reconcilation for CallingInfo{mUid=10598, mPackageName='com.topjohnwu.magisk, mAppProcessToken='null'}

11-15 06:22:17.407  1258  1258 I AppsFilter: interaction: PackageSetting{b8d19cc com.google.android.microdroid.empty_payload/10399} -> PackageSetting{8b85415 com.topjohnwu.magisk/10598} BLOCKED

11-15 06:22:17.407  1258  1258 I AppsFilter: interaction: PackageSetting{d58632a com.example.kinginstaller/10373} -> PackageSetting{8b85415 com.topjohnwu.magisk/10598} BLOCKED

11-15 06:22:17.861  4900  4900 I SafetyLabelChangedBroadcastReceiver: received broadcast packageName: com.topjohnwu.magisk, current user: UserHandle{0}, packageChangeEvent: NEW_INSTALL, intent user: UserHandle{0}

11-15 06:22:17.876 26997 27782 I System.out: LP:package:com.topjohnwu.magisk

11-15 06:22:17.877 26997 27783 I System.out: LP:package:com.topjohnwu.magisk

11-15 06:22:17.878 27959 27959 I Finsky  : [2] kha.f(9): AIM: AppInfoCacheUpdater -> invalidating apps: [com.topjohnwu.magisk]

11-15 06:22:17.878 27959 28014 I Finsky  : [288] kiu.a(55): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.topjohnwu.magisk]

11-15 06:22:17.879 27959 28014 I Finsky  : [288] kiu.a(55): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.topjohnwu.magisk]

11-15 06:22:17.890 27959 27007 I Finsky  : [837] bb.a(21): Asset module storage cleared for package com.topjohnwu.magisk.

11-15 06:22:17.898 27959 27959 I Finsky  : [2] kha.f(9): AIM: AppInfoCacheUpdater -> invalidating apps: [com.topjohnwu.magisk]

11-15 06:22:17.914 17722 27797 I ProximityAuth: [RecentAppsMediator] Package added: (user=UserHandle{0}) com.topjohnwu.magisk

11-15 06:22:17.939 27959 28005 I Finsky  : [279] kiu.a(55): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.topjohnwu.magisk]

11-15 06:22:17.954 27959 28014 I Finsky  : [288] kiu.a(55): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.topjohnwu.magisk]

11-15 06:22:18.562  1258  6289 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.topjohnwu.magisk cmp=com.topjohnwu.magisk/.ui.MainActivity} with LAUNCH_MULTIPLE from uid 10079 (BAL_ALLOW_VISIBLE_WINDOW) result code=0

11-15 06:22:18.576   592  2897 W gralloc4: Unable to set buffer name VRI[magisk]#1276(BLAST Consumer)1276: File name too long

11-15 06:22:18.576  1258  1791 I ActivityManager: Start proc 27840:com.topjohnwu.magisk/u0a598 for next-top-activity {com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity}

11-15 06:22:18.577   592  2897 W gralloc4: Unable to set buffer name VRI[magisk]#1276(BLAST Consumer)1276: File name too long

11-15 06:22:18.579   592  2897 W gralloc4: Unable to set buffer name VRI[magisk]#1276(BLAST Consumer)1276: File name too long

11-15 06:22:18.580   592  2897 W gralloc4: Unable to set buffer name VRI[magisk]#1276(BLAST Consumer)1276: File name too long

11-15 06:22:18.663 27840 27840 I opjohnwu.magisk: Using CollectorTypeCC GC.

11-15 06:22:18.665 27840 27840 E opjohnwu.magisk: Not starting debugger since process cannot load the jdwp agent.

11-15 06:22:19.066  1258  1790 I ActivityManager: Force stopping com.topjohnwu.magisk appid=10598 user=-1: deletePackageX

11-15 06:22:19.066  1258  1872 I AppsFilter: interaction: PackageSetting{974ecfd com.google.android.microdroid.empty_payload/10399} -> PackageSetting{aeb3b50 com.topjohnwu.magisk/10598} BLOCKED

11-15 06:22:19.067  1258  1872 I AppsFilter: interaction: PackageSetting{94c4448 com.example.kinginstaller/10373} -> PackageSetting{aeb3b50 com.topjohnwu.magisk/10598} BLOCKED

11-15 06:22:19.067  1258  1790 I ActivityManager: Killing 27840:com.topjohnwu.magisk/u0a598 (adj 0): stop com.topjohnwu.magisk due to deletePackageX

11-15 06:22:19.068  1258  1790 W ActivityTaskManager: Force removing ActivityRecord{491887d u0 com.topjohnwu.magisk/.ui.MainActivity t4971 f}}: app died, no saved state

11-15 06:22:19.090  1258  1928 I WindowManager: WIN DEATH: Window{b2b6cad u0 com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity}

11-15 06:22:19.090  1258  1928 W InputManager-JNI: Input channel object 'b2b6cad com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity (client)' was disposed without first being removed with the input manager!

11-15 06:22:19.196  1258  3281 W InputManager-JNI: Input channel object 'e072aa5 Splash Screen com.topjohnwu.magisk (client)' was disposed without first being removed with the input manager!

11-15 06:22:19.423  1258  1872 I ActivityManager: Force stopping com.topjohnwu.magisk appid=10598 user=0: pkg removed

11-15 06:22:19.423  1258  1872 I WindowManager:   Force removing ActivityRecord{491887d u0 com.topjohnwu.magisk/.ui.MainActivity t4971 f} isExiting}

11-15 06:22:19.423  1258  1872 W WindowManager: removeAppToken: Attempted to remove non-existing token: Token{8c243c3 ActivityRecord{491887d u0 com.topjohnwu.magisk/.ui.MainActivity t4971 f} isExiting}}

11-15 06:22:19.447  1258  1872 I ActivityManager: Force stopping com.topjohnwu.magisk appid=10598 user=0: pkg removed

11-15 06:22:19.447  1258  1872 I WindowManager:   Force removing ActivityRecord{491887d u0 com.topjohnwu.magisk/.ui.MainActivity t4971 f} isExiting}

11-15 06:22:19.447  1258  1872 W WindowManager: removeAppToken: Attempted to remove non-existing token: Token{8c243c3 ActivityRecord{491887d u0 com.topjohnwu.magisk/.ui.MainActivity t4971 f} isExiting}}

11-15 06:22:19.510 27303 27303 E PackageChangedReceiver: com.google.android.libraries.mediahome.providers.video.broadcastreceivers.PackageChangedReceiver.onReceive:58 Error: package com.topjohnwu.magisk not found

11-15 06:22:19.510 27303 27303 E PackageChangedReceiver: android.content.pm.PackageManager$NameNotFoundException: com.topjohnwu.magisk

11-15 06:22:19.537  4900  4920 W LightPackageInfoLiveData: Package "com.topjohnwu.magisk" not found for user UserHandle{0}

11-15 06:22:19.537  4900  4921 W LightPackageInfoLiveData: Package "com.topjohnwu.magisk" not found for user UserHandle{0}

11-15 06:22:19.572 27303 27928 E PackageAddedReceiver: com.google.android.libraries.mediahome.providers.video.broadcastreceivers.PackageAddedReceiver$1.doInBackground:64 Package not found com.topjohnwu.magisk

11-15 06:22:19.572 27303 27928 E PackageAddedReceiver: android.content.pm.PackageManager$NameNotFoundException: com.topjohnwu.magisk

11-15 06:22:19.600 27959 27959 I Finsky  : [2] wqj.u(84): Package no longer installed: com.topjohnwu.magisk

11-15 06:22:19.601 27959 27959 I Finsky  : [2] wqj.u(84): Package no longer installed: com.topjohnwu.magisk

11-15 06:22:19.605 27959 27959 I Finsky  : [2] kha.f(9): AIM: AppInfoCacheUpdater -> invalidating apps: [com.topjohnwu.magisk]

11-15 06:22:19.607 27959 28015 I Finsky  : [289] kiu.a(55): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.topjohnwu.magisk]

11-15 06:22:19.610 27959 27959 I Finsky  : [2] wqj.u(84): Package no longer installed: com.topjohnwu.magisk

11-15 06:22:19.612 27959 27007 I Finsky  : [837] bb.a(21): Asset module storage cleared for package com.topjohnwu.magisk.

11-15 06:22:19.618 27959 27959 W Finsky  : [2] abtb.b(133): STU: Failed to get storage stats for package 'com.topjohnwu.magisk' (1601: Error getting stats: android.content.pm.PackageManager.NameNotFoundException)

11-15 06:22:19.629 17722 27814 I ProximityAuth: [RecentAppsMediator] Package removed: (user=UserHandle{0}) com.topjohnwu.magisk

11-15 06:22:19.686 20934 27823 W SQLiteLog: (28) double-quoted string literal: "com.topjohnwu.magisk"

11-15 06:22:19.705 20934 25111 I Icing   : doRemovePackageData com.topjohnwu.magisk

11-15 06:22:19.815  1258  2025 I RollbackManager: broadcast=ACTION_PACKAGE_FULLY_REMOVED pkg=com.topjohnwu.magisk

11-15 06:22:19.840  1258  2104 W WifiService: Couldn't get PackageInfo for package:com.topjohnwu.magisk

11-15 06:22:19.867  1258  1258 I Telecom : CarModeTracker: Package com.topjohnwu.magisk is not tracked.: SSH.oR@2Sg

11-15 06:22:19.870  1258  1258 I ConditionProviders: Disallowing condition provider com.topjohnwu.magisk (userSet: true)

11-15 06:22:19.870  1258  2104 I PasspointManager: No app ops listener found for com.topjohnwu.magisk

11-15 06:22:19.870  1258  2104 W WifiService: Couldn't get PackageInfo for package:com.topjohnwu.magisk

11-15 06:22:19.892  1258  2104 I PasspointManager: No app ops listener found for com.topjohnwu.magisk

**Comment by Unknown78** [comment]
@canyie @yujincheng08

**Comment by yujincheng08** [comment]
tho no enough log, but i think its signature missmatched.

**Comment by chuppito** [comment]
You closed, but what solution do I have to have magisk?

**Comment by Unknown78** [comment]
Hmm.. let me take a step back.. 

> I noticed that magisk manager had disappeared. I tried to install it and every time it disappears.

Does `disappears` in that context means missing from launcher or from list of Apps in the Settings? Did you really uninstall any previous existing installation of Magisk App?

**Comment by chuppito** [comment]
I think absent Applications but he always has a trace. The problem is that the next Android update may not happen. We'll see

**Comment by Unknown78** [comment]
> I think
Why "I think"? Do you regally check the Apps list in the settings?

**Comment by chuppito** [comment]
Yes. I will try updating Android to see if that fixes the problem.
