### ISSUE TITLE
Magisk Shut down on 25.2 when im try to click on setting 

### ISSUE THREAD

**Issue by RobertoMM1986** [topjohnwu/Magisk#7519]
Device: Redmi Note 10 PRO
Android version: 12
Magisk version name: 26.4
Magisk version code: 26.401

I did fresh install and installed Magisk 25.2 instead of 26.4 because i need older version for other modules.
I never had issue in the past with this version (25.2) but with the new release (26.4) when im click on setting on up right Magisk shut down everytime im try to click on setting.
I can fix only by updating to last version (26.4) any tip???

**Comment by Unknown78** [comment]
Please try the latest build and see whether it'll solve your problem or not.
https://github.com/topjohnwu/Magisk/actions/workflows/build.yml
