### ISSUE TITLE
Magic 26.4 has a startup cycle

### ISSUE THREAD

**Issue by zhangziran** [topjohnwu/Magisk#7520]
Device: xiaomi12 (cupid)

Android version: 13 Magisk version name: 26.4

Magisk version code: 26401

Replace patches created in version 26.2 or higher

Must have a startup loop, but this has never happened before in version 26.1.

I use Magisk to create patches and updates, and follow the installation instructions every step.

Where did I go wrong?

**Comment by zhangziran** [comment]
After using  https://github.com/topjohnwu/Magisk/issues/7515#issuecomment-1811617058 to fix the issue, you can enter the desktop normally, but you cannot open any apps (including the status bar) and the lock screen is gone.

**Comment by Unknown78** [comment]
Could you please attach/upload the full logcat from boot?

**Comment by Unknown78** [comment]
> After using https://github.com/topjohnwu/Magisk/issues/7515#issuecomment-1811617058 to fix the issue

@TotallyAvailable He said that he already tried to use the latest build and still errors. We'll just wait for the logcat.

**Comment by zhangziran** [comment]
When posting, the latest compiled version is Magisk Build # 3669. Currently, 3670 has been updated, so I still need to test 3670. But as I am located in Beijing time and currently working overtime, I may need to wait until tomorrow to take the 3670 test first. If the problem persists, I will learn how to capture logcat（ https://www.jianshu.com/p/c4abb7fa6f81) before uploading

**Comment by yujincheng08** [comment]
no log no fix.
