### ISSUE TITLE
Module Files Not Mounted to System

### ISSUE THREAD

**Issue by bagusnl** [topjohnwu/Magisk#753]
I've installed magisk, but all modules files not mounted to system. But su, resetprop, and service.sh works perfectly.
I've v17.3 installed first, modules not mounted, then my friend suggested to install canary 17.4 so i install that version. After installing that version, module files mounted. But, when i reboot, it loops around 3 times, then module files not mounted again.

I guess i tried on 16.7 17.1 17.3 and 17.4

Lenovo Vibe K5 a6020a40 AEX 5.8 UnOfficial Oreo 8.1
Kernel 3.10.108 gcc 4.9.x 

Here i attach untouched boot.img and magisk log
https://drive.google.com/folderview?id=1UUNhXkIXF1M4iim_NgxIext36bgECJeL

**Comment by bagusnl** [comment]
I mean files on title, typo happens 😂

**Comment by gloeyisk** [comment]
> I've installed magisk, but all modules files not mounted to system. But su, resetprop, and service.sh works perfectly.
> I've v17.3 installed first, modules not mounted, then my friend suggested to install canary 17.4 so i install that version. After installing that version, module files mounted. But, when i reboot, it loops around 3 times, then module files not mounted again.
> 
> I guess i tried on 16.7 17.1 17.3 and 17.4
> 
> Lenovo Vibe K5 a6020a40 AEX 5.8 UnOfficial
> Kernel 3.10.108 gcc 4.9.x
> 
> Here i attach untouched boot.img and magisk log
> https://drive.google.com/folderview?id=1UUNhXkIXF1M4iim_NgxIext36bgECJeL

I thought Girls Not Mounted :laughing:

**Comment by topjohnwu** [comment]
@bagusnl can't access the files.
You can upload files to GitHub, you don't need to use Google Drive

**Comment by bagusnl** [comment]
> @bagusnl can't access the files.
> You can upload files to GitHub, you don't need to use Google Drive

sorry my bad, i was using my phone when creating this issue
though, boot.img still on Google Drive, GitHub not support that file. I updated the link

[magisk_log_20181103_093750.log](https://github.com/topjohnwu/Magisk/files/2544607/magisk_log_20181103_093750.log)
[boot.img](https://drive.google.com/file/d/1YVePNfPTblbEyQ96Aw-4ETFDd_nLPQVZ/view?usp=sharing)

**Comment by topjohnwu** [comment]
Close as OP mentioned issue fixed
