### ISSUE TITLE
Magisk no option for Direct Install, lots of crashing

### ISSUE THREAD

**Issue by sanman97** [topjohnwu/Magisk#7530]
where's the log file located? and do i adb logcat or just use a logcat app (before or after?)
does reinstalling Magisk delete the log?
here's the boot.img and patched
https://mega.nz/folder/Ko92UQYa#be9FKzuVFxgSYoL1_IMInQ
ok all i got this time was logcat while installing Magisk app, which disappeared right when opening it, and tried installing again, and disappeared

trying a bunch of versions but using the same boot.img to make a patched file and booting it
lots of crashing system UI, magisk app disappears, etc

Device: Pixel 6
Android version: 13
Magisk version name: 16.4, and previous
Magisk version code: 26401 (Magisk disappeared...)

ROM Derpfest (latest)

i was reading some other bug reports

**Comment by canyie** [comment]
Nothing was recorded in your logcat, but I presume it was fixed in the latest build https://github.com/topjohnwu/Magisk/actions/runs/6820908782
