### ISSUE TITLE
一加9R氧OS LE2101_13.1.0.583(EX01) F.30刷入magisk后卡logo

### ISSUE THREAD

**Issue by crux92** [topjohnwu/Magisk#7550]
Device:Oneplus 9R
Android version:13.1
Magisk version name:debug
Magisk version code:26401(D)

‘logcat.log’ seems infinitely increasing so I interrupted, and captured some.
‘magisk.log’ seems cannot read.
attachment include 'boot.img','logcat_captured.log','magisk.log','dmesg.log','proc_mounts.log'
[oneplus9R.zip](https://github.com/topjohnwu/Magisk/files/13447983/oneplus9R.zip)

**Comment by yujincheng08** [comment]
not magisk's issue

**Comment by dckill** [comment]
> > > Device:Oneplus 9R Android version:13.1 Magisk version name:debug Magisk version code:26401(D)
> > > ‘logcat.log’ seems infinitely increasing so I interrupted, and captured some. ‘magisk.log’ seems cannot read. attachment include 'boot.img','logcat_captured.log','magisk.log','dmesg.log','proc_mounts.log' [oneplus9R.zip](https://github.com/topjohnwu/Magisk/files/13447983/oneplus9R.zip)
> > 
> > 
> > 我也是同样情况, 请问你解决了么?
> 
> 后来我直接刷的安卓14，然后用一加工具箱进行root，root后是旧版的app和旧版的zygisk。先把app更新到了新版，安装magisk的时候有直接安装的选项，直接安装就没问题。感觉是修补的boot.img有问题。

感谢反馈, 我卡主之后使用官方包中的boot.img文件进行还原,能够进入系统, 你这个自己刷全量的方案我回头试试, 感谢!!

**Comment by crux92** [comment]
> > > > Device:Oneplus 9R Android version:13.1 Magisk version name:debug Magisk version code:26401(D)
> > > > ‘logcat.log’ seems infinitely increasing so I interrupted, and captured some. ‘magisk.log’ seems cannot read. attachment include 'boot.img','logcat_captured.log','magisk.log','dmesg.log','proc_mounts.log' [oneplus9R.zip](https://github.com/topjohnwu/Magisk/files/13447983/oneplus9R.zip)
> > > 
> > > 
> > > 我也是同样情况, 请问你解决了么?
> > 
> > 
> > 后来我直接刷的安卓14，然后用一加工具箱进行root，root后是旧版的app和旧版的zygisk。先把app更新到了新版，安装magisk的时候有直接安装的选项，直接安装就没问题。感觉是修补的boot.img有问题。
> 
> 感谢反馈, 我卡主之后使用官方包中的boot.img文件进行还原,能够进入系统, 你这个自己刷全量的方案我回头试试, 感谢!!

LE2101_14.0.0.300(EX01)暂时用不了此方法，直接安装会出现第一屏之后无限重启的情况。
