### ISSUE TITLE
Bootloop - Samsung M12

### ISSUE THREAD

**Issue by halvabner** [topjohnwu/Magisk#7551]
Device: Samsung Galaxy M12
Android version: 13
Magisk version name: 26.4
Magisk version code: aa6c7c15 (26401) (D)

### Problem
After following the [instructions](https://topjohnwu.github.io/Magisk/install.html) as accurately as possible, the device bootloops after rebooting from Download mode.

### Firmware
`M127FXXU6DWIA` (latest). It can be obtained [here](https://samfw.com/firmware/SM-M127F/EGY/M127FXXU6DWIA) or by using official tools such as Samsung Kies.

### What I have additionally tried
Apparently Magisk worked fine on the older firmware version [M127FXXU4DWC4](https://samfw.com/firmware/SM-M127F/EGY/M127FXXU4DWC4) from June. Sadly when I tried using it instead, I discovered that the bootloader doesn't allow you to flash images with version numbers lower than the current installed version.
Unrelated, but could you perhaps let me know if it's possible to bump the version number in the old firmware image to bypass this? I wouldn't mind this solution if it's less expensive than fixing Magisk for the latest firmware instead.

### `boot.img` in the AP_* I patched:
[boot.img.zip](https://github.com/topjohnwu/Magisk/files/13453587/boot.img.zip)

(`Ramdisk: Yes` so I assume recovery.img is not needed)

### `boot.img` in the AP_* after getting patched by Magisk:
[magisk_boot.img.zip](https://github.com/topjohnwu/Magisk/files/13453590/magisk_boot.img.zip)

### Magisk patching log:

```
- Device platform: arm64-v8a
- Installing: aa6c7c15 (26401)
- Processing tar file
-- Extracting: boot.img
-- Copying: recovery.img.lz4
-- Copying: dtbo.img.lz4
-- Copying: super.img.lz4
-- Copying: metadata.img.lz4
-- Patching: vbmeta.img
-- Writing: vbmeta.img
-- Copying: vbmeta_system.img.lz4
-- Copying: misc.bin.lz4
-- Copying: meta-data/
-- Copying: meta-data/fota.zip
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [37195788]
RAMDISK_SZ      [1476135]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [128116]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2023-08]
PAGESIZE        [2048]
NAME            [SRPTJ05C006]
CMDLINE         [androidboot.hardware=exynos850 androidboot.selinux=enforce loop.max_part=7]
CHECKSUM        [53b4e5b4f8a2b30a5818d8cdfb3b8c507dfd709d000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
SAMSUNG_SEANDROID
[boot/sign.rs:242] unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [19] (primitive)
VBMETA
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Patching ramdisk
resetprop: get prop [ro.crypto.state]: [encrypted]
preinit device: cache
- Pre-init storage partition: cache
Loading cpio: [ramdisk.cpio]
Add file [init] (100750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add file [overlay.d/sbin/magisk32.xz] (100644)
Add file [overlay.d/sbin/magisk64.xz] (100644)
Add file [overlay.d/sbin/stub.xz] (100644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/stub.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add file [.backup/.magisk] (100000)
Dumping cpio: [ramdisk.cpio]
Loading dtbs from [dtb]
Loading dtbs from [dtb]
Trap
Patch @ 0x00219BD4 [821B8012] -> [E2FF8F12]
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [37195788]
RAMDISK_SZ      [1476135]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [128116]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2023-08]
PAGESIZE        [2048]
NAME            [SRPTJ05C006]
CMDLINE         [androidboot.hardware=exynos850 androidboot.selinux=enforce loop.max_part=7]
CHECKSUM        [53b4e5b4f8a2b30a5818d8cdfb3b8c507dfd709d000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
SAMSUNG_SEANDROID
[boot/sign.rs:242] unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [19] (primitive)
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [2]
KERNEL_SZ       [37195788]
RAMDISK_SZ      [2041872]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [128116]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2023-08]
PAGESIZE        [2048]
NAME            [SRPTJ05C006]
CMDLINE         [androidboot.hardware=exynos850 androidboot.selinux=enforce loop.max_part=7]
CHECKSUM        [94b4fe600b5de0a0c2a948b5a4cac1c193a2c4bf000000000000000000000000]
-- Writing: boot.img

****************************
 Output file is written to
 /storage/emulated/0/Download/magisk_patched-26401_XjWAD.tar
****************************
cp: can't preserve ownership of 'busybox': Operation not permitted
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
cp: can't preserve ownership of 'magiskpolicy': Operation not permitted
- All done!
```

### `cat /proc/mounts` on the firmware in question (bootloader unlocked) (*without* Magisk)
[mounts.txt](https://github.com/topjohnwu/Magisk/files/13453605/mounts.txt)

### dmesg
I found it challenging to get dmesg or logcat output so I hope it isn't needed. If it is necessary I'll try harder.

### A small question I have
I would like to know this out of curiosity. Unofficial guides recommend I create an archive containing boot.img and vbmeta.img, let Magisk patch it and then factory reset after flashing it. The official guide instructs to give Magisk the entire AP_* file to patch and then flash the patched AP\_\* + original BL\_\*, CP\_\*, CSC\_\*. Flashing CSC\_\* causes it to wipe the original firmware and so it isn't required we boot into recovery mode to wipe it manually after patching. Am I correct?

**Comment by Unknown78** [comment]
Please try [the latest successful build that was pushed by topjohnwu](https://github.com/topjohnwu/Magisk/actions/workflows/build.yml?query=branch%3Amaster+is%3Asuccess+event%3Apush+actor%3Atopjohnwu).
> Currently it is [cfb20b0f86414d851b51e10cd633328d405ca4f7](https://github.com/topjohnwu/Magisk/suites/18073040664/artifacts/1041400471)

Click to download, extract the .zip file, you'll find the .apk to install.
Unhide and uninstall previous installation of Magisk.
Install it to get the App and do Direct-Install patch as usual.
If `app-release.apk` didn't work, try `app-debug.apk`. Both App and Direct-Install patch.

<hr>

If those didn't work, then we need logs with App and Direct-Install from that `app-debug.apk`.

Desktop requirements:
- Phone USB Drivers Installed
- `adb` from [Android SDK Platform-Tools](https://developer.android.com/tools/releases/platform-tools#downloads)

Phone requirements:
- USB Debugging enabled
- USB Debugging authorized/allowed the Desktop
- Superuser granted the `com.android.shell` (`adb shell`)

Steps:
1. Turn off the phone.
2. On the desktop, open terminal/shell/cmd
3. Change directory to the extracted `platform-tools` folder.
4. Enter `adb logcat > logcat.log`
5. Connect the phone to desktop.
6. Turn on the phone

If it doesn't bootloop:
> 7. Wait till home shows up + another 60 seconds,
> 8.  If you're **able** to open Magisk App, then go to Logs, tap the diskette icon. Get `magisk_log_dateTtime.log` in your internal storage Download folder.
> 9. Back to desktop, press `CTRL+C`
> 10. If earlier you're **not able** to open Magisk App, enter `adb shell su -c cat /cache/magisk.log > magisk.log`
> 11. Enter `adb shell su -c dmesg > dmesg.log`
> 12. Enter `adbshell su -c cat /proc/mounts > proc_mounts.log`
> 13. Restart the phone, wait till power on, and then enter `adb wait-for-device shell su -c cat /proc/last_kmsg > last_kmsg.log`

If it does bootloop:
> 7. Wait till it restart itself
> 8. Back to desktop, press `CTRL+C`
> 9. Enter `adb wait-for-device shell su -c cat /cache/magisk.log > magisk.log`
> 10. Enter `adb wait-for-device shell su -c dmesg > dmesg.log`
> 11. Enter `adb wait-for-device shell su -c cat /proc/mounts > proc_mounts.log`
> 12. Enter `adb wait-for-device shell su -c cat /proc/last_kmsg > last_kmsg.log`

Attach all the log files here.

**Comment by yujincheng08** [comment]
no logcat and dmesg

**Comment by Unknown78** [comment]
So you tried beforehand that with unpatched boot the adb works at boot?

**Comment by Unknown78** [comment]
I'm on Nougat and `adb logcat` should work without root or unpatched boot given that USB debugging is enabled and authorized the Desktop.

`adb` not being detected at all boot stages is so weird, are you sure you had [Samsung Android USB Driver](https://developer.samsung.com/android-usb-driver) installed?

**Comment by Unknown78** [comment]
OCR is really the last resort...

Let's try experiment even further..

**Comment by Unknown78** [comment]
OCR is really the last resort...

Let's try experiment even further..
I'd like you to try method from https://github.com/topjohnwu/Magisk/issues/7491#issuecomment-1813843647

With unpatched firmware, please flash magisk through recovery mode, boot to system and see if the bootloop is gone or not. Some people was able to solve it through that way, I hope you do so. This is my very last attempt that I was able to think.

**Comment by ItzPeto** [comment]
@halvabner Were you able to solve this issue? A friend of mine seems to have this exact problem with bootlooping after flashing.

**Comment by jeweljacob387** [comment]
> @halvabner Were you able to solve this issue? A friend of mine seems to have this exact problem with bootlooping after flashing.

And I too join the league of failed ones. My state is also same, Magisk was installed and was working fine until out of my curiosity I updated latest stock version using Samsung switch.

I'm not proficient with adb tools but if someone can guide, I still have patience left to try.

**Comment by jeweljacob387** [comment]
> > @halvabner Were you able to solve this issue? A friend of mine seems to have this exact problem with bootlooping after flashing.
> 
> And I too join the league of failed ones. My state is also same, Magisk was installed and was working fine until out of my curiosity I updated latest stock version using Samsung switch.
> 
> I'm not proficient with adb tools but if someone can guide, I still have patience left to try.



Magisk logs while patching

```
- Device platform: arm64-v8a
- Installing: a9f8c207 (27007)
- Processing tar file
-- Patching  : vbmeta.img
-- Copying   : recovery.img
-- Extracting: boot.img
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [37261324]
RAMDISK_SZ      [1476131]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [128116]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2024-05]
PAGESIZE        [2048]
NAME            [SRPTJ12A008]
CMDLINE         [androidboot.hardware=exynos850 androidboot.selinux=enforce loop.max_part=7]
CHECKSUM        [f6bb35f59db239dc824a78f492acdafad29dec5c000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
SAMSUNG_SEANDROID
unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [19] (primitive)
VBMETA
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Patching ramdisk
- Pre-init storage partition: cache
Loading cpio: [ramdisk.cpio]
Add file [init] (100750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add file [overlay.d/sbin/magisk.xz] (100644)
Add file [overlay.d/sbin/stub.xz] (100644)
Add file [overlay.d/sbin/init-ld.xz] (100644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup [init] -> [.backup/init.xz]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/init-ld.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/stub.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add file [.backup/.magisk] (100000)
Dumping cpio: [ramdisk.cpio]
Loading dtbs from [dtb]
Loading dtbs from [dtb]
Trap
Patch @ 0x00219BD4 [821B8012] -> [E2FF8F12]
Patch @ 0x01C9C32A [70726F63615F636F6E66696700] -> [70726F63615F6D616769736B00]
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [37261324]
RAMDISK_SZ      [1476131]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [128116]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2024-05]
PAGESIZE        [2048]
NAME            [SRPTJ12A008]
CMDLINE         [androidboot.hardware=exynos850 androidboot.selinux=enforce loop.max_part=7]
CHECKSUM        [f6bb35f59db239dc824a78f492acdafad29dec5c000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
SAMSUNG_SEANDROID
unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [19] (primitive)
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [2]
KERNEL_SZ       [37261324]
RAMDISK_SZ      [1356847]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [128116]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2024-05]
PAGESIZE        [2048]
NAME            [SRPTJ12A008]
CMDLINE         [androidboot.hardware=exynos850 androidboot.selinux=enforce loop.max_part=7]
CHECKSUM        [56e9ea648c709279be71e5dae1cb3b24e92743fc000000000000000000000000]
-- Writing   : boot.img

****************************
 Output file is written to 
 /storage/emulated/0/Download/magisk_patched-27007_iRP4L.tar 
****************************
cp: can't preserve ownership of 'busybox': Operation not permitted
cp: can't preserve ownership of 'init-ld': Operation not permitted
cp: can't preserve ownership of 'magisk': Operation not permitted
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
cp: can't preserve ownership of 'magiskpolicy': Operation not permitted
- All done!
```
