### ISSUE TITLE
Magisk installer partition identification error.

### ISSUE THREAD

**Issue by Giveuplll** [topjohnwu/Magisk#7555]
Magisk installer partition identification error.Identify the model that does not have init_boot originally, and identify that there is an init_boot image installation, which leads to the installation failure.
This is a screenshot of the installation failure.
![Screenshot_2023-11-24-18-28-54](https://github.com/topjohnwu/Magisk/assets/100572502/c0c14dc1-0cb9-49ef-8425-a292c3386ebb)
In addition, when I executed the magisk uninstaller and restarted the system, the /adb/magisk/ folder was not deleted automatically, and it could not be deleted manually.

Use KernelSu's root terminal to delete, and I have completely uninstalled magisk before this operation.
![Screenshot_2023-11-25-08-47-53-491_com termux](https://github.com/topjohnwu/Magisk/assets/100572502/8bc92532-dca8-42c9-b1cd-50bbc03056fb)

device:Redmi PICO F4/MUNCH
Android version:Android 13
Magisk version name:26.4
Magisk version code:26401

**Comment by yujincheng08** [comment]
twrp installation has been deprecated.

**Comment by Giveuplll** [comment]
> TWRP 安装已弃用。

问题是我修补boot安装，打开app就叫我修复环境，修复还不成功，我想手动把magisk文件夹删了让他重新修复，那个文件夹还删不掉

**Comment by canyie** [comment]
Duplicate of #7231

**Comment by Giveuplll** [comment]
> Duplicate of #7231
There seems to be no explanation and solution, or I don't understand it.

**Comment by Giveuplll** [comment]
> twrp installation has been deprecated.

The problem is that I repaired the boot installation, and when I opened the app, I was asked to repair the environment. The repair was not successful. I wanted to manually delete the magisk folder and let him repair it again, but that folder could not be deleted.

**Comment by DocMAX** [comment]
Same problem here...
https://github.com/topjohnwu/Magisk/issues/7719

**Comment by DocMAX** [comment]
I think this is the place. Maybe put init_boot last?
https://github.com/topjohnwu/Magisk/blob/86e00209649a60e5359ace3665997b653e00fc33/scripts/util_functions.sh#L379
