### ISSUE TITLE
Bootloop A13 Redmi 7

### ISSUE THREAD

**Issue by zinhuofc** [topjohnwu/Magisk#7568]
Device: redmi 7 onclite
Android version: 13
Magisk version name: 
[debug.txt](https://github.com/topjohnwu/Magisk/files/13503496/debug.txt)
[release.txt](https://github.com/topjohnwu/Magisk/files/13503518/release.txt)
d9b67a2
Magisk version code: 26401

**Comment by yujincheng08** [comment]
no enough log.
