### ISSUE TITLE
Magisk Hide Broken? 

### ISSUE THREAD

**Issue by Dodgexander** [topjohnwu/Magisk#758]
Related to this issue:

https://github.com/topjohnwu/Magisk/issues/729#issuecomment-436132532

Magisk 17 doesn't run on stock ZTE axon 7 ROMs without a modification to boot.img and custom signed modules: https://forum.xda-developers.com/axon-7/development/kernel-magisk-17-stock-roms-t3856809

Result is some modules don't work properly and magisk fails safetynet on stock rom. Even with props config module and certified fingerprint it fails both basic integrity and CTS.

Here's my log: 11-06 00:04:42.745  1275  3042 F libc    : Fatal signal 7 (SIGBUS), code 1, fault addr 0x7dd27c0c31 in tid 3042 (IzatProvider)
11-06 00:04:42.894  3118  3118 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-06 00:04:42.894  3118  3118 F DEBUG   : Build fingerprint: 'ZTE/P996A01_O/ailsa_ii:8.0.0/OPR1.170623.032/20180815.171922:user/release-keys'
11-06 00:04:42.894  3118  3118 F DEBUG   : Revision: '0'
11-06 00:04:42.894  3118  3118 F DEBUG   : ABI: 'arm64'
11-06 00:04:42.894  3118  3118 F DEBUG   : pid: 1275, tid: 3042, name: IzatProvider  >>> system_server <<<
11-06 00:04:42.894  3118  3118 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x7dd27c0c31
11-06 00:04:42.894  3118  3118 F DEBUG   :     x0   0000007dd2ad6700  x1   0000007da083fde4  x2   0000000000000002  x3   0000000000000004
11-06 00:04:42.894  3118  3118 F DEBUG   :     x4   0000000000000ace  x5   0000000000000004  x6   000000000000000e  x7   0000000000000ac0
11-06 00:04:42.894  3118  3118 F DEBUG   :     x8   0000007da083fd80  x9   0000007dd27c0c31  x10  0000007da8469798  x11  000000000000006b
11-06 00:04:42.894  3118  3118 F DEBUG   :     x12  0000000000000000  x13  00000000000016be  x14  0000000000000022  x15  0000000000000008
11-06 00:04:42.894  3118  3118 F DEBUG   :     x16  0000007da083fdd0  x17  0000000000000018  x18  0000000000000020  x19  0000007da84697a0
11-06 00:04:42.894  3118  3118 F DEBUG   :     x20  0000007da8456b14  x21  0000000013940210  x22  00000000160a1fb0  x23  0000000013955250
11-06 00:04:42.894  3118  3118 F DEBUG   :     x24  00000000139551e8  x25  0000000013940158  x26  0000000070872918  x27  0000000000000000
11-06 00:04:42.894  3118  3118 F DEBUG   :     x28  0000000000000000  x29  0000007da083fdc0  x30  0000007da8456b70
11-06 00:04:42.894  3118  3118 F DEBUG   :     sp   0000007da083fd60  pc   0000007dd27c0c31  pstate 0000000020000000
11-06 00:04:42.901  3118  3118 F DEBUG   : 
11-06 00:04:42.901  3118  3118 F DEBUG   : backtrace:
11-06 00:04:42.901  3118  3118 F DEBUG   :     #00 pc 0000000000543c31  /system/lib64/libart.so
11-06 00:04:42.901  3118  3118 F DEBUG   :     #01 pc 0000000000013b6c  /system/lib64/liblocationservice_jni.so (_ZL8onEnableP7_JNIEnvP8_jobjecti+88)
11-06 00:04:42.901  3118  3118 F DEBUG   :     #02 pc 0000000000281704  /system/priv-app/com.qualcomm.location/oat/arm64/com.qualcomm.location.odex (offset 0x98000)
Vold-posix: - Patching boot image
Vold-posix: - Target image: /dev/block/sde12
Vold-posix: - Unpacking boot image
Vold-posix: - Checking ramdisk status
Vold-posix: - Magisk patched boot image detected
Vold-posix: - Patching ramdisk
Vold-posix: - Repacking boot image
Vold-posix: - Flashing new boot image
Vold-posix: - Done, reboot to apply.

I would post things like log cat and dmesg without using the modification to get v17 working on stock ZTE axon ROMs but it's impossible to do so as device gets stuck in loop to recovery. V16.7 doesn't have this problem though but still fails safetynet.

Here are current logs post modification:
https://drive.google.com/file/d/1fyho2EbiPMPDe7hDDFc1R_usAoE1qHpp/view?usp=drivesdk

**Comment by topjohnwu** [comment]
Duplicate #729
