### ISSUE TITLE
树莓派 lineageos 15.1 无法刷入

### ISSUE THREAD

**Issue by alexxuyao** [topjohnwu/Magisk#760]
你好，我在树莓派 3b+ 上安装了 lineageos 15.1 但无法刷入 magisk 。

我是按 
https://konstakang.com/devices/rpi3/LineageOS15.1/
进行操作的，但无法刷入 magisk ,提示

Sony ELF32 format detected

请问如何解决？

**Comment by topjohnwu** [comment]
那個 boot image format 不遵循 AOSP 格式，無法刷入
