### ISSUE TITLE
Cannot enable zygisk on A14 QPR2 Beta 2

### ISSUE THREAD

**Issue by Logan-Developer** [topjohnwu/Magisk#7619]
Device: Google Pixel 8
Android version: Android 14 QPR2 Beta 2
Magisk version name: 1dcf3255
Magisk version code: 26402

After updating my pixel 8 to A14 QPR2, I can no longer use zygisk. The option is toggled in the settings, but it remains disabled (Magisk reports Zygisk=No) even after rebooting the phone.

Edit: here is the log:
[magisk_log_2023-12-11T14.39.14.log](https://github.com/topjohnwu/Magisk/files/13641296/magisk_log_2023-12-11T14.39.14.log)

**Comment by jiggs82** [comment]
Same issue for me too P8Pro

**Comment by fuzzhead** [comment]
No root at all Pixel 8 Pro. Tried stable and beta builds of the Magisk App

**Comment by techgenius1** [comment]
Same on Pixel 7 Pro  A14 QPR2 B2

**Comment by Crinisus** [comment]
Same with P6P (AP11.231117.006)

**Comment by KieronQuinn** [comment]
> Looks like there's been a couple of method signature changes that need to be accounted for:
> 
> ```
> 12-11 14:35:08.937   843   843 E :  zygisk64: unknown signature of nativeForkAndSpecialize(II[II[[IILjava/lang/String;Ljava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZZ)I
> 12-11 14:35:08.937   843   843 E :  zygisk64: unknown signature of nativeSpecializeAppProcess(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZZ)V
> ```

The strange thing is both of these signatures are the same in the new build so I'm not sure what's going on here.

**Comment by WhiteDayZ** [comment]
Same issue on P6 QPR2 B2

**Comment by Aarqw12** [comment]
I can confirm from pixel 8 ( Shiba ) same issue

**Comment by canyie** [comment]
@KieronQuinn Can you provide the commit which introduced the new argument?

**Comment by KieronQuinn** [comment]
> @KieronQuinn Can you provide the commit which introduced the new argument?

Not in AOSP because this is the QPR, no source code. I've tried adding the argument to a custom build but it still complains, I'm guessing I'm missing something. My current patch is here: https://pastebin.com/raw/5bkPi9x6

**Comment by KieronQuinn** [comment]
Correction, that _does_ work, it just needed a clean build. PR incoming!

**Comment by vvb2060** [comment]
https://dumps.tadiphone.dev/dumps/google/barbet/-/blob/barbet_beta-user-14-AP11.231117.006-11174680-release-keys/system/system/framework/framework.jar

```
.method static blacklist forkAndSpecialize(II[II[[IILjava/lang/String;Ljava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZZ)I
    .registers 24
    .param p0, "uid"  # I
    .param p1, "gid"  # I
    .param p2, "gids"  # [I
    .param p3, "runtimeFlags"  # I
    .param p4, "rlimits"  # [[I
    .param p5, "mountExternal"  # I
    .param p6, "seInfo"  # Ljava/lang/String;
    .param p7, "niceName"  # Ljava/lang/String;
    .param p8, "fdsToClose"  # [I
    .param p9, "fdsToIgnore"  # [I
    .param p10, "startChildZygote"  # Z
    .param p11, "instructionSet"  # Ljava/lang/String;
    .param p12, "appDataDir"  # Ljava/lang/String;
    .param p13, "isTopApp"  # Z
    .param p14, "pkgDataInfoList"  # [Ljava/lang/String;
    .param p15, "allowlistedDataInfoList"  # [Ljava/lang/String;
    .param p16, "bindMountAppDataDirs"  # Z
    .param p17, "bindMountAppStorageDirs"  # Z
    .param p18, "bindMountSyspropOverrides"  # Z
```
```
.method private static blacklist specializeAppProcess(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZZ)V
    .registers 21
    .param p0, "uid"  # I
    .param p1, "gid"  # I
    .param p2, "gids"  # [I
    .param p3, "runtimeFlags"  # I
    .param p4, "rlimits"  # [[I
    .param p5, "mountExternal"  # I
    .param p6, "seInfo"  # Ljava/lang/String;
    .param p7, "niceName"  # Ljava/lang/String;
    .param p8, "startChildZygote"  # Z
    .param p9, "instructionSet"  # Ljava/lang/String;
    .param p10, "appDataDir"  # Ljava/lang/String;
    .param p11, "isTopApp"  # Z
    .param p12, "pkgDataInfoList"  # [Ljava/lang/String;
    .param p13, "allowlistedDataInfoList"  # [Ljava/lang/String;
    .param p14, "bindMountAppDataDirs"  # Z
    .param p15, "bindMountAppStorageDirs"  # Z
    .param p16, "bindMountSyspropOverrides"  # Z

```

**Comment by jiggs82** [comment]
Any luck building it with fix yet guys 🤔

**Comment by KieronQuinn** [comment]
There's a failing action, seems to be failing for the PR before this one too. I can't do anything about that unfortunately.

**Comment by canyie** [comment]
> There's a failing action, seems to be failing for the PR before this one too. I can't do anything about that unfortunately.

The actions is just too buggy. I have re-ran it for you.

**Comment by EwanMac3** [comment]
Any way to download the build output from GitHub Actions?

**Comment by Xuzhour** [comment]
same issue on pixel 7 pro
