### ISSUE TITLE
Unable to build Magisk from source

### ISSUE THREAD

**Issue by KneesDev** [topjohnwu/Magisk#7627]
Device: N/A
Android version: N/A
Magisk version name: latest (commit ca25935) from master branch
Magisk version code: N/A

There seems to be an issue with the code in this repository. While building, I get the following message:
```bash
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\path\to\magisk\build.gradle.kts' line: 1

* What went wrong:
An exception occurred applying plugin request [id: 'MagiskPlugin']
> Failed to apply plugin 'MagiskPlugin'.
   > Cannot invoke "org.eclipse.jgit.lib.Ref.getObjectId()" because the return value of "org.eclipse.jgit.lib.RefDatabase.exactRef(String)" is null

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6s
```
This message appears as an error in Android Studio, too.

**Comment by yujincheng08** [comment]
magke sure magisk is still under its git repo

**Comment by KneesDev** [comment]
I haven't deleted the .git directory so it should be..

**Comment by XdekHckr** [comment]
> I haven't deleted the .git directory so it should be..

I have compiled it few days ago without issues and the APK is provided on my GitHub, also threads: 
https://github.com/topjohnwu/Magisk/issues/7623#issuecomment-1856548144
https://xdaforums.com/t/help-compile-build-magisk-apk.4645772/

**Comment by xiaopao2014** [comment]
Remember, sometimes we download source.zip instead of "git clone " for GFW, it would get that issue. try to "git init " local can fix it
