### ISSUE TITLE
Magisk version above v24.2 results in "Installed: N/A"

### ISSUE THREAD

**Issue by Haus3master** [topjohnwu/Magisk#7635]
Device: Nokia 1
Android version: "Android 8.1 go" to "Android 10 go"
Magisk version name: d7750b72
Magisk version code: 26403

This device has a mediatek mt6737m, and is running Android 10 go at the moment but this issue affects all 3 Android versions. (All of these are stock roms)

Any version of magisk which is above v24.2 stable results in Installed as N/A.

I'm attaching the magisk manager log along with the patched boot image.
[magisk_log_2023-12-18T22.41.46.log](https://github.com/topjohnwu/Magisk/files/13706635/magisk_log_2023-12-18T22.41.46.log)

Note: The 'su' applet is missing from /system/bin according to terminal emulator
[manager log and patched boot image.zip](https://github.com/topjohnwu/Magisk/files/13706653/manager.log.and.patched.boot.image.zip)

**Comment by vvb2060** [comment]
v24.2 work?

**Comment by Haus3master** [comment]
> v24.2 work?

Yes, it works. Any version above that doesn't when.

**Comment by canyie** [comment]
```
903 896 0:15 / /sbin rw,relatime master:8 - tmpfs magisk rw,seclabel,mode=755
```
Does `/sbin/su` or `/sbin/magisk` exists? Can you su in adb shell? If you can, can you extract and attach `magisk.log` from `/cache`?

**Comment by Haus3master** [comment]
> ```
> 903 896 0:15 / /sbin rw,relatime master:8 - tmpfs magisk rw,seclabel,mode=755
> ```
> 
> Does `/sbin/su` or `/sbin/magisk` exists? 

Yes, these do exist but running su is unsuccessful and hence getting the log from cache is not possible.

I was able to get another manager log and an adb logcat after boot_comolete flag was triggered

**Comment by canyie** [comment]
It looks you started recording too late. Shutdown your phone, run `adb logcat > logcat.log`, start your phone, then connect it to your PC immediately

**Comment by Haus3master** [comment]
> It looks you started recording too late. Shutdown your phone, run `adb logcat > logcat.log`, start your phone, then connect it to your PC immediately

The logcat triggers after the boot is complete, the usage of "wait for device" flag didn't help either.

Can the magisk.log from cache partition help? I'll try extracting it somehow if it's helpful

**Comment by Haus3master** [comment]
[logcat.log](https://github.com/topjohnwu/Magisk/files/13724771/logcat.log)
Here's adb logcat that was taken through the boot process

**Comment by canyie** [comment]
Sorry, this one still looks too late  ╮（╯＿╰）╭

**Comment by yujincheng08** [comment]
send the file generated by `adb bugreport`.

**Comment by Haus3master** [comment]
> send the file generated by `adb bugreport`.

Hi, sorry about the delay, here's the output of adb bugreport 
[bugreport-Frontier_00WW-QP1A.190711.020-2021-04-08-16-50-49.zip](https://github.com/topjohnwu/Magisk/files/13743763/bugreport-Frontier_00WW-QP1A.190711.020-2021-04-08-16-50-49.zip)

**Comment by windowshopr** [comment]
Not sure if this is the correct thread to post this in, but figured I'd start here before opening a new issue. Doesn't seem to want to install properly on a Umidigi F3 Pro, Android 13 either. I have tried the latest (26.4) and the above mentioned 24.2 versions, says `Installed: N/A` and `Zygisk: No` under the Magisk heading. When you click the Install button, it just shows the recent changelog for the current version, and the `LET'S GO` button is greyed out. There's a checkbox for `Method Select and Patch a File` but that's all. Without going through the steps of TWRP install, which I imagine would result in the same thing anyway, figured I'd mention it here too. Thanks!

**Comment by canyie** [comment]
Still toooooo late. Try setting log buffer size to the maximum value in Developer Options and try again?

**Comment by yujincheng08** [comment]
I wonder why magiskd crashed without tomestone.

**Comment by yujincheng08** [comment]
Use this module to capture log: https://t.me/hwrtools/10

**Comment by Haus3master** [comment]
> Still toooooo late. Try setting log buffer size to the maximum value in Developer Options and try again?

I'll try this



> Use this module to capture log: https://t.me/hwrtools/10

There magisk installation is not active, hence, using this module is not possible at the moment

**Comment by Haus3master** [comment]
[bugreport-Frontier_00WW-QP1A.190711.020-2021-04-09-10-55-02.zip](https://github.com/topjohnwu/Magisk/files/13751473/bugreport-Frontier_00WW-QP1A.190711.020-2021-04-09-10-55-02.zip)
Log buffer size is maximum (1MB)

**Comment by Haus3master** [comment]
Nope,

> [app-debug.zip](https://github.com/topjohnwu/Magisk/files/13752444/app-debug.zip) Flash this magisk. And use adb to see if there's `system.log` in `/data/local/tmp`. If so, send it.

System.log doesn't exist in the specified directory after flashing the given build

**Comment by Haus3master** [comment]
I'm attaching the stock boot image. 
[boot.zip](https://github.com/topjohnwu/Magisk/files/13756690/boot.zip)
Patched boot image:
[G.zip](https://github.com/topjohnwu/Magisk/files/13756697/G.zip)
Also, logcat only begins after the device reaches the lockscreen. It's still unclear why it behaves like that

**Comment by Haus3master** [comment]
> I'm attaching the stock boot image. [boot.zip](https://github.com/topjohnwu/Magisk/files/13756690/boot.zip) Patched boot image: [G.zip](https://github.com/topjohnwu/Magisk/files/13756697/G.zip) Also, logcat only begins after the device reaches the lockscreen. It's still unclear why it behaves like that

Please compare these images, I think magisk is either not patching or skipping the image entirely. Magisk 24.2 works and takes about 20 seconds to generate patched image, but with later versions, it takes less than 5 seconds to generate boot image

**Comment by Haus3master** [comment]
Update: Upon installing HavocOS GSI image all versions including latest debug build work normally, strange

**Comment by yujincheng08** [comment]
this problem is not caused by boot patching

**Comment by Haus3master** [comment]
My device doesn't have a vbmeta partition. Upto magisk 24.2 patch vbmeta in boot image option shows up, but versions above it doesn't show this option, could this be an issue?

**Comment by k0mraid3** [comment]
Just wanted to second this issue, just happened now on Galaxy Tab S8+ Ultra when trying to update magisk app from within the app, app update went fine, then on reboot and attempting the direct patch,, on next reboot, su was gone and only root access was via twrp, tried to reflash magisk (latest) via twrp, no good either, something did catch my eye about some policy error in /data/misc but could be a useless rabbit-hole. Tried both beta and stable. Too late for logs as i've wiped and am upgrading it to 14, but somethings went wrong big time, same exact situation as OP for the most part. If i have time after the new year i'll replicate this again and catch logs if not already sorted.

**Comment by canyie** [comment]
> My device doesn't have a vbmeta partition. Upto magisk 24.2 patch vbmeta in boot image option shows up, but versions above it doesn't show this option, could this be an issue?

No

**Comment by canyie** [comment]
Can you test these builds?
26202: https://github.com/topjohnwu/magisk-files/raw/bfb230a95f5acb0b2f5a113c8e12f6e7a05c892f/app-debug.apk
26203: https://github.com/topjohnwu/magisk-files/raw/cd7fd78534f2f4b032d776b3ca2f2924a65353e0/app-debug.apk

**Comment by Haus3master** [comment]
> Can you test these builds? 26202: https://github.com/topjohnwu/magisk-files/raw/bfb230a95f5acb0b2f5a113c8e12f6e7a05c892f/app-debug.apk 26203: https://github.com/topjohnwu/magisk-files/raw/cd7fd78534f2f4b032d776b3ca2f2924a65353e0/app-debug.apk

The 26202 build fails to patch the boot image 
" Copying image to cache
Installation failed"

The 26203 build is still showing the same N/A error.
I attached the install and manger logs of 26203 build
[magisk_install_log_2023-12-28T14.06.26.log](https://github.com/topjohnwu/Magisk/files/13784722/magisk_install_log_2023-12-28T14.06.26.log)
[magisk_log_2023-12-28T14.06.31.log](https://github.com/topjohnwu/Magisk/files/13784723/magisk_log_2023-12-28T14.06.31.log)

**Comment by Haus3master** [comment]
The install (boot image patch) logs of the 26202 build
[magisk_install_log_2023-12-28T14.12.00.log](https://github.com/topjohnwu/Magisk/files/13784774/magisk_install_log_2023-12-28T14.12.00.log)

**Comment by k0mraid3** [comment]
> Can you test these builds? 26202: https://github.com/topjohnwu/magisk-----files/raw/bfb230a95f5acb0b2f5a113c8e12f6e7a05c892f/app-debug.apk 26203: https://github.com/topjohnwu/magisk-files/raw/cd7fd78534f2f4b032d776b3ca2f2924a65353e0/app-debug.apk

```  26202: https://github.com/topjohnwu/magisk-----files/raw/bfb230a95f5acb0b2f5a113c8e12f6e7a05c892f/app-debug.apk ``` 
26202 - Confirmed working just now, Android 14. , Sam Tab S8+. Had to clear all old data/cache/etc and flash clean via odin or it would start down a rabbit-hole of different errors, including the one i mentioned before about issues with some policy in /data/misc. Once everything was cleared and reset, 26202 worked fine.

2603 -- Same issue as latest, except here it will reboot device and it booted fine first time round', but no magisk. Reboot back to recovery and attempt to reflash  magisk, and seems its mucking up boot partition, i say this because if reboot is attempted, it does the classic bootloop, never making it completely past first splash (I am thinking our issue is happening just before kernel loads or right as its loading.)

**Comment by yujincheng08** [comment]
[app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13794953/app-debug.apk.zip)
Install this version of magisk, and see if `/data/local/tmp` has `magisk.log`. If so, send.

**Comment by Haus3master** [comment]
> [app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13794953/app-debug.apk.zip) Install this version of magisk, and see if `/data/local/tmp` has `magisk.log`. If so, send.

Nope, the file still doesn't exist. I got the boot image patch and manager logs...
[magisk_install_log_2023-12-30T10.04.06.log](https://github.com/topjohnwu/Magisk/files/13797124/magisk_install_log_2023-12-30T10.04.06.log)
[magisk_log_2023-12-30T10.10.26.log](https://github.com/topjohnwu/Magisk/files/13797125/magisk_log_2023-12-30T10.10.26.log)

**Comment by yujincheng08** [comment]
[app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13797667/app-debug.apk.zip)
This magisk should product `/sbin/.magisk/kmsg`.

**Comment by Haus3master** [comment]
> [app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13797667/app-debug.apk.zip) This magisk should product `/sbin/.magisk/kmsg`.

The kmsg exists but trying to do anything results in permission denied

**Comment by Haus3master** [comment]
> [app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13797667/app-debug.apk.zip) This magisk should product `/sbin/.magisk/kmsg`.

If possible a build that would dump all logs to the internal storage would be easier as there wouldn't be any issues with file permissions

**Comment by vvb2060** [comment]
If you don't know how to use it, don't use the terminal.  Install a file manager. https://play.google.com/store/apps/details?id=me.zhanghai.android.files

**Comment by yujincheng08** [comment]
[app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13798738/app-debug.apk.zip)
Try this to see if you can access `/sbin/.magisk/kmsg`?

**Comment by Haus3master** [comment]
> [app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13798738/app-debug.apk.zip) Try this to see if you can access `/sbin/.magisk/kmsg`?

This build is getting the device stuck at the logo. It boots on flashing 24.2 boot image. I'm attaching the direct install logs
[magisk_install_log_2023-12-30T23.01.40.log](https://github.com/topjohnwu/Magisk/files/13798788/magisk_install_log_2023-12-30T23.01.40.log)

**Comment by yujincheng08** [comment]
i am out idea. lets see if others have any idea. the problem should be that the magisk policy is not injected correctly.

**Comment by yujincheng08** [comment]
[app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13799811/app-debug.apk.zip)
Suddenly something came into my mine. Try if this boots? If so, can you access `/sbin/.magisk/kmsg`? If so, can you send this file?

**Comment by Haus3master** [comment]
> [app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13799811/app-debug.apk.zip) Suddenly something came into my mine. Try if this boots? If so, can you access `/sbin/.magisk/kmsg`? If so, can you send this file?

The device boots up.
I am able to access /sbin/.magisk/kmsg.
This is the kmsg file
[kmsg (1).zip](https://github.com/topjohnwu/Magisk/files/13800213/kmsg.1.zip)
Side effect of this build is that System UI doesn't work, basically no navigation and status bar.

**Comment by yujincheng08** [comment]
[app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13804889/app-debug.apk.zip)
Use this ver to get the kmsg file again.

**Comment by canyie** [comment]
Hi. Have you tested whether v24.3 work or not?

**Comment by Haus3master** [comment]
> Hi. Have you tested whether v24.3 work or not?

24.3 isn't working

**Comment by Haus3master** [comment]
> [app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13804889/app-debug.apk.zip) Use this ver to get the kmsg file again.

Here's the kmsg,( systemui is still broken)
[kmsg.zip](https://github.com/topjohnwu/Magisk/files/13805244/kmsg.zip)

**Comment by yujincheng08** [comment]
Please also send `/system/bin/init`.

**Comment by Haus3master** [comment]
> Please also send `/system/bin/init`.

Here it is
[init.zip](https://github.com/topjohnwu/Magisk/files/13807527/init.zip)

**Comment by yujincheng08** [comment]
[app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13811653/app-debug.apk.zip)
Try if this works.

**Comment by Haus3master** [comment]
Switched to a GSI where everything including magisk works (camera is broken though). I'm leaving it up to the other Nokia 1 users (if any) to sort this out.

**Comment by Haus3master** [comment]
Wrong tag
