### ISSUE TITLE
Custom recovery installed but no magisk

### ISSUE THREAD

**Issue by tkalfaoglu** [topjohnwu/Magisk#764]
Stock recovery of ALP-09, and Omirom latest version installed.
1. Extracted RECOVERY_RAMDISK.IMG from stock code,
2. Stored in sdcard,
3. Installed latest magisk manager, selected "preserve force encryption" and "dm-verity" options.
4. Clicked Install, selected "patched boot image file", selected RECOVERY_RAMDISK.IMG
5. It created the patched_boot.img, no errors/warnings shown. Downloaded it to my pc with 
   sudo adb pull  /storage/emulated/0/Download/patched_boot.img
6. restarted phone in fastboot mode.
7. Stored the recovery with:
   sudo fastboot flash recovery_ramdisk patched_boot.img
8. After reboot, the magisk manager still says "not installed"

Tried this with both stable (17.1) and beta (17.3) from the magisk manager.

**Comment by topjohnwu** [comment]
EMUI 9 cannot be properly rooted due to the fact that Huawei still doesn't release any EMUI 9 kernel source code. Without a proper kernel hexpatch, Magisk is unable to be loaded. Blame the stupid company for violating GPL.

**Comment by tkalfaoglu** [comment]
Many thanks -- downloading an older EMUI image.. Going back to 8.0.x fast...
