### ISSUE TITLE
Stuck in bootloop after attempting to flash magisk on Samsung Galaxy A12 (A125F). 

### ISSUE THREAD

**Issue by Shaddow798** [topjohnwu/Magisk#7654]
Device: Samsung A12 (SM-A125F
Android version: 12 
Magisk version name: 26.4 (debug) 
Magisk version code: [1057cb3 ](https://github.com/topjohnwu/Magisk/commit/1057cb3e3ca2c513f6757c4448cc35075084520c) (26403) (D)
Attached files:
[magisk_install_log_2023-12-24T21.17.31.log](https://github.com/topjohnwu/Magisk/files/13761319/magisk_install_log_2023-12-24T21.17.31.log)
[procmounts.txt](https://github.com/topjohnwu/Magisk/files/13761553/procmounts.txt)

Here are the boot.img and recovery.img files that magisk created (I extracted this from the patched AP archive)
[boot.zip](https://github.com/topjohnwu/Magisk/files/13761604/boot.zip)
note the recovery is split using the split command on linux so it probaly doesnt work in 7zip 
[recovery_1.zip](https://github.com/topjohnwu/Magisk/files/13761613/recovery_1.zip)
[recovery_2.zip](https://github.com/topjohnwu/Magisk/files/13761614/recovery_2.zip)

Hello, Whenever I attempt to flash magisk on my a12 I inevitably run into an issue after flashing where the phone is bootlooping and the only way to recover is to flash a non patched AP firmware. This is likely linked to this issue #7256  and issue #7254

I cannot seem to capture kernel logs with `sudo adb -d logcat` as it just sits on waiting on device (unless i boot stock). I couldn't manage to get the device into recovery with the magisk image flashed so I couldn't figure out how to extract the kernel logs. If there is anything you want me to try, I would be willing to try.

**Comment by kyrenlee** [comment]
do you unlock bootlaoder？

**Comment by Shaddow798** [comment]
> do you unlock bootlaoder？

yeah I did its fully unlocked.
I don't think I would have gotten that far if it was locked.

**Comment by yujincheng08** [comment]
Since there's no enough information, I suspect it's the same as #7254 and close as duplicates.
