### ISSUE TITLE
"Installed: N/A, Zygisk: Yes" a short time after reboot, *or* after granting root privileges *once* quickly enough

### ISSUE THREAD

**Issue by NOTMASTER09** [topjohnwu/Magisk#7658]
Device: Xiaomi redmi 8
Android version: 11
Magisk version name: 65207f96 (D)
Magisk version code: 26404
Logcat from boot to crash(?): 
[logs.txt](https://github.com/topjohnwu/Magisk/files/13786070/logs.txt)

**Comment by yujincheng08** [comment]
when showing `Installed: N/A`, can u `su` in terminal?

**Comment by yujincheng08** [comment]
confirmed it is libsu's issue. does older versions work?

**Comment by NOTMASTER09** [comment]
No i can't, i can only do it once when it still shows up normally, once it shows N/A it prints `/system/bin/sh: su: inaccessible or not found`

**Comment by yujincheng08** [comment]
generate and send a bugreport when magisk stops working

**Comment by vvb2060** [comment]
Duplicate of #6914

**Comment by yujincheng08** [comment]
Duplicate of #6914

**Comment by NOTMASTER09** [comment]
So are there any workarounds to this or do i need to try and flash a different kernel? I don't remember flashing any custom kernels(besides the stock havocos one)

**Comment by yujincheng08** [comment]
`Kernel: Linux version 4.9.289-lineageos-g345ec19e351c (nobody@android-build) (Android (6877366 based on r383902b1) clang version 11.0.2 (https://android.googlesource.com/toolchain/llvm-project b397f81060ce6d701042b782172ed13bee898b79)) #1 SMP PREEMPT Sun Feb 27 10:15:50 IST 2022`

absolutely not a custom kernel. no workarond except for install other kernel.
