### ISSUE TITLE
Google Pixel Android P offline charging

### ISSUE THREAD

**Issue by DreamerPlays** [topjohnwu/Magisk#766]
We already had this issue with #597 and it was "resolved", but I still experience it after installing the October update via factory image then flashing the OTA. After that, I installed the canary Magisk but it still hangs on the offline charging battery icon. It also was said that the November update fixed it, but as I know of, it has not been released for the first Pixel...

**Comment by Darkcast** [comment]
I have the exact same issue on magisk 18.00
