### ISSUE TITLE
suppprt `init` that does not directly invoke `/system/bin/init`

### ISSUE THREAD

**Issue by Red-Skuller** [topjohnwu/Magisk#7661]
installed the 26404 apk. extracted boot.img from rom (e-1.17-q.zip). pushed the boot.img to device and using the magisk app created the attached patched boot.img. Pulled the patched boot.img. Rebooted to fastboot. fastboot flash boot the patched boot.img. Rebooted and opened magisk app --> Installed: N/A

I also tried to install via TWRP by renaming from .apk to .zip but that also did nothing

[magisk_patched-26404_1Yhl6.zip](https://github.com/topjohnwu/Magisk/files/13793452/magisk_patched-26404_1Yhl6.zip)
Device: Sony Xperia Z2 tablet -> sgp511
Android version: 10
Magisk version name: magisk canary
Magisk version code: 26404

PS: I don't know how to collect logs so if you want them please write the procedure with the commands

**Comment by yujincheng08** [comment]
send generated file from `adb bugreport`

**Comment by Red-Skuller** [comment]
Here you go
[bugreport-lineage_castor_windy-QQ3A.200805.001-2023-12-29-14-27-05.zip](https://github.com/topjohnwu/Magisk/files/13793839/bugreport-lineage_castor_windy-QQ3A.200805.001-2023-12-29-14-27-05.zip)

**Comment by yujincheng08** [comment]
too late. please do this right after the device has adb.

**Comment by Red-Skuller** [comment]
Ok now i flashed again and bugreport was started as soon as adb was available
[bugreport-lineage_castor_windy-QQ3A.200805.001-2023-12-29-15-03-57.zip](https://github.com/topjohnwu/Magisk/files/13794094/bugreport-lineage_castor_windy-QQ3A.200805.001-2023-12-29-15-03-57.zip)

**Comment by yujincheng08** [comment]
Not using debug version of magisk. close unconditionally.

**Comment by Red-Skuller** [comment]
Redid everything using debug 26404
[bugreport-lineage_castor_windy-QQ3A.200805.001-2023-12-29-15-12-39.zip](https://github.com/topjohnwu/Magisk/files/13794164/bugreport-lineage_castor_windy-QQ3A.200805.001-2023-12-29-15-12-39.zip)
[magisk_patched-26404_0fN5n.zip](https://github.com/topjohnwu/Magisk/files/13794166/magisk_patched-26404_0fN5n.zip)

**Comment by Red-Skuller** [comment]
It works with version 24000

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/13794425/app-debug.zip)
Use this version of magisk to grab bugreport instead.

**Comment by yujincheng08** [comment]
Looks like `magiskinit` failed to patch `/init`.

Use this ver to grab bugreport again 
[app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13795044/app-debug.apk.zip)

**Comment by Red-Skuller** [comment]
There you go. It failed again.
[magisk_patched-26404_HFI4t.zip](https://github.com/topjohnwu/Magisk/files/13795496/magisk_patched-26404_HFI4t.zip)
[bugreport-lineage_castor_windy-QQ3A.200805.001-2023-12-29-19-27-26.zip](https://github.com/topjohnwu/Magisk/files/13795497/bugreport-lineage_castor_windy-QQ3A.200805.001-2023-12-29-19-27-26.zip)

**Comment by yujincheng08** [comment]
[app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13796012/app-debug.apk.zip)
Try this one.

**Comment by Red-Skuller** [comment]
This one works! device rooted
[bugreport-lineage_castor_windy-QQ3A.200805.001-2023-12-29-23-18-31.zip](https://github.com/topjohnwu/Magisk/files/13796363/bugreport-lineage_castor_windy-QQ3A.200805.001-2023-12-29-23-18-31.zip)
[magisk_patched-26404_r2ST8.zip](https://github.com/topjohnwu/Magisk/files/13796364/magisk_patched-26404_r2ST8.zip)

**Comment by yujincheng08** [comment]
good to hear. will sumbit fix later.

**Comment by vvb2060** [comment]
#7061 regression
