### ISSUE TITLE
magisk 26.0 and above crashes home screen if zygisk enabled and you remove magisk app and reboot

### ISSUE THREAD

**Issue by s-lanc44** [topjohnwu/Magisk#7663]
Device: Motorola g7 power
Android version: 9
Magisk version name: debug
Magisk version code: 26404

As of 26.0, if you have magisk and magisk app installed with zygisk enabled, and then uninstall the magisk app and reboot, it has a problem as soon as you unlock the phone. the way to get my phone back was to fastboot the stock boot.img. there are no modules installed

If magisk and magisk app are installed and zygisk is disabled, and then i uninstall magisk app and reboot, there are no problems (it adds the stub on the home screen to reinstall magisk)

25.2 works. the problem started as soon as it goes to 26.0. this continues to 26.4 and the debug version

i do see a lot of lines below
Magisk : pkg: cannot find com.topjohnwu.magisk for user=[0]

attached is the logcat
https://github.com/topjohnwu/Magisk/files/13795644/magisk264bootloader_nomagiskapp_zygiskenabled.txt

**Comment by s-lanc44** [comment]
[magisk264bootloader_nomagiskapp_zygiskenabled.txt](https://github.com/topjohnwu/Magisk/files/13795644/magisk264bootloader_nomagiskapp_zygiskenabled.txt)

**Comment by yujincheng08** [comment]
not debug magisk.
