### ISSUE TITLE
Hide Magisk Manager loses root on Pixel 3 XL

### ISSUE THREAD

**Issue by captainmedic** [topjohnwu/Magisk#767]
On the Pixel 3 XL after using hide magisk manager it appears we lose root ability and another version of magisk manager somehow installs when on build 17.3. If you use the canary build it simply fails to have root at all.

https://forum.xda-developers.com/apps/magisk/pixel-3-xl-root-goes-using-hide-magisk-t3865585

and

https://forum.xda-developers.com/showpost.php?p=78099131&postcount=201

**Comment by captainmedic** [comment]
It appears that the latest canary build is working for me (v17.4-c61c3ae0) and therefore I am closing the issue.

**Comment by HamsterHam88** [comment]
I still can't get it to work, any ideas?
