### ISSUE TITLE
upgrading to canary disabled root

### ISSUE THREAD

**Issue by Turhvjbufv** [topjohnwu/Magisk#7676]
upgraded from magisk beta 26.4(26400), to canary (26404), first I downloaded the apk from github, installed it, opened the app, and updated using the magisk app.
that didnt work so I tried flashing it using recovery(how I normally install/update magisk), still doesnt work.
edit: tried to flash normal magisk, caused a bootloop, and I cannot enter recovery, any help?

screenshot of magisk app and logs from boot
![1](https://github.com/topjohnwu/Magisk/assets/91851160/9681e66a-69c1-41a8-bdd8-b047acbf47c6)
[magisk.txt](https://github.com/topjohnwu/Magisk/files/13827276/magisk.txt)

btw Im using lineage 20 if that matters
Device: A72
Android version: 13
Magisk version name: canary
Magisk version code: 26404

**Comment by sawdoctor** [comment]
Be interested to know if this version works

https://github.com/topjohnwu/Magisk/issues/7661#issuecomment-1872338279

Hopefully its the same bug as the update is waiting to be released

**Comment by yujincheng08** [comment]
send file generated with `adb bugreport`

**Comment by Turhvjbufv** [comment]
@sawdoctor  tried to flash normal magisk, caused a bootloop, and I cannot enter recovery, any help?

**Comment by yujincheng08** [comment]
close because of no useful log.

**Comment by Turhvjbufv** [comment]
@yujincheng08 please add a warning on download page or guide that downgrading from canary can cause bootloop with no option to use recovery

**Comment by yujincheng08** [comment]
downgrading is never supported.

**Comment by Turhvjbufv** [comment]
> downgrading is never supported.

ffs good to know now(no blaming you blaming myself)

**Comment by Turhvjbufv** [comment]
Well to everyone else that did the same dumb thing as me here is the solution, no data wipe required(not for me at least), if you cannot enter recovery mode and there is a bootloop, wait until the battery is drained, connect the phone to PC and try to boot into recovery, from there flash the update for os and it should remove root.
If recovery doesn't work, try fastboot and do the same there as recovery.
