### ISSUE TITLE
huawei emui 9 android 9.0 magisk manager apk open error:E SQLiteDatabase: Failed to open database '/sbin/.core/db-0/magisk.db'. 

### ISSUE THREAD

**Issue by cofface** [topjohnwu/Magisk#768]
huawei emui 9 android 9.0 magisk manager apk open error:E SQLiteDatabase: Failed to open database '/sbin/.core/db-0/magisk.db'.

**Comment by topjohnwu** [comment]
EMUI 9 is not supported

**Comment by arkadym** [comment]
Is magisk 18 support emui 9 ?
