### ISSUE TITLE
bootloop s8

### ISSUE THREAD

**Issue by Voxelmonk6009** [topjohnwu/Magisk#7682]
Device: SM-G950F
Android version: 9
Magisk version name: Majisk 26.4
Magisk version code: 26404

- installed no-verity-opt-encrypt-5.1 - it failed ERROR 1
- installed the 6.1 version of it - it failed ERROR 1
- tried rebooting - bootloop
- tried installing LazyFLasher - it failed
- cleared cache, delvik, system and data - sucssessfully cleared
- tried rebooting - bootloop
- installed Majisk 26.4 - sucssesful
- tried rebooting - didnt work

- i am new to doing these things, i really need help, please

**Comment by yujincheng08** [comment]
No log no fix.

**Comment by Voxelmonk6009** [comment]
[dmesg[1].log](https://github.com/topjohnwu/Magisk/files/13835852/dmesg.1.log)
[recovery[1].log](https://github.com/topjohnwu/Magisk/files/13835854/recovery.1.log)

i got those two logs
