### ISSUE TITLE
Bootloop on Hisense A7

### ISSUE THREAD

**Issue by KyoSakuyo** [topjohnwu/Magisk#7684]
Device:HNR320T (Hisense A7)
Android version:10
Magisk version name:26404
Magisk version code:26404

Linked: [#7515](https://github.com/topjohnwu/Magisk/issues/7515) [#7520](https://github.com/topjohnwu/Magisk/issues/7520) 

My device has never managed to update above >= 26402, the version only goes up to 26401, and updating to a new version keeps getting stuck in bootloop.

I can use adb commands in bootloop, but I can't get su privileges (even though I gave com.android.shell root privileges in magisk manager before updating), and I got some logs using `adb bugreport`, but I can't use the `adb shell su -c cat /cache/magisk.log > magisk.log` command to get further logs.

**Comment by KyoSakuyo** [comment]
[bugreport-HNR320T-QP1A.190711.020-2024-01-04-23-16-32.zip](https://github.com/topjohnwu/Magisk/files/13832528/bugreport-HNR320T-QP1A.190711.020-2024-01-04-23-16-32.zip)

**Comment by yujincheng08** [comment]
Try #7668

**Comment by KyoSakuyo** [comment]
It works! Thank you~~
