### ISSUE TITLE
Any version of Magisk Manager above 5.7.0 freezes at splash screen

### ISSUE THREAD

**Issue by dhjw** [topjohnwu/Magisk#769]
I installed the latest Magisk via manual boot.img patch and flash.

Any version of Magisk Manager above 5.7.0 freezes at the splash screen.

5.7.0 works fine for me, but it's annoying to be asked to upgrade on every launch, because if I do it stops working.

I have no modules or anything enabled.

I'm using a BLU Selfie 3 aka BLU Grand Max with Marshmallow. [This ROM](https://www.mediafire.com/folder/fksq672j6kty8/)

**Comment by garfae** [comment]
We concur. 

Using stock ROM on a Blackview BV8000 running Android 7, with Magisk 17.1 and TWRP installed.
No custom modules loaded. Tried clearing data on Magisk Manager, and of course resinstalling (downgarding to 5.7.0 did the trick).

Note that Manager (can't remember which, the one which came with the 17.1 release) used to work just fine until today.

**Comment by Didgeridoohan** [comment]
Without any [logs](https://didgeridoohan.com/magisk/MagiskHelp) accompanying your report, it is just a collection of words of little value...

Also, if you haven't looked at it already, here are some general tips for when the Manager doesn't work as it should:
https://didgeridoohan.com/magisk/Magisk#hn_Magisk_Manager_crashesfreezes

**Comment by dhjw** [comment]
Here's `logcat | grep magisk`: [5.7.0](http://paste.ubuntu.com/p/GtG6XZNnGK/
) (works), [5.8.0](http://paste.ubuntu.com/p/rchYC8p2nq/), [6.0.1](http://paste.ubuntu.com/p/NbkZJDJ6t2/)

The relevant error seems to be `System  : ClassLoader referenced unknown path: /data/app/com.topjohnwu.magisk-1/lib/arm`

**Comment by garfae** [comment]
@Didgeridoohan Thank you for your invaluable input. It's kinda hard though to dump a logcat with your supersu manager crashing, wouldn't you say? ;-)

Still, here's our logcat (MatCat filtered on "magisk") : [logs-2018-11-14-19-50-49.zip](https://github.com/topjohnwu/Magisk/files/2582166/logs-2018-11-14-19-50-49.zip)

Ops performed (with Manager 5.5.5 installed):
1) start logging using MatCat;
2) install latest Manager 6.0.1 over current;
3) attempt to open Manager (crash);
4) uninstall Manager 6.0.1, install Manager 5.5.5 (to be able to grant root to MatCat);
5) open MatCat, grant root, to stop logging.

**Comment by dhjw** [comment]
[Full log when running 6.0.1 after boot](http://paste.ubuntu.com/p/HRX7NVMKd4/
) (I clicked Wait after the OS said app not responding)
[Full log when running 6.0.1 after closing app from previous run](http://paste.ubuntu.com/p/2sN8zWgX27/
)
not seeing the `Killing` lines anymore, but still stuck at splash screen.

**Comment by topjohnwu** [comment]
You should test on the latest Canary build, providing debugging magisk logs (get it via custom recovery). Without the proper logs, I cannot know what is happening on your device

**Comment by garfae** [comment]
@topjohnwu Thank you! However you're talking to regular users here, not canary-level experts... So honestly I have no idea what you just said.

Assuming we can confirm the crash on the Canary build, how exactly do we get magisk logs via recovery? Do you mean the logs in [code]/cache/magisk.log[/code]?

**Comment by dhjw** [comment]
The latest Magisk patched boot.img is working fine, just MagiskManager crashes (after installing patch) if I load a version higher than 5.7.0. I've provided my logcat logs as mentioned on [xda-developers](https://forum.xda-developers.com/apps/magisk/dev-magisk-canary-channel-bleeding-edge-t3839337).

**Comment by dhjw** [comment]
1. installed MagiskManager full debug apk
2. removed Magisk by flashing old non-Magisk boot.img
3. booted and loaded MagiskManager. no crash. patched boot.img via the app
4. diff showed no difference from last patched_boot.img
5. flashed new patched_boot.img
6. booted
7. enabled logcatx record for MagiskManager
8. without loading MagiskManager manually, recorded some things in the log [seen here](http://paste.ubuntu.com/p/xc7tgcdNff/)
9. adb shell; su -; worked because of previous access granted when i had 5.7.0 installed, I guess
10. cache/magisk.log [seen here](http://paste.ubuntu.com/p/6ZHYTbtqVK/)
11. cleared logcatx app log, started record and tried manually loading MagiskManager (fingers crossed)
12. **it works! no crash.**
13. uninstall MagiskManager debug version, reinstall 6.0.1.apk
14. no more crashing.

very strange.
i had looked at the magisk.log before reflashing and nothing was out of the ordinary

i did remove a few seemingly-bloatware packages since last time i tried it.. most recently "com.pivotmobile.android.metrics", "com.dti.blu", "com.blu.copy" and other blu packages.

**Comment by dhjw** [comment]
I locked my bootloader which wiped my data. After that the canary apk and 6.0.1 started freezing again and I haven't been able to fix it, even with reflashing the patched boot.img with Flashify (with v5.7.0 installed temporarily). I think the trick that fixed it was installing the canary build / 6.0.1 and then reflashing via bootloader. Since I can't get root for Flashify with the crashing APKs I can't flash after installing them with a locked bootloader. Guess I'm going back to 5.7.0 permanently.
