### ISSUE TITLE
Enhancement request: Custom boot image patch script

### ISSUE THREAD

**Issue by rummsbumms** [topjohnwu/Magisk#77]
Would you mind to add the possibility to execute custom boot image patch script (e.g. to add a vendor boot signature) within the magisk install script?

Change could be like:
```
if [ -x "/data/custom_boot_image_patch.sh" ]; then
    ui_print "- Calling user boot image patch script" 
    sh /data/custom_boot_image_patch.sh new-boot.img
fi
```
in update-binary, function repack_boot(), right before the line
`mv new-boot.img $NEWBOOT`

It's the same way supersu does handle this.

**Comment by rummsbumms** [comment]
Any chance that this gets implemented?

**Comment by topjohnwu** [comment]
OK, I'll add it :)

**Comment by rummsbumms** [comment]
thx! :)

**Comment by rummsbumms** [comment]
@topjohnwu Could you please consider my enhancement request in the next update? This would make automation scripts easier :)
