### ISSUE TITLE
magisk modules are not deactivated after having activated safe mode on the previous boot

### ISSUE THREAD

**Issue by UblockAntiAdblock** [topjohnwu/Magisk#7702]
Device:SM-A546E
Android version:14
Magisk version name:Canary
Magisk version code: 65207f96 (26404)

What the title says. I want to install a specific module but I want to be able to remove it through safe mode in case it causes a bootloop. Since there is no TWRP on this phone yet.
My device: SM-A546E

**Comment by pndwal** [comment]
This:
https://github.com/topjohnwu/Magisk/issues/4624#issuecomment-1431369122

**Comment by vvb2060** [comment]
Don't wait for any, the sooner you press the key the better. magisk is detected earlier than the system, if pressed too late it only triggers the system safe mode but does not disable magisk modules.

**Comment by vvb2060** [comment]
Note: you can release the volume down key after the animation appears. This will trigger magisk safe mode but not system safe mode. 
Remember that magisk detects key before the system does.

**Comment by UblockAntiAdblock** [comment]
Thank you so much! You have to press the key before the system animation appears. However, you have to "calculate" when to do it. Since if you press it just after starting the Bootloader image. It will not activate either of the 2 safe modes. 👍
