### ISSUE TITLE
Magisk on arm after v26.1 cause device failed to boot 

### ISSUE THREAD

**Issue by nexplorer-3e** [topjohnwu/Magisk#7706]
This may be a regression that 
 - `Directly handle AVB 1.0 signing and verification without going through Java implementation` that introduced in v26.2. on 26.1 cause the `patch vbmeta` install option is gone (not ticking it would get working though)
 - `Update toolchain that produces broken arm32 executables` or other changes introduced in v26.3 that breaks.

After patching and flashing boot.img with newer magisk not below 26300 (or via recovery or directly upgrade), the device stuck
at first splash screen, then reboots into bootloader.

screenshot on canary:
![Screenshot_20240111-232719_Magisk](https://github.com/topjohnwu/Magisk/assets/60149113/d439896c-fd0a-419c-8043-6fe43e05e4ad)

on 26.3:
![Screenshot_20240111-232236_Magisk](https://github.com/topjohnwu/Magisk/assets/60149113/c87fb26a-ce32-4546-ac89-f91fd7fc5026)

on 26.2: Although there are install options, the busybox binary is broken cause installation failed.

on 26.1:
![Screenshot_20240111-231505_Magisk](https://github.com/topjohnwu/Magisk/assets/60149113/38224807-5156-437e-8749-9fca0d659e2a)

if there is need for bisect the problematic commit, please let me know.

Device: Xperia Z2 Tablet Wifi (castor-windy)
Android version: 11.0 (lineage-18.1-20240109-nightly-castor_windy) 
Magisk version name: 12061795
Magisk version code: 26404

**Comment by nexplorer-3e** [comment]
> git bisect start
> # status: waiting for both good and bad commits
> # bad: [5e2ef1b7f41aa695d425db152add83629cc93363] Better bytes support in C++
> git bisect bad 5e2ef1b7f41aa695d425db152add83629cc93363
> # status: waiting for good commit(s), bad commit known
> # good: [659b9c6feefcd39284ea6048d22d4001d7624b38] Support extracting any partition from payload.bin
> git bisect good 659b9c6feefcd39284ea6048d22d4001d7624b38
> # good: [f12951bd1d126de105c806f3751579c93708e25d] Fix typo
> git bisect good f12951bd1d126de105c806f3751579c93708e25d
> # good: [7eebe62bb6929ca572a2ae778bb18d660c20bb85] Do not realpath ANDROID_SDK_ROOT
> git bisect good 7eebe62bb6929ca572a2ae778bb18d660c20bb85
> # bad: [2a654e5d7ffcc9b8fb83b427c3e9af796da842d5] Improve byte_data const correctness
> git bisect bad 2a654e5d7ffcc9b8fb83b427c3e9af796da842d5
> # bad: [57afae3425a4ae585afb1ab62de4a9ee94d598a2] Cleanup cpio codebase
> git bisect bad 57afae3425a4ae585afb1ab62de4a9ee94d598a2
> # bad: [feb44f875e59caf6cc52122d05bbdb88825bf503] Migrate PREINITDEVICE in recovery mode
> git bisect bad feb44f875e59caf6cc52122d05bbdb88825bf503
> # first bad commit: [feb44f875e59caf6cc52122d05bbdb88825bf503] Migrate PREINITDEVICE in recovery mode
`git log -1`:
```bash
commit feb44f875e59caf6cc52122d05bbdb88825bf503 (HEAD, origin/master, origin/HEAD)
Author: topjohnwu <topjohnwu@gmail.com>
Date:   Fri Jun 2 16:49:04 2023 -0700

    Migrate PREINITDEVICE in recovery mode

    Close #6917
```

**Comment by canyie** [comment]
Looks you face #7068 in the feb44f875e59caf6cc52122d05bbdb88825bf503 build. Can you test d15017b? That commit fixed #7068.

**Comment by nexplorer-3e** [comment]
> Looks you face #7068 in the [feb44f8](https://github.com/topjohnwu/Magisk/commit/feb44f875e59caf6cc52122d05bbdb88825bf503) build. Can you test [d15017b](https://github.com/topjohnwu/Magisk/commit/d15017b777e8eac216a822eaf44ff46c94991cbd)? That commit fixed #7068.

@canyie I've just test which commit caused the boot patch installation to fail, then `git bisect` points me to those three commits (6b21091...b8cb9cd), which cause bootloop and the commit you mentioned cannot be tested intree:

<details><summary>Details</summary>
<p>
> # bad: [69174e2c13d8db83a9ffe0f66f2a671e86bcd265] Release Magisk v26.2
> # good: [5e2ef1b7f41aa695d425db152add83629cc93363] Better bytes support in C++
> git bisect start 'v26.2' 'HEAD'
> # bad: [1f7c3e9f14875876ec3acffb8d7cd0d9325ab9a7] Use rust to calculate sha
> git bisect bad 1f7c3e9f14875876ec3acffb8d7cd0d9325ab9a7
> # bad: [d2eaa6e6c12dde9815e266cf890abebea8ffc318] Fix scripts on Windows
> git bisect bad d2eaa6e6c12dde9815e266cf890abebea8ffc318
> # bad: [866386e21f1b0c9f584ba9e4803eccab2e47eb98] Use to_string instead of to_owned
> git bisect bad 866386e21f1b0c9f584ba9e4803eccab2e47eb98
> # good: [d2fbcd07b752e1ec0857bc8f79d11a641ef77b5f] Use sccache on non CI env
> git bisect good d2fbcd07b752e1ec0857bc8f79d11a641ef77b5f
> # skip: [e58f98e844535926e7451b7183dece198eccfc40] Update cargo files
> git bisect skip e58f98e844535926e7451b7183dece198eccfc40
> # good: [c1038ac6f9bdf9cf46f56bb4ed61d49bbf84dac0] Remove permissve update_engine
> git bisect good c1038ac6f9bdf9cf46f56bb4ed61d49bbf84dac0
> # bad: [6b21091fe219ba6ff32c7d0097b74f8a486e9108] Fix compile errors and cleanup
> git bisect bad 6b21091fe219ba6ff32c7d0097b74f8a486e9108
> # skip: [b8cb9cd84d9fda84cbd5af5dbf3d718ef1e896e9] Refactor magiskboot cpio
> git bisect skip b8cb9cd84d9fda84cbd5af5dbf3d718ef1e896e9
> # only skipped commits left to test
> # possible first bad commit: [6b21091fe219ba6ff32c7d0097b74f8a486e9108] Fix compile errors and cleanup
> # possible first bad commit: [e58f98e844535926e7451b7183dece198eccfc40] Update cargo files
> # possible first bad commit: [b8cb9cd84d9fda84cbd5af5dbf3d718ef1e896e9] Refactor magiskboot cpio
> 

</p>
</details> 

I would try to cherry pick onto good commit (b8cd9cd^) to test if that fixes the direct installation case mentioned above.

**Comment by nexplorer-3e** [comment]
`EPERM`, really strange.

**Comment by canyie** [comment]
The issue with direct installation is fixed by a470ee6. It seems irrelevant with the permission issue. Not sure what caused it. Anyway, can you test 92f9806?

**Comment by canyie** [comment]
[magisk_patched-26404_u5y6l.zip](https://github.com/topjohnwu/Magisk/files/13949675/magisk_patched-26404_u5y6l.zip)
Does this image boot?

**Comment by nexplorer-3e** [comment]
> [magisk_patched-26404_u5y6l.zip](https://github.com/topjohnwu/Magisk/files/13949675/magisk_patched-26404_u5y6l.zip) Does this image boot?

@canyie no, this one bootloops at first screen.

**Comment by canyie** [comment]
Can you test #7718?

**Comment by nexplorer-3e** [comment]
> Can you test #7718 and #7665?

7718 working on my machine. Thank you!
7665 is not merged yed.
