### ISSUE TITLE
Failed to copy "userdata.img.ext4.lz4" for patching AP

### ISSUE THREAD

**Issue by Thx2TheContributors** [topjohnwu/Magisk#7708]
Failed to copy "userdata.img.ext4.lz4" for patching AP from lastest version of stock frimware of SM-N9500【N9500ZCS7DUD1】, I'm not sure how to configure the options "Preserve AVB 2.0/dm-verity" & "Preserve force encryption" as I can't find the reference info on web , therefore I've tried check/unchecked both or either of the them and it turned out the same 

（the only relevant info I found: TWRP page says this phone use dm-verity "This means that swiping to allow system modifications will prevent you from being able to boot if you are using the stock kernel. In order to bypass dm-verity's boot prevention, you will have to install a kernel that has dm-verity disabled in the fstab." , https://twrp.me/samsung/samsunggalaxynote8snapdragon.html）

Device: Samsung Galaxy note 8 
Snapdragon (greatqltezc) arm64-v8a
【SM-N9500】【N9500ZCS7DUD1】【CHC】
Android version: 9
Magisk version name: V26.4
Magisk version code: 26404

boot and recovery 【original file from stock firmware】https://drive.google.com/drive/folders/1YZM4vqqkMc8IKonvoOzoIYGVbGbQazwQ?usp=sharing

**Comment by yujincheng08** [comment]
expected: #7129

**Comment by Thx2TheContributors** [comment]
> expected: #7129

Does it mean "userdata.img.ext4.lz4" is intentionally cut off by this updated version of Magisk as it's useless for the first time installing Magisk and might caused data partition shrink issue?
