### ISSUE TITLE
Su Command logging does not really work as expected 

### ISSUE THREAD

**Issue by Olit2000** [topjohnwu/Magisk#771]
In the superuser log only the first command that gets invoked is shown (always '''/system/bin/sh''')
I recently switched from super su to magisk. There everything got logged (stdin, stdout, stderr). This was very useful to understand what the app was doing and saved my phone because I could undo changes to the system that nearly broke everything.
Please add this feature.

**Comment by topjohnwu** [comment]
Duplicate, closed
