### ISSUE TITLE
Bootloop with EROFS system partition ...

### ISSUE THREAD

**Issue by Huexxx** [topjohnwu/Magisk#7716]
**Device: Xiaomi Mi Mix 2 (Chiron)
Android version: 14
Magisk version name: 65207f96
Magisk version code: 26404**

Since I introduced EROFS support on my rom, I cannot make it work with EROFS system partition.

Same problem since first A13 roms with EROFS support.

Rom with EROFS system partition bootloops on MIX logo (no bootanim, no adb). Exactly same rom with EXT4 system partition flawlessly works.

Boot images always patched within specified Magisk debug app.

* /proc/mounts of EXT4 version working without Magisk
[EXT4_proc_mounts.txt](https://github.com/topjohnwu/Magisk/files/13937574/EXT4_proc_mounts.txt)

* logcat and dmesg of EXT4 version working with Magisk
[Magisk26404_EXT4_logcat.txt](https://github.com/topjohnwu/Magisk/files/13937514/Magisk26404_EXT4_logcat.txt)
[Magisk26404_EXT4_dmesg.txt](https://github.com/topjohnwu/Magisk/files/13937515/Magisk26404_EXT4_dmesg.txt)

* /proc/mounts of EROFS version working without Magisk
[EROFS_proc_mounts.txt](https://github.com/topjohnwu/Magisk/files/13937491/EROFS_proc_mounts.txt)

* pmsg-ramoops-0 and console-ramoops-0 of EROFS version bootlooping with Magisk (added .txt to upload)
[pmsg-ramoops-0.txt](https://github.com/topjohnwu/Magisk/files/13937563/pmsg-ramoops-0.txt)
[console-ramoops-0.txt](https://github.com/topjohnwu/Magisk/files/13937566/console-ramoops-0.txt)

The errors seem linked to cp_link and cp_afc ops...

```
Magisk  : cp_link : /debug_ramdisk/.magisk/worker/system/bin/[ <- /debug_ramdisk/.magisk/mirror/system/bin/[
Magisk  : cp_afc /debug_ramdisk/.magisk/mirror/system/bin/[ -> /debug_ramdisk/.magisk/worker/system/bin/[ failed: Invalid argument (os error 22)
```

Regards.

**Comment by yujincheng08** [comment]
Try #7685...

**Comment by Huexxx** [comment]
Hi, thanks for your advice, but it keeps failing.

[pmsg-ramoops-0.txt](https://github.com/topjohnwu/Magisk/files/13938585/pmsg-ramoops-0.txt)
[console-ramoops-0.txt](https://github.com/topjohnwu/Magisk/files/13938586/console-ramoops-0.txt)

Same error but without mirror...
```
Magisk  : cp_link : /debug_ramdisk/.magisk/worker/system/bin/[ <- /system/bin/[
Magisk  : cp_afc /system/bin/[ -> /debug_ramdisk/.magisk/worker/system/bin/[ failed: Invalid argument (os error 22)
```

**Comment by yujincheng08** [comment]
[app-debug.apk.zip](https://github.com/topjohnwu/Magisk/files/13938657/app-debug.apk.zip)
Then use this to grab the log

**Comment by Huexxx** [comment]
Hi again.

[pmsg-ramoops-0.txt](https://github.com/topjohnwu/Magisk/files/13938785/pmsg-ramoops-0.txt)
[console-ramoops-0.txt](https://github.com/topjohnwu/Magisk/files/13938786/console-ramoops-0.txt)

Thanks so much for your work.

**Comment by yujincheng08** [comment]
Hmm, readlink says `Invalid argument`.

**Comment by vvb2060** [comment]
>  I introduced EROFS support on my rom

fix your kernel

**Comment by Huexxx** [comment]
Well, understood, but maybe you can point me a bit to where the problem is...

EROFS is working without problems, I have just problems with magisk.

Please, point me to the code where Magisk do the readlink and get `Invalid argument` to see how to patch my kernel to work as intended.

**Comment by dakkshesh07** [comment]
Hey any follow ups on this issue? I've been facing similar issues with my erofs builds. Seeing similar readlink failures in magisk log.

**Comment by Huexxx** [comment]
As said... I've fixed my kernel... how? Adding a massive number of
commits... I can't tell you which of them is the clue... but is
related to symlinks... you have to backport fs stuff...
