### ISSUE TITLE
Super user authentication is lost after a restart

### ISSUE THREAD

**Issue by Harshiv-Patel** [topjohnwu/Magisk#772]
in v17.3(17302)[magiskmanager version 6.0.1(501)] the list of apps that have been granted superuser access is lost upon restart[which is due to a separate Magisk issue, I believe,unrelated], when rebooted, the apps that ask for su, likes of apps2sd, greenify,ssdboost etc are denied su access (shown via toast) and you need to manually toggle the app in superuser tab of Magisk manager,

Running Android Lollipop 5.1.1 with Arch=arm,armeabi-v7a, device is Samsung Galaxy SM-E700H.

**Comment by topjohnwu** [comment]
Try out the latest canary, it shall fix your issue
