### ISSUE TITLE
Magisk not proving root acces on Google Pixel 4a

### ISSUE THREAD

**Issue by andriesfc** [topjohnwu/Magisk#7725]
Hi 

I'm expiring an issue with using the latest Magick (version 24.6) on a Pixel 4A, regarding root access. 

Each time after my device reboots, the buttons for root access and modules keeps being prayed out. The only way to restore root and module access back is to re-patch my boot image again and flash it. 

Note that this prevents me from installing any Magisk module, as Magisk needs root access for this.

I assume this is not the intended user experience and/or application work flow. 

I have also 3 times now restored the stock rom, patched the stock rom's boot.img, and flashed it in an attemp to see If may have missed a step. The last two times rather following the steps on the Github.

I'm not a magisk developer, so if there are any logs which I can send without root access, please let me know, and I will gladly attach it to this issue.

Regards

Andries

Device: Google Pixel 4a
Android version: 14
Magisk version name: 26404
Magisk version code: 26404

**Comment by yujincheng08** [comment]
> Magisk not proving root acces on Google Pixel 4a

But

> The only way to restore root and module access back is to re-patch my boot image again and flash it.

And
![image](https://github.com/topjohnwu/Magisk/assets/5022927/59579719-3bb2-4cca-9785-54d93c335d15)
