### ISSUE TITLE
Direct Install on Redmi9a did not work properly

### ISSUE THREAD

**Issue by wzf1018** [topjohnwu/Magisk#7731]
Device:Redmi9A
Android version:android11,MIUI12.5
Magisk version name:Magisk v26.4
Magisk version code:26404

Steps to reproduce/复现步骤
I pressed the "install" button, then checked "Direct Install", and finally clicked "Let's go", and when everything was done, I restarted the system.

Expected behaviour/预期行为
The boot image is successfully flashed and the system is booted by the new boot image.

Actual behaviour/实际行为
Although the system boot is successful, the new boot image is not successfully flashed, and the magisk is still in the previous state .

**Comment by canyie** [comment]
It's due to MTK kernel restrictions. No way to fix on our side.
