### ISSUE TITLE
magisk does not support devices with unencrypted data

### ISSUE THREAD

**Issue by roynatech2544** [topjohnwu/Magisk#7734]
Device: Samsung J7 Pop (SM-J727S)
Android version: Android 11 (Custom ROM - Pixel Experience)
Magisk version name: 65207f96
Magisk version code: 26404

Upon installing magisk from TWRP, rebooting, installing the Magisk apk, enabling zygisk in settings, rebooting, and zygisk is still not enabled, and on settings page, it still says 'reboot to apply changes'
I do have modules installed but they never caused an issue with zygisk enabling on all other devices, so that probably isn't the cause.

Screenshots of current state (I did reboot multiple times):
![Screenshot_20240128-125244_Magisk](https://github.com/topjohnwu/Magisk/assets/69458352/d7a5df3a-a608-4682-a4ef-b6019aa4d4d4)
![Screenshot_20240128-125250_Magisk](https://github.com/topjohnwu/Magisk/assets/69458352/bdd004df-1f7c-4abf-9b15-c841ae5acb7b)

Boot-time generated full logs:
[logcat.txt](https://github.com/topjohnwu/Magisk/files/14074809/logcat.txt)
[magisk_log_2024-01-28T12.47.35.log](https://github.com/topjohnwu/Magisk/files/14074810/magisk_log_2024-01-28T12.47.35.log)
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/14074811/dmesg.txt)

**Comment by vvb2060** [comment]
```
<14>[    4.003679]  [1:           init:    1] init: processing action (late-init) from (/system/etc/init/hw/init.rc:415)
<14>[    4.003769]  [1:           init:    1] init: processing action (late-init) from (/system/etc/init/atrace.rc:3)
<14>[    4.009345]  [1:           init:    1] init: processing action (nonencrypted) from (/system/etc/init/hw/init.rc:941)
<14>[    4.009748]  [1:           init:    1] init: starting service 'zygote'...
<14>[    4.010203]  [1:           init:    1] init: Created socket '/dev/socket/zygote', mode 660, user 0, group 1000
<14>[    4.010453]  [1:           init:    1] init: Created socket '/dev/socket/usap_pool_primary', mode 660, user 0, group 1000
<14>[    4.012965]  [1:           init:    1] init: starting service 'zygote_secondary'...
<14>[    4.013429]  [1:           init:    1] init: Created socket '/dev/socket/zygote_secondary', mode 660, user 0, group 1000
<14>[    4.013684]  [1:           init:    1] init: Created socket '/dev/socket/usap_pool_secondary', mode 660, user 0, group 1000
<14>[    4.454677]  [0:           init:    1] init: processing action (nonencrypted) from (/system/etc/init/hw/init.rc:1101)
<14>[    4.454902]  [0:           init:    1] init: starting service 'exec 2 (/debug_ramdisk/magisk --service)'...
<14>[    4.954586]  [2:           init:    1] init: processing action (post-fs-data) from (/system/etc/init/hw/init.rc:1094)
<14>[    4.954767]  [2:           init:    1] init: starting service 'exec 8 (/debug_ramdisk/magisk --post-fs-data)'...
```

**Comment by vvb2060** [comment]
upload /system/etc/init/hw/init.rc

**Comment by roynatech2544** [comment]
[init.rc.txt](https://github.com/topjohnwu/Magisk/files/14091460/init.rc.txt)
Here

**Comment by aviraxp** [comment]
https://github.com/Roynas-Android-Playground/device_samsung_j7popelteskt/commit/20dc4b2b33e8cad02128a31d86374663115ebdb5

**Comment by roynatech2544** [comment]
> > <14>[    3.976647]  [1:           init:    1] init: Command 'mount_all /system/vendor/etc/fstab.samsungexynos7870' action=init (/vendor/etc/init/init.samsungexynos7870.rc:30) took 132ms and succeeded
> 
> [Roynas-Android-Playground/device_samsung_j7popelteskt@20dc4b2](https://github.com/Roynas-Android-Playground/device_samsung_j7popelteskt/commit/20dc4b2b33e8cad02128a31d86374663115ebdb5)

Thanks seems i missed it
