### ISSUE TITLE
Samsung M20 Bootloop

### ISSUE THREAD

**Issue by KingMahmud** [topjohnwu/Magisk#7739]
Device: Samsung M20
Android version: 10
Magisk version name: v26.4(debug)
Magisk version code: 65207f96(26404)

Flashing any magisk version after 24.3 results in bootloop.

[dmesg.txt](https://github.com/topjohnwu/Magisk/files/14087252/dmesg.txt)

[last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/14087272/last_kmsg.txt)

**Comment by KingMahmud** [comment]
A line of last_kmsg.txt makes me curious : 
"Kernel panic - not syncing: dmv corrupt"

Is something wrong with dm-verity? I had disabled it after installing TWRP.

**Comment by yujincheng08** [comment]
It maybe the same issue as #6141

**Comment by KingMahmud** [comment]
Maybe its the same, i see there is no "official" solution. Can you point me how to solve this "unofficially"?

**Comment by yujincheng08** [comment]
Please refer to https://github.com/topjohnwu/Magisk/issues/6141#issuecomment-1229277033
