### ISSUE TITLE
Bootloop on Samsung with custom rom

### ISSUE THREAD

**Issue by rajarshikhatua100** [topjohnwu/Magisk#7746]
I am using custom rom based on Samsung galaxy S21 5g in my Samsung galaxy m31, 

if I flash magisk version 24.2 in twrp then it successfully installes 
here are the screenshot - 
![Screenshot_2024-02-01-16-43-23](https://github.com/topjohnwu/Magisk/assets/77912617/1849e8ee-e815-4f63-b10d-490380f6cb19)
![Screenshot_2024-02-01-16-43-16](https://github.com/topjohnwu/Magisk/assets/77912617/f235cc00-a518-4d0d-b634-4dc77953616a)

but If I install any later version especially the newest ones then the system goes into bootloop 
here are the screenshot -
![Screenshot_2024-02-01-16-35-54](https://github.com/topjohnwu/Magisk/assets/77912617/4f59bda9-f6b9-4076-9784-f4d0fe64ee17)

so I did flashed the letest version and the bootloop happened, immediately i went to recovery and collected the kmsg and dmesg with my pc , here are the files - 
[kmsg.txt](https://github.com/topjohnwu/Magisk/files/14132101/kmsg.txt)
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/14132104/dmesg.txt)

if you wonder what would happen if I flash magisk 24.2 and the update through magisk app, I tested it - same result, bootloop, I don't understand what is happening

hope this helps, let me know if I did something wrong or you need some additional help

Device: Samsung Galaxy M31
Android version: 13
Magisk version name: 356ee1fe
Magisk version code: 26405

**Comment by yujincheng08** [comment]
logs are useless. but i think it's the same as #6141.

**Comment by rajarshikhatua100** [comment]
why logs are useless

**Comment by rajarshikhatua100** [comment]
just fix the problem, is it fixable or not
