### ISSUE TITLE
Magisk Hide doesn't work on SKYGO app

### ISSUE THREAD

**Issue by fawkes15** [topjohnwu/Magisk#775]
Hi, SkyGO app (https://play.google.com/store/apps/details?id=it.sky.anywhere&hl=it) detects my OP 5T rooted. It's the first and only app that has this issue. I'm on OxygenOS Beta 19 (8.1.0) and magisk 17.3.
I attach log file, I hope is usefull. Thanks

https://pastebin.com/q1gzAhaW

**Comment by martyfender** [comment]
You should be on the Canary build to report issues here.

**Comment by fawkes15** [comment]
The same with canary build :-(

**Comment by fawkes15** [comment]
any news?

**Comment by giammin** [comment]
hide magisk manager

clear skygo cache and data

**Comment by fawkes15** [comment]
I did it.... works! thanks 👍

**Comment by giammin** [comment]
> I did it.... works! thanks 👍

you are welcome

**Comment by pariantes** [comment]
> hide magisk manager
> 
> clear skygo cache and data

i did it,.... doesn't work :-(

I have OnePlus 6 with Oxygen 9.0.2 Magisk 17.1 (Stable Version)

is there other solution?

Skygo reply wtich error code 99z (Rooted Device)

**Comment by auanasgheps** [comment]
@pariantes you don't even deserve a reply

**Comment by pariantes** [comment]
@auanasgheps nobody has request your opinion, shut up please and think your business

**Comment by pariantes** [comment]
@giammin credo tu sia italiano. Puoi aiutarmi per favore a risolvere il problema? ti ringrazio.

**Comment by giammin** [comment]
@pariantes 

1- hide magisk manager (from magisk settings)
2- hide magisk to alla the sky apps (skygo, sky guida tv, etc etc)
3- kill all sky apps
3- clear CACHE and DATA of all sky apps
4 - reboot you phone

i dunno other methods, sorry mate

**Comment by pariantes** [comment]
> @pariantes
> 
> 1- hide magisk manager (from magisk settings)
> 2- hide magisk to alla the sky apps (skygo, sky guida tv, etc etc)
> 3- kill all sky apps
> 3- clear CACHE and DATA of all sky apps
> 4 - reboot you phone
> 
> i dunno other methods, sorry mate

Thanks giammin, but doesn't work. Errore Code 99z (Device Rooted)

**Comment by Didgeridoohan** [comment]
As stated in the first reply, use the Canary build...

**Comment by pariantes** [comment]
@Didgeridoohan where i can find it?
