### ISSUE TITLE
Bluetooth and "power and performance" are not working

### ISSUE THREAD

**Issue by MAKROBUS** [topjohnwu/Magisk#7750]
Device: xiaomi 12 lite (taoyao)
Android version: android 14, V816.0.2.0.ULIEUXM
Magisk version name: magisk canary
Magisk version code: 26405
[com.android.bluetooth_2024-01-29T06_55_10.987.log](https://github.com/topjohnwu/Magisk/files/14150037/com.android.bluetooth_2024-01-29T06_55_10.987.log)
[com.miui.powerkeeper_2024-01-29T17_45_38.470.log](https://github.com/topjohnwu/Magisk/files/14150038/com.miui.powerkeeper_2024-01-29T17_45_38.470.log)

**Comment by yujincheng08** [comment]
close because of no magisk log
