### ISSUE TITLE
Zygisk not working after updating to version: 27001

### ISSUE THREAD

**Issue by Arc157** [topjohnwu/Magisk#7758]
Device: Any VPhoneGaGa Device
Android version: 10
Magisk version name: 3d91a561
Magisk version code: 27001

Trying to update Magisk to the latest version, then enabling Zygisk, will not apply Zygisk.
This issue was not present in Magisk v26.1.

I am able to provide VPhoneGaGa APK if needed.

`magisk.log`
[magisk_log_2024-02-05T16.25.06.log](https://github.com/topjohnwu/Magisk/files/14167682/magisk_log_2024-02-05T16.25.06.log)

Logcat was taken using the module: https://github.com/evdenis/adb_root
As for some reason. VPhoneGaGa doesn't let you connect ADB unless this module is active.
`logcat`
[logcat.txt](https://github.com/topjohnwu/Magisk/files/14167784/logcat.txt)

**Comment by yujincheng08** [comment]
This is because VPhoneGaGa is not loading nativebridge. Ask its developer to support it.
