### ISSUE TITLE
WiFi not working properly

### ISSUE THREAD

**Issue by a6680** [topjohnwu/Magisk#7761]
After trying to update to Magisk 27.0 (27001) on Android 10, WiFi still says "IP configuration failed" and WiFi doesn't work. However, with Magisk 26.4 (26400), the WiFi works fine. 
Device: Wayne (Xiaomi 6x) 
Android version: 10 (CarbonROM) 
Magisk version name: 27.0 
Magisk version code: 27001

**Comment by yujincheng08** [comment]
no log no fix.

**Comment by Zxqi47** [comment]
绷不住了，为什么wifi会断啊，哭死
