### ISSUE TITLE
Direct Install - Unable to find preeinit dir

### ISSUE THREAD

**Issue by albgen** [topjohnwu/Magisk#7766]
[magisk_log_2024-02-06T15.28.03.log](https://github.com/topjohnwu/Magisk/files/14181638/magisk_log_2024-02-06T15.28.03.log)
[magisk_install_log_2024-02-06T15.27.42.log](https://github.com/topjohnwu/Magisk/files/14181639/magisk_install_log_2024-02-06T15.27.42.log)

Device: Woopket k52
Android version: 13
Magisk version name: v27.0
Magisk version code: 27000

This box is rooted by default.
Just tried the direct install and seems it is patched but it does not work.
![image](https://github.com/topjohnwu/Magisk/assets/7231968/2960b377-b16c-469e-bc4e-b642a7b08584)

**Comment by canyie** [comment]
Close because you are not using the latest debug build

**Comment by albgen** [comment]
where to get it or should i build it?

**Comment by canyie** [comment]
https://raw.githubusercontent.com/topjohnwu/magisk-files/canary/app-debug.apk

Flash image patched by this build, reboot, try to execute /sbin/su and upload /cache/magisk.log
