### ISSUE TITLE
su request times out when User Authentication is enabled

### ISSUE THREAD

**Issue by nathanlepori** [topjohnwu/Magisk#7770]
Device: OnePlus Open (CPH2551)
Android version: 13
Magisk version name: 3d91a561
Magisk version code: 27001

When User Authentication is enabled `su` hangs for about a minute after the fingerprint read and then displays "\<App name\> was denied Superuser rights". If using a terminal like adb shell or Termux the message "Permission denied" is also shown when the request times out. The timeout happens regardless of the app and changing the request timeout in Magisk settings doesn't make a difference (currently set to the default 10s).
The issue happens regardless of whether there are modules installed or not, and regardless of the duration chosen when root is requested. Disabling User Authentication immediately fixes the issue.
Logs:
[magisk_log_2024-02-07T15.03.07.log](https://github.com/topjohnwu/Magisk/files/14194882/magisk_log_2024-02-07T15.03.07.log)

**Comment by 176-85-44-91** [comment]
Same issue here, magisk 27.0 (27000), android 12 (oxygen os 12), oneplus 7 pro, similarly, disabling user authentication fixes the issue right away.

**Comment by canyie** [comment]
Try #7577?

**Comment by nathanlepori** [comment]
Hi @canyie in my case it looks a bit different, enabling user authentication does bring up the biometrics dialog and after scanning the option gets enabled correctly. That tells me that SystemUI does support biometrics on OnePlus ROMs but please correct me if I'm wrong here. Anyway I will play around with the build you linked to see if it changes anything.
Thank you :)

**Comment by CBush88** [comment]
OnePlus 8 user, I assume this is the issue I've been facing.  The last working Magisk version for me is 26.3.  26.4 and 27 cause root requests to time out.

**Comment by aviraxp** [comment]
Seems only happens on oneplus roms?

**Comment by nathanlepori** [comment]
Was able to build and install #7577 and indeed using "Magisk Provide" mode User Authentication works fine. I guess there's something weird going on with OnePlus' implementation of SystemUI when it comes to biometrics

**Comment by xerta555** [comment]
Ah, glad to see nathanlepori took care to open a ticket to cover this problem
Exactly the same problem is happening on my end on my OnePlus device.
I can't say exactly which version the problem started with, as I discovered it completely by accident

**Comment by Ujj11hb** [comment]
#7577

**Comment by dxkf177** [comment]
> Device: OnePlus Open (CPH2551) Android version: 13 Magisk version name: [3d91a56](https://github.com/topjohnwu/Magisk/commit/3d91a561fe9b18505ac9f41d399ee181054b77c9) Magisk version code: 27001
> 
> When User Authentication is enabled `su` hangs for about a minute after the fingerprint read and then displays "<App name> was denied Superuser rights". If using a terminal like adb shell or Termux the message "Permission denied" is also shown when the request times out. The timeout happens regardless of the app and changing the request timeout in Magisk settings doesn't make a difference (currently set to the default 10s). The issue happens regardless of whether there are modules installed or not, and regardless of the duration chosen when root is requested. Disabling User Authentication immediately fixes the issue. Logs: [magisk_log_2024-02-07T15.03.07.log](https://github.com/topjohnwu/Magisk/files/14194882/magisk_log_2024-02-07T15.03.07.log)

**Comment by MisterFloppy** [comment]
> Seems only happens on oneplus roms?

No, its's also happening on Xiaomi roms, I'm affected in the exactly same manner as reported by dxkf177 before! Last try was at 07:54:00.

Device: Pocophone F1
Android version: 9
Magisk version name: https://github.com/topjohnwu/Magisk/commit/81658d45f7236fdbd535a6c3a06ae19bc08cb842(27002)
Magisk version code: 27002

Magisk log:
[magisk.log](https://github.com/topjohnwu/Magisk/files/15411806/magisk.log)
