### ISSUE TITLE
zygisk doesnt work on pixel 8 grapheneos

### ISSUE THREAD

**Issue by AskAlice** [topjohnwu/Magisk#7773]
[magisk.log](https://github.com/topjohnwu/Magisk/files/14208679/magisk.log)
[bootlog.txt](https://github.com/topjohnwu/Magisk/files/14208680/bootlog.txt)
Device: pixel 8 shiba
Android version: 14
Magisk version name: debug
Magisk version code: 27001

**Comment by yujincheng08** [comment]
Duplicated of #7593

**Comment by sabamdarif** [comment]
try this:-

https://github.com/sabamdarif/zygisk-for-grapheneos

https://github.com/PerformanC/ReZygisk/pull/53
