### ISSUE TITLE
WiFi not working

### ISSUE THREAD

**Issue by wahyu6070** [topjohnwu/Magisk#7776]
Device: redmi 4x (Santoni)
Android version: 9 - 10
Magisk version name:27.0
Magisk version code:27001

my wifi didn't work after installing magisk 17.0, but it returned to normal by installing magisk version 16.5

**Comment by Lamdarer** [comment]
I have the same issue:
Android version: 10
Magisk version name: 27.0
Magisk version code: 27000
Not sure why I have 27000 but that's what I got through the normal in-app update.
Also I guess [this](27.0) is/was related.

**Comment by wahyu6070** [comment]
[log.txt](https://github.com/topjohnwu/Magisk/files/14213976/log.txt)

**Comment by osm0sis** [comment]
#7764

**Comment by Lamdarer** [comment]
> #7764

Thank you, in the meantime is there an easy way to role back? i couldnt find any in the docs and I would prefer not to loose my configuration by reinstalling
