### ISSUE TITLE
Magisk manager crashes when install zip modules

### ISSUE THREAD

**Issue by Fingalzzz** [topjohnwu/Magisk#779]
Hi, I'm now on Magisk Manager 6.0.1 with Magisk v17.1
I was trying to install local zip modules, but it crashes after select the zip file and generate no log.
Install modules from Repo works perfectly.
I have tried reinstall the manager but it still not work.

**Comment by xxRaiyanxxYT** [comment]
@Fingalzzz
There is no way unless topjohnwu fixes it..........
