### ISSUE TITLE
Bootloop - Samsung Galaxy A12

### ISSUE THREAD

**Issue by SLAZZUU** [topjohnwu/Magisk#7799]
Device: Samsung Galaxy A12
Android version: 12
Magisk version name: 27.0 (debug)
Magisk version code:  27001

Followed all the steps in the installation guide: https://topjohnwu.github.io/Magisk/install.html#samsung-devices

[logcat.log](https://github.com/topjohnwu/Magisk/files/14240590/logcat.log)
[magisk_install_log_2024-02-12T14.52.46.log](https://github.com/topjohnwu/Magisk/files/14240594/magisk_install_log_2024-02-12T14.52.46.log)
[proc_mounts_before_magisk.log](https://github.com/topjohnwu/Magisk/files/14240597/proc_mounts_before_magisk.log)

**Comment by canyie** [comment]
Maybe related https://github.com/topjohnwu/Magisk/issues/7254#issuecomment-1932178001

**Comment by pewterbrass** [comment]
At least U4 binary won't work. I'm around 90% sure the device reboots because of an SMC call to the TEE when the inner (SignerVer02) signature check on boot.img fails. 

It might very well be an unintended reboot, as the device isn't supposed to just shut down when encountering an error in the orange state.

**Comment by pewterbrass** [comment]
See here for more info:

https://github.com/topjohnwu/Magisk/issues/7254#issuecomment-1938017793

**Comment by yujincheng08** [comment]
Duplicated of #7254

**Comment by zer0def** [comment]
It's worth remarking, that this issue isn't a direct duplicate of #7254, though it shares surface symptoms and some research about it was documented there. That said, this likely doesn't warrant re-opening.
