### ISSUE TITLE
Magisk zip files

### ISSUE THREAD

**Issue by nats63114** [topjohnwu/Magisk#781]
Just like to thank the fucking a-holes that put empty zip files to download as i had to everything over again on my phone trying to root it. Thanks again

**Comment by Didgeridoohan** [comment]
Very constructive post...

As long as you're downloading from the official source you should have no issue.

You can close this now, so that topjohnwu doesn't have to.

**Comment by nats63114** [comment]
I got i had to go through a diff. Website sry rooting this phone was
suppose to b easy as its the same one as i had before-last one broke-anyway
got a little frustrating this time.. I apologize
