### ISSUE TITLE
No imei or baseband after rooting Realme 9 RMX3388 (indian version of realme 9 se 5g)

### ISSUE THREAD

**Issue by JakaasJai69** [topjohnwu/Magisk#7814]
Device: Realme 9 RMX3388
Android version: 13
Magisk version name: Magisk Debug
Magisk version code: 27001

I downloaded magisk from github latest version (v27) and got stock rom with same specifications online (RMX3388export_11_F.08_2023110915340134.zip). ofcourse i already had unlocked my bootloader with deeptesting (at that time there was no problem).

I extracted boot and vbmeta and patched it with magisk and flashed vbmeta with --disable-verity --disable-verification. I restarted my phone and noticed the tile icons (shutter) are invisible. It took like 1 minute for them to get back but i though it was just because i have'nt completed the setup so i opened magisk and complted the setup and restarted the phone. But the when i opened shinzuku and it asked for root i gave it but nothing happned.

I restarted my phone again and it started working. But i noticied the no sim icon even tho i have my sim installed so i checked the status in about option of settings. It says "Imei sv unknown" then i checked my baseband it was also "unknown" for unkown reason.

i checked other forums for similar issues and got to know that magisk had a bug where it did not initilize the network files or something when rooted with magisk on mediatek devices. There was a fix which mentioned that deleting the /mnt/vendor/nvdata/md/NVRAM/NVD_IMEI folder did temporary fix the problem so i did that (ofcourse with backup) it did nothing so i restored the files.

I did'nt install custom recovery or custom rom or anything.

There is no difference between the unmagisked and magisked device since this issue started when i patched and flashed the boot image from stock rom and even if i remove it and flash the original, it does nothing but remove root.

[magisk_log_2024-02-15T23.40.57.log](https://github.com/topjohnwu/Magisk/files/14301004/magisk_log_2024-02-15T23.40.57.log)

will upload the logcat soon. Thanks

**Comment by JakaasJai69** [comment]
Instead of logcat i think kernal log is much important i saw network errors there. I am sharing theia log collection. I just hope there is nothing private there. 

[android.txt](https://github.com/topjohnwu/Magisk/files/14307200/android.txt)
[dumpsysSF_oplus.txt](https://github.com/topjohnwu/Magisk/files/14307203/dumpsysSF_oplus.txt)
[dumpsysSF.txt](https://github.com/topjohnwu/Magisk/files/14307204/dumpsysSF.txt)
[kernel.txt](https://github.com/topjohnwu/Magisk/files/14307205/kernel.txt)

**Comment by JakaasJai69** [comment]
I also noticed that i cannot go to stock recovery with patched boot but can go with original easily. I restarted into recovery with magisk and it started bootlooping. I had to go to fastboot mode to come out of loop.

**Comment by JakaasJai69** [comment]
[logcat_output.txt](https://github.com/topjohnwu/Magisk/files/14311719/logcat_output.txt)
Logcat, not from bootup but enough errors.

**Comment by pndwal** [comment]
Just a guess (I'm not a dev), but based on

> There is no difference between the unmagisked and magisked device since this issue started when i patched and flashed the boot image from stock rom and even if i remove it and flash the original, it does nothing but remove root

seems you mean flashing un-patched/boot doesn't fix...

Are you certain downloaded ROM is exact version match for current loaded ROM?... Because symptoms are typical of boot image mismatch. Critically, /boot includes the kernel.

(You could try after flashing the complete downloaded ROM.)

**Comment by JakaasJai69** [comment]
>> Are you certain downloaded ROM is exact version match for current loaded ROM?... Because symptoms are typical of boot image mismatch. Critically, /boot includes the kernel.
>> 
>> (You could try after flashing the complete downloaded ROM.)

I will certainly do it. That would be my first priority after backing up my imei and network essentials. But the problem is the recovery is also not working (it may be because of kernel) and I need to do it with either custom recovery or fastboot. I don't know if former is available for my device and fastboot will be a big hassle because I need to do it manually partation by partation. So, I need a mtk tool or something similar to flash my device. It would take a bit of time, because my exams are going on. So, let's see.
