### ISSUE TITLE
Zygisk fails to start (crashes zygote) on Android 15 DP1

### ISSUE THREAD

**Issue by KieronQuinn** [topjohnwu/Magisk#7818]
Device: Pixel 8 Pro (husky)
Android version: 15 DP1
Magisk version name: 27.0 (3d91a561)
Magisk version code: 27001

While Magisk works on Android 15 DP1, Zygisk causes zygote to crash and disables itself after 3 attempts:

> W Magisk  : zygote crashes too many times, rolling-back

Relevant native crash of zygote64:

```
02-16 23:11:27.462  1579  1579 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-16 23:11:27.462  1579  1579 F DEBUG   : Build fingerprint: 'google/husky_beta/husky:VanillaIceCream/AP31.240119.016/11414567:user/release-keys'
02-16 23:11:27.462  1579  1579 F DEBUG   : Revision: 'MP1.0'
02-16 23:11:27.462  1579  1579 F DEBUG   : ABI: 'arm64'
02-16 23:11:27.462  1579  1579 F DEBUG   : Timestamp: 2024-02-16 23:11:27.342063398+0000
02-16 23:11:27.462  1579  1579 F DEBUG   : Process uptime: 1s
02-16 23:11:27.462  1579  1579 F DEBUG   : Cmdline: zygote64
02-16 23:11:27.462  1579  1579 F DEBUG   : pid: 1504, tid: 1504, name: system_server  >>> zygote64 <<<
02-16 23:11:27.462  1579  1579 F DEBUG   : uid: 1000
02-16 23:11:27.462  1579  1579 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
02-16 23:11:27.462  1579  1579 F DEBUG   : pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
02-16 23:11:27.462  1579  1579 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
02-16 23:11:27.462  1579  1579 F DEBUG   : Cause: null pointer dereference
02-16 23:11:27.462  1579  1579 F DEBUG   :     x0  0000000000000000  x1  0000000000000000  x2  0000000000000000  x3  0000000000000010
02-16 23:11:27.462  1579  1579 F DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  000000000000004a  x7  7f7f7f7f7f7f7f7f
02-16 23:11:27.462  1579  1579 F DEBUG   :     x8  0000000000000000  x9  aeea3c66ca165d4e  x10 0000000000000000  x11 00000000f1ab6612
02-16 23:11:27.462  1157  1157 D AOC     : F1:MSG: controller.cc, 899: AudioOutCtrl: ipc: audio_output_tu, cmd ID: 0x00d1, tag: 0x13, rc: 0
02-16 23:11:27.462  1579  1579 F DEBUG   :     x12 b4000074cf871b60  x13 00000076f7705ac0  x14 b4000075ff859450  x15 0000007fe3ae26a0
02-16 23:11:27.462  1579  1579 F DEBUG   :     x16 00000074101b3398  x17 00000076d730e080  x18 00000076f8420000  x19 0000000000000000
02-16 23:11:27.462  1579  1579 F DEBUG   :     x20 0000007fe3ae2930  x21 0000000040380011  x22 0000000000000000  x23 b4000075ff859430
02-16 23:11:27.462  1579  1579 F DEBUG   :     x24 00000074101bc000  x25 0000007fe3ae313c  x26 00000073400500d0  x27 00000076f74d606d
02-16 23:11:27.462  1579  1579 F DEBUG   :     x28 00000074101b4a48  x29 0000000000000001
02-16 23:11:27.462  1579  1579 F DEBUG   :     lr  000000741019073c  sp  0000007fe3ae2880  pc  00000076d730e090  pst 0000000080001000
02-16 23:11:27.462  1579  1579 F DEBUG   : 2 total frames
02-16 23:11:27.462  1579  1579 F DEBUG   : backtrace:
02-16 23:11:27.462   911  1035 D audio_hw_cca: CCA setting: 0
02-16 23:11:27.462  1579  1579 F DEBUG   :       #00 pc 0000000000058090  /apex/com.android.runtime/lib64/bionic/libc.so (__strlen_aarch64+16) (BuildId: 3d7a1c7687593f77c7dd00e73a7b7109)
02-16 23:11:27.462   911  1035 D audio_hw_cca: CCA Unsupport: 0
02-16 23:11:27.462  1579  1579 F DEBUG   :       #01 pc 000000000000b738  /memfd:jit-cache (deleted)
```

Full tombstone: [tombstone_01.txt](https://github.com/topjohnwu/Magisk/files/14316880/tombstone_01.txt)

Magisk log: [magisk_log_2024-02-16T23.37.32.log.txt](https://github.com/topjohnwu/Magisk/files/14316893/magisk_log_2024-02-16T23.37.32.log.txt)

Full logcat: [dp1log-debug.txt](https://github.com/topjohnwu/Magisk/files/14316903/dp1log-debug.txt)

**Comment by canyie** [comment]
I noticed that you have installed modules such as Sui and LSPosed. Can you disable all modules and try again?

**Comment by KieronQuinn** [comment]
> I noticed that you have installed modules such as Sui and LSPosed. Can you disable all modules and try again?

You're right, it was LSposed. I'd assumed that a module couldn't cause a Zygisk hard crash but obviously I was mistaken.

**Comment by ABirHAsan123-beep** [comment]
> Device: Pixel 8 Pro (husky) Android version: 15 DP1 Magisk version name: 27.0 ([3d91a56](https://github.com/topjohnwu/Magisk/commit/3d91a561fe9b18505ac9f41d399ee181054b77c9)) Magisk version code: 27001
> 
> While Magisk works on Android 15 DP1, Zygisk causes zygote to crash and disables itself after 3 attempts:
> 
> > W Magisk  : zygote crashes too many times, rolling-back
> 
> Relevant native crash of zygote64:
> 
> ```
> 02-16 23:11:27.462  1579  1579 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 02-16 23:11:27.462  1579  1579 F DEBUG   : Build fingerprint: 'google/husky_beta/husky:VanillaIceCream/AP31.240119.016/11414567:user/release-keys'
> 02-16 23:11:27.462  1579  1579 F DEBUG   : Revision: 'MP1.0'
> 02-16 23:11:27.462  1579  1579 F DEBUG   : ABI: 'arm64'
> 02-16 23:11:27.462  1579  1579 F DEBUG   : Timestamp: 2024-02-16 23:11:27.342063398+0000
> 02-16 23:11:27.462  1579  1579 F DEBUG   : Process uptime: 1s
> 02-16 23:11:27.462  1579  1579 F DEBUG   : Cmdline: zygote64
> 02-16 23:11:27.462  1579  1579 F DEBUG   : pid: 1504, tid: 1504, name: system_server  >>> zygote64 <<<
> 02-16 23:11:27.462  1579  1579 F DEBUG   : uid: 1000
> 02-16 23:11:27.462  1579  1579 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
> 02-16 23:11:27.462  1579  1579 F DEBUG   : pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
> 02-16 23:11:27.462  1579  1579 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
> 02-16 23:11:27.462  1579  1579 F DEBUG   : Cause: null pointer dereference
> 02-16 23:11:27.462  1579  1579 F DEBUG   :     x0  0000000000000000  x1  0000000000000000  x2  0000000000000000  x3  0000000000000010
> 02-16 23:11:27.462  1579  1579 F DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  000000000000004a  x7  7f7f7f7f7f7f7f7f
> 02-16 23:11:27.462  1579  1579 F DEBUG   :     x8  0000000000000000  x9  aeea3c66ca165d4e  x10 0000000000000000  x11 00000000f1ab6612
> 02-16 23:11:27.462  1157  1157 D AOC     : F1:MSG: controller.cc, 899: AudioOutCtrl: ipc: audio_output_tu, cmd ID: 0x00d1, tag: 0x13, rc: 0
> 02-16 23:11:27.462  1579  1579 F DEBUG   :     x12 b4000074cf871b60  x13 00000076f7705ac0  x14 b4000075ff859450  x15 0000007fe3ae26a0
> 02-16 23:11:27.462  1579  1579 F DEBUG   :     x16 00000074101b3398  x17 00000076d730e080  x18 00000076f8420000  x19 0000000000000000
> 02-16 23:11:27.462  1579  1579 F DEBUG   :     x20 0000007fe3ae2930  x21 0000000040380011  x22 0000000000000000  x23 b4000075ff859430
> 02-16 23:11:27.462  1579  1579 F DEBUG   :     x24 00000074101bc000  x25 0000007fe3ae313c  x26 00000073400500d0  x27 00000076f74d606d
> 02-16 23:11:27.462  1579  1579 F DEBUG   :     x28 00000074101b4a48  x29 0000000000000001
> 02-16 23:11:27.462  1579  1579 F DEBUG   :     lr  000000741019073c  sp  0000007fe3ae2880  pc  00000076d730e090  pst 0000000080001000
> 02-16 23:11:27.462  1579  1579 F DEBUG   : 2 total frames
> 02-16 23:11:27.462  1579  1579 F DEBUG   : backtrace:
> 02-16 23:11:27.462   911  1035 D audio_hw_cca: CCA setting: 0
> 02-16 23:11:27.462  1579  1579 F DEBUG   :       #00 pc 0000000000058090  /apex/com.android.runtime/lib64/bionic/libc.so (__strlen_aarch64+16) (BuildId: 3d7a1c7687593f77c7dd00e73a7b7109)
> 02-16 23:11:27.462   911  1035 D audio_hw_cca: CCA Unsupport: 0
> 02-16 23:11:27.462  1579  1579 F DEBUG   :       #01 pc 000000000000b738  /memfd:jit-cache (deleted)
> ```
> 
> Full tombstone: [tombstone_01.txt](https://github.com/topjohnwu/Magisk/files/14316880/tombstone_01.txt)
> 
> Magisk log: [magisk_log_2024-02-16T23.37.32.log.txt](https://github.com/topjohnwu/Magisk/files/14316893/magisk_log_2024-02-16T23.37.32.log.txt)
> 
> Full logcat: [dp1log-debug.txt](https://github.com/topjohnwu/Magisk/files/14316903/dp1log-debug.txt)

**Comment by flobo09** [comment]
FYI, just for anyone finding this thread after upgrading to 15, Dreamland canary 97 works with DP15 as a lsposed replacement.
