### ISSUE TITLE
Magisk not working after 27.0 update

### ISSUE THREAD

**Issue by AmikadM** [topjohnwu/Magisk#7820]
Device: POCO F5
Android version: hyperos 1.0.2 xiaomi.eu Android 14
Magisk version code: 3d91a561 (27001) (D)

Magisk stopped working when I installed the 27.0 update.
I tried to re patch the boot file and re flashing it but the magisk app keeps showing I have no root.
I also tried to re install the 26.4 update and after that, it was working normaly.

[boot.img.zip](https://github.com/topjohnwu/Magisk/files/14320524/boot.img.zip)
[magisk_patched_marble_27_debug.img.zip](https://github.com/topjohnwu/Magisk/files/14320525/magisk_patched_marble_27_debug.img.zip)
[magisk_log_2024-02-18T00.16.52.log.zip](https://github.com/topjohnwu/Magisk/files/14320526/magisk_log_2024-02-18T00.16.52.log.zip)

**Comment by yujincheng08** [comment]
get a bugreport as soon as the phone reboots and send it.

**Comment by AmikadM** [comment]
Is that what you want ?
https://1drv.ms/u/s!AkVLk38u6NJdiHHellDUi1le-q2E

**Comment by canyie** [comment]
Can you run `adb shell "ps -A | grep magisk"` and send its output?

**Comment by canyie** [comment]
Seems to be a regression caused by commit 8d5b9e5.
Can you run `/debug_ramdisk/magisk su` and see if you can get root? If you can, please attach `/data/cache/magisk.log`

**Comment by AmikadM** [comment]
I don't know what IS supposed to happen when I run `/debug_ramdisk/magisk su` but it just executes without errors but won't allow root access.
[magisk.log](https://github.com/topjohnwu/Magisk/files/14322229/magisk.log)

**Comment by yujincheng08** [comment]
I highly suspect this is caused by the ROM you used. If this issue does not happen on official ROM, there's nothing we can do.

**Comment by vvb2060** [comment]
Try to use the stock ROM. If the issue still happen, please open a new issue.  
You could also try magisk alpha, I'm guessing it works partially.
