### ISSUE TITLE
SM-X115 Firmware Installation gives bootloop / Factory data reset solves the problem

### ISSUE THREAD

**Issue by Foufure13** [topjohnwu/Magisk#7828]
Device: SM-X115 OR Samsung tab A9
Android version: 13
Magisk version name: Magisk v27.0
Magisk version code: 27001

I encountered a problem after installing the firmware patch with magisk,
the tablet booted 2 times and displayed a bios error.
it gave me the choice of trying again to boot or factory data reset or see the logs.
![img_7141](https://github.com/topjohnwu/Magisk/assets/49339740/4ab25ac6-f8c2-4519-8c56-ba6959510eee)

(I'd already checked that the firmware was compatible by installing it without the patch, and had no problems).

only I've found that if you choose the Factory data reset option, it,
corrects the bootloop and the tablet works correctly.

Finally, if you reinstall magisk, the root option is available.

and root works correctly
I hope this will help you with this bug for future rooting.

[SM-X115_log-dmesg_withmagisk.txt](https://github.com/topjohnwu/Magisk/files/14334164/SM-X115_log-dmesg_withmagisk.txt)
[SM-X115_proc-mounts_NOmagisk.txt](https://github.com/topjohnwu/Magisk/files/14334165/SM-X115_proc-mounts_NOmagisk.txt)
[SM-X115_proc-mounts_withmagisk.txt](https://github.com/topjohnwu/Magisk/files/14334166/SM-X115_proc-mounts_withmagisk.txt)
[boot.img.zip](https://github.com/topjohnwu/Magisk/files/14334202/boot.img.zip)

**Comment by pndwal** [comment]
Are you following official instructions?... Because they clearly state:

> • Installing Magisk for the first time REQUIRES a full data wipe (this is NOT counting the data wipe when unlocking bootloader). Please make a backup your data.
> ...
> • Reboot to download mode. Open Odin on your PC, and flash magisk_patched.tar as AP, together with BL, CP, and CSC (NOT HOME_CSC because we want to wipe data) from the original firmware.
>
> • Your device should reboot automatically once Odin finished flashing. Agree to do a factory reset if asked.

**Comment by Foufure13** [comment]
> Are you following official instructions?... Because they clearly state:
> 
> > • Installing Magisk for the first time REQUIRES a full data wipe (this is NOT counting the data wipe when unlocking bootloader). Please make a backup your data.
> > ...
> > • Reboot to download mode. Open Odin on your PC, and flash magisk_patched.tar as AP, together with BL, CP, and CSC (NOT HOME_CSC because we want to wipe data) from the original firmware.
> > • Your device should reboot automatically once Odin finished flashing. Agree to do a factory reset if asked.



of course I rooted by following these steps
this isn't my first time rooting

**Comment by bright-aidar** [comment]
why u not write how u take root for this device sm-x115

**Comment by yackie828** [comment]
Fuck u
