### ISSUE TITLE
Zygisk didn't work on latest version 27

### ISSUE THREAD

**Issue by xElkomy** [topjohnwu/Magisk#7833]
the zygsik doesn't work on the lastversion on infinix note 10 pro device
![image](https://github.com/topjohnwu/Magisk/assets/46958133/f2ebd229-4c75-4ad4-b930-f813f0ba85d9)

Device: infinix note 10 pro
Android version: 11
Magisk version name:27.0
Magisk version code:27001

**Comment by itapi** [comment]
@yujincheng08  your're the most stupid supporter ever.....

**Comment by yujincheng08** [comment]
@itapi thank you. but issues without log are always closed unconditionally. maybe the stupid guy is you.

**Comment by yujincheng08** [comment]
also the readme has said "Only bug reports from Debug builds will be accepted". maybe you should first learn how to use your eyes.
