### ISSUE TITLE
not working on asus zenfone 4 a450cg t00q 

### ISSUE THREAD

**Issue by naveenjotron** [topjohnwu/Magisk#784]
DEVICE: asus_t00q
Architecture: intel x86
[magisk_install_log_20181118_225740.log](https://github.com/topjohnwu/Magisk/files/2593096/magisk_install_log_20181118_225740.log)
[magisk_install_log_20181118_231935.log](https://github.com/topjohnwu/Magisk/files/2593097/magisk_install_log_20181118_231935.log)
[boot.zip](https://github.com/topjohnwu/Magisk/files/2593098/boot.zip)

**Comment by i1itione** [comment]
It seems that the 1st gen. Intel platform Zenfone series doesn't support Magisk due to non standard boot image.

**Comment by naveenjotron** [comment]
Is there any way to make it working because many of us are still using 1st generation zenfones.

**Comment by naveenjotron** [comment]
found a way to unpack and repack zenfone images @topjohnwu 
[AndImgTool.zip](https://github.com/topjohnwu/Magisk/files/2660262/AndImgTool.zip)
 place AndImgTool.exe and boot image in same folder and type cmd
for unpack : AndImgTool.exe <ImageForExtract.img>
for pack : AndImgTool.exe <SourceDir>

**Comment by topjohnwu** [comment]
@naveenjotron since it's not using standard boot image formats and I don't have the phone, I will not support it. You can create a tool for your device and share it with others (if you can and if you want)

**Comment by naveenjotron** [comment]
@topjohnwu Then maybe you can show me how to patch boot.img .
