### ISSUE TITLE
Zygote/zygisk crash

### ISSUE THREAD

**Issue by KamioKamoko** [topjohnwu/Magisk#7847]
Device: infinix note 12
Android version: 13
Magisk version name: 3d91a561
Magisk version code:27001

My zygote/zygisk always crash when i boot up
[magisk_log_2024-02-24T16.44.42.log](https://github.com/topjohnwu/Magisk/files/14392360/magisk_log_2024-02-24T16.44.42.log)

Can anyone help me?

**Comment by KamioKamoko** [comment]
![Screenshot_20240224-163236](https://github.com/topjohnwu/Magisk/assets/161120900/f5d7d0f5-542b-4d58-869f-e166e265ea09)

Sorry i forgor to add screenshot

**Comment by yujincheng08** [comment]
Close because you didn't use the debug build.

And this is mostly not magisk's issue but caused by a specific zygisk module.
