### ISSUE TITLE
I have zygisk open but not work

### ISSUE THREAD

**Issue by BabyKingLeo** [topjohnwu/Magisk#7849]
Device: Samsung Galaxy S21
Android version:14
Magisk version name: app-debug.apk
Magisk version code: 27001

If someone can help me

![Screenshot_20240224_121010](https://github.com/topjohnwu/Magisk/assets/161122807/33f063ee-f8df-46b3-8603-5c91c59ebaca)
![Screenshot_20240224_121005](https://github.com/topjohnwu/Magisk/assets/161122807/aaa14971-a8c6-4791-824e-1ffe7161bac3)
![Screenshot_20240224_121001](https://github.com/topjohnwu/Magisk/assets/161122807/0aefd702-0aae-437c-b69d-6141ae4c8c2d)

**Comment by yujincheng08** [comment]
close because of no log.

**Comment by BabyKingLeo** [comment]
How to get log
