### ISSUE TITLE
Dual license magiskpolicy as LGPL

### ISSUE THREAD

**Issue by DreaminginCodeZH** [topjohnwu/Magisk#785]
First of all, thanks for your work about selinux-inject!

I'm recently trying to use `su`, `app_process` and `ServiceManager.addService()` to start a root Java process and do IPC with `Binder` with my app, but the new system service would require modification to the SElinux policy to allow app to bind to its binder interface, which is why I'll need sepolicy-inject.

The [original repo](https://bitbucket.org/joshua_brindle/sepolicy-inject) and [phhusson' fork](https://github.com/phhusson/sepolicy-inject) has been released into public domain because of the header in `sepolicy-inject.c`, but as I read through the commit history of the [magiskpolicy](https://github.com/topjohnwu/magiskpolicy) repo, that header was removed during a restructure of code so I have to assume from that point the code became proprietary. And when magiskpolicy is moved into magiskmanager, the whole project is licensed under GPL, which means anything linking against magiskpolicy will also need to be GPL.

So I was wondering if you could be so kind to dual license the magiskpolicy module as LGPL? This would enable me to create a LGPL [Android library for sepolicy-inject](https://github.com/DreaminginCodeZH/SePolicyInject) that exposes the sepolicy-inject functionality as JNI calls and used by people wishing to use `ServiceManager.addService()` to do IPC with `Binder` reliably, without requiring all the apps/libraries using it to also be GPL. Or if you could kindly agree to continue what the previous authors did and release your `sepolicy.{h,c}` into public domain, that would also be great! And I'll also release my library into public domain in this case.

Finally, I fully understand that your improvements on sepolicy-inject are your own work, so you have every right to reject such a request. But thanks for your great work again!

**Comment by topjohnwu** [comment]
Personally I will recommend you to not rely on bundling sepolicy modification libraries but instead rely on existing tools like `sepolicy` and `magiskpolicy`.
I will consider separating some parts of the code out and re-licencing it with LGPL though.

**Comment by topjohnwu** [comment]
And also, if you need any specific rules, please report to me and if it is reasonable I will add it to the magisk rules. Many devices out there simply don't allow live patches (sepolicy reloads), which is why Magisk has to do things pre-init nowadays.

**Comment by DreaminginCodeZH** [comment]
Thanks! The main reason for me to bundle sepolicy-inject was that some devices have su but not supolicy/magiskpolicy. I didn't expect some devices to disallow sepolicy reload though :/ Could you give me some examples?

The policy I intend to inject is "allow untrusted_app su binder { call, transfer }". If it were to be included in magiakpolicy, it should be something like "allow appdomain magisk binder { call transfer }" (found this in ChainFire's librootjava). But to support SuperSu and other su's I'll still need to bundle sepolicy-inject I guess.
