### ISSUE TITLE
I have zygisk open but no work

### ISSUE THREAD

**Issue by BabyKingLeo** [topjohnwu/Magisk#7850]
Device: Samsung galaxy s21
Android version:14
Magisk version name: app_debug.apk
Magisk version code: 27001
![Screenshot_20240224_121010](https://github.com/topjohnwu/Magisk/assets/161122807/3e1f602d-fa06-4467-aa1e-c4e1eb962157)
![Screenshot_20240224_121005](https://github.com/topjohnwu/Magisk/assets/161122807/0235bed1-54bf-4cd1-b919-f76238f5dc6a)
![Screenshot_20240224_121001](https://github.com/topjohnwu/Magisk/assets/161122807/1badecde-8c30-48c0-a292-1bbf426f4a48)
[magisk_log_2024-02-24T15.46.47.log](https://github.com/topjohnwu/Magisk/files/14393031/magisk_log_2024-02-24T15.46.47.log)

**Comment by yujincheng08** [comment]
`zygote crashes too many times, rolling-back`
this is because one of your zygisk module crashes zygote. its not magisk's issue. so disable all modules and find out which one causes it.
