### ISSUE TITLE
[BUG]: Magisk App Cannot Be Hidden 4d5510be-alpha (27001)

### ISSUE THREAD

**Issue by adrianmmiller** [topjohnwu/Magisk#7853]
Device: Pixel 6 Pro
Android version: 14
Magisk version name: 4d5510b-alpha
Magisk version code: 27001

Updated from within 2c6adbc-alpha (27000) to 4d5510b-alpha (27001)

Upon launch of 27001, message stating i would need to download full magisk.

Removed 27001 app, installed clean, launched, tried hiding, again met message i would need to download full magisk.

For now have left i have left magisk app unhidden, working fine....

**Comment by yujincheng08** [comment]
no alpha support here.
