### ISSUE TITLE
Root not found after flashing patched boot img

### ISSUE THREAD

**Issue by remozaza** [topjohnwu/Magisk#7858]
Device: Redmi Note 13 (sapphiren )
Android version:13
Magisk version name:27001
Magisk version code:27001 
I tried rooting with a patch it worked but I want Magisk.
And I'll include the log file too
[magisk_log_2024-02-26T00.42.28.txt](https://github.com/topjohnwu/Magisk/files/14398255/magisk_log_2024-02-26T00.42.28.txt)

I can't upload the boot.img I'll add a MediaFire link:
[https://www.mediafire.com/file/ktyqkcxo2jmku7r/boot_a/file](url)

**Comment by yujincheng08** [comment]
try #7685

**Comment by remozaza** [comment]
> try #7685

There is not a Tut there its a bunch of code

**Comment by remozaza** [comment]
![Screenshot_2024-02-26-22-56-57-612_com godevelopers OprekCek](https://github.com/topjohnwu/Magisk/assets/99085233/47375ef1-32a8-450f-80f0-96a39deacf18)
This what shows after I flash patched Magisk img still no root

**Comment by pndwal** [comment]
> > try #7685
> 
> There is not a Tut there its a bunch of code

Probably meant for you to try fixes for that... Get CI test build from artifacts in [Refactor magic mount](https://github.com/topjohnwu/Magisk/actions/runs/8010519385)

**Comment by remozaza** [comment]
> > > try #7685
> > 
> > 
> > There is not a Tut there its a bunch of code
> 
> Probably meant for you to try fixes for that... Get CI test build from artifacts in actions: [Refactor magic mount](https://github.com/topjohnwu/Magisk/actions/runs/8010519385)

What to do now?
![Screenshot_2024-02-26-23-35-00-103_com android chrome](https://github.com/topjohnwu/Magisk/assets/99085233/6951d0bb-ec0f-48ac-be55-e2ab5d824bdc)

**Comment by remozaza** [comment]
Still doesn't work

**Comment by remozaza** [comment]
Got Magisk from ci build still no root

**Comment by pndwal** [comment]
> Got Magisk from ci build still no root

... https://github.com/topjohnwu/Magisk/pull/7685 is clearly a WIP, but there have been other mount related fixes since the CI build you tried... You could try later CI builds in Actions or just wait for Devs to respond here.

**Comment by canyie** [comment]
Please grab a bug report: https://developer.android.com/studio/debug/bug-report

**Comment by remozaza** [comment]
Oh I found out how I just gotta tap CPU section alot of times here is my bug report zip file; https://www.mediafire.com/file/smlm1zpwp1e37gm/bugreport-2024-03-03-224344.zip/file

**Comment by canyie** [comment]
Hmmm, no magiskd, no magisk mount on the init namespace.
Can you fully shutdown the phone, connect it to the PC, run `adb bugreport`, turn it on again, then upload the generated bugreport file? I need to see earlier logs.

**Comment by remozaza** [comment]
> Hmmm, no magiskd, no magisk mount on the init namespace. Can you fully shutdown the phone, connect it to the PC, run `adb bugreport`, turn it on again, then upload the generated bugreport file? I need to see earlier logs.

Ok will do

**Comment by b0l5** [comment]
I have exactly the same problem.  I did the updates and tried to upload the new boot.img file again.  I do everything correctly, i.e. I create a new boot.img file using magisk, then I flash it, but Magisk still doesn't fully work.

![Screenshot_2024-03-15-23-12-24-30_785cfb1f0fb0c9a2030c9b38a1c3479a.jpg](https://github.com/topjohnwu/Magisk/assets/65984817/a1e58895-f613-4822-a615-62b779cbe4fb)

**Comment by pndwal** [comment]
> Ok will do

Well?
