### ISSUE TITLE
SEPolicy rules not loaded when installing modules via CLI

### ISSUE THREAD

**Issue by programminghoch10** [topjohnwu/Magisk#7861]
Device: `gts4lv` and `beyond2lte`
Android version: `13` / `14` (both LineageOS)
Magisk version name: `7e9abe6e (27001) (D)`
Magisk version code: 27001

When installing a module using the CLI command `magisk --install-module` the module's SELinux rules are not installed correctly, yet the installation completes "successfully".

I noticed this since I am using the CLI command during development for quick and automated testing.
In this case: [ViPER4AndroidRepackaged](https://github.com/programminghoch10/ViPER4AndroidRepackaged)

Installing in the app:
```
- Extracting module files
 < lots of module related stuff >
- Installing custom sepolicy rules
- Done
```
[full app install log](https://github.com/topjohnwu/Magisk/files/14407951/module_install_app.txt)

Installing via CLI:
```
- Extracting module files
 < lots of module related stuff >
- Installing custom sepolicy rules
- Unable to find preinit dir
- Done
```
[full cli install log](https://github.com/topjohnwu/Magisk/files/14407954/module_install_cli.txt)

_Side Note: wouldn't it be a good idea to also show stderr on the cli?_

So the result it that the module won't work  when installed via CLI, but does work when installed via the app.

[here](https://github.com/topjohnwu/Magisk/files/14408003/magisk_log_2024-02-26T18.09.07.log) is the magisk app log of both installations done one after another. I had two more modules installed, but disabled.

**Comment by yujincheng08** [comment]
use `su -M` instead.

**Comment by programminghoch10** [comment]
> use `su -M` instead.

Thanks, that works. I've adapted my deploy script for this.

However wouldn't it be an useful enhancement to do this by default inside the `magisk --install-module` command?

**Comment by Dhp668** [comment]
> use `su -M` instead.

what is su-M？
