### ISSUE TITLE
Stuck "Download" when trying to flash patched magisk boot.img

### ISSUE THREAD

**Issue by KevinAdhaikal** [topjohnwu/Magisk#7866]
Hello, i want to root my Phone, i just patch my boot-sign.img using Magisk Manager.
when i am flashing patched boot-sign.img by Magisk Manager, using Research Download. but its stuck at "Downloading"

when i trying to search google, i found this forum: https://www.hovatek.com/forum/thread-27355.html
its says "fdl2 seems to contain an spd signature, fdl1 doesn't (at least to the little i'm aware of)"

so, should i patch fdl2-sign.bin or not?

Device: Evercross U6
Chipset: Spreadtrum SC9850
Android version: 7.0 (Nougat)
Magisk version name: 27001
Magisk version code: 27001

**Comment by pndwal** [comment]
Please say if you can't simply find or patch boot.img or why it won't work...

Where are instructions to patch fdl2-sign.bin?

**Comment by KevinAdhaikal** [comment]
> Please say if you can't simply find or patch boot.img or why it won't work...
> 
> Where are instructions to patch fdl2-sign.bin?

hmmmm... i dont know

**Comment by KevinAdhaikal** [comment]
> Please say if you can't simply find or patch boot.img or why it won't work...
> 
> Where are instructions to patch fdl2-sign.bin?

and btw, i did patch boot-sign.img, but when i do flash it, its stuck at "Downloading"
i am using research download

**Comment by KevinAdhaikal** [comment]
when i try to unpack the .CPB file, its says "boot-sign.img" not "boot.img"

**Comment by pndwal** [comment]
I have no Idea why you think that's needed then...

As official instructions indicate, you need to locate your current ROM, extract boot.img then patch and flash that... Magisk must be installed in ramdisk and patching injects magiskinit there...

How is there an issue if you haven't tried to install Magisk properly??

**Comment by KevinAdhaikal** [comment]
I recorded from start to finish, is there something wrong?
https://github.com/topjohnwu/Magisk/assets/109958650/0bf436f9-81e1-47cf-ac45-f1667886a69a

**Comment by pndwal** [comment]
Fastboot?

**Comment by KevinAdhaikal** [comment]
> Fastboot?

stuck at sending

**Comment by pndwal** [comment]
How do you unlock bootloader from Developer settings??... Please show this... Generally it only "allows" bootloader unlock!!...

**Comment by KevinAdhaikal** [comment]
> How do you unlock bootloader from Developer settings??... Please show this... Generally it only "allows" bootloader unlock!!...

oh, i am sorry, the text is "OEM Unlocking"
but, the description is "Allow the bootloader to be unlocked"

**Comment by yujincheng08** [comment]
so its not magisk's issue.

**Comment by KevinAdhaikal** [comment]
but, when i do `fastboot oem device-info` its not responding
and yeah, i am using `adb reboot bootloader`
i dont know why, when i do `adb reboot fastboot` its just restart
