### ISSUE TITLE
Error `Unable to find preinit dir` when installing Shamiko from magisk CLI

### ISSUE THREAD

**Issue by austrisu** [topjohnwu/Magisk#7868]
Device: Pixel 3a
Android version: Android 12 and Android 11
Magisk version name: 27001 (D)
Magisk version code: 27001 (D)

Device: AVD emulator x64 with playstore
Android version: api33
Magisk version name: 27001 (D)
Magisk version code: 27001 (D)

## Issue

When installing Shamiko from CLI I got the message `Unable to find preinit dir`. The error seems to occur because the preinit directory is not found in `/proc/mounts`. I have checked `/proc/mounts` from the root shell I am in and this directory is nowhere to be found. Magisk Alpha was also affected by this but fixed it in the latest release.

```
# magisk --install-module /storage/self/primary/Download/Shamiko-v1.0.1-300-release.zip
- Device is system-as-root
***********************
 Shamiko
 by LSPosed Developers
***********************
*******************
 Powered by Magisk
*******************
- Shamiko version v1.0.1 (300)
- Extracting verify.sh
- Verified META-INF/com/google/android/update-binary
- Verified customize.sh
- Verified verify.sh
- Installing from Magisk / KernelSU app
- Magisk version: 27001
- Device platform: x64
- Verified module.prop
- Verified sepolicy.rule
- Verified post-fs-data.sh
- Verified uninstall.sh
- Extracting zygisk libraries
- Verified zygisk/x86.so
- Verified zygisk/x86_64.so
- Verified machikado.x86
- これで勝ったと�?�うなよ―�?��??!!
- Installing custom sepolicy rules
- Unable to find preinit dir
- Done
```

**Comment by yujincheng08** [comment]
https://github.com/topjohnwu/Magisk/issues/7861#issuecomment-1964714610
