### ISSUE TITLE
[Feature Request]: Magisk Crashlog Support 

### ISSUE THREAD

**Issue by xxRaiyanxxYT** [topjohnwu/Magisk#788]
Hi, @topjohnwu
***i came up with a idea Adding magisk Crash log, Would be best huh? it will save the log file automatically when Magisk Crashes.***
                       ***--------Also-------***
Im Facing Magisk Crash While Adding a Local/Custom Module...
>The issue kinda Similar to  #779 and #791

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/blob/0784448c697282f8ccc60ffa0664249406d411bf/native/jni/daemon/log_daemon.cpp#L130

**Comment by xxRaiyanxxYT** [comment]
Yea Great Lol

**Comment by topjohnwu** [comment]
Magisk debug versions will already log tons of stuffs. It will also log all FATAL errors, so even daemon crashes should be recorded too.
