### ISSUE TITLE
Boot failure after March update

### ISSUE THREAD

**Issue by festum** [topjohnwu/Magisk#7896]
Encountered boot failure with Magisk patched `boot.img` after updating `raven-ota-ap1a.240305.019.a1-090960f8`. Magisk v27 was working good on `raven-uq1a.240205.002`. Tried with Magisk 27001, 27.0, 26.4, 26.1 and all failed on `ZygoteInit` even with all modules removed (`adb wait-for-device shell magisk --remove-modules -n`).

Possible related to [this](https://xdaforums.com/t/march-4-2024-ap1a-240305-019-a1-global-root-pixel-6-pro-raven.4352027/post-89383182) comment in XDA thread.

Device: `Google Pixel 6 Pro` (`raven`)
Android version: `14`
Magisk version name: 3d91a561
Magisk version code: 27001

boot [logcat.txt](https://github.com/topjohnwu/Magisk/files/14538574/logcat.txt)

**Comment by aviraxp** [comment]
`F linker  : CANNOT LINK EXECUTABLE "/system/bin/audioserver": library "android.hardware.audio.core.sounddose-V1-ndk.so" not found: needed by /system/lib64/libaudioprocessing.so in namespace (default)`

**Comment by festum** [comment]
Right, only V2 exists in `/system/lib64`. Unfortunately, I don't have system folder permission in boot stage. 

```
raven:/ $ ls /system/lib64/android.hardware.audio.core.sounddose-*
/system/lib64/android.hardware.audio.core.sounddose-V2-ndk.so
raven:/ $ su -c 'ln -s /system/lib64/android.hardware.audio.core.sounddose-V2-ndk.so /system/lib64/android.hardware.audio.core.sounddose-V1-ndk.so'
Permission denied
raven:/ $ magisk su -c 'ln -s /system/lib64/android.hardware.audio.core.sounddose-V2-ndk.so /system/lib64/android.hardware.audio.core.sounddose-V1-ndk.so'
Permission denied
```

The outdated module seems the culprit but somehow not been removed by `--remove-modules`. Maybe I didn't run this flag against latest (debug) Magisk.

```
Magisk  : module  : /debug_ramdisk/.magisk/worker/system/lib64/libaudioprocessing.so <- /debug_ramdisk/.magisk/modules/module_audiohq/system/lib64/libaudioprocessing.so
```

Re-run `adb wait-for-device shell magisk --remove-modules`, and it works now.

Many thanks, @aviraxp you saved my weekend.
