### ISSUE TITLE
after flashing boot.img magisk dont fully work

### ISSUE THREAD

**Issue by b0l5** [topjohnwu/Magisk#7914]
Hello, yesterday I did the update OS and tried to upload the new boot.img file again. I do everything correctly, i.e. Before update I turn off all mods, reboot OS, Update system > I create a new boot.img file using magisk form payload.bin, then I flash it, but Magisk still doesn't fully work.

![magisk_log_2024-03-16T19.11.07.zip](https://github.com/topjohnwu/Magisk/files/14624864/magisk_log_2024-03-16T19.11.07.zip)

![magisk_patched-27000_1aJMh.zip](https://github.com/topjohnwu/Magisk/files/14624865/magisk_patched-27000_1aJMh.zip)

![Screenshot_2024-03-15-23-12-24-30_785cfb1f0fb0c9a2030c9b38a1c3479a.jpg](https://github.com/topjohnwu/Magisk/assets/65984817/ee09ecd7-45e3-48ce-acab-efd2ac7038b0)

Device: Oneplus 8 pro
Android version: 13 
Magisk version name: Magisk
Magisk version code:27001

**Comment by KuronosuKami** [comment]
Make sure you're using the correct boot.img. 
I had the same problem. I was 100% sure I was using the correct boot.img, but somehow I wasn't, or Magisk didn't save it correctly after flashing it in-app, or SOMEthing. 
After I made sure, it worked.
Extract it again from the payload.bin.

**Comment by b0l5** [comment]
delete magisk.db solved my problem
