### ISSUE TITLE
Using Magisk for rooting

### ISSUE THREAD

**Issue by onuryurtturk** [topjohnwu/Magisk#792]
Hi everybody, how can I use Magisk for rooting which is done inside an application?  I think so, there isn't a document in wiki. Can you explain on some samples?

**Comment by onuryurtturk** [comment]
@dark-1 nope,thanks I know where I will find wiki. Wiki is too complex for mentioned topic. I don't know where I should start

**Comment by dark-1** [comment]
oops !!! sorry!!!
I thought it was for all users, Or at-least I remembered it was easy before...

Try this: https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445
Now this is tested .... 👍 

BR 👍

**Comment by Didgeridoohan** [comment]
Considering your other opened issue for the root shell APIs (libsu) and that the wiki is too complex, what exactly is it that you're trying to accomplish?
