### ISSUE TITLE
Can't hide the app v27002 canary

### ISSUE THREAD

**Issue by andigenn** [topjohnwu/Magisk#7921]
Device: Xiaomi Mi 8
Android version: 10
Magisk version name: canary
Magisk version code: 27002

Get failed toast when trying to hide the app v27002 canary and the app it is not hidden.
The debug version works.
[magisk_log_2024-03-19T12.05.19.log](https://github.com/topjohnwu/Magisk/files/14649683/magisk_log_2024-03-19T12.05.19.log)

**Comment by damjang** [comment]
Same problem here:
Device: Samsung Galaxy S21+ (SM-G996B)
Android version: 14
Magisk version name: canary
Magisk version code: 27002
I have also problem that Magisk not update from 27001, I have to unhide it and then can update. I can't see any log in Magisk: I cleared all logs, try to hide, but no logs generated.

**Comment by mik1011984** [comment]
Same problem here. Can't update without unhiding and Magisk fails to hide after update.

Device: Xiaomi Poco F3 Global (8GB/256GB)
Android version: 13 / LOS20
Magisk version name: canary
Magisk version code: 27002

**Comment by jeanrivera** [comment]
Same here, Canary V27002 it is not able to be hidden

**Comment by zzzabc1020** [comment]
[magisk_log_2024-03-20T01.33.45.log](https://github.com/topjohnwu/Magisk/files/14654259/magisk_log_2024-03-20T01.33.45.log)
![Screenshot_2024-03-20-01-03-20-287_com topjohnwu magisk](https://github.com/topjohnwu/Magisk/assets/157718556/ede30a2e-7012-4609-9bc9-b6d189ffe72a)
Same here, Canary V27002 it is not able to be hidden

**Comment by qwerty472123** [comment]
Same, the AndroidManifest.xml in stub.apk is not found

**Comment by KuronosuKami** [comment]
Same same :)

**Comment by Tryffin** [comment]
Device: RedMagic 8S Pro
Android version: 13
Magisk version name: canary
Magisk version code: 27002

Same here, while hiding and using 27001, failed to download 27002 via Manager. After unhidden, it could download and install 27002, but failed to hide it

**Comment by spookymyo** [comment]
Same

Pixel 8 Pro unlocked

**Comment by ForsakenRei** [comment]
Same issue here, but my case is I cannot upgrade since I didn't unhide it and it keep prompt upgrade to the full version. I already uninstalled the hidden one but will need reflash the patched boot img...

**Comment by M33FT** [comment]
Same problem. S23 Ultra | OFW 14

**Comment by shaharis** [comment]
Same problem, cannot hide. Had to uninstall the manager to be undetectable by banking app..

**Comment by EarthMa** [comment]
Same problem.
Device: Xiaomi: RedMi note12 Turbo
Android version: 13
Magisk version code: 27000

**Comment by otonieru** [comment]
Yes. Same problem like others. Can't hide the Canary version of Magisk App.

Device : Pixel 7 Pro
Android : 14, March Stable Release
Magisk Version : 27002

**Comment by YuruiHong** [comment]
Same problem.
Device: Xiaomi: RedMi K30i 5G
Android version: 13
Magisk version code: 27002

**Comment by vvb2060** [comment]
#7893
