### ISSUE TITLE
Sepolicy statement is not correctly prased after rust rewrite

### ISSUE THREAD

**Issue by aviraxp** [topjohnwu/Magisk#7929]
[    1.165436][T700295] magiskinit: sepolicy rule syntax error: allow zygote nsfs file { open read }

Device: Oneplus Ace 2 Pro
Android version: 14
Magisk version name: 27.2
Magisk version code: 27002

**Comment by yujincheng08** [comment]
efa49567fab5b7e0a0aff0b5cdc43e3f4d1f912c
