### ISSUE TITLE
 OpenHarmony 4.x system support

### ISSUE THREAD

**Issue by luzh0422** [topjohnwu/Magisk#7934]
Hello, is there any plan to support the OpenHarmony system?

Device: HUAWEI  Mate 60
Android version: OpenHarmony 4.x
Magisk version name: 27.2
Magisk version code: 27002

**Comment by yujincheng08** [comment]
No

**Comment by enessmr** [comment]
> Android version: OpenHarmony 4.x
It's An HUAWEI system. Its not Fully Android.

**Comment by enessmr** [comment]
oops
