### ISSUE TITLE
Magisk patched init_boot doesn't boot on Pixel

### ISSUE THREAD

**Issue by TomBolger** [topjohnwu/Magisk#7946]
Device: Google Pixel 8 Pro
Android version: 14.0.0 (AP1A.240305.019.A1, Mar 2024)
Magisk version name: Canary
Magisk version code: 81658d45 (27002)

After updating to the March Android patch, I have lost root and cannot regain it. I can't pull a dmesg log because I'm not rooted, and I don't have any issues relating to Magisk because I cannot even get to the operating system with Magisk enabled. 

I took the stock init_boot image and patched it on the latest Magisk, both Stable and Canary, and in both cases, the patched boot image will not boot with fastboot boot X.img command. I have a friend with a Pixel 8 Pro and we have the same experience. If we fastboot flash the patched boot image, we get a boot loop, but flashing back to stock init_boot boots back to an unrooted state.

**Comment by callmejay758** [comment]
Can confirm this is the case on my Pixel 7 as well.

**Comment by osm0sis** [comment]
Worked fine for me on my Pixel 8 Pro. I successfully used Install to Inactive slot even

**Comment by osm0sis** [comment]
@TomBolger maybe try Debug version instead of Canary and report back. Seems like the only difference here.
