### ISSUE TITLE
MagiskHide not quick enough, bring toggle back as option?

### ISSUE THREAD

**Issue by thermatk** [topjohnwu/Magisk#795]
Hello!
I have a curious case with two interconnected apps working great with MagiskHide separately, but detecting root when one calls the other via Intent. I'm getting sure it's a hiding speed issue and as a solution I would be very thankful if you would give back the option to manually toggle root temporarily in a future update 👍 

More details:
I have to use the [Secure Mail](https://play.google.com/store/apps/details?id=com.citrix.mail.droid) by Citrix, which can only open attachments through [QuickEdit](https://play.google.com/store/apps/details?id=com.citrix.worxedit.xenmobile). Both apps fail to start with root enabled, both start when MagiskHide enabled, both start when I just loose root after kernel update (don't even have to repackage Magisk Manager). Yet Quick Edit detects root and fails if started by opening an attachment in Secure Mail. A temporary root toggle or at least a cli command to manually unmount Magisk would solve the issue.

**Comment by Didgeridoohan** [comment]
Have you tested the apps with the new and improved MagiskHide in the latest Canary (17317)?

**Comment by thermatk** [comment]
Sure thing, even tried the sh-hide alternative

**Comment by Didgeridoohan** [comment]
Ok... How about a Canary debug log and a logcat or a strace showing the detection happening. If there's anything that can be done about it, as much info as possible is necessary.

I can't speak for @topjohnwu, of course, but I really doubt there'll be a return of the root toggle. I don't think it'd even be if any use anymore.

**Comment by topjohnwu** [comment]
@thermatk I'm pretty sure the new MagiskHide targeting method in the latest Canary will cover your case.
