### ISSUE TITLE
Can't update to full canary or debug 27002.

### ISSUE THREAD

**Issue by TonyTall** [topjohnwu/Magisk#7952]
Device: Oneplus 8T
Android version: 14
Magisk version name: debug
Magisk version code: 27002

I tried to recover root after full update of my firmware. 
Before updating I had the canary 27001 hidden magisk. 

After updating I flashed latest magisk.zip and then tried to update to full magisk but it could not to download and install it. 

How can I recover my root? 

![Screenshot_2024-03-31-11-08-08-37_d0dfe873020ed1a39e22eb279aa8243e](https://github.com/topjohnwu/Magisk/assets/63284196/9a0834f6-cd74-4705-9273-440d93341751)
![Screenshot_2024-03-31-11-08-16-46_d0dfe873020ed1a39e22eb279aa8243e](https://github.com/topjohnwu/Magisk/assets/63284196/98e352fc-6427-442b-99b7-c1f1ce4f9235)
![Screenshot_2024-03-31-11-09-02-62_785cfb1f0fb0c9a2030c9b38a1c3479a](https://github.com/topjohnwu/Magisk/assets/63284196/fe9ae724-98e0-423e-9e9e-4dfd310d4cc3)

[magisk_log_2024-03-31T11.09.07.log](https://github.com/topjohnwu/Magisk/files/14814618/magisk_log_2024-03-31T11.09.07.log)

**Comment by JasonKhew96** [comment]
https://github.com/topjohnwu/Magisk/issues/7921
