### ISSUE TITLE
denylist not showing apps in other users

### ISSUE THREAD

**Issue by aruskkk** [topjohnwu/Magisk#7959]
Device: google pixel 7A
Android version: 14
Magisk version name: debug
Magisk version code: 27002

(magisk settings) (zygisk enabled)
Multiuser mode: DEVICE OWNER MANAGED
mount namespace mode: GLOBAL NAMESPACE
Superuser access: APPS & ADB
AUTOMATIC Response: Grant

I have another user on my device with facebook installed, when i go to the main user profile and go to denylist, facebook installed in the other user will not appear(same with all apps in other users) ive tried downgrading my device to see if that was problem but issue still persists, Thanks. (everything was working fine last week with these settings, my pixel had a update when i wasnt using it and these issues happened)

**Comment by aruskkk** [comment]
i have no modules installed, ive tried rebooting hundreds of times and factory resetting it and it did not fix it. XDA forums did not have any answers either

**Comment by aruskkk** [comment]
[magisk_log_2024-04-01T09.03.25.log](https://github.com/topjohnwu/Magisk/files/14823652/magisk_log_2024-04-01T09.03.25.log)

**Comment by 5thdesert** [comment]
> i have no modules installed, ive tried rebooting hundreds of times and factory resetting it and it did not fix it. XDA forums did not have any answers either

Dude you need to download the module by yourself
