### ISSUE TITLE
Direct update 27002 freezed app, then repatch boot.img causing boot loop

### ISSUE THREAD

**Issue by zevozki** [topjohnwu/Magisk#7966]
Device: Oneplus 10 Pro
Android version:13
Magisk version name: canary, debug
Magisk version code: 27002

Today I received update notification to install 27002 and installed and its freezed. force closed reopen ist freez. I had to uninstall and restart the device then BOOT LOOP at oneplus logo.
I flashed stock boot.img its working fine. then started doing rooting process again following the guide (used canary and Debug app). After flashing the patched image again the device go in boot loop. 

this is first time using github to report. so apologies if I did something wrong. I am unable to get logs due the device is not accessable during patching.

**Comment by freebrowser1** [comment]
One note here: Never use beta / canary apps for rooting a 'production' device.

Anyway, which commands did you send to the device ?

**Comment by zevozki** [comment]
I moved from stable to canary due to earlier stable build didnt pass safetynet i was despreate to use my banking app. Since then i forget to switch back to stable until this latest canary build 27002. 

I used **Boot patch.img** not flash

**Comment by freebrowser1** [comment]
Maybe install [Island](https://github.com/oasisfeng/island) which creates a 'work profile'.
Configure Magisk that only the main user has root access.
Install the banking app into the Island (work profile).
I've never tried, but that may work.

**Comment by zevozki** [comment]
I

> Maybe install [Island](https://github.com/oasisfeng/island) which creates a 'work profile'. Configure Magisk that only the main user has root access. Install the banking app into the Island (work profile). I've never tried, but that may work.

Intersting. I will keep an eye on this to learn more. So far im back to stable 27000.
