### ISSUE TITLE
Can't hide magisk manager

### ISSUE THREAD

**Issue by vanrzuf** [topjohnwu/Magisk#7978]
Device: OnePlus 6
Android version: 11
Magisk version name: 81658d45
Magisk version code: 27002
After update to 27002 i can't hide magisk manager. It just says "Failed!" in toast.

04-06 18:10:06.849  5166  5211 D OpenGLRenderer: endAllActiveAnimators on 0x66363a65d0 (RippleDrawable) with handle 0x655638bc60
04-06 18:10:06.865  5166  5219 W PackageParsing: Failed to parse /data/user/0/com.topjohnwu.magisk/cache/stub.apk
04-06 18:10:06.865  5166  5219 W PackageParsing: java.io.FileNotFoundException: AndroidManifest.xml
04-06 18:10:06.865  5166  5219 W PackageParsing:        at android.content.res.ApkAssets.nativeOpenXml(Native Method)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at android.content.res.ApkAssets.openXml(ApkAssets.java:376)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at android.content.pm.parsing.ApkLiteParseUtils.parseApkLiteInner(ApkLiteParseUtils.java:245)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at android.content.pm.parsing.ApkLiteParseUtils.parseApkLite(ApkLiteParseUtils.java:212)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at android.content.pm.parsing.ApkLiteParseUtils.parseMonolithicPackageLite(ApkLiteParseUtils.java:89)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at android.content.pm.parsing.ParsingPackageUtils.parseMonolithicPackage(ParsingPackageUtils.java:327)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at android.content.pm.parsing.ParsingPackageUtils.parsePackage(ParsingPackageUtils.java:242)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at android.content.pm.parsing.ParsingPackageUtils.parseDefault(ParsingPackageUtils.java:181)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:6104)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at a.P8.g(SourceFile:10)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at a.P8.F(SourceFile:306)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at a.XB.c(SourceFile:35)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at a.xp.e(SourceFile:6)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at a.UH.run(SourceFile:104)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at a.VM.run(SourceFile:33)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at a.LA.run(SourceFile:3)
04-06 18:10:06.865  5166  5219 W PackageParsing:        at a.Lf.run(SourceFile:92)
04-06 18:10:09.753  2253  2253 D QtiCarrierConfigHelper: WARNING, no carrier configs on phone Id: 0
04-06 18:10:09.882  1204  1390 I ThermalEngine: Monitor : quiet_therm = 33333, msm_therm = 34411, xo_therm = 34852, battery_therm = 314,current_now = -426000 
04-06 18:10:10.419  1091  7606 W NotificationService: Toast already killed. pkg=com.topjohnwu.magisk token=android.os.BinderProxy@3b76753
04-06 18:10:11.180  2224  2835 D QCNEJ/WlanStaInfoRelay: Received action: android.net.wifi.RSSI_CHANGED

**Comment by yujincheng08** [comment]
Fixed by 7abe635de92b41f989f1043781c7cce82c06b40d
