### ISSUE TITLE
High compression mode removed? 

### ISSUE THREAD

**Issue by aadmiral** [topjohnwu/Magisk#798]
High compression mode was removed at 6add682 without notice? There's also no apparent patch notes for why.  That feature is the only way I'm able to get Magisk on my SM-T530NU, so I can't update to anything higher than 16.7. (Auto update in manager sends me to bootloop)

**Comment by topjohnwu** [comment]
@aadmiral it's too much of a burden for me to maintain, it complicates things quite a bit. I would consider adding it back if I can come up with a better idea.
