### ISSUE TITLE
Andoid 15 Beta 1 - broke zygisk

### ISSUE THREAD

**Issue by TQMatvey** [topjohnwu/Magisk#7985]
Device: Google Pixel 8
Android version: 15 Beta 1
Magisk version name: Debug
Magisk version code: 81658d45 27002 (D)

after flashing Android 15 Beta 1 users (including myself) have encountered that Zygisk stopped working.

[magiskzyggiskcrash.txt](https://github.com/topjohnwu/Magisk/files/14953926/magiskzyggiskcrash.txt)

idk what to add, it just doesnt work lol, here is a full logcat from boot to opening app

**Comment by canyie** [comment]
This is most likely caused by LSPosed. Try disabling LSPosed and try again.

**Comment by ryangiggs901** [comment]
Same for me, is there any way to turn ZYGISK back on?
