### ISSUE TITLE
Commit "Support 32-bit magiskboot" breaks patching already-patched bootimg

### ISSUE THREAD

**Issue by aviraxp** [topjohnwu/Magisk#7988]
![image](https://github.com/topjohnwu/Magisk/assets/18079988/68bea253-30c6-4685-9b1b-d75e8198b72b)

Device: Oneplus Ace 2 Pro
Android version: 14
Magisk version name: 27.2
Magisk version code: 27002

**Comment by FuccDucc** [comment]
Yes, but actually, it breaks patching ANY .img related to rooting a phone.

Both tested: boot.img and init_boot.img, and i dont even have a OnePlus.

Errors:
![a](https://github.com/topjohnwu/Magisk/assets/61570793/b681e6ed-0f74-41fe-9fe4-8325e9e44db6)

**Comment by aviraxp** [comment]
unsupported file type

**Comment by anurag565** [comment]
Why no one is looking at above issues? Literally no one commented on that. I didn't write that but i have same issue and atleast comment on it
