### ISSUE TITLE
Enabling Zygisk causes bootloop on Infinix X688B

### ISSUE THREAD

**Issue by imxitiz** [topjohnwu/Magisk#7993]
Device: Infinix X688B
Android version: 11
Magisk version name: 27.0
Magisk version code: 27000

I am having issue after enabling Zygisk in Infinix X688B. Previously, everything was functioning smoothly, but after enabling Zygisk and rebooting, the device gets stuck on the boot logo for some time and again reboot. I am in its stock state with only the bootloader unlocked, maintaining the stock OS and recovery. Also not sure how to extract log file to provide, ADB isn't working on stock recovery as well. It's showing unauthorized.

Previously, reflashing the original boot.img resolved the booting issue, but wanted to enable Zygisk. So, wanted to solve this issue. Please guide me through, how can I solve this issue.

**Comment by Bronald88** [comment]
Doesn't Magisk come with a built-in Superuser?

**Comment by jvatechs** [comment]
Same things.
Magisk 26.4 work perfect, but 27.0 give me bootloop.

**Comment by jvatechs** [comment]
> Infinix X688B, phone?

Infinix, but model different.
I think that something wrong in the stock Infinix ROMs.

**Comment by kankou-Heile** [comment]
I am using the latest magisk alpha v28, and it works very smoothly, I recommend you to use the alpha and use the zygisk next module.
Device: hot 11 play
Code: X688B

**Comment by NCLnclNCL** [comment]
Use zygísk next/rezygisk
