### ISSUE TITLE
zygisk not work on Lineageos

### ISSUE THREAD

**Issue by MaddoxUp** [topjohnwu/Magisk#7995]
Zygisk does not work in the latest LineageOs system
When I try to use the zygisk feature on my phone, it causes me not to get into the system and reboot to fastboot. When I close the module in safe mode and reboot, I can enter normally, but Zygisk cannot be enabled
Device: LineageOs 21-20240317-NIGHTLY-guacamoleb
Android version: 14
Magisk Version Name: v27.0
Magisk version code:27002

**Comment by MaddoxUp** [comment]
This only appears on the latest lineageOS, and I had to brush back to the old version of lineageOS, even though I lost all the data.

**Comment by Powan21** [comment]
I've the same problem on OnePlus 7 pro too

**Comment by CarterTheCoder** [comment]
Disabling LSPosed module fixed this for me.

**Comment by Powan21** [comment]
Were you able to reactivate it after?  I don't want to do without lsposed

**Comment by Powan21** [comment]
Thanks for your answer

**Comment by creamIcec** [comment]
@Powan21 Try use this fork 
https://github.com/Admirepowered/LSPosed
It worked for my OnePlus 8T with latest LineageOS installed.
Original LSPosed is archived for too long and incompabilities can happen any time.
