### ISSUE TITLE
Upgraded lineageos ,then zygisk not working

### ISSUE THREAD

**Issue by Seshiria** [topjohnwu/Magisk#7998]
Device: oneplus 5
Android version: 14
Magisk version name: 27.0（27000）
Magisk version code: 01658d45（27002）（D）

Possibly related thread: android security update 2024/3/5 > 2024/4/5

[magisk_log_2024-04-19T02.02.28.log](https://github.com/topjohnwu/Magisk/files/15028877/magisk_log_2024-04-19T02.02.28.log)

![image](https://github.com/topjohnwu/Magisk/assets/57834968/b287473a-297a-482c-b54a-0a47a968576a)

**Comment by equinol** [comment]
Same issue, injection and new subsystem incompatibility.

**Comment by adamchap1** [comment]
Same issue here with latest Lineage, Oneplus 9 Pro and Magisk 27. It also killed a load of widgets from my home screen.

There was a bootloop after the Lineage dots spinning and the SIM PIN screen never appeared. Had to boot to safe mode, then reboot again just to get some sort of operational phone.

**Comment by canyie** [comment]
Most likely caused by LSPosed. Please disable LSPosed and try again.

**Comment by zovallo** [comment]
same issue. can anyone help. i need LSposed!

**Comment by Seshiria** [comment]
> same issue. can anyone help. i need LSposed!

You can try this [fork](https://github.com/LucisUrbe/LSPosed), or other
