### ISSUE TITLE
no documentation on manual mount

### ISSUE THREAD

**Issue by stangri** [topjohnwu/Magisk#8]
The http://forum.xda-developers.com/apps/magisk/magisk-details-dummies-to-developers-t3473486 reads: Auto Mount has to be enabled for Magisk to mount your files automatically. You can disable it and mount the files manually in the scripts (post-fs, post-fs-data, service). 

However there's no information on how to mount manually in the post-fs-data script. Please provide information on that.

**Comment by stangri** [comment]
@laggardkernel thanks for the explanation and the links. I'm sorry this is turning into the support thread, but I'm not getting any help at xda.

As far as I understand the bind_mount intended to only work for the existing directories in /system and I need to mount dynamically created entries in /magisk/modname/system/app. 

Here's what I'm trying to do: https://github.com/stangri/AppSystemizer/blob/master/common/post-fs-data.sh#L93-L107 (sorry, haven't mastered markdown to display those in the comment body).

I get the /magisk/AppSystemizer/system/app/* created but they don't get mounted. :(

I would appreciate any help.

**Comment by stangri** [comment]
I've looked at the travel function in the magic_mask.sh, but I'm confused by its use of both TMPDIR and DUMMDIR and don't seem to understand the code. 

If I need to manually mount something from /magisk/MyMod/system/priv-app in /system/priv-app/ in post-fs-data.sh, could you please tell me what I need to do in terms of bash commands?

**Comment by topjohnwu** [comment]
The command for bind mounting:
`mount -o bind <source> <target>`
Do what ever you want, as this is the point of scripts: Do what ever you want :)

**Comment by stangri** [comment]
@laggardkernel @topjohnwu here's where I run into problems: 
if I try to mount -o bind /magisk/module/system/priv-app/newappname /system/priv-app/newappname I get the error as /system/priv-app/newappname doesn't exist! 
If I mkdir -p /system/priv-app/newappname in my post-fs-data.sh, would it try to create a directory on a true /system?

**Comment by topjohnwu** [comment]
That is not possible :)
You have to clone a dummy, mount a mirror, mount things back.......
Just use my Magic mount to achieve it, this is the reason why Magisk exist lol

**Comment by stangri** [comment]
Is there maybe some directory I can create in post-fs.sh to indicate to magisk that I want to systemize it?

Alternatively, can I use some or all functions from scripts/magic_mask.sh? Is it the part with stages? Can I simply point one of your variables to point it to my module and leave the code as is?
