### ISSUE TITLE
can't mount system to write

### ISSUE THREAD

**Issue by LOVECHEN** [topjohnwu/Magisk#8010]
/dev/block/dm-8 on /system/bin/vold type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround)
/dev/block/dm-8 on /system/bin/vold_prepare_subdirs type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround)
/dev/block/dm-8 on /system/bin/vr type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround)
/dev/block/dm-8 on /system/bin/watchdogd type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround)
/dev/block/dm-8 on /system/bin/wificond type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround)
/dev/block/dm-8 on /system/bin/wm type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround)
/dev/block/dm-8 on /system/bin/xml2abx type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround)
/dev/block/dm-8 on /system/bin/ziptool type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround)
/dev/fuse on /mnt/installer/0/emulated type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other)
/dev/fuse on /mnt/androidwritable/0/emulated type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other)
/dev/fuse on /mnt/user/0/emulated type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other)
/dev/fuse on /storage/emulated type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other)
/dev/block/dm-49 on /mnt/pass_through/0/emulated type f2fs (rw,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,gc_merge,discard,discard_unit=block,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,barrier,extent_cache,mode=adaptive,active_logs=6,reserve_root=32768,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,checkpoint_merge,fsync_mode=nobarrier,memory=normal)
manet:/ # mount -o remount,rw /
'/dev/block/dm-8' is read-only
manet:/ # mount -o remount,rw /system
mount: '/system' not in /proc/mounts
1|manet:/ # whoami
root

Device: REDMI K70 PRO 23117RK66C
Android version: 14
OS version: HyperOS 1.0.13.0UNMCNXM
Kernel version : 6.1.25-android14-11-gab928514c75c-ab11207973
Magisk version name: 81658d45
Magisk version code: 27002

**Comment by yujincheng08** [comment]
EROFS (Enhanced **Read-Only** File System) is a lightweight **read-only** file system

**Comment by cocka11** [comment]
> /dev/block/dm-8 on /system/bin/vold type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround) /dev/block/dm-8 on /system/bin/vold_prepare_subdirs type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround) /dev/block/dm-8 on /system/bin/vr type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround) /dev/block/dm-8 on /system/bin/watchdogd type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround) /dev/block/dm-8 on /system/bin/wificond type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround) /dev/block/dm-8 on /system/bin/wm type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround) /dev/block/dm-8 on /system/bin/xml2abx type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround) /dev/block/dm-8 on /system/bin/ziptool type erofs (ro,seclabel,relatime,user_xattr,acl,cache_strategy=readaround) /dev/fuse on /mnt/installer/0/emulated type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other) /dev/fuse on /mnt/androidwritable/0/emulated type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other) /dev/fuse on /mnt/user/0/emulated type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other) /dev/fuse on /storage/emulated type fuse (rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other) /dev/block/dm-49 on /mnt/pass_through/0/emulated type f2fs (rw,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,gc_merge,discard,discard_unit=block,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,barrier,extent_cache,mode=adaptive,active_logs=6,reserve_root=32768,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,checkpoint_merge,fsync_mode=nobarrier,memory=normal) manet:/ # mount -o remount,rw / '/dev/block/dm-8' is read-only manet:/ # mount -o remount,rw /system mount: '/system' not in /proc/mounts 1|manet:/ # whoami root
> 
> Device: REDMI K70 PRO 23117RK66C Android version: 14 OS version: HyperOS 1.0.13.0UNMCNXM Kernel version : 6.1.25-android14-11-gab928514c75c-ab11207973 Magisk version name: [81658d4](https://github.com/topjohnwu/Magisk/commit/81658d45f7236fdbd535a6c3a06ae19bc08cb842) Magisk version code: 27002

Try mount -o rw,remount /
