### ISSUE TITLE
Magisk Debug - hide option not work

### ISSUE THREAD

**Issue by Bladius2024** [topjohnwu/Magisk#8017]
Device: Redmi Note 13 Pro 5G 
Android version: 14
Magisk version name: Debug
Magisk version code: 81658d45 (27002) (D)

**Comment by Bladius2024** [comment]
When trying to hide Magisk I get an error, no code, just the word "error".  Regardless of whether you use the default name or another name, hiding does not work.

**Comment by JasonKhew96** [comment]
duplicate https://github.com/topjohnwu/Magisk/issues/7921
