### ISSUE TITLE
Zygisk Does not work on Android 15

### ISSUE THREAD

**Issue by SL4F** [topjohnwu/Magisk#8021]
Device: Google Pixel 6 Pro 
Android version: VanillaIceCream (AP31.240322.027)
Magisk version name: Debug
Magisk version code: 81658d45:27002

Zygisk seems to work when there's no modules turned on, but as soon as any module that requires zygisk it breaks saying it's turned off when in the magisk settings it's on, but in the magisk tab on the main screen says it's off, this only happens when attempting to turn on any module that requires zygisk.

log with a zygisk module
[magisk_log_2024-05-01T13.18.41.log](https://github.com/topjohnwu/Magisk/files/15173155/magisk_log_2024-05-01T13.18.41.log)
log with non zygisk module
[magisk_log_2024-05-01T13.19.48.log](https://github.com/topjohnwu/Magisk/files/15173149/magisk_log_2024-05-01T13.19.48.log)
log without any modules
[magisk_log_2024-05-01T13.20.52.log](https://github.com/topjohnwu/Magisk/files/15173151/magisk_log_2024-05-01T13.20.52.log)

screenshots without zygisk module 
![Screenshot_20240501-132427](https://github.com/topjohnwu/Magisk/assets/52598005/52fbe6ee-df42-4bdf-8273-b574995cde22)
![Screenshot_20240501-132433](https://github.com/topjohnwu/Magisk/assets/52598005/27dc7833-d2d3-49a7-85db-081a664d4fd9)

screenshots with a zygisk plugin
![Screenshot_20240501-132552](https://github.com/topjohnwu/Magisk/assets/52598005/82477939-7ead-42e5-be39-a70e3e795c67)
![Screenshot_20240501-132608](https://github.com/topjohnwu/Magisk/assets/52598005/fd449586-4ac3-4239-ab06-461ff729ea51)
![Screenshot_20240501-132614](https://github.com/topjohnwu/Magisk/assets/52598005/45a487dc-7bec-46db-8db3-841c2cd579c0)

**Comment by canyie** [comment]
This is most likely caused by LSPosed, not us.

**Comment by SL4F** [comment]
> This is most likely caused by LSPosed, not us.

yet it's if I enable ANY zygisk module.

**Comment by SL4F** [comment]
> This is most likely caused by LSPosed, not us.

I even tried using zygisk next and it crashes when trying to launch itself.

**Comment by SL4F** [comment]
@canyie so it most likely is zygisk.

**Comment by SL4F** [comment]
why would lsposed add this inside the magisk app?
![Screenshot_20240501-132614~2](https://github.com/topjohnwu/Magisk/assets/52598005/dd45121c-88ac-49cb-b86d-b2841b375760)

**Comment by canyie** [comment]
Because LSPosed crashes the system, triggering Zygisk's bootloop protection mechanism which disables itself. There's nothing to do with us.

**Comment by SL4F** [comment]
> Because LSPosed crashes the system, triggering Zygisk's bootloop protection mechanism which disables itself. There's nothing to do with us.

@canyie this happens with every module that requires zygisk, you're telling me even a Pokemon go mod is supposed to crash the system? it happens with ANY module that requires zygisk, I used lsposed as an example yet you refuse to even look into it.

**Comment by canyie** [comment]
And then? You tested two modules and they don't work, so that's the reason you blame zygisk? The "log with a zygisk module" you provided only shows Zygisk's bootloop protection mechanism is triggered while you installed LSPosed which is known to be broken on Android 15, so I guess that's the reason, isn't that OK?

**Comment by busybox11** [comment]
Can confirm. LSPosed is broken, not only on A15 but also on newer A14 builds. Disabling it fixes Zygisk for me, which is annoying. I can understand why you would think Magisk would be the culprit here, but it's not.
