### ISSUE TITLE
Root Not Detected in Magisk After Flashing magisk_patched*.img

### ISSUE THREAD

**Issue by TheStxfan** [topjohnwu/Magisk#8038]
Device: Redmi Note 13 Pro Plus 5G Global
Android version: 13, 14 (I tried to do this since MIUI 14.0.2.0, now I am on HyperOS 1.0.4.0)
Magisk version name: Magisk-v27.0.apk (https://github.com/topjohnwu/Magisk/releases/download/v27.0/Magisk-v27.0.apk)
Magisk version code: v27.0

Magisk logs:
[magisk_log_2024-05-10T17.08.44.log](https://github.com/topjohnwu/Magisk/files/15275951/magisk_log_2024-05-10T17.08.44.log)
[magisk_install_log_2024-05-10T17.08.40.log](https://github.com/topjohnwu/Magisk/files/15275953/magisk_install_log_2024-05-10T17.08.40.log)

boot.img:
[boot.zip](https://github.com/topjohnwu/Magisk/files/15276075/boot.zip)

magisk_patched.img:
[magisk_patched-27000_FgQuh.zip](https://github.com/topjohnwu/Magisk/files/15276078/magisk_patched-27000_FgQuh.zip)

**Comment by canyie** [comment]
Hello, I cannot acccess the logs you provided. It seems your device has init_boot.img and you should patch that instead.
I'm closing this issue as this is stale and came from a stable build rather than debug builds.
