### ISSUE TITLE
Not able to enable zygisk on voltage os Android 14 (qpr2)

### ISSUE THREAD

**Issue by Ankit2502** [topjohnwu/Magisk#8050]
Device: redmipad (yunluo)
Android version: 14 (qpr2 update) voltage os
Magisk version name: 27.0
Magisk version code: 27002

Magisk info -
![Screenshot_20240514-145031](https://github.com/topjohnwu/Magisk/assets/89592455/611c59e7-746f-4115-928f-dd641c2cb2da)

Issue -

I have enabled zygisk in setting and even after tons of reboots, truning off and on, repatching boot.img I am just not able to enable zygisk hence not able to use any zygisk related module

Settings screen shot -
![Screenshot_20240514-145043](https://github.com/topjohnwu/Magisk/assets/89592455/55c654ac-2182-4a41-bb02-420539fd9d11)

Files related to bug-

Magisk logcat taken on termux by command (logcat -d -f /sdcard/logcat.txt)
[magisk_log_2024-05-14T11.23.21.log](https://github.com/topjohnwu/Magisk/files/15306178/magisk_log_2024-05-14T11.23.21.log)

dmesg.log taken by command on termux (su -c dmesg > dmesg.log)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/15306255/dmesg.log)

If need anything else pls tell me instead of archiving the issue..

Btw I do not have any module installed so -
![Screenshot_20240514-145924](https://github.com/topjohnwu/Magisk/assets/89592455/f3d50269-ee82-4cb7-b758-13cac0f3c96e)

**Comment by aviraxp** [comment]
https://github.com/VoltageOS/frameworks_base/commit/9e74a46b68369da7daafd3d2701c7b3069df1896

**Comment by deep0708** [comment]
I also faced this problem on voltage os QPR2 (Begonia aka Redmi Note 8 Pro). Tried everything zygisk is not working.

**Comment by Casualnoob** [comment]
A fix for this issue is discussed here: 

https://github.com/HuskyDG/magisk-files/issues/129 

Be aware that the above is an unofficial magisk fork, that has been seemingly abandoned. Nevertheless, this commit should resolve your issues: [[]](https://github.com/KitsuneMagisk/Magisk/pull/5/commits/9a0930cebb115e339dadd761fbf63d9413a4d5f3)(url)

**Comment by Ankit2502** [comment]
> 

> A fix for this issue is discussed here:
> 
> [HuskyDG/magisk-files#129](https://github.com/HuskyDG/magisk-files/issues/129)
> 
> Be aware that the above is an unofficial magisk fork, that has been seemingly abandoned. Nevertheless, this commit should resolve your issues: [here](https://github.com/KitsuneMagisk/Magisk/pull/5/commits/9a0930cebb115e339dadd761fbf63d9413a4d5f3)(url)

thanks a lot for this, i haven't tested as i switched to miui 13 a12 after getting fed up with all these issue on aosp
btw can we expect to get updates for that qpr2 supported kitsune mask as project is unmentained so can we expect that in magisk latest updates? (basicly for me almost all the time direct flashing kitsune gives bootloop)
