### ISSUE TITLE
Magisk cause wifi and speaker not work.

### ISSUE THREAD

**Issue by Hoshikawakaguya** [topjohnwu/Magisk#8058]
Device: Rakuten Mini (C330)
Android version: SparkOS13.4 (Android13)
Magisk version name: debug
Magisk version code: 27002

After install magisk, wifi and speaker do not work.
[logcat.txt](https://github.com/topjohnwu/Magisk/files/15322406/logcat.txt)
[magisk_log.log](https://github.com/topjohnwu/Magisk/files/15322408/magisk_log.log)

**Comment by vvb2060** [comment]
#7764

**Comment by Hoshikawakaguya** [comment]
Do you mean speaker is the same issue?
