### ISSUE TITLE
Magisk App Can't Start On Android 15(Xiaomi HyperOS)

### ISSUE THREAD

**Issue by hamjin** [topjohnwu/Magisk#8060]
Device: Redmi K60 Ultra
Android version: 15 Beta 1
Magisk version name: 81658d45
Magisk version code: 27002

Can't open Magisk app on the device, log is [canary.log](https://github.com/topjohnwu/Magisk/files/15334197/canary.log).

**Comment by PadMadoff** [comment]
I think this is a problem with Android versions above version 14. I have similar problem. Zigisk does not work, but there is root access.

**Comment by ProcessDuck** [comment]
we have the same codename device i have mi 13t pro (corot) i can patch boot img but when i flash it boots but does not work

**Comment by yujincheng08** [comment]
Looks like it's hyperOS's issue.
