### ISSUE TITLE
Cant root my Mi 13T Pro (corot)

### ISSUE THREAD

**Issue by ProcessDuck** [topjohnwu/Magisk#8065]
Device:Mi 13T Pro
Android version:14
Magisk version name:27002
Magisk version code:81658d45 (27002) (D)

there is no custom recoverys for mi 13t pro and because of that i patched my boot img. it said its pached and i moved it to my pc and i opened cmd and i rebooted my phone to bl. i typed fastboot flash boot_a patched.img and fastboot flash boot_b patched.img.
and it said thats flashed. i rebooted my phone and it booted normally without root. and yes i download my current hyperos rom and extracted the right boot img.

**Comment by pndwal** [comment]
Shouldn't you be patching/flashing init_boot.img for your device per instructions?

**Comment by ProcessDuck** [comment]
> Shouldn't you be patching/flashing init_boot.img for your device per instructions? (There's generally no generic ramdisk in boot.img of devices launched with Android 13+.)

i tried that too but phone bootlopped in mi logo

**Comment by pndwal** [comment]
How are you patching it?... What errors?

**Comment by ProcessDuck** [comment]
> How are you patching it?... What errors?...
> 
> Also, did you restore boot.img (and any other changed images) before flashing init_boot.img and booting?

i have the stock boot.img that boots to hyperos and i patch it from magisk app

**Comment by pndwal** [comment]
?... That could be the issue... You shouldn't be patching that...

**Comment by ProcessDuck** [comment]
> ?... That could be the issue... You shouldn't be patching that...

then what image i should patch

**Comment by ProcessDuck** [comment]
i patched init_boot.img and flashed it to init_boot_a and init_boot_b . the mistake ive made is i tried flashing without a-b slots.

**Comment by pndwal** [comment]
Ah, sorted then...

So fastboot flash init_boot /path/to/magisk_patched_[random_strings].img doesn't work??
