### ISSUE TITLE
Calling stub online can break Hide the Magisk app function

### ISSUE THREAD

**Issue by pndwal** [topjohnwu/Magisk#8066]
Device: Any
Android version: Any
Magisk version name: Any
Magisk version code: 27002

Hide the Magisk App function is clearly calling stub from online repo (per update JSON) so if Update channel is set to Stable or Beta with Canary loaded and stub version has been incremented, the Hide attempt will fail since this commit: [Always update stub APK when upgrade](https://github.com/topjohnwu/Magisk/commit/c951b208a1e7fcd986a8c3c65a9a190ea4ecf58a), [topjohnwu](https://github.com/topjohnwu/Magisk/commits?author=topjohnwu) committed on 15 Mar.

Eg the Stub apk used by 27000 (27.0) is v38... 27002 builds use v39, so if channel is set to Stable with current Canary installed, stub installation breaks with only unspecified "error" popping up...

I know we can simply set the channel so it doesn't call JSON for older versions when taking Hide (or Restore?) the Magisk app, but I don't know why stub is still being called online... I think there were previous fixes to make installation 100% offline (ie. to retrieve stub.apk embedded in current binaries) so perhaps this is a regression?...

I do see stub.apk is still linked in JSON so I may be missing a reason it needs to work this way, but I believe current stub is embedded in the package binaries so logically it seems that the app should pull stub from these as it does the binaries used for patching images (not rely on channel set or GitHub repo or network connection)...

Is there any reason that this shouldn't or can't work entirely offline?... Shouldn't the update JSON only be called for notes.md (changelog) and the complete Magisk package.apk (when updating App) these days?

**Comment by topjohnwu** [comment]
Stub APK is already fully offline and embedded in the full APK

**Comment by pndwal** [comment]
Yeah, I see

[Update stub implementation](https://github.com/topjohnwu/Magisk/commit/6b8171644068279f42b043fa5f4ce532c02986fe)
committed on 10 Jul,

[Move :stub to :app:stub](https://github.com/topjohnwu/Magisk/commit/b168163ef018a559deca0f9044d5ec637339010b)
committed on 4 Jul,

[Remove stub entries from canary JSONs](https://github.com/topjohnwu/magisk-files/commit/ca1062daa5f47acd0b8dbe352e3209db10356af1)
committed 27 days ago

Seems it's fixed now, thanks. 👍
