### ISSUE TITLE
Terminal apps don't get su permission, message "recv_fd: msg_flags =m 0, msg_controllen(0) != 24"

### ISSUE THREAD

**Issue by MisterFloppy** [topjohnwu/Magisk#8072]
I tried getting superuser permission by running the "su" command in several terminal apps (Termux, Termius, Nethunter Terminal) after having granted su access to them in the magisk manager, all to no avail: a message is always popping up saying "recv_fd: msg_flags =m 0, msg_controllen(0) != 24". Last try was at 18:36:00.. If I remember correctly, until v26 of Magisk it worked fine.

Device: Pocophone F1
Android version: 9
Magisk version name: 81658d45(27002)
Magisk version code: 27002

Magisk log:
[magisk.log](https://github.com/topjohnwu/Magisk/files/15406433/magisk.log)

**Comment by Yop-Solo** [comment]
I get the same line in the terminal.
````
$ su -c ls -l /mnt/media_rw
recv_fd: msg_flags = 0, msg_controllen(0) != 24
````

Device: Pocophone F1
Android 12 (Lineage OS 19)
Magisk 27000
Termux 0.101

[magisk_log_2024-05-25T14.34.29.log](https://github.com/topjohnwu/Magisk/files/15443472/magisk_log_2024-05-25T14.34.29.log)

**Comment by yujincheng08** [comment]
try set selinux to permissive to see if it works. if so, it's not magisk's issue.

**Comment by yujincheng08** [comment]
this is because someone has umounted magisk's devpts. not our issue.

**Comment by MisterFloppy** [comment]
Thank you for your response. However,I have no clue at all how to solve the issue, and am feeling a little bit like being left standing in the rain :-(

Regarding that you have closed and labeled the issue as "not our issue" meaning that "it is caused by third-party like customized ROM or module", please take note that

- The ROM installed on the device is the stock one from the manufacturer Xiaomi, so it's not customized
- not a single module has been added since the last time the "su" command worked flawlessly when the previous version of Magisk (v26.?) was installed

So my assumption is that the problem has been introduced with the upgrade process to the newer version of Magisk.

Fortunately, as a word-around for the problem that I can't run "su" commands at the moment in native terminal apps, I have discovered an app  which is an interpreter for the good old programming language "BASIC" and has an example inluded that allows running "su" commands from there!

Could you list the "su" commands one by one required to "revert" the  unmount of  magisk's devpts, please?

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/blob/c6f076251033c46a66b8f06a517cd58d94ad2fb7/native/src/core/daemon.cpp#L394-L407

**Comment by MisterFloppy** [comment]
Here's a log after I have disabled all the Magisk modules on my device.

Device: Pocophone F1
Android version: 9
Magisk version name: https://github.com/topjohnwu/Magisk/commit/81658d45f7236fdbd535a6c3a06ae19bc08cb842(27002)
Magisk version code: 27002

Magisk log:
[magisk.log](https://github.com/topjohnwu/Magisk/files/15462892/magisk.log)
