### ISSUE TITLE
After flash patch file magisk N/A in magisk app

### ISSUE THREAD

**Issue by davidx7** [topjohnwu/Magisk#8076]
I install magisk and patch boot.img after flash with magisk patch file and reboot phone:

root checker: rooted
safety Net: failed

magisk installed N/A
zygisk No
ramdisk Yes

Device: Redmi 12C
MIUI version: 14.0.6.0
Android version: 13 TP1A.220624.014
Magisk version name: debug
Magisk version code: 27002

magisk_install_log
-----------------------------------------------------------------------------------------------------------------------------------
- Device platform: arm64-v8a
- Installing: 81658d45 (27002)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [12626986]
RAMDISK_SZ      [16128081]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [147873]
OS_VERSION      [12.0.0]
OS_PATCH_LEVEL  [2023-09]
PAGESIZE        [2048]
NAME            []
CMDLINE         [bootopt=64S3,32N2,64N2 buildvariant=user]
CHECKSUM        [36aa2f969c04ec8c98ccc4e44fba362f582985f8000000000000000000000000]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
[boot/sign.rs:242] unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [1] (primitive)
VBMETA
Loading cpio: [ramdisk.cpio]
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
resetprop: get prop [ro.crypto.state]: [encrypted]
preinit device: md_udc
- Pre-init storage partition: md_udc
Loading cpio: [ramdisk.cpio]
Add file [init] (100750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add file [overlay.d/sbin/magisk32.xz] (100644)
Add file [overlay.d/sbin/magisk64.xz] (100644)
Add file [overlay.d/sbin/stub.xz] (100644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/stub.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add file [.backup/.magisk] (100000)
Dumping cpio: [ramdisk.cpio]
Loading dtbs from [dtb]
Loading dtbs from [dtb]
- Repacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [12626986]
RAMDISK_SZ      [16128081]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [147873]
OS_VERSION      [12.0.0]
OS_PATCH_LEVEL  [2023-09]
PAGESIZE        [2048]
NAME            []
CMDLINE         [bootopt=64S3,32N2,64N2 buildvariant=user]
CHECKSUM        [36aa2f969c04ec8c98ccc4e44fba362f582985f8000000000000000000000000]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
[boot/sign.rs:242] unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [1] (primitive)
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [2]
KERNEL_SZ       [12626986]
RAMDISK_SZ      [16458933]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [147873]
OS_VERSION      [12.0.0]
OS_PATCH_LEVEL  [2023-09]
PAGESIZE        [2048]
NAME            []
CMDLINE         [bootopt=64S3,32N2,64N2 buildvariant=user]
CHECKSUM        [93ce00a94112241d7d1c90cc6320acff161609c7000000000000000000000000]

cp: can't preserve ownership of 'busybox': Operation not permitted
****************************
 Output file is written to 
 /storage/emulated/0/Download/magisk_patched-27002_fkBlT.img 
****************************
cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
cp: can't preserve ownership of 'magiskpolicy': Operation not permitted
- All done!

**Comment by yujincheng08** [comment]
You should patch `init_boot.img`

**Comment by davidx7** [comment]
redmi 12c just have boot_a.img, boot_b.img, vbmeta_img, vbmeta_b.img
