### ISSUE TITLE
Bluetooth not turning on after installing Magisk

### ISSUE THREAD

**Issue by iXeNIV** [topjohnwu/Magisk#8080]
After flashing phone then setting it up, I installed Magisk V27.0 everything works fine except bluetooth can no longer be turned on even if uninstalling Magisk, so I had to reflash it again, without Magisk bluetooth worked, then I installed it again to confirm, found out it was caused by Magisk.

Device: Poco X3 NFC
Android version:11 Xiaomi EU 12.5.8.0 ROM
Magisk version name: V27.0
Magisk version code:27002

**Comment by yujincheng08** [comment]
Should be a duplicate of #7764
