### ISSUE TITLE
installed N/A in magisk app

### ISSUE THREAD

**Issue by davidx7** [topjohnwu/Magisk#8081]
redmi 12c have two slot a and b. i flash both partition boot_a and boot_b but not working.
i try flash init_boot partition: FAILED (remote: 'This partition doesn't exist')

after flash with magisk patch file and reboot phone:

root checker: rooted
safety Net: failed

magisk installed N/A
zygisk No
ramdisk Yes

Device: Redmi 12C
MIUI version: 14.0.6.0
Android version: 13 TP1A.220624.014
Magisk version name: debug
Magisk version code: 27002
magisk_install_log

    Device platform: arm64-v8a
    Installing: https://github.com/topjohnwu/Magisk/commit/81658d45f7236fdbd535a6c3a06ae19bc08cb842 (27002)
    Copying image to cache
    Unpacking boot image
    Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
    HEADER_VER [2]
    KERNEL_SZ [12626986]
    RAMDISK_SZ [16128081]
    SECOND_SZ [0]
    RECOV_DTBO_SZ [0]
    DTB_SZ [147873]
    OS_VERSION [12.0.0]
    OS_PATCH_LEVEL [2023-09]
    PAGESIZE [2048]
    NAME []
    CMDLINE [bootopt=64S3,32N2,64N2 buildvariant=user]
    CHECKSUM [36aa2f969c04ec8c98ccc4e44fba362f582985f8000000000000000000000000]
    KERNEL_FMT [gzip]
    RAMDISK_FMT [gzip]
    [boot/sign.rs:242] unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [1] (primitive)
    VBMETA
    Loading cpio: [ramdisk.cpio]
    Checking ramdisk status
    Stock boot image detected
    Patching ramdisk
    resetprop: get prop [ro.crypto.state]: [encrypted]
    preinit device: md_udc
    Pre-init storage partition: md_udc
    Loading cpio: [ramdisk.cpio]
    Add file [init] (100750)
    Create directory [overlay.d] (0750)
    Create directory [overlay.d/sbin] (0750)
    Add file [overlay.d/sbin/magisk32.xz] (100644)
    Add file [overlay.d/sbin/magisk64.xz] (100644)
    Add file [overlay.d/sbin/stub.xz] (100644)
    Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
    Loading cpio: [ramdisk.cpio.orig]
    Backup [init] -> [.backup/init]
    Record new entry: [overlay.d] -> [.backup/.rmlist]
    Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
    Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
    Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
    Record new entry: [overlay.d/sbin/stub.xz] -> [.backup/.rmlist]
    Create directory [.backup] (0000)
    Add file [.backup/.magisk] (100000)
    Dumping cpio: [ramdisk.cpio]
    Loading dtbs from [dtb]
    Loading dtbs from [dtb]
    Repacking boot image
    Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
    HEADER_VER [2]
    KERNEL_SZ [12626986]
    RAMDISK_SZ [16128081]
    SECOND_SZ [0]
    RECOV_DTBO_SZ [0]
    DTB_SZ [147873]
    OS_VERSION [12.0.0]
    OS_PATCH_LEVEL [2023-09]
    PAGESIZE [2048]
    NAME []
    CMDLINE [bootopt=64S3,32N2,64N2 buildvariant=user]
    CHECKSUM [36aa2f969c04ec8c98ccc4e44fba362f582985f8000000000000000000000000]
    KERNEL_FMT [gzip]
    RAMDISK_FMT [gzip]
    [boot/sign.rs:242] unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [1] (primitive)
    VBMETA
    Repack to boot image: [new-boot.img]
    HEADER_VER [2]
    KERNEL_SZ [12626986]
    RAMDISK_SZ [16458933]
    SECOND_SZ [0]
    RECOV_DTBO_SZ [0]
    DTB_SZ [147873]
    OS_VERSION [12.0.0]
    OS_PATCH_LEVEL [2023-09]
    PAGESIZE [2048]
    NAME []
    CMDLINE [bootopt=64S3,32N2,64N2 buildvariant=user]
    CHECKSUM [93ce00a94112241d7d1c90cc6320acff161609c7000000000000000000000000]

cp: can't preserve ownership of 'busybox': Operation not permitted

Output file is written to
/storage/emulated/0/Download/magisk_patched-27002_fkBlT.img

cp: can't preserve ownership of 'magisk32': Operation not permitted
cp: can't preserve ownership of 'magisk64': Operation not permitted
cp: can't preserve ownership of 'magiskboot': Operation not permitted
cp: can't preserve ownership of 'magiskinit': Operation not permitted
cp: can't preserve ownership of 'magiskpolicy': Operation not permitted

    All done!

**Comment by SomaKhaos** [comment]
i have the same problem on my pixel 7 with lineageos21

**Comment by ThunderStud613** [comment]
If you read the bootloader error message.... `init_boot` doesn't exist in your devices GPT partition table... Sorry good sir just needed to point that out

**Comment by pndwal** [comment]
Just to confirm, did you try "fastboot flash boot /path/to/magisk_patched_[random_strings].img" (w/o specifying slot)?...

... init_boot.img is only for devices launched with Android 13+... Yours launched with 12.

**Comment by pndwal** [comment]
Further, since Checker is reporting root, did you previously have taken Hide the Magisk app (have Magisk hidden in stub)?... Please check for re-named (default name is 'Settings') stub apps in device 
Further, since Checker is reporting root, did you previously have taken Hide the Magisk app (have Magisk hidden in stub)?... Please check for re-named (default name is 'Settings') stub apps in device settings, Apps...mm


Also, run 
Further, since Checker is reporting root, did you previously have taken Hide the Magisk app (have Magisk hidden in stub)?... Please check for re-named (default name is 'Settings') stub apps in device settings, Apps...

Also, run 
Also, run "Magisk -c" or "magisk -v" in an basic terminal emulator (avod Termux unless know what you are doing) to see if Magisk is really installed...

**Comment by yujincheng08** [comment]
please provide [bugreport](https://developer.android.com/studio/debug/bug-report) as soon as the device boots.

**Comment by Hamed516** [comment]
https://github.com/topjohnwu/Magisk/issues/8081#issuecomment-2151274117

**Comment by secretgspot** [comment]
same happened to me, updated to 27 and everything went to craps! can't revert back to 26.4. you should seriously check compatibility before allowing installation. very unhappy!
