### ISSUE TITLE
S24+ - Safe mode not triggered

### ISSUE THREAD

**Issue by remdu92** [topjohnwu/Magisk#8092]
Device: SM-S926B/DS
Android version: A14 - Build : S926BXXS2AXD6
Magisk version name: 81658d45 (debug)
Magisk version code: 27002

Hello Magisk team,

After almost killing my phone and recovered it, I've made some severals tests to triggers Magisk safe mode.
I'm not talking about Samsung Safe Mode here.

I've never got the Magisk safe mode where all modules got disabled.
I'm however able to trigger it on a slower phone (Galaxy s20)

I've followed Magisk FAQ to enter properly the keystroke : https://topjohnwu.github.io/Magisk/faq.html
I've found a related issue where it's explained to try several timing : https://github.com/topjohnwu/Magisk/issues/4624
I've look into the source code, where i found the button needs to be pressed during 3s to trigger safe mode : https://github.com/topjohnwu/Magisk/blob/master/native/src/core/bootstages.cpp

I've tried to press the keystoke with cold boot, reboot, hard reboot, charger boot. Each time, no luck
Started cold boot with button pressed or a little bit later to try severals timming

My guess is, phone don't spend enough time on magisk init process, hence the 3s requierements are not met.

Indeed, when I power on the phone, here the process:

1. First "samsung logo" - less than a second
2. Bootloader unlocked warning, this screen can be bypass by pressing power key (i've tried with and without bypass) - 10s without bypass
3. Samsung logo with warning image and red line saying phone cannot be trusted as phone is not running samsung officiel fimeware - less than a second
4. Samsung logo (secured by knox) without any warning for 20s (volume down released at end of this stage)
5. Boot animation

I'm willing to help and grab as much logs as possible.
I've magisk.log file but unsure it's usefull in this case
Didn't find how to dump kernel boot log

Hope you may have an idea, or maybe changing the key combo at boot could be an option

Regards

**Comment by NikulausRui** [comment]
I got the same issue

**Comment by vvb2060** [comment]
#7923 fixed
