### ISSUE TITLE
努比亚Z17刷入magisk后指纹不可用

### ISSUE THREAD

**Issue by youyim123** [topjohnwu/Magisk#810]
由于刷了magisk后开机密码错误，所以取消密码后刷入v17.4-a9f265a5，指纹不可用，提示无法注册指纹，请使用其他手指。
[log.zip](https://github.com/topjohnwu/Magisk/files/2635796/log.zip)

**Comment by SovietBall** [comment]
能告诉我你怎么上传文件吗😊
