### ISSUE TITLE
Zygisk does not work on latest LineageOS 21

### ISSUE THREAD

**Issue by zhaobozhen** [topjohnwu/Magisk#8113]
Device: Xiaomi MI6
Android version: 14
Magisk version name: 81658d45
Magisk version code: 27002

bootlog: [bootlog.txt](https://github.com/user-attachments/files/15604134/bootlog.txt)
magisk log: [magisk_log_2024-06-06T13.20.32.log](https://github.com/user-attachments/files/15604137/magisk_log_2024-06-06T13.20.32.log)
ROM link: https://mirrorbits.lineageos.org/full/sagit/20240531/lineage-21.0-20240531-nightly-sagit-signed.zip

It seems that zygote crashed, but I'm not sure if it's caused by an issue with the ROM.
```
06-14 16:46:30.476  2725  2725 D :  zygisk32: androidSetCreateThreadFunc
06-14 16:46:30.497  2726  2726 D :  zygisk64: androidSetCreateThreadFunc
06-14 16:46:30.497  2725  2725 I :  zygisk32: replace nativeForkAndSpecialize
06-14 16:46:30.497  2725  2725 I :  zygisk32: replace nativeSpecializeAppProcess
06-14 16:46:30.497  2725  2725 I :  zygisk32: replace nativeForkSystemServer
06-14 16:46:30.527  2726  2726 I :  zygisk64: replace nativeForkAndSpecialize
06-14 16:46:30.527  2726  2726 I :  zygisk64: replace nativeSpecializeAppProcess
06-14 16:46:30.527  2726  2726 I :  zygisk64: replace nativeForkSystemServer
06-14 16:46:31.620  2726  2726 D :  zygisk64: pre  forkSystemServer
06-14 16:46:32.041  2840  2840 D :  zygisk64: post forkSystemServer
06-14 16:46:32.560   967  1753 I :  ** zygote restarted
06-14 16:46:32.565   967  1753 W :  zygote crashes too many times, rolling-back
```

**Comment by yujincheng08** [comment]
Caused by a zygisk module.

**Comment by Maritoguionyo** [comment]
> Device: Xiaomi MI6 Android version: 14 Magisk version name: [81658d4](https://github.com/topjohnwu/Magisk/commit/81658d45f7236fdbd535a6c3a06ae19bc08cb842) Magisk version code: 27002
> 
> bootlog: [bootlog.txt](https://github.com/user-attachments/files/15604134/bootlog.txt) magisk log: [magisk_log_2024-06-06T13.20.32.log](https://github.com/user-attachments/files/15604137/magisk_log_2024-06-06T13.20.32.log) ROM link: https://mirrorbits.lineageos.org/full/sagit/20240531/lineage-21.0-20240531-nightly-sagit-signed.zip
> 
> It seems that zygote crashed, but I'm not sure if it's caused by an issue with the ROM.
> 
> ```
> 06-14 16:46:30.476  2725  2725 D :  zygisk32: androidSetCreateThreadFunc
> 06-14 16:46:30.497  2726  2726 D :  zygisk64: androidSetCreateThreadFunc
> 06-14 16:46:30.497  2725  2725 I :  zygisk32: replace nativeForkAndSpecialize
> 06-14 16:46:30.497  2725  2725 I :  zygisk32: replace nativeSpecializeAppProcess
> 06-14 16:46:30.497  2725  2725 I :  zygisk32: replace nativeForkSystemServer
> 06-14 16:46:30.527  2726  2726 I :  zygisk64: replace nativeForkAndSpecialize
> 06-14 16:46:30.527  2726  2726 I :  zygisk64: replace nativeSpecializeAppProcess
> 06-14 16:46:30.527  2726  2726 I :  zygisk64: replace nativeForkSystemServer
> 06-14 16:46:31.620  2726  2726 D :  zygisk64: pre  forkSystemServer
> 06-14 16:46:32.041  2840  2840 D :  zygisk64: post forkSystemServer
> 06-14 16:46:32.560   967  1753 I :  ** zygote restarted
> 06-14 16:46:32.565   967  1753 W :  zygote crashes too many times, rolling-back
> ```

Had the same issue but



> Caused by a zygisk module.

Reading this then disabling zygisk-specific modules fixed it for me
