### ISSUE TITLE
magisk.log !!When Zygisk is turned on , there is a media playback error, no sound video playback on browsers, can't use Newpipe or Google photos to play videos or even music ☠️!!

### ISSUE THREAD

**Issue by Ranintotrouble** [topjohnwu/Magisk#8119]
I have not seen any other user reporting this bug so I posted it.

Device: Olivelite 
Android version: 13
Magisk version name: 27
Magisk version code:27002

**Comment by Ranintotrouble** [comment]
> I have not seen any other user reporting this bug so I posted it.
> Device: Olivelite Android version: 13 Magisk version name: 27 Magisk version code:27002

I am genuinely asking for help , if anyone could tell me the solution. Everything works fine , just turning up zygisk makes this system error for media playback.

**Comment by yujincheng08** [comment]
close because of no log
