### ISSUE TITLE
[Feature Request] Add argument to the Manager to install prequest(s) module(s)

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk#813]
Hello,

I think it would be more appropriate in sweater requests, but who cares.....

Would it be possible to add if it's not already done a new command argument to the Magisk manager to install one or more prerequisite module(s) during the installation of a module?

I ask that because for now, modules devs can add some shell commands to check if a module folder exists or not in "/sbin.magisk/img/" (formerly "/sbin/.core/img/)".
Of course i think it would be possible to nest a pre-requisite module installation in the installer of a first module, but including this possibility could save time for people like me who make modules.

Meanwhile the whole project is a very good job.

**Comment by topjohnwu** [comment]
That means it will need a whole package management system (like `apt` in Debian/Ubuntu). This complicates things A LOT, and I don't plan to . implement such complicated infrastructure for modules

**Comment by xerta555** [comment]
>That means it will need a whole package management system (like apt in Debian/Ubuntu). This complicates things A LOT, and I don't plan to implement such complicated infrastructure for modules

Instead of a complex system, i saw something happening as follows:
- argument in question called
- launch a shell script with su access to check via a grep if the name of the module in question exist
- if the folder of the prerequisite module does not exist, download it via the existing repository and install it by the same method as the one used today (or with an URL provided in the main script installer)
- Once the installation of the prerequisite has been completed, proceed to the next step of the initial installation script and so on

It's sure that if u need to implement a complicated system like an applet in Magisk just for that......
