### ISSUE TITLE
Zygisk cannot be enable on devices using emmc flash memory.

### ISSUE THREAD

**Issue by coolzyd** [topjohnwu/Magisk#8132]
In magisk official version 27000 to 27002，zygisk and denlist cannot be enable on some of the devices.It is stuck in the effective state after restart, and no matter how many restart operations are performed, this problem cannot be solved.After my test, this abnormal situation mostly appears on virtual machines,cloud android devices and devices using emmc flash memory.This means that magisk's su hiding function and some modules based on zygisk will not work in the above models.At the same time, most virtual machines and cloud Android devices use emmc flash memory, and I think this abnormal situation only appears on emmc flash memory devices.I hope to fix this bug and restore support for emmc flash devices in a future version of 27.1.

Device:
Android version:13
Magisk version name:27.0
Magisk version code:27002

**Comment by yujincheng08** [comment]
tried on my riscv64 develop board which uses emmc and zygisk works.
