### ISSUE TITLE
Magisk not installing flashed with fastboot

### ISSUE THREAD

**Issue by mike855** [topjohnwu/Magisk#8145]
Device: Redmi note 9 pro (miatoll)
Android version: Lineages 21 with microg (android 14)
Magisk version name: Magisk debug
Magisk version code: 27002

Hello,

I flashed patched boot image with fastboot, and nothing changed, Magisk is not installed.
Magisk apk v27 installed with adb then updated from phone with debug apk
Note that flashed boot was patched with version 27, not debug. I just repatched with debug for the issue.

(Screenshot, boot.img and patched boot.ing and log attached)

Boot.IMG : https://nextcloud.muguet.online/index.php/s/CpaptiPsTjHFCqq

Patched boot : https://nextcloud.muguet.online/index.php/s/nkHcn33TAPw38KY

[magisk_log_2024-06-19T09.10.26.log](https://github.com/user-attachments/files/15896843/magisk_log_2024-06-19T09.10.26.log)
[magisk_install_log_2024-06-19T08.49.12.log](https://github.com/user-attachments/files/15896844/magisk_install_log_2024-06-19T08.49.12.log)

**Comment by yujincheng08** [comment]
can you try `/system/bin/magisk su` in adb shell?

**Comment by mike855** [comment]
`joyeuse:/ $ /system/bin/magisk su
Permission denied
13|joyeuse:/ $`

**Comment by yujincheng08** [comment]
the magisk app shjould pop up a su request dialog, please grant access to it

**Comment by mike855** [comment]
I don't have any prompt. I get the Permission denied instantly.
what means : 13|joyeuse
That is the android version before the pipe? Because I'm android 13.
I think I had magisk before upgrading with 14, then I uninstalled it. I forgot If I wiped data after that. So maybe there are still traces of previous installation?

**Comment by yujincheng08** [comment]
maybe you can try to install a shell emulator app and try `/system/bin/magisk su`.

**Comment by mike855** [comment]
I dont have acces to /system with termux as the phone is not rooted.
Is there a way to remove all traces of eventual previous magisk installations?

**Comment by yujincheng08** [comment]
/system is always accessible to all apps, otherwise apps cannot use system libraries.

**Comment by yujincheng08** [comment]
as you can use `adb root`, are you using a customized rom? if so, it should be https://github.com/topjohnwu/Magisk/issues/6914

**Comment by mike855** [comment]
I use LineageOS for microg wich is a fork of LineageOS. So it is custom LineageOS^^
I take a look at #6914

**Comment by yujincheng08** [comment]
Duplicate of #6914
