### ISSUE TITLE
Root Lost on ONE UI 6.1

### ISSUE THREAD

**Issue by zastian-dev** [topjohnwu/Magisk#8158]
# Problem 
I wanted to update my device so I downloaded the firmware. copied my AP over to my phone and try and flash it. Magisk crashes. well no problem I just extract the boot.img manually and flash it and reTAR the AP. 
That worked I could flash the system with Odin. but after a reboot I lost root. open the magisk app and it states magisk is not installed. 

# Logs
[magisk_log_2024-06-27T14.42.28.log](https://github.com/user-attachments/files/16014993/magisk_log_2024-06-27T14.42.28.log)

Device:Samsung S23 SM-S911B
Android version: 14 (ONE UI 6.1)
Magisk version name: 2c6adbc
Magisk version code: 27002

**Comment by raikrishna53** [comment]
_**same problem with me someone have any idea to solve this issue asap**_

**Comment by raikrishna53** [comment]
Did you find any idea, bro

**Comment by zastian-dev** [comment]
Nope none I just flashed the stock rom again and haven't looked into it again. sorry didn't want to mess with a rooted phone that wasn't entirely functional.

**Comment by yujincheng08** [comment]
```
---Manager Logs---
27.0 (27000)
```
Not using the debug version.
