### ISSUE TITLE
ARM32 busybox executable segmentation fault on 27003

### ISSUE THREAD

**Issue by Unknown78** [topjohnwu/Magisk#8168]
Device: Samsung Galaxy Note 4 SM-N910H
Android version: 7.1.1 Nougat (API 25)
Magisk version name: debug
Magisk version code: 27003 ([45fa1fce](https://github.com/topjohnwu/Magisk/commit/45fa1fce7009a43637d621411b8b95891bbcdfdc)) [[Download](https://github.com/topjohnwu/magisk-files/commit/4b39a3d48ab14e9a15f7543598a0f4831677aadb)]

Device platform: armeabi-v7a

**System**: 
- [REFINED_NOTE8_7.1_T2.zip](https://t.me/RefinedNougat/491)
- [Konup_RisingNote4_for_RefinedNote8_7.1.1_ver.2.3.zip](https://xdaforums.com/t/refined-note-8-7-1-1-exynos-updated-mod-risingnote4-ver-2-3.4363583/) 
- [Konup_HomeOneUI_RefinedNote8_7.1.1_ver.2.0_14.07.2022.zip](https://xdaforums.com/t/refined-note-8-7-1-1-exynos-oneui-port-home-screen-bixby-weather-wallpaper-choice-apps.4371353/)
- [Konup_SamsungCamera7_RefinedNote8_7.1.1_v.1.2.zip](https://xdaforums.com/t/refined-note-8-7-1-1-exynos-updated-stock-samsungcamera7-ver-1-2-now-writing-60fps.4201475/)
- [ModemServiceMode_RefinedNote8_7.1.1.zip](https://xdaforums.com/t/refined-note-8-7-1-1-exynos-updated-mod-risingnote4-ver-2-3.4363583/post-88539729)

**Boot**:
- [Helios_Kernel-V3.2-N910C.H-20240107.zip](https://github.com/ananjaser1211/Helios_5433/issues/1#issuecomment-1880082613)

---

# Problem

I've already direct installed **Magisk** with the debug of [27001 (3d91a561)](https://github.com/topjohnwu/magisk-files/commit/72400d2258acf4a2ec8cc480093ec464fc799ddf)

If I try to update the **App** with the currently latest debug of [27003 (45fa1fce)](https://github.com/topjohnwu/magisk-files/commit/4b39a3d48ab14e9a15f7543598a0f4831677aadb),

## Case 1

Then the **App** could launch, but it's not functional.
I could grant superuser access to many apps, but the Magisk **App** itself seems to be not getting root access.

Might be unrelated, but this buggy **App** prevents me to view the device's files from Windows Explorer with USB File Transfer, so I need to pull the files manually with `adb` or rollback the **App** to the latest working of [27001 (3d91a561)](https://github.com/topjohnwu/magisk-files/commit/72400d2258acf4a2ec8cc480093ec464fc799ddf).

<details><summary><b>Screenshot of Home (click to expand)</b></summary>

![Screenshot_30 06 24_15 26 05](https://github.com/topjohnwu/Magisk/assets/25132599/fe12c284-6e55-43e6-ab85-9c0003c7546a)
</details>

<details><summary><b>Screenshot of Logs 1 (click to expand)</b></summary>

![Screenshot_30 06 24_12 25 57](https://github.com/topjohnwu/Magisk/assets/25132599/1a1c4945-73fd-4b6f-9273-75d7b6edfdf6)
</details>

<details><summary><b>Screenshot of Logs 2 (click to expand)</b></summary>

![Screenshot_30 06 24_15 33 48](https://github.com/topjohnwu/Magisk/assets/25132599/86ea7b4b-53de-4321-bae2-47fd36f22272)
</details>

<details><summary><b>Screenshot of Settings (click to expand)</b></summary>

![Screenshot_30 06 24_15 26 21](https://github.com/topjohnwu/Magisk/assets/25132599/b0cd3e9f-af81-4d77-962f-36026de350f5)
</details>

[logcat_Magisk_27003_45fa1fce_app-debug_2024-06-30T12.17.13.603000.log](https://github.com/user-attachments/files/16043307/logcat_Magisk_27003_45fa1fce_app-debug_2024-06-30T12.17.13.603000.log)
```java
06-30 12:17:14.899  3359  5129 E ActivityTrigger: activityStartTrigger: not whiteListedcom.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity/27003
```

This is the `magisk_log` from the diskette button,
[Magisk_27003_45fa1fce_app-debug_magisk_log_2024-06-30T12.17.29.log](https://github.com/user-attachments/files/16043308/Magisk_27003_45fa1fce_app-debug_magisk_log_2024-06-30T12.17.29.log)

## Case 2
Then installing **Magisk** with the method of `Direct Install` will crash the **App**.
[logcat_Magisk_27003_45fa1fce_app-debug_2024-06-30T12.45.10.363000.log](https://github.com/user-attachments/files/16043318/logcat_Magisk_27003_45fa1fce_app-debug_2024-06-30T12.45.10.363000.log)

```java
06-30 12:45:14.907  2557  2557 E App     : kotlin.UninitializedPropertyAccessException: lateinit property installDir has not been initialized
06-30 12:45:14.907  2557  2557 E App     : 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.getInstallDir(MagiskInstaller.kt:58)
06-30 12:45:14.907  2557  2557 E App     : 	at com.topjohnwu.magisk.core.tasks.MagiskInstaller.exec$suspendImpl(MagiskInstaller.kt:576)
06-30 12:45:14.907  2557  2557 E App     : 	at com.topjohnwu.magisk.core.tasks.MagiskInstaller$exec$1.invokeSuspend(MagiskInstaller.kt)
06-30 12:45:14.907  2557  2557 E App     : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-30 12:45:14.907  2557  2557 E App     : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-30 12:45:14.907  2557  2557 E App     : 	at android.os.Handler.handleCallback(Handler.java)
06-30 12:45:14.907  2557  2557 E App     : 	at android.os.Handler.dispatchMessage(Handler.java)
06-30 12:45:14.907  2557  2557 E App     : 	at android.os.Looper.loop(Looper.java)
06-30 12:45:14.907  2557  2557 E App     : 	at android.app.ActivityThread.main(ActivityThread.java)
06-30 12:45:14.907  2557  2557 E App     : 	at java.lang.reflect.Method.invoke(Native Method)
06-30 12:45:14.907  2557  2557 E App     : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
06-30 12:45:14.907  2557  2557 E App     : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
06-30 12:45:14.907  2557  2557 E App     : 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bebd979, Dispatchers.Main.immediate]
06-30 12:45:14.909  2557  2557 I art     : System.exit called, status: 1
06-30 12:45:14.909  2557  2557 I AndroidRuntime: VM exiting with result code 1, cleanup skipped.
```

## Case 3

Then installing **Magisk** with the method of `Select and Patch a File` will fail.

**magisk_install_log_2024-06-30T12.57.30.log**
```
- Device platform: armeabi-v7a
- Installing: 45fa1fce (27003)
- Copying image to cache
! Installation failed
```
[logcat_Magisk_27003_45fa1fce_app-debug_2024-06-30T12.57.13.677000.log](https://github.com/user-attachments/files/16043397/logcat_Magisk_27003_45fa1fce_app-debug_2024-06-30T12.57.13.677000.log)

---

# Additional Info

I accidently found this issue when troubleshooting other issue, https://github.com/topjohnwu/Magisk/issues/8013?notification_referrer_id=NT_kwDOAX9-N7QxMDQ0MDg2NjE5NzoyNTEzMjU5OQ#issuecomment-2091532113

Then I tried to open up a new issue, https://github.com/topjohnwu/Magisk/issues/8147
It seems to be yet another different issue.

**Comment by canyie** [comment]
![image](https://github.com/topjohnwu/Magisk/assets/31466456/6cbfe1e9-cd2a-4f81-bb1c-270cb12b7b1a)

**Comment by Ya11123** [comment]
في الاثنين، 1 يوليو 2024 10:01 ص 残页 ***@***.***> كتب:

**Comment by Unknown78** [comment]
@canyie Okay. How did you know that it was busybox fault? Will I open a new issue again after this? lol

**Comment by canyie** [comment]
Your screenshot shows "Ramdisk no" which gives me some hints, so I tried to run arm32 busybox locally, and it gives me "Segmentation fault" 😄 
Not sure if all issues are caused by it, but a broken busybox can explain all issues. So you don't need to open another issue, at least not now :) lol

**Comment by osm0sis** [comment]
This happened instead: https://github.com/topjohnwu/Magisk/commit/ef81cdab4f6cf211ab2ae37c7c00635ae819b702

Which had likely also fixed the issue.
