### ISSUE TITLE
(Upcoming) Canary build will render Nexus 5 unable to boot

### ISSUE THREAD

**Issue by sn-o-w** [topjohnwu/Magisk#8172]
Device: Nexus 5 (hammerhead)
Android version: 10
Magisk version name: Canary
Magisk version code: 27003 + commits https://github.com/topjohnwu/Magisk/commit/52063b3652b4127b36486cfc536dad045c3eeff3 + https://github.com/topjohnwu/Magisk/commit/cacc60b1ac9321199ef723a9f567c071ed350d22 + https://github.com/topjohnwu/Magisk/commit/c194168d9bf01afb1ad3556e9d0d8f1c08bb2a7a

---

Nexus 5 will be unable to boot while using the newest Canary builds. The device is simply stuck at the Google logo phase, it doesn't even get to LineageOS boot animation. So I dunno how can I collect logs at this early phase.

This is what happens on the device:

https://github.com/topjohnwu/Magisk/assets/2406819/e51e7ee7-ef58-4cf5-8e7b-869046bdf301

I took APK from here: https://github.com/topjohnwu/Magisk/actions/runs/9729582390 Then I installed the APK on another device, non-rooted, and I manually patched the kernel of my hammerhead, and the patched file I transferred to the hammerhead and I flashed it via TWRP.

In case you need these files:
[boot-17.1-2023-02-17.zip](https://github.com/user-attachments/files/16044983/boot-17.1-2023-02-17.zip)
[boot-PATCHED-17.1-2023-02-17.zip](https://github.com/user-attachments/files/16044986/boot-PATCHED-17.1-2023-02-17.zip)

**Comment by aviraxp** [comment]
Does it boot with `flag += " B_CRT0=1"` removed in build.py?

**Comment by aviraxp** [comment]
Seems a magiskboot issue then.

**Comment by aviraxp** [comment]
Warning: NEVER flash patched image shared by others or patch image on another device even if they have the same device model! You may need to do a full data wipe to recover your device. ALWAYS patch boot image on the same device where you want to install Magisk.

**Comment by canyie** [comment]
![image](https://github.com/topjohnwu/Magisk/assets/31466456/8eb137de-270f-4f10-b0bc-41977980d79b)
![image](https://github.com/topjohnwu/Magisk/assets/31466456/b5d71602-3e0e-4740-bc8d-62121982386a)
Dunno if you patched the image on the correct device 🤔
