### ISSUE TITLE
Use class instead of classname [ClassNotFoundException] 

### ISSUE THREAD

**Issue by suqiernb** [topjohnwu/Magisk#8185]
Device: MI Pad 5 Pro
Android version: 13
Magisk version name: 27.0
Magisk version code: 27003
Zygisk version: 5

```cpp
// Hook JNI native methods for a class
//
// Lookup all registered JNI native methods and replace it with your own functions.
// The original function pointer will be saved in each JNINativeMethod's fnPtr.
// If no matching class, method name, or signature is found, that specific JNINativeMethod.fnPtr
// will be set to nullptr.
void hookJniNativeMethods(JNIEnv *env, const char *className, JNINativeMethod *methods, int numMethods);
```

- Using `className` leads to `ClassNotFoundException`, typically due to `ClassLoader` restrictions.
- `jclass` should be used instead to avoid the ClassNotFoundException.

```cpp
void hookJniNativeMethods(JNIEnv *env, jclass clazz, JNINativeMethod *methods, int numMethods);
```

**Comment by yujincheng08** [comment]
> All API methods will stop working after post[XXX]Specialize as Zygisk will be unloaded from the specialized process afterwards

When using `hookJniNativeMethods`, there should not be classloader restriction. And you only have one classloader, which is the system classloader (the one zygote creates).
