### ISSUE TITLE
多用户问题

### ISSUE THREAD

**Issue by zbqwla73264** [topjohnwu/Magisk#821]
仅主用户时，其它用户的magisk manager显示需要重新安装magisk，但安装一直失败。
由主用户管理，仅在其它用户上安装的应用 无法请求root权限，主用户上已经允许的应用自动获得了root权限。
分别管理，magisk manager没有自动安装到其它用户上。

还有，在其它用户上管理magiskhide时，可以勾选Android系统，随后系统崩溃。

**Comment by SovietBall** [comment]
兄dei你在这发中文真的好吗
还有，magisk的设置里有多用户模式
麻烦你在主用户时找找～(￣▽￣～)~

**Comment by topjohnwu** [comment]
中文沒問題的，重點是要有 log ，並且用 canary debug build 啊兄dei

**Comment by zbqwla73264** [comment]
@topjohnwu 可能是我没有说清楚，解释一下。
如果多用户模式设置为`仅设备所有者有超级用户权限`，那么在第二用户上的Magisk Manager会提示需要额外的安装。#817 好像解决了这个问题。
如果多用户模式设置为`由设备拥有者管理`，那么一个只在第二用户上安装，主用户上没有安装的应用，无法获得root权限，自动拒绝。但如果主用户上也安装了，并且获得了root权限，第二用户上申请时会自动获得，不弹窗。看样子是其它用户的规则与主用户完全同步，这是期望行为吗？
如果多用户模式设置为`各用户独立`，Magisk好像没有确认各个用户上是否都安装了Magisk Manager。

最后，在第二用户上安装的Magisk Manager，Magisk hide可以勾选Android系统(包名：android)，随后系统崩溃。

测试版本，canary release build a54eaf53。主要是逻辑上的问题，日志在这里应该不能提供多少帮助…按照上面的信息，可以重复触发这些问题。
