### ISSUE TITLE
hookJniNativeMethods original function pointer not get update

### ISSUE THREAD

**Issue by fei-ke** [topjohnwu/Magisk#8213]
Device: Samsung SM-S9100
Android version: Android 14
Magisk version name: b38ab2a7
Magisk version code: 27004

```c++
JNINativeMethod targetHookMethods[] = {
        {"native_get", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
         (void *) my_native_get},
};
api->hookJniNativeMethods(env, "android/os/SystemProperties", targetHookMethods, 1);

//targetHookMethods[0].fnPtr still porint to my_native_get
```

After a bit of digging, I found this comparison will not be passed,
the method.signature hold a full signature: `(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;` 
but the old_method.signature got a short signature: `LLL`
https://github.com/topjohnwu/Magisk/blob/7c0b25cad9fd7b400085666c1e18ffa393f7fa1e/native/src/core/zygisk/hook.cpp#L592

Seems similar to: #7945

**Comment by yujincheng08** [comment]
Check https://github.com/topjohnwu/Magisk/pull/8215
