### ISSUE TITLE
Can't install on Pixel 7 after July 5, 2024 update

### ISSUE THREAD

**Issue by UncleJed** [topjohnwu/Magisk#8218]
Device: Pixel 7
Android version: 14 with July 5, 2024 security update
Magisk version name: 27.0
Magisk version code: 27004 (D)

[magisk_log_2024-07-14T17.21.28.log](https://github.com/user-attachments/files/16228857/magisk_log_2024-07-14T17.21.28.log)

Log file attached.  I couldn't get the boot.img file to upload

**Comment by pndwal** [comment]
The boot image file for patching is init_boot.img, not boot.img... you are patching that right?

**Comment by UncleJed** [comment]
Thank You.  That was it.  All these years I've been using boot.img with 
no issues. Thank You so much for the quick response and fix!!

**Comment by pndwal** [comment]
Oh... Sounded like you had Magisk before July 5 OTA 🤔... If so you must have patched init_boot.img!... On properly configured GKI compliant devices launched with Android 13+, generic ramdisk simply never existed in boot.img...
