### ISSUE TITLE
"Requires Additional Setup" + "Unable to find preinit dir"

### ISSUE THREAD

**Issue by sn-o-w** [topjohnwu/Magisk#8219]
Device: Nexus 5 (hammerhead)
Android version: 10
Magisk version name: Canary
Magisk version code: 27004

---

I'm not sure what is wrong, but I get the prompt "Requires additional setup" every time, and I need to reflash Magisk.

In the installation window, I get at the end, "All done!" but the penultimate line says, "Unable to find preinit dir.".

I took some screenshots:
<img src="https://github.com/user-attachments/assets/dfe3a94e-cb2d-495e-9a9a-bf2b24e3868c" width="400"> <img src="https://github.com/user-attachments/assets/ce5491c3-e204-4418-8d4d-3329b9fce420" width="400">

So even if it says that the installation went successfully, after I reboot the device and open Magisk Manager, I see again "Requires additional setup" and it tells me I need to reflash Magisk.

And given the fact I couldn't install the last 2-3 official Canary releases until this is merged https://github.com/topjohnwu/Magisk/pull/8174, I am forced to create my own Magisk builds with the fix included. I even tried to merge other recent PRs submitted by @yujincheng08, but no use.

I created my own Magisk APK, I even added my own signing key in order to have a working Magisk Manager, I patched the boot file on my Nexus 5 for my Nexus 5, and then I flashed the patched image via TWRP. And this problem persists.

I created my own Magisk APK via GitHub Actions here: https://github.com/sn-o-w/Magisk

And this is the patched boot file: [magisk_patched-27004_pMmTd.zip](https://github.com/user-attachments/files/16228989/magisk_patched-27004_pMmTd.zip)

**Comment by pndwal** [comment]
Especially as you have custom ROM, what happens if you patch boot.img in Magisk app and flash w/ fastboot?

**Comment by pndwal** [comment]
Yes... Only partial root w/ custom recovery installation:

> In this release, a brand new pre-init partition detection mechanism has been designed to support even more devices. Due to complicated reasons, this detection mechanism cannot be performed in a custom recovery environment.

> This means that any installation of Magisk v26+ using custom recovery will be incomplete; a subsequent re-installation through the Magisk app after booting up is required.

[v26.0](https://topjohnwu.github.io/Magisk/releases/26000.html)

... After booting and taking Direct from app, the selinux/module rule directory path should be set properly however...

**Comment by yujincheng08** [comment]
send magisk log

**Comment by yujincheng08** [comment]
Try https://github.com/topjohnwu/Magisk/pull/8221

**Comment by MSharkM** [comment]
Hi
I see by changing the location from METADATA to USERDATA the problem solved!
But article 8221 has been closed and now i have just the same problem and would be thankful if somebody help me!

**Comment by Lixczyy** [comment]
> Hi I see by changing the location from METADATA to USERDATA the problem solved! But article 8221 has been closed and now i have just the same problem and would be thankful if somebody help me!

Hi i have the same issue where should i change metadata to userdata?
