### ISSUE TITLE
Magic Hide makes apps unusable (they keep stopping) 

### ISSUE THREAD

**Issue by F5T3** [topjohnwu/Magisk#8232]
Device: Motorola Moto G84 (XT2347-2)
Android version: 14 With the May 1st 2024 security patch
Magisk version name: b38ab2a7
Magisk version code: 27004 (D) 

Modules:
FlagSecurePatcher
Framework Patcher GO
Hide UserDebug, Test-Keys and LineageOS
liboemcryptodisabler
Magisk built-in BusyBox
PlayIntegrityFork
SafetyNet sensitive props
Shamiko
Systemless Hosts
TobyBox (Ext)
Zygisk - LSPosed
Zygisk - Sui
Zygist Assistant
zygist-detach

I am going to switch to Magisk canary for now. 

To recreate: add apps to Magisk Hide, if it doesn't work try with the Modules. 

I have tried Brawl Stars, Clash Royale and Clash of clans, Google Play Services, Google Play Store,  Google Services Framework, Ruru root check and Momo Root checker. 

It only happens when the apps are in the Magisk Hide list. 

I will add logs once I have them all in files.

**Comment by F5T3** [comment]
I mixed it up with the DenyList sorry.

**Comment by JasonKhew96** [comment]
@F5T3 are you using HMA xposed module? disable `Settings > [Module] Data Isolation > Enforce data isolation for all apps`

**Comment by F5T3** [comment]
> @F5T3 are you using HMA xposed module

No I am only using SnapEnhance. I was using BootloaderSpoofer and DevOptsHide earlier but realised I didn't need them since they did nothing. (In my use)
