### ISSUE TITLE
Error installation modules magisk

### ISSUE THREAD

**Issue by xnnnsets** [topjohnwu/Magisk#8260]
Device: samsung a34
Android version: 14
Magisk version name: Magisk (0495468d) (27006)
Magisk version code: Magisk (0495468d) (27006)

**Comment by xnnnsets** [comment]
[magisk_install_log_2024-07-27T22.18.07.log](https://github.com/user-attachments/files/16400699/magisk_install_log_2024-07-27T22.18.07.log)

Modul di magisk stable berfungsi tanpa kesalahan
Mengapa saya menggunakan magisk cannary  Because i need magisk cannary to hide bank and zygisk next

**Comment by Ereciosz** [comment]
Had same issue. Just downloaded newest Vanced Magiskn module and it's working fine. One that was released like 2 hours ago.
