### ISSUE TITLE
Bootloop after enable zygisk

### ISSUE THREAD

**Issue by EngSahl** [topjohnwu/Magisk#8267]
Device: Infinix Hot 11 X662
Android version: 11
Magisk version name: v27.0
Magisk version code: 27006

Whenever i tried to enable zygisk or install any module the device got into a bootloop 
And it's a problem I can't use any module like shamiko or lsposed even when i try to install riru the same thing happened

**Comment by vincentng295** [comment]
This problem happens if libzygisk.so is placed under `/system/lib(64)`

**Comment by EngSahl** [comment]
> This problem happens if `libzygisk.so` is placed under `/system/lib(64)`

So how can I solve this?
