### ISSUE TITLE
Cannot Direct Install on Nvidia Shield TV 2017 (darcy)

### ISSUE THREAD

**Issue by znbaboy** [topjohnwu/Magisk#8274]
Device: Nvidia Shield TV 2017 (darcy)
Android version: Android 13 (LineageOS 20)
Magisk version name: Magisk Canary
Magisk version code: 27006

Title pretty much explains my issue. 

I manually patch the boot.img and flash it to my Shield TV. Everything works fine, but once I get a new LineageOS update, I have to manually flash the boot.img again using my computer. Its a pretty big hassle to move my Shield TV to my computer with its power brick + connect it to a monitor every time I have an update.

Why is the option to Direct Install missing on the Shield TV? I couldn't find a clear answer to this anywhere. Are there any forks of Magisk that can handle this perhaps?

Thank you!

**Comment by canyie** [comment]
Sorry, can't understand your issue.
If you mean the Direct Install option is lost after installing OTA, this is because the boot partition was overwritten by OTA and the app cannot get root anymore. No way to fix.

**Comment by znbaboy** [comment]
> Sorry, can't understand your issue. If you mean the Direct Install option is lost after installing OTA, this is because the boot partition was overwritten by OTA and the app cannot get root anymore. No way to fix.

No that is not what I am saying.

I am saying that I patch the boot.img and flash it to my Shield TV. My device is then rooted and I am able to do typical root actions. 

The issue is, even though the device is rooted, I am not able to flash Magisk to the boot partition through the Magisk Manager app as it only gives me the option to patch a boot.img file even though I am rooted with Magisk.

I have LineageOS installed on my phone as well and I use this exact process to keep my root after OTA:

Download/install LineageOS update through OTA > Open Magisk Manager and flash to second slot > Reboot device

This allows me to update my device while keeping root with no computer. I want the same process for my Shield TV but the direct install option is never available regardless if the device is rooted or not.
