### ISSUE TITLE
File leak in zipsigner

### ISSUE THREAD

**Issue by ale5000-git** [topjohnwu/Magisk#828]
zipsigner (I have version 3.0) at every run create 2 temp files in the user temp folder (at least on Windows), at the end it remove only one of them, leaking 1 file at every run.

Could it be fixed please?

**Comment by topjohnwu** [comment]
Here is the snippet of the code:
```java
File temp1 = File.createTempFile("signAPK", null);
File temp2 = File.createTempFile("signAPK", null);

try {
    /* Do signing here */
} finally {
    temp1.delete();
    temp2.delete();
}
```
So, it is a bug in your JVM, nothing I can fix

**Comment by ale5000-git** [comment]
To workaround this problem now I just choose a custom temp dir and delete it after execution.
`java -Djava.io.tmpdir="${MY_TEMP_DIR}" -jar zipsigner.jar ...`
