### ISSUE TITLE
prevent access to magisk.db 

### ISSUE THREAD

**Issue by Yuri29710** [topjohnwu/Magisk#8283]
Hello! I recently noticed that by modifying /data/adb/magisk.db I could give root to any app, including games, and this should be a problem in case some malicious app gets root and installs another app and grants root without warning the user. I believe that /data/adb/magisk.db should be hidden so that no app or user can do this. what do you think? 
![Screenshot_20240804_005345](https://github.com/user-attachments/assets/5e30ffb1-8cb8-4f66-9582-dba2afb5d878)
Device: SM-A135M
Android version: 14
Magisk version name: Debug
Magisk version code: 27006

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/blob/ca36b42d79d8fb2f526afb92c31bf9c9806eec70/app/core/src/main/res/values/strings.xml#L58
