### ISSUE TITLE
(darcy) Device Does Not Boot After Patching Boot.img

### ISSUE THREAD

**Issue by znbaboy** [topjohnwu/Magisk#8285]
Device: Nvidia Shield TV 2017 (darcy)
Android version: lineage-21.0-20240805-nightly-foster (Android 14)
Magisk version name: Magisk Canary
Magisk version code: 27006

Trying to boot device after patching/flashing boot.img via fastboot/bootloader causes device to return to bootloader interface. Fails to boot.

**Comment by znbaboy** [comment]
Why was this closed? Can we get more info instead of just closing?

**Comment by yujincheng08** [comment]
https://github.com/topjohnwu/Magisk/blob/09131aca893efd950ad59847dadf109a0f556b89/README.MD?plain=1#L34-L40

**Comment by znbaboy** [comment]
> https://github.com/topjohnwu/Magisk/blob/09131aca893efd950ad59847dadf109a0f556b89/README.MD?plain=1#L34-L40

[magisk_install_log_2024-08-06T00.18.31.zip](https://github.com/user-attachments/files/16505176/magisk_install_log_2024-08-06T00.18.31.zip)

patched boot.img + install.log included

**Comment by hamedsbt** [comment]
Same issue on Nvidia Shield TV 2019 Pro.

**Comment by hamedsbt** [comment]
> Device: Nvidia Shield TV 2017 (darcy) Android version: lineage-21.0-20240805-nightly-foster (Android 14) Magisk version name: Magisk Canary Magisk version code: 27006
> 
> Trying to boot device after patching/flashing boot.img via fastboot/bootloader causes device to return to bootloader interface. Fails to boot.

How did you select boot.img file? 
I have installed "Documentsui" app but it doesn't help!

**Comment by znbaboy** [comment]
> > Device: Nvidia Shield TV 2017 (darcy) Android version: lineage-21.0-20240805-nightly-foster (Android 14) Magisk version name: Magisk Canary Magisk version code: 27006
> > Trying to boot device after patching/flashing boot.img via fastboot/bootloader causes device to return to bootloader interface. Fails to boot.
> 
> How did you select boot.img file? I have installed "Documentsui" app but it doesn't help!

There seems to be some bug in LOS21 that causes the file manager to not open even when after installing one. The workaround to solve this was:

- Install SwiftBackup apk (https://www.apkmirror.com/apk/swiftapps-org/swift-backup/swift-backup-5-0-4-release/swift-backup-5-0-4-android-apk-download)
- Continue without an account
- Go to Settings and select the export option (it will make you select the default app to use for this action. Here you choose your file manager)
- Then do the same thing with the import option
- Now when you open Magisk to patch the boot.img, it will open the file manager without issue.

I will be creating a bug report for this on LOS Gitlab later today

**Comment by znbaboy** [comment]
> > https://github.com/topjohnwu/Magisk/blob/09131aca893efd950ad59847dadf109a0f556b89/README.MD?plain=1#L34-L40
> 
> [magisk_install_log_2024-08-06T00.18.31.zip](https://github.com/user-attachments/files/16505176/magisk_install_log_2024-08-06T00.18.31.zip)
> 
> patched boot.img + install.log included

I have provided what you requested. Can you reopen the issue or should I create a new one? @yujincheng08
