### ISSUE TITLE
boot.img from LineageOS build (3rd August) for 'bramble' (Google Pixel 4a 5G) isn't being patched.

### ISSUE THREAD

**Issue by StupidRepo** [topjohnwu/Magisk#8298]
There appears to be no errors when patching the boot.img in Magisk, however upon flashing it, it seems like Magisk hasn't actually rooted the device?

![Screenshot_20240809-234944_Magisk.png](https://github.com/user-attachments/assets/a6c8d939-8d18-410a-b23e-6e32fb477a64)

Device: bramble/Google Pixel 4a 5G
Android version: 14
Magisk version name: 27006
Magisk version code: 0495468d (27006)

**Comment by canyie** [comment]
How can we help you without any valid info?

**Comment by StupidRepo** [comment]
> How can we help you without any valid info?
What valid info was needed? I already said the patch log was normal like any other boot.img patch I have done.

Anyway, after a day it seems to be randomly working?

**Comment by 7kilobytes** [comment]
> > How can we help you without any valid info?
> 
> What valid info was needed? I already said the patch log was normal like any other boot.img patch I have done.
> 
> Anyway, after a day it seems to be randomly working?

Could you please describe in details how you could make it work? I have the same issue

**Comment by StupidRepo** [comment]
> > > How can we help you without any valid info?
> > 
> > 
> > What valid info was needed? I already said the patch log was normal like any other boot.img patch I have done.
> > Anyway, after a day it seems to be randomly working?
> 
> Could you please describe in details how you could make it work? I have the same issue

I don't actually know? It seemed after a few restarts it fixed itself?
