### ISSUE TITLE
Magisk Manager Changelog window bug

### ISSUE THREAD

**Issue by Anutha02** [topjohnwu/Magisk#831]
I am getting this weird shake when clicking on Changelog in the latest magisk Manager 6.1.0.
Also it occurs exactly in an alternating manner I.e. it occurs on 2nd 4th 6th click and so on
![video2gif_20181208_143507](https://user-images.githubusercontent.com/36439704/49684199-7d8b9a80-faf6-11e8-8a35-00da30d890da.gif)

**Comment by Anutha02** [comment]
Instead of an alertdialog you would probably be better off dedicating a separate activity for the Changelog.

**Comment by topjohnwu** [comment]
Fixed: aad9aced183c52298037ccb6b2213e0942b8b6e5
