### ISSUE TITLE
Magisk Manager crashes if it cannot access the internet

### ISSUE THREAD

**Issue by Madis0** [topjohnwu/Magisk#832]
I hid Magisk Manager using the official option. When launching it, Manager crashed as soon as it checked for updates. 
Later on I noticed that AFWall+ had restricted it for some reason and after giving it internet access again, everything worked fine.

Using
- Android 8.1.0
- Magisk 18.0
- Magisk Manager 6.1.0 (`com.OYAuJ.hT8.pVfupY`)

[logs.txt](https://github.com/topjohnwu/Magisk/files/2659603/logs.txt)

**Comment by topjohnwu** [comment]
Please provide full logs from debug canary builds

**Comment by djechelon** [comment]
Duplicates #917
