### ISSUE TITLE
Zygisk never becomes enabled after rebooting to apply changes.

### ISSUE THREAD

**Issue by Microsoft-Outlook-612AFDC28E14556F** [topjohnwu/Magisk#8320]
Device: Fairphone 4 (Codename FP4)
Android version: 14
Magisk version name: 27
Magisk version code: 27006

My apologies in advance if I broke any of the bug reporting rules.
[logcat.txt](https://github.com/user-attachments/files/16667275/logcat.txt)
[magisk_log_2024-08-19T19.42.46.log](https://github.com/user-attachments/files/16667277/magisk_log_2024-08-19T19.42.46.log)

**Comment by yujincheng08** [comment]
modules' issue
