### ISSUE TITLE
Pixel 9 fails to boot after installing patched init_boot.img "Your device is corrupted and unable to boot"

### ISSUE THREAD

**Issue by yaspoon** [topjohnwu/Magisk#8325]
Device: Pixel 9
Android version: 14 AD1A.240530.030.B1
Magisk version name: Magisk (0495468d)
Magisk version code: 27006

I eventually got it to boot by flashing the vbmeta.img and disabling verity and verification as mentioned in the installation guide. There is mention in the magisk log about `[boot/sign.rs:261] unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [1] (primitive)` so I'm wondering if this is why booting fails without turning off verity/verification

When the phone booted it actually went to recovery saying "Try factory reseting your device" after doing that the device did boot. Sideloading magisk it mentions that it needs to "finish setup and reboot" doing that worked and I then had a working SU.

[magisk_install_log_2024-08-22T01.37.30.log](https://github.com/user-attachments/files/16706287/magisk_install_log_2024-08-22T01.37.30.log)
[pixel9_init_boot_imgs.zip](https://github.com/user-attachments/files/16706307/pixel9_init_boot_imgs.zip)

**Comment by yaspoon** [comment]
I first tried with Magisk 27.0 the app acted quit strange freezing a few times but did eventually patch the image. When the device failed to boot after recovering it I then tried Magisk 0495468 version which also failed to boot until I disabled verity/verification.

**Comment by yujincheng08** [comment]
> I eventually got it to boot

Issue is not where you ask questions.

https://github.com/topjohnwu/Magisk/blob/1dc723fb6d9846954fddc1ff0fe8c32fa8a31355/.github/ISSUE_TEMPLATE/config.yml#L3-L5
