### ISSUE TITLE
Update to Magisk 18.0 can't using fingerprint

### ISSUE THREAD

**Issue by SovietBall** [topjohnwu/Magisk#833]
update to magisk 18.0 can't using fingerprint
device:SLA-AL00
emui 5.1.1 Android 7.0

**Comment by JoanVC100** [comment]
Same for me in Elephone S7 x25 Edition.
Tested with Android 6.0.1 and 7.1.1

**Comment by topjohnwu** [comment]
1. No logs, no fix
2. You should be using debug canary builds for providing logs, not release builds

**Comment by JoanVC100** [comment]
Sorry for that, i tried to replicate the problem and the fingerprint isn't working, but now i bring you the log of Magisk. 

[magisk.log](https://github.com/topjohnwu/Magisk/files/2660447/magisk.log)
