### ISSUE TITLE
"Zygisk No" after patching and flashing boot.img

### ISSUE THREAD

**Issue by rkachowski** [topjohnwu/Magisk#8341]
Device: OnePlus Nord 2T
Android version: 14 / OxygenOS CPH2399_14.0.0.606(EX01)
Magisk version name: magisk-canary
Magisk version code: 8e82113b (27007)(D)

After patching the `boot.img` file via magisk + flashing and rebooting, magisk doesn't seem to be installed. Within the magisk panel in the app it shows "Installed N/A - Zygisk No - Ramdisk Yes"
[magisk_install_log_2024-08-26T21.17.11.log](https://github.com/user-attachments/files/16753130/magisk_install_log_2024-08-26T21.17.11.log)
[magisk_log_2024-08-26T21.35.34.log](https://github.com/user-attachments/files/16753131/magisk_log_2024-08-26T21.35.34.log)

**Comment by vvb2060** [comment]
#8177
