### ISSUE TITLE
Can't Install Magisk Module

### ISSUE THREAD

**Issue by SovietBall** [topjohnwu/Magisk#835]
My Phone Can't Install Any Magisk Module
Data Partition It's F2FS
Install "F2FS Loopback Bug Workaround" In TWRP
And Install Module It's Works (Just in the first reboot from Twrp to Android)
I hope you can fix it, because I've tried it a few 20 times for this.
I'm not sure you can read it, because I'm using Microsoft translate.
Here is log
- Copying zip to temp directory
- Installing Android_Pie_Fonts-v6.zip
 
Unzipping files...
 
    *****************************
    *     Android Pie Fonts     *
    *****************************
    *             v6            *
    *         Joey Huab         *
    *****************************
 
- Mounting /data, /cache
- Magisk install detected
- Mounting /system, /vendor
cat: write error: Broken pipe
- Found /data/adb/magisk_merge.img
e2fsck 1.42.9 (28-Dec-2013)
! /data/adb/magisk_merge.img mount failed...
! Installation failed

**Comment by topjohnwu** [comment]
I cannot fix your broken F2FS driver in your device's kernel. Either switch to EXT4, or flash an updated custom kernel.
