### ISSUE TITLE
Odin stuck at `File analysis..` when trying to flash patched AP generated by Magisk 27007, while 27000 is fine

### ISSUE THREAD

**Issue by UlyssesWu** [topjohnwu/Magisk#8371]
Device: Samsung S23 (SM-S9110 CHC)
Android version: 14
Magisk version name: Magisk (8e82113b)
Magisk version code: 27007

Odin version: 3.14
Firmware: https://samfw.com/firmware/SM-S9110/CHC/S9110ZCU2BXA4

I'm trying to root S23. Firstly I tried to use Magisk v27 stable to generate a patched AP. It can be flashed by Odin, but at the end it will stuck at setup wizard - when trying to activate the phone it always shows a toast `[2002] -45`. (some similar case [here](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1893057))
My phone was not binded to a Google account when flashing, and I have no idea how to fix that. The only option for me is to flash the original AP, it will not stuck at setup wizard and will activate as usual - I feel so lucky that my phone didn't get bricked 😭 

Then I decided to try the canary version 27007. It took much longer than 27000 to generate a patched AP. However, the Odin cannot handle it - Odin will stuck at `File analysis..` forever:

![odin-magisk-bad](https://github.com/user-attachments/assets/1579da33-fcf4-4e86-a810-8d7b5fcb39e0)

Since I'm using the exact same AP for patch input, I believe the 27007 has changed something and Odin cannot support that.

I have compared the boot.img generated by 27000 and 27007, they're exactly same. I just attach one of them (patched).
[boot.zip](https://github.com/user-attachments/files/16908395/boot.zip)

[magisk_install_log.log](https://github.com/user-attachments/files/16908574/magisk_install_log_2024-09-06T21.16.48.log)

**Comment by UlyssesWu** [comment]
Sorry, I just realized that Odin will work if flashing patched AP + BL + CP + CSC at the same time.
However, it still stucks when trying to activate the phone, with a toast `[2002] -45`.

**Comment by UlyssesWu** [comment]
looks like a duplicate of #7242

**Comment by diabl0w** [comment]
this is not a duplicate of that ticket as far as i can tell, and the bug still exists on 27008. please reopen

**Comment by jeweljacob387** [comment]
My device is Samsung Galaxy M12 (SM-M127G). Patched image using Magisk v27004 also make Odin stuck at _File Analysis..._.
Tried with the whole AP file and minimal zip with boot, recovery and vbmeta.

**Comment by lifr0m** [comment]
The same

**Comment by KN592** [comment]
got this issue with galaxy A30 too, patched magisk tar just keeps odin stuck at file analysis

**Comment by ErenalpCet** [comment]
also got this issue on j4 core while trying to flash patched firmware

**Comment by KN592** [comment]
> also got this issue on j4 core while trying to flash patched firmware

had to wait until the next day, then the OEM unlock setting showed up again and was greyd out, so i went ahead and got twrp running now, finally free of the pain. you can flash magisk through twrp iirc, might wanna try that if it is possible for you good luck, also post your issue etc on XDA forum

**Comment by ErenalpCet** [comment]
thanks. if oem unlocking setting is not showing up you can change the time.

**Comment by PedroMiguel-PXS** [comment]
i have an A04S and i patched a boot.img with magisk 27, the masigk generate the magisk_patched2700 and i put on odin, i dont know but should works and not works

**Comment by mochibuilds** [comment]
If oem is not unlocked you will get this error
