### ISSUE TITLE
Custom package id feature. 

### ISSUE THREAD

**Issue by MeGaNeKoS** [topjohnwu/Magisk#8398]
Device: Samsung SM-A146P 
Android version: 14
Magisk version name: 27.0
Magisk version code: 27007

Enable user to use custom package name as well.

![Screenshot_20240917_070424_TB Checker](https://github.com/user-attachments/assets/255e0ce2-244f-46da-868b-b853f04f3f88)

**Comment by Astoritin** [comment]
I don't think it's difficult if you use Hide My Applist.
Besides this is not an issue caused by Magisk, especially passing detector.

**Comment by canyie** [comment]
Adding the feature won't prevent it from being detected.
