### ISSUE TITLE
daemon not auto started on some vivo devices

### ISSUE THREAD

**Issue by 1q23lyc45** [topjohnwu/Magisk#8405]
Device: Vivo Y52s
Android version: 11 (The factory system is Android 10)
Magisk version name:33f70f8f
Magisk version code:27008

## IS DIFFERENT FROM #5148 !
Magisk Daemon cannot auto start.
But I can manually start it using the 
```bash
adb root;adb shell /sbin/magisk --daemon
```
command.
I have already bypassed the su command restriction through Radare2 and also found a way to bypass the mount restriction.

After starting the daemon, there aren't any additional SELinux restrictions, and MagiskSU is working properly.

**Comment by vvb2060** [comment]
upload log, kmsg or bugreport

**Comment by 1q23lyc45** [comment]
> upload log, kmsg or bugreport

How to capture logs? `adb logcat`'s capture may not be very useful. I have tried to analyze it, but only a bunch of useless Android runtime errors and logs for certain drivers (wifi/touch screen/Bluetooth). I can't catch it with the Logcatcher module because Magisk doesn't work at all. It's only mounted on /sbin and doesn't run the daemon.

**Comment by 1q23lyc45** [comment]
The issue has been resolved. Simply uninstall Magisk once, format the cache partition, delete all files under /data/adb, and reinstall Magisk.

The modified magisk installed last time was not uninstalled completely(I clicked on restore original factory image instead of completely uninstall), which caused the issue.
