### ISSUE TITLE
magisk 18.0 breaks cell connectivity on a Samsung s9+ l

### ISSUE THREAD

**Issue by partcyborg** [topjohnwu/Magisk#841]
Device: Samsung s9+ intl. Snapdragon edition (SM-G9650)
Magisk version: 18.0 (upgraded from 17.1)
Rom: RR GSI (using latest phh gsi patches)

Issue: after upgrading magisk to the new 18.0, my cell connectivity cycles endlessly between disconnected and connected with signal.  This happens around once per second at first, slowing down over time to around once every 10-20 seconds after several minutes.  When the rest happens, some kind of ui refresh happens as well, causing things like in progress "slide" keyboard inputs to break, Nova launcher's app drawer to close, and likely other things I didn't notice due to thi the first two.  This renders the device unusable.  Rolling back to 17.1 fixes the issue (although 17.1 has its own issues but that is outside scope here).

I was told that magisk has known issues on phh gsi images, but if you are careful to not set certain module setups (for example, no files overlayed in /system/etc outside things in /sbin/.core/img/.core) everything works perfectly.  I would normally just stay on 17.1, but given the push to get everyone and everything on 18, that won't be possible for long.

**Comment by partcyborg** [comment]
Here are kernel, modem and logcat logs from my device from while this is happening:

https://drive.google.com/file/d/18q8YD0viru4XIAOsKKepRMNPlC5tJIKf/view?usp=sharing

Hope this helps

**Comment by topjohnwu** [comment]
Move to a single issue (#844) regarding GSIs
