### ISSUE TITLE
Possible Bind Mount Issue?

### ISSUE THREAD

**Issue by diabl0w** [topjohnwu/Magisk#8426]
Device: SM-F926B
Android version: 14
Magisk version name: Canary
Magisk version code: 27008

Issue: according to (the docs)[https://github.com/topjohnwu/Magisk/blob/master/docs/details.md]:

```
MAGISKTMP=$(magisk --path)

# Magisk internal stuffs
INTERNALDIR=$MAGISKTMP/.magisk

...

# /data/adb/modules will be bind mounted here.
# The original folder is not used due to nosuid mount flag.
$INTERNALDIR/modules
```

However, despite having many modules installed, `/debug_ramdisk/.magisk/modules` is empty. Is this correct?

**Comment by vvb2060** [comment]
yes, don't rely on magisk internal details

**Comment by diabl0w** [comment]
> yes, don't rely on magisk internal details

What is it's purpose then?
