### ISSUE TITLE
I flashed some modules,but I can't find them in magisk after reboot.

### ISSUE THREAD

**Issue by yejunjie10311031** [topjohnwu/Magisk#8438]
Device:pixel6
Android version:14
Magisk version name:canary
Magisk version code:27008

I flashed some modules,but I can't find them in magisk modules list after reboot and they also not work.
![PXL_20241005_035456241](https://github.com/user-attachments/assets/9e8d76c1-94ec-4ac3-9a7a-d4fc1c60414a)
![Screenshot_20241005-121836](https://github.com/user-attachments/assets/335e5a41-6393-41f9-ad28-566bba11365c)
![Screenshot_20241005-121810](https://github.com/user-attachments/assets/1511f8c7-f45d-444e-af9f-7a5dc0e1a73d)

**Comment by canyie** [comment]
不像是我们的问题，请先向模块作者反馈

**Comment by yejunjie10311031** [comment]
> 不像是我们的问题，请先向模块作者反馈

但很抱歉这并不是模块的问题，因为我后来用爱玩机工具箱的magisk模块管理里面成功安装了这几个模块，重启后在列表里可以看到且正常工作
![Screenshot_20241005-135905](https://github.com/user-attachments/assets/d9007463-befc-49f0-ae7f-3f7d4e165c57)

**Comment by canyie** [comment]
说不定这个模块只支持在爱玩机里刷，没适配 magisk app

**Comment by aviraxp** [comment]
关于部分本地模块成功安装后实际未刷入的说明

直接安装脚本已于4年前淘汰，在v20.4后应该替换为调用magisk内置安装函数的安装脚本，如果模块开发者坚持不更换脚本使用官方安装流程，那么适配magisk内部行为变化是开发者的责任。
另外，通过命令行安装或者在线更新模块强制执行官方安装流程，仅本地安装需要开发者更新模块安装脚本。

**Comment by xgongluo** [comment]
@aviraxp @canyie
我有一个类似的问题请教一下：
我通过magisk  --install-module 的方式安装了一个module，也成功的在magisk  module的列表里面显示了。
但是我在magisk 的modules目录里面看不到这个module：
a53x:/debug_ramdisk/.magisk/modules # pwd
/debug_ramdisk/.magisk/modules
a53x:/debug_ramdisk/.magisk/modules # ls
a53x:/debug_ramdisk/.magisk/modules #

我使用的magisk版本是27.0
在26.4的时候是可以看到这个module的。
请问是有什么改动导致不显示了吗？
我有什么方式来判断我的module是已经安装了呢 （除了在GUI里面看之外，因为我需要在代码里面判断）？
谢谢

**Comment by aviraxp** [comment]
不要依赖magisk内部行为

**Comment by aviraxp** [comment]
不要依赖magisk内部行为
