### ISSUE TITLE
Incompatible with GSIs

### ISSUE THREAD

**Issue by topjohnwu** [topjohnwu/Magisk#844]
GSIs use tons of non standard hacks that I am not willing to spend time to support it.
**ALL custom ROMs** should aim to be as close to stock ROM as possible, it is impossible for me to keep track of all the incompatible custom changes in the wild unless it is from a major OEM.

**Comment by jeanrivera** [comment]
I am currently running a GSI on my HTC U12+ I can confirm same issue is there any log I can provide to help fix this issue?

**Comment by Adm0** [comment]
For Leagoo T8s found working version: 16.4

**Comment by artur-g** [comment]
For Vernee T3 Pro
Pie: 17.1 Above that has root but you are unable to grant root for more apps (dialog does not show)
Oreo: 18.1, didn't try 19

**Comment by alexa-v2** [comment]
Any progress on this?

**Comment by alexa-v2** [comment]
Also note:

Every gsi I tried on my moto G7 (Android 9, arm64-v8a, a/b partition) flashing magisk zip caused bootloops.  Flashing patched image would boot until I installed magisk manager and complete environment setup, then bootloop. So it would seem to be an issue with how magisk sets up its environment

Tested gsi: Resurrection Remix, lineage OS, dirty unicorn, descendant

**Comment by Adm0** [comment]
Phone: Leagoo T8s 
Vendor: LeagooOS (android 8.1), 
System: gsi  AEX v6.5 arm64 aonly 20190509 (for phh-su and adb root)

I installed magisk canary build 4040a024 and found the magisk logs in dmesg.
And drew attention to this:

> [    0.858507] (1)[1:init]magiskinit: Early mount system
[    0.859628] (1)[1:init]magiskinit: mount ->/system failed with 22: Invalid argument
[    0.859895] (1)[1:init]magiskinit: Early mount vendor
[    0.859948] (1)[1:init]magiskinit: mount ->/vendor failed with 22: Invalid argument
[    0.860025] (1)[1:init]magiskinit: open: /proc/device-tree/firmware/android/fstab/product/dev failed with 2: No such file or directory
[    0.860105] (1)[1:init]magiskinit: open: /proc/device-tree/firmware/android/fstab/odm/dev failed with 2: No such file or directory
[    0.860151] (1)[1:init]magiskinit: sepol: no selinux

Full log: [dmesg](https://github.com/topjohnwu/Magisk/files/3169402/log.txt)

cat /proc/device-tree/firmware/android/fstab/*/dev
> /dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/system
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/vendor

ls -l /dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/system
ls -l /dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/vendor
> /dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/system -> /dev/block/mmcblk0p28
 /dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/vendor -> /dev/block/mmcblk0p27

ls -R /*/etc/selinux/
> /system/etc/selinux/:
mapping                              plat_property_contexts  
plat_and_mapping_sepolicy.cil.sha256 plat_seapp_contexts     
plat_file_contexts                   plat_sepolicy.cil       
plat_hwservice_contexts              plat_service_contexts   
plat_mac_permissions.xml             selinux_denial_metadata 
/system/etc/selinux/mapping:
26.0.cil 27.0.cil 28.0.cil 
/vendor/etc/selinux/:
nonplat_file_contexts       nonplat_service_contexts                     
nonplat_hwservice_contexts  plat_sepolicy_vers.txt                       
nonplat_mac_permissions.xml precompiled_sepolicy                         
nonplat_property_contexts   precompiled_sepolicy.plat_and_mapping.sha256 
nonplat_seapp_contexts      vndservice_contexts                          
nonplat_sepolicy.cil 

Also making old versions found a commit with which problems begin: adf95ce3

**Comment by Adm0** [comment]
Watching dmesg logs with a working and non-working magisk, I saw some dependency:
If so, the magisk does not work

> [ 0.858507] (1)[1:init]magiskinit: Early mount system
[ 0.859628] (1)[1:init]magiskinit: mount ->/system failed with 22: Invalid argument
[ 0.859895] (1)[1:init]magiskinit: Early mount vendor
[ 0.859948] (1)[1:init]magiskinit: mount ->/vendor failed with 22: Invalid argument
...
[    0.876713] (0)[171:kworker/u16:2]mmc0: new HS400 MMC card at address 0001
[    0.877380] (0)[171:kworker/u16:2]mmcblk0: mmc0:0001 DF4032 29.1 GiB 
[    0.877774] (0)[171:kworker/u16:2]mmcblk0boot0: mmc0:0001 DF4032 partition 1 4.00 MiB
[    0.878169] (0)[171:kworker/u16:2]mmcblk0boot1: mmc0:0001 DF4032 partition 2 4.00 MiB
[    0.878560] (0)[171:kworker/u16:2]mmcblk0rpmb: mmc0:0001 DF4032 partition 3 4.00 MiB

If so, the magisk work

> [    0.857096] (0)[114:kworker/u16:1]mmc0: new HS400 MMC card at address 0001
[    0.857710] (0)[114:kworker/u16:1]mmcblk0: mmc0:0001 DF4032 29.1 GiB 
[    0.858087] (0)[114:kworker/u16:1]mmcblk0boot0: mmc0:0001 DF4032 partition 1 4.00 MiB
[    0.858482] (0)[114:kworker/u16:1]mmcblk0boot1: mmc0:0001 DF4032 partition 2 4.00 MiB
[    0.858860] (0)[114:kworker/u16:1]mmcblk0rpmb: mmc0:0001 DF4032 partition 3 4.00 MiB
...
[    0.919170] (0)[1:init]magiskinit: Early mount system
[    0.926204] (0)[1:init]magiskinit: Found system: [mmcblk0p28] (179, 28)
[    0.949423] (0)[1:init]magiskinit: Early mount vendor
[    0.949463] (0)[1:init]magiskinit: Found vendor: [mmcblk0p27] (179, 27)

So I decided to make magisk for the test and I add `sleep(1);` in early_mount and now the magisk seems to be working.

**Comment by alexa-v2** [comment]
I noticed that ianmacd version solved my bootloop issue on Descendant sGSI on a moto g6 if that helps

**Comment by nonnymoose** [comment]
Here's a new one: The latest Magisk won't respond to su requests on any GSI ROM that I've tested. It just times out and returns `permission denied`. Manually editing `magisk.db` to enable specific apps works perfectly fine. It seems that MagiskSU cannot open the dialog to ask whether it should allow the app to use root.

**Comment by nonnymoose** [comment]
As it turns out, it wasn't Magisk's fault. The shared library `libdirect-coredump.so` was missing from `/system/lib`/`/system/lib64`, so I copied it from `/vendor` and Magisk started working perfectly.

**Comment by artur-g** [comment]
> 
> 
> As it turns out, it wasn't Magisk's fault. The shared library `libdirect-coredump.so` was missing from `/system/lib` / `/system/lib64`, so I copied it from `/vendor` and Magisk started working perfectly.

This fix works on Vernee T3 Pro on GSI AOSP 9.0 v113. 
Good job @nonnymoose 
@phhusson This looks interesting.

**Comment by rfgamaral** [comment]
Any updates on this?

**Comment by EarsKilla** [comment]
> As it turns out, it wasn't Magisk's fault. The shared library `libdirect-coredump.so` was missing from `/system/lib` / `/system/lib64`, so I copied it from `/vendor` and Magisk started working perfectly.

helped for me too

**Comment by Geofferey** [comment]
For users with devices such as the Moto G7 Power removing `init.mmi.hab.sh` from `/vendor/bin/` may fix boot loops when installing magisk. Dm-verity will need to be disabled. Take a look at [this](https://review.lineageos.org/c/LineageOS/android_device_motorola_nash/+/206632/17/rootdir/bin/init.mmi.hab.sh).

**Comment by alexa-v2** [comment]
That'll do it yes

For those who are curious, that script looks like it verifies boot, vendor, and system and refuses to boot if any fails veru. Which obviously with Magisk boot image verification will fa

Good catch 👍

**Comment by phhusson** [comment]
> As it turns out, it wasn't Magisk's fault. The shared library `libdirect-coredump.so` was missing from `/system/lib` / `/system/lib64`, so I copied it from `/vendor` and Magisk started working perfectly.

This is Magisk fault. This error happen only on permissive contexts, or on contexts that allow noatsecure, that's why it works on STOCK UNMODIFIED NO MAGISK boot.img + GSI.
This issue has absolutely nothing to do with GSI.
There is no reason to add noatsecure to contexts not related to Magisk.

**Comment by alexa-v2** [comment]
@topjohnwu maybe an issue that needs looking at. Doesn't seem like a desired behavior for magisk to modify **any** selinux policies outside of it's own context

> > As it turns out, it wasn't Magisk's fault. The shared library `libdirect-coredump.so` was missing from `/system/lib` / `/system/lib64`, so I copied it from `/vendor` and Magisk started working perfectly.
> 
> This is Magisk fault. This error happen only on permissive contexts, or on contexts that allow noatsecure, that's why it works on STOCK UNMODIFIED NO MAGISK boot.img + GSI.
> This issue has absolutely nothing to do with GSI.
> There is no reason to add noatsecure to contexts not related to Magisk.

**Comment by Andrew-afk** [comment]
> As it turns out, it wasn't Magisk's fault. The shared library `libdirect-coredump.so` was missing from `/system/lib` / `/system/lib64`, so I copied it from `/vendor` and Magisk started working perfectly.

I dont have those files in `/vendor` ... What do i do?

**Comment by lss4** [comment]
For Android 11 phh-based GSIs, the main issue would be how to deal with the absence of `/sbin` and to coexist with phh's `resetprop` (which is not removed even after using `phh-securize.sh` and would get in the way as Magisk needs to use its own `resetprop`). (See [here](https://github.com/topjohnwu/Magisk/issues/3593#issuecomment-754326443))

For now getting Magisk to work on such GSIs requires modifying `/system` contents, but I'm not sure if it's possible to handle those issues without altering `/system` as with dynamic partitions and non-vndklite GSI variants, mounting `/system` read-write may not be straightforward.

As some GSIs can be less bootable compared to others, or being outright unfriendly with Magisk in overall... things that works on the GSIs I've tested may not apply to all other GSIs.

**Comment by phhusson** [comment]
For resetprop issue, I can rename "my" (it's really magisk's) resetprop to
resetprop_phh.

**Comment by Mek101** [comment]
From my unbderstanding, this issue is outdated: https://twitter.com/topjohnwu/status/1008056655001468928

**Comment by bf8392** [comment]
On the Android 11 AOSP GSI, the Phone stucks in Bootloop after patching the boot image...

**Comment by lss4** [comment]
> On the Android 11 AOSP GSI, the Phone stucks in Bootloop after patching the boot image...

This depends on device (vendor-related). Not all devices work with Magisk patched boot image using GSI.

Also, some GSIs have an inconsistency, that it has a physical `/sbin` but doesn't expose it to `$PATH`. Magisk will first try installing it to `/sbin` and as a result, this inconsistency will prevent Magisk from working normally (see #4309).

If that's the case and you're running a vndklite ROM, you need to manually delete the `/sbin` folder after mounting system r/w from recovery (be sure it is empty before deleting it), so that Magisk would then install itself to `/bin` which will allow Magisk to work.

**Comment by bf8392** [comment]
Ahhh Okay great thanks :-) I also manually patched the boot Image, which also didn't work...does this apply here too? Because after flashing the stock boot back again, it worked...

**Comment by lss4** [comment]
> Ahhh Okay great thanks :-) I also manually patched the boot Image, which also didn't work...does this apply here too? Because after flashing the stock boot back again, it worked...
> Besides I tried it on a non vndklite ROM...just flashed vndklite variant (which I don't know the difference between). Do I have a better chance to get it to work here? Besides that I should mention that I don't have a custom recovery as there is non available for the Ulefone Armor 10 5G...

non-vndklite GSIs use ext4 deduplication to reduce system partition size, which in turn makes mounting system r/w no longer trivial. In comparison, vndklite GSIs still allow system to be mounted r/w. To me this is the only major difference, though I can't be sure what else might be different between non-vndklite and vndklite ones.

**Comment by bf8392** [comment]
Okay great thanks for the explanation :-)

**Comment by bf8392** [comment]
I tried various GSI'S now (Havoc OS, AOSP) both vdklte and non...it always results in bootloop when I patch the boot image.... interesting side fact: it works flawlessly on stock...

**Comment by lss4** [comment]
> I tried various GSI'S now (Havoc OS, AOSP) both vdklte and non...it always results in bootloop when I patch the boot image.... interesting side fact: it works flawlessly on stock...

My Samsung Galaxy Tab S7+ was in the same boat. Magisk worked fine on stock but not on GSI (bootloops).

It was due to a known issue with new Samsung Qualcomm vendors. By flashing an Android 10 vendor I was able to get Magisk working on GSI, but I had to manually deal with a 100-second (platform) watchdog when using GSIs there.

**Comment by zainullahk** [comment]
magisk wont boot for me either 
a71 any help
