### ISSUE TITLE
Magisk Hide Takes Forever!

### ISSUE THREAD

**Issue by chadify** [topjohnwu/Magisk#8459]
Device: Nothing 2(a)
Android version: 14
Magisk version name:28
Magisk version code:28001

The loading wheels just keeps spinning for forever.
Here's the attached video: 

https://github.com/user-attachments/assets/f12fcf81-2146-4d17-aeee-d4015be08d8d

**Comment by canyie** [comment]
Hello, we don't have enough info such as logs to perform investigation on this report. For this reason, I am closing this issue.
