### ISSUE TITLE
Magisk hide not working with fortnite ??

### ISSUE THREAD

**Issue by Mathew444** [topjohnwu/Magisk#846]
So I have no issues with Pokemon go but fortnite still gives me that error message wasn't that fixed in 17.1 ? I'm running the v18. Maybe I'm just doing something wrong. I'm thankful for any help!

**Comment by Mathew444** [comment]
* Starting MagiskHide
06-18 12:54:28.421   619   936 I Magisk  : hide_utils: Hiding sensitive props
06-18 12:54:28.422   619   936 I Magisk  : hide_list: [com.epicgames.fortnite]
06-18 12:54:28.435   619   936 I Magisk  : hide_list: [com.epicgames.portal]
06-18 12:54:28.445   619   936 I Magisk  : hide_list: [com.google.android.gms/.droidguard.DroidGuardService]
12-09 00:38:31.460   619  1366 I Magisk  : ** late_start service mode running
12-09 00:38:31.460   619  1366 I Magisk  : * Running service.d scripts
12-09 00:38:31.460   619  1366 I Magisk  : service.d: exec [propsconf_late]
12-09 00:38:32.191   619  1366 I Magisk  : * Running module service scripts
12-09 00:38:32.191   619  1366 I Magisk  : ViPER4AndroidFX: exec [service.sh]
12-09 00:39:13.952   619   936 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[4857] ns=[4026534136]
12-09 00:45:47.890   619   936 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[9862] ns=[4026534136]
12-09 00:50:49.988   619 11972 I Magisk  : hide_list add: [com.nianticlabs.pokemongo]
12-09 00:51:06.039   619   936 I Magisk  : proc_monitor: com.nianticlabs.pokemongo/com.nianticproject.holoholo.libholoholo.unity.UnityMainActivity PID=[12005] ns=[4026534123]
12-09 00:51:37.365   619   936 I Magisk  : proc_monitor: com.nianticlabs.pokemongo/com.nianticlabs.pokemongoplus.service.BackgroundService PID=[12356] ns=[4026534139]
12-09 00:54:01.483   619   936 I Magisk  : proc_monitor: com.epicgames.portal/.activities.main.MainActivity PID=[13230] ns=[4026534116]
12-09 01:14:22.536   619   936 I Magisk  : proc_monitor: com.epicgames.portal/org.chromium.content.app.SandboxedProcessService0 PID=[13299] ns=[4026531840]
12-09 01:14:22.541   619   936 I Magisk  : proc_monitor: com.epicgames.fortnite/com.epicgames.ue4.SplashActivity PID=[15081] ns=[4026534137]
12-09 01:14:25.263   619   936 I Magisk  : proc_monitor: com.epicgames.fortnite/com.epicgames.ue4.SplashActivity PID=[15882] ns=[4026534116]
12-09 01:19:30.393   619   936 I Magisk  : proc_monitor: com.epicgames.fortnite/org.chromium.content.app.SandboxedProcessService0 PID=[16747] ns=[4026531840]
12-09 01:19:50.253   619   936 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[16923] ns=[4026534125]
12-09 02:44:29.568   619   936 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[21253] ns=[4026534135]
12-09 04:57:31.533   619   936 I Magisk  : proc_monitor: com.epicgames.portal/.IntentReceiver PID=[29023] ns=[4026534136]
12-09 05:44:34.422   619   936 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[31665] ns=[4026534151]
12-09 06:49:24.647   619   936 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[5618] ns=[4026534128]
12-09 08:57:33.288   619   936 I Magisk  : proc_monitor: com.epicgames.portal/.IntentReceiver PID=[8306] ns=[4026534095]12-09 09:51:13.867   619   936 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[10394] ns=[4026534106]

**Comment by topjohnwu** [comment]
Please refer to the tutorial here: https://topjohnwu.github.io/Magisk/tutorials.html#best-practices-for-magiskhide
