### ISSUE TITLE
Can't get root for Magisk >=17.2, only version <= 17.1 works on my phone.

### ISSUE THREAD

**Issue by coreboot2** [topjohnwu/Magisk#847]
My phone is Redmi note 2, I recently using MiFlash to fully wipe and flashed the latest MIUI. I can't get root using the latest Magisk. So I downgrade versions. I found the lastest Magisk works is the 17.1.

miui version: MIUI V.9.6.1
android version: 5.0

**Comment by topjohnwu** [comment]
1. No logs, no fix
2. You should be using debug canary builds for providing logs, not release builds
