### ISSUE TITLE
Can NOT Change File Permission !

### ISSUE THREAD

**Issue by Johnn78** [topjohnwu/Magisk#8477]
Device: Poco F3
Android version: 13
Magisk version name: v28.0
Magisk version code: 28001
![Screenshot_2024-10-16-00-18-35-997_com estrongs android pop](https://github.com/user-attachments/assets/7ec9d3b7-1fcf-4b47-8412-4eadbf583895)
![IMG_20241016_002153](https://github.com/user-attachments/assets/629206b6-28a5-445c-b78f-4ab13372a19b)
![IMG_20241016_002241](https://github.com/user-attachments/assets/cc21ad4b-d6c7-4225-91ce-370dd3c98c56)
![IMG_20241016_002328](https://github.com/user-attachments/assets/ebf53d4b-59b5-4463-87f7-da97c4a6fcdb)

I have Adaway for blocking ads. Its operaion is to update the etc/host file with addresses so that to block ads. If this file is big then occurs some delation in browsing. To resolve this problem is to find the etc/host file (for example via ES File Explorer) & in properties to change the permissions of file by disabling the "read" permission from "other". This was done successfully until Magisk v27. In Magisk v28 or Magisk (070719db) (28001) if I go to change it then I got the error "Sorry the operation failed". I tried to use and other file managers like "Root Explorer" but it couldn't. Only if I go back to Magisk v27 then I can change permission of file and to disable the "read" permission from "other". Developer find what you have changed in Magisk v28 or in Magisk (070719db) (28001) and doesn't permit to change permission to fix it in next version. Thanks in advance !

**Comment by pndwal** [comment]
Guessing, but if works with 27003 but not 27004, could be another sepolicy change issue like this:
https://github.com/topjohnwu/Magisk/issues/8457#issuecomment-2415283959

**Comment by aviraxp** [comment]
https://github.com/topjohnwu/Magisk/commit/92b305a389bcb0dc7e2b3169134f0a81bac6c513#diff-df031a3e39488591e9b4c84425c47bbbb7f51787e120511cfa14866f12597176L155

If you are using sth like systemless hosts, please change module hosts attributes intead

**Comment by Johnn78** [comment]
> Guessing, but if works with 27003 but not 27004, could be another issue with the sepolicy change like this: [#8457 (comment)](https://github.com/topjohnwu/Magisk/issues/8457#issuecomment-2415283959)

What do you mean to change sepolicy ? To change the SELinux which is disabled, permissive, or enforcing ?

**Comment by Johnn78** [comment]
> [92b305a#diff-df031a3e39488591e9b4c84425c47bbbb7f51787e120511cfa14866f12597176L155](https://github.com/topjohnwu/Magisk/commit/92b305a389bcb0dc7e2b3169134f0a81bac6c513#diff-df031a3e39488591e9b4c84425c47bbbb7f51787e120511cfa14866f12597176L155)
> 
> If you are using sth like systemless hosts, please change module hosts attributes intead

I necessarily use systemless host via build-in module of Magisk because else, Adaway can't be functional. But what do you mean to change module host attribute ? The host as file, I can't change attribute and this is the problem which I opened this thread.

**Comment by aviraxp** [comment]
> > [92b305a#diff-df031a3e39488591e9b4c84425c47bbbb7f51787e120511cfa14866f12597176L155](https://github.com/topjohnwu/Magisk/commit/92b305a389bcb0dc7e2b3169134f0a81bac6c513#diff-df031a3e39488591e9b4c84425c47bbbb7f51787e120511cfa14866f12597176L155)
> > 
> > If you are using sth like systemless hosts, please change module hosts attributes intead
> 
> I necessarily use systemless host via build-in module of Magisk because else, Adaway can't be functional. But what do you mean to change module host attribute ? The host as file, I can't change attribute and this is the problem which I opened this thread.

operate /data/adb/modules/hosts/system/etc/hosts

**Comment by pndwal** [comment]
> What do you mean to change sepolicy ? To change the SELinux which is disabled, permissive, or enforcing ?

Probably not this anyway (but meant the Magisk change/issue, not to change Selinux status)... Try suggestion to change module's hosts file attributes...

**Comment by Johnn78** [comment]
> > What do you mean to change sepolicy ? To change the SELinux which is disabled, permissive, or enforcing ?
> 
> Probably nothing you can change anyway (meant the Magisk change/issue, not to change Selinux status)... Try suggestion to change module's hosts file attributes...

Yes, this I did with help of above comment (by aviraxp) by going to /data/adb/modules/hosts/system/etc/hosts. Now I am looking a way, may exist some a way to make the change permanently because in every restart of mobile then I should change the attribute again.
