### ISSUE TITLE
Magisk doesn't install after flashing patched boot.img

### ISSUE THREAD

**Issue by Hengen42** [topjohnwu/Magisk#8478]
"After flashing the boot.img via fastboot in the bootloader, I am unable to install Magisk. It seems like it is not flashing the boot partition.

My process sequence: I patch the boot.img and flash it via fastboot."

Device: Xiaomi 14T Pro
Android version: 14
Magisk version name: 070719db
Magisk version code: 070719db (28001) (D)

[magisk_log_2024-10-16T00.48.45.log](https://github.com/user-attachments/files/17386303/magisk_log_2024-10-16T00.48.45.log)

**Comment by pndwal** [comment]
GKI compliant A13+ launch version devices now move generic ramdisk to init_boot.img... Need to patch and flash that per Installation Instruction page.

**Comment by Hengen42** [comment]
ah bro thanks. It was installed when I patched and flashed the init_boot file. Thanks.

**Comment by pndwal** [comment]
Please close issue then.
