### ISSUE TITLE
多用户问题

### ISSUE THREAD

**Issue by ghost** [topjohnwu/Magisk#848]
如果多用户模式设置为`仅设备所有者有超级用户权限`，那么在第二用户上的Magisk Manager会提示需要额外的安装。#817 好像解决了这个问题。
如果多用户模式设置为`由设备拥有者管理`，那么一个只在第二用户上安装，主用户上没有安装的应用，无法获得root权限，自动拒绝。~~但如果主用户上也安装了，并且获得了root权限，第二用户上申请时会自动获得，不弹窗。~~(更新：预期行为)
如果多用户模式设置为`各用户独立`，Magisk好像没有确认各个用户上是否都安装了Magisk Manager。

最后，在第二用户上安装的Magisk Manager，Magisk hide可以勾选Android系统(包名：android)，随后系统崩溃。

测试版本，canary release build a54eaf53。主要是逻辑上的问题，日志在这里不能提供有效帮助…按照上面的信息，可以重复触发这些问题。

**Comment by vvb2060** [comment]
稍微看了看。
由所有者管理，是所有用户都使用所有者(user0)的超级用户配置，并且保存时只保存`UID%100000`。你这种情况，由于user0没有这个应用，需要使用隐藏API:getApplicationInfoAsUser，它需要INTERACT_ACROSS_USERS权限。
这些解决后，能显示弹窗并存储策略了，但由于策略存储时UID信息量减少，展示超级用户应用列表时会不知道userid，getApplicationInfoAsUser用不了，只能抛出找不到应用，然后这个策略被删除…

**Comment by NormanBB** [comment]
Please describe the issue in English and mention the exact model, since not everyone here is supposed to understand Chinese.

The developer has complained such kind of (non-standard) phones and showed little interest supporting them.

copied from @kcschan

**Comment by NormanBB** [comment]
Sorry,it was my fault.
