### ISSUE TITLE
Zygisk doesn't work after beta update.

### ISSUE THREAD

**Issue by eakteam** [topjohnwu/Magisk#8483]
Zygisk doesn't work after beta update 28.0.

[magisk_log_2024-10-18T00.07.18.log](https://github.com/user-attachments/files/17423798/magisk_log_2024-10-18T00.07.18.log)

![Screenshot_20241018_000743](https://github.com/user-attachments/assets/0ae36388-878d-4910-94de-b0cbe9b7b06b)

![Screenshot_20241018_000755](https://github.com/user-attachments/assets/88ae51f0-48e8-49ef-a0db-909e213de26f)

Device: Samsung Note 20 5G
Android version: 14
Magisk version name: 28001
Magisk version code: 28001

**Comment by canyie** [comment]
Hello, it looks like the issue is caused by LSPosed. Please disable LSPosed and try again.
