### ISSUE TITLE
Stuck booting to recovery with v18.0 with LineageOS 14.1 on ASUS Zenfone2 (Z00A)

### ISSUE THREAD

**Issue by jaakristioja** [topjohnwu/Magisk#849]
This is my first time installing Magisk, probably did something wrong. I have a LineageOS 14.1 on an ASUS Zenfone2 (Z00A). I didn't install the app, just downloaded the zip for Magisk v18.0 from my laptop, `adb push`ed it, and installed it via TWRP. Then, it only booted to recovery no matter how I tried, no system. ;-(

Possibly related to #729?

Fortunately, after installing the Magisk-uninstaller-20181208.zip from TWRP I was able to boot back to LineageOS.

**Comment by abesty** [comment]
Hi, i think the problem is your bootloader doesn't accept unsigned boot images to loads OS, just try to re-signed it by flash via TWRP https://forum.xda-developers.com/android/software-hacking/signing-boot-images-android-verified-t3600606 i hope it solved your problem

**Comment by krasCGQ** [comment]
On MM bootloader? If yes, try suggestion above or flash modified Magisk on ZenFone 2 subforum.

**Comment by jaakristioja** [comment]
> On MM bootloader?

I have no idea. How do I check?

**Comment by jaakristioja** [comment]
Ok, I managed to install Magisk v16.0 from [here](https://forum.xda-developers.com/zenfone2/general/root-magisk-v16-0-zenfone2-t3759936). Is it safe to let MagiskManager 6.1.0 upgrade Magisk to v18.0?

**Comment by jaakristioja** [comment]
I think I will stick to v16.0 then. Thank you very much for Your help and have a Merry Christmas! :christmas_tree: :santa: =]
