### ISSUE TITLE
Offline charging bug: Custom ROM/stock, Pixel XL (1st gen)

### ISSUE THREAD

**Issue by bdashore3** [topjohnwu/Magisk#850]
I am currently on the December update for the OG pixel XL on the Liquid Remix rom. Stock has fixed the offline charging issue, but I have found that on multiple ROMs that the charging bug isn't fixed. I am not sure how it was fixed on stock. I also need help with logging for this particular issue because the offline charging is impossible to take a log on via adb

Update: same bug happens on stock - Does NOT happen via November update

Magisk Version: Latest Canary

**Comment by topjohnwu** [comment]
Please refer to #906
