### ISSUE TITLE
Phone cant mount partitions after installing magisk (it can manually)

### ISSUE THREAD

**Issue by LiterallyUser** [topjohnwu/Magisk#8518]
Hello! i am experiencing problem with installing magisk. Currently i am using CrDroid 10.1 gsi and every time i install it (replace boot.img) my phone hangs at 'Tecno' logo and doesnt boot. however, if i will run this:

mount /dev/block/mapper/userdata /data -t f2fs -f
mount /dev/block/by-name/prodnv /mnt/vendor -t ext4 -f
mount /dev/block/by-name/socko_a /mnt/vendor/socko
sleep 2
insmod /mnt/vendor/socko/mali_kbase.ko
insmod /mnt/vendor/socko/adaptive-ts.ko

The phone will boot up to os but wont have other modules like camera, figerprint and etc.
Some logs on bootup:
[логи1.txt](https://github.com/user-attachments/files/17546868/1.txt)

Also if i will try to flash install.zip using twrp it will error out with "unsupported image" (probably fstab related)

(i tried multiple magisk versions INCLUDING the latest and dev one)
Device:
Android version: 14
Magisk version name: cant find
Magisk version code: 28001

**Comment by LitteraryUser** [comment]
[mounts.txt](https://github.com/user-attachments/files/17547125/mounts.txt)
^^^ cat /proc/mounts on a working phone

**Comment by LiterallyUser** [comment]
some more 
[logcat magisk 28001 debug.txt](https://github.com/user-attachments/files/17547650/logcat.magisk.28001.debug.txt)
[mounts.txt](https://github.com/user-attachments/files/17547651/mounts.txt)
[proc mount on non booting.txt](https://github.com/user-attachments/files/17547652/proc.mount.on.non.booting.txt)
[dmesg right when phone is available for adb.txt](https://github.com/user-attachments/files/17547653/dmesg.right.when.phone.is.available.for.adb.txt)
stuff

**Comment by theintel** [comment]
Does your phone have vbmeta partition? (Check stock ROM)
If there is vbmeta.img, then you have to add the signature of the modified boot.img to the vbmeta and flash both.

**Comment by LiterallyUser** [comment]
> then you have to add the signature of the modified boot.img
i think its not the case here since magisk works perfectly in stock os

**Comment by LiterallyUser** [comment]
> > then you have to add the signature of the modified boot.img 


 i think its not the case here since magisk works perfectly in stock os

**Comment by theintel** [comment]
I see. And Crdroid doesn’t have  vbmeta either then?

**Comment by LiterallyUser** [comment]
looks like yeah since it is just a gsi. By the way i am manually signing boot image using vbmeta thing

**Comment by LiterallyUser** [comment]
(rsa4096_vbmeta.pem)

**Comment by LiterallyUser** [comment]
(this is the only way to make phone accept boot image and boot, this works perfectly fine on stock os)

**Comment by LiterallyUser** [comment]
also i should mention that it will be in this half-booted state after rooting it if i am using ANY gsi

**Comment by theintel** [comment]
For me, the stock rom had vbmeta. I had to manually sign the modified boot.img, then add that signature to vbmeta_modified.img. After flashing them both, it still didn’t boot. The stock rom was somewhat aggressive. The only way was:

- boot into recovery
- wipe data
- boot into fastboot
- flash vbmeta
- flash boot.img
- boot into recovery again
- wipe data again

Only then it booted without issues. If everything else fails, maybe try this (tiresome) method.

**Comment by LiterallyUser** [comment]
i will try to soon!

**Comment by LiterallyUser** [comment]
my stock image also has vbmeta but it is packed in .pac file and idk how to take it out

**Comment by theintel** [comment]
Pac file? Sounds familiar. Does your phone have spreadtrum (SPD) chipset?

**Comment by LiterallyUser** [comment]
mhm

**Comment by LiterallyUser** [comment]
Unisoc T606

**Comment by theintel** [comment]
Then you have to use SPD Research Tool to unpack that pac file.

**Comment by LiterallyUser** [comment]
Noted.

**Comment by LiterallyUser** [comment]
Gotta to do this now

**Comment by LiterallyUser** [comment]
BUT how to add signature to vbmeta?

**Comment by theintel** [comment]
Long process. But I think I can guide you through.

Pac file tutorial: https://www.hovatek.com/forum/thread-1231.html

**Comment by LiterallyUser** [comment]
i already know how to flash it since i did this multiple time :D

**Comment by theintel** [comment]
vdmeta_modified.img making tutorial: https://www.hovatek.com/forum/thread-32664.html

But first make sure that your rom has vbmeta.img (could be vbmeta_a.img). Check in SPD Upgrade Tool flashing page.

**Comment by LiterallyUser** [comment]
i am using this tool to sign boot tho-

**Comment by LiterallyUser** [comment]
for some reason when i am trying to load image in research tool it says "error 3508"

**Comment by theintel** [comment]
BTW, many versions of SPD Upgrade Tool / Research Tool couldn’t flash my device successfully. I had try them one by one until I found a working version.

So make sure that you can successfully flash the stock/custom rom before tweaking partitions. Things can go wrong very often.

**Comment by LiterallyUser** [comment]
for some reason only upgrade tool works for my rom

**Comment by theintel** [comment]
Keep trying these until you find a working one: https://spdflashtool.com/category/research-tool

For me, Research Tool version R23.19.3301 worked.

**Comment by LiterallyUser** [comment]
THIS ONE WORKED!

**Comment by LiterallyUser** [comment]
it seems like there are 5 vbmetas....

**Comment by theintel** [comment]
vbmeta_a.img matters the most. Ignore others for now. Is there any vbmeta_b.img?

**Comment by theintel** [comment]
> THIS ONE WORKED!

Can you imagine that they provide broken software releases!

**Comment by LiterallyUser** [comment]
nope, only a

**Comment by LiterallyUser** [comment]
the a\b thingy is kinda broken on this device

**Comment by theintel** [comment]
> nope, only a

OK cool. Keep going. You need to extract signatures one by one and save them. Long process. Needs hex editing. Take your time. Don't rush anything. One bit of wrongly copied hex data can ruin hours of work.

> the a\b thingy is kinda broken on this device

That's Unisoc way of doing things maybe.

**Comment by LiterallyUser** [comment]
it looks like whole thing hanged and now everything expect browser for some reason is irresponsive

**Comment by LiterallyUser** [comment]
oh, i see why now, i have 0kb of storage left. Well, i will clean stuff out and will continue this thing, however its kind of late time for me rn

**Comment by theintel** [comment]
> oh, i see why now, i have 0kb of storage left. Well, i will clean stuff out and will continue this thing, however its kind of late time for me rn

I'm tired too. TTYL.

**Comment by mgnoon009** [comment]
[](url)

**Comment by LiterallyUser** [comment]
Problem solved after installing android 12 gsi

**Comment by LiterallyUser** [comment]
So it looks like my phone just stops working correctly with modified boot on new gsis, android 12 lineage worked so problem solved

**Comment by theintel** [comment]
Great!

**Comment by ayrahandra** [comment]
Excuse me sir, can you teach how to? I try to flash some gsi Rom too but can progress cause the tutorial say that i need too flash system' but ADB saus error' to erase

**Comment by theintel** [comment]
I can't. Maybe @LiterallyUser can.
