### ISSUE TITLE
OnePlus Nord rebooting into fastboot when booting patched boot.img with magisk v28 (27005+) 

### ISSUE THREAD

**Issue by LoryKiller** [topjohnwu/Magisk#8532]
If I root my OnePlus Nord using Magisk v27 it works, if I try to update to Magisk v28 (but I'm experiencing this since magisk 27005) the device reboots into the bootloader until I flash stock boot.img

[logcat.log](https://github.com/user-attachments/files/17619498/logcat.log)
[dmesg.log](https://github.com/user-attachments/files/17619499/dmesg.log)
[procmounts.log](https://github.com/user-attachments/files/17619504/proc.mounts.log) 
[console-ramoops-0.log](https://github.com/user-attachments/files/17619543/console-ramoops-0.log) (not sure why it looks like that)

Device: Oneplus Nord (avicii)
Android version: 12
Magisk version name: v28
Magisk version code: 28001 debug

**Comment by MOOOOs** [comment]
On the OnePlus 7 Pro, Android 10 experienced a similar issue after flashing Magisk 28 through the app; it was functioning properly until I attempted to boot into TWRP. My recovery was missing, and I was unable to boot into TWRP; the screen was black, and after reflashing TWRP, it would only boot into TWRP and not into the system. The only solution was to restore an older backup image.

**Comment by LoryKiller** [comment]
Apparently the issue was caused by the pixelify module as previously stated here [#8377 ](https://github.com/topjohnwu/Magisk/issues/8377)
I uninstalled that module and after flashing patched boot.img Android boots normally
I'm not sure why the issue was stated at not planned, pixelify is a common module it's a shame I can't install it
