### ISSUE TITLE
[Feature Request] Please resume 64-bit support

### ISSUE THREAD

**Issue by mirfatif** [topjohnwu/Magisk#854]
I run Linux on my phone inside chroot and namespaces (which obviously requires root access). I need 64 bit so that my login and hence subsequent processes run as aarch64. If the architecture is 32-bit (e.g. uanme -m shows armv8l), building/compiling environment is disturbed resulting in errors or 32-bit libraries/binaries.

**Comment by DenyDarko** [comment]
Check @ianmacd builds.

As far as I remember his builds do have what you ask

**Comment by mirfatif** [comment]
@DenyDarko he stopped support for arm64 builds

**Comment by ianmacd** [comment]
I rebuilt 64 bit versions again a few days ago as a test, but arm64 magiskinit segfaults on boot now and I haven't been able to trace the fault. This means I can't simply re-include 64 bit binaries in my unofficial builds.

The right place to offer 64 bit binaries is here in the official builds, if John recognises and agrees with the motivation for them.

**Comment by mirfatif** [comment]
@topjohnwu appreciated. Thanks.

**Comment by topjohnwu** [comment]
@mirfatif please wait for a few days before the official canary drops :)

**Comment by m132** [comment]
> I need 64 bit so that my login and hence subsequent processes run as aarch64.

You don't, you just want to run `setarch linux64` after `su`

**Comment by mirfatif** [comment]
@m132 and what if even I didn't know that any such thing existed? :D
Thanks, it's a good thing to play with.
