### ISSUE TITLE
[BUG] Zygisk doesn't work on latest Android 15

### ISSUE THREAD

**Issue by HarriBuh** [topjohnwu/Magisk#8540]
Device: Google Pixel 7
Android version: Android 15, November patch
Magisk version name:  070719db (?)
Magisk version code: 28001

Just updated my phone to the very latest Android 15 version (although I skipped the initial 15 release in October) and Zygisk doesn't seem to work at all, even when turned "ON"

![Screenshot_20241107-104049.png](https://github.com/user-attachments/assets/a712b34a-76b8-4edb-9036-69d7ea6f2cea)

![Screenshot_20241107-104102.png](https://github.com/user-attachments/assets/fb4f8c8d-20bc-4189-b16e-3b7a9a996c7a)

Just recognised contradictory information on the app:

![Screenshot_20241107-104707.png](https://github.com/user-attachments/assets/8b117841-3e77-4b25-a184-0e191178e5a0)

**Comment by canyie** [comment]
More likely caused by LSPosed
