### ISSUE TITLE
[Xiaomi 14 Pro]Zygisk not work after HyperOS2 Update

### ISSUE THREAD

**Issue by simila** [topjohnwu/Magisk#8562]
Device:Xiaomi 14 Pro
Android version:15
Magisk version name:v28.0
Magisk version code:28001(D)

I have installed Magisk on this device.Zygisk will not work after HyperOS2 update.It always shown need to reboot.
[magisk_log_2024-11-17T10.17.58.log](https://github.com/user-attachments/files/17788603/magisk_log_2024-11-17T10.17.58.log)

Magisk log attached.

**Comment by canyie** [comment]
Someone has tested the Zygisk feature and confirmed it is working properly on HyperOS 2. Your issue is likely caused by LSPosed. Try disabling it and try again.
