### ISSUE TITLE
Magisk reports ambiguous error for invalid module zip

### ISSUE THREAD

**Issue by mokurin000** [topjohnwu/Magisk#8579]
Device: POCO F2 Pro
Android version: 14
Magisk version name: 070719db
Magisk version code: 28001

When try to install a module without `META-INF/com/google/android/updater-script` (mis-typed as update-script), Magisk just complains '!Unzip error', no useful error hint was given.

**Comment by canyie** [comment]
Yeah, I agree that we should print something that is more useful. Related code:

https://github.com/topjohnwu/Magisk/blob/b32d7bfafd2da3092ecc4720fd9fd1e3c041a808/app/core/src/main/java/com/topjohnwu/magisk/core/tasks/FlashZip.kt#L50-L62

**Comment by aviraxp** [comment]
https://github.com/topjohnwu/Magisk/pull/8416
