### ISSUE TITLE
Magisk blocks OTA updates

### ISSUE THREAD

**Issue by Martmists-GH** [topjohnwu/Magisk#8599]
The update engine seems to try to validate hashes, but this fails because the boot image has a different hash:

```
E/update_engine( 2082): [1205/130621.176402:ERROR:verified_source_fd.cc(50)] Unable to open ECC source partition /dev/block/bootdevice/by-name/boot_a: Success (0)
E/update_engine( 2082): [1205/130621.176516:ERROR:partition_writer.cc(362)] The hash of the source data on disk for this operation doesn't match the expected value. This could mean that the delta update payload was targeted for another version, or that the source partition was modified after it was installed, for example, by mounting a filesystem.
E/update_engine( 2082): [1205/130621.176564:ERROR:partition_writer.cc(367)] Expected:   sha256|hex = 823C3D9D5EEA8C1F03B508B06900E61DFC561A09E323986525515FA3D17CDE18
E/update_engine( 2082): [1205/130621.176605:ERROR:partition_writer.cc(370)] Calculated: sha256|hex = 9C3F3C060B651A3D8DE5E26518F7E20E7BF06FB6308E06391E79508D1C0B3A87
E/update_engine( 2082): [1205/130621.176649:ERROR:partition_writer.cc(381)] Operation source (offset:size) in blocks: 0:1,11384:1,11442:510
E/update_engine( 2082): [1205/130621.176703:ERROR:partition_writer.cc(306)] source_fd != nullptr failed.
E/update_engine( 2082): [1205/130621.176741:ERROR:delta_performer.cc(938)] partition_writer_->PerformDiffOperation( operation, error, buffer_.data(), buffer_.size()) failed.
E/update_engine( 2082): [1205/130621.185465:ERROR:partition_writer.cc(362)] The hash of the source data on disk for this operation doesn't match the expected value. This could mean that the delta update payload was targeted for another version, or that the source partition was modified after it was installed, for example, by mounting a filesystem.
E/update_engine( 2082): [1205/130621.185572:ERROR:partition_writer.cc(367)] Expected:   sha256|hex = 823C3D9D5EEA8C1F03B508B06900E61DFC561A09E323986525515FA3D17CDE18
E/update_engine( 2082): [1205/130621.185615:ERROR:partition_writer.cc(370)] Calculated: sha256|hex = 9C3F3C060B651A3D8DE5E26518F7E20E7BF06FB6308E06391E79508D1C0B3A87
E/update_engine( 2082): [1205/130621.185658:ERROR:partition_writer.cc(381)] Operation source (offset:size) in blocks: 0:1,11384:1,11442:510
E/update_engine( 2082): [1205/130621.185707:ERROR:partition_writer.cc(306)] source_fd != nullptr failed.
E/update_engine( 2082): [1205/130621.185744:ERROR:delta_performer.cc(938)] partition_writer_->PerformDiffOperation( operation, error, buffer_.data(), buffer_.size()) failed.
E/update_engine( 2082): [1205/130621.193412:ERROR:partition_writer.cc(362)] The hash of the source data on disk for this operation doesn't match the expected value. This could mean that the delta update payload was targeted for another version, or that the source partition was modified after it was installed, for example, by mounting a filesystem.
E/update_engine( 2082): [1205/130621.193501:ERROR:partition_writer.cc(367)] Expected:   sha256|hex = 823C3D9D5EEA8C1F03B508B06900E61DFC561A09E323986525515FA3D17CDE18
E/update_engine( 2082): [1205/130621.193543:ERROR:partition_writer.cc(370)] Calculated: sha256|hex = 9C3F3C060B651A3D8DE5E26518F7E20E7BF06FB6308E06391E79508D1C0B3A87
E/update_engine( 2082): [1205/130621.193587:ERROR:partition_writer.cc(381)] Operation source (offset:size) in blocks: 0:1,11384:1,11442:510
E/update_engine( 2082): [1205/130621.193635:ERROR:partition_writer.cc(306)] source_fd != nullptr failed.
E/update_engine( 2082): [1205/130621.193671:ERROR:delta_performer.cc(938)] partition_writer_->PerformDiffOperation( operation, error, buffer_.data(), buffer_.size()) failed.
E/update_engine( 2082): [1205/130621.193722:ERROR:delta_performer.cc(211)] Failed to perform BROTLI_BSDIFF operation 4401, which is the operation 0 in partition "boot"
E/update_engine( 2082): [1205/130621.193771:ERROR:download_action.cc(227)] Error ErrorCode::kDownloadStateInitializationError (20) in DeltaPerformer's Write method when processing the received payload -- Terminating processing
```

For devices without a supported TWRP, this means the device is permanently locked into an old version and unable to receive updates.

Device: OnePlus 8T
Android version: 13
Magisk version name: ?
Magisk version code: 28003

**Comment by Wolf-bit-tech** [comment]
E/update_engine( 2082): [1205/130621.176402:ERROR:verified_source_fd.cc(50)] Unable to open ECC source partition /dev/block/bootdevice/by-name/boot_a: Success (0)
E/update_engine( 2082): [1205/130621.176516:ERROR:partition_writer.cc(362)] The hash of the source data on disk for this operation doesn't match the expected value. This could mean that the delta update payload was targeted for another version, or that the source partition was modified after it was installed, for example, by mounting a filesystem.
E/update_engine( 2082): [1205/130621.176564:ERROR:partition_writer.cc(367)] Expected:   sha256|hex = 823C3D9D5EEA8C1F03B508B06900E61DFC561A09E323986525515FA3D17CDE18
E/update_engine( 2082): [1205/130621.176605:ERROR:partition_writer.cc(370)] Calculated: sha256|hex = 9C3F3C060B651A3D8DE5E26518F7E20E7BF06FB6308E06391E79508D1C0B3A87
E/update_engine( 2082): [1205/130621.176649:ERROR:partition_writer.cc(381)] Operation source (offset:size) in blocks: 0:1,11384:1,11442:510
E/update_engine( 2082): [1205/130621.176703:ERROR:partition_writer.cc(306)] source_fd != nullptr failed.
E/update_engine( 2082): [1205/130621.176741:ERROR:delta_performer.cc(938)] partition_writer_->PerformDiffOperation( operation, error, buffer_.data(), buffer_.size()) failed.
E/update_engine( 2082): [1205/130621.185465:ERROR:partition_writer.cc(362)] The hash of the source data on disk for this operation doesn't match the expected value. This could mean that the delta update payload was targeted for another version, or that the source partition was modified after it was installed, for example, by mounting a filesystem.
E/update_engine( 2082): [1205/130621.185572:ERROR:partition_writer.cc(367)] Expected:   sha256|hex = 823C3D9D5EEA8C1F03B508B06900E61DFC561A09E323986525515FA3D17CDE18
E/update_engine( 2082): [1205/130621.185615:ERROR:partition_writer.cc(370)] Calculated: sha256|hex = 9C3F3C060B651A3D8DE5E26518F7E20E7BF06FB6308E06391E79508D1C0B3A87
E/update_engine( 2082): [1205/130621.185658:ERROR:partition_writer.cc(381)] Operation source (offset:size) in blocks: 0:1,11384:1,11442:510
E/update_engine( 2082): [1205/130621.185707:ERROR:partition_writer.cc(306)] source_fd != nullptr failed.
E/update_engine( 2082): [1205/130621.185744:ERROR:delta_performer.cc(938)] partition_writer_->PerformDiffOperation( operation, error, buffer_.data(), buffer_.size()) failed.
E/update_engine( 2082): [1205/130621.193412:ERROR:partition_writer.cc(362)] The hash of the source data on disk for this operation doesn't match the expected value. This could mean that the delta update payload was targeted for another version, or that the source partition was modified after it was installed, for example, by mounting a filesystem.
E/update_engine( 2082): [1205/130621.193501:ERROR:partition_writer.cc(367)] Expected:   sha256|hex = 823C3D9D5EEA8C1F03B508B06900E61DFC561A09E323986525515FA3D17CDE18
E/update_engine( 2082): [1205/130621.193543:ERROR:partition_writer.cc(370)] Calculated: sha256|hex = 9C3F3C060B651A3D8DE5E26518F7E20E7BF06FB6308E06391E79508D1C0B3A87
E/update_engine( 2082): [1205/130621.193587:ERROR:partition_writer.cc(381)] Operation source (offset:size) in blocks: 0:1,11384:1,11442:510
E/update_engine( 2082): [1205/130621.193635:ERROR:partition_writer.cc(306)] source_fd != nullptr failed.
E/update_engine( 2082): [1205/130621.193671:ERROR:delta_performer.cc(938)] partition_writer_->PerformDiffOperation( operation, error, buffer_.data(), buffer_.size()) failed.
E/update_engine( 2082): [1205/130621.193722:ERROR:delta_performer.cc(211)] Failed to perform BROTLI_BSDIFF operation 4401, which is the operation 0 in partition "boot"
E/update_engine( 2082): [1205/130621.193771:ERROR:download_action.cc(227)] Error ErrorCode::kDownloadStateInitializationError (20) in DeltaPerformer's Write method when processing the received payload -- Terminating processing

**Comment by Martmists-GH** [comment]
I also tried following the [Guide](https://topjohnwu.github.io/Magisk/ota.html), but after Magisk tells me to reboot from System Updates, that runs into an error:

```
W/SystemUpdate( 7081): [Execution,AbRebootAction] Failed to switch boot slot.
W/SystemUpdate( 7081): dxhm: Failed to set slot switch to: true Update engine error code: 15
W/SystemUpdate( 7081): 	at dxhn.i(:com.google.android.gms@244631030@24.46.31 (190408-699197446):729)
W/SystemUpdate( 7081): 	at dxhn.a(:com.google.android.gms@244631030@24.46.31 (190408-699197446):827)
W/SystemUpdate( 7081): 	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@244631030@24.46.31 (190408-699197446):150)
W/SystemUpdate( 7081): 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@244631030@24.46.31 (190408-699197446):2)
W/SystemUpdate( 7081): 	at akar.onHandleIntent(:com.google.android.gms@244631030@24.46.31 (190408-699197446):8)
W/SystemUpdate( 7081): 	at opv.run(:com.google.android.gms@244631030@24.46.31 (190408-699197446):70)
W/SystemUpdate( 7081): 	at opu.run(:com.google.android.gms@244631030@24.46.31 (190408-699197446):152)
W/SystemUpdate( 7081): 	at expj.run(:com.google.android.gms@244631030@24.46.31 (190408-699197446):21)
W/SystemUpdate( 7081): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/SystemUpdate( 7081): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/SystemUpdate( 7081): 	at java.lang.Thread.run(Thread.java:1012)
```

Rebooting manually will get stuck and kick me to Recovery, I have to switch back to slot A in fastboot to get my device working again.

**Comment by osm0sis** [comment]
Here's what I found to work on my OnePlus devices. 
https://xdaforums.com/t/tools-zips-scripts-osm0sis-odds-and-ends-multiple-devices-platforms.2239421/page-149#post-84764713

**Comment by Martmists-GH** [comment]
How did you dump the boot image using that process? android-ota-extractor doesn't seem to support delta files.

**Comment by osm0sis** [comment]
Just the normal way by command line.

**Comment by osm0sis** [comment]
Anyway, long story short, Magisk can't do anything about the boot hash checking, but that's what the Restore Images option is for, and if done in the right order an OTA can work correctly, but the instructions can vary by manufacturer.
