### ISSUE TITLE
Root permission never prompts under latest December 2018 Nokia 7 Android 9.0 build

### ISSUE THREAD

**Issue by HikariCalyx** [topjohnwu/Magisk#861]
Phone: Nokia 7 (TA-1041)
Build version: C1N-347A-0-00CN-B01

After this build installed, I've tried Magisk 17.1 to latest canary release, Magisk will never prompt for root permission.
Of course I've tried completely remove magisk before reinstalling it.

```
09-01 14:24:01.183   626   626 I Magisk  : * Creating /sbin overlay
09-01 14:24:01.216   628   628 I Magisk  : Magisk v18.1-b245931c(18002) daemon started
09-01 14:24:01.226   628   629 I Magisk  : ** post-fs-data mode running
09-01 14:24:01.226   628   629 I Magisk  : * Initializing Magisk environment
09-01 14:24:01.229   628   629 I Magisk  : * Mounting mirrors
09-01 14:24:01.231   628   629 I Magisk  : bind_mount: /sbin/.magisk/mirror/system
09-01 14:24:01.231   628   629 I Magisk  : mount: /sbin/.magisk/mirror/vendor
09-01 14:24:01.232   628   629 I Magisk  : bind_mount: /sbin/.magisk/mirror/bin
09-01 14:24:01.233   628   629 I Magisk  : * Setting up internal busybox
09-01 14:24:01.271   634   634 I Magisk  : Magisk v18.1-b245931c(18002) logger started
09-01 14:24:01.325   628   629 I Magisk  : * Mounting /data/adb/magisk.img
09-01 14:24:01.404   628   629 I Magisk  : * Running post-fs-data.d scripts
09-01 14:24:01.405   628   629 I Magisk  : * Running module post-fs-data scripts
09-01 14:24:01.405   628   629 I Magisk  : * Loading modules
09-01 14:24:01.418   628   650 I Magisk  : * Starting MagiskHide
09-01 14:24:01.418   628   650 I Magisk  : hide_utils: Hiding sensitive props
09-01 14:24:01.419   628   650 I Magisk  : hide_list: [com.google.android.gms/.droidguard.DroidGuardService]
12-13 00:10:28.486   628  1139 I Magisk  : ** late_start service mode running
12-13 00:10:28.487   628  1139 I Magisk  : * Running service.d scripts
12-13 00:10:28.526   628  1139 I Magisk  : * Running module service scripts
12-13 00:12:25.459  5887  5887 W Magisk  : su: request rejected (10250->0)
12-13 00:14:02.619  6230  6230 W Magisk  : su: request rejected (2000->0)
```

Stock boot: https://drive.google.com/file/d/1WbZxU_PpB_jAru_7dguJ7GZtdOlm2jzH/view?usp=drivesdk
Logcat: [logcat.txt](https://github.com/topjohnwu/Magisk/files/2672654/logcat.txt)

**Comment by yuankongk** [comment]
7+ is the same

**Comment by soridal** [comment]
Google Pixel / same issue!!

**Comment by MrAnderson187** [comment]
Same issue but i have
"su: request rejected (10086->0)" 
Honor 8 FRD-L09C432
Android 8
Magisk 18.0 (Beta Channel)

**Comment by braveheartleo** [comment]
The same `su: request rejected` log entries are also encountered running
`Magisk-v18.0` on `Nokia/Onyx_00WW/B2N_sprout:9/PPR1.180610.011/00WW_3_39D:user/release-keys`.

**Comment by noto10** [comment]
I have the same issue with Samsung Note, Android 5.

Magisk 18-stable installed without error but root functions are gone. Apps do not trigger su requests. Going back to Magisk 17.0 restored root. Also tried v18-canary which does not work as well.

Got a bunch of these:

`07-19 00:10:34.549   256   395 I Magisk  : ** late_start service mode running
07-19 00:10:34.549   256   395 I Magisk  : * Running service.d scripts
07-19 00:10:34.549   256   395 I Magisk  : * Running module service scripts
07-19 00:10:34.549   256   400 I Magisk  : * Starting MagiskHide
07-19 00:10:34.559   256   400 I Magisk  : hide_utils: Hiding sensitive props
07-19 00:10:34.559   256   400 I Magisk  : hide_list: [com.google.android.gms.unstable]
07-19 00:10:34.939   256   400 E Magisk  : proc_monitor: Your kernel doesn't support mount namespace :(
12-14 08:46:48.406  7718  7718 E Magisk  : write failed with 32: Broken pipe
12-14 08:46:48.406  7718  7718 E Magisk  : readlink /proc/3998/cwd failed with 2: No such file or directory
12-14 08:46:48.406  7718  7718 E Magisk  : read failed with 9: Bad file number
12-14 08:46:48.406  7718  7718 E Magisk  : read failed with 9: Bad file number
12-14 08:46:48.406  7718  7718 E Magisk  : read failed with 14: Bad address
12-14 08:46:48.406  7718  7718 E Magisk  : read failed with 14: Bad address
12-14 08:46:48.406  7718  7718 E Magisk  : dup2 failed with 9: Bad file number
12-14 08:46:48.406  7718  7718 E Magisk  : dup2 failed with 9: Bad file number
12-14 08:46:48.406  7718  7718 E Magisk  : dup2 failed with 9: Bad file number
12-14 08:46:48.406  7718  7718 W Magisk  : su: request rejected (10270->0)
12-14 08:47:43.046 10492 10492 W Magisk  : su: request rejected (10314->0)
12-14 08:48:09.676 11965 11965 E Magisk  : write failed with 32: Broken pipe
12-14 08:48:09.676 11965 11965 E Magisk  : readlink /proc/8908/cwd failed with 2: No such file or directory
12-14 08:48:09.676 11965 11965 E Magisk  : read failed with 9: Bad file number
12-14 08:48:09.676 11965 11965 E Magisk  : read failed with 9: Bad file number
12-14 08:48:09.676 11965 11965 E Magisk  : read failed with 14: Bad address
12-14 08:48:55.166 14966 14966 W Magisk  : su: request rejected (10270->0)
12-14 08:49:42.066 17408 17408 W Magisk  : su: request rejected (10268->0)
12-14 08:49:56.376 18227 18227 W Magisk  : su: request rejected (10318->0)
12-14 08:49:59.606 18453 18453 W Magisk  : su: request rejected (10318->0)
12-14 08:50:42.816 20522 20522 W Magisk  : su: request rejected (10268->0)
12-14 08:51:43.016 21433 21433 W Magisk  : su: request rejected (10268->0)
12-14 08:52:08.486 21745 21745 E Magisk  : write failed with 32: Broken pipe
12-14 08:52:08.496 21745 21745 E Magisk  : readlink /proc/20888/cwd failed with 2: No such file or directory
12-14 08:52:08.496 21745 21745 E Magisk  : read failed with 9: Bad file number`

**Comment by hkzlab** [comment]
Issue with similar effects on my Wiko View 2 GO with Android 8.1 .
I have yet to try with magisk 17.x, if it can even be done, as this phone requires to manually patch the boot.img and flash it via fastboot.

**Comment by topjohnwu** [comment]
Magisk Manager requires `BOOT_COMPLETED` broadcast to be able to deliver to the app. Some system in Chinese devices tend to block these broadcasts by default. You need to whitelist Magisk Manager from "battery optimized" or something like that in order for root prompt to work properly.

**Comment by danupri** [comment]
I have white list Magisk Mngr from batt optimation in Redmi note 2 still no root akses

**Comment by raku-cat** [comment]
Can also confirm on the mi max 3 with xiaomi.eu I get no root prompts, existing apps with permission do work though, I had assumed this was to do with me enabling the repackaging but it seems not. I have disabled battery optimization on the manager app, not really anywhere else to turn something like that off, battery saver and adaptive battery are also off.

**Comment by kongwy** [comment]
The same problem appears in my Nokia 7 too. @HikariCalyx provided me a solution and it works. I believe it will be better to be attached here in case anyone needs it:

1. Clear storage of Magisk Manager in the "Storage" page of "App info". Then re-grant the permissions of "Storage" and "run at startup". 

2. Also, grant the permission of lock screen continue running by tick the checkbox in system built-in "Background activity manager".

3. Reboot your device. (if necessary)

**Comment by Humorize** [comment]
I used an APP which can disable and enable other APPs' broadcast reciever to enable Magisk's all broadcast reciever, then Root Access Prompt appears normally.

My phone is Xiaomi Max 2 with MIUI 10.3 by Xiaomi.EU 9.3.28 Beta based on Android 7.1.1
Magisk's version is 18.1, Magisk Manager's version is 7.1.1

**Comment by gowinder** [comment]
> I used an APP which can disable and enable other APPs' broadcast reciever to enable Magisk's all broadcast reciever, then Root Access Prompt appears normally.
> 
> My phone is Xiaomi Max 2 with MIUI 10.3 by Xiaomi.EU 9.3.28 Beta based on Android 7.1.1
> Magisk's version is 18.1, Magisk Manager's version is 7.1.1

what is the app name

**Comment by Jasi2169** [comment]
This needs to be fixed and analyzed properly i have been having this issue from long since s7 nougat oreo n pie all having this issue @topjohnwu

**Comment by Jasi2169** [comment]
try this @HikariCalyx 

https://forum.xda-developers.com/apps/magisk/magisk-root-granter-v1-0-t3925037

**Comment by martobg10** [comment]
> Magisk Manager requires `BOOT_COMPLETED` broadcast to be able to deliver to the app. Some system in Chinese devices tend to block these broadcasts by default. You need to whitelist Magisk Manager from "battery optimized" or something like that in order for root prompt to work properly.

Please, any fix for kitkat? :(
