### ISSUE TITLE
Fingerprint sensor error

### ISSUE THREAD

**Issue by JoanVC100** [topjohnwu/Magisk#862]
Hello again. The fingerprint with my Elephone S7 x25 Edition with Android 6.0.1 wasn't working after the Magisk update. I tried to downgrade to 17.3 but the sensor isn't working anyways.

I leave here the Magisk log after booting:

[magisk.log](https://github.com/topjohnwu/Magisk/files/2672860/magisk.log)

**Comment by Lourens-Rich** [comment]
Same issue on Huawei Nova Lite 2017 (SLA-L22) on Android 7. This happened when i update Magisk from 17.2 to 18.

**Comment by JoanVC100** [comment]
Lourens, could you provide a magisk log with the latest canary build with the phone so you can make things easier for people to investigate what could be the problem? Thanks.

**Comment by blairfancy** [comment]
Same issue for me and my Huawei SLA_L02

**Comment by JoanVC100** [comment]
Same for you, could you provide a magisk log with the latest canary build with your phone so you can make things easier for people to investigate what could be the problem? Thanks.

**Comment by blairfancy** [comment]
i m not an expert in magisk but if you guide me probably i can retreive the file you need.

**Comment by JoanVC100** [comment]
https://forum.xda-developers.com/apps/magisk/dev-magisk-canary-channel-bleeding-edge-t3839337

Here you have the instructions. You have to install canary magisk and then, when you have it installed and booted, you have to follow this:

Magisk bugs:
Magisk logs are placed in /cache/magisk.log (For A/B devices, they are actually in /data/cache/magisk.log)

Then you attach the magisk.log into a comment.

**Comment by blairfancy** [comment]
Sorry but instruction is not clear enough to succeed. First my twrp is buggy i cant install magisk-debug.zip.
I tried to install magisk debug  apk but no option available to install debug version of magisk

**Comment by JoanVC100** [comment]
@blairfancy Try uninstalling normal magisk with the canary uninstaller and then try it again

**Comment by blairfancy** [comment]
Here are log you have requested:
`01-07 12:12:13.318   399   399 I Magisk  : * Creating /sbin overlay
01-07 12:12:13.378   401   401 I Magisk  : * Device API level: 24
01-07 12:12:13.379   401   401 I Magisk  : Magisk v18.2-b3140276(18101) daemon started
01-07 12:12:13.390   401   402 I Magisk  : ** post-fs-data mode running
01-07 12:12:13.390   401   402 I Magisk  : * Initializing Magisk environment
01-07 12:12:13.836   401   402 I Magisk  : * Mounting mirrors
01-07 12:12:13.839   401   402 I Magisk  : mount: /sbin/.magisk/mirror/system <- /dev/block/bootdevice/by-name/system
01-07 12:12:13.839   401   402 I Magisk  : mount: /sbin/.magisk/mirror/vendor <- /dev/block/bootdevice/by-name/vendor
01-07 12:12:13.839   401   402 I Magisk  : bind_mount: /sbin/.magisk/mirror/bin <- /data/adb/magisk
01-07 12:12:13.839   401   402 I Magisk  : * Setting up internal busybox
01-07 12:12:13.902   407   407 I Magisk  : Magisk v18.2-b3140276(18101) logger started
01-07 12:12:13.974   401   402 I Magisk  : * Running post-fs-data.d scripts
01-07 12:12:13.982   401   402 I Magisk  : * Mounting /data/adb/magisk.img
01-07 12:12:14.156   401   402 E Magisk  : mount /sbin/.magisk/block/loop08->/sbin/.magisk/img failed with 13: Permission denied
01-07 12:12:14.160   401   402 I Magisk  : * Running module post-fs-data scripts
01-07 12:12:14.160   401   402 I Magisk  : * Loading modules
02-08 20:50:03.209   401   711 I Magisk  : ** late_start service mode running
02-08 20:50:03.210   401   711 I Magisk  : * Running service.d scripts
02-08 20:50:03.220   401   711 I Magisk  : * Running module service scripts
02-08 20:52:37.626  9058  9058 W Magisk  : su: request rejected (2000->0)`

**Comment by blairfancy** [comment]
[magisk.log](https://github.com/topjohnwu/Magisk/files/2846735/magisk.log)

**Comment by xerta555** [comment]
Same issue for me with my LG device.

**Comment by JoanVC100** [comment]
@xerta555 Did you even read this post? Can you send the magisk log with the cannsry build, please?

**Comment by xerta555** [comment]
> @xerta555 Did you even read this post? Can you send the magisk log with the cannsry build, please?

@JoanVC100 @Lourens-Rich @blairfancy 
The suggestion of Didgeridoohan have works for me:
https://forum.xda-developers.com/showpost.php?p=78883712&postcount=31277

In some words:
- remove your fingerprint in your Settings app
- adding again your fingerprint through your Settings app
- remove any app that have root access in Magisk Manager
- open the app that request the root access
- use your finger to allow the root access for the app

**Comment by JoanVC100** [comment]
The problem is that fingerprint in Settings app isn't available after flashing magisk on the phone, like if never existed any fingerprint sensor in the phone.

**Comment by xerta555** [comment]
> The problem is that fingerprint in Settings app isn't available after flashing magisk on the phone, like if never existed any fingerprint sensor in the phone.

On wich type of ROM this problem has been reported ? (stock/custom) ?

**Comment by JoanVC100** [comment]
@xerta555 Stock

**Comment by xerta555** [comment]
> Stock

Ok, i'm on custom ROM.
Have u tried to reproduice it with a custom ROM ?

**Comment by JoanVC100** [comment]
@xerta555 I will try this weekend Lineage 14

**Comment by blairfancy** [comment]
Still not work with magisk 18.1 after install patched boot with fastboot fingerprint option disapear from menu

**Comment by xerta555** [comment]
> Still not work with magisk 18.1 after install patched boot with fastboot fingerprint option disapear from menu

Have you tried the suggestion i linked ?

**Comment by blairfancy** [comment]
Unfortunately there are no custom firmware for my phone. I can share patched boot if you want have a look to find root cause.

**Comment by Naviss53** [comment]
Same issue with Huawei Nova. Rollback from 18.1 to 17.3 resolved the issue.

**Comment by blairfancy** [comment]
@Naviss53 Witch magisk manager were used to flash 17.3?

**Comment by Naviss53** [comment]
I did a complete uninstall from the last magisk manager and i copied the magisk 17.3 zip on the phone. i did a reboot in TWRP and flashed the 17.3 zip and wiped dalvik cache and cache. I only installed the Magisk manager 6.1.0 apk  after that by downloading it and manually installed from Android.
