### ISSUE TITLE
Oneplus 6/6T Charging Bug

### ISSUE THREAD

**Issue by LeonZewe** [topjohnwu/Magisk#863]
On the latest Magisk version (v18.0), the phone will not display the charging animation when you try to charge the device while off. As soon as you plug it in, the "This device is unlocked" screen shows up and it gets stuck there. After some experimenting I noticed that the device does indeed charge, it just doesn't display the animation and the screen never turns off.

**Comment by 10330384** [comment]
The same as Pixel devices, like #597 .
It reproduce at **PQ1A.181205.002, Dec 2018**  **Magisk v18.0**

**Comment by NeonUniverse** [comment]
I have a 6 and 6T, can confirm this happens

**Comment by ebiel** [comment]
I can confirm the issue.
device: OnePlus 6
Android: Oxygen OS 9.0.2
Magisk: 18.0

There is some discussion/reporting going on over at xda:
https://forum.xda-developers.com/oneplus-6/help/stucked-bootloader-message-charging-t3859775/

To the devs: Thank you so much for all your effort.

**Comment by topjohnwu** [comment]
Please refer to #906
