### ISSUE TITLE
Critical Security Gap

### ISSUE THREAD

**Issue by OmarAwjy** [topjohnwu/Magisk#8635]
Device:Samsung Galaxy S21
Magisk version name:28101
Magisk version code:28101

Magisk "User Authentication" is made for protecting root access when user's phone is not in his hands, When we enable "User Authentication" all superuser requests should be assigned with user's password, but unfortunately, Magisk "Automatic Response" option completely conflicts with it, even if "User Authentication" is enabled, the "Automatic Response" option state can be changed without "User Authentication", if you changed it to "Grant", it won't prompt for User's password, and, it will grant all superuser requests for apps without User Authentication even if it's enabled, I'm asking The Magisk Team to fix this user security problem ASAP, Thanks.

EDIT : I strongly recommend to add the user's password protection for the entrie Magisk Manager app, this will protect unauthorised modules to be installed or removed, as some modules can remove the whole User's password.

**Comment by akano12** [comment]
If someone have physical access to an asset, whatever protections and measure you take become useless. 


Let's not dive deep into how someone with physical access can uninstall then reinstall magisk app to reset your preferences, or flash any binary on your phone, or hack nasa using html.

Tldr, pointless

**Comment by OmarAwjy** [comment]
> If someone have physical access to an asset, whatever protections and measure you take become useless.
> 
> Let's not dive deep into how someone with physical access can uninstall then reinstall magisk app to reset your preferences, or flash any binary on your phone, or hack nasa using html.
> 
> Tldr, pointless

Already thought about this before you and have the plan, Magisk will be a system app (i'll systemize it) to prevent uninstallation, and, will chmod 444 it, to prevent updates or downgrades, but this security issue need to be solved first, and yes, whatever protections and measure i take (if i can realize the security concept) are useful.

**Comment by canyie** [comment]
Hello,
We have taken a look at this issue and determined that this is not a security vulnerability.
Here's our reasoning: While a physical attacker can bypass user interaction requirements, it is also possible for physical attackers to reboot the device into bootloader mode, install an image with malicious‌ programs then fully compromise and control the device. "User Authentication" is a best-effort protection measure, and does not claim to be safe against physical attacks. It is also almost impossible to "truly" protects an unlocked device from physical attacks, as most users have granted root access to other apps without setting an expiration time, and some of which can also be abused to execute malicious‌ commands or scripts with root privileges. 
This issue will be considered as a feature enhancement request, and is not enough to be considered as a security vulnerability. 
The security severity rating of this issue has been marked as NSI (Negligible Security Impact).

**Comment by OmarAwjy** [comment]
> Hello, We have taken a look at this issue and determined that this is not a security vulnerability. Here's our reasoning: While a physical attacker can bypass user interaction requirements, it is also possible for physical attackers to reboot the device into bootloader mode, install an image with malicious‌ programs then fully compromise and control the device. "User Authentication" is a best-effort protection measure, and does not claim to be safe against physical attacks. It is also almost impossible to "truly" protects an unlocked device from physical attacks, as most users have granted root access to other apps without setting an expiration time, and some of which can also be abused to execute malicious‌ commands or scripts with root privileges. This issue will be considered as a feature enhancement request, and is not enough to be considered as a security vulnerability. The security severity rating of this issue has been marked as NSI (Negligible Security Impact) to reflect the assessment.

Not true.
Since the /data partition is encrypted - 99% of android devices are encrypting the /data partition automtically once a password is set, even if the bootloader is unlocked, and even if an attacker flashed malwares in the bootloader, these malwares won't be able to work until the /data partition is decrypted, and this is not possible without user's password.

And about "as most users have granted root access to other apps without setting an expiration time", it's just their very own security decision, they can revoke the root access and re-grant it for 10 mins only, or not, it's simply their decision, but others are putting security first.

**Comment by vvb2060** [comment]
I will remove the authentication feature because it works 99% of the time, but the only time it doesn't work is when someone wants to do something malicious with root privileges. It's a false security feature that misleads the user.

**Comment by vvb2060** [comment]
You should use screen pinning to protect against possible malicious actors.
https://support.google.com/android/answer/9455138

**Comment by OmarAwjy** [comment]
I have initially fixed the issue on my side, Used App manager (root) to disable Magisk main activity, just left the superuser requests activity to be running, and secured App manager with the screen lock, here i fixed installing unauthorised modules and that "Automatic response" problem, and used MaxLock module to protect App manager and magisk from being Uninstalled/Data cleared,

I'll create a custom build of Magisk to fix all the security issues i faced.

**Comment by vvb2060** [comment]
No, you just need to protect your lock screen password.

**Comment by OmarAwjy** [comment]
> No, you just need to protect your lock screen password.

Already did and doing every week

**Comment by OmarAwjy** [comment]
What i worked on is if someone ordered me to unlock the phone and i had to, but without revealing my password ofcourse, so he won't be able to take root access, that's all

**Comment by vvb2060** [comment]
I think hiding apps from the home screen is a good idea.

**Comment by OmarAwjy** [comment]
> I think hiding apps from the home screen is a good idea.

If someone is technically not so bad he will easily open the "Apps" section from settings.

**Comment by akano12** [comment]
Bro why you acting like you're some major asset for the government of the United States? 

Get over it with these scenarios you're coming up with

**Comment by JMitander** [comment]
Sure, if someone has physical access, there are countless ways to break in. But letting ‘Automatic Response’ override the password prompt pretty much defeats the whole point of having ‘User Authentication’ in the first place. I’d love to see Magisk close that loophole so we can actually rely on the feature—knowing our phone isn’t wide open for anyone who picks it up.
