### ISSUE TITLE
Module can’t be installed

### ISSUE THREAD

**Issue by Killer74-hub** [topjohnwu/Magisk#8640]
Device: Samsung A 70, Pixel 6 pro (all devices lol)
Android version: 15,14,13
Magisk version name: 28101
Magisk version code: 28101

Nethunter can’t install. Code starts with:
Device is system as root
….
Installing Nethunter
! No background image found for your device
! Installation failed

Also , the network interfaces can’t be accessed. Internal and external. This all worked before.

please give me an solution/ tutorial for android 15/14.

**Comment by Panlelaila** [comment]
I have same problem . Device: Hisence Touch lite, Android 11.

**Comment by Panlelaila** [comment]
I found that moving the module files from the “download” path to a different folder allowed me to install it.

**Comment by Killer74-hub** [comment]
> I found that moving the module files from the “download” path to a different folder allowed me to install it.

This doesn't really fix the issue. Maybe it todes,but the "wifi issue" is still not resolved and needs an fix. Also, everything I said needs a fix because obviously it's a bug. But thank you for answering I will try it out

**Comment by LoYaGiC** [comment]
In my device module successfully installed but when i check module menu before reboot it's not shown like it's installed, after reboot it's still not shown so i just re-install and it's just same like before, i just want install fast charge module man😐

**Comment by yujincheng08** [comment]
no full log, and from #8623 i think this issue is also from module's side
