### ISSUE TITLE
update to v18 fails and causes a bootloop

### ISSUE THREAD

**Issue by LeonCame** [topjohnwu/Magisk#866]
In my case : Android 7.0 (oukitel C84G)
Magisk 17.1 work fine, installed by TWRP, everything was ok (tests pass, secure device ok etc).

I update to v18 trough the app as recommended. Update report in console say everything is ok but next :  bootloop, impossible to boot system or recovery !

Have to use fastboot (the last chance) to restore factory boot (oem unlock destroy all unsaved data). A lot of lost time (and the data after my last backup of September).

I suggest to the Magisk developers:
- put a warning before updating, reminding to make backups and mentioning the risk that the device can not start any more !!!
- further delay the aggressive update invitation via the application pop up
- to allow the deactivation of the systematic invitation to update (why urge people to use something that is not trusted)
- to work on a system of verification of the compatibility of the modules and to prevent, instead of breaking everything!

**Comment by Didgeridoohan** [comment]
Or, you take some responsibility for what you do to your device...

**Comment by LeonCame** [comment]
Exactly, it will teach me to trust you.
