### ISSUE TITLE
Partitions cannot be edited.

### ISSUE THREAD

**Issue by Killer74-hub** [topjohnwu/Magisk#8670]
Partitions cannot be edited. Also, nethunter cannot write files to the storage or cannot update. Also on the Pixel 6 pro, the WiFi chip cannot be enabled in monitor mode, which should work normally. Different Kernek won´t fix it.

Device: Any Android Above Android 15
Android version: 15
Magisk version name: 28.1
Magisk version code:28101

**Comment by yujincheng08** [comment]
No log. So I assume it's the same as #8623
