### ISSUE TITLE
System glitches persist after #668 on Nokia 7 Plus with Android 9.0

### ISSUE THREAD

**Issue by braveheartleo** [topjohnwu/Magisk#868]
While the fix indicated in #668 may have resolved some of the glitches described therein, the following  glitches have manifested upon installing `Magisk-v18.0` on `Nokia/Onyx_00WW/B2N_sprout:9/PPR1.180610.011/00WW_3_39D:user/release-keys`:

1) haptic feedback intensity is increased, returns to normal intensity when Magisk is uninstalled (no change since the fix from #668)
2) multiple user profile in Settings>System becomes empty (no current user, guest items), current user and guest items start showing properly upon Magisk uninstallation

System gestures are no longer affected having Magisk installed. There may be others that I have yet to encounter. I am providing the following snapshots for `/proc/mounts`:

* noroot: https://pastebin.com/8aYaknkq
* rooted: https://pastebin.com/dhm14DqY
* diff: https://pastebin.com/8aYaknkq

**Comment by topjohnwu** [comment]
@braveheartleo please provide boot logcats, the mounts has no info to debug (and I think your non-root one is still rooted). Have you tried to disable all modules?

**Comment by braveheartleo** [comment]
@topjohnwu It seems that the latest system update 00WW_351B for this phone have fixed all the remaining issues described in this report. This can now be closed. Thank you.
