### ISSUE TITLE
Unable to Root Nokia 6 with latest Android Pie internal build installed

### ISSUE THREAD

**Issue by HikariCalyx** [topjohnwu/Magisk#870]
I've tried both patch stock boot and flash Magisk canary release zip under TWRP, it does patch successfully, but Magisk Manager still indicates "Magisk not installed".

Strange enough, Magisk v17.x can work perfectly but Magisk v18.0 won't work.

[recovery.log](https://github.com/topjohnwu/Magisk/files/2678748/recovery.log)
[d1c_logcat.txt](https://github.com/topjohnwu/Magisk/files/2678752/d1c_logcat.txt)

[Stock Boot](https://drive.google.com/open?id=1e6SktAxCmivDOXY6hKL6Eak24OC6gBDc)

UPDATE: As a workaround, I created my own update channel that ensures the Magisk version will always stay at 17.1. Hope this will also fix other's issue.

**Comment by Didgeridoohan** [comment]
"Magisk not installed" have been known to happen if the Manager is installed to external or adoptable storage. Make sure it is installed to the internal storage if it isn't already.

**Comment by emmy223** [comment]
Hey i am facing an issue on my Nokia 6,i was in pie update and twrp is not booting on it . Also it's showing E: failed to find device for partition system. I tried @HikariCalyx steps to root android pie build it showing rooted and granting permission also but not installing any module from magisk, showing failed to extract how to solve this issue

**Comment by tantrev** [comment]
I can replicate this issue.  As previously described, installing the old Magisk was able to fix the problem. Nice work @HikariCalyx
