### ISSUE TITLE
Magiskhide didn't work in Marsmallow

### ISSUE THREAD

**Issue by AkagiShiroe** [topjohnwu/Magisk#871]
Fgo(JP) giving error code 61 for magisk. I use marsmallow because my phone nougat/Oreo are extremely slow. Can you help sir? Or marsmallow didn't supported anymore, BTW I'm using magisk18 with hidden magisk manager.

**Comment by topjohnwu** [comment]
Check my release notes, it is not possible to enforce `procfs` isolation on Android 6.0 and lower.

**Comment by AkagiShiroe** [comment]
thank you, so only for android 7+? ill try nougat rom later and hope for the best since my phone thermal management are broken.

**Comment by p3yot3** [comment]
@topjohnwu Can you confirm that Magisk v18 is not compatible with Marshmallow please? The release notes are not clear & I don't want to risk upgrading my MM phone to v18 if it is no longer compatible. Thanks.

**Comment by Didgeridoohan** [comment]
@p3yot3 Of course it's still compatible with Marshmallow. He's talking about MagiskHide fixing the procfs leak. That's not possible on Marshmallow...

**Comment by p3yot3** [comment]
@Didgeridoohan Thanks for the confirmation, flashed & working fine.

@topjohnwu Thanks for all your brilliant work!
