### ISSUE TITLE
Issue with GET_CONTENT on Chenyee (诚壹) devices Oreo 8.1.0

### ISSUE THREAD

**Issue by chenyee100** [topjohnwu/Magisk#872]
Hello,
I've faced an issue while i'm trying to patch boot.img using the latest Magisk Manager 6.1.0.apk

The issue is happening with `act=android.intent.action.GET_CONTENT typ=*/* `

In logcat Magisk APK is trying to open storage activity to select boot.img using the following command from logcat, but actually nothing happens on three different devices from Chenyee:
`act=android.intent.action.GET_CONTENT typ=*/* cmp=com.android.contacts/com.cyee.contacts.activities.ContactSelectionActivity`

While on other devices with Oreo 8.1.0 the command is different and boot.img could be selected using:
`act=android.intent.action.GET_CONTENT typ=*/* cmp=com.android.documentsui/.picker.PickActivity`

Is there a circumvention solution until there will be a fix for this issue ?

Attached are the logcat and a screenrecord for your reference:
[Logcat + Screenrecord](https://mega.nz/#F!Lkw13CJD!HDeBtfYeU2B6odx4F-7K5w)

**Comment by topjohnwu** [comment]
Unfortunately, this it nothing I can do with it. Until one day I incorporate my own file manager, the file selection relies on the platform behavior.
