### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cresmarM** [topjohnwu/Magisk#873]
Cant download ..
Modules.
But my connection..
Is extremely..
High.

**Comment by penn5** [comment]
please close this you clearly need to learn a) how to report bugs b) how to use internet and apps c) how to have some common courtesy.

**Comment by cresmarM** [comment]
Sorry but my brother is the one who posted this so dont mind this issue...
okay...

**Comment by cresmarM** [comment]
Sorry but my brother is the one who posted this so dont mind this issue...
okay...
