### ISSUE TITLE
magiskpolicy --load and --compile-split don't work on Pixel 2

### ISSUE THREAD

**Issue by AuroraWright** [topjohnwu/Magisk#874]
Not really sure why, but if I overlay a custom .cil file in /vendor and use --compile-split in magiskpolicy, or if I load a raw precompiled sepolicy file with --load, neither actually does anything (I tried dumping the sepolicy from sysfs and there's no change). Adding rules with --live works fine however.

**Comment by topjohnwu** [comment]
It works for me, you might have to figure it out yourself
