### ISSUE TITLE
[feature request] Implement custom .cil file loading

### ISSUE THREAD

**Issue by AuroraWright** [topjohnwu/Magisk#875]
There are certain sepolicy elements (in my case I had to add a "genfscon" statement) which can't be added with magiskpolicy --live. Given that some devices now support loading split sepolicies, it is possible to craft a custom .cil (from what I could see, a .cil needs to be derived from the base/platform sepolicy, either adding wholly new lines or extending existing ones, I made my own by compiling a custom platform_sepolicy and using this command: https://stackoverflow.com/a/9510294 to diff it from the untouched platform_sepolicy).
Example of how I added it: https://github.com/AuroraWright/Magisk/commit/16563b2e02d2b82c6db899ee5e81c1c5f0802e51 (works fine on a Pixel 2 XL on Pie).
It'd be nice to have such a feature officially.

**Comment by topjohnwu** [comment]
You can already use the tool `secilc` that in `/system/bin` to do what you want. `magiskpolicy`'s `--compile-split` command is simulating the behavior of `init` loading split policies on boot.
