### ISSUE TITLE
magisklogd always crashed

### ISSUE THREAD

**Issue by CrescendoFang** [topjohnwu/Magisk#877]
magisklogd always crash (thus no logs being generated).

logcat shows many like this:
`12-17 08:30:38.210  2828  2862 E octvm_klo: get package info failed for magisklogd`

and tombstones saying:
```
name: magisk >>> magisklogd <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30
```

plus in logcat:
```
12-17 08:30:38.278  2828  2862 E octvm_klo: get package info failed for magisklogd
12-17 08:30:38.278  2828  2862 I octvm_klo: summary:[signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30
12-17 08:30:38.278  2828  2862 I octvm_klo: ]
12-17 08:30:38.279  2828  2862 I octvm_klo: summary: [/system/lib/libc.so (fgets+15)]
12-17 08:30:38.279  2828  2862 I octvm_klo: summary: [/sbin/magisk]
12-17 08:30:38.279  2828  2862 I octvm_klo: start gathering logcat log...
```

and the rootfs (/) always mounted as **rw**
I'm unable to remount it as ro.

xposed is present but even tho I removed it (+ reflashing the firmware to make sure the system's clean before magisk), the issue remain the same regardless the presence of xposed.

**Comment by CrescendoFang** [comment]
full log since boot: https://pastebin.com/raw/wm8cnPVh

**Comment by penn5** [comment]
Please attach one of these tombstones.

**Comment by CrescendoFang** [comment]
I can easily get 10 tombstones in single boot session.... (numbered from 0 - 9)

do I have to upload it all ot any of it is sufficient?

**Comment by CrescendoFang** [comment]
found the cause of rootfs (/) mounted as rw: magisklogd crashing.

I got 1 boot session that surprise me: rootfs mounted as ro!

turned out that there's no tombstones about magisklogd crash as well.

**Comment by topjohnwu** [comment]
For some reason your device is messed up. post-fs-data is supposed to happen before late_start mode, which in your case it isn't. Try to do a full wipe, or change to another ROM

**Comment by CrescendoFang** [comment]
full wipe solved the issue... damn MIUI stressing me up...

thanks bro....

**Comment by hacker1024** [comment]
I have this too with Pixel Experience (Android 9.0)
