### ISSUE TITLE
after uninstalling magisk V.18, my android cannot load the system and always back to TWRP after reboot. does anyone can help me?

### ISSUE THREAD

**Issue by Shintanovitari1234** [topjohnwu/Magisk#879]

**Comment by Shintanovitari1234** [comment]
Sorry, I am using Xiaomi A1 Android 8.0.0

**Comment by Shintanovitari1234** [comment]
but if I reinstall magisk V.18 or lower version my android can start into the system

**Comment by CrescendoFang** [comment]
reflash full fastboot ROM

**Comment by Darkcast** [comment]
I had the same problem, It looks like the version 18 messes up the boot image. When you install Magisk it backs up a copy of the boot.img file if you use the Magisk Uninstaller from twrp it will revert back and you should be able to use your device.
