### ISSUE TITLE
Magisk v17.1 & v18: Random issues on MIUI 10(.1) (xiaomi eu) on Mi Pad 4

### ISSUE THREAD

**Issue by slashbeast** [topjohnwu/Magisk#881]
Hi,

I am getting weird issues with Magisk, tested 17.1 and 18, on MIUI 10 and 10.1 from Xiaomi EU on Xiaomi Mi Pad 4. What I noticed so far is that when I boot with Magisk my WIFI is always in disabled state and I have to manually enable it every boot, as well as random 'Power Not Responding' errors, system feel a bit laggy too. If I revert Magisk by over-installing the same MIUI .zip on the current magisk enabled system,  have flawlessly working system, but without root.

I've googled around and other people do have the same issues, although they do not specify that they use Magisk, they do confirm it happens on MiPad4 and XiaomiEU rom.

I am not sure how to debug it, any hints?

**Comment by kcschan** [comment]
Please at least provide technical data/telemetry described in XDA's thread, if you want to help the developer to diagnose the issue. Here is a better example:

https://github.com/topjohnwu/Magisk/issues/870

**Comment by slashbeast** [comment]
Sorry It appears that it's not a Magisk issue after all, the only difference is that with Magisk I get a 'Power has stopped' and without I just get, after much longer run time, a 'Power keeps crashing', as is MIUI is hiding the one-time crashes.
