### ISSUE TITLE
v18.0 su: cannot find manager

### ISSUE THREAD

**Issue by cleversboy** [topjohnwu/Magisk#882]
01-01 07:06:59.570   241   241 I Magisk  : * Creating /sbin overlay
01-01 07:06:59.580   243   243 I Magisk  : Magisk v18.0(18000) daemon started
01-01 07:06:59.590   243   244 I Magisk  : ** post-fs-data mode running
01-01 07:06:59.590   243   244 I Magisk  : * Initializing Magisk environment
01-01 07:06:59.590   243   244 I Magisk  : * Mounting mirrors
01-01 07:06:59.590   243   244 I Magisk  : mount: /sbin/.magisk/mirror/system
01-01 07:06:59.590   243   244 I Magisk  : link: /sbin/.magisk/mirror/vendor
01-01 07:06:59.590   243   244 I Magisk  : bind_mount: /sbin/.magisk/mirror/bin
01-01 07:06:59.590   243   244 I Magisk  : * Setting up internal busybox
01-01 07:06:59.620   250   250 I Magisk  : Magisk v18.0(18000) logger started
01-01 07:06:59.670   243   244 I Magisk  : Create /data/adb/magisk.img with size 64M
01-01 07:06:59.690   243   244 I Magisk  : * Mounting /data/adb/magisk.img
01-01 07:06:59.810   243   244 I Magisk  : * Running post-fs-data.d scripts
01-01 07:06:59.810   243   244 I Magisk  : * Running module post-fs-data scripts
01-01 07:06:59.810   243   244 I Magisk  : * Loading modules
01-01 07:06:59.940   243   263 I Magisk  : * Starting MagiskHide
01-01 07:06:59.940   243   263 I Magisk  : hide_utils: Hiding sensitive props
01-01 07:06:59.940   243   263 I Magisk  : hide_list add: [com.google.android.gms/.droidguard.DroidGuardService]
01-01 07:06:59.970   243   263 E Magisk  : proc_monitor: Your kernel doesn't support mount namespace :(
12-18 20:32:13.134   243   628 I Magisk  : ** late_start service mode running
12-18 20:32:13.134   243   628 I Magisk  : * Running service.d scripts
12-18 20:32:13.144   243   628 I Magisk  : * Running module service scripts
12-18 20:32:13.184   243   641 I Magisk  : * Starting MagiskHide
12-18 20:32:13.184   243   641 I Magisk  : hide_utils: Hiding sensitive props
12-18 20:32:13.184   243   641 I Magisk  : hide_list: [com.google.android.gms/.droidguard.DroidGuardService]
12-18 20:32:13.294   243   641 E Magisk  : proc_monitor: Your kernel doesn't support mount namespace :(
12-18 20:32:58.083   243  4263 E Magisk  : su: cannot find manager
12-18 20:35:02.614  7428  7428 W Magisk  : su: request rejected (10258->0)
12-18 20:39:27.014 19002 19002 W Magisk  : su: request rejected (10302->0)
12-18 20:48:12.914 29208 29208 W Magisk  : su: request rejected (10100->0)

**Comment by bmg002** [comment]
Is the problem here not listed right above the "su: cannot find manager" log entry?
proc_monitor: Your kernel doesn't support mount namespace :(

**Comment by cleversboy** [comment]
No. It means my phone use kernel that does not support magisk hide.

**Comment by cleversboy** [comment]
Yes. I tried that before posting the issue.
