### ISSUE TITLE
Magisk doesn't injects system.prop

### ISSUE THREAD

**Issue by dojwB** [topjohnwu/Magisk#890]
Hey, I'm maintaining few Magisk modules and one of them relays on system.prop but I noticed Magisk stopped injecting system.prop to build.prop.
I tried reinstalling but it did not help. 
Looks like GitHub doesn't support mobile Chrome, uploading logs to GDrive.
[Here's logs.](https://drive.google.com/file/d/1F9O3op0VaZS6dFiXA-alPk6i3U48XOq5)
[Logs from Magisk app](https://drive.google.com/file/d/1JHW5U1eRv-IRb9YxaXdKxNKDo-Pp9bh6/)

**Comment by Didgeridoohan** [comment]
Your logs are locked... You'll have to share them first.

And just to make sure: your aware that Magisk doesn't actually touch build.prop, right? The values from the system.prop file are simply loaded to memory, replacing those that where loaded from build.prop earlier in the boot process.

**Comment by dojwB** [comment]
I unlocked logs. For the problem, when I go into build.prop while system booted up, I don't see any changes.

**Comment by Didgeridoohan** [comment]
That's what I said... The build.prop file does not change and it never has. Check the loaded values with the getprop  command in a terminal emulator.

There's no issue, you can close this.

**Comment by dojwB** [comment]
Thank you, I'm now closing issue.
