### ISSUE TITLE
Magisk sometimes doesn't start on boot. Leagoo T8s

### ISSUE THREAD

**Issue by Adm0** [topjohnwu/Magisk#895]
Tested magisk v17.1, v17.2, v18 installed through TWRP.
When magisk doesn't start: [dmesg](https://github.com/topjohnwu/Magisk/files/2702269/dmesg.txt)
When magisk start: [dmesg](https://github.com/topjohnwu/Magisk/files/2702268/dmesg.txt), [magisk.log](https://github.com/topjohnwu/Magisk/files/2702275/magisk.log)

**Comment by topjohnwu** [comment]
Duplicate #844
