### ISSUE TITLE
[Feature Request] Mount Namespace & Network Namespace implementation per app basis 

### ISSUE THREAD

**Issue by mirfatif** [topjohnwu/Magisk#897]
Mount namespace implementation per app basis will give the user more granular control depending on the nature of app.
Network namespaces are an easy way to control internet connectivity on per pid basis (iptables --pid-owner is too cumbersome without --cmd-owner). An app running as root won't be able to access internet if user doesn't want so, even the other root processes are able to connect (dividing control of uid based firewalls further).
Network namespaces are enabled on Android kernels by default but the feature can be set optional depending on device capability.

**Comment by topjohnwu** [comment]
@mirfatif your point does not hold: if an app have root access, it can easily use the `setns` system call to switch to another namespace. There is no point in restricting the root environment. The mount namespace thing is simply changing the "default" behavior, not actually for security reasons.

**Comment by mirfatif** [comment]
I know that restricting internet access or providing other security mechanisms is out of the scope of Magisk, but this is the only place to control such things. Once the shell is running as root with full capabilities, user has no control what the app is doing in background.

> if an app have root access, it can easily use the `setns` system call to switch to another namespace.

This can also be restricted by dropping CAP_SYS_SDMIN or using SECCOMP, NO_NEW_PRIVS etc. And that would be optional for every app.
