### ISSUE TITLE
Magisk v18 issue: Hide not blocking '/sbin' access every now and then

### ISSUE THREAD

**Issue by paarnoutse** [topjohnwu/Magisk#900]
At my device (OnePlus 5, running OxygenOS 5.1.7 Android 8.1.0), in Magisk v18 the access to '/sbin' isn't blocked for hided apps every now and then.
Sometimes hiding works, sometimes it doesn't. Disabling and re-enabling Magisk Hide sometimes helps for a while (access to '/sbin' blocked again), but after some time same problem occurs. It happens randomly for _any_ hided app.
Because I've to use Microsoft Intune Company Portal for my Work account, due to this Magik Hide failures root is detected 10-20 times/day, so access to Microsoft apps (Outlook, Skype for Business, etc.) blocked. According to Intune XDA Forums, other users encounter same problems.

It happens randomly for all hided apps, and also appeared to happen in Canary 18.1. Therefore I've installed the Canary Debug version and used the hided "RootBeer Sample" app ('com.scottyab.rootbeer.sample') for creating illustrating logs for you (selected this root checker app because it shows in the Log the exact results of all his root checking actions).

In attachment:
- Magisk Log (from Canary Debug 18.1 version)
- A Log where hiding RootBeer worked
- A Log of just 5 minutes later, where hiding NOT worked anymore for the same app.
   It now has access to '/sbin/su' --> Root detected!

In first Log file (Magisk Hide works):
12-22 12:23:24.074 6665 21284 I RootBeer: LOOKING FOR BINARY: /sbin/su Absent :(

In second Log file (Magisk Hide fails):
12-22 12:28:46.697 22653 24371 I RootBeer: LOOKING FOR BINARY: /sbin/su PRESENT!!!

Thanks in advance for checking what's going wrong here with magisk hiding in Magisk v18.

[A) Log_2018-12-22_12-23-06 - Hiding RootBeer OK.txt](https://github.com/topjohnwu/Magisk/files/2705533/A.Log_2018-12-22_12-23-06.-.Hiding.RootBeer.OK.txt)

[B) Log_2018-12-22_12-28-31 - Hiding RootBeer FAILS.txt](https://github.com/topjohnwu/Magisk/files/2705531/B.Log_2018-12-22_12-28-31.-.Hiding.RootBeer.FAILS.txt)

[magisk_log_20181222_122938.log](https://github.com/topjohnwu/Magisk/files/2705532/magisk_log_20181222_122938.log)

**Comment by paarnoutse** [comment]
Just noticed that the 'magisk_log_yyyymmdd_hhmmss.log' file contains a mix of 'namespace' usage type messages, eg:
- "D Magisk  : su: use namespace of pid=[nnnnn]"
- "D Magisk  : su: use global namespace"
I didn't touch the 'Mount Namespace Mode' setting in Magisk Manager, so it's using the default.
Is it normal/expected that both _Inherit Namespace_ and _Global Namespace_ related messages are shown in the magisk_log? If not, it's possibly a lead for the issue?

**Comment by topjohnwu** [comment]
Merge into #907
