### ISSUE TITLE
[Feature request] Linux command line patch tool

### ISSUE THREAD

**Issue by haroon-ali** [topjohnwu/Magisk#901]
Hi,
Can you please provide a command line Linux tool - which should also run on Windows Subsystem for Linux -  that can patch boot images so one don't have to install magisk manager, upload the image file to phone, patch it, then copy the patch boot to PC for flashing.
I can just run `magisk_patch boot.img` which would generate `patch_boot.img` file.

Thanks for the fantastic software

**Comment by topjohnwu** [comment]
Check the documentations. You can easily patch boot images without going through the app, but directly through ADB shell.
