### ISSUE TITLE
MI8SE無法應用magisk16.6以後的版本

### ISSUE THREAD

**Issue by asdffczx** [topjohnwu/Magisk#908]
mi8se使用16.6以後的版本就會卡一屏或者卡動畫，怎麼辦

**Comment by chenyee100** [comment]
1- Write in English to let all the community participate.
2- Try to add a screenrecord or a screenshot you are getting about the screen or the card animation you are talking about.

**Comment by topjohnwu** [comment]
這種 report 我無法幫你修復
