### ISSUE TITLE
nubia redmagic Unable to install module

### ISSUE THREAD

**Issue by scarlet-glass** [topjohnwu/Magisk#909]
device：nubia  redmagic Mars
Android version：Android 9.0
cpu：sdm845
Nubia series mobile phones, android 8.1+ platform, are unable to install modules in the mobile phone, the following is the error message。
Ask god for help
--------------------------------------------------------------------------
- Mounting /data, /cache
- Magisk install detected
- Mounting /system, /vendor
- Found /data/adb/magisk_merge.img
e2fsck 1.43.3 (04-Sep-2016)
open: /dev/block/loop7 failed with 2: No such file or directory
! /data/adb/magisk_merge.img mount failed...
! Installation failed
--------------------------------------------------------------------------
/dev/block/

Android 7.1

bootdevice loop4 ram0 ram13 ram4 ram9 sda3 sda8 sdc1 sde1 sde14 sde19 sde23 sde28 sde32 sde37 sde41 sde9 sdf4
loop0 loop5 ram1 ram14 ram5 sda sda4 sda9 sdd sde10 sde15 sde2 sde24 sde29 sde33 sde38 sde5 sdf vold
loop1 loop6 ram10 ram15 ram6 sda1 sda5 sdb sdd1 sde11 sde16 sde20 sde25 sde3 sde34 sde39 sde6 sdf1
loop2 loop7 ram11 ram2 ram7 sda10 sda6 sdb1 sdd2 sde12 sde17 sde21 sde26 sde30 sde35 sde4 sde7 sdf2
loop3 platform ram12 ram3 ram8 sda2 sda7 sdc sde sde13 sde18 sde22 sde27 sde31 sde36 sde40 sde8 sdf3

Android 8.1
bootdevice ram12 ram4 sda sda5 sdb1 sdd1 sde11 sde17 sde22 sde28 sde33 sde39 sde44 sde5 sde7 sdf3
platform ram13 ram5 sda1 sda6 sdb2 sdd2 sde12 sde18 sde23 sde29 sde34 sde4 sde45 sde50 sde8 sdf4
ram0 ram14 ram6 sda10 sda7 sdc sdd3 sde13 sde19 sde24 sde3 sde35 sde40 sde46 sde51 sde9 sdf5
ram1 ram15 ram7 sda2 sda8 sdc1 sde sde14 sde2 sde25 sde30 sde36 sde41 sde47 sde52 sdf vold
ram10 ram2 ram8 sda3 sda9 sdc2 sde1 sde15 sde20 sde26 sde31 sde37 sde42 sde48 sde53 sdf1 zram0
ram11 ram3 ram9 sda4 sdb sdd sde10 sde16 sde21 sde27 sde32 sde38 sde43 sde49 sde6 sdf2

**Comment by scarlet-glass** [comment]
/dev/block/

Android 7.1

bootdevice loop4    ram0  ram13 ram4 ram9  sda3 sda8 sdc1 sde1  sde14 sde19 sde23 sde28 sde32 sde37 sde41 sde9 sdf4
loop0      loop5    ram1  ram14 ram5 sda   sda4 sda9 sdd  sde10 sde15 sde2  sde24 sde29 sde33 sde38 sde5  sdf  vold
loop1      loop6    ram10 ram15 ram6 sda1  sda5 sdb  sdd1 sde11 sde16 sde20 sde25 sde3  sde34 sde39 sde6  sdf1
loop2      loop7    ram11 ram2  ram7 sda10 sda6 sdb1 sdd2 sde12 sde17 sde21 sde26 sde30 sde35 sde4  sde7  sdf2
loop3      platform ram12 ram3  ram8 sda2  sda7 sdc  sde  sde13 sde18 sde22 sde27 sde31 sde36 sde40 sde8  sdf3


Android 8.1
bootdevice ram12 ram4 sda   sda5 sdb1 sdd1  sde11 sde17 sde22 sde28 sde33 sde39 sde44 sde5  sde7 sdf3
platform   ram13 ram5 sda1  sda6 sdb2 sdd2  sde12 sde18 sde23 sde29 sde34 sde4  sde45 sde50 sde8 sdf4
ram0       ram14 ram6 sda10 sda7 sdc  sdd3  sde13 sde19 sde24 sde3  sde35 sde40 sde46 sde51 sde9 sdf5
ram1       ram15 ram7 sda2  sda8 sdc1 sde   sde14 sde2  sde25 sde30 sde36 sde41 sde47 sde52 sdf  vold
ram10      ram2  ram8 sda3  sda9 sdc2 sde1  sde15 sde20 sde26 sde31 sde37 sde42 sde48 sde53 sdf1 zram0
ram11      ram3  ram9 sda4  sdb  sdd  sde10 sde16 sde21 sde27 sde32 sde38 sde43 sde49 sde6  sdf2

**Comment by topjohnwu** [comment]
It's an F2FS driver bug in your Nubia kernel, I cannot fix it for you.
