### ISSUE TITLE
Magisk 18.0 - Superuser Popup No Longer Appears To Grant Access

### ISSUE THREAD

**Issue by 0pLuS0** [topjohnwu/Magisk#910]
My Specs:

OnePlus 5T
OxygenOS 5.1.7 (Oreo 8.1.0
Magisk 18.0

Previous version of Magisk 17.1 never had this issue, and I've also run Magisk on several devices going back serveral years and versions, and I've never seen this till now.

I flashed magisk in TWRP, reboot, open up Magisk, then I go to an app that requires root access, wait for the popup to click "Grant", but it never appears.

Before I was able to get this to appear by going to Settings > Superuser Access and tapping Disabled, then tapping Apps and ADB, then trying this over and it would work, this time I tried it and nothing...

Then I also cleared the cache and data, and still nothing, now for whatever reason is going on, I can't get this to work.

Since I can't gain root I also can't get you a logcat... :(

I hope there's something that can be done to resolve this, it's quite frustrating trying to get this to work, and it's very erratic, sometimes working other times not...

**Comment by Didgeridoohan** [comment]
You don't need root to grab logs. Use [ADB](https://forum.xda-developers.com/showthread.php?t=1726238) or an [app](https://www.xda-developers.com/guide-sending-a-logcat-to-help-debug-your-favorite-app/) that's been given permission to read the logs.

**Comment by martyfender** [comment]
If I'm not mistaken, you can also access it in the TWRP file manger and copy it to your internal SD.

**Comment by topjohnwu** [comment]
You have to have Magisk Manager properly installed and whitelisted from any battery optimization.

**Comment by 0pLuS0** [comment]
Hmm I never had to mess with any battery optimization settings in the past...
