### ISSUE TITLE
Magisk Canany Build Debug, it could fix problems on 18.0 

### ISSUE THREAD

**Issue by Deviltrucker** [topjohnwu/Magisk#911]
This could solve root problems on 18.0 but it's from Magisk Canary Builds. 
Hope it helps
Log:
12-25 22:12:12.752   262   262 D Magisk  : resetprop: getprop [ro.crypto.state]: [unencrypted]
12-25 22:12:12.772   262   262 I Magisk  : * Creating /sbin overlay
12-25 22:12:12.802   265   265 I Magisk  : Magisk v18.1-b245931c(18002) daemon started
12-25 22:12:12.802   265   266 I Magisk  : ** post-fs-data mode running
12-25 22:12:12.802   265   266 I Magisk  : * Initializing Magisk environment
12-25 22:12:12.812   265   266 D Magisk  : resetprop: prop [ro.build.version.sdk] does not exist
12-25 22:12:12.812   265   266 I Magisk  : * Mounting mirrors
12-25 22:12:12.812   265   266 I Magisk  : mount: /sbin/.magisk/mirror/system <- /dev/block/mmcblk0p35
12-25 22:12:12.812   265   266 I Magisk  : link: /sbin/.magisk/mirror/vendor <- /sbin/.magisk/mirror/system/vendor
12-25 22:12:12.812   265   266 I Magisk  : bind_mount: /sbin/.magisk/mirror/bin <- /data/adb/magisk
12-25 22:12:12.812   265   266 I Magisk  : * Setting up internal busybox
12-25 22:12:12.892   272   272 I Magisk  : Magisk v18.1-b245931c(18002) logger started
12-25 22:12:12.952   265   266 I Magisk  : * Mounting /data/adb/magisk.img
12-25 22:12:13.082   265   266 I Magisk  : * Running post-fs-data.d scripts
12-25 22:12:13.082   265   266 I Magisk  : * Running module post-fs-data scripts
12-25 22:12:13.082   265   266 I Magisk  : iYTBP-Vanced-Magisk-Repo: exec [post-fs-data.sh]
12-25 22:12:13.112   265   266 I Magisk  : * Loading modules
12-25 22:12:13.112   265   266 I Magisk  : iYTBP-Vanced-Magisk-Repo: constructing magic mount structure
12-25 22:12:13.112   265   266 I Magisk  : bind_mount: /system/app/YouTube <- /sbin/.magisk/img/iYTBP-Vanced-Magisk-Repo/system/app/YouTube
12-25 22:12:13.192   265   284 I Magisk  : * Starting MagiskHide
12-25 22:12:13.192   265   284 I Magisk  : hide_utils: Hiding sensitive props
12-25 22:12:13.192   265   284 D Magisk  : resetprop: prop [ro.boot.vbmeta.device_state] does not exist
12-25 22:12:13.192   265   284 D Magisk  : resetprop: prop [ro.boot.verifiedbootstate] does not exist
12-25 22:12:13.192   265   284 D Magisk  : resetprop: prop [ro.boot.flash.locked] does not exist
12-25 22:12:13.192   265   284 D Magisk  : resetprop: prop [ro.boot.veritymode] does not exist
12-25 22:12:13.192   265   284 D Magisk  : resetprop: prop [ro.boot.warranty_bit] does not exist
12-25 22:12:13.192   265   284 D Magisk  : resetprop: prop [ro.warranty_bit] does not exist
12-25 22:12:13.192   265   284 D Magisk  : resetprop: getprop [ro.debuggable]: [0]
12-25 22:12:13.192   265   284 D Magisk  : resetprop: getprop [ro.secure]: [1]
12-25 22:12:13.192   265   284 D Magisk  : resetprop: prop [ro.build.type] does not exist
12-25 22:12:13.192   265   284 D Magisk  : resetprop: prop [ro.build.tags] does not exist
12-25 22:12:13.192   265   284 D Magisk  : resetprop: prop [ro.build.selinux] does not exist
12-25 22:12:13.192   265   284 D Magisk  : hide_list: initialize
12-25 22:12:13.192   265   284 I Magisk  : hide_list add: [com.google.android.gms.unstable]
12-25 22:12:13.272   265   284 I Magisk  : hide_list rm: [com.google.android.gms.unstable]
12-25 22:12:13.322   265   284 I Magisk  : hide_list add: [com.google.android.gms/.droidguard.DroidGuardService]
12-25 22:12:13.422   265   284 E Magisk  : proc_monitor: Your kernel doesn't support mount namespace :(
12-25 22:12:13.422   265   284 D Magisk  : proc_monitor: running cleanup
12-25 22:12:13.422   265   284 D Magisk  : proc_monitor: terminating
12-25 22:12:14.173   265   351 I Magisk  : ** late_start service mode running
12-25 22:12:14.173   265   351 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:12:14.173   265   351 I Magisk  : * Running service.d scripts
12-25 22:12:14.213   265   351 I Magisk  : * Running module service scripts
12-25 22:12:14.754   265   353 I Magisk  : * Starting MagiskHide
12-25 22:12:14.754   265   353 I Magisk  : hide_utils: Hiding sensitive props
12-25 22:12:14.754   265   353 D Magisk  : resetprop: prop [ro.boot.vbmeta.device_state] does not exist
12-25 22:12:14.754   265   353 D Magisk  : resetprop: prop [ro.boot.verifiedbootstate] does not exist
12-25 22:12:14.754   265   353 D Magisk  : resetprop: prop [ro.boot.flash.locked] does not exist
12-25 22:12:14.754   265   353 D Magisk  : resetprop: prop [ro.boot.veritymode] does not exist
12-25 22:12:14.754   265   353 D Magisk  : resetprop: prop [ro.boot.warranty_bit] does not exist
12-25 22:12:14.754   265   353 D Magisk  : resetprop: prop [ro.warranty_bit] does not exist
12-25 22:12:14.754   265   353 D Magisk  : resetprop: getprop [ro.debuggable]: [0]
12-25 22:12:14.754   265   353 D Magisk  : resetprop: getprop [ro.secure]: [1]
12-25 22:12:14.754   265   353 D Magisk  : resetprop: getprop [ro.build.type]: [user]
12-25 22:12:14.754   265   353 D Magisk  : resetprop: getprop [ro.build.tags]: [release-keys]
12-25 22:12:14.754   265   353 D Magisk  : resetprop: prop [ro.build.selinux] does not exist
12-25 22:12:14.754   265   353 D Magisk  : hide_list: initialize
12-25 22:12:14.754   265   353 I Magisk  : hide_list: [com.google.android.gms/.droidguard.DroidGuardService]
12-25 22:12:14.784   265   353 E Magisk  : proc_monitor: Your kernel doesn't support mount namespace :(
12-25 22:12:14.784   265   353 D Magisk  : proc_monitor: running cleanup
12-25 22:12:14.784   265   353 D Magisk  : proc_monitor: terminating
12-25 22:12:19.229   265   351 D Magisk  : apk_install: attempting to install APK
12-25 22:12:19.719   265   351 D Magisk  : apk_install: Error: Could not access the Package Manager.  Is the system running?
12-25 22:12:24.965   265   351 D Magisk  : apk_install: attempting to install APK
12-25 22:12:25.385   265   351 D Magisk  : apk_install: Error: Could not access the Package Manager.  Is the system running?
12-25 22:12:30.601   265   351 D Magisk  : apk_install: attempting to install APK
12-25 22:12:30.991   265   351 D Magisk  : apk_install: 	pkg: /data/magisk.apk
12-25 22:12:39.320   265   351 D Magisk  : apk_install: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
12-25 22:12:46.027   265  2376 D Magisk  : su: request from pid=[2360], client=[10]
12-25 22:12:46.027   265  2376 D Magisk  : su: request from uid=[10189] (#1)
12-25 22:12:46.027   265  2376 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:12:46.027   265  2376 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:12:46.027   265  2376 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
12-25 22:12:46.027   265  2376 D Magisk  : su: waiting child pid=[2378]
12-25 22:12:46.027  2378  2378 D Magisk  : su: fork handler
12-25 22:12:46.037  2378  2378 D Magisk  : su: use namespace of pid=[2360]
12-25 22:12:46.037  2378  2378 D Magisk  : su: setns failed, fallback to isolated
12-25 22:12:51.013   265  2376 D Magisk  : su: return code=[0]
12-25 22:12:53.265   265  2937 D Magisk  : su: request from pid=[2934], client=[12]
12-25 22:12:53.265   265  2937 D Magisk  : su: request from uid=[10190] (#1)
12-25 22:12:53.265   265  2937 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:12:53.265   265  2937 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:13:19.052   265  4616 D Magisk  : su: request from pid=[4613], client=[10]
12-25 22:13:19.052   265  4616 D Magisk  : su: request from uid=[10222] (#1)
12-25 22:13:19.052   265  4616 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:13:19.052   265  4616 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:13:19.052   265  4616 D Magisk  : su: waiting child pid=[4618]
12-25 22:13:19.052  4618  4618 D Magisk  : su: fork handler
12-25 22:13:19.052  4618  4618 D Magisk  : su: use global namespace
12-25 22:13:23.487   265  5036 D Magisk  : su: request from pid=[5032], client=[15]
12-25 22:13:23.487   265  5036 D Magisk  : su: request from uid=[10188] (#1)
12-25 22:13:23.487   265  5036 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:13:23.487   265  5036 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:13:23.487   265  5036 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
12-25 22:13:23.487   265  5036 D Magisk  : su: waiting child pid=[5039]
12-25 22:13:23.487  5039  5039 D Magisk  : su: fork handler
12-25 22:13:23.487  5039  5039 D Magisk  : su: use namespace of pid=[5032]
12-25 22:13:23.487  5039  5039 D Magisk  : su: setns failed, fallback to isolated
12-25 22:13:53.329   265  2937 D Magisk  : su: waiting child pid=[8641]
12-25 22:13:53.329  8641  8641 D Magisk  : su: fork handler
12-25 22:13:53.329  8641  8641 D Magisk  : su: use namespace of pid=[2934]
12-25 22:13:53.329  8641  8641 D Magisk  : su: setns failed, fallback to isolated
12-25 22:13:53.339  8641  8641 W Magisk  : su: request rejected (10190->0)
12-25 22:13:53.339   265  2937 D Magisk  : su: return code=[1]
12-25 22:14:51.601   265 10301 D Magisk  : su: request from pid=[10299], client=[12]
12-25 22:14:51.601   265 10301 D Magisk  : su: request from uid=[10212] (#1)
12-25 22:14:51.601   265 10301 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:14:51.601   265 10301 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:15:07.058   265 10938 D Magisk  : su: request from pid=[10935], client=[13]
12-25 22:15:07.058   265 10938 D Magisk  : su: request from uid=[10218] (#1)
12-25 22:15:07.058   265 10938 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:15:07.058   265 10938 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:15:07.058   265 10938 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
12-25 22:15:07.058   265 10938 D Magisk  : su: waiting child pid=[10940]
12-25 22:15:07.058 10940 10940 D Magisk  : su: fork handler
12-25 22:15:07.068 10940 10940 D Magisk  : su: use namespace of pid=[10935]
12-25 22:15:07.068 10940 10940 D Magisk  : su: setns failed, fallback to isolated
12-25 22:15:10.211 11018 11029 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xb50eaafa in tid 11029 (Binder_1)
12-25 22:15:11.142   265 10938 D Magisk  : su: return code=[0]
12-25 22:15:51.675   265 10301 D Magisk  : su: waiting child pid=[11410]
12-25 22:15:51.675 11410 11410 D Magisk  : su: fork handler
12-25 22:15:51.675 11410 11410 D Magisk  : su: use namespace of pid=[10299]
12-25 22:15:51.675 11410 11410 D Magisk  : su: setns failed, fallback to isolated
12-25 22:15:51.685 11410 11410 W Magisk  : su: request rejected (10212->0)
12-25 22:15:51.685   265 10301 D Magisk  : su: return code=[1]
12-25 22:15:53.637   265 11434 D Magisk  : su: request from pid=[11432], client=[16]
12-25 22:15:53.637   265 11434 D Magisk  : su: request from uid=[10212] (#1)
12-25 22:15:53.637   265 11434 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:15:53.637   265 11434 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:16:18.984   265  4616 D Magisk  : su: return code=[0]
12-25 22:16:53.691   265 11434 D Magisk  : su: waiting child pid=[12356]
12-25 22:16:53.691 12356 12356 D Magisk  : su: fork handler
12-25 22:16:53.691 12356 12356 E Magisk  : write failed with 32: Broken pipe
12-25 22:16:53.691   265 11434 D Magisk  : su: return code=[1]
12-25 22:18:34.819   265 13431 D Magisk  : su: request from pid=[13411], client=[14]
12-25 22:18:34.819   265 13431 D Magisk  : su: request from uid=[10222] (#1)
12-25 22:18:34.819   265 13431 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:18:34.819   265 13431 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:18:34.819   265 13431 D Magisk  : su: waiting child pid=[13434]
12-25 22:18:34.819 13434 13434 D Magisk  : su: fork handler
12-25 22:18:34.829 13434 13434 D Magisk  : su: use global namespace
12-25 22:23:32.657   265 15183 D Magisk  : su: request from pid=[15179], client=[10]
12-25 22:23:32.657   265 15183 D Magisk  : su: request from uid=[10212] (#1)
12-25 22:23:32.657   265 15183 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:23:32.657   265 15183 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:23:32.657   265 15183 D Magisk  : magiskdb: query mnt_ns=[0]
12-25 22:23:51.998   265 15317 D Magisk  : su: request from pid=[15312], client=[12]
12-25 22:23:51.998   265 15317 D Magisk  : su: request from uid=[10190] (#1)
12-25 22:23:51.998   265 15317 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:23:51.998   265 15317 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:23:51.998   265 15317 D Magisk  : magiskdb: query mnt_ns=[0]
12-25 22:24:28.447   265 13431 D Magisk  : su: return code=[0]
12-25 22:24:32.711   265 15183 D Magisk  : su: waiting child pid=[15593]
12-25 22:24:32.711 15593 15593 D Magisk  : su: fork handler
12-25 22:24:32.711 15593 15593 E Magisk  : write failed with 32: Broken pipe
12-25 22:24:32.711   265 15183 D Magisk  : su: return code=[1]
12-25 22:24:33.362   265 15601 D Magisk  : su: request from pid=[15597], client=[18]
12-25 22:24:33.362   265 15601 D Magisk  : su: request from uid=[10212] (#1)
12-25 22:24:33.362   265 15601 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:24:33.362   265 15601 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:24:33.362   265 15601 D Magisk  : magiskdb: query mnt_ns=[2]
12-25 22:24:46.526   265 15707 D Magisk  : su: request from pid=[15705], client=[10]
12-25 22:24:46.526   265 15707 D Magisk  : su: request from uid=[10222] (#1)
12-25 22:24:46.526   265 15707 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:24:46.526   265 15707 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:24:46.526   265 15707 D Magisk  : magiskdb: query mnt_ns=[2]
12-25 22:24:46.526   265 15707 D Magisk  : su: waiting child pid=[15709]
12-25 22:24:46.526 15709 15709 D Magisk  : su: fork handler
12-25 22:24:46.526 15709 15709 D Magisk  : su: use global namespace
12-25 22:24:52.052   265 15317 D Magisk  : su: waiting child pid=[15829]
12-25 22:24:52.062 15829 15829 D Magisk  : su: fork handler
12-25 22:24:52.062 15829 15829 E Magisk  : write failed with 32: Broken pipe
12-25 22:24:52.062   265 15317 D Magisk  : su: return code=[1]
12-25 22:25:09.130   265 15707 D Magisk  : su: return code=[0]
12-25 22:25:16.878   265 16001 D Magisk  : su: request from pid=[15997], client=[14]
12-25 22:25:16.878   265 16001 D Magisk  : su: request from uid=[10190] (#1)
12-25 22:25:16.878   265 16001 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:25:16.878   265 16001 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:25:16.878   265 16001 D Magisk  : magiskdb: query multiuser_mode=[1]
12-25 22:25:16.878   265 16001 D Magisk  : magiskdb: query mnt_ns=[2]
12-25 22:25:24.677   265 16092 D Magisk  : su: request from pid=[16089], client=[10]
12-25 22:25:24.677   265 16092 D Magisk  : su: request from uid=[10222] (#1)
12-25 22:25:24.677   265 16092 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:25:24.677   265 16092 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:25:24.677   265 16092 D Magisk  : magiskdb: query multiuser_mode=[1]
12-25 22:25:24.677   265 16092 D Magisk  : magiskdb: query mnt_ns=[2]
12-25 22:25:24.687   265 16092 D Magisk  : su: waiting child pid=[16094]
12-25 22:25:24.687 16094 16094 D Magisk  : su: fork handler
12-25 22:25:24.687 16094 16094 D Magisk  : su: use global namespace
12-25 22:25:33.426   265 15601 D Magisk  : su: waiting child pid=[16229]
12-25 22:25:33.426 16229 16229 D Magisk  : su: fork handler
12-25 22:25:33.426 16229 16229 E Magisk  : write failed with 32: Broken pipe
12-25 22:25:33.426   265 15601 D Magisk  : su: return code=[1]
12-25 22:25:42.516   265 16092 D Magisk  : su: return code=[0]
12-25 22:25:49.794   265 16403 D Magisk  : su: request from pid=[16399], client=[13]
12-25 22:25:49.794   265 16403 D Magisk  : su: request from uid=[10190] (#1)
12-25 22:25:49.794   265 16403 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:25:49.794   265 16403 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:25:49.794   265 16403 D Magisk  : magiskdb: query multiuser_mode=[1]
12-25 22:25:49.794   265 16403 D Magisk  : magiskdb: query mnt_ns=[1]
12-25 22:26:00.435   265 16659 D Magisk  : su: request from pid=[16656], client=[10]
12-25 22:26:00.435   265 16659 D Magisk  : su: request from uid=[10222] (#1)
12-25 22:26:00.435   265 16659 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:26:00.435   265 16659 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:26:00.435   265 16659 D Magisk  : magiskdb: query multiuser_mode=[1]
12-25 22:26:00.435   265 16659 D Magisk  : magiskdb: query mnt_ns=[1]
12-25 22:26:00.435   265 16659 D Magisk  : su: waiting child pid=[16661]
12-25 22:26:00.435 16661 16661 D Magisk  : su: fork handler
12-25 22:26:00.435 16661 16661 D Magisk  : su: use global namespace
12-25 22:26:16.943   265 16001 D Magisk  : su: waiting child pid=[16836]
12-25 22:26:16.943 16836 16836 D Magisk  : su: fork handler
12-25 22:26:16.943 16836 16836 E Magisk  : write failed with 32: Broken pipe
12-25 22:26:16.943   265 16001 D Magisk  : su: return code=[1]
12-25 22:26:23.740   265 16659 D Magisk  : su: return code=[0]
12-25 22:26:49.868   265 16403 D Magisk  : su: waiting child pid=[17413]
12-25 22:26:49.868 17413 17413 D Magisk  : su: fork handler
12-25 22:26:49.868 17413 17413 E Magisk  : write failed with 32: Broken pipe
12-25 22:26:49.878   265 16403 D Magisk  : su: return code=[1]
12-25 22:26:57.596   265 17498 D Magisk  : su: request from pid=[17495], client=[17]
12-25 22:26:57.596   265 17498 D Magisk  : su: request from uid=[10222] (#1)
12-25 22:26:57.596   265 17498 D Magisk  : magiskdb: query su_fingerprint=[0]
12-25 22:26:57.596   265 17498 D Magisk  : magiskdb: query magiskhide=[1]
12-25 22:26:57.596   265 17498 D Magisk  : magiskdb: query multiuser_mode=[1]
12-25 22:26:57.596   265 17498 D Magisk  : magiskdb: query mnt_ns=[1]
12-25 22:26:57.596   265 17498 D Magisk  : su: waiting child pid=[17500]
12-25 22:26:57.596 17500 17500 D Magisk  : su: fork handler
12-25 22:26:57.596 17500 17500 D Magisk  : su: use global namespace
12-25 22:27:09.288   265 17645 I Magisk  : * Starting MagiskHide
12-25 22:27:09.288   265 17645 I Magisk  : hide_utils: Hiding sensitive props
12-25 22:27:09.288   265 17645 D Magisk  : resetprop: prop [ro.boot.vbmeta.device_state] does not exist
12-25 22:27:09.288   265 17645 D Magisk  : resetprop: prop [ro.boot.verifiedbootstate] does not exist
12-25 22:27:09.288   265 17645 D Magisk  : resetprop: prop [ro.boot.flash.locked] does not exist
12-25 22:27:09.288   265 17645 D Magisk  : resetprop: prop [ro.boot.veritymode] does not exist
12-25 22:27:09.288   265 17645 D Magisk  : resetprop: prop [ro.boot.warranty_bit] does not exist
12-25 22:27:09.288   265 17645 D Magisk  : resetprop: prop [ro.warranty_bit] does not exist
12-25 22:27:09.288   265 17645 D Magisk  : resetprop: getprop [ro.debuggable]: [0]
12-25 22:27:09.288   265 17645 D Magisk  : resetprop: getprop [ro.secure]: [1]
12-25 22:27:09.288   265 17645 D Magisk  : resetprop: getprop [ro.build.type]: [user]
12-25 22:27:09.288   265 17645 D Magisk  : resetprop: getprop [ro.build.tags]: [release-keys]
12-25 22:27:09.288   265 17645 D Magisk  : resetprop: prop [ro.build.selinux] does not exist
12-25 22:27:09.288   265 17645 D Magisk  : hide_list: initialize
12-25 22:27:09.288   265 17645 I Magisk  : hide_list: [com.google.android.gms/.droidguard.DroidGuardService]
12-25 22:27:09.328   265 17645 E Magisk  : proc_monitor: Your kernel doesn't support mount namespace :(
12-25 22:27:09.328   265 17645 D Magisk  : proc_monitor: running cleanup
12-25 22:27:09.328   265 17645 D Magisk  : proc_monitor: terminating
12-25 22:27:15.495 17682 17682 F libc    : Fatal signal 13 (SIGPIPE), code 0 in tid 17682 (magisk.bin)
12-25 22:29:48.508   265 17498 D Magisk  : su: return code=[0]

**Comment by topjohnwu** [comment]
I don't see any issues here

**Comment by Deviltrucker** [comment]
@topjohnwu Working everything fine on the latest canary build, thanks.
