### ISSUE TITLE
[Feature Request] Runtime free space

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#912]
Hey @topjohnwu,

I was thinking about a setting in MM that will enable a user to define some free space for runtime. 

The approach I have in mind is something like $RequiredSpace + $User-defined-freespace = $Total-mounted-space.

Such a feature will help us avoid issues like the one in the attached Screenshot below where I'm unable to use hphosts with systemless AdAway as it's kinda big:

![screenshot_20181226-071217](https://user-images.githubusercontent.com/3320229/50434624-4252df00-08de-11e9-86f1-dda294758ee7.jpg)

**Comment by topjohnwu** [comment]
I'm planning to use a completely new approach for storing module files, please stay tuned :)
