### ISSUE TITLE
No root prompt

### ISSUE THREAD

**Issue by cleversboy** [topjohnwu/Magisk#915]
01-01 16:51:06.100   229   229 D Magisk  : resetprop: getprop [ro.crypto.state]: [unencrypted]
01-01 16:51:06.100   229   229 I Magisk  : * Creating /sbin overlay
01-01 16:51:06.120   231   231 I Magisk  : Magisk v18.1-b245931c(18002) daemon started
01-01 16:51:06.130   231   232 I Magisk  : ** post-fs-data mode running
01-01 16:51:06.130   231   232 I Magisk  : * Initializing Magisk environment
01-01 16:51:06.140   231   232 D Magisk  : resetprop: prop [ro.build.version.sdk] does not exist
01-01 16:51:06.140   231   232 I Magisk  : * Mounting mirrors
01-01 16:51:06.150   231   232 I Magisk  : mount: /sbin/.magisk/mirror/system <- /dev/block/platform/msm_sdcc.1/by-name/system
01-01 16:51:06.150   231   232 I Magisk  : link: /sbin/.magisk/mirror/vendor <- /sbin/.magisk/mirror/system/vendor
01-01 16:51:06.150   231   232 I Magisk  : bind_mount: /sbin/.magisk/mirror/bin <- /data/adb/magisk
01-01 16:51:06.150   231   232 I Magisk  : * Setting up internal busybox
01-01 16:51:06.190   238   238 I Magisk  : Magisk v18.1-b245931c(18002) logger started
01-01 16:51:06.230   231   232 I Magisk  : * Mounting /data/adb/magisk.img
01-01 16:51:06.280   231   232 I Magisk  : * Running post-fs-data.d scripts
01-01 16:51:06.280   231   232 I Magisk  : * Running module post-fs-data scripts
01-01 16:51:06.280   231   232 I Magisk  : * Loading modules
01-01 16:51:06.280   231   232 D Magisk  : magiskdb: query magiskhide=[1]
01-01 16:51:06.300   231   249 I Magisk  : * Starting MagiskHide
01-01 16:51:06.300   231   249 I Magisk  : hide_utils: Hiding sensitive props
01-01 16:51:06.300   231   249 D Magisk  : resetprop: prop [ro.boot.vbmeta.device_state] does not exist
01-01 16:51:06.300   231   249 D Magisk  : resetprop: prop [ro.boot.verifiedbootstate] does not exist
01-01 16:51:06.300   231   249 D Magisk  : resetprop: prop [ro.boot.flash.locked] does not exist
01-01 16:51:06.300   231   249 D Magisk  : resetprop: prop [ro.boot.veritymode] does not exist
01-01 16:51:06.300   231   249 D Magisk  : resetprop: prop [ro.boot.warranty_bit] does not exist
01-01 16:51:06.300   231   249 D Magisk  : resetprop: prop [ro.warranty_bit] does not exist
01-01 16:51:06.300   231   249 D Magisk  : resetprop: getprop [ro.debuggable]: [1]
01-01 16:51:06.300   231   249 D Magisk  : resetprop: setprop [ro.debuggable]: [0] by modifing prop data structure
01-01 16:51:06.300   231   249 D Magisk  : resetprop: getprop [ro.secure]: [0]
01-01 16:51:06.300   231   249 D Magisk  : resetprop: setprop [ro.secure]: [1] by modifing prop data structure
01-01 16:51:06.300   231   249 D Magisk  : resetprop: prop [ro.build.type] does not exist
01-01 16:51:06.300   231   249 D Magisk  : resetprop: prop [ro.build.tags] does not exist
01-01 16:51:06.300   231   249 D Magisk  : resetprop: prop [ro.build.selinux] does not exist
01-01 16:51:06.300   231   249 D Magisk  : hide_list: initialize
01-01 16:51:06.300   231   249 I Magisk  : hide_list: [com.google.android.gms/.droidguard.DroidGuardService]
01-01 16:51:06.320   231   249 E Magisk  : proc_monitor: Your kernel doesn't support mount namespace :(
01-01 16:51:06.320   231   249 D Magisk  : proc_monitor: running cleanup
01-01 16:51:06.320   231   249 D Magisk  : proc_monitor: terminating
01-01 16:51:34.559   231   575 I Magisk  : ** late_start service mode running
01-01 16:51:34.559   231   575 D Magisk  : magiskdb: query magiskhide=[1]
01-01 16:51:34.559   231   575 I Magisk  : * Running service.d scripts
01-01 16:51:34.559   231   575 I Magisk  : * Running module service scripts
12-26 06:28:19.934   231   578 I Magisk  : * Starting MagiskHide
12-26 06:28:19.934   231   578 I Magisk  : hide_utils: Hiding sensitive props
12-26 06:28:19.934   231   578 D Magisk  : resetprop: prop [ro.boot.vbmeta.device_state] does not exist
12-26 06:28:19.934   231   578 D Magisk  : resetprop: prop [ro.boot.verifiedbootstate] does not exist
12-26 06:28:19.934   231   578 D Magisk  : resetprop: prop [ro.boot.flash.locked] does not exist
12-26 06:28:19.934   231   578 D Magisk  : resetprop: prop [ro.boot.veritymode] does not exist
12-26 06:28:19.934   231   578 D Magisk  : resetprop: prop [ro.boot.warranty_bit] does not exist
12-26 06:28:19.934   231   578 D Magisk  : resetprop: prop [ro.warranty_bit] does not exist
12-26 06:28:19.934   231   578 D Magisk  : resetprop: getprop [ro.debuggable]: [0]
12-26 06:28:19.934   231   578 D Magisk  : resetprop: getprop [ro.secure]: [1]
12-26 06:28:19.934   231   578 D Magisk  : resetprop: getprop [ro.build.type]: [user]
12-26 06:28:19.934   231   578 D Magisk  : resetprop: getprop [ro.build.tags]: [release-keys]
12-26 06:28:19.934   231   578 D Magisk  : resetprop: prop [ro.build.selinux] does not exist
12-26 06:28:19.934   231   578 D Magisk  : hide_list: initialize
12-26 06:28:19.934   231   578 I Magisk  : hide_list: [com.google.android.gms/.droidguard.DroidGuardService]
12-26 06:28:20.244   231   578 E Magisk  : proc_monitor: Your kernel doesn't support mount namespace :(
12-26 06:28:20.284   231   578 D Magisk  : proc_monitor: running cleanup
12-26 06:28:20.284   231   578 D Magisk  : proc_monitor: terminating
12-26 06:29:28.013  3676  3676 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x798 in tid 3676 (rild)
12-26 06:29:28.329   231  4215 D Magisk  : su: request from pid=[4213], client=[12]
12-26 06:29:28.329   231  4215 D Magisk  : su: request from uid=[0] (#1)
12-26 06:29:28.329   231  4215 D Magisk  : magiskdb: query su_fingerprint=[0]
12-26 06:29:28.329   231  4215 D Magisk  : magiskdb: query magiskhide=[1]
12-26 06:29:28.329   231  4215 D Magisk  : su: waiting child pid=[4217]
12-26 06:29:28.329  4217  4217 D Magisk  : su: fork handler
12-26 06:29:28.329  4217  4217 D Magisk  : su: use namespace of pid=[4213]
12-26 06:29:28.329  4217  4217 D Magisk  : su: setns failed, fallback to isolated
12-26 06:29:28.369   231  4215 D Magisk  : su: return code=[0]
12-26 06:30:27.387  6207  6207 F Adjust  : PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to `sandbox` if you want to test your app!
12-26 06:30:29.917  2608  2608 F NotificationMgrNet: init() called multiple times!  sInstance = com.lge.networksettings.NotificationMgr@2c66a85c
12-26 06:31:11.587   231  7684 D Magisk  : su: request from pid=[7683], client=[11]
12-26 06:31:11.587   231  7684 D Magisk  : su: request from uid=[10258] (#1)
12-26 06:31:11.587   231  7684 D Magisk  : magiskdb: query su_fingerprint=[0]
12-26 06:31:11.587   231  7684 D Magisk  : magiskdb: query magiskhide=[1]
12-26 06:32:11.657   231  7684 D Magisk  : su: waiting child pid=[7786]
12-26 06:32:11.657  7786  7786 D Magisk  : su: fork handler
12-26 06:32:11.657  7786  7786 D Magisk  : su: use namespace of pid=[7683]
12-26 06:32:11.657  7786  7786 D Magisk  : su: setns failed, fallback to isolated
12-26 06:32:11.667  7786  7786 W Magisk  : su: request rejected (10258->0)
12-26 06:32:11.667   231  7684 D Magisk  : su: return code=[1]
12-26 06:33:04.287   231  9807 D Magisk  : su: request from pid=[9794], client=[12]
12-26 06:33:04.287   231  9807 D Magisk  : su: request from uid=[10509] (#1)
12-26 06:33:04.287   231  9807 D Magisk  : magiskdb: query su_fingerprint=[0]
12-26 06:33:04.287   231  9807 D Magisk  : magiskdb: query magiskhide=[1]
12-26 06:33:04.287   231  9807 D Magisk  : su: waiting child pid=[9809]
12-26 06:33:04.287  9809  9809 D Magisk  : su: fork handler
12-26 06:33:04.287  9809  9809 D Magisk  : su: use global namespace
12-26 06:33:18.617   231  9807 D Magisk  : su: return code=[0]
12-26 06:38:34.327   231 18908 D Magisk  : su: request from pid=[18907], client=[13]
12-26 06:38:34.327   231 18908 D Magisk  : su: request from uid=[0] (#1)
12-26 06:38:34.337   231 18908 D Magisk  : magiskdb: query su_fingerprint=[0]
12-26 06:38:34.337   231 18908 D Magisk  : magiskdb: query magiskhide=[1]
12-26 06:38:34.337   231 18908 D Magisk  : su: waiting child pid=[18910]
12-26 06:38:34.337 18910 18910 D Magisk  : su: fork handler
12-26 06:38:34.337 18910 18910 D Magisk  : su: use namespace of pid=[18907]
12-26 06:38:34.337 18910 18910 D Magisk  : su: setns failed, fallback to isolated
12-26 06:38:34.347   231 18908 D Magisk  : su: return code=[0]
12-26 06:42:42.577   231 19346 D Magisk  : su: request from pid=[19345], client=[11]
12-26 06:42:42.577   231 19346 D Magisk  : su: request from uid=[0] (#1)
12-26 06:42:42.577   231 19346 D Magisk  : magiskdb: query su_fingerprint=[0]
12-26 06:42:42.587   231 19346 D Magisk  : magiskdb: query magiskhide=[1]
12-26 06:42:42.587   231 19346 D Magisk  : su: waiting child pid=[19348]
12-26 06:42:42.587 19348 19348 D Magisk  : su: fork handler
12-26 06:42:42.587 19348 19348 D Magisk  : su: use namespace of pid=[19345]
12-26 06:42:42.587 19348 19348 D Magisk  : su: setns failed, fallback to isolated
12-26 06:42:42.597   231 19346 D Magisk  : su: return code=[0]
12-26 06:47:10.817   231 19382 D Magisk  : su: request from pid=[19381], client=[12]
12-26 06:47:10.817   231 19382 D Magisk  : su: request from uid=[0] (#1)
12-26 06:47:10.817   231 19382 D Magisk  : magiskdb: query su_fingerprint=[0]
12-26 06:47:10.817   231 19382 D Magisk  : magiskdb: query magiskhide=[1]
12-26 06:47:10.817   231 19382 D Magisk  : su: waiting child pid=[19384]
12-26 06:47:10.817 19384 19384 D Magisk  : su: fork handler
12-26 06:47:10.817 19384 19384 D Magisk  : su: use namespace of pid=[19381]
12-26 06:47:10.827 19384 19384 D Magisk  : su: setns failed, fallback to isolated
12-26 06:47:10.827   231 19382 D Magisk  : su: return code=[0]
12-26 06:50:24.907   231 19420 D Magisk  : su: request from pid=[19419], client=[11]
12-26 06:50:24.907   231 19420 D Magisk  : su: request from uid=[0] (#1)
12-26 06:50:24.907   231 19420 D Magisk  : magiskdb: query su_fingerprint=[0]
12-26 06:50:24.907   231 19420 D Magisk  : magiskdb: query magiskhide=[1]
12-26 06:50:24.907   231 19420 D Magisk  : su: waiting child pid=[19422]
12-26 06:50:24.917 19422 19422 D Magisk  : su: fork handler
12-26 06:50:24.917 19422 19422 D Magisk  : su: use namespace of pid=[19419]
12-26 06:50:24.917 19422 19422 D Magisk  : su: setns failed, fallback to isolated
12-26 06:50:24.927   231 19420 D Magisk  : su: return code=[0]
12-26 06:51:36.147   231 19432 D Magisk  : su: request from pid=[19431], client=[12]
12-26 06:51:36.147   231 19432 D Magisk  : su: request from uid=[0] (#1)
12-26 06:51:36.147   231 19432 D Magisk  : magiskdb: query su_fingerprint=[0]
12-26 06:51:36.147   231 19432 D

**Comment by topjohnwu** [comment]
You have to have Magisk Manager properly installed and whitelisted from any battery optimization.

**Comment by danupri** [comment]
How to do that?
