### ISSUE TITLE
magisk hide didn't work on Google Play Store

### ISSUE THREAD

**Issue by null4n** [topjohnwu/Magisk#916]
The safetynet was passed, but play store still show the app didn't compatible with this device. such as super Mario run: ``https://play.google.com/store/apps/details?id=com.nintendo.zara``

version 17.1 works fine. only after upgraded to 18.0

**Comment by sklaes** [comment]
I can install and play that game with magisk 18.0 even without using magisk hide for the game itself.

**Comment by null4n** [comment]
> I can install and play that game with magisk 18.0 even without using magisk hide for the game itself.

But on my phone, most Nintendo games didn't show if safetynet failed. if I open the url it will tell me not compatible with this device. 

Now I disabled `phone` permission for play store the it shows all this games. Magisk 17.1 didn't have this issue at all.

**Comment by null4n** [comment]
https://play.google.com/store/apps/details?id=com.nintendo.zaga
also try this

**Comment by topjohnwu** [comment]
Clear Play Store data and relaunch the app. The status will only be checked once and the result will be cached.
