### ISSUE TITLE
Magisk v18.0 crashes if blocked in firewall

### ISSUE THREAD

**Issue by leopard20** [topjohnwu/Magisk#917]
When I restrict the app's access to internet (MIUI ROM), Magisk manager crashes upon start.

Note that this only occurs when device is connected to the internet and Magisk attempts to get the latest updates.

Device: Xiaomi Mi 5s Plus
OS: Android 8.0.0 (MIUI 10, v8.12.20)

**Comment by Didgeridoohan** [comment]
I think that was fixed after the release of v18.0 stable. Are you testing on the Canary debug channel (as is [https://github.com/topjohnwu/Magisk/blob/master/README.MD#bug-reports](required when reporting bugs))?

**Comment by leopard20** [comment]
My apologies. I was using the stable channel.
If this is fixed already, feel free to close this.

**Comment by Didgeridoohan** [comment]
Just to make sure, you can install the Canary build and you'll find out if it's fixed or not. And if it's fixed you can actually close it yourself (as the creator of the issue).

**Comment by leopard20** [comment]
The issue still persists on the latest version. Plz reopen.

**Comment by Didgeridoohan** [comment]
If you are experiencing issues still, open a new issue with a proper bug report (with logs, etc). Take a look in the [Magisk repo readme](https://github.com/topjohnwu/Magisk/blob/master/README.MD) for details on what a proper bug report should contain.
