### ISSUE TITLE
! Unable to repack boot image! Segmentation fault 

### ISSUE THREAD

**Issue by robintan5566** [topjohnwu/Magisk#919]
Hi, I'm having issue installing the magisk v18. I'm using M9 plus TV box. Below is the installation log. Could someone help me? Many thanks.

- Detecting target image
- Target image: /dev/block/boot
- Device platform: armeabi-v7a
- Existing zip found
- Extracting files
- Unpacking boot image
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/dev/block/boot]
HEADER_VER [0]
KERNEL_SZ [7283099]
RAMDISK_SZ [2708738]
SECOND_SZ [32955]
EXTRA_SZ [0]
RECOV_DTBO_SZ [0]
PAGESIZE [2048]
NAME []
CMDLINE []
CHECKSUM [c13a84edd37cc57f9c2f036cfd3ac3346630cfac]
KERNEL_FMT [lzop]
RAMDISK_FMT [gzip]
- Checking ramdisk status
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Backing up stock boot image
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
Compressing to [stock_boot_4feb81dde4715972df6473dc0542873cde5de69 0.img.gz]
- Patching ramdisk
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Patch with flag KEEPVERITY=[false] KEEPFORCEENCRYPT=[false]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
- Repacking boot image
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/dev/block/boot]
HEADER_VER [0]
KERNEL_SZ [7283099]
RAMDISK_SZ [2708738]
SECOND_SZ [32955]
EXTRA_SZ [0]
RECOV_DTBO_SZ [0]
PAGESIZE [2048]
NAME []
CMDLINE []
CHECKSUM [c13a84edd37cc57f9c2f036cfd3ac3346630cfac]
KERNEL_FMT [lzop]
RAMDISK_FMT [gzip]
Repack to boot image: [new-boot.img]
! Unable to repack boot image!
Segmentation fault
! Installation failed

**Comment by robintan5566** [comment]
[magisk_install_log_20181228_221429.log](https://github.com/topjohnwu/Magisk/files/2715015/magisk_install_log_20181228_221429.log)

**Comment by robintan5566** [comment]
I have uninstalled using the magisk-uninstaller.zip and re-installed using app-full-debug.apk

**Comment by topjohnwu** [comment]
Unfortunately, LZOP compression is not supported
