### ISSUE TITLE
Magisk v18 can not mount system&vendor to /sbin/.magisk/mirror/system&vendor

### ISSUE THREAD

**Issue by znlsl** [topjohnwu/Magisk#921]
Hi, I'm having issue installing the magisk v18. But I found adb logcat always shows: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x30 in tid 1262 (magisk.bin). So I get full main log:

01-03 05:22:06.901  1243  1243 I Magisk  : * Creating /sbin overlay
01-03 05:22:06.926  1245  1245 I Magisk  : Magisk v18.0(18000) daemon started
01-03 05:22:06.936  1245  1246 I Magisk  : ** post-fs-data mode running
01-03 05:22:06.936  1245  1246 I Magisk  : * Initializing Magisk environment
01-03 05:22:06.946  1245  1246 I Magisk  : * Mounting mirrors
01-03 05:22:06.949  1245  1246 E Magisk  : mount /dev/block/platform/soc/c0c4000.sdhci/by-name/system->/sbin/.magisk/mirror/system failed with 16: Device or resource busy
01-03 05:22:06.949  1245  1246 I Magisk  : mount: /sbin/.magisk/mirror/system
01-03 05:22:06.949  1245  1246 E Magisk  : mount /dev/block/platform/soc/c0c4000.sdhci/by-name/vendor->/sbin/.magisk/mirror/vendor failed with 16: Device or resource busy
01-03 05:22:06.949  1245  1246 I Magisk  : mount: /sbin/.magisk/mirror/vendor
01-03 05:22:06.950  1245  1246 I Magisk  : bind_mount: /sbin/.magisk/mirror/bin
01-03 05:22:06.951  1245  1246 I Magisk  : * Setting up internal busybox
01-03 05:22:06.971  1248  1248 E Magisk  : execve /sbin/.magisk/mirror/system/bin/logcat failed with 2: No such file or directory
01-03 05:22:06.973  1248  1248 I Magisk  : * Mounting /data/adb/magisk.img
01-03 05:22:07.000   625   627 D vold    : Disk at 7:64 changed
01-03 05:22:07.049  1248  1248 I Magisk  : * Running post-fs-data.d scripts
01-03 05:22:07.049  1248  1248 I Magisk  : * Running module post-fs-data scripts
01-03 05:22:07.049  1248  1248 I Magisk  : * Loading modules
01-03 05:22:07.050  1254  1254 E Magisk  : execve /sbin/.magisk/mirror/system/bin/logcat failed with 2: No such file or directory
01-03 05:22:07.052  1256  1256 I Magisk  : Magisk v18.0(18000) logger started
01-03 05:22:07.054  1257  1257 E Magisk  : execve /sbin/.magisk/mirror/system/bin/logcat failed with 2: No such file or directory
01-03 05:22:07.055  1258  1258 E Magisk  : execve /sbin/.magisk/mirror/system/bin/logcat failed with 2: No such file or directory
01-03 05:22:07.055  1259  1259 E Magisk  : execve /sbin/.magisk/mirror/system/bin/logcat failed with 2: No such file or directory
01-03 05:22:07.057  1262  1262 E Magisk  : execve /sbin/.magisk/mirror/system/bin/logcat failed with 2: No such file or directory
--------- beginning of crash
01-03 05:22:07.057  1262  1262 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x30 in tid 1262 (magisk.bin), pid 1262 (magisk.bin)
01-03 05:22:07.083  1266  1266 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-03 05:22:07.083  1266  1266 E libc    : failed to connect to tombstoned: No such file or directory
01-03 05:22:07.083  1266  1266 I crash_dump32: performing dump of process 1262 (target tid = 1262)
01-03 05:22:07.083  1266  1266 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-03 05:22:07.083  1266  1266 F DEBUG   : Build fingerprint: 'samsung/Phoenix/Phoenix:8.1.0/OPM1.171019.026/G6200ZCU0ARL2:user/release-keys'
01-03 05:22:07.083  1266  1266 F DEBUG   : Revision: '0'
01-03 05:22:07.083  1266  1266 F DEBUG   : ABI: 'arm'
01-03 05:22:07.083  1266  1266 F DEBUG   : pid: 1262, tid: 1262, name: magisk.bin  >>> magisklogd <<<
01-03 05:22:07.083  1266  1266 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30
01-03 05:22:07.083  1266  1266 F DEBUG   : Cause: null pointer dereference
01-03 05:22:07.083  1266  1266 F DEBUG   :     r0 ed70192c  r1 00001000  r2 00000000  r3 00000000
01-03 05:22:07.084  1266  1266 F DEBUG   :     r4 ed702970  r5 0f6cd000  r6 00001000  r7 ed702950
01-03 05:22:07.084  1266  1266 F DEBUG   :     r8 ed70192c  r9 00000000  sl 0f6cd000  fp 0f6cd000
01-03 05:22:07.084  1266  1266 F DEBUG   :     ip 0f6cce6c  sp ed701908  lr 0f6b9241  pc ee423c1e  cpsr 20000030
01-03 05:22:07.084  1248  1265 I Magisk  : * Starting MagiskHide
01-03 05:22:07.084  1248  1265 I Magisk  : hide_utils: Hiding sensitive props
01-03 05:22:07.084  1248  1265 I Magisk  : hide_list: [com.google.android.gms/.droidguard.DroidGuardService]
01-03 05:22:07.086  1266  1266 F DEBUG   : 
01-03 05:22:07.086  1266  1266 F DEBUG   : backtrace:
01-03 05:22:07.086  1266  1266 F DEBUG   :     #00 pc 00043c1e  /system/lib/libc.so (fgets+15)
01-03 05:22:07.086  1266  1266 F DEBUG   :     #01 pc 0000423d  /sbin/magisk.bin
01-03 05:22:07.086  1266  1266 F DEBUG   :     #02 pc 000479ef  /system/lib/libc.so (__pthread_start(void*)+22)
01-03 05:22:07.086  1266  1266 F DEBUG   :     #03 pc 0001b2ed  /system/lib/libc.so (__start_thread+32)
01-03 05:22:07.093  1266  1266 E crash_dump32: unable to connect to activity manager: Connection refused
01-03 05:22:07.095  1259  1261 I Magisk  : magisklogd: logcat output EOF
01-03 05:22:07.096  1267  1267 E Magisk  : execve /sbin/.magisk/mirror/system/bin/logcat failed with 2: No such file or directory
01-03 05:22:07.097  1268  1268 E Magisk  : execve /sbin/.magisk/mirror/system/bin/logcat failed with 2: No such file or directory
01-03 05:22:07.097  1268  1268 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x30 in tid 1268 (magisk.bin), pid 1268 (magisk.bin)
01-03 05:22:07.115  1271  1271 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-03 05:22:07.116  1271  1271 E libc    : failed to connect to tombstoned: No such file or directory

**Comment by Didgeridoohan** [comment]
Please note that any bug reports posted need to be from the [Canary debug build](https://forum.xda-developers.com/apps/magisk/dev-magisk-canary-channel-bleeding-edge-t3839337). The Magisk log from the stable release is just to sparse.

Source: [The Magisk repo readme.md](https://github.com/topjohnwu/Magisk#bug-reports)

**Comment by znlsl** [comment]
> Please note that any bug reports posted need to be from the [Canary debug build](https://forum.xda-developers.com/apps/magisk/dev-magisk-canary-channel-bleeding-edge-t3839337). The Magisk log from the stable release is just to sparse (and whatever you're reporting about might be fixed upstream).
> 
> Source: [The Magisk repo readme.md](https://github.com/topjohnwu/Magisk#bug-reports)

Got it. I will retest with Canary debug build. THX!

**Comment by znlsl** [comment]
I installed latest magisk-debug version and magisk manager apk, still has problom, it seems that something wrong with  mounting  partition to /sbin/.magisk/mirror/xxxx:

01-03 19:57:09.721   645   646 E Magisk  : mount /dev/block/platform/soc/c0c4000.sdhci/by-name/system->/sbin/.magisk/mirror/system failed with 16: Device or resource busy
01-03 19:57:09.721   645   646 I Magisk  : mount: /sbin/.magisk/mirror/system <- /dev/block/platform/soc/c0c4000.sdhci/by-name/system
01-03 19:57:09.721   645   646 E Magisk  : mount /dev/block/platform/soc/c0c4000.sdhci/by-name/vendor->/sbin/.magisk/mirror/vendor failed with 16: Device or resource busy
01-03 19:57:09.721   645   646 I Magisk  : mount: /sbin/.magisk/mirror/vendor <- /dev/block/platform/soc/c0c4000.sdhci/by-name/vendor

attch dmesg and logcat logs.
[dmesg.log](https://github.com/topjohnwu/Magisk/files/2715985/dmesg.log)
[logcat.log](https://github.com/topjohnwu/Magisk/files/2715986/logcat.log)

**Comment by stcdalyc** [comment]
meet same problem. i think the main error is "execve /sbin/.magisk/mirror/system/bin/logcat failed with 2: No such file or directory". this error will cause my phone stuck and ANR(because it will create a lot process in background which will consume cpu resources), but i can fix it by copying the /system/bin/logcat to /sbin/.magisk/mirror/system/bin/logcat mannully.

**Comment by topjohnwu** [comment]
Your kernel or ROM is weird... Linux kernel allows multiple mounts with the same block. Since all mounts are read-only, it should not show "block is busy" error. Unfortunately, this is not something I can fix
