### ISSUE TITLE
magisk18.0 不能成功隱藏

### ISSUE THREAD

**Issue by 34292885** [topjohnwu/Magisk#923]
我將magisk本體隱藏為manager以及用magisk hide功能，親測發現以下app不起作用，仍然無法正常使用，直到使用官方uninstall根除整個magisk才能再使用。

1.皇室戰爭（Clash Royal）
2.對峙2（standoff 2）
3.神魔之塔（tower of saviours）
4.Pokémon Go

Sorry, my English is very poor
Android 7.1.2
OPPO Find 7a
twrp3.2.3-0

I hide the magisk ontology as a manager and use the magic hide function. I found out that the following app doesn't work and still can't be used normally until I use the official uninstall to eradicate the entire magisk.

1. 皇室戰爭 (Clash Royal)
2. 對峙 2 (standoff 2)
3. 神魔之塔（Tower of saviours）
4. Pokémon Go

Translated by Google
Android 7.1.2
OPPO Find 7a
Twrp3.2.3-0

**Comment by Deviltrucker** [comment]
You have Google Translate
