### ISSUE TITLE
Blank screen after installing modules

### ISSUE THREAD

**Issue by rexx0520** [topjohnwu/Magisk#925]
After installed modules from magisk manager and reboot, the screen blanked after 2nd boot animation.
It seems that the only way to fix is to wipe /data to enter the system?

Phone: HTC U11+

**Comment by Didgeridoohan** [comment]
That's likely not a Magisk issue... Take it up with the module creators instead.

And:
https://www.didgeridoohan.com/magisk/Magisk#hn_Module_causing_issues_Magisk_functionality_bootloop_loss_of_root_etc
