### ISSUE TITLE
Magisk Not Fully Installed check with Root checker

### ISSUE THREAD

**Issue by danupri** [topjohnwu/Magisk#927]
Detail:
Redmi note 2 Android 5.0.2
Rom Miui Global 8
TWRP 3.2.3
MAGISK V18 
MAGISK MANAGER V6.01 

I have try:
- Flash zip via twrp
- Install directly from Magisk Manager 
- Patch boot img
- Whitelist magisk manager from batt optimation
Still no work

Instal titanium backup says no root acces
Banking apps says rooted devices
Root checker result as attached pict
Any other idea

![screenshot_2018-12-30-12-58-19-101_com app wifi rootcheck master](https://user-images.githubusercontent.com/46244790/50544841-064cb080-0c35-11e9-9793-ee878454407b.png)
![screenshot_2018-12-29-22-51-41-058_com miui powerkeeper](https://user-images.githubusercontent.com/46244790/50544843-18c6ea00-0c35-11e9-91ed-90e0e92c4a4d.png) 

> 12-30 12:55:40.636   252   252 I Magisk  : * Creating /sbin overlay
12-30 12:55:40.667   255   255 I Magisk  : Magisk v18.0(18000) daemon started
12-30 12:55:40.672   255   256 I Magisk  : ** post-fs-data mode running
12-30 12:55:40.672   255   256 I Magisk  : * Initializing Magisk environment
12-30 12:55:40.674   255   256 I Magisk  : * Mounting mirrors
12-30 12:55:40.676   255   256 I Magisk  : mount: /sbin/.magisk/mirror/system
12-30 12:55:40.676   255   256 I Magisk  : link: /sbin/.magisk/mirror/vendor
12-30 12:55:40.676   255   256 I Magisk  : bind_mount: /sbin/.magisk/mirror/bin
12-30 12:55:40.676   255   256 I Magisk  : * Setting up internal busybox
12-30 12:55:40.709   260   260 I Magisk  : Magisk v18.0(18000) logger started
12-30 12:55:40.741   255   256 I Magisk  : * Mounting /data/adb/magisk.img
12-30 12:55:40.782   255   256 I Magisk  : * Running post-fs-data.d scripts
12-30 12:55:40.782   255   256 I Magisk  : * Running module post-fs-data scripts
12-30 12:55:40.782   255   256 I Magisk  : * Loading modules
12-30 12:55:40.795   255   271 I Magisk  : * Starting MagiskHide
12-30 12:55:40.795   255   271 I Magisk  : hide_utils: Hiding sensitive props
12-30 12:55:40.796   255   271 I Magisk  : hide_list: [com.google.android.gms/.droidguard.DroidGuardService]
12-30 13:55:43.427   255   696 I Magisk  : ** late_start service mode running
12-30 13:55:43.428   255   696 I Magisk  : * Running service.d scripts
12-30 13:55:43.428   255   696 I Magisk  : * Running module service scripts
12-30 12:57:05.463   255   271 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[4761] ns=[4026534542]
12-30 12:58:30.078  6835  6835 W Magisk  : su: request rejected (10139->0)

**Comment by Ante0** [comment]
Check in Magisk Manager - Menu - Superuser if Titanium backup is rejected. I've had this issue sometimes where it won't show the Allow/Deny dialog but it's automatically rejected. Enabling access for the app in that section of Magisk Manager solves it.
As for your banking apps, have you tried enabling hide for them?

The log looks fine to me. Other than the "rejected" at the bottom. 

And if the root checker app doesn't show the dialog either it would automatically reject it and thus not show root as being installed.

**Comment by danupri** [comment]
No app shown in the list of superuser,,
Yes, I have try use hide for banking apps,, 

Btw thanks for your reply

**Comment by NaufalAriqS21** [comment]
Same here, but I use MIUI 9. SuperSU not prompting. When I change setting to grant, it has the same result.
Using Magisk v18.0, other modules is working. (In this log, I use ADB & Fastboot for Android NDK)
Log:

> 01-04 20:22:21.744   254   254 I Magisk  : * Creating /sbin overlay
01-04 20:22:21.781   257   257 I Magisk  : Magisk v18.0(18000) daemon started
01-04 20:22:21.783   257   258 I Magisk  : ** post-fs-data mode running
01-04 20:22:21.783   257   258 I Magisk  : * Initializing Magisk environment
01-04 20:22:21.785   257   258 I Magisk  : * Mounting mirrors
01-04 20:22:21.786   257   258 I Magisk  : mount: /sbin/.magisk/mirror/system
01-04 20:22:21.786   257   258 I Magisk  : link: /sbin/.magisk/mirror/vendor
01-04 20:22:21.787   257   258 I Magisk  : bind_mount: /sbin/.magisk/mirror/bin
01-04 20:22:21.788   257   258 I Magisk  : * Setting up internal busybox
01-04 20:22:21.823   262   262 I Magisk  : Magisk v18.0(18000) logger started
01-04 20:22:21.921   257   258 I Magisk  : Upgrade/New module: adb-ndk
01-04 20:22:21.921   257   258 I Magisk  : Create /data/adb/tmp.img with size 64M
01-04 20:22:22.133   257   258 I Magisk  : * Merging /data/adb/magisk_merge.img + /data/adb/magisk.img -> /data/adb/tmp.img
01-04 20:22:22.299   257   258 I Magisk  : * Move /data/adb/tmp.img -> /data/adb/magisk.img
01-04 20:22:22.300   257   258 I Magisk  : * Mounting /data/adb/magisk.img
01-04 20:22:22.390   257   258 I Magisk  : * Running post-fs-data.d scripts
01-04 20:22:22.390   257   258 I Magisk  : * Running module post-fs-data scripts
01-04 20:22:22.390   257   258 I Magisk  : * Loading modules
01-04 20:22:22.390   257   258 I Magisk  : hosts: constructing magic mount structure
01-04 20:22:22.391   257   258 I Magisk  : adb-ndk: constructing magic mount structure
01-04 20:22:22.391   257   258 I Magisk  : bind_mount: /system/etc/hosts
01-04 20:22:22.393   257   258 I Magisk  : mnt_tmpfs : /system/bin
01-04 20:22:22.393   257   258 I Magisk  : bind_mount: /system/bin/adb
01-04 20:22:22.393   257   258 I Magisk  : bind_mount: /system/bin/adb.bin
01-04 20:22:22.393   257   258 I Magisk  : bind_mount: /system/bin/fastboot
01-04 20:22:22.394   257   258 I Magisk  : bind_mount: /system/bin/install-recovery.sh
01-04 20:22:22.394   257   258 I Magisk  : bind_mount: /system/bin/6620_launcher
01-04 20:22:22.394   257   258 I Magisk  : bind_mount: /system/bin/6620_wmt_concurrency
01-04 20:22:22.394   257   258 I Magisk  : bind_mount: /system/bin/6620_wmt_lpbk
01-04 20:22:22.394   257   258 I Magisk  : bind_mount: /system/bin/AcdApiDaemon
01-04 20:22:22.394   257   258 I Magisk  : bind_mount: /system/bin/MtkCodecService
01-04 20:22:22.394   257   258 I Magisk  : bind_mount: /system/bin/aal
01-04 20:22:22.394   257   258 I Magisk  : bind_mount: /system/bin/aee
01-04 20:22:22.394   257   258 I Magisk  : bind_mount: /system/bin/aee_archive
01-04 20:22:22.394   257   258 I Magisk  : bind_mount: /system/bin/aee_core_forwarder
01-04 20:22:22.394   257   258 I Magisk  : bind_mount: /system/bin/aee_dumpstate
01-04 20:22:22.394   257   258 I Magisk  : bind_mount: /system/bin/akmd8963
01-04 20:22:22.395   257   258 I Magisk  : bind_mount: /system/bin/akmd8975
01-04 20:22:22.395   257   258 I Magisk  : bind_mount: /system/bin/am
01-04 20:22:22.395   257   258 I Magisk  : bind_mount: /system/bin/ami304d
01-04 20:22:22.395   257   258 I Magisk  : bind_mount: /system/bin/app_process32
01-04 20:22:22.395   257   258 I Magisk  : bind_mount: /system/bin/app_process64
01-04 20:22:22.395   257   258 I Magisk  : bind_mount: /system/bin/applypatch
01-04 20:22:22.395   257   258 I Magisk  : bind_mount: /system/bin/appops
01-04 20:22:22.395   257   258 I Magisk  : bind_mount: /system/bin/appwidget
01-04 20:22:22.395   257   258 I Magisk  : bind_mount: /system/bin/atci_service
01-04 20:22:22.395   257   258 I Magisk  : bind_mount: /system/bin/atcid
01-04 20:22:22.395   257   258 I Magisk  : bind_mount: /system/bin/atrace
01-04 20:22:22.396   257   258 I Magisk  : bind_mount: /system/bin/audiocmdservice_atci
01-04 20:22:22.396   257   258 I Magisk  : bind_mount: /system/bin/autokd
01-04 20:22:22.396   257   258 I Magisk  : bind_mount: /system/bin/badblocks
01-04 20:22:22.396   257   258 I Magisk  : bind_mount: /system/bin/batterywarning
01-04 20:22:22.396   257   258 I Magisk  : bind_mount: /system/bin/bcc
01-04 20:22:22.396   257   258 I Magisk  : bind_mount: /system/bin/blkid
01-04 20:22:22.396   257   258 I Magisk  : bind_mount: /system/bin/bmgr
01-04 20:22:22.396   257   258 I Magisk  : bind_mount: /system/bin/bmi160d
01-04 20:22:22.396   257   258 I Magisk  : bind_mount: /system/bin/bmm050d
01-04 20:22:22.396   257   258 I Magisk  : bind_mount: /system/bin/boot_logo_updater
01-04 20:22:22.396   257   258 I Magisk  : bind_mount: /system/bin/bootanimation
01-04 20:22:22.396   257   258 I Magisk  : bind_mount: /system/bin/btconfig
01-04 20:22:22.397   257   258 I Magisk  : bind_mount: /system/bin/btlogmask
01-04 20:22:22.397   257   258 I Magisk  : bind_mount: /system/bin/bu
01-04 20:22:22.397   257   258 I Magisk  : bind_mount: /system/bin/bugreport
01-04 20:22:22.397   257   258 I Magisk  : bind_mount: /system/bin/capture_audio.sh
01-04 20:22:22.397   257   258 I Magisk  : bind_mount: /system/bin/ccci_fsd
01-04 20:22:22.397   257   258 I Magisk  : bind_mount: /system/bin/ccci_mdinit
01-04 20:22:22.397   257   258 I Magisk  : bind_mount: /system/bin/clatd
01-04 20:22:22.397   257   258 I Magisk  : bind_mount: /system/bin/consumerird
01-04 20:22:22.397   257   258 I Magisk  : bind_mount: /system/bin/content
01-04 20:22:22.397   257   258 I Magisk  : bind_mount: /system/bin/dalvikvm32
01-04 20:22:22.397   257   258 I Magisk  : bind_mount: /system/bin/dalvikvm64
01-04 20:22:22.397   257   258 I Magisk  : bind_mount: /system/bin/debuggerd
01-04 20:22:22.398   257   258 I Magisk  : bind_mount: /system/bin/debuggerd64
01-04 20:22:22.398   257   258 I Magisk  : bind_mount: /system/bin/dex2oat
01-04 20:22:22.398   257   258 I Magisk  : bind_mount: /system/bin/dhcp6c
01-04 20:22:22.398   257   258 I Magisk  : bind_mount: /system/bin/dhcp6ctl
01-04 20:22:22.398   257   258 I Magisk  : bind_mount: /system/bin/dhcp6s
01-04 20:22:22.398   257   258 I Magisk  : bind_mount: /system/bin/dhcpcd
01-04 20:22:22.398   257   258 I Magisk  : bind_mount: /system/bin/dmlog
01-04 20:22:22.398   257   258 I Magisk  : bind_mount: /system/bin/dnsmasq
01-04 20:22:22.398   257   258 I Magisk  : bind_mount: /system/bin/downloader
01-04 20:22:22.398   257   258 I Magisk  : bind_mount: /system/bin/dpm
01-04 20:22:22.398   257   258 I Magisk  : bind_mount: /system/bin/drmserver
01-04 20:22:22.398   257   258 I Magisk  : bind_mount: /system/bin/dualmdlogger
01-04 20:22:22.399   257   258 I Magisk  : bind_mount: /system/bin/dumpstate
01-04 20:22:22.399   257   258 I Magisk  : bind_mount: /system/bin/dumpsys
01-04 20:22:22.399   257   258 I Magisk  : bind_mount: /system/bin/e2fsck
01-04 20:22:22.399   257   258 I Magisk  : bind_mount: /system/bin/em_svr
01-04 20:22:22.399   257   258 I Magisk  : bind_mount: /system/bin/emdlogger1
01-04 20:22:22.399   257   258 I Magisk  : bind_mount: /system/bin/evi
01-04 20:22:22.399   257   258 I Magisk  : bind_mount: /system/bin/ext4_resize
01-04 20:22:22.399   257   258 I Magisk  : bind_mount: /system/bin/factory
01-04 20:22:22.399   257   258 I Magisk  : bind_mount: /system/bin/fdpp
01-04 20:22:22.399   257   258 I Magisk  : bind_mount: /system/bin/fsck_msdos
01-04 20:22:22.399   257   258 I Magisk  : bind_mount: /system/bin/fsck_msdos_mtk
01-04 20:22:22.399   257   258 I Magisk  : bind_mount: /system/bin/fuelgauged
01-04 20:22:22.400   257   258 I Magisk  : bind_mount: /system/bin/geomagneticd
01-04 20:22:22.400   257   258 I Magisk  : bind_mount: /system/bin/gsm0710muxd
01-04 20:22:22.400   257   258 I Magisk  : bind_mount: /system/bin/gsm0710muxdmd2
01-04 20:22:22.400   257   258 I Magisk  : bind_mount: /system/bin/guiext-server
01-04 20:22:22.400   257   258 I Magisk  : bind_mount: /system/bin/gzip
01-04 20:22:22.400   257   258 I Magisk  : bind_mount: /system/bin/hostapd
01-04 20:22:22.400   257   258 I Magisk  : bind_mount: /system/bin/hostapd_cli
01-04 20:22:22.400   257   258 I Magisk  : bind_mount: /system/bin/idmap
01-04 20:22:22.400   257   258 I Magisk  : bind_mount: /system/bin/ime
01-04 20:22:22.400   257   258 I Magisk  : bind_mount: /system/bin/init.atmel_ts.sh
01-04 20:22:22.400   257   258 I Magisk  : bind_mount: /system/bin/input
01-04 20:22:22.400   257   258 I Magisk  : bind_mount: /system/bin/installd
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/ip
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/ip6tables
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/iptables
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/keystore
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/kpoc_charger
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/lcdc_screen_cap
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/linker
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/linker64
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/lmkd
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/logcat
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/logd
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/logwrapper
01-04 20:22:22.401   257   258 I Magisk  : bind_mount: /system/bin/lsm303md
01-04 20:22:22.402   257   258 I Magisk  : bind_mount: /system/bin/lsm6ds3d
01-04 20:22:22.402   257   258 I Magisk  : bind_mount: /system/bin/magd
01-04 20:22:22.402   257   258 I Magisk  : bind_mount: /system/bin/make_ext4fs
01-04 20:22:22.402   257   258 I Magisk  : bind_mount: /system/bin/matv
01-04 20:22:22.402   257   258 I Magisk  : bind_mount: /system/bin/mc6420d
01-04 20:22:22.402   257   258 I Magisk  : bind_mount: /system/bin/mcd
01-04 20:22:22.402   257   258 I Magisk  : bind_mount: /system/bin/md_ctrl
01-04 20:22:22.402   257   258 I Magisk  : bind_mount: /system/bin/mdlogger
01-04 20:22:22.402   257   258 I Magisk  : bind_mount: /system/bin/mdnsd
01-04 20:22:22.402   257   258 I Magisk  : bind_mount: /system/bin/media
01-04 20:22:22.402   257   258 I Magisk  : bind_mount: /system/bin/mediaserver
01-04 20:22:22.402   257   258 I Magisk  : bind_mount: /system/bin/memorydumper
01-04 20:22:22.403   257   258 I Magisk  : bind_mount: /system/bin/memsicd
01-04 20:22:22.403   257   258 I Magisk  : bind_mount: /system/bin/memsicd3416x
01-04 20:22:22.403   257   258 I Magisk  : bind_mount: /system/bin/meta_tst
01-04 20:22:22.403   257   258 I Magisk  : bind_mount: /system/bin/mfv_ut
01-04 20:22:22.403   257   258 I Magisk  : bind_mount: /system/bin/mitop
01-04 20:22:22.403   257   258 I Magisk  : bind_mount: /system/bin/mke2fs
01-04 20:22:22.403   257   258 I Magisk  : bind_mount: /system/bin/mmp
01-04 20:22:22.403   257   258 I Magisk  : bind_mount: /system/bin/mobile_log_d
01-04 20:22:22.403   257   258 I Magisk  : bind_mount: /system/bin/monkey
01-04 20:22:22.403   257   258 I Magisk  : bind_mount: /system/bin/mpud6050
01-04 20:22:22.403   257   258 I Magisk  : bind_mount: /system/bin/msensord
01-04 20:22:22.404   257   258 I Magisk  : bind_mount: /system/bin/mtk_agpsd
01-04 20:22:22.404   257   258 I Magisk  : bind_mount: /system/bin/mtk_setprop
01-04 20:22:22.404   257   258 I Magisk  : bind_mount: /system/bin/mtkbt
01-04 20:22:22.404   257   258 I Magisk  : bind_mount: /system/bin/mtkrild
01-04 20:22:22.404   257   258 I Magisk  : bind_mount: /system/bin/mtkrildmd2
01-04 20:22:22.404   257   258 I Magisk  : bind_mount: /system/bin/mtpd
01-04 20:22:22.404   257   258 I Magisk  : bind_mount: /system/bin/muxreport
01-04 20:22:22.404   257   258 I Magisk  : bind_mount: /system/bin/ndc
01-04 20:22:22.404   257   258 I Magisk  : bind_mount: /system/bin/netcfg
01-04 20:22:22.404   257   258 I Magisk  : bind_mount: /system/bin/netd
01-04 20:22:22.404   257   258 I Magisk  : bind_mount: /system/bin/netdiag
01-04 20:22:22.405   257   258 I Magisk  : bind_mount: /system/bin/nvram_agent_binder
01-04 20:22:22.405   257   258 I Magisk  : bind_mount: /system/bin/nvram_daemon
01-04 20:22:22.405   257   258 I Magisk  : bind_mount: /system/bin/oatdump
01-04 20:22:22.405   257   258 I Magisk  : bind_mount: /system/bin/orientationd
01-04 20:22:22.405   257   258 I Magisk  : bind_mount: /system/bin/patchoat
01-04 20:22:22.405   257   258 I Magisk  : bind_mount: /system/bin/perf_native_test
01-04 20:22:22.405   257   258 I Magisk  : bind_mount: /system/bin/permission_check
01-04 20:22:22.405   257   258 I Magisk  : bind_mount: /system/bin/ping
01-04 20:22:22.405   257   258 I Magisk  : bind_mount: /system/bin/ping6
01-04 20:22:22.405   257   258 I Magisk  : bind_mount: /system/bin/playback_audio.sh
01-04 20:22:22.405   257   258 I Magisk  : bind_mount: /system/bin/pm
01-04 20:22:22.406   257   258 I Magisk  : bind_mount: /system/bin/ppl_agent
01-04 20:22:22.406   257   258 I Magisk  : bind_mount: /system/bin/pppd
01-04 20:22:22.406   257   258 I Magisk  : bind_mount: /system/bin/pppd_btdun
01-04 20:22:22.406   257   258 I Magisk  : bind_mount: /system/bin/pppd_dt
01-04 20:22:22.406   257   258 I Magisk  : bind_mount: /system/bin/pq
01-04 20:22:22.406   257   258 I Magisk  : bind_mount: /system/bin/racoon
01-04 20:22:22.406   257   258 I Magisk  : bind_mount: /system/bin/radvd
01-04 20:22:22.406   257   258 I Magisk  : bind_mount: /system/bin/reboot
01-04 20:22:22.406   257   258 I Magisk  : bind_mount: /system/bin/recovery
01-04 20:22:22.406   257   258 I Magisk  : bind_mount: /system/bin/requestsync
01-04 20:22:22.406   257   258 I Magisk  : bind_mount: /system/bin/resize2fs
01-04 20:22:22.407   257   258 I Magisk  : bind_mount: /system/bin/resize_ext4
01-04 20:22:22.407   257   258 I Magisk  : bind_mount: /system/bin/rtt
01-04 20:22:22.407   257   258 I Magisk  : bind_mount: /system/bin/run-as
01-04 20:22:22.407   257   258 I Magisk  : bind_mount: /system/bin/s62xd
01-04 20:22:22.407   257   258 I Magisk  : bind_mount: /system/bin/schedtest
01-04 20:22:22.407   257   258 I Magisk  : bind_mount: /system/bin/screencap
01-04 20:22:22.407   257   258 I Magisk  : bind_mount: /system/bin/screencolor
01-04 20:22:22.407   257   258 I Magisk  : bind_mount: /system/bin/screenrecord
01-04 20:22:22.407   257   258 I Magisk  : bind_mount: /system/bin/sdcard
01-04 20:22:22.407   257   258 I Magisk  : bind_mount: /system/bin/sensorservice
01-04 20:22:22.407   257   258 I Magisk  : bind_mount: /system/bin/service
01-04 20:22:22.407   257   258 I Magisk  : bind_mount: /system/bin/servicemanager
01-04 20:22:22.408   257   258 I Magisk  : bind_mount: /system/bin/settings
01-04 20:22:22.408   257   258 I Magisk  : bind_mount: /system/bin/sh
01-04 20:22:22.408   257   258 I Magisk  : bind_mount: /system/bin/sn
01-04 20:22:22.408   257   258 I Magisk  : bind_mount: /system/bin/stp_dump3
01-04 20:22:22.408   257   258 I Magisk  : bind_mount: /system/bin/superumount
01-04 20:22:22.408   257   258 I Magisk  : bind_mount: /system/bin/surfaceflinger
01-04 20:22:22.408   257   258 I Magisk  : bind_mount: /system/bin/svc
01-04 20:22:22.408   257   258 I Magisk  : bind_mount: /system/bin/tc
01-04 20:22:22.408   257   258 I Magisk  : bind_mount: /system/bin/terservice
01-04 20:22:22.408   257   258 I Magisk  : bind_mount: /system/bin/tertestclient
01-04 20:22:22.408   257   258 I Magisk  : bind_mount: /system/bin/thermal
01-04 20:22:22.409   257   258 I Magisk  : bind_mount: /system/bin/thermal_manager
01-04 20:22:22.409   257   258 I Magisk  : bind_mount: /system/bin/thermald
01-04 20:22:22.409   257   258 I Magisk  : bind_mount: /system/bin/tiny_mkswap
01-04 20:22:22.409   257   258 I Magisk  : bind_mount: /system/bin/tiny_swapoff
01-04 20:22:22.409   257   258 I Magisk  : bind_mount: /system/bin/tiny_swapon
01-04 20:22:22.409   257   258 I Magisk  : bind_mount: /system/bin/toolbox
01-04 20:22:22.409   257   258 I Magisk  : bind_mount: /system/bin/tune2fs
01-04 20:22:22.409   257   258 I Magisk  : bind_mount: /system/bin/uiautomator
01-04 20:22:22.409   257   258 I Magisk  : bind_mount: /system/bin/uncrypt
01-04 20:22:22.409   257   258 I Magisk  : bind_mount: /system/bin/vdc
01-04 20:22:22.409   257   258 I Magisk  : bind_mount: /system/bin/vold
01-04 20:22:22.410   257   258 I Magisk  : bind_mount: /system/bin/wifi2agps
01-04 20:22:22.410   257   258 I Magisk  : bind_mount: /system/bin/wm
01-04 20:22:22.410   257   258 I Magisk  : bind_mount: /system/bin/wmt_loader
01-04 20:22:22.410   257   258 I Magisk  : bind_mount: /system/bin/wpa_cli
01-04 20:22:22.410   257   258 I Magisk  : bind_mount: /system/bin/wpa_supplicant
01-04 20:22:22.410   257   258 I Magisk  : bind_mount: /system/bin/xlog
01-04 20:22:22.410   257   258 I Magisk  : bind_mount: /system/bin/yamaha537
01-04 20:22:22.410   257   258 I Magisk  : bind_mount: /system/bin/zip_utils
01-04 20:22:22.410   257   258 I Magisk  : copy_link : /system/bin/app_process
01-04 20:22:22.410   257   258 I Magisk  : copy_link : /system/bin/dalvikvm
01-04 20:22:22.410   257   258 I Magisk  : copy_link : /system/bin/cat
01-04 20:22:22.411   257   258 I Magisk  : copy_link : /system/bin/chcon
01-04 20:22:22.411   257   258 I Magisk  : copy_link : /system/bin/chmod
01-04 20:22:22.411   257   258 I Magisk  : copy_link : /system/bin/chown
01-04 20:22:22.411   257   258 I Magisk  : copy_link : /system/bin/clear
01-04 20:22:22.411   257   258 I Magisk  : copy_link : /system/bin/cmp
01-04 20:22:22.411   257   258 I Magisk  : copy_link : /system/bin/cp
01-04 20:22:22.411   257   258 I Magisk  : copy_link : /system/bin/date
01-04 20:22:22.411   257   258 I Magisk  : copy_link : /system/bin/dd
01-04 20:22:22.411   257   258 I Magisk  : copy_link : /system/bin/df
01-04 20:22:22.411   257   258 I Magisk  : copy_link : /system/bin/dmesg
01-04 20:22:22.411   257   258 I Magisk  : copy_link : /system/bin/du
01-04 20:22:22.411   257   258 I Magisk  : copy_link : /system/bin/getenforce
01-04 20:22:22.412   257   258 I Magisk  : copy_link : /system/bin/getevent
01-04 20:22:22.412   257   258 I Magisk  : copy_link : /system/bin/getprop
01-04 20:22:22.412   257   258 I Magisk  : copy_link : /system/bin/getsebool
01-04 20:22:22.412   257   258 I Magisk  : copy_link : /system/bin/grep
01-04 20:22:22.412   257   258 I Magisk  : copy_link : /system/bin/hd
01-04 20:22:22.412   257   258 I Magisk  : copy_link : /system/bin/id
01-04 20:22:22.412   257   258 I Magisk  : copy_link : /system/bin/ifconfig
01-04 20:22:22.412   257   258 I Magisk  : copy_link : /system/bin/iftop
01-04 20:22:22.412   257   258 I Magisk  : copy_link : /system/bin/insmod
01-04 20:22:22.412   257   258 I Magisk  : copy_link : /system/bin/ioctl
01-04 20:22:22.412   257   258 I Magisk  : copy_link : /system/bin/ionice
01-04 20:22:22.412   257   258 I Magisk  : copy_link : /system/bin/kill
01-04 20:22:22.413   257   258 I Magisk  : copy_link : /system/bin/ln
01-04 20:22:22.413   257   258 I Magisk  : copy_link : /system/bin/load_policy
01-04 20:22:22.413   257   258 I Magisk  : copy_link : /system/bin/log
01-04 20:22:22.413   257   258 I Magisk  : copy_link : /system/bin/ls
01-04 20:22:22.413   257   258 I Magisk  : copy_link : /system/bin/lsmod
01-04 20:22:22.413   257   258 I Magisk  : copy_link : /system/bin/lsof
01-04 20:22:22.413   257   258 I Magisk  : copy_link : /system/bin/md5
01-04 20:22:22.413   257   258 I Magisk  : copy_link : /system/bin/mkdir
01-04 20:22:22.413   257   258 I Magisk  : copy_link : /system/bin/mknod
01-04 20:22:22.413   257   258 I Magisk  : copy_link : /system/bin/mkswap
01-04 20:22:22.413   257   258 I Magisk  : copy_link : /system/bin/mount
01-04 20:22:22.413   257   258 I Magisk  : copy_link : /system/bin/mv
01-04 20:22:22.414   257   258 I Magisk  : copy_link : /system/bin/nandread
01-04 20:22:22.414   257   258 I Magisk  : copy_link : /system/bin/netstat
01-04 20:22:22.414   257   258 I Magisk  : copy_link : /system/bin/newfs_msdos
01-04 20:22:22.414   257   258 I Magisk  : copy_link : /system/bin/nohup
01-04 20:22:22.414   257   258 I Magisk  : copy_link : /system/bin/notify
01-04 20:22:22.414   257   258 I Magisk  : copy_link : /system/bin/printenv
01-04 20:22:22.414   257   258 I Magisk  : copy_link : /system/bin/ps
01-04 20:22:22.414   257   258 I Magisk  : copy_link : /system/bin/readlink
01-04 20:22:22.414   257   258 I Magisk  : copy_link : /system/bin/renice
01-04 20:22:22.414   257   258 I Magisk  : copy_link : /system/bin/restorecon
01-04 20:22:22.414   257   258 I Magisk  : copy_link : /system/bin/rm
01-04 20:22:22.414   257   258 I Magisk  : copy_link : /system/bin/rmdir
01-04 20:22:22.415   257   258 I Magisk  : copy_link : /system/bin/rmmod
01-04 20:22:22.415   257   258 I Magisk  : copy_link : /system/bin/route
01-04 20:22:22.415   257   258 I Magisk  : copy_link : /system/bin/runcon
01-04 20:22:22.415   257   258 I Magisk  : copy_link : /system/bin/schedtop
01-04 20:22:22.415   257   258 I Magisk  : copy_link : /system/bin/sendevent
01-04 20:22:22.415   257   258 I Magisk  : copy_link : /system/bin/setenforce
01-04 20:22:22.415   257   258 I Magisk  : copy_link : /system/bin/setprop
01-04 20:22:22.415   257   258 I Magisk  : copy_link : /system/bin/setsebool
01-04 20:22:22.415   257   258 I Magisk  : copy_link : /system/bin/sleep
01-04 20:22:22.415   257   258 I Magisk  : copy_link : /system/bin/smd
01-04 20:22:22.415   257   258 I Magisk  : copy_link : /system/bin/start
01-04 20:22:22.416   257   258 I Magisk  : copy_link : /system/bin/stop
01-04 20:22:22.416   257   258 I Magisk  : copy_link : /system/bin/swapoff
01-04 20:22:22.416   257   258 I Magisk  : copy_link : /system/bin/swapon
01-04 20:22:22.416   257   258 I Magisk  : copy_link : /system/bin/sync
01-04 20:22:22.416   257   258 I Magisk  : copy_link : /system/bin/top
01-04 20:22:22.416   257   258 I Magisk  : copy_link : /system/bin/touch
01-04 20:22:22.416   257   258 I Magisk  : copy_link : /system/bin/umount
01-04 20:22:22.416   257   258 I Magisk  : copy_link : /system/bin/uptime
01-04 20:22:22.416   257   258 I Magisk  : copy_link : /system/bin/vmstat
01-04 20:22:22.416   257   258 I Magisk  : copy_link : /system/bin/watchprops
01-04 20:22:22.416   257   258 I Magisk  : copy_link : /system/bin/wipe
01-04 20:22:22.426   257   287 I Magisk  : * Starting MagiskHide
01-04 20:22:22.426   257   287 I Magisk  : hide_utils: Hiding sensitive props
01-04 20:22:22.426   257   287 I Magisk  : hide_list: [com.google.android.gms/.droidguard.DroidGuardService]
01-04 20:22:23.057   257   363 I Magisk  : ** late_start service mode running
01-04 20:22:23.058   257   363 I Magisk  : * Running service.d scripts
01-04 20:22:23.510   257   363 I Magisk  : * Running module service scripts
01-04 20:23:33.556   257   287 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[3918] ns=[4026534497]
01-04 20:25:12.430  8153  8153 W Magisk  : su: request rejected (10104->0)
01-04 20:25:30.154  8295  8295 W Magisk  : su: request rejected (10104->0)
01-04 20:44:01.485 13684 13684 W Magisk  : su: request rejected (10119->0)
01-04 20:44:21.128 13822 13822 W Magisk  : su: request rejected (10117->0)
01-04 20:45:02.134 14019 14019 W Magisk  : su: request rejected (10119->0)
01-04 20:46:02.260 14488 14488 E Magisk  : write failed with 32: Broken pipe

**Comment by topjohnwu** [comment]
You have to exclude Magisk Manager from battery optimizations
