### ISSUE TITLE
zipsigner - reproducible zip files

### ISSUE THREAD

**Issue by ale5000-git** [topjohnwu/Magisk#932]
I want to create signed zip files with the same sha256 hash on different OS.

The signed zip files are almost identical but the are some differences on Windows vs Linux.
Is it possible to make zipsigner working the same under all OS?

The diff file is here:
[diff.txt](https://github.com/topjohnwu/Magisk/files/2717600/diff.txt)

Files inside the zip files have the same hash but the zip file itself _no_.

There is one difference repeated many times (I'm not sure if there are also others):
- On Linux a byte with hex code: 14
- Where on Windows in the same place appears a byte with hex code: 1C

**Comment by ale5000-git** [comment]
There is one diffetrence repeated many times (I'm not sure if there are also other).

On Linux, hex code: 14
On Windows, hex code: 1C

**Comment by topjohnwu** [comment]
Doesn't seem to be an issue to me. I use the implementation of zip in JVM, so it depends on what JRE you are using

**Comment by ale5000-git** [comment]
After some tests I have discovered that all the differences was caused by the time zone.
To fix the issue I just executed it in this way:
`java -Duser.timezone=GMT -jar zipsigner.jar ...`
