### ISSUE TITLE
Feature request *.rc scripts injection for modules 

### ISSUE THREAD

**Issue by AGagarin** [topjohnwu/Magisk#933]
Hi there. It would be nice to have an ability to inject *.rc scripts  as a part of module (rebuild boot.img)
Originally there is a only one script injected into init.rc (init.magisk.rc)
However  to support some low level, hardware features *.rc scripts injections are required on init stage.

**Comment by topjohnwu** [comment]
Sorry, it isn't possible technically

**Comment by AGagarin** [comment]
Why ? https://forum.xda-developers.com/pixel-2-xl/how-to/guide-qxdm-port-activation-pixel-2-xl-t3884967#post78563337
