### ISSUE TITLE
Bad package name of Magisk Manager (Version 6.1.0-1df65940)

### ISSUE THREAD

**Issue by JoanVC100** [topjohnwu/Magisk#934]
Today I updated the Manager Canary app and I realized that the package name is one of the strings of the warning when you have to download de API of SafetyNet to check if the phone passes it. Specifically, the string is:

<string name="proprietary_title">Descarregar codi propietari</string>, Line 111 in values-ca/strings.xml

Here are the photos that prove it:

![manager 1](https://user-images.githubusercontent.com/36604048/50561040-22208700-0d07-11e9-8da4-2b11dee3972d.png)
![manager 2](https://user-images.githubusercontent.com/36604048/50561041-22208700-0d07-11e9-9c77-116e0c19876d.png)

**Comment by Didgeridoohan** [comment]
That's not the package name, but the app label. It's known...

For now, you can solve the problem by uninstalling the repackaged Manager and reinstall the latest Manager manually.

**Comment by JoanVC100** [comment]
I tested what you said and now I have the app label correctly, thanks.

PD: Sorry for saying "package name", I'm not very good with English, so sorry for the confusion, I was referring to the name of the app, the package it will be like "com.topjohnwu.magisk", but anyways thanks for clarifying that.

Closing issue...
