### ISSUE TITLE
The Magisk Manager app can't donwload new versions of Magisk (Canary Build)

### ISSUE THREAD

**Issue by JoanVC100** [topjohnwu/Magisk#935]
When I try to download new versions of Magisk they just do not appear and I can't download through the Manager app.

![manager](https://user-images.githubusercontent.com/36604048/50561449-29499400-0d0b-11e9-81c0-db13fde93545.gif)

**Comment by Didgeridoohan** [comment]
That's actually a feature, not a bug (introduced a few days ago):
https://github.com/topjohnwu/Magisk/commit/58ba0b0b4eb39c0e7a1f3b0dc783dde1f2863371

I don't speak the language you have set, but I'm going to assume that "Actualizació" means update. Click that button and you'll be good to go.

You can close this issue now.

**Comment by JoanVC100** [comment]
Oh, okey (I feel a little stupid right now 😳). Thanks for that, now I will close this.
