### ISSUE TITLE
Magisk Manager fails to directly install Magisk updates

### ISSUE THREAD

**Issue by lightspeed397** [topjohnwu/Magisk#938]
When I try to update Magisk from Magisk Manager via direct install method it gets to extracting files, and the system dialog box comes up and says Magisk Manager has stopped.
To update Magisk I have to boot into recovery, uninstall and flash the Magisk update.
This has happened on all versions of Magisk and Magisk Manager that I have tested.
My device is a BLU Life One X2 Stock ROM TWRP Recovery.

**Comment by topjohnwu** [comment]
Please provide logs

**Comment by lightspeed397** [comment]
Here are the logs and screenshots attached.
Hopefully they have everything you need.
.zip file contains 3 system logs.
![screenshot_20190101-110239](https://user-images.githubusercontent.com/46253776/50783190-b9d62600-126f-11e9-869a-a4c461f826f1.png)
![screenshot_20190101-110250](https://user-images.githubusercontent.com/46253776/50783191-bb075300-126f-11e9-94d2-4be6695bd86f.png)
![screenshot_20190101-110254](https://user-images.githubusercontent.com/46253776/50783195-bcd11680-126f-11e9-8ca3-b6ed4708ab1b.png)
[2019-01-04_20.41.zip](https://github.com/topjohnwu/Magisk/files/2733660/2019-01-04_20.41.zip)
[alogcat.2019-01-04-20-27-35-0600.txt](https://github.com/topjohnwu/Magisk/files/2733661/alogcat.2019-01-04-20-27-35-0600.txt)
[magisk_log_20190104_203509.log](https://github.com/topjohnwu/Magisk/files/2733662/magisk_log_20190104_203509.log)
