### ISSUE TITLE
Latest Magisk does not install on stock Samsung kernel

### ISSUE THREAD

**Issue by adroidnote4** [topjohnwu/Magisk#94]
Hi,

Further to reported issue #30 where MagiskHide encounters an error with stock Samsung kernels and you reported that Samsung kernel seems to hide namespace of processes i.e. Magisk Hide doesn't play well with stock Samsung devices.

Unfortunately, latest version of Magisk (v11/v11.1) does not install on stock Samsung kernel...I've tried through recovery and via Magisk manager, but Magisk fails to install, only superuser is installed!

Please note that I was able to install Magisk v9 and v10 on Samsung stock kernels without any issues but Magisk hide was not working. 

Magisk v11.1 installs fine on custom Samsung kernel and also passes SafetyNet.

See attached recovery logs and screen shots showing magisk not installed.

Thanks for your support on Samsung devices.
[Logs2.zip](https://github.com/topjohnwu/Magisk/files/801992/Logs2.zip)

**Comment by ccerrillo** [comment]
I have the same issue, to install magisk i need to flash boefla kernel or supersu before magisk

The zip attached is the boot.img of the stock based rom
[boot.img.zip](https://github.com/topjohnwu/Magisk/files/835013/boot.img.zip)

**Comment by woyaojizhu8** [comment]
Same issue here, so I downgraded from v11.1 to v10.2. Topjohnwu said v11.6 has fixed some issues with samsung devices on v11.5, so maybe you can try it.

**Comment by TurokO8A** [comment]
Same Issue here on v11.6, did a proper install removing Chainfire's SuperSU (full unroot) Xposed, and everything else... Magisk doesn't detect the installed version after reboot. This was tested on a Galaxy J7 (SM-J700M) running SDK23(M 6.0.1). I got it to work on an alternate "stock" marshamllow kernel, however SafetyNet still shows the CTS mismatch (tried disabling magisk/magisk hide and rebooting several times). Yet, the original kernel remains unsupported. Would really appreciate some help on this issue. (both tested kernels attached.)

[SM-J700M boot.img (stock and alternate).zip](https://github.com/topjohnwu/Magisk/files/871787/SM-J700M.boot.img.stock.and.alternate.zip)

**Comment by topjohnwu** [comment]
Samsung issues are all fixed

**Comment by TurokO8A** [comment]
I don't really want to reopen a closed issue but Magisk 12.0 didn't fix the issue (loosing root after reboot) on my Galaxy J7... In my previous post I said the alternate kernel I used was able to keep root but wouldn't get through safetynet. This time, it won't keep root even on the alternate kernel (both the original and the alternate one are attached on my previous post). I would really apreciate some help with this one, I really support this platform. Thank you in advance :)

**Comment by TurokO8A** [comment]
I just noticed that after rebooting and loosing root, I get a notification saying that unauthorized changes were detected and I should reboot to erase them... maybe it has to do with that?

**Comment by TurokO8A** [comment]
Hey! I'd like to retract that statement... after a couple of reboots and a long delay after booting, MagiskSU started working again. The SU delay is still there at boot but it seems to have diminished after a couple boots. Everything else works great, including Magisk Hide. Apart from that detail, Magisk 12.0 works great on Samsung devices :)
