### ISSUE TITLE
Can't Downgrade Module (System App)

### ISSUE THREAD

**Issue by maruashok** [topjohnwu/Magisk#940]
I have a module which installs apk as a system app,
Problem is suppose  i install app which has version 2.0 and module has also version 2.0 now if i uninstall that module ,twice reboot,wipe dalvik cache and install same module but now apk version is 1.0 and also module version is also 1.0 in that case app failed to start.

i extract module v1.0  and  check apk file with Es File Explorer it says installed version is 2.0 and current version is 1.0 but i already uninstalled module v2.0. to confirm issue goto /system/priv-app/ and checked my apk and its of version 1.0.

i think i am missing something, i used latest template and did some small changes in module.prop and push apk file in /system/priv-app/MyApp/MyApp.apk

**Comment by topjohnwu** [comment]
This is not a Magisk problem, but a module problem

**Comment by maruashok** [comment]
How to solve it..??
