### ISSUE TITLE
Magisk break charging when phone is powered off on MARLIN

### ISSUE THREAD

**Issue by cydia2020** [topjohnwu/Magisk#945]
Hello,
Thank you for your great work.

I've recently noticed that magisk 18.0 break charging when the phone is off, the phone will stuck at the charging splash screen and never comments charging.

I have to hold the power button to force the phone to power off and reboot to the system to charge.

Phone: Pixel XL
OS: PQ1A.181205.002.A1 (Dec 18 security patch)
Original kernel

**Comment by Didgeridoohan** [comment]
https://github.com/topjohnwu/Magisk/issues/906
