### ISSUE TITLE
Magisk installation disables USB debugging in developer options

### ISSUE THREAD

**Issue by a3k80xfy4npyd6wku1** [topjohnwu/Magisk#946]
**Steps to reproduce:**

1. Enable developer options
2. Enable USB debugging
3. Flash Magisk-v18.0.zip

_USB debugging is disabled_

**Steps to revert:**

1. Flash Magisk-uninstaller-20181208.zip

_USB debugging is enabled_

**Comment by Didgeridoohan** [comment]
First if all, any bug report need to be accompanied by proper logs... Without it, the issue will just be closed without further comment. Some tips and help: https://www.didgeridoohan.com/magisk/MagiskHelp

Second, I'm going to make a guess at what's going on:

Some ROMs need to have ro.build.type set to "userdebug" (MagiskHide changes it to "user") for Developer options to appear. Maybe this is related? Try turning off MagiskHide and reboot. If that has any effect you can use the MagiskHide Props Config module to change whatever prop it is that's needed back to it's original value.

**Comment by topjohnwu** [comment]
@a3k80xfy4npyd6wku1 this is an issue of your custom ROM not following standard ADB enable/disable configuration. You can turn off MagiskHide if you want to preserve the original behavior of your ROM

**Comment by a3k80xfy4npyd6wku1** [comment]
Thanks for clarifying.

I found this issue on PixelExperience_whyred-9.0-20181228-1358-OFFICIAL.zip by @jhenrique09
