### ISSUE TITLE
Root with Magisk on Cubot Note plus - MT6737T Android

### ISSUE THREAD

**Issue by jsach1** [topjohnwu/Magisk#948]
Error: Unable to Unpack Boot Image  (solved)
Device: Cubot Note plus
Android 7.0 / FW COBOT_NOTE Plus_7151C_V12_20180522

**Comment by jsach1** [comment]
I had probably made a small mistake. I forgot to unlock the boot loader first. I suspect that will be the cause of the error message.
I will repeat the rooting of my cell phone on occasion and report the result here.

**Comment by jsach1** [comment]
Which file needs to be patched by Magisk Manager (Cubot Note plus / Android 7.0)?
- recovery.img
- recovery-verified.img
- ramdisk.img
- ramdisk-recovery.img
- boot.img
- boot-verified.img
And under which file name does the patched file have to be copied back to the device?

In the internet I have not found a clear file name for my phone.

**Comment by topjohnwu** [comment]
I will assume the issue to be the same as #980
