### ISSUE TITLE
Google Pixel XL Android 9.0 Charging Bug

### ISSUE THREAD

**Issue by saappleg** [topjohnwu/Magisk#949]
I have a bug that prevents the phone from charging past 96% after installing Magisk 18.0. Tried factory reset with factory image and reinstalling Magisk and still have the same issue. If you need any logs or anything let me know.

**Comment by topjohnwu** [comment]
This doesn't make any sense at all, and you didn't provide any relevant information

**Comment by saappleg** [comment]
There is a bug that I have narrowed down to being Magisk that will not allow the phone to charge past 96% I have produced it on two Pixel XLs (2016) running Magisk 18.0 on the latest January OTA. This is not the bug of it not charging while the phone is turned off.... This is while booted up and plugged into charge. 

When charging the only way to fully charge the device is to remove Magisk.

I have no modules installed so I know for a fact it is an issue with Magisk. 

What doesn't make sense? I have went through everything I can on my side to narrow down the issue to Magisk.

**Comment by Didgeridoohan** [comment]
Always assume that logs are necessary...

**Comment by saappleg** [comment]
01-07 18:36:03.897   614   614 I Magisk  : * Creating /sbin overlay
01-07 18:36:03.920   616   616 I Magisk  : Magisk v18.0(18000) daemon started
01-07 18:36:03.931   616   617 I Magisk  : ** post-fs-data mode running
01-07 18:36:03.931   616   617 I Magisk  : * Initializing Magisk environment
01-07 18:36:03.935   616   617 I Magisk  : * Mounting mirrors
01-07 18:36:03.936   616   617 I Magisk  : bind_mount: /sbin/.magisk/mirror/system
01-07 18:36:03.936   616   617 I Magisk  : mount: /sbin/.magisk/mirror/vendor
01-07 18:36:03.937   616   617 I Magisk  : bind_mount: /sbin/.magisk/mirror/bin
01-07 18:36:03.938   616   617 I Magisk  : * Setting up internal busybox
01-07 18:36:03.996   622   622 I Magisk  : Magisk v18.0(18000) logger started
01-07 18:36:04.047   616   617 I Magisk  : * Mounting /data/adb/magisk.img
01-07 18:36:04.079   616   617 I Magisk  : * Running post-fs-data.d scripts
01-07 18:36:04.079   616   617 I Magisk  : * Running module post-fs-data scripts
01-07 18:36:04.080   616   617 I Magisk  : * Loading modules
01-07 18:36:04.089   616   637 I Magisk  : * Starting MagiskHide
01-07 18:36:04.089   616   637 I Magisk  : hide_utils: Hiding sensitive props
01-07 18:36:04.090   616   637 I Magisk  : hide_list: [com.google.android.gms/.droidguard.DroidGuardService]
01-07 18:36:05.580   616   869 I Magisk  : ** late_start service mode running
01-07 18:36:05.580   616   869 I Magisk  : * Running service.d scripts
01-07 18:36:05.586   616   869 I Magisk  : * Running module service scripts
01-07 18:37:20.021   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[5052] ns=[4026534419]
01-07 18:37:48.599   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[6576] ns=[4026534367]
01-07 19:40:22.334   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[10672] ns=[4026534440]
01-07 20:33:50.055   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[19042] ns=[4026534330]
01-07 20:35:15.098   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[20858] ns=[4026534436]
01-07 20:36:16.281   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[21970] ns=[4026534466]
01-07 23:19:39.305   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[16613] ns=[4026534538]
01-08 00:07:19.164   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[21168] ns=[4026534563]
01-08 01:51:40.588   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[5337] ns=[4026534366]
01-08 04:54:26.960   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[29019] ns=[4026534380]
01-08 05:02:08.741   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[32231] ns=[4026534582]
01-08 05:30:06.984   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[2160] ns=[4026534380]
01-08 10:50:27.904   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[21247] ns=[4026534380]
01-08 13:52:46.380   616   637 I Magisk  : proc_monitor: com.google.android.gms/.droidguard.DroidGuardService PID=[30639] ns=[4026534380]


This is all I can find is this the log?
