### ISSUE TITLE
Mi8se Won't Boot After Flashing Magsik (All Version Above 16.6)

### ISSUE THREAD

**Issue by xiaowyyyyya** [topjohnwu/Magisk#951]
Magisk won't boot on Mi8se since a few months ago, all version above 16.6 won't boot. I am on the latest firmware for sure. And unfortunately adb logcat does not work because the boot admination won't even show up. But the good news is that I have the ramoops files and a few logs from recovery, I hope that will help. If you need any additional information, please leave a comment. Hopefully there is gonna be a fix coming soon))) https://drive.google.com/drive/folders/1F_LGXoYs9mrMBX1aCZXvgJQAGpzATTc3?usp=sharing
Thank you! Really appreciate your hard work!

**Comment by 10032x** [comment]
Same Issue Here!!!

**Comment by hulove** [comment]
Same Issue Here

_Sent from my Xiaomi MI 8 SE using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xiaowyyyyya** [comment]
It may be the issue with the boot.img
Here is a backup of my boot.ing (After flashing magisk 18.0 debug version)
https://drive.google.com/open?id=1QFq-Msy6TyIncO2GxIH5gQ8YrCjrnhHT

**Comment by xiaowyyyyya** [comment]
Here are some boot images from my friends:))) Just in case you need that
https://drive.google.com/open?id=1N43z9f6CmWkhlhAB3iqhBoCm7-zwf-m6

**Comment by lightspeed397** [comment]
I have had a similar issue with BLU life one x2 using Magisk v18.0 It loads the boot screen for a few seconds then reboots into recovery.
All other versions I have tested work just fine.

**Comment by xiaowyyyyya** [comment]
> I have had a similar issue with BLU life one x2 using Magisk v18.0 It loads the boot screen for a few seconds then reboots into recovery.
> All other versions I have tested work just fine.

You can open a new issue so the dev can better help you :)

**Comment by guglicap** [comment]
Same issue here. Let me know if you need anything that could help.

**Comment by xiaowyyyyya** [comment]
@topjohnwu

**Comment by asdffczx** [comment]
@topjohnwu

**Comment by topjohnwu** [comment]
Please check #980
