### ISSUE TITLE
logs provided

### ISSUE THREAD

**Issue by lightspeed397** [topjohnwu/Magisk#952]
Here are the logs and screenshots attached.
Hopefully they have everything you need.
.zip file contains 3 system logs.
[2019-01-04_20.41.zip](https://github.com/topjohnwu/Magisk/files/2733660/2019-01-04_20.41.zip)
[alogcat.2019-01-04-20-27-35-0600.txt](https://github.com/topjohnwu/Magisk/files/2733661/alogcat.2019-01-04-20-27-35-0600.txt)
[magisk_log_20190104_203509.log](https://github.com/topjohnwu/Magisk/files/2733662/magisk_log_20190104_203509.log)
![screenshot_20190101-110239](https://user-images.githubusercontent.com/46253776/50783190-b9d62600-126f-11e9-869a-a4c461f826f1.png)
![screenshot_20190101-110250](https://user-images.githubusercontent.com/46253776/50783191-bb075300-126f-11e9-94d2-4be6695bd86f.png)
![screenshot_20190101-110254](https://user-images.githubusercontent.com/46253776/50783195-bcd11680-126f-11e9-8ca3-b6ed4708ab1b.png)

_Originally posted by @lightspeed397 in https://github.com/topjohnwu/Magisk/issue_comments#issuecomment-452015551_

**Comment by lightspeed397** [comment]
If you need anything else let me know.
I will provide the necessary info asap.
thank you.

**Comment by Didgeridoohan** [comment]
To clarify, this is connected to issue https://github.com/topjohnwu/Magisk/issues/938.

**Comment by topjohnwu** [comment]
Your logs does not contain any crashes...
Also, #966 seems to be the same issue, I'll close this issue. Please continue the conversation over there.
