### ISSUE TITLE
magiskd drains battery

### ISSUE THREAD

**Issue by bluesky139** [topjohnwu/Magisk#955]
I have battery drain problem on Magisk, the magiskd process keeps use CPU, check my screenshot below, it keeps 30% CPU usage and never stop.

The problem happened with Magisk v18.0, I tried downgrade to v17.3, it still happened.

I use MagiskHide on several normal apps, I have 3 modules installed, they are only replace system files and set system properties, no other script execute.

System is AOSP Android 8.1, fresh system. When I try to downgrade to v17.3, I cleared user data, reflashed system image.

A strange behavior what I got is the high CPU usage is not happening at system just booted, it happens after several minutes/hours later.

Log is attached.

![image](https://user-images.githubusercontent.com/1788897/50869829-a30b0d00-13f0-11e9-929d-36ea4ff79985.png)

[magisk.log](https://github.com/topjohnwu/Magisk/files/2739002/magisk.log)

**Comment by crok** [comment]
Did you disable logd? That is the most likely reason most of the time..

**Comment by topjohnwu** [comment]
@bluesky139 please answer the question @crok asked :)

**Comment by bluesky139** [comment]
No, I didn't disable logd, and I don't know how to disable it.

**Comment by zzj0311** [comment]
@crok I have the same issue, what should I do with logd?

**Comment by topjohnwu** [comment]
This shouldn't be relevant after the new MagiskHide mechanism, closed

**Comment by Crescendo-BLYAT** [comment]
@topjohnwu it is still relevant... LOS 16.0 here, toggling Magisk Hide off/on rectified this high cpu usage...

**Comment by 805447391** [comment]
I have also faced this problem. The process 'magiskd' consuming cpu time 5 seconds per 5 seconds. Toggle magisk hide prop could fix this problem temporary, rebooting also, but,,,its difficult to recur it.

**Comment by seffparker** [comment]
I have the same issue. The work-around by @805447391 does the job. But its not a permanent fix.

Andoird 9, Magisk 18.1 / 7.1.1

**Comment by MartinX3** [comment]
Omnirom 9.0 based on Sony open devices project
Xperia xz2
I can confirm it
18.1 -> 2 processes 15% cpu each
19.0 -> 2 processes 100% CPU each

Deactivate magiskd his let the processes disappear from the top of "htop"

**Comment by MartinX3** [comment]
@topjohnwu

**Comment by crok** [comment]
> Omnirom 9.0 based on Sony open devices project
> Xperia xz2
> I can confirm it
> 18.1 -> 2 processes 15% cpu each
> 19.0 -> 2 processes 100% CPU each
> 
> Deactivate magiskd his let the processes disappear from the top of "htop"

Absolutely the same happens on my Mido, too.

**Comment by kuroyukihime0** [comment]
Same here with Magisk 19.0 and Mi9 9.0

**Comment by virusmoere** [comment]
Same here. Magisk 19 on pixel2 (April Update). Magiskd is using 100% CPU. If toggeling magiskd hide off and on the CPU usage normalizes until it ramps up again after some time.

**Comment by crok** [comment]
Indeed. The trigger seems to be an event of a "hiding" of root from an app on the list.

**Comment by Olit2000** [comment]
Having the same issue. I also foud that there are _two_ magiskd processes running, using around 90% of cpu and keeping the device awake. 
For me the problem seems to start right after reboot.
I think it is a greater problem because it has been described in other issues too: #1279 #1238 #541

**Comment by lin0lin0** [comment]
Just some observation. Updated Magisk 19.1 to 19.2 yesterday on my Xperia z3c CarbonRom 6.1.
Had no "magiskd" issues with some apps in Magisk Hide list at day time.

For the night I put phone to no mobile data and WiFi off.
Woke up for a pee and realized phone was dead for battery.
Three screenshots showing battery drain started likely about my bed time (perhaps when data cut off???).
After plugging adapter to charge up in htop I got two "magiskd" processes until I toggled Magisk Hide off and on again.
![Apps_20190522-065123](https://user-images.githubusercontent.com/50867244/58165155-74971b80-7c87-11e9-9c15-428dd30d410a.png)
![DropAtNight_20190522-064541](https://user-images.githubusercontent.com/50867244/58165156-74971b80-7c87-11e9-8ff3-ff481154d597.png)
![Screenshot_Termux_20190522-065302](https://user-images.githubusercontent.com/50867244/58165157-752fb200-7c87-11e9-92ab-03bf4de89253.png)

**Comment by MartinX3** [comment]
Try disabling magisk hide @lin0lin0 
It helped me. :)

**Comment by lin0lin0** [comment]
Hi MartinX3,
that's what I did in v19.1 permanently - and toggling is stopping magiskd high load as well. 
The bad thing is if I permanently disable Hide - I have to think before using BankingApp :-/
On the other hand empty battery is fatal because alarm clock wouldn't wake me up o.O

**Comment by MartinX3** [comment]
Please use a canary builds and follow these instructions to create a new bug report 
https://forum.xda-developers.com/apps/magisk/dev-magisk-canary-channel-bleeding-edge-t3839337
as described in the Readme of this repo :)

**Comment by bluemantwo** [comment]
I am having the same issue v19.0

**Comment by crok** [comment]
> I am having the same issue v19.0

Better upgrade to v19.3 (released at Jun 5, v19.0 is almost 4 months old).

Why are you using v19.0 anyway? It's a pre-May1st release, there was a huge upgrade in v19.1 (May1st release, new templates, new methods, imageless operation.. hell a lot of stuff).

**Comment by bluemantwo** [comment]
Thanks.  I did that and do not see CPU issue again yet.  But now I have lost all ability to hide root.  Rebooted, turned hide off/on.  Still root is being detected and safetynet fails.

**Comment by Olit2000** [comment]
I'm using Magisk 19.3 for a while now and I didn't have this issue either since I updated. The issue seems to have been solved

**Comment by ShaAmin-cpu** [comment]
![Screenshot_2019-08-18-09-25-45-62_354d8a2f68bc9775ed3c9363dac7e362](https://user-images.githubusercontent.com/53892191/63270126-2826a080-c2b5-11e9-8342-ca4dba22faa3.png)
im using magisk 19.4 canary build facing same problem.....Dont know how to fix it nothing works for me
