### ISSUE TITLE
unable to repack boot.img

### ISSUE THREAD

**Issue by silverik13** [topjohnwu/Magisk#956]
Hi, im sorry im new to this.
I want to root my S8, with stock rom and recovery,  with magisk but keeps saying unable to repack boot.img.
See attachements.

**Comment by silverik13** [comment]
![screenshot_20190108-163127_magisk manager](https://user-images.githubusercontent.com/46404778/50881628-836ce800-13e2-11e9-9be9-3a421c772aaa.jpg)
[magisk_install_log_20190108_114116.log](https://github.com/topjohnwu/Magisk/files/2739668/magisk_install_log_20190108_114116.log)

**Comment by silverik13** [comment]
Nobody??????

**Comment by topjohnwu** [comment]
The image you provided to Magisk Manager is incorrect. Please find a proper boot image to patch

**Comment by HarshAtGithub** [comment]
> ![screenshot_20190108-163127_magisk manager](https://user-images.githubusercontent.com/46404778/50881628-836ce800-13e2-11e9-9be9-3a421c772aaa.jpg)
> [magisk_install_log_20190108_114116.log](https://github.com/topjohnwu/Magisk/files/2739668/magisk_install_log_20190108_114116.log)

i have the exact same issue now. have you got any solution to this.?

**Comment by massic2** [comment]
My problem was that i forgot to unpack .lz4 file
