### ISSUE TITLE
can't update to 18.0

### ISSUE THREAD

**Issue by bailianmojun** [topjohnwu/Magisk#957]
xiaomi Mix3 can only use 17.1 magisk.when i try to update magisk, it will keep stopping in "magisk patched boot image detected".
       i saw your twitter,i know you are tired of Chinese Android problem because they change too many things.
       In China,we can't use Google Service and Google push,but Chinese software makers want let us know something sometimes,so they thought a stupid idea-"keep running in your Phone".almost all Chinese engineers do this because This is the only way.
        that 's why Chinese Android SYSTEM change many things and kill software more usually and stronger than nomal Android.

i wish you fix some Chinese problem.I know you are tired,and i understand you,but i am really love this software . not only me.there are many people love your software in china.
  if you want some Chinese help,i think you can download "coolapk", It is a kind of forum ,i knew magisk there.i think maybe you can join there and ask some people for test if you want.   

 Have goodday.

**Comment by xming521** [comment]
666

**Comment by topjohnwu** [comment]
@bailianmojun provide install logs so I can at least know what's happening

**Comment by bailianmojun** [comment]
@topjohnwu    is this what you want? it didn't tell me any error,but it will stop at last step in this log. nothing change even if i wait half hour


Detecting target image

Target image: /dev/block/ sde45
Device platform:  arm64-v8a
Downloading zip   100%

Extracting files

Unpacking boot image 

Checking  ramdisk status

Magisk patched boot image detected

**Comment by MPeti1** [comment]
@bailianmojun you can follow [this](https://www.didgeridoohan.com/magisk/MagiskHelp) guide to provide the meaningful logs

**Comment by TGSAN** [comment]
> @bailianmojun you can follow [this](https://www.didgeridoohan.com/magisk/MagiskHelp) guide to provide the meaningful logs

I have same problem in my MI MIX 3. However, TWRP and Magisk Magisk are suspended in the "Magisk patched boot images detected" step, so the log cannot be saved.

**Comment by MPeti1** [comment]
What do you mean by that they are suspended? Your phone automatically reboots after installation is complete?

**Comment by bailianmojun** [comment]
@MPeti1 installation can not be complete.because it stop working in "Magisk patched boot images detected" forever.

**Comment by deximy** [comment]
Same to you. What I need to add is that this question doesn't only happen to xiaomi mix 3, neither MIUI for China. My MIUI is downloaded from xiaomi.eu, which works like a normal Android system. Unfortunately, 18.0 still can't be installed.

**Comment by deximy** [comment]
What's more, when I tried to install Magisk after unstallation, it can't be installed completely. Magisk manager shows that Magisk is not installed after reboot. Here are the logs in Recovery:

************************
* Magisk v18.0 Installer
************************
- Mounting /system, /vendor
- Using system_root_image, keep dm/avb-verity
- Encrypted data detected, keep forceencrypt
- Target image: /dev/block/mmcblk0p60
- DTBO image: /dev/block/mmcblk0p52
- Device platform: arm64
- Constructing environment
Invalid image: not signed
- Unpacking boot image
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/dev/block/mmcblk0p60]
HEADER_VER      [1]
KERNEL_SZ       [25263361]
RAMDISK_SZ      [0]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
PATCH_LEVEL     [2018-12]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200,n8 androidboot.console=ttyMSM0 earlycon=msm_serial_dm,0xc170000 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 sched_enable_hmp=1 sched_enable_power_aware=1 service_locator.enable=1 swiotlb=1 firmware_class.path=/vendor/firmware_mnt/image loop.max_part=7 buildvariant=user androidboot.verifiedbootstate=green androidboot.selinux=permissive]
CHECKSUM        [e31b4bf851cb8a61f0a721e2b865a84f5b9167c2]
DTB             [12122617]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [raw]
- Checking ramdisk status
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
- Stock boot image detected
- Backing up stock boot image
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
Compressing to [stock_boot_c6b58978a496f9fb915deb88d0fc7e72eda4cd1c.img.gz]
cp: can't stat 'ramdisk.cpio': No such file or directory
- Patching ramdisk
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
Add entry [init] (0750)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Segmentation fault
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
- Repacking boot image
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/dev/block/mmcblk0p60]
HEADER_VER      [1]
KERNEL_SZ       [25263361]
RAMDISK_SZ      [0]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
PATCH_LEVEL     [2018-12]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200,n8 androidboot.console=ttyMSM0 earlycon=msm_serial_dm,0xc170000 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 sched_enable_hmp=1 sched_enable_power_aware=1 service_locator.enable=1 swiotlb=1 firmware_class.path=/vendor/firmware_mnt/image loop.max_part=7 buildvariant=user androidboot.verifiedbootstate=green androidboot.selinux=permissive]
CHECKSUM        [e31b4bf851cb8a61f0a721e2b865a84f5b9167c2]
DTB             [12122617]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [raw]
Repack to boot image: [new-boot.img]
HEADER_VER      [1]
KERNEL_SZ       [25263361]
RAMDISK_SZ      [0]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
PATCH_LEVEL     [2018-12]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200,n8 androidboot.console=ttyMSM0 earlycon=msm_serial_dm,0xc170000 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 sched_enable_hmp=1 sched_enable_power_aware=1 service_locator.enable=1 swiotlb=1 firmware_class.path=/vendor/firmware_mnt/image loop.max_part=7 buildvariant=user androidboot.verifiedbootstate=green androidboot.selinux=permissive]
CHECKSUM        [e31b4bf851cb8a61f0a721e2b865a84f5b9167c2]
MagiskBoot v18.0(18000) (by topjohnwu) - Boot Image Modification Tool
Cleaning up...
- Flashing new boot image
- Unmounting partitions
- Done

**Comment by sajibhasan3343** [comment]
Helpful

**Comment by topjohnwu** [comment]
#980

**Comment by sajibhasan3343** [comment]
Yes
