### ISSUE TITLE
How do I verify the Magisk zip against your private key?

### ISSUE THREAD

**Issue by soaringowl2145** [topjohnwu/Magisk#961]
I would like to be able to verify that the Magisk zip was indeed downloaded successfully and was not tampered with.  I know you said that we can use keytool but nowhere in your documentation have I found what the correct output of the command should be.

What is the correct signature of the key?

**Comment by soaringowl2145** [comment]
Plus that also does not answer the question of what is the key signature.

**Comment by MPeti1** [comment]
I don't really know how it does, but you can take a look at the sources. If you don't understand it I could take a look at it.

**Comment by 211217613** [comment]
@soaringowl2145  Are you trying to verify authenticity and integrity via sha256?

**Comment by soaringowl2145** [comment]
> @soaringowl2145 Are you trying to verify authenticity and integrity via sha256?

I'm trying to verify authenticity and integrity in any way at all. The problem is none of this stuff is posted anywhere that is easily accessible to the user, if it is even posted at all! Do you know where I can even find the sha256?

**Comment by 211217613** [comment]
I know exactly what you're talking about. I've asked for these checksums on other projects. 

From what I understand, I **think** the sha25sum would have to be generated during the build process. I haven't looked, but there doesn't seem to be any CI/CD in this project.  The sha256sum would have to generated on the build machine and uploaded.

**Comment by soaringowl2145** [comment]
> I know exactly what you're talking about. I've asked for these checksums on other projects.
> 
> From what I understand, I **think** the sha25sum would have to be generated during the build process. I haven't looked, but there doesn't seem to be any CI/CD in this project. The sha256sum would have to generated on the build machine and uploaded.

So in other words we have to wait for @topjohnwu to give us the info that should have been posted a long time ago?

**Comment by vvb2060** [comment]
Why don't you trust the files downloaded from GitHub, but trust the information(Certificate fingerprints) displayed on the GitHub ?

**Comment by 211217613** [comment]
@vvb2060 That verifies integrity. The artifact that's being downloaded will not be tampered with in transit.

But I think what is trying to be verified is authenticity. The artifact has not been tampered with during the build process. 


AMIRIGHT?

**Comment by soaringowl2145** [comment]
It is not difficult at all even in the least bit to put the signature key along with a checksum somewhere.

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/magisk_files/blob/master/stable.json 
Are you ready to tell me that md5 is not safe?

**Comment by soaringowl2145** [comment]
> https://github.com/topjohnwu/magisk_files/blob/master/stable.json
> Are you ready to tell me that md5 is not safe?

Thank you! Now we are actually getting somewhere. So why is there no md5 for the app?

**Comment by vvb2060** [comment]
you can unzip `magisk.zip` to get app, `common/magisk.apk` .

**Comment by 211217613** [comment]
Md5 is not safe

:)

**Comment by liudongmiao** [comment]
As the zip or apk are signed like jar. You can always to check it. However, you must implement yourself.

Here is someway to check it manually.

```
keytool -printcert -jarfile /path/to/apk_or_zip
# keytool is part of jre/jdk
```

And for apk, there is another way:

```
apksigner verify --print-certs /path/to/apk
# apksigner is part of android build tools
# apksigner cannot handle apk sign v3 well.
```

And if you want to implement by yourself, you can use the hash or entire file of certificate.

```
MD5:  52:23:8D:8C:75:BD:02:D4:ED:73:0D:6D:10:92:FB:82
SHA1: D6:3B:55:48:32:50:82:06:5B:4F:88:62:F6:82:9C:E5:C9:1E:8D:1E
SHA256: B7:AB:38:FA:38:C8:2E:F3:CB:28:B1:F9:04:4C:03:60:79:4A:BF:10:9B:CB:2C:E9:7E:8A:D9:39:D7:36:BD:1F
```

I think it's enough.

**Comment by soaringowl2145** [comment]
> As the zip or apk are signed like jar. You can always to check it. However, you must implement yourself.
> 
> Here is someway to check it manually.
> 
> ```
> keytool -printcert -jarfile /path/to/apk_or_zip
> # keytool is part of jre/jdk
> ```
> And for apk, there is another way:
> 
> ```
> apksigner verify --print-certs /path/to/apk
> # apksigner is part of android build tools
> # apksigner cannot handle apk sign v3 well.
> ```
> And if you want to implement by yourself, you can use the hash or entire file of certificate.
> 
> ```
> MD5:  CE:DA:68:C1:E1:74:71:0A:EF:58:89:7D:AE:6E:AB:4F
> SHA1: DC:0F:2B:61:CB:D7:E9:D3:DB:BE:06:0B:2B:87:0D:46:BB:06:02:11
> SHA256: B4:CB:83:B4:DA:D9:9F:99:7D:BE:87:2F:01:3A:A1:6C:14:EE:C4:1D:16:70:21:F3:71:F7:E1:33:0F:27:3E:E6
> ```
> I think it's enough.

Now that this is solved, can someone PLEASE put this here:

https://github.com/topjohnwu/Magisk

Perhaps below the "Building Notes and Instructions" would be the perfect place for this? This way it is easily accessible for everyone without having to search endlessly.

Thank you!
