### ISSUE TITLE
OutOfMemoryException on Direct Install

### ISSUE THREAD

**Issue by MPeti1** [topjohnwu/Magisk#966]
If I choose Direct Install in the Update Magisk menu in Magisk Manager, I always get a RuntimeException stating that an OutOfMemory error occurred while executing an AsyncTask.
Here is the crash log: https://gist.github.com/MPeti1/1493fc126877477fd56adbec0e127326

I've a Xiaomi Redmi 3S Prime, it has MIUI 8 (SDK 23) on it. It has 3 GB of ram, returns 192 for ActivityManager.getMemoryClass() and 384 for ActivityManager.getLargeMemoryClass(), so I think it should have enough memory to decompress the zip file

**Comment by topjohnwu** [comment]
@MPeti1 you have to report bugs with debug builds. The stacktrace you provided cannot tell me anything

**Comment by MPeti1** [comment]
Here is the crash log from canary build: https://gist.github.com/MPeti1/04f2a62e7f930726e352948988244cd9

**Comment by MPeti1** [comment]
I've taken a look on the referenced issue and an other issue referenced in #952, and seen that they are pretty fresh. Just to clarify, I have this issue since Direct Install came out, but I only found 2 days ago that the main Magisk repo (this) accepts issues.

**Comment by MPeti1** [comment]
Error persists on 6.1.0-1d9c4410 canary with [this crash log](https://gist.github.com/MPeti1/5069d6dd40d1472040e2b5571e855d8d)
