### ISSUE TITLE
BACON + POSP 2.1 + Magisk 18 = Stuck on Boot screen.

### ISSUE THREAD

**Issue by itsbhanusharma** [topjohnwu/Magisk#974]
My Device: OnePlus One (bacon) 64 GB
ROM: POSP (potatoproject.co) - [v2.1](https://mirror.potatoproject.co/bacon/weeklies/potato_bacon-9-20190114.Baked-v2.1.WEEKLY.zip)
Magisk Version - 18.0 

Magisk 18 was working fine on a previous version of the same rom, two days ago the devs released the above linked update and my phone was stuck on the oneplus boot logo. 
I uninstalled magisk to be able to use the ROM again. 

Installing version 17.1 works (kind of) but it isn't detected in latest version of ROM for some reason. Installing magisk manager reports magisk not installed. 

I was nagging the developers of rom and they suggested to create the issue here. 

I can provide any logs/reports etc. if you enlighten me how to do the same.

**Comment by topjohnwu** [comment]
Magisk works on AOSP, and it used to work on the ROM. How is this a Magisk problem?

**Comment by zeeshanmuhammad** [comment]
I am also experiencing the same issue on my OnePlus One (bacon) device.

I am using potato_bacon-9-20190212.Baked-v2.1.WEEKLY.zip, with open_gapps-arm-9.0-micro-20190209.zip and Magisk-v18.1.zip (flashed in that order) via twrp-3.2.3-0-bacon.img for TWRP recovery.

I can confirm that the device gets stuck on the OnePlus boot icon and never enters into the Android / POSP boot animation.

I have cleared the Dalvik cache, system, data and cache partitions.

If I flash as above without Magisk-v18.1.zip , the whole thing works nicely.

**Comment by gotzl** [comment]
With v20.1 of Magisk, I have still the same issues as the OS. I've the same device, my version of POSP is 2.3, though.

I found, that v17.2 of Magisk worked, while v17.3 left me stuck at the OPO boot screen.
I've bisected between the two versions, with the following result:
```
$ git bisect bad
dd9ddd20195872e0c63cc85bfd269b22935e899f is the first bad commit
commit dd9ddd20195872e0c63cc85bfd269b22935e899f
Author: topjohnwu <topjohnwu@gmail.com>
Date:   Sat Oct 20 00:23:07 2018 -0400

    Remove unnecessary instruction from Defex hexpatch
    
    Close #489

 scripts/boot_patch.sh | 8 +++-----
 1 file changed, 3 insertions(+), 5 deletions(-)
```

Maybe you have an idea why this seems to be needed ?
v20.1 boots for me after reverting that particular commit.
