### ISSUE TITLE
Please help Magiskboot

### ISSUE THREAD

**Issue by Mavigsm** [topjohnwu/Magisk#976]
Magiskboot unpack repack boot.img windows console app source Thank you my master

**Comment by Mavigsm** [comment]
Why is that? you are afraid to answer

**Comment by Weasley-J** [comment]
Hello, Could you tell me how to bulid a console magisk.exe, I want to it to mod boot.img on cmd console, I used the NDK  ---  FrankeNDK topjohnwu provided then an ERROR as follow:
![图片](https://user-images.githubusercontent.com/47849474/60520523-23fbef00-9d18-11e9-8918-563c34988569.png)
Help~Please

**Comment by Weasley-J** [comment]
I have set ENV for FrankeNDK topjohnwu provided in my path.
