### ISSUE TITLE
Unsupported device: Moto G4 Plus ATHENE NPJ25.93-14 Android 7.0

### ISSUE THREAD

**Issue by blap** [topjohnwu/Magisk#98]
Unsupported device: Moto G4 Plus ATHENE NPJ25.93-14 Android 7.0
Do not start device...
[boot.zip](https://github.com/topjohnwu/Magisk/files/805417/boot.zip)

**Comment by fridewald** [comment]
Same here with the Moto G4 Athene xt1622 android 7.0.
ElementalX Kernel + superSU 2.79 SR3 already working.
Installation in TWRP works fine, only get a prompt "Failed to mount '/data' (Invalid argument)".
When trying to reboot, will start with boot animation and then turn off again
[boot-brokenMagisk.zip](https://github.com/topjohnwu/Magisk/files/838494/boot-brokenMagisk.zip)

**Comment by 3onyc** [comment]
Exact same issue here with the Motorla Moto G4 Plus (XT1642) Running NPJ25.93-14

[xt1642-magisk-boot.zip](https://github.com/topjohnwu/Magisk/files/848679/xt1642-magisk-boot.zip)

**Comment by 3onyc** [comment]
As a workaround, you can install the [ElementalX kernel](https://forum.xda-developers.com/moto-g4-plus/development/kernel-elementalx-g4-0-01-t3424836), I've flashed it & magisk and that seems works correctly.

**Comment by topjohnwu** [comment]
I think all Moto issues are fixed
