### ISSUE TITLE
Incompatible With System-As-Root Without Ramdisk

### ISSUE THREAD

**Issue by topjohnwu** [topjohnwu/Magisk#980]
Many Chinese devices uses system as root without ramdisk block. A fix shall come soon (please check #1102)

**Comment by xiaowyyyyya** [comment]
Great to see your reply, really appreciate that! And by the way, is not only Chinese MIUI not working, all of the 3rd party AOSP, MIUI are not working too. Hopefully you can find the way to make it work! Thank you very much!

**Comment by DeliriousMetro** [comment]
That is a bit strange.

I own an Mi 6X which runs the custom rom - Xiaomi.eu (which is based off the China base rom) and Magisk 18.0 works fine on it and other versions too.

It does lag out if you install Magisk straight after the rom, I would have to install the rom first and wipe cache then boot up and then flash Magisk. If you install Magisk straight after the rom installation including a wipe without boot, the device will lag out a lot.

**Comment by xiaowyyyyya** [comment]
> That is a bit strange.
> 
> I own an Mi 6X which runs the custom rom - Xiaomi.eu (which is based off the China base rom) and Magisk 18.0 works fine on it and other versions too. Infact, I have been running Magisk 17.X since purchasing the phone when it came out.
> 
> It does lag out if you install Magisk straight after the rom, I would have to install the rom first and wipe cache then boot up and then flash Magisk. If you install Magisk straight after the rom installation including a wipe without boot, the device will lag out a lot.
> 
> Seeing the reports about Magisk not working on Mi 8 SE on the thread over at Xiaomi.eu makes me think this might be a device specific matter?

It is a device specific issue, it's just for Mi 8 SE

**Comment by xiaowyyyyya** [comment]
@topjohnwu this is a device specific issue related to Mi 8 SE, not for all Xiaomi devices.

**Comment by solidv** [comment]
Same problem with Mi 8 SE, last magisk to work is version 16.6

**Comment by kissunyeason** [comment]
just xiaomi 8se，not all xiaomi device

**Comment by xiaowyyyyya** [comment]
@isaac chen

**Comment by xiaowyyyyya** [comment]
@tingyichen

**Comment by xiaowyyyyya** [comment]
@topjohnwu I personally did some research based on this issue, and it seems that most of the ### **Snapdragon 710** devices (Xiaomi M8 SE, Smastisan Pro 2S, etc.) have the same issue. Therefore, in conclusion, I think Magisk is somehow incompatible with **Snapdragon 710**, not only Xiaomi devices.

**Comment by topjohnwu** [comment]
The PR #1102 will soon be integrated into Magisk after thorough testing. Please stay tuned!

**Comment by Dodgexander** [comment]
> The PR #1102 will soon be integrated into Magisk after thorough testing. Please stay tuned!

fantastic news, thanks so much @topjohnwu

**Comment by Dodgexander** [comment]
Since v19 this doesn't seem to work any more.

**Comment by RedCriterion** [comment]
This is still a problem for me. Any Version above 16.7 results in a Boot-to-recovery.
Axon 7 Mini

**Comment by Dodgexander** [comment]
Still need to use a patched boot image together with custom signed modules to get it to work on Axon 7.

**Comment by bluenote73** [comment]
I've just tried v19.1 with axon7 as documented in #729 and the behaviour is the same. 
If we could get that issue reopened?

**Comment by RedCriterion** [comment]
tried newest canary 19.2 (19102) - still not working

**Comment by SL-TX** [comment]
ZTE Blade V9 same issue. Last working magisk 16.7

**Comment by AndGuz** [comment]
Same issue here on ZTE ZMAX PRO, last compatible version is 16.6. whatever version higher than 16.6 makes the device to boot to recovery always.

**Comment by color-space** [comment]
yes its unbelievable my reopening of issues is always getting closed, altough obviously on zte devices anything newer than 16.6 does not work

**Comment by itsjoeoui** [comment]
> yes its unbelievable my reopening of issues is always getting closed, altough obviously on zte devices anything newer than 16.6 does not work

RIP
