### ISSUE TITLE
Magisk Manager stopped working on startup

### ISSUE THREAD

**Issue by MPeti1** [topjohnwu/Magisk#981]
Earlier I've installed a debug build to help solve #966, and that started to notify me that my device requires additional setup. First I've ignored that because I wanted to revert to a release build soon, but today I wanted to use an updated root app so Magisk took the permission from it, and for some reason it wasn't able to acquire it again. Then I went to the Superuser tab of the Manager, and the app list was empty. Then I decided to run that additional setup recommended by the Manager, and from now on it instantly crashes on startup. even after I updated it today. It seems that the problem is actually 2 problems:

The problem itself that causes the crash is in libsu, but I've taken a look on the [crash log](https://gist.github.com/MPeti1/31b4f5aca7aada48e31b025939151e2a) and that does not make sense to me because you don't try to get any array's length at that line, not even in previous versions, however I remember that in the past it did return a null array if there were no results in listFiles().

But the main problem is unknown to me. Is it a proper thing to just install the canary build over the release?

Please note that at the moment I've the 6.1.0-1d9c4410, 175 canary build installed but still Magisk 17.1 to be able to test Direct Install, and I've rebooted the phone.

**Comment by MPeti1** [comment]
Almost forgot about the Magisk log
[magisk.log](https://github.com/topjohnwu/Magisk/files/2776083/magisk.log)

**Comment by MPeti1** [comment]
After restoring app and app data with Titanium Backup it's working again, and updated app was able to acquire root, but after installing the canary build again the Superuser menu's app list is empty again. Maybe it has to do something with the settings resetted

**Comment by topjohnwu** [comment]
I would need a install log to know what's going on

**Comment by MPeti1** [comment]
Sorry, what do you mean? According to Didgeridoohan's tutorial install log can be saved after installing Magisk or a module, but I just updated to Manager. This means I need to reinstall Magisk with the app after updating to the canary channel?

**Comment by malnvenshorn** [comment]
I'm having the same issue. Magisk Manager canary build d73127b1 crashes right on start.
Updated from 6.0.1, Magisk 17.3 is installed.

```
01-22 14:17:17.156  3999  4192 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 3999
01-22 14:17:17.156  3999  4192 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
01-22 14:17:17.156  3999  4192 E AndroidRuntime: 	at com.topjohnwu.superuser.io.SuFile.trans(SuFile.java:238)
01-22 14:17:17.156  3999  4192 E AndroidRuntime: 	at com.topjohnwu.superuser.io.SuFile.listFiles(SuFile.java:251)
01-22 14:17:17.156  3999  4192 E AndroidRuntime: 	at com.topjohnwu.core.utils.Utils.lambda$loadModules$3(Utils.java:102)
01-22 14:17:17.156  3999  4192 E AndroidRuntime: 	at com.topjohnwu.core.utils.-$$Lambda$Utils$VgceUhXhXqGxQ0kobo-J3vKPS1A.run(lambda)
01-22 14:17:17.156  3999  4192 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-22 14:17:17.156  3999  4192 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-22 14:17:17.156  3999  4192 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```

How do I get the install log?

**Comment by MPeti1** [comment]
Error persists in latest (version code 175) canary.

**Comment by MPeti1** [comment]
I've set a breakpoint [at the first line](https://github.com/topjohnwu/libsu/blob/99c8a430bceefcd0e6904bdb48ab1168d9a3fc1d/io/src/main/java/com/topjohnwu/superuser/io/SuFile.java#L238) of SuFile.trans() and it seems that it tries to list `/sbin/.magisk/img` folder. In Magisk 17.1 `.magisk` is named `.core`, and so the file listing does not find any files. But because the `File[] list` itself is null, it's length can't be read in the next line.

**Comment by topjohnwu** [comment]
@MPeti1 v18 is already out for a long time, as mentioned in the last release notes Magisk Manager will no longer support anything lower than v18 (there are tons of other stuffs that is changed in v18 other than the paths). Backwards compatibility within the app is becoming a mess, that's why I came to this decision.

**Comment by malnvenshorn** [comment]
@topjohnwu Whats the proper way to update Magisk in this case? On XDA you wrote `If you already have Magisk installed, it is strongly recommended to upgrade directly via Magisk Manager`.

Just flashing the new Magisk version via TWRP or do I have to use the uninstaller before?

**Comment by MPeti1** [comment]
Sorry then, in the future I'll be more careful. But still, I think it shouldn't crash because of that. It could recommend to update Magisk immediately, and it wouldn't even need any backwards compatibility, because rebooting to recovery and installing the zip via that doesn't depend on the current Magisk version

**Comment by malnvenshorn** [comment]
@topjohnwu Any chance to get an answer? Updating through the manager is not possible because it only ask to install an update to itself. And updating with the newest version of the manager is not possible because it crashes :confused:
