### ISSUE TITLE
documents.ui (stock file manager) debug info breaks after magisk installation

### ISSUE THREAD

**Issue by vivekjindal** [topjohnwu/Magisk#982]
once magisk is installed stock file manager (com.android.documentsui) will no longer show debug info.

tested plaform: android pie, havoc os, magisk 18.0

tried magisk hide on app.

let me know if you need any additional info or logs.

**Comment by topjohnwu** [comment]
This is 99% caused by the fact that MagiskHide will force revert `ro.build.type` from `userdebug` to `user`. Nothing to fix here.

**Comment by Didgeridoohan** [comment]
@vivekjindal You can test by disabling MagiskHide and if it starts workning after that you can use the MagiskHide Props Config to revert that particular prop even with MagiskHide enabled.

**Comment by vivekjindal** [comment]
Changing the ro.build.type value from user to userdebug didn't resolve the issue. However, disabling the MagiskHide feature solves the issue. Any other way to solve this while keeping MagiskHide enabled?

**Comment by Didgeridoohan** [comment]
Try reverting the other MagiskHide props as well, one by one until you find the culprit (if it's caused by one of those)...

**Comment by vivekjindal** [comment]
tried all possible settings in props. it didn't work. debug info is displayed only when MagiskHide is enabled. Can you tell which prop files MagiskHide functionality is touching? I was studying MagiskHide activity but given my limited knowledge of programming I couldn't figure it out.
