### ISSUE TITLE
magisk patched boot.img - breaks boot 

### ISSUE THREAD

**Issue by hyakki-** [topjohnwu/Magisk#984]
Hi I was hoping you could take a look at my boot image, this is for a tv box ugoos am3/  android 7.1.2 (amlogic S912 chipset), 

if I patch this boot image using Magisk Manager the box fails to boot completely, it doesn't even make it to the second boot logo, patching appears to go fine with no errors, same if I flash Magisk from TWRP, no complaints or errors but for some reason it fails to boot.

it seems like if anything modifys the ramdisk it will fail to boot, it's really strange I can't figure it out and not sure how to log this since its pre-boot.

Thanks..
I have tried Magisk 16 - Magisk 18 and the Canary builds with the same result.

[stock_boot_f4f6bb3d7d060bbc34af8a9e149f4158d1027296.zip](https://github.com/topjohnwu/Magisk/files/2778721/stock_boot_f4f6bb3d7d060bbc34af8a9e149f4158d1027296.zip)

**Comment by nitramwin** [comment]
I just wanted to write that I am having the same issue on new install of Magisk v18 or upgrade from v17.2. The second boot screen (of the OS) does not appear. Furthermore, the recovery-based uninstall does not seem to revert to the original behavior. I expect that the install has modified a file that cannot be reverted during uninstall.

**Comment by hyakki-** [comment]
update I think it may be a problem with magiskinit , i tried running it from shell and it seg faults

`
[   92.656332@3] magiskinit[7128]: unhandled level 3 translation fault (11) at 0xffffffff, esr 0x92000007
[   92.660278@3] pgd = ffffffc04356f000
[   92.663523@3] [ffffffff] *pgd=00000000138c0003, *pmd=00000000082ef003, *pte=0000000000000000
[   92.671883@3]
[   92.673529@3] CPU: 3 PID: 7128 Comm: magiskinit Tainted: G        W  O 3.14.29 #53
[   92.681064@3] task: ffffffc020a07000 ti: ffffffc027ebc000 task.ti: ffffffc027ebc000
[   92.688651@3] PC is at 0x36c30
[   92.691649@3] LR is at 0x8965
[   92.694568@3] pc : [<0000000000036c30>] lr : [<0000000000008965>] pstate: 20000010
[   92.702123@3] sp : 00000000fffae1e8
[   92.705524@3] x12: 00000000fffae130
[   92.709060@3] x11: 0000000000000001 x10: 00000000fffaf378
[   92.714491@3] x9 : 000000000004822f x8 : 000000000004820e
[   92.719936@3] x7 : 00000000fffaf3e0 x6 : 00000000ffffffff
[   92.725358@3] x5 : 0000000000000000 x4 : 00000000ffffffff
[   92.730792@3] x3 : 0000000000000001 x2 : 0000000000000020
[   92.736225@3] x1 : 000000000004820e x0 : 00000000ffffffff
[   92.741659@3]

`

**Comment by BruXy** [comment]
I have tried patching again, providing `magisk_install_log` (I did not tried flash boot again, but checksum of the `patched_boot.img` is the same:

```
Magisk-v18.1(18100).zip
MagiskManager-v7.0.0.apk
boot.img
magisk_install_log_20190204_223651.log
patched_boot.img
[root@notebook taimen-pq1a.181105.017.a1]# adb shell cat /storage/emulated/0/Download/magisk_install_log_20190204_223651.log
- Copying image to cache
- Device platform: arm64-v8a
- Downloading zip
... 0%
1038+1 records in
1038+1 records out
1063528 bytes transferred in 0.006 secs (177254666 bytes/sec)
- Unpacking boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [15155388]
RAMDISK_SZ      [9915831]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
PATCH_LEVEL     [2018-11]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200,n8 earlycon=msm_serial_dm,0xc1b0000 androidboot.hardware=taimen androidboot.console=ttyMSM0 lpm_levels.sleep_disabled=1 user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3 service_locator.enable=1 swiotlb=2048 firmware_class.path=/vendor/firmware loop.max_part=7 raid=noautodetect usbcore.autosuspend=7 androidboot.dtbo_idx=12 buildvariant=user]
CHECKSUM        [5f84318b85ea12347b32b976d3a22827db35ab1c]
DTB             [392041]
KERNEL_FMT      [lz4]
RAMDISK_FMT     [gzip]
- Checking ramdisk status
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Backing up stock boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Compressing to [stock_boot_5ec2e06639fc086d1f78e60813378199ab978ab6.img.gz]
- Patching ramdisk
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Patch @ 0185B06E [736B69705F696E697472616D667300]->[77616E745F696E697472616D667300]
- Repacking boot image
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [15155388]
RAMDISK_SZ      [9915831]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
PATCH_LEVEL     [2018-11]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200,n8 earlycon=msm_serial_dm,0xc1b0000 androidboot.hardware=taimen androidboot.console=ttyMSM0 lpm_levels.sleep_disabled=1 user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3 service_locator.enable=1 swiotlb=2048 firmware_class.path=/vendor/firmware loop.max_part=7 raid=noautodetect usbcore.autosuspend=7 androidboot.dtbo_idx=12 buildvariant=user]
CHECKSUM        [5f84318b85ea12347b32b976d3a22827db35ab1c]
DTB             [392041]
KERNEL_FMT      [lz4]
RAMDISK_FMT     [gzip]
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [15153974]
RAMDISK_SZ      [10153739]
SECOND_SZ       [0]
EXTRA_SZ        [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
PATCH_LEVEL     [2018-11]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200,n8 earlycon=msm_serial_dm,0xc1b0000 androidboot.hardware=taimen androidboot.console=ttyMSM0 lpm_levels.sleep_disabled=1 user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3 service_locator.enable=1 swiotlb=2048 firmware_class.path=/vendor/firmware loop.max_part=7 raid=noautodetect usbcore.autosuspend=7 androidboot.dtbo_idx=12 buildvariant=user]
CHECKSUM        [581967149fe8cf202725795384717c3da0473362]
MagiskBoot v18.1(18100) (by topjohnwu) - Boot Image Modification Tool
Cleaning up...

****************************
 Patched image is placed in 
 /storage/emulated/0/Download/patched_boot.img 
****************************
- All done!

```

**Comment by nitramwin** [comment]
Closed because it is solved or no boot img?
