### ISSUE TITLE
Ing Bank app might have busted MagiskHide

### ISSUE THREAD

**Issue by djechelon** [topjohnwu/Magisk#985]
Hi,

I am customer of ING Bank and use their [app](https://play.google.com/store/apps/details?id=it.ingdirect.app). The app is publicly downloadable and **does not require log in** to test for root detection.

The application does not **yet** _prevent_ root users from logging in, but I am afraid that in the future, once they implement NFC payment, things will get harder.

I use Magisk 18.0 on Pixel 3XL and until the app's last update, MagiskHide successfully hid itself from ING. After the most recent app update, and perhaps after a temporary crash of Magisk which revealed root to SafetyNet and all the apps, ING started to recognize me as root and displayed a warning on its main screen.

I applied the latest OTA from Google (yes, I was a bit behind updates), and **before** flashing Magisk I gave another try to ING. Still, I was detected as root even with stock firmware.

I reinstalled Magisk nonetheless, reapplied MagiskHide to all apps I was interested in and wiped Cache/Dalvik.

Today...

- Magisk's SafetyNet passes
- Google Play Store recognizes the device as Certified. Netflix app is downloadable
- Google Pay does not detect root and doesn't prevent me to add cards (disclaimer: I am prevented to add my card because it's unsupported, but Pay normally checks SafetyNet before checking the card)
- Other apps I hid in MagiskHide do not recognize me as root
- _ING still recognizes me as root_

I have no evidence suggesting me that since this last update once ING detects a hardware device ID that does not pass SafetyNet it will display the warning forever.

I have no evidence suggesting that SafetyNet was updated to detect if the bootloader is unlocked. In fact, when I flashed OTA, I was still unlocked.

I have no evidence suggesting that ING is using a brand new mechanism to detect root.

I am providing the link to the official Play Store listing, I can easily extract the APK from phone in case someone wants to take deeper analysis on it.

The application is fully localized in Italian. The presence of a warning ⚠together with a message as follows indicates that you have been busted as root. Its absence means you are either stock or undetected

> Consigliamo di installare ed utilizzare l'App su dispositivi con sistema operativo autorizzato e certificato Android. Nel caso in cui il tuo dispositivo abbia subito un processo di rooting non è possibile garantire il corretto funzionamento e la completa sicurezza dell'App ING Italia

**Comment by Didgeridoohan** [comment]
Tested. No problems hiding root from the app in question.

You can close this issue.

**Comment by djechelon** [comment]
Have you tried running the app once without Magisk Hide enabled? I continue to get the same issue. No other root app is busted. SafetyNet passes. Tried to wipe application data.

Any help I can provide? Logs etc?

**Comment by Didgeridoohan** [comment]
I've tested with the app both off and on the Hide list, and with the Manager both repackaged and not. The app needs to be on the Hide list and the Magisk Manager need to be hidden, or I'll see the warning message.

**Comment by djechelon** [comment]
Confirmed repackaging Magisk blew the warning up. It is likely that the application has a list of known roo-manager package names. I totally forgot about Manager Hide feature.

**Comment by enetec1** [comment]
This ticket shouldn't be closed... App is still sometimes capable to detect root...

**Comment by kam821** [comment]
@enetec1 
There is one obvious method to detect Magisk using the fact that MagiskHide does not work properly for applications with an isolated context
https://github.com/topjohnwu/Magisk/issues/2406

**Comment by djechelon** [comment]
@enetec1 I am not getting any more true positives from Ing. Perhaps your problem might be that Magisk became unstable on your device. I doubt that the bank already implemented isolated context, at least till they still don't offer mobile payment options (which is the mail leverage of anti root detection)

**Comment by enetec1** [comment]
To be honest ING app has a very weird behaviour... 
I've no issues with Google Pay and Sky Go (two of the hardest app in Italy...) and with Fineco bank app too. 
Ing with same settings was able to detect root (& show a warning splash screen...).
Changing name to Magisk Manager app it worked fine for a while... now it's some days that of my two identical devices (really identical, even with apps and files...) on one it works fine and on the other I have warning splash. 
I'll try to understand because of this behaviour and I would update here eventually...

**Comment by enetec1** [comment]
Some updates... I've found ING app makes use of IBM Trusteer solution to "detect compromised mobile devices"... connecting to trusteer.com on startup. 

I've so inhibited this access to app using AdAway blacklist. 

Still not solved for now (I can't reset app so often since I've token enabled and I need it daily...) BUT app still works fine and I'm sure this could be a needed first step. 

More, on the second device I've already seen warning splash screen to go away without resetting app, so it could fix itself in some days... 

Anyway I think this app would eventually require a specific module to be maintained "safe" at the end and not a simple Magisk Hide setting...  :/

**Comment by djechelon** [comment]
That's very strange. My warning from ING disappears immediately once I restore Hide.

I think you need to reset your entire device for once at least

**Comment by enetec1** [comment]
This ia not so strange... look in /data/data/it.ingdirect.app/tas/_dd_riskscore/  ;)

**Comment by enetec1** [comment]
A simple device reboot after blocking (by AdAway...) the Trustee site access solved on my second device. 
Before reboot every tries I made was no success...

**Comment by cr1cr1** [comment]
Latest version may look for the "su" binary in the path :)

Speculation:

```java
    public static boolean isRooted() {
        try {
            return searchPathForBinary("su");
        } catch (Exception e) {
            DeviceLog.exception("Rooted check failed", e);
            return false;
        }
    }


...

    private static boolean searchPathForBinary(String str) {
        File[] listFiles;
        for (String file : System.getenv("PATH").split(":")) {
            File file2 = new File(file);
            if (file2.exists() && file2.isDirectory() && (listFiles = file2.listFiles()) != null) {
                for (File name : listFiles) {
                    if (name.getName().equals(str)) {
                        return true;
                    }
                }
                continue;
            }
        }
        return false;
    }

---

hashMap3.put("rooted", isRooted());

    protected static Boolean isRooted() {
        String str = Build.TAGS;
        if (str != null && str.contains("test-keys")) {
            return true;
        }
        String[] strArr = {"/data/local/bin/su", "/data/local/su", "/data/local/xbin/su", "/sbin/su", "/su/bin", "/su/bin/su", "/system/app/SuperSU", "/system/app/SuperSU.apk", "/system/app/Superuser", "/system/app/Superuser.apk", "/system/bin/failsafe/su", "/system/bin/su", "/system/sd/xbin/su", "/system/xbin/daemonsu", "/system/xbin/su"};
        int i = 0;
        while (i < 15) {
            try {
                if (new File(strArr[i]).exists()) {
                    return true;
                }
                i++;
            } catch (RuntimeException e) {
                Log.e("o.b.g.d.a.a", "Exception while attempting to detect whether the device is rooted", e);
            }
        }
        return false;
    }


```

**Comment by enetec1** [comment]
Upgraded to latest Magisk Manager, now root is undetected. 
I had and still have different name for Magisk Manager and unchanged settings. 
Probably ING app was capable to see Magisk Manager app anyway and no more with new version... :?

**Comment by pocheche** [comment]
I have the same problem, disabling Addaway while opening ING app solved the issue.
