### ISSUE TITLE
Magisk Manager crashes when settings are opened

### ISSUE THREAD

**Issue by AleD219** [topjohnwu/Magisk#986]
01-22 17:13:35.528  9000  9000 D AndroidRuntime: Shutting down VM
01-22 17:13:35.529  9000  9000 E AndroidRuntime: FATAL EXCEPTION: main
01-22 17:13:35.529  9000  9000 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 9000
01-22 17:13:35.529  9000  9000 E AndroidRuntime: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:283)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at androidx.preference.Preference.d(Unknown Source:22)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at androidx.preference.ListPreference.a(Unknown Source:2)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at androidx.preference.Preference.a(Unknown Source:59)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at androidx.preference.Preference.a(Unknown Source:6)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at androidx.preference.PreferenceGroup.a(Unknown Source:146)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.lp.a(Unknown Source:115)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.lp.a(Unknown Source:118)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.lp.a(Unknown Source:41)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.lp.a(Unknown Source:12)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.lq.a(Unknown Source:9)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.yp.b(Unknown Source:8)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.ln.a(Unknown Source:66)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.jl.h(Unknown Source:13)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.jr.a(Unknown Source:340)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.jx.a(Unknown Source:190)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.jx.a(Unknown Source:18)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.jx.a(Unknown Source:46)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.jr.a(Unknown Source:109)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.jr.b(Unknown Source:88)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.jr.b(Unknown Source:31)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.ji.e(Unknown Source:6)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.wr.a(Unknown Source:23)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.wr.b(Unknown Source:29)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.wr.b(Unknown Source:4)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.wr.lambda$mbNp5yay80CSCUlF30REOmuoVMY(Unknown Source:0)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at a.-$$Lambda$wr$mbNp5yay80CSCUlF30REOmuoVMY.run(Unknown Source:4)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6739)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
01-22 17:13:35.529  9000  9000 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
01-22 17:13:35.533  1325  5799 W ActivityManager:   Force finishing activity com.topjohnwu.magisk/a.b

latest magisk canary.

**Comment by topjohnwu** [comment]
Fixed here, thanks for the report.
118a9f224e985db2dc5aeab81b63adc82bc1b539

**Comment by AleD219** [comment]
I still have the same problem, thought
