### ISSUE TITLE
Magisk 11.1 SafetyNet not passed

### ISSUE THREAD

**Issue by Artrix** [topjohnwu/Magisk#99]
I have Xiaomi Mi5 with miui 8.1.4.0, on Magisk v9 all work and safetynet is passed, on Magisk 11.1 cts profile mismatch. And app allegro (app for shopping) see root, app is added to hide in Magisk. 

Log from app: http://pastebin.com/C16H9H3K

**Comment by amarpreetosahan** [comment]
I confirmed that issue

**Comment by andrewleech** [comment]
I've been investigating this issue and discussing some workarounds here:
https://forum.xda-developers.com/mi-5/how-to/mi-5-passing-safetynet-unlocked-t3557845/post71119896#post71119896

Basically for any MIUI based roms I've tested safetynet passes with magisk v9 and phh-superuser-magisk-r266-2 as long as your build fingerprint matches a cts passing (stable) version (I've got a magisk module which will set this for you). I've done this on a few roms developer and a number of realeases of xiaomi.eu roms.

magisk v11.1 release and beta v12 fail both cts and basic integrity. 

I've got twrp recovery install log and logcat's of running magisk manager safetynet check attached here for both v9 and v12beta
the v12beta logcat also includes trying to run safetynet helper as well.

Before each test the boot image was reflashed in twrp to the original image for my rom.

My module to set props relating to safetnet passing, this was installed and enabled for all tests below:
[magisk-safetynet-props.zip](https://github.com/topjohnwu/Magisk/files/846225/magisk-safetynet-props.zip)

v9 testing
[recovery_v9_phh_install.txt](https://github.com/topjohnwu/Magisk/files/846229/recovery_v9_phh_install.txt)
[logcat_v9_safetynet_check.txt](https://github.com/topjohnwu/Magisk/files/846226/logcat_v9_safetynet_check.txt)
[magisk_error_log_v9.txt](https://github.com/topjohnwu/Magisk/files/846231/magisk_error_log_v9.txt)

v12 beta testing
[recovery_v12_170312_install.txt](https://github.com/topjohnwu/Magisk/files/846232/recovery_v12_170312_install.txt)
[logcat_v12_safetynet_check.txt](https://github.com/topjohnwu/Magisk/files/846233/logcat_v12_safetynet_check.txt)
[magisk_error_v12.txt](https://github.com/topjohnwu/Magisk/files/846234/magisk_error_v12.txt)

I'd be happy to help further in diagnosing the regression in v11 / v12
Cheers.
