### ISSUE TITLE
magisk fails to pass safety net on GSI pie roms 

### ISSUE THREAD

**Issue by TaifAljaloo** [topjohnwu/Magisk#996]
Hello everybody 
glad to discuss with you again, im opening this issue due to the high demands on this problem
so to resume this problem on **GSI ( generic system image)** roms alot of users facing an issue with latest magisk which is magisk fails everytime to pass the safety net and i can estimate the problem source is rom fingerprint but even trying to use offical fingerprint the same problem come again 
thanks for understanding and help

**Comment by topjohnwu** [comment]
#844
