### ISSUE TITLE
请问吴先生，为什么刷入patched_boot.img 后默认的Magisk.apk 是不完整的？

### ISSUE THREAD

**Issue by 7763sea** [topjohnwu/Magisk#997]
![image](https://user-images.githubusercontent.com/13548133/51890787-f660f180-23d7-11e9-8c6e-26d7a13dcf86.png)

吴先生您好，由于工作原因想让patched_boot.img 默认安装的Magisk.apk 为完整版，因为无法联网。

另外请问是否能告诉我们让Magisk patched_boot.img 默认开启root权限。是否有方法呢？
若有回复感激不尽！

**Comment by topjohnwu** [comment]
因為這個 APK 是直接包在 binary 裡面的，必須要限制大小
你按是之後，它會自動升級最新的 APK，並完成完整設定。

**Comment by 7763sea** [comment]
非常感谢！！！
